### ISSUE TITLE
ResourceSet doesn't work with serialized resources

### ISSUE THREAD

**Issue by filipnavara** [dotnet/corefx#35114]
We are planning to port our WinForms application to .NET Core 3. We've been maintaining the project side-by-side with the one targeting full .NET Framework for a while. Recent optimization we made in the use of RESX resources unfortunately doesn't work on .NET Core currently. We have a workaround, but the problem is likely to bite more people so I am sharing it.

We replaced the standard `ResXFileCodeGenerator` with a T4 script adapted from http://blog.baltrinic.com/software-development/dotnet/t4-template-replace-resxfilecodegenerator. The main change in the generated C# file is that instead of using the `new System.Resources.ResourceManager(typeName, assembly)` constructor with two parameters we use the constructor with there parameters like `new System.Resources.ResourceManager(typeName, assembly, typeof(System.Resources.ResourceSet))`. This causes the resource sets to be typed as `ResourceSet` instead of `RuntimeResourceSet`. The crucial difference is that `ResourceSet` loads all the resources to memory and keeps references to them in a dictionary. On the other hand `RuntimeResourceSet` only keeps the positions of the objects and creates/deserializes them on each access. We specifically want all the resources to be loaded eagerly and kept around because it's images used throughout the application UI that are referenced all the time.

Unfortunately when the resource deserialization code was brought back in .NET Core 3.0 it was enabled only for `RuntimeResourceSet`. The functionality is not enabled for `ResourceSet` and the constructor taking the `deserializationAllowed` parameter is internal. This causes our application to crash on startup when it is used.

**Comment by tarekgh** [comment]
@filipnavara could you point where is the constructor that takes deserializationAllowed as internal?

**Comment by filipnavara** [comment]
@tarekgh Sorry, I skipped one level of indirection in the description. The constructor is on `ResourceReader` here: https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Resources/ResourceReader.cs#L154. And `ResourceSet` can be constructed from the `ResourceReader` (although it's inconvenient way to do it).

**Comment by tarekgh** [comment]
@danmosemsft this is same issue asking enabling the binary formatter serialization in the resources. do you have any conclusion where did we land with this issue?

**Comment by filipnavara** [comment]
It is slightly different from the issues that I have seen before. The code path used by the default `ResXFileCodeGenerator` already allows binary deserialization. I am asking for the same treatment for other code path and/or an explicit constructor for `ResourceReader`/`ResourceSet` that would allow the deserialization.

The least impactful change I can think of is modifying the code here: 

https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Resources/ManifestBasedResourceGroveler.cs#L246

by adding a check for the default `ResourceReader` type (like `CanUseDefaultResourceClasses` above it, but just for the `readerTypeName` and not the `resSetTypeName`) and if the default reader type is used then call the internal constructor with `permitDeserialization: true`.

**Comment by ericstj** [comment]
This seams reasonable.  The IResourceReader is the thing that's managing the stream and doing the serialization, so if we see that readerTypeName is `System.Resources.ResourceReader` ewe can directly invoke that constructor and avoid the CreateInstance call.

**Comment by filipnavara** [comment]
Great. I'll submit a PR shortly.
