### ISSUE TITLE
NetworkStream's ReadAsync Never Fails after ReadTimeout Period is Done

### ISSUE THREAD

**Issue by aliio** [dotnet/corefx#35129]
`NetworkStream`'s `ReadAsync` Never Fails after `ReadTimeout` Period is Done

Here is a small sample to reproduce the problem

```csharp
static void Main(string[] args)
{
    Task.Run(async () =>
    {
        var server = new TcpListener(IPAddress.Any, 8080);
        server.Start();
        var client = server.AcceptTcpClient();
        var stream = client.GetStream();

        var buffer = new byte[128];
        stream.ReadTimeout = 1000;

        try
        {
            await stream.ReadAsync(buffer, 0, buffer.Length);
        }
        catch (Exception e)
        {
            // Reading never fails
            Console.WriteLine("Timed out");
        }
    });
    
    Console.ReadKey();
}
```

The Problem can be reproduced on these configurations:
OS: `macOS 10.14.2`
Framework: `netcoreapp2.2`

Edit:
Just use `telnet localhost 8080` and wait a second

**Comment by stephentoub** [comment]
ReadTimeout only applies to the synchronous operations.  As noted in the docs:
https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.networkstream.readtimeout?redirectedfrom=MSDN&view=netframework-4.7.2#System_Net_Sockets_NetworkStream_ReadTimeout
"This property affects only synchronous reads performed by calling the Read method."

**Comment by davidsh** [comment]
closing as by-design.
