### ISSUE TITLE
Issue to track AzurePipelines trigger comments to be fixed.

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#35121]
Azure Pipelines seems to have rolled out a fix that we should be getting by Friday or Monday. So I've opened this issue to close it once this happens and people gets updated on that matter.

Note they are only broken for fork PRs.

cc: @stephentoub @danmosemsft @jkotas @ViktorHofer @MarcoRossignoli @filipnavara

**Comment by safern** [comment]
And they're fixed 😄 https://github.com/dotnet/corefx/pull/34931

We can now start removing Jenkins. 

Just for the record, these are the available commands.

`/azp run corefx-ci`
`/azp run corefx-outerloop-linux`
`/azp run corefx-outerloop-osx`
`/azp run corefx-outerloop-windows`

Also, to run all the above, you can just do:
`/azp run`

There is also, `/azp help`, which will comment a help text. However, right now it is not that useful, but I requested a feature to azure devops team where they display available pipelines on the help message.

cc: @dotnet/ncl @chcosta

**Comment by filipnavara** [comment]
Thanks for keeping us updated!

**Comment by danmosemsft** [comment]
Yay! if I want to rerun an individual leg, I can no longer do that? Or I go to their page to do it?

**Comment by safern** [comment]
In the latest PRs every individual leg is displayed as an individual build. i.e: `corefx-ci (Windows x64_Debug)` -- so I guess you could do: `/azp run corefx-ci (Windows x64_Debug)`

Also, you can rerun them from the checks UI as well, no need to go to their page:
![image](https://user-images.githubusercontent.com/22899328/52655318-bd7d4e00-2ea8-11e9-8f02-4355287b8e55.png)

**Comment by MarcoRossignoli** [comment]
Wow great! thank's for info!

**Comment by filipnavara** [comment]
> so I guess you could do: `/azp run corefx-ci (Windows x64_Debug)`

Nope, doesn't work (#35264).

> Also, you can rerun them from the checks UI as well

Unfortunately not available to mere mortals (ie. contributors/collaborators).

**Comment by safern** [comment]
> Nope, doesn't work (#35264).

😢 😭 -- I just let azure devops team know. Will update once I get an answer.

> Unfortunately not available to mere mortals (ie. contributors/collaborators).

They said this is a GitHub limitation and that they where going to push on them and work with them to try an enable it for you guys 😄
