### ISSUE TITLE
CoreFX standalone build, is it possible?

### ISSUE THREAD

**Issue by iarischenko** [dotnet/corefx#35130]
Is it possible to build (rebuild) CoreFX with out access to the to the NuGet servers?

I.e. download nuget packages to a local folder and pass the folder as parameter to build system?
Or build the CoreFX once (with network) and then re-build without network?

@alpencolt @kbaladurin @MichalStrehovsky

**Comment by alpencolt** [comment]
cc @jkotas

**Comment by am11** [comment]
https://github.com/dotnet/source-build provides ability for package distribution systems to do a complete offline build of all .NET Core, ASP.NET and few repositories from Microsoft GH org (currently [25 repos](https://github.com/dotnet/source-build/blob/f864f9e/.gitmodules)). There are also build jobs to that effect in Azure Pipelines CI: https://dev.azure.com/dnceng/public/_build/results?buildId=88586.

**Comment by jkotas** [comment]
The build script check for `NUGET_PACKAGES` environment variable that you should be able to use to override the location of the nuget cache.

Also, the build script has `-InitTools` and `-Restore` options that you should be able to use to download everything needed upfront, without building anything. (That's the theory at least.)

cc @safern

**Comment by iarischenko** [comment]
I've set the `NUGET_PACKAGES` variable to corefx folder, then executed `build -r` command.
Then I've tar-ed the repo, copied the archive to chroot, un-tar-ed the archive, set `NUGET_PACKAGES` variable. The first `build.sh -r` restore failed with error: 
``` bash
/usr/src/packages/BUILD/corefx-3.0.0/build.proj(30,26): error MSB4057: The target "GenerateConfigurationProps" does not exist in the project.
```
The full log in attached:
[log.txt](https://github.com/dotnet/corefx/files/2840133/log.txt)

And if I run the `build.sh -r` again the error does not happen.

**Comment by iarischenko** [comment]
I've figured out: path to corefx source should be the same on both systems. It resolves the `target "GenerateConfigurationProps" does not exist` issue.

Now, I've faced with next issue: `SourceRevisionId is not set`
``` bash
[  299s] /usr/src/packages/BUILD/corefx-3.0.0/packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19072.5/tools/Version.targets(69,5): error : SourceRevisionId is not set, which means the SourceLink targets are not included in the build. Those are needed to produce a correct sha for our build outputs. [/usr/src/packages/BUILD/corefx-3.0.0/src/Native/build-native.proj]
```

**Comment by iarischenko** [comment]
The `SourceRevisionId` could be set via command line as follows: 
``` bash
./build.sh /p:SourceRevisionId=3.0.0
```
In my case the corefx archive does not contain git repo. For this reason the `SourceRevisionId` is not set.
I've build the corefx with out the internet connection & other build machine.
