### ISSUE TITLE
The content of LICENSE.txt is not recognized by github as MIT License

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#35159]
![image](https://user-images.githubusercontent.com/41759/52449667-091caa00-2aed-11e9-962c-8859f89fc3f2.png)

vs 

![image](https://user-images.githubusercontent.com/41759/52449694-18035c80-2aed-11e9-9d34-cd7cdf90520a.png)

(from Arcade)

**Comment by danmosemsft** [comment]
@richlander

**Comment by danmosemsft** [comment]
File is identical to arcade one (except a newline)
github detects licenses with `licensee` which looks at more than just the file content.
Need to experiment with it .. https://github.com/benbalter/licensee/blob/master/docs/command-line-usage.md

**Comment by danmosemsft** [comment]
Ones that are detected OK:
```
C:\>licensee detect git\cli
License:        NOASSERTION
Matched files:  LICENSE, README.md
LICENSE:
  Content hash:  d64f3bb4282a97b37454b5bb96a8a264a3363dc3
  Attribution:   Copyright (c) 2015 .NET Foundation
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       MIT
README.md:
  Content hash:  51cf2668e504b9a963adf290a8fc4684943108b7
  License:       NOASSERTION
```
```
C:\>licensee detect git\arcade
License:        MIT
Matched files:  LICENSE.TXT, README.md
LICENSE.TXT:
  Content hash:  d64f3bb4282a97b37454b5bb96a8a264a3363dc3
  Attribution:   Copyright (c) .NET Foundation and Contributors
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       MIT
README.md:
  Content hash:  8c1668d4df0f8363886c27cfd51ad2f1087cf876
  Confidence:    90.00%
  Matcher:       Licensee::Matchers::Reference
  License:       MIT

```

**Comment by danmosemsft** [comment]
That are not:
```
C:\>licensee detect git\corefx
License:        NOASSERTION
Matched files:  LICENSE.TXT, PATENTS.TXT, README.md
LICENSE.TXT:
  Content hash:  d64f3bb4282a97b37454b5bb96a8a264a3363dc3
  Attribution:   Copyright (c) .NET Foundation and Contributors
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       MIT
PATENTS.TXT:
  Content hash:  fab2cb8362aea178cb0953521a67d438862fd7cc
  License:       NOASSERTION
  Closest non-matching licenses:
    MS-PL similarity:  32.28%
README.md:
  Content hash:  5aa341030719f7ddcfece3011cefff9aee8f0e51
  Confidence:    90.00%
  Matcher:       Licensee::Matchers::Reference
  License:       MIT
```
```
C:\>licensee detect git\coreclr
License:        NOASSERTION
Matched files:  LICENSE.TXT, PATENTS.TXT, README.md
LICENSE.TXT:
  Content hash:  d64f3bb4282a97b37454b5bb96a8a264a3363dc3
  Attribution:   Copyright (c) .NET Foundation and Contributors
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       MIT
PATENTS.TXT:
  Content hash:  fab2cb8362aea178cb0953521a67d438862fd7cc
  License:       NOASSERTION
  Closest non-matching licenses:
    MS-PL similarity:  32.28%
README.md:
  Content hash:  8e4443ddce88ce24c02f7b5665d1a33bbc90837b
  Confidence:    90.00%
  Matcher:       Licensee::Matchers::Reference
  License:       MIT

```

**Comment by danmosemsft** [comment]
My guess is that it's the PATENTS.TXT, which it's mis-recognizing (with low confidence) as containing the MS-PL, and Github puts all this together and decides it's not clearly MIT.

`licensee` finds `PATENTS.TXT` with this regex
https://github.com/benbalter/licensee/blob/238ee63394cab172641f6df11fe6eff0f42537da/lib/licensee/project_files/license_file.rb#L41

One "fix" would be to rename PATENTS.TXT.

I guess this is not worth doing anything about unless there's evidence it's causing more confusion. 

cc @leecow

**Comment by ViktorHofer** [comment]
IMO I think it would be nice to fix this. Customers/Devs/me always look at the license section on a GH repo. Not clearly pointing out that we are MIT licensed results in confusion or in the worst case, in partners not supporting us.

**Comment by danmosemsft** [comment]
@ViktorHofer seems that Eric pinged github support and they are aware of the issue.

**Comment by ericstj** [comment]
From GitHub:

> I believe this happens when there's a PATENTS file in the repository also. This file supersedes the license file and is used for repository license classification. 
> This is something our team are currently discussing however. I'll add your feedback into this existing discussion.
