### ISSUE TITLE
Self contained publish on linux includes .a files

### ISSUE THREAD

**Issue by dagood** [dotnet/corefx#35153]
@peterhuene commented on [Wed Feb 06 2019](https://github.com/dotnet/core-setup/issues/5105)

@vitek-karas commented on [Wed Feb 06 2019](https://github.com/dotnet/sdk/issues/2912)

Using relatively new 3.0 SDK

```
mkdir ca1
cd ca1
dotnet new console
dotnet publish --self-contained -r linux-x64
```

In the publish directory there are 6 `.a` files which don't seem to have any purpose. Basically for every native library (`.so`) coming from CoreFx, there's a corresponding `.a` as well:
```
-rwxrw-rw- 1 vitek vitek 2836614 Feb  5 04:05 System.IO.Compression.Native.a
-rwxrw-rw- 1 vitek vitek   27254 Feb  5 04:05 System.IO.Ports.Native.a
-rwxrw-rw- 1 vitek vitek  396432 Feb  5 04:05 System.Native.a
-rwxrw-rw- 1 vitek vitek   79868 Feb  5 04:05 System.Net.Http.Native.a
-rwxrw-rw- 1 vitek vitek   29400 Feb  5 04:05 System.Net.Security.Native.a
-rwxrw-rw- 1 vitek vitek  906184 Feb  5 04:05 System.Security.Cryptography.Native.OpenSsl.a
```
I don't think these files are needed for anything. 
Per customer report this also reproes on MacOS, but I didn't verify.

---

@livarcocc commented on [Wed Feb 06 2019](https://github.com/dotnet/sdk/issues/2912#issuecomment-461098282)

@peterhuene can you take a look?

---

@peterhuene commented on [Wed Feb 06 2019](https://github.com/dotnet/sdk/issues/2912#issuecomment-461133133)

We should only be copying what's in the native assets directory, so if present it gets copied (hence why you get the .txt file too).  Did something change in what gets packaged into `Microsoft.NETCore.App`?

I'll investigate.

---

@peterhuene commented on [Wed Feb 06 2019](https://github.com/dotnet/sdk/issues/2912#issuecomment-461264426)

I can reproduce this on the current shipping 2.2.103 SDK.

It appears the `runtime.$RID.microsoft.netcore.app` packages (where $RID is not a Windows-based RID) does indeed contain the static library files in their native assets.  As a result, they get treated like native assets like any other files and copied for the publish.

I think this is a core-setup issue.  These files should not be packaged for `Microsoft.NETCore.App` packages on non-Windows platforms.

---

@dagood commented on [Thu Feb 07 2019](https://github.com/dotnet/core-setup/issues/5105#issuecomment-461576681)

We can certainly filter these out in Core-Setup, but I think a better option is to have CoreFX stop putting the `.a` files in its transport packages. This keeps the change close to where the source lives.

Moving to CoreFX.

**Comment by omajid** [comment]
It looks like corefx includes these `.a` files intentionally. There are things (like corert?) that depend on that: https://github.com/dotnet/corefx/pull/25628

**Comment by peterhuene** [comment]
Should we filter them out when packaging `NETCore.App` then?

**Comment by dagood** [comment]
Thanks omajid. Next question is: do things (like?) CoreRT depend on `Microsoft.Private.CoreFx.NETCoreApp` (the transport package) directly, or `Microsoft.NETCore.App`?

If they depend on the transport package, then we can filter in Core-Setup. Otherwise, we'll break them either way.

**Comment by jkotas** [comment]
> CoreRT depend on `Microsoft.Private.CoreFx.NETCoreApp`

Yes.

> Should we filter them out when packaging `NETCore.App` then?

Correct.

**Comment by dagood** [comment]
Thanks all, moving this back to https://github.com/dotnet/core-setup/issues/5105.
