### ISSUE TITLE
HTTP2: HPackEncoder lower casing logic is incorrect

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#35164]
See this code:

https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HPack/HPackEncoder.cs#L91

The `| toLowerMask` logic is incorrect for some allowed non-alpha characters like _.

Note lower-casing logic is only used for header names. Related: #31307

**Comment by geoffkizer** [comment]
Given that we want to optimize using the static table as per #31307, I don't think this code is all that perf critical since it will only be used for nonstandard header names. So just calling char.ToLowerInvariant or whatever is fine to do.

Also note that header names are validated when created, so we don't need to check for valid characters here. We might want to assert this, though, just to make sure.

**Comment by geoffkizer** [comment]
Also, I believe we have some tests for header names and values, but they are only running for HTTP/1.1 currently. We need to enable these for HTTP2 as well.

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/corefx/pull/35324
