### ISSUE TITLE
HttpClient issue when calling older ASP.Net webAPIs from net core

### ISSUE THREAD

**Issue by chrizy** [dotnet/corefx#35181]
I’m having an issue when calling an ASP.Net 5.2.3 WebAPI (framework 4.7.2) when using net core as the client. The issue does not happen If compile the test console app using framework 4.7.2. The issue is that the message body does not get serialized in the API controller and will always by null.

network traces below for the same code running against each runtime. It looks like some extra bytes is being added in net core.
Thanks

**.net core 2.2 (fails)**

```
POST http://croy201703/CrmServer/api/v1/login HTTP/1.1
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Host: croy201703

48
{"username":"Admin","password":"Admin","installID":"test","force":false}
0
```

**.net framework 4.7.2 (works OK)**

```
POST http://croy201703/CrmServer/api/v1/login HTTP/1.1
Content-Type: application/json; charset=utf-8
Host: croy201703
Content-Length: 72

{"username":"Admin","password":"Admin","installID":"test","force":false}

```

Application calling code used for both tests
```
            var baseURL = "http://croy201703/CrmServer/";
            var username = "Admin";
            var password = "Admin";

            // Login
            var httpClient = new HttpClient()
            {
                BaseAddress = new Uri(baseURL)
            };
            var loginRequest = new { Username = username, Password = password, InstallID = "test", Force = false };
            var loginResponse = await httpClient.PostAsJsonAsync("api/v1/login", loginRequest);

```
also tried with not passing as an anonymous type

**Comment by geoffkizer** [comment]
.NET Core is sending the body as chunked, whereas framework is sending using Content-Length. Both are legal. I don't see a problem here.

**Comment by davidsh** [comment]
>The issue is that the message body does not get serialized in the API controller and will always by null.

Perhaps the bug is in your ASP.NET layer.  Maybe it assumes 'Content-Length' encoding only for request body?  And if it gets 'Transfer-Encoding: chunked' then it might fail with serializing to `null`?

**Comment by davidsh** [comment]
Also, this code from your client example:

``c#
var loginResponse = await httpClient.PostAsJsonAsync("api/v1/login", loginRequest);
```

where is "loginRequest" defined?  I assume it is an `HttpContent` derived class?  

As @geoffkizer mentioned:

there is a different in how .NET Framework and .NET Core will transmit a request body in cases where it is ambiguous.  If neither 'Content-Length' nor 'Transfer-Encoding: chunked' appear for the request body, each of the frameworks makes a choice.  However, you can ensure that a specific choice is made it you specifically set either 'Content-Length' or 'Transfer-Encoding: chunked' semantics yourself.

**Comment by chrizy** [comment]
Thanks for the feedback, I suspect the chunked is the issue. The problem as I see it is by default no net core application can talk to older asp net 5.2.3 as asp.net doesn't support or understand the data sent, and does not give an clear indication as to the problem. It seems like an odd default position to be in. 
Also changing each http request (talking about over 70 apis here) in my net core application to disable chunked is not easy, Unless there is some global setting which can control this? or is there a way to get asp.net to support it?

**Comment by davidsh** [comment]
The root cause here still hasn't been determined but based on your scenario the problem is in ASP.NET and not the client-side HTTP stack (HttpClient).

>Unless there is some global setting which can control this? or is there a way to get asp.net to support it?

I suggest you follow up with the ASP.NET core team on this.  @Tratcher Can you comment on this?

**Comment by Tratcher** [comment]
@dougbu any thoughts on why MVC 5.2.3 would care about the difference between chunked and content-length? It shouldn't.

@davidsh this can be moved to https://github.com/aspnet/AspNetWebStack.

**Comment by davidsh** [comment]
>@davidsh this can be moved to https://github.com/aspnet/AspNetWebStack.

@Tratcher I know there is a tool that does that.  But I don't have it installed.  Can you move this please and also let me know where the tool is?

**Comment by Tratcher** [comment]
This issue was moved to aspnet/AspNetWebStack#232

**Comment by Tratcher** [comment]
We use Eilon's https://hubbup.io/Mover tool.
