### ISSUE TITLE
Dictionary int constructor ~10 times faster on Windows than on Linux

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#3518]
Perf test being run:

```
[Benchmark]
[InlineData(0)]
[InlineData(1024)]
[InlineData(4096)]
[InlineData(16384)]
public void ctor_int(int size)
{
    foreach (var iteration in Benchmark.Iterations)
        using (iteration.StartMeasurement())
            for (int i = 0; i <= 5000; i++)
            {
                new Dictionary<int, string>(size); new Dictionary<int, string>(size); new Dictionary<int, string>(size);
                new Dictionary<int, string>(size); new Dictionary<int, string>(size); new Dictionary<int, string>(size);
                new Dictionary<int, string>(size); new Dictionary<int, string>(size); new Dictionary<int, string>(size);
            }
}
```

Linux results:
```
<assemblies>
  <assembly name="System.Collections.Tests.dll" environment="64-bit .NET (unknown version) [collection-per-class, parallel (1 threads)]" test-framework="xUnit.net 2.1.0.3168" run-date="2015-09-29" run-time="08:55:06" total="4" passed="4" failed="0" skipped="0" time="155.515" errors="0">
    <errors />
    <collection total="4" passed="4" failed="0" skipped="0" name="Test collection for System.Collections.Tests.Perf_Dictionary" time="152.324">
      <test name="System.Collections.Tests.Perf_Dictionary.ctor_int(size: 0)" type="System.Collections.Tests.Perf_Dictionary" method="ctor_int" time="1.3813971" result="Pass" />
      <test name="System.Collections.Tests.Perf_Dictionary.ctor_int(size: 1024)" type="System.Collections.Tests.Perf_Dictionary" method="ctor_int" time="3.5940251" result="Pass" />
      <test name="System.Collections.Tests.Perf_Dictionary.ctor_int(size: 4096)" type="System.Collections.Tests.Perf_Dictionary" method="ctor_int" time="34.9892132" result="Pass" />
      <test name="System.Collections.Tests.Perf_Dictionary.ctor_int(size: 16384)" type="System.Collections.Tests.Perf_Dictionary" method="ctor_int" time="112.359834" result="Pass" />
    </collection>
  </assembly>
</assemblies>
```

Windows results:
```
<assemblies>
  <assembly name="System.Collections.Tests.dll" environment="64-bit .NET (unknown version) [collection-per-class, parallel (8 threads)]" test-framework="xUnit.net 2.1.0.3168" run-date="2015-09-28" run-time="17:54:01" total="4" passed="4" failed="0" skipped="0" time="22.975" errors="0">
    <errors />
    <collection total="4" passed="4" failed="0" skipped="0" name="Test collection for System.Collections.Tests.Perf_Dictionary" time="22.793">
      <test name="System.Collections.Tests.Perf_Dictionary.ctor_int(size: 0)" type="System.Collections.Tests.Perf_Dictionary" method="ctor_int" time="1.0212133" result="Pass">
      <test name="System.Collections.Tests.Perf_Dictionary.ctor_int(size: 1024)" type="System.Collections.Tests.Perf_Dictionary" method="ctor_int" time="1.3380868" result="Pass">
      <test name="System.Collections.Tests.Perf_Dictionary.ctor_int(size: 4096)" type="System.Collections.Tests.Perf_Dictionary" method="ctor_int" time="4.5502888" result="Pass">
      <test name="System.Collections.Tests.Perf_Dictionary.ctor_int(size: 16384)" type="System.Collections.Tests.Perf_Dictionary" method="ctor_int" time="15.8834876" result="Pass">
    </collection>
  </assembly>
</assemblies>
```

Note that the because of the way the test is written, destructing of the dictionaries can be included in the measured portion. It would be worthwhile to store local copies of the dictionaries so that destruction doesn't happen within the iteration.StartMeasurement ```using``` so the exact problem can be narrowed down.

**Comment by stephentoub** [comment]
@ianhays, is it possible you're running the Linux tests with a debug coreclr / mscorlib?  I just tried this locally and I'm not seeing anywhere near such a difference.

**Comment by ianhays** [comment]
I agree that the results don't make a lot of sense and are indicative of a problem somewhere else along the line - in theory non xplat code like Collections should be the one thing that is constant (or near so) between platforms. 

>is it possible you're running the Linux tests with a debug coreclr / mscorlib? 

I'm thinking that the mscorlib that I've been using was probably compiled in a Debug configuration. I'm going to modify my workflow a bit and rerun the tests. It's likely that this issue can be closed. I'll reexamine the results for #3505 to ensure that it is still an issue as well.

As an aside, I will be very soon (Today) adding new perf tests - any recommendations on libraries that are high perf priority or contain distinct differences between the Linux and Windows implementations for me to start on?

**Comment by stephentoub** [comment]
> any recommendations on libraries that are high perf priority or contain distinct differences between the Linux and Windows implementations for me to start on?

I would focus on areas we know have differences in their implementations in corefx between Windows and Unix, and in particular operations that are often done on hot paths.  Static usage analysis of how many times a particular function is used can tell you the frequency of how often it occurs in the code, but it doesn't tell you how often it's invoked, e.g. if a function is used in a tight loop it's only going to show up as being used once but it's going to be invoked a lot.

Some suggestions:
- Reading/writing from/to various sources and targets (FileStream, PipeStream, NetworkStream, etc.)
- Constructing/disposing memory mapped files
- Accessing culture information / string formatting with data influenced by current culture
- HttpClient request/responses (this is going to be a bit challenging due to network latencies)
- Cryptographic operations (e.g. random number generation, encrypting/decrypting data with CryptoStream, etc.)
- Entering/existing Monitors
- Setting/waiting on Auto/ManualResetEvents
