### ISSUE TITLE
IsolatedStorageFile GetUserStoreForAssembly inconsistency

### ISSUE THREAD

**Issue by jlchavez** [dotnet/corefx#35180]
This is a shared issue with .net core/standard and .net framework.

I have a library, for example let's name it WebPx.VirtualStorage, that calls the IsolatedStorageFile methods to get an IsoltatedStorage instance by User and Assembly, so this is the "Calling Assembly", but when I run a Web App or a Test Console App, those applications magically become the "Calling Assembly" and then the files are not really shared on an Isolated Storage by Assembly, it works like if I had requested IsolatedStorageScope.Application instead of IsolatedStorageScope.Assembly.

In .net framework, I could pass Evidence with a StrongName that forced for my assembly, so that I could ensure that the IsolatedStorage mechanism would always use that assembly name as the base for generating the physical path.

Even if Code Access Security is not supported, it should be allowed to pass a StrongName as Evidence, resolving issue #10935, and that the currently available methods should not throw an exception if used #18706, so that it can be forced "as a workaround" or adapt to special requirements, but that would require us to wait for the next release of .net core, so it would be great to fix both things,, and resolve the Assembly Scope, for what we develop forward with .net core/framework.

```
private static IsolatedStorageFile GetStore()
{
  IsolatedStorageFile store = IsolatedStorageFile.GetUserStoreForAssembly();
  return store;
}
```

In .net framework I could do

```
  var scope = IsolatedStorageScope.Assembly | IsolatedStorageScope.User;
  var strongName = new StrongName(new StrongNamePublicKeyBlob(DecodeHexString("00..8B")), "WebPx.VirtualStorage", new Version(6, 0, 0, 6));
  var evidence = new Evidence(new EvidenceBase[] { strongName }, null);
  var store = IsolatedStorageFile.GetStore(scope, null, null, evidence, null);
```

I might build a sample code with unit testing, if you need this sample, but i'm short of time with this, I have to build an alternate component for IsolatedStorage since this won't work for my current project, and it can't wait for a "release"... but while debugging I found that the folders changed:

For LocalStorageTest:
`C:\ProgramData\IsolatedStorage\mczgwee5.xly\jd41pqrd.wl3\StrongName.juocmblnfld5nltit5r1ajx4gg3qntvy\AssemFiles\`
With AssemblyIdentity for StrongName 'WebPx.LocalStorageTest'

For ConsoleAppTest:
`C:\ProgramData\IsolatedStorage\mczgwee5.xly\jd41pqrd.wl3\StrongName.osl54eaiwhirxv5vd1i5surmygahi1fs\AssemFiles\`
With AssemblyIdentity for StrongName 'WebPx.Web...'

For WebAppTest (unsigned assembly of course):
`C:\ProgramData\IsolatedStorage\mczgwee5.xly\jd41pqrd.wl3\Url.2gdf4ta0vupauvpaclwaqxofqoayi1e2\AssemFiles\`
With AssemblyIdentity for Url: 
`file:///C:/Source/WebPx8/Master/Src/Web/WebPx/WebPx.Web/Samples/ErrorHandlingSample/bin/Debug/netcoreapp2.1/ErrorHandlingSample.dll`

**Comment by danmosemsft** [comment]
I wonder how common this is encountered.

**Comment by JeremyKuhne** [comment]
If anyone wants to take up #10935 that would be great, we just don't have the resources to give to it ourselves right now. When I first ported `IsolatedStorage` I had to do the best matching I could given that you can't actually get the `StrongName` in .NET Core (it isn't a thing). We also don't have a working implementation of `Evidence` currently- it is just a stub.

**Comment by carlossanlop** [comment]
Triage: Closing as this isn't a common scenario.
