### ISSUE TITLE
HttpListener.Start() throws ArgumentNullException in some cases in Linux platform (dotnet core 2.1/2.2, etc)

### ISSUE THREAD

**Issue by qixu001** [dotnet/corefx#35191]
The problem is very similar to this:https://github.com/Microsoft/vscode-docs-authoring/issues/101
here's the callstack:
```
System.ArgumentNullException: Value cannot be null.
   at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
   at System.Net.HttpEndPointListener.ProcessAccept(SocketAsyncEventArgs args)
   at System.Net.HttpEndPointListener.Accept(SocketAsyncEventArgs e)
   at System.Net.HttpEndPointListener..ctor(HttpListener listener, IPAddress addr, Int32 port, Boolean secure)
   at System.Net.HttpEndPointManager.GetEPListener(String host, Int32 port, HttpListener listener, Boolean secure)
   at System.Net.HttpEndPointManager.AddPrefixInternal(String p, HttpListener listener)
   at System.Net.HttpEndPointManager.AddListener(HttpListener listener)
   at System.Net.HttpListener.Start()
```

Taking a look at the source code, it looks that the issue happens when server is starting, client sends requests to the server. And the code that fails is likely because in HttpEndPointListener, the unregisteredConnections is null when the call of ProcessAccept comes from the cor of HttpEndPointerListener when the _unregisteredConnections is not initialized.
```c#
  lock (epl._unregisteredConnections)
            {
                epl._unregisteredConnections[conn] = conn;
            }
```

**Comment by wfurt** [comment]
do you have repro code @qixu001

**Comment by qixu001** [comment]
listener = new HttpListener();
            try { listener.Prefixes.Add(httpListenerPrefix); }
            catch (Exception ex) { throw new ArgumentException("The provided prefix is not supported. Prefixes have the format: 'http(s)://+:(port)/'", ex); }

            listener.TimeoutManager.IdleConnection = TimeSpan.FromSeconds(3600);
            //--------------------- start listener
            try
            {
                listener.Start();
            }
            catch (Exception e)
            {......
            }
the httpListenerPrefix is http://+:9000/
the key to repro it is that client side keeps sending requests, while the server is starting.

**Comment by qixu001** [comment]
> do you have repro code @qixu001

Please see the code above. BTW, I run it in docker and I have clients keep sending requests while the server starts.

**Comment by qixu001** [comment]
What's more, once it runs into the condition, there's no quick recovery way. 
I have code to sleep and retry and then it will have this call stack:
2019-02-09 05:42:11.272 [ERROR] Start failed, error:System.Net.HttpListenerException (98): Address already in use
   at System.Net.HttpEndPointManager.GetEPListener(String host, Int32 port, HttpListener listener, Boolean secure)
   at System.Net.HttpEndPointManager.AddPrefixInternal(String p, HttpListener listener)
   at System.Net.HttpEndPointManager.AddListener(HttpListener listener)
   at System.Net.HttpListener.Start()

It keeps that way until waiting for 2 seconds. Is there any way to reduce the recovery time?

**Comment by wfurt** [comment]
We could/should use Socket.ReuseAddress. That avoids need to wait for TIME_WAIT delay. I'll try to reproduce and I'll share findings.

**Comment by qixu001** [comment]
> We could/should use Socket.ReuseAddress. That avoids need to wait for TIME_WAIT delay. I'll try to reproduce and I'll share findings.

Thanks for the suggestion. Regarding the Socket.ReuseAddress, how can I use it for HttpListener?

**Comment by qixu001** [comment]
BTW, here's what I think it happened, just FYI.
So in HttpListener's Accept(SocketAsyncEventArgs e)---which is called by HttpEndPointListener(HttpListener listener, IPAddress addr, int port, bool secure), if the AcceptAsync() returns false, then ProcessAccept will be called and then it's doomed. Simply because the _unregisteredConnections is not initialized when executing lock(_unregisteredConnections) inside the ProcessAccept. 
private void Accept(SocketAsyncEventArgs e)
        {
            e.AcceptSocket = null;
            bool asyn;
            try
            {
                asyn = _socket.AcceptAsync(e);
            }
            catch (ObjectDisposedException)
            {
                // Once the listener starts running, it kicks off an async accept,
                // and each subsequent accept initiates the next async accept.  At
                // point if the listener is torn down, the socket will be disposed
                // and the AcceptAsync on the socket can fail with an ODE.  Far from
                // ideal, but for now just eat such exceptions.
                return;
            }
            if (!asyn)
            {
                ProcessAccept(e);
            }
        }

private static void ProcessAccept(SocketAsyncEventArgs args)
        {
            HttpEndPointListener epl = (HttpEndPointListener)args.UserToken;

            Socket accepted = args.SocketError == SocketError.Success ? args.AcceptSocket : null;
            epl.Accept(args);

            if (accepted == null)
                return;

            if (epl._secure && epl._cert == null)
            {
                accepted.Close();
                return;
            }

            HttpConnection conn = new HttpConnection(accepted, epl, epl._secure, epl._cert);
            lock (epl._unregisteredConnections)
            {
                epl._unregisteredConnections[conn] = conn;
            }
            conn.BeginReadRequest();
        }

**Comment by davidsh** [comment]
HttpListener is considered a legacy component.  On Windows, it is based on top of http.sys.  On Linux, it is a rewrite/port of the Mono version.  There are several existing issues in CoreFx regarding perf/stress for this component on Linux platform.

Unless porting from existing code, we recommend new development use ASP.NET middleware components like Kestrel server instead of using HttpListener.

**Comment by qixu001** [comment]
> HttpListener is considered a legacy component. On Windows, it is based on top of http.sys. On Linux, it is a rewrite/port of the Mono version. There are several existing issues in CoreFx regarding perf/stress for this component on Linux platform.
> 
> Unless porting from existing code, we recommend new development use ASP.NET middleware components like Kestrel server instead of using HttpListener.

In my scenario, we don't run asp.net, but just need a lightweight http server. Is Kestrel server an overkill for that?

**Comment by davidsh** [comment]
>In my scenario, we don't run asp.net, but just need a lightweight http server. Is Kestrel server an overkill for that?

It depends on your scenario.  But you might want to check out ASP.NET and Kestrel.  It is lightweight and has high performance.

**Comment by qixu001** [comment]
Kestral's cold start performance is a joke. It takes 1 sec or more to start a functional server, which is almost 10 times slower than nodejs and 5 times slower than HttpListener. 
This strongly limits the dotnet core's adoption in server less scenario like AWS lambda

**Comment by danmosemsft** [comment]
@davidfowl

**Comment by karelz** [comment]
I believe that Kestrel startup is on ASP.NET team's radar. You can follow up on their repo.
Serverless scenarios (Azure Functions, AWS Lambda) rarely do pure cold startup - they have infrastructure warmed up to process incoming requests AFAIK.

Either way, I think this issue can be now closed.

See HttpListener deprecation plan in https://github.com/dotnet/platform-compat/issues/88 and https://github.com/dotnet/designs/issues/9
