### ISSUE TITLE
BufferExtensions.Write hangs in a spinning wait when IBufferWriter<T>.GetSpan returns empty span

### ISSUE THREAD

**Issue by AArnott** [dotnet/corefx#35231]
The `BufferExtensions.Write<T>(this IBufferWriter<T>, ReadOnlySpan<T>)` extension method is vulnerable to enter a spinning loop that never exits when the `IBufferWriter<T>.GetSpan` method returns a span of empty length.

While returning a 0 length span is a violation of the interface contract, I think corefx shouldn't enter a spinning loop with no exit in such a case. Instead, a 0 length span should be detected and an exception thrown.

https://github.com/dotnet/corefx/blob/5ae8385e063788f3c3b668bf2cbbb012a302bae2/src/System.Memory/src/System/Buffers/BuffersExtensions.cs#L127-L144

**Comment by ahsonkhan** [comment]
@adamsitnik, are you still planning on working on this issue?
