### ISSUE TITLE
Add ALPN support to HttpListener

### ISSUE THREAD

**Issue by WouterTinus** [dotnet/corefx#35244]
Support for ALPN was added to System.Net.Security.SslStream in #23177. This is great for applications that can claim a port for themselves using a TcpListener, but for my application I'm looking to use it in combination with the port sharing mechanism provided by a HttpListener.

The use case is to implement ACME TLS-ALPN-01 validation as defined by the IETF in https://tools.ietf.org/html/draft-ietf-acme-tls-alpn-05, but we don't want to take down IIS or become a proxy for it.

Our issue tracking this: https://github.com/PKISharp/win-acme/issues/990

If you would consider adding this to CoreFX - or point me somewhere else if I overlooked something - it would be great!

**Comment by davidsh** [comment]
>If you would consider adding this to CoreFX (or point me somewhere else if I overlooked something) it would be great!

There are two implementations of HttpListener in CoreFx.  The Windows one is based on http.sys (same underlying technology that .NET Framework HttpListener uses).  The Linux one is based on a separate implementation written directly using System.Net.Sockets (ported from Mono implementation).

So, implementing this feature would requires changes to both implementations.

**Comment by karelz** [comment]
We do not plan to evolve HttpListener futher - see https://github.com/dotnet/designs/issues/9 and https://github.com/dotnet/platform-compat/issues/88
For full server support we recommend to use Kestrel, fully modern and high-performance HTTP server for .NET.
