### ISSUE TITLE
api suggestion: Process.Kill shouldn't throw when the process has exited

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#35257]
Currently, `Process.Kill` throws when the process has already exited.

Perhaps the method should noop if the process has already exited.

It avoids a try-catch to check (and ignore) the 'has already terminated' case.
And it avoids unexpected exceptions if the user forgot to add the try-catch.

**Comment by danmosemsft** [comment]
I agree, it seems unlikely that it is useful to fail in this case. Although, Directory.Delete will throw if the path does not exist, perhaps that is useful to flag a typo in the path (?)

@bgribaudo?

**Comment by tmds** [comment]
> Although, Directory.Delete will throw if the path does not exist, perhaps that is useful to flag a typo in the path (?)

`Kill` is an instance method, and an instance can be obtained when the process exists.

**Comment by danmosemsft** [comment]
@tmds right -- I meant, I probably would have designed Directory.Delete to silently return.

**Comment by bgribaudo** [comment]
I like the idea. Seems like it would simplify the common use-case scenario.

If this change were made, https://github.com/dotnet/corefx/pull/34147#discussion_r248286784 / https://github.com/dotnet/corefx/pull/34147#issuecomment-450876620 would be resolved.

Haven't thoroughly checked how `WaitForExit()` works across platforms. If `Kill()` is changed to silently return when the process is already dead, would probably be good to make sure that `WaitForExit()` does the same.

If this change is made, would be nice to similarly modify [`Stop()`](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs#L68) (which was added to support `Kill(bool entireProcessTree)`).

**Comment by tmds** [comment]
Does this need to go through API review?

**Comment by danmosemsft** [comment]
No, as the API is not changed in shape. A change to WaitForExit might break existing code though (?)

**Comment by danmosemsft** [comment]
@wtgodbe @krwq own this area and should decide.
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md

**Comment by tmds** [comment]
> A change to WaitForExit might break existing code though (?)

`WaitForExit` already has this behaviour: when the Process has terminated, it doesn't throw.

**Comment by danmosemsft** [comment]
@bgribaudo I think we should take this change. Any interest in making it?

**Comment by tmds** [comment]
@danmosemsft I can take a look at this. I should also be able to handle Windows (based on CI results).

**Comment by danmosemsft** [comment]
thanks @tmds!

**Comment by krwq** [comment]
I think this is a good idea, can't think of any breaking scenario since Kill doesn't return any value but even if there is such I think it should be acceptable

**Comment by tmds** [comment]
Implemented in https://github.com/dotnet/corefx/pull/36184.

**Comment by bgribaudo** [comment]
Thanks, @tmds! @danmosemsft, sorry that I couldn't jump on this one.
