### ISSUE TITLE
SslStream.AuthenticateAsServer/ClientAsync methods should default CancellationToken to default(CancellationToken)

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#35283]
The new Authenticate overloads on SslStream take a CancellationToken, but don't provide a default value for this. These should default to default(CancellationToken), i.e. CancellationToken.None.

https://github.com/dotnet/corefx/blob/3c30357d51b96339021b4ee52f38445c31248bb2/src/System.Net.Security/src/System/Net/Security/SslStream.cs#L425
https://github.com/dotnet/corefx/blob/3c30357d51b96339021b4ee52f38445c31248bb2/src/System.Net.Security/src/System/Net/Security/SslStream.cs#L390

**Comment by davidsh** [comment]
@karelz @geoffkizer @stephentoub Are we still planning on reviewing and implementing this?

**Comment by stephentoub** [comment]
The entirety of the implementation is adding ` = default` in two or four places, depending on how you count :)  Assuming we can review it in the next few API review meetings and it's approved, we should do it in 3.0.

**Comment by terrajobst** [comment]
We should. Looks good.
