### ISSUE TITLE
System.Net.Http.pdb not found

### ISSUE THREAD

**Issue by MagicAndre1981** [dotnet/corefx#35294]
I try to debug an UWP app and now I fail to get the PDB for `"C:\Program Files\WindowsApps\Microsoft.NET.CoreFramework.Debug.2.2_2.2.27129.1_x86__8wekyb3d8bbwe\System.Net.Http.dll"`:

Here is symsrv output from Visual Studio 2017:

```
E:\A\_work\280\s\corefx\bin\obj\Windows_NT.AnyCPU.Release\System.Net.Http\uap\System.Net.Http.pdb: Cannot open symbol file.

SYMSRV:  BYINDEX: 0x659
         C:\Users\Andre\AppData\Local\Temp\SymbolCache*https://msdl.microsoft.com/download/symbols
         System.Net.Http.pdb
         AA857BED6CCF43B5972A921054D1848F1

SYMSRV:  UNC: C:\Users\Andre\AppData\Local\Temp\SymbolCache\System.Net.Http.pdb\AA857BED6CCF43B5972A921054D1848F1\System.Net.Http.pdb - path not found
```

Where can I get the PDB?

**Comment by davidsh** [comment]
@tommcdon Can you comment on where the public symbols are for UWP packages?

**Comment by MagicAndre1981** [comment]
@davidsh 

I can answer it on my own. I played with the unreleased [6.2.2](https://www.nuget.org/packages/Microsoft.NETCore.UniversalWindowsPlatform/6.2.2)/[6.2.3](https://www.nuget.org/packages/Microsoft.NETCore.UniversalWindowsPlatform/6.2.3) and it looks those PDBs are not available because they are not officially released.

Using [6.1.9](https://www.nuget.org/packages/Microsoft.NETCore.UniversalWindowsPlatform/6.1.9) I get the PDB.

**Comment by davidsh** [comment]
>I can answer it on my own. I played with the unreleased 6.2.2/6.2.3 and it looks those PDBs are not available because they are not officially released.
Using 6.1.9 I get the PDB.

Glad you were able to find the PDB!  I'll close this issue since the question is now answered.
