### ISSUE TITLE
Meta: nameof(x) 

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#3529]
Using `nameof(aParameter)` instead of `"parameter"` is considered a best practice in C#.
Whilst browsing the code for corefx, I noticed that this coding practice is not followed - for example, there is a lot of code that is written as follows:

```csharp
public void aFunction(object aParameter) {
    if (aParameter == null) {
        throw new ArgumentNullException("aParameter");
    }
    //..
}
```

Whilst adding several characters to the line of code, using `nameof(aParameter)` would prevent future inconsistencies (for example, by changing the parameter name without changing the string in ArgumentNullException)

I attach the following StackOverflow thread covering the topic of nameof - here are some good examples of its usefullness.

http://stackoverflow.com/questions/31695900/what-is-the-purpose-of-nameof

I  end by suggesting that the standard of passing string literals, where nameof() could be used, should be changed to promote better code. I would be willing to start the process of using nameof() where applicable if you need community help.

Hugh

P.S: It just occurred to me that nameof() is a new C# 6 feature. Therefore, there may be backwards compatibility issues. If I understand correctly, nameof() is evaluated at compile time, so this may not be an issue.

**Comment by stephentoub** [comment]
Thank you for the suggestion. However, we're still using C# 5 in the corefx repo.  When we upgrade to C# 6, we will start to take advantage of new features like nameof.

**Comment by weshaggard** [comment]
Yes I fully expect nameof(T) will be come part of our coding guidelines once we make the switch to C# 6. I'm hoping that will be able to happen by the end of the year.

**Comment by NickCraver** [comment]
Any update on C# 6 support? I was looking at #5968 and it's another in a series of issues I see benefiting from this support. It even goes so far as to impact the API discussion because of the maintenance costs C# 6 reduces. I assume there's a tooling issue somewhere blocking the move?

**Comment by weshaggard** [comment]
@NickCraver we are very close I've asked @joperezr to set our builds up to use the roslyn toolset package for all our builds (right now it is only used by our x-plat builds) once that happens we sill open the door for using C# 6.0 everywhere in corefx. 

@joperezr did you file an issue for tracking the toolset update? if not please do.

**Comment by NickCraver** [comment]
@weshaggard that's great to hear - thanks for the update!

**Comment by joperezr** [comment]
@weshaggard I hadn't log it before, but I just did. See #6085
