### ISSUE TITLE
Reduce allocation in SocketsHttpHandler for HTTP/2

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#35309]
https://github.com/dotnet/corefx/pull/35179 made a significant dent in the allocations in the new HTTP/2 implementation in SocketsHttpHandler, but there's still a gap between HTTP/1.1 and HTTP/2.  The following shows the allocations for 10K sequential GET requests to a localhost ASP.NET Core server that just outputs a "hello world" response body, first with HTTP/1.1 and second with HTTP/2.

HTTP/1.1:
![image](https://user-images.githubusercontent.com/2642209/52758632-04696180-2fd7-11e9-9839-ee22ac5615b5.png)

HTTP/2:
![image](https://user-images.githubusercontent.com/2642209/52759744-02090680-2fdb-11e9-8ced-6e067163ed63.png)

cc: @geoffkizer

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/pull/35324 removes from the above second image:
- the System.Object line
- the System.Int32 line
- the System.Net.Http.HPack.HPackDecoder.HeaderCallback line
- 3 of the 8 System.Strings per request (e.g. that line drops from ~80K to ~50K)

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/pull/35522 removes the TaskCompletionSource line and one of the tasks.

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/pull/35426 removes one of the tasks.

**Comment by karelz** [comment]
@stephentoub do you think some of this is must-have in 3.0? We think with @geoffkizer that it might be ok to move it to Future.

**Comment by stephentoub** [comment]
> @stephentoub do you think some of this is must-have in 3.0? We think with @geoffkizer that it might be ok to move it to Future.

After all of the various aforementioned changes, it's mostly done.  The main remaining change would come about from pooling Http2Stream, at which point I'd expect the HTTP/1.1 and HTTP/2 allocation profiles for this basic scenario to look the same.  I'm hopeful that we can get the pooling change in for 3.0, but it's not absolutely must-have.

**Comment by geoffkizer** [comment]
Do we have an issue to track pooling of Http2Stream objects? Seems like we should at least consider this for the future.

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/issues/39683
