### ISSUE TITLE
[Suggestion] SortedSet / SortedDictionary: get Next/Prev Key or Node

### ISSUE THREAD

**Issue by vdisasm** [dotnet/corefx#3530]
Both classes are good as Sets, but are limited if I want to find Key and then find previous or next Key (or node) without need to start searching from root.

**Comment by joshfree** [comment]
Hi @vdisasm thanks for the suggestion.  I'm not quite sure what you want us to fix.  Could take a look at the .NET API review process (https://aka.ms/apireview) and expand upon your post?  Also, here is a link to a good example of a good proposal from earlier: https://github.com/dotnet/corefx/issues/271

Thanks,
Josh

**Comment by svick** [comment]
I think #3275 is one way of solving this problem, so this could be considered a duplicate.

**Comment by vdisasm** [comment]
#3275 seems exactly what I want.
Sorry for bad description and duplicate.
