### ISSUE TITLE
[CI outer loop]  System.Xml.Linq.xNodeBuilder.Tests

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#35329]
Windows.10.Amd64.ClientRS4.ES.Open-x64-Debug
```
Assert.Equal() Failure
Expected: 0
Actual:   1
```
   at CoreXml.Test.XLinq.XNodeBuilderFunctionalTests.RunTests() in 
D:\a\1\s\src\System.Private.Xml.Linq\tests\xNodeBuilder\FunctionalTests.cs:line 33

Windows.10.Amd64.ClientRS4.ES.Open-x86-Release
```
Expected: 0
Actual:   1
```
   at CoreXml.Test.XLinq.XNodeBuilderFunctionalTests.RunTests() in
 D:\a\1\s\src\System.Private.Xml.Linq\tests\xNodeBuilder\FunctionalTests.cs:line 33

Windows.10.Amd64.ClientRS4.Open-x86-Release
```
Expected: 0
Actual:   1
```
   at CoreXml.Test.XLinq.XNodeBuilderFunctionalTests.RunTests() in D:\a\1\s\src\System.Private.Xml.Linq\tests\xNodeBuilder\FunctionalTests.cs:line 34

https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F35234~2Fmerge/test~2Ffunctional~2Fcli~2F~2Fouterloop~2F/20190214.1/workItem/System.Xml.Linq.xNodeBuilder.Tests/analysis/xunit/CoreXml.Test.XLinq.XNodeBuilderFunctionalTests~2FRunTests

**Comment by stephentoub** [comment]
Grrr… I thought I fixed that.  These tests are frustrating.  I'll take another look.

**Comment by benaadams** [comment]
I accidentally triggered outloop; thought I'd made use of it and raise the errors 😄

**Comment by stephentoub** [comment]
I can't repro this locally.  Can you?

**Comment by benaadams** [comment]
Was outerloop CI 22hrs ago https://github.com/dotnet/corefx/pull/35234

**Comment by stephentoub** [comment]
Oh, this is netfx...

**Comment by buyaa-n** [comment]
Hi @stephentoub any update? is there any work here for 3.0?

**Comment by stephentoub** [comment]
@buyaa-n, what is it you're concerned with here?

**Comment by buyaa-n** [comment]
Am just setting milestone for all issues which haven't set that

**Comment by stephentoub** [comment]
I see what happened. I fixed the tests to pass on core after @tannergooding's floating point changes, and in doing so netfx is failing because it doesn't have Tanner's change. Will fix.

**Comment by stephentoub** [comment]
> Am just setting milestone for all issues which haven't set that

Got it. I was worried there was something deeper :)

**Comment by buyaa-n** [comment]
> I see what happened. I fixed the tests to pass on core after @tannergooding's floating point changes, and in doing so netfx is failing because it doesn't have Tanner's change. Will fix.

Thank you!

> Got it. I was worried there was something deeper :)

Sorry for confusion :P
