### ISSUE TITLE
SendPacketsAsync.BufferZeroCountThenNormal_ZeroCountIgnored failed in CI on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#3532]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/4396/console
```
System.Net.Sockets.Tests.SendPacketsAsync.BufferZeroCountThenNormal_ZeroCountIgnored [FAIL]
        Timed out
        Expected: True
        Actual:   False
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets.Legacy\tests\FunctionalTests\SendPacketsAsync.cs(231,0): at 
```
cc: @davidsh, @cipop, @pgavlin

**Comment by CIPop** [comment]
These fail in a slow CI system. Timing was updated by 77fb5b23 (timeouts increased x10).

I will submit a PR to re-enable the tests. If they still fail please follow-up on this issue.

**Comment by CIPop** [comment]
This was already fixed and the `ActiveIssue` tag removed.
