### ISSUE TITLE
[CI outer loop] System.Net.NameResolution.PalTests.NameResolutionPalTests/TryGetAddrInfo_HostName

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#35328]
Ubuntu.1604.Arm64.Open-arm64-Release
 System.Net.NameResolution.PalTests.NameResolutionPalTests/TryGetAddrInfo_HostName

```
Assert.Equal() Failure
Expected: Success
Actual:   TryAgain
```
   at System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetAddrInfo_HostName() in 
/__w/1/s/src/System.Net.NameResolution/tests/PalTests/NameResolutionPalTests.cs:line 55

https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F35234~2Fmerge/test~2Ffunctional~2Fcli~2F~2Fouterloop~2F/20190214.1/workItem/System.Net.NameResolution.Pal.Tests/analysis/xunit/System.Net.NameResolution.PalTests.NameResolutionPalTests~2FTryGetAddrInfo_HostName

**Comment by benaadams** [comment]
Same run

Ubuntu.1604.Arm64.Open-arm64-Release
```
Assert.Equal() Failure
Expected: Success
Actual:   TryAgain
```
System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetAddrInfo_HostName_TryGetNameInfo() 
in /__w/1/s/src/System.Net.NameResolution/tests/PalTests/NameResolutionPalTests.cs:line 114

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/32797
cc: @wfurt

**Comment by wfurt** [comment]
cc: @ulisesh
