### ISSUE TITLE
[CI outer loop] System.Runtime.Serialization.Formatters.Tests

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#35330]
OpenSuse.42.Amd64.Open-x64-Debug
```
Expected: 77840
Actual:   73744
```
```
at System.Runtime.Serialization.Formatters.Tests.EqualityExtensions.IsEqual(Bitmap this, Bitmap other, Boolean isSamePlatform) 
in /__w/1/s/src/System.Runtime.Serialization.Formatters/tests/EqualityExtensions.cs:line 1233
```
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F35234~2Fmerge/test~2Ffunctional~2Fcli~2F~2Fouterloop~2F/20190214.1/workItem/System.Runtime.Serialization.Formatters.Tests/analysis/xunit/System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests~2FValidateAgainstBlobs(obj:%20Bitmap%20%7B%20Flags%20=%2077840,%20FrameDimensionsList%20=%20%5B7462dc86-6180-4c7e-8e3f-ee7333a7a483%5D,%20Height%20=%20)

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/34924.  We should get that test disabled.
