### ISSUE TITLE
Is it possible to install System.IO.IsolatedStorage dependency on a .NET 4.6.1 console app?

### ISSUE THREAD

**Issue by hugoqribeiro** [dotnet/corefx#35336]
Hi.

I have a library built on .NET Standard 2.0 that references the System.IO.IsolatedStorage 4.3.0 package.

When I try to add that library package to a .NET 4.6.1 console app, NuGet fails with the following error:

```
Could not install package 'System.IO.IsolatedStorage 4.3.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework.
```

Why is that? What am I missing here?

Thanks.

**Comment by vcsjones** [comment]
/cc @JeremyKuhne who may be able to answer this better than I...

This package seems a bit strange to me. It has a `netstandard1.4` ref assembly, but the actual lib assembly is in `netcore50`. I don't think .NET Framework will pull libs from netcore50.

**Comment by vcsjones** [comment]
For what it's worth, I don't think you should be referencing this package for .NET Framework. Instead you should just be adding a reference to `System.IO.IsolatedStorage` assembly since it is part of the .NET Framework.

**Comment by vcsjones** [comment]
I think then the easiest way to work around this problem is to make your library multi-target for netstandard2.0 and .NET Framework and only include the package if targeting netstandard. Something like this perhaps?

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net461</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' != 'net461' ">
    <PackageReference Include="System.IO.IsolatedStorage" Verison="4.3.0" />
  </ItemGroup>
</Project>
```

**Comment by carlossanlop** [comment]
Triage: it seems the above answer may be the right one. If not, feel free to reactivate.
