### ISSUE TITLE
[Ci outer loop] System.Linq.Parallel.Tests

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#35333]
Seem to be `ulimit: core file size: cannot modify limit: Operation not permitted` across all platforms
e.g. Ubuntu.1604.Arm64.Open-arm64:Debug

```
Executed on DDARM64S-007
+ ./RunTests.sh /ssd/dotnetbuild/work/35561fea-ddff-4f5d-841c-3c61c8c8f1ec/Payload /ssd/dotnetbuild/work/35561fea-ddff-4f5d-841c-3c61c8c8f1ec/Payload /ssd/dotnetbuild/work/35561fea-ddff-4f5d-841c-3c61c8c8f1ec/Payload/tools
./RunTests.sh: line 126: ulimit: core file size: cannot modify limit: Operation not permitted
----- start 10:51:59 =============== To repro directly: =====================================================
pushd .
/ssd/dotnetbuild/work/35561fea-ddff-4f5d-841c-3c61c8c8f1ec/Payload/dotnet xunit.console.dll System.Linq.Parallel.Tests.dll -xml testResults.xml -nologo -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests -notrait category=IgnoreForCI -notrait category=failing
popd
===========================================================================================================
/ssd/dotnetbuild/work/35561fea-ddff-4f5d-841c-3c61c8c8f1ec/Work/0695868c-d830-42dc-b318-3aec856285b3/Exec /ssd/dotnetbuild/work/35561fea-ddff-4f5d-841c-3c61c8c8f1ec/Work/0695868c-d830-42dc-b318-3aec856285b3/Exec
[37m  Discovering: System.Linq.Parallel.Tests (method display = ClassAndMethod, method display options = None)
[m[37m  Discovered:  System.Linq.Parallel.Tests (found 1185 of 1188 test cases)
[m[37m  Starting:    System.Linq.Parallel.Tests (parallel test collections = on, max threads = 46)
[mKilled
```
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F35234~2Fmerge/test~2Ffunctional~2Fcli~2F~2Fouterloop~2F/20190214.1/workItem/System.Linq.Parallel.Tests/wilogs

**Comment by stephentoub** [comment]
This looks like an infrastructure issue.  The PLINQ tests don't use ulimit.
cc: @dotnet/dnceng

**Comment by MattGal** [comment]
The Ulimit calls that are failing are not the source of failures unless you actually need to raise ulimit, and come from RunTests.sh.

This only becomes an infra issue if the limits on the machines actually need to be raised (this will happen in the case where the limit your script asks for is > the hard limit) if so, let me know.

**Comment by stephentoub** [comment]
@mattgal, ok, in that case, what would cause the tests to be "killed"? That's also not coming from the tests.

**Comment by MattGal** [comment]
taking a look.

**Comment by MattGal** [comment]
```
2019-02-14 11:29:00,533: ERROR: job(46): kill: Job running for too long. Killing...
2019-02-14 11:29:00,589: ERROR: executor(551): _execute_command: Executor timed out after 600 seconds and was killed.
2019-02-14 11:29:00,589: INFO: event(43): send: Sending event type WorkItemTimeout
2019-02-14 11:29:00,742: INFO: saferequests(90): request_with_retry: Response complete with status code '201'
2019-02-14 11:29:00,744: INFO: executor(570): _execute_command: Finished _execute_command, exit code: -3
```

**Comment by MattGal** [comment]
They may not be used to running with 46 threads?

**Comment by MattGal** [comment]
Actually given Windows does the exact same thing w/ 2 threads & cores and ulimit has no impact on Windows, I think someone has made a test or tests hang here.

**Comment by MattGal** [comment]
Sent the Windows dump from the x86 run offline, may not be of the right process unfortunately though.

**Comment by stephentoub** [comment]
> They may not be used to running with 46 threads?

@MattGal, can you elaborate?  Do you mean Environment.ProcessorCount on these machines will return 46?

**Comment by MattGal** [comment]
@stephentoub  : Yes, even when we run in docker and forcibly limit the docker containers to 2 cores, most metadata you can access will get a 46 because the machine itself has 46 cores.

**Comment by stephentoub** [comment]
If that's true, that's broken.

**Comment by stephentoub** [comment]
@janvorli, we take docker limits into account on Unix; do we not on Windows?

**Comment by MattGal** [comment]
Sorry, I'm only talking about the ARM failures that were also timing out here.  On Windows, you're not currently running in Docker so that's not the case.

One data point, when I first commented on this issue I downloaded and ran the Windows test.   Two hours later when my machine was choking to death while I tried to present it was still running the test.  Reproducing the problem is easy at least.

**Comment by stephentoub** [comment]
> Sorry, I'm only talking about the ARM failures that were also timing out here. On Windows, you're not currently running in Docker so that's not the case.

ARM failures on Unix?  We should be respecting docker limits in ProcessorCount there.

> One data point, when I first commented on this issue I downloaded and ran the Windows test. Two hours later when my machine was choking to death while I tried to present it was still running the test. Reproducing the problem is easy at least.

On what OS and architecture?

**Comment by MattGal** [comment]
For ARM on Linux, I'm pretty sure I've seen recent issues like https://github.com/dotnet/corefx/issues/34974 that would make it seem like that's only been recently fixed. Just a guess, I haven't personally investigated.

As for my Windows machine, I run plain RTM RS4 AMD64 on a 4-core SurfaceBook w/ 16 GB RAM.

**Comment by stephentoub** [comment]
> I'm pretty sure I've seen recent issues like #34974 that would make it seem like that's only been recently fixed.

That test was saying that the test expected 46 but Environment.ProcessorCount actually returned 2, i.e. ProcessorCount was doing what it was supposed to.

> As for my Windows machine, I run plain RTM RS4 AMD64 on a 4-core SurfaceBook w/ 16 GB RAM.

Ok, I'll try running on netfx. Thanks.

**Comment by stephentoub** [comment]
@MattGal, can you tell me what caused https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F35468~2Fmerge/test~2Ffunctional~2Fcli~2F~2Fouterloop~2F/20190220.1/workItem/System.Linq.Parallel.Tests/wilogs to fail on Windows?  I see this in the logs for "Windows.10.Amd64.ClientRS5.Open-x86:Release":
```
  Discovering: System.Linq.Parallel.Tests (app domain = on [no shadow copy], method display = ClassAndMethod, method display options = None)

  Discovered:  System.Linq.Parallel.Tests (found 1150 of 1188 test cases)

  Starting:    System.Linq.Parallel.Tests (parallel test collections = on, max threads = 2)

  Finished:    System.Linq.Parallel.Tests

=== TEST EXECUTION SUMMARY ===

   System.Linq.Parallel.Tests  Total: 185924, Errors: 0, Failed: 0, Skipped: 0, Time: 112.343s
```
so it would appear all the tests actually completed successfully.

**Comment by MattGal** [comment]
The failure is a timeout, if it's the same as the same test had a year or two ago it may have started some broker process that hung.   Basically Helix Clients don't consider the work done (even if the work completed as you noticed) unless all child processes have exited.

Since we're talking about an entirely new operating system (Client RS5 came online this week) it's also possible that  dialog was launched by one of the processes and not handled by dhandler.  I'll check this out to be sure, but given this same test has leaked processes before I suspect that.
