### ISSUE TITLE
$(CommonPath) in <Compile Include> paths causing bad Visual Studio experience.

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#3534]
A bunch of our .csproj files have lines like &lt;Compile Include "$(CommonPath)\blah\blah"&gt; where $(CommonPath) is defined in dir.prop.

This has a really bad effect on VS experience as its navigation and Intellisense engine struggle to find these files.

Defining $(CommonPath) inside the individual .csproj fixes the Intellisense and still gives us some measure of encapsulation, albeit imperfect.

Is the encapsulation of "Common" really worth this?

**Comment by mellinoe** [comment]
Is the issue that VS is unable to categorize the source file into the correct project / configuration? I have noticed that the files will show up in the Solution explorer but be listed under "Miscellaneous Files". I agree that it is very annoying and a terrible experience.

**Comment by weshaggard** [comment]
@AtsushiKan can you give a specific project and repo steps so I can try to understand what is happening here? For example is it that it doesn't show up in the solution explorer correct or is it that intellisense in for code defined in these files doesn't show up?  If you use relative paths does that fix the problem?

**Comment by AtsushiKan** [comment]
Problem occurs when a project has two .cs files in the $(Common) path that reference types in each other.

For example, open up System.Security.Cryptography.Cng.sln

Open up Common\src\Internal\Cryptograpy\HashProviderCng.cs (this is in the Common path, mapped to Internal\Cryptography in the solution explorer.)

The file contains a type declaration:

     internal sealed class HashProviderCng : HashProvider
     {…}

“HashProvider” is defined in a file Common\src\Internal\Cryptograpy\HashProvider.cs.

So “HashProvider” should be colored green and you should be able to “F12” on it to be taken to HashProvider.cs. But it doesn’t and you can’t.

And yes, replacing the $(Common) with a relative path fixes the VS experience.

**Comment by weshaggard** [comment]
@Pilchie is this a known limitation with intellisense in VS?

**Comment by Pilchie** [comment]
Where is `$(CommonPath)` defined?  This should work as long as it works on command line builds.  We basically run msbuild to get the compiler command line to populate IntelliSense.

**Comment by AtsushiKan** [comment]
The path is:

  <project-specific>.csproj

       <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), dir.props))\dir.props" />

Which jumps up two directory levels to src\dir.props

         <Import Project="..\dir.props" />


Which then brings us to $\dir.props


        <ProjectDir>$(MSBuildThisFileDirectory)</ProjectDir>
        <SourceDir>$(ProjectDir)src/</SourceDir>
        …
        <CommonPath>$(SourceDir)Common\src</CommonPath>

**Comment by nguerrera** [comment]
Do we think that $(CommonPath) is all that important to keep? I'd be fine just putting literal relative paths everywhere. 

(The VS issue should be addressed, though -- @Pilchie should we file a bug on dotnet/roslyn?)

**Comment by AtsushiKan** [comment]
I vote for kicking $(CommonPath) out with extreme prejudice.

**Comment by Pilchie** [comment]
Tagging @davkean.  This is something we could look at in the switch to CPS, but we probably wound't do anything in csproj.dll for it.

**Comment by weshaggard** [comment]
I agree that this doesn't add a ton of value and given that it causes some pain I'm OK with removing it. @AtsushiKan feel free to submit a PR cleaning it up.

**Comment by mellinoe** [comment]
> Do we think that $(CommonPath) is all that important to keep?

I think it's more important to be able to navigate within VS, get proper Intellisense, refactoring, etc. than to have the csproj files be clean, personally. So I'd vote to remove it, unless there's some way we can work around this in a global fashion. I would also be fine with just including $(CommonPath) in each csproj to reduce the code churn, although I'm not sure how others feel about that.

**Comment by Pilchie** [comment]
I'm not actually convinced that this is a fundamental problem with the project system.

Can you do me a favor.  set TRACEDESIGNTIME=true and then delete your .vs directory /.suo file and open the solution again.  You should have a bunch of <Guid>.designtime.log files in %TEMP%.  If you find the one where we build the "Compile" target for this project, we should see the command line going to csc (unless something else fails first).  That's what IntelliSense is based off.

**Comment by AtsushiKan** [comment]
Ok, it seems the problem is having a forward slash instead of a backward slash in the path.

The troublesome guy is:
    <SourceDir>$(ProjectDir)src\</SourceDir>

In dir.props

If I replace the “/” with a “\”, Intellisense starts working. The

Nick, is there a reason (cross-plat, etc.) why we needed a forward slash here?

**Comment by weshaggard** [comment]
Looks like this was fixed with #3884 so closing.

**Comment by AtsushiKan** [comment]
Well it was nice while it lasted - https://github.com/dotnet/corefx/commit/4367ec4c791928c6b2f994e9602dbc75aea7934d undid this.

@joperezr : could you either change the paths in $(CommonPath) (and $(SourceDir)) to use backslashes, or if necessary, define a $(PathSeparator) variable depending on the $(OSEnvironment) property?

**Comment by joperezr** [comment]
yeah I can add a PathSeparator and use it in those two variables.
