### ISSUE TITLE
Do not include System.IO.Ports.Native.* in NetCoreApp

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#35358]
Repro: Download and expand latest .NET Core preview for Linux `.tar.gz` from https://github.com/dotnet/core-setup/

Result: `System.IO.Ports.Native.*` is included in the package

We should not be including `System.IO.Ports.Native.*` in netcoreapp, since the `System.IO.Ports` is not included in netcoreapp either.

**Comment by jkotas** [comment]
Left over from https://github.com/dotnet/corefx/issues/33374 . I think the fix should be to stop including these files in Microsoft.Private.CoreFx.NETCoreApp in corefx build.

@krwq Could you please take a look?

**Comment by krwq** [comment]
@jkotas yes, I was planning to start working on that and fix the testing right now

**Comment by krwq** [comment]
got side tracked and only got time now
