### ISSUE TITLE
Refactor and consolidate the AdapterUtil.cs

### ISSUE THREAD

**Issue by saurabh500** [dotnet/corefx#3535]
Reuse the common functions from AdapterUtil.cs 
The AdapterUtil is present in both Data.Common and Data.SqlClient with common functions.
Refactor the AdapterUtil.cs so that most of it can reside in Data.Common

**Comment by saurabh500** [comment]
Tagging Pull request https://github.com/dotnet/corefx/pull/2986

**Comment by cheenamalhotra** [comment]
@saurabh500 

Now that [AdapterUtil.cs](https://github.com/dotnet/SqlClient/blob/master/src/Microsoft.Data.SqlClient/netcore/src/Common/src/Microsoft/Data/Common/AdapterUtil.cs) is also present in Microsoft.Data.Common namespace, I think this issue can be closed?
