### ISSUE TITLE
FILETIME structure uses wrong type

### ISSUE THREAD

**Issue by Ziriax** [dotnet/corefx#35360]
In file `corefx/src/Common/src/CoreLib/System/Runtime/InteropServices/ComTypes/IMoniker.cs`, the type `FILETIME` uses `int` to map `dwLowDateTime` and `dwHighDateTime`.

However, this should be `uint`.

Is this mapping intentional, maybe for historical reasons?

**Comment by jkotas** [comment]
Yes, it is like that for historic reasons. Fixing this would be a breaking change

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.comtypes.filetime?view=netframework-4.7.2
