### ISSUE TITLE
Adding a .Batch to Linq

### ISSUE THREAD

**Issue by frankhaugen** [dotnet/corefx#35371]
This might have been suggested before, but I couldn't locate it. And it's my first attempt at something like this, so I apologize if I'm doing it wrong

I fin myself re-using this extension in almost all of my "large data"-projects, and I miss it as a "core feature" of Linq:
```C#
static class EnumerableExtensions
{
	public static IEnumerable<IEnumerable<TSource>> Batch<TSource>(this IEnumerable<TSource> source, int maxItems)
	{
		return source.Select((item, inx) => new { item, inx })
			.GroupBy(x => x.inx / maxItems)
			.Select(g => g.Select(x => x.item));
	}
}
```
It's as simple as it get's though I'd have to delve deeper into the Linq code before making it, as it seems to be "wrong" to use Linq in a Linq "feature"

Thank you for taking the time to consider my proposal

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/32412.  Thanks.
