### ISSUE TITLE
Discussion regarding support of CoreFX builds on non-windows OSes.

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#3538]
Today, building CoreFX on non windows platforms uses Mono as the runtime for all the managed code we need to run (namely MSBuild and Roslyn).

The long term goal is to instead run on-top of a stable CoreCLR build.  However, making this change has the possibility to regress supported build platforms since CoreCLR may not run everywhere Mono does (e.g. FreeBSD, other linux Distros, etc.)  As a concrete example, our tool runtime package (which we would use to run GenFacades) contains a CoreCLR which only supports Ubuntu 14.04<sup>[1](#fr1)</sup>.

With buildtools 97 we are at the point now where we can actually enable GenFacades and have it work on Ubuntu 14.04, but doing so will break the build on incompatible distros.  The question is, do we care enough to spend engineering effort to allow the build to work on platforms that we don't have a supported CoreCLR package for?  Do we expect that when MSBuild on .NET Core lands and we try to adopt it that we will remove our mono dependency entirely?  What does that mean for folks like the FreeBSD port team (/cc @janhenke), who want to build our stack on FreeBSD while they bring things up if we don't have FreeBSD packages?

I know that @pgavlin is chomping at the bit to get more of the build working on Linux.  It would be helpful to me as well, but we need closure here before we start going making changes that might break folks.  I see a few paths forward.
1. Say that building Managed CoreFX code cross platform requires your platform be supported by CoreCLR.  Since today the supported platforms are Ubuntu 14.04 and OSX, update build.sh to pass the correct RID for ToolNugetRuntimeId when invoking MSBuild.  If you are on a different distro and want to go out of your way to install the correct set of dependencies so an existing supported RID can run on your distro, you're free to do so and then use that RID.
2. Do platform detection and "light up" when we are running on a CoreCLR supported distro.  In this mode, if we are able to run CoreCLR, we prefer that otherwise we fallback to Mono.  For cases where we can't fallback (e.g GenFacades) we just no-op the relevant builds tasks.
3. Make the statement that managed code that runs during build time _must_ run on Mono and _may_ run on CoreCLR.  This is like (2) expect it means we can always fallback.  This is not true today.

I'm interested in getting everyone's take on this.  Maybe I'm freaking out over nothing and I can go ahead and just do (1) without anyone getting upset.

<sup><a name="fr1">1</a></sup> Technically, this could mean any OS that has a set of libraries which are binary compatible with the versions of our dependencies in Ubuntu 14.04.  For some dependencies this is easy (i.e. the version of openssl that is in another distro's package manager is probably binary compatible with the version in Ubuntu 14.04, but the version of the ICU library is probably not, since they decorate their export names per version).

**Comment by ellismg** [comment]
/cc @weshaggard @akoeplinger @nguerrera @bartonjs @Petermarcu 

I tagged a set of folks that I figure are interested in this and have strong opinions.  Feel free to pull in additional folks to the discussion.

**Comment by akoeplinger** [comment]
Can you share some details about what prevents GenFacades from working on Mono?

If at all possible I'd prefer (2) as Ubuntu 14.04 is a very narrow set of platforms and I think there are a *lot* of distros (e.g. Arch, openSuse, etc.) where Mono runs today but there's no CoreCLR package.

**Comment by janhenke** [comment]
@jasonwilliams200OK @josteink 

In general I have to keep a way for porting to new platforms. While FreeBSD supports seems mostly working, other platforms might be interesting to add in the future (e.g. OpenBSD, NetBSD). I also prefer option (2). Running on CoreCLR itself should be the goal, but we need to support Mono as a backup runtime.

For the Linux side I also second @akoeplinger's comment, Linux is not just Ubuntu. There is a wide variety of Linux distributions out there. We need a generic approach here that works with all systems, provided they have the necessary libraries. E.g. I am test building on my Gentoo system, which works fine so far. But it has probably quite different library versions (Gentoo is a rolling release distribution) and possible different symbol names (every library is compiled locally for just this system).

The whole packaging is in general still an area with open questions. We should aim for an approach, which is as generic as possible.

**Comment by ellismg** [comment]
> Can you share some details about what prevents GenFacades from working on Mono?

The major problem was that GenFacades is compiled against the .NET Core surface area (and we're trying to push more of our build tools to compile against this as well, e.g. BCL Rewriter) and Mono doesn't seem to support some of the new things in .NET 4.6 which are in .NET Core (e.g. Array.Empty<T> and there were some missing type forwards for some of the contracts).

**Comment by akoeplinger** [comment]
@ellismg I understand the motivation. Avoiding Array.Empty should be easy as GenFacades likely won't benefit much from it (Mono waits for the net46 referencesource drop to integrate the new APIs). Missing type forwards are an issue, we should look into adding the missing things to Mono, would love to get more details on them.

As I said, I think it's an important goal to still be able to build via Mono as a fallback.

**Comment by ellismg** [comment]
@akoeplinger 

> Avoiding Array.Empty should be easy as GenFacades likely won't benefit much from it.

The problem is IIRC Roslyn can insert calls on your behalf (e.g. calling param methods with no arguments) so simply building against the .NET Core surface area can create binaries that won't run on Mono.

> Missing type forwards are an issue, we should look into adding the missing things to Mono, would love to get more details on them.

I think the problem was that IOException moved down into the System.Runtime contract (from System.IO) and Mono didn't have the change.

One other option would be to produce two toolsets, one that targeted something like .NET 4.5.2 (or some profile that was compatible with Mono) and another that targeted .NET Core. In build.sh we detect if your platform is supported by .NET Core and then decide what tool-set to use.  This adds an additional cost to all the tools we use as part of the build, but maybe it's one the community is willing to help us pay.

> As I said, I think it's an important goal to still be able to build via Mono as a fallback.

Do you imagine there's a set of supported distros that if they worked out of the box then we would be able to cut Mono support?  If so, what does that set look like? What if we provided a way to provide a CoreCLR + Native Shim build you produced and used that in concert with the managed components from nuget?  I would rather us spend engineering effort moving folks towards a CoreCLR based world for our build (selfhosting and all that jazz) than trying to support two different runtimes at build time.

**Comment by akoeplinger** [comment]
> One other option would be to produce two toolsets, one that targeted something like .NET 4.5.2 (or some profile that was compatible with Mono) and another that targeted .NET Core.

Honestly I'd rather fix the issues in Mono that prevent it from running the .NET Core targeted package.

> Do you imagine there's a set of supported distros that if they worked out of the box then we would be able to cut Mono support?

I don't think so. There are just so many of them that you can't really please everyone.

> What if we provided a way to provide a CoreCLR + Native Shim build you produced and used that in concert with the managed components from nuget?

That sounds good.

**Comment by janhenke** [comment]
Indeed one set of managed assemblies for all Unix-like platforms should be the goal. Then bootstrapping would also not be an issue. Native Shims + CoreCLR should be compilable on new platforms to bootstrap at any given time.

**Comment by naamunds** [comment]
What would be the cost of producing binary packages of CoreCLR for FreeBSD and other Linux distributions?  Might it be less work than option 3 that you gave?  Why do we only support Windows, Ubuntu, and OS X today?  

One concern I have about option 2 is what happens if some piece of the CoreCLR build which is required for building CoreFX does not support Mono?  Does this option assume that all such required pieces of the build must always support Mono?  If so, might it actually not be significantly different than option 2?  I don’t have a good understanding of how much of the CoreCLR build is required for building CoreFX.

**Comment by mellinoe** [comment]
This is outdated and things have moved on; going to close.
