### ISSUE TITLE
Marshal.GetLastWin32Error doesnt seem to work (always return 0)

### ISSUE THREAD

**Issue by Sioma112233** [dotnet/corefx#35382]
Hey, 
I am trying to use Marshal.GetLastWin32Error on Linux and always get a 0 return value.
I tested the same code with dotnet-core and mono and came up with different results.
this code:
``` csharp
using System;
using System.Runtime.InteropServices;

namespace Test
{
    static class Program
    {
        static void Main(string[] args)
        {
            int fd = open("/this-path-is-not-real", 2); // 2 is ReadWrite

            Console.WriteLine(fd);
            Console.WriteLine(Marshal.GetLastWin32Error());
        }

  
        [DllImport("libc", SetLastError = true)]
        static extern int open(string pathname, int flags);
    }
}
```
**Mono Output (correct behaviour)**
```
-1
2 // 2 is the err-code of 'file not found'
```
**Dotnet-Core Output (incorrect behaviour)**
```
-1
0
```
I also tried opening the file in ReadOnly mode with same result

Thanks in advance

**Comment by Sioma112233** [comment]
Btw, using dotnet core 2.1.8

**Comment by stephentoub** [comment]
You're calling Marshal.GetLastWin32Error after calling WriteLine, which involves other p/invokes and syscalls. Try calling it immediately after open and storing the result into a local.

**Comment by Sioma112233** [comment]
You are right, solved the problem =D, my bad
