### ISSUE TITLE
SemaphoreSlim has avoidable sync-over-async that can cause spiral of death; discussion of potential fix

### ISSUE THREAD

**Issue by mgravell** [dotnet/corefx#35393]
Currently, the **synchronous** `SemaphoreSlim.Wait(...)` path includes, in some cases, a sync-over-async:

``` c#
return (asyncWaitTask != null) ? asyncWaitTask.GetAwaiter().GetResult() : waitSuccessful;
```

Specifically, it does this if the `SemaphoreSlim` is being used by a combination of sync/async consumers (`m_asyncHead != null)`).

Under load in a brief spike, this can cause an avoidable spiral of death: I have proc-dumps with 650+ threads stuck in the `Wait()` => `Task.SpinThenBlockingWait()` path, with **nobody** actively having the semaphore (it was being used as a mutex in this case, so expected 0 or 1). It *looks* like the `Task` layer wanted a worker thread to re-activate (presumably avoiding thread-theft, etc), and the workers were getting blocked here faster than they could unblock:

``` c#
ThreadPool.UnsafeQueueUserWorkItemInternal(waiterTask, preferLocal: true);
```

---

This appears to be avoidable; we don't really need a `Task` here - all we need is some blocking mechanism. Also, `Task` is pretty heavy-weight for this scenario.

Proposal:

- replace `TaskNode` with `INode`, with two implementations; has `void Activate();`
- existing call to `ThreadPool.UnsafeQueueUserWorkItemInternal` becomes `node.Activate()`
- one is `TaskNode` for the genuine async case; `Activate` uses `ThreadPool.UnsafeQueueUserWorkItemInternal` on self
- one is `MonitorNode`, for the sync case; `Activate` uses `lock(this) { Monitor.Pulse(this); }` or similar
- end of the `Wait` code-path waits (with timeout) on this lock (note: lock should be acquired *before* enqueue)
- to avoid creating unbound numbers of monitor-handles, slightly cheeky bit: since `Wait()` always runs on single thread, use a `[ThreadStatic] static MonitorNode _perThreadWaitNode` which is lazily instantiated (reset it to `null` in any critical failure scenario where it times out and we were unable to remove it from the linked-list, to avoid oddities)

---

Thoughts?

**Comment by mgravell** [comment]
(/cc @stephentoub)

**Comment by stephentoub** [comment]
Thanks, but I'm missing something. In what situation would a different Monitor-based blocking mechanism not incur the same spiral you refer to? Your proposal might save a bit of overhead when there are both sync and async waiters, but how would it avoid the starvation? Can you share a repro?

**Comment by stephentoub** [comment]
> would it avoid the starvation

Ah, you're saying that rather than queuing the "release", that would be done synchronously via Pulse.

**Comment by mgravell** [comment]
@stephentoub  exactly; so there is no need for a QUWI during `Release` when the next waiting item is from the `Wait` path rather than `WaitAsync`, and hence no additional worker activation needed to release the item in the success case; in the failure case, the Wait(timeout) deals with it. I have a working implementation of this approach in a `MutexSlim` that I've put together to get around the problem we saw here, if it would add context

**Comment by mgravell** [comment]
@stephentoub as an alternative fix that is less risky: leave most of the code unchanged, including the Task usage. But: track whether a node in the tree has come from sync Vs async routes. If it came from the sync path, use direct completion rather than QUWI: we know who the awaiter is (we have met the enemy, and they are us), and we know it not configured to steal our thread.

**Comment by stephentoub** [comment]
> track whether a node in the tree has come from sync Vs async 

Yes, that's what I'm planning to do.
