### ISSUE TITLE
HttpClient Recommendations in High-Perf, Low Allocation Scenarios

### ISSUE THREAD

**Issue by stevejgordon** [dotnet/corefx#35391]
This is not a bug report but more of a question to review usage guidance of handling request and response data for HttpClient. After discussing offline with @karelz we agreed it might be worth making a public issue to see where this leads!

The scenario I am focused on is using high-performance, low allocation features to reduce overhead if high volume data processing service workers. For example, we have a queue processor handling 10's of millions of events per day which needs to (after enriching) index data into ElasticSearch. I was curious whether I could reduce overhead by writing to the ElasticSearch API directly.

As a result, I've ended up with an early, first-pass, naive implementation and I'd appreciate opinions of the likely many ways it could be improved. I'd like to refine the example and then use it as the basis for blog posts to help members of the community with similar requirements.

Code for the example is available in my repo - https://github.com/stevejgordon/ElasticSearchClient

**Comment by stevejgordon** [comment]
A related query I also have is around any plans for HttpClient and related types to support low-alloc scenarios where we want to get lower-level and pass data as Span<byte> etc. I'm also thinking about scenarios where if possible I could send headers without allocating strings. I've not dived into the internals of HttpRequestMessage etc to know if this is simply a daft idea.

I'm playing with some other code to call some other APIs where I've also constructed my data using various Spans and pooled memory. If I could hook this into sending via HttpClient without allocating a bunch of strings that would potentially be handy. I'm also wondering if working with Sockets directly is an option but there's a lot to that including TLS support.

**Comment by Rodrigo-Andrade** [comment]
Today at an app of ours, most of the time HttpClient is parsing uris and headers. the current apis dont let us leverage stuff that dont change every request, like some static headers, or uris that only the querystring change, they have to be reparsed and validated every single request.

**Comment by karelz** [comment]
Triage: We started working on perf work already. We will make more changes in 5.0.
If there is anything specific that you think we should look at, please let us know and let's file concrete issues to discuss those options.
Thanks @stevejgordon!
