### ISSUE TITLE
ImmutableList of ValueTuples goes haywire on indexed access

### ISSUE THREAD

**Issue by Timovzl** [dotnet/corefx#35396]
Suppose we make an `ImmutableList<T>` of a `(string, string)` ValueTuple:

    private ImmutableList<(string Key, string Value)> Pairs
        = ImmutableList.Create(new[] { ("One", "Two") });

Access through `First()` is no problem:

    var tupleFirst = this.Pairs.First(); // ("One", "Two")
    var keyFirst = this.Pairs.First().Key; // "One"

Indexed access, `[0]`, seems fine until we access the ValueTuple's members:

    var tuple0 = this.Pairs[0]; // ("One", "Two")
    var key0 = this.Pairs[0].Key; // null - SAY WHAT?!

As soon as we navigate into the ValueTuple's members, they all come back as null. What's going on here?

**Edit**
Looking again, this happens only in the Immediate Window.
I thought I saw it happening regularly as well, but I was mistaken.

**Comment by 0xd4d** [comment]
Sounds like https://github.com/dotnet/roslyn/issues/29951

**Comment by Timovzl** [comment]
Turns out to be a reported [issue](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/694770) with the debugger.
