### ISSUE TITLE
System.Reflection.Emit Nuget package still missing APIs on .Net Standard 2.0

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/corefx#35414]
I'm currently looking into targeting .Net Standard for Iron Python: https://github.com/IronLanguages/dlr/issues/175

Some of the required Reflection.Emit APIs are missing from the System.Reflection.Emit nuget package when targeting .Net Standard 2.0, such as `DynamicMethod` and `TypeBuilder.CreateType()`. However they exist in both .Net Core and .Net Framework, and I believe it was decided in https://github.com/dotnet/corefx/issues/29365 (specifically from https://github.com/dotnet/corefx/issues/29365#issuecomment-398256162  and onwards) that such APIs should be included in the Nuget Package, and should throw when used from an AOT runtime.

The work to do that was completed in https://github.com/dotnet/corefx/pull/30741.

Is there any reason why the Nuget package doesn't seem to reflect this?

Thanks

**Comment by YairHalberstadt** [comment]
Ok, digging into this a little more:

The relavant APIs still need to be added to https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Emit/ref/System.Reflection.Emit.cs
and tests added, similar to https://github.com/dotnet/corefx/issues/30355.

Also the Nuget Package still hasn't been updated to reflect existing changes, such as the inclusion of `TypeBuilder.DefinePInvokeMethod`. Is there any reason for this?

**Comment by 0xd4d** [comment]
Did you try the latest preview: 4.6.0-preview.19073.11 and System.Reflection.Emit.Lightweight (for DynamicMethod)? TypeBuilder.CreateType() -> TypeBuilder.CreateTypeInfo()

**Comment by YairHalberstadt** [comment]
@0xd4d
Yes

**Comment by YairHalberstadt** [comment]
Actually I didn't try Lightweight

**Comment by YairHalberstadt** [comment]
@0xd4d 
You're right! That should work. Thanks

**Comment by YairHalberstadt** [comment]
Before I close this issue, could I have clarity on what the differences are between the prerelease package, which is after the relisting, and the stable package which is before the relisting?

If I use the stable packages, will the methods throw a PNSE on AOT? What about the prerelease?

**Comment by YairHalberstadt** [comment]
I can confirm that the methods throw a PNSE on the prerelease, but not the stable.
