### ISSUE TITLE
Change NetworkStream.Socket property from protected to public

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#35410]
NetworkStream currently has a `protected Socket Socket { get; }` that allows a derived type to access the underlying socket.  It's valuable in some situations however for an arbitrary consumer of NetworkStream to have direct access to the Socket, e.g. we need to work around the lack of this in SocketsHttpHandler, which needs to fish out the underlying socket from the stream if at all possible.  We should add some public property for this; if we can't change the visibility of the existing property, we can add a new one.

**Proposal**

```C#
public class NetworkStream
{
    ...
    public Socket Socket { get; } // change existing protected property to be public
    ...
}
```

**Comment by karelz** [comment]
`Socket` property is protected, but not virtual, which means we should be able to just change its visibility.

**Comment by terrajobst** [comment]
Seems fine. The only question is: @scalablecory mentioned that we might want to use `NetworkStream` for non-socket based streams, e.g. QUIC. What would happen then?

**Comment by terrajobst** [comment]
Seems fine. The only question is: @scalablecory mentioned that we might want to use `NetworkStream` for non-socket based streams, e.g. QUIC. What would happen then?

> `Socket` property is protected, but not virtual, which means we should be able to just change its visibility.

That's correct and we've done this in the past.

**Comment by stephentoub** [comment]
> we might want to use NetworkStream for non-socket based streams. What would happen then?

`Socket` is already exposed, it's just protected rather than public.  I don't think we'd choose to break the protected property any more than a public one, would we?

Also, it's System.Net.**Sockets**.NetworkStream... pretty tightly connected to **Sockets** already.

@scalablecory, what did you have in mind?

**Comment by felipepessoto** [comment]
If it involves something more than changing the property visibility, I might help. Creating tests, validation, etc.

Thanks

**Comment by stephentoub** [comment]
> If it involves something more than changing the property visibility, I might help. Creating tests, validation, etc.

@felipepessoto, yes:
- Flipping the visibility
- Adding it to the ref assembly
- Adding tests (or if there are already some, since it's protected, fixing them up accordingly)
- Fixing SocketsHttpHandler to use it rather than creating its own derived type, i.e. delete this https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ExposedSocketNetworkStream.cs#L7-L13 and just use NetworkStream instead

**Comment by felipepessoto** [comment]
Yes. I'll do it. Thanks
