### ISSUE TITLE
System.Drawing.Common\tests\Drawing2D\GraphicsPathTests AssertClosedCurve fails on arm32/64.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/corefx#35424]
AssertClosedCurve checks:
```
GraphicsPath gpi = new GraphicsPath();
gpi.AddClosedCurve(new Point[3] { new Point(1, 1), new Point(2, 2), new Point(3, 3) });
Assert.Equal(new RectangleF(0.8333333f, 0.8333333f, 2.33333278f, 2.33333278f), path.GetBounds());
```
and it fails on arm32/64 because `AddClosedCurve` returns there a different left bottom point: `X=0.8333334, Y=0.8333334` instead of `X=0.8333333, Y=0.8333333`.

There are 3 places where this issue can be fixed (in my understanding):
1. fix `operator ==` to compare floats with epsilon:
https://github.com/dotnet/corefx/blob/383e8d6d5cabcadd9bbb726e8f9568751890ec7a/src/System.Drawing.Primitives/src/System/Drawing/RectangleF.cs#L209-L211

2. fix Windows API function `GpStatus WINGDIPAPI GdipAddPathClosedCurve2` that is called from `AddClosedCurve` to return the same result on WIndows x64 and Windows arm32/64 ;

3. fix the test/delete the assert:
https://github.com/dotnet/corefx/blob/383e8d6d5cabcadd9bbb726e8f9568751890ec7a/src/System.Drawing.Common/tests/Drawing2D/GraphicsPathTests.cs#L2477

**Comment by wfurt** [comment]
closing as dup of #35744 We will need some better way how to compare objects with floats.

**Comment by sandreenko** [comment]
Do you mean to close #35744 (opened 3 days ago) as duplicate of this one (opened 15 days ago)?

**Comment by wfurt** [comment]
yes. because people already start looking at it.

**Comment by safern** [comment]
I think we are going to fix the assertions to allow a small variance in the values, because it seems like the result different is coming from the CRT `cosf`, `sinf`, and `atan2f` functions that are being used in the internal implementations. Closing since we're tracking the issue with #35744 and we already have a thread going there.
