### ISSUE TITLE
Package harvesting doesn't account for servicing

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#35425]
Today we only harvest assets from the last stable package, however its possible for us to service older releases such that the "latest package" is missing that servicing fix.  Typically we then make sure to build a new "latest" package that harvests assets from the older releases servicing package,  but this can get complicated and is completely *manual*.  We should think more about what it means to flow harvested bits around and think through policies/tooling we can implement to make it less error prone.

/cc @wtgodbe

**Comment by ViktorHofer** [comment]
Fixed by https://github.com/dotnet/corefx/commit/2c974d484209ab46815ec9abd35936ca66f2444e and by added documentation for servicing packaging work.
