### ISSUE TITLE
HTTP2: Cookie tests randomly failing

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#35422]
I've seen this on multiple PRs and on some of my Linux VMs / WSL machines.

Tests failing:
System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies_Http2

* GetAsync_ReceiveSetCookieHeader_CookieAdded()
* GetAsync_SetCookieContainer_CookieSent()

The tests appear to fail with HttpRequestException.  There is no inner exception shown.  However, debugging shows that the failure is due to an ObjectDisposedException:

``` System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies_Http2.GetAsync_ReceiveSetCookieHeader_CookieAdded(cookieName: "Hello", cookieValue: "World", useCookies: False) [FAIL]
        System.Net.Http.HttpRequestException : An error occurred while sending the request.
        ---- System.ObjectDisposedException : The semaphore has been disposed.
        Stack Trace:
          /home/localadmin/GitHub/corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs(1249,0): at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
          /home/localadmin/GitHub/corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(506,0): at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
```

Inner exception stack trace:

```
          ----- Inner Stack Trace -----
          /__w/3/s/src/System.Private.CoreLib/shared/System/Threading/SemaphoreSlim.cs(927,0): at System.Threading.SemaphoreSlim.CheckDispose()
          /__w/3/s/src/System.Private.CoreLib/shared/System/Threading/SemaphoreSlim.cs(863,0): at System.Threading.SemaphoreSlim.Release(Int32 releaseCount)
          /home/localadmin/GitHub/corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs(919,0): at System.Net.Http.Http2Connection.SendHeadersAsync(HttpRequestMessage request)
          /__w/3/s/src/System.Private.CoreLib/shared/System/Threading/Tasks/ValueTask.cs(762,0): at System.Threading.Tasks.ValueTask`1.get_Result()
          /home/localadmin/GitHub/corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs(1229,0): at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
```

**Comment by davidsh** [comment]
Initial analysis from @stephentoub 

"That suggests that Http2Connection.CheckForShutdown was called and made it to the end, resulting in _writerLock.Dispose() getting called, and then code subsequently tries to use _writerLock."

**Comment by davidsh** [comment]
I submitted PR #35423 to improve the diagnostics.  So, after that PR is merged, any failures here will always show the inner exception (i.e. ObjectDisposedException).

**Comment by geoffkizer** [comment]
The timing issue is as follows:

SendHeadersAsync takes the writer lock and sends the headers
We receive a GOAWAY and the full response, causing CheckForShutdown to dispose the writer lock
SendHeadersAsync releases the writer lock, which now throws because it was disposed

We need to somehow defer disposing the writer lock until we know that no one is using it.

@rmkerr, this is related to your PR

**Comment by geoffkizer** [comment]
All that said, I sort of wonder if we actually need to dispose the writer lock here at all. We are only using it asynchronously, so presumably no kernel handle is ever allocated. @stephentoub thoughts?

**Comment by davidsh** [comment]
>We need to somehow defer disposing the writer lock until we know that no one is using it.

This problem reminds of another issue we have (unrelated to HTTP2) but dealing with disposing an object while another object is using it.

I wish .NET had reference counting semantics similar to COM, i.e. AddRef(), Release().  Because if it did, then Dispose() would work like that, i.e. doing a Release().  But the actual object wouldn't be destroyed until all callers did a Release() of it.

**Comment by stephentoub** [comment]
> All that said, I sort of wonder if we actually need to dispose the writer lock here at all. We are only using it asynchronously, so presumably no kernel handle is ever allocated. @stephentoub thoughts?

Technically there's no need to dispose of it.  The only meaningful thing SemaphoreSlim.Dispose does is free the WaitHandle that's allocated lazily if you access SemaphoreSlim.AvailableWaitHandle, and we're not doing that.  Obviously SemaphoreSlim.Dispose could change in the future to make it more meaningful to Dispose, but it hasn't changed since it was originally built, and it's probably not going to any time soon... and if it did, this code could be changed, too.

Still, even if we were to remove the Dispose, I'd want to make sure that we weren't doing so as a bandaid.  It feels right now like we don't have a good handle on the lifetime semantics of various objects, when things are actually expected to not be used anymore, etc.  I'm fine if we decide not to call SemaphoreSlim.Dispose, but I do want to make sure we have a firm grasp on exactly where/when we would safely.

**Comment by rmkerr** [comment]
> We need to somehow defer disposing the writer lock until we know that no one is using it.

Why not just acquire the writer lock before disposing it?

**Comment by stephentoub** [comment]
> Why not just acquire the writer lock before disposing it?

That doesn't prevent someone from trying to acquire it.

**Comment by rmkerr** [comment]
That makes sense. Thanks Stephen.

I agree that we have some issues with object lifetimes in the HTTP/2 code, particularly when streams or connections are closed. I don't think it's going to be super tough to fix, but it does need to happen.

**Comment by geoffkizer** [comment]
Failing on acquiring it is fine. At that point the underlying stream is closed anyway.

That said, I do agree with your larger point here:

> It feels right now like we don't have a good handle on the lifetime semantics of various objects

**Comment by stephentoub** [comment]
> Failing on acquiring it is fine. At that point the underlying stream is closed anyway.

Calling WaitAsync on a disposed SemaphoreSlim will throw an exception. That's not fine :-) Even if we were to catch it and eat it, that's a large unnecessary expense.

**Comment by geoffkizer** [comment]
The exception should only happen when we race between a new request and receiving a shutdown from the server, and there's not much we can do to avoid it.

**Comment by stephentoub** [comment]
> The exception should only happen when we race between a new request and receiving a shutdown from the server, and there's not much we can do to avoid it.

Is it that the thing we'd use to avoid it is the very lock in question?  If so I agree we simply shouldn't dispose it.  We debated in general whether to expose IDisposable on such locking primitives; in the end we ended up doing so, under the principle that you should be able to aggressively dispose of your resources, but there are also cases where it simply doesn't make sense to do it.

**Comment by geoffkizer** [comment]
I'm not sure. I think we need to review how we manage shutdown in general. It may be that not disposing the semaphore makes sense, but I don't know yet.

**Comment by geoffkizer** [comment]
BTW, we are often going to throw on shutdown because we always have a pending read and the only way to cancel it is to close the connection.

**Comment by geoffkizer** [comment]
All that said, since reworking shutdown is not trivial, we should probably just do a quick change to not dispose the writer lock so that we fix this issue. And file a separate issue for revisiting the shutdown logic.

**Comment by geoffkizer** [comment]
I added a separate issue to review and clean up shutdown behavior, #35466
