### ISSUE TITLE
Repo organization guidelines for Common\tests

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#3543]
Currently, there's a free-for-all regarding how code is placed in `src/Common/tests` folders, unlike the `src/Common/src` folder tree which has clear guidelines.

There are a few proposals:
1) Mirror the `src/Common/src` idea and have everything properly aligned to the namespace. So, the folder paths would look like this:

`src/Common/tests/System/Net/Http/HelperClass.cs`.  

Note that each namespace path is one word only per part in the pathname.

This seems to be the most logical choice although. It could create some confusion at first since, for example, Sockets tests will add to Threading, EventSource and Resources but in the end will allow for better organization, review and increase code reuse.

2) Organize `src/Common/tests` per namespace ownership: /System.Net; /System.Xml, etc. So, the folder paths would look like this:

`src/Common/tests/System.Net.Http/HelperClass.cs`

This is partially what's going on today although there are folders that aren't fully specifying the namespace such as Collections, Compression, etc.

Please add your opinions.

**Comment by davidsh** [comment]
I like the first option 1).  We should have the paths be broken up per word, the same as the src tree.

**Comment by pgavlin** [comment]
I agree with @davidsh; it seems reasonable to be consistent here.

**Comment by stephentoub** [comment]
Yes, we should do (1).  With a few exceptions, the files in Common are essentially a big internal-only class library used by the rest of corefx, with files from e.g. System/IO used by multiple assemblies and not just System.IO.

I'll fix it up.
