### ISSUE TITLE
API proposal: lightweight task creation facility

### ISSUE THREAD

**Issue by mgravell** [dotnet/corefx#35441]
Problem:

When writing libraries that are heavily task-based, it is often the case that you want to create a task that your library needs to update later, out-of-band (so not a typical `async` method). Currently, the typical way of doing this is to create and hold onto a `TaskCompletionSource<T>` *in addition to* any other state you need. `TaskCompletionSource<T>`, however, is simply an object that wraps a single readonly `Task` field, with methods to interact with it.

This means allocating an extra object each time; for many scenarios: fine, but... kinda unnecessary and awkward for high volume usage, and extra *unnecessary* GC work.

If you're lucky, you can compose your "other state" such that you subclass `TaskCompletionSource<T>` to avoid the extra allocation (assuming your "other state" already involved an object), but this then gives you a scrappy API unless you hide the *intended* API behind an interface, and hide the fact that it is really a `TaskCompletionSource<T>`. I think there *is* also a way to abuse `AsyncTaskMethodBuilder<T>` for similar purposes, but it is ... frankly API abuse and not small (due to the core state etc).

---

Two immediate options come to mind:

- create a `readonly struct` that is basically a direct copy of `TaskCompletionSource<T>`; heck, call it `ValueTaskCompletionSource<T>` and have it expose the `m_Task` (the same `Task<T>` from before) as a `ValueTask<T>` on the public API - anyone who really wants the `Task` can call `AsTask()` and get it back
- create a new `CompletableTask<T> : Task<T>` with **public** constructors and method that match the API from `TaskCompletionSource<T>`

(the first sounds easier to implement, as it is a copy with a handful lines of code changed)

With either outcome: the new type can be held as state and manipulated, without needing an extra allocation for every single instance.

/cc @stephentoub

**Comment by Wraith2** [comment]
From what i remember of ValueTask<T> i think option 1 would be problematic. Once one caller has interacted with the field no others should and if it's part of a larger object it would be easy for people to make a mistake and do so.

**Comment by mgravell** [comment]
@Wraith2 no, that wouldn't be a problem and wouldn't be a change from how `TaskCompletionSource<T>` works today; but... this might not be needed - see next:

**Comment by mgravell** [comment]
Note: for `ValueTask<T>`-specific usage, this can be implemented using `ManualResetValueTaskSourceCore<TResult>` to create your own `IValueTaskSource`, and using a `new ValueTask<T>(yourCustomSource, token)`.

This doesn't help with existing `Task<T>` APIs, though...

**Comment by tarekgh** [comment]
CC @stephentoub

**Comment by mgravell** [comment]
Side note: the only awkward bit I can see here is what to do if someone uses `default`/`new()` on the struct type. Meaning: should extra code be added so that anything that touches `m_task.Whatever()` becomes `(m_task ?? ThrowNRE().Whatever())`

**Comment by AndreasTruetschel** [comment]
@mgravell I exactly built this what you propose initially some time ago. It is called `ValueTaskCompletionSource` and is designed as a drop-in replacement for `TaskCompletionSource<T>`.  
The only differences are:
* There is a non-generic version, as `ValueTask<T>` cannot be cast to the non generic `ValueTask` as easily as can done with `Task<T>`
* As you already mentioned `ValueTaskCompletionSource` is a struct and needs some other way of initialization then the default constructor. My solution to this is providing a static `Create` method. If one calls the default constructor or uses `default`, the `ValueTaskCompletionSource` behaves like it was created normally and already completed, with a default value for the result in case of the generic version.

This can be found [here](https://github.com/AI4E/AI4E.Utils/blob/master/src/AI4E.Utils/Async/ValueTaskCompletionSource.cs).

**Comment by stephentoub** [comment]
> basically a direct copy of TaskCompletionSource<T>; heck, call it ValueTaskCompletionSource<T> and have it expose the m_Task (the same Task<T> from before) as a ValueTask<T> on the public API - anyone who really wants the Task can call AsTask() and get it back

This effectively exists: `AsyncTaskMethodBuilder<T>` is a struct, provides a `Task` property that returns the associated `Task<T>`, has `SetResult/Exception` methods, etc.  It's meant to be used by the compiler for `async Task<T>` methods, but nothing prevents you from using it directly.

Plus, if someone really cares about this allocation, they're likely going to want to go further and use `ManualResetValueTaskSource<T>` to create their own cacheable/reusable `ValueTask<T>`s (or rely on the runtime to do it for them if we end up doing that for all `async ValueTask<T>` methods).

Given all that, I don't see further types being exposed for this, so I'm going to close the issue.  Thanks for the suggestion.
