### ISSUE TITLE
Unhelpful error message when using System.Reflection.Emit on UWP

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/corefx#35443]
System.Reflection.Emit preview throws an exception when used on UWP in Release build:

> System.PlatformNotSupportedException: PlatformNotSupported_RefEmit. For more information, visit http://go.microsoft.com/fwlink/?LinkId=623485

Following the link gives you this suggestion:

> ### Runtime exception messages
> To minimize application executable size, .NET Native does not include the full text of exception messages. As a result, runtime exceptions thrown in release builds may not display the full text of exception messages. Instead, the text may consist of a substring along with a link to follow for more information. For example, the exception information may appear as:
> 
>> Exception thrown: '$16_System.AggregateException' in Unknown Module.  
>>  
>> Additional information: AggregateException_ctor_DefaultMessage  
>   
>> If there is a handler for this exception, the program may be safely continued.  
>
> **If you need the complete exception message, run the debug build instead.** For example, the previous exception information from the release build might appear as follows in the debug build:
> 
>> Exception thrown: 'System.AggregateException' in NativeApp.exe.  
>>   
>> Additional information: Value does not fall within the expected range.  

However running the debug build, Emit is supported, so no exception occurs!

**Comment by danmosemsft** [comment]
Is this a broader issue? It is probably not worth doing something special just to show "ref emit is not supported"..

**Comment by YairHalberstadt** [comment]
I think this is a broader issue, as I explain in the issue I raised on the docs repository: https://github.com/dotnet/docs/issues/10576

**Comment by steveharter** [comment]
This is a known issue. Unfortunately changing this would break applications that already depend on this.

See also https://github.com/dotnet/corefx/issues/30654

**Comment by ViktorHofer** [comment]
Because of the high servicing bar we can't take any breaking issues. Therefore closing this.
