### ISSUE TITLE
Console.KeyAvailable throws when no terminal attached

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#35479]
Here is the error I'm getting:

```
Unhandled Exception: System.InvalidOperationException: Cannot see if a key has been pressed when either application does not have a console or when console input has been redirected from a file. Try Console.In.Peek.
   at System.Console.get_KeyAvailable()
   at SonarTest.Program.Main(String[] args) in /home/krwq/src/test-app/Program.cs:line 85
/home/pi/iot-hackathon.sh: line 3:   506 Aborted                 /home/pi/test-app/test-app
```

to run app like that

```shell
nohup ./app &
```

It should just return false when there is no terminal or at least give a way of checking if there is one

cc: @wfurt

**Comment by stephentoub** [comment]
> It should just return false when there is no terminal or at least give a way of checking if there is one

That's coming from here:
https://github.com/dotnet/corefx/blob/7817a109400b5b22c02ae6667706cda8a7f3d168/src/System.Console/src/System/Console.cs#L93-L96
so the check would be:
```C#
if (!Console.IsInputRedirected) { … }
```

**Comment by krwq** [comment]
Nice! Thank you! I think this can be closed in this case
