### ISSUE TITLE
SqlClient: Allow specifying a UDT SqlParameter value via SqlBytes

### ISSUE THREAD

**Issue by bricelam** [dotnet/corefx#35470]
Today, it's possible to read a UDT value as a SqlBytes object from SqlDataReader using GetSqlBytes.

``` csharp
var connection = new SqlConnection(@"Data Source=(localdb)\MSSQLLocalDB");
connection.Open();

var command = connection.CreateCommand();
command.CommandText = "SELECT geometry::Parse('POINT(0 0)')";

var reader = command.ExecuteReader();
reader.Read();
var geometrySqlBytes = reader.GetSqlBytes(0);
```

Unfortunately, there is no way to specify a UDT value as a SqlBytes object in SqlParamter.

``` csharp
var connection = new SqlConnection(@"Data Source=(localdb)\MSSQLLocalDB");
connection.Open();

var command = connection.CreateCommand();
command.CommandText = "SELECT @Point.X";

var parameter = command.Parameters.AddWithValue("@Point", geometrySqlBytes);
parameter.SqlDbType = SqlDbType.Udt;
parameter.UdtTypeName = "geometry";

// ArgumentException: Specified type is not registered on the target server. SqlBytes
var x = command.ExecuteScalar();
```

SqlBytes should be special cased in this codepath as a means of merely specifying the bytes to send to the server.

cc @ajcvickers @divega

**Comment by AfsanehR** [comment]
Thanks @bricelam I can confirm that this is happening both in .Net Core and .Net Framework.

**Comment by saurabh500** [comment]
@bricelam  What is the use case for this? How will the bytes be constructed in the first place ?

**Comment by saurabh500** [comment]
NVM I read through https://github.com/NetTopologySuite/NetTopologySuite/issues/302
