### ISSUE TITLE
NetworkInterface.GetAllNetworkInterfaces exceptions thrown internally showing up in debugger

### ISSUE THREAD

**Issue by mdisg** [dotnet/corefx#35480]
Recently i attached the debugger to our application which we have ported from .NET 4.5 to .NET Core using it on a linux system build with buildroot.

In the debug output there were exceptions like `System.IO.DirectoryNotFoundException` and `System.IO.FileNotFoundException` showing up. Looking for the reason revealed that two files are going to be read by the call `NetworkInterface.GetAllNetworkInterfaces()` which are

- /var/lib/dhcp/dhclient.leases
- /etc/samba/smb.conf

Both files and also the directories do not exist on the system because we don't use DHCP at the moment and samba will never be installed.

The reason for the exceptions are missing `File.Exists` checks in the methods `ParseWinsServerAddressesFromSmbConfFile` and `ParseDhcpServerAddressesFromLeasesFile` in the source [StringParsingHelpers.Addresses.cs](https://github.com/dotnet/corefx/blob/master/src/System.Net.NetworkInformation/src/System/Net/NetworkInformation/StringParsingHelpers.Addresses.cs)

I think it would be better to check if the files exist rather then silently catch the exceptions if the don't.

@mellinoe if i'm not mistaken you created that code part, what do you think?

**Comment by tmds** [comment]
> a linux system build with buildroot.

Cool! Are you building bits of .NET Core yourself to make it work with buildroot?

> I think it would be better to check if the files exist rather then silently catch the exceptions if the don't.

Makes sense.

**Comment by mdisg** [comment]
> 
> 
> Cool! Are you building bits of .NET Core yourself to make it work with buildroot?
> 
@tmds The prebuild runtime available for download works on that system without modification but such things as the missing file check are likely to show up on such a system because there are not that much applications installed to reduce memory consumption because it's a embedded arm system.

> I wonder why these show up in your debugger in particular. Does this mean corefx doesn't typically throw anything? Or is it a setting of the debugger to not show exceptions from the framework?

Internal catched exceptions show up in the debug output as `Exception thrown: x in x.dll` but the debugger does not break on it by default. We call `NetworkInterface.GetAllNetworkInterfaces()` every minute to check if something on the network configuration has changed. So there were about 3-4 exceptions showing up every call of that method which made me wonder what is happening so i activated the exceptions under the exception settings  `Break When Thrown`. After that i could retrieve the exception message what is causing the exception to be thrown.

**Comment by tmds** [comment]
> @tmds The prebuild runtime available for download works on that system without modification

Ah. Does your embedded Linux stack use glibc?

**Comment by mdisg** [comment]
@tmds Yes glibc 2.22

**Comment by stephentoub** [comment]
> I think it would be better to check if the files exist rather then silently catch the exceptions if the don't.

Doing a File.Exists to avoid the exception in most cases seems reasonable, but we should keep the catch blocks as well, just in case.
