### ISSUE TITLE
BrotliStream allocates 65K buffer

### ISSUE THREAD

**Issue by Timovzl** [dotnet/corefx#35487]
`BrotliStream` allocates a `byte[]` buffer of `DefaultInternalBufferSize`=65K, as can be seen in the source:
https://github.com/dotnet/corefx/blob/master/src/System.IO.Compression.Brotli/src/System/IO/Compression/BrotliStream.cs

This seems like a sizeable allocation for every stream. The stream option is attractive because it makes it very easy to use the algorithm correctly. It is made less attractive by the buffer allocation.

The stream is already disposable, so its seems trivial to _rent_ a buffer instead of allocating one. To rent from `MemoryPool`, the buffer's type would have to change to `Memory<byte>`. Alternatively, `ArrayPool` might be used, although the former seems preferable.

**Comment by joshfree** [comment]
Thanks for reporting this @Timovzl 😄
