### ISSUE TITLE
Fake async implementation of TextWriter.FlushAsync

### ISSUE THREAD

**Issue by baal2000** [dotnet/corefx#35495]
[TextWriter.FlushAsync](https://github.com/dotnet/corefx/blob/6622937a3ccdb0ebe81747e92903a009e1702575/src/Common/src/CoreLib/System/IO/TextWriter.cs#L617) wraps synchronous counterpart `TextWriter.Flush()` into `Task.Run()`. Would it be rather more honest to not implement and let the users deal when needed?

**Comment by stephentoub** [comment]
What does it mean to not implement it?  These are virtual methods on an abstract type.  The expectation is that a derived types override these.  But for ones that don't, a consumer still needs the method to behave reasonably.

**Comment by baal2000** [comment]
Leaving as abstract would work. If must be implemented as virtual base class method and there is no native support for async then it is reasonably to do the way is done in [SyncTextWriter.FlushAsync](https://github.com/dotnet/corefx/blob/6622937a3ccdb0ebe81747e92903a009e1702575/src/Common/src/CoreLib/System/IO/TextWriter.cs#L863).

**Comment by stephentoub** [comment]
It can't be left as abstract; it was added after the type was already released, so it would have been a big breaking change to add a new abstract method to an already shipped type.

**Comment by baal2000** [comment]
The behavior may still be changed to synchronous without making that abstract but that is up to you. I guess there is a reason for the method to be implemented this way that we may never know.

Thanks.

**Comment by stephentoub** [comment]
> I guess there is a reason for the method to be implemented this way that we may never know.

Both options (sync and async invocation) have pros and cons.  For example, a benefit to invoking the operation async are that arbitrary implementations could have a Flush method that takes a really long time, and callers may reasonably expect that a FlushAsync returns the Task close to immediately; this is relevant if, for example, the caller wants to invoke multiple operations concurrently and then wait for them all to complete.
