### ISSUE TITLE
Consider removing Range.OffsetAndLength

### ISSUE THREAD

**Issue by terrajobst** [dotnet/corefx#35508]
We currently have this nested type for `Range`:

```C#
namespace System
{
    public partial struct Range
    {
        public OffsetAndLength GetOffsetAndLength(int length);

        public readonly struct OffsetAndLength
        {
            public int Offset { get; }
            public int Length { get; }
 
            public OffsetAndLength(int offset, int length);
            public void Deconstruct(out int offset, out int length);
        }
    }
}
```

However, considering that the outputs are fixed, we should consider making this simply a tuple:

```C#
namespace System
{
    public partial struct Range
    {
        public (int Offset, int Length) GetOffsetAndLength(int length);
    }
}
```

/cc @tarekgh @stephentoub @dotnet/fxdc

**Comment by tarekgh** [comment]
I agree this is simpler. I got push back during the code review against using Tuple as I had the original implementation in the PR as described here. anyway, I am fully agree with what proposed here.

**Comment by danmosemsft** [comment]
I thought there was a general discussion about using Tuple in public API, @terrajobst and the feeling was that it wasn't a good idea - I recall mention was made of naming and tooling support. Do I remember wrong?

**Comment by bartonjs** [comment]
We had a meeting on it today, and landed on PascalCasing.  Since "OffsetAndLength" is pretty clearly just a 2-tuple, apparently Immo is excited to (re-)start our use of "AVOID" tuples instead of "DO NOT" use tuples.

**Comment by terrajobst** [comment]
I feel called out 🤘😎

**Comment by tarekgh** [comment]
@terrajobst I assume this is not approved yet. right? or should I assume otherwise.

**Comment by bartonjs** [comment]
> I assume this is not approved yet. right?

Right.  Still `api-ready-for-review`.

**Comment by terrajobst** [comment]
Yep, the intention of this item is to have the conversation with @dotnet/fxdc in the usual forum :-)

**Comment by terrajobst** [comment]
@tarekgh would you mind taking care of this as well?

**Comment by tarekgh** [comment]
@terrajobst sure :-) I am happy we are changing this.

**Comment by tarekgh** [comment]
This is done now.
