### ISSUE TITLE
Add APIs for some threading metrics

### ISSUE THREAD

**Issue by kouvel** [dotnet/corefx#35500]
From https://github.com/dotnet/coreclr/issues/20372

```c#
    public static class ThreadPool
    {
        public static long CompletedWorkItemCount { get; }
        public static long PendingLocalWorkItemCount { get; }
        public static long PendingGlobalWorkItemCount { get; }
        public static long PendingWorkItemCount { get; }
        public static int ThreadCount { get; }
    }

    public static class Monitor
    {
        public static long LockContentionCount { get; }
    }
```

- `ThreadPool.CompletedWorkItemCount`
  - Gets the number of work items that have been processed so far
  - For a thread pool implementation that may have different types of work items, the count includes all types (user work items including tasks, timer callbacks, wait callbacks, and IO completions)
  - Changes over units of time would be plottable and would allow calculating throughput and average work item duration
  - There is some overhead in tracking this information, but it seems to be negligible
- `ThreadPool.PendingLocalWorkItemCount`
  - Gets the number of local work items that are currently queued to be processed
  - Local work items are work items queued in some fashion that has association with a particular thread or its execution environment, and are typically processed in last-in-first-out order. They may include tasks and work items queued with `QueueUserWorkItem(..., preferLocal: true)`.
- `ThreadPool.PendingGlobalWorkItemCount`
  - Gets the number of global work items that are currently queued to be processed
  - Global work items are shared by all thread pool worker threads and are typically processed in first-in-first-out order. See `PendingWorkItemCount` for other relevant remarks.
- `ThreadPool.PendingWorkItemCount`
  - Gets the number of work items that are currently queued to be processed
  - For a thread pool implementation that may have different types of work items, the count may not include all types. The count may only include user work items including tasks. Some implementations may also include queued timer and wait callbacks in the count. On Windows, the count is unlikely to include the number of pending IO completions, as they get posted directly to an IO completion port.
- `ThreadPool.ThreadCount`
  - Gets the number of thread pool threads that currently exist
  - For a thread pool implementation that may have different types of threads, the count includes all types
- `Monitor.LockContentionCount`
  - Gets the number of times there was contention upon trying to take a `Monitor`'s lock so far
  - Changes over units of time would be plottable and would allow calculating frequency of contention

CC @noahfalk @stephentoub @sywhang @vancem

**Comment by danmosemsft** [comment]
Since area owner is proposing this, I guess it is ready for review.

**Comment by kouvel** [comment]
I think we have already discussed most of the things on the other issue, but if anyone has any suggestions on naming or behavior, please let me know.

**Comment by kouvel** [comment]
There is also this related request: https://github.com/dotnet/corefx/issues/34277. Perhaps we could also add properties like `PendingLocalWorkItemCount` and `PendingGlobalWorkItemCount` in addition. In CoreCLR the global one can include work items from the unmanaged side. As for "local"/"global", that distinction in naming and behavior is already there in a `QueueUserWorkItem` overload. The total is probably also good to have.

**Comment by kouvel** [comment]
Updated proposal inline to include `PendingLocalWorkItemCount` and `PendingGlobalWorkItemCount`

**Comment by kouvel** [comment]
@terrajobst, would it be possible to review this soon? The work to expose these is currently targeted for 3.0 and there is other 3.0 work to expose event counters that depends on this.

**Comment by ghuntley** [comment]
Being discussed at https://www.youtube.com/watch?v=vHqgsQ23GRg

**Comment by terrajobst** [comment]
Looks good.

The only concern is about local vs. global. Unless there is a specific scenario needing the differentiation. If there isn't we should just expose the total.

**Comment by danmosemsft** [comment]
@kouvel I guess this stays open because https://github.com/dotnet/corefx/pull/37401 was only part of the work?

**Comment by kouvel** [comment]
This was only meant to be open until the APIs were exposed, closing with https://github.com/dotnet/corefx/pull/37401

**Comment by danmosemsft** [comment]
@kouvel I meant because you didn't expose all the above, but I guess that was intentional
https://github.com/dotnet/corefx/pull/37401/commits/abc1e2caabcf27eae089ce9d7e2d45cf8f4423c3

**Comment by kouvel** [comment]
Oh ok, yes that was intentional. We had decided to start with not distinguishing local vs global work items, and those could be added later if needed.
