### ISSUE TITLE
Common sln for both .NET framework and Core

### ISSUE THREAD

**Issue by jchang6** [dotnet/corefx#35504]
Ok, so I have managed to port one application from .NET Framework 4.6.1 to Core 3.0.
The same code files now work for both, but I seem to need separate sln and directories for each project, except that the Core project excludes the \Properties\AssemblyInfo.cs file. 
If I try to have one directory with one proj file for Framework and another for Core, 
the Core project builds, but the Framework project complains I am missing the Target Framework Version entry, even though it is in proj file?
This project also builds on MacOS (which was the original purpose of the port) but does not run, "It was not possible to find any compatible framework version"
So if there is a link to running .Net Core apps on Mac for a non-Mac person, that would be helpful

**Comment by danmosemsft** [comment]
You should be able to have a single project, with 
`<TargetFrameworks>netcoreapp30;net461</TargetFrameworks>`

**Comment by jchang6** [comment]
Visual Studio 2019 does not let me have both in there, but I can do one at a time, which works for me, thanks!

**Comment by jchang6** [comment]
> You should be able to have a single project, with
> <TargetFrameworks>netcoreapp30;net461</TargetFrameworks>

Visual Studio 2019 does not let me have both in there, but I can do one at a time, which works for me, thanks!

**Comment by saucecontrol** [comment]
Make sure you change the `TargetFramework` element to `TargetFrameworks` in the csproj.  Targetframework only allows one, TargetFramework**s** allows many

**Comment by jchang6** [comment]
ok, this works. With both targets, project -> properties, the Target Framework drop box is disabled, but Solution Explorer -> Dependencies shows both .NETCoreApp 3.0 and .NETFramework 4.7.2, build compiles both
