### ISSUE TITLE
API Proposal: Add CopyToAsync methods to write from PipeReader to PipeWriter

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#35513]
https://github.com/dotnet/corefx/issues/27246 adds methods for copying from the PipeReader to a Stream and from a Stream to a PipeWriter but we haven't yet added APIs to copy from a PipeReader to a PipeWriter:

```C#
public abstract class PipeReader
{
      public virtual Task CopyToAsync(PipeWriter writer, CancellationToken cancellationToken = default);
}
```

**Comment by davidfowl** [comment]
cc @terrajobst I'd like to review this one for 3.0 as well.

**Comment by benaadams** [comment]
`int bufferSize` ?

**Comment by davidfowl** [comment]
Hmm, I guess it depends on the implemenation of CopyToAsync, if it just calls WriteAsync then it does whatever internally, but if it calls GetMemory(), Advance it would control the GetMemory() call. Lets remove it for now.

**Comment by terrajobst** [comment]
We can always add the `bufferSize` later if we have to. Let's approave as-is.

**Comment by carlreinke** [comment]
No return type? 😉

**Comment by davidfowl** [comment]
I dunno what you mean 😬
