### ISSUE TITLE
HTTP2: Implement MaxResponseHeadersLength setting

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#35528]

**Comment by rmkerr** [comment]
@geoffkizer do you have any thoughts on when this limit should be enforced? Off the wire? After decoding hpack?

The comprehensive approach would probably be some combination of the two, enforcing both the size off the wire, and checking again later to ensure the headers haven't decompressed to be larger than the maximum.

**Comment by scalablecory** [comment]
I've implemented this to both constrain the encoded string and the decoded string. Waiting for #38324 to get merged before PRing.

**Comment by stephentoub** [comment]
Nice.
