### ISSUE TITLE
System.Diagnostics.PerformanceCounter

### ISSUE THREAD

**Issue by jchang6** [dotnet/corefx#35520]
I am trying to port a dotNet Framework app to Core. On VS 2019 pre3, Core SDK 3.0.100.1081
System.Diagnostics does not have the PerformanceCounterCategory class
any ideas?

**Comment by MarcoRossignoli** [comment]
Are you sure should be here https://github.com/dotnet/corefx/blob/7817a109400b5b22c02ae6667706cda8a7f3d168/src/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs#L17

**Comment by Anipik** [comment]
@jchang6 any other questions ?

**Comment by jkotas** [comment]
You need to add a reference to System.Diagnostics.PerformanceCounter package. It is not reference it by default. We are providing this package to ease migration from .NET Framework. We do not recommend its use for new code.
