### ISSUE TITLE
Add Rune.TryEncodeToUtf8Bytes

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/corefx#35530]
The API `Rune.TryEncodeToUtf8Bytes` (see [source.dot.net](https://source.dot.net/#System.Private.CoreLib/shared/System/Text/Rune.cs,a25810101a4e6140)) is being added to the `System.Runtime` ref assembly to unblock feature work, but this API was never sent through formal review. We should review it.

Here's the API shape:

```cs
namespace System.Text
{
    public readonly partial struct Rune
    {
        // EXISTING APPROVED API - writes as UTF-16
        public bool TryEncode(Span<char> destination, out int charsWritten);

        // NEW PROPOSED API - writes as UTF-8
        public bool TryEncodeToUtf8Bytes(Span<byte> destination, out int bytesWritten);
    }
}
```

In particular we need to figure out how to normalize the `TryEncode` / `TryEncodeToUtf8Bytes` names so that they fit a common pattern. Per our brief review today we said that we're not opposed to suffixing everything with `Utf16` and `Utf8`, especially since we expect that consumers of this particular API will be familiar with UTF-\* representation.

/cc @ahsonkhan @ericstj

**Comment by Wraith2** [comment]
Would it be useful to return `OperationStatus` instead of `bool` so that the method can indicate the reason for failure to the caller? If you're trying to use it with pipelines and you just need to get a bigger buffer it'd be better to retry than fail the entire operations wouldn't it?

**Comment by GrabYourPitchforks** [comment]
The only failure reason would be that the buffer is too small. We could return `OperationStatus`, but it wouldn't buy us much.

**Comment by Wraith2** [comment]
If that's the case and there's some way to determine/calculate how much space will be needed that's fine. 
Can Utf8 encoding of arbitrary bytes not fail?

**Comment by GrabYourPitchforks** [comment]
`Rune` instances have `Utf16SequenceLength` and `Utf8SequenceLength` properties which will tell you the required buffer size.

UTF-8 encoding of arbitrary data can fail, but the `Rune` type does not represent arbitrary data. It represents a well-formed Unicode scalar value. This is validated by `Rune`'s ctors. A well-formed Unicode scalar value will never fail encoding as long as the destination buffer is large enough.

**Comment by Wraith2** [comment]
Great, thanks for the clarification.

**Comment by terrajobst** [comment]
Looks good, minor suggestion from review:

```C#
bool TryEncodeAsUtf8(...);
```

**Comment by GrabYourPitchforks** [comment]
@terrajobst, @bartonjs:

There are existing public APIs named `DecodeUtf16` and `DecodeUtf8`. For consistency where the UTF suffix is provided, should the new APIs instead be named `[Try]EncodeUtf16` and `[Try]EncodeUtf8`? Additionally, since the side effect is that these APIs write to a destination buffer, should they be `[Try]EncodeToUtf16` and `[Try]EncodeToUtf8`?

I don't think we need a formal review on this, but if we can get agreement on the naming here I can quickly update the other PRs.
