### ISSUE TITLE
Process.Handle does not work on Linux like it does on Windows

### ISSUE THREAD

**Issue by hanabi1224** [dotnet/corefx#35544]
When targeting to netcoreapp2.0, below code works fine on windows but not linux,  WaitHandle.WaitAll returns immediately on linux instead of waiting for process to actually exit.  Is this bug or by design?

        static void Main(string[] args)
        {
            Process p;
            if (Environment.OSVersion.Platform == PlatformID.Win32NT)
            {
                p = Process.Start("timeout", "10");
            }
            else
            {
                p = Process.Start("sleep", "10s");
            }

            var waitHandle = new ManualResetEvent(false);
            waitHandle.SetSafeWaitHandle(new SafeWaitHandle(p.Handle, false));
            WaitHandle.WaitAll(new[] { waitHandle });
            if (!p.HasExited)
            {
                throw new Exception("Process wait handle is not working properly");
            }
            else
            {
                Console.WriteLine("success");
            }
        }

**Comment by sunnycase** [comment]
Try `Process.WaitForExit()`.

**Comment by hanabi1224** [comment]
@sunnycase That one works but it's not what I need :(

**Comment by joshfree** [comment]
@jeffschwMSFT
