### ISSUE TITLE
How do I get the same string comparison behaviour on linux as on Windows?

### ISSUE THREAD

**Issue by RobSwDev** [dotnet/corefx#35558]
We're trying to port our .net product to Linux. We've been reasonably successful, but cannot reproduce the string comparison behaviour we had on Windows. 
We are using `CurrentCultureIgnoreCase`, which considers `"ß"` and `"ss"` equal. On Linux, these are considered not equal. 
If we include CompareOptions.IgnoreNonSpace as suggested [here](https://github.com/dotnet/corefx/issues/17052), then `"héllo"` and `"hello"` become equal.

What are our options for getting the same behaviour on both platforms? Is it possible to same behaviour on Linux as Windows behaviour for CurrentCultureIgnoreCase?

**Comment by wfurt** [comment]
cc: @tarekgh

**Comment by tarekgh** [comment]
@RobSwDev the framework usually depends on the underlying OS for the string comparisons. I don't think you can get 100% parity between Windows and Linux. what exactly your scenario here?

**Comment by RobSwDev** [comment]
@tarekgh We develop a .Net calculation engine that has had several releases on Windows. Now we also want to make it available on Linux. Although most of the calculations are numeric, the engine does support some string functions. 

Ideally, if a client takes a calculation and executes it on Windows or Linux, they should get the same results.
So far, we seem to have 2 choices - neither is particularly appealing.
- change behaviour so that results are different from previously released versions (e.g. use CompareOptions.IgnoreNonSpace, or just ordinal string comparison)
- accepting that for some calculations, results will differ between Windows & Linux.

**Comment by tarekgh** [comment]
@RobSwDev thanks for the explanation. 

> the engine does support some string functions.

Is it limited to some words/phrases or you can expect anything? 

Also, would it be OK to enable NonSpace option on both Windows and Linux? this will make the behavior very close on both.

**Comment by RobSwDev** [comment]
@tarekgh 

There are no limitations: clients create their own calculation models, and can theoretically use any strings they like. 

We are considering NonSpace, but one issue is that it changes results compared to previous (Windows only) releases. 

You say "very close" - are there still differences between Windows & Linux even with this option enabled?

**Comment by tarekgh** [comment]
> You say "very close" - are there still differences between Windows & Linux even with this option enabled?

As I mentioned .net core depends on the underlying OS behavior and we know the Windows and ICU not 100% compatible so I expect there could be some other cases but I expect these cases will be corner cases. 

Just wondering, would ordinal comparisons can work in your scenario. this is the only way you can get 100% consistent results between Linux and Windows.

I am closing this issue but feel free to respond back if you have any more questions or requests.

**Comment by moh-hassan** [comment]
I know it's closed, by I faced the same problems in Nunit test which causes the test success in Windows but fail in Linux ( Ubuntu) due to string comparison

I replaced

           StringComparer.CurrentCultureIgnoreCase
To

        StringComparer.OrdinalIgnoreCase
and test pass successfully
[Recommendations for String Usage](https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings#recommendations-for-string-usage)
