### ISSUE TITLE
stackalloc initializer loses value during initialization

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#35550]
Not sure which part of the stack is broken - perhaps I'm missing something obvious but feels like my value should not get lost

```csharp
using System;
using System.Linq;

public class Program
{
  public static void Main()
  {
    byte foo = 8;
    Span<byte> outArray = stackalloc byte[8] { foo, 0, 0, 0, 0, 0, 0, 0 };
    Console.WriteLine(string.Join("", outArray.ToArray().Select(x => x.ToString("X2"))));
  }
}
```

Expected output:

```
0800000000000000
```

Actual output:

```
0000000000000000
```

Seems like repros for length 4-8 (perhaps larger range)

This works as expected:

```csharp
   byte foo = 8;
   Span<byte> outArray = stackalloc byte[3] { foo, 0, 0 };
   Console.WriteLine(string.Join("", outArray.ToArray().Select(x => x.ToString("X2"))));
```

Repros on https://try.dot.net/ also my local box with sdk 2.1.403

Also repros when foo is not on the stack (i.e. a property in the class)

cc: @ahsonkhan @stephentoub

**Comment by saucecontrol** [comment]
Looks like a Roslyn issue.  This:

```C#
public static byte Bar(byte x)
{
    Span<byte> span = stackalloc byte[6] { x, 0, x, 0, x, 0 };
    return span[0];
}
```

compiles to:

```IL
    .method public hidebysig static 
        uint8 Bar (
            uint8 x
        ) cil managed 
    {
        // Method begins at RVA 0x2050
        // Code size 26 (0x1a)
        .maxstack 4
        .locals init (
            [0] valuetype [System.Memory]System.Span`1<uint8>
        )

        IL_0000: ldc.i4.6
        IL_0001: conv.u
        IL_0002: localloc
        IL_0004: dup
        IL_0005: ldc.i4.0
        IL_0006: ldc.i4.6
        IL_0007: initblk
        IL_0009: ldc.i4.6
        IL_000a: newobj instance void valuetype [System.Memory]System.Span`1<uint8>::.ctor(void*, int32)
        IL_000f: stloc.0
        IL_0010: ldloca.s 0
        IL_0012: ldc.i4.0
        IL_0013: call instance !0& valuetype [System.Memory]System.Span`1<uint8>::get_Item(int32)
        IL_0018: ldind.u1
        IL_0019: ret
    } // end of method Bar
```

From what I can tell, if there are no non-0 literals in the initializer and at least 3 0's, `initblock` is emitted, and the other values are ignored (note arg0 doesn't show up anywhere in the IL).  Less than 3 0's or any non-0 literals, and the IL comes out right.  Doesn't matter where the 0's are or how many beyond 3.

**Comment by saucecontrol** [comment]
Addressed in https://github.com/dotnet/roslyn/issues/29092

**Comment by krwq** [comment]
how do i check which version of compiler was used to produce the binary? is there commit hash somewhere there perhaps in the metadata? perhaps we should update roslyn everywhere?

**Comment by ahsonkhan** [comment]
> also my local box with sdk 2.1.403

This issue doesn't exist on latest sdk/.NET Core 3.0.

> how do i check which version of compiler was used to produce the binary? is there commit hash somewhere there perhaps in the metadata? perhaps we should update roslyn everywhere?

cc @jaredpar 

Please move to the appropriate repo/area. There is nothing to fix in regards to System.Memory itself.

**Comment by jaredpar** [comment]
> how do i check which version of compiler was used to produce the binary?

There is no commit hash stored in a compiled binary that would identify the compiler that produced it.

**Comment by krwq** [comment]
im closing then - initially wasn't sure which part of the stack was broken so put it in the middle ground, I've already created dotnet/iot version. Thanks for helping tracking this down!

@jaredpar sounds good - I'll check the csc under the sdk directory to see how far we are
