### ISSUE TITLE
System.IO.Pipelines .NET Framework 4.5 support.

### ISSUE THREAD

**Issue by moien007** [dotnet/corefx#35556]
Currently, I'm using [this](https://www.nuget.org/packages/Unofficial.System.IO.Pipelines.NET45/) package to add System.IO.Pipelines to my .NET 4.5 projects. <br/> Why [System.IO.Pipelines](https://www.nuget.org/packages/System.IO.Pipelines/) package doesn't support .NET 4.5?

**Comment by benaadams** [comment]
Timelines? It was released in 2018 and supports .NET 4.6 released in 2015

**Comment by moien007** [comment]
Would it possible to add .NET 4.5 support in the future?

**Comment by Wraith2** [comment]
4.5 is out of support, 4.5.2 is still supported but if you want to use new features like spans pipelines etc etc you're much better off using the latest desktop framework. I don't think anything else developed in core goes back further than 4.6 so there would need to be a strong case to do so. Is there good reason you can't updare your framework?

**Comment by moien007** [comment]
> 4.5 is out of support, 4.5.2 is still supported but if you want to use new features like spans pipelines etc you're much better off using the latest desktop framework. I don't think anything else developed in core goes back further than 4.6 so there would need to be a strong case to do so. Is there good reason you can't update your framework?

I just mentioned this issue for sake of capability. Fortunately, All operating systems that support .NET 4.5 is able to install .NET Core.

**Comment by anurse** [comment]
Closing as we have no plans to port System.IO.Pipelines to .NET Framework.

**Comment by deniszykov** [comment]
Actually System.IO.Pipelines could target .NET 4.5 instead of current .NET 4.6 with very few changes in code.

**Comment by Wraith2** [comment]
There is still no reason to do so.

**Comment by deniszykov** [comment]
I do not agree. This can be done for consistency. Related packages are targeting .NET 4.5:
System.Threading.Tasks.Extensions (ValueTask)
System.Memory
System.Buffers
System.Runtime.CompilerServices.Unsafe.

In my case, I use these great packages. And System.IO.Pipelinse as drop-in source code (what a shame).
