### ISSUE TITLE
Network build failures in 'official/dotnet/corefx/refs/heads/master' - '20190224.1'

### ISSUE THREAD

**Issue by robertborr** [dotnet/corefx#35569]
@dotnet-mc-bot commented on [Sun Feb 24 2019](https://github.com/dotnet/core-eng/issues/5318)

There were a set of failures during this build. Here is a summary of these:
* https://dnceng.visualstudio.com/internal/_build/results?buildId=105552
  - **Agent:** Hosted Ubuntu 1604 4
  - **Error log:** /__w/1/s/eng/publish.proj(0,0): error : Unable to upload to corefx-tests/4.6.0-preview4.19124.1/Linux.x64/netcoreapp/tests/Unix.AnyCPU.platform/System.IO.Pipes.Tests.zip due to System.Net.Http.HttpRequestException: Connection refu...

@robertborr

---

@robertborr commented on [Mon Feb 25 2019](https://github.com/dotnet/core-eng/issues/5318#issuecomment-467135656)

/__w/1/s/eng/publish.proj(129,5): warning : Connection refused
/__w/1/s/eng/publish.proj(129,5): warning :    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
/__w/1/s/eng/publish.proj(129,5): warning :    at System.Threading.Tasks.ValueTask`1.get_Result()
/__w/1/s/eng/publish.proj(129,5): warning :    at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
/__w/1/s/eng/publish.proj(129,5): warning :    at System.Threading.Tasks.ValueTask`1.get_Result()
/__w/1/s/eng/publish.proj(129,5): warning :    at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
/__w/1/s/eng/publish.proj(129,5): warning :    at System.Threading.Tasks.ValueTask`1.get_Result()
/__w/1/s/eng/publish.proj(129,5): warning :    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
/__w/1/s/eng/publish.proj(129,5): warning :    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
/__w/1/s/eng/publish.proj(129,5): warning :    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
/__w/1/s/eng/publish.proj(129,5): warning :    at Microsoft.DotNet.Build.CloudTestTasks.AzureHelper.RequestWithRetry(TaskLoggingHelper loggingHelper, HttpClient client, Func`1 createRequest, Func`2 validationCallback, Int32 retryCount, Int32 retryDelaySeconds) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/common/AzureHelper.cs:line 240
/__w/1/s/eng/publish.proj(129,5): error : Unable to upload to corefx-tests/4.6.0-preview4.19124.1/Linux.x64/netcoreapp/tests/Unix.AnyCPU.Release/System.IO.Pipes.Tests.zip due to System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
/__w/1/s/eng/publish.proj(129,5): error :    --- End of inner exception stack trace ---
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
/__w/1/s/eng/publish.proj(129,5): error :    at System.Threading.Tasks.ValueTask`1.get_Result()
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
/__w/1/s/eng/publish.proj(129,5): error :    at System.Threading.Tasks.ValueTask`1.get_Result()
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
/__w/1/s/eng/publish.proj(129,5): error :    at System.Threading.Tasks.ValueTask`1.get_Result()
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
/__w/1/s/eng/publish.proj(129,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.BlobFeed.CheckIfBlobExistsAsync(String blobPath) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/BlobFeed.cs:line 51
/__w/1/s/eng/publish.proj(129,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.BlobFeedAction.UploadAssetAsync(ITaskItem item, SemaphoreSlim clientThrottle, Int32 uploadTimeout, PushOptions options) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/BlobFeedAction.cs:line 171.
/__w/1/s/eng/publish.proj(129,5): error : Connection refused
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
/__w/1/s/eng/publish.proj(129,5): error :    at System.Threading.Tasks.ValueTask`1.get_Result()
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
/__w/1/s/eng/publish.proj(129,5): error :    at System.Threading.Tasks.ValueTask`1.get_Result()
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
/__w/1/s/eng/publish.proj(129,5): error :    at System.Threading.Tasks.ValueTask`1.get_Result()
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
/__w/1/s/eng/publish.proj(129,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.BlobFeed.CheckIfBlobExistsAsync(String blobPath) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/BlobFeed.cs:line 51
/__w/1/s/eng/publish.proj(129,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.BlobFeedAction.UploadAssetAsync(ITaskItem item, SemaphoreSlim clientThrottle, Int32 uploadTimeout, PushOptions options) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/BlobFeedAction.cs:line 171
/__w/1/s/eng/publish.proj(129,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.BlobFeedAction.PublishToFlatContainerAsync(IEnumerable`1 taskItems, Int32 maxClients, Int32 uploadTimeoutInMinutes, PushOptions pushOptions) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/BlobFeedAction.cs:line 121
/__w/1/s/eng/publish.proj(129,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.PushToBlobFeed.ExecuteAsync() in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/PushToBlobFeed.cs:line 118
    1 Warning(s)
    2 Error(s)

---

@robertborr commented on [Mon Feb 25 2019](https://github.com/dotnet/core-eng/issues/5318#issuecomment-467194458)

@danmosemsft - moving to corefx repo

**Comment by davidsh** [comment]
This looks like an infrastructure issue.

**Comment by davidsh** [comment]
@wtgodbe

**Comment by wtgodbe** [comment]
@safern have we seen this one before? Do we need to update an access key @MattGal ?

**Comment by MattGal** [comment]
Taking a look now.  Note that storage accounts can refuse connections periodically with valid connection strings / SAS tokens.

**Comment by safern** [comment]
cc: @mikem8361 who wrote this feature. We're uploading to dotnet blob feed using arcade's built-in MSBuild task.

**Comment by MattGal** [comment]
Yeah I filed this issue a week ago when @robertborr showed it to me the previous time, there's just no retry logic in Arcade's homemade, ported-from-buildtools implementation of checking if a blob exists.

https://github.com/dotnet/arcade/pull/2060/files  should fix it, I just didn't merge it because I didn't get a LGTM (hint hint)

**Comment by mikem8361** [comment]
I'll approve it, but I thought you would want someone in the engineering team to do that.

**Comment by MattGal** [comment]
@mikem8361 yup I'm working on that.

**Comment by MattGal** [comment]
Looks like @chcosta wants to do it the proverbial "right way", I'm going to mute this thread now.

**Comment by MattGal** [comment]
#2060 was sufficient but not good enough, filed https://github.com/dotnet/arcade/issues/2118 to track fixing this.

**Comment by wfurt** [comment]
This also looks like environmental problem, not a product bug.

**Comment by MattGal** [comment]
It's not a product bug, it's an infrastructure bug that we don't retry when attempting to check if a blob exists.  Track it via https://github.com/dotnet/arcade/issues/2118 and it should get fixed eventually.
