### ISSUE TITLE
error GC97D5F25: implicit declaration of function 'X509_STORE_CTX_get0_store' is invalid in C99

### ISSUE THREAD

**Issue by robertborr** [dotnet/corefx#35562]
build: https://dnceng.visualstudio.com/internal/_build/results?buildId=104405&view=logs   (logs attached)
RedHat6_x64_Release leg, the following errors occurred:

/__w/1/s/src/Native/Unix/System.Security.Cryptography.Native/pal_x509.c(311,25): error GC97D5F25: implicit declaration of function 'X509_STORE_CTX_get0_store' is invalid in C99 [-Werror,-Wimplicit-function-declaration] [/__w/1/s/src/Native/build-native.proj]
      X509_STORE* store = X509_STORE_CTX_get0_store(ctx);
                          ^
/__w/1/s/src/Native/Unix/System.Security.Cryptography.Native/pal_x509.c(311,17): error G5F2A7227: incompatible integer to pointer conversion initializing 'X509_STORE *' (aka 'struct x509_store_st *') with an expression of type 'int' [-Werror,-Wint-conversion] [/__w/1/s/src/Native/build-native.proj]
      X509_STORE* store = X509_STORE_CTX_get0_store(ctx);
                  ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/__w/1/s/src/Native/Unix/System.Security.Cryptography.Native/pal_x509.c(758,21): error G5F2A7227: incompatible integer to pointer conversion initializing 'X509_STORE *' (aka 'struct x509_store_st *') with an expression of type 'int' [-Werror,-Wint-conversion] [/__w/1/s/src/Native/build-native.proj]
          X509_STORE* store = X509_STORE_CTX_get0_store(storeCtx);
                      ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  3 errors generated.
  make[2]: *** [System.Security.Cryptography.Native/CMakeFiles/objlib.dir/pal_x509.c.o] Error 1
  make[1]: *** [System.Security.Cryptography.Native/CMakeFiles/objlib.dir/all] Error 2
  make: *** [all] Error 2
  Failed to build corefx native components.
/__w/1/s/src/Native/build-native.proj(37,5): error MSB3073: The command ""/__w/1/s/src/Native/build-native.sh" x64 Release Linux outconfig netcoreapp-Linux-Release-x64 stripsymbols" exited with code 1.

Build FAILED.

/__w/1/s/src/Native/Unix/System.Security.Cryptography.Native/pal_x509.c(311,25): error GC97D5F25: implicit declaration of function 'X509_STORE_CTX_get0_store' is invalid in C99 [-Werror,-Wimplicit-function-declaration] [/__w/1/s/src/Native/build-native.proj]
/__w/1/s/src/Native/Unix/System.Security.Cryptography.Native/pal_x509.c(311,17): error G5F2A7227: incompatible integer to pointer conversion initializing 'X509_STORE *' (aka 'struct x509_store_st *') with an expression of type 'int' [-Werror,-Wint-conversion] [/__w/1/s/src/Native/build-native.proj]
/__w/1/s/src/Native/Unix/System.Security.Cryptography.Native/pal_x509.c(758,21): error G5F2A7227: incompatible integer to pointer conversion initializing 'X509_STORE *' (aka 'struct x509_store_st *') with an expression of type 'int' [-Werror,-Wint-conversion] [/__w/1/s/src/Native/build-native.proj]
/__w/1/s/src/Native/build-native.proj(37,5): error MSB3073: The command ""/__w/1/s/src/Native/build-native.sh" x64 Release Linux outconfig netcoreapp-Linux-Release-x64 stripsymbols" exited with code 1.
    0 Warning(s)
    4 Error(s)

**Logfiles, in case the build is deleted:**
[5310-corefx-20190222.5-logs_104405.zip](https://github.com/dotnet/corefx/files/2901676/5310-corefx-20190222.5-logs_104405.zip)

**Comment by robertborr** [comment]
discovered in https://github.com/dotnet/core-eng/issues/5310

FYI: @bartonjs

**Comment by bartonjs** [comment]
Already fixed by https://github.com/dotnet/corefx/pull/35542.
