### ISSUE TITLE
Utf8Formatter returns the wrong result for double/float when using the currency format

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#35566]
The `Utf8Formatter.TryFormat(double value, Span<byte> destination, out int bytesWritten, StandardFormat format = default(StandardFormat))` code currently returns an incorrect value for `StandardFormat.Parse("C")`.

This failure is because `TryFormatFloatingPoint` currently assumes the string returned only contains ASCII data: https://source.dot.net/#System.Private.CoreLib/shared/System/Buffers/Text/Utf8Formatter/Utf8Formatter.Float.cs,110

This assumption is generally correct, except for the currency format when the invariant currency symbol is `¤` (`U+00A4` - Currency Sign).

**Comment by tannergooding** [comment]
This was introduced in https://github.com/dotnet/coreclr/pull/22434

**Comment by tannergooding** [comment]
CC. @stephentoub, @GrabYourPitchforks, @ahsonkhan

**Comment by GrabYourPitchforks** [comment]
Good catch. There are span-based APIs for transcoding on the `Encoding` class.

```cs
int bytesRequired = Encoding.UTF8.GetByteCount(inputUtf16Span);
if (destUtf8Span.Length < bytesRequired) { /* FAIL */ }
int actualBytesWritten = Encoding.UTF8.GetBytes(inputUtf16Span, destUtf8Span);
Debug.Assert(bytesRequired == actualBytesWritten);
```

**Comment by stephentoub** [comment]
Because Utf8Formatter always uses invariant, this will always happen with 'C', right?  If so, it seems like we could either:
a) Simply put back a guard that checks if the format is 'C' and throws.
b) Replace the currency symbol with something else by, for example, passing a NumberFormatInfo to the float/double.TryFormat that's something like InvariantCulture but with a different symbol that's ASCII.
c) Do the post-processing @GrabYourPitchforks suggests.

**Comment by tannergooding** [comment]
> Because Utf8Formatter always uses invariant, this will always happen with 'C', right

Correct.

> Do the post-processing @GrabYourPitchforks suggests (but presumably only if 'C')

I think this is the best option. I don't think we should prevent the UTF8Formatter from supporting any format specifiers as it is needlessly hindering functionality that may be desirable.

**Comment by tannergooding** [comment]
Resolved with https://github.com/dotnet/corefx/pull/35899
