### ISSUE TITLE
Add missing feature detection properties to DbProviderFactory

### ISSUE THREAD

**Issue by roji** [dotnet/corefx#35564]
Following up on #35535, we should add feature detection properties on DbProviderFactory for features which are optional, similar to the existing `CanCreateDataSourceEnumerator`. This would include:

```c#
class DbProviderFactory
{
    public virtual bool CanCreateDataAdapter { get; }
    public virtual bool CanCreateCommandBuilder { get; }
}
```

The default implementation would call the corresponding Create method and check if the result is null or not.

/cc @divega @ajcvickers @bricelam

**Comment by divega** [comment]
Assigning to @roji on 3.0 milestone.
