### ISSUE TITLE
Remove some unnecessary HWIntrinsic API overloads

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#35560]
There are currently several HWIntrinsic API overloads exposed that are largely unnecessary. These APIs could be removed and have the same functionality be supported internally by the JIT, as is done with the majority of the other HWIntrinsic APIs.

### InsertVector128

These APIs were exposed to have them mirror the `ExtractVector128` APIs. However, in practice, they make the APIs harder to consume and more difficult to support in the JIT. These APIs would instead be supported by the JIT supporting containment on the second operand via the overload that takes `Vector128<T> data`.

```diff
namespace System.Runtime.Intrinsics.X86
{
    public abstract partial class Avx
    {
-        public static unsafe Vector256<sbyte> InsertVector128(Vector256<sbyte> value, sbyte* address, byte index);
-        public static unsafe Vector256<byte> InsertVector128(Vector256<byte> value, byte* address, byte index);
-        public static unsafe Vector256<short> InsertVector128(Vector256<short> value, short* address, byte index);
-        public static unsafe Vector256<ushort> InsertVector128(Vector256<ushort> value, ushort* address, byte index);
-        public static unsafe Vector256<int> InsertVector128(Vector256<int> value, int* address, byte index);
-        public static unsafe Vector256<uint> InsertVector128(Vector256<uint> value, uint* address, byte index);
-        public static unsafe Vector256<long> InsertVector128(Vector256<long> value, long* address, byte index);
-        public static unsafe Vector256<ulong> InsertVector128(Vector256<ulong> value, ulong* address, byte index);
-        public static unsafe Vector256<float> InsertVector128(Vector256<float> value, float* address, byte index);
-        public static unsafe Vector256<double> InsertVector128(Vector256<double> value, double* address, byte index);
    }

    public abstract partial class Avx2
    {
-        public new static unsafe Vector256<sbyte> InsertVector128(Vector256<sbyte> value, sbyte* address, byte index);
-        public new static unsafe Vector256<byte> InsertVector128(Vector256<byte> value, byte* address, byte index);
-        public new static unsafe Vector256<short> InsertVector128(Vector256<short> value, short* address, byte index);
-        public new static unsafe Vector256<ushort> InsertVector128(Vector256<ushort> value, ushort* address, byte index);
-        public new static unsafe Vector256<int> InsertVector128(Vector256<int> value, int* address, byte index);
-        public new static unsafe Vector256<uint> InsertVector128(Vector256<uint> value, uint* address, byte index);
-        public new static unsafe Vector256<long> InsertVector128(Vector256<long> value, long* address, byte index);
-        public new static unsafe Vector256<ulong> InsertVector128(Vector256<ulong> value, ulong* address, byte index);
    }
}
```

### ExtractVector128

These APIs were exposed because of percieved difficulty in efficiently supporting containment for `Store(address, ExtractVector128(...))`. The split API makes these harder to consume and supporting containment for stores (at a basic level) looks to be fairly simple (prototype here: https://github.com/mikedn/coreclr/commit/a00b42e9442ceeeacda7981bbb462bb8ec7a8a21).

```diff
namespace System.Runtime.Intrinsics.X86
{
    public abstract partial class Avx
    {
-        public static unsafe void ExtractVector128(byte* address, Vector256<byte> value, byte index);
-        public static unsafe void ExtractVector128(sbyte* address, Vector256<sbyte> value, byte index);
-        public static unsafe void ExtractVector128(short* address, Vector256<short> value, byte index);
-        public static unsafe void ExtractVector128(ushort* address, Vector256<ushort> value, byte index);
-        public static unsafe void ExtractVector128(int* address, Vector256<int> value, byte index);
-        public static unsafe void ExtractVector128(uint* address, Vector256<uint> value, byte index);
-        public static unsafe void ExtractVector128(long* address, Vector256<long> value, byte index);
-        public static unsafe void ExtractVector128(ulong* address, Vector256<ulong> value, byte index);
-        public static unsafe void ExtractVector128(float* address, Vector256<float> value, byte index);
-        public static unsafe void ExtractVector128(double* address, Vector256<double> value, byte index);
    }

    public abstract partial class Avx2
    {
-        public new static unsafe void ExtractVector128(byte* address, Vector256<byte> value, byte index);
-        public new static unsafe void ExtractVector128(sbyte* address, Vector256<sbyte> value, byte index);
-        public new static unsafe void ExtractVector128(short* address, Vector256<short> value, byte index);
-        public new static unsafe void ExtractVector128(ushort* address, Vector256<ushort> value, byte index);
-        public new static unsafe void ExtractVector128(int* address, Vector256<int> value, byte index);
-        public new static unsafe void ExtractVector128(uint* address, Vector256<uint> value, byte index);
-        public new static unsafe void ExtractVector128(long* address, Vector256<long> value, byte index);
-        public new static unsafe void ExtractVector128(ulong* address, Vector256<ulong> value, byte index);
    }
}
```

**Comment by tannergooding** [comment]
This came about from a discussion on https://github.com/dotnet/coreclr/issues/22815.

CC. @mikedn, @fiigii, @CarolEidt

**Comment by tannergooding** [comment]
It is worth noting that, for `BroadcastScalarToVector` that deal with `float`/`double`,  the overloads that take `float*` and `double*` still exist in AVX. This is because `VBROADCAST reg, mem` was introduced in AVX and `VBROADCAST reg, reg` was introduced in AVX2. Having separate overloads also matches what native does, in that they expose `* __m128 _mm_broadcast_ss(float *a);` for AVX and `* __m128 _mm_broadcastss_ps(__m128 a);` for AVX2

**Comment by tannergooding** [comment]
Taking this would leave the following APIs that do an explicit load or store: [load_store.txt](https://github.com/dotnet/corefx/files/2901480/load_store.txt)

**Comment by mikedn** [comment]
I think things are pretty clear with Insert/Extract.

I'm not sure about broadcast, if we need to keep the memory overloads for `float`/`double` then we probably don't save anything in terms of JIT complexity. So perhaps we should just keep all overloads?

Keep in mind that if we still want to be able to generate memory forms of integer broadcasts we'll need to do it in the JIT by combing the register form of broadcast with something like `Create(int)`. So it's some extra work.

**Comment by tannergooding** [comment]
> Keep in mind that if we still want to be able to generate memory forms of integer broadcasts we'll need to do it in the JIT by combing the register form of broadcast with something like `Create(int)`. So it's some extra work.

Why would we need to do that rather than just supporting containment for `Avx2.BroadcastScalarToVector128(Sse2.LoadScalarVector128(address))`?

**Comment by fiigii** [comment]
Folding `Create` into `BroadcastScalarToVector128` requires the first step of https://github.com/dotnet/coreclr/issues/22388, I will make it in this week. Sorry for the delay.

> supporting containment for `Avx2.BroadcastScalarToVector128(Sse2.LoadScalarVector128(address))`?

I think we should support it.

**Comment by CarolEidt** [comment]
The proposal makes sense to me, though I would agree with @mikedn that if we need to keep some of the memory overloads for broadcast then we might as well keep them all.

**Comment by mikedn** [comment]
> Why would we need to do that rather than just supporting containment for Avx2.BroadcastScalarToVector128(Sse2.LoadScalarVector128(address))?

That does not seem to be the same as `Create`. At the first glance `LoadScalar` supports only some integer types. Am I missing some overloads?

**Comment by tannergooding** [comment]
> At the first glance `LoadScalar` supports only some integer types. Am I missing some overloads?

Ah, right. You aren't missing any overloads, there is only `MOVD` which always reads 4-bytes, so we don't have `LoadScalar(byte*)`. We would have to support it via `CreateScalar(byte)`.

> then we might as well keep them all.

I think I would be okay with this if we also supported containment on the overloads that take a vector (rather than an address). We currently have these marked as `NoContainment` and it means that we have "worse" codegen in places where the JIT stack-spills or the user writing code that would cause an implicit read from memory.

**Comment by tannergooding** [comment]
I've removed the removal of the broadcast APIs and marked this ready for review.

**Comment by tannergooding** [comment]
I'll have the PR up removing these shortly.
