### ISSUE TITLE
Enable testing for System.IO.Ports package

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#35599]
Related:
- https://github.com/dotnet/corefx/issues/35358
- https://github.com/dotnet/corefx/issues/33374

When creating a package for native (https://github.com/dotnet/corefx/pull/35126) I have disabled package testing because of some infrastructure issues (build require that a package was already on nuget before it was uploaded) - this should be possible to re-enable now.

**Comment by ericstj** [comment]
We can do this now by downgrading the native package versions and restoring them from the feed (eg: the last corefx build)

**Comment by krwq** [comment]
will take a look whenever got time
