### ISSUE TITLE
Should GenAPI be removing the DebuggerDisplay and DebuggerStepThrough attributes?

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#35601]
Currently the automatic generation of reference assemblies excludes some of the Debugger* attributes:
https://github.com/dotnet/corefx/blob/7c37cfbd03d058b966160fdc39cd902ef3b2782c/eng/DefaultGenApiDocIds.txt#L12-L17

This is relevant to Xml.ReaderWriter:
https://github.com/dotnet/corefx/blob/7c37cfbd03d058b966160fdc39cd902ef3b2782c/src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs#L528
https://github.com/dotnet/corefx/blob/7c37cfbd03d058b966160fdc39cd902ef3b2782c/src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs#L815

Should we be emitting these or retain them?

For context: https://github.com/dotnet/corefx/pull/35557#discussion_r259776563

cc @ericstj, @krwq

**Comment by jkotas** [comment]
It should be fine to remove these. There are not relevant for the compilers.

**Comment by ericstj** [comment]
Thanks!
