### ISSUE TITLE
Should GenAPI be removing the ComVisible attribute?

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#35608]
Example usages: https://github.com/dotnet/corefx/blob/77cde697f9ee9941bdc76e02b9481d781790e86a/src/System.Security.Principal.Windows/ref/System.Security.Principal.Windows.cs#L321-L322
https://github.com/dotnet/corefx/blob/77cde697f9ee9941bdc76e02b9481d781790e86a/src/System.Diagnostics.EventLog/ref/System.Diagnostics.EventLog.cs#L164-L165

Excluded here: https://github.com/dotnet/corefx/blob/77cde697f9ee9941bdc76e02b9481d781790e86a/eng/DefaultGenApiDocIds.txt#L28

Should we be emitting these or retain them?

cc @bartonjs, @vancem

**Comment by ericstj** [comment]
@AaronRobinsonMSFT this is similar to https://github.com/dotnet/corefx/issues/35610.  Can you let us know if the same conclusion applies?

**Comment by AaronRobinsonMSFT** [comment]
@ericstj Same conclusion. Thanks.

**Comment by tannergooding** [comment]
Can't this be used (and was used on full framework) to generate interop libraries?

I think, in general, attributes from `System.Runtime.CompilerServices` and `System.Runtime.InteropServices` should be kept; as they are used heavily by existing tools.

**Comment by ericstj** [comment]
Suppose we bring it back, how do you suppose we treat the types of changes that were made in .NETCore that removed COMVisibility of runtime types?  /cc @jkotas 

Do we say "no" to those types of changes moving forward since that changes public surface area?

**Comment by jkotas** [comment]
The reference assemblies are meant to capture only stuff relevant to managed compilers. COM visibility is not relevant to managed compilers, thus it does not make sense to capture COM visibility in reference assemblies.

**Comment by jkotas** [comment]
>  attributes from System.Runtime.CompilerServices and System.Runtime.InteropServices should be kept; as they are used heavily by existing tools.

Examples?
