### ISSUE TITLE
GetHashCode seems to only use the first field of a struct to calculate hash code

### ISSUE THREAD

**Issue by miguep** [dotnet/corefx#35613]
With a struct like this:
```csharp
    struct MyStruct
        {
            public float a,b;
        };
```
if I try the following:

```csharp
            MyStruct myStruct1 = new MyStruct { b= 1.0f, a = 2.0f};
            MyStruct myStruct2 = new MyStruct { b= 1.0f, a = 1.0f};

            int hash = myStruct1.GetHashCode();
            int hash2 = myStruct2.GetHashCode();
```
hash and hash2 are different, but trying this:

```csharp
            MyStruct myStruct1 = new MyStruct { a= 1.0f, b = 2.0f};
            MyStruct myStruct2 = new MyStruct { a= 1.0f, b = 1.0f};

            int hash = myStruct1.GetHashCode();
            int hash2 = myStruct2.GetHashCode();
```
hash and hash2 are the same.

This behavior is different from the one in .NET Framework

**Comment by danmosemsft** [comment]
@jkotas was this an intentional change? I suppose some line may have to be drawn otherwise computing a hash for a struct could be arbitrarily expensive.

**Comment by jkotas** [comment]
Yes, this is side-effect of using functionally correct hash algorithm for float/double: https://github.com/dotnet/coreclr/pull/13164/files#diff-ca326b8cd58d6642f56aa054c221c22aR2717

**Comment by jkotas** [comment]
> some line may have to be drawn otherwise computing a hash for a struct could be arbitrarily expensive.

Right, the built-in hash algorithm for structs has number of trade offs, and it is pretty slow too. It is best to always implement `GetHashCode` on structs explicitly.
