### ISSUE TITLE
add span support to MemoryMappedFiles

### ISSUE THREAD

**Issue by m5x** [dotnet/corefx#35614]
`Span<T>` wave seems to have missed `System.IO.MemoryMappedFiles`. Is there some particular blocker for this? There are many scenarios in which it would be very useful to be able to access mapped memory as `Span<T>`.

**Comment by stephentoub** [comment]
What API specifically? Does this end up being different from https://github.com/dotnet/corefx/issues/33279?

**Comment by m5x** [comment]
It doesn't. Didn't know about that one. Closing this issue.
