### ISSUE TITLE
Should GenAPI be removing the InterfaceType attribute?

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#35610]
Example usage: https://github.com/dotnet/corefx/blob/23c06516a29ac94585cee09e82b5ddf57d0cae0e/src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs#L1241-L1242

Excluded here: https://github.com/dotnet/corefx/blob/23c06516a29ac94585cee09e82b5ddf57d0cae0e/eng/DefaultGenApiDocIds.txt#L30

Should we be emitting these or retain them?

cc @AaronRobinsonMSFT, @jkoritzinsky

**Comment by AaronRobinsonMSFT** [comment]
I am not ready to remove this interface at the moment. Removing these attributes could cause many issues downstream and the full consequences I fear aren't even fully understood. I would leave as is for the foreseeable future.

**Comment by AaronRobinsonMSFT** [comment]
Okay, let try this again. I don't fully understand how the ref assemblies are used by developers. If they are only for building and never a runtime component, then sure we can remove these attributes as they have no purpose during compile time, otherwise we should keep them.

**Comment by ericstj** [comment]
Closing per:

> they are only for building and never a runtime component, then sure we can remove these attribute

**Comment by tannergooding** [comment]
These attributes can be used at compile time by analyzers.

**Comment by ericstj** [comment]
Analyzers can look at anything, including method bodies if they really want to, but that doesn't mean we should preserve everything.  We need to have a non-hypothetical scenario for adding them.

**Comment by tannergooding** [comment]
This attribute can be used by an analyzer to help ensure you declare your COM interop interfaces correctly. Inheriting COM interfaces is peculiar because of how you need to redeclare all methods defined in the base interface and needing to match the signatures.

I've used this attribute in my own analyzers to help this before.

**Comment by ericstj** [comment]
That's fair.  Do you expect it would limit our ability to make changes in the future?

**Comment by ericstj** [comment]
Ping: do you imagine adding this attribute to our reference assemblies will constrain API design in the future?

**Comment by AaronRobinsonMSFT** [comment]
@ericstj  Nope. I don't see any reason these can't be kept if analyzers have a need.

**Comment by ericstj** [comment]
Ok. Will remove suppression
