### ISSUE TITLE
Process.MaxWorkingSet should read from /sys/fs/cgroup/memory when available

### ISSUE THREAD

**Issue by richlander** [dotnet/corefx#35638]
I am playing with the Process.MaxWorkingSet API. I am getting results that I don't expect. Should the values be so different in Linux containers? Is that some container-ism or something wrong with our Linux PAL?

```console
C:\testapps\workingset>dotnet run
Hello World!
MinWorkingSet: 204800
WorkingSet64: 15110144
MaxWorkingSet: 1413120

C:\testapps\workingset>docker run --rm -v C:\testapps\workingset:/app -w /app microsoft/dotnet:3.0-sdk dotnet run
Hello World!
MinWorkingSet: 0
WorkingSet64: 23556096
MaxWorkingSet: 9223372036854775807

C:\testapps\workingset>docker run --rm -m 60m -v C:\testapps\workingset:/app -w /app microsoft/dotnet:3.0-sdk dotnet run
Hello World!
MinWorkingSet: 0
WorkingSet64: 23568384
MaxWorkingSet: 9223372036854775807

C:\testapps\workingset>docker run --rm microsoft/dotnet:3.0-sdk uname -a
Linux b1a8742108c0 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 GNU/Linux

C:\testapps\workingset>docker run --rm -m 60m -v C:\testapps\workingset:/app -w /app microsoft/dotnet:3.0-sdk-alpine dotnet run
Hello World!
MinWorkingSet: 0
WorkingSet64: 25010176
MaxWorkingSet: 9223372036854775807

C:\testapps\workingset>docker run --rm -m 60m microsoft/dotnet:3.0-sdk-alpine cat /sys/fs/cgroup/memory/memory.limit_in_bytes
62914560

C:\testapps\workingset>docker run --rm microsoft/dotnet:3.0-sdk-alpine uname -a
Linux 0ba6cfe799f1 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 Linux

C:\testapps\workingset>type Program.cs
∩╗┐using System;
using System.Diagnostics;

namespace workingset
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Console.WriteLine($"MinWorkingSet: {Process.GetCurrentProcess().MinWorkingSet}");
            Console.WriteLine($"WorkingSet64: {Process.GetCurrentProcess().WorkingSet64}");
            Console.WriteLine($"MaxWorkingSet: {Process.GetCurrentProcess().MaxWorkingSet}");
        }
    }
}

C:\testapps\workingset>
```

**Comment by stephentoub** [comment]
What do you see if you change your program to be:
```C#
static void Main() => Console.WriteLine(File.ReadAllText("/proc/self/status");
```

**Comment by richlander** [comment]
Just discovered this. It seems important.

```console
C:\testapps\workingset>docker run --rm microsoft/dotnet:3.0-sdk-alpine cat /sys/fs/cgroup/memory/memory.limit_in_bytes
9223372036854771712

C:\testapps\workingset>docker run --rm -m 60m microsoft/dotnet:3.0-sdk-alpine cat /sys/fs/cgroup/memory/memory.limit_in_bytes
62914560
```

**Comment by stephentoub** [comment]
> It seems important.

What specifically?  Without specifying the 60 MB limit, docker allows the app as much memory / swap memory as it wants.

**Comment by danmosemsft** [comment]
It is getting it from proc/PID/stat, 25th field, `rsslim`. Here it is dumping the raw value as well:

```
c:\d\preview3\2>docker run --rm -v c:\d\preview3\2:/app -w /app microsoft/dotnet:3.0-sdk dotnet run -r linux-x64
Hello World!
MinWorkingSet: 0
WorkingSet64: 23515136
MaxWorkingSet: 9223372036854775807
raw stat: 18446744073709551615
```
Note the raw value is UInt64.MaxValue. This is an unsigned long, and we're reading it as such, but because the API was originally defined to return `IntPtr`, we are explicitly clipping the value to Int64.MaxValue and that's what we return. 

Running outside of docker, in WSL, I get the same :
```
dan@danmose3:~$ cat /proc/$$/stat | awk -F " " '{print $25}'
18446744073709551615
```

It looks like this is `RLIM_INFINITY` ie., there is no soft limit. Same for hard limit:
```
dan@danmose3:~$ cat /proc/$$/limits
Limit                     Soft Limit           Hard Limit           Units
...
Max resident set          unlimited            unlimited            bytes
```

Whether there is a more appropriate value than `rsslimit` to use for `MaxWorkingSet` I do not know. @janvorli ?

**Comment by richlander** [comment]
I just meant that this mechanism reports the values I expect.

Results you asked for: https://gist.github.com/richlander/abc3e69b76b02d4103f5c0766be6d1d3

**Comment by danmosemsft** [comment]
It looks like this crossed with @stephentoub comment. I agree it seems it is the correct value - there is no limit.

**Comment by richlander** [comment]
There is no limit according to that API. My view is that our APIs should be cgroup-friendly. These ones don't seem to be.

JFYI: we should be using .NET Core nightly docker images. This is what that looks like:

```console
docker run --rm -m 60m -v C:\testapps\workingset:/app -w /app mcr.microsoft.com/dotnet/core-nightly/sdk:3.0-alpine dotnet run
```

**Comment by stephentoub** [comment]
> My view is that our APIs should be cgroup-friendly. These ones don't seem to be.

From where do you recommend we get the maximum working set value?  This is what the OS is reporting to us via /proc.

**Comment by janvorli** [comment]
I agree with @richlander that we should be getting the limit from cgroups instead of /proc/self/stat, as the latter is container agnostic and always provides limits for the whole system.

**Comment by stephentoub** [comment]
> I agree with @richlander that we should be getting the limit from cgroups instead of /proc/self/stat, as the latter is container agnostic and always provides limits for the whole system.

/sys/fs/cgroup isn't always available.  Your recommendation is to try to read it from there, and if we can't, fall back to /proc?

**Comment by janvorli** [comment]
We can fall back either to that or the value we get from getrlimit api, like we do in coreclr pal:
https://github.com/dotnet/coreclr/blob/master/src/pal/src/misc/cgroup.cpp#L385-L428

**Comment by stephentoub** [comment]
Ok, sounds reasonable.

**Comment by richlander** [comment]
Who should take this on?

**Comment by stephentoub** [comment]
> Who should take this on?

Normally I'd say this doesn't seem particularly high priority and it should be handled like any other filed issue.  But since I'm already here and it'll take five minutes, I'll just do it now.

**Comment by richlander** [comment]
Thanks much. The missing context is that we have an important scenario we're enabling which is "support for cgroups and docker-limits". That's what this is oriented on: https://github.com/dotnet/designs/pull/49. Certainly, that design doesn't talk to this at all. However, this issue is the first thing I found wanting to validate the GC change. It makes sense to improve the near neighbors. Any other ideas on similar changes we should consider for better cgroups support?

**Comment by stephentoub** [comment]
@richlander, I merged a change that should address this.  Can you try your scenario again with bits from master?
