### ISSUE TITLE
HTTP2: Improve handling of status code pseudo-header

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#35642]
Currently, we will happily receive 0, 1, or more status codes on a response. We should require exactly 1.

Also, we will happily accept a status code header that comes after regular headers. Again, we should disallow this. The status code must be the first header received.

Reference: https://tools.ietf.org/html/rfc7540#section-8.1.2

**Comment by wfurt** [comment]
fixed by #37069
