### ISSUE TITLE
HTTP2: Deal with client-initiated stream abort

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#35652]
Currently, there is a TODO in the code to track this:
https://github.com/dotnet/corefx/blob/694eeba312046e2097c731d40f32c1cac675aa03/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs#L358

The TODO references #31310, but this is really a more general issue, and unfortunately rather complex, so I'm filing a separate issue to track this.

Client-initiated abort can happen for several reasons: 
(a) User-initiated cancellation
(b) Exception from the request stream when sending the request body
(c) User disposes the response body before reading to the end
(d) Certain cases where we receive invalid data on the stream, such as a bad HEADERS frame, or out-of-order frames (DATA before HEADERS, etc), or the response window is exceeded, etc. We can handle these errors without killing the connection, by simply aborting the invalid stream. That said, all of these are invalid server behavior and so it also seems reasonable to treat them as connection errors and just kill the connection; these should never be hit in normal operation anyway. But the RFC seems to prefer to treat these as stream errors instead of connection errors, generally speaking. See:

https://tools.ietf.org/html/rfc7540#section-5.4.2
"A stream error is an error related to a specific stream that does not
   affect processing of other streams.

   An endpoint that detects a stream error sends a RST_STREAM frame
   (Section 6.4) that contains the stream identifier of the stream where
   the error occurred.  The RST_STREAM frame includes an error code that
   indicates the type of error."

Currently, we don't do any of this; we just propagate the exception to the user and leave the Http2Stream object in the connection's stream dictionary. That's obviously incorrect.

In these cases, we should first send a RST_STREAM to abort the stream. We also need to remove the stream from the connection's stream dictionary. But if we just naively do this today, it will cause problems. There may be frames on this stream in flight from the server, and we can't treat these as connection errors, as we do for a stream that completed normally.

The RFC says:
"A RST_STREAM is the last frame that an endpoint can send on a stream.
   The peer that sends the RST_STREAM frame MUST be prepared to receive
   any frames that were sent or enqueued for sending by the remote peer.
   These frames can be ignored, except where they modify connection
   state (such as the state maintained for header compression
   (Section 4.3) or flow control).

   Normally, an endpoint SHOULD NOT send more than one RST_STREAM frame
   for any stream.  However, an endpoint MAY send additional RST_STREAM
   frames if it receives frames on a closed stream after more than a
   round-trip time.  This behavior is permitted to deal with misbehaving
   implementations."

So, we need to ignore frames we receive on a stream that the client has aborted. Except that we also need to process these streams to update header decoder state, and flow control state on the connection. This seems to imply we need to do one of the following:

(a) Track client-aborted streams in the stream dictionary, so we can distinguish between actual completed streams and client-aborted streams, and handle them differently. We don't want to have to track these forever, so we would probably also need some scavenge logic that removes these at some point. As long as the scavenge delay is not small, say a couple seconds, this seems reasonable to do.
(b) Just remove client-aborted streams from the stream dictionary immediately, as if they were completed successfully. But also, any frames on closed streams must now be discarded (after being processed for header compression and connection-level flow control) instead of causing connection errors.

I'm leaning toward (b), since this seems simpler and also seems to match the behavior of WinHTTP, as I understand it.

cc @rmkerr @stephentoub

**Comment by rmkerr** [comment]
I agree that (b) is the right approach. I don't think that the additional complexity associated with tracking cancelled or aborted streams is worth the minor improvement in spec compliance.

**Comment by rmkerr** [comment]
The only thing I have to add is that we may want some additional state indicating _how_ the abort was initiated so that we can make sure to send the right error code along with any RST_STREAM frames.

**Comment by karelz** [comment]
@geoffkizer can you please help us figure out what is needed here? Thanks!

**Comment by geoffkizer** [comment]
I think much of this is addressed by the changes in #36884. In particular, I believe we should now be sending RST_STREAM on client abort in the cases listed above.

We should add tests for these cases to confirm.

There's also this part:

> Just remove client-aborted streams from the stream dictionary immediately, as if they were completed successfully. But also, any frames on closed streams must now be discarded (after being processed for header compression and connection-level flow control) instead of causing connection errors.

With #36884, we should be removing these streams from the dictionary immediately. However, I'm unclear whether we need to do something further to discard frames on closed streams. I will follow up here.

**Comment by wfurt** [comment]
do you envision any more work here @geoffkizer ?
Perhaps it is time to close this one and track any remaining work as more specific issues. (like we did recently)

**Comment by geoffkizer** [comment]
Do we have tests for all of the cases listed above? If not, we at least need issues to track missing tests.

**Comment by wfurt** [comment]
I'll take a look and make inventory.

**Comment by karelz** [comment]
@wfurt what is left on this issue? Is it just missing tests? Or is there suspicion that there is a bug fix?

**Comment by wfurt** [comment]
I think we have plenty tests for (a). This is area actively worked on and #39019 will bring over more old tests.

(b) should be covered by SendAsync_ConcurentSendReceive_Fail.

(c) had weakest coverage with partial coverage.    #39471 add more fixes and tests in this area. I'm not sure if we need more, but we can clone or update Http2_PendingSend_SendsReset() to Dispose stream instead of canceling and than sending another request to make sure connection is still usable. 

I think we have coverage for (d). Not necessarily for every specific error but the code handling it is in SendRequest() so it should catch all low-level exceptions.

**Comment by wfurt** [comment]
I think we have enough coverage as well as some active work in this area. If found more missing parts, we should open more specific issue. 

cc: @stephentoub

**Comment by stephentoub** [comment]
This issue was closed, but there's still a TODO for it in the code:
https://github.com/dotnet/corefx/blob/8b5eb8d9fb7857e5b40e763287f8f8832c15af31/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs#L728
@geoffkizer, are your other work items covering addressing that?

**Comment by geoffkizer** [comment]
> @geoffkizer, are your other work items covering addressing that? Or is that already done?

Working on it.
