### ISSUE TITLE
Question Regarding X509Certificate2, SslStream, and EphemeralKeySet

### ISSUE THREAD

**Issue by masterwok** [dotnet/corefx#35663]
Hello,

I have a few questions regarding _X509Certificate2_ and _EphemeralKeySet_. I'm attempting to use _SslStream_ with an _X509CertificateCollection_ in an application deployed to IIS. 

The discrepancy between the application functioning as expected on my local machine versus when it's deployed seem to stem from the lack of a user profile.

The IIS instance doesn't have "Load User Profile" enabled and I'm hesitant to enable this feature due to unknown side-effects doing so might have (as this application is quite large with a lot of hands in it).

Because of this, I started to look into using an _EphemeralKeySet_ to load the key into memory. However, this doesn't appear to work with SslStream according to [#24454](https://github.com/dotnet/corefx/issues/24454).

I've also tried, and failed, to use _MachineKeySet_ which after some research appears to be due to access issues (I don't have access to the IIS server as that's handled by another team).

I've seem to have hit a wall as to how I can get this feature working.

Are there any workarounds for this issue? 

Any help would be greatly appreciated. Thank you!

**Comment by davidsh** [comment]
@bartonjs

**Comment by bartonjs** [comment]
* EphemeralKeySet and SslStream is a known problem (#24454)
* MachineKeySet (explicit or implicit) requires admin rights (by virtue of the fact that you're altering machine-wide state)
* UserKeySet (explicit or implicit) requires the user profile to be loaded.

Of those, the only one that really sounds like it's in your control is to load the user profile.  (I mean, if you wanted to jump in and help debug the EphemeralKeySet/SslStream problem, that'd be great... but I assume that wasn't what you were asking :smile:)

**Comment by masterwok** [comment]
I see, thanks for confirming. While fixing the EphemeralKeySet/SslStream sounds like an interesting problem, I'll probably have to pass this time haha Best of luck though!
