### ISSUE TITLE
Developer Workflow Changes

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#35661]
With multiple changes that went into master in the last weeks we addressed some long standing issues related to our **developer workflow**. With the move to arcade (a common build infrastructure and SDK) we were able to streamline and move a lot of our infrastructure upstream so that other repositories can consume it. 
One of the things that we didn't attempt to unify in the initial move was the command line experience. Gladly we had time to so now and also updated all our docs to outline the new commands.

Some of the actions and options in the build scripts (`build.cmd`, `build.sh`) changed. To get a summary of the new changes, type `build.cmd/sh -help` (see the output at the end of the announcement). _Note that on Unix you can use both the single and double hyphen syntax._

## Changes
- **build -test does not automatically build the tests anymore. You want to add the -buildtests switch if you need to build the tests.**

- Chaining actions is now possible which means that multiple build script invocations aren't necessary anymore for building and testing. Breaking change: `-restore` and `-build` are only implicit if no actions are passed in.

- Running tests without building them in the same command is now possible (test assemblies must be built before of course)

- Different actions for running different type of tests: `-test`, `-integrationTest`, `performanceTest`.

- Clean scripts replaced with a clean action in the build script. (Re-)Building after clean does not require re-fetching the local dotnet installation anymore.

- Add a help description that explains all actions and options.

## Scenarios

| Name | Command | Scenario |
|---|---|---|
| Restore and build sources | build(-restore -build) | _Default / after clone / clean build_
| Restore | build -restore | _Airplane mode_
| Build different frameworks | build -f/-framework netfx/uap/uapaot |
| Build for a specific configuration | build -c/-configuration Debug/Release | _-debug/-release are removed_
| Full run | build -restore -build -buildtests -test | _God mode_
| Rebuild | build -rebuild | _Clean bin and obj and build_
| Build and run unit tests | build -buildtests -test | _Requires sources be built first_
| Build tests | build -buildtests
| Run performance tests | build -performanceTest | _Perf analysis_
| Clean | build -clean | _Back to start_

## CLI help

```
C:\git\corefx>.\build.cmd -h
Common settings:
  -framework              Build framework: netcoreapp, netfx, uap or uapaot (short: -f)
  -configuration <value>  Build configuration: Debug or Release (short: -c)
  -verbosity <value>      MSBuild verbosity: q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic] (short: -v)
  -binaryLog              Output binary log (short: -bl)
  -help                   Print help and exit (short: -h)

Actions (defaults to -restore -build):
  -restore                Restore dependencies (short: -r)
  -build                  Build all source projects (short: -b)
  -buildtests             Build all test projects
  -rebuild                Rebuild all source projects
  -test                   Run all unit tests (short: -t)
  -performanceTest        Run all performance tests
  -pack                   Package build outputs into NuGet packages
  -sign                   Sign build outputs
  -publish                Publish artifacts (e.g. symbols)
  -clean                  Clean the solution

Advanced settings:
  -coverage               Collect code coverage when testing
  -outerloop              Include tests which are marked as OuterLoop
  -allconfigurations      Build packages for all build configurations
  -os                     Build operating system: Windows_NT or Unix
  -arch                   Build platform: x86, x64, arm or arm64
  -msbuildEngine <value>  MSBuild engine to use: dotnet or vs

Command-line arguments not listed above are passed thru to msbuild.
The above arguments can be shortened as much as to be unambiguous (e.g. -con for configuration, -t for test, etc.).
```

Big thanks to @safern for helping me with the changes!

cc @ericstj @danmosemsft @jkotas @stephentoub @sandreenko @dotnet/corefx-contrib

**Comment by ViktorHofer** [comment]
Please let me know if you face any issues with the new changes.

**Comment by jkotas** [comment]
What's the difference between unit test and  integration test in CoreFX?

**Comment by jkotas** [comment]
Are VSIXes relevant to CoreFX? It sounds very specific to Roslyn and maybe a very few other repos that build VS-specific parts. I do not think it should be in common.

**Comment by wfurt** [comment]
Is it possible to cross-build code & test s from top? 
I'm primarily interested in ARM32/64 (assuming that I do have rootfs created)

**Comment by safern** [comment]
>  Is it possible to cross-build code & test s from top?
> I'm primarily interested in ARM32/64 (assuming that I do have rootfs created

Yes, just how we do our CI and official buils -- just set the ROOTFS_DIR env var. i.e:
`ROOTFS_DIR=/crossrootfs/arm64 ./build.sh -restore -build -buildtests -arch arm64`

**Comment by ViktorHofer** [comment]
> What's the difference between unit test and integration test in CoreFX?

In corefx we don't have that differentiation yet! But as that comes from arcade it nevertheless is helped in the help message which we invoke.

> Are VSIXes relevant to CoreFX? It sounds very specific to Roslyn and maybe a very few other repos that build VS-specific parts. I do not think it should be in common.

When you say common what do you mean? In the common build script or just in the help message so that isn't advertised? Note that we directly invoke the help message from the arcade build script after invoking our specific help message. cc @tmat

**Comment by jkotas** [comment]
> In the common build script or just in the help message

I care about the "new to the repo" experience. The help message of the build script is a key part of that experience. 25% are of the actions listed in help message are irrelevant to the repo. It is not a good experience to have such high noise ratio in the help message.

I think that these special options that are relevant to just small fraction of repos should not be printed in the default arcade build script text, so that the repos can reuse the help text without degrading their "new to the repo" experience.

It is fine with me for these niche options to be still recognized in the default build script; or shown in the advanced version of the help text.

**Comment by ViktorHofer** [comment]
> I care about the "new to the repo" experience.

I do too! I agree with you. We should trim the help message down. Two options:
1) Don't invoke the arcade help script and just copy the relevant parts into our help text.
2) Trim down the arcade build script (either remove parts or as you proposed move stuff into the advanced section)

**Comment by tmat** [comment]
Do [1]. Actually, don't invoke `common/build.ps1` at all. Just import `common/tools.ps1` and use the functions there directly.

**Comment by tmat** [comment]
@jkotas 
> It sounds very specific to Roslyn and maybe a very few other repos that build VS-specific parts

That would be at least 10 repos, btw. But yes, I agree, you should not deal with VS specific parts in CoreFX.

**Comment by danmosemsft** [comment]
Should we put this info into a markdown? I guess it could get out of date there, but equally if this is the documentation it could get out of date here.

I pinned it meantime.

**Comment by jkotas** [comment]
> equally if this is the documentation it could get out of date here.

Yep, this issue should not be the documentation. This issue is an announcement about what changed recently, and it will be irrelevant and outdated in month once more things change.

We should make sure that the (existing) repo documentation is up to date and reflects the current state. For example, the main developer guide doc https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md captures a lot of what is written above; but it is not quite up to date and it is missing a important detail here and there from the above.

**Comment by danmosemsft** [comment]
Maybe this is what is referred to above, but `-?` is still wrong:
```
C:\git\corefx>build.cmd -?
build.ps1 [-build] [-buildtests] [-configuration <string>] [-framework <string>] [-os <string>] [-allconfigurations] [-coverage] [-outerloop] [-arch <string>] [-clean] [-help] [-properties <string[]>] [<CommonParameters>]


C:\git\corefx>build.cmd -h
Default if no actions are passed in: -restore -build

CoreFx specific actions:
  -buildtests             Build test projects in the solution
.. etc..
```

**Comment by ViktorHofer** [comment]
Unfortunately -? invokes the native powershell help. I haven't yet found a hook to override that.

**Comment by ViktorHofer** [comment]
@jkotas I tried to keep the Developer guide updated. Apart from the clean scripts which were replaced by the clean command, what are you missing?

I agree that the scenario table could be useful in the docs. We might want to add it and overhaul the developer-guide with it, which is currently hard to read.

**Comment by jkotas** [comment]
> what are you missing?

Here are a few:
- The full/half-full/empty dots in the platform matrix at the top do not match current state, arm64 is missing. (I think it would look better if the table is just full dots and empty cells.)
- It does not mention that both `-` and `--` work on Unix.
- It mentions integrationTests that are not a thing

Maintaining good docs is hard. Thanks for doing that!

**Comment by danmosemsft** [comment]
> Unfortunately -? invokes the native powershell help. I haven't yet found a hook to override that.
 
build.cmd wraps build.ps1 doesn't it? Why does it invoke the latter if the parameters include /?

**Comment by ViktorHofer** [comment]
> build.cmd wraps build.ps1 doesn't it? Why does it invoke the latter if the parameters include -? or other variants

Not sure I follow. The build.cmd does nothing else than invoke the build.ps1 scripts with all arguments passed in.

**Comment by ViktorHofer** [comment]
> Here are a few:

Thanks, updated the doc. I updated the table but am not 100% sure if the support matrix is right, please take a look.

**Comment by danmosemsft** [comment]
> build.cmd does nothing else than invoke the build.ps1 scripts with all arguments passed in.

Can't it translate /? To -h before it passes them.

**Comment by ViktorHofer** [comment]
/? is not the problem, -? is. Not sure, I think a better option would be to call the help powershell function from the cmd.
