### ISSUE TITLE
Make CoreFx pick up optimization data through darc rather than maestro v1

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#35662]
I've been trying to switch from using maestro v1 to darc for the `optimization.windows_nt-x64.IBC.CoreFx`

I've set up the darc subscription as
```
https://dnceng@dev.azure.com/dnceng/internal/_git/dotnet-optimization (.NET Core 3 Dev) ==> 'https://github.com/dotnet/corefx' ('master')
  - Id: dcaaa06b-98e3-4611-7eda-08d69dadeabb
  - Update Frequency: everyDay
  - Merge Policies:
    AllChecksSuccessful
      ignoreChecks =
                     [
                       "WIP",
                       "license/cla"
                     ]
  - Last Build: N/A
```

Note `.NET Core 3 Dev` channel.  This works for the PGO package that CoreCLR uses but not the IBC package.

Something is wrong with the publishing of dotnet-optimization such that the IBC package we depend on is not being updated.

/cc @hoyosjs @adiaaida

**Comment by adiaaida** [comment]
I think I am overwriting the AssetManifest artifacts because they have the same artifact name. I'm fixing that now.

**Comment by ericstj** [comment]
I see, maybe @jcagme can help figure out how to publish the different legs of the optimization repo.  Maybe you need to give them different build ids, or something.  Not sure if darc is good about a repo publishing independent legs.

**Comment by hoyosjs** [comment]
I talked to him. It's not a scenario supported by DARC/BAR/Maestro++. The only solution, at least for now, is to do a single-step publish to bar.

**Comment by jcagme** [comment]
Independent legs can publish but ideally there is only a single publish to BAR leg. In almost all other build definitions we use it a fork-closing mechanism where 1. only runs if all previous legs succeeded and 2. all the created asset manifests will be merged into one before publishing to BAR so nothing is missed. So the correct thing to do would be to: 

1. Publish to the feed in as many legs as needed (this will generate an asset per publish)
2. Make sure the assets are uploaded to artifacts
3. Run the `Publish to Build Asset Registry Job` only if all the previous legs succeeded (you can look at what arcade is doing)

**Comment by adiaaida** [comment]
Ok, so I set it up wrong. I didn't realize that was how we were meant to do things (I think the docs in arcade might be out of date).

**Comment by jcagme** [comment]
It would be great if you could point us to such doc so we can update what's wrong/out of date.

/cc: @garath

**Comment by jcagme** [comment]
@adiaaida should we open (if there is non yet) a tracking bug for the optimization change?

**Comment by hoyosjs** [comment]
There's a change up for it already.
