### ISSUE TITLE
RemoteExecutorConsoleApp sometimes doesn't get built when building a test project inside VS

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#35681]
Looks like a p2p configuration not to be passed over correctly.

cc @ericstj

**Comment by ericstj** [comment]
Can you be more specific about a repro?

**Comment by ViktorHofer** [comment]
I'll try 😁

**Comment by ericstj** [comment]
Something does come to mind: VS only builds project references that are in the solution.  So if your SLN didn't have this and the vertical build didn't previously build it for you it would cause this.

**Comment by ViktorHofer** [comment]
Thanks Eric! Closing this in favor of https://github.com/dotnet/corefx/issues/35761.
