### ISSUE TITLE
Packaging All Configurations leg takes a really long time in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#35693]
This leg now ends up being the long-pole by far in CI.  It's taking around 30 minutes to build but then almost an hour in the Send To Helix phase, apparently for package validation.

cc: @ViktorHofer, @safern

**Comment by safern** [comment]
Note that sometimes it takes 20 mins to run the tests in the Sen to Helix step. It depends on how long Helix takes to provisión machines, how clogged is the queue. 

@MattGal could you please help me looking how long does this tests really end up taking, and how much they take on waiting for a machine? We could potentially move this tests to a different queue that is no that busy and has enough agents.

**Comment by MattGal** [comment]
I think you're actually running into the "idling at 0 machines" problem here.  I took a recent run as an example:

https://dev.azure.com/dnceng/public/_build/results?buildId=113318&view=logs 
Whose packaging test is Correlation Id `0ccde088-5da9-46bf-bf18-2951c6270689`

- Job was queued at 2019-03-04 10:36
- First work item starts at 2019-03-04 10:48 (~12 minutes)
- The 72 work items ran a total time of 35:35 and you waited 26 minutes for the results.

With pre-existing idle machines, some percentage of the work listed could have been done in the 12 minutes spent creating fresh VMs for your packaging test run, but there really is some benefit to freshly-created machines.  

As such, you're describing this issue: https://github.com/dotnet/core-eng/issues/5081 .  It's tricky with our enormous asymetrical workloads to idle at 0 machines.  At some point I expect we'll idle certain queues at multiple machines but this would be after implementing automatic offlining and cleanup for aged machines.

**Comment by stephentoub** [comment]
Thanks for looking, @MattGal.  What would you recommend then?

**Comment by MattGal** [comment]
We're hoping to have a feature in the near future for recycling machines above a certain age.  Once that's completed, it becomes much more reasonable  (Without it, machines live way too long and go bad) to idle at a number > 0. 

Until then, you might consider trying out other Windows queues;  ones others are using, but not over-using will be a bit faster.  Note that for the amount of tests you're running you're already saving ~9 minutes even in this state, though I agree it's annoyingly slow.

**Comment by safern** [comment]
> Until then, you might consider trying out other Windows queues; ones others are using, but not over-using will be a bit faster. Note that for the amount of tests you're running you're already saving ~9 minutes even in this state, though I agree it's annoyingly slow.

Thanks, @MattGal. Could you recommend one queue that is not over-used?

**Comment by MattGal** [comment]
I'd say either try ClientRS5 or we can do some experiments with higher idling on ClientRS4 to see what the performance gains actually look like (ping me offline if you want to try this)

**Comment by safern** [comment]
> I'd say either try ClientRS5 or we can do some experiments with higher idling on ClientRS4 to see what the performance gains actually look like (ping me offline if you want to try this)

Thanks. I'll follow up offline.

**Comment by ViktorHofer** [comment]
@safern what's the status here? Should we upgrade the queue to use ClientRS5?

**Comment by safern** [comment]
> @safern what's the status here? Should we upgrade the queue to use ClientRS5?

Forgot about this issue, sorry about that. I'll upgrade tomorrow and see if it helps.

**Comment by ViktorHofer** [comment]
Thanks 👍

**Comment by ericstj** [comment]
I think this is reasonable now.  I sampled 5 recent PRs and we are between 40 and 50 minutes.
