### ISSUE TITLE
Add Socket.ReceiveFrom overloads that accept Span<byte>

### ISSUE THREAD

**Issue by jefffhaynes** [dotnet/corefx#35716]
Currently it is possible to perform a socket receive from a connection-oriented protocol using Socket.Receive(Span<byte>, ...).  In some cases it would be desirable to do the same for datagrams, especially in high-performance streaming scenarios.  However, currently the Socket.ReceiveFrom method, necessary to receive datagrams from unconnected sources, does not include any overload which accepts a Span<byte> buffer.

**Comment by davidsh** [comment]
See similar issues: #28131 #30915

**Comment by jefffhaynes** [comment]
After playing with this some more, there's really no great workaround.  Also, I think it's worth noting that the underlying PAL seems to implement ReceiveFrom with Span, but it isn't exposed.

**Comment by karelz** [comment]
Duplicate of #35861
