### ISSUE TITLE
JSON tests timing out on some distros

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#35724]
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F35100~2Fmerge/test~2Ffunctional~2Fcli~2F~2Fouterloop~2F/20190302.1/workItem/System.Text.Json.Tests/wilogs

Dump files aren't working but I see these
```
  System.Text.Json.Tests: [Long Running Test] 'System.Text.Json.Tests.Utf8JsonReaderTests.TestPartialJsonReaderMultiSegment', Elapsed: 00:03:11
[Long Running Test] 'System.Text.Json.Tests.Utf8JsonWriterTests.WriteLargeKeyValue', Elapsed: 00:02:00

```

They appear on several instances, the entire library only gets 10 minutes, can you make these much faster, maybe that will be enough?

@ahsonkhan

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/pull/35100

**Comment by ahsonkhan** [comment]
> They appear on several instances, the entire library only gets 10 minutes, can you make these much faster, maybe that will be enough?

I will see what I can do on Monday. At the very least, this test should be outerloop. Thanks for bringing it up.

**Comment by danmosemsft** [comment]
> At the very least, this test should be outerloop

We are trying to get outerloop consistently green (without retries). If it is not fast, certainly it should be outerloop, but it is not a place for flaky tests (in case that's what you meant..)

**Comment by ahsonkhan** [comment]
> but it is not a place for flaky tests

This test shouldn't be flaky and pass consistently. I'll verify before moving it though.

**Comment by stephentoub** [comment]
> the entire library only gets 10 minutes

My understanding is this is configurable. We should consider making it bigger, at least for outerloop. Sometimes long running tests are unavoidable, in particular when testing edge cases. Obviously we should strive to run tests as quickly as possible and not use a longer timeout as a crutch.

**Comment by danmosemsft** [comment]
In that context presumably the timeout is the same across architectures including some whose hardware is much slower than a dev machine. Soon we will stand up regular 32 bit ARM runs. So on a dev machine the tests ought to consistently finish well within whatever timeout they have.

**Comment by ahsonkhan** [comment]
> At the very least, this test should be outerloop.

I just realized these tests are already part of outerloop.

> We should consider making it bigger, at least for outerloop. Sometimes long running tests are unavoidable, in particular when testing edge cases. 

+1

I will pick a sentinel permutation of the writer options rather than testing all combinations.
