### ISSUE TITLE
await SmtpClient.SendMailAsync never ends

### ISSUE THREAD

**Issue by Eilon** [dotnet/corefx#35738]
_From @BogCZE on Tuesday, 26 February 2019 21:31:18_

### Describe the bug
Hi guys,
We've got problem with SmtpClient.SendMailAsync method. When try to send MailMessage with null or empty Body SendMailAsync never ends or throws exception and thread is stucked.

### To Reproduce
1. Using this version of ASP.NET Core '2.2.1'
2. Run this code - not full code just the main part (we are using our own smtp server)
```c#
 using (var smtpClient = InitSmtpClient(smtpConfig)) {
                    try {
                        var mailMessage = new MailMessage('from', 'To', 'Subject' String.Empty);
                        await smtpClient.SendMailAsync(mailMessage).ConfigureAwait(false);
                        await _emailLogic.MarQueueAsReadAsync(e.Id);
                    }
                    catch (Exception ex) {
                        _logger.LogError(ex, ex.Message);
                    }
                }
```
3. With these arguments `new MailMessage('from', 'To', 'Subject' String.Empty)`
4. No error or result application just awaits and awaits

### Expected behavior
We tried to set Timeout for SmtpClient but after reading documentation we find out that Timeout is not related to SendMailAsync. We expects at least some kind of exception or timeout to be able to react and skip of sending such email. Now just stuck and nothing happens - we run this code using https://blog.maartenballiauw.be/post/2017/08/01/building-a-scheduled-cache-updater-in-aspnet-core-2.html tutorial (it means our email sender runs repeatedly every minute).
Wesolved this issue by add default message to body when null or empty but I think it would be better when this SenMailAsync will not stuck like this at first place.

### Additional context
Include the output of `dotnet --info`
.NET Core SDKs installed:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.2.102 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

_Copied from original issue: aspnet/AspNetCore#7976_

**Comment by Eilon** [comment]
_From @muratg on Tuesday, 26 February 2019 22:44:20_

@BogCZE you may want to move this bug to `dotnet/corefx` repo. It doesn't appear it's related to ASP.NET Core.

**Comment by Eilon** [comment]
_From @benaadams on Tuesday, 26 February 2019 23:07:22_

> you may want to move this bug to `dotnet/corefx` repo.

Link here https://github.com/dotnet/corefx

**Comment by davidsh** [comment]
I've reproduced the hang with .NET Core 2.2. 

It doesn't seem to hang if the SmtpClient.Send() API is used instead.

**Comment by davidsh** [comment]
I've debugged this and can see that in the NULL/empty body case, the 'SendMessageCallback' is not getting called via the IAsyncResult.  This code was originally ported from .NET Framework so it should work the same.  Not sure why it isn't.

**Comment by BogCZE** [comment]
> _From @muratg on Tuesday, 26 February 2019 22:44:20_
> 
> @BogCZE you may want to move this bug to `dotnet/corefx` repo. It doesn't appear it's related to ASP.NET Core.

Thanks for moving. I was on vacation thus I was unable to respond nor move. This topic. Thanks a lot :)

**Comment by BogCZE** [comment]
> I've debugged this and can see that in the NULL/empty body case, the 'SendMessageCallback' is not getting called via the IAsyncResult. This code was originally ported from .NET Framework so it should work the same. Not sure why it isn't.

Well in old implemntation we used sync version and it worked without a problem but now we started to using async version and hit this problem. So I am happy you were able to reproduce this and hopefully it will be fixed in future version :) thank a lot 👍

**Comment by MarcoRossignoli** [comment]
@Eilon are you using internal smtp?Can you try to send using "external" smtp(to have a delay and avoid synchronous execution)?
I did some test and seems that issue jump out in case of empty content and synchronous completion of async send

https://github.com/dotnet/corefx/blob/700f035b9533ed4e439de83e99da1293b7a82e93/src/System.Net.Mail/src/System/Net/Mail/MailPriority.cs#L342-L344

becuse in case of non empty content code ends up to call `LazyAsyncResult.InvokeCallback` wrapper with or without exception, invoking `SendMessageCallback`

https://github.com/dotnet/corefx/blob/700f035b9533ed4e439de83e99da1293b7a82e93/src/System.Net.Mail/src/System/Net/Mime/MimePart.cs#L182-L184

In case of empty execution `InvokeCallback` is called only in case of "real" async execution

https://github.com/dotnet/corefx/blob/700f035b9533ed4e439de83e99da1293b7a82e93/src/System.Net.Mail/src/System/Net/Mail/MailPriority.cs#L312

I think that in case of `CompletedSynchronously` we missed a call to `LazyAsyncResult.InvokeCallback`, something like:
```cs
  else
            {
                LazyAsyncResult result = new LazyAsyncResult(this, state, callback);
                IAsyncResult newResult = writer.BeginGetContentStream(EmptySendCallback, new EmptySendContext(writer, result));
                if (newResult.CompletedSynchronously)
                {
                    writer.EndGetContentStream(newResult).Close();
                    result.InvokeCallback(); <- missing call to `SendMessageCallback`
                }
                return result;
            }
```

/cc @davidsh

**Comment by davidsh** [comment]
@MarcoRossignoli, @Eilon didn't submit the bug.  He just copied it from another repo to CoreFx.

**Comment by MarcoRossignoli** [comment]
ah sorry I missed that :triumph::triumph::triumph: @BogCZE are you using internal smtp?Can you try to send using "external" smtp(to have a delay and try to avoid synchronous execution)?
