### ISSUE TITLE
Perf: String.ToUpper and String.ToLower 3x slower on Linux

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#3574]
Perf test and relevant helper methods:
```
[Benchmark]
[MemberData("TestStringSizes")]
public void ToUpper(int size)
{
    PerfUtils utils = new PerfUtils();
    string testString = utils.CreateString(size);
    foreach (var iteration in Benchmark.Iterations)
        using (iteration.StartMeasurement())
            for (int i = 0; i < 10000; i++)
                testString.ToUpper();
}

 public static IEnumerable<object[]> TestStringSizes()
{
    yield return new object[] { 10 };
    yield return new object[] { 100 };
    yield return new object[] { 1000 };
}

/// <summary>
/// Helper method to create a string containing a number of random
/// characters equal to the specified length
/// </summary>
public string CreateString(int length)
{
    byte[] bytes = new byte[length];
    rand.NextBytes(bytes);
    return System.Convert.ToBase64String(bytes);
}
```

Linux results (same for ToLower) for length=1000:
```
        <performance runid="System.Runtime.Tests.Perf_String.ToUpper-Linux" etl="/home/ianha/uptonogood/results/System.Runtime.Tests.Perf_String.ToUpper-Linux.csv">
          <metrics>
            <Duration displayName="Duration" unit="msec" />
          </metrics>
          <iterations>
            <iteration index="0" Duration="114.61829999089241" />
            <iteration index="1" Duration="111.06960000097752" />
            <iteration index="2" Duration="106.1824000030756" />
            <iteration index="3" Duration="107.53720000386238" />
            <iteration index="4" Duration="147.38410000503063" />
            <iteration index="5" Duration="192.89770001173019" />
            <iteration index="6" Duration="106.46169999241829" />
            <iteration index="7" Duration="159.09139999747276" />
            <iteration index="8" Duration="122.1220999956131" />
          </iterations>
        </performance>
```

Windows results (same for ToUpper) for length=1000:
```
        <performance runid="System.Runtime.Tests.Perf_String.ToUpper-WindowsCore" etl="D:\git\corefx\bin\tests\Windows_NT.AnyCPU.Release\system.runtime.tests\dnxcore50\System.Runtime.Tests.Perf_String.ToUpper-WindowsCore.etl">
          <metrics>
            <Duration displayName="Duration" unit="msec" />
          </metrics>
          <iterations>
            <iteration index="0" Duration="24.6714113552639" />
            <iteration index="1" Duration="24.627505451887373" />
            <iteration index="2" Duration="24.291938904650578" />
            <iteration index="3" Duration="24.389159119270516" />
            <iteration index="4" Duration="24.933421259181614" />
            <iteration index="5" Duration="27.931567232625184" />
            <iteration index="6" Duration="27.334275884739782" />
            <iteration index="7" Duration="25.369629260262627" />
            <iteration index="8" Duration="24.692223893877781" />
            <iteration index="9" Duration="24.623228902856681" />
            <iteration index="10" Duration="24.49778346463745" />
            <iteration index="11" Duration="25.394718347906291" />
            <iteration index="12" Duration="25.005267282888781" />
            <iteration index="13" Duration="25.05630076798252" />
            <iteration index="14" Duration="24.603556777317863" />
            <iteration index="15" Duration="24.572765624300246" />
            <iteration index="16" Duration="24.15480423241479" />
            <iteration index="17" Duration="24.504055736548708" />
            <iteration index="18" Duration="24.982173918125682" />
            <iteration index="19" Duration="24.671981561801203" />
            <iteration index="20" Duration="24.778325081019375" />
            <iteration index="21" Duration="25.687234301572516" />
            <iteration index="22" Duration="25.222801076891756" />
            <iteration index="23" Duration="24.93085532976329" />
            <iteration index="24" Duration="25.105053426927043" />
            <iteration index="25" Duration="24.831069185725482" />
            <iteration index="26" Duration="24.839052077248198" />
            <iteration index="27" Duration="25.224511696504123" />
            <iteration index="28" Duration="24.916600166329317" />
            <iteration index="29" Duration="24.382886847359714" />
            <iteration index="30" Duration="24.53684261244689" />
            <iteration index="31" Duration="24.474690099874806" />
            <iteration index="32" Duration="24.618382147289594" />
            <iteration index="33" Duration="24.329572536116302" />
            <iteration index="34" Duration="24.227220462659716" />
            <iteration index="35" Duration="24.354376520491314" />
            <iteration index="36" Duration="24.271981675842653" />
            <iteration index="37" Duration="26.9305696562883" />
            <iteration index="38" Duration="26.043613387423193" />
            <iteration index="39" Duration="24.764355020854055" />
            <iteration index="40" Duration="24.287377252351689" />
            <iteration index="41" Duration="24.657156191829927" />
          </iterations>
        </performance>
```

Results for other lengths are similar but less severe. I have excluded them for the conciseness but may post them if desired.

**Comment by ianhays** [comment]
I expect this could be an issue with the strings being generated being of a different format on different systems. Could also be some other problem involving the generated strings and the way ToUpper and ToLower treat them.

**Comment by ellismg** [comment]
@ianhays 

> I expect this could be an issue with the strings being generated being of a different format on different systems.

Can you expand on what you mean by this?  Are you implying that when run on windows vs osx the benchmarks are not using the same strings?  If so, that seems like a bug in the infrastructure we should fix.

FWIW, We almost certainly can do better here.  Are there instructions yet on how to run these tests locally?  @stephentoub and I had some optimization ideas during the PR but we were waiting on doing the work until it was easy to get numbers and see changes.

**Comment by ianhays** [comment]
>Can you expand on what you mean by this? Are you implying that when run on windows vs osx the benchmarks are not using the same strings? If so, that seems like a bug in the infrastructure we should fix.

That is correct. However, looking back at the code, I don't see how that could be the case - the strings should be the same as they are using the same Random seed.

>Are there instructions yet on how to run these tests locally?

There are but they're not adequate; a number of changes have been made to the workflow since I wrote them. I need to update buildtools/CoreFX to xunit 2.1.0 to consume some xunit-performance changes and I will update the docs (both on OneNote and Github) with better guidelines afterwards. I'll have that done today and send out an email when it's ready.

**Comment by ianhays** [comment]
@ellismg updated docs coming in https://github.com/dotnet/corefx/pull/3619.

**Comment by stephentoub** [comment]
https://github.com/dotnet/coreclr/issues/1718 helped significantly reduce allocations in ToLower/ToUpper, and https://github.com/dotnet/coreclr/issues/1722 helped improve throughput by ~15%.  

It looks like another ~25% of the throughput/time is going towards UTF16 validation costs in ICU (e.g. the difference between using U16_NEXT/U16_APPEND and U16_NEXT_UNSAFE/U16_APPEND_UNSAFE)... not clear we're going to be able to do anything about that.

It'd be interesting to understand whether the difference only exists for certain cases, e.g. the test is basically ASCII only.  If it does, maybe there are some optimizations that could be done specifically to handle those special-but-common cases.

**Comment by stephentoub** [comment]
We made several changes that significantly improve the situation, both in terms of memory and throughput, including a fast-path for ASCII.  At this point, the main difference appears to be entirely in the ICU implementation as compared to the Windows implementation, and there's little more that can or should be done on the .NET side.  As such, I'm going to close this out.  We can revisit and look into additional workarounds if it shows up as a real issue.
