### ISSUE TITLE
Call to ValueStringBuilder.EnsureCapacity may result in unexpected (smaller) size of the buffer

### ISSUE THREAD

**Issue by shadow-cs** [dotnet/corefx#35746]
`ValueStringBuilder.EnsureCapacity` calls `Grow` with `requiredAdditionalCapacity` argument se to `capacity - _chars.Length` but `Grow` calculates the new buffer size by adding `requiredAdditionalCapacity` to `_pos`.

Following test demonstrates the issue:

```csharp
        [Fact]
        public void EnsureCapacity_IfRequestedCapacityWins()
        {
            // Note: constants used here may be dependent on minimal buffer size
            // the ArrayPool is able to return.
            Span<char> initialBuffer = stackalloc char[32];
            var builder = new ValueStringBuilder(initialBuffer);

            builder.EnsureCapacity(65);

            Assert.Equal(128, builder.Capacity);
        }
```

Currently the `_chars` buffer will be allocated to `64` chars not `128` chars as expected.

To fix this `EnsureCapacity` should call `Grow(capacity - _pos)`.

**Comment by shadow-cs** [comment]
I've fixed the issue in my fork [here](https://github.com/shadow-cs/corefx/tree/issue/value-string-builder) including a few more tests that cover `Grow` and `EnusreCapacity`. I'll be happy to submit a PR ;-).

**Comment by jkotas** [comment]
@shadow-cs The PR with this fix would be very welcomed. Could you please submit it?

**Comment by stephentoub** [comment]
+1; Thanks!  And the fix looks right.  Though we might also want to:
- Rename the argument to Grow to make it clear it's about additional capacity beyond the current position rather than beyond the current span length.
- Add a Debug.Assert to Grow to validate that _pos > _chars.Length - additionalCapacityBeyondPos.

**Comment by shadow-cs** [comment]
@stephentoub will do
