### ISSUE TITLE
Make sure that all throwing exception types are serializable 

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#35748]
I think I saw at least one which wasn't serializable.

**Comment by danmosemsft** [comment]
I had a quick scan and found these. In general I do not think it is a good use of time for us to exhaustively ensure exceptions are serializable (although we might accept PR's). Our only scenario so far is telemetry. We should make sure likely common exceptions are serializable and get feedback on any other cases. I marked `<<` ones that might fall in that category (not sure about networking/security ones). 
```
ChannelClosedException << most interesting?
ReaderWriterLockApplicationException << 
ImageFormatLimitationException (S.R.M)
XPathCompileException  <<
XslLoadException  <<
XslTransformException <<
UpaException
internal WinHttpException
internal HuffmanDecodingException
internal HPackDecodingException 		
internal Http2ProtocolException
CurlException
RethrowException
InvalidEnumArgumentException (S.CM.P)
EventLog*Exceptoin
CompositionException
ComposablePartException
ConfigurationErrorsException (S.CD)
internal InternalException
internla GssApiException
internal SslException 
private AppleCommonCryptoCryptographicException
private AppleCFErrorCryptographicException
private DebugAssertException
XamlParseException (xaml)
ElementNotAvailableException (xaml)
LayoutCycleException (xaml)
```

**Comment by danmosemsft** [comment]
The fact that XmlException is never serializable when it's constructed over an XmlNode seems more important than the above.

**Comment by ViktorHofer** [comment]
Changing label as I don't think there is infrastructure work required.

**Comment by joperezr** [comment]
@ViktorHofer is this required for 3.0?

**Comment by ViktorHofer** [comment]
Yes, we shouldn't release a new .NET Core version with exceptions that aren't serializable as that would break partners (Azure) and customers.

**Comment by danmosemsft** [comment]
Since none of these have been reported I think it's OK for now to just fix this for the obvious mainstream ones. Starting with the XMLException issue mentioned above.

**Comment by joperezr** [comment]
@ViktorHofer I'm happy to take this (that way I'll also learn a bit about serialization), I'll just need to sync up with you for a brief overview.

**Comment by ViktorHofer** [comment]
Sure, just ping me.

**Comment by danmosemsft** [comment]
@joperezr still on track for 7/1? As mentioned above I think this is dialable down

**Comment by joperezr** [comment]
Yes, I haven't started it but it is on my list of to-dos for this week.

**Comment by eiriktsarpalis** [comment]
FYI there's at least one exception type missing a deserialization constructor:

https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpRequestException.cs

**Comment by eiriktsarpalis** [comment]
I would propose adding a test that uses reflection to search for exception types missing serialization boilerplate.

**Comment by ViktorHofer** [comment]
That type doesn't have a deserialization ctor because it uses safe-serialization aka "SerializeObjectState" in .NET Framework. In .NET Core we don't support that.

**Comment by joperezr** [comment]
Closing given the above comment by @ViktorHofer. @eiriktsarpalis feel free to open a new issue or reopen this one (and change the title) in order for adding a guard to catch these issues in the future.
