### ISSUE TITLE
.NET Core runtime refuses to load assemblies serialized with PEHeaderBuilder.CreateLibraryHeader

### ISSUE THREAD

**Issue by osman-turan** [dotnet/corefx#35758]
`PEHeaderBuilder.CreateLibraryHeader()` method does not set `Characteristics.ExecutableImage` bit of image characteristics.

https://github.com/dotnet/corefx/blob/5419ecd858d11f08938019ba49477039de93ec3f/src/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/PEHeaderBuilder.cs#L104-L107

As a result, .NET runtime refuses to load assemblies which were serialized by using `PEHeaderBuilder.CreateLibraryHeader()`. A workaround is explicitly setting this bit by calling `PEHeaderBuilder` constructor like following:

```c#
var peHeaderBuilder = new PEHeaderBuilder(
    imageCharacteristics: Characteristics.ExecutableImage | Characteristics.Dll);
```

I've created a minimal repository to fiddle with it (see: https://github.com/osman-turan/Minimal-Metadata-Serialization). Relevant section is https://github.com/osman-turan/Minimal-Metadata-Serialization/blob/b0447e11b52c384b900970bfc1b2a44d95814c41/MinimalMetadataSerialization/Program.cs#L42-L48

**Comment by osman-turan** [comment]
I can create a pull-request if it's ok to fix it by changing `PEHeaderBuilder.CreateLibraryHeader()`.

**Comment by karelz** [comment]
Yes please, it is marked up-for-grabs, so PR is welcome!
