### ISSUE TITLE
Consider moving RemoteExecutorConsoleApp to arcade

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#35761]
Currently we live build the RemoteExecutorConsoleApp even though it never changes. Building test projects inside VS often fail with an error that VS can't find the `RemoteExecutorConsoleApp.dll` assembly. VS doesn't build ProjectReferences outside of the solution (https://github.com/dotnet/corefx/issues/35681#issuecomment-469393454).

As the RemoteExecutorConsoleApp is a netstandard application without any dependencies on corefx we should consider moving it to arcade and consume it as a nuget package instead. It's general goodness that should be shared with other repositories (i.e. Mono).

Another case where I noticed an out-of-solution dependency is the `PerfRunner` which is used to run performance tests. As performance tests inside corefx will probably go away soon we can ignore it.

cc @safern @ericstj @danmosemsft

**Comment by ericstj** [comment]
@ViktorHofer what is the latest on this issue?

**Comment by ericstj** [comment]
Found PR here: https://github.com/dotnet/arcade/pull/2176

**Comment by ViktorHofer** [comment]
Done with https://github.com/dotnet/corefx/pull/36487
