### ISSUE TITLE
Is there a Resharper settings file for this coding style?

### ISSUE THREAD

**Issue by rkeithhill** [dotnet/corefx#3576]
I personally dislike the default R# C# coding style configuration.  It would be nice to have R# configured for this coding style.  Then I could use R#'s code reformatting functionality to bring code into line.  :-)  While the stand-alone CodeFormatter.exe is nice to have, for the rest of my team, if it isn't integrated into their VS workflow it might as well not exist.

**Comment by ellismg** [comment]
We don't have an R# settings file, if you would like to contribute one, PRs are welcome!  We do have a regular vsssettings file (https://github.com/dotnet/corefx/blob/master/corefx.vssettings) which should codify some stuff.

I believe the long term plan is to get codeformatter to run as a roslyn analyzer so it can provide fixes in your editor as your develop, but @jaredpar would know more about the status of that.

**Comment by jaredpar** [comment]
@ellismg that's correct.  There is an effort underway to move the fixes to analyzers and have code formatter be a driver.  That way it can work equally as well as a command line tool and IDE feature.

**Comment by rkeithhill** [comment]
@jaredpar Looking forward to having this functionality in the IDE.

**Comment by NickCraver** [comment]
@jaredpar any news on the formatter move?

**Comment by jaredpar** [comment]
@srivatsn should have the latest on the move to make code formatter be comprised of analyzers + code fixes.

**Comment by srivatsn** [comment]
Currently we have reimplemented four rules as analyzers\fixers and Codeformatter has been modified to drive these analyzers\fixers. We'll implement the rest of them in the coming months.

**Comment by karelz** [comment]
@jaredpar do we need this bug opened in CoreFX? Is it tracking anything actionable here?

**Comment by jaredpar** [comment]
No I don't think we need a bug here.

**Comment by karelz** [comment]
OK, closing.
cc: @mellinoe

**Comment by quasarea** [comment]
seen .NET Core 2.0.6 released but no DotSettings file there
