### ISSUE TITLE
Consider adding folded trailing header support

### ISSUE THREAD

**Issue by caesar-chen** [dotnet/corefx#35769]
In RFC 2616, HTTP/1.1 header field values can be folded onto multiple lines. Later in RFC 7230, folded header is obsoleted.

Since our code supports folded headers (`Header` property) for compat reason - there are some servers still use it. We may want to add folded header support to `TrailingHeaders` property as well.

Also notice that:
1. In RFC 7230, folded header is obsoleted.
2. HTTP/2 doesn't have folded header concept.

We need to think if this is really needed.

/cc: @dotnet/ncl

**Comment by geoffkizer** [comment]
I think the main issue here is that the folded header line processing is in ReadNextResponseHeaderLineAsync, which is an async method that keeps reading from the underlying stream as necessary.

But we want to use this from ChunkedEncodingReadStream.ReadChunkFromConnectionBuffer, which is synchronous and only operates over the current buffer.

So we need to factor out something like TryReadNextResponseHeaderLine that operates only over the current buffer, and can be called from ChunkedEncodingReadStream.ReadChunkFromConnectionBuffer.

@caesar1995 please correct me if I'm wrong here.

**Comment by caesar1995** [comment]
Yes, this inline with my observation.

**Comment by karelz** [comment]
Triage: Unclear if this happens in practice. Closing for now. If it happens in real-world scenario, we can revisit the decision.
