### ISSUE TITLE
To make a dnx451 support for System.Xml

### ISSUE THREAD

**Issue by Kagamine** [dotnet/corefx#3577]
There was no fx/System.XML on Mono platform.
When I dnu build, there was an error occurred.

```
Unable to resolve dependency fx/System.XML 
```

I think making a dnx451 support for System.Xml will solve the problem.

**Comment by akoeplinger** [comment]
Try with System.Xml instead of System.XML, that should work.

**Comment by Kagamine** [comment]
Thanks, I'll have a try.
