### ISSUE TITLE
System.Diagnostics.Tests.ProcessTests.GetProcessesByName_ProcessName_ReturnsExpected test failure

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#35783]
Failed in this PR: https://github.com/dotnet/corefx/pull/35776 (https://github.com/dotnet/corefx/pull/35776/checks?check_run_id=72655929) on Windows.81.Amd64.Open-x64-Debug:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F35776~2Fmerge/test~2Ffunctional~2Fcli~2F~2Fouterloop~2F/20190305.1/workItem/System.Diagnostics.Process.Tests/analysis/xunit/System.Diagnostics.Tests.ProcessTests~2FGetProcessesByName_ProcessName_ReturnsExpected
```text
Unhandled Exception of Type Xunit.Sdk.NotEmptyException
Message :
Assert.NotEmpty() Failure
Stack Trace :
   at System.Diagnostics.Tests.ProcessTests.GetProcessesByName_ProcessName_ReturnsExpected() in D:\a\1\s\src\System.Diagnostics.Process\tests\ProcessTests.cs:line 1074
```

cc @tmds

**Comment by danmosemsft** [comment]
Interesting.

**Comment by tmds** [comment]
> Windows.81.Amd64.Open-x64-Debug

Not my cup of tea.

**Comment by danmosemsft** [comment]
Two possibilities
1.  Somehow `currentProcess.ProcessName` is not null or empty, in this case `GetProcessesByName` would immediately return empty string causing this result. Suggest asserting that just above this line.
1.  Somehow list returned by `GetProcesses` does not include this process name. Might be worth this test dumping the list to console if it's failing.

**Comment by MarcoRossignoli** [comment]
@danmosemsft we have a log https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F35959~2Fmerge/test~2Ffunctional~2Fcli~2F~2Fouterloop~2F/20190312.1/workItem/System.Diagnostics.Process.Tests/analysis/xunit/System.Diagnostics.Tests.ProcessTests~2FGetProcessesByName_ProcessName_ReturnsExpected

Not enough we should print also `currentProcess.ProcessName` do you agree?

**Comment by wfurt** [comment]
It also failed on OSX and Linux machines. But it is failing _only_ for PRs. There was no single failure in official builds.

```
System.AggregateException : One or more errors occurred. (TimeSpan overflowed because the duration is too long.) (TimeSpan overflowed because the duration is too long.)\n---- System.OverflowException : TimeSpan overflowed because the duration is too long.\n---- System.OverflowException : TimeSpan overflowed because the duration is too long.

----- Inner Stack Trace #1 (System.OverflowException) -----
   at System.TimeSpan.Add(TimeSpan ts) in /__w/2/s/src/System.Private.CoreLib/shared/System/TimeSpan.cs:line 165
   at System.TimeSpan.op_Addition(TimeSpan t1, TimeSpan t2) in /__w/2/s/src/System.Private.CoreLib/shared/System/TimeSpan.cs:line 489
----- Inner Stack Trace #2 (System.OverflowException) -----
   at System.TimeSpan.Add(TimeSpan ts) in /__w/2/s/src/System.Private.CoreLib/shared/System/TimeSpan.cs:line 165
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\projects\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 79
```

**Comment by danmosemsft** [comment]
resovled by https://github.com/dotnet/corefx/pull/37294 ?

**Comment by MarcoRossignoli** [comment]
Mmm error was on Win...btw no more happened...
