### ISSUE TITLE
[Question]Append -skipbuildpackages to local coreclr build

### ISSUE THREAD

**Issue by MarcoRossignoli** [dotnet/corefx#35784]
On benchmarking guide we added a workflow for coreclr https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/benchmarking.md#benchmarking-apis-implemented-within-systemprivatecorelib

On point 9 when we want to compile changes on coreclr we use
```
C:\Projects\coreclr>build.cmd -release -skiptests -skipnative
```

I found `-skipbuildpackages` that speedup a lot the build(we need only to compile System.Private.Corelib and not rebuild all corefx repo), are there unexpected effetcs?Can I use it?

EDIT: We could add on point 10 also 
```
C:\Projects\corefx>msbuild /p:CoreCLROverridePath=C:\Projects\coreclr\bin\Product\Windows_NT.x64.Release\ ./external/runtime/runtime.depproj /p:ConfigurationGroup=Release
```
right?

/cc @adamsitnik @ViktorHofer @jkotas

**Comment by jkotas** [comment]
Yes, it is fine to use `-skipbuildpackages` here

**Comment by ViktorHofer** [comment]
@MarcoRosignolli would you like to send a PR to update the docs?
