### ISSUE TITLE
Using async inside Paralle.ForEeach

### ISSUE THREAD

**Issue by roozbehid-ic** [dotnet/corefx#35793]
Using async inside Parallel.Foreach is not supported.
If you use it, statements after `await` wont run.

First, how can I know this is the case? For example is there anything specific to look for in the statement of method to know that async is supported or not, or anything in documentation to say that?

Second, is it possible to have a warning or something informational from compiler?

For example, following code compiles and runs, but wont print.(I know why it wont print, just asking how to avoid these kinds of mistakes....because I recently learned why and really got scared if I did this mistake previously or not!)

```
            List<char> mylist = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".ToList();
            Parallel.ForEach(mylist, async item =>
            {
                await Task.Delay(100);
                Console.WriteLine($"{item}");
            }
            );
```

**Comment by tarekgh** [comment]
> If you use it, statements after await wont run.

I don't think this is true. it will run but you have it to give it a time to run as you adding some delay. 

Just try something like the following (not I added some Sleep at the end to give time to the other for each to completely run.

```C#
            List<char> mylist = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".ToList();
            Parallel.ForEach(mylist, async item =>
                {
                    await Task.Delay(100);
                    Console.WriteLine($"{item}");
                }
            );

            Thread.Sleep(mylist.Count * 600);
```

I am closing this issue but feel free to reply back with any more questions and I'll be happy to help with.
