### ISSUE TITLE
Timer_Change_BeforeDueTime_ChangesWhenTimerWillFire test fails

### ISSUE THREAD

**Issue by sokket** [dotnet/corefx#3583]
A timer test failed on PR here:

http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/4494/testReport/junit/(root)/TimerChangeTests/Timer_Change_BeforeDueTime_ChangesWhenTimerWillFire/

MESSAGE:
Should have received a timer event after this new duration Expected: True Actual: False
+++++++++++++++++++
STACK TRACE:
at TimerChangeTests.Timer_Change_BeforeDueTime_ChangesWhenTimerWillFire() in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Threading.Timer\tests\TimerChangeTests.cs:line 94

**Comment by joshfree** [comment]
related https://github.com/dotnet/corefx/issues/3533

**Comment by sokket** [comment]
Looks like a dupe, closing this one
