### ISSUE TITLE
How to do async in a dedicated thread not in the pool thread?

### ISSUE THREAD

**Issue by juepiezhongren** [dotnet/corefx#35847]
@davidfowl 
there r long time calculation, IO, timer, but just don't want to interfere with pool.

**Comment by benaadams** [comment]
Create your own `TaskScheduler` e.g. something like
```csharp
public sealed class DedicatedThreadsTaskScheduler : TaskScheduler
{
    public static TaskFactory Factory { get; } = new TaskFactory(
        CancellationToken.None,
        TaskCreationOptions.HideScheduler, TaskContinuationOptions.HideScheduler,
        new DedicatedThreadsTaskScheduler(Environment.ProcessorCount));

    private readonly BlockingCollection<Task> _tasks = new BlockingCollection<Task>();

    public DedicatedThreadsTaskScheduler(int numThreads)
    {
        for (int i = 0; i < numThreads; i++)
        {
            new Thread(() =>
            {
                foreach (Task t in _tasks.GetConsumingEnumerable()) TryExecuteTask(t);
            })
            { IsBackground = true }.Start();
        }
    }

    protected override void QueueTask(Task task) => _tasks.Add(task);

    protected override bool TryExecuteTaskInline(Task task, bool taskWasPreviouslyQueued) => TryExecuteTask(task);

    protected override IEnumerable<Task> GetScheduledTasks() => _tasks;
}
```

Then you can use the `DedicatedThreadsTaskScheduler.Factory.StartNew(...).Unwrap()` instead of `Task.Run`

e.g.
```csharp
Task t = DedicatedThreadsTaskScheduler.Factory.StartNew(() => MyFunc()).Unwrap();
```

**Comment by juepiezhongren** [comment]
@benaadams  thx

**Comment by tarekgh** [comment]
@juepiezhongren let's know if you have any more questions. @benaadams thanks for providing the answer.

**Comment by juepiezhongren** [comment]
@benaadams but how to do it for io callback? i mean call back execute in the same thread with the usage of async-await

**Comment by benaadams** [comment]
> i mean call back execute in the same thread with the usage of async-await

If you want to post back to the same thread, then you can look to using a `SynchronizationContext` https://msdn.microsoft.com/magazine/gg598924.aspx

Also don't use `.ConfigureAwait(false)` on that particular await.

/cc @stephentoub
