### ISSUE TITLE
System.IO.DriveInfo on macOS reports the wrong about of FreeSpace

### ISSUE THREAD

**Issue by TravisEz13** [dotnet/corefx#35869]
# Repro

Call the GetDrives() method of `System.IO.DriveInfo`

# Actual

From PowerShell, which uses the `2.1.8` runtime
```PowerShell
> [System.IO.DriveInfo]::GetDrives() | ?{ $_.Name -like '/'} | %{[int32]($_.TotalFreeSpace / 1GB)}
76
```

Or (comma added for readability)
```PowerShell
> [System.IO.DriveInfo]::GetDrives() | ?{ $_.Name -like '/'} | % TotalFreeSpace
81869557760
```

> 81,869,557,760

# Expected

![image](https://user-images.githubusercontent.com/10873629/53989630-40c24600-40db-11e9-9bcb-e0f51fae6ff9.png)

**Comment by filipnavara** [comment]
Actually, if you look closely the reported number is pretty close to the value of (available - purgeable), or the truly available space.

**Comment by TravisEz13** [comment]
From everything I'm reading, that is currently an irrelevant number.  The OS will manage purging this.  I've verified by writing a file much larger than the available space reported by the formula you specified. (128GB to be exact)

**Comment by TravisEz13** [comment]
Although, once I deleted that file the free space ballooned up to 209GB

**Comment by danmosemsft** [comment]
@TravisEz13 you are looking at `TotalFreeSpace`, what does `AvailableFreeSpace` give you? `TotalFreeSpace` can be larger, as it includes space available to privileged processes (see docs for `statvfs`, `f_bavail` and `f_bfree`)

**Comment by TravisEz13** [comment]
@danmosemsft 	It was sixty something GB.  I can look when I get back to work.

**Comment by danmosemsft** [comment]
You could also do some investigating with `du` and/or a simple program that dumps the results from `statvfs`

**Comment by TravisEz13** [comment]
@danmosemsft 	Can you point me to the code where this is done?  

As I stated before, I could right a file far larger that than the free space either of these numbers were reporting.  After, I wrote the file and deleted it the number they reporting, grew by a large number.  I think the calls are simply calling the wrong underlying API.

**Comment by TravisEz13** [comment]
My amount of purgeable space has now gone to 16GB.  I'm not sure why, I didn't do anything, but it still seems to me the API should report the space that is available to write to, so some implementation detail.

```
Name               : /
IsReady            : True
RootDirectory      : /
DriveType          : Fixed
DriveFormat        : apfs
AvailableFreeSpace : 578838593536
TotalFreeSpace     : 592493441024
TotalSize          : 1000345825280
VolumeLabel        : /
```
![image](https://user-images.githubusercontent.com/10873629/54146144-95700480-43ec-11e9-80a1-292153ddfb1e.png)

**Comment by danmosemsft** [comment]
@TravisEz13 here is the relevant code
https://github.com/dotnet/corefx/blob/96fccd3abda252d781a447fe801c8b389fa0055f/src/Native/Unix/System.Native/pal_mount.c#L102

It should be possible to wrap that in a 10-20 line C program then you can explore without .NET in the picture. I would expect that `du` does this (more elaborately) but I am not sure where the sources are for the `du` that is on macOS.

**Comment by TravisEz13** [comment]
I think `df -h` is a better command to investigate this.  It reports the same size as `AvailableFreeSpace`.  

```
Filesystem     Size   Used  Avail Capacity iused               ifree %iused  Mounted on
/dev/disk1s1  932Gi  380Gi  539Gi    42% 2530248 9223372036852245559    0%   /
```

I'm not sure I want to debug finder to figure out what API it uses and based on the articles I'm reading I don't think they are going to expose an API to get the actual usable space.

**Comment by danmosemsft** [comment]
Thanks for looking @TravisEz13 - that will help anyone else who has this question.
