### ISSUE TITLE
TargetsLinux doesn't work anymore in CSPROJ test projects

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#35878]
I was trying to debug some test failures on Linux tests.  I noticed though when building and running tests on Linux (i.e. Ubuntu), the `$(TargetsUnix)` is true but `$(TargetsLinux)` is undefined.  So, we have various test code files that aren't compiling anymore into the test projects.

For example this block of files won't be included in the build for the test project:
https://github.com/dotnet/corefx/blob/fd88c5df4bde4ef56522a1cd81da1ff69c92edc4/src/System.Net.Security/tests/FunctionalTests/System.Net.Security.Tests.csproj#L113-L147

I first discovered this problem while building on Debian on WSL (Windows Subsystem for Linux).  I thought it might be a WSL specific problem.  But the same problem happens with a real Linux VM.

Is  `$(TargetsLinux)` broken now?  There are several places in CoreFx tests that use it in the CSPROJ file.

```
$ grep -r TargetsLinux .
./System.Data.Odbc/src/System.Data.Odbc.csproj:  <ItemGroup Condition="'$(TargetsLinux)' == 'true' OR '$(TargetsFreeBSD)' == 'true' OR '$(TargetsWebAssembly)'=='true'">
./System.Data.Odbc/tests/System.Data.Odbc.Tests.csproj:  <ItemGroup Condition="'$(TargetsLinux)' == 'true'">
./System.Diagnostics.Process/src/System.Diagnostics.Process.csproj:  <ItemGroup Condition=" '$(TargetsLinux)' == 'true'">
./System.IO.FileSystem.Watcher/src/System.IO.FileSystem.Watcher.csproj:  <ItemGroup Condition=" '$(TargetsLinux)' == 'true'">
./System.IO.Ports/src/System.IO.Ports.csproj:    <GeneratePlatformNotSupportedAssemblyMessage Condition="'$(TargetGroup)' == 'netstandard' AND '$(TargetsWindows)' != 'true' AND '$(TargetsLinux)' != 'true' AND '$(TargetsOSX)' != 'true'">SR.PlatformNotSupported_IOPorts</GeneratePlatformNotSupportedAssemblyMessage>
./System.IO.Ports/src/System.IO.Ports.csproj:  <ItemGroup Condition="'$(TargetsNetFx)' != 'true' AND ('$(TargetsWindows)' == 'true' OR '$(TargetsLinux)' == 'true' OR '$(TargetsOSX)' == 'true')">
./System.IO.Ports/src/System.IO.Ports.csproj:  <ItemGroup Condition=" '$(TargetsLinux)' == 'true' ">
./System.IO.Ports/src/System.IO.Ports.csproj:  <ItemGroup Condition=" '$(TargetsLinux)' == 'true'  OR '$(TargetsOSX)' == 'true'">
./System.IO.Ports/src/System.IO.Ports.csproj:  <ItemGroup Condition="'$(TargetsLinux)' == 'true' OR '$(TargetsOSX)' == 'true'">
./System.IO.Ports/tests/System.IO.Ports.Tests.csproj:  <ItemGroup Condition="'$(TargetsLinux)' != 'true' AND '$(TargetsOSX)' != 'true'">
./System.Net.NetworkInformation/src/System.Net.NetworkInformation.csproj:  <ItemGroup Condition=" '$(TargetsLinux)' == 'true' ">
./System.Net.NetworkInformation/src/System.Net.NetworkInformation.csproj:  <ItemGroup Condition="'$(TargetsLinux)' == 'true'">
./System.Net.Security/tests/FunctionalTests/System.Net.Security.Tests.csproj:  <ItemGroup Condition=" '$(TargetsLinux)' == 'true' ">
```

**Comment by davidsh** [comment]
cc: @dotnet/ncl @stephentoub @wtgodbe @safern @ViktorHofer

**Comment by davidsh** [comment]
I think the problem is how the Configuration.Props was defined.  In the System.Net.Security.Tests CSPROJ file, it references TargetsLinux.  But the Configuration.props file doesn't list "Linux".  It only lists "Unix"

```
$ more *.props
﻿<Project DefaultTargets="Build">
  <PropertyGroup>
    <BuildConfigurations>
      netstandard-Unix;
      netstandard-Windows_NT;
      netstandard-OSX;
      netcoreapp-Windows_NT;
      netcoreapp-Unix;
      netcoreapp-OSX;
    </BuildConfigurations>
  </PropertyGroup>
</Project>
```

System.Data.Odbc test project also uses TargetsLinux in the CSPROJ file.  But its Configuration.props file uses "Linux" instead of "Unix":

```
davidsh@davidsh2:/mnt/d/GitHub/corefx-wsl/src/System.Data.Odbc/tests$ more *.props
﻿<Project>
  <PropertyGroup>
    <BuildConfigurations>
      netcoreapp-FreeBSD;
      netcoreapp-Linux;
      netcoreapp-OSX;
      netcoreapp-Windows_NT;
      netfx-Windows_NT;
    </BuildConfigurations>
  </PropertyGroup>
</Project>
```

I'll have to look around to see if this problem happens elsewhere.

**Comment by wfurt** [comment]
yes, I think Configuration.props is the key. However, it also depends if we truly need  Linux as special case. If not, using netcoreapp-Unix is just fine IMHO. And yes, TargetsLinux is not intuitive.
Also note, that the Configuration also impacts where compiled dll is placed e.g. Any-Unix vs Any-Linux.

**Comment by safern** [comment]
This changed here: https://github.com/dotnet/corefx/commit/db469684ca828f425074f57d4acd07830e3c0163#diff-ad18a0dcd0050fac79576d7138e4a8dfL12

The reasoning of that change is because when you say `netcoreapp-Unix` it doesn't necessarily means it targets linux, it targets unix but not linux specifically. So that is why it was removed. Basically you can now condition it to, `'$(TargetsUnix)' AND '$(TargetOS)' == 'Linux'`. Also I recall that some projects where accidentally including stuff specifically for OSX that was intended for Unix, because TargetsLinux was set to true in that case.

**Comment by davidsh** [comment]
>However, it also depends if we truly need Linux as special case.

The System.Net.Security tests have specific tests for Kerberos with NegotiateStream. Apparently, those tests don't work on Mac OSX.  But do work on Linux.  So, the *.CSPROJ is correct.  What is wrong now is the Configuration.props file.

>This changed here: db46968#diff-ad18a0dcd0050fac79576d7138e4a8dfL12
The reasoning of that change is because when you say netcoreapp-Unix it doesn't necessarily means it targets linux, it targets unix but not linux specifically.

That change broke this.  I can fix the Configuration.props and change out the "Unix" and replace it with "Linux" as needed.

Conceptually, we have 3 OS's (Linux, MacOSX and Windows). And "Unix" == "Linux" + "MacOSX".  I'm not sure I totally agree with that previous change.  I would think that if I targetted "Unix" in the Configuration.props, then of course `$(TargetsUnix)` is true.  But then I would expect `$(TargetsLinux)` and `$(TargetsOSX)` to be true as well.

**Comment by davidsh** [comment]
>Conceptually, we have 3 OS's (Linux, MacOSX and Windows). And "Unix" == "Linux" + "MacOSX".

Actually looking at https://github.com/dotnet/corefx/commit/db469684ca828f425074f57d4acd07830e3c0163#diff-ad18a0dcd0050fac79576d7138e4a8dfL12 again, it seems that "Unix" != "Linux" + "MacOSX".  "Unix" is now considered a separate thing consisting of just "FreeBSD"?  Is that right @wfurt @safern ?

**Comment by wfurt** [comment]
In most cases Unix = !Windows. Looking at the System.Net.Security.Tests.csproj, spitting targets in Configuration.props is right change. It seems like we truly build something else for that OS.

**Comment by davidsh** [comment]
Closing and will track with #24707
