### ISSUE TITLE
NO_PROXY and HTTP_PROXY uppercase variables not working in Linux

### ISSUE THREAD

**Issue by vasicvuk** [dotnet/corefx#35886]
NO_PROXY and HTTP_PROXY  uppercase variables currently are not working in Linux. In code only uppercase HTTPS_PROXY and ALL_PROXY are handled.

https://github.com/dotnet/corefx/blob/56d177d8ed94096c13ac14894945899783b1a3df/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpEnvironmentProxy.cs#L93

**Comment by vasicvuk** [comment]
I've created a pull request for this issue

https://github.com/dotnet/corefx/pull/35887

**Comment by davidsh** [comment]
Fixed with PR #37200
