### ISSUE TITLE
FtpWebRequest.Timeout is ignored when connection to the server fails

### ISSUE THREAD

**Issue by loop-evgeny** [dotnet/corefx#35888]
.NET Core 2.1.8 on Windows 7 x64

When `FtpWebRequest.GetResponse` cannot connect to the server, because it's unreachable or does not respond on port 21 (and not due to DNS issues) it throws a `WebException` after ~21 seconds, while I would expect this to happen after the time set in FtpWebRequest.Timeout. That timeout value seems to be completely ignored.

C# code to reproduce

```
            const int timeout = 2000;

            var request = (FtpWebRequest)WebRequest.Create("ftp://10.99.99.99/"); // A non-existent IP address
            request.Method = WebRequestMethods.Ftp.ListDirectoryDetails;

            request.Timeout = timeout; // This makes no difference
            request.ReadWriteTimeout = timeout; // ... nor this

            var stopwatch = Stopwatch.StartNew();

            try
            {
                request.GetResponse();
                Console.WriteLine("FTP response received after " + stopwatch.Elapsed);
            }
            catch (WebException)
            {
                Console.WriteLine("FTP request failed after " + stopwatch.Elapsed); // Always ~21 seconds
            }
```

A workaround is to use `GetResponseAsync`:

```
        private static WebResponse GetResponseWithTimeout(this WebRequest request)
        {
            var task = request.GetResponseAsync();
            if (Task.WaitAll(new Task[] {task}, request.Timeout))
                return task.Result;
            throw new TimeoutException($"Web request to {request.RequestUri} timed out after {request.Timeout:N0} ms");
        }
```

**Comment by davidsh** [comment]
The 21 second timeout is a fixed timeout in Winsock on Windows.  There is a timeout for establishing the TCP 3-leg handshake (SYN, SYN-ACK, ACK).  There is no control over changing that.  Usually this timeout occurs when the server is very busy and can't even establish a TCP handshake.

There is a similar issue opened before in this repo about this already.

**Comment by davidsh** [comment]
See issues #34095 #31951

**Comment by loop-evgeny** [comment]
OK, I can understand if it's impossible to set a longer timeout than 21 seconds, but it should support a shorter one! GetResponse could be changed internally call GetResponseAsync and time that out, as I've had to do manually.

Also, if a longer timeout is not supported it should not just be silently ignored - this is really confusing to the user (but sadly, .NET Core has a history of doing exactly this).
