### ISSUE TITLE
SSL Certificate validation error on Yocto

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/corefx#35897]
I'm using this test program on my embedded Yocto-based Linux distribution
```csharp
public static async Task Main()
{
    var client = new HttpClient();
    var response = await client.GetAsync("https://microsoft.com");
    Console.WriteLine("yay: " + response.StatusCode);
}
```
 I'm `dotnet publish`ing with `-r linux-arm`. My project file contains
```xml
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <RuntimeFrameworkVersion>2.2.3</RuntimeFrameworkVersion>
```

On the target platform, the program fails with
```
Unhandled Exception: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
[…]
```

When I run with `SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt SSL_CERT_DIR=/dev/null` it works.
When I run with `DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0` it works.

I've checked the `System.Security.Cryptography.X509Certificates.dll` and according to the metadata it was built from https://github.com/dotnet/corefx/tree/5cb2e3488d8e6040a3652e82f54962da468a2e23 — the v2.2.3 tag, so it should include https://github.com/dotnet/corefx/pull/32455 to fix #32224

What else could be wrong?

**Comment by davidsh** [comment]
@bartonjs

**Comment by bartonjs** [comment]
@Tragetaschen The best diagnostics would come from the validation callback on SslStream.

Something like

```C#
HttpClientHandler handler = new HttpClientHandler();

using (HttpClient httpClient = new HttpClient(handler))
{
    handler.ServerCertificateCustomValidationCallback = (request, cert, chain, errors) =>
    {
        Console.WriteLine($"SslPolicyErrors: {errors});

        if (chain == null)
        {
            Console.WriteLine("No chain...");
        }
        else
        {
            foreach (X509ChainElement element in chain.ChainElements)
            {
                Console.WriteLine();
                Console.WriteLine(element.Certificate.Subject);

                foreach (X509ChainStatus status in element.ChainElementStatus)
                {
                    Console.WriteLine($"  {status.Status}: {status.StatusInformation}")
                }
            }
        }
    };

    var response = await client.GetAsync("https://microsoft.com");
    Console.WriteLine("yay: " + response.StatusCode);
}
```

(Unless there's already diagnostic info like this that can be enabled with tracing, @davidsh?)

**Comment by Tragetaschen** [comment]
```
SslPolicyErrors: RemoteCertificateChainErrors

CN=*.microsoft.com

CN=Microsoft IT TLS CA 5, OU=Microsoft IT, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
  PartialChain: unable to get local issuer certificate
SslPolicyErrors: RemoteCertificateChainErrors

CN=www.microsoft.com, OU=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=WA, C=US

CN=Microsoft IT TLS CA 4, OU=Microsoft IT, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
  PartialChain: unable to get local issuer certificate
yay: OK
```

and with `SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt SSL_CERT_DIR=/dev/null`

```
SslPolicyErrors: None

CN=*.microsoft.com

CN=Microsoft IT TLS CA 5, OU=Microsoft IT, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

CN=Baltimore CyberTrust Root, OU=CyberTrust, O=Baltimore, C=IE
SslPolicyErrors: None

CN=www.microsoft.com, OU=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=WA, C=US

CN=Microsoft IT TLS CA 4, OU=Microsoft IT, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

CN=Baltimore CyberTrust Root, OU=CyberTrust, O=Baltimore, C=IE
yay: OK
```

**Comment by bartonjs** [comment]
That's.... odd.

If you try with the 3.0 daily builds does the problem go away?  There were some changes to chain building recently that should have been more favorable to cross-certified chains.  (Unless your SSL_CERT_FILE is pointing at a place different than where your OS tells OpenSSL to (tell us to) look, that shouldn't be the problem; but it's really my best hope)

FWIW: `openssl version -d` will print where OPENSSLDIR is, and ${OPENSSLDIR}/cert.pem is the implicit value for SSL_CERT_FILE.  Of course, if your OS changed OPENSSLDIR between the OpenSSL 1.0.2 and OpenSSL 1.1.x libraries then the command will tell you the 1.1 when we want the 1.0...

**Comment by davidsh** [comment]
>If you try with the 3.0 daily builds does the problem go away? 

You can also try to install the .NET Core 3.0 Preview 3 which released a few days ago. That might be easier than trying to install the daily builds.

https://devblogs.microsoft.com/dotnet/announcing-net-core-3-preview-3/

**Comment by Tragetaschen** [comment]
```
SslPolicyErrors: None

CN=*.microsoft.com

CN=Microsoft IT TLS CA 5, OU=Microsoft IT, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

CN=Baltimore CyberTrust Root, OU=CyberTrust, O=Baltimore, C=IE
SslPolicyErrors: None

CN=www.microsoft.com, OU=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=WA, C=US

CN=Microsoft IT TLS CA 4, OU=Microsoft IT, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

CN=Baltimore CyberTrust Root, OU=CyberTrust, O=Baltimore, C=IE
yay: OK
```

.NET Core 3.0 Preview 3 without any additional environment variables :D

**Comment by davidsh** [comment]
>SslPolicyErrors: None
.NET Core 3.0 Preview 3 without any additional environment variables :D

Glad to see the problem goes away with .NET Core 3.0.

Since this appears to be fixed now, we can close this issue.

**Comment by Nirav-Bhadradiya** [comment]
@davidsh  Facing issues with .net core 3.0 still. @Tragetaschen How did you fixed this can you guide me ?
