### ISSUE TITLE
Consider making the internal parsing/formatting logic public

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#35898]
### Rationale

The existing parsing and formatting functions that live on the various types are culture-aware and support a lot of functionality out of the box. This is generally good in that it ensures we, by default, support a larger band of users.

However, it is often the case that specialized applications may know that the data they are dealing with is always coming from a specific culture, that the data they are dealing with is always invariant, or that it is always in a given format.

Today, we internally support these different code-paths in the internal `System.Number` class. We often have fast paths for cases like "invariant culture", "hex format", or "no special modifiers". But, these are internal and are behind several if checks from the primary APIs (checks that are generally predicted by the CPU to be false).

It may be beneficial for us to consider "productizing" these APIs and making them public. This would give us a centralized location for which specialized number parsing/formatting logic could live and would give end-users access to the underlying `NumberBuffer` in order to better customize their own formatting/parsing logic if desired. It would also give end-users direct access to the "fast-path" functions when they are desirable.

### Proposed APIs

```csharp
// TODO: Document the proposed public surface area.
//       This should probably be split into `NumberFormatter`, `NumberParser`, and `NumberBuffer`.
```

**Comment by tannergooding** [comment]
Will work on updating this with my proposed surface area. But wanted to get the general proposal up for discussion first.

**Comment by stephentoub** [comment]
We've changed the shape of these internal/private helpers on pretty much every .NET Core release. Our flexibility there would cease, our support burden increase, etc. The value added here would need to be huge IMO for this to be worthwhile.
