### ISSUE TITLE
Windows Forms - Core fail w/VS19 RC1 and Core 3 preview 3

### ISSUE THREAD

**Issue by jchang6** [dotnet/corefx#35893]
After installing VS2019 RC1 and .NET Core 3.0 preview 3, my previous Windows Forms apps no longer open. In creating a new project, Windows Forms App (.NET Core) is one of the options, but fails to create. Message: No template could be found with the group identity 'Microsoft.Common.Winforms'
Also, in project properties: Target framework, .NET Core 3.0 is not an option

**Comment by danmosemsft** [comment]
This issue was moved to dotnet/winforms#549
