### ISSUE TITLE
Marshal NCCEventArgs to WinRT crashes

### ISSUE THREAD

**Issue by devsko** [dotnet/corefx#35909]
This happened first in a WPF app with a WindowsXamlHost from the windows toolkit, but it can be reproduced very easy. 
`Windows.winmd` must be referenced and a app.manifest with `<maxversiontested Id="10.0.18226.0"/>` is needed.
``` c#
using System;
using System.Collections.ObjectModel;
using Windows.UI.Xaml.Controls;
using Windows.UI.Xaml.Hosting;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            using (WindowsXamlManager.InitializeForCurrentThread())
            {
                var data = new ObservableCollection<object>();
                var list = new ListBox();
                list.ItemsSource = data;
                data.Add(new object());
            }
        }
    }
}
```
This throws at `data.Add()`
```
Cannot marshal 'parameter #2': Error 0x2608.  Debugging resource strings are unavailable. See http://go.microsoft.com/fwlink/?linkid=106663&Version=4.0.30319.0&File=mscorrc.dll&Key=0x2608

   at System.StubHelpers.StubHelpers.ThrowInteropParamException(Int32 resID, Int32 paramIdx)
   at System.Runtime.InteropServices.WindowsRuntime.NotifyCollectionChangedEventArgsMarshaler.CreateNativeNCCEventArgsInstanceHelper(Int32 action, IntPtr newItem, IntPtr oldItem, Int32 newIndex, Int32 oldIndex)
   at System.Runtime.InteropServices.WindowsRuntime.NotifyCollectionChangedEventArgsMarshaler.ConvertToNative(NotifyCollectionChangedEventArgs managedArgs)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at ConsoleApp2.Program.Main(String[] args) in ...\Program.cs:line 18
```
Environment:
- Windows Preview 10.0.18351.0
- Windows SDK 10.0.18342.0
- .NET Core 3.0.100-preview3-010431

**Comment by jkotas** [comment]
cc @AaronRobinsonMSFT @jeffschwMSFT

**Comment by danmosemsft** [comment]
Aside, should our resources refer to a Silverlight page?
```
    IDS_EE_LINK_FOR_DEBUGGING_MESSAGES       "Debugging resource strings are unavailable. See http://go.microsoft.com/fwlink/?linkid=106663&Version=%1!s!&File=mscorrc.dll&Key=0x%2!X! "
    IDS_EE_LINK_FOR_ERROR_MESSAGES           "Error 0x%3!X!.  Debugging resource strings are unavailable. See http://go.microsoft.com/fwlink/?linkid=106663&Version=%1!s!&File=mscorrc.dll&Key=0x%2!X! "
```

**Comment by devsko** [comment]
@AaronRobinsonMSFT @jeffschwMSFT Sorry for being impatient, but this is blocking us completely from trying to port an UWP app into a XAML island. Are there any news on this or can we somehow workaround?

**Comment by jeffschwMSFT** [comment]
Sorry for the delay @devsko I will take a look today.

**Comment by jeffschwMSFT** [comment]
@devsko can you share a small repro.  I am building up the repro based on the code snippet, but if you had a complete repro that will accelerate the investigation.

**Comment by devsko** [comment]
@jeffschwMSFT  I dont have one but it wont take long...

**Comment by devsko** [comment]
@jeffschwMSFT https://github.com/devsko/Bug35909
This is for Windows SDK 18342. You can change the version in .csproj

**Comment by jeffschwMSFT** [comment]
Thanks for the repro @devsko, I am able to see the issue.  I took a look yesterday and I see the root of the issue.  I have asked @jkoritzinsky to see if there is a workaround or a fix for the issue.

**Comment by devsko** [comment]
Thanks a lot, Jeff. 🤞🏼

**Comment by devsko** [comment]
Hey @jkoritzinsky. Thank you very much for the fix. I am afraid there is another issue with INotifyPropertyChanged. I get a NullReferenceException now on every Binding. The repro is updated https://github.com/devsko/Bug35909. Do you want me to open another bug?
