### ISSUE TITLE
Internal abstract methods are not included in the ref files

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#35924]
This causes problems, e.g.
```cs
using System.ComponentModel;

public class Program
{
    public static void Main(string[] args)
    {
        new SubBaseNumberConverter();
    }

    private class SubBaseNumberConverter : BaseNumberConverter
    {
        public SubBaseNumberConverter() : base()
        {
        }
    }
}
```

This compiles in .NET Core, but throws a `TypeLoadException`

**Comment by hughbe** [comment]
FYI doesn't seem to compile in netfx

**Comment by stephentoub** [comment]
> Internal abstract methods are not included in the ref files

By design. Why should they be?

**Comment by stephentoub** [comment]
@jaredpar, @terrajobst, it appears the C# compiler pays attention to internal abstract methods. Do we need to include them (or a stand-in) in ref assemblies?

**Comment by jaredpar** [comment]
@stephentoub yes and this is a good example of why they should be included.

**Comment by jkotas** [comment]
Add private constructor to ref? It is what we have been doing in other similar cases.

**Comment by stephentoub** [comment]
> Add private constructor to ref? It is what we have been doing in other similar cases.

Seems reasonable. Technically seems like it'd be breaking change, with the visibility of the current implicit ctor changing, but in practice it shouldn't be impactful.

**Comment by jaredpar** [comment]
If the goal is to prevent non-corefx compilations from creating instances or implementing derived types then that will do the trick.

**Comment by karelz** [comment]
Is that a C# compiler problem or something else?

**Comment by jaredpar** [comment]
@karelz 

> Is that a C# compiler problem or something else?

Several behaviors listed here. Which are you referring to?

**Comment by karelz** [comment]
@jaredpar what is this issue in CoreFX tracking - which tool? Which namespace? Can't make heads and tails of it :(

**Comment by jaredpar** [comment]
@karelz same. Feel like there is context missing here. 

Nothing here though looks like a compiler bug though. The compiler has requirements on what must appear in ref assemblies. CoreFX, to my understanding, doesn't add everything which is strictly necessary in this case in their reference assembly generation. That's a bit of a guess though as I don't understand the full scenario here.

**Comment by karelz** [comment]
@stephentoub is it supposed to track infra work in CoreFX repo?

**Comment by jkotas** [comment]
@karelz 

The fix for the specific bug here should be to change `class BaseNumberConverter` constructor to private [here](https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.TypeConverter/ref/System.ComponentModel.TypeConverter.cs#L87).

The more general infrastructure issue is to investigate where [GenApiTool](https://github.com/dotnet/arcade/tree/master/src/Microsoft.DotNet.GenAPI) can be updated to catch this class of bugs.

**Comment by karelz** [comment]
Thanks, that makes sense now! I didn't realize it is about specific class in BCL :(
