### ISSUE TITLE
ZipArchive creation in memory

### ISSUE THREAD

**Issue by Eilon** [dotnet/corefx#35928]
_From @theCuriousOne on Sunday, 10 March 2019 21:07:40_

### Describe the bug
Trying to create a zip file completely in memory, but the entries are not written (empty zip)

### To Reproduce
1. .net core 2.2 (SDK 2.2 102)
2. code to run as a console application:
```
static void Main(string[] args)
        {
            using (Stream zipStream = new MemoryStream())
            {
                using(ZipArchive archive = new ZipArchive(zipStream, ZipArchiveMode.Create,true))
                {
                    ZipArchiveEntry readmeEntry = archive.CreateEntry("Readme.txt");
                    using (StreamWriter writer = new StreamWriter(readmeEntry.Open()))
                    {
                        writer.WriteLine("Information about this package.");
                        writer.WriteLine("========================");
                    }
                }

                using (FileStream compressedFileStream = File.Create("test.zip"))
                {
                    zipStream.CopyTo(compressedFileStream);
                }
            }
        }
```
3. /
4. Open the created test.zip (probably inside the debug folder) and inspect the content of the archive

### Expected behavior
I expect to have a readme.txt file which contains some text, but there is no file.

### Screenshots
/

### Additional context
Maybe I am doing something wrong, but after simplifying the problem as above (I have somewhat more complex scenario) it may point out to a bug in .net core.

_Copied from original issue: aspnet/AspNetCore#8391_

**Comment by stephentoub** [comment]
@theCuriousOne, have you tried setting zipStream.Position = 0 before the CopyTo call?

**Comment by DaZombieKiller** [comment]
The following code worked perfectly fine on my end:
```cs
using System.IO;
using System.IO.Compression;

class Program
{
    static void Main(string[] args)
    {
        using (var ms  = new MemoryStream())
        using (var zip = new ZipArchive(ms, ZipArchiveMode.Create, true))
        {
            using (var readme = zip.CreateEntry("Readme.txt").Open())
            using (var writer = new StreamWriter(readme))
            {
                writer.WriteLine("Information about this package.");
                writer.WriteLine("========================");
            }

            using (var fs = File.OpenWrite("test.zip"))
            {
                fs.SetLength(0);
                ms.Position = 0;
                ms.CopyTo(fs);
            }
        }
    }
}
```

The exact example posted in the OP also works if `zipStream.Position = 0;` is added right before the `CopyTo` call. So that is indeed the issue.

**Comment by stephentoub** [comment]
> that is indeed the issue

Yup. CopyTo by design copies from the current position, so in the original code it wasn't copying anything.

Thanks for confirming the issue is addressed
