### ISSUE TITLE
Getting errors running tests locally

### ISSUE THREAD

**Issue by andrewcahill** [dotnet/corefx#35943]
Hi,

I am trying to build and test the Corefx repo locally in order to assist on issues. I believe I have followed the contributor guide correctly. However when I try to run the command 'build.cmd -clean -restore -build -buildtests -test ' I am receiving a few errors(please see the below image). I am running under regular command prompt in non-admin mode. 

![image](https://user-images.githubusercontent.com/10255671/54117068-7b90ea80-4409-11e9-9815-594cb21df35f.png)

Thanks in advance,
Andrew.

**Comment by ViktorHofer** [comment]
You haven't done anything wrong. The error just tells you that tests in System.Runtime. Tests are failing. Can you please post the xunit failure that's printed onto the console?

**Comment by andrewcahill** [comment]
Got it thanks.

Sure, hopefully the below is what you are looking for:

Discovering: System.Runtime.Tests (method display = ClassAndMethod, method display options = None)
    Discovered:  System.Runtime.Tests (found 5211 of 5262 test cases)
    Starting:    System.Runtime.Tests (parallel test collections = on, max threads = 8)
      System.Tests.ArgIteratorTests.ArgIterator_Throws_PlatformNotSupportedException [SKIP]
        Condition(s) not met: "IsArgIteratorNotSupported"
      System.Tests.DateTimeTests.ToBinary_Invoke_ReturnsExpected(date: 0001-01-01T00:00:00.0000010+04:00, expected: -143999999990) [FAIL]
        Assert.Equal() Failure
        Expected: -143999999990
        Actual:   -4611686162427387894
        Stack Trace:
          C:\dev\github\corefx\src\System.Runtime\tests\System\DateTimeTests.cs(851,0): at System.Tests.DateTimeTests.ToBinary_Invoke_ReturnsExpected(DateTime date, Int64 expected)
      System.Tests.DateTimeTests.ToFileTime_Invoke_ReturnsExpected(date: 1601-01-01T00:00:00.0000000) [FAIL]
        System.ArgumentOutOfRangeException : Not a valid Win32 FileTime.
        Stack Trace:
          F:\vsagent\36\s\src\System.Private.CoreLib\shared\System\DateTime.cs(1333,0): at System.DateTime.ToFileTimeUtc()
          F:\vsagent\36\s\src\System.Private.CoreLib\shared\System\DateTime.cs(1315,0): at System.DateTime.ToFileTime()
          C:\dev\github\corefx\src\System.Runtime\tests\System\DateTimeTests.cs(892,0): at System.Tests.DateTimeTests.ToFileTime_Invoke_ReturnsExpected(DateTime date)
      System.Tests.DateTimeTests.ToFileTime_Invoke_ReturnsExpected(date: 1601-01-01T00:00:00.0000001) [FAIL]
        System.ArgumentOutOfRangeException : Not a valid Win32 FileTime.
        Stack Trace:
          F:\vsagent\36\s\src\System.Private.CoreLib\shared\System\DateTime.cs(1333,0): at System.DateTime.ToFileTimeUtc()
          F:\vsagent\36\s\src\System.Private.CoreLib\shared\System\DateTime.cs(1315,0): at System.DateTime.ToFileTime()
          C:\dev\github\corefx\src\System.Runtime\tests\System\DateTimeTests.cs(892,0): at System.Tests.DateTimeTests.ToFileTime_Invoke_ReturnsExpected(DateTime date)
  System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
     at System.Runtime.ExceptionServices.Tests.HandleProcessCorruptedStateExceptionsTests.RaiseException(UInt32, UInt32, UInt32, IntPtr)
     at System.Runtime.ExceptionServices.Tests.HandleProcessCorruptedStateExceptionsTests.RaiseException(UInt32, UInt32, UInt32, IntPtr)
     at System.Runtime.ExceptionServices.Tests.HandleProcessCorruptedStateExceptionsTests.CauseAVInNative()
     at System.Runtime.ExceptionServices.Tests.HandleProcessCorruptedStateExceptionsTests+<>c.<ProcessExit_Called>b__4_0()
     at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean, Boolean)
     at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
     at System.Reflection.MethodBase.Invoke(System.Object, System.Object[])
     at RemoteExecutorConsoleApp.Program.Main(System.String[])
    Finished:    System.Runtime.Tests
  === TEST EXECUTION SUMMARY ===
     System.Runtime.Tests  Total: 32192, Errors: 0, Failed: 3, Skipped: 1, Time: 22.338s

Thanks.

**Comment by ViktorHofer** [comment]
Awesome. Can you please also share your corefx\.dotnet\dotnet.exe --info output. That contains infos like the OS version which help us diagnosing the issue.

**Comment by andrewcahill** [comment]
Sure please see below file(dotnetinfo.txt)

[dotnetinfo.txt](https://github.com/dotnet/corefx/files/2952609/dotnetinfo.txt)

I have attached also the testresults file for your information.

[testResults.txt](https://github.com/dotnet/corefx/files/2952591/testResults.txt)

Thanks for your help Viktor.

**Comment by stephentoub** [comment]
Thanks.  The tests are buggy; I'll fix them.

**Comment by andrewcahill** [comment]
Great, thanks Stephen.
