### ISSUE TITLE
Update Windows.Compatibility package with newer WCF Core packages.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/corefx#35961]
WCF ran into dotnet/wcf#3437

Could we update the Microsoft.Windows.Compatibility 2.1.0 package to reference WCF Core 4.5.0 or above packages please?

@safern

**Comment by danmosemsft** [comment]
@StephenBonikowsky, for sure @safern can give pointers on how to do this.

**Comment by safern** [comment]
I guess we would need to do this in the release2.2 and master branch. Should be very simple

You need to add the new package versions here:
https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.Windows.Compatibility/externalIndex.json

Also, update it here:
https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.Windows.Compatibility/Microsoft.Windows.Compatibility.pkgproj#L7

**Comment by StephenBonikowsky** [comment]
Opened #35990 for update into Master.

**Comment by safern** [comment]
@StephenBonikowsky could you port your change to release/2.2 branch?

**Comment by StephenBonikowsky** [comment]
Sure
