### ISSUE TITLE
Revisit Index/Range API requirements

### ISSUE THREAD

**Issue by terrajobst** [dotnet/corefx#35972]
One issue with the new `Index` and `Range` types is that in the current design library authors have to do work to provide customers with support for them, specifically they have to add overloads for methods taking indexes and ranges. That's unfortunate, especially for cases where the API in question is an interface and adding overloads isn't possible.

We should consider supporting a code-spit solution for `Index` and `Range` based APIs that avoids forcing library authors to provide overloads. For example, the compiler could lower this code:

```C#
Index i = ...;
var element = collection[i];
```
to

```C#
Index i = ...;
var element = collection[i.GetOffset(collection.Count)];
```

We could use a marker interface (e.g. `ICollection<T>` or `IEnumerable`) to determine that the type is a collection and then synthesize the indexer taking `Index`. Also see this section with [related information](https://github.com/dotnet/apireviews/tree/master/2019/System.Index#convenient-use-of-high-performance-apis).

/cc @stephentoub @tarekgh @jaredpar 

### Proposed API Changes

Based on the current [proposal to improve `Index`/`Range` binding in C#](https://github.com/dotnet/csharplang/blob/master/proposals/index-range-changes.md) we should remove the following APIs:

```diff
 public readonly struct Memory<T>
 {
-    public Memory<T> this[Range range] { get; }
-    public Memory<T> Slice(Index startIndex);
-    public Memory<T> Slice(Range range);
 } 

 public static class MemoryExtensions
 {
     public static ReadOnlyMemory<char> AsMemory(this string text, Index startIndex);
     public static ReadOnlyMemory<char> AsMemory(this string text, Range range);
     public static Memory<T> AsMemory<T>(this T[] array, Index startIndex);
     public static Memory<T> AsMemory<T>(this T[] array, Range range);
     public static Span<T> AsSpan<T>(this ArraySegment<T> segment, Index startIndex);
     public static Span<T> AsSpan<T>(this ArraySegment<T> segment, Range range);
     public static Span<T> AsSpan<T>(this T[] array, Index startIndex);
     public static Span<T> AsSpan<T>(this T[] array, Range range);
 } 

 public readonly struct ReadOnlyMemory<T>
 {
-    public ReadOnlyMemory<T> this[Range range] { get; }
-    public ReadOnlyMemory<T> Slice(Index startIndex);
-    public ReadOnlyMemory<T> Slice(Range range);
 } 

 public readonly ref struct ReadOnlySpan<T>
 {
-    public readonly ref T this[Index index] { get; }
-    public ReadOnlySpan<T> this[Range range] { get; }
-    public ReadOnlySpan<T> Slice(Index startIndex);
-    public ReadOnlySpan<T> Slice(Range range);
 } 

 public readonly ref struct Span<T>
 {
-    public ref T this[Index index] { get; }
-    public Span<T> this[Range range] { get; }
-    public Span<T> Slice(Index startIndex);
-    public Span<T> Slice(Range range);
 } 

 public sealed class String
 {
-    public char this[Index index] { get; }
-    public string this[Range range] { get; }
-    public String Substring(Index startIndex);
-    public String Substring(Range range);
 }
```

**Comment by tarekgh** [comment]
@terrajobst  could you please explain one more time why we need to keep the Slice APIs which takes Index parameter in Span/Memory? Also, why we need to keep the String.Substring APIs which take range and index? I believe we don't want to keep those as we have the same APIs that takes integers. Or those needed for binding? I thought the compiler will just handle such cases and no explicit binding will be needed.

**Comment by stephentoub** [comment]
@terrajobst, could we also use this moment to re-examine `RuntimeHelpers.GetSubArray`?
```C#
namespace System.Runtime.CompilerServices
{
    public static class RuntimeHelpers
    {
        public static T[] GetSubArray<T>(T[] array, Range range);
    }
}
```
Why did we bury this on `RuntimeHelpers` rather than just having it be a normal static helper method like all of the others on `Array` already? e.g.
```C#
namespace System
{
    public class Array
    {
        public static T[] Slice<T>(T[] array, int startIndex, int length); // or Subarray, or some other name
    }
}
```
and taking an int/int pair as with Substring rather than taking a Range?

**Comment by stephentoub** [comment]
I also generally agree with @tarekgh's feedback.  Seems like we should also remove `{ReadOnly}Memory<T>.Slice(Index)` (you can either use the existing int-based overloads or use `memory[^start..]`, `{ReadOnly}Span.Slice(Index)` (same reasoning), and both remaining `String.Substrings` (same reasoning).

**Comment by jaredpar** [comment]
@stephentoub 

> Why did we bury this on RuntimeHelpers rather than just having it be a normal static helper method like all of the others on Array already?

Believe this was the recommendation of @davidwrighton. The decision is somewhat un-interesting to the compiler. Just let us know where to look for it. 

@agocke

**Comment by tarekgh** [comment]
We need to decide about GetSubArray quickly before @agocke do the changes in the compiler side. I am ok with Stephen proposal to move it to Array class. If we change the parameters to be int/int instead of range, I think the compiler has to convert the range to int/int and then call. which would be one extra step to the compiler if I understand correctly). I like int/int if anyone else other than the compiler going to call this method so they don;t have to create a Range object to call it.

**Comment by agocke** [comment]
Note: changing the signature or location of this member will be a "real" breaking change, in that code built with the earlier version of Roslyn will fail to compile against the newer framework, and vice versa.

Like before this will hopefully be a small breaking window, but unlike the pattern-based changes, things will not just continue working.

**Comment by terrajobst** [comment]
Let's take a look at this tomorrow.

**Comment by terrajobst** [comment]
Closed with https://github.com/dotnet/corefx/pull/36976.
