### ISSUE TITLE
JsonSerializer.ReadAsync OOMs if input Stream does not increase the number of bytes read when the serializer increases the buffer size

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#35973]
## Steps to reproduce
Here's the repro app: https://github.com/pranavkm/jsonserializer-oom/blob/master/Program.cs. Tested using shared fx v3.0.0-preview4-27506-4. When the input `Stream` does not fill up the passed in buffer, the serializer attempts to double the size. This eventually OOMs.

## Background

In MVC, we are attempting to write a `Stream` implementation that converts a Stream containing non-UTF8 encoded bytes in to `UTF8` bytes for `JsonSerializer` to read. Our implementation uses a fixed size char array that we read content in to and expect the serializer to continue calling in to it until we've exhausted the input stream. The serializer however attempts to double the buffer size on each call resulting in an OOM in about 10-12 iterations. While we can change our algorithm to attempt to fill up the passed in read buffer to the full extent, this behavior is surprising and I most developers wouldn't anticipate allocating 2GB of memory to parse json. (https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Stream.cs#L112-L113)

## Environment

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview4-010710
 Commit:    7a72261960

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   D:\temp\app2\dotnet-sdk-latest-win-x64\sdk\3.0.100-preview4-010710\

Host (useful for support):
  Version: 3.0.0-preview4-27511-05
  Commit:  2befa32cec

.NET Core SDKs installed:
  3.0.100-preview4-010710 [D:\temp\app2\dotnet-sdk-latest-win-x64\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview4-19158-05 [D:\temp\app2\dotnet-sdk-latest-win-x64\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27511-05 [D:\temp\app2\dotnet-sdk-latest-win-x64\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview4-27508-60 [D:\temp\app2\dotnet-sdk-latest-win-x64\shared\Microsoft.WindowsDesktop.App]
```

**Comment by pranavkm** [comment]
cc @steveharter \ @ahsonkhan

**Comment by stephentoub** [comment]
It'd be good to double check, but I think I fixed this in https://github.com/dotnet/corefx/pull/35823.

**Comment by stephentoub** [comment]
I just tried your repro with master.  I had to add a `if (_index > 500) return 0;` line to the repo to avoid invalid json and to allow the sequence to complete, but I then got the output:
```
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```
and the program ended without error.

**Comment by stephentoub** [comment]
@pranavkm, can you try a build from corefx master (you should be able to just overwrite your System.Text.Json.dll) and confirm the issue is fixed?

**Comment by pranavkm** [comment]
Verified using runtime v3.0.0-preview4-27513-05 that this was resolved. Thanks @stephentoub

**Comment by stephentoub** [comment]
Thanks for verifying, @pranavkm.
