### ISSUE TITLE
HttpClient doesn't always call through HttpMessageInvoker.SendAsync( )

### ISSUE THREAD

**Issue by wizofaus** [dotnet/corefx#35977]
HttpMessageInvoker defines `virtual Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)`.
HttpClient then overrides this, and provides a convenience function where the cancellationToken defaults to None, but it does NOT call the virtual function `SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)`. This means if you derive from HttpClient and override `SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)`  (for mocking or other purposes), any code that calls `HttpClient.SendAsync(HttpRequestMessage message)` doesn't use the overridden version.  It would be a minor and surely sensible change to the latter function to call via the virtual function (in fact, surely it would be safe just to specify a default parameter value for `cancellationToken`?).   As it is currently, I have to ensure any code that uses HttpClient.SendAsync always specifies the cancellation token.

(BTW, yes I know the usually recommended approach is to mock or override HttpMessageHandler instead, but that's actually slightly tricky with many mocking libraries, due to SendAsync being protected)

**Comment by davidsh** [comment]
>It's probably a reasonable change to make, but it does have downsides, e.g. introducing another virtual call and the associated overhead.

@stephentoub Couldn't the extra virtual call be removed (eventually) by the JIT? I know that it already does various "devirtualization" optimizations.

**Comment by stephentoub** [comment]
> Couldn't the extra virtual call be removed (eventually) by the JIT?

Yes, in some situations.  In theory the JIT should be able to remove it if you wrote code like:
```C#
private static readonly HttpClient s_client = new HttpClient();
```
Might already do so. I also doubt the virtual call would be measurable with everything else going on.  Just wanted to call out any downsides.

**Comment by scalablecory** [comment]
This is not really an appropriate place to override behavior anymore, as all the methods taking `HttpCompletionOption` will never call your overridden `SendAsync`.

**Comment by wizofaus** [comment]
> This is not really an appropriate place to override behavior anymore, as all the methods taking `HttpCompletionOption` will never call your overridden `SendAsync`.

Well then can we request that `HttpMessageHandler.SendAsync( )` is made public so it can be more easily replaced by a mock?

**Comment by davidsh** [comment]
>Well then can we request that HttpMessageHandler.SendAsync( ) is made public so it can be more easily replaced by a mock?
Are there any MS-sanctioned guidelines on best practices for mocking Http calls?

The HttpMessageHandler.SendAsync() method is protected internal and only call'able via the HttpClient API family. We do not plan to make this method public as it goes against the current design of HttpClient and would potentially be a breaking change.

However, you might consider using the [HttpMessageInvoker](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpmessageinvoker?view=netcore-3.0) class which is the base class of HttpClient. It basically is a small class which exposes a public virtual [SendAsync](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpmessageinvoker.sendasync?view=netcore-3.0) method. That in turn calls the handler's protected SendAsync() method.  So, you could get the mocking behavior you want by subclassing HttpMessageInvoker directly.
