### ISSUE TITLE
API Proposal: Add protected SecurityDescriptor to ObjectSecurity

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#35993]
Classes derived from `ObjectSecurity` depend on seeing the `_securityDescriptor` field, which is marked internal. This no longer works as types have split into different assemblies and is causing failures. #34151

Propose that we add a protected property to view this. Don't want to make it public as it would allow changing the descriptor and would likely break other logic.

``` C#
namespace System.Security.AccessControl
{
    public abstract class ObjectSecurity
    {
        protected CommonSecurityDescriptor SecurityDescriptor { get; }
    }
}
```

cc: @bartonjs

**Comment by karelz** [comment]
@JeremyKuhne only 1 area label please :)

**Comment by JeremyKuhne** [comment]
> only 1 area label please :)

@karelz Why? This is in both areas. Should I create a new label for "IO related"? Create another issue with the IO label so I can keep track of the proposal?

**Comment by karelz** [comment]
Here's motivation for single area label: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#triage-rules---simplified
Once there are multiple, ownership is unclear. Issues get double counted, etc.
If the issue has 2 separate parts bringing value, then let's have 2 tracking issues linked together.

**Comment by JeremyKuhne** [comment]
API is merged in.
