### ISSUE TITLE
Directory.GetCurrentDirectory() give C:\WINDOWS\system32 on WSL

### ISSUE THREAD

**Issue by wli3** [dotnet/corefx#36003]
Create an app in windows with

```c#
using System;
using System.IO;
namespace wsl
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(Directory.GetCurrentDirectory());
        }
    }
}
```

dotnet publish

on normal windows
```
λ c:\work2\temp\wsl\bin\Debug\netcoreapp3.0\publish\wsl.exe
c:\work2\temp
```

switch to WSL, mine is ubuntu.18.04-x64
```
xingmu@williammain02:~$ /mnt/c/work2/temp/wsl/bin/Debug/netcoreapp3.0/publish/wsl.exe
C:\WINDOWS\system32
```

`C:\WINDOWS\system32` is at least strange. And I am surprised I can even **call an exe in WSL**

**Comment by ichensky** [comment]
Did you compile/run application with dotnet installed into wsl via apt package?

**Comment by svick** [comment]
@wli3 I believe this is part of WSL's Windows interoperability, [as documented here](https://docs.microsoft.com/en-us/windows/wsl/interop#run-windows-tools-from-wsl):

> WSL can invoke Windows binaries directly from the WSL command line using `[binary name].exe`.

It attempts to have meaningful current directory, but that's not always possible:

> By default, WSL tries to keep the working directory of the Windows binary as the current WSL directory, but will fall back on the instance creation directory if the working directory is on VolFs.

You can see that this has nothing to do with .Net by doing the following:

1. Launch WSL directly from the start menu.
2. Run `cmd.exe` from it:

```
svick@Svick:~$ cmd.exe
Microsoft Windows [Version 10.0.17134.648]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>
```

1. Launch WSL the start menu.
2. Change the current directory to some Windows directory.
3. Run `cmd.exe`:

```
svick@Svick:~$ cd /mnt/c
svick@Svick:/mnt/c$ cmd.exe
Microsoft Windows [Version 10.0.17134.648]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\>
```

Notice that in the first case, `cmd.exe` was launched withe the current directory of `C:\WINDOWS\system32`, while in the second case, it had a meaningful current directory.

So, I don't think there's anything to be done here.

**Comment by danmosemsft** [comment]
Thanks @svick. @wli3 please reopen if you believe we are mistaken.
