### ISSUE TITLE
String interpolation should use the implicit string cast before resorting to ToString

### ISSUE THREAD

**Issue by xxbiohazrdxx** [dotnet/corefx#36011]
Let's say we have a class, TestObject. That object has an implicit string operator to cast the object to a string.

```
public class TestObject
{
	private string Value;

	public TestObject(string TestValue)
	{
		Value = TestValue;
	}

	public static implicit operator string(TestObject object)
	{
		return Value;
	}
}
```

If I were to call an method that expects a string, let's say

```
var Test = new TestObject("Hello World!");
File.WriteAllLines("output.txt", Test);
```

And open output.txt, I would see the expected output:
`Hello World!`

However. If I use string interpolation:

```
var Test = new TestObject("Hello World!");
File.WriteAllLines("output.txt", $"Interpolated {Test}");
```

I would expect the text in output.txt to be the following:
`Interpolated Hello World!`

Instead, what happens is the string interpolation uses the `ToString` method. Since I have not overridden `ToString` on `TestObject`, it is called on the base class `Object` which returns the name of the class. Opening output.txt you will see:
`Interpolated TestObject`

**Comment by tannergooding** [comment]
This should likely be filed on the dotnet/csharplang repo, as string interpolation is a language feature.

**Comment by xxbiohazrdxx** [comment]
Gotcha. It's kind of hard to figure out the best place to open an issue with how split up everything is.
