### ISSUE TITLE
ContentLength of HttpWebRequest should be set by  HttpWebRequest.ContentLength On NetCore

### ISSUE THREAD

**Issue by bluetianx** [dotnet/corefx#36029]
I have a nuget package that it send web request base on Net Standard2.0 . I set ContentLength of HttpWebRequest by `request.Headers.Add("Content-Length", "0");` . It can work when I run it on net core (v2.1) ,but It throws a exception ,when I run it on Net Framwork(V4.6.1).  I suggest Net core  throw same exception.   The exception info is `System.ArgumentException
  HResult=0x80070057
  Message=必须使用适当的属性或方法修改“Content-Length”标头。
Parameter name: name
  Source=System
  StackTrace:
   在 System.Net.WebHeaderCollection.ThrowOnRestrictedHeader(String headerName)
   在 System.Net.WebHeaderCollection.Add(String name, String value)
   在 BirdMessenger.Core.Uploader.Create() 在 D:\浏览器下载\BirdMessenger-master\BirdMessenger-master\src\BirdMessenger\Core\Uploader.cs 中: 第 28 行
   在 BirdMessenger.TusClient.Create() 在 D:\浏览器下载\BirdMessenger-master\BirdMessenger-master\src\BirdMessenger\TusClient.cs 中: 第 22 行
   在 ConsoleApp1.Program.Main(String[] args) 在 D:\浏览器下载\BirdMessenger-master\BirdMessenger-master\src\ConsoleApp1\Program.cs 中: 第 28 行
` .

**Comment by stephentoub** [comment]
> It can work when I run it on net core (v2.1) ,but It throws a exception ,when I run it on Net Framwork(V4.6.1). I suggest Net core throw same exception.

Why?

**Comment by bluetianx** [comment]
I just think .Net core and ,Net Framework should have the same behavior in setting ContentLength of HttpWebRequest

**Comment by davidsh** [comment]
>I set ContentLength of HttpWebRequest by request.Headers.Add("Content-Length", "0");

I assume you are trying to do a POST request using HttpWebRequest and this 'Content-Length' represents the size of the request body?  Normally, HttpWebRequest will calculate the 'Content-Length' header automatically for you.  It does this by noticing whether you obtain the request body stream via HttpWebRequest.GetRequestStreamAsync() and then write to that stream and close it.  Then it can calculate the 'Content-Length' from that.
