### ISSUE TITLE
JsonSerializer does not support substituting collection interfaces when parsing

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#36026]
**Runtime version:** 3.0.0-preview4-27513-05

Consider:

```C#
var content = "[ 1, 2, 3]";
Console.WriteLine(JsonSerializer.Parse(content, typeof(List<int>))); // works
Console.WriteLine(JsonSerializer.Parse(content, typeof(IList<int>))); // throws
```

Here's the resulting `JsonReaderException`:

```C#
The JSON value from [System.Collections.Generic.IList`1[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]] could not be converted to System.Collections.Generic.IList`1[System.Int32].
```

It's fairly common to have collection properties on serialized types be interfaces rather than concrete implementations. MVC's model binding and JSON.NET support a variety of interface types including `IEnumerable<T>`, `ICollection<T>`, `IReadOnlyCollection<T>`, `IList<T>` (basically stuff that `List<T>` implements)

**Comment by pranavkm** [comment]
Here's the piece of code that handles the conversion in MVC - https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/ModelBinding/Binders/CollectionModelBinderProvider.cs#L35-L53 (specifically for .lists). Presumably this problem also affects other collection types such as `IDictionary<TKey, TValue>`

**Comment by ahsonkhan** [comment]
> Here's the piece of code that handles the conversion in MVC

Permalink in case master changes:
https://github.com/aspnet/AspNetCore/blob/a673be3b9a2464cb20351f381e189a43beb6f426/src/Mvc/Mvc.Core/src/ModelBinding/Binders/CollectionModelBinderProvider.cs#L35-L53

**Comment by steveharter** [comment]
Closing. These features will address:
https://github.com/dotnet/corefx/issues/36640 and https://github.com/dotnet/corefx/issues/36643

cc @layomia
