### ISSUE TITLE
PipeWriter.AsStream().Dispose should complete the writer?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#36034]
When you call Stream.Dispose{Async} on the Stream returned from PipeWriter.AsStream(), it seems like it should call PipeWriter.Complete (after calling Flush{Async}).  If you were, for example, using a writer stream in one concurrent operation and the associated reader stream in another, with a pipe in between to handle the buffering and hand-off, you'd want the writer to be able to signal to the reader of completion, and with streams that's generally done by closing one end, e.g. closing a Socket (NetworkStream) or anonymous pipe (PipeStream) to indicate to the other end of the connection that no more data will be coming.

I noticed this because we have a VirtualNetwork in our test libraries... I was looking at replacing it with Pipe, and it has this semantic, as it's used as a stand-in for actually communicating over the network.

Are there scenarios where we wouldn't want this complete behavior?

cc: @davidfowl, @pakrym

**Comment by davidfowl** [comment]
> it seems like it should call PipeWriter.Complete (after calling Flush{Async})

Are you suggesting Dispose call FlushAsync as well or just call Complete? If it's the former then it worries me (sync over async by default).

Yes this is reasonable overall, I brought this up in this PR https://github.com/dotnet/corefx/pull/35399#issue-254052752. Would we do the same for PipeReader as well?

> Are there scenarios where we wouldn't want this complete behavior?

Nothing obvious comes to mind, just scenarios where you pass the Stream to another component that disposes it and then you try to use the PipeReader/PipeWriter after. That can be worked around with a non-disposing wrapper stream

**Comment by stephentoub** [comment]
> Are you suggesting Dispose call FlushAsync as well or just call Complete? If it's the former then it worries me (sync over async by default).

What happens if you call Complete without flushing?  Presumably you need to flush in order for the data to be made available to the reader?  In which case, yes, Dispose and DisposeAsync would need to use FlushAsync (potentially special-cased for the stream returned from Pipe's PipeReader if there's something better it could do).

My assumption (based just on my own expected usage, so I might be missing some cases) is that someone using AsStream() is effectively transferring ownership of the PipeWriter to the Stream, with in general all subsequent usage for that operation happening via the Stream, and thus Dispose should by default do the equivalent of disposing the writer, which would be flushing and completing it.

> Would we do the same for PipeReader as well?

We could.  I'm less sure about the benefits of doing that.

> That can be worked around with a non-disposing wrapper stream

I'd be fine as well if we made it optional, e.g. `AsStream(bool leaveOpen = false)`.

**Comment by pakrym** [comment]
> What happens if you call Complete without flushing? 

In the default pipe implementation data becomes available to the reader, no flushing required.

> Are there scenarios where we wouldn't want this complete behavior?

I wasn't able to come up with a scenario where this would hurt.

> My assumption (based just on my own expected usage, so I might be missing some cases) is that someone using AsStream() is effectively transferring ownership of the PipeWriter to the Stream, with in general all subsequent usage for that operation happening via the Stream, and thus Dispose should by default do the equivalent of disposing the writer, which would be flushing and completing it.

You could imagine scenarios where stream wrapper and pipe usages are interleaved especially when trying to interop with existing libraries (e.g. using the PipeWriter directly to write headers and then passing stream wrapper to Newtonsoft.Json to write body)

**Comment by stephentoub** [comment]
> In the default pipe implementation data becomes available to the reader, no flushing required.

Interesting.  So does that mean that back pressure isn't applied when completing?  Is that the expected design for all PipeWriters?

**Comment by davidfowl** [comment]
It's an interesting question. In the Pipe case, there's no backpressure being applied so the PipeWriter never needs to wait for Complete. Other implementations however could result in needing to apply back pressure if it wanted to flush buffered data. Today the StreamPipeWriter implementation in ASP.NET Core 3.0 discards buffered data https://github.com/aspnet/AspNetCore/blob/30d0afca055f5f7a101b20213848672cb262f2d7/src/Http/Http/src/StreamPipeWriter.cs#L287.

**Comment by pakrym** [comment]
> apply back pressure if it wanted to flush buffered data

What's the point of applying backpressure after all data is in memory anyway and the writer is not going to write anymore?

Stream wrapper around PipeWriter should always flush in WriteAsync so there is no problem with not flushing in Dispose.

**Comment by davidfowl** [comment]
The same argument could be made about StreamWriter, it's a choice and since Dispose shouldn't throw you have 2 options:
1. Flush the buffered data
2. Discard the buffered data

**Comment by pakrym** [comment]
I think I understand now. In the default pipe data is in memory and flushing is just flipping a pointer but if PipeWriter is backed by async IO it becomes a problem.

Complete is not async so those PipeWriter implementations are not able to flush efficiently. I guess the answer is to discard.

**Comment by davidfowl** [comment]
One major difference between PipeWriter and Stream is that writes are always buffered, unless you call FlushAsync (WriteAsync being a combination of Write + FlushAsync) so there's an expectation that if you don't flush, then it's disappeared (at least that was the intent since GetMemory/GetSpan/Advance is buffered). Which means that when you call WriteAsync we always FlushAsync no matter what so that we don't break this invariant so it's actually not a problem to discard.

**Comment by pakrym** [comment]
@davidfowl one problem I see is the behaviour change when going from default pipe to other implementations.

Should we break Pipe?
