### ISSUE TITLE
Clean up remains of SecureString

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#3603]
We seem to still have a project.lock.json file for SecureString's tests in src\System.Security.SecureString\tests

This library is also listed in the README.md file.

Can these be removed now?

**Comment by pallavit** [comment]
@ellismg Thanks for creating the issue. I am not sure why project.lock.json file was left behind since I removed the whole System.Security.SecureString directory! I will send a PR,.

**Comment by pallavit** [comment]
This should already be fixed as part of #3628
