### ISSUE TITLE
Proposal: Add ReadOnlySpan<char> (variable name) overload to System.Environment.GetEnvironmentVariable

### ISSUE THREAD

**Issue by OlegKarasik** [dotnet/corefx#36046]
I wouldn't say need for this overload is a common scenario but I personally do hit it from time to time. Here are two scenarios when having `System.Environment.GetEnvironmentVariable(ReadOnlySpan<char>)` overload would be very helpful:

1. **Expanding environment variable during parsing** - now when `Span` is available you can do more and more parsing without creating any sub string (_which is great_). Unfortunately you still have to do this when trying to expand environment variables. Having this overload would solve this problem.
2. **Mutating environment variable name** - In general it is quite common to access environment variables use case when environment variables are retrieved through several layers of abstraction. Some of these layers usually customize variable name (_prefix, postfix, etc._). All these modification require a new `string` with solo purpose being passed layer down. Having this overload would allow to use `stackalloc` and `ReadOnlySpan<char>` to avoid memory allocations.

**Comment by GrabYourPitchforks** [comment]
What type of application would benefit from this? Generally we use `Span<T>` for hot or tight code paths. Reading an environment variable seems like something that would only take place a small handful of times over an application's entire lifetime, and if it's only a small handful of times then it seems acceptable to perform the allocations.

**Comment by OlegKarasik** [comment]
@GrabYourPitchforks 
I faced this when I was working on the project which was able to dynamically configure different configuration sources on application startup based on configuration passed through environment variables. This configuration was accessed on multiple abstraction levels, so to distinguish these levels all variables were extended with prefixes and postfixes. So this was a typical case when you request variable "NAME" and this would result in "PREFIX_NAME_POSTFIX". This is where `Span<T>` and `stackalloc` can be very handy because you can allocate some space on stack (limited) an reuse it to append / prepend these prefixes and postfixes to form environment variable name. The you can pass resulting `ReadOnlySpan<T>` to `System.Environment.GetEnvironmentVariable` and get the value, all this without unnecessary allocations.

I agree that this isn't a popular scenario and (probably) in most cases a few extra allocations aren't a problem. In the case I've tested there was about 100 configuration parameters on three layers (two prefixes and postfix) so there was some startup penalty due to unnecessary allocations but I would never call them critical but this case drove me to the idea of having such overload.

**Comment by jkotas** [comment]
> 100 configuration parameters on three layers

Allocations of about 300 environment variable names will cost in the order of 10's microseconds. Drop in a bucket for typical startup path. 

Note that the typical `Environment.GetEnvironmentVariable` cost is more than 10x of allocation of typical environment name. If you wanted to make this pattern to scale well for large number of parameters, you would want to reduce number of times `Environment.GetEnvironmentVariable` is called, e.g. fetch snapshot of environment variables using `GetEnvironmentVariables`, index it, and do lookups in that snapshot.

**Comment by jkotas** [comment]
This overload would not move the performance needle enough.

**Comment by OlegKarasik** [comment]
> Note that the typical Environment.GetEnvironmentVariable wall-clock time cost is more than 10x of allocation cost of typical environment name. If you wanted to make this pattern to scale well for large number of parameters, you would want to reduce number of times Environment.GetEnvironmentVariable is called, e.g. fetch snapshot of environment variables using GetEnvironmentVariables, index it, and do lookups in that snapshot.

This is how it is done currently. 

Thanks for taking a look!
