### ISSUE TITLE
System.IO.Pipes.PipeOptions.CurrentUserOnly doesn't work cross platform

### ISSUE THREAD

**Issue by TylerLeonhardt** [dotnet/corefx#36053]
I've confirmed on Windows that the following code **does** set the correct ACLs but on macOS and Linux (Ubuntu), the correct ACLs (aka file permissions) are not set:

minimal PowerShell example:
```
/home/tyler> $pipe = [System.IO.Pipes.NamedPipeServerStream]::new("withacl", [System.IO.Pipes.PipeDirection]::InOut, 1, [System.IO.Pipes.PipeTransmissionMode]::Byte, [System.IO.Pipes.PipeOptions]::CurrentUserOnly)

/home/tyler> getfacl --access /tmp/CoreFxPipe_withacl                                                                                                          getfacl: Removing leading '/' from absolute path names
# file: tmp/CoreFxPipe_withacl
# owner: tyler
# group: tyler
user::rwx
group::rwx
other::r-x
```

These permissions are identical to when you create a PipeServer without the `CurrentUserOnly`:

```
/home/tyler> $pipe = [System.IO.Pipes.NamedPipeServerStream]::new("noacl", [System.IO.Pipes.PipeDirection]::InOut, 1, [System.IO.Pipes.PipeTransmissionMode]::Byte, [System.IO.Pipes.PipeOptions]::Asynchronous)         
      
/home/tyler> getfacl --access /tmp/CoreFxPipe_noacl                                                                                                            getfacl: Removing leading '/' from absolute path names
# file: tmp/CoreFxPipe_noacl
# owner: tyler
# group: tyler
user::rwx
group::rwx
other::r-x
```

Am I doing something wrong?

**Comment by filipnavara** [comment]
Yes, you are assuming that it works based on file permissions. It does not.

**Comment by TylerLeonhardt** [comment]
@filipnavara how does it work? Perhaps a better question is... how can I be sure that no other user can connect to my pipe?

**Comment by filipnavara** [comment]
Sorry, obviously I should have answered that in the first place. I am no expert on it though, but this search should point you in the right direction: https://github.com/dotnet/corefx/search?utf8=✓&q=GetPeerId&type=

**Comment by TylerLeonhardt** [comment]
Thanks for that... I see now that something is in place but I still don't quite see how a rogue process couldn't read/write directly to the pipe file though.

**Comment by stephentoub** [comment]
> I see now that something is in place but I still don't quite see how a rogue process couldn't read/write directly to the pipe file though

The code compares its own user id against that of the remote:
https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.IO.Pipes/src/System/IO/Pipes/NamedPipeClientStream.Unix.cs#L105-L114
https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.IO.Pipes/src/System/IO/Pipes/NamedPipeServerStream.Unix.cs#L95-L104
and throws / kills the connection if it doesn't match.
