### ISSUE TITLE
HttpWebRequest doesn't use WebRequest.DefaultWebProxy settings

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#36058]
The design of HttpWebRequest uses the WebRequest.DefaultWebProxy static property as the default value of its .Proxy property.  And by default this points to the system proxy (e.g. on Windows it is the IE settings).  The current recommended pattern for developers on .NET Framework that need to pass proxy credentials to this proxy is to set [WebRequest.DefaultWebProxy.Credentials](https://docs.microsoft.com/en-us/dotnet/api/system.net.webrequest.defaultwebproxy?view=netframework-4.7.2#System_Net_WebRequest_DefaultWebProxy) property.

This works on .NET Framework but does not work on .NET Core.

On .NET Framework, the HttpClient APIs actually pay attention to WebRequest.DefaultWebProxy.Credentials property as a side-affect of the implementation of HttpClient on .NET Framework which uses HttpWebRequest underneath.  However, users are encouraged to migrate to the [HttpClientHandler.DefaultProxyCredentials](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.defaultproxycredentials?view=netframework-4.7.2#System_Net_Http_HttpClientHandler_DefaultProxyCredentials) property instead.

On .NET Core, the HTTP stack itself is implemented in a different way. HttpClient is the underlying HTTP protocol stack. And HttpWebRequest is built as a thin layer on top of HttpClient APIs. The recommendation is for users to use HttpClient directly since it is the modern and higher performing API surface.

On .NET Core, the WebRequest family of objects (WebRequest, HttpWebRequest, etc.) are considered legacy APIs and provided for app-compat only.

On .NET Core, it is not intended that WebRequest.DefaultWebProxy.Credentials will be used directly by HttpClient APIs. Users can already use the [HttpClientHandler.DefaultProxyCredentials](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.defaultproxycredentials?view=netframework-4.7.2#System_Net_Http_HttpClientHandler_DefaultProxyCredentials) property instead. However, it is expected that direct use of HttpWebRequest should work properly with WebRequest.DefaultWebProxy.Credentials regardless of how it is implemented on .NET Core.

Here is some repro code to demonstrate. Assume that Fiddler is used as the proxy and requires simple Basic proxy authentication with user="1" and password="1".

```c#
using System;
using System.IO;
using System.Net;

internal class Program
{
    static void Main()
    {
        Console.WriteLine($"(Framework: {Path.GetDirectoryName(typeof(object).Assembly.Location)})");

        try
        {
            WebRequest.DefaultWebProxy.Credentials = new NetworkCredential("1", "1"); // This is what Fiddler needs.

            var serverUri = new Uri("http://corefx-net-http11.azurewebsites.net");
            HttpWebRequest request = HttpWebRequest.CreateHttp(serverUri);

            var response = (HttpWebResponse)request.GetResponseAsync().GetAwaiter().GetResult();
            Console.WriteLine($"{(int)response.StatusCode} {response.StatusDescription}");
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex);
        }
    }
}
```

On .NET Framework, the output is "200 OK" since it can successfully pass the proxy credentials to the default system proxy (Fiddler). On .NET Core, the result is a WebException being thrown with "System.Net.WebException: The remote server returned an error: (407) Proxy Auth Required."

**Comment by davidsh** [comment]
I have identified a possible simple fix for this.

**Comment by HASSEN-MEDDEB-ATOS** [comment]
Hello @davidsh
How can i resolve this in .Net core :/ WebRequest.DefaultWebProxy  WebRequest.DefaultWebProxy           
`````````
public static class CRMConnection
    {
        private static OrganizationServiceProxy sp = null;
        private static IWebProxy proxy = WebRequest.DefaultWebProxy;
        private static string URL;
        private static string Login;
        private static string MDP;
        private static string B64_Encoded_MDP;
        private static string Xml_Settings_Path = Directory.GetParent(Directory.GetCurrentDirectory()).Parent.Parent.FullName + @"\VSMP_Settings_File.xml";
        private static XmlDocument VELBOURN_Settings;

        public static OrganizationServiceProxy InitCRMConnection()
        {
            try
            {


                const SslProtocols _Tls12 = (SslProtocols)0x00000C00;

                const SecurityProtocolType Tls12 = (SecurityProtocolType)_Tls12;

                ServicePointManager.SecurityProtocol = Tls12;

                VELBOURN_Settings = new XmlDocument();
                VELBOURN_Settings.Load(Xml_Settings_Path);
                B64_Encoded_MDP = VELBOURN_Settings.DocumentElement.SelectSingleNode("//CRMConnection_Settings//MDP").InnerText;
                MDP = Base64Decode(B64_Encoded_MDP);
                URL = VELBOURN_Settings.DocumentElement.SelectSingleNode("//CRMConnection_Settings//CRMLink").InnerText;
                Login = VELBOURN_Settings.DocumentElement.SelectSingleNode("//CRMConnection_Settings//Login").InnerText;

                PropertyInfo _WebProxy = proxy.GetType().GetProperty("WebProxy", BindingFlags.NonPublic | BindingFlags.Instance);
                WebProxy wProxy = (WebProxy)_WebProxy.GetValue(proxy, null);
                wProxy.Credentials = System.Net.CredentialCache.DefaultNetworkCredentials;
                

                if (string.IsNullOrEmpty(URL) || string.IsNullOrEmpty(Login) || string.IsNullOrEmpty(MDP))
                    throw new Exception("connection failed");

                Uri OrganizationUri = new Uri(Path.Combine(URL + "XRMServices/2011/Organization.svc"));
                ClientCredentials cc = new ClientCredentials();
                ClientCredentials cd = null;

                cc.UserName.UserName = Login;
                cc.UserName.Password = MDP;

                // On se connecte
                sp = new OrganizationServiceProxy(OrganizationUri, null, cc, cd);
                sp.ServiceConfiguration.CurrentServiceEndpoint.EndpointBehaviors.Add(new ProxyTypesBehavior());

            }
            catch (Exception ex)
            {
                LogHelper.Writer("Erreur lors de la connexion au crm, Message de l'erreur : " + Environment.NewLine + ex.ToString());
            }
            return sp;
        }       
        private static string Base64Decode(string base64EncodedData)
        {
            var base64EncodedBytes = Convert.FromBase64String(base64EncodedData);
            return Encoding.UTF8.GetString(base64EncodedBytes);
        }
    }
````````
