### ISSUE TITLE
ComputeHash Async required

### ISSUE THREAD

**Issue by mgardi85** [dotnet/corefx#36068]
Currently "System.Security.Cryptography.HashAlgorithm" has Computehash with 3 overloads.
one of them takes Stream as an input and reads from the stream to compute the hash.

can we have an "ComputeHashAsync" to do this item as the reading from stream can be done async

**Comment by GrabYourPitchforks** [comment]
Seems reasonable. Thinking something like the below?

```cs
public class HashAlgorithm
{
    public virtual Task<byte[]> ComputeHashAsync(Stream inputStream, CancellationToken cancellationToken = default);

    // Do we also need the below method? There's no existing Stream-based overload.
    public virtual Task HashCoreAsync(Stream inputStream, CancellationToken cancellationToken = default);
}
```

**Comment by niklasholm** [comment]
I discovered the need for this when migrating to ASP.NET Core 3.0. Kestrel now throws an error by default if trying to access the request stream synchronously, as hashing the request body would do. To work around it, I had to copy the request stream (asynchronously) to a memorystream object and use it for hashing, which seems like an expensive and ugly workaround. The hash algorithm having an async implementation of ComputeHash would be very useful in this case.

**Comment by terrajobst** [comment]
* Makes sense. We shouldn't make the API virtual though because it just does an async read and then forwards to the existing sync API
* Without `virtual`, we don't need `HashCoreAsync`


```C#
public class HashAlgorithm
{
    public Task<byte[]> ComputeHashAsync(Stream inputStream, CancellationToken cancellationToken = default);
}
```
