### ISSUE TITLE
Add RFC 3161, SignedCms, and SignerInfo changes to netstandard2.1

### ISSUE THREAD

**Issue by dtivel** [dotnet/corefx#36062]
Please add to netstandard2.1:

* https://github.com/dotnet/corefx/issues/24524 (including at least `SignerInfo.GetSignature()` from https://github.com/dotnet/corefx/issues/14197).
* https://github.com/dotnet/corefx/issues/25449

CC @bartonjs, @rrelyea

**Comment by rrelyea** [comment]
NuGet team is driving to ship XPlat signature validation as part of a NetStandard 2.1 NuGet.Packaging.dll
Can this be made available in Preview7 of 3.0?

**Comment by bartonjs** [comment]
@rrelyea That's the plan.
