### ISSUE TITLE
Will you have WCF for .net core? When?

### ISSUE THREAD

**Issue by lopatnov** [dotnet/corefx#36063]
Will you have WCF for .net core? When?

**Comment by KexyBiscuit** [comment]
It's already [here](/dotnet/wcf).

**Comment by BhaaLseN** [comment]
Probably means more like dotnet/wcf#2695. Still waiting on WCF hosting (not client), NetTcp (for .NET/.NET communication) and NamedPipe (for local machine IPC) transports here as well.

**Comment by lopatnov** [comment]
It's about WCF hosting, client and about connected services.

**Comment by Joe4evr** [comment]
The gRPC work that's being done in ASP.NET Core is set to be the "new" WCF. [The latest Community Standup](https://www.youtube.com/watch?v=Sg1TI3cOUkU) even talks about it as such.

**Comment by davidsh** [comment]
Closing since the question has been answered.

**Comment by Grauenwolf** [comment]
That doesn't make any sense. 

* gRPC isn't going to support the existing WS-* standards.
* gRPC isn't going to support named pipes or MSMQ or any of the other wire formats
* gRPC doesn't concern itself with things like distributed transactions

Yes, I'm happy that we're going to get a gRPC implementation. But it doesn't solve the same problems that WCF was designed to solve.
