### ISSUE TITLE
jsonconvert.deserialzeobject cannot convert some value 

### ISSUE THREAD

**Issue by Ultronvision** [dotnet/corefx#36075]
Hi Friends, I have encountered some issues regarding JsonConvert.DeserializeObject functionality. I am using the C# POCO class to deserialize the incoming strings from some server. Weird thing is  that  "SBcontentresults = httpScanBarcode.Content.ReadAsStringAsync().Result;" when I mouse over the SBcontentresults object the VisualStudio community 2017 ask me to which format it shows the results while selecting the JSON Visualizer and it shows all the values. While using the "ScanBarcodeInfoList = JsonConvert.DeserializeObject<BarcodeData>(SBcontentresults);" actually missed one of the value which is string type. Now the question is why is this behavior, and it works for other string variables but not for a particular one. I am using content core 2.1 and builtin Newtonsoft.Json namespace.

**Comment by yujayee** [comment]
I don't think Newtonsoft.Json is owned by Microsoft, correct? @karelz

**Comment by ahsonkhan** [comment]
> I don't think Newtonsoft.Json is owned by Microsoft, correct?

Correct, it isn't. @Ultronvision, I believe the appropriate repo for this issue is: https://github.com/JamesNK/Newtonsoft.Json

Presumably you are talking about `Newtonsoft.Json` (https://www.newtonsoft.com/json/help/html/Overload_Newtonsoft_Json_JsonConvert_DeserializeObject.htm).

cc @JamesNK
