### ISSUE TITLE
System.IO.Compression.ZLibException: The stream state of the underlying compression routine is inconsistent

### ISSUE THREAD

**Issue by kabazakra** [dotnet/corefx#36072]
Hi,

I have netcoreapp2.1 app, that provides some push notifications (actually, an intensive data stream) based on 'server sent events' protocol over HTTP. A client can subscribe and listen to updates. I added GzipCompressionProvider to the netcore services DI to gzip the traffic. To ensure that only one thread writes data to connection, I have a batch block that accumulates 'pushes' into a queue per connection (per single HttpResponse in the backend). From time to time I am getting a very abstract error, that stream is inconsistent. 

System.IO.Compression.ZLibException: The stream state of the underlying compression routine is inconsistent.
at System.IO.Compression.Deflater.Deflate(FlushCode flushCode)
at System.IO.Compression.Deflater.ReadDeflateOutput(Byte[] outputBuffer, FlushCode flushCode, Int32& bytesRead)
at System.IO.Compression.DeflateStream.FlushAsyncCore(CancellationToken cancellationToken)

Can you advise what can cause such errors? It shouldn't be a multithreading issue, but I am wondering in which case we can have such 'stream violations'.

Thanks!

**Comment by stephentoub** [comment]
Are you able to share an isolated repro of the issue?

> Can you advise what can cause such errors? It shouldn't be a multithreading issue, but I am wondering in which case we can have such 'stream violations'.

The error is coming from zlib, the native library used by DeflateStream.  If you search for Z_STREAM_ERROR in http://www.zlib.net/manual.html, you can see descriptions of the various reasons it might happen.

**Comment by kabazakra** [comment]
Hi, 
@stephentoub thanks for the link, Well, to be honest, it is not reproducible in isolated tests. I don't know what causes this issue to happen. Even if I close the underlying connection I get another error. Can it be related to insufficient memory problems?

**Comment by carlossanlop** [comment]
Triage:
This is not actionable without a repro. Closing. If you can give us a repro, even offline, feel free to reopen.
