### ISSUE TITLE
Move AsyncLazy implementation from Roslyn to CoreFX

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#36078]
Roslyn implements and heavily uses `AsyncLazy<T>` abstraction for a lazy value that can be retrieved asynchronously (or synchronously). The implementation is in

https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Utilities/AsyncLazy%601.cs

I'd like to propose that we move this primitive (and perhaps clean it up a bit) to a CoreFX library (System.Threading.Tasks/Extensions?) since it is a general concept that can be reused in other libraries and the implementation is tricky to get right.

Note that the functionality is needed in libraries targeting .NET Framework 4.7.2+ as well as .NET Core.

**Comment by sharwell** [comment]
I'm not currently convinced the implementation in Roslyn is correct, especially in relation to things like vs-threading. I would expect these issues to be resolved before claiming it's ready for general use.

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/32552

**Comment by tarekgh** [comment]
closing the issue as @stephentoub pointed out it is duplicate from other active issue.
