### ISSUE TITLE
Unable to run netfx tests locally

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#36079]
Even after doing a full netfx build from root, trying to run netfx tests for projects locally fails, e.g.
```
d:\repos\corefx\src\System.Net.Security\tests\FunctionalTests>dotnet msbuild /t:rebuildandtest /p:TargetGroup=netfx
Microsoft (R) Build Engine version 16.0.385-preview+g966cdf2ac6 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  RemoteExecutorConsoleApp -> d:\repos\corefx\artifacts\bin\RemoteExecutorConsoleApp\netstandard-Debug\RemoteExecutorConsoleApp.exe
d:\repos\corefx\artifacts\bin\runtime\netfx-Windows_NT-Debug-x64\Microsoft.NET.Test.Sdk.Program.cs(3,25): error CS0234: The type or namespace name 'TestPlatform' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?) [d:\repos\corefx\src\System.Net.Security\tests\FunctionalTests\System.Net.Security.Tests.csproj]
```

@safern is investigating.
cc: @ViktorHofer

**Comment by safern** [comment]
Before change: https://github.com/dotnet/corefx/commit/a99a7a450d7b3b785b0a495627ec745ad4f6c3e4#diff-157c769233d1597c193c4aedfe05a488R34 it worked just fine. It seems like the new Microsoft.NET.Test.Sdk package changed its dependencies or structure and we might need to update the way we're binplacing/adding references:

We might just be missing a reference here: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.CoreFxTesting/build/core/vstest/VSTest.targets#L27

**Comment by safern** [comment]
As a workaround setting `EnableVSTestReferences` in Directory.Build.props to false or passing it as an msbuild property to build and run the tests should unblock this scenario.

**Comment by stephentoub** [comment]
Thanks, @safern.  Doing:
```
dotnet msbuild /t:rebuildandtest /p:TargetGroup=netfx /p:EnableVSTestReferences=false
```
instead of:
```
dotnet msbuild /t:rebuildandtest /p:TargetGroup=netfx
```
worked for me locally as a workaround.

**Comment by jvrdev** [comment]
In my case what did the trick was to upgrade all test projects in the solution from `netcoreapp2.0` to `netcoreapp2.1` after noticing the newer version of `Microsoft.TestPlatform.TestHost` (https://www.nuget.org/packages/Microsoft.TestPlatform.TestHost/16.4.0) depended on .NETCoreApp 2.1 .
