### ISSUE TITLE
QueryEnumerable only accepts expression features prior to Framework version 4.0

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#3607]
Any expression type introduced after 3.5 will fail with an `ArgumentException`:

```C#
[Fact]
public void Block()
{
    Expression block = Expression.Block(
        Expression.Empty(),
        Expression.Constant(Enumerable.Range(0, 2).AsQueryable())
        );
    IQueryable<int> q = _prov.CreateQuery<int>(block);
    Assert.Equal(Enumerable.Range(0, 2), q); // "Unhandled Expression Type: Block"
}
```

Expressions that existed with 3.5, but using features from 4.0 will also fail with an `ArgumentException`:

```C#
[Fact]
public void ExplicitlyTypedConditional()
{
    Expression call = Expression.Call(
        typeof(Queryable),
        "OfType",
        new[] { typeof(long) },
        Expression.Condition(
            Expression.Constant(true),
            Expression.Constant(new long?[] { 2, 3, null, 1 }.AsQueryable()),
            Expression.Constant(Enumerable.Range(0, 3).AsQueryable().Select(i => (long)i)),
            typeof(IQueryable)
            )
        );
    IQueryable<long> q = _prov.CreateQuery<long>(call);
    Assert.Equal(new long[] { 2, 3, 1 }, q); // "Argument types do not match"
}

**Comment by JonHanna** [comment]
Rather than derive from `ExpressionVisitor`, `ExpressionWriter` derives from an internal class much as `ExpressionVisitor` was in 3.5, but not updated for the subsequent changes.

`ExpressionVisitor` depends on virtual generic methods, which were once not working, so that might be a reason why this was once, but is not now, necessary. Is there any other reason? Preliminary work on deriving from it seems to work well, and allows the above to be solved relatively easily.

**Comment by VSadov** [comment]
It could also be to protect preexisting query providers (like Linq to SQL) from unspecified behavior in case they see new nodes.

**Comment by JonHanna** [comment]
It shouldn't really affect other providers, unless maybe one delegates something to this provider, in which case it should gain.
