### ISSUE TITLE
GraphicsPath.AddString - text bounds are clipped

### ISSUE THREAD

**Issue by soualid** [dotnet/corefx#36083]
Probably related to https://github.com/dotnet/corefx/issues/33540.

When using `GraphicsPath.AddString` under Linux, text bounds are clipped when the text is long. The path is truncated when rendered. The same code runs well under Windows (see generated sample images below).

Note that the `Graphics.DrawString` is not affected by this problem, but cannot be used as a workaround when drawing a text with a custom pen is needed.

Short, Self Contained, Correct (Compilable), Example:

```
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.Drawing.Text;
using System.IO;

namespace Repro
{
    public class ReproBitmapIssue
    {
        static void Main(string[] args)
        {
            using (var overlayBitmap = new Bitmap(1080, 1920, PixelFormat.Format32bppArgb))
            {
                var g = Graphics.FromImage(overlayBitmap);
                g.InterpolationMode = InterpolationMode.HighQualityBicubic;
                g.CompositingQuality = CompositingQuality.HighQuality;
                g.SmoothingMode = SmoothingMode.HighQuality;
                g.TextRenderingHint = TextRenderingHint.AntiAlias;

                var p = new GraphicsPath();
                var emSize = 30;
                Point origin = new Point(0, 0);
             
                p.AddString("Testing with a long long long text",
                    new FontFamily(GenericFontFamilies.SansSerif),
                    (int)FontStyle.Regular,
                    emSize * g.DpiY / 72,
                    origin,
                    StringFormat.GenericDefault);

                g.FillPath(Brushes.Black, p);

                var overlayFilename = "test.png";
                using (var fileStream = File.Open(overlayFilename, FileMode.Create, FileAccess.Write))
                {
                    overlayBitmap.Save(fileStream, ImageFormat.Png);
                }
            }
        }
    }
}
```

Linux (clipped): 
![test linux](https://user-images.githubusercontent.com/1830223/54462922-a4024700-4771-11e9-898c-0199d970fcea.png)

Windows (correct): 
![test windows](https://user-images.githubusercontent.com/1830223/54463475-80d89700-4773-11e9-9510-003818af1a79.png)

**Comment by am11** [comment]
Seems like it was fixed by https://github.com/mono/libgdiplus/pull/383, but there hasn't been a new release since (git tag, that has that commit). Meanwhile, we can build from source:

```sh
# ubuntu
apt install -y libtool libjpeg-dev libtiff-dev libcairo2-dev libglib2.0-dev git autoconf

git clone https://github.com/mono/libgdiplus --single-branch --branch master --depth 1
cd libgdiplus
./autogen.sh
make install
```

and `dotnet run` to get:

![image](https://user-images.githubusercontent.com/3840695/54472965-0db63b80-47da-11e9-9b27-6a10f9def0f1.png)


@akoeplinger, are there plans for new release of libgdiplus for .NET Core 3.0?

**Comment by soualid** [comment]
I confirm this bug is fixed on the HEAD of `mono/libgdiplus` (tested under macosx), thanks! Should we keep this ticket open until its release?

**Comment by stephentoub** [comment]
Thanks for confirming.  We don't ship libgdiplus with .NET Core, so it's just a matter of someone having an updated version installed (even if a locally built version).  Given that, I don't think we need to keep this open, as it wouldn't actually be tracking anything.
