### ISSUE TITLE
[Uri] Uri.IsWellFormedUriString() returns false for a URL which is correct

### ISSUE THREAD

**Issue by brijeshb** [dotnet/corefx#36101]
When a url query contains url encoded curly brackets and apostrophe, 
``` Uri.IsWellFormedUriString(DeeplinkUrl, UriKind.Absolute) ``` returns false

The following fail but should pass
https://www.sample.com/?a=%7B%7D&b=%E2%80%99
https://www.sample.com/?a=%7B%7D%E2%80%99

They pass the check when present independent of each other
https://www.sample.com/?b=%E2%80%99
https://www.sample.com/?a=%7B%7D
https://www.sample.com/?a=%7B
https://www.sample.com/?a=%7D

We're using this code in .net core 2.2 runtime, .net standard 2.0 libraries

**Comment by davidsh** [comment]
@rmkerr

**Comment by rmkerr** [comment]
I put together a quick repro for this issue:
```csharp
using System;

class Program
{
    static void Main()
    {
        int i = 0;

        Uri uri = new Uri(@"https://www.sample.com/?a=%7B%7D&b=%E2%80%99"); // a={}&b=’
        Console.WriteLine($"{++i}: {uri.IsWellFormedOriginalString()}");

        uri = new Uri(@"https://www.sample.com/?a=%7B%7D%E2%80%99"); // a={}’
        Console.WriteLine($"{++i}: {uri.IsWellFormedOriginalString()}");

        uri = new Uri(@"https://www.sample.com/?b=%E2%80%99"); // b=’
        Console.WriteLine($"{++i}: {uri.IsWellFormedOriginalString()}");

        uri = new Uri(@"https://www.sample.com/?a=%7B%7D"); // a={}
        Console.WriteLine($"{++i}: {uri.IsWellFormedOriginalString()}");

        uri = new Uri(@"https://www.sample.com/?a=%7B"); // a={
        Console.WriteLine($"{++i}: {uri.IsWellFormedOriginalString()}");

        uri = new Uri(@"https://www.sample.com/?a=%7D"); // a=}
        Console.WriteLine($"{++i}: {uri.IsWellFormedOriginalString()}");
    }
}
```

As described in the original report, these show inconsistent behavior in IsWellFormedOriginalString:
```
1: False
2: False
3: True
4: True
5: True
6: True
```

My best guess here is that we are inconsistently treating these characters as reserved or unreserved depending on the context. An encoded non-reserved character would cause IsWellFormedOriginalString to return false. I'm not sure what the actual status of these characters is though. They're explicitly called out as dangerous in the old URI RFC (1738), but don't seem to be mentioned in 3986.
