### ISSUE TITLE
Evolving EventCounter API

### ISSUE THREAD

**Issue by sywhang** [dotnet/corefx#36129]
## Intro & Rationale

Currently we have implementation for `EventCounter` class which is used to collect metrics like request per second. However the design of this API is not as flexible as it could be, and for different kinds of counters / metrics, the current `EventCounter` API doesn't work very well for various reasons (specific examples detailed below). 

This proposal includes 3 new APIs that are variants of the current `EventCounter` class - namely `PollingCounter`, `IncrementingEventCounter`, and `IncrementingPollingCounter`. 

### EventCounter

Proposing two public surface additions to `EventCounter`:

- `public string DisplayName { get; set; }`

This is a property that will be displayed in the payload for the EventCounter. This is a property a user can set if the user wants a separate field that represents how this counter should be displayed on a viewer, if it is different from the name of this counter. For example, a counter may be instantiated with a name "request-counter", and its `DisplayName` property can be set to "Number of Requests" which would be a more viewer-friendly name. This is useful when trying to create counters that interact with the CLI, where having spaces in the name might cause trouble or confusion for the CLI parser and the user.

- `public void AddMetaData(string key, string value)`

This API adds a key-value pair of "MetaData" to an instance of `EventCounter`. This API exists so that users can add any metadata about their counter that may not be relevant for all `EventCounter` instances. A user can add arbitrary number of metadata to their `EventCounter` instance, and it will be reported as part of the `EventCounter` payload by a comma-separated string. For example, suppose the user wants to categorize his/her counters into different tiers of counters in terms of priority - they can use this API to encode that information into their `EventCounter` instances:

```C#
    anImportantCounter.AddmetaData("priority", "1");
    notAnImportantCounter.AddMetaData("priority", "3");
```

### PollingCounter
```C#
public class PollingCounter {
    public PollingCounter(string name, EventSource eventSource, Func<float> getMetricFunction);
    public string DisplayName { get; set; }
    public void AddMetaData(string key, string value);
}
```

`PollingCounter` is a class that will be used for similar kind of metrics to those that can be represented by `EventCounter`, but it takes in a callback function as a parameter to its constructor, which is used to gather metrics instead of the client having to explicitly call `WriteMetric` - this is what you need to do for instances of `EventCounter`. Explicit calls to `WriteMetric` may not be so nice for certain kinds of metrics because some metrics vary over time in a continuous manner, and it is not always clear at what discrete interval the value needs to be polled and written from the user's side. For example, GC heap size varies over time, but user may not know (and should not be) querying the heap size 15 times a second to keep track of this. `PollingCounter` allows user to get reports on the value without needing to explicitly update the value at an arbitrary time interval of user's choice. 

When the EventSource that the instance of `PollingCounter` is attached to is enabled, it will then call the callback function per every interval it needs to report the values. 

A user who wants to monitor his/her app's GC heap size can create an instance of `PollingCounter` like this:

```C#
    PollingCounter gcHeapCounter = new PollingCounter("GC Heap Size", myEventSource, () => GC.GetTotalMemory(false));
```

A viewer that displays PollingCounter would be able to display a metric for every interval that it requested the samples to be taken (via the `EventCounterIntervalSec` argument).

### IncrementingEventCounter
```C#
public class IncrementingEventCounter {
    public IncrementingEventCounter(string name, EventSource eventSource);
    public string DisplayName { get; set; }
    public TimeSpan DisplayRateTimeScale { get; set; }
    public void Increment(float increment = 1);
    public void AddMetaData(string key, string value);
}
```

`IncrementingEventCounter` is a counter that generates a slightly different metric than `EventCounter`. `EventCounter` reports various statistics per each interval it reports such as min, max, mean, median, and standard deviation. However, for certain values, we might want to capture just the sum of increments over an interval. For example, the number of exceptions thrown is an incrementing value, and we don't want to take an average on the "# of exceptions" thrown per interval because it will be meaningless. What we really want is "how many exceptions were thrown since I last reported that value", and that is what `IncrementingEventCounter` is for.

A counter that keeps track of exceptions that happened in a user's app can be implemented as an `IncrementingEventCounter` like this:

```C#
...
    IncrementingEventCounter exceptionCounter = new IncrementingEventCounter("exception-counter", myEventSource);
...

public void someRoutine()
{
    try
    {
        // some code
    }
    catch (ArgumentException)
    {
    	exceptionCounter.Increment();
    }
}
...

```

`IncrementingEventCounter` reports in its payload the total number of increment that happened since it last reported the value. For example, if `EventCounterIntervalSec` was set to 3 seconds, it would display how many increments happened in the past 3 seconds.

`IncrementingEventCounter` has a public property called `DisplayRateTimeScale` - this can be set if the user wants to specify that this counter should be aggregated at a particular rate. For example, a simple viewer might want to show this counter (# of exceptions) as # of exceptions per second, or per hour. The viewer needs to know a certain timescale that represents the rate at which it should be displayed.

### IncrementingPollingCounter
```C#
public class IncrementingPollingCounter {
    public IncrementingPollingCounter(string name, EventSource eventSource, Func<float> getCountFunction);
    public string DisplayName { get; set; }
    public TimeSpan DisplayRateTimeScale { get; set; }
    public void AddMetaData(string key, string value);
}
```

`IncrementingPollingCounter` is a similar type of counter to `IncrementingEventCounter` in that it aggregates values over an interval, but like `PollingCounter`, it takes in callback function to update the counter value instead of having the user explicitly call `Increment` on it. This allows the flexibility of `PollingCounter` for a metric whose value may change in a continuous manner.

## PRs
https://github.com/dotnet/coreclr/pull/23077 introduced these APIs as internal only. 

 

 cc @vancem @noahfalk @tommcdon @jorive

**Comment by terrajobst** [comment]
* MetaData -> `Metadata`
* `AddMetaData` to `SetMetaData
* Add a `DiagnosticCounter` abstract base
    - Have propected ctor that accepts the name and `EventSource`
    - Add `Name` get-only property
    - Add `EventSource` get-only property
    - Add `DisplayName` get/set property
    - Add abstract `SetMetadata(string key, string value) method
    - All counters, including the existing `EventCounter` should inherit from it
* `getMetricFunction` -> `metricProvider`
* `getCountFunction` -> `totalValueProvider`
* We should consider using `double` instead of `float`

**Comment by sywhang** [comment]
The APIs were exposed via #23808 and all the changes discussed during the API review were implemented.

**Comment by oleh-zheleznyak** [comment]
Hi @sywhang !
Thanks a for doing this work on `EventCounter` - I believe these API extensions are crucial.
Having only `WriteMetric` leaves too much to implement to the user of the API.

It's a huge step forward with new EventCounter APIs, however it feels like good old `PerformanceConter`s had broader functionality still. 
I'm thinking about `PerformanceCounterType`s like `RawBase` and `RawFraction` that allowed to capture metrics like % of cache hits, and the like by simply calling `Increment` or `IncrementBy` on counter and counter base.

Are there any plans to extend the APIs any further? 
Or maybe it's possible to achieve the same functionality by composing the new APIs (and I just don't see it)?

Thank you very much!

**Comment by roji** [comment]
These don't seem to have been added to .NET Standard 2.1 yet, making it difficult for libraries to report them (the rest of EventSource and friends are there). Any plans on making that happen?

/cc @terrajobst

**Comment by sywhang** [comment]
Hi @oleh-zheleznyak, you should be able to compute something like % cache hits with the new counter APIs. The runtime already does it for metrics like % CPU load and % time in GC using `PollingCounter`. As described in the API proposal above, you can pass in a callback function to the constructor that gives the value it should poll for at the interval requested and it should compute the value using the callback function. You can refer to the implementation of RuntimeEventSource here: https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/src/System/Diagnostics/Eventing/RuntimeEventSource.cs

@roji, That problem got our attention about a week ago. There is already a PR open to add these to .NET Standard 2.1 - https://github.com/dotnet/standard/pull/1308. 

HTH :-)

**Comment by roji** [comment]
@sywhang great, should have looked...! I'm guessing we can expect this to go in for preview8 then.
