### ISSUE TITLE
Utf8JsonReader\Writer should support all primitive types

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#36125]
Currently these primitive types are not directly supported and must have custom code to use, such as what the JsonSerializer currently does:

- char (treated as a string of length 1)
- byte
- sbyte
- short
- ushort

cc @ahsonkhan

**Comment by ahsonkhan** [comment]
> float

{Try}GetSingle exists already.

Same with `WriteNumber` with float support.

**New APIs:**
```C#
public ref partial struct Utf8JsonReader
{
    public byte GetByte() { throw null; }
    public sbyte GetSByte() { throw null; }
    public short GetInt16() { throw null; }
    public ushort GetUInt16() { throw null; }
    public bool TryGetByte(out byte value) { throw null; }
    public bool TryGetSByte(out sbyte value) { throw null; }
    public bool TryGetInt16(out short value) { throw null; }
    public bool TryGetUInt16(out ushort value) { throw null; }

    public char GetChar() { throw null; }
    public bool TryGetChar(out char value) { throw null; }
}

public ref partial struct Utf8JsonWriter
{
    public void WriteNumberValue(byte value) { }
    public void WriteNumberValue(sbyte value) { }
    public void WriteNumberValue(short value) { }
    public void WriteNumberValue(ushort value) { }

    public void WriteNumber(System.ReadOnlySpan<byte> utf8PropertyName, byte value, bool escape = true) { }
    public void WriteNumber(System.ReadOnlySpan<byte> utf8PropertyName, sbyte value, bool escape = true) { }
    public void WriteNumber(System.ReadOnlySpan<byte> utf8PropertyName, short value, bool escape = true) { }
    public void WriteNumber(System.ReadOnlySpan<byte> utf8PropertyName, ushort value, bool escape = true) { }
    public void WriteNumber(System.ReadOnlySpan<char> propertyName, byte value, bool escape = true) { }
    public void WriteNumber(System.ReadOnlySpan<char> propertyName, sbyte value, bool escape = true) { }
    public void WriteNumber(System.ReadOnlySpan<char> propertyName, short value, bool escape = true) { }
    public void WriteNumber(System.ReadOnlySpan<char> propertyName, ushort value, bool escape = true) { }
    public void WriteNumber(string propertyName, byte value, bool escape = true) { }
    public void WriteNumber(string propertyName, sbyte value, bool escape = true) { }
    public void WriteNumber(string propertyName, short value, bool escape = true) { }
    public void WriteNumber(string propertyName, ushort value, bool escape = true) { }

    public void WriteString(string propertyName, char value, bool escape = true) { }
    public void WriteString(System.ReadOnlySpan<char> propertyName, char value, bool escape = true) { }
    public void WriteString(System.ReadOnlySpan<byte> utf8PropertyName, char value, bool escape = true) { }
    public void WriteStringValue(char value) { }
}
```

**Open Questions:**
1) {Try}GetChar semantics? Throw/return false if not a single-character? Surrogate pair behavior?
2) WriteStringValue(char) semantics? Write the character as a JSON string surrounded with quotes? Surrogate pair behavior?
3) @bartonjs, should we add similar APIs to `JsonElement` as well?

Related issue:  https://github.com/dotnet/corefx/issues/34690
cc @layomia

**Comment by bartonjs** [comment]
For the writer, these values are already covered by the implicit conversions to int.

I don't know what it means to write a single `char`.  If it's a single-character string, just wrap it in a span and call the span one.

For the reader there's arguably benefit for the Try APIs on the smaller numeric types... I could go either way.  Again, I don't know what it means for `char` (a string whose value is representable with a single UTF-16 code unit?).

**Comment by ahsonkhan** [comment]
> For the writer, these values are already covered by the implicit conversions to int.

> I don't know what it means to write a single `char`.  If it's a single-character string, just wrap it in a span and call the span one.

Agreed. I don't mind removing it from the writer.

> For the reader there's arguably benefit for the Try APIs on the smaller numeric types... I could go either way. 

Yep. I think having it on the reader makes more sense.

> Again, I don't know what it means for `char` (a string whose value is representable with a single UTF-16 code unit?).

I had the same question. @steveharter, any thoughts? Otherwise, we can discuss in the review itself.

**Comment by steveharter** [comment]
The float\single converter in the serializer now uses the appropriate reader API. I'll update the issue.

For `char` a string of length 1 makes the most sense IMO. That is also what Json.NET uses. The work-around for someone to handle this themselves is not trivial.

**Comment by terrajobst** [comment]
The `char` one might be harder to define. We should get @JamesNK input on those. Basically two options:

* **We can treat it as a number**. If the primary goal is to define serialization behavior, that might be OK. And given that we have to write UTF8 that might be more honest.

* **Treat it as a single character string**. This would mean that we either throw for chars that we can't represent in UTF8 or write garbage.

The other ones seem fine.

**Comment by WinCPP** [comment]
@steveharter @ahsonkhan is this something that I can start working on while the conclusion is reached on API for `char`?

In that case I could start with `TryGet*` and `Get*` APIs on `Utf8JsonReader` and `JsonElement` in [comment](https://github.com/dotnet/corefx/issues/36125#issuecomment-474074184) by @ahsonkhan and work on the `Write*` APIs when concluded?

**Comment by ahsonkhan** [comment]
@WinCPP, sound good to me. Assigning to you. Thanks.

**Comment by WinCPP** [comment]
@ahsonkhan I followed the steps given in [updating-ref-source.md](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/updating-ref-source.md) to add new `Get*` and `TryGet*` APIs to `ref` assembly. This generates a lot of changes such as adding `readonly` to some `getters` etc. apart from changing order of some existing APIs. Additionally it introduces following change and adds `DisposeAsync` method. Entire diff is available in this [gist](https://gist.github.com/WinCPP/a1c194ee634bcbc2b91884c8b88edbfe).

```
-    public sealed partial class Utf8JsonWriter : System.IDisposable
+    public sealed partial class Utf8JsonWriter : System.IAsyncDisposable, System.IDisposable
```
```
+        public System.Threading.Tasks.ValueTask DisposeAsync() { throw null; }
```

Looks like the steps in doc are no more being followed? And instead I should directly add the methods by hand? Appreciate your inputs.

**Comment by ahsonkhan** [comment]
> Additionally it introduces following change and adds `DisposeAsync` method.

This is a known limitation and requires a manual change to remove (currently the DisposeAsync API surface is within the manual ref since the API surface is different between platforms).
https://github.com/dotnet/corefx/blob/e175429fc706ae9ef6ab6afd9d746937872d922e/src/System.Text.Json/ref/System.Text.Json.Manual.cs#L12
https://github.com/dotnet/corefx/issues/38349

> This generates a lot of changes such as adding `readonly` to some `getters` etc.

Can you file an issue regarding this? I am not sure if this is expected (maybe related to recent changes like https://github.com/dotnet/arcade/pull/2526).
cc @tannergooding, @ericstj, @safern 

> And instead should I directly add the methods by hand?

Sure, if that's easier. One thing you could do is generate the ref to see the fully qualified API surface and what order they should appear in, undo all the other changes, and manually re-add the APIs. Other than having to deal with some corner cases (for instance where the manual ref file is involved), it should generally work.

**Comment by stephentoub** [comment]
> currently the DisposeAsync API surface is within the manual ref since the API surface is different between platforms

Can we fix that?

**Comment by WinCPP** [comment]
@ahsonkhan Additions for (Try)Get for byte, sbyte, short, ushort are almost ready.
1. IIUC we don't want to do the `Write` APIs. Please confirm.
2. Do we have conclusion on the (Try)GetChar API?
3. I see that JsonDocument doesn't have equivalent `TryGetValue` APIs. (Noticed it when going through changes for #37838). So do we want to have them and if yes, in this issue or in separate issue?

**Comment by ahsonkhan** [comment]
> IIUC we don't want to do the `Write` APIs. Please confirm.

They are not yet needed, and can be added later (especially after some perf validation related to up-casting to a larger numeric type).

> Do we have conclusion on the (Try)GetChar API?

I'll follow up on that and get back to you.

>  I see that JsonDocument doesn't have equivalent `TryGetValue` APIs. (Noticed it when going through changes for #37838). So do we want to have them and if yes, in this issue or in separate issue?

This is the issue. If you look at the API proposal, these APIs need to be added to `JsonElement` as well (not `JsonDocument`).
https://github.com/dotnet/corefx/issues/36125#issuecomment-474074184

**Comment by WinCPP** [comment]
> This is the issue. If you look at the API proposal, these APIs need to be added to `JsonElement` as well (not `JsonDocument`).
> [#36125 (comment)](https://github.com/dotnet/corefx/issues/36125#issuecomment-474074184)

Oops sorry.  How did I miss that :man_facepalming: : Will will on the same.

**Comment by terrajobst** [comment]
We concluded we shouldn't support it unless there is significant customer feedback.

**Comment by ahsonkhan** [comment]
To be clear, the conclusion was we wouldn't support `char` (specifically) for the reader/writer APIs. The previously approved APIs for smaller numeric types has already been checked-in by @WinCPP.
