### ISSUE TITLE
Introduce a JsonExtensionDataAttribute equivalent for System.Text.Json Serialization

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#36147]
Capturing `JsonExtensionDataAttribute` equivalent that was listed in https://github.com/dotnet/corefx/issues/34372.

When a property is annotated with `JsonExtensionDataAttribute`, Json.NET will deserialize any properties that do not have a match in to this collection. 

As @KrzysztofCwalina [notes](https://github.com/dotnet/corefx/issues/34372#issuecomment-455383472),

> An additional thing we would need to support Azure SDK: version resilient serialization, including round-tripping.
> We need to be able to add a property bag field (dictionary) to deserialized types. If deserialized payload has a property that does not exist in the type, the property would be saved in the dictionary. The serializer would serialize not only actual properties of the type, but also the dictionary (so all payload round trips). 

MVC uses [this feature](https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Mvc/Mvc.Core/src/ProblemDetails.cs#L61-L62) as part of it's public API surface, so we'd love for this to be in the initial release. Additionally, libraries that produce API documentation [are specifically aware](https://github.com/RSuter/NJsonSchema/blob/3cf93115a2195b42ab62cb75831515445a465b85/src/NJsonSchema/Generation/JsonSchemaGenerator.cs#L367-L368
) of `JsonExtensionDataAttribute`. Once System.Text.Json lands this feature, 3rd party libraries should be to determine what properties are treated as extension data properties. Json.NET uses an attribute, and data contract serialization [uses an interface](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/forward-compatible-data-contracts).

**Comment by ahsonkhan** [comment]
Related/duplicate issue: https://github.com/dotnet/corefx/issues/37558
