### ISSUE TITLE
System.ComponentModel.Primitives breaks MSBuild up-to-date check

### ISSUE THREAD

**Issue by tfabraham** [dotnet/corefx#36154]
The presence of the System.ComponentModel.Primitives package 4.1 or 4.3 in a .NET 4.x project breaks up-to-date checking and causes the project to build on every solution/project build vs. skipping as up-to-date.

To reproduce with VS 2017 15.9.9:
1) Create a new .NET Framework class library project (I used 4.7.2)
2) Add System.ComponentModel.Primitives 4.1 or 4.3

The project will never show as up-to-date and will always build.

The problem does **not** occur with System.ComponentModel.Primitives 4.0.

**Comment by danmosemsft** [comment]
@tfabraham can you look at a detailed build log and find the earliest point that suggests why it's not skipping? Maybe attach the log, if you anonymize anything in it you don't want to share.

**Comment by ericstj** [comment]
Let's try a local repro.  If this is an issue it's likely in the SDK or NuGet.  That package doesn't provide targets or anything that might break incremental build.

**Comment by ericstj** [comment]
I gave this a try and it did not reproduce for me.  Here's what I see upon second build:
```
========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
```


If you can make it reproduce  please reactivate this issue and provide either an msbuild binary log or a repro project.
