### ISSUE TITLE
Clean builds failing

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#36155]
Doing:
```
git clean -xdf
build.cmd
```
on an up-to-date repo fails locally for me with this error:
```
D:\repos\corefx\external\test-runtime\XUnit.Runtime.depproj(211,5): error : Error: no assets for test sdk package where found under: C:\Users\stoub\.nuget\packages\microsoft.net.test.sdk\16.0.1\build\netcoreapp1.0\*.*
```
https://github.com/dotnet/corefx/pull/36082/files#diff-841e9e59d27acec708f2c73eaa3cf6a0R212

@ericstj highlighted that it can be worked around by adding `/p:EnableVSTestReferences=false` to the build.

cc: @safern

**Comment by ericstj** [comment]
You may need to delete .nuget\packages too.  It's possible that restore is finding the microsoft.net.test.sdk package in a machine-wide fallback folder so the path constructed using $(PackagesDir) is wrong.

**Comment by safern** [comment]
The condition to the error I added on the PR is wrong, I used `!=` instead of `==` -- I'll send a PR shortly.
