### ISSUE TITLE
[release/2.1.0] FileFormatException when opening a Package with over 4GB file on desktop

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#36156]
Release 2.1 version of #36013, #24457.

The scenario is to create System.IO.Packaging packages which contain files over 4GB and can be exchanged with desktop System.IO.Packaging.  Today there were 3 bugs blocking this scenario.

Fix is needed by partner who's ship schedule cannot wait for .NETCore 3.0.

Here are the fixes in master.
https://github.com/dotnet/corefx/pull/36027
https://github.com/dotnet/corefx/pull/35660
https://github.com/dotnet/corefx/pull/35763

**Comment by ericstj** [comment]
@pensivebrian do you still need this for 2.1?  My understanding was you had a workaround.  If we need this for 2.1 we're going to have go through MS Support rather than github.

**Comment by pensivebrian** [comment]
I have a workaround so this isn't needed. Thanks!
