### ISSUE TITLE
Path.GetFileName returns an empty string if input starts with two slashes "//"

### ISSUE THREAD

**Issue by xPaw** [dotnet/corefx#36151]
I am porting a library to .NET Core and one of the tests started failing.

What's strange is that it only happens when running the code in Visual Studio (both 2017 and 2019 Preview)

> Microsoft Visual Studio Community 2019 Preview Version 16.0.0 Preview 4.2
> C# Tools   3.0.0-beta4-19156-04+7d31dd6ee3fdc2c556345d36a5ab4fd6f9318803

These return an empty string:
```csharp
Path.GetFileName("//kitten.jpg")
Path.GetFileNameWithoutExtension("//kitten.jpg")
```

Am I missing something obvious here? This did not happen on .NET Framework.

**Comment by stephentoub** [comment]
cc: @JeremyKuhne

**Comment by JeremyKuhne** [comment]
This is an expected change as we honor the root correctly now in Core. On Windows anything that begins with a double slash is considered "special". The specihsal falls into three buckets (in priority order):

1. Starts with `\\?\` exactly- skips all normalization and length checks, goes straight to internal NT apis
2. Starts with two slashes (forward or backward) and a period or question mark, then another slash- considered device path, current working directory is ignored
3. Starts with two slashes (forward or backward) - considered a UNC

You can see this behavior by typing `dir "//localhost/c$"` at a cmd prompt then trying to do the same with your path.

**Comment by xPaw** [comment]
When did this change happen? When I tried in CLI using dotnet 2.1.601, it still returned the string.

This change is somewhat breaking for me because I use `GetFileName` on strings that will not touch the actual file system. I'm using it on a custom archive format, so the file list is in memory.

**Comment by JeremyKuhne** [comment]
> When did this change happen?

We made all of our path handling changes in the original release of [Core 2.1](https://blogs.msdn.microsoft.com/jeremykuhne/2018/03/08/system-io-in-net-core-2-1-sneak-peek/). We haven't made any changes since then.

> Why does it consider forward slashes an UNC?

Slashes have always been treated identically by DOS/Windows. The full history is [here](https://blogs.msdn.microsoft.com/larryosterman/2005/06/24/why-is-the-dos-path-character/).

**Comment by xPaw** [comment]
So why doesn't it return an empty string for me when I do `dotnet run` in console both on Windows or Linux? Both use 2.1.

**Comment by JeremyKuhne** [comment]
> So why doesn't it return an empty string for me when I do dotnet run in console both on Windows or Linux? Both use 2.1.

I'm not sure. I don't see any issues myself- if I change the project target framework and rerun `dotnet run` I see the expected behavior on each target (2.0, 2.1, 2.2, 3.0).

Note that Unix has no concept of UNCs so you won't see special treatment for these.

**Comment by MgSam** [comment]
Is the bar for breaking changes in .NET a lot lower than it used to be? File parsing code is some of the most finicky and brittle code around- I actually find it shocking you guys decided to take breaking changes in NET Core 2.1 against such common behavior that has existed since .NET Framework 1.0.

**Comment by JeremyKuhne** [comment]
> Is the bar for breaking changes in .NET a lot lower than it used to be? 

It is lower. https://devblogs.microsoft.com/dotnet/update-on-net-core-3-0-and-net-framework-4-8/ discusses this a bit and even brings up the example of file enumeration changes.

With the `Path` APIs we made [a number of changes](https://blogs.msdn.microsoft.com/jeremykuhne/2018/03/08/system-io-in-net-core-2-1-sneak-peek/). We did our best to keep breaks as constrained as possible while establishing a more consistent and usable baseline for the future. Calls like this work the way they should now (i.e. consistently):

``` C#
    Console.WriteLine(Path.GetFileName(@"C:\"));
    Console.WriteLine(Path.GetFileName(@"C:\foo"));
    Console.WriteLine(Path.GetFileName(@"\\?\"));
    Console.WriteLine(Path.GetFileName(@"\\?\foo"));
    Console.WriteLine(Path.GetFileName(@"\\?\C:\foo"));
    Console.WriteLine(Path.GetFileName(@"\\foo"));
    Console.WriteLine(Path.GetFileName(@"\\server\foo"));
    Console.WriteLine(Path.GetFileName(@"\\server\share\foo"));
```

I spent over a dozen years beating on this problem space trying to understand the nuances and find changes that would both fix as much as possible and break as little as possible. I'm fully aware that the changes are breaking, but the hope is that those breaks are reasonably constrained and that the benefits significantly outweigh them. Time, of course, will be the ultimate judge. :)

Note that we have added new APIs to try and make path manipulation a bit easier / more predictable:

https://docs.microsoft.com/en-us/dotnet/api/system.io.path.join
https://docs.microsoft.com/en-us/dotnet/api/system.io.path.ispathfullyqualified
https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getfullpath?view=netcore-2.2#System_IO_Path_GetFullPath_System_String_System_String_

I'd love more feedback on additional APIs that we could add that would make path analysis/manipulation easier. One thing I've been thinking of are simpler APIs for looking at path segments. `GetLastSegment`, `EnumerateSegments`, `TrimLastSegment`, etc. would allow "non-contextual" manipulation much like `Path.Join` does for `Path.Combine` (notably that they would be simple string manipulation routines that don't consider roots). `NormalizeSeparators` is another thing I want to do. Community feedback/involvement helps me to justify new APIs to API review and also helps me justify allocating time to making them happen.

**Comment by JeremyKuhne** [comment]
If there are any other questions we can reopen this.
