### ISSUE TITLE
Fix Serbian date formats

### ISSUE THREAD

**Issue by tarekgh** [dotnet/corefx#3616]
In the following cultures 

sr-Cyrl-XK
sr-Latn-ME
sr-Latn-RS
sr-Latn-XK

it has wrong date pattern as "d. M. yyyy.". the CLDR don't include spaces. the problem with that is parser get confused between the date and the time separator and fail parse these dates. 
these cultures has time pattern as hh.mm.ss. so we'll have date separator as ". " and time separator as ".". 

The fix is we need to remove the spaces in the date pattern to allow the parser detect such special cases and work. if we cannot fix the format then we'll need to work around this in the parser but this comes with the regression risk.

**Comment by tarekgh** [comment]
@eerhardt please have a look and let me know if you can fix it in the data we read from Linux if not I'll try to look at fixing it in the parser.

**Comment by ellismg** [comment]
Some CLDR data has spaces in it (see http://www.unicode.org/repos/cldr-aux/charts/24/summary/sr.html).  Am I looking at the wrong data?

**Comment by tarekgh** [comment]
@ellismg 

look at  the following links:
http://demo.icu-project.org/icu-bin/locexp?d_=en&_=sr_Cyrl_XK
http://demo.icu-project.org/icu-bin/locexp?d_=en&_=sr_Latn_ME
http://demo.icu-project.org/icu-bin/locexp?d_=en&_=sr_Latn_RS
http://demo.icu-project.org/icu-bin/locexp?d_=en&_=sr_Latn_XK

you'll find:
      Short Date d.M.yy. 5.10.15. 

Also can download the raw CLDR data from http://www.unicode.org/Public/cldr/28/core.zip and open the file main/sr.xml and you'll find 
    <dateFormatLength type="short">
	<dateFormat>
		<pattern>d.M.yy.</pattern>
	</dateFormat>
    </dateFormatLength>
