### ISSUE TITLE
Provide convenience APIs to go from JsonElement to .NET objects

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#36169]
The `JToken` family of types in Json.NET has convenience APIs to convert to a .NET object. This scenario is particularly useful in combination with https://github.com/dotnet/corefx/issues/36166 when the target type cannot be inferred.

Consider:

```C#
var array = JsonSerializer.Parse<object[]>("[1, false]"));
```

Currently this fails (https://github.com/dotnet/corefx/issues/36167), however, assuming this works, it's less obvious, what the serializer would do if it encounters a complex type.

 ```C#
var array = JsonSerializer.Parse<object[]>("[1, false, { name : \"Person\" }]"));
```

Json.NET solves this by using `JArray` and `JObject` when it encounters a type it cannot deserialize without knowing more details. In tandem with the convenience APIs, the user then has the flexibility to further convert this type.

**Comment by pranavkm** [comment]
cc @JamesNK

**Comment by steveharter** [comment]
This is not yet supported by design. The plan is to deserialize "object" into JsonElement from this [feature](https://github.com/dotnet/corefx/issues/36148). We will then likely add an extension method to JsonSerializer (or JsonSerializerOptions) to convert a JsonElement into the provided <T> using the registered converters.

**Comment by steveharter** [comment]
Closing this per the feature link above.

**Comment by steveharter** [comment]
@JeremyKuhne do we have a feature issue for the JsonElement work? If so, please close this. Thanks

**Comment by JeremyKuhne** [comment]
This is supported now.
