### ISSUE TITLE
JsonSerializer error message for type mismatch is confusing

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#36168]
```C#
var content = "1";
var deserialized = JsonSerializer.Parse<string>(content);
Console.WriteLine(deserialized);
```

This fails<sup>[1]</sup> , however the error message isn't meaningful:

> System.Text.Json.JsonReaderException: The JSON value from [System.String] could not be converted to System.String.

-----------------------------------

[1] - The equivalent code works with Json.NET:  `Newtonsoft.Json.JsonConvert.DeserializeObject<string>(content)` succeeds

**Comment by BrennanConroy** [comment]
Similarly when passing a double "13.143" and expecting an `Int32` the error message is "System.Text.Json.JsonReaderException: The JSON value from [System.Int32] could not be converted to System.Int32.".

The `Utf8JsonReader`s exception looks like "The JSON value is either of incorrect numeric format, or too large or too small for an Int32."

**Comment by steveharter** [comment]
Note that the serializer will not try to auto-convert like Json.NET. However yes the message should be improved to closer match the reader.

**Comment by Anipik** [comment]
@steveharter the exception message will change here after your converter change goes in ?

**Comment by ahsonkhan** [comment]
@Anipik, are you working on this issue for the 6/26 target?

**Comment by steveharter** [comment]
> @steveharter the exception message will change here after your converter change goes in ?

No. However, due to JsonPATH changes the message is now:

```The JSON value could not be converted to System.String. Path: $ | LineNumber: 0 | BytePositionInLine: 1.```

IMO this is acceptable.

**Comment by steveharter** [comment]
Recommend closing or Future.

**Comment by Anipik** [comment]
Yeah I also think that we could just close this one .
