### ISSUE TITLE
ConfigurationManager do not load AppSettings from EnvironmentVariables under Net Core, does under NetFramework

### ISSUE THREAD

**Issue by MarcoGix** [dotnet/corefx#36178]
Good morning to all,

I have an issue using ConfigurationManager in NetCore in Azure WebApps.

Azure WebApps provides configuration settings setted in the Azure Portal as EnvironmentVariables with the convention APPSETTINGS_{key}={value}

This kind of usage is supported by NetFramework (461 for sure, dunno if also olders) and if I run the project targeting 461 it works just fine. When I target netcoreapp2.2 it does load App.Config settings but doesn't load setting configured via EnvironmentVariables.

We've a lot of projects that we'd like to migrate to NetCore but still using the static ConfigurationManager in AzureWebApps. I
s this a bug, or is a missing feature?

**Comment by ericstj** [comment]
@JeremyKuhne is this something ConfigurationManager did or was it an ASP.Net host thing?

**Comment by JeremyKuhne** [comment]
Hmm- I didn't see any code to this effect in System.Configuration when I ported it. @MarcoGix can you please give some concrete setting examples?

**Comment by MarcoGix** [comment]
You can replicate it creating a new Azure WebApp and deploying a simple triggered webjob that lists the ConfigurationManager keys. 

The values you set in the Configuration setting of the WebApp are available in the ConfigurationManager if you target net46 but not if you target netcoreapp.

You can use the following code sample, compile/publish as run.exe
and upload into app_data/webjobs/triggered/Foo folder and trigger it from the WebApp panel.

https://github.com/projectkudu/kudu/wiki/WebJobs

```
       static void Main(string[] args)
        {
            Console.WriteLine($"==AppSettings==");
            foreach (var i in ConfigurationManager.AppSettings.AllKeys)
                Console.WriteLine($"Key:{i} Value:{ConfigurationManager.AppSettings[i]}");

            Console.WriteLine($"==ConnStrings==");
            foreach (ConnectionStringSettings i in ConfigurationManager.ConnectionStrings)
                Console.WriteLine($"Name:{i.Name} Value:{i.ConnectionString}");
        }
```

I'm not sure which magic Kudu uses to make it happen, if any. Our side we only change the targetFramework.

**Comment by maryamariyan** [comment]
@MarcoGix this link explains the equivalent workflow for .NET Core: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?view=aspnetcore-2.2

Hope this helps.
