### ISSUE TITLE
ProjectNTfs dependency is not auto-updated

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#36186]
The last auto-update was in February. I am doing manual one as part of https://github.com/dotnet/corefx/pull/36172.

**Comment by jkotas** [comment]
@ViktorHofer Do you happen to know where to look to get this fixed?

**Comment by ViktorHofer** [comment]
cc @ericstj

**Comment by ericstj** [comment]
@dagood where can we go to investigate this?  When I yanked buildtools I manually plumbed versiontools back in.  I tested a couple targets and confirmed they worked but it might not have been sufficient for what get's called in the maestro v1 PRs.  I suspect there's a build somewhere that's failing when trying to prep a PR.

**Comment by ericstj** [comment]
Also, may make more sense to just wait till I pick up the new versiontools from arcade.  That'll be less of a hack.  Was blocked on that due to arcade breaking changes up until this morning.

**Comment by dagood** [comment]
First, check out which action the subscription is: https://github.com/dotnet/versions/blob/fff00830cfa4d8d1fc4ec39b249999d3457a0f6f/Maestro/subscriptions.json#L448-L460

Go to the `corefx-general` action to find the def: https://github.com/dotnet/versions/blob/fff00830cfa4d8d1fc4ec39b249999d3457a0f6f/Maestro/subscriptions.json#L16-L20

Assemble the URL: https://devdiv.visualstudio.com/DevDiv/_build?definitionId=1084

Yeah, it's been failing a lot, e.g. https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2516169

```
MSBUILD : error MSB1001: Unknown switch.
Switch: -inittools
```

**Comment by ViktorHofer** [comment]
Thanks @dagood. I just took a quick look and seems like I don't have enough permission to see which script is executed (can't see the variable group) or if it's an inline script, what the arguments are. Can you help?

**Comment by dagood** [comment]
Interesting... do you see an option to "View queue time variables" in the `...` menu at the top right?

But, the subscription has that info: https://github.com/dotnet/versions/blob/fff00830cfa4d8d1fc4ec39b249999d3457a0f6f/Maestro/subscriptions.json#L465-L476

The script is this:

https://github.com/dotnet/corefx/blob/d9dcfc5ab3c5bda9fe211699d5bde7df8c5fe6d5/eng/update-dependencies.cmd#L1-L4

Looks like the option was removed in https://github.com/dotnet/corefx/commit/a619534cac9b7d000f0899248656d232cb44f61f?

**Comment by ViktorHofer** [comment]
Thanks a lot. I just fixed that directly: https://github.com/dotnet/corefx/commit/922492558648039b520d40941966486921a8da19.

**Comment by dagood** [comment]
Nice, no problem. If you want to try running the def manually to validate (and get any other missed updates current), it looks like queueing a new build with the arg names + values from the failed build's queue time variables dialog would do it.

**Comment by ViktorHofer** [comment]
Thanks, I'll just wait :)

**Comment by safern** [comment]
I queued a build manually just to verify it is fixed: 

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2518041

It seems to be working, it opened:
https://github.com/dotnet/corefx/pull/36215

**Comment by ViktorHofer** [comment]
impatient 😂

**Comment by safern** [comment]
🤣 😄
