### ISSUE TITLE
CMD refuses to get inputs longer than a certain length with Console.ReadLine()

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/corefx#36188]
Operating System: Windows 10 Home x64, Korean Build 17763.379
Runtime used: .NET Framework 4.7.2, .NET Core 3.0 Preview

when using Console.ReadLine, the CMD refuses to read inputs over a certain length; For example, `Console.ReadLine()` without anything done previously refuses to read over 254 characters (the input cuts off after that point). Well-known workarounds for this is to do `Console.SetIn(new StreamReader(Console.OpenStandardInput(8192)))`, however, per [comments on the OpenStandardInput method](https://github.com/dotnet/corefx/blob/1caac52208d277ce673e17bc0069ded9b9fcb4c2/src/System.Console/src/System/Console.cs#L360) the bufferSize is ignored, and although this kind of works, it only extends that limit to 1022 characters which still isn't a whole lot. 

According to the [MS Support page](https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation) about the topic, the max input supported by CMD is 8191 on XP+, and some websites suggest that it's extended to 32767 on 7+. I was able to go up to 4095 when I did something similar with C++. (Still not reaching that limit, however bigger than the limit with .NET)

Is this done intentionally, or is it a bug / system limitation? Would there be any workarounds to this?

**Comment by stephentoub** [comment]
> however, per comments on the OpenStandardInput method the bufferSize is ignored, and although this kind of works, it only extends that limit to 1022 characters which still isn't a whole lot.

Try this:
```C#
const int BufferSize = …;
Console.SetIn(new StreamReader(Console.OpenStandardInput(), Encoding.UTF8, false, BufferSize));
```
where BufferSize is whatever you want it to be.

> Is this done intentionally, or is it a bug / system limitation?

The default cmd console mode is "ENABLE_LINE_INPUT", which means that when code issues a ::ReadFile call against stdin, ::ReadFile doesn't return to the caller until it encounters a carriage return.  But the call to ReadFile only has a limited size buffer that was passed to it.  Which means that cmd looks at the buffer size provided to it, and determines based on that how many characters long the line can be... if the line were longer, it wouldn't be able to store all the data into the buffer.

So, there's a fixed limit based on how big a buffer the calling code passes in.  System.Console initializes `In` to be a StreamReader constructed with a 256-character buffer:
https://github.com/dotnet/corefx/blob/a6f76f4f620cbe74821c6445af3f13e048361658/src/System.Console/src/System/ConsolePal.Windows.cs#L182
which means that's the buffer StreamReader passes off to ::ReadFile, which means that's the limit on the line length.  The "Try this" example above creates a StreamReader with whatever size, which means that's the size buffer passed off to ::ReadFile, and hence the line limit.

I don't think there's much that can be done here in Console, other than deciding on a different fixed buffer size if a larger one is desired.

cc: @wtgodbe

**Comment by Gnbrkm41** [comment]
Totally forgot about setting the stream buffer size explicitly. 🤦‍♂️ I see. That seems reasonable to me.

Feel free to close the issue as you want. Thanks for the help!

As a completely unrelated side note, Shouldn't this comment be updated? https://github.com/dotnet/corefx/blob/a6f76f4f620cbe74821c6445af3f13e048361658/src/System.Console/src/System/ConsolePal.Windows.cs#L15

The `DefaultBufferSize` const seems to have changed since when the code was originally written. The value is now 1024. Not completely sure if the default value of `Console.In` should change as well but the comment definitely should be removed I think.
https://github.com/dotnet/coreclr/blob/69dc790d171783584f5af3a5da60a25e2c301899/src/System.Private.CoreLib/shared/System/IO/StreamWriter.cs#L25
