### ISSUE TITLE
CookieContainer storing cookies with a space in the name

### ISSUE THREAD

**Issue by PaitoAnderson** [dotnet/corefx#36189]
We're dealing with a website that requires a space in the cookie name, and I'm not able to store it in the CookieContainer, is this something you would consider changing to match browsers?

<img width="676" alt="Screen Shot 2019-03-20 at 2 36 40 PM" src="https://user-images.githubusercontent.com/4108718/54710292-b8ea2c00-4b1d-11e9-8f39-e221968b9c7b.png">

```cs
var cookieContainer = new CookieContainer();
cookieContainer.Add(new Cookie
{
    Value = "Value",
    Name = "White Space",
    Domain = "microsoft.com",
    HttpOnly = true
});
```

**Comment by davidsh** [comment]
>We're dealing with a website that requires a space in the cookie name

None of the cookie RFCs allows a space character in the cookie name.  The website appears to be violating the specification.

See: [RFC 6265](https://www.ietf.org/rfc/rfc6265.txt)
```
4.1.1.  Syntax
   Informally, the Set-Cookie response header contains the header name
   "Set-Cookie" followed by a ":" and a cookie.  Each cookie begins with
   a name-value-pair, followed by zero or more attribute-value pairs.
   Servers SHOULD NOT send Set-Cookie headers that fail to conform to
   the following grammar:

 set-cookie-header = "Set-Cookie:" SP set-cookie-string
 set-cookie-string = cookie-pair *( ";" SP cookie-av )
 cookie-pair       = cookie-name "=" cookie-value
 cookie-name       = token
 cookie-value      = *cookie-octet / ( DQUOTE *cookie-octet DQUOTE )
 cookie-octet      = %x21 / %x23-2B / %x2D-3A / %x3C-5B / %x5D-7E
                       ; US-ASCII characters excluding CTLs,
                       ; whitespace DQUOTE, comma, semicolon,
                       ; and backslash
 token             = <token, defined in [RFC2616], Section 2.2>
```

And [RFC 2616](https://www.ietf.org/rfc/rfc2616.txt) doesn't allow a space character (SP) inside a token.

```
       token          = 1*<any CHAR except CTLs or separators>
       separators     = "(" | ")" | "<" | ">" | "@"
                      | "," | ";" | ":" | "\" | <">
                      | "/" | "[" | "]" | "?" | "="
                      | "{" | "}" | SP | HT
```

**Comment by davidsh** [comment]
@geoffkizer @stephentoub

**Comment by karelz** [comment]
If it is not allowed in RFCs, I suggest to close it, unless we have evidence that it is widely used pattern.

**Comment by PaitoAnderson** [comment]
Thanks for your replies, I fully understand if you don't want to implement this as it is violating the standards.

It does however appear every major browser supports this (really wish they didn't!) I just unscientifically looked at the 3000 odd cookies on my machine and found three sites that placed cookies with spaces in the name so there is some use of this pattern.

https://ca.subzero-wolf.com/ (cookies called `_sdsat_Logged In` and `_sdsat_User Agent String`)
https://www.telus.com/ (cookies called `_sdsat_user: uuid`, `_sdsat_user: registrationStatus`, and `_sdsat_user: banType`)
https://lms.ryder.com/ (cookie called `Ryder Portal`)

**Comment by karelz** [comment]
If all browsers support it and there are multiple sites, then I'd be fine supporting that too in .NET Core.
It won't be a priority for us though ...

Assuming it should be medium complex, marking as up-for-grabs
