### ISSUE TITLE
macOS: undocumented errorCode for IOException thrown on FileInfo(path).Open(FileMode.Open)

### ISSUE THREAD

**Issue by jpfreyen** [dotnet/corefx#36195]
# Issue Title

macOS: undocumented errorCode for IOException thrown on FileInfo(path).Open(FileMode.Open)

# General

Environment: MacOS Mojave 14.3
.NetCoreApp-v2.1

when using FileInfo(pathname).Open(FileMode.Open)) and an IOException is thrown, errorCode reported is 35 regardless if Marshal.GetHRForException(e) or e.HResult is used to retrieve the error code.  error code 35 is undocumented in your documentation:

https://docs.microsoft.com/en-us/windows/desktop/debug/system-error-codes--0-499-

The mono implementation .NETFoundation 462 does the more correct thing and report an error code 32.  This error code is reasonable error for the situation in a macOS environment (process can't be shared because it's being used by another process).

BUT if 35 is actually the right error code, Microsoft needs to document this as its undocumented.

Sample code:

``` .    // macOS Mojave 14.3
             try
             {
                using (new FileInfo(Path.GetTempFileName()).Open(FileMode.Open))
                 {
                     return false;
                 }
             }
             catch (IOException e)
             {
                 // mono .NETFramework 462 is value 32, .NETCore-v2.1 is 35
                    var errorCode = Marshal.GetHRForException(e) & ((1 << 16) - 1);
                 
                 // .NETCore-v2.1 value is 35, mono .NETFramework 462 is some huge negative number
                var errorCode2 = e.HResult;

             }
```

**Comment by jpfreyen** [comment]
Also, just discovered, if this is run under Linux Centos7.6, errorCode will be 11, Bad Format, which makes no sense at all.

I'd rather just see errno values for the 'NIX OS's than this Windows errorCode stuff if this is too unreliable.

**Comment by JeremyKuhne** [comment]
Can you share detailed exception info and a stack trace? Exceptions that are derived from `IOException` (such as `FileNotFoundException`) are hard coded to a specific HResult. Anything we can't categorize and throw as a top level `IOException` just gets the native errno: https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/Interop/Unix/Interop.IOErrors.cs#L112

**Comment by jpfreyen** [comment]
I will see if I can get that for you or give a sample example without risking IP from my employer.

But one thing I notice looking at the link you provided, why isn't Error.EIO there?  That is the fundamental "I/O error" in Linux, and I would have thought EIO == EIOException are about as equivalent as it comes between different machine platforms.

**Comment by jpfreyen** [comment]
Here is detailed exception info.  Sorry I can't give the stack trace from the actual failure but I'll see if I can reproduce it as this is being caused in a unit test.

![Screen Shot 2019-03-21 at 4 17 46 PM](https://user-images.githubusercontent.com/10945795/54790867-efdf4100-4bf4-11e9-900f-6014ecb86fb0.png)

**Comment by danmosemsft** [comment]
Presumably if we do https://github.com/dotnet/corefx/issues/34221 you would be glad to use that? instead of the native error code, which sometimes is OS specific, sometimes faux- Windows, and not sure about this case.

**Comment by jpfreyen** [comment]
Let me think about that after reading that carefully.

But for now, I've reproduced this in a simple example environment so I'm zipping the project up for your use.  Get yourself a macOS environment (I run Mojave) and a Linux environment (I'm running Fedora 28).  Note, I also use Rider IDE because it's the exact same GUI interface across all 3 OS's.  In this snapshot I'm running the debugger to show that I'm getting errorCode 35.  This example project is using .NETCore 2.2.

![Screen Shot 2019-03-22 at 11 47 59 AM](https://user-images.githubusercontent.com/10945795/54846408-00e18e00-4c99-11e9-94b2-ba29eda4d000.png)

[forMsft.tar.gz](https://github.com/dotnet/corefx/files/2997889/forMsft.tar.gz)

**Comment by JeremyKuhne** [comment]
According to your string, you're hitting this case (`EWOULDBLOCK`): https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/Interop/Unix/Interop.IOErrors.cs#L145

On Mac it is defined the same as `EAGAIN` (35), which is **11** on Linux so that makes some sense to me.

**Comment by jpfreyen** [comment]
OK, so it's a bit confusing that would be reported as 32 on both mono .NETFramework 462 implementation and 32 on Windows (.NETFramework, .NETCore), which I actually deem correct.  And that is what is really throwing me off.  What is worse is that to me, it's hard to know what values I should be expecting based on the Microsoft .NET documentation.  I'm a Linux guy, but as a .NETCore standard, your documentation leads me to expect that 35 is undocumented and 11 means BAD_FORMAT, and there is really nothing for me to expect otherwise than when reading this:

https://docs.microsoft.com/en-us/windows/desktop/debug/system-error-codes--0-499-

_the HResult values should **always** be values from that URL above, no exceptions._

I looked over https://github.com/dotnet/corefx/issues/34221 (it's a long thread).  I think the solution to make this platform independent and satisfy everyone using .NETCore is as follows (some of it is highlighted in 34221):

1. Do what mono does, base HResult on https://docs.microsoft.com/en-us/windows/desktop/debug/system-error-codes--0-499-.  Mono already has an install base for non-Windows OS's using .NET in industry so .NETCore should not be having HResult doing something different with respect to mono (unless there is an obvious bug). 
2. throw more detailed exceptions for the overloaded IOException as .NET is an exception diagnosing paradigm  
3. have a new variable, call it Errno which is easily recognizable, that contains a valid error value if the OS .NETCore is running on is **NOT** Windows. Basically, if a Windows machine tries to read errno, throw a "NotSupportedInOSException" (something like that).  That will satisfy hard core 'NIX people who may only be targeting one OS (like Linux) and want that error code info native to the OS.

I think 1. and 3. would be sufficient, 2. if it fancy's your imagination

**Comment by danmosemsft** [comment]
@jpfreyen why would #34221 (the enum) not be sufficient for you? Error codes aren't fun to deal with anyway, even if we do consistently return them from the platform (or conversely, consistently unify them to Windows equivalents)

**Comment by jpfreyen** [comment]
I think you are refering to this?:

> I don't think we want to change what the value of HResult is; even if we pick the existing Win32 values (which is rather limiting and do not necessarily match to sufficient distinct causes) that would break anyone expecting the Unix code today. Plus, it's a poor name for a cross platform code. On top of that, it's weakly typed as int rather than a nice enum.
> 
> This would require an API proposal:
> 
> to add a property to IOException named perhaps Error or IOError (I think FileSystemError is a poor choice as, at least on Windows, it did not necessarily originate with a file system operation.). It would have the type of the enum in 2.
> 
> to add a new enumeration named eg IOError and populate it with several useful entries perhaps based on my analysis above. We do not need to think of them all now, it's not a breaking change to add more later, but it would need a (brief) review so better to do it now.

I disagree with HResult conclusion, that is if you are referring to how HResult works today in .NETCore.  It should follow your documentation, which is what mono interpreted, which is the same as how it works on Windows machines in .NETFramework.  mono has been out for 14 years, it has a longer time for a UNIX install base today than .NETCore.  .NETCore should not change this behavior no matter what OS its run on.  Microsoft supports both mono and .NETCore, HResult is kind-of fundamental universal behavior, its easy to access under the exception, and it's of Microsoft's interest to keep this the same for portability-universal-sake.  Thus, what I am experiencing is a bug and compatibility breakage.  And it kind of sounds like people like @arunjvs would agree with me.

For 1. and 2., I don't see how it would be more useful for people targeting .NETCore on 'NIX systems than say, just an Errno field, which is pretty understandable and universal in the non-Windows OS world.  And for Windows, if HResult works reliably and is accurate and effort is made to make it so,  I'm not sure what is gained by adding a new IOError field that will have enumerations of common cases within IOException.  Yes, it may be easier to read but you are not going to capture everything, it seems like it is just fixing a subset of the problem and may add to more confusion IOError's use overall. I do think just adding a few more IOException subclasses would be less work and could help a bit, some you highlighted (DirectoryAlreadyExistsException, FileAlreadyExistsException, DirectoryNotEmptyException, UnauthorizedIOException, then my error ProcessSharingException). would be low hanging fruit.

**Comment by danmosemsft** [comment]
>For 1. and 2., I don't see how it would be more useful for people targeting .NETCore on 'NIX systems than say, just an Errno field, which is pretty understandable and universal in the non-Windows OS world. And for Windows, if HResult works reliably and is accurate and effort is made to make it so, I'm not sure what is gained by adding a new IOError field that will have enumerations of common cases within IOException. 

@jpfreyen it makes it easier to write libraries that are intended to work cross platform in a strongly typed way, without guessing which of the 100's of error codes you may need to handle - even assuming we successfully use Windows error codes on all platforms (which I am not actually sure is a goal). The argument for an enumeration vs. subtypes is already covered in #34221.

**Comment by jpfreyen** [comment]
@danmosemsft, then why doesn't HResult work in .NETCore the way you just said- cross platform? mono's .NET implementation implements HResult as a universal cross-platform solution, whereas HResult can throw error values based on other OS's and as a result is not functioning cross-platform.  Again, there is multi-year old existing code bases out there not implemented on Windows solutions that are depending on HResult to work in a cross-platform way and in the spirit of mono's implementation.

**Comment by danmosemsft** [comment]
@stephentoub, thoughts, was it a goal to consistently use hresult on all platforms instead of mixing with errno?

**Comment by jpfreyen** [comment]
Follow-up question- is the mono team consulted for cross-platform questions like this since they were first to implement?  Both the .NETCore and Mono projects are both owned by Microsoft after all.

**Comment by jpfreyen** [comment]
I find it a bit amusing that I'm a Linux guy asking for Windows functionality :-)

**Comment by danmosemsft** [comment]
@jpfreyen I think this is covered by https://github.com/dotnet/corefx/issues/34221. Please add thoughts there if you wish (or reopen this if I'm mistaken)
