### ISSUE TITLE
API Proposal - Add high level AssemblyDependencyResolver APIs

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/corefx#36237]
API Proposal TBD

**Comment by sdmaclea** [comment]
In https://github.com/dotnet/corefx/issues/34791#issuecomment-475375328

@jeffschwMSFT Suggested:

@sdmaclea would we consider adding a constructor that took an AssemblyDependencyResolver as input?  That way the primary use case for a customer would look something like this...

AssemblyDependencyResolver resolver = new AssemblyDependencyResolver(pluginPath);
AssemblyLoadContext alc = new AssemblyLoadContext("My plugin", resolver);

In this way the Load would not just return null, it would resolve an assembly (if a resolver existed) and return null other wise.

My thinking here is that without this overload a customer would have to also know about the ADR (as it is separate) and wire up the event.  If it were a parameter it is likely more discoverable.

**Comment by sdmaclea** [comment]
https://github.com/dotnet/corefx/issues/34791#issuecomment-475378393

@jkotas replied:

I do not think we would to attach specific behaviors to the abstract base class. This should be a factory method, not a constructor.  E.g.:

```
AssemblyDependencyResolver resolver = new AssemblyDependencyResolver(pluginPath);
AssemblyLoadContext alc = resolver.CreateAssemblyLoadContext("My plugin");
```

**Comment by sdmaclea** [comment]
https://github.com/dotnet/corefx/issues/34791#issuecomment-475426699
@sdmaclea replied
```C#
namespace System.Runtime.Loader
{
    public partial class AssemblyDependencyResolver
    {
        // Load assembly and dependencies into alc
        public static System.Reflection.Assembly 
        LoadAssembly(string path, AssemblyLoadContext alc = AssemblyLoadContext.Default);

        // Load assembly and dependencies in custom AssemblyLoadContext
        //
        // Dependent assemblies will be loaded in AssemblyLoadContext.Default
        // if AssemblyLoadContext.Default already knows how to find them from
        // its TPA list. Otherwise it will be loaded in the custom 
        // AssemblyLoadContext
        //
        // This behavior can selectively be disabled with assemblyPreferIsolatedLoad. 
        // If the user supplied function returns true and the AssemblyDependencyResolver
        // can resolve the AssemblyName's path, then it will be loaded into 
        // the custom AssemblyLoadContext.
        //
        // The behavior for unmanaged libraries is similar. It can optionally
        // be controlled by the optional unmanagedDllPreferIsolatedLoad 
        // function.
        public static System.Reflection.Assembly 
        LoadAssemblyInNewAssemblyLoadContext(string path
                                             string alcName = null, // "LoadAssemblyInNewAssemblyLoadContext({0})" % path
                                             bool isCollectible = false,
                                             Func<bool, AssemblyName, AssemblyDependencyResolver> assemblyPreferIsolatedLoad  = null,
                                             Func<bool, string, AssemblyDependencyResolver> unmanagedDllPreferIsolatedLoad  = null);
    }
}
```
With basic usage like 
```C#
Assembly myPlugin = AssemblyDependencyResolver.LoadAssembly(pluginPath);
```
or 
```C#
Assembly myPlugin = AssemblyDependencyResolver.LoadAssemblyInNewAssemblyLoadContext(pluginPath);
```

Advanced usage could use `assemblyPreferIsolatedLoad` and/or `unmanagedDllPreferIsolatedLoad`  to allow per dependency control over isolation.

**Comment by sdmaclea** [comment]
@jeffschwMSFT replied

> Assembly myPlugin = AssemblyDependencyResolver.LoadAssembly(pluginPath);

I would not recommend expanding our Load* to AssemblyDependencyResolver.  I would rather keep loading on AssemblyLoadContext and enable some sort of either constructor (which is my preference) or a factor method (which @jkotas suggested).  

> We can certainly add samples and docs cross references.

I agree this is required, but I would rather offer an intellisense option to help lead people in the right direction and not have to search to discover how to best use it.  I feel one of our goals of making this class concrete is that it enables people to new and use.  Having an intuitive way to pair that with the ADR would help even more.

**Comment by sdmaclea** [comment]
@vitek-karas replied
Is there a reason we're trying to come up with "Easy to use" loading method... once again I might add :-)
I personally would prefer for us to solve the basics first. Then try to write some sample using the new APIs and see where it's getting overly complex. And maybe then try to add some "Easy to use" APIs.

Re some of the proposed APIs:
`ADR.LoadAssembly(into alc)` - I would like to see at least a rough idea how this would be implemented. Especially if it allows loading into Default. I don't think it's that simple - it would have to be based on event handlers... I guess.

The factory method which creates an ALC from ADR is much more realistic - it can provide its own implementation of ALC and override `Load`. But then again, it implies isolation policy...

**Comment by sdmaclea** [comment]
@jeffschwMSFT replied:

> Is there a reason we're trying to come up with "Easy to use" loading method

I hope that is our goal for .NET Core 3.0. ;)

> Can we please split the discussion:

I am OK with splitting, the consideration is we likely have one of our last opportunities to make API level changes, and since this is drimane to this API I offered it as a suggestion.  Though you are right, we need to close down the discussion and prepare for the current solid set of enhancements that we already have a great proposal for.

Overall, I am super happy with the advances we are making in this API and like most things am looking for even more.

**Comment by josalem** [comment]
Is the intent with using the `AssemblyDependencyResolver` to keep users from having to write a series of nested `try\catch` blocks in their `AssemblyLoadContext.Load` override?  When I currently use an ALC and override the `Load` function it always ends up looking something like this:
```csharp
        protected override Assembly Load(AssemblyName assemblyName)
        {
            // types that code inside and outside the ALC need to reason over
            if (<white list of assemblies to always resolve from default>)
                return null;

            try
            {
                var asm = LoadFromAssemblyPath(Path.Combine($"\path\to\running\assembly\{assemblyName.Name}.dll"));
                return asm;
            }
            catch (Exception)
            {
                // Then check the search path
                try
                {
                    var asm = LoadFromAssemblyPath($"\some\arbitrary\path\{assemblyName.Name}.dll"));
                    return asm;
                }
                catch (Exception)
                {
                    // eventually give up and just resolve it in the shared context
                    return null;
                }
            }
        }
```
For the use cases I have been looking at , there is usually some surface area of types/interfaces that _both_ the code inside the ALC and outside will need to reason over, e.g., logging message types, DTO types, etc.  Once you get started on this manual book keeping, you can really go over a deep end with defining this function.  Will these `AssemblyDependencyResolvers` be designed in such a way that library designers can pre-define these whitelists of types?  I'm assuming that is what the `Func<bool, AssemblyName, AssemblyDependencyResolver> assemblyPreferIsolatedLoad` will be used for.  I guess my question then is what will be the main tool for defining _which_ dependencies get loaded into the ALC?  As it stands, this is what ultimately defines the boundary between ALCs, right?  Making this either very explicit or defining a well-known behavior will cement that boundary for users (SDK builders _and_ the SDK consumers).

**Comment by vitek-karas** [comment]
@josalem The intent behind `AssemblyDependencyResolver` is to make it easy to consume components produced by the .NET Core SDK. It almost exclusively relies on the `.deps.json` file generated for the component by the SDK. SDK (and consequently project files) already have mechanism through which the author of the component can define which assemblies belong to the component and which assemblies should come from the host.
The general rules should be that the component should NOT carry assemblies which it expects to get from the host. Including them just creates all kinds of issues, which in your case is fixed by having the "blacklist" of what not to load.

So `AssemblyDependencyResolver` itself should not really provide ways to apply the blacklist as that can already be done through the `.deps.json`. That said, if the host wants to load incorrectly authored components, it would come handy. I'm not sure we should provide some really easy way to do that though.

**Comment by sdmaclea** [comment]
If the intent is to help intellisense to help find `AssemblyDependencyResolver`

Perhaps we should add something like 

```C#
System.Reflection.Assembly.Load(AssemblyDependencyResolver componentWithDependencies,
                                System.Reflection.Assembly.LoadOptions = default);
```

**Comment by jeffschwMSFT** [comment]
I have recently had a shift towards the Assembly.Load* APIs, so I like this approach.  One thing to keep in mind is that Assembly.Load is in .NET Standard so it easily works across .NET Framework and .NET Core, this new API would not necessarily be.  Though I like the direction.

**Comment by sdmaclea** [comment]
> Assembly.Load is in .NET Standard so it easily works across .NET Framework and .NET Core, this new API would not necessarily be.

Understood. That is why it seemed like a natural place for intellisense to help find it.

Here is a more complete proposal. AssemblyDependencyResolver is in LoadOptions to make the API more extensible.  I think intellisense will still help.

```C#
namespace System.Reflection
{
    public partial classs Assembly
    {
        public struct LoadOptions
        {
            LoadOptions(System.Runtime.Loader.AssemblyDependencyResolver? dependencyResolver,
                        System.Runtime.Loader.AssemblyLoadContext? context = null);

            /// <summary>Managed dependency path resolver</summary>
            /// <remarks>
            /// Function accepting an AssemblyName, returning a fully qualified path
            /// </remarks>
            public readonly Func<AssemblyName, string?>? managedDependencyResolver;

            /// <summary>Unmanaged dependency path resolver</summary>
            /// <remarks>
            /// Function accepting a library name, returning a fully qualified path
            /// </remarks>
            public readonly Func<string, string?>? unmanagedDependencyResolver;

            /// <summary>AssemblyLoadContext to load into</summary>
            /// <remarks>
            /// When assemblyLoadContext == null, match Assembly.Load(path) behavior 
            /// for choosing AssemblyLoadContext
            /// </remarks>
            public readonly System.Runtime.Loader.AssemblyLoadContext? assemblyLoadContext;
        }
        public static Assembly Load(string path, LoadOptions options);
    }
}
```

**Comment by jkotas** [comment]
> `Assembly Load(string path, LoadOptions options)`

We have `Load(string assemblyName)` today. Adding this overload would violate API design guidelines. From https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/member-overloading: "DO NOT have overloads with parameters at the same position and similar types yet with different semantics." 

I doubt that this design needs to be Intellisense-optimized. This is a complex topic and calling the right API is only a small part of what you need to do. I think the most likely entrypoint for people trying to figure this out these days would be StackOverflow. We may want to make sure that eventual StackOverflow questions related to this have the right answers.

**Comment by sdmaclea** [comment]
@jeffschwMSFT Seems like consensus may be heading to "we do not need this API."  Given @jkotas recent comment, I would be tempted to close this issue.

**Comment by jeffschwMSFT** [comment]
Let's close, then step back and ensure we have all the right surface area.  I feel there is still a disjoint nature of our offering, but we can discuss further in a different issue.
