### ISSUE TITLE
Due diligence on new DbDataReader extension method class on System.Data.Common

### ISSUE THREAD

**Issue by divega** [dotnet/corefx#36243]
This issue to make sure we follow up with @terrajobst to make sure we do the right thing for the new extension method sponsor class to be created in https://github.com/dotnet/corefx/pull/36123. 

Possible concerns are:

1. Should the class be included in .NET Standard 2.1?
2. ~~Understand in which of the TFMs targeted by the System.Data.Common package the methods will be available~~ 

cc @roji @ajcvickers

**Comment by roji** [comment]
@divega, #31595 has the api-candidate-for-standard label and this issue doesn't seem to contain anything more beyond that - can we close?

**Comment by divega** [comment]
Closing as we have scheduled this for API review.
