### ISSUE TITLE
Microsoft.VisualBasic.Strings.Replace produces unexpected result when replacing Japanese characters

### ISSUE THREAD

**Issue by Nukepayload2** [dotnet/corefx#36251]
Forwarded from https://github.com/dotnet/vblang/issues/390 

I found that the `Microsoft.VisualBasic.Strings.Replace` function has a strange behavior. 
The following program replaces Japanese full-width characters "ポ" and half-width characters "ﾎﾟ" with "po":
```vbnet
Module Program
    Sub Main()
        Dim replaced = Replace(Expression:="ﾎﾟポ",
                               Find:="ポ", Replacement:="po",
                               Compare:=CompareMethod.Text)
        Console.WriteLine(replaced)
    End Sub
End Module
```
[Run with SharpLab](https://sharplab.io/#v2:EYLgHgbALANANiAbsGAXEAnArgOwD4CSAtgA4D2GqAzgAQDKAnlagKZECwAUMeZbQLIBLAMYYyVMgDNUAOgBqgqlgCGcAELKqIrl35kAJljgsaABTEBzDMo6ca9+lmA1+ywTgAUASi4O/NABFBIhoMFhI4ZWEWfRoAXhoAJXDI6I8AUTASMKotMhwQOIAiQDj/wHz/wF2GIphffzr6hr8AMXd9QqKqmCSUqLYWHHRi8mraxrGxgGEyUmUwwqmZsP4WVAALAxkAFRYwVB87eqmcCWMZAHUMQVYAGXcWDzCI3v19v3ScWLonLnfYvUNjEA)

The expected result is "popo". But actually the value of `replaced` is "poﾟpo". It's inconsistent with the `Range.Replace` function of Excel. 
This bug will affect .NET Core 3.0 when the `Microsoft.VisualBasic.Strings.Replace` function is ported from .NET Framework.

**Comment by danmosemsft** [comment]
Sounds like.NETFramework has this behavior? I don't know details of the issue, but I doubt it would be changed, since the purpose of bringing the code to.NET Core is to make it possible to run VB libraries, and any possibility of requiring code changes and recompilation to preserve behavior works against that goal.

**Comment by Nukepayload2** [comment]
@danmosemsft 
You can add a switch that allows us to opt-in the enhanced `Replace` function in the configuration file.
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <AppContextSwitchOverrides value="Switch.Microsoft.VisualBasic.Strings.UseEnhancedReplace=true" />
  </runtime>
</configuration>
```

**Comment by Gnbrkm41** [comment]
Microsoft.VisualBasic (and Microsoft.CSharp) packages seems to have been archived, and these are very unlikely that it will accept new contributions. (https://github.com/dotnet/corefx/issues/33170) Although there is an exception for Microsoft.VisualBasic, it is limited to "contributions that are within the scope of the porting effort."... which I guess is the porting effort from .NET Framework to .NET Core, not the old VBA, which seems to be the `Range.Replace` function you're talking about.

Considering that this would technically be a breaking change from .NET Framework, and this would involve some work to achieve so, I'm inclined to guess that this is unlikely to happen.

**Comment by danmosemsft** [comment]
I agree @cston if you agree, we could close.

**Comment by cston** [comment]
Yes, .NET Core behavior should match .NET Framework.

**Comment by Gnbrkm41** [comment]
Perhaps you could try asking in [VS Developer Community](https://developercommunity.visualstudio.com/spaces/61/index.html)? This is the place to ask for bugs in .NET Framework.
