### ISSUE TITLE
InvalidStateForRecompposition method is misspelled

### ISSUE THREAD

**Issue by nschonni** [dotnet/corefx#36324]
Since this is public, it would be a breaking change
https://github.com/dotnet/corefx/blob/c06df8e5f3877ddd3fd1a75b1d4d494268acce7f/src/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ErrorBuilder.cs#L20
It only appears to have one reference in this repo right now
https://github.com/dotnet/corefx/blob/c06df8e5f3877ddd3fd1a75b1d4d494268acce7f/src/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ImportEngine.cs#L537

Should be InvalidStateForRecomposition with one "p"

**Comment by stephentoub** [comment]
> Since this is public, it would be a breaking change

It's on an internal type, so it's not breaking.

**Comment by nschonni** [comment]
Ok, I'll send something then. I usually assume when I see `public` it would be breaking

**Comment by nschonni** [comment]
The PR for this wasn't merged

**Comment by stephentoub** [comment]
We generally don't open issues for arbitrary internal typos. But thanks.
