### ISSUE TITLE
EnvDTE SolutionFolder AddFromFile shows error message

### ISSUE THREAD

**Issue by AdamJachocki** [dotnet/corefx#36338]
Hi, first of all, sorry that I posted this bug here, but I couldn't find any better place for this.

I want to add some projects to solution using DTE. This is WPF APPLICATION, not an extension.

I have to add some projects to one folder, and then another one project to other folder and last project to yet another folder.

When adding projects to first folder everything is ok. But when I add projects to another folder, the message box popups saying: "Operation could not be completed: Invalid window handle."

After clicking OK, I get another MessageBox: "Operation could not be completed: Unspecified error".

But, all the projects are successfully added to the solution. So the biggest problem is the message box that popups while doing the job. Having read "invalid window handle", I thought that maybe I should try do EVERYTHING on main thread. But result is the same. Additionaly there is no messages in Output Window of Visual Studio. This is my code:

(DoFunction and DoAction are simple methods that wraps the content into try..catch and if there is RPC_E_SERVERCALL_RETRYLATER exception, it will take another attempt)

`//Getting DTE Service
dteService = DoFunction(() =>(DTE2)Activator.CreateInstance(Type.GetTypeFromProgID("VisualStudio.DTE.15.0", true), true));

//Getting the solution
activeSolution = DoFunction(() => dteService.Solution as Solution4);
DoAction(() =>activeSolution.Open(solutionPath));`

ActiveSolution is my private field.

`//Adding project to solution:
DoAction(() =>
{
    SolutionFolder folder = GetExistingSolutionFolder(folderTree);
    if (folder == null)
        activeSolution.AddFromFile(projectFileName);
    else
        folder.AddFromFile(projectFileName); //<-- messagebox popups here
}); `

Project is being added to folder inside solution. Folders already exist in solution. GetExistingSolutionFolder just searches recurseviley for the folder.

What could be the reason of this message box? What's important, no exception is thrown.

I have also described this problem here: https://stackoverflow.com/questions/55179773/envdte-solutionfolder-addfromfile-shows-error-message

**Comment by danmosemsft** [comment]
Hello @AdamJachocki . This repo is for .NET Core libraries. The best place to log VS issues is via the Feedback button in the top right of VS itself. That will actually go to the right people in the VS team, and they can communicate back.

I'm going to close this issue here meantime.
