### ISSUE TITLE
Sporadic failure in System.Diagnostics.Tests.ProcessTests.TestEnableRaiseEvents on Linux

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#36331]
Debian.8.Amd64-x64 and Alpine.38.Amd64-x64 today. Previously I see SLES and OpenSUSE.

Each of the two tests (null and false) passed on rerun on one configuration and failed on the other, suggesting general flakiness. It looks like historically they are slightly flaky. The "true" version is not.

The failure is because the `Exited` delegate was invoked even though `p.EnableRaisingEvents` was set to false or not set at all. 

```
Assert.False() Failure
Expected: False
Actual:   True
Stack Trace :
   at System.Diagnostics.Tests.ProcessTests.TestEnableRaiseEvents(Nullable`1 enable) in /__w/1/s/src/System.Diagnostics.Process/tests/ProcessTests.cs:line 121
```

https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190324.4/workItem/System.Diagnostics.Process.Tests/analysis/xunit/System.Diagnostics.Tests.ProcessTests~2FTestEnableRaiseEvents(enable:%20null)
https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190324.4/workItem/System.Diagnostics.Process.Tests/analysis/xunit/System.Diagnostics.Tests.ProcessTests~2FTestEnableRaiseEvents(enable:%20False)

In Process.cs, `EnableRaisingEvents` sets `_watchForExit`. In this case we do not set it (or set to false) => `_watchForExit` is false. 

The `Exited` delegate is called by `OnExited()` which is called by `RaiseOnExited()` which is called synchronously by `HasExited` (not used here) or synchronously by `WaitForExit` (if `_watchForExit` set) or by `CompletionCallback`. =>  `CompletionCallback` must be the source of this callback.

`CompletionCallback` is set up by `EnsureWatchingForExit()` to be called when the process handle is signaled. This is the only only place it is set up =>we know `EnsureWatchingForExit()` was called.

If `_watchForExit` is false the only other effect is to prevent `SetProcessHandle` from calling `EnsureWatchingForExit()`. Other than by `EnableRaisingEvents`  this is the only place that `EnsureWatchingForExit()` is called (on Windows). => on Windows, if `EnableRaisingEvents` is not true, `Exited` will only be invoked if you use `HasExited` and this test does not.

Incidentally MSDN says 

>Note that the Exited event is raised even if the value of EnableRaisingEvents is false when the process exits during or before the user performs a HasExited check.

That comment seems wrong. 

On Unix  `EnsureWatchingForExit()` is called in one other place, `GetProcessHandle`, and `GetProcessHandle` is always called in `ForkAndExecProcess` if the fork succeeds. => on Unix, whatever the value of  `EnableRaisingEvents`, the callback will be called when the `_waitHandle` is signaled 

1. Question then is why the test ever passes - apparently most times, the handle does not get signaled.? The test after killing the process does `p.WaitForExit(30 sec)` before checking that `Exited` was called. The simplest explanation is that the process is usually not terminating within that 30 seconds. Seems unlikely? The `ProcessWaitState` class is complex and it's not clear to me what other causes there may be. @tmds

2. Either way it seems that we should modify the Unix implementation so that, like Windows, it does not raise the event ever, if `EnableRaisingEvents` is false, and you do not call `HasExited`.

@stephentoub

**Comment by danmosemsft** [comment]
A clue may lie in the fact that the `true` variation of the test is always passing. In this case the test spins for 30 seconds. Perhaps that extra 30 seconds is what is needed for the process to exit and the event to get signaled properly.

**Comment by tmds** [comment]
> On Unix EnsureWatchingForExit() is called in one other place, GetProcessHandle, and GetProcessHandle is always called in ForkAndExecProcess if the fork succeeds. => on Unix, whatever the value of EnableRaisingEvents, the callback will be called when the _waitHandle is signaled

This is only since https://github.com/dotnet/corefx/pull/36199.
The method is called to get the `_waitHandle` created in `EnableRaisingEvents`:
https://github.com/dotnet/corefx/blob/d3942d4671919edb0cca6ddc1840190f524a809d/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs#L190-L192
and as a side-effect we are causing `Process.Exited` events to be emitted by the `_registeredWaitHandle`.

**Comment by danmosemsft** [comment]
Can we explain why the test only failed occasionally? That would have prevented this regression

**Comment by tmds** [comment]
https://github.com/dotnet/corefx/blob/71122bb4921e0239ea679dd275d53695b94e52f4/src/System.Diagnostics.Process/tests/ProcessTests.cs#L90-L121

When `StartSleepKillWait` returns, there is also a callback on the `ThreadPool` that triggers `Process.Exited`. So if it manages to do that before the check, the test fails.

We can sleep a little so the `Process.Exited` event has some more time to get triggered.

**Comment by stephentoub** [comment]
> Can we explain why the test only failed occasionally

Because there's a race condition.  The callback is invoked by queueing a work item to the thread pool.  For the `true` case, we can safely wait for the callback to be invoked, because we expect it to be invoked.  But in the `false`/`null` case, we do not expect it to be invoked... the best we could do would be to wait for some period of time, and the longer we wait, the more likely it is that it wasn't queued, but also the longer the test takes, and even then there's no guarantee.

**Comment by danmosemsft** [comment]
> When StartSleepKillWait returns, there is also a callback on the ThreadPool that triggers Process.Exited. So if it manages to do that before the check, the test fails.

Right but it has 30 seconds - I guess the machine could be so heavily loaded it doesn't get scheduled in that time but it seemed unlikely to me. Anyway, I"ll let it go. 😃

**Comment by stephentoub** [comment]
> Right but it has 30 seconds

That's 30 seconds for the process to exit.  Only once it's exited is the callback queued.

**Comment by danmosemsft** [comment]
Thanks both, fast turnaround!
