### ISSUE TITLE
Proposal: Combine ISOWeek.GetWeekOfYear and GetYear methods

### ISSUE THREAD

**Issue by khellang** [dotnet/corefx#36339]
If you have a `DateTime` and want to get the ISO week for that date, it's usually not enough to only get the week, as the ISO week year might not be the same as the year of the specified `date`. That means you'd almost always want to call both `GetWeekOfYear` and `GetYear` for the same date.

Since both `GetYear` and `GetWeekOfYear` does (more or less) the same work and has both week and year available internally, it would make sense to merge the two methods into one, to avoid doing the same work twice, and have it return either a tuple or make `ISOWeek` itself a (readonly) struct and return that.

The current type looks like this:

```csharp
namespace System.Globalization
{
    public static partial class ISOWeek
    {
        public static int GetWeekOfYear(System.DateTime date) { throw null; }
        public static int GetWeeksInYear(int year) { throw null; }
        public static int GetYear(System.DateTime date) { throw null; }
        public static System.DateTime GetYearEnd(int year) { throw null; }
        public static System.DateTime GetYearStart(int year) { throw null; }
        public static System.DateTime ToDateTime(int year, int week, System.DayOfWeek dayOfWeek) { throw null; }
    }
}
```

I propose something like this:

```diff
namespace System.Globalization
{
-    public static partial class ISOWeek
+    public readonly partial struct ISOWeek : System.IEquatable<ISOWeek>
    {
+        public ISOWeek(int year, int week) { throw null; }
+        public int Year { get { throw null; } }
+        public int Week { get { throw null; } }
+        public void Deconstruct(out int year, out int week) { throw null; }
+        public bool Equals(System.Globalization.ISOWeek obj) { throw null; }
+        public override bool Equals(object obj) { throw null; }
+        public override int GetHashCode() { throw null; }
+        public override string ToString() { throw null; }
+        public bool TryFormat(System.Span<char> destination, out int charsWritten) { throw null; }

-        public static int GetWeekOfYear(System.DateTime date) { throw null; }
-        public static int GetYear(System.DateTime date) { throw null; }
+        public static System.Globalization.ISOWeek FromDate(System.DateTime date) { throw null; }
    }
}
```

Ref. https://github.com/dotnet/corefx/issues/28933#issuecomment-476096246

Is it too late to make changes to the (not yet shipped) `System.Globalization.ISOWeek` APIs?

// @tarekgh

**Comment by khellang** [comment]
Also, at that point, I think it would make sense to also move `ToDateTime` into an instance method on `ISOWeek`:

```diff
namespace System.Globalization
{
    public readonly partial struct ISOWeek : System.IEquatable<ISOWeek>
    {
-        public static System.DateTime ToDateTime(int year, int week, System.DayOfWeek dayOfWeek) { throw null; }
+        public System.DateTime ToDateTime(System.DayOfWeek dayOfWeek) { throw null; }
    }
}
```

**Comment by tarekgh** [comment]
Sorry, this is too late to change and also this is not a big deal as the callers can wrap the calls inside a helper method if really needed.

**Comment by khellang** [comment]
> this is not a big deal as the callers can wrap the calls inside a helper method if really needed

@tarekgh Sure, but you end up doing the same calculations twice. I still think it would be beneficial to make `ISOWeek` a struct that could be passed around. An implementation of the above proposal isn't much work; https://github.com/dotnet/coreclr/compare/master...khellang:iso-week-tweaks

**Comment by karelz** [comment]
@terrajobst thoughts?
We should have time to fix it - breaking changes between Previews are ok.

@khellang you need to convince @tarekgh that the change makes sense first ;)

**Comment by tarekgh** [comment]
I am still thinking we don't need to create a type have a state. The whole ISOWeek is just a helper methods as we discussed in the original proposal. We discussed even if we can make it a calendar by itself there. I would prefer to keep the APIs as it is and if it is really necessary we can expose extra APIs return a Tuple of the week and the year. this should satisfy the scenario mentioned in this issue.

**Comment by khellang** [comment]
> I am still thinking we don't need to create a type have a state.

By making it a named struct, it's easier to add more APIs in the future (or now), like formatting etc. It also opens up the possibility for users to add extension methods. Also, let's face it, it's just generally much friendlier than tuples 😅

> The whole ISOWeek is just a helper methods as we discussed in the original proposal

Right, and it'll still be a bunch of helper methods. Just factored a bit better to optimize a very common scenario as well as opening up future improvements. 

> We discussed even if we can make it a calendar by itself there.

Yes, but concluded that it wouldn't fit properly into the calendar shape. I don't see why that would prevent it from being a struct with state? 🤔 

> if it is really necessary we can expose extra APIs return a Tuple of the week and the year. this should satisfy the scenario mentioned in this issue.

Nothing is really necessary, I just think it would be better. We could indeed just add a new method that returns year and week as a tuple, but why have three methods for more or less the same thing? 

The linked comment above shows that the APIs might already be a bit confusing, so I'm just thinking as long as we still have a chance to correct this, in my opinion, API mistake, while still in preview, we should do it 😁

**Comment by tarekgh** [comment]
> By making it a named struct, it's easier to add more APIs in the future (or now), like formatting etc. It also opens up the possibility for users to add extension methods. Also, let's face it, it's just generally much friendlier than tuples 

That is exactly my point, if we need to format ISO dates, it should be done on DateTime and not any other type. That is how we format dates in general. I am not seeing why Tuple is less friendly. Actually your proposal have Deconstruct which will behave exactly as Tuple.

> Right, and it'll still be a bunch of helper methods. Just factored a bit better to optimize a very common scenario as well as opening up future improvements.

I am not really expecting we'll need more in the future. The ISO scenarios is limited.

> I don't see why that would prevent it from being a struct with state?

Because we already have DateTime. people usually use DateTime and when need any conversion they use some other helpers (e.g. Calendars) to convert dates. Having another object carrying different form of dates will open the door for more scenarios that can miss up.  people carrying DateTime object will have just one object representing the date and we have the tools to convert it to any other forms (including formatting).

> but why have three methods for more or less the same thing?

Not same thing. Think about the scenarios. Why you need to force people to get both year and week all the time while are interested in week or year only? and it will be simpler to return one number you care about. If you care getting both week and year, then we still providing the API does that.

> The linked comment above shows that the APIs might already be a bit confusing

I don't consider this confusing. The comment from the guy was 

```I missed the existence of GetYear(). Sorry for the noise```

He didn't just look at the type to know what is offering. this is not confusion but discover-ability. the intellisense should be helping with that much.
