### ISSUE TITLE
XSD Validation Support - Missing?

### ISSUE THREAD

**Issue by NightOwl888** [dotnet/corefx#3633]
As I [posted earlier on StackOverflow](http://stackoverflow.com/questions/32872684/how-do-i-validate-xml-against-xsd-separate-documents-in-dnx-core-5-0-asp-net?noredirect=1#comment53665404_32872684), I am attempting to port some older code to DNX core 5.0, but it seems that XSD validation support is missing from the library. Or if I am wrong, could someone please provide a sample or point me to the correct document that shows how to validate XML against XSD (separate documents).

**Comment by akoeplinger** [comment]
There was a thread in the .NET Foundation forums about XmlSchema which might be related: http://forums.dotnetfoundation.org/t/xmlschema-in-net-core/507/11

**Comment by SariDev** [comment]
Please add support for XSD's in .NET Core.

I dare to say working with XML files and validating those files in an easy way (through xml schema validation) is a pretty common task for most enterprise applications.
Therefore I would like to see support inside .NET Core to work with XSD's.

If XSD's will be added to .NET Core it would be great if the current XSD 1.1 release could be supported as it offers support for assertions, which improves XSD validation a lot.

**Comment by prachi2607** [comment]
Hi,

We are working with XML schemas and writing a custom validator for each schema is a major overhead.
If schema validation going to be supported on CoreCLR as it is much needed?
If yes, is there a timeline for the same?

Thanks in advance

**Comment by wompeter** [comment]
Would also love to see support for this.  XML won't be going away anytime soon and every enterprise app I've ever touched has validation routines in it :(

**Comment by fubar-coder** [comment]
Related to #2342?

**Comment by DevilfishSoftware** [comment]
Has there been any progress with XSD support in .NET Core?

**Comment by danmosemsft** [comment]
You can see this in master in corefx\src\System.Private.Xml\src\System\Xml\Core. It's expected in the next major release of .NET Core.

**Comment by karelz** [comment]
@danmosemsft should we just close it as fixed or is there still something left?

**Comment by danmosemsft** [comment]
@sepidehMS I'm closing this against #11888 because #11888 is all that remains for this to be useable. Please correct me if I'm wrong. Also, please help close any other issues about missing XML functionality if #11888 will bring it.

**Comment by milla** [comment]
Has there been any progress with XSD support in .NET Core?

**Comment by richieeeeeeee** [comment]
Why is it closed? It still does not exist in .NET Core 1.1!

**Comment by karelz** [comment]
Both issues were closed with milestone=1.2, which means they will be fixed in the release after 1.1.
The whole .NET Standard 2.0 push for 1.2 is LOTS of APIs and it takes significant time to port them all even for large team.

**Comment by GurmeetMunshi** [comment]
How to generate a Class from xsd in dot net core 2.0

**Comment by krwq** [comment]
@GurmeetMunshi, currently it is not supported - you can generate really close to working class using full framework though (might even work without changes). We have a separate issue tracking it: https://github.com/dotnet/corefx/issues/8647
