### ISSUE TITLE
API Review for Activity Sampling Support for DiagnosticSource

### ISSUE THREAD

**Issue by vancem** [dotnet/corefx#36349]
In addition to the work for System.Diagnostic.Activity to support the W3C Ids (see issue  #34828), we also wanted to support  the W3C concept of ACTIVITY SAMPLING in System.DIagnostics.DiagnositicSource.      The goal is to allow logging systems (like Applications Insights) to have most (say 99%) requests NOT logged (thus saving overhead and log size), but having ALL the events for those 1% that are sampled logged (which gives excellent fidelity for those requests.   

This feature was planned along with the other W3C support in #34828) but we wanted to do it as a separate item to make review and implementation more straightforward.   This issue tracks the API design portion of the sampling feature, and  #36340 is the actual implementation.  

One important goal of the design is to give the control over the sampling to the logging system (e.g. that is the subscriber of the DiagnosticListener).    That way they control all configuration of the system.   DiagnosticSource/Activity's role is to provide 'primitives' to support this.   In particular 

1. Creating a 'W3CIDFlags' property on Activity.   Activity already was mirroring the structure of the W3C ID, and this is just 'finishing it off' by exposing the 'flags' part of the ID (previously we simply ignored this data).   In particular the only flag current defined byte by the W3C standard is the 'Recording' bit that represent the fact that the associated request should be sampled by the logging system..   
2. Parse the W3CIDFlags property from the ID, as well as propage it to child Activities, and use the flags on any outgoing W3C Ids. 
3. Add a new  callback  DiagnosticSource.OnActivityImport(...), This method can be called by instrumentation logic whose job it is to read 'external' requests (e.g. HTTP) and gives the subscribers the ability to update the Activity (basically set or reset the 'Recording' bit, based on whatever policy they have.   
3. Add a new  callback  DiagnosticSource.OnActivityExport(...), This method can be called by instrumentation logic whose job it is to write 'external' requests (e.g. HTTP) and gives the subscriber the ability to update the outgoing payload based on its policy (it is not expected that this callback will be used in most cases, but is useful for completeness).  

The following APIs support the setting and propagation of the W3CIdFlags.    Along with these new APIs, we also updated the string'based ID methods/properties so that they properly parse / output the new flags based on the state of the W3CIDFlags field. 
```C#
    public partial class Activity
    {
        public bool Recording { get; }
        public W3CIdFlags W3CIdFlags { get; set; }
        public Activity SetParentId(in ActivityTraceId traceId, in ActivitySpanId spanId, W3CIdFlags w3CFlags = W3CIdFlags.None);
    }
    [System.FlagsAttribute]
    public enum W3CIdFlags
    {
        None = 0,
        Recording = 1,
    }
```
The 'Recording' property is simply a convenience method for accessing W3CIdFlags.Recording.  It is useful because the 'IsEnabled' callback in DiagnosticsListener subscribers will want to access it conveniently, and it is a concept that is independent of W3C, so having a name that reflects that is good.  A setter is possible, but we did not include it here because it is used far less often and we can add it later if we find it useful to do so.   

The changes to DiagnosticSource/DiagnosticListener to support the new OnActivityImport and OnActivityExport are shown below. 
```C#
    public partial class DiagnosticListener : System.Diagnostics.DiagnosticSource, System.IDisposable, System.IObservable<System.Collections.Generic.KeyValuePair<string, object>>
    {
        public override void OnActivityExport(Activity activity, object payloadObj) 
        public override void OnActivityImport(Activity activity, object payloadObj) 
        public virtual System.IDisposable Subscribe(
            System.IObserver<KeyValuePair<string, object>> observer, 
            System.Func<string, object, object, bool> isEnabled, 
            System.Action<Activity, object> onActivityImport = null, 
            System.Action<Activity, object> onActivityExport = null);
    }
    public abstract partial class DiagnosticSource
    {
        public virtual void OnActivityExport(Activity activity, object payloadObj) 
        public virtual void OnActivityImport(Activity activity, object payloadObj)
    }
```
Basically each of those methods is given the 'payload object' (which represents the incoming (or outgoing) request, and the activity that should be imported (or exported).   

Note that very few instrumentation sites will need to ever call these callbacks (basically only those where activities are 'entering' or 'leaving' the system), and it is also assumed that unless you are doing something sophisticated like sampling, the subscriber will not need to specify them (the 'do nothing' body is fine).

Below is the help for each of the *OnActivity* methods
```C#
        /// <summary>
        /// Optional: If an instumentation site creating an new activity that was caused
        /// by something outside the process (e.g. an incomming HTTP request), then that site
        /// will want to make a new activity and transfer state from that incoming request
        /// to the activity.   To the extent possible this should be done by the instrumenation
        /// site (because it is a contract between Activity and the incomming request logic
        /// at the instrumenation site.   However the instrumenation site can't handle policy
        /// (for example if sampling is done exactly which requests should be sampled) For this
        /// the instrumentation site needs to call back out to the logging system and ask it to
        /// resolve policy (e.g. decide if the Activity's 'sampling' bit should be set)  This
        /// is what OnActivityImport is for.   It is given the activity as well as a payload
        /// object that represents the incomming request.   The DiagnosticSource's subscribers
        /// then have the opportunity to update this activity as desired.   
        /// 
        /// Note that this callout is rarely used at instrumentation sites (only those sites
        /// that are on the 'boundry' of the process), and the instrumetation site will implement
        /// some default policy (it sets the activity in SOME way), and so this method does not
        /// need to be overriden if that default policy is fine.   Thus this is call should 
        /// be used rare (but often important) cases.   
        /// 
        /// Note that the type of 'payloadObject' is typed as object here, but for any 
        /// particular instrumentation site and the subscriber will know the type of 
        /// the payload and thus cast it and decode it if it needs to. 
        /// </summary>
        public virtual void OnActivityImport(Activity activity, object payloadObj) { }

        /// <summary>
        /// Optional: If an instumentation site is at a location where activities leave the
        /// process (e.g. an outgoing HTTP request), then that site will want to transfer state 
        /// from the activity to the outgoing request.    To the extent possible this should be
        /// done by the instrumenationsite (because it is a contract between Activity and the 
        /// ougoing request logic at the instrumenation site.   However the instrumenation site 
        /// can't handle policy (for example whether activity information should be disabled, 
        /// or written in a older format for compatibility reasons).   For this
        /// the instrumentation site needs to call back out to the logging system and ask it to
        /// resolve policy.  This is what OnActivityExport is for.   It is given the activity as
        /// well as a payloay object that represents the outgoing request.   The DiagnosticSource's 
        /// subscriber then have the ability to update the outgoing request before it is sent.   
        /// 
        /// Note that this callout is rarely used at instrumentation sites (only those sites
        /// that are on an outgoing 'boundry' of the process).   Moreover typically the default
        /// policy that the instrumenation site performs (transfer all activity state in a 
        /// particular outgoing convention), is likely to be fine.   This is only for cases
        /// where that is a problem.  Thus this is call should be used very rarely and is
        /// mostly here for symetry with OnActivityImport and future-proofing.  
        /// 
        /// Note that the type of 'payloadObject' is typed as object here, but for any 
        /// particular instrumentation site and the subscriber should know the type of 
        /// the payload and thus cast it and decode it if it needs to.
        /// </summary>
        public virtual void OnActivityExport(Activity activity, object payloadObj) { }
```

**Comment by terrajobst** [comment]
Looks good. Notes from the review:

* Should `W3CIdFlags` be typed as `byte`?
    - We could, but it doesn't add much and `int` is generally easier, so we decided to leave it as-is
* Rename `W3CIdFlags.Recording` to `Recorded` to match the spec
* `payloadObj` should be `payload` or `state`, which is what we use everywhere else

**Comment by vancem** [comment]
I have updated the original proposal to reflect the changes above, as well as in the implementation.   I am closing this issue
