### ISSUE TITLE
Which is the System.Drawing replaement?

### ISSUE THREAD

**Issue by Charmatzis** [dotnet/corefx#3634]
Hi, guys.
I have a question... which way is to create images in .net core?

**Comment by Maxwe11** [comment]
#2020 
#1563

**Comment by Charmatzis** [comment]
I tried to build it as the instructions says, but I use VS2015 x64 Native Tools Command Prompt and it fails....
Is there anything that we can do?
The errors are:
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1925): warning
C4005: 'snprintf': macro redefinition
c:\users\xr_xa_000\documents\github\libgd\src\gd.h(92): note: see previous definition of
 'snprintf'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1927): fatal er
ror C1189: #error:  Macro definition of snprintf conflicts with Standard Library functio
n declaration


and in the end
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\
amd64\cl.EXE"' : return code '0x2'

**Comment by migueldeicaza** [comment]
There is an open source System.Drawing implementation in Mono:

github.com/mono/mono/tree/master/mcs/class/System.Drawing

It requires this:

https://github.com/mono/libgdiplus

**Comment by Charmatzis** [comment]
Finally I download the VS 2013 Community edition and build it successfully.

**Comment by ststeiger** [comment]
While SkiaSharp is work in progress, see
https://github.com/zkweb-framework/ZKWeb.System.Drawing
or 
https://github.com/sherif-elmetainy/DotnetGD/tree/master/src/CodeArt.DotnetGD
