### ISSUE TITLE
Json serializer support for a property name policy

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#36351]
Extend the JSON Serializer [API](https://github.com/dotnet/corefx/issues/34372) to add support for how a property name is (de)serialized. Related information can be found in the programming model [documentation](https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/docs/SerializerProgrammingModel.md).

Functionality includes:
- An attribute used to specify an explicit name (`JsonNameAttribute`).
- Run-time settings on `JsonSerializerOptions`:
    - A property used to expose the policy for property names (`PropertyNamingPolicy`) and dictionary key names (`DictionaryKeyPolicy`).
    - A property used to specify case-insensitive property names (`PropertyNameCaseInsensitive`)

- An abstract class representing the naming policy (`JsonPropertyNamingPolicy`)
    - A static property to get the CamelCasing policy (`CamelCase`).
    - A single method that takes a string to convert and then returns the converted string.

# Examples
To change a property name explicitly (JSON will contain "birthdate" instead of "BirthDay")
```cs
    public class Person
    {
...
        [JsonName("birthdate")] public DateTime BirthDay { get; set; }
...
    }
```

The name that is specified here (`birthdate`) will be used verbatim, and will not be processed by any name policy.

To change to camel-casing and case-insensitive:
```cs
...
    var options = new JsonSerializerOptions();
    options.PropertyNamePolicy = JsonNamePolicy.CamelCase;
    options.PropertyNameCaseInsensitive = true;
    options.DictionaryKeyPolicy= JsonNamePolicy.CamelCase;
...
    }
```

Extensibility:
```cs
...
    var options = new JsonSerializerOptions();
    options.PropertyNamePolicy = new MyNamePolicy();
...

public class MyNamePolicy : JsonNamePolicy
{
    protected override string ConvertName(string name)
    {
    ...
    }
}

```

# API
```cs
namespace System.Text.Json.Serialization
{
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
    public sealed class JsonNameAttribute : JsonAttribute
    {
        public JsonNameAttribute ();
        public JsonNameAttribute(string name);

        public string Name { get; set; }
    }

    public class JsonSerializerOptions
    {
...
        /// <summary>
        /// Defines the policy used to convert a property's name on an object to another format, such as camel-casing.
        /// The resulting property name is expected to exactly match the JSON payload during deserialization, and
        /// will be used when writing the property name during serialization.
        /// </summary>
        /// <remarks>
        /// This property can be set to <see cref="JsonPropertyNamingPolicy.CamelCase"/> to specify a camel-casing policy.
        /// </remarks>
        public JsonPropertyNamingPolicy PropertyNamingPolicy { get; set; }

        /// <summary>
        /// Determines whether a property's name uses a case-insensitive comparison during deserialization.
        /// The default value is false.
        /// </summary>
        /// <remarks>There is a performance cost associated with a true value since property names in the
        /// JSON payload require additional processing to normalize them for a case-insensitive comparison.</remarks>
        public bool PropertyNameCaseInsensitive { get; set; }

        // same concept as PropertyNamePolicy but for key values in a dictionary.
        public JsonPropertyNamingPolicy DictionaryKeyPolicy { get; set; }
...
    }

    /// <summary>
    /// Determines the policy used to convert a JSON name to another format, such as a camel-casing format.
    /// </summary>
    public abstract class JsonPropertyNamingPolicy
    {
        protected JsonPropertyNamingPolicy();

        /// <summary>
        /// Returns the policy for camel-casing.
        /// </summary>
        public static JsonNamePolicy CamelCase { get; }

        protected abstract string ConvertName(string name);
    }
}

```

Design notes
- Validation will occur to ensure there are no duplicates property names on a POCO based on `PropertyNamingPolicy` and `PropertyNameCaseInsensitive`, and that the name in `JsonNameAttribute` exists as a property on the POCO.
- An exception will be thrown if `JsonPropertyNamingPolicy'ConvertName()` returns null.

**Comment by anurse** [comment]
Specifically for ASP.NET scenarios: A global setting to enable `camelCase` serialization.

**Comment by JamesNK** [comment]
What does `DictionaryKeyCaseInsensitive` do? It makes sense for a property, you're searching for a property and falling back to using case insensitivity if you can't find an exact match. With a dictionary you're just setting key/values into a dictionary.

**Comment by JamesNK** [comment]
```
...
    var options = new JsonSerializerOptions();
    Func<string, string> customNamePolicy (value)  =>
        {
            // some code here that returns the new string
        };

    options.PropertyNamePolicy = JsonNamePolicy.Create(customNamePolicy);
...
    }
```

I'm not a fan of using a `Func<string, string>` for two reasons:
1. Very few people will ever use it, and those that do use it to support camel/snake/kabab case will probably need more code than you want to put in a method to achieve correct naming.
2. You can't refer to a policy created in code via an attribute. A real type would let people reference the policy in an attribute: `[JsonNaming(typeof(SnakeCaseNamingPolicy))]`. When the serializer resolves the type it can inspect the attribute, create the policy type, and then use it at serialization.

**Comment by steveharter** [comment]
> What does DictionaryKeyCaseInsensitive do?

Uses `StringComparer.OrdinalIgnoreCase` when we automatically create Dictionary<string, T>. If we don't support it, and someone wants a case-insensitive dictionary how would they do that?

> Very few people will ever use it, and those that do use it to support camel/snake/kabab case will probably need more code than you want to put in a single method to achieve correct naming.

I'm assuming 50-100 LOC for something like that. It could reference a static method...

> You can't refer to a policy created in code via an attribute.

Eek. I had that in the corelab prototpe but it didn't make it over the "future" section for `JsonNameConverterAttribute`. That however required a new Attribute type (derived from `JsonNameConverterAttribute`) for every converter (e.g. snake-casing). Assume that the attribute either a method that converts (a single line to call the same static method as the implementation) or a property that specifies the converter through a func...

**Comment by terrajobst** [comment]
* `JsonNamePolicy` should have a protected ctor
* For `PropertyNameCaseInsensitive` we need to think about how we match names (comparisons and normalization aren't yielding the same results). @GrabYourPitchforks and @steveharter: you should chat.
* The `ConvertName` produces strings but that seems fine because they are going to be cached.
* The code calling `ConvertName()` should disallow `null` values, but must accept empty strings. Likewise, `ConvertName()` should be documented as  disallowing null values but as accepting empty strings.
