### ISSUE TITLE
StreamReader.ReadLineAsync continues to read values from a closed HttpResponseMessage

### ISSUE THREAD

**Issue by CheloXL** [dotnet/corefx#36368]
I have some simple code that opens a request to an SSE server and waits for messages. All works fine until the connection to server is interrupted (server restart, connectivity issues, etc).

When this happens, StreamReader.ReadLineAsync starts to read "empty" lines instead of simply throw because the underlining stream was closed.

The code is similar to the following:

```cs
var request = new HttpRequestMessage {
	Method = HttpMethod.Get,
	RequestUri = _targetUri
};

request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("text/event-stream"));
request.Headers.Connection.Add("keep-alive");
var response = await _client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, token).ConfigureAwait(false);
var content = await response.Content.ReadAsStreamAsync().ConfigureAwait(false);
using (var sr = new StreamReader(content, Encoding.UTF8)) {
	while (true){
		var line = await sr.ReadLineAsync().ConfigureAwait(false);
		...do something with line...
	}
}
```

The thing is: sometimes it works (when the connection closes, the ReadLineAsync throws), but sometimes it doesn't (ReadLineAsync continues to return empty results). On my machine I can reproduce this 50% of the time (so, it's quite easy to reproduce). If I put fiddler in the middle, it works 100% of the time.

Right now I detect this by counting the number of empty results and if it's too high (100 in my case) I simply break out of the loop, but that sounds more like a hack to me.

Notes:
_client is a reference to a global HttpClient that I use across the application. It is initialized as
```cs
new HttpClient(new HttpClientHandler {
	AllowAutoRedirect = false,
	AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate
}) {
	Timeout = Timeout.InfiniteTimeSpan
};
```

**Comment by stephentoub** [comment]
> When this happens, StreamReader.ReadLineAsync starts to read "empty" lines instead of simply throw because the underlining stream was closed.

`string.Empty` or `null`?  It's supposed to return `null` after it's reached the end of the stream.

If `string.Empty`, can you please share a repro we can run?

**Comment by CheloXL** [comment]
@stephentoub You are correct. It returns null, not string.Empty. So the issue is then why sometimes throw?

Anyways, thanks. Checking for null nullifies (cuak) my hack.

**Comment by stephentoub** [comment]
> So the issue is then why sometimes throw?

If the underlying `Read{Async}` method throws, that'll propagate out of `ReadLine{Async}`.  Is that the case you're talking about?

**Comment by CheloXL** [comment]
Yes. Basically, sometimes I'm getting a null read and sometimes I'm getting an exception that says something like "the underlining stream was closed".

That's why I asked this in the first place. The underlining stream is always closed when the connection is broken. I would expect to always receive null, or to always throw. I'm not sure about the difference...

**Comment by stephentoub** [comment]
It sounds like you have a race condition of some kind in your app. There's a difference between a stream being at EOF such that reads return 0, and the stream being Disposed/Closed such that trying to read from it throws. StreamReader will return null in the former case, but will allow any exceptions from the read call to propagate. You need to make sure the stream you're reading from isn't Disposed/Closed while it's still being used by the reader.
