### ISSUE TITLE
Enable NullableContextOption

### ISSUE THREAD

**Issue by hez2010** [dotnet/corefx#36360]
I think all projects in corefx should opt-in NullableContextOption in order to work well with new C# 8.0 feature nullable reference type and provide comprehensive nullable check. In this way user can know which parameters or return values are nullable and which are not, without digging into corefx's source code. Also it can help user avoid NullReferenceException/ArgumentException caused by null value at compile time. 
As well as ASP.NET Core

**Comment by stephentoub** [comment]
It is a monumental effort to correctly annotate the .NET Core surface area and implementation. It is in progress, but it's going to take awhile.
