### ISSUE TITLE
Unsafe.Unbox<T> should reinterpret boxed 'object' handle as IntPtr

### ISSUE THREAD

**Issue by glenn-slayden** [dotnet/corefx#36386]
Minor point, although the **Unsafe** methods are never intended to be verifiable, it is trivial to eliminate at least one **PEVerify** error (`0x8013187B` "Value type expected"), namely in the **Unbox** API.  

Since the `unbox T` instruction requires value-type `T`, the following function should issue `conv.i` or `conv.u` in order to re-interpret the supplied object reference as the `IntPtr` valuetype that it also is. 

https://github.com/dotnet/corefx/blob/8c0f15cb5fa7919056f0882660556ead69fe9887/src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.il#L306-L313

Like so:

    ldarg box
    conv.i             // <--
    unbox !!T
    ret

Works like a charm, minus one **PEVerify** error.

**Comment by glenn-slayden** [comment]
See also https://github.com/dotnet/corefx/issues/30730

**Comment by glenn-slayden** [comment]
On second thought, this could be a false-positive or bogus error from **PEVerify**. How is the "thing to unbox" which is on the top of the IL execution stack for the `unbox` instruction ever _not_ an object reference?

**Comment by jkotas** [comment]
Reiniterpreting object as IntPtr is not verifiable either; and adding it as you propose would introduce GC hole.

**Comment by glenn-slayden** [comment]
Thanks for the info. I suspected there might be a hole in the absence of `stobj`.
