### ISSUE TITLE
Where is source code of System.Drawing.Primitive of 4.3.0? 

### ISSUE THREAD

**Issue by sgdcHewei** [dotnet/corefx#36396]
I am using the following nuget package of the following https://www.nuget.org/packages/System.Drawing.Primitives/
version 4.3.0
But the master branch source code seems have version 4.2.0
Where can I get the source code for 4.3.0?

Thanks

**Comment by ahsonkhan** [comment]
> But the master branch source code seems have version 4.2.0

This is the assembly version, not the NuGet package version: 
https://github.com/dotnet/corefx/blob/d3eed78a3765aef0325384c61a4593570ae3622b/src/System.Drawing.Primitives/Directory.Build.props#L4

> Where can I get the source code for 4.3.0?

The [release/1.1.0](https://github.com/dotnet/corefx/tree/release/1.1.0/src/System.Drawing.Primitives) branch contains the source that was packaged/published to NuGet (i.e. https://www.nuget.org/packages/System.Drawing.Primitives/4.3.0)
https://github.com/dotnet/corefx/blob/82cce14f0c8188a2218ec5dc9a55977ccdba02e0/pkg/Microsoft.Private.PackageBaseline/packageIndex.json#L1282-L1292

The master branch contains the source for the in-box assembly (as part of .NET Core 2.0+), not the standalone NuGet package.
https://github.com/dotnet/corefx/blob/d3eed78a3765aef0325384c61a4593570ae3622b/pkg/Microsoft.Private.PackageBaseline/packageIndex.json#L1759-L1783

Hopefully that helps clarifies things.

cc @alexperovich

**Comment by ViktorHofer** [comment]
Closing. If you have further questions feel free to reopen.
