### ISSUE TITLE
How can know the exact corefx commit of a corefx nuget package?

### ISSUE THREAD

**Issue by sillyousu** [dotnet/corefx#36394]
I want to track down a bug relate to [System.IO.Pipelines 4.5.3 ](https://www.nuget.org/packages/System.IO.Pipelines/4.5.3) .
But which commit in corefx repo I shoud look into?

```
Commonly Used Types:
System.IO.Pipelines.Pipe
System.IO.Pipelines.PipeWriter
System.IO.Pipelines.PipeReader

99ce22c306b07f99ddae60f443d23a983ae78f7b 
When using NuGet 3.x this package requires at least version 3.4.
```
The commit hash on [nuget.org ](https://www.nuget.org/packages/System.IO.Pipelines/4.5.3)is misleading.  
The dll symbol does not match this commit.

**Comment by sillyousu** [comment]
ref https://github.com/dotnet/corefx/issues/31935

**Comment by svick** [comment]
What makes you think the symbols do not match?

**Comment by sillyousu** [comment]
@svick  My colleague upgrade the dependency. I just know that. closing
