### ISSUE TITLE
Creating different XName instances in the empty namespace leaks memory

### ISSUE THREAD

**Issue by Thiez** [dotnet/corefx#36404]
The following loop will eventually fill all memory:

```csharp
while (true)
{
    XName _ = $"x{Guid.NewGuid()}";
// or XName.Get($"x{Guid.NewGuid()}");
}
```

This is because `XNamespace` contains a `XHashtable` that keeps track of all `XName` instances that have ever been created within that namespace. However, the empty namespace lives forever (`XNamespace.None`), so no name allocated within that namespace will ever expire.

Note that this problem does not occur when the namespace is eligible for garbage collection, e.g. the following code can run forever in a small amount of memory:

```csharp
while (true)
{
    XName.Get($"x{Guid.NewGuid()}", $"x{Guid.NewGuid()}");
}
```

While obviously no sane developer should write the indicated loops, this implicit interning can be abused to DOS a server that uses `XDocument` for parsing XML. E.g. in the following example, imagine that the loop is actually a request handler of some sort, and the xml is supplied by a (hostile) external actor.

```csharp
string ReceiveExternalRequest() {
    return $"<x{Guid.NewGuid()} />";
}

while (true) {
    var xml = ReceiveExternalRequest();
    XDocument.Parse(xml);
}
```

**Comment by GrabYourPitchforks** [comment]
Thank you for the report and clear repro. We'll look into this.

**Comment by buyaa-n** [comment]
Thank you @Thiez for reporting, we acknowledge there's an issue there, but the solutions investigated have a non-trivial performance impact on all use cases, and the issue cited has been around for a long time with very few reported issues resulting from it. So we are not going to fix it at this point. It can be revisited in the future should it be demonstrated to be a larger concern than anticipated.
