### ISSUE TITLE
ImmutableList.Contains is few times slower that List.Contains or LinkedList.Contains

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/corefx#36407]
How to run the benchmarks:

```cmd
git clone https://github.com/dotnet/performance.git
# if you have .NET Core 3.0 installed
dotnet run -c Release -f netcoreapp3.0 -p .\performance\src\benchmarks\micro\MicroBenchmarks.csproj --filter *ContainsFalse*List *ContainsTrue*List --join
# if you don't have .NET Core 3.0 installed
py .\performance\scripts\benchmarks_ci.py -f netcoreapp3.0 --filter *ContainsFalse*List *ContainsTrue*List --bdn-arguments="--join true"
```

|                  Type |        Method | Size |         Mean |
|---------------------- |-------------- |----- |-------------:|
|  ContainsFalse&lt;Int32&gt; |          List |  512 |    133.49 us |
| ContainsFalse&lt;String&gt; |          List |  512 |    874.65 us |
|   ContainsTrue&lt;Int32&gt; |          List |  512 |     71.70 us |
|  ContainsTrue&lt;String&gt; |          List |  512 |    482.38 us |
|  ContainsFalse&lt;Int32&gt; |    LinkedList |  512 |    440.38 us |
| ContainsFalse&lt;String&gt; |    LinkedList |  512 |  1,377.87 us |
|   ContainsTrue&lt;Int32&gt; |    LinkedList |  512 |    224.22 us |
|  ContainsTrue&lt;String&gt; |    LinkedList |  512 |    672.24 us |
|  ContainsFalse&lt;Int32&gt; | ImmutableList |  512 | 13,338.16 us |
| ContainsFalse&lt;String&gt; | ImmutableList |  512 | 24,118.15 us |
|   ContainsTrue&lt;Int32&gt; | ImmutableList |  512 |  6,590.86 us |
|  ContainsTrue&lt;String&gt; | ImmutableList |  512 | 12,033.68 us |

Full docs for the new benchmarking workflow: https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-corefx.md

**Comment by shortspider** [comment]
@adamsitnik I've taken a stab at this in #40540.

Here are the results before my changes:

Type |        Method | Size |         Mean 
-- |-- |-- |--
  ContainsFalse<Int32> |          List |  512 |     66.24 us 
 ContainsFalse<String> |          List |  512 |    896.36 us 
   ContainsTrue<Int32> |          List |  512 |     33.75 us 
  ContainsTrue<String> |          List |  512 |    467.96 us 
  ContainsFalse<Int32> |    LinkedList |  512 |    462.66 us 
 ContainsFalse<String> |    LinkedList |  512 |  1,579.11 us 
   ContainsTrue<Int32> |    LinkedList |  512 |    212.49 us 
  ContainsTrue<String> |    LinkedList |  512 |    706.79 us 
  ContainsFalse<Int32> | ImmutableList |  512 |  7,717.98 us
 ContainsFalse<String> | ImmutableList |  512 | 22,193.37 us 
   ContainsTrue<Int32> | ImmutableList |  512 |  3,514.81 us
  ContainsTrue<String> | ImmutableList |  512 | 10,200.01 us

And after

Type |Method | Size |Mean 
 -- |-- |-- |--
  ContainsFalse<Int32> |          List |  512 |    67.65 us 
 ContainsFalse<String> |          List |  512 |   997.93 us 
   ContainsTrue<Int32> |          List |  512 |    34.98 us 
  ContainsTrue<String> |          List |  512 |   533.55 us 
  ContainsFalse<Int32> |    LinkedList |  512 |   503.57 us 
 ContainsFalse<String> |    LinkedList |  512 | 1,775.85 us
   ContainsTrue<Int32> |    LinkedList |  512 |   214.58 us 
  ContainsTrue<String> |    LinkedList |  512 |   724.15 us 
  ContainsFalse<Int32> | ImmutableList |  512 | 1,226.45 us 
 ContainsFalse<String> | ImmutableList |  512 | 3,242.86 us 
   ContainsTrue<Int32> | ImmutableList |  512 |   643.22 us 
  ContainsTrue<String> | ImmutableList |  512 | 1,558.64 us

**Comment by Symbai** [comment]
Your results show a 10-12% regression on List and LinkedList after changes but you didn't modified them. Either the test code isn't good or the test results. Have you run them multiple times and do you still get a 10-12% regression?

**Comment by shortspider** [comment]
@Symbai I've attached files with 3 runs with and without my changes. There isn't a flat regression in List/LinkedList but there is variance between the runs. That might just be my machine, do you see the same results if you run them locally?

[runs-without-changes.txt](https://github.com/dotnet/corefx/files/3535737/runs-without-changes.txt)
[runs-with-changes.txt](https://github.com/dotnet/corefx/files/3535745/runs-with-changes.txt)

**Comment by adamsitnik** [comment]
@shortspider thank you for your contribution! the improvements are really impressive!
