### ISSUE TITLE
.Net Core 2.2 Exception 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException'

### ISSUE THREAD

**Issue by matendie** [dotnet/corefx#36401]
This exception is continuing to show up... 
Exception thrown: 'System.NotImplementedException' in System.Private.CoreLib.dll
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 1364.9437ms 500 text/html; charset=utf-8
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll
The thread 0x1148 has exited with code 0 (0x0).
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll
The thread 0x6538 has exited with code 0 (0x0).
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll

**Comment by wfurt** [comment]
Could you share some simle repro code @matendie ? This is not actionable without more details. 
Also include info about your os and general environment.

**Comment by matendie** [comment]
hm... I have another .NET core 2.2 API that doesn't have this issue. The
problematic one is already complex enough that It will be difficult for me
to figure out what triggers it. I don't think its the system, since I have
another API that is not having this problem.

Let me investigate a little more before I can give you more info. Looks
like its related to some other assembly I'm including, but not sure which
one.

Tad

**Comment by davidsh** [comment]
I've seen this exception on Linux this past week using .NET `Dns.GetHostAddressesAsync` I will try to post repro code soon.  It was trying to resolve a name that couldn't be resolved.

This exception is unusual.  We should never be exposing `System.Net.Internals.SocketExceptionFactory.ExtendedSocketException` to an API caller of Socket or DNS APIs.  It should have been transformed into a SocketException, for example.

**Comment by matendie** [comment]
Im running Windows 10 as a parallel on Mac Pro. Don't ask, not my decision,
LOL.
Im not sure when this exception started showing up, i just noticed it today
when my call to external API failed and I used tracing to look at the stack
and the request.
I have some remaining nuget libs that I need to get cleared up. Some didn't
do what I needed. I can give you a list of things my projects include. If
that helps at all for now?

Tad

**Comment by matendie** [comment]
Here are the included libraries in the project... Like I said, I'm not sure
if its related to any of these, but if you see anything that may be a
suspect, that you want me to try removing to test, let me know.

[image: image.png]

[image: image.png]

**Comment by davidsh** [comment]
@matendie Your last message didn't include any actual screenshots.  It just says "image.png".

**Comment by matendie** [comment]
here is more info on what's in the project:

Library responsible to AAD Bearer Token Authentication:

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.2.0" />
    <PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" Version="4.5.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.4.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.IdentityModel.Tokens.Jwt">
      <HintPath>..\..\..\Program Files\dotnet\sdk\NuGetFallbackFolder\system.identitymodel.tokens.jwt\5.2.0\lib\netstandard1.4\System.IdentityModel.Tokens.Jwt.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>

API that gets called from outside and calls other external APIs:
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <UserSecretsId>guid</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Extensions.DiagnosticAdapter" Version="2.2.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="4.0.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.5.0" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="4.5.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Custom.ADAuthentication.Provider\Custom.ADAuthentication.Provider.csproj" />
    <ProjectReference Include="..\Custom.projectDataLayer.Service\Custom.projectDataLayer.Service.csproj" />
    <ProjectReference Include="..\Custom.projectAuthentication.Service\Custom.projectAuthentication.Service.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Swagger\" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="HibernatingRhinos.Profiler.Appender">
      <HintPath>..\..\..\Users\username\Downloads\EntityFramework.Profiler-v5.0-Build-5032\Appender\net46\HibernatingRhinos.Profiler.Appender.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>

Data Layer EF specific :
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.2" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Command\" />
  </ItemGroup>
</Project>


I did have a custom library  but I removed it since I didn't need it:
https://github.com/hanssens/localstorage

**Comment by karelz** [comment]
@davidsh do you have suggestions for next steps?

**Comment by davidsh** [comment]
>@davidsh do you have suggestions for next steps?

Next step is for us to reproduce the problem and see where this weird exception is coming from.

**Comment by matendie** [comment]
I'm looking in to this again... I switched over from VS2017 Pro to VS 2019 Pro and the exception is no longer showing in output window. If I open it back in VS2017 Pro exception shows back up again
```
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Internals.SocketExceptionFactory.ExtendedSocketException' in System.Private.CoreLib.dll
```

I'm not sure what the debugger difference is between the two VS versions, could new one be hiding it, or is the old one causing it?

No Idea.

**Comment by karelz** [comment]
There should be no difference in the same .NET Core 2.2 version behavior in one VS or another, or outside.
Can you please run it outside of VS?
I would also recommend trying older VS 2017 in a brand new VM with fresh installation to avoid some corrupted install /config problems.

**Comment by matendie** [comment]
I'm not sure how to run it outside of VS and have visibility to exceptions thrown... I published this API to Azure and I don't see any exceptions thrown in Application Insights. Maybe this is a VS 2017 issue?

**Comment by karelz** [comment]
You can try to isolate it and move it outside of ASP.NET Core first. Or you can try to create repro on brand new VM (fresh install).

Rather than VS 2017 issue, it is more likely to be some weird environment setting / debugging setting in your VS.
I recommend to not chase it down, unless you have something actionable - you may opt in to debug the exception and find out what triggered it.
Closing for now, feel free to reopen if there is anything actionable for us. Thansk!

**Comment by matendie** [comment]
Ok will do, thank you!

**Comment by lhsomoza** [comment]
I have the same issue, it does not provide much information for troubleshooting.

**Comment by wfurt** [comment]
can you isolate simple corefx repro @lhsomoza 
notes here are not actionable so far.

**Comment by plemanach** [comment]
I can reproduce it on a simple console on ubuntu 

`class Program
    {
        static void Main(string[] args)
        {
             Console.WriteLine(Dns.GetHostAddressesAsync("nonexistenthost").Result);
        }
    }`

`Unhandled Exception: System.AggregateException: One or more errors occurred. (No such device or address) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.ResolveCallback(Object context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at DnsTest.Program.Main(String[] args) in /home/plemanach/plemanach/DnsTest/Program.cs:line 10
`

`dotnet --version
2.2.401
`
