### ISSUE TITLE
List<T>.ForEach async action is not blocked

### ISSUE THREAD

**Issue by ayayalar** [dotnet/corefx#36425]
List<T>.ForEach method allows to pass an `async Action<T>` as a parameter. However it doesn't `await` internally. I would think the compiler would generate at least a warning about this usage if `ForEach` does not fully support `async Action<T>`.

**Comment by stephentoub** [comment]
The ForEach method doesn't know anything about async... all it knows is that it takes a void-returning delegate that it invokes for each item.  It's the compiler that's allowing an async method to be used here, treating it as an async void.

https://devblogs.microsoft.com/pfxteam/potential-pitfalls-to-avoid-when-passing-around-async-lambdas/
