### ISSUE TITLE
Nullable: Compiler issues

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#36427]
Joint issue for compiler issues related to Nullable feature.

Design questions:
- [Virtual/Abstract members: is it safe to mark them non-nullable?](https://github.com/dotnet/coreclr/pull/23459#discussion_r269316953)
  - mark according to what user would expect (i.e. object.ToString should return non-nullable, even though it is possible to return null)
  - https://github.com/dotnet/coreclr/pull/23466#discussion_r269772689

Bugs:
- [initialization of fields is not being correctly tracked](https://github.com/dotnet/coreclr/pull/23486/files/2ed95a7d5892416a24376b854d3eb8817d4112f6#diff-9c434c19c2163aa15448cd87e7f1afe7R28)
- [nullable foo + `foo == null || foo.Bar()`](https://github.com/dotnet/coreclr/pull/23486#discussion_r269669007)
- [initialization using Interlocked.CompareExchange](https://github.com/dotnet/coreclr/pull/23459#discussion_r269301985)
- [marking abstract/virtual member nullable does not let you restrict it in derived classes](https://github.com/dotnet/coreclr/pull/23466#discussion_r269800779)
- [caching the result of a null comparison value forces you to use ! operator](https://github.com/dotnet/coreclr/pull/23450/files#r269128254).

cc: @jaredpar @jcouv @stephentoub

**Comment by buyaa-n** [comment]
Bug: Compiler complaining when assagning nullable value to non nullable after checking it was not null 
```csharp
if (c[i] != null)
        ret[cnt++] = c[i]!;
```
https://github.com/dotnet/coreclr/pull/23489#discussion_r269756279

**Comment by danmosemsft** [comment]
For compiler issues we should presumably be opening bugs (with mini reproes) against Roslyn as we go along -- @jaredpar  ?

**Comment by danmosemsft** [comment]
I assume it is easier to construct a mini repro while reproing the issue, rather later from an old PR comment 😺

**Comment by buyaa-n** [comment]
Similar bug: assigning nullable value after indirect null check throwing compiler error https://github.com/dotnet/coreclr/pull/23489#discussion_r269701201

**Comment by jcouv** [comment]
> For compiler issues we should presumably be opening bugs (with mini reproes) against Roslyn as we go along

Yes, please.

**Comment by krwq** [comment]
some of them might be fixed in the latest compiler version. @safern and @tannergooding will update coreclr compiler soon and we will try again and see if still repros - if still does then we will file issues.

**Comment by krwq** [comment]
ref: https://github.com/dotnet/coreclr/pull/23526#discussion_r270193836

**Comment by krwq** [comment]
ref: https://github.com/dotnet/coreclr/pull/23526#discussion_r270195225

**Comment by joperezr** [comment]
@krwq what is the difference between this issue and #36384 ?

**Comment by stephentoub** [comment]
I think this can be closed.  All of these issues are tracked individually in the roslyn and csharplang repos, and we've been linking to those directly from the code.
