### ISSUE TITLE
ImageConverter throws ArgumentException while converting OLE image

### ISSUE THREAD

**Issue by pavelovcharov** [dotnet/corefx#36439]
ImageConverter throws ArgumentException in the following code
```c#
        [Test]
        public void ImageWithOLEHeader() {
            var type = GetType();
            var assembly = type.Assembly;
            using(var imageStream = assembly.GetManifestResourceStream(assembly.GetName().Name + ".NorthwindDBImage.bmp")) {
                using(var ms = new MemoryStream()) {
                    imageStream.CopyTo(ms);
                    var converter = new ImageConverter();
                    var image = converter.ConvertFrom(ms.ToArray());
                    Assert.IsNotNull(image);
                }
            }
        }
```
Result StackTrace:	
```
at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
   at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement, Boolean validateImageData)
   at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement)
   at System.Drawing.Image.FromStream(Stream stream)
   at System.Drawing.ImageConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.TypeConverter.ConvertFrom(Object value)
   at netcore3_ImageWithOLEHeader.TestClass.ImageWithOLEHeader() in C:\Work\github\netcore3_ImageWithOLEHeader\netcore3_ImageWithOLEHeader\Program.cs:line 22
```

The issue is not reproduced in .NET Framework 4.7.

I have prepared a small sample to demonstrate the issue: https://github.com/pavelovcharov/netcore3_ImageWithOLEHeader

Environment info:

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview4-010776
 Commit:    5a3b17f24a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview4-010776\

Host (useful for support):
  Version: 3.0.0-preview4-27517-02
  Commit:  843acd2ab1

.NET Core SDKs installed:
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009497 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.601 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  3.0.100-preview4-010702 [C:\Program Files\dotnet\sdk]
  3.0.100-preview4-010776 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview4-19167-01 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27517-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview4-27512-47 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by ericstj** [comment]
This is the same as https://github.com/dotnet/corefx/issues/36525

**Comment by ericstj** [comment]
Thank you for the report!

**Comment by ericstj** [comment]
Also, you may want to try calling the stream constructor of the type using Activator.CreateInstance, this avoids the intermediate byte[] and also the TypeConverter issue.

It's similar to how a lot of these images were handled when reading from resx: 
https://github.com/dotnet/winforms/blob/400c8d6de27ec6b96cf935cb3bb56243b68509f8/src/System.Windows.Forms/src/System/Resources/ResXFileRef.cs#L268

**Comment by ericstj** [comment]
Reactivating, this appears to be different.

**Comment by ericstj** [comment]
Yeah, this is because we're missing this code that strips the OLE Header. https://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/ImageConverter.cs,181

Adding that back is straight-forward enough.  @pavelovcharov where did you produce such a bitmap from?  It looks to me like none of the editors I tried could open this.

**Comment by pavelovcharov** [comment]
It's from the Northwind database

**Comment by Anipik** [comment]
@pavelovcharov can you describe how you obtained the image from the northwind database ?

**Comment by Anipik** [comment]
@JeremyKuhne this is the ole header related issue.

**Comment by pavelovcharov** [comment]
> @pavelovcharov can you describe how you obtained the image from the northwind database ?

We just took a byte array and saved it to as a bmp file.

**Comment by Anipik** [comment]
is it just a random byte array in csharp ?

**Comment by pavelovcharov** [comment]
The image was stored in the database as a byte array. We took this byte array and save to the file.
