### ISSUE TITLE
SRM MetadataReader.GetNamespaceDefinitionRoot() is not thread-safe

### ISSUE THREAD

**Issue by dgrunwald** [dotnet/corefx#36430]
`NamespaceCache.GetRootNamespace()` suffers from a race condition:

When thread 1 is currently inside `PopulateNamespaceTable()`
```c#
            lock (_namespaceTableAndListLock)
            {
               ...
                _namespaceTable = namespaceTable;
                // thread 1 currently here
                _rootNamespace = namespaceTable[rootNamespace];
            }
```
Another thread calling `GetRootNamespace()` will observe that `_namespaceTable != null`, skip acquiring the lock, and then return the possibly-still-uninitialized `_rootNamespace`.

The two stores at the end of the lock need to be swapped, and `_namespaceTable` should be marked volatile (AFAIK volatile is required to ensure the CPU actually performs the loads/stores in the correct order, at least on non-x86/x64 CPUs).

The resulting `NullReferenceException` due to the uninitialized `NamespaceDefinition` caused [one of our ILSpy CI builds](https://ci.appveyor.com/project/icsharpcode/ilspy/builds/23409493/job/oij7qe32fncod4hv) to randomly fail.

**Comment by tmat** [comment]
Yes, there is a race condition. Thanks for finding this!

**Comment by MarcoRossignoli** [comment]
or check for `_rootNamespace != null` no?
