### ISSUE TITLE
Ensure we build versionless configurations for all references

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#36451]
The following references create problems for source build:
https://github.com/dotnet/corefx/blob/b22beb2990d2186abf839fb9144443ad6578018c/external/binplacePackages/binplacePackages.depproj#L29-L37
https://github.com/dotnet/corefx/blob/b22beb2990d2186abf839fb9144443ad6578018c/external/netstandard/netstandard.depproj#L55-L64

We need to make sure that these PackageReferences won't be active for `netstandard` nor `netcoreapp` BuildConfigurations.  We need to make sure that the ref projects maintain a configuration for these (that may mean ifdefing).

https://github.com/dotnet/source-build/issues/884

/cc @ViktorHofer

**Comment by ViktorHofer** [comment]
I think when I started to harvest System.Memory I made sure that we respect sourcebuild. It shouldn't run on netcoreapp or netstandard (besides TargetsNetstandard which I assume is the netstandard test suite?)

**Comment by ericstj** [comment]
> besides TargetsNetstandard which I assume is the netstandard test suite?

`TargetsNetstandard` is true for any netstandard targetgroup.  It saves you from having to do string comparisons against targetgroup.

This still restores and copies System.Memory ref to bin\ref\netstandard.  
We need a netstandard ref for System.Memory so that other netstandard configurations that build during source build can use it.  They cannot depend on packages.
We do not build a netstandard ref. 
https://github.com/dotnet/corefx/blob/b22beb2990d2186abf839fb9144443ad6578018c/src/System.Memory/ref/Configurations.props#L3-L6.

**Comment by ViktorHofer** [comment]
ok makes sense 👍

**Comment by ericstj** [comment]
We actually may be able to avoid this.  Source build has infra for proucing ref-only packages to consume for this purpose: https://github.com/dotnet/source-build-reference-packages/tree/master/src/referencePackages/src.

I'm going to see about leveraging this instead of complicating our repo with source that we don't ship.

**Comment by ericstj** [comment]
Closing this since we have an Ack that source build will produce reference packages for these.
