### ISSUE TITLE
ChineseLunisolarCalendar year 2057 and 2089 incorrect  

### ISSUE THREAD

**Issue by KalibGao** [dotnet/corefx#36454]
https://github.com/dotnet/corefx/blob/bf1e52f51f30fb9e97077e9ce2a8e19a9c2c1f16/src/Common/src/CoreLib/System/Globalization/ChineseLunisolarCalendar.cs#L204

https://github.com/dotnet/corefx/blob/bf1e52f51f30fb9e97077e9ce2a8e19a9c2c1f16/src/Common/src/CoreLib/System/Globalization/ChineseLunisolarCalendar.cs#L236

Hey there, 
  With running xunit test, some date info could not match when `System.Globalization.ChinseLunisolar` class convert `DateTime`  to local time.   I found that `s_yearInfo` field (the year  2057 and 2089)  have some minor problem, the source and comments could not match the real output. 

```csharp
var dateTime = new DateTime(2057, 10, 14, 13, 24, 14);
// var dateTime =  new DateTime(2089, 9, 19, 21, 15, 52);
ChineseLunisolarCalendar chineseLunisolarCalendar = new ChineseLunisolarCalendar();
Console.Write("days in month: ");
for (int i = 0; i < 12; i++)
{
       Console.Write(chineseLunisolarCalendar.GetDaysInMonth(2057, i + 1) + " ");
}
// year 2057 output   : 29   30   30   29   30   29   30   30   29   29   30   29
// year 2057 in source:  29   30   30   29   30   29   30   29   30   29   30   29  
// the index 7 and 8 need reverse.

// year 2089 output    : 30   30   29   30   29   29   30   29   29   30   30   29
// year 2089 in source : 30   30   29   30   29   29   29   30   29   30   30   29
// the index 7 and 8 need reverse.

// update: also 2097
// output: 30   29   30   29   29   30   29   29   30   30   29   30     
// source: 30   29   30   29   29   29   30   29   30   30   29   30
// the index 5 and 6 need reverse.
```

Curious about released-sdk is different from source code.

**Comment by Gnbrkm41** [comment]
Can't seem to repro on my end. Windows 10 Pro x64 Insider Preview 1903 (Build No. 18362.1), Korean

2057
```
Actual:   29 30 30 29 30 29 30 29 30 29 30 29
Expected: 29 30 30 29 30 29 30 29 30 29 30 29
```
2089
```
Actual:   30 30 29 30 29 29 29 30 29 30 30 29
Expected: 30 30 29 30 29 29 29 30 29 30 30 29
```

Nit: Title Chinse -> Chinese. 😀

**Comment by tarekgh** [comment]
@KalibGao We have fixed some issue in Chinese Lunisolar calendar in .NET Core https://github.com/dotnet/coreclr/issues/19480. Are you using .NET Core or you are running on the full framework? I guess you are running on the full framework and looking at the sources of the .NET Core. The change in .NET Core is done in purpose to make this calendar more accurate. This change didn't get ported to the full framework for app comparability reason there.

Let me know if you still have any question here.

CC @elyoh

**Comment by KalibGao** [comment]
Thanks, @tarekgh, it's duplicated.
