### ISSUE TITLE
missing methods on System.IO.Packaging.PackUriHelper that were in WindowsBase

### ISSUE THREAD

**Issue by stevenbrix** [dotnet/corefx#36459]
This is the list of public types on the PackUriHelper class from WindowsBase that are no longer in the PackUriHelper as part of CoreFX:

```c#
        public static Uri GetPackageUri(Uri package);
        public static Uri Create(Uri uri);
        public static Uri Create(Uri uri, Uri partName);
        public static int ComparePackUri(Uri uri, Uri uri2);
```

These should be added back so applications porting to .NET Core aren't broken

**Comment by stephentoub** [comment]
These methods were removed from Core when UriParser.Register wasn't available, at which point they were broken. With Register now available, seems fine to bring them back.
