### ISSUE TITLE
UriBuilder.Query property setter is not idempotent

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/corefx#3646]
The `UriBuilder.Query` property setter prepends the supplied value with a `?` character, even if the supplied value already starts with `?`.

https://github.com/dotnet/corefx/blob/41e203011152581a6c65bb81ac44ec037140c1bb/src/System.Private.Uri/src/System/UriBuilder.cs#L277

This means that code calling the `Query` setter has to check to ensure the value it's passing doesn't already have the question mark even when hoping to simply append to the end of the query.

Here's example code that suffers from the issues this surfaces:

``` csharp
var uri = new UriBuilder("http://localhost/page?param1=foo");

if (someOption) {
    uri.Query += "&someOption=true";
}
```

Expected value of uri.Query:
`?param1=foo&someOption=true`

Actual value of uri.Query:
`??param1=foo&someOption=true`

**Comment by davidsh** [comment]
cc: @CIPop @SidharthNabar

**Comment by hughbe** [comment]
FYI, there is similar behaviour for the setter for Fragment
