### ISSUE TITLE
Error: System.Net.Http.HttpRequestException: Connection refused

### ISSUE THREAD

**Issue by HenrikBach1** [dotnet/corefx#36475]
Hi,

I have difficulties in understanding why an application hickups on the localhost ip address 127.0.0.1 with any port address with this error:

```
System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
```

What does .NET Core need to accept to listen on the localhost ip address?

Thank you.

/Henrik

**Comment by stephentoub** [comment]
This error is just coming from the OS when we try to connect.  It sounds like whatever you're trying to connect to isn't listening.

**Comment by HenrikBach1** [comment]
OK, I understand your clarification, when it is a client application.

However, my understanding of the application is that it sets up ports for listening on the given addresses and ports, thus it basically is a server application. So, what does .NET Core need to accept to listen on the localhost ip and port addresses?

**Comment by stephentoub** [comment]
I do not understand. What application? Do you have a small repro of the problem? You would need a socket bound to loopback and listening. It's no different from any other socket use.

**Comment by wfurt** [comment]
You can run tcpdump or wireshark and capture traffic on loopback and given port. 
You can also can also use `netstat -an` to see if the there is anything listening on port you expect.

**Comment by HenrikBach1** [comment]
There isn't anything listening on the port I expect with `netstat -an`. 

I'll try to investigate and make a small repro of the application.

**Comment by davidsh** [comment]
>There isn't anything listening on the port I expect with netstat -an.

The error "Connection refused" is expected from HttpClient if there isn't anything listening on the port to connect to.

If you are able to reproduce the problem and have something listening on the port, please let us know.  Thanks.
