### ISSUE TITLE
The AttritubteWildcard.Namespace does not contain a value if an intersection or union is used

### ISSUE THREAD

**Issue by JosVerburg** [dotnet/corefx#36484]
I've noticed that the `AttributeWildcard.Namespace` does not contain the correct value when it requires a union or intersection to be calculated.

In the code sample below I've used a schema with 2 elements. The first one `el1` has a `xs:anyAttribute` which allows the namespaces `http://foo.com` and `http://bar.com`, since we also get a `xs:anyAttribute` from the attribute group `group1` the intersection should be the value.
The second element shows that the `AttributeWildcard.Namespace` is set when no intersection needs to be done.
Describe here: https://www.w3.org/TR/xmlschema-1/#element-anyAttribute

I've noticed that the correct list of allowed namespaces is available in the internal property `NamespaceList`. So I'd think we could return a value based the `NamespaceList` instead of having a separate string. (I didn't yet look into how/when the string is set). Let me know if you'd like to see a pull request for this :)

```csharp
using System;
using System.IO;
using System.Reflection;
using System.Xml.Schema;

namespace ConsoleApp1
{
	public class Program
	{
		public static void Main(string[] args)
		{
			const string xsd = @"<?xml version=""1.0""?>
<xs:schema
	xmlns:xs=""http://www.w3.org/2001/XMLSchema"">
	<xs:element name=""el1"">
		<xs:complexType>
			<xs:attributeGroup ref=""group1""/>
				<!-- The result should be the intersection of this xs:anyAttribute and the xs:anyAttribute of group1 -->
				<xs:anyAttribute namespace=""http://foo.com http://bar.com""/>
		</xs:complexType>
	</xs:element>
	<xs:element name=""el2"">
		<xs:complexType>
			<xs:attributeGroup ref=""group1""/>
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name=""group1"">
		<xs:anyAttribute namespace=""http://foo.com""/>
	</xs:attributeGroup>
</xs:schema>";
			XmlSchema schema;
			using (var reader = new StringReader(xsd))
				schema = XmlSchema.Read(reader, (sender, e) =>
				{
					throw e.Exception;
				});

			var schemaSet = new XmlSchemaSet();
			schemaSet.Add(schema);
			schemaSet.Compile();

			foreach (XmlSchemaElement element in schemaSet.GlobalElements.Values)
			{
				Console.WriteLine($"====={element.Name}=====");
				var attributeWildcard = ((XmlSchemaComplexType)element.ElementSchemaType).AttributeWildcard;
				Console.WriteLine("Public property:   " + (attributeWildcard.Namespace ?? "AttriubteWildcard does not contain the calculated namespace :("));
				var namespaceList = attributeWildcard.GetType().GetProperty("NamespaceList", BindingFlags.Instance | BindingFlags.NonPublic).GetValue(attributeWildcard);
				Console.WriteLine("Internal property: " + namespaceList);
			}
			// Outputs:
			// =====el1=====
			// Public property:   AttriubteWildcard does not contain the calculated namespace :(
			// Internal property: http://foo.com
			// =====el2=====
			// Public property:   http://foo.com
			// Internal property: http://foo.com
		}
	}
}
```

**Comment by JosVerburg** [comment]
@karelz Could you indicate whether the internal property `NamespaceList` will indeed hold the correct value or check this with the expert in this area?
I've done some tests with a small schema in which the `NamespaceList` had to be filled with either a union or intersection of the namespaces, and as far as I've seen it always seems to be correct.

And would it be likely to be merged if we create a pull request for this?

**Comment by krwq** [comment]
@JosVerburg solution you have proposed sounds correct. Quick looking in the spec I couldn't find info that intersection should be performed but presumably the code is already doing so internally and the fix will be just reporting the value correctly.

Yes, pull request would be perfect!

**Comment by krwq** [comment]
Marking as future since this is not required for the current release but will likely be included if fix and corresponding test is sent in the pull request.

**Comment by JosVerburg** [comment]
@krwq Can you assign the issue to me? I'll try to create a pull request in the next week.

**Comment by krwq** [comment]
Thanks @JosVerburg!
