### ISSUE TITLE
Obsolete Microsoft.Extensions.Hosting.IApplicationLifetime is not marked in code

### ISSUE THREAD

**Issue by EdiWang** [dotnet/corefx#36509]
**Steps:**
1. Use IApplicationLifetime interface
2. Figure out which namespace it lives in
3. Read Microsoft docs: `Microsoft.Extensions.Hosting.IApplicationLifetime` is obsolete (https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.iapplicationlifetime?view=aspnetcore-2.2)
4. Use `Microsoft.AspNetCore.Hosting.IApplicationLifetime`

**Expected:**
There is [Obsolete] marked to the Microsoft.Extensions.Hosting.IApplicationLifetime, or there is a compiler warning.

**Actual:**
In Assembly Microsoft.Extensions.Hosting.Abstractions, Version=2.2.0.0, this interface do not have the [Obsolete] attribute and won't show a compiler warning.

![image](https://user-images.githubusercontent.com/3304703/55289629-53d6e600-53fb-11e9-8bec-331dfb7b9673.png)

**Info:** 
Version: .NET Core 2.2.3

**Comment by karelz** [comment]
It seems to be marked as obsolete in code now:
https://github.com/aspnet/AspNetCore/blob/7fe3b7640d6d4485a8f9005e4d22de3858420eb9/src/Hosting/Abstractions/src/IApplicationLifetime.cs#L15-L16

AspNetCore repo is better place for the issue if it is not fully addressed.
