### ISSUE TITLE
Potential Bug with a pinned GCHandle.Alloc call

### ISSUE THREAD

**Issue by Akaion** [dotnet/corefx#36511]
There's a problem with GCHandle.Alloc where if you try to allocate the same object (in my case the same byte array) with the GCHandle.Pinned parameter, it doesn't store the byte array again and instead just uses a reference to the first byte array that was stored.

Here's an example

```csharp
var bytes = new byte[] { 0x00, 0xFF, 0x00, 0xFF };

var buffer1 = GCHandle.Alloc(bytes, GCHandleType.Pinned);

var buffer1Address = buffer1.AddrOfPinnedObject();

var buffer2 = GCHandle.Alloc(bytes, GCHandleType.Pinned);

var buffer2Address = buffer2.AddrOfPinnedObject();
```

In this case, buffer1Address and buffer2Address will be the exact same.

I was just wondering if this is intentional or if it is indeed a bug?

If this is intentional maybe offering an option to not do this could be useful (at least in my case it is)

**Comment by stephentoub** [comment]
AddrOfPinnedObject returns the same address because it's the same object.  There's only one object here and thus only has one location in memory: AddrOfPinnedObject returns that location.

**Comment by GrabYourPitchforks** [comment]
To add to what @stephentoub said, I think the confusion might be coming from the `Alloc` method name. The `GCHandle.Alloc` method is allocating a new _handle_ to the object, not duplicating the object passed in to it. So if you compare the two `GCHandle` instances directly, you'll see that they have two different values for the stored handle, but each handle points to the exact same backing object. Hence the behavior you're seeing with `AddrOfPinnedObject`.

**Comment by Akaion** [comment]
I see what you mean. I was under the impression that the `Alloc` was allocating unmanaged memory for each object. Thanks for the clarification.
