### ISSUE TITLE
Avoid StackOverflowException when there are graph cycles in serialization

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#36510]
During serialization if there is a cycle in the object graph, a `StackOverflowException` is raised. Instead we should throw an `InvalidOperationException` or other exception TBD. `StackOverflowException` is non-recoverable.

To avoid this, we should use the `MaxDepth` setting. Note this setting is used during deserialization (where we throw a `InvalidOperationException`) but it currently is not used for serialization.

**Comment by Gnbrkm41** [comment]
Manually thrown `StackOverflowException` is recoverable (i.e. `throw new StackOverflowException`), if I remember correctly. Only the ones thrown by CLR (e.g. by recursion) cannot be caught by normal try-catch block.

**Comment by Gnbrkm41** [comment]
Oh, never mind, I think you meant these genuine `StackOverflowException`s....

**Comment by pranavkm** [comment]
@ajcvickers this might be of interest to EF.

**Comment by ajcvickers** [comment]
@pranavkm Thanks.
@steveharter Is there some mechanism for the serializer to handle cycles without throwing? If not, this will be pretty much a show-stopper for anyone serializing object graphs from an OR/M.

/cc @divega

**Comment by Andrzej-W** [comment]
To correctly serialize and deserialize object graphs from an OR/M we also need object references (https://www.newtonsoft.com/json/help/html/PreserveObjectReferences.htm).
Simple example: we want to serialize orders and customers. Two orders have a reference to one customer. After deserialization we have to have one customer object and not two with exactly the same property values.
