### ISSUE TITLE
Add Serializable attribute to System.Object 

### ISSUE THREAD

**Issue by aaabbbcccddd00001111** [dotnet/corefx#36515]
Add Serializable attribute to System.Object so that we can serialize and deserialize any object to and from System.IO.Stream using BinaryFormatter.

Now we need to add Serializable attribute to every class we need to serialize or deserialize.

**Comment by Wraith2** [comment]
This is very unlikely to happen. Serializable was removed and added back only where it is absolutely required for compatibility, see https://github.com/dotnet/corefx/issues/19119 for rationale and discussion.
