### ISSUE TITLE
[Proposal]: linq `where` with remove

### ISSUE THREAD

**Issue by ichensky** [dotnet/corefx#36521]
For ex. we have code: 
```csharp
var list =new List<string>(){
        "x",
        "x1",
        "x2",
        "x3",    
         
        "y",    
        "y1",
        "y2",
        "y3",    
        "y4",
            
        "z",    
        "z1",
        "z2"  
            
        };
```
And we want to select new list of lists like: 
```
[x:[x1,x2,x3], y:[y1,y2,y3,y4], z:[z1,z2]]
```
This can be done for ex. with code:
```csharp
var listOfList=
            // here we selecting root elements [x,y,z]
            list.Where(x=>x.Length==1)
            // here foreach root element we selecting sublist
            .Select(x=>
new KeyValuePair<string,List<string>>(x, list.Where(y=>y.IndexOf(x)==0)
```

But when we selecting sublists, for each root element we call method: 
```csharp
 list.Where(y=>y.IndexOf(x)==0
```
This peace of code could be optimized if we'd have in `linq` method for ex. like `WhereWithRemove`, which would select needed elements from the list and then remove them. 

This method can be used like:  
```csharp
var list = new List<int>(){1, 2, 3, 4, 5,6,7};
list.Where(x=>x>3 && x<7).ToList();  // now list= {1, 2, 3, 4, 5,6,7}
list.WhereWithRemove(x=>x>3 && x<7).ToList(); // now list={1,2,7}
```
And code above will be optimized to the:

```csharp
var tmp=list;
var listOfList=
            tmp.WhereWithRemove(x=>x.Length==1) // now tmp contains: {x1,x2,x3,y1,y2,y3,y4,z1,z2}
            .Select(x=>new KeyValuePair<string,List<string>>(x, 
                   tmp.WhereWithRemove(y=>y.IndexOf(x)==0) //after every iteration tmp will contains {y1,y2,y3,y4,z1,z2}, {z1,z2}, {}
```

Instead of method `WhereWithRemove` can be added overload for the method `Where` with flag 'remove', for ex.:

```csharp
       public static IEnumerable<TSource> Where<TSource>(
                  this IEnumerable<TSource> source, 
                  Func<TSource, bool> predicate, 
                  bool remove=false);

```

**Comment by Gnbrkm41** [comment]
`WhereWithRemove` will `select` and simultaneously remove the items from the original list? Not only that this would not work for generic IEnumerable<T>, it mutates the original list (If I remember correctly, every LINQ methods are pure functions, i.e. no side effects.).

**Comment by Wraith2** [comment]
First time Linqer here but would't a simple grouping do what you want?
```csharp
var result = from value in list
group value by value[0].ToString() into partition
select new KeyValuePair<string,List<string>>(
	partition.Key, 
	(from item in partition where item!=partition.Key select item).ToList()
);
```

**Comment by ichensky** [comment]
Yes grouping can be applied, but not if collection too big, because it becomes working slowly and can be optimized. Proposal to make a mechanism that will allow using the linq without additional overhead by changing current collection, while querying it.

**Comment by Wraith2** [comment]
In which case all the points raised by @Gnbrkm41 apply and make this sound like a very bad idea.

**Comment by svick** [comment]
@ichensky While I agree with others that the proposed solution would be a bad idea, if `GrouBy` does not work for you, maybe another approach would? So: can you provide an example where `GroupBy` is too slow and your proposal works well?

**Comment by Clockwork-Muse** [comment]
Frankly, I'm suspicious about the claims here: 
 - The presented method is _at least_ `O(n^2)` just for access (compared to possibly `O(n)` for the original), never mind the constant array shuffling.
 - The memory consumed is unlikely to be significantly better, given that the native output of `GroupBy` is largely identical in implication.

```csharp
// Yields IGrouping<char, string>, which is functionally equivalent to the KeyValuePair<string, List<string>> you were using.
var grouped = listOfStuff.Where(x => x.Length > 1).GroupBy(x => x[0]).ToList();
```
 - The method presented **must** be run single-threaded, whereas `GroupBy` is embarrassingly parallelizeable (ignoring ordering issues).
 - The method presented **must** be run over a type that has "deletable" storage.  So, it can't be used with something like `File.ReadLines(...)`, or any of a host of similar transient enumerated collections.
