### ISSUE TITLE
An error pops up when using the method AddResource() of ResXResourceWriter in the .NET Core 3.0 winforms application

### ISSUE THREAD

**Issue by dreddy-work** [dotnet/corefx#36525]
@Zheng-Li01 commented on [Mon Jan 28 2019](https://github.com/dotnet/winforms/issues/387)

**OS:** RS4 X64
**VS:** Visual Studio 2019 Version 16.0.0.0 Preview 4.0 [28526.15.d16.0stg]
**.NET SDK:** .NET Core 3.0.100-preview-10184

**More Info:**
1. In .Net framework application adding the same code, no exception pops up.
2. Replace Bitmap value = new Bitmap(64, 64) with Bitmap value = new Bitmap("C:\Users\Desktop\xxx.png") , no exception pops up.

**Steps to Reproduce:**
1. Create a Winforms .Net Core application by command: dotnet new winforms –o “xxx”.
2. Write code to Form1.cs.
    using System.Resources;
    using System.Drawing;
    Bitmap value = new Bitmap(64, 64);
    String key = "e";
    ResXResourceWriter writer = new ResXResourceWriter("ResxResourceWriter.resx");
    ResXDataNode node = new ResXDataNode(key, value);
    writer.AddResource(node);
3. Debug the application.

**Actual:**
When debugging to writer.AddResource(node), the exception pops up.
![image](https://user-images.githubusercontent.com/38325459/51834305-d62c2680-2334-11e9-8764-6b0f0b4b3800.png)

**Call Stack:**
System.ArgumentNullException
HResult=0x80004003
Message=Value cannot be null.
Source=System.Drawing.Common
StackTrace:
at System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)
at System.Drawing.Image.Save(Stream stream, ImageFormat format)
at System.Drawing.ImageConverter.ConvertTo(ITypeDescriptorContext context, CultureInfo culture, Object value, Type destinationType)
at System.ComponentModel.TypeConverter.ConvertTo(Object value, Type destinationType)
at System.Resources.ResXDataNode.FillDataNodeInfoFromObject(DataNodeInfo nodeInfo, Object value)
at System.Resources.ResXDataNode.GetDataNodeInfo()
at System.Resources.ResXResourceWriter.AddResource(ResXDataNode node)
at AddResourceconsole.Program.Main(String[] args) in C:\Users\v-jiaol\Desktop\WinformDemo\AddResourceconsole\Program.cs:line 31

**Expected:**
No exception pops up, application runs successfully.

---

@dreddy-work commented on [Mon Apr 01 2019](https://github.com/dotnet/winforms/issues/387#issuecomment-478689191)

Moving it to CoreFx repro as there was bug in porting Windows.Image.cs source.

**Comment by dreddy-work** [comment]
adding @ericstj  as FYI.

**Comment by dreddy-work** [comment]
Issue was because of a bug in Image class source on windows that was ported long ago as part fo Syste.Drawing.dll in corefx. I shared details in email to Eric and Santy. @tarekgh

**Comment by ericstj** [comment]
[drawingConverter.zip](https://github.com/dotnet/corefx/files/3031598/drawingConverter.zip)

Attached a repro project.  This does appear to be a bug in the port of ImageConverter.  This is all it takes to repro:
```c#
            Bitmap value = new Bitmap(64, 64);
            ImageConverter converter = new ImageConverter();
            var converted = converter.ConvertTo(value, typeof(byte[]));
```

**Comment by tarekgh** [comment]
CC @safern, @maryamariyan

**Comment by ericstj** [comment]
On desktop this calls Image.Save, which defaults to Png if an encoder is not found.
https://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/Image.cs,658

On .NETCore this calls Save(stream, format) which throws if an encoder is not found;:
https://github.com/dotnet/corefx/blob/d2db42612c462f64f6520106cce17fe973c27bb6/src/System.Drawing.Common/src/System/Drawing/Image.Windows.cs#L285-L303

Oddly, this is inconsistent with Image.Save(string, format) which does fallback to Png:
https://github.com/dotnet/corefx/blob/d2db42612c462f64f6520106cce17fe973c27bb6/src/System.Drawing.Common/src/System/Drawing/Image.Windows.cs#L201-L212

One option would be to make those consistent but it could be semi-breaking for folks who expected that exception (also, falling back to Png seems rather unexpected). 

Another option it to replicate FindEncoder up in the ImageConverter.  Looks like that just builds off of public members;
https://github.com/dotnet/corefx/blob/78cf4e450180c62ebbdb8b306b757103bea0cfc5/src/System.Drawing.Common/src/System/Drawing/Imaging/ImageFormat.cs#L154-L160
