### ISSUE TITLE
Changes regarding the new era to JapaneseCalendar / JapaneseLunisolarCalendar

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/corefx#36526]
A few hours ago, [the name of Japan's new era has been announced as 'Reiwa'](https://www3.nhk.or.jp/nhkworld/nhknewsline/backstories/reiwaera/) (令和, `\u4ee4\u548c`). 

I had a quick glance at the code, and although the information is fetched from the OS (#27800) and therefore barely any changes should be required, there seem to be a couple of hard-coded data in the codes.

List of changes required:
* https://github.com/dotnet/corefx/blob/304c0194b16a1f26c14cda92e2532efcf126c99f/src/Common/src/CoreLib/System/Globalization/JapaneseCalendar.Win32.cs#L203 https://github.com/dotnet/corefx/blob/304c0194b16a1f26c14cda92e2532efcf126c99f/src/Common/src/CoreLib/System/Globalization/JapaneseCalendar.WinRT.cs#L50 (Duplicate data?) Need to add another English Abbreviation. Actually, it seems that neither of the methods and the fields are actually accessed; Could we just delete this?
* https://github.com/dotnet/corefx/blob/304c0194b16a1f26c14cda92e2532efcf126c99f/src/Common/src/CoreLib/System/Globalization/JapaneseCalendar.cs#L77
Need to add the new era to the fallback case, though it seems very unlikely to happen.
(The problem is, quite a lot of callsites are expecting the first item in the array to be the current era, which wouldn't be the case until 1st of May)

**Comment by Clockwork-Muse** [comment]
>(The problem is, quite a lot of callsites are expecting the first item in the array to be the current era, which wouldn't be the case until 1st of May)

...ah, current time, the most insidious of implicit dependencies.

**Comment by MichalStrehovsky** [comment]
Related: #36527

**Comment by Gnbrkm41** [comment]
See https://github.com/dotnet/coreclr/pull/23614#issuecomment-478746095.
