### ISSUE TITLE
[Uri] HttpUtility.UrlDecode will decode twice compare to WebUtility.UrlDecode

### ISSUE THREAD

**Issue by Eilon** [dotnet/corefx#36532]
_From @daohunliwei on Saturday, 30 March 2019 06:35:43_

### Describe the bug
The framework I am using is net core 2.0.
I have a string that has been urlencode twice.When I use 「System.Web.HttpUtility.UrlDecode」 to decode, I only call it once, but all the strings are decoded.
When this method is running on Windows, everything works fine. When running on Linux, the above problem occurs.
Later, I changed 「System.Net.WebUtility.UrlDecode」to decode, and the results on both sides are the same.

### To Reproduce
1. Using this version of ASP.NET Core '2.2.105'
2. Run this code 
```csharp
string url="https%3a%2f%2foapi.dingtalk.com%2fservice%2fget_corp_token%3fsignature%3dFHOywukz2tdfFpx2dPg5medckUMauhAFOuppnDx%252b2NQ%253d"
var right = System.Net.WebUtility.UrlDecode(url);
//resultRight=https://oapi.dingtalk.com/service/get_corp_token?signature=FHOywukz2tdfFpx2dPg5medckUMauhAFOuppnDx%2b2NQ%3d
var wrong = System.Web.HttpUtility.UrlDecode(url);
//resultWrong=https://oapi.dingtalk.com/service/get_corp_token?signature=FHOywukz2tdfFpx2dPg5medckUMauhAFOuppnDx+2NQ=
```

### Expected behavior
I want to call decode only once to decode one layer.

### Screenshots
none.

### Additional context
Include the output of `dotnet --info`

>.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac
Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.104/
Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84
.NET Core SDKs installed:
  2.2.104 [/usr/share/dotnet/sdk]
.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

_Copied from original issue: aspnet/AspNetCore#8938_

**Comment by Eilon** [comment]
_From @Eilon on Monday, 01 April 2019 18:18:02_

@joshfree / @GrabYourPitchforks - any idea where this bug should go? dotnet/corefx?

**Comment by Eilon** [comment]
_From @GrabYourPitchforks on Monday, 01 April 2019 18:34:18_

Normally it should go to corefx, but I cannot repro this in a simple console application. Both APIs produce the "right" string in this scenario.

**Comment by wfurt** [comment]
cc: @rmkerr

**Comment by karelz** [comment]
cc @wtgodbe

**Comment by scalablecory** [comment]
I'm unable to replicate this. @daohunliwei do you have any more info?

The code in question does not have any platform-specific behavior, so I can't explain it working on Windows but not Linux.

**Comment by wtgodbe** [comment]
Based on local testing & test results from https://github.com/dotnet/corefx/pull/37881, it looks like this is no longer reproing. @daohunliwei I'd suggest trying again with the latest 3.0 SDK, which can be found at https://github.com/dotnet/core-sdk. In the meantime I will close this issue - please re-open if you believe I'm mistaken.
