### ISSUE TITLE
 Why the new JSON APIs under the namespace `System.Text.Json.Serialization` and not `System.Json` 

### ISSUE THREAD

**Issue by Waleed-KH** [dotnet/corefx#36530]
Follows https://github.com/dotnet/corefx/issues/34372#issuecomment-465916976
The current JSON APIs naming is so long and not clear, Why it can't be more simple? (Please see the example in the comment link above)

**Comment by scottdorman** [comment]
From my comment on the referenced issue:

> The types in System.Json are, if I remember correctly, a throwback to Silverlight 3. They constitute a legacy API and don't conflict (in naming) to the types in the new JSON API. It seems like the new JSON APIs should be in a System.Json namespace as well since that seems (to me at least) to be the more natural container and is also consistent with the use of the System.Xml namespace to contain all types that are XML related.

**Comment by Waleed-KH** [comment]
https://github.com/dotnet/corefx/issues/34372#issuecomment-481755586
