### ISSUE TITLE
Whither System.Linq.AsyncEnumerable?

### ISSUE THREAD

**Issue by Damien-The-Unbeliever** [dotnet/corefx#36545]
IEnumerable has a companion class - System.Linq.Enumerable - that provides LINQ to Objects implementation.

IAsyncEnumerable doesn't seem to have such a companion. Is this a deliberate decision? I can't find any discussion on this but I may be searching wrong.

In the meantime, I've spent a couple of weekends trying to build my own. It doesn't seem undoable but perhaps there's a reason it's undesirable?

(It is, however, undoubtedly tedious to produce all of the overloads)

**Comment by jkotas** [comment]
Take a look at https://github.com/dotnet/reactive and https://www.nuget.org/packages/System.Linq.Async

**Comment by jkotas** [comment]
@bartdesmet  @onovotny

**Comment by Damien-The-Unbeliever** [comment]
I'm looking for the pull model of enumerable, not the push model of reactive.

**Comment by svick** [comment]
@Damien-The-Unbeliever 

> I'm looking for the pull model of enumerable, not the push model of reactive.

That's exactly what the System.Linq.Async package offers, since it uses `IAsyncEnumerable<T>`.

**Comment by bartdesmet** [comment]
`System.Linq.Async` is indeed what you're looking for. See https://github.com/dotnet/reactive/tree/master/Ix.NET/Source/System.Linq.Async for the source. It's 100% isomorphic to `System.Linq` and has all the operators, including support for cancellation and support for deep asynchrony of predicates, selectors, etc.

**Comment by Damien-The-Unbeliever** [comment]
Yeah, I see it now. Thanks

**Comment by CodingNinjaOctocat** [comment]
> `System.Linq.Async` is indeed what you're looking for. See https://github.com/dotnet/reactive/tree/master/Ix.NET/Source/System.Linq.Async for the source. It's 100% isomorphic to `System.Linq` and has all the operators, including support for cancellation and support for deep asynchrony of predicates, selectors, etc.

If I have a IAsyncEnumerable that contains 20 elements, each element takes 1 seconds to get, and if I just want to get the last element, then it takes 20 seconds for me to use Last()?

This is crazy!

I wish I could use IEnumerable<Task> so that I could quickly enumerate the elements and then manually await it, but the asynchronous data source forced me to use The IAsyncEnumerable.

**Comment by svick** [comment]
@CodingNinjaOctocat That sounds like you want `IEnumerable<Task<T>>`, instead of `IAsyncEnumerable<T>`. What's preventing you from using that?

**Comment by CodingNinjaOctocat** [comment]
> @CodingNinjaOctocat That sounds like you want `IEnumerable<Task<T>>`, instead of `IAsyncEnumerable<T>`. What's preventing you from using that?

You're right, I test it over and over again, IEnumerable<Task<T>> is the best choice.
