### ISSUE TITLE
Instructions for using custom CoreFX with CLI

### ISSUE THREAD

**Issue by saurabh500** [dotnet/corefx#3656]
I have made some changes to the CoreFX for SqlClient and I want to test those changes with an application which is executed using DNX.

How do I achieve this? 
I have found some Windows instructions for creating custom DNX by a custom CoreCLR build at https://github.com/dotnet/coreclr/blob/master/Documentation/building/custom-dnx-instructions.md

I couldn't find anything about CoreFX.
I tried to replace the dlls in the DNX runtime folder with the CoreFX build, but the application fails to run silently without any console output.

**Comment by ellismg** [comment]
/cc @davidfowl

What version of DNX are you using?  I am not sure if we are still dropping assemblies in the runtime folder (unless DNX directly depends on them, which would not be the case here) or if you need to put them in the packages folder.

Does setting DNX_TRACE=1 produce any helpful output (e.g. is the runtime booting?)

**Comment by saurabh500** [comment]
I was using 1.0.0-rc1-15820
Today I got a new version 1.0.0-rc1-15828

In 1.0.0-rc1-15828 I could copy a few files over to the bin folder of the runtime and I could see the changes reflected in the libraries being used. 

I haven't tested DNX_TRACE=1 yet.

**Comment by TheNinjaCat** [comment]
I am using 1.0.0-rc1-15838.

Where do I need to drop the private binaries?

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md is for consuming nightly drops
still need one for consuming private binaries.

**Comment by weshaggard** [comment]
I will update some docs for this.

**Comment by karelz** [comment]
We should update basics dev docs like this soon - moving back to 2.0 to not loose track.
