### ISSUE TITLE
Thread.CurrentPrincipal is null in .net core 3

### ISSUE THREAD

**Issue by stephenjannin** [dotnet/corefx#36562]
When migrating a winforms application from .net 4.5.2 to .net core 3.0, the next line shows a different behavior :
**.net 4.5.2** : `Thread.CurrentPrincipal.Identity.Name` => returns an empty string
**.net core 3.0** : `Thread.CurrentPrincipal.Identity.Name` => throws an exception
```
System.NullReferenceException: 'Object reference not set to an instance of an object.'
System.Threading.Thread.CurrentPrincipal.get returned null.
```

**Comment by karelz** [comment]
@tarekgh @kouvel is it by design change? I vaguely remember there may have been intentional breaking changes around CurrentPrincipal ...

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/issues/30187
https://github.com/dotnet/corefx/issues/34489

those fixed CurrentPrincipal. Not sure about Identity.Name.

**Comment by jkotas** [comment]
.NET Core has different default. The default principal policy in .NET Core is no principal. 

If you would like to keep .NET Framework behavior, call `AppDomain.CurrentDomain.SetPrincipalPolicy(PrincipalPolicy.UnauthenticatedPrincipal)` in the Main method of your app.

**Comment by stephenjannin** [comment]
I confirm the proposed workaround is working. But I'm not clear if I have to add the workaround or if you will fix it in further .net core versions ?

**Comment by jkotas** [comment]
Apply the workaround please. We do not plan to change the default.

Alternatively, if the use of CurrentPrincipal is in the code that you can control, it would be a good idea to make the code robust against returning null e.g. `Thread.CurrentPrincipal?.Identity.Name`.

BTW: .NET Core 3.0 will have initial support for warnings on nullable types: https://devblogs.microsoft.com/dotnet/nullable-reference-types-in-csharp/ . If you opt-in your project into this feature, you will get a warning on for `Thread.CurrentPrincipal.Identity` about CurrentPrincipal being potentially null.
