### ISSUE TITLE
Automate updating HarvestPackages.props

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/corefx#36570]
We should automatically update https://github.com/dotnet/corefx/blob/master/external/harvestPackages/harvestPackages.props when a new OOB package gets built, rather than depending on the dev to run https://github.com/dotnet/corefx/blob/2be1075a381c11330907392951813c7bbab8b1ad/external/harvestPackages/harvestPackages.depproj#L16 manually. We should do this in servicing branches as well.

CC @ericstj

**Comment by ericstj** [comment]
Essentially at the same time the PackageIndex is updated to commit stable versions this should be run as well.

**Comment by ericstj** [comment]
Closing as this is tracked in arcade issues
