### ISSUE TITLE
Using System.Composition.*

### ISSUE THREAD

**Issue by christiannagel** [dotnet/corefx#3657]
I tried to use the System.Composition packages, but didn't find them on a NuGet feed, and trying to open the solutions resulted in this error 
"The <TargetFrameworkIdentifier> for a portable project must be .NETPortable." 
How can I use these libraries? What's the roadmap for System.Composition.*?

Thanks!

**Comment by dsplaisted** [comment]
The current release of the System.Composition libraries is the [Microsoft.Composition](https://www.nuget.org/packages/Microsoft.Composition) NuGet package.

I think that the build infrastructure for the corefx repo doesn't currently work too well with Visual Studio 2015.  This is probably why you were not able to open the solution.  For now, you could open the project with VS 2013 (although if you just want to consume the APIs, the NuGet package is easier).

**Comment by christiannagel** [comment]
Thanks for the information. 
Will the release for System.Composition be the same as Microsoft.Compositon, and I just need to change the namespace later on? 
I'll install VS 2013 on a system and try out to open the project. However, I need to write C# 6 syntax - for a chapter of an upcoming C# 6 book with .NET Core.

**Comment by christiannagel** [comment]
And: I could open other projects of .NET Core with Visual Studio 2015, but not System.Composition

**Comment by dsplaisted** [comment]
@christiannagel The namespaces will stay the same.  Previously the NuGet package name did not match the namespace or assembly name.  Now for corefx packages we are using the assembly name as the NuGet package name.  For System.Composition, there are actually 5 different assemblies, so we may end up with 5 different NuGet packages.  Or we might decide to consolidate them.

In any case the APIs should remain the same and be compatible with what is released today.

If you use the existing NuGet package, it will work fine on Visual Studio 2015, and you can use C# 6.

**Comment by alrz** [comment]
Is this the right place to suggest things like attributed cataloges for MEF? like `[assembly: DirectoryCatalog("...")]`?

**Comment by AtsushiKan** [comment]
I believe the original question has been answered. I don't see anything actionable anymore.
