### ISSUE TITLE
System.Threading.Tasks.Dataflow.Tests hanging in CI

### ISSUE THREAD

**Issue by pgavlin** [dotnet/corefx#3658]
For example:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/3031/console
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/3035/console
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/3036/console

**Comment by stephentoub** [comment]
I'll take a look... nothing's changed here in src or tests in very long time, so this is almost certainly due to some recent change in coreclr.

**Comment by stephentoub** [comment]
@janvorli, I believe https://github.com/dotnet/coreclr/pull/1677 broke this.  When I checkout the commit before yours, the tests all pass, and when I sync to include your commits, the tests hang.  Can you please take a look?  This (along with another deployment issue we're investigating) is blocking our CI runs.

**Comment by janvorli** [comment]
I am looking into that.

**Comment by stephentoub** [comment]
This was fixed by the exception handling fixes in coreclr.
