### ISSUE TITLE
ODBC .NET Bridge issue

### ISSUE THREAD

**Issue by deokershesh** [dotnet/corefx#36598]
I am trying to change ODBC bridge code to rename to different APIs, so that it could work with other databases natively as well. I downloaded/cloned "corefx", built it successfully. Now I want to change API name let say from "OdbcConnection" to "AbcConnection". I made relevant changes in the code, under folders D:\corefx\src\System.Data.Odbc\src\System\Data\Odbc & D:\corefx\src\Common\src\Interop, however I am getting below error! 

C:\Users\newuser\.nuget\packages\microsoft.dotnet.apicompat\1.0.0-beta.19128.2\build\Microsoft.DotNet.ApiCompat.targets(72,5): error : MembersMustExist : Member 'System.Data.Odbc.OdbcCommand..ctor(System.String, System.Data.Odbc.OdbcConnection)' does not exist in the implementation but it does exist in the contract. [D:\corefx\src\System.Data.Odbc\src\System.Data.Odbc.csproj]

Similarly there are 8 more errors.

Could someone help to answer following?
What all other changes needed to change the name of API?

Thanks for your help.

**Comment by Wraith2** [comment]
There will be one or more files in the D:\corefx\src\System.Data.Odbc\ref\ folder which define the public interface, you need to edit them to duplicate the renames that you've done.

**Comment by deokershesh** [comment]
Thanks Wraith2 for quick inputs, this resolved the issue. There is System.Data.Odbc.cs file, modifying the same resolved the issue.

Thanks a lot.
