### ISSUE TITLE
What kind EqualityComparer use to unknown in compile time type?

### ISSUE THREAD

**Issue by westfin** [dotnet/corefx#36592]
Is it possible get `EqualityComparer<>.Default`
by `Type` in runtime?
In compile time I don't know what type will be.

Is it correct to use `EqualityComparer<object>.Default`?
Can there be problems with this?

**Comment by bartonjs** [comment]
@westfin Do you mean you want to get the default equality comparer for a type that you learn about at runtime, but not in a generic way?

```C#
IEqualityComparer comparer = (IEqualityComparer)typeof(EqualityComparer<>).
    MakeGenericType(o.GetType()).
    GetProperty("Default", BindingFlags.Static | BindingFlags.Public);
```

Seems like maybe what you want?

I think `EqualityComparer<object>.Default` is just going to end up calling `((object)x).Equals((object)y)`; which is probably functionally equivalent for any particular T, but I can't speak to that without a lot more digging.

**Comment by westfin** [comment]
> @westfin Do you mean you want to get the default equality comparer for a type that you learn about at runtime, but not in a generic way?

@bartonjs Yes, you are right. Thanks for help
