### ISSUE TITLE
I can't use the RawSecurityDescriptor class

### ISSUE THREAD

**Issue by amei130** [dotnet/corefx#36591]
Describe the bug
I can't use the RawSecurityDescriptor class, but I can find the RawSecurityDescriptor class in the API document

UTL: https://docs.microsoft.com/zh-cn/dotnet/api/system.security.access control.rawsecurity descriptor?View=netcore-2.1

To Reproduce

Using this version of ASP.NET Core '2.1'
Run this code
```c#
using System;
using System.Security.AccessControl;
namespace DiscUtilsNetCore
{
public class Class1
{
RawSecurityDescriptor de;
}
}
```
cannot be compiled
```
erroinf 严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS0246	未能找到类型或命名空间名“RawSecurityDescriptor”(是否缺少 using 指令或程序集引用?) DiscUtilsNetCore	D:\Project\DiscutilsNetcore\DiscUtilsNetCore\Class1.cs	7	活动的
```

**Comment by vcsjones** [comment]
Your compiler error CS0246 is it seems. "The type or namespace name 'type/namespace' could not be found (are you missing a using directive or an assembly reference?)"

I was able to use this code verbatim in a new ASP.NET Core 2.1 project without issue.

```csharp
using System;
using System.Security.AccessControl;

namespace DiscUtilsNetCore
{
    public class Class1
    {
        RawSecurityDescriptor de;
    }
}
```

Please note however that this class is not available in .NET Standard - it is only available in .NET Framework and .NET Core. Are you perhaps trying to use it in a library project that is .NET Standard?

**Comment by bartonjs** [comment]
Closing issue due to lack of response.
