### ISSUE TITLE
.NET Core ODBC Bridge porting

### ISSUE THREAD

**Issue by deokershesh** [dotnet/corefx#36625]
We are in the process of porting .NET Core ODBC Bridge code to database specific code for our native ODBC driver. I added following line in "D:\corefx\src\Common\src\Interop\Windows\Interop.Libraries.cs" to make an entry for our own ODBC driver.

**Comment by deokershesh** [comment]
Please ignore above msg, its not complete, by mistake the msg got delivered!

**Comment by deokershesh** [comment]
We are in the process of porting .NET Core ODBC Bridge code to database specific code for our native ODBC driver. I added following line in "D:\corefx\src\Common\src\Interop\Windows\Interop.Libraries.cs" to make an entry for our own ODBC driver.

internal const string Abc32 = "abcOdbc.dll";

However at compile time, I get following error, abcOdbc.dll is built as per Microsoft ODBC Standard Specification 3.8.

D:\corefx\src\Common\src\Interop\Interop.Odbc.cs(59,9): error BCL0015: abcOdbc.dll!SQLAllocHandle is not supported on one\more targeted platforms. [D:\corefx\src\System.Data.Odbc\src\System.Data.Odbc.csproj]

Any help in this regard is highly appreciated.

Thanks a ton

**Comment by stephentoub** [comment]
It sounds like you're building the code within the corefx build system.  The error you're getting is from an analyzer that runs and flags P/Invokes, in particular on Windows, that aren't known to be available on all versions of Windows corefx targets, and it's saying it has no idea what this "abcOdbc.dll" library is.  If this is just for your own work (we obviously wouldn't take a PR that tried to call into this unknown "abcOdbc.dll" library), you could just suppress that warning.

**Comment by deokershesh** [comment]
Hi Stephen,
Yes, I am building corefx and as part of the same my modified code for System.Data.Odbc gets built. Actually, it reports as an error! How can I suppress this error? Thanks for your help.

**Comment by stephentoub** [comment]
> Actually, it reports as an error! How can I suppress this error? 

It reports an error because warnings-as-errors is enabled. Just suppress the warning.

**Comment by danmosemsft** [comment]
@deokershesh You may be need to edit or create a file named like https://github.com/dotnet/corefx/blob/master/src/System.Data.Odbc/src/PinvokeAnalyzerExceptionList.analyzerdata

**Comment by deokershesh** [comment]
Thanks Dan, Changing odbc32.dll to abcOdbc.dll in file https://github.com/dotnet/corefx/blob/master/src/System.Data.Odbc/src/PinvokeAnalyzerExceptionList.analyzerdata resolved these errors. Thanks a lot.
