### ISSUE TITLE
Digest authentication does not respect RFC7616-3.4

### ISSUE THREAD

**Issue by shutdown256** [dotnet/corefx#36622]
Similarly to #24482 when sending  Authorization header in HTTP Digest authentication, current implementation does not respect [RFC7616-3.4](https://tools.ietf.org/html/rfc7616#section-3.4) where it says that `username*` field should NOT be used over username field unless it contains characters not allowed inside the ABNF quoted-string production. This for example means that even `@` symbol commonly present in username field causes `username*=utf-8''` style encoding with which many servers are not yet compatible.

Code to reproduce:
```c#
public async Task DigestAuthTest()
{
	var uri = new Uri("https://mail.emclient.com/webdav/");
	var request = WebRequest.CreateHttp(uri);
	request.KeepAlive = true;
	request.PreAuthenticate = true;
	request.UserAgent = "Fake UA/1.0.0";
														  
	request.Headers.Add("Accept-Encoding", "gzip, deflate");
	request.AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate;

	var credentialCache = new CredentialCache();
	var cred = new NetworkCredential("fakeusername@emclient.com", "fakepassword123");
	credentialCache.Add(uri, "Digest", cred);

	request.Credentials = credentialCache;
	const string payload = "<?xml version=\"1.0\" encoding=\"utf-8\"?><D:propfind xmlns:D=\"DAV:\"><D:prop><D:current-user-principal /><D:resourcetype /></D:prop></D:propfind>";

	request.Method = "PROPFIND";
	request.ContentType = "text/xml; charset=utf-8";
	request.Accept = "text/xml";
	request.Headers.Add("Brief", "t");
	request.Headers.Add("Depth", "0");
	request.AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip;
	request.ContentLength = payload.Length;

	using (var sw = new StreamWriter(await request.GetRequestStreamAsync()))
	{
		await sw.WriteAsync(payload);
		await sw.FlushAsync();
	}
	var response = (HttpWebResponse) await request.GetResponseAsync();
	Assert.IsTrue(response.StatusCode == HttpStatusCode.MultiStatus);
}
```

this produces following request:

```
PROPFIND https://mail.emclient.com/webdav/ HTTP/1.1
User-Agent: eM Client Test/8.0.0.0
Accept-Encoding: gzip, deflate
Accept: text/xml
Brief: t
Depth: 0
Connection: Keep-Alive
Authorization: Digest username*=utf-8''fakeusername%40emclient.com, realm="mail.emclient.com", nonce="bd19b1f32831baa857ccd0b14b85bd73", uri="/webdav/", response="e7e5d738c4195fe0e350070a6d130256", algorithm=md5, opaque="4bc4f13929d28e0859ee285ad15429c6", qop=auth, nc=00000001, cnonce="659F07D423KRHJ6k"
Content-Type: text/xml; charset=utf-8
Content-Length: 141
Host: mail.emclient.com

<?xml version="1.0" encoding="utf-8"?><D:propfind xmlns:D="DAV:"><D:prop><D:current-user-principal /><D:resourcetype /></D:prop></D:propfind>
```

but expected (abbreviated) result is:
`username="fakeusername@emclient.com",`

We belive the problematic code is here:
https://github.com/dotnet/corefx/blob/dc965e16c4f71163df9de013951c95916992c908/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/AuthenticationHelper.Digest.cs#L95

and similarly to 
https://github.com/dotnet/corefx/blob/dc965e16c4f71163df9de013951c95916992c908/src/System.Net.Http/src/System/Net/Http/Headers/ContentDispositionHeaderValue.cs#L444
it should run a check first to determine whether or not to use the star utf-8 encoding.

**Comment by davidsh** [comment]
@mconnew Can you comment on this given WCF's use of Digest auth?

**Comment by mconnew** [comment]
@davidsh, this shouldn't be a problem for WCF as we don't actually do any Digest authentication directly (other than in some test code) but instead rely on platform code for us. I suspect Windows server supports RFC 5987 fully as we've seen no reports of this problem.
