### ISSUE TITLE
Azure Linux Web App, "it" culture not working

### ISSUE THREAD

**Issue by Eilon** [dotnet/corefx#36631]
_From @valeriob on Friday, 05 April 2019 08:05:46_

### Describe the bug
Create a new aspnetcore 2.2 web app, enable it and en cultures as the documentation instructs, and make a page that prints the current date in short date format "d".
Run it locally with an italian browser, it correctly use the dd/MM/yyyy pattern, then deploy it to azure linux web app (code and framework dependent, not container) navigate to that page with the same browser with italian language : the displayed date has the english M/d/yyyy pattern.
Printing the output of this code in a page confirms that the database of culture information has problems : 

new System.Globalization.CultureInfo("it").DateTimeFormat.ShortDatePattern)
new System.Globalization.CultureInfo("en").DateTimeFormat.ShortDatePattern)

_Copied from original issue: aspnet/AspNetCore#9106_

**Comment by Eilon** [comment]
_From @blowdart on Friday, 05 April 2019 16:38:23_

@Eilon can you move this to CoreFx?

**Comment by joshfree** [comment]
@tarekgh @krwq PTAL

**Comment by tarekgh** [comment]
@Eilon could you please help explain why you think this is corefx issue? I believe this is about setting the current culture correctly in the web app and not really how the culture behave.

**Comment by tarekgh** [comment]
CC @blowdart as it looks he is the one asked to move this issue to corefx.  @blowdart please explain why you think this is corefx issue?

**Comment by tarekgh** [comment]
I have confirmed on Linux (I used Ubuntu) we are producing the dd/MM/yy pattern for Italian culture. 

@valeriob what Linux distro and version you were running on on Azure? and what is the output you are seeing from 

```C#
   new System.Globalization.CultureInfo("it").DateTimeFormat.ShortDatePattern)
   new System.Globalization.CultureInfo("en").DateTimeFormat.ShortDatePattern)
```

**Comment by blowdart** [comment]
Culture and ageing formatting which isn’t us

________________________________

**Comment by tarekgh** [comment]
@valeriob I have confirmed on Ubuntu 14.04 we return expected short date pattern for Italian too. Please send the information I requested in https://github.com/dotnet/corefx/issues/36631#issuecomment-480444935

**Comment by valeriob** [comment]
Hi,
i'm not using any distribution directly, i'm deploying code in an Azure Linux Web App, it builds a container under the hood automatically as i recon. I've chosen netcore 2.2, and i think it's using an old aspnetcore version 2.2.0.

**Comment by tarekgh** [comment]
Thanks @valeriob 

Could you please get the values of 

```
RuntimeInformation.OSDescription and RuntimeInformation.FrameworkDescription
```

**Comment by valeriob** [comment]
Hi @tarekgh,
yes i meant MM/dd/yyy.

Those are the values :
OSDescription : Linux 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 
FrameworkDescription : .NET Core 4.6.27317.07 
CultureInfo_it_EnglishName : Invariant Language (Invariant Country) 
Cultura Request : it-IT
CulturaUI Request : it-IT
Cultura Thread : it-IT
CulturaUI Thread : it-IT
ShortDatePattern it : MM/dd/yyyy
ShortDatePattern en : MM/dd/yyyy

I'm not deploying any container, i'm using Azure Linux Werb App with code deployment and i selected .netcore 2.2 runtime, using the startup file to run "dotnet /site/wwwroot/mywebsite.dll"

Thanks

**Comment by tarekgh** [comment]
Looks this has been deployed on a container with turning on the Invariant Globalization mode https://github.com/dotnet/corefx/blob/master/Documentation/architecture/globalization-invariant-mode.md which basically no complete globalization support on such container. I am not sure if there is option to choose the container when deploying? 

@Eilon any idea how the container is chosen in the  @valeriob scenario? or do you know who can help in that.

**Comment by valeriob** [comment]
Those are the app settings taken from kudu

webpages:Enabled = true
deployment_branch = master
SCM_TRACE_LEVEL = Verbose
SCM_COMMAND_IDLE_TIMEOUT = 60
SCM_LOGSTREAM_TIMEOUT = 1800
SCM_BUILD_ARGS =
REMOTEDEBUGGINGVERSION = 15.0.28010.00
WEBSITE_HTTPLOGGING_RETENTION_DAYS = 7
ASPNETCORE_HOSTINGSTARTUPASSEMBLIES = Microsoft.ApplicationInsights.Profiler.AspNetCore
WEBSITE_SITE_NAME = yyyyyyyy
APPINSIGHTS_INSTRUMENTATIONKEY = xxxxxxx
WEBSITE_AUTH_LOGOUT_PATH = /.auth/logout
ASPNETCORE_ENVIRONMENT = Development
WEBSITE_AUTH_ENABLED = False
SCM_USE_LIBGIT2SHARP_REPOSITORY = 0
WEBSITE_WEBDEPLOY_USE_SCM = false
WEBSITE_AUTH_AUTO_AAD = False
ScmType = None

**Comment by tarekgh** [comment]
I am not seeing any interesting setting 
```
ASPNETCORE_ENVIRONMENT = Development
```
@valeriob could you try other settings than ```Development``` value and figure out if this will make any difference? 

@Eilon any idea if there is any specific settings affect enabling/disabling the (globalization environment mode)[https://github.com/dotnet/corefx/blob/master/Documentation/architecture/globalization-invariant-mode.md]?

**Comment by Eilon** [comment]
> @Eilon any idea how the container is chosen in the @valeriob scenario? or do you know who can help in that.

Sorry no idea.

> @Eilon any idea if there is any specific settings affect enabling/disabling the globalization environment mode?

By default, ASP.NET Core uses whatever culture the host process is using. The developer has to explicitly use loc/glob features of .NET Core or ASP.NET Core to use something else.

**Comment by tarekgh** [comment]
> By default, ASP.NET Core uses whatever culture the host process is using. The developer has to explicitly use loc/glob features of .NET Core or ASP.NET Core to use something else.

my question was regarding the configuration setting when deploying to Azure. anyway, do you have any contact we can ask how the containers get configured when deploying? Thanks.

**Comment by Eilon** [comment]
I'm not aware of any config settings that directly affect loc in ASP.NET Core. It would be an app-specific thing, or a general .NET / .NET Core thing.

There's an internal email 'ancant' that you could try contacting to see if there's an Azure App Service specific thing.

**Comment by tarekgh** [comment]
@valeriob could you please send more details about how you did the deployments? did you choose a container during the deployment? more info here can help.

**Comment by valeriob** [comment]
Hi,
i just created the web app like this : 
![image](https://user-images.githubusercontent.com/1522516/55783676-3d8df180-5aaf-11e9-8e0e-27eb86cb1059.png)
i added the app config WEBSITE_WEBDEPLOY_USE_SCM= false because octopus deploy does not work with it and add startup file = "dotnet /home/site/wwwroot/mywebapp.dll

I do not think the code copy itself is the problem, i've the same result if i ftp into it and copy the output of dotnet publish command into /home/site/wwwroot. I do not know what container it uses to run the code, up to last week it was using an old dotnet 2.2 build, a few days ago has been updated to 2.2.2.

Thanks

**Comment by davidfowl** [comment]
@valeriob we confirmed this is an issue with the base image used on Azure App Service. We're looking into it.

cc @glennc @bradygaster

**Comment by valeriob** [comment]
cheers !

**Comment by tarekgh** [comment]
This issue was moved to Microsoft/Oryx#68
