### ISSUE TITLE
Pushing SystemColors down may have broken KnownColor linkage

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#36642]
SystemColors are supposed to respond to user-preference changed events (EG: someone changes the system to High Contstrast mode).  This happens under ifdef in the KnownColor table.  Previously we only cared about this support for SystemColors which were in Drawing.Common so we ifdef'ed that linkage.

Now that we've pushed the SystemColors down we should remove the ifdef.  To avoid pulling SystemEvents into the shared framework we can call it through reflection.

**Comment by Anipik** [comment]
@safern have you started working on this one ?

**Comment by danmosemsft** [comment]
Should this be assigned to you @Anipik ?
