### ISSUE TITLE
Wrong ColorUtil being used on netcoreapp3.0 (and maybe netcoreapp2.1)

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#36641]
It appears that we're using the wrong source for this.  There's a netcoreapp2.0 and netcoreapp2.1 version and only 2.0 is used.

**Comment by Anipik** [comment]
@safern have you started working on this one ?

**Comment by safern** [comment]
@Anipik assigned to you since you mentioned you were going to work on this, thanks 😄
