### ISSUE TITLE
Span constructor has incorrect documentation

### ISSUE THREAD

**Issue by mikernet** [dotnet/corefx#36650]
`Span<T>(void* pointer, int length)` [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.span-1.-ctor?view=netstandard-2.1#System_Span_1__ctor_System_Void__System_Int32_) indicates that the length is in bytes but that does not appear to be the case in my testing - length refers to the number of `T` elements, not the byte length.

**Comment by stephentoub** [comment]
The docs are wrong. Thanks for reporting. Would you like to submit a PR to fix them?
https://github.com/dotnet/dotnet-api-docs

**Comment by mikernet** [comment]
@stephentoub I just checked the latest code in CoreFX and the xml docs for the method look correct - is it just a matter of time before they sync up with the online docs or do the online docs need to be manually synced up with them?

**Comment by mikernet** [comment]
Er, I mean CoreCLR. You can see the constructor on line 112 has the correct docs:

https://github.com/dotnet/coreclr/blob/652ff3c4b94a96a293788d321a036b236be46aef/src/System.Private.CoreLib/shared/System/Span.Fast.cs#L112

**Comment by stephentoub** [comment]
The process unfortunately is manual right now.

**Comment by mikernet** [comment]
OK I'll open an issue over on the docs repo.
