### ISSUE TITLE
BaseNumberConverter ConvertFrom for decimal/double/float differs from .NET Framework and is buggy anyway

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#36659]
From .NET Framework reference source:
```cs
public override object ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value) {
    if (value is string) {
        string text = ((string)value).Trim();

        try {
            if (AllowHex && text[0] == '#') {
                return FromString(text.Substring(1), 16);
            }
            else if (AllowHex && text.StartsWith("0x") 
                        || text.StartsWith("0X")
                        || text.StartsWith("&h")
                        || text.StartsWith("&H")) {
                return FromString(text.Substring(2), 16);
            }
            else {
            }
            ...
        }
    }
}
```

In .NET Core:

```cs
public override object ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value)
{
    if (value is string text)
    {
        text = text.Trim();

        try
        {
            if (AllowHex && text[0] == '#')
            {
                return FromString(text.Substring(1), 16);
            }
            else if (AllowHex && text.StartsWith("0x", StringComparison.OrdinalIgnoreCase)
                        || text.StartsWith("&h", StringComparison.OrdinalIgnoreCase))
            {
                return FromString(text.Substring(2), 16);
            }
    }
}
```

This causes behavioural differences in the following situations, applicable to `DecimalConverter`, `DoubleConverter` and `SingleConverter`, because all these set `AllowHex` to false.

- `converter.ConvertFrom("#2")`: throws in .NET Framework; throws in .NET Core
- `converter.ConvertFrom("0x2")`: throws in .NET Framework; throws in .NET Core
- `converter.ConvertFrom("0X2")`: *does not* throw in .NET Framework; throws in .NET Core
- `converter.ConvertFrom("&h2")`: *does not* throw in .NET Framework; *does not* throw in .NET Core
- `converter.ConvertFrom("&H2")`: *does not* throw in .NET Framework; *does not* throw in .NET Core

There are several bugs, both in .NET Core and in .NET Framework due to incorrect order of precedence between the && and the || operators.

The intention of the code is to disallow (throw) the following:
- `converter.ConvertFrom("#2")`
- `converter.ConvertFrom("0x2")`
- `converter.ConvertFrom("0X2")`
- `converter.ConvertFrom("&h2")`
- `converter.ConvertFrom("&H2")`

This is because all these representations above are hex, but `AllowHex` only applies to the first condition in the following list of `... || ...` due to the order of precedence. Changed bracketing would fix this

**Comment by danmosemsft** [comment]
@tannergooding
