### ISSUE TITLE
System.Text.Json.JsonElement documentation copy-paste issue

### ISSUE THREAD

**Issue by Zenexer** [dotnet/corefx#36686]
https://github.com/dotnet/corefx/blob/268812e10fe17e8177dc5ca680128b286207c82f/src/System.Text.Json/src/System/Text/Json/Document/JsonElement.cs#L341

This should say `string`, not `bool`.

**Comment by Zenexer** [comment]
While we're at it:

https://github.com/dotnet/corefx/blob/268812e10fe17e8177dc5ca680128b286207c82f/src/System.Text.Json/src/System/Text/Json/Document/JsonElement.cs#L343

This is incorrect because of:

https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/src/System/Text/Json/Document/JsonDocument.cs#L240

Therefore, it throws an exception if it's not `String` or `Null`.

**Comment by ahsonkhan** [comment]
Thanks for the issue! Good catch :)

Would you be willing to submit a PR for the documentation fix that you have suggested, to match the source?

cc @bartonjs
