### ISSUE TITLE
FileStream allocates gigabytes of memory

### ISSUE THREAD

**Issue by AndreasTruetschel** [dotnet/corefx#36680]
When allocating many (~400) FileStreams for paths that are all in the same directory, a `System.IO.FileNotFound` exception is issued in the VS diagnostic tools window, if the `useAsync` parameter is set to true in the FileStream constructor. 
 
The file-streams are used as copy target for data that is stored in main memory ONE AFTER ANOTHER. The process memory grows rapidly above some dozens of gigabytes until windows shuts down the process.  

The thrown exception is due to a non-loadable assembly and only  occurs in this scenario. If setting `useAsync` to `false`, everything works fine.

The exception stack trace:
![grafik](https://user-images.githubusercontent.com/12112026/55689108-1df8ab00-5981-11e9-9a38-38d10c004339.png)

The application is a `.Net Core 3.0 preview 3` application. The code that used the file-streams is located in a `.net standard 2.0` library.

I was not able to repro this in a smaller sample project yet.

**Comment by danmosemsft** [comment]
What assembly is it trying to load?

**Comment by JeremyKuhne** [comment]
`FileStream` allocates a 4K buffer by default. That's not gigabytes for sure. If we can get more info on this we can look into possible mitigations if, in fact, FileStream is eating all of the space.

**Comment by AndreasTruetschel** [comment]
@danmosemsft I don't know the assembly it tries to load. As this is a closed source project at work, I am not able to provide you the repro/source code. I tried to build a small repro mut was not able to repo the bug this way.   

@JeremyKuhne It is exactly the case that the memory allocated by the process that this occurs in allocates gigabytes of memory after the operation on the file-stream. The size of allocated memory grows rapidly and in 10-15 secs the whole available memory of the computer was allocated (~32GB).  

Is there any way I can help you with this without the source code of the project?

**Comment by davidfowl** [comment]
@AndreasTruetschel a memory dump might help. Sending it directly to somebody at MSFT (before it reaches 32GB though...)

**Comment by stephentoub** [comment]
You can send me one at stoub at microsoft. I can share it with Jeremy/Dan/David as well.

**Comment by AndreasTruetschel** [comment]
I have tried several times on the same build machine with the same config but were not able to repro this any more. I am sry guys, I cannot create a memory dump :(

**Comment by JeremyKuhne** [comment]
No problems, if you get data that can pinpoint something we're doing wrong here please reopen. :)
