### ISSUE TITLE
Suspicious definition of `LsaOpenPolicy` in Interop code

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#36724]
We have the following (formatted) definition in `Interop.LsaOpenPolicy`:

```cs
[DllImport(Interop.Libraries.Advapi32, EntryPoint = "LsaOpenPolicy", SetLastError = true, CharSet = CharSet.Unicode)]
internal static extern uint LsaOpenPolicy(
    string systemName,
    ref LSA_OBJECT_ATTRIBUTES attributes,
    int accessMask,
    out SafeLsaPolicyHandle handle
);
```

Notice that this takes a `string` as the first parameter.

In the documentation for `LsaOpenPolicy` found at https://docs.microsoft.com/en-us/windows/desktop/api/ntsecapi/nf-ntsecapi-lsaopenpolicy the definition is different:
```c
NTSTATUS LsaOpenPolicy(
  PLSA_UNICODE_STRING    SystemName,
  PLSA_OBJECT_ATTRIBUTES ObjectAttributes,
  ACCESS_MASK            DesiredAccess,
  PLSA_HANDLE            PolicyHandle
);
```

Note that the first parameter is a pointer to `LSA_UNICODE_STRING` defined in the documentation (https://docs.microsoft.com/en-gb/windows/desktop/api/lsalookup/ns-lsalookup-_lsa_unicode_string) as:
```c
typedef struct _LSA_UNICODE_STRING {
  USHORT Length;
  USHORT MaximumLength;
  PWSTR  Buffer;
} LSA_UNICODE_STRING, *PLSA_UNICODE_STRING;
```

Surely marshalling a `string` would not be the same as marshalling an `LSA_UNICODE_STRING`?

**Comment by danmosemsft** [comment]
@jeremykuhne?

**Comment by JeremyKuhne** [comment]
Yes, it is wrong. that is your standard `UNICODE_STRING`.
