### ISSUE TITLE
WebSocket concurrent Send/ReceiveAsync semantics unclear

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#3674]
As observed by @mkosieradzki different WebSocket implementations have different behaviour when it comes to concurrent Send/ReceiveAsync operations: see https://github.com/aspnet/WebSockets/issues/42

I am creating a matching issue here since the semantics should be specified at the WebSocket level, so a user of a 'WebSocket' doesn't need to know what library provided the implementation.

\cc @davidfowl @Tratcher

**Comment by davidsh** [comment]
cc: @CIPop @SidharthNabar @pgavlin @mconnew

**Comment by CIPop** [comment]
At this point, most of the tests that we have for System.Net.WebSockets.Client validated the same behavior on both Desktop and CoreFX. (Unforuntately the majority of the tests have not yet been ported to GitHub: we're still figuring out how to set up servers, etc.)

It is expected to have different behaviors if you are using _different_ APIs (System.Web.WebSockets vs System.Net.WebSockets). The two different APIs should maintain their behavior across existing platforms: ASP.Net 5 ws should behave the same as older versions of ASP.Net.

While we try our best to keep behavior for the same APIs on different platforms (in our case System.Net.WebSockets.ClientWebSocket) we are sometimes limited by the underlying implementation (managed HttpWebRequest in Desktop vs native WinHttp in CoreFX).

Please add more detail regarding the System.Net.WebSockets.Client differences in behavior. The referenced item is talking about implementations not related to CoreFX. We'll have to address each problem on a case-by-case for app-compat reasons.

**Comment by tmds** [comment]
CoreFX and aspnet/WebSockets both implement System.Net.WebSockets.WebSocket. CoreFX has a Client implementation and aspnet/WebSockets has both a Client and a Server implementation.

As a user of a WebSocket instance I would like to know what multi-threading behavior I can expect.

The documentation of ClientWebSocket says: don't expect anything.
The implementation of ClientWebSocket says: I support concurrent sends, concurrent with a read.
The tests of ClientWebsocket probably check the concurrency(?).
The implementation in aspnet/WebSockets is in the making, currently no concurrency is supported.

It would be beneficial if the WebSocket definition can be extended to include thread safety for the Send and Receive operations.
Otherwise when writing some code (especially a library) you should expect nothing and need to implement this yourself, which is adding overhead to implementations which are already thread-safe and will be less mature than a common implementation.

**Comment by CIPop** [comment]
@tmds Thanks for the detailed reply. 
To clarify the expectation for he current CoreFX Windows (WinHTTP) implementation: it supports exactly one send and one receive on each WebSocket object in parallel.

/cc: @SidharthNabar

**Comment by tmds** [comment]
Thanks to the ManagedWebSocket aspnet/WebSockets now has the same behavior: "supports exactly one send and one receive on each WebSocket object in parallel".

**Comment by CIPop** [comment]
cc: @mariaw , @karelz

**Comment by karelz** [comment]
@mairaw action item for docs team:
On WebSocket.SendAsync and ReceiveAsync methods, please include remark: "Supports exactly one send and one receive on each WebSocket object in parallel."

**Comment by mairaw** [comment]
Do we also need to add these remarks to ClientWebSocket since they override the WebSocket implementation?

**Comment by karelz** [comment]
@CIPop @davidsh?

**Comment by mairaw** [comment]
I've added the remarks to WebSocket.SendAsync and WebSockets.ReceiveAsync on MSDN:
https://msdn.microsoft.com/en-US/library/hh159367(VS.110).aspx
https://msdn.microsoft.com/en-US/library/hh159308(VS.110).aspx

I've changed the remarks just a bit since they'd be in the context of one of the methods. Let me know if that looks good and I'll wait on the answer for the ClientWebSocket.
These remarks will be ported to docs.microsoft.com at a later time.

/cc @DelfCo @CIPop @davidsh

**Comment by CIPop** [comment]
> Do we also need to add these remarks to ClientWebSocket since they override the WebSocket implementation?

Yes, please add them for ClientWebSocket as well.

**Comment by mairaw** [comment]
Ok, thanks for confirming that @CIPop. It's done:
http://msdn.microsoft.com/en-US/library/hh875123(VS.110).aspx
http://msdn.microsoft.com/en-US/library/hh874933(VS.110).aspx

**Comment by CIPop** [comment]
Thank you @mairaw !

**Comment by karelz** [comment]
And thanks for fast turn-around @mairaw! Again! :)

Once we pay off all the debt of delayed triage of CoreFX repo issues, I hope we will be able to pass these issues to docs team earlier and have faster time-to-resolution as a result. Almost there!

**Comment by tmds** [comment]
Thx @mairaw !

**Comment by mlowry99** [comment]
I just stumbled on this conversation. I'm developing my first C# WinForms application using websockets. I have a requirement to have a form that has transaction request-response behavior and a separate panel with a blog-style newsfeed with multiple outputs.  The comment "Exactly one send and one receive is supported on each WebSocket object in parallel." has me confused.  Is there a recommended way to set up the above requirement?
