### ISSUE TITLE
NET Standard Test Suite

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#36743]
With https://github.com/dotnet/corefx/commit/0c5594864387aef6d9f6c8842f8a9e476ef39cc3 we added the ability to build a netstandard test suite. It's unclear to me if we still need it as we now take a different road with Mono. 

We build and protect it currently as part of the AllConfigurations leg. If we don't need it anymore we should remove it.

Benefits:
- Reduce AllConfigurations leg time
- Remove unncessary infra logic

cc @safern @ericstj @danmosemsft

**Comment by Paiza28** [comment]
248-246125-6
พัฒนัย สกุลรักษ์

**Comment by safern** [comment]
cc: @joperezr who added it.

**Comment by ericstj** [comment]
Lets ask the mono / Xamarin folks if they plan to use it.  If not, then I think we can turn it off.

**Comment by ericstj** [comment]
@marek-safar do you plan to use this for Mono / Xamarin TFMs?  If not, then I think we can turn it off.

**Comment by marek-safar** [comment]
I think we don't need it as we are working in a different approach

**Comment by ericstj** [comment]
Thanks @marek-safar
