### ISSUE TITLE
System.Buffers: .NET Standard Shims appear in the build output for .Net framework 4.6.1 project

### ISSUE THREAD

**Issue by rymeskar** [dotnet/corefx#36754]
**Invariants:**
* [System.Buffers](https://www.nuget.org/packages/System.Buffers/) nuget is multi-targeting and has specific no-dependency target for .Net framework 4.5.
* Project in question targets .Net framework 4.6.1
* Nuget should prefer any suitable target from .Net framework family (thus the 4.5 target)

**Repro:**
1. Create new 4.6.1 class library project
2. Install System.Buffers package
3. Build

Observe amount of shims in the output.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/8701120/55842142-820ea100-5b32-11e9-90ee-79b1af5bad20.png)

For convenience, I have uploaded the min repro steps [on github](https://github.com/rymeskar/fuzzy-octo-fiesta/tree/master/OldCsProj461).

**Questions**
* Is this expected? I have not seen such behavior with similar System.* family nuget packages.
* Is this because of System.Buffers packaging?
* Does it have to do with the MSBuild?

**Comment by ericstj** [comment]
This is expected.  System.Buffers is a .NETStandard2.0 library.  .NETStandard2.0 is supported on .NET 4.6.1 but is not inbox.  As such, the build infrastructure in MSBuild/,NET SDK adds all the shims to the application.

**Comment by rymeskar** [comment]
Hi @ericstj  

[System.Buffers](https://www.nuget.org/packages/System.Buffers/) does supply the .NET framework 4.5 target according to nuspec.

![image](https://user-images.githubusercontent.com/8701120/55898932-ef1e4700-5bc3-11e9-91a6-6dec58031ab8.png)

Or you mean different support?

**Comment by ericstj** [comment]
That's not the assembly, that's the dependency group.  The current behavior is intentional and expected.  This library doesn't explicitly target .NETFramework and is providing a netstandard2.0 assembly when installed in a net461 project.

**Comment by rymeskar** [comment]
@ericstj 
Thank you for clarifying answer.

Then how is one able to tell how will the System.* package behave for '.NET framework dependency group'?

Whether it will bring in .NET shims or it is really an .NET framework assembly?

For example [System.Numerics.Vectors](https://www.nuget.org/packages/System.Numerics.Vectors/4.5.0),   [System.ValueTuple](System.ValueTuple) and [System.Net.Http](https://www.nuget.org/packages/System.Net.Http/) do not copy any shims to the output folder?

Background: The behavior described in this thread leads to encountering the known issues of consuming .NET Standard 2.0 packages on NET Framework 4.6.1 -4.7.1.

**Comment by ericstj** [comment]
You can examine the Assembly's references to see if it is a NETStandard2.0 assembly.  If an assembly references `netstandard` it will require the System.*.dll and netstandard.dll files on [net461,net471].

I don't think that's ultimately your request.  Perhaps you can phrase your request as "We'd like it if library X specifically targeted .NETFramework so that we can depend on it without requiring our consumers to bring in all of the .NETStandard support dlls".   If you phrase an issue as such and open the request as servicing then the owning teams can take a look and see if they can make the change.

**Comment by rymeskar** [comment]
Thank you for a complete explanation.

This does make sense.

We will therefore file an ask along those lines.
