### ISSUE TITLE
Add DebuggerDisplay/DebuggerTypeProxy to JSON reader / writer / dom

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#36768]
Tracking issue for creating the debugger visualizer of JSON reader/writer/document

As an example of how to get started, see https://github.com/dotnet/corefx/blob/95fa11b014ff7eeffdb325a7a0b3aa3afacc2f4a/src/Common/src/CoreLib/System/Span.cs#L19-L20

**Comment by ahsonkhan** [comment]
Related: https://github.com/dotnet/corefx/issues/34663

**Comment by layomia** [comment]
Duplicate of https://github.com/dotnet/corefx/issues/34663.
