### ISSUE TITLE
API Proposal: IAsyncEnumerable intergrate with LINQ

### ISSUE THREAD

**Issue by hez2010** [dotnet/corefx#36778]
For example:
```csharp
IAsyncEnumerable<T> xxxx;

var result = await xxxx.Where(i=> .....).OrderBy(i=> ...).AsAsync();
var result = await from async c in xxxx where .... order by ..... asc;
```

**Comment by benaadams** [comment]
I think Reactive Extensions provides for this in v4 https://github.com/dotnet/reactive

/cc @onovotny

**Comment by GalaxiaGuy** [comment]
I think this was recently discussed: https://github.com/dotnet/corefx/issues/36545

The conclusion was:
https://github.com/dotnet/reactive/tree/master/Ix.NET/Source/System.Linq.Async

**Comment by stephentoub** [comment]
Closing as dup of https://github.com/dotnet/corefx/issues/36545.
