### ISSUE TITLE
Linux outerloop tests failed to start

### ISSUE THREAD

**Issue by vcsjones** [dotnet/corefx#36771]
While attempting to run linux outerloop in PR #36770 the tests did not run with the following output:

> A container resource with name alpine_36_container could not be found. The container resource does not exist. If you intended to specify an image, use NAME:TAG or NAME@DIGEST. For example, ubuntu:latest
One or more errors occurred.

**Comment by safern** [comment]
@vcsjones sorry about that. Taking a look now.
