### ISSUE TITLE
xml doc comment for PipeReader.OnWriterCompleted is wrong

### ISSUE THREAD

**Issue by AArnott** [dotnet/corefx#36798]
As shown below, the summary tag in the xml doc comment for `PipeReader.OnWriterCompleted` is wrong. It looks like it was written with `PipeWriter.Complete` in mind, honestly. `OnWriterCompleted` doesn't cancel anything -- it just adds a callback for when the writer marks its own completion.

https://github.com/dotnet/corefx/blob/af562e84b8b5a4a335ceb5006886a6c42c1c023e/src/System.IO.Pipelines/src/System/IO/Pipelines/PipeReader.cs#L73-L76

**Comment by davidfowl** [comment]
Oops
