### ISSUE TITLE
Ref and src folders have mismatched param names

### ISSUE THREAD

**Issue by mairaw** [dotnet/corefx#36804]
@carlossanlop and I are looking into adding more API docs and we ran into an issue where the source has a parameter name that is different than what we're seeing in the reference assemblies.

I'm guessing it's because of the mismatch we're seeing between the src and ref folders?
https://github.com/dotnet/corefx/blob/master/src/System.IO.Compression.ZipFile/ref/System.IO.Compression.ZipFile.cs#L16
https://github.com/dotnet/corefx/blob/master/src/System.IO.Compression.ZipFile/src/System/IO/Compression/ZipFile.Extract.cs#L78

**ref** calls it _overwriteFiles_, **src** calls it _overwrite_.

/cc @terrajobst @karelz

**Comment by ahsonkhan** [comment]
See PR where an attempt was made to normalize the source/ref. In particular:, what you have observed is called out here: https://github.com/dotnet/corefx/pull/35474/files#r258747663

From @bartonjs:
> This one is tricky.  https://github.com/dotnet/standard/search?q=ExtractToDirectory&unscoped_q=ExtractToDirectory says that most of the platforms called it `overwrite` but the netstandard-ref calls it `overwriteFiles` (like the ref here).

> So I think `overwriteFiles` is correct, but clearly there's a problem somewhere.  (cc @terrajobst)

Relevant commits:
https://github.com/dotnet/corefx/pull/35474/commits/1534ca918cb69fda62039663b2c5282785c3b03f
https://github.com/dotnet/corefx/pull/35474/commits/0735619aab5d754b74eb0dc00955c7db0bda1e03

We need to re-visit that PR/set of changes.

**Comment by carlossanlop** [comment]
We looked into this, and @ericstj helped confirm the right change for this particular case is to make the source match the ref.
