### ISSUE TITLE
Test failure: NRE on System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandlerTest.GetAsync_IPv6LinkLocalAddressUri_Success

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/corefx#36802]
System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http2/GetAsync_IPv6LinkLocalAddressUri_Success
System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandlerTest/GetAsync_IPv6LinkLocalAddressUri_Success
System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandlerTest/GetAsync_IPv6LinkLocalAddressUri_Success
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F36497~2Fmerge/test~2Ffunctional~2Fcli~2F/20190411.32/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandlerTest~2FGetAsync_IPv6LinkLocalAddressUri_Success
Windows.10.Amd64.ClientRS4.ES.Open-x64-Debug
```text
Unhandled Exception of Type System.NullReferenceException
Message :
System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace :
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in D:\a\1\s\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 59
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_IPv6LinkLocalAddressUri_Success() in D:\a\1\s\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.cs:line 301
--- End of stack trace from previous location where exception was thrown ---
```

_Originally posted by @ahsonkhan in https://github.com/dotnet/corefx/pull/36497#issuecomment-482350459_

**Comment by danmosemsft** [comment]
@wfurt

**Comment by davidsh** [comment]
```
Unhandled Exception of Type System.NullReferenceException
Message :
System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace :
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in D:\a\1\s\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 59
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_IPv6LinkLocalAddressUri_Success() in D:\a\1\s\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.cs:line 301
--- End of stack trace from previous location where exception was thrown ---
```

The test appeared to get NRE due to the options.Address property being NULL. 

https://github.com/dotnet/corefx/blob/4fa6319fb590b046ba4c962088b960a31749f245/src/Common/tests/System/Net/Http/LoopbackServer.cs#L59

This is the only possible field access that could result in an NRE.  However, the constructor of the Options class initializes the .Address property to IPAddress.Loopback.  So, the only way this could be null is if Loopback is broken on this test machine.

**Comment by wfurt** [comment]
Perhaps we can add XUnit Fixture to rune once and dup all used addresses to Output. Or assert when LoopbackServer server is created to get more information.
