### ISSUE TITLE
string.Join unexpected behavior when calling Join(String separator, params object[] values);

### ISSUE THREAD

**Issue by hinteadan** [dotnet/corefx#36820]
When calling the `String Join(String separator, params object[] values)` signature and pass a **null** value as the first parameter, followed by a type other than string, then any number and type of other parameters, the method **returns an empty string**.

Code samples:
`string.Join(",", null, 0) //returns ""`
`string.Join(",", null, 0, null, null, "", null, 0, "", null, new Exception(), DateTime.Now) //returns ""`

**Comment by hinteadan** [comment]
Wrong repo, applies to .NET Standard. I haven't tried in .NET Core.

**Comment by hinteadan** [comment]
Apparently it's expected behavior, noted as a remark on the MSDN Documentation:

https://docs.microsoft.com/en-us/dotnet/api/system.string.join?view=netframework-4.7.2#System_String_Join_System_String_System_Object___

**Comment by stephentoub** [comment]
This was already fixed for .NET Core.
