### ISSUE TITLE
.net core should return 24hours datetime by format string "H",instead of format string "h"

### ISSUE THREAD

**Issue by chuanjiao10** [dotnet/corefx#36836]
.net framework on win return 24 hours datetime by format string "H",
But .net core 2.2 on win,linux return 12 hours datetime by format string "h",
This will affect the time that powershell displays in getchilditem on win, linux.

am,pm,上午,下午.
In the Chinese get-childitem return, the columns cannot be aligned.

I have reported issues to powershell on github, https://github.com/PowerShell/PowerShell/issues/8099
But this seems to be a problem with the .net core.

note:
ls retrun 24 hours datetime on linux. 

Steps to reproduce
------------------

```c#
using System;
using System.Globalization;

namespace DotnetCoreTest
{
    class Program
    {
        static void Main(string[] args)
        {
            DateTime now = DateTime.Now;
			CultureInfo enus = new CultureInfo("en-us");
			CultureInfo zhhans = new CultureInfo("zh-hans");
			Console.WriteLine(enus.DateTimeFormat.ShortTimePattern);
			Console.WriteLine(enus.DateTimeFormat.LongDatePattern);
			Console.WriteLine(now.ToString(enus.DateTimeFormat));

			Console.WriteLine("--------");

			Console.WriteLine(zhhans.DateTimeFormat.ShortTimePattern);
			Console.WriteLine(zhhans.DateTimeFormat.LongDatePattern);
			Console.WriteLine(now.ToString(zhhans.DateTimeFormat));
        }
    }
}

```

return:
![9318](https://user-images.githubusercontent.com/8968667/56074032-3c760080-5dde-11e9-8398-f3213f001710.png)

powershell：
```powershell

$日期对象 = Get-Date
$日期格式 = New-Object System.Globalization.CultureInfo "en-us"
$日期格式.DateTimeFormat.ShortTimePattern
$日期格式.DateTimeFormat.LongDatePattern
$日期对象.ToString($日期格式)

write-host '-------------'
$中文日期格式 = New-Object System.Globalization.CultureInfo "zh-cn"
$中文日期格式.DateTimeFormat.ShortTimePattern
$中文日期格式.DateTimeFormat.LongDatePattern
$日期对象.ToString($中文日期格式)


```
powershell on linux return:

```
h:mm tt
dddd, MMMM d, yyyy
4/13/2019 10:36:58 AM
-------------
tth:mm
yyyy年M月d日dddd
19-4-13 上午10:46:27
```

Environment data
----------------
.net core 2.2
powershell 6.2.0 on centos 7.6

reporter
----------------
By the chinese powershell study & research group. QQ group No. is 183173532

**Comment by danmosemsft** [comment]
@tarekgh

**Comment by tarekgh** [comment]
.Net Core picks the data from the underlying OS. On Windows, we get it through Windows Win32 APIs and on Linux we get the data through the ICU library. Both ICU and Windows trying to converge to use the CLDR standard locale data. If you think there is wrong data there (e.g. the date pattern should us 24-hours designators) then report the issue to Windows or CLDR. If you want to report any issue to Windows, please use the Feedback Hub on Windows 10. If you want to report the issue to CLDR, please use the link http://cldr.unicode.org/index/bug-reports.

**Comment by chuanjiao10** [comment]
> .Net Core picks the data from the underlying OS. On Windows, we get it through Windows Win32 APIs 
@tarekgh  How do you explain that .net core and .net frame work return inconsistencies on win?
Is the .net framework wrong? Does it use Windows Win32 APIs?

**Comment by tarekgh** [comment]
> How do you explain that .net core and .net framework return inconsistencies on win?

I don't think this is true if you are running on the exact same version of Windows. You can have inconsistency if you are running on different versions of Windows and Windows decided to update the globalization data on one of these versions. I have ran your code on my Windows 10 (version 1803) and I am seeing both full framework and net core 2.2 returning the exact same result. 

```
h:mm tt
dddd, MMMM d, yyyy
4/15/2019 9:02:29 AM
--------
H:mm
yyyy'年'M'月'd'日'
2019/4/15 9:02:29
```

> Is the .net framework wrong?

No

> Does it use Windows Win32 APIs?
Yes

**Comment by chuanjiao10** [comment]
I re-examined and found that the output of the .net framework and the .net core on win is the same.

The .net core has different output between win and linux. And does not affect English, only affects Chinese.

You are right, sorry.

=============
win+.net framework + us language setting= 12hours
win+.net core + us Language setting= 12hours
#There may be other non-English languages set to 24 hours.
win+.net framework + chinese language setting= 24hours
win+.net core + chinese Language setting= 24hours


linux+.net core + us language setting= 12hours
linux+.net core + chinese language setting= 12hours

**Comment by anhuisunfei** [comment]
@chuanjiao10  How did you fix this problem?

**Comment by chuanjiao10** [comment]
Did not solve

**Comment by tarekgh** [comment]
It is not a problem. it is by design we use the underlying OS for the globalization data. please look at previous comment https://github.com/dotnet/corefx/issues/36836#issuecomment-483020242 

You still can override the setting of any culture by overwriting the properties of CultureInfo.DateTimeFormat object.

**Comment by chuanjiao10** [comment]
> on Linux we get the data through the ICU library

it is by     **wrong**    design ,or  **wrong** depend.
Such as believe that "the earth is the center of the universe"
Chinese setting in ICU library **wrong**，We should not depend  **wrong**

**Does not affect English, only affects Chinese.** 

in linux ls command，return 24h time for zh-cn.utf8 user. linux not  depend **wrong** ICU library,why .net do it?

Suggest：
at  .net core， System.Globalization.CultureInfo "zh-cn",Forced to “H”. not  depend **wrong** ICU library

**Comment by tarekgh** [comment]
@chuanjiao10 

I am not sure why you think depending on ICU is wrong. This is a library that use the globalization data picked up from the standards (CLDR)[http://cldr.unicode.org/] which should be the closest accurate data. If you disagree with such data, you can just make your case to the CLDR or ICU and they can just fix it. 

.NET trying to avoid to to deviate from the standards and forcing unify the globalization across platforms. Windows 10 started to support ICU too and eventually ICU will be used everywhere.

**Comment by anhuisunfei** [comment]
```csharp
 var dtf = new DateTimeFormatInfo
            {
                ShortDatePattern = "yyyy-MM-dd",
                LongDatePattern = "yyyy'年'M'月'd'日",
                ShortTimePattern = "HH:mm",
                LongTimePattern = "HH:mm:ss.fff",
                FullDateTimePattern = "yyyy-MM-dd HH:mm:ss"
            };

            var supportedCultures = new List<CultureInfo>
            {

                new CultureInfo("zh-CN") { DateTimeFormat = dtf }

            };

            app.UseRequestLocalization(new RequestLocalizationOptions
            {
                DefaultRequestCulture = new RequestCulture("zh-CN"),
                // Formatting numbers, dates, etc.
                SupportedCultures = supportedCultures,
                // UI strings that we have localized.
                SupportedUICultures = supportedCultures
            });
```
@tarekgh @chuanjiao10 
now we are fixed with this problem.

**Comment by chuanjiao10** [comment]
Aristotle is not willing to admit the wrong "the earth is the center of the universe", and perhaps wants to burn me.
