### ISSUE TITLE
Consider eliminating global.json merge conflicts

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/corefx#36846]
@stephentoub 

There are two maestro-bot updates which often collide between these line in global.json

https://github.com/dotnet/corefx/blob/609fae21a5f931ce31a71c37e30f4ce6b196b62c/global.json#L7-L8

I was wondering if something simple like adding one or more blank lines between them might eliminate the merge conflicts.

**Comment by sdmaclea** [comment]
Of course if maestro-bot is using a json pretty printer it won't work w/o more work

**Comment by karelz** [comment]
@sdmaclea please only 1 issue type - see [triage rules](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#triage-rules---simplified)
