### ISSUE TITLE
The type "Span<T>" exists in both "System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" and "netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51".

### ISSUE THREAD

**Issue by Apollo3zehn** [dotnet/corefx#36841]
When I create a new classlib via `dotnet new classlib`, and (1) change the target framework to:

```
<PropertyGroup>
  <TargetFramework>netstandard2.1</TargetFramework>
</PropertyGroup>
```

and (2) add a reference to System Memory:

```
<ItemGroup>
  <PackageReference Include="Microsoft.Extensions.Logging" Version="3.0.0-preview3.19153.1" />
</ItemGroup>
```

Then the following simple code does not compile with error `The type "Span<T>" exists in both "System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" and "netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51".`

```
public class Class1
{
    Span<byte> Test() {
       ...
    }
}
```

The only solution I found so far is to add:

```
<PackageReference Include="System.Memory" Version="4.5.2">
  <ExcludeAssets>all</ExcludeAssets>
</PackageReference>
```

**Comment by davidfowl** [comment]
Related to #36719 ?

cc @ericstj

**Comment by ericstj** [comment]
yep, same issue.  Let's use #36719 to track it.
