### ISSUE TITLE
Activity doc comments are missing

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#36858]
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activity?view=netcore-2.2

cc @lmolkova

**Comment by ahsonkhan** [comment]
FYI @carlossanlop 

https://github.com/dotnet/corefx/blob/7336f57f745e7399803902efca8fd085ff6ca326/src/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L14-L31

**Comment by carlossanlop** [comment]
Thanks for mentioning me, @ahsonkhan. I have a PR in dotnet-api-docs that is automatically porting some of these missing comments in System.Diagnostics: https://github.com/dotnet/dotnet-api-docs/pull/2336

Anything else missing, @wtgodbe is the area owner, he can add it.
