### ISSUE TITLE
Stop publishing to myget

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#36860]
Now that we stopped restoring from myget we should also stop publishing to myget. Any concerns?

cc @eristj @safern @wtgodbe

**Comment by safern** [comment]
Right now we're no longer publishing to myget, that step is disabled because of the out-of-storage issue. We haven't been publishing for weeks now because of this issue.

https://github.com/dotnet/corefx/blob/master/eng/pipelines/publish.yml#L99

**Comment by ViktorHofer** [comment]
Okay then now's the perfect time to remove it completely 👍
