### ISSUE TITLE
Update IlLink.Tasks to the latest release and fix build errors

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#36861]
We should consume the new IlLink.Tasks package that is published to the blob feed. Currently we target an old version. To not get stale dependencies we should also invest in auto-updating it.

**Comment by ericstj** [comment]
@sbomer can this be resolved?

**Comment by stephentoub** [comment]
Yup, we updated last week.

**Comment by stephentoub** [comment]
(Although it'd be nice to also do the "To not get stale dependencies we should also invest in auto-updating it" part.  Maybe a separate issue?)

**Comment by ViktorHofer** [comment]
I'll do that right now.

**Comment by ViktorHofer** [comment]
I just set up a subscription. This is now part of the batched dependency update in master.

**Comment by ViktorHofer** [comment]
Actually Version.Details.xml is missing the metadata for darc to update. Adding it: https://github.com/dotnet/corefx/pull/42270
