### ISSUE TITLE
HttpClient tries to verify the certificate issuer

### ISSUE THREAD

**Issue by mayconbeserra** [dotnet/corefx#36874]
**Description:** HttpClient Validates the CA Issuer when using a pfx.

**Expected:**

Since I have a pfx, with the password, my application should not need to access to the CA Issuer URL to perform a call against the desired endpoint which is already allowed in the security proxy. 

When we extract the pfx to PEM files, we don't have that issue using CURL.

**My scenario:**

My cluster doesn't have access to the internet, and when we try to call one endpoint which requires client authentication via PFX, the request is blocked because we can't validate the CA Issuer.

**Trace after giving access to the pki.caissuer-url.com**

```
[System.Threading.Tasks.TplEventSource-11] (1, 0, 25).
[Microsoft-System-Net-Http-21] (2649323, 50492551, 16023056, SendAsyncCore, HttpConnection(HttpConnectionPoolhttp://pki.caissuer-url.com:80): Sending request: Method: GET, RequestUri: 'http://pki.caissuer-url.com/aia/Ext-Issuing-CA01-G2.crt', Version: 2.0, Content: <null>, Headers:
{
  Request-Id: |8452871d-44cb710093771190.1.
}).
[Microsoft-System-Net-Http-21] (2649323, 50492551, 16023056, WriteToStreamAsync, HttpConnection(HttpConnectionPoolhttp://pki.caissuer-url.com:80): Writing 114 bytes.).
[Microsoft-System-Net-Sockets-1] (Socket#20318803, SendAsync, (AwaitableSocketAsyncEventArgs#53710617)).
[Microsoft-System-Net-Sockets-7] (AwaitableSocketAsyncEventArgs#53710617, LogBuffer, System.Byte[]).
[Microsoft-System-Net-Sockets-2] (Socket#20318803, SendAsync, False).
[Microsoft-System-Net-Http-1] (HttpResponseMessage#54181145, .ctor, (OK)).
[Microsoft-System-Net-Http-2] (HttpResponseMessage#54181145, .ctor, ).
[Microsoft-System-Net-Http-3] (HttpResponseMessage#54181145, RequestMessage, HttpResponseMessage#54181145, HttpRequestMessage#16023056).
[Microsoft-System-Net-Http-1] (HttpConnectionResponseContent#64062224, .ctor, ).
[Microsoft-System-Net-Http-2] (HttpConnectionResponseContent#64062224, .ctor, ).
[Microsoft-System-Net-Http-3] (HttpResponseMessage#54181145, Content, HttpResponseMessage#54181145, HttpConnectionResponseContent#64062224).
[Microsoft-System-Net-Sockets-1] (Socket#20318803, ReceiveAsync, (AwaitableSocketAsyncEventArgs#3129430)).
[Microsoft-System-Net-Sockets-2] (Socket#20318803, ReceiveAsync, True).
[System.Threading.Tasks.TplEventSource-26] (31).
[System.Threading.Tasks.TplEventSource-10] (1, 0, 31, 2, 0).
[System.Threading.Tasks.TplEventSource-26] (32).
[System.Threading.Tasks.TplEventSource-10] (1, 0, 32, 2, 0).
[System.Threading.Tasks.TplEventSource-26] (33).
[System.Threading.Tasks.TplEventSource-10] (1, 0, 33, 2, 0).
[System.Threading.Tasks.TplEventSource-26] (34).
[System.Threading.Tasks.TplEventSource-10] (1, 0, 34, 2, 0).
[System.Threading.Tasks.TplEventSource-13] (25).
[System.Threading.Tasks.TplEventSource-13] (24).
[System.Threading.Tasks.TplEventSource-13] (23).
[System.Threading.Tasks.TplEventSource-13] (22).
[System.Diagnostics.Eventing.FrameworkEventSource-30] (140296584203944).
[System.Diagnostics.Eventing.FrameworkEventSource-31] (140296584203944).
[Microsoft-System-Net-Sockets-7] (AwaitableSocketAsyncEventArgs#3129430, LogBuffer, System.Byte[]).
[Microsoft-System-Net-Http-21] (2649323, 50492551, 16023056, FillAsync, HttpConnection(HttpConnectionPoolhttp://pki.caissuer-url.com:80): Received 2750 bytes.).
[System.Threading.Tasks.TplEventSource-20] (31, 140296589470624).
[System.Threading.Tasks.TplEventSource-11] (1, 0, 31).
[System.Threading.Tasks.TplEventSource-20] (32, 140296589472320).
[System.Threading.Tasks.TplEventSource-11] (1, 0, 32).
[Microsoft-System-Net-Http-21] (2649323, 50492551, 16023056, SendAsyncCore, HttpConnection(HttpConnectionPoolhttp://pki.caissuer-url.com:80): Received response: StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:
{
  Accept-Ranges: bytes
  ETag: "881ddff67587d21:0"
  Server: Microsoft-IIS/8.5
  Date: Thu, 21 Mar 2019 10:23:43 GMT
  Content-Type: application/x-x509-ca-cert
  Last-Modified: Wed, 15 Feb 2017 10:26:26 GMT
  Content-Length: 2508
}).
```

**.NET Core SDK:** 2.1.505

**Comment by stephentoub** [comment]
cc: @bartonjs

**Comment by bartonjs** [comment]
If you're only providing one certificate in the client certificates collection then the system should just use it.  You'd still see a chain build where any intermediate certificates are trying to be looked up to be passed along on the TLS handshake, but it's not a filter at that point.

The collection isn't expected to be one chain (a la cURL) but a set of potential peers, and then information from the handshake helps to pick the correct one.  (Logic which is greatly simplified when ClientCertificates.Count is 0 or 1.)

**Comment by mayconbeserra** [comment]
Hi @bartonjs 

I didn't understand well your answer. the pfx file has all the chain when I extract the pfx to PEM files. In this case, I assume I would not need to add any ca authority certificate to the collection. Is it right?

And could you highlight how I could perform a request without hitting the ca issuer endpoint?

My code example is below:
```
            var certificate = new X509Certificate2("./Certificates/cert1.pfx", "password");
            var handler = new HttpClientHandler();

            handler.SslProtocols = SslProtocols.Tls11 | SslProtocols.Tls12;

            handler.ClientCertificates.Add(certificate);
            handler.CheckCertificateRevocationList = false;

            Console.WriteLine("Creating Http Client");
            HttpClient client = new HttpClient(handler);

            handler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => { return true; };

            Console.WriteLine("Getting User Info Data");

            try
            {
                var result = await client.GetAsync("https://my-api.com/api/v1/orders/0001");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
```

**Comment by bartonjs** [comment]
That code looks like it should work, even if the issuer endpoint can't be reached.

If you want to avoid the call altogether you'll need to cache the intermediate (and, potentially, root).  Once at startup you could so something like

```C#
using (X509Store store = new X509Store(StoreName.My, StoreLocation.CurrentUser, OpenFlags.ReadWrite))
{
    X509Certificate2Collection coll = new X509Certificate2Collection();
    coll.Import(pfxPath, pfxPassword, X509KeyStorageFlags.DefaultKeySet);

    foreach (X509Certificate2 cert in coll)
    {
        if (!cert.HasPrivateKey)
        {
            store.Add(cert);
        }

        cert.Dispose();
    }
}
```

This puts the intermediate and root (assuming they're both in the PFX and assuming you don't have private keys for them in the PFX) into the CurrentUser\My store, which is looked at during chain building but doesn't establish trust.

**Comment by mayconbeserra** [comment]
Hi @bartonjs 

Unfortunately, tried the code above but it's still hitting the pki endpoint.

If I ran from MacOS, everything works, but it doesn't from a docker container.

Would that be a bug in dotnet core?

**Comment by bartonjs** [comment]
> Would that be a bug in dotnet core on linux?

If you ran the "load to store" code as the same user which is building the chain, and it actually added things, and you're on .NET Core 2.1 or higher, then there does seem to be something wrong going on.

But, in order to really investigate it, we'd need a repro.

**Comment by mayconbeserra** [comment]
Hi @bartonjs 

Unfortunately, I can't provide a repository for that because of security reasons.

I did a double check here, and the certificates were loaded to store correctly. I also added your code together to my call, and it works now, thanks for that 🎉.

However, if there is a need to load the whole chain in the local store, that means the code below doesn't add the whole chain, right? 
`handler.ClientCertificates.Add(myPfxCertificate);`

**Comment by bartonjs** [comment]
`handler.ClientCertificates.Add(myPfxCertificate);` just adds one certificate.  As part of the TLS handshake the client cert is presented along with any intermediate certificates to help the remote side build the chain effectively.  If the local (client) side can't build the chain it just sends the cert with no intermediates and hopes the remote knows how to find the intermediates.

**Comment by bartonjs** [comment]
Based on "I also added your code together to my call, and it works now" it seems like there's not more work here.  So closing the issue.
