### ISSUE TITLE
XElement formating issue

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/corefx#36871]
XElement behaves bad with xml nodes that contain literal strings beside xml elements. In this case, XElement deletes all white spaces, including line separators, regardless of the reader and writer settings, and the method used to read the XElement content(using a reader, or ToString)
For example:
```VB.NET
Dim cshtml = 
<cshtml>
   <p>Test</p>
   @foreach (var i in items)
   {
     <h>item: </h>
     <div>
       <p>i</p>
     </div>
   }
   <p>End Test</p>
</cshtml>

Dim S = cshtml.ToString()
```

The resulting string in s will be:
```xml
<cshtml>
  <p>Test</p>
                             @foreach (var i in items)
                             {
                             <h>item: </h><div><p>i</p></div>
                             
                             }
                                 <p>End Test</p></cshtml>
```

The format is damaged because the c# string!. If you omitted it, every thing will work fine! Why?

**Comment by krwq** [comment]
@VBAndCs, XML spec allows to normalize whitespace around the text (I believe it should not touch whitespaces within text but not 100% sure without looking at the spec).

The situation should improve if you put `xml:space="preserve"` on the element containing such or use CDATA.

XML parser is still allowed to normalize line endings regardless of that setting.

Your best bet is to use XmlTextReader/XmlTextWriter with WhitespaceHandling option - it should work best when whitespaces are important.

Please let me know if this fixes your issue.

**Comment by VBAndCs** [comment]
@krwq
Thanks for your help. This is the result using `xml:space="preserve"`.. It doesn't preserv line breaks in my case:
```xml
<cshtml xml:space="preserve">
  <p>Test</p>
   @foreach (var i in items)
   {
     <h>item: </h><div xml:space="preserve"><p>i</p></div>
   }
   <p>End Test</p></cshtml>
```

I tried XmlTextReader/XmlTextWriter  before and got the same results. The only thing worked for me is this workaround:

```xml
<cshtml>
  <p>Test</p>
   <zmiItem0/>
   <zmlitem1/>
     <h>item: </h>
     <div>
          <p>i</p>
     </div>
   <zmlitem2>
   <p>End Test</p>
</cshtml>
```

Then I replace <zmlitemN/> in the output string.

**Comment by krwq** [comment]
@VBAndCs could you paste the code you are using for reading and writing XML with XmlTextReader/Writer? I wanted to double check if there is anything else we can do to improve this.

One other thing you might want to check: writer might be writing new lines but `\n` instead of `\r\n` - some editors might not display it correctly.

**Comment by VBAndCs** [comment]
@krwq
I deleted the Writer code since it didn't solve the issue. I tried different ways, untill I realized that if I erased the text parts, I get a correct xml format.
I checked  `\n` and tried to manually replace it, or use the replace option. Nothing changed as long as the XML contains that c# literal code!
I am satisfied with my workaround now, but I am reporting this so you can check what is happening and fix it for all developers.

**Comment by krwq** [comment]
@VBAndCs we will need a complete code sample which is not working correctly for this to be actionable.. Note XML is one of the largest libraries in corefx and there are multiple different Readers/Writers.

**Comment by VBAndCs** [comment]
I already gave the sample using VB.NET xml literals. You can try it as is:
```VB.NET
Dim cshtml = 
<cshtml>
   <p>Test</p>
   @foreach (var i in items)
   {
     <h>item: </h>
     <div>
       <p>i</p>
     </div>
   }
   <p>End Test</p>
</cshtml>

Dim S = cshtml.ToString()
Console.WriteLine(S)
```

You can trace the XElemnt.ToString() and see why it produces that code.
If you want C# sample:
```C#
var cshtml =
@"<cshtml>
   <p>Test</p>
   @foreach (var i in items)
   {
     <h>item: </h>
     <div>
       <p>i</p>
     </div>
   }
   <p>End Test</p>
</cshtml>";

var x = System.Xml.Linq.XElement.Parse(cshtml);
var S = cshtml.ToString();
```

You can trace Parse and ToString. 
Thanks.

**Comment by krwq** [comment]
@VBAndCs running C# above here is the output I get:

```xml
<cshtml>
   <p>Test</p>
   @foreach (var i in items)
   {
     <h>item: </h>
     <div>
       <p>i</p>
     </div>
   }
   <p>End Test</p>
</cshtml>
```

this looks the same as an input to me...

**Comment by VBAndCs** [comment]
Sorry, it exactly prints the input itself :D
Change `var S = cshtml.ToString();` to 'Dim S = x.ToString()' to print the xml string.

**Comment by VBAndCs** [comment]
```C#
var cshtml =
@"<cshtml>
   <p>Test</p>
   @foreach (var i in items)
   {
     <h>item: </h>
     <div>
       <p>i</p>
     </div>
   }
   <p>End Test</p>
</cshtml>";

var xml = System.Xml.Linq.XElement.Parse(cshtml);
var s = xml.ToString();
Console.WriteLine(s);
```

**Comment by krwq** [comment]
@VBAndCs didn't notice that, just quickly copy pasted... :man_facepalming:

**Comment by krwq** [comment]
@VBAndCs try this out: `XElement.Parse(cshtml, LoadOptions.PreserveWhitespace);`

**Comment by VBAndCs** [comment]
@krwq
It works. Thanks alot. Of course it will not work for xml literals becuase VB.NET does the parsing internally! Using string literal workarround is not always possible (it can contain embeded vb expressions). I will ask about this in VB.NET repo. 
Thanks again.

**Comment by krwq** [comment]
Glad it works for you :smile: (still facepalming on my first response though)

**Comment by VBAndCs** [comment]
It was my typo mistake in first place :) .. Sleap time errors :D .
