### ISSUE TITLE
Question: Behaviour of ThreadPool.SetMaxThreads(-1, -1)

### ISSUE THREAD

**Issue by filipnavara** [dotnet/corefx#36885]
There's a unit test for `ThreadPool.SetMaxThreads(-1, -1)` which expects it to succeed:

https://github.com/dotnet/corefx/blob/master/src/System.Threading.ThreadPool/tests/ThreadPoolTests.cs#L117

As far as I can tell this is undocumented behaviour. It seems to work in CoreCLR only because the managed prototype for `SetMaxThreadsNative` uses `int` as data type for the parameters, while the unmanaged prototype uses `DWORD`:

https://github.com/dotnet/coreclr/blob/de68c9ddd18f863fd67098ab28d19206c9c66627/src/System.Private.CoreLib/src/System/Threading/ThreadPool.CoreCLR.cs#L300-L301
https://github.com/dotnet/coreclr/blob/d3e39bc2f81e3dbf9e4b96347f62b49d8700336c/src/vm/comthreadpool.cpp#L127

Is this quirk something that is supposed to be supported and tested? It seems rather non-obvious why is it tested and what is the expected behaviour.

/cc @jkotas @kouvel

**Comment by filipnavara** [comment]
CoreRT returns `false` for the same parameters:

https://github.com/dotnet/corert/blob/110868358d75dff78744fde45fa84ba562fc23b7/src/System.Private.CoreLib/src/System/Threading/ThreadPool.Portable.cs#L335-L338

**Comment by jkotas** [comment]
Looks like a bug to me.

**Comment by kouvel** [comment]
Returning false makes sense to me. Probably the test was attempting to match desktop behavior.

**Comment by marek-safar** [comment]
@stephentoub could you help us to resolve the issue

**Comment by stephentoub** [comment]
> Probably the test was attempting to match desktop behavior.

Yes, netfx returns true for SetMaxThread(-1, -1).  It returns false for SetMinThreads(-1, -1).

The return value here for SetMaxThread is a bit misleading.  It returns true for any change, even if not changed to what you asked for, e.g. SetMaxThreads(int.MaxValue, int.MaxValue) will return true even though it sets both values instead to 32K.

Regardless, I can submit a PR to fix the return values for negative numbers.

**Comment by kouvel** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/24163
