### ISSUE TITLE
Add unlimited support for nested arrays to Json deserializer

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#36889]
Currently the deserializer does not support enumerables or jagged arrays greater than two dimension such as int[][][] being returned directly from a Parse() method. For enumerable properties on an object, that restriction is one dimension less: only a single level is supported: e.g. int[] or List<> and not int[][] or List<List<>>

These current limitations only apply to deserialization, not serialization.

Expect that there is no limit to the nesting of arrays or enumerables from the root or as properties on an object.

cc @layomia

**Comment by ahsonkhan** [comment]
From @pranavkm (from https://github.com/dotnet/corefx/issues/37317):
> 
```C#
class Container
{
    public int[][] Matrix { get; set; }
}

var json = "{\"Matrix\": [[1, 2], [3, 4]]}";
Console.WriteLine(JsonSerializer.Parse<Container>(json));
```

> This seems to work though:

```C#
var json = "[[1, 2], [3, 4]]";
Console.WriteLine(JsonSerializer.Parse<int[][]>(json).Length);
```
