### ISSUE TITLE
Why is Task<T> not covariant?

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/corefx#36892]
Does anybody have some history as to why this was done?

maybe @stephentoub ?

**Comment by stephentoub** [comment]
Because classes can't be covariant, only delegates and interfaces.

**Comment by inputfalken** [comment]
@stephentoub 

Would it be possible to make `Task<T>` an implementation of a covariant interface in the future?

**Comment by stephentoub** [comment]
We've discussed multiple times whether it'd be worth adding such an interface, including at length when we initially added async/await to the language, and each time decided no.  You're welcome to open an issue proposing it, but I wouldn't expect much progress on it any time soon.
