### ISSUE TITLE
Windows Compat Pack - unable to find a stable System.Data.SqlClient >= 4.6.1

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#36902]
Creating issue for multiple customer reported issues:

_User grant <grantwinney@protonmail.com> sends the following message to the owners of Package 'Microsoft.Windows.Compatibility 2.1.0'._

> Every time I try to upgrade my .NET Standard library from v2.0.1 to v.2.1.0 I get the following error and it rolls back to 2.0.1:
> **NU1103: Unable to find a stable package System.Data.SqlClient with version (>= 4.6.1)**
> •	Found 32 version(s) in nuget.org [ Nearest version: 4.7.0-preview.18571.3 ]
> •	Found 2 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 4.1.0 ] Package restore failed. Rolling back package changes for 'Logger'.
> Is this new version dependent on System.Data.SqlClient for some reason? I don't use it in my application, and don't have a dependency on it.

_User arbor <info@nlundberg.se> sends the following message to the owners of Package 'Microsoft.Windows.Compatibility 2.1.0'._

> **NuGet package Microsoft.Windows.Compatibility version 2.1.0 released to NuGet has a dependency to System.Data.SqlClient >= 4.6.1 that is not on NuGet**.

_User dwn <diwendt@microsoft.com> sends the following message to the owners of Package 'Microsoft.Windows.Compatibility 2.1.0'._

> 2.1.0 breaks installation of this package:
> Severity Code Description Project File Line Suppression State Error NU1103 **Unable to find a stable package System.Data.SqlClient with version (>= 4.6.1)**
> •	Found 1272 version(s) in https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json [ Nearest version: 4.7.0-alphautf8string.18530.6 ]
> •	Found 32 version(s) in nuget.org [ Nearest version: 4.7.0-preview.18571.3 ]
> •	Found 0 version(s) in Microsoft Visual Studio Offline Packages
> •	Found 0 version(s) in https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/index.json
> •	Found 0 version(s) in https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/index.json
> •	Found 0 version(s) in https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/index.json
> •	Found 0 version(s) in https://dotnetfeed.blob.core.windows.net/aspnet-extensions/index.json
> •	Found 0 version(s) in https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/index.json
> •	Found 0 version(s) in secassure dotnetcoretest E:\code\dotnetcoretest\dotnetcoretest.csproj 1

**Comment by danmosemsft** [comment]
@ericstj

**Comment by ericstj** [comment]
https://github.com/dotnet/corefx/commit/8681eefb557edbb50bd9e96c785388d836d44331
https://github.com/dotnet/corefx/commit/c82b438c8ed6eaba3dbed009cd484d5bb392237e

@wtgodbe it looks like servicing missed publishing 4.6.1 of SqlClient.

**Comment by wtgodbe** [comment]
Yes, unfortunately we did :( We discovered this in https://github.com/dotnet/corefx/pull/36060, and will ship that package with 2.2.5. That was the motivation for https://github.com/dotnet/arcade/issues/2419.

**Comment by TravisEz13** [comment]
Will `Microsoft.Windows.Compatibility` be updated to fix this or just publish SqlClient?  If it is the second, what is the ETA?  I want to make sure we don't miss this change.

**Comment by wtgodbe** [comment]
We'll be shipping an updated `Microsoft.Windows.Compatibility` concurrently to the new `System.Data.SqlClient` with out May servicing release, which should go public early in May.

**Comment by ericstj** [comment]
In the meantime you should unlist the one with the dangling dependency.

**Comment by grantwinney** [comment]
Agreed. There'll be a lot of confused people opening duplicate issues. Plus, Visual Studio shows a yellow exclamation for my project that's nagging me to update the package.

**Comment by wtgodbe** [comment]
Sounds good, I'll follow up offline with the nuget folks.

**Comment by wtgodbe** [comment]
I just unlisted the 2.1.0 version of the package from nuget.org.

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). 

I assume however that this specific issue is really about what is included in Windows Compatibility Pack and not really about System.Data.SqlClient, so I am not going to move it to the new repo. 

@danmosemsft any thoughts?

**Comment by danmosemsft** [comment]
@wtgodbe is this now resolved (since May release)?

**Comment by wtgodbe** [comment]
Yes, this should be resolved now. Here's the [4.6.1 version of SqlClient](https://www.nuget.org/packages/System.Data.SqlClient/4.6.1), and the [2.1.1 version of the Compatibility package](https://www.nuget.org/packages/Microsoft.Windows.Compatibility/2.1.1).

**Comment by danmosemsft** [comment]
thanks @wtgodbe
