### ISSUE TITLE
project.lock.json files are all out of date as of yesterday afternoon.

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#3691]
- git checkout master (no local changes)
- build.cmd
- git status
- Ponder the sea of red as the build process made local changes to every project.lock.json file in the project.

I assume fixing this is just a matter of checking in those changes, but since I don't know what caused it, I'm not blindly sticking my head out either.

**Comment by weshaggard** [comment]
We are hitting bug https://github.com/aspnet/dnx/issues/2771 where one bad project.lock.json file causes them all to be regenerated. We need to figure out which lock file really needs updated and update that one and this problem goes away. I will have a look.

**Comment by weshaggard** [comment]
For future reference if you look at your log file you will see something a long the lines of `Updating the invalid lock file with dnu restore --lock` in the BatchRestorePackages that will point to the individual project.lock.json file that is invalidated. If you build just that project it will update that lock file and the batch restore will no longer regenerate all the lock files.
