### ISSUE TITLE
A bug of Image.GetThumbnailImage in System.Drawing.Common

### ISSUE THREAD

**Issue by NanaseRuri** [dotnet/corefx#36914]
I tried to get some thumbnails by Image.GetThumbnail and I found that the solid color picture will get a larger size. I wonder if there is a bug here. Of course the method works well in other case.
Project: https://github.com/NanaseRuri/FakeBilibili

![QQ截图20190416170345](https://user-images.githubusercontent.com/32630839/56196647-d3a2b880-6069-11e9-91d6-17324c3cbe9b.png)
![QQ截图20190416170449](https://user-images.githubusercontent.com/32630839/56196648-d3a2b880-6069-11e9-9e61-d95f2d8a1f01.png)
![QQ截图20190416170507](https://user-images.githubusercontent.com/32630839/56196649-d43b4f00-6069-11e9-9c37-a238285123e6.png)

The pictures:
![1](https://user-images.githubusercontent.com/32630839/56196683-e2896b00-6069-11e9-9063-e96cb3ae1ede.jpg)
![1 min](https://user-images.githubusercontent.com/32630839/56196685-e3ba9800-6069-11e9-93bd-84f80550aa71.jpg)

**Comment by safern** [comment]
Thanks @NanaseRuri for reporting the issue. Could you please help me providing the version of .NET Core and System.Drawing.Common package that you used?

**Comment by NanaseRuri** [comment]
> Thanks @NanaseRuri for reporting the issue. Could you please help me providing the version of .NET Core and System.Drawing.Common package that you used?

My fault.

`.Net Core :                                2.2.104
 System.Drawing.Common:       4.5.1`

**Comment by safern** [comment]
Thanks for confirming @NanaseRuri
