### ISSUE TITLE
PostNonRewindableContentUsingAuth_NoPreAuthenticate_ThrowsInvalidOperationException fails on Linux

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#3693]
System.Net.Http.Functional.Tests:
Reference PR: #3680
Reference build: http://dotnet-ci.cloudapp.net/job/dotnet_corefx_prtest/4926/

PostNonRewindableContentUsingAuth_NoPreAuthenticate_ThrowsInvalidOperationException looks like it's failing because it's expecting an InvalidOperationException but is getting an HttpRequestException.

The InvalidOperationException should not be wrapped within a HttpRequestException by CurlHandler. See WinHttpHandler. It only wraps WinHttpException and IOException. WinHttpHandler also matches .NET Desktop.

**Comment by davidsh** [comment]
cc: @stephentoub @kapilash

**Comment by kapilash** [comment]
@stephentoub  fixed this via #3767
