### ISSUE TITLE
Deserializer should use Dictionary for property name lookup when high property count or case insensitive

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#36939]
This is a placeholder for a todo in JsonClassInfo.cs that states:
```
// Todo: on classes with many properties (about 50) we need to switch to a hashtable for performance. 
// Todo: when using PropertyNameCaseInsensitive we also need to use the hashtable with case-insensitive 
// comparison to handle Turkish etc. cultures properly.
```

The case insensitive section relates to feature https://github.com/dotnet/corefx/issues/36351.

**Comment by ahsonkhan** [comment]
> The case insensitive section relates to feature https://github.com/dotnet/corefx/issues/3635.

I believe the issue being linked is https://github.com/dotnet/corefx/issues/36351

**Comment by steveharter** [comment]
@ahsonkhan yes thanks. Updated.
