### ISSUE TITLE
PostNonRewindableContentUsingAuth_PreAuthenticate_Success fails on Linux

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#3695]
System.Net.Http.Functional.Tests:
Reference PR: #3680
Reference build: http://dotnet-ci.cloudapp.net/job/dotnet_corefx_prtest/4926/

PostNonRewindableContentUsingAuth_PreAuthenticate_Success is failing with a CurlException "Send failed since rewinding of the data stream failed".
This is failing because it is trying to rewind a non-rewindable stream. BUT it shouldn't be attempting that. It shouldn't need to rewind the stream because the POST should succeed right away. This tells me that the .PreAuthenticate feature in the Linux version of the Handler (CurlHandler) is broken. The test is issuing a HEAD request first which should "warm up" the authentication for the .PreAuthenticate=true. But it looks like it is broken.

Also, the CurlHandler should NOT be rewinding the stream on its own.  Only the HttpContent class do that as part of the contract for SerializeToStreamAsync().  See StreamContent.cs in the Http Library.

I see that the Linux code might be calling Seek to rewind the content to re-POST it. That itself shouldn't happen because only the StreamContent class is responsible for rewinding itself. The handlers are NOT supposed to rewind the content on their own. I suspect that the CurlHandler is doing this because one of the tests is failing with a CurlHandler specific message:

"Send failed since rewinding of the data stream failed".
That code probably needs to change in CurlHandler.  There shouldn't be a separate string resource for this error since CurlHandler shouldn't be rewinding content.

**Comment by davidsh** [comment]
cc: @stephentoub @kapilash

**Comment by kapilash** [comment]
This is fixed via #3806 Closing this.
