### ISSUE TITLE
ToLower Comparations UTF-8 works on Windows but not on Linux

### ISSUE THREAD

**Issue by vasicvuk** [dotnet/corefx#36952]
The following sample:
```csharp
using System;
using System.Linq;
public class Program
{
    public static void Main()
    {
        var line = "Место и општин» ресеп matching";
        var match = new string[] { "место", "place" };
        if (match.Any(line.ToLower().Contains))
        {
            Console.WriteLine("matches");
        }
        Console.ReadLine();
    }
}
```

returns **matches** as output on Windows, but on Linux it does not print **matches**.

The problem is with **ToLower()** after which **StartsWith** and **Contains** (that i tested) are not working properly. 

.Net Core version: **2.2.101.**

For Linux i used Docker image: **microsoft/dotnet:2.2-aspnetcore-runtime-alpine**

**Comment by huoyaoyuan** [comment]
Are you in globalization-invariant mode? Only ASCII chars will be cased then.
See https://github.com/dotnet/corefx/blob/master/Documentation/architecture/globalization-invariant-mode.md

**Comment by vasicvuk** [comment]
I have not set globalization-invariant mode. Is this by default?

**Comment by huoyaoyuan** [comment]
The document says off by default. You can do a check on behaviors in [this section](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/globalization-invariant-mode.md#cultures-and-culture-data).

**Comment by jkotas** [comment]
> I have not set globalization-invariant mode. Is this by default?

It is on by default on Alpine. https://github.com/dotnet/dotnet-docker-nightly/issues/500 has details.

**Comment by tarekgh** [comment]
Alpine image has the invariant globalization mode is on by default, which means, will not get the appropriate globalization support. The issue is tracked by Oryx team here https://github.com/Microsoft/Oryx/issues/68. They are working to change the deployment to different image as Alpine was done by mistake.
