### ISSUE TITLE
StringBuilder ChunkEnumerator.Current fails with NRE exception when MoveNext is not called.

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#36973]
```cs
        static void Main(string[] args)
        {
            StringBuilder sb = new StringBuilder();
            sb.Insert(0, new char[] {'h', 'e', 'l', 'l', 'o'});
            var enumerator = sb.GetChunks();
            Console.WriteLine(enumerator.Current);
        }
```

This fails with a NRE. 

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Text.StringBuilder.ChunkEnumerator.get_Current()
   at tmp2.Program.Main(String[] args) in C:\repos\tmp2\Program.cs:line 13
```

In order to avoid that I would have to call `MoveNext` before calling `Current` -- because of this, doing a foreach on the chunks will not fail.

cc: @stephentoub @krwq @JeremyKuhne

**Comment by bbartels** [comment]
Isn't this expected behaviour though? IEnumerable works in the same way, throwing an exception when Current is called before MoveNext()?
Albeit a System.InvalidOperationException would probably be more sensible, to keep it consistent with IEnumerable.

**Comment by danmosemsft** [comment]
Right, Current is not defined until you succcessfuly do the first MoveNext. We seem to sometimes return default, sometimes throw IOE. In this case we are throwing NRE by accident. It should probably throw IOE.

**Comment by safern** [comment]
I agree. Yes this issue is to avoid throwing a NRE, but instead be consistent with all the Enumerators we have accross the frameworks.
