### ISSUE TITLE
[Linux] Incorrect output for "g" custom `DateTimeOffset` format specifier

### ISSUE THREAD

**Issue by dougbu** [dotnet/corefx#3698]
The following statement behaves differently on Windows and Linux when `CultureInfo.CurrentCulture` is `new Culture("en-GB")`. See [full test application](https://github.com/dougbu/CultureInfo) for more context.
``` c#
Console.WriteLine("Formatted now '{0:dddd, yyyy/MM/dd/ g}'.", DateTimeOffset.Now);
```

On Windows using either `dnx451` or `dnxcore50` and on Linux using `dnx451` (i.e. Mono), the output is:
```
Formatted now 'Wednesday, 2015/10/07/ A.D.'.
```

However on Linux using `dnxcore50`:
```
Formatted now 'Wednesday, 2015/10/07/ AD'.
```

Note periods are missing in Linux / `dnxcore50` output. Not sure if other custom (or standard) format specifiers behave differently on Linux in some locales.

----

OS: Ubuntu 14.04.3 LTS
DNX: 1.0.0-rc1-15837
System.Globalization/4.0.11-beta-23405
System.Globalization.Extensions/4.0.1-beta-23405
System.Runtime/4.0.21-beta-23405

**Comment by tarekgh** [comment]
CC @eerhardt 

The framework depends on the OS for getting the values of the date formatting parts. So you can expect some differences like that as the framework don't really carry of such data (like the era names for instance).
Eric may talk more about that as spend some time on Linux reading such data but in general if we came across different data like that, the issue has to be raised to the OS itself to fix the issue. in this case ICU will need to update such data. 
we may come across some cases need to be special cased in the framework but so far we don't have any.

**Comment by ellismg** [comment]
In general we'll guarantee the same locale data is present for Invariant (note that sorts might be different across platforms), but we don't make any guarantees of stability across platforms (note you can construct applications that behave differently on different version of Windows on both CoreCLR and the Full Desktop Framework).

Applications shouldn't depend on this data being stable.

This means if you are going to persist data and expect it to round trip, you need to be using InvariantCulture at a minimum.
