### ISSUE TITLE
Float formatting writing in scientific notation on Windows x86 rather than standard format ('G')

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#36986]
Writing floats is failing **only on** `Windows.10.Amd64.ClientRS5.Open-x86-Release`, i.e. **Windows and x86**, where its writing the float in scientific notation rather than following the 'G':

For example check the following where I get an isolated repro: https://github.com/dotnet/corefx/pull/36985/commits/cef2e42b9c11cf3c28853540016c9f426c836b0b from https://github.com/dotnet/corefx/pull/36985

This came up in Utf8JsonWriter use case where the test is failing [WriteNumberValueSingle](https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F36961~2Fmerge/test~2Ffunctional~2Fcli~2F/20190417.66/workItem/System.Text.Json.Tests/analysis/xunit/System.Text.Json.Tests.Utf8JsonWriterTests~2FWriteNumberValueSingle(formatted:%20False,%20skipValidation:%20False)):
```text
Assert.Equal() Failure
            ↓ (pos 2)
Expected: [12345678,12345678,12345678,12345678,123456···
Actual:   [1.234568E+07,1.234568E+07,1.234568E+07,1.2···
            ↑ (pos 2)
```

Same issue with `12345680`

Tried the following:
```C#
        [Fact]
        public void TestWritingFloat1()
        {
            var output = new byte[100];
            Assert.True(WriteNumberValueMinimized((float)12345678, output, out int bytesWritten));
            
            string expectedStr = "12345678";

            string actualStr = Encoding.UTF8.GetString(output.AsSpan(0, bytesWritten).ToArray());

            string message = $"{bytesWritten}, {expectedStr.Length}, {actualStr.Length}, ";
            if (expectedStr != actualStr)
            {
                int length = Math.Min(bytesWritten, expectedStr.Length);
                for (int i = 0; i < length; i++)
                {
                    if (output[i] != (byte)expectedStr[i])
                    {
                        message += $"{i}, {output[i]}, {(byte)expectedStr[i]},";
                        break;
                    }
                }
            }

            Assert.True(expectedStr == actualStr, message);
            Assert.True(expectedStr != actualStr, message);
        }

        [Fact]
        public void TestWritingFloat2()
        {
            var output = new byte[100];
            Assert.True(WriteNumberValueMinimized((float)12345680, output, out int bytesWritten));

            string expectedStr = "12345680";

            string actualStr = Encoding.UTF8.GetString(output.AsSpan(0, bytesWritten).ToArray());

            string message = $"{bytesWritten}, {expectedStr.Length}, {actualStr.Length}, ";
            if (expectedStr != actualStr)
            {
                int length = Math.Min(bytesWritten, expectedStr.Length);
                for (int i = 0; i < length; i++)
                {
                    if (output[i] != (byte)expectedStr[i])
                    {
                        message += $"{i}, {output[i]}, {(byte)expectedStr[i]},";
                        break;
                    }
                }
            }

            Assert.True(expectedStr == actualStr, message);
            Assert.True(expectedStr != actualStr, message);
        }

        private bool WriteNumberValueMinimized(float value, byte[] output, out int bytesWritten)
        {
            return Utf8Formatter.TryFormat(value, output, out bytesWritten);
        }
```

**Expected something like the following (since all bytes should match):** And we do get this behavior on other OSes and on Windows-x64.
```text
Message :
8, 8, 8, 
Expected: True
Actual:   False
Stack Trace :
   at System.Text.Json.Tests.Utf8JsonWriterTests.TestWritingFloat2() in /Users/vsts/agent/2.149.2/work/1/s/src/System.Text.Json/tests/Utf8JsonWriterTests.cs:line 3013
```

[TestWritingFloat1](https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F36985~2Fmerge/test~2Ffunctional~2Fcli~2F/20190417.73/workItem/System.Text.Json.Tests/analysis/xunit/System.Text.Json.Tests.Utf8JsonWriterTests~2FTestWritingFloat1)

```text
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
12, 8, 12, 1, 46, 50,
Expected: True
Actual:   False
Stack Trace :
   at System.Text.Json.Tests.Utf8JsonWriterTests.TestWritingFloat1() in D:\a\1\s\src\System.Text.Json\tests\Utf8JsonWriterTests.cs:line 2978
```

[TestWritingFloat2](https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F36985~2Fmerge/test~2Ffunctional~2Fcli~2F/20190417.73/workItem/System.Text.Json.Tests/analysis/xunit/System.Text.Json.Tests.Utf8JsonWriterTests~2FTestWritingFloat2)
```text
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
12, 8, 12, 1, 46, 50,
Expected: True
Actual:   False
Stack Trace :
   at System.Text.Json.Tests.Utf8JsonWriterTests.TestWritingFloat2() in D:\a\1\s\src\System.Text.Json\tests\Utf8JsonWriterTests.cs:line 3006
```

[TestWritingFloatIBW1](https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F36985~2Fmerge/test~2Ffunctional~2Fcli~2F/20190417.73/workItem/System.Text.Json.Tests/analysis/xunit/System.Text.Json.Tests.Utf8JsonWriterTests~2FTestWritingFloatIBW1)
```text
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
12, 12, 12, 1, 46,
Expected: True
Actual:   False
Stack Trace :
   at System.Text.Json.Tests.Utf8JsonWriterTests.TestWritingFloatIBW1() in D:\a\1\s\src\System.Text.Json\tests\Utf8JsonWriterTests.cs:line 3051
```

[TestWritingFloatIBW2](https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F36985~2Fmerge/test~2Ffunctional~2Fcli~2F/20190417.73/workItem/System.Text.Json.Tests/analysis/xunit/System.Text.Json.Tests.Utf8JsonWriterTests~2FTestWritingFloatIBW2)
```text
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
12, 12, 12, 1, 46,6, 54,7, 56,
Expected: True
Actual:   False
Stack Trace :
   at System.Text.Json.Tests.Utf8JsonWriterTests.TestWritingFloatIBW2() in D:\a\1\s\src\System.Text.Json\tests\Utf8JsonWriterTests.cs:line 3098
```

cc @tannergooding, @jkotas, @GrabYourPitchforks

**Comment by stephentoub** [comment]
> only on Windows.10.Amd64.ClientRS5.Open-x86-Release, i.e. Windows and x86

That's netfx, right?

**Comment by tannergooding** [comment]
Do you have an isolated repro that shows this failing as a result of a UTF8Formatter call or a value.ToString call?

**Comment by tannergooding** [comment]
> That's netfx, right?

If its netfx, that has entirely different parsing/formatting logic that hasn't been made IEEE compliant and differs from the x64 logic.

You might be able to repro using netcoreapp2.1 locally.

**Comment by ahsonkhan** [comment]
> Do you have an isolated repro that shows this failing as a result of a UTF8Formatter

See code snippet above. I am only calling Utf8Formatter API there.

> That's netfx, right?

Is it, I am not sure.

**Comment by ahsonkhan** [comment]
> You might be able to repro using netcoreapp2.1 locally.

Yep, I can repro locally on netfx!

**Comment by ahsonkhan** [comment]
Yep, the issue exists on .NET Core 2.1.

```C#
        static void Main(string[] args)
        {
            float value = 12345678;

            Console.WriteLine((float)12345678); // 1.234568E+07
            Console.WriteLine(float.Epsilon); // 1.401298E-45

            var output = new byte[100];

            Utf8Formatter.TryFormat(value, output, out int bytesWritten);

            string actualStr = Encoding.UTF8.GetString(output.AsSpan(0, bytesWritten).ToArray());

            Console.WriteLine(actualStr); // 1.234568E+07
        }
```

On .NET Core 3.0, output is as follows:
```text
12345678
1E-45
12345678
```

**Comment by ahsonkhan** [comment]
Closing it as expected/by-design.
