### ISSUE TITLE
How to get the version of this source that's shipped with FW 4.7.2?

### ISSUE THREAD

**Issue by IanKemp** [dotnet/corefx#36991]
I'm using `System.Net.Http.HttpClient` in a .NET Framework 4.7.2 project and have encountered an issue that I need to troubleshoot by stepping through the source of `HttpClient`. Visual Studio is able to download the PDB for `System.Net.Http.dll` from the Microsoft symbol servers but can't find matching source files, which means stepping doesn't work..

The obvious solution - cloning this `corefx` repo and pointing VS to that when it asks me to locate source files - doesn't work because the 4.7.2 PDB from the symbol server doesn't match the current version of the code in `corefx`.

I have managed to get around this somewhat by using JetBrains dotPeek as a symbol server, to generate a PDB and thus source files from the 4.7.2 version of `System.Net.Http.dll` that's in my GAC, but this is not particularly optimal. Obviously the ideal and simplest solution is to have the requisite source files available for download from the symbol servers - but since this is apparently too logical for Microsoft, an acceptable fallback would be to be able to clone a version of this repo that has the 4.7.2 sources.

Does said version (tag) exist and if so, what is it?

**Comment by Gnbrkm41** [comment]
I believe .NET Core and .NET Framework does not share the same source. In fact, there has been a lot of changes introduced into .NET Core that are not present in .NET Framework (e.g. Widespread internal use of Span<T>s) as there's less worries for making 'breaking changes'.

One place you can find .NET Framework source would be the [Reference source](https://referencesource.microsoft.com), which if I remember correctly, lets you download the whole of the source codes of .NET Framework. However, although it generally works, it is not completely up-to-date and you might see that debugger points to absurd places (e.g. comments).

**Comment by Gnbrkm41** [comment]
Considering this is more of a .NET Framework question, you might have better luck with [VS developer
community](https://developercommunity.visualstudio.com/spaces/8/index.html) as that's the place for .NET Framework related questions/bug reports.

**Comment by Gnbrkm41** [comment]
https://github.com/Microsoft/referencesource has (subset of?) sources for .NET Framework as well. The difference I know of is only the license, but I'm not sure if any of these is more up-to-date.

**Comment by danmosemsft** [comment]
I am asking folks offline as well.

**Comment by karelz** [comment]
.NET HttpClient is entirely different than the one in .NET Framework - see my talk [.NET Core Networking stack](https://karelz.github.io/details) from DotNext 2017 Moscow conference if you're interested in details.

.NET Framework 4.7.2 sourced were published on reference source: https://referencesource.microsoft.com (see https://github.com/Microsoft/referencesource/pull/59).
If it does not work, please try simple HelloWorld repro with just HttpClient and check that it works.

**Comment by karelz** [comment]
I think this should be now addressed. If the above does not work on HelloWorld-style app, feel free to reopen.

**Comment by karelz** [comment]
OK, turns out the entire directory with HttpClient.cs is missing from reference source :(

**Comment by karelz** [comment]
Duplicate of https://github.com/Microsoft/referencesource/issues/75

**Comment by danmosemsft** [comment]
Sources shared by https://github.com/Microsoft/referencesource/pull/105

This is not the same as being on source server, but you can manually point the debugger there.
