### ISSUE TITLE
build.sh issue on OSX, "Too many open files"

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#3701]
I'm getting the following error while running build.sh on Mac OSX, using a locally-built mono from source:

````
error MSB6003: The specified task executable "csc2.exe" could not be run. Too many open files.
````
This occurs about halfway through my build, before which everything seems to be going fine. Has anyone encountered this? I can build everything individually it seems.

**Comment by akoeplinger** [comment]
Did you increase your `ulimit`? The default is pretty low.

**Comment by mellinoe** [comment]
Thanks, that's probably the issue. OSX newbie here...
