### ISSUE TITLE
Uri.LocalPath returns `\` in path in Linux

### ISSUE THREAD

**Issue by ashishnegi** [dotnet/corefx#37026]
**Steps:**
1. in any `dotnet new console` app's Program.cs, put these lines

```cs
var path = new System.Uri(Assembly.GetExecutingAssembly().CodeBase).LocalPath;
var dirPath = Path.GetDirectoryName(path); // empty on Linux and right on windows.
```

`dirPath` is empty in Linux and right value in windows.

**Problem:**

To get the path of executing assembly, `new System.Uri(Assembly.GetExecutingAssembly().CodeBase).LocalPath` is the [recommended](https://stackoverflow.com/questions/52797/how-do-i-get-the-path-of-the-assembly-the-code-is-in) approach.
However, it returns `\` as name-separator in paths in Linux. As `\` is a valid file-name the returned path is wrong. It can't be used to perform any other operation.

**Expected:**
`Uri.LocalPath` should contain right platform specific `name-separator` character.
Note: `/` is supported `name-separator` character on all platform.

**Comment by danmosemsft** [comment]
What is `Assembly.GetExecutingAssembly().CodeBase` giving..

**Comment by davidsh** [comment]
Historically, the Uri.LocalPath is always problematic.  The URI RFCs are not very descriptive on this part. We originally supported Windows filepaths (hence the backslash separator) since this code came from .NET Framework. We made various changes/PRs over the last year or so to make Linux support for this better.  We should be careful of further changes to avoid regressions which happened last year while trying to fix this area.

**Comment by davidsh** [comment]
@wtgodbe

**Comment by tmds** [comment]
It's not clear what the issue is.
Using .NET Core 3.0 preview4 on Linux:
```
using System;
using System.IO;
using System.Reflection;

namespace console
{
    class Program
    {
        static void Main(string[] args)
        {
            var path = new System.Uri(Assembly.GetExecutingAssembly().CodeBase).LocalPath;
            var dirPath = Path.GetDirectoryName(path); // empty on Linux and right on windows.
            System.Console.WriteLine(dirPath);
        }
    }
}
```

```
$ dotnet run
/tmp/console/bin/Debug/netcoreapp3.0
$ dotnet bin/Debug/netcoreapp3.0/console.dll
/tmp/console/bin/Debug/netcoreapp3.0
```

**Comment by ashishnegi** [comment]
I am using latest of dotnet 2.2

```bash
testadm@asdi1-1:~$ cd dirpath/
testadm@asdi1-1:~/dirpath$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.203
 Commit:    e5bab63eca

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.203/

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  2.2.203 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
testadm@asdi1-1:~/dirpath$ cat
bin/            dirpath.csproj  obj/            Program.cs
testadm@asdi1-1:~/dirpath$ cat dirpath.csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

</Project>
testadm@asdi1-1:~/dirpath$
testadm@asdi1-1:~/dirpath$

```

**Comment by ashishnegi** [comment]
I realized that problem is occurring when asking for assembly path from a dll loaded from dotnet [StartHook](https://github.com/dotnet/core-setup/pull/4421/files) feature.
Let me create reproducible steps and open this issue again.
