### ISSUE TITLE
CancellationTokenSource.Token comment should say "a" not "the"

### ISSUE THREAD

**Issue by IanMercer** [dotnet/corefx#37025]
https://github.com/dotnet/corefx/blob/df5bba114e23afc4a3621917da0a1f810be19e7a/src/Common/src/CoreLib/System/Threading/CancellationTokenSource.cs#L99

Currently the comment displays as "Gets the CancellationToken associated with this CancellationTokenSource." but if you examine the code you will see it hands out a new CancellationToken each time.

Suggest comment should be "Gets a CancellationToken associated with ..." instead.

**Comment by stephentoub** [comment]
Thanks, but I think it's fine as is.  `CancellationToken` is a value type; every `CancellationToken` value that wraps the same `CancellationTokenSource` is logically the same `CancellationToken` and indistinguishable from any other one created in the same way.

**Comment by IanMercer** [comment]
Yeah, I saw afterwards that it has an Equals method that makes them behave as if they were equal.
