### ISSUE TITLE
Compile error in src/Microsoft.VisualBasic.Core/tests/VB with `dotnet test /p:targetgroup=netfx`

### ISSUE THREAD

**Issue by cston** [dotnet/corefx#37037]
Compile error in src/Microsoft.VisualBasic.Core/tests/VB with `dotnet test /p:targetgroup=netfx`:
```
>dotnet test /p:targetgroup=netfx
FileIOTestBase.vb(12,18): error BC30002: Type 'IO.FileCleanupTestBase' is not defined.
```

See https://github.com/dotnet/corefx/pull/37010#issuecomment-484955991.

**Comment by danmosemsft** [comment]
I assume this also tracks enabling tests for NETFX as noted in that linked PR.

**Comment by cston** [comment]
Fixed in https://github.com/dotnet/corefx/pull/37277.
