### ISSUE TITLE
Expose Http2 support or Max http version on Http.SocketsHttpHandler

### ISSUE THREAD

**Issue by IlyaGrebnov** [dotnet/corefx#37034]
CC @stephentoub 

If I read code correctly SocketsHttpHandler do not respect HttpRequestMessage.Verion same way as WinHttpHandler and HTTP2 need to be explicitly enabled via run time switch. I am not feel using run time switch in library. So would it be possible to expose switch at SocketsHttpHandler level? Note, using existing property (generic .Properties is fine with me) or changing behavior to respect HttpRequestMessage.Verion  would be preferred way, because in this I can avoid adding yet another target for library (I already have 4.5, 4.6.1, net standard 2.0 and .core 2.1).

**Comment by davidsh** [comment]
We plan to address this for .NET Core 3.0.  The current AppContext and environment variables inside SocketsHttpHandler is only temporary.

**Comment by stephentoub** [comment]
Closing as dup of https://github.com/dotnet/corefx/issues/35138
