### ISSUE TITLE
The documentation comment for UTF8JsonReader.ValueSequence has a typo

### ISSUE THREAD

**Issue by stephan-tolksdorf** [dotnet/corefx#37036]
The documentation comment for [`UTF8JsonReader.ValueSequence`](https://github.com/dotnet/corefx/blob/87fdc75beacc76e02c8e572ae3b0613b418200eb/src/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.cs#L118-L120) incorrectly states "Therefore, only access `ValueSpan` if `HasValueSequence` is true. Otherwise, the token value must be accessed from `ValueSpan`." It should be "only access `ValueSequence` if `HasValueSequence` is true".

**Comment by danmosemsft** [comment]
Thanks. Would you like to offer a quick PR?

**Comment by danmosemsft** [comment]
You can probably do it on the web page with the "pencil" icon in github.

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/dotnet/corefx/pull/37038
