### ISSUE TITLE
RSAES_OAEP certificates do not work with EnvelopedCms

### ISSUE THREAD

**Issue by vcsjones** [dotnet/corefx#37042]
While working on #34366 I found a few code paths that seem to imply certificates with a SPKI of RSAES_OAEP are supposed to work but there are a couple of things preventing that when I actually tried it.

The first is that this switch statement for the managed PAL does not handle the RsaOaep OID:

https://github.com/dotnet/corefx/blob/432a34fed6f0db6d76d5b3f8bbc8297fb0aa5f6b/src/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/AnyOS/ManagedPal.Encrypt.cs#L110-L115

Over in the Windows PAL, RSAES_OAEP certificates are not correctly handled here:

https://github.com/dotnet/corefx/blob/eb63183901fbe6afc2be4e1ff0f365fe20cefbf5/src/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/Windows/PkcsPalWindows.Encrypt.cs#L213

I think it's doable to handle RSAES_OAEP certificates, though the Windows PAL might get weird, so we should either fix the places that are stopping it from working correctly (with tests) or we should remove the partial handling of it that we have today. 

/cc @bartonjs

**Comment by vcsjones** [comment]
For what it's worth, this works in .NET Framework but fails in .NET Core; and as far as I can tell it has failed since `EnvelopedCms` was introduced.

**Comment by bartonjs** [comment]
If it works in .NET Framework then it's probably better to just make it work.  (Also, that implies you have a working test  :smile:).

I don't know if it's something that needs to be done for 3.0; but if you (or anyone else) wants to tackle it before we close out 3.0 (and the fix isn't a major rewrite) then I'd be happy to see it fixed :).

**Comment by vcsjones** [comment]
@bartonjs I'll pick this up, I don't think the changes are going to end up being drastic.

Side question: do you have a known list of discrepancies between the Windows PAL and the Managed PAL for EnvelopedCms? I wonder if it is a feasible goal to eventually replace the Win32 PAL with the  managed one if we keep chipping away at the managed one.

**Comment by bartonjs** [comment]
> do you have a known list of discrepancies between the Windows PAL and the Managed PAL for EnvelopedCms?

The big one is that Windows PAL supports (IFC/Classic) Diffie-Hellman for a KeyAgreementRecipientInfo.

I don't know if there's anything else that WindowsPAL does better/differently than ManagedPAL.  Mainly it was "2.0/2.1 are trying to make it super easy to port from .NET Framework, so don't change off of the CryptMsg API given this already worked in 1.0".  (Since SignedCms was not present in 1.0 it was written as just managed).

If you want to argue that maybe the Windows PAL should be reduced to "oh, crap, you care about KeyAgreement with classic Diffie-Hellman", I'm probably willing to entertain that for 3.0. :smile:

**Comment by vcsjones** [comment]
> If you want to argue that maybe the Windows PAL should be reduced to "oh, crap, you care about KeyAgreement with classic Diffie-Hellman", I'm probably willing to entertain that for 3.0.

That was the thought, yes. Doing the work for RSA OAEP has me wondering "why". I'll entertain the idea a bit more and write a new issue.

**Comment by vcsjones** [comment]
Documenting some of my findings here. For .NET Framework 4.8, the following is the behavior for certificates with an RSAES_OAEP SPKI:

1. If the parameters are asn.1 null, an exception is thrown.
2. If the parameters are present and correctly contain RSAES-OAEP-params, those parameters are used for the recipient. e.g. OAEP-SHA256 certificate will result in a KeyTransRecipientInfo using OAEP-SHA256.
3. If the parameters are missing entirely, SHA1 is used.

`#1` is interesting. RFC 5756 more or less says "Stop putting parameters with id-RSAES-OAEP certificates":

>CAs that issue certificates with the id-RSAES-OAEP algorithm
   identifier MUST NOT include parameters in the subjectPublicKeyInfo
   algorithm field.

That seems to imply the expectation that complete and total omission of the parameters is expected. I'm not sure if that is what actually happens from CAs though - I suppose the easiest way is to request a cert from a CA and see what they do. I'll follow up when/if I can try submitting a CSR to digicert and seeing what they do.

**Comment by vcsjones** [comment]
Hm. So this is not trivial with non-Windows X509 PALs. The X509Pal does not handle RSAES_OAEP keys in certificates in a number of places. Just to call out a few:

https://github.com/dotnet/corefx/blob/85c4b4bdae8095c3681d4cd91e00894f26c3baf6/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/CertificateExtensionsCommon.cs#L65-L73

and here:

https://github.com/dotnet/corefx/blob/ef6e6693329981588384e98f463f814f5763c13d/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.OSX/X509Pal.cs#L36

That leaves us being able to add RSAES_OAEP to the Windows PAL, but not the managed one.

I'm mostly inclined now to say that this may not be worth it given the scarcity of these certificates until someone has a very good reason to make it worth plumbing RSAES_OAEP all the way through the X509 stack. Heck it took me an hour just to figure out how to even make one of these certificates correctly. Given that, we have the following options.

1. Remove handling of RSAES_OAEP certificates from all PALs (that does not work right now).
1. Get the Windows PAL working and allow the managed PAL to keep failing. This is possible because the Windows PAL uses certificate handles and doesn't need `X509Certificate2` to handle retrieving the key.
1. Leave things as they are.

@bartonjs

**Comment by bartonjs** [comment]
While (3) sounds nice and easy, (2) might be better (particularly since the cases where it works best in .NET Framework as the least recommended by RFC).

Though, I guess, if .NET Core already doesn't work well/at-all with with `id-RSAES-OAEP` RSA certs, then maybe (1) is better.

(I feel like I saw an RFC discouraging the creation of new keys with `id-RSAES-OAEP` or `id-RSASSA-PSS`, but I'm certainly not finding it right now.  Amusingly, https://tools.ietf.org/html/rfc8017#appendix-A.2.1 arguably undoes RFC 5756 by re-asserting `The parameters field associated with this OID in a value of type AlgorithmIdentifier SHALL have a value of type RSAES-OAEP-params` (doesn't say "when specified" or any other guarded words)).

**Comment by vcsjones** [comment]
>Though, I guess, if .NET Core already doesn't work well/at-all with with id-RSAES-OAEP RSA certs, then maybe (1) is better.

It works well enough to get the Windows PAL for `EnvelopeCms` working but `GetRSA{Public, Private}Key` won't work for these certs. This is more or less the same story with the FFDH certificates - you can instantiate them with `X509Certificate2` but there is no key handling that works for them.

>  (2) might be better (particularly since the cases where it works best in .NET Framework as the least recommended by RFC).

I have those changes already done, so if that seems like an acceptable idea, I can finish it out.

>The parameters field associated with this OID in a value of type AlgorithmIdentifier SHALL have a value of type RSAES-OAEP-params.

🤔
