### ISSUE TITLE
TypeDescriptor.GetConverter, what is the expected result if there is no converter?

### ISSUE THREAD

**Issue by bbarry** [dotnet/corefx#3705]
in 
https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.TypeConverter/tests/TypeDescriptorTests.cs

I notice: `Assert.NotNull(converter);` on line 17. Based on my limited exploratory testing in .NET 4.5 I can't seem to get this method to ever return null. It always seems to at least return an instance of `System.ComponentModel.TypeConverter` (if a better converter cannot be found). Is this test over specified (and somewhere something is missing to ensure a contract on the method) or is there some way to make that method return null (a missing test case)?

**Comment by joshfree** [comment]
@pallavit could you take a look please?

**Comment by pallavit** [comment]
@Tanya-Solyanik could you please help answer this question.

**Comment by Tanya-Solyanik** [comment]
System.ComponentModel.TypeDescriptor.GetConverter method should not return null, it either returns the base class - System.ComponentModel.TypeConverter or throws and exception.

**Comment by pallavit** [comment]
@bbarry I hope that answers your question.

**Comment by bbarry** [comment]
It confirms my expectation. Reading a little harder I notice the cases I was expecting to see there on lines 52, 53, 65 and 66.
