### ISSUE TITLE
Meta: Azure Pipelines on mobile

### ISSUE THREAD

**Issue by filipnavara** [dotnet/corefx#37063]
I figured there's no tracking issue for the Azure Pipelines UI problems on mobile devices. It is listed under [known issues](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/pullrequest-builds.md#known-issues) but that doesn't allow people to track if there's any progress with resolving it.

The experience with Azure Pipelines UI on mobile devices is abysmal. CoreFX has the "Sending tests to Helix" step that prints the mc.dot.net URLs in the log output. On Desktop you can click on them, but it requires CMD+Click (on macOS) or CTRL+Click (on Windows) to go through. On mobile there's no CMD or CTRL key so it doesn't work. To add insult to the injury it doesn't allow normal text selection and copying, so it's not possible to manually copy the URL either.

On Desktop there's an option to download log from individual build step as a .zip file. However it is hidden under icon one has to hover over with mouse. Naturally that's also not possible on mobile. It is however possible to long press on the while space where the icon would normally be and it starts the download.

Effectively the only way to get to the Helix test results is to long press on a white spot on the Azure Pipelines page, download the .zip file with the logs, extract it, open it in a text editor and copy the URL from there back to the browser.

It's 2019 and making a link clickable in a browser sounds like a problem that should have been solved already. 

/cc @safern @karelz @MarcoRossignoli

**Comment by ViktorHofer** [comment]
Fixed.

**Comment by ViktorHofer** [comment]
Sorry I thought was just about the test experience. We enabled Test Explorer integration in AzDO for corefx, so you don't need to click the links anymore and go to MC for most cases. The other issue with the logs was already submitted to the AzDO team, they are aware of it.

There is no immediate action required or possible here from our side, closing.

**Comment by filipnavara** [comment]
How do I get to this "Test Explorer"? Is it the "Tests" tab on the Azure Piplines page (eg. https://dev.azure.com/dnceng/public/_build/results?buildId=177744&view=ms.vss-test-web.build-test-results-tab) ?

**Comment by safern** [comment]
Yes :smile:

**Comment by filipnavara** [comment]
The Test Explorer seems to ignore some of the failures. See https://dev.azure.com/dnceng/public/_build/results?buildId=187372&view=ms.vss-test-web.build-test-results-tab. Two failed builds on Helix step, zero failures on the Tests tab.

**Comment by safern** [comment]
Yes, this is a known issue and it is mostly an issue on the Helix SDK. We're working with the engineering team to fix it: https://github.com/dotnet/arcade/issues/2659

**Comment by filipnavara** [comment]
Thanks. I will watch the other issue :)
