### ISSUE TITLE
Suggestion: Add LINQ method to Zip an IEnumerable with "itself.Skip(1)"

### ISSUE THREAD

**Issue by LWChris** [dotnet/corefx#37095]
I want to have an extension method for `IEnumerable` that makes it easy to create diffs of the elements, by calling a selector for each two adjacent elements.

Essentially, this is `source.Take(source.Count() - 1).Zip(source.Skip(1), SELECTOR)`.

I have already used this extension in various projects when I have a series of values and need to work out the differences. So far I called this extension "ZipLink", because it zips the elements and creates the "linking" element between.

Having a dedicated extension allows for much shorter code that enumerates `source` only once, when otherwise using current LINQ extensions you need two enumerators:

```cs
public IEnumerable<Vector3D> GetPolygonalChain(Point3D[] points) {
  return points.Skip(1).Zip(points, (x1, x0) => x1 - x0);
}

public IEnumerable<Vector3D> GetPolygonalChain(Point3D[] points) {
  return points.ZipLink((x0, x1) => x1 - x0);
}
```

```cs
public IEnumerable<Diff> GetDiffs(IEnumerable<Frame> frames) {
  var fr = frames.ToList(); // Avoid multiple enumeration of "frames"
  return fr.Skip(1).Zip(fr, (next, prev) => Diff.Create(prev, next));
}

public IEnumerable<Diff> GetDiffs(IEnumerable<Frame> frames) {
  return frames.ZipLink(Diff.Create);
}
```

The proposed code would be using a `ZipLinkIterator` like so:

```cs
namespace System.Linq
{
    public static partial class Enumerable
    {
        public static IEnumerable<TResult> ZipLink<T, TResult>(this IEnumerable<T> source, Func<T, T, TResult> resultSelector)
        {
            if (source is null)
            {
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.source);
            }

            if (resultSelector is null)
            {
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.resultSelector);
            }

            return ZipLinkIterator(source, resultSelector);
        }

        private static IEnumerable<TResult> ZipLinkIterator<T, TResult>(IEnumerable<T> source, Func<T, T, TResult> resultSelector)
        {
            using (IEnumerator<T> e = source.GetEnumerator())
            {
                if (e.MoveNext())
                {
                    T last = e.Current;
                    while (e.MoveNext())
                    {
                        yield return resultSelector(last, last = e.Current);
                    }
                }
            }
        }
    }
}
```

**Comment by Clockwork-Muse** [comment]
Side note, can be mocked via something like:
```csharp
var result = source.Aggregate(
	Tuple.Create(new List<int>(), new Queue<double>(), 1),
	(a, current) = >
	{
		var ongoing_result = a.Item1;
		var window_queue = a.Item2;
		var window_start = a.Item3;

		if (window_start == 0 && window_queue.TryDequeue(out double previous))
		{
			ongoing_result.Add(whatever_func(current, previous));
		}
		window_queue.Enqueue(current);

		return Tuple.Create(ongoing_result, window_queue, window_start > 0 ? window_start - 1 : 0);
	},
	a = > a.Item1);
```
(there's a number of variations on this depending on what you want to happen to the "dropped" rows, etc)

In RDBMS terms, this is a "window", and we would probably want to generalize this function as such.  There are [existing libraries](https://github.com/daniel-gustafsson/WindowToLinq) for this sort of thing, of course.

**Comment by LWChris** [comment]
@Clockwork-Muse Yes, it is a window of length 2. This specialized case used for all sorts of derivative calculations could use a "simple" shortcut without the necessity to (1) add a whole library, (2) understand the concept of windowing.

The referenced library's API looks _scary_ for this more common case. And to be honest, even after reading the whole readme and the inline-documentation of the `Window` function - i. e. after 10 minutes of studying the source code of that library - I'm still not sure what to pass to

```cs
IEnumerable<TResult> Window<TSource, TResult>(
  this IEnumerable<TSource> source
  , Func<int, bool> precedingBound
  , Func<int, bool> followingBound
  , Func<TSource, IEnumerable<TSource>, TResult> selector)
```

to get the result I need.

```cs
var src = Enumerable.Range(1, 5);
var res = src.ZipLink((a, b) => a * b);
// res: {2, 6, 12, 20}
```
I _guess_ it is something like

```cs
var res = src.Window(i => i >= 0, i => i <= 1, (_, win) => win.ElementAt(0) * win.ElementAt(1));
```

which feels a bit bloated for the simpler default case.

**Comment by LWChris** [comment]
> I _guess_ it is something like
> 
> ```cs
> var res = src.Window(i => i >= 0, i => i <= 1, (_, win) => win.ElementAt(0) * win.ElementAt(1));
> ```

Meanwhile I think it actually it has to be

```cs
var res = src.Window(i => i >= -1, i => i <= 0, (_, win) => win).Skip(1).Select(win => win.ElementAt(0) * win.ElementAt(1));
```

The windowing function always returns the same amount of windows as original elements by having shorter windows at the borders, which is useful and correct for actual windowing, but a bit annoying for diffing.

**Comment by stephentoub** [comment]
This is a very specific API.  I've no doubt it would be useful in a limited set of scenarios, but I don't think it warrants being added to Enumerable itself, where we want to expose only the broadest and most impactful set of extensions.  It can be achieved with the existing set of LINQ methods, and a dedicated implementation can easily be added as an extension method in any of the myriad of LINQ extension libraries that exist.
