### ISSUE TITLE
Unix Interop Code is platform specific

### ISSUE THREAD

**Issue by migueldeicaza** [dotnet/corefx#371]
In commits like this:

https://github.com/dotnet/corefx/commit/377dde76c5df105a7bab2c0a3002c0d835ff1b07

An attempt has been made to map both structures and constants to C# managed structures.    Unix does not have a binary interface for either the constants or the structures, so the definition is likely already wrong for some platforms and will likely be wrong for ports, even within Linux itself.

While the structures are constants do change from Unix to Unix a little known quirk is that both structures and constants also change in size, layout and the values in Linux itself.

Early versions of Linux chose to emulate the ABI of the host platform, allowing early Linux to easily execute binaries written for the mainstream operating system of the platform.   Linux/Alpha copied OSF/1; Linux/SPARC copied SunOS 4; Linux/MIPS some variation of IRIX and so on.  This is why Linux includes many of these definitions in /usr/include/arch/XXX, because they are different in each platform.

You should do something similar to what Mono.Posix does, which is to have a managed wrapper that talks to a C library that actually performs the native call and marshals the native version to a well-known structure shared with the managed implementation.

**Comment by stephentoub** [comment]
Thanks, @migueldeicaza. Yes, we've already had discussions about this issue internally (and in particular for types like struct stat), and may very well end up with a solution like you propose (other solutions discussed included code generation tools). For now, we went with this approach for expediency, knowing it's limited to a particular distro/version/etc. for now. We have a work for this in our internal bug tracking system.
