### ISSUE TITLE
HttpClient does not works with localhost when proxy is enabled in system settings even with localhost in the list of proxy exclude addresses.

### ISSUE THREAD

**Issue by dma198** [dotnet/corefx#37112]
**Environment:**
- Windows 10. Has proxy configured. localhost in exclude list.
- .Net Core 2.2.101
-  Http server binds to all interfaces (*)
-  Tested url(GET method) normally works in browser
 
Call new HttpClient().GetAsync("http://localhost/api:5500").Wait()

Generates exception: "The server returned an invalid or unrecognized response".

After disabling proxy in system settings all is works.

Guess HttpClient uses proxy regardless that it is localhost.

**Comment by davidsh** [comment]
Could be the same as #33866.

@dma198 Please send us a screenshot of your proxy config.

**Comment by dma198** [comment]
Here you are
-------------------------------

![Screenshot from 2019-04-24 10-25-11](https://user-images.githubusercontent.com/10126106/56628185-6b606200-667b-11e9-9983-51f203e74950.png)

**Comment by davidsh** [comment]
>Here you are

Thank you for the screenshot.  But it doesn't look like it is settings from Internet Explorer proxy settings. Normally the dialog looks something like this:

![image](https://user-images.githubusercontent.com/7684835/56632092-ffdfab80-660c-11e9-90c4-5145fd3a1142.png)

So, what dialog settings are those?

**Comment by dma198** [comment]
That is Windows 10 standard network settings dialog, Proxy tab

**Comment by dma198** [comment]
Old style Control Panel dialog available in Win10, shows same: 

![Screenshot from 2019-04-24 18-15-14](https://user-images.githubusercontent.com/10126106/56652012-e39b4780-66bc-11e9-8836-3c45eec7f399.png)

**Comment by davidsh** [comment]
>Old style Control Panel dialog available in Win10, shows same:

Thanks for posting the IE settings dialog.  They are not the same settings because the IE settings dialog also has checkboxes for "Automatically detect settings" and "Use automatic configuration script".  In your case, the "Automatically detect settings" checkbox is checked.

Can you try unchecking that box and running your repro again?  If your code starts working as expected then this is a duplicate of #33866.

**Comment by dma198** [comment]
Confirm duplicate of 33866
