### ISSUE TITLE
HttpClient slow parallized requests on linux

### ISSUE THREAD

**Issue by mikenorgate** [dotnet/corefx#37114]
I have found that making a bunch of parallel requests to different domains shows a large difference in response times between Windows and Linux. As you can see from the test results below when running on Linux the first run of requests consistently take over a second whereas on Windows the timing is much lower

Here are the full details of the test I am running:

### Environment:
- Windows: Windows 10 Pro 1809. .Net core 2.2
- Linux: Ubuntu 16.04.2 LTS. .Net core 2.2

### Test Results:
**Linux**
```
Run 1
Max: 00:00:01.7611629
Min: 00:00:01.0997532
Avg: 00:00:01.3080000
Run 2
Max: 00:00:00.5364598
Min: 00:00:00.1077417
Avg: 00:00:00.1840000
```
```
Run 1
Max: 00:00:01.6518448
Min: 00:00:01.0683208
Avg: 00:00:01.2680000
Run 2
Max: 00:00:00.5278526
Min: 00:00:00.1088224
Avg: 00:00:00.1820000
```
```
Run 1
Max: 00:00:01.6706209
Min: 00:00:01.0816414
Avg: 00:00:01.2540000
Run 2
Max: 00:00:00.5382613
Min: 00:00:00.1050479
Avg: 00:00:00.1880000
```

**Windows:**
```
Run 1
Max: 00:00:00.7903048
Min: 00:00:00.2537194
Avg: 00:00:00.4020000
Run 2
Max: 00:00:00.5417385
Min: 00:00:00.1077183
Avg: 00:00:00.1770000
```
```
Run 1
Max: 00:00:00.7238954
Min: 00:00:00.2259200
Avg: 00:00:00.3750000
Run 2
Max: 00:00:00.5352573
Min: 00:00:00.1058812
Avg: 00:00:00.2670000
```
```
Run 1
Max: 00:00:00.7443581
Min: 00:00:00.2271784
Avg: 00:00:00.3820000
Run 2
Max: 00:00:00.5431293
Min: 00:00:00.1050701
Avg: 00:00:00.2390000
```

### Test Code:
```c#
class Program
    {
        static void Main(string[] args)
        {
            var client = new HttpClient();

            var domains = new string[]
            {
                "http://example.com",
                "http://example.net",
                "http://example.org",
                "http://example.edu",
                "http://iana.org",
                "https://google.com",
            };

            //Adding this in removes the spike in times
            //foreach (var domain in domains)
            //{
            //    client.GetAsync(domain).Wait();
            //}

            Console.WriteLine("Run 1");
            RunTest(client, domains);
            Console.WriteLine("Run 2");
            RunTest(client, domains);
        }

        private static void RunTest(HttpClient client, string[] domains)
        {
            var times = new TimeSpan[100];
            var tasks = Enumerable.Range(0, times.Length)
                .Select(async i =>
                {
                    var s = Stopwatch.StartNew();
                    var response = await client.GetAsync(domains[i % domains.Length]);
                    times[i] = s.Elapsed;
                });

            Task.WaitAll(tasks.ToArray());


            Console.WriteLine("Max: " + times.Max());
            Console.WriteLine("Min: " + times.Min());
            Console.WriteLine("Avg: " + TimeSpan.FromMilliseconds(times.Average(x=>x.TotalMilliseconds)));
        }
    }
```

**Comment by karelz** [comment]
Can you please turn it into BenchmarkDotNet perf test? That is much more reliable and provides interesting statistics.
The key question is if this is reproducible in other environments - making sure that the DNS/proxy setup and network conditions are the same.
Are you able to test the same on Azure VMs? (they should have similar network conditions)

**Comment by mikenorgate** [comment]
I'm not quite sure of the best way to change this into a BenchmarkDotNet test as I can't see away to make multiple requests simultaneously and get the time for each request, all I can do is get the time it takes to get through all the requests

I have tested on the following Azure VMs and *wasn't* able to reproduce the same results:

Windows:
- Location: EastUS
- SKU: Standard DS2 v2  
- OS: Windows Server 2019 Datacenter
- Dotnet core: 2.2.4

Linux:
- Location: EastUS
- SKU: Standard DS2 v2  
- OS: Ubuntu Server 18.04 LTS
- Dotnet core: 2.2.4

It must be somehow related to my local linux setup. I'll close this issue as doesn't seem like an actual issue
