### ISSUE TITLE
The default encoding is not correct

### ISSUE THREAD

**Issue by chucklu** [dotnet/corefx#37111]
I try to get the default encoding in win10 by powershell 6.1 with the following command
```powershell
[System.Text.Encoding]::Default.EncodingName
```
What I got is Unicode (UTF-8), however the actually default encoding should be Chinese Simplified (GB2312).

You can check more detail info in https://github.com/PowerShell/PowerShell/issues/9450

**Comment by jkotas** [comment]
This is documented to always return UTF-8 for .NET Core:

https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.default?view=netcore-2.2

**Comment by chucklu** [comment]
Is it possible that I can read the operation system default encoding from registry or some other way?

**Comment by jkotas** [comment]
- Add reference to `System.Text.Encoding.CodePages` package from .NET Core Windows Compatibility Pack
- `CodePagesEncodingProvider.Instance.GetEncoding(0).EncodingName` will be the default encoding name

**Comment by chucklu** [comment]
@jkotas  Thanks
