### ISSUE TITLE
Microsoft.Bcl.Json.Sources (change to binary distribution)

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#37126]
Tracking issue for replacing the Microsoft.Bcl.Json.Sources package with a proper netstandard20 binary package for preview 6

/cc @joperezr @terrajobst @rynowak @KrzysztofCwalina @Petermarcu

**Comment by ahsonkhan** [comment]
Related/duplicate issue https://github.com/dotnet/corefx/issues/37043.
