### ISSUE TITLE
Namespaces like System.Web.Services are pending for port in .net Core

### ISSUE THREAD

**Issue by gsmental** [dotnet/corefx#37135]
every time when we try to port our existing application,  we faces only these namesspaces which can not port into .net Core. technically these all are WebService (asmx) based libraries. i hope these will be also port into .net core

System.Web.Services.Protocols.HttpWebClientProtocol
System.Web.Services.WebServiceBindingAttribute
System.Web.Services.Protocols.WebClientProtocol
System.Web.Services.Protocols.SoapHeader
System.Web.Services.Protocols.SoapHeaderAttribute
System.Web.Services.Protocols.SoapDocumentMethodAttribute
System.Web.Services.Protocols.SoapHttpClientProtocol
System.Web.Services.Protocols.InvokeCompletedEventArgs
System.Web.Services.Protocols.SoapParameterStyle
System.Web.Services.Description.SoapBindingUse

**Comment by karelz** [comment]
System.Web is not planned to be ported to .NET Core - check out ASP.NET repos (e.g. https://github.com/aspnet/AspNetCore) for more details.

**Comment by gsmental** [comment]
i am agree with you. but problem is that most of Winform  applications are working with Asmx (Webservices),  so i am  not talking about to port all asp.net web, just Web services and related classes can be converted.

**Comment by karelz** [comment]
Still worth asking on ASP.NET side as I expect they own this part.
cc @merriemcgaw if she has opinion ...

**Comment by Eilon** [comment]
A fair question, but there are no plans at this time to port the functionality of these namespaces to ASP.NET Core.
