### ISSUE TITLE
Proposal: Extension method to get value or default with creation function for Dictionary

### ISSUE THREAD

**Issue by datvm** [dotnet/corefx#37149]
From #3482, currently in .NET Core 3.0 we have:

`public static TValue GetValueOrDefault<TKey, TValue>(this IReadOnlyDictionary<TKey, TValue> dictionary, TKey key, TValue defaultValue);`

However, `defaultValue` is a value and therefore not useful in case of "Get or Create" and **may** cause new developers think `defaultValue` expression is only evaluated when key is not found.

# Rationale and Usage

Newcomers may think `defaultValue` is only evaluated when key is not present (which is not correct). My proposal is to prevent it:

```
// createObjectWithSideEffect("key") is evaluated even if key exist
var foo = dict.GetValueOrDefault("key", CreateObjectWithSideEffect("key"))
```

Correct usage is a bit cumbersome, and cannot be used for non-nullable types:

```cs
var foo = dict.GetValueOrDefault("key") ?? CreateObjectWithSideEffect("key");
```

Therefore I suggest an API that defaultValue only evaluate when `key` is not present, and usage should be:

```cs
var foo = dict.GetValueOrDefault("key", CreateObjectWithSideEffect);
```

For example:

```cs
var foo = dict.GetValueOrDefault("key", key =>
{
    var result = new Foo();

    // Assign values
    // ...
    
    // Maybe add it back to the dictionary, but I suggest adding a GetOrCreate extension method instead
    dict[key] = result;

    return result;
});
```

# Proposed API

```cs
public static class CollectionExtensions
{
     public static TValue GetValueOrDefault<TKey, TValue>(this IDictionary<TKey, TValue> dictionary, 
     TKey key, Func<TKey, TValue> defaultValue);
     public static TValue GetValueOrDefault<TKey, TValue>(this IReadOnlyDictionary<TKey, TValue> 
     dictionary, TKey key, Func<TKey, TValue> defaultValue);
}
```

**Comment by safern** [comment]
@datvm thanks for your suggestion. While it makes sense, we would need a formal proposal with rationale, more usage scenarios and open questions if any, here is an example: https://github.com/dotnet/corefx/issues/35938

Please ping me whenever updated.

**Comment by datvm** [comment]
Thanks, I have updated the comment. Sorry this is the first time I post a proposal, will try better next time.

**Comment by safern** [comment]
No worries, @datvm, thanks for the proposal. I've marked it as ready for review, and also added the extension method for `IReadOnlyDictionary`.

**Comment by GrabYourPitchforks** [comment]
Feedback: This would be a compile-time breaking change because there would be an overload resolution conflict if the `null` literal is provided as the last parameter to the extension method.
