### ISSUE TITLE
what "ReferenceFromRuntime" means?

### ISSUE THREAD

**Issue by newpost** [dotnet/corefx#37171]
In System.Runtime.csproj :`<Project>
  <ItemGroup>
    <ReferenceFromRuntime Include="System.Private.CoreLib" />
  </ItemGroup>
</Project>`

https://github.com/dotnet/corefx/blob/4e1b64e1ab06202e9aa451a0b320b7fd4ed11519/src/System.Runtime/src/System.Runtime.csproj#L31

**Comment by joperezr** [comment]
Hello @newpost. The way we build our implementation assemblies (which this System.Runtime.csproj is one of them) is by adding references to a targeting pack from the specific framework that the implementation is targetting. There are a few cases where we don't want to compile against this targeting pack, and instead compile against runtime assemblies directly, so for this we use the Item called `ReferenceFromRuntime`.

This item is very specific to our build infrastructure, and will only take effect to projects in our repo, so it won't be something that you would do when building .NET Core applications.

I'm closing this issue as the question was answered, but feel free to reopen if you have any follow up questions.
