### ISSUE TITLE
All corefx PRs currently failing Packaging All Configurations leg

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#37185]
Error during restore:
```
D:\a\1\s\.dotnet\sdk\3.0.100-preview3-010431\NuGet.targets(119,5): error : Failed to retrieve information about 'Microsoft.TargetingPack.NETFramework.v4.6.2' from remote source 'https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.targetingpack.netframework.v4.6.2/index.json'. [D:\a\1\s\external\netfx\netfx.depproj]
D:\a\1\s\.dotnet\sdk\3.0.100-preview3-010431\NuGet.targets(119,5): error :   A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. [D:\a\1\s\external\netfx\netfx.depproj]
```

I'm not sure who should investigate, whether it's a blip that'll automatically fix itself soon, etc.
cc: @dotnet/dnceng

**Comment by MattGal** [comment]
@stephentoub I'm taking a look, but sounds like a storage-account blip to me too.

**Comment by MattGal** [comment]
- Storage account shows now health alerts in Azure portal
- Subsequent CI builds are getting past it: https://dev.azure.com/dnceng/public/_build/results?buildId=169471

I'm guessing intermittent storage account blip.

**Comment by stephentoub** [comment]
Thanks for looking, @MattGal.

**Comment by stephentoub** [comment]
@SteveCarrollMSFT, just FYI as an example of intermittent effects impacting CI.

**Comment by MattGal** [comment]
@stephentoub  another interesting point Matt M pointed out in this build: https://dev.azure.com/dnceng/public/_build/results?buildId=169535
... there seem to be unusual network problems on the AzDO hosted Ubuntu build pools going on.  I'll start a thread with the CI experts to see if it's known.
