### ISSUE TITLE
Investigate feasibility of supporting NegotiateStream channel bindings on non-Windows platforms

### ISSUE THREAD

**Issue by vijaykota** [dotnet/corefx#3718]
The gss_init_sec_context and gss_accept_sec_context APIs take channel binding as input. This support needs to be understood. This would be useful for NegotiateStream.Authenticate\* APIs

**Comment by vijaykota** [comment]
Changing milestone since NegotiateStream xplat is planned for RTM

**Comment by vijaykota** [comment]
I had opened the issue in the context of NegotiateStream. AuthenticateAsClient uses a ChannelBinding parameter and AuthenitcateAsServer uses ExtendedProtectionPolicy.CustomChannelBinding. For v1, only WCF requires NegotiateStream and neither of these are used in WCF code. Hence changing the milestone to Future.
#3609 is linked to this and closed but that is specifically asking about GSS-NTLM and not channel bindings.

**Comment by CIPop** [comment]
@karelz I'm marking this for netstandard2.0 consideration and final decision.
The behavior is supported in Windows but not on non-Windows implementations.

**Comment by karelz** [comment]
@Priya91 can you please follow up with WCF team (@mconnew @zhenlan) to find out if this is truly useful for them?

If not, it looks like we can close it. Once we get more customer feedback/need, we can reconsider.

**Comment by Priya91** [comment]
Synced with @mconnew  offline, WCF doesn't use channelbinding with NegotiateStream, they use channelbinding on httpclient. We can close this.

**Comment by karelz** [comment]
Thanks @Priya91 for closing on it!
