### ISSUE TITLE
Out-of-band System.Data.SqlClient depends on inbox native shims

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#37183]
SqlClient out-of-band netstandard packages depend on .NET Core native shims:

https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System.Data.SqlClient.csproj#L481-L483

The native shims are not compatible between .NET Core versions, e.g. ImportPrincipalName got changed to ImportTargetName in dotnet/corefx#35383.

This leads to failures when the netstandard SqlClient package is used on a different version of .NET Core than what it was build on, e.g. https://github.com/dotnet/corert/issues/7353

**Comment by AfsanehR** [comment]
Thanks @jkotas . I will take a look at this.

**Comment by davidsh** [comment]
I am working on a PR to revert some of those changes in .NET Core 3.0 branch (master).  This will allow SqlClient OOB to work on either .NET Core 2.x or .NET Core 3.x runtimes.
