### ISSUE TITLE
StreamReader detectEncodingFromByteOrderMarks needs tests

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#37190]
We don't check that the detection algorithm works as expected. At the very least we should check that we set the encoding correctly based on the data stream. It would also be good to actually read data out in the different encodings.

StreamReader tests are in System.IO.

**Comment by davidkaya** [comment]
I will take it if possible :)

**Comment by JeremyKuhne** [comment]
@jimdemis added some with #36959, these are a good addition as well.
