### ISSUE TITLE
Test failure: ProcessStart_UseShellExecute_OnUnix_SuccessWhenProgramInstalled(isFolder: False)

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/corefx#37198]
The test is failing on Linux with:

> Assert.Equal() Failure
          ↓ (pos 0)
Expected: xdg-open
Actual:   sh
          ↑ (pos 0)

There are a few related failures, such as `ProcessStart_OpenFileOnLinux_UsesSpecifiedProgramUsingArgumentList(programToOpenWith: \"vi\")`. These appear to have been introduced by https://github.com/dotnet/corefx/commit/8b515adcd4ea0b8233f018f9e87ef946ce0e7c42#diff-c2151a182d9032ef4525c69b3569d024 & https://github.com/dotnet/corefx/commit/4214b09864bea0416f17727ffa39a55d950035d1#diff-c2151a182d9032ef4525c69b3569d024. The first change is in release/3.0, so we're seeing the failures in `preview5` as well. 

CC @stephentoub @tmds

**Comment by danmosemsft** [comment]
This should be fixed by https://github.com/dotnet/corefx/pull/37144.

**Comment by wtgodbe** [comment]
@danmosemsft that PR actually reintroduced these test failures. The timeline goes:

https://github.com/dotnet/corefx/pull/36913 - caused the intial set of failures (this is the current state in `release/3.0`)
https://github.com/dotnet/corefx/pull/37113 - reverted the previous change, fixed the test failures
https://github.com/dotnet/corefx/pull/37144 - reintroduced the test failures

**Comment by danmosemsft** [comment]
Oh... @tmds

**Comment by wtgodbe** [comment]
These are outerloop tests, which is why we missed them in CI. You can see the failures from this PR: https://github.com/dotnet/corefx/pull/37197

**Comment by tmds** [comment]
I need to investigate further, but on first sight, these may be things we need to update in the tests:

- LongProcessNamesAreSupported is failing on Alpine. The test itself may be incompatible with Alpine. busybox figures out what the process should do based on the name, and the test is renaming to something busybox doesn't know.
- ProcessStart_UseShellExecute_OnUnix_SuccessWhenProgramInstalled is failing on a number of distros but not on all. It may have to do with the way xdg-open works.

**Comment by stephentoub** [comment]
I'm disabling this test temporarily, as it's causing all outerloop linux runs to fail.

**Comment by stephentoub** [comment]
I'm also disabling ProcessTests.LongProcessNamesAreSupported against this issue.

**Comment by stephentoub** [comment]
And ProcessTests.ProcessStart_OpenFileOnLinux_UsesSpecifiedProgramUsingArgumentList

**Comment by tmds** [comment]
@stephentoub we need some input here: https://github.com/dotnet/corefx/pull/37294#discussion_r280190584
