### ISSUE TITLE
How to reads the SO_ORIGINAL_DST socket option?

### ISSUE THREAD

**Issue by TuoNiao** [dotnet/corefx#37215]
How to reads the SO_ORIGINAL_DST socket option when a connection has been redirected by an iptables REDIRECT target？

**Comment by davidsh** [comment]
@wfurt @tmds

**Comment by wfurt** [comment]
don't think there is good way right now. 
You can wait for https://github.com/dotnet/corefx/issues/37122 or use workaround described there.
