### ISSUE TITLE
Test Failure: System.Diagnostics.Tests.ProcessTests/LongProcessNamesAreSupported

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#37211]
Test **System.Diagnostics.Tests.ProcessTests/LongProcessNamesAreSupported** has failed.

Message :
```
Assert.Contains() Failure
Not found: (filter expression)
In value:  Process[] [System.Diagnostics.Process (sh), System.Diagnostics.Process (sh), System.Diagnostics.Process (bash), System.Diagnostics.Process (dotnet)]
```
Stack Trace :
```
at System.Diagnostics.Tests.ProcessTests.LongProcessNamesAreSupported() in /__w/1/s/src/System.Diagnostics.Process/tests/ProcessTests.cs:line 1883
```

Details:
https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190425.7/workItem/System.Diagnostics.Process.Tests/analysis/xunit/System.Diagnostics.Tests.ProcessTests~2FLongProcessNamesAreSupported

**Comment by wtgodbe** [comment]
Closing as part of https://github.com/dotnet/corefx/issues/37198
