### ISSUE TITLE
BitmapData SetPixel()

### ISSUE THREAD

**Issue by informatorius** [dotnet/corefx#37228]
System.Drawing.Bitmap class has a SetPixel() method but it is slow for setting many pixels because each call locks in bitmap in the kernel. That is why Bitmap also has a LockBits() method which locks the bitmap and returns a System.Drawing.Imaging.BitmapData for direct manipulation. 

The problem is this BitmapData class has no easy method for SetPixel() but you need to calculate with IntPtr and stride values. 

I wish extension methods in System.Drawing.Imaging for BitmapData which allow fast SetPixel() for many pixels

**Comment by danmosemsft** [comment]
@informatorius to propose new API please edit the top post to match the API review process guidelines
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md

Note that System.Drawing is not necessarily a good choice for new development. We do not have plans to add features to it.

**Comment by gfoidl** [comment]
@informatorius have a look at https://github.com/LuizZak/FastBitmap

**Comment by informatorius** [comment]
thx
