### ISSUE TITLE
BigEndianUTF32 in Encoding class is private

### ISSUE THREAD

**Issue by davidkaya** [dotnet/corefx#37221]
I have noticed (during #37190) that `BigEndianUTF32` in `Encoding` is private for some reason. Other helpers are public.

https://github.com/dotnet/corefx/blob/09e2417cd0505df4558535651efb1bbcffdf0c59/src/Common/src/CoreLib/System/Text/Encoding.cs#L1146-L1156

Is that on purpose?

/cc: @JeremyKuhne

**Comment by stephentoub** [comment]
> Is that on purpose?

It's on purpose in that there's never been a strong expressed need to expose it.  It exists in order to cache it for use in Encoding.GetEncoding.

**Comment by joshfree** [comment]
Closing out the issue as this is intentional in the code.  @davidkaya feel free to reactivate the issue with more comments if I misunderstood the request.  Thanks
