### ISSUE TITLE
Unable to load a resource from a .net dll

### ISSUE THREAD

**Issue by cadilhac** [dotnet/corefx#37226]
As with .net framework, I'm trying to load a resource. For instance:

```
ResourceManager systemRM = new ResourceManager("System", Assembly.GetAssembly(typeof(CategoryAttribute)));
var str = systemRM.GetString("PropertyCategoryDefault", System.Globalization.CultureInfo.CurrentUICulture);
```

I get a MissingManifestResourceException:

> "Could not find any resources appropriate for the specified culture or the neutral culture. Make sure "System.resources" was correctly embedded or linked into assembly "System.ComponentModel.Primitives" at compile time, or that all the satellite assemblies required are loadable and fully signed."

systemRM.GetResourceSet(CultureInfo.InvariantCulture, true, false) also returns null.

**Comment by danmosemsft** [comment]
@cadilhac can you please create a minimal repro case? Eg., a github repo that we can fork and steps to build and publish the code. Something without any unnecessary code or steps - hello world style. The above is not sufficient to help, unfortunately.

**Comment by tarekgh** [comment]
@cadilhac This is expected because you don't have a resources for Invariant culture. What exactly you are trying to do here? Invariant culture is like any other culture, if you don't have any resources built for the requested culture, then you'll get the missing resources.

If you want to use neutral resources, please follow https://docs.microsoft.com/en-us/dotnet/api/system.resources.neutralresourceslanguageattribute?view=netframework-4.8

**Comment by cadilhac** [comment]
> @cadilhac This is expected because you don't have a resources for Invariant culture. What exactly you are trying to do here? Invariant culture is like any other culture, if you don't have any resources built for the requested culture, then you'll get the missing resources.
> 
> If you want to use neutral resources, please follow https://docs.microsoft.com/en-us/dotnet/api/system.resources.neutralresourceslanguageattribute?view=netframework-4.8

I'm sorry, bad copy/paste. I'm not using the invariant culture. I updated my original post.

**Comment by tarekgh** [comment]
@cadilhac  Could you please share a small repro?

What is your CurrentUICulture? And does your app has resources for such culture?

and what happen when you call 

```C#
systemRM.GetResourceSet(CultureInfo.InvariantCulture, true, true);
```

Note the last parameter is true.

by the way, if you call ResourceManager.GetString and not passing any culture, the resource manager will just use the CurrentUICulture. It'll be good if you can tell what is the output of the following too.

```C#
var str = systemRM.GetString("PropertyCategoryDefault");
```

Last, please double check your resource really include PropertyCategoryDefault entry.

**Comment by cadilhac** [comment]
You didn't get it. This is not my resources. These are resources in a .net dll (System.ComponentModel.Primitives.dll in this case). Anyway, I was able to fix the issue by providing another basename:

var systemRM = new ResourceManager("FxResources.System.ComponentModel.Primitives.SR", Assembly.GetAssembly(typeof(CategoryAttribute)));

So in conclusion, there is a breaking change here. And I got another case where it happens too. I had to replace the basename "System.Windows.Forms" by "System.SR". Will it stay like this? Was it expected?

**Comment by jkotas** [comment]
Resource strings of framework assemblies are internal implementation detail. They are not guaranteed to be stay the same between versions.

> Will it stay like this? Was it expected?

It is not guaranteed to stay like this. We may change it in next version and it won't be considered a breaking change.

**Comment by tarekgh** [comment]
@jkotas is right. You cannot assume the resources inside the framework not going to change. Why you are doing that in the first place? why you don't carry your own resources to have reliable app?

**Comment by cadilhac** [comment]
I sell a WinForms component ([Smart PropertyGrid](http://visualhint.com/propertygrid)) and I use resources from .Net to avoid replicating some strings (why bother with that when .Net already has translated strings in many languages) which also allows to be consistent with the MS PropertyGrid. I also use reflection to access some internal components of .Net dlls. This is necessary to create a very powerful abd flexible component.

**Comment by tarekgh** [comment]
Maybe you can probe first to look if the resources exist and then fallback to something else. You can use [Assembly.GetManifestResourceNames](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.getmanifestresourcenames?view=netframework-4.8) to enumerate the existing resource sets in the assembly.
