### ISSUE TITLE
Process.StartTime Access is Denied (.Net Core)

### ISSUE THREAD

**Issue by tonyatl** [dotnet/corefx#37230]
Is it possible to configure security on an asp.net core 2.2 webapi service so that Process.StartTime can be authorized for access? Documentation alludes to this by mentioning link demands and full-trust, but i don't understand the mechanics to implement them - and examples are very rare to non-existent.

Currently i get Access is denied. I do not want to correlate users on each process - ie use the same one. this is not reasonable or feasible for my environment.

i have detailed the issue here: https://stackoverflow.com/questions/55871898/process-starttime-access-is-denied-net-core

**Comment by danmosemsft** [comment]
Hello @tonyatl . Your question seems to be about .NET Framework. This is the repo for .NET Core. You'll want to post your question/feedback here instead: https://developercommunity.visualstudio.com/spaces/61/index.html

Looks like you may have your answer in stackoverflow anyway.
