### ISSUE TITLE
HTTP2: Provide way to access RST_STREAM reason

### ISSUE THREAD

**Issue by JamesNK** [dotnet/corefx#37240]
HttpClient does not provide a way to access the RST_STREAM reason returned by the server. The RST_STREAM reason can sometimes be used to communicate status in RPC scenarios: https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#errors

Being able to access the reason would allow the .NET gRPC client to provide a more specific error to the user.

This feature would be useful, but not blocking, to gRPC.

**Comment by stephentoub** [comment]
PR https://github.com/dotnet/corefx/pull/37223 ensures that the error code from both RST_STREAM and GOAWAY frames is propagated as part of the error message surfaced to the HttpResponseMessage/Stream, do the failure reason is at least communicated. #26477 tracks exposing such error information (for both HTTP/1.1 and HTTP/2) in a strongly-typed fashion, but that's unlikely to happen for 3.0. I'm going to close this issue against that. Thanks.
