### ISSUE TITLE
Proposal: MemoryStream-like Stream class, which can use Memory<T> instead of byte[] as a backing store

### ISSUE THREAD

**Issue by torgabor** [dotnet/corefx#37255]
I think it would be great to have an API to make it possible to interface `Memory`-based API-s with `Stream`-based ones, and enable a lot of opportunities for low-overhead interop with native code. It would also allow us to leverage the ` MemoryPool<T>` for termporary buffer creation.
I propose, that either `MemoryStream` should be extended so that it can operate on `Memory<T> `or an entirely new class should be created.
Unfortunately, `MemoryStream` has the ability to expose the underlying byte[] array,  so I would lean towards implementing a brand-new class.

**Comment by stephentoub** [comment]
Thanks. Dup of #21380 and https://github.com/dotnet/corefx/issues/22404.
