### ISSUE TITLE
HttpRequestMessage multiple-send checking should be done in HttpMessageInvoker

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#3725]
From https://github.com/dotnet/corefx/issues/3268#issuecomment-146564360

> it seems that we made a mistake when we did this. We should actually be checking for this in the HttpMessageInvoker base class SendAsync (which is public). Most people just use HttpClient to invoke the handlers. But simple scenarios can use the HttpMessageInvoker as well. That class was created as way to invoke the handler's SendAsync() method without a lot of overhead of HttpClient. The actual handler SendAsync() method is protected and can't be invoked directly. But HttpMessageInvoker is able to call that method being the handler's method is actually marked protected internal and not just protected.

**Comment by davidsh** [comment]
We've decided not to change this behavior based on app-compat with .NET Framework, etc.
