### ISSUE TITLE
Add JsonException and make JsonReaderException internal

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#37272]
Proposal to add a single exception class called `JsonException` and make `JsonReaderException` internal instead of public.

The new exception contains a "Path" property used by the serializer, and the `LineNumber` and `BytePositionInLine` become nullable since they are not always set.

The original proposal was to add two new exception classes, but during review there was not enough justification for three classes. Keeping `JsonReaderException` is necessary since the serializer itself has a dependency to catch exceptions thrown from the reader in order to re-throw.

```cs
namespace System.Text.Json
{
    public class JsonException : System.Exception
    {
        public JsonException (string message, string path, long? lineNumber, long? bytePositionInLine, Exception innerException);
        public JsonException (string message, string path, long? lineNumber, long? bytePositionInLine);
        protected JsonException(SerializationInfo info, StreamingContext context);
        public long? BytePositionInLine { get; }
        public long? LineNumber { get; }
        public string Path { get; }
        public override void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    }
}
```

**Comment by steveharter** [comment]
cc @ahsonkhan @rynowak

**Comment by ahsonkhan** [comment]
> the existing `JsonReaderException` will now derive from that instead of `System.Exception`.

Would the JsonWriter continue to throw the InvalidOperationException/ArgumentException/etc.?

**Comment by rynowak** [comment]
For the reader/writer I think it depends case by case. 

Misuse of APIs should result in InvalidOperation/Argument exceptions

Incorrect JSON should result in JsonExceptions

**Comment by rynowak** [comment]
For the reader/writer I think it depends case by case. 

Misuse of APIs should result in InvalidOperation/Argument exceptions

Incorrect JSON should result in JsonExceptions

**Comment by steveharter** [comment]
This is not proposing changing any exception semantics except:
- The deserializer now always throws `JsonSerializationException` on invalid JSON (instead of `JsonReaderException`) - even when `JsonReaderException` is originally thrown from the reader.
- The serializer will throw `JsonSerializationException` (currently the only exception case is MaxDepth exceeded).

Otherwise as @rynowak states yes misuse of APIs will continue to result in InvalidOperation etc. One non-obvious case is the deserializer throws InvalidOperation due to "duplicate" property names when using the case-insensitive setting or [JsonProperty(name)] - this is raised before inspecting any JSON.

**Comment by rynowak** [comment]
API proposal looks like what I would expect.

**Comment by steveharter** [comment]
Updated to make `JsonReaderException` internal.

**Comment by wli3** [comment]
This breaking change blocked our build. https://github.com/dotnet/cli/pull/11392. And I am surprised there is no concrete decision which Exception is the replacement (JsonSerializationException is not exposed). But the type is removed first.

From the conversion i will replace all JsonReaderException with JsonException. Please file bug on CLI if there is further decision.

**Comment by steveharter** [comment]
Closing as API approved
