### ISSUE TITLE
AllConfigurations and code coverage leg should use helix IncludeDotNetCli feature

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#37295]
https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Helix/Sdk/Readme.md#all-possible-options

Currently we are packaging the dotnet cli ourselves. Instead we should use the pre-built feature in the Helix sdk by specifying `IncludeDotNetCli`, `DotNetCliVersion` and `DotNetCliPackageType`. That will download the dotnet cli and update PATH.

**Comment by safern** [comment]
Fixed for AllConfigurations in: https://github.com/dotnet/corefx/pull/42496 -- since we don't yet have code coverage running in helix we can close this.
