### ISSUE TITLE
WinHttpHandler MaxConnectionsPerServer default value

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#3729]
Currently:

```
C# Assert.Equal(Int32.MaxValue, handler.MaxConnectionsPerServer);
```

Opening this issue to discuss if this is the correct behavior given the RFC recommendation of a max of 2 connections/server and browser current settings of about 6-10 connections/server.

Throwing in a few articles about this:
http://stackoverflow.com/questions/985431/max-parallel-http-connections-in-a-browser
http://www.stevesouders.com/blog/2008/03/20/roundup-on-parallel-connections/

My proposal is to switch this to a smaller number, maybe something that's similar to what most modern browsers do today.

**Comment by davidsh** [comment]
@SidharthNabar PTAL

**Comment by SidharthNabar** [comment]
My understanding is that a high number of concurrent connections is required for server environment (ASP.NET 5 scenarios). The linked articles are about the browser scenario which is a very different user scenario. 

@Tratcher @davidfowl - thoughts?

**Comment by Tratcher** [comment]
Yes, the browser recommendation is not appropriate to this scenario.  That said, how is this implemented in WinHttpHandler? Is it done locally or is it just a flag passed down to WinHttp?

We've learned over the years that managing connections with only a numerical limit is sub-optimal. Ideally the connection pool would grow more like the threadpool, allocating new connections only if queued for a minimum amount of time.  Also, MaxValue is worse than 2, as you loose more time and resources managing the connections than you would just waiting in the queue.  20-50 should be a sufficient default.

**Comment by davidsh** [comment]
>Is it done locally or is it just a flag passed down to WinHttp?

We set the WInHttpOption, `WINHTTP_OPTION_MAX_CONNS_PER_SERVER`, on the request handle to a value of Int.MaxValue as the default.  A developer can change the property MaxConnectionsPerServer in WinHttpHandler to change that default.

See: https://github.com/dotnet/corefx/blob/master/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs

**Comment by Tratcher** [comment]
Ah, figures. Does it hold up under stress with lots of concurrent requests?

**Comment by CIPop** [comment]
> Ah, figures. Does it hold up under stress with lots of concurrent requests?

I haven't seen any issues in the tests that I ran. I'll tentatively close this. We can reopen if necessary.
