### ISSUE TITLE
BitVector32 should implement IEquatable<T>

### ISSUE THREAD

**Issue by justinvp** [dotnet/corefx#373]
`BitVector32` and `BitVector32.Section` are both structs that override `Equals` and `GetHashCode`. `BitVector32.Section` even has an `Equals(Section)` overload. Should these value types implement `IEquatable<T>` per the design guidelines?

`BitVector32` is in `System.Collections.Specialized`. I understand that most of the collections in `System.Collections.Specialized` are considered *legacy*, are here mainly for backwards compatibility, and therefore shouldn't be invested in per @davkean's [comments](https://github.com/dotnet/corefx/issues/370#issuecomment-69140116). However, I'm not sure I'd necessarily consider `BitVector32` *legacy* as it does appear to be useful on its own and isn't replaced by anything else (that I'm aware of).

## Proposed API

```c#
// Previously didn't implement IEquatable<T>
public struct BitVector32 : IEquatable<BitVector32>
{
    // Existing members
    public override bool Equals(object o);
    public override int GetHashCode();

    // Proposed members
    public bool Equals(BitVector32 other);
    public static bool operator ==(BitVector32 left, BitVector32 right);
    public static bool operator !=(BitVector32 left, BitVector32 right);

    ...

    // Previously didn't implement IEquatable<T>
    public struct Section : IEquatable<Section>
    {
        // Existing members
        public override bool Equals(object o);
        public bool Equals(Section obj);
        public static bool operator ==(Section a, Section b);
        public static bool operator !=(Section a, Section b);
        public override int GetHashCode();

        // No new members required

        ...
    }
}
```

**Comment by justinvp** [comment]
Here's what the change would look like: https://github.com/justinvp/corefx/commit/0b47bb0b52941edd03ddc75add31530c883f4dbc

**Comment by davkean** [comment]
Agreed. These look fine to me.

**Comment by mikedn** [comment]
I wouldn't call BitVector32 useful. Most people simply use a [Flags] enum, BitVector32 is simply too much [hassle](http://referencesource.microsoft.com/#System/compmod/system/componentmodel/MaskedTextProvider.cs,122). It's unlikely that many people will benefit from this change, especially in the context of .NET Core.

**Comment by justinvp** [comment]
*Useful* may be too strong, but `BitVector32` certainly isn't completely in the *legacy* bucket like `StringCollection` (replaced by `List<string>`).

I agree that these changes are low priority and that not a lot of people will benefit directly. However, there is something to be said for following best practices when possible. These types should implement `IEquatable<T>` per the design guidelines. My guess as to why they do not: `IEquatable<T>` was added to .NET after `BitVector32`, and nobody got around to (perhaps deliberately due to low priority) or forgot to update `BitVector32`. If `BitVector32` is being carried forward into .NET Core, it should follow the design guidelines, if possible. In this case, the changes are trivial and non-intrusive.

**Comment by tumey** [comment]
Ready

**Comment by terrajobst** [comment]
[We've reviewed this proposal](https://github.com/dotnet/apireviews/blob/master/2015-01-14-misc/README.md#373-bitvector32-should-implement-iequatablet) and think it's not ready yet. The API review board needs to follow-up to answer the question whether we consider `BitVector32` a legacy API or not.

**Comment by terrajobst** [comment]
We've made the decision to treat `BitVector32` the same way we treat non-generic collection, which is that they are legacy types provided to support existing code. However, we don't want to invest in them and add new functionality.
