### ISSUE TITLE
[.Net Core]The icons still show the gear icon

### ISSUE THREAD

**Issue by merriemcgaw** [dotnet/corefx#37305]
@Judy-Gao commented on [Wed Apr 24 2019](https://github.com/dotnet/winforms/issues/866)

**OS**: RS4 X64
**VS**: Dev16 16.1 d16.1 branch 28823.117 build
**.NET Core**: 3.0.100-preview5-11552 from Release branch

**More Info:**
1. This issue not reproduce .NET Framework project.
2. Affect controls and these's dependence dll.

Controls | DLL | Repositories
-- | -- | --
FileSystemWatcher | System.IO.FileSystem.Watcher.dll | dotnet/Corefx
PerformanceCounter | System.Diagnostics.PerformanceCounter.dll | dotnet/Corefx
Process | System.Diagnostics.Process.dll | dotnet/Corefx
SerialPort | System.IO.Ports.dll | dotnet/Corefx
ServiceController | System.ServiceProcess.ServiceController.dll | dotnet/Corefx
PrintDocument | System.Drawing.Common.dll | dotnet/Corefx
DataSet | System.Data.Common.dll | dotnet/Corefx
BackgroundWorker | System.ComponentModel.EventBasedAsync.dll | dotnet/Corefx
DirectoryEntry | System.DirectoryServices.dll | dotnet/Corefx
DirectorySearcher | System.DirectoryServices.dll | dotnet/Corefx
EventLog | System.Diagnostics.EventLog.dll | dotnet/Corefx

**Steps to reproduce:**
 1. Install the .NET Core 3.0 SDK from https://github.com/dotnet/core-sdk for Release branch.
 2. Open the .NET Core app from \\\mlangfs1\public\Winforms\CoreTest\IconChange\4.22\Issue1.zip  in VS.
 3. Run it and observe the control icon such as FileSystemWatcher

**Actual:**  FileSystemWatcher icon show gear
![FileSystemWatcher](https://user-images.githubusercontent.com/49627041/56650382-7df98c00-66b9-11e9-8233-d206e640cd4d.PNG)

**Expected:** FileSystemWatcher can show it's own icon.

---

@merriemcgaw commented on [Thu Apr 25 2019](https://github.com/dotnet/winforms/issues/866#issuecomment-486847127)

@dreddy-work can you take a look and determine why this is happening or where we need to make adjustments so it can work properly?

**Comment by merriemcgaw** [comment]
The resources associated with these binaries need to be ported to Core. This is required for compat with .NET Framework. DevExpress controls have runtime scenarios with designer functionality, and may need these icons.

**Comment by danmosemsft** [comment]
It looks like these are wired up by convention. There is no code in the libraries that references them. They are embedded as resource streams that are named for the type, with the bmp suffix, ie.,
```
System.ComponentModel.BackgroundWorker.bmp
System.Diagnostics.EventLog.bmp
System.Diagnostics.PerformanceCounter.bmp
System.Diagnostics.Process.bmp
System.IO.FileSystemWatcher.bmp
System.IO.Ports.SerialPort.bmp
System.Timers.Timer.bmp
etc
```
I'm guessing that somewhere in the designer is the other side of this assumption. We should be able to tweak it to look in a different assembly, and put these in winforms. That keeps 10KB of bloat out of the libraries, code that's only relevant to the Visual Studio designer.

**Comment by ericstj** [comment]
It's defined in ToolboxBitmapAttribute, which we don't apply to any of the CoreFx types.  Can the designer apply this attribute via TypeDescriptor, or add some fallback for known types at a higher level?

**Comment by merriemcgaw** [comment]
That makes sense, @Tanya-Solyanik can you see where we can do this in the designer codebase? @dreddy-work do you see _any_ runtime scenarios needing these icons? I, for one, do not.

**Comment by Tanya-Solyanik** [comment]
@Shyam-Gupta is working on the toolbox.
@ericstj  - what was the reason these attributes were not applied? We did not know they were needed?

**Comment by ericstj** [comment]
See https://github.com/dotnet/corefx/issues/37305#issuecomment-488165692.  These are designer assets that don’t belong in runtime assemblies. If you can put them in the designer you’ll have more control of them (just think of high dpi and theming changes in the IDE).

I haven’t looked at all the types but I can imagine layering is also a problem since drawing needs to be higher in the stack on .NETCore and outside the base shared framework.

**Comment by ericstj** [comment]
Yeah, lots of these are actually much lower in the .NETCore stack and won't be able to take a dependency on ToolboxBitmapAttribute.  We can't push ToolboxBitmapAttribute down due to its dependency on Image / gdiplus.   /cc @safern 

Here's where WInForms reads these: https://github.com/dotnet/winforms/blob/ee3a37b37de437d04f542e650bd5c26e504b73cc/src/System.Windows.Forms.Design/src/System/Drawing/Design/ToolboxItem.cs#L751.  Please include a fallback that checks inside System.Windows.Forms.Design using some convention.

**Comment by Tanya-Solyanik** [comment]
Thank you for the investigation, Eric! We were hoping to reuse the existing extensibility model here:(. Seems like we have to follow WPF-y model. FYI @dustincampbell

**Comment by ericstj** [comment]
You can keep the exisitng model for user code, but for these framework types add a fallback.  We've done similar things elsewhere in .NETCore (see TypeConverter).  It's not a big change.

**Comment by danmosemsft** [comment]
@merriemcgaw perhaps this bug should move back...

**Comment by Tanya-Solyanik** [comment]
> You can keep the exisitng model for user code, but for these framework types add a fallback.

This is a great idea!

**Comment by joshfree** [comment]
Closing out issue as it's unrelated to dotnet/corefx libraries per investigation above.
