### ISSUE TITLE
Consider re-using the Utf8JsonWriter instance within the Serializer

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#37335]
Currently, the serializer creates a new instance of the Utf8JsonWriter every time. Consider re-using an existing instance and resetting it each time.

https://github.com/dotnet/corefx/blob/5ed8c52f6a6d78267fe5857f7a67780ea02cc7a8/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.Stream.cs#L56

https://github.com/dotnet/corefx/blob/5ed8c52f6a6d78267fe5857f7a67780ea02cc7a8/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.Helpers.cs#L97

One approach to re-using the writer is as follows:
https://github.com/aspnet/AspNetCore/pull/9607

cc @steveharter

**Comment by Marusyk** [comment]
I will try to prepare PR for this, if nobody is against it

**Comment by ahsonkhan** [comment]
Absolutely, go for it. Thanks!

**Comment by karelz** [comment]
@Marusyk are you still working on it? I see the linked PR is Closed ...

**Comment by karelz** [comment]
@ahsonkhan please assign issues to contributors when they grab them ... thanks! (community contributor rightfully complained ;))

**Comment by Marusyk** [comment]
No, we decided to stop because there is small benefit from caching

https://github.com/dotnet/corefx/pull/37533#discussion_r284940413

**Comment by ahsonkhan** [comment]
Closing as not worth fixing.
