### ISSUE TITLE
Firebird SQL over ODBC crashes application when importing VARCHAR(MAX)

### ISSUE THREAD

**Issue by pielegacy** [dotnet/corefx#37348]
**Problem**

When trying to import data from a Firebird SQL database, the .NET Core host will crash when using SQL BulkCopy with a table that contains an `NVARCHAR(MAX)` column. 

This is occurring within a `try-catch` block yet still crashes the application, there are no errors logged in the console and when ran as a Windows Service it crashes the entire service.

**Configuration**

![image](https://user-images.githubusercontent.com/7465061/57054634-3a1a0e80-6cd9-11e9-9628-b4325317e481.png)

![image](https://user-images.githubusercontent.com/7465061/57054661-66ce2600-6cd9-11e9-9b98-43b58f1232bb.png)

**Error Logs**

From Windows Event Viewer

```
Faulting application name: dotnet.exe, version: 2.1.26515.5, time stamp: 0x5afb4a19
Faulting module name: ntdll.dll, version: 10.0.14393.2608, time stamp: 0x5bd133d4
Exception code: 0xc0000374
Fault offset: 0x00000000000f7b43
Faulting process id: 0x141c
Faulting application start time: 0x01d4fa48764e1eda
Faulting application path: C:\ProgramData\dotnet\dotnet.exe
Faulting module path: C:\windows\SYSTEM32\ntdll.dll
Report Id: e7873e37-9ded-48d2-98e9-9d5270a20ce1
Faulting package full name: 
```

**Comment by divega** [comment]
@pielegacy would it be possible for you to provide a repro project? Also, do you happen to know if the same functionality works with the .NET Framework version of System.Data.Odbc?

cc @saurabh500.

**Comment by AfsanehR** [comment]
@pielegacy Could you please provide a repro so we can look into this? Thanks

**Comment by ajcvickers** [comment]
Closing this issue as the requested repro project has not been provided. We will be happy to continue the investigation if such a project is posted in the future.
