### ISSUE TITLE
Use custom ICU data directory at runtime

### ISSUE THREAD

**Issue by jshin47** [dotnet/corefx#37343]
On Linux, the default sorting behavior is StringSort, which places symbols _before_ numbers and letters.

On Windows, the default is to place symbols _after_ numbers and letters.

There is an easy way to get `CompareInfo.Compare` to make Windows and Linux behave consistently - if you are okay with the `StringSort` behavior.

However if you want the Windows-style behavior, there is no easy path. The comments for the native dotnet code indicate this, https://github.com/dotnet/coreclr/blob/master/src/corefx/System.Globalization.Native/pal_collation.c#L26

> 
> // ICU's default is to use "StringSort", i.e. nonalphanumeric symbols come before alphanumeric.
> // When StringSort is not specified (.NET's default), the sort order will be different between
> // Windows and Unix platforms. The nonalphanumeric symbols will come after alphanumeric
> // characters on Windows, but before on Unix.
> // Since locale - specific string sort order can change from one version of Windows to the next,
> // there is no reason to guarantee string sort order between Windows and ICU. Thus trying to
> // change ICU's default behavior here isn't really justified unless someone has a strong reason
> // for !StringSort to behave differently.

In my opinion this is unacceptable in many use cases. We should be able to have a consistent and logical sort order on both platforms.

To overcome this I edited and rebuilt my system en_US.UTF-8 locale. I verified that my change works using the `sort` program on a text file. It worked.

But my simple `dotnet` program (`netcoreapp2.1` or `netcoreapp2.2`, and I presume `netcoreapp3` as well) does not seem to pick up the custom en_US.UTF-8 locale.

            System.Globalization.CultureInfo.CurrentCulture = new System.Globalization.CultureInfo("en_US");
            var string0 = "100 Mile House";
            var string1 = "'s-Hertogenbosch"; // begins with '

            var resultSort = CompareInfo.GetCompareInfo("en_US").Compare(string0, string1);

`resultSort` is always 1, indicating that "100 Mile House" comes _after_ the string beginning with an apostrophe.

How can I make `dotnet` load the locale I've defined in `/usr/lib/locale/locale-archive` ??

Best,
Justin

**Comment by danmosemsft** [comment]
@tarekgh

**Comment by tarekgh** [comment]
> How can I make dotnet load the locale I've defined in /usr/lib/locale/locale-archive ??

Did you try to do https://askubuntu.com/questions/21316/how-can-i-customize-a-system-locale?

**Comment by jshin47** [comment]
Hi Tarek,

I didn't see this reply, thanks for getting back so quickly!

Yes, that's the first thing I did. I verified that it works by using the `sort` command.

I don't get the impression that any of the system locale stuff matters because it all goes through ICU. Is that not the case?

**Comment by tarekgh** [comment]
> I don't get the impression that any of the system locale stuff matters because it all goes through ICU. Is that not the case?

That is I am not sure of. We just call ICU for the collation. If your custom locale is picked by ICU, it should be reflected on the .NET. Maybe you can try to call the native ICU API first to see if the locale change is reflected there. 
Or, if you can share the changes you did and how did you install it, I can try it myself. 

By the way, the steps in  https://askubuntu.com/questions/21316/how-can-i-customize-a-system-locale mentioned updating the system locale in the path ```/usr/share/i18n/locales``` just in case ICU not picking the system locale from ```/usr/lib/locale/locale-archive```.

**Comment by jshin47** [comment]
Sure, I can share the changes.

All I did was edit the file /usr/share/i18n/locales/iso14651_t1_common to edit the rule for the apostrophe:

`<U0027> <TIF-A>;IGNORE;IGNORE;<U0027> # 61 '`

And then rebuilt with `locale-gen "en_US.UTF-8`

**Comment by tarekgh** [comment]
Thanks @jshin47 for sharing. I'll try to take a look in the next couple of days.

**Comment by jshin47** [comment]
Sure thing. I used the `sort` command with a text file containing just the strings

`100 Mile House`
`'s-Hertogenbosch`

And it correctly sorted.

But my test program still puts the second string before the first.

**Comment by jshin47** [comment]
One more thing.

I think that ICU data files typically have the name `icudtl.dat` and for other apps, like `chromium-browser` for instance, are customized on a per-app basis. There may also be a similar default data file embedded in some `so` file, I imagine. I think that these files drive ICU behavior, not the system locale. I have no idea how to compile the files, and even if I did, no idea how to tell .NET to use that data file. There is an environment variable `ICU_DATA_DIR` that you can supposedly use to control ICU at runtime but I have no evidence it works with .NET Core.

**Comment by tarekgh** [comment]
Right, ICU carry its own collation data and that is what it uses for performing the sort operations. .NET don't care how ICU installed there as .NET just calls the ICU native APIs. So, if you customize the ICU and install it, that will get reflected on .NET automatically. 

What you can do is download the ICU sources from https://github.com/unicode-org/icu/releases/tag/release-64-2 and then do your own changes. build it and install it. here is the commands to build it:

```
go to the sources folder:

./configure --prefix=/usr/local/share 
make 
make install
```

**Comment by jshin47** [comment]
Thanks @tarekgh . But what if I want to compile just the data file and not the entire ICU, like an `icudtl.dat`? If I set the environment variable `ICU_DATA_DIR`, should it be reflected at runtime? I see other applications like Google Chrome and Slack do this.

**Comment by tarekgh** [comment]
I think you need to to set the environment variable ```ICU_DATA``` to the folder has the ICU data. I believe this should work. for more info, look at the section [ICU Data Directory](http://userguide.icu-project.org/icudata)

**Comment by jshin47** [comment]
I have tried setting `ICU_DATA` to a nonsense value to see if it throws an error. It doesn't. But maybe that's part of the internal ICU error handling.

I will try it with a real data file once I rebuild my custom data file and report back to you my findings.

**Comment by jshin47** [comment]
@tarekgh it didn't seem to have any effect. But I am wondering if there is something wrong with my data files. Could you point me toward an example project that I can use to test ICU from C++ ? (how are you doing it?)

**Comment by tarekgh** [comment]
try https://gist.github.com/tarekgh/71ad02888da20ce33b776806ee7ca9cb the comment on the top of the file is how you can compile it.

**Comment by jshin47** [comment]
Thanks! I am working with it now. I get the same undesirable result even after setting data directory using `u_setDataDirectory` so maybe something wrong with my file.

**Comment by tarekgh** [comment]
https://github.com/unicode-org/icu/blob/master/docs/userguide/icu_data/buildtool.md has some useful info. looking at the end, it has file substitution which you may try too. Sorry, I am not able to try myself now but if you couldn't do it, I'll try it next week. Thanks for your effort here.

**Comment by jshin47** [comment]
I'll try that too! What I really want to see is at least instance of using `u_setDataDirectory` or `ICU_DATA`, and then having the collation result be different as a result. If I keep not getting any differences with my current method of building the data I will try that build tool (I am using their ant build right now).

**Comment by jshin47** [comment]
Okay, so here's what I've discovered.

First, you have to compile ICU with the option `--with-data-packaging=archive` if you want to be able to use `ICU_DATA` at runtime. That said, it works if you do.

Second, I have thus far been unsuccessful in reproducing Windows-style collation rules on Linux.

Any idea where I might find the Windows rules defined?

**Comment by tarekgh** [comment]
Thanks for the update.

> Any idea where I might find the Windows rules defined?

Windows has a collation weights table (not exactly rules). you can find these tables [here](https://www.microsoft.com/en-us/download/details.aspx?id=10921) if this can help.

**Comment by tarekgh** [comment]
@jshin47 I am closing this issue as there is no real action from our side. Feel free to send any more questions if you need any more help. Thanks for your report.
