### ISSUE TITLE
string.Equals with InvariantCultureIgnoreCase differs from .Net Framework behaviour

### ISSUE THREAD

**Issue by paaland** [dotnet/corefx#37357]
The following code shows the two strings as equal in .Net Framework (4.7) while .Net Core 2.2 says they are different.

```
var text1 = "Abwasserfluss";
var text2 = "Abwasserfluß";

var areEqual = text1.Equals(text2, StringComparison.InvariantCultureIgnoreCase);

Console.WriteLine($"{text1} equals {text2}: {areEqual}");
```
I just ported a lot of code from .Net Framework to .Net Core and this is causing lots of errors.

**Comment by stephentoub** [comment]
cc: @tarekgh

**Comment by tarekgh** [comment]
We depend on the underlying OS collation behavior so it is expected you can see some differences. Please do the following to get the behavior you desire:

```C#
var areEqual = String.Compare(text1, text2, CultureInfo.InvariantCulture, CompareOptions.IgnoreNonSpace) == 0;
```

The issue https://github.com/dotnet/corefx/issues/17052 has some more info too. 

I am closing this issue but feel free to send any more question you may have.
