### ISSUE TITLE
Environment.GetEnvironmentVariable with something other than EnvironmentVariableTarget.Process silently fails on systems without registry

### ISSUE THREAD

**Issue by Izumemori** [dotnet/corefx#37366]
I have noticed that calling 
```cs
Environment.GetEnvironmentVariable(varName, EnvironmentVariableTarget.User);
// or
Environment.GetEnvironmentVariable(varName, EnvironmentVariableTarget.Machine);
```
silently "fails", ie returns an empty string, instead of falling back to `EnvironmentVariableTarget.Process` or throwing a `NotSupportedException`.

Is there any reason for this? Because this seems like an easy thing to overlook when porting an application from Windows to Unix, and might confuse users.

**Comment by stephentoub** [comment]
This was discussed at length in https://github.com/dotnet/corefx/issues/32685 and https://github.com/dotnet/corefx/issues/20147. Thanks.

**Comment by Izumemori** [comment]
Thank you, I guess I can't really argue with it. A warning on the docs might be enough, but I'd love to see it actually throw or at least fall back to Process, as many people might not check the docs because it does return the same as an unset variable.
