### ISSUE TITLE
ArrayBufferWriterTests_String.MultipleCallsToGetSpan test failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#37372]
On macOS.
```
System.Buffers.Tests.ArrayBufferWriterTests_String.MultipleCallsToGetSpan


Error message
Assert.Equal() Failure\nExpected: 6552500064\nActual: 6552498272

Stack trace
   at System.Buffers.Tests.ArrayBufferWriterTests`1.MultipleCallsToGetSpan() in /Users/vsts/agent/2.150.3/work/1/s/src/System.Memory/tests/ArrayBufferWriter/ArrayBufferWriterTests.T.cs:line 375
```
cc: @ahsonkhan

**Comment by ViktorHofer** [comment]
The tests asserts that the Span that is returned from GetSpan is always at the same memory location. Do the pointers need to be pinned maybe? https://github.com/dotnet/corefx/blob/master/src/System.Memory/tests/ArrayBufferWriter/ArrayBufferWriterTests.T.cs#L375

**Comment by stephentoub** [comment]
> Do the pointers need to be pinned maybe? 

The spans need to be pinned.  I'm about to push a PR.

**Comment by ViktorHofer** [comment]
Ah yeah, I meant the spans... You were faster, as always 😁
