### ISSUE TITLE
Source code for System.Threading.Timer is missing

### ISSUE THREAD

**Issue by ygoe** [dotnet/corefx#37385]
It should be here: https://github.com/dotnet/corefx/tree/master/src/System.Threading.Timer

But that project is empty. It doesn't look correct. I need to look at the implementation of the `Change` method to evaluate its performance characteristics. (I.e. is it okay to call it repeatedly in a hot path.)

**Comment by vcsjones** [comment]
The implementation for this is in CoreLib, which is in the coreclr repository here: https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Threading/Timer.cs
