### ISSUE TITLE
Cannot use ConfiguredAsyncDisposable or ConfiguredCancelableAsyncEnumerable with Microsoft.Bcl.AsyncInterfaces

### ISSUE THREAD

**Issue by onovotny** [dotnet/corefx#37381]
With `Microsoft.Bcl.AsyncInterfaces`, it's impossible to use `ConfiguredCancelableAsyncEnumerable<T>` or `ConfiguredAsyncDisposable`'s

The factory methods that create them are in `TaskExtensions`, which is missing currently from the `netstandard2.0` version. As those ctor's are internal, there's no way to use them correctly.

/cc @stephentoub @terrajobst

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/37354
Addressed by https://github.com/dotnet/corefx/pull/37379
