### ISSUE TITLE
TimeZoneInfo_DisplayNameStartsWithOffset tes failing locally for Casablanca

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#37389]
```
System.Tests.TimeZoneInfoTests.TimeZoneInfo_DisplayNameStartsWithOffset [FAIL]
  01:00 != 00:00:00, dn:(UTC+01:00) Casablanca, sn:(UTC+01:00) Casablanca
  Expected: True
  Actual:   False
  Stack Trace:
    D:\repos\corefx\src\System.Runtime\tests\System\TimeZoneInfoTests.cs(2229,0): at System.Tests.TimeZoneInfoTests.TimeZoneInfo_DisplayNameStartsWithOffset()
```
cc: @tarekgh

**Comment by tarekgh** [comment]
thanks @stephentoub for reporting it.

**Comment by eanova** [comment]
The problem seems to be that even though the standard name is (UTC+01:00) Casablanca,  Windows sets the BaseUtcOffsetoff to 00:00.  The PS timezone also behaves this way.

**Comment by tarekgh** [comment]
@eanova I have reported the issue to Windows team. ```(UTC+01:00) Casablanca``` is the display name and not the standard name.
