### ISSUE TITLE
Meybe/Optional

### ISSUE THREAD

**Issue by yahorsi** [dotnet/corefx#37399]
Hi Guys,

Just wondering why in the .NET there is no Meybe/Optional type. Nullable is a bit different thing.
Having full support for the Meybe/Optional will make programming much cleaner/simpler.
By full I mean not just adding Meybe/Optional but adding corresponding support in collections/linq and so on.

Thanks

**Comment by GalaxiaGuy** [comment]
https://github.com/dotnet/corefx/issues/18159
(and potentially https://github.com/dotnet/csharplang/issues/426)

**Comment by stephentoub** [comment]
Closing as a dup of the cited issues.  Thanks.
