### ISSUE TITLE
ZipArchive() seems to read deadloop under UWP on a defective test file

### ISSUE THREAD

**Issue by kburgoyne** [dotnet/corefx#37394]
I have a ~330MB test ZIP file which Microsoft.NETCore.App "new ZipArchive(…)" will read for about  1 minute and then finally throw System.IO.InvalidDataException("End of Central Directory record could not be found.").

That's "acceptably correct" because the file is truncated by one byte at the end due to a bad download. A couple older ZIP utils also reject the file (although Windows File Explorer is willing to open it and copy files out of it).  For our purposes, it's acceptable to get the exception.

The possible issue is with Microsoft.NETCore.UniversalWindowsPlatform. Our real (not test) app is UWP, so this is the one that's the concern for us.  From what I've been able to observe, "new ZipArchive(…)" gives every impression of being lost in an infinite read loop.

I read on another issue the code will apparently read through the entire file trying to find the Central Directory. Considering the ~330MB file size, I've given it as long as 15 minutes to see if it will finally either work or throw the same exception as Microsoft.NETCore.App.

Process Explorer seems to indicate it is busy reading like crazy.  VS2019 Process Memory graph indicates a ton of managed heap garbage collection without the amount of process memory increasing.  So seemingly no memory leak/accumulation but a ton of memory thrashing.

I wonder if anyone who is set up to debug Microsoft.NETCore.UniversalWindowsPlatform can investigate what "new ZipArchive(…)" is actually busy doing with this file. Did the code actually get lost in an infinite loop, or is it just busy reading through the entire ~330MB file in an incredibly slow and time consuming manner.  In other words, would it eventually throw the exception given a decade or so of waiting.  Is there anything that can be done to make it more responsive like Microsoft.NETCore.App.

Our real app downloads files like this one from the web (it's a USGS data file) and then tries to use ZipArchive() to perform a validation against the downloaded image. It's obviously unacceptable from a user standpoint if what they see is the app stuck in the file validation phase for seemingly forever.

I can post the file to a OneDrive share if someone is willing to investigate.

Thanks!

**Comment by carlossanlop** [comment]
Fixed with #41007.
