### ISSUE TITLE
Get 8 build errors on Linux

### ISSUE THREAD

**Issue by cnblogs-dudu** [dotnet/corefx#3739]
Get 8 errors when building latest corefx on ubuntu with dnx-coreclr-linux-x64.1.0.0-rc1-15838.
```
CSC : error CS7027: Error signing output with public key from file 
'/data/git/corefx/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00104/lib/ECMA.snk' 
-- mscoree.dll [/data/git/corefx/src/System.IO.Compression.ZipFile/ref/System.IO.Compression.ZipFile.csproj]

CSC : error CS7033: Delay signing was specified and requires a public key, but no public key was specified 
[/data/git/corefx/src/System.IO.Compression.ZipFile/ref/System.IO.Compression.ZipFile.csproj]

CSC : error CS7027: Error signing output with public key from file 
'/data/git/corefx/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00104/lib/ECMA.snk' 
-- mscoree.dll [/data/git/corefx/src/System.IO.Compression/ref/System.IO.Compression.csproj]

CSC : error CS7033: Delay signing was specified and requires a public key, but no public key was specified 
[/data/git/corefx/src/System.IO.Compression/ref/System.IO.Compression.csproj]

CSC : error CS7027: Error signing output with public key from file 
'/data/git/corefx/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00104/lib/ECMA.snk' 
-- mscoree.dll [/data/git/corefx/src/System.Reflection.Context/ref/System.Reflection.Context.csproj]

CSC : error CS7033: Delay signing was specified and requires a public key, but no public key was specified 
[/data/git/corefx/src/System.Reflection.Context/ref/System.Reflection.Context.csproj]

CSC : error CS7027: Error signing output with public key from file 
'/data/git/corefx/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00104/lib/ECMA.snk' 
-- mscoree.dll [/data/git/corefx/src/System.Runtime.WindowsRuntime.UI.Xaml/ref/System.Runtime.WindowsRuntime.UI.Xaml.csproj]

CSC : error CS7033: Delay signing was specified and requires a public key, but no public key was specified 
[/data/git/corefx/src/System.Runtime.WindowsRuntime.UI.Xaml/ref/System.Runtime.WindowsRuntime.UI.Xaml.csproj]
```

**Comment by mellinoe** [comment]
I'm also seeing this on OSX and Linux. It seems to be the same projects as above

**Comment by jasonwilliams200OK** [comment]
I am getting same on FreeBSD. Here is the [msbuild.log](https://gist.githubusercontent.com/jasonwilliams200OK/b375ce52c7b0c90e24af/raw/c895d405a3044dd6acdb26ec49c4b0ced0c76d1a/corefx-msbuild.log).

**Comment by weshaggard** [comment]
Copying the snippet from @jasonwilliams200OK's log:
```
 /root/corefx/packages/Microsoft.Build.Mono.Debug.14.1.0.0-prerelease/lib/tools/../tools/csc2.exe -noconfig -nowarn:1701,1702 -langversion:5 -nostdlib+ -warn:4 -define:DEBUG;TRACE;DEBUGRESOURCES;SIGNED -reference:/root/corefx/packages/System.IO.Compression/4.0.0/ref/dotnet/System.IO.Compression.dll -reference:/root/corefx/packages/System.IO/4.0.0/ref/dotnet/System.IO.dll -reference:/root/corefx/packages/System.Runtime/4.0.0/ref/dotnet/System.Runtime.dll -reference:/root/corefx/packages/System.Text.Encoding/4.0.0/ref/dotnet/System.Text.Encoding.dll -debug- -delaysign+ -keyfile:/root/corefx/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00104/lib/ECMA.snk -optimize- -out:/root/corefx/bin/obj/ref/System.IO.Compression.ZipFile/4.0.1.0/System.IO.Compression.ZipFile.dll -target:library -warnaserror+ System.IO.Compression.ZipFile.cs /root/corefx/bin/obj/ref/System.IO.Compression.ZipFile/4.0.1.0/_AssemblyInfo.cs
CSC : error CS7027: Error signing output with public key from file '/root/corefx/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00104/lib/ECMA.snk' -- mscoree.dll [/root/corefx/src/System.IO.Compression.ZipFile/ref/System.IO.Compression.ZipFile.csproj]
CSC : error CS7033: Delay signing was specified and requires a public key, but no public key was specified [/root/corefx/src/System.IO.Compression.ZipFile/ref/System.IO.Compression.ZipFile.csproj]
```

I assume the file `/root/corefx/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00104/lib/ECMA.snk` exists? 

I'm not at all sure what is happening here. @akoeplinger @ellismg any ideas? My only guess is there is something going on with mono csc here.

**Comment by ellismg** [comment]
I think @pgavlin was seeing this, but he cleaned and rebuilt and it worked.

**Comment by pgavlin** [comment]
No, I'm still seeing this. Haven't had a chance to investigate yet.

**Comment by pgavlin** [comment]
FWIW, I verified that the key file exists and that it contains the ECMA key.

**Comment by jasonwilliams200OK** [comment]
Yup the `ECMA.snk` file exists. I just rebuilt the current master: commit 4554758fb from scratch and the occurrence of this error has increased from 8 (against 2d36889) to 12: [old](https://gist.githubusercontent.com/jasonwilliams200OK/b375ce52c7b0c90e24af/raw/c895d405a3044dd6acdb26ec49c4b0ced0c76d1a/corefx-msbuild.log) vs. [new msbuild.log](https://gist.githubusercontent.com/jasonwilliams200OK/b375ce52c7b0c90e24af/raw/ca9f28aef5ac9977116b069c7caa9d70712e011c/corefx-msbuild.log)

**Comment by ellismg** [comment]
I looked into this a little.

We don't actually use mono CSC, we use Roslyn and apparently Roslyn has never supported this when running on platforms other than windows (since it calls into mscoree to do stuff), see https://github.com/dotnet/roslyn/issues/2444 for more context.

We actually have code to work around this in dir.props by unconditionally setting `UseECMAKey` to false when the host platform in not Windows.  However, some projects were stomping over this setting.  It's unclear to me why this just started to break.

I will open a PR that modifies the specific projects to only set `UseECMAKey` to true if it is unset.

**Comment by weshaggard** [comment]
Thanks @ellismg I think this just started to break because we just started to build the ref folders recently (https://github.com/dotnet/corefx/commit/581a77341ea7fd3f8ed9897b5d2810eea87eb44b). I suspect it has been broken since then.

**Comment by jasonwilliams200OK** [comment]
Thanks @ellismg! No more `ECMA.snk` errors on FreeBSD ([latest msbuild.log](https://gist.githubusercontent.com/jasonwilliams200OK/b375ce52c7b0c90e24af/raw/62c9aed2bcd3a2d816b5118b42a5883d6638e37a/corefx-msbuild.log) against 01fc685) :+1:
