### ISSUE TITLE
gssapi error when building CoreFx on Fedora

### ISSUE THREAD

**Issue by robertpi** [dotnet/corefx#37404]
Hello all,

I'm trying to build corefx on a Fedora, as an external to the mono project, I get an error when trying to build the `corefx/src/Native/Unix/System.Net.Security.Native` directory.

The make output is:

```
Making all in native
make[3]: Entering directory '/home/rpickeri/mono/mono/native'
Makefile:1445: ../../external/corefx/src/Native/Unix/System.Net.Security.Native/.deps/libmono_native_unified_la-pal_gssapi.Plo: No such file or directory
make[3]: *** No rule to make target '../../external/corefx/src/Native/Unix/System.Net.Security.Native/.deps/libmono_native_unified_la-pal_gssapi.Plo'.  Stop.
make[3]: Leaving directory '/home/rpickeri/mono/mono/native'
make[2]: *** [Makefile:514: all-recursive] Error 1
make[2]: Leaving directory '/home/rpickeri/mono/mono'
make[1]: *** [Makefile:588: all-recursive] Error 1
make[1]: Leaving directory '/home/rpickeri/mono'
make: *** [Makefile:518: all] Error 2
```

I think this is a dependency issue, but I'm not sure what Fedora package needs to be added.

Kind regards,
Robert

**Comment by robertpi** [comment]
After running `./build.sh` directly, rather than via mono, I get the below error message that `pal_config.h`, so it seems pretty clear that this is the missing dependency, but I haven't been able to identify where this should come from. 

```
1 error generated.
/home/rpickeri/mono/external/corefx/src/Native/Unix/System.Native/pal_io.c:6:10: fatal error: 
      'pal_config.h' file not found
#include "pal_config.h"
         ^~~~~~~~~~~~~~
1 error generated.
make[2]: *** [System.Native/CMakeFiles/System.Native.dir/build.make:76: System.Native/CMakeFiles/System.Native.dir/pal_errno.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:224: System.Native/CMakeFiles/System.Native.dir/all] Error 2
make[2]: *** [System.Native/CMakeFiles/System.Native-Static.dir/build.make:89: System.Native/CMakeFiles/System.Native-Static.dir/pal_interfaceaddresses.c.o] Error 1
1 error generated.
make[2]: *** [System.Native/CMakeFiles/System.Native-Static.dir/build.make:102: System.Native/CMakeFiles/System.Native-Static.dir/pal_io.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:187: System.Native/CMakeFiles/System.Native-Static.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:93: System.IO.Compression.Native/CMakeFiles/System.IO.Compression.Native-Static.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
Failed to build corefx native components.
Command execution failed with exit code 1.
```

**Comment by danmosemsft** [comment]
pal_config.h is generated from pal_config.h.in src\Native\Unix\configure.cmake

What version of cmake do you have? Can you check you have all prerequisites:
https://github.com/dotnet/corefx/blob/master/Documentation/building/unix-instructions.md
then maybe `git clean -fdx` and try again?

**Comment by robertpi** [comment]
I have `cmake version 3.14.1`, a clean and rebuild still fails to generate 'pal_config.h'.

The file `src\Native\Unix\configure.cmake` just contains this somewhat cryptic message:

```
#
# !!!! IMPORTANT !!!!
#
# Any change in this file needs to be manually reflected into Mono's configure.ac
# by adding or removing AC_CHECK_FUNC/AC_TRY_LINK which mirror the CMake checks in this file.
#
# !!!! IMPORTANT !!!!
#
# The last reviewed revision: b70c466082dfdc30de89808e34097b30e6124b75
#
```

The rebuild did cause me to notice there are some missing methods from openssl, I think, could this be the source of this issue? I have openssl 1.1.0 installed, which is not the last but one release:

```
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11") 
-- Found CURL: /usr/lib64/libcurl.so (found version "7.59.0")  
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.1.0h")  
-- Looking for TLSv1_1_method in /usr/lib64/libssl.so
-- Looking for TLSv1_1_method in /usr/lib64/libssl.so - found
-- Looking for TLSv1_2_method in /usr/lib64/libssl.so
-- Looking for TLSv1_2_method in /usr/lib64/libssl.so - found
-- Looking for EC_GF2m_simple_method
-- Looking for EC_GF2m_simple_method - not found
-- Looking for SSL_get0_alpn_selected
-- Looking for SSL_get0_alpn_selected - not found
```

**Comment by wfurt** [comment]
cc: @bartonjs

**Comment by bartonjs** [comment]
This mainly seems like a nesting problem in the Mono tree.

FWIW, if `SSL_get0_alpn_selected` is detecting as not present, that suggests you don't have the OpenSSL 1.1.0 headers (probably 1.0.2).  I don't know about Mono's usage of OpenSSL, but .NET Core's shims can build against 1.0.1, 1.0.2, 1.1.0, or 1.1.1.

**Comment by karelz** [comment]
There does not seem to be anything left to do in CoreFX.
If there are improvements in our build system that would help building on Fedora, please put up a PR if you can. Thanks!
