### ISSUE TITLE
System.Numerics.Vectors types are not serializable

### ISSUE THREAD

**Issue by frabert** [dotnet/corefx#37425]
Currently, none of the types in `System.Numerics.Vectors` are marked as `[Serializable]`.
Is there are reason for not having the annotation, or is it simply lack of request/need?

**Comment by jkotas** [comment]
A limited version of binary serialization (ie `[Serializable]` attribute) was included in .NET Core to ease migration of code from .NET Framework. The binary serialization is legacy technology with number of problems. We do not plan to make more types binary serializable.

We recommend to switch to alternative serialization schemes (e.g. based on JSON) that do not depend on binary serialization.

More details are in https://github.com/dotnet/corefx/issues/19119 https://docs.microsoft.com/en-us/dotnet/standard/serialization/binary-serialization
