### ISSUE TITLE
BoundedChannelWriter.TryWrite() returns true when Channel is full and FullMode is DropWrite

### ISSUE THREAD

**Issue by Grammarian** [dotnet/corefx#37447]
I would expect this unit test to pass, but it fails on the `IsFalse` assert:

 ```
[TestMethod]
public void Full()
{
    var channel = Channel.CreateBounded<string>(new BoundedChannelOptions(1)
    {
        AllowSynchronousContinuations = false,
        FullMode = BoundedChannelFullMode.DropWrite,
        SingleReader = true,
        SingleWriter = true
    });
    
    Assert.IsTrue(channel.Writer.TryWrite("one"));
    Assert.IsFalse(channel.Writer.TryWrite("two"));
}
```

Given these docs for the `TryWrite()`:

```
/// <summary>Attempts to write the specified item to the channel.</summary>
/// <param name="item">The item to write.</param>
/// <returns>true if the item was written; otherwise, false if it wasn't written.</returns>
public abstract bool TryWrite(T item);
```

The second `TryWrite()` does not write to the channel, and I think should return false.

**Comment by stephentoub** [comment]
It's behaving correctly. The Drop modes mean that writes succeed even if the channel is full. To do that, something must be removed, and in the DropWrite case, it's the item just written. Think of it like the buffer temporarily expanding to fit the written item and then getting rid of something to shrink back down.

If you want TryWrite to return false here, you should use the default mode that doesn't drop anything.

**Comment by Grammarian** [comment]
Thanks for your response. I do understand the behaviour. 

However, given that the docs say "true if the item was written; otherwise, false if it wasn't written". And in this case, it clearly wasn't written, so returning `true` seems somewhat inaccurate.
