### ISSUE TITLE
HTTP2: System.IO.IOException: The request was aborted.

### ISSUE THREAD

**Issue by JamesNK** [dotnet/corefx#37446]
An error is raised from the gRPC interop tests with HttpClient.SendAsync:

```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The request was aborted.
   at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
   at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync()
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Grpc.NetCore.HttpClient.Internal.GrpcCall`2.SendAsync(HttpClient client, HttpRequestMessage message) in /var/local/git/grpc-dotnet/src/Grpc.NetCore.HttpClient/Internal/GrpcCall.cs:line 349
```

https://source.cloud.google.com/results/invocations/b97f0bdb-5797-4f24-b9b1-54b30875a5b7/targets/github%2Fgrpc%2Finterop_test/tests;group=tests;test=cloud_to_cloud:aspnetcore:c%2B%2B_server:empty_unary:tls;row=4

**Comment by JamesNK** [comment]
This test works against some HTTP2 gRPC servers:

* ASP.NET Core in Kestrel
* Java
* Go
* Dart

And fails in others

* C Core
* Languages that wrap C Core (Ruby, Python, C#)
* NodeJS

**Comment by JamesNK** [comment]
Wireshark captures of success against ASP.NET Core and failure against C Core: [wireshark.zip](https://github.com/dotnet/corefx/files/3145065/wireshark.zip)

**Comment by wfurt** [comment]
can we reproduce this in house @JamesNK?

**Comment by JamesNK** [comment]
Yes.

1. git clone https://github.com/JamesNK/grpc-dotnet.git
2. git checkout jamesnk/nativeinteropserver
3. dotnet run -p testassets\InteropTestsNativeWebsite
4. dotnet run -p testassets\InteropTestsClient --server_port 8070 --test_case empty_unary

**Comment by wfurt** [comment]
I will investigate. With latest code I get:
```
furt@net-dale:/mnt/github/grpc-dotnet/testassets/InteropTestsClient$ ~/dotnet-3.0.x/dotnet run --server_port 8070 --test_case  empty_unary
Use TLS: False
Use Test CA: False
Client type: httpclient
Server host: localhost
Server port: 8070
running empty_unary

Unhandled Exception: System.AggregateException: One or more errors occurred. (An error occurred while sending the request.) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The request was aborted. ---> System.Net.Http.Http2ProtocolException: The HTTP/2 request failed with protocol error 'INTERNAL_ERROR' (0x2).
```

**Comment by wfurt** [comment]
It seems like the test does send RST_STREAM[1] with INTERNAL_ERROR. Could you please clarify expected behavior @JamesNK

**Comment by JamesNK** [comment]
It should work. All the other gRPC HTTP/2 clients (C++, Java, JavaScript, Dart, Ruby, Python, C# C Core) are able to successfully call this server.

I will update the server to log its internals to the console. You could also examine what HttpClient sends to the server vs what the C# C Core client sends in the wireshark logs I attached to this issue.

**Comment by wfurt** [comment]
can I run the other clients anyhow? (one passing would be good enough so I can look for differences. It almost looks like we send something in the request server does not like.

**Comment by JamesNK** [comment]
Here is a repo that will run successfully:
1. git clone https://github.com/JamesNK/grpc-dotnet.git
2. git checkout jamesnk/nativeinteropserver
3. dotnet run -p testassets\InteropTestsNativeWebsite
4. dotnet run -p testassets\InteropTestsClient --server_port 8070 --test_case empty_unary **--client_type ccore**

Only the last part is different.

**Comment by wfurt** [comment]
thanks. I did look at differences in requests. For now, I can only see that functional request also sends accept-encoding, grpc-accept-encoding and TE: trailers. 
I don't know if that can make difference but it would be nice to match it. I assume I would need to build the grpc package somehow, right? I did quick search through the repo and I did not see anything obvious.

**Comment by JamesNK** [comment]
Thanks for the info, I fixed it.

The C Core server logs mentioned the TE header. I looked into the spec and the TE header is required, and some gRPC servers use it absence to detect bad proxies.

Adding "te:trailers" succeeds:
```
C:\Development\Source\grpc-dotnet [jamesnk/nativeinteropserver ≡ +0 ~1 -0 !]> dotnet run -p testassets\InteropTestsClient --server_port 8070 --test_case empty_unary --client_type httpclient
Use TLS: False
Use Test CA: False
Client type: httpclient
Server host: localhost
Server port: 8070
running empty_unary
Passed!
```
