### ISSUE TITLE
ProcessInfo Linux/Windows incompatibility

### ISSUE THREAD

**Issue by pragmaticadam** [dotnet/corefx#37467]
Hi,

I'm trying to run same process as a child of current process. Showed below code works just fine under windows, but fails in Linux with  error

No executable found matching command "dotnet-MyDll.dll"

```
var processInfo = new ProcessStartInfo
            {
                FileName = "dotnet",
                Arguments = "MyDll.dll " + id.ToString()
            };

            Console.WriteLine("Starting child process...");
            var process = Process.Start(processInfo);
            return process;

```

Ive also tried
         `       FileName = "dotnet MyDll.dll"+ id.ToString(),`
but it ends up with different error 
Unhandled Exception: System.ComponentModel.Win32Exception: No such file or directory

I've also tried 
```

            var parentP = Process.GetCurrentProcess();
            string fullPath = parentP.MainModule.FileName;
            var command = fullPath+" "+Assembly.GetEntryAssembly().Location+" "+ id.ToString();
            Console.WriteLine("Command = "+command);
            var processInfo = new ProcessStartInfo
            {
                FileName = command
            };
            var process = Process.Start(processInfo);
```
Still 
Unhandled Exception: System.ComponentModel.Win32Exception: No such file or directory

what is proper way of running currently running dll again under Linux with dotnet core

**Comment by wfurt** [comment]
cc: @tmds

**Comment by pragmaticadam** [comment]
I've also tried :

var parrentP = Process.GetCurrentProcess();
        string fullPath = parrentP.MainModule.FileName;
        var command = "\"" + fullPath + "\" " ;
        var args = Assembly.GetEntryAssembly().Location + " " + id;
        var processInfo = new ProcessStartInfo
        {
            FileName = command,
            Arguments = args
        };
            var process = Process.Start(processInfo);


Works under windows, do not work under LINUX


Exception No such file or directory
Exception    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)

Looks for me like something with path building, 

WHAT IS WORK AROUND FOR THIS ?

**Comment by tmds** [comment]
This works:

```cs
static void Main(string[] args)
{
    if (args.Length == 0)
    {
        var psi = new ProcessStartInfo
        {
            FileName = Process.GetCurrentProcess().MainModule.FileName,
            Arguments = $"\"{Assembly.GetEntryAssembly().Location}\" \"hello world\""
        };
        Process.Start(psi).WaitForExit();
    }
    else
    {
        System.Console.WriteLine("Called with arg: " + args[0]);
    }
}
```

If you want to use the `Arguments` property, you need to surround the individual arguments with double quotes. For example:
```cs
Arguments = $"\"{Assembly.GetEntryAssembly().Location}\" \"hello world\""
```

If it doesn't work for you, what is the values of: `Process.GetCurrentProcess().MainModule.FileName` and `Assembly.GetEntryAssembly().Location`.

> WHAT IS WORK AROUND FOR THIS ?

Don't use CAPS unless you're angry and want to yell at someone.

**Comment by stephentoub** [comment]
> If you want to use the Arguments property, you need to surround the individual arguments with double quotes

Only if they may have whitespace, right?

**Comment by tmds** [comment]
> Only if they may have whitespace, right?

Yes, only needed then. They get stripped of the other arguments, so adding them everywhere is a simple way to avoid forgetting them somewhere.

**Comment by pragmaticadam** [comment]
> @pragmaticadam is it working for you now? may this be closed?

Yes,
thank You!
