### ISSUE TITLE
Build is broken in version 3.0.100-preview6-011767

### ISSUE THREAD

**Issue by pavelovcharov** [dotnet/corefx#37471]
I've a simple app that references the following packages:
```
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.0.1" />
    <PackageReference Include="NUnit" Version="3.11.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.13.0" />
```
https://github.com/pavelovcharov/netcore3_buildbrokenpreview6

The project is successfully built with .NET Core 3.0.100-preview4-011223. However, after upgrading to the version 3.0.100-preview6-011767, the build fails with an error: 
```
error NU1102: Unable to find package Microsoft.NETCore.Platforms with version (>= 3.0.0-preview6.19255.4)
```

**dotnet --info:**
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-011767
 Commit:    ce3e2ee3c1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-011767\

Host (useful for support):
  Version: 3.0.0-preview6-27705-15
  Commit:  19521cec63

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-011767 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6-19255-03 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27705-15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27705-15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by pavelovcharov** [comment]
I've just checked, the project builds successfully with the .NET Core version 3.0.100-preview5-011568.

**Comment by ViktorHofer** [comment]
cc @wtgodbe

**Comment by benaadams** [comment]
You likely need to add a NuGet.config to pick up the right feeds as they aren't on NuGet (as are pre-preview); from https://github.com/dotnet/core-sdk#installers-and-binaries it suggests
```
<configuration>
  <packageSources>
    <add key="dotnet-core" value="https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json" />
    <add key="dotnet-windowsdesktop" value="https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/index.json" />
    <add key="aspnet-aspnetcore" value="https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/index.json" />
    <add key="aspnet-aspnetcore-tooling" value="https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/index.json" />
    <add key="aspnet-entityframeworkcore" value="https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/index.json" />
    <add key="aspnet-extensions" value="https://dotnetfeed.blob.core.windows.net/aspnet-extensions/index.json" />
  </packageSources>
</configuration>
```

**Comment by ViktorHofer** [comment]
You should only need "https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json" for the base .NET Core workload.

Thanks Ben!

**Comment by pavelovcharov** [comment]
Thanks @ViktorHofer, @benaadams
