### ISSUE TITLE
[System.Text.Json] About difference between property with null and does not exists

### ISSUE THREAD

**Issue by jkbrito** [dotnet/corefx#37485]
How do we deal with the difference between a json property being null, and there is no property?
For example:

```csharp
public class ObjectOne {

    [JsonProperty(Name = "propertyOne")]
    public string PropertyOne {get;set;}
    
    [JsonProperty(Name = "propertyTwo")]
    public string PropertyTwo {get;set;}

}
```
```javascript
{"propertyOne": null, "propertyTwo":null}
{"propertyOne": null }
```

We could create a struct that contains the information of whether a property exists or not in deserialization. For exemple.
 
```csharp
 public struct JsonMetadata<T>
    {
        public JsonMetadata(T obj)
        {
            HasProperty = true;
            Value = obj;
        }

        public bool HasProperty { get; }  
        public T Value { get; }

        public static implicit operator T(JsonMetadata<T> jMetadata) => jMetadata.Value;
        public static implicit operator JsonMetadata<T>(T value) => new JsonMetadata<T>(value);
    }

 public class ObjectOne {

    [JsonProperty(Name = "propertyOne")]
    public string PropertyOne {get;set;}
    
    [JsonProperty(Name = "propertyTwo")]
    public JsonMetadata<string> PropertyTwo {get;set;}

}
```
Is this possible? Is there any way to handle this case in the current implementation?

**Comment by ahsonkhan** [comment]
cc @steveharter

**Comment by steveharter** [comment]
Potential workarounds:
1) Set the property to some placeholder\singleton value which will get overridden during deserialize if the JSON contains the value
2) Implement the setter for the property(s) and set some private bool to track.
3) Implement a [custom converter](https://github.com/dotnet/corefx/issues/36639) and track whether the property exists in the JSON or not.

@JamesNK does Json.NET have a mechanism to detect whether a property was deserialized?

**Comment by JamesNK** [comment]
No. There is `[Required]` that will throw an error if there is no JSON for that property, but nothing like this.

All three of the options you listed are good solutions.

**Comment by pranavkm** [comment]
@JamesNK, did you mean [JsonPropertyRequired](https://www.newtonsoft.com/json/help/html/JsonPropertyRequired.htm)

MVC users have often asked for a way to identify when a property isn't on the wire. While @steveharter's solutions are acceptable for the trivial cases, it really doesn't scale well if you want the behavior to apply in general. Plus, you're forced to manually perform the checks which seems cumbersome. 

Could we consider introducing an attribute like Json.NET to enforce this behavior?

**Comment by ahsonkhan** [comment]
I believe @steveharter has provided the relevant info for the question being posed in this issue. Hence closing. The discussion related to the `[Required]` property can continue in https://github.com/dotnet/corefx/issues/38492.

Thanks.
