### ISSUE TITLE
UWP: Input interpretation of multi layered keyboards

### ISSUE THREAD

**Issue by MovGP0** [dotnet/corefx#37488]
There seems to be a bug in UWP, such that mutli-layered keyboard layouts like the german [Neo2](https://neo-layout.org/) are not interpreted correctly. 

Ie. on Neo2, layer 1 (lowercase characters) and 2 (uppercase caracters) are interpreted correctly, while layers 3 (special caracters), 4 (control caracters), 5 (greek letters), and 6 (math symbols) are falsily interpreted as lowercase and uppercase caracters. 

This way, basic tasks like writing E-Mail addresses, programming in an UWP app, or entering passwords, is not possible. (except by copy-pasting from an WinForms or WPF application)

The mapping works perfectly fine in WinForms and WPF applications.

**Comment by MovGP0** [comment]
applies to `Windows.UI.Xaml.Input` `KeyUp` any `KeyDown` events.

**Comment by jkotas** [comment]
This is bug in the Windows operating system, not in the open source .NET Core project.

Could you please report this issue via
https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub instead?

**Comment by MovGP0** [comment]
I've reported this bug multiple times via Windows Feedback. No response so far.
