### ISSUE TITLE
Consider changing the CodeAccessPermission.PermitOnly stub to NoOp

### ISSUE THREAD

**Issue by 0x53A** [dotnet/corefx#37483]
``PermitOnly`` currently throws a PNSE. We use a third party WinForms Control which calls this.

Could this instead be stubbed to be a NoOp?

This would help us get one step further in the .net core 3 port.

**Comment by ViktorHofer** [comment]
cc @danmosemsft

**Comment by bartonjs** [comment]
There's no CAS, but we also don't want the illusion of CAS working.

Methods that ask if a permission is held return true, methods that grant permissions return true, methods that try to take permissions away throw.

**Comment by danmosemsft** [comment]
That was the reasoning. @0x53A have you reached out to the owner of the control?

**Comment by 0x53A** [comment]
No, as far as I know the company no longer exists.

My backup plan is to just rewrite the dll with Cecil and remove the call. I did a prototype and it seemed to work.

**Comment by danmosemsft** [comment]
OK. I"ll close this then. If others hit this problem, please open a new issue (since we're more likely to see it) and if it's common enough then we can think about other options.
