### ISSUE TITLE
System.Text.Json serializer doesn't work with Guid and Guid?

### ISSUE THREAD

**Issue by Eilon** [dotnet/corefx#37496]
_From @nguyenquyhy on Tuesday, 07 May 2019 08:58:20_

### Describe the bug
System.Text.Json serializer doesn't work with `Guid` and `Guid?`. The behavior is as following:

- For `Guid`: the serialized data is always `{}` regardless of the `Guid` value.
- For `Guid?`: get exception `ArgumentException: Cannot bind to the target method because its signature is not compatible with that of the delegate type.`

### To Reproduce
1. Using ASP.NET Core 3.0 Preview 5
2. Create a default API template and remove AddNewtonsoftJson()
3. Change `IEnumerable<int>` in ValueController to `IEnumerable<Guid>` or `IEnumerable<Guid?>` and the returned data accordingly.
4. Test the API

### Expected behavior
`Guid` and `Guid?` should serialized into strings or null.

_Copied from original issue: aspnet/AspNetCore#10033_

**Comment by Eilon** [comment]
_From @pranavkm on Tuesday, 07 May 2019 16:18:26_

@Eilon could you transfer this to https://github.com/dotnet/corefx?

**Comment by ahsonkhan** [comment]
cc @steveharter, @layomia - what do we need to do to enable Guid support?

**Comment by nguyenquyhy** [comment]
May I know if Guid support is planned for .NET Core 3.0 release?
We are building a new application on 3.0 preview and are planning to migrate our existing applications from 2.2 to 3.0 once 3.0 is released, so we would like to know if we have to stick with JSON.NET.

**Comment by ahsonkhan** [comment]
> May I know if Guid support is planned for .NET Core 3.0 release?

Yes, it is. You should be able to serialize/deserialize `Guid`. We'll try to get it in for preview6. Thanks

**Comment by joshfree** [comment]
@JeremyKuhne could you grab this one since you're also working on the EnumConverter?

**Comment by JeremyKuhne** [comment]
> could you grab this one 

Sure, on it.
