### ISSUE TITLE
Add Convert.ToByte(value, fromBase) overload for ReadOnlySpan<char>

### ISSUE THREAD

**Issue by MarcusWichelmann** [dotnet/corefx#37504]
I'm not sure, what your common practice regarding adding Span-ified overloads to old framework methods is, but here is a case, where one would be very handy:

There is a `Convert.ToByte(string? value, int fromBase)` method which I'm calling like that:
```C#
public static byte[] FromHexString(ReadOnlySpan<char> hex)
{
    if (hex.Length % 2 != 0)
        throw new ArgumentException("Odd hex string length.", nameof(hex));

    var result = new byte[hex.Length / 2];
    for (int i = 0; i < result.Length; i++)
    {
        result[i] = Convert.ToByte(hex.Slice(i * 2, 2).ToString(), 16);
    }

    return result;
}
```
As you can see, I need to call `ToString()` because the method expects a `string`.

But in the called method, this string is converted back to a `ReadOnlySpan<char>` as soon as the argument checks have passed:
https://github.com/dotnet/corefx/blob/09e2417cd0505df4558535651efb1bbcffdf0c59/src/Common/src/CoreLib/System/Convert.cs#L2187

An overload like `byte ToByte(ReadOnlySpan<char>? value, int fromBase)` would allow users of this method to save this unnecessary conversion and allocation.

What do you think about adding this overload to this method (and maybe other methods in this class)?

**Comment by FiniteReality** [comment]
`byte.TryParse` and `byte.Parse` accept a ROS<char> and also accepts a NumberStyle and IFormatProvider, which you can use to specify that the input number is hexadecimal. You'd probably be better off using those instead of `Convert.ToByte`.

**Comment by GrabYourPitchforks** [comment]
@MarcusWichelmann Is the suggestion at https://github.com/dotnet/corefx/issues/37504#issuecomment-490441358 sufficient for your scenario? It's the canonical way of parsing hex strings.

Some sample usage within the Framework source code:

 * https://referencesource.microsoft.com/mscorlib/system/runtime/remoting/soapinteroptypes.cs.html#978
 * https://referencesource.microsoft.com/System/net/System/Net/HttpListenerRequestUriBuilder.cs.html#297
 * https://referencesource.microsoft.com/System.Web/UI/Page.cs.html#2160

**Comment by MarcusWichelmann** [comment]
@GrabYourPitchforks Yeah, looks like this is a great alternative and solves my issue. Thank you @FiniteReality!

I'm not sure if it would still make sense to enhance the `Convert` methods, too. If you think it does not, feel free to close this issue.
