### ISSUE TITLE
HTTP2: Response trailers not loaded with some gRPC calls

### ISSUE THREAD

**Issue by JamesNK** [dotnet/corefx#37511]
HttpClient is sometimes not loading response trailers into `HttpResponseMessage.TrailingHeaders`. I've confirmed that the server is returning trailers in Wireshark.

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (  Expected: <Grpc.Core.RpcException>
  But was:  <System.InvalidOperationException: Response did not have a grpc-status trailer.
   at Grpc.NetCore.HttpClient.Internal.GrpcCall`2.GetStatusCore(HttpResponseMessage httpResponseMessage) in C:\Development\Source\grpc-dotnet\src\Grpc.NetCore.HttpClient\Internal\GrpcCall.cs:line 426
```

This exception comes from the managed gRPC client. The response content stream has been completely read yet the expected trailer is missing.

Repo:

1. git clone https://github.com/JamesNK/grpc-dotnet.git
2. git checkout jamesnk/fix-interoptests
3. dotnet run -p testassets\InteropTestsNativeServer
4. dotnet run -p testassets\InteropTestsClient --server_port 8070 --test_case unimplemented_method

This failure effects 4 test cases (replace `--test_case XXX` with name):
* empty_stream
* unimplemented_method
* unimplemented_service
* status_code_and_message

The bug might be related to responses with an empty body.

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-011799
 Commit:    3816213dde

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-011799\

Host (useful for support):
  Version: 3.0.0-preview6-27707-07
  Commit:  c9e7f134dc
```

// @wfurt @karelz

**Comment by wfurt** [comment]
I did quick check and it seems like the trailers are not valid: 
rfc7540: 8.1.2.1.  Pseudo-Header Fields
>  Pseudo-header fields MUST NOT appear in trailers.  Endpoints MUST treat a request or response that contains  undefined or invalid pseudo-header fields as malformed

The trailer I see contains `:status 200`
<img width="1226" alt="trailers" src="https://user-images.githubusercontent.com/14356188/57481987-4d3c5980-7258-11e9-9707-d92dbc5a980a.png">

**Comment by wfurt** [comment]
It seems like server sends RST_STREAM before sending back data or trailers:

![image](https://user-images.githubusercontent.com/14356188/57483659-2bdd6c80-725c-11e9-9057-da2bdb385cfe.png)

I need to check if we throw properly but reading content should fails.

**Comment by wfurt** [comment]
Also the flags on response headers is 5 -> EndStream is set. Because of that, we return empty stream and rest of the frames are discarded.

**Comment by JamesNK** [comment]
There were 4 test cases that were failing. Lets make sure we say which one we are referring to, because I think there might be some different issues going on here.

empty_stream:

![image](https://user-images.githubusercontent.com/303201/57487374-8500db00-7304-11e9-8aec-64768ccb89f9.png)

I debugged this one further and the trailers are coming back in HttpResponseMessage.Headers!

![image](https://user-images.githubusercontent.com/303201/57487489-d5783880-7304-11e9-80d4-87d295561bd2.png)

The gRPC spec does not mention trailers sometimes being returned in the header: https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#responses

Is it a bug in the HTTP2 C Core server is returning or a bug in HttpClient misinterpreting the HTTP2? If it is a bug in C Core then I can get the gRPC people involved.

**Comment by JamesNK** [comment]
![image](https://user-images.githubusercontent.com/303201/57488009-060ca200-7306-11e9-9cf3-d821e4a2a519.png)

Hmmm, it does seem like the C Core gRPC server returns the headers (blue) and trailers (red) together.

**Comment by JamesNK** [comment]
> Also the flags on response headers is 5 -> EndStream is set. Because of that, we return empty stream and rest of the frames are discarded.

Maybe dumb question: How are you deciding if headers returned are headers or trailers? If response headers have EndStream set to true, should that make them response headers?

**Comment by JamesNK** [comment]
By the way, I have updated the gRPC client using HttpClient to now pass these tests. It looks for trailers in HttpResponseMessage.TrailingHeaders and then falls back to HttpResponseMessage.Headers.

I'll leave this issue open so we can confirm if HttpClient is processing HTTP2 headers/trailers correctly and putting them in the correct location.

**Comment by wfurt** [comment]
The sequence is Headers(+Continuation), data, Headers.
Any header received after initial Header block with EndOFHeaders will go to TrailingHeaders collection. 

Note, that if you do have data, you need to read them until end of stream and only after that you will be able to access trailing headers. If you do before, you will get empty collection. 

Does it make sense?

**Comment by JamesNK** [comment]
Yeah sure. I think what is happening here is a quirk of some gRPC implementations to optimize performance by returning one HEADERS frame instead of two.

I think the `HttpResponseMessage.TrailingHeaders` documentation should be clear about what constitutes a trailing header. Other HTTP/2 servers may do similar optimization for empty responses and it is an easy place for confusion when using this API.

Where do the docs live? Currently there is nothing on it - https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpresponsemessage.trailingheaders?view=netcore-3.0

**Comment by wfurt** [comment]
I'm not sure if text was written yet. The optimization would make sense, especially when values are known when server start sending response. To rephrase my reply, you would get TrailingHeaders collection only if headers were received in distinct header block. 

There was lot of conversation if we should have separate property or put everything to Headers, but I don't remember all the details. It seems like you will have to check both collections.

**Comment by JamesNK** [comment]
I think HttpClient is behaving correctly here. Closing.
