### ISSUE TITLE
Add DisplayUnits property to EventCounter and friends

### ISSUE THREAD

**Issue by sywhang** [dotnet/corefx#37510]
`IncrementingEventCounter` and `IncrementingPollingCounter` were introduced as new types that tracks metrics that are always incrementing and therefore is better reported as a rate. We added the property `DisplayRateTimeScale`. 

This proposal is to add one more property: `string DisplayUnits`.

To track rates, the units of the metric being tracked is often needed. For example, "Allocated bytes per second" could be any of "bytes / sec", "KB / sec", "MB / sec" or "GB / sec", so some kind of cue from the writer is needed for the reader. Having the `DisplayUnits` would allow the writer to create this counter as:
```
IncrementingEventCounter allocatedBytesCounter = new IncrementingEventCounter("Bytes Allocated", myEventSource)
{
    DisplayName = "Rate of Bytes Allocated",
    DisplayUnits = "MB",
    DisplayRateTimeScale = TimeSpan.FromSeconds(1)
};
```

as opposed to what needs to be done currently to implement such a counter:
```
IncrementingEventCounter allocatedBytesCounter = new IncrementingEventCounter("Bytes Allocated", myEventSource)
{
    DisplayName = "Rate of Bytes Allocated",
    DisplayRateTimeScale = TimeSpan.FromSeconds(1)
};
allocatedBytesCounter.AddMetadata("DisplayUnits", "MB");
```

cc @noahfalk @tommcdon

[EDIT] 
This property would be useful to `EventCounter` and `PollingCounter` as well, so I'm now proposing that it be added to `DiagnosticCounter` which is the parent class for `EventCounter` and friends.

**Comment by noahfalk** [comment]
We should define the exact type(s) this property is being added to. I assume there is a similar scenario for our non-incremeting counters as well? Ie:

GC Heap Size (MB) vs GC Heap Size (KB)

**Comment by sywhang** [comment]
Thanks @noahfalk! I updated the description above

**Comment by terrajobst** [comment]
It's not entirely clear what the API is. We assume you're proposing to add this property:

```C#
namespace System.Diagnostics.Tracing
{
    public partial abstract class DiagnosticCounter
    {
        public string DisplayUnits { get; }
    }
}
```

Presumably the units aren't supposed to be parsed or localized, correct? If so, we should make that clear in documentation. The prefix `Display` looks sufficient, though.

**Comment by noahfalk** [comment]
Answers:

> Looks like DisplayRateTimeScale is on the derived types, presumably that's intentional?

Correct. Only some of counters are expected to be displayed as a rate, so only those counters have DisplayRateTimeScale.

> Presumably the units aren't supposed to be parsed or localized, correct? If so, we should make that clear in documentation. The prefix Display looks sufficient, though.

Correct, no intention for parsing or localization on these strings.

> You currently cannot represent whether the unit is a prefix (e.g. "$") or a suffix (e.g. "MB/s"). Would you need this?

We don't believe we need it. The expectation is to display a composite string label such as: "Allocation Rate (MB/s)" or "Bank Account Balance ($)". In the UIs we are building or anticipate others will build the numeric value is displayed in a different column of a table or in a graphical chart.

> Since this API is in System.Private.Corlib we'll need to clarify nullability. If the value is an empty string, it's encoded correctly (non-null), if null is valid, we should add a question mark. What about the existing DisplayName?

If there is a pattern in this space or a recommendation from you guys I think we'd be happy to follow it. The DisplayXXX fields don't feel like something where a user would meaningfully distinguish between null and empty string. Both of those feel like an indication that the counter provider has opted not to provide a default display string. Right now the implementation does expose null, but we could easily change it to initialize those properties to an empty string by default.


HTH. Thanks @terrajobst !

**Comment by terrajobst** [comment]
Looks like we're OK with this. The default return value would be `string.Empty`.

```C#
namespace System.Diagnostics.Tracing
{
    public partial abstract class DiagnosticCounter
    {
        public string DisplayUnits { get; }
    }
}
```
