### ISSUE TITLE
CompareInfo.IndexOf() returns different values on Linux and Windows

### ISSUE THREAD

**Issue by KashMoneyMillionaire** [dotnet/corefx#37526]
The following code behaves differently on Linux and Windows. Windows returns 0 while Linux returns -1. I except 0 to be returned on both based on my understanding of the `IgnoreSymbols` flag.

```csharp
System.Globalization.CompareInfo info = System.Globalization.CultureInfo.CurrentCulture.CompareInfo;
int index = info.IndexOf("Mary", "♪Mary", System.Globalization.CompareOptions.IgnoreSymbols);
System.Console.WriteLine(index);
```

I've looked at #31103 and I don't believe that using `CompareOptions.Ordinal` will work here (mostly because it is an invalid flag combination).

`char.IsSymbol('♪')` returns true for both Windows and Linux.

System Info:
Runtime: .NET Core 2.1 on both
OS: Windows 10 and Ubuntu 18.04

**Comment by danmosemsft** [comment]
@tarekgh

**Comment by tarekgh** [comment]
@KashMoneyMillionaire thanks for reporting the issue. On Linux we use ICU for the string collations in general. I have investigated this specific case and I am seeing the underlying issue is coming from ICU. I have started communicating this to the ICU. just to let you know, if you do just string comparison 

```C#
CompareInfo info = CultureInfo.CurrentCulture.CompareInfo;
int result = info.Compare("Mary", "♪Mary", CompareOptions.IgnoreSymbols);
System.Console.WriteLine(result);
```

This will successfully return 0 which means the 2 strings are equals. But when doing search (i.e. IndexOf), ICU return the result the .NET is reporting. 

Per that, I am going to close the issue here and I'll try to update when hearing back from ICU. Feel free to respond back with any question.

**Comment by KashMoneyMillionaire** [comment]
@tarekgh Thanks for the informed reply. I had a feeling it was down at the ICU level, but I could never figure out how to confirm that. And good to know that the Compare works correctly. 

Is there some documentation/source code showing how the CoreClr calls into the ICU? I'm curious of the mechanism here. Additionally, is there some bug/tracking number for the ICU that I could monitor this on? I'm not sure if they have a public bug tracking list, so there may not be one.

**Comment by tarekgh** [comment]
> Is there some documentation/source code showing how the CoreClr calls into the ICU? I'm curious of the mechanism here

You may look at the code how we are doing that:
https://github.com/dotnet/coreclr/blob/e985b20260631c98a09f08cb67e93d690a6ffd0b/src/System.Private.CoreLib/shared/System/Globalization/CompareInfo.Unix.cs#L263
https://github.com/dotnet/coreclr/blob/e985b20260631c98a09f08cb67e93d690a6ffd0b/src/corefx/System.Globalization.Native/pal_collation.c#L465

> is there some bug/tracking number for the ICU that I could monitor this on? I'm not sure if they have a public bug tracking list, so there may not be one.

I sent it to ICU support group through the email just to get them acknowledge the issue. You may subscribe to this group "ICU support mailing list <icu-support@lists.sourceforge.net>" to get all ICU raised issues. Also they have place to log bugs for them here https://unicode-org.atlassian.net/projects/ICU/issues
