### ISSUE TITLE
Switch OS X process information retrieval over to use sysctl

### ISSUE THREAD

**Issue by sokket** [dotnet/corefx#3753]
Currently, OS X uses the platform-specific `proc_*` calls to retrieve process and thread information. By moving these calls over to use `sysctl`, we can support many more platforms (such as FreeBSD).

**Comment by dasMulli** [comment]
I've looked into this a bit and i see two potential issues:
First, querying the running threads seems to be only possible using `proc_pidinfo` with `PROC_PIDLISTTHREADS` as parameter (OS X only). FreeBSD exposes the MIB flag value `KERN_PROC_INC_THREAD` which is not present on OS X.
Additionally, it seems that some process detail information such as the process executable path and argument strings is not restricted to processes belonging to the same user.

Another affected feature that is currently used is determining the executable path.
Querying the process path via `sysctl()` is only possible using `KERN_PROCARGS` or `KERN_PROCARGS2`, which cannot be accessed without the proper permission. Access is only granted when the executable has the SUID bit enabled and is owned by root. The `ps` command line tool shipping with OS X uses this mechanism and fails to display the process path / arguments when built manually or copied over from /bin and stripped of the SUID bit or root ownership. `libproc` wraps the pretty much undocumented `proc_info` system call into to xnu kernel, which allows querying only for the executable path of a PID or listing threads to all unprivileged processes.

**Comment by Priya91** [comment]
The current implementation works on OSX, and there's no motivation to change this. If freebsd requires support, an implementation using sysctl can be explored, currently there's no requirement for this.
