### ISSUE TITLE
[System.Text.Json] Deserializing object without parameterless ctor results in null-ref

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#37537]
I'm not sure if there are plans to support objects without parameterless ctors. However, attempting to deserialize an object without one results in a null ref rather than a meaningful error:

```C#
class Program
{
    static void Main(string[] args)
    {
        var instance = new NoParameterlessCtor(10);
        var json = JsonSerializer.ToString(instance);

        Console.WriteLine(JsonSerializer.Parse<NoParameterlessCtor>(json));
    }
}

class NoParameterlessCtor
{
    public NoParameterlessCtor(int id)
    {
        Id = id;
    }

    public int Id { get; set; }
}
```

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Text.Json.Serialization.JsonSerializer.HandleStartObject(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
```

**Comment by ahsonkhan** [comment]
I don't think custom ctors is supported atm. cc @steveharter

**Comment by pranavkm** [comment]
@ahsonkhan could we improve the error message for the current release? Seeing a null ref doesn't help the user understand that the scenario isn't supported.

**Comment by ahsonkhan** [comment]
> could we improve the error message for the current release

Agreed. I am sure we can improve the error messaging for non-supported scenarios, overall. I'll let @steveharter chime in regarding that.

**Comment by vcsjones** [comment]
Wrote #37545 to track improving error messaging.
