### ISSUE TITLE
Comparing Utf8JsonReader to default instance with the == operator

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#37534]
The `Utf8JsonReader` is a ref struct and it's possible that someone might pass around a default instance. Currently, there is no good way for the receiver to check if the `Utf8JsonReader` is default (equivalent to null for a class, or "not set").

One solution is for the reader to implement the == operator. However, this has concerns around what the semantics of "equality" mean here. What does comparing two non-default instances of the reader mean?

Another solution is for the reader to provide an `IsDefault` property that can be polled instead. This may be less discoverable, but has clear semantics tied to the usage scenario.

## API Proposal:
```C#
    public ref partial struct Utf8JsonReader
    {
        public bool IsDefault { get; }

        // OR the following, though the semantics need to be well-defined:
       public static bool operator ==(Utf8JsonReader left, Utf8JsonReader right);
       public static bool operator !=(Utf8JsonReader left, Utf8JsonReader right);
    }
```

As an aside, since `Utf8JsonReader` is a ref struct, it cannot implement `IEquatable`, like any ref struct.

## Usage is relatively straightforward:
```C#
private static void ValidateAndReadOnce(ref Utf8JsonReader reader)
{
    if (reader.IsDefault)
    {
        throw new Exception("Reader was not set");
    }
    reader.Read();
}
```

**There is still a question whether such an API is absolutely necessary.** Calling `.Read()` on a default instance of `Utf8JsonReader` would return false, so it may not be necessary for the caller to guard against that. In that case, such an API wouldn't be necessary.

```C#
// Current behaviour of API calls to the Utf8JsonReader on a default instance.
[Fact]
public static void DefaultUtf8JsonReader()
{
    Utf8JsonReader json = default;

    Assert.Equal(0, json.BytesConsumed);
    Assert.Equal(0, json.TokenStartIndex);
    Assert.Equal(0, json.CurrentDepth);
    Assert.Equal(JsonTokenType.None, json.TokenType);
    Assert.Equal(default, json.Position);
    Assert.False(json.HasValueSequence);
    Assert.True(json.ValueSpan.SequenceEqual(default));
    Assert.True(json.ValueSequence.IsEmpty);

    Assert.Equal(0, json.CurrentState.BytesConsumed);
    Assert.Equal(default, json.CurrentState.Position);
    Assert.Equal(0, json.CurrentState.Options.MaxDepth);
    Assert.False(json.CurrentState.Options.AllowTrailingCommas);
    Assert.Equal(JsonCommentHandling.Disallow, json.CurrentState.Options.CommentHandling);

    Assert.False(json.Read());

    json = default;
    JsonTestHelper.AssertThrows<InvalidOperationException>(json, (jsonReader) => jsonReader.TextEquals("".AsSpan()));
    JsonTestHelper.AssertThrows<InvalidOperationException>(json, (jsonReader) => jsonReader.TextEquals(default(ReadOnlySpan<char>)));
    JsonTestHelper.AssertThrows<InvalidOperationException>(json, (jsonReader) => jsonReader.TextEquals(default(ReadOnlySpan<byte>)));
}
```

What do others think? Folks from asp.net, would such an API be useful for you anywhere?
- **Should we have such an API and if so which approach?**
   - IsDefault or == operator?

I know that you have guards on the `Read` method itself, which is a more appropriate solution since it guards against a default instance being passed in, for free. For example:
https://github.com/aspnet/AspNetCore/blob/9fae14a92650175b2c9ef73d2ab605b52c2b18e4/src/SignalR/common/Shared/SystemTextJsonExtensions.cs#L11-L19

cc @jeffschwMSFT, @bartonjs, @steveharter, @joshfree, @GrabYourPitchforks, @KrzysztofCwalina, @BrennanConroy, @rynowak

**Comment by stephentoub** [comment]
How would IsDefault be implemented? From a quick glance at the ctor, it seems like you could pass default for all arguments and it would be a valid construction, and the only state that wouldn't be default would be the max depth as an implementation detail. Is that right? So you'd use that, and if we ever changed that default, you'd use another bool to track construction?

**Comment by ahsonkhan** [comment]
> How would IsDefault be implemented?

I was relying on having some field we could leverage that would be different between a `default` instance and one created with `new Utf8JsonReader(default, default, default)`.

> So you'd use that, and if we ever changed that default, you'd use another bool to track construction?

Yep. As you observed, that's the only field we **could** use.

**Comment by terrajobst** [comment]
We certainly don't want the comparison operators as they feel hard to define. `IsDefault` feels OK & consistent, but we're unsure how much value this adds. Why can't the receive just read? Why is the validation necessary? Why is the `Try`-pattern not sufficient?
