### ISSUE TITLE
[System.Text.Json] JsonIgnoreAttribute does not apply to complex type properties

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#37536]
Scenario:

```C#
class Program
{
    static void Main(string[] args)
    {
        var ignored = new JsonIgnored
        {
            Prop1 = "foo",
            Prop2 = new ComplexType {  Property = "foo" },
            Id = 10,
        };

        Console.WriteLine(JsonSerializer.ToString(new object[] { ignored }));
    }
}

class JsonIgnored
{
    [JsonIgnore]
    public string Prop1 { get; set; }

    [JsonIgnore]
    public ComplexType Prop2 { get; set; }

    public int Id { get; set; }
}

class ComplexType
{
    public string Property { get; set; }
}
```

Output:

```
[{"Prop2":{"Property":"foo"},"Id":10}]
```

`Prop1` gets ignored, however `Prop2` does not even though both have `JsonIgnoreAttribute` applied.

**Comment by pranavkm** [comment]
This isn't entirely blocking, but it seems like a pretty nasty bug to run in to.

cc @steveharter

**Comment by MarcoRossignoli** [comment]
I did some debug and seems that missing some check 
https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.HandleObject.cs#L105 for serialization
https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/src/System/Text/Json/Serialization/JsonPropertyInfo.cs#L176 for deserialization
for serialization I think could be ok a simple check `ShouldSerialize`
for deserialization is a bit more complex, I think we should check if prop/field is inside a type with `Ignore` attribute.
I could give it a try if I'm on correct way(first look into this namespace)

**Comment by JeremyKuhne** [comment]
#37586 should have fixed this.

**Comment by MarcoRossignoli** [comment]
@JeremyKuhne as I said on PR @steveharter PR fix issue, but at the moment PR is still open

**Comment by JeremyKuhne** [comment]
> but at the moment PR is still open

My bad, totally misread this. 😊

**Comment by MarcoRossignoli** [comment]
Oh...merged now some hour ago
