### ISSUE TITLE
[System.Text.Json] Consider making JsonPropertyNameAttribute.Name readonly

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#37552]
Constructing `JsonPropertyName` requires specifying the property name. There isn't a very good reason to make the property settable:

```C#
[JsonPropertyName("some-name" Name = "ChangedMyMind")]
public string Name { get; set; }
```

**Comment by pranavkm** [comment]
@steveharter possible API design change so would be useful to address this sooner if it's something you would like to fix.

**Comment by ahsonkhan** [comment]
**Current API shape:**
https://github.com/dotnet/corefx/blob/0b8a72e7c8b57a753dbeab762b3967ecda6d47c7/src/System.Text.Json/ref/System.Text.Json.cs#L371-L376

```C#
[System.AttributeUsageAttribute(System.AttributeTargets.Property, AllowMultiple = false)]
public sealed partial class JsonPropertyNameAttribute : System.Text.Json.Serialization.JsonAttribute
{
    public JsonPropertyNameAttribute(string propertyName) { }
    public string Name { get { throw null; } set { } }
}
```

**Proposal:**
```C#
    public string Name { get { throw null; } }
```

**Question:** Should the `Name` property match the parameter name `propertyName` or vice versa?

**Comment by ahsonkhan** [comment]
Based on the discussion today, change the `propertyName` ctor parameter to `Name` to match the string property.

**Comment by paulomorgado** [comment]
XML has `System.Xml.Serialization.XmlElementAttribute` with an `ElementName` property.

I would prefer:

```
[System.AttributeUsageAttribute(System.AttributeTargets.Property, AllowMultiple = false)]
public sealed partial class JsonPropertyAttribute : System.Json.Serialization.JsonAttribute
{
    public JsonPropertyNameAttribute(string propertyName) { }
    public string PropertyName { get { throw null; } set { } }
}
```

**Comment by ahsonkhan** [comment]
> XML has `System.Xml.Serialization.XmlElementAttribute` with an `ElementName` property.

The distinction here is that `XmlElementAttribute` covers a few different concepts, whereas `JsonPropertyNameAttribute` is solely about the name itself. I am not sure if there would be a need, in the future, to extend `JsonPropertyNameAttribute` to include anything that isn't related to customizing the name. 

Hence, I don't see the name change buying us all that much to justify the API churn.

**Comment by paulomorgado** [comment]
A `JsonPropertyAttribute` could be an explicit way of saying the opposite of `JsonIgnoreAttribute`.

`JsonPropertyAttribute` would, optionally have a `Name` property.
