### ISSUE TITLE
Question about strange parameter name in ArgumentException

### ISSUE THREAD

**Issue by sungam3r** [dotnet/corefx#37566]
Hi. I'm not sure that the question refers to this repository. I use .NET Core 2.2 and throw exception:
```c#
throw new ArgumentException("blablabla", "super-duper");
```

Visual Studio 2017 shows me such dialog:
![image](https://user-images.githubusercontent.com/21261007/57485104-8524ba80-72b3-11e9-8cf9-ec8d7fe5fc28.png)

In watch window I see normal message with parameter name:
![image](https://user-images.githubusercontent.com/21261007/57485191-b56c5900-72b3-11e9-8d5c-407371c8ae99.png)

Call  to
```c#
throw new ArgumentNullException("super-duper", "blablabla");
```
behaves similarly.

So, the question is - what is **Arg_ParamName_Name** ?

![image](https://user-images.githubusercontent.com/21261007/57485382-42171700-72b4-11e9-9a6a-50523fe3c877.png)

**Comment by Clockwork-Muse** [comment]
[It's being used to add the formatting to the message](https://github.com/dotnet/coreclr/blob/9773db1e7b1acb3ec75c9cc0e36bd62dcbacd6d5/src/System.Private.CoreLib/shared/System/ArgumentException.cs#L77-L90):

```csharp
 override string Message
{
	get
	{
		string s = base.Message;
		if (!string.IsNullOrEmpty(_paramName))
		{
			string resourceString = SR.Format(SR.Arg_ParamName_Name, _paramName);
			return s + Environment.NewLine + resourceString;
		}
		else
			return s;
	}
}
```

...although I guess I'm a little surprised the whole thing isn't formatted in one go...

**Comment by danmosemsft** [comment]
Yeah I can only guess that VS is displaying the `message` field content, or `base.Message`. It is odd that ArgumentException does not format it in the constructor, but probably not particularly worth changing now as it could break derived classes.

Also in VS2019 it seems OK so maybe VS debugger fixed something:
![image](https://user-images.githubusercontent.com/6385855/57496196-85f32780-7286-11e9-9bac-91bc6c0c9bdd.png)
