### ISSUE TITLE
Console.BufferHeight in netcoreapp2.1 raise Exception PlatformNotSupportedException in Ubuntu

### ISSUE THREAD

**Issue by moh-hassan** [dotnet/corefx#37579]
I have a Console application build in dotnetcorapp2.1. It's running fine on Windows.

When trying to run on Ubuntu it raise an Exception error:

>System.PlatformNotSupportedException: Operation is not supported on this platform. at System.ConsolePal.set_BufferHeight(Int32 value)

That is because This line:

     Console.BufferHeight = Int16.MaxValue - 1;

This [document ](https://docs.microsoft.com/en-us/dotnet/api/system.console.bufferheight?view=netcore-2.2)didn't mention the limitation that I take into account for Console.BufferHeight

What is the limitation of Console.BufferHeight (and BufferWidth) on Ubuntu?

**Comment by danmosemsft** [comment]
@moh-hassan these are not supported on Unix - you're correct, the docs should state that. @carlossanlop maybe you could make sure there's an issue in https://github.com/dotnet/dotnet-api-docs to note the Unix specific behaviors on the Console methods/properties, then we can close this.

**Comment by moh-hassan** [comment]
Thanks @danmosemsft  for reply.

As you said, I find some methods in the class [ConsolePal](https://github.com/dotnet/corefx/blob/007571b90c3cc555cd30f3b467b87c22f9f665e0/src/System.Console/src/System/ConsolePal.Unix.cs) not supported.

[ConsolePal.Unix.cs](https://github.com/dotnet/corefx/blob/007571b90c3cc555cd30f3b467b87c22f9f665e0/src/System.Console/src/System/ConsolePal.Unix.cs)
 [301 ](https://github.com/dotnet/corefx/blob/007571b90c3cc555cd30f3b467b87c22f9f665e0/src/System.Console/src/System/ConsolePal.Unix.cs#L301)public static int BufferWidth
 [307 ](https://github.com/dotnet/corefx/blob/007571b90c3cc555cd30f3b467b87c22f9f665e0/src/System.Console/src/System/ConsolePal.Unix.cs#L307)public static int BufferHeight
 [313 ](https://github.com/dotnet/corefx/blob/007571b90c3cc555cd30f3b467b87c22f9f665e0/src/System.Console/src/System/ConsolePal.Unix.cs#L313)public static void SetBufferSize(int width, int height)
 [328   ](https://github.com/dotnet/corefx/blob/007571b90c3cc555cd30f3b467b87c22f9f665e0/src/System.Console/src/System/ConsolePal.Unix.cs#L328)public static int WindowLeft
 340 public static int WindowWidth
 350  public static int WindowHeight
 386 public static void SetWindowPosition(int left, int top)
 391  public static void SetWindowSize(int width, int height)

 and others

**Comment by carlossanlop** [comment]
@wtgodbe who owns System.Console. If you add this missing information to the  /// comments in corefx, I can take care of porting it to dotnet-api-docs with our automatic tool.

**Comment by wtgodbe** [comment]
I've created https://github.com/dotnet/dotnet-api-docs/pull/2433

**Comment by danmosemsft** [comment]
I will close this issue then - feel free to update the linked issue.
