### ISSUE TITLE
Question : How to use System.Memory with pinvoke? 

### ISSUE THREAD

**Issue by dotChris90** [dotnet/corefx#37577]
Hello dotnet team,

I have an native DLL which has a function with following signature.

int function(void** ptr)

The Marshalling of int is easy. But the void** drives me crazy. In C++ you simply init a variable, put it as parameter and the function write the Adresse of an array so Adresse of Adresse of first element into it.

Since the new span and memory classes was released my hope was that there is a way to have a C# "view" of this unmanaged array. A view so the memory is not copied a second time. the size of array is known (want to mention it). 

I know the usual way to do this is pass managed array and C++ shall write into it but unfortunately the dll was not written by me.

Is there the possibility to create a c# view of this unmanaged array or a walk around?

thanks for your time.

**Comment by danmosemsft** [comment]
@AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
@dotChris90, Thanks for the question. The easiest way to perform this kind of operation is as demonstrated in the code below. Support for `Span<T>` as a first class citizen for marshalling has been discussed before and perhaps will eventually get done, it is definitely on our backlog.

The below way of doing this converts to a `Span<T>` very quickly, but please do remember to free the memory after use as it is not being managed by the runtime.

C#
``` csharp
private class PInvokeNative
{
    [DllImport(nameof(PInvokeNative))]
    public static extern int PopulateWithData(ref IntPtr r);
}

static unsafe void Main(string[] args)
{
    IntPtr r = IntPtr.Zero;
    int size = PInvokeNative.PopulateWithData(ref r);
    var rs = new Span<int>(r.ToPointer(), size / sizeof(int));
    foreach (var i in rs)
    {
        Console.WriteLine(i);
    }
}
```

C/C++
``` C
EXPORT int PopulateWithData(void **d)
{
    int size = sizeof(int) * 10;
    int *ib = (int *)malloc(size);

    int *t = ib;
    for (int i = 10; 0 < i; --i)
        *t++ = i;
    
    *d = ib;
    return size;
}
```

Output:
```
$ dotnet run
10
9
8
7
6
5
4
3
2
1
```

**Comment by dotChris90** [comment]
@AaronRobinsonMSFT thanks for answering. looks promising. just one last question.

is it possible using memory instead of span? since span is stack only data type. just ask since span can not be a field of object. :)

**Comment by AaronRobinsonMSFT** [comment]
@dotChris90 I don't fully understand your scenario, but I am unclear why that would be needed in this case. The memory is native so the `Span<T>` is purely a view over the data, there is no additional allocation merely providing a safe access API. I would store the `IntPtr` as a private field and access it as desired from within the class. Exposing that as memory to others would probably necessitate the `Memory<T>` type, but I am not entirely sure of your scenario.

**Comment by dotChris90** [comment]
Oh Sorry - maybe it is best to explain the scenario to avoid confussion but sorry it is a little bit longer ....

I found out that dotnet community (thanks to all of you!) started to extend the System.Numerics namespace with a tensor class just like numpy array class see https://docs.microsoft.com/en-us/dotnet/api/system.numerics.tensors.densetensor-1?view=dotnet-plat-ext-3.0. This class using a Memory< T > as buffer to store any array independent of its dimension. If I remember well it was said that this tensor class shall be the beginning for a standarized tensor in .NET and can be used to exchange tensors between libraries (Tensorflow.Sharp, ML.NET, Accord.NET, ...). 

There also is this C++ lib "Arrayfire" (https://github.com/arrayfire/arrayfire) which seems to be often used in big data and so on for performance reason. It uses a special array/tensor class which has a underlying "void*" as buffer. The pinvoke system already works (mostly) fine with it and there exist a arrayfire-dotnet wrapper. The problem is - if you want to combine it with other .NET packages - you can not easily map this complex, unmanaged tensor class to managed .NET (afaik). You usual have to copy the arrays memory a second time as array e.g. double[] and give this array to .NET package. To avoid copy arrayfire has a API called "af_get_raw_pointer" which gives you the underlying adresse of the buffer "void*" (so thats the void** parameter). 

My idea now was to combine both. I though if it is possible to create an unmaned arrayfire, get the underlying buffer (so the "void**" parameter), create a view as Memory< T > and set this Memory < T > in a System.Numerics.Tensor.DenseTensor object from dotnet. In this way there exist just one memory area (the buffer of arrayfire) and a Memory < T > view which is a field of DenseTensor object. 

Was just an idea / mind experiment and no critical situation. :) btw the span seems to work already. thanks.

**Comment by dotChris90** [comment]
solved by implementing Memorymanager see issue #37618.
