### ISSUE TITLE
Regex Capture ReadOnlySpan<char> Why isn't this a thing yet? 3.0+

### ISSUE THREAD

**Issue by electricessence** [dotnet/corefx#37589]
https://github.com/dotnet/corefx/blob/master/src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Capture.cs

It's seems like such a trivial add.  The `Capture` class already contains a reference to the original `Text`.  I actually thought this change would be in the 3.0 release. 

Is this a protective measure?  I obviously can create a span from the capture information, but it seems odd that I have the index and length but can't simply get a ReadOnlySpan<char> from it.

Is this something planned for the future?

**Comment by danmosemsft** [comment]
Span overloads are proposed here https://github.com/dotnet/corefx/issues/24145. It had one round of API review and there was significant feedback there, then no progress was made. If you're interested, you could continue that conversation. If we got a satisfactory conclusion then it would need API approval and then implementation. Note that it would need implementing for the compiled codepath also, which is challenging (it's hand written IL emit)

There is BTW an Escape/Unescape PR https://github.com/dotnet/corefx/pull/32949 which was waiting on API approval as well.

cc @ViktorHofer 

I'll close this in favor of #24145

**Comment by electricessence** [comment]
@danmosemsft thanks for your reply. :)
