### ISSUE TITLE
HttpClient returns OK when Protocol Negotiation fails

### ISSUE THREAD

**Issue by kmcclellan** [dotnet/corefx#37594]
Using `HttpClient` to send a request over a TLS connection results in an erroneous success status code when the connection is terminated due to ALPN failing.

Circumstances:
1) Client machine does not support HTTP/2 (Ubuntu 16.04 out of the box)
2) Server requires HTTP/2 (Apple Push Notification Service)
3) An HTTPS request is initiated with `HttpClient` (.NET Core 2.2)

**Expected**: an exception explaining that the connection was terminated.
**Actual**: request completes with 200 - OK success code.

Code to reproduce:
```c#
// Switch to enable HTTP/2 in .NET Core 2.2
AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);

// Apple Push Notification Service requires HTTP/2
using (var client = new HttpClient
{
    BaseAddress = new Uri("https://api.push.apple.com")
})

// If HTTP/2 is supported, this should return a 404
// If not supported, an exception should be thrown (connection terminated)
using (var response = await client.PostAsync("bad/path", null))
{
    Console.WriteLine($"Response Status Code: {response.StatusCode}");
}
```
Output:
`Response Status Code: OK`

.NET Core 2.2
Ubuntu 16.04

**Comment by wfurt** [comment]
are you sure 200 is not coming from server? What do you get when you run curl -v ? 
Also could you grab 3.0 preview and give it try? HTTP2 is getting to usable state in default handler.

**Comment by kmcclellan** [comment]
Hi, thanks for the quick response. Running a curl is how I discovered the ALPN was failing. I assume it is failing from .NET as well, since when HTTP/2 is "successful" (when I run the same code from Windows) it is a 404.
```
curl https://api.push.apple.com/bad/path -X POST --verbose
*   Trying 17.188.144.31...
* Connected to api.push.apple.com (17.188.144.31) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 597 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: api.push.apple.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: CN=api.push.apple.com,OU=management:idms.group.533599,O=Apple Inc.,ST=California,C=US
* 	 start date: Thu, 14 Mar 2019 17:50:10 GMT
* 	 expire date: Mon, 12 Apr 2021 17:50:10 GMT
* 	 issuer: CN=Apple IST CA 2 - G1,OU=Certification Authority,O=Apple Inc.,C=US
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> POST /bad/path HTTP/1.1
> Host: api.push.apple.com
> User-Agent: curl/7.47.0
> Accept: */*
> 
* GnuTLS recv error (-110): The TLS connection was non-properly terminated.
* Closing connection 0
curl: (56) GnuTLS recv error (-110): The TLS connection was non-properly terminated.
@@4Unexpected HTTP/1.x request: POST /bad/path 
```
As for Core 3.0, I have tested it with preview 5 and the results appear to be the same.

**Comment by wfurt** [comment]
Did you opt-in for HTTP2 ? https://devblogs.microsoft.com/dotnet/announcing-net-core-3-preview-4/

You can also grab daily build https://github.com/dotnet/core-sdk and set Version to 2.0 in HttpRequestMessage. Http2 is no longer opt-in but we will default to 1.1

**Comment by kmcclellan** [comment]
I can confirm this issue does not arise when "opting-in" in HTTP/2 on the `SocketsHttpHandler` in .NET Core 3.0. Doing so appears not even to require OS support for HTTP/2 (`libcurl`). ALPN does not fail and I get the expected 404 - `NotFound`.

**Comment by wfurt** [comment]
good to know. Please open new issue if you bump to any problem with HTTP/2. When 3.0 ships (and next preview), opt-jn will no longer be needed. 
And yes, that was one of the goals for new implementation - to be fully c# and independent on particular OS.
