### ISSUE TITLE
UWP -> PKI Certificates -> System.Net.Http.HttpClient vs Windows.Web.Http.HttpClient

### ISSUE THREAD

**Issue by chrisahill** [dotnet/corefx#37598]
**Use Case**
Building enterprise UWP application which user will enter url to their on premise enterprise server to connect. User has to enter in the url to their server, UWP has to authenticate against that endpoint without knowing anything about the credentials before hand, just like a web browser would.

**Issue**
Depending on your which HTTP client you use, you get a different user experience. When using `Windows.Web.Http.HttpClient` Windows 10 native UI prompt will appear allowing the User to select from multiple certificates. However, using the equivalent call with  `System.Net.Http.HttpClient` having `ClientHandler.ClientCertificateOptions` set to `Automatic` the behavior becomes Windows will select the first matching certificate even if there are multiple matching certs and send that certificate, which will result in the request failing `Error code 403` if that certificate was not the correct one. 

**Responses to obvious questions**
**Q:** Why not just use `Windows.Web.Http` then?
**A:** We are building on an SDK that supports `Xamarin.Android`, `Xamarin.iOS`, `WPF` and `UWP`. According to Microsoft the `System.Net.Http` implementation now uses the same http stack as `Windows.Web.Http` so, when you build cross platform you should just use `System.Net.Http` 
[Demystifying HttpClient APIs in the Universal Windows Platform](https://blogs.windows.com/buildingapps/2015/11/23/demystifying-httpclient-apis-in-the-universal-windows-platform/#jaOQr4K6fwebrvgh.97)

**Argument**
If `System.Net.Http` is uses the same http stack as `Windows.Web.Http` then there needs to be an equivalent way to invoke native windows 10 security prompts when building UWP apps against `System.Net.Http` The below code examples are as close to equivalent as you can write but don't invoke the same behavior.

**Windows.Web.Http**
```C#
var httpClient = new Windows.Web.Http.HttpClient();
var json = await httpClient.GetStringAsync(new Uri("<pki_secured_rest_endpoint>"));
````

**System.Net.Http**
```C#
var httpClientHandler = new System.Net.Http.HttpClientHandler();
httpClientHandler.ClientCertificateOptions = System.Net.Http.ClientCertificateOption.Automatic;
var httpClient = new System.Net.Http.HttpClient(httpClientHandler);
var json = await httpClient.GetStringAsync(new Uri("<pki_secured_rest_endpoint>"));
```

**Additional Resources**
https://stackoverflow.com/questions/31291008/system-net-http-httpclient-vs-windows-web-http-httpclient-what-are-the-main-di

https://devblogs.microsoft.com/dotnet/net-networking-apis-for-uwp-apps/

**Comment by wfurt** [comment]
cc: @bartonjs

**Comment by bartonjs** [comment]
> According to Microsoft the System.Net.Http implementation now uses Windows.Web.Http so, when you build cross platform you should just use System.Net.Http

I don't see that in the linked article.  In fact, it says:

> **Do you need to integrate with native UI for collecting user credentials, control HTTP cache read and write behavior; or pass in a specific SSL client certificate for authentication?**
If yes – then use Windows.Web.Http.HttpClient. [...]

It does say to use System.Net.Http for cross-platform, as the next question/answer, but the first flow question seems to indicate that this is a known delta in the implementations.

**Comment by chrisahill** [comment]
@bartonjs 
>According to Microsoft the System.Net.Http implementation now uses Windows.Web.Http so, when you build cross platform you should just use System.Net.Http

Correct this in not in the article, We learned this through out MVP channels to MS that `System.Net.Http` uses `Windows.Web.Http` making it one implementation that has two API surfaces, `System.Net.Http` and `Windows.Web.Http`

**Comment by karelz** [comment]
Triage: We cannot make the private key in per-user certificate store work easily. The fallback is to use the WinRT APIs directly. Closing.
