### ISSUE TITLE
Return code from msbuild not reflective of test failures

### ISSUE THREAD

**Issue by mmitche** [dotnet/corefx#376]
Has anyone seen this?  If a test run earlier in the corefx build fails, the return code of msbuild is still 0.  I think this is because we're passing ContinueOnError to the Exec task.  Is this intentional?

**Comment by weshaggard** [comment]
Yes that is intentional because we want all the tests to run still even if one fails. I do think we should be still capturing the ExitCode from the test runs however and then using that data to determine if there were any test failures. We aren't currently doing that but @FiveTimesTheFun should be able to add that once he gets his test running work in (or perhaps included with that).

**Comment by mmitche** [comment]
It should be relatively simple to do.  I'll add it and send a PR.

**Comment by mellinoe** [comment]
In the meantime we need to make sure that PR test builds that appear to be succeeding are actually succeeding. I just updated #308 and it appears to have succeeded but further inspection shows that one test case failed.

**Comment by akoeplinger** [comment]
@mmitche you might also want to install the [XUnit Jenkins Plugin](https://wiki.jenkins-ci.org/display/JENKINS/xUnit+Plugin) so you get a nice summary of the tests directly in the Jenkins UI (the test runner needs to output an XML file for the plugin to process, this can be done by passing `/xml <filename>` to xunit.console.exe)

**Comment by mellinoe** [comment]
That sounds great, and would be super useful, IMO.

**Comment by mmitche** [comment]
After looking into this further, the issue might be related to the way the tests are being run.  They're being run using AfterTargets=build for the src\dirs.proj.  It appears that a failure in the AfterTargets does not cause the original build.proj to fail (though dirs.proj fails), which causes msbuild to not report a non-zero exit code.

**Comment by mmitche** [comment]
This is also case with package creation:

  System.Xml.XPath.XDocument NuGet Package -> D:\enlistments\corefx\bin\Debug\Packages\System.Xml.XPath.XDocument.999.999.999-shab388971346.nupkg

System.Xml.XPath.XmlDocument NuGet Package -> D:\enlistments\corefx\bin\Debug\Packages\System.Xml.XPath.XmlDocument.999.999.999-shab388971346.nupkg
D:\enlistments\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.17-prerelease\lib\packages.targets(46,7): error : foo2 [D:\enlistments\corefx\src\dirs.proj]

D:\enlistments\corefx>echo %errorlevel%
0

**Comment by mmitche** [comment]
This apparently is an msbuild bug that has been fixed somewhat recently.

**Comment by weshaggard** [comment]
@mmitche I assume this issue should be closed now after your recent commits?

**Comment by mmitche** [comment]
Yes
