### ISSUE TITLE
[System.Text.Json] Deserializing null array throws null-ref

### ISSUE THREAD

**Issue by gnovack** [dotnet/corefx#37606]
Passing "null" to JsonSerializer.Parse when deserializing arrays throws NullReferenceException.
```
int[] obj = JsonSerializer.Parse<int[]>("null");

//throws:
//Object reference not set to an instance of an object.
//at System.Text.Json.Serialization.JsonSerializer.ApplyObjectToEnumerable(Object value, JsonSerializerOptions options, ReadStack& state, Utf8JsonReader& reader, Boolean setPropertyDirectly)
```

**Comment by danmosemsft** [comment]
Thanks. Interested in offering a PR with test?

**Comment by triynko** [comment]
I have a class with a property that's a list type. It has default set of items in it.  When I Parse<TheType>, it MERGES the items in the array rather than loading them. This duplicates data.  With something so basic non-functioning, this library cannot be used at all.
