### ISSUE TITLE
[System.Text.Json] Serializing class that has array of children of the same class throws StackOverflowException

### ISSUE THREAD

**Issue by oskardudycz** [dotnet/corefx#37610]
As in title: Serializing class that has array of children of the same class throws StackOverflowException.

Simplest repro steps:

```
public class TestClass
{
    public TestClass[] Children { get; set; }
}

var document = new TestClass();
var str = JsonSerializer.ToString(document);
```
I create repository that reproduces this issue: https://github.com/oskardudycz/System.Text.Json.Fail

**Comment by oskardudycz** [comment]
I added also failing test scenario for this case: https://github.com/dotnet/corefx/pull/37611

**Comment by ahsonkhan** [comment]
I believe this is a duplicate of https://github.com/dotnet/corefx/issues/37313. Closing.

Feel free to re-open if you disagree.
