### ISSUE TITLE
Add "InvariantCulture" name

### ISSUE THREAD

**Issue by iSazonov** [dotnet/corefx#37621]
Currently we have empty name for Invariant culture and LCID 127.
LCID is not recommended for use and looks unfriendly in interactive scenarios like _IntelliSense_.
The empty name for Invariant culture looks unfriendly too.

IntelliSense scenario is important but does't work in PowerShell:
```powershell
Get-Culture <tab>    # it is impossible to get Invariant culture because it is empty string
```

### Suggestion

Add "InvariantCulture" name so that we can use it wherever we currently use the empty string name.
Ex.: GetCulture(), GetCultures()

**Comment by Gnbrkm41** [comment]
Why not `CultureInfo.InvariantCulture`?

**Comment by iSazonov** [comment]
@Gnbrkm41 With GetCultures() we can get a list of culture names and name for Invariant culture in the list will be empty string. For use in the Intellisense, we are forced to find a culture with LCID 127 and empty name and replace the name with "InvariantCulture". My request is for this to be implemented in Core.

**Comment by svick** [comment]
Why should this be implemented by `CultureInfo.GetCulture`? Wouldn't it be enough to modify the behavior of `Get-Culture`?

**Comment by iSazonov** [comment]
@svick It is just for the discussion. Of cause the empty name can be replaced in any application. I would like to understand why this is not done or can not be done in Core. 
Note that in Unix "invariant" culture has name "C". I'd expect that in Core "invariant" culture has a name too and the name is "InvariantCulture".

**Comment by tarekgh** [comment]
There is already a name ""x-iv_mathan" you can use which gives the Invariant culture. It is not right to introduce more names or aliases for the culture as this is a source of other problems.  Also, if need to introduce a new name, this should be supported by the underlying OS too, otherwise, we'll start deviate from the OS and add special cases which is not worth to do. 

by that, I am closing this issue. Feel free to reply back if you still have any question.

**Comment by iSazonov** [comment]
@tarekgh Thanks! 
Could you please help with how we could better implement IntelliSense scenario?
1. Get human-friendly culture names (including Invariant Culture)
(DisplayName? TwoLetterISOLanguageName?)
2. By the name (selected by user) get CultureInfo object.

**Comment by tarekgh** [comment]
This depends on the expectation from IntelliSense. If the IntelliSense targeting users who are not familiar with the culture names (e.g. en-US) then you can use EnglishName if it is OK to have all names showed in English. If not, then you have the choice of using DisplayName or NativeName. I prefer using EnglishName if there is no issue with that as DisplayName depends on the available resources which in .NET Core, most of the time would show up in English depending on the current UI Culture and the Windows UI language (if running on Windows). 

If IntelliSense targetting users familiar with culture names, then use that name and let IntelliSense especial case invariant the way you like. I believe IntelliSense show the values and some hint about the value, you can use the culture Name as the value and you can use EnglishName as the hint of this value.

**Comment by iSazonov** [comment]
@tarekgh Thanks for great help!

/cc @mklement0 For information.
