### ISSUE TITLE
Improved performance with Task.WhenAll (ImmutableArray<Task> tasks)

### ISSUE THREAD

**Issue by Therzok** [dotnet/corefx#37629]
Should Task.WhenAll have an extension method for ImmutableArray which avoids copies which are done for the array variant?

**Comment by Clockwork-Muse** [comment]
....I think the larger question would be, "Should we globally add API surface area to avoid copies in the case of `ImmutableXXX` (or otherwise readonly) datastructures", rather than focusing on `Task` specifically.  

Hmmm.... I wonder if we could/should teach Roslyn to emit `ImmutableList<T>`/`ImmutableArray<T>` in the case it can see no modification happens to the collection?

```csharp
// ImmutableArray<int> instead of int[]
var n = new[] { 0, 1 };
CallingSomeMethod(n);
```

**Comment by Therzok** [comment]
@Clockwork-Muse Given how Immutable collections are implemented, a general solution would not work without coordination between corefx and roslyn.

Afaik, Roslyn only optimizes for types in mscorlib, so Immutable collections go out of scope.

Implicit conversions would still allocate an array copy via the immutable collection constructor. A general purpose fix for this would be way more complex :D

**Comment by Clockwork-Muse** [comment]
@Therzok - Oh, I'm aware, it was more just idle musing for that part.

**Comment by Therzok** [comment]
Just thought about this from a different perspective, which makes the problem really hard to solve in the current world.

Exposing corlib internals to immutable.collections, which would be a layering violation, which most likely makes it not an option.

Then we are left with teaching corlib about ImmutableArray.

Don't know what to say about the other immutable collections. The usage pattern of ImmutableArray in this scenario and possibly many similar others is that we're trying to avoid copying when we can guarantee no copying.

Would ImmutableArray being part of corlib even be considered an option? Is it too much friction/effort for too little gain?

**Comment by stephentoub** [comment]
> Would ImmutableArray being part of corlib even be considered an option? Is it too much friction/effort for too little gain?

I think so.  But thank you for the suggestion.
