### ISSUE TITLE
[.Net Core] The IsLoadCompleted property’s CanWrite value is incorrect in System.Media.SoundPlayer class   

### ISSUE THREAD

**Issue by John-Qiao** [dotnet/corefx#37623]
**OS:** RS4 X64
**VS:** Dev16 16.2.0 Preview 1.0 [28907.174.d16.2]
**.NET Core:** 3.0.100-preview6-011854 from Master branch

**More Info:**
There’s no this issue when the separate System.Media.SoundPlayer.dll exist in .NET Core SDK(located under C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.0.0-previewX-XXXXX-XX folder), after this separate System.Media.SoundPlayer.dll be removed from .NET Core SDK, this issue occurs.   

**Steps to reproduce:**
1.	Install the .NET Core 3.0 SDK from https://github.com/dotnet/core-sdk for Master branch.
2.	Open the attached ‘Testcase’ .NET Core app in VS.
3.	Start it and observe the **CanWrite** property value in debugging result.
[Testcase.zip](https://github.com/dotnet/corefx/files/3172013/Testcase.zip)

**Actual:** 
The **IsLoadCompleted** property’s **CanWrite** value is true.  
![NetCore-result](https://user-images.githubusercontent.com/45864985/57609243-12f8f200-75a1-11e9-8159-b246c2703bb6.png)

**Expected:** 
As the **IsLoadCompleted** property is read-only, so its **CanWrite** value should be **false**, like it works in .NET Framework. 
![NetFramework-result](https://user-images.githubusercontent.com/45864985/57609276-20ae7780-75a1-11e9-9b5d-93b46a1fe9dd.png)

**Comment by ericstj** [comment]
/cc @maryamariyan 

This is a side-effect of the property being implemented as an auto-property with a private setter (and thus CanWrite returns true).  In .NETFramework it had no setter and was set with direct field access (CanWrite returns false).

I don't see this as a breaking change.  Reflection behavior describing internal / private members is not a compatibility contract.  Do you have a real scenario where this is actually breaking an application?  If so, please provide that.  Simply observing a diff in implementation assemblies then manufacturing a repro to illustrate that change does not constitute an relevant issue, especially when that illustration uses private reflection. @merriemcgaw
