### ISSUE TITLE
SCTP support requests ?

### ISSUE THREAD

**Issue by sgf** [dotnet/corefx#37622]
SCTP（Stream Control Transmission Protocol) is an old and important Protocol on Transport Layer.
The SCTP protocol is second only to the TCP and UDP protocols.
its supported by many OS and Devices.
its Almost 20 years Age.
.net core As a cross platform. any plan to support that in feature?

**Comment by scalablecory** [comment]
Are there any specific scenarios you're aiming to enable with SCTP?

**Comment by davidfowl** [comment]
SCTP will be replaced with QUIC which we'll end up supporting in a future version (along with HTTP/3)

**Comment by sgf** [comment]
Every scene where TCP or UDP are using.
TCP is full of loopholes. Syn attack,TIME_WAIT state(it's a long history of difficult issues.).

**Comment by sgf** [comment]
I do not want to discuss too much on UDP.
Why?Because UDP is an target that ICP blockade, routing is being discriminated against in the process of forwarding packets.UDP uses subject to many restrictions.

**Comment by sgf** [comment]
Maybe these arguments are not enough to be the sctp implementation force, but in fact sctp itself is good enough.In fact, QUIC basically copied many features of SCTP.

One reason why SCTP is not popular is that Windows, which is a mainstream PC operating system, does not support it.(if do,i think many app,internet games will use it to replace TCP/UDP).

where another:QUIC is from google.

**Comment by wfurt** [comment]
It seems like the question was answered, right? 
sctp is not coming any time soon.
