### ISSUE TITLE
[.Net Core] Cannot declare a variable of SystemSounds type(System.Media.SystemSounds class)

### ISSUE THREAD

**Issue by John-Qiao** [dotnet/corefx#37624]
**OS:** RS4 X64
**VS:** Dev16 16.2.0 Preview 1.0 [28907.174.d16.2]
**.NET Core:** 3.0.100-preview6-011854 from Master branch

**More Info:**
There’s no this issue when the separate System.Media.SoundPlayer.dll exist in .NET Core SDK(located under C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.0.0-previewX-XXXXX-XX folder), after this separate System.Media.SoundPlayer.dll be removed from .NET Core SDK, this issue occurs.   

**Steps to reproduce:**
1.	Install the .NET Core 3.0 SDK from https://github.com/dotnet/core-sdk for Master branch.
2.	Create a new template .NET Core app.
3.	Open Form1.cs file and declare a variable of SystemSounds type.

**Actual:** 
Cannot declare the variable with an error.  
![NetCore-result](https://user-images.githubusercontent.com/45864985/57610591-b21ee900-75a3-11e9-8153-9e70107bcfd6.png)
![NetCore-result2](https://user-images.githubusercontent.com/45864985/57610607-b945f700-75a3-11e9-91c5-05b4b4181b26.png)

**Expected:** 
Can declare the variable without error, like it works in .NET Framework. 
![NetFramework-result](https://user-images.githubusercontent.com/45864985/57610648-cfec4e00-75a3-11e9-9e47-93b01fa83482.png)
![NetFramework-result2](https://user-images.githubusercontent.com/45864985/57610666-da0e4c80-75a3-11e9-915e-c50f00f662fa.png)

**Comment by Wraith2** [comment]
Why would you want to create an instance of it when there are only static properties?

**Comment by John-Qiao** [comment]
@Wraith2, we are testing the .NET Core, and found there's a differnece between .NET Framework and .NET Core in SystemSounds class. So we want to confirm if that's by design in .NET Core SystemSounds class now?

**Comment by ericstj** [comment]
Yes by design.  You could never have instantiated this type in .NETFramework.  It would have been static if that was available in .NET framework with the type was created.  There is no binary compatible scenario that would break with this change and no legitimate source usage scenario that would break either.
