### ISSUE TITLE
System.Net.Http.HttpClientHandler.CookieContainer is empty in a UWP app despite proper header being set

### ISSUE THREAD

**Issue by MikelThief** [dotnet/corefx#37628]
When I make a request to the server to obtain cookies, my client's cookiecontainer stays empty.
Proper header is included with a response.
Postman doesn't have this problem. Cookies are not HttpOnly and they are not "secure".

UWP version: 6.2.8
Target OS: Win10 1809

I have attached a simple repro to show the issue.
Please step line by line the `OnLaunched `method in `App.xaml.cs`.

Sample response from server:

```
HTTP/1.1 200 OK
Date: Tue, 14 May 2019 19:51:34 GMT
Server: Apache/2.4.25 (Debian)
Cache-control: no-cache, no-store, must-revalidate, max-age=0
Pragma: no-cache
Set-Cookie: STUDIA_SID=7RL2098D7YzU5wYoQAJU66Wkkufr3ohs; domain=studia3.elka.pw.edu.pl; path=/; expires=Tue May 14 20:06:34 2019
Set-Cookie: STUDIA_COOKIES=YES; domain=studia3.elka.pw.edu.pl; path=/; expires=Mon Aug 12 19:51:34 2019
Last-Modified: Tue, 14 May 2019 19:51:34 GMT
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 1131
Keep-Alive: timeout=5, max=1000
Connection: Keep-Alive
Content-Type: text/html; charset=utf-8

        V n 6} ~ D(*  ]_  ^-j$y04l#h  R ZZ     "/ ~C _  _JZ_b h     ! \w    Wg?    + l4  L iP  
 e q I  չPӤߌ %:F   

*** FIDDLER: RawDisplay truncated at 128 characters. Right-click to disable truncation. ***

```
Reproduction
[NoCookiesProblem.zip](https://github.com/dotnet/corefx/files/3557133/NoCookiesProblem.zip)

**Comment by karelz** [comment]
Triage: Differences in WinRT cookies and handling and .NET cookie handling (we already have tons of special code to handle differences).

**Comment by davidsh** [comment]
This issue was specific to the UAP implementation of the networking stack which had a different implementation for things like HTTP and WebSockets.

As of PR #41759, we no longer build the separate implementation for the UAP platform. So, this issue can't occur anymore with .NET 5 because we now will be using the same .NET Core implementation as on Windows, Linux, Mac.

**Comment by MikelThief** [comment]
@davidsh .NET 5 is likely going to be release in November 2020. Is there any recommended workaround except for manually extracting it from headers? 1 year is a lot of time to just wait.
