### ISSUE TITLE
Extension methods Realizations

### ISSUE THREAD

**Issue by ASalihov** [dotnet/corefx#37625]
Can somebody explain why most of methods in this file https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs don't have realisations?

**Comment by Wraith2** [comment]
because it's in the /ref folder it is the code which produces the api facade. look at the version of the files in the /src folder instead.

**Comment by ASalihov** [comment]
> because it's in the /ref folder it is the code which produces the api facade. look at the version of the files in the /src folder instead.

But in src folder there no Math.Sqrt and other methods... And what "produces the api facade" mean?

**Comment by Wraith2** [comment]
You need to read https://github.com/dotnet/corefx/blob/719e29d92e3e0a0e6f6295d1669cd9684fca028d/Documentation/coding-guidelines/project-guidelines.md#library-project-guidelines to understand how the source is laid out. 

In this case the implementation is in CoreLib in the CoreCLR project and is exposed in CoreFx through the reference assembly.

**Comment by karelz** [comment]
Answered, closing.
