### ISSUE TITLE
Update to test on Alpine 3.9

### ISSUE THREAD

**Issue by mthalman** [dotnet/corefx#37646]
CoreFX is currently being tested on Alpine 3.6 which is EOL.  This should be updated to the latest, Alpine 3.9.  This should apply to both 2.x and 3.0.

Example data showing 3.6 is being used: https://mc.dot.net/#/product/netcore/21msrc/source/prodcon~2Fcorefx~2Frelease~2F2.1-msrc~2F/type/test~2Ffunctional~2Fcli~2F/build/20190412.01

Also, the CI build seems to be using 3.8 and should also be updated to 3.9.

**Comment by ericstj** [comment]
@wfurt  it looks like you attempted to do this here: https://github.com/dotnet/corefx/pull/36392

Can you have a look?

/cc @safern

**Comment by wfurt** [comment]
3.9 did not have stable (enough) runs for CI. So I used 3.8 for CI and 3.9 for official builds. Do we have list of branches we actively service? I think we should use 3.8 for 2.x to avoid issues with new OpenSSL.

cc: @wtgodbe

**Comment by mthalman** [comment]
> 3.9 did not have stable (enough) runs for CI. So I used 3.8 for CI and 3.9 for official builds. Do we have list of branches we actively service? I think we should use 3.8 for 2.x to avoid issues with new OpenSSL.

What issues with OpenSSL?  Is it at all related to this: https://github.com/dotnet/corefx/issues/35956?  I'd really like to see this one fixed.

If CI exposes issues with 3.9 then maybe that'll prompt folks to fix those issues.

**Comment by wfurt** [comment]
That was  #36426. I don't know how well we support new OpenSSL in older branches. That still may be issues even if master get fixed.

**Comment by wtgodbe** [comment]
@wfurt we actively service 2.1 & 2.2. 1.0.0 & 1.1.0 go EOL next month, but unless something changes we don't have any more scheduled builds for those branches, so we should be fine just fixing this in 2.1/2.2.

**Comment by mthalman** [comment]
There is no support for 1.x on Alpine so that's not an issue.  Alpine 3.9 falls under the list of supported OS versions at [.NET Core 2.1 - Supported OS versions](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md), [.NET Core 2.2 - Supported OS versions](https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2-supported-os.md), and [.NET Core 3.0 - Supported OS versions](https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md).

It's important this get done very soon because we already have published Docker images for .NET Core 2.x and 3.0 on Alpine 3.9 and we've got a requirement to make this the default Alpine version.

**Comment by ericstj** [comment]
Since #36426 was fixed in master lets make sure master is using Alpine 3.9 in CI.  /cc @ViktorHofer 

If you need separate work for servicing can you spin off a separate issue for that?

**Comment by mthalman** [comment]
> If you need separate work for servicing can you spin off a separate issue for that?

I've created #38027 to address 2.x.
