### ISSUE TITLE
gdpicture_ needs System.Drawing.Bitmap.FromGDIplus

### ISSUE THREAD

**Issue by Lohnegrim** [dotnet/corefx#37645]
NET Core Version: 3.0 Preview5
Have you experienced this same bug with .NET Framework?: No

Hi, when I tryed to convert a App from classic .Net FW  to .Net Core, I encountered that when you try to create a GdViewer from GDPicture (https://www.gdpicture.com/) then the creation fails because of the missing Method System.Drawing.Bitmap.FromGDIplus:
System.MissingMethodException: Method 'System.Drawing.Bitmap.FromGDIplus' not found.

**Comment by ericstj** [comment]
That's an internal API.  Are you the maintainer for GdViewer?  Can you elaborate on why it's calling internal APIs in System.Drawing?

**Comment by Lohnegrim** [comment]
No, I'm only a user of GDPicture, and I encountered this Error (among others) after trying to convert our big project to dotNet Core

**Comment by Lohnegrim** [comment]
Hi,
I got a Update on the Ticket with:
"The current road-map is to migrate to .NET core at the end of this year, so it  is work-in-progress."

**Comment by Lohnegrim** [comment]
Hi, I got a Update from the GDPicture Support, they make a fix on their end.
