### ISSUE TITLE
XML Signature generated in Java failed Validation in C#.net using SignedXML

### ISSUE THREAD

**Issue by BilalIqbal0926** [dotnet/corefx#37643]
I am working on an assignment where i will receive an XML request in REST service (Built using C#.Net).

I am suing System.Security.Cryptography.Xml version 4.5.0 with target .Net Framework 4.7.

Sender is using Java to generate XML signature and public key is provided separately in certificate form. 

My C# code is getting failed on provided sample files, always give false for valid / in valid files.

I tried same sample in Java application and it works fine.

 X509Certificate2 objCertificate = new X509Certificate2(@"D:\Signing_testing.crt");
            XmlDocument validFile = new XmlDocument();

            validFile.Load(@"D:\sample_file.xml");
            validFile.PreserveWhitespace = true;

            
            SignedXml validSigned = new SignedXml(validFile);

            XmlNodeList nl = validFile.GetElementsByTagName("Signature");
            XmlElement validSign = (XmlElement)nl[0];

            validSigned.LoadXml(validSign);

            Console.WriteLine("Valid file result " + validSigned.CheckSignature(objCertificate, true));

Can anyone help on this issue?

**Comment by bartonjs** [comment]
SignedXml supports a diagnostic output to report the various steps it performs, https://social.msdn.microsoft.com/Forums/en-US/80310179-00bd-4af3-8928-288b325d8269/signedxml-checksignature-enable-signedxmldebuglog?forum=xmlandnetfx#12907efc-7abb-4fbf-a435-7c856ce2c364 has an example of enabling it.

**Comment by BilalIqbal0926** [comment]
Thanks bartonjs.

I added that configuration and i found the issue, it was taking my XML without spaces. I had set the property already to preserve white spaces but it was after XML DOcument Load function. So log directed me to resolve issue.

Thanks again
