### ISSUE TITLE
System.Net.Http not working for .NET core project targeting net45 

### ISSUE THREAD

**Issue by ksaurabh1** [dotnet/corefx#37666]
I have a project which is written both in .NET framework and .NET core.
The core project targets **netstandard2.0, net45 and net461**

I have a Package reference to System.Net.Http as follows, in both the projects 

`<ItemGroup>
      <PackageReference Include="Newtonsoft.Json" Version="10.0.1" />
      <PackageReference Include="System.Net.Http" Version="4.3.0" />
  </ItemGroup>`

net45 target expects the System.Net.Http version to be 4.0.0 , and I have used binding redirect to achieve the same in the .NET Framework project

`<dependentAssembly>
    <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.0.0.0" />
  </dependentAssembly> 
`

The referenced dll in case of the .NET framework project is version 4.0.0 as expected.

But the same is not achievable in .NET core project. Somehow it refers to 4.2.0.0 and hence the application targeting net45 breaks.

Please advice how to use System.Net.Http version 4.0.0 in .NET Core application targeting ns2, net45 and net461

**Comment by wfurt** [comment]
cc: @ericstj

**Comment by ericstj** [comment]
I think you mean you're using the .NET.SDK to target .NET45, is that correct?  There is no such thing as a ".NET Core application targeting net45".  .NET Core applications do not use bindingRedirects at all and target netcoreappX.Y.  

If you're using System.Net.Http 4.3.0 package you should redirect to the assembly version that is carried by that package, not down to 4.0.0.0.  Redirecting down can break assemblies which depend on the APIs that are only present in the higher version.

If you're still having problems that are specific to the .NET.SDK you can open an issue in the dotnet/sdk repo and provide a build log that illustrates the issue.

**Comment by ksaurabh1** [comment]
Thanks for the clarification Eric.
Yes, i am using .NET.SDK to target net45.

<Project Sdk="Microsoft.NET.Sdk">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <TargetFrameworks>netstandard2.0;net45;net461</TargetFrameworks>

I am not actually using the binding redirect, that was one of the option which i tried.
the configuration present in csproj is 

<ItemGroup>
      <PackageReference Include="Newtonsoft.Json" Version="10.0.1" />
      <PackageReference Include="System.Net.Http" Version="4.3.0" />
  </ItemGroup>


The irony is when i am building the project in my local machine through VS IDE, all the bindings happen properly, System.Net.Http v4.0.0.0 for net45 , v4.1.1.0 for net461 and 4.2.0.0 for ns2.0.

But when i am building the same solution using a script on a host, the bindings were not happening correctly. Maybe the reason is, I have only v4.0 and v4.7.2 present in folder  "Reference Assemblies\Microsoft\Framework\.NETFramework". We are using cayman components to use the VS components on the host machines. As such, even if we put the v4.5 in reference assemblies we can target only one folder by setting the path (either 4.5 or 4.7.2), and as such as pointed by you, targeting folder 4.5 breaks assemblies which depend on the APIs that are only present in the higher version.

We are looking into the issue and how to get over it.
Thanks for your help.
