### ISSUE TITLE
Creating a cross-platform service?

### ISSUE THREAD

**Issue by ocdtrekkie** [dotnet/corefx#37679]
Not sure if this is the ideal repo to file this issue, let me know if there's a better place.

I have a WinForms .NET Framework app (in Visual Basic, FWIW), and I a few long-term goals:
- Factor out the WinForms UI and run it as a background service.
- Make it cross-platform, since for one deployment scenario, Windows is non-ideal.

I've played with creating a Windows Service using the project template in Visual Studio, which is fairly straightforward. And while Linux services appear to operate similarly (service start/stop options, basically), there doesn't seem to be a straightforward way to create a service with .NET that runs on both.

I found this article on the matter: https://dejanstojanovic.net/aspnet/2018/august/creating-windows-service-and-linux-daemon-with-the-same-code-base-in-net/

But with .NET Core aggressively moving to replace .NET Framework, it seems like a truly valuable contribution would be to support a project type/template that could build a proper Windows Service and a Linux service outright, and move towards deprecating the "Windows Service" project type.

**Comment by pingzing** [comment]
@ocdtrekkie Have you seen [this blog post](https://devblogs.microsoft.com/aspnet/net-core-workers-as-windows-services/) about some things they're doing in .NET Core 3 for this kind of thing? The comments mention that you can use the exact same code base to set it up for a something using systemd on a Unix using a config file, but I can't seem to find any docs about it.

**Comment by ocdtrekkie** [comment]
I had not. And perhaps that is a promising start, since the current Windows Service project template uses the .NET Framework. But as we look towards .NET 5, I'm really hoping the service template can move towards being inherently cross-platform by default.

**Comment by karelz** [comment]
I believe the APIs do exist in System.ServiceProcess namespace, right?
We do not track Visual Studio templates and extensions in this repo. Please file a VS Feedback item for that.
Closing, please let me know if my assumptions are not correct.
