### ISSUE TITLE
`Ctrl + .` doesn't implement quick actions and refactoring 

### ISSUE THREAD

**Issue by ranjan-ranjan** [dotnet/corefx#37671]
**Steps to Reproduce:**

1. I am trying to get values from `app.config` in a WPF project
2. So, I have added reference to `System.Configuration.ConfigurationSettings.AppSettings[""]`
3. This gives a warning and workaround
4. We can't use `Ctrl +` . to implement quick actions and refactoring
5. `Ctrl +` . should implement quick actions and refactoring
6. I have added snapshot as a reference

**Expected Behavior:**

`Ctrl + .` doesn't implement quick actions and refactoring

**Actual Behavior:**

`Ctrl + .` should implement quick actions and refactoring

Issue was file in https://github.com/dotnet/roslyn/issues/30826

![47648972-b8b6b780-dba1-11e8-899f-c770044c0119](https://user-images.githubusercontent.com/16834561/57779257-6145f680-7743-11e9-99e2-e382f8d3a599.png)

**Comment by Gnbrkm41** [comment]
The title seems somewhat misleading (I immediately assumed it was more of a roslyn issue); consider renaming it on the line of 'why is this method/class marked as obsolete/deprecated?' as this seems like it was done on purpose.

**Comment by Gnbrkm41** [comment]
(Also looks like [ConfigurationManager](https://docs.microsoft.com/en-us/dotnet/api/system.configuration.configurationmanager?view=netframework-4.7.2) is pretty much a drop-in replacement, but correct me if I'm wrong: http://www.philosophicalgeek.com/2007/11/26/difference-between-configurationsettings-and-configurationmanager/)

**Comment by ranjan-ranjan** [comment]
No
I feel that the normal behavior was to implement a suggestion on pressing `Ctrl + .`

**Comment by Gnbrkm41** [comment]
Normally they are, however in this case they are deliberately hidden from Intellisense suggestions to discourage the use of the type. So this is *the normal behaviour* for that type.
