### ISSUE TITLE
Test failure: System.Data.SqlClient.Tests.SqlStringTest/Constructor_ValueLcid_Success fail with "System.TypeInitializationException"

### ISSUE THREAD

**Issue by dotnet-mc-bot** [dotnet/corefx#37692]
Opened on behalf of @Jiayili1

The test `System.Data.SqlClient.Tests.SqlStringTest/Constructor_ValueLcid_Success` has failed.

```
System.TypeInitializationException : The type initializer for 'System.Data.Locale' threw an exception.\r
---- System.IO.FileLoadException : Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

Stack Trace:

```
   at System.Data.Locale.GetLocaleNameForLcid(Int32 lcid)
   at System.Data.SqlTypes.SqlString.get_CultureInfo() in D:\A\_work\2\s\src\System.Data.SqlClient\src\System\Data\SqlTypes\SQLString.cs:line 281
   at System.Data.SqlClient.Tests.SqlStringTest.ValidateProperties(String value, CultureInfo culture, SqlString sqlString) in D:\A\_work\2\s\src\System.Data.SqlClient\tests\FunctionalTests\SqlStringTest.cs:line 38
   at System.Data.SqlClient.Tests.SqlStringTest.Constructor_ValueLcid_Success(Int32 lcid, String name) in D:\A\_work\2\s\src\System.Data.SqlClient\tests\FunctionalTests\SqlStringTest.cs:line 30
----- Inner Stack Trace -----
   at System.Data.Locale..cctor()
```

Failing configurations:
- Windows.10.Amd64
  - AnyCPU-Debug
  - AnyCPU-Release

Failed tests:
System.Data.SqlClient.Tests.SqlStringTest/Constructor_ValueLcid_Success
System.Data.SqlClient.Tests.SqlStringTest/Constructor_Value_Success

**Comment by ahsonkhan** [comment]
@divega, I am curious, was there a reason for some of these issue "transfers" between dotnet/corefx and dotnet/SqlClient and back?

Interestingly, it seems to have pushed these issues to the top of the list of issue (since they are listed by latest - https://github.com/dotnet/corefx/issues - even though the older dates persist). So now, 37695 was opened 13 days ago but is a higher issue number than 37694 which was opened 4 hours ago.
![image](https://user-images.githubusercontent.com/6527137/57828113-1fc34480-775f-11e9-894a-4aa8164f0880.png)

**Comment by Wraith2** [comment]
This failure hasn't happened in the last year that i've seen and the test is enabled. It is probably best to close it.

**Comment by divega** [comment]
@ahsonkhan I was originally going to transfer all issues in area-System.Data.SqlClient to the new repo, but then I realized that there were a few that looked like they could be specific to the copy of the codebase in CoreFx, including any issues created for test failures. When I realized this, I had already moved a few of these issues, which I decide to move back. Is there any ulterior consequence to change in ordering?

I suspect as @Wraith2 said, some of these are quite old, but maybe worth looking at one by one.

**Comment by ahsonkhan** [comment]
>  Is there any ulterior consequence to the change in ordering? 

Nope, just observing the weird quirk of GitHub ordering. I sometimes poll the "recent" issues, so was just caught off guard by it.

**Comment by stephentoub** [comment]
@divega, is this still for 3.0?

**Comment by divega** [comment]
@stephentoub I don’t know. Let’s ask @david-engel. Is the test still disabled or failing?

**Comment by David-Engel** [comment]
@divega It appears that SqlStringTest was deleted by @stephentoub in October of 2016:
https://github.com/dotnet/corefx/commit/7888677b3c53596085c2fa53860d9a0519eeecfd#diff-f95f8aafcd3cd8a0d21dae095f440501

**Comment by stephentoub** [comment]
> It appears that SqlStringTest was deleted by @stephentoub in October of 2016

@David-Engel, that PR added it, copying it from Mono; it didn't delete it.  SqlStringTest is still in the repo:
https://github.com/dotnet/corefx/blob/master/src/System.Data.Common/tests/System/Data/SqlTypes/SqlStringTest.cs

**Comment by David-Engel** [comment]
@stephentoub No wonder I couldn't find it. I was looking for it in System.Data.SqlClient. I haven't heard anything about it failing but we don't run the System.Data.Common tests regularly.

**Comment by cheenamalhotra** [comment]
As commented above by @Wraith2 , the issue is not happening anymore.
Also confirmed with @David-Engel the issue can now be closed.
