### ISSUE TITLE
Deserializing duplicate JSON object keys to a dictionary

### ISSUE THREAD

**Issue by JamesNK** [dotnet/corefx#37694]
Deserializing duplicate JSON object keys to a dictionary should be thought about. They're not common, but they're also not disallowed by the JSON spec.

In Newtonsoft.Json key/value pairs are set into the dictionary so that the last value in an object wins. This means dictionaries align with classes when it comes to duplicate object keys: the final result is the last value.

```json
{
    "Hello": "friends",
    "Hello": "world"
}
```

```cs
var d = JsonSerializer.Parse<Dictionary<string, string>(json);
var target = d["Hello"]; // world
```

Throwing an error that there is a duplicate key would prevent someone from using the serializer. S.T.J should either follow "last value wins", or have a setting to opt into it or out of it. Newtonsoft.Json has a setting like this: https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Linq_DuplicatePropertyNameHandling.htm

This should also be considered with JsonDocument.

My recommendation is to follow "last value wins" by default in the serializer and JsonDocument, and either add a setting now or in the future to allow people to be more strict (throw an error) about duplicate JSON object keys.

// @ahsonkhan @rynowak @steveharter @JeremyKuhne

**Comment by ahsonkhan** [comment]
> This should also be considered with JsonDocument.

For searching a property within a payload that contains duplicates, `JsonDocument` already picks the last one (matching what Json.NET does).

https://github.com/dotnet/corefx/blob/f6762c0e37641bf31b9957dc51e74089bac5a310/src/System.Text.Json/tests/JsonDocumentTests.cs#L1770-L1791

cc @bartonjs

> My recommendation is to follow "last value wins" by default in the serializer

Agreed. That makes sense to me. Would the same apply when deserializing any duplicate property (even outside of dictionary)?

```C#
public class Foo
{
   bool SomeBool {get; set;}
}

string json = "{\"SomeBool\": false, \"SomeBool\":true}";
Foo foo = JsonSerializer.Parse<Foo>(json);
Assert.True(foo.SomeBool);
```

**Comment by JamesNK** [comment]
> Would the same apply when deserializing any duplicate property (even outside of dictionary)?

I haven't tested it out but that is likely that is already the serializer behavior for non-dictionaries. The alternative is keeping state for every POCO you are deserializing: you will need a list of keys that have been set, and you would check it before setting a property value.

**Comment by JamesNK** [comment]
> JsonDocument already picks the last one (matching what Json.NET does).

You don't need to do it for 3.0 but someone will soon ask for a setting like https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Linq_DuplicatePropertyNameHandling.htm for JsonDocument and the serializer.

The load/parse methods on JsonDocument will likely have overloads in the future with additional options beyond just JsonReaderOptions.

**Comment by ahsonkhan** [comment]
> The load/parse methods on JsonDocument will likely have overloads in the future with additional options beyond just JsonReaderOptions.

That would be somewhat unfortunate, imo. If we expect that to be the case, do you think we should instead have a dedicated `JsonDocumentOptions` rather than re-use `JsonReaderOptions`?

**Comment by GSPP** [comment]
Multiple identical keys are likely an error in the data. Picking the last one hides errors and drops data. It's `ON ERROR RESUME NEXT` for data... Seems like a bad default.

**Comment by ahsonkhan** [comment]
@maryamariyan, are you working on this issue for the 6/26 target?

**Comment by maryamariyan** [comment]
yes. but I plan to start this on Thursday, 6/13.
I will unassign in case someone can pick this up earlier and can reassign back if it is available by then.

**Comment by Anipik** [comment]
@ahsonkhan do we finally want to go with the "last value wins" approach ?

**Comment by ahsonkhan** [comment]
>  do we finally want to go with the "last value wins" approach ?

Yes. Trying to validate up front for duplicate property names and disallowing it would likely be too expensive (in terms of perf), so I don't think throwing by default is worth the trade-off. @steveharter, let us know if you agree with that.

**Comment by steveharter** [comment]
> Trying to validate up front for duplicate property names and disallowing it would likely be too expensive (in terms of perf)

Yes - the code should be changed to use last-value-wins via TryAdd or an indexer (which doesn't throw, unlike Add).

We could always add an opt-in option in the future to prevent duplicates.

**Comment by steveharter** [comment]
Also offline discussion with @Anipik:
- Determine semantics of Json.NET for duplicate properties. Does it throw or allow?
- If it allows, for collections\dictionaries what semantics does it have? Replace or add to the current (previous) collection\dictionary.

Currently I'm assuming:
- Allow duplicate properties
- Add semantics to previous list\collection

**Comment by steveharter** [comment]
Also we should see a perf improvement for dictionaries - please run some perf numbers for the dictionary change (@layomia added some recent benchmarks) and report on that. Thanks!

**Comment by Anipik** [comment]
> Determine semantics of Json.NET for duplicate properties. Does it throw or allow?

Yes it does not throw, it follows last win approach

>  If it allows, for collections\dictionaries what semantics does it have? Does it replace, add or ignore the items on the extra collection\dictionary?

For collections it just replaces the collections and for dictionaries it concatenates the keys. the behavior is same for System.Text.Json

>  please run some perf numbers for the dictionary change

I ran the performance numbers. The change improves the performance by 5-8 percent for dictionaries and  for object the change doesn't affect the performance. (Even with the linq)

The size of the object and dictionary was 30 elements. Currently the json tests are broken in performance so I just wrote new ones to test the change.

**Comment by Anipik** [comment]
> Can't run and\or compile

I was earlier getting a compile error that "Not able to convert IO.Stream to generic type parameter"
but for some reason its no logger exists. i will try to debug why it occured in the firstplace

**Comment by layomia** [comment]
> > Currently the json tests are broken in performance so I just wrote new ones to test the change.
> 
> What does this mean? Can't run and\or compile? cc @layomia

PR https://github.com/dotnet/performance/pull/530 adding benchmarks for dictionary and other collections is not merged yet. I'll work to check this in ASAP.
