### ISSUE TITLE
Regex tests intermittently fail due to memory usage

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#377]
In RegexLangElementsCoverageTests.cs, there are several checks related to the total memory usage of the test:

```` CSharp
// ** RegexLangElementsCoverageTests.cs **

double maxAcceptablePercentDifference = .3;
startWorkingSet = GC.GetTotalMemory(true);
...
endWorkingSet = GC.GetTotalMemory(true);

percentDifference = ((double)Math.Abs(startWorkingSet - endWorkingSet)) / startWorkingSet;

if (maxAcceptablePercentDifference < percentDifference)
{
    Console.WriteLine("Err_004888anied Total memory increased significantly there may be a memory leak");
    Console.WriteLine("Percent Difference={0}, Max Acceptable Percent Difference={1}, Start Working Set={2}, End Working Set={3}",
        percentDifference, maxAcceptablePercentDifference, startWorkingSet, endWorkingSet);
    iCountErrors++;
}
````
I think this check may be causing us more bad than good. I'm not sure what GC.GetTotalMemory takes into consideration, but this logic might also be getting tripped up by the fact that we have multiple tests running in parallel. Also, in general, this seems like a bit of a flaky check in the first place; it fails around 10% of the time for me, I would say. Anyone opposed to removing these checks, or at least making it not an error?

**Comment by jacobcarpenter** [comment]
I have also experienced this spurious failure.

**Comment by jacobcarpenter** [comment]
See also Issue #323

**Comment by mellinoe** [comment]
Oops! I'm actually going to close this issue and continue the discussion there. Thanks @jacobcarpenter
