### ISSUE TITLE
StreamPipeReader/Writer should allow to leave underlying stream opened

### ISSUE THREAD

**Issue by azhmur** [dotnet/corefx#37701]
Currently StreamPipeReader/Writer always closes underlying stream on complete, which effectively prohibits writing tests for roundtrip scenarios. I have added option to leave underlying stream opened via corresponding options classes. The change is fully backward compatible. 

Please look at https://github.com/dotnet/corefx/pull/37667/files#diff-3e3d4d1815dfb473d42636ce0603aaa6R93 for details.

PS As far as I understand StreamPipeReader/Writer wasn't yet shipped, it was only part of preview releases in nuget.
PPS Original API review: https://github.com/dotnet/corefx/issues/27246

**Comment by shutdown256** [comment]
I would also love to be able to dispose the stream without completing underling Reader/Writer.

**Comment by anurse** [comment]
The `leaveOpen` parameter option seems appropriate to me. There is [precedent in the framework](https://docs.microsoft.com/en-us/dotnet/api/system.io.streamreader.-ctor?view=netframework-4.8#System_IO_StreamReader__ctor_System_IO_Stream_System_Text_Encoding_System_Boolean_System_Int32_System_Boolean_) for this.

Since the `PipeReader.Create` and `PipeWrite.Create` methods already take in a "options" object (`StreamPipeReaderOptions`/`StreamPipeWriterOptions`) and that constructor already has a series of optional parameters for other options, I think it makes sense to add it there.

So the proposed change is this (copied from original API review in https://github.com/dotnet/corefx/issues/27246, additions highlighted with `// **` comments):

```csharp
public class PipeReader
{
    public static PipeReader Create(Stream stream, StreamPipeReaderOptions readerOptions = null);

    public virtual Stream AsStream();
    public virtual Task CopyToAsync(Stream stream, CancellationToken cancellationToken = default);
}

public class PipeWriter
{
    public static PipeWriter Create(Stream stream, StreamPipeWriterOptions writerOptions = null);

    public virtual Stream AsStream();
    protected internal virtual Task CopyFromAsync(Stream stream, CancellationToken cancellationToken = default);
}

public class StreamPipeWriterOptions
{
    private const int DefaultMinimumBufferSize = 4096;

    // ** Add a new constructor argument 'leaveOpen'
    public StreamPipeWriterOptions(MemoryPool<byte> pool = null, int minimumBufferSize = DefaultMinimumBufferSize, bool leaveOpen = false)
    {
        Pool = pool;
        MinimumBufferSize = minimumBufferSize;
        LeaveOpen = leaveOpen;
    }

    public int MinimumBufferSize { get; }
    public MemoryPool<byte> Pool { get; }

    // ** New Property
    public bool LeaveOpen { get; }
}

public class StreamPipeReaderOptions
{
    private const int DefaultBufferSize = 4096;
    private const int DefaultMinimumReadSize = 1024;

    // ** Add a new constructor argument 'leaveOpen'
    public StreamPipeReaderOptions(MemoryPool<byte> memoryPool = null, int bufferSize = DefaultBufferSize, int minimumReadSize = DefaultMinimumReadSize, bool leaveOpen = false)
    {
        Pool = pool;
        BufferSize = bufferSize;
        MinimumReadSize = minimumReadSize;
    }

    public int BufferSize { get; }
    public int MinimumReadSize { get; }
    public MemoryPool<byte> Pool { get; }

    // ** New Property
    public bool LeaveOpen { get; }
}
```

This seems appropriate to me (cc @davidfowl @halter73). Submitting for API review.

**Comment by stephentoub** [comment]
This is adding a LeaveOpen option for when creating a PipeReader/Writer that wraps a Stream; do we need something similar for the other direction, when using AsStream to create a Stream that wraps a PipeReader/Writer?  Right now calling Dispose on the Stream will call Complete on the PipeReader/Writer; I still believe that's the right default, but if we're making the other direction configurable, should we here as well?

**Comment by halter73** [comment]
I agree. We should have a LeaveOpen option for both the reader and writer.

**Comment by anurse** [comment]
Seems appropriate to me. Updated my comment.

**Comment by terrajobst** [comment]
The API shape as oulined by @anurse's [comment](https://github.com/dotnet/corefx/issues/37701#issuecomment-495461474) looks good.

@tannergooding has filed a separate bug for removing the explicit buffer sizes and instead use sentinels so we can change their values later.

**Comment by tannergooding** [comment]
>has filed a separate bug for removing the explicit buffer sizes and instead use sentinels so we can change their values later. 

See https://github.com/dotnet/corefx/issues/37984

**Comment by stephentoub** [comment]
@anurse, is someone working on this?  It's a breaking change to APIs added in .NET Core 3.0, right?

**Comment by davidfowl** [comment]
This is already done.

**Comment by stephentoub** [comment]
So the issue can be closed?  Even better.
