### ISSUE TITLE
File iteration over folders ending in a dot fails

### ISSUE THREAD

**Issue by ptr727** [dotnet/corefx#37709]
When iterating over files in a folder that ends in a dot, the file iteration will fail with a file not found exception.

See: https://github.com/dotnet/corefx/issues/24160
Per the above issue, I understand that this should have been fixed?

I tested with .NET Core 3 Preview 4 on Win10 x64 using Visual Studio 2019, and it fails.

It seems that the directory iteration works correctly, but that the file iteration is not using the NT UNC notation, and the file attribute read fails to open the file.

I cannot predict when folders my app touches may contain a dot in the path, so I either have to always prepend \\?\ when on Windows, or the file file and directory enumeration has to automatically support opening files using \\?\ on Windows when needed, or allways.

Test app:
```
using System;
using System.IO;

namespace DotInPath
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create test files and folders
            Directory.CreateDirectory(@"\\?\C:\Temp\Test");
            File.Create(@"\\?\C:\Temp\Test\Test.txt");
            Directory.CreateDirectory(@"\\?\C:\Temp\TestDot.");
            File.Create(@"\\?\C:\Temp\TestDot.\TestDot.txt");
            Directory.CreateDirectory(@"\\?\C:\Temp\TestDotDot..");
            File.Create(@"\\?\C:\Temp\TestDotDot..\TestDotDot.txt");

            try
            {
                // Iterate over all files
                //DirectoryInfo sourceInfo = new DirectoryInfo(@"C:\Temp");
                DirectoryInfo sourceInfo = new DirectoryInfo(@"\\?\C:\Temp");
                foreach (DirectoryInfo dirInfo in sourceInfo.EnumerateDirectories("*", SearchOption.AllDirectories))
                {
                    Console.WriteLine(dirInfo.FullName);
                    foreach (FileInfo fileInfo in dirInfo.EnumerateFiles("*.*", SearchOption.TopDirectoryOnly))
                    {
                        Console.WriteLine(fileInfo.FullName);
                    }
                }
            }
            catch (Exception e)
            {
                // Exception thrown: 'System.IO.DirectoryNotFoundException' in System.IO.FileSystem.dll
                Console.WriteLine(e);
            }
        }
    }
}
```

**Comment by JeremyKuhne** [comment]
I thought I had all of these corner cases, but either I missed one or perhaps we regressed.

Note that creating files with trailing periods is a seriously bad idea. Almost nothing handles them correctly as the trailing period gets normalized away unless you use `\\?\`. We purposefully don't help you create them if you don't use `\\?\`.

**Comment by JeremyKuhne** [comment]
@carlossanlop I'll take a look at this with you so you can see what I was trying to do to address this sort of thing.

**Comment by ptr727** [comment]
Thank you for taking a look.
I agree that it is a bad idea to use them, but my app encountered them, (in the Cortana appdata folder), and I'd like to not break when it does happen.
