### ISSUE TITLE
Utf8JsonReader has ambiguous documentation for Get/TryGet methods

### ISSUE THREAD

**Issue by Wildenhaus** [dotnet/corefx#37722]
As of 3.0-preview5, the current documentation for the Get*/TryGet* helper methods have ambiguous documentation that does not accurately reflect their behavior.

https://github.com/dotnet/corefx/blob/d06ce9d2116cb4bda528822e63d32ce3735ea653/src/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.TryGet.cs#L413-L432

The summary states that the method will read the _next_ token and parse it. However, the current implementation parses the current token, not the next one in the document. This ambiguous language exists in the documentation for all Get*/TryGet* methods, and is made more confusing by the `Read()` function's documentation, which also states that it reads the next token in the document.

Given the current implementation, it may be helpful to fix the documentation to reflect the true behavior of these methods as well as implement additional methods that do in fact parse the next token instead of the current one. I am porting some Json.NET code and have wrapped all of these methods inside of extension methods to avoid having to call `Read()` before I parse each property value.

**Comment by ahsonkhan** [comment]
> it may be helpful to fix the documentation to reflect the true behavior of these methods

I agree. We should fix this. Good catch :)

> as well as implement additional methods that do in fact parse the next token instead of the current one

I am not sure about this one. It might just increase confusion given the current `Read()` and then `Get()` model.

**Comment by ahsonkhan** [comment]
> it may be helpful to fix the documentation to reflect the true behavior of these methods

Would you be willing to submit a PR for the fix?

**Comment by Wildenhaus** [comment]
> Would you be willing to submit a PR for the fix?

Sure! Will submit a PR in a bit.

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/dotnet/corefx/pull/37779
