### ISSUE TITLE
conflicting ValueTask definition between netstandard2.1 and nuget package

### ISSUE THREAD

**Issue by itn3000** [dotnet/corefx#37738]
# Overview

build error in netstandard2.1 when using nuget package using [System.Threading.Tasks.Extensions](https://www.nuget.org/packages/System.Threading.Tasks.Extensions/).

# Environment

* windows8.1-x64(ja)
* dotnet sdk 3.0pre5

# Steps to reproduce

1. create project with `dotnet new classlib -f netstandard2.1`
2. add [System.Threading.Channels-4.6.0-pre5](https://www.nuget.org/packages/System.Threading.Channels/4.6.0-preview5.19224.8)
3. add method using `ValueTask<T>`
4. build project

method code is following
```csharp
using System.Threading.Tasks;

class Class1
{
    ValueTask<int> X()
    {
        return new ValueTask<int>(1);
    }
}
```

# Expected result

success to build project

# Actual result

error occured with following message(sorry for Japanese, but point of error was output)

```
.NET Core 向け Microsoft (R) Build Engine バージョン 16.0.462+g62fb89029d
Copyright (C) Microsoft Corporation.All rights reserved.

  G:\src\gitrepos\dotnet-sandbox\ivaluetasksourcerror\ivaluetasksourcerror.csproj の復元が 27.28 ms で完了しました。
C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(157,5): message NETSDK1057: プレビュー版の .NET Core を使用しています。https://aka.ms/dotnet-core-preview をご覧ください [G:\src\gitrepos\dotnet-sandbox\ivaluetasksourcerror\ivaluetasksourcerror.csproj]
Class1.cs(5,11): error CS0433: 型 'ValueTask<TResult>' が 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' と 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' の両方に存在します。 [G:\src\gitrepos\dotnet-sandbox\ivaluetasksourcerror\ivaluetasksourcerror.csproj]

ビルドに失敗しました。

Class1.cs(5,11): error CS0433: 型 'ValueTask<TResult>' が 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' と 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' の両方に存在します。 [G:\src\gitrepos\dotnet-sandbox\ivaluetasksourcerror\ivaluetasksourcerror.csproj]
    0 個の警告
    1 エラー

経過時間 00:00:01.21
```

Currently, the package which has problem I found is only System.Threading.Channels, but another package may have same problem because System.Threading.Tasks.Extension is used widely.

**Comment by danmosemsft** [comment]
@joperezr

**Comment by Gnbrkm41** [comment]
`CS0433 The type 'ValueTask<TResult>' exists in both 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'` just in case if someone's wondering

**Comment by joperezr** [comment]
@terrajobst was this type recently moved inbox on netstandard 2.1? If so, we need to change System.Threading.Tasks.Extensions netstandard2.1 assembly to add a typeforward so that the type is unified with netstandard 2.1.

**Comment by ericstj** [comment]
I believe this should be handled with @wtgodbe's changes to add System.Threading.Tasks.Extensions.dll to netstandard2.1.  We should double check that. #36719

**Comment by ericstj** [comment]
Looks like the public keys were incorrect.  Fixing here: https://github.com/dotnet/standard/pull/1203

**Comment by ericstj** [comment]
This should now be fixed in the latest SDK.
