### ISSUE TITLE
Deserialize invalid string should throw but it is parsing to default value

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/corefx#37735]
Deserialize invalid string should throw but it is parsing to default value. (MyEnum.Alpha in this case)
-- UPDATE: Even setting valid numeric value converted into default value
```csharp
[Fact] 
public static void DeserializeInvalidString()
{
    string json = "{ \"Value\" : \"Three\" }";
    Assert.Throws<JsonException>(() =>
    {
        Bucket b = JsonSerializer.Parse<Bucket>(json);
    });
}

public static void DeserializeInvalidValue()
{
    string json = "{ \"Value\" : \"3\" }";
   Assert.Throws<JsonException>(() =>
    {
        Bucket b = JsonSerializer.Parse<Bucket>(json);
    });
}

public static void DeserializeValidValue()
{
    string json = "{ \"Value\" : 1 }";
    Bucket b = JsonSerializer.Parse<Bucket>(json);
    Assert.Equal(b.Value, MyEnum.Beta);   // whatever value I pass always got MyEnum.Alpha
}

public class Bucket
{
    public MyEnum Value;
}

public enum MyEnum
{
    Alpha,
    Beta,
}
```

**Comment by ahsonkhan** [comment]
cc @JeremyKuhne

**Comment by buyaa-n** [comment]
I think this test case is similar to this issue, here it should throw with invalid value but instead it is parsing into non existing value of 999
```csharp
    [Flags]
    public enum StoreColor
    {
        Black = 1,
        Red = 2,
        Yellow = 4,
        White = 8,
        DarkGoldenrod = 16
    }

    [Fact]// should throw invalid value
    public static void AllowIntegerValueAndNonNamedValue()
    {
        JsonReaderException e = Assert.Throws<JsonReaderException>(() =>
        { // s=999
             string s = JsonSerializer.ToString((StoreColor)999);
        });
    }
```

**Comment by ahsonkhan** [comment]
> I think this test case is similar to this issue, here it should throw with invalid value but instead it is parsing into non existing value of 999

Agreed. How come you closed this issue though?

**Comment by buyaa-n** [comment]
Sorry close button clicked accidentally

**Comment by ahsonkhan** [comment]
We should throw in the overflow case (for instance if the enum is backed by a byte, we should validate and throw for any JSON payload containing more than > 256 (or < 0)).

We should also verify what Json.NET does and consider matching that behavior, in all these cases.

**Comment by buyaa-n** [comment]
@ahsonkhan as per our grooming update the issue with retest result (updated inline so that no confusion for issue resolver) cc @maryamariyan

**Comment by ahsonkhan** [comment]
> update the issue with retest result

1) I believe this:
> Assert.Equal(b, MyEnum.Beta);   // whatever value I pass always got MyEnum.Alpha

Needs to be: 
```C#
Assert.Equal(b.Value, MyEnum.Beta);
```

2) Serializing/Deserializing fields are **not** supported today. If you change the `Value` field to a property, the test pass as expected. That is why you are seeing the "default" enum value being set for all these test cases. We aren't modifying it at all during deserialization:

```C#
[Fact]
public static void SerializeStructsWorks()
{
    string json = "{ \"Value\" : 1 }";
    Bucket b = JsonSerializer.Parse<Bucket>(json);
    Assert.Equal(b.Value, MyEnum.Beta); // Success!
}

public class Bucket
{
    public MyEnum Value { get; set; } // Properties are supported
}

public enum MyEnum
{
    Alpha,
    Beta,
}
```

To clarify, consider the following where the user sets the field value to something other than the default enum value (i.e. something other than 0, in your case `MyEnum.Alpha`). I get the the JsonSerializer **should** set the value to what the data contains (in vNext once we have field support built in), but I am just stating it doesn't **today** and is a known limitation. **Here's the issue:** https://github.com/dotnet/corefx/issues/36505
```C#
[Fact]
public static void SerializeStructsWorks()
{
    string json = "{ \"Value\" : 0 }";
    Bucket b = JsonSerializer.Parse<Bucket>(json);
    // Since fields are not supported, we leave the values as is, which is why this test fails today (as expected).
    Assert.Equal(b.Value, MyEnum.Alpha);
}

public class Bucket
{
    public MyEnum Value = MyEnum.Beta; // public/private fields retain their original value, whether default or custom
}
```

3) Similarly, for the "overflow" scenario, Json.NET doesn't throw. So, we shouldn't either:
```C#
[Fact]
public static void SerializeStructsWorks()
{
    string json = "{ \"Value\" : 3 }"; // Note the digit 3 (i.e. Json Number), and not "3" in quotes (which is Json String)
    Bucket b = JsonSerializer.Parse<Bucket>(json);
    Assert.Equal(b.Value, (MyEnum)3); // Success!

    Bucket original = JsonConvert.DeserializeObject<Bucket>(json);
    Assert.Equal(original.Value, (MyEnum)3); // We match this behavior within our deserializer
}

public class Bucket
{
    public MyEnum Value { get; set; }
}

public enum MyEnum
{
    Alpha,
    Beta,
}
```

**Comment by buyaa-n** [comment]
Thank you @ahsonkhan that makes sense, sounds like we are not going to throw error in this case, closing the issue
