### ISSUE TITLE
System.Diagnostics.Tests.ProcessTests.ProcessNameMatchesScriptName fails on netcoreapp-Linux-Release-x64-RedHat.6.Amd64.Open consistently

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#37739]
@tmds you added the test that fails on RedHat6. It seems the process name is stripped after 15 characters. I will disable the test meanwhile for RH6.

https://dev.azure.com/dnceng/public/_build/results?buildId=191758&view=ms.vss-test-web.build-test-results-tab&runId=4626326&resultId=358982

```
Assert.Equal() Failure\n ↓ (pos 15)\nExpected: ProcessNameMatchesScriptName_163_84763abe\nActual: ProcessNameMatc\n ↑ (pos 15)

   at System.Diagnostics.Tests.ProcessTests.ProcessNameMatchesScriptName() in /__w/1/s/src/System.Diagnostics.Process/tests/ProcessTests.Unix.cs:line 174
```

cc @stephentoub

**Comment by stephentoub** [comment]
This also just failed on Debian here. Details here:
https://github.com/dotnet/corefx/issues/38169

**Comment by MarcoRossignoli** [comment]
again here https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38133~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190603.3/workItem/System.Diagnostics.Process.Tests/analysis/xunit/System.Diagnostics.Tests.ProcessTests~2FProcessNameMatchesScriptName

**Comment by tmds** [comment]
Interesting, 2 Debian fails in such a short time, and none in the weeks before.

**Comment by MarcoRossignoli** [comment]
btw I've seen similar behaviour on windows fixing same issue https://github.com/dotnet/corefx/issues/35783

**Comment by danmosemsft** [comment]
I saw a sporadic failure on WSL where the name was wrong entirely:
```
      System.Diagnostics.Tests.ProcessTests.ProcessNameMatchesScriptName [FAIL]
        Assert.Contains() Failure
        Not found: (ProcessNameMatc)
        In value:  9407 (dotnet) S 8713 8614 1136 1027 0 0 0 0 0 0 0 0 0 0 20 0 1 0 366663 439087394816 11 18446744073709551615 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

        Stack Trace:
          /home/dan/git/corefx/src/System.Diagnostics.Process/tests/ProcessTests.Unix.cs(176,0): at System.Diagnostics.Tests.ProcessTests.ProcessNameMatchesScriptName()
```
