### ISSUE TITLE
Add string.CreateAsync

### ISSUE THREAD

**Issue by JeffCyr** [dotnet/corefx#37749]
# Rationale
The existing `public static string Create<TState>(int length, TState state, SpanAction<char, TState> action)` function is useful to reduce allocations when building a string. This proposal describes an async version that could be used to create a string asynchronously. This could be used by an async deserializer when it knows the length of a string and then receives the chars asynchronously by chunks.

# Proposed API

```c#
public class String
{
    //...

    public static async ValueTask<string> CreateAsync<TState>(int length, TState state, AsyncMemoryAction<char, TState> action);
}

namespace System.Buffers
{
    //...

    public delegate ValueTask AsyncMemoryAction<T, in TArg>(Memory<T> memory, TArg arg);
}
```

# Usage

```c#
int length = await context.ReadLengthAsync();

string s = await string.CreateAsync(length, context, async (chars, state) =>
{
    while (!chars.IsEmpty)
    {
        ReadOnlyMemory<char> chunk = await state.ReadCharsAsync(chars.Length);
        if (chunk.IsEmpty) throw ...

        chunk.CopyTo(chars);
        chars = chars.Slice(chunk.Length);
    }
});
```

# Implementation

A PR with the proposed changed is available on my fork: https://github.com/JeffCyr/corefx/pull/1

```c#
public static async ValueTask<string> CreateAsync<TState>(int length, TState state, AsyncMemoryAction<char, TState> action)
{
    if (action == null)
        throw new ArgumentNullException(nameof(action));

    if (length <= 0)
    {
        if (length == 0)
            return string.Empty;
        throw new ArgumentOutOfRangeException(nameof(length));
    }

    string result = FastAllocateString(length);
    await action(new Memory<char>(result, 0, length), state);

    return result;
}
```

**Comment by JeffCyr** [comment]
cc @terrajobst, @stephentoub 

Do you think this have value?

**Comment by stephentoub** [comment]
> Do you think this have value?

Some, but in my opinion not enough to add it as an API right now.  This is going to add the overhead of another async method that yields, which is probably around 130 bytes, so the break even point in memory would be at best something like 65 characters, meaning for many strings you'd be better off just allocating a char[] and then creating a string from it.  Plus many developers that cared about this level of optimization would probably push back on any such overhead and would instead opt for the (unsafe-and-not-recommended-but-people-do-it-anyway) approach to creating a string and then writing into it.   There are other downsides, too, such as the `Memory<char>` allowing you to get the partially created string out of it, putting async methods onto String (it doesn't currently have any), etc.  And if you cared a lot about perf in such situations, you'd probably also want to avoid the string entirely, and instead use `ArrayPool<char>` with `ReadOnlySpan<char>` for functionality.

**Comment by JeffCyr** [comment]
Alright I will close the issue then
