### ISSUE TITLE
HttpWebRequest set host no need port;how can set

### ISSUE THREAD

**Issue by windsOne** [dotnet/corefx#37742]
![image](https://user-images.githubusercontent.com/14890297/57901109-22748580-7896-11e9-81d6-e2dfbd985622.png)

![image](https://user-images.githubusercontent.com/14890297/57900979-995d4e80-7895-11e9-9f07-571478cc2912.png)

What should I do to avoid the port being added?

**Comment by windsOne** [comment]
I noticed that  .net framework 
https://referencesource.microsoft.com/#System/net/System/Net/HttpWebRequest.cs,edb176a48e29d9dd

Is the judgment about whether the port is needed

**Comment by huoyaoyuan** [comment]
![image](https://user-images.githubusercontent.com/5644458/57971244-fce29b80-79bd-11e9-9ded-d975547e6d91.png)
![image](https://user-images.githubusercontent.com/5644458/57971248-0cfa7b00-79be-11e9-9175-0536cb66336a.png)
试了几个路径，均无法复现

**Comment by windsOne** [comment]
use .net core  
I
![image](https://user-images.githubusercontent.com/14890297/57983793-5f07d300-7a88-11e9-80ef-a8105658f1b4.png)

![image](https://user-images.githubusercontent.com/14890297/57983769-2536cc80-7a88-11e9-9e3b-1ab706c405c1.png)
![image](https://user-images.githubusercontent.com/14890297/57983772-2c5dda80-7a88-11e9-803b-3cf49fa96c92.png)
And I said that the .net framework can be. But the .net core doesn't work. The source code does not implement the corresponding function.

**Comment by huoyaoyuan** [comment]
@windsOne I can't interpret your previous English explanation as you're running on .net core.
For .net core application, just don't use `WebRequest` related apis; use `HttpClient` instead.
Is there any functionality lacked on and `HttpRequestMessage`?

**Comment by windsOne** [comment]
@huoyaoyuan 
What do you mean by using HttpClient?

**Comment by wfurt** [comment]
I don't understand what the issue is. Do you have simple runable repro code @windsOne  instead of screen shots?

As far as the HttpClient: it is just alternative API to HTTP functionality. (and has much better performance  and functionality)
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netcore-2.2
