### ISSUE TITLE
COM port not sending ESC commands - Ubuntu 

### ISSUE THREAD

**Issue by blelem** [dotnet/corefx#37770]
I experienced some problems while sending ESC commands on Ubuntu, using System.IO.Ports, with the dotnet v3.0.0-preview5.

The following code works fine (compiled and running on dotnet v3.0.0-preview5) on a Windows machine, but fails on Linux.  The message is never sent.

            // msg = ESC-@ Hello World
            byte[] msg = new byte[] { 0x1B, 0x40, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x20, 0x77, 0x6f, 0x72, 0x6c, 0x64 };

            port.BaseStream.Write(msg, 0, msg.Length);
            port.BaseStream.Flush();

That bit of code comes from our legacy code, where it works properly on a Ubuntu system, compiled with .NET 4.7, running atop Mono. 

When omitting the ESC command (the 0x1B, 0x40), the message is sent as expected. 
Writing the original message directly to the port, without messing round with the baseStream also works fine.

            byte[] msg = new byte[] { 0x1B, 0x40, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x20, 0x77, 0x6f, 0x72, 0x6c, 0x64 };
            port.Write(msg, 0, msg.Length); //Works on both Linux and Windows

suggested labels: area-System.IO, os.linux
Tagging @wfurt, just in case.

**Comment by wfurt** [comment]
if feels certainly suspicious that ESC would trigger this.
I would expect cfmakeraw() to disable any any special character process but maybe there is something else. 
I assume this is /dev/ttySx on x64 platform? 

cc: @krwq

**Comment by blelem** [comment]
Yes, I was using /dev/ttySx on x64 platform.

**Comment by krwq** [comment]
@blelem I've just tried running this with USB to U(S)ART with RX/TX connected. And it's not reproing for me. Here is the full repro I tried (also tried writing directly using SerialPort.Write and also no issues).

```csharp
            using (SerialPort port = new SerialPort("/dev/ttyUSB0"))
            {
                port.Open();
                byte[] msg = new byte[] { 0x1B, 0x40, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x20, 0x77, 0x6f, 0x72, 0x6c, 0x64 };

                port.BaseStream.Write(msg, 0, msg.Length);
                port.BaseStream.Flush();

                byte[] bytes = new byte[msg.Length];
                int totalBytesRead = 0;
                while (totalBytesRead < bytes.Length)
                {
                    int bytesRead = port.BaseStream.Read(bytes, totalBytesRead, bytes.Length - totalBytesRead);
                    totalBytesRead += bytesRead;
                }

                Assert.Equal(bytes, msg); // Xunit Assert
            }
```

What version of System.IO.Ports package are you using on linux?

**Comment by blelem** [comment]
Where can I get the System.IO.ports package version information? I used dotnet core preview 5 on ubuntu, on a computer sporting an Intel® Pentium® N3710.

I'll try later today to repro in the same environment but with preview 9.

**Comment by blelem** [comment]
The behavior with dotnet preview 9, System.IO.ports 4.6.0-preview9.19421.4 seems to be quite different than 4 months ago.  

Writing to the base stream gives quite random results, sometimes the data is sent, sometimes not. Roughly 4 out of 5 of my messages were not sent over the COM wire. The content of the data written doesn't seem to matter, the write will randomly come out of the com port.
```
 port.BaseStream.Write(msg1, 0, msg1.Length);
 port.BaseStream.Flush();
```


On the other hand, writing to the port works reliably.  

``` 
  port.Write(msg2, 0, msg2.Length);
```
 
Here is my test code. I listen to the output of the com port using a COM port sniffer (EZ-Tap Pro).

```
using System;
using System.IO.Ports;

namespace BugReport_EscapeSequenceAndPort
{
    class Program
    {
        static void Main(string[] args)
        {


            var AlloCounter = 0;
            var HelloCounter = 0;
            using (SerialPort port = new SerialPort("/dev/ttyS3", 19200))
            {
                port.Open();
                do
                {
                    Console.WriteLine("Press 1 -> port.BaseStream.Write");
                    Console.WriteLine("Press 2 -> port.Write");
                    var key = Console.ReadKey(true).Key;

                    if (key == ConsoleKey.D1)
                    {
                        Console.WriteLine("port.BaseStream.Write");

                        byte[] msg1 = System.Text.Encoding.ASCII.GetBytes($"Hello world {HelloCounter}\n");
                        port.BaseStream.Write(msg1, 0, msg1.Length);
                        port.BaseStream.Flush();

                        HelloCounter++;
                    }
                    if (key == ConsoleKey.D2)
                    {
                        Console.WriteLine("port.Write");

                        byte[] msg2 = System.Text.Encoding.ASCII.GetBytes($"Allo  world {AlloCounter}\n");
                        port.Write(msg2, 0, msg2.Length);

                        AlloCounter++;
                    }

                } while (true);
            }
        }

    }
}
```
And here is the output as read by the COM sniffer. Most of the "hello world" sent by the code were not read by the sniffer. All "Allo World" were correctly read.

![image](https://user-images.githubusercontent.com/2476938/64319335-c2c8f400-cfc4-11e9-8ed1-11018c4d1221.png)

For the test I used dotnet preview 9, System.IO.ports 4.6.0-preview9.19421.4, on a Ubuntu machine.

**Comment by krwq** [comment]
@bielem could you try removing Flush and see if this makes any difference?

Looking at the code Write(byte[], int, int) is just calling `BaseStream.Write`:
https://github.com/dotnet/corefx/blob/master/src/System.IO.Ports/src/System/IO/Ports/SerialPort.cs#L1179

so the only diff would be `Flush`.

**Comment by krwq** [comment]
I think I know what the problem is, will send PR shortly (comment about Flush is correct)

**Comment by blelem** [comment]
Yes, removing the Flush fixed the problem on the Ubuntu machine. I should have tried that earlier.😣

**Comment by krwq** [comment]
@blelem I'll fix the Flush problem soonish. Seems the extra 0 I've seen is unrelated to the tcflush/tcdrain call I'm making - it only happens on 1st byte for me and seems to be specific to the device I use
