### ISSUE TITLE
Current status of graphics library development.

### ISSUE THREAD

**Issue by JimBobSquarePants** [dotnet/corefx#3778]
Hi all,
I've been following the various conversations regarding graphics in corefx: #1563, #489, etc and also following the progress of the library in corefxlab https://github.com/dotnet/corefxlab/tree/master/src/System.Drawing.Graphics and I'm still left wondering what the overall plan is. Progress in the lab repo seems to have stopped and there seems to be no further discussion I can find anywhere on what is happening.

I'm the primary author of the project [ImageProcessor](https://github.com/JimBobSquarePants/ImageProcessor/) which I wrote to make System.Drawing a little easier to work with. It's been fairly successful in adoption but as far as I can fathom my work (~3 years) will become obsolete very soon.

Since corefx was announced I've started working on a library which can do basic stuff like encode/decode pngs, bmps, jpegs, and gifs (animated too), I've partially implemented some primitives for shapes and colors, and am experimenting with resampling algorithms now.

All that work can be found [here](https://github.com/JimBobSquarePants/ImageProcessor/tree/Core)

I'm super uneasy about doing all this work though as I don't want it to be in vain, superseded immediately by something out of Microsoft. Should I continue? If so is it something that you would think the community could invest in and help me deliver (Graphics is tricky stuff and I'm no computer scientist).

**Comment by JimBobSquarePants** [comment]
Hello?

**Comment by ikourfaln** [comment]
so ?!!

**Comment by alexperovich** [comment]
@terrajobst do we have any plans in this area?

**Comment by karelz** [comment]
@JimBobSquarePants very sorry for the extra delay. We are finally getting to proper triage of all issues on GitHub.
To my knowledge we do not have any immediate or medium-term plans to create new libraries. Definitely not unless there is a high demand from customers.
I think that it is a great thing that you have a library which is used. I would recommend you to keep working on it. If we ever go into graphics library space, we should try to look for existing solutions first (at least I would).

If you have any feedback on CoreFX from your point of view and if you think that some of your types should move to the platform, please let us know.

Closing for now as the question was (finally) answered :).

**Comment by JimBobSquarePants** [comment]
Thanks @karelz I appreciate it. 

We've been making excellent progress so far with my xPlat library now called [ImageSharp](https://github.com/JimBobSquarePants/ImageSharp) and would welcome any input from anyone interested in the subject.
