### ISSUE TITLE
Add API reviewing to the New Contributor Guide

### ISSUE THREAD

**Issue by aaronfranke** [dotnet/corefx#37796]
https://github.com/dotnet/corefx/wiki/New-contributor-Docs#contributing-guide

The API review process is required for new APIs, but it is not mentioned at all on this page. This issue is a request for this information to be added somewhere in the new contributor guide.

https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md

**Comment by ahsonkhan** [comment]
cc @karelz

**Comment by danmosemsft** [comment]
I think it would also be useful to specifically break out how to format an API request. The document above covers the whole flow with that only mentioned briefly, with a link to an old issue as an example. We link to this very often and that would make it clearer.

**Comment by danmosemsft** [comment]
-> Future as this is not must fix to ship.

**Comment by karelz** [comment]
The info is already captured on the WIki to some extent -- see e.g.: https://github.com/dotnet/corefx/wiki/Contributions#add--expose-api-in-corefx-net-core-only
