### ISSUE TITLE
Remove UTF-16 encoding text within the docs for ReadOnlySpan<char> overloaded APIs on Utf8JsonWriter

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#37794]
See https://github.com/dotnet/corefx/pull/37789#discussion_r285431754 for context

For example, remove the text that specifies UTF-16 text from summary/param docs:
https://github.com/dotnet/corefx/blob/27dae83598c87e3cf4b139c8c981c13fe8e9a81e/src/System.Text.Json/src/System/Text/Json/Writer/Utf8JsonWriter.WriteProperties.String.cs#L71-L74

Similarly, update the string-based overloads as well (the summary text is fine, but param tags need to be updated):
https://github.com/dotnet/corefx/blob/27dae83598c87e3cf4b139c8c981c13fe8e9a81e/src/System.Text.Json/src/System/Text/Json/Writer/Utf8JsonWriter.WriteProperties.String.cs#L53-L57

cc @bartonjs

**Comment by watfordgnf** [comment]
I've put together the basics for this and am wondering about `JsonEncodedText` and whether or not its methods should have their summaries and parameters updated.

**Comment by ahsonkhan** [comment]
Good point. Yes, for any `ROS<char>` API that is an overload of a string one, we should remove the UTF-16 encoding since its implied, and in this case, too much information might actually cause confusion. This includes `JsonEncodedText`

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/dotnet/corefx/pull/37866
