### ISSUE TITLE
Parsing invalid Enum value throwing NRE instead of corresponding JsonReaderException

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/corefx#37808]
Parsing invalid Enum value throwing NRE, i am not sure what exception it should throw but pretty sure  NRE is not expected
```csharp
    [Flags]
    public enum StoreColor
    {
        Black = 1,
        Red = 2,
        Yellow = 4,
        White = 8,
        DarkGoldenrod = 16
    }
    [Fact]
    public static void InvalidValueNegativeStringNumber()
    {
        JsonReaderException ex = Assert.Throws<JsonReaderException>(() =>
        {
            JsonSerializer.Parse<StoreColor>("\"-1\"");
        });

        Assert.Equal("Error message", ex.Message);
    }

    [Fact]
    public static void InvalidValueDash()
    {
        JsonReaderException ex = Assert.Throws<JsonReaderException>(() =>
        {
            JsonSerializer.Parse<StoreColor>("\"-\"");
        });

        Assert.Equal("Error message.", ex.Message);
    }

<message>
<![CDATA[
System.NullReferenceException : Object reference not set to an instance of an object.
]]>
</message>
<stack-trace>
<![CDATA[
at System.Text.Json.Serialization.Tests.EnumTests.InvalidValueDash() in D:\dotnet\corefx\src\System.Text.Json\tests\Serialization\EnumTests.cs:line 516
]]>
</stack-trace>
```

**Comment by Cybrosys** [comment]
Seeing as the above enum doesn't specify a specific underlying data type, I do believe signed int will be used.

This means that it's valid to cast -1 to StoreColor. I tested the above using Newtonsoft Json and it was able to parse the negative string value to the the StoreColor enum with the underlying value set to -1. 

The second test however will fail becasue it can't convert "-" to a number.

The first test will fail if the underlying type of the enum is explicitly specified to be byte or another unsigned data type.

**Comment by buyaa-n** [comment]
@Cybrosys yes they are invalid values my point was it shouldn't throw NRE

**Comment by watfordgnf** [comment]
Is this problem actually with the test case? Which line is 516 in your example?

`JsonReaderException` is internal to `System.Text.Json` and would not be caught by a user, so the test should use `JsonException`.

The following works:
```csharp
        [Fact]
        public static void ReadEnumFail()
        {
            Assert.Throws<JsonException>(() => JsonSerializer.Parse<JsonTokenType>(@"""-1"""));
            Assert.Throws<JsonException>(() => JsonSerializer.Parse<JsonTokenType>(@"""-"""));
        }
```
Attempting to change this to:
```csharp
        [Fact]
        public static void ReadEnumFail()
        {
            Assert.Throws<JsonReaderException>(() => JsonSerializer.Parse<JsonTokenType>(@"""-1"""));
            Assert.Throws<JsonReaderException>(() => JsonSerializer.Parse<JsonTokenType>(@"""-"""));
        }
```
Has Visual Studio suggest I add the following using:
```csharp
using Newtonsoft.Json;
```

**Comment by buyaa-n** [comment]
@watfordgnf thank you for looking into it, the error line number was produced from long test file run, not only these tests, that's why line number is 516.
JFYI `JsonReaderException  `is public to `System.Text.Json` and we do not need to use `JsonException` exception from Newtonsoft

Anyways seems this issue is fixed as the above tests now running successfully, closing this issue
