### ISSUE TITLE
PipeReader.CopyToAsync stuck in an endless loop

### ISSUE THREAD

**Issue by shutdown256** [dotnet/corefx#37802]
There is a bug either in `PipeReader.CopyToAsyncCore()` or `ReadOnlySequence.TryGet()`: 

When `ReadOnlySequence.TryGet()` reaches final segment it will return true and this final memory but it will also set position as `default(SequencePosition)` - I don't know if this is by design but `CopyToAsyncCore()` method does not take it in consideration and it will copy the memory but not advance the reader - this will cause it to repeat this data indefinitely.

I propose 2 solutions:
a) return `ReadOnlySequence.End` as position when returning final segment in `TryGet()`
b) check if position is `.equal(default)` in `PipeReader.CopyToAsyncCore()` and if so, set `consumed = buffer.End` and break

**Comment by ahsonkhan** [comment]
cc @davidfowl, @justinvp

**Comment by justinvp** [comment]
@ahsonkhan, just curious, why am I cc'd?

**Comment by ahsonkhan** [comment]
OOPs, I meant @jkotalik :)

**Comment by davidfowl** [comment]
Odd, how did any of the tests pass...

**Comment by shutdown256** [comment]
Actually I found another bug in the `PipeReader.CopyToAsyncCore()` - should I put here or file a separate issue?

**Comment by jkotalik** [comment]
Go ahead and post it here. We'll move it to a separate issue if we deem it too large to tackle with a single pull request.

**Comment by davidfowl** [comment]
@shutdown256 OR just sent a PR to fix it 😄

**Comment by shutdown256** [comment]
`ReadResult result = await ReadAsync(cancellationToken).ConfigureAwait(false);` should be before the try/finally block because if you cancel the read operation the finally clause will try to advance reader that is not in reading state and instead of OperationCancelledException you will end up with InvalidOperationException.

@davidfowl I would but i'm not exactly stoked to clone the entire corefx repo...
