### ISSUE TITLE
Doc: Duplicate references to the same Interface: BufferBlock

### ISSUE THREAD

**Issue by Bartolomeus-649** [dotnet/corefx#37803]
In the doc for [BufferBlock<T> Class](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.dataflow.bufferblock-1?view=netcore-2.2) the same interface is listed multiple times.
> Implements
> IDataflowBlock, IPropagatorBlock\<T,T>, IReceivableSourceBlock\<T>, 
> ISourceBlock\<T>, ISourceBlock\<TOutput>,      **// There is only one ISourceBlock interface**
> ITargetBlock\<T>, ITargetBlock\<TInput>            **// There is only one ITargetBlock interface**

Even though their declaration seem a bit different, they link to the same doc page.

Also, if you look in the namespace doc, the listed Intefaces are these:

> ## Interfaces
> Interface | Description
> :-- | :--
> IDataflowBlock | Represents a dataflow block.
> IPropagatorBlock<TInput,TOutput> | Represents a dataflow block that is both a target for data and a source of data.
> IReceivableSourceBlock<TOutput> | Represents a dataflow block that supports receiving messages without linking.
> ISourceBlock<TOutput> | Represents a dataflow block that is a source of data.
> ITargetBlock<TInput> | Represents a dataflow block that is a target for data.

At least [BatchBlock ](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.dataflow.batchblock-1?view=netcore-2.2)has the same problem as well.

**Comment by karelz** [comment]
Please file a bug on docs repo - you can even suggest changes there directly via submitting PR.
cc @mairaw
