### ISSUE TITLE
IOException on recursive Directory.Delete of path with trailing backslash

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/corefx#3780]
I observed this after we took a recent beta System.IO over in MSBuild.  Many of our tests create a directory and have a `finally` that deletes it, which suddenly started failing.  After debugging, I think this is a regression caused by 0721434, which added a call in [`RemoveDirectory`](https://github.com/dotnet/corefx/blob/0721434e19e7f9ecf8bf6dba7485f6c86827388c/src/System.IO.FileSystem/src/System/IO/Win32FileSystem.cs#L491) to canonicalize the path to extended form.  The following call then adds a backslash before calling `FindFirstFile`, but the extended path has different behavior in Win32: it no longer silently condenses double backslashes to a single path separator.

While proving to myself that I understood the bug I wrote a fix; I'll send a PR shortly.

**Comment by JeremyKuhne** [comment]
I'll fix the issue soon (and add a test)

**Comment by rainersigwald** [comment]
@JeremyKuhne For what it's worth I did both in PR #3781 (but I won't be offended if you want to go a different way).

**Comment by JeremyKuhne** [comment]
@rainersigwald Thanks! I'll merge it once we get a green CI build.
