### ISSUE TITLE
Char.IsWhiteSpace should also apply to the 0-width space

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/corefx#37817]
The `char.IsWhiteSpace` API ([here](https://docs.microsoft.com/en-us/dotnet/api/system.char.iswhitespace?view=netcore-2.2)) doesn't contain the [0-width space](http://www.codetable.net/decimal/8203) character (`8203`, or `200B`).

This can be quickly tested like so:
```csharp
char space = (char)8203;
Console.WriteLine(char.IsWhiteSpace(space)); // FALSE
string empty = space.ToString();
Console.WriteLine(string.IsNullOrEmpty(empty)); // FALSE
```

Unless this has been done deliberately for some specific reason (why?), I think it might be a good idea to just add this other character to that list, so that it could be used indirectly by both the `char.IsWhiteSpace` and `string.IsNullOrWhiteSpace` APIs.

**Comment by Wraith2** [comment]
The Unicode standard defines the zero width space as a Format character not a Separator, [char.IsWhitespace](https://github.com/dotnet/corefx/blob/e4c091186e5b2f98696e10f978c3548e14c89f0a/src/Common/src/CoreLib/System/Char.cs#L273) is checking for known ascii values or Separator Unicode category. If you want to change the designation for the character you'll need to convince the Unicode people.

**Comment by Sergio0694** [comment]
Hey @Wraith2 - thank you for your reply.
I see, and that's absolutely fine, I just wasn't sure why the API was defined that way, as the description says "[...] character is categorized as white space", and the 8203 character is called "0-width _space_".
It makes sense now, thanks! 😊
