### ISSUE TITLE
[Outerloop] [OleDb] tests SEHException - External component has thrown an exception

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/corefx#37823]
Looking at the results of outerloop tests run on master I noticed some of outerloop OLEDB tests are failing:
https://dnceng.visualstudio.com/public/_build/results?buildId=194048&view=ms.vss-test-web.build-test-results-tab

Error message
```
System.Runtime.InteropServices.SEHException : External component has thrown an exception.
```

Stack trace
```
   at System.Data.Common.UnsafeNativeMethods.ICommandText.Execute(IntPtr pUnkOuter, Guid& riid, tagDBPARAMS pDBParams, IntPtr& pcRowsAffected, Object& ppRowset)
   at System.Data.OleDb.OleDbCommand.ExecuteCommandTextForSingleResult(tagDBPARAMS dbParams, Object& executeResult) in D:\a\1\s\src\System.Data.OleDb\src\OleDbCommand.cs:line 857
   at System.Data.OleDb.OleDbCommand.ExecuteCommandText(Object& executeResult) in D:\a\1\s\src\System.Data.OleDb\src\OleDbCommand.cs:line 810
   at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method) in D:\a\1\s\src\System.Data.OleDb\src\OleDbCommand.cs:line 601
   at System.Data.OleDb.OleDbCommand.ExecuteNonQuery() in D:\a\1\s\src\System.Data.OleDb\src\OleDbCommand.cs:line 916
   at System.Data.OleDb.Tests.OleDbCommandBuilderTests.RunTest(Action`2 testAction, String memberName) in D:\a\1\s\src\System.Data.OleDb\tests\OleDbCommandBuilderTests.cs:line 152

```

The failure is on both netcoreapp and netfx and not intermittent.

All non outerloop tests seem fixed since https://github.com/dotnet/corefx/pull/37540, because the only trace of OleDb failures I've seen so far is on outerloop results.

Another related open issue: https://github.com/dotnet/corefx/issues/37411

It is yet to be confirmed if this is a product issue or the test needs to be fixed. 
cc: @saurabh500 @ViktorHofer

**Comment by maryamariyan** [comment]
@karelz I found both labels System.Data.OleDb and System.Data.

If you remember I had created this label. Seems like System.Data.Odbc is removed but System.Data.OleDb is still available. Should the OleDb label need to be removed?

**Comment by saurabh500** [comment]
@maryamariyan is this only happening in the CI outerloop, or is this reproducible on dev box as well ?

**Comment by maryamariyan** [comment]
I am not getting a local repro.

**Comment by saurabh500** [comment]
To reiterate:
JET driver was originally requested to be added as part of https://github.com/dotnet/core-eng/issues/6125
If I am understanding correctly, here are the action items:

- [ ] to reopen https://github.com/dotnet/core-eng/issues/6125 and request to remove JET driver from the CI machines (refer to step 1 of https://github.com/dotnet/corefx/pull/37825#issuecomment-494217728).
- [ ] to skip tests on x86 platform
- [ ] to skip tests if both JET and ACE are installed on the machine

**Comment by ViktorHofer** [comment]
@maryamariyan @saurabh500 can you please drive this? Would be great to get back to a sane state for OleDb and move tests back to innerloop as soon as they are passing.

**Comment by maryamariyan** [comment]
yes. this should be fixed very soon :)

**Comment by maryamariyan** [comment]
The CI changes have been submitted but will not go into effect immediately. Once that's completed and tested out, I will push up the remaining change to skip on x86 platform and add condition to skip on machines with both JET and ACE installed.

**Comment by stephentoub** [comment]
Any update on this?  If it's not going to be fixed imminently, can we disable the OleDb tests until it is?  It's causing hundreds of outerloop test failures, which makes it more difficult to see actual failures to pay attention to.
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F37990~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190528.4/workItem/System.Data.OleDb.Tests

**Comment by MattGal** [comment]
@stephentoub we're hoping to roll out the changes (to remove the extra driver installs) today.  I'll try to update this thread when that happens.

**Comment by stephentoub** [comment]
Great.  Thanks, @MattGal.

**Comment by maryamariyan** [comment]
I prepared the follow up PR that will need to get merged after the dnceng changes get rolled out here: https://github.com/dotnet/corefx/pull/38024

**Comment by maryamariyan** [comment]
Prepared and merged https://github.com/dotnet/corefx/pull/38090 ignores oledb tests temporarily while the fix for oledb is underway.
(to help track other outerloops results better)

**Comment by maryamariyan** [comment]
Closing via https://github.com/dotnet/corefx/pull/38024
