### ISSUE TITLE
Add ValueTuple operators to System.Numerics.Vectors structs

### ISSUE THREAD

**Issue by aaronfranke** [dotnet/corefx#37822]
Edit: Changed from `Tuple` to `ValueTuple`

The basic idea of `ValueTuple` operators is to allow easy conversion between these types and the types of any other math library, without them having to know about each other:

        Vector2 v = new Vector2(5, 6);
        // Option 1
        OtherVec2 m = (ValueTuple<float, float>)v;
        // Option 2
        ValueTuple<float, float> t = v;
        OtherVec2 n = t;

Example implementation:

        public static implicit operator ValueTuple<float, float>(Vector2 value)
        {
            return ValueTuple.Create(value.X, value.Y);
        }

        public static implicit operator Vector2(ValueTuple<float, float> value)
        {
            return new Vector2(value.Item1, value.Item2);
        }

You may notice that the `Tuple` operators are all `implicit`. C# cannot implicitly double-cast:

        Vector2 v = new Vector2(5, 6);
        OtherVec2 m = v; // Error cannot convert type

It is impossible to perform any conversions with `ValueTuple` operators without the file containing the word "`ValueTuple`", so there is no danger of a `Vector4` accidentally becoming a `Quaternion` or anything.

Implementing this proposal would mean greater interoperability with math libraries that choose to also implement `ValueTuple` operators.

**Comment by Gnbrkm41** [comment]
Is there a reason you'd want to ditch `Vector2` and use very ambiguous & generic `ValueTuple<float, float>`?

**Comment by aaronfranke** [comment]
@Gnbrkm41 As I explained, it's so that I can convert between types easily. What if I wanted to take a `System.Numerics.Vector2` and turn it into a `Godot.Vector2` or `UnityEngine.Vector2`? If all of these types were to implement these operators, it's easy to do the above. 

If this is an operation performed frequently and/or the type is long, the tuple could even be aliased:

    using System.Numerics;
    using Trans2D = System.Tuple<float, float, float, float, float, float>; // Or ValueTuple<>
    
        // Somewhere else
        Matrix3x2 m = new Matrix3x2(1, 2, 3, 4, 5, 6);
        
        Godot.Transform2D t = (Trans2D)m;
        Matrix3x2 n = (Trans2D)t;

Without (value) tuple operators:

        Matrix3x2 m = new Matrix3x2(1, 2, 3, 4, 5, 6);
        
        Godot.Transform2D t = new Godot.Transform2D(m.M11, m.M21, m.M12, m.M22, m.M31, m.M32);
        Matrix3x2 n = new Matrix3x2(t.x.x, t.y.x, t.x.y, t.y.y, t.o.x, t.o.y);

**Comment by tannergooding** [comment]
You could also just provide helper extensions methods in your library.

I don't think that converting a `S.N.Vector` type to a tuple is, in general, a desirable operation. For most libraries, you likely want to operate with their vector types all the way through, as that is generally the most efficient for that platform. Conversion should probably be a limited operation where you rely on something like `unsafe` code or helper methods to do the conversion where required.

**Comment by tannergooding** [comment]
I also don't think `Tuple` is the right type. `Tuple` is a class (reference type) and creating a short-lived GC tracked object just to convert from one platforms value type to anothers is the wrong thing to do.

If this were to be done, it would need to be `ValueTuple`, but again, that is a very inefficient way to do it and reinterpreting the underlying bits is likely the better option (assuming that both platforms represent the `Vector2` the same).

**Comment by Gnbrkm41** [comment]
If the `Godot.Vector*` or `UnityEngine.Vector*` types did implement conversion operators to/from ValueTuple, then it could have been somewhat reasonable, but it looks like none of them implement such conversion operators. (I might be wrong, I use neither of them)

Given that none of the mentioned types don't implement such operators, it would require some work on all the types on their side to actually be useful; if so, why don't they just define operators that can go straight to/from `System.Numerics.Vector*` in the first place, instead of going through conversion to `Tuple/ValueTuple`?

**Comment by aaronfranke** [comment]
> if so, why don't they just define operators that can go straight to/from `System.Numerics.Vector*` in the first place, instead of going through conversion

Because:

1. Those types would require having the `System.Numerics` package installed to work. It doesn't really make sense to require having `System.Numerics` if they're going to implement their own vectors, yet the ability to convert between them would still be nice.

2. What if math libraries want to convert between each other? For example, a math library designed for working in both Unity and Godot. The library would need to support conversions to both Unity and Godot's types. And if you wanted to take the library and use it in another engine, or use two math libraries together, then they would need further more conversions. Yet if they could convert to `ValueTuple` then they could be converted to anything that also supports converting to `ValueTuple`.

@tannergooding What do you mean by reinterpreting the bits?

**Comment by Gnbrkm41** [comment]
1. It's likely that they don't have to. `System.Numerics` namespace and most of the types belonging to the namespace are present in most of the recent framework versions already. Looks like [.NET Core 1.0+, .NET Framework 4.6+, Mono 5+, UWP 10.1+ have them](https://apisof.net/catalog/System.Numerics.Vector2) already, and eventually .NET Standard 2.1+ will adopt them. Also, `System.Numerics` package doesn't look like a bad dependency to have, considering that it's uploaded directly by Microsoft; unless you plan to only target <.NET Standard 2.1 and have absolutely no dependency on other packages, you can use these types in many places already.

2. Considering the point above they could go through `System.Numerics.Vector*`, or even better, just add tons of overloads that accept framework-agnostic `System.Numerics.Vector*` maybe (which, I think is unlikely to happen, but)

Reinterpreting the bits I'm guessing simply mean doing something like `*(Godot.Vector2)&anotherVector2`, but it only works under the assumption that "both platforms represent the Vector2 the same".

**Comment by aaronfranke** [comment]
Regarding 2: There are many common math types that don't exist in System.Numerics. Just to name a few, AABB and Rectangles, 3D rotation basis (matrix 3x3), integer vectors (Vector2i / Vector2Int etc), and floating point colors (TBH this should be a proposal in its own right, .NET Core could use these...)

**Comment by aaronfranke** [comment]
Ok, so I'm going to close this issue then. I think the fact that `System.Numerics` is included by default in newer versions of .NET and Mono make this a non-issue, since (for the most part) we could simply define operators that convert to `System.Numerics` types. The only things projects have to worry about is: 

* Complex and potentially niche types as mentioned above.

* Using a new enough version of .NET or Mono that includes `System.Numerics`.
