### ISSUE TITLE
Corefx coding conventions don't match .editorconfig settings

### ISSUE THREAD

**Issue by AdamYoblick** [dotnet/corefx#37828]
The coding convensions say to use var when the type is apparent, but the editorconfig specifies to never use var:

https://github.com/dotnet/corefx/blob/master/.editorconfig#L41

:)

**Comment by Gnbrkm41** [comment]
doesn't `false|none` mean no suggestions regarding that matter? looks like it only makes suggestions on `var (elsewhere)` cases, which means that it would not care whether you use `var` or explicit types as long as it's clear which type you're using.

**Comment by Gnbrkm41** [comment]
Thought the coding convention was to allow `var ` only when type is apparent (but allow explicit types if one prefers it), and otherwise always use explicit types.

**Comment by tannergooding** [comment]
`false` means that the IDE won't generate new code that uses `var`. The level `none` means that you won't get any notification if you do the wrong thing.

I think, in general, it would be good to make the `.editorconfig` match https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md and to eventually enforce it.

Given that `.editorconfig` is also hierarchical in nature, it is possible for individual projects to have different presets if they still fall within the repo style guidelines and better match the area owners preferences.

**Comment by tannergooding** [comment]
CC. @danmosemsft, @ericstj, @eerhardt since this came up during standup the other day.

**Comment by ViktorHofer** [comment]
Closing as @stephentoub changed this in https://github.com/dotnet/corefx/commit/86789bdf585c3d199016749bfe3ad95261df3c5f
