### ISSUE TITLE
JsonSerializerOptions.IgnoreReadOnlyProperties is not respected during deserialization

### ISSUE THREAD

**Issue by danadesrosiers** [dotnet/corefx#37844]
According to the doc block in JsonSerializerOptions, the IgnoreReadOnlyProperties option should apply to both serialization and deserialization.  
https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs#L125-L133

This makes sense, serialization and deserialization should have consistent behavior.  If I serialize, then deserialize, I would expect to end up with the same object.

Currently, the IgnoreReadOnlyProperties option is respected for serialization, but not deserialization.  The default value of the option is `false`, so if I have an object with a read only property, when I serialize, the property is included in the json, but when I deserialize, the property is ignored and its data is lost.  This seems like a bug.

Example:
```csharp
public class JsonSerializerTest
{
    [Fact]
    public void TestReadOnlyProperty()
    {
        var original = new ObjectWithReadyOnlyProperty(1) {MyData = "Test"};
        Assert.Equal(1, original.Id);  // The Id property is set to 1

        // serialize
        var json = JsonSerializer.ToString(original);
        Assert.Equal(@"{""Id"":1,""MyData"":""Test""}", json);  // Id property is serialized to JSON

        // deserialize
        var newObject = JsonSerializer.Parse<ObjectWithReadyOnlyProperty>(json);
        Assert.Equal(1, newObject.Id);  // FAIL: Id is 0, the value was lost :(
    }

    public class ObjectWithReadyOnlyProperty
    {
        public int Id { get; }  // read only
        public string MyData { get; set; }

        private ObjectWithReadyOnlyProperty() {}

        public ObjectWithReadyOnlyProperty(int id)
        {
            Id = id;
        }
    }
}
```

In addition to this being inconsistent and having the potential to unexpectedly lose data, I think the ability to deserialize read only properties is important because it makes is possible to deserialize to an immutable object.  That is what I was trying to accomplish when I encountered this.

**Comment by ahsonkhan** [comment]
cc @steveharter

**Comment by steveharter** [comment]
@danadesrosiers the `IgnoreReadOnlyProperties` is not set in your test.

Also on deserialize, no read-only properties are set whether or not  `IgnoreReadOnlyProperties` is true or false.

Here's an updated version:
```cs
        [Fact]
        public static void TestReadOnlyProperty()
        {
            var original = new ObjectWithReadyOnlyProperty(1) { MyData = "Test" };
            Assert.Equal(1, original.Id);  // The Id property is set to 1

            var options = new JsonSerializerOptions();
            options.IgnoreReadOnlyProperties = true;

            // serialize
            var json = JsonSerializer.ToString(original, options);
            Assert.Equal(@"{""MyData"":""Test""}", json);  // Id property is not serialized to JSON

            // deserialize
            var newObject = JsonSerializer.Parse<ObjectWithReadyOnlyProperty>(json);
            Assert.Equal(0, newObject.Id);  // Id is 0 since that is the default value of the field
        }
```

**Comment by danadesrosiers** [comment]
Hi, @steveharter 

Thanks for taking a look.  I am interested in the case when IgnoreReadOnlyProperties is `false`.  I meant to explicitly set the option, but it is the default value, so it wasn't strictly necessary.

I understand that no read-only properties are set on deserialize whether or not IgnoreReadOnlyProperties is true or false.  That is the behavior that I believe to be incorrect, for the reasons described above.  Additionally, it is not consistent with the default behavior of Newtonsoft Json.Net.

Newtonsoft deserializes readonly:
```csharp
[Fact]
public void TestReadOnlyPropertyDeserializesNewtonsoft()
{
    var original = new ObjectWithReadyOnlyProperty(1) {MyData = "Test"};
    Assert.Equal(1, original.Id);  // The Id property is set to 1

    // serialize
    var json = JsonConvert.SerializeObject(original);
    Assert.Equal(@"{""Id"":1,""MyData"":""Test""}", json);  // Id property is serialized to JSON

    // deserialize
    var newObject = JsonConvert.DeserializeObject<ObjectWithReadyOnlyProperty>(json);
    Assert.Equal(1, newObject.Id);  // The Id property is set to 1
}
```

JsonSerializer does not 
```csharp
[Fact]
public void TestReadOnlyPropertyDeserializes()
{
    var original = new ObjectWithReadyOnlyProperty(1) {MyData = "Test"};
    Assert.Equal(1, original.Id);  // The Id property is set to 1

    var options = new JsonSerializerOptions();
    options.IgnoreReadOnlyProperties = false;

    // serialize
    var json = JsonSerializer.ToString(original, options);
    Assert.Equal(@"{""Id"":1,""MyData"":""Test""}", json);  // Id property is serialized to JSON

    // deserialize
    var newObject = JsonSerializer.Parse<ObjectWithReadyOnlyProperty>(json, options);
    Assert.Equal(1, newObject.Id);  // FAIL: Id is 0, the value was lost
}
```

What is the reason not to deserialize read only properties?  It seems to me it makes sense to deserialize anything with a public getter by default.

**Comment by krwq** [comment]
@danadesrosiers I don't believe the intent of this property was to work for deserialization. I.e. if I implemented:

```csharp
int Foo { get => 42; }
```

the round-tripping won't work as well but serializing this property is possible - the fact that there is a backing field seem to be an implementation detail and I don't believe it makes sense to deserialize it.

**Comment by ahsonkhan** [comment]
> Newtonsoft deserializes readonly

After talking to @JamesNK, Newtonsoft does not deserialize readonly properties. It does, however, support non-default constructors. That is why the sample works. If you removed the `ObjectWithReadyOnlyProperty(int id)` ctor, Newtonsoft won't deserialize the property either.

```C#
[Fact]
public static void SerializeStructsWorks()
{
    var original = new ObjectWithReadyOnlyProperty() {};
    Assert.Equal(1, original.Id);  // The Id property is set to 1

    // deserialize
    var newObject = JsonConvert.DeserializeObject<ObjectWithReadyOnlyProperty>(@"{""Id"":2,""MyData"":""Test""}");
    Assert.Equal(2, newObject.Id);  // The Id property doesn't change, and remains 1, as expected
}
public class ObjectWithReadyOnlyProperty
{
    public int Id { get => 1; }  // read only
    public string MyData { get; set; }

    public ObjectWithReadyOnlyProperty() { }
}
```

Just like Newtonsoft, the System.Text.Json deserializer does not deserialize readonly properties. The feature that's missing is support for non-default ctors, which is a known limitation for v1 of the built-in library.

**Comment by danadesrosiers** [comment]
@ahsonkhan, thanks for tracking that down.  That approach does make sense.  Is there any idea at this point when the non-default ctor feature might be available?  Sounds like some time after .NET Core 3.0 goes to GA.

**Comment by ahsonkhan** [comment]
> Sounds like some time after .NET Core 3.0 goes to GA.

Yes, I don't think this feature will make it to 3.0 and planned for vNext. We should file an issue for Future to track this, and maybe we can pull it in, time permitting (though its unlikely at this point).
