### ISSUE TITLE
BitArray throws IndexOutOfRangeException when unmet shrink threshold

### ISSUE THREAD

**Issue by bricelam** [dotnet/corefx#37849]
``` csharp
var left = new BitArray(64);
var right = new BitArray(32);

// NB: Since the shrink threshold (256) isn't met, the underlying int array isn't resized
left.Length = 32;

// System.IndexOutOfRangeException: Index was outside the bounds of the array.
left.Or(right);
```

The `Or` operation (and probably others) assume that the length of underlying int arrays of both operands are equal. But this isn't the case when the arrays aren't actually resized when the BitArray length changes.

cc @ajcvickers @Pilchie

**Comment by Pilchie** [comment]
@danmosemsft ?

**Comment by danmosemsft** [comment]
@tannergooding  maybe one you could look at?

**Comment by Gnbrkm41** [comment]
I think I can submit a PR for this. Feel free to reject if it's undesirable 😁
