### ISSUE TITLE
Cannot build corefx on Ubuntu 18.04 machines

### ISSUE THREAD

**Issue by tarekgh** [dotnet/corefx#37868]
getting the errors:

```
/home/tarek/oss/corefx/external/runtime/runtime.depproj : error NU1102: Unable to find package Microsoft.NETCore.Platforms with version (>= 3.0.0-preview6.19271.9)
/home/tarek/oss/corefx/external/runtime/runtime.depproj : error NU1102:   - Found 1366 version(s) in dotnet-core [ Nearest version: 3.0.0-preview5.19222.4 ]
/home/tarek/oss/corefx/external/runtime/runtime.depproj : error NU1102:   - Found 35 version(s) in https://api.nuget.org/v3/index.json [ Nearest version: 3.0.0-preview4.19212.13 ]
/home/tarek/oss/corefx/external/runtime/runtime.depproj : error NU1102:   - Found 0 version(s) in https://dotnet.myget.org/F/roslyn/api/v3/index.json
/home/tarek/oss/corefx/external/runtime/runtime.depproj : error NU1102:   - Found 0 version(s) in https://dotnet.myget.org/F/sourcelink/api/v3/index.json
/home/tarek/oss/corefx/external/runtime/runtime.depproj : error NU1102:   - Found 0 version(s) in dotnet-coreclr
/home/tarek/oss/corefx/external/runtime/runtime.depproj : error NU1102:   - Found 0 version(s) in https://www.myget.org/F/xunit/api/v3/index.json
```

[msbuild.binlog.zip](https://github.com/dotnet/corefx/files/3208555/msbuild.binlog.zip)

**Comment by tarekgh** [comment]
@dsplaisted 

@joperezr briefly looked at this and he is not seeing anything wrong with the scripts in corefx. He think this could be SDK issue as get restore is not able to handle restoring the package on Ubuntu 18.04  while the package exist in the feed.

**Comment by dsplaisted** [comment]
Is this using the dotnet-core MyGet feed?  I think that's not being published to anymore, and the blob feed should be used instead.

**Comment by tarekgh** [comment]
Here is the feeds we use mentioned in the nuget.config file
```
    <add key="dotnet-core" value="https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json" />
    <add key="dotnet-coreclr" value="https://dotnetfeed.blob.core.windows.net/dotnet-coreclr/index.json" />

```

**Comment by joperezr** [comment]
> Is this using the dotnet-core MyGet feed? I think that's not being published to anymore, and the blob feed should be used instead.

It's not, it is going against the blob feed. If you check the binlog you'll see that the sources are right, in fact, looks like the restore task does get back all different versions from the index.json but for some reason can't find the version we are looking for, even though the version is clearly there.

**Comment by ericstj** [comment]
Still reproducing?  Could be an issue of a known bug with blob feeds.
https://github.com/dotnet/arcade/issues/2774

**Comment by wfurt** [comment]
I can build on 18.04. I've seen something similar while back on Ubuntu 16 and unsuccessfully try to debug it with @safern. I end up creating new VM image with same version and that fixed it.

**Comment by tarekgh** [comment]
Unfortunately, on my VM I am still hitting the exact same error. I pulled the latest sources and built clean.

**Comment by ericstj** [comment]
Do you have a recent binlog so that we can reconcile it with the data from the server?  One thing that I noticed is that it says 1366 versions in dotnet-core.  If I look at the json file from the blob feed I see that the claimed "nearest" version (3.0.0-preview5.19222.4) is actually almost the 1366th version in the file.  It's actually 1368 but we likely had a couple servicing versions that came in since then to bump it up.  This speaks to either a) nuget is truncating the json, or b) nuget is using a stale json.  One thing to try is to run `dotnet nuget locals http-cache --clear`  or `dotnet nuget locals all --clear` to see if that fixes a stale index that isn't being updated.  If that doesn't fix it share the log and I believe next steps would be to follow up with engineering team / nuget to find out where the issue likes.

**Comment by tarekgh** [comment]
Thanks @ericstj. clearing the cache the way you described made it work perfectly.

**Comment by ericstj** [comment]
Great!  Seems cache-age on those index files should make this impossible to happen persistently like this. /cc @emgarten @jcagme in case they feel this smells and want to follow up with an investigation to blob feed tooling.

**Comment by emgarten** [comment]
There shouldn't be any caching done by blob storage. NuGet client has a cache policy of 30 minutes for all json files and the server has no control over it.
