### ISSUE TITLE
build.cmd -test fails with missing 'testscope' argument

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/corefx#37865]
Whenever I try to run `build & build -buildtests -test` or pretty much anytime I try to run build script with `-test` option specified, the PS script fail saying that the argument 'testscope' is missing. Freshly forked/cloned from the latest corefx master branch. (at the moment the most recent commit is https://github.com/dotnet/corefx/commit/a0aac7aef0e9c6c1fd4bd5d51a4dff6e0e05f9d8.) I don't remember this happening when I tried this last time (which... I think is about two weeks ago?).

I'm guessing it won't be too helpful, but going to upload the original error message anyway (in Korean). Ran on `Developer Command Prompt for VS 2019 Preview` (v16.2.0-pre.1.0), Windows 10 Home/Pro, Build No. 18890/18898 (yes, I tried it on two separate PCs)
```
C:\Users\gotos\source\repos\corefx\eng\build.ps1 : 'testscope' 매개 변수에 대한 인수가 누락되었습니다. 유형이 'System.String'인 매개 변수를 지정하고 다시 시도하십시오.
    + CategoryInfo          : InvalidArgument: (:) [build.ps1], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingArgument,build.ps1
```

**Comment by ViktorHofer** [comment]
Sorry for the inconvenience, I forgot to test all scenarios here. I submitted a fix: https://github.com/dotnet/corefx/pull/37871

**Comment by Gnbrkm41** [comment]
@ViktorHofer Thanks for the quick fix!
