### ISSUE TITLE
Unsafe.AsRef<T>(in T) loses nullability of T

### ISSUE THREAD

**Issue by ektrah** [dotnet/corefx#37861]
It seems that passing a nullable-reference-type reference to System.Runtime.CompilerServices.Unsafe.AsRef<T>(in T) turns it into a non-nullable-reference-type reference:

![screenshot](https://user-images.githubusercontent.com/4752078/58172275-66053000-7c98-11e9-91a4-32682db50d26.png)

Curiously, this doesn't happen when assigning to the reference...

![screenshot2](https://user-images.githubusercontent.com/4752078/58172814-e6786080-7c99-11e9-9e57-f29963ecf12f.png)

...unless the previously referenced value isn't null:

![screenshot3](https://user-images.githubusercontent.com/4752078/58172829-f3954f80-7c99-11e9-863d-d5ce9c88c187.png)

Not sure if this is an issue with System.Runtime.CompilerServices.Unsafe (lack of nullability annotations?) or Roslyn or both...

I'm using Visual Studio 16.1.0 with .NET Core 3.0.100-preview5-011568.

<details>
<summary>Full code (click to expand)</summary>

```csharp
using System;
using System.Runtime.CompilerServices;

namespace ConsoleApp1
{
    class Program
    {
        static void Main()
        {
            string? s = "Hello World";

            ref string? r1 = ref s;

            ref string? r2 = ref Unsafe.AsRef(in s);

            DangerousUpdate(in s);

            DangerousUpdateIfNotNull(in s);
        }

        static void DangerousUpdate(in string? s)
        {
            Unsafe.AsRef(in s) = null;
        }

        static void DangerousUpdateIfNotNull(in string? s)
        {
            if (s == null)
                throw new InvalidOperationException();

            Unsafe.AsRef(in s) = null;
        }
    }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <NullableContextOptions>enable</NullableContextOptions>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.6.0-preview6.19259.10" />
  </ItemGroup>

</Project>
```

</details>

**Comment by stephentoub** [comment]
The System.Runtime.CompilerServices.Unsafe library has not been annotated for nullable reference types; the whole library will thus be "oblivious".  Whether these warnings are correct or not given the language rules would then be an issue for Roslyn; I suggest the issue be moved there. Thanks.

**Comment by ektrah** [comment]
Are there no plans to annotate System.Runtime.CompilerServices.Unsafe at all or has it just not been done yet? If no plans, does it mean that all methods will require non-nullable reference types even if they perfectly work with nullable ones (and thus require a *dammit* on every invocation) or will it default to nullable?

**Comment by stephentoub** [comment]
Anything unannotated defaults to "oblivious".

The majority of corefx will be unannotated for .NET Core 3.0.  We only plan to annotate a few of the core reference assemblies in that timeframe, e.g. System.Runtime.dll, System.Collections.dll, etc.

We do plan to annotate everything beyond that in the future.

**Comment by ektrah** [comment]
OK, thanks! I have opened https://github.com/dotnet/roslyn/issues/35910 for the Roslyn side of this issue.
