### ISSUE TITLE
Add unit test coverage for portable PDB

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#3787]
There is test coverage in Roslyn for portable PDBs, but before we ship a stable System.Reflection.Metadata, we need sufficient unit tests in corefx.

We'll merge #3560 with Roslyn's sign-off now so that we can get them a -rc build out of master in time.

**Comment by tmat** [comment]
We have some coverage now. We could probably have more, but it's a general problem tracked already by https://github.com/dotnet/corefx/issues/931, so I'm gonna close this issue.
