### ISSUE TITLE
Move JsonSerializer to the root namespace - System.Text.Json

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#37896]
**Motivation:**
Since `JsonSerializer` is the more commonly used API, move it to the root namespace. This means move `JsonSerializer` and `JsonSerializerOptions` into the root namespace, `System.Text.Json`:

**Proposed API surface:**
https://github.com/dotnet/corefx/blob/510ab9e6433ff0df29e0ae080140f4f2c1b69abd/src/System.Text.Json/ref/System.Text.Json.cs#L349

```diff
namespace System.Text.Json
JsonCommentHandling
JsonDocument
JsonElement
JsonEncodedText
JsonException
JsonProperty
JsonReaderOptions
JsonReaderState
JsonTokenType
JsonValueType
JsonWriterOptions
Utf8JsonReader
Utf8JsonWriter 
+ JsonNamingPolicy
+ JsonSerializer
+ JsonSerializerOptions

System.Text.Json.Serialization
JsonAttribute 
JsonExtensionDataAttribute 
JsonIgnoreAttribute 
- JsonNamingPolicy
JsonPropertyNameAttribute 
- JsonSerializer
- JsonSerializerOptions
```

**Questions:**
1) Rename `System.Text.Json.Serialization` to something to indicate "extensibility". Maybe `Converters` given we plan to add `JsonConverter` there? Custom?
2) Should we move reader/writer to a nested namespace?

cc @steveharter

**Comment by rynowak** [comment]
Keep the nested namespace as `root.Serialization`.

**Comment by steveharter** [comment]
For the three file moves let's be sure to coordinate with other active PRs and be sure to preserve git history.

**Comment by paulomorgado** [comment]
I can't help to think that this should me more in pair with XML.

For starters, it should be `System.Json` and `System.Json.Serialization` as it is `System.Xml` and `System.Xml.Serialization` and so on.

**Comment by Anipik** [comment]
@ahsonkhan should we move the internal types used by the JsonSerializer to System.Text.Json namespace ?

**Comment by ahsonkhan** [comment]
> should we move the internal types used by the JsonSerializer to System.Text.Json namespace ?

I would say yes, but just confirm with @steveharter.

**Comment by steveharter** [comment]
> Should we move the internal types used by the JsonSerializer to System.Text.Json namespace ?

Sure.

> For the three file moves let's be sure to coordinate with other active PRs and be sure to preserve git history.

Actually, I don't think we want to physically move any files in the repo. The reader\writer\document all have their own directories even though they are in the root `System.Text.Json` namespace.

**Comment by Anipik** [comment]
> The reader\writer\document all have their own directories even though they are in the root System.Text.Json namespace.

All the files in reader\writer\document are in the same namespace. If we dont move the files, some of the files\classes will be in System.Text.Json and some System.Text.Json.Serialization

**Comment by steveharter** [comment]
Per offline discussion, I agree with this concern. However since we already have a mix of physical folders and namespaces that don't align we should refactor all of this after the usability studies and when we know the namespaces are correct (if we agree it makes sense to do that at that time).

Otherwise it just adds short-team overhead and the possibility of additional file moves.
