### ISSUE TITLE
Is moving field to base type really binary compatible?

### ISSUE THREAD

**Issue by adrianoc-unity3d** [dotnet/corefx#37892]
In the [Breaking changes rules doc](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-rules.md#members)  the following paragraph looks incorrect:

> Moving a member onto a class higher in the hierarchy tree of the type from which it was removed

just to be clear,  the scenario described looks to be something like:

```CSharp
// A & B declared in SomeLib.dll
public class A
{
}

public class B : A
{
	public int field;
}

// C declared in SomeProgram.exe
public class C
{
    public static void Main()
    {
        B b = new B();
        System.Console.WriteLine(b.field);
    }
}
```
[The generated IL](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8D0OAEAgvgGT4BC+AJnAMYYQJxX5oB2+AygPZhwAyaYADoqGDAFgAUAAEAzPhkAmItIDe0gL7Tp8xSsohVUjVICQe9jHwAzNHAxUA3Fp1S8+AMLU6DJi3YuXhkARgB2YTgADzhdBWUvdWl8FMV4kIA2RQAWfABZCHYACgBKZNTTVKqKfGB8AF58NjgAdwpSlylq1NDhUIBOIpE7ByoSzqrtKU0gA===) has a reference to B.field. I don't see how moving *field* to *A* can be *binary compatible*

Also, *peverify* complains about that change and I get an exception  at runtime.

Am I missing something ?

**Comment by karelz** [comment]
If you reference it from another module and run against "moved" binaries, what does it do?

**Comment by adrianoc-unity3d** [comment]
@karelz following the steps:

1. Compile SomeLib.dll & SomeProgram.exe
2. In SomeLib.cs, move `public int field;` to class **A**
3. Recompile **only SomeLib.dll**
4. Run *S*omeProgram.exe**

Step **4** throws an exception:
> Unhandled Exception: System.MissingFieldException: Field not found: 'B.field'.
   at C.Main()

**Comment by ericstj** [comment]
I'm guessing that doc was not accounting for fields, since we don't typically expose public fields.  /cc @terrajobst 

APICompat does the right thing here: https://github.com/dotnet/arcade/blob/c9ab9c47d6c66fb9ad89e331900e06bed7463904/src/Microsoft.DotNet.ApiCompat/Rules/Compat/MembersMustExist.cs#L27
It only permits moving to base for methods.

We should probably update that doc.

**Comment by adrianoc-unity3d** [comment]
@ericstj why does this work for *non virtual methods* ? 

I've added a ```Foo()``` in class ```B``` (above) and recompiled both assemblies and verified that  
the call (in **C**) was emitted as: 

```IL_0008: callvirt instance int32 [SomeLib]B::Foo()```

Then I moved ```Foo()``` to ```A``` and recompiled only classes **A** & **B** and I expected it to fail but it works and peverify also does not complain. Initially I've though it was due to the use of ```callvirt``` but changing it to a simple ```call``` did not change anything.

Is that the jit will lookup the method in the base (**A**) even if the IL clearly specifies a derived (**B**) type?

**Comment by jkotas** [comment]
> Is that the jit will lookup the method in the base (A) even if the IL clearly specifies a derived (B) type?

Right. It is how it is speced in [ECMA-335](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-334.pdf). Look for: This implements “call base class” behavior.

**Comment by ericstj** [comment]
I believe so.  @carolEidt or @bruceforstall might be able to elaborate on JIT behavior.  Here’s what the spec says:

>The CLI resolves the method to be called according to the rules specified in §I.12.4.1.3 (Computed destinations), except that the destination is computed with respect to the class specified by the metadata token.
[Rationale: This implements “call base class” behavior. end rationale]

**Comment by CarolEidt** [comment]
> Is that the jit will lookup the method in the base (A) even if the IL clearly specifies a derived (B) type?

The JIT isn't really involved in looking up the methods. It always asks the VM to provide it with the call info, given the metadata for the call. The behavior described by @jkotas and @ericst describe is correct. Note, though that this is the right link for the CLI spec: http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-335.pdf.
