### ISSUE TITLE
Get automated process to enforce coding rules

### ISSUE THREAD

**Issue by sokket** [dotnet/corefx#3789]
Currently, we have code styling and formatting rules for both native and managed code but there is no process to enforce these rules. We should enforce these rules in an automated, easy way to ensure code cleanliness and styling

**Comment by mellinoe** [comment]
@sokket How much of this do we have right now? I know we have the native code formatter, but it is a manual process (i.e. just a script you can optionally run). Do we have plans to automate that stuff and/or add something for managed code?

**Comment by sokket** [comment]
There currently isn't a plan in place for how to do this; we have manual formatting rules that can be applied for C# and C++ but no process and no plan for a way forward

**Comment by karelz** [comment]
Next steps:
1. Create analyzer that checks the rules
2. Enable it for selected projects (we might need to disable it for some legacy tests, etc.)

**Comment by mellinoe** [comment]
We talked a bit more about this today. The general consensus was that we should add this, but have it "disabled" by default. By that, I mean the option is available, but it is not build-blocking or automatic.

**Comment by weshaggard** [comment]
I'm a firm believe that if we are going to do anything here it should be to add an auto-formatter instead of having a style-cop type of tool. I'm going to close this as I don't expect we will have a tool to verify this at build time.
