### ISSUE TITLE
System.Runtime.Caching - Object Keys

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/corefx#37893]
Hi All,
I am looking for a GC-friendly caching solution that allows me to cache items using objects as keys instead of strings.  I'd ideally like an API that I can use similar to this:
````c#
var CachedValue1 = cache.GetOrSet(
  value: ()=>...,
  key: CacheKey,
  expiresIn: TimeSpan.FromMinutes(30)
);
...

var CachedValueN = cache.GetOrAdd(
  value: ()=>...,
  key: CacheKeyN,
  expiresIn: TimeSpan.FromMinutes(30),
  dependsOn: new[]{ CachedValue1, CachedValue2, CachedValue3, CachedValue12 }
);
````

I've taken a look at System.Runtime.Caching but appears to do all its caching using string-based cache keys and I am working with complex objects that aren't easily boiled down to a simple string.  Any thoughts?

**Comment by KKhurin** [comment]
@TonyValenti have you taken look at [ASPNET core memory cache](https://github.com/aspnet/caching/tree/master/src/Microsoft.Extensions.Caching.Memory)? 

What exactly do you mean by "GC-friendly"? An item with 30 minutes expiration is almost guaranteed to be promoted to Gen2 and if there are many items like this they will collectively churn gen2 quite a bit.

**Comment by StephenBonikowsky** [comment]
Closing since there was no response back.
