### ISSUE TITLE
Consider documenting the official stance on whether `Dispose` method should dispose of the passed in `IDisposable`s

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/corefx#37908]
Related: https://github.com/dotnet/iot/issues/419, https://github.com/dotnet/corefx/issues/37873, https://github.com/dotnet/corefx/issues/37701

I have been noticing a few issues that discuss about whether to dispose `IDisposable` types that are passed in to the types through constructor (e.g. various `Stream` types that accept another `Stream`) when `Dispose()` method is called. Looking up on `Framework Design Guidelines` and MS Docs article on Dispose method, it mentions that all the unmanaged resources that are allocated & held within the instance should be disposed of when `Dispose` is called, however it does not mention the ones that are passed in from outside. (Or maybe I can't just find it... definitely possible.)

I think it would be great if it could be unified (at least for new types that are introduced into CoreFX / other repositories). What would be the recommendation on this? Should such types
* Dispose of the passed in `IDisposable`s when `Dispose` is called by default?
* Provide a boolean parameter upon construction that determines whether to dispose of the parameters on disposal?
   * Should it be `true` for dispose? (e.g. `bool shouldDispose`) or `true` for leave open? (e.g. `bool leaveOpen`)

**Comment by Gnbrkm41** [comment]
#37701 doesn't mention about `Dispose` methods but I guess it's close enough.

**Comment by ahsonkhan** [comment]
cc @bartonjs, @KrzysztofCwalina
