### ISSUE TITLE
Add .NET 4.6.1 target to AsyncInterfaces

### ISSUE THREAD

**Issue by onovotny** [dotnet/corefx#37929]
The AsyncInterfaces package currently targets .NET Standard 2.0 and .NET Standard 2.1. This means that a .NET Framework 4.6.1 project may pull in a lot of other packages by referencing this one.

Please add a .NET 4.6.1 target (with the same items as in the .NET Standard 2.0 one) to minimize package dependency issues.

**Comment by karelz** [comment]
@joperezr @stephentoub any thoughts?

**Comment by stephentoub** [comment]
> any thoughts?

What's the downside of adding a 4.6.1 target?  "Just" increased size of the NuGet package?

@terrajobst, any strong reason not to do this?

**Comment by joperezr** [comment]
AFAIK there are no other concerns apart from nuget package size and to actually make the source compile against netfx.

**Comment by joperezr** [comment]
I'll take care of this.

**Comment by tarekgh** [comment]
@joperezr would you do that for all recently added packages?

**Comment by joperezr** [comment]
> would you do that for all recently added packages?

Nope, the plan is to do it for the 3 bridge packages, which are all includded in my PR #38104. Is there a specific package you want to have a net461 target?
