### ISSUE TITLE
Single line comments ended with single \r return \r when calling GetComment

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#37931]
Repro:

```csharp
        [Fact]
        public static void Test()
        {
            string jsonString = "//asd\r";
            string expectedComment = "asd";
            byte[] dataUtf8 = Encoding.UTF8.GetBytes(jsonString);
            var state = new JsonReaderState(options: new JsonReaderOptions { CommentHandling = JsonCommentHandling.Allow });
            var json = new Utf8JsonReader(dataUtf8, isFinalBlock: true, state);

            Assert.True(json.Read());
            Assert.Equal(expectedComment, json.GetComment());
            Assert.False(json.Read());
        }
```

```
        Expected: asd
        Actual:   asd\r
```

cc: @ahsonkhan

**Comment by ahsonkhan** [comment]
Given the json payload is effectively empty, I would consider this a low priority issue, but it is a bug nonetheless.

For example, if the JSON actually contained some content, the test passes:
```C#
[Fact]
public static void CommentThenData()
{
    string jsonString = "//asd\r1";
    string expectedComment = "asd";
    byte[] dataUtf8 = Encoding.UTF8.GetBytes(jsonString);
    var state = new JsonReaderState(options: new JsonReaderOptions { CommentHandling = JsonCommentHandling.Allow });
    var json = new Utf8JsonReader(dataUtf8, isFinalBlock: true, state);

    Assert.True(json.Read());
    Assert.Equal(expectedComment, json.GetComment());
    Assert.True(json.Read());
    Assert.Equal(1, json.GetInt32());
    Assert.False(json.Read());
}
```
cc @WinCPP

**Comment by WinCPP** [comment]
@ahsonkhan, @krwq May I pick this up for fix?

**Comment by ahsonkhan** [comment]
I am not sure how far @krwq has gotten with this but certainly he wouldn't mind if you worked on it. Please cc him on your PR (and me) and we can collaborate that way. Note that a similar issue exists in the multi-segment case and should be fixed:
`ConsumeSingleLineCommentMultiSegment`
https://github.com/dotnet/corefx/blob/e58b35cd0f8fe6caa194ca7e48388d8d59854fe0/src/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.MultiSegment.cs#L2416

**Comment by krwq** [comment]
@WinCPP I have initial fix for the single segment with test cases (there is one test case failing but I think this is a test issue but haven't started looking at it yet) - I haven't started on the multi-segment yet at all.

If you want to pick this up you can go ahead and pick it up from my WIP changes which I just checked in:
https://github.com/krwq/corefx/tree/fix-33321

I currently have some side issue which I urgently need to take a look before I come back to this.

**Comment by krwq** [comment]
ahh I confused this with https://github.com/dotnet/corefx/issues/33321 - I included the fix in there as well so you can isolate it and send a patch (and do similar for multi-segment)

**Comment by krwq** [comment]
I have time to pick it up again so will finish working on the other issue which will include a fix for this

**Comment by WinCPP** [comment]
> I have time to pick it up again ...

@krwq sorry, suddenly got occupied with lot of new tasks at work and didn't get time to look into this whole day today. Thanks for looking into the same. Will back off for now...
