### ISSUE TITLE
JsonSerializer does not serialize fields

### ISSUE THREAD

**Issue by Alois-xx** [dotnet/corefx#37936]
So far JsonSerializer only supports serialization of properties. Practically every other serializer can also serialize fields. Is this feature on the roadmap?

**Comment by Anipik** [comment]
cc @steveharter @ahsonkhan

**Comment by ahsonkhan** [comment]
Duplicate of https://github.com/dotnet/corefx/issues/36505

>  Is this feature on the roadmap?

Yes it is, but for vNext.
