### ISSUE TITLE
EventListener.DisposeOnShutdown crashing xunit processes

### ISSUE THREAD

**Issue by jaredpar** [dotnet/corefx#3793]
Recently we've seen xunit failing due to a bug in EventListener.DisposeOnShutdown.  Here is the stack of the failure:

``` 
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
    at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
    at System.Diagnostics.Tracing.EventListener.DisposeOnShutdown(Object sender, 
```

Here is the relevant code:

``` csharp
private static void DisposeOnShutdown(object sender, EventArgs e)
{
    foreach (var esRef in s_EventSources)
    {
        EventSource es = esRef.Target as EventSource;
        if (es != null)
            es.Dispose();
    }
}
```

It appears this code is not accounting for the case that `s_EventSources` could be modified either by the `Dispose` call directly or indirectly via other methods in `EventListener`.  All of the other methods which modify / enumerate `s_EventSources` take care to lock the appropriate guard.  This method is the sole exception.  

Jenkins Job Link showing the failure in action: http://dotnet-ci.cloudapp.net/job/roslyn_master_win_rel_unit64/112/

**Comment by weshaggard** [comment]
cc @vancem

**Comment by vancem** [comment]
cc @davmason

David, I have not looked at this carefully, but it looks like we just need to wrap DisposeOnShutdown in the EventListener lock (like everything else).

**Comment by davkean** [comment]
We're running into this bug pretty consistently ([another log](http://dotnet-ci.cloudapp.net/view/roslyn/job/roslyn_stabil_win_dbg_unit32/33/consoleFull#9576954053666a956-fc27-4f51-b90e-c3e0fbfe1603)), given this is on desktop, we're not going to get a fix soon - but please make sure this gets included as part of the next .NET update.

**Comment by vancem** [comment]
cc @davmason 

I have asked David to insure that this gets into the set of bugs we are fixing for V4.6.2

**Comment by davkean** [comment]
Just a 3 monthly reminder that we're hitting this every day in xunit.

**Comment by davmason** [comment]
@davkean I fixed this a while ago (>1 month) in the coreclr repo, I would have expected it to be part of the most recent coreclr builds. Are you stuck on a version without the fix?

**Comment by jaredpar** [comment]
@davmason our tests have to run on both desktop and CoreCLR.

**Comment by davmason** [comment]
@jaredpar @davkean  It's already included for 4.6.2 but there's no way to deliver it to desktop sooner. Targeting the nuget package instead would resolve it, it's already fixed in there, but I'm not sure how easy that is to do since it's xunit that has the dependency.

**Comment by davkean** [comment]
Targeting the nuget package is not a fix, it's xunit that has the dependency not us.

**Comment by davmason** [comment]
We need to clean up the open bugs that are not for .Net Core. This was fixed in .Net Core in coreclr PR [#2111](https://github.com/dotnet/coreclr/pull/2111) and the fix is coming for desktop with 4.6.2.

**Comment by davkean** [comment]
k, just a reminder we're still hitting this daily - just in case this isn't in 4.6.2 yet: https://github.com/dotnet/roslyn/issues?utf8=%E2%9C%93&q=is%3Aissue+eventlistener+

**Comment by vancem** [comment]
It is in 4.6.2.   It really a question of your deployment.   There are builds of 4.6.2 available 

\\vsufile\patches\sign\NETFX\4.6.2\S98.3\01539.00\ISV_Offline

Is an installer.

**Comment by mmitche** [comment]
@vancem Have these been released yet?

**Comment by danmosemsft** [comment]
@mmitche 4.6.2 was released a year ago

**Comment by vancem** [comment]
Download URL if you care. 

https://www.microsoft.com/en-us/download/details.aspx?id=53344
