### ISSUE TITLE
Hardware Intrinsics Feedback

### ISSUE THREAD

**Issue by dasMulli** [dotnet/corefx#37935]
So I just spent some time experimenting with Hardware Intrinsics and wanted to share my experience.
I have no previous experience with using hardware intrinsics except vor a very basic understanding of what it is about nor any pre-existing asm/c* optimised avx/sse code that I could copy from, but I set out to improve on a routine that showed up as by far the most expensive loop for implementing the [Hungarian algorithm](https://en.wikipedia.org/wiki/Hungarian_algorithm) in C#. (I do know how pointers and operations work due to experience with C and a little x86 assembler)

Fast forward a few hours:
* Code runs faster by around 35% (using BenchmarkDotNet) without significant logic changes, just using `Vector256<float>` comparisons and some bitmasking.
* I've recognised more opportunities for improvements in the surrounding code.

What I really liked about the experience using .NET Core Hardware Intrinsics:
* The API is easy and intuitive to understand once you see an example of how to load and use vectors.
* The methods on the Avx and See* classes are easy to understand and I don't need to look up the horrible instruction names from Intel documentation.
* Also the `FloatComparison` enum is super helpful with its naming. I compared it to some C++ code I found and recognised how much value the long and expressive names provide - although I had to google the exact behaviour of Ordered/Unorderd and Signaling/NonSignaling (nothing 2 existing SO answers didn't explain).

Things that I have questions about:
* Any chance to provide easier creation of vecotors like using `ref` arguments? (e.g. `Avx.LoadVectror256(ref myarr[0])`, `Avx.CreateVector128Int(1,1,1,1,1,1,1,1)`)
* Is there a plan to introduce `Vector512<T>`? I've found mentions in GH issues here but nothing more specific.

Summary: Great work, thanks for that!

**Comment by Gnbrkm41** [comment]
I remember seeing that AVX-512 isn't widely available in common consumer CPUs.
![image](https://user-images.githubusercontent.com/42944058/58350371-a6cf9580-7ea0-11e9-9822-041c828e276c.png) (From wikipedia `AVX-512` document)
In addition, I remember hearing that at the moment AVX-512 instructions involves downclocking of the CPU which actually can be worse compared to alternatives; but I might be wrong.

cc @tannergooding

**Comment by tannergooding** [comment]
CC. @danmosemsft, @CarolEidt, @RussKeldorph who may enjoy reading some positive Hardware Intrinsics feedback.

**Comment by Gnbrkm41** [comment]
Regarding `Avx.CreateVector128Int(1,1,1,1,1,1,1,1)` (I think you meant 256): `Vector256.Create(1)`?

**Comment by tannergooding** [comment]
> Is there a plan to introduce Vector512<T>? I've found mentions in GH issues here but nothing more specific.

AVX-512 is not currently very common in consumer grade CPUs. It also nearly triples the currently exposed surface area (taking us from ~1500 APIs to ~4500 APIs). It *may* be on the plate in the future, but that will likely be dependent on availability, need/desire, and perf numbers.

> Any chance to provide easier creation of vecotors like using ref arguments? (e.g. Avx.LoadVectror256(ref myarr[0]), Avx.CreateVector128Int(1,1,1,1,1,1,1,1))

This has come up a few times before as well and likely won't happen for 3.0, but may happen in the future based on demand...

A summation of past things noted for this is:
* Hardware Intrinsics are expected to be used on decently large chunks of memory and pinning is generally the optimal thing to do for performance (exceptions to this may be things like `Bmi2.MultiplyNoFlags` which have what are effectively `out` parameters)
* It isn't immediately obvious that a `ref T` could actually read between 2 and 32 T, depending on the size
* You generally have to use the `System.Runtime.CompilerServices.Unsafe` class to work with `ref` beyond tracking a singular object, which is very easy to get wrong
* You can use `Unsafe.ReadUnaligned` to work with `ref T` today, the downside is that you don't necessarily get to choose some behaviors like `NonTemporaral` or `Aligned` load checks, but you can't safely guarantee some of those semantics for non-pinned data anyways.
* We don't currently have a proper `native int` type and waiting to expose such APIs until after the C# compiler supports one (with operators) may be more desirable.

**Comment by CarolEidt** [comment]
@dasMulli - Thanks for this! Just to follow up on a couple of things mentioned by @tannergooding above:

> You can use Unsafe.ReadUnaligned to work with ref T today, the downside is that you don't necessarily get to choose some behaviors like NonTemporaral or Aligned load checks

Would the `Unsafe.ReadUnaligned` address what you want to do?

Also, with regard to `Avx.CreateVector128Int(1,1,1,1,1,1,1,1)`, it is indeed true that `Vector128.Create(1)` or `Vector256.Create(1)` will give you a vector with all the same values, though there are currently some inefficiences there (https://github.com/dotnet/coreclr/issues/22388), but I wonder if you were interested in an API that allowed you to specify different constants. This has come up before, but I don't think an issue currently exists.

**Comment by dasMulli** [comment]
Reg `Vector256.Create()`: seems that I completely missed that, I only searched on `Vector256<T>` for creation methods.

`Unsafe.ReadUnaligned`: I'll just stick with pointers before making things too complicated. I was simply thinking of ways to not necessarily use pointers (and pointer arithmetic) everywhere.

@tannergooding Thanks for the explanations.

**Comment by dasMulli** [comment]
Closing since my outstanding questions have been answered.

**Comment by dasMulli** [comment]
If anyone is interested, I've been poking at this algorithm for another day, changing data structures (most importantly double to float), removing a dependency on MathNet.Numerics except for the entry point API and changed every loop that seemed worth it to use hardware intrinsics. The results are great. Without the hardware intrinsics but with the other changes I'd still be well over a second for the 500x500 benchmark so I'm looking at 8-10x speedup due to hardware intrinsics.

The only thing blocking me from trying this out in a production use case is the fix for https://github.com/dotnet/corefx/issues/37738 not yet being in a public build but I guess the fix is going to be available soon.

``` ini

BenchmarkDotNet=v0.11.5, OS=Windows 10.0.18362
Intel Core i9-8950HK CPU 2.90GHz (Coffee Lake), 1 CPU, 6 logical and 6 physical cores
.NET Core SDK=3.0.100-preview5-011568
  [Host]     : .NET Core 3.0.0-preview5-27626-15 (CoreCLR 4.6.27622.75, CoreFX 4.700.19.22408), 64bit RyuJIT
  DefaultJob : .NET Core 3.0.0-preview5-27626-15 (CoreCLR 4.6.27622.75, CoreFX 4.700.19.22408), 64bit RyuJIT


```
|                        Method |         Mean |      Error |     StdDev |
|------------------------------ |-------------:|-----------:|-----------:|
| BaseHungarianAlgorithm100x100 |    15.857 ms |  0.1289 ms |  0.1206 ms |
|     HungarianAlgorithm100x100 |     1.513 ms |  0.0291 ms |  0.0286 ms |
| BaseHungarianAlgorithm250x250 |   272.480 ms |  3.1205 ms |  2.7663 ms |
|     HungarianAlgorithm250x250 |    17.416 ms |  0.2384 ms |  0.1861 ms |
| BaseHungarianAlgorithm500x500 | 2,723.436 ms | 49.7220 ms | 46.5100 ms |
|     HungarianAlgorithm500x500 |   140.412 ms |  2.7456 ms |  3.0517 ms |

**Comment by danmosemsft** [comment]
Thanks for the update @dasmulli. If your project is open source, perhaps others would be interested if you pushed something the changes before and after.

**Comment by dasMulli** [comment]
Just got the go-ahead from our customer to release the code for this class, i'd like to re-do the different optimization steps to benchmark each change separately.

On a different note: How "bad" is casing a `bool*` to a `byte*`? Is the memory size and content (0 / 1) well-defined or considered an implementation detail of the CLR?
(Something i may change as well but currently there is a boolean matrix used as mask for some operations.. also something i'll likely change)

**Comment by dasMulli** [comment]
Thanks!

Yeah i have AVX code now that compares the bools to a Zero-Vector https://gist.github.com/dasMulli/e5b96d8a520a9c60764425e3378d0ddf#file-counttruesbenchmark-cs-L64-L68

**Comment by dasMulli** [comment]
I just put up the code at https://github.com/dasMulli/hungarian-algorithm with various stages of optimizations. And even though it is still not optimal, it is already a huge improvement and I'll likely be spending more time on other parts of the system, but the code dump is up now. Btw the system this is going to be run on will be a new Cascade Lake Xeon, so that's why i've been asking about the status / plan for AVX-512.

Some benchmark results: https://github.com/dasMulli/hungarian-algorithm/blob/master/benchmark-results/work-laptop/DasMulli.Benchmarks.HungarianAlgorithmImplementationsBenchmark-report-github.md
