### ISSUE TITLE
No way to turn off tty echo via corefx API (tcsetattr on Linux)

### ISSUE THREAD

**Issue by cspotcode** [dotnet/corefx#37948]
On Linux, TTY echo needs to be disabled to avoid keystrokes -- potentially ugly ansi escape sequences -- from rendering on the console.  dotnet's API does not expose this functionality except within `Console.ReadKey`, which is inadequate.

PSReadLine reads input keystrokes by repeatedly calling `Console.ReadKey` in a loop.  Dotnet's `ReadKey` implementation turns off TTY echo while it's waiting for a keypress, but it re-enables echo as soon as a key is pressed.  Despite PSReadLine's best efforts to immediately call `ReadKey` again, there is a brief window where keystrokes will be echoed to the console.  When holding down a key or typing rapidly, there's a chance these ansi escape sequences will appear and garble the display.

The proper solution is for libraries such as PSReadLine to disable tty echo *once* before reading input, *not* off and back on with every keypress.  dotnet's API needs to expose this functionality somewhere.

**Comment by cspotcode** [comment]
Related: PowerShell/PSReadLine#753

**Comment by stephentoub** [comment]
Have you tried .NET Core 3.0?

**Comment by wtgodbe** [comment]
@cspotcode did you get a chance to try this with the latest 3.0 SDK? You can download the installer from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe

**Comment by cspotcode** [comment]
I tested, and it's fixed in 3.0.

The relevant commit: https://github.com/dotnet/corefx/commit/007571b90c3cc555cd30f3b467b87c22f9f665e0

echo is turned off here:
https://github.com/dotnet/corefx/blob/master/src/Native/Unix/System.Native/pal_console.c#L180-L184

Sorry for the issue spam.
