### ISSUE TITLE
Incorrect StackChange value for OpCodes.Stelem

### ISSUE THREAD

**Issue by toptensoftware** [dotnet/corefx#37955]
Shouldn't the stack change value for `OpCodes.Stelem` be `-3` instead of `0`?

https://github.com/dotnet/corefx/blob/b86783ef9525f22b0576278939264897464f9bbd/src/Common/src/CoreLib/System/Reflection/Emit/OpCodes.cs#L1878

**Comment by steveharter** [comment]
cc @GrabYourPitchforks @jkotas @MichalStrehovsky

**Comment by jkotas** [comment]
https://github.com/dotnet/coreclr/pull/25382/
