### ISSUE TITLE
BoundedChannel ChannelWriter .WriteAsync() never completes.

### ISSUE THREAD

**Issue by electricessence** [dotnet/corefx#37958]
.NET Standard 2.0 inside a .NET Core 2.2 console application.

I've run into a very strange issue with `.WriteAsync(`) that after hours of debugging I can't really say why it's happening, but I have found a work-around that is satisfactory.

For some reason I was able to replicate over and over a situation where writing to a bounded channel would eventually stop even though the channel had been drained.
I tracked the number of entries being written and the number being read and eventually the application would 'freeze' while waiting for the `.WriteAsync`.
Now I know this sounds suspiciously like I screwed something up and wasn't draining the channel properly or something, but I definitely exhausted every possible situation where I thought it was my code causing the problem.

I eventually switched away from `.WriteAsync` in favor of the following extension:
https://github.com/electricessence/Open.ChannelExtensions/blob/master/Open.ChannelExtensions/Extensions.cs#L22-L49
```cs
        public static ValueTask<bool> TryWriteAsync<T>(this ChannelWriter<T> writer,
            T value, CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();

            if (writer.TryWrite(value))
                return new ValueTask<bool>(true);

            return TryWriteAsyncCore(writer, value, cancellationToken);
        }

        static async ValueTask<bool> TryWriteAsyncCore<T>(ChannelWriter<T> writer,
            T value, CancellationToken cancellationToken = default)
        {
            ValueTask<bool> tryAgain;
            do
            {
                cancellationToken.ThrowIfCancellationRequested();

                if (writer.TryWrite(value))
                    return true;

                tryAgain = writer.WaitToWriteAsync(cancellationToken);
            }
            while (tryAgain.IsCompletedSuccessfully ? tryAgain.Result : await tryAgain.ConfigureAwait(false));

            return false;
        }
```

Now I may simply be misinterpreting the expected behavior of `.WriteAsync` but after switching completely away from using it in favor of "trying" and then throwing if the above extension returns false, the problem simply went away and I could no longer reproduce.  Keeping in mind that the channel never closed prematurely and this method never returned false.

Please close if this is a known issue.  If you'd like to pursue this further, it will take some setup to restore the various change-lists to where the issue is reproducible.

What I can tell you certainly is that the point of forever waiting was here:
https://github.com/electricessence/Open.ChannelExtensions/blob/746b3a107ed75355ab4071f329cf7754b82e15fc/Open.ChannelExtensions/Extensions.Write.cs#L35-L36

And once this was changed to the latest:
https://github.com/electricessence/Open.ChannelExtensions/blob/master/Open.ChannelExtensions/Extensions.Write.cs#L35-L37
The problem went away.

**Comment by stephentoub** [comment]
Can you share an isolated repro? From a super quick glance at your code, I'd guess you're ending up awaiting the same ValueTask twice, which is not supported.

**Comment by electricessence** [comment]
Oh really!?  You can only await a ValueTask once?  So a single ValueTask can't have multiple awaiters?

**Comment by electricessence** [comment]
Might not be right away but I'll look deeper into getting an isolated repro.
I'll close for now and re-open when I do.

**Comment by electricessence** [comment]
@stephentoub ... isn't DisposeAsync() a ValueTask?  Does that mean you have to emit a unique ValueTask when it's called?  Or is it gonig to be assumed that DisposeAsync only get's called once by it's owner?

**Comment by stephentoub** [comment]
> You can only await a ValueTask once? So a single ValueTask can't have multiple awaiters?

Correct.  See https://devblogs.microsoft.com/dotnet/understanding-the-whys-whats-and-whens-of-valuetask/ for more details.

> isn't DisposeAsync() a ValueTask?

Yes, it returns a ValueTask.

> Does that mean you have to emit a unique ValueTask when it's called?

A method that returns a ValueTask needs to ensure that its caller is able to consume it.

> Or is it gonig to be assumed that DisposeAsync only get's called once by it's owner?

As with Dispose, DisposeAsync is supposed to be callable any number of times (serially), with subsequent calls effectively being nops.

**Comment by electricessence** [comment]
@stephentoub Thanks for the clarification.  I'll pass this info along.

**Comment by electricessence** [comment]
@stephentoub if I might slip one very important question in about `await` in here:
Will `await` ever have a way (maybe in c#8) that will make:
```cs
// now
var x = myValueTask.IsCompletedSuccessfully ? myValueTask.Result : await myValueTask;
```
```cs
// future?
var x = await myValueTask;
```
I totally understand this might break certain desired behavior for true 'deferring' of awaitables, but is there or can't there simply be:
```cs
var x = await now myValueTask; 
```
Maybe some keyword that checks any awaitable for completion and synchronously continuing?

**Comment by svick** [comment]
@electricessence That's how `await` already works: if `myValueTask.GetAwaiter().IsCompleted` returns `true`, the method continues synchronously.

**Comment by electricessence** [comment]
@svick are you suggesting that there's no benefit (compilation or run-time) checking for `myValueTask.IsCompletedSuccessfully ` like in the first example?  If so I'm so relieved. :|
I always thought placing await anywhere automatically incurred scheduling.

**Comment by svick** [comment]
@electricessence There are some cases where checking `IsCompletedSuccessfully` can be useful (see e.g. [how it's used in corefx](https://github.com/dotnet/corefx/search?q=IsCompletedSuccessfully)), but those should be really rare and they're not about scheduling.

**Comment by electricessence** [comment]
Right, I think my misconception has been dismissed.  I definitely see when it's useful and when it's not.
Thank you everyone.
