### ISSUE TITLE
Is .NET Standard being retired with .NET Core 3.0?

### ISSUE THREAD

**Issue by shaulbehr** [dotnet/corefx#37965]
I'm attempting to upgrade my project to .NET Core 3.0 preview. I've installed the SDK, and updated all my .NET Core projects to `netcoreapp3.0`. 
I figured that I should do the same for my .NET Standard projects, and update those to the latest version, i.e. `netstandard2.1`. But now when I try to compile my .NET Core projects, I get a compiler error:

>   MyNetCoreApp.csproj: [NU1201] Project MyNetStandardLib is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Project MyNetStandardLib supports: netstandard2.1 (.NETStandard,Version=v2.1)

I searched for this issue and couldn't find anyone else reporting it, but I did find some other projects on GitHub where for .NET Core 3.0 they're moving their .NET Standard projects to .NET Core 3.0, e.g. [here](https://github.com/aspnet/AspNetCore/issues/3754#issuecomment-434341032) and the pull request referenced [here](https://github.com/aspnet/Mvc/pull/8734#pullrequestreview-176018687).

Does this mean that .NET Standard is being deprecated, and all projects in future will be .NET Core?

**Comment by JarnoNijboer** [comment]
.NET Standard is not deprecated and as long as you don't need API's from .netcore3.0 or .netstandard2.1, you should target .netstandar2.0. The projects you are referencing are ASP.Net projects and ASP.Net 3.0 only works on .net core 3.0. Asp.net 2.x was targetting .netstandard 2.0 because is supported .net core and .net full framework.

**Comment by Wraith2** [comment]
> Does this mean that .NET Standard is being deprecated, and all projects in future will be .NET Core?

No. At least that isn't the plan currently. Corefx in 3.0 will support netstandard 2.1. Desktop framework (netfx) will only support netstandard 2.0 and the plan is to not implement ay later netstandard versions on desktop. After core 3.0 it will be [rebranded as 5.0](https://devblogs.microsoft.com/dotnet/introducing-net-5/) and a lot of work will be done to integrate multiple framework and runtime implementations into a more coherent ecosystem.

for the 3.0 release timeframe you will still end up with mono and corefx separately supporting netstandard 2.1 as far as I know.

**Comment by davidfowl** [comment]
@shaulbehr What version of visual studio are you using?

**Comment by karelz** [comment]
The error above should not happen netcoreapp3.0 does support netstandard2.1. Please use latest preview and latest Visual Studio.
cc @wtgodbe @ericstj

**Comment by ericstj** [comment]
Correct, this should work when using VS 2019 with a recent .NET SDK.  If you're still seeing issues, please reactivate this and share your `dotnet --info` output.

**Comment by MalinAan** [comment]
I'm having the same issue after installing .net core SDK version 3. I'm running on macOS. I get the following error several places:

`MyDotNetProject.fsproj: [NU1201] Project OtherDotNetProject is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Project OtherDotNetProject supports: netstandard2.1 (.NETStandard,Version=v2.1)`

I tried to delete the .bin folders to my project, rebuild and clean and rebuild.

```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.2.300 [/usr/local/share/dotnet/sdk]
  2.2.401 [/usr/local/share/dotnet/sdk]
  2.2.402 [/usr/local/share/dotnet/sdk]
  3.0.100 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Gladskih** [comment]
Error in private Asure Build:
> Project MyClient is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Project MyClient supports: netstandard2.0 (.NETStandard,Version=v2.0)
>     One or more projects are incompatible with .NETCoreApp,Version=v3.1.)

`dotnet --info` report:

> .NET Core SDK (reflecting any global.json):
>  Version:   3.1.101
>  Commit:    b377529961
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  6.3.9600
>  OS Platform: Windows
>  RID:         win81-x64
>  Base Path:   C:\Program Files\dotnet\sdk\3.1.101\
> 
> Host (useful for support):
>   Version: 3.1.1
>   Commit:  a1388f194c
> 
> .NET Core SDKs installed:
>   2.0.0 [C:\Program Files\dotnet\sdk]
>   2.0.3 [C:\Program Files\dotnet\sdk]
>   2.1.4 [C:\Program Files\dotnet\sdk]
>   2.1.300 [C:\Program Files\dotnet\sdk]
>   2.2.103 [C:\Program Files\dotnet\sdk]
>   2.2.104 [C:\Program Files\dotnet\sdk]
>   3.0.100 [C:\Program Files\dotnet\sdk]
>   3.1.101 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> 
> To install additional .NET Core runtimes or SDKs:
>   https://aka.ms/dotnet-download

**Comment by ericstj** [comment]
@Gladskih you should open a new issue.  If you're having an issue during restore, the correct location for the issue is https://github.com/nuget/home.  My best guess is that your corporate build infrastructure is using a very old nuget.exe to restore the project.  Make sure you're using dotnet.exe to restore the project.  If that doesn't help, open the new issue in nuget repo and attach the msbuild.binlog you get when running `dotnet restore /bl` on the project.
