### ISSUE TITLE
System.Printing Support

### ISSUE THREAD

**Issue by shaggygi** [dotnet/corefx#37978]
I was trying to port an API to .NET Core that uses System.Printing PrintServer.  I came across this [doc](https://docs.microsoft.com/en-us/dotnet/api/system.printing.printserver?view=netcore-3.0) and have the impression System.Printing is supported.  Am I missing something?

I currently have the following installed: 3.0.100-preview5-011568

**Comment by danmosemsft** [comment]
@shaggygi do you have https://www.nuget.org/packages/Microsoft.Windows.Compatibility installed?

Assuming so - check the API's you need are available: https://apisof.net/catalog/System.Printing

**Comment by shaggygi** [comment]
@danmosemsft Thanks for reply.  Yes, I have Win Compat installed.  Just don't see the related System.Printing IntelliSense show up.  Trying to use PrintServer, LocalPrintServer and PrintQueueCollection which appear in the provided link.  Any other packages need to be installed?

**Comment by danmosemsft** [comment]
Ah, System.Printing not System.Drawing.Printing. I think that's WPF. @ericstj is it available in Core? I see only a ref in https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/System.Printing/ref/System.Printing.cs

**Comment by danmosemsft** [comment]
Ping @ericstj

**Comment by ericstj** [comment]
It’s part of WPF and available building a WPF .NETCore 3.0 app.
