### ISSUE TITLE
PipeOptions, StreamPipeReaderOptions, and StreamPipeWriterOptions should not hardcode default sizes.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#37984]
As per the title, `PipeOptions`, `StreamPipeReaderOptions`, and `StreamPipeWriterOptions` should be updated so that the default sizes (such as the buffer size) are not hardcoded. The current values are based on profiling data and that may change in the future based on additional profiling data or customer feedback.

Changing it to not be hardcoded leaves the default buffer size an implementation detail that can be configured per runtime/os/etc and so that it can be freely changed under the covers if needed/desired.

There is prior art to using `-1` or `0` as the default. `-1` gives more flexibility since it is always an invalid size and `0` may be desirable for other scenarios (such as saying "don't do any buffering"). Another alternative is to use `Nullable<T>`.

This currently looks to apply to:
```cs
PipeOptions.PauseWriterThreshold
PipeOptions.ResumeWriterThreshold
PipeOptions.MinimumSegmentSize
StreamPipeReaderOptions.BufferSize
StreamPipeReaderOptions.MinimumReadSize
StreamPipeWriterOptions.MinimumBufferSize
```

After construction, the properties should reflect the actual default.

**Comment by tannergooding** [comment]
CC. @anurse, @stephentoub

**Comment by tannergooding** [comment]
I've marked this for 3.0 as we should change this before the API ships, if we are going to.

**Comment by jkotalik** [comment]
Yeah, definitely agree we should do this.

cc @davidfowl

**Comment by ahsonkhan** [comment]
> As per the title, `PipeReaderOptions` and `PipeWriterOptions` should be updated so that the default buffer size taken by the constructor is -1.

For clarity, this issue is talking about `StreamPipeReaderOptions`, `StreamPipeWriterOptions`. Please correct me if I am mistaken.
https://github.com/dotnet/corefx/blob/1064d0352c007fd2d8fb32d7f6e286fbb6d41264/src/System.IO.Pipelines/src/System/IO/Pipelines/StreamPipeWriterOptions.cs#L24

> Yeah, definitely agree we should do this.

As an aside, the `JsonSerializerOptions` doesn't have a non-parameterless ctor at all and exposes the `DefaultBufferSize` as a settable property. Do we have general guidelines around options like these ctor with getters versus settable properties) and if so, should we apply them consistently? I want to keep this issue focused on the new Pipelines related options, but just mentioning JSON so that we can adjust based on the decision here, if applicable.
https://github.com/dotnet/corefx/blob/1064d0352c007fd2d8fb32d7f6e286fbb6d41264/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs#L36

cc @steveharter

**Comment by anurse** [comment]
Should we use `int?` or is that overkill here?

**Comment by tannergooding** [comment]
Other APIs are and have been using -1 to represent this. We should likely do the same here for consistency

**Comment by anurse** [comment]
Fair point, I think consistency is important here. Just wanted to mention it :).

**Comment by terrajobst** [comment]
That makes sense. We should make the same change across

* `PipeOptions` constructor
* `StreamPipeReaderOptions` constructor
* `StreamPipeWriterOptions` constructor

After construction, the properties should reflect the actual default. In other words, we should only change the literal of the parameter itself to `-1`.

@bartonjs brought up the question if we should expose something like `Buffer.DefaultBufferSize` that is `-1`. We believe that's overkill. Also, many of the BCL construct that accept buffer sizes currently don't accept negative values. We could change that, but this would be a sizable work item and we're in the wrong part in the cycle to do that.

**Comment by stephentoub** [comment]
> PipeOptions constructor

@terrajobst, what option does this refer to?

**Comment by stephentoub** [comment]
Also from https://github.com/dotnet/corefx/pull/39286:
- Why is this just about bufferSize and not about other int options?
- Why use -1 rather than nullable?

**Comment by tannergooding** [comment]
> why then did it focus only on the buffer sizes

Because buffer sizes are something we already handle in other APIs as something we want to be able to freely change in the future.

Because `-1` is what we already use in other APIs to represent the same. It is also cheaper than nullable to use.

**Comment by tannergooding** [comment]
Anything else could be reviewed separately and independently and may not have pre-existing usages in other places in the framework.

**Comment by tannergooding** [comment]
Also, at the time I opened the issue, the API surface was fairly different. I don't believe several of the other options existed or were exposed in the same places yet.

I don't think we should be blocking this change (which also has prior art) on the other bits. Instead, we should be having separate API reviews to cover anything additional that had changed since this proposal went up that might also fall into a similar bucket.

**Comment by stephentoub** [comment]
> Because buffer sizes are something we already handle in other APIs as something we want to be able to freely change in the future.

There are other such APIs here, e.g. minimumSegmentSize, pauseWriterThreshold, etc. I don't see how something like minimumBufferSize is more relevant.

> Because -1 is what we already use in other APIs to represent the same.

To which are you referring?  Weren't most/all of them created before nullable existed?

> It is also cheaper than nullable to use.

There is no way additional overhead of using nullable here is going to be measurable/impactful in the overall context.

> I don't think we should be blocking this change (which also has prior art) on the other bits. Instead, we should be having separate API reviews to cover anything additional that had changed since this proposal went up that might also fall into a similar bucket.

Today the API is consistent: the parameters all have default values that represent the actual value.  This change makes it inconsistent, by changing some but not all to use -1 as a default instead.  We should not leave the API in a partial state.

**Comment by tannergooding** [comment]
> To which are you referring? Weren't most/all of them created before nullable existed?

I have no clue. Today, APIs use `-1` or `0` for the most part. `-1` generally makes more sense because it is invalid and can never be valid outside being some token for `default`. `0` could be valid for multiple contexts, including not wanting any buffering. Continuing to use `-1` is consistent with our existing patterns.

> This change makes it inconsistent, by changing some but not all to use -1 as a default instead

It looks like there is one parameter (`StreamPipeReaderOptions.MinimumReadSize`) which wouldn't be covered, is that the only thing you are referring to?

**Comment by stephentoub** [comment]
> Today, APIs use -1 or 0 for the most part.

Can you share some examples where -1 is used as the default value for an optional parameter buffer size?

> is that the only thing you are referring to?

No, also all the ones on PipeOptions (which is explicitly called out as part of the approval): minimumSegmentSize, pauseWriterThreshold, resumeWriterThreshold.

**Comment by tannergooding** [comment]
`StreamReader` and `StreamWriter` are the two that immediately come to mind. I really don't care if it is nullable or `-1`, we just shouldn't be hardcoding the value as that prevents us from impacting existing apps that are targeting newer versions of the framework (without them recompiling) if we determine that the current defaults are no longer representative (and buffer size defaults are something that should be modifiable given it can be fairly hardware dependent for the optimal size and we are picking a baseline based on profiling done today).

> No, also all the ones on PipeOptions

I'll update the root proposal.

**Comment by terrajobst** [comment]
Conclusion:

* Nullable would have been nice, but we can't change the type for some of the APIs (because they shipped) and we prefer consistency, so we're going with the sentinel value of `-1`.
