### ISSUE TITLE
ToLocalTime() in System.DateTime do not always produce expected result

### ISSUE THREAD

**Issue by ableji** [dotnet/corefx#37982]
# Issue Title

ToLocalTime() method in System.DateTime do not always produce correct result;

# General

based on my researches tehran time zone is kind of dynamic,
first half of year is (+4:30) and second half (+3:30) but ToLocalTime() always add 3:30.

there is more details here:
https://www.timeanddate.com/time/zone/iran/tehran
https://www.timeanddate.com/time/zone/iran

I think  ToLocalTime() must act dynamically in this case!

this is missing feature <b>or</b> its not concern of ToLocalTime()?

**Comment by tarekgh** [comment]
@ableji Which OS version you are running on? And which version of the .NET you are using?

**Comment by Clockwork-Muse** [comment]
Also, can we please see sample code that you're using?

**Comment by tarekgh** [comment]
I just tried that on Windows and Ubuntu machines and I am getting the right results. 

@ableji maybe the dates you used was wrong? I mean the daylight saving starts 4th week of March and ends on 3rd week of September. so please try dates like 2019/4/1 and 2019/19/1 and let me know what you are getting. don't forget to send the OS and .Net versions you are using and also send the code you are using as @Clockwork-Muse suggested.

**Comment by tarekgh** [comment]
@ableji I am closing this issue but feel free to respond back with the information if you still reproduce the problem you are seeing and then we can reopen this issue. Thanks for your report.

**Comment by ableji** [comment]
Im so sorry it  was my mistake, the problem was somewhere else in my code and every thing works perfectly
@tarekgh @Clockwork-Muse
