### ISSUE TITLE
How ignore bad comparer for backwards compatibility?

### ISSUE THREAD

**Issue by rfht** [dotnet/corefx#38006]
I have this old assembly that shipped with mono v4 (the game Terraria, but that's besides the point) and when I try to run it with mono 5.x, it fails on start because of

```
System.ArgumentException: Unable to sort because the IComparer.Compare() method returns inconsistent results...
```

I found out that this is because it is triggered by `System.Collections.Generic.ArraySortHelper<T>.Sort` as found in https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/shared/System/Collections/Generic/ArraySortHelper.cs#L68 and after manually disabling (commenting out) the exception the program runs fine with corert in mono 5. The comment [here](https://github.com/mono/mono/blob/master/mcs/class/referencesource/mscorlib/system/collections/generic/arraysorthelper.cs#L80) indicates that bad comparers used to be ignored.

Is there a reason why the [condition in that didn't throw for mono4 compat](https://github.com/mono/mono/blob/master/mcs/class/referencesource/mscorlib/system/collections/generic/arraysorthelper.cs#L87) isn't included in corert? Is there a different way to restore backwards-compatible behavior with this that I'm not aware of? If not, any chance that there could be a knob (flag, environment setting...) that could allow legacy behavior selectively?

**Comment by karelz** [comment]
How is CoreRT involved here? cc @jkotas 
Can you create a standalone repro demonstrating the problem? Is it potentially caused by Mono taking CoreFX sources? @marek-safar

**Comment by jkotas** [comment]
This is not CoreRT specific issue. This is bug-for-bug compatibility between .NET Framework and.NET Core (and all runtimes that are reusing .NET Core libraries).

**Comment by rfht** [comment]
> How is CoreRT involved here? cc @jkotas

CoreRT is used in mono's build. The corresponding code is here: https://github.com/mono/corert/blob/master/src/System.Private.CoreLib/shared/System/Collections/Generic/ArraySortHelper.cs#L43. It is pulled in as an external dependency in `external` directory (https://github.com/mono/mono/tree/master/external).

yes, @jkotas is right and this is about compatibility with previously tolerated buggy implementations. This seems to be a relatively non-invasive compatibility to enable, that's why I brought it up.

> Can you create a standalone repro demonstrating the problem?

Probably. I don't have access to the source code of the assembly that triggers this, but should be able to cook something up over the next few days...

> Is it potentially caused by Mono taking CoreFX sources? @marek-safar

The compatibility issue is pretty clearly associated with the switch to mono 5 and therefore the use of CoreFX sources in mono. Interestingly, the function is still called `ThrowOrIgnoreBadComparer`, but with the CoreRT code it seems to only throw, therefore leading to the compatibility issue I observed.

I am thinking of a patch to detect an old / .NET Framework assembly version and in that case ignore rather than throw; possibly with `TargetFrameworkAttribute`. If adding such a compatibility tweak is not categorically out of the question, I'll see what works and make a PR...?

**Comment by jkotas** [comment]
> If adding such a compatibility tweak is not categorically out of the question, I'll see what works and make a PR...?

The compatibility quirk for .NET Framework target framework does not make sense in .NET Core (ie CoreCLR or CoreRT) because of the target framework is never .NET Framework in .NET Core. 

If you care about this to be fixed in existing class libraries Mono, I think it would be best to fix it directly in the Mono fork.

**Comment by rfht** [comment]
That makes sense. I will bring it up with mono then. From my end this issue is closed then. Feel free to re-open if needed. I will post a link to mono thread once open.
