### ISSUE TITLE
Net Core 3.0 bootstrap failure for c7d48ca

### ISSUE THREAD

**Issue by joshudson** [dotnet/corefx#38008]
Commit c7d48ca7732b7717e84d8375588d83866104ef58 builds a really broken corefx when using 3.0preview5 as the initial bootstrap source.

    joshua@nova:~/netcore/corefxϟ uname -a
    Linux nova 4.19.0-4-amd64 #1 SMP Debian 4.19.28-2 (2019-03-15) x86_64 GNU/Linux
    joshua@nova:~/netcore/corefxϟPATH=/home/joshua/netcore/3.0preview5:$PATH ./build.sh -restore -build -buildtests -test

generates hunderds of test failures of the form

    <failure exception-type="System.TypeInitializationException">
          <message><![CDATA[System.TypeInitializationException : The type initializer for 'System.PlatformDetection' threw an exception.\n---- System.FormatException : Input string was not in a correct format.]]></message>
          <stack-trace><![CDATA[   at System.PlatformDetection.get_IsNonZeroLowerBoundArraySupported() in /home/joshua/netcore/corefx/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.cs:line 119
       at System.Text.RegularExpressions.Tests.GroupCollectionTests.ICollection_CopyTo_Invalid() in /home/joshua/netcore/corefx/src/System.Text.RegularExpressions/tests/GroupCollectionTests.cs:line 119
    ----- Inner Stack Trace -----
       at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type) in /_/src/System.Private.CoreLib/shared/System/Number.Parsing.cs:line 1929
       at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info) in /_/src/System.Private.CoreLib/shared/System/Number.Parsing.cs:line 218
       at System.Int32.Parse(String s) in /_/src/System.Private.CoreLib/shared/System/Int32.cs:line 107
       at System.PlatformDetection.ToVersion(String versionString) in /home/joshua/netcore/corefx/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs:line 165
       at System.PlatformDetection..cctor() in /home/joshua/netcore/corefx/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Unix.cs:line 84]]></stack-trace>
        </failure>

**Comment by wfurt** [comment]
Is the linked commit correct @joshudson ? 

BTW I don't think you can pick any random dotnet and expect corefx to build.

cc: @safern

**Comment by karelz** [comment]
@joshudson what exactly are you doing? Does it happen with latest source code as well?

**Comment by joshudson** [comment]
I'm trying to build a new corefx from master to test something else. I took the latest preview build to bootstrap from, cloned master and built with full testing yesterday. I can certainly pull master again and try again.

**Comment by joshudson** [comment]
Still happening with commit bd492f2084f9c6be6af5338f29a54e1c3bc65599 which is tip of master as of 2 minutes ago.

**Comment by karelz** [comment]
I don't understand why you say you need bootstrap.
Cloning CoreFX and building it should be doable by following our docs. Did you do that?
Or are you experimenting with unsupported OS/architecture?

**Comment by joshudson** [comment]
I located the problem. `PlatformAPIs.LoadDistroInfo()` tried to parse `/etc/os-release` for version, didn't find a number there. I'm guessing this is test harness code so I can just try/catch around parsing the string in `PlatformDetection.ToVersion()`

**Comment by karelz** [comment]
Why didn't it parse it on your system and it worked on everyone's else?

**Comment by joshudson** [comment]
Whoever wrote that code assumed it was a number. Not set isn't a number.

    joshua@nova:~ϟ cat /etc/os-release 
    PRETTY_NAME="Debian GNU/Linux buster/sid"
    NAME="Debian GNU/Linux"
    ID=debian
    HOME_URL="https://www.debian.org/"
    SUPPORT_URL="https://www.debian.org/support"
    BUG_REPORT_URL="https://bugs.debian.org/"
    joshua@nova:~ϟ 

I've got another spurious test failure pull request coming in a few minutes. Should we batch them together?

**Comment by karelz** [comment]
@joshudson you are the only persona out of couple of hundred that ran into this.
We should first figure out what is different on your system that leads to such special cases.
Don't batch unrelated PRs. Also, let's hold on first to figure out why is your system different than everyone's else ...

**Comment by karelz** [comment]
cc @wfurt

**Comment by joshudson** [comment]
A typical `/etc/os-release` would look something like this:

PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
    NAME="Debian GNU/Linux"
    VERSION_ID="9"
    VERSION="9 (stretch)"
    ID=debian
    HOME_URL="https://www.debian.org/"
    SUPPORT_URL="https://www.debian.org/support"
    BUG_REPORT_URL="https://bugs.debian.org/"

However, I'm on trunk debian (drivers...). `VERSION_ID` is not defined. This was causing the test harness to fail.

**Comment by danmosemsft** [comment]
Thanks for figuring this out, @joshudson

**Comment by wfurt** [comment]
'sid' is never-ending rolling release without number @karelz - like master vs 3.0. For that reason we don't test on it or claim support. It would be reasonable to take a fix to make parsing more resilient. (we may need one for core-setup as well)

**Comment by safern** [comment]
Marking as future since this is test code, not critical for 3.0. @joshudson thanks for figuring this out, would you be interested on putting up a PR to make our parsing more resilient here?

**Comment by joshudson** [comment]
@safern: PR is already up.

**Comment by safern** [comment]
> @safern: PR is already up.

Thanks, I completely missed it on the thread, but just saw that you linked it. Thanks 😄

**Comment by ViktorHofer** [comment]
Closing in favor of https://github.com/dotnet/corefx/issues/38443
