### ISSUE TITLE
Flat Request-Id

### ISSUE THREAD

**Issue by ArneMancofi** [dotnet/corefx#38011]
@lmolkova , in [FlatRequestId.md](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/FlatRequestId.md) , under [step 3 of the Non-hierarchical Request-Id example](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/FlatRequestId.md#non-hierarchical-request-id-example), how can "service-b ... scan through its headers and find `Request-Id: ghi`," when service-a sent `Request-Id: def`?
Perhaps this point needs some clarification in the text?

**Comment by lmolkova** [comment]
I guess this is a mistake. 
If you are interested in the correlation standard, this is the one: https://www.w3.org/TR/trace-context/

We will gracefully retire Request-Id (hierarchical and non-hierarchical). Please use new and shiny W3C trace-context.

**Comment by lmolkova** [comment]
I have just added deprecation note on flat-id spec in #38025 and referenced https://www.w3.org/TR/trace-context/ there. It has never been implemented and no code changes are expected.
