### ISSUE TITLE
X509Certificate2 contains empty "Subject" property on Linux on .Net Core 2.2

### ISSUE THREAD

**Issue by vitaaaly** [dotnet/corefx#38014]
I create X509Certificate2 instance from a byte array on Linux, but property "Subject" is empty.
When I make the same operation on Windows property "Subject" contains necessary information.

I use .Net Core 2.2.
Code for creation X509Certificate2:

` 

            var collection = new X509Certificate2Collection();

            collection.Import(rawData);

            var certificate = collection.Cast<X509Certificate2>().First();
`
[See original code](https://github.com/dotnet/corefx/issues/25828#issuecomment-351087167)

This code work well done on Linux and on Windows on .Net Core 2.1.
Problems started after .Net Core switching to 2.2.

**Comment by davidsh** [comment]
@bartonjs

**Comment by bartonjs** [comment]
In order to diagnose this at all I'd need to see a certificate for which this was true.

**Comment by vitaaaly** [comment]
@bartonjs I found the reason of this problem.
In ReadDirectoryOrIA5String of DictionaryStringHelper ([see here](https://github.com/dotnet/corefx/blob/e23119d577e644d2c2a25419c88c1181681358e0/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Helpers.cs#L215)) use swich..case that contains some UniversalTagNumbers, but in my case tag.TagValue is UniversalTagNumber.NumericString.
As result a have CryptographicException.

**Comment by bartonjs** [comment]
@vitaaaly The fact that hasn't come up in several years makes it a pretty unique certificate.  Looking at the RFC it says that common attributes are DirectoryString (and the semi-common email-address attribute is IA5String), I guess it doesn't have a serious grudge against NumericString; though it seems like it must be a custom attribute.
