### ISSUE TITLE
Hyperledger fabric : container_linux.go:344: starting container process caused "exec: \"scripts/script.sh\": stat scripts/script.sh: no such file or directory":

### ISSUE THREAD

**Issue by jlestercastro** [dotnet/corefx#38015]
Hello, someone know on how to fix this issue.
I'm setting up my first hyper ledger fabric network.
Getting Hyperledger-Image : OK

Generating Gensis block: Command : cd fabric-samples/first-network 
Status: OK
![image](https://user-images.githubusercontent.com/39945211/58541132-63bd4b80-822d-11e9-8816-5fd34df372c8.png)

But when running up the network show this.

![image](https://user-images.githubusercontent.com/39945211/58541205-8ea79f80-822d-11e9-806d-fed2d1bb15a1.png)

Always showing error: OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "exec: \"scripts/script.sh\": stat scripts/script.sh: no such file or directory": unknown
ERROR !!!! Test failed

Thank you.

**Comment by wfurt** [comment]
This seems like wrong repo @jlestercastro.
You this only for issues with .Net Core libraries.
