### ISSUE TITLE
Update to test on Alpine 3.9 for .NET Core 2.x

### ISSUE THREAD

**Issue by mthalman** [dotnet/corefx#38027]
CoreFX is currently being tested on Alpine 3.6 which is EOL. This should be updated to the latest, Alpine 3.9.

Example data showing 3.6 is being used: https://mc.dot.net/#/product/netcore/21msrc/source/prodcon~2Fcorefx~2Frelease~2F2.1-msrc~2F/type/test~2Ffunctional~2Fcli~2F/build/20190412.01

Also, the CI build seems to be using 3.8 and should also be updated to 3.9.

This issue applies to servicing for 2.x.  A separate issue exist for 3.0 (#37646)

**Comment by mthalman** [comment]
It's important this get done very soon because we already have published Docker images for .NET Core 2.x and 3.0 on Alpine 3.9 and we've got a requirement to make this the default Alpine version.

**Comment by wtgodbe** [comment]
I'll work with @wfurt to get this done before the next 2.x release. @mthalman Can I find the new 3.9 images in the list from https://github.com/dotnet/dotnet-buildtools-prereqs-docker? I see the following tags:

>     "alpine-3.9-helix-09ca40b-20190508143246",
    "alpine-3.9-helix-09ca40b-20190521001803",
    "alpine-3.9-helix-34f2903-20190227035445",
    "alpine-3.9-helix-3e800f1-20190501005341",
    "alpine-3.9-helix-3e800f1-20190502142303",
    "alpine-3.9-helix-98b4f89-20190506161422",
    "alpine-3.9-helix-a1cb429-20190228124956",
    "alpine-3.9-helix-af66924-20190215231918",
    "alpine-3.9-helix-ce7c948-20190227232728",
    "alpine-3.9-helix-e4eaef4-20190228230637",
    "alpine-3.9-helix-e4eaef4-20190327215821",
    "alpine-3.9-helix-e4eaef4-20190415134749",

**Comment by mthalman** [comment]
CC @MattGal 
Yes, the latest would be `alpine-3.9-helix-09ca40b-20190521001803` in that list.

**Comment by MattGal** [comment]
@wtgodbe I am going to be updating all the helix-named images to have python 3 by default as part of https://github.com/dotnet/core-eng/issues/6668, you might hold off til then.

**Comment by wtgodbe** [comment]
Resolved by https://github.com/dotnet/corefx/pull/38404 & @MattGal 's follow-up
