### ISSUE TITLE
Test - Fix FakeNetwrokStream(System.Net.Security.Tests) read method  for successive network read

### ISSUE THREAD

**Issue by rajansingh10** [dotnet/corefx#3802]
In SslStreamStreamToStreamTest.cs, SslStream_StreamToStream_Successive_ClientWrite_Success need to rely on DoNetworkRead() of FakeNetwrokStream because of the limitation of FakeNetworkStream. The read method in FakeNetworkStream does do NetworkRead on some condition which itself is wrong. As a result, in successive read, data is never read from the network.
So for now we have put a workaround method named DoNetworkRead(), which is being explicitly called from  SslStream_StreamToStream_Successive_ClientWrite_Success.

This issue is to remove DoNetworkRead() & find the real fix so that a NetworkStream encapsulation is maintained

**Comment by vijaykota** [comment]
Will fix this for RTM since this is a fix in the test code

**Comment by vijaykota** [comment]
Fixed via https://github.com/dotnet/corefx/pull/4297
