### ISSUE TITLE
.NET breaks smartctl program

### ISSUE THREAD

**Issue by ygoe** [dotnet/corefx#38033]
I can't use the `smartctl` program from a .NET Core application. On Ubuntu 16.04 Server, this happens when I run the command `smartctl -A '/dev/sda'` as root:

```
smartctl 6.5 2016-01-24 r4214 [x86_64-linux-4.4.0-148-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF READ SMART DATA SECTION ===
SMART Attributes Data Structure revision number: 16
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  1 Raw_Read_Error_Rate     0x000b   100   100   016    Pre-fail  Always       -       0
  2 Throughput_Performance  0x0005   140   140   054    Pre-fail  Offline      -       68
  3 Spin_Up_Time            0x0007   100   100   024    Pre-fail  Always       -       0
  4 Start_Stop_Count        0x0012   100   100   000    Old_age   Always       -       4
  5 Reallocated_Sector_Ct   0x0033   100   100   005    Pre-fail  Always       -       0
  7 Seek_Error_Rate         0x000b   100   100   067    Pre-fail  Always       -       0
  8 Seek_Time_Performance   0x0005   124   124   020    Pre-fail  Offline      -       33
  9 Power_On_Hours          0x0012   095   095   000    Old_age   Always       -       39604
 10 Spin_Retry_Count        0x0013   100   100   060    Pre-fail  Always       -       0
 12 Power_Cycle_Count       0x0032   100   100   000    Old_age   Always       -       4
192 Power-Off_Retract_Count 0x0032   100   100   000    Old_age   Always       -       15
193 Load_Cycle_Count        0x0012   100   100   000    Old_age   Always       -       15
194 Temperature_Celsius     0x0002   181   181   000    Old_age   Always       -       33 (Min/Max 25/39)
196 Reallocated_Event_Count 0x0032   100   100   000    Old_age   Always       -       0
197 Current_Pending_Sector  0x0022   100   100   000    Old_age   Always       -       0
198 Offline_Uncorrectable   0x0008   100   100   000    Old_age   Offline      -       0
199 UDMA_CRC_Error_Count    0x000a   200   200   000    Old_age   Always       -       0
```

When I start the same command through .NET Core, this is the output:

```
smartctl 6.5 2016-01-24 r4214 [x86_64-linux-4.4.0-148-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

'/dev/sda': Unable to detect device type
Please specify device type with the -d option.

Use smartctl -h to get a usage summary
```

This is the code:

```c#
long? temp = null;

var psi = new ProcessStartInfo("smartctl", "-A '/dev/" + device + "'")
{
	RedirectStandardOutput = true,
	UseShellExecute = false
};
var p = Process.Start(psi);
while (!p.StandardOutput.EndOfStream)
{
	string line = p.StandardOutput.ReadLine();
	Console.WriteLine(line);
	if (line.StartsWith("194 "))
	{
		Console.WriteLine("[Match 194]");
		string[] parts = Regex.Split(line, @"\s+");
		if (parts.Length >= 10)
		{
			temp = long.Parse(parts[9]);
			Console.WriteLine("[Temp]");
		}

		p.StandardOutput.ReadToEnd();   // Kindly eat up the remaining output
	}
}
```

.NET Core 2.2 on Linux x64. The same command works fine when calling from a PHP interpreter and when piping through `cat`. So I guess .NET Core destroys the environment in a way that breaks `smartctl`.

**Comment by ygoe** [comment]
Little update: The same code works fine through Mono 4.2.1. It's just .NET Core that breaks it.

Here's the output of `dotnet --info`:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.700
 Commit:    c2ef055a0f

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.700/

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.0.3 [/usr/share/dotnet/sdk]
  2.1.4 [/usr/share/dotnet/sdk]
  2.1.700 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

The app I'm using now was created with VS 2019 today, using the code from the old Mono app that's in use for years.

**Comment by danmosemsft** [comment]
> So I guess .NET Core destroys the environment in a way that breaks smartctl.

Does it help to compare `strace` traces of `smartctl` between working and non working cases?

**Comment by krwq** [comment]
Also in addition to what @danmosemsft asked could you print output of following:

```
shopt -s extdebug
declare -F smartctl
shopt -u extdebug
type -a smartctl
```

**Comment by danmosemsft** [comment]
Good thinking @krwq. When I run `smartctl -A '/dev/sdc'` on my Ubuntu I get `/dev/sdc: Unable to detect device type` - no quotes in output. If I do `smartctl -A \'/dev/sdc\'` I get  `'/dev/sdc': Unable to detect device type` . So I think you are getting literal quotes in your output due to literal quotes in your input due to perhaps the issue mentioned.

**Comment by ygoe** [comment]
There seems to be a difference in command-line arguments handling. Left is through `dotnet`, right is called directly from the shell. The string quoting of `'/dev/sda'` is not resolved in the left case.

![grafik](https://user-images.githubusercontent.com/868315/58625319-82c1e900-82d2-11e9-9fb8-4e2fcfaab88f.png)

**Comment by wfurt** [comment]
note, that the quotes are processed by shell it self. When you use excecv() (Or dotnet)  that does not happen so the utility will get what you passed in. 

I don't think this is bug. You should not depend on shell processing unless you start  `/bin/sh -c smartctl -A '/dev/sda'`

You should be able to see that when running:
`strace -f -e trace=%process mycoolapp`

**Comment by ygoe** [comment]
How would you suggest doing this with .NET?:

* call executable: `smartctl`
* argv[1]: `-A`
* argv[2]: `a path with spaces`

**Comment by wfurt** [comment]
Good question. This should work:
```
new ProcessStartInfo("smartctl", "-A \"a path with spaces\"");
```
I think the behavior comes from Windows where single quote is not uses.  Since there is no variable expansion `'` and `"` are basically same.

Better yet, you could use ArgumentList:
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.argumentlist?view=netcore-2.1#System_Diagnostics_ProcessStartInfo_ArgumentList

That would take out ambiguity about quoting and parsing string to elements.

**Comment by ygoe** [comment]
Good info, I didn't know that `ArgumentList` existed. Seems to be new. But not explained much. I've created an [issue about that](https://github.com/MicrosoftDocs/feedback/issues/1601).

**Comment by MrM40** [comment]
It's my experience that `ArgumentList` doesn't parse single quotes any better. I'm still looking/waiting for a solution/fix to parse single quotes with `Process.Star`t and `ProcessStartInfo.Arguments`

**Comment by krwq** [comment]
@MrM40 

> It's my experience that ArgumentList doesn't parse single quotes any better.

could you give an example of broken scenario? (with expected and actual output)

**Comment by MrM40** [comment]
Sorry, I got wiser sinse :-P
An example of an command in Linux shell which include a single quote:
`dpkg-query -W -f=' ${db:Status-Status} ' mariadb*`

In C#:

     ....
     ProcessStartInfo pi = new ProcessStartInfo("dpkg-query");
     pi.ArgumentList.Add("-W");
     pi.ArgumentList.Add("-f= ${db:Status-Status} ");
     pi.ArgumentList.Add("mariadb*");
     ....

or going through the shell:

     ....
     ProcessStartInfo pi = new ProcessStartInfo("sh");
     pi.ArgumentList.Add("-c");
     pi.ArgumentList.Add("dpkg-query -W -f=' ${db:Status-Status} ' mariadb*");
     ....

**Comment by wfurt** [comment]
is there anything left on this issue or shall we close it?

**Comment by MrM40** [comment]
I believe it can be closed :-)
