### ISSUE TITLE
MemoryMarshal.AsBytes<T>(...) for Memory<T>

### ISSUE THREAD

**Issue by vitidev** [dotnet/corefx#38052]
Why MemoryMarshal does not contain overloads for Memory<T>?

     MemoryMarshal.AsBytes<T>(Memory<T>)
     MemoryMarshal.AsBytes<T>(ReadOnlyMemory<T>)

**Comment by johnkellyoxford** [comment]
This wouldn't really be possible I think, because you cannot cast an underlying `T[]`/`string`/`MemoryManager<T>` to a byte version, without some kind of flag inside `Memory<T>` indicating to cast the resultant `Span<T>` from `.Span` into a `Span<byte>`, which increases the size of it

**Comment by jkotas** [comment]
Correct. This is not implementable as @johnkellyoxford explained.
