### ISSUE TITLE
Path directory separator tests failing on Unix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#38066]

**Comment by stephentoub** [comment]
cc: @MarcoRossignoli

**Comment by MarcoRossignoli** [comment]
@stephentoub PR ready https://github.com/dotnet/corefx/pull/38096

**Comment by karelz** [comment]
Is it addressed in the merged PR #38096 or is the bug still active?

**Comment by MarcoRossignoli** [comment]
Fixed we can close

**Comment by karelz** [comment]
Fixed by #38096
