### ISSUE TITLE
System.Threading.Tasks.Extensions shipped multiple times with same assembly version, different assembly references

### ISSUE THREAD

**Issue by AArnott** [dotnet/corefx#38065]
The System.Threading.Tasks.Extensions.dll assembly shipped multiple times on nuget.org with the *same assembly version* but with *different assembly references*. 

Specifically:

| NuGet package version | Assembly version | Assembly version of reference to System.Runtime.CompilerServices.Unsafe |
|--|--|--|
| 4.5.0 | 4.2.0.0 | 4.0.4.0 |
| 4.5.1 | 4.2.0.0 | 4.0.4.0 |
| 4.5.2 | 4.2.0.0 | 4.0.4.**1** |

Notice how the 4.5.2 package release of the System.Threading.Tasks.Extensions assembly changed the version of System.Runtime.CompilerServices.Unsafe that is referenced, but kept its own assembly version the same.

This led to a regression when shipping Visual Studio 2019 Update 1 that led to some customers being unable to use VS at all because it would keep crashing. After several days of investigation we found the root cause:
 
We had several processes that shipped the 4.5.2 package version of System.Threading.Tasks.Extensions together with the Unsafe 4.0.4.1 assembly. But some customer machines have the System.Threading.Tasks.Extensions.dll that came from the 4.5.0-4.5.1 package range in their GAC, and did _not_ have the Unsafe 4.0.4.0 in their GAC. As a result, when our processes load, instead of loading the 4.5.2 package version, the CLR loaded the 4.5.0 version from the GAC, and then failed to find the Unsafe 4.0.4.0 assembly since the one we shipped is 4.0.4.1. 

Now granted, whoever or whatever installed the System.Threading.Tasks.Extensions.dll into the GAC without also GAC'ing all its dependencies is obviously to blame here, I thought the corefx policy was that the assembly version would change every single time a corefx assembly changed and shipped on nuget.org. That policy was obviously not followed here and had it been, we would have been protected from a faulty installer in another application.

We're going to add an artificial binding redirect to our processes' app.config files to redirect Unsafe 4.0.4.0 to 4.0.4.1 as a workaround.

Can/should a new System.Threading.Tasks.Extensions package version be pushed to nuget with a new assembly version so we and others can consume that and be implicitly protected from such a situation?

**Comment by AArnott** [comment]
[One of the many customer reports of the VS crash](https://developercommunity.visualstudio.com/content/problem/569009/unable-to-start-visual-studio-1610-p3.html)

**Comment by danmosemsft** [comment]
@joperezr

**Comment by joperezr** [comment]
This package is built out of the release branch so it would need to be fixed there. The problem here was caused do to servicing the package since we needed to remove the reference assets out of it, but in order to do that we did rebuild the package after a different change went in that rev'ed the Unsafe assembly. I can fill up the release template and submit a PR with the fix.

**Comment by tarekgh** [comment]
@ericstj I originally moved it to infrastructure because we need to look at any other library suffer from the same issue. I recall the guidelines was infrastructure include the build and packaging of the libraries.
