### ISSUE TITLE
JsonSerializer throws MissingMethodException

### ISSUE THREAD

**Issue by Yucked** [dotnet/corefx#38064]
StackTrace:

```
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Byte[] System.Text.Json.Serialization.JsonSerializer.ToBytes(!!0, System.Text.Json.Serialization.JsonSerializerOptions)'.
  Source=Frostbyte
  StackTrace:
   at Frostbyte.Handlers.ConfigHandler.ValidateConfiguration() in D:\Projects\Frostbyte\Handlers\ConfigHandler.cs:line 43
   at Frostbyte.Handlers.StartupHandler.<InitializeAsync>d__3.MoveNext() in D:\Projects\Frostbyte\Handlers\StartupHandler.cs:line 36
```

Throw right here: https://github.com/Yucked/Frostbyte/blob/master/Handlers/StartupHandler.cs#L36

SDK and RunTime

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011568
 Commit:    b487ff10aa

Host (useful for support):
  Version: 3.0.0-preview6-27729-07
  Commit:  7982806713```

**Comment by ahsonkhan** [comment]
The `JsonSerializer.ToBytes` method was recently renamed to `ToUt8Bytes`, so I suspect there is some mismatching bits causing the concern here. Can you try with the latest SDK and see if you are still hitting this issue?
https://github.com/dotnet/corefx/issues/37898

cc @pranavkm, @BrennanConroy from the aspnet side in case they have some insights.

**Comment by pranavkm** [comment]
You likely need the preview6 SDK, since that determines what you're compiling against.

**Comment by Yucked** [comment]
I'm guessing this is the right place to download the prev6 SDK: https://github.com/dotnet/core-sdk#installers-and-binaries

**Comment by ahsonkhan** [comment]
> I'm guessing this is the right place to download the prev6 SDK

Yep!

**Comment by Yucked** [comment]
Thank you, that fixed the issue!
