### ISSUE TITLE
[QUESTION]VS Debugging issue

### ISSUE THREAD

**Issue by MarcoRossignoli** [dotnet/corefx#38071]
I cannot see variables on watch debug windows with VS2019 Preview only for corefx solutions
![image](https://user-images.githubusercontent.com/7894084/58658057-ede5dc80-831f-11e9-882e-68f93fba65db.png)

```
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.2.0 Preview 1.0
VisualStudio.16.Preview/16.2.0-pre.1.0+28917.182
Microsoft .NET Framework
Version 4.8.03761

Installed Version: Enterprise
```
Does anyone know the reason?Is it only my issue?

**Comment by danmosemsft** [comment]
Did you build release? That can break expression eval in many cases.

**Comment by ahsonkhan** [comment]
> I cannot see variables on watch debug windows with VS2019 Preview only for corefx solutions

There was a recently issue with the debugger (seemingly for structs only), where locals weren't showing up.

A temporary workaround would have been to attach the VS debugger to a running test (by running it via the command line), with `System.Diagnostics.Debugger.Launch();` added within the test you want to debug. I think that would have worked to resolve the locals issue, but not sure (feel free to try and let me know, I am curious):
For example:
```text
E:\GitHub\Fork\corefx\src\System.Text.Json\tests>dotnet msbuild /t:BuildAndTest /p:XUnitMethodNam=System.Text.Json.Serialization.Tests.StreamTests.ClassWithIndexerTest
```

I believe this has now been fixed (and the coreclr bits got ingested to corefx). See https://github.com/dotnet/coreclr/pull/24798

I just verified it myself in corefx master:
![image](https://user-images.githubusercontent.com/6527137/58743207-47aedb00-83e2-11e9-98dc-0e986c3e9574.png)


cc @steveharter, @cshung, @tommcdon, @layomia, @JeremyKuhne

**Comment by ahsonkhan** [comment]
Closing as fixed. Feel free to re-open if it isn't.

**Comment by MarcoRossignoli** [comment]
Thanks guys!

**Comment by MarcoRossignoli** [comment]
Confirm that after re-clone all works as expected.
