### ISSUE TITLE
System.Drawing.ImageConverter cannot convert from System.Drawing.Icon

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#38080]
Transfered from: https://github.com/dotnet/winforms/issues/985

Minimal repro:

Create a Winforms .NET Core app.

Add following code into Form.cs file.
```cs
public Form1()
{
    InitializeComponent();

     Icon test_Icon = Icon;
     myObj = new ImageConverter();
     Object result_obj = myObj.ConvertFrom(test_Icon);

}

protected System.Drawing.ImageConverter myObj = null;
```

Make a breakpoint at this code line: Object result_obj = myObj.ConvertFrom(test_Icon);

Run the app.

@Anipik maybe you could help with this one? 

It seems like we missed this when porting: https://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/ImageConverter.cs,40

cc: @danmosemsft

**Comment by Anipik** [comment]
sure I will take a look into it

**Comment by safern** [comment]
Thanks 😄 -- assigned.

**Comment by Anipik** [comment]
Adding this fixes the error https://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/ImageConverter.cs,76

I will throw a pr to fix this
