### ISSUE TITLE
Create visual designer for TPL dataflow

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/corefx#38086]
The system.threading.tasks.dataflow namespace allow defining tasks as a network of linked blocks. I think using it will be easier if we can use a visual designer to define the blocks, link them and configure there properties, then the designer produces the code, so we can only focus on the code we write inside each block (double-clicking the block entity in the designer should open the related method in code editor.

**Comment by stephentoub** [comment]
That would be a fine project for someone to work on.  But corefx generally isn't the right place for such tooling, and I don't see that being a priority any time in the foreseeable future.

**Comment by VBAndCs** [comment]
@stephentoub
I know it needs to be a part on VS.NET and VSCode to be used with any type of project, but the nuget refers to this repo as the project site.

>  I don't see that being a priority any time in the foreseeable future.

It can simplify concurrent programming, make the code more readable, and apply the separation of concerns principal.

**Comment by terrajobst** [comment]
Yeah, this request doesn't belong here. We wouldn't be the ones building it. So tracking it here doesn't make much sense either. So I'm closing it.
