### ISSUE TITLE
ImmutableHashSet<T>.SetEquals has redundant counter

### ISSUE THREAD

**Issue by GeorgeAlexandria** [dotnet/corefx#38094]
Hello,

The implementation of [ImmutableHashSet\`T.SetEquals](https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableHashSet_1.cs#L744) use redundant [`matches`](https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableHashSet_1.cs#L754) counter. This counter is redundant because 

* implementation contains check that the two `ISet` collections, which are created by the same `IEqualityComparer`, have the same count
* implementation iterate the all items from the second collection and check that the all of them is containing in the first collection, otherwise implementation returns false

So after iteration, if it wasn't broken, we actually know, that the two collections contain the same items.

I suppose that the implementation must be as the follow code:
```diff
        private static bool SetEquals(IEnumerable<T> other, MutationInput origin)
        {
            Requires.NotNull(other, nameof(other));

            var otherSet = new HashSet<T>(other, origin.EqualityComparer);
            if (origin.Count != otherSet.Count)
            {
                return false;
            }

-           int matches = 0;
            foreach (T item in otherSet)
            {
                if (!Contains(item, origin))
                {
                    return false;
                }

-               matches++;
            }

-           return matches == origin.Count;
+           return true;
        }
```

If I miss something, let me know about it

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/corefx/pull/38325
