### ISSUE TITLE
ProcessStart_OpenFileOnLinux_UsesSpecifiedProgram failed in CI on Linux

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#38114]
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fskip-oledb/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190530.2/workItem/System.Diagnostics.Process.Tests/analysis/xunit/System.Diagnostics.Tests.ProcessTests~2FProcessStart_OpenFileOnLinux_UsesSpecifiedProgram(programToOpenWith:%20%5C%22vi%5C%22)
```
Unhandled Exception of Type System.InvalidOperationException
Message :
System.InvalidOperationException : Process has exited, so the requested information is not available.
Stack Trace :
   at System.Diagnostics.Process.EnsureState(State state) in /_/src/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 958
   at System.Diagnostics.Process.get_ProcessName() in /_/src/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 512
   at System.Diagnostics.Tests.ProcessTests.ProcessStart_OpenFileOnLinux_UsesSpecifiedProgram(String programToOpenWith) in /_/src/System.Diagnostics.Process/tests/ProcessTests.Unix.cs:line 310
```

**Comment by danmosemsft** [comment]
More info in the console output
```
vi: can't read user input
    System.Diagnostics.Tests.ProcessTests.ProcessStart_OpenFileOnLinux_UsesSpecifiedProgram(programToOpenWith: "vi") [FAIL]
[?1049h[999;999H[6n[1;1H[J[1;1HProcessStart_OpenFileOnLinux_UsesSpecifiedProgram[2;1H~[3;1H~[4;1H~[5;1H~[6;1H~[7;1H~[8;1H~[9;1H~[10;1H~[11;1H~[12;1H~[13;1H~[14;1H~[15;1H~[16;1H~[17;1H~[18;1H~[19;1H~[20;1H~[21;1H~[22;1H~[23;1H~[1;1H[24;1H[K- /tmp/ProcessTests_bhkkqfmd.3ss/ProcessStart_OpenFileOnLinux_UsesSpecifiedProgr[1;1H[24;1H[K      System.InvalidOperationException : Process has exited, so the requested information is not available.
      Stack Trace:
        /_/src/System.Diagnostics.Process/src/System/Diagnostics/Process.cs(958,0): at System.Diagnostics.Process.EnsureState(State state)
        /_/src/System.Diagnostics.Process/src/System/Diagnostics/Process.cs(512,0): at System.Diagnostics.Process.get_ProcessName()
        /_/src/System.Diagnostics.Process/tests/ProcessTests.Unix.cs(310,0): at System.Diagnostics.Tests.ProcessTests.ProcessStart_OpenFileOnLinux_UsesSpecifiedProgram(String programToOpenWith)
```

This same output is on all 4 Alpine legs, but only 2 failed. Presumably `vi` is failing and it's just a race to read the process name first.

**Comment by danmosemsft** [comment]
Happened to notice https://bugs.alpinelinux.org/issues/2259 which apparently is long fixed but suggests it can happen because a previous process messed up stdin.

We need access to a shell here so we can repro with `strace`. @wfurt do we/you have a way to do this? Repro tool?

**Comment by danmosemsft** [comment]
cc @tmds in case all this escaped goo above suggests a theory to him.

**Comment by wfurt** [comment]
Seems like we observed some instability in #31970 and decided to disable 'vi' test on Alpine. For recored, on Alpine 'vi' is not normal application but rather minimal implementation using BusyBox. Now, since we start this all in background, vi should not share normal stdin. However, because 'vi' is  interactive it may also need /dev/tty besides stdin. I don't know what we do to make sure we have controlling terminal when running tests in background. 
From this and #31970 it all smells like race condition. That could be bug in busybox, our tests logic or production code. 

To answer your question @danmosemsft: We run all Alpine tests as containers so it is trivial to run same environment using same tag from eng/pipelines/linux.yml
I don't think kernel matters in this case but we use ubuntu.1604 as base host.

**Comment by danmosemsft** [comment]
Thanks @tmds. I don't realize even vi is part of busybox. I wonder whether there is a more suitable executable for this test.

**Comment by wfurt** [comment]
we can update images and use "vim" instead. 
However I think it would be nice to understand what is going on. I don't know if we need interactive program for this test or not. Maybe as next step, we should try to reproduce it locally with identical container. 

One more note that the characters in log looks like ANSI escaper sequences. We may use TERM=dumb to avoid it.

**Comment by tmds** [comment]
> However I think it would be nice to understand what is going on. I don't know if we need interactive program for this test or not. Maybe as next step, we should try to reproduce it locally with identical container.

`vi` on alpine exits shortly after starting when stdin is not a terminal.

Looking at what the test does (and ProcessStart_OpenFileOnLinux_UsesSpecifiedProgramUsingArgumentList), this test could use the `sleep` command instead.
