### ISSUE TITLE
Consider unsealing SocketsHttpHandler 

### ISSUE THREAD

**Issue by IlyaGrebnov** [dotnet/corefx#38122]
HttpClientHandler is unsealed, but doesn't expose PooledConnectionLifetime, so I have to fallback to SocketsHttpHandler. Now I am trying to enable HTTP/2 using code below unfortunately it doesn't compile because HttpClientHandler is sealed and thee is no suitable method found to override.

Any suggestions? CC @stephentoub 

        private class Handler : SocketsHttpHandler
        {
            private static readonly Version Http2 = new Version(2, 0);

            protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
            {
                request.Version = PlatformDetection.IsNetCore3OrAbove ? Handler.Http2 : request.Version;
                return base.SendAsync(request, cancellationToken);
            }
        }

**Comment by stephentoub** [comment]
> Any suggestions?

Create a delegating handler whose job it is to update the request appropriately, and wrap it around the underlying handler that'll send the request:
```C#
public sealed class Http2VersionHandler : DelegatingHandler
{
    private static readonly Version Http2 = new Version(2, 0);

    public Http2VersionHandler(HttpMessageHandler innerHandler) : base(innerHandler) { }

    protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        request.Version = PlatformDetection.IsNetCore3OrAbove ? Http2 : request.Version;
        return base.SendAsync(request, cancellationToken);
    }
}
...
// Instead of:
var client = new HttpClient(new SocketsHttpHandler() { ... });

// use:
var client = new HttpClient(new Http2VersionHandler(new SocketsHttpHandler() { ... }));
```
?

**Comment by IlyaGrebnov** [comment]
This is good suggestion. Thank you!
