### ISSUE TITLE
Custom TaskScheduler replaced by the default one for no apparent reason

### ISSUE THREAD

**Issue by fernacolo** [dotnet/corefx#38149]
I'm trying to build a custom `TaskScheduler` that uses the priority of each task to make scheduling decisions. Basically, if there are two or more tasks ready to run, it should schedule the one that has more priority.

I can put priority information in a custom `SynchronizationContext` and communicate it to my custom `TaskScheduler`. The problem is that certain `await` patterns cause the scheduler to be lost for no apparent reason. Here is the smallest repro code I could make:

```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;

namespace ReproApp
{
    internal static class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine(RuntimeInformation.FrameworkDescription);
            var scheduler = new MyTaskScheduler();
            var context = new MySynchronizationContext(scheduler);
            context.Post(Run, null);
            Thread.Sleep(3000);
        }

        private static void Run(object state)
        {
            RunAsync(); // no await here, intentional.
        }

        private static async Task RunAsync()
        {
            Logger.WriteLine("Before InternalRunAsync"); // <-- Scheduler OK.
            await InternalRunAsync();
            Logger.WriteLine("After InternalRunAsync"); // <-- Scheduler changed. WHY???
        }

        private static async Task InternalRunAsync()
        {
            Logger.WriteLine("Before Delay"); // <-- Scheduler OK.
            await Task.Delay(TimeSpan.FromSeconds(1.5));
            Logger.WriteLine("After Delay"); // <-- Scheduler OK.
        }
    }

    internal static class Logger
    {
        private static readonly Stopwatch sw = Stopwatch.StartNew();

        public static void WriteLine(string msg)
        {
            var nativeThreadId = AppDomain.GetCurrentThreadId();
            var threadId = Thread.CurrentThread.ManagedThreadId;
            var syncContext = SynchronizationContext.Current?.ToString() ?? "null";
            var scheduler = TaskScheduler.Current.ToString();
            Console.WriteLine(
                $"[{(int) sw.Elapsed.TotalMilliseconds} native:{nativeThreadId} managed:{threadId} syncCtx:{syncContext} sch:{scheduler}] {msg}");
        }
    }

    internal sealed class MySynchronizationContext : SynchronizationContext
    {
        private readonly MyTaskScheduler scheduler;

        public MySynchronizationContext(MyTaskScheduler scheduler)
        {
            this.scheduler = scheduler;
        }

        public override SynchronizationContext CreateCopy()
        {
            return new MySynchronizationContext(scheduler);
        }

        public override void Post(SendOrPostCallback d, object state)
        {
            void SetContextAndCall()
            {
                SetSynchronizationContext(this);
                d(state);
            }

            new Task(SetContextAndCall).Start(scheduler);
        }

        public override void Send(SendOrPostCallback d, object state)
        {
            void SetContextAndCall()
            {
                SetSynchronizationContext(this);
                d(state);
            }

            new Task(SetContextAndCall).RunSynchronously(scheduler);
        }
    }

    internal sealed class MyTaskScheduler : TaskScheduler
    {
        protected override void QueueTask(Task task)
        {
            ThreadPool.QueueUserWorkItem(RunTask, task);
        }

        private void RunTask(object state)
        {
            var task = (Task) state;
            TryExecuteTask(task);
        }

        protected override bool TryExecuteTaskInline(Task task, bool taskWasPreviouslyQueued)
        {
            return TryExecuteTask(task);
        }

        protected override IEnumerable<Task> GetScheduledTasks()
        {
            return new List<Task>();
        }
    }
}
```

And here is the output:

```
.NET Core 3.0.0-preview5-27626-15
[0 native:4 managed:4 syncCtx:ReproApp.MySynchronizationContext sch:ReproApp.MyTaskScheduler] Before InternalRunAsync
[2 native:4 managed:4 syncCtx:ReproApp.MySynchronizationContext sch:ReproApp.MyTaskScheduler] Before Delay
[1513 native:4 managed:4 syncCtx:ReproApp.MySynchronizationContext sch:ReproApp.MyTaskScheduler] After Delay
[1514 native:4 managed:4 syncCtx:ReproApp.MySynchronizationContext sch:System.Threading.Tasks.ThreadPoolTaskScheduler] After InternalRunAsync
```

The 4th log entry shows that my task scheduler was mysteriously replaced by the default. Why?

This prevents my prioritization solution to work properly because everything running on the wrong task scheduler will not be scheduled with the correct priority.

**Comment by tarekgh** [comment]
@stephentoub it looks the second part of the method ```RunAsync()``` which is after the await, is executing in a method which doesn't have any Task associated with it. interesting enough, if you add any Task related call, the context and the scheduler will be restored:

```C#
        private static async Task RunAsync()
        {
            // Context and Scheduler are correct 

            await InternalRunAsync();

            // Context and Scheduler are NOT correct because there is no Task associated with the currently executing thread. (i.e Task.t_currentTask is null)

            await Task.Delay(TimeSpan.FromSeconds(1));

            // Context and Scheduler are restored correctly  
        }
```

any thing bill a ring here?

**Comment by kevingosse** [comment]
As I understand it, the continuation of `InternalRunAsync` is inlined because the thread is already using the desired synchronization context. If you replace `SetSynchronizationContext(this);` with `SetSynchronizationContext(new MySynchronizationContext(scheduler));` then it'll work as expected.

To be honest, I wasn't aware continuations could ever be inlined under a synchronization context. 

In any case, I believe the synchronization context shouldn't be used to store information related to the TaskScheduler. You probably should use the ExecutionContext instead (through `AsyncLocal<T>`).

**Comment by fernacolo** [comment]
> If you replace SetSynchronizationContext(this); with SetSynchronizationContext(new MySynchronizationContext(scheduler)); then it'll work as expected.

That was indeed the case. Can you please elaborate? Why the current instance, which is also of type `MySynchronizationContext`, cannot be used? What is different between the two instance (`this` and the new one)?

**Comment by fernacolo** [comment]
The reason I'm asking that is to look for an optimization opportunity and avoid creating an object all the time, in case I can't use the `AsyncLocal<T>` for some reason.

**Comment by kevingosse** [comment]
Unless I'm mistaken, you're hitting that test:

https://github.com/dotnet/coreclr/blob/25878db0c11bfb8d52088c75ccfcc13e4c8383f2/src/System.Private.CoreLib/shared/System/Threading/Tasks/TaskContinuation.cs#L386-391

https://github.com/dotnet/coreclr/blob/25878db0c11bfb8d52088c75ccfcc13e4c8383f2/src/System.Private.CoreLib/shared/System/Threading/Tasks/TaskContinuation.cs#L386_391

This is an optimization. What awaiting a task under a synchronization context guarantees you is that your continuation will run under that same synchronization context. After awaiting `Task.Delay`, the continuation is completed by a threadpool thread, operating outside of the synchronization context. So the framework calls `SynchronizationContext.Post` to put back the continuation in the right context. Then the `InternalRunAsync` completes, and the `RunAsync` state-machine must be invoked again. This is done by the same thread that completed `InternalRunAsync` (that is, the one that was called by `SynchronizationContext.Post`). But this thread already operates under the right synchronization context! So the framework resumes the execution of the state-machine without calling `Post` again. And how does the runtime know that the thread is already using the right synchronization context? By checking ` m_syncContext == SynchronizationContext.Current`.

**Comment by tarekgh** [comment]
@kevingosse thanks for your analysis. 

@fernacolo I am closing the issue but feel free to send any more questions if you have any.
