### ISSUE TITLE
Instructions for patching private CLR do not work

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#38144]
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md#testing-with-private-coreclr-bits says I can build from the root, then apply a private CoreCLR using `dotnet msbuild /p:CoreCLROverridePath=d:\git\coreclr\bin\Product\Windows_NT.x64.Release\ ./external/runtime/runtime.depproj`
however that gives
```
Error:

    An assembly specified in the application dependencies manifest (Microsoft.NETCore.App.deps.json) was not found:

      package: 'Microsoft.NETCore.App', version: '9.9.9'

      path: 'runtimes/rid/native/comhost.dll'

  ----- end 20:37:24.40 ----- exit code -2147450740 ----------------------------------------------------------
```
the workaround is to  run dotnet msbuild on src/pretest.builds before running a test and after building runtime.depproj

@ericstj @safern

**Comment by joshudson** [comment]
Confirmed. But I don't think the workaround works.

**Comment by danmosemsft** [comment]
@joshudson FWIW it did for me. I guess if it doesn't, then use `/p:CoreCLROverridePath=d:\git\coreclr\bin\Product\Windows_NT.x64.Release\ ` when building from the root with build.

**Comment by joshudson** [comment]
CoreCLROverridePath is clearly what I needed thanks.

**Comment by ViktorHofer** [comment]
@ericstj I assigned you as this touches runtime.depproj mostly. I hope that's ok.

**Comment by ericstj** [comment]
I just tried reproducing this and it doesn't repro for me.  I did a `build` of corefx, a `build -release -skiptests` of coreclr and then did build of runtime.depproj specifying CLROverridePath.  It copied over the private CoreCLR and didn't delete anything.  I'm guessing we're missing something in repro steps.  @danmosemsft or anyone else who hits this, please share a binlog (/bl) from the build of the runtime.depproj and I can have a look.

This could be an issue with using an old SDK.  The SDK used to do some tricks where it would delete host assets we reference https://github.com/dotnet/corefx/issues/34455#issuecomment-452933079

If you do hit this, another thing to try would be to see if it repros if you use the latest SDK, or the local SDK from the .dotnet folder.
