### ISSUE TITLE
 add additional library gss-ntlmssp in .netcore 2.1

### ISSUE THREAD

**Issue by stevenruizhang** [dotnet/corefx#38157]
I create one .net core 2.1 project and can run will in my local windows os. But when i follow the AWS toolkit for VS tool to push that in AWS lambda it will throw below issue. I check this is regarding NTLM auth does not work by default on Unix issue, so any library can resolve that issue and include in .net core project directly , i try gss-ntlmssp but it must be run in pt-get -y install and hard to run that in Lambda, i need native .net library then i can package that in project with .zip file and upload to aws lambda
![aws issue](https://user-images.githubusercontent.com/13114985/58788259-1ae70780-861e-11e9-92c5-b697c93957f0.jpg)

**Comment by davidsh** [comment]
.NET Core requires Linux machines to have the gss-ntlmssp package installed on the Linux machine in order for NTLM authentication to work.  .NET Core does not bundle Linux packages with its setup.  It is assumed that Linux machines will have the proper setup before .NET Core is installed and used.

AWS lambda Linux VMs probably don't have the required package installed on their VMs.  I am not sure how you can customize AWS lambda Linux VMs for that.

**Comment by wfurt** [comment]
you can probably grab binary from any close enough distribution or build it your self from sources @stevenruizhang. However the library is not used directly by .Net but rather by Kerberos and GSSAPI .Net depends on. Figuring out how to customize particular Linux distribution or environment is beyond  corefx.
