### ISSUE TITLE
Issue with upaired surrogate conversion to utf16

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/corefx#38178]
Destination too small for unpaired surrogate when converting to utf16

Two tests marked as active issue. More details here: 
https://github.com/dotnet/corefx/pull/37911#issuecomment-497963969

**Comment by MarcoRossignoli** [comment]
@maryamariyan should tests fail?I removed `[ActiveIssue(38178)]` but works on my local win.

**Comment by MarcoRossignoli** [comment]
@ahsonkhan seems ok now https://github.com/dotnet/corefx/pull/38411
