### ISSUE TITLE
HtmlEncoder.Encode overload does not correctly handle multi-character icons

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/corefx#38184]
The following test fails against a preview6 nightly:

```C#
[Fact]
public void Emoji()
{
    // Arrange & Act
    using (var stringWriter = new StringWriter())
    {
        HtmlEncoder.Default.Encode(stringWriter, "😂2");
        var encoded = stringWriter.ToString();
        Assert.Equal("&#x1F602;2", encoded);
    }
}
```
The "2" directly after the emoji gets truncated. If you add a second '2' after the first, it succeeds. Also of note is that the `Encode(string value)` overload does NOT seem to suffer from this problem.

I would assume that this would be true of other emojis and/or high unicode characters.

Originally reported in https://github.com/aspnet/AspNetCore/issues/10573.

Seems to share some similarities with https://github.com/dotnet/corefx/issues/33276.

**Comment by AbhiAgarwal192** [comment]
Submitted a PR for this. This will get fixed in the next release.

**Comment by GrabYourPitchforks** [comment]
I believe this was fixed in https://github.com/dotnet/corefx/pull/38328. If this is incorrect, please reopen this issue.
