### ISSUE TITLE
.Net Core 2.0 not able to post xml content to WCF service

### ISSUE THREAD

**Issue by mananchoksi007** [dotnet/corefx#38181]
Receives Below Error

**<?xml version="1.0" encoding="UTF-8"?><errorResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IndentifierServicexml.xsd"><returnResults><returnCode>0202</returnCode><returnMessage>Unable to unmarshal XML stream.  Please verify and resubmit.::Premature end of file.</returnMessage><returnCodeDetail>Invalid input</returnCodeDetail></returnResults></errorResponse>**

Its successfully working with .Net Framework. Is there different way to post the xml content then .Net framwork soap service call.

**Comment by StephenBonikowsky** [comment]
@karelz 
This issue belongs to WCF, I moved it from the WCF repo since the fix is over here and added the Serialization label.
We are actively working on it and should have it fixed in the 3.0 time frame, probably for Preview7.
Should we add it to the 3.0 milestone?

**Comment by karelz** [comment]
If it is critical for 3.0, then yes, set the milestone to 3.0.

**Comment by stephentoub** [comment]
Fixed by #38246
