### ISSUE TITLE
Perf: Console Color setting 5x slower on Linux

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#3818]
| test name                                        |  Windows time |  Linux time |  linux/windows | 
|--------------------------------------------------|------------|---------------|-------------|----------------| 
| Perf_Console.ForegroundColor | 11.91903744   | 49.60640001 | 4.161946822    | 
| Perf_Console.BackgroundColor | 12.05075527   | 62.62819999 | 5.197035257    | 

Perf Test (same for ForegroundColor):
```
[Benchmark]
public void BackgroundColor()
{
    const int innerIterations = 1000;
    foreach (var iteration in Benchmark.Iterations)
    {
        using (iteration.StartMeasurement())
        {
            for (int i = 0; i < innerIterations; i++)
            {
                Console.BackgroundColor = ConsoleColor.Black; Console.BackgroundColor = ConsoleColor.Blue;
                Console.BackgroundColor = ConsoleColor.Cyan; Console.BackgroundColor = ConsoleColor.DarkBlue;
                Console.BackgroundColor = ConsoleColor.DarkGray; Console.BackgroundColor = ConsoleColor.Red;
                Console.BackgroundColor = ConsoleColor.DarkGreen; Console.BackgroundColor = ConsoleColor.White;
            }
        }
    }
    Console.ResetColor();
}
```
Can post individual iteration results if desired.

**Comment by stephentoub** [comment]
@ianhays, I'm getting very different results for this test, with the Linux version being an order of magnitude faster than the Windows version, and when output is redirected, two orders of magnitude faster.  We should understand why my results are so skewed from yours.

**Comment by ianhays** [comment]
Confirmed; Console App results are as you mentioned:

Linux Redirected (fraction of a ms):
```
00:00:00.0001740
00:00:00.0001853
00:00:00.0001740
00:00:00.0001740
00:00:00.0001740
00:00:00.0001894
00:00:00.0002102
```

Linux not redirected: (~40 ms)
```
00:00:00.0367006
00:00:00.0569756
00:00:00.0592777
00:00:00.0533425
00:00:00.0435211
00:00:00.0371486
```

WindowsCore not redirected (~170 ms)
```
00:00:00.2648846
00:00:00.2101040
00:00:00.1826109
00:00:00.1768447
00:00:00.1756065
00:00:00.1685927
```

It would appear that in this case it is my WindowsCore results that are skewed. I figured there was probably a problem with the way I was running my tests somehow, and there was. I was redirecting output from building/running the tests to determine if there were any build failures (___ exited with code 1), and if there are then I retry the build. This was causing the Console color change to be redirected and therefore significantly faster than it should have been. I'll just need to change my scripts a bit to avoid this quirk in the future.

Closing this issue and going to rerun my other Console tests also.

**Comment by ianhays** [comment]
Actually, this might be an issue with running through msbuild in general rather than an issue with redirecting msbuild output. Even without the redirects I'm getting similar results where Windows is ~12 ms when it should be ~170. Running them through corerun still gets good results.
