### ISSUE TITLE
I have a problem with DataFlow

### ISSUE THREAD

**Issue by bluetianx** [dotnet/corefx#38194]
# Problem describe:
my dataflow  not work after  a while, The whole dataflow is blocked when the block of fileExtract  donot handle any message. I try stop the dataflow by calling Complete() of startNode, I find that
Completion.Status of node of SaveFileToDB is WaitingForActivation. 
        I donot know why , the Completion.Status of node of SaveFileToDB should is Faulted  ,if the node of fileExtract has a unhandle exception. I donot know that how to troubleshoot the bug.
       if you donot understand my mean,please tell me ,I will try.
# Addtional info
OS: windows server 2016 with 16 core  64g RAM
I run my datafolw by hosting on windows server
nuget package:System.Threading.Tasks.Dataflow  v4.9.0
Net framework : 4.6.1
# Notable
 the block of fileExtract  is CPU-bound
the block of GetFileStream is IO-bound

My dataflow design is as follows:
![未命名文件 (1)](https://user-images.githubusercontent.com/29353661/58855386-88ed0680-86d2-11e9-9ba0-9e8dfd6a76ac.png)

**Comment by svick** [comment]
It's hard to tell without seeing your code, but it sounds like the action of the `fileExtract` block is stuck. Is that possible?

In that situation, completion would not propagate to `SaveFileToDB`, because `fileExtract` can't complete, which happens because it's still processing a message.

**Comment by bluetianx** [comment]
there is not loop in ```fileExtract ``` block, The code as follows:
``` C#

public static FileTransportModel HandleCntFile(FileTransportModel fileTransport)
        {
            Stopwatch stopwatch = new Stopwatch();
            stopwatch.Start();
            try
            {
                Service1.NLogger.Debug($"receiveMessage-{fileTransport.FileId}");
                if (fileTransport.HasError || fileTransport.FileContentBytes==null || fileTransport.FileContentBytes.Length==0)
                {
                    Service1.NLogger.Debug($"extractFinish-{fileTransport.FileId}");
                    stopwatch.Stop();
                    fileTransport.T4 = stopwatch.ElapsedMilliseconds;
                    return fileTransport;
                }

                string[] plaintextArra = new string[] { "txt", "xml", "js", "html" };

                if (plaintextArra.Contains(fileTransport.FileExtension))
                {
                    //fileTransport.FileContent = Encoding.Default.GetString(fileTransport.FileContentBytes);
                }
                else
                {
                    TextExtractor textExtractor = new TextExtractor();
                    
                    fileTransport.FileContentBytes = Encoding.UTF8.GetBytes(textExtractor.Extract(fileTransport.FileContentBytes).Text.Replace("\r\n", ""));
                }
                

            }
            catch (Exception ex)
            {
                Service1.NLogger.Error(ex);
                fileTransport.HasError = true;
                fileTransport.Exceptions.Add(ex);
            }
            Service1.NLogger.Debug($"extractFinish-{fileTransport.FileId}");
            stopwatch.Stop();
            fileTransport.T4 = stopwatch.ElapsedMilliseconds;
            return fileTransport;
        }

```

Nlog maybe caused deadlock , Nlog in my code  is a static variable,which only is instanced once.the code as follow ：
``` C#
public partial class Service1 : ServiceBase
    {
        private FileExtractDataFlow _fileExtractDataFlow;

        public static Logger NLogger = LogManager.GetLogger("DefaultLog");
  //something code 
}
```

PS: my vesion of nlog is 4.6.3

**Comment by bluetianx** [comment]
I  log  by useing Nlog every block，I think nlog is thread safe ，do I wrong ？

**Comment by svick** [comment]
What happens when you run your inside a debugger and inspect call stacks of threads when you reach the problematic state? Does any of the stacks include `HandleCntFile`? If it does, look at the bottom of that stack, that's where you'll probably find the problem.

**Comment by bluetianx** [comment]
ok ， I will do it when the problem happens again. I'll let you know if there are any new developments

**Comment by tarekgh** [comment]
@bluetianx I am going to close the issue, but when you hit the problem again and have more info, reply back here and we'll reopen the issue. Thanks.

**Comment by bluetianx** [comment]
I dose not find deadlock after I have analyzed dump of the app, 
![TIM截图20190611090950](https://user-images.githubusercontent.com/29353661/59259418-5f9d1f00-8c6c-11e9-95f6-02b06a7db194.png)
![TIM截图20190611091007](https://user-images.githubusercontent.com/29353661/59259447-6af04a80-8c6c-11e9-9ca0-16ea42b1636d.png)
![TIM截图20190611091021](https://user-images.githubusercontent.com/29353661/59259454-6e83d180-8c6c-11e9-86dd-3b57ced0c1c3.png)

# Notable
This is my first encounter with dump, Let me know if I'm doing something wrong,Thank you
