### ISSUE TITLE
SslStream does not call BeginRead or ReadAsync of InnerStream in .NET Core 2.1 and newer

### ISSUE THREAD

**Issue by afterlogic-support** [dotnet/corefx#38198]
I found that SslStream in .NET Core 2.1/2.2/3.0 does not call BeginRead or ReadAsync of InnerStream when SslStream's BeginRead or ReadAsync are called.

Discussion at https://stackoverflow.com/questions/56431957/sslstream-does-not-call-beginread-or-readasync-of-innerstream-in-net-core-2-1 suggests this is because starting from .NET Core 2.1 the "core" APIs are no longer the byte-array ones; they'd be the Span ones.

It's also been said that NetworkStream has special code to preserve backwards compatibility with derived classes for the synchronous case, but not the asynchronous case.

The code below makes a connection to SMTP server smtp-mail.outlook.com at port 587 and then switches the connection to TLS with a STARTTLS command. MyStream is a wrapper around NetworkStream which I pass to SslStream.

usings:

```c#
	using System.Threading;
	using System.Threading.Tasks;
	using System.IO;
	using System.Net.Sockets;
	using System.Net.Security;
	using System.Text;
```

MyStream class:

```c#
	public class MyStream : NetworkStream
	{
		public MyStream(TcpClient tc) : base(tc.Client)
		{
		}

		public override int Read(byte[] buffer, int offset, int count)
		{
			int bytesRead = 0;

			try
			{
				bytesRead = base.Read(buffer, offset, count);
			}
			finally
			{
			}
			return bytesRead;
		}

		public override void Write(byte[] buffer, int offset, int count)
		{
			try
			{
				base.Write(buffer, offset, count);
			}
			finally
			{
			}
		}

		public override void WriteByte(byte value)
		{
			try
			{
				base.WriteByte(value);
			}
			finally
			{
			}
		}

		public override IAsyncResult BeginRead(byte[] buffer, int offset, int size, AsyncCallback callback, object state)
		{
			try
			{
				return base.BeginRead(buffer, offset, size, callback, state);
			}
			finally
			{
			}
		}

		public override int EndRead(IAsyncResult asyncResult)
		{
			int bytesRead = 0;

			try
			{
				bytesRead = base.EndRead(asyncResult);
			}
			finally
			{
			}
			return bytesRead;
		}

		public override IAsyncResult BeginWrite(byte[] buffer, int offset, int size, AsyncCallback callback, object state)
		{

			try
			{
				return base.BeginWrite(buffer, offset, size, callback, state);
			}
			finally
			{
			}
		}

		public override void EndWrite(IAsyncResult asyncResult)
		{
			try
			{
				base.EndWrite(asyncResult);
			}
			finally
			{
			}
		}

		public override Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
		{
			return Task.Factory.FromAsync<int>(BeginRead(buffer, offset, count, null, null), EndRead);
		}

		public override Task WriteAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
		{
			return Task.Factory.FromAsync(BeginWrite(buffer, offset, count, null, null), EndWrite);
		}
	}
```

Main method:
```c#
	public async static Task Main(string[] args)
	{
		TcpClient tc = new TcpClient();
		await tc.ConnectAsync("smtp-mail.outlook.com", 587);
		MyStream ms = new MyStream(tc);
		byte[] response = new byte[64*1024];
		int n;
		string command;
		byte[] request;
		n = await ms.ReadAsync(response, 0, response.Length);
		command = "EHLO domain\r\n";
		request = Encoding.ASCII.GetBytes(command);
		await ms.WriteAsync(request, 0, request.Length);
		n = await ms.ReadAsync(response, 0, response.Length);
		Console.WriteLine(Encoding.ASCII.GetString(response, 0, n));
		command = "STARTTLS\r\n";
		request = Encoding.ASCII.GetBytes(command);
		await ms.WriteAsync(request, 0, request.Length);
		n = await ms.ReadAsync(response, 0, response.Length);
		Console.WriteLine(Encoding.ASCII.GetString(response, 0, n));
		SslStream ssl = new SslStream(ms);
		await ssl.AuthenticateAsClientAsync("smtp-mail.outlook.com");
		command = "RSET\r\n";
		request = Encoding.ASCII.GetBytes(command);
		await ssl.WriteAsync(request, 0, request.Length);
		n = await ssl.ReadAsync(response, 0, response.Length);
		Console.WriteLine(Encoding.ASCII.GetString(response, 0, n));
		command = "QUIT\r\n";
		request = Encoding.ASCII.GetBytes(command);
		await ssl.WriteAsync(request, 0, request.Length);
		n = await ssl.ReadAsync(response, 0, response.Length);
		Console.WriteLine(Encoding.ASCII.GetString(response, 0, n));
		ssl.Dispose();
		tc.Close();
	}
```

In .NET Core 2.1+, MyStream.BeginRead, MyStream.EndRead and MyStream.ReadAsync will not be called after ssl.AuthenticateAsClientAsync line.

In .NET Core 2.0 and .NET Framework, they are called as they should be.

**Comment by davidsh** [comment]
@stephentoub

**Comment by stephentoub** [comment]
When we add new virtual methods to a type like Stream, we often want to take an optimized path in those methods but may not be able to if some other method on the type could have been overridden, in which case for compat reasons we want to prefer to call that other method.  That's the case with the Read/Write{Async} span-based and memory-based overloads on Stream that were added in .NET Core 2.1.  However, we appear to have missed adding those checks into NetworkStream.Read/WriteAsync.  As a result, those methods always just call to the underlying Socket unless you've overridden those specific methods.

In theory we could add those checks into NetworkStream now, but that could also introduce a compat problem, and it's not clear that the problem it solves is any better than the problem it introduces.  So we may not want to change anything.

As for the impact on your example, you have a few options:
1. Override the relevant Read/Write{Async} methods.
2. Wrap your stream around NetworkStream rather than deriving from it.

**Comment by afterlogic-support** [comment]
Thank you for reply. Yeah, I already implemented option 2, seems to work well. I cannot use option 1 because my dll must support both .net core 2.0 and .net core 2.1 while the option 1 obviously won't work in 2.0 (Span is not there yet).

**Comment by karelz** [comment]
This should be part of making asyn/await first-class in SslStream.

**Comment by wfurt** [comment]
This is not related to SslStream @karelz, see comments from @stephentoub. 
Since there is compat risk and have only @afterlogic-support hitting this so far and since there is a workaround I suggest we close this.

**Comment by karelz** [comment]
Agreed, closing.
