### ISSUE TITLE
Add ctor to HashSet<T> that allows the initial capacity to be specified

### ISSUE THREAD

**Issue by mattwarren** [dotnet/corefx#382]
Unlike most other collections within the `System.Collections` namespace, `HashSet<T>` doesn't have a [constructor overload](http://msdn.microsoft.com/en-us/library/bb354549(v=vs.110).aspx) that allows you to pass in the expected capacity. It will only let you pass in an [`IEnumerable<T> collection`](http://referencesource.microsoft.com/#System.Core/System/Collections/Generic/HashSet.cs,116) of items to pre-populate it with.

Having this would enable the use case where you know how many items will be added to the `HashSet<T>` (or at least an upper bound), but don't have them all up front, i.e. they are to be added over time. 

It would therefore let pre-size the `HashSet<T>` so that it doesn't have to grow over time, with all the associated copying that is needed. This pattern is exposed by other collections, for instance [`List<T>`](http://msdn.microsoft.com/en-us/library/dw8e0z9z(v=vs.110).aspx), to cover this scenario.

There's already a private [`Initialize` method](http://referencesource.microsoft.com/#System.Core/System/Collections/Generic/HashSet.cs,831ca3e6d9c0d78b) that will do the work, so unless I'm missing something, it's just a case of calling this.

Is this something that is worth adding?

**Comment by mikedn** [comment]
I'd very much like to see this added too. It is useful to avoid resizing in cases where a reasonable approximation of the final count is known, especially for hashtables where resizing is more expensive than for lists.

**Comment by KrzysztofCwalina** [comment]
I think it's a good suggestion.

**Comment by mattwarren** [comment]
Cool, glad people agree. BTW I'm more than happy to do the pull-request for the actual work if that's possible?

**Comment by Petermarcu** [comment]
@mattwarren,Please do. We'd love to have you contribute!

**Comment by mattwarren** [comment]
Cool, I guess I have to wait until `System.Collection` is open-sourced though, or have I missed that announcement?

**Comment by terrajobst** [comment]
That's correct. I'll mark this issue as "Accepting PRs". If you want to call dips, say so here :-)

**Comment by mattwarren** [comment]
Yeah I'd love to call dibs on this one ;-) I'll put together a PR when it's open-sourced.

**Comment by terrajobst** [comment]
[We've reviewed this proposal](https://github.com/dotnet/apireviews/blob/master/2015-01-14-misc/README.md#382-add-constructor-to-hashsett-that-allows-the-initial-capacity-to-be-specified) and think it would be a great addition. Please go ahead!

**Comment by thomaslevesque** [comment]
Since we're talking about the `HashSet<T>` constructor, see this related issue: #498

**Comment by mattwarren** [comment]
Just a quick question, will I need to submit a CLA before I can send a PR for this?

**Comment by mikedn** [comment]
You can submit a PR at any time, the CLA bot will tell you that you have to sign the CLA in the PR.

**Comment by StanRozenberg** [comment]
@mattwarren Are you still moving forward with this PR, if not I then I can do it.

**Comment by thomaslevesque** [comment]
@StanRozenberg , the source for `HashSet<T>` hasn't been published on GitHub yet... it won't be possible to implement this feature until then.

**Comment by StanRozenberg** [comment]
@thomaslevesque ah I didn't notice,  thanks!

**Comment by mattwarren** [comment]
@StanRozenberg I'm just waiting for the code to be open-sourced, as @thomaslevesque pointed out it's not done yet, see https://github.com/dotnet/corefx/issues/966.

I plan to implement that change after that.

**Comment by dotnetchris** [comment]
+1

**Comment by benjamin-bader** [comment]
@mattwarren Looks like HashSet and friends have landed - I'm looking forward to seeing this land, too!

**Comment by whoisj** [comment]
:+1: @mattwarren I'd come here to suggest the same thing, fortunately you beat me to it by months and now it looks like it'll get adopted!

**Comment by stephentoub** [comment]
@mattwarren, the HashSet code is available in the repo now:
https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/HashSet.cs
I believe the change should be done against the future branch.

**Comment by MarkusSintonen** [comment]
I made a pull request for solution to the issue. Pull request is in the future branch as @svick already referenced.

**Comment by stephentoub** [comment]
Fixed by #2862 (in future branch). Thanks, @MarkusSintonen.
