### ISSUE TITLE
DirectoryInfo.Parent.ToString() returns absolute not relative path (unlike Desktop)

### ISSUE THREAD

**Issue by rjmholt** [dotnet/corefx#38215]
From https://github.com/PowerShell/PowerShell/issues/9800.

Identical to https://github.com/dotnet/corefx/issues/2632 (but that was resolved by https://github.com/dotnet/corefx/pull/5437).

If you've got PowerShell on your machine, try:

```powershell
[System.IO.DirectoryInfo]::new($PWD).Parent.ToString()
```

In PowerShell Core 6.2 (.NET Core 2.1) and 7 (.NET Core 3.0-preview5) this returns an absolute path, but in Windows PowerShell (.NET Framework) it's relative.

Here's a simple reproduction in C#:

```csharp
class Program
{
        static void Main(string[] args)
        {
            Console.WriteLine(new DirectoryInfo(Environment.CurrentDirectory).Parent.ToString());
        }
}
```

```
> dotnet run -f netcoreapp3.0
C:\Users\me\Documents\Dev\sandbox

> dotnet run -f netcoreapp2.1
C:\Users\me\Documents\Dev\sandbox

> dotnet run -f net48
sandbox
```

**Comment by stephentoub** [comment]
cc: @JeremyKuhne

**Comment by JeremyKuhne** [comment]
I don't think we should change this to match desktop as this turns a passed-in fully qualified path into a relative path (which is more risky from a security standpoint).

Using `.Name` will give you consistent behavior and is explicit about intent.

We should add some tests to document this change in behavior.

**Comment by carlossanlop** [comment]
@JeremyKuhne additionally, I suggest we also update [the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.io.directoryinfo.parent?view=netcore-3.0) (a remark maybe?) to clarify that Parent will return a full path in netcore and a relative path in framework. If you agree, I'll open an issue in dotnet/dotnet-api-docs and assign it to both of us.

**Comment by rjmholt** [comment]
That would be helpful to us.

PowerShell doesn't depend on this directly, but exposes the API and coercing any object to a string defaults to `ToString()`. So usages involving `DirectoryInfo` being used as a path string (like `Get-Item ./here | Test-Path`) are all affected.

**Comment by JeremyKuhne** [comment]
> If you agree, I'll open an issue in dotnet/dotnet-api-docs and assign it to both of us.

We should also update `ToString()` (for `*Info`) to recommend using the `.Name` and `.FullName` properties instead.

**Comment by doctordns** [comment]
This should probably be noted as a breaking change for at least PowerShell 7. Scripts written using the Get-ChildItem cmdlet to use the returned DirectoryInfo objects can now break.

**Comment by carlossanlop** [comment]
Documentation clarification merged. Pending adding tests.
