### ISSUE TITLE
PDB files are locked and can't be deleted/renamed once loaded

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#38212]
We've been getting reports of locked pdb files (https://github.com/aspnet/AspNetCore/issues/3269) when deploying ASP.NET Core applications (but not locked dlls) and we assumed that it was application insights locking the pdb. Turns out, the runtime opens pdb files (once somebody accesses something like Exception.StackTrace) it can't be renamed/deleted until the process ends. This interrupts the deployment process on azure app service. It turns out we need to pass the right FileShare permissions when opening the file pdb file.

Here's a simple repro:

```C#
using System;
using System.IO;

namespace ConsoleApp52
{
    class Program
    {
        static void Main(string[] args)
        {
            var pdbFile = Path.ChangeExtension(typeof(Program).Assembly.Location, ".pdb");
            var assemblyFile = typeof(Program).Assembly.Location;

            try
            {
                throw new Exception();
            }
            catch (Exception e)
            {
                // This forces the PDB to be read
                Console.WriteLine(e.StackTrace);
            }

            File.Move(assemblyFile, Path.ChangeExtension(assemblyFile, ".dll.delete"));
            // This line fails
            File.Move(pdbFile, Path.ChangeExtension(assemblyFile, ".pdb.delete"));

            Console.ReadKey();
        }
    }
}
```

I think this fix should be ported down level as well.

**Comment by stephentoub** [comment]
Did you mean to open this in coreclr?

**Comment by davidfowl** [comment]
The source is in corefx and it seems to be dynamically loaded by coreclr. 

https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.StackTrace/src/System/Diagnostics/StackTraceSymbols.CoreCLR.cs#L14

https://github.com/dotnet/coreclr/blob/9773db1e7b1acb3ec75c9cc0e36bd62dcbacd6d5/src/System.Private.CoreLib/src/System/Diagnostics/StackFrameHelper.cs#L111

**Comment by stephentoub** [comment]
Right, so System.Reflection.Metadata (which is used by System.Diagnostics.StackTrace). Ok.

cc: @tmat, @mikem8361

**Comment by stephentoub** [comment]
(I see now it is actually directly using File.  Thanks.)

**Comment by mikem8361** [comment]
This is probably the MetadataReaderProvider caching in  corefx's StackTraceSymbols.CoreCLR.cs.  We do a File.OpenRead on the pdb path.

The caching is necessary because there is a lot libraries that use System.Diagnostics.StackTrace in their logging to get source/line info on stack frames.

/cc: @noahfalk
