### ISSUE TITLE
Add some HttpClientMiniStressTest coverage for HTTP/2

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#38229]
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/tests/FunctionalTests/HttpClientMiniStressTest.cs

**Comment by karelz** [comment]
@stephentoub any update on this one? Will you have time to fix it for ZBB on 7/1? Thanks!

**Comment by stephentoub** [comment]
I put up a PR.
