### ISSUE TITLE
[System.Text.Json] JsonExtensionData should allow non-JsonElement types during serialization

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#38238]
Consider the model

```C#
public class TestModel
{
    public string Name { get; set; } = "Test"

    public Dictionary<string, object> Extensions { get; set; } = new Dictionary<string, object>()
    {
       ["foo"] = 1,
     }
}
```

This serializes correctly. If I annotate the `Extensions` property with `JsonExtensionDataAttribute`, serialization fails with:

`The data extension property 'WebApplication1.Test2Controller+TestModel.Extensions' cannot contain dictionary values of type 'System.Int32'. Dictionary values must be of type JsonElement.`

It's not entirely clear why serialization requires the type be an instance of `JsonElement`. Additionally, it's not particularly trivial to produce `JsonElement` instances to put inside a dictionary.

Could this constraint be removed so that it's treated the same as a regular dictionary for the purposes of serialization?

**Comment by pranavkm** [comment]
Note that in the one use case that MVC uses this feature, it stores arbitrary content (strings or numbers) in the `JsonExtensionData` backed dictionary.

**Comment by pranavkm** [comment]
cc @steveharter

**Comment by MarcoRossignoli** [comment]
Guys I'm working on this if you can take a look at https://github.com/dotnet/corefx/pull/38262 and let me know what you think I could bring it to the end.

**Comment by steveharter** [comment]
The request is only for polymorphic serialize, which for round-tripping on subsequent deserialize will create JsonElement.

This means the values should always be JsonElement, and we shouldn't try to convert to int, string, etc. 

cc @MarcoRossignoli
