### ISSUE TITLE
How can I create a DNX to use with dnvm?

### ISSUE THREAD

**Issue by TheNinjaCat** [dotnet/corefx#3823]
Hello,

I have compiled CoreFX following the instructions at: 

https://github.com/dotnet/corefx/blob/master/Documentation/building/windows-instructions.md

And I have created the Hello World app following the instructions at:

http://dotnet.readthedocs.org/en/latest/getting-started/installing-core-windows.html

However, the instructions does not cover how to create and install a custom DNX. Is there any documentation about it?

**Comment by joshfree** [comment]
I believe this issue is being tracked here https://github.com/dotnet/corefx/issues/3656

**Comment by stephentoub** [comment]
Closing as a dup of #3656 (and because DNX doesn't exist as of rc2).
