### ISSUE TITLE
Add Ptr<T>, type safe IntPtr wrapper for marshaling

### ISSUE THREAD

**Issue by cromachina** [dotnet/corefx#38243]
Typically wrapping native libraries that produce (own) and consume native pointers is done with System.IntPtr. It seems like a better way to match a native interface is to wrap IntPtr in another structure to give it a unique type, `Ptr<T>`. This would be similar to the idea of `SafeHandle` but unmanaged and not for just Windows Handle types. `OpaquePtr<T>` may represent a pointer of unknown implementation (such as a C header only declaring `struct Bar;`), in which case it does not make sense to provide a Read/Write interface, but still have it be distinguishable from other pointers.

Possible simple implementation and example usage:
```csharp
using System;
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Sequential)]
public struct Ptr<T> where T : struct
{
    public IntPtr ptr;
    
    public T Read()
    {
        return Marshal.PtrToStructure<T>(ptr);
    }
    
    public void Write(T t)
    {
        Marshal.StructureToPtr(t, ptr, false);
    }
}

[StructLayout(LayoutKind.Sequential)]
public struct OpaquePtr<T> where T : struct
{
    public IntPtr ptr;
}

[StructLayout(LayoutKind.Sequential)]
public struct Foo
{
    public double bar;
}

[StructLayout(LayoutKind.Sequential)]
public struct Bar
{}

public class Bindings
{
    private const string blahLib = "blah.so";
    
    [DllImport(blahLib)]
    public static extern Ptr<Foo> createFoo();
    
    [DllImport(blahLib)]
    public static extern void destroyFoo(Ptr<Foo> foo);
    
    [DllImport(blahLib)]
    public static extern void makeFoo(out Ptr<Foo> foo);

    public static void Main()
    {
        Ptr<Foo> f;
        makeFoo(out f);
        
        Ptr<Foo> g = createFoo();

        Foo h = f.Read();
        h.bar = 1.0;
        g.Write(h);
        
        // Compiler error.
        // Ptr<Bar> b;
        // destroyFoo(b);
        
        destroyFoo(f);
        destroyFoo(g);
    }
}
```

**Comment by jkotas** [comment]
`Ptr<T>` that you are proposing is equivalent to `T*` (C# unmanaged pointers).

Why are not C# unmanaged pointers sufficient for what you are trying to do?

**Comment by cromachina** [comment]
Then you are forced with the `unsafe` constraint, no?

**Comment by jkotas** [comment]
Yes, unmanaged pointers do require `unsafe`.

`Ptr<T>` that you are proposing is exactly as unsafe as `T*`. It is not desirable that it is masking the unsafe, without guaranteeing any kind of safety. We are trying hard to avoid adding APIs to the platform that are unsafe in practice, but pretend to be nice safe on the surface.

**Comment by cromachina** [comment]
`IntPtr` is just as bad in that regard then, as it masks `intptr_t`, which is as ambiguous as `void *`. Curious as marshaling documentation often suggests the usage of IntPtr and not unsafe pointers.

**Comment by cromachina** [comment]
So you get type safety without the theater of `unsafe`, which you already circumvent with `IntPtr` and `DllImport` which do not require `unsafe` to use. Perhaps this is a flawed design?

**Comment by jkotas** [comment]
Yes, we wish some of the old APIs used actual pointers instead `IntPtr`, but we cannot go back in time to fix it.

**Comment by cromachina** [comment]
I see, well hopefully you guys can enter a deprecation cycle for the marshaling API and gradually force the usage of typed pointers. Thanks for responding so quickly!
