### ISSUE TITLE
ExtendedSocketException: nodename nor servname provided, or not known. 

### ISSUE THREAD

**Issue by PedroCavaleiro** [dotnet/corefx#38248]
Hi,

I'm trying to send a mail using MailKit from my WebAPI but keep getting this error
On .NETCore 3: 
ExtendedSocketException: nodename nor servname provided, or not known

And on .NetCore 2: 
Device Not Configured

This error is what made me test the .NET Core 3
This is my current system configuration

OS: macOS Mojave (10.14.5)
.NET Core (SDK): 3.0.100-preview5-011568
.NET Core (Runtime): 3.0.0-preview5-27626-15
Visual Studio for Mac: 8.1 Preview (8.1 build 2460)
Connected to the router by WiFi

**Comment by davidsh** [comment]
>ExtendedSocketException: nodename nor servname provided, or not known

We have seen this type of error before on MacOS.  It is some kind of DNS resolution problem.

**Comment by PedroCavaleiro** [comment]
> > ExtendedSocketException: nodename nor servname provided, or not known
> 
> We have seen this type of error before on MacOS. It is some kind of DNS resolution problem.

I've read that, but it happened on .NET Core 2.2 and apparently it still isn't fixed.

My Mac is properly configured and there are no problems in the internet I've already cleaned the DNS cache in case it was corrupted somehow but still the same.

**Comment by wfurt** [comment]
This is clearly DNS lookup failure. I was tracing something this while back and sometimes OS simply returns failure. I did not find any good way aside from retry how to fix it. You can try to use NameResolution directly and check what you getting.

**Comment by PedroCavaleiro** [comment]
Apparently the problem is fixed, don't know if it was an macOS update that fixed or an VS update but now it's working.

**Comment by galvesribeiro** [comment]
The problem still happen on OSX with .Net Core 3.1

**Comment by PedroCavaleiro** [comment]
> The problem still happen on OSX with .Net Core 3.1

I'm running the latest version of OSX and .NET Core (3.1) and I didn't run into problems
Have you tried to clear your DNS and test with another network?

**Comment by galvesribeiro** [comment]
It happens on my home network over wifi, over wire, at office, and even on Starbucks wifi...

**Comment by PedroCavaleiro** [comment]
Can you run this small program and tell me the output?
```
using System;
using System.Net;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
			Console.WriteLine(Dns.GetHostName());
			Console.WriteLine(Dns.GetHostEntryAsync(Dns.GetHostName()).GetAwaiter().GetResult().AddressList[0]);            
        }
    }
}
```

**Comment by galvesribeiro** [comment]
![image](https://user-images.githubusercontent.com/4714040/73126389-b3a50b80-3f90-11ea-89c2-d5d5a3da59a4.png)

`Dns.GetHostName()` return the right macbook name but `GetHostEntryAsync(hostname)` is what explodes...

**Comment by PedroCavaleiro** [comment]
I'm unable to replicate the problem...
Try editing your hosts file `/etc/hosts` and add `<your network ip> GUTO-MBP` or `127.0.0.1 GUTO-MBP`

**Comment by galvesribeiro** [comment]
Looks like it worked @PedroCavaleiro 

Thanks!
