### ISSUE TITLE
System.Runtime.Remoting Support 

### ISSUE THREAD

**Issue by shaggygi** [dotnet/corefx#38259]
I mistakenly [added to CoreClr repo](https://github.com/dotnet/coreclr/issues/24974), but closed and added here.

There has been many mentions of System.Runtime.Remoting APIs not being ported to .NET Core. I understand the reasoning, but want to understand a little more before continuing with other limited options.

I have an older API that depends on System.Runtime.Remoting. I was trying to port it to a .NET Core v3 library and use with a .NET Core console app. When it reaches the code that references Remoting code, I get the following error.

System.TypeLoadException: 'Could not load type 'System.Runtime.Remoting.Channels.IChannel' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.'

I also get the error when adding/running with the Windows Compatibility package. The code is intended to only run on Windows. I wanted to know if System.Runtime.Remoting should/will be able to run within a .NET Core project using the Windows Compatibility package and only on Windows? 

Any help is appreciated.

**Comment by danmosemsft** [comment]
@shaggygi no S.R.Remoting will not be available in.NET Core. It was explicitly cut because of technical compromises and fragility inherent in it. I recommend you look at other remoting technologies if you need this scenario on Core. Is this for cross process or cross machine?

**Comment by shaggygi** [comment]
@danmosemsft Thanks for reply and understood on why Remoting is not being moved forward.  I was more hoping we could at least use the Windows Compatibility package since we intend to run only on Windows.  We have an old 3rd-party API dependency that is built on Remoting and the vendor has confirmed they will not be updating to support .NET Core.  We are evaluating options for longer term strategy, but was hoping to get a solution to allow us to slowly begin transitioning pieces over time.

**Comment by danmosemsft** [comment]
@shaggygi the compat pack is pure library, and remoting is a major runtime feature (that we didn't bring forward) which is why it doesn't help you unfortunately. Thanks for the info.

I'll close this feel free to reopen if you have more questions.
