### ISSUE TITLE
SafeAccessTokenHandle is missing from .Net Core

### ISSUE THREAD

**Issue by Akaion** [dotnet/corefx#38285]
I've just noticed that you provide a SafeHandle [implementation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.win32.safehandles.safeaccesstokenhandle?view=netcore-2.2) for thread access tokens, however, this doesn't seem to be part of the Microsoft.Win32.SafeHandles namespace on .Net Core. 

Any insight into why this wasn't included?

**Comment by jkotas** [comment]
`SafeAccessTokenHandle` and other Windows-specific APIs for accessing security tokens is in a separate NuGet package: https://www.nuget.org/packages/System.Security.Principal.Windows

You can add it to your project by running `dotnet add package System.Security.Principal.Windows`
