### ISSUE TITLE
can not target .Net Core 3.0 in VS 2019 16.1.2

### ISSUE THREAD

**Issue by stevenruizhang** [dotnet/corefx#38297]
1) install the latest VS 2019 
![image](https://user-images.githubusercontent.com/13114985/59012041-0185cb80-8869-11e9-91ac-475b0ef367d9.png)
2) create console App , can not target to .net core 3.0 even sdk install 
![image](https://user-images.githubusercontent.com/13114985/59012083-25491180-8869-11e9-883c-e4ffcdd59062.png)
![image](https://user-images.githubusercontent.com/13114985/59012092-32fe9700-8869-11e9-8455-d4c85d831aad.png)
3) can not find the preview option in VS 2019
![image](https://user-images.githubusercontent.com/13114985/59012117-46a9fd80-8869-11e9-95af-dc9ef62fcfd5.png)

**Comment by svick** [comment]
The preview option is under Environment → Preview Features:

![](https://user-images.githubusercontent.com/287848/59018191-9676cd80-8845-11e9-9904-2321fa1f47fd.png)

**Comment by stevenruizhang** [comment]
The preview option is under Environment → Preview Features:
works well
