### ISSUE TITLE
No GetCustomAttributes for System.Type

### ISSUE THREAD

**Issue by MattMcCarthy** [dotnet/corefx#383]
With System.Type no longer being a sub class of MemberInfo, all of the GetCustomAttributes methods against class types have been lost on Core50.

**Comment by mikedn** [comment]
AFAIK you're supposed to use TypeInfo for that:

```C#
foreach (var attr in type.GetTypeInfo().GetCustomAttributes<FooAttribute>()) {...
```

**Comment by MattMcCarthy** [comment]
Awesome! Spent hours looking for that. :(
Thanks so much.
