### ISSUE TITLE
use a foreach with for if input foreach enumerable is an array

### ISSUE THREAD

**Issue by VGib** [dotnet/corefx#38302]
Hello,

i don't know if it has been done, since I use the .net Framework 4.5.

But i get big performance increase when dealing with calculating code with lot of arrays, which such a method (I just check  that the IEnumerable is IList, since this has been lot done in your Linq code)

```csharp
 public static void ForEach<T>(this IEnumerable<T> values, Action<T> doOnValue)
        {
            var valuesAsList = values as IList<T>;
            if (valuesAsList is null)
            {
                foreach (var value in values)
                {
                    doOnValue?.Invoke(value);
                }
            }
            else
            {
                for (int position = 0; position < valuesAsList.Count; position++)
                {
                    doOnValue?.Invoke(valuesAsList[position]);
                }
            }
        }
```

the foreach is a good way for code lisibility. And I have the advantage of for boost , with foreach lisibility.

Is it possible to do the same for:
```csharp
foreach (var value in myArray)
{
 // do some code
}
```

Why do you think ? 

Regards,

VGib

**Comment by Wraith2** [comment]
`T[]` is `ILIst<T>` so it is already done

**Comment by VGib** [comment]
OK thanks,

I'll wait that we migrate to .net core 2.2 (and then 3.0 when it's out)

**Comment by Wraith2** [comment]
This isn't a recent change, it's behaviour added with generics in the 2.0 desktop framework a decade ago. Casting to IList<T> will work with arrays because otherwise you have to special case them everywhere.

**Comment by VGib** [comment]
I think you didn't understand what i mean. I said foreach with array (and IList)  should not use enumerator, but for loop.

I know that array are IList and can be used with for loop.

This is an optimization. 

I reopen the issue, until you tell me that foreach behave like this.

**Comment by svick** [comment]
It sounds like you want to change the language, the right repo for that is dotnet/csharplang, maybe someone can move this issue there?

Also, there is already a very similar issue there: https://github.com/dotnet/csharplang/issues/1424. But note that that feature very likely wouldn't apply to `IList<T>`, because that would be a breaking change, and it has also been rejected.

**Comment by VGib** [comment]
Yes that's right.

But, I don't want to change the langage, only CLR implementation.

If there is a foreach with a IList, do as it is a for loop. (The langage syntax should be the same, only the compiler should be aware of it).
Howerver I don't master the drawbacks.

Can some one confirm me, that this is not a breaking change ?

**Comment by Wraith2** [comment]
It would be a language change. It would be a breaking change.

**Comment by danmosemsft** [comment]
@vgib I agree this should go in the csharplang repo. Can you please move there ? Thanks for opening it.

**Comment by VGib** [comment]
done [here](https://github.com/dotnet/csharplang/issues/2586)
