### ISSUE TITLE
.NET Core 2.2.5 Release notes and download links result in 404

### ISSUE THREAD

**Issue by Dargazo** [dotnet/corefx#38316]
For .NET Core release 2.2.5 (https://github.com/dotnet/core/releases/tag/v2.2.5 ) the "Release Notes" link points to:
https://github.com/dotnet/core/blob/master/release-notes/1.1/2.2.5/2.2.5.md (which 404s)
this should be (I'm assuming):
https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2.5/2.2.5.md

Similarly, the "Download and Install" link points to:
https://github.com/dotnet/core/blob/master/release-notes/1.1/2.2.5/2.2.5-download.md (which also 404s)
this should be (I'm assuming):
https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2.5/2.2.5-download.md

**Comment by danmosemsft** [comment]
@leecow ?

**Comment by leecow** [comment]
Sorry about that ... fixed.

**Comment by Dargazo** [comment]
It works now, thank you!
