### ISSUE TITLE
Console logs timestamps in local timezone instead of UTC

### ISSUE THREAD

**Issue by tomkerkhove** [dotnet/corefx#38329]
When configuring the Console logger to output timestamps as following:
```csharp
Host.CreateDefaultBuilder(args)
    .ConfigureAppConfiguration((hostingContext, config) =>
    {
        config.AddEnvironmentVariables();
    })
    .ConfigureLogging((hostBuilderContext, loggingBuilder) =>
    {
        loggingBuilder.AddConsole(consoleLoggerOptions => consoleLoggerOptions.TimestampFormat = "[HH:mm:ss]");
    })
    .ConfigureServices(services =>
    {
        services.AddHostedService<OrdersQueueProcessor>();
    });
```

The generated logged message uses my local timezone rather than UTC without an option to change this.

Would be good to be able to influence this and use UTC by default.

**Comment by gfoidl** [comment]
@tomkerkhove can you move this issue to https://github.com/aspnet/Extensions as it belongs to there?

(Close this one, open a new one over there and put the link to the new one here).

**Comment by danmosemsft** [comment]
I moved to https://github.com/aspnet/Extensions/issues/1808

**Comment by tomkerkhove** [comment]
Sorry for that @gfoidl 	and thanks @danmosemsft 	!
