### ISSUE TITLE
Test: Add the Cipher Related tests to verify cipher Algorithms not present in the enum.

### ISSUE THREAD

**Issue by shrutigarg** [dotnet/corefx#3832]
Add the Cipher Related tests to verify cipher Algorithms not present in the enum.

**Comment by vijaykota** [comment]
Tests are missing for Windows as well. So planning this additional coverage in RTM

**Comment by shrutigarg** [comment]
There is no API( or any parameter)  available to set the desired cipher in Windows which is used in Handshake. It internally picks up the cipher suite which is the strongest. So testing of all cipher Algorithms is not possible in Windows setup.
Though in Unix we can start an openssl server by providing the cipher suite to be accepted by the server
(i.e.  openssl s_server -debug  -msg  -cert ClientCert.pem -cipher <cipher to be tested> )
So client on any platform can be tested against an openssl server for the cipher suite variation.

We will have to look at the feasibility of such setup in CI

**Comment by vijaykota** [comment]
This can be revisited when the multi-machine CI setup strategy is finalized. There may be a way to reuse the test server of System.Net.Http.Functional.Tests once the budgeting for that is straightened out

**Comment by CIPop** [comment]
/cc @karelz 

Sounds like some tests are missing.

**Comment by karelz** [comment]
@CIPop can you scope it to just one area label please? We can split the bug into 2 if necessary.

**Comment by CIPop** [comment]
By mistake only: forgot to remove the original label.

**Comment by davidsh** [comment]
Not really needed at this point to invest in a large test effort. It would be better to simply react to any bugs in this area and add tests at that point.
