### ISSUE TITLE
OSX tests might not run in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#38332]
The SendToHelix step only takes ~5min and MC doesn't show tests run on that platform.

cc @stephentoub @safern @ericstj

**Comment by ViktorHofer** [comment]
Example: https://dnceng.visualstudio.com/public/_build/results?buildId=214735

**Comment by ViktorHofer** [comment]
Of course I could be wrong here but we should make sure that they indeed run.

**Comment by safern** [comment]
In the example you pointed out there is a test failure in OSX: https://dnceng.visualstudio.com/public/_build/results?buildId=214735&view=ms.vss-test-web.build-test-results-tab&runId=5263996&resultId=347262&paneView=debug

Could it have been timing or that MC errored when fetching the results?

**Comment by safern** [comment]
We could send a PR changing the HelixCommand when in OSX to something that would fail and see if everything is marked as failed?

**Comment by safern** [comment]
This other one also has results for OSX... https://dnceng.visualstudio.com/public/_build/results?buildId=215950&view=ms.vss-test-web.build-test-results-tab&runId=5296666&paneView=debug&resultId=130099

The example you provided has 2 attempts, could’ve been that MC got confused for the multiple attempts? I opened an issue that was closed by design a couple of days ago suggesting this behavior.

**Comment by ViktorHofer** [comment]
I don't think this has to anything to do with helix. Usually in every PR tests only run for five minutes. I suggest we should take a look at the infra logs to check if the test execution is triggered correctly. I hope I'm mistaken here.

**Comment by ViktorHofer** [comment]
OK I believe I'm just super paranoid. Infra logs show that tests are invoked correctly. Closing.

**Comment by safern** [comment]
That’s is what I’m trying to check by suggesting to send a PR with a WorkItemCommand instead of calling RunTests.sh — call something that fails like a non-existent .sh script. That will prove if they’re are running.
