### ISSUE TITLE
Unable to run System.Text.Encodings.Web.Tests locally

### ISSUE THREAD

**Issue by AbhiAgarwal192** [dotnet/corefx#38342]
When I try to run the test case project System.Text.Encodings.Web.Tests locally, i get an error message saying missing microsoft.net.test.sdk. 

Also three other sdks are missing like microsoft.sourcelink.vsts.git, microsoft.net.compilers.toolset and microsoft.sourcelink.github

**Comment by vcsjones** [comment]
Can you explain how you ran the tests (Command line, Visual Studio, etc)? I was able to run the tests properly through the command line.

Are you able to run other test projects successfully?

![image](https://user-images.githubusercontent.com/361677/59117560-0b1c3b80-891c-11e9-8c27-b317c0a84e39.png)

**Comment by AbhiAgarwal192** [comment]
Hi @vcsjones , I was trying to run through visual studio test explorer. Though i was able to run the test cases through command line.

**Comment by tarekgh** [comment]
@AbhiAgarwal192 did you build the repo before trying to run the tests? I mean from the command prompt, run build.cmd first.

**Comment by AbhiAgarwal192** [comment]
Yes i did that.

**Comment by vcsjones** [comment]
Does it work in Visual Studio now that you've got it running from the command line once? Which version of Visual Studio are you using?

**Comment by AbhiAgarwal192** [comment]
visual studio 2019 with the latest build. And even after the test cases passed from command line, i was unable to run it from visual studio.

**Comment by tarekgh** [comment]
I'll try that and will get back to you. Thanks.

**Comment by tarekgh** [comment]
I just tried it and worked fine. even the debug logs I got didn't have any reference to microsoft.net.test.sdk. 

did you load the solution https://github.com/dotnet/corefx/blob/master/src/System.Text.Encodings.Web/System.Text.Encodings.Web.sln first and then press F5 to run?

**Comment by krwq** [comment]
One other thing is to make sure to right click on the test project in solution explorer and "Set as startup project" and that you have previously did full build of corefx (presumably you did since tests run from the command line)

**Comment by tarekgh** [comment]
@krwq this is the default settings in the solution.

**Comment by tarekgh** [comment]
@AbhiAgarwal192 do you have any update here?

**Comment by AbhiAgarwal192** [comment]
Hi @krwq, If i set it up as startup project and run it using f5 i am able to run the test cases. But my concern was running it from the test explorer which is still not working for me.

**Comment by krwq** [comment]
@AbhiAgarwal192 this is a known issue: https://github.com/dotnet/corefx/issues/34314
I think everyone would like this to work but unfortunately it's a bit more complex to make that work with corefx vs other repos.

**Comment by AbhiAgarwal192** [comment]
@krwq Thank you!

**Comment by tarekgh** [comment]
closing this per discussion. @AbhiAgarwal192 thanks for the report and let's know if you still have any question.
