### ISSUE TITLE
.NET Core 3 and WPF library

### ISSUE THREAD

**Issue by davidhunter22** [dotnet/corefx#38355]
I just tried some existing WPF code using .NET Core 3.0 preview 5 and VS 16.2 Preview 1. I read the porting guide for WPF and it seems to only talk about apps not libraries. The main changes seem to be 
```
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
```
When I try 
```
    <OutputType>Library</OutputType>
    <UseWPF>true</UseWPF>
```
I get unresolved references for all the WPF related stuff. I did try WinLibrary but that is rejected. Does this only work for applications at present?

**Comment by wangfu91** [comment]
@davidhunter22  For libraries, you need change the ```Sdk``` to ```Microsoft.NET.Sdk.WindowsDesktop```, and add the ```<UseWPF>true</UseWPF>``` tag.
```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
</Project>
```

**Comment by davidhunter22** [comment]
Ah can't believe I didn't see the WindowsDesktop thing. That works great thanks.
