### ISSUE TITLE
Debug.Print(string) should behave the same as Debug.WriteLine(string)

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/corefx#38359]
In .NET Framework, Debug.Print(string) behaves the same as with Debug.WriteLine(string) not Debug.Write(string).

.NET Core needs to do the same. (This is an easy fix, just need to call WriteLine instead of Write in Debug class)
Refer to: https://github.com/dotnet/core/issues/2843
This issue was present since the initial port to .NET Core (locally tested against netcoreapp2.1 and netcoreapp3.0). 

NOTE:
Since the initial port to .NET Core there were a few discrepancies between the behavior of Framework vs Core for Debug APIs, we fixed most via https://github.com/dotnet/corefx/issues/32955.

Current issue states another one of those discrepancies.

**Comment by adamsitnik** [comment]
@maryamariyan can this issue be closed now after you have merged https://github.com/dotnet/coreclr/pull/25036?

**Comment by maryamariyan** [comment]
@adamsitnik System.Private.CoreLib hasn't been updated for corefx yet since my coreclr submission last week, it is open so it can track corefx tests that needs to be updated once corelib gets updated for corefx..

**Comment by stephentoub** [comment]
It was actually updated and I fixed the tests at the time.

**Comment by maryamariyan** [comment]
Thanks @stephentoub that slipped by me.
Here it is: https://github.com/dotnet/corefx/pull/38449
I was looking for that PR.

**Comment by wtgodbe** [comment]
Looks like this can be closed (@maryamariyan please re-open if I'm misinterpreting things)
