### ISSUE TITLE
JsonSerializer.Parse throws for UInt64 backed enum with value -1

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/corefx#38363]
parsing
`"{ \"MyByteEnum\" : -1, \"MyUInt32Enum\" : -1 }";` 
returns successfully but

`"{ \"MyByteEnum\" : -1, \"MyUInt32Enum\" : -1, \"MyUInt64Enum\" : -1 }";`
will throw

Below shows a comparison between JsonConvert.DeserializeObject and JsonSerializer.Parse for this case:

```c#
   string json = "{ \"MyByteEnum\" : -1, \"MyUInt32Enum\" : -1, \"MyUInt64Enum\" : -1 }";
   SimpleTestClass result = JsonConvert.DeserializeObject<SimpleTestClass>(json);
   Assert.Equal(SampleUInt64Enum.Max, result.MyUInt64Enum);

   // MyUInt64Enum throws with value -1
   Assert.Throws<JsonException>(() => JsonSerializer.Parse<SimpleTestClass>(json));
```

For more info, refer to @ahsonkhan 's comment here https://github.com/dotnet/corefx/pull/37895#discussion_r291792346

**Comment by ahsonkhan** [comment]
cc @steveharter, @JeremyKuhne

**Comment by MarcoRossignoli** [comment]
Found the issue if we have a negative ulong we don't fallback with any result https://github.com/dotnet/corefx/blob/c81cb6f165ae44c5885bb36ff89e4aa1cf1e504d/src/System.Text.Json/src/System/Text/Json/Serialization/Converters/JsonValueConverterEnum.cs#L42

Working on solution

**Comment by ahsonkhan** [comment]
> Found the issue if we have a negative ulong we don't fallback with any result

Yep. See https://github.com/dotnet/corefx/pull/37895#discussion_r291792346

The question is what **should** actually happen. I don't think we should allow out-of-bounds enum values. For example: It's one thing to say any int32 value is allowed in an int32-backed enum (even if the enum itself doesn't have it), it's another to say, things that don't even fit an int32, we will still allow (by overflowing around the int32 range). The same thing should apply to the other numeric types. I don't see a scenario where that is useful.

cc @JamesNK. @bartonjs

**Comment by vladd** [comment]
> The question is what **should** actually happen. I don't think we should allow out-of-bounds enum values.

**Comment by bartonjs** [comment]
> But then, shouldn't we throw on \"MyUInt32Enum\" : -1 as well?

Yep.

**Comment by MarcoRossignoli** [comment]
@bartonjs so no more support for `-1` = `MaxValue`?Can you confirm?

**Comment by bartonjs** [comment]
For an enum backed by UInt32?  The serializer can't write `-1` for that type, so why would the deserializer support reading it?

**Comment by MarcoRossignoli** [comment]
I'm with you...I would only know how to fix https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/tests/Serialization/EnumTests.cs#L107 
It will changes to `Parse_Negative1ForUInt64Enum_Throw`
