### ISSUE TITLE
Expression compiler - No support for TryFault and TryCatch with Filter

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#3838]
See CoreCLR https://github.com/dotnet/coreclr/issues/1764 for the underlying issue that causes this limitation. Note that this does work in the .NET Framework when emitting to a MethodBuilder that's not backed by a DynamicMethod.

We could either get the support for it in CoreCLR or consider an emulation strategy a la a try/catch/rethrow/finally with a Boolean flag to check whether an exception was observed.

**Comment by JonHanna** [comment]
The same thing is true of `BeginExceptFilterBlock()`.

**Comment by bartdesmet** [comment]
See https://github.com/dotnet/corefx/issues/5873 for the issue tracking this in `System.Reflection.Emit` now.

**Comment by VSadov** [comment]
I assume, once unblocked at least tests need to be added

**Comment by JonHanna** [comment]
We already have a good few appropriate tests, all marked as ActiveIssue, so they can be unblocked.
