### ISSUE TITLE
X509Certificate error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error

### ISSUE THREAD

**Issue by Kalyxt** [dotnet/corefx#38399]
Hello
I have signed .dll file using a sha1 algorithm. 
To verify if .dll file is signed by me I compare thumbprint of the certificate. 
Everything works just fine under windows but I couldn't find what might be wrong under linux-arm and linux-x64.

Here is the code:

`Dim theCertificate As New X509Certificate2
            Dim theSigner As New X509Certificate
            Try

                theSigner = New X509Certificate(u_FullPath)
               '--- Load certificate
                theCertificate = New X509Certificate2(theSigner)

                '--- Verify the thumbprint
                If CONST_FirmThumbPrint <> theCertificate.Thumbprint.ToString Then
                    '--- Invalid thumbprint
                    z_VerifyUpgradeDLLSignature = EXC.Get("Selected file isnt signed by...")
                    GoTo ExitFunction
                End If

            Catch ex1 As System.Security.Cryptography.CryptographicException

                GoTo ExitFunction

            Catch ex As Exception

                GoTo ExitFunction
            End Try`

Code stops at   theSigner = New X509Certificate(u_FullPath)

error message - Interop+Crypto+OpenSslCryptographicException: error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error   at Internal.Cryptography.Pal.CertificatePal.FromBio(SafeBioHandle bio, SafePasswordHandle password)   at Internal.Cryptography.Pal.CertificatePal.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)

I am using .NET Core 2.2 (2.2.203)
dotnet publish -c release -r linux-arm -o

**Comment by bartonjs** [comment]
Using X509Certificate2 to see the signer of an Authenticode-signed file isn't supported on any OS other than Windows.

This is tracked by https://github.com/dotnet/corefx/issues/2910.
