### ISSUE TITLE
Application of ObsoleteAttribute to legacy collection types

### ISSUE THREAD

**Issue by sharwell** [dotnet/corefx#384]
As mentioned in #370, the lack of `[Obsolete]` on certain legacy types in `System.Collections.Specialized` could be confusing to developers. In general I support the use of ObsoleteAttribute, but for this particular library I would recommend it only be applied to types which have well-known newer (better) alternatives.

I'm working on the following table...

| Legacy Type | Replacement |
| --- | --- |
| `BitVector32` | No direct replacement? |
| `HybridDictionary` | No direct replacement? |
| `IOrderedDictionary` | No direct replacement? |
| `ListDictionary` | No direct replacement? |
| `NameObjectCollectionBase` | No direct replacement? |
| `NameValueCollection` | No direct replacement? |
| `OrderedDictionary` | No direct replacement? |
| `StringCollection` | `List<string>` |
| `StringEnumerator` | Only used with `StringCollection` (not marked obsolete?) |
| `StringDictionary` | `Dictionary<string, string>` |

**Comment by akoeplinger** [comment]
:+1: 

More generally, I'd really appreciate if the team could investigate applying `[Obsolete]` to other legacy collection classes like `ArrayList` as well. This [simple search](http://stackoverflow.com/search?tab=newest&q=%5bc%23%5d%20arraylist) on StackOverflow has plenty of results where people are still using it and I doubt all of it is legacy code.

I know that seasoned .NET developers are very well aware of the fact that the generic collection classes are preferred, but if we can improve the discoverability for beginners as well, I think that'd benefit everyone.

**Comment by mikedn** [comment]
BitVector32 seems useless to me (#373) but that doesn't automatically make it obsolete. And it certainly doesn't have a direct replacement.

Dictionary<string, string> is not a direct replacement for StringDictionary. StringDictionary uses a Hashtable and there are well known differences between Hashtable and Dictionary<K,V> that can make replacement a bit problematic.

Personally I wouldn't include any of these types (and the non-generic collections) in .NET Core, they're remnants of the early days of .NET and do not belong in the future. But I suspect that the same arguments that were used to put them in .NET Core will also lead rejection of obsoleting them.

At the end of the day only the most clueless developers will use these today, the very same type of developer that would ignore all the warnings as well.

**Comment by terrajobst** [comment]
I feel quite strongly that we shouldn't apply the obsoletion attribute on the legacy collection types. First let, we restate what I said in #370:

@akoeplinger

> Those warnings can be easily disabled, I don't think that's a good enough reason to keep confusing users.

But only at the global level. You can't say "yes, I know about `ArrayList`". These warnings will cause a lot of noise and my concern is that you miss other obsoletion warnings that tell customers about potentially issues in their applications. In the past, we've been quite selective when it comes to applying this attribute. If used too broadly, the signal to noise ratio reaches the point where the features becomes useless.

A better mechanism to make sure that new code doesn't use these collection types is by not referencing the `System.Collections.NonGeneric` NuGet package by default, which is what we're planning on doing.

**Comment by terrajobst** [comment]
@sharwell also just discovered why we decided to port the legacy collection types to .NET Core: these collection types don't have a 1:1 mapping in all scenarios. You pretty much have to revisit a large chunk of the code using those to determine how you replace them.

Even fairly straightforward collections like `ArrayList` and `Hashtable` have semantics that can be error prone to port. For example, `Hashtable` doesn't throw when indexing with a non existent key, `Dictionary<K,V>` throws. `ArrayList` has virtual members.

Porting legacy code to use the modern collections can be worthwhile if you want to drop the dependency on `System.Collections.NonGeneric`, benefit from generics or get better perf.

I don't think that obsoletion warnings in the code are a good motivator. For true legacy code it's much better if you can simply add a reference to the `System.Collections.NonGeneric` NuGet package and have it work.

**Comment by akoeplinger** [comment]
@terrajobst 
> [..] that you miss other obsoletion warnings that tell customers about potentially issues in their applications.

Can you give an example of such a warning? I'm not sure what a "potential issue" in this context would be?

> A better mechanism to make sure that new code doesn't use these collection types is by not referencing the  System.Collections.NonGeneric  NuGet package by default, which is what we're planning on doing.

True, that'll likely help.

**Comment by Giorgi** [comment]
What about all custom collections such as ProcessModuleCollection ?

**Comment by sharwell** [comment]
So what you are saying is.............

**Comment by Giorgi** [comment]
It would be great to replace with generic ones so that it's easier to iterate over them

**Comment by sharwell** [comment]
@Giorgi Sorry for the confusion. My comment is actually related to the issue I opened up immediately after commented.

**Comment by terrajobst** [comment]
@sharwell using a diagnostic is likely better because it could be more targeted. For example, it could provide a single warning per project, rather than spilling a gazillion warnings.

**Comment by KyleMcNutt** [comment]
As a newbie to the .NET world, although extremely interested in following this space and learning as much as possible, I had no idea that `ArrayList` was a legacy collection type, so I'm very glad I've been following these Github conversations. I also think that there are probably a lot of other people like me out there who are coming from a Java world where `ArrayList`'s get used frequently (at least in my experience).

That being said I think that @terrajobst's suggestion of removing the `System.Collections.NonGeneric` NuGet package by default for .NET projects would be enough to warn me away from using an `ArrayList`. It would be nice to have something that pointed me in a better direction in case I did try and use an `ArrayList` but I suppose a quick ~~Google~~ Bing search would net me that information.

**Comment by ebickle** [comment]
I haven't fully formulated the thought yet, but I've been toying with the idea of proposing an enhancement to the ObsoleteAttribute type so that, well, it's no longer obsolete.

The primary issue is that there needs to be an indication to developers which types are discouraged, but not necessarily obsolete in the sense that they shouldn't ever be used or may be removed in a future version.

The corefx libraries are designed to be released at a higher cadence than the regular .NET Framework, and the versioning & deprecation strategy should be revisited to fit better.

WinRT has a DeprecatedAttribute with a DeprecationType. ObsoleteAttribute could potentially have a similar type enumeration added to it, which would provide a method of indicating that something is "discouraged" but not necessarily obsolete to the point a warning should be shown.

It would require changes to the compiler to avoid warning on "discouraged" APIs. The IDE could potentially pick up on the attribute and gray out APIs, to provide a hint to developers without being overbearing.

Alternately, an entirely new attribute could be added for APIs that are discouraged but not officially deprecated.

**Comment by weshaggard** [comment]
For better or worst I think that @terrajobst suggestion of having a diagnostic (FxCop rule or Roslyn Analytic) about these types is about the best we can do. That can hopefully help point people in the right direction without having the compile time implications that obsolete has. In particular compile time implications become trouble when you are in an asp.net type scenario where you are compiling on the fly and it essentially breaks apps at runtime.

**Comment by Priya91** [comment]
From the conversation, the issue has been addressed by @weshaggard and @terrajobst comments. Closing this issue.
