### ISSUE TITLE
InterlockedTests.MemoryBarrierProcessWide failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#38400]
netcoreapp-Linux-Release-arm64-(Ubuntu.1604.Arm64.Open)Ubuntu
https://dev.azure.com/dnceng/public/_build/results?buildId=218360&view=ms.vss-test-web.build-test-results-tab&runId=5372384&paneView=debug
```
Error message
Assert.Equal() Failure\nExpected: 1000000\nActual: 999998

Stack trace
   at System.Threading.Tests.InterlockedTests.MemoryBarrierProcessWide() in /_/src/System.Threading/tests/InterlockedTests.netcoreapp.cs:line 122
```

**Comment by stephentoub** [comment]
This test was just re-enabled in https://github.com/dotnet/corefx/commit/7e56d8bd8b224d834b782a98bfd7035f71c3f547.

cc: @vsadov

**Comment by stephentoub** [comment]
Also failed here:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38381~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190610.14/workItem/System.Threading.Tests/analysis/xunit/System.Threading.Tests.InterlockedTests~2FMemoryBarrierProcessWide
```
Unhandled Exception of Type Xunit.Sdk.EqualException
Message :
Assert.Equal() Failure
Expected: 1000000
Actual:   999999
Stack Trace :
   at System.Threading.Tests.InterlockedTests.MemoryBarrierProcessWide() in /_/src/System.Threading/tests/InterlockedTests.netcoreapp.cs:line 122
```

**Comment by ericstj** [comment]
Again: https://dev.azure.com/dnceng/public/_build/results?buildId=216796&view=ms.vss-test-web.build-test-results-tab&runId=5366168&resultId=245930&paneView=debug

```
Assert.Equal() Failure\nExpected: 1000000\nActual: 999998
```

**Comment by stephentoub** [comment]
I've disabled the test.

**Comment by VSadov** [comment]
It is a serious concern that this is not working reliably. We rely on process-wide fences in GC, for example. 

We should reactivate the bug then. (https://github.com/dotnet/coreclr/issues/20215)

I hope it is a test issue.

**Comment by VSadov** [comment]
Or just use this bug for tracking.

**Comment by danmosemsft** [comment]
If this is tracked by https://github.com/dotnet/coreclr/issues/20215, I don't think we need this issue open as well.
