### ISSUE TITLE
Expression interpreter - No support for TryFault

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#3840]
This is not implemented right now. It may be possible to get it to work if we could get a try...fault... region in the interpreter code (in particular in EnterTryCatchFinallyInstruction.Run) but the C# compiler does not have this construct.

Some options are:
- Get it into the compiled binary using some ILASM magic, possibly by using a helper TryFault method that's self-contained and is parameterized on interpreter instruction ranges (range of try, range of fault, etc.). May be tricky with build.
- Piggyback on a C# language construct that emits fault blocks, e.g. using blocks in iterators. An example of this trick is pasted below, but it'd obviously be changed to be parameterized on instruction ranges rather than take in Action delegates.
- Emulate try...fault in some lowering phase by rewriting it to try...finally with a Boolean flag check. This could also be the way to get TryFault to work on the compiler, see #3838. Will have to be double-checked to be conform the exception semantics of the CLR construct.

```csharp
static class ExceptionHelpers
{
    public static void TryFault(Action body, Action fault)
    {
        TryFaultCore(body, fault).MoveNext();
    }

    private static IEnumerator TryFaultCore(Action body, Action fault)
    {
        using (new Handler(fault))
        {
            body();
            yield return null;
        }
    }
}

struct Handler : IDisposable
{
    private readonly Action _fault;

    public Handler(Action fault)
    {
        _fault = fault;
    }

    public void Dispose()
    {
        _fault();
    }
}
```

**Comment by VSadov** [comment]
could also be modeled as an all-catching  Try/Catch

**Comment by bartdesmet** [comment]
Hmm, wouldn't a Try/Catch interfere with the evaluation order of filters higher up? I.e. we'd unwind to the catch-all prior to evaluating filters higher up:

try
{
.  try
.  {
.     A();
.  }
.  fault
.  {
.     B();
.  }
}
catch (E e) when C(e)
{
.  D();
}

Order should be A, C, B, D in case A throws an exception of type E for which C evaluates to true. If fault is implemented as catch-all-and-rethrow, B would run before C.
