### ISSUE TITLE
Expression interpreter - No support for exception filters

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#3841]
The expression interpreter lacks support for TryCatch with a CatchBlock whose Filter property is non-null. This is properly supported in the expression compiler though.

Support for this could be likely be added by unflattening the list of catch blocks that are processed by EnterTryCatchFinallyInstruction.Run and using C# 6.0's support for filters to run a region of interpreter instructions when an exception occurs (those would have an "isinst" check followed by the user-supplied filter code) which get skipped on regular code paths using a goto. The reason the list of catch blocks needs to be unflattened (just in this case, we can keep things compact in cases where no filters are used) is to ensure that the code in the filters runs prior to unwinding the stack, such that any side-effects are visible across filters and eventually when the handlers run. By piggybacking on the CLR support for filters, we don't have to worry about this stack walk to evaluate which handler to use by running filter expressions; we just have to keep the nesting of exception handlers consistent with the emitted expression.

Rough idea:

```csharp
public override int Run(InterpretedFrame frame)
{
    // ...
    try
    {
        // ...
    }
    catch (Exception ex) when (RunFilter(frame, _filter.StartIndex, _filter.EndIndex))
    {
        // ...
    }
    // ...
}
```

There may be some trickiness around keeping the stack balance in all cases, but should be doable.

**Comment by JonHanna** [comment]
> This is properly supported in the expression compiler though.

How do you find that? If I try:

```C#
[Fact]
public void FilterOnCatch()
{
    TryExpression tryExp = Expression.TryCatch(
        Expression.Throw(Expression.Constant(new TestException()), typeof(int)),
        Expression.Catch(typeof(TestException), Expression.Constant(1), Expression.Constant(false)),
        Expression.Catch(typeof(TestException), Expression.Constant(2), Expression.Constant(true)),
        Expression.Catch(typeof(TestException), Expression.Constant(3))
        );
    Assert.Equal(2, Expression.Lambda<Func<int>>(tryExp).Compile()());
}
```

I get a `NotSupportedException` originating from `DynamicILGenerator.BeginExceptFilterBlock()`, similar to the cause of #3838 when it gets to `.Compile()`.

**Comment by bartdesmet** [comment]
Supported up to the restriction in reflection emit, yes (meaning we do emit the construct, for the interpreter we just don't attempt). Works on desktop CLR when emitting to method builders. Both should likely be addressed now that C# has filters too. My work on extending the expression APIs already emits those filters so one would be right to assume they can be compiled and/or interpreted.

**Comment by JonHanna** [comment]
>  The reason the list of catch blocks needs to be unflattened (just in this case, we can keep things compact in cases where no filters are used) is to ensure that the code in the filters runs prior to unwinding the stack, such that any side-effects are visible across filters and eventually when the handlers run.

I took a different tact to what I think you are suggesting here. Just as the C# compiler turns an exception with a filter into a filter that includes both the type check and the filter from the C# (since in CIL filters don't have a built-in type check), so I put all of the logic for finding which, if any, handler to run into a filter, whether the catch block has a filter or no.
