### ISSUE TITLE
Source-build patch removal for CoreFX

### ISSUE THREAD

**Issue by crummel** [dotnet/corefx#38412]
Source-build has some patches that we are currently applying to your repo.  This issue tracks removing the patches.  These patches can be found at https://github.com/dotnet/source-build/tree/release/3.0/patches/corefx.

Patches that have the responsibility "Repo" and the Disposition "Incorporate" are patches that we believe are valid source-build fixes that should be moved into your repo.  Please let us know if these don't seem like good patches.  Any changes with the responsibility "source-build" is something that we plan to keep going forward or integrate in another way - please also let us know if you think there may be problems with those patches.

Patch name | Type | Disposition | Responsibility | Notes
-- | -- | -- | -- | --
corefx/0001-Remove-publishing-package-that-source-build-doesn-t-.patch | Build | Incorporate | Repo |

**Comment by ericstj** [comment]
Already done in https://github.com/dotnet/corefx/commit/ecfb60b67d09b992f24af0625305299710bc128f
