### ISSUE TITLE
Allow a precision to be provided for the 'G' format in UTF8Formatter

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#38416]
Full framework and .NET Core prior to 3.0 have different floating-point formatting behavior as compared to .NET Core 3.0 or higher. In particular, they do not produce roundtrippable strings by default.

In order to provide the best possible results for roundtripping and consistency between the UTF8 and UTF16 formatters, the UTF8Formatter should be fixed to allow a precision to be given for the 'G' format specifier.

This will allow System.Text.Json to use "G17" when serializing double-precision floating-point values on Full Framework and .NET Core versions prior to 3.0. This is the same format specifier that is used in System.Xml, Newtonsoft.Json, and most other serializers.
* "G17" is used because "R" (the roundtrip format specifier), on Full Framework and .NET Core versions prior to 3.0, has some bugs that cause it to not always return a roundtrippable result.

**Comment by tannergooding** [comment]
CC. @ahsonkhan, @danmosemsft

**Comment by danmosemsft** [comment]
> to allow a precision to be given for the 'G' format specifier

Would this change any existing observable behavior? (Assuming no mistakes are made.) This sounds like it was simply not possible to specify a precision before.

**Comment by tannergooding** [comment]
Correct. The PR resolving this is here: https://github.com/dotnet/corefx/pull/38419. 

The logic currently just does:
```csharp
                case 'g':
                case 'G':
                    if (format.Precision != StandardFormat.NoPrecision)	
                        throw new NotSupportedException(SR.Argument_GWithPrecisionNotSupported);	
                    break;
```

The fix is removing the check so that precisions can be specified.

**Comment by stephentoub** [comment]
PR was closed pending customer feedback.  Closing issue as well.
