### ISSUE TITLE
JsonSerializer not parsing correctly nested object having null dictionary

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/corefx#38414]
JsonSerializer not parsing a class with nested class having a null Dictionary property. 
- if the Dictionary in inner object is initialized then no issue
- if the Dictionary in inner object is null all properties defined after that object has null or 0, properties defined before that object are set properly
- if inner object is not initialized then no issue
- this issue is also root cause of https://github.com/dotnet/corefx/issues/38490 
```csharp
[Fact]
public static void OuterClassHavingPropertiesDefinedAfterClassWithDictionaryTest()
{
    OuterClassHavingPropertiesDefinedAfterClassWithDictionary testObject = new OuterClassHavingPropertiesDefinedAfterClassWithDictionary { MyInt = 10, MyIntArray = new int[] { 3 },    MyDouble= 3.14, MyList =new List<string> { "Hello" }, MyString = "World",  MyInnerTestClass = new SimpleClassWithDictionary { MyInt = 2 } };
    string json = JsonSerializer.ToString(testObject);

    OuterClassHavingPropertiesDefinedAfterClassWithDictionary parsedObject = JsonSerializer.Parse<OuterClassHavingPropertiesDefinedAfterClassWithDictionary>(json);

    Assert.Equal(3.14, parsedObject.MyDouble);      // Not fail
    Assert.Equal(10, parsedObject.MyInt);           // Fails because set to 0
    Assert.Equal("World", parsedObject.MyString);   // Fails because set to null
    Assert.Equal("Hello", parsedObject.MyList[0]);  // Fails because set to null
    Assert.Equal(3, parsedObject.MyIntArray[0]);    // Fails because set to null
    Assert.Equal(2, parsedObject.MyInnerTestClass.MyInt);   // Not fail, set correctly
}

public class SimpleClassWithDictionary
{
    public int MyInt { get; set; }
    public Dictionary<string, string> MyDictionary { get; set; }
}
public class OuterClassHavingPropertiesDefinedAfterClassWithDictionary
{
    public double MyDouble { get; set; }
    public SimpleClassWithDictionary MyInnerTestClass { get; set; }
    public int MyInt { get; set; }
    public string MyString { get; set; }
    public List<string> MyList { get; set; }
    public int[] MyIntArray { get; set; }
}
```

**Comment by ahsonkhan** [comment]
cc @YohDeadfall

**Comment by ahsonkhan** [comment]
@buyaa-n, can you provide a simplified repro of the issue that doesn't involve all the various types from the test class? What is the simplest "model" type where such an issue occur?

**Comment by buyaa-n** [comment]
I didn't dig into these bugs much, but i suspect its happening because a type having another type having property (not primitive type an array or collection) with same name and type they overwriting one another's value. Will think about simpler case

**Comment by buyaa-n** [comment]
@ahsonkhan @steveharter @layomia it turns out this issue is not related to Struct, simplified test and  updated the issue accordingly, looks like very bad bug

**Comment by ahsonkhan** [comment]
> it turns out this issue is not related to Struct, simplified test and updated the issue accordingly,

> JsonSerializer not parsing a class with nested class having a null Dictionary property.

> this issue is also root cause of #38490

In that case, @tannergooding's PR should fix both this issue and the other one you filed: https://github.com/dotnet/corefx/pull/38704

Can you please checkout his branch and verify that his change is actually fixing both of the issues you reported?

**Comment by buyaa-n** [comment]
This test is merged with Active issue number so @tannergooding can pull and test in his branch

**Comment by buyaa-n** [comment]
Verified with latest code, it is fixed

**Comment by YohDeadfall** [comment]
Should this issue be assigned to @tannergooding then?

**Comment by ahsonkhan** [comment]
Sure, if you prefer. The issue is fixed either way :p
