### ISSUE TITLE
[API review] Add Timers.Count

### ISSUE THREAD

**Issue by kouvel** [dotnet/corefx#38422]
From https://github.com/dotnet/coreclr/issues/20372#issuecomment-497013866:

```c#
namespace System.Threading
{
    public sealed class Timer
    {
        /// <summary>
        /// Gets the number of timers that are currently active. An active timer is registered to tick at some point in the
        /// future, and has not yet been canceled.
        /// </summary>
        public static long ActiveCount { get; }
    }
}
```

Enables tracking the number of timers currently scheduled.
- Used `long` instead of `int` because this API is somewhat similar in nature to `ThreadPool.PendingWorkItemCount` and the choice there was to use `long`

**Comment by stephentoub** [comment]
What are the scenarios for this?  I'm wondering if this data is sufficient, or if the scenarios would actually need more details for things to be meaningful, e.g. the distribution of when the timers are scheduled to fire next.

**Comment by stephentoub** [comment]
@kouvel, I see you marked this as api-suggestion and Future, but then you also submitted PRs to coreclr to implement this and corefx to expose it.  Which is it? :)

**Comment by kouvel** [comment]
CC @davidfowl

**Comment by kouvel** [comment]
A scenario is to be able to track the number of scheduled timers, and to be able to report and view it over time such that timer leaks can be spotted easily. If more details are necessary I imagine that would need a different API. Are you thinking of something that could support future additions to metrics? I was thinking along those lines before (like maybe a separate class that provides runtime metrics, mainly for other reasons), so far providing individual APIs on the relevant existing class has been preferred for new threading metrics that were recently added. This API is similar to `ThreadPool.PendingWorkItemCount`.

**Comment by kouvel** [comment]
The corefx PR to expose it is targeted for post-3.0. The coreclr PR is targeted for 3.0 such that the value can be obtained through reflection. @davidfowl wanted a solution for 3.0.

**Comment by stephentoub** [comment]
> The coreclr PR is targeted for 3.0 such that the value can be obtained through reflection.

Just gonna leave this here:
https://github.com/dotnet/coreclr/pull/22396#issuecomment-463033411
:wink:
cc: @jkotas 

This API is trivial.  If we believe in it, let's get it reviewed and merged for 3.0 and avoid taking a private reflection dependency.  If we don't, let's not depend on it via private reflection.

> Are you thinking of something that could support future additions to metrics?

My question was mainly about the scenarios it was meant to target.  If it's just about detecting leaks or a backed-up queue that grows continually, this seems reasonable.  I was imagining other potential use cases, e.g. determining whether groups of timers could be coalesced to help tune perf, helping to find cases where timers aren't being disposed of and aren't leaked but are sticking around beyond when they're useful, etc.

**Comment by kouvel** [comment]
There have been cases before where there was no timer leak but there were so many short-period timers that it showed other perf effects. Although this doesn't provide any info about the average frequency of repeating timers (which I think would be useful in some cases), it can help to spot a high number of timers and if other perf effects related to timers are seen, further investigation may be prompted to fix something else.

**Comment by stephentoub** [comment]
Ok, thanks. I changed the issue to be 3.0.

**Comment by davidfowl** [comment]
> If it's just about detecting leaks or a backed-up queue that grows continually, this seems reasonable.

I wanted to specifically target this case as a counter value. Detecting Timer leaks would be a plus as well.

**Comment by stephentoub** [comment]
> I wanted to specifically target this case as a counter value

Does that mean monotonically increasing to count how many timers there have ever been? Or you just mean what Kount has, where it's tracking the current number of active timers?

**Comment by davidfowl** [comment]
> Does that mean monotonically increasing to count how many timers there have ever been? Or you just mean what Kount has, where it's tracking the current number of active timers?

Number of active timers. Thought i can see where the number of timers ever could also be interesting. Number of counters can be another signal to look at when looking at system health (basically all of the shared resources in .NET are useful to look at)

**Comment by stephentoub** [comment]
Ok, thanks. This seems reasonable to me.

**Comment by terrajobst** [comment]
After long discussion, we agreed on:

```C#
namespace System.Threading
{
    public partial class Timer
    {
        public static long ActiveCount { get; }
    }
}
```

**Comment by kouvel** [comment]
Thanks, updated proposal inline to reflect the above
