### ISSUE TITLE
API proposal: use SocketAsyncEventArgs.SetBuffer(int, int) with Memory buffer

### ISSUE THREAD

**Issue by kjkrum** [dotnet/corefx#38457]
I'm using SAEA for the first time, so apologies if I've overlooked something obvious. I'm interested in the ability to set a `Memory` buffer and reuse it for numerous operations without reallocating it. But I don't see any API to set the offset and number of bytes to send or receive independently from the `start` and `length` parameters to the `Memory` constructor. `SetBuffer(int, int)` throws an exception when using a `Memory` buffer.

If I'm not missing something, then this is an API suggestion: allow `SetBuffer(int, int)` to be used with a `Memory` buffer, and use the `Offset` and `Count` properties of the SAEA rather than the properties of the buffer to determine the range to send or receive. When used this way, I think the arguments to `SetBuffer` would range from `0` to `MemoryBuffer.Length`.

**Comment by kjkrum** [comment]
This is an issue with `byte[]` buffers as well; see this [SO Q&A from 2013](https://stackoverflow.com/questions/18042097/how-to-specify-the-number-of-bytes-to-send-when-using-socket-sendtoasync) for the clumsy workaround.  Perhaps more generally, `SocketAsyncEventArgs` should have `OpOffset` and `OpCount` properties that are set by a new `SetOpBuffer` method, and constrained by `Offset` and `Count` when using a `byte[]` buffer or `MemoryBuffer.Length` when using a `Memory` buffer.

**Comment by davidsh** [comment]
@stephentoub @wfurt

**Comment by tmds** [comment]
@kjkrum can you use `Memory<T>.Slice` to do what you want?

**Comment by JanEggers** [comment]
just use Pipelines.Sockets.Unofficial or have a look how to use the api there:

https://github.com/mgravell/Pipelines.Sockets.Unofficial/blob/master/src/Pipelines.Sockets.Unofficial/SocketConnection.Send.cs

**Comment by kjkrum** [comment]
@tmds I thought of that, but it would introduce unnecessary allocations. Instead, I changed what I was trying to do to better fit the existing API. If I received half a message, I was going to leave it in the SAEA's buffer until I received the rest of it, so the next call to receive would require a different offset. But now I'm just requiring that the consumer always copy all the data into its own buffer, so the SAEA's buffer never needs to change.

**Comment by stephentoub** [comment]
> it would introduce unnecessary allocations

`Memory<T>` is a struct.  What allocations are you concerned with?

**Comment by kjkrum** [comment]
If I replaced the SAEA's `MemoryBuffer` with a new slice before every async operation, the new `Memory` would be stored on the heap and the previous one would have to be GCed, right? Anyway, it's a moot point since I realized I don't need to do that. (I was trying to treat the SAEA's buffer like Java's `ByteBuffer`, with flip and compact operations.)

**Comment by stephentoub** [comment]
> If I replaced the SAEA's MemoryBuffer with a new slice before every async operation, the new Memory would be stored on the heap and the previous one would have to be GCed, right?

No, `Memory<T>` is a struct; creating a new one does not involve a heap allocation.

**Comment by kjkrum** [comment]
@stephentoub But it _can_ be stored on the heap, and I think it will be if it's a field of an object.

**Comment by stephentoub** [comment]
@kjkrum, the `Memory<T>` is stored as a field on the `SocketAsyncEventArgs` class.  Yes, that `SocketAsyncEventArgs` is on the heap, but no matter how many times you overwrite the `Memory<T>` that's stored on it, you're not allocating anything beyond that initial allocation for the `SocketAsyncEventArgs` instance.  In other words, this code:
```C#
for (int i = 0; i < 100; i++)
{
    saea.SetBuffer(memory.Slice(i, 10);
}
```
is allocation-free.
