### ISSUE TITLE
Decimal.Parse with culture does not allows spaces inside numbers with libicu64

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#38455]
Repro code:

1) Create a new Ubuntu 16.04 machine. It should have libicu55 installed by default. Run this code and see that it prints the decimal as `32000`

```
using System;
using System.Globalization;

namespace repro
{
    public class Program
    {

        public static void Main(string[] args)
        {
            var culture = new CultureInfo("fr-FR");
            Console.WriteLine(Decimal.Parse("32 000", NumberStyles.AllowThousands, culture));
        }
    }
}
```

2. Install `libicu64`  (I used the `ppa:ondrej/php` repository because I couldn't figure out any other way to apt-get install the package).

3. Run the app again. See that it fails with:

```
Unhandled Exception: System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseDecimal(ReadOnlySpan`1 value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Decimal.Parse(String s, NumberStyles style, IFormatProvider provider)
   at repro.Program.Main(String[] args) in /home/prkrishn/repro/Program.cs:line 21
```

It's weird that spaces are allowed with a non-English Culture to start with. With an en-US Culture, the parse fails regardless of the installed libicu64 version.

**Comment by tannergooding** [comment]
Will follow up here, it sounds like a bug in libicu, and so there is likely little we can do here.

CC. @tarekgh

**Comment by tarekgh** [comment]
I'll try to take a look

**Comment by tarekgh** [comment]
@tannergooding was right. ICU has changed the NumberGroupSeparator from "\u00a0" to "\u202f".

We have special cased handling "\u00a0" https://github.com/dotnet/coreclr/blob/96c8a1259f5605f52a4d08d804c5f0cdb59308b2/src/System.Private.CoreLib/shared/System/Number.Parsing.cs#L1903 so we may need to special case \u202f too :-(
