### ISSUE TITLE
IndexOutOfRangeException on parsing struct having a class property

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/corefx#38490]
Note: 1. Serialization part producing correct/valid json., Error happening on parsing it back.
2. When the row 3 `testObject.MySampleTestClass = new SimpleTestClass  { MyString = "Hello", MyDouble = 3.14 } ;` is not set there is no error, test class: [TestClasses.SimpleTestStruct.cs.txt](https://github.com/dotnet/corefx/files/3312576/TestClasses.SimpleTestStruct.cs.txt)
```csharp
[Fact]
public static void ReadStructObjectValueTest()
{
    SimpleTestStruct testObject = new SimpleTestStruct();
    testObject.Initialize();
    testObject.MySimpleTestClass = new
    SimpleTestClass  { MyString = "Hello", MyDouble = 3.14 } ;

    string json = JsonSerializer.ToString(testObject);
    SimpleTestStruct parsedObject = JsonSerializer.Parse<SimpleTestStruct>(json);
    parsedObject.Verify();            
}

System.Text.Json.Serialization.Tests.ObjectTests.ReadStructObjectValueTest [FAIL]
   System.IndexOutOfRangeException : Index was outside the bounds of the array.
 Stack Trace:
D:\dotnet\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonClassInfo.cs(246,0):  
   at System.Text.Json.JsonClassInfo.GetProperty(JsonSerializerOptions options, ReadOnlySpan`1 propertyName, ReadStackFrame& frame)
D:\dotnet\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.HandlePropertyName.cs(76,0): 
   at System.Text.Json.JsonSerializer.HandlePropertyName(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
D:\dotnet\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.cs(52,0): 
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
D:\dotnet\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.Helpers.cs(22,0): 
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
D:\dotnet\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.String.cs(74,0):
   at System.Text.Json.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options)
D:\dotnet\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.String.cs(31,0):
   at System.Text.Json.JsonSerializer.Parse[TValue](String json, JsonSerializerOptions options)
D:\dotnet\corefx\src\System.Text.Json\tests\Serialization\Object.ReadTests.cs(297,0): 
   at System.Text.Json.Serialization.Tests.ObjectTests.ReadStructObjectValueTest()
```

**Comment by AbhiAgarwal192** [comment]
@buyaa-n Checking.

**Comment by AbhiAgarwal192** [comment]
Can you share your repo url?

**Comment by buyaa-n** [comment]
@AbhiAgarwal192 https://github.com/dotnet/corefx/pull/38403/files#diff-90c308a62f95240a19bf0b1d31eb6971R255

**Comment by buyaa-n** [comment]
oops mistakenly closed

**Comment by ahsonkhan** [comment]
@buyaa-n, can you provide a simpler repro of the issue?

**Comment by buyaa-n** [comment]
@ahsonkhan I was not able to find simpler repro test. The core cause of this issue is similar to https://github.com/dotnet/corefx/issues/38414 except in this case its `iBackward` index is out of bounds here: https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.cs#L236 . If we avoid that with additional check `iBackward < count` we will get exact same error as in https://github.com/dotnet/corefx/issues/38414

**Comment by buyaa-n** [comment]
@ahsonkhan i was not able to simplify much, so at least attaching the test class

**Comment by buyaa-n** [comment]
The root cause of this issue is fixed with Tanner's change, so `iBackward ` index is not exceeding out of bounds anymore, so closing this issue, not sure if we want to add boundary check to avoid future failure, @ahsonkhan feel free to open it back if needed

**Comment by ahsonkhan** [comment]
@buyaa-n, good point. We know that iForward is within the bounds. If iBackward is also within the bounds (and that is an invariant), we should add a Debug.Assert ther:
