### ISSUE TITLE
Modify misc tests to use Invariant culture instead of current culture

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#3850]
Also see issue #3759 for background

Some tests assume en-us or invariant and on a test machine which is not configured the tests will fail. These tests should not depend on a specific default locale. 

Below is a set of tests that fail when LANG variable is not set in Linux. These should be fixed to explicitly use Invariant. 

Note that some of these tests fail due to unrelated but known issue with case-insensitive string comparison that happens to fail with the default locale of en-US-POSIX (when LANG is not set) so these tests may have to be disabled temporary for Linux until that issue is fixed

 Int32Tests.TestTryParse
 UInt32Tests.TestTryParse
 UInt16Tests.TestTryParse
 UInt64Tests.TestTryParse
 StringTests.TestLastIndexOf
 StringTests.TestEndsWith
 StringTests.TestStartsWith
 StringTests.TestIndexOf
 Int16Tests.TestTryParse
 Int64Tests.TestTryParse
 TypeTests.TestGetTypeByName
 Tests.Expression_Tests.TestCallInstanceMethodsByName
 CaseInsensitiveComparer_ctor.ExecuteCaseInsensitiveComparer_ctor
 CaseInsensitiveComparer_Default.ExecuteCaseInsensitiveComparer_Default
 CaseInsensitiveComparer_Object.ExecuteCaseInsensitiveComparer_Object
 CollectionsUtilTests.ExecuteCollectionsUtilTests
 System.Reflection.Tests.ModuleTest.GetTypeTest
 System.Reflection.Tests.MethodInfoPropertyTests.TestReturnType2
 System.Reflection.Tests.MethodInfoPropertyTests.TestReturnType4
 System.Reflection.Tests.GetTypeReflectionTests.GetType1
 System.Reflection.Tests.ParameterInfoNameTests.TestMethodParams1

**Comment by karelz** [comment]
Should be simple change of tests to set culture to InvariantCulture first.

**Comment by Vertygo** [comment]
Can I take this one?

**Comment by karelz** [comment]
Sure, assigned to you @Vertygo

**Comment by karelz** [comment]
If you're in trouble @krwq and @tarekgh should be able to help ...

**Comment by krwq** [comment]
Hi @Vertygo, what's the status? Are you still working on it?

**Comment by krwq** [comment]
@Vertygo it's ok if you haven't started yet, I'm just wondering if I can pick this up since it is the last System.Globalization 2.0.0 bug 😉

**Comment by krwq** [comment]
@steveharter this does not repro for me on bash for windows or Ubuntu
Is there some special setup I need for this?

Here is what I did:
```
echo $LANG
  => en_US.UTF-8
set LANG=
echo $LANG
  => (nothing)
msbuild.sh src/System.Globalization/tests/System.Globalization.Tests.csproj /t:RebuildAndTest
  => `(...) System.Globalization.Tests  Total: 1647, Errors: 0, Failed: 0, Skipped: 0, Time: 7.295s`
```

**Comment by krwq** [comment]
I think those tests might not be in the System.Globalization... looking now

**Comment by tarekgh** [comment]
@krwq we had changed the globalization test much since this issue is opened. if you don't see any problem when changing the default language on the system before running the tests then we are ok here.

**Comment by krwq** [comment]
Thanks @tarekgh for confirming 😉
