### ISSUE TITLE
Access is denied: 'OpenQA.Selenium.Remote.DesiredCapabilities'.  -> AppiumOptions.ctor()

### ISSUE THREAD

**Issue by jackwangchs** [dotnet/corefx#38500]
To solve the port leaking issue https://github.com/SeleniumHQ/selenium/issues/4162, I upgrade the selenium to v4.0.0a1 and use AppiumOptions. However, it always reports 'Access is denied' error.

The driver setup is like this:
```
var options = new AppiumOptions();
options.AddAdditionalOption("platformName", "iOS");
options.AddAdditionalOption("deviceName", "iPhone X");
```
Any solution on that?

**Comment by svick** [comment]
What makes you think this is a corefx issue?

**Comment by jackwangchs** [comment]
Just open the ticket when checking the issue of Selenium branch, didn't notice it open in there. If you don't think it comes from corefx, just let me know.

**Comment by scalablecory** [comment]
Hi @jackwangchs,

The linked issue has 71 comments. Can you please extract the part you believe to be a corefx issue and edit your issue with that? This will be a huge help!

**Comment by tarekgh** [comment]
@jackwangchs I am closing this issue. if you have any specific to be addressed in corefx, please send the required information and we can reopen. Thanks.
