### ISSUE TITLE
Explore performance improvements when JsonSerializerOptions.PropertyNameCaseInsensitive is set

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#38510]
ASP.NET Core uses camel case serialization for it's serialization, but needs to be able to read content sent using `HttpClient.PostAsJsonAsync` which uses property casing. MVC supports this by setting `PropertyNameCaseInsensitive = true`. This works as expected, however has a significant performance penalty for deserialization: 

![image](https://user-images.githubusercontent.com/1165805/58991269-b900dc00-879c-11e9-9013-ce8dfccf8fc5.png)

For a future release, consider making this sort of round tripping more performant.

**Comment by JeremyKuhne** [comment]
@pranavkm Can you provide more details on the inputs/outputs here?

**Comment by pranavkm** [comment]
Json payload: https://github.com/aspnet/Benchmarks/blob/master/scripts/mvcjsoninput.lua#L2-L15 (repeated 8x times).

Type being deserialized: https://github.com/aspnet/Benchmarks/blob/master/src/Benchmarks/Controllers/HomeController.cs#L79-L96

Interestingly the test input is camel-cased because the benchmark was written prior to the `PropertyNameCaseInsensitive` change was made.

**Comment by ahsonkhan** [comment]
As a first step, we should add such a benchmark to [dotnet/performance](https://github.com/dotnet/performance) so that we can track the performance change in a tighter loop.
