### ISSUE TITLE
NuGet package `microsoft.netcore.app` version 3.0+ removes reference assemblies

### ISSUE THREAD

**Issue by yatli** [dotnet/corefx#38522]
In 2.x versions we have, for example, `ref\netcoreapp2.2\netstandard.dll` -- that's easy to understand, and we can just feed the assemblies in this folder to the compiler services for type checking etc.
But now in 3.0 preview packages this folder is gone. The compiler service complains about missing types.

Where should we look now?

**Comment by wtgodbe** [comment]
I believe the new location for these bits is the `Microsoft.NetCore.App.Ref` package - @dagood can you confirm?

**Comment by dagood** [comment]
Yes, in 3.0, `Microsoft.NETCore.App` is no longer the entry point to grab a framework/runtime. If you need to obtain ref assemblies as a package, that's `Microsoft.NetCore.App.Ref`, but if you install the SDK it's already installed at e.g. `C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.0.0-preview6-27804-01`. (That's what projects compile against now.) https://github.com/dotnet/designs/pull/50 has more info on the new approach.

**Comment by ericstj** [comment]
Curious why you’re looking at the package directly rather than letting nuget / SDK do their job to raise the references.  @dsplaisted @nguerrera

**Comment by yatli** [comment]
@ericstj I'm working on a F# language server, so it is a bit different than just getting things to build properly.

The basic workflow is to first figure out what are the source files in the project, what assemblies doe the project reference, and send the information to `FSharp.Compiler.Services`.

So there needs to be an "out-of-band" step to extract references. We first use Buidalyzer to populate `project.assets.json`, then parse it to get the dlls. This works well for netcoreapp2.x but not in 3.0, because `Microsoft.NetCore.App.Ref` is absent, and `Microsoft.NetCore.App` does not contain the ref assemblies anymore.

**Comment by ericstj** [comment]
Why wouldn’t you evaluate the project and invoke a target to do this?  MSBuild has a rich API that supports this sort of thing. That is how VS interacts with projects. /cc @davkean

**Comment by yatli** [comment]
I'm not the original author of the base project: https://github.com/fsprojects/fsharp-language-server
When I [forked](https://github.com/yatli/coc-fsharp) it, the "project cracker" sits there extracting project information without msbuild.

I guess this is partly because the F# tooling is a bit different than C# -- it's less dependent on msbuild, and it may be used with its own tooling (FAKE, Paket etc.) -- the F# compiler service has its own project cracker too. At some time it tried to support native MSBuild (around 2017 iirc), and now it seems deprecated.

Speaking of using the MSBuild API, yes it has a very rich API about these things, but sometimes too heavy to setup (considering we're running F#, possibly on mono, possibly on netfx, up to netcoreapp3.0).
I tried to use the MSBuild API directly, but it can't even find the F# compiler.

[That's why Buildalyzer is made](https://daveaglick.com/posts/running-a-design-time-build-with-msbuild-apis).

**Comment by ViktorHofer** [comment]
What is the remaining action item here? Can we close this?

**Comment by yatli** [comment]
I'm good -- it was more like a question and now I've implemented the new way of finding ref assemblies.
Would be great if it is documented somewhere, though.

**Comment by sergey-litvinov** [comment]
@ericstj we also use that original package `Microsoft.NetCore.App` and will switch to `Microsoft.NetCore.App.Ref`. 

And wanted to mention our reason - we need to understand what APIs are available in .Net Core 2\3 to provide kind of auto completion service, but we don't need to actually execute it. So that package was perfect fit and we don't need to install the whole SDK as part of deploy process and we can just add a nuget package and then consume all `references` libraries in that package that is much easier for us
