### ISSUE TITLE
Support (de)serializing types that implement `IDictionary` and `IDictionary<string, TValue>` without hint of implemented type

### ISSUE THREAD

**Issue by layomia** [dotnet/corefx#38521]
e.g. Given

```C#
public class StringToObjectIDictionaryWrapper : IDictionary<string, object>
{
    private readonly IDictionary<string, object> _dict;

    public StringToObjectIDictionaryWrapper(IDictionary<string, object> dict)
    {
        _dict = dict;
    }

    // Implementation for IDictionary<string, object>
    ...
}
```

After https://github.com/dotnet/corefx/pull/38512 is merged, this will work:
```C#
[Fact]
public static void ImplementsIDictionaryOfObject()
{
    var input = new StringToObjectIDictionaryWrapper(new Dictionary<string, object>
    {
        { "Name", "David" },
        { "Age", 32 }
    });

    string json = JsonSerializer.ToString(input, typeof(IDictionary<string, object>)); // Providing implemented type
    Assert.Equal(@"{""Name"":""David"",""Age"":32}", json);

    IDictionary<string, object> obj = JsonSerializer.Parse<IDictionary<string, object>>(json); // Parsing to implemented type
    Assert.Equal(2, obj.Count);
    Assert.Equal("David", ((JsonElement)obj["Name"]).GetString());
    Assert.Equal(32, ((JsonElement)obj["Age"]).GetInt32());
}
```

This doesn't work
```C#
[Fact]
public static void ImplementsIDictionaryOfObject()
{
    var input = new StringToObjectIDictionaryWrapper(new Dictionary<string, object>
    {
        { "Name", "David" },
        { "Age", 32 }
    });

    // This throws NotSupportedException
    string json = JsonSerializer.ToString(input); // Not providing implemented type
    Assert.Equal(@"{""Name"":""David"",""Age"":32}", json);

    // (Assuming json == @"{""Name"":""David"",""Age"":32}") This throws NotSupportedException
    StringToObjectIDictionaryWrapper obj = JsonSerializer.Parse<StringToObjectIDictionaryWrapper>(json); // Parsing to actual type
    Assert.Equal(2, obj.Count);
    Assert.Equal("David", ((JsonElement)obj["Name"]).GetString());
    Assert.Equal(32, ((JsonElement)obj["Age"]).GetInt32());
}
```

**Comment by ahsonkhan** [comment]
@steveharter, can you please take a look and see if this issue is something we should be fixing, or is by design.

**Comment by steveharter** [comment]
`{ "Name", "David" }` is not a valid way to represent a dictionary entry, @layomia we don't support this currently, do we?

Only name:value pairs like this `{ "Name" :"David" }` and perhaps `{ "Key":"Name", "Value":"David" }`

**Comment by layomia** [comment]
> `{ "Name", "David" }` is not a valid way to represent a dictionary entry, @layomia we don't support this currently, do we?
> 
> Only name:value pairs like this `{ "Name" :"David" }` and perhaps `{ "Key":"Name", "Value":"David" }`

This code is creatung a new instance of the `StringToObjectIDictionaryWrapper` type which implements `IDictionary<string, object>`.
```C#
var input = new StringToObjectIDictionaryWrapper(new Dictionary<string, object>
{
    { "Name", "David" },
    { "Age", 32 }
});
```

The question is should we be able to parse the json string `@"{""Name"":""David"",""Age"":32}"` to a `StringToObjectIDictionaryWrapper` type (and roundtrip i.e. serialize back to the json string) since it implements `IDictionary<string, object>`?

Same question would apply to types that implement any of the interfaces we support - `ICollection`, `IList<T>`, etc.

**Comment by steveharter** [comment]
I see. Yes we should deserialize "David" and `32` both into a JsonElement, like we do for other "object" cases in dictionaries.
