### ISSUE TITLE
#2241 still happen when convert between Enum[] and signed/unsigned version of it's underlying type with Enumerable.Cast<>()

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/corefx#38535]
#2241 still happen for convert Enum, int to uint and some opposite case, should that also be fixed?

Maybe related to 
https://github.com/dotnet/roslyn/issues/29680#issuecomment-424549785
and
https://blogs.msdn.microsoft.com/ericlippert/2009/09/24/why-is-covariance-of-value-typed-arrays-inconsistent/

Should some check be add to Enumerable.Cast() to workaround this?
```cs
            if (typedSource != null && (default(TResult) == null || !(source is TResult[]) || source.GetType() == typeof(TResult[])))
            {
                return typedSource;
            }
```

The below code still get `System.ArrayTypeMismatchException: Source array type cannot be assigned to destination array type.` in netcoreapp3.0(3.0.0-preview6-27804-01)
```cs
Array[] test = new Array[] { new DayOfWeek[] { DayOfWeek.Monday }, new int[] { 1 }, new uint[] { 1 } };
foreach (var cur in test)
{
    cur.Cast<uint>().ToList();
    cur.Cast<uint>().ToArray();
    cur.Cast<DayOfWeek>().ToList();
    cur.Cast<DayOfWeek>().ToArray();
    cur.Cast<int>().ToList();
    cur.Cast<int>().ToArray();
}
```

**Comment by yyjdelete** [comment]
I have some mistake. Infact, the non generic version, `(uint)(object)0` or `(uint)(object)(DayOfWeek.Monday)` also get an `InvalidCastException`. But it's still an question, should the linq report the right Exception for cast?

**Comment by EgorBo** [comment]
As far as I understand you box all integers and the `Cast` just simply does `yield return (TResult)obj;` so you can't box `int` and ubox it as `uint`.

**Comment by mburbea** [comment]
That said though with enums it should be legal to cast between base type and the enum.
```cs
var intArray = new int[]{1};
var enumArray = (StringComparison[])(object)intArray; //legal
var enumUnbox = (StringComparison)(object)intArray[0] //legal
var enumArrayViaLinq = new[] { 1}.Cast<StringComparison>().ToArray();
// throws source array type cannot be assigned to destination array type
```

**Comment by jkotas** [comment]
We should relax the type check in `Array.Copy`

**Comment by yyjdelete** [comment]
@jkotas
Another question, when test with `Unsafe.As` to skip type check and just test ToArray with old runtime before the patch(3.0.0-preview6-27804-01), it show the cast between signed/unsigned is the only two fails, other incompatibility types convert always success..
Is this by design, or `Unsafe.As` just skip some needed checks since it's unsafe, or some other checks is missing?

```cs
using System;
using System.Linq;
using System.Runtime.CompilerServices;

namespace ConsoleApp7
{
    internal class Program
    {
        private static void TryCastUnsafe<T>(Array array)
        {
            try
            {
                var tmp = Unsafe.As<T[]>(array).ToArray();
                Console.WriteLine($"Convert from {array.GetType().GetElementType()} to {typeof(T)}:{string.Join(",", tmp)}");
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"Failed convert from {array.GetType().GetElementType()} to {typeof(T)}: {ex.GetType()}: {ex.Message}");
            }
        }

        private static void Main(string[] args)
        {
            TryCastUnsafe<int>(new uint[] { 0, 1, 2, 3, 4, 5 });
            TryCastUnsafe<uint>(new int[] { 0, 1, 2, 3, 4, 5 });
            TryCastUnsafe<int>(new ulong[] { 0, 1, 2, 3, 4, 5 });
            TryCastUnsafe<ulong>(new int[] { 0, 1, 2, 3, 4, 5 });
            TryCastUnsafe<double>(new int[] { 0, 1, 2, 3, 4, 5 });
            TryCastUnsafe<int>(new double[] { 0, 1, 2, 3, 4, 5 });

            TryCastUnsafe<int>(new object[] { new object() });
            //Keep all zero to avoid bad memory
            TryCastUnsafe<object>(new long[6]);
        }
    }
}
```

**Comment by jkotas** [comment]
`Unsafe.As` skips *all* checks since it's unsafe, If you use it incorrectly such as to cast `long[]` to `object[]`, you can get all sorts of hard to trace down problems, e.g. intermittent crashes or data corruptions.
