### ISSUE TITLE
Aop aspect Technology Addition？

### ISSUE THREAD

**Issue by dayAndnight2018** [dotnet/corefx#38533]
Is there any official intention to add Spring Aspect-like AOP technology? It is undeniable that the middleware pipeline provided by Microsoft provides great convenience for software design, but Aop technology can provide more flexibility and aspect programming ideas.Pray for officials to consider joining Aop technology into .Net Core.

**Comment by scalablecory** [comment]
There are no issues that I know of discussing this; do you have something in mind?

**Comment by dayAndnight2018** [comment]
> There are no issues that I know of discussing this; do you have something in mind?

Something just like AspectCore Framework , see more at https://github.com/aspectcore

**Comment by stephentoub** [comment]
Closing as a dup of https://github.com/dotnet/corefx/issues/31336. Thanks.
