### ISSUE TITLE
Binaries should enable the compiler control guard feature (CFG) at build time

### ISSUE THREAD

**Issue by vonders** [dotnet/corefx#38545]
# Platform

clrcompression.dll 

# Author or host

Host

# Version

latest master 

# Issue

Control flow guard is not enabled in release mode, which is a vulnerability. In clrcompression.dll 

[binSkim] error BA2008: EnableControlFlowGuard : Binaries should enable the compiler control guard feature (CFG) at build time

**Comment by ericstj** [comment]
We should look into our native build scripts to make sure they set this flag.

**Comment by danmosemsft** [comment]
Maybe check coreclr as well (I assume it's just grepping the build log)?

**Comment by jkotas** [comment]
This is about running the https://github.com/Microsoft/binskim tool on the binaries produced by the build. CoreCLR was fine last time I have checked.

**Comment by wtgodbe** [comment]
I was not able to reproduce this error with the latest 3.0.0 bits of CoreFx. Running `.\BinSkim.exe analyze corefx\artifacts\bin\native\netcoreapp-Windows_NT-Debug-x64\*.dll` succeeded without error. @vonders can you comment on where you got the `clrcompression.dll` that you analyzed?

**Comment by wtgodbe** [comment]
Specifically, I see the following when running with `--verbose`:

> E:\code\corefx\artifacts\bin\native\netcoreapp-Windows_NT-Debug-x64\clrcompression.dll: pass BA2008: 'clrcompression.dll' enables the control flow guard mitigation. As a result, the operating system will force an application to close if an attacker is able to redirect execution in the component to an unexpected location.

**Comment by wtgodbe** [comment]
I see the same when building with `Release` configuration

**Comment by vonders** [comment]
ok thanks for checking, I am on netcore 6.2.2 will try with latest

**Comment by wtgodbe** [comment]
@tommcdon `netcore 6.2.2.` sounds like UWP, could this be a servicing issue for UWP?

**Comment by tommcdon** [comment]
@wtgodbe CoreCLR UWP 6.2 is based off of the release/2.1 tree.  Is CFG being enabled in 2.1 servicing?

**Comment by wtgodbe** [comment]
I'll check

**Comment by wtgodbe** [comment]
release/2.1 appears fine as well:

> E:\code\corefx\bin\Windows_NT.x64.Release\native\clrcompression.dll: pass BA2008: 'clrcompression.dll' enables the control flow guard mitigation. As a result, the operating system will force an application to close if an attacker is able to redirect execution in the component to an unexpected location.

**Comment by ericstj** [comment]
Double check the AOT-specific clrcompression.dll.  There should be a separate '-aot' folder with that in it.

**Comment by wtgodbe** [comment]
> E:\code\corefx\bin\Windows_NT.x64.Release\native_aot\clrcompression.dll: pass BA2008: 'clrcompression.dll' enables the control flow guard mitigation. As a result, the operating system will force an application to close if an attacker is able to redirect execution in the component to an unexpected location.

Looks like we're good there as well

**Comment by ericstj** [comment]
Ok, recommend we close this and reopen if we get some more specific pointer on the exact files / branch that have issue.  @vonders if you can repro please let us know the exact file and where you got it from that exhibits the problem.

**Comment by vonders** [comment]
thankyou for checking. Will do
