### ISSUE TITLE
System.Text.Json.Serialization.JsonSerializer doesnt work with class members

### ISSUE THREAD

**Issue by mshobohm** [dotnet/corefx#38540]
System.Text.Json.Serialization doesnt work with class members:
using System;
using System.Text.Json.Serialization;

namespace json.prep
{
    class Program
    {
        public class Product
        {
            public String Name; /*works only with:  { get; set; } */
        }
        static void Main(string[] args)
        {
            Product product1 = new Product
            {
                Name = "Product 1",
            };

            string json;

            var options = new JsonSerializerOptions
            {
                WriteIndented = true,
            };

            json = JsonSerializer.ToString<Product>(product1, options);
            Console.WriteLine(json);
            Console.ReadKey();

        }
    }
}
[Output was 
{}, expected
{
  "Name": "Product 1"
}

**Comment by Dreamescaper** [comment]
Probably duplicate:
https://github.com/dotnet/corefx/issues/36505

**Comment by ahsonkhan** [comment]
Fields are currently not supported and as @Dreamescaper mentioned, this is a duplicate issue. Hence, closing.
