### ISSUE TITLE
700+ OSX tests are failing in rolling builds

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#38553]
https://dev.azure.com/dnceng/public/_build/results?buildId=224886&view=ms.vss-test-web.build-test-results-tab

cc @stephentoub @safern

**Comment by ViktorHofer** [comment]
This started to happen with @bartonjs's test matrix change: https://dev.azure.com/dnceng/public/_build/results?buildId=223117

**Comment by ViktorHofer** [comment]
@tarekgh can you please take a look at the failing globalization tests: https://dev.azure.com/dnceng/public/_build/results?buildId=224751&view=ms.vss-test-web.build-test-results-tab

**Comment by safern** [comment]
This is only happening in rolling builds because in PR Builds we're not running on macOS 10.14 -- in PR Builds we're running on macOS 10.13. This is only happening for macOS 10.14.

**Comment by ViktorHofer** [comment]
Yeah noticed that: https://github.com/dotnet/corefx/commit/dda4588873cde2740d15e32749ccfd13eb33db07#r33943915

**Comment by tarekgh** [comment]
@ViktorHofer @safern do you need me go and look fixing the globalization tests on OSX 10.14? I can try to upgrade to that and look at fixing those later today.

**Comment by ViktorHofer** [comment]
Yes that would be great. I think those two are the only ones failing. As soon as those are fixed we can enable 10.14 in PRs.

**Comment by tarekgh** [comment]
ok, will try that later today or Monday as I am in training.

**Comment by tarekgh** [comment]
@ViktorHofer cpuld you please tell what ICU version used in 10.14 and how did you get it there? you can find the version by  looking at the file path /usr/local/Cellar/icu4c

**Comment by ViktorHofer** [comment]
Seems you already got the info that you needed? I don't have direct access to any of these machines...

**Comment by tarekgh** [comment]
No problem. I was able to repro the issue on my local machine. that is how I validated the fix. please let me know if there is anything I can help with.

**Comment by ericstj** [comment]
Looks like the remaining failures are all in crypto.  @bartonjs are you looking at those?

**Comment by bartonjs** [comment]
@ericstj Some of the machines in that pool have OpenSSL, others don't.  The ones which don't fail, the ones which do pass.  Engineering is aware of the problem and hopefully working on it.  (#38498)

**Comment by ViktorHofer** [comment]
Seems like the original issue has been fixed - although I don't know why? Closing.
