### ISSUE TITLE
[System.Text.Json] Dictionary and Child Object bug 

### ISSUE THREAD

**Issue by IvanJosipovic** [dotnet/corefx#38565]
There appears to be bug in System.Text.Json related Dictionary and Child Objects.

The output is really bizzare. As output.Dict ends up getting a new entry that never existed before.
![image](https://user-images.githubusercontent.com/9521987/59538878-11785d80-8eb0-11e9-98af-c5cf3dda620c.png)

.Net Core: 3.0.100-preview6-012264
System.Text.Json: 4.6.0-preview6.19303.8

```
    public class Bug2
    {
        [Fact]
        public void Test()
        {
            var input = new Class1()
            {
                Test = "value1",
                Child = new Class2()
            };

            var output = JsonSerializer.Parse<Class1>(JsonSerializer.ToString(input, new JsonSerializerOptions { IgnoreNullValues = true }));

            Assert.True(output.Test == "value1");
            Assert.Null(output.Dict);
            Assert.NotNull(output.Child);
            Assert.Null(output.Child.Dict);
            Assert.Null(output.Child.Test);
        }

        class Class1
        {
            public string Test { get; set; }
            public Dictionary<string, string> Dict { get; set; }
            public Class2 Child { get; set; }
        }

        class Class2
        {
            public string Test { get; set; }
            public Dictionary<string, string> Dict { get; set; }
        }
    }
```

**Comment by ahsonkhan** [comment]
cc @steveharter, @layomia

**Comment by ahsonkhan** [comment]
At first I thought the issue was you hadn't pass in `IgnoreNullValues` as a `JsonSerializerOptions` to the Parse API, but the issue persists even with that.

```C#
[Fact]
public static void Test()
{
    var input = new Class1()
    {
        Test = "value1",
        Child = new Class2()
    };

    Assert.Null(input.Dict);

    var str = JsonSerializer.ToString(input, new JsonSerializerOptions { IgnoreNullValues = true });

    Assert.Equal("{\"Test\":\"value1\",\"Dict\":null,\"Child\":{\"Dict\":null}}", str);

    Class1 output = JsonSerializer.Parse<Class1>(str, new JsonSerializerOptions { IgnoreNullValues = true });

    Assert.True(output.Test == "value1");
    Assert.Null(output.Dict);   // Fails
    Assert.NotNull(output.Child);   // Fails
    Assert.Null(output.Child.Dict);
    Assert.Null(output.Child.Test);
}
```

**Comment by pgovind** [comment]
Just FYI, I'm debugging something else in this space, so if I find the fix and a fix, I'll put it up

**Comment by pgovind** [comment]
More info: If I change `Dict` defined in Class2 to `Dict2`, the test still fails, but `output.Dict` now contains the key `Dict2`. 
I've also narrowed down the issue further. After we parse \"Dict\":null, we parse "Child", but `readStack.CurrentState.IsProcessingDictionary` still returns true, so we mess up everything after that.

**Comment by tannergooding** [comment]
I root caused the same and should have a fix up shortly. Just confirming the best route with Steve now.

**Comment by pgovind** [comment]
@steveharter : Before I start trying to fix this, do you have suggestions/pointers on where/how to fix this?
