### ISSUE TITLE
Improve API diff to show "where T : notnull"

### ISSUE THREAD

**Issue by GSPP** [dotnet/corefx#38571]
In https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/api-diff/preview6/3.0-preview6_System.Collections.Generic.md there is a weird looking constraint `where TKey : object`. Confused at what this was I looked at the source:

https://github.com/dotnet/corefx/blob/5fa3d3b8f89302202091993681391c9b356755a7/src/Common/src/CoreLib/System/Collections/Generic/IDictionary.cs#L14

It really is `where TKey : notnull`. The tool that generates these API diffs should be improved.

**Comment by stephentoub** [comment]
It actually was `: object`. It was only just changed this week to `: notnull`.
