### ISSUE TITLE
Unused parameters for custom test error messages

### ISSUE THREAD

**Issue by DAXaholic** [dotnet/corefx#38575]
There are a couple of tests which pass custom test error messages to a helper method but those messages are not used.
At first glance it seems most of these cases were introduced with commit ab1743b4 

In the example below the message is passed to `EnsureOperationCanceledExceptionThrown` but never used within that helper method:

https://github.com/dotnet/corefx/blob/ab1743b45213e88295a38e2bf9d80ded09058b18/src/System.Collections.Concurrent/tests/BlockingCollectionCancellationTests.cs#L74-L76

https://github.com/dotnet/corefx/blob/ab1743b45213e88295a38e2bf9d80ded09058b18/src/System.Collections.Concurrent/tests/BlockingCollectionCancellationTests.cs#L163-L168

There are more examples like this (e.g. in [BarrierCancellationTests.cs](https://github.com/dotnet/corefx/blob/master/src/System.Threading/tests/BarrierCancellationTests.cs#L49-L52))

IMHO the current state is a bit confusing so I suggest to either remove those unused parameters altogether or modify the helper methods to use the passed messages.
The latter approach may bring some parts back to a state which conflicts with the 'spirit' of ab1743b4, therefore I would ask for your opinions about it.

**Comment by Clockwork-Muse** [comment]
As the perpetrator, I feel we should remove the parameters.
Were you wanting to submit a PR?

**Comment by DAXaholic** [comment]
Yup, I'd go through the tests and remove those unused parameters.

**Comment by danmosemsft** [comment]
OK, assigned! thanks.
