### ISSUE TITLE
Why trigger event "AssemblyResolve"?

### ISSUE THREAD

**Issue by newpost** [dotnet/corefx#38583]
```
class Program
    {
        static void Main(string[] args)
        {
            Test();
            Console.WriteLine("Hello World!");
        }

        private static Assembly CurrentDomain_AssemblyResolve(object sender, ResolveEventArgs args)
        {
            Console.WriteLine(args.Name);//System.Collections.Concurrent.resources, Version=4.0.14.0, Culture=zh-CN, PublicKeyToken=b03f5f7f11d50a3a
            return null;
        }

        public static void Test()
        {
            AppDomain.CurrentDomain.AssemblyResolve += CurrentDomain_AssemblyResolve;
            IDictionary<string, string> dic = new ConcurrentDictionary<string, string>();
            dic.Add("key", "value");
            dic.Add("key", "value");
        }
    }
````

**Comment by ViktorHofer** [comment]
Is your question why trigger `AssemblyResolve` for satellite assemblies?

**Comment by newpost** [comment]
@ViktorHofer yes

**Comment by tarekgh** [comment]
I believe this is expected. When accessing any resources, the loader will try to find first if there is a a satellite assembly matching the UI culture. I believe you are running on Chinese platform. if the loader couldn't find the satellite assembly, it'll fire the event giving a chance to the event subscriber to react to that. 

@sdmaclea please correct me if what I mentioned in not correct.

**Comment by newpost** [comment]
why the loader couldn't find the satellite assembly？when culture is en-us, the loader find it,But culture is
zh-CN，not .

Regards,

________________________________
发件人: Tarek Mahmoud Sayed <notifications@github.com>
发送时间: Tuesday, June 18, 2019 3:32:47 AM
收件人: dotnet/corefx
抄送: niceguy; Author
主题: Re: [dotnet/corefx] Why trigger event "AssemblyResolve"? (#38583)


I believe this is expected. When accessing any resources, the loader will try to find first if there is a a satellite assembly matching the UI culture. I believe you are running on Chinese platform. if the loader couldn't find the satellite assembly, it'll fire the event giving a chance to the event subscriber to react to that.

@sdmaclea<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsdmaclea&data=02%7C01%7C%7C0fc6da6bd54e486c7a0e08d6f35a9454%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636963967697254655&sdata=awplsZqpT%2Frxr1kHDuu%2F4gVXdlknCbe%2Byv%2FJykfmU8w%3D&reserved=0> please correct me if what I mentioned in not correct.

―

**Comment by tarekgh** [comment]
> why the loader couldn't find the satellite assembly？when culture is en-us, the loader find it,But culture is zh-CN，not .

Because the framework doesn't carry satellite assemblies at all. in case of en-US, it will just use the resources inside the main assembly. 

I am going to close this issue, but feel free to send any more questions you have. Thanks for your report.

**Comment by sdmaclea** [comment]
@tarekgh Is correct.

@newpost I believe the second call to  `dic.Add("key", "value");` will trigger an exception. 

The exception will contain an error message. The runtime is trying to translate the message to your UI culture. The `AssemblyResolve` event is firing when the translation doesn't exist for your UI culture. It allows your handler to locate the satellite assembly.

If your handler returns `null`. It then will fallback to the parent culture and try again. Ultimately if it fails to find a culture specific satellite assembly it will return the language neutral message (English).
