### ISSUE TITLE
System.Text.Json Cannot Run Tests from Visual Studio

### ISSUE THREAD

**Issue by danstur** [dotnet/corefx#38587]
After building the System.Text.Json solution via build.cmd (or Visual Studio) the resulting assemblies are put into a `$(ArtifactsBinDir)$(TestProjectName)/netcoreapp-$(ConfigurationGroup)/` directory. 

The working directory of the System.Text.Json.Tests project under Debug is set to `$(ArtifactsBinDir)$(TestProjectName)/netcoreapp-$(_bc_OSGroup)-$(ConfigurationGroup)-$(ArchGroup)/` this causes an error when trying to execute the tests with the following message box:
```
---------------------------
Microsoft Visual Studio
---------------------------
The working directory 'E:\code\corefx\artifacts\bin\System.Text.Json.Tests\netcoreapp-Windows_NT-Debug-x64\' specified in the '.NET Core xUnit Console' debug profile does not exist.
---------------------------
OK   
---------------------------
```

Running the same tests via `dotnet msbuild /t:rebuildandtest` locates the tests correctly.

Am I doing something wrong or is this a mistake in the test configuration?

**Comment by scalablecory** [comment]
Running corefx tests via VS is not supported. The best way to debug in VS right now is to launch via command line and attach a debugger.

**Comment by danstur** [comment]
@scalablecory If running tests via Visual Studio is not supported, someone should remove the whole section [Build, Run and Debug tests using Visual Studio](https://github.com/dotnet/corefx/wiki/Build-and-run-tests#build-run-and-debug-tests-using-visual-studio) in the contributor section.

Given that it also works perfectly fine by simply fixing the incorrect path *and* is documented extensively, this seems a weird position.

**Comment by ericstj** [comment]
Running tests in VS via F5 is supported.  Did you select a configuration in the configuration manager that matches the one you want to use (EG: netcroreapp-Debug).  /cc @ViktorHofer

**Comment by ViktorHofer** [comment]
@ericstj this seems to happening because I stopped binplacing the test assemblies. I probably forgot to update the path in the launchSettings.json template. What is the correct msbuild property that exposes the  configuration string where the binaries are copied to? `$(BuildConfiguration)`?

**Comment by ericstj** [comment]
Don't construct the path on your own, use the same exact property used when copying the output.  I imagine that is OuputPath (or TargetDir or OutDir).

**Comment by ahsonkhan** [comment]
The default configuration is netcoreapp-Debug. I have been able to debug in VS just fine (using F5).

![image](https://user-images.githubusercontent.com/6527137/59659906-1b25ed80-915c-11e9-81a9-31640a04e0d4.png)

**Comment by ViktorHofer** [comment]
This should now work again. Thanks for reporting!
