### ISSUE TITLE
[System.Text.Json] merging two json structures

### ISSUE THREAD

**Issue by axm** [dotnet/corefx#38589]
I ran into this use case recently and I was unable to find a solution. 

On one hand I read the contents of a file, then I obtained the JSON representaiton of that content with

```
var document = JsonDocument.Parse(fileContent);
```

Now I have access to all that data. The second thing I did was build a custom JSON object with the `Utf8JsonWriter`.

**Question:** how can I integrate the latter object into the former (`document`)? I want to create a property in `document` (maybe nested quite deeply) and set the value of that property to the object that I build with `Utf8JsonWriter`.

**Comment by ahsonkhan** [comment]
The `JsonDocument`, in its v1 implementation, is read-only (i.e. it is not modifiable).

One thing you could do as a workaround, via the `Utf8JsonWriter`, is enumerate all the tokens of the `JsonDocument`, and write them out to the writer (including inserting the custom JSON object you have). You can then pass the output of the `Utf8JsonWriter` to `JsonDocument.Parse` to get a `JsonDocument` containing your whole JSON.

Maybe something like this (note: this isn't fully tested, just a sample):
```C#
[Fact]
public static void ModifyJsonDocument()
{
    string originalJson = "{\"hi\": 1}";
    JsonDocument doc = JsonDocument.Parse(originalJson);

    JsonDocument newDoc = AddJsonData(doc, doc);

    Assert.Equal("{\"hi\":1,\"mySubElement\":{\"hi\":1}}", newDoc.RootElement.ToString());
}

private static JsonDocument AddJsonData(JsonDocument original, JsonDocument subOject)
{
    JsonElement element = original.RootElement;
    var abw = new ArrayBufferWriter<byte>();
    using var writer = new Utf8JsonWriter(abw);

    writer.WriteStartObject();
    foreach(JsonProperty properties in element.EnumerateObject())
    {
        properties.Value.WriteProperty(properties.Name, writer);
    }
    JsonElement subElement = subOject.RootElement;
    subElement.WriteProperty("mySubElement", writer);
    writer.WriteEndObject();

    writer.Flush();

    return JsonDocument.Parse(abw.WrittenMemory);
}
```

**Comment by axm** [comment]
Thanks @ahsonkhan that works.

Are there any plans to introduce this functionality out of the box in 1.1 or above?

**Comment by ahsonkhan** [comment]
> Are there any plans to introduce this functionality out of the box in 1.1 or above?

When you say 1.1 or above, what do you mean? If you mean the next version of .NET Core, we will likely add support for this in the next release of .NET Core (after 3.0).
