### ISSUE TITLE
Is DPI broken in 3.0.100-preview6-012264?

### ISSUE THREAD

**Issue by markzielinski** [dotnet/corefx#38580]
I just updated from 3.0.100-preview5-011568 to 3.0.100-preview6-012264 and it looks like there were some changes made to DPI.

I checked the release notes and didn't see any changes documented for DPI, however after updating to Preview 6 my WPF application now looks huge.    

My display resolution is 2560 x 1440 with the scale set to the recommended 125%.

**Comment by huoyaoyuan** [comment]
I think it's a fix in Preview 6, because my WPF application looks small (like 100% dpi) in Preview 5.

**Comment by ericstj** [comment]
Closing in favor of https://github.com/dotnet/wpf/issues/976
