### ISSUE TITLE
Pretty please: `JsonTokenType` to `[Flags]`

### ISSUE THREAD

**Issue by mqudsi** [dotnet/corefx#38590]
Before `System.Text.Json` finalizes, would it be possible to change the definition of `JsonTokenType` (and maybe others) to make certain operations on top of `Utf8JsonReader` more efficient?

This is what I had in mind:

```csharp
[Flags]
public enum JsonTokenType : byte
{
    None = 0,
    StartObject = 1 << 0,
    EndObject = 1 << 1,
    StartArray = 1 << 2,
    EndArray = 1 << 3,
    PropertyName = 1 << 4,
    String = 1 << 5,
    Number = 1 << 6,
    True = 1 << 7,
    False = 1 << 8,
    Null = 1 << 9,
    Comment = 1 << 10,

    // These will make things more efficient.
    // You don't even have to define them if you feel they're too subjective,
    // library writers can define them on their end by virtue of `JsonTokenType`
    // members having power-of-two values.
    Boolean = True | False,
    Literal = String | Number | Boolean | Null,
    // etc.
}
```

As mentioned, there's no need to actually provide the definitions for `Boolean`, `NestedStart`, etc. as a dev can easily define them once on their end (although having them in the library means they can be kept in-sync), so that usages such as "handle this `ValueSpan` if it is a boolean" can be written as `(reader.TokenType & Boolean) != JsonTokenType.None` rather than `reader.TokenType == JsonTokenType.True || reader.TokenType == JsonTokenType.False`.

(`JsonValueType` can also use this to get `JsonTokenType.Boolean`)

**Comment by scalablecory** [comment]
Doing this will trade one efficiency for another: you can no longer use a jump table to process the enum.

**Comment by mqudsi** [comment]
That's a good point. I'm assuming the reason for separate enum states for `True` and `False` is for performance reasons (guessing: it's no additional cost to determine which of the two up front and saves a conditional afterwards)?

**Comment by ahsonkhan** [comment]
> make certain operations on top of `Utf8JsonReader` more efficient?

Can you please show a code sample you had in mind, where such a change would make the code more efficient? If you have some more concrete perf numbers (or a benchmark that I can run), that would help motivate this change.

**Comment by ahsonkhan** [comment]
@mqudsi, do you have any perf numbers or a benchmark in mind?

**Comment by mqudsi** [comment]
Unfortunately the type of optimizations I'm talking about are going to be somewhat machine dependent. Haswell+ has hugely improved indirection support so things like jump tables don't have as bad of a hit on newer processors; on my end this isn't worth pursuing.

**Comment by terrajobst** [comment]
We also reviewed this today and think we don't want to do because it's adding a lot of complexity.

However, @ahsonkhan will change the the value `Comment` so we can do range checks instead of jump tables.

**Comment by ahsonkhan** [comment]
> Unfortunately the type of optimizations I'm talking about are going to be somewhat machine dependent. 

@mqudsi, also, the enum is backed by a byte and we have more than 8 enum values. Making it a flag wouldn't be feasible without also increasing the enum size to something like an int32, which does increase the struct size of anything that has TokenType as a field (for instance the `Utf8JsonReader`).
