### ISSUE TITLE
Test failure: System.Runtime.Extensions.Tests/System.Tests.AppDomainTests/MonitoringIsEnabled

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#38595]
Test `System.Tests.AppDomainTests/MonitoringIsEnabled` has failed.

Message :
```
Assert.InRange() Failure
Range:  (1 - 9223372036854775807)
Actual: 0
```

Stack Trace :
```
at System.Tests.AppDomainTests.MonitoringIsEnabled() in /_/src/System.Runtime.Extensions/tests/System/AppDomainTests.cs:line 396
```

Build: -[20190616.8](https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190616.8)(Master)

Failing configurations:

- Windows.10.Amd64.ServerRS5.Open-x64-Release

Details:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190616.8/workItem/System.Runtime.Extensions.Tests/analysis/xunit/System.Tests.AppDomainTests~2FMonitoringIsEnabled

**Comment by ViktorHofer** [comment]
@stephentoub looking at the test code https://github.com/dotnet/corefx/blob/f5399d9d24536697a3bc36339e13ba085fc28938/src/System.Runtime.Extensions/tests/System/AppDomainTests.cs#L388 I'm unsure if this shouldn't be a remote invocation?

**Comment by stephentoub** [comment]
> I'm unsure if this shouldn't be a remote invocation?

It shouldn't need to be.

@Maoni0, this failure suggests that:
```C#
GCMemoryInfo mi = GC.GetGCMemoryInfo();
return mi.HeapSizeBytes - mi.FragmentedBytes;
```
returned `0`.  In what situation would that occur?  Thanks.

**Comment by Maoni0** [comment]
if there was no accounting errors at all, we should see at least 24 bytes difference but I know there are some corner cases where the accounting is a little off. I had some changes that included fixes related to the accounting; unless this is easy to repro I would probably just wait till those changes are in (which might be a while).

**Comment by stephentoub** [comment]
Ok, thanks.

**Comment by stephentoub** [comment]
Failed again here, on the same configuration, same error.
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38635~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190618.6/workItem/System.Runtime.Extensions.Tests/analysis/xunit/System.Tests.AppDomainTests~2FMonitoringIsEnabled

**Comment by ViktorHofer** [comment]
ServerRS5 (netcoreapp) != ClientRS5 (uap)

**Comment by ViktorHofer** [comment]
See https://github.com/dotnet/corefx/blob/master/eng/pipelines/windows.yml#L118

**Comment by stephentoub** [comment]
@ViktorHofer, then why does a) this show up in the UWP CoreCLR leg:
![image](https://user-images.githubusercontent.com/2642209/59693134-64099080-91b4-11e9-8056-0ed61f5eee83.png)
and b) the infrastructure logs show it as being UWP:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38635~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190618.6/workItem/System.Runtime.Extensions.Tests/wilogs
e.g.
```
C:\dotnetbuild\work\97830540-9b0c-486d-8a75-5ddaeb4a0077\Work\40102fcf-d967-4b46-aecd-02366899c8c5\Exec>XUnitRunnerUap System.Runtime.Extensions.Tests.dll -xml "C:\Users\runner\AppData\Local\Packages\5cd54353-3ed7-4a6e-a72f-db349f28867c_v52bfwc2c21ha\LocalState\System.Runtime.Extensions.Tests.xml" -nologo -nocolor -notrait category=nonuaptests -notrait category=nonwindowstests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
```

**Comment by ViktorHofer** [comment]
What I'm saying is that this failure (clientrs5 - uwp) is not on the same configuration as the failure in the initial post (serverrs5 - netcoreapp).

**Comment by stephentoub** [comment]
> What I'm saying is that this failure (clientrs5 - uwp) is not on the same configuration as the failure in the initial post (serverrs5 - netcoreapp).

Ah, ok, thanks.
