### ISSUE TITLE
CollectionViewSource Class in namespace System.Windows.Data

### ISSUE THREAD

**Issue by JBerg60** [dotnet/corefx#38594]
The documentation says that the collectionviewsource class is in the framework since preview 5:

https://docs.microsoft.com/de-de/dotnet/api/system.windows.data.collectionviewsource?view=netframework-4.8

However, I cannot find the class, nor the source code.

any pointers?

**Comment by Wraith2** [comment]
You're looking in the wrong repository. you need dotnet/wpf
https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/CollectionViewSource.cs
