### ISSUE TITLE
decimal.ToSingle needs to have its logic implemented independently from decimal.ToDouble

### ISSUE THREAD

**Issue by tannergooding** [dotnet/corefx#38602]
`decimal.ToSingle` is currently implemented by calling `DecCalc.VarR4FromDec`, which in turn just does `return (float)VarR8FromDec(in value)`. This is incorrect as it does not produce the nearest representable `single-precision floating-point` result. It instead computes the nearest representable `double-precision floating-point` result and then rounds that to the nearest representable `single-precision floating-point`.

An example of this is called out here: https://github.com/dotnet/corefx/issues/38588#issuecomment-502735876.

Namely, `4.2` as the nearest representable double is `4.20000000000000017763568394002504646778106689453125` and the nearest representable single is `4.19999980926513671875`.

However, if you first convert to the nearest representable double and then downcast that to single, you instead get `4.200000286102294921875`.

**Comment by tannergooding** [comment]
CC. @pentp.

Any concerns with fixing this?

**Comment by pentp** [comment]
Only concern could be compatibility with earlier versions, but since this is a correctness bug it should be fine to fix in 3.0.

**Comment by tannergooding** [comment]
This was actually due to https://github.com/dotnet/coreclr/issues/25132 and everything looks to be fine.

There might still be a minor perf improvement by converting directly to float, but I don't believe there is a correctness issue here.
