### ISSUE TITLE
Cloning SecurityBindingElement misses EnableUnsecuredResponse 

### ISSUE THREAD

**Issue by maheshnlrb** [dotnet/corefx#38609]
The constructor of  SecurityBindingElement that takes elementToBeCloned does not set the EnableUnsecuredResponse to what's set on source.

**Comment by davidsh** [comment]
I think you're referring to [System.ServiceModel.Channels.SecurityBindingElement](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.channels.securitybindingelement?view=netframework-4.8).

That class is part of WCF.  Please open an issue here for that: https://github.com/dotnet/wcf/issues
