### ISSUE TITLE
System.Net.Security tests are intermittently hanging on Linux

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#38618]
Test was running in privileged docker container on Linux in a loop for a longer period of time (host and container are both on ubuntu).

Here are some stacks to look at (this contains eestack, dumpasync -stacks, dumpasync -stacks -fields): https://gist.github.com/krwq/f7bb696c941e88a8a54e083c20a3d905

Basically some combination of multiple tests seem to be causing the hang (hang: no observable activity for 4min)
- ClientAsyncAuthenticateTest
- ServerRequireEncryptionTest
- SslStreamStreamToStreamTest* (multiple tests from this group)
- CertificateValidationClientServer
- ServerAllowNoEncryptionTest
- ParameterValidationTest
- SslStreamAlertsTest
- SslStreamCredentialCacheTest
- ServerAsyncAuthenticateTest
- ServerNoEncryptionTest

possibly I have missed something from the log.

cc: @ViktorHofer - have you seen any intermittent System.Net.Security issues on the CI recently? I'm wondering if this is specific to my openssl installation or a more generic issue

**Comment by ViktorHofer** [comment]
I don't think I've seen failures on System.Net.Security in CI yet.

**Comment by krwq** [comment]
another one: https://gist.github.com/krwq/48ae98b4ed4a2d44f8eb6186250c8f6a

**Comment by krwq** [comment]
one of the recent fixes must have fixed this, previously I was getting repro relatively frequently, now running for the last couple of days and no repro. Closing.
