### ISSUE TITLE
System.Text.Json JsonSerializer API JsonSerializerOptions conflict/priority

### ISSUE THREAD

**Issue by mqudsi** [dotnet/corefx#38612]
Some of the overloads for `JsonSerializer.ReadValue` take both a `Utf8JsonReader` and an (optional) `JsonSerializerOptions` structure as parameters. However, a `Utf8JsonReader` is already associated with an existing `JsonSerializerOptions` object via its `JsonReaderState`, which can be explicitly initialized with a custom `JsonSerializerOptions`.

From an API UX perspective, this is vague and confusing. If you pass in a `Utf8JsonReader` created with one set of options via the `JsonReaderState` constructor parameter and also pass in a second set of (differing) options via the optional `JsonSerializerOptions` parameter, which will win out?

Additionally, it means that there is extra unused state being passed around (copied, actually) and the heap allocations to go with it. Of course the biggest issue is the potential for underlying bugs in the STJ implementation or in external code calling into it.

Given that `Utf8JsonReader` is a low-level instrument that most users won't be interacting with at all, and given that it's intended to be re-entrant/re-initialized ([barring some issues](https://github.com/dotnet/corefx/issues/38591)), I suggest eliminating the option of specifying an additional `JsonSerializerOptions` to `JsonSerializer.Parse()` and friends when using an overload that explicitly passes in a pre-existing `Utf8JsonReader`. If changing/overriding the settings is needed, developers delving this far into the STJ API would presumably be aware that they can create a new `Utf8JsonReader` with the options they need, eliminating any confusion here.

If it's absolutely necessary to override the settings, then again eliminating that specific overload but exposing the `JsonSerializerOptions` as a property of the `JsonSerializer` object means it's at least clearer which of the two `JsonSerializerOptions` instances has priority (the latter assigned). Depending on why it's absolutely necessary, it could also just be made a private (or protected, if it's not a sealed class) overload.

**Comment by ahsonkhan** [comment]
This is a good question. Thanks for bringing it up :)

> If you pass in a `Utf8JsonReader` created with one set of options via the `JsonReaderState` constructor parameter and also pass in a second set of (differing) options via the optional `JsonSerializerOptions` parameter, which will win out?

We had thought about this during the API design. The options with which the `Utf8JsonReader` was constructed would be honored over the `JsonSerializerOptions` being passed in. This is something we document to help clarify it a bit, but yes, it does cause some friction from the user's point of view.

Presumably, usage of the the JsonSerializer and Reader/Writer interop APIs are a more advance scenario (and hence most users wouldn't have to deal with understanding this additional complexity).

https://github.com/dotnet/corefx/blob/2e6661d4cceeff2549b0299ec54e9f3b34c09b20/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Utf8JsonReader.cs#L45-L48

> However, a `Utf8JsonReader` is already associated with an existing `JsonSerializerOptions` object via its `JsonReaderState`, which can be explicitly initialized with a custom `JsonSerializerOptions`.

Note, this is not entirely accurate. The `Utf8JsonReader` has `JsonReaderOptions` (not `JsonSerializerOptions`), but I understand the spirit of your concern.

> Additionally, it means that there is extra unused state being passed around (copied, actually) and the heap allocations to go with it.

The `JsonReaderOptions` is a struct, so we don't have the additional heap allocation.

> Given that `Utf8JsonReader` is a low-level instrument that most users won't be interacting with at all, and given that it's intended to be re-entrant/re-initialized ([barring some issues](https://github.com/dotnet/corefx/issues/38591)), I suggest eliminating the option of specifying an additional `JsonSerializerOptions` to `JsonSerializer.Parse()` and friends when using an overload that explicitly passes in a pre-existing `Utf8JsonReader`.

Part of the motivating concern for adding such overloads was for implementers of Converters. Unfortunately, they need some way to pass back the JsonSerializerOptions to the serializer in their implementation.

Thanks for the feedback and perspective. It is really valuable! I will think about this some more and see where we can land given some of the other usages/requirements. If you have any other suggestions (given some of the context/info I provided above), do let me know.

cc @steveharter, @rynowak, @JamesNK

**Comment by mqudsi** [comment]
Thanks for the additional context (especially re converters). I'll keep that in mind as I experiment some more with STJ and let you know!

**Comment by ahsonkhan** [comment]
@mqudsi, is there anything else left about this issue?

**Comment by mqudsi** [comment]
Nope, I think we can close this one out. Thank you!
