### ISSUE TITLE
Native support for deserializing string to primitive type?

### ISSUE THREAD

**Issue by mqudsi** [dotnet/corefx#38616]
The Newtonsoft JSON library is able to parse 

```json
{
    "Number": "42"
}
```

to a C# structure

```csharp
struct Foo
{
    int Number { get; set; }
}
```

However

```csharp
var foo = JsonSerializer.Parse<Foo>(@"{ ""Number"": ""42"" }");
```

throws an exception as `Foo.Number` is an integer but the JSON equivalent is technically a string.  

This isn't a bug per se as STJ is correct, but it's a very common scenario as type safety is an afterthought in the web world where much of JSON comes from. Are there any plans to support this? In terms of performance, it could be as simple as advancing the `Utf8JsonReader` by a single byte when the current token is `JsonTokenType.String` but the expected type is any other primitive, and trying the read from there (then advancing past the closing `"` when done, obviously).

**Comment by ahsonkhan** [comment]
This is a known limitation of the S.T.Json APIs and is by design. One approach to resolve this on the `JsonSerializer` would be for the user to implement their own converter which will allow strings to be parsed as primitive types.

**Comment by mqudsi** [comment]
Thanks!

**Comment by ahsonkhan** [comment]
To add some more context/clarification, the S.T.Json APIs avoid any type coercion or type inference/guessing (especially by default), which is why it is "by design".

Thanks for the question, @mqudsi :)
