### ISSUE TITLE
AssemblyNameTests.FullName accepts 'extended' name as well as 'expected'

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/corefx#38615]
As part of fixing the test in Mono (https://github.com/mono/mono/issues/15073), I noticed that Core seems to just return the 'expected' string. Why is the 'extended' one an option in the test? Checking the history just leads me back to the initial commit, which this was still present in. If this behavior is intended, the reason should probably be documented, as from an outside perspective it seems confusing.

https://github.com/dotnet/corefx/blob/2e6661d4cceeff2549b0299ec54e9f3b34c09b20/src/System.Reflection/tests/AssemblyNameTests.cs#L305

**Comment by jkotas** [comment]
This means that at some point there was a variant of the runtime that returned the extended string.

A PR to make the test more strict is welcomed.

**Comment by CoffeeFlux** [comment]
I'll submit one later today :)
