### ISSUE TITLE
Add support for copying from Vector<T> to Span<T>

### ISSUE THREAD

**Issue by surban** [dotnet/corefx#38633]
Currently `Vector<T>` can be constructed from a `Span<T>`, but writing the result of a vectorized operation into a `Span<T>` is impossible, since the `Vector<T>.CopyTo` method lacks the necessary overload.

# Rationale and usage

The following code computes the sum of two arrays using SIMD operations and stores it in the `trgt` parameter.

```C#
        static void VectorizedArrayAdd(double[] trgt, double[] x, double[] y)
        {
            Debug.Assert(x.Length == y.Length && x.Length == trgt.Length);
            Debug.Assert(x.Length % Vector<double>.Count == 0);

            for (int i=0; i < x.Length; i += Vector<double>.Count)
            {
                var xv = new Vector<double>(x, i);
                var yv = new Vector<double>(y, i);
                var tv = xv + yv;
                tv.CopyTo(trgt, i);
            }
        }
```

Converting this code to accept `Span<double>` instead of `double[]` makes sense, for example to support operation on slices of arrays or on external memory. A first conversion attempt leads to the following code.

```C#
        static void VectorizedSpanAdd(Span<double> trgt, Span<double> x, Span<double> y)
        {
            Debug.Assert(x.Length == y.Length && x.Length == trgt.Length);
            Debug.Assert(x.Length % Vector<double>.Count == 0);

            for (int i = 0; i < x.Length; i += Vector<double>.Count)
            {
                var xs = x.Slice(i, Vector<double>.Count);
                var xv = new Vector<double>(xs);

                var ys = y.Slice(i, Vector<double>.Count);
                var yv = new Vector<double>(ys);

                var tv = xv + yv;
                var ts = trgt.Slice(i, Vector<double>.Count);
                tv.CopyTo(ts); // ERROR: Argument 1: cannot convert from 'System.Span<double>' to 'double[]' 
            }
        }
```

However, this fails to compile since `Vector<double>.CopyTo(Span<double> x)` does not exist.

## Propsed API
Extend `Vector<T>` as follows.
```C#
public struct Vector<T> : IEquatable<System.Numerics.Vector<T>>, IFormattable where T : struct
{
    public void CopyTo(Span<T> destination);
}
```

## Details

- Support for constructing a `Vector<T>` from a `Span<T>` has been added in #26499, but without the ability to get the result back out into a `Span<T>` the usability of this feature is limited.

**Comment by scalablecory** [comment]
There's a standard feature for this already:

```c#
Span<byte> span;
Vector<byte> vector = MemoryMarshal.Cast<Vector<byte>, byte>(span);
```

**Comment by tannergooding** [comment]
We already added this in: <https://github.com/dotnet/coreclr/pull/23333>

**Comment by tannergooding** [comment]
It will be available in .NET Core 3.0 and should already be available in the latest public preview.
