### ISSUE TITLE
Add System.Runtime.InteropServices.ICustomMarshaler to the contract

### ISSUE THREAD

**Issue by jazzdelightsme** [dotnet/corefx#3863]
c.f. [coreclr #1767](https://github.com/dotnet/coreclr/issues/1767)

The ICustomMarshaler interface needs to be added to the contract so that people can use it.

**Comment by jasonwilliams200OK** [comment]
dup https://github.com/dotnet/corefx/issues/1346

**Comment by yizhang82** [comment]
Thanks @jazzdelightsme for opening this issue. I'm going to close this since this is a dup of #1346. We can take the discussion there.
