### ISSUE TITLE
Enable System.Diagnostics.Process.HandleCount property

### ISSUE THREAD

**Issue by pallavit** [dotnet/corefx#3865]

**Comment by stephentoub** [comment]
What's the driving desire behind exposing this?  I'm curious what decisions will be made based on the result.  We could implement this for Unix by trying to determine the number of open file descriptors, for example, but it's not clear what value that provides.

**Comment by pallavit** [comment]
Powershell team has asked us for this behavior. They use it in their get-process cmdlet to display the no. of handles in the process

PS C:\windows\system32> get-process -name wsmprovhost

Handles  NPM(K)    PM(K)      WS(K) VM(M)   CPU(s)     Id  SI ProcessName
-------  ------    -----      ----- -----   ------     --  -- -----------
    467      29    62904      48292 ...79     1.67  14732   0 wsmprovhost

Do you see any issue with exposing this property for this? I am yet to investigate whether this can be implemented x-plat, however, based on your response I am guessing it is possible :).

**Comment by stephentoub** [comment]
> I am yet to investigate whether this can be implemented x-plat, however, based on your response I am guessing it is possible :).

I mean, it's possible to return a number, but that number won't actually be the number of "handles", since "handles" don't exist on Unix.  We could make up something that we pretend is a handle, like a file descriptor, but it's really not the same thing and doesn't cover all of the same things that "handles" does on Windows.

**Comment by pallavit** [comment]
@stephentoub This was requested by the Powershell team mainly for feature consistency for windows. Now that I have more context on the cross-plat aspect, I would drive it accordingly. Thanks :)

**Comment by pallavit** [comment]
Since HandleCount is not cross-plat friendly, I will close this bug as won't fix since, we would most likely not add it to our library.
