### ISSUE TITLE
System.Text.Json wrongly complains about duplicate property names when one is ignored

### ISSUE THREAD

**Issue by mqudsi** [dotnet/corefx#38668]
A common "hack" used anytime you're working with convention-based serializers (so JSON converters or Entity Framework alike) is to create proxies as converters (I know there is converter support separately):

```cs
enum MyEnum {
	Case1 = 0,
	Case2 = 1,
}

struct Foo {
	[JsonIgnore]
	public MyEnum Bar { get; set; }	

	[JsonPropertyName("Bar")]
	public string BarString
	{
		get => Enum.GetName(typeof(MyEnum), MyEnum);
		set => value switch {
			"Case1" => MyEnum.Case1,
			"Case2" => MyEnum.Case2,
			_ => throw new Exception("Unknown value!"),
		}
	}
}
```

Attempting to (de)serialize this type throws an exception complaining about duplicate property names. Since `Foo.Bar` is ignored, `Foo.BarString` should be the only JSON property with the name "Bar".

Currently, it is necessary to also change the JSON property name of the original property:

```cs
struct Foo {
	[JsonIgnore]
	[JsonPropertyName("NotBar")]
	public MyEnum Bar { get; set; }	

	[JsonPropertyName("Bar")]
	public string MyEnumString
	{
		get => Enum.GetName(typeof(MyEnum), MyEnum);
		set => value switch {
			"Case1" => MyEnum.Case1,
			"Case2" => MyEnum.Case2,
			_ => throw new Exception("Unknown value!"),
		}
	}
}
```

This hack work in Entity Framework and NewtonSoft's JSON serializer, among others.

**Comment by ahsonkhan** [comment]
Good issue. @steveharter, how do such attributes/options compose?

**Comment by ahsonkhan** [comment]
She would verify that the ordering the attributes show up in the .NET POCO don't affect the end behavior.
