### ISSUE TITLE
error CS1069: The type name 'Icon' could not be found

### ISSUE THREAD

**Issue by onovotny** [dotnet/corefx#38682]
.NET Core Version: `3.0.100-preview7-012503`

Looks like a type `Icon` was moved to a new assembly, `System.Drawing.Common`, but that assembly isn't referenced by default by the SDK targets:

```
3>Utilities\FileHelper.cs(314,23,314,27): error CS1069: The type name 'Icon' could not be found in the namespace 'System.Drawing'. This type has been forwarded to assembly 'System.Drawing.Common, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' Consider adding a reference to that assembly.
```

**Comment by ericstj** [comment]
Icon has been in System.Drawing.Common since 2.0 https://apisof.net/catalog/System.Drawing.Icon

System.Drawing.Common has always been out of the base NETCoreApp shared framework (due to its native dependencies on Unix that aren't inbox: LibGDIPlus).

System.Drawing.Common is inbox in the Windows Desktop SDK.

Can you double check that something else isn't causing your missing dependency?  Perhaps you had a package that was bringing it in transitively before?

**Comment by onovotny** [comment]
This is a straight update from Preview 6, where it works, to the latest Preview 7, where the compile fails.

You can repro with the master: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer

It also does not only happen for me: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/716#issuecomment-502858425

**Comment by safern** [comment]
I just downloaded the latest SDK -- version: `3.0.100-preview7-012511` which contains the following winforms version:

```json
"framework": {
      "name": "Microsoft.WindowsDesktop.App",
      "version": "3.0.0-preview7-27819-03"
 }
```

and I was able to use `Icon` as part of my dummy App, compiled and ran fine. Could you confirm if you can still repro with that version of the SDK?

**Comment by campersau** [comment]
I just rechecked with dotnet `3.0.100-preview7-012511` and it still compiles with the same errors. https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/716#issuecomment-502858425

<details>
<summary>dotnet build output (german)</summary>

```
1>------ Erstellen gestartet: Projekt: Types, Konfiguration: Debug Any CPU ------
1>You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
1>C:\Program Files\dotnet\sdk\3.0.100-preview7-012511\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(340,5): warning NETSDK1107: Microsoft.NET.Sdk.WindowsDesktop is required to build Windows desktop applications. 'UseWpf' and 'UseWindowsForms' are not supported by the current SDK.
1>Types -> C:\dev_projects\NuGetPackageExplorer\Types\bin\Debug\netcoreapp3.0\NuGetPackageExplorer.Types.dll
1>Erstellen des Projekts Types.csproj beendet.
2>------ Erstellen gestartet: Projekt: Core, Konfiguration: Debug Any CPU ------
2>Core -> C:\dev_projects\NuGetPackageExplorer\Core\bin\Debug\netcoreapp3.0\Core.dll
3>------ Erstellen gestartet: Projekt: PackageViewModel, Konfiguration: Debug Any CPU ------
3>Types\MruItem.cs(33,30,33,36): warning CS8610: Die NULL-Zulässigkeit von Verweistypen im Typ des Parameters "obj" entspricht nicht dem außer Kraft gesetzten Member.
3>PackagePart\PackagePart.cs(277,30,277,36): warning CS8610: Die NULL-Zulässigkeit von Verweistypen im Typ des Parameters "obj" entspricht nicht dem außer Kraft gesetzten Member.
3>Utilities\FileHelper.cs(314,23,314,27): error CS1069: Der Typname "Icon" konnte nicht im Namespace "System.Drawing" gefunden werden. Dieser Typ wurde an Assembly "System.Drawing.Common, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" weitergeleitet. Sie sollten einen Verweis auf die Assembly hinzufügen.
3>Die Erstellung des Projekts "PackageViewModel.csproj" ist abgeschlossen -- FEHLER.
4>------ Erstellen gestartet: Projekt: NuGetPackageExplorer, Konfiguration: Debug Any CPU ------
4>C:\dev_projects\NuGetPackageExplorer\PackageExplorer\Controls\PdbFileViewer.xaml(13,103): error MC3066: Von dem Typverweis kann kein öffentlicher Typ mit dem Namen "AssemblyDebugDataViewModel" gefunden werden. Zeile 13 Position 103.
4>C:\dev_projects\NuGetPackageExplorer\PackageExplorer\MainWindow.xaml(22,10): error MC3074: Das Tag "DisabledCommand" ist im XML-Namespace "clr-namespace:PackageExplorerViewModel;assembly=PackageViewModel" nicht vorhanden. Zeile 22 Position 10.
4>C:\dev_projects\NuGetPackageExplorer\PackageExplorer\PackageViewer.xaml(48,112): error MC3066: Von dem Typverweis kann kein öffentlicher Typ mit dem Namen "EditablePackageMetadata" gefunden werden. Zeile 48 Position 112.
4>C:\dev_projects\NuGetPackageExplorer\PackageExplorer\ValidationResultWindow.xaml(15,95): error MC3066: Von dem Typverweis kann kein öffentlicher Typ mit dem Namen "ValidationResultViewModel" gefunden werden. Zeile 15 Position 95.
4>Die Erstellung des Projekts "NuGetPackageExplorer.csproj" ist abgeschlossen -- FEHLER.
========== Erstellen: 2 erfolgreich, 2 fehlerhaft, 0 aktuell, 0 übersprungen ==========
```
</details>

**Comment by ericstj** [comment]
This looks like it's caused by the SDK framework reference refactoring: https://github.com/dotnet/cli/issues/10536

@dsplaisted can you have a look?  /cc @vatsan-madhavan

**Comment by ericstj** [comment]
Yeah, setting `<UseWindowsForms>true</UseWindowsForms>` fixes this.  I think it may be interesting to review the classification of `System.Drawing.Common` as "common" rather than "WinForms", that said it contains other types that are specifically not for WPF and clash with WPF names so that may be the reasoning there. 

https://github.com/dotnet/core-setup/pull/6573/files#diff-0fd5841e781965454af0e91c667bc7e4R53

Curious if WPF has a better option for "Icon" : you may be able to avoid a dependency here. 

If you think that `System.Drawing.Common` should be in the default set of WPF, please open an issue in https://github.com/dotnet/core-setup to have that discussion.  Tag all those involved in https://github.com/dotnet/core-setup/pull/6573.

**Comment by onovotny** [comment]
Icon's are used within WPF too, widely.

**Comment by ericstj** [comment]
System.Drawing.Icon or a different type?  Again, if you think its important that this is available to WPF apps please open the issue in core-setup and tag the folks who made this change.

**Comment by dsplaisted** [comment]
Though the work to change this would probably occur in the core-setup repo, I'd suggest filing the issue in dotnet/wpf, as it's a WPF scenario and is more likely to get attention from the right folks if filed there.

**Comment by onovotny** [comment]
I'm not sure how important it is, I don't have data...

**Comment by vatsan-madhavan** [comment]
@dsplaisted, would the  `Reference` support alluded to in https://github.com/dotnet/sdk/issues/3265 help with a scenario like this as well?

**Comment by onovotny** [comment]
I added UseWindowsForms in the props and it still fails
