### ISSUE TITLE
A few long running tests in `System.Drawing.Printing.Tests`

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/corefx#38689]
I noticed a few tests were running for a long time, ranging from ~4 minutes to about 23 minutes; wondering if this is related to relatively new changes since I didn't experience this last time. Technically they didn't fail... I'm just wondering why it took so long.

### Build Environment
* Windows 10 Home x64, Insiders Build (Fast ring), Build No. 18917
* Surface Pro 4
  * (One thing that has changed since last time I ran the test is internet connection; I'm on some extremely slow network at the moment, and by slow, about 4~6Mbps)

```cs
System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.GetHdevmode_PageSettings_ReturnsExpected', Elapsed: 00:02:01
  [Long Running Test] 'System.Drawing.Printing.Tests.PrintDocumentTests.PrintPage_SetValue_ReturnsExpected', Elapsed: 00:12:22
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.GetHdevmode_PageSettings_ReturnsExpected', Elapsed: 00:04:01
  [Long Running Test] 'System.Drawing.Printing.Tests.PrintDocumentTests.PrintPage_SetValue_ReturnsExpected', Elapsed: 00:14:22
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.ToString_ReturnsExpected', Elapsed: 00:02:02
  [Long Running Test] 'System.Drawing.Printing.Tests.PrintDocumentTests.PrintPage_SetValue_ReturnsExpected', Elapsed: 00:16:58
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.ToString_ReturnsExpected', Elapsed: 00:04:02
  [Long Running Test] 'System.Drawing.Printing.Tests.PrintDocumentTests.PrintPage_SetValue_ReturnsExpected', Elapsed: 00:18:58
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.ToString_ReturnsExpected', Elapsed: 00:06:02
  [Long Running Test] 'System.Drawing.Printing.Tests.PrintDocumentTests.PrintPage_SetValue_ReturnsExpected', Elapsed: 00:20:58
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.ToString_ReturnsExpected', Elapsed: 00:08:02
  [Long Running Test] 'System.Drawing.Printing.Tests.PrintDocumentTests.PrintPage_SetValue_ReturnsExpected', Elapsed: 00:22:58
```

**Comment by Gnbrkm41** [comment]
The command used was `build & build -buildtests -test` on VS2019 Dev. Command Prompt.

**Comment by Gnbrkm41** [comment]
Now even more:
```cs
System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.GetHdevmode_PageSettings_ReturnsExpected', Elapsed: 00:04:10
  [Long Running Test] 'System.Drawing.Printing.Tests.PrintDocumentTests.PrintPage_SetValue_ReturnsExpected', Elapsed: 00:14:32
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.ToString_ReturnsExpected', Elapsed: 00:02:08
  [Long Running Test] 'System.Drawing.Printing.Tests.PrintDocumentTests.PrintPage_SetValue_ReturnsExpected', Elapsed: 00:17:08
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.ToString_ReturnsExpected', Elapsed: 00:04:08
  [Long Running Test] 'System.Drawing.Printing.Tests.PrintDocumentTests.PrintPage_SetValue_ReturnsExpected', Elapsed: 00:19:08
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.ToString_ReturnsExpected', Elapsed: 00:06:08
  [Long Running Test] 'System.Drawing.Printing.Tests.PrintDocumentTests.PrintPage_SetValue_ReturnsExpected', Elapsed: 00:21:08
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.ToString_ReturnsExpected', Elapsed: 00:08:08
  [Long Running Test] 'System.Drawing.Printing.Tests.PrintDocumentTests.PrintPage_SetValue_ReturnsExpected', Elapsed: 00:23:08
      System.Drawing.Printing.Tests.PrintDocumentTests.BeginPrint_SetValue_ReturnsExpected [SKIP]
        Condition(s) not met: "IsWindowsRS3OrEarlier"
      System.Drawing.Printing.Tests.PrintDocumentTests.PrinterSettings_SetValue_ReturnsExpected [SKIP]
        Condition(s) not met: "IsWindowsRS3OrEarlier"
      System.Drawing.Printing.Tests.PrintDocumentTests.QueryPageSettings_SetValue_ReturnsExpected [SKIP]
        Condition(s) not met: "IsWindowsRS3OrEarlier"
      System.Drawing.Printing.Tests.PrintDocumentTests.Ctor_Default_Success [SKIP]
        Condition(s) not met: "IsWindowsRS3OrEarlier"
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.ToString_ReturnsExpected', Elapsed: 00:10:32
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.ToString_ReturnsExpected', Elapsed: 00:12:32
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.ToString_ReturnsExpected', Elapsed: 00:14:32
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.ToString_ReturnsExpected', Elapsed: 00:16:32
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.ToString_ReturnsExpected', Elapsed: 00:18:32
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.PrinterResolutions_ReturnsExpected', Elapsed: 00:02:07
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.IsDirectPrintingSupported_ImageFormatSupported_ReturnsExpected', Elapsed: 00:02:07
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.IsDirectPrintingSupported_ImageFormatSupported_ReturnsExpected', Elapsed: 00:04:07
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.IsDirectPrintingSupported_ImageFormatSupported_ReturnsExpected', Elapsed: 00:06:07
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.IsDirectPrintingSupported_ImageFormatSupported_ReturnsExpected', Elapsed: 00:08:07
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.IsDirectPrintingSupported_ImageFormatSupported_ReturnsExpected', Elapsed: 00:10:07
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.IsDirectPrintingSupported_ImageFormatSupported_ReturnsExpected', Elapsed: 00:12:07
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.IsDirectPrintingSupported_ImageFormatSupported_ReturnsExpected', Elapsed: 00:14:07
      System.Drawing.Printing.Tests.PrinterSettingsTests.CreateMeasurementGraphics_Default_ReturnsExpected [SKIP]
        Condition(s) not met: "IsWindowsRS3OrEarlier"
      System.Drawing.Printing.Tests.PrinterSettingsTests.Clone_Success [SKIP]
        Condition(s) not met: "IsWindowsRS3OrEarlier"
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.SupportsColor_ReturnsExpected', Elapsed: 00:02:06
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.SupportsColor_ReturnsExpected', Elapsed: 00:04:06
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.SupportsColor_ReturnsExpected', Elapsed: 00:06:06
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.PaperSizes_ReturnsExpected', Elapsed: 00:02:08
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.PaperSizes_ReturnsExpected', Elapsed: 00:04:08
     System.Drawing.Common.Tests: [Long Running Test] 'System.Drawing.Printing.Tests.PrinterSettingsTests.PaperSizes_ReturnsExpected', Elapsed: 00:06:08
```

**Comment by ViktorHofer** [comment]
@safern those are fairly simple tests, ie constructing an object and asserting notnull. Any idea how this could hang?

**Comment by Gnbrkm41** [comment]
I think I could try to attach debugger to it to see what's happening. I don't know if it is caused directly by the tests or something else.

**Comment by Gnbrkm41** [comment]
So I've been trying to check `PaperSources_ReturnsExpected` test; it looks like the type constructs just fine, but the call to `printerSettings.PaperSources` take *several minutes* before it returns; maybe it's something to do with `Get_PaperSources` (and I'm assuming it's the same for other methods as well). Having a deeper look.

**Comment by Gnbrkm41** [comment]
For PaperSources_ReturnsExpected:

The call to `printerSettings.PaperSources` continues to `Get_PaperSources()`:
https://github.com/dotnet/corefx/blob/60d8aa31a4c1ffa0e125bd7941aca171439a2f72/src/System.Drawing.Common/src/System/Drawing/Printing/PrinterSettings.Windows.cs#L1120-L1151

https://github.com/dotnet/corefx/blob/60d8aa31a4c1ffa0e125bd7941aca171439a2f72/src/System.Drawing.Common/src/System/Drawing/Printing/PrinterSettings.Windows.cs#L1078
🙄  This calls `PrinterName`, which calls `PrinterNameInternal`, which calls `SafeNativeMethods.PrintDlg(data);` and hangs. Wonder why the value isn't cached in `_printerName` after the first call to `PrinterNameInternal`? Just curious.

-----------
Most of the time are spent calling `PrinterName` and `FastDeviceCapabilities()` (multiple times).
`FastDeviceCapabilities` seem to call `GetOutputPort()` (which in turn also calls `SafeNativeMethods.PrintDlg(data);`, at which point it hangs for about 40 seconds ~ a minute.) 
https://github.com/dotnet/corefx/blob/60d8aa31a4c1ffa0e125bd7941aca171439a2f72/src/System.Drawing.Common/src/System/Drawing/Printing/PrinterSettings.Windows.cs#L786
Once `GetOutputPort` returns, it calls another native method `SafeNativeMethods.DeviceCapabilities`, at which point it again hangs for a while.

https://github.com/dotnet/corefx/blob/60d8aa31a4c1ffa0e125bd7941aca171439a2f72/src/System.Drawing.Common/src/System/Drawing/Printing/PrinterSettings.Windows.cs#L718

Another native method that seem to hang is `SafeNativeMethods.DocumentProperties`.

It looks like most of them are waiting for the native methods to return. Not sure what's happening; It could be some weird quirkiness of my laptop, but I'm not too sure.

**Comment by danmosemsft** [comment]
Do you happen to know whether this happened before you updated your Windows build? It may be a bug in the insiders build. Seems we are passing `PD_RETURNDEFAULT` to `PrintDlg` - I don't know the API but if that doesnt return immediately it seems beyond our control.

@JeremyKuhne

**Comment by JeremyKuhne** [comment]
@Gnbrkm41 What printers do you have installed/available? If it isn't a fast ring problem overall, first suspect for me would be a driver or possibly access to a remote printer. I definitely don't see this problem - the whole set of System.Drawing.Common tests runs in < 5 seconds for me.

**Comment by Gnbrkm41** [comment]
>Do you happen to know whether this happened before you updated your Windows build?
No idea. I've been using Insider build for a while.

I used to have a driver for [HP Deskjet 1050](https://support.hp.com/kr-ko/drivers/selfservice/HP-Deskjet-1050-All-in-One-Printer-series---J4/4027462/model/4027464), which I removed since I've ran the test last time. Can't reproduce it now... not sure if it's because of the driver or simply upgrading to latest fast ring fixed it.

**Comment by safern** [comment]
> Can't reproduce it now... not sure if it's because of the driver or simply upgrading to latest fast ring fixed it.

😄 -- weird intermittent issues, the good thing is it doesn't repro anymore after those changes. Will then close this issue.
