### ISSUE TITLE
Create and Store asymmetric keys on Linux

### ISSUE THREAD

**Issue by MuhammadAliYousaf** [dotnet/corefx#38716]
How to create ECDsa public private keys and store them on Linux (Ubuntu) using .Net Core.
@bartonjs Please help. I am done on windows and Mac (#37967), now need to implement on Linux.

**Comment by bartonjs** [comment]
Linux supports adding certificates to X509Store instances (provided they are CurrentUser stores).  So it's the same as on macOS:

* ECDsa.Create(ECCurve)
* Use CertificateRequest to build a self signed cert with that key
* Add that self-signed cert to an X509Store of your choosing (Linux supports creating and writing to arbitrary stores, macOS is limited to StoreName.My)

Alternatively (.NET Core 3.0):
* ECDsa.Create(ECCurve)
* ecdsa.ExportPkcs8PrivateKey()
* Persist that to disk
* Later, load it from disk
* ECDsa.Create()
* ecdsa.ImportPkcs8PrivateKey(bytes, out _)

**Comment by MuhammadAliYousaf** [comment]
Thanks,
Following is code which I am using, its working perfectly on MacOS but on linux when I get Certificate from the store, it does not has private key. Please let me know where I am doing mistake.

`try
            {
                string subjectName = "MyCertificate";

                X509Certificate2 certificate = null;

                using (var ecdsa = ECDsa.Create("ECDsa"))
                {
                    ecdsa.KeySize = 256;
                    var request = new CertificateRequest(
                        $"CN={subjectName}",
                        ecdsa,
                        HashAlgorithmName.SHA256);

                    // set basic certificate contraints
                    request.CertificateExtensions.Add(
                        new X509BasicConstraintsExtension(true, true, 12, true));

                    // key usage: Digital Signature and Key Encipherment
                    request.CertificateExtensions.Add(
                        new X509KeyUsageExtension(
                            X509KeyUsageFlags.KeyCertSign,
                            true));

                    // DPS samples create certs with the device name as a SAN name 
                    // in addition to the subject name
                    var sanBuilder = new SubjectAlternativeNameBuilder();
                    sanBuilder.AddDnsName(subjectName);
                    var sanExtension = sanBuilder.Build();
                    request.CertificateExtensions.Add(sanExtension);

                    // Enhanced key usages
                    request.CertificateExtensions.Add(
                        new X509EnhancedKeyUsageExtension(
                            new OidCollection {
                            new Oid("1.3.6.1.5.5.7.3.2"), // TLS Client auth
                            new Oid("1.3.6.1.5.5.7.3.1")  // TLS Server auth
                            },
                            false));

                    // add this subject key identifier
                    request.CertificateExtensions.Add(
                        new X509SubjectKeyIdentifierExtension(request.PublicKey, false));

                    var notbefore = DateTimeOffset.UtcNow.AddDays(-1);
                    var notafter = DateTimeOffset.UtcNow.AddDays(365);

                    certificate = request.CreateSelfSigned(notbefore, notafter);
                }


                var SerialNumber = certificate.SerialNumber;

                X509Store certificateStore = new X509Store(StoreName.My, StoreLocation.CurrentUser);
                certificateStore.Open(OpenFlags.ReadWrite);
                certificateStore.Add(certificate);
                certificateStore.Close();

                Console.WriteLine("Added into store with Serial No: " + SerialNumber);

                X509Certificate2 founded = null;
                using (var store = new X509Store(StoreName.My, StoreLocation.CurrentUser, OpenFlags.ReadOnly))
                {
                    store.Open(OpenFlags.OpenExistingOnly);
                    var certs = store.Certificates.Find(X509FindType.FindBySerialNumber, SerialNumber, false);
                    founded = certs.OfType<X509Certificate2>().FirstOrDefault();
                }

                if (founded != null)
                {
                    Console.WriteLine("Founded: " + founded.Subject);
                    Console.WriteLine("Public Key: " + founded.PublicKey);
                    Console.WriteLine("Private Key: " + founded.HasPrivateKey + " - " + founded.GetECDsaPrivateKey());                   //**HERE I AM GETTING FALSE.** 

                }
                else
                    Console.WriteLine("Not Found!");

                Console.ReadLine();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error : " + ex.Message);
            }`

**Comment by bartonjs** [comment]
Oh, you're hitting https://github.com/dotnet/corefx/issues/31746.

It looks like this is an OpenSSL bug that has since been fixed.  Running substantially the same code as you put here, I get success when OpenSSL 1.1. generates the PFX, and no private key found when OpenSSL 1.0 generates it:

```
jbarton@jsb-ubuntu18:~/dncli/ecdsacertstore$ CLR_OPENSSL_VERSION_OVERRIDE=1.0.0 dotnet run
certificate.HasPrivateKey: True
Added into store with Serial No: 00E25B6FD1BF51D5F0
Cert: CN=MyCertificate-636966575358661930
CertSerial: 00E25B6FD1BF51D5F0
Has Private Key: False

Founded: CN=MyCertificate-636966575358661930
Public Key: System.Security.Cryptography.X509Certificates.PublicKey
Private Key: False -
jbarton@jsb-ubuntu18:~/dncli/ecdsacertstore$ CLR_OPENSSL_VERSION_OVERRIDE=1.0.0 dotnet run
certificate.HasPrivateKey: True
Added into store with Serial No: 00D9A64BEC22CF6F9A
Cert: CN=MyCertificate-636966575455574128
CertSerial: 00D9A64BEC22CF6F9A
Has Private Key: False

Cert: CN=MyCertificate-636966575358661930
CertSerial: 00E25B6FD1BF51D5F0
Has Private Key: False

Founded: CN=MyCertificate-636966575455574128
Public Key: System.Security.Cryptography.X509Certificates.PublicKey
Private Key: False -
jbarton@jsb-ubuntu18:~/dncli/ecdsacertstore$ CLR_OPENSSL_VERSION_OVERRIDE=1.1 dotnet run
certificate.HasPrivateKey: True
Added into store with Serial No: 655753F0E2FEB892
Cert: CN=MyCertificate-636966575546665412
CertSerial: 655753F0E2FEB892
Has Private Key: True

Cert: CN=MyCertificate-636966575455574128
CertSerial: 00D9A64BEC22CF6F9A
Has Private Key: False

Cert: CN=MyCertificate-636966575358661930
CertSerial: 00E25B6FD1BF51D5F0
Has Private Key: False

Founded: CN=MyCertificate-636966575546665412
Public Key: System.Security.Cryptography.X509Certificates.PublicKey
Private Key: True - System.Security.Cryptography.ECDsaOpenSsl
jbarton@jsb-ubuntu18:~/dncli/ecdsacertstore$ CLR_OPENSSL_VERSION_OVERRIDE=1.1 dotnet run
certificate.HasPrivateKey: True
Added into store with Serial No: 00C8E3B7C69066D0EB
Cert: CN=MyCertificate-636966575546665412
CertSerial: 655753F0E2FEB892
Has Private Key: True

Cert: CN=MyCertificate-636966575585521733
CertSerial: 00C8E3B7C69066D0EB
Has Private Key: True

Cert: CN=MyCertificate-636966575455574128
CertSerial: 00D9A64BEC22CF6F9A
Has Private Key: False

Cert: CN=MyCertificate-636966575358661930
CertSerial: 00E25B6FD1BF51D5F0
Has Private Key: False

Founded: CN=MyCertificate-636966575585521733
Public Key: System.Security.Cryptography.X509Certificates.PublicKey
Private Key: True - System.Security.Cryptography.ECDsaOpenSsl
jbarton@jsb-ubuntu18:~/dncli/ecdsacertstore$ CLR_OPENSSL_VERSION_OVERRIDE=1.0.0 dotnet run
certificate.HasPrivateKey: True
Added into store with Serial No: 00A8595B938EAA7372
Cert: CN=MyCertificate-636966575546665412
CertSerial: 655753F0E2FEB892
Has Private Key: True

Cert: CN=MyCertificate-636966575585521733
CertSerial: 00C8E3B7C69066D0EB
Has Private Key: True

Cert: CN=MyCertificate-636966575637505376
CertSerial: 00A8595B938EAA7372
Has Private Key: False

Cert: CN=MyCertificate-636966575455574128
CertSerial: 00D9A64BEC22CF6F9A
Has Private Key: False

Cert: CN=MyCertificate-636966575358661930
CertSerial: 00E25B6FD1BF51D5F0
Has Private Key: False

Founded: CN=MyCertificate-636966575637505376
Public Key: System.Security.Cryptography.X509Certificates.PublicKey
Private Key: False -
jbarton@jsb-ubuntu18:~/dncli/ecdsacertstore$
```

**Comment by MuhammadAliYousaf** [comment]
That is great, it's working.
Now can you please tell me that where certificates are stored, when I add them in X509Store. Like in MacOS they become visible in Keychain, on Ubuntu where they stored?

**Comment by MuhammadAliYousaf** [comment]
On Linux, Certificates are stores in the following directory,
~/.dotnet/corefx/cryptography/x509stores/my

But we want to make them secure, passphrase is not enough. Is there any other way of securing? I mean on windows we have CNG, keychain on MacOS, how we can secure them on Linux? 
Does linux OS provides any similar feature to secure certificates? 
We mainly want to secure private keys. As you know, in .Net core we need to pair it with certificate for storage.

**Comment by bartonjs** [comment]
> Does linux OS provides any similar feature to secure certificates?

No(t that we're aware of), or we'd already be using it.  Neither Linux nor OpenSSL has a concept that's really the same as Keychain or CNG KSPs.

If what you're really after is just private key storage, in .NET Core 3.0 you can import and export keys into PKCS#8 or Encrypted PKCS#8.  e.g. `ecdsa.ExportEncryptedPkcs8PrivateKey(passphrase, encryptionOptions)` and `ecdsa.ImportEncryptedPkcs8PrivateKey(passphrase, bytes, out bytesRead)` and then you can store that in whatever manner seems the most appropriate.
