### ISSUE TITLE
[System.Numerics.BitOperations] Add Bitmask methods

### ISSUE THREAD

**Issue by shaggygi** [dotnet/corefx#38715]
Related to [.NET IoT](https://github.com/dotnet/iot), there are scenarios where we need to mask bit values.  Reading register data or writing to ports for I/O use this with some of the device bindings.

Would it be possible to add the following static methods to this API?  Thx

```csharp
public static uint Bitmask (uint value, uint mask);
public static ulong Bitmask (ulong value, ulong mask);
```

Examples:
```csharp
BitOperations.Bitmask(0b0101_0101_1010_1010, 0b0000_0000_0000_0000); // Returns 0b0000_0000_0000_0000
BitOperations.Bitmask(0b1000_0100_0010_0001, 0b0000_1111_0000_0101); // Returns 0b0000_0100_0000_0001
BitOperations.Bitmask(0b0101_0101_1010_1010, 0b1111_1111_1111_1111); // Returns 0b0101_0101_1010_1010
```

cc/ @joperezr

**Comment by stephentoub** [comment]
Why wouldn't you just use `&`?

**Comment by shaggygi** [comment]
Good point.  I was thinking there was something we did with BitVectors where I thought this would help.  Let me go back and review that code and if this is related.  Thx

**Comment by shaggygi** [comment]
Yup, different topic :face_with_head_bandage:.  Thx for pointing out.  I could see other methods added for getting/setting specific bit.

```csharp
public static uint ClearBit (uint value, int offset);
public static uint SetBit (uint value, int offset);
public static bool GetBit (uint value, int offset);
```

**Comment by stephentoub** [comment]
Those are all discussed in https://github.com/dotnet/corefx/issues/32269.
