### ISSUE TITLE
Add reference assembly for packages in `netcoreapp3.0`

### ISSUE THREAD

**Issue by anurse** [dotnet/corefx#38729]
ASP.NET Core's framework embeds `System.IO.Pipelines` (since it is required by ASP.NET Core servers). As a result, our targeting pack also includes this library. However, since `System.IO.Pipelines` does not provide a ref assembly, we currently embed the full library. This is not ideal as it means the `3.0.0` version of this library will always be present on disk. The implementation is also larger than the ref assembly.

In order to properly embed the ref assembly, we need `System.IO.Pipelines` to produce `ref/netcoreapp3.0` asset.

Packages affected:
* `System.IO.Pipelines`
* ~~`System.Threading.Channels`~~

**Comment by anurse** [comment]
cc @ericstj

**Comment by ericstj** [comment]
We may want to look at anything in the WindowsDesktop pack as well to see if they are bundling any package that are missing a ref.

**Comment by joperezr** [comment]
From the ASPNETCore ref pack, I can see that System.Threading.Channels has the same problem.
