### ISSUE TITLE
XSD Validation Errors- Missing details on xsd schema error code

### ISSUE THREAD

**Issue by surbhigarg92** [dotnet/corefx#38748]
When trying to validate XML against XSD in .net core 2.2 , we are unable to get the exact schema validation error . The validation error only give details on the name of XML element which has failed the validation , not on which XSD schema validation is failed. 

Below error is thrown by .net xml parser

> The element 'SignonRq' in namespace **'http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/'** has invalid child element 'CustLangPref' in namespace **'{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}'.** List of possible elements expected: 'SignonPswd, SignonCert, SignonTransport, SessKey, ClientDt' in namespace '**http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/**'.

Same validation if we run in Java below error is thrown.

> Error - Line 12, 50: org.xml.sax.SAXParseException; lineNumber: 12; columnNumber: 50; cvc-pattern-valid: Value '47BD999C6068493EB1BB33A48730C55D' is not facet-valid with respect to pattern '[0-9A-Fa-f]{8}(-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}' for type 'UUID_NoID'.

There is no way to get cvc exception schema code in .net core 2.2

**Comment by krwq** [comment]
@surbhigarg92 is there anything we do differently between .NET Core and full framework or older version of .NET Core?

Could you paste some example XML and schema along with expected and actual message?

**Comment by vermaaditya** [comment]
@krwq - we are looking for .NET (Core & Framework). 

The validation error give details on the name of XML element which has failed the validation along with the line number and position & not on which XSD schema validation has failed.

For instance in .NET, we are getting the below validation error – 

`The element 'SignonRq' in namespace 'http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/' has invalid child element 'CustLangPref' in namespace '{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}'. List of possible elements expected: 'SignonPswd, SignonCert, SignonTransport, SessKey, ClientDt' in namespace 'http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/'.
`
But the same validation in Java appears to be like – 

`Error - Line 42, 19: org.xml.sax.SAXParseException; lineNumber: 42; columnNumber: 19; cvc-complex-type.2.4.a: Invalid content was found starting with element 'PostalCode'. One of '{"http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/":Country, "http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/":Latitude, "http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/":Longitude, "http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/":County, "http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/":Region, "http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/":RegionCd, "http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/":Township, "http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/":LegalAddr, "http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/":ItemIdInfo, "http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/":CountyTownCd, "http://www.CSIO.org/standards/PC_Surety/CSIO1/xml/":TownCd, "http://www.CSIO.org/standards/PC_Surety/CSIO1/xml/":AddrFormatCd, "http://www.CSIO.org/standards/PC_Surety/CSIO1/xml/":LengthTimeAddr, "http://www.CSIO.org/standards/PC_Surety/CSIO1/xml/":AddrValidationdInd}' is expected.`

Please let us know if there is a provision in .Net to get the Schema Validation Type i.e. “cvc-complex-type.2.4.a” in the above example.

**Comment by krwq** [comment]
@vermaaditya I do not believe we store error codes. We do store line and column number as well as the schema object though:

https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System/Xml/Schema/XmlSchemaException.cs#L184
https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System/Xml/Schema/XmlSchemaException.cs#L179
https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System/Xml/Schema/XmlSchemaException.cs#L174

**Comment by vermaaditya** [comment]
@krwq - I always see the schemaObject and SourceSchemaObject as null. 

![image](https://user-images.githubusercontent.com/20763984/60116158-22b94800-9795-11e9-8b70-73e5b8bbb16b.png)

Would appreciate if you can help on how to populate those objects.

**Comment by krwq** [comment]
@vermaaditya [per docs](https://docs.microsoft.com/en-us/dotnet/api/system.xml.schema.xmlschemaexception.sourceschemaobject?view=netframework-4.8) that means:
> A return value of nil indicates a syntactic parsing validation error in the SOM (Schema Object Model).

which might suggest a bug.

Have you tried doing something similar to this perhaps:
https://stackoverflow.com/a/7469892

**Comment by vermaaditya** [comment]
@krwq - Tried the solution mentioned in the link does not help.

**Comment by krwq** [comment]
@vermaaditya do you know if this is specific to this particular error? do you get the same results on full framework?

**Comment by krwq** [comment]
To update this thread, the issue here is to provide unique identifier for the exception (i.e. in case user needs to suppress the schema warning) - ideally that would be a spec chapter. Currently we do not have info on the spec chapter when throwing an exception and that would be a bit of work to add that information. As a workaround we can reverse engineer the resource name for the exception message which should provide relatively unique identifier for the exception. I.e. (note that code is .NET Core specific because of the hard-coded resource name. It would need some work to find the right resource name for full framework and possibly other places which might use different name):

```csharp
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Resources;
using System.Text.RegularExpressions;
using System.Xml.Schema;

namespace XmlSchemaExceptionMatching
{
    class Program
    {
        static void Main(string[] args)
        {
            string example = @"The element 'SignonRq' in namespace 'http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/' has invalid child element 'CustLangPref' in namespace '{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}'. List of possible elements expected: 'SignonPswd, SignonCert, SignonTransport, SessKey, ClientDt' in namespace 'http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/'.";

            // there should only be one instance of that (note, needs lock or seperate ThreadLocal copy for multi-threaded scenarios)
            XmlExceptionMatcher matcher = new XmlExceptionMatcher();

            string exceptionId = matcher.GetExceptionIdentifierFromMessage(example);

            // not found should only happen due to bug (i.e. wrong resource stream or exception coming from outside of resources)
            Console.WriteLine(exceptionId ?? "<not found>"); // Prints: Sch_InvalidElementContentExpecting
        }
    }

    class XmlExceptionMatcher
    {
        private List<(Regex, string)> _regexToId = new List<(Regex, string)>();
        public XmlExceptionMatcher()
        {
            using (Stream resourceStream = typeof(XmlSchema).Assembly.GetManifestResourceStream("FxResources.System.Private.Xml.SR.resources"))
            using (ResourceReader resReader = new ResourceReader(resourceStream))
            {
                foreach (DictionaryEntry kv in resReader)
                {
                    string key = kv.Key as string;
                    string value = kv.Value as string;

                    if (key == null || value == null)
                        continue;

                    // replace {0} - {9} with .* and escape parts in between
                    string pattern = "^" + string.Join(".*", Regex.Split(value, "\\{\\d\\}").Select(s => Regex.Escape(s))) + "$";

                    Regex re = new Regex(pattern, RegexOptions.Compiled | RegexOptions.Singleline);
                    _regexToId.Add((re, key));
                }
            }
        }

        public string GetExceptionIdentifierFromMessage(string exceptionMessage)
        {
            foreach ((Regex re, string id) in _regexToId)
            {
                if (re.IsMatch(exceptionMessage))
                    return id;
            }

            return null;
        }
    }
}
```
