### ISSUE TITLE
Investigate bogus assignment in System.Net.Sockets

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#38750]
Something I noticed investigating other issue, in one of the recent [PR](https://github.com/dotnet/corefx/pull/37486) there is an assignment which gets always overridden. Either assignment should be removed or we should return after it.

https://github.com/dotnet/corefx/commit/3fac6ad5bc4576eb2216ccb24fbed2bf173d41f4#diff-eee4543f13c4d6b0c1bd8bdb53281f7aR1875

cc: @tmds

**Comment by davidsh** [comment]
@stephentoub

**Comment by tmds** [comment]
I'll clean this up next week.

**Comment by davidsh** [comment]
PR #37486 is being reverted due to unexpected changes in async Socket I/O behavior.

**Comment by davidsh** [comment]
We reverted PR #37486 (#38764).  So, this issue is moot as an active issue.  But it should be considered additional feedback when redoing PR #37486.
