### ISSUE TITLE
TcpReceiveSendGetsCanceledByDispose failing in CI

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#38763]
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38527~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190621.24/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SendReceiveMemoryNativeTask~2FTcpReceiveSendGetsCanceledByDispose(receiveOrSend:%20False)

Test was just added in: #37486

```
Ubuntu.1604.Amd64.Open-x64-Debug
Get Repro environment
Unhandled Exception of Type Xunit.Sdk.EqualException
Message :
Assert.Equal() Failure
Expected: OperationAborted
Actual:   ConnectionReset
Stack Trace :
   at System.Net.Sockets.Tests.SendReceive`1.TcpReceiveSendGetsCanceledByDispose(Boolean receiveOrSend) in /_/src/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs:line 1121
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by davidsh** [comment]
We are in the process of reverting PR #37486 due to unanticipated changes to Socket async I/O behaviors.

**Comment by davidsh** [comment]
We reverted PR #37486 with PR #38764.  So, I'm going to close this since the problem should go away now.
