### ISSUE TITLE
 System.Globalization.Tests.CurrentCultureTests tests failing on Linux amd64 checked CoreCLR

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#38768]
First found in https://github.com/dotnet/coreclr/pull/25120. The tests are disabled in CoreCLR CI against this issue.

Affected tests:

System.Globalization.Tests.CurrentCultureTests.CurrentCulture_DefaultWithNoLang
System.Globalization.Tests.CurrentCultureTests.CurrentCulture_BasedOnLangEnvVar

```
Error message
Exit code was 150 but it should have been 42\nExpected: True\nActual: False

Stack trace
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Microsoft.DotNet.RemoteExecutor/RemoteInvokeHandle.cs:line 143
```

**Comment by danmosemsft** [comment]
I am curious why we are getting literal `\n` in cases like this in Azure DevOps. Xunit is using `Environment.NewLine` https://github.com/xunit/assert.xunit/blob/master/Sdk/Exceptions/EqualException.cs#L89 which in this case would be `\n`
In MC it appears without newlines at all
```
System.Globalization.Tests.CurrentCultureTests.CurrentCulture_DefaultWithNoLang(langEnvVar: null) [FAIL]
      Exit code was 150 but it should have been 42
```
Need to dig the xunit log out.

**Comment by jkotas** [comment]
>  why we are getting literal \n in cases like this in Azure DevOps

It is how Azure DevOps test result rendering works. The code that produces `\n` in this case is somewhere inside Azure DevOps infrastructure, I think.

**Comment by ViktorHofer** [comment]
@tarekgh can you please take a look at the two failures?

**Comment by tarekgh** [comment]
Pasting the used container information to try to repro it as we didn't change anything here and not clear why this started to fail now. looks we are using Centos-7 OS. will try to look at that by tomorrow.

```
##[section]Starting: Initialize containers
##[command]/usr/bin/docker version --format '{{.Server.APIVersion}}'
'1.39'
Docker daemon API version: '1.39'
##[command]/usr/bin/docker version --format '{{.Client.APIVersion}}'
'1.39'
Docker client API version: '1.39'
##[command]/usr/bin/docker ps --all --quiet --no-trunc --filter "label=b23c1b"
##[command]/usr/bin/docker network prune --force --filter "label=b23c1b"
##[command]/usr/bin/docker network create --label b23c1b vsts_network_35335b678bfd450abadc76e0b5f96e64
9507273c5f37782703155a9a01f64ba3a8d63330c085be71e194f942f836dbec
##[command]/usr/bin/docker pull mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-3e800f1-20190501005343
centos-7-3e800f1-20190501005343: Pulling from dotnet-buildtools/prereqs
Digest: sha256:b8b7d2a784d4d4e0cd85037feacafc987ef7a1294a453fc07963350e64971b80
Status: Image is up to date for mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-3e800f1-20190501005343
##[command]/usr/bin/docker inspect --format="{{index .Config.Labels \"com.azure.dev.pipelines.agent.handler.node.path\"}}" mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-3e800f1-20190501005343
##[command]/usr/bin/docker create --name 10bb8a581abe4d14be00c2bfed6c106d_mcrmicrosoftcomdotnetbuildtoolsprereqscentos73e800f120190501005343_546c08 --label b23c1b --network vsts_network_35335b678bfd450abadc76e0b5f96e64  -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/datadisks/disk1/workspace/_work/1":"/__w/1" -v "/datadisks/disk1/workspace/_work/_temp":"/__w/_temp" -v "/datadisks/disk1/workspace/_work/_tool":"/__t" -v "/datadisks/disk1/workspace/_work/_tasks":"/__w/_tasks" -v "/datadisks/disk1/workspace/externals":"/__a/externals":ro -v "/datadisks/disk1/workspace/_work/.taskkey":"/__w/.taskkey" mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-3e800f1-20190501005343 "/__a/externals/node/bin/node" -e "setInterval(function(){}, 24 * 60 * 60 * 1000);"
7e7b7d7918dcd7e9d77173f360513da9df7afba7b75c16aa417833a86dd5451e
##[command]/usr/bin/docker start 7e7b7d7918dcd7e9d77173f360513da9df7afba7b75c16aa417833a86dd5451e
7e7b7d7918dcd7e9d77173f360513da9df7afba7b75c16aa417833a86dd5451e
##[command]/usr/bin/docker ps --all --filter id=7e7b7d7918dcd7e9d77173f360513da9df7afba7b75c16aa417833a86dd5451e --filter status=running --no-trunc --format "{{.ID}} {{.Status}}"
7e7b7d7918dcd7e9d77173f360513da9df7afba7b75c16aa417833a86dd5451e Up Less than a second
##[command]/usr/bin/docker exec  7e7b7d7918dcd7e9d77173f360513da9df7afba7b75c16aa417833a86dd5451e sh -c "command -v bash"
/usr/bin/bash
##[command]whoami 
helixbot
##[command]id -u helixbot
1000
Try create an user with UID '1000' inside the container.
##[command]/usr/bin/docker exec  7e7b7d7918dcd7e9d77173f360513da9df7afba7b75c16aa417833a86dd5451e bash -c "grep 1000 /etc/passwd | cut -f1 -d:"
##[command]/usr/bin/docker exec  7e7b7d7918dcd7e9d77173f360513da9df7afba7b75c16aa417833a86dd5451e useradd -m -u 1000 helixbot_azpcontainer
Grant user 'helixbot_azpcontainer' SUDO privilege and allow it run any command without authentication.
##[command]/usr/bin/docker exec  7e7b7d7918dcd7e9d77173f360513da9df7afba7b75c16aa417833a86dd5451e groupadd azure_pipelines_sudo
##[command]/usr/bin/docker exec  7e7b7d7918dcd7e9d77173f360513da9df7afba7b75c16aa417833a86dd5451e usermod -a -G azure_pipelines_sudo helixbot_azpcontainer
##[command]/usr/bin/docker exec  7e7b7d7918dcd7e9d77173f360513da9df7afba7b75c16aa417833a86dd5451e su -c "echo '%azure_pipelines_sudo ALL=(ALL:ALL) NOPASSWD:ALL' >> /etc/sudoers"
Allow user 'helixbot_azpcontainer' run any docker command without SUDO.
##[command]stat -c %g /var/run/docker.sock
999
##[command]/usr/bin/docker exec  7e7b7d7918dcd7e9d77173f360513da9df7afba7b75c16aa417833a86dd5451e bash -c "cat /etc/group"
##[command]/usr/bin/docker exec  7e7b7d7918dcd7e9d77173f360513da9df7afba7b75c16aa417833a86dd5451e usermod -a -G input helixbot_azpcontainer
##[section]Finishing: Initialize containers
```

**Comment by ViktorHofer** [comment]
Thanks!

**Comment by tarekgh** [comment]
I looked at the issue and I have hard time to repro. But this is not related to Globalization but rather it is related to running remote execution. The whole test didn't really run but rather it is aborted. 

@MattGal thankfully provided a remote to exact environment and I couldn't repro the issue by building and running the exact same failed tests. @MattGal pointed out the failure is because of 

```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.0.0' was not found.
  - The following frameworks were found:
      9.9.9 at [/home/helixbot/work/a5695057-09d9-4e1c-9840-a5af643fdf6b/Payload/shared/Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
```

@MattGal will try later to repro this issue but would be good if @ericstj @wtgodbe take a look to see if they can find something not obvious here.

**Comment by ViktorHofer** [comment]
This indicates that the shared framework is built with a 9.9.9 version but a 3.0.0 should be built. I'm not sure what could be causing this. To me that sounds like coreclr isn't using the right testhost, cc @BruceForstall

**Comment by ericstj** [comment]
Right, @BruceForstall and I chatted about this last week.  In most cases it was working because the script which launched the test was passing in the roll-forward parameter.  Why would that work for the outer test but not the remote-exec call?  Perhaps a commandline arg is missing?

Of course changing the version of the CoreCLR shared framework is likely to fix this, but it would be good to get remoteexec behaving in the same way as the test case itself.

**Comment by ViktorHofer** [comment]
the environment variable (https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.CoreFxTesting/build/assets/RunnerTemplate.Windows.txt#L54) should handle both scenarios, I'm not sure why this isn't working for remote-exec calls.

**Comment by ericstj** [comment]
I guess this is what did it: https://github.com/dotnet/corefx/blob/30ca4113ed07fc78060a0c9d3f95eee4fe8f8ee3/src/System.Globalization/tests/CultureInfo/CultureInfoCurrentCulture.cs#L141

**Comment by ericstj** [comment]
We could update https://github.com/dotnet/corefx/blob/30ca4113ed07fc78060a0c9d3f95eee4fe8f8ee3/src/System.Globalization/tests/CultureInfo/CultureInfoCurrentCulture.cs#L162-L174

**Comment by tarekgh** [comment]
why this worked before and started to break now?

**Comment by ericstj** [comment]
@ViktorHofer changed the version of the test shared framework to match the actual productversion, this helps folks like CoreCLR and Mono reuse our test assets.  It also helps run our test assets against the real product.  That's what caused this to break.

There are some other environment variables we should be careful to preserve so that the remoteExec doesn't go looking machine-wide as well.  We should probably preserve all DOTNET_* args, alternatively explicitly list DOTNET_MULTILEVEL_LOOKUP and DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX.  We should persist those in this test.

We should also update CoreCLR to fix the shared framework version.

**Comment by BruceForstall** [comment]
I have changes in progress that will update CoreCLR to use 3.0.0 instead of 9.9.9.

@ericstj Should the COMPlus_* variables also be preserved?

**Comment by tarekgh** [comment]
I believe we should preserve DONTNET_* and ComPlus*. 

I am not sure why we clear the environment variables in the first place. I looked at the history and it doesn't say why we do that. 

@BruceForstall would you apply this change to the test or want me to do it?

**Comment by BruceForstall** [comment]
> @BruceForstall would you apply this change to the test or want me to do it?

@tarekgh Please make the change.

**Comment by tarekgh** [comment]
will do it.

**Comment by tarekgh** [comment]
I have merged the suggested change to preserve the environment variables in the test. I am not sure if there is something else need to be done by @BruceForstall or @ViktorHofer?

**Comment by ViktorHofer** [comment]
That's all. Thank you

**Comment by jkotas** [comment]
The exclusion added in https://github.com/dotnet/coreclr/pull/25120 should be deleted to verify that this actually works.

**Comment by tarekgh** [comment]
talked offline with @ViktorHofer and he is going to follow up getting the updated corefx tests to coreclr and remove the test exclusion.

**Comment by wtgodbe** [comment]
@ViktorHofer please make sure this change is done before the code merge at Noon PST tomorrow (21.5 hours from now)

**Comment by ericstj** [comment]
Still tracking anything here @ViktorHofer?  I think the fix went into corefx.

**Comment by jkotas** [comment]
This is fully resolved now.

**Comment by tarekgh** [comment]
https://github.com/dotnet/coreclr/pull/25425
