### ISSUE TITLE
String.Format Fatal error in Windows 7

### ISSUE THREAD

**Issue by miguep** [dotnet/corefx#38762]
The following line of code results in "Fatal error. 0xC000001D"

``` csharp
String.Format(CultureInfo.InvariantCulture, "{0}", 1.0d);
```

We started observing this in build 3.0.100-preview7-012535.
build 3.0.100-preview7-012496 runs fine.

This is currently blocking all WPF test runs in Windows 7

Stack Trace:
Fatal error. 0xC000001D
   at System.Number+Grisu3.GetCachedPowerForBinaryExponentRange(Int32, Int32, In
t32 ByRef)
   at System.Number+Grisu3.TryRunShortest(DiyFp ByRef, DiyFp ByRef, DiyFp ByRef,
 System.Span`1<Byte>, Int32 ByRef, Int32 ByRef)
   at System.Number+Grisu3.TryRunDouble(Double, Int32, NumberBuffer ByRef)
   at System.Number.FormatDouble(System.Text.ValueStringBuilder ByRef, Double, S
ystem.ReadOnlySpan`1<Char>, System.Globalization.NumberFormatInfo)
   at System.Number.TryFormatDouble(Double, System.ReadOnlySpan`1<Char>, System.
Globalization.NumberFormatInfo, System.Span`1<Char>, Int32 ByRef)
   at System.Double.TryFormat(System.Span`1<Char>, Int32 ByRef, System.ReadOnlyS
pan`1<Char>, System.IFormatProvider)
   at System.Text.StringBuilder.AppendFormatHelper(System.IFormatProvider, Syste
m.String, System.ParamsArray)
   at System.String.FormatHelper(System.IFormatProvider, System.String, System.P
aramsArray)
   at System.String.Format(System.IFormatProvider, System.String, System.Object)

**Comment by danmosemsft** [comment]
@tannergooding for grisu3

**Comment by danmosemsft** [comment]
STATUS_ILLEGAL_INSTRUCTION?

**Comment by tannergooding** [comment]
@miguep, could you provide more context on the code that is failing. I'm not currently able to repro with the latest bits or `3.0.100-preview7-012535`

**Comment by miguep** [comment]
@tannergooding I'm running a console .NET Core app that only executes that line of code in Main, and I hit this issue.

I'm running on a Win7 x86 Enterprise VM. I can give you access to it.

**Comment by tannergooding** [comment]
> I'm running on a Win7 x86 Enterprise VM

Let me see if I can repro on Win10 x86 as well. It may be something specific to the 32-bit version.

**Comment by miguep** [comment]
it does not repro on Win10 as far as we can tell, only on Win7

**Comment by tannergooding** [comment]
The delta between the given "good" build and the given "bad" build is: https://github.com/dotnet/coreclr/compare/e2b3130f...56d57afaab

**Comment by AbhiAgarwal192** [comment]
@miguep  Yes even i tried reproducing it on windows 10 machine and was unable to reproduce.

**Comment by tannergooding** [comment]
> I'm running on a Win7 x86 Enterprise VM. I can give you access to it.

That would be great. I failed to repro locally on a Win7 x64 Enterprise VM (using the 32-bit SDK on SysWoW64). I am imaging a Win7 x86 Enterprise VM now to check that as well.

**Comment by tannergooding** [comment]
I'm still trying to confirm (need to finish building CoreCLR to get a JITDump, etc), but I believe this is due to https://github.com/dotnet/coreclr/pull/24917.

Namely, the failing method is utilizing `Math.Ceiling` which is handled as a named intrinsic. The compiler says it is supported if `compSupports(InstructionSet_SSE41)` here: https://github.com/dotnet/coreclr/blob/master/src/jit/importer.cpp#L19826

The failure is occurring on a Intel E6750 which is from 2007 and does not have SSE4.1 support.

CC. @CarolEidt, @MichalStrehovsky

**Comment by tannergooding** [comment]
The simplest and quickest fix is to probably change the check to say `compSupports(InstructionSet_SSE41) && !aot`

**Comment by CarolEidt** [comment]
> The simplest and quickest fix is to probably change the check to say compSupports(InstructionSet_SSE41) && !aot

That makes sense, and we should check to see where else the JIT might be checking for other instruction sets, outside of HW intrinsic code.

**Comment by tannergooding** [comment]
@miguep, this should be fixed in the next nightly build.
