### ISSUE TITLE
HTTP/2: Http2_FlowControl_ClientDoesNotExceedWindows failing

### ISSUE THREAD

**Issue by wfurt** [dotnet/corefx#38799]
This seems to be direct outcome of  #38226
I could not reproduce it and it is possible that the test is just too sensitive.  This should be investigated.

I'll keep looking as time permits.  

cc: @davidsh @scalablecory

**Comment by stephentoub** [comment]
Failed three more times here:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38817~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190624.2/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2~2FHttp2_FlowControl_ClientDoesNotExceedWindows
```
Alpine.39.Amd64.Open-x64-Debug
Get Repro environment
Unhandled Exception of Type Xunit.Sdk.FalseException
Message :
Assert.False() Failure
Expected: False
Actual:   True
Stack Trace :
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.Http2_FlowControl_ClientDoesNotExceedWindows() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 964
--- End of stack trace from previous location where exception was thrown ---
Ubuntu.1804.Amd64.Open-x64-Debug
Get Repro environment
Unhandled Exception of Type Xunit.Sdk.FalseException
Message :
Assert.False() Failure
Expected: False
Actual:   True
Stack Trace :
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.Http2_FlowControl_ClientDoesNotExceedWindows() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 957
--- End of stack trace from previous location where exception was thrown ---
Centos.7.Amd64.Open-x64-Debug
Get Repro environment
Unhandled Exception of Type Xunit.Sdk.FalseException
Message :
Assert.False() Failure
Expected: False
Actual:   True
Stack Trace :
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.Http2_FlowControl_ClientDoesNotExceedWindows() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 964
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by scalablecory** [comment]
I'm unable to repro this. I suspect CI system load may be making 500ms delays not enough. Going to update that and re-enable to see what happens.

**Comment by karelz** [comment]
@scalablecory what is status of this fix? Will it be ready by EOW?

**Comment by scalablecory** [comment]
I'm unable to repro; going to give it another shot once finished with other PRs but can't guarantee EOW.

**Comment by karelz** [comment]
Plan: Spend 1 more hour, then just re-enable.

**Comment by eiriktsarpalis** [comment]
I believe it's just a manifestation of the bug that was fixed in #39222. So I believe it's safe to re-enable.

**Comment by scalablecory** [comment]
I'm able to repro the failure now, so looking at it.

**Comment by geoffkizer** [comment]
Due to the recent flush change, this probably needs to get updated to use ByteAtATimeContent, like Http2_InitialWindowSize_ClientDoesNotExceedWindows did. Not sure if that's the issue you're seeing or not. It might explain why you were unable to repro recently, and now you can.

**Comment by scalablecory** [comment]
@geoffkizer yep, that's what I'm seeing.
