### ISSUE TITLE
Is UdpClient thread-safe?

### ISSUE THREAD

**Issue by chuyangliu** [dotnet/corefx#38825]
In my scenario, one UdpClient.ReceiveAsync() and multiple UdpClient.SendAsync() may be executed concurrently. Will this cause any race conditions?

**Comment by Tornhoof** [comment]
No it's not.
Take a look at the source.
https://github.com/dotnet/corefx/blob/eebe43224d8994b5b47bc2906c271ea6f256728b/src/System.Net.Sockets/src/System/Net/Sockets/UDPClient.cs#L18
The Buffer ist used in e.g. BeginReceive which is in turn used in ReceiveAsync.

**Comment by chuyangliu** [comment]
Yes it indicates multiple calls to ReceiveAsync() may not be thread-safe. But in my scenario, only one thread will call ReceiveAsync() while multiple threads may call SendAsync().

**Comment by Clockwork-Muse** [comment]
@chuyangliu - It uses `Socket` underneath, so the proper question is "is `Socket` safe for multiple `SendAsync` calls?" (I don't know the true answer to that, unfortunately).

**Comment by chuyangliu** [comment]
Looks like Socket is thread-safe per [MSDN](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket?view=netframework-4.8#thread-safety)?

Though UdpClient is a thin wrapper for Socket, it still accesses some shared class members inside [BeginSend()](https://github.com/dotnet/corefx/blob/eebe43224d8994b5b47bc2906c271ea6f256728b/src/System.Net.Sockets/src/System/Net/Sockets/UDPClient.cs#L286) so I'm not so sure about it.

**Comment by scalablecory** [comment]
@chuyangliu you can use multiple instances of `Socket` concurrently, but calling a single instance of `Socket` concurrently is not thread-safe for all scenarios.

Currently, particular to the connectionless (i.e. UDP) methods, they are not currently thread-safe if you use the socket without binding it first.
