### ISSUE TITLE
Block.Update returns different expression for identical children in different collection.

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#3883]
According to the documentation:

> If all of the children are the same, it will return this expression.

However, only the enumerables themselves are compared, so a different enumeration of the same children will incorrectly return a new expression.

**Comment by bartdesmet** [comment]
See my remarks on #3958. There's a series of other nodes that have the same behavior (MethodCall, New, Index, Invocation, ListInit, MemberInit, etc. come to mind), so we should do all of them if we decide it's a desirable change.

Is there inadvertent cloning behavior when the expression is run through a no-op visitor?

**Comment by JonHanna** [comment]
I'm going to close this now and expand the scope of #3958

**Comment by stephentoub** [comment]
@JonHanna, there are still two tests marked as ```[ActiveIssue(3883)]```.  Can they be re-enabled?  Should their number be changed if they're still failing?

**Comment by JonHanna** [comment]
Their number should be changed.
