### ISSUE TITLE
System.ComponentModel.Annotations is exposing members in netstandard2.0 missing from supported frameworks

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#38849]
Run API compat between netstandard2.0 reference and net461 and observe the following:
```
CannotRemoveAttribute : Attribute 'System.ObsoleteAttribute' exists on 'System.ComponentModel.DataAnnotations.AssociationAttribute' in the compatible-assembly but not the this-assembly. 
CannotChangeAttribute : Attribute 'System.AttributeUsageAttribute' on 'System.ComponentModel.DataAnnotations.DisplayAttribute' changed from '[AttributeUsageAttribute(AttributeTargets.Class | AttributeTargets.Field | AttributeTargets.Method | AttributeTargets.Parameter | AttributeTargets.Property, AllowMultiple=false)]' in the compatible-assembly to '[AttributeUsageAttribute(AttributeTargets.Field | AttributeTargets.Method | AttributeTargets.Parameter | AttributeTargets.Property, AllowMultiple=false)]' in the this-assembly. 
MembersMustExist : Member 'System.ComponentModel.DataAnnotations.DisplayFormatAttribute.GetNullDisplayText()' does not exist in the this-assembly but it does exist in the compatible-assembly. 
MembersMustExist : Member 'System.ComponentModel.DataAnnotations.DisplayFormatAttribute.NullDisplayTextResourceType.get()' does not exist in the this-assembly but it does exist in the compatible-assembly. 
MembersMustExist : Member 'System.ComponentModel.DataAnnotations.DisplayFormatAttribute.NullDisplayTextResourceType.set(System.Type)' does not exist in the this-assembly but it does exist in the compatible-assembly. 
CannotRemoveAttribute : Attribute 'System.ObsoleteAttribute' exists on 'System.ComponentModel.DataAnnotations.FilterUIHintAttribute' in the compatible-assembly but not the this-assembly. 
MembersMustExist : Member 'System.ComponentModel.DataAnnotations.RangeAttribute.ConvertValueInInvariantCulture.get()' does not exist in the this-assembly but it does exist in the compatible-assembly. 
MembersMustExist : Member 'System.ComponentModel.DataAnnotations.RangeAttribute.ConvertValueInInvariantCulture.set(System.Boolean)' does not exist in the this-assembly but it does exist in the compatible-assembly. 
MembersMustExist : Member 'System.ComponentModel.DataAnnotations.RangeAttribute.ParseLimitsInInvariantCulture.get()' does not exist in the this-assembly but it does exist in the compatible-assembly. 
MembersMustExist : Member 'System.ComponentModel.DataAnnotations.RangeAttribute.ParseLimitsInInvariantCulture.set(System.Boolean)' does not exist in the this-assembly but it does exist in the compatible-assembly. 
```
This means someone writing an assembly which depends on these APIs will fail with a MissingMethodException when run on desktop.

Fix here may be to version the assembly and only expose the new API in netstandard2.1 (or some other TFM that wouldn't be constrained by desktop compatibility).

**Comment by ericstj** [comment]
This library also exposed members missing from netcoreapp2.0:
```
Compat issues with assembly System.ComponentModel.Annotations:
TypesMustExist : Type 'System.ComponentModel.DataAnnotations.AssociatedMetadataTypeTypeDescriptionProvider' does not exist in the implementation but it does exist in the contract.
TypesMustExist : Type 'System.ComponentModel.DataAnnotations.MetadataTypeAttribute' does not exist in the implementation but it does exist in the contract.
Total Issues: 2
```

This library needs to refactor its references, and potentially consider treating itself as out-of-box for netcoreapp if folks intend to continue to add surface area.

**Comment by ajcvickers** [comment]
@ericstj Does this mean that if we need to target .NET Standard 2.0 with this package, then we these changes need to be reverted? (I don't think that targeting a different .NET Standard is an option here.)

**Comment by divega** [comment]
The package already targets multiple TFMs, so at least for the members and types must exist issues we just need to be careful to add them conditionally for new TFMs. Do you see any reason not to add new targets?

**Comment by ajcvickers** [comment]
@divega That may be an option. But I'm very nervous about making the .NET Framework/.NET Standard/packages.config problem worse since it is already a major source of problems for which we are not able to give any clear answers.

**Comment by ericstj** [comment]
Adding new targets is fine.  Note that you have a couple constraints here that need to be addressed in different ways.
1. Desktop constrains what you do in your `netstandard2.0` reference, to avoid this constraint you can add new API in either a `netstandard2.1` or `netcoreapp*` reference.  Each having the associated supported framework implications.
2. The package doesn't carry it's necoreapp2+ implementation today, meaning you can never ship new functionality to any past `netcoreapp` framework.  This can be solved by removing the place-holder and permitting the package to carry an OOB implementation (similar to what we do for System.Collections.Immutable, and others).

**Comment by divega** [comment]
> But I'm very nervous about making the .NET Framework/.NET Standard/packages.config problem worse

I think public APIs for existing targets should not carry any changes, so for better or for worse, that shouldn't change. There is always risk that we make a mistake (like this issue), but I think that comes with owning a package that ships from CoreFx.

@ericcstj that makes sense to me, but I think we may need guidance on how to fix this issue in the actual code, given our experience authoring packages here is limited. 

I don't think we need to take the `netcoreapp` implementation OOB. We haven't had any cases in which we needed to ship new functionality for .NET Core in an OOB fashion.

Just for completeness, is there a path to merge these APIs into actual .NET Standard 2.1 and stop publishing the package from this branch? I imagine a few problems that may make that unfeasible but I am sure you know better.

**Comment by ericstj** [comment]
Since the package is already part of .NETCoreApp maybe you can just stop modifying the API and stop producing the package now.  Do you have any reason to ship new API and make it available anywhere other than .NETCoreApp?  If not, then let's just delete the package and that should fix this issue.  It means that folks building `netstandard2.0` libraries will only see the API from last release, but that may be OK.

**Comment by divega** [comment]
That was more or less the motivation behind my question, with the difference that I think there is still some value in these changes being available for .NET Standard 2.1, not just .NET Core 3.0.

**Comment by ericstj** [comment]
These don't need to be *part of .NETStandard2.1 to be available for applications targeting .NETStandard2.1.  You can expose a .NETStandard2.1 reference from the package.  You could place all the "new" API in the .NETStandard2.1 reference.  Next release you'll be in the same position you are now, unless you decide to stop representing the API as "provided by" the framework.  Path here is up to you, let me know which direction you're thinking and I can help describe the changes.

**Comment by divega** [comment]
> These don't need to be *part of .NETStandard2.1 to be available for applications targeting .NETStandard2.1.

@ericstj Yes, I get that.  I was just trying to explore if making in part of .NET Standard 2.1 was a possibility. 

Anyway, I discussed it with @ajcvickers and we agreed that we prefer to go in the other direction: include a real implementation assembly in the package that contains any API improvements and can be used from any modern .NET implementations. 

I will contact you offline so we can discuss how exactly that looks like.
