### ISSUE TITLE
Inconsistent readonly struct System.Diagnostics.CounterSample on desktop

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#38851]
https://github.com/dotnet/corefx/pull/24997 made this struct readonly, including in the nestandard2.0 reference assembly, but it is not readonly on desktop.  Is that a problem?  I don't think it should be, but I wanted to raise it as currently API Compat will flag this.

```
CannotRemoveAttribute : Attribute 'System.Runtime.CompilerServices.IsReadOnlyAttribute' exists on 'System.Diagnostics.CounterSample' in the compatible-assembly but not the this-assembly. 
TypeCannotChangeClassification : Type 'System.Diagnostics.CounterSample' is marked as readonly in the compatible-assembly so it must also be marked readonly in the this-assembly. 
```

**Comment by stephentoub** [comment]
It should not be a problem as long as we don't violate the readonly-ness.

**Comment by ericstj** [comment]
Looks like the same is true for `System.ServiceProcess.SessionChangeDescription`

**Comment by wtgodbe** [comment]
@Anipik I don't think this is a must-have for 3.0, given that ZBB is tomorrow I'm moving it to future

**Comment by ericstj** [comment]
FWIW this is a regression from the past release, if you fix it you need to fix it now.  The work is to just investigate wether or not the structs are actually treated as readonly on desktop.

**Comment by ericstj** [comment]
I checked both and they do behave as readonly.
