### ISSUE TITLE
HttpClient has 20 second delay when finding proxy that does not exist.

### ISSUE THREAD

**Issue by logic01** [dotnet/corefx#38882]
dotnet core 2.2
HttpClientFactory
HttpClient

The HttpClient takes 20 seconds on the first request when `HttpClientHandler() { UseProxy = true }`,  the default setting, when no proxy is configured.

To resolve this we have to set `HttpClientHandler() { UseProxy = false}`.

We identified this issue during our upgrade from core 2.0 to core 2.2 and the subsequent refactor of our HttpClient usages to follow new conventions. Here is how it manifested in our system.

The first request was taking 20+ seconds to hit the network. We connected a remote debug session to our Dev server and stuck a debug symbol on

 `var response = await client.GetAsync("http://localhost:8888/system");`

We then had Fiddler setup to listen on that port. For the first request there was a 20+ second interval between the GetAsync() and the request showing up in fiddler. Subsequent requests showed up immediately.

Example project.
```
public class Provider : IProvider
{
private readonly IHttpClientFactory _clientFactory;

public Provider(IHttpClientFactory clientFactory)
{
_clientFactory = clientFactory;
}

public async Task<HttpResponseMessage> SubmitRequest()
{
var client = _clientFactory.CreateClient();
client.Timeout = TimeSpan.FromSeconds(120);

var start = DateTime.Now;
var response = await client.GetAsync("http://localhost:53702/system");
var span = start - DateTime.Now;

return response;
}
}
```

If we ran the application locally using IIS Express we did not see this issue. We have several environments and some experienced the issue while others did not.

Setting  `HttpClientHandler() { UseProxy = false}` resolved the performance issue in all environments.

Suggestions:

1. UseProxy should default to false.
2. It should not take 20 seconds to identify there is no proxy.

**Comment by stephentoub** [comment]
cc: @davidsh

**Comment by davidsh** [comment]
This is a common problem which is dependent on the network environment. It is not something that can be controlled via .NET Core.

Is this on Windows or Linux?  I suspect Windows.  .NET Core uses a Windows API that communicates with a service "WinHttp AutoProxy Discover Service". Depending on the network configuration, discovering a proxy can be time consuming as network I/O needs to happen with WPAD protocol.

If this is Windows, one workaround is to turn off this checkbox, "Automatically Detect Settings".  That will prevent any proxy discovery process on the network.
![image](https://user-images.githubusercontent.com/7684835/60108164-01b51080-971d-11e9-8a73-4d199d02e809.png)

The discovery process is cached for a while in both the Windows native layer and .NET Core. So, if it takes a long time to eventually fail to discover a proxy, subsequent HTTP requests won't bother looking for one.

>Suggestions:
UseProxy should default to false.

The current API behavior is 'UseProxy = true'.  We can't change the default of that unfortunately.

**Comment by logic01** [comment]
Additional Notes: If you allow the HttpClient to idle for 2 minutes, the default timeout, then the very next request will take 20+ seconds again and subsequent will take < 1ms.

**Comment by karelz** [comment]
Triage:
We didn't get response on info about local settings.
It seems like it is a bad config, or something specific which we can;t diagnose without additional info.
Closing for now, feel free to reopen if there is more info available.
