### ISSUE TITLE
XmlBaseReader removes significant whitespace when wrapping another reader.

### ISSUE THREAD

**Issue by davster** [dotnet/corefx#3888]
This issue produces data corruption because element contents are modified.

We were able to condense the repro to a few lines in LinqPad:
var sourceXml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><Value>a\r\nb\r\nc</Value>";
XmlReaderSettings settings = new XmlReaderSettings() { IgnoreWhitespace = true };
var streamToValidate = new MemoryStream(Encoding.UTF8.GetBytes(sourceXml), false);
XmlReader dictionaryReader = XmlDictionaryReader.CreateTextReader(streamToValidate, new XmlDictionaryReaderQuotas());
//// XmlReader dictionaryReader = XmlReader.Create(streamToValidate, settings);
XmlReader validatingReader = XmlReader.Create(dictionaryReader, settings);
XDocument.Load(validatingReader).Dump();

Uncommenting the second dictionaryReader instead of the XmlDictionaryReader doesn’t reproduce the bug.

**Comment by yitzhaks** [comment]
If I’m not mistaken, the bug is in _`XmlBaseReader.MoveToWhitespaceText()`_:
    protected XmlTextNode MoveToWhitespaceText()
    {
        if (whitespaceTextNode == null)
        {
            whitespaceTextNode = new XmlWhitespaceTextNode(bufferReader);
        }
        **if (nsMgr.XmlSpace == XmlSpace.Preserve)**
            whitespaceTextNode.NodeType = XmlNodeType.SignificantWhitespace;
        else
            whitespaceTextNode.NodeType = XmlNodeType.Whitespace;
        MoveToNode(whitespaceTextNode);
        return whitespaceTextNode;
    }

There should be a check there if we’re inside a content node, and return SignificantWhitespace if we are. There should also be some logic that makes sure the content node isn’t made up entirely of whitespace, in which case the node type should be Whitespace after all.

**Comment by krwq** [comment]
Hey @khdang, could you check if this is the same issue as https://github.com/dotnet/corefx/issues/5206 and close?

**Comment by khdang** [comment]
Thanks @krwq This is the same issue as #5206. This is an issue on Desktop which is in discussion to have an appropriate resolution given it could introduce a breaking change. Once we have the right fix we will create an issue to port the fix to NetCore.
