### ISSUE TITLE
The Utf8JsonWriter API xml documentation could be improved

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#38896]
Some of the text within the xml tags of the Utf8JsonWriter APIs could be improved by re-wording them. Whatever change is made, should be applied consistently across all the API overloads.

Address some of the feedback including:
https://github.com/dotnet/corefx/pull/38864#discussion_r297200606
https://github.com/dotnet/corefx/pull/38864#discussion_r297201708
https://github.com/dotnet/corefx/pull/38864#discussion_r297231404
https://github.com/dotnet/corefx/pull/38864#discussion_r297260018

**Comment by safern** [comment]
Already started tackling this guy. Assigning.
