### ISSUE TITLE
Refactor and clean up the SpanTestHelper helpers for asserting that a ref struct method throws

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#38891]
See feedback from https://github.com/dotnet/corefx/pull/38865

Consider moving the helper to `AssertExtensions`

**Comment by Marusyk** [comment]
Please assign it to me. I've already prepared PR.

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/dotnet/corefx/pull/39186
