### ISSUE TITLE
HTTP2: STREAM_CLOSED error after request cancellation

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#38913]
I found this issue by running @stephentoub's stress code from #38911 against local IIS, with the "GET w/ cancellation" operation enabled.

This results in a bunch of errors that look as follows:

```System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.Net.Http.Http2ProtocolException: The HTTP/2 request failed with protocol error 'STREAM_CLOSED' (0x5).
   at System.Net.Http.Http2Connection.ProcessHeadersFrame(FrameHeader frameHeader) in C:\github\geoffkizer\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs:line 316
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync() in C:\github\geoffkizer\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs:line 224
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\github\geoffkizer\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\Http2Connection.cs:line 1462
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in C:\github\geoffkizer\corefx\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 539
```

I believe what's happening here is:
(1) We are cancelling the request, sending a RST_STREAM, and removing the stream from the stream dictionary before we've received the entire response
(2) The server already has sent additional frames on this response before it processes the RST_STREAM
(3) We receive additional frames on this stream and treat this as an error

We need to change our processing of frames on closed streams to simply ignore them, not generate a stream error, as per #35652.

**Comment by geoffkizer** [comment]
@wfurt, why aren't cancellation tests catching this? It's not really stress related. Can you point me to the relevant tests?

**Comment by geoffkizer** [comment]
We should ensure we have tests that send additional frames after receiving a RST_STREAM from cancellation (or other error) and ensure that this doesn't cause a connection error, and that subsequent requests can succeed on the same connection.

**Comment by wfurt** [comment]
OK. I'm also working on porting some older tests to GenericLoopback but they may not cover this as HTTP/1 is quite different.

**Comment by geoffkizer** [comment]
Yeah, unfortunately, cancellation is one area where things work quite differently between HTTP/1.1 and HTTP2.

**Comment by geoffkizer** [comment]
#38918 improves this, but I'm still seeing exceptions because it's possible that a request is cancelled while we are in the middle of processing a HEADER or DATA frame. That is:

(a) we successfully retrieve the http2Stream from the dictionary
(b) request is cancelled, setting its state to aborted
(c) we get a callback like OnResponseHeader, and we throw because the request is now aborted

We need to just ignore callbacks like OnResponseHeader if we are in the aborted state.

**Comment by stephentoub** [comment]
This same error message shows up as "Error 8" in https://github.com/dotnet/corefx/issues/38911.  I assume it's the same root cause, even though the call stack is different?

**Comment by geoffkizer** [comment]
> I assume it's the same root cause, even though the call stack is different? 

I assume so, yeah.

**Comment by geoffkizer** [comment]
Note, #38918 fixes the product issue. We still need to update tests.
