### ISSUE TITLE
Portable PDB specification dot not match the implementations: Module table should not be copied

### ISSUE THREAD

**Issue by gfraiteur** [dotnet/corefx#38944]
The [Portable PDB Specification](https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/specs/PortablePdb-Metadata.md) specifies: 

> "#~" stream shall only contain debugging information tables defined above and *a copy of the Module table from the type system metadata* but no other type system metadata table. The Module table effectively links the debugging metadata to the corresponding type system metadata.

Microsoft implementations of the specification does not copy the Module table to the `#~` stream, but only references it. Visual Studio Code Coverage, and `dumpbin /pdbpath:verbose` do not work when a Portable PDB has the Module table in the PDB File. However Visual Studio Debugger accepts the Module table.

PostSharp versions up to 6.2.8 emitted the Module table according to the spec. We will change our implementation to match with the reality.

**Comment by tarekgh** [comment]
Issue moved to [dotnet/coreclr #25432](https://github.com/dotnet/coreclr/issues/25432) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jkotas** [comment]
@tarekgh Both the specification and the code that reads and writes the portable PDB format lives in CoreFX repo. Thus, this issue should live in CoreFX repo as well.

**Comment by jkotas** [comment]
cc @tmat

**Comment by tarekgh** [comment]
Thanks @jkotas. I didn't know that.

**Comment by tmat** [comment]
@gfraiteur The spec is incorrect. Will update it. IIRC we copied the Module table in early versions but then dropped it and forgot to update the spec.

**Comment by gfraiteur** [comment]
Thank you. The next builds of PostSharp will reflect the updated spec.

@tmat @jkotas Greetings from (hot) Prague :)
