### ISSUE TITLE
Revising System.Net.Sockets contract v4.1

### ISSUE THREAD

**Issue by SidharthNabar** [dotnet/corefx#3895]
This issue discusses the changes being proposed in the current API surface of `System.Net.Sockets` contract version 4.1 in .NET Core. Version 4.1 is currently at an experimental stage and this revision takes it closer to the shape we intend to release at ASP.NET 5 RTM.

## Rationale

.NET Core as a platform is intended to be modern, performant and cross-plat, so we need to ensure that the API surface is streamlined and adapted accordingly. This revision omits some of the Windows-specific or legacy types and methods that were present in the earlier (beta8) version of 4.1, and now includes new methods that follow the recommended TPL (async/await) pattern.

## Proposed API and Usage

Following are the new Task Parallel Library-compatible methods being added to the class `System.Net.Sockets.Socket`. These are being added as extension methods to `Socket` class so that they can be supported on .NET framework via an OOB package as well (since we cannot add instance methods to types that are already defined in the .NET framework)

```c#
public static partial class SocketTaskExtensions
    {
        public static System.Threading.Tasks.Task<Socket> AcceptAsync(this System.Net.Sockets.Socket socket)

        public static System.Threading.Tasks.Task<Socket> AcceptAsync(this System.Net.Sockets.Socket thisSocket, System.Net.Sockets.Socket acceptSocket)

        public static System.Threading.Tasks.Task ConnectAsync(this System.Net.Sockets.Socket socket, System.Net.EndPoint remoteEndPoint)

        public static System.Threading.Tasks.Task ConnectAsync(this System.Net.Sockets.Socket socket, System.Net.IPAddress address, int port)

        public static System.Threading.Tasks.Task ConnectAsync(this System.Net.Sockets.Socket socket, System.Net.IPAddress[] addresses, int port)

        public static System.Threading.Tasks.Task ConnectAsync(this System.Net.Sockets.Socket socket, string host, int port)

        public static System.Threading.Tasks.Task<int> ReceiveAsync(this System.Net.Sockets.Socket socket, System.ArraySegment<byte> buffer, System.Net.Sockets.SocketFlags socketFlags)

        public static System.Threading.Tasks.Task<int> ReceiveAsync(this System.Net.Sockets.Socket socket, System.Collections.Generic.IList<System.ArraySegment<byte>> buffers, System.Net.Sockets.SocketFlags socketFlags)

        public static System.Threading.Tasks.Task<System.Net.Sockets.SocketReceiveFromResult> ReceiveFromAsync(this System.Net.Sockets.Socket socket, System.ArraySegment<byte> buffer, System.Net.Sockets.SocketFlags socketFlags, System.Net.EndPoint remoteEndPoint)        

        public static System.Threading.Tasks.Task<System.Net.Sockets.SocketReceiveMessageFromResult> ReceiveMessageFromAsync(this System.Net.Sockets.Socket socket, System.ArraySegment<byte> buffer, System.Net.Sockets.SocketFlags socketFlags, System.Net.EndPoint remoteEndPoint)

        public static System.Threading.Tasks.Task<int> SendAsync(this System.Net.Sockets.Socket socket, System.ArraySegment<byte> buffer, System.Net.Sockets.SocketFlags socketFlags)

        public static System.Threading.Tasks.Task<int> SendAsync(this System.Net.Sockets.Socket socket, System.Collections.Generic.IList<System.ArraySegment<byte>> buffers, System.Net.Sockets.SocketFlags socketFlags) 

        public static System.Threading.Tasks.Task<int> SendToAsync(this System.Net.Sockets.Socket socket, System.ArraySegment<byte> buffer, System.Net.Sockets.SocketFlags socketFlags, System.Net.EndPoint remoteEndpoint)

    }

public struct SocketReceiveFromResult  
  {  
        public int ReceivedBytes;  
        public EndPoint RemoteEndPoint;  
  }  

public struct SocketReceiveMessageFromResult  
 {  
        public int ReceivedBytes;  
        public SocketFlags SocketFlags;  
        public EndPoint RemoteEndPoint;  
        public IPPacketInformation PacketInformation;  
     }  

```

The usage of these new methods is the same as other APIs in .NET that follow the async/await pattern. For example:

```c#
private async void ConnectToServerAsync () 
{
var socket = new Socket(SocketType.Stream, ProtocolType.Tcp);
await socket.ConnectAsync(serverAddress, serverPort);
// Use connected socket.
}
```

## Pull Request
The pull request for this API change is #3655. It shows the diff from the previous revision of this contract, so you can see the types and methods that are no longer included in the proposed revision.

## Updates from Discussion
- Revised initial proposal based on API review feedback from @terrajobst 

- Revised the signatures of methods `ReceiveFromAsync` and `ReceiveMessageFromAsync` based on feedback from @CIPop and @stephentoub - these async methods were modifying multiple variables through `ref` and `out` parameters. In order to avoid this, we have now defined their return values as structs (`SocketReceiveFromResult` and `SocketReceiveMessageFromResult`) that contain all the variables returned by the respective async methods. These new structs will also be added to the contract.

- Also revised `ReceiveAsync` and `SendAsync` methods to accept `ArraySegment` as input parameter, in order to match existing APIs.

**Comment by SidharthNabar** [comment]
@joshfree @terrajobst @weshaggard @stephentoub  PTAL

**Comment by davidsh** [comment]
cc: @josguil @CIPop

**Comment by pgavlin** [comment]
@SidharthNabar is this discussion intended to review only the proposed TPL API additions? I think that we need to discuss some of the APIs proposed for removal in #3655 as well.

**Comment by svick** [comment]
How does this address the performance concerns raised by @stephentoub's 2011 article [Awaiting Socket Operations](http://blogs.msdn.com/b/pfxteam/archive/2011/12/15/10248293.aspx)?

Or is this meant as a convenient API for the cases where the allocations are acceptable?

**Comment by CIPop** [comment]
@svick This is meant as a convenient API and not as a high perf one.
You will still achieve highest perf using the `SocketAsyncEventArgs` APIs.

**Comment by SidharthNabar** [comment]
@pgavlin - Yes, we also need to discuss the APIs that are no longer included in this latest revision. We were thinking of creating a separate linked issue so as to not distract from the API review of the added APIs here. Is that okay or would you prefer having it in the same issue?

**Comment by pgavlin** [comment]
@SidharthNabar Either approach is fine, as long as it's clear that the removal of those APIs (as well as other possible additions) must also go through API review.

**Comment by terrajobst** [comment]
@weshaggard and I discussed this. While extension methods seem a bit odd here, we can see the benefits in order to provide the Task functionality for .NET Framework without having to rev the .NET Framework.

Other feedback:

* `thissocket`. I'd call the `this` parameter simple `socket`. That's inline what we do else where.
* `remoteEP`. Spell end point out. If too long, consider dropping `remote`.
* `AcceptAsync(this System.Net.Sockets.Socket thisSocket, System.Net.Sockets.Socket acceptSocket, int receiveSize)`. The order of the last two parameters seems strange. I'd swap them to make the consisten with the shorter overload.
* No cancellation token? It seems odd that none of the operations can be cancelled.

**Comment by pgavlin** [comment]
@SidharthNabar re: the `receiveSize` parameter to `AcceptAsync`: this API is not trivially supportable cross-platform. Do we have usage data on its APM/synchronous/Async equivalents? If this capability is not widely used (and IIRC @CIPop mentioned that it's not applicable to most address families), I'd prefer that we not add it to the async methods (and discuss its removal from other methods in #3913).

**Comment by SidharthNabar** [comment]
@terrajobst Thanks for the feedback.
>  thissocket . I'd call the  this  parameter simple  socket . That's inline what we do else where
Agreed - fixed.

>  remoteEP . Spell end point out. If too long, consider dropping  remote .
Agreed. Fixed.

> AcceptAsync(this System.Net.Sockets.Socket thisSocket, System.Net.Sockets.Socket acceptSocket, int receiveSize) . The order of the last two parameters seems strange. I'd swap them to make the consisten with the shorter overload.
Agree with the feedback - however, the current BeginAccept method had this order of parameters which is why the new async one was also designed that way. In any case, due to @pgavlin 's feedback that this is not cross-plat friendly, we are removing both the overloads that take the `receiveSize` parameter.
> No cancellation token?
Agreed. We are currently unclear on if and how we can support cancellation for all socket operations in a cross-plat way. For now, we propose to add these methods and in a subsequent iteration, we will add the overloads with CancellationToken (similar to HttpClient, Stream and other .NET APIs)

@pgavlin - Agreed. Removing the overloads that take `receiveSize` as input. We can add it back at a later time if we find that there are scenarios that require it.

**Comment by terrajobst** [comment]
Sounds good!

**Comment by SidharthNabar** [comment]
Made updates based on inputs from @CIPop and @stephentoub . @weshaggard , @terrajobst - please take a look (described the changes in the discussion section above)

**Comment by KrzysztofCwalina** [comment]
Our API reviews are on Tuesdays. We will review this one tomorrow.

**Comment by terrajobst** [comment]
A few more questions:

* You missed one occurence of `thissocket`.
* Why are these structs?
* The structs shouldn't have public fields. They should be properties and it seems they should be read only.

**Comment by stephentoub** [comment]
> Why are these structs?

That was my initial suggestion, to avoid needing to allocate an additional object to hand back the results.  There is of course also the cost of copying to think about, but in this case, with this few number of fields and small size, struct would seem to be the better choice, barring time to do a real perf investigation.

**Comment by terrajobst** [comment]
That makes sense. I assume the fields should be still be read-only properties, though?

**Comment by stephentoub** [comment]
> I assume the fields should be still be read-only properties, though?

I'm fine with that; no strong opinion.  If we do that, then the types would obviously also need a constructor that takes all the values.

**Comment by SidharthNabar** [comment]
@terrajobst 

> You missed one occurence of  thissocket .
Sorry, that was a typo. Fixed now.

> Why are these structs?
Stephen's answer above applies.

> The structs shouldn't have public fields. They should be properties and it seems they should be read only.
We have them as public fields in order to be consistent with the earlier API and usage where these were ref/out parameters and were not read-only. Making them read-only may break existing developer scenarios where they depend on the ability to modify the individual fields. Please let us know if that is okay.

**Comment by SidharthNabar** [comment]
The PR for this issue is merged and the API review is completed. Hence closing this issue.

**Comment by CIPop** [comment]
Marking with NetFX port consider to track the port of Task-based Socket APIs to Desktop.
