### ISSUE TITLE
HTTP/2 POST w/ Expect: 100-continue never completing

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#38968]
Start with the code in https://github.com/dotnet/corefx/issues/38911, but change:
- `ConcurrentRequests` = 1
- `AppxContentLength` = 100_000

Using the latest bits in master, the first request hangs indefinitely. (I'm running against a Preview6 Kestrel.)

cc: @geoffkizer, @scalablecory, @davidsh, @wfurt

**Comment by davidsh** [comment]
@wfurt

**Comment by stephentoub** [comment]
Looks like a credit manager problem.  I debugged into it, and we're stuck trying to send the request body content, waiting on the credit manager:
```
Name:        System.Net.Http.CreditManager+Waiter
MethodTable: 00007fff39fca4f8
EEClass:     00007fff39fd8b98
Size:        32(0x20) bytes
File:        C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0-preview6-27804-01\System.Net.Http.dll
Fields:
              MT    Field   Offset                 Type VT     Attr            Value Name
00007fff398cb220  400037f        8         System.Int32  1 instance             1696 Amount
00007fff39fe4a18  4000380        0 ...Private.CoreLib]]  0 instance 000002efe8089b08 TaskCompletionSource
```
but the credit manager currently has none to offer:
```
0:035> !do 000002efe80772a0
Name:        System.Net.Http.CreditManager
MethodTable: 00007fff39fc97b8
EEClass:     00007fff39fd83a8
Size:        32(0x20) bytes
File:        C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0-preview6-27804-01\System.Net.Http.dll
Fields:
              MT    Field   Offset                 Type VT     Attr            Value Name
00007fff398cb220  400037c       10         System.Int32  1 instance                0 _current
00007fff39fca7b8  400037d        8 ...System.Net.Http]]  0 instance 000002efe8089b70 _waiters
00007fff398c71e8  400037e       14       System.Boolean  1 instance                0 _disposed
```
(Ignore the version numbers in the file names here... I overwrote my Preview6 shared framework's System.Net.Http with one I built out of master.)

**Comment by geoffkizer** [comment]
Regular POST works though?

**Comment by stephentoub** [comment]
> Regular POST works though?

Correct.  I added a bunch of tracing (which I'll put up a PR for), and it looks like the key difference is that in the POST case, we're sending window updates, but in the POST w/ Expect: 100-continue case, we don't send any.

**Comment by stephentoub** [comment]
I think the problem is here:
https://github.com/dotnet/corefx/blob/8628de7f486c825b6055ac85feb2c3f4f3981c75/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs#L176
We wait for the entire body to send before returning the response stream to the caller.  That means the response stream can't pull on the data sent by the server, which means we effectively deadlock: we send a bunch of data, the server echos it back (per the stress program), but we then never read from the response data, so the response window fills up and the server stops sending and stops reading from the request, so the request window fills up... and we're hung.

**Comment by geoffkizer** [comment]
That does seem like a problem. Specifically, since we intend to support duplex communication here, we shouldn't be waiting for the request body to complete sending before we return the response. In fact, I'm not really sure how duplex works at all, given this... Am I missing something?

This seems like something we should have a unit test for. What tests do we have for duplex communication?

**Comment by stephentoub** [comment]
> In fact, I'm not really sure how duplex works at all, given this... Am I missing something?

This path is only taken for Expect: 100-continue; we probably just lack tests for duplix + 100-continue.

Shouldn't be hard to fix... looking at it this morning...
