### ISSUE TITLE
CultureInfoConverter.GetCultureName(null) throws NRE

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#38979]
Should return null

```cs
public static IEnumerable<object[]> GetCultureName_TestData()
{
    yield return new object[] { new CultureInfo("fr-FR"), new CultureInfo("fr-FR").Name };
    yield return new object[] { new CultureInfo("es-MX"), new CultureInfo("es-MX").Name };
    yield return new object[] { null, null };
}

[Theory]
[MemberData(nameof(GetCultureName_TestData))]
public void GetCultureName_Invoke_ReturnsExpected(CultureInfo culture, string expected)
{
    var converter = new SubCultureInfoConverter();
    Assert.Equal(expected, converter.GetCultureName(culture));
}

private class SubCultureInfoConverter : CultureInfoConverter
{
    public new string GetCultureName(CultureInfo culture)
    {
        return base.GetCultureName(culture);
    }
}
```

**Comment by maryamariyan** [comment]
In .NET Framework the behavior is also to throw NRE.

Also looking at e.g. TypeConverter.ConvertFromInvariantString method [here](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.typeconverter.convertfrominvariantstring?view=netframework-4.8#System_ComponentModel_TypeConverter_ConvertFromInvariantString_System_String_) shows that can throw with NSE if it couldn't do the operation.

Also note the remarks at the same docs page:
```
An exception is raised if the string cannot be converted into the appropriate object. The default implementation always returns null.

Use the context parameter to extract additional information about the environment from which this converter is invoked. This parameter can be null, so always check it. Also, properties on the context object can return null.

See also
ITypeDescriptorContext
```

cc: @tarekgh @safern

**Comment by maryamariyan** [comment]
As I spoke offline with @tarekgh it might seem like a good idea to continue throwing so as to differentiate from default behavior which returns null.

**Comment by hughbe** [comment]
There is precedent to fix things like NREs in .Net core

**Comment by maryamariyan** [comment]
That makes sense. I think though, the question is whether to return null or rather NSE.

**Comment by safern** [comment]
Yes I also agree we should throw an ANE instead. Even though .NET Framework throws a NRE it is better to instead throw an ANE from the user perspective.

We’ve decided to throw NRE only where in hot paths where perf matters much and we want to avoid doing the null check.

**Comment by hughbe** [comment]
I think the question is to return null or to throw ANE

**Comment by maryamariyan** [comment]
Yes.

**Comment by safern** [comment]
As part of the nullable annotations effort we've been trying to avoid more nulls as part of the framework, being said that, I don't think we should return null. I think we should instead throw ANE.

cc: @stephentoub thoughts?

**Comment by maryamariyan** [comment]
@danmosemsft we're inclined towards throwing ANE. What are your thoughts?

**Comment by danmosemsft** [comment]
Makes sense given that brings us closer to .NET Framework and documented behavior.

**Comment by tarekgh** [comment]
I agree throwing is better here than returning null. if the caller need to check null after the call, the caller can still check null before the call. or try catch the exception.

**Comment by hughbe** [comment]
Fix to ANE instead of NRE is in https://github.com/dotnet/corefx/pull/38980
