### ISSUE TITLE
What's the different between "dnxcore50" and "dotnet" target?

### ISSUE THREAD

**Issue by Kagamine** [dotnet/corefx#3897]

**Comment by ericstj** [comment]
'dotnet' is the new portable.  It indicates that your project/package wants to run on a package-based platform wherever all of your dependencies are supported.  

'dnxcore' is one package based platform.  It's the core-clr based ASP.NET v5.

**Comment by khellang** [comment]
@Kagamine You can read more about the `dotnet` TFM at http://blog.nuget.org/20150729/Introducing-nuget-uwp.html :smile:

**Comment by khellang** [comment]
@Kagamine @onovotny also has a great blog post on `dotnet`; https://oren.codes/2015/07/29/targeting-net-core/
