### ISSUE TITLE
HTTP2: Retry on GOAWAY

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#39013]
When we receive a GOAWAY, we should retry any requests with stream ID > the "last stream ID" parameter received as part of the GOAWAY. We're not doing this currently. We're aborting the streams without allowing them to be retried.

https://tools.ietf.org/html/rfc7540#section-6.8

**Comment by geoffkizer** [comment]
Found as part of #38911

**Comment by krwq** [comment]
https://github.com/dotnet/corefx/pull/39036 is adding 2 test cases disabled with this issue

**Comment by krwq** [comment]
@geoffkizer @stephentoub what should happen when server already has send headers/body which client might have already acted upon? Exception? (we already have a test case testing this: GoAwayFrame_AbortAllPendingStreams_StreamFailWithExpectedException but it also expects exception for the case which I think should be retried)

I could imagine from user perspective exception probably makes more sense to let the user know "whatever I just sent you, disregard".

Another question: For GOAWAY which sets error which is not NO_ERROR, i.e. ENHANCE_YOUR_CALM should we attempt to retry? My gut tells me I'd expect a restart as a user but I wanted double check with you before I send a patch.

**Comment by stephentoub** [comment]
> but it also expects exception for the case which I think should be retried

What case do you think should be retried?

**Comment by krwq** [comment]
@stephentoub test currently sends GOAWAY with `lastStreamId = 0` which essentially means anything can be retried.

From server perspective the situation is simple: nothing got processed
From client perspective I believe we should retry only when user have not already started reading the content and in any other case we should signal that they might have read something bogus (signal => throw an exception)

**Comment by krwq** [comment]
@stephentoub, I've added my pending changes (which I believe is correct fix) here:
https://github.com/dotnet/corefx/pull/39127

marked it as draft until you confirm this is the expected behavior

**Comment by geoffkizer** [comment]
> what should happen when server already has sent headers/body which client might have already acted upon?

As I commented on the PR, this is invalid behavior from the server. so we can kind of do whatever we want, including failing everything or failing requests that have already been processed, etc.

> My proposal: retry if server has not started responding, exception otherwise

Sounds good to me

> Another question: For GOAWAY which sets error which is not NO_ERROR, i.e. ENHANCE_YOUR_CALM should we attempt to retry? My gut tells me I'd expect a restart as a user but I wanted double check with you before I send a patch.

My assumption is that if the server is sending GOAWAY with error != NO_ERROR, then it's going to close the connection immediately afterward. Of course, we can't necessarily assume the server is going to do that; but in general, indicating an error like this probably means the connection is not usable anymore.

Regardless, we should still retry based on last-stream-id.

> My proposal: GOAWAY => retry (ignore error code, only don't retry for cases mentioned by previous question)

Sounds good to me.
