### ISSUE TITLE
TryValidateObject should use fluent model builder configuration

### ISSUE THREAD

**Issue by HakanL** [dotnet/corefx#39018]
Currently TryValidateObject is only using the data annotation attributes on the models, but since it's perfectly valid to use fluent configuration (the Scaffold-DbContext command is using that for example) I think the TryValidateObject should be able to use the fluent metadata in EF Core (like HasMaxLength, etc) to validate the model as well.

**Comment by ajcvickers** [comment]
@HakanL Thanks for the suggestion. The validation done by data annotations is independent of EF Core. There is no way for this validation to read the EF configuration. Further, we explicitly didn't add domain model validation to EF Core because it is usually handled better by other layers--for example, in your ASP.NET controller or similar--and this also often needs to be consistent with U.I. validation. EF is not well-placed to do this.

**Comment by HakanL** [comment]
Ok, I understand that we don't want any dependencies between EF Core and the core DataValidation/Annotations package. But the problem is when you try to save strings (for example) that are too long, and using the fluent EF configuration (HasMaxLength and so on) and call TryValidateObject then it all passes. But when attempting to actually save (to SQL Server) you just get the generic "string or binary truncated" message, which doesn't tell you which property/column was causing it. I agree that data validation in general should be done in other layers, but there is no component (to my knowledge) that can use the fluent DB config to validate. Maybe there should be a new component that can bridge DataValidation/Annotations with EF Core? I tried to open a ticket in the EF Core repo but got directed over here.

**Comment by ajcvickers** [comment]
@HakanL This is something that we are not planning to do in EF Core. Is there anything preventing you from using data annotations for this validation?

**Comment by HakanL** [comment]
@ajcvickers Yes, the data context is generated (reverse-engineered) using the Scaffold-Context command, which is using fluent configuration, to my knowledge it doesn't have a setting to use attributes instead of fluent.

**Comment by ajcvickers** [comment]
@HakanL See https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell#scaffold-dbcontext

**Comment by HakanL** [comment]
@ajcvickers Ohhh #embarred :) Thanks for your help! Granted it would be nice to have a validation that could use the fluent api as well, but at least this will solve my immediate needs. Cheers!
