### ISSUE TITLE
HTTP2: Cancel while sending request body causes RST_STREAM to be sent twice

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#39016]
Found as part of #38911 

If cancellation occurs while we are sending the request body, we will send RST_STREAM twice on the stream.

One occurs here: https://github.com/dotnet/corefx/blob/1833ec4769749dfce2b6dadad5882f208b499796/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs#L142

The other occurs here: https://github.com/dotnet/corefx/blob/1833ec4769749dfce2b6dadad5882f208b499796/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L1522

It seems like we only need one of these, but I'm not sure which is the correct one.

We need to ensure that the cancellation tests:
(a) validate that RST_STREAM is only sent once
(b) validate that nothing else is sent on the stream after RST_STREAM
(c) validate that the connection itself is still usable after the cancellation, i.e. a new request on the same connection succeeds.

@wfurt Can you take a look at this?

(edit: fix first code link)

**Comment by wfurt** [comment]
yes, I can. I'll also add more tests.
