### ISSUE TITLE
Unit Testing with SQLite: System.Data.SqlClient is not supported on this platform

### ISSUE THREAD

**Issue by giri-nitesh** [dotnet/corefx#39023]
I have a **.NET Core 2.2** solution with APIs written in it. For DAC layer I have used **.NET Standard 2.0** with following technical specs:

1. **Microsoft.EntityFrameworkCore<2.2.4>**
2. **Microsoft.EntityFrameworkCore.SqlServer<2.2.4>**
3. **Microsoft.EntityFrameworkCore.Tools<2.2.4>**

I am unit testing my APIs by using SQLite db. All of the testcases get passed except the functions which make use of stored procedures where sql queries have been written. I get the following exception:

> System.Data.SqlClient is not supported on this platform.System.
   PlatformNotSupportedException: System.Data.SqlClient is not supported on this platform.
     at System.Data.SqlClient.SqlParameter..ctor(String parameterName, Object value)
     at <stored_procedure_name>(Int32 someId, Int32 anotherId)

**Comment by roji** [comment]
Can you please post more details, specifically which exact platform you're running on? Your csproj could also be useful.

**Comment by roji** [comment]
Also, you seem to be talking about SqlClient (which is the client library for Microsoft SQL Server) and SQLite (which is a completely different database). Can you please clarify?

**Comment by giri-nitesh** [comment]
> 
> 
> Can you please post more details, specifically which exact platform you're running on? Your csproj could also be useful.

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>7.1</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.2.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Data.SqlClient" Version="4.6.1" />
  </ItemGroup>

</Project>

**Comment by giri-nitesh** [comment]
> 
> 
> Also, you seem to be talking about SqlClient (which is the client library for Microsoft SQL Server) and SQLite (which is a completely different database). Can you please clarify?
 I am using Microsoft SQL Server database to build my application, while for unit testing I am using SQLite db.

**Comment by giri-nitesh** [comment]
> 
> 
> Can you please post more details, specifically which exact platform you're running on? Your csproj could also be useful.

Following is the csproj file:
[MyAPP.zip](https://github.com/dotnet/corefx/files/3339228/MyAPP.csproj.zip)

**Comment by roji** [comment]
@giri-nitesh 
1. Which platform are you running on? Windows, Linux, Mac?
2. The csproj you posted targets .NET Standard, which is for libraries. Can you please post the csproj of your runnable test project, which should be targeting .NET Core?
3. Also, can you please confirm that your issue is when running against SQL Server (SqlClient) and not Sqlite, as your stack trace indicates? Sqlite doesn't seem to be related to this issue in any way.

**Comment by giri-nitesh** [comment]
1. Windows
2. [MyApp.csproj.zip](https://github.com/dotnet/corefx/files/3340083/MyApp.csproj.zip)
3. Issue occurs when I run my UnitTest application against SQLite db. SQL Server has been used as db for my application.

**Comment by Wraith2** [comment]
SQLite does not support stored procedures. SQL Server does. If you're trying to test core targeted at SQL Server and which contains stored procedures it will not work against your SQLite database. You need to find another way to test, I suggest using the same database server you're likely to go into production with.
