### ISSUE TITLE
SendAsync_ConcurentSendReceive_Ok test runs very slowly

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#39046]
I often run just the HTTP2 tests with -parallel none and -verbose in order to get a clear picture of what's happening during test execution.

The whole HTTP2 test class takes about 53s to run. Over 30s of this is this configurations of this single test.

It would be good to make this test run more quickly.

**Comment by geoffkizer** [comment]
Moving to Outerloop doesn't really solve the problem. 

I don't see why these tests need to be so slow. We should rework them to complete promptly.

**Comment by wfurt** [comment]
I was looking at it again and with all the new tests added for duplex, I'm not sure if this worth of keeping or fixing. Do you have any thoughts on this @geoffkizer? If you agree, we should simply delete it.

**Comment by geoffkizer** [comment]
I'm fine deleting it, but it would be good if you could look at the new tests and make sure you think they are covering everything this test is covering. If so, go ahead and delete.
