### ISSUE TITLE
VersionConverter and UriTypeConverter inconsistent behavior wrt full framework

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#39041]
Per @hughbe (https://github.com/dotnet/corefx/pull/28516#issuecomment-506691453):

Couple of things that I would like to point out that are inconsistent between `UriTypeConverter/VersionConverter` and the other type converters in .NET Core:
- They throw `ArgumentNullException` for `CanConvertFrom(null)` whereas .NET Framework returns `false`. I suggest fixing this to be consistent with other type converters.
- They return `false` for `CanConvertFrom(typeof(InstanceDescriptor))` because they don't call their base class `CanConvertFrom` method. See https://github.com/dotnet/corefx/pull/35760. I suggest fixing this
- They don't support `InstanceDescriptor` conversion - should this be added to `VersionConverter`?

**Comment by Marusyk** [comment]
Can I try to prepare PR for this?

**Comment by safern** [comment]
Yes. If you’re going to take it this would need to be ready before July 16th. Let me know to assign it.

**Comment by Marusyk** [comment]
Yes, I will prepare PR until Monday
