### ISSUE TITLE
.NET Standard in a NET 4.7.2 library

### ISSUE THREAD

**Issue by richardgavel** [dotnet/corefx#39068]
I'm dealing with a 4.7.2 monolith (number of libraties) that I'm gradually trying to shift over to a .NET Core application. The first thing I'm trying to do is gradually reduce the references down from .NET framework ones to .NET standard ones (for example, turning a reference to System.Configuration into a package reference to System.Configuration.Configuration manager. The idea is to try and get closer and closer to pure .NET standard compatibility. However, I get a number of  the following errors. But I really want it to use the NuGet package because I want it to validate at least those references against the NET Standard APIs. But maybe what I'm trying to do simply isn't possible?

`C:\Program Files\dotnet\sdk\2.2.105\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ConflictResolution.targets(41,5): message NETSDK1041: Encountered conflict between 'Reference:C:\Users\xxx\.nuget\packages\system.runtime.serialization.primitives\4.3.0\ref\net46\System.Runtime.Serialization.Primitives.dll' and 'Platform:System.Runtime.Serialization.Primitives.dll'.  NETSDK1033: Choosing 'Platform:System.Runtime.Serialization.Primitives.dll' because AssemblyVersion '4.2.0.0' is greater than '4.1.2.0'.`

**Comment by ericstj** [comment]
These are not errors just normal messages about assemblies that used to be delivered by packages which are now part of the framework.
