### ISSUE TITLE
Remove CancellationToken parameter from new CloseAsync methods in System.Data.Common

### ISSUE THREAD

**Issue by divega** [dotnet/corefx#39069]
Based on https://github.com/dotnet/standard/pull/1283#discussion_r298295697, accepting a `CancellationToken` in `CloseAsync` methods can be confusing.

When writing asynchronous code, it is common practice to pass the same cancellation token to all async calls used to implement an operation. 

But `CloseAsync` is often used in finally blocks to release resources after another async database operation is performed. 

E.g., based on the pattern used by EF Core at https://github.com/aspnet/EntityFrameworkCore/blob/d13f1b71fe48ec735d67ee320e2db1f942d0f2a6/src/EFCore.Relational/Migrations/Internal/MigrationCommandExecutor.cs#L92-L149:

``` c#
await connection.OpenAsync(ct);
try
{
    command.Connection = connection;
    await command.ExecuteNonQueryAsync(ct);
}
finally
{
    await connection.CloseAsync(ct);
}
```

If `ExecuteNonQueryAsync` is cancelled, an exception (i.e. `OperationCanceledException`) will be thrown. But if in the finally block the same `CancellationToken` was passed to `connection.CloseAsync(ct)`, the desired effect of closing the connection wouldn't be attained, and another `OperationCanceledException` would be surfaced.

Similar reasoning was used to decide [not to accept a `CancellationToken` from `IAsyncDisposable.DisposeAsync`](https://docs.microsoft.com/dotnet/csharp/language-reference/proposals/csharp-8.0/async-streams):

> _`DisposeAsync` accepting a `CancellationToken`_: while in theory it makes sense that anything async can be canceled, disposal is about cleanup, closing things out, free'ing resources, etc., which is generally not something that should be canceled; cleanup is still important for work that's canceled.  The same `CancellationToken` that caused the actual work to be canceled would typically be the same token passed to `DisposeAsync`, making `DisposeAsync` worthless because cancellation of the work would cause `DisposeAsync` to be a nop.  If someone wants to avoid being blocked waiting for disposal, they can avoid waiting on the resulting `ValueTask`, or wait on it only for some period of time.

cc @roji, @ajcvickers

**Comment by stephentoub** [comment]
Removing the token sounds fine (we'd asked about this in the API review initially as well), but we're now late in the cycle, at a point where we try not to take API breaking changes.  I believe this will need special approval.
cc: @danmosemsft, @terrajobst

**Comment by divega** [comment]
> we'd asked about this in the API review initially as well

Very true. I think we didn't fully understand what was broken about it until we started trying to consume the API and took another look. We'll try to do better!
