### ISSUE TITLE
Extend the Xml Serializer Generator to generate serializers for faults

### ISSUE THREAD

**Issue by atanasa** [dotnet/corefx#39089]
I have operations that use the XmlSerializer to serialize faults. The pregenerated serializers does not have serializers for those. 

Is there an option to extend the svcutil serializer generator to emit code for those too?

I've noticed that if I don't pregenerate the serializers, at runtime the serializer that is generated in-memory generates mappings for faults (along with the request/responce serializers).
For some reason when I pregenerate the serializers, only the mappings of the request/response serializers are generated and faults are left to the default serializer.

Looking at the code, WCF already generated the mappings for the faults but does not include them for the pregenerated serializers for some reason.

**Comment by atanasa** [comment]
Maybe this should go to the WCF repo, as probably their code needs to be adapted to pass the fault mappings into the existing .Net Core code.

**Comment by StephenBonikowsky** [comment]
Issue moved to [dotnet/wcf #3768](https://github.com/dotnet/wcf/issues/3768) via [**ZenHub**](https://www.zenhub.com/)
