### ISSUE TITLE
Http2_InitialWindowSize_ClientDoesNotExceedWindows test sporadically failing CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#39082]
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38804~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190701.1/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2~2FHttp2_InitialWindowSize_ClientDoesNotExceedWindows

e.g.
```
Windows.81.Amd64.Open-x64-Debug
Get Repro environment
Unhandled Exception of Type Xunit.Sdk.FalseException
Message :
Assert.False() Failure
Expected: False
Actual:   True
Stack Trace :
   at System.Net.Test.Common.Http2LoopbackConnection.ExpectSettingsAck() in /_/src/Common/tests/System/Net/Http/Http2LoopbackConnection.cs:line 199
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.Http2_InitialWindowSize_ClientDoesNotExceedWindows() in /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1193
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by eiriktsarpalis** [comment]
The issue seems to be caused by the ignore settings ack mechanism in the Http2LoopbackConnection class. It is susceptible to races in tests that use it more than once. I was able to reproduce consistently once I removed all the `Task.Delay` calls. Will follow up with a PR that makes the mechanism more resilient in such scenaria.

**Comment by davidsh** [comment]
>The issue seems to be caused by the ignore settings ack mechanism in the Http2LoopbackConnection class. 

So, the problem is a test issue and not a product issue?

**Comment by eiriktsarpalis** [comment]
Correct
