### ISSUE TITLE
Deprecation errors compiling native projects on macOS Catalina 

### ISSUE THREAD

**Issue by vcsjones** [dotnet/corefx#39114]
Compiling CoreFx on Catalina results in several deprecation errors, one of such is below.

> Error G11420DD6: 'CC_MD5_Init' is deprecated: first deprecated in macOS 10.15 - This function is cryptographically broken and should not be used in security contexts. Clients should migrate to SHA256 (or stronger). [-Werror,-Wdeprecated-declarations] [/Users/kjones/Projects/corefx/src/Native/build-native.proj]
              return CC_MD5_Init(&ctx->d.md5);

For the benefit of other contributors that are running the beta and wish to compile corefx, this can be worked around by adding this line:

```
add_compile_options(-Wno-deprecated-declarations)
```

to ./src/Native/Unix/System.Security.Cryptography.Native.Apple/CMakeLists.txt before `add_definitions`. For example:

```
project(System.Security.Cryptography.Native.Apple C)

set(CMAKE_INCLUDE_CURRENT_DIR ON)
add_compile_options(-Wno-deprecated-declarations)

add_definitions(-DPIC=1)
```

While I realize Catalina is beta at the time of writing, I do not anticipate this behavior will change.

**Comment by EgorBo** [comment]
In Mono we ignored it via https://github.com/EgorBo/mono/blob/5f72702c73000e10c5f5f57c56ad08a8ce9b196d/mono/utils/mono-md5.c#L33-L37

**Comment by vcsjones** [comment]
@EgorBo Yeah, that makes sense but there are many deprecation warnings, such as:

>pal_ssl.c(24,12): error GDBA9EB41: 'SSLCreateContext' is deprecated: first deprecated in macOS 10.15 - No longer supported. Use Network.framework. [-Werror,-Wdeprecated-declarations] [/Users/kjones/Projects/corefx/src/Native/build-native.proj]
  Failed to build corefx native components.
      return SSLCreateContext(NULL, isServer ? kSSLServerSide : kSSLClientSide, kSSLStreamType);

Taking a glance at it, there are about 20(?) places that would need pragma directives and I was far too lazy.

**Comment by ViktorHofer** [comment]
@vcsjones would you want us to help scout Catalina? Would be great if you could submit a PR with the pragma ignores.

**Comment by vcsjones** [comment]
@ViktorHofer sure! Will submit some changes soon.

**Comment by vcsjones** [comment]
This was fixed by #39938.

**Comment by danmosemsft** [comment]
Thanks @vcsjones. Did you spot any  other issues specific to Catalina? We are testing it currently.

**Comment by vcsjones** [comment]
@danmosemsft

Nothing so far that there isn't an existing issue for it.

I do see that the PR I linked to is for 5.0. I assume these will be ported to 2.1 at a later time and will auto flow in to 2.2 and 3.0 branches?
