### ISSUE TITLE
HttpClient.Get*Async helpers throw different exceptions depending on where it occurs

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#39118]
If an exception occurs while retrieving the headers, then an HttpRequestException emerges.  If an exception occurs while processing the response body, then an IOException emerges.

**Comment by davidsh** [comment]
We should always surface HttpRequestException as the top-level exception from the HttpClient APIs.  The IOException can be an inner exception to the HttpRequestException.

Of course, if the developer caller is simply calling Stream.ReadAsync(), then a top-level IOException is appropriate.

**Comment by stephentoub** [comment]
Actually, hold off on investigating this.  I may have been looking at the wrong thing... will close or come up with a repro.

**Comment by stephentoub** [comment]
Yeah, not hard to repro.
```C#
using System;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Net.Sockets;
using System.Text;
using System.Threading.Tasks;

class Program
{
    static async Task Main()
    {
        using (var listener = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp))
        {
            listener.Bind(new IPEndPoint(IPAddress.Loopback, 0));
            listener.Listen(1);
            string uri = "http://localhost:" + ((IPEndPoint)listener.LocalEndPoint).Port;

            using (var client = new HttpClient())
            {
                Task<string> t = client.GetStringAsync(uri);
                using (Socket server = listener.Accept())
                using (var reader = new StreamReader(new NetworkStream(server)))
                {
                    while (!string.IsNullOrEmpty(reader.ReadLine())) ;

                    server.Send(Encoding.UTF8.GetBytes("HTTP/1.1 200 OK\r\nContent-Length: 5\r\n\r\nhello")); // 1
                    //server.Send(Encoding.UTF8.GetBytes("HTTP/1.1 200 OK\r\nContent-Length: 5\r\n"));        // 2
                    //server.Send(Encoding.UTF8.GetBytes("HTTP/1.1 200 OK\r\nContent-Length: 5\r\n\r\nhe"));  // 3

                    server.Dispose();
                    Console.WriteLine(await t);
                }
            }
        }
    }
}
```

With (1) uncommented, it prints "hello".

With (2) uncommented instead, you get an HttpRequestException that wraps an IOException.

With (3) uncommented instead, you get the IOException directly.

**Comment by davidsh** [comment]
>With (3) uncommented instead, you get the IOException directly. HttpClient itself isn't wrapping the exceptions that come from the handler, and the IOException is coming out of accesses to the response stream.

That is probably a bug in the new code that handles trailing headers.

**Comment by stephentoub** [comment]
> That is probably a bug in the new code that handles trailing headers.

Don't think so; happens with 2.1 as well.  HttpClient in .NET Core simply isn't wrapping any exceptions from the handler, e.g. nowhere in https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpClient.cs does "new HttpRequestException" occur.

**Comment by stephentoub** [comment]
Probably happened as part of https://github.com/dotnet/corefx/pull/13720, though I'd need to dig deeper to confirm.
