### ISSUE TITLE
Test projects in VS show a conflict in intellisense because of populating reference item too late

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#39133]
When in design time build, now that we depend on conflict resolution, the `Reference` item is populated too late so `_HandlePackageFileConflicts` is not handling conflicts correctly. So when conflict resolution runs it only has the reference coming from the packages, so it doesn't resolve conflicts.

![image](https://user-images.githubusercontent.com/22899328/60553998-b71e3000-9cea-11e9-9a35-ac494aefb6e0.png)

So after looking at the design time binlogs I figured we can hook up to `PrepareForBuild` in order to add references dynamically and that would fix the issue.

However, this all looks kind of hacky and we can be able to cleanup `reference.targets` and perhaps hook it up earlier, maybe through an initial targets or something like that.

cc: @ViktorHofer @ericstj @scalablecory

**Comment by ViktorHofer** [comment]
This raises the bigger question, how can we protect design-time builds in CI? I can't guarantee this won't happen again unless there is a way to validate that path.

**Comment by ViktorHofer** [comment]
> When in design time build, now that we depend on conflict resolution, the Reference item is populated too late so _HandlePackageFileConflicts is not handling conflicts correctly

I didn't change the sequencing of the targets that populate the Reference item except for `ReferenceFromRuntime`. I'm a little surprised but will investigate now offline. It seems this issue is still not resolved.

**Comment by ViktorHofer** [comment]
@davkean do you know if there's a way to invoke design-time builds from the command line?
