### ISSUE TITLE
JsonElement.WriteAsValue does not support scientific notation with decimal separator

### ISSUE THREAD

**Issue by ghord** [dotnet/corefx#39139]
I encountered the issue where following code throws:
```c#
var test = JsonDocument.Parse("{ \"test\" : 6.5e-5 }").RootElement;

using(var stream = new MemoryStream())
{
       var writer = new Utf8JsonWriter(stream);
       //throws System.ArgumentException: 'e' is an invalid end of a number. Expected a delimiter.
       test.WriteAsValue(writer);       
}
```

Tested on .net core 3 preview5 and preview6.

**Comment by bartonjs** [comment]
https://github.com/dotnet/corefx/blob/7a9c2ab617229faad613fa5554b298df388f6fb7/src/System.Text.Json/src/System/Text/Json/Writer/JsonWriterHelper.cs#L177-L181

Says that `.` and `e` are exclusive, which is (in retrospect) obviously wrong.

**Comment by vicrdguez** [comment]
Hi
I would like to grab this, is it up for grab?

**Comment by bartonjs** [comment]
@vicrdguez All yours :)

**Comment by vicrdguez** [comment]
Added to principal branch, **Commit 589cd355**
Tell me if something is not correct

**Comment by bartonjs** [comment]
@vicrdguez I left some comments on the commit.  In addition to fixing the functional errors there should be test cases added for

* Positive decimal positive scientific: 6.022e23
* Positive decimal negative scientific: 6.022e-23
* Negative decimal positive scientific: -6.022e23
* Negative decimal negative scientific: -6.022e-23

I know there's a 1e400 case (positive/positive no-decimal), making sure that we also have something like -1e400 and 1e-400 and -1e-400 seems good... and then integral and decimal with no scientific (1, -1, 1.1, -1.1).

(And a PR is generally a better vessel for comments than individual commit hash links)

**Comment by vicrdguez** [comment]
@bartonjs thanks for the corrections, I will add it and create the test cases.
Im sorry for the hash link, is my first contribution.
Thanks for the help!!

**Comment by vicrdguez** [comment]
Im having troubles with the projects references since VS can't resolve any. Anywhere I can search about this problem? All the information I found doesn't help

**Comment by bartonjs** [comment]
Are you getting those errors as red squiggles, or compiling is actually failing?  (IIRC we have a problem that's being worked on where the VS experience in corefx is broken-looking, but the compile succeeds)

**Comment by vicrdguez** [comment]
@bartonjs  I have the red squiggles when I load the project, anyways when compiling it fails. First its like the project doest find the target framework. I added <TargetFramework>netcoreapp3.0</TargetFramework> by hand in the csproj but then, the references errors appear

**Comment by bartonjs** [comment]
Did you run `build.cmd` (or build.sh) from the root before loading VS?

**Comment by vicrdguez** [comment]
Im doing a fresh instalation of cmake, sdk and runtime. I will then run build.cmd. Let's see if I can make this work.
Thanks!

**Comment by vicrdguez** [comment]
After some testes and re installing everithing, thats what I get when trying to run tests:

```
[7/9/2019 09:31:33  Error] Testhost process exited with error: It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.0.0' was not found.
  - The following frameworks were found:
      2.1.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.11 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.12 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.2.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.2.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.0.0-preview6-27804-01 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download
```

I have preview six but is like there is another newer installed(?)
When I ran build.cmd I saw this:
`dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-**preview7**-012630/dotnet-sdk-3.0.100-preview7-012630-win-x64.zip`

**Comment by ericstj** [comment]
You can always run tests from the command-line `dotnet msbuild <testProject.csproj> /t:RebuildAndTest` after running `build.cmd` once.

It sounds like the error you're hitting may be related to test refactoring work @ViktorHofer is doing.  When running tests from CoreFx in VS the test host shouldn't be running from Program Files, it needs to use the shared framework we've built in the output directory.

If you'd like folks to collaborate more on your changes you can open a draft PR with the suggested change.

**Comment by ericstj** [comment]
@vicrdguez can you let us know if you're still looking at this?  We really appreciate the help and would like to get this fix in before our lock-down on 7/16.  Can you let us know by tomorrow if you plan to move forward with your fix, otherwise we'll pick up this issue ourselves.  Thanks!

**Comment by vicrdguez** [comment]
@ericstj yes I am! I have all the code an tests, but wasted lots of time with the problem I said yesteday and couldn't run them.
Thanks for the advice running the tests from command prompt, sorry for the delay answering, the time difference is big.
If everithing is correct, tomorrow I will check in this tomorrow

**Comment by ericstj** [comment]
No worries @vicrdguez, I wasn't sure if you knew about our schedule.  Sorry to pressure on the time, normally this sort of issue isn't so urgent but right now we're locking down the product for 3.0.  Submit a PR as soon as you have something ready and we'll start giving feedback.

**Comment by vicrdguez** [comment]
No problem @ericstj  I totally understand that. Im know finishing and I'm about to commit!
Thanks

**Comment by vicrdguez** [comment]
@ericstj I've tried to run the tests in the command prompt since I can't run them in VS,but about 45 tests failed. I don't usually commit changes with this uncertainty but I know you are hurry and I think (and hope) the code is correct.

Let me know if there is something to be fixed.
Thanks!

**Comment by ViktorHofer** [comment]
> After some testes and re installing everithing, thats what I get when trying to run tests:

How do you run tests inside VS? With the VS Test Explorer? The error that you posted indicates that you are using a wrong dotnet host which would happen if use VS Test Explorer without launching VS from command line, see: After some testes and re installing everithing, thats what I get when trying to run tests:

**Comment by vicrdguez** [comment]
@ViktorHofer I get that error right clicking in a test method and and then clicking in run tests.
But I see following your instructions I can launch the process.
Whats the difference about the host version between launching vs form command line or not?
Just curious about it

**Comment by ViktorHofer** [comment]
> I get that error right clicking in a test method and and then clicking in run tests.

That is using VS Test Explorer. As described, this only works when launching VS from the CLI.

> Whats the difference about the host version between launching vs form command line or not?

When launching VS from the CLI, we override the PATH property and a few other environment variables temporarily to point to our own built dotnet hive which contains the live built shared framework. If you use VS normally it would use the dotnet host from the dotnet hive at the default location (on Windows usually `C:\Program Files\dotnet`).

**Comment by vicrdguez** [comment]
I've just commited new changes, waiting for review

**Comment by vicrdguez** [comment]
@ViktorHofer I could run tests with F5 (green arrow) but for me, failed to run VS from command line with this error:

`.\build.cmd -vs System.Text.Json -arch x64`
```
MSBUILD : error MSB1001: Unknown switch.
Switch: -vs

For switch syntax, type "MSBuild -help"
Build failed.
```

**Comment by ViktorHofer** [comment]
Then you are not on latest master. This feature was merged about two days ago.
