### ISSUE TITLE
System.Net.Sockets 4.1. contract contains several Windows-specific APIs and APM pattern methods

### ISSUE THREAD

**Issue by SidharthNabar** [dotnet/corefx#3913]
This issue tracks the removal of some APIs from the Sockets contract in order to align it better to the .NET Core platform.

## Rationale

The current version of Sockets 4.1 contract in beta8 includes some types, properties and methods that are tied to Windows-specific concepts. Since .NET Core is intended to be cross-plat, these need to be excluded in order to provide similar behavior and API surface across platforms. Further, the Sockets contract also contains methods following the APM pattern (Begin/End), which is not supported for other APIs within .NET Core. Hence, these methods are being excluded and new methods are being added that follow the recommended pattern TPL-based pattern of async/await (See #3895). Lastly, there are some constructors that are performing expensive, blocking operations within the constructor - these need to be removed as well.

This issue tracks the removal of these APIs - a related issue is #3895 , which tracks addition of the TPL-based methods.

## Proposed API Exclusions

Following are the types, properties and methods being excluded by the proposed revision to the contract:

### Types:
```c#
public partial struct SocketInformation
public enum SocketInformationOptions
public enum TransmitFileOptions

```

### Properties/Methods/Constructors:
```c#
Type: Socket
public Socket(System.Net.Sockets.SocketInformation socketInformation)
public System.IAsyncResult BeginAccept - all overloads
public System.IAsyncResult BeginConnect - all overloads
public System.IAsyncResult BeginDisconnect
public System.IAsyncResult BeginReceive - all overloads
public System.IAsyncResult BeginReceiveFrom
public System.IAsyncResult BeginReceiveMessageFrom
public System.IAsyncResult BeginSend - all overloads
public System.IAsyncResult BeginSendTo
public void Disconnect(bool reuseSocket)
public bool DisconnectAsync(System.Net.Sockets.SocketAsyncEventArgs e)
public System.Net.Sockets.SocketInformation DuplicateAndClose(int targetProcessId)
public System.Net.Sockets.Socket EndAccept - all overloads
public void EndConnect(System.IAsyncResult asyncResult)
public void EndDisconnect(System.IAsyncResult asyncResult)
public int EndReceive - all overloads
public int EndReceiveFrom(System.IAsyncResult asyncResult, ref System.Net.EndPoint endPoint)
public int EndReceiveMessageFrom(System.IAsyncResult asyncResult, ref System.Net.Sockets.SocketFlags socketFlags, ref System.Net.EndPoint endPoint, out System.Net.Sockets.IPPacketInformation ipPacketInformation)
public int EndSend - all overloads
public int EndSendTo(System.IAsyncResult asyncResult)
public void SetIPProtectionLevel(System.Net.Sockets.IPProtectionLevel level)

Type: SocketAsyncEventArgs
public bool DisconnectReuseSocket
public System.Net.Sockets.TransmitFileOptions SendPacketsFlags

Type: SocketFlags
MaxIOVectorLength

Type: TcpClient
public TcpClient(System.Net.IPEndPoint localEP)
public TcpClient(string hostname, int port)
public System.IAsyncResult BeginConnect - all overloads
public void Connect - all overloads
public void EndConnect(System.IAsyncResult asyncResult)

Type:TcpListener
public System.Net.Sockets.Socket AcceptSocket()
public System.Net.Sockets.TcpClient AcceptTcpClient()
public void AllowNatTraversal(bool allowed) { }
public System.IAsyncResult BeginAcceptSocket(System.AsyncCallback callback, object state)
public System.IAsyncResult BeginAcceptTcpClient(System.AsyncCallback callback, object state)
public static System.Net.Sockets.TcpListener Create(int port)
public System.Net.Sockets.Socket EndAcceptSocket(System.IAsyncResult asyncResult)
public System.Net.Sockets.TcpClient EndAcceptTcpClient(System.IAsyncResult asyncResult)

Type:UdpClient
public UdpClient(string hostname, int port)
public void AllowNatTraversal(bool allowed)
public System.IAsyncResult BeginReceive(System.AsyncCallback requestCallback, object state)
public System.IAsyncResult BeginSend - all overloads
public void Connect - all overloads
public byte[] EndReceive(System.IAsyncResult asyncResult, ref System.Net.IPEndPoint remoteEP)
public int EndSend(System.IAsyncResult asyncResult)
public byte[] Receive(ref System.Net.IPEndPoint remoteEP)
public int Send - all overloads
public Task<int> SendAsync(byte[] datagram, int bytes)
```

## Pull Request
The pull request that implements the removal of the above APIs is #3655 

## Discussion
We are looking for feedback on the removal of these APIs based on the rationale described above. Also, if your code uses any of these APIs, please look at the revised contract in the PR for alternatives to use instead. If you believe the alternatives are not sufficient to address specific scenarios, that would be good to raise here as well.

**Comment by SidharthNabar** [comment]
@davidsh @CIPop @josguil @pgavlin @stephentoub @joshfree @weshaggard  PTAL

**Comment by pgavlin** [comment]
Looks like the "Types" section is missing `SocketInformationOptions`.

We should consider removing `CancelConnectAsync`, as its semantics are not cross-platform compatible.

My comments on https://github.com/dotnet/corefx/pull/3655 re: restricting API inputs still stand. We should also discuss the APIs alluded to by https://github.com/dotnet/corefx/commit/e4731ad428d538cbfc75d4dc2dcc8fd7d3aba534#commitcomment-13807519 for providing platform-transparent address families, etc.

**Comment by terrajobst** [comment]
@weshaggard and I just discussed this. From an API stand point the removals are sound and we've not problems with that. The question is whether upstream dependencies, such as WCF, have enough time to react to the removal for RC. @weshaggard mentioned that there is an email thread on this.

@weshaggard, any other concerns? Otherwise, LGTM.

**Comment by josguil** [comment]
@pgavlin 

I'll update the contract so we don't include CancelConnectAsync. 

I'm not very clear on restricting API inputs. Is there any action in particular you would like us to take?

**Comment by SidharthNabar** [comment]
@terrajobst - Thanks for the quick turnaround. We are already co-ordinating with WCF and other upstream dependent teams to mitigate the impact for RC. At this point, we don't believe that the impact due to API removal is major.

**Comment by SidharthNabar** [comment]
@pgavlin and @josguil  - We cannot remove `CancelConnectAsync` since it already shipped as part of the 4.0 contract of Sockets.

**Comment by pgavlin** [comment]
@SidharthNabar Ah, I did not realize that. No worries, then.

**Comment by KrzysztofCwalina** [comment]
Our API reviews are on Tuesdays. We will review this one tomorrow.

**Comment by terrajobst** [comment]
Given the responses above, we approved it.

**Comment by SidharthNabar** [comment]
The PR for this issue is merged and the API review is completed. Hence closing this issue.
