### ISSUE TITLE
WinHttpHandler succeeds erroneously when receiving partial content

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#39136]
In this example, the server says it has a Content-Length of 5 but then only sends 2 bytes.  The built-in handlers in .NET Framework and .NET Core both fail appropriately, but WinHttpHandler ignores the discrepancy and returns the 2 bytes without error.
```C#
using System;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Net.Sockets;
using System.Text;
using System.Threading.Tasks;

class Program
{
    static async Task Main()
    {
        using (var listener = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp))
        {
            listener.Bind(new IPEndPoint(IPAddress.Loopback, 0));
            listener.Listen(1);
            string uri = "http://localhost:" + ((IPEndPoint)listener.LocalEndPoint).Port;

            using (var client = new HttpClient(new WinHttpHandler()))
            {
                Task<string> t = client.GetStringAsync(uri);
                using (Socket server = listener.Accept())
                using (var reader = new StreamReader(new NetworkStream(server)))
                {
                    while (!string.IsNullOrEmpty(reader.ReadLine())) ;
                    server.Send(Encoding.UTF8.GetBytes("HTTP/1.1 200 OK\r\nContent-Length: 5\r\n\r\nhe"));
                    server.Dispose();
                    Console.WriteLine(await t);
                }
            }
        }
    }
}
```
cc: @davidsh

**Comment by davidsh** [comment]
>but WinHttpHandler ignores the discrepancy and returns the 2 bytes without error.

WinHttpHandler layers on top of native WinHttp which handles the HTTP protocol details.  I think both native WinHttp and WinINet won't return errors for these cases.  They will simply return whatever the response body bytes are up to EOF (end-of-file, i.e. stream end/FIN).

I don't think it is worth trying to fix this at the .NET layer to force the .NET WinHttpHandler behavior to match .NET Framework or .NET Core (SocketsHttpHandler).
