### ISSUE TITLE
IntelliSense/colorization/type resolution for framework types broken in corefx projects

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#39156]
e.g.
![image](https://user-images.githubusercontent.com/2642209/60598187-4161a500-9d7a-11e9-8727-7bf683bf47ac.png)
cc: @ViktorHofer

**Comment by ViktorHofer** [comment]
Can't repro on 16.1.2. Downloading the latest dogfood build now.

**Comment by stephentoub** [comment]
I restarted VS several times, and 3rd time was the charm and it now seems to work.  No idea what changed.

**Comment by ViktorHofer** [comment]
Discussed offline, it seems the issue is now gone and could have been a caching / other transient issue.
