### ISSUE TITLE
RegionInfoPropertyTests fails on non-US machines

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#39177]
Repro:

1. Add Czech language pack in Windows language settings
2. Run System.Globalization.Tests

Result:

```
     System.Globalization.Tests.RegionInfoPropertyTests.DisplayName(name: "en-US", expected: "United States") [FAIL]
        Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
        Stack Trace:

          Child exception:
            Xunit.Sdk.EqualException: Assert.Equal() Failure
                     (pos 0)
          Expected: United States
          Actual:   Spojené státy
                     (pos 0)
          D:\corefx\src\System.Globalization\tests\System\Globalization\RegionInfoTests.cs(78,0): at System.Globalization.Tests.RegionInfoPropertyTests.<>c.<DisplayName>b__5_0(String _name, String _expected)
```

**Comment by tarekgh** [comment]
@jkotas  I assume you set Czech as the default language after installing it. 

That is interesting because the test force UI culture to English. I'll take a look anyway.

**Comment by tarekgh** [comment]
@jkotas I cannot repro this issue. My guess here is you have en-US system and then you installed the Czech language pack but you didn't log off and log on again to have the settings apply correctly. That causes getting en-US as UI language while Czech is the UI language. 

Anyway, if you still can repro the issue, could you please run the following code on that machine and get me the output? 
Side note, when having Czech as default user locale, I am getting some build and run errors. I had to reset it to en-US first to build and the reset it back to Czech to try to repro the issue.

```C#
using System;
using System.Runtime.InteropServices;
using System.Globalization;

namespace test
{
    public unsafe class Program
    {

        [DllImport("kernel32.dll", CharSet = CharSet.Auto)]
        internal static extern bool GetUserPreferredUILanguages(uint dwFlags, uint* pulNumLanguages, char* pwszLanguagesBuffer, uint* pcchLanguagesBuffer);

        [DllImport("kernel32.dll", CharSet = CharSet.Unicode)]
        internal static extern int GetLocaleInfoEx(string lpLocaleName, uint LCType, void* lpLCData, int cchData);

        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Console.WriteLine($"UI Culture: {CultureInfo.CurrentUICulture}  .... User Culture: {CultureInfo.CurrentCulture}");
            CultureInfo.CurrentUICulture = new CultureInfo("en-US");
            Console.WriteLine($"UI Culture: {CultureInfo.CurrentUICulture} ... User Default UI Culture: {GetUserDefaultUICulture().Name} .... User Culture: {CultureInfo.CurrentCulture}");
            Console.WriteLine(new RegionInfo("en-US").DisplayName);
        }

        private static CultureInfo GetUserDefaultUICulture()
        {
            const uint MUI_LANGUAGE_NAME = 0x8;
            uint langCount = 0;
            uint bufLen = 0;
 
            if (GetUserPreferredUILanguages(MUI_LANGUAGE_NAME, &langCount, null, &bufLen))
            {
                char[] languages = new char[bufLen];
                fixed (char* pLanguages = languages)
                {
                    if (GetUserPreferredUILanguages(MUI_LANGUAGE_NAME, &langCount, pLanguages, &bufLen))
                    {
                        int index = 0;
                        while (languages[index] != (char)0 && index < languages.Length)
                        {
                            index++;
                        }
 
                        return new CultureInfo(new string(languages, 0, index));
                    }
                }
            }

            Console.WriteLine($"Couldn't read User Pererred UI Languages");
 
            return GetUserDefaultCulture();
        }    

        internal static CultureInfo GetUserDefaultCulture()
        { 
            const string LOCALE_NAME_USER_DEFAULT = null;            
            const string LOCALE_NAME_SYSTEM_DEFAULT = "!x-sys-default-locale";            
            const uint LOCALE_SNAME = 0x0000005C;

            string strDefault = GetLocaleInfoEx(LOCALE_NAME_USER_DEFAULT, LOCALE_SNAME);
            if (strDefault == null)
            {
                strDefault = GetLocaleInfoEx(LOCALE_NAME_SYSTEM_DEFAULT, LOCALE_SNAME);
 
                if (strDefault == null)
                {
                    return CultureInfo.InvariantCulture;
                }
            }
 
            return new CultureInfo(strDefault);
        }        

        internal static unsafe string GetLocaleInfoEx(string localeName, uint field)
        {
            const int BUFFER_SIZE = 530;
 
            char* pBuffer = stackalloc char[BUFFER_SIZE];
            int resultCode = GetLocaleInfoEx(localeName, field, pBuffer, BUFFER_SIZE);
            if (resultCode > 0)
            {
                return new string(pBuffer);
            }
 
            return null;
        }        
    }
}

```

**Comment by jkotas** [comment]
Since I have filled this, I have switched back to English (without uninstalling the language pack) and also rebooted the machine. This is what my settings looks like now:

![image](https://user-images.githubusercontent.com/6668460/60692019-83790c80-9e88-11e9-9126-19cfa7d585e1.png)

I can still repro the problem. Your test prints this:

```
Hello World!
UI Culture: en-US  .... User Culture: en-US
UI Culture: en-US ... User Default UI Culture: en-US .... User Culture: en-US
Spojené státy
```

Does this look like a possible valid state, or does this look like the Windows installation got corrupted somehow? In any case, you can stop by to look at the machine next week.

> I am getting some build and run errors. I had to reset it to en-US first to build and the reset it back to Czech to try to repro the issue.

Yes, one tends to hit number of bugs if you run with Czech locale. It is not a happy place to be. (I have switched to Czech locale for only for short time to try something when I have noticed this one problem.) Now that we are going to have [team in Prague](https://twitter.com/ziki_cz/status/1136498155070021640), it may be a good idea to get all the bugs fixed.

**Comment by tarekgh** [comment]
Thanks @jkotas that is very helpful. After switching Windows UI language settings to English, I am able to repro it. This is a Windows bug. Calling Windows API ```GetUserPreferredUILanguages``` it returns en-US which is correct. but when calling the following:

```C#
            const uint LOCALE_SLOCALIZEDCOUNTRYNAME = 0x00000006;
            string displayName = GetLocaleInfoEx("en-US", LOCALE_SLOCALIZEDCOUNTRYNAME);
```

It returns ```Spojené státy``` which is incorrect as I expect to get the name in English. I'll close this issue here and will file a bug to Windows team.

**Comment by tarekgh** [comment]
I reported the issue to Windows team.

**Comment by jkotas** [comment]
I have submitted https://github.com/dotnet/corefx/pull/39212 to move this test to OuterLoop. Also, I have opened a batch of other issues and PRs on failures that I got in running on latest Windows switched to Czech.

**Comment by tarekgh** [comment]
Thanks @jkotas. That make sense.

**Comment by ShawnSteele** [comment]
I think this happens to be dependent on the order the user settings were changed in Windows.  If you select the new UI language and THEN select the new user locale, I believe it'll behave.
