### ISSUE TITLE
Add validation for compiler emitted attributes to be present where they need to be

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#39175]
For nullable compiler generated attributes like `NullableContextAttribute` or `NullablePublicOnly` we want to validate that they're on the right places and that they don't get added into wrong places like shims.

We need this validation because having `NullablePublicOnly` in the right places would avoid metadata bloat by telling the compiler to not emit nullable metadata for internal/private members.

See: https://github.com/dotnet/corefx/pull/39174

cc: @stephentoub @ViktorHofer @ericstj

**Comment by ViktorHofer** [comment]
Are you sure this needs to be protected by infra? Wouldn't a comment next to the feature flag be enough?

**Comment by stephentoub** [comment]
I think having a few simple tests in System.Runtime would be valuable, e.g. check that some public API expected to have an attribute has it, and that some internal APIs don't.  A sanity check.  Comments next to the feature flag would be useful, too, but the moment you start having conditions in build files that govern metadata that's not inspected (e.g. on internals), it becomes really easy to accidentally change it and not realize it.

**Comment by ViktorHofer** [comment]
Runtime checks over infra checks +1
