### ISSUE TITLE
HTTP2: Does the user need to Flush on the request stream to guarantee that request data is sent?

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#39181]
For HTTP/1.1, we don't guarantee that the request body is sent until either you flush or you close the request stream. In practice, this doesn't matter because we don't support duplex.

With HTTP/2 however, we do support duplex and so it's important for the user to know exactly when their data is guaranteed to be sent to the server. 

Currently, we are effectively flushing on every write to the request body. But we've discussed potentially changing this to improve performance: it's better to do fewer writes to the wire when possible, and delaying flush could allow us to coalesce this write with other outgoing frames. Since we're behaving this way, it's likely that users will assume this behavior will never change and they never have to Flush, which would lock us into the current behavior and prevent us from optimizating in the future.

This may be something we can change in a future release anyway, given that HTTP2 is only supported for GRPC in 3.0. I just want to ensure we aren't locking ourselves in to anything here.

@stephentoub thoughts?

**Comment by stephentoub** [comment]
Good question. Both approaches seem reasonable to me, but I think I prefer the one we currently have, which is effectively the same as NetworkStream: every write is direct to the network, and if you want buffering, you layer that on top.

**Comment by geoffkizer** [comment]
> I think I prefer the one we currently have, which is effectively the same as NetworkStream: every write is direct to the network, and if you want buffering, you layer that on top.

The thing that worries me here is that this approach rules out the potential optimization of merging frames when there's no one currently blocked on the write lock.

This is different than saying "do your own buffering". If the issue was just buffering, I'd be fine with it. Though I will note that we explicitly *do* buffer for HTTP/1.1. Maybe we should remove that?

**Comment by geoffkizer** [comment]
> potential optimization of merging frames

To be clear, I mean merging frames from *other streams*.

If we don't guarantee that we send the bits to the wire immediately, then we can send frames from multiple different streams (including not just DATA but HEADERS and WINDOW_UPDATE etc) in a single write. We do this currently in limited circumstances -- specifically, we do it when we know that another writer is waiting to write more data. But that's not very common; it only happens if another writer tries to write while we are holding the write lock, and we don't hold the write lock for very long.

If we do guarantee this, then we can't explore this optimization later.

**Comment by stephentoub** [comment]
> Though I will note that we explicitly do buffer for HTTP/1.1

Not for https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RawConnectionStream.cs which is the closest approximation here I think.  It's used for WebSockets, or more specifically anything that upgrades, so it's a similar idea.

> The thing that worries me here is that this approach rules out the potential optimization of merging frames when there's no one currently blocked on the write lock.

I guess the confusing thing here is that we're talking about this in the context of "duplex", but it's really not limited to that.  Any content, even content that's intended to be fully received before a response is sent, is going to go through the same code paths, so we're really talking about them as well.  For something that's actually intended to be duplex communication, I think it's unlikely in the majority case that it would benefit from such an optimization, as my guess is most messages will need to be sent immediately, and so if we don't flush on each write, the caller will (or they'll neglect to, and they could have a pretty hard to track-down deadlock).  But for "normal" scenarios, I agree with you that there's the potential for optimization... however, even then, most content types used (e.g. ByteArrayContent, StringContent, etc.) are going to perform a single write, and so again, no possibility for optimization.

**Comment by stephentoub** [comment]
> I mean merging frames from other streams.

Ah; I thought you were referring to the same stream.  In more than the limited cases you mention, wouldn't this require that we potentially wait a bit before actually sending?  Sounds like nagle.

**Comment by scalablecory** [comment]
In terms of best practices / documentation, I think it's worth leaving the door open for it. Is that the primary question here?

It would be a fun experiment to determine the types of workloads that would benefit the most from this, to see if it's worth the additional complexity.

We can also choose to buffer and consolidate writes if we're waiting for a previous `send()` to complete. I don't think this would require anything from `Flush` but could share much of the same implementation.

**Comment by geoffkizer** [comment]
> which is the closest approximation here I think

The comparison I'm making is to ChunkedEncodingWriteSteam and similar. These streams buffer.

> I guess the confusing thing here is that we're talking about this in the context of "duplex", but it's really not limited to that. 

Agreed. The reason I mention duplex is that it really only matters for duplex. For non-duplex, you don't care if it's buffered or not because you're going to send it all and then close.

**Comment by geoffkizer** [comment]
> wouldn't this require that we potentially wait a bit before actually sending? Sounds like nagle.

We would wait, yes, but there's no timeout as in Nagle. 

The trick is that since it's a request body, you can always assume there's more data coming, and so you can flush as you want instead of flushing every time. Except this isn't true for duplex.

**Comment by geoffkizer** [comment]
> In terms of best practices / documentation, I think it's worth leaving the door open for it. Is that the primary question here?

Yeah, that's the primary question. But also, if we always write immediately today, then code that doesn't flush will work fine. So even if we document that you must flush, we might find ourselves locked in to writing immediately if we ship that way.

>We can also choose to buffer and consolidate writes if we're waiting for a previous send() to complete. I don't think this would require anything from Flush but could share much of the same implementation.

We don't release the write lock until the send completes. We can't reuse the buffer until the send completes. Theoretically, we could use unused parts of the buffer, or allocate a new buffer and start to fill that, etc. But I doubt this is worthwhile. Send always complete immediately unless the kernel buffer is full, which isn't common, and if it does happen there's not a lot of value in us filling our own buffers instead.

**Comment by stephentoub** [comment]
@jamesnk, does the gRPC implementation flush when it sends a message?

**Comment by JamesNK** [comment]
No. It just calls WriteAsync

https://github.com/grpc/grpc-dotnet/blob/42a8bb3f334b8ce4743c393900abbe26e44214c7/src/Grpc.Net.Client/Internal/StreamExtensions.cs#L139-L149

**Comment by JamesNK** [comment]
Right now there are two calls to WriteAsync in quick succession for each message: once for the header, once for the message content.

**Comment by stephentoub** [comment]
> We would wait, yes

Yeah, I'm skeptical we'd actually do this. The heuristics involved could easily lead to perf regression on some workloads.

If you really think it's valuable to leave the door open, and if it won't torpedo gRPC, then ok, but I'm not currently optimistic.

Have you prototyped it to see what the actual perf benefits could be?

**Comment by stephentoub** [comment]
> Right now there are two calls to WriteAsync in quick succession for each message: once for the header, once for the message content.

That's actually a good argument for removing the explicit flush as Geoff suggests, and having the gRPC code add the flush explicitly after the second write.

**Comment by geoffkizer** [comment]
> The heuristics involved could easily lead to perf regression on some workloads.

Do you have some particular workload in mind? I have trouble coming up with a realistic workload that seems like it could be worse.

> Have you prototyped it to see what the actual perf benefits could be?

No. At this point I'm mostly concerned with keeping the option open in the future.

**Comment by stephentoub** [comment]
> Do you have some particular workload in mind?

The vast majority of content is going to be single-write, e.g. StringContent, ByteArrayContent, ReadOnlyMemoryContent, etc. For single-write, the only cross-stream benefit is if there's no explicit flush at the end of the content body, which means the request would be artificially delayed in order to wait for another packet from another stream to combine it with.

There will be some content, e.g. StreamContent, where there could likely be multiple writes. If you're only focused on such cases rather than the single-write, and we'll force a flush immediately after SerializeToStreamAsync completes, then I agree the downside will be reduced. However even then there are patterns where it could hurt. Imagine a stream that ends up performing two writes, one for 15k as the bulk of the data, and then another a bit later for the remaining 1 byte in the stream. We could have already sent the 15k,  but now it may be delayed until sending that remaining 1 byte, which could also add latency.

For duplex, I can certainly see the benefits if the caller is going to perform multiple writes as part of a single message, as it sounds like we currently do for gRPC, but in such cases the caller is almost certainly going to do the writes in very quick succession and then immediately flush (or else they have a bug), which significantly reduces any possible benefit from cross-stream joins beyond what we already do.

**Comment by geoffkizer** [comment]
> For single-write, the only cross-stream benefit is if there's no explicit flush at the end of the content body, which means the request would be artificially delayed in order to wait for another packet from another stream to combine it with.

End of request body always causes a flush. So there's no delay.

> Imagine a stream that ends up performing two writes, one for 15k as the bulk of the data, and then another a bit later for the remaining 1 byte in the stream. We could have already sent the 15k, but now it may be delayed until sending that remaining 1 byte, which could also add latency.

(I assume we're talking about non-duplex here.)

Possibly -- though I'm skeptical.

It seems to me there's a "tipping point" where it's better to send what we have, and then send again later, rather than waiting for more data and sending all at once. On the one hand, buffering a large amount, like say 1MB, seems like a bad idea. On the other extreme, if the writes are each 1 byte, it's clearly better to do at least some buffering, for a variety of reasons. 

I don't have a great sense for what the tipping point here is. It's certainly > TCP MTU = 1500 bytes, and probably much larger. But whether it is 4K or 16K or 64K or more, I don't know. Likely it depends on a variety of factors. We have somewhat arbitrarily picked 32K in the HTTP2 write buffer logic. We could certainly tune this up or down.

Again, my main concern here is ensuring we can do this sort of tuning and optimization in the future, even if we don't have time to do it right now.

And also, we *already do this for HTTP/1.1*, in ChunkedEncodingWriteStream etc. The buffer limit there is usually 4K. In practice it's not always 4K; it's whatever the actual buffer size is at the moment, and the buffer may have grown > 4K at some point because it was required for sending headers.

**Comment by stephentoub** [comment]
> End of request body always causes a flush. 

Right. In which case there's little benefit to such a cross-stream optimization for what I believe is by far the most common case. And as I mentioned, I have trouble seeing cross-stream benefit for duplex, as someone sending a message will write it and then flush immediately. Which is why I don't think we'd spend any energy coming up with an approach around optimizing for these cross-stream cases.

But that's all academic. I expect we'd see immediate benefit in the gRPC case, by removing the flush-per-write and having gRPC add one after both writes. At which point there's little more to discuss right now.

**Comment by geoffkizer** [comment]
>  I expect we'd see immediate benefit in the gRPC case, by removing the flush-per-write and having gRPC add one after both writes. At which point there's little more to discuss right now.

Yeah, we'd probably see a benefit. But alternatively, GRPC could simply combine the writes into a single write themselves. That would be the right thing to do if using Sockets directly.

**Comment by geoffkizer** [comment]
There's one other wrinkle here that just occurred to me...

Even in the single-write case (e.g. StringContent), there are actually two writes under the covers. The first happens when the content is written. The second happens when SerializeToStreamAsync completes -- we send a DATA frame with length = 0 and the EndStream bit set, to close the request stream.

If we did do buffering (and thus require Flush), we could combine these into a single write.

**Comment by stephentoub** [comment]
> There's one other wrinkle here

Sounds like a no-brainer then to remove the flush.
