### ISSUE TITLE
Create a placeholder stub for WebSockets.Client for non-Windows platforms

### ISSUE THREAD

**Issue by SidharthNabar** [dotnet/corefx#3918]
WCF currently depends on WebSockets.Client API, but this API is not exposed on non-Windows platforms. There is a plan to add this in the future, but that will not happen in RC timeframe. However, we need to at least provide a placeholder stub so that WCF code will at least compile.

@vijaykota - PTAL.

**Comment by pgavlin** [comment]
This was addressed by #3922.
