### ISSUE TITLE
cannot use 'checked' as the linq select anonymous type memeber name

### ISSUE THREAD

**Issue by cpzhang** [dotnet/corefx#39190]
from x in db.table
 select new
 {
  checked = 1
 }

like the codes above , visual sutdio 2019 will report the error
"Error CS0746	Invalid anonymous type member declarator."

**Comment by vcsjones** [comment]
`checked` [is a language keyword][1]. You can either use a different name, or escape it using an `@`:

```csharp
from x in db.table
select new
{
@checked = 1
}
```

[1]: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/checked

**Comment by danmosemsft** [comment]
Thanks closing as I think this is answered.

**Comment by vcsjones** [comment]
@danmosemsft did you mean to close this?

**Comment by cpzhang** [comment]
thanks @vcsjones

**Comment by danmosemsft** [comment]
@vcsjones yes 🙂
