### ISSUE TITLE
Update Wiki to mention that changes to .NET Core must be binary compatible with the full .NET Framework

### ISSUE THREAD

**Issue by justinvp** [dotnet/corefx#392]
A question came up in the comments for #271 about the possibility of a binary breaking change in the .NET Core Regex collections from the Regex collections in the full .NET Framework.

@davkean responded:

> You need to be able to build against this library and run on .NET Framework 4.6.

And I asked:

> So if you accept this suggestion (adding the generic interfaces to these types), the changes will have to be added to .NET 4.6 as well? How much time is left to make changes to .NET 4.6?

And @weshaggard responded:

> Yes @justinvp any types that already exist on the full desktop framework will need to be updated there as well if they are updated in .NET Core. We have a high level goal of making code written for .NET work no matter what .NET platform you are targeting. As for how much time is left to add new public APIs to .NET 4.6 at this point we are not accepting any more unless they are critical.
> 
> With that said we fully expect .NET Core to evolve much more quickly then the full .NET framework that ships in Windows. We just have to be aware that any changes need to eventually make it there as well so while thinking about breaking changes you cannot just consider .NET Core you must consider the other platforms as well. If we don't do that then we risk diverging the platforms and making .NET development as a whole more difficult.

I think it'd be worth adding this to one of the wiki pages so it is clear to everyone that types in .NET Core that exist in the full .NET Framework must be binary compatible. I don't think this is explicitly stated anywhere currently.

**Comment by terrajobst** [comment]
Thanks. I'll take stab at this.

**Comment by akoeplinger** [comment]
So if I rely on new APIs in .NET Core I'll have to live with not being compatible with full .NET until it "eventually" catches up?

Is this the problem the .NET "distribution" Immo talked about plans to solve? E.g. you ensure a hypothetical .NET 4.8 is binary compatible with .NET Core 1.1 packages.

Would love to get a blog post about this since it seems to be one of the main confusion points.

**Comment by davkean** [comment]
My statement was incorrect. What I should have said, is that I need to be able to build against .NET Core and run on a future .NET Framework version, not necessarily the current one. What that means is that any decision you make now, should not back you into a corner to prevent that from occurring.

**Comment by terrajobst** [comment]
I believe this is taken care of by our [triaging document](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/triage.md).
