### ISSUE TITLE
API Proposal: ReadOnlySpan<T> Concat

### ISSUE THREAD

**Issue by Symbai** [dotnet/corefx#39201]
When using Span.Slice especially for strings it's currently a bottleneck to slice parts out of it and create a new string with these parts. It's because we have to call ToString() on each ReadOnlySpan<char> and then concat them together. The reason to use Span is to achieve performance. So the idea is that we create an API that calls ToArray() and ToString() only once which is faster and allocates less memory.

I've included a poor demonstration code to show the benefit. I think there are better ways to implement this but I also wanted to give some kind of motivation to this proposal by showing some benchmark results.

The target goal is to let us concat from many different span sources but ReadOnlySpan arrays aren't allowed as arguments so I've created an example with a Range array on a single span source.

### Proposal

```
internal static partial class SpanHelpers
{
   public static string Concat(this ReadOnlySpan<char> span, Range[] ranges);
   public static byte[] Concat(this ReadOnlySpan<byte> span, Range[] ranges);
   //ReadOnlySpan<T>[] aren't allowed as parameter, but if it is it would allow us to concat multiple span from different sources
   public static string Concat(ReadOnlySpan<char>[] spans);
   public static byte[] Concat(ReadOnlySpan<byte>[] spans);
}
```
### Demo Implementation
```
//This is my poor example to demonstrate the benefit. Not an actual proper implementation
public unsafe static string Concat(this ReadOnlySpan<char> span, Range[] ranges)
{
    int index = 0;
    int length = 0;
    for (int i = 0; i < ranges.Length; i++)
    {
        length += ranges[i].End.Value - ranges[i].Start.Value;
    }
    var result = new string('\0', length);
    fixed (char* spanPointer = span)
    fixed (char* resultPointer = result)
    {
        for (int i = 0; i < ranges.Length; i++)
        {
            int bytesToCopy = (ranges[i].End.Value - ranges[i].Start.Value);
            Unsafe.CopyBlock(resultPointer + index, spanPointer + ranges[i].Start.Value, (uint)bytesToCopy * sizeof(char));
            index += bytesToCopy;
        }
    }
            
    return result;
}
public unsafe static byte[] Concat(this ReadOnlySpan<byte> span, Range[] ranges)
{
    int index = 0;
    int length = 0;
    for (int i = 0; i < ranges.Length; i++)
    {
        length += ranges[i].End.Value - ranges[i].Start.Value;
    }
    var result = new byte[length];
    fixed (byte* spanPointer = span)
    fixed (byte* resultPointer = result)
    {
        for (int i = 0; i < ranges.Length; i++)
        {
            int bytesToCopy = (ranges[i].End.Value - ranges[i].Start.Value);
            Unsafe.CopyBlock(resultPointer + index, spanPointer + ranges[i].Start.Value, (uint)bytesToCopy * sizeof(byte));
            index += bytesToCopy;
        }
    }

    return result;
}
```

### Sample Usage:
Before:
```
[Benchmark]
public string Current_String()
{
    string result = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
    ReadOnlySpan<char> span = result.AsSpan();
    result = span.Slice(0, 2).ToString() + span.Slice(5, 2).ToString() + span.Slice(9, 2).ToString();
    return result;
}
[Benchmark]
public byte[] Current_ByteArray()
{
    byte[] result = new byte[64];
    ReadOnlySpan<byte> span = result.AsSpan();
    var buffer1 = span.Slice(0, 2).ToArray();
    var buffer2 = span.Slice(5, 2).ToArray();
    var buffer3 = span.Slice(9, 2).ToArray();
    byte[] newArray = new byte[buffer1.Length + buffer2.Length + buffer3.Length];
    Buffer.BlockCopy(buffer1, 0, newArray, 0, buffer1.Length);
    Buffer.BlockCopy(buffer2, 0, newArray, buffer1.Length, buffer2.Length);
    Buffer.BlockCopy(buffer3, 0, newArray, buffer1.Length + buffer2.Length, buffer3.Length);
    return newArray;
}
```
After:
```
[Benchmark]
public string Concat_String()
{
    string result = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
    ReadOnlySpan<char> span = result.AsSpan();
    result = span.Concat(new[] { new Range(0, 2), new Range(5, 7), new Range(9, 11) });
    return result;
}
[Benchmark]
public byte[] Concat_ByteArray()
{
    byte[] result = new byte[64];
    ReadOnlySpan<byte> span = result.AsSpan();
    result = span.Concat(new[] { new Range(0, 2), new Range(5, 7), new Range(9, 11) });
    return result;
}
```

### Benefit:
```
Intel Core i7-4960X CPU 3.60GHz (Haswell), 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=3.0.100-preview7-012593
  [Host] : .NET Core 3.0.0-preview7-27824-03 (CoreCLR 4.700.19.32302, CoreFX 4.700.19.32001), 64bit RyuJIT
  Core   : .NET Core 3.0.0-preview7-27824-03 (CoreCLR 4.700.19.32302, CoreFX 4.700.19.32001), 64bit RyuJIT

Job=Core  Runtime=Core
```

|            Method |     Mean |  Allocated |
|------------------ |---------:|----------:|
|    Current_String | 70.20 ns | 136 B |
|     **Concat_String** | **39.45 ns** |      **88 B** |
| Current_ByteArray | 67.46 ns |    216 B |
|  **Concat_ByteArray** | **44.20 ns** |     **168 B** |

**Comment by stephentoub** [comment]
.NET Core 3.0 has string.Concat overloads that take 2, 3, and 4 spans.

**Comment by Symbai** [comment]
What about Readonlyspan<byte> ?

**Comment by stephentoub** [comment]
There's no existing such Concat today for bytes. There'd need to be a very compelling use case, highlighting that it's a common enough operation to warrant such a helper in the core libraries (anyone can implement this on their own). With spans generally used in situations where developers are trying to avoid allocations, I suspect such an API that explicitly allocated a new array wouldn't be particularly valuable.

**Comment by Symbai** [comment]
> 
> 
> With spans generally used in situations where developers are trying to avoid allocations, I suspect such an API that explicitly allocated a new array wouldn't be particularly valuable.

Why does ToArray() exists then? Isn't that allocating a new array? Wouldn't it be nice if we could merge multiple spans into a new array allocating just once instead of calling ToArray over and over again? Since, you said it yourself, spans is there to avoid allocations. And my request is about avoiding additional allocation.

When we have something that does that with span of char, which is great. Then I believe that requesting something similar for span of byte is acceptable. On the other hand you are probably right that such a use case, for char or byte doesn't matter, is kinda specific. I'm leaving this request open to vote for it. Feel free to close it when you feel there is no place for it.

**Comment by stephentoub** [comment]
> Why does Span.ToArray() exists then?

Primarily for interop with APIs that require arrays.

> Wouldn't it be nice if we could merge multiple spans into a new array allocating just once instead of calling ToArray over and over again?

But for such perf-sensitive situations, you wouldn't want to allocate an array at all, e.g.
```C#
ReadOnlySpan<byte> s1 = ..., s2 = ..., s3 = ...;
int len = s1.Length + s2.Length + s3.Length;
byte[] buffer = ArrayPool<byte>.Shared.Rent(len);
try
{
    s1.CopyTo(buffer);
    s2.CopyTo(buffer.AsSpan(s1.Length));
    s3.CopyTo(buffer.AsSpan(s1.Length + s2.Length));
    ... // use buffer here
}
finally
{
    ArrayPool<byte>.Shared.Return(buffer);
}
```

**Comment by Symbai** [comment]
In your case the lifetime of this array is short and it would be needed once and in that case, I wouldn't basically have to allocate an array at all, as you said. But in all other cases I have to. In the case where the lifetime of the array would exceed the lifetime of the span.

For example you are reading a large file, let's say 2GB, and slicing out a few pieces and then merge them together into new byte array, let's say 64k, and store it for further purposes in a new class. In this case you don't keep the original byte array of 2GB in memory nor do you work with the arraypool as you don't return it in a short of amount of time since you don't know the lifetime of the new class.

If you read a large file once you can probably spend that few milliseconds for extra allocation. But if you read many you don't. Same goes for using some native APIs like ReadProcessMemory where you temporarily allocate the same amount of bytes you read and then deal with it but definitely not keeping it in memory any longer than needed. But again you cannot use ArrayPool when you don't know the lifetime of the array you store. In case of ReadProcessMemory, you can easily deal with few thousands of arrays to process but even more to create when slicing out pieces.

Processing large amount of data, slicing pieces out of it and store them for future purpose (means lifetime exceeds the lifetime of the span / data / arraypool). That's the idea behind the request.

**Comment by stephentoub** [comment]
Sure.  It can also be implemented in your code or in some library you use in a few lines:
```C#
public static byte[] Concat(ReadOnlySpan<byte> s1, ReadOnlySpan<byte> s2)
{
    var array = new byte[s1.Length + s2.Length];
    s1.CopyTo(array);
    s2.CopyTo(array.AsSpan(s1.Length));
    return array;
}
```
My point is that we don't add all such helpers to the core libraries.  They need to rise to a certain level of usefulness before we consider it.  We also prefer not to add APIs that cause developers to fall into a pit of performance failure (even if they're necessary or valid in some niche scenarios).

**Comment by Symbai** [comment]
No problem, thanks though :-)
