### ISSUE TITLE
BitArray race conditions may lead to memory corruption

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/corefx#39204]
As of https://github.com/dotnet/corefx/pull/33781, the `BitArray` class contains unsafe code as a performance optimization. Since `BitArray` instances are not thread-safe, this opens the possibility that improper cross-thread access to a `BitArray` instance may result in global memory corruption.

We should modify the `BitArray` internal logic to be resilient against this possibility. We don't need to make the type thread-safe, but improper cross-thread access shouldn't be able to cause damage beyond corruption of the individual `BitArray` instances involved.

**Comment by benaadams** [comment]
Work on local array references rather than class references?

**Comment by GrabYourPitchforks** [comment]
@benaadams Yeah, that should work. I didn't want to be too prescriptive in the bug description. :)

**Comment by benaadams** [comment]
Also probably faster too :)

**Comment by mikedn** [comment]
Simply using local array references is not sufficient. You have to acquire the array and the length atomically but that's not really possible so the only solution is to validate the length once the 2 have been copied to local variables.
