### ISSUE TITLE
nit: JsonCamelCaseNamePolicy -> JsonCamelCaseNamingPolicy

### ISSUE THREAD

**Issue by JamesNK** [dotnet/corefx#39208]
I noticed that the internal class for camel casing names is `JsonCamelCaseNamePolicy`. It should probably be `JsonCamelCaseNamingPolicy` since it is inheriting from `JsonNamingPolicy`.

**Comment by Marusyk** [comment]
just rename? 
please assign it to me

**Comment by stephentoub** [comment]
Or CamelCaseJsonNamingPolicy?
