### ISSUE TITLE
EncryptDecrypt_Read test fails with "System.IO.IOException : Element not found"

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#39211]
I am getting this failure reliably on one of my machines:

```
      System.IO.Tests.EncryptDecrypt.EncryptDecrypt_Read [FAIL]
        System.IO.IOException : Element not found. : 'C:\Users\jkotas\AppData\Local\Temp\tmpA55.tmp'
        Stack Trace:
          D:\corefx\src\System.IO.FileSystem\src\System\IO\FileSystem.Win32.cs(60,0): at System.IO.FileSystem.ThrowExceptionEncryptDecryptFail(String fullPath)
          D:\corefx\src\System.IO.FileSystem\src\System\IO\FileSystem.Win32.cs(24,0): at System.IO.FileSystem.Encrypt(String path)
          D:\corefx\src\System.IO.FileSystem\src\System\IO\File.cs(650,0): at System.IO.File.Encrypt(String path)
 ```

**Comment by jkotas** [comment]
Related: https://github.com/dotnet/corefx/pull/32342 disabled this test for Windows Home Edition. However, the machine that this fails on is a domain joined Windows Enterprise Edition.

**Comment by jkotas** [comment]
@carlossanlop reported the same failure in https://github.com/dotnet/corefx/pull/38489#issuecomment-501452568 so I am clearly not the only one hitting it.

**Comment by JeremyKuhne** [comment]
EFS is blocked on the REDMOND domain. The error is super unhelpful, but you can see the exact same text if you manually try to set the encrypted attribute on a file (it is under `Advanced...` on the `General` properties tab).

We need to allow for this specific error in the test:

```
ERROR_NOT_FOUND
1168 (0x490)
Element not found.
```

It is inferred here, but this API is the same thing as checking the attribute box in file properties.

**Comment by jkotas** [comment]
Or just move the test to outer loop since it is sensitive to the environment?

**Comment by JeremyKuhne** [comment]
> Or just move the test to outer loop since it is sensitive to the environment?

Or both. :)

**Comment by ViktorHofer** [comment]
A rolling build just hit a similar issue on arm64: https://dnceng.visualstudio.com/public/_build/results?buildId=306903&view=ms.vss-test-web.build-test-results-tab

```
    System.IO.Tests.EncryptDecrypt.EncryptDecrypt_Read [FAIL]
      System.IO.IOException : The process cannot access the file 'C:\Users\HelixAdmin\AppData\Local\Temp\tmp3B8D.tmp' because it is being used by another process.
      Stack Trace:
        /_/src/System.IO.FileSystem/src/System/IO/FileSystem.Win32.cs(60,0): at System.IO.FileSystem.ThrowExceptionEncryptDecryptFail(String fullPath)
        /_/src/System.IO.FileSystem/src/System/IO/FileSystem.Win32.cs(24,0): at System.IO.FileSystem.Encrypt(String path)
        /_/src/System.IO.FileSystem/src/System/IO/File.cs(650,0): at System.IO.File.Encrypt(String path)
        /_/src/System.IO.FileSystem/tests/File/EncryptDecrypt.cs(44,0): at System.IO.Tests.EncryptDecrypt.EncryptDecrypt_Read()
```

**Comment by ViktorHofer** [comment]
Happened again on arm64: https://dnceng.visualstudio.com/public/_build/results?buildId=379373&view=ms.vss-test-web.build-test-results-tab&runId=11700884&resultId=100000&paneView=attachments

**Comment by ViktorHofer** [comment]
@JeremyKuhne should we disable the test / move it to outerloop as it seems to be flaky?

**Comment by jkotas** [comment]
PR: https://github.com/dotnet/corefx/pull/41604
