### ISSUE TITLE
System.ServiceProcess.ServiceController tests fail in non-English locales

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#39216]
Repro:

1. Install Czech language pack and select Czech as Windows display language
2. Run CoreFX System.ServiceProcess.ServiceController tests

Result:

```
    Starting:    System.ServiceProcess.ServiceController.Tests (parallel test collections = on, max threads = 32)
      System.ServiceProcess.Tests.SafeServiceControllerTests.SetDisplayName_GetServiceName [FAIL]
        System.InvalidOperationException : Service 'Izolace klíce CNG' was not found on computer '.'.
        ---- System.ComponentModel.Win32Exception : Zadaná sluzba není nainstalovaná sluzba.
        Stack Trace:
          D:\corefx\src\System.ServiceProcess.ServiceController\src\System\ServiceProcess\ServiceController.cs(513,0): at System.ServiceProcess.ServiceController.GenerateNames()
          D:\corefx\src\System.ServiceProcess.ServiceController\src\System\ServiceProcess\ServiceController.cs(245,0): at System.ServiceProcess.ServiceController.get_ServiceName()
          D:\corefx\src\System.ServiceProcess.ServiceController\tests\SafeServiceControllerTests.cs(176,0): at System.ServiceProcess.Tests.SafeServiceControllerTests.SetDisplayName_GetServiceName()
          ----- Inner Stack Trace -----

      System.ServiceProcess.Tests.SafeServiceControllerTests.InitializeDisplayName_GetServiceName [FAIL]
        System.InvalidOperationException : Service 'Izolace klíce CNG' was not found on computer '.'.
        ---- System.ComponentModel.Win32Exception : Zadaná sluzba není nainstalovaná sluzba.
        Stack Trace:
          D:\corefx\src\System.ServiceProcess.ServiceController\src\System\ServiceProcess\ServiceController.cs(513,0): at System.ServiceProcess.ServiceController.GenerateNames()
          D:\corefx\src\System.ServiceProcess.ServiceController\src\System\ServiceProcess\ServiceController.cs(245,0): at System.ServiceProcess.ServiceController.get_ServiceName()
          D:\corefx\src\System.ServiceProcess.ServiceController\tests\SafeServiceControllerTests.cs(193,0): at System.ServiceProcess.Tests.SafeServiceControllerTests.InitializeDisplayName_GetServiceName()
          ----- Inner Stack Trace -----

    Finished:    System.ServiceProcess.ServiceController.Tests
  === TEST EXECUTION SUMMARY ===
     System.ServiceProcess.ServiceController.Tests  Total: 19, Errors: 0, Failed: 2, Skipped: 0, Time: 2,818s
```

**Comment by danmosemsft** [comment]
We run tests in es-ES specifically to stay clean of the en-US assumptions in tests that we used to have. I wonder why it has not protected us against these.

**Comment by stephentoub** [comment]
This looks to me like a Windows issue.  `GetServiceDisplayName` is saying it can't find the service by the very localized display name it previously handed back.

**Comment by danmosemsft** [comment]
@tarekgh is there a difference in how es-ES is enabled (the one in our CI) and cs-CZ here? Eg., one is a full edition and one is a language pack? Maybe that accounts for the difference?

**Comment by tarekgh** [comment]
I wouldn't be surprised if this is Windows issue. https://github.com/dotnet/corefx/issues/39177 was Windows issue too. I'll try to take a look to understand what is going on.

**Comment by maryamariyan** [comment]
In the region settings:
- I changed country or region to "Czech Republic"
- Regional Format to "Czech (Czechia)"
- Under Region > Administrative > Change System Locale > set to Czech (Czechia)
- Did a PC restart
- Set language preferences to Czech 

(probably not all of the above needed) 
Didn't get a repro.
The application names are still in english but things like the calendar are showing up in Czech.

Also confirmed in test the following 
```
Assert.True(CultureInfo.CurrentCulture.Name.Equals("cs-CZ", StringComparison.OrdinalIgnoreCase));
```

**Comment by tarekgh** [comment]
@maryamariyan I think you need to keep the default UI locale to en-US. I'll take a look and report back.

**Comment by stephentoub** [comment]
I installed the French language pack from the Windows Store, made it my default, logged out and in, and then the tests similarly started failing, which is how I debugged down to the Windows call.

**Comment by maryamariyan** [comment]
> I installed the French language pack from the Windows Store, made it my default, logged out and in, and then the tests similarly started failing, which is how I debugged down to the Windows call.

Confirmed, had to install the language pack. It was the windows display language that needed to change to get the repro, as you said logged out as well.

**Comment by tarekgh** [comment]
I am noticing something very interesting: 

the test code 
```C#
        public static void SetDisplayName_GetServiceName()
        {
            var keyIsoDisplayName = new ServiceController(KeyIsoSvcName).DisplayName;

            var controller = new ServiceController();
            controller.DisplayName = keyIsoDisplayName;
            Assert.Equal(KeyIsoSvcName.ToLowerInvariant(), controller.ServiceName.ToLowerInvariant());
        }
```

When I run this code on the machine with the installed Czech language and using corefx repo compiled bits, I am seeing the failure. 

If I create a standalone net core app and run the exact code (with doing Console.WriteLine instead of assert), I am not getting the thrown exception. ServiceName would be  empty string though. Also, in the project I was referencing the package

```Xml
  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="4.5.0" />
  </ItemGroup>
```

We may need to look more what is the difference between running with corefx bits and standalone referencing nuget package.

**Comment by tarekgh** [comment]
I have confirmed through the native Windows API calls, calling GetServiceKeyNameW and passing the display name returned from GetServiceDisplayNameW is failing. What I couldn't confirm from the docs if GetServiceKeyNameW support the input localized display name. I guess it should. So, we may send this issue to Windows team. 

What is still not clear to me, when looking at the code, doing 

            var controller = new ServiceController();
            controller.DisplayName = keyIsoDisplayName;

this should initialize the service name with empty string. Then calling controller.ServiceName should return empty string (as I see that in the standalone net core app). but I don't know how the code path get forced to call ```ServiceController.GenerateNames()```

**Comment by tarekgh** [comment]
One thing I discovered, if you reboot the machine after changing the UI language on the machine, the issue will not repro. it is worth filing a bug to Windows anyway.

**Comment by jkotas** [comment]
There are two tests that suffer from this problem. Could you please mark the other one (`InitializeDisplayName_GetServiceName`) as OuterLoop as well?

**Comment by Anipik** [comment]
sorry I missed the other  one. I will add the outerloop to othe one as well
