### ISSUE TITLE
 Culture is not supported error on dotnet 2.2-alpine docker container

### ISSUE THREAD

**Issue by nicoxiang** [dotnet/corefx#39214]
Hi all,

I got an error when publish app to dotnet runtime 2.2-alpine docker container, exception message shows 

> Culture is not supported.
Parameter name: culture
1033 (0x0409) is an invalid culture identifier.

and stacktrace below

>  at System.Globalization.CultureData.GetCultureData(Int32 culture, Boolean bUseUserOverride)
   at System.Globalization.CultureInfo.InitializeFromCultureId(Int32 culture, Boolean useUserOverride)
   at System.Data.XSDSchema.HandleDataSet(XmlSchemaElement node, Boolean isNewDataSet)
   at System.Data.XSDSchema.LoadSchema(XmlSchemaSet schemaSet, DataSet ds)
   at System.Data.DataSet.InferSchema(XmlDocument xdoc, String[] excludedNamespaces, XmlReadMode mode)
   at System.Data.DataSet.ReadXml(XmlReader reader, Boolean denyResolving)
   at System.Data.DataSet.ReadXml(TextReader reader)

https://github.com/dotnet/corefx/blob/master/src/System.Data.Common/src/System/Data/XMLSchema.cs#L2567

I run a test on 'dotnet runtime 2.2-alpine' and  'dotnet sdk 2.2-alpine' container :

`
Console.WriteLine($"{new CultureInfo(0x409).Name}");
`

only 'dotnet runtime 2.2-alpine' container throw exception.  

I also test code:

`
Console.WriteLine($"{new CultureInfo("en-US").Name}");
`

no exception was thrown.

I saw someone reply on [MSDN](https://social.msdn.microsoft.com/Forums/en-US/671bc463-932d-4a9e-bba1-3e5898b9100d/culture-4096-0x1000-is-an-invalid-culture-identifier-culturenotfoundexception?forum=csharpgeneral) said:

> " it is important to always reference cultures based on the culture name rather than the LCID culture identifier to avoid unintended app behavior."

Maybe we can replace culture identifier with culture name here.

**Comment by tarekgh** [comment]
@nicoxiang Alpine image ship with non full Globalization support which is called [Invariant Globalization mode](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/globalization-invariant-mode.md). That is is the limitation on that image to keep the image size as small as possible.

If you want to have full globalization support, you'll need to remove the environment variable ```DOTNET_SYSTEM_GLOBALIZATION_INVARIANT``` and install the ICU library on that image. Usually if you are using System.Data, it will be better to disable the invariant mode.
