### ISSUE TITLE
Regex.IsMatch produces wrong result with RegexOptions.IgnoreCase on Ubuntu 18.04 WSL

### ISSUE THREAD

**Issue by miyconst** [dotnet/corefx#39225]
Discovered after debugging this issue - [dotnet pack always failed on Ubuntu-18.04 with dotnet-sdk-3.0-preview3](https://github.com/dotnet/sdk/issues/3024).

Reporting here, as the original issue does not seem to have much traction.

----------

On Ubuntu 18.04 under [WSL](https://www.microsoft.com/en-us/p/ubuntu-1804-lts/9n9tngvndl3q), `Regex.IsMatch` returns `False` even if the pattern matches the string when `RegexOptions.IgnoreCase` flag passed.

### The applicaiton

```cs
using System;
using System.Text.RegularExpressions;

namespace ConsoleDemo
{
    class Program
    {
        static void Main(string[] args)
        {
            string test = @"Parent/Child.Grand.Child";
            Regex reg = new Regex('^' + Regex.Escape(test) + '$', RegexOptions.IgnoreCase);

            Console.WriteLine("Test string: {0}", test);
            Console.WriteLine("Regex: {0}", reg);
            Console.WriteLine("Regex.IsMatch: {0}", reg.IsMatch(test));
        }
    }
}
```

### Output on vanilla Ubuntu 18.04

```
Test string: Parent/Child.Grand.Child
Regex: ^Parent/Child\.Grand\.Child$
Regex.IsMatch: True
```

### Output on WSL Ubuntu 18.04

```
Test string: Parent/Child.Grand.Child
Regex: ^Parent/Child\.Grand\.Child$
Regex.IsMatch: False
```

Removing `RegexOptions.IgnoreCase` option fixes the output on WSL as well.

------------

<details>
<summary>
`dotnet --info`
</summary>

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /home/star/dotnet/sdk/3.0.100-preview6-012264/

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf

.NET Core SDKs installed:
  3.0.100-preview6-012264 [/home/star/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [/home/star/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [/home/star/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

</details>

**Comment by danmosemsft** [comment]
What is the value of the LANG environment variable? @tarekgh

**Comment by miyconst** [comment]
>What is the value of the LANG environment variable?

```
user@DESKTOP-7U2PNF8:~$ echo $LANG
C.UTF-8
```

**Comment by stephentoub** [comment]
That's the issue, most likely. Try changing it to something like en-US.UTF-8.

(https://github.com/dotnet/coreclr/pull/25373 should also address it in 3.0.)

**Comment by miyconst** [comment]
Thanks @stephentoub, it works with `LANG=en-US.UTF-8`.

**Comment by tarekgh** [comment]
Closing the issue as we already addressed it as @stephentoub pointed out and there is a workaround too.
