### ISSUE TITLE
Utf8JsonReader.Skip has inconsistent behavior for properties

### ISSUE THREAD

**Issue by scalablecory** [dotnet/corefx#39237]
`Utf8JsonReader.Skip` behaves in away that is not obvious depending on the current token type:

* If the token is a property name, it skips the name and places the reader on the first token of the property value.
* If the token is anything else, it moves the reader to the last token of the current "thing", and the next `Read()` will put you on the next "thing".

I would, instead, expect one of the following behaviors:
* If we consider a property to be an entire "thing", then move the reader to the last token of the property value. This doesn't sound ideal to me but I can see an argument for it...
* Otherwise, `Skip()` should be a NOP for property names as it is for anything else that is not an array/object.

**Comment by scalablecory** [comment]
@ahsonkhan not sure if this is locked in yet.

**Comment by ericstj** [comment]
@scalablecory do you have any precedent for the expected behavior?  What does JSON.NET do?  /cc @bartonjs @layomia

**Comment by bartonjs** [comment]
The plan for Skip, last I knew, was that it always ends up on the last token of the "logical value".  If the current TokenType is PropertyName, it should call Read once, then evaluate Skip as if that was its starting point.

"logical value": the value represented by (or started by) the current token... unless the current token is of type PropertyName, then the value represented by/started by the next token.

**Comment by bartonjs** [comment]
For properties, this was a target scenario:

```C#
while (reader.Read())
{
    if (reader.TokenType == JsonTokenType.EndObject)
    {
        break;
    }

    Debug.Assert(reader.TokenType == JsonTokenType.PropertyName);
    string propertyName = reader.GetString();

    switch (propertyName)
    {
        case "etc":
            ReadEtc(ref reader, state);
            break;
       ...
       default:
           reader.Skip();
           // Now the next call to Read() will result in either PropertyName or EndObject
           break;
    }
}
```

And for arrays:

```C#
while (reader.Read())
{
    if (reader.TokenType == JsonTokenType.EndArray)
    {
        break;
    }
    else if (reader.TokenType == JsonTokenType.String)
    {
        _strings.Add(reader.GetString());
    }
    else
    {
        reader.Skip();
        // if we were StartObject or StartArray we're now at the matching EndObject/EndArray
        // so the loop call to Read() will position us at the next element in this array.
    }
}
```

**Comment by scalablecory** [comment]
@bartonjs that works for me.

**Comment by bartonjs** [comment]
@scalablecory Just to double check: What I'm describing is that it should work like your first bullet under "I would, instead, expect...".  If you're seeing a behavior other than that (e.g. that the TokenType is not PropertyName (or EndObject) after calling Skip() then Read() from a PropertyName) then there's a bug (or something in the design changed).

**Comment by ahsonkhan** [comment]
For completeness, this is consistent with Json.NET's behavior:
https://github.com/dotnet/corefx/blob/e6a5951fb68a09598f1fc1826a94de212385c649/src/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.cs#L318-L342

https://github.com/JamesNK/Newtonsoft.Json/blob/f940f218041dbc80928ebcd65fe8beaac59f70f1/Src/Newtonsoft.Json/JsonReader.cs#L957-L972

It's also similar to XmlReader, though, if I understand it correctly, it treats "primitive values" differently and still skips one (skip == read in that case, where we no-op on json):
https://github.com/dotnet/corefx/blob/e6a5951fb68a09598f1fc1826a94de212385c649/src/System.Private.Xml/src/System/Xml/Core/XmlReader.cs#L1516-L1538
