### ISSUE TITLE
HTTP2: Pending bytes from a previous frame may not be flushed if another pending write is canceled

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#39234]
Consider two frames both trying to acquire the write lock concurrently.  One of them gets it, the other has to wait and registers itself as a pending writer.  The first frame then doesn't require itself to be flushed if there are pending writers, and so writes itself to the buffer but doesn't explicitly flush.  Between the time that it checks for pending writers and does the write, however, the other frame is canceled, and the pending writers count is decremented back to 0.  There's now data in the buffer that needed to be flushed, but there's no pending write that's going to do it.

We could "easily" address this by only counting a non-cancelable write as one that can be pending, but from HttpClient every request will use a cancelable token, and thus all header/data frame writes associated with that request will be cancelable.

A more robust solution is probably to queue a forced flush in the case where a pending waiter is canceled.

cc: @geoffkizer

**Comment by geoffkizer** [comment]
Thanks for finding and fixing.
