### ISSUE TITLE
Reading Console.CursorLeft is blocked by Console.ReadLine in another thread

### ISSUE THREAD

**Issue by jchristn** [dotnet/corefx#39246]
I noticed this issue here was closed: https://github.com/dotnet/corefx/issues/24654

I'm using .NET Core 2.2 and the issue still exists.

Sample code here, run ```dotnet consoletest.dll false``` to see without the ```Console.ReadLine()``` and ```dotnet consoletest.dll``` to see with the ```Console.ReadLine()```.

When running with the ```Console.ReadLine()``` on Ubuntu 18.04, the worker threads are blocked because they are waiting for the value from ```Console.CursorLeft```.

```
using System;
using System.Threading;
using System.Threading.Tasks;
 
namespace ConsoleTest
{
    class Program
    {
        static bool runConsoleWorker = true; 

        static void Main(string[] args)
        { 
            if (args != null && args.Length > 0)
            {
                if (args[0].Equals("false")) runConsoleWorker = false;
            }

            Task.Run(() => BackgroundWorker("Worker 1 says hello"));
            Task.Run(() => BackgroundWorker("Worker 2 says hello"));

            if (runConsoleWorker)
            {
                Console.WriteLine("Starting console worker...");
                ConsoleWorker();
            }
            else
            {
                Console.WriteLine("Awaiting wait handle...");
                EventWaitHandle waitHandle = new EventWaitHandle(false, EventResetMode.AutoReset, null);
                bool waitHandleSignal = false;
                do
                {
                    waitHandleSignal = waitHandle.WaitOne(1000);
                }
                while (!waitHandleSignal);
            }
        }

        static void ConsoleWorker()
        {
            while (true)
            {
                Console.Write("Enter some text: ");
                Console.ReadLine();
            }
        }

        static void BackgroundWorker(string text)
        {
            while (true)
            {
                Task.Delay(1000).Wait(); 
                if (Console.CursorLeft != 0) Console.WriteLine("");
                Console.WriteLine(text);
            }
        }
    }
}
```

**Comment by jchristn** [comment]
BTW I only notice this on Linux. Have not tried on Mac. Issue doesn’t seem to exist on Windows. When I tested on Linux, it was Ubuntu 18.04.

**Comment by stephentoub** [comment]
Getting the current cursor position on Unix requires writing to stdout and reading from stdin, so if there's a pending ReadLine from stdin in progress, getting the current cursor position synchronizes with it.

**Comment by jchristn** [comment]
Ah, I see.  I wish I would have understood this a week ago :)  Is there a path forward or is this a "working as expected" condition that no one will attempt to resolve (or there is no possible way to resolve)?  Thanks for getting back to me!

**Comment by stephentoub** [comment]
It's working as expected, though I understand it's not ideal for your needs. It's possible there's a change that could be made to address it, but I suspect it would be far from simple, and currently there are no plans to address it. If someone submitted a PR for it, we'd certainly evaluate it, though.

**Comment by jchristn** [comment]
Ok thanks, I'll close this.  It was difficult to track this down to the source of the problem because the Console.CursorLeft was actually buried in a NuGet package I use.  Have a great day @stephentoub
