### ISSUE TITLE
WinHttpHandler: setting TransferEncodingChunked = true causes request to be downgraded to HTTP/1.1

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#39293]
With SocketsHttpHandler, we just ignore TransferEncodingChunked on HTTP2 requests. WinHttpHandler, by contrast, seems to downgrade to HTTP/1.1 in this case.

You can see this by running the PostUsingChunkedEncoding_Success test with WinHttpHandler and setting the DefaultRequestVersion = 2.0.

**Comment by davidsh** [comment]
WinHttpHandler is letting native WinHTTP do that. It simply passes on the Transfer-Encoding: chunked request headers (along with other request headers).

Is this issue suggesting we should make a change to WinHttpHandler to actively strip-off the 'Transfer-Encoding: chunked' header if the HttpRequestMessage.Version is set to (2,0)?

**Comment by geoffkizer** [comment]
Maybe we don't need to do anything here. But the behavior is different than SocketsHttpHandler, and that at least seems worth understanding.

Looking at this further, the case that worries me more is the PostUsingNoSpecifiedSemantics_UsesChunkedSemantics case, which is also downgrading to HTTP/1.1. We're not setting TransferEncodingChunked here. We're just relying on the handler to choose the right way to send the body, and for some reason this is getting sent as HTTP/1.1 with WinHttpHandler.

**Comment by davidsh** [comment]
>PostUsingNoSpecifiedSemantics_UsesChunkedSemantics case, which is also downgrading to HTTP/1.1. We're not setting TransferEncodingChunked here. We're just relying on the handler to choose the right way to send the body, and for some reason this is getting sent as HTTP/1.1 with WinHttpHandler.

The test is verifying that in cases where no semantics are specific for request body upload (i.e. no 'Content-Length' nor 'Transfer-Encoding'), then chunked is used. But that logic was invented before HTTP/2.0 came along.

So, probably, we need to update the handlers (all of them) to include HTTP/2.0 in the logic. So, if using HTTP/2.0 (HttpRequestMessage.Version = (2,0)) then, "no specified semantics" is fine since perhaps we need to pick 'Content-Length'.  However, some request body content that uses streams might not be able to calculate a length at all (TryComputeLength() returns false). Perhaps that is not an issue for HTTP/2.0 since it would continually read the request stream until EOF.

**Comment by geoffkizer** [comment]
As far as I can tell, it's actually not verifying anything about *how* the body is sent, it's just verifying that it was sent correctly.

But yeah, it seems worth understanding why WinHttpHandler is using HTTP/1.1 here.

**Comment by davidsh** [comment]
>But yeah, it seems worth understanding why WinHttpHandler is using HTTP/1.1 here.

WinHttpHandler leaves the 'Transfer-Encoding: chunked' request as-is. WinHttpHandler also sets specific WinHTTP settings when HttpRequestMessage.Version = (2,0).  It's very possible that native WinHTTP is detecting the presence of the 'Transfer-Encoding: chunked' request header and simply then igoring the HTTP/2.0 request version. That would be a WinHTTP behavior we have no control over.

The real question is "Do we want to change the behavior of WinHttpHandler to ignore/suppress the Transfer-Encoding: chunked header when HTTP/2.0 is requested?" Make this change is something we could do in .NET Core.

**Comment by karelz** [comment]
Triage: Looks like the behavior is not ideal, but kind of ok. There is likely not good way to fix it -- beside fixing it in WinHttp.
Given there is no customer complaint, we will close it for now. Happy to reconsider in future.
