### ISSUE TITLE
HTTP2: Incorrect exception thrown when attempting to resend non-rewindable content

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#39295]
See SocketsHttpHandler_PostScenarioTest.PostNonRewindableContentUsingAuth_NoPreAuthenticate_ThrowsHttpRequestException with HTTP2

This is throwing an InvalidOperationException, when it should be throwing an HttpRequestException with an inner exception of type InvalidOperationException.

**Comment by karelz** [comment]
@eiriktsarpalis can you please fix this one as well? @davidsh can provide advice/pointers ...

**Comment by eiriktsarpalis** [comment]
@geoffkizer could you provide a bit more context? Test is passing locally and seems to be doing the same in outerloop test runs.

**Comment by davidsh** [comment]
>@geoffkizer could you provide a bit more context? Test is passing locally and seems to be doing the same in outerloop test runs.

I suspect that this test is only failing due to @geoffkizer pending PR #39343.  So, until that PR gets merged, you'l need to temporarily adjust the test's code to force it to use HTTP/2.0 protocol I think. Then I think you'll see the test failure.

**Comment by eiriktsarpalis** [comment]
I forced http/2 by changing [this line](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTestBase.cs#L21), but the test is still passing for me locally.

**Comment by davidsh** [comment]
I don't think this test derives from that base class.  Also, you need to make sure the test endpoint is the HTTP/2 remote server and not the HTTP/1 remote server. 

If it still isn't repro'ing then @geoffkizer will need to comment.

**Comment by stephentoub** [comment]
> I forced http/2 by changing this line, but the test is still passing for me locally.

I don't think that's sufficient, as in master the server it's talking to only speaks 1.1:
https://github.com/dotnet/corefx/blob/689e58ec123d8c730d48d1c35c8f7ecbba6c22cf/src/Common/tests/System/Net/Configuration.cs#L10
@geoffkizer's changes in https://github.com/dotnet/corefx/pull/39343 are fixing up these tests to actually talk to an appropriate remote server for its version:
https://github.com/dotnet/corefx/pull/39343/files#diff-94af524660d1444b9a137d3b0f637775R182

**Comment by eiriktsarpalis** [comment]
OK, I'm repro'ing now.

**Comment by eiriktsarpalis** [comment]
Comparing with the v1.1 implementation it seems like I need to adapt the logic found [here](https://github.com/dotnet/corefx/blob/ccf9ccfc38922cfe1c6eaa568e83b09119a2dd6b/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L714-L718) to this [handler](https://github.com/dotnet/corefx/blob/ccf9ccfc38922cfe1c6eaa568e83b09119a2dd6b/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L1594-L1601).

As a side note, the exception emanates from `HttpContent.SerializeToStreamAsync()` which is override-able and could throw arbitrary exception types. Shouldn't those be getting wrapped as well?

**Comment by davidsh** [comment]
>Shouldn't those be getting wrapped as well?

Probably. If you decide to fix that as part of this PR, please add more tests to validate that fix.

**Comment by eiriktsarpalis** [comment]
> Probably. If you decide to fix that as part of this PR, please add more tests to validate that fix.

Is divergence of behaviour compared to the 1.1 implementation acceptable?

**Comment by davidsh** [comment]
>Is divergence of behaviour compared to the 1.1 implementation acceptable?

The exception should only be wrapped as it emanates from the HttpClient APIs. It doesn't get wrapped right away from those HttpContent methods.  Perhaps it would be best to focus on that change separately and with a specific test case so that we can better understand what behaviors might change.
