### ISSUE TITLE
RID for Alpine 3.10

### ISSUE THREAD

**Issue by mthalman** [dotnet/corefx#39294]
Alpine 3.10 has been released so there should be RID support for it: https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/runtime.json.

**Comment by ericstj** [comment]
@bartonjs @wfurt do we support Alpine 3.10?

I believe we typically service for this sort of thing so that would mean we should take this for 3.0.

**Comment by bartonjs** [comment]
Yep, it's a new version of a supported distro.  There are some other changes that need to be ported over (macOS 10.15, RHEL 8.1).  I'll do this today.

**Comment by bartonjs** [comment]
Fixed by #39300 (3.0 and master).
Also: #39302 and #39303 (2.1, 2.2, respectively)
