### ISSUE TITLE
Windows 7 build fails (update dev instructions about proxies and myget.org access)

### ISSUE THREAD

**Issue by deserthacker** [dotnet/corefx#3930]
I've been trying to build the latest good build for a couple of hours, I've updated dnvm and dnu build still cannot build:

EXEC : error : FindPackagesById: Microsoft.NETCore.Platforms [c:\git\dotnet\corefx\build.proj]
    An error occurred while sending the request.
EXEC : error : FindPackagesById: coveralls.io [c:\git\dotnet\corefx\build.proj]
    An error occurred while sending the request.
EXEC : error : FindPackagesById: Microsoft.NETCore.Console [c:\git\dotnet\corefx\build.proj]
    HTTP request timed out. Exiting.
EXEC : error : FindPackagesById: Microsoft.NETCore.TestHost [c:\git\dotnet\corefx\build.proj]
    An error occurred while sending the request.
EXEC : error : FindPackagesById: OpenCover [c:\git\dotnet\corefx\build.proj]
    An error occurred while sending the request.
EXEC : error : FindPackagesById: Microsoft.NETCore.Platforms [c:\git\dotnet\corefx\build.proj]
    HTTP request timed out. Exiting.
EXEC : error : FindPackagesById: coveralls.io [c:\git\dotnet\corefx\build.proj]
    HTTP request timed out. Exiting.
EXEC : error : FindPackagesById: Microsoft.NETCore.TestHost [c:\git\dotnet\corefx\build.proj]
    HTTP request timed out. Exiting.
EXEC : error : FindPackagesById: Microsoft.NETCore.Console [c:\git\dotnet\corefx\build.proj]
    HTTP request timed out. Exiting.
EXEC : error : FindPackagesById: OpenCover [c:\git\dotnet\corefx\build.proj]
    An error occurred while sending the request.
EXEC : error : FindPackagesById: xunit.runner.utility [c:\git\dotnet\corefx\build.proj]
    An error occurred while sending the request.
EXEC : error : FindPackagesById: Microsoft.NETCore.Platforms [c:\git\dotnet\corefx\build.proj]
    HTTP request timed out. Exiting.
EXEC : error : FindPackagesById: ReportGenerator [c:\git\dotnet\corefx\build.proj]
    An error occurred while sending the request.
EXEC : error : FindPackagesById: Microsoft.NETCore.Platforms [c:\git\dotnet\corefx\build.proj]
    HTTP request timed out. Exiting.
EXEC : error : FindPackagesById: xunit.runner.utility [c:\git\dotnet\corefx\build.proj]
    An error occurred while sending the request.
EXEC : error : FindPackagesById: ReportGenerator [c:\git\dotnet\corefx\build.proj]
    HTTP request timed out. Exiting.
EXEC : error : FindPackagesById: Microsoft.DotNet.xunit.performance.analysis [c:\git\dotnet\corefx\build.proj]
    HTTP request timed out. Exiting.
EXEC : error : FindPackagesById: ReportGenerator [c:\git\dotnet\corefx\build.proj]
    An error occurred while sending the request.
c:\git\dotnet\corefx\build.proj(24,5): error MSB3073: The command ""c:\git\dotnet\corefx\packages//dnx-coreclr-win-x86.1.0.0-beta7/
\bin\dnu.cmd" restore --packages "c:\git\dotnet\corefx\packages" --source https://www.myget.org/F/dotnet-core/ --source https://www
.myget.org/F/dotnet-coreclr/ --source https://www.myget.org/F/dotnet-corefxtestdata/ --source https://www.myget.org/F/dotnet-buildt
ools/ --source https://www.nuget.org/api/v2/ "c:\git\dotnet\corefx\src" "c:\git\dotnet\corefx\packages/Microsoft.DotNet.BuildTools.
1.0.25-prerelease-00104/lib/"" exited with code 1.

I'd think this should "just work", did I miss an install or setup step?

**Comment by joshfree** [comment]
@deserthacker are you still seeing HTTP timeouts/errors?

**Comment by deserthacker** [comment]
Yes, still seeing timeouts.  Here's what I did, opened a VS2013 command window, typed build from the command line, timeouts are actually much worse today than the other day; it seems the build cannot resolve even common types:

EXEC : warning : FindPackagesById: runtime.win7.System.Runtime.Extensions [c:\git\dotnet\corefx\build.proj]
EXEC : warning : FindPackagesById: runtime.win7.System.Runtime.Extensions [c:\git\dotnet\corefx\build.proj]
EXEC : warning : FindPackagesById: runtime.win7.System.Runtime.Extensions [c:\git\dotnet\corefx\build.proj]
EXEC : warning : FindPackagesById: runtime.win7.System.Runtime.Extensions [c:\git\dotnet\corefx\build.proj]
EXEC : warning : FindPackagesById: runtime.win7.System.Runtime.Extensions [c:\git\dotnet\corefx\build.proj]
EXEC : warning : FindPackagesById: runtime.win7.System.Runtime.InteropServices.RuntimeInformation [c:\git\dotnet\corefx\build.proj]
EXEC : warning : FindPackagesById: runtime.win7.System.Runtime.InteropServices.RuntimeInformation [c:\git\dotnet\corefx\build.proj]
EXEC : warning : FindPackagesById: runtime.win7.System.Runtime.InteropServices.RuntimeInformation [c:\git\dotnet\corefx\build.proj]
EXEC : warning : FindPackagesById: runtime.win7.System.Runtime.InteropServices.RuntimeInformation [c:\git\dotnet\corefx\build.proj]
EXEC : warning : FindPackagesById: runtime.win7.System.Runtime.InteropServices.RuntimeInformation [c:\git\dotnet\corefx\build.proj]

The build has been running for about 15 minutes just trying to restore packages, I'm assuming it will fail again.  Is there a configuration I'm missing somewhere?

**Comment by deserthacker** [comment]
Spent more time digging into this issue and root caused it to the proxy server on my corporate LAN, appears that something changed on that server and caused me fits.

Is there a best practice for repeatable builds?  Local nuget repository behind firewall?  Proxy server configured differently?

I think this is what I need to solve my issue.

**Comment by karelz** [comment]
Old issue, most likely not valid anymore. Please reopen if it still happens.
