### ISSUE TITLE
Make Microsoft.Win32.SystemEvents static

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#39308]
This is a holdover "static like class" from pre .NET 2.0 that wasn't made static.

Current:

``` C#
namespace Microsoft.Win32
{
    public sealed class SystemEvents
    {
        private SystemEvents()
        {
        }
    }
}
```

Proposed:

``` C#
namespace Microsoft.Win32
{
    public static class SystemEvents
    {
    }
}
```

**Comment by terrajobst** [comment]
(You can use this issue for any class whether all public APIs are static, all constructors are private, and the type is sealed)

**Comment by danmosemsft** [comment]
Just curious is there any benefit to doing this other than tidiness?

**Comment by Marusyk** [comment]
I can prepare PR for this. If it is really needed then please assign the issue to me

**Comment by JeremyKuhne** [comment]
@Marusyk, feel free to give it a shot. This particular one is a little tricky to accomplish. :)

**Comment by Marusyk** [comment]
What about this code
https://github.com/dotnet/corefx/blob/b75421a0035bf3a44e1f68447255470d57074dbb/src/Microsoft.Win32.SystemEvents/src/Microsoft/Win32/SystemEvents.cs#L41-L44

Should I add lock for that?

**Comment by stephentoub** [comment]
> This is a holdover "static like class" from pre .NET 2.0 that wasn't made static.

It's instantiated in the implementation:
https://github.com/dotnet/corefx/blob/b75421a0035bf3a44e1f68447255470d57074dbb/src/Microsoft.Win32.SystemEvents/src/Microsoft/Win32/SystemEvents.cs#L481
and
https://github.com/dotnet/corefx/blob/b75421a0035bf3a44e1f68447255470d57074dbb/src/Microsoft.Win32.SystemEvents/src/Microsoft/Win32/SystemEvents.cs#L491
as part of lazily-initializing the instance, and the lazy initialization factors in information about the thread that's doing the initialization.

This doesn't seem worth changing to me.  @JeremyKuhne, can this be closed, or are you hoping the implementation will be overhauled?
