### ISSUE TITLE
System.Drawing.Common lower .netstandard version?

### ISSUE THREAD

**Issue by MattSFT** [dotnet/corefx#39326]
Is it possible to downgrade the .netstandard requirement for https://www.nuget.org/packages/System.Drawing.Common?

I don't know enough about the specifics of this library so not sure it is possible, but I would like to use it in a project targeting .netstandard 1.3.

**Comment by carlossanlop** [comment]
@safern moved for easier tracking.

**Comment by jkotas** [comment]
We do not plan to back port any libraries to netstandard1.x. We recommend everybody to upgrade to netstandard2.0.
