### ISSUE TITLE
redirect process failed

### ISSUE THREAD

**Issue by fawdlstty** [dotnet/corefx#39324]
# Issue Title

redirect process failed

# General

.net core 2.1
os version: centos 7.5
build env: win10 x64 (cross compile, linux-x64 independent)

my program is a single http server, powered by HttpListener, it run well a long time. I have try to add a function that it Git updates and restarts when a special HTTP response is received. code like this:

```csharp
_server.add_get_event ("_update", (_gets) => {
    using (var _ps = new Process ()) {
        _ps.StartInfo = new ProcessStartInfo ("git", "pull -v --progress \"origin\"") {
            RedirectStandardInput = true,
            RedirectStandardOutput = true,
            RedirectStandardError = true
        };
        _ps.OutputDataReceived += (_sender, _e) => {
            if (_e.Data == null)
                return;
            Console.WriteLine ($"recv data: [{_e.Data}]");
            if (_e.Data.IndexOf ("Username for") != -1) {
                _ps.StandardInput.WriteLine ("test1");
            } else if (_e.Data.IndexOf ("Password for") != -1) {
                _ps.StandardInput.WriteLine ("test1");
            }
        };
        _ps.ErrorDataReceived += (_sender, _e) => { };
        _ps.Start ();
        _ps.BeginOutputReadLine ();
        while (!_ps.HasExited)
            Thread.Sleep (100);
    }
    Thread.Sleep (100);
    _psi = new ProcessStartInfo ("dotnet", "Myserver.dll");
    using (var _ps = Process.Start (_psi)) {
    }
    new Thread (() => { Thread.Sleep (100); Environment.Exit (0); }).Start ();
    return $"restart...".to_bytes ();
});
```

and the code run success for my win10 env,but it run in centos, the redirect is not work, the putty output:

![20190607222647](https://user-images.githubusercontent.com/7323999/59115629-4189a300-897c-11e9-87b8-0d7cef6e8587.jpg)

the username and password is typed by myself, and the git prompts for a user name and this line should have been redirected to the process pipeline.

**Comment by carlossanlop** [comment]
Transferred from the dotnet/core repo.
CC'ing @wtgodbe, @krwq to assist with the question.

**Comment by wfurt** [comment]
It is likely that the git is expecting tty for interactive operation. Typically it would for example turn off terminal echo so it does not show as you type password. When running in background (like web server) , tty is not available and interactive programs do fail. This is general Unix behavior independent of  Process() class. 

You may check https://git-scm.com/docs/git-credential or use something like https://stackoverflow.com/questions/14629107/how-to-input-password-to-git-pull-command

**Comment by krwq** [comment]
I'd recommend playing with one of the environment variables (I couldn't see any command line switches, perhaps):

```
       GIT_TERMINAL_PROMPT
           If this environment variable is set to 0, git will not prompt on the terminal (e.g., when asking for
           HTTP authentication).
       GIT_ASKPASS
           If this environment variable is set, then Git commands which need to acquire passwords or passphrases
           (e.g. for HTTP or IMAP authentication) will call this program with a suitable prompt as command-line
           argument and read the password from its STDOUT. See also the core.askPass option in git-config(1).
```

also might be better to use ArgumentList instead of Arguments on ProcessStartInfo to avoid any quote escaping issues

**Comment by fawdlstty** [comment]
No, my question is about the line of 'Username for / Password for'，why it is not print 'recv data: []'? At least the input username line is a normal input/output interaction, right?

**Comment by krwq** [comment]
@fawdlstty I believe this might be `/dev/tty` which does the interactive part vs `/dev/stdin` or `/dev/stdout` which mean standard input/output. Perhaps there is some way to interact with that i.e. by redirecting input/output correctly but I'm not familiar with this too much. @wfurt any thoughts?

**Comment by wfurt** [comment]
I did quick test on centos:
```
 strace -f -otrace.txt git pull -v --progress origin > /tmp/aa
Username for 'https://github.com':
```
The fact that the text still shows, tells me that it is not going to stdout. (it would be redirected)

and looking at the trace:
```
11081 open("/dev/tty", O_RDONLY)        = 6
11081 open("/dev/tty", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 7
11081 fstat(7, {st_mode=S_IFCHR|0666, st_rdev=makedev(5, 0), ...}) = 0
11081 ioctl(7, TCGETS, {B38400 opost isig icanon echo ...}) = 0
11081 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f6b59c53000
11081 write(7, "Username for 'https://github.com"..., 35) = 35
```

You mentioned that it works without auth  @fawdlstty Why don't you save it to $HOME/.netrc or set up github credentials. (note that the HOME can be anything and can be set within your execution. 
Another alternative is to use program like tmux to force pty allocation for git. 
You can practice all this outside of .Net from shell.
And if course you can wrap everything in shell script and call that from your application.

**Comment by fawdlstty** [comment]
I'm solving this problem by saving the credentials, but I'm just a little confused about this
