### ISSUE TITLE
Code coverage of corelib taking a really long time and generating 404s

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#39322]
I built corelib locally, then tried to do a coverage run of System.Threading.Tasks\tests.  It takes minutes after tests complete to produce a report, and spits out error messages like (why is it trying to access such uris?):
```
  Initializing report builders for report types: Html
  Analyzing 1078 classes
   Error during reading file 'https://raw.githubusercontent.com/stephentoub/coreclr/4994ad73f0a4700475c025e478d70de69041dbcb/bin/obj/Windows_NT.x64.Release/Eventing/NativeRuntimeEventSource.cs': Response status code does not indicate success: 404 (Not Found).
   Error during reading file 'https://raw.githubusercontent.com/stephentoub/coreclr/4994ad73f0a4700475c025e478d70de69041dbcb/bin/obj/Windows_NT.x64.Release/System.Private.CoreLib/System.SR.cs': Response status code does not indicate success: 404 (Not Found).
    Writing report file 'd:\repos\corefx\artifacts\bin\System.Threading.Tasks.Tests\netcoreapp-Debug\report\index.htm'
  Report generation took 126.1 seconds
```
Subsequent attempts are faster but still spit out 404s.

cc: @ViktorHofer

**Comment by ViktorHofer** [comment]
Nothing changed here, it was always like that. The 404s are expected as those files aren't present in the repository but in the coverage result file. There's a cache that in ReportGenerator which should be by default 2-3 weeks so subsequent builds are much faster. If you don't want to use source Link for corelib

**Comment by stephentoub** [comment]
> /p:CoverageSourceLink=false

Why isn't this the default? In what situation would I be using a locally built corelib and want source link?

**Comment by ViktorHofer** [comment]
How would infra know that you are using a local corelib when building an individual library? For that we would need to create a different path by ie adding a marker file. I didn't write the runtime binplacing logic so I don't know if something like that already exists.

**Comment by ViktorHofer** [comment]
Our do you need to pass in that override property when building an individual library as well?

**Comment by ViktorHofer** [comment]
cc @ericstj

**Comment by stephentoub** [comment]
Well, if it's working as expected, I'll close this.
