### ISSUE TITLE
System.Buffers dll specifically targetting .NetFramework instead of reusing the .NetStandard one

### ISSUE THREAD

**Issue by rymeskar** [dotnet/corefx#39362]
Based on conversation with @ericstj in the following [thread](https://github.com/dotnet/corefx/issues/36754), we would like if System.Buffers specifically targeted .NETFramework so that we can depend on it without requiring our consumers to bring in all of the .NETStandard support dlls. 
Reason: the known incompatibilities between .NetStandard 2.0 and framework >=4.6.1 && <4.7.2.

**Comment by ericstj** [comment]
This is a duplicate of https://github.com/dotnet/corefx/issues/37639
