### ISSUE TITLE
How to detect linux distribution name/version when in WSL?

### ISSUE THREAD

**Issue by tlmii** [dotnet/corefx#39366]
Over at https://github.com/aspnet/HttpRepl, there's [some code](https://github.com/aspnet/HttpRepl/blob/13bd26c3c91407dc835a463bea496fc160d42fb9/src/Microsoft.Repl/Input/InputManager.cs#L122) that does detection of linux distro in order to decide if some STTY settings need to be changed. 

This works fine on normal installs of Ubuntu, but in Ubuntu 18.04 on WSL2, the call to `RuntimeInformation.OSDescription` returns the following:

> "Linux 4.19.43-microsoft-standard #1 SMP Mon May 20 19:35:22 UTC 2019"

Is there a way to get the distribution name/version from .NET Core in this scenario? Or should we resort to something like piping the output of `lsb_release -a`?

**Comment by danmosemsft** [comment]
Looks like you need to add a package reference to `Microsoft.DotNet.PlatformAbstractions` then you can get it from `Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.OperatingSystem` and `Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.OperatingSystemVersion`

Code is here https://github.com/dotnet/core-setup/blob/master/src/managed/Microsoft.DotNet.PlatformAbstractions/RuntimeEnvironment.cs

On my machine it returns "ubuntu" and "18.04"

We would like to expose this information in the bass class libraries but that work has been pushed out of 3.0 for now. That is tracked already in https://github.com/dotnet/corefx/issues/31002

**Comment by danmosemsft** [comment]
If you don't want the package reference (which is great, we would rather deprecate that package long term) looks like you can copy code. See LoadDistroInfo in that repo.

**Comment by tlmii** [comment]
Perfect. Thanks Dan. I'll talk it over with the team and make a call on which way to go. Good to know you'd like to deprecate, as that'll probably impact our decision.

**Comment by danmosemsft** [comment]
Tracked by other issue...
