### ISSUE TITLE
System.Text.Json Deserialize Not Ignoring Property

### ISSUE THREAD

**Issue by realdevhl** [dotnet/corefx#39373]
Take the following class:

```
public class MyObject
{
    [JsonIgnore]
    public List<object> MyAttribute { get; set; }

    [JsonPropertyName("MyAttribute")]
    public int MyAttributeCount { get; set; }
}
```

And then try to parse some JSON

```
json = $"{{\"MyAttribute\": 0}}";

MyObject myObject = JsonSerializer.Parse<MyObject>(json);
```

Results in the following error.

'The JSON property name for 'MyObject.MyAttributeCount' collides with another property.'

If I remove the property decorated with JSONIgnore then it works.

I am using System.Text.Json v4.6.0-preview6.19303.8

**Comment by ericstj** [comment]
@layomia can you have a look?

**Comment by steveharter** [comment]
This is a duplicate of #38668

This was fixed in https://github.com/dotnet/corefx/pull/38935
