### ISSUE TITLE
EventLogTests.GetEventLogEntriesTest failed in CI on Windows 7

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#39389]
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F39383~2Fmerge/test~2Ffunctional~2Fcli~2F~2F/20190711.7/workItem/System.Diagnostics.EventLog.Tests/analysis/xunit/System.Diagnostics.Tests.EventLogTests~2FGetEventLogEntriesTest
```
Windows.7.Amd64.Open-x64-Debug
Get Repro environment
Unhandled Exception of Type System.ComponentModel.Win32Exception
Message :
System.ComponentModel.Win32Exception : Access is denied.
Stack Trace :
   at System.Diagnostics.EventLogInternal.get_EntryCount() in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs:line 157
   at System.Diagnostics.EventLogEntryCollection.get_Count() in /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogEntryCollection.cs:line 22
   at System.Diagnostics.Tests.EventLogTests.GetEventLogEntriesTest() in /_/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogTests.cs:line 359
```

**Comment by danmosemsft** [comment]
Looks like this test is missing the retries we do elsewhere for Win7.
`Assert.True(eventLog.Entries.Count >= 0);` should probably be something like 
```c#
int count;
Helpers.RetryOnWin7(() => { count = eventLog.Entries.Count; });
Assert.True(count >= 0);
```

**Comment by JeremyKuhne** [comment]
Hit again on Windows.7.Amd64.Open-x64-Debug:

https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F39275~2Fmerge/test~2Ffunctional~2Fcli~2F~2F/20190712.39/workItem/System.Diagnostics.EventLog.Tests/analysis/xunit/System.Diagnostics.Tests.EventLogTests~2FGetEventLogEntriesTest

**Comment by danmosemsft** [comment]
@anipik

**Comment by stephentoub** [comment]
Failed again here:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F39504~2Fmerge/test~2Ffunctional~2Fcli~2F~2F/20190715.58/workItem/System.Diagnostics.EventLog.Tests/analysis/xunit/System.Diagnostics.Tests.EventLogTests~2FGetEventLogEntriesTest
