### ISSUE TITLE
JsonElement.WriteValue(writer) writing wrong characters for invalid surrogate pairs

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/corefx#39397]
I assume it should throw for invalid surrogates, so wrote the tests throwing ArgumentException. 
Whatever i believe that it souldn't write unexpected values. For both tests the written values were `"\\ufffd\\ufffd\\ufffd"` instead of `"\\udc00\\ud800\\ud803"` or throwing
```csharp
[Fact]
public static void WriteValueSequenceWithInvalidSurrogatesShouldThrow2()
{
    char[] chars = new char[] { '[', '"', (char)0xDC00, (char)0xD800, (char)0xD803, '"', ']' };
    var buffer = new ArrayBufferWriter<byte>(128);
    byte[] temp = Encoding.UTF8.GetBytes(chars);
    ReadOnlySequence<byte> sequence = JsonTestHelper.GetSequence(temp, 1);

    using (JsonDocument doc = JsonDocument.Parse(sequence, s_options))
    {
        JsonElement target = doc.RootElement[0];
        var writer = new Utf8JsonWriter(buffer);

        Assert.Throws<ArgumentException>(() => target.WriteValue(writer));
    }
}

[Fact]
public static void WriteValueBytesWithInvalidSurrogatesShouldThrow()
{
    char[] chars = new char[] { '[', '"', (char)0xDC00, (char)0xD800, (char)0xD803, '"', ']' };
    var buffer = new ArrayBufferWriter<byte>(128);
    byte[] temp = Encoding.UTF8.GetBytes(chars);

    using (JsonDocument doc = JsonDocument.Parse(temp, s_options))
    {
        JsonElement target = doc.RootElement[0];
        var writer = new Utf8JsonWriter(buffer);
        target.WriteValue(writer);

        Assert.Throws<ArgumentException>(() => target.WriteValue(writer));
    }
}
```

**Comment by mburbea** [comment]
+uFFFD is the invalid character replacement symbol  `�`. Invalid UTF sequences should either be an error or correctly return the character replacement symbol.

**Comment by buyaa-n** [comment]
Good point, not sure how valid to replace all chars, 1st pair is valid surrogate pair. 

Anyways I assume it should throw as Utf8JsonWriter is throwing in this case

**Comment by ericstj** [comment]
@steveharter do you think this will change with your escaping work?

**Comment by steveharter** [comment]
I believe the semantics will be the same for this particular case -- the replacement character will be written and no exception will be thrown. I've noticed that in a few places where we throw today, the JavaScriptEncoder will write the replacement characters. I haven't yet hooked up the writer completely so I can't tell yet by the tests, but I believe an unpaired surrogate located at the end of the buffer should throw.

cc @GrabYourPitchforks

**Comment by steveharter** [comment]
@buyaa-n per @GrabYourPitchforks "System.Text.Encoding.Web performs U+FFFD replacement because that's what the normal UTF-16 Encode API does, so the symmetry is nice. If you have a need to introduce an overload that fails on ill-formed data feel free, but the default overload should be to perform silent replacement like the UTF-16 version does."

**Comment by steveharter** [comment]
@ahsonkhan I assume `JsonWriterOptions.SkipValidation` should have no effect on whether the replacement character is used or not.

**Comment by steveharter** [comment]
@buyaa-n I am assigning this back to you to close or modify the tests. The tests should be written to assume the replacement character. With the implementation of https://github.com/dotnet/corefx/pull/39524 complete, System.Text.Json no longer does it's own escaping except for trivial ascii scenarios - instead it calls `System.Text.Encoding.Web.JavaScriptEncoder` to do that.

It is still possible to get an exception however - see the code and documentation at https://github.com/dotnet/corefx/blob/9b486c1ea7bcfe7d09206ae449bffb049754ade5/src/System.Text.Encodings.Web/src/System/Text/Unicode/UnicodeHelpers.cs#L118

**Comment by buyaa-n** [comment]
From previous comments I understood that U+FFFD replacement is valid and either it should replace or throw. The reason i kept it open is because Utf8JsonWriter is throwing in this case but JsonElement writer replacing, assuming they should behave same. Anyways if you guys thinking its fine am closing it
