### ISSUE TITLE
System.Native not compatible with macOS 10.12

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/corefx#39394]
System.Native references the utimensat API that was only introduced in macOS 10.13.

https://github.com/dotnet/BenchmarkDotNet/issues/1195#issuecomment-510549672

There's also:

```
         _SystemNative_SysLog in System.Native.a(pal_process.c.o)
     "_syslog$DARWIN_EXTSN", referenced from:
```

Which is probably in the same bucket.

Note that this was found in CoreRT, but I don't have a reason to doubt this is a problem for CoreCLR as well.

**Comment by jkoritzinsky** [comment]
CoreFX should add this block (from CoreCLR) into their CMake configuration files to set the minimum MacOS version they need to support:

https://github.com/dotnet/coreclr/blob/eff4feaa164ea7b6644fa7fb37f8238184de4cbc/configurecompiler.cmake#L527-L533

**Comment by ViktorHofer** [comment]
Am I missing something here? We don't support macOS <= 10.13

**Comment by danmosemsft** [comment]
@leecow

**Comment by jkoritzinsky** [comment]
I thought we still supported macOS 10.12, but it looks like my info is out of date. In any case, that CMake block (updated to 10.13) would allow CoreFX to build on a newer macOS version without having to worry about targeting issues (so things won't break when the macOS version of the build machines changes).

**Comment by ViktorHofer** [comment]
cc @safern as he has more knowledge on that

**Comment by MichalStrehovsky** [comment]
https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md#macos

Looks like it's 10.13+.

We can close. Sorry for confusion.
