### ISSUE TITLE
Several network tests fail on Debian 10 with authentication error

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#39401]
We want to get down to zero test failures on rolling builds for 3.0. Looking at the rolling builds results we currently have 64 test failures. Most of them are authentication errors on Debian 10.

https://dnceng.visualstudio.com/public/_build/results?buildId=260574&view=ms.vss-test-web.build-test-results-tab

cc @wfurt @davidsh @stephentoub

**Comment by davidsh** [comment]
Isn't this the same as #38444?

**Comment by ViktorHofer** [comment]
Right, closing as dupe of https://github.com/dotnet/corefx/issues/38444
