### ISSUE TITLE
Add a JsonAttribute to allow null-value handling on a per-property basis

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#39416]
The ask is for an attribute that does the equivalent of `JsonSerializerOptions.IgnoreNullValues` on a per property basis.

**Comment by stephentoub** [comment]
I'm marking this as Future.  If that's not correct, please add more details.

**Comment by layomia** [comment]
Closing as a duplicate of https://github.com/dotnet/corefx/issues/40600 which discusses conditional igoring on a per-property basis.
