### ISSUE TITLE
Set AssemblyInfomationalVersion to package version

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#3942]
It would make tracking down builds so much easier.

/cc @ericstj

**Comment by davidsh** [comment]
+1

**Comment by davidfowl** [comment]
While you're at it add the commit sha as well using AssemblyMetadata

**Comment by ericstj** [comment]
It's actually not package version you want.  That is just the same as the assembly version (prior to the generations work).  I think you want the pre-release string and the branch.  Commit SHA is already something @chcosta is looking at adding to the package.  Perhaps we can add it to the binaries as well.

**Comment by danmosemsft** [comment]
@chcosta are you planning on doing this for 2.0 release?

**Comment by mellinoe** [comment]
We do have the commit SHA in an `[AssemblyVersionAttribute]`, so I think that's good enough? We've had it for a long time; we probably just never closed this.

**Comment by danmosemsft** [comment]
@davidfowl the AssemblyVersionAttriute seems fine to me -- OK to close?

**Comment by weshaggard** [comment]
Yes I think that is good enough. Closing.
