### ISSUE TITLE
Behavior differences between fileInfo and reading length

### ISSUE THREAD

**Issue by foxjazz** [dotnet/corefx#39422]
[RepoSteps](https://github.com/evetoolsblue/WritingShared)
Tested on Windows 10

**Comment by mikedn** [comment]
At least on NTFS, `FileInfo` contains the file length from the file's directory entry. That length is usually only updated when the file is closed and so it may contain stale information if you keep the stream opened.

**Comment by foxjazz** [comment]
It Looks like for clarity, FileInfo and Read.Length only sync up after a flush.
