### ISSUE TITLE
Process.StartTime on macOS returns different values

### ISSUE THREAD

**Issue by mdolan92869** [dotnet/corefx#39434]
When getting the StartTime for a process, each time it's called for a new instance of the same process, it has a different value. I believe that the issue is in StartTimeCore where the native "now" time is retrieved, a bunch of arithmetic is performed, then the C# "now" time is retrieved. Since operations were between the two "now" calls, the "now" values will obviously be different, but they're used as if they're the same. I've attached a sample program that will show the deltas between StartTime accesses.

System: macOS 10.14.5 Mojave

[ProcessStartTime.zip](https://github.com/dotnet/corefx/files/3387833/ProcessStartTime.zip)

**Comment by mdolan92869** [comment]
In the attached code, the PID I was using was for Microsoft Outlook on my laptop. It was launched one time, but the StartTime drifted and no 2 consecutive calls got the same value.

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/blob/ef25246c7ea01a96cda8a464b4b717213e8d9685/src/System.Diagnostics.Process/src/System/Diagnostics/Process.OSX.cs#L53-L60

@mdolan92869 perhaps you'd like to attempt a fix?

**Comment by jpfreyen** [comment]
@danmosemsft    I'm reading this and I am concerned that there is a similar issue in Linux not being addressed by just fixing Process.OSX.cs

**Comment by danmosemsft** [comment]
We likely won't have time to look at this for a a little while, so if either of you feel motivated to work on PR(s) that would be welcome.

**Comment by watfordgnf** [comment]
I've been away from OS X programming for some time (and my MBP is too old to run .NET Core), but would `proc_bsdinfo.pbi_start_tvsec` be a good start? `Interop.libproc.GetProcessInfoById` already has a call which retrieves it within `proc_taskallinfo.pbsd`. https://github.com/dotnet/corefx/blob/f7539b726c4bc2385b7f49e5751c1cff2f2c7368/src/Common/src/Interop/OSX/Interop.libproc.cs#L310-L323

Untested:
```csharp
        /// <summary>Gets the time the associated process was started.</summary>
        private int StartTimeCore
        {
            get
            {
                EnsureState(State.HaveNonExitedId);
                Interop.libproc.proc_taskallinfo? info = Interop.libproc.GetProcessInfoById(Id);

                if (info == null)
                    throw new Win32Exception(SR.ProcessInformationUnavailable);

                // ignores microseconds
                return DateTime.UnixEpoch + TimeSpan.FromSeconds(info.pbsd.pbi_start_tvsec));
            }
        }
```

**Comment by watfordgnf** [comment]
@mdolan92869 I've put up a branch which attempts a fix if you can test (my MBP cannot run .NET Core).

@jpfreyen it looks like the Linux code falls back on UtcNow if it can't read the boot time from `/proc/stat`. It would be nice if `/proc/{pid}/psinfo` was available on *nix, as its start time is relative to the epoch rather than ticks since boot.

**Comment by jpfreyen** [comment]
@watforgnf I would agree, pbi_start_tvsec/pbi_start_tvusec would be a good place to start for macOS.

And @watfordgnf do you mean /proc/{pid}/stat instead of /proc/stat?

**Comment by watfordgnf** [comment]
It pulls `starttime` from `/proc/{pid}/stat`, which is in ticks since boot. Boot time is then pulled from `/proc/stat`. It falls back to adding `starttime` to `DateTime.UtcNow` in the event `/proc/stat` parsing fails (for whatever reason).

**Comment by watfordgnf** [comment]
I've opened draft PR #39572 to discuss a possible implementation.

**Comment by jpfreyen** [comment]
Thanks for the fix @watfordgnf; I can't help test, my work environment is totally not setup to build .NETCore code changes and try them.
