### ISSUE TITLE
Mark Microsoft.Bcl.AsyncInterfaces & Microsoft.Bcl.HashCode as stable in Preview 8

### ISSUE THREAD

**Issue by terrajobst** [dotnet/corefx#39439]
We have received requests that people would like to ship packages on top of these. Given that

1. They are done.
2. They are for .NET Standard 2.0 (rather than .NET Core 3.0) earlier is better than later.

/cc @ericstj @wtgodbe

**Comment by jkotas** [comment]
To avoid mistakes with shipping similar packages in the past, we have said that we are not going to ship these packages before the platform piece that carries the inbox implementation ships. What makes us believe that we will get it right this time?

**Comment by danmosemsft** [comment]
cc @KrzysztofCwalina for update on his schedule.

**Comment by ericstj** [comment]
We've done a few of these recently.  System.Numerics.Tensors, Microsoft.IO.Redist, Microsoft.Diagnostics.Tracing.EventSource.Redist.  I'm not aware of any issues that fell out of one-off releases of these but others can chime in if they think this is a bad idea.

**Comment by jkotas** [comment]
>  System.Numerics.Tensors, Microsoft.IO.Redist, Microsoft.Diagnostics.Tracing.EventSource.Redist

None of these are duplicating the inbox APIs with the same identity. They have independent identity and just happens to be sharing some sources with .NET Core.

I am talking about System.ValueTuple and similar packages we have done in the past.

**Comment by ericstj** [comment]
In this case we aren't shipping the same identity, these are different assembly identities, does that mitigate your concern?  Are you worried we'll need to change this API before we ship it?

**Comment by jkotas** [comment]
`Microsoft.Bcl.AsyncInterfaces` & `Microsoft.Bcl.HashCode` packages contain netcoreapp3.0 / netstandard2.1 assets. If we mark them stable before netcoreapp3.0 / netstandard2.1 is marked stable, we would end up with stable part depending on not yet stable part.

**Comment by ericstj** [comment]
Not literally depending on it in a way that would break anything, but yes they would depend on the location and surface area that we eventually ship.  That would prevent us from moving the types or changing the API.  My understanding is that @terrajobst was agreeing not to do that.

**Comment by benaadams** [comment]
Any reason they are `Microsoft.Bcl.` rather than `System.`?

**Comment by ericstj** [comment]
@joperezr can you prep the PRs for this in release?  One PR that marks them stable, then a PR after that that bumps the versions.  /cc @wtgodbe

**Comment by joperezr** [comment]
talked offline, seems like partner teams don't really require for us to do this any longer so our current plan is to not do anything and just let these packages ship with the rest of 3.0 release.
