### ISSUE TITLE
DangerousAcceptAnyServerCertificateValidator delegated not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by olandese** [dotnet/corefx#39435]
# Issue Title

DangerousAcceptAnyServerCertificateValidator is ignored on Ubuntu 18.04 with .Net Core 2.2.301

# General
I'm using the HttpClient and the DangerousAcceptAnyServerCertificateValidator delegate in the HttpClientHandler but calling rest api with self-signed cerificate generated from a self-signed root certificate, I get the following error: 

Error Message:
   System.Threading.Tasks.TaskCanceledException : The operation was canceled.
  Stack Trace:
     at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)

For more information see my blog post https://blog.olandese.nl/2019/07/12/solve-system-threading-tasks-taskcanceledexception-the-operation-was-canceled-on-ubuntu-18-04-in-net-core-2-2/

**Comment by davidsh** [comment]
@olandese Can you please attach the test certificate to this issue so that we can attempt to repro the problem?

There is an interesting issue on Linux where self-signed certificates will NOT work at all because Linux requires the certificate to have additional X509v3 fields set that Windows doesn't require. This is a limitation of Linux and OpenSsl and not related to .NET Core. So, it's quite possible that exporting a self-signed certificate that works on Windows will not work on Linux.

The extra field required on the self-signed certificate is about having the "Cert signing" attribute set on the KeyUsage field.

The specific exception you're getting "The operation was canceled" is probably masking the real problem with the certificate.

Can you try to re-generate a self-signed certificate on Linux directly so that it meets the requirements for Linux?

**Comment by davidsh** [comment]
Please see https://github.com/dotnet/corefx/issues/37282#issuecomment-488132215 for more info.

**Comment by olandese** [comment]
sure, in which format you want them? the root and the actual certificate

**Comment by davidsh** [comment]
>sure, in which format you want them? the root and the actual certificate

Based on the issue description, it was assumed there was a *single* self-signed certificate in use:
>but calling rest api with self-signed cerificate I get the following error

But there is actually two certificates in use? A root and a certificate derived from that? So, is the "root" certificate untrusted in some way?

Can you provide a complete repro for this?  For example, a runnable project that we can do an "dotnet run" on reproduce this problem?  Also, are you using Ubuntu as a VM or docker image?

**Comment by davidsh** [comment]
And looking at your images of the certificates you provided, I'm wondering whether the use of SHA1 could be a problem on Linux.  SHA256 is recommended as the minimum for certificates.

**Comment by olandese** [comment]
Thank you for your feedback! I will ask to upgrade the encryption algorithm. But anyway, the delegate should suppress all of this "dangerous" things, I would assume. 
The rest api is talking with a certificate derive from a self-signed root certificate. 
As soon I put the root certiicate in the /usr/local/share/ca-certificates/ everything works fine. 
I can provide you the sources, but it;s nothing more than I already wrote in the blog post

**Comment by davidsh** [comment]
In terms of your scenario, are you running both a client and a server?  What "server" is sending back that certificate?

The problem you're seeing could be a variety of issues. The only real way to diagnose this is a repro we can run that reproduces the problem. And the description from the blog article isn't specific enough for us to construct a run-able repro.

Other customers in the past have been able to use Docker, for example, to provide a fully run-able repro program that can build and run and demonstrate problems that they report here.

**Comment by olandese** [comment]
the derived certificate is running on an Azure API Management. 
I will create and provide you a repo, or docker image to reproduce this behaviour

**Comment by bartonjs** [comment]
> And looking at your images of the certificates you provided, I'm wondering whether the use of SHA1 could be a problem on Linux. 

The SHA1 in the images is "thumbprint algorithm".  It's not a real attribute of the certificate, just explaining that the thumbprint is computed using SHA-1, which is true for all certificates.  (It's just a CertUI oddity)

**Comment by davidsh** [comment]
>I will create and provide you a repo, or docker image to reproduce this behaviour

@olandese Please let us know when/if you will be able to create a repo for this issue so that we can easily reproduce the behavior you see.

Also, please consider trying out .NET Core 3.0.  Latest preview:
https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-9/
