### ISSUE TITLE
Need tests for JsonSerializerOptions.GetConverter

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#39457]
We should test that `GetConverter` on a default `JsonSerializerOptions` always returns expected converters for given types. (Even though they are mostly currently internal, we should always get the bool converter for bool, etc.)

In addition to validating that we get the expected converter, we should add tests to ensure they don't try to dereference options sent to the `Read`/`Write`/`GetConverter` methods. (I.e. get the converter, then call it's methods with a null `JsonSerializerOptions`.)

cc: @steveharter

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/dotnet/corefx/pull/39750 (master) and https://github.com/dotnet/corefx/pull/40381 (release/3.0)
