### ISSUE TITLE
HTTP2: Receiving RST_STREAM from server does not interrupt request body send

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#39458]
If you do a POST and send request content, and the server sends a RST_STREAM, we continue to allow writes on the request body stream, and in fact we keep sending DATA frames to the server.

Instead, we should fail the next attempted write on the request stream and not send any more DATA frames to the server.

I'm working on a PR to add a test for this.

**Comment by JamesNK** [comment]
See https://github.com/dotnet/corefx/issues/39582 for a hang caused by this issue in gRPC.

**Comment by geoffkizer** [comment]
Fixed by #39638

**Comment by karelz** [comment]
Fixed in master (5.0) in PR #39638 and also in release/3.0 branch (3.0) in PR #39775.
