### ISSUE TITLE
HTTP2: Exception during request body send does not send a RST_STREAM to the server

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#39459]
If an exception occurs while sending the request body (i.e. HttpContent.SerializeToStreamAsync), we do not send a RST_STREAM to the server. We should.

I'm working on a PR to add a test for this.

**Comment by karelz** [comment]
Fixed in master (5.0) in PR #39638 and also in release/3.0 branch (3.0) in PR #39775.
