### ISSUE TITLE
HTTP2 Duplex: Receiving non-success status code does not allow response body to be read

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#39460]
When we receive a non-success status code (e.g. 403), we stop sending the request body. However, we also immediately send a RST_STREAM, which causes the server to stop sending the response body if it hasn't finished already. This means the client cannot reliably read the response body. (Note this works for HTTP/1.1, though we only do this when Expect: 100-continue is used; for HTTP2 we always do it.)

We should simply stop sending the request body and defer the RST_STREAM until the response body has been fully read.

**Comment by karelz** [comment]
Fixed in master (5.0) in PR #39638 and also in release/3.0 branch (3.0) in PR #39775.
