### ISSUE TITLE
HTTP2: Dispose on response stream before stream is fully consumed does not remove stream from the stream dictionary

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#39461]
If you dispose the response stream before consuming all the data, we do not remove the Http2Stream from the connection's stream dictionary. This means that the connection still thinks the Http2Stream is open, and the connection will never go away.

**Comment by geoffkizer** [comment]
This also means the stream continues to count against the max streams limit, which is why we are seeing the stress test stop processing requests when you do this.

**Comment by davidfowl** [comment]
Ahh I was trying to figure out if this was a sever bug.

**Comment by karelz** [comment]
Fixed in master (5.0) in PR #39638 and also in release/3.0 branch (3.0) in PR #39775.
