### ISSUE TITLE
Incorrect connection window handling for response Stream.Read?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#39470]
PR https://github.com/dotnet/corefx/pull/38918 removed `_connection.ExtendWindow(bytesRead);` from the response stream's ReadAsync:
https://github.com/dotnet/corefx/blob/c14b80faff694bae4e085bad221e2e83410e5f33/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs#L649-L652
but didn't remove it from Read:
https://github.com/dotnet/corefx/blob/c14b80faff694bae4e085bad221e2e83410e5f33/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs#L624-L628
I assume that's a bug that needs to be fixed in Read by removing the corresponding line?

cc: @geoffkizer

**Comment by geoffkizer** [comment]
> I assume that's a bug that needs to be fixed in Read by removing the corresponding line?

Yep, sorry for the oversight. Thanks for catching this.
