### ISSUE TITLE
HTTP2: Race to abort 

### ISSUE THREAD

**Issue by scalablecory** [dotnet/corefx#39486]
Here we call `AbortStreams` with an exception that may not be the one captured in `_abortException`.

https://github.com/dotnet/corefx/blob/bbbcac59ac07f344ce4e257ef182a90c429d2b58/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L1275-L1282

**Comment by krwq** [comment]
I'm wondering if we should call it at all - presumably we've already called it if _abortException is not null

**Comment by davidsh** [comment]
@geoffkizer @stephentoub
