### ISSUE TITLE
System.Text.Json Issue with System.Reflection.Emit.Lightweight

### ISSUE THREAD

**Issue by devhl-labs** [dotnet/corefx#39502]
When trying to use System.Text.Json v4.6.0-preview8.19365.3 I get the following error:

Could not load file or assembly 'Systrem.Reflection.Emit.Lightweight, Version=4.1.0.0

I don't see that version number in nuget.  What can I do to get the latest Text.Json working?

**Comment by steveharter** [comment]
@realdevhl what platform are you on?

**Comment by realdevhl** [comment]
Vs 19 preview

**Comment by steveharter** [comment]
Is this a .NET Core or .NET Framework project? And the project type? Thanks

**Comment by realdevhl** [comment]
Its a class library.  I did it in standard and then core to see if it
carried over.

**Comment by ahsonkhan** [comment]
@realdevhl, can you please share a sample repro with your csproj itself?

cc @joperezr

**Comment by ericstj** [comment]
.NETStandard doesn't apply to "loading", please let us know what target framework and version you are running this code on.  I'm guessing you didn't reference System.Text.Json package in the application itself.  The System.Text.Json package depends on other packages which will carry framework specific implementation assemblies.

**Comment by realdevhl** [comment]
[my repo](https://github.com/realdevhl/CocApi)

I have a library in Core 3.0 and the same library in Standard 2.1.    I have added using System.Text.Json in the libraries.  When I run Deserialize it gives me the error in either library.

**Comment by ericstj** [comment]
Your repo built and the program ran successfully for me.  I noticed a bunch of unnecessary references which can be removed, but I couldn't reproduce the ref.emit issue even after removing all these.
```diff
index 5ac3704..7336aa0 100644
--- a/CocApiCoreLibrary/CocApiCoreLibrary.csproj
+++ b/CocApiCoreLibrary/CocApiCoreLibrary.csproj
@@ -8,7 +8,6 @@
   </PropertyGroup>

   <ItemGroup>
-    <PackageReference Include="System.Reflection.Emit.Lightweight" Version="4.6.0-preview8.19365.2" />
     <PackageReference Include="System.Text.Json" Version="4.6.0-preview8.19365.2" />
   </ItemGroup>

diff --git a/CocApiLibrary/CocApiLibrary.csproj b/CocApiLibrary/CocApiLibrary.csproj
index 55fc8f5..f6e7b73 100644
--- a/CocApiLibrary/CocApiLibrary.csproj
+++ b/CocApiLibrary/CocApiLibrary.csproj
@@ -12,9 +12,6 @@
   </PropertyGroup>

   <ItemGroup>
-    <PackageReference Include="System.Net.Http" Version="4.3.4" />
-    <PackageReference Include="System.Net.Requests" Version="4.3.0" />
-    <PackageReference Include="System.Reflection.Emit.Lightweight" Version="4.0.1" />
     <PackageReference Include="System.Text.Json" Version="4.6.0-preview8.19365.2" />
   </ItemGroup>
```

What SDK version are you using?  Can you shared dotnet --info?

**Comment by devhl-labs** [comment]
```
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by devhl-labs** [comment]
This only happens when using the latest version from https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json

**Comment by ericstj** [comment]
I see, this is happening because you're mixing/matching builds.  You're using the preview8 Json package on the preview6 shared framework.  It's broken because https://github.com/dotnet/corefx/commit/ab58ff6e649852b85fdb99b15992a2fa3a7d8834#diff-17b8c81ffa387b6afeb9ca0d9b67fd1bR4 bumped the version of Ref.Emit since API was added.

Most of the time this is OK, but when we move types or bump assembly versions like we did here it will break.

If you want to use the latest package you should use  a newer SDK / shared framework.  You can get that by installing from https://github.com/dotnet/core-sdk
