### ISSUE TITLE
Add more tests that write various large sizes of JSON using JsonSerializer.Serialize(Async)

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#39500]
From https://github.com/dotnet/corefx/pull/39417#issuecomment-510919567

We should add more tests to verify that serializing (outputting) large JSON works as expected. It would be good to add test sizes around 4, 8, 12, 16k (particularly 12/16k as they are currently special sizes for SerializeAsync), and also some larger payloads above 85k. It would also be good to add tests where depth changes at those size threshold (for example, writing a start or end array/object at the 16k bytes).

More context: https://github.com/dotnet/corefx/pull/39417#discussion_r303064061

> The default threshold is 75% of the default buffer size (16K) so 12K. However it really determines what is returned from the array pool. 

cc @steveharter, @buyaa-n, @layomia

**Comment by buyaa-n** [comment]
@ahsonkhan @ericstj @steveharter @layomia please take a look test I've created and please give some feedback for improvement https://github.com/buyaa-n/corefx/pull/3/files

**Comment by buyaa-n** [comment]
Fixed with #39668
