### ISSUE TITLE
DefaultTraceListener should not hold lock while displaying UI

### ISSUE THREAD

**Issue by AArnott** [dotnet/corefx#39515]
In .NET Framework, `Debug.Fail` pops a modal assertion failure dialog box that holds a static lock object in the System.Diagnostics tracing system for the duration of the dialog's lifetime.
Because this lock is also acquired for every traced message, other threads get blocked while the modal dialog is displayed. 
This can quickly devolve into deadlocks. For .NET Framework this bug was Won't Fixed because fixing it was deemed too risky.

Given .NET Core 3.0 is adding the assertion failed dialog, can we please make sure that it does not hold a trace lock while it is visible so we don't repeat this mistake?

**Comment by stephentoub** [comment]
Apparently it's not happening for 3.0:
https://github.com/dotnet/coreclr/issues/20973#issuecomment-511621308
cc: @jkotas
