### ISSUE TITLE
Unix AES in-place decryption returns incorrect answers

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#3952]
There was a specific test, VerifyInPlaceEncryption, that passed.

Another test, TransformStateSeparation, was marked as failing due to #1965.  #1965 is fixed locally (it was a test bug), but TransformStateSeparation continues to fail.  Investigation showed that the problem went away without using in-place decryption.

So now TransformStateSeparation uses distinct buffers for input and output, and a new test, VerifyInPlaceDecryption, tracks this new failure.

**Comment by AtsushiKan** [comment]
No longer repros - reenabled test.
