### ISSUE TITLE
Slower performance with multidimensional array vs array-of-arrays

### ISSUE THREAD

**Issue by Turnerj** [dotnet/corefx#39525]
I'm working on [a benchmark for some text edit comparisons](https://github.com/Turnerj/TextDifferenceBenchmarking) and had noticed something strange when looking at micro-optimisations of the code.

The baseline creation of the array-of-arrays ([file](https://github.com/Turnerj/TextDifferenceBenchmarking/blob/master/TextDifferenceBenchmarking/DiffEngines/DmitryBychenko.cs)):
```csharp
// Best operation (among insert, update, delete) to perform 
EditOperationKind[][] M = Enumerable
	.Range(0, source.Length + 1)
	.Select(line => new EditOperationKind[target.Length + 1])
	.ToArray();

// Minimum cost so far
int[][] D = Enumerable
	.Range(0, source.Length + 1)
	.Select(line => new int[target.Length + 1])
	.ToArray();
```

The multidimensional "optimised" version ([file](https://github.com/Turnerj/TextDifferenceBenchmarking/blob/master/TextDifferenceBenchmarking/DiffEngines/DmitryMultiDimension.cs)):
```csharp
// Best operation (among insert, update, delete) to perform 
var M = new EditOperationKind[source.Length + 1, target.Length + 1];

// Minimum cost so far
var D = new int[source.Length + 1, target.Length + 1];
```

With just this change (and changes to actually reading from the array from `D[x][y]` to `D[x,y]`), this was the benchmark results.

```
BenchmarkDotNet=v0.11.5, OS=Windows 10.0.17134.885 (1803/April2018Update/Redstone4)
Intel Core i7-6700HQ CPU 2.60GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
Frequency=2531252 Hz, Resolution=395.0614 ns, Timer=TSC
.NET Core SDK=3.0.100-preview5-011568
  [Host] : .NET Core 3.0.0-preview5-27626-15 (CoreCLR 4.6.27622.75, CoreFX 4.700.19.22408), 64bit RyuJIT
  Core   : .NET Core 3.0.0-preview5-27626-15 (CoreCLR 4.6.27622.75, CoreFX 4.700.19.22408), 64bit RyuJIT
```

|               Method |  N |         Mean |      Error |     StdDev |       Median |          Max | Ratio | RatioSD |    Gen 0 |    Gen 1 |    Gen 2 | Allocated |
|--------------------- |--- |-------------:|-----------:|-----------:|-------------:|-------------:|------:|--------:|---------:|---------:|---------:|----------:|
|       DmitryBychenko |  1 |     1.549 us |  0.0295 us |  0.0290 us |     1.537 us |     1.626 us |  1.00 |    0.00 |   0.6657 |        - |        - |    2088 B |
| DmitryMultiDimension |  1 |     1.204 us |  0.0066 us |  0.0062 us |     1.205 us |     1.217 us |  0.78 |    0.01 |   0.3128 |        - |        - |     984 B |
|                      |    |              |            |            |              |              |       |         |          |          |          |           |
|       DmitryBychenko |  2 |     3.949 us |  0.0445 us |  0.0416 us |     3.933 us |     4.017 us |  1.00 |    0.00 |   1.4496 |        - |        - |    4552 B |
| DmitryMultiDimension |  2 |     3.923 us |  0.0285 us |  0.0266 us |     3.919 us |     3.977 us |  0.99 |    0.01 |   0.8774 |        - |        - |    2760 B |
|                      |    |              |            |            |              |              |       |         |          |          |          |           |
|       DmitryBychenko |  4 |    12.390 us |  0.0668 us |  0.0625 us |    12.396 us |    12.481 us |  1.00 |    0.00 |   4.0436 |        - |        - |   12696 B |
| DmitryMultiDimension |  4 |    14.707 us |  0.0830 us |  0.0736 us |    14.718 us |    14.832 us |  1.19 |    0.01 |   2.9602 |        - |        - |    9320 B |
|                      |    |              |            |            |              |              |       |         |          |          |          |           |
|       DmitryBychenko |  8 |    42.991 us |  0.1972 us |  0.1845 us |    42.968 us |    43.252 us |  1.00 |    0.00 |  13.0005 |        - |        - |   40816 B |
| DmitryMultiDimension |  8 |    55.383 us |  0.2227 us |  0.2084 us |    55.334 us |    55.721 us |  1.29 |    0.01 |  10.9253 |        - |        - |   34440 B |
|                      |    |              |            |            |              |              |       |         |          |          |          |           |
|       DmitryBychenko | 16 |   160.081 us |  1.0725 us |  1.0033 us |   160.287 us |   161.536 us |  1.00 |    0.00 |  45.6543 |   1.7090 |        - |  145056 B |
| DmitryMultiDimension | 16 |   253.966 us |  1.7243 us |  1.5286 us |   253.481 us |   256.969 us |  1.59 |    0.01 |  32.2266 |  32.2266 |  32.2266 |  132680 B |
|                      |    |              |            |            |              |              |       |         |          |          |          |           |
|       DmitryBychenko | 32 |   677.476 us |  2.4517 us |  2.2933 us |   677.440 us |   682.216 us |  1.00 |    0.00 | 108.3984 |  53.7109 |        - |  545536 B |
| DmitryMultiDimension | 32 |   940.128 us |  3.7499 us |  3.3242 us |   940.912 us |   945.401 us |  1.39 |    0.01 | 153.3203 | 153.3203 | 153.3203 |  521160 B |
|                      |    |              |            |            |              |              |       |         |          |          |          |           |
|       DmitryBychenko | 64 | 2,633.051 us | 14.9213 us | 13.2274 us | 2,629.797 us | 2,658.248 us |  1.00 |    0.00 | 343.7500 | 171.8750 |        - | 2114496 B |
| DmitryMultiDimension | 64 | 3,978.057 us | 35.7731 us | 33.4622 us | 3,968.022 us | 4,045.105 us |  1.51 |    0.02 | 492.1875 | 492.1875 | 492.1875 | 2066120 B |

In (N=1, N=2), I figure the multidimensional array is faster due to not calling the `Enumerable` methods to create the array-of-arrays and similarly think that is why the allocations are lower. I am confused though how when (N=16), it leads to a Gen2 increase in memory over the array-of-arrays.

With (N=64), the ratio between these blows up to 1.51 purely from using `[,]` over `[][]`. Is there something I'm missing about the differences between the two types of multidimensional arrays and how they are handled?

**Comment by Turnerj** [comment]
I will also note that I replicated this in .NET Framework as well with about the same values.

**Comment by Turnerj** [comment]
So I didn't know this originally but apparently it might be well known that [multidimensional arrays are slower than jagged arrays](https://stackoverflow.com/a/597729/1676444).

**Comment by stephentoub** [comment]
Thanks. But yes, this has always been the case. Code that needs high performance is generally written to prefer jagged.

**Comment by Turnerj** [comment]
With jagged and multidimensional arrays being very similar in terms of usage (though jagged allowing arrays of different sizes at each level) and multidimensional arrays being a language feature, is it worthwhile trying to improve the performance of multidimensional arrays? Could the compiler internally treat multidimensional internally as jagged?

Otherwise with their similarities and multidimensional being so much slower (and using more memory, especially Gen2) after X size, I would nearly think multidimensional arrays would be best deprecated from the language. I know that is a whole separate thing and extremely unlikely to happen, just it seems strange to have first-party language support for something where the language-agnostic way (jagged) just performs vastly better.
