### ISSUE TITLE
PipeReader.ReadAsync never completes after cancellation when stepping in debugger with visible Locals window

### ISSUE THREAD

**Issue by AArnott** [dotnet/corefx#39536]
It seems that the debugger inspecting properties on the PipeReader causes the PipeReader to enter a bad state leading to hangs. Consider this example:

```cs
var pipe = new Pipe();

var pendingRead = pipe.Reader.ReadAsync();
pipe.Reader.CancelPendingRead();
var readResult = await pendingRead;
```

When run in a .NET Core 2.2 console application without stepping, this completes successfully.
When stepping in the debugger with no visible watch/locals/auto window this also completes successfully.
**But** when stepping in the debugger with the Locals window visible, it hangs on the last line.

This worked properly in all cases for System.IO.Pipelines 4.5.3.
This regressed behavior shows up in 4.6.0-preview6.19303.8.

**Comment by stephentoub** [comment]
Taking a quick look, I'm guessing the problem here is `ValueTask<T>.Result`, it getting evaluated by the Locals window prior to the await, and that invalidating the underlying IValueTaskSource for the await.  Or something like that.

**Comment by AArnott** [comment]
That makes sense. Also while investigating this I got an odd exception around concurrent reading even though the code only had one readasync method and it had only executed once. I suspect this too was because a debugger locals window was open and caused the PipeReader to think there were multiple calls.

**Comment by davidfowl** [comment]
Man I ran into this and didn't even know it 😄

**Comment by stephentoub** [comment]
I'm actually surprised to hear it didn't repro on .NET Core 2.2.
