### ISSUE TITLE
System.Reflection.Emit & System.Reflection.Emit.Lightweight 4.6.0 depend on System.Reflection.Emit.ILGeneration 4.3.0 but should be 4.6.0

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/corefx#39542]
[System.Reflection.Emit 4.6.0-preview6.19303.8](https://www.nuget.org/packages/System.Reflection.Emit/4.6.0-preview6.19303.8) and [System.Reflection.Emit.Lightweight 4.6.0-preview6.19303.8](https://www.nuget.org/packages/System.Reflection.Emit.Lightweight/4.6.0-preview6.19303.8) both depend on `System.Reflection.Emit.ILGeneration (>= 4.3.0)` but this should be `System.Reflection.Emit.ILGeneration (>= 4.6.0-preview6.19303.8)` or a lot of netstandard1.x assemblies will be referenced by the application.

AFAIK, one of the reasons to update the packages was to add a netstandard2.0 target so those people who target netstandard2.0 and reference those nuget packages don't get any netstandard1.x files. See https://github.com/dotnet/corefx/issues/29365#issuecomment-398243215 and https://github.com/dotnet/corefx/issues/29365#issuecomment-398256178

**Comment by ericstj** [comment]
@joperezr can you double check that we set the baselineversion for this in the packageIndex?

**Comment by joperezr** [comment]
I sent out a PR for this. I have tested that both packages now produce the expected package dependency.

**Comment by joperezr** [comment]
Closed via #39605

**Comment by karelz** [comment]
@joperezr do we need similar change in master?

**Comment by joperezr** [comment]
> do we need similar change in master?

Nope we shouldn't need this in master. Every release we do a reset on the baseline versions all over the place, so in case it hasn't been fixed already it will happen soon for our setup for .NET 5.0.
