### ISSUE TITLE
Expose CancellationTokenSource.CreateLinkedTokenSource(CancellationToken)

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#39555]
We currently have two `CreateLinkedTokenSource` overloads:
```C#
public static CancellationTokenSource CreateLinkedTokenSource(CancellationToken token1, CancellationToken token2);
public static CancellationTokenSource CreateLinkedTokenSource(params CancellationToken[] tokens);
```

However, a fairly common scenario with `CreateLinkedTokenSource` is to use it to accept an externally provided token while also being able to cancel for internal reasons.  In such a case, you want to call:
```C#
public async Task SomeMethodAsync(CancellationToken cancellationToken)
{
    CancellationTokenSource cts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
    ...
}
```
This works, but it binds to the `params` overload.  To workaround that array allocation, if developers even realize they're incurring it, they can explicitly pass `default` or `CancellationToken.None`:
```C#
    CancellationTokenSource cts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, default);
```

**Proposal**
We already have this overload internally:
https://github.com/dotnet/corefx/blob/6ec67c15c3f213206e9cf66a2d69d274d3836e6b/src/Common/src/CoreLib/System/Threading/CancellationTokenSource.cs#L759
We should just make it public.

**Comment by Zenexer** [comment]
Our team would be using this quite a bit. We’ve gotten used to doing it manually, but this would make some rather confusing snippets of code much clearer. I’ve even made at least one ASP.NET fix proposal that would benefit from this change.

**Comment by GrabYourPitchforks** [comment]
Feedback: We discussed whether this would be necessary if we had a _params ROS\<T\>_ overload. But there's not even 100% consensus that we want to add that overload, and the proposal in this issue has merit on its own regardless.
