### ISSUE TITLE
Question: Has dynamic and emit execution performance been improved?

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/corefx#39565]
Today, I benchmark dynamic, emit, orgin, and reflect. I was surprised to find that their performance had been greatly improved. My last test results showed that there was still a big performance gap between native and dynamic invocations. I've been looking at the dynamic performance of. Net Core, and I haven't seen any of this in the relevant articles. My question is whether these test results are reliable and when was the performance improved?

Here is the result on different client:  

- **PC1 :**
![image](https://user-images.githubusercontent.com/16236903/61361332-eb7d1900-a8b2-11e9-932b-cd3d0f715d26.png)  

- **PC2 :**
![image](https://user-images.githubusercontent.com/16236903/61361504-2da65a80-a8b3-11e9-8255-0165c909f112.png)  

- **PC3 :**
![image](https://user-images.githubusercontent.com/16236903/61362456-cd181d00-a8b4-11e9-953d-07399867961c.png)

**Comment by mattwarren** [comment]
It'll be easier for people to comment on this issue if you post the full code to your benchmarks, either paste them into the issue or link to a gist or similar.

**Comment by NMSAzulX** [comment]
@mattwarren  OK . I have upload the code.  https://github.com/NMSAzulX/BechmarkReflector

**Comment by NMSAzulX** [comment]
Here is the major code.
```C#
        [Benchmark]
        public void Origin()
        {

            TestBechmark instance = new TestBechmark();
            instance.Name = "123456789";

        }

        [Benchmark]
        public void Dynamic()
        {
            TestBechmark instance = new TestBechmark();
            RunDynamic(instance);
        }

        [Benchmark]
        public void Reflect()
        {
            TestBechmark instance = new TestBechmark();
            NameInfo.SetValue(instance, "123456789");
        }

        [Benchmark]
        public void Emit()
        {
            TestBechmark instance = new TestBechmark();
            EmitSetString(instance, "123456789");
        }

        public void RunDynamic(dynamic instance)
        {
            instance.Name = "123456789";
        }
```

**Comment by danmosemsft** [comment]
cc @jkotas may know.

**Comment by danmosemsft** [comment]
@NMSAzulX  Benchmark.NET should be generating a markdown file for you that can be pasted into the Github issue. Easier to read and search than a screenshot. 😸

**Comment by jkotas** [comment]
The `dynamic` keyword runs a lot of code underneath, and so you will see improvements it its performance as the core capabilities (e.g. code quality or more primitive framework APIs) are improved.

Also, some of your benchmarks above are dominated by object allocation performance. They are not really testing `dynamic` or `Reflection.Emit`.

**Comment by NMSAzulX** [comment]
@jkotas  @danmosemsft Thank you!   :)
And @jkotas Is there any official code for dynamic performance testing? I want to learn it.

**Comment by jkotas** [comment]
https://github.com/dotnet/performance repo has all our performance microbenchmarks. I do not see any microbenchmarks for `dynamic` keyword there. If you would like to contribute some, PRs are welcomed.

**Comment by NMSAzulX** [comment]
@jkotas Thanks. OK.

**Comment by mattwarren** [comment]
> Is there any official code for dynamic performance testing? I want to learn it.

@NMSAzulX It's not code, but you might also want to have a read of [Microbenchmark Design Guidelines](https://github.com/dotnet/performance/blob/master/docs/microbenchmark-design-guidelines.md) that @adamsitnik just published.

**Comment by NMSAzulX** [comment]
@mattwarren  Thanks very much! :)
