### ISSUE TITLE
Disk space for Mac CI tests

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#3956]
All CI tests are failing with "There is not enough space on the disk." on dotnet_corefx_mac_release_prtest

**Comment by mmitche** [comment]
@tannergooding @joshfree @ellismg Anything change recently with the tests/build process?  I see a huge folder called RoslynTestDump in the TEMP dir which doesn't appear to be getting cleaned up, and a bunch of zip files called tmpXXXX containing a folder called .nuget.

**Comment by tannergooding** [comment]
Adding @jaredpar and @agocke, I don't believe it is anything new, but they should be getting cleaned up.

**Comment by jaredpar** [comment]
I don't know what that file is.

**Comment by joshfree** [comment]
Closing as this was resolved earlier today.  Thanks @mmitche for taking care of this!
