### ISSUE TITLE
FromBase64Transform.InputBlockSize = 1 instead of 4

### ISSUE THREAD

**Issue by gfoidl** [dotnet/corefx#39583]
https://github.com/dotnet/corefx/blob/ba2d62a24ea8574f40c43cd27cc384f079958a0c/src/System.Security.Cryptography.Encoding/src/System/Security/Cryptography/Base64Transforms.cs#L127

For base64 decoding 4 input bytes are transformed / decoded to 3 output bytes.
https://github.com/dotnet/corefx/blob/ba2d62a24ea8574f40c43cd27cc384f079958a0c/src/System.Security.Cryptography.Encoding/src/System/Security/Cryptography/Base64Transforms.cs#L123
So the `InputBlockSize` should be set to `4`, instead of `1`.

With `InputBlockSize` set to `1`, one byte at a time is read, fed to the transform, [buffered](https://github.com/dotnet/corefx/blob/ba2d62a24ea8574f40c43cd27cc384f079958a0c/src/System.Security.Cryptography.Encoding/src/System/Security/Cryptography/Base64Transforms.cs#L155-L163) there until at least 4 bytes are available to perform the actual base64 decoding.
So there are some avoidable reads (from the source / input) and method calls when the `InputBlockSize` is set to `4`, as it then matches the minimum required inputcout for base64.

The example in the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.frombase64transform.transformblock?view=netcore-3.0#System_Security_Cryptography_FromBase64Transform_TransformBlock_System_Byte___System_Int32_System_Int32_System_Byte___System_Int32_) explicitely uses `4` and has a comment `/*myTransform.InputBlockSize*/` (ref for [code-snippet](https://github.com/dotnet/samples/blob/ebcf07b4d7cdb59e4c3ebe6f467b0bf1059a3d78/snippets/csharp/VS_Snippets_CLR_System/system.Security.Cryptography.FromBase64Transform%20Example/CS/class1.cs#L116-L121) used in doc).

Further info for context: https://github.com/dotnet/corefx/pull/38062#discussion_r289034878

Note: this is not a correctness issue, as the transform can handle any input. It's more or less about perf and to align it with the base64 standard.

/CC: @bartonjs 

---

A potential fix is here https://github.com/gfoidl/corefx/commit/17702c5fcb101ae58097a98e4f213c9351dfbd50
If I should submit a PR, then I'll also update the snippet from the docs.

**Comment by bartonjs** [comment]
Once visible changes are being made, perhaps it also makes sense to set CanTransformMultipleBlocks to true, which means CryptoStream will pass it as much data as it has available (up to the block size) on each TransformBlock call (though that means it'll almost never use the stackalloc buffers).

**Comment by gfoidl** [comment]
> set CanTransformMultipleBlocks to true

I can look at this point, and see if it is benefitial.

> it'll almost never use the stackalloc buffers

But it will still be non-allocating, as the buffers will be rented from the array pool.

---

So this means I can submit a PR to address these points?

**Comment by bartonjs** [comment]
> So this means I can submit a PR to address these points?

Yep.

@ericstj This would be a "user visible runtime change" in 5.0... I thought you had made a tag that we can apply to the issues/PRs so we can make sure they all get documented... but I don't see one.  Am I not clever enough at my name guessing, or have we just not made it yet?

**Comment by ericstj** [comment]
It's 'breaking-change', and should be put on the PR if it is breaking in its merged form.

**Comment by gfoidl** [comment]
> it also makes sense to set CanTransformMultipleBlocks to true

`ToBase64Transform` could also be improved so that more than 3 bytes could be allowed, hence better perf with `CryptoStream` when `CanTransformMultipleBlocks = true` (but need to look deeper at it).
Is it worth to make a PR for this? (I would do this in a different PR than https://github.com/dotnet/corefx/pull/39599, as I assume that quite a lot of the code in this class needs to be changed.)
