### ISSUE TITLE
HTTP2: Hang when writing sending large data to completed request

### ISSUE THREAD

**Issue by JamesNK** [dotnet/corefx#39582]
Writing large data to the request stream (Http2WriteStream retrieved from SerializeToStreamAsync) will hang if the server has finished. I would have expected Stream.WriteAsync to error.

Repro:
1. `git clone https://github.com/JamesNK/grpc-dotnet.git`
2. `git checkout jamesnk/unimplemented-duplexstream`
3. `dotnet test test\FunctionalTests --filter Name~DuplexStream_SendToUnimplementedMethod_Hang`

Logic in the test is like:
1. Client makes HTTP/2 call to the server
2. Client immediately starts writing 64 KB to request stream
3. Server finishes response with 200. It never reads the request stream.
4. Client's first write of 64 KB succeeds (i.e. doesn't hang. I don't know what has happened to the data). Client writes another block of 64 KB. Client hangs on awaiting Stream.WriteAsync.

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013248
 Commit:    135af55c46
```

**Comment by stephentoub** [comment]
>  It never reads the request stream.

Isn't that the bug here?

**Comment by JamesNK** [comment]
Does a server always have to read the client request to prevent the client from hanging?

In this scenario the client has called the wrong location and the server sends them a simple status - HEADERS - saying so, followed by RST_STREAM (NO_ERROR)

**Comment by JamesNK** [comment]
1. Client sends request headers (plus some data straight away)
2. Client sends more data
3. Server responds with response headers and stream reset

![image](https://user-images.githubusercontent.com/303201/61424216-e7aace80-a966-11e9-84a1-9ed23f20e535.png)

**Comment by JamesNK** [comment]
https://github.com/dotnet/corefx/issues/39458

Same issue?

**Comment by stephentoub** [comment]
> Same issue?

Yes, if the issue is that the client isn't respecting RST_STREAM while sending the request body, that's the same issue.
