### ISSUE TITLE
Many XxxExpression.Update returns different expression for identical children in different collection.

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#3958]
According to the documentation:

> If all of the children are the same, it will return this expression.

However, only the enumerables themselves are compared, so a different enumeration of the same children will incorrectly return a new expression.

In particular a `TryExpression` with no catch blocks (valid if the expression has a finally or fault block) must be `Update`d with the empty `Handlers` property it holds fed back to it, rather than `null` or another empty collection of handlers.

**Comment by bartdesmet** [comment]
AFAIK, all of the expression nodes with an IEnumerable<T> collection of children simply use a reference equality comparison in the Update method, and never do a SequenceEqual check in an attempt to retain the current node instance. At the very minimum, this should suffice for object.ReferenceEquals(e, visitor.Visit(e)) to hold, such that visiting an expression doesn't cause cloning of any subtree. This was not the case for ConditionalExpression without an IfFalse expression set, cf. the recent change to that node type to fix this behavior.

If we decide to make a change to any particular node such as TryExpression, we should be consistent across all node types. However, there's a question as to whether the cloning behavior is desired, similar to the factory methods returning unique instances (i.e. unless everything is reference equal, cause cloning).

**Comment by JonHanna** [comment]
Yes, I was quite deliberately not looking at the woods in order to give detailed attention to the trees, but this does affect (whether as a flaw or just something that could perhaps be spelled out differently in the docs) several expression types.

Some of those expressions are sorely lacking in tests, and I'd rather have tests that would catch any regressions before shifting much.

Whether something actually needs to be done can still be considered before then, though.

**Comment by JonHanna** [comment]
From the other issue @bartdesmet 

> Is there inadvertent cloning behavior when the expression is run through a no-op visitor?

Well, I first found this by writing a quick mostly-no-op visitor to test something and neglecting to explicitly pass in the same collection. One could write a reasonable visitor that changed little, coming up with identical collections the majority of the time, and still failed to produce this behaviour from `Update`.

On the other hand, it's not very hard to avoid if one knows what to do to avoid it, so perhaps just clarifying "all of the children" means the exact same collection(s) in the documentation would be worth doing, and allay any other concerns.

**Comment by JonHanna** [comment]
Since this is marked up for grabs, I'm taking that as a green light on tackling this. (I'd just remembered it and looked it up to argue it's case).
