### ISSUE TITLE
weird version of downloaded runtime when building aspnet core repo

### ISSUE THREAD

**Issue by chrisnas** [dotnet/corefx#39592]
I've cloned the aspnetcore repo 
![image](https://user-images.githubusercontent.com/10163781/61466443-357d0200-a97a-11e9-9c10-a1a4c746fbe8.png)
and tried to rebuild it on Windows with build.cmd

During the .NET Core runtime installation process, I see **preview8** versions downloaded while the preview 7 is not even available yet
- SDK: 3.0.100-preview6-012264
- runtime: 3.0.0-preview8-27914-06

```
D:\github\AspNetCore>.\build.cmd
WARNING: No default group of projects was specified, so building the 'managed' subsets of projects. Run `build.cmd
-help` for more details.
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview6-012264/dotnet-sdk-3.0.100-preview6-012264-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview6-012264/dotnet-sdk-3.0.100-preview6-012264-win-x64.zip
dotnet-install: Adding to current process PATH: "D:\github\AspNetCore\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished
Downloading vswhere
Downloading RoslynTools.MSBuild 16.0.0-alpha
  Restauration effectuée dans 11.62 sec pour C:\Users\cnasa\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19365.4\tools\Tools.proj.
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Runtime/3.0.0-preview8-27914-06/dotnet-runtime-3.0.0-preview8-27914-06-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Runtime/3.0.0-preview8-27914-06/dotnet-runtime-3.0.0-preview8-27914-06-win-x64.zip
dotnet-install: Installation finished
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Runtime/3.0.0-preview8-27914-06/dotnet-runtime-3.0.0-preview8-27914-06-win-x86.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Runtime/3.0.0-preview8-27914-06/dotnet-runtime-3.0.0-preview8-27914-06-win-x86.zip
dotnet-install: Adding to current process PATH: "D:\github\AspNetCore\.dotnet\x86\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished

```
@karelz mentioned that I should create an issue in the corefx repo with the "wtgobde" tag
I hope this helps

**Comment by davidsh** [comment]
>During the .NET Core runtime installation process, I see preview8 versions downloaded while the preview 7 is not even available yet

The master branch is already on "preview 8" level because the code has forked into the release/3.0 branch.  The release/3.0 branch is at "preview 7" level.  We expect .NET Core 3.0 Preview 7 to formally release to the public soon.

**Comment by karelz** [comment]
@wtgodbe @ViktorHofer @safern can you please take a look?

**Comment by ViktorHofer** [comment]
What's the issue here? I can't see any errors in the log.

**Comment by stephentoub** [comment]
This looks fine to me. As David said, our dev branches pull builds based on other repo's dev branches, which are generally newer than what's been released.

**Comment by chrisnas** [comment]
When switching to release/3.0-preview7 branch, the preview7 version of the runtime is downloaded
Got it.
