### ISSUE TITLE
Improve protocol for Experimental packages

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/corefx#39611]
Right now, we have 2 experimental packages in CoreFx - https://github.com/dotnet/corefx/tree/master/src/System.Utf8String.Experimental and https://github.com/dotnet/corefx/tree/master/src/System.Runtime.Intrinsics.Experimental. Both block themselves from shipping stable by setting `BlockStable=true`: https://github.com/dotnet/corefx/blob/182bed51dec709b3b1b56a4f435e0727e5dea110/src/System.Runtime.Intrinsics.Experimental/Directory.Build.props#L6. We also block publishing of these packages through this exclusion: https://github.com/dotnet/corefx/blob/1841042b99062de13dc80098cede9413be569238/eng/publish.proj#L18. And we exclude them from the `Microsoft.Private.CoreFx.OOB` package: https://github.com/dotnet/corefx/blob/008d21c47c22b5757e09f6c3d346998004a0f985/pkg/Microsoft.Private.CoreFx.OOB/Microsoft.Private.CoreFx.OOB.pkgproj#L28. However, we have a couple pieces of weirdness around these 2 - first, we don't automatically exclude them from the APICatalog layout drops, which lead to `System.Runtime.Intrinsics.Experimental` showing up in our official docs (e.g. https://docs.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.x86.avx2?view=netcore-3.0); and second, we manually exclude all source files from compilation for `System.Utf8String.Experimental` - https://github.com/dotnet/corefx/blob/182bed51dec709b3b1b56a4f435e0727e5dea110/src/System.Utf8String.Experimental/src/System.Utf8String.Experimental.csproj#L9 (which is why `System.Utf8String.Experimental` doesn't show up on the docs page). We should clean up these workarounds, and figure out a way to exclude the experimental types from the docs layout.

CC @ahsonkhan @safern @ViktorHofer @ericstj

**Comment by safern** [comment]
I think this pieces should get all together once we improve the docs and ApiCompat layout generation by using the Microsoft.NETCore.App package as the source of truth for the docs. I’ve been currently generating those drops manually and I missed that these where there. Will consider for P8 to avoid having them show up in the docs.

**Comment by ahsonkhan** [comment]
Also adding area owners, @tannergooding, @GrabYourPitchforks

**Comment by ViktorHofer** [comment]
As @safern mentioned the docs part is currently a manual progress. What is the action-item here? Do you want to consolidate how we mark packages as non-public?

**Comment by wtgodbe** [comment]
> Do you want to consolidate how we mark packages as non-public?

Yes, and to use the same logic for the ApiCatalog drop generation process (though presumably once this logic lives in core-sdk, we'll just be picking up `M.NC.App` & the compat back, so we shouldn't have to worry about it at that point)

**Comment by safern** [comment]
Why not converge this with the issue wrt updating the infrastructure of producing the APICatalog and docs drop, instead of having a new issue.

**Comment by wtgodbe** [comment]
We can consolidate this to just removing the compilation workaround for `UTF8String` (and perhaps consolidating the logic for defining Experimental types), since the APICatalog stuff will live in core-sdk and is sort of orthogonal to the CoreFx work

**Comment by ahsonkhan** [comment]
On thing we should get clarity on is what does the csproj/pkgproj look like for the experimental/preview/non-shipping packages. We have two instances currently and they are not consistent.
`Utf8String` uses `BlockStable` and conditionally includes the files on `IsPrerelease`.
`Instrinsics` only uses `BlockStable`.

Why is that? What is the recommended pattern?

**Comment by wtgodbe** [comment]
@tannergooding is https://github.com/dotnet/corefx/tree/master/src/System.Numerics.Tensors also experimental?

**Comment by tannergooding** [comment]
Yes, as per the e-mail thread, `System.Numerics.Tensors` is an experimental package.

**Comment by ahsonkhan** [comment]
We should be excluding such experimental packages from the .NET Core 3.0 docs drop and API diff:
https://docs.microsoft.com/en-us/dotnet/api/system.numerics.tensors?view=dotnet-plat-ext-3.0

Just so there is clarity, it's these three:
- System.Numerics.Tensors
- System.Runtime.Intrinsics.Experimental
- System.Utf8String.Experimental

Or are there others? They all should at least be `BlockStable`
https://github.com/dotnet/corefx/search?q=BlockStable&unscoped_q=BlockStable

We should also try to be consistent and make sure all the package names/csproj have a suffix `.Experimental`.

cc @mairaw

**Comment by ViktorHofer** [comment]
We believe most of the work discussed here is implemented with https://github.com/dotnet/corefx/commit/d217998bc5a3dfdc21ae22dd6161ea6c8f71f30c. Closing.
