### ISSUE TITLE
System.ArgumentOutOfRangeException is thrown by System.Diagnostics.TraceSource.TraceEvent

### ISSUE THREAD

**Issue by Liphi** [dotnet/corefx#39626]
Hi, this issue happens sporadically. Can expert share some light? Is there some known issue like concurrency?

                   foreach (KeyValuePair<string, Endpoint> publicEndpoint in publicEndpoints.Entry)
                    {
                        if (publicEndpoint.Value.IPAddress == null
                            || publicEndpoint.Value.Region == null
                            || publicEndpoint.Value.HostId == default(Guid)
                            || publicEndpoint.Value.ApiUri == null)
                        {
                            CosmosDBTrace.TraceWarning(
                                "RegionalEndpointsRefreshHandler: Required Endpoint propertie(s) null. IPAdress = {0}, Region = {1}, HostId = {2}, ApiUri = {3}",
                                publicEndpoint.Value.IPAddress,
                                publicEndpoint.Value.Region,
                                publicEndpoint.Value.HostId,
                                publicEndpoint.Value.ApiUri);
                            continue;
                        }
                    }

        public void TraceWarning(string format, params object[] args)
        {
            if (args != null && args.Length > 0)
            {
                this.TraceSource.TraceEvent(TraceEventType.Warning, 0, format, args);
            }
            else
            {
                this.TraceSource.TraceEvent(TraceEventType.Warning, 0, format);
            }
        }

System.ArgumentOutOfRangeException: Count cannot be less than zero. Parameter name: count 
StackTrace :
at System.String.CopyTo(Int32 sourceIndex, Char[] destination, Int32 destinationIndex, Int32 count) at System.IO.StreamWriter.Write(String value) at System.Diagnostics.TextWriterTraceListener.Write(String message) at System.Diagnostics.TraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id) at System.Diagnostics.TraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String format, Object[] args) at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String format, Object[] args) at Microsoft.Azure.Cosmos.Compute.Core.Diagnostics.DiagnosticsTrace.TraceWarning(String format, Object[] args) in d:\dbs\sh\csdb\0718_213049_0\cmd\w\Product\Cosmos\Compute\Core\Diagnostics\DiagnosticsTrace.cs:line 96 ...

**Comment by stephentoub** [comment]
What is the value of `Trace.UseGlobalLock`?  Is there some code somewhere setting it to `false`?

**Comment by Liphi** [comment]
yeah, I see it is set as false. Is it the root cause?

        public DiagnosticsTrace()
        {
            // From MSDN: http://msdn.microsoft.com/en-us/library/system.diagnostics.trace.usegloballock%28v=vs.110%29.aspx
            // The global lock is always used if the trace listener is not thread safe,
            // regardless of the value of UseGlobalLock. The IsThreadSafe property is used to determine
            // if the listener is thread safe. The global lock is not used only if the value of
            // UseGlobalLock is false and the value of IsThreadSafe is true.
            // The default behavior is to use the global lock.

            System.Diagnostics.Trace.UseGlobalLock = false;
        }

**Comment by stephentoub** [comment]
> Is it the root cause?

Most likely.  The stack is highlighting a failure that suggests code is accessing the underlying StreamWriter concurrently, which it shouldn't.

**Comment by Liphi** [comment]
Thx. May i know the drawback if we set it as true? Perf penalty?

**Comment by stephentoub** [comment]
> May i know the drawback if we set it as true? Perf penalty?

The default is `true`.  It causes a shared lock to be taken each time you trace.  In contrast, if it's false, then a lock is taken on each listener instance that gets written to if that listener's IsThreadSafe is false (also the default).

My guess is that somewhere in your code, two different trace listeners around the same StreamWriter.  As such, with UseGlobalLock as false, a lock is being taken on those instances, but as the instances aren't the same, the locks aren't the same, and so the underlying StreamWriter ends up being accessed concurrently.  If my guess is correct, then this will be fixed by UseGlobalLock's default of true, because all access would be performed under the same lock.  Another solution if that is the case would be to ensure you don't create two listeners for the same stream.
