### ISSUE TITLE
PostAsJsonAsync extension method sets Content-Length to 0 in .NET Core 2.1 with any versions of System.Net.Http and System.Net.Http.Formatting.

### ISSUE THREAD

**Issue by doboczyakos** [dotnet/corefx#39627]
var response = await _client.PostAsJsonAsync(requestUri, value, cancellationToken);

Request object is null on the server side because content length is set to 0.
I've tried the newest versions of System.Net.Http and System.Net.Http.Formatting and the issue is the same.
It works if I replace this with the following:
var objectContent = new ObjectContent<TRequest>(value, new System.Net.Http.Formatting.JsonMediaTypeFormatter(), (System.Net.Http.Headers.MediaTypeHeaderValue)null);
await objectContent.ReadAsStringAsync();
var response = await _client.PostAsync(requestUri, objectContent, cancellationToken);

**Comment by stephentoub** [comment]
@dougbu, should this issue be moved to https://github.com/aspnet/AspNetWebStack?

**Comment by dougbu** [comment]
@stephentoub looks like it. Doing&hellip;

**Comment by dougbu** [comment]
Oh well, I can't transfer out of dotnet/x and into aspnet/y. @stephentoub please do the needful.

**Comment by stephentoub** [comment]
> I can't transfer out of dotnet/x and into aspnet/y

@dougbu, I can't either; the transfer support only works within an org.

@doboczyakos, can you please re-open the issue at https://github.com/aspnet/AspNetWebStack? Thanks.

**Comment by doboczyakos** [comment]
Thanks for the very proactive cooperation. Is it really just my interest to have a bug reported?
I've created https://github.com/aspnet/AspNetWebStack/issues/252


> @dougbu, should this issue be moved to https://github.com/aspnet/AspNetWebStack?

**Comment by t-l-k** [comment]
@doboczyakos opened this as https://github.com/aspnet/AspNetWebStack/issues/252

(just joining the dots)
