### ISSUE TITLE
Inconsistent param name for SequencePosition

### ISSUE THREAD

**Issue by mairaw** [dotnet/corefx#39629]
While reviewing a docs PR for adding the docs for SequencePosition (https://github.com/dotnet/dotnet-api-docs/pull/2683), I've noticed that some of the naming is not consistent.

In some cases, the object param is called object, other times obj. Can't they be consistent?
https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/SequencePosition.cs#L22
https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/SequencePosition.cs#L51

**Comment by danmosemsft** [comment]
This API already shipped I think, and parameter name changes are binary (reflection) and source (named parameter) breaking changes so I suspect we would not want to change it now.

**Comment by mairaw** [comment]
Yep, it was shipped in 2.1. Closing then.
