### ISSUE TITLE
Window.ShowDialog sometimes blocks several seconds when there is a task frequently update UI

### ISSUE THREAD

**Issue by chenyj796** [dotnet/corefx#39659]
I have a Window to display high frequency market data.
I use Dispatcher.InvokeAsync(... , DispatcherPriority.Background) to update the UI. 
Sometimes if I click some button to show a dialog window, it will block the whole application with serveral seconds.

**Comment by stephentoub** [comment]
Hi @chenyj796, it sounds like your issue is with WPF?  Can you close this issue and open it in https://github.com/dotnet/wpf instead?  Thanks.
