### ISSUE TITLE
HTTP2: dynamic table error when insert index wraps

### ISSUE THREAD

**Issue by scalablecory** [dotnet/corefx#39656]
Once `DynamicTable` has wrapped its insert index, the indexer will start throwing exceptions with high indexes:

https://github.com/dotnet/corefx/blob/347412c9a917c71a744d8e20b090da90aa558a79/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HPack/DynamicTable.cs#L28-L39

**Comment by stephentoub** [comment]
@scalablecory, do we end up using the dynamic table at all today?  We disable that functionality, right?  If I'm remembering correctly, makes me wonder why we're carrying around the code for a disabled feature.

Regarding exceptions, what should it be doing instead? i.e. what does the HTTP2 protocol say should happen when we exceed 2^31 dynamic headers?

**Comment by scalablecory** [comment]
We can't send dynamic headers today but we do receive them.

This isn't about integer overflow, which shouldn't happen with current implementation, but about wrapping of `_insertIndex` back to 0 when we insert new entries:

```c#
_insertIndex = (_insertIndex + 1) % _buffer.Length;
```

This is expected behavior (`_buffer` is a ring buffer), but the indexer doesn't handle it properly as you'll get `_buffer[1 - index - 1]` where `index` can be in the 100s.

**Comment by stephentoub** [comment]
> We can't send dynamic headers today but we do receive them.

Don't we disable it in https://github.com/dotnet/corefx/blob/98db7d16ba21886901efbce6ea7b7e2b4ccec23c/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L137-L141?  Is that insufficient?

**Comment by stephentoub** [comment]
> the indexer doesn't handle it properly

That said, if we actually do support receiving dynamic headers, but we're not properly handling a large-ish number of them, that's something we should fix for 3.0 rather than 5.0.

**Comment by scalablecory** [comment]
Ah! Yes, it looks like we do disable them, so 3.0 is safe here. Thanks for finding that.
