### ISSUE TITLE
BrotliEncoder.GetMaxCompressedLength uses wrong parameter name in ref vs src

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#39654]
`BrotliEncoder` has this in the ref:
```
public static int GetMaxCompressedLength(int inputSize)
```
but this in the src:
```
public static int GetMaxCompressedLength(int length)
```
It was shipped with the "inputSize" parameter like that in the reference assembly and docs in previous releases, so it's technically a breaking change to rename it, and I don't know what name was actually approved in API review.  The implementation does argument validation on the argument, and will throw an argument exception containing "length" if it's invalid.

**Comment by bartonjs** [comment]
The API review (https://github.com/dotnet/corefx/issues/25785) brought in `public static int GetMaximumCompressedSize(int inputSize) { throw null; }` and exited with `public static int GetMaxCompressedLength(int length);`, looks like the ref only caught half of that change.

Given that changing the src is less breaking than the ref, I'd make the src match the ref (and update the exception as well).
