### ISSUE TITLE
Add IEnumerable<T>.ToArray(int) overload to optimize performance

### ISSUE THREAD

**Issue by RobertBouillon** [dotnet/corefx#39663]
LINQ's default `ToArray()` is great for rapid-development, but sometimes you know the size of the desired array and you don't need `ToArray()` to spend CPU time figuring it out. By supplying the desired array size, you can bypass a lot of superfluous code in the default `ToArray()` designed to intelligently determine the size of the new array.

```csharp
//Current API
string[] ConvertToString(int[] foo) => foo.Select(x=>x.ToString()).ToArray();

//Proposed API allows the implementer to supply the desired length.
string[] ConvertToString(int[] foo) => foo.Select(x=>x.ToString()).ToArray(foo.Length);
```

Prototype:
```csharp
public static T[] ToArray<T>(this IEnumerable<T> source, int count)
{
  T[] ret = new T[count];

  int index = 0;
  foreach(T item in source)
    ret[index++] = item;
  return ret;
}
```

**Comment by EgorBo** [comment]
See https://github.com/dotnet/corefx/issues/2926

**Comment by stephentoub** [comment]
> you don't need ToArray() to spend CPU time figuring it out

Are you noticing measurable performance impact?  In the example you highlight, for example, there shouldn't be any, as the output array will be constructed with the underlying array's length:
https://source.dot.net/#System.Linq/System/Linq/Select.SpeedOpt.cs,74

> Related: #2926

I'm going to close this as a dup of #2926, as this API was already proposed, discussed, and decided against.  Thanks for the suggestion, though.
