### ISSUE TITLE
Code coverage badge is out of date

### ISSUE THREAD

**Issue by Maxwe11** [dotnet/corefx#3967]
**Line coverage**
Badge number: 56.8%
Actual number: 57.8%

**Branch coverage**
Badge number: 45.5%
Actual number: 47.0%

**Comment by joshfree** [comment]
@Sridhar-MS can you comment?

**Comment by stephentoub** [comment]
It looks correct to me.  @Maxwe11, can you try just manually refreshing the corefx page?  You might have a stale cached file.

**Comment by Maxwe11** [comment]
Clearing browser cache didn't help but it looks correct if I open image directly.
Same issue on another machine in same LAN.
Since it's not related with project I close issue, thanks.
