### ISSUE TITLE
Port System.Diagnostics.Eventing namespace to .Net Core

### ISSUE THREAD

**Issue by Anipik** [dotnet/corefx#39670]
We ported System.Diagnostics.Eventlog(2.1) and System.Diagnostics.Eventing.Reader(3.0) but we 
missed types in System.Diagnostics.Eventing

The three types are
```
EventDescriptor
EventProvider
EventProviderTraceListener
```

I am not sure if we missed it by chance or these were not ported on purpose.
Currently eventing apis can only be used to read the logs and not write it. You will have to use eventlog to write it.
These types\apis provide an another way to write eventlogs.

Related Issue https://github.com/dotnet/core/issues/2933

cc @ericstj @danmosemsft @maryamariyan

**Comment by ericstj** [comment]
I believe the distinction is writing vs reading.  I believe EventProvider is the writing side, and an EventProviderTraceListener is a bridge type that connects the tracing system to an event writer.  You may want to look into what the required registration / installation story is for these to work.  If its purely managed code on top of PInvokes its probably OK to bring back in one of the nuget packages for windows only.  If it requires installation / machine-wide registration that might not be so easy.
/cc @brianrob

**Comment by brianrob** [comment]
These should not be ported.  They are older functionality that have been replaced by `EventSource`.
/cc @noahfalk
