### ISSUE TITLE
Reading Socket.Blocking returns a stale cache value; code and documentation don't agree

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/corefx#39677]
I'm not sure if the code is wrong or the documentation is wrong.

Documentation says "The Blocking property indicates whether a Socket is in blocking mode." The actual behavior on reading the property is it returns the last value the property was set to. If you make a native API call (in this case the call was WSAEventSelect) the property return is stale. I spent a long time trying to track this down before checking the source code and noticing reading `Blocking` doesn't really do anything.

**Comment by scalablecory** [comment]
What scenario are you seeing `Blocking` not reflect the actual blocking configuration of the socket?

Are you calling `WSASetEvent` on a socket?

**Comment by jhudsoncedaron** [comment]
Yes, that's exactly what I did. There's no other way to wait for one of five conditions where some of them are sockets and some aren't.

**Comment by jhudsoncedaron** [comment]
Sorry, somehow got the wrong function. The actual function is WSAEventSelect .
[blockingnonblocking.zip](https://github.com/dotnet/corefx/files/3419301/blockingnonblocking.zip)

**Comment by scalablecory** [comment]
Ah! `WSAEventSelect` does automatically set a socket to non-blocking, so this makes sense now.

For now, I would generally assume using the `SafeHandle` to operate on the socket might create any number of unexpected/undocumented states. @davidsh any background on why we're caching the `Blocking` property?

If this is an issue for you, an alternative to using `WSAEventSelect` might be to use async and `Task.WhenAny` to identify when either your socket i/o or some other non-socket task has completed.

**Comment by jhudsoncedaron** [comment]
The only issue was me reading the "Blocking" property to track down where the call was that changed it to non-blocking and left it and finding it was still true at the point of failure later on.

**Comment by scalablecory** [comment]
Okay. We'll get docs updated on using `SafeHandle` in https://github.com/dotnet/dotnet-api-docs/pull/2767.

On if we should be caching `Blocking` or not is another thing all together -- will want some thoughts from @dotnet/ncl. I suspect we do so right now for perf reasons and changing that may not be ideal.

**Comment by wfurt** [comment]
It should have proper value if you use .Net functions to manipulate the socket, right @scalablecory ? So the warning is about case when somebody manipulates OS handle behind our back.
In such cases more troubles can happen in general.

**Comment by scalablecory** [comment]
> It should have proper value if you use .Net functions to manipulate the socket, right @scalablecory ? So the warning is about case when somebody manipulates OS handle behind our back.
> In such cases more troubles can happen in general.

Correct. I'm fine saying you're on your own if you do this. Mostly curious why we're doing it :).

**Comment by jhudsoncedaron** [comment]
Why do you read this property if not for debugging? I couldn't come up with another reason.

**Comment by scalablecory** [comment]
Closing this out as docs were updated for 3.0
