### ISSUE TITLE
[System.Net.NetworkInformation] BasicTest_AccessInstanceProperties_NoExceptions test failed

### ISSUE THREAD

**Issue by Maxwe11** [dotnet/corefx#3969]
(local build)

		 System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_AccessInstanceProperties_NoExceptions [FAIL]
			Overflow
			Expected: True
			Actual:   False
			Stack Trace:
	  Discovered:  System.Composition.Tests
			   E:\Workspace\github\corefx\src\System.Net.NetworkInformation\tests\FunctionalTests\NetworkInterfaceBasicTest.cs(39,0): at System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_AccessInstanceProperties_NoExceptions()
	  Finished:    System.Net.NetworkInformation.Functional.Tests
	  
	  Starting:    System.Composition.Tests
	  === TEST EXECUTION SUMMARY ===
		 System.Net.NetworkInformation.Functional.Tests  Total: 19, Errors: 0, Failed: 1, Skipped: 0, Time: 3,682s

**Comment by joshfree** [comment]
cc @CIPop @davidsh @SidharthNabar

**Comment by CIPop** [comment]
@Maxwe11 Please provide a full-memory dump or describe repro steps. Unfortunately the log isn't helping here.

**Comment by Maxwe11** [comment]
just run `build.cmd` from root of the project or `msbuild /t:RebuildAndTest` from directory with tests (`System.Net.NetworkInformation\tests\FunctionalTests`)

**Comment by CIPop** [comment]
I believe that this was fixed by #4452 after the issue was understood (repro only on machines with certain WiFi cards).
@Maxwe11 please let us know if you are still hitting this. (Also attach the ETW logs or dump if so.)
