### ISSUE TITLE
Enable disabled xunit warnings

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#39697]
- [x] xUnit1019	MemberData must reference a member providing a valid data type
- [x] xUnit1026	Theory methods should use all of their parameters
- [x] xUnit2017	Do not use Contains() to check if a value exists in a collection

**Comment by danmosemsft** [comment]
Community folks, as indicated by the labels, this is a great first issue.

**Comment by ViktorHofer** [comment]
You are fast Mr Toub. Meanwhile I'm at an .NET Event giving a talk and watching your PRs coming in. I feel like a PM.

**Comment by Gnbrkm41** [comment]
working on 2000.

**Comment by Gnbrkm41** [comment]
working on 2000.

**Comment by zoeysaurusrex** [comment]
I’ll grab 2005 today

**Comment by Gnbrkm41** [comment]
a couple of the xUnit2003 errors from src/Common/tests/System/Security/Cryptography/AlgorithmImplementations/ECDsa/ECDsaTests.netcoreapp.cs slipped out somehow: L193/L216

maybe I'll just do it whilst I'm doing this.

**Comment by Gnbrkm41** [comment]
....actually.... turns out that there's even more.

**Comment by Gnbrkm41** [comment]
Attempting to grab 1026.

**Comment by stephentoub** [comment]
@Gnbrkm41, are you working on 1026?  I started to and then noticed your comment.  If you're actively working on it, I'll stop, otherwise I'll finish it up.

**Comment by Gnbrkm41** [comment]
@stephentoub, feel free finish up; there's still quite a lot left to finish, and I probably won't have time to finish it up for now. Thanks!

**Comment by stephentoub** [comment]
All rules we plan to enable have been enabled.  Thanks!

**Comment by Gnbrkm41** [comment]
Pretty amazing to see all of them enabled, Thanks everyone!
