### ISSUE TITLE
Build fails on macOS in Travis CI with 3.0.0 preview 7 - "dyld: lazy symbol binding failed: Symbol not found: _utimensat"

### ISSUE THREAD

**Issue by martincostello** [dotnet/corefx#39701]
I've been maintaining a branch of [AspNet.Security.OpenId.Providers](https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers/pull/53) for ASP.NET Core 3.0 for a while, and just updated it from preview 6 to preview 7 (SDK version `3.0.100-preview7-012821`).

The macOS build in Travis CI fails with the following error in preview 7 ([build](https://travis-ci.org/aspnet-contrib/AspNet.Security.OpenId.Providers/jobs/562701646#L114)):

```sh
dyld: lazy symbol binding failed: Symbol not found: _utimensat
  Referenced from: /Users/travis/build/aspnet-contrib/AspNet.Security.OpenId.Providers/.dotnetcli/shared/Microsoft.NETCore.App/3.0.0-preview7-27912-14/System.Native.dylib
  Expected in: /usr/lib/libSystem.B.dylib
```

This failure appears right at the top of the build script with `dotnet build`.

I've already updated several other branches from preview 6 to preview 7 with no issue, so it doesn't look like something systematic, but I'm not sure what specifically in this PR is causing the problem.

**Comment by martincostello** [comment]
Same issue [for this PR](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/333) too on [macOS](https://travis-ci.org/aspnet-contrib/AspNet.Security.OAuth.Providers/jobs/562726110#L115).

**Comment by martincostello** [comment]
Further digging found that the Travis macOS build was pinned to `osx_image: xcode8.3`, which equates to macOS 10.12 ([docs](https://docs.travis-ci.com/user/reference/osx/#using-macos)).

Removing this constraint (https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/333/commits/dbd0a9636ffad3ca1c690d396577d2d517111a85) [fixed the issue](https://travis-ci.org/aspnet-contrib/AspNet.Security.OAuth.Providers/jobs/562728294).

Leaving open for now as I'm not sure if this is an intentional change to the compatibility matrix for .NET Core 3.0 or not.

**Comment by ericstj** [comment]
Introduced in https://github.com/dotnet/corefx/pull/31522 /cc @Anipik  @bartonjs @stephentoub 

Did we intend to drop support for OSX 10.12?  Our docs say its still supported.
https://docs.microsoft.com/en-US/dotnet/core/macos-prerequisites?tabs=netcore30

**Comment by bartonjs** [comment]
macOS 10.12 is not supported: https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md.  We just have too many redundant documentation sources.  (@leecow we need to get https://docs.microsoft.com/en-US/dotnet/core/macos-prerequisites?tabs=netcore30 updated to say 10.13)

**Comment by danmosemsft** [comment]
Doc fixed. Thanks for the report.
