### ISSUE TITLE
Upgrade analyzer packages

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#39702]
Some of the core analyzer packages we're using are tied to versions that are several years out-of-date.

**Comment by ericstj** [comment]
Can you be more specific? https://github.com/dotnet/corefx/blob/e6a5951fb68a09598f1fc1826a94de212385c649/eng/Analyzers.props#L2-L10
/cc @safern

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/blob/e6a5951fb68a09598f1fc1826a94de212385c649/eng/Analyzers.props#L5-L6

e.g. Microsoft.CodeAnalysis.FxCopAnalyzers is 1.1.0, which was released on 11/30/2015.  The current version is 2.9.4-beta1.final, released last month.

I'm working on it.

**Comment by ericstj** [comment]
Maybe we can subscribe to that and get Darc updates?

**Comment by stephentoub** [comment]
Probably.  But we've got debt to address before we can do that, which is mainly what I'm working on.

**Comment by safern** [comment]
Thanks, @stephentoub
