### ISSUE TITLE
HTTP Status Code to description

### ISSUE THREAD

**Issue by honfika** [dotnet/corefx#39715]
Please make the `System.Net.HttpStatusDescription` class and the `Get` method in that class public. I think it would be useful for some users.
https://github.com/dotnet/corefx/blob/28e0be5f236b57027b66395fcef87d3c58e31424/src/Common/src/System/Net/HttpStatusDescription.cs#L7

In .NET framework this functionality is available as:
`System.Web.HttpWorkerRequest.GetStatusDescription(304);`

This method is also duplicated in corefx source (however it just test), for example here:
https://github.com/dotnet/corefx/blob/28e0be5f236b57027b66395fcef87d3c58e31424/src/Common/tests/System/Net/Http/LoopbackServer.cs#L223

I know that there is a workaround to get this message:
```c#
            var m = new HttpResponseMessage(HttpStatusCode.NotModified);
            string desc = m.ReasonPhrase;
```
But I'd like to avoid the new object allocation.

**Comment by khellang** [comment]
If you have ASP.NET Core referenced anyway, you probably have access to the `Microsoft.AspNetCore.WebUtilities.ReasonPhrases` type and its [`GetReasonPhrase(Int32)`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.webutilities.reasonphrases.getreasonphrase) method.

**Comment by honfika** [comment]
Thanks. I don't have ASP.NET Core reference.
So that another place where this list is hardcoded in .NET source...
https://github.com/aspnet/AspNetCore/blob/425c196cba530b161b120a57af8f1dd513b96f67/src/Http/WebUtilities/src/ReasonPhrases.cs

By the way, the ASP.NET Core's list is a little bir different, ASP.NET does not contain status code 103... CoreFX does not contain 306, 418, 419.

**Comment by Tratcher** [comment]
What do you want to do with the reason phrases?

**Comment by honfika** [comment]
I'd like to create HTTP response messages in our HTTP(S)&HTTP/2 Proxy library:
https://github.com/justcoding121/Titanium-Web-Proxy

**Comment by karelz** [comment]
Triage: One can create an extension method, even with caching if perf matters. Given this is not mainline scenario with just low upvotes, we don't think it is valuable for CoreFX to add it. Closing.
