### ISSUE TITLE
System.NotImplementedException: Neutral region info at System.Globalization.RegionInfo..ctor

### ISSUE THREAD

**Issue by ststeiger** [dotnet/corefx#39723]
If one does
`Size = RegionInfo.CurrentRegion.IsMetric ? PageSize.A4 : PageSize.Letter;`
this fails, with a 

> System.NotImplementedException: Neutral region info at System.Globalization.RegionInfo..ctor

under certain conditions or environments (Xamarin.Forms). 

See 
https://github.com/ststeiger/PdfSharpCore/issues/46
https://github.com/ststeiger/PdfSharpCore/commit/2ba8fbe9fbde77c5f0e83d92af9b163f7a919c57

Is there something like InvariantRegion that one could return ? 
Or wouldn't it be better to return NULL in CurrentRegion, then it could be caught without exceptions. 
Could we define InvariantRegion as metric, since that's the [SI-unit](https://en.wikipedia.org/wiki/International_System_of_Units) ?

**Comment by stephentoub** [comment]
@ststeiger, can you share a more complete repro as well as the full stack trace of the exception?

And, you say "under certain conditions or environments (Xamarin.Forms)"... is your repro using .NET Core or Mono?

Thanks.

**Comment by tarekgh** [comment]
I don't think this is coreclr issue. Maybe this is mono issue? looking at the failing stack 

https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Globalization/RegionInfo.cs#L99

We don't throw NotImplementedException but mono does:

https://github.com/mono/mono/blob/master/mcs/class/corlib/System.Globalization/RegionInfo.cs#L113

I'll move the issue to Mono.

**Comment by tarekgh** [comment]
This issue was moved to mono/mono#15820
