### ISSUE TITLE
NullReferenceException in Regex.Replace

### ISSUE THREAD

**Issue by tonyredondo** [dotnet/corefx#39746]
The following code works when the project is targeting `netcoreapp2.2` framework, but fails with a **`NullReferenceException`** in `netcoreapp3.0` preview7.

```csharp
using System;
using System.Text.RegularExpressions;

namespace BugDemo
{
    class Program
    {
        private static readonly Regex EnvironmentTemplateFormatRegex = 
            new Regex(@"{Env:([A-Za-z0-9_ |+-\\*/_!""$% &\(\) = '?¡¿.:,;<>]*)}", 
                RegexOptions.Compiled | RegexOptions.Multiline);

        static void Main(string[] args)
        {
            Console.WriteLine(ReplaceEnvironmentTemplate("value value {Env:MYENVVAR} value value"));
        }

        public static string ReplaceEnvironmentTemplate(string source)
        {
            if (source is null) return null;
            var result = EnvironmentTemplateFormatRegex.Replace(source, match =>
            {
                if (match.Groups.Count < 2) return match.Value;
                var key = match.Groups[1].Value;
                return Environment.GetEnvironmentVariable(key);
            });
            return result;
        }
    }
}

``` 
![image](https://user-images.githubusercontent.com/69803/61830151-c10afd00-ae6a-11e9-8daf-81bf6edc05cf.png)

**Comment by danmosemsft** [comment]
My guess - the GetEnvironmentVariable is returning null. Looking at the code, StringBuilder will allow you to append a null string (it ignores it) but ValueStringBuilder does not.

**Comment by danmosemsft** [comment]
Similar for Insert, VSB does not accept null but SB does. So either Regex (and anyone else who changed to VSB) should check for null before calling, or VSB should match SB semantics here. I suggest the latter as the cost is negligible and it avoids other cases of this error.

cc @stephentoub

**Comment by stephentoub** [comment]
> as the cost is negligible

Based on what? We use VSB in some fairly time sensitive code.

**Comment by danmosemsft** [comment]
Based on the fact its just a null check, but sure, there's places even that is measurable. Your preference?

**Comment by stephentoub** [comment]
> Your preference?

If that's actually the issue...

Either do the null check at each call site where a null is possible, or add a Regex-specific method to VSB (ala https://github.com/dotnet/corefx/blob/master/src/System.Text.RegularExpressions/src/System/Text/ValueStringBuilder.Reverse.cs) that does the null check as well and then use that instead.

**Comment by danmosemsft** [comment]
Good point about inlining. @ViktorHofer I can fix this, you're busy.

**Comment by danmosemsft** [comment]
Need to port

**Comment by danmosemsft** [comment]
Thanks @tonyredondo  for the report, you should see this fixed in 3.0 Preview 8 in not too long.

**Comment by tonyredondo** [comment]
Thanks to you, I’m glad to see how fast the the fix has been done. I’m gonna continue testing the preview. Meanwhile I just gonna put “?? string.Empty”, and continue porting the project I’m working on.

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/corefx/pull/39818.
