### ISSUE TITLE
Directory.EnumerateDirectories Hits Open File Descriptor Limit Somewhat Easily

### ISSUE THREAD

**Issue by steveisok** [dotnet/corefx#39768]
This was originally raised by the VS for Mac team as they were seeing the issue w/ their Angular project template.  The details of that issue and my analysis can be found in https://github.com/mono/mono/issues/15738.  

The gist of the issue is that the angular project type does npm install and then they traverse the node_modules directories recursively.  

```
static IEnumerable<T> ExpandWildcardFilePath<T> (....) {
   ....
   if (recursive) {
      // Recursive search. Try to match the remaining subpath in all subdirectories.
      foreach (var dir in Directory.EnumerateDirectories (basePath))
         res = res.Concat (ExpandWildcardFilePath (project, dir, baseRecursiveDir, true, filePath, func, directoryExcludeRegex));
   }
}
```

Now, the argument could be made not to recurse (or read through the enumerator first) and that would be reasonable.  However, I think there may be opportunities to improve our underlying handle usage / lifetime.

**Comment by stephentoub** [comment]
> However, I think there may be opportunities to improve our underlying handle usage / lifetime.

How?

**Comment by steveisok** [comment]
My initial feeling is that if you prioritize handle liftetime, then you'd have to tweak this more like the old mono (and netfx) behavior, which was FindFirstFile / FindNextFile.  

However, I don't know if there are other solutions / what the best ones are, so I'm seeking your input.  

Assuming handle lifetime is actually an issue, what other options do we have?

**Comment by danmosemsft** [comment]
cc @JeremyKuhne

**Comment by JeremyKuhne** [comment]
We already only keep one handle open for the lifetime of the enumerator. I'm not sure what you would do here other than close and reopen the handle between every MoveNext(). That can be done, in theory, but it would be pretty painful and should be kept behind an options flag if we think we need to go that way.

A simple workaround here is to flatten the result if they want to keep the same semantics. E.g. ToArray().

Note that one advantage that exists now is that you can build your own enumerator that contains the recursion within the scope of a single handle.

**Comment by danmosemsft** [comment]
The mono issue above links to a workaround https://github.com/mono/monodevelop/pull/8256/files that just changes to Directory.GetFiles. I'm curious how that helps as I thought that was just sugar on top of the enumerator API.

**Comment by JeremyKuhne** [comment]
>  I'm curious how that helps

Because that effectively does ToArray() on the result, closing the enumerator.

**Comment by steveisok** [comment]
May be rusty, but isn't there an implicit ToArray there when the return type is string[]?

**Comment by stephentoub** [comment]
Right, this is all why I don't understand what the suggestion would be for doing better.

EnumerateDirectories needs to open a handle and keep it open while enumerating; the alternative would be to open the handle, cache everything into a data structure, close the handle, and then return the data structure.  But that's exactly what GetDirectories does, and EnumerateDirectories was introduced later specifically to avoid these overheads.

If a developer actually wants the caching behavior, they can use GetDirectories (or use ToArray).  If a developer wants the recursive behavior, they can specify so with SearchOption and let the implementation handle everything.  If the developer is explicitly calling other things while holding open the handle, well, that's what they get.

Opening the search handle for each subsequent file would be prohibitively expensive (O(N^2)) and wouldn't actually have correct semantics.

**Comment by steveisok** [comment]
That all makes sense to me.  I'm coming from a naive place where I didn't expect the behavior to be what it is. The mono implementation used to be of the open, cache, close, return variety.  

If the intent of EnumerateDirectories in corefx was to lessen overhead, then we can probably close this issue.  

Separately, the VS4M team did indicate their use of GetFiles was a perf drop, but I have no other information than that.

**Comment by stephentoub** [comment]
> If the intent of EnumerateDirectories in corefx was to lessen overhead, then we can probably close this issue.

Thanks.  Not just in corefx; that was the intent of the `Enumerate*` methods in general when they were introduced.  e.g. from the docs:
https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.enumeratefiles?view=netframework-4.8
>The EnumerateFiles and GetFiles methods differ as follows: When you use EnumerateFiles, you can start enumerating the collection of names before the whole collection is returned; when you use GetFiles, you must wait for the whole array of names to be returned before you can access the array. Therefore, when you are working with many files and directories, EnumerateFiles can be more efficient.
