### ISSUE TITLE
System.Net.Http.HttpClient , how to use proxy? netcoreapp2.2

### ISSUE THREAD

**Issue by btrepp** [dotnet/corefx#39794]
How are we supposed to configure system.net.http.httpclient to use proxy's now?.
There's lots of tickets but it seems that is changed/should just work?

A client created like (F#)
```
let handler = new System.Net.Http.HttpClientHandler()
let client = new System.Net.Http.HttpClient(handler)
return client
```
Seems to only work if the proxy is specified explicitly.
I've tried "automatically detect settings" it doesn't appear to pick up the proxy.

Is it possible to use environment variables?

Windows 10, netcoreapp2.2

**Comment by scalablecory** [comment]
"automatically detect settings" uses DNS/DHCP to find proxy settings. Do you have this configured?

"use automatic configuration script" uses a URL to a PAC script to resolve proxies for URLs. Have you tried configuring this? If so, can you supply a copy of your PAC script?

> Is it possible to use environment variables?

HTTP_PROXY will be used for HTTP, HTTPS_PROXY will be used for HTTPS, and ALL_PROXY will be used for either if the other two aren't defined.

**Comment by wfurt** [comment]
I don't think the environment variable change was ported back to 2.2. That will be available only for netcoreapp3.0

cc: @davidsh to confirm

**Comment by davidsh** [comment]
>I don't think the environment variable change was ported back to 2.2. That will be available only for netcoreapp3.0
cc: @davidsh to confirm

Those changes to use environment variables on Windows is only a .NET Core 3.0 feature.

However, if your proxy is configured using IE settings on your Windows machine, then it should be working to detect the proxy.

Please try .NET Core 3.0 (latest preview is .NET Core 3.0 Preview 7).

**Comment by davidsh** [comment]
Please try out .NET Core 3.0.  Latest preview:
https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-8/

If there are problems with proxies for you, please open a new issue.  Thanks!
