### ISSUE TITLE
System.Text.Json cannot parse the Decimal literals. 

### ISSUE THREAD

**Issue by AlexPaskhin** [dotnet/corefx#39792]
Just decided to use System.Text.Json instead of Newtonsoft.Json, but found that System.Text.Json cannot parse the Decimal literals. So they are not compatible.

Here the small code example:
``` c#
     public class TickerBitcoin
    {
        public decimal price_usd { get; set; }
    }
    class Program
    {
        static void Main(string[] args)
        {

            string test_json_string = "[{\"price_usd\":9934.36214151},{\"price_usd\":\"9934.36214151\"}]";

            TickerBitcoin[] tickers1 = (TickerBitcoin[])Newtonsoft.Json.JsonConvert.DeserializeObject(test_json_string, typeof(TickerBitcoin[]));
            Console.WriteLine(" Newtonsoft.Json - passed");

            TickerBitcoin[] tickers2 = (TickerBitcoin[])System.Text.Json.JsonSerializer.Deserialize(test_json_string, typeof(TickerBitcoin[]));
            Console.WriteLine(" System.Text.Json - passed");

        }
    }
```
It works fine for "Newtonsoft.Json" but throws an exception for "System.Text.Json"

**Comment by scalablecory** [comment]
Does your test fail if you remove the quoted decimal value?

Lack of support for quoted numbers is a known behavior #39473.

**Comment by AlexPaskhin** [comment]
Answer on question: **If you remove the quoted decimal the test will pass.**
 
The exact Exception that has been thrown:
```
System.Text.Json.JsonException
  HResult=0x80131500
  Message=The JSON value could not be converted to System.Decimal. Path: $[1].price_usd | LineNumber: 0 | BytePositionInLine: 57.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at ConsoleApp3._0PG.Program.Main(String[] args) in D:\GitHub\Source\AlexBb\RestWebApiService\PG\ConsoleApp3.0PG\Program.cs:line 20

Inner Exception 1:
InvalidOperationException: Cannot get the value of a token type 'String' as a number.
```
It is not expected behaviour for parsing JSON information for millons already existed REST Web API services. 

No one would use System.Text.Json if there is a chance that it cannot parse that 99% of  other JSON parsers CAN.

**Comment by scalablecory** [comment]
I understand your frustration; I too have seen many json APIs that quote their non-float numbers. Continuing discussion on #39473 is the best option to getting this changed.

It looks like there isn't a bug here, so I'm going to close the ticket. If you do believe there is still a bug when you remove the quotes around the second price, please re-open so we can take a look.
