### ISSUE TITLE
HttpRequestMessage leaking memory

### ISSUE THREAD

**Issue by marcscol** [dotnet/corefx#39809]
I made a library in .netstandard 2.0 using HttpClient. I do not even have to send a message to the target endpoint to have the request content not being released.

```c#
using (var dataContent = PrepareHttpContentJson(dataToPost))
{
    HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, 
        new Uri(methodToCall, UriKind.RelativeOrAbsolute));
    request.Content = dataContent;

    request.Content.Dispose();
    request.Content = null;
    request.Dispose();
}
```

Calling Dispose is useless. Setting to null is useless. By an weird reason, the request.Content memory is never returned to be available. If the content is huge, the system crashes in a matter of minutes by out of memory.

**Comment by stephentoub** [comment]
@marcscol, can you please share a complete standalone repro we can run to see the behavior you describe?

**Comment by Clockwork-Muse** [comment]
You should only need to do this:
```
using (var request = new HttpRequestMessage(HttpMethod.Post, new Uri(methodToCall, UriKind.RelativeOrAbsolute)))
{
    // content cleaned up when the request is disposed.
    request.Content = PrepareHttpContentJson(dataToPost);
}
```

.... are you sure you're not holding on to a reference to `dataToPost` somewhere?  That, or `methodToCall`?

**Comment by marcscol** [comment]
Hi Clock,
If I do not assign anything to the request.Content, the memory is cleaned-up nicely. When I assign to the content, the memory keeps rising.

**Comment by marcscol** [comment]
@stephentoub, I will upload to a repro, so you can see what's happening.

Thanks

**Comment by marcscol** [comment]
@Clockwork-Muse, methodToCall is a string constant.

**Comment by Clockwork-Muse** [comment]
@marcscol - if `methodToCall` is a string constant, then the URI can also be a constant (you wouldn't need to create it each time).  This is unlikely to be the source of your problems, however.

**Comment by marcscol** [comment]
@Clockwork-Muse , It is a constant, but this method is call to reach diferent routes. But, like you said, I think this is not related to the problem I am having.

**Comment by stephentoub** [comment]
> I will upload to a repro, so you can see what's happening.

Thanks.

**Comment by eiriktsarpalis** [comment]
Any updates on producing a repro? If not, we could maybe close this?

**Comment by karelz** [comment]
Triage: No repro, not actionable for us now, closing.
If/when there is more info available, feel free to reopen.
