### ISSUE TITLE
Enable yaml stages based publishing

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#39802]
https://github.com/dotnet/arcade/blob/master/Documentation/YamlStagesRepoStatus.md. Target completion data is 8/13.

We need to do this sooner than later.

cc @safern @wtgodbe @ericstj

**Comment by ericstj** [comment]
Yeah, @joperezr and @safern were discussing doing this yesterday.

**Comment by safern** [comment]
Yeah I already started looking at this yesterday.
