### ISSUE TITLE
PublishSingleFile excluding appsettings not working as expected

### ISSUE THREAD

**Issue by matthew-mcginty** [dotnet/corefx#39801]
I'm trying to publish an app so that the publish output creates 2 files only:
App.exe
appsettings.config

App.exe should read/use the config

I have attempted this by placing this in my .proj file:
```
<ItemGroup>        
    <None Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>            
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </None>
</ItemGroup>
```
and publishing with the following:
`dotnet publish -c Release --self-contained -r win-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true`

The expected 2 files are created (exe/config) but the exe does not read the config file, rendering the exe non-functional

Is this possible to achieve?

```
dotnet --version
3.0.100-preview7-012821
```

**Comment by ViktorHofer** [comment]
You can use the `runtimeconfig.json` file to set runtime switches / settings. Would that work for your use-case?

**Comment by matthew-mcginty** [comment]
If it can work then I wouldn't know how. Currently the app uses ConfigurationBuilder/ServiceProvider approach in my `Startup.cs` to load appsettings.json via `GetSection()`. I would not know how to read the `runtimeconfig.json` in a similar way if it's indeed possible. I don't see anything [here](https://github.com/dotnet/cli/blob/v2.0.0/Documentation/specs/runtime-configuration-file.md) which suggests how to to do this.
My `appsettings.json` mainly contains system paths that would vary form user to user

**Comment by ViktorHofer** [comment]
this sounds like aspnetcore specific logic. You might want to move that issue over to https://github.com/aspnet/aspnetcore

**Comment by tarekgh** [comment]
This issue was moved to aspnet/AspNetCore#12621
