### ISSUE TITLE
HTTP2: Race between response body Dispose and request body completion 

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#39819]
Found during GRPC stress.

If the client finishes sending the request body at approximately the same time that it disposes the response body without reading to the end, then there's a race between sending EndStream for the request body and RST_STREAM caused by the dispose. If the RST_STREAM ends up getting sent first, then this is a protocol violation.

**Comment by geoffkizer** [comment]
@eiriktsarpalis For HttpStress to try to induce this, it would try to do something like this:

Create a duplex stream, send some data, have the server send some data too but don't read it on the client, then (a) Dispose the response body and (b) immediately complete the request body.

**Comment by eiriktsarpalis** [comment]
> Create a duplex stream, send some data, have the server send some data too but don't read it on the client, then (a) Dispose the response body and (b) immediately complete the request body.

@geoffkizer I created such a test case, and was able to consistently reproduce a small percentage of errors with the latest nightly. Confirming however that building off latest master made all errors go away.

**Comment by karelz** [comment]
Waiting on merge of #39874 to make it into 3.0. Reopening.

**Comment by karelz** [comment]
Fixed in 3.0 by PR #39874 and in master (5.0) in PR #39834
