### ISSUE TITLE
Potential redundant assertion in System.Data.Common tests?

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/corefx#39826]
https://github.com/dotnet/corefx/blob/8a6389529afdc0dd53d4c94fe665695ec54c21af/src/System.Data.Common/tests/System/Data/DataSetTest2.cs#L1440-L1458

what's the point of comparing two same string literals in this test? seems odd.

**Comment by stephentoub** [comment]
There's no point to them.  I put up a PR to delete them.  In the future, please feel free to just submit a PR to make such fixes.  Thanks!
