### ISSUE TITLE
HttpClient requests - improve header parsing perf (when TryAddWithoutValidation)

### ISSUE THREAD

**Issue by Rodrigo-Andrade** [dotnet/corefx#39835]
Today most of the cpu time of my requests are parsing headers before sending the actual request:

![image](https://user-images.githubusercontent.com/1174384/62001171-771b5480-b0c0-11e9-85a1-e8cbcf90be93.png)

Any guidance to improve this? I'am not doing anything fancy like sending 30+ headers.

**Comment by Rodrigo-Andrade** [comment]
This is dotnetcore 3.0 preview 7

**Comment by stephentoub** [comment]
Where do you expect the majority of CPU time to be spent?

**Comment by Rodrigo-Andrade** [comment]
Parsing the response i guess? Most of those headers don't need to be re-validated at each request. Today there is no mechanism for me to bypass this, at least that i know of.

**Comment by Rodrigo-Andrade** [comment]
like:
![image](https://user-images.githubusercontent.com/1174384/62003454-7e0c8c00-b0ed-11e9-90ce-9baa9016a318.png)

Why does it need to `GetAuthenticationLength`? I added it with the `TryAddWithoutValidation` method, but it seems it just delays it?

**Comment by karelz** [comment]
Triage: Can we avoid parsing headers before sending?

**Comment by stephentoub** [comment]
> Most of those headers don't need to be re-validated at each request. Today there is no mechanism for me to bypass this, at least that i know of.

Have you added the headers you're sending in every message into HttpClient.DefaultRequestHeaders instead of manually putting them into each message?  If so, you're still seeing them getting re-validated on every request?

**Comment by Rodrigo-Andrade** [comment]
Most are not statically know, some diagnostics headers, some are re-passing headers to other services.

**Comment by karelz** [comment]
@Rodrigo-Andrade I am not sure I fully understand -- do you have a small repro demonstrating what you want / need? That would be easiest way to clarify ... Thanks!

**Comment by Rodrigo-Andrade** [comment]
I have something like this: https://github.com/aspnet/AspLabs/blob/master/src/Proxy/src/ProxyAdvancedExtensions.cs#L57

But the point is, when i already know that a header is valid, i still need to parse it, and that parse is usually not cheap. 

If the header is a "know header ", i might be paying even more (like the authorization header). It would be really nice to have an api that i can say: just use this as is. 

The TryAddWithoutValidation api looked like that, but after profiling it was a surprise to see it still parses it all the way.

Sory if my poor English is getting in the way.

**Comment by stephentoub** [comment]
> The TryAddWithoutValidation api looked like that

@davidsh, is it expected that TryAddWithoutValidation defers rather than removes the validation? Would it make sense when we enumerate the headers internally to write out that we don't force validation?

**Comment by davidsh** [comment]
>@davidsh, is it expected that TryAddWithoutValidation defers rather than removes the validation? Would it make sense when we enumerate the headers internally to write out that we don't force validation?

The intent of the API was to add the header string as-is to the collection without validation. And following that, the header would be written to the wire as-is.

**Comment by stephentoub** [comment]
> The intent of the API was to add the header string as-is to the collection without validation. And following that, the header would be written to the wire as-is.

We're definitely not doing that today.  So it sounds like that's the bug here.

**Comment by stephentoub** [comment]
@Rodrigo-Andrade, can you please share a repro that manifests this?  I'm interested specifically in the headers you're setting.

**Comment by Rodrigo-Andrade** [comment]
Sure, ill  try to make a repro later today.

**Comment by stephentoub** [comment]
Thanks.  Even just a list of key/value pairs would be fine.  I'd like to validate a potential fix.

**Comment by Rodrigo-Andrade** [comment]
repro is here: https://github.com/Rodrigo-Andrade/HeaderParsingRepro

this is how the tracing looks like: 

![image](https://user-images.githubusercontent.com/1174384/66350835-abb65280-e932-11e9-92b9-f2d2ca9e20a8.png)
