### ISSUE TITLE
ODBC EntityFrameworkCore database provider

### ISSUE THREAD

**Issue by tb-mtg** [dotnet/corefx#39832]
Now that ODBC is included in .Net Core 2.2 are there any plans to support this and an EntityFrameworkCore provider?

If there are no plans what would be the recommendation to implementing one or are there any known working implementations that could be used?

**Comment by danmosemsft** [comment]
@divega  ?

**Comment by divega** [comment]
@tb-mtg,

1. The most complex parts of an EF Core provider are the ones that generate SQL, and those tend to be very specialized for the target database sever. Given this, there isn’t such thing as an ODBC EF Core provider that works with any database.

2. It should be possible to build a base EF Core provider based on Microsoft.EntityFrameworkCore.Relational that leverages System.Data.Odbc for database connectivity. This could help a bit when building providers for databases for which ODBC drivers exist but ADO.NET provider aren’t available, let’s say on .NET Core, or on a specific OS. However, so far this hasn’t happened enough for anyone to be motivated to build it.

I would like to hear what exactly you have in mind such provider would solve.
