### ISSUE TITLE
Design mismatch between Utf8JsonWriter and ASP.NET Core's no sync IO default policy

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#39837]
It seems fairly natural to create a Utf8JsonWriter around an ASP.NET Core context.Response.Body Stream, as a way of easily writing out a response JSON payload.  However, when Utf8JsonWriter is used in this manner, any WriteXx call could end up doing a synchronous Flush on the Stream, yet by default ASP.NET Core prohibits synchronous I/O on the response stream.  This mismatch would seem to make it really easy to hit unexpected failures.

Have I misunderstood something?

cc: @ahsonkhan, @davidfowl

**Comment by davidfowl** [comment]
I didn't realize that Grow writes to the Stream...

**Comment by davidfowl** [comment]
You can easily switch to the `BodyWriter` and it would buffer appropriately 😄

**Comment by stephentoub** [comment]
It's wrong to be that a) these two ctors behave differently, and b) there's no way to avoid sync I/O when using Stream.

I think Grow needs to be changed to not write or flush the underlying stream.

**Comment by davidfowl** [comment]
Yea I don’t disagree, it should be possible to avoid all sync IO. I thought that was the point of having flush and flush async

**Comment by ahsonkhan** [comment]
> I think Grow needs to be changed to not write or flush the underlying stream.

I am trying to think back to why Grow initially wrote to the underlying stream. It may have been to reduce buffer grows in the stream case, but I see why that can cause an issue. Let me double check and make sure there wasn't some other side effect of doing this.

> It's wrong to me that a) these two ctors behave differently, and b) there's no way to avoid sync I/O when using Stream.

Makes sense to me. I am fine with changing it.

**Comment by ahsonkhan** [comment]
> any WriteXx call could end up doing a **synchronous Flush on the Stream**, yet by default ASP.NET Core prohibits synchronous I/O on the response stream

> I think Grow needs to be changed to not write or flush the underlying stream.

Just to clarify, where is WriteXx/Grow flushing the stream? It writes to the stream, but it doesn't flush it. I understand that doing either goes against the "no sync IO policy".

**Comment by stephentoub** [comment]
> where is WriteXx/Grow flushing the stream?

I meant "flush to" or "write on".

**Comment by GSPP** [comment]
`Utf8JsonWriter.Flush` flushes the underlying stream. I think this behavior should be decoupled from flushing the buffers of `Utf8JsonWriter`. I might want to flush the writer but not the stream.

For example, `FileStream.Flush` calls into the kernel which is not necessarily desired.

Maybe add a parameter:

    void Flush(bool flushStream = false)

**Comment by stephentoub** [comment]
> I think this behavior should be decoupled from flushing the buffers of Utf8JsonWriter

Please open a separate issue. It's distinct from this one.

**Comment by GSPP** [comment]
Right, I opened https://github.com/dotnet/corefx/issues/40011.

**Comment by ahsonkhan** [comment]
> It's wrong to me that a) these two ctors behave differently, and b) there's no way to avoid sync I/O when using Stream.

Regarding (a), note that the semantics of `BytesPending`/`BytesCommitted` have to be different between IBW and Stream modes because of the underlying by-design differences in the contract of the two output sinks. I am not sure what the `Utf8JsonWriter` can do about those. Presumably, @stephentoub, you are OK with those differences (and it is only (a)/(b) together that was concerning).

**Comment by ahsonkhan** [comment]
Re-opening until fixed in release/3.0

**Comment by ahsonkhan** [comment]
Fixed in 3.0 by https://github.com/dotnet/corefx/pull/40420
