### ISSUE TITLE
System.Threading.Channels - Concurrent Stack

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/corefx#39841]
It looks like System.Thread.Channels uses a ConcurrentQueue<T> under the hood.  It would be really great it it could also use a ConcurrentStack<T>.  Are there any chances a creation parameter could be added that lets me use a stack instead?

**Comment by tarekgh** [comment]
CC @stephentoub

**Comment by tarekgh** [comment]
@TonyValenti what exactly the issue you are trying to solve here?

**Comment by TonyValenti** [comment]
@tarekgh @stephentoub 
We have a codebase that we're wanting to port to channels.  Here's what it does currently:

1. Take a large dataset (10M+ IDs)  and break it down into standardized chunks (200 elements each)
2.  The chunks are fed into a concurrent stack.
3.  We pop a chunk off the stack and feed it to a third party.
4.  Occasionally the third party will return "error" for the batch and we get no results for any of the 200 elements.  When this happens we split the batch into smaller batches and push the smaller batches back onto the stack, preserving the order.
4.  Eventually we find the element that was causing the error and log some data about it.

The order that we process items is important which is why we currently use a stack instead of a queue.

**Comment by stephentoub** [comment]
> The order that we process items is important

I'm struggling to understand this part.  If you're pushing items into the concurrent stack non-concurrently with the consumer popping, then you wouldn't need a concurrent stack and could just use a stack.  If you're pushing items into the concurrent stack concurrently with the consumer popping, then you are very likely going to process items out of order already, e.g. thread 1 pushes item A then B then C, thread 2 pops C, thread 1 pushes D, thread 2 pops D then A then B, so thread 2 has processed the items in the order C D A B which doesn't match either a forwards or backwards ordering of the elements as produced by thread 1.  Can you elaborate?

**Comment by TonyValenti** [comment]
@stephentoub Thinking through this a little bit more, I think we have to keep certain aspects of the stack.
