### ISSUE TITLE
Build fails with 'error MSB3073' when run from folder containing a space

### ISSUE THREAD

**Issue by PRIMETSS** [dotnet/corefx#39840]
**Reproduce:**
Clone corefx repo into a folder, eg d:\DATA\MY GitHub\corefx

Build FAILED Error MSB3073: when it attempts to build src\System.Runtime.CompilerServices.Unsafe\src\System.Runtime.CompilerServices.Unsafe.ilproj

`C:\Users\PaulFarrand\.nuget\packages\microsoft.net.sdk.il\5.0.0-alpha1.19373.2\targets\Microsoft.NET.Sdk.IL.targets(101,5): error MSB3073: The command "D:\DATA\My GitHub\corefx\artifacts\toolset\ilasm\ildasm "D:\DATA\My GitHub\corefx\artifacts\bin\ref\netcoreapp\System.Runtime.CompilerServices.Unsafe.dll" /OUT="D:\DATA\My GitHub\corefx\artifacts\obj\System.Runtime.CompilerServices.Unsafe\netcoreapp-Debug\/System.Runtime.CompilerServices.Unsafe.ref.il"" exited with code 9009. [D:\DATA\My GitHub\corefx\src\System.Runtime.CompilerServices.Unsafe\src\System.Runtime.CompilerServices.Unsafe.ilproj]`

**WorkAround**
Rename folder to D:\DATA\MyGitHub 
Builds sucessfully

Ive spent about 2 days trying to locate the what I believe is a miss formatted \OUT="...." path
That contains a forward 'slash' at **Debug\\/System.Runtime**

`/OUT="D:\DATA\My GitHub\corefx\artifacts\obj\System.Runtime.CompilerServices.Unsafe\netcoreapp-Debug\/System.Runtime.CompilerServices.Unsafe.ref.il"`

Ive not been able to find it in the build scripts, anyone with better knowledge able to give clues?
Just found this that seems similair in coreclr
[https://github.com/dotnet/coreclr/pull/21819](https://github.com/dotnet/coreclr/pull/21819)

**Comment by danmosemsft** [comment]
This line
https://github.com/dotnet/coreclr/blob/master/src/.nuget/Microsoft.NET.Sdk.IL/targets/Microsoft.NET.Sdk.IL.targets#L84
should probably be `<_IldasmCommand>"$(_IlasmDir)ildasm"</_IldasmCommand>`

You could try editing `C:\Users\PaulFarrand\.nuget\packages\microsoft.net.sdk.il\5.0.0-alpha1.19373.2\targets\Microsoft.NET.Sdk.IL.targets` to confirm this.

**Comment by PRIMETSS** [comment]
Thanks, makes sense I couldn't find it in corefx
I did try the manual rename from console and was a bit baffled at first as couldnt get ildasm.exe to report anything back.
But just rechecked as the info you given helped.
It seems with or without the '\/' in the OUT="" option being sent to ildsam actually works! I was expecting it to return error with the extra '/' in the path, but both
```
/OUT="D:\DATA\My GitHub\corefx\artifacts\obj\System.Runtime.CompilerServices.Unsafe\netcoreapp-Debug\/System.Runtime.CompilerServices.Unsafe.ref.il"
or 
/OUT="D:\DATA\My GitHub\corefx\artifacts\obj\System.Runtime.CompilerServices.Unsafe\netcoreapp-Debug\System.Runtime.CompilerServices.Unsafe.ref.il"
```
Return Error/Exit Code '0'
`echo Exit Code is %errorlevel%`
And confirmed get the disassembled System.Runtime.CompilerServices.Unsafe.ref.il in artifacts\obj\...

So from this its not the actual extra '/' causing ildsam.exe to exit with error but is the whole line being interpreted incorrectly. Which sort of was my original thought, but couldn't find where this is.
I must admit I'm baffled how 'Microsoft.NET.Sdk.IL.targets' in coreclr is affecting corefx 'build'

**Comment by PRIMETSS** [comment]
Seems above has resolved those issues when building corefx with folder with a space.
But seems each 'fix' uncovers more issues later in the build.

Im stumped on this (hope last!) one '--baseline" in 
[https://github.com/dotnet/corefx/blob/master/src/shims/ApiCompat.proj](https://github.com/dotnet/corefx/blob/master/src/shims/ApiCompat.proj)

Line 90++
` <!-- TODO: Once the repo targets netstandard2.1, have this instance of APICompat run against` `NetStandard21RefPath -->`
`   <Exec Command="$(_ApiCompatCommand) &quot;$(NetStandardRefPath.TrimEnd('\/'))&quot; --baseline &quot;$(ApiCompatNSBaselineFile)&quot; @&quot;$(ApiCompatResponseFile)&quot;"`
`          CustomErrorRegularExpression="^[a-zA-Z]+ :"`
`          StandardOutputImportance="Low"`
`          IgnoreExitCode="true"`
`    >`
`      <Output TaskParameter="ExitCode" PropertyName="ApiCompatExitCode" />`
`    </Exec>`

`    <Error Condition="'$(ApiCompatExitCode)' != '0'" Text="ApiCompat failed comparing` `netstandard to $(TargetGroup)" />`

![image](https://user-images.githubusercontent.com/11331370/62050305-29355680-b250-11e9-9edd-b0308a785c71.png)

Anyone able to chime in an offer some suggestions please? @danmosemsft ? ta

**Comment by danmosemsft** [comment]
Have you made any changes other than the one I suggested?

**Comment by PRIMETSS** [comment]
Yes, I made that change and it helped, but a few more issue found in that same <Exec Command...?> line as above (edited)
Also a few more locations in same Targets file (above).

And then found more issues after in other scr files (above). **Which Im working through**

ps: Just did a build of coreclr (as I believe Microsoft.NET.Sdk.IL.targets' is in that Repo not CoreFX) and it too seems to have same issues building with spaces in folder.
I think it might be best to do a PR for each issue-error? Whats your thoughts? As looks like this might be on-going, as Ive found at least another 3-6 issues and its across multiple Repo's so

**Comment by PRIMETSS** [comment]
Found it

Source: corefx\src\shims\ApiCompat.proj
Modified below below
`<Exec Command="$(_ApiCompatCommand) &quot;$(_netStandard21OnlyRef)&quot;` `@&quot;$(ApiCompatResponseFile)&quot; $(_netStandard21BaselineModifer)` `&quot;$(ApiCompatNSOnlyBaselineFile)&quot;"` 
`      CustomErrorRegularExpression="^[a-zA-Z]+ :"`
`      StandardOutputImportance="Low"`
`      IgnoreExitCode="true"`
`      >`
      <Output TaskParameter="ExitCode" PropertyName="ApiCompatExitCode" />
    </Exec>

Performed Rebuild of corefx:
Build Succeeded

**Comment by danmosemsft** [comment]
I suggest one PR per repo. Note some tools those repos use come  from the dotnet/arcade repo.

**Comment by ViktorHofer** [comment]
Closing as this was addressed in a the linked commit.
