### ISSUE TITLE
System.Drawing.dll is missing dependencies in .netcore 3.0 preview 7.

### ISSUE THREAD

**Issue by richardmccavery** [dotnet/corefx#39845]
System.Drawing.dll is missing dependencies in .netcore 3.0 preview 7.

![Preview7Deps](https://user-images.githubusercontent.com/53267677/61802674-c8111b80-ae28-11e9-9647-c1193d79dd65.png)

# General

Trying to build an application which previously compiled perfectly with Preview 6.

Compilation complains that a reference to System.Drawing.Common.dll is required, however this appears to be missing.  Also checking with dotPeek (screenshot attached), you can see the missing assembly references.

I am unable for example to create an instance of the Bitmap class.

According to online docs, this is available in Preview 6, and shows the implementation being in System.Drawing.Common.dll.

I will have to revert to Preview 6 until some suggestion as to how to proceed is forthcoming.

Thanks in advance and keep up the great work.

Some notes on where we are with native compilation / AOT etc. and what currently works in Preview7 would also be appreciated in the release notes.

**Comment by ericstj** [comment]
System.Drawing.dll is supposed to be missing dependencies.  It's only a facade to unify the desktop assembly identity with .NETCore.

One thing that changed in Preview7 was the way the SDK references assemblies.  It is now honoring UseWPF and UseWindowsForms with respect to dependencies and System.Drawing.Common is classified as Windows Forms and is not available by default unless a project specifies `UseWindowsForms`.

See https://github.com/dotnet/corefx/issues/38682#issuecomment-503733336.

@dsplaisted @nguerrera @KathleenDollard - it's not very intuitive to know that one has to add one of these properties to get more references.  Is there anything planned to make this easier to understand?

**Comment by ericstj** [comment]
Closing this out as the dependencies of System.Drawing.dll are to be expected and the change that happened here is related to what is referenced by default which is not defined in CoreFx.  @dsplaisted suggested here https://github.com/dotnet/corefx/issues/38682#issuecomment-503757380 that if you'd like to have a discussion about what's available by default for WPF applications you open an issue in the WPF repo.
