### ISSUE TITLE
System.Net.NameResolution.Functional.Tests have few tests that constantly fail on local machines?

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/corefx#39859]
Similar: #24355, though the platform and the failure cause is different. 

### Environment

  - Windows 10 Home 1903, Build 18362.239, Korean, x64
  - Intel Core i5-4570 CPU
Can't repro on my laptop (Windows 10 Pro Insider Preview, Fast ring, Build 18945, x64).

### Failing tests
```
System.Net.NameResolution.Functional.Tests
┗ System.Net.NameResolution.Tests
  ┗ GetHostAddressesTest
    ┗ DnsBeginGetHostAddresses_BadName_Throws
  ┗ GetHostByNameTest
    ┗ DnsObsoleteBeginGetHostByName_BadName_Throws
    ┗ DnsObsoleteGetHostByName_BadName_Throws
  ┗ GetHostEntryTest
    ┗ DnsBeginGetHostEntry_BadName_Throws
    ┗ DnsGetHostEntry_BadName_Throws
    ┗ DnsGetHostEntry_UnknownPunicodeHost_HostNotFound
    ┗ DnsGetHostEntry_UnknownUnicodeHost_HostNotFound
  ┗ ResolveTest
    ┗ DnsObsoleteBeginResolve_BadName_Throws
    ┗ DnsObsoleteResolve_BadName_Throws
```
All of the tests above fail with Assert.Throws not throwing:
```
Message: 
    Assert.Throws() Failure
    Expected: typeof(System.Net.Sockets.SocketException)
    Actual:   (No exception was thrown)
```
Cloned straight from the master branch (latest commit is 6737565). No matter how many times I run the tests, they always seem to fail; haven't looked into the test codes yet. They do not seem to fail when ran on CI pipelines. Wonder what the reason is?

**Comment by stephentoub** [comment]
Who's your internet provider?

If you open a browser and browse to a non-existent domain, do you get a default page from your provider?

**Comment by Gnbrkm41** [comment]
It's a Korean provider called SK Broadband.

I don't get such a page; I could try changing my DNS resolver though.

**Comment by stephentoub** [comment]
Generally the reason you wouldn't see an exception in these cases is because your internet provider's DNS server is returning the address of some default site they own that will put up a message like "The site you requested could not be found" or something similar.  From the client's perspective, the DNS request was successful.

**Comment by Gnbrkm41** [comment]
Oh, looks like changing the DNS provider have solved it 😶 

Closing the issue. Thanks, @stephentoub!
