### ISSUE TITLE
Monad classes in C#

### ISSUE THREAD

**Issue by giorgiozoppi** [dotnet/corefx#39851]
Feature request: Support for some basic monads as maybe, either monads directly in the corefx.
This will enable more functional domain and concurrent domain application. Several libraries are available but it is still missing an official one.

An example possible will be:

```c#
 public Either<EmailStatus, EmailMessage> Validate(EmailMessage message)
        {
            List<EmailMessage> listMessages = new List<EmailMessage>() {message};
            var filterItemCount = listMessages.Where(msg => HasValidFrom(msg))
                .Where(msgTo => HasValidContacts(msgTo.EmailTo))
                .Where(msgCc => HasOptionalValidContacts(msgCc.EmailCarbonCopy))
                .Where(msgBcc => HasOptionalValidContacts(msgBcc.EmailCarbonCopy)).Count();

            return (filterItemCount > 0)
                ? Either.Right<EmailStatus, EmailMessage>(() => message)
                : Either.Left<EmailStatus, EmailMessage>(() => CreateMailStatus(message));

        }
```

This is a logic for email header validation.

**Comment by scalablecory** [comment]
There's a pretty popular issue on the C# repo for this: https://github.com/dotnet/csharplang/issues/399

**Comment by danmosemsft** [comment]
@giorgiozoppi C# language requests should go into the dotnet/csharplang repo. I don't have the power to move issues there, so I'll close this and let you decide whether to add to that existing issue or open a new one. Thanks for the suggestion!

**Comment by MgSam** [comment]
Erm- despite the wording of the title, I don't think he's asking for a language feature. I think he's asking for a library in the BCL. Please correct me if I'm misreading.

**Comment by scalablecory** [comment]
Agreed @MgSam

**Comment by giorgiozoppi** [comment]
I am asking for a library. Sorry for the misleading title. We have just a lot of features in this language. For example this library could be useful as well in TPL.DataFlow and since it will be lazy, In Haskell  some monads classes are in the  “Standard Prelude". It will be nice to have System.Functional.Monad namespaces that it will might include:
- Either
- MayBe (or a stronger variant of NullOptional)
- Reader<E,T>
- Writer 
- IO<T>
This will help a lot of user to create an immutable business logic.

**Comment by garfbradaz** [comment]
I still dont know what a Monad is 😅

**Comment by JarnoNijboer** [comment]
> I am asking for a library. Sorry for the misleading title. We have just a lot of features in this language. For example this library could be useful as well in TPL.DataFlow and since it will be lazy, In Haskell some monads classes are in the “Standard Prelude". It will be nice to have System.Functional.Monad namespaces that it will might include:
> 
> * Either
> * MayBe (or a stronger variant of NullOptional)
> * Reader<E,T>
> * Writer
> * IO
>   This will help a lot of user to create an immutable business logic.

If you want Functional types, maybe you could use the `FSharp.Core` package?

**Comment by giorgiozoppi** [comment]
Makes sense.

**Comment by giorgiozoppi** [comment]
I would close this issue.

**Comment by MaceWindu** [comment]
if you are looking for library, you should check this one https://github.com/louthy/language-ext
