### ISSUE TITLE
HTTP2: failure with 0-length header strings

### ISSUE THREAD

**Issue by scalablecory** [dotnet/corefx#39873]
0-length string literals in header names cause the HPACK decoder to fail -- it just keeps reading a header name until it exhausts the string array or until it reaches end of headers.

It's not clear what the behavior here should be... clearly a 0-length header name is odd, but the spec as far as I can tell doesn't actually disallow it. If we do disallow it, we should fail fast with a HPackException rather than letting things run out of control.

**Comment by scalablecory** [comment]
@geoffkizer @wfurt @stephentoub thoughts on behavior? Or, do you see something disallowing this in the spec?

**Comment by geoffkizer** [comment]
As far as I know, empty header values are perfectly legal. So we should fix this and allow them.

The best reference here is probably the HTTP/1.1 RFC. HTTP2 implicitly relies on this.

**Comment by geoffkizer** [comment]
Ah wait, we're talking 0 length header *names*, not *values*? 

This is not allowed. Per RFC 7230, a header name is a token, and a token must consist of at least one character.

We should obviously not hang or whatever, but we should disallow this.

**Comment by karelz** [comment]
Why is it not interesting for 3.0?
What happens when malicious server sends it?

**Comment by scalablecory** [comment]
@karelz HttpClient will throw an exception either way. The change here is to make it a consistent one.

**Comment by karelz** [comment]
Thanks @scalablecory , will it be compat problem in 5.0?

**Comment by davidsh** [comment]
>Why is it not interesting for 3.0?

I think we should fix this for 3.0.

**Comment by karelz** [comment]
Reopening for tracking the fix in 3.0 - @scalablecory please work with @davidsh on business justification in the template (for smooth process). Thanks!

**Comment by scalablecory** [comment]
Fix has been merged into 3.0; closing.
