### ISSUE TITLE
process not sharing file for RW

### ISSUE THREAD

**Issue by foxjazz** [dotnet/corefx#39908]
https://github.com/foxjazz/TestFileReaderWriter.git

clone  run windows 10

**Comment by stephentoub** [comment]
What is the issue you're trying to raise?

**Comment by foxjazz** [comment]
![image](https://user-images.githubusercontent.com/867496/62218266-56c1f300-b369-11e9-90d1-718ca4ac967e.png)

This is what happens.

**Comment by stephentoub** [comment]
And why do you believe that's a bug in corefx?

**Comment by foxjazz** [comment]
I am pretty sure System.IO is part of corefx, and accessing a shared file shouldn't be an issue. But could be wrong and breaking some unpublished rule.

**Comment by stephentoub** [comment]
> accessing a shared file shouldn't be an issue

It depends on how the file was opened and on how it's trying to be opened.

Can you please share a minimal repro (not an entire project on GitHub) that demonstrates the problem?

**Comment by foxjazz** [comment]
https://github.com/foxjazz/TestFileReaderWriter.git

**Comment by foxjazz** [comment]
Narrowed error down to file create is somehow retaining a file lock. Removed File.create and looks like its working.

**Comment by stephentoub** [comment]
> File.Create

It creates the file and returns a FileStream for the open file. You need to dispose that FileStream.
