### ISSUE TITLE
BitArray.CopyTo(Array, int) seems broken

### ISSUE THREAD

**Issue by MichaelL79** [dotnet/corefx#39929]
# BitArray.CopyTo(Array, int) seems broken

When using BitArray.CopyTo() in .NET Core 3 it seems the bits are always copied to the last position of the provided array.

# General

My setup is a .NetStandard 2 class library with a method that contains a BitArray.CopyTo(Array, int). If I use this library from within a WPF application using .Net 4.7.2 everything works as expected. When I use the exact same library from within a .NET Core 3 application (Console or WPF) always the last byte of the array is overwritten and the index parameter is ignored. Example:

```
bool[] directionBools = { true, true, true, true };
bool[] levelBools = { false, false, false, true };
byte[] byteHolder = new byte[2];
BitArray directionBits = new BitArray(directionBools);
BitArray levelBits = new BitArray(levelBools);

directionBits.CopyTo(byteHolder, 0);
levelBits.CopyTo(byteHolder, 1);
```

In .NET 4.7.2 and earlier this would result in an array 0F-08. In .NET Core 3 it results in an array 00-08 as the second CopyTo overwrites the 0F that was wrongly copied to index 1 instead of index 0.  If you increase the byteHolder length to eg. 5. It would result in 0F-08-00-00-00 in 4.7.2 and 00-00-00-00-08 in Core 3.

Best regards
Michael

**Comment by Clockwork-Muse** [comment]
Behavior confirmed.... 

[But we have a test to protect against this, that passes!?](https://github.com/dotnet/corefx/blob/30ca4113ed07fc78060a0c9d3f95eee4fe8f8ee3/src/System.Collections/tests/BitArray/BitArray_GetSetTests.cs#L230-L313) (Verified under debug of test)..... what?

I know there also used to be a copy distributed along with coreclr, although that's long gone.

**Comment by jkotas** [comment]
Regression introduced by @ahsonkhan 's change https://github.com/dotnet/corefx/pull/33367

**Comment by ericstj** [comment]
@ahsonkhan can you provide an update here?  Will a fix make it in for Preview9?

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/dotnet/corefx/pull/40442 for release/3.0 and in https://github.com/dotnet/corefx/pull/40441 for master.
