### ISSUE TITLE
Clean up NRE in SmtpConnection.Abort

### ISSUE THREAD

**Issue by scalablecory** [dotnet/corefx#39925]
When we initialize a connection, it's possible for `_tcpClient.Connect()` to fail and for `_networkStream` to never get assigned:

https://github.com/dotnet/corefx/blob/175c4b7467f4da173c732f9aaf95882b3c426665/src/System.Net.Mail/src/System/Net/Mail/SmtpConnection.cs#L100-L104

Then, during `Abort()`, we attempt to `_networkStream.Dispose()` which throws a `NullReferenceException`.

https://github.com/dotnet/corefx/blob/175c4b7467f4da173c732f9aaf95882b3c426665/src/System.Net.Mail/src/System/Net/Mail/SmtpConnection.cs#L172-L187

The NRE is caught eventually, and ignored, in `SmtpClient.Abort()`:

https://github.com/dotnet/corefx/blob/d77ce06711bbf4c91eaac5690a709dc9c352e720/src/System.Net.Mail/src/System/Net/Mail/SmtpClient.cs#L1036-L1045

We should update to not cause an NRE. Found in #39732 .

**Comment by jbhensley** [comment]
The fix seems trivial: `_networkStream?.Close()`, but it doesn't look like there's a good way of unit testing without using reflection to access internal/private members/methods. Should we be concerned about adding a test for this?
