### ISSUE TITLE
Overload of Directory.DeleteDirectory("path", true) that deletes what it can and leaves rest

### ISSUE THREAD

**Issue by yishaigalatzer** [dotnet/corefx#3993]
Whenever we have clean up code to remove directories and files, we always end up with hacks to workaround issues with readonly files, handles being temporarily held.

The is no reliable mechanism to delete the folders and files, and there is no mechanism to skip failures and report them at the end.

Which leads to poor implementations that fail on long paths, sym and hard links, and random errors.

See:
https://github.com/NuGet/NuGet.Client/pull/13 
http://stackoverflow.com/questions/329355/cannot-delete-directory-with-directory-deletepath-true

And many more random suggestions pop up on the interwebs

CC // @xavierdecoster

**Comment by RichiCoder1** [comment]
Seconded. Most ever tool I've built that has to deal with the file system has inevitably had to deal with this issue.

**Comment by JeremyKuhne** [comment]
One of the things I've already done is have it handle file names that it used to choke on (trailing spaces, etc.). That might be the issue from the linked stackoverflow.

In my own path library I have the ability to specify an attribute filter. It won't do anything with any file/directory that hit the filter (including walking into matching directories). How useful would that functionality be?

**Comment by yishaigalatzer** [comment]
@JeremyKuhne it will be useful for a filter to allow for decision making or even more actions (like remove readonly, or make an extra cleanup call depending on your app, you might be able to unlock a file that is held is one of your services). 

It will be also be important to make sure such a filter doesn't get into longpath issues.

**Comment by JeremyKuhne** [comment]
Have you looked at what the shell provides from a design perspective? (IFileOperation)

https://msdn.microsoft.com/en-us/library/windows/desktop/bb775771(v=vs.85).aspx

Not suggesting that you P/Invoke, but wondering if we might be better served by a library that provides a similar model. On a related note, some are asking for Interfaces in general to allow easier testing #312/#2022.

**Comment by lstefano71** [comment]
At CppCon 2015 Niall Douglas explained what is the correct algorithm to delete a directory tree on NTFS and why the naive algorithm is wrong. Here's the relevant bit of his talk: https://youtu.be/uhRWMGBjlO8?t=8m53s
(The algorithm for Posix is just before).
Here's the PDF with the slides: https://github.com/CppCon/CppCon2015/blob/master/Tutorials/Racing%20the%20Filesystem/Racing%20the%20Filesystem%20-%20Niall%20Douglas%20-%20CppCon%202015.pdf

I may be wrong, but the code in https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System/IO/Win32FileSystem.cs as of today seems to be an implementation of the wrong way to go about it.

**Comment by karelz** [comment]
We can't change behavior due to compat. But if someone proposes new API, that should be doable.

**Comment by karelz** [comment]
Triage: Adding API adds cost. While potentially useful, there seems to be limited interest (3 people commenting). Closing for now, until there is more interest.
