### ISSUE TITLE
How to get startup path from assembly in Single Exe File

### ISSUE THREAD

**Issue by OmidID** [dotnet/corefx#39948]
I don't know is it a bug or not.
After I published my application using this command `dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true` I'm not able to get the correct startup address from the code below:
```cs
var executablePath = Path.GetFullPath(typeof(Program).Assembly.Location);
```
The output is in the temp directory and it's dll file. Something like this:
```C:\Users\MyUser\AppData\Local\Temp\.net\MyApp\po5w3wnz.iiu\MyApp.dll```

**Comment by khellang** [comment]
I guess this is because it's basically embedding the DLL in a generated assembly and extracting it to a temp location before loading the DLL. Seems like it's a known issue; https://github.com/dotnet/coreclr/issues/20287#issuecomment-504287272

**Comment by Symbai** [comment]
It's not an issue rather a breaking change if you come from .NET Framework and dot net team suggests to use GetModuleFileNameW API is Process.GetCurrent().Mainmodule.Filename.

**Comment by OmidID** [comment]
Yea, this is what I already did in my code. I created this issue because I wasn't sure the assembly location should be the execution file or extracted one.

**Comment by khellang** [comment]
> I wasn't sure the assembly location should be the execution file or extracted one.

Well, you did ask for the location of the assembly containing `Program`, which is the extracted assembly. If you want the executing assembly, you might want to use on of the static `Assembly` methods.
