### ISSUE TITLE
Issue with IAsyncEnumerable and GetEnumerator

### ISSUE THREAD

**Issue by SebHonorine** [dotnet/corefx#39946]
Describe what is not working as expected:
Preparing some documentation on .Net Core 3 I'm trying to update some projects from 2.1 to 3.0
I've done something similar to this:
https://stackoverflow.com/questions/40476233/how-to-mock-an-async-repository-with-entity-framework-core

before updating my csproj:
![image](https://user-images.githubusercontent.com/8523321/62293742-3c564b00-b437-11e9-9eca-88f265693b94.png)

After:
![image](https://user-images.githubusercontent.com/8523321/62293764-4a0bd080-b437-11e9-8dc3-71b2aaaa1bb6.png)

seems like now when going into the metadata I've seen that it went from System.Interactive.Async to System.Runtime.
no more GetEnumerator in the IAsyncEnumerable but getAsyncEnumerator which make a little sense. I tried to replace in my code with getAsyncEnumerator but i get the error
"an exception tree may not contain a call or invocation that uses optional arguments"

I came across this issue : #14239
But, not sure if it is related

Don't know where to go from there. been a day since I m stuck. Sorry if its stupid :) and thanks

Steps to reproduce
update TargetFramework to 3.0

look where you where doing a IAsyncEnumerable.getEnumerator

Further technical details
EF Core version:"Microsoft.EntityFrameworkCore" Version="3.0.0-preview7.19362.6"

**Comment by stephentoub** [comment]
> an exception tree may not contain a call or invocation that uses optional arguments

GetAsyncEnumerator takes an optional CancellationToken argument.  Does this error go away if you explicit pass `default` to the GetAsyncEnumerator call?

**Comment by SebHonorine** [comment]
thanks.Seems ok now. . . i ve tried "null" but not default.
have some more implementation  to do now it wants to go trhough 
        TResult IAsyncQueryProvider.ExecuteAsync<TResult>(Expression expression, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

**Comment by stephentoub** [comment]
> Seems ok now

Great.
