### ISSUE TITLE
Add tests for expression interpreter

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#3995]
Cross-check expression interpreter against expression compiler by using a catalog of expressions.

**Comment by VSadov** [comment]
@bartdesmet - is this issue still tracking anything in particular?

**Comment by JonHanna** [comment]
While there are still some small gaps in coverage generally, I think the mechanism for testing both types of compilation for all relevant tests mean this can be closed.

**Comment by stephentoub** [comment]
Addressed.
