### ISSUE TITLE
Enable SDL tool runs in our official builds

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#39959]
Follow steps outlined here: https://github.com/dotnet/arcade/blob/master/Documentation/HowToAddSDLRunToPipeline.md 

Work with @sunandabalu for feedback / issues on the process.

We should do this first in master and see what it finds then decide what needs to be ported to 3.0.

@Anipik this might be something you can pick up that's more urgent than the 5.0 versioning work.
@safern this could collided with the pipeline stuff you have assigned.

**Comment by Anipik** [comment]
Thanks @ericstj I will take a look and start on this.

**Comment by safern** [comment]
@Anipik let’s sync after lunch as this might collide with the refactor I’m doing.

**Comment by Anipik** [comment]
Sure

**Comment by safern** [comment]
Spoke with @Anipik offline and this comes as part of the `post-build.yml` stuff and then we should enable it through a parameter. In order for to solve: https://github.com/dotnet/corefx/issues/39802 -- I'm bringing that template to the build, so I will take this over as it is just adding an extra parameter to what I'm doing.
