### ISSUE TITLE
"System.Management currently is only supported for Windows desktop applications." message when package is indirectly imported

### ISSUE THREAD

**Issue by roederja2** [dotnet/corefx#39975]
I have two netcorapp3.0 projects (with preview 7). One is my application, the other is my NUnit test project. The application project depends on the System.Management nuget package. In the test project there are tests that exercise the code that uses System.Management. If the test project does not also directly reference the System.Management nuget package I get an exception in the constructor of ManagementObjectSearcher: "System.Management currently is only supported for Windows desktop applications.". If I directly reference the System.Management package in my test project the problem goes away. This is with System.Management 4.6.0-preview7.19362.9

**Comment by ViktorHofer** [comment]
@roederja2 is it possible to provide a sample project (to repro the issue)? that would help us further triage this issue and make progress on it. thanks!

**Comment by ViktorHofer** [comment]
Moving to future as we haven't heard yet from the customer and we believe this isn't 3.0 specific.

**Comment by ericstj** [comment]
I'm guessing this NUnit not honoring the deps file.  This package has both a win-specific implementation and a RID-less implementation.  It sounds like the RID-less implementation is being chosen.  That's inconsistent with how a normal .NETCore application works.

**Comment by ViktorHofer** [comment]
@jnm2 do you know if nunit is passing the deps-file correctly to the testhost?

**Comment by jnm2** [comment]
@ViktorHofer I'm pretty sure NUnit is just doing `Assembly.Load` and assuming the BCL will automagically make everything work. Is there documentation we should follow for dynamic assembly loading on .NET Core?

/cc @rprouse @ChrisMaddock @OsirisTerje

**Comment by ViktorHofer** [comment]
you want to load the deps.json file when you load the assembly. This can be done with an AssemblyLoadContext or if you instantiate a new testhost process by passing the -deps-file runtime option host argument.

**Comment by ViktorHofer** [comment]
Closing as this seems to be an nunit issue.

**Comment by waltdestler** [comment]
@ViktorHofer I'm also having this issue, not with NUnit, but when dynamically loading my own assembly that uses System.Management. Can you please explain or link to how "This can be done with an AssemblyLoadContext"? I've spent a couple hours on Google trying to figure it out, but either there's not much info available or I don't know what I should be searching for. (I'm new to .NET Core.) Thanks!

**Comment by ViktorHofer** [comment]
Can you please open a new issue for that. Thanks.
