### ISSUE TITLE
API Proposal: Channel.QueueSize

### ISSUE THREAD

**Issue by tebeco** [dotnet/corefx#39998]
### Context
We are trying to add Monitoring/Healthchecks on the number of elements enqueued into the `Channel` internal queue
A simple read only access to the `Count` is fine in order to avoid affecting `hot path` (`Read/Write` operations).

The idea is to access it as a `Counter` / `Gauge`, a "one shot read" so that these metrics can be used/pushed to Monitoring in order to see how a system behave over time.
It could also be used to affect custom `Healthchecks` => `Degraded` or `Unhealthy` if various thresholds are being hit.

#### Workaround
We could (as of today) use things like `Interlocked.Increment()` / `Interlocked.Decrement()` anytime the `Writer` or `Reader` are affecting the `Channel` queue.
* **It directly affects the hot path⚠**
* it needs to be aware of `Bounded / Unbounded` + success of the operation.
* It only works if both Consumer and Producer can share the same reference on the counter.

### Current Api
I took a really fast look at the code (probably too fast) [here.](https://github.com/dotnet/corefx/tree/master/src/System.Threading.Channels/src/System/Threading/Channels)
As i understand it the `Channels` has [an internal `Deque` structure to hold the data](https://github.com/dotnet/corefx/blob/master/src/System.Threading.Channels/src/System/Collections/Generic/Deque.cs#L12)

### Personnal understanding
I saw that there were multiple implementations of various kind of `Channels` base on :
* `Bounded/Unbounded`
* `Single/Multiple` Producer
* `Single/Multiple` Consumer

I'm a bit lost in the code base to be honnest as i see that it uses `Deque<T>` and/or [`ConcurrentQueue<T>`](https://github.com/dotnet/corefx/blob/master/src/System.Threading.Channels/src/System/Threading/Channels/UnboundedChannel.cs#L20)
As i understand the [`Deque<T>` type already have a public `Count` property](https://github.com/dotnet/corefx/blob/master/src/System.Threading.Channels/src/System/Collections/Generic/Deque.cs#L19) that looks like what we are looking for

## Proposal
Would it be possible to add the a public property the the `Channels` class ?
I naive idea would look like :
`public int Count => _queue.Count` or `public int Count => _items.Count`
(but as i the main issue would be dedicated implementation per `Channel` "Type"

**Comment by tarekgh** [comment]
CC @stephentoub

**Comment by tebeco** [comment]
It would be amazing if it lands in `3.1` to be honest ^^ as we are waiting for `3.0` to use `signalr` / `Azure Signalr Service`
but i have not idea if and how it affect `netstandard`

**Comment by JanEggers** [comment]
@tebeco +1 from me I requested the same thing some years ago when channels have been located in corefx labs

so I guess this will not happen any time soon....

**Comment by JanEggers** [comment]
https://github.com/dotnet/corefxlab/issues/1782

**Comment by JanEggers** [comment]
https://github.com/dotnet/corefx/issues/25162

**Comment by stephentoub** [comment]
A Count property was added to ChannelReader in https://github.com/dotnet/runtime/pull/312 for issue https://github.com/dotnet/corefx/issues/30852.

**Comment by tebeco** [comment]
thx a lot ;)
