### ISSUE TITLE
building trouble: restoring packages failed

### ISSUE THREAD

**Issue by meanshe** [dotnet/corefx#40017]
Hi there,

I'm trying to build corefx managed libraries,but stuck in restoring packages. can anybody help?

=========================================================================

root@vinpc:~/Desktop/git/dotnet/corefx-3.0.0-preview6.19303.8# **./build.sh /p:BuildNative=false**
  Restore completed in 19.74 ms for /home/vincent/.nuget/packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19280.2/tools/Tools.proj.
  Tool 'coverlet.console' (version '1.5.1') was restored. Available commands: coverlet
  Tool 'dotnet-reportgenerator-globaltool' (version '4.1.6') was restored. Available commands: reportgenerator
  
  Restore was successful.
  Restore completed in 8.07 ms for /home/vincent/Desktop/git/dotnet/corefx-3.0.0-preview6.19303.8/external/netstandard/netstandard.depproj.
  Restore completed in 4.86 ms for /home/vincent/Desktop/git/dotnet/corefx-3.0.0-preview6.19303.8/external/tools/tools.depproj.
  **Failed** to download package 'System.IO.Compression.TestData.1.0.8' from 'https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/system.io.compression.testdata/1.0.8/system.io.compression.testdata.1.0.8.nupkg'.
  **Unable to read data from the transport connection: Connection reset by peer.**
    Connection reset by peer
  Failed to download package 'Microsoft.DiaSymReader.Native.1.5.0' from 'https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.diasymreader.native/1.5.0/microsoft.diasymreader.native.1.5.0.nupkg'.
  The download of 'https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.diasymreader.native/1.5.0/microsoft.diasymreader.native.1.5.0.nupkg' timed out because no data was received for 60000ms.
    Exception of type 'System.TimeoutException' was thrown.
  Failed to download package 'System.Drawing.Common.TestData.1.0.9' from 'https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/system.drawing.common.testdata/1.0.9/system.drawing.common.testdata.1.0.9.nupkg'.
  The download of 'https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/system.drawing.common.testdata/1.0.9/system.drawing.common.testdata.1.0.9.nupkg' timed out because no data was received for 60000ms.
    Exception of type 'System.TimeoutException' was thrown.
  Retrying 'FindPackagesByIdAsync' for source 'https://az774065.vo.msecnd.net/artifacts/xunit/nuget/v3/flatcontainer/microsoft.dotnet.remoteexecutor/index.json'.
  The HTTP request to 'GET https://az774065.vo.msecnd.net/artifacts/xunit/nuget/v3/flatcontainer/microsoft.dotnet.remoteexecutor/index.json' has timed out after 100000ms.
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/system.net.testdata/index.json'.
  The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/system.net.testdata/index.json' has timed out after 100000ms.
  Failed to download package 'System.IO.Compression.TestData.1.0.8' from 'https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/system.io.compression.testdata/1.0.8/system.io.compression.testdata.1.0.8.nupkg'.
  The download of 'https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/system.io.compression.testdata/1.0.8/system.io.compression.testdata.1.0.8.nupkg' timed out because no data was received for 60000ms.
    Exception of type 'System.TimeoutException' was thrown.
  Failed to download package 'Microsoft.DiaSymReader.Native.1.5.0' from 'https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.diasymreader.native/1.5.0/microsoft.diasymreader.native.1.5.0.nupkg'.
  The download of 'https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.diasymreader.native/1.5.0/microsoft.diasymreader.native.1.5.0.nupkg' timed out because no data was received for 60000ms.
    Exception of type 'System.TimeoutException' was thrown.

**Comment by ViktorHofer** [comment]
Can you please try again? Comedies 3 told me that a feed was down.

**Comment by wfurt** [comment]
no response for 20+ days. this seems like transient problem.
