### ISSUE TITLE
Sockets tests depend on "localhost" resolving to an IPv6 and an IPv4 address

### ISSUE THREAD

**Issue by pgavlin** [dotnet/corefx#4002]
This is not always the case on Linux: how the name resolves depends on the host's configuration.

**Comment by ianhays** [comment]
This is the cause of https://github.com/dotnet/corefx/issues/4829

**Comment by ianhays** [comment]
Somewhat related, but perhaps I have a misunderstanding of something here. Is it by design that:

```
Console.WriteLine(IPAddress.IsLoopback(IPAddress.Loopback.MapToIPv6()));
```

prints ```false```? It would seem to me that the Loopback mapped to IPV6 should still be treated as loopback, no? Isn't ```::ffff:127.0.0.1``` as much an IPV6 loopback as ```::1```?

This behavior is on Desktop, too.

**Comment by ianhays** [comment]
@ericeil I recall you mentioning something like this a few weeks ago at the team meeting. Did you determine the cause?

**Comment by ericeil** [comment]
> Isn't ```::ffff:127.0.0.1``` as much an IPV6 loopback as ```::1```?

I think the answer is that ```::ffff:127.0.0.1``` is a v6 address that maps to the *v4* loopback address, and so it not technically a *v6* loopback address.  It doesn't route to a v6 endpoint.

**Comment by ericeil** [comment]
Given that we haven't had an actual instance of a problem related to "localhost" assumptions in the tests, I'm closing this.

**Comment by pgavlin** [comment]
@ericeil did you try reenabling the two tests that are disabled on this bug?
https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/tests/FunctionalTests/DnsEndPointTest.cs#L251
https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs#L649

**Comment by ericeil** [comment]
Thanks, @pgavlin. No, I didn't realize there were ActiveIssues associated with this bug.  I'll give those a look.

**Comment by geoffkizer** [comment]
Unless I'm missing something, this is just a bad test and should be removed.

**Comment by stephentoub** [comment]
> Unless I'm missing something, this is just a bad test and should be removed.

Let's be careful here.  There are a bunch of tests annotated with this issue number, and I don't believe we should just blanketly delete them all.  I expect they're providing coverage for things we don't have elsewhere.  For example, this doesn't seem like a bad test that should just be deleted:
https://github.com/dotnet/corefx/blob/969d86808c24fae13ab15c636b41ebc4ed204534/src/System.Net.Sockets/tests/FunctionalTests/DnsEndPointTest.cs#L320
Rather we should fix it to not rely on this particular behavior, if this behavior is in fact problematic on Unix.

**Comment by geoffkizer** [comment]
Yes, you're absolutely right.  I spoke too quickly.

Apparently, all these DnsEndPointTests are using "localhost" as the domain name to resolve.

Unfortunately, "localhost" typically only resolves to IPv4 loopback on Unix, not both IPv4 and IPv6.  So using this for testing is problematic.

Regardless, I agree we need to fix these tests.

**Comment by steveharter** [comment]
FWIW full list of tests flagged with 4002:
```
System.Net.Sockets.Tests.DnsEndPointTest.Socket_StaticConnectAsync_Success
System.Net.Sockets.Tests.DualModeConnectToHostString.DualModeConnect_LoopbackDnsToHost_Helper
System.Net.Sockets.Tests.DualModeConnectToDnsEndPoint.DualModeConnect_DnsEndPointToHost_Helper
System.Net.Sockets.Tests.DualModeConnectAsync.DualModeConnectAsync_DnsEndPointToHost_Helper
System.Net.Sockets.Tests.DualModeConnectAsync.DualModeConnectAsync_Static_DnsEndPointToHost_Helper
```

**Comment by steveharter** [comment]
See also related issue https://github.com/dotnet/corefx/issues/13967

**Comment by davidsh** [comment]
>Yes, you're absolutely right. I spoke too quickly.
Apparently, all these DnsEndPointTests are using "localhost" as the domain name to resolve.
Unfortunately, "localhost" typically only resolves to IPv4 loopback on Unix, not both IPv4 and IPv6. So using this for testing is problematic.
Regardless, I agree we need to fix these tests.

So, is the "fix" for these tests to replace "localhost" with either/both "127.0.0.1" and/or "::1"?

**Comment by geoffkizer** [comment]
I don't think that's the right fix, no.  It kind of defeats the purpose of these tests, which (I think) is to actually test name resolution.  The fact that the only name they resolve is "localhost" is kind of lame to begin with.

It would be better to use a real DNS name here.  Of course that may introduce it's own set of problems, but if we think we can manage those, it would certainly make the tests a lot more useful.

**Comment by davidsh** [comment]
>It would be better to use some real DNS names here. Of course that may introduce it's own set of problems, but if we think we can manage those, it would certainly make the tests a lot more useful.

Managing external servers, networks or DNS entries is difficult for the CI system.

Perhaps relying on something like www.microsoft.com which has both IPV4 AND IPV6 addresses in DNS might be sufficient.

**Comment by geoffkizer** [comment]
Yeah, something like www.microsoft.com would be good.  Or www.contoso.com or something like that, depending on how that resolves.

**Comment by steveharter** [comment]
@geoffkizer do you plan on making the change soon? (or any one else)?

**Comment by geoffkizer** [comment]
> @geoffkizer do you plan on making the change soon? (or any one else)?

No.

**Comment by karelz** [comment]
Next step:
Change the 4 tests (search the code base for their name) - replace localhost with www.microsoft.com:
```
System.Net.Sockets.Tests.DnsEndPointTest.Socket_StaticConnectAsync_Success
System.Net.Sockets.Tests.DualModeConnectToHostString.DualModeConnect_LoopbackDnsToHost_Helper
System.Net.Sockets.Tests.DualModeConnectToDnsEndPoint.DualModeConnect_DnsEndPointToHost_Helper
System.Net.Sockets.Tests.DualModeConnectAsync.DualModeConnectAsync_DnsEndPointToHost_Helper
System.Net.Sockets.Tests.DualModeConnectAsync.DualModeConnectAsync_Static_DnsEndPointToHost_Helper
```

**Comment by davidsh** [comment]
>Next step:
Change the 4 tests (search the code base for their name) - replace localhost with www.microsoft.com:

That is a possible next step.  But we need to validate that IPv4 and IPV6 DNS records will always be returned back in all scenarios for that DNS name.  That needs to get tested. We should also verify that running CI tests in large scale won't be seen as an undesirable client connection to www.microsoft.com. I.e. we don't want it to be seen as a denial-of-service type situation.

**Comment by karelz** [comment]
Good point about the denial-of-service concern.
For large-scale verification, IMO it is sufficient to run the test in a loop every 10s-30s on local machine for some time (let's say 1h). The full large-scale validation can be done directly in CI. If it causes trouble, we can always revert he change.

**Comment by ViktorHofer** [comment]
It seems like www.microsoft.com always returns an IPv4 and IPv6 DNS record. Of course it depends on where you are doing the lookup but it seems the domain should fit.

**Comment by ViktorHofer** [comment]
From @davidsh 

> I think there is confusion about what this test is. "DualMode" is a concept for listening sockets and not outbound sockets. It allows a socket to listen on both an IPv4 and IPv6 address at the same time. This helps developers since they don't have to create 2 sockets on a server to listen for both IPv4 and IPv6.
I think this test was creating a listener and testing for receiving data on both IPv4 and IPv6. It thus required DNS resolution of the server endpoint to return both A and AAAA DNS records. In addition, it probably required listening on that dual-mode socket.
Changing this test to 'www.microsoft.com' might be testing the DNS resolution part of the test but it isn't testing receiving data on a dual-mode socket. We presumably used 'localhost' here because we were creating a loopback server to listen on.

**Comment by tmds** [comment]
```
Console.WriteLine(string.Join(", ", Dns.GetHostAddresses("localhost") as IEnumerable<IPAddress>));
```
on my Linux machine prints:
```
::1, 127.0.0.1
```
So it looks like this is resolving localhost to both addresses. Is this different on the CI machines? Is it tied to specific Unix flavors? Perhaps related to configuration?

**Comment by geoffkizer** [comment]
I think it's related to configuration, but I haven't tracked down the details.

**Comment by ViktorHofer** [comment]
Yeah it seems there a different behaviors between Unix distributions like Ubuntu, Suse, Debian, ... https://superuser.com/questions/1005335/how-do-i-ping-localhost-using-ipv6

Do we normally change configurations for our CI machines so that tests pass? I guess not, because it won't work on local dev machines.

**Comment by karelz** [comment]
@stephentoub can you please help here?
