### ISSUE TITLE
HTTP2: Hanging requests when multiplexing with cancellations on Windows

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/corefx#40022]
I'm seeing a condition in which http2 requests hang indefinitely when multiplexed with cancelled requests. The issues occurs on Windows but I haven't been able to reproduce in Ubuntu or OSX.

## Reproduction Steps

Install the nightly build (off master):
```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   5.0.100-alpha1-013662
 Commit:    7031ddb3f6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\eitsarpa\AppData\Local\Temp\dotnet-nightly-190805\sdk\5.0.100-alpha1-013662\

Host (useful for support):
  Version: 3.0.0-preview8-28379-02
  Commit:  3a87ac0079
```
Run the http stress suite from [this branch](https://github.com/eiriktsarpalis/corefx/tree/c51d5e3d8ea7cb911af41d5a278b5818090546a1/src/System.Net.Http/tests/StressTests/HttpStress) using the following arguments:
```
$  dotnet run -c Release -- -n 2 -ops 0 -maxContentLength 5  -clientTimeout 20 -cancelRate 0.1
```
Effectively this runs the stress suite using 2 concurrent workers sharing the same HttpClient instance, repeating a single GET request with a response body of length 5. A 10% of all requests will be cancelled at random. Here's the final output from a single stress session:
```
HttpStress Run Final Report

[8/5/2019 11:10:13 AM] Total: 237,165 Runtime: 00:20:08
         0: GET                       Success: 221,445  Canceled: 15,620        Fail: 100
            TOTAL                     Success: 221,445  Canceled: 15,620        Fail: 100

Latency(ms) : n=237165, p50=0.31, p75=0.39, p99=46.41, p999=70.47, max=20018.38

There were a total of 100 failures classified into 1 different types:

Failure Type 1/1:
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendHeadersAsync(HttpRequestMessage request, CancellationToken cancellationToken, Boolean mustFlush)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at HttpStress.RequestContext.SendAsync(HttpRequestMessage request, HttpCompletionOption httpCompletion, Nullable`1 token) in C:\Users\eitsarpa\devel\HttpStress\ClientOperations.cs:line 91
   at HttpStress.ClientOperations.<>c.<<get_Operations>b__1_0>d.MoveNext() in C:\Users\eitsarpa\devel\HttpStress\ClientOperations.cs:line 173
--- End of stack trace from previous location where exception was thrown ---
   at HttpStress.StressClient.<>c__DisplayClass11_0.<<StartCore>g__RunWorker|0>d.MoveNext() in C:\Users\eitsarpa\devel\HttpStress\StressClient.cs:line 109

         0: GET                       Fail: 100
            TOTAL                     Fail: 100
```
A few notes regarding this repro:
* The issue seems to impact a very low percentage of requests (0.04% in this instance).
* Surfaced `TaskCanceledException`s correspond to requests that have not been signaled for cancellation.
* Reproduces both with http.sys and kestrel, so this is very likely a client issue.
* The issue reproduces on Windows pretty consistently in my test environment (using a D4 instance in Azure). I have not been able to reproduce the issue on a D4 instance running Ubuntu 16.04 (using the same nightly build) or OSX.
* Setting `-n 1` (running with just one worker) makes the issue go away.
* Setting `-cancelRate 0` (no cancelled requests) makes the issue go away.
* Setting `-clientTimeout` to a high number makes the stress suite stall.
* Changing the `-maxContentLength` parameter does not impact ability to reproduce issue.

**Comment by davidsh** [comment]
@geoffkizer @stephentoub

**Comment by stephentoub** [comment]
> Setting -clientTimeout to a high number makes the stress suite stall.

That should make debugging this easier. Set it to a very high number, wait until all of the rest of the requests have completed, attach a debugger, and see what request is outstanding, where it's stuck, and why.

**Comment by geoffkizer** [comment]
Since you're running on 3.0, it's possible this is related to #39834 which hasn't made it to 3.0 yet.

If we are hitting #39834, that could cause the server to decide to terminate the connection, which could possibly lead to hangs like this if we have some issue in our connection shutdown handling. (Or possibly the server is doing something weird when this happens, but that seems less likely since it happens with both http.sys and kestrel.)

**Comment by geoffkizer** [comment]
Actually, it looks like you are running off master, not 3.0, right? 

What's different about the stress code in your branch that causes this to happen? I.e. why haven't we seen this before?

**Comment by eiriktsarpalis** [comment]
> Actually, it looks like you are running off master, not 3.0, right?

Correct.

**Comment by eiriktsarpalis** [comment]
I seem to have fallen victim to local state. Hadn't disabled `DOTNET_MULTILEVEL_LOOKUP`, and was loading an older version of System.Net.Http as a result. Closing.
