### ISSUE TITLE
Socket_SendToAsyncV4IPEndPointToV4Host_Throws_Unix fails on OSX.

### ISSUE THREAD

**Issue by pgavlin** [dotnet/corefx#4003]

**Comment by pgavlin** [comment]
There is a mismatch in the error code returned by Socket.SendToAsync.

**Comment by pgavlin** [comment]
The specific difference is that on *nix, the returned error is `SocketError.NetworkUnreachable` vs. `SocketError.Fault`. We could remap this error code for the various `SendTo` APIs if we feel that returning identical error codes is the right thing to do here. Frankly, I'm a bit surprised that Winsock returns EFAULT for this situation, as the docs for EFAULT on MSDN state that it means "The lpBuffers, lpTo, lpOverlapped, lpNumberOfBytesSent, or lpCompletionRoutine parameters are not part of the user address space, or the lpTo parameter is too small."[1]

[1] https://msdn.microsoft.com/en-us/library/windows/desktop/ms741693(v=vs.85).aspx

**Comment by stephentoub** [comment]
Pat, just took a quick look at the test, and it's using ```new IPEndPoint(IPAddress.Loopback, UnusedPort)```... wouldn't the Loopback vs IPv6Loopbackoopback explain the EFAULT, as the lpTo parameter would be too small?  Or am I completely off-base?

**Comment by pgavlin** [comment]
Ah, that could definitely be it. That explains the difference: on *nix, I assume that the address family is checked as long as the size of the address is at least large enough to be a `struct sockaddr`.

**Comment by pgavlin** [comment]
I'm a bit wary of remapping this error: the manpages for `{send,recv}msg` don't explicitly call out the conditions under which `ENETUNREACH` is returned, so we might end up masking other errors.

**Comment by stephentoub** [comment]
How difficult would it be to "fix" the size check so that we end up catching it as EFAULT that way?

**Comment by pgavlin** [comment]
We could refactor the code s.t. we pass the address family for the socket in to `{Send,Receive}Message` (without this information we can't do the check). This would be a pretty significant refactoring: every send/recv variant in the PAL would take another parameter, as would every call in the `SocketAsyncContext`.

I wonder whether this is even worth remapping at all, however: in theory, callers should be ready to handle `SocketError.NetworkUnreachable` on Windows as well, as `WSASendTo` et. al. may also return that error as per MSDN.

**Comment by stephentoub** [comment]
> every send/recv variant in the PAL would take another parameter, as would every call in the SocketAsyncContext

That does seem like overkill (with a performance impact for the non-error case) in order to get one error code vs another, in particular because the error code that's expected is about a usage error, rather than an error denoting a runtime situation.  If making this usage error case behave identically will complicate the codebase and result in needing to pass more information around, I'm ok with it being a minor behavioral difference that we accept.

**Comment by pgavlin** [comment]
SGTM.

**Comment by CIPop** [comment]
:+1: 

Only one comment regarding these types of differences in general: I think it would be useful to have different tests that clearly outline the different behavior.

**Comment by stephentoub** [comment]
>  I think it would be useful to have different tests that clearly outline the different behavior.

Agreed; we've tried to do this elsewhere in corefx.

**Comment by stephentoub** [comment]
@pgavlin, the new Unix variant of this is now failing on the mac in the lab;

System.Net.Sockets.Tests.DualMode.Socket_SendToAsyncV4IPEndPointToV4Host_Throws_Unix [FAIL]
04:27:49       Assert.Equal() Failure
04:27:49       Expected: NetworkUnreachable
04:27:49       Actual:   InvalidArgument
04:27:49       Stack Trace:
04:27:49             at System.Net.Sockets.Tests.DualMode.Socket_SendToAsyncV4IPEndPointToV4Host_Throws_Unix()
04:27:49             at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
04:27:49             at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
04:27:49             at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
