### ISSUE TITLE
HTTP2: _expect100ContinueWaiter should use TaskCreationOptions.RunContinuationsAsynchronously

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#40030]
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs#L119

It's using TaskContinuationOptions.RunContinuationsAsynchronously, which is incorrect.

**Comment by stephentoub** [comment]
Grrrr.

**Comment by geoffkizer** [comment]
Found because I added a bunch of Debug.Assert(!Monitor.IsEntered(SyncObject)) checks as you suggested on my PR.

**Comment by geoffkizer** [comment]
reopen for 3.0

**Comment by GSPP** [comment]
Wow, that's nasty :laughing:

**Comment by karelz** [comment]
Fixed for 3.0 in PR #40112 and in master (5.0) in PR #39882.
