### ISSUE TITLE
System.Management does not work with .net core 3.0 prev 7

### ISSUE THREAD

**Issue by Pilchie** [dotnet/corefx#40048]
_From @HolyOne on Sunday, August 4, 2019 10:10:32 AM_

I have an existing class using System.Management code which works.

I created a .net core 3 web app (I run on visual studio with Administrator permisions)
I get marshal error when I try to connect WMI at the first line.

This is the line I call
`   DNS = new ManagementScope (@"\\localhost\root\MicrosoftDNS") ;`

This is the error I get
**System.Runtime.InteropServices.MarshalDirectiveException:** 'Cannot marshal 'parameter #3': Cannot marshal a string by-value with the [Out] attribute.'

I do not use any win32 dll call or out parameter in my code so I thought it must be an internal error on System.Management or .net core 3 preview

![image](https://user-images.githubusercontent.com/293601/62422290-bf3a0880-b6b8-11e9-9680-fca506719139.png)

Thank you

_Copied from original issue: aspnet/AspNetCore#12860_

**Comment by Pilchie** [comment]
_From @HolyOne on Monday, August 5, 2019 8:55:54 AM_

I just tried latest prerelease ( 4.6.0-preview7.19362.9) and it seems it passes this line

**Comment by danmosemsft** [comment]
@holyone yes this was fixed in an earlier preview. https://github.com/dotnet/corefx/issues/35694
It seems you are unblocked now and this issue can be closed is that right?

**Comment by HolyOne** [comment]
Yes thank you
