### ISSUE TITLE
AcceptV6BoundToSpecificV6_Success fails on *nix.

### ISSUE THREAD

**Issue by pgavlin** [dotnet/corefx#4005]

**Comment by pgavlin** [comment]
Related tests (*BoundToSpecificV6_Success) also fail.

**Comment by pgavlin** [comment]
I've narrowed this down to the following assertion on an accepted socket:

`Assert.True(clientSocket.DualMode);`

On Windows, it appears that a listening socket that is bound to a specific IPv6-only address remains a dual-stack socket. On other platforms, this is not the case: once a socket is bound to a specific IPv6-only address, that socket is no longer dual-stack (i.e. the value of the `IPV6_V6ONLY` socket option is `1`, regardless of its value before the socket was bound). As a consequence, a socket for a connection accepted on the listening socket will also be IPv6-only. Personally, I find both behaviors a bit surprising: on the one hand, changing socket options without a call to `setsockopt` is somewhat disconcerting; on the other hand, a socket bound to an IPv6-only address is by definition not dual-stack, as it can never communicate using IPv4. My preference is that we change the tests to accommodate this behavior, as aside from the value of `Socket.DualMode` it's not observable (due to the aforementioned inability to communicate using IPv4 over a socket bound to an IPv6-only address). @CIPop, @davidsh, @SidharthNabar: any opionions?

**Comment by pgavlin** [comment]
After a bit more digging, I have found an observable difference in the case of UDP: on Windows, a dual-stack socket bound to an IPv6-only address will accept an IPv4 end point as a parameter to `Socket.ReceiveFrom`. On other platforms, the method will instead throw an exception b/c the socket cannot communicate with IPv4 hosts and the endpoint is therefore invalid. If this difference is deemed important, I think that we can emulate the Windows behavior of the `IPV6_V6ONLY` socket option on other platforms without too much trouble. /cc @stephentoub as well.

**Comment by CIPop** [comment]
> on Windows, a dual-stack socket bound to an IPv6-only address will accept an IPv4 end point as a parameter to Socket.ReceiveFrom. On other platforms, the method will instead throw an exception b/c the socket cannot communicate with IPv4 hosts and the endpoint is therefore invalid.

My opinion is that sockets is a low-level API and shouldn't try to change the platform's behavior if that change comes with considerable performance impact. I think throwing on platforms that don't fully support Windows's behaviors should be an accepted difference.

If possible, I would like to keep the test for Windows and have a different one (next to the first one) that demonstrates the difference.

**Comment by stephentoub** [comment]
> shouldn't try to change the platform's behavior if that change comes with considerable performance impact

Do we know it would have considerable performance impact on the other cases?  I have no problem if it's pay-for-play, with it being more expensive in the cases that would otherwise fail.

**Comment by pgavlin** [comment]
@stephentoub it would be an extra field per *nix socket to track the dual-mode state and some additional internal API complexity, but could save on system calls in cases where `Socket.DualMode` is frequently accessed.

**Comment by stephentoub** [comment]
Doesn't seem worth it.  Let's just ensure we're throwing the appropriate exception for the situation (whatever exception that may be, maybe a PlatformNotSupportedException, maybe something else) and add a comment to the code about what's happening and how it could be addressed in the future if need be.  Cool?

**Comment by pgavlin** [comment]
> Let's just ensure we're throwing the appropriate exception for the situation (whatever exception that may be, maybe a PlatformNotSupportedException, maybe something else) 

Unfortunately there's no way to throw `PlatformNotSupportedException` (or any other exception, really, besides the exception that's already being thrown) without adding the aforementioned state: the root cause of the issue is the OS's IP stack changing the value of the `IPV6_V6ONLY` option out from under us, which we can't notice without keeping track of the value set by managed code.

**Comment by stephentoub** [comment]
Ok.  Then just the detailed comment I guess.

**Comment by pgavlin** [comment]
FWIW, it might actually not be a bad thing to cache the expected value of `Socket.DualMode` on all platforms: the current implementation of this property makes a system call on each access, and this property is accessed as part of a number of argument validation checks.

**Comment by pgavlin** [comment]
@CIPop any thoughts on the above? This is a potential minor speedup for the `Receive{,Message}From` APIs at the cost of slightly larger socket instances. Do we have usage data for these APIs?

**Comment by CIPop** [comment]
> FWIW, it might actually not be a bad thing to cache the expected value of  Socket.DualMode  on all platforms.

Given what we've found out I would be against caching the value and instead keep doing the syscalls. The behavior is probably subject to change with kernel-level improvements.

@SidharthNabar PTAL regarding this question:
> This is a potential minor speedup for the  Receive{,Message}From  APIs at the cost of slightly larger socket instances. Do we have usage data for these APIs?

**Comment by CIPop** [comment]
> Doesn't seem worth it. Let's just ensure we're throwing the appropriate exception for the situation (whatever exception that may be, maybe a PlatformNotSupportedException, maybe something else) and add a comment to the code about what's happening and how it could be addressed in the future if need be. Cool?
> Ok. Then just the detailed comment I guess.

:+1:
