### ISSUE TITLE
IgnoreDataMember

### ISSUE THREAD

**Issue by josundt** [dotnet/corefx#40062]
**NewtonSoft.Json** is aware of certain attributes in the `System.Runtime.Serialization` namespace (`System.Runtime.Serialization.Primitives` assembly) like **`IgnoreDataMemberAttribute`**.

Properties with this attribute will not be serialized by NewtonSoft.Json.

Are you planning to support this with **`System.Text.Json.JsonSerializer`**, or is there a different approach I can use to annotate properties that should be ignored?

**Comment by ahsonkhan** [comment]
We decided against adding support for attributes coming from the `System.Runtime.Serialization` namespace.

See previous discussion:
https://github.com/dotnet/corefx/issues/37503#issuecomment-493296230

You can use the `JsonIgnore` attribute to annotate your property, which the `System.Text.Json.JsonSerializer` is aware off/honors.
https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonignoreattribute?view=netcore-3.0

Does the new `JsonIgnore` attribute work for you @josundt? If not, please feel free to re-open the issue.

**Comment by josundt** [comment]
As long as there is a solution I'm happy :-)

Personally I like the idea and see the benefits of certain generic attributes providing serialization instructions built in to the core framework. They can be consumed by different serialization libraries, because many of these instructions are common, even for different serialization formats (to control/override property names, to ignore certain properties etc).

When such attributes are available in the core framework, f.ex. C# projects containing POCO models only don't need NuGet package dependencies for one or more serialization components just for these serialization hints, and the same attribute can provide instructions to multiple serializers instead of having one per serializer.
