### ISSUE TITLE
Fix up System.Text.Encodings.Web test namespace to be consistent with other corefx projects

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#40073]
See https://github.com/dotnet/corefx/pull/39900#discussion_r309387083

Rename the namespace in the test project from `Microsoft.Framework.WebEncoders` to `System.Text.Encodings.Web.Tests`

https://github.com/dotnet/corefx/blob/c6f5ceedea28edf01ae7d3e13c02935669dad434/src/System.Text.Encodings.Web/tests/IHtmlEncoder.cs#L8

cc @GrabYourPitchforks

**Comment by igor-susic** [comment]
@ahsonkhan This seems like a good start to get to know codebase a little and make the first contribution, if it is ok with you I would like to take this one.

**Comment by ahsonkhan** [comment]
Awesome, go for it. I can't yet assign this to you, so I'll assign it to myself.

@karelz, can we get igor-susic added as a contributor?

**Comment by igor-susic** [comment]
@ahsonkhan No problem, I'm on it 👍
