### ISSUE TITLE
Consider implementing Socket.SendPacketsAsync on *nix.

### ISSUE THREAD

**Issue by pgavlin** [dotnet/corefx#4007]

**Comment by ericeil** [comment]
Moving this to "future."  We should implement this if there is demand.

**Comment by ericeil** [comment]
AFAIK, this is *not* supported on Mono, either.

**Comment by ericeil** [comment]
Closing this.  We'll be evaluating all of the missing/unsupported APIs in the next release.

**Comment by geoffkizer** [comment]
This is a feature gap between Windows and Unix.  I don't think it's particularly urgent.  But we should implement this sooner or later.
