### ISSUE TITLE
System.Threading.Channels - GetConsumingEnumerableAsync

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/corefx#40087]
Hi @stephentoub -
I'd like to request that a new member/extension method be added to ChannelReader<T>.

I think that the current methods for reading from a channel reader are a bit clunky (waiting to be able to read then actually trying to read) yet I understand their importance.

````BlockingCollection<T>```` has a ````GetConsumingEnumerable```` member that lets you enumerate and consume the collection.  I think it makes a lot of sense for ChannelReader<T> to have a similar member as well.

Think that can happen?

**Comment by stephentoub** [comment]
This was already added in 3.0. it's called ReadAllAsync.

**Comment by TonyValenti** [comment]
@stephentoub Hmm!  I'm using Version 4.5 from a .NET 4.6.1 app.  What do I need to do to be able to use that method?
