### ISSUE TITLE
Linger time is incorrect on OS X for boundary values.

### ISSUE THREAD

**Issue by pgavlin** [dotnet/corefx#4008]

**Comment by pgavlin** [comment]
It looks like OS X uses a `short` internally for storing the linger time for a socket. Furthermore, the units for the linger time are in ticks by default. When changed to seconds, the number of seconds is scaled to ticks and the result is stored. To make matters worse, integer values that exceed the range of a `short` are silently truncated and no error is returned by `setsockopt`. All of this adds up to some pretty bizarre behavior: for example, setting the linger time in seconds to `32767` results in a linger time of `-1`.

The only way I can think of to compensate for this behavior is to check for values that are out-of-range before calling `setsockopt` and returning an error from the shim, but this will result in an implementation that has a vastly smaller range for linger time on OS X (a maximum of about 327 seconds rather than 65535 seconds). @stephentoub any opinion here?

**Comment by stephentoub** [comment]
> @stephentoub any opinion here?

That sounds like the right solution.  If I'm understanding correctly, it's effectively just changing the silent truncation behavior to explicit error behavior, which is more diagnosable and more reliable.

**Comment by pgavlin** [comment]
Okay. One wrinkle that we might run into here is the possibility that the number of ticks per second varies across calls to `setsockopt`, thus changing the maximum linger time. I'd like to propose that we pick a max linger time that is rather short, and thus unlikely to be affected by false positives (i.e. we admit a linger time that ends up overflowing the range of a `short` once it is scaled). Experimentally, I believe that 256 seconds is a reasonable maximum (and probably underestimates the actual practical maximum by a fair amount, giving us room to improve in the future).

**Comment by stephentoub** [comment]
Seems reasonable, but what would cause the number of ticks per second to vary?  Via some sycall that changes it?

**Comment by pgavlin** [comment]
IIRC the number of ticks per second is derived from the clock frequency of the machine.

**Comment by pgavlin** [comment]
(so frequency scaling could change the value)

**Comment by stephentoub** [comment]
That seems very strange.  If that were true, then setsockopt storing a number of ticks would actually be storing an arbitrarily varying amount of time, and you wouldn't be able to use functions that return the number of ticks along with a value from _SC_CLK_TCK to determine an amount of time.

**Comment by pgavlin** [comment]
That's true, yes. Let me run some experiments.

**Comment by pgavlin** [comment]
On the other hand, even if frequency scaling doesn't affect ticks/second, couldn't the value be different across machines?

**Comment by stephentoub** [comment]
Yes, so we'd need to query for the ratio.

**Comment by pgavlin** [comment]
In which case we'd have a limit that changes not just per-platform, but also per-machine. This isn't the only such limit we'd have (# of open files, etc. are all configuration-related); I just wanted to make sure that's clear.

**Comment by stephentoub** [comment]
We already have that limit implicitly, though, right? It's just we'd be making it an error rather than silently becoming some other value?

**Comment by pgavlin** [comment]
Yes, that's correct. As I mentioned, it's not a huge issue: it's just different from the typical behavior of the option, where the max linger time is defined solely by the size of the integer used to store the value (i.e. only OS X would have a limit on linger time that differs between machines).

**Comment by stephentoub** [comment]
The other option would be to just say that the OS has this arbitrary limit, and I'd you go above it, you effectively get an infinite or whatever time, and we just ensure that's the fallback behavior.

**Comment by pgavlin** [comment]
> if you go above it, you effectively get an infinite or whatever time, and we just ensure that's the fallback behavior.

Either choice requires essentially the same machinery: we'd still need to validate that the input is in bounds and explicitly turn it into an infinite value, as otherwise it just wraps (so 328 seconds might be a negative value and thus no/infinite linger, but 400 seconds might be a positive but unexpected value).

**Comment by stephentoub** [comment]
> only OS X would have a limit on linger time that differs between machines

Oh, wait, maybe I misunderstood before... went we talking about only doing this l limit on OS X, not on Linux?

**Comment by pgavlin** [comment]
Yes. Linux behaves reasonably w.r.t. linger time.

**Comment by pgavlin** [comment]
Closed by #4086.
