### ISSUE TITLE
.Net Core Certificate for Docker Containers 

### ISSUE THREAD

**Issue by mathavanmani** [dotnet/corefx#40101]
Hi , I  was able to run a .net core application which does the Encryption using a certificate in Linux.  
Added the Certificate via X509Store.Add method. 

But now, we got many Docker containers running , I would like to know how I can refer/mount this certificate I have added (using X509Store.Add) inside a container. Obviosuly, I dont want to run Add certificate inside each container.

Any help would be appreciated.

Thanks.

**Comment by Clockwork-Muse** [comment]
Normally, you'd want to add any certificates to the "normal" linux certificate stores, same as on windows, not mess around with adding them via code.

In issue #32875 : 
> LocalMachine\Root is an interpreted view of the SSL_CERT_DIR and SSL_CERT_FILE values from OpenSSL.

...so you'd set up the certificates as part of the image, or volume mounted from the host, or something.  Your app wouldn't know there's anything special.

Note that if you have a private key, you're going to need to take special care - [for example, the use of `secrets` in these docker-compose files](https://docs.docker.com/ee/ucp/interlock/usage/tls/).  Of course, you can also just terminate at a reverse proxy, which, last I knew, what what was recommended if you're hosting an ASP.NET Core app (although it does support some HTTPS stuff).

**Comment by mathavanmani** [comment]
Hi @Clockwork-Muse , Trying to do RSA Encryption using certificate in 'My' key store. As per #32875, Certificate needs to be added by following way.

using (X509Store store = new x50Store(StoreName.My, StoreLocation.CurrentUser, OpenFlags.ReadWrite))
{
    store.Add(new X509Certificate2(pathToPfx, pfxPassword, X509StorageFlags.PersistKeySet));
}

Now, I wanted to know how to achieve this in containerized application as I don't want to add certificate in each container.

**Comment by Clockwork-Muse** [comment]
.... do something like [mount them from the host](https://stackoverflow.com/questions/26028971/docker-container-ssl-certificates), at the "standard" location, and they'll be in the store.  
[There's more specific instructions for Kestrel](https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/aspnetcore-docker-https.md), which seems to be expecting just to use a .pfx file, if you're running a web API.

**Comment by mathavanmani** [comment]
Hi, Thanks for your help. got it working by following command

**docker run --name test  -it  -v /Data/cryptography:/root/.dotnet/corefx/cryptography/x509stores/my/ ImageId:1.0.0**

**Comment by Clockwork-Muse** [comment]
Um.  Messing with the "personal" store is [not supported](https://github.com/dotnet/corefx/issues/32875#issuecomment-431086821):

>All (other) CurrentUser stores are (currently) stored under ~/.dotnet/corefx/x509stores/. Directly interacting with this directory or its child directories and files can put .NET in an invalid state, and is not supported. The structure of this directory is considered an internal implementation detail and subject to change.

Put the certificate in the usual machine certificate store instead (for example, on Ubuntu [follow these directions](http://manpages.ubuntu.com/manpages/bionic/man8/update-ca-certificates.8.html) and map that.
