### ISSUE TITLE
UDP Socket using SocketAsyncEventArgs garbage collects nearly every second

### ISSUE THREAD

**Issue by ryanthedev** [dotnet/corefx#40156]
Hello! I'm hoping for some help into figuring out why i'm getting so much GC.  I looked at some previous closed issues and noticed they were experiencing a similar issue.  Here is a screen shot of my diag window while in debug.
![image](https://user-images.githubusercontent.com/30601201/62728326-5ca27e80-b9d0-11e9-8bdb-d7c6448b0698.png)

here is another image showing my heap with a compare.
![image](https://user-images.githubusercontent.com/30601201/62728395-8cea1d00-b9d0-11e9-8bdb-df23c880dbd2.png)

My csproj
![image](https://user-images.githubusercontent.com/30601201/62728767-71cbdd00-b9d1-11e9-8596-0bbb8abbdb38.png)

Here is my server code
```csharp
class Program
    {
        private static Channel<SocketAsyncEventArgs> _free;
        private static Socket _listener;
        private static int _msgCount;
        private static Channel<SocketAsyncEventArgs> _inbound;
        private static Channel<SocketAsyncEventArgs> _outbound;

        static async Task Main(string[] args)
        {
            _free = Channel.CreateUnbounded<SocketAsyncEventArgs>();
            _inbound = Channel.CreateUnbounded<SocketAsyncEventArgs>();
            _outbound = Channel.CreateUnbounded<SocketAsyncEventArgs>();

            
            
            for(var i = 0; i < 5000; i++)
                Create();

            StartCounting();
            await RunAsync();
        }

        static SocketAsyncEventArgs Create()
        {
            var rwSocket = new SocketAsyncEventArgs();            
            rwSocket.Completed += new EventHandler<SocketAsyncEventArgs>(IO_Compelte);
            rwSocket.RemoteEndPoint = new IPEndPoint(IPAddress.Any, 0);
            _free.Writer.TryWrite(rwSocket);
            return rwSocket;
        }

        static Task RunAsync()
        {
            _listener = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);
            _listener.SetSocketOption(SocketOptionLevel.IP, SocketOptionName.PacketInformation, true);
            _listener.Bind(new IPEndPoint(IPAddress.Parse("127.0.0.1"), 8888));
            var reads = ProcessReads();
            var writes = ProcessWrites();

            return Task.WhenAll(reads, writes);
        }        

        static Task<int> Write(EndPoint target, string content, CancellationToken cancellation)
        {            
            if (_free.Reader.TryRead(out var args))
            {
                args.RemoteEndPoint = target;
                var buffMaxLen = Encoding.ASCII.GetMaxByteCount(content.Length);
                var buff = ArrayPool<byte>.Shared.Rent(buffMaxLen);
                var total = Encoding.ASCII.GetBytes(content, buff);
                args.SetBuffer(buff, 0, total);

                var tsc = new TaskCompletionSource<int>();
                args.UserToken = tsc;

                if (!_listener.SendToAsync(args))
                {
                    _outbound.Writer.TryWrite(args);
                }

                return tsc.Task;
            }
            else
            {
                Create();
                return Write(target, content, cancellation);
            }
        }

        static void InternalRead()
        {
            if (_free.Reader.TryRead(out var args))
            {
                var buff = ArrayPool<byte>.Shared.Rent(1024);
                args.SetBuffer(buff, 0, buff.Length);

                if (!_listener.ReceiveFromAsync(args))
                {
                    _inbound.Writer.TryWrite(args);
                }
            }
            else
            {
                Create();
                InternalRead();
            }
        }

        static void IO_Compelte(object sender, SocketAsyncEventArgs e)
        {
            switch (e.LastOperation)
            {
                case SocketAsyncOperation.ReceiveFrom:
                    {
                        _inbound.Writer.TryWrite(e);                        
                    }                    
                    break;
                case SocketAsyncOperation.SendTo:
                    {
                        _outbound.Writer.TryWrite(e);
                    }                    
                    break;
                default:
                    throw new ArgumentException("The last operation completed on the socket was not a receive or send");
            }
            
        }        

        static async Task ProcessReads()
        {
            InternalRead();

            while (await _inbound.Reader.WaitToReadAsync())
            {
                while(_inbound.Reader.TryRead(out var e))
                {
                    CompelteRead(e);
                }
            }            
        }

        static async Task ProcessWrites()
        {
            while (await _outbound.Reader.WaitToReadAsync())
            {
                while (_outbound.Reader.TryRead(out var e))
                {
                    CompleteSend(e);
                }
            }
        }

        static void CompleteSend(SocketAsyncEventArgs e)
        {
            TaskCompletionSource<int> completion = e.UserToken as TaskCompletionSource<int>;
            if (e.SocketError == SocketError.Success)
                completion.SetResult(e.BytesTransferred);
            else
                completion.SetException(new Exception(e.SocketError.ToString()));

            ArrayPool<byte>.Shared.Return(e.Buffer);
            _free.Writer.TryWrite(e);
        }

        static void CompelteRead(SocketAsyncEventArgs e)
        {
            var content = Encoding.ASCII.GetString(e.Buffer.AsSpan().Slice(0, e.BytesTransferred));
            ArrayPool<byte>.Shared.Return(e.Buffer);
            Interlocked.Increment(ref _msgCount);
            _free.Writer.TryWrite(e);
            InternalRead();
        }

        static void StartCounting()
        {
            Task.Run(async () =>
            {
                while (true)
                {
                    var count = Interlocked.Exchange(ref _msgCount, 0);
                    Console.WriteLine($"Msgs: {count}");
                    await Task.Delay(1000);
                }
            });
        }
    }
```

**Comment by davidsh** [comment]
@stephentoub

**Comment by davidsh** [comment]
What version of .NET Core are you running against?  Please show output of `dotnet --info`.

**Comment by davidsh** [comment]
What version of .NET Core are you running against?  Please show output of `dotnet --info`.

**Comment by ryanthedev** [comment]
λ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf

.NET Core SDKs installed:
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by karelz** [comment]
@scalablecory looked at it and thinks that this amount of allocations is fairly appropriate for the workload.
Closing as resolved.

If you think we allocate too much, please create a smaller repro demonstrating that. Thank you.
