### ISSUE TITLE
Dictionary performance downgrade after deserialization

### ISSUE THREAD

**Issue by JeffreyZhao** [dotnet/corefx#40150]
I just found an issue in `Dictionary<,>` that causes performance downgrade if a instance is created from deserialization.

<details>
<summary>Benchmark code</summary>

```csharp
public class DictionaryPerf
{
    private Dictionary<int, int> _original;
    private Dictionary<int, int> _deserialized;

    public DictionaryPerf()
    {
        _original = new Dictionary<int, int> {
            {0, 0}, {1, 1}, {2, 2}, {3, 3}, {4, 4},
            {5, 5}, {6, 6}, {7, 7}, {8, 8}, {9, 9}
        };

        var formatter = new BinaryFormatter();
        var stream = new MemoryStream();
        formatter.Serialize(stream, _original);

        stream.Position = 0;
        _deserialized = (Dictionary<int, int>)formatter.Deserialize(stream);
    }

    [Benchmark(Baseline = true, OperationsPerInvoke = 10)]
    public void Original()
    {
       _original.ContainsKey(0); 
       _original.ContainsKey(1); 
       _original.ContainsKey(2); 
       _original.ContainsKey(3); 
       _original.ContainsKey(4); 
       _original.ContainsKey(5); 
       _original.ContainsKey(6); 
       _original.ContainsKey(7); 
       _original.ContainsKey(8); 
       _original.ContainsKey(9); 
    }

    [Benchmark(OperationsPerInvoke = 10)]
    public void Deserialized()
    {
       _deserialized.ContainsKey(0); 
       _deserialized.ContainsKey(1); 
       _deserialized.ContainsKey(2); 
       _deserialized.ContainsKey(3); 
       _deserialized.ContainsKey(4); 
       _deserialized.ContainsKey(5); 
       _deserialized.ContainsKey(6); 
       _deserialized.ContainsKey(7); 
       _deserialized.ContainsKey(8); 
       _deserialized.ContainsKey(9); 
    }
}
```

</details>

Benchmark result:

```ini
BenchmarkDotNet=v0.11.5, OS=Windows 10.0.17763.615 (1809/October2018Update/Redstone5)
Intel Core i7-7700HQ CPU 2.80GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.0.100-preview7-012821
  [Host]     : .NET Core 3.0.0-preview7-27912-14 (CoreCLR 4.700.19.32702, CoreFX 4.700.19.36209), 64bit RyuJIT
  DefaultJob : .NET Core 3.0.0-preview7-27912-14 (CoreCLR 4.700.19.32702, CoreFX 4.700.19.36209), 64bit RyuJIT
```

|       Method |      Mean |     Error |    StdDev | Ratio | RatioSD |
|------------- |----------:|----------:|----------:|------:|--------:|
|     Original |  6.431 ns | 0.0962 ns | 0.0803 ns |  1.00 |    0.00 |
| Deserialized | 10.424 ns | 0.2067 ns | 0.1832 ns |  1.62 |    0.04 |

The cause of the issue is that, we'll save `EqualityComparer<T>.Default` if the `_comparer` is `null`:

https://github.com/dotnet/corefx/blob/1083657c17b84248ea59896823f605ea63ce78a6/src/Common/src/CoreLib/System/Collections/Generic/Dictionary.cs#L358

But after deserialization we haven't set it back:

https://github.com/dotnet/corefx/blob/1083657c17b84248ea59896823f605ea63ce78a6/src/Common/src/CoreLib/System/Collections/Generic/Dictionary.cs#L689

So the `_comparer` in the deserialized dictionary will keep an instance of `EqualityComparer<T>.Default` which will go to slow branches every time we're going to use `_comparer`.

It can be verified in this way:

```csharp
var dict = new Dictionary<int, int>();

var formatter = new BinaryFormatter();
var stream = new System.IO.MemoryStream();
formatter.Serialize(stream, dict);

stream.Position = 0;
var dictCopy = (Dictionary<int, int>)formatter.Deserialize(stream);

var comparerField = typeof(Dictionary<int, int>).GetField("_comparer", BindingFlags.Instance | BindingFlags.NonPublic);
var comparer = comparerField.GetValue(dictCopy);

// expected to be null, but get an GenericEqualityComparer<int> now.
Console.WriteLine(comparer); 
```

To fix the issue, we can simply set `_comparer` back to `null` if the deserialized comparer is `EqualityComparer<T>.Default`, as what I did when optimizing `HashSet<>`:

https://github.com/dotnet/corefx/blob/45466468dce20e578b05055f1abc7baab5570135/src/System.Collections/src/System/Collections/Generic/HashSet.cs#L487-L490

I can create a PR to fix the issue, but I also have a question about how we can verify this with unit test. The tricky part is that it cannot be verified via public API. Also, it has to be reproduced with `BinaryFormatter`, but I doubt it's accessible in `System.Collections.Tests` project.

Can you provide any thought on how I should write unit test for this issue in corefx?

**Comment by ericstj** [comment]
Was this a regression from 2.x?  If so, keep in 3.0, if not move out.

**Comment by JeffreyZhao** [comment]
@ericstj It's a regression from 2.1. It's fine in 2.0, but introduced by this change:

https://github.com/dotnet/corefx/commit/926183e3cba0cb9b24685fb0fa308b386fed61df#diff-72146f1d0ccb2f246a39b3aaceef746d

**Comment by danmosemsft** [comment]
> Can you provide any thought on how I should write unit test for this issue in corefx?

I think it's not essential to have a test to protect this perf fix. So long as we have enough test coverage of the functoinality.

@JeffreyZhao could you share a bit about your scenario? Is this preventing you meeting your perf goals?

I am wondering how critical this is for 3.0 since (a) it's been regressed a long time without a report of it (b) we do not recommend binary serialization in general - it's mainly for compatibility with existing code so hopefully it is not a heavily used path.

**Comment by danmosemsft** [comment]
BTW, thank you for sharing your benchmark, I wonder whether we have sufficient coverage in https://github.com/dotnet/performance already? I assume not, since we didn't detect this.

**Comment by stephentoub** [comment]
Just to make sure I understand, we added an optimization and this just nullifies that optimization when using a dictionary created via deserialization... is that right?

**Comment by JeffreyZhao** [comment]
> @JeffreyZhao could you share a bit about your scenario? Is this preventing you meeting your perf goals?
> 
> I am wondering how critical this is for 3.0 since (a) it's been regressed a long time without a report of it (b) we do not recommend binary serialization in general - it's mainly for compatibility with existing code so hopefully it is not a heavily used path.

It's not discovered from any of my products, but from code reading, since I have to handle the same scenario for `HashSet<>`. I agree that it's not a critical issue as 1) no functionality is broken, and 2) binary serialization is not used much.

> @stephentoub Just to make sure I understand, we added an optimization and this just nullifies that optimization when using a dictionary created via deserialization... is that right?

Yes, that's right. It nullifies the optimization after created via deserialization.

**Comment by JeffreyZhao** [comment]
Just did a quick trial fix, and it turns out `if (_comparer == EqualityComparer<TKey>.Instance)` doesn't work, since they're different comparer instance after deserialization.

```csharp
var dict = new Dictionary<int, int>();

var formatter = new BinaryFormatter();
var stream = new System.IO.MemoryStream();
formatter.Serialize(stream, dict);

stream.Position = 0;
var dictCopy = (Dictionary<int, int>)formatter.Deserialize(stream);

var comparerField = typeof(Dictionary<int, int>).GetField("_comparer", BindingFlags.Instance | BindingFlags.NonPublic);
var comparer = comparerField.GetValue(dictCopy);

Console.WriteLine(comparer == EqualityComparer<int>.Default); // False
Console.WriteLine(Equals(comparer, EqualityComparer<int>.Default)); // True
```

**Comment by stephentoub** [comment]
> It nullifies optimization after created via deserialization

Right.  So this isn't actually a regression... it's just that an optimization that was added doesn't apply in all circumstances.

This can be seen by running the benchmark on both 2.2 and 3.0:

|       Method |     Toolchain |     Mean |     Error |    StdDev | Ratio | RatioSD |
|------------- |-------------- |---------:|----------:|----------:|------:|--------:|
|     Original | netcoreapp2.2 | 4.511 ns | 0.0326 ns | 0.0305 ns |  1.00 |    0.00 |
| Deserialized | netcoreapp2.2 | 7.359 ns | 0.0447 ns | 0.0418 ns |  1.63 |    0.02 |
|     Original | netcoreapp3.0 | 4.566 ns | 0.0347 ns | 0.0325 ns |  1.01 |    0.01 |
| Deserialized | netcoreapp3.0 | 6.461 ns | 0.0394 ns | 0.0369 ns |  1.43 |    0.01 |

There's actually an improvement in the deserialized time from 2.2 to 3.0.  It's just that there was and continues to be a difference in time between "original" and "deserialized", because an optimization that was added only applies to "original".

**Comment by jkotas** [comment]
Binary serialization is legacy feature that we have not plans of improving. This optimization was intentionally not included for round-tripped dictionary to keep the code simple. It is in line with out general approach for binary serialization.

**Comment by ViktorHofer** [comment]
I actually remember that case and as @jkotas said we intentionally left the optimization out of the serialization path.

**Comment by JeffreyZhao** [comment]
Understood. Please feel free to close it if sees appropriate.
