### ISSUE TITLE
 System.Net.Internals.SocketExceptionFactory+ExtendedSocketException in MacOS for IPHostEntry host = Dns.GetHostEntry(Dns.GetHostName());

### ISSUE THREAD

**Issue by jpfreyen** [dotnet/corefx#40169]
With this example code for Program.cs, for .NETCore 2.1:

```
using System;
using System.Net;

namespace MeHostName
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            IPHostEntry host = Dns.GetHostEntry(Dns.GetHostName());
            Console.WriteLine($"{host.HostName} I am");
        }
    }
}
```

I can reliably, repeatedly generate the following exception, an exception I've read in this github project (like here: https://github.com/dotnet/corefx/issues/36401 for .NETCore 2.2)  I should never, ever see:

> /usr/local/share/dotnet/dotnet /Users/jamesfreyensee/playground/csharpstuff/RootUser/bin/Debug/netcoreapp2.1/MeHostName.dll
> Hello World!
> 
> Unhandled Exception: System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Device not configured
>    at System.Net.Dns.InternalGetHostByName(String hostName)
>    at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
>    at RootUser.Program.Main(String[] args) in /Users/jamesfreyensee/playground/csharpstuff/RootUser/Program.cs:line 12
> 
> Process finished with exit code 6.

Here's dotnet version stats:

> 
> OS Version:  10.14
>  OS Platform: Darwin
>  RID:         osx.10.14-x64
>  Base Path:   /usr/local/share/dotnet/sdk/2.1.505/
> 
> Host (useful for support):
>   Version: 2.2.2
>   Commit:  a4fd7b2c84
> 
> .NET Core SDKs installed:
>   2.1.505 [/usr/local/share/dotnet/sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by jpfreyen** [comment]
I'm thinking this would be a problem in Linux too

**Comment by stephentoub** [comment]
That you're hitting an error is correct; the OS returned an error from the DNS request and do this throws an exception. The bug is the error message, as the code was misinterpreting the error code. That was fixed for 3.0 in https://github.com/dotnet/corefx/pull/32351.

**Comment by stephentoub** [comment]
Closing as dup of https://github.com/dotnet/corefx/issues/13309, fixed by https://github.com/dotnet/corefx/pull/32351.

**Comment by jpfreyen** [comment]
Question:  Is System.Net.NetworkInformation.NetworkInterface.GetIsNetworkAvailable() a valid check to see if "The device is configured" and I will get that Exception thrown or not?  Because it's coming out 'True', and from coding samples I have been researching, it seems like if that comes out 'True', I should not hitting any error or receiving an exception:
     
 ```
  static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Console.WriteLine($" is network available 
          {System.Net.NetworkInformation.NetworkInterface.GetIsNetworkAvailable()}");
}

output:

> Hello World!
>  is network available True

```

**Comment by jpfreyen** [comment]
Is this a problem or should I open up a new issue?
