### ISSUE TITLE
System.IO.Pipelines 4.6.0-preview7.19362.9 is hanging when reading from a PipeReader

### ISSUE THREAD

**Issue by thomhurst** [dotnet/corefx#40162]
Using Pipelines 4.5.3 was working as expected.

I made 0 code changes, updated Pipelines to v4.6.0-preview7.19362.9 and reading from my PipeReader started hanging.

Reproduction:
Checkout this branch: https://github.com/thomhurst/A-sync-RedisClient/tree/feature/pipelines-4-6-preview-hanging
You'll need a Redis Server to connect to, and should connect over SSL. (Information such as host and port just needs entering in the test class)
Run the tests and you'll see they hang.

Once reproduced, change the Pipelines version to 4.5.3, rerun the tests and see it doesn't hang.

**Comment by jkotalik** [comment]
Would it be possible to get a minimal repro, ideally where we don't need to spin up a redis server? I see you are doing some custom things with pipes like making your own pipe scheduler: https://github.com/thomhurst/A-sync-RedisClient/blob/feature/pipelines-4-6-preview-hanging/TomLonghurst.RedisClient/Pipes/DedicatedScheduler.cs. 

Can you open something like Parallel Stacks in Visual Studio to figure out where it is hanging? Or collect a process dump that we can analyze? Do you know which specific test is hanging?

We have made a few changes to Pipes between 4.5 and 4.6. https://github.com/dotnet/corefx/commits/master/src/System.IO.Pipelines/src/System/IO/Pipelines for history.

**Comment by thomhurst** [comment]
Hi @jkotalik 

Sorry - I've no idea how to give you a repo without connecting to Redis. This is my first time using pipes and my only experience is connecting to Redis!

I've not used parallel stacks either - Is there a way I can dump you the raw data?
Here's a screenshot but not sure how much help it'll be
<img width="1118" alt="parallel stacks" src="https://user-images.githubusercontent.com/30480171/62735646-85079880-ba23-11e9-897e-9533d2be9499.png">

All the tests are hanging. But on 4.5.3 they don't!

As per your comment about the pipescheduler etc, I've completely removed those, and used PipeWriter.Create and PipeReader.Create and they're still hanging:

https://github.com/thomhurst/A-sync-RedisClient/tree/feature/pipelines-4-6-preview-hanging-2

Please let me know how else I can help!

**Comment by jkotalik** [comment]
The most useful thing for us would be to get your app in a state where it is hanging and then collect a process dump. You can do this on windows by going to the process explorer, finding the dotnet process which is running the tests/app, and right click->create dump file. You can then upload it to a shared place (like a public one drive folder) so I can look at it, that would be useful.

The parallel stacks view doesn't seem to give us much. Let's start by figuring out which test is causing the hang.

>  I've completely removed those, and used PipeWriter.Create and PipeReader.Create and they're still hanging

Which class specifically are you using PipeReader/PipeWriter.Create? I don't see those in the branch you linked. FYI PipeReader/PipeWriter wraps a stream, which has different behavior than a normal pipe. However if you are just calling new Pipe(), then you shouldn't be seeing a hang.

**Comment by thomhurst** [comment]
@jkotalik I'm using the Create methods in here: 
https://github.com/thomhurst/A-sync-RedisClient/blob/feature/pipelines-4-6-preview-hanging-2/TomLonghurst.RedisClient/Client/RedisClient.Connect.cs

Here's a dump (I think I got the right one. Executing the test seemed to kick off four dotnet processes)

https://drive.google.com/file/d/1vMPF_v9qOlnWBvvtNVfqpv1neibieIEa/view?usp=sharing

**Comment by jkotalik** [comment]
cc @davidfowl

**Comment by thomhurst** [comment]
@jkotalik I see it's been moved to the future milestone. Does this mean it's going to be a long time for a fix?

**Comment by davidfowl** [comment]
I'll take a look at this today.

**Comment by thomhurst** [comment]
@davidfowl were you able to recreate it?

**Comment by davidfowl** [comment]
@thomhurst does it only repro with SSL?

**Comment by davidfowl** [comment]
OK reproduced it and it's a usage issue (you were just getting lucky before). The bug is here https://github.com/thomhurst/A-sync-RedisClient/blob/9421c601c60a83da3beaf26f25d8c2a335d17a9e/TomLonghurst.RedisClient/Models/ResultProcessor.cs#L187. Just drop the second argument.

```C#
Pipe.Input.AdvanceTo(endOfLinePosition.Value);
```

PS: I'm writing a document describing these usage patters that should hopefully clear things up (preview here https://gist.github.com/davidfowl/94acfe2d835209839181bf3b62ea90be).

PS: I also found a bunch of other bugs. I'll file issues on your repo 😄

**Comment by thomhurst** [comment]
@davidfowl D'oh. Sorry to waste your time then guys, and thanks for the help! 😄
