### ISSUE TITLE
Enable symbol validation in our official builds.

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#40196]
Currently blocked on: https://github.com/dotnet/arcade/issues/2871

cc: @ericstj @ViktorHofer @markwilkie @danmosemsft

**Comment by ericstj** [comment]
I've pinged the arcade issue on this.  If we get a fix we can reenable.  If not we'll need to manually verify this on our release builds for 3.0.

**Comment by ericstj** [comment]
@JohnTortugo can you let us know what the new symbol validation mechanism will be?

**Comment by markwilkie** [comment]
Given the fact that symbols aren't available for 10+ minutes, we're going to move symbol validation out of the main build and into the steps to release/ship.  In the future, we'll do this as part of ring validation, but that'll be part of 5.0.  For now, it'll be a manual validation step.

**Comment by ViktorHofer** [comment]
Closing as discussed in the Arcade Working Group meeting. We will move symbol validation out of the build and instead do it manually for 3.0. @markwilkie will provide more details about how we will approach that.
