### ISSUE TITLE
Expression interpreter - Issue with Convert

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#4019]
See disabled test "CompileInterpretCrossCheck_Convert" in PR for #3995.

System.Exception : Error for expression 'Convert(null)':

        Xunit.Sdk.NotNullException: Assert.NotNull() Failure

**Comment by bartdesmet** [comment]
More detailed info:

  System.Exception : Error for expression '(System.Boolean)null'

**Comment by bartdesmet** [comment]
Compiler threw 'System.NullReferenceException: Object reference not set to an instance of an object.' but interpreter did not.

**Comment by bartdesmet** [comment]
Here's an initial list of conversions where the outcome differs between compiler and interpreter:

System.Object -> System.DayOfWeek
System.Object -> System.Nullable`1[System.DayOfWeek]
System.Boolean -> System.Byte
System.Boolean -> System.Nullable`1[System.Byte]
System.Boolean -> System.SByte
System.Boolean -> System.Nullable`1[System.SByte]
System.Boolean -> System.Int16
System.Boolean -> System.Nullable`1[System.Int16]
System.Boolean -> System.UInt16
System.Boolean -> System.Nullable`1[System.UInt16]
System.Boolean -> System.Int32
System.Boolean -> System.Nullable`1[System.Int32]
System.Boolean -> System.UInt32
System.Boolean -> System.Nullable`1[System.UInt32]
System.Boolean -> System.Int64
System.Boolean -> System.Nullable`1[System.Int64]
System.Boolean -> System.UInt64
System.Boolean -> System.Nullable`1[System.UInt64]
System.Boolean -> System.Char
System.Boolean -> System.Nullable`1[System.Char]
System.Boolean -> System.Single
System.Boolean -> System.Nullable`1[System.Single]
System.Boolean -> System.Double
System.Boolean -> System.Nullable`1[System.Double]
System.Boolean -> System.Byte
System.Boolean -> System.Nullable`1[System.Byte]
System.Boolean -> System.SByte
System.Boolean -> System.Nullable`1[System.SByte]
System.Boolean -> System.Int16
System.Boolean -> System.Nullable`1[System.Int16]
System.Boolean -> System.UInt16
System.Boolean -> System.Nullable`1[System.UInt16]
System.Boolean -> System.Int32
System.Boolean -> System.Nullable`1[System.Int32]
System.Boolean -> System.UInt32
System.Boolean -> System.Nullable`1[System.UInt32]
System.Boolean -> System.Int64
System.Boolean -> System.Nullable`1[System.Int64]
System.Boolean -> System.UInt64
System.Boolean -> System.Nullable`1[System.UInt64]
System.Boolean -> System.Char
System.Boolean -> System.Nullable`1[System.Char]
System.Boolean -> System.Single
System.Boolean -> System.Nullable`1[System.Single]
System.Boolean -> System.Double
System.Boolean -> System.Nullable`1[System.Double]
System.Object[] -> System.String[]
System.Object[] -> System.Collections.Generic.IEnumerable`1[System.Char][]

**Comment by bartdesmet** [comment]
With the pending PR commits, we're down to the following (known) issues with convert:

```
// C(Monday), I(1)
yield return Expression.Convert(Expression.Constant(1, typeof(object)), typeof(DayOfWeek));

// C(InvalidCastException), I(1)
yield return Expression.Convert(Expression.Constant(1, typeof(object)), typeof(DayOfWeek?));

// C(InvalidCastException), I(object[])
yield return Expression.Convert(Expression.Constant(new object[] { "bar" }), typeof(string[]));

// C(InvalidCastException), I(object[])
yield return Expression.Convert(Expression.Constant(new object[] { "bar" }), typeof(IEnumerable<char>[]));
```

C indicates compiled result; I indicates interpreted result.

**Comment by bartdesmet** [comment]
Update: the errors listed above have been addressed by the latest PR update.

**Comment by VSadov** [comment]
fixed by https://github.com/dotnet/corefx/pull/5713
