### ISSUE TITLE
Enable SourceLink validation into official builds

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#40195]
This is currently blocked on: https://github.com/dotnet/arcade/issues/3603

We should just turn it on whenever this is fixed in arcade.

cc: @ViktorHofer @ericstj @danmosemsft @markwilkie

**Comment by ericstj** [comment]
I've pinged the arcade issue on this.  If we get a fix we can reenable.  If not we'll need to manually verify this on our release builds for 3.0.
