### ISSUE TITLE
Welcome to ftp.eu.OpenBSD.org   Hosted by Safespring  For other mirror sites visit http://www.openbsd.org/ftp.html       _____                 ____   _____ _____         / ___ \               |  _ \ / ____|  __ \       / /  / /___  ___  ____ | |_) | (___ | |  | |     / /  / / __ \/ _ \/ __ \|  _ < \___ \| |  | |    / /__/ / /_/ /  __/ / / /| |_) |____) | |__| |    \_____/ .___/\___/_/ /_/ |____/|_____/|_____/          /_/                                                      |    .            The proactively secure Unix-like           .   |L  /|   .        Operating System.       _ . |\ _| \--+._/| .      Please visit the OpenBSD web site      / ||\| Y J  )   / |/| ./	at http://www.openbsd.org/     J  |)'( |        ` F`.'/   -<|  F         __     .-<     All transfers are logged, if you don't     | /       .-'. `.  /-. L___ like this policy, disconnect now!     

### ISSUE THREAD

**Issue by playboyistanbul** [dotnet/corefx#40217]
Welcome to ftp.eu.OpenBSD.org 
 Hosted by Safespring
 For other mirror sites visit http://www.openbsd.org/ftp.html
      _____                 ____   _____ _____   
     / ___ \               |  _ \ / ____|  __ \  
    / /  / /___  ___  ____ | |_) | (___ | |  | | 
   / /  / / __ \/ _ \/ __ \|  _ < \___ \| |  | | 
  / /__/ / /_/ /  __/ / / /| |_) |____) | |__| | 
  \_____/ .___/\___/_/ /_/ |____/|_____/|_____/  
       /_/                                       
              |    .            The proactively secure Unix-like
          .   |L  /|   .        Operating System.
      _ . |\ _| \--+._/| .      Please visit the OpenBSD web site
     / ||\| Y J  )   / |/| ./	at http://www.openbsd.org/
    J  |)'( |        ` F`.'/
  -<|  F         __     .-<     All transfers are logged, if you don't
    | /       .-'. `.  /-. L___ like this policy, disconnect now!
    J \      <    \  | | O\|.-' 
  _J \  .-    \/ O | | \  |F    
 '-F  -<_.     \   .-'  `-' L__
__J  _   _.     >-'  )._.   |-' You can order OpenBSD CDROMs
`-|.'   /_.           \_|   F   from http://www.openbsd.org/orders.html.
  /.-   .                _.<    CD sales are important to support the   
 /'    /.'             .'  `\	continued development of the project.   
  /L  /'   |/      _.-'-\      
 /'J       ___.---'\|	       
   |\  .--' V  | `. `          
   |/`. `-.     `._)           
      / .-.\		       
VK    \ (  `\                  
       `.\

**Comment by terrajobst** [comment]
This is a bot.
