### ISSUE TITLE
Can PersistedFiles.GetUserFeatureDirectory support other root directories other than $HOME ?

### ISSUE THREAD

**Issue by CXuesong** [dotnet/corefx#40213]
https://github.com/dotnet/corefx/blob/0de236d983639d4b8e683e48e5722c93c4471689/src/Common/src/CoreLib/System/IO/PersistedFiles.Unix.cs#L87-L95

I'm making an ASP.NET Core application running as a linux background service (systemd.service). To run the ASP.NET Core server process as a separate user, I used `useradd --system` to create an user dedicated to the service without user profile directory (i.e. `$HOME`). When [executing `dotnet run` under the service user](https://github.com/crystal-pool/GrayWing/blob/defb94cff39c29ebf9433b543adda8ff66379202/Scripts/RunServer.ps1#L61) to start the server, I got the following exception

> Unhandled Exception: System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.

Though this server is running behind a reverse-proxy that provides HTTPS and I could try disable the HTTPS binding provided by ASP.NET Core and bypass this problem, but before that, I tried to [execute `dotnet dev-certs https` in the service script](https://github.com/crystal-pool/GrayWing/blob/defb94cff39c29ebf9433b543adda8ff66379202/Scripts/RunServer.ps1#L52) before `dotnet run`. However, `dev-certs` failed.

So I executed `dev-certs` as the service user (who does not have a valid $HOME) and the result looks like this
```
my-service@machine:/$ dotnet dev-certs https -v
Listing 'HTTPS' certificates on 'CurrentUser\My'.
'0' found matching the criteria.
SUBJECT - THUMBPRINT - NOT BEFORE - EXPIRES - HAS PRIVATE KEY
Checking certificates for validity.
Listing valid certificates
'0' found matching the criteria.
SUBJECT - THUMBPRINT - NOT BEFORE - EXPIRES - HAS PRIVATE KEY
Listing invalid certificates
'0' found matching the criteria.
SUBJECT - THUMBPRINT - NOT BEFORE - EXPIRES - HAS PRIVATE KEY
Listing 'HTTPS' certificates on 'LocalMachine\My'.
Filtering found certificates to those with a subject equal to 'CN=localhost'
'0' found matching the criteria.
SUBJECT - THUMBPRINT - NOT BEFORE - EXPIRES - HAS PRIVATE KEY
Listing certificates excluded from consideration.
'0' found matching the criteria.
SUBJECT - THUMBPRINT - NOT BEFORE - EXPIRES - HAS PRIVATE KEY
No valid certificates present on this machine. Trying to create one.
Saving the certificate into the certificate store.
Error saving the certificate in the certificate store 'CurrentUser\My'.
Exception message: The X509 certificate could not be added to the store.
Exception message: Access to the path '/.dotnet/corefx/cryptography/x509stores/my' is denied.
Exception message: Permission denied
There was an error saving the HTTPS developer certificate to the current user personal certificate store.
```

After doing some search, I think the code I quoted at the beginning is the root cause, because X509Store used `PersistedFiles.GetUserFeatureDirectory` to determine the filesystem location for the certs.
https://github.com/dotnet/corefx/blob/0de236d983639d4b8e683e48e5722c93c4471689/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/DirectoryBasedStoreProvider.cs#L299-L307

My question is, can we introduce some mechanism (e.g. environment variables) to change the root of `UserFeatureDirectory`, something like `DOTNET_CLI_HOME` introduced in dotnet/cli#9327 ? This can make the days for those who does not have a valid `$HOME` much easier.

**Comment by tmds** [comment]
> Though this server is running behind a reverse-proxy that provides HTTPS and I could try disable the HTTPS binding provided by ASP.NET Core and bypass this problem

If you set `ASPNETCORE_URLS=http://*:8080` then ASP.NET Core shouldn't add an https endpoint.

**Comment by CXuesong** [comment]
@tmds Sure. Actually I decided to change the `applicationUrl` value in `launchsettings.json` to remove HTTPS binding. That addressed my issue.

However, in a more generic aspect, I'm not sure whether a valid $HOME folder should be a hard prerequisite for PersistedFiles-dependant features.

**Comment by bartonjs** [comment]
Where else would you want it to point?  Since it supports interception via the HOME environment variable you can redirect it to wherever you want on a single process invocation.

Our PersistedFiles files are for things belonging to the user, and the only real user context is $HOME (or the path from /etc/passwd that eventually becomes $HOME under interactive shells).

**Comment by CXuesong** [comment]
Actually I used to think executables should work even without a valid `$HOME` on Linux because Linux allows me to create a system account without user profile by default. (Actually `$HOME=/`.) Now I suppose I should just override the default and explicitly give the service user a user profile directory with `adduser --system --create-home`, because other tools like `npm` won't work without a valid `$HOME`, either…

I think on the other way round, changing `$HOME` should solve the problem, too. I will close the issue for now. Thanks for your explanation!
