### ISSUE TITLE
Expression interpreter - Issue with ConvertChecked

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#4022]
See disabled test "CompileInterpretCrossCheck_ConvertChecked" in PR for #3995.

System.Exception : Error for expression 'ConvertChecked(False)':

        Xunit.Sdk.NotNullException: Assert.NotNull() Failure
           at Xunit.Assert.NotNull(Object object)

**Comment by bartdesmet** [comment]
More detailed info:

  System.Exception : Error for expression '#(System.Byte)False'

**Comment by bartdesmet** [comment]
Interpreter threw 'System.InvalidCastException: Unable to cast object of type 'System.Boolean' to type 'System.Byte'.' but compiler did not.

**Comment by VSadov** [comment]
fixed by https://github.com/dotnet/corefx/pull/5713
