### ISSUE TITLE
EXEC : error : Could not load type 'System.Text.Json.Serialization.JsonSerializerOptions' from assembly 'System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

### ISSUE THREAD

**Issue by vikramtamboli** [dotnet/corefx#40241]
Hi Team,

We are trying to compile source from https://github.com/SteveSandersonMS/presentation-2019-06-NDCOslo/tree/master/demos/MissionControl

**When we run below command we get exception
D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Server>dotnet build**

Microsoft (R) Build Engine version 16.3.0-preview-19329-01+d31fdbf01 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj : warning NU1603: RazorComponents.MaterialDesign 0.1.0-alpha-20190610102728 depends on Microsoft.AspNetCore.Components.Browser (>= 3.0.0-preview6.19305.13) but Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19305.13 was not found. An approximate best match of Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19307.2 was resolved. [D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Server\MissionControl.Server.csproj]
Restore completed in 108.36 ms for D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj.
D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Server\MissionControl.Server.csproj : warning NU1603: RazorComponents.MaterialDesign 0.1.0-alpha-20190610102728 depends on Microsoft.AspNetCore.Components.Browser (>= 3.0.0-preview6.19305.13) but Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19305.13 was not found. An approximate best match of Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19307.2 was resolved.
Restore completed in 505.88 ms for D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Server\MissionControl.Server.csproj.
Restore completed in 1.03 sec for D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\PinMapLibrary\PinMapLibrary.csproj.
Restore completed in 35.97 ms for D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Shared\MissionControl.Shared.csproj.
You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Server\MissionControl.Server.csproj : warning NU1603: RazorComponents.MaterialDesign 0.1.0-alpha-20190610102728 depends on Microsoft.AspNetCore.Components.Browser (>= 3.0.0-preview6.19305.13) but Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19305.13 was not found. An approximate best match of Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19307.2 was resolved.
You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj : warning NU1603: RazorComponents.MaterialDesign 0.1.0-alpha-20190610102728 depends on Microsoft.AspNetCore.Components.Browser (>= 3.0.0-preview6.19305.13) but Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19305.13 was not found. An approximate best match of Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19307.2 was resolved.
MissionControl.Shared -> D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Shared\bin\Debug\netstandard2.0\MissionControl.Shared.dll
PinMapLibrary -> D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\PinMapLibrary\bin\Debug\netstandard2.0\PinMapLibrary.dll
MissionControl.Client -> D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\bin\Debug\netstandard2.0\MissionControl.Client.dll
_**EXEC : error : Could not load type 'System.Text.Json.Serialization.JsonSerializerOptions' from assembly 'System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. [D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj]
at Microsoft.AspNetCore.Blazor.Build.BootJsonWriter.GetBootJsonContent(String assemblyFileName, String entryPoint, String[] assemblyReferences, IEnumerable`1 embeddedContent, Boolean linkerEnabled)
at Microsoft.AspNetCore.Blazor.Build.BootJsonWriter.WriteFile(String assemblyPath, String[] assemblyReferences, String[] embeddedResourcesSources, Boolean linkerEnabled, String outputPath)
at Microsoft.AspNetCore.Blazor.Build.DevServer.Commands.WriteBootJsonCommand.<>c__DisplayClass0_0.b__0()
C:\Users\349185.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview6.19307.2\targets\Blazor.MonoRuntime.targets(633,5): error MSB3073: The command "dotnet "C:\Users\349185.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview6.19307.2\targets../tools/Microsoft.AspNetCore.Blazor.Build.dll" write-boot-json "obj\Debug\netstandard2.0\MissionControl.Client.dll" --references "D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\obj\Debug\netstandard2.0\blazor\bootjson-references.txt" --embedded-resources "D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\obj\Debug\netstandard2.0\blazor\embedded.resources.txt" --linker-enabled --output "D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\obj\Debug\netstandard2.0\blazor\blazor.boot.json"" exited with code 1. [D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj]**_

Build FAILED.

D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj : warning NU1603: RazorComponents.MaterialDesign 0.1.0-alpha-20190610102728 depends on Microsoft.AspNetCore.Components.Browser (>= 3.0.0-preview6.19305.13) but Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19305.13 was not found. An approximate best match of Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19307.2 was resolved. [D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Server\MissionControl.Server.csproj]
D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Server\MissionControl.Server.csproj : warning NU1603: RazorComponents.MaterialDesign 0.1.0-alpha-20190610102728 depends on Microsoft.AspNetCore.Components.Browser (>= 3.0.0-preview6.19305.13) but Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19305.13 was not found. An approximate best match of Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19307.2 was resolved.
D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Server\MissionControl.Server.csproj : warning NU1603: RazorComponents.MaterialDesign 0.1.0-alpha-20190610102728 depends on Microsoft.AspNetCore.Components.Browser (>= 3.0.0-preview6.19305.13) but Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19305.13 was not found. An approximate best match of Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19307.2 was resolved.
D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj : warning NU1603: RazorComponents.MaterialDesign 0.1.0-alpha-20190610102728 depends on Microsoft.AspNetCore.Components.Browser (>= 3.0.0-preview6.19305.13) but Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19305.13 was not found. An approximate best match of Microsoft.AspNetCore.Components.Browser 3.0.0-preview6.19307.2 was resolved.
EXEC : error : Could not load type 'System.Text.Json.Serialization.JsonSerializerOptions' from assembly 'System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. [D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj]
C:\Users\349185.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview6.19307.2\targets\Blazor.MonoRuntime.targets(633,5): error MSB3073: The command "dotnet "C:\Users\349185.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview6.19307.2\targets../tools/Microsoft.AspNetCore.Blazor.Build.dll" write-boot-json "obj\Debug\netstandard2.0\MissionControl.Client.dll" --references "D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\obj\Debug\netstandard2.0\blazor\bootjson-references.txt" --embedded-resources "D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\obj\Debug\netstandard2.0\blazor\embedded.resources.txt" --linker-enabled --output "D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\obj\Debug\netstandard2.0\blazor\blazor.boot.json"" exited with code 1. [D:\Workspaces\presentation-2019-06-NDCOslo-master\demos\MissionControl\MissionControl.Client\MissionControl.Client.csproj]
4 Warning(s)
2 Error(s)

Time Elapsed 00:00:13.34

**Comment by aeastham67** [comment]
I just saw this too. Is there a workround for this? Thanks

**Comment by aeastham67** [comment]
For info, I just updated Microsoft.AspNetCore.Blazor and Microsoft.AspNetCore.Blazor.Build to Latest Prerelease 3.0.0-preview-7.193365.7 which fixed this.

**Comment by steveharter** [comment]
@pranavkm @rynowak PTAL. Some versioning issues? Looks like upgrading to latest addresses the issue.

**Comment by pranavkm** [comment]
@vikramtamboli, it's likely that you have a preview7 SDK \ runtime installed which had a couple of API breaking changes. As @aeastham67 pointed out, upgrading to preview7 should resolve the issue. Feel free to file a new issue in https://github.com/aspnet/AspNetCore/issues if you're still seeing this after you upgrade.

**Comment by vikramtamboli** [comment]
Thanks for the help 

**My dotnet version is 3.0.100-preview7-012821**

@aeastham67  - I already upgraded to latest preview packages available in nuget for all projects still not able to compile
tried with visual studio 2019 preview version as well
also tried adding System.Text.Json to MissionControl.Client

![image](https://user-images.githubusercontent.com/16055034/62916128-f3ae6400-bd4b-11e9-9b47-07e80df701cd.png)

![image](https://user-images.githubusercontent.com/16055034/62916173-1f314e80-bd4c-11e9-936d-5242df68ddf9.png)


little more help needed here to get this working

**Comment by pranavkm** [comment]
@vikramtamboli could you include the output from `dotnet --info`?

**Comment by vikramtamboli** [comment]
C:\Users>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by pranavkm** [comment]
This issue was moved to aspnet/AspNetCore#13093
