### ISSUE TITLE
System.Configuration.ConfigurationManager installing many dependencies

### ISSUE THREAD

**Issue by JamesFaix** [dotnet/corefx#40256]
I have a project where I want to install the System.Configuration.ConfigurationManager package. My project is on .NET Framework 4.6.2, and I am trying to install v4.5.0 of the package.

From the dependencies listed for this package (and its dependencies) it seems like this should also install
 - System.Security.Permissions
 - System.Security.AccessControl
 - System.Security.Principal.Windows

However, I am seeing all of these references added to my csproj file:

 - Packages:
     - System.Configuration.ConfigurationManager
     - System.Security.AccessControl
     - System.Security.Permissions
     - System.Security.Principal.Windows
- GAC references:			
     - System.Data.OracleClient
     - System.Drawing
     - System.Net
     - System.Transactions

If I try to install v4.4.0 or v4.4.1 instead, I do not get any of these extra references, and just System.Configuration.ConfigurationManager.

Any idea where these extra dependencies are coming from? Particularly, the System.Data.OracleClient package seems very strange.

**Comment by ViktorHofer** [comment]
The package references are fine. System.Configuration.ConfigurationManager v4.5.0 added a dependency on System.Security.Permissions which itself depends on System.Security.AccessControl which depends on System.Security.Principal.Windows. For the assembly references I would need to dig further.

**Comment by ViktorHofer** [comment]
The oracle reference is coming from System.Security.Permissions: https://github.com/dotnet/corefx/blob/758b1bfe0693801c3ac3e1b3b103a3b5e64be14a/src/System.Security.Permissions/src/System.Security.Permissions.csproj#L202.

Closing, feel free to reopen if you have further questions.

**Comment by JamesFaix** [comment]
💯 Thank you for the investigation and prompt response!
