### ISSUE TITLE
System.Net.NetworkInformation.NetworkInterface.GetIsNetworkAvailable() is true despite error saying not configured for macOS 

### ISSUE THREAD

**Issue by jpfreyen** [dotnet/corefx#40263]
I filed a similar issue but didn't get resolution on further questions.

The following code will throw an exception saying device is not configured even though the check System.Net.NetworkInformation.NetworkInterface.GetIsNetworkAvailable() returns true:

```
using System;
using System.Net;

namespace Hello
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            
            Console.WriteLine($" is network available {System.Net.NetworkInformation.NetworkInterface.GetIsNetworkAvailable()}");
                
            IPHostEntry host = Dns.GetHostEntry(Dns.GetHostName());
            Console.WriteLine($"{host.HostName} I am");
        }
    }
}
```

> Hello World!
>  is network available True
> 
> Unhandled Exception: System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Device not configured
>    at System.Net.Dns.InternalGetHostByName(String hostName)
>    at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
>    at Hello.Program.Main(String[] args) in /Users/jamesfreyensee/playground/csharpstuff/Hello/Program.cs:line 15

This is based on many code samples I found in which _System.Net.NetworkInformation.NetworkInterface.GetIsNetworkAvailable()_ was being used a check before _IPHostEntry host = Dns.GetHostEntry(Dns.GetHostName());_ is called.

**Expected results**
If _IPHostEntry host = Dns.GetHostEntry(Dns.GetHostName());_ is throwing an exception saying "Device not configured", _System.Net.NetworkInformation.NetworkInterface.GetIsNetworkAvailable()_  should have returned **_false_**

**Comment by davidsh** [comment]
@wfurt

**Comment by davidsh** [comment]
Which version of .NET Core is this running against?

**Comment by jpfreyen** [comment]
Apologies, forgot to add that:

OS Version: 10.14
OS Platform: Darwin
RID: osx.10.14-x64
Base Path: /usr/local/share/dotnet/sdk/2.1.505/

Host (useful for support):
Version: 2.2.2
Commit: a4fd7b2c84

.NET Core SDKs installed:
2.1.505 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by wfurt** [comment]
I assume this is 2.x, right? The messages are unrelated. 
Dns lookup will throw that exception regardless of real network status if lookup fail. That should be fixed by https://github.com/dotnet/corefx/pull/32351

**Comment by jpfreyen** [comment]
So moving forward, in 3.0, System.Net.NetworkInformation.NetworkInterface.GetIsNetworkAvailable()  is not a good check to prevent DNS lookup throwing that exception?

**Comment by wfurt** [comment]
what exactly are you trying to do? Note that name resolution may work without network via local files as well as connectivity (or presence of up interface and gateway) does not guarantee working DNS. 

You can do probes for well-known name and get that as OK sign. But even with that you may bump to a failure once in a while - either by asking for unknown name or because of transient outages.

**Comment by jpfreyen** [comment]
What I want to do is retrieve the hostname and then use a DNS lookup to find the canonical network name for the host without tripping an exception on macOS.  That code works in Windows, so I'm struggling to understand what is different on macOS (and Linux) for .NET Core.  3 DNS servers are configured on my macOS laptop with 3 Search domains, all automatically assigned.  On command line I get:

$ scutil --dns | grep 'nameserver\[[0-9]*\]'
  nameserver[0] : 10.3.0.6
  nameserver[1] : 10.45.0.5
  nameserver[2] : 10.3.0.19

so I'm struggling to understand how lookup is failing.

**Comment by wfurt** [comment]
what do you get if you run `hostname` and 
```
nslookup `hostname`
```

On windows the hostname and "localhost" are special and do not perform any DNS lookup AFAIK. On Unix it is not, so the lookup will fail if the name is not in your DNS zone. Depending on your network, that can  be done automatically via DHCP integration.

**Comment by jpfreyen** [comment]
Oh OK, for Windows, that would explain a successful call.  And sure enough, on the mac:

JF-EN-C02V905BHTDF:$ nslookup `hostname`
Server:		10.3.0.6
Address:	10.3.0.6#53

** server can't find JF-EN-C02V905BHTDF.tld: NXDOMAIN

**Comment by wfurt** [comment]
that make sense. There is not much we can do about it at .Net level. Your best choice is integration with DHCP e.g. when DHCP server hands out lease, it would also create DNS entry. Or use some form of DynDNS.

If you simply trying to figure out your address, methods from NetworkInformation could be good choice.

**Comment by jpfreyen** [comment]
This was very helpful in understanding everything @wfurt , thank you very much!
