### ISSUE TITLE
HTTP/2: Trailing headers are getting dropped

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/corefx#40260]
While we have been using trailing headers in the HttpStress suite for a while, the code was actually missing validation logic on the client side. It looks like trailing headers are being dropped, for a significant percentage of requests:

## Reproduction Steps

1. Check out https://github.com/eiriktsarpalis/corefx/tree/httpstress-add-trailing-header-validation.
2. Using a recent build of `release/3.0`, run the stress suite with arguments `dotnet run -- -n 1 -ops 2 -cancelRate 0`

## Additional Info

* Server sending back a random number of up to 100 trailing headers.
* Response is typically missing 1 header, but might be missing 2-3 headers in rarer instances.
* Issue is impacting between 20% and 50% of total requests.
* I don't know at this point if it's a kestrel or client issue. Http.sys does not support trailing headers.

**Comment by davidsh** [comment]
Trailing headers can only be retrieved by the client after the client reads the entire response body. Is this HttpStress suite doing that?

It would be interesting to use Wireshark and capture packets to see if the problem is the client or server.

**Comment by davidsh** [comment]
@stephentoub @geoffkizer

**Comment by eiriktsarpalis** [comment]
> Trailing headers can only be retrieved by the client after the client reads the entire response body. Is this HttpStress suite doing that?

The current code does not do that, however I just verified that the issue persists even if I do add this.

> It would be interesting to use Wireshark and capture packets to see if the problem is the client or server.

👍

**Comment by eiriktsarpalis** [comment]
I neglected to add a sample error message:
```
System.Exception: missing headers Header-17-Trailer, Header-18-Trailer, Header-19-Trailer, Header-55-Trailer out of a total of 56 headers.
   at HttpStress.ClientOperations.<>c.<<get_Operations>b__1_2>d.MoveNext() in C:\Users\eitsarpa\devel\dotnet\corefx\src\System.Net.Http\tests\StressTests\HttpStress\ClientOperations.cs:line 246
--- End of stack trace from previous location where exception was thrown ---
   at HttpStress.StressClient.<>c__DisplayClass11_0.<<StartCore>g__RunWorker|0>d.MoveNext() in C:\Users\eitsarpa\devel\dotnet\corefx\src\System.Net.Http\tests\StressTests\HttpStress\StressClient.cs:line 108
```
The above implies that all other `Header-<x>-Trailer` names between 0 and 55 have been accounted for.

**Comment by eiriktsarpalis** [comment]
The issue is caused by headers containing empty values. Aspnetcore ignores those values when added via the `IHeaderDictionary.Append` method, which is what the `AppendTrailer` method calls under wraps. For more details c.f. https://github.com/aspnet/AspNetCore/issues/13085
