### ISSUE TITLE
Expose Assembly.Load(byte[], byte[]) and Assembly.LoadFile(string path)

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#4027]
On CoreCLR this would be implemented by loading assemblies into the default load context. Today we have to do wacky things to load into the default load context (assuming that we don't control it). It's one of the reasons DNX has a specific API that is exposed to user code to allow them to do the same https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Runtime.Abstractions/IAssemblyLoadContext.cs

/cc @jkotas @nguerrera @gkhanna79

**Comment by jkotas** [comment]
These APIs do not load into the default load context on desktop. I do not think it makes sense for them to load into default load context on CoreCLR - same API, different behavior across runtimes.

**Comment by davidfowl** [comment]
Ok we need a new API to Load into the default load context when you down own it on CoreCLR. Everyone will have to ifdef (we do this today in Razor).

**Comment by jkotas** [comment]
This API exists on desktop: Assembly.LoadFrom. Are you saying that we should expose Assembly.LoadFrom in CoreCLR?

**Comment by gkhanna79** [comment]
@davidfowl Is the need to load assemblies into default context even when the default context is overridden? What is the motivation?

**Comment by davidfowl** [comment]
Consider that any time anybody wants to load an assembly from disk or from byte[], they have to cross compile. DNX has an abstraction that protects users from this (https://github.com/aspnet/Entropy/blob/dev/samples/Runtime.CustomLoader/Program.cs), IAssemlyLoadContext, IAssemblyLoaderContainer, but as @jkotas said, these do different things on each of the CLRs. We're at an impasse, the basic need to Load assemblies is different and we want to be able to target both .NET Framework and .NET Core.

**Comment by jkotas** [comment]
Would it help to provide OOB System.Runtime.Loader.dll contract implementation for desktop, that would try to simulate AssemblyLoadContext using AppDomain.ResolveEvent, etc. for the most common cases?

**Comment by davidfowl** [comment]
@jkotas Yes it would. We to some extent did that here https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Loader/LoadContext.cs#L124. Assuming the runtime team can do a better job :smile: . I'd also want another change though. I want to be able to Load(byte[]) and Load(file) without implementing a LoadContext. See https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Razor/Compilation/RoslynCompilationService.cs#L350

Everytime, we use a load context, our derived class exposes a public method so that it can be called from the outside. This is the biggest annoyance with the existing APIs.

**Comment by davidfowl** [comment]
Does this still need more info?

**Comment by gkhanna79** [comment]
@davidfowl I have filed https://github.com/dotnet/coreclr/issues/1954 to track the work in CoreCLR repo and will close this issue. Please follow up with me if there are additional questions.

**Comment by weshaggard** [comment]
@gkhanna79 I'm going to reopen this issue to use to track adding the public APIs to the contract. I agree the work will need to happen in coreclr repo but the API changes will need to happen here.

**Comment by gkhanna79** [comment]
Assigning to @steveharter since he needs to bring the proposed design to FX API Review for discussion first.

**Comment by KevinRansom** [comment]
I would really like to be able to run my build coreclr apps under the desktop debugger, at least until the debugging experience is back to par with desktop.  Any that use this api, are going to fail, and so I would like someway of using this class on the desktop.

**Comment by muratg** [comment]
Do we have a agreed upon design for this yet?  Blocks https://github.com/aspnet/dnx/issues/3227

**Comment by gkhanna79** [comment]
@steveharter ?

**Comment by steveharter** [comment]
I've been tracking this issue at https://github.com/dotnet/coreclr/issues/2095. Currently working on proposal for this, with likely recommendation to minimize public changes to coreclr with implementation and perhaps contract in separate library.
