### ISSUE TITLE
IAsyncDisposable.ConfigureAwait papercut

### ISSUE THREAD

**Issue by jnm2** [dotnet/corefx#40296]
Having both `ConfigureAwait(false)` calls is important, but it requires two lines and prevents you from making use of a using declaration:

```cs
var stream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false);
await using (stream.ConfigureAwait(false))
{
    // Use stream, typed as System.Stream
}
```

**Comment by jnm2** [comment]
I'm not sure if anything nicer is possible. A generic `ConfigureAwait` is pretty dubious:

```cs
await using var _ = (await response.Content.ReadAsStreamAsync().ConfigureAwait(false)).ConfigureAwait(false, out var stream);
```

And you actually can use a using declaration, contrary to what I thought at first:

```cs
var stream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false);
await using var _ = stream.ConfigureAwait(false);

// Use stream, typed as System.Stream
```

**Comment by scalablecory** [comment]
This actually is a bit hard to grok. @geoffkizer @stephentoub

**Comment by stephentoub** [comment]
https://github.com/dotnet/csharplang/issues/2661
