### ISSUE TITLE
Adding a dependency in one project.json breaks build very badly

### ISSUE THREAD

**Issue by kapilash** [dotnet/corefx#4030]
Adding the following line in ```src\System.Net.Http\src\project.json``` is breaking build (on all platforms).

        "System.Security.Cryptography.OpenSsl": "4.0.0-beta-*",

Firstly,  running build in the root directory results in failure in the package restore step.
This error is due to e945fa2b4e1d54ee68c92e8d027e99fc4b894448 

Strangely, only on windows, we get to go past this  just by running ```build.cmd``` again. 

Secondly, even if we revert the above commit,

The build break is not just in System.Net.Http project but across the board. The following  projects are broken because of one line change in one project.json :

*  ```System.Net.Security```
*  ```System.Net.Sockets```
*  ```System.Security.AccessControl```
* ```System.Security.Cryptography.Algorithms``` and a few more.

I can see from the build logs that the System.Security.Cryptography etc are missing from the references. 
I am not able to figure out if this is an issue with dnu's resolution mechanism (coupled with the dependencies in corefx) or if this a problem with current version of this particular package.

Please note that this was working till very recently in a PR. Am seeing this only when I tried to rebase it with master.

**Comment by joshfree** [comment]
@bartonjs @ericstj

**Comment by ericstj** [comment]
This is a known issue.  It's happening because the packages from build 23420 and later require a new version of DNX that can support generations.

I'm working on getting us moved to that version, but I need to update all the "dotnet" projects in order to do so, which I'm doing first.

In the meantime you can temporarily use 23419 instead of *.

**Comment by kapilash** [comment]
Thanks @ericstj   I tried hardcoding the version to 23419, but that is not working.

This is what I added:

     "System.Security.Cryptography.OpenSsl": "4.0.0-beta-23419",

 Is that correct?

**Comment by ericstj** [comment]
Any other * dependency in the same project.json will be re-evaluated to include a 23420 package.  You can check the project.lock.json to see if this is happening.

That said I've just fixed this internally and it's awaiting merge.  Hopefully tomorrow we'll be back in business consuming the latest packages.

**Comment by kapilash** [comment]
fixed with tools-version 110. closing it.
Thanks @ericstj
