### ISSUE TITLE
LocaleBuilder can not create custom locale for ckb-IQ

### ISSUE THREAD

**Issue by heesong-kim** [dotnet/corefx#40301]
Hello.
We need to create custom culture for .NET Core.
I tried Locale Builder from https://www.microsoft.com/en-us/download/details.aspx?id=41158
and I was able to create "bh-IN.msi" successfully.
However I couldn't create "ckb-IQ.msi"

![localeBuilder1](https://user-images.githubusercontent.com/35357918/62996541-020d9480-bea0-11e9-92de-42c788cfb720.png)

LocaleBuilder doesn't seem to allow name "ckb-IQ". It says to use "ku-Arab-IQ" instead.
However we cannot use "ku-Arab-IQ" because we've been using name "ckb-IQ" for our product.
We were able to create "ckb-IQ.msi" on Windows7. So we were able to install custom locale and build text resource DLL for ckb-IQ.
However the "ckb-IQ.msi" built on Windows7 doesn't work on Windows10.
So I tried to recreate "ckb-IQ.msi" on Windows10 with the latest version of Locale Builder and I saw the error "Locale Builder could not proceed due to following issue: Use culture name ku-Arab-IQ instead of alternate sort name ckb-IQ to replace system culture ku-Arab-IQ".

How can I create custom locale for ckb-IQ?

Actually I have also raised a question to MSDN Forum. https://social.msdn.microsoft.com/Forums/sqlserver/en-US/d7a938e3-e06d-4ece-b058-f0184cef6907/localebuilder-can-not-create-custom-locale-for-ckbiq?forum=netfxbcl
but I have not received the answer I want yet. So I also raise the question here.

**Comment by stephentoub** [comment]
How is this related to .NET Core?

**Comment by tarekgh** [comment]
@heesong-kim please report this issue to Windows team through the Feedback Hub in Windows 10. This is not a .NET issue. I'll try to to get Windows team be aware about it too.

**Comment by ShawnSteele** [comment]
In the help menu, there's a 'provide feedback' link, did you happen to try that?  (If so I need to figure out why it didn't make it to us.)

Windows called this locale ku-Arab-IQ before it was added to CLDR.  When we imported ckb-IQ from CLDR, we "aliased" to the existing locale name to prevent disruption to existing apps that used the earlier windows name.  Windows (& .Net) therefore return data from ku-Arab-IQ for either ckb-IQ or ku-Arab-IQ.

Unfortunately, that alias won't pick up the custom locale information.  For a "complete" story you'll have to replace both.

LocaleBuilder objects to the name when you first try to create ckb-IQ, however if you start with ku-Arab-IQ, you should be able to change the name in the locale builder in the next step.

**Comment by heesong-kim** [comment]
@ShawnSteele, Thank you for your answer.
To send an e-mail to the outside of the company, I need an approval process.
So, I didn't use 'provide feedback' link first.
Can I contact you through github? If not, I will email through 'provide feedback'.

I tried your method "LocaleBuilder objects to the name when you first try to create ckb-IQ, however if you start with ku-Arab-IQ, you should be able to change the name in the locale builder in the next step."
So now I can create ckb-IQ.msi and installed it.
But even if I installed ckb-IQ.msi, after Visual Studio build finished, there is no ckb-IQ resources.dll.
(FYI, our product is Tizen.NET TV which uses .NET Core.
Our apps have been using Resources.ckb-IQ.resx.)

It seems that Windows 10 blocks the creation of resource dll for ckb-IQ.
It's a big problem for us.
We need to build & package our apps with ckb-IQ locale on Windows 10 and install to TV.
Could you help me?
