### ISSUE TITLE
Fix System.Net's Interop.OpenSsl error handling

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefx#4031]
There are 2 issues with OpenSsl's current error handling

1. In Interop.OpenSsl.Disconnect, we are ignoring the SSL_get_error error code, and just continuing even though there was an error from SSL_shutdown.
2. There are 2 sets of error codes in OpenSSL:
 1. Those defined in err.h
 2. Those defined in ssl.h
 These two sets overlap, for example ERR_R_SYS_LIB = 2 and SSL_ERROR_WANT_READ = 2.

In Interop.OpenSsl.GetSslError, if the SslErrorCode returned from SSL_get_error (defined in ssl.h) is SSL_ERROR_SYSCALL, it calls ERR_get_error (defined in err.h), and casts that result to an SslErrorCode, which is incorrect since it will return a separate set of error codes. We need to treat these errors separately, since they are separate sets with conflicting values.

**Comment by vijaykota** [comment]
> SslErrorCode, which is incorrect 

@eerhardt, for all the cases where GetSslError() is used, OpenSsl documentation explicitly mentions that SslErrorCode is returned. So current behavior is correct.

**Comment by eerhardt** [comment]
@vijaykota - here's the chunk of code I'm talking about https://github.com/dotnet/corefx/blob/master/src/Common/src/Interop/Unix/libssl/Interop.OpenSsl.cs#L404-L412:

```C#
private static Ssl.SslErrorCode GetSslError(SafeSslHandle context, int result)
{
    Ssl.SslErrorCode retVal = Ssl.SslGetError(context, result);
    if (retVal == Ssl.SslErrorCode.SSL_ERROR_SYSCALL)
    {
        retVal = (Ssl.SslErrorCode)Crypto.ErrGetError();
    }
    return retVal;
}
```

The call to Crypto.ErrGetError() and casting the result to SslErrorCode is the issue.  ErrGetError returns an ERR_R_* reason, not an SSL_ERROR_*.

**Comment by vijaykota** [comment]
My bad.. sorry I remembered this incorrectly. The call to ERR_get_error was only to get a more descriptive error in a much earlier version of the code which used to log the string. The call to ErrGetError can now be removed

**Comment by bartonjs** [comment]
@stephentoub I think that you fixed this in https://github.com/dotnet/corefx/pull/5551 (https://github.com/dotnet/corefx/commit/b9d6a1a9a46bf4a74624a71cfe42b078c2f86dfc, in particular).  Would you agree?

And, @eerhardt, would you? :smile:

**Comment by eerhardt** [comment]
The second issue looks like it is resolved by that change. But the first issue is still in the code:

https://github.com/dotnet/corefx/blob/master/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.Ssl.cs#L289

**Comment by bartonjs** [comment]
Oh, good catch.

**Comment by bartonjs** [comment]
/me rolls his eyes.

It looks like that's unreachable code.  We set quiet shutdown, which means shutdown just exits 1 without doing any work.

> SSL_shutdown() can be modified to only set the connection to "shutdown" state but not actually send the "close notify" alert messages, see SSL_CTX_set_quiet_shutdown(3). When "quiet shutdown" is enabled, SSL_shutdown() will always succeed and return 1.

Then, if we weren't setting quiet, and actually wanted to do the session vitrification, then this would need to be a lot more complicated.

https://www.openssl.org/docs/manmaster/ssl/SSL_shutdown.html

Anyways, I'll clean this up with some comments and asserts.
