### ISSUE TITLE
HTTP2: Review recent HTTP2-related security bulletins

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/corefx#40367]
Several HTTP2-related security bulletins have been released by Netflix recently.

https://github.com/Netflix/security-bulletins/blob/master/advisories/third-party/2019-002.md

These bulletins apply to server implementations of HTTP2, but we should review these and determine whether we should do anything for HttpClient.

These are all mitigated by the fact that a client chooses to connect to a particular server (whereas a server is expected to serve arbitrary clients). So, the first mitigation for any issue here is simply to not connect to the specific poorly-behaving server. That said, these seem worth looking at regardless.

Evaluation of the specific vulnerabilities:

"Data Dribble" -- applies
"Ping Flood" -- applies
"Resource Loop" -- does not apply; we ignore prioritization
"Reset Flood" -- does not apply; we disable push so the peer cannot create streams
"Settings Flood" -- applies
"0-Length Headers Leak" -- unclear, but I think this is already mitigated. We disallow 0-length header names and we enforce a limit on total header size via MaxResponseHeadersLength.
"Internal Data Buffering" -- unclear. I don't actually understand what the particular DoS attack here is; it seems very specific to particular server implementations of response buffering, but it's not clear exactly what's happening. I believe we already apply backpressure properly in all outbound data scenarios, whether the backpressure is caused by HTTP2 flow control or TCP flow control.
"Empty Frames Flood" -- applies

**Comment by samsosa** [comment]
This is not only relevant for the **HttpClient**, but also for **AspNetCore**/**Kestrel**. Maybe cross post this issue or ping the [AspNetCore](https://github.com/aspnet/AspNetCore)-Team?

**Comment by geoffkizer** [comment]
I got this from the ASP.NET folks, so they are already aware.

**Comment by playboyistanbul** [comment]
İF U CAN SEND THİS ETC WALLET PLEASE
0x0aac7cff13a9a4c17d01331475ce7c74cd164528

Geoff Kizer <notifications@github.com>, 16 Ağu 2019 Cum, 23:55 tarihinde
şunu yazdı:

**Comment by playboyistanbul** [comment]
FİRST TO LİNK GOOD THANK U SO MUCH


AtOmXpLuS <notifications@github.com>, 16 Ağu 2019 Cum, 23:59 tarihinde şunu
yazdı:

**Comment by davidsh** [comment]
@wfurt Can you look into this issue?

**Comment by karelz** [comment]
@scalablecory already looked at these as well and didn't find anything related, closing.
