### ISSUE TITLE
cosmosdb v3 and v2 clients stall on p7 & p8

### ISSUE THREAD

**Issue by FluentGuru** [dotnet/corefx#40374]
For some reason, the cosmos db client v3 stalls on read item operations both not on database/containers o store procedure manipulation operations. This only happens on netcore3 p7 & p8. I've been using it happily in all netcore3 releases since p2 and never had this problem.

_***PS. This issue also happens on the v2 client***_

This is the call that causes the stallness:
```
var doc = await _container.ReadItemAsync<GrainStateEntity>(id, new PartitionKey(partitionKey), new ItemRequestOptions()
                {
                    ConsistencyLevel = _options.GetConsistencyLevel() //Either Session or null. It happens with both
                });
```
This is my current connection policy
![image](https://user-images.githubusercontent.com/2110596/63183467-00b8a500-c023-11e9-8091-b14fc87b8f6b.png)

**Comment by FluentGuru** [comment]
Related https://github.com/Azure/azure-cosmos-dotnet-v3/issues/717

**Comment by scalablecory** [comment]
@eiriktsarpalis

**Comment by scalablecory** [comment]
Do any operations other than `ReadItemAsync` work?

**Comment by FluentGuru** [comment]
@scalablecory database, stored procedures, collection/container manipulation works

**Comment by eiriktsarpalis** [comment]
@FluentGuru which version of Microsoft.Azure.Cosmos are you using? I notice that a minor version update (3.0.0 -> 3.1.1) happened 4 days ago.

**Comment by FluentGuru** [comment]
@eiriktsarpalis I tried all available versions. Right now I'm using `3.2.0-preview`

**Comment by eiriktsarpalis** [comment]
Can you confirm that 3.2.0-preview does not hang when run against < p7 versions?

**Comment by FluentGuru** [comment]
@eiriktsarpalis I can't. I had to rollback a lot of changes I've done since then :(

**Comment by scalablecory** [comment]
@FluentGuru I'm unable to reproduce this with Preview 7 or Preview 8. Can you please share a small app that reproduces the issue?

**Comment by davidsh** [comment]
@FluentGuru It isn't clear what component of .NET Core might be causing the problem you're having.  We really can't proceed without having a smaller repro that we can analyze.

Please let us know when you are able to isolate what part of .NET Core might be contributing to your problem.  Then we'll be able to re-open this issue with more actionable information.  Thanks!
