### ISSUE TITLE
System.Text.Json: Custom Constructor Support 

### ISSUE THREAD

**Issue by endeffects** [dotnet/corefx#40399]
Please provide support for custom constructors and allow to specify the constructor with an attribute.

**Comment by ahsonkhan** [comment]
cc @steveharter

**Comment by Gnbrkm41** [comment]
https://github.com/dotnet/corefx/issues/38569#issuecomment-503566048
> For the 3.0 release, there is no planned additional support for calling a non-default constructor during deserialization. That would have to be done by a custom converter.

**Comment by layomia** [comment]
Sufficiently similar to https://github.com/dotnet/corefx/issues/40399 - closing as duplicate.

**Comment by gfoidl** [comment]
@layomia you created a endless-loop :wink:
(the link points to the current issue itself)
Did you mean #38569?

**Comment by layomia** [comment]
@gfoidl yes, thank you!

**Comment by etghanibahman** [comment]
Is there any temporary solution for this ?!

**Comment by manne** [comment]
@etghanibahman I have implemented a functionality supporting "custom" constructors. For details read <https://github.com/dotnet/corefx/issues/38569#issuecomment-574886051>
