### ISSUE TITLE
Test failure: System.Text.Json.Serialization.Tests.OptionsTests.Options_GetConverter_GivesCorrectDefaultConverterAndReadWriteSuccess

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#40406]
Test `System.Text.Json.Serialization.Tests.OptionsTests.Options_GetConverter_GivesCorrectDefaultConverterAndReadWriteSuccess` has failed.

```
Error message
Assert.Equal() Failure\r\n ↓ (pos 4)\r\nExpected: 3.14\r\nActual: 3.1400000000000001\r\n ↑ (pos 4)

Stack trace
   at System.Text.Json.Serialization.Tests.OptionsTests.GenericConverterTestHelper[T](String converterName, Object objectValue, String stringValue, JsonSerializerOptions options) in /_/src/System.Text.Json/tests/Serialization/OptionsTests.cs:line 446
   at System.Text.Json.Serialization.Tests.OptionsTests.Options_GetConverter_GivesCorrectDefaultConverterAndReadWriteSuccess() in /_/src/System.Text.Json/tests/Serialization/OptionsTests.cs:line 388
```
Build: -[20190819.1](https://dnceng.visualstudio.com/public/_build/results?buildId=315168&view=logs)(Master)

Details:
https://dnceng.visualstudio.com/public/_build/results?buildId=315168&view=ms.vss-test-web.build-test-results-tab&runId=9114846&resultId=111373&paneView=debug

**Comment by ahsonkhan** [comment]
Looks like certain numbers, like 3.14 don't round-trip, even with G17. The recent change by @WinCPP tried to make use of the workaround for netfx, but that doesn't help:
https://github.com/dotnet/corefx/pull/40197

https://github.com/dotnet/corefx/blob/3d72b56b8e7d1e4e44262be6c45c2aac580bbbc4/src/System.Text.Json/src/System/Text/Json/Writer/Utf8JsonWriter.WriteValues.Double.cs#L98-L111

```C#
double value = 3.14;
const string FormatString = "G17";
string utf16Text = value.ToString(FormatString, CultureInfo.InvariantCulture);
Console.WriteLine(utf16Text); // 3.1400000000000001
```

cc @tannergooding

**Comment by tannergooding** [comment]
This is expected. The parsing algorithm for .net framework is incorrect and will fail to correctly parse some values, even at G17. .NET Framework doesn't provide a way to return more than 17 digits and so there is no workaround.

**Comment by ahsonkhan** [comment]
I see. In that case, the issue has been fixed (changed the test case to double values that do end up round-tripping on netfx). I didn't skip that test for netfx since it has to do with converters and very little to do with formatting doubles.
