### ISSUE TITLE
Incorrect testhost configuration for source-build

### ISSUE THREAD

**Issue by adaggarwal** [dotnet/corefx#40417]
Environment - CentOS docker on RHEL7 Hyper-V vm. 
CoreFX version - 1bb52e6a3db7f3673a3825f3677b9f27b9af99aa
[Sourcebuild](https://github.com/NikolaMilosavljevic/source-build/tree/eb30c269429785b4bc057b61b7f9a163c2383845 )  [PR](https://github.com/dotnet/source-build/pull/1113)

Details:
The testhost that gets cooked up in sourcebuild->corefx->artifacts has a faulty **System.Memory.dll** when compared to the one in standalone corefx. This results in test run failures for source-build corefx tests. It seems to be a configuration issue. 

Steps to repro:

1. Use source-build clone for the commit SHA1 aforementioned. And `build.sh` for a primary build.
2. For setting up test utilities and running the tests; build again with test flag, i.e. `build.sh -test`

[Extra Steps to validate the erroneous dll] -> 

1. Build a standalone corefx using the commit SHA1 mentioned and copy System.Memory.dll from shared testhost to SB/bin/src/corefx.<SHA1>/artifacts/bin/testhost/<>/<>/shared/. 
2. Manually run any of the tests which were failing previously in source-build test build.

**Comment by adaggarwal** [comment]
cc @ericstj @joperezr @crummel

**Comment by ericstj** [comment]
This is the same as https://github.com/dotnet/corefx/pull/40199.  @adaggarwal did you try porting that fix to source build?

**Comment by adaggarwal** [comment]
Thanks for the pointer @ericstj 
I am not able to fetch 808f11f79ca091ed1996611382fd5a097c80669f. Is it an orphan commit?

**Comment by eerhardt** [comment]
> did you try porting that fix to source build?

@ericstj - looking at the fix for #40199, I don't even see those files in the `release/3.0` branch. Is that expected?

**Comment by adaggarwal** [comment]
Referencing #40426 for porting the resolution changes to release/3.0

**Comment by ericstj** [comment]
> @ericstj - were you planning on porting that change to 3.0?

@eerhardt yep.  FYI, git did a clean cherry-pick here despite the move.  GIT ≫ GitHub. 😝

**Comment by adaggarwal** [comment]
@ericstj @eerhardt  While the #40426 is in CI, I tried the changes in my local via a coreFX patch and it works! :)
