### ISSUE TITLE
[System.Text.Json] Serialize throw "System.ArgumentOutOfRangeException" while serializing a JSON string

### ISSUE THREAD

**Issue by Daddoon** [dotnet/corefx#40412]
Hello,

I'm actually having a blocking issue on my Blazor project due to a very strange behavior withing the System.Text.Json serializer.

It seem to me a very specific bug. I'm actually serializing a C# object to a simple string with Newtonsoft.Json.

I get the serialized object, and send it through the InvokAsync interop method, in order to call Javascript and i have this exception:

```
System.ArgumentOutOfRangeException : 'Specified argument was out of the range of valid values.'
```

After digging, i see that **System.Text.Json.JsonSerializer.Serialize** seem faulty, but the weirdest thing is that i only ask the serializer to serialize a string, not a plain class or other things.

It seem that this is some weird serializing conditions in the plugin with non-unicode characters (somehow).

This is OK:

```csharp
System.Text.Json.JsonSerializer.Serialize("ààààaaa");
```

This is OK:

```csharp
System.Text.Json.JsonSerializer.Serialize("{\"$type\":\"BlazorMobile.Common.Interop.MethodProxy, BlazorMobile.Common\",\"TaskIdentity\":\"4d8349dd-0fa7-40d2-b3ca-aaea7814cec4\",\"TaskSuccess\":{\"$type\":\"System.Boolean\",\"$value\":false},\"AsyncTask\":{\"$type\":\"System.Boolean\",\"$value\":false},\"ReturnType\":{\"$type\":\"BlazorMobile.Common.Interop.TypeProxy, BlazorMobile.Common\",\"SerializedData\":\"\\\"BlazorMobile.Common.Models.IgnoredType, BlazorMobile.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\\\"\"},\"ReturnValue\":null,\"InterfaceType\":{\"$type\":\"BlazorMobile.Common.Interop.TypeProxy, BlazorMobile.Common\",\"SerializedData\":\"\\\"SoNG.Mobile.App.Common.Interfaces.IXamarinBridge, SoNG.Mobile.App.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\\\"\"},\"MethodIndex\":{\"$type\":\"System.Int32\",\"$value\":0},\"GenericTypes\":{\"$type\":\"BlazorMobile.Common.Interop.TypeProxy[], BlazorMobile.Common\",\"$values\":[]},\"Parameters\":{\"$type\":\"System.Object[], %CORE%\",\"$values\":[\"\",\"Erreur: Impossible de se connecter a internet\",\"OK\"]},\"ExceptionDescriptor\":null}");
```

This throw an exception:

```csharp
System.Text.Json.JsonSerializer.Serialize("{\"$type\":\"BlazorMobile.Common.Interop.MethodProxy, BlazorMobile.Common\",\"TaskIdentity\":\"4d8349dd-0fa7-40d2-b3ca-aaea7814cec4\",\"TaskSuccess\":{\"$type\":\"System.Boolean\",\"$value\":false},\"AsyncTask\":{\"$type\":\"System.Boolean\",\"$value\":false},\"ReturnType\":{\"$type\":\"BlazorMobile.Common.Interop.TypeProxy, BlazorMobile.Common\",\"SerializedData\":\"\\\"BlazorMobile.Common.Models.IgnoredType, BlazorMobile.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\\\"\"},\"ReturnValue\":null,\"InterfaceType\":{\"$type\":\"BlazorMobile.Common.Interop.TypeProxy, BlazorMobile.Common\",\"SerializedData\":\"\\\"SoNG.Mobile.App.Common.Interfaces.IXamarinBridge, SoNG.Mobile.App.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\\\"\"},\"MethodIndex\":{\"$type\":\"System.Int32\",\"$value\":0},\"GenericTypes\":{\"$type\":\"BlazorMobile.Common.Interop.TypeProxy[], BlazorMobile.Common\",\"$values\":[]},\"Parameters\":{\"$type\":\"System.Object[], %CORE%\",\"$values\":[\"\",\"Erreur: Impossible de se connecter à internet\",\"OK\"]},\"ExceptionDescriptor\":null}");
```

Note the "à" **Impossible de se connecter à internet**.

In my opinion it seem that somehow the serializer is trying to parse something instead of just converting/escaping my plain string, or somehow in THIS condition, the special character throw something.

Thanks in advance for your reviews !

**Comment by Daddoon** [comment]
Actually, removing the last part of my JSON string does not go on exception even with the 'à' character.

See:

```csharp
System.Text.Json.JsonSerializer.Serialize("{\"$type\":\"BlazorMobile.Common.Interop.MethodProxy, BlazorMobile.Common\",\"TaskIdentity\":\"4d8349dd-0fa7-40d2-b3ca-aaea7814cec4\",\"TaskSuccess\":{\"$type\":\"System.Boolean\",\"$value\":false},\"AsyncTask\":{\"$type\":\"System.Boolean\",\"$value\":false},\"ReturnType\":{\"$type\":\"BlazorMobile.Common.Interop.TypeProxy, BlazorMobile.Common\",\"SerializedData\":\"\\\"BlazorMobile.Common.Models.IgnoredType, BlazorMobile.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\\\"\"},\"ReturnValue\":null,\"InterfaceType\":{\"$type\":\"BlazorMobile.Common.Interop.TypeProxy, BlazorMobile.Common\",\"SerializedData\":\"\\\"SoNG.Mobile.App.Common.Interfaces.IXamarinBridge, SoNG.Mobile.App.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\\\"\"},\"MethodIndex\":{\"$type\":\"System.Int32\",\"$value\":0},\"GenericTypes\":{\"$type\":\"BlazorMobile.Common.Interop.TypeProxy[], BlazorMobile.Common\",\"$values\":[]},\"Parameters\":{\"$type\":\"System.Object[], %CORE%\",\"$values\":[\"\",\"Erreur: Impossible de se connecter à internet\",\"OK\"]}}}}")
```
It may not be related to unicode, still the behavior is not normal.

**Comment by Daddoon** [comment]
The only "workaround" i have found for my plugin is to convert the string to Base64, in order to avoid this bug.

Still this is less than ideal as i'm stuck with a design that look like C# object -> Newtonsoft.Json -> Base64 -> InvokeAsync that will internally call System.Text.Json himself, as the serializer behavior cannot be changed for the moment with Blazor.

**Comment by ahsonkhan** [comment]
This is a duplicate of https://github.com/dotnet/corefx/issues/40409.
https://github.com/dotnet/corefx/issues/40409#issuecomment-522514553

Can you try with preview 9 bits (or latest nightly)? It is no longer reproducible on master.

Please try the nightly SDK/runtime with the fix to verify it works (https://github.com/dotnet/core-sdk#installers-and-binaries), or wait till preview 9 ships. Alternatively, you could reference the latest S.T.Json NuGet package. For example:

```csproj
  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="4.6.0-preview9.19413.13" />
    <PackageReference Include="System.Text.Encodings.Web" Version="4.6.0-preview9.19413.13" />
  </ItemGroup>
```

This bug was introduced in preview 8 but has since been fixed (preview 9 and in master). See https://github.com/dotnet/corefx/pull/39524#discussion_r314138162

> Actually, removing the last part of my JSON string does not go on exception even with the 'à' character.

Yep, it is difficult to hit that code path easily. It has to do with where the unicode character shows up and how much ascii text is before/after.

cc @steveharter

**Comment by Daddoon** [comment]
Sorry for the duplicate !

Thanks for the info and the feedback.

So i will just let that sink in, as it is already fixed for preview9. I will just wait and eventually post a notice on my documentation.

Closing.
