### ISSUE TITLE
Process.Start isn't using vfork on Ubuntu 18.04

### ISSUE THREAD

**Issue by ayende** [dotnet/corefx#40410]
The following code will fail to run on Ubuntu 18.04 system that has a 0.5 RAM + 1 GB Swap.

```
using System;
using System.Diagnostics;

namespace Tryouts
{
    public static class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Starting...");
            var mem = new byte[1024 * 1024 * 768];
            for (int i = 0; i < mem.Length; i++)
            {
                mem[i] = (byte)i;
            }

            Console.WriteLine("Ready...");

            Process.Start("/bin/bash", "-c echo 'test'").WaitForExit();

        }
    }
}
```

I'm getting the output:

```
Starting...
Ready...

Unhandled Exception: System.ComponentModel.Win32Exception: Cannot allocate memory
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName, String arguments)
   at Tryouts.Program.Main(String[] args) in /home/ubuntu/test/Program.cs:line 19
```

This is a brand new machine and I followed the setup instructions here:
https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current

I run `strace -e trace=clone dotnet /home/ubuntu/test/bin/Debug/netcoreapp2.2/test.dll` and got:

`clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f43cf865a10) = -1 ENOMEM (Cannot allocate memory)`

Looking at the code, it seems that the code wants to use `vfork`, here:

https://github.com/dotnet/corefx/blob/b3686977e17f885fdfbcfbc2906d32f9678a8726/src/Native/Unix/configure.cmake#L121

And the `HAVE_VFORK` is set here:

https://github.com/dotnet/corefx/blob/5c83394112febe1b481ab1c0b61a45c850677165/src/Native/Unix/System.Native/pal_process.c#L342

I check the file on that machine, and `vfork` certain exists there, but maybe for build reason, this isn't set properly? 

The end result is that calling `Process.Start` is going to kill us if we are over 50% memory utilization.

**Comment by stephentoub** [comment]
You're using 2.2. The change to use vfork was in 3.0.

**Comment by ayende** [comment]
Oh, I see, thanks
