### ISSUE TITLE
HTTP2: Header corruption issue in SocketsHttpHandler

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/corefx#40459]
I'm able to consistently reproduce a HTTP2 header corruption issue present with SocketsHttpHandler. The issue occurs in GET operations sending headers whose values are url encodings of the `+` character. Here's how that might look:
```
header-0: %2b%2b%2b, %2b, %2b%2b%2b
header-1: %2b%2b, %2b, %2b%2b
```
The code for populating the headers is the following:
```csharp
public void PopulateWithRandomHeaders(HttpRequestHeaders headers)
{
    for (int i = 0; i < 5; i++)
    {
        headers.Add($"header-{i}", Enumerable.Range(0, 5).Select(MkHeaderValue));
    
        string MkHeaderValue(int _) => HttpUtility.UrlEncode(new String('+', _random.Next(16,18)));
    }
}
```
Every request contains 5 headers, each containing 5 values. Importantly, every value is a url encoding of either 16 or 17 `+` characters, chosen randomly. I was not able to get the issue to reproduce without randomizing the length of header values.

The server accepting these requests will read the headers and perform basic validation (i.e. every value is a repeated `%2b` string). If successful returns 200, otherwise it will give 400.

### Reproduction Steps

Check out [this branch](https://github.com/eiriktsarpalis/corefx/tree/header-corruption-repro). Then using the latest 3.0.1xx nightly from the command line:
```
cd src/System.Net.Http/tests/StressTests/HttpStress
dotnet run -c Release -- -serverUri http://127.0.0.1:5001/ -ops 2 -cancelRate 0 -n 1 -seed 0
```
The run will fail on the 13th iteration with the following message:
```
Error from iteration 13 ( 2: GET Headers) in task 0 with 13 successes / 1 fails:
System.Exception: Server received bad headers:
header-0: %2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b, %2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b, %2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b, %2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b, %2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b
header-1: %2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b, %2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b, %2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b, %2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b, %2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b
header-2: %2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b, %2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b, %2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b, %2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b, %2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b
header-3: %2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b, %2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b, %2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b, %2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b, %2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b%2b
header-4: cmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGeA0cmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGeA0cmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGeA0cmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGeA0cmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdGcmdG
   at HttpStress.ClientOperations.<>c.<<get_Operations>b__1_2>d.MoveNext() in C:\Users\eitsarpa\devel\dotnet\corefx\src\System.Net.Http\tests\StressTests\HttpStress\ClientOperations.cs:line 227
--- End of stack trace from previous location where exception was thrown ---
   at HttpStress.StressClient.<>c__DisplayClass12_0.<<StartCore>g__RunWorker|1>d.MoveNext() in C:\Users\eitsarpa\devel\dotnet\corefx\src\System.Net.Http\tests\StressTests\HttpStress\StressClient.cs:line 129
```
As you can see the contents of the final header have been silently corrupted. Some more notes:
* Stress run is using a single worker, so there's no contention among requests.
* The failure happens deterministically (by fixing the `-seed` parameter passed to the `Random` instance).
* Impacts about 5% of requests.
* Reproduces using Kestrel and http.sys, http and https, Windows & Linux.

Captured frames on wireshark:
![image](https://user-images.githubusercontent.com/2813363/63377532-37c2e980-c388-11e9-86aa-3facc4965735.png)

It looks like the issue lies with the client. I would suspect it's an HPACK encoder bug. This is unrelated to the [other data corruption issue](https://github.com/dotnet/corefx/issues/40194).

**Comment by geoffkizer** [comment]
This is just a guess, but the issue may be here: https://github.com/dotnet/corefx/blob/d3911035f2ba3eb5c44310342cc1d654e42aa316/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HPack/HPackEncoder.cs#L294

In all other cases where we call IntegerEncoder.Encode, we initialize the first byte of the target buffer so that the high bits (the ones not used for the integer encoding) are initialized correctly. Here, we don't seem to do that. If the high bit here happens to be 1, then that indicates huffman encoding, which is incorrect.

**Comment by scalablecory** [comment]
@geoffkizer is correct. Definitely want this fixed for 3.0 :)

**Comment by jkotalik** [comment]
@scalablecory does this bug also apply to the aspnetcore implementation? https://github.com/aspnet/AspNetCore/blob/master/src/Servers/Kestrel/Core/src/Internal/Http2/HPack/HPackEncoder.cs#L138

**Comment by jkotalik** [comment]
From what I can tell, it doesn't because we set buffer[0] to 0. https://github.com/aspnet/AspNetCore/blob/master/src/Servers/Kestrel/Core/src/Internal/Http2/HPack/HPackEncoder.cs#L136

**Comment by scalablecory** [comment]
@jkotalik I agree, aspnet looks fine.

**Comment by eiriktsarpalis** [comment]
Confirming that adding initialization before that particular line eliminates the problem. Will follow-up with a PR but want to create a failing unit test first.

**Comment by stephentoub** [comment]
Re-opening to track port to release/3.0
