### ISSUE TITLE
Handle properties on types in System.Reflection.Metadata should be public

### ISSUE THREAD

**Issue by devhawk** [dotnet/corefx#4045]
It appears that all types that wrap metadata rows (such as TypeDefinition) have a private Handle property. [Example](https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/src/System/Reflection/Metadata/TypeDefinition.cs#L36-L39):

``` csharp
// from TypeDefinition.cs
private TypeDefinitionHandle Handle
{
    get { return TypeDefinitionHandle.FromRowId(RowId); }
}
```

I find that I often use LINQ to search thru table results looking for specific information, but need the handle at the end. For example, this code searches thru the TypeReferences for System.Object - useful for finding all the class objects in an assembly. Note how I have to create an anonymous type to hold the handle separately from the type reference, even though the TypeReference can easily construct a handle internally. 

``` csharp
_reader.TypeReferences
    .Select(h => new
    {
        Handle = h,
        TypeRef = _reader.GetTypeReference(h)
    })
    .Where(o => _reader.GetString(o.TypeRef.Name) == "Object" && _reader.GetString(o.TypeRef.Namespace) == "System")
    .Select(o => o.Handle)
    .Single();
```

I'd much rather write this:

``` csharp
_reader.TypeReferences
    .Select(h => _reader.GetTypeReference(h))
    .Where(tr => _reader.GetString(tr.Name) == "Object" && _reader.GetString(tr.Namespace) == "System")
    .Select(tr => tr.Handle)
    .Single();
```

**Comment by joshfree** [comment]
@nguerrera @tmat

**Comment by tmat** [comment]
We can't always reconstruct the handle the entity it originated from. For example, if WinRT projection is applied to TypeReferenceHandle (e.g. DateTime, Color, Vector, Matrix, etc.) we may map it to an index into the projection table when constructing TypeReference struct. The struct doesn't store the original Handle.  

Currently, I think this is only the case for TypeReferences but the reader is designed so that new projections can be introduces without breaking APIs.

**Comment by tmat** [comment]
BTW, I'd recommend to compare for type name as follows:

```
reader.StringComparer.Equals(typeRef.Name, "Object") &&
reader.StringComparer.Equals(typeRef.Namespace, "System");
```

This comparison doesn't allocate any objects.

**Comment by devhawk** [comment]
If the value returned from TypeReference.Handle might not match the value passed into MetadataReader.GetTypeReference because of type projection, does that make the case for exposing Handle property publicly stronger? If I'm caching the entity handle for a well known type that gets projected into another type (say IVector<T> -> IList<T>), won't I need the projected handle (i.e. IList<T>) rather than the unprojected handle (i.e. IVector<T>).

Thanks for the suggestion on StringComparer.

**Comment by tmat** [comment]
No, a handle for the projected type doesn't exist. The projected type ref doesn't have representation in the assembly.

**Comment by nguerrera** [comment]
Closing since this was a very deliberate design decision to make going from Handle to record one directional.
