### ISSUE TITLE
Volatile usage in ConcurrentDictionary

### ISSUE THREAD

**Issue by scalablecory** [dotnet/corefx#40452]
`ConcurrentDictionary` has these `Volatile.Write` calls which are performed inside of a `lock`:

https://github.com/dotnet/corefx/blob/2fac89f63c644ab81d936d62c91e6003302e718d/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs#L393
https://github.com/dotnet/corefx/blob/2fac89f63c644ab81d936d62c91e6003302e718d/src/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs#L539

Is the `lock` not acting as a sufficient barrier here so that we still need to use `Volatile.Write`?

**Comment by stephentoub** [comment]
> Is the lock not acting as a sufficient barrier here so that we still need to use Volatile.Write?

No.  Reads are not performed while holding the lock, and we need to ensure that any objects published will only be published once all previous writes (such as to initialize those objects) have been published as well.
