### ISSUE TITLE
Co-locate Reference Docs and Sample Code within the Repo on a Per-Library Basis

### ISSUE THREAD

**Issue by cartermp** [dotnet/corefx#4046]
# Problem

As .NET Core moves the platform towards being more modular, sample code and reference docs should move in that direction too.  We should have a good story in place for reference docs and samples.

**Note:** Samples here mean samples which _only_ call the API they are co-located with.  These are not cross-cutting, they don't cover scenarios, and they don't involve other app models (ASP.NET, UWP, etc).  They will be console apps which cover only the "happy path" of an API in a demonstrative way.
# Solution

Co-locate reference docs and samples with the code they describe and demonstrate usage of, on a per-library basis.

The existing structure of libraries in corefx would be altered as such (using `System.Linq` as an example):

Before:

```
/src
|__System.Linq
   |__/ref
   |__/src
   |__/tests
```

After:

```
/src
|__System.Linq
   |__/ref
   |__/doc (new! contains documentation, perhaps in markdown files)
   |__/src
   |__/samples (new! contains a buildable sample project)
   |__/tests
```

Sample code in `/samples` will be embedded directly into docs in the `/doc` folder so that any time sample code is changed, the documentation is automatically updated.

See [an example of how this may look](https://github.com/cartermp/corefx/tree/samples/src/System.Linq) for some more detail.
## Building

The proposed solution would affect the build process.  I see two options here:

a. Force `/samples` to build before a release
b. Eventually have `/samples` build as "full" build, but do not require that to release

Both have their benefits and drawbacks which are worth discussing.

Finally, hooks will have to eventually be added to force other sample projects outside of corefx to build so their sample code can also stay up-to-date.
# Justification

This solution will form the "core" of an eventual samples system which will ultimately accomplish the following:
- Easier to update reference docs and samples if they live with the code they describe
- No code samples in reference docs will be out-of-date and fail to compile
- No code samples in any .NET Core conceptual docs will be out-of-date and fail to compile
- No .NET Core sample applications will be out-of-date and fail to compile

We want to avoid a future scenario where developers have to turn to places like StackOverflow to learn how to use an API because the sample code in the documentation is outdated and/or won't compile.  If all our .NET Core samples are tied into the build system, we can avoid that scenario.

**Comment by richlander** [comment]
Cool! This looks good.

I see you chose csproj for your sample. I know we use csproj extensively in the repo. I'm wondering if that's the best choice for samples since we'll be encouraging xproj for people writing apps. Thoughts? There is also a nice opportunity to standardize on a single way to write samples across the Core and ASPNET repos.

/cc @davidfowl, @DamianEdwards, @terrajobst

**Comment by CIPop** [comment]
/cc @SidharthNabar @davidsh @danroth27 
I like the initiative and the folder structure. Here are a few observations/questions:
  1. How does this work with current MSDN articles:

      a. Will the docs have a back-link to MSDN? 
      b. Can MSDN reference these docs and samples?
  2. How does this align with ASP.Net's documentation at https://docs.asp.net/en/latest/?
  3. How does this align with samples on MSDN, [Windows Store Github](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples) and code snippets and samples in ASP's docs and GitHub project?

**Comment by cartermp** [comment]
@richlander Good idea.  I chose csproj just because it was the same used in that library.  Making the switch to xproj is a good idea if that's how ASPNET is doing it too.

@CIPop I see this as aligning well with ASP.NET docs/samples efforts.  So long as code snippets come from some project that coincides with those docs, that project can have packages restored and be built whenever a new version of a corefx library it uses is released.  I can see a similar thing happening for UWP samples, too.

I don't think I can definitively answer any of your questions about MSDN.  It's an open question for me.

**Comment by mellinoe** [comment]
A few things:
* As far as I am aware, .xproj/project.json projects are for ASP.NET apps, which we don't build here, and are only one of the application types customers might want samples for. I'd prefer to go with whatever will integrate into our current build process the easiest and smoothest, which is probably regular csproj's.
* Do we want these samples to "break the build", so to speak, if incompatible changes are made to the source? If so, do we want them to use all project-to-project references? Our tests right now use project-to-project references, but only for the actual library they are testing. Samples are going to be a bit more "cross-cutting", so do we want them to reference all of the libraries they use with a project reference?
    * Alternatively, do we just want to use NuGet references and catch samples breaks after the fact? I think I would prefer if there were separate builds for the samples so that they can be fix "out-of-band" from regular product updates. We would still consider it a priority to keep the samples running, but it wouldn't be an immediate checkin blocker if you broke the samples.
* I think everyone likes the idea of documentation being close to the code and easy to edit, but I'll echo @CIPop 's concerns about how everything (meaning the overall documentation story) is going to align.

**Comment by richlander** [comment]
The meta thing is that we're going to enough content in the repo to generate ref docs. The samples will not be cross-cutting. They will be brain-dead simple samples that demonstrate the most typical use cases for an API. Those are the ones we want to show up in our ref docs. They will be more typical and more simple than the tests so they should /absolutely/ break the build.

The resulting docs will have no explicit affinity to MSDN in the sense that they could be built with and deployed anywhere as a self-sufficient experience. Yeah, this an open source project! Microsoft is actually doing the right thing!

project.json and xproj are not ASP.NET specific. I know it seems like they have been. We're going to adopt it for more things. There will be no UWP samples in this repo. They will be elsewhere. These will all be console apps that demonstrate basic APIs. We want all the samples to be runable. They should be so simple that you can take one of these samples and run it on Mono.

**Comment by cartermp** [comment]
Updated the Issue text to clarify what we mean by samples.  As @richlander said, these will merely be console apps which will cover the common use cases of an API in a demonstrative way.  The sample *projects* themselves will only ever contain a subset of the dependencies that the test projects do, so there shouldn't be any issues in resolving those.

**Comment by CIPop** [comment]
+1 on @richlander 's idea of separating the simple cases from the FunctionalTests. It'll make it much simpler for customers to take a look and understand what the APIs are doing.

-1 on duplicating FunctionalTest code. We need to think of a way to easily integrate the sample code in our existing CI system.

> I see this as aligning well with ASP.NET docs/samples efforts. So long as code snippets come from some project that coincides with those docs, that project can have packages restored and be built whenever a new version of a corefx library it uses is released (probably via a hook). I can see a similar thing happening for UWP samples, too.

What I'm trying to get at is: if I'm a developer and I want to learn how to build a simple lib that I'll share between my device Apps and webservices (think of a custom OAuth lib), where should I start looking for answers: MSDN, ASP.NET Docs, CoreFX repo, the Windows Store Samples?

If the answer is everywhere: how do we make sure that the developer understands where these locations are?

**Comment by weshaggard** [comment]
@richlander I would like to understand more of your thoughts on xproj vs csproj. Right now this repro uses msbuild and standard csproj files for building. I do not want to introduce xproj files and mix the builds without better understanding the direction.

**Comment by karelz** [comment]
Anything happening on this one?

**Comment by cartermp** [comment]
Nope.  We won't be doing this for the foreseeable future.
