### ISSUE TITLE
Cannot run under ARM Linux

### ISSUE THREAD

**Issue by whuanle** [dotnet/corefx#40473]
System environment:

```
Linux 3.10.53-HULK2 #1 SMP PREEMPT Wed Jul 12 19:47:39 CST 2017 armv7l GNU/Linux

PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

```

I have a console app，use of .NET Core 2.x or 3.0

![image](https://user-images.githubusercontent.com/2189761/63394737-a12c1200-c3f3-11e9-9236-eba60d776133.png)

```
ubuntu@ubuntu:~$ file ConsoleApp3 
ConsoleApp3: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-, for GNU/Linux 2.6.32, BuildID[sha1]=af5075900c7b6efa51a7db214b11cb7566bd5ef1, stripped

```
but...

```
root@aaa:/tmp/publish# ./libsos.so 
Illegal instruction
root@aaa:/tmp/publish# ./ConsoleApp3
bash: ./ConsoleApp3: No such file or directory

```
Unable to install SDK and Runtime... 
This is an industrial development board,I can't run my .NET Core program here.Even independent publish releases....
No matter which version I use，.NET Core 2.x or 3.0.

**Comment by Gnbrkm41** [comment]
Try `dotnet ConsoleApp3.dll`?

**Comment by whuanle** [comment]
> ~试试`dotnet ConsoleApp3.dll`？~ 请忽略这一点，抱歉 😅

help me...

**Comment by whuanle** [comment]
No one help me... ...
