### ISSUE TITLE
Deserialization support for more implementing types in JsonSerializer

### ISSUE THREAD

**Issue by layomia** [dotnet/corefx#40479]
https://github.com/dotnet/corefx/pull/39001 added support for types derived from [BCL collections that are natively supported by the serializer](https://github.com/dotnet/corefx/issues/36643), with the exception of read-only types, and types that do not implement any of:

- `IList`
- `ICollection<T>`
- `Stack<T>`
- `Queue<T>`
- `IDictionary`
- `IDictionary<string, TValue>`

Some examples are `public class StackWrapper : Stack { }` and [StringValues](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.primitives.stringvalues?view=aspnetcore-3.0). The serializer throws a `NotSupportedException` when a deserialization attempt is made for these types.

More investigation/design needs to be done, but these types can be supported by using reflection to probe for the right constructors to populate them if we determine to support them in the future.

**Comment by Tornhoof** [comment]
The problem with Stack is simply, do you reverse the order during deserialization or not. I'm sure @jamesnk has input on that. I'm not sure that there is only one valid answer there so you might need to consider a setting for it.

**Comment by layomia** [comment]
The default behavior in the serializer for `Stack<T>`, `Stack`, `ImmutableStack<T>`, and types that derive from `Stack<T>` is:

Deserialization: if the payload is "[1,2,3]", we return a stack with 3 at the top.
Serialization: if stack's contents are [1, 2, 3] with 3 at the top, we return JSON payload [3,2,1].
[This is what JSON.Net does](https://github.com/JamesNK/Newtonsoft.Json/issues/971).

I agree that a reversal setting should be considered if there's a demonstrated need. There'd be a performance cost for reversal opt-ins.
