### ISSUE TITLE
Replace tfm based constants with SDK ones

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#40484]
We should replace constants for different target frameworks with the auto-generated ones that come with the SDK and are available in the product.

1. Remove https://github.com/dotnet/corefx/blob/38aa9151607cb63bb569beb42880057ba2cd3da0/Directory.Build.props#L345-L356
2. Replace these constants in the C# soures with the SDK ones:

`NETCOREAPP, NETCOREAPP1_0, NETCOREAPP1_1, NETCOREAPP2_0, NETCOREAPP2_1, NETCOREAPP2_2` ...

https://docs.microsoft.com/en-us/dotnet/core/tutorials/libraries

@Anipik in case you are interested in picking this one up.

cc @ericstj

**Comment by ViktorHofer** [comment]
We should only keep the ones which aren't defined by the SDK, ie when we are ahead of the SDK.

**Comment by eriawan** [comment]
@ViktorHofer 

This seems quite easy and I'm sure it's non-breaking.
Could I take this issue?

**Comment by ViktorHofer** [comment]
Sure. You want to leave the constants for the versionless tfms: `netcoreapp`, `netfx` and `uap`. Everything else should be replaceable.
