### ISSUE TITLE
[macOs 10.15] Removing X509Certificate from store can terminate process

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/corefx#40491]
Repro steps:
* `dotnet dev-certs https --trust`
* `dotnet run` below program
```csharp
static void Main(string[] args)
{
    var oid = "1.3.6.1.4.1.311.84.1.1";
    using (var store = new X509Store(StoreName.My, StoreLocation.CurrentUser))
    {
        store.Open(OpenFlags.ReadWrite);
        var certs = store.Certificates.OfType<X509Certificate2>();
        var matchingCerts = certs.Where(c => c.Extensions.OfType<X509Extension>().Any(e => string.Equals(oid, e.Oid.Value, StringComparison.Ordinal)));

        foreach (var cert in matchingCerts)
        {
            Console.WriteLine(cert);
            store.Remove(cert); // terminates here
            Console.WriteLine("Removed cert");
        }

        store.Close();
    }
}
```

**Comment by stephentoub** [comment]
> // terminates here

What error do you get?  Is there an exception?  Does it seg fault?

**Comment by BrennanConroy** [comment]
Seg fault

**Comment by stephentoub** [comment]
cc: @bartonjs

**Comment by bartonjs** [comment]
@BrennanConroy Where'd you get the build you're running? (I downloaded the preview8 tgz, disabled gatekeeper after I got tired of clicking approve on the libraries, and then `./dotnet dev-certs https --trust` fails with illegal instruction... so I'm not sure we're in the same state)

**Comment by vcsjones** [comment]
Interestingly I can reproduce this on .NET Core 3.0 (exite code is 139) but not 2.2. 2.2 gives a managed permission exception.

**Comment by BrennanConroy** [comment]
@bartonjs I'm using:
* Microsoft.AspNetCore.App 3.0.0-preview9.19405.4
* Microsoft.NETCore.App 3.0.0-preview8-28379-12
* SDK 3.0.100-preview9-013697

**Comment by bartonjs** [comment]
Looks like I'm getting kPOSIXErrorEPERM when trying to export the private key associated with the newly generated RSA key to feed into the cert creation.  Wonder what got broken during upgrade...

**Comment by vcsjones** [comment]
@bartonjs Do you mean when you are doing `dotnet dev-certs https --trust` to create a local certificate?

I already had the certificate locally. The issue I am seeing when trying to remove the certificate from the store looks like a double release of a CFTypeRef.

**Comment by bartonjs** [comment]
> Do you mean when you are doing dotnet dev-certs https --trust to create a local certificate?

Yep.  On a whim I tried using the installer.pkg instead of just the tgz.  (Different source, and no longer under Downloads), and that one worked fine.  So now I'm at least in a place where I can try to see the right answer :smile:

**Comment by bartonjs** [comment]
Hmm.  `CheckTrustSettings` is doing a CFRelease on cert if `SecTrustSettingsCopyTrustSettings` returns `noErr` (aka "I have trust rules and need to fail this") but then moves on to ask a followup question.

Seems like the right answer is that CheckTrustSettings shouldn't be calling CFRelease since it wasn't the one that made the cert object be born.

So, to be fair, it only crashes when it was about to throw an exception saying it wasn't going to do the removal :) (We don't support removing certs from the keychain that have custom trust rules)

**Comment by bartonjs** [comment]
Yep, -2/+2 line fix seems to work.

**Comment by bartonjs** [comment]
(Caused by the refactoring in #32670, only took 10 months to find it :smile: ... perhaps 10.13/10.14 had `cert` not go to zero as long as the SecIdentityRef was still alive, and 10.15 doesn't do that anymore.)
