### ISSUE TITLE
Configuration=Release (or any specific setting of Configuration) broken

### ISSUE THREAD

**Issue by mmitche** [dotnet/corefx#405]
If Configuration is set, the build fails (from root).

This is because we include the Microsoft common targets before we set up basic properties.  The common targets set up the basic configuration properties, but avoid doing so if any are explicitly set.

The fix, I think is to move the basic properties we set into the dir.props in corefx.

**Comment by weshaggard** [comment]
These are already setup in src\dir.props. Is this an issue that they break the other projects like the proj files themselves?

**Comment by weshaggard** [comment]
@mmitche I believe this issue has been fixed so I'm closing. If that is not the case please reopen.
