### ISSUE TITLE
Add System.Reflection.PathAssemblyResolver support for 'retargetable' assemblies

### ISSUE THREAD

**Issue by ryalanms** [dotnet/corefx#40523]
.assembly extern retargetable mscorlib
{
.publickeytoken = (7C EC 85 D7 BE A7 79 8E ) // |.....y.
.ver 2:0:5:0
}

If any assemblies loaded by `MetadataLoadContext` were built against some older versions of mscorlib, `PathAssemblyResolver` will fail to match any newer versions of mscorlib present in `assemblyPaths`, due to a public key token mismatch.  `PathAssemblyResolver` already supports taking the most recent version for target assemblies with an empty public key token. 

https://github.com/dotnet/corefx/blob/master/src/System.Reflection.MetadataLoadContext/src/System/Reflection/PathAssemblyResolver.cs#L80

Add support for most-recent assembly match when assembly being resolved is 'retargetable'.

**Comment by vatsan-madhavan** [comment]
We are trying to address https://github.com/dotnet/wpf/issues/1451 (potentially for 3.0). @ryalanms thinks that we'd need our own implementation of a `MetadataAssemblyResolver` that's almost exactly like `PathAssemblyResolver`, with a bit of [extra intelligence](https://github.com/dotnet/wpf/commit/99d9347a9bcbb4148a59e4b7867954abacc25a21#diff-9ae9ce8633a194b69ee08558488f8408R84) for dealing with retargetable assemblies. 

This seems more suitable for `PathAssemblyResolver` itself. Thoughts? 

/cc @rladuca

**Comment by ericstj** [comment]
Can you wrap PathAssemblyResolver?

**Comment by ryalanms** [comment]
Yes, we could but PathAssemblyResolver has private members, and the wrapper would need to keep track of the assemblyPaths and have similar matching logic and error handling.

**Comment by ericstj** [comment]
Maybe a better way to phrase this is that PathAssemblyResolver ought to use a resolution policy that is similarly permissive as the normal load path.  Presumably that normal load path handles retargetable assemblies correctly.  @vitek-karas

**Comment by ryalanms** [comment]
It also looks like RoAssemblyName.ToAssemblyName() doesn't copy AssemblyName.Flags, which includes AssemblyNameFlags.Retargetable.

**Comment by steveharter** [comment]
I have a prototype at https://github.com/steveharter/dotnet_corefx/tree/RetargetableAsm

It adds support for `AssemblyNameFlags.Retargetable` and does the extra check in PathAssemblyResolver to detect.

Due to the `AssemblyNameFlags.Retargetable` support, it can't be worked around in a custom\wrapped PathAssemblyResolver.

Thus we need to determine if this meets the bar for 3.0 -- how common is this scenario?

**Comment by ryalanms** [comment]
Thanks, @steveharter.  This looks great.  

Any applications ported from .NET Framework to .NET Core that rely on older versions of NuGet packages may hit this, so I believe it is a common scenario.

**Comment by vatsan-madhavan** [comment]
@ericstj thoughts on how common this is going to be, and whether this will become a common enough issue during migration?

**Comment by hallatore** [comment]
> I brought this up in tactics and their indication was won't fix for now and consider for 3.1 if we get more feedback on this blocking multiple packages.

It seems to block a lot of legacy WPF apps when porting them to core. And as it stands now there are no workaround to fix it, since the nuget packages causing this usually are quite old.

This also worked in preview3 and earlier. So my [Netling](https://github.com/hallatore/netling) app is already ported and working. As long as I compile it with the old preview SDK.

**Comment by terrajobst** [comment]
Given the adoption of PCLs on NuGet, it seems @ericstj's suggestion should work for most components that are likely used by WPF apps. Postponing this until we see more evidence for this seems reasonable. Bringing all the complexity of PCLs v1 doesn't seem worth it at this point.

**Comment by ericstj** [comment]
Closing as this is fixed in master and currently "won't fix" for 3.0.
