### ISSUE TITLE
Inconsistency of System.Text.Json behavior between .NET Framework and .NET Core

### ISSUE THREAD

**Issue by DenSmoke** [dotnet/corefx#40533]
`JsonSerializer.Serialize` works differently with `double` depending on target.
I wrote simple test to check `System.Text.Json` behavior comparing to `Newtonsoft.Json`
```C#
public struct TestStruct
{
    public TestStruct(double number)
    {
        DoubleField = number;
    }

    public double DoubleField { get; set; }
}

public class JsonTest
{

    [Theory]
    [InlineData(0.99999999999999)]
    [InlineData(0.999999999999999)]
    [InlineData(0.9999999999999999)]
    [InlineData(0.99999999999999999)]
    public void SystemTextJsonTest(double number)
    {
        var data = new TestStruct(number);
        var datastring = JsonSerializer.Serialize(data);
        var deserializedData = JsonSerializer.Deserialize<TestStruct>(datastring);
        Assert.Equal(data.DoubleField, deserializedData.DoubleField);
    }

    [Theory]
    [InlineData(0.99999999999999)]
    [InlineData(0.999999999999999)]
    [InlineData(0.9999999999999999)]
    [InlineData(0.99999999999999999)]
    public void NewtonsoftJsonTest(double number)
    {
        var data = new TestStruct(number);
        var dataString = Newtonsoft.Json.JsonConvert.SerializeObject(data);
        var deserializedData = Newtonsoft.Json.JsonConvert.DeserializeObject<TestStruct>(dataString);
        Assert.Equal(data.DoubleField, deserializedData.DoubleField);
    }
}
```
Results
![image](https://user-images.githubusercontent.com/16131575/63589861-e64a7280-c5b2-11e9-9390-fd31508edabd.png)

For some reason `JsonSerializer.Serialize` rounds `double` when it exceeds 17 digits, but `JsonConvert.Serialize` doesn't.

I have ASP.NET Core Web API which is sending good JSON provided by `System.Text.Json` and this JSON is being deserialized on .NET Framework without problems so the problem is only with `JsonSerializer.Serialize`

**Comment by stephentoub** [comment]
cc: @tannergooding

**Comment by Wraith2** [comment]
Probably a consequence of https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/

**Comment by ahsonkhan** [comment]
As I understand it, we use "G17" on full framework as part of this change https://github.com/dotnet/corefx/pull/38322 since the defaults produce fewer strings that round-trip. 

I believe the inconsistency you observed is expected due to the limitations in netfx (https://github.com/dotnet/corefx/issues/40406#issuecomment-522552006).

https://github.com/dotnet/corefx/blob/3d72b56b8e7d1e4e44262be6c45c2aac580bbbc4/src/System.Text.Json/src/System/Text/Json/Writer/Utf8JsonWriter.WriteValues.Double.cs#L98-L142

**Comment by tannergooding** [comment]
Yes, this is by design; as per my explanation in the comment(s) @ahsonkhan linked to above.
