### ISSUE TITLE
Use a custom PFX/PKCS12 loader/exporter on non-Windows platforms

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#40539]
We have a slew of bugs related to inconsistencies between the Windows PFX loader (PFXImportCertStore), the Unix PFX loader (PKCS12_parse), and the macOS PFX loader (SecItemImport), and their paired export functions:

* #2743
* #2745
* #2746
* #11046
* #16705
* #24225
* #24226
* #26397
* #30946
* #31746
* #37599

(And probably others)

Now that we have experience with manually loading PKCS#12/PFX content (the `Pkcs12Info` class) and writing it (`Pkcs12Builder`), we should just use a custom loader and unify the experience across the platforms.

**Comment by danieljsummers** [comment]
I'll second that. Just ran into the same issue with .NET Core 2.2.6; thankfully, it was just the `www-data` user that was affected. I can run the process as another non-root user, which is a fine workaround.
