### ISSUE TITLE
HttpClient use different host in ssl certificate and http request

### ISSUE THREAD

**Issue by pengweiqhca** [dotnet/corefx#40531]
Certificate host is iovip.qbox.me, http request host is image.tuhu.cn. How can I do?
``` C#
using (var client = new HttpClient())
using (var request = new HttpRequestMessage(HttpMethod.Get, "https://iovip.qbox.me/test/FtPFFB2e_qh1isgop4jyxG68k4tE_w2880_h1800.jpg@200w_200h_100q.webp"))
{
	request.Headers.Host = "image.tuhu.cn";

	using (var response = await client.SendAsync(request))
	{
		Console.WriteLine(response.StatusCode);
	}
}
```

**Comment by eiriktsarpalis** [comment]
It seems that the host you are trying to connect to is using an invalid certificate. Most clients/browsers will refuse to connect unless explicitly overridden. This can be done with HttpClient too, see [this SO question](https://stackoverflow.com/questions/12553277/allowing-untrusted-ssl-certificates-with-httpclient) for more pointers. If using .NET Core and SocketsHttpHandler you need to override the validation callback located [here](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.ssloptions?view=netcore-2.2#System_Net_Http_SocketsHttpHandler_SslOptions).

**Comment by pengweiqhca** [comment]
I want implement this function through.net core, http status code is 200 rather than 404
``` bash
curl https://iovip.qbox.me/test/FtPFFB2e_qh1isgop4jyxG68k4tE_w2880_h1800.jpg@200w_200h_100q.webp -H 'HOST: image.tuhu.cn' --head
```

**Comment by davidsh** [comment]
When I use a  browser on this URL

>https://iovip.qbox.me/test/FtPFFB2e_qh1isgop4jyxG68k4tE_w2880_h1800.jpg@200w_200h_100q.webp

it works fine.  Analysis on the "iovip.qbox.me" server shows that the DNS returns 20 different IP addresses.  That's ok.

I haven't checked all the particular servers but it seems that the SSL certificate being used is a wildcard certificate:

![image](https://user-images.githubusercontent.com/7684835/63694490-6ba86f80-c7cb-11e9-8840-8251358fdfa4.png)

But the wildcard pattern is only "*.qbox.me".

In the case of the C# code above, a specific host header is being used "image.tuhu.cn".  That host header will be used as the host name to match any certificate. And that pattern doesn't match anything. So, by default you will get a connection error about invalid certificate.

The code needs to be revised using [HttpClient.Handler.ServerCertificateCustomValidationCallback](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.servercertificatecustomvalidationcallback?view=netcore-2.2) property.

You could do something like this:

```c#
var handler = new HttpClientHandler();
handler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;

using (var client = new HttpClient(handler))
using (var request = new HttpRequestMessage(HttpMethod.Get, "https://iovip.qbox.me/test/FtPFFB2e_qh1isgop4jyxG68k4tE_w2880_h1800.jpg@200w_200h_100q.webp"))
{
    request.Headers.Host = "image.tuhu.cn";
    using (var response = await client.SendAsync(request))
    {
        Console.WriteLine(response.StatusCode);
    }
}
```

**Comment by pengweiqhca** [comment]
But I don't want use `HttpClientHandler.DangerousAcceptAnyServerCertificateValidator`.
Whether can let ``TargetHost to take effect
``` C#
new SocketsHttpHandler
{
	SslOptions =
	{
		TargetHost = "iovip.qbox.me"
	}
}
```
