### ISSUE TITLE
Bumping the version of OOB packages to match product version(5.0.0)

### ISSUE THREAD

**Issue by Anipik** [dotnet/corefx#40544]
We have bumped the package versions of most assemblies to match the .netcore version (5.0.0) in https://github.com/dotnet/corefx/pull/40530

There are some oob packages for which we just updated the minor version instead of lifting them to 5.0.0

The list of such projects is 
```
Microsoft.Bcl.AsyncInterfaces - 1.2.0
Microsoft.Bcl.HashCode - 1.2.0
Microsoft.Diagnostics.Tracing.EventSource.Redist- 2.3.0
Microsoft.XmlSerializer.Generator - 2.3.0
System.Collections.Immutable -1.8.0
System.Composition - 1.5.0
System.Numerics.Tensors- 0.4.0
System.Reflection.Metadata- 1.9.0
Microsoft.VisualBasic.Core -10.6.0
```

We can bump the versions of these packages to 5.0.0 except the last one.
Opening this issue to discuss whether we should do it or not

cc @ericstj @ViktorHofer @safern @danmosemsft

**Comment by Anipik** [comment]
@safern - collections
@maryamariyan, @ViktorHofer - composition
@tmat, @nguerrera - SRM
@tannergooding - Tensors
@StephenMolloy, @HongGit -Microsoft.XmlSerializer.Generator

Tagging area cowners to make a decision on bumping the package version and assembly version to 5.0.0

**Comment by nguerrera** [comment]
I don't have any opinion on the version number of SRM. Bumping it to 5.0.0 or not seems fine to me.

**Comment by ViktorHofer** [comment]
I'm fine with bump the version of S.CM.C as well.

**Comment by ericstj** [comment]
One suggestion WRT to VB: you can make it 6 + productVersion.  That way it can still be centrally maintained and not go backwards. /cc @cston

**Comment by tannergooding** [comment]
Sounds good to me.

**Comment by nguerrera** [comment]
> One suggestion WRT to VB: you can make it 6 + productVersion. That way it can still be centrally maintained and not go backwards. /cc @cston

And give up a chance to line up everything at 11.0.0 in November 2026? 😉

**Comment by StephenMolloy** [comment]
Sure. I don't see why not.

**Comment by safern** [comment]
I'm fine with bumping S.C.Immutable
