### ISSUE TITLE
Reevaluate a design decision - XDocument automatically connects text nodes next to each other

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/corefx#4054]
XDocument automatically connects text nodes which are next to each other, and combines them in a single node. The expected behavior is to have a separate node for each.

**Comment by mellinoe** [comment]
@krwq 

This sounds like something we'd have a very hard time changing, given that we need to remain compatible with older code.

**Comment by JonHanna** [comment]
I would expect the behaviour to be for adjacent text nodes to be combined into a single node, unless an added node was empty in which case the existing text node would remain unchanged (rather than replaced with a new identical node), as that's the requirement of the XQuery and XPath Data Model.

**Comment by karelz** [comment]
Won't fix due to compatibility.
