### ISSUE TITLE
System.Reflection.Tests.AssemblyTests.CurrentAssemblyHasLocation failing on OSX

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#4055]
Seeing this in my local runs (sadly Mac runs in Jenkins are not is super great shape so I'm not sure if we are hitting it there as well).

@nguerrera Can you take a look?  I am not sure if this is a problem with the new method or the path classes or something else...

      Assert.Equal() Failure
      Expected: /Users/matell/git/corefx/bin/tests/OSX.AnyCPU.Debug/System.Reflection.CoreCLR.Tests/dnxcore50/.
      Actual:   /Users/matell/git/corefx/bin/tests/OSX.AnyCPU.Debug/System.Reflection.CoreCLR.Tests/dnxcore50

**Comment by nguerrera** [comment]
cc @AlexGhiondea I wonder if AppContext.BaseDirectory should be normalized. 

I'm making the test more defensive and tolerating it as long as Path.GetFullPath matches.
