### ISSUE TITLE
API Proposal: System.IO.File.TryDelete(string path, int numberOfRetries, int timeout)

### ISSUE THREAD

**Issue by 0x90d** [dotnet/corefx#40561]
## Proposal:

```
namespace System.IO
{
    public class File
    {
        public static bool TryDelete(string path);
        public static bool TryDelete(string path, int numberOfRetries = 0, int timeout = 250);
    }
}
```
## Background

A very common problem is that when trying to delete a file it's used by another process which raises an exception. A very common solution is that File.Delete is wrapped around with a try-catch, possibly wrapped around a loop retrying for a specific amount of times. As no developer knows exactly what happens outside of his code, a File.Delete is probably always wrapped with a try-catch. 

With this proposal I would like to reduce the amount of lines and give this away to .NET to take care of.

## Reason

TryDelete tries to delete a file for a specific amount of times which reduces the amount of code developers write every day since File.Delete is likely always a "Try to delete and do X if it fails" in code anyway by being surrounded with a try-catch. Having the option to retry is an additional line of code saver but not explicitly necessary.

It behaves similar to Dictionary.TryGetValue for example which only purpose is is to save a few lines as well.

**Comment by gfoidl** [comment]
Somewhat similar proposal: https://github.com/dotnet/corefx/issues/31917

---

> Dictionary.TryGetValue for example which only purpose is is to save a few lines

This is not the _only_ purpose. The other one (and maybe the major one) is that it avoids a _KeyNotFoundException_, hence no exceptions for control-flow.

**Comment by 0x90d** [comment]
> 
> 
> > Dictionary.TryGetValue for example which only purpose is is to save a few lines
> 
> This is not the _only_ purpose. The other one (and maybe the major one) is that it avoids a _KeyNotFoundException_, hence no exceptions for control-flow.

The idea was to avoid exception handling as well but you're right that TryGetValue not only avoids exception handling but also avoids them internally, while the behavior of my proposal would simply shift the exception handling into .NET. Which still makes sense since it's frequently used and I saw some other APIs been added to .NET Core which doesn't anything different than the developer would do but makes his life a little bit easier. Best example I can remember is string. Contains(string value, StringComparison comparisonType) which itself calls IndexOf only https://source.dot.net/#System.Private.CoreLib/shared/System/String.Searching.cs,3c7c3a0a723d7e1b. But I'm generally opened to any feedback if and how the file deletion can be improved to make life easier.

**Comment by danmosemsft** [comment]
In most code in my experience Delete is not called in a loop. When looping is needed it is easily implemented as a utility method. New API is not free of cost no matter how simple eg it adds cognitive load in Intellisense. So it is unlikely to be a good fit for the framework.

String.Contains exists because it is super commonly needed and avoids a possible typo in the condition. It reduces cognitive load.

Thanks for the suggestion!
