### ISSUE TITLE
No cancellation token on Dns.GetHost{Address,Addresses}Async

### ISSUE THREAD

**Issue by roji** [dotnet/corefx#40586]
The two async methods on `Dns` do not accept a cancellation token. [With the recent cancellation improvements in the socket layer](https://github.com/dotnet/corefx/issues/24430), it seems like a good idea to allow cancellation of DNS queries as well.

**Comment by roji** [comment]
I admit I haven't research this yet. There do seem to be at least a [couple](https://linux.die.net/man/3/qdns) [packages](http://www.chiark.greenend.org.uk/~ian/adns/) but I have no idea how mature they are and whether it's appropriate to take a dependency on them.

I'm not sure if it's acceptable to have the overload accepting a token and not have it work across all platforms; cancellation is essentially already a best-effort thing, and it does remind me of ADO.NET where actual async may or may not be implemented by a given provider. That would at least unlock async DNS on Windows or wherever supported.

**Comment by roji** [comment]
From a very brief look at [adns](https://www.gnu.org/software/adns/) and [Qdns](https://linux.die.net/man/3/qdns), it (unsurprisingly) seems like they're DNS-only lookup libs as opposed to general host lookup libs (i.e. replacing Linux's gethostbyname, consulting /etc/nsswitch.conf, /etc/hosts etc.).

But regardless, the question is again whether it makes sense to provide the overloads and implement them where available, while falling back to sync elsewhere.

**Comment by scalablecory** [comment]
Cancellation has always been best-effort, so it's not really a blocker.

**Comment by scalablecory** [comment]
Triage: we are okay with these APIs. Combining this into #42004 to make API review simpler. Closing this one.
