### ISSUE TITLE
Reevaluate a design decision - bad PI within XDocument

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/corefx#4063]
One of the tests prints error messages but does not fail. It checks for bad ProcessingInstruction within an XDocument. I'm not sure if the contents of the two XmlReaders are truly supposed to the equivalent or different.

I have attached the simplified version of the test.
[BadPITestExample.txt](https://github.com/dotnet/corefx/files/18179/BadPITestExample.txt)

**Comment by karelz** [comment]
@sepidehMS is the test disabled?

**Comment by sepidehMS** [comment]
Won't fix as the behaviour needs to be consistent among Desktop and CoreFX
