### ISSUE TITLE
DirectoryInfo.Attributes thrown System.IO.FileNotFoundException for hidden directory on macOS 

### ISSUE THREAD

**Issue by justinushermawan** [dotnet/corefx#40649]
Dear corefx team,

I just tested my below code on macOS.
```
DirectoryInfo di = new DirectoryInfo(Path.Combine(env.ContentRootPath, ".myfolder"));    
if (!di.Exists)    
{     
    di.Create();     
    di.Attributes = FileAttributes.Directory | FileAttributes.Hidden;  // got FileNotFoundException :(
}    
```
But, it always thrown `System.IO.FileNotFoundException` while setting the directory attributes after creating it. I use the dot (.) prefix on my folder name and want to make it hidden. It works fine on Windows.

It it a bug?

**Comment by wfurt** [comment]
Linux has same issue. The problem is that Unix implementation would cache `_exists = false` and it would "remember" that the path does not exist.

Note that FileAttributes.Hidden is not quite portable. 
Most Linux file systems do not have attribute to represent that.

**Comment by danmosemsft** [comment]
@wfurt is this caching a bug?

**Comment by wfurt** [comment]
I don't understand your question @danmosemsft.
There is internal state which does not get updated after directory is created with Create()

**Comment by danmosemsft** [comment]
You answered my question with your PR, thanks @wfurt.
