### ISSUE TITLE
HttpClient.GetAsync() sends an empty Cookie header on Mac and Linux

### ISSUE THREAD

**Issue by halter73** [dotnet/corefx#4065]
When running [this test](https://github.com/aspnet/KestrelHttpServer/blob/8d107b22aecc03785814643ef82b61233ff9196b/test/Microsoft.AspNet.Server.Kestrel.FunctionalTests/ResponseTests.cs#L52) (which just does a plain call to GetAsync without any special configuration), HttpClient sends the following request on Mac and Linux:

    GET / HTTP/1.1\r\nHost: localhost:8792\r\nAccept: */*\r\nAccept-Encoding: gzip,deflate\r\nCookie: \r\n\r\n

This helped expose a header parsing bug in Ketrel :smile:, but I don't think the Cookie header should be sent in this case.

**Comment by joshfree** [comment]
@vijaykota
