### ISSUE TITLE
Remove Microsoft.BCL compat packages from 5.0

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#40656]
Per https://github.com/dotnet/corefx/pull/40363#discussion_r318743671 we won't be shipping new versions of the compat packages from 5.0, so we can remove these from the repo.

**Comment by kapsiR** [comment]
@ViktorHofer Just for clarification: Does that mean, that from 5.0 the compat packages (e.g. Microsoft.Bcl.AsyncInterfaces) are not supported anymore? (no netstandard2.0 support?)
