### ISSUE TITLE
System.Collections.ArrayList is not ComVisible

### ISSUE THREAD

**Issue by DanielVanNoord** [dotnet/corefx#40675]
I am testing a port of a set of COM Clients and Servers over to .Net Core 3.0. So far everything is working except for a property that exposes an ArrayList. From the .Net Framework client libraries and the .Net Core client libraries I get a 
>System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to class type 'System.Collections.ArrayList'. Instances of types that represent COM components cannot be cast to types that do not represent COM components; however they can be cast to interfaces as long as the underlying COM component supports QueryInterface calls for the IID of the interface.

When getting the ArrayList from the .Net Core Servers. All the methods and properties are loaded by the client libraries using late binding and reflection.

I also get the same exception from a .Net Framework Server and the .Net Core Client library. However I can cast the type returned from NetCore to IEnumerable in the client libraries and it contains the correct values. I took a look at ArrayList in the .Net Reference source and the corefx source and determined that it is ComVisible in .Net Framework but is not in .Net Core. I also verified this from code by checking for the ComVisible attribute on ArrayList. On the other hand IEnumbable works and is ComVisible in both.

Ideally the existing .Net Framework clients should be able to load the .Net Core COM servers without requiring changes. Is it possible to get the ComVisible Attribute added to the .Net Core ArrayList?

**Comment by danmosemsft** [comment]
@AaronRobinsonMSFT  what is our policy on ComVisible? I believe @jkotas said in the past it should only exist on types that are directly related to COM interop and we largely stripped it.

**Comment by AaronRobinsonMSFT** [comment]
> I believe @jkotas said in the past it should only exist on types that are directly related to COM interop and we largely stripped it.

@danmosemsft That is generally true, but there are exceptions. For example we did add it back to `MarshalByRefObject` since it was very impacting and created difficult workarounds - see https://github.com/dotnet/coreclr/pull/22930. In this case since there are workarounds (i.e. cast to `IEnumerable`) so I think we should avoid adding it back. More than willing to reconsider due to developer impact though.

**Comment by jkotas** [comment]
Many .NET Framework 1.0 types that lives in mscorlib were marked as COM-visible. We did not take this legacy feature forward to .NET Core.

There are a few exceptions for fundamental types like `MarshalByRefObject` or `IEnumerable`. ArrayList is not a fundamental type that would be appropriate to mark as COM visible in .NET Core.

**Comment by DanielVanNoord** [comment]
The issue (for me) with removing it is that all of the existing client libraries that expect the old behavior will need to be updated to use IEnumerable before they will work. This will prevent old libraries from working with new .Net Core Com servers. This will make our upgrade path to .Net Core a lot more painful.

**Comment by jkotas** [comment]
I am sorry about that. We had to strike the balance for how many legacy .NET Framework feature we bring to .NET Core and this one did not make the list.

**Comment by Peter-Simpson** [comment]
I don't think this is just an ASCOM issue, ArrayList is a basic staple of COM interop; it is the closest thing that it has to a collection and is used extensively by many interop based applications.

This suggested approach just makes migration to .NET Core harder and riskier which will delay take-up.

What benefit is there in forcing developers to copy values using for each loop as opposed to simply assigning to a variable?

As I understand it, all that is required is to decorate the ArrayList command as COM compatible, is there a technical downside to doing this or is this simply a philosophical position?

Regards, Peter

**Comment by jkotas** [comment]
> As I understand it, all that is required is to decorate the ArrayList command as COM compatible

It is not just that. There is also:
- Writing interop test for ArrayList methods exposed by COM interop and iterate on additional issues identified by these tests.
- Potentially introduce fake COM interfaces (like https://github.com/microsoft/referencesource/blob/master/mscorlib/system/reflection/cominterfaces.cs from .NET Framework) to compensate for differences between managed surface that can evolve and COM surface that is set in stone.
- Make sure that collisions between .NET Core ArrayList and the global .NET Framework-specific ArrayList COM registration in registry are handled gracefully

**Comment by Peter-Simpson** [comment]
Hi Jan,

 

Thanks for your informative reply. 

 

I have no experience in this type of work and so have no real appreciation of the amount of work involved, it’s clearly non-trivial from your description. But first a different question, if this work was done to the project’s technical standards, would it be accepted, or has a decision been made that the present level of COM support is as far as the project will go at this time?

 

Regards, Peter

**Comment by jkotas** [comment]
A few though:

We prefer to address issues in priority order. We have received a lot more feedback about missing `dynamic` keyword COM support in .NET 3 complicating migrations. I think addressing that would be much more beneficial than this.

This work would not be part of .NET Core 3.x. It would potentially ship in .NET 5 more than one year from now. The benefit of this work decrease over time as people who run into it implement workarounds. Is there anybody going to be left waiting for this in .NET 5?

**Comment by Peter-Simpson** [comment]
> Is there anybody going to be left waiting for this in .NET 5?

The [Core Roadmap](https://github.com/dotnet/core/blob/master/roadmap.md) is targetting .NET 5 delivery in just over a year, and my gut tells me that businesses will still be generating significant business value at that point through applications using COM components.

Some businesses will take the .NET Core opportunity to re-write their applications and to ditch COM, but I suspect that many more will seek to evolve their existing applications, and it is these users that I think may ask for more complete COM support.

Nonetheless this is just one person's perspective and only time will tell whether the capability is significant to others; in the meantime, we will work round the issue.

Best wishes, Peter
