### ISSUE TITLE
Invalid CultureInfo name not throwing exception

### ISSUE THREAD

**Issue by mikernet** [dotnet/corefx#40698]
As far as I can tell from the [`CultureInfo` constructor](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.-ctor?view=netframework-4.8#System_Globalization_CultureInfo__ctor_System_String_) and [`CreateSpecificCulture`](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.createspecificculture?view=netframework-4.8) docs, these two lines should both throw an exception:

```c#
new CultureInfo("aaa").Name.Dump();
CultureInfo.CreateSpecificCulture("aaa").Name.Dump();
```

Upon further inspection it looks like it creates an unknown language culture with a fallback to invariant. This doesn't seem right...the fact that it throws `CultureNotFoundException` when you give it an invalid name (i.e. "aaaaa") instead of `ArgumentException` and it doesn't actually throw `CultureNotFoundException` when the specified culture isn't found is rather odd. The description of the parameter states that it has to be a predefined culture name, which "aaa" is not.

If this is intended behavior then it should probably be documented a little better.

**Comment by tarekgh** [comment]
This is Windows 10 behavior, every culture name conforms to BCP-47 is a valid culture and Windows will be able to create it. If you have any concern, please report that to Windows through the Feedback hub. .NET is always use whatever the underlying OS is giving.

**Comment by mikernet** [comment]
What I'm saying is the MSDN documentation that I linked is highly misleading and should be fixed if this is intended behavior, and furthermore the exceptions being thrown are also misleading. An invalid format for the parameter should throw an argument exception,  not a culture not found exception. Neither of those problems have anything to do with Windows 10.

**Comment by mikernet** [comment]
I understand that a breaking change for the exception type is highly unlikely to happen now, but the method's behavior should at least be properly documented because as it stands right now it isn't.

**Comment by mikernet** [comment]
One other issue: the documented behavior of the CreateSpecificCulture method says it throws an exception if "The culture specified by name does not have a specific culture associated with it." Shouldn't a non-existent culture like "aaa" throw an exception here then? How can a non-existent culture have a specific culture associated with it?

These docs lack much needed clarity.

**Comment by tarekgh** [comment]
Thanks @mikernet for clarifying. feel free to log a doc issue in the repo https://github.com/dotnet/docs.

**Comment by mikernet** [comment]
I opened an issue in the doc repo (https://github.com/dotnet/docs/issues/14117), but I still feel like the behavior of the methods is incorrect more than the documentation. These behaviors are not defined in Windows, it's up to .NET to decide how it handles the exceptional circumstances and the documented behavior seems much more sane to me than the actual behavior, especially with regards to point #2 in the doc issue.

Are you sure the actual behavior is the intended behavior?

**Comment by tarekgh** [comment]
What is happen is when you create a culture with name like "aaa" which is is not one of the names carried by Windows, at that time Windows will try to create it for us and try to fill the culture properties as much it can by matching the language part and country part. for example, if I try to create ja-US which I think not exist, Windows will try to fake the culture by getting the language information from the Japanese language and will get the country information from US and combine it into a new culture. now when passing "aaa" which not matching any language/country, Windows will just use Invariant culture properties for that. And that is what you are seeing.

This is the behavior defined by Windows starting Windows 10 and not really the .NET. the framework just calling the OS for getting the needed information. the code of CreateSpecificCulture is just calling the OS at the end.

**Comment by mikernet** [comment]
I understand that, but .NET can still choose to wrap the native calls with whatever behavior it deems appropriate. I think it would have been much more intuitive if it behaved the way the docs state that it does (apparently whoever wrote the docs thinks so too, since apparently they thought that's how it works as well, haha :) and the dev could choose to fallback to invariant in case of an exception or fail or show an error or whatever...but that's neither here nor there at this point, it's much easier to fix the docs than to introduce breaking changes.

A few minutes ago I was surprised to learn that the invariant culture is marked as a specific culture for the "invariant country" region and not a neutral culture, so the behavior of `CreateSpecificCulture` makes more sense now. I'll revise my doc issue to reflect that.

**Comment by mikernet** [comment]
I figured out why this is so bloody confusing...the invariant culture is marked as `IsNeutralCulture == false` but it shows up in the neutral culture list (`CultureInfo.GetCultures(CultureTypes.NeutralCultures)`) and **doesn't** show up in the specific culture list (`CultureInfo.GetCultures(CultureTypes.SpecificCultures)`...how's that for a mind bending flustercuck. Jeez...

**Comment by tarekgh** [comment]
agree this is confusing but unfortunately this is the behavior since v1.0. But this is also documented here https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.getcultures?view=netframework-4.8

```
NeutralCultures, which returns all neutral cultures and the invariant culture.
```

Which implicitly indicating invariant is not neutral culture :-)

**Comment by mikernet** [comment]
`CreateSpecificCulture()` docs state that a `CultureNotFoundException` is thrown if "the culture specified by name does not have a specific culture associated with it."

When would this ever happen? What named cultured doesn't have a specific culture associated with it? None of these lines throw an exception:

```c#
CultureInfo.GetCultures(CultureTypes.NeutralCultures).Select(c => CultureInfo.CreateSpecificCulture(c.Name)).ToList();
CultureInfo.CreateSpecificCulture("aaa-XX"); // still works, returns unknown country culture
CultureInfo.CreateSpecificCulture("aaa"); // still works, returns blank name culture
```

**Comment by tarekgh** [comment]
This should throw:

```C#
CultureInfo.CreateSpecificCulture("This is not a valid culture"); 
```

As I mentioned the culture name has to comply with the BCP-47 specs. Otherwise we should throw.

**Comment by mikernet** [comment]
Right, but it says:

> name is not a valid culture name.
> -or-
> The culture specified by name does not have a specific culture associated with it.
 
So that's already covered by the first part.
