### ISSUE TITLE
Question on SocketsHttpHandler.ConnectTimeout property

### ISSUE THREAD

**Issue by khavishbhundoo** [dotnet/corefx#40706]
Hello , 

I am just beginning my journey in the C# and .Net ecosystem so bear with me if its a common question.

1.Is the ConnectTimeout similar to  `CURLOPT_CONNECTTIMEOUT` in curl ?
2.Is the value supposed to be in miliseconds or seconds

**Comment by stephentoub** [comment]
>  is the ConnectTimeout similar to CURLOPT_CONNECTTIMEOUT in curl ?

Yes

> Is the value supposed to be in miliseconds or seconds

It's a TimeSpan, which you can create with TimeSpan.FromMilliseconds, TimeSpan.FromSeconds, etc.

**Comment by khavishbhundoo** [comment]
@stephentoub 

Thanks for the info.Is there a plan to add `CURLOPT_LOW_SPEED_TIME` equivalent as well.

**Comment by stephentoub** [comment]
There is no plan currently for such a setting.  Please feel free to open an API proposal issue (https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md) with details if you believe it's necessary. Thanks.
