### ISSUE TITLE
Lost HTTP Header Attribute

### ISSUE THREAD

**Issue by gaborposz** [dotnet/corefx#40700]
Hello,
During development we have encountered a very strange issue regarding HTTP Headers.

We use [WinHttpHandler](https://www.nuget.org/packages/System.Net.Http.WinHttpHandler/4.5.2) on the client, and [Kester](https://www.nuget.org/packages/Microsoft.AspNetCore.Server.Kestrel.Core/2.2.0) (with self-hosting) on the backend for HTTP/2 communication, and we put some custom attributes into the HTTP header to transfer data together with the HTTP requests.

We noticed that occasionally -after several requests with specific header sizes- our custom header attribute is completely missing on the server side, although it was seemingly sent successfully by the client. It’s still unclear whether the error is on client side (WinHttpHandler) or on server side (Kestrel), but it only happens if HTTP 2.0 protocol is used with secure communication (HTTPS).

I have created a simple project to reproduce this error, the code is pretty straightforward, but let me know if you have any question.
Please have a look, and give us feedback if it can be fixed, or workaround is possible.

[MissingCustomHeaderReproduce.zip](https://github.com/dotnet/corefx/files/3558893/MissingCustomHeaderReproduce.zip)

Thanks and Best Regards,
Gabor Posz

**Comment by davidsh** [comment]
What version of .NET Core are you using?  Output of "dotnet --info" ?

Why are you using WinHttpHandler?  You should consider using .NET Core.  As of .NET Core 3.0, HttpClientHandler (which uses SocketsHttpHandler) supports HTTP/2 protocol.

**Comment by gaborposz** [comment]
We are using WinHttpHandler because our client is .NET Framework 4.7 based (it must be, because it is used by other .NET Framework components), and this is the only way to support HTTP/2 with .NET Framework.

Only our backend service is .NET Core based. We use the [.NET Core 2.2.3 Runtime](https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-2.2.3-windows-x64-installer) (Microsoft.NETCore.App 2.2.3) in production environment, and [.NET Core 2.2.105 SDK](https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-2.2.105-windows-x64-installer) for development.

**Comment by davidsh** [comment]
>our custom header attribute is completely missing on the server side, although it was seemingly sent successfully by the client. 

How do you know this?  Did you do a Wireshark trace? Although with HTTP/2 normally over TLS that would be difficult.

>It’s still unclear whether the error is on client side (WinHttpHandler) or on server side (Kestrel)

Can you try another server (such as IIS) to determine whether it is really a client-side or server-side problem?

**Comment by gaborposz** [comment]
I tried with Wireshark, but with secure communication it is not visible, and with disabled HTTPS the error is not reproducible.

I might try with IIS, but I'm not familiar with that, so it would take more time.

Isn't there an easier way to find out whether it's the client or the server? E.g.: Dump out the raw data by WinHttpHandler or Kester before/after the encryption?

**Comment by gaborposz** [comment]
Hi,
After some struggle I eventually managed to try it with IIS. I tested it with an ASP.NET (.NET Framework) as well as an ASP.NET Core handler, and both of them was working fine. It indicates that the problem is most probably in the self hosted Kestrel.

**Comment by davidsh** [comment]
Seems like this issue should be moved to one of the ASP.NET repos.

cc: @Tratcher

**Comment by Tratcher** [comment]
This issue was moved to aspnet/AspNetCore#13650
