### ISSUE TITLE
JsonSerializer always encodes dictionary keys and property names

### ISSUE THREAD

**Issue by chenyj796** [dotnet/corefx#40704]
I have some code as below:
``` csharp
var dict = new Dictionary<string, Dictionary<string, string>>();
dict.Add("用户组01", new Dictionary<string, string>
{
    { "用户ABC","123"},
    { "用户DEF","456"}
});
var json = JsonSerializer.Serialize(dict);
```
and got the json as below:
```
{"\u7528\u6237\u7EC401":{"\u7528\u6237ABC":"123","\u7528\u6237DEF":"456"}}
```
when I actually want:
```
{"用户组01":{"用户ABC":"123","用户DEF":"456"}}
```

**Comment by Tornhoof** [comment]
You  can try the ``JavaScriptEncoder.UnsafeRelaxedJsonEscaping`` encoding setting by creating your own Options.
Like
```csharp
new JsonSerializerOptions
        {
            Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
        };
```

**Comment by chenyj796** [comment]
Unfortunately, it doesn't work.
And why serialize to localized string is not default behavior?

**Comment by am11** [comment]
`JavaScriptEncoder.UnsafeRelaxedJsonEscaping` is apparently working with POCOs but not dictionaries.

<details>
  <summary>Code</summary>

```c#
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.RegularExpressions;

static class Program
{
    struct Node
    {
        public string Name { get; set; }
        public string Value { get; set; }
    }

    struct Container
    {
        public string Name { get; set; }
        public List<Node> Values { get; set; }
    }

    static void Main(string[] args)
    {
        var object1 = new Dictionary<string, Dictionary<string, string>>
        {
            ["用户组01"] = new Dictionary<string, string>
            {
                ["用户ABC"] = "123",
                ["用户DEF"] = "456"
            }
        };

        var object2 = new Container
        {
            Name = "用户组01",
            Values = new List<Node>
            {
                new Node { Name = "用户ABC", Value = "123" },
                new Node { Name = "用户DEF", Value = "456" }
            }
        };

        var options = new JsonSerializerOptions
        {
            Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
        };
        var json1 = JsonSerializer.Serialize(object1, options);
        var json2 = JsonSerializer.Serialize(object2, options);

        Console.WriteLine("serialized JSON of {0}: {1}", nameof(object1), json1);
        Console.WriteLine("serialized JSON of {0}: {1}", nameof(object2), json2);
    }

    // workaround method https://snipplr.com/view/57863/
    static string UnescapeUnicdeCharacters(this string subject)
    {
        if (Regex.Match(subject, @".*\\u.*").Success)
        {
            var regex = new Regex(@"\\[uU]([0-9A-F]{4})");
            subject = regex.Replace(subject, delegate (Match match) { return ((char)int.Parse(match.Value.Substring(2), NumberStyles.HexNumber)).ToString(); });
        }
        return subject;
    }
}
```
</details>

Outputs:

```
serialized JSON of object1: {"\u7528\u6237\u7EC401":{"\u7528\u6237ABC":"123","\u7528\u6237DEF":"456"}}
serialized JSON of object2: {"Name":"用户组01","Values":[{"Name":"用户ABC","Value":"123"},{"Name":"用户DEF","Value":"456"}]}
```

An expensive (in terms of performance) workaround to get decoded `json1` is replace characters using approach like [`UnicodeToCharacter()`](https://snipplr.com/view/57863/):

With:
```diff
- Console.WriteLine("serialized JSON of {0}: {1}", nameof(object1), json1);
+ Console.WriteLine("serialized JSON of {0}: {1}", nameof(object1), UnicodeToCharacter(json1));
```

it produces the output:

> serialized JSON of object1: {"用户组01":{"用户ABC":"123","用户DEF":"456"}}

@ahsonkhan, is this a bug?

aside, about the workaround: with the new additions in framework like `Rune`, `Utf8String` etc., is there a better approach than `UnicodeToCharacter()` to get decoded unicode characters? (not just JSON use-case, any string like `"\u7528\u6237ABC"` decoded as `"用户ABC"`)

**Comment by steveharter** [comment]
Yes this is a bug - the dictionary code is not passing the `options.Encoder` to the writer, so it is using the default encoder which escapes. Also the bug exists for property names as well.

**Comment by steveharter** [comment]
@chenyj796 other than the longer JSON and associated performance cost, does this cause any other issue for you? Would like input on severity of issue for 3.0.

I verified deserialization works as expected for Dictionaries with the escaped Chinese characters.

**Comment by ahsonkhan** [comment]
> You  can try the ``JavaScriptEncoder.UnsafeRelaxedJsonEscaping`` encoding setting by creating your own Options and use them in your calls.

As the name suggests, I wouldn't jump directly to using `UnsafeRelaxedJsonEscaping` primarily to get localized output to show up. The default encoder used was chosen specifically for defense-in-depth. You should evaluate your scenario thoughtfully before choosing the non-default encoding.

For escaping text that contains unicode characters like the Chinese characters, consider creating a `JavascriptEncoder` using the factory method that allows non-latin1 characters (but keeps escaping html specific characters like <, >). If it is safe to leave html characters un-escaped in your context/scenario, and if emitting even html characters unescaped truly is a concern, then you can keep using `UnsafeRelaxedJsonEscaping`.

```C#
using System.Text.Unicode;

JavaScriptEncoder customEncoder = JavaScriptEncoder.Create(
    new TextEncoderSettings(UnicodeRanges.All));

new JsonSerializerOptions
{
    Encoder = customEncoder
};
```

I'd try that instead (once the issue that @steveharter identified has been fixed).

**Comment by steveharter** [comment]
After offline discussion, the fix in master (which will become 5.0) will not be ported to 3.0 since there is just a few days before the final build.

This could make it into 3.1 pending feedback.

Closing for 3.0. Please re-open if this is blocking scenarios or adoption.

**Comment by ahsonkhan** [comment]
Re-opening to consider for 3.1.

**Comment by ugavnholt** [comment]
Danish characters æ. ø, and å have the same issue, I would assume that Swedish, German, Norwegian and french characters will have the same problem.

The following test show what fails:

```csharp
[Fact]
public void Utf8Test()
{
    var logger = logFactory.CreateLogger("BackendObject_SerializeToUtf8Stream");
    logger.LogInformation("Starting test.");

    using (var stream = new MemoryStream())
    using (var jsonUtf8 = new Utf8JsonWriter(stream))
    {
        jsonUtf8.WriteStartObject();
        jsonUtf8.WriteString("name", "æøå");
        jsonUtf8.WriteEndObject();
        jsonUtf8.Flush();

        var checkString = Encoding.UTF8.GetString(stream.ToArray());
        Assert.Equal(@"{""name"":""æøå""}", checkString);
    }
}
```

Default encoder should work with any language, otherwise its a serious flaw if everybody have to use the `JavaScriptEncoder.UnsafeRelaxedJsonEscaping` encoder, and do manual ancoding for all possible languages.

**Comment by ahsonkhan** [comment]
> Default encoder should work with any language, otherwise its a serious security flaw because everybody would have to do their own hack based on the `JavaScriptEncoder.UnsafeRelaxedJsonEscaping` encoder. This is a serious problem for any international use.

You could specify your own `JavascriptEncoder` using the `Create` factory method for the language you need supported. This avoids having to use `UnsafeRelaxedJsonEscaping` which forgoes a lot of the default escaping behavior intended for defense-in-depth (which includes why characters outside the ascii range are escaped by default as well). The default escaping behavior that you are observing is by-design.

```C#
var writerOptions = new JsonWriterOptions
{
    Encoder = JavaScriptEncoder.Create(UnicodeRanges.All) // Or just pick the particular language
};

// Similarly with the serializer options
var options = new JsonSerializerOptions
{
    Encoder = JavaScriptEncoder.Create(UnicodeRanges.All) // Or just pick the particular language
};
```

@ugavnholt here's some related issues:
https://github.com/dotnet/corefx/issues/38354
https://github.com/dotnet/corefx/issues/39756#issuecomment-515299446
