### ISSUE TITLE
Suggested API Addition: ConcurrentDictionary.TryUpdate(TKey key, Func<TKey, TValue, TValue> updateFactory)

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#4072]
The discussion on #4068 made me think of how it's possible to add to a `ConcurrentDictionary` based on a key, or to do an add-or-update based on the key and/or current value, but it's not possible to do an update based on current values that would not add a new value if there wasn't one already.

This can be added externally easily enough:

```C#
public static bool TryUpdate<TKey, TValue>(this ConcurrentDictionary<TKey, TValue> dict,
    TKey key,
    Func<TKey, TValue, TValue> updateFactory)
{
    TValue curValue;
    while(dict.TryGetValue(key, out curValue))
    {
        TValue value = updateFactory(key, curValue);
        if(
            (default(TValue) == null && ReferenceEqual(curValue, value))
            || dict.TryUpdate(key, value, curValue)
        )
            return true;
    }
    return false;
}
```

But this is slower (and hence more likely to have to loop) than if the call was an instance method, and also prevents the factory from being called with the stored key rather than the passed key (should a difference be significant to the factory).

That it's come up for at least someone else before is suggested by http://stackoverflow.com/q/12240219/400547 (they didn't need the key in their factory, but the above would have provided them with an answer too as their factory could simply ignore it).

**Comment by Priya91** [comment]
@JonHanna If you're still interested in this api addition, please come up with a proposal with a speclet, as mentioned in the [api-review guidelines](https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/Documentation/project-docs/api-review-process.md)
