### ISSUE TITLE
Socket.ConnectAsync on MacOS with sandbox enabled, requires server entitlements

### ISSUE THREAD

**Issue by odhanson** [dotnet/corefx#40737]
When calling System.Net.HttpWebRequest.GetResponse/SendRequest a socket connection is made from the client machine to the HTTP server. In MacOS, if the app is running from within a sandbox, it is understandable that com.apple.security.network.client should be added to the list of entitlements so the app will have permissions to make network connections. 
It turns out, however, that Socket.ConnectAsync will bind the socket to IPAddress.Any. in MacOS, binding the socket requires com.apple.security.network.server permissions which is used when we want to allow incoming connections to our app. 
Requiring com.apple.security.network.server is unreasonable IMO and I wonder why do we need to Bind a client socket connection to an IPAddress ?

**Comment by odhanson** [comment]
cc: @jkotas , @stephentoub

**Comment by stephentoub** [comment]
@davidsh, @geoffkizer, do you know why Socket.ConnectAsync does a bind to Any? (It does so both on netfx and core.)

**Comment by davidsh** [comment]
>@davidsh, @geoffkizer, do you know why Socket.ConnectAsync does a bind to Any? (It does so both on netfx and core.)

I don't know the answer. Perhaps it was a Windows requirement (winsock).

@Tratcher do you know?

**Comment by scalablecory** [comment]
ConnectEx requires a bound socket.

I wonder if we can avoid this outside of Windows.

**Comment by stephentoub** [comment]
> ConnectEx requires a bound socket. It does this to allow reuse w/ DisconnectEx.

Interesting. Thanks.

> I wonder if we can avoid this outside of Windows.

Sounds like "yes".  And the actual code changes in System.Net.Sockets to achieve that are simple.

**Comment by odhanson** [comment]
So it turns out this is a blocker issue for us. If I enable these entitlements we will be rejected the next time we submit our app to the Apple store.

Project management aside, how do you suggest we approach fixing this? I can make the fix in the mean time. Right now ConnectAsync will perform 
```c#
                e._socketAddress = SnapshotAndSerialize(ref endPointSnapshot);

                // Do wildcard bind if socket not bound.
                if (_rightEndPoint == null)
                {
                    if (endPointSnapshot.AddressFamily == AddressFamily.InterNetwork)
                    {
                        InternalBind(new IPEndPoint(IPAddress.Any, 0));
                    }
                    else if (endPointSnapshot.AddressFamily != AddressFamily.Unix)
                    {
                        InternalBind(new IPEndPoint(IPAddress.IPv6Any, 0));
                    }
                }

                // Save the old RightEndPoint and prep new RightEndPoint.
                EndPoint oldEndPoint = _rightEndPoint;
                if (_rightEndPoint == null)
                {
                    _rightEndPoint = endPointSnapshot;
                }
```
Perhaps we want to move this into a private method implemented inside Socket.Unix and Socket.Windows ?

**Comment by karelz** [comment]
Reopening for port to 3.0 - @scalablecory can you please create porting PR? Thanks!

**Comment by danmosemsft** [comment]
@odhanson could you please pick up a 3.0 build in a few days and confirm you are unblocked to release your product now?

**Comment by odhanson** [comment]
@danmosemsft I have tested with latest nightly build and LGTM

**Comment by danmosemsft** [comment]
Excellent! Let us know when you ship!

**Comment by odhanson** [comment]
I don't want to ship nightly builds (also I am not sure our build agent can support that). When will this be officially released ?

**Comment by rafaelmaeuer** [comment]
@odhanson sorry as this is oftopic but I couldn't find another way to contact you. Can you please get in touch with me? I have a question to your SR-Tool from http://www1.idc.ac.il/toky/videoProc-07/projects/SuperRes/srproject.html
