### ISSUE TITLE
[Question] Newest APIs related to asycnhronous queues?

### ISSUE THREAD

**Issue by SirJosh3917** [dotnet/corefx#40734]
Recently, I've wanted to implement a simple enqueue/dequeue extremely similar to `ConcurrentQueue<T>`, but with a truly asynchronous `Dequeue` method. My current result, is this <https://paste.mod.gg/agovewixaj.cpp>

However, the primary problem is that the `CancellationToken` passed to `Dequeue` will never actually do anything, since `ThreadPool.RegisterWaitForSingleObject` doesn't accept a `CancellationToken`, so my other route is to look for ManualResetEvent(Slim) alternatives.

I noticed @stephentoub had a blog post from 2012 with an asynchronous manual reset event, and I'm curious if it's still relevant? It doesn't accept a `CancellationToken` for WaitAsync though, which is what troubles me about it.

I'm currently at a roadblock for where to go since I'm not very knowledgeable in async. The current implementation that I have can hit up to 6 million messages per second (int) with one thread enqueueing and another task dequeueing, and in a perfect world I wouldn't want to sacrifice any performance (but I'd be prepared to take a mild hit).

**Comment by svick** [comment]
This probably doesn't answer your question, but I think you shouldn't implement your own async queue and instead should use an existing library that can act as an async queue. Some options (all of them seem to support cancellation):

* [`AsyncEx.AsyncCollection`](https://github.com/StephenCleary/AsyncEx/wiki/AsyncCollection): this does exactly what you want, but it's a 3rd party library, which might be a problem for some.
* [`BufferBlock` from TPL Dataflow](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.dataflow.bufferblock-1?view=netcore-2.2): you can use the `ReceiveAsync` method for async dequeuing. The class also has lots of dataflow-related functionality, which you can ignore.
* [`Channel` from `System.Threading.Channels`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.channels?view=dotnet-plat-ext-2.1): `ChannelReader`'s `ReadAsync` can be used for async dequeuing. The API might be somewhat cumbersome for this purpose.

**Comment by stephentoub** [comment]
> The API might be somewhat cumbersome for this purpose

What about it?

**Comment by svick** [comment]
@stephentoub Just that you have separate reader and writer, which is generally not something you want from a queue. But I admit that's really minor.

**Comment by stephentoub** [comment]
> The current implementation that I have can hit up to 6 million messages per second (int) with one thread enqueueing and another task dequeueing, and in a perfect world I wouldn't want to sacrifice any performance (but I'd be prepared to take a mild hit).

I'd recommend using Channels, and I expect you'll see a significant performance increase rather than sacrifice over the example you shared.

**Comment by stephentoub** [comment]
Here's an example.

This has two benchmarks per type, one that first enqueues and then dequeues (so that the dequeue will always find data available) and one that first dequeues asynchronously, then enqueues, and then awaits the dequeue (so that the dequeue will always complete asynchronously).

|                      Method |        Mean |     Gen 0 | Allocated |
|---------------------------- |------------:|----------:|----------:|
|         ChannelQueueDequeue |    494.5 us |         - |         - |
|         ChannelDequeueQueue |    869.0 us |         - |         - |
| AsyncCollectionQueueDequeue |  3,081.4 us |  953.1250 | 5999352 B |
| AsyncCollectionDequeueQueue | 12,328.5 us | 2031.2500 |    1184 B |
|   SimpleMessageQueueDequeue |    474.0 us |  114.7461 |  720000 B |
|   SimpleMessageDequeueQueue |          NA |         - |         - |

```C#
using System;
using System.Collections.Concurrent;
using System.Runtime.CompilerServices;
using System.Threading;
using System.Threading.Channels;
using System.Threading.Tasks;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using Nito.AsyncEx;

[MemoryDiagnoser]
public class Program
{
    public static void Main(string[] args) => BenchmarkSwitcher.FromTypes(new[] { typeof(Program) }).Run(args);

    private const int Iters = 10_000;

    private static readonly Channel<int> _c = Channel.CreateUnbounded<int>();

    [Benchmark]
    public async Task ChannelQueueDequeue()
    {
        for (int i = 0; i < Iters; i++)
        {
            _c.Writer.TryWrite(i);
            await _c.Reader.ReadAsync();
        }
    }

    [Benchmark]
    public async Task ChannelDequeueQueue()
    {
        for (int i = 0; i < Iters; i++)
        {
            var t = _c.Reader.ReadAsync();
            _c.Writer.TryWrite(i);
            await t;
        }
    }


    private static readonly AsyncCollection<int> _ac = new AsyncCollection<int>();

    [Benchmark]
    public async Task AsyncCollectionQueueDequeue()
    {
        for (int i = 0; i < Iters; i++)
        {
            _ac.Add(i);
            await _ac.TakeAsync();
        }
    }

    [Benchmark]
    public async Task AsyncCollectionDequeueQueue()
    {
        for (int i = 0; i < Iters; i++)
        {
            var t = _ac.TakeAsync();
            _ac.Add(i);
            await t;
        }
    }

    private static readonly SimpleMessagePipe<int> _smp = new SimpleMessagePipe<int>();

    [Benchmark]
    public async Task SimpleMessageQueueDequeue()
    {
        for (int i = 0; i < Iters; i++)
        {
            _smp.Enqueue(i);
            await _smp.Dequeue();
        }
    }

    [Benchmark]
    public async Task SimpleMessageDequeueQueue()
    {
        for (int i = 0; i < Iters; i++)
        {
            var t = _smp.Dequeue();
            _smp.Enqueue(i);
            await t;
        }
    }

    // COPIED UNMODIFIED FROM https://paste.mod.gg/agovewixaj.cpp
    public class SimpleMessagePipe<T>
	{
		private readonly ManualResetEventSlim _mres = new ManualResetEventSlim(false);
		private readonly ConcurrentQueue<T> _queue = new ConcurrentQueue<T>();

		public void Dispose()
		{
			_mres.Dispose();
		}

		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public void Enqueue(T message)
		{
			_queue.Enqueue(message);

			_mres.Set();
		}

		public Task<T> Dequeue(CancellationToken cancellationToken = default)
		{
			if (_queue.TryDequeue(out var result))
			{
				if (_mres.IsSet)
				{
					_mres.Reset();
				}

				return Task.FromResult(result);
			}

			return AsyncDequeue(cancellationToken);
		}

		// https://stackoverflow.com/a/18766131
		private Task<T> AsyncDequeue(CancellationToken cancellationToken)
		{
			var tcs = new TaskCompletionSource<T>();

			var registeredWaitHandle = ThreadPool.RegisterWaitForSingleObject(_mres.WaitHandle, (state, timedOut) =>
			{
				if (!_queue.TryDequeue(out var result))
				{
					tcs.SetException(new Exception("Multiple async dequeuers? Unable to dequeue."));
					return;
				}

				tcs.SetResult(result);
			}, tcs, -1, true);

			tcs.Task.ContinueWith((_, state) =>
			{
				var localRegisteredWaitHandle = (RegisteredWaitHandle)state;

				localRegisteredWaitHandle.Unregister(null);
			}, registeredWaitHandle, cancellationToken);

			return tcs.Task;
		}

		[MethodImpl(MethodImplOptions.NoInlining)]
		private static void ThrowDispose()
		{
			throw new ObjectDisposedException(nameof(SimpleMessagePipe<T>));
		}
	}
}
```

Note that your AsyncDequeue is buggy, which is why no results are produced for that case here):
```
 ---> System.Exception: Multiple async dequeuers? Unable to dequeue.
   at Program.SimpleMessageDequeueQueue() in c:\Users\stoub\Desktop\Benchmarks\Program.cs:line 86
   at BenchmarkDotNet.Autogenerated.Runnable_5.<.ctor>b__3_4() in c:\Users\stoub\Desktop\Benchmarks\bin\Release\netcoreapp3.0\e94635fc-80d6-4ae6-aa1f-ff0c83726962\e94635fc-80d6-4ae6-aa1f-ff0c83726962.notcs:line 3409
```
Potentially related, it also appears to be buggy with regards to how it handles resetting the MRES; it would need more synchronization to avoid deadlocks.

**Comment by SirJosh3917** [comment]
> This probably doesn't answer your question, but I think you shouldn't implement your own async queue and instead should use an existing library that can act as an async queue. Some options (all of them seem to support cancellation):
That's precisely what I wanted to achieve by asking this question, and you did answer it! I know my implementation is completely garbage in comparison to what some really knowledgeable asynchronous people can come up with, hence I asked my question :)

> Here's an example.
Channels look awesome, thanks Stephen! Looking around, it looks like they completely are what I need them to be - a simple, fast pub/sub enqueue with an asynchronous dequeue. This is great!
