### ISSUE TITLE
If possible, stop hard-coding magic values that aren't exposed in OpenSSL headers

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#4074]
See discussion here: https://github.com/dotnet/corefx/pull/4026/files#r42687456

**Comment by eerhardt** [comment]
Assigning this to @vijaykota in case he knows of a way to fix this, or to close if there isn't a way.

**Comment by vijaykota** [comment]
We didn't find any other place for these other than the internal headers so closing this.
