### ISSUE TITLE
The installation path for x64 SDK installations: "" cannot be the same as for x86 SDK installations: ""

### ISSUE THREAD

**Issue by E1adi** [dotnet/corefx#40750]
Hey guys,

I can't install nor uninstall .NET Core SDK v3.0 prev 8.
The Error I get is as the title:
The installation path for x64 SDK installations: "" cannot be the same as for x86 SDK installations: ""

I used Revo uninstaller to delete it once and can't install it since than.

Attached the log file of the installer.

P.S. I can't find .Net Core SDK v3.0 prev8 on the installed programs on the machine.

[Microsoft_.NET_Core_SDK_3.0.100_-_preview8_(x64)_20190901145432.log](https://github.com/dotnet/corefx/files/3566082/Microsoft_.NET_Core_SDK_3.0.100_-_preview8_.x64._20190901145432.log)

**Comment by ViktorHofer** [comment]
Issue moved to [dotnet/core-sdk #4524](https://github.com/dotnet/core-sdk/issues/4524) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ViktorHofer** [comment]
Issue moved to [dotnet/core-sdk #4523](https://github.com/dotnet/core-sdk/issues/4523) via [**ZenHub**](https://www.zenhub.com/)

**Comment by E1adi** [comment]
@ViktorHofer Thank you for moving my issue to the relevant place.
