### ISSUE TITLE
HandleNull in JsonSerializer Throws before invoking custom JsonConverter

### ISSUE THREAD

**Issue by suedama1756** [dotnet/corefx#40756]
Dotnet Core: 3.0.100-preview7-012821

I have a custom Option<T> struct type similar to the Option monad type supported in other languages such as scala. I have written a simple OptionJsonConvertFactory which is generally working as expected, however, the HandleNull routing in JsonSerializer appears to be using reflection on the type to verify whether the target type supports nulls and throws when deserializing "null" before ever calling my converter.

Looking through the source I can see CustomConverterTests.ValueTypeConverterForNullWithArray tests that seem to indicate this functionality should be supported, however, these tests fail if I copy and run them.

Has this already been fixed?

**Comment by suedama1756** [comment]
Apologies, I can see this is fixed and merged already. I'm hoping its in the next release for 3...

**Comment by ahsonkhan** [comment]
@suedama1756 - was the issue resolved for you with latest?

Can you share a small repro of the issue you were seeing, primarily so I can track where the fix for your scenario came from?
