### ISSUE TITLE
RemoteExecutor.Invoke incurs large overheads with checked coreclr

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#40773]
Every call to RemoteExecutor.Invoke appears to be adding more than a second of overhead when using a checked coreclr build. For example, a Regex test using RemoteExecutor.Invoke that takes ~0.1 seconds on a release coreclr takes ~1.4s on a checked coreclr.  This adds a non-trivial amount of execution time to some coreclr CI legs, and I believe contributes to some of the timeouts we see in coreclr CI.

In corefx tests, we have ~500 call sites to RemoteExecutor.Invoke.  But some of those are theories.  Watching a `build -test` execution locally for inner loop execution, RemoteExecutor.Invoke is used 2137 times (that's how many dotnet.exe processes are created with RemoteExecutor.dll on the command line, according to Process Monitor).  If each adds 1s of overhead, that's **~36 minutes** of overhead in each coreclr checked CI leg.

This appears to be less about RemoteExecutor.Invoke itself and more about all of the validation that happens in a checked build as part of starting the runtime, so I'm not sure what we can do about it, other than using RemoteExecutor.Invoke more sparingly (and maybe finding ways to trim back on the cost of the checked validation performed).

cc: @ViktorHofer, @jkotas

**Comment by ViktorHofer** [comment]
Does the same overhead apply to other out-of-proc executions? We have some test executables in our reflection and S.R.Extensions tests.

**Comment by stephentoub** [comment]
For managed executables.  But the number of times RemoteExecutor.Invoke is run is orders of magnitude more than those, if I'm thinking of the same ones.

**Comment by jkotas** [comment]
> ~1.4s on a checked coreclr

Just want to make sure - is this number with R2R CoreLib or IL-only CoreLib?

We have number of CoreFX tests disabled for the default CoreCLR runs because of they are too slow on checked CoreCLR. If the RemoteExecutor tests are always slow on checked CoreCLR, we may consider disabling all them.

**Comment by stephentoub** [comment]
> Just want to make sure - is this number with R2R CoreLib or IL-only CoreLib?

This was with building my local coreclr repo with `build -checked -skiptests`, building corefx against it with `/p:CoreCLROverridePath`, and then running corefx tests as normal.  I assume that's with R2R?

**Comment by jkotas** [comment]
> I assume that's with R2R?

That setup uses IL-only CoreLib. The scripts go out of their way to make it happen: https://github.com/dotnet/corefx/blob/master/eng/restore/runtime/runtime.depproj#L114

A simple way to improve this would be to switch to R2R CoreLib.

**Comment by stephentoub** [comment]
Looking over our usage of RemoteExecutor.Invoke, a lot of it is due to UAP's CultureInfo.CurrentCulture being process-global rather than thread-local.  We could remove many of these if we stopped running these tests on UAP.  Alternatively, or in the interim, we could change many of these call sites to use a RemoteExecutor.InvokeIfUap that invoked the delegate remotely if it was uap and locally/synchronously in the same process for everywhere else.

**Comment by tarekgh** [comment]
> Alternatively, or in the interim, we could change many of these call sites to use a RemoteExecutor.InvokeIfUap

I prefer that, just in case we'll need to get that back in the future for any reason. But I would be OK either way.

**Comment by eiriktsarpalis** [comment]
There's also the possibility of using `System.Runtime.Loader` in cases where the sole motivation is isolation of statics.

**Comment by jkotas** [comment]
> We could remove many of these if we stopped running these tests on UAP (or were able to change the behavior)

It should be safe to bet ok that we will change the behavior. The plan for UAP is not 100% agreed upon yet, but the likely outcome is:
- We are going to get rid of this and other uap quirks and unify with mainstream .NET Core
- UAP TFM as it exists today will disapper. UAP is going to be yet another Windows flavor that we test on (e.g. similar to Windows Nano)

> possibility of using System.Runtime.Loader in cases where the sole motivation is isolation of statics.

This does not work for CoreLib where most of these live currently.
