### ISSUE TITLE
SignalR sends incomplete JSON in socket frames when using new System.Text.Json Serializer

### ISSUE THREAD

**Issue by suedama1756** [dotnet/corefx#40770]
3.0.100-preview8-013656

SignalR JS Client: 3.0.0-preview6.19307.2

We have an issue where SignalR is sending incomplete JSON in a socket frame to the browser which results in an error in the signalr client.

```js
 if (input[input.length - 1] !== TextMessageFormat.RecordSeparator) {
            throw new Error("Message is incomplete.");
   }
```

The issue does not occur when using the NewtonSoft JSON serializer. It looks like the JSON buffer is not being flushed correctly

**Comment by BrennanConroy** [comment]
This issue was moved to aspnet/AspNetCore#13651
