### ISSUE TITLE
Why does LINQ not optimize for read only collections?

### ISSUE THREAD

**Issue by mikernet** [dotnet/corefx#40798]
Why don't LINQ methods check for `IReadOnlyCollection<T>` instead of `ICollection<T>`, `IReadOnlyList<T>` instead of `IList<T>`, etc. for optimizations? 

This is part of the reason read-only collections are effectively useless and unusable in .NET unless they also implement the writeable versions of the interfaces with a bunch of `throw NotSupportedException()` interface method implementations, but then what's the point?

**Comment by Wraith2** [comment]
Doing so causes a performance degradation for everyone and is only useful in a small number of cases.

See 
https://github.com/dotnet/corefx/issues/26579
https://github.com/dotnet/corefx/issues/32569
https://github.com/dotnet/corefx/issues/32570
https://github.com/dotnet/corefx/issues/24773
https://github.com/dotnet/corefx/issues/17629

**Comment by mikernet** [comment]
In that case the utility provided by the read-only interfaces being variant is completely overshadowed by this issue. It would have been way better to leave them as invariant so that they could actually be used. How often do people actually use collection interface variance? I've yet to see it used anywhere. This effectively makes them useless.

This makes me sad...very sad. Ah well.

**Comment by scalablecory** [comment]
perf impact isn't actually that large considering it only hits the initial LINQ extension method, not iteration.

Can you demonstrate the benefit of this? What collections are there that don't implement the writable interface?

**Comment by mikernet** [comment]
According to the above, CoreRT solved the invariant casting performance issue with some caching. There are many other places that follow this pattern of optimizing for `IList<T>` and `ICollection<T>` when all it does is read and it's a royal pain, especially because I would like to program against read only interfaces but it's entirely impractical at the moment. I end up having to cast up to IList and ICollection all over the place to ensure proper optimizations take place so I gave up. 

This is just another nail in the coffin of practically using read only collections among many other problems that permeate through the entire framework and demonstrates why design compromises of this magnitude for the sake of performance in situations that can be optimized by the CLR in the future is a bad idea...we can effectively never go back now...there are tons of methods that take `IList<T>` instead of `IReadOnlyList<T>` and you can't add another method side-by-side with a read only signature because `IList<T>` doesn't implement `IReadOnlyList<T>` so you get ambiguos method call errors when you do that. It's just a huge steamy pile of doo doo.

We have several custom collection types that are indexable but can't be modified through the `IList<T>` interface, or which can count efficiently but can't add or remove items via `ICollection<T>` methods....but we are forced to implement the full writable interfaces every time.

**Comment by Wraith2** [comment]
What stops you providing your own linq function implementations?

**Comment by mikernet** [comment]
With DIM there's a possibility that a small set of optimizable LINQ methods can call DIMs that provide more optimized versions of the algorithms but otherwise it's too finicky...you just end up with side-by-side LINQ methods that behave differently depending on whether your object is stored as an `IReadOnlyCollection<T>` or an `IEnumerable<T>`.

**Comment by mikernet** [comment]
You also end up with "ambiguous method call" errors if you use a class that explicitly specifies that it implements both `IReadOnlyCollection<T>` and `IEnumerable<T>`, which I have run into before. There are workarounds but it just ends up being annoying and/or error prone.

In the case of me exposing a property as an `IReadOnlyCollection<T>`, the user of my library now has to also know to use the optimized LINQ methods instead of the normal ones, and if they pass the collection to any methods that consume it as an `IEnumerable<T>` then it uses unoptimized LINQ instead. Internally I can use my optimized calls but it isn't a good user experience.

**Comment by stephentoub** [comment]
Closing as a dup of all the issues listed by @Wraith2 above.
