### ISSUE TITLE
StreamPipeWriter shouldn't flush when Completed with Exception

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#40812]
StreamPipeWriter is flushing when it is Completed with an Exception.
I'd expected it to abort pending write operations instead of trying to flush them. Otherwise the writer has no way of aborting pending writes.

https://github.com/dotnet/corefx/blob/aea8a56edf54228029b0f9ddf369e4d4f82f4446/src/System.IO.Pipelines/src/System/IO/Pipelines/StreamPipeWriter.cs#L204-L221

CC @davidfowl

**Comment by davidfowl** [comment]
This is by design to avoid truncation of data when flush async isn’t called. When wrapping a stream, the underlying call to dispose also does the same thing. 

Maybe the exception being non-null could indicate that any buffered writes could be discarded.

**Comment by tmds** [comment]
Consider:
```
// Try to flush for 500 ms
await writer.FlushAsync(new CancellationTokenSource(500).Token);
```
How to get rid of the data without flushing?

**Comment by davidfowl** [comment]
Call complete with an exception. I think that's the best indication about aborting any buffered data.
