### ISSUE TITLE
Sources for System.Threading.Tasks.Extensions 4.5.2

### ISSUE THREAD

**Issue by rhegner** [dotnet/corefx#40827]
Which tag/commit of this repository does contain the sources for "System.Threading.Tasks.Extensions 4.5.2"? I need this information for compliance reasons in our company.

PS: I did try to use the https://github.com/dotnet/versions repository to find the answer to my question, but "System.Threading.Tasks.Extensions 4.5.2" cannot be found in that repository (see also my related issue https://github.com/dotnet/versions/issues/502).

**Comment by stephentoub** [comment]
@rhegner, FYI the binary in the nuget package includes the commit from which it was built (on Windows right-click, Properties, Details tab, Product version).  In this case, the commit is https://github.com/dotnet/corefx/commits/99ce22c306b07f99ddae60f443d23a983ae78f7b.

**Comment by stephentoub** [comment]
It's also on the nuget page:
https://www.nuget.org/packages/System.Threading.Tasks.Extensions/4.5.2
![image](https://user-images.githubusercontent.com/2642209/64345651-b80b6080-cfbe-11e9-899e-b7e82a64a998.png)

**Comment by rhegner** [comment]
Thanks @stephentoub , that's really useful information!

**Comment by dagood** [comment]
If you open up the nupkg (it's just a zip) or have it restored into a package cache, the info on the NuGet page is also available in the `.nuspec` xml file.
