### ISSUE TITLE
System.Text.Json.JsonSerializer can not handle recursion, even when there is none

### ISSUE THREAD

**Issue by tabinnorway** [dotnet/corefx#40826]
The following will crash, rendering .net core useless for most real world applications. Tested with Preview 8. Newtonsoft handles it with no issues. There are huge amounts of situations where an object can contain "child" objects of its own class. Not just folders.

```csharp
   public class AUser
    {
        public string Fullname { get; set; }
        public AFolder Folder { get; set; }
    }

    public class AFolder
    {
        public string Name { get; set; }
        public IList<AFolder> SubFolders { get; set; }
    }

...
var us = new AUser {
   Folder = new AFolder {
      SubFolders = null // For good measure
   }
};

var t = System.Text.Json.JsonSerializer.Serialize(us);

**Comment by tabinnorway** [comment]
Fixed in Preview 9 - thanks :-)

**Comment by ahsonkhan** [comment]
This doesn't repro in Preview 9 builds. Try upgrading to the latest SDK/package.

This is a duplicate of https://github.com/dotnet/corefx/issues/40608, https://github.com/dotnet/corefx/issues/40050, and https://github.com/dotnet/corefx/issues/39769  /cc @steveharter 

Thanks for the report!
