### ISSUE TITLE
HttpClient has big problems if server sends back result before Post is completed

### ISSUE THREAD

**Issue by mshiels** [dotnet/corefx#40834]
Based on wireshark traces and a customers server issue we have been debugging I am finding that things seem to be getting confused internally in this situation.

Very basic client side code - since it can't really take advantage of any async stuff right now.
Result = Post.SendAsync(Request).Result;
Content = Result.Content.ReadAsStringAsync().Result;

And in this case we are uploading a very large form-data (with 100-continue disabled) and the server about 100ms into the upload blasts back a HTTP error chunk and terminates the socket or in the case of SSL sends the 'close pending' SSL notice and closes the socket. 

What is truly scary is that accessing the Result object shows '200', 'ok'.  When in this case there was absolutely no way it could be valid.   I had to write a raw socket LinqPad script to be my test server since we can not test against our customer's server.  So it seemed the first transaction I sent would always be 200/ok, but then second+ transactions get the error - but I am doing some more testing to see if they are getting the error from the prior transaction or the current one.
But the bigger problem is that in this situation the Result.Content is null - I assume since things got aborted during the send.  

It's not a very normal situation at all - but it does occur and handling of this seems problematic at best.

**Comment by stephentoub** [comment]
Can you please share a simple repro of the situation you're describing?  I'm having trouble following from the text.

And what version of .NET Core are you using?  What OS?

**Comment by mshiels** [comment]
Running actually .Net 4.6.1 but latest HttpClient 4.3.4 I think it was.  As far as I could tell this was teh right place to post, but maybe not.  

I'll see if I can describe it in more detail - it is a crazy situation - but it's one we have run into multiple time with multiple different clients and is generally very badly handled by almost all client side toolkits.   No one is expecting/processing received data if the send itself failed, but sometimes it's available and tells you why the send failed.  

Server basically is doing the following.  It starts to accept the very large form-data POST but along the way and before the data has been all sent it sends back a response and terminates the socket.   The error ranges from transaction too big to - can't load code - or can't find gateway (ie it's working as a reverse proxy/load balancer).

The client side code of course is in the middle of sending, when kaboom the connection has data being received and then terminates the socket.  Slightly different behaviour if it's a SSL connection since I can see the SSL 'close pending(?)' transaction just before the socket really closes.

The issue is that in the HttpClient code it seems I get back a half baked HttpResponseMessage since it's marked as '200' OK but has NO HEADERS, CONTENT IS NULL etc.  it almost looks like a default construction of the HttpResponseMessage with nothing filled in.  So accessing the IsSuccessStatusCode property returns 'true' but it really should not be, since technically the upload failed, and we got back a nice http buffer of failure information.  

The client code in a sync flavour calls Response.Content.ReadAsStringAsync().Result - but since Response.Content IS NULL things really are in a wonky state.

**Comment by davidsh** [comment]
>Running actually .Net 4.6.1 but latest HttpClient 4.3.4 I think it was. As far as I could tell this was teh right place to post, but maybe not.

This repo is only for .NET Core issues.  .NET Framework issues can be reported here.
https://developercommunity.visualstudio.com/spaces/61/index.html

However, the latest version of .NET Framework is 4.8. You might try that. But future innovation for .NET Framework will only happen in .NET Core releases such as .NET 5.  See:

https://devblogs.microsoft.com/dotnet/introducing-net-5/
https://devblogs.microsoft.com/dotnet/net-core-is-the-future-of-net/

You might also try moving your application to .NET Core.  Latest .NET Core 3.0 Preview available:
https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-9/

**Comment by mshiels** [comment]
Been trying to figure out what 'source repository' system.net.http is built from that is in Nuget - I have spelunked fairly far into in a prior coding session,  Dinosaur developer here who has a heck of a time finding which source went into what project to get what .net library these days!!  So many similar ones in some cases private builds etc.  

I am not sure the framework version will matter much since System.Net.Http is a Nuget package probably same code built for each flavour right??

Our main engine here is a bit harder to port over since it involves multiple appdomain capabilities and involves alot of code!!   We use the multiple appdomains to ensure we can have different bits/pieces of our code that can use/run different dependancy libraries.   It works great, but .net Core abandoned Appdomains so not sure how we can do this in .Net Core.  it is the future but I just don't want to be the one trying it on this engine project.

**Comment by mshiels** [comment]
I'm going to try re-creating the situation I have right now with .Net Core 3 since I can run/build a portion of this code for LinqPad script testing etc.

**Comment by davidsh** [comment]
>I am not sure the framework version will matter much since System.Net.Http is a Nuget package probably same code built for each flavour right??

You should avoid using the System.Net.Http NuGet package. In general, it is no longer needed.  System.Net.Http already is part of .NET Framework.  And for .NET Core, most of the needed binaries are contained in the default Microsoft.NETCore.App package. The System.Net.Http NuGet package has a set of problems (see #11100, #17522 etc.). So, you should avoid it.

**Comment by mshiels** [comment]
oh it wasn't part of the frameworks last time I tried enabling this integration, so live and learn.   I'll try my testing again.  But it's so confusing between documentation and what's available.  ServerCertificateCustomerValidationCAllback is documented but look slike I need to be 4.7.2 at least, I'll check/see if this is still an issue with pure .Net core as well.
