### ISSUE TITLE
VB tests not running correctly on Linux/macOS

### ISSUE THREAD

**Issue by filipnavara** [dotnet/corefx#40842]
PR #40365 added couple of new test for Microsoft.VisualBasic.Core assembly. The following tests access registry and work on Windows only:

- Microsoft.VisualBasic.Tests.InteractionTests.SaveSetting
- Microsoft.VisualBasic.Tests.InteractionTests.DeleteSetting
- Microsoft.VisualBasic.Tests.InteractionTests.GetAllSettings
- Microsoft.VisualBasic.Tests.InteractionTests.GetSetting

The tests are guarded by the following condition:

https://github.com/dotnet/corefx/blob/063568705557b469606eef1069946484d78034ae/src/Microsoft.VisualBasic.Core/tests/InteractionTests.cs#L14

Unfortunately the condition is incorrect for non-Windows platforms.

It should be fixed. Also, it should be investigated why it doesn't trigger an error on the CI. We initially discovered it on Mono on macOS which consumes the CoreFX test assemblies through a feed.

**Comment by ViktorHofer** [comment]
I just built Mirosoft.Win32.Registry on a Unix machine and the assembly contains the actual implementation code from Win32 instead of PNSE members.

cc @ericstj @safern

**Comment by ViktorHofer** [comment]
> Also, it should be investigated why it doesn't trigger an error on the CI. We initially discovered it on Mono on macOS which consumes the CoreFX test assemblies through a feed.

The condition is correct, even though its name is misleading. Those mentioned tests are negative tests that throw `ArgumentException` on both Windows and Unix and the condition `s_SupportsRegistry` is only used for those.

If a positive test would use that condition it would fail on Unix with a PNSE. On UAP the validation code isn't even reached and a PNSE is thrown immediately, therefore the distinction exists: https://source.dot.net/#Microsoft.VisualBasic.Core/Microsoft/VisualBasic/Interaction.vb,466.

1) We should change the condition's name in corefx
2) We should investigate on Mono's side why the tests are failing.

**Comment by filipnavara** [comment]
Part of the problem could be that Mono is too eager with some initialization (possibly within the bounds of ECMA 335 specification but not identical to CoreCLR). The actual failure on the CI was the following:

```
Assert.Throws() Failure
Expected: typeof(System.ArgumentException)
Actual: typeof(System.TypeInitializationException): The type initializer for 'Microsoft.Win32.Registry' threw an exception.
---- System.TypeInitializationException : The type initializer for 'Microsoft.Win32.Registry' threw an exception.
-------- System.PlatformNotSupportedException : Registry is not supported on this platform.
```

The "expected" part suggests that the code path here was taken though:

https://github.com/dotnet/corefx/blob/063568705557b469606eef1069946484d78034ae/src/Microsoft.VisualBasic.Core/tests/InteractionTests.cs#L229

That code path implies that `s_SupportRegistry == true` which still looks in line with my understanding of `!PlatformDetection.IsUap` being `true` on Linux and macOS.

**Comment by filipnavara** [comment]
Ah, I guess I see what you were implying. Looks like the error is indeed related to the eager initialization then.

**Comment by ViktorHofer** [comment]
> Ah, I guess I see what you were implying. Looks like the error is indeed related to the eager initialization then.

cc @akoeplinger

**Comment by filipnavara** [comment]
Thanks for all the help! I'll do some more tests on the weekend and create a new Mono issue if it turns out to be problem there.
