### ISSUE TITLE
IsolationLevel is missing the FlagsAttribute

### ISSUE THREAD

**Issue by snappyfoo** [dotnet/corefx#40848]
The [documentation ](https://docs.microsoft.com/en-us/dotnet/api/system.data.isolationlevel?view=netcore-2.2)for IsolationLevel states that it has the FlagsAttribute, meaning that values can be combined. But trying to do so gives the error "Bitwise operation on enum which is not marked by [Flags] attribute"

Looking at the [source code](https://github.com/dotnet/corefx/blob/master/src/System.Data.Common/src/System/Data/IsolationLevel.cs) shows that it doesn't have the attribute.

Am I missing something? Please help me out here, I was hoping to be able to combine ReadCommitted and Snapshot as there is a READ_COMMITTED_SNAPSHOT isolation level in SQL Server and I assumed combining those two IsolationLevels would be a way to achieve that? If not, how?

**Comment by mburbea** [comment]
Read_commited_snapshot isolation (RCSI) is not an isolation level in the traditional sense, but a database level setting. RCSI basically replaces read_committed with snapshot isolation. Since read_committed is the default setting, RCSI basically makes snapshot isolation the default.

If you want to get RCSI behavior the easiest way is to enable_snapshot on your server and manually set the isolation to snapshot. Or turn on the RCSI setting.

**Comment by snappyfoo** [comment]
Thank you for that, that's cleared a couple of things up for me.

Also, I have subsequently found that the "error" I have is a ReSharper warning, and that enums without the Flag attribute can still be combined, but the behaviour isn't always guaranteed. In any case, I don't need to combine them any more, so the issue doesn't affect me.

But I do think there is an issue with either the documentation or the code, as they don't agree with each other.

**Comment by snappyfoo** [comment]
> If you want to get RCSI behavior the easiest way is to enable_snapshot on your server and manually set the isolation to snapshot. Or turn on the RCSI setting.

Just to double check, are you saying that setting ALLOW_SNAPSHOT_ISOLATION ON in the DB and using Snapshot as my IsolationLevel for the transaction is the same as setting READ_COMMITTED_SNAPSHOT ON in the DB and using ReadCommitted?

**Comment by Suchiman** [comment]
@snappyfoo no, Read Committed Snapshot Isolation means that reads (SELECT) will use Snapshot isolation (row versioning) but writes (Insert, Update, Delete, Merge, etc.) will use traditional read committed isolation (two phase locking)

**Comment by roji** [comment]
Regardless of the above discussion, this does seem to be a documentation bug - the IsolationLevel enum doesn't (and shouldn't) have `[Flags]`. @divega any interesting history here that you're aware of? Will submit a doc PR.

**Comment by roji** [comment]
Have opened https://github.com/dotnet/dotnet-api-docs/issues/3141 to track the doc discrepancy, will leave this open for @divega to confirm that it shouldn't be possible to combine isolation levels.

**Comment by divega** [comment]
It is not possible to combine them, as far as I am aware. Since @roji already create a separate issue to track the API docs bug, and the question on how to enable read committed snapshot were answered by @Suchiman and @mburbea, closing this.
