### ISSUE TITLE
API Proposal: SequenceReader<T>.TryPeek overloads for look ahead

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#40845]
Today it isn't easy to get the value at a specific position from the `ReadOnlySequence<T>` making it hard to write parsers that look ahead at data without moving the reader.

```C#
public partial ref struct SequenceReader<T>
{
    bool TryPeek(SequencePosition position, out T value);
    bool TryPeek(int count, out T value);
}
```

cc @softworkz

**Comment by JeremyKuhne** [comment]
I think a better choice here would be:

```C#
public partial ref struct SequenceReader<T>
{
    bool TryPeek(int skip, out T value);
}
```

Picking an arbitrary start position makes the reader confusing- it has a position and is mostly forward-only. In addition the perf characteristics would be way out of line with the related methods.

**Comment by softworkz** [comment]
You mean that this method should actually advance the reader?

**Comment by JeremyKuhne** [comment]
> You mean that this method should actually advance the reader?

No, the peek methods shouldn't advance the reader at all. The idea here is that you can peek ahead for a value without having to get a set of values or rewinding the reader. Say, peek for a CR then peek again for a LF, rather than a CR/LF (as a simple example).

**Comment by softworkz** [comment]
Ah ok. So what are you implying by changing:

`bool TryPeek(int count, out T value);`

to 

`bool TryPeek(int skip, out T value);`

Was it just about a better parameter naming then?

**Comment by JeremyKuhne** [comment]
> Was it just about a better parameter naming then?

Yep.

**Comment by softworkz** [comment]
I apologize - I misunderstood.

**Comment by ahsonkhan** [comment]
Are we fine with having to incur the cost of slicing the sequence and fetching the span again (for the API that takes a `SequencePosition`)? The other existing APIs on `SequenceReader` do not have this overhead. This concern would apply to all the APIs that take an arbitrary `SequencePosition`.

Maybe, something like this:
```C#
public readonly bool TryPeek(SequencePosition position, out T value)
{
    ReadOnlySequence<T> sequence = Sequence.Slice(position);

    ReadOnlySpan<T> span = sequence.FirstSpan;

    if (!span.IsEmpty)
    {
        value = span[0];
        return true;
    }
    else
    {
        value = default;
        return false;
    }
}
```

**Comment by JeremyKuhne** [comment]
Approved: #40962 (comment):

``` C#
        public bool TryPeek(int skip, out T value);
```

**Comment by ahsonkhan** [comment]
@JeremyKuhne - the parameter name isn't `skip`. It should be `offset`.

Also, don't forget the `readonly` keyword (+ the comment link needs to be updated).

**Comment by JeremyKuhne** [comment]
>  the parameter name isn't skip. It should be offset.

Copy/paste fail. Fixing.
