### ISSUE TITLE
NetworkInformation X-Plat Failures

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#4085]
System.Net.NetworkInformation.Tests.IPInterfacePropertiesTest.IPInfoTest_AccessAllIPv4Properties_NoErrors [FAIL]  System.Net.NetworkInformation.Tests.IPInterfacePropertiesTest.IPInfoTest_AccessAllIPv6Properties_NoErrors [FAIL]
System.Net.NetworkInformation.Tests.IPInterfacePropertiesTest.IPInfoTest_AccessAllProperties_NoErrors [FAIL]
 System.Net.NetworkInformation.Tests.IPInterfacePropertiesTest.IPv6ScopeId_AccessAllValues_Success [FAIL]
System.Net.NetworkInformation.Tests.IPInterfacePropertiesTest.IPv6ScopeId_GetLinkLevel_MatchesIndex [FAIL]
System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_AccessInstanceProperties_NoExceptions [FAIL]
System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_GetIPInterfaceStatistics_Success [FAIL]
System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_StaticIPv6LoopbackIndex_MatchesLoopbackNetworkInterface [FAIL]
System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_StaticLoopbackIndex_MatchesLoopbackNetworkInterface [FAIL]

**Comment by ellismg** [comment]
This may not be a real thing, I think there was some weird timing issue with how a job ran and @mellinoe's fixes.

**Comment by mellinoe** [comment]
Hm, what platform was that on? I think those are all marked as Windows-only right now so they shouldn't even show up x-plat.

**Comment by ellismg** [comment]
This was running on Linux, in CI (for my merge TFS job).  I kicked off another build to see if happens again, I agree that with your recent changes we shouldn't be hitting this.

**Comment by ellismg** [comment]
I think this was just bad timing.

**Comment by stephentoub** [comment]
Yeah, I've run into this before.  The test job that runs on the Linux machines gets the current source and sees if the .csproj files contain UnsupportedPlatform for Linux, but it could be running with bits built from a version of the source before that change got checked in.  The fix here I think is to stop using this UnsupportedPlatform mechanism, that requires looking at the .csproj files, and instead modify [PlatformSpecific] / [ActiveIssue] to support being used at the assembly level.  Then we can simply use the same mechanism we already do for skipping tests, just skipping all tests in an assembly attributed this way, and we have the single mechanism that's in the binary so we're not looking at two different places to determine the tests to run and whether to run them.

**Comment by ellismg** [comment]
Why can we not configure Jenkis such that all the sub-jobs get the same sha?  Is the problem that github is updating the ref all the time to point to the new merged sha?

Ideally all the jobs would run against the same merged sha that the master job was kicked off against.

**Comment by stephentoub** [comment]
We probably can.  If we already have, I have no idea why it's failing; this is the only explanation I previously came up with.

Regardless, even if we made such a change, I still think we should get rid of the UnsupportedPlatforms mechanism and just have the PlatformSpecific/ActiveIssue attributes in the code.

**Comment by ellismg** [comment]
Okay, makes sense.  @bartonjs and I had the same basic hunch as you, BTW.
