### ISSUE TITLE
Disposing the FileSystemWatcher does not close associated file descriptors

### ISSUE THREAD

**Issue by mrward** [dotnet/corefx#40888]
Filed this against Mono, which uses corefx, but the problem also affects corefx.

https://github.com/mono/mono/issues/16709

## Steps to Reproduce

Related problem - https://github.com/mono/mono/issues/15931

1. Sample project - https://github.com/mrward/test-file-watcher-dispose - multi-target project that builds .NET 4.7.2 and .NET Core 2.1
2. Build this project.
3. From the command line run `dotnet bin/debug/netcoreapp2.1/FileWatcherDisposeTest.dll`
4. Run `lsof -p pid`. Process id is output from the console app.
5. See that the file watcher creates file descriptors for several directories.
6. After 10 seconds the file watcher will be disposed.
7. Run `lsof -p pid` again.

### Current Behavior

lsof still lists the directories.

```
dotnet 3972 user    4r DIR   1,12      170   51740695 /Volumes/Drive/projects/tests/FileWatcherDisposeTest/FileWatcherDisposeTest/bin/Debug/net472
dotnet 3972 user    5r DIR   1,12      136   51740600 /Volumes/Drive/projects/tests/FileWatcherDisposeTest/FileWatcherDisposeTest/bin/Debug
dotnet 3972 user    6r DIR   1,12      102   51740599 /Volumes/Drive/projects/tests/FileWatcherDisposeTest/FileWatcherDisposeTest/bin
dotnet 3972 user    7r DIR   1,12      204   51740594 /Volumes/Drive/projects/tests/FileWatcherDisposeTest/FileWatcherDisposeTest
dotnet 3972 user    8r DIR   1,12      170   51740593 /Volumes/Drive/projects/tests/FileWatcherDisposeTest
dotnet 3972 user    9r DIR   1,12     6324     185300 /Volumes/Drive/projects/tests
dotnet 3972 user   10r DIR   1,12     2312        278 /Volumes/Drive/projects
dotnet 3972 user   11r DIR   1,12      646          2 /Volumes/Drive
dotnet 3972 user   12r DIR    1,4      160     420284 /Volumes
```
If you change the console project to run GC.Collect after the dispose does not fix the problem (this does work with Mono)

### Expected Behavior

File watcher directories not listed by lsof.

Note that 

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview9-014004
 Commit:    8e7ef240a5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100-preview9-014004/

Host (useful for support):
  Version: 3.0.0-preview9-19423-09
  Commit:  2be172345a

.NET Core SDKs installed:
  2.1.701 [/usr/local/share/dotnet/sdk]
  3.0.100-preview9-014004 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by danmosemsft** [comment]
I don't know this code I just scanned it. But should this handle be explicitly disposed somewhere? @JeremyKuhne @carlossanlop 

https://github.com/dotnet/corefx/blob/bca549851e2b24eceb1968a4a8ebab5f2ba4f7f2/src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs#L143

**Comment by scalablecory** [comment]
@wfurt was recently looking at `FileSystemWatcher` on OSX

**Comment by wfurt** [comment]
I can take a look as well I can run repro on Linux for comparison. Also note that there was issue with Sockets that in some cases underlying handle would not be properly closed. That would show up if you target 2.1 even if you use 3.0 SDK.

**Comment by marek-safar** [comment]
@danmosemsft @karelz this is impacting VS4M, it would be great to prioritize the investigation so we know what the options are for us.

**Comment by Therzok** [comment]
Profiling this, I found that the RunningInstance is being alive by these 2 paths. Sadly, there are no field names, as the mono profiler does not report field names.

<img width="675" alt="Screenshot 2019-09-07 at 13 55 37" src="https://user-images.githubusercontent.com/109974/64474048-58a48080-d177-11e9-80ba-39892080b9c7.png">
<img width="649" alt="Screenshot 2019-09-07 at 13 55 34" src="https://user-images.githubusercontent.com/109974/64474049-59d5ad80-d177-11e9-8c8e-c42f69a2c16a.png">

**Comment by Therzok** [comment]
These both keep the EventStreamSafeHandle and EventStreamCallback instances alive, leading to the native one not being released.

**Comment by Therzok** [comment]
To note, the System.IO.CoreFX.FileSystemWatcher namespace is due to a change in mono:
https://github.com/mono/corefx/blob/master/src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs#L19-L24

**Comment by Therzok** [comment]
It's not just the safeHandle, the CancellationToken registration should also be disposed:
https://github.com/dotnet/corefx/blob/bca549851e2b24eceb1968a4a8ebab5f2ba4f7f2/src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs#L173

**Comment by danmosemsft** [comment]
@therzok if you modify the code to do that can you confirm it solves it?

**Comment by Therzok** [comment]
@danmosemsft Don't have cycles available to take a look at it right now.

**Comment by danmosemsft** [comment]
@Therzok not a problem, thanks for adding the information.

**Comment by slluis** [comment]
It would be great to have a quick fix for this. It has an important impact in VSMac.

**Comment by danmosemsft** [comment]
@slluis could you tell us more about the impact? Is this somehow a new problem?

What versions of .NET Core would VSMac require a fix in?

**Comment by mrward** [comment]
@danmosemsft The fix in corefx would be backported to Mono. Not sure what version of corefix Mono would be using. @steveisok may know more.

Currently this causes VS Mac to keep file descriptors around after file watchers are disposed. Eventually this breaks Mono's networking stack, which has a limit of 1024 file descriptors.

**Comment by wfurt** [comment]
I'll take a look. I drop it before as it look like @Therzok  was digging into it.

**Comment by Therzok** [comment]
@wfurt just wanted to provide some assistance on the issue, as the retention paths should most likely be the same :smile:

**Comment by steveisok** [comment]
Mono is set up to track 2.2, so if a fix lands there it would be the easiest.

**Comment by wfurt** [comment]
I put up PR with proposed fix. I'm not sure if possible but it would be great if anybody can give it try with VS. 
It does fix issue observed with provided repro.

**Comment by Therzok** [comment]
It fixes it!

**Comment by danmosemsft** [comment]
@steveisok can you confirm that VS for Mac does _not_ need this back ported in corefx (eg., to 3.0.1) since evidently VS for Mac is consuming it out of the Mono sources?

**Comment by steveisok** [comment]
Correct.  We do not need it backported.

**Comment by wfurt** [comment]
the extra code is to make sure Dispose() works concurrently from multiple threads. That may not be VS/Mac use case.  I also put more notes to #39881 (just in case it matters for VS use)

**Comment by danmosemsft** [comment]
@wfurt since VS for mac does not need a backport my suggestion is to close this and wait see whether we get customer feedback that justifies a backport. Taht also gives more time for it in master. If you agree -we can close this.

**Comment by wfurt** [comment]
should we get this to master @danmosemsft ? I was waiting for somebody from core team to review this before merging to master.

**Comment by danmosemsft** [comment]
Oh - yes for sure @wfurt. I missed that it wasn't in master yet.
