### ISSUE TITLE
Make generic collection interfaces implement non-generic collection interfaces

### ISSUE THREAD

**Issue by TylerBrinkley** [dotnet/corefx#40893]
When dealing with collections from a non-generic context such as a serializer you must access the collection through the non-generic collection interfaces. Sometimes you can just cast the collection to the non-generic collection interface but when the collection does not implement the non-generic interface such as with `HashSet<T>` you must then use some reflection and wrap the collection in a new collection object that does implement the non-generic interface. This is somewhat difficult and is a pain in general. I propose considering making the generic collection interfaces implement the non-generic collection interfaces through the use of default interface implementations.

## Proposed API
```diff
 namespace System.Collections.Generic {
-    public interface ICollection<T> : IEnumerable<T> {
+    public interface ICollection<T> : IEnumerable<T>, ICollection {
-        int Count { get; }
+        new int Count { get; }
+        bool ICollection.Count => Count;
+        bool ICollection.IsSynchonized => false;
+        object ICollection.SyncRoot => this;
+        void ICollection.CopyTo(Array array, int index) => array is T[] a ? CopyTo(a, index) : throw (array == null ? new ArgumentNullException(nameof(array)) : new ArgumentException());
     }
-    public interface IList<T> : ICollection<T> {
+    public interface IList<T> : ICollection<T>, IList {
-        T this[int index] { get; set; }
+        new T this[int index] { get; set; }
-        void Clear();
+        new void Clear();
-        void RemoveAt(int index);
+        new void RemoveAt(int index);
+        bool IList.IsFixedSize => throw new NotSupportedException();
+        bool IList.IsReadOnly => IsReadOnly;
+        object IList.this[int index] { get => this[index]; set => this[index] = GetValue(value); }
+        int IList.Add(object value) {
+            Add(GetValue(value));
+            return Count - 1;
+        }
+        void IList.Clear() => Clear();
+        bool IList.Contains(object value) => Contains(GetValue(value));
+        int IList.IndexOf(object value) => IndexOf(GetValue(value));
+        void IList.Insert(int index, object value) => Insert(index, GetValue(value));
+        void IList.Remove(object value) => Remove(GetValue(value));
+        void IList.RemoveAt(int index) => RemoveAt(index);
+        private static T GetValue(object value) => value is T t ? t : (value == null ? (default(T) == null ? default : throw new ArgumentNullException(nameof(value))) : throw new ArgumentException());
     }
-    public interface IDictionary<TKey, TValue> : ICollection<KeyValuePair<TKey, TValue>> {
+    public interface IDictionary<TKey, TValue> : ICollection<KeyValuePair<TKey, TValue>>, IDictionary {
-        ICollection<TKey> Keys { get; }
+        new ICollection<TKey> Keys { get; }
-        ICollection<TValue> Values { get; }
+        new ICollection<TValue> Values { get; }
-        void Clear();
+        new void Clear();
+        bool IDictionary.IsFixedSize => throw new NotSupportedException();
+        bool IDictionary.IsReadOnly => IsReadOnly;
+        object IDictionary.this[object key] { get => this[GetKey(key)]; set => this[GetKey(key)] = GetValue(value); }
+        ICollection IDictionary.Keys => Keys;
+        ICollection IDictionary.Values => Values;
+        void IDictionary.Add(object key, object value) => Add(GetKey(key), GetValue(value));
+        void IDictionary.Clear() => Clear();
+        bool IDictionary.Contains(object key) => Contains(GetKey(key));
+        IDictionaryEnumerator IDictionary.GetEnumerator() => new EnumeratorWrapper(GetEnumerator());
+        void IDictionary.Remove(object key) => Remove(GetKey(key));
+        private static TKey GetKey(object key) => key is TKey t ? t : throw (key == null ? new ArgumentNullException(nameof(key)) : new ArgumentException());
+        private static TValue GetValue(object value) => value is TValue t ? t : (value == null ? (default(TValue) == null ? default : throw new ArgumentNullException(nameof(value))) : throw new ArgumentException());
     }
 }
```

## Open Questions
* Is returning `Count - 1` reasonable for `IList.Add`?
* Is throwing a `NotSupportedException` reasonable for `IList` and `IDictionary` `IsFixedSize`?

**Comment by danmosemsft** [comment]
I'm sure there is lots of historical context here -- @terrajobst

**Comment by terrajobst** [comment]
Adding a new interface to an existing interface was a source breaking change. DIMs *might* allow us to do that, but we recently discussed this in the context of the read-only interfaces and concluded that this can result in ambiguity of the default implementations ("shared diamond"). We'll have to go through the motions of seeing what common implementers are doing and convince ourselves that shared diamonds would be extremely unlikely.

**Comment by TylerBrinkley** [comment]
While it could be useful in reflection-like scenarios, Json.NET uses the [CollectionWrapper](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Utilities/CollectionWrapper.cs) and [DictionaryWrapper](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Utilities/DictionaryWrapper.cs) classes for this purpose, the fact that the non-generic interfaces don't define some members at the same hierarchy level as the generic interfaces would cause issues, e.g. `((IList<T>)value).IsReadOnly` would now be ambiguous because it could refer to `ICollection<T>.IsReadOnly` or now `IList.IsReadOnly` and the only way to correct that would be to add a new `IsReadOnly` member to `IList<T>` directly which would be undesirable.
