### ISSUE TITLE
Reduce XPath unit tests run time

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#409]
Either reduce unit tests subset (apply [OuterLoop] to long tests) or modify tests to keep run time below 5s on average machine.

Currently on some machine they run for ~25s. Reduce it by a factor of 5.

**Comment by CoderDennis** [comment]
What are you doing to run these tests? When I run build.cmd it only runs the tests from System.Collections.Immutable, but no others. I see that using the VS test runner isn't supported yet. Could you share the command line command you're using?

**Comment by krwq** [comment]
I think all long tests are marked OuterLoop, running XPath tests takes really quickly on my machine
