### ISSUE TITLE
Do a sanity check of our ref assemblies to see if any struct is missing a dummy field

### ISSUE THREAD

**Issue by safern** [dotnet/corefx#40909]
Based on the following discussion: https://github.com/dotnet/standard/pull/1500#discussion_r321741920

We should do a sanity check to find out if we're missing any dummy field from any significant structs in our ref assemblies.

cc: @stephentoub @ahsonkhan @ericstj

**Comment by terrajobst** [comment]
Related: https://github.com/dotnet/standard/issues/1512

**Comment by safern** [comment]
I missed a special case on my tool to validate this and found 1 type that is missing a reference type field,  which is unfortunate because there could be a GC hole if someone creates a pointer of that type, however I don't think the type is too critical, the type missing it is:

`System.Text.SpanRuneEnumerator` 

The reason why it needs it, is because it has a private field of `Span<char>` type and `Span` has a `ByReference<T>` private field which holds a managed ref of `T`.

@stephentoub @jkotas @danmosemsft would that case meet the bar in order to fix it in 3.1?

**Comment by jkotas** [comment]
> GC hole if someone creates a pointer of that type

That is not accurate description of the impact.

The impact is that somebody writing unsafe code without knowing what they are doing will not get a error from the C# compiler. Somebody writing unsafe code without knowing what they are doing can do a ton more damage - without any errors from the C# compiler.

> meet the bar in order to fix it in 3.1?

I do not think so.
