### ISSUE TITLE
Supports for serializing enums to their text name

### ISSUE THREAD

**Issue by AnFa1978** [dotnet/corefx#40905]
# Issue Title
1) Define “Foo” class which provide access to enum property “Color” (enumeration has different values)
2) Create instance and serialize to json with System.Text.Json.JsonSerializer.Serialize(…)

# General
Representation of serialized enum is integer instead of string e.g. “2” instead of “Red”. Because of shared public APIs with customers it's not so easy possible to write converters for enumerations. Therefore this small feature would be very helpful to support our switch. (observed with W10 and .Net Core SDK 3.0.100 preview8 x64)

**Comment by ahsonkhan** [comment]
Support for serializing enums as strings already exists if you use the built-in `JsonStringEnumConverter` and pass that in to the `JsonSerializerOptions`:
https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonstringenumconverter?view=netcore-3.0

See other related issues:
https://github.com/dotnet/corefx/issues/38568#issuecomment-509393089
https://github.com/dotnet/corefx/issues/40497#issuecomment-524052269

Here's a sample test that uses it:
https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/tests/Serialization/ReadScenarioTests.cs#L17

**Please feel free to re-open the issue if that doesn't work for your scenario.**

**Comment by AnFa1978** [comment]
Thx for your support. Was not aware of this feature
