### ISSUE TITLE
Question: Is .Net Remoting supported? Also WCF Interfacing

### ISSUE THREAD

**Issue by ciaranmurraycm** [dotnet/corefx#4091]
We can hide .Net Remitting behind WCF and  visa versa

**Comment by ciaranmurraycm** [comment]
ciaran.murray.cm@gmail.com

**Comment by ciaranmurraycm** [comment]
ciaran.murray.cm@gmail.com

**Comment by roncain** [comment]
Hi @ciaranmurraycm .NET Remoting is not supported in .NET Core, and I am not aware of plans to add it. However, if you were using RealProxy from the full framework .NET Remoting to construct transparent proxies at runtime, you might find what you need in https://github.com/dotnet/corefx/tree/master/src/System.Reflection.DispatchProxy . It does not do cross-machine communication like .NET Remoting did, but it does provide the equivalent of transparent proxies.

Regarding WCF interfacing -- what specifically are you asking about?  I can answer some questions here, but the best place to engage with the rest of the WCF team would be to open specific issues at https://github.com/dotnet/wcf/issues

**Comment by roncain** [comment]
I am going to close this issue now, because it is a question that has been answered. Feel free to reopen if new questions arise.
