### ISSUE TITLE
EventLog access is not supported on this platform (Linux)

### ISSUE THREAD

**Issue by kamaruddin-desai** [dotnet/corefx#40925]
# EventLog access is not supported on this platform (Linux)

System.PlatformNotSupportedException: EventLog access is not supported on this platform. An exception is thrown on linux platform(CentOS 7) when trying to read the remote windows host events. The same piece of code is working fine on Windows platform.

# General
`string queryString = "*[System/Level=2]"; // XPATH Query
                                                      //SecureString pw = new SecureString();//GetSecurePassword();
                                                      //SecureString theSecureString = new NetworkCredential("", "password").SecurePassword;
            string password = "PASSWORD";
            SecureString sec_pass = new SecureString();
            Array.ForEach(password.ToArray(), sec_pass.AppendChar);

            EventLogSession session = new EventLogSession(
             "IP_ADDRESS",                // Remote Computer hostname
			 "DOMAIN",                 // Domain
			 "USERNAME",                // Username
			 sec_pass,
             SessionAuthentication.Default);
            // Query the Application log on the remote computer.
            EventLogQuery query = new EventLogQuery("Application", PathType.LogName, queryString);
            query.Session = session;

            try
            {
                EventLogReader logReader = new EventLogReader(query);

                // Display event info
                //DisplayEventAndLogInformation(logReader);

                EventRecord eventInstance = logReader.ReadEvent();
                Console.WriteLine(eventInstance.ToXml());
            }
            catch (EventLogException e)
            {
                Console.WriteLine("Could not query the remote computer! " + e.Message);
                return;
            }`
.csproj file for the same
\<Project Sdk="Microsoft.NET.Sdk"\>

  \<PropertyGroup\>
    \<OutputType\>Exe\</OutputType\>
    \<TargetFramework\>netcoreapp3.0\</TargetFramework\>
  \</PropertyGroup\>
  \<ItemGroup\>
    \<PackageReference Include="System.Diagnostics.EventLog" Version="4.6.0-preview9.19421.4" /\>
  \</ItemGroup\>

\</Project\>

**Comment by ViktorHofer** [comment]
EventLog isn't supported on non Windows_NT OS's. https://github.com/dotnet/corefx/blob/8c041484dda3059bd4adebebda939a15ee4a087d/src/System.Diagnostics.EventLog/src/System.Diagnostics.EventLog.csproj#L5

**Comment by kamaruddin-desai** [comment]
1. .NET Core v3.0.0-preview9 or later releases are capable of reading Windows event logs of the remote Windows host is it possible now or in upcoming releases of .NET Core?

2. Its capability will be restricted to reading the Linux Syslogs?

Just looking for the answers of above two questions? 😃

**Comment by danmosemsft** [comment]
For 1 - @Anipik can best answer.

For 2 - there is no current plan. I recommend you open an issue to track the request (proposing how the API should look and behave).

**Comment by Anipik** [comment]
> .NET Core v3.0.0-preview9 or later releases are capable of reading Windows event logs of the remote Windows host is it possible now or in upcoming releases of .NET Core?

Yes you can read logs from the remote machine in all the available version of System.Diagnostics.EventLog package

**Comment by danmosemsft** [comment]
This seems resolved. Please reopen if not.

**Comment by kamaruddin-desai** [comment]
Running the above-mentioned code snippet on **CentOS Linux release 7.6.1810 (Core)**
#https://github.com/dotnet/corefx/issues/40925#issue-490731052

Getting the below exception:

> Unhandled Exception: System.PlatformNotSupportedException: EventLog access is not supported on this platform.
   at System.Diagnostics.EventLog.GetEventLogs(String machineName)
   at MySample.Main() in /opt/DotNetCore/TestFolder/Program.cs:line 11

**Comment by Anipik** [comment]
@kamaruddin-desai  you can only use this library on windows machine which means that both the host and remote need to be windows machine

**Comment by kamaruddin-desai** [comment]
@Anipik Do we have support for reading remote windows events from the Linux host in future?

**Comment by kamaruddin-desai** [comment]
@Anipik Do you have any update?

**Comment by Anipik** [comment]
Sry i missed the message

>  Do we have support for reading remote windows events from the Linux host in future?

Currently there is no plan to do that. You can create an issue for that to get the discussion going.
