### ISSUE TITLE
HttpClient adding a header changes the case of the header name

### ISSUE THREAD

**Issue by dreymers-goformz** [dotnet/corefx#40995]
For example: httpClient.DefaultRequestHeaders.Add("X-Request-Id", "test");
This adds a header with the last character upper-cased: X-Request-ID

Cause: When adding a header, the code is searching for any HttpKnownHeaderNames case-insensitive;  if it finds one, it then replaces the value with the one from HttpKnownHeaderNames.

This is problematic for anyone already using one of these headers with a different case (and is high-risk for creating hidden bugs).

**Comment by davidsh** [comment]
@geoffkizer

**Comment by geoffkizer** [comment]
This is a known issue with how we deal with "known headers". 

Is this actually causing issues in practice?

**Comment by scalablecory** [comment]
HTTP headers are case-insensitive, so in theory this should not matter if a server is well behaved.

**Comment by dreymers-goformz** [comment]
@geoffkizer - not an issue for me (since I caught it); couldn't speak for anyone else, though.
@scalablecory - agreed, in theory.

Just seems wrong to change the key's value in the Add method.

**Comment by geoffkizer** [comment]
If you use HTTP2 you'll actually get "x-request-id" on the wire, because all header names in HTTP2 are in lower case.

**Comment by scalablecory** [comment]
@dreymers-goformz do you have any examples where this is causing problems in real code or making `HttpClient` harder to learn?

It's not an unreasonable concern (especially for X-* headers) but I'd like to see some convincing scenarios where doing this for known headers is harmful.

**Comment by dreymers-goformz** [comment]
@scalablecory I don't recall exactly - I think it was something like 
`var value = Request.Headers.FirstOrDefault(x => x.Key == "X-Request-Id");`

Easy workarounds include headers.TryGetValue(...) and headers["X-Request-Id"].
Hard to say how likely this is to crop up unexpectedly in developers' app code, I guess.

**Comment by karelz** [comment]
Triage: This is happening only for known headers. We don't believe it will break anyone in practice who is using best practices. Closing.
