### ISSUE TITLE
Update to test on Alpine 3.10 for 2.x

### ISSUE THREAD

**Issue by mthalman** [dotnet/corefx#41038]
Now that Alpine 3.10 has been released, testing should be updated to include that version. Also, be sure to check that the CI build is using 3.10 as well.  This is specific to 2.x servicing.

Related to https://github.com/dotnet/corefx/issues/38027

**Comment by ViktorHofer** [comment]
@danmosemsft do we want that for 2.x?

**Comment by ViktorHofer** [comment]
cc @terrajobst

**Comment by MichaelSimons** [comment]
FWIW, the OS support policy for 2.x states Alpine 3.7 + is supported.

https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md
https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2-supported-os.md

**Comment by mthalman** [comment]
@ViktorHofer, @danmosemsft, @terrajobst - Can we get some traction on this?  This is blocking the release of Docker images on this version.

**Comment by terrajobst** [comment]
@richlander would be better suited to respond.

**Comment by ViktorHofer** [comment]
Rich, please let us know if we should do this for the release branches:

> It is both adding the RID and validating via a new CI leg.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by richlander** [comment]
Yes. We will need to do this several more times with 2.1. Expect us to ask at least every 6 months to adopt a new Alpine.

**Comment by richlander** [comment]
Do we need a new RID? Thought we just used `linux-musl`.

**Comment by MichaelSimons** [comment]
In the past we have always had version specific rids.  It appears that the rid changes were already made sometime ago - https://github.com/dotnet/corefx/commit/ad0128498892bfbb36f0ac4310e80d80e59d0bca

**Comment by richlander** [comment]
I see ... so we have both the general ones and the specific ones? I didn't know that. I always use the general one (like `linux-musl-x64`), but I can see the role for the specific ones.

**Comment by MichaelSimons** [comment]
See https://github.com/dotnet/dotnet-docker/issues/1374 for the importance of why Alpine 3.10 support is critical.

**Comment by richlander** [comment]
Sure, but that doesn't explain why the RID is important. I'm not pushing back on the RID, just saying that the RID choice and supporting 3.10 don't relate directly.

**Comment by ViktorHofer** [comment]
Done.
