### ISSUE TITLE
Update to test on Alpine 3.10

### ISSUE THREAD

**Issue by mthalman** [dotnet/corefx#41037]
Now that Alpine 3.10 has been released, testing should be updated to include that version. Also, be sure to check that the CI build is using 3.10 as well.

Related to https://github.com/dotnet/corefx/issues/37646

**Comment by ViktorHofer** [comment]
I don't see a docker image for 3.10: https://mcrflowprodcentralus.cdn.mscr.io/mcrprod/dotnet-buildtools/prereqs?P1=1568236084&P2=1&P3=1&P4=RRnugnNCyLF2%2B2WuY6EZl4g5ZnNMyPVkDdt0GLiZDRI%3D&se=2019-09-11T21%3A08%3A04Z&sig=IDwLCHNzM1gcT9UJDleOHZV%2BjHO4k3CiyRLO1%2Bzrd98%3D&sp=r&sr=b&sv=2015-02-21

**Comment by mthalman** [comment]
> I don't see a docker image for 3.10: https://mcrflowprodcentralus.cdn.mscr.io/mcrprod/dotnet-buildtools/prereqs?P1=1568236084&P2=1&P3=1&P4=RRnugnNCyLF2%2B2WuY6EZl4g5ZnNMyPVkDdt0GLiZDRI%3D&se=2019-09-11T21%3A08%3A04Z&sig=IDwLCHNzM1gcT9UJDleOHZV%2BjHO4k3CiyRLO1%2Bzrd98%3D&sp=r&sr=b&sv=2015-02-21

I've logged an issue for @MattGal to get those created: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/182

**Comment by MattGal** [comment]
@ViktorHofer : please try out mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.10-helix-3043688-20190918214010

**Comment by ViktorHofer** [comment]
Thanks will do this.

**Comment by mthalman** [comment]
@ViktorHofer - Can we make this happen for 2.x as well: https://github.com/dotnet/corefx/issues/41038
