### ISSUE TITLE
AsyncLocal<T> value is changed unexpectedly to the old value when EntityFrameworkCore and SqlClient DiagnosticsListener used

### ISSUE THREAD

**Issue by stukselbax** [dotnet/corefx#41049]
We are using Jaeger to track app performance and recently encountered in a problem tracking requests:

```
Span has already been finished; will not be reported again. Operation: sqlClient SELECT Trace Id: 3378cd4b82959a046319f2eb1904476b Span Id: 851107e900911a68
```

It occurred when we updated library opentracing-contrib/csharp-netcore from 0.5.0 to 0.6.0 where support for SqlClient DiagnosticsListener was added.

There is [an issue](https://github.com/opentracing-contrib/csharp-netcore/issues/44) in those library, but as it reproduced without it in a simple console app, it's not their fault, I guess. There is [similar issue](https://github.com/dotnet/corefx/issues/32695) in this repo also. 

DiagnosticsListener is used to inspect specific commands. In order to report span in correct order, jaeger library uses [AsyncLocalScopeManager](https://github.com/opentracing/opentracing-csharp/blob/master/src/OpenTracing/Util/AsyncLocalScopeManager.cs#L34), which uses AsyncLocal<T> to track active scope. When specific command goes to DiagnosticsListener, this active scope in AsyncLocal<T> is changed.  But apparently it can be restored to previous state. Commands reported in the following order:

```
.. "Microsoft.EntityFrameworkCore.Database.Command.CommandExecuting" -> Active now EFCore
....  "System.Data.SqlClient.WriteCommandBefore" -> Active now SqlClient. Remember EFCore as previously active.
....  "System.Data.SqlClient.WriteCommandAfter"-> Dispose active, which is SqlClient. Restore active to EFCore.
.. "Microsoft.EntityFrameworkCore.Database.Command.CommandExecuted" -> Dispose active, which should be EFCore. But it is - SqlClient! We get disposed SqlClient Scope twice. It's a problem.
```

When the last command is reported, AsyncLocal<T> sees that "System.Data.SqlClient.WriteCommandBefore" command is active now and gets called Dispose() second time, but "Microsoft.EntityFrameworkCore.Database.Command.CommandExecuting" is expected.

I have created simple repro. In order to see the bug:

```
git clone https://github.com/stukselbax/AsyncLocalProblem
cd AsyncLocalProblem
devenv .
```

_SQLEXPRESS is required_. Build solution, select AsyncLocalProblem as startup project, F5. Inspect red message 

```
System.Data.SqlClient.WriteCommandBefore was already disposed!!
```

Set SpanHasAlreadyFinished as startup project , F5. Inspect warning message

```
warn: Jaeger.Tracer[0]
      Span has already been finished; will not be reported again. Operation: sqlClient SELECT Trace Id: af69374e58cb1fe1 Span Id: ab16fb209a1877a4
```

You can play with AsyncLocal<T>, for example, in order to get change notification.

Because I don't know where problem is (SqlClient, AsyncLocal, EntityFrameworkCore, ...) I report issue here.

**Comment by stukselbax** [comment]
Strange context changed is _probably_ happens in [ExecuteReaderAsync()](https://github.com/dotnet/corefx/blob/b49a8a9be1d53cd9e50cb68fd8540be25c65d433/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlCommand.cs#L1722) method. It is a bit confusing because there used `TaskCompletionSource`, `Task<SqlDataReader>.Factory.FromAsync()` and `.ContinueWith()`...

**Comment by tarekgh** [comment]
Maybe the logic is not fully right in your app? Here is what I think is happening but I don't know why:

-  Microsoft.EntityFrameworkCore.Internal.RelationalLoggerExtensions.CommandExecuting get executed and the asyncLocal status will be s1 = (name: CommandExecuting, prevStatus: null)
- Next System.Data.SqlClient.SqlClientDiagnosticListenerExtensions.WriteCommandBefore executed and the asyncLocal status will be s2 = (name: WriteCommandBefore, prevStatus: s1)
- After that there will be 2 async operations spawned from the current context which means we'll have 2 executing tasks sharing the same status s2.
    - The first eventually will call System.Data.SqlClient.SqlClientDiagnosticListenerExtensions.WriteCommandAfte and will dispose WriteCommandBefore of s2.
    - The second eventually will call Microsoft.EntityFrameworkCore.Internal.RelationalLoggerExtensions.CommandExecuted and will dispose WriteCommandBefore of s2 too.
I am not sure if it is expected to spawn 2 async operations to handle the requests. But, maybe your app need to be tolerant that if the object is disposed, just ignore the disposal but keep setting the asynclocal status as you currently do.

**Comment by benaadams** [comment]
The Disposable is being stored directly in the AsyncLocal; changing it with
```csharp
manager.Status = prevStatus;
```
Only changes the current ExecutionContext's copy; ExecutionContexts stored elsewhere will still retain the previous value (ExecutionContexts aren't linked and are immutable).

If you add an indirection to the disposable you should get the behaviour you want.

e.g. in your sample if you store a `DisposableHolder` instead
```csharp
internal sealed class DiagnosticManager : IObserver<DiagnosticListener>
{
    private class DisposableHolder
    {
        public Disposable Disposable { get; set; }
    }

    private AsyncLocal<DisposableHolder> _status;

    public DiagnosticManager()
    {
        _status = new AsyncLocal<DisposableHolder>(OnStatusChanged);
        DiagnosticListener.AllListeners.Subscribe(this);
    }

    private void OnStatusChanged(AsyncLocalValueChangedArgs<DisposableHolder> args)
    {
        WriteLine(
                "AsyncLocal<T> changed {0} from: {1} to {2}",
                args.ThreadContextChanged ? "by context" : "by setter",
                args.PreviousValue?.Disposable?.ToString() ?? "<null>",
                args.CurrentValue?.Disposable?.ToString() ?? "<null>");
        if (args.CurrentValue?.Disposable?.ToString().EndsWith("WriteCommandBefore") == true == true && args.CurrentValue?.Disposable?.disposed == true)
        {
            WriteLine(Environment.StackTrace);
        }
    }

    public Disposable Status
    {
        get => _status.Value?.Disposable;
        set
        {
            var status = _status;
            if (status.Value == null)
            {
                status.Value = new DisposableHolder();
            }

            status.Value.Disposable = value;
        }
    }
```
Then you'll get the output you expect
```
Hello World!
AsyncLocal<T> changed by setter from: <null> to <null>
Listener: Microsoft.EntityFrameworkCore. Microsoft.EntityFrameworkCore.Database.Command.CommandExecuting
Listener: SqlClientDiagnosticListener. System.Data.SqlClient.WriteCommandBefore
AsyncLocal<T> changed by context from: System.Data.SqlClient.WriteCommandBefore to <null>
AsyncLocal<T> changed by context from: <null> to System.Data.SqlClient.WriteCommandBefore
AsyncLocal<T> changed by context from: System.Data.SqlClient.WriteCommandBefore to <null>
AsyncLocal<T> changed by context from: <null> to System.Data.SqlClient.WriteCommandBefore
AsyncLocal<T> changed by context from: <null> to System.Data.SqlClient.WriteCommandBefore
Going to dispose System.Data.SqlClient.WriteCommandBefore of SqlClientDiagnosticListener
Change manager status to previous: Microsoft.EntityFrameworkCore.Database.Command.CommandExecuting
AsyncLocal<T> changed by context from: Microsoft.EntityFrameworkCore.Database.Command.CommandExecuting to <null>
AsyncLocal<T> changed by context from: Microsoft.EntityFrameworkCore.Database.Command.CommandExecuting to <null>
AsyncLocal<T> changed by context from: <null> to Microsoft.EntityFrameworkCore.Database.Command.CommandExecuting
AsyncLocal<T> changed by context from: Microsoft.EntityFrameworkCore.Database.Command.CommandExecuting to <null>
AsyncLocal<T> changed by context from: <null> to Microsoft.EntityFrameworkCore.Database.Command.CommandExecuting
Going to dispose Microsoft.EntityFrameworkCore.Database.Command.CommandExecuting of Microsoft.EntityFrameworkCore
Change manager status to previous:
AsyncLocal<T> changed by context from: <null> to <null>
Press enter

AsyncLocal<T> changed by context from: <null> to <null>
```

**Comment by stukselbax** [comment]
Probably @tarekgh assumption about the "2 async operations" is the issue. From the API client point of view, there should be only one async operation:

```c#
try
{
    var manager = new DiagnosticManager();
    var dbContext = services.GetRequiredService<JaegerDbContext>();

    var dates = await dbContext.Dates.ToListAsync();
}
catch (Exception e)
{
    WriteLine("Error ocured: {0}", e);
}
finally
{
    WriteLine("Press enter");
    ReadLine();
}
```

I'll definitely try to apply @benaadams proposed solution to the source detected the problem (jaeger tracing), but why there is more than one `ExecutionContext` - that's the question. I thought that single `ExecutionContext` should flow with async operations.

Also having more objects than probably required could hit some performance issue?

**Comment by benaadams** [comment]
>  but why there is more than one `ExecutionContext` - that's the question. I thought that single `ExecutionContext` should flow with async operations.

`ExecutionContext`s are immutable; if you change the value of an `AsyncLocal<T>`; it creates a new `ExecutionContext` and replaces the current one with that. That new `ExecutionContext` will be used by everything that completes sync and captured in any async method that suspends and resumes later after that point (mimicking the sync behaviour).

However; when completion of the current async method causes a previous async method to resume, that async method will have captured an earlier `ExecutionContext` with an earlier `AsyncLocal` value prior to the change. So while `AsyncLocal`s flow; they also unwind their values like a stack as the async methods stack unwinds. Until you get back to the async method/await before you first set the AsyncLocal, when it will again be unset.

If you want the `AsyncLocal` to be mutable and reflect changes made at all points both upstack and downstack and behave more like an "AsyncGlobal" then you want the first assignment to be a class type; and then to change a value on the class rather than change the AsyncLocal itself.

Another way of thinking of `AsyncLocal`s is as hidden parameter passed to the methods; when you change the parameter the next methods called will receive the changed value but when the stack unwinds it will go back to the previous value e.g.
```csharp
static void Main()
{
    AsyncMethod1(asyncValue: 0);
}

void AsyncMethod1(int asyncValue)
{
    Console.WriteLine($"{nameof(AsyncMethod1)} : before asyncValue = {asyncValue}");
    AsyncMethod2(asyncValue);
    Console.WriteLine($"{nameof(AsyncMethod1)} : after  asyncValue = {asyncValue}");
}
void AsyncMethod2(int asyncValue)
{
    Console.WriteLine($"{nameof(AsyncMethod2)} : before asyncValue = {asyncValue}");
    asyncValue = 2; // Change value
    AsyncMethod3(asyncValue);
    Console.WriteLine($"{nameof(AsyncMethod2)} : after  asyncValue = {asyncValue}");
}
void AsyncMethod3(int asyncValue)
{
    Console.WriteLine($"{nameof(AsyncMethod3)} : before asyncValue = {asyncValue}");
    AsyncMethod4(asyncValue);
    Console.WriteLine($"{nameof(AsyncMethod3)} : after  asyncValue = {asyncValue}");
}
void AsyncMethod4(int asyncValue)
{
    Console.WriteLine($"{nameof(AsyncMethod4)} : before asyncValue = {asyncValue}");
    asyncValue = 4; // Change value
    AsyncMethod5(asyncValue);
    Console.WriteLine($"{nameof(AsyncMethod4)} : after  asyncValue = {asyncValue}");
}
void AsyncMethod5(int asyncValue)
{
    Console.WriteLine($"{nameof(AsyncMethod5)} : before asyncValue = {asyncValue}");
    asyncValue = 5; // Change value
    Console.WriteLine($"{nameof(AsyncMethod5)} : after  asyncValue = {asyncValue}");
}
```
Would produce the output like
```
AsyncMethod1 : before asyncValue = 0
AsyncMethod2 : before asyncValue = 0
AsyncMethod3 : before asyncValue = 2
AsyncMethod4 : before asyncValue = 2
AsyncMethod5 : before asyncValue = 4
AsyncMethod5 : after  asyncValue = 5
AsyncMethod4 : after  asyncValue = 4
AsyncMethod3 : after  asyncValue = 2
AsyncMethod2 : after  asyncValue = 2
AsyncMethod1 : after  asyncValue = 0
```

**Comment by benaadams** [comment]
The above sync code mimics what happens in the async version with AsyncLocal
```csharp
using System.Threading;
using System.Threading.Tasks;
using static System.Console;

class Program
{
    static AsyncLocal<int> asyncValue = new AsyncLocal<int>();

    static async Task Main()
    {
        asyncValue.Value = 0;
        await AsyncMethod1();
    }

    static async Task AsyncMethod1()
    {
        WriteLine($"{nameof(AsyncMethod1)} : before asyncValue = {asyncValue.Value}");
        await AsyncMethod2();
        WriteLine($"{nameof(AsyncMethod1)} : after  asyncValue = {asyncValue.Value}");
    }
    static async Task AsyncMethod2()
    {
        WriteLine($"{nameof(AsyncMethod2)} : before asyncValue = {asyncValue.Value}");
        asyncValue.Value = 2; // Change value
        await AsyncMethod3();
        WriteLine($"{nameof(AsyncMethod2)} : after  asyncValue = {asyncValue.Value}");
    }
    static async Task AsyncMethod3()
    {
        WriteLine($"{nameof(AsyncMethod3)} : before asyncValue = {asyncValue.Value}");
        await AsyncMethod4();
        WriteLine($"{nameof(AsyncMethod3)} : after  asyncValue = {asyncValue.Value}");
    }
    static async Task AsyncMethod4()
    {
        WriteLine($"{nameof(AsyncMethod4)} : before asyncValue = {asyncValue.Value}");
        asyncValue.Value = 4; // Change value
        await AsyncMethod5();
        WriteLine($"{nameof(AsyncMethod4)} : after  asyncValue = {asyncValue.Value}");
    }
    static async Task AsyncMethod5()
    {
        WriteLine($"{nameof(AsyncMethod5)} : before asyncValue = {asyncValue.Value}");
        asyncValue.Value = 5; // Change value
        WriteLine($"{nameof(AsyncMethod5)} : after  asyncValue = {asyncValue.Value}");
    }
}
```
Also outputs
```
AsyncMethod1 : before asyncValue = 0
AsyncMethod2 : before asyncValue = 0
AsyncMethod3 : before asyncValue = 2
AsyncMethod4 : before asyncValue = 2
AsyncMethod5 : before asyncValue = 4
AsyncMethod5 : after  asyncValue = 5
AsyncMethod4 : after  asyncValue = 4
AsyncMethod3 : after  asyncValue = 2
AsyncMethod2 : after  asyncValue = 2
AsyncMethod1 : after  asyncValue = 0
```

HTH

**Comment by ericsampson** [comment]
I wonder if it's worth enhancing the documentation to capture some of the subtleties that Ben called out? It's a bummer when such useful tidbits are buried in GitHub issues.

**Comment by tarekgh** [comment]
@ericsampson

> I wonder if it's worth enhancing the documentation to capture some of the subtleties that Ben called out? It's a bummer when such useful tidbits are buried in GitHub issues.

Feel free to create a new doc issue on https://github.com/dotnet/docs. let me know if want me help with that.

I am going to close this issue as it looks everything is clear now. Let me know if you have any more questions. thanks to @benaadams for his help in this issue too.
