### ISSUE TITLE
Build.sh in WSL 1 Fails with 'csc.dll exited with code 139'

### ISSUE THREAD

**Issue by ManickaP** [dotnet/corefx#41050]
Env: WSL 1, Ubuntu 18.04, with prerequisites listed in [here](https://github.com/dotnet/corefx/blob/c4c1985531cc1f25c805bbc4801b85c98e0dfee0/Documentation/building/unix-instructions.md).
Build fails with:
```
/home/manicka/.nuget/packages/microsoft.net.compilers.toolset/3.3.0-beta2-19367-02/tasks/netcoreapp2.1/Microsoft.CSharp.Core.targets(58,5): 
  error MSB6006: "csc.dll" exited with code 139.
  [/mnt/d/UbuntuShare/corefx/src/System.Reflection.MetadataLoadContext/src/System.Reflection.MetadataLoadContext.csproj]
```

It's always System.Reflection.MetadataLoadContext library.
The build works in WSL 2. However that requires Insider Preview of Win.

@davidsh Encountered the same problem.
Might be related to [Roslyn#23846](https://github.com/dotnet/roslyn/issues/23846).

To reproduce run:
```
./build.sh
```
in WSL.

**Comment by ViktorHofer** [comment]
@ManickaP could you please update the dotnet version specified in global.json (both entries) to a preview-9 or rc-1 build and try it again? Trying to investigate if an old CoreLib assembly is the cause here.

**Comment by ManickaP** [comment]
@ViktorHofer with rc-1 I got a different error in a different lib:
```
/home/manicka/dotnet/sdk/3.0.100-rc1-014190/Microsoft.CSharp.CurrentVersion.targets(100,9):
  error MSB3041: Unable to create a manifest resource name for "System/Xml/XmlCharType.bin".
  Could not find a part of the path '/home/manicka/corefx/src/System.Private.Xml/src/System/Xml/System/Xml/XmlCharType.cs'.
  [/home/manicka/corefx/src/System.Private.Xml/src/System.Private.Xml.csproj]
```

I don't know why, but the path contains `System/Xml` twice. If Iook into `System.Private.Xml.csproj`, there it is OK: `<Compile Include="System\Xml\XmlCharType.cs" />` and the file exists.

**Comment by ViktorHofer** [comment]
Can you please try that scenario again now on master?

**Comment by ManickaP** [comment]
@ViktorHofer I works! Thanks!
Tried on WSL1 Ubuntu 18.04 and OpenSUSE Leap 15.1, both succeeded.
