### ISSUE TITLE
Icon entry selection from file/stream does not consider color depth

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#41068]
Originally reported in https://github.com/dotnet/winforms/issues/1825. #41048 fixes this, the change will need to be ported into 3.0.x.

**Comment by ericstj** [comment]
@JeremyKuhne can you prep a PR against `release/3.0` when you get a chance and mark it no-merge?  That way we are ready to go when 3.0 unlocks for servicing changes.

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/pull/41202

**Comment by danmosemsft** [comment]
@anipik when merging changes into 3.0 it's good to check that Github closed the issue .

**Comment by Anipik** [comment]
okay, its strange that Github didnt close this issue. The issue contains "Fixes ##"
