### ISSUE TITLE
Add shims for the rest of the libc native calls

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefx#4106]
It looks like we still have a handful of libc calls from managed code:

https://github.com/dotnet/corefx/blob/c02d33b18398199f6acc17d375dab154e9a1df66/src/Common/src/Interop/Linux/libc/Interop.inotify.cs#L11-L15
https://github.com/dotnet/corefx/blob/c02d33b18398199f6acc17d375dab154e9a1df66/src/Common/src/Interop/Unix/libc/Interop.getdomainname.cs#L13

We should shim these calls.

Also, when we have the shims in place, we should remove the libc string from Interop.Libraries.

**Comment by jasonwilliams200OK** [comment]
There is also https://github.com/dotnet/corefx/blob/c02d33b/src/Common/src/Interop/Unix/libc/Interop.ioctl.cs#L13.
