### ISSUE TITLE
Add validation that project.json's don't overspecify dependencies

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#4108]
It would be really nice if we validated that no project.json specifies dependencies that aren't used.

See https://github.com/dotnet/corefx/pull/4107#issuecomment-150646389

**Comment by Maxwe11** [comment]
It would be nice to have this check on DNX (or who consumes project.json?) level.

**Comment by ericstj** [comment]
I played around with this a bit and its not so simple.  There are things that are used by the compiler but never make it to the final assembly (eg: Conditional attribute) and there are cases where multiple builds share the same reference set (debug/release, cross-compile by OS while sharing the same framework in the project.json).  With these characteristics it would mean we'd need some sort of file-tracker that spans multiple builds of a project, potentially on multiple machines,  to implement this correctly.  I don't think that's something particularly useful for us to invest in right now.
