### ISSUE TITLE
Reading HttpResponseMessage.Content.Headers.ContentLength allocates ContentLength memory even with HEAD request

### ISSUE THREAD

**Issue by nettolicious** [dotnet/corefx#41091]
This is dotnet core 2.2, using the default IHttpClientFactory. Making a HEAD request to check size of  a file to download. Accessing the Content.Headers.ContentLength property of the HttpResponseMessage causes memory to be allocated equal to the value of ContentLength.
![MemoryAllocation](https://user-images.githubusercontent.com/37562625/64879079-59736180-d612-11e9-82a1-56142915f0f0.jpg)

**Comment by stephentoub** [comment]
Can you try .NET Core 3.0?  This sounds like the same issue fixed in https://github.com/dotnet/corefx/pull/3812.

**Comment by davidsh** [comment]
@stephentoub I don't think #3812 is the right issue/PR to link against.

**Comment by stephentoub** [comment]
(Fixed.  Was missing a 9 at the end.)

**Comment by davidsh** [comment]
Closing this since it appears the issue is fixed already in .NET Core 3.0.
