### ISSUE TITLE
C#如何使用Microsoft.AspNetCore.SignalR.Client连接Hub

### ISSUE THREAD

**Issue by XuVeeKan** [dotnet/corefx#41115]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS1061	'“HubConnectionBuilder”未包含“WithUrl”的定义，并且找不到可接受第一个“HubConnectionBuilder”类型参数的可访问扩展方法“WithUrl”(是否缺少 using 指令或程序集引用?)	WindowsFormsApp1	C:\Users\XWJ\source\repos\WindowsFormsApp1\WindowsFormsApp1\Form1.cs	23	活动的

**Comment by danmosemsft** [comment]
Error CS1061 'HubConnectionBuilder' does not contain a definition of "WithUrl" and can't find an accessible extension method "WithUrl" that accepts the first "HubConnectionBuilder" type parameter (are you missing a using directive or an assembly reference?)

**Comment by XuVeeKan** [comment]
> Error CS1061 'HubConnectionBuilder' does not contain a definition of "WithUrl" and can't find an accessible extension method "WithUrl" that accepts the first "HubConnectionBuilder" type parameter (are you missing a using directive or an assembly reference?)

Hei guy, do you know how to solve it?

**Comment by XuVeeKan** [comment]
Resolve=>>> https://github.com/aspnet/AspNetCore/issues/9827
