### ISSUE TITLE
HttpContext.Session.GetString Not Working on Linux

### ISSUE THREAD

**Issue by ZackTech** [dotnet/corefx#41116]
I have an Asp.net Core application version 2 (I have yet to upgrade it to version 2.2and beyond)

The following code generates a Captcha image:
```
public FileStreamResult GetCaptchaImage()
        {
            int width = 200;
            int height = 60;

            string captchaCode = Captcha.GenerateCaptchaCode();
            
            var result = Captcha.GenerateCaptchaImage(width, height, captchaCode);

            HttpContext.Session.SetString("CaptchaCode", result.CaptchaCode);

            Stream s = new MemoryStream(result.CaptchaByteData);

            return new FileStreamResult(s, "image/png");
        }
```
When I test the Captcha code is correct with code like this:
```
if (viewModel.CaptchaCode != HttpContext.Session.GetString("CaptchaCode"))
{
}
```
It works fine on my local windows PC and on Azure but not on a Ubuntu VPS.
On the Ubuntu VPS it always comes back as null.

I build the project on a Windows PC using the following commands:
```
dotnet restore -r ubuntu.16.04-x64
dotnet build -r ubuntu.16.04-x64
dotnet publish -f netcoreapp2.0 -c Release -r ubuntu.16.04-x64
```
And then  publish to Linux.

Any ideas how I can fix this?

**Comment by davidsh** [comment]
@Tratcher This looks like an ASP.NET issue

**Comment by Tratcher** [comment]
This issue was moved to aspnet/AspNetCore#14012
