### ISSUE TITLE
API proposal: Char.Empty

### ISSUE THREAD

**Issue by Symbai** [dotnet/corefx#41127]
This probably gets denied like all my suggestions but however I would like to propose Char.Empty which does nothing else than String.Empty by returning a char instead of a string.

```
namespace System
{
    public struct Char : IComparable, IConvertible, IComparable<Char>, IEquatable<Char>
    {
        public static readonly Char Empty;
    }
}
```

Most common scenario would be:
```
void DoStuff(string s) {
	s = s.Replace('a', char.Empty);
}
```

There will be reasons against this API and I could ask why the same reasons wouldn't apply to string.Empty which got approved but anyways. Another scenario most devs would have asked "Why doesn't something like this exist?" and here is my question to the official .NET team, can this be added?

**Comment by EgorBo** [comment]
`String.Empty` is basically an **empty** array of chars (Length=0), what value `char.Empty` is supposed to have ? `\0` ? What are the use-cases for such field?

**Comment by benaadams** [comment]
Probably a Remove(char) api would be better for your scenario?
```csharp
public partial class String
{
    public string Remove(char charToRemove);
}
```

**Comment by GrabYourPitchforks** [comment]
I'm curious about the scenario you've identified.

Is there a reason why `string.Replace("a", string.Empty)` is insufficient for the common scenario you've identified? Do you expect that the character to be removed is not constant, so you need a `string.Remove(char)` API instead?

**Comment by Symbai** [comment]
Ask @Wraith2 who has down voted, thanks.
