### ISSUE TITLE
Where is the system.printing namespace and how do we access it in VS2019?

### ISSUE THREAD

**Issue by intermension** [dotnet/corefx#41133]
This link would suggest System.Printing is available.

https://docs.microsoft.com/en-us/dotnet/api/system.printing?view=netcore-3.0

I have .NET Core 3.0 Preview 9 installed with VS 2019 but i cant seem to reference this Assembly / Namespace. I cant find anything in Nuget nor anything about printing assemblies in general. The api seems well documented on MS Docs where to find is a mystery.

**Comment by mv10-work** [comment]
Based on the last comment in the docs, it looks like you need to install the [Windows Compatibility Package](https://docs.microsoft.com/en-us/dotnet/core/porting/windows-compat-pack) to pick up WPF support.

> This namespace is part of the enhanced printing services provided with Windows Presentation Foundation. Managed code developers using Windows Forms must use the APIs in the System.Drawing.Printing namespace.

**Comment by danmosemsft** [comment]
This is in WPF rather than the compatibility pack, I think. (The compatibility pack is built out of this repo: System.Printing is built out of dotnet/wpf.) @ericstj is there a way to get System.Printing without creating a WPF app? I don't see a package for it.

**Comment by intermension** [comment]
Thanks you're right. I can access System.Printing from a WPF library project and then reference that from Winforms app, seems kinda convoluted but at least its progress.

**Comment by ericstj** [comment]
System.Printing actually builds on top of WPF and is dependent upon types within it.  It's not available independently.  

> from a WPF library project and then reference that from Winforms app

You don't need the seperate project, you can set `<UseWPF>true</UseWPF>` from the winforms application.  /cc @vatsan-madhavan 
Only requirement is that that Project uses the `Microsoft.NET.Sdk.WindowsDesktop` SDK as winforms and WPF do, and sets `<UseWPF>true</UseWPF>`

**Comment by intermension** [comment]
@ericstj Even better. Thanks.
