### ISSUE TITLE
NullReference Exception in SqlParameterCollection.Add() when using a Typed DataSet and EF 6.3 in the same .NET Core 3.0 Project (Preview 8) 

### ISSUE THREAD

**Issue by HSchwichtenberg** [dotnet/corefx#41141]
**Repro steps**

1. Create a dotnet core 3.0 project (Preview 8)
2. Add PackageReferences 
    PackageReference Include="System.Data.DataSetExtensions" Version="4.6.0-preview3.19128.7" />
    PackageReference Include="System.Data.SqlClient" Version="4.7.0-preview8.19405.3" />
2. Add a typed dataset
3. Run Code, e.g.
     var d = new MyDataSet(); 
    var t = new MyTableTableAdapter();
     t.Connection.ConnectionString = @"...";
     t.Fill(d.MyTable);
4. Now add another reference
    PackageReference Include="EntityFramework" Version="6.3.0-preview8-19405-04" />
5. The above code will fail now at  this._adapter.DeleteCommand.Parameters.Add():
System.NullReferenceException: 'Object reference not set to an instance of an object.'

[TypedDataSetDemo.zip](https://github.com/dotnet/SqlClient/files/3566592/TypedDataSetDemo.zip)

**Expected result**

I should be able to use Typed DataSet and EF 6.3 in the same project (for migrating old projects using Typed DataSets)

**Actual result**

System.NullReferenceException: 'Object reference not set to an instance of an object.' in the generated code.
![2019-09-02_17-28-46](https://user-images.githubusercontent.com/3673169/64124424-49a08580-cda7-11e9-802d-bf42c5ac4165.png)

**Note**

The same error happens if you have the Typed DataSet and the EF 6.3 in different projects that are referenced by the same start project.

**Comment by danmosemsft** [comment]
> It should be in 3.1 which is an LTS release due out shortly after 3.0. It's still unmerged though, not sure what's going on with that.

Note that 3.1 is not branching off master. It branches off release/3.0. (Master ships in 5.0)

**Comment by HSchwichtenberg** [comment]
But "manually modify the generated code to use a shorter constructor." means that we have to redo these manual changes every time the Typed DataSet is regenerated. Consequently, projects with Typed DataSets cannot be migrated to .NET Core 3.0 👎

**Comment by cheenamalhotra** [comment]
Closing issue as the fix has been merged for 3.1 release branch.
