### ISSUE TITLE
BUG: Json.NET converter for IPAddress does not work in .NET Core 3.0 specifically

### ISSUE THREAD

**Issue by zezba9000** [dotnet/corefx#41144]
Using Json.NET converters within the .NET Core 3.0 runtime fails. However in .NET Core 2.2 or .NET Framework 4.8 it works fine.

It seems like some "Type" is not coming through correctly.

.NET Core versions are both using the same .NET Standard 2.0 Json.NET lib.
This makes me think its a .NET runtime issue of some kind or another but I can't be sure.

**Download this example project that you can reproduce the issue with.**
https://vrstudios-my.sharepoint.com/:u:/p/andrew_witte/ETIlqlXTlu1Moiz2Q2MYsAUBIje5Z96Zij7xGPL3wAO6wA?e=sz1oDH

Win10 x64 1904
OS Build: 18362.356
Visual Studio 2019 16.3.0 Preview 3.0
.NET Core 3.0.100-preview9-014004
.NET Core 2.2.104

Here are all my available .NET Core versions installed.
```
1.0.0-preview1-002702
1.0.0-preview2-003121
1.0.0-preview2-003131
1.0.1
1.0.2
1.0.3
1.0.4
1.1.0
2.0.2
2.0.3
2.1.100
2.1.101
2.1.102
2.1.103
2.1.104
2.1.2
2.1.200
2.1.201
2.1.202
2.1.4
2.1.400
2.1.401
2.1.402
2.1.403
2.1.500
2.1.502
2.1.503
2.1.504
2.1.505
2.1.507
2.1.508
2.1.509
2.1.602
2.1.604
2.1.700
2.1.700-preview-009618
2.1.701
2.1.800
2.1.800-preview-009677
2.1.800-preview-009696
2.1.801
2.1.802
2.2.101
2.2.103
2.2.104
3.0.100-preview9-014004
```

VS info
```
Microsoft Visual Studio Community 2019 Preview
Version 16.3.0 Preview 3.0
VisualStudio.16.Preview/16.3.0-pre.3.0+29230.61
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA947
Microsoft Visual C++ 2019

Application Insights Tools for Visual Studio Package   9.1.00815.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.3.277.18560
ASP.NET and Web Tools 2019

ASP.NET Core Blazor Language Services   16.0.19227.01

ASP.NET Web Frameworks and Tools 2019   16.3.277.18560
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.3.277.18560
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.3.277.18560
Azure Functions and Web Jobs Tools

C# Tools   3.3.1-beta3-19430-03+fa8e2c9b566e4471a3509fc63d7baca0a2a6d30b
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

ConvertToDevExtremeCommand Extension   1.0
ConvertToDevExtremeCommand Visual Studio Extension Detailed Info

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20816.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.0.83+gbc8a4b23ec
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61908.27190
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.10821.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.3.1-beta3-19430-03+fa8e2c9b566e4471a3509fc63d7baca0a2a6d30b
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.3.0-beta.19421.2+9f51ac5290b1dfc5dc434841d61b2ac31997ea8c
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers
```

**Comment by jkotas** [comment]
The repro fails with: 

```
Hello .NET Core 3.0!
Unhandled exception. Newtonsoft.Json.JsonSerializationException: Error getting value from 'ScopeId' on 'System.Net.IPAddress+ReadOnlyIPAddress'.
 ---> System.Net.Sockets.SocketException (10045): The attempted operation is not supported for the type of object referenced.
   at System.Net.IPAddress.get_ScopeId()
   at lambda_method(Closure , Object )
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
```

**Comment by jkotas** [comment]
The problem is caused by the following code in the repro:

```
			public override bool CanConvert(Type objectType)
			{
				return objectType == typeof(IPAddress);
			}
```

This no longer works after a fix for https://github.com/dotnet/corefx/issues/33373. The same breakage is mentioned there already: https://github.com/dotnet/corefx/issues/33373#issuecomment-478693168

**Comment by davidsh** [comment]
@JamesNK @stephentoub

**Comment by jkotas** [comment]
@zezba9000 This is a latent bug in the implementation of your IPAddress converter that was exposed by .NET Core 3. The implementation of `CanConvert` should allow for IPAddress subclasses like this:

```
public override bool CanConvert(Type objectType)
{
    return objectType.IsSubclassOf(typeof(IPAddress));
}
```

**Comment by zezba9000** [comment]
@jkotas So you're saying a framework change was made that passes a reference to a private class that implements IPAddress? In turn making it so simply setting something to IPAddress.Any is now not directly a IPAddress and just a implementation of one which IPAddress as its base-class?

In short this is a framework change and not a breaking RuntimeType change correct?
This seems like a pretty bad choice. #1 its very confusing and #2 is slower.

**Comment by stephentoub** [comment]
> So you're saying a framework change was made that passes a reference to a private class that implements IPAddress?

That derives from IPAddress, yes.  e.g. IPAddress.Any now returns a ReadOnlyIPAddress, which derives from IPAddress.

> In short this is a framework change and not a breaking RuntimeType change correct?

Correct.

> its very confusing

How so?  If an API returns "object", is it confusing that it might be something that derives from System.Object rather than being "System.Object" concretely?

> is slower

What specifically is slower?  The Type comparison check you're doing in your code?  Can you share the real-world scenario where this has a measurably negative impact?

The change was made because otherwise you might access IPAddress.Loopback or IPAddress.Any or any of those other static properties, and the IPAddress you got back may not have actually represented the address you expected, because it could have been mutated.

**Comment by JamesNK** [comment]
If the Json.NET serializer can't serialize this type anymore then the least impact change on your code would be to write a `JsonConverter` for it, and add the converter to `JsonSerializerSettings`.

**Comment by zezba9000** [comment]
@stephentoub Lets just say it has the potential of being verbosely annoying because correctly me if I'm wrong but .NET for some reason has no equivalent for the 'is' keyword in the aspect of a Type class helper methods that is like doing: 
> objectType == typeof(IPAddress) || objectType.IsSubclassOf(typeof(IPAddress));

There really should be a method called something like: objectType.IsTypeOrSubclassOf(typeof(IPAddress));

@JamesNK It works. Just have to add missing extension method for IPAddress type comparison.

**Comment by poke** [comment]
You could also use [`Type.IsAssignableFrom`](https://docs.microsoft.com/en-us/dotnet/api/system.type.isassignablefrom?view=netframework-4.8) to avoid checking against the exact type and subtypes.

**Comment by stephentoub** [comment]
> potential of being verbosely annoying

Fair enough.  Though I'm not sure anyone's ever accused reflection of being concise :wink:

**Comment by zezba9000** [comment]
@poke "Type.IsAssignableFrom" doesn't work because the type is not assignable directly from a IPAddress type but rather a ReadOnlyIPAddress. Its not equivalent to the 'is' keyword in short.

@stephentoub Well it should be for common stuff like this, which it is for the most part. I mean I'm sure there is an internal runtime method that handles the 'is' keyword situation that could be invoke for a "IsClassOrSubclassOf" implementation detail method in the runtime.

I have far more use for something like "IsClassOrSubclassOf" vs "IsSubclassOf". Just my two cents in this area.

**Comment by stephentoub** [comment]
> "Type.IsAssignableFrom" doesn't work because the type is not assignable directly from a IPAddress type but rather a ReadOnlyIPAddress

What do you mean by this?  `typeof(IPAddress).IsAssignableFrom(objectType)` doesn't give you the right answer?

**Comment by zezba9000** [comment]
Ooops lol ya just had the logic flipped in my head from doing it the other way around so many times. Silly me.
Still like my suggestion as it avoids the need to flip code around but whatever.

**Comment by poke** [comment]
> Still like my suggestion as it avoids the need to flip code around but whatever.

Yeah, `IsAssignableFrom` requiring backwards logic is a common issue with it.

You can [show your support here](https://github.com/dotnet/corefx/issues/40666) if you would rather want something that makes a bit more sense :)

**Comment by zezba9000** [comment]
Awesome!
