### ISSUE TITLE
System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_MaxResponseHeadersLength_Test.SetAfterUse_Throws failed in the release 3.0 branch

### ISSUE THREAD

**Issue by Anipik** [dotnet/corefx#41148]
```
      Condition(s) not met: "IsUap"
    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_MaxResponseHeadersLength_Test.SetAfterUse_Throws [FAIL]
      System.Threading.Tasks.TaskCanceledException : A task was canceled.
      Stack Trace:
        /_/src/System.Net.Http/src/System/Net/Http/HttpClient.cs(553,0): at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
        /_/src/System.Net.Http/src/System/Net/Http/HttpClient.cs(294,0): at System.Net.Http.HttpClient.FinishGetStreamAsync(Task`1 getTask)
        /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.MaxResponseHeadersLength.cs(54,0): at System.Net.Http.Functional.Tests.HttpClientHandler_MaxResponseHeadersLength_Test.SetAfterUse_Throws()
        --- End of stack trace from previous location where exception was thrown ---
  Finished:    System.Net.Http.Functional.Tests
```

https://dev.azure.com/dnceng/public/_build/results?buildId=353186&view=ms.vss-test-web.build-test-results-tab

**Comment by eiriktsarpalis** [comment]
Looking at the [test history](https://dev.azure.com/dnceng/public/_build/results?buildId=353186&view=ms.vss-test-web.build-test-results-tab&runId=10640820&resultId=174807&paneView=history), it looks like isolated failures. Perhaps just a temporary issue with the remote server?

**Comment by eiriktsarpalis** [comment]
I'd be inclined to close this. @ViktorHofer thoughts?

**Comment by ViktorHofer** [comment]
I'm surprised that the test doesn't use a loopbackserver given that it's testing a very simple scenario. @eiriktsarpalis I think the right fix would be to change this and other siblings tests to use loopback.

**Comment by eiriktsarpalis** [comment]
> I think the right fix would be to change this and other siblings tests to use loopback.

Is that something we should be pursuing for all outerloop tests depending on remote servers?

**Comment by davidsh** [comment]
>Is that something we should be pursuing for all outerloop tests depending on remote servers?

Yes we should try to move more tests to loopback if possible. Some tests will be more difficult to do that as they will require the loopback server to be enhanced further. 

The history of this is that long ago we didn't have the loopback server. Everything talked to a remote server. Over time we introduced the loopback server and made it more capable and more stable. So, where it makes sense, we should move tests to loopback server.

**Comment by eiriktsarpalis** [comment]
My only concern is that loopback is a bespoke implementation, with emphasis on introspecting server-side protocol state. I do think there is value in running at least some of the functional tests against baseline production servers, which of course needn't be hosted remotely.
