### ISSUE TITLE
HTTP2: GRPC greeter service failing with 'Invalid Http/2 connection preface' error.

### ISSUE THREAD

**Issue by sabyabr** [dotnet/corefx#41159]
I’ve downloaded the attached sample code and trying to run the Greeter service and client on my machine. But it fails with 'Invalid Http/2 connection preface' error. 
Also attaching the email thread with grpc team regarding this issue. 
[GreeterServiceError.zip](https://github.com/dotnet/corefx/files/3623228/GreeterServiceError.zip)
[sample.zip](https://github.com/dotnet/corefx/files/3623226/sample.zip)
[HttpClientTrace.zip](https://github.com/dotnet/corefx/files/3623215/HttpClientTrace.zip)

**Comment by JamesNK** [comment]
I have looked into this a bit in discussion offline.

Background:
* gRPC is setup on ASP.NET Core on port 5000 without TLS
* .NET Core gRPC client is using `http://` address and has set `System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport` to true
* The server is rejecting the client's attempt to start connection

The code in sample.zip works on my computer.

**Comment by eiriktsarpalis** [comment]
Code in sample.zip works on my machine as well. I'm using dotnet sdk version `3.0.100-rc2-014234` on Windows. Running both server and client apps without any arguments.

**Comment by sabyabr** [comment]
It works after updating it to rc1 version
