### ISSUE TITLE
I can't use "dotnet ef database update --environment RELEASE"

### ISSUE THREAD

**Issue by codeoflin** [dotnet/corefx#41179]
![image](https://user-images.githubusercontent.com/45932283/65171600-d9f9ee00-da68-11e9-9e23-f4a9f19a9955.png)

![image](https://user-images.githubusercontent.com/45932283/65171699-188fa880-da69-11e9-911a-f7d0922d2fb7.png)

what should I replace?

**Comment by khellang** [comment]
Shouldn't you `set ASPNETCORE_ENVIRONMENT=Production`? 🤔

**Comment by codeoflin** [comment]
> Shouldn't you [`set ASPNETCORE_ENVIRONMENT=Production`](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#aspnet-core-environment)? What makes you think there's an environment switch? 🤔

https://www.learnentityframeworkcore.com/migrations/commands/cli-commands

I just want use it when I update the database

**Comment by danmosemsft** [comment]
@codeoflin could you move this to https://github.com/aspnet/EntityFrameworkCore ? You'll probably get your answer there.

**Comment by codeoflin** [comment]
> @codeoflin could you move this to https://github.com/aspnet/EntityFrameworkCore ? You'll probably get your answer there.

ok thanks
