### ISSUE TITLE
Compile to x86 can not run at x64 platform

### ISSUE THREAD

**Issue by chenyj796** [dotnet/corefx#41199]
I have a library file which is writen by C language and compiled to x86.

In my C# project, I need call the C library by PInvoke, so I set the PlatformTarget property to x86 in .csproj file.

``` xml
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>netcoreapp3.0;net461</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <Prefer32Bit>true</Prefer32Bit>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
```
When I run the app at windows 7 x64:
1) for net461, it works fine
2) for netcoreapp3.0, it throws a System.BadImageFormatException.

**Comment by lindexi** [comment]
@chenyj796 I do not good at English, so I replay Chinese.

首先 Prefer32Bit 是给 AnyCpu  平台使用的，设置了这个项的时候，将会在 AnyCpu 下编译IL声明为x86但是这个代码将会在 x64 的系统下，能额外使用更多的内存

那么 AnyCPU(Prefer 32-bit) 和 x86 有什么区别？实际上在 ARM 系统，只能使用 AnyCPU(Prefer 32-bit) 运行 32 位程序，如果选择 x86 就无法运行。

为什么需要在 64 位的设备使用 AnyCPU(Prefer 32-bit)，因为如果存在一些库只能在 32位程序运行，那么就需要运行的程序是 32 位，所以需要使用这个方法。

所以你选择的 x86 和 Prefer32Bit 是冲突的，详细请看我博客 [WPF 编译为 AnyCPU 和 x86 有什么区别](https://blog.lindexi.com/post/wpf-%E7%BC%96%E8%AF%91%E4%B8%BA-anycpu-%E5%92%8C-x86-%E6%9C%89%E4%BB%80%E4%B9%88%E5%8C%BA%E5%88%AB )

另外，我回复不了为什么 461 能用，但是 core 用不了。能否请你调试一下两个版本调用的 C 库是否相同文件，以及通过 Environment.Is64BitProcess 判断当前运行程序

**Comment by chenyj796** [comment]
多谢德熙。

其实把Prefer32Bit去掉，效果也是一样的。
由于我这个C库只有32位版本的，但是要支持运行在x64机器上，所以必须编译为x86平台。

现在的问题是编译为x86时，双击.exe文件直接没有反应，通过dotnet 运行看到它报 System.BadImageFormatException异常。
这甚至和有没有调用C库都没有关系了，只所以提到调用C库的问题，是因为它是我这里的基本需求。

概括一下，我要怎样在x64平台上运行x86版本的.netcore程序？如果解决不了，那只能继续使用.NetFramework了。

**Comment by lindexi** [comment]
其实你尝试一个控制台的 dotnet core 项目，编译为x86 是可以在 x64 运行的，这部分没有什么问题

提示 System.BadImageFormatException 我只能提供两个方法进行调试，很抱歉没有直接的方法

## VisualStudio 单步调试

因为不能确定是运行到哪一句代码提示这个异常，如果在提示异常的时候，可以通过调用堆栈看到对应附近的代码有加载某个 dll 库之类的，那么就可以确定是某个库加载的问题。例如查看他对应的版本是 x86 还是 x64 等

如果不能确定是哪一句代码或调用哪个库，那么就尝试按下 F11 进入单步调试，看执行到哪句代码就提示这个异常。特别小心静态构造函数等，这部分的代码碰到了就执行

## ProcessMonitor

如果发现程序里面的引用没有找到绝对路径，那么可以通过 [Process Monitor ) 看到应用程序访问的每个文件，在出现异常的时候，最后读取的文件是哪一个，可以用来找到是加载的库的路径不对的问题，和是加载哪个库的问题

**Comment by chenyj796** [comment]
我直接用最简单的代码，还是一样的报错。
1. dotnet new wpf
2. 修改.csproj文件，添加<PlatformTarget>x86</PlatformTarget>

控制台程序也是一样的问题。

**Comment by lindexi** [comment]
@chenyj796 Good. 尝试升级到RC1的 dotnet core 试试

**Comment by chenyj796** [comment]
我就是用的RC1版本的……

**Comment by huoyaoyuan** [comment]
`Prefer32Bit`是仅在.NET Framework上可用的，Core上没有这个概念。
我在Core上使用`PlatformTarget`也遇到了些问题；根据收集到的信息来看，Core上似乎应该使用`RuntimeIdentifiers`也就是rid。试试只写`win-x86`，不写`win-x64`，然后publish再运行？

**Comment by chenyj796** [comment]
@huoyaoyuan 试了你的方法，还是不行。
感觉32位的.netcore程序就是不能在64位机器上运行，这就比较尴尬了。

**Comment by huoyaoyuan** [comment]
用3.0控制台做了一下实验，加上`<PlatformTarget>x86</PlatformTarget>`后，启动的进程就是32位的了，从`Environment.Is64BitProcess`可以看到。
终极解决方案我怀疑需要装一份32位的sdk。

**Comment by lindexi** [comment]
> 感觉32位的.netcore程序就是不能在64位机器上运行

@chenyj796 放心 .NET Core 的 x86 是可以在 x64 运行的，不然我的好多项目都gg的，不知你能否尝试在另一台设备上编译运行

> 终极解决方案我怀疑需要装一份32位的sdk

如果使用 --self-contained 发布，将会带所有环境，也许试试命令行发布一下

      dotnet publish -r win-x86 -c release --self-contained 

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish

**Comment by chenyj796** [comment]
@lindexi 
使用 --self-contained 发布的方式，可以运行了。
多谢！

**Comment by lindexi** [comment]
@chenyj796 厉害

**Comment by chenyj796** [comment]
经过验证，在.NET Core 3.0正式版，这个问题已经不存在了
