### ISSUE TITLE
HTTP2: Support receiving dynamic headers

### ISSUE THREAD

**Issue by scalablecory** [dotnet/corefx#41208]
We disabled receipt of dynamic headers for 3.0 by setting max dynamic table size = 0.

A number of bugs relating to this were fixed in 5.0, and we should consider re-enabling the feature.

**Comment by Tratcher** [comment]
Yes please. The other side did the hard work to decide which headers to inturn, we might as well take advantage of it.

Kestrel already has receiving working and we're syncing that code with you.

**Comment by scalablecory** [comment]
This would be easy to do and has some clear benefit, so I'm inclined to want it for 5.0. I'm currently reviewing which HTTP servers support sending dynamic headers.

Kestrel having support for sending these would be a key motivator I think. https://github.com/aspnet/AspNetCore/issues/4715

**Comment by Tratcher** [comment]
This should happen regardless of kestrel's support for sending dynamic headers (that's harder, but we'll try it too). There are plenty of other implementations that already do this, including some gRPC servers @JamesNK can point you at.
