### ISSUE TITLE
Decimal GetHashCode() not always equal for different number of tailing 0

### ISSUE THREAD

**Issue by miloszu** [dotnet/corefx#41204]
> var a = 1000.250000000000000000m;
> var b = 1000.25000000000000000000m;
> a == b
true
> a.GetHashCode() == b.GetHashCode()
false
> a.GetHashCode()
-1083130353
> b.GetHashCode()
1083130368

Reproduced on .NET Core 2.2 and Windows 10

**Comment by scalablecory** [comment]
@miloszu have you tested if this behavior is still in .NET Core 3.0?

**Comment by huoyaoyuan** [comment]
The hash code of 1000.25 is always 231097 now. Tested on 3.0 rc1 win-x64.

**Comment by Gnbrkm41** [comment]
Happens on 2.1.801 and 2.2.300, also on .NET Framework 4.8. I can't reproduce it on 3.0.100.

**Comment by scalablecory** [comment]
I also can't reproduce on 3.0, so appears to be fixed. Please upgrade and feel free to re-open ticket if you find it is still not working for you in 3.0.
