### ISSUE TITLE
Marshaling wchar_t on Linux uses wrong size

### ISSUE THREAD

**Issue by lainy** [dotnet/corefx#41206]
# General

Tested on .NET Core 3.0.100-preview9-014004 on Arch Linux.

The following code should print out `4` on this system, but instead outputs `2`.
Printing `sizeof(wchar_t)` from a C program gives `4`.

Discovered when trying to interop with a C library that has a struct with `wchar_t[5]` inside.

```cs
using System;
using System.Runtime.InteropServices;

namespace dotnet_core_wchar_t_size
{
    class Program
    {
        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
        internal struct test
        {
            public char c;
        }

        static void Main(string[] args)
        {
            Console.WriteLine(Marshal.SizeOf(typeof(test)));
        }
    }
}
```

**Comment by tannergooding** [comment]
`CharSet.Unicode` is documented to be

| Name | Value | Description |
| ----- | ----- | ---- |
| Unicode | 3 | Marshal strings as Unicode 2-byte character strings.

**Comment by jkoritzinsky** [comment]
More specifically, `CharSet.Unicode` is documented to map to a native `char16_t` on Unix-like platforms: https://docs.microsoft.com/en-us/dotnet/standard/native-interop/charset
