### ISSUE TITLE
HTTP2: Support sending frame padding

### ISSUE THREAD

**Issue by scalablecory** [dotnet/corefx#41215]
Consider adding support for frame padding in HTTP2. [The RFC](https://httpwg.org/specs/rfc7540.html#padding) is vague on the benefits of this as TLS itself also supports padding.

**Comment by Tratcher** [comment]
Not worth it. As you said, TLS already covers this. Http/3 has dropped this feature.

**Comment by geoffkizer** [comment]
Not clear what you mean here...

We support receiving padded frames, though we could probably use some more tests here. See #39162, #39163

I don't think there's any benefit from sending padded frames.

**Comment by scalablecory** [comment]
> Not clear what you mean here...

Yep, I meant sending it :). I don't see any benefit either.

**Comment by scalablecory** [comment]
Closing; we do not currently see a benefit in supporting this.
