### ISSUE TITLE
HTTP2: Proxy over HTTP2

### ISSUE THREAD

**Issue by scalablecory** [dotnet/corefx#41213]
Consider adding support for [CONNECT over HTTP2](https://httpwg.org/specs/rfc7540.html#CONNECT). The ability to multiplex streams could save precious latency.

Not sure if any proxy servers support HTTP2 yet.

**Comment by Tratcher** [comment]
Would need a list of proxies and servers that support this before considering this. It's not clear who would use this vs a HTTP/1.1 proxy.

**Comment by geoffkizer** [comment]
I don't think there's any real value here. If you want to do CONNECT (as a proxy or otherwise), you are almost certainly going to try this using HTTP/1.1.

**Comment by scalablecory** [comment]
Closing; will revisit the idea if server support starts happening.
