### ISSUE TITLE
Incorrect P/Invoke signature for CryptoNative_EvpDigestUpdate

### ISSUE THREAD

**Issue by filipnavara** [dotnet/corefx#41219]
The `count` argument is defined as `int` in managed code and as `size_t` in native code:
https://github.com/dotnet/corefx/blob/6074cfc995d7968fcdbc7f707acff0c6284c6ae9/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.EVP.cs#L22-L23
https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/Native/Unix/System.Security.Cryptography.Native/pal_evp.h#L43

**Comment by bartonjs** [comment]
Yep, the shim function should be int32_t.
