### ISSUE TITLE
HTTP2: Support stream priority/dependency

### ISSUE THREAD

**Issue by scalablecory** [dotnet/corefx#41212]
Consider implementing [stream prioritization and dependencies](https://httpwg.org/specs/rfc7540.html#StreamPriority). This could be useful in bandwidth/latency-sensitive scenarios.

**Comment by scalablecory** [comment]
Seems complicated, and we would want to consider if priority inversion is possible.

**Comment by Tratcher** [comment]
Browsers use this to prioritize HTML and CSS over images. Not clear what the HttpClient scenarios would be.

What kind of API would you use to specify these?

Kestrel doesn't support these.

**Comment by scalablecory** [comment]
Due to the apparent complexity of implementing this, I would like to see some concrete use cases before moving forward on it. Desktop and server use is probably limited, but mobile might see some use.

I can imagine this being used for code that is latency-sensitive. Maybe a website with a real-time SignalR feed that is also processing other requests. Some games also have a concept of high-priority updates VS low-priority updates.

**Comment by geoffkizer** [comment]
From what I can tell, HTTP2 prioritization is basically dead. No one actually does this.

We can revisit in HTTP3, but let's see how people actually use this.

**Comment by scalablecory** [comment]
Closing until a need is found.
