### ISSUE TITLE
Find a way to trim out ExcludeFromCodeCoverage attribute from published trimmed app

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#41234]
Several assemblies that end up getting pulled into lots of apps (e.g. System.Linq) use `[ExcludeFromCodeCoverage]`.  There's generally no need for that in a published trimmed app, but it's sticking around and bringing with it System.Diagnostics.Tooling.dll.  While fairly small (5K) it's still another .dll that would be nice to remove.  This could be achieved in various ways, including:
- Stop using [ExcludeFromCodeCoverage] in these assemblies, which would impact all code coverage results
- `#if DEBUG` around such usage, which would then only impact code coverage release results
- Teach the linker used during app publishing to always strip this attribute

cc: @sbomer, @noahfalk

**Comment by ViktorHofer** [comment]
> Teach the linker used during app publishing to always strip this attribute

If we do that how do we guarantee that we are testing what we are shipping?

> #if DEBUG around such usage, which would then only impact code coverage release results

We can't measure code coverage on Release anyway as the System.Private.CoreLib assembly in that configuration isn't instrument-able.

**Comment by stephentoub** [comment]
> If we do that how do we guarantee that we are testing what we are shipping?

This is a general issue faced by doing aggressive trimming as part of app publishing.  Is there a specific concern to this attribute?

**Comment by stephentoub** [comment]
The assembly also includes GeneratedCodeAttribute, which is much more common. Not worth effort.
