### ISSUE TITLE
System.Net.Http.HttpRequestException

### ISSUE THREAD

**Issue by Alan-Lun** [dotnet/corefx#41247]
version
.Net core 2.2 API

Docker File : FROM microsoft/dotnet:2.2-aspnetcore-runtime

dotnet publish xxxx_API.csproj -c Release

AWS ECS

Error:System.Net.Http.HttpRequestException: Too many open files in system —> System.Net.Sockets.SocketException: Too many open files in system

想請問這是為什麼

**Comment by scalablecory** [comment]
This indicates that you've exhausted the open file descriptor limit on Linux. You can verify this by running in a console:

```
cat /proc/sys/fs/file-nr
```

**Comment by wfurt** [comment]
This can also be #37044. Fix for leaving OS handles opened was not back-ported to 2.x. 
If in doubts, you can use 3.0 to verify. 
And of course you need to increase handle if you have many parallel requests.

**Comment by cadaov** [comment]
Does #38499 apply only to 3.0 or also to 2.x ? if not, is it going to be available to 2.x ?

**Comment by wfurt** [comment]
so far nobody confirmed #38499 fixes issues observed in #37044. Also proper dispose should be sufficient to avoid the problem. We would need some more evidence and impact to get permission for back-port. with 3.0 out, the bar is even higher now.

**Comment by karelz** [comment]
Please try .NET Core 3.0.
If it happens again, please reopen this issue with a (minimal) repro. There is not enough information here now for us to make it actionable.
