### ISSUE TITLE
System.Management.MangementScope Exception with Dotnet Core 3 Release

### ISSUE THREAD

**Issue by MakisupaVT** [dotnet/corefx#41264]
I'm attempting to upgrade a project to Dotnet Core 3 which uses System.Management for WMI calls. When connecting to my MangementScope:

`var scope = new ManagementScope(@"\\computer\root\CIMV2", new ConnectionOptions());`

Program dies with the exception:

> An unhandled exception has occurred while executing the request.
System.Runtime.InteropServices.MarshalDirectiveException: Cannot marshal 'parameter #3': Cannot marshal a string by-value with the [Out] attribute.
   at System.StubHelpers.StubHelpers.ThrowInteropParamException(Int32 resID, Int32 paramIdx)
   at System.Management.ManagementPath.GetWbemPath(IWbemPath wbemPath)
   at System.Management.ManagementScope.set_prvpath(ManagementPath value)
   at System.Management.ManagementScope..ctor(ManagementPath path, ConnectionOptions options)

I've seen the same Marshal exception on recent Core 3 preview posts that were supposedly fixed, but this issue seems to persist.

**Comment by danmosemsft** [comment]
Can you please make sure you have the latest version of System.Management. Perhaps your project has locked it to an older version.

https://github.com/dotnet/corefx/issues/38093

**Comment by MakisupaVT** [comment]
My bad here. Although I updated all the NuGet packages in my solution, and I thought I got them all, I missed updating System.Management in my Management package and it was at version 4.5.0. Upgrading to 4.6.0 solved my issue.
