### ISSUE TITLE
Verify code covererage for deserialize read methods where `reader.BytesConsumed != utf8Json.Length`

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#41266]
`System.Text.Json.JsonSerializer.ParseCore()` and  `System.Text.Json.JsonSerializer.Deserialize()` both have a check like this:
```cs
                if (reader.BytesConsumed != actualByteCount)
                {
                    ThrowHelper.ThrowJsonException_DeserializeDataRemaining(
                        actualByteCount, actualByteCount - reader.BytesConsumed);
                }
```

However that is not getting hit by any tests. In fact, it is likely that it is now dead code because the reader verifies all data is read when `isFinalBlock==true` is passed into the reader (as is the case for the two methods above).

We need to verify that the `if` statement is still valid or whether it should be removed.

**Comment by ahsonkhan** [comment]
I believe this got fixed by https://github.com/dotnet/corefx/pull/41414.

@steveharter - please re-open if you think this issue is still relevant.
