### ISSUE TITLE
HttpResponseMessage.TrailingHeaders blocks some headers

### ISSUE THREAD

**Issue by Tratcher** [dotnet/corefx#41262]
HttpResponseMessage.TrailingHeaders re-used the HttpResponseHeaders collection that blocks some headers it thinks belong in HttpContentHeaders instead. With trailers you don't have that flexibility and this may block customer scenarios.

A header like `Content-MD5` is restricted.
- The header is received and stored in the collection.
- `response.TrailingHeaders.ToString()` does show the value.
- `response.TrailingHeaders.GetValues("Content-MD5");` throws:
```
System.InvalidOperationException: Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.
at System.Net.Http.Headers.HttpHeaders.GetHeaderDescriptor(String name)
at System.Net.Http.Headers.HttpHeaders.GetValues(String name)
at ResponseTrailers.Program.Main(String[] args) in C:\temp\ResponseTrailers\Program.cs:line 30
```
- `response.TrailingHeaders.TryGetValues("Content-MD5", out var values)` returns false.
- Enumeration is the only way to get the value:
```
foreach (var header in response.TrailingHeaders)
{
    Console.WriteLine($"Trailer {header.Key}: {string.Join(", ", header.Value)}");
}
```

I reviewed the content headers that would be blocked and didn’t find any that people are likely to use, but devs are unpredictable. 

Proposed change: HttpResponseMessage owns and creates the trailers collection. It could be changed to create it using a new internal constructor that specified different behavior. No public API changes would be required. Note there are plenty of headers that are prohibited in trailers that could be filtered by these rules instead of the content headers.
https://github.com/dotnet/corefx/blob/9161098ade5075a8c126b2d7eb98abbeadff2961/src/System.Net.Http/src/System/Net/Http/HttpResponseMessage.cs#L123-L126
https://github.com/dotnet/corefx/blob/9161098ade5075a8c126b2d7eb98abbeadff2961/src/System.Net.Http/src/System/Net/Http/Headers/HttpResponseHeaders.cs#L144-L145

The secondary issue is that HttpResponseHeaders has many properties that would not apply to trailers. That is a long term API wart, but not blocking.

.NET Core 3.0 based repro. Run Kestrel directly, not IIS Express.
[ResponseTrailers.zip](https://github.com/dotnet/corefx/files/3643612/ResponseTrailers.zip)

**Comment by scalablecory** [comment]
Ah yes, we had a long discussion on this one. I think the suggestion to have an internal flag in `HttpResponseHeaders` is the best way to go at this point.

**Comment by alnikola** [comment]
After some discussion, it was decided that a proper fix must do a name-based filtering of headers allowed to be in the message trail as it defined by [4.1.2.  Chunked Trailer Part](https://tools.ietf.org/html/rfc7230#section-4.1.2). A simple header type based validation (e.g. all content headers are allowed) is **not enough**. However, it's believed a reaction to a detected invalid header should be different depending on how the header is being added to HttpResponseHeaders collection:
1. If a header has been received over the wire, it must be logged and then ignored
2. If the Add method is called explicitly, an exception must be thrown

**Comment by Tratcher** [comment]
> 1. If a header has been received over the wire, it must be logged and then ignored

This check is already happening in the transport before calling the collection, but logging could be added.
