### ISSUE TITLE
Skip codepath Environment.OSVersion.Platform on publish trimmed with linker

### ISSUE THREAD

**Issue by jormenjanssen** [dotnet/corefx#41284]
The publish trimmed feature in .NET core 3 is not trimming code on specific code paths (see example below) which are  unable to get hit when published with specific runtime-rid e.g. windows and readytorun

Another approach would be #if but this has several disadvantages in Visual Studio etc.

```csharp
public static IServiceCollection AddSocketCAN(this IServiceCollection serviceCollection)
        {
            if (Environment.OSVersion.Platform != PlatformID.Unix)
                return serviceCollection;

            serviceCollection
                .AddSingleton<ICanFactory, SocketCanFactory>()
                .AddSingleton<ISafetyRequestProvider, UnixDiagramSafetyRequestProvider>();
            
            return serviceCollection;
        }

**Comment by jkotas** [comment]
https://github.com/mono/linker/issues/607#issuecomment-499218393 is a similar suggestion, but it is a good idea to have this specific one tracked.

**Comment by jormenjanssen** [comment]
@jkotas close this one and duplicate in mono linker repo or keep this open and create new in mono linker?

**Comment by jkotas** [comment]
Close this one and create a new one in mono/linker repo
