### ISSUE TITLE
NuGet: System.Collections.Concurrent targeting .NetCore,Version=5? preventing the library reference.

### ISSUE THREAD

**Issue by dynamiclynk** [dotnet/corefx#41298]
NuGet: System.Collections.Concurrent targeting .NetCore,Version=5? preventing the library reference.

![image](https://user-images.githubusercontent.com/621804/65554412-160cd300-deef-11e9-9c21-f70caf93e852.png)

**Comment by safern** [comment]
Hello @dynamiclynk, could you please provide a more detailed information of the issue?

How are you trying to reference it? What kind of project are you trying to consume it from, what framework are you targeting in such project, etc?

**Comment by dynamiclynk** [comment]
It's targeting a version of .NetCore that doesn't exist.

**Comment by safern** [comment]
You shouldn't need to reference that package at all, `System.Collections.Concurrent` is part of the shared framework in .NETCore 2.2 already, actually we no longer build that package as that library you get it for free if you target .NET Core in your project. 

You should be able to remove the package reference and just add a using statement in the file you want to use it. i.e:

```cs
using System.Collections.Concurrent;
```

and then use whatever type from that library that you need.

**Comment by dynamiclynk** [comment]
You're right. When did Ctrl+. to add the reference it wanted to install the nuget instead of adding the using statement. Oh well user error :) thanks for the quick response.

**Comment by danmosemsft** [comment]
@safern This package was last published in 2016, and it used the TFM "netcore50" which the UI here is translating to ".NET Core 5.0". Is that the correct TFM for ".NET Core 5.0" (unreleased product) or does it represent the old Project N target or something else?

**Comment by dynamiclynk** [comment]
> @safern This package was last published in 2016, and it used the TFM "netcore50" which the UI here is translating to ".NET Core 5.0". Is that the correct TFM for ".NET Core 5.0" (unreleased product) or does it represent the old Project N target or something else?

Ah yeah DNXCore50 right..doh I forgot about that?

**Comment by safern** [comment]
Closing per discussion above.

> translating to ".NET Core 5.0"

.NETCore,Version=5 is uwp10 which is confusing since now, the next version of .NET will be `.NET 5.0`
