### ISSUE TITLE
DrawString render issue with .Net Core 3.0

### ISSUE THREAD

**Issue by endofunk** [dotnet/corefx#41292]
### **Related to:** https://www.nuget.org/packages/System.Drawing.Common/ (4.6.0)

With everything else being equal; simply upgrading a project from .Net Core 2.2 to .Net Core 3.0 results in a new `DrawString` render issue; downgrading from 3.0 to 2.2 resolves this? (see attached screen shots)

**Note:** 
I tried a number of different font families including `GenericSansSerif`, `GenericSerif` and `GenericMonospace` -- all result in the same render issue. It works as expected on .Net Core 2.2 but not on .Net Core 3.0

**.Dot Net 2.2** 
![dotnetcore22](https://user-images.githubusercontent.com/22223342/65538811-70665d80-df08-11e9-9a4e-90301233206f.png)

**.Dot Net 3.0** 
![dotnetcore30](https://user-images.githubusercontent.com/22223342/65538813-72302100-df08-11e9-9732-5a98379a9a43.png)

**Comment by krwq** [comment]
cc: @safern

**Comment by ipoetry** [comment]
I have the same problems ,but with chinese character.

**Comment by krwq** [comment]
Btw I remember this worked for me couple months back but required installing libgdiplus. Can you try installing it if you haven't yet?

If that still doesn't help can you run `strace <yourapp> | grep -i ENOENT` if it tries to search for some file it cannot find?

**Comment by safern** [comment]
> Btw I remember this worked for me couple months back but required installing libgdiplus. Can you try installing it if you haven't yet?

I believe if it worked before using 2.2 they might have libgdiplus installed, but good to get confirmation.

**Comment by safern** [comment]
Also a small repro example if possible.

**Comment by endofunk** [comment]
As mentioned previously it works as expected prior to .Net Core 3.0

### The following code snippet is sufficient to recreate the issue:
`
var bitmap = new System.Drawing.Bitmap(100, 100);
var graphics = System.Drawing.Graphics.FromImage(bitmap);
var font = new System.Drawing.Font(System.Drawing.FontFamily.GenericSansSerif, 12);
graphics.DrawString("Cancel 123", font, System.Drawing.Brushes.Black, 10, 10);
bitmap.Save("bugexample.png");
`

As mentioned previously to one need only change the `Target Framework` from `.NET Core 2.2` to `.NET Core 3.0` to recreate the render issue.
![Screen Shot 2019-09-27 at 23 41 51](https://user-images.githubusercontent.com/22223342/65803954-9302ab80-e180-11e9-9447-9856400fdd42.png)
![Screen Shot 2019-09-27 at 23 42 55](https://user-images.githubusercontent.com/22223342/65803961-972ec900-e180-11e9-9f35-cb2e9542d794.png)

**Comment by safern** [comment]
> As mentioned previously to one need only change the Target Framework from .NET Core 2.2 to .NET Core 3.0 to recreate the render issue.

What package version are you using?

**Comment by endofunk** [comment]
`System.Drawing.Common` : 4.6.0
`Microsoft.NETCore.App` : 2.2.0
`Microsoft.NETCore.App` : 3.0.0
`Visual Studio for Mac 2019` : 8.3 (build 1805

**Comment by peters** [comment]
@endofunk It’s reproducible on Ubuntu 19.04 as well.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by akkgr** [comment]
Me too, had to go back to core 2.2.

**Comment by krahu** [comment]
Last version where it is working is **.NET Core 3.0 Preview 7**. You can try [CoreCompat](https://github.com/CoreCompat/CoreCompat) or  [CoreCompat v2](https://www.nuget.org/packages/CoreCompat.System.Drawing.v2/) which privide same namespaces. Or rewrite code to use SkiaSharp (or ImageSharp....) like us.

**Comment by wuchang** [comment]
遇到相同的问题
``` g.DrawString(“1234”，....```

![TIM截图20191011230756](https://user-images.githubusercontent.com/137900/66662776-08d83e00-ec7c-11e9-889f-70510e14976a.png)

**Comment by safern** [comment]
Thanks for the report. I've assigned a milestone, it indeed seems like a regression, I will investigate, and see try to root-cause the issue. If it is indeed a regression, will change the milestone to 3.x and try to get it for our 3.1 release

**Comment by safern** [comment]
Ok, so I had time to investigate this. 

This was broken as part of this change: https://github.com/dotnet/corefx/commit/b75421a0035bf3a44e1f68447255470d57074dbb#diff-8eda13b1268284d720355f95667dea21R218 as it is missing a `CharSet = Unicode` parameter in the `DllImport`. 

Then we consolidated some `Graphics` code in between `Unix` and `Windows` and this was fixed there as you can see on master: https://github.com/dotnet/corefx/blob/b49a8a9be1d53cd9e50cb68fd8540be25c65d433/src/System.Drawing.Common/src/System/Drawing/GdiplusNative.cs#L1234

I will put up a PR to fix this on 3.0 and 3.1 and of course audit to see if there were any other regressions where we needed to use Unicode as the Charset.

cc: @danmosemsft

**Comment by dotnetdot1** [comment]
> 遇到相同的问题
> ` g.DrawString(“1234”，....`
> 
> ![TIM截图20191011230756](https://user-images.githubusercontent.com/137900/66662776-08d83e00-ec7c-11e9-889f-70510e14976a.png)
https://www.cnblogs.com/dotnet-org-cn/p/11756285.html
nuget 包中的GdipDrawString 定义问题导致的 乱码，收到改回来就好 
nuget 包中的GdipDrawString 定义 少了CharSet 标记导致的

**Comment by dotnetdot1** [comment]
https://www.cnblogs.com/dotnet-org-cn/p/11756285.html
nuget 包中的GdipDrawString 定义问题导致的 乱码，收到改回来就好
nuget 包中的GdipDrawString 定义 少了CharSet 标记导致的

**Comment by safern** [comment]
This is fixed.
