### ISSUE TITLE
JsonSerializer.Deserialize<dynamic> is not producing a dynamic

### ISSUE THREAD

**Issue by Corys9** [dotnet/corefx#41290]
JsonSerializer.Deserialize&lt;dynamic&gt; does not produce a dynamic, but System.Text.Json.JsonElement instead. Is this going to be supported in the near future?

**Comment by scalablecory** [comment]
Closing as duplicate of #38007. We're looking for some good use cases for this, and would appreciate a comment there on how you'd use this.
