### ISSUE TITLE
Interop.OpenSsl.cs should not depend on SslProtocols definition

### ISSUE THREAD

**Issue by vijaykota** [dotnet/corefx#4129]
At https://github.com/dotnet/corefx/blob/master/src/Common/src/Interop/Unix/libssl/Interop.OpenSsl.cs#L222 the enum SslProtocols is used which is specifc to System.Net.Primitives. As a result, other libraries like System.Net.HttpClient which consume functionality from Interop.OpenSsl.cs are forced to add a reference to System.Net.Primtives (and transitively other libs the latter depends on)

**Comment by davidsh** [comment]
Having libraries like System.Net.Http depend on System.Net.Primitives is fine. System.Net.Primitives is considered the "base" contract.

So, I don't understand this issue really. 

cc: @stephentoub @CIPop @pgavlin

**Comment by vijaykota** [comment]
But what is the advantage of adding this dependency? System.Net.HttpClient was just an example. If defining a new type called PalSslProtocols is not an option, the method can take 5 bools as params (ssl2, ssl3.. etc.)

**Comment by eerhardt** [comment]
System.Net.Http already has a dependency on System.Net.Primitives.
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/project.json#L9
This isn't an issue.
Closing.
