### ISSUE TITLE
API suggestion: CharUnicodeInfo.UnicodeVersion

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/corefx#41308]
Suggest adding an API that allows callers to determine the version of the Unicode Standard currently supported by the `CharUnicodeInfo` class.

```cs
namespace System.Globalization
{
    public static class CharUnicodeInfo
    {
        public static Version UnicodeVersion { get; }
    }
}
```

This will return a `System.Version` representing the Unicode data files which have been ingested to form the `CharUnicodeInfo` backing tables. As of this writing, the return value would be "11.0.0". Once we update the backing data, it'll read "12.1.0". And so on each time we ingest new data.

Per the versioning scheme listed at https://www.unicode.org/versions/#Version_Numbering, Unicode Standard version numbers are always in the format _\<major\>.\<minor\>.\<update\>_. So this makes the `System.Version` class ideal for representing such data.

/cc @tarekgh

**Comment by tarekgh** [comment]
I am concerned this property will cause come confusion as we use some functionality from the underlying OS (e.g. sorting) which will not match this version we are exposing. either we avoid exposing this at all or we may try to expose it in more constrained name (like UnicodeCharCategoryVersion or something similar.

**Comment by GrabYourPitchforks** [comment]
Yes, we'd have to be mindful of any potential confusion. My intent was that this version number would only reflect what's backing the `CharUnicodeInfo` class. If devs are unlikely to know the difference between that class and general comparison / sorting then we may need to rethink this.

**Comment by tarekgh** [comment]
> If devs are unlikely to know the difference between that class and general comparison / sorting then we may need to rethink this.

I am pretty sure this will be the case if we didn't name this property more specific to the char Unicode info.

**Comment by GrabYourPitchforks** [comment]
I don't have a good scenario for this at the moment. Closing.
