### ISSUE TITLE
System.Private assemblies don't get stable product version in AssemblyInformationalVersion

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#41315]
This is true for all System.Private assemblies that ship in the shared framework and needs to be fixed in CoreFx and CoreCLR.

Thank you @mjsabby for the report and @dagood for investigating.

Bug is here in CoreFx: 
https://github.com/dotnet/corefx/blob/4ac4c0367003fe3973a3648eb0715ddb0e3bbcea/Directory.Build.props#L393

To fix we may want to change the behavior to consider IsNetCoreApp where we don't set this for libraries that are part of the shared framework.  For CoreCLR we might just explicitly set it in the corelib project.

**Comment by safern** [comment]
Self assigned as I did this change. We might still need to set block stable for those packages in order to not produce a stable package.

**Comment by ericstj** [comment]
I don't think any of these actually build packages, but if you can think of a good rule go ahead and make it.

**Comment by safern** [comment]
> I don't think any of these actually build packages, but if you can think of a good rule go ahead and make it.

Yeah I was mixing up terms. We just need to add two different rules, `IsShippingPackage` and `IsShippingAssembly`.

**Comment by ericstj** [comment]
Reactivating to track port to 3.0.

**Comment by safern** [comment]
The fix for this was merged earlier today in 3.0
