### ISSUE TITLE
Deserialize interfaces using System.Text.Json.JsonSerializer

### ISSUE THREAD

**Issue by marian-margeta** [dotnet/corefx#41325]
How can I deserialize json to a class type that contain interface properties? I have a tree based structure that looks like this:
```csharp
interface INode { }

class Node : INode
{
    public List<INode> Nodes { get; set; }
}

class Leaf : INode
{
    public string Value { get; set; }
}
```

With Json.NET I am able to deserialize it by defining custom JsonConverter:
```csharp
class InterfaceJsonConverter : JsonConverter
{
    public override bool CanConvert(Type objectType)
    {
        return objectType.IsInterface && typeof(INode).IsAssignableFrom(objectType);
    }
    ....
}
```

With with System.Text.Json.JsonSerializer I can also implement custom converter that inherits from `JsonConverter<INode>`. However, when I try to deserialize the json, I get following exception:
```
NotSupportedException:  Deserialization of interface types is not supported.
```

Is it a way how to deserialize interfaces using JsonSerializer at this time? If not is it planned for future releases?

**Comment by ahsonkhan** [comment]
> However, when I try to deserialize the json, I get following exception

@steveharter, @layomia  - is this an issue with the converter feature?

I remember we had similar issues for polymorphic types (at least for built-in collection interfaces, etc.). Were those issues fixed specifically for the built-in cases? If so, we should extend support for user-defined types/interfaces as well.

**Comment by layomia** [comment]
Polymorphic interface deserialization will be considered as part of https://github.com/dotnet/corefx/issues/39031.
