### ISSUE TITLE
The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by ClementeGao** [dotnet/corefx#41320]
# Issue Title
When I initiate a request with a certificate   The program has an error    is   The SSL connection could not be established, see inner exception.

# General

```c#
  private static string HttpPost(string url, string postdata, X509Certificate cer)
        {
            using (HttpClientHandler handler = new HttpClientHandler())
            {
                var httpClientHandler = new HttpClientHandler
                {
                    ServerCertificateCustomValidationCallback = (message, certificate2, arg3, arg4) => true
                };
                handler.ClientCertificates.Add(cer);
                using (HttpClient httpClient = new HttpClient(handler))
                {
                    //AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);
                    HttpContent httpContent = new StringContent(postdata);
                    var response = httpClient.PostAsync(url, httpContent).Result;

                    var body = response.Content.ReadAsStringAsync().Result;

                    return body;
                }
            }
```

**Comment by wfurt** [comment]
can you provide more information about certificate, server and OS you running on @ClementeGao? This is not actionable as currently written.

**Comment by scalablecory** [comment]
Closing this out -- please feel free to reopen if you're still encountering this problem and can provide more detail.

**Comment by ClementeGao** [comment]
sorry l am late for replay message l  got way for the issue,
![image](https://user-images.githubusercontent.com/16145998/68523782-d3fdec00-02f8-11ea-9b7d-e34bba815af7.png)
 X509Certificate2 certificate = new X509Certificate2(input.Path, CER_PASSWORD); the way solve my problem
before l used the following code
X509Certificate2 certificate = new X509Certificate2(input.Path, CER_PASSWORD, X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.MachineKeySet);

l do not know why
