### ISSUE TITLE
Problems serializing Dictionary<string,string> when is a property of an object

### ISSUE THREAD

**Issue by fvoncina** [dotnet/corefx#41337]
When I try to serialize a Dictionary<string, string> directly like this:
```csharp
var dic = new Dictionary<string, string>
{
    {"key1","value1" },
    {"key2","value2" },
};
var json = System.Text.Json.JsonSerializer.Serialize(dic);
```
I get the right output:
```json
{"key1":"value1","key2":"value2"}
```

But when the dictionary is a property of an object, the Dictionary is not serialized at all:
```csharp
public class Dto
{
    public string Id { get; set; }
    public IDictionary<string, string> Dic = new Dictionary<string, string>();
}

var dto = new Dto { Id = "aaaaaa" };
dto.Dic.Add("key1", "aaaa");
dto.Dic.Add("key2", "bbbb");            
var json = System.Text.Json.JsonSerializer.Serialize(dto);
```
Result:
```json
{"Id":"aaaaaa"}
```

**Comment by fvoncina** [comment]
Here is a working fiddle showing the problem: https://dotnetfiddle.net/54CeJJ

**Comment by ahsonkhan** [comment]
The JsonSerializer doesn't support fields currently (which is the case in your dictionary in `Dto`). That's why you are seeing the discrepency. If you make it a property with getter/setter, then it should serialize correctly.

```C#
public Dictionary<string, string> Dic { get; set; } = new Dictionary<string, string>();
```

Does that help resolve your issue?

**Comment by ahsonkhan** [comment]
Closing as duplicate.
