### ISSUE TITLE
Create WCF binary drops for adding new APIs to docs.microsoft.com

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/corefx#41334]
- [x] Drop for .NET Core 2.1 using WCF packages version 4.5.3

- [x] Drop for .NET Core 3.0 using WCF packages version 4.6.0

WCF Packages...
[System.ServiceModel.Duplex](https://www.nuget.org/packages/System.ServiceModel.Duplex/)
[System.ServiceModel.Http](https://www.nuget.org/packages/System.ServiceModel.Http/)
[System.ServiceModel.NetTcp](https://www.nuget.org/packages/System.ServiceModel.NetTcp/)
[System.ServiceModel.Primitives](https://www.nuget.org/packages/System.ServiceModel.Primitives/)
[System.ServiceModel.Security](https://www.nuget.org/packages/System.ServiceModel.Security/)

@mairaw Once the docs are created would it be possible to get a list of them so that we can review them. I assume that since all the APIs we've added in Core also exist in the full framework the docs will basically be a copy. There are some where we may want to make some additional changes due to functionality changes in porting them to Core.

Thanks.

**Comment by safern** [comment]
I already provided @mairaw with the drop so I will close this.
