### ISSUE TITLE
Delegate.GetMethodInfo may return null?

### ISSUE THREAD

**Issue by exyi** [dotnet/corefx#41346]
Why is the result of [`RuntimeReflectionExtensions.GetMethodInfo(this Delegate)`](https://github.com/dotnet/corefx/blame/0a1850cc370986c7348e09bcd1c1adcf522d6db3/src/System.Runtime/src/System/Reflection/RuntimeReflectionExtensions.cs#L103) marked as nullable? It only seems to touch the `Delegate.Method` property which is not nullable. If that's intended, could you please describe the reason in a comment?

**Comment by stephentoub** [comment]
This looks like a bug.
