### ISSUE TITLE
Issue regarding AddAuthenticationCore and cookies

### ISSUE THREAD

**Issue by ffMathy** [dotnet/corefx#41349]
Before in my old code, I used to do:

```csharp
services
    .AddAuthentication(options =>
    {
        options.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        options.DefaultChallengeScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    })
    .AddCookie(options =>
    {
        options.LoginPath = "/Admin/Account/Login";
    });
```

To get auth with cookies working. 

Now, after migrating to .NET Core 3 while still using the above code, my identity showed as never authenticated. I found something referring to something being moved around, and concluded I needed to use `AddAuthenticationCore`.

I couldn't find any documentation on how to get the same working with that, so I ended up with the following code:

```csharp
services.AddAuthenticationCore(options =>
{
    options.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;

    options.AddScheme<CookieAuthenticationHandler>(CookieAuthenticationDefaults.AuthenticationScheme, null);
});
```

But now I get the following error:

> Unable to resolve service for type 'Microsoft.AspNetCore.Authentication.ISystemClock' while attempting to activate 'Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler'.

The reason I tried using this approach, is that `AddCookie` no longer exists with the new method approach.

What can I do to get this working?

**Comment by ffMathy** [comment]
I think your bot unfortunately tagged this with the wrong label. I suppose it has to do with authentication?

**Comment by stephentoub** [comment]
@ffMathy, this looks like an issue for ASP.NET. Can you move this to the aspnet/aspnetcore repo? Thanks.

**Comment by GrabYourPitchforks** [comment]
Transferred to https://github.com/aspnet/AspNetCore/issues/14555.
