### ISSUE TITLE
System.Text.Json fails to serialize Dictionary with int keys

### ISSUE THREAD

**Issue by israellot** [dotnet/corefx#41345]
```
var dictionary = new Dictionary<int, int>()
            {
                [0] = 1
            };

 var serialized = System.Text.Json.JsonSerializer.Serialize(dictionary);
```

This simple serialization is handled well by the former default Newtonsoft json library by serializing the int key as string. On System.Text.Json is throws a not supported exception.

**Comment by ahsonkhan** [comment]
This is a known issue and is a duplicate of https://github.com/dotnet/corefx/issues/40120
