### ISSUE TITLE
Compile error in Visual Studio 2019

### ISSUE THREAD

**Issue by ffMathy** [dotnet/corefx#41344]
I get the following error:

> ETSDK1013	The TargetFramework value '' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly.	System.Text.Json (src\System.Text.Json)	C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets

When trying to compile `System.Text.Json`.

I really want to contribute more, so this is a bummer.

**Comment by ahsonkhan** [comment]
Did you first build the repo via the command line?

If on windows, run `build.cmd` at the root of the repo first, then you should be able to build/test S.T.Json via the command line/in VS.

https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md#building-the-repository

**Comment by ericstj** [comment]
+1 to what @ahsonkhan said.  Also, be sure to have the latest .NETCore 3.0 SDK installed as we now depend on it (when opening in VS).  If you don't wish to install it you can launch the sln from the root, after building once, using `build -vs System.Text.Json`.  The latter will allow you to run tests in test explorer as well.  Let us know if you have any issues.

**Comment by ViktorHofer** [comment]
Closing as resolved. Feel free to reopen if you still encounter the issue.
