### ISSUE TITLE
When CurrentCulture is "fr-FR" , double.TryParse("0.0000", out double d) return false.

### ISSUE THREAD

**Issue by toolgood** [dotnet/corefx#41356]
In .net framework 4.0, .net framework 4.6, .net core 2.1 and .net core 3.0 throw exception.

       static void Main(string[] args)
        {
            Thread.CurrentThread.CurrentCulture = new CultureInfo("fr-FR");
            //Thread.CurrentThread.CurrentUICulture = new CultureInfo("fr-FR");

            if (double.TryParse("0.0000", out double d) == false) {
                throw new Exception("double.TryParse(\"0.0000\",out double d) is Error.");
            }

            Console.WriteLine("double.TryParse(\"0.0000\",out double d) is OK.");
        }

**Comment by danmosemsft** [comment]
I was going to suggest this was because in `fr-FR` the decimal separator is a comma. But in en-US, `0,000` parses successfully.

**Comment by kevingosse** [comment]
> I was going to suggest this was because in `fr-FR` the decimal separator is a comma. But in en-US, `0,000` parses successfully.

Group separator in fr-FR is space, not point. `double.TryParse("0 0000", out double d)` evaluates properly (and throws with en-US).

**Comment by tarekgh** [comment]
"0.0000" is wrong number for fr-FR. because ```.``` is not decimal separator nor group separator. 

```C#
            CultureInfo ci = new CultureInfo("fr-FR");
            Console.WriteLine($"NumberDecimalSeparator: '{ci.NumberFormat.NumberDecimalSeparator}'");
            Console.WriteLine($"NumberGroupSeparator: '{ci.NumberFormat.NumberGroupSeparator}'");
            Console.WriteLine($"1.234 formatted as : '{1.234.ToString(ci)}'");
```

That produce 

```
NumberDecimalSeparator: ','
NumberGroupSeparator: ' '
1.234 formatted as : '1,234'
```

If you want to guarantee the parsing success, always use Invariant culture for formatting and parsing the numbers and dates.
