### ISSUE TITLE
corefx is not getting indexed by source.dot.net

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#41368]
cc: @ahsonkhan, @alexperovich

**Comment by alexperovich** [comment]
This is strange. For some reason now the indexer is unable to load this project and many others. 
>  Generating F:\workspace\_work\1\s\bin\repo\corefx\src\System.Text.Json\src\System.Text.Json.csproj
  11:36:49 Workspace failed: Msbuild failed when processing the file 'F:\workspace\_work\1\s\bin\repo\corefx\src\System.Text.Json\src\System.Text.Json.csproj' with message: The SDK 'Microsoft.NET.Sdk' specified could not be found.  F:\workspace\_work\1\s\bin\repo\corefx\src\System.Text.Json\src\System.Text.Json.csproj
  11:36:49 Msbuild failed when processing the file 'F:\workspace\_work\1\s\bin\repo\corefx\src\System.Text.Json\src\System.Text.Json.csproj' with message: The SDK 'Microsoft.NET.Sdk' specified could not be found.  F:\workspace\_work\1\s\bin\repo\corefx\src\System.Text.Json\src\System.Text.Json.csproj

It looks like something strange is not working with roslyn's MSBuildWorkspace to load these projects. Most of the projects in corefx are hitting this.

**Comment by alexperovich** [comment]
I'm trying an updated version of the roslyn assemblies.

**Comment by stephentoub** [comment]
What version of the sdk is being used? Has it been updated to at least 3.0.100?

**Comment by alexperovich** [comment]
Whatever version is specified in the global.json is downloaded as part of the indexer build, but the actual indexing part might be unable to see that. I'm not sure how MSBuildWorkspace finds the things needs.

**Comment by alexperovich** [comment]
Hrm, does msbuild.exe from VS use SDKs from the path like that? If not that would probably be the problem.

**Comment by alexperovich** [comment]
The build of winforms is failing completely after installing the correct dotnet cli but it then uses the msbuild.exe from vs 2019 and it fails with this same error. Is preview VS required?

**Comment by danmosemsft** [comment]
cc @ViktorHofer

**Comment by ViktorHofer** [comment]
I can't speak for winforms but in corefx we depend on 3.0.100. Do you have a commit when the indexer started failing?

**Comment by alexperovich** [comment]
Updating to the latest roslyn assemblies didn't fix anything.

**Comment by alexperovich** [comment]
Yea, it looks like something odd with VS msbuild and any repo building 3.0 or 5.0 preview. The vs msbuild and the roslyn MSBuildWorkspace both hit this problem.

**Comment by stephentoub** [comment]
This is starting to hamper people's productivity. Anything we can do to help make progress?

**Comment by john-h-k** [comment]
might be related, you can see it appears to be broken in a couple of places, e.g [Environment.NewLine](https://source.dot.net/#System.Private.CoreLib/shared/System/Environment.Windows.cs,63a04833d43dd9d3)

**Comment by stephentoub** [comment]
> you can see it appears to be broken in a couple of places, e.g Environment.NewLine

That looks like an unrelated issue.  @KirillOsenkov, does this look familiar?  The code:
https://github.com/dotnet/coreclr/blob/2d62d2b19d3213b3b0b3d273f192b7b298a1e86a/src/System.Private.CoreLib/shared/System/Environment.Windows.cs#L50
```C#
public static string NewLine => "\r\n";
```
is getting rendered like this:
![image](https://user-images.githubusercontent.com/2642209/66073994-3b6c9300-e526-11e9-90a9-9822c148a3a3.png)

**Comment by KirillOsenkov** [comment]
@alexperovich I've seen the "Microsoft.NET.Sdk" not found before. I had to open VS on the machine and allow Prerelease SDKs in Tools Options. 

![image](https://user-images.githubusercontent.com/679326/66078390-c9408200-e516-11e9-9549-5affbcb12500.png)

I think it ultimately reads a text file from somewhere, maybe we can create that file programmatically to trick the SDK Resolver into working.

Paging @nguerrera for help!

**Comment by KirillOsenkov** [comment]
@stephentoub escape character rendering is known: https://github.com/KirillOsenkov/SourceBrowser/issues/125

I've fixed it just now in https://github.com/KirillOsenkov/SourceBrowser/commit/8b38c94fe8b705efba234d6c24eefc79a8830f67

@alexperovich wanna pull it down? ^^

**Comment by alexperovich** [comment]
I'll update to the latest stuff when I have time. The failure to index projects is caused by the VS 16.3 restriction on 3.0.100 from what I can tell. The build machines don't have VS 16.3 so it can't build anything. Once those build machines are updated I will fix it.

**Comment by stephentoub** [comment]
Thanks.

**Comment by stephentoub** [comment]
@alexperovich, did you make a change?  It all appears to be working again.

**Comment by alexperovich** [comment]
Yep, I got it fixed. Things are working now https://source.dot.net/#System.Text.Json/System/Text/Json/Document/JsonDocument.cs,4dd04a3ef6a52203.
