### ISSUE TITLE
Dotnet-sdk error

### ISSUE THREAD

**Issue by Godtide** [dotnet/corefx#41362]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux RHEL 7 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

After following the instructions
mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-3.0.100-rhel.6-x64.tar.gz -C $HOME/dotnet
export DOTNET_ROOT=$HOME/dotnet
export PATH=$PATH:$HOME/dotnet

"dotnet new console -o myApp" and every dotnet command 

throws error

System.TypeInitializationException: The type initializer for 'Crypto' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'System.Security.Cryptography.Native.OpenSsl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libSystem.Security.Cryptography.Native.OpenSsl: cannot open shared object file: No such file or directory
   at Interop.Crypto.GetMaxMdSize()
   at Interop.Crypto..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto.EvpSha256()
   at Internal.Cryptography.HashProviderDispenser.CreateHashProvider(String hashAlgorithmId)
   at System.Security.Cryptography.SHA256.Implementation..ctor()
   at System.Security.Cryptography.SHA256.Create()
   at Microsoft.DotNet.Cli.Telemetry.Sha256Hasher.Hash(String text)
   at Microsoft.DotNet.Cli.Telemetry.TelemetryCommonProperties.GetTelemetryCommonProperties()
   at Microsoft.DotNet.Cli.Telemetry.Telemetry.InitializeTelemetry()

**Comment by scalablecory** [comment]
Not sure if setup issue @dagood.

**Comment by dagood** [comment]
@Godtide, is it possible you're missing an openssl prereq? Also, just to confirm for sure, you are running on RHEL 6, right?

@leecow, are RHEL 6 dependencies missing from https://github.com/dotnet/core/blob/master/Documentation/linux-prereqs.md, given that https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-3.0.100-linux-rhel-6-x64-binaries links to it?

**Comment by leecow** [comment]
If that's the problem then yes, we can add a row for RHEL 6 dependencies. @Godtide , can you confirm that RHEL6 is what you are using and if installing openssl resolves your issue?

**Comment by wfurt** [comment]
The claim is:
> Operating System: Linux RHEL 7 - x64

seems like use of RH6 build on RH7.

**Comment by dagood** [comment]
"Operating System: Linux RHEL 7 - x64" is automatically generated text based on the page this issue was opened from (after hitting the "I can into an issue" button). We don't have a RHEL 6 entry in the dropdown, which I would assume is why the tarball was used instead. (Which is the right thing to do if running RHEL 6.)

Of course, without more info, a lot is possible.

**Comment by Godtide** [comment]
My bad, my Linux distribution is Ubuntu 18.04.
and I've installed the packages. Thank you for your contribution
