### ISSUE TITLE
Is there any special reason to not providing an interface or abstraction of HttpClient?

### ISSUE THREAD

**Issue by abbasdevelopers** [dotnet/corefx#41379]
# Is there any special reason to not providing an interface or abstraction of HttpClient?

Although, it is possible to register dependency with HttpClient concrete class but what if I want to mock its implementation. I can define my own interface with all given methods in HttpClient class but this approach is not much appealing. Do you have any plan to provide its interface or abstraction in future? Or, there is any special reason to keep it concrete?

**Comment by stephentoub** [comment]
Closing as dup of https://github.com/dotnet/corefx/issues/29086 (which itself is largely a dup of another issue). Thanks.
