### ISSUE TITLE
RuntimeInformation should expose APIs to detect OS architecture and OS skus.

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#4137]
**Rationale**
These APIs are requested by [developers](https://github.com/dotnet/corefx/issues/999) and by the DNX team, to incorporate ```IRuntimeEnvironment``` [APIs](https://github.com/aspnet/dnx/blob/8ddcfe9661188784fad37ea8d3b2965d3b4e756f/src/Microsoft.Extensions.PlatformAbstractions/IRuntimeEnvironment.cs) to .NET Core. 
We are also providing ```GetOSDisplayName``` that will give information about OS version, if we are able to detect a version, to be used purely for debug purposes, like to send diagnostic data or to display information. 
ARM64 is not added to OSArchitecture, as it is not yet supported. Once we decide to add ARM64, it should be easy to update the OOB assembly contract without breaking existing applications.

**Proposed APIs**
```c#
namespace System.Runtime.InteropServices
{
    public enum Architecture
    {
        x86,
        x64,
        Arm
    }

    public static partial class RuntimeInformation
    {
        public static Architecture ProcessArchitecture { get { return default(Architecture); } }
        public static Architecture OSArchitecture { get { return default(Architecture); } }
        public static string OSDescription { get { return default(string); } }
        public static string FrameworkDescription { get { return default(string); } }
    }
}
```

cc @terrajobst @weshaggard @stephentoub 

**Changes From API Review**

1. Made ```Is64BitProcess()``` as ```GetProcessArchitecture()``` that'll return an ```Architecture``` enum value.
2. Renamed ```GetOSDisplayName()``` and ```GetRuntimeDisplayName
()``` to ```GetOSDebugName()``` and ```GetRuntimeDebugName()``` to emphasize that these APIs are to be used only for debug informational purposes.

**Comment by AArnott** [comment]
Let's try not to let this turn into browser "user-agent" strings. ;-)

**Comment by mellinoe** [comment]
Isn't "OSArchitecture" more like a "ProcessorArchitecture" ? I think the "GetOSArchitecture()" method could stay the same, but the enum itself seems to be the processor architecture, more specifically.

**Comment by mellinoe** [comment]
Also, just something random to throw out there: when I'm working on System.Numerics.Vectors, it's often interesting to know which specific instruction sets the machine I am running on supports. For example, does the processor support SSE2, AVX2, AVX-512, etc. Theoretically I could use this information at runtime in order to select different specialized algorithms depending on my knowledge of how they perform on different hardware. For example, maybe I could defer to one of two image decoding algorithms depending on whether some specific vector manipulation instruction was available on the machine. Would we be better suited to encapsulating these 'RuntimeInformation' API's in such a way that, in the future, the above information could also be expressed through the library? Or do we think that this library isn't going to be a place for such information to be exposed? Based on the few things we are exposing here, it would seem like a natural extension to add some of what I described above in the future, but I'm not sure what our view on the scope of this thing is.

**Comment by Priya91** [comment]
@mellinoe : I intended this to be OSArchitecture, since running 32 bit OS on 64bit processor is allowed. And any operation one might want to do has to be with what bitness OS is rather than the processor's capability.

**Comment by mellinoe** [comment]
My point was mainly that the enum itself doesn't really seem to have any affinity to the concept of an operating system, it's just has values that represent various architectures for processors themselves.

Consider if we had some API to query what kind of processor you were running on (the actual physical chip). It would probably make sense to include the architecture type of that processor, but would we want the type of that enum to be named "OSArchitecture"? Or would we want a separate enum that had pretty much the same values?

**Comment by Priya91** [comment]
Yeah I understand the premise of your comment, but ```GetOSArchitecture() == ProcessorArchitecture.x64``` is kind of misleading in context. Maybe just having ```Architecture``` would suit here.

We also already have ```ProcessorArchitecture``` enum type in ```System.Reflection``` and will be a conflict.

**Comment by mellinoe** [comment]
> We also already have ProcessorArchitecture enum type in System.Reflection and will be a conflict.

Ah, you're right, and it's in all the way down in System.Runtime as well... That's rather unfortunate.

**Comment by davidfowl** [comment]
What about Runtime display name?

**Comment by svick** [comment]
What about `Is64BitOperatingSystem`? Though I'm not sure it's useful outside desktop .Net (where `Environment.Is64BitOperatingSystem` is available). I saw it used for example to find the right location of tools in the Windows SDK.

Also, why does the proposed API use methods instead of properties?

**Comment by Priya91** [comment]
@svick ```GetOSArchitecture()``` returns an enum of x86, x64 and ARM, which will tell if it's 64 bit operating system.

**Comment by Priya91** [comment]
@davidfowl What's the use case for getting runtime display name? If this API exists what do you expect it to return? I am not aware of any special branding done for .NET runtimes.

**Comment by davidfowl** [comment]
@Priya91 some loggable information or something I could put in an error page:

CoreCLR 1.3.4.000 (git sha).

Here's what `mono --version` prints:

```
Mono JIT compiler version 4.3.0 (explicit/07bae96 Thu Sep 17 10:54:44 EDT 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug
	LLVM:          yes(3.6.0svn-mono-(detached/a173357)
	GC:            sgen
```

We don't need that much information but some basic information would be great. You could imagine this contract implemented on mono would print something similar to above (maybe a single line version).

**Comment by davidfowl** [comment]
@Priya91 Any more info needed?

**Comment by Priya91** [comment]
@davidfowl Thanks for the info, let me investigate how this API will behave for our available runtimes, and what would be a good string to return and get back to you if i need more info.
