### ISSUE TITLE
Need to update build/machine setup instructions for corefx on Linux

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefx#4138]
Currently, we need to install:
- libcurl
- libssl-dev

To build corefx successfully on Linux, but these dependencies are not listed on any build docs.

**Comment by leculver** [comment]
Additionally I had to increase the number of file handles available on my machine in order to build successfully.  I added `fs.file-max = 100000` to `/etc/sysctl.conf`, then ran `sudo sysctl -p`.  This allowed the build to succeed.

**Comment by naamunds** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/1905
