### ISSUE TITLE
The type name 'SqlConnection' could not be found in the namespace 'System.Data.SqlClient'

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/corefx#41382]
Hi,

Why this happens? Should I install another package instead of `System.Data.SqlClient`?

**Comment by dehghani-mehdi** [comment]
Reinstalling `System.Data.SqlClient` fixed the problem!

**Comment by divega** [comment]
@dehghani-mehdi also check https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/.
