### ISSUE TITLE
How can I use Microsoft.AspNetCore.Mvc.Internal.ActionSelector in ASP.NET Core 3.0/.NET Core 3.0 or alternative solution in Core 3.0? 

### ISSUE THREAD

**Issue by Microshaoft** [dotnet/corefx#41381]
reference MSDN:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.internal.actionselector?view=aspnetcore-2.2

c# code in .NET Core 2.2, for your reference:

https://github.com/Microshaoft/Microshaoft.Common.Utilities.Net.4x/blob/aace0a952433f09d24d5977ad7fae7adf40a18d4/CommonUtilities.Shared/WebApi.Common.Controllers/SyncAsyncActionSelector.cs#L8

**Comment by pranavkm** [comment]
This issue was moved to aspnet/AspNetCore#14512
