### ISSUE TITLE
Bring System.Speech to .Net Core or add some alternative

### ISSUE THREAD

**Issue by kolappannathan** [dotnet/corefx#41391]
System.Speech API is not available in .Net Core or .Net standard. Currently, there are no alternatives for synthesizing audio locally in these frameworks. Kindly bring an API for this.

I am trying to migrate a [project ](https://github.com/vishnuprasadv/CaptchaGen) from .Net Framework to .Net Core but this is preventing it.

**Comment by danmosemsft** [comment]
@preethikurup @terrajobst have we already reached out to owners of System.Speech? I don't recall working with that team.

**Comment by terrajobst** [comment]
> @preethikurup @terrajobst have we already reached out to owners of System.Speech? I don't recall working with that team.

Yes, they are now part of Azure and there is a new offering. `System.Speech` is not evolved anymore.

**Comment by terrajobst** [comment]
We don't plan on bringing this .NET Framework API to .NET Core. See [this announcement](https://github.com/dotnet/corefx/issues/41769) for details.

**Comment by kolappannathan** [comment]
Does .Net core has viable alternative option that for **local** speech synthesis?
