### ISSUE TITLE
Should ResolveEventArgs.Name be nullable?

### ISSUE THREAD

**Issue by jnm2** [dotnet/corefx#41404]
Is [`AppDomain.AssemblyResolve`](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.assemblyresolve?view=netcore-3.0) ever raised with a null [`ResolveEventArgs.Name`](https://docs.microsoft.com/en-us/dotnet/api/system.resolveeventargs.name?view=netcore-3.0) property? It doesn't seem like anything useful could be done by the event handler if `Name` is null.

It would save having to write `if (e.Name is null) return null;` in every handler if `ResolveEventArgs.Name` could be non-nullable to guarantee that the handler won't be called unless there is some name.

https://github.com/dotnet/corefx/blob/967eb3c5cb5fd36c8bb56d06f4c840f6a7a5a754/src/Common/src/CoreLib/System/ResolveEventArgs.cs#L11-L23

**Comment by Wraith2** [comment]
If I remember the design review correctly I think there is at least one case with dynamic codegen where there isn't a name.

**Comment by jnm2** [comment]
If there's ever a case where you're trying to load an assembly with no name, why is `ResolveEventArgs` instantiated?

**Comment by safern** [comment]
cc: @jkotas

**Comment by jkotas** [comment]
`Name` is never going to be null when the event is created by the runtime.

It may be null in the unlikely case that it is created by user code (e.g. `new ResolveEventArgs(null)`) because of the public constructor is missing a null check on the argument.

**Comment by safern** [comment]
> It may be null in the unlikely case that it is created by user code (e.g. new ResolveEventArgs(null)) because of the public constructor is missing a null check on the argument.

So it makes sense to leave it as nullable, correct?

**Comment by jkotas** [comment]
It depends on whether you consider `new ResolveEventArgs(null)` to be a bug or feature. I think it is a bug. My vote would be to change to both the name constructor argument  and the name property to be non-nullable.

**Comment by safern** [comment]
> My vote would be to change both the name constructor argument and the name property to be non-nullable.

Sounds reasonable. We followed that pattern with some Attributes where null is not really accepted but you can't throw. 

At the end the annotations are about the intent of the API, it seems like this API didn't have the intent to be used with `null`.

**Comment by stephentoub** [comment]
Seems fine.  If we believe framework code is in reality the only producer of this EventArgs type, and that even it weren't it would never make sense to create one with a null name, then a non-nullable name is the intent, and regardless of whether it checks for null, we can annotate it as non-nullable.
