### ISSUE TITLE
Unable to serialize ValueTuple using System.Text.Json

### ISSUE THREAD

**Issue by codexguy** [dotnet/corefx#41420]
To reproduce:
Take the sample default ASPNET Core 3.0 app (API-based template), change the WeatherForecast class to include a ValueTuple:

    public class WeatherForecast
    {
...

        public (int x, int y) Location { get; set; }
    }

Change the Get method to populate Location with arbitrary values. Run the project: JSON returned has an empty location. Serializing ValueTuple's is possible with Newtonsoft (being unable to do so wrecks existing code I have that uses ValueTuples successfully with Core 2.1, moving to Core 3.0).

**Comment by GrabYourPitchforks** [comment]
Possible dupe of https://github.com/dotnet/corefx/pull/39254?

**Comment by codexguy** [comment]
My workaround for this is to start changing code to use poco instead. (Would have been better to fail the serialization, IMHO, than let it emit bad output.) If this is the same as 39254, please add "ValueTuples" as part of the test cases for resolution. As a side note, it seems like the System.Text.Json serializer also does not handle *fields* where Newtonsoft does.

**Comment by codexguy** [comment]
I believe this is a Duplicate of #36505

**Comment by ahsonkhan** [comment]
I mention a workaround for `ValueTuples` (up to 3) based on custom converters if folks need it.
https://github.com/dotnet/runtime/issues/1519#issuecomment-572751931
