### ISSUE TITLE
Enumerable.OfType should use where TResult:notnull

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/corefx#41431]
Null will never get into result because of it's semantics. So it should be disallowed on the type parameter.

Since nullable annotation of `System.Linq` hasn't been shipped now, the change isn't breaking.

**Comment by stephentoub** [comment]
Why is such a change beneficial / what does it improve? Adding that constraint impairs composition, where you want to cast to a T your handed from somewhere else, and not having the constraint doesn't prevent you from using a non-nullable type.

**Comment by huoyaoyuan** [comment]
Preventing potential unnecessary cast(which does have overhead), or potential `! `(may cause bugs if context changes.
The interface is covariant, using non-nullable type doesn't narrow the return consuming side.
For type argument there could be problem.
Does current annotation system support something like this? 
```csharp
IEnumerable<[NotNull]T> OfType<T>()
```

**Comment by stephentoub** [comment]
> Does current annotation system support something like this?

No

> Preventing potential unnecessary cast(which does have overhead)

If the developer writes:
```C#
OfType<string>
```
then the `T` is already non-nullable.

If the developer explicitly writes:
```C#
OfType<string?>
```
then they're explicitly specifying a `T?`, presumably because they want to pass this `IEnumerable<T?>` off to something that needs that type.

I see very little upside and concrete downside (composition scenarios where the supplied `T` may be nullable) to making the proposed change.

**Comment by huoyaoyuan** [comment]
> then they're explicitly specifying a T?, presumably because they want to pass this IEnumerable<T?> off to something that needs that type.

'IEnumerable<T>' is always 'IEnumerable<T?>' because covariance, so this would not be a problem.

Let me clearify potential usage:
```csharp
class Generic<T>
{
    public void M(IEnumerable untyped)
    {
        var typed = untyped.OfType<T>();
        foreach (var element in typed)
        {
            // no null check for element is required, even if T is unconstrained 
        }
    }
}
```

This seems to be unpopular though.

**Comment by stephentoub** [comment]
> no null check for element is required, even if T is unconstrained 

If T is unconstrained, this would fail with a warning if OfType was constrained to notnull.

**Comment by stephentoub** [comment]
Thanks for the suggestion.  We're going to leave this as-is.
