### ISSUE TITLE
private set PropertyInfo GetSetMethod Is null

### ISSUE THREAD

**Issue by hanxinimm** [dotnet/corefx#41434]
my class has two property

public long Id => 2;
public long OrganizationId { get; private set; }

OrganizationId  PropertyInfo GetSetMethod Is null,
but IL Code has method

![image](https://user-images.githubusercontent.com/13499426/65831588-0970ec00-e2ee-11e9-8202-39840f3c4f16.png)

![image](https://user-images.githubusercontent.com/13499426/65831645-8ac87e80-e2ee-11e9-8d84-780729d28e91.png)

what's  happen?

**Comment by vcsjones** [comment]
Can you include the code that is used to obtain the `PropertyInfo` instance that reproduces the issue? If I try this:

```csharp
class Program
{
    public class Bar
    {
        public long Foo { get; private set; }
    }

    static void Main(string[] args)
    {
        var result = typeof(Bar).GetProperty(nameof(Bar.Foo));
        Console.WriteLine(result.SetMethod != null);
    }
}
```

It prints `True`, so the reflection is seeing the setter.

**Comment by hanxinimm** [comment]
`class Program
    {
        public class Bar : BarBase
        {
            public long FooName { get; set; }
        }

        public abstract class BarBase
        {
            public long Foo { get; private set; }
        }

        static void Main(string[] args)
        {
            var result = typeof(Bar).GetProperty(nameof(Bar.Foo));
            Console.WriteLine(result.SetMethod != null);
            Console.WriteLine("Hello World!");
        }
    }`

**Comment by vcsjones** [comment]
@hanxinimm 

Ah, that's because `Foo` is not visible to `Bar`. You would similarly get a compilation error if you tried accessing the setter from `Bar`.

You can access it like so:

```csharp
var result = typeof(BarBase).GetProperty(nameof(Bar.Foo));
```
