### ISSUE TITLE
How do I set the JSON DateTime format?

### ISSUE THREAD

**Issue by q7164518** [dotnet/corefx#41436]
var json = JsonSerializer.Serialize(new { D = DateTime.Now });
I want to format it as "yyyy-mm-dd HH: MM :ss"
How can I solve it?

**Comment by q7164518** [comment]
I have read the document and solved it.
https://docs.microsoft.com/zh-cn/dotnet/api/system.text.json.serialization.jsonconverter-1?view=netcore-3.0

**Comment by ahsonkhan** [comment]
Here's the document that talks specifically about overriding DateTime behavior via converters:
https://docs.microsoft.com/en-us/dotnet/standard/datetime/system-text-json-support
