### ISSUE TITLE
HttpRequest Method Changes during Execution

### ISSUE THREAD

**Issue by KrisJohnstone** [dotnet/corefx#41444]
** Overview **
Trying to send a post message to Azure DevOps and while executing the httpRequest method changes from being Post to Get. The response I get back from Azure DevOps is Http Method not allowed.

** System Details **
Mac OSX 10.4.15
.Net Framework Versions:
Ice@Ices-MacBook-Pro-2  /  dotnet --list-sdks
2.1.700 [/usr/local/share/dotnet/sdk]
3.0.100 [/usr/local/share/dotnet/sdk]

** Code **   
```
public WorkItemQueryResult GetListOfStories(string queryString, string tfsInstance, string PAT)
        {
            var client = new HttpClient();
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", $"{GetPatAsEncodedString(PAT)}");

            var request = new HttpRequestMessage()
            {
                Content = new StringContent(queryString, Encoding.UTF8, "application/json" ),
                Method = HttpMethod.Post,
                RequestUri = new Uri($"{tfsInstance}_apis/wit/wiql?api-version=5.1")
            };
            
            request.Headers.Authorization = new AuthenticationHeaderValue("Basic", $"{GetPatAsEncodedString(PAT)}");
            request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            var task = Task.Run(() => client.SendAsync(request)); 
            task.Wait();

            if (!task.Result.IsSuccessStatusCode) return new WorkItemQueryResult();
            
            var response = task.Result.Content.ReadAsAsync<WorkItemQueryResult>();
            return response.Result;
        }
```

With a break point on Task.Run, the request method looks like the following: 
<img width="1945" alt="Screen Shot 2019-09-30 at 11 47 52 am" src="https://user-images.githubusercontent.com/18162364/65844242-babc6400-e378-11e9-8d55-eba93a61cac6.png">

After waiting for the task the request looks like the following:
<img width="1602" alt="Screen Shot 2019-09-30 at 11 51 08 am" src="https://user-images.githubusercontent.com/18162364/65844260-d162bb00-e378-11e9-8950-501853ffc79b.png">

The response code that I'm receiving is 405 - Method Not Allowed.

** Items Tried **
- I've tried using both versions of .Net Core in case there was a bug that somehow hadn't been found.
- Tried using .PostAsync instead. 

It's most likely something silly, but I've not been able to ascertain what the issue is, my google foo is letting me down.

**Comment by scalablecory** [comment]
@KrisJohnstone it sounds like @benaadams was able to help. Are you ready to close this issue?

**Comment by KrisJohnstone** [comment]
The problem hasn't been resolved. I still get 405 - Method Not Allowed :(

In my last post I verified:
- If it was a auth issue with azure devops then the expected outcome would be the same as in my test in YaRC I'd have thought, which would be a http status code of 203.
- That the URL in the request was the same in both screen grabs.

**Comment by scalablecory** [comment]
When we get a 3xx redirect, we clear out the Authorization header for security. To work around this, I would set your URL to one not requiring a redirect. Alternately, you can set `SocketsHttpHandler.AllowAutoRedirect = false` and manage the redirect yourself.

**Comment by Saancreed** [comment]
> * That the URL in the request was the same in both screen grabs.

> To work around this, I would set your URL to one not requiring a redirect.

Right, it looks like you were redirected because you tried to access the resource with http protocol. As a workaround you could try sending the request to `https://dev.azure.com` so you don't get redirected at all.

**Comment by KrisJohnstone** [comment]
Hey Guys,

Yes solved. The issue was my appSettings file wasn't being copied to the bin folder so still had a non https link :(

Thank you for the assistance, apologies for the rookie error.
