### ISSUE TITLE
LangVersion latest ignores C# 8

### ISSUE THREAD

**Issue by Timovzl** [dotnet/corefx#41458]
The interpretation of `<LangVersion>latest</LangVersion>` ignores C# 8. Instead, C# 7 is selected.

Tested in both `netcoreapp3.0` and `netstandard2.0` projects.

While I'm aware that the `netcoreapp3.0` project could simply omit the `LangVersion`, this still looks like incorrect (and counterintuitive) behavior. In practice it's annoying for existing project templates and for projects being upgraded.

(For `netstandard2.0` projects, even though we could argue about the usefulness of C# 8 there, I believe that `<LangVersion>latest</LangVersion>` expresses a clear intent to use the latest possible version - without having to update the value as potential new versions become available. That intent should be honored.)

**Comment by Timovzl** [comment]
Heh. Despite a Clean and Build, it appears the IDE was lagging. I'm not seeing the issue anymore.

**Comment by jrmoreno1** [comment]
I had the same problem, using 16.3.3 -- IDE issue, not framework.
