### ISSUE TITLE
Add Assembly.GetEntryAssembly() back to the contracts

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#4146]
We want to be able to implement `IApplicationEnvironment` which has an ApplicationName which is the name of the application being run. This is impossible to do today without writing a custom host or accessing it via mscorlib directly.

**Comment by davidfowl** [comment]
@nguerrera This is done right?

**Comment by nguerrera** [comment]
@davidfowl No, it isn't.

**Comment by nguerrera** [comment]
cc @weshaggard

**Comment by weshaggard** [comment]
@pallavit can you have a look at this.

**Comment by weshaggard** [comment]
@davidfowl how does this relate to https://github.com/dotnet/corefx/issues/4314? While in I'm in favor of adding this API as well I'm trying to understand your scenarios, do you have other scenarios outside of the application name?

**Comment by davidfowl** [comment]
Not really, if we added the other thing and make this the default implementation (and made the name settable). It would enable the scenario I'm after.

**Comment by davidfowl** [comment]
Can I get an update on this API?

**Comment by pallavit** [comment]
/cc: @weshaggard , @terrajobst We have been looking at the API additions collectively and this is in the list of the things. I am not sure of the timelines yet though, as the implementation work has not yet started. I am hoping you are mostly unblocked with #4314 and this is only for the matter of completeness. Let me know if that is not the case.

**Comment by weshaggard** [comment]
Yes this is included but we should try to do this as a one-off to help unblock some cli scenarios.

**Comment by pallavit** [comment]
This is exposed via #5029

**Comment by NTaylorMullen** [comment]
@pallavit Question, this seems to only be exposed in netstandard1.5. Is there a reason this can't also be exposed for netstandard1.0 and netstandard1.3?

**Comment by weshaggard** [comment]
It cannot be exposed in an earlier netstandard because some of the platforms that target those do not support it (i.e. WP, UWP).

**Comment by NTaylorMullen** [comment]
Ah, I see. Thanks @weshaggard
