### ISSUE TITLE
ComputeSignature on Linux : OpenSslCryptographicException: error:04075093:rsa routines:RSA_sign:value missing

### ISSUE THREAD

**Issue by xav-stargate** [dotnet/corefx#41466]
Hi,

I would like to know why my code work on Windows and not on Linux.

```
private void SignManifestFile(PassGeneratorRequest request)
{

            Trace.TraceInformation("Signing the manifest file...");

            try
            {

                ContentInfo contentInfo = new ContentInfo(manifestFile);

                SignedCms signing = new SignedCms(contentInfo, true);

                CmsSigner signer = new CmsSigner(SubjectIdentifierType.SubjectKeyIdentifier, passCert)
                {
                    IncludeOption = X509IncludeOption.None
                };

                Trace.TraceInformation("Fetching Apple Certificate for signing..");
                Trace.TraceInformation("Constructing the certificate chain..");
                signer.Certificates.Add(appleCert);
                signer.Certificates.Add(passCert);

                signer.SignedAttributes.Add(new Pkcs9SigningTime());

                Trace.TraceInformation("Processing the signature..");
                signing.ComputeSignature(signer); //< ----------- EXCEPTION

                signatureFile = signing.Encode();

                Trace.TraceInformation("The file has been successfully signed!");
            }
            catch (Exception exp)
            {
                Trace.TraceError("Failed to sign the manifest file: [{0}]", exp.Message);
                throw new ManifestSigningException("Failed to sign manifest", exp);
            }
}
```
```
Error :
>  ---> Interop+Crypto+OpenSslCryptographicException: error:04075093:rsa routines:RSA_sign:value missing
>    at System.Security.Cryptography.RSAOpenSsl.TrySignHash(ReadOnlySpan`1 hash, Span`1 destination, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding, Boolean allocateSignature, Int32& bytesWritten, Byte[]& signature)
>    at System.Security.Cryptography.RSAOpenSsl.TrySignHash(ReadOnlySpan`1 hash, Span`1 destination, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding, Int32& bytesWritten)
>    at System.Security.Cryptography.Pkcs.CmsSignature.RSAPkcs1CmsSignature.Sign(ReadOnlySpan`1 dataHash, HashAlgorithmName hashAlgorithmName, X509Certificate2 certificate, Boolean silent, Oid& signatureAlgorithm, Byte[]& signatureValue)
>    at System.Security.Cryptography.Pkcs.CmsSignature.Sign(ReadOnlySpan`1 dataHash, HashAlgorithmName hashAlgorithmName, X509Certificate2 certificate, Boolean silent, Oid& oid, ReadOnlyMemory`1& signatureValue)
>    at System.Security.Cryptography.Pkcs.CmsSigner.Sign(ReadOnlyMemory`1 data, String contentTypeOid, Boolean silent, X509Certificate2Collection& chainCerts)
>    at System.Security.Cryptography.Pkcs.SignedCms.ComputeSignature(CmsSigner signer, Boolean silent)
>    at Avomark.VirtualWallet.ApplePay.PassGenerator.SignManifestFile(PassGeneratorRequest request)
```
Ubuntu 16.04
Net core : 2.2.402

Thanks everyone :)

[@danmosemsft added formatting]

**Comment by bartonjs** [comment]
Most likely, it means that `passCert.HasPrivateKey` was `false` on Linux.

* That error means RSA.TrySignHash was called on an RSA key with no private key
* Since you didn't pass an explicit private key object, the key we call Sign on is cert.GetRSAPrivateKey()
* If GetRSAPrivateKey returns `null`, we fall back to GetRSAPublicKey, just so we can get the "there's no private key here" exception message -- for compatibility with what we did in .NET Framework (but perhaps we could use a better message here).

Since you got that error, it seems like GetRSAPrivateKey() returned null, but GetRSAPublicKey() didn't, so it's an RSA certificate with no private key.  So the further root cause depends on how you actually got `passCert`.

**Comment by xav-stargate** [comment]
The `passCert` is loaded from a store (on Windows and Linux), could that explain why there is no private key ?

```
X509Store store = new X509Store(StoreName.CertificateAuthority, StoreLocation.LocalMachine);
store.Open(OpenFlags.ReadOnly);
X509Certificate2Collection certCollection = store.Certificates;
X509Certificate2Collection currentCerts = certCollection.Find(X509FindType.FindByThumbprint, thumbprint,  false);
```

**Comment by bartonjs** [comment]
> The passCert is loaded from a store (on Windows and Linux), could that explain why there is no private key ?

Certs can certainly be in the store with no associated private key.  Loading from the store won't _lose_ the key, but it also won't magically find one if it didn't already know about it.

**Comment by xav-stargate** [comment]
I've added my certificate following these steps :
* Go to /usr/local/share/ca-certificates/
* Create a new folder, i.e. "sudo mkdir school"
* Copy the .crt file into a folder
* Permissions  (755 for the folder, 644 for the file)
* Run "sudo update-ca-certificates"

I just read that a _crt_ file can not contain a private key!
Do you have a solution for add a certificate and a private key (p12 file) to a store on ubuntu ?

**Comment by bartonjs** [comment]
```C#
using (X509Store store = new X509Store(StoreName.My, StoreLocation.CurrentUser))
{
    store.Open(OpenFlags.ReadWrite);
    store.Add(new X509Certificate2("file.p12", password, X509StorageFlags.PersistKeySet));
}
```

Is the only supported way to add a cert to a store.

Of course, you could just load the file from the .p12 and skip the store altogether (without PersistKeySet).

**Comment by xav-stargate** [comment]
Thanks!

**Comment by alizainal-abidin** [comment]
Hi @xav-stargate,

May I know your workaround for this? I recently got the same error when using _dotnet-passbook_ which runs on docker (linux image).

I've tried to add this but have had no success..
https://github.com/dotnet/corefx/issues/41466#issuecomment-540235768

Many thanks!!
