### ISSUE TITLE
JsonSerializer cant Deserialize dynamic objects

### ISSUE THREAD

**Issue by ghost1372** [dotnet/corefx#41472]
hi I hope this is a good place to ask this question
It seems we can't deserialize dynamic objects
i used this code but not worked is there any way to do this?
```
var objList = System.Text.Json.JsonSerializer.Deserialize<List<dynamic>>(json);
```

**Comment by steveharter** [comment]
Duplicate of issue https://github.com/dotnet/corefx/issues/38007
