### ISSUE TITLE
Consider throwing a meaningful error if the serializer is asked to serialize a `Task` 

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#41508]
Consider

```C#
var value = SomeAsyncFunc(); // This returns Task<SomeModel>
var json = JsonSerializer.Serialize(value);
```

This currently throws the following error:

```C#
An unhandled exception occurred while processing the request.JsonSerializationException: Self referencing loop detected for property 'task' with type 'System.Runtime.CompilerServices.AsyncTaskMethodBuilder 1+AsyncStateMachineBox 1 [System.Collections.Generic.List 1[XXXX.Models.YYY],System.Runtime.CompilerServices.IAsyncStateMachine]'. Path 'stateMachine.<>t__builder'. Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
```

It's almost always an indication of a non-awaited task if it's passed in to the serializer. Could this throw a more meaningful error up front if this is detected? See https://github.com/aspnet/AspNetCore/issues/13272 for previous discussions on this.

**Comment by steveharter** [comment]
I believe you intended to create a [Newtsonsoft ](https://github.com/JamesNK/Newtonsoft.Json) issue.

The error contains "Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference" and does not repro on System.Text.Json.
