### ISSUE TITLE
HttpClient.GetAsync causes the subsequent async method to deadlock

### ISSUE THREAD

**Issue by tangsaidi** [dotnet/corefx#41503]
After I've obtained the result from a `GetAsync()` method, when I try to call `await` on another async method, the program deadlocks for no apparent reason. I suspect it's caused by some side effects introduced by the `HttpClient`, because the program completes as expected when I replace the `GetAsync()` with a fake IO bound operation. 

Would someone help me with how did a deadlock happen? And is this a bug with the `System.Net.Http` library?

System.Net.Http Version (Deadlocks)
```
public static class DeadLock
{
    static DeadLock()
    {
        // should not block async method in general
        // but static constructor cannot be async
        int result = Setup().Result;
    }
    private static async Task<int> Setup()
    {
        string project = await GetProjects();

        Console.WriteLine("Project retrieved ");
        Console.WriteLine(project);

        Task<int> simpleRequest = DoNothing(); // The program deadlocks here

        Console.WriteLine("Projects dispatched");
        return 0;
    }
    private static async Task<string> GetProjects()
    {
        HttpClient httpClient = new HttpClient();
        await httpClient.GetAsync("https://www.zazzle.com");
        return "Project A";
    }
    private static async Task<int> DoSomething() {
        Thread.Sleep(2000);
        return 0;
    }
    private static async Task<int> DoNothing() { return 0;}
    public static string Talk() { return "Hi"; }
}

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("Done " + DeadLock.Talk());
        Console.ReadLine();
    }
}
```

Fake IO-bound operation (Completes)
```
public static class DeadLock
{
    static DeadLock()
    {
        int result = Setup().Result;
    }
    private static async Task<int> Setup()
    {
        string project = await GetProjects();

        Console.WriteLine("Project retrieved ");
        Console.WriteLine(project);

        Task<int> simpleRequest = DoNothing();

        Console.WriteLine("Projects dispatched");
        return 0;
    }
    private static async Task<string> GetProjects()
    {
        await DoSomething();
        return "Project A";
    }
    private static async Task<int> DoSomething() {
        Thread.Sleep(2000);
        return 0;
    }
    private static async Task<int> DoNothing() { return 0;}
    public static string Talk() { return "Hi"; }
}

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("Done " + DeadLock.Talk());
        Console.ReadLine();
    }
}
```

The expected output is:
```
Project retrieved
Project A
Projects dispatched
Done Hi
```
Whereas the version with HttpClient gives me
```
Project retrieved
Project A
```
And it hangs ...

Environment
IDE: Microsoft Visual Studio Professional 2017 Version 15.9.14
OS: Windows Server 2019 Standard
Cores: 16

supportedRuntime version="v4.0" 
sku=".NETFramework,Version=v4.6.1"

Thanks you!

**Comment by stephentoub** [comment]
This doesn't actually have anything to do with HttpClient.  It's entirely to do with blocking inside of a static cctor waiting for another thread to do something: if that other thread ends up needing to touch the class, the runtime will deadlock because it'll require the static cctor to have been completed, but it won't complete until this operation completes.

You can see this in your "Fake IO-bound operation" by actually introducing asynchrony, e.g. change `Thread.Sleep(2000);` to `await Task.Delay(2000);`.

**Comment by tangsaidi** [comment]
Thank you for the reply! Introduction of actual asynchronous operation does recreate the deadlock situation. 

It's still unclear to me where exactly did I touch the class in the second thread. It would make sense if the program deadlocks when the first `GetProjects()` is called, because `GetProjects()` is a static class method. But it actually passes this line and successfully returns, and it only deadlocks when the second `DoNothing()` call is fired.

I'm new to C#, my apologies if this is the wrong place to ask this question.

**Comment by stephentoub** [comment]
> It's still unclear to me where exactly did I touch the class in the second thread

It's happening from the static call to DoNothing.  That's a static method on this Deadlock class, and invoked from the asynchronous continuation from awaiting on GetProjects, so the continuation runs on some thread, prints out some stuff, and then invokes the static DoNothing method, which requires that the static cctor have been run, but the static cctor is blocked waiting for this operation to complete, and it deadlocks.  If you attach a debugger when it's hung, you can see this by looking at the call stacks, e.g. here's the Parallel Stacks view in VS:

![image](https://user-images.githubusercontent.com/2642209/66078284-b6867700-e52f-11e9-9c22-9fdd0ecaa390.png)
