### ISSUE TITLE
Inconsistent floating-point parsing exceptions

### ISSUE THREAD

**Issue by erandis-vol** [dotnet/corefx#41505]
Per the documentation the following should throw an OverflowException when using Single.Parse and Double.Parse:

```csharp
Single.Parse("-3.40282347E+39");
Single.Parse("3.40282347E+39");
Double.Parse("-1.7976931348623157E+309");
Double.Parse("1.7976931348623157E+309");
```

As expected, an exception is thrown on .NET Framework. On .NET Core 3.0.100 I am instead getting +/-Infinity.

**Comment by Wraith2** [comment]
It's likely to be due to this https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/
/cc @tannergooding for good measure

**Comment by vcsjones** [comment]
Yes, looks very similar to https://github.com/dotnet/corefx/issues/39296#issuecomment-509382614.

**Comment by tannergooding** [comment]
Yes, this is known and by-design. It is listed as part of the breaking changes for 2.2 to 3.0: https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.0#floating-point-formatting-and-parsing-behavior-changed
