### ISSUE TITLE
[System.Text.Json] Add Utf8JsonReader.SetState(...) method to improve custom converters performance

### ISSUE THREAD

**Issue by Groxan** [dotnet/corefx#41510]
I suggest adding the `Utf8JsonReader.SetState(JsonReaderState state)` method that allows you to set the reader state to any of the previous states so that you can read the JSON token, go back and read it again. This is a very useful feature especially when you are working with a custom `JsonConverter`.

---

Let's look at an example.

### What we have

Imagine, we have the following models:

````cs
interface IDevice
{
    string Kind { get; }
}

class Phone : IDevice
{
    public string Kind => "phone";

    public string Model { get; set; }
    public string Number { get; set; }
}

class Laptop : IDevice
{
    public string Kind => "laptop";

    public string Model { get; set; }
    public string Processor { get; set; }
}
````

### What we want

And we want to deserialize the following JSON to `List<IDevice>`:

````json
[
  {
    "kind": "phone",
    "model": "oneplus",
    "number": "123456789"
  },
  {
    "kind": "laptop",
    "model": "lenovo",
    "processor": "core i7"
  }
]
````

### What we have to do

To do this, we create our own `JsonConverter<IDevice>`, and if we want to achieve maximum performance, we do it like this:

````cs
class FastCustomConverter : JsonConverter<IDevice>
{
    public override IDevice Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        reader.Read();
        reader.Read();

        if (reader.ValueTextEquals("phone"))
        {
            var phone = new Phone();

            reader.Read();
            reader.Read();
            phone.Model = reader.GetString();

            reader.Read();
            reader.Read();
            phone.Number = reader.GetString();

            reader.Read();
            return phone;
        }
        else if (reader.ValueTextEquals("laptop"))
        {
            var laptop = new Laptop();

            reader.Read();
            reader.Read();
            laptop.Model = reader.GetString();

            reader.Read();
            reader.Read();
            laptop.Processor = reader.GetString();

            reader.Read();
            return laptop;
        }
        else
        {
            throw new JsonException();
        }
    }

    public override void Write(Utf8JsonWriter writer, IDevice value, JsonSerializerOptions options)
    {
        throw new NotImplementedException();
    }
}
````
And it works! Moreover, it works amazingly, and the performance is awesome in comparison with Newtonsoft.Json. But...

### What's wrong

But sometimes (in fact almost always) we prefer to have well-readable code instead of maximum performance. Do you agree that writing such a converter for complex types with a large number of nested objects, to put it mildly, is a headache?

### What we want to do

So, we want to do it as follows:

````cs
class ReadableCustomConverter : JsonConverter<IDevice>
{
    public override IDevice Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var root = JsonDocument.ParseValue(ref reader).RootElement;

        return root.GetProperty("kind").GetString() switch
        {
            "phone" => JsonSerializer.Deserialize<Phone>(root.GetRawText()),
            "laptop" => JsonSerializer.Deserialize<Laptop>(root.GetRawText()),
            _ => throw new JsonException()
        };
    }

    public override void Write(Utf8JsonWriter writer, IDevice value, JsonSerializerOptions options)
    {
        throw new NotImplementedException();
    }
}
````

### What's wrong

This also works, but much slower (~3 times slower). Obviously, we have a big overhead since we parse JSON to `JsonDocument` then convert it to raw string and then deserialize it to a specific type. Pretty dumb...

The problem is that we cannot just read the `"kind"` value to determine the correct type for deserialization, and then deserialize it, because the reader position is no longer at the beginning of the object.

### Solution

That's why I suggest adding a function to change the position (state) of the reader, so we can create our own converter as follows:

````cs
class ReadableJsonConverter : JsonConverter<IDevice>
{
    public override IDevice Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        // remember where is the beginning of the object
        var initial = reader.CurrentState;

        // find out the desired type
        reader.Read();
        reader.Read();
        var kind = reader.GetString();

        // return to the beginning of the object
        reader.SetState(initial); //                <---------- that's what I suggest

        // deserialize the object to the desired type
        return kind switch
        {
            "phone" => JsonSerializer.Deserialize<Phone>(ref reader),
            "laptop" => JsonSerializer.Deserialize<Laptop>(ref reader),
            _ => throw new JsonException()
        };
    }

    public override void Write(Utf8JsonWriter writer, IDevice value, JsonSerializerOptions options)
    {
        throw new NotImplementedException();
    }
}
````

Pretty short code and minimal overhead.

---

Unfortunately, this is a fairly common case when people have to work with JSON arrays of objects of different types, and it would be great to have an effective mechanism to handle this.

**Comment by pekkah** [comment]
If Utf8JsonReader is a struct can't you just pass it without the ref to another method and read there until you find the type return it and continue reading with the original reade from the original position? This would cause the struct to be copied to called method argument and not change the original?
