### ISSUE TITLE
GetAllNetworkInterfaces issues on Linux

### ISSUE THREAD

**Issue by wfurt** [dotnet/corefx#41515]
I did recently more testing with `GetAllNetworkInterfaces` on Linux and there is number of issues:

1. Following fragments _always_ throw on Linux. (works on OSX and Windows)
```c#
foreach (NetworkInterface n in list)
{
    Console.WriteLine("Interafce {0}: {1} {2}", n.Name, n.Speed, n.OperationalStatus);
}
```

This because code trying to get speed does not understand that some interfaces like `lo` loopback may not have a speed. On Windows we return -1. (thanks @ManickaP)
Even if Speed is not accessed we always throw internally and creating and catching exception is causing performance degradation. 

2. Implementation is based on address callbacks. We can miss interfaces without address.

```
$ip link
242: tun0: <POINTOPOINT,MULTICAST,NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 500
    link/none
243: tap0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether ea:86:ec:53:b3:c2 brd ff:ff:ff:ff:ff:ff
```
From pair tun/tap  only tap is visible in `GetAllNetworkInterfaces`. This could happen on other tunneling or point2point interfaces as well. 

3. accessing IsReceiveOnly will always throw.
Since Linux does not have concept of OnlyReceaving we should return `false` IMHO. 

4. GetIPProperties().GetIPv6Properties().GetScopeId() will always throw. 
Linux uses interface index for scopeId. We should use it as needed instead of throwing.  

I think in general we should not throw when accessing properties and we should return reasonable default (like -1 for speed on Windows)

**Comment by karelz** [comment]
@wfurt this should be fixed ... can you please double-check?
