### ISSUE TITLE
MemoryMappedFile Race Condition

### ISSUE THREAD

**Issue by sotheanith** [dotnet/corefx#41517]
I am trying to use MemoryMappedFile so that multiple threads in my application can read from the same file. The problem occurs when I run this code to try to access the same file in quick succession.
```MemoryMappedFile.CreateFromFile(FilePath);```
I attempt to fix this problem by using OpenExisting() method and named a memory when I use CreateFromFile(). 

```    
try
{
    MemoryMappedViewStream mmvs = MemoryMappedFile.OpenExisting(Path.GetFullPath(FilePath).GetHashCode().ToString()).CreateViewStream();
}
catch (FileNotFoundException)
{
    MemoryMappedViewStream mmvs = MemoryMappedFile.CreateFromFile(FilePath, System.IO.FileMode.Open, Path.GetFullPath(FilePath).GetHashCode().ToString()).CreateViewStream();
}
```

The solution above works well for windows os. However, since, other os doesn't support naming of a memory block, can someone offers insight on how to solve the original problem?

**Comment by the-exodus** [comment]
> I am trying to use MemoryMappedFile so that multiple threads in my application can read from the same file. The problem occurs when I run this code to try to access the same file in quick succession.
> `MemoryMappedFile.CreateFromFile(FilePath);`
> I attempt to fix this problem by using OpenExisting() method and named a memory when I use CreateFromFile().
> 
> ```
> try
> {
>     MemoryMappedViewStream mmvs = MemoryMappedFile.OpenExisting(Path.GetFullPath(FilePath).GetHashCode().ToString()).CreateViewStream();
> }
> catch (FileNotFoundException)
> {
>     MemoryMappedViewStream mmvs = MemoryMappedFile.CreateFromFile(FilePath, System.IO.FileMode.Open, Path.GetFullPath(FilePath).GetHashCode().ToString()).CreateViewStream();
> }
> ```
> 
> The solution above works well for windows os. However, since, other os doesn't support naming of a memory block, can someone offers insight on how to solve the original problem?

Actually, all the threads in a process share the same adress space. Once ONE thread maps a view of the file to an address, all the other threads in that process can access it there. That requires synchronization of course, so only one thread at a time writes to it. You can create multiple views of the same MemoryMappedFile-instance, if you want to have one per thread for some reason, but you do _not_ want to create multiple filemappings for the same file and especially not in the same process 

And most operating systems can create named objects. Windows uses the FileMapping-object, while most unixlikes use /dev/shm to reserve and share memory sections.

Anyway, I digress. You seem to have misunderstood the way memory mapped files work in Windows (and in .NET), and possibly processes/threads. Create a single MemoryMappedFile, and then get as many ViewAccessors as you need. Or just use a ConcurrentDictionary (or whatever storage suits you) if you just need intra-process.

And just so I have said it; there's no race condition. You're having multiple threads doing quite heavy stuff without any synchronization, that wouldn't work even if you did :)

WallOfText.EOS == true.

**Comment by sotheanith** [comment]
> > I am trying to use MemoryMappedFile so that multiple threads in my application can read from the same file. The problem occurs when I run this code to try to access the same file in quick succession.
> > `MemoryMappedFile.CreateFromFile(FilePath);`
> > I attempt to fix this problem by using OpenExisting() method and named a memory when I use CreateFromFile().
> > ```
> > try
> > {
> >     MemoryMappedViewStream mmvs = MemoryMappedFile.OpenExisting(Path.GetFullPath(FilePath).GetHashCode().ToString()).CreateViewStream();
> > }
> > catch (FileNotFoundException)
> > {
> >     MemoryMappedViewStream mmvs = MemoryMappedFile.CreateFromFile(FilePath, System.IO.FileMode.Open, Path.GetFullPath(FilePath).GetHashCode().ToString()).CreateViewStream();
> > }
> > ```
> > 
> > 
> > The solution above works well for windows os. However, since, other os doesn't support naming of a memory block, can someone offers insight on how to solve the original problem?
> 
> Actually, all the threads in a process share the same adress space. Once ONE thread maps a view of the file to an address, all the other threads in that process can access it there. That requires synchronization of course, so only one thread at a time writes to it. You can create multiple views of the same MemoryMappedFile-instance, if you want to have one per thread for some reason, but you do _not_ want to create multiple filemappings for the same file and especially not in the same process
> 
> And most operating systems can create named objects. Windows uses the FileMapping-object, while most unixlikes use /dev/shm to reserve and share memory sections.
> 
> Anyway, I digress. You seem to have misunderstood the way memory mapped files work in Windows (and in .NET), and possibly processes/threads. Create a single MemoryMappedFile, and then get as many ViewAccessors as you need. Or just use a ConcurrentDictionary (or whatever storage suits you) if you just need intra-process.
> 
> And just so I have said it; there's no race condition. You're having multiple threads doing quite heavy stuff without any synchronization, that wouldn't work even if you did :)
> 
> WallOfText.EOS == true.

This is the solution.
