### ISSUE TITLE
memory leak by TaskDelay inside a loop

### ISSUE THREAD

**Issue by JanEggers** [dotnet/corefx#41525]
this is the issue I try to figure out:

https://github.com/chkr1011/MQTTnet/issues/767

is it possible that task.delay is leaking memory if used inside a longrunning loop?

I know that the aspnet team invented this:
https://github.com/aspnet/AspNetCore/blob/3cd5054eb5d8851b25881cd05cccb931aaa022e6/src/SignalR/common/Shared/TimerAwaitable.cs

but there are no docs on that type and there are no hints on msdn that you should not use Task.delay inside loops

**Comment by Wraith2** [comment]
With your dump you might be able to use the sos tools to identify the GCRoot of all those allocations, see https://github.com/dotnet/coreclr/issues/26386 for some guidance on this.

**Comment by JanEggers** [comment]
@Wraith2 thx for the tip, I used Visual Studio, and after some digging I found the Issue, Its code that is no longer used so I just need to upgrade the library.

this caused the issue:
https://github.com/chkr1011/MQTTnet/blob/2918be18c6c6529584cd1d78e09ebb3fc0819e4f/Source/MQTTnet/Internal/AsyncAutoResetEvent.cs#L85
