### ISSUE TITLE
Collect EventSource logs in CI system

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#4152]
In order to help with investigations related to native failures we should have a way to collect the following from the CI system when a test fails:
1. Full-memory dumps + symbols [edit: covered by #14093]
2. EventSource traces

System.Net defines EventSource (ETW) tracing for both production and test code:
`*Microsoft-System-Net-Debug`
`*Microsoft-System-Net-TestLogging`

To investigate issues such as #4037 I would need to enable collection for these two sources as well as memory dump collection.

**Comment by weshaggard** [comment]
cc @Chrisboh @markwilkie

**Comment by ellismg** [comment]
Related: We should be capturing dumps on Linux and OSX when segfaults happen.

**Comment by mellinoe** [comment]
@danmosemsft @markwilkie Are we addressing this for our Helix and Jenkins runs?

**Comment by danmosemsft** [comment]
@sepidehMS is currently working on enabling @schaabs 's Dumpling service.

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/issues/14093 is that part

**Comment by weshaggard** [comment]
We are now capturing dumps on linux machines which I think covers this issue, so closing. If there are more things we need then we should open them separately.
