### ISSUE TITLE
Consolidate SafeSocketHandle / InnerSocketCloseHandle

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#41551]
Socket's safe handle is actually two layers of safe handles: SafeSocketHandle, which is the one exposed to the rest of the implementation (and publicly), and then InnerSocketCloseHandle, which actually owns the handle / file descriptor and which is wrapped by SafeSocketHandle.

This layering should no longer be necessary, adds a lot of complication to the implementation, and makes creating sockets more expensive (two SafeHandles for each instead of one).

We should look at merging InnerSocketCloseHandle back into SafeSocketHandle.

**Comment by stephentoub** [comment]
cc: @tmds, in case you're interested

**Comment by wfurt** [comment]
> This layering should no longer be necessary

what was original motivation for this split @stephentoub @geoffkizer

**Comment by stephentoub** [comment]
I'm not 100% sure, but I believe it was done to enable closing the underlying handle while synchronous operations were in flight (Dispose on a SafeHandle won't take effect until all add-refs have been released). That should no longer be an issue, as (as of @tmds' fixes) we now cancel all pending operations and prevent new ones from starting. If there was another motivation, I suspect it was either misguided or based on some other limitation that has since been removed. I could of course be wrong, but this is a very non-standard, and complex and relatively expensive, approach without current clear motivation.

**Comment by geoffkizer** [comment]
> I believe it was done to enable closing the underlying handle while synchronous operations were in flight

That's my understanding too.

**Comment by tmds** [comment]
With the two handles, one is the public facing. When it has been disposed and released, the internal one does the actual close (`InnerSafeCloseSocket.ReleaseHandle`).
If we remove the `InnerSafeCloseSocket`, those operations will need to change to use a raw handle ptr.

**Comment by stephentoub** [comment]
> those operations will need to change to use a raw handle ptr

The operations inside the SafeHandle? Yes.

**Comment by tmds** [comment]
@stephentoub you can assign this to me.

**Comment by stephentoub** [comment]
Awesome.
