### ISSUE TITLE
RSA.ImportRSAPublicKey in .Net Core 3 not working

### ISSUE THREAD

**Issue by tracker1** [dotnet/corefx#41563]
I'm trying to initialize an RSA instance via `ImportRSAPublicKey` and I'm getting an `ASN1 corrupted data.` error.

Simple case:
```
var r1 = RSA.Create();
var base = new RSACryptoServiceProvider(4096);

// throws
r1.ImportRSAPublicKey(base.ExportSubjectPublicKeyInfo(), out _);

// what I want/need
return new RsaSecurityKey(r1);
```

Version Info reference:
```
#region Assembly System.Security.Cryptography.Algorithms, Version=4.3.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// C:\Program Files (x86)\dotnet\packs\Microsoft.NETCore.App.Ref\3.0.0\ref\netcoreapp3.0\System.Security.Cryptography.Algorithms.dll
#endregion
```

Do I need to do some other conversion first?

**Comment by tracker1** [comment]
The example above is contrived, as I would expect the immediately exported value to be able to import right away again.

**Comment by vcsjones** [comment]
It looks like you are mixing the expected formats up. You are exporting with `ExportSubjectPublicKeyInfo` which exports a SPKI, but importing with `ImportRSAPublicKey` which is expecting the key to be in PKCS#1 format.

If you import with `ImportSubjectPublicKeyInfo`, then it works as expected:

```csharp
var r1 = RSA.Create();
var @base = new RSACryptoServiceProvider(4096);

r1.ImportSubjectPublicKeyInfo(@base.ExportSubjectPublicKeyInfo(), out _);
```

**Comment by vcsjones** [comment]
Likewise `ImportRSAPublicKey` should be paired with `ExportRSAPublicKey` if that is more preferable for you:

```csharp
r1.ImportRSAPublicKey(@base.ExportRSAPublicKey(), out _);
```

**Comment by bartonjs** [comment]
`ImportRSAPublicKey` imports the RSAPublicKey format from PKCS#1 (https://tools.ietf.org/html/rfc3447#appendix-A.1.1) (the PEM key format which starts with "BEGIN RSA PUBLIC KEY").  `ExportSubjectPublicKeyInfo` exports the key in the X.509 SubjectPublicKeyInfo format for RSA keys (the PEM key format which starts with "BEGIN PUBLIC KEY").

As @vcsjones mentioned, you need to match your export format and your import format.
