### ISSUE TITLE
JsonSerializer.Serialize(this) ignores derived class members

### ISSUE THREAD

**Issue by EdiWang** [dotnet/corefx#41573]
The following code produces results differently for System.Text.Json and Newtonsoft.Json

```csharp
class Program
{
    static void Main(string[] args)
    {
        var b = new PlayerA { Name = "I am Player A", Test = "Hello" };
        var blowJson = b.GetJson();
        var goodJson = b.GetNewtonsoftJson();
        
        Console.WriteLine(blowJson);
        // {}

        Console.WriteLine(goodJson);
        // {"Name":"I am Player A","Test":"Hello"}
    }
}

public class JsonablePlayer
{
    public string GetJson()
    {
        return System.Text.Json.JsonSerializer.Serialize(this);
    }

    public string GetNewtonsoftJson()
    {
        return Newtonsoft.Json.JsonConvert.SerializeObject(this);
    }
}

class PlayerA : JsonablePlayer
{
    public string Name { get; set; }
    public string Test { get; set; }
}
```

I am migrating Newtonsoft.Json to System.Text.Json. And this caused a bug in my system. 

My design was using this trick to serialize settings classes into database: https://github.com/EdiWang/Moonglade/blob/master/src/Moonglade.Configuration/BlogConfig.cs#L89

I put GetJson() method in a base class instead of in an Interface so that I don't have to implement the interface every time with the same code in every settings class

Base Class:
https://github.com/EdiWang/Moonglade/blob/master/src/Moonglade.Configuration/Abstraction/MoongladeSettings.cs

Example Settings Class:
https://github.com/EdiWang/Moonglade/blob/master/src/Moonglade.Configuration/GeneralSettings.cs.

It worked perfectly with Newtonsoft.Json. I wonder if there is a workaround for this in System.Text.Json?

**Comment by Tornhoof** [comment]
That's because the method you're invoking looks like this:
https://github.com/dotnet/corefx/blob/b00e9b036558a87c7f25ee59bde41e9b97d9b9a1/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.String.cs#L19-L22
and that one is using ``JsonablePlayer`` for TValue.

If you want the old behaviour take a look at:
https://github.com/dotnet/corefx/blob/b00e9b036558a87c7f25ee59bde41e9b97d9b9a1/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.String.cs#L35-L40
and pass in the real type, i.e. change your code to:
```csharp
    public string GetJson()
    {
        return System.Text.Json.JsonSerializer.Serialize(this, GetType());
    }
```

**Comment by Joe4evr** [comment]
For what it's worth, tightly coupling the serialization method to your data like this is pretty bad practice. The ideal design should allow one to swap out the serialization method with something else without needing to recompile the base data types.

**Comment by EdiWang** [comment]
Thanks @Tornhoof for the detailed explanation, GetType() works!

**Comment by EdiWang** [comment]
@Joe4evr Good point, separating the serialization method from model class makes perfect sense,I am going to change the design.

**Comment by paillave** [comment]
the workaround works for a simple type but how can we do with a list of item that all derive from a base class?
How can I have the following example working properly?

```csharp
namespace TestJson
{
    class Program
    {
        static void Main(string[] args)
        {
            var toSerialize =
                new[] {
                    new ClassBase
                    {
                        Value1 = "aze"
                    },
                    new NewClass2
                    {
                        Value1="qsd",
                        ShouldBeSerialized="why am I not serialized?"
                    }
                 };
            var textJsonSerialized = System.Text.Json.JsonSerializer.Serialize(toSerialize);
            // expecting [{"Value1":"aze"},{"ShouldBeSerialized":"why am not serialized?","Value1":"qsd"}]
            // but getting [{"Value1":"aze"},{"Value1":"qsd"}]
            Console.WriteLine(textJsonSerialized);

            var newtonSoftSerialized =  Newtonsoft.Json.JsonConvert.SerializeObject(toSerialize);
            // as expected getting [{"Value1":"aze"},{"ShouldBeSerialized":"why am not serialized?","Value1":"qsd"}]

            Console.WriteLine(newtonSoftSerialized);
        }
    }
    public class ClassBase
    {
        public string Value1 { get; set; }
    }
    public class NewClass2 : ClassBase
    {
        public string ShouldBeSerialized { get; set; }
    }
}
```
