### ISSUE TITLE
Q: How to work on System.Threading.Tasks and System.Threading?

### ISSUE THREAD

**Issue by Trapov** [dotnet/corefx#41575]
Currently almost all of the classes from `System.Threading.Tasks` and `System.Threading` namespaces are placed in [https://github.com/dotnet/corefx/tree/master/src/Common/src/CoreLib/System/Threading](https://github.com/dotnet/corefx/tree/master/src/Common/src/CoreLib/System/Threading) and they don't have any solutions to work with. How could I work on them and contribute? What's the dev/contributer-guide?

**Comment by stephentoub** [comment]
They're part of System.Private.CoreLib and are only mirrored to corefx as part of a source sharing approach. To work on them, you need to work on the dotnet/coreclr repo, and they are part of the CoreLib .sln there.

**Comment by Trapov** [comment]
Thank you, couldn't find them there at first but now I did.
