### ISSUE TITLE
Unable to use System.Management facilities on MacOs

### ISSUE THREAD

**Issue by godrose** [dotnet/corefx#41582]
Repro steps:

- Create a .NET Core 3.0 app test project (using SpecFlow and xUnit)
- Create a .NET Core 3.0 library project
- Use `System.Management`-related code within the library project

Expected: It just works (and it used to)
Actual: It doesn't (which is frustrating)

More info:
Error - System.PlatformNotSupportedException : System.Management currently is only supported for Windows desktop applications.
Env - MacOs latest, running from VS for Mac latest
Stack Trace - includes the code `ManagementObjectSearcher searcher = new ManagementObjectSearcher
                ("Select * From Win32_Process Where ParentProcessID=" + pid);`

It looks like this should have never worked but apparently it did...

**Comment by Gnbrkm41** [comment]
I don't understand what you're saying; the description of the namespace is `Provides access to a rich set of management information and management events about the system, devices, and applications instrumented to the Windows Management Instrumentation (WMI) infrastructure.`, the most important part being ***Windows*** Management Instrumentation. It relies on the WMI infrastructure that only Windows provides, which means it can't be supported on MacOS or any other non-Windows OSes.

What do you mean by "it just works and it used to"? it worked on Windows?

**Comment by godrose** [comment]
It works on Windows. It fails to do so on Mac. I remember it used to work with one of the preview versions.

**Comment by stephentoub** [comment]
> I remember it used to work with one of the preview versions.

This has never been implemented on Unix.

**Comment by godrose** [comment]
I see
