### ISSUE TITLE
Where are the unit tests for Systems.Collections.Generic?

### ISSUE THREAD

**Issue by lloydjatkinson** [dotnet/corefx#41592]
I've not been able to find the tests for any of the types in https://github.com/dotnet/corefx/tree/master/src/Common/src/CoreLib/System/Collections/Generic

System.Linq has tests in a directory called tests (e.g. https://github.com/dotnet/corefx/blob/master/src/System.Linq/tests/FirstTests.cs).

**Comment by Wraith2** [comment]
Try https://github.com/dotnet/corefx/tree/master/src/Common/tests/System/Collections

**Comment by stephentoub** [comment]
The test project is here:
https://github.com/dotnet/corefx/tree/master/src/System.Collections/tests
It includes files from the location @Wraith2 mentions.
