### ISSUE TITLE
DateTime.Date ToString() - .net core 2.2. - console/windowsservice differences

### ISSUE THREAD

**Issue by ftlsoft** [dotnet/corefx#41611]
# Issue Title

DateTime.Date ToString() - .net core 2.2. - console/windowsservice differences
# General

Hi, i`v found an issue with DateTime.Date in app runned as a console and as a windows service (Local System user)

Log:
As a console app:
2019/10/07 10:59:32.864|DEBUG|: DateTime.Now: 2019-10-07 10:59:32 DateTime.Now.Date: **2019-10-07 0:00:00** 
As a windows service:
2019/10/07 10:59:36.370|DEBUG|: DateTime.Now: 10/7/2019 10:59:36 AM DateTime.Now.Date: **10/7/2019 12:00:00 AM** 

Arythmethic operations are calulated ok (from the midnight), but returned time part is wrong
2019/10/07 10:59:36.372|DEBUG|: DateTime.Now.AddHours(-11): 10/6/2019 11:59:36 PM DateTime.Now.AddHours(-11).Date: **10/6/2019 12:00:00 AM** 

Both tests have:
2019/10/07 10:59:32.872|DEBUG|: CultureInfo.CurrentCulture: en-US 
2019/10/07 10:59:32.872|DEBUG|: TimeZoneInfo.Local.GetUtcOffset(02:00:00)

**Comment by Clockwork-Muse** [comment]
Side note: `DateTime.Now` may not be what you want.  Among other things, `DateTime.Now.AddHours(-11)` _will return results you likely don't expect around Daylight Savings Time_, because no BCL type is timezone aware; at `2019-11-02 23:00:00` the result will be `2019-11-03 10:00:00`, not `2019-11-03 09:00:00` as you probably want.

Note that, in a number of timezones, midnight (`00:00:00`/`12:00:00AM`) is the change point for DST, so `DateTime.Now.Date` may be an invalid or ambiguous value.

**Comment by tarekgh** [comment]
I think @ftlsoft  is just confused about what is the expect behavior. Here is some clarification. 

- When calling DateTime.Date, it strip the time value and reset it to 0 which would be 12:00 AM.
- When calling DateTime.ToString() it will print the DateTime parts that include the Date and the Time.
- Doing DateTime.Date.ToString will print whatever date stored inside the datetime and will print 12:00 AM as you did reset the time when did .Date.
- Doing DateTime.Now.AddHours(-11) will print the whole date and time without resetting the time to 12:00 AM as you didn't do .Date part. which will print something like ```1:59:36 PM``` according to what you have indicated.

Side point: 
Looks in your machine there is some difference in the date/time formatting patterns between the current user settings and local system settings. 
The local system settings would be the following which you can see it using regedit tool:

```
HKEY_USERS\S-1-5-18\Control Panel\International
    sShortDate       M/d/yyyy
    sTimeFormat    h:mm:ss tt
```

I think your current user setting would be 
    
```
    sShortDate       yyyy-MM-dd
    sTimeFormat    h:mm:ss
```

The time don't have the AM/PM designators which make the time not printed with AM//PM. 

I am going to close this issue, but feel free to send any question and we'll be happy to help you with.
