### ISSUE TITLE
Allow circular reference support for the new dotnet core 3 json api's

### ISSUE THREAD

**Issue by MaddoxDevelopment** [dotnet/corefx#41628]
The new System.Text.Json API's do not support ignoring circular references while serializing.
This is an issue because EF Core produces circular references by default when using navigation properties.

This results in an exception being thrown when you serialize a result set from EF Core.

**Comment by Jozkee** [comment]
Thank you for filing the issue but this is already being discussed in #41002, please make sure to make comments in there in case you have any.
