### ISSUE TITLE
Support for [JsonObject(MemberSerialization.OptIn)] attribute

### ISSUE THREAD

**Issue by cedemax** [dotnet/corefx#41633]
Newtonsoft.Json supports a convenient way to serialize certain types of classes using attributes only, by specifying the [JsonObject(MemberSerialization.OptIn)] attribute on the class, and then picking the desired properties to serialize using the [JsonProperty] attribute on the. This does not seem to be supported yet?

Is there a viable workaround other than writing custom converters for all those classes?

**Comment by Symbai** [comment]
Dupe of #39277

**Comment by ahsonkhan** [comment]
Closing as duplicate.
