### ISSUE TITLE
Http/2 support for HttpWebRequest

### ISSUE THREAD

**Issue by Varorbc** [dotnet/corefx#41645]
Http/2 has been supported in HttpClient. The underlying implementation of HttpWebRequest is HttpClient. However, HttpWebRequest does not support Http/2.

https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0/

![image](https://user-images.githubusercontent.com/5714438/66382556-052f8780-e9ee-11e9-852c-e704c516b1b9.png)

https://github.com/dotnet/corefx/blob/5ad15fcb189a9c232051d03c1e889f985f62232b/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs#L1156-L1243

https://github.com/dotnet/corefx/blob/5ad15fcb189a9c232051d03c1e889f985f62232b/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs#L816-L844

https://github.com/dotnet/corefx/blob/5ad15fcb189a9c232051d03c1e889f985f62232b/src/System.Net.HttpListener/src/System/Net/Windows/HttpListenerResponse.Windows.cs#L80-L97

**Comment by davidsh** [comment]
cc: @stephentoub 

Looks like some code changes were missed in HttpWebRequest.cs for .NET Core 3.0.  We simply have to allow HttpVersion.Version20 to be set.

**Comment by scalablecory** [comment]
This is a legacy class; the effort seems low here, but I wonder what the bar is for enhancements to `HttpWebRequest`.

**Comment by karelz** [comment]
Triage: Legacy API, we do not want people to encourage using it more. We want them to migrate to `HttpClient`.
If there is enough interest, we may take a PR. But we do not want to encourage anyone to submit PR without demonstration of business need and interest from a few customers at least.
