### ISSUE TITLE
API Proposal: Add pipe creation extension methods that take an ACL

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/corefx#41657]
### Summary

Similar to #41614, we don't currently have a way to create a pipe with a given ACL in .NET Core. We can modify the ACL, but it would be more secure to have the proper ACL on the pipe from the start.

The Pipe ACL `PipeSecurity` is already exposed in the `System.IO.Pipes` assembly , we should add creation extension methods to the existing `PipesAclExtensions`.

### Proposal

Add the following two creation methods to the existing `PipesAclExtensions` class in the `System.IO.Pipes` assembly:

``` C#
namespace System.IO.Pipes
{
    public static class PipesAclExtensions
    {
        // Add
        public AnonymousPipeServerStream CreateAnonymousPipeServerStream(
            this PipeSecurity pipeSecurity
            PipeDirection direction,
            HandleInheritability inheritability,
            int bufferSize);

        public NamedPipeServerStream CreateNamedPipeServerStream(
            this PipeSecurity pipeSecurity
            string pipeName,
            PipeDirection direction,
            int maxNumberOfServerInstances,
            PipeTransmissionMode transmissionMode,
            PipeOptions options,
            int inBufferSize,
            int outBufferSize,
            HandleInheritability inheritability = HandleInheritability.None,
            PipeAccessRights additionalAccessRights = default);

        // Existing
        public static PipeSecurity GetAccessControl(this PipeStream stream);
        public static void SetAccessControl(this PipeStream stream, PipeSecurity pipeSecurity);
    }
}
```

### Details

Since these are already in the same assembly as the modified types it should be pretty straight-forward to implement.

### Related Issues

#41614 API Proposal: Add file and directory creation methods that take an ACL

CC: @danmosemsft, @ericstj, @terrajobst

**Comment by terrajobst** [comment]
We should not make them extension methods. We should follow the other pattern and create new static types suffixed with `Acl`:

@JeremyKuhne: we need to update the ordering to match the existing APIs. Please update this comment.

```C#
namespace System.IO.Pipes
{
    public static class AnonymousPipeServerStreamAcl
    {
        public AnonymousPipeServerStream Create(
            PipeSecurity pipeSecurity
            PipeDirection direction,
            HandleInheritability inheritability,
            int bufferSize);
    }

    public static class NamedPipeServerStreamAcl
    {
        public NamedPipeServerStream Create(
            PipeSecurity pipeSecurity
            string pipeName,
            PipeDirection direction,
            int maxNumberOfServerInstances,
            PipeTransmissionMode transmissionMode,
            PipeOptions options,
            int inBufferSize,
            int outBufferSize,
            HandleInheritability inheritability = HandleInheritability.None,
            PipeAccessRights additionalAccessRights = default);
    }
}
```

**Comment by TonyValenti** [comment]
Definitely excited to see the work on this. Really looking forward to it being completed!

**Comment by carlossanlop** [comment]
Fixed with dotnet/runtime#317

**Comment by TonyValenti** [comment]
I'm super excited the work on this has been complete!  Do you have an ETA on a release date?

**Comment by carlossanlop** [comment]
@TonyValenti it's targeted for 5.0. You can always consume a nightly build or a preview to test these new APIs.
