### ISSUE TITLE
NullReferenceException in System.DirectoryServices.AccountManagement

### ISSUE THREAD

**Issue by Marusyk** [dotnet/corefx#41655]
In method `Save` from `Principal` class, the `context` object was used before it was verified against null:

https://github.com/dotnet/corefx/blob/7c586d32edce94c910fc8b402f4adedaa3cf05fd/src/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/Principal.cs#L340-L350

The null value for the context parameter is invalid and we are expecting InvalidOperationException.

This code will generate `NullReferenceException` when

```csharp
GroupPrincipal groupPrincipal 
  = new GroupPrincipal(new PrincipalContext(ContextType.Machine));
groupPrincipal.Save(null);
```
Context:
System.DirectoryServices.AccountManagement v4.6.0

**Comment by safern** [comment]
Fixed in: #41656
