### ISSUE TITLE
HTTP2: Drawbacks of setting HttpClient.Timeout = Timeout.InfiniteTimespan?

### ISSUE THREAD

**Issue by JamesNK** [dotnet/corefx#41650]
Query for HttpClient folks:

gRPC can have long running streaming calls. A streaming call might not return any response for over 100 seconds, which then triggers a cancellation based on `HttpClient.Timeout`.

I am considering setting `HttpClient.Timeout` to `Timeout.InfiniteTimespan` when the gRPC channel's internal HttpClient is created. What drawbacks to this that I should be aware of? Is this recommended?

Note: gRPC has its own mechanism for timeouts called [deadlines](https://grpc.io/blog/deadlines/). Deadline is the standardized way of limiting the duration of unresponsive gRPC calls. I would like developers to only think about setting a deadline and not think about it AND `HttpClient.Timeout`. There is no deadline by default.

**Comment by geoffkizer** [comment]
Seems like a reasonable thing to do.

**Comment by stephentoub** [comment]
There aren't really drawbacks other than the obvious one: you won't have timeouts.

There are actually optimizations that kick-in when the timeout is set to infinite.

And HttpClient is just one wrapper for the underlying handler; others like HttpMessageInvoker don't have a Timeout.

**Comment by JamesNK** [comment]
Thanks for the feedback. I've disabled HttpClient.Timeout in gRPC https://github.com/grpc/grpc-dotnet/pull/595
