### ISSUE TITLE
.Net Core 2.2 Memory

### ISSUE THREAD

**Issue by Alan-Lun** [dotnet/corefx#41669]
.Net Core 2.2 API
Memory
https://imgur.com/Gri252Z

.Net Core 2.2 Console 安裝 https://www.nuget.org/packages/Quartz/
Memory
https://imgur.com/sZ2KSuX

.Net Core 2.2 Razor Page 和 MVC
Memory
https://imgur.com/53J9bUg

我有設定 csproj ，Memory 上漲速度有減緩但依舊無法停止每天上漲的 Memory，都不會降下來
`
<ServerGarbageCollection>false</ServerGarbageCollection>
`

.Net Core 3.0 初始API 也有此狀況 , 記憶體不會下降到原本
https://imgur.com/lavFW6r

**Comment by danmosemsft** [comment]
translated:
===
.Net Core 2.2 API
Memory

https://imgur.com/Gri252Z
.Net Core 2.2 Console Installation https://www.nuget.org/packages/Quartz/
Memory

https://imgur.com/sZ2KSuX
.Net Core 2.2 Razor Page and MVC
Memory

https://imgur.com/53J9bUg
I've set csproj, Memory's rise has slowed down but still can't stop the daily rise of Memory, won't come down

<ServerGarbageCollection>false</ServerGarbageCollection> The .Net Core 3.0 initial API also has this condition, and memory does not drop to the original

**Comment by danmosemsft** [comment]
@Alan-Lun have you tried profiling to see where the memory is going? 

You can use one of these tools
* PerfView: https://github.com/Microsoft/perfview
* Visual Studio: https://docs.microsoft.com/en-us/visualstudio/profiling/memory-usage?view=vs-2019
* dotMemory

**Comment by Alan-Lun** [comment]
@danmosemsft 
有使用 Visual Studio，也有看dotMemory
但看不出來為什麼飆升
https://imgur.com/xJfcjpP

我看其他文章也有此問題
https://stackoverflow.com/questions/51388701/asp-net-core-memory-inscrease-on-every-request-and-gc-does-not-free-it

https://stackoverflow.com/questions/57591344/why-asp-net-core-2-2-do-not-release-memory

https://chat.stackoverflow.com/rooms/198268/discussion-on-question-by-kevin-tanudjaja-why-asp-net-core-2-2-do-not-release-me

https://github.com/aspnet/AspNetCore/issues/6102#issuecomment-479461130

**Comment by danmosemsft** [comment]
@Alan-Lun thanks. I did Bing translate again:
===
@danmosemsft
There's using Visual Studio, there's also watching dotMemory
But i don't see why it's soaring.

https://imgur.com/xJfcjpP I see other articles that also have this problem
===

@davidfowl any thoughts here?

**Comment by danmosemsft** [comment]
This is not actionable without a repro case or more details. Please reactivate if you have these.

**Comment by Alan-Lun** [comment]
@danmosemsft 那請問可以給我一個Email連結，可以讓我寄送一些目前專案上的，讓你們測試看看嗎
