### ISSUE TITLE
Load X509Certificate2 from raw : GetPrivateKey : keyset does not exist

### ISSUE THREAD

**Issue by xav-stargate** [dotnet/corefx#41676]
Hi

I use .NET Core 2.2 on Linux AND Windows, I do not want to use the stores. I try to add permissions to IIS or Everyone for test on "C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys" it does not work.. The file is created and I can open it ! But why my program can't do it ?

```
X509KeyStorageFlags flags = X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.Exportable;
X509Certificate2 cert = new X509Certificate2(rawCert, "myPassword", flags);

bool result = cert.HasPrivateKey(); // true
var pk =  cert.GetRSAPrivateKey(); // Exception
```

I get this exception :

> Internal.Cryptography.CryptoThrowHelper.WindowsCryptographicException HResult=0x80090016 Message=keyset does not exist
> Source=System.Security.Cryptography.Csp Arborescence des appels de procédure : at Internal.NativeCrypto.CapiHelper.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer) at System.Security.Cryptography.RSACryptoServiceProvider.get_SafeProvHandle() at System.Security.Cryptography.RSACryptoServiceProvider.get_SafeKeyHandle() at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 keySize, CspParameters parameters, Boolean useDefaultKeySize) at System.Security.Cryptography.RSACryptoServiceProvider..ctor(CspParameters parameters) at Internal.Cryptography.Pal.CertificatePal.<>c.b__66_0(CspParameters csp) at Internal.Cryptography.Pal.CertificatePal.GetPrivateKey[T](Func2
>   createCsp, Func2 createCng) at Internal.Cryptography.Pal.CertificatePal.GetRSAPrivateKey() at Internal.Cryptography.Pal.CertificateExtensionsCommon.GetPrivateKey[T](X509Certificate2 certificate, Predicate`1 matchesConstraints) at System.Security.Cryptography.X509Certificates.RSACertificateExtensions.GetRSAPrivateKey(X509Certificate2 certificate) at ConsoleTest.Program.Main(String[] args) in ...

I've so many problems with the certificate management..  
I've try to use the store, it's work on Windows but not on Linux... (https://github.com/dotnet/corefx/issues/41466#issuecomment-538544491). 
I just want get my private key, the same way on Windows as on Linux 

Thanks everyone

**Comment by bartonjs** [comment]
If that's really the entirety of the program that seems really weird.  Off the top of my head this would be something like your account has write access to `%ALLUSERSPROFILE%\Application Data\Microsoft\Crypto\SystemKeys` but doesn't have read access... so creating the private key file succeeds, but reading it back fails.

Are you running as an elevated account when you run this program?

**Comment by xav-stargate** [comment]
I have exactly the same error with and without elevation of rights

**Comment by bartonjs** [comment]
Next up is:

* Can you reproduce the problem on another computer?
  * If yes, can you reproduce the problem with a PFX you can share?
    * If yes, please share it and say what version of Windows you're using.
    * If no, we'll need to work something else out.
  * If no, can you reproduce the problem with a PFX whose key can be shared?
    * If yes, please record your execution under [Time Travel Debugging](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/time-travel-debugging-record) and we'll figure out what to do about the giant file.
    * If no, we'll need to work something else out.

You've hit what seems to be a unique problem.

**Comment by xav-stargate** [comment]
Sorry, you can close this issue ! 
My certificate isn't invalid :/
