### ISSUE TITLE
UriBuilder adds explicit port to Uri.OriginalString even if not present in original Uri

### ISSUE THREAD

**Issue by cmeeren** [dotnet/corefx#41679]
When passing a `Uri` to `UriBuilder`, the resulting `builder.Uri` has a different `OriginalString`. Specifically, the port has been added to `OriginalString` where it was not present originally.

```f#
open System
open System.Web

let uri = "http://example.com"
Uri(uri).OriginalString  // is "http://example.com"
UriBuilder(Uri(uri)).Uri.OriginalString  // is "http://example.com:80/"
```

This has implications e.g. for serialization of URIs. Newtonsoft.Json seems to use `Uri.OriginalString` when serializing URIs. This means that after having been through a `UriBuilder` (e.g. to add path segments), all my URIs come out with ports where they originally had none.

Note that a slash is also added.

This bug exists in at least .NET Core 3.0 and 2.2

**Comment by davidsh** [comment]
>This has implications e.g. for serialization of URIs. Newtonsoft.Json seems to use Uri.OriginalString when serializing URIs.

I'm pretty sure that .NET Framework behaves the same way here.

Not sure why .OriginalString is used here. That property is not recommended for most use cases of Uri because it is not a normalized representation of the URI.

@JamesNK Can you comment here?

**Comment by cmeeren** [comment]
For the record, I also created a related issue here: https://github.com/JamesNK/Newtonsoft.Json/issues/2190

**Comment by karelz** [comment]
Triage: Looks like it is compatible with .NET Framework and it is not recommended property to use (see https://github.com/dotnet/corefx/issues/41679#issuecomment-539992890). Closing.
