### ISSUE TITLE
Add deserialization tests for long input strings

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#41687]
To address https://github.com/dotnet/corefx/pull/41414#discussion_r330845194

The deserializer doesn't currently do any multiplication on the length, so this would be a preventative test.

**Comment by eugenesmlv** [comment]
Can I take this issue?

**Comment by steveharter** [comment]
Certainly.  See https://github.com/dotnet/corefx/pull/41414/commits/40499f9de38c02e1b49cb6cf9a1891052f3b98f4#diff-1cc85a982fd12de79abc65a090c75039L368 for example.

These tests need to run as outerloop as explained there.
