### ISSUE TITLE
ThreadLocal implementation does not match documentation

### ISSUE THREAD

**Issue by oznetmaster** [dotnet/corefx#41680]
The documentation for ThreadLocal states:

> If this instance was not previously initialized for the current thread, accessing Value will attempt to initialize it. If an initialization function was supplied during the construction, that initialization will happen by invoking the function to retrieve the initial value for Value. Otherwise, the default value will be used. If an exception is thrown, that exception is cached and thrown on each subsequent access of the property.

However, the current implementation appears to not cache the exception, and to reevaluate the initialization function on every access to Value.

Is the documentation incorrect, or is the implementation incorrect?

**Comment by stephentoub** [comment]
The documentation is incorrect.  It has never cached the exception in this manner. Thanks.
https://github.com/dotnet/dotnet-api-docs/pull/3316
