### ISSUE TITLE
Incorrect output double when formatting using format specifier G

### ISSUE THREAD

**Issue by Alex493049469** [dotnet/corefx#41697]
```
double d1 = (0.60000000000000009);
Console.WriteLine(d1.ToString("G"));

double d2 = (0.20000000000000001);
Console.WriteLine(d2.ToString("G"));
				
//.net 4.6.2
//0,6
//0,2

//.net Core 3.0
//0,6000000000000001
//0,2
```

**Comment by Wraith2** [comment]
It's probably intenetional caused by a known breaking change, see
https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.0#floating-point-formatting-and-parsing-behavior-changed

**Comment by ronnygunawan** [comment]
Possible duplicates:
#6405
https://github.com/dotnet/coreclr/issues/19596
