### ISSUE TITLE
Directory.GetFiles works on Win but not *nix

### ISSUE THREAD

**Issue by benmccallum** [dotnet/corefx#41700]
Hi team,

I'm trying to use a dotnet core global tool in a docker build process but getting caught up on the fact that this line of code works on Windows and finds the files, but in a Linux environment it doesn't seem to. 

    Directory.GetFiles(currentWorkingDirectory, "*.csproj", SearchOption.AllDirectories)

For the Windows docker image, I'm using `microsoft/dotnet:2.2-sdk-nanoserver-sac2016` and for the Linux one I'm trying to migrate to I'm using `mcr.microsoft.com/dotnet/core/sdk:2.2`.

I've done some searching online and can't find anything (official or otherwise) that would indicate what I'm trying to do is not supported on Linux, so I'm a bit stumped. Any help would be greatly appreciated.

Cheers,
Ben

**Comment by benmccallum** [comment]
Oh damn. Nevermind. Was logging it anticipating I would have issues again today but fresh eyes after a holiday and it's my own issue. Sorry!

**Comment by danmosemsft** [comment]
@benmccallum glad you figured it out! Note that 2.2 goes out of support in December: 
https://dotnet.microsoft.com/platform/support/policy/dotnet-core
