### ISSUE TITLE
Encoding UTF8 GetString behaving differently in .net core 3.0

### ISSUE THREAD

**Issue by AmarMovva** [dotnet/corefx#41714]
```
var encoding = new System.Text.UTF8Encoding();
var bytes = new Byte[] { 240, 142 };
```
//Outputs two null (?) UTF8 characters in .net core 3.0 but in .net core 2.2, .net 4.7.2 framework 
//returns only one null character
`encoding.GetString(bytes);`

Did something got changed with .net core 3.0.

**Comment by tarekgh** [comment]
@GrabYourPitchforks I marked this issue for 3.1 till we decide if we treat this change as a breaking change and document it or we'll need to fix it.

**Comment by GrabYourPitchforks** [comment]
This is already documented as an intentional breaking change. See https://github.com/dotnet/docs/issues/13547.

**Comment by tarekgh** [comment]
Closing this one per @GrabYourPitchforks comments as this is known breaking change. @AmarMovva feel free to respond back if you have more comments of questions. Thanks for reporting the issue.

**Comment by davidbuckleyni** [comment]
Hi I seem to be having the same issue in asp.net core 3.1 

`     List<Stock> _result = new List<Stock>();

      var uri = new Uri(string.Format(Constants.GetALlStock, string.Empty));
      var response = await _httpClient.GetAsync(uri);
       if (response.IsSuccessStatusCode)       {
                byteArray = await response.Content.ReadAsByteArrayAsync();
                var content = Encoding.UTF8.GetString(byteArray, 0, byteArray.Length);
                _result = JsonConvert.DeserializeObject<List<Stock>>(content);
            }
            return _result.ToList();`
Its not null as I can see the data in the byte array so why is this crashing in asp.net 3.1

**Comment by danmosemsft** [comment]
@davidbuckleyni could you please open a new issue in dotnet/runtime repo linked to this, and I will close this again? If there is a regression introduced in 3.x we will look promptly.

**Comment by GrabYourPitchforks** [comment]
No repro provided. Closing.
