### ISSUE TITLE
Incorrect branch distance calculation present in .NET core 3.0+

### ISSUE THREAD

**Issue by IntelOrca** [dotnet/corefx#41710]
Issue #26621 is still present in .NET core 3.0 onwards as the fix #28493 was not merged into the 3.0 source stream.

**Comment by jkotas** [comment]
cc @tmat

**Comment by tmat** [comment]
@mmitche @markwilkie Was release/2.1 not auto-merged to master and release/3.x?

**Comment by mmitche** [comment]
There is no auto-merge from release/2,x -> release/3 for the core* repos. I believe this was intentional given the large differences in those products.

Please port.

**Comment by jkotas** [comment]
The default workflow for runtime repos is: 
1. Submit the fix to master first
2. Cherry-pick the fix into release branches as necessary.

**Comment by tmat** [comment]
@mmitche @jkotas I'd expect changes release/2.1 to flow to master to avoid issues like this one. That's certainly standard flow in many other repos.

**Comment by tmat** [comment]
Should I now port it to release/3.x and also to master, or does release/3.x flow to master?

**Comment by jkotas** [comment]
release/3.1 does not flow to master. Get it to master first. Once it is in master, submit a back port PR and follow the servicing process for this. (I would port it to 3.1 only. 3.0 is a very short-lived release.)

**Comment by tmat** [comment]
What's the rationale behind not flowing 3.1 to master? This process is just adding unnecessary work and is error prone.

**Comment by jkotas** [comment]
Due to high churn in coreclr/corefx, flowing 3.1 to master would be add even more unnecessary work and it would be even more error prone.

**Comment by jkotas** [comment]
E.g. you can merge release/3.1 to master to see the giant amount of merge conflicts.

**Comment by tmat** [comment]
Odd, Roslyn has been doing this for years and we've had no issues.

**Comment by jkotas** [comment]
> That's certainly standard flow in many other repos.

It is not the industry standard. The industry standard is to submit to master and back-port as necessary. There is no automatic flow from servicing to master in any of the major open source projects that I know about: Linux kernel, LLVM, ... .

**Comment by danmosemsft** [comment]
> Due to high churn in coreclr/corefx, flowing 3.1 to master would add even more unnecessary work and it would be even more error prone.

On top of above reasons, another reason is that often a fix is already in master when we decide to port it. In those cases inevitably the backport is second and it's nice to have a consistent flow.

**Comment by tmat** [comment]
@danmosemsft So in that case, the flow would be a no-op.

**Comment by tmat** [comment]
I don't actually care that much about where the fix goes first. The bigger issue is that our repos are not consistent and I can't track each repos flow in my head while contributing to dozens of repos.

**Comment by jkotas** [comment]
> The bigger issue is that our repos are not consistent

So get the repos that are not following the industry standard to change.

**Comment by tmat** [comment]
@jaredpar @jasonmalinowski

**Comment by tmat** [comment]
So if we change the flow, how do we prevent issues like this - when a change is merged to servicing branch without being merged to master?

**Comment by stephentoub** [comment]
> when a change is merged to servicing branch without being merged to master?

If the flow is merge first to master and then port to servicing as appropriate, when would that ever happen?

**Comment by tmat** [comment]
> If the flow is merge first to master and then port to servicing as appropriat

It happened because no one was apparently enforcing that. https://github.com/dotnet/corefx/pull/28493 was not merged to master.

**Comment by stephentoub** [comment]
Are you asking then for tooling to be put in place?

Mistakes can be made regardless of the flow direction.  With either direction tooling can help.

**Comment by tmat** [comment]
> Are you asking then for tooling to be put in place?

Ideally, yes.

> Mistakes can be made regardless of the flow direction

Sure, the mistake happened because I expected the flow from servicing to master to happen automatically because that's what other repos I work with do.

**Comment by mmitche** [comment]
> Mistakes can be made regardless of the flow direction. With either direction tooling can help.

Yep


> Sure, the mistake happened because I expected the flow from servicing to master to happen automatically because that's what other repos I work with do.

This flow is really tough for any repos that are not leaves in the dependency graph. Inter-branch merges are really painful when the version files are always getting edited. I'm beginning to think that this automation provides more pain and possibility of mistakes than value.

I'd be more of a fan of putting in automation which would keep track of the product relatated-ness of various branches and repos (e.g. release/2.1 is related to release/2.2) and identify cases where fixes in one branch are not merged into oither branches. It could be more selective, and allow the user to either dismiss the warning (fix not applicable to branch) or cherry-pick the fix along.

**Comment by jasonmalinowski** [comment]
> With either direction tooling can help.

We've always been strict with Roslyn to ensure the old branches are merged forward, precisely to make sure that even if a mistake happens we did get stuff being pulled forward. If nothing else, it means that we can delete old release branches with confidence because we aren't going to delete some head that had was the only root to some commits which would then get GC'ed.

I will also express some concern about "industry standard" as a phrase being tossed around here -- the Visual Studio repo for example does not require "backport from master" and flows changes forward, and I can think of plenty of repos do this in the dotnet org here. And those repos have good reasons for doing the flow they are doing. I'm not saying we shouldn't unify on a single model, but "they should just change" is far more complicated and and dismissive of possible concerns they have.

**Comment by jkotas** [comment]
> the Visual Studio repo for example does not require "backport from master" and flows changes forwar

Visual Studio is closed source desktop app. I have in mind the standard of large open source infrastructure projects (OSes, compilers, core libraries, etc.). Are you aware of any non-.NET projects in this category that encourage submitting patches to servicing first and then automatically flow them to master?

Related: https://www.bing.com/search?q=upstream+first+policy

**Comment by danmosemsft** [comment]
This should be closed as the fix is everywhere now.
