### ISSUE TITLE
UWP: System.Reflection.MissingRuntimeArtifactException caused by Encoding.GetString(Byte*,Int32) reflection.

### ISSUE THREAD

**Issue by guperrot** [dotnet/corefx#41722]
Microsoft AppCenter is trying to use System.Reflection.Metadata v1.7.0.

We are trying to extract some information about the native image from a stack trace frame for our crash reporting tool for apps compiled in .NET Native but not distributed in Windows Store.

One part of the code is using `System.Reflection.PortableExecutable.PEReader` and in particular the `ReadCodeViewDebugDirectoryData` that at some point calls `Encoding.GetString(System.Byte*, System.Int32)` via reflection: https://github.com/dotnet/corefx/blob/d3911035f2ba3eb5c44310342cc1d654e42aa316/src/System.Reflection.Metadata/src/System/Reflection/Internal/Utilities/EncodingHelper.cs#L122-L123

When .NET native is enabled on a release x86 app build, we get:

```
System.Reflection.MissingRuntimeArtifactException
  HResult=0x8013151A
  Message=Object_NotInvokable, System.Text.Encoding.GetString(System.Byte*,System.Int32)
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

We tried adding various rules in the `Default.rd.xml` of our test application but without luck so far.

I isolated the problem here to reproduce the problem with an app that builds very fast because very small: https://github.com/guperrot/uwp-rd-test/blob/master/UwpRdTest/App.xaml.cs#L37

And the rules: https://github.com/guperrot/uwp-rd-test/blob/master/UwpRdTest/Properties/Default.rd.xml we tried a lot of combinations of Type, Assembly, Namespace etc... but we are unable to find the rule that would solve this reflection issue.

**Comment by jkotas** [comment]
This is problem in .NET Native. Can you please reach out to dotnetnative at microsoft dot com by email? It's a better channel to report .NET Native issues and get help.

**Comment by guperrot** [comment]
I will reach out to them then. Thanks.
