### ISSUE TITLE
System.Reflection.RuntimeAssembly not serializable

### ISSUE THREAD

**Issue by artemlos** [dotnet/corefx#41739]
# Computing a hash of the calling assembly

I would compute the hash of the calling assembly, similar to the way it can be done in .NET Framework using the code below:

```
var assembly = Assembly.GetCallingAssembly();

var hash = new Hash(assembly);

var hashVal = hash.GenerateHash(new SHA512Managed());
```

Since this does not seem to be possible in .NET Core, I have tried to use the Binary Formatter to serialize the object returned from `Assembly.GetCallingAssembly()`, using the code below:

```
var assembly = Assembly.GetCallingAssembly();

BinaryFormatter formatter = new BinaryFormatter();
MemoryStream stream = new MemoryStream();

formatter.Serialize(stream, assembly);

SHA512 sha = SHA512.Create();

var hash = Convert.ToBase64String(sha.ComputeHash(stream));
```

This gives me the error:
```
System.Reflection.RuntimeAssembly' in Assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' is not marked as serializable.'
```

## Question

Is there a best practise of how the hash of the calling assembly can be computed or is there any plan of making the `System.Reflection.RuntimeAssembly` serializable?

**Comment by artemlos** [comment]
@scalablecory The Hash class requires [System.Security.Policy Namespace](https://docs.microsoft.com/en-us/dotnet/api/system.security.policy?view=netframework-4.8&viewFallbackFrom=netstandard-2.1), which is not supported in .NET Standard.

I double checked .NET Core 2.0 and the namespace seems to be supported (based on docs page), but it would be good if there would be a way to do this in .NET Standard.

**Comment by GrabYourPitchforks** [comment]
What exactly are you trying to compute? A hash of the name, a hash of the actual DLL bytes, or something else?

**Comment by artemlos** [comment]
@GrabYourPitchforks I would like to compute the hash of the actual DLL bytes.

**Comment by GrabYourPitchforks** [comment]
You can get the file name of the assembly via the `Assembly.Location` property. Then read the raw bytes and run it through the hash algorithm of your choice.

If you're looking for something that's "good enough" without computing a real hash you can use the MVID of the assembly. This is accessible through `Assembly.ManifestModule.ModuleVersionId`.
