### ISSUE TITLE
Add self-signed and untrusted root HTTPS tests for HttpClient

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#4173]
Both the Windows and X-Plat codebases would benefit from these tests.

Negative trust tests are good for verifying that the trust model is being respected, and validating the exceptions being thrown.

Additionally, OuterLoop versions which then temporarily add trust for the untrusted root and verify it's then passes are virtuous.

Other potential cases of increasing complexity
* Target vs SubjectAltName/Subject mismatch
* Expired
* Revoked
* Certificate is invalid for server role (has an EKU extension, but doesn't say ServerAuthentication)
* Domain is outside of the issuance scope of the CA

**Comment by bartonjs** [comment]
@CIPop I started this with you since you guys probably would have a better plan for how you want it architected in than me just sort of bolting something on the side to make my scenario work.

**Comment by davidsh** [comment]
Our team is already thinking about how to solve this.

**Comment by davidsh** [comment]
This PR added some SSL tests (active for Unix only right now).
https://github.com/dotnet/corefx/pull/7171/files

```c#
public const string ExpiredCertRemoteServer = "https://expired.badssl.com/";
public const string WrongHostNameCertRemoteServer = "https://wrong.host.badssl.com/";
public const string SelfSignedCertRemoteServer = "https://self-signed.badssl.com/";
public const string RevokedCertRemoteServer = "https://revoked.grc.com/";
```

**Comment by davidsh** [comment]
PR #7626 added API surface area for System.Net.Http and most of the tests for the above
Marking this issue done.
