### ISSUE TITLE
Could ConfigurationProviders load their data in parallel on start-up?

### ISSUE THREAD

**Issue by pekspro** [dotnet/corefx#41743]
I’m using both Azure KeyVault and Azure App Configuraton as ConfigurationProviders in a .NET Core 3 web application, also when I’m debugging. For me KeyVault adds about 5 seconds extra during launch, and App Configuration about 1 second. And this adds up to 6 seconds extra delay.

But couldn’t these providers load their data in parallel? It looks to me like they are running in serial, which make me loose one second every time I start to debug.

**Comment by ericstj** [comment]
I believe this issue belongs in https://github.com/aspnet/extensions. /cc @anurse
