### ISSUE TITLE
dotnet 3.1 Release date

### ISSUE THREAD

**Issue by vintzl** [dotnet/corefx#41748]
Some questions:

1. When is due 3.1? I can read "Scheduled for November 2019" here:
   - https://github.com/dotnet/core/blob/master/roadmap.md
   - https://dotnet.microsoft.com/platform/support/policy/dotnet-core

  But I can see here:
   - https://github.com/aspnet/AspNetCore/milestone/64
  "_3.1.0-preview3 Due by December 03, 2019_"

 2. Will System.Text.Json support no default parameter-less constructors in 3.1?

 3. Is there any 3.1 preview package now?

**Comment by Joe4evr** [comment]
> Will System.Text.Json support parameter-less constructors in 3.1?

![](https://i.imgur.com/nHv3ZC3.png)
How does S.T.Json *not* support parameterless constructors right now?

**Comment by vintzl** [comment]
:s edited

**Comment by Symbai** [comment]
> 
>  
>     2. Is there any 3.1 preview package now?

Yes:
https://github.com/dotnet/core-sdk
https://github.com/dotnet/core-setup#daily-builds

**Comment by joperezr** [comment]
For the 3.1 available preview packages now, we recently shipped preview 1. You can get those installers/binaries from here: https://dotnet.microsoft.com/download/dotnet-core/3.1
/cc: @ahsonkhan @steveharter for the Json question.
For 3.1 release, I'm not sure if we have a specific day set yet, but from @richlander's blog it seems to be December 2019: https://devblogs.microsoft.com/dotnet/announcing-net-core-3-1-preview-1/

**Comment by ahsonkhan** [comment]
Regarding S.T.Json, non default, parameterless ctors are not supported yet for 3.1. That's planned for 5.0 (e.g. see https://github.com/dotnet/corefx/issues/41102).

**Comment by joperezr** [comment]
Closing as the question has been answered, but please @vintzl feel free to reopen if you think otherwise.
