### ISSUE TITLE
BoundedChannel. Initial size of Deque 

### ISSUE THREAD

**Issue by lobster2012-user** [dotnet/corefx#41756]
```BoundedChannel``` uses ```Deque<T>``` as a buffer.
```Deque<T>``` represents an ring buffer that expands 2 times if necessary (and copies items).
It`s initial size is 0.
I suggest adding a parameter - the initial size of the queue, to prevent unnecessary costs at startup.

**Proposed API**

https://github.com/dotnet/corefx/blob/master/src/System.Threading.Channels/src/System/Threading/Channels/ChannelOptions.cs

```csharp
public abstract class BoundedChannelOptions
{
     public InitialBufferSize {get; set;} // check >=0
     ....
}
```

https://github.com/dotnet/corefx/blob/master/src/System.Threading.Channels/src/System/Collections/Generic/Deque.cs

```csharp

internal sealed class Deque<T>
{
        public Deque(int initialBufferSize)
        {
              _array = initialBufferSize > 0 ?new T[initialBufferSize] : Array.Empty<T>();
              //tail..
             //head..
        }
}


```

Related issues.
```RingBuffer<T>``` https://github.com/dotnet/corefx/issues/40489
```Deque<T>``` https://github.com/dotnet/corefx/issues/32790

**P.S.**
In the implementation of the queue, you can replace the whole array with chunks, use the pool.

**Comment by Gnbrkm41** [comment]
looks like BoundedChannelOptions already have one?
```cs
public BoundedChannelOptions(int capacity)
```

**Comment by Gnbrkm41** [comment]
As for the `Deque` type; why is it necessary? it looks like it's `internal` and wouldn't make much impact. I can't really tell since I don't use these though.

Could you explain what the reason for the suggestion is?

**Comment by lobster2012-user** [comment]
DEQUE - an internal buffer, has an initial size of 0, which increases the size by 2 times (at least 4) of the element, while copying the elements.
I would like to set the initial size of this buffer.

**Comment by tarekgh** [comment]
@lobster2012-user could you please follow the API proposal as described in https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md?

**Comment by lobster2012-user** [comment]
@tarekgh 
I edited the post a bit.

**Comment by tarekgh** [comment]
@lobster2012-user thanks.

**Comment by stephentoub** [comment]
The internal deque is an implementation detail.

Presizing the buffer in the channel also presumes a particular implementation; what makes sense now wouldn't make as much sense if it were, for example, replaced with a linked last, or chunked as you suggest.

Pooling wasn't used based on expected use cases.

Can you please share the overall scenario where these suggested changes would make an impactful difference? In what situation are you creating lots of bounded channels, and with a large enough bound that the array growth matters?

**Comment by lobster2012-user** [comment]
@stephentoub 

1. In general, I agree. The parameter here is more likely even the queue itself, or rather its implementation. CreateChannelFromResizableArray (...)

2. Why is this needed?
2.1 First, benchmarks with competitors.
2.2 Suppose we have a slow consumer, a large capacity. A solid array with copying is a so-so solution.
3. I do not quite understand the purpose of System.Threading.Channels
On the one hand, this low-level solution should work faster than DataFlow, should be fast, optimized, but I will erase the implementation of the queue and do not see it there.
On the other hand, nothing was built on top of it. DataFlow, Rx live their own lives. There is still - Disruptor-net - not familiar with this solution.

**Comment by stephentoub** [comment]
> Suppose we have a slow consumer, a large capacity. A solid array with copying is a so-so solution.

But the array quickly reaches its max size. So the main concern would generally be when you have a lot of these. What is the scenario where you're creating lots of bounded channels with a large capacity and slow consumers, where the costs involved here are measurable and meaningful?

> benchmarks with competitors

Please share.

**Comment by lobster2012-user** [comment]
>> Sample
With 8 GB of memory, an extension of 3 GB to 6 GB will not be possible or long. This is more a theory than a practice, you are right.


>>   Please share.
Benchmarks are the first thing that catches your eye. So I mentioned them.
 I have not seen tests with slow cosumers

So far, I do not quite understand why I should use this library at all.
(For the reasons described above (prev message).

>> Does that mean you're not actually using it?
You could say that.
In old tasks where speed was required, I used a custom solution.
Currently I use dataflow, the task is simple and does not require high performance.
At the same time I'm trying to learn channels (for the future)


**I repeat, I don’t understand what this library claims to be Maybe I shouldn't look at her at all.**

**Comment by stephentoub** [comment]
> Maybe I shouldn't look at her at all.

If you don't need it, then it's fine not to use it.

> I don’t understand what this library claims to be.

It provides core abstractions and data structures for efficiently passing data from producers to consumers asynchronously, using simple patterns that integrate well with C#. It's lower-level than the Dataflow library, which builds in the processing as well rather than just the data structures for handing off the data.

**Comment by stephentoub** [comment]
> This is more a theory than a practice

Thanks. My concern is performance-focused API requests when there's no demonstrated need or even actual usage driving the stated need.

**Comment by lobster2012-user** [comment]
Thank you all for the answers. I will close the issue.
