### ISSUE TITLE
Build is broken by unsafe code in S.Linq.Expressions.Tests

### ISSUE THREAD

**Issue by pgavlin** [dotnet/corefx#4177]
e.g. http://dotnet-ci.cloudapp.net/job/dotnet_corefx_mac_release_prtest/5039/consoleFull#1996732205a82fefab-f698-416f-8fca-58544c94cd4e

**Comment by kapilash** [comment]
#4176 is fixing it

**Comment by pgavlin** [comment]
Looks like https://github.com/dotnet/corefx/pull/4176 is--beat me to it :)

**Comment by pgavlin** [comment]
The fix has been merged.
