### ISSUE TITLE
How can I host AspNetCore in Windows Service with https url?

### ISSUE THREAD

**Issue by chenyj796** [dotnet/corefx#41782]
I have a AspNetCore which will host in Windows Service.
The CreateHostBuilder method as below.

``` csharp
public static IHostBuilder CreateHostBuilder(string[] args)
{
	return Host
		.CreateDefaultBuilder(args)
		.UseWindowsService()
		.ConfigureServices((context, services) =>
		{
			services.AddHostedService<Worker>();
		})
		.ConfigureWebHostDefaults(builder =>
		{
			builder.UseUrls("http://localhost:6000/", "https://localhost:6001/");
			builder.UseStartup<Startup>();
		});
}
```

When I run it in Console, everything works fine.
However, when I install it as Windows Service, and request the http://localhost:6000/ or https://localhost:6001/, there is nothing returned.
Seems the UseUrls only support one url with http scheme, like 
``` csharp
builder.UseUrls("http://localhost:6000/");
```

**Comment by davidsh** [comment]
@Tratcher ASP.NET Core repo issue

**Comment by Tratcher** [comment]
This issue was moved to aspnet/AspNetCore#15016
