### ISSUE TITLE
System.Threading.Channels. Ability to delete an item from channel queue only after its successful processing.

### ISSUE THREAD

**Issue by neyromant** [dotnet/corefx#41819]
Hi,
Is it possible to somehow organize reading from the System.Threading.Channel with confirmation?
I want to read data from a channel, and if I could not process it, so that the data remains in the channel queue, for example, until the next processing attempt.
```
var channel = Channel.CreateBounded<LogItem>(new BoundedChannelOptions(100)
            {
                FullMode = BoundedChannelFullMode.DropOldest,
                AllowSynchronousContinuations = true,
                SingleReader = true,
                SingleWriter = false
            });
//...
var item = await channel.Reader.ReadAsync();
await DoSomeWorkOnItemAsync(item); //Now, if DoSomeWorkOnItemAsync throws exception, I will lose item
```
Of course, I can add an item to the top of the queue, but I need the old items that have not been processed to be pushed out of the queue when it is full.

Is it possible for the channel to have an API like below?:
```
using (PickedResult<LogItem> peekedItem = await channel.Reader.PeekAsync())
{
    await DoSomeWorkOnItemAsync(peekedItem.Value);
    peekedItem.CommitRead(); // Confirmed read. Item removes from channel's queue
}
```

Thank you very much for your reply in advance.

**Comment by tarekgh** [comment]
CC @stephentoub 

I believe the proposal here will not work nicely in the multithreading scenarios. imagine 2 threads calling channel.Reader.PeekAsync() in same time. maybe what can help is adding API like `InsertFront(item)` which can allow inserting item in the front of the queue and not at the end.

**Comment by stephentoub** [comment]
It sounds like you're looking for a solution ala two-phase commit.  This is complicated to support, both in implementation and in API, and I don't think it makes sense to add that to the channels library.  However, the TPL Dataflow library does include support for this, with its interfaces allowing you to reserve and then either consume or release a reservation on an item.

For channels, whether a "peek" makes sense would I think depend on exactly the semantics you care about.  I see you've set the options to be SingleReader, which presumably means you don't have to worry about multiple consumers reading from the channel.  In which case the only concurrency problem would be if after peeking the item the channel filled up and the peeked item was dropped.  If that's a problem, then I don't see a good solution.  If it's not a problem, then a peeking API could be relevant.

Any new API added at this point would need to be able to have a valid base implementation, which would make PeekAsync problematic.  I could imagine a TryPeek method, with the base implementation always returning false.

**Comment by neyromant** [comment]
Thank you very match. I will try TPL Dataflow.
