### ISSUE TITLE
Consolidate files which were split by tfms which aren't supported anymore

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/corefx#41821]
In example `ProcessTests.netcoreapp.cs` should be consolidated with `ProcessTests.cs`. As we just removed UWP we have multiple places to clean-up.

cc @stephentoub

**Comment by Marusyk** [comment]
Please assign it to me

**Comment by ViktorHofer** [comment]
Thanks for helping, assigned. Let me know if you need any help.

**Comment by Marusyk** [comment]
Could you please clarify how can I find other files?

**Comment by Marusyk** [comment]
I continue to work on this to combine other files

**Comment by ViktorHofer** [comment]
yes, this issue isn't just about the ProcessTests file but also about others which were split by the target framework which isn't necessary anymore as the project doesn't multi-target anymore.

**Comment by Marusyk** [comment]
@ViktorHofer it would be better to prepare one large PR or many for each project? How will it be easier to review?

**Comment by Marusyk** [comment]
ok, I'm going to do that in a few PR because there are a lot of files and it can be difficult to review

**Comment by Marusyk** [comment]
So, can I continue in dotnet/runtime?

**Comment by ViktorHofer** [comment]
yes :)

**Comment by Marusyk** [comment]
Well, it almost done, but a few questions.

Should I remove *.netcoreapp.cs files for projects where `BuildConfigurations` has  `$(NetFrameworkCurrent);` :
- Microsoft.CSharp  
- System.ComponentModel.Annotations
- System.ServiceModel.Syndication
- System.Threading.Channels

$(NetFrameworkCurrent)-Windows_NT;
- System.Security.Cryptography.Pkcs

And finally, the `GenericVectorTests.netcoreapp.cs` from `System.Numerics.Vectors`  with `GenericVectorTests.netcoreapp.tt`, shold it be consolidated with `GenericVectorTests.cs` and `GenericVectorTests.tt`?

**Comment by jkotas** [comment]
Yes, you are right for both of these.

**Comment by Marusyk** [comment]
Thank you all for these reviews. 
It looks like done. Please let me know if I missed something, otherwise the issue may be closed.

**Comment by jkotas** [comment]
Thank you a lot for all your work on this!

**Comment by ViktorHofer** [comment]
Indeed, thanks a lot for your dedication here.
