### ISSUE TITLE
.Net Core 3.0 CredentialCache empty

### ISSUE THREAD

**Issue by MarkusBrgr** [dotnet/corefx#41826]
When accessing the `CredentialCache.DefaultCredentials` or `CredentialCache.DefaultNetworkCredentials` both returned Credentials are empty.

### Code to Reproduce:

This code produces 2 empty Credentials:
```c#
class Program {
    static void Main(string[] args) {

        var defaultCred = CredentialCache.DefaultCredentials;
        var defaultNetCred = CredentialCache.DefaultNetworkCredentials;

    }
}
```

I expected to get at least one Credentials to be filled with my User-Credentials.

This Code has been tested in .net Core 3.0 and .net Framework 4.7.1 on Windows 7 and Windows 10.

**Comment by stephentoub** [comment]
These are sentinel objects used to represent the desire to use the default credentials: they don't actually contain the credentials, e.g. as noted in the docs:
"The ICredentials instance returned by DefaultCredentials cannot be used to view the user name, password, or domain of the current security context."

**Comment by davidsh** [comment]
This is by-design.  They are sentinel objects. They will never return the currently active username, password etc.
