### ISSUE TITLE
HttpClient.DefaultRequestVersion of HTTP/2 is not honored if using SendAsync

### ISSUE THREAD

**Issue by scalablecory** [dotnet/corefx#41836]
This will send a request via HTTP/1.1:

```c#
var client = new HttpClient() { DefaultRequestVersion = HttpVersion.Version20 };
var msg = new HttpRequestMessage { Method = HttpMethod.Get, RequestUri = new Uri("https://contoso.com") };
client.SendAsync(msg);
```

The default version is only being used for the convenience methods (`GetAsync` etc.).

**Comment by davidsh** [comment]
That is by-design. We talked about it during API review.  If users are passing in an HttpRequestMessage, then they control HTTP version via that.

@stephentoub

**Comment by scalablecory** [comment]
Wow, that's an unfortunate inconsistency with how `DefaultRequestHeaders` works.

We've got a docs bug to fix, in that case.

**Comment by davidsh** [comment]
>Wow, that's an unfortunate inconsistency with how DefaultRequestHeaders works.

I think that discussion came up as well.  I don't recall all the discussion. But it is recorded on YouTube.

@stephentoub might remember the whole discussion.

**Comment by stephentoub** [comment]
You can see it's mentioned here as the alternative, and then it was discussed further as David mentions in the API review discussion:
https://github.com/dotnet/corefx/issues/37224#issue-437734971

**Comment by scalablecory** [comment]
Yea. It's unfortunate that we didn't add some post-review notes to that issue. Okay, it is what it is I guess.

**Comment by davidsh** [comment]
It submitted a PR to fix the documentation:
https://github.com/dotnet/dotnet-api-docs/pull/3359
