### ISSUE TITLE
TraceOptions.Callstack ignored

### ISSUE THREAD

**Issue by ericjohannsen** [dotnet/corefx#41837]
Consider the following static method called from the Main method of a console project:

```
static void TraceTest()
{
    Trace.Listeners.Clear();

    TextWriterTraceListener tl = new TextWriterTraceListener(Console.Out);
    tl.TraceOutputOptions = TraceOptions.DateTime | TraceOptions.Callstack;

    Trace.Listeners.Add(tl);

    Trace.TraceWarning("Alert");
}
```

If the console project is .NET Framework, the stack trace is included:

> TraceConsFwk.exe Warning: 0 : Alert
>     DateTime=2019-10-16T21:53:58.7416455Z
>     Callstack=   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
>    at System.Environment.get_StackTrace()
>    at System.Diagnostics.TraceEventCache.get_Callstack()
>    at System.Diagnostics.TraceListener.WriteFooter(TraceEventCache eventCache)
>    at System.Diagnostics.TraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
>    at System.Diagnostics.TraceInternal.TraceEvent(TraceEventType eventType, Int32 id, String format, Object[] args)
>    at System.Diagnostics.Trace.TraceWarning(String message)
>    at Testing.TraceTestX.TraceTest() in C:\Users\Eric\source\repos\GcMon\TraceConsFwk\Program.cs:line 23
>    at Testing.TraceTestX.Main() in C:\Users\Eric\source\repos\GcMon\TraceConsFwk\Program.cs:line 28

However, if the console project is .NET Core, the stack trace is absent:

> GcMon Warning: 0 : Alert
>     DateTime=2019-10-16T21:52:26.1178378Z

Expected: The TraceOptions.Callstack flag is respected on .NET Core.

Tested with .NET Core 3.0 in VS 2019.

**Comment by danmosemsft** [comment]
@stephentoub seems this should be closed now?
