### ISSUE TITLE
Unhandled exception AwaitableSocketAsyncEventArgs.s_availableSentinel at PerformIOCompletionCallback

### ISSUE THREAD

**Issue by azhmur** [dotnet/corefx#41830]
We have number of Kestrel Asp.net MVC Core 3.0.100 hosts and SocketHttpHandler backed HttpClients looking at them all in same process. Most of them using Http1.1 unsecure. Sometimes unhandled exception occurs which results in process termination. It seems like our code is not involved and there is tricky racing in SocketHttpHandler/Socket.Tasks. Can anyone provide hints how we can diagnose it further?

```
System.Exception: s_availableSentinel
   at void System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.s_availableSentinel(object state)
   at void System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.InvokeContinuation(Action<object> continuation, object state, bool forceAsync, bool requiresExecutionContextFlow)
   at void System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs _)
   at void System.Threading._IOCompletionCallback.PerformIOCompletionCallback(uint errorCode, uint numBytes, NativeOverlapped* pNativeOverlapped)
```

**Comment by stephentoub** [comment]
Any chance you have a repro you can share?  Such an exception should never happen.

**Comment by azhmur** [comment]
Thank you for an explanation.
It had been reproduced only at one instance with specific workload. No luck yet in reproducing it different environments.
We don't use Kestrel sockets/pipes directly. Everything on HttpRequest/HttpResponse level at least. No ValueTasks in our code. Most of HttpClient staff is done with HttpContent.ReadAsAsync<T>().
I had read you article on ValueTask usage more than one time as well.
As far as I understand it is hard do detect problems with AwaitableSocketAsyncEventArgs on their root cause (like multiple awaits) and then delayed punishment without relevant stack hits. 
Maybe we can add some debug only traces to AwaitableSocketAsyncEventArgs which can help with tracking root cause for such issues?

**Comment by azhmur** [comment]
Reproduced on same machine with less staff in process. One connection, one HttpClient, one SocketHttpHandler. One SendAsync with legacy MediaTypeFormatter in overall synchronous loop. But still no luck on different machines even with same data. Switching to HTTP2 seems to be workaround.

PS No antivirus. AWS. Windows 2016 Version 10.0.14393 Build 14393.

**Comment by stephentoub** [comment]
> One connection, one HttpClient, one SocketHttpHandler. One SendAsync with legacy MediaTypeFormatter in overall synchronous loop.

Thanks.  Can you share what the code looks like?

**Comment by azhmur** [comment]
Unfortunately, it is whole business app, not something small. It requires complex setup, and i have tried to reproduce on different machines without success. I have 3 dumps. In all cases Args have 2 bytes buffer and last operation was Send. Buffer content is different in each case.

![image](https://user-images.githubusercontent.com/2143587/67199410-21252700-f3f9-11e9-9e2d-c035c8150965.png)
![image](https://user-images.githubusercontent.com/2143587/67199435-2e421600-f3f9-11e9-8d95-85e48ab5fba2.png)
![image](https://user-images.githubusercontent.com/2143587/67199498-5d588780-f3f9-11e9-9f18-2457be7ad758.png)

PS I can provide dumps if you are interested in looking into. Maybe something in state of the socket or args can bring you some ideas.
PPS Blocks sequence sent in each run are identical, responses slightly different. So I thought it may be "bad sequence" involved. But failure happens on different stages.
PPPS The only unsual part in our code is that we dispose HttpRequest after SendAsync, but before fully consuming response. I think this kind of behavior isn't something wrong.

**Comment by azhmur** [comment]
I had tried different tweaks. It seems i have found possible cause. We write synchronously to HttpRequest provided stream, which is ChunkedEncodingWriteStream. We also do a lot of Flush and sometimes empty block writes (they becomes Flash as well in this particular implementation and effectively NoOp). After i have removed all such places in our code the issue have stopped to reproduce.
I was expected we may somehow access request stream concurrently (like flushing concurrently while dispose already running), but haven't find any proofs it happens.
I will try to provide minimal test case and will close issue if i can't do it in reasonable timeframe.

**Comment by stephentoub** [comment]
Thank you for investigating.
