### ISSUE TITLE
FileSystemWatcher does not fire events on MacOS when NotifyFilter = LastAccess

### ISSUE THREAD

**Issue by cyperous** [dotnet/corefx#41841]
MacOS Versions tested: Mojave 10.14, Catalina 10.15

Code used.

```csharp
     using (var watcher = new FileSystemWatcher (Directory.GetCurrentDirectory (), "*.txt")) {
            watcher.IncludeSubdirectories = true;
            watcher.NotifyFilter = NotifyFilters.LastAccess;

            watcher.Changed += (sender, e) => {
               Console.WriteLine (e.FullPath);
            };

            watcher.EnableRaisingEvents = true;

            // Wait for the user to quit the program.
            Console.WriteLine ("Press 'q' to quit the sample.");
            while (Console.Read () != 'q');
         }
```
if I run cat sometextfile.txt, the event in the code above is never fired.

Alternate Code that works in Mojave but not in Catalina

 ```csharp
 public abstract class AccessTime {
      public abstract DateTime GetLastAccessTime (string filename);
   }

   public class AccessTimeUnix : AccessTime {
      public override DateTime GetLastAccessTime (string filename) {
         return new Mono.Unix.UnixFileInfo (filename).LastAccessTime;
      }
   }

   public class AccessTimeWindows : AccessTime {
      public override DateTime GetLastAccessTime (string filename) {
         FileInfo temp = new FileInfo (filename);
         temp.Refresh ();
         return temp.LastAccessTime;
      }
   }

public static AccessTime _accessTime;

public static void Main (string [] args) {
         if (Environment.OSVersion.Platform ==  PlatformID.Unix) {
            _accessTime = new AccessTimeUnix ();
         } else {
            _accessTime = new AccessTimeWindows ();  
         }

        DateTime currentTime = _accessTime.GetLastAccessTime ("sometextfile.txt");

        File.ReadAllText ("sometextfile.txt")

        DateTime newTime = _accessTime.GetLastAccessTime ("sometextfile.txt");

        //Note currentTime and newTime will be different
}
```

By using the technique above I can run a loop continuing to watch for files that are being read but not changed because the LastAccessTime is changing.

For some reason on Catalina, the LastAccessTime is not being updated not sure why it's probably a bug in Catalina.

**Comment by danmosemsft** [comment]
@cyperous thanks for the report. Any interest in digging a little more to verify it's a Catalina issue? Then we can log it against them.

**Comment by cyperous** [comment]
@danmosemsft I tried running the FileSystemWatcher on both Catalina and Mojave both don't work on either OS Version, at least for LastAccess is concerned.

The workaround I've been using on Mojave by monitoring the Last Access timestamps manually works on Mojave.  But on Catalina the timestamps are not changing under the same conditions.

**Comment by safern** [comment]
cc: @carlossanlop @JeremyKuhne

**Comment by wfurt** [comment]
note that some file systems allows to mount with noatime to save expense of  writing to fs on access. I assume this on on standard apfs @cyperous ?

**Comment by cyperous** [comment]
I've been playing around trying to figure out if and when the atime changes when reading a file.

It seems that if I create a drive formatted with MacOS Extended, I don't encounter any issues at least when it comes to using stat -s file.

For some reason on an APFS file system though the st_atime is not being updated.

@wfurt I would agree with you, even Windows 10 has access times disabled and you can enable it using a command in a elevated power shell window.  Maybe Catalina has something similar that we just don't know about.

**Comment by cyperous** [comment]
I just had a major revelation.
I just tried using the following command `sudo mount -vuwo strictatime /Volumes/Drive`

This drive is formatted apfs.

After performing this action the access time's are now being updated on this drive.

YEAH!!!

**Comment by carlossanlop** [comment]
> _After performing this action the access time's are now being updated on this drive._

@cyperous that's great to hear. It seems we can close this issue since we know the reason was external.

Just to double check, the issue has been resolved for both Mojave and Catalina, and your `FileSystemWatcher` code is now able to detect last access changes after you mount the apfs drive using the provided command. Correct? If you're still having problems, let us know and we can reopen the issue.

**Comment by cyperous** [comment]
@carlossanlop That's correct.
