### ISSUE TITLE
.NET Core 3.0  - Assembly.ReflectionOnlyLoadFrom throws System.PlatformNotSupportedException

### ISSUE THREAD

**Issue by sdg002** [dotnet/corefx#41857]
This API works fine on .NET Framework 4.6.1

I used this overload of `System.Reflection.Assembly.ReflectionOnlyLoadFrom` to load `Newtonsoft.json.dll` l.  Tests with version 9 and version 12 of NewtonSoft produced the same error.

`public static Assembly ReflectionOnlyLoadFrom(string assemblyFile);`

**Exception message**

```
System.PlatformNotSupportedException
  HResult=0x80131539
  Message=ReflectionOnly loading is not supported on this platform.
  Source=System.Private.CoreLib


```

Is the method `ReflectionOnlyLoadFrom` deprecated? If so then the method should be marked with `Obsolete` attribute and alternative method provided.

Thanks,
Sau

**Comment by sdg002** [comment]
Sorry. I just saw the fine print in the XML comments. Is there an alternative.

> .NET Core only: This member is not supported.

**Comment by sdg002** [comment]
Thank you for the quick response.

I am going to try MetadataReader.GetAssemblyDefinition
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.metadata.metadatareader.getassemblydefinition?view=netcore-3.0

**Comment by sdg002** [comment]
The class MetadataReader looks promising, but is there something simpler. I am wary of doing low level memory handling. 

Thanks,
Sau

**Comment by jkoritzinsky** [comment]
The `System.Reflection.MetadataLoadContext` class and related APIs sounds like what you're looking for.
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.metadataloadcontext?view=dotnet-plat-ext-3.0

**Comment by DaZombieKiller** [comment]
> 
> 
> The class MetadataReader looks promising, but is there something simpler? I am wary of doing low level memory handling.
> 
> Thanks,
> Sau

You can avoid dealing with pointers by retrieving a `MetadataReader` through a [`PEReader`](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.portableexecutable.pereader?view=netcore-3.0) instance instead of constructing it yourself.
That said, as pointed out by @jkoritzinsky, `MetadataLoadContext` is most likely what you really want.

**Comment by KalleOlaviNiemitalo** [comment]
`AssemblyName.GetAssemblyName(string assemblyFile)` is also available, if you just want the assembly version.

**Comment by sdg002** [comment]
`AssemblyName.GetAssemblyName` is a good suggestion.  At the moment I am doing a `Assembly.LoadFile` on all the DLLs that are resolved by  `AssemblyDependencyResolver.ResolveAssemblyToPath`  in the central `Resolving` event to find the assembly whose version closely matches the `arg2` parameter of `Resolving` event.

I think, the method `AssemblyName.GetAssemblyName` is better than `LoadFile` because it avoids unnecessarily bringing into memory unwanted assemblies. Find the best version match and then do a `AssemblyLoadFile`.

If `Assembly.LoadFrom` is going to remain unchanged, then forcibly resolving the dependencies in this manner will be a work around to achieve the same effect. 

**Project:** ConsoleAppNewDepsJson
**GitHub:** https://github.com/sdg002/MEFFwkCoreComparison

Thanks,
Sau

**Comment by steveharter** [comment]
Per https://github.com/dotnet/corefx/issues/2800, `MetadataLoadContext` is the newer API. This supports read-only reflection (can't invoke methods).

**Comment by steveharter** [comment]
Closing; the MetadataLoadContext is used to read metadata.
