### ISSUE TITLE
Support for GeoCoordinateWatcher from System.Device.Location

### ISSUE THREAD

**Issue by arturredzko** [dotnet/corefx#41862]
Hi
Are there any plans or an existing solution for using/replacing GeoCoordinateWatcher class from System.Device.Location in .NET Core 3.0? I want to port this code from .NET 4.5 :

oGeoWatcher = new GeoCoordinateWatcher() ;
oGeoWatcher.TryStart(false, TimeSpan.FromMilliseconds(1000));
...
if (oGeoWatcher.Status == GeoPositionStatus.Disabled) 
..

Thanks
Artur

**Comment by danmosemsft** [comment]
Please see #30775.
