### ISSUE TITLE
[Linux] SendAsync_SendRequestUsingMethodToEchoServerWithNoContent_MethodCorrectlySent tests fail

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#4187]
New tests added in PR #4184 has tests failing on Linux:

SendAsync_SendRequestUsingMethodToEchoServerWithNoContent_MethodCorrectlySent()
SendAsync_SendRequestUsingMethodToEchoServerWithContent_Success

http://dotnet-ci.cloudapp.net/job/dotnet_corefx_prtest/5931/

**Comment by stephentoub** [comment]
> Looks like a problem with parsing

The issues all boil down to a space at the beginning of what's being compared:
```
16:18:19       Expected: GET
16:18:19       Actual:    GET
```

**Comment by Maxwe11** [comment]
again http://dotnet-ci.cloudapp.net/job/dotnet_corefx_prtest/6283/console
