### ISSUE TITLE
dotnetcore Kestrel Http/2 support without https

### ISSUE THREAD

**Issue by RajeshAKumar** [dotnet/corefx#41899]
The Kestrel using .net core 3.0, does not support Http/2 protocol even if protocol is set.
o.ConfigureEndpointDefaults(lo => lo.Protocols = HttpProtocols.Http1AndHttp2);

and added the context switch too.
AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);

The Client application using Request.Version = 2.0 works on say "https://google.com", but fails to work on "http://google.com".
Our scenario is our URL is https, but the SSL is terminated at the load balancer, so the application server hosting the kestrel based micro service does not get https, but only http connections.

How to make the server support the http/2?

**Comment by davidsh** [comment]
>The Kestrel using .net core 3.0, is not support Http/2 protocol even if protocol is set.
o.ConfigureEndpointDefaults(lo => lo.Protocols = HttpProtocols.Http1AndHttp2);
How to make the server support the http/2?

@Tratcher

**Comment by scalablecory** [comment]
Kestrel to my knowledge already supports this. See https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.0#unable-to-start-aspnet-core-grpc-app-on-macos

`HttpClient` does not, but there is already an issue for that at https://github.com/dotnet/corefx/issues/41621

**Comment by RajeshAKumar** [comment]
> Kestrel to my knowledge already supports this, but you can't listen on both HTTP/1 and HTTP/2 at the same time. See https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.0#unable-to-start-aspnet-core-grpc-app-on-macos
> 
> `HttpClient` does not support this, but there is an issue tracking h2c support at #41621

Thank you, the issue was to set it only to Http2 and not support both, then it worked.

**Comment by davidsh** [comment]
>Thank you, the issue was to set it only to Http2 and not support both, then it worked.

Sounds like your issue is now resolved?  If so, you can close the issue.
