### ISSUE TITLE
FileSystemAclExtensions methods should null check the "this" argument

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/corefx#41907]
These methods should null check the `this` argument:

https://github.com/dotnet/corefx/blob/226f57b4f2bf91822604aa73338070c601d7a0fe/src/System.IO.FileSystem.AccessControl/src/System/IO/FileSystemAclExtensions.cs

cc @JeremyKuhne @stephentoub

**Comment by danmosemsft** [comment]
We have about 1500 public extension methods and there's others that have this issue. Ideally we'd have an analyzer.
```c#
        public static Vector128<byte> AsByte<T>(this Vector128<T> vector)
            where T : struct
        {
            return vector.As<T, byte>();
```

**Comment by stephentoub** [comment]
`Vector128<T>` is a struct. :Wink:

But yes, I'm sure there are other occurrences of this.

**Comment by danmosemsft** [comment]
My bad, I didn't realize we had both `Vector128` and `Vector128<T>`. The former is a class.

It's a little confusing to search for them by eyeball, eg., this is not a problem
```c#
        public static void Validate(this XDocument source, XmlSchemaSet schemas, ValidationEventHandler validationEventHandler)
        {
            source.Validate(schemas, validationEventHandler, false);
        }
```
because the call is through another extension method, which does the check.

**Comment by eanova** [comment]
I would like to work on this.
