### ISSUE TITLE
Better experience for investigating assembly loading issues (Could not load file or assembly <assembly name> or one of its dependencies. The system cannot find the file specified.)

### ISSUE THREAD

**Issue by cdmihai** [dotnet/corefx#41900]
In my experience, this is one of the most annoying and sometimes quite time consuming errors that I get with C# apps. If my experience is shared by most developers, it means this error is wasting a lot of developer time world wide. Would there be ways to improve it to reduce wasted time? For example, the message part with `or one of its dependencies` is vague. Could the runtime detect exactly which assembly failed to load exactly which dependency and just print that broken chain out instead of `or one of its dependencies`?

**Comment by jkotas** [comment]
> message part with or `one of its dependencies` is vague

It was both vague and actually wrong. Missing dependencies do not cause the assembly itself from being loaded. We have fixed this error message in .NET Core several years ago: https://github.com/dotnet/coreclr/pull/4624.

> print that broken chain

Tracked by https://github.com/dotnet/coreclr/issues/20484

**Comment by jkotas** [comment]
cc @vitek-karas
