### ISSUE TITLE
Strange `MembersMustExist` error when adding `Replace()` method to `ImmutableList` builder

### ISSUE THREAD

**Issue by bert2** [dotnet/corefx#41917]
I noticed that the [`ImmutableList<T>.Builder`](https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.Builder.cs) class is missing the method `Replace()` [that `ImmutableList<T>` has](https://github.com/dotnet/corefx/blob/5e4bf872154c17a1407997a38cc013fb12d5d1af/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.cs#L397).

So, I created a fork and [added it along with tests](https://github.com/bert2/corefx/commit/98b52e37eab65cf1e67f6c18b74f3268bfc444ba) re-using the [test cases](https://github.com/dotnet/corefx/blob/5e4bf872154c17a1407997a38cc013fb12d5d1af/src/System.Collections.Immutable/tests/ImmutableListTest.cs#L527) for `ImmutableList<T>.Replace()`.

However, trying to build with...
```
PS> .\build.cmd -build System.Collections.Immutable
```
...shows me this error:
>C:\Users\bert\.nuget\packages\microsoft.dotnet.apicompat\5.0.0-beta.19518.2\build\Microsoft.DotNet.ApiCompat.targets(143,5): error : MembersMustExist : Member 'System.Collections.Immutable.ImmutableList<T>.Builder.Replace(T, T)' does not exist in the reference but it does exist in the implementation. [D:\DEV\corefx\src\System.Collections.Immutable\src\System.Collections.Immutable.csproj]
C:\Users\bert\.nuget\packages\microsoft.dotnet.apicompat\5.0.0-beta.19518.2\build\Microsoft.DotNet.ApiCompat.targets(143,5): error : MembersMustExist : Member 'System.Collections.Immutable.ImmutableList<T>.Builder.Replace(T, T, System.Collections.Generic.IEqualityComparer<T>)' does not exist in the reference but it does exist in the implementation. [D:\DEV\corefx\src\System.Collections.Immutable\src\System.Collections.Immutable.csproj]
C:\Users\bert\.nuget\packages\microsoft.dotnet.apicompat\5.0.0-beta.19518.2\build\Microsoft.DotNet.ApiCompat.targets(157,5): error : MatchingRefApiCompat failed - The reference assembly doesn't match all the APIs in the implementation for 'D:\DEV\corefx\artifacts\bin\System.Collections.Immutable\netcoreapp-Debug\System.Collections.Immutable.dll'. To address either fix errors in the reference assembly (referenced as implementation in compat errors for this reverse compat check), add the issues to the baseline file 'D:\DEV\corefx\src\System.Collections.Immutable\src\MatchingRefApiCompatBaseline.txt' or disable this check by setting RunMatchingRefApiCompat=false in this project. [D:\DEV\corefx\src\System.Collections.Immutable\src\System.Collections.Immutable.csproj]

I'm not quite sure what this error is telling me or how I'm supposed to fix it. Can anyone assist, please?

The build succeeds when I remove the `<Exec Command="$(_ApiCompatCommand) ...` tag from `Microsoft.DotNet.ApiCompat.targets`. By that I was able to verify that my test cases are green using:
```
PS> .\build.cmd -buildtests -test System.Collections.Immutable
```

**Comment by stephentoub** [comment]
You also need to add it to the reference assembly, under the ref folder.

**Comment by bert2** [comment]
Thanks, that did the trick!
