### ISSUE TITLE
System.Text.Json - JsonSerializer.SerializeAsync?

### ISSUE THREAD

**Issue by yruson** [dotnet/corefx#41916]
I create test console app,(use net core3.0), and code as below:

`using System;
using System.IO;
using System.Text.Json;
using System.Threading.Tasks;

namespace TestConsoleApp1
{
    class Program
    {
        async static Task Main(string[] args)
        {
            var obj = new { Name = "Test", Age = 18 };

            string json = string.Empty;
            using (var stream = new MemoryStream())
            {
                await JsonSerializer.SerializeAsync(stream, obj);
                stream.Position = 0;
                using var reader = new StreamReader(stream);
                json = await reader.ReadToEndAsync();
            }

            Console.WriteLine(json);    //output {"Name":"Test","Age":18}, is ok
            Console.WriteLine(await GetJson(obj));  //output {}, why?

            Console.ReadLine();
        }

        private static async Task<string> GetJson(object obj)
        {
            string json = string.Empty;
            using (var stream = new MemoryStream())
            {
                await JsonSerializer.SerializeAsync(stream, obj);
                stream.Position = 0;
                using var reader = new StreamReader(stream);
                json = await reader.ReadToEndAsync();
            }
            return json;
        }
    }
}
`

output
{"Name":"Test","Age":18}
{}

the same code, but to output different results, why?

**Comment by ahsonkhan** [comment]
@yruson - how did you resolve your issue?

**Comment by yruson** [comment]
@ahsonkhan 
This is because System.Text.Json.Serializer is a generic method and it uses the generic parameter, not the runtime type.
use : await JsonSerializer.SerializeAsync<T>(stream, obj);

`private static async Task<string> GetJson<T>(T obj)
    {
        string json = string.Empty;
        using (var stream = new MemoryStream())
        {
            await JsonSerializer.SerializeAsync<T>(stream, obj);
            stream.Position = 0;
            using var reader = new StreamReader(stream);
            json = await reader.ReadToEndAsync();
        }
        return json;
    }`
