### ISSUE TITLE
Why CodePagesEncodingProvider.Instance.GetEncoding("utf-8") return null?

### ISSUE THREAD

**Issue by rstm-sf** [dotnet/corefx#41929]
Hello!

Why `CodePagesEncodingProvider.Instance.GetEncoding("utf-8")` return `null`? Is this considered normal behavior?

But if write this, then everything is fine
```c#
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
var test = Encoding.GetEncoding("utf-8");
```

because there is a `null` check

https://github.com/dotnet/corefx/blob/ac99a1b7168bd32046a954c3f06012c0fa909bed/src/Common/src/CoreLib/System/Text/Encoding.cs#L267-L275

**Comment by tarekgh** [comment]
CodePagesEncodingProvider doesn't support any Unicode encoding. It only support the code pages encoding. The Unicode encodings (e.g. UTF-8, UTF32) is supported by default encoding. https://docs.microsoft.com/en-us/dotnet/api/system.text.codepagesencodingprovider?view=netcore-3.0#remarks is mentioning what encoding is supported by default. 

The best practice is you always use the Encoding class. And if  your app need to support the code page encodings, you just register it and continue using the Encoding class to get the needed encoding. Using the provider class directly will restrict you to only the encodings defined by this provider.
