### ISSUE TITLE
Power Bi connection to postgres

### ISSUE THREAD

**Issue by scobbyy2k3** [dotnet/corefx#41923]
i got this error message while attempting to pull data from postgres to power bi. How do i solve it?

Details: "An error happened while reading data from the provider: 'Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'"

**Comment by safern** [comment]
@scobbyy2k3 could you provide a minimal repro example? Like a code snippet where we can repro this issue?

**Comment by ericstj** [comment]
Closing as no info after 1 week.  Please reopen if you can share a repro.

SWAG: looks to me like you're using a component that forgot to distribute/load its dependencies.  You might try to follow up with that component owner.  The callstack of the exception might indicate where the load occured and which component was missing the dependency.
