### ISSUE TITLE
Assembly.Load(String) doesn't need full name

### ISSUE THREAD

**Issue by NextTurn** [dotnet/corefx#41955]
Migrated from dotnet/dotnet-api-docs#2270 to request for more information.

> https://github.com/dotnet/dotnet-api-docs/blob/3417fadcec76fa01f6b262ea7bcd999ae6b74a50/xml/System.Reflection/Assembly.xml#L3552
>
> I successfully called `Assembly.Load(String)` with the [simple name](https://docs.microsoft.com/dotnet/api/system.reflection.assemblyname.name) of an assembly, in .NET Framework 4.7.2 and .NET Core 2.2.

**Comment by jkotas** [comment]
Responded in https://github.com/dotnet/dotnet-api-docs/issues/2270#issuecomment-544604488
