### ISSUE TITLE
Why System.Text.Json requires that class explicitly have parameterless constructor

### ISSUE THREAD

**Issue by neman** [dotnet/corefx#41973]
I have a class containing one constructor with some parameters. 
Why do I also have to explicitly declare default constructor?

I'm already using both constructors throughout the code, and System.Text.Json does not serialize if I do not explicitly write default constructor. Newtonsoft json did not required this intervention. Now I have to revert back to old code.

Example of code which does not work

```c#
string test = "{\"First\": {\"Name\": \"Nemanja\"}}";
var value = JsonSerializer.Deserialize<Dictionary<string, Person>>(test);

public class Person
{
   public string Name { get; set; }
   public Person(int x)   { }
}
```

This code throws exception. It works when I add parameterless constructor

**Comment by khellang** [comment]
The serializer needs a constructor to call in order to create the `Person` object. Does the code you showed even work with Newtonsoft.Json? I thought it matched constructor argument names with JSON property names? Anyway, the feature you're talking about is probably already covered by either https://github.com/dotnet/corefx/issues/40399 or https://github.com/dotnet/corefx/issues/38569.

**Comment by neman** [comment]
The same code works well with Newtonsoft.Json

```C#
using System;
using System.Collections.Generic;

namespace ConsoleApp
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            string test = "{\"First\": {\"Name\": \"Nemanja\"}}";
            var worked = Newtonsoft.Json.JsonConvert.DeserializeObject<Dictionary<string, Person>>(test);
            var failed = System.Text.Json.JsonSerializer.Deserialize<Dictionary<string, Person>>(test);
        }

        private class Person
        {
            public string Name { get; set; }

            public Person(int x) { }
        }
    }
}
```

![image](https://user-images.githubusercontent.com/350314/67276844-cad1ea00-f4c5-11e9-8bfe-ffd98bed1ea0.png)

**Comment by khellang** [comment]
Hmm. What does Newtonsoft pass as the `x` argument in that `Person` constructor? Or does it just not call a constructor at all?

**Comment by neman** [comment]
It pass default for int, 0

![image](https://user-images.githubusercontent.com/350314/67278863-2605db80-f4ca-11e9-9677-be4e3349f906.png)

**Comment by ericstj** [comment]
Related https://github.com/dotnet/corefx/issues/40399.  As a simplification v1 of System.Text.Json only supports parameterless constructors.
