### ISSUE TITLE
Net Core 3.0 Memory

### ISSUE THREAD

**Issue by Alan-Lun** [dotnet/corefx#41978]
https://github.com/dotnet/corefx/issues/41669
記憶體都持續飆高，不會下降釋放
基本專案
https://github.com/Alan-Lun/NetCoreMemory

圖片
init
https://imgur.com/PgpjVFe
呼叫一次
https://imgur.com/2w25aUI
連續呼叫
https://imgur.com/SU8bWQm
https://imgur.com/t3GxpGY

目前專案上Memory
Quartz.net(https://github.com/quartznet/quartznet)
https://imgur.com/IyanjhX
.Net Core 3.0 WebAPI
https://imgur.com/YXBCd2e

memory total: 128mb
build image: mcr.microsoft.com/dotnet/core/sdk:3.0-buster
dotnet publish API.csproj -c Release -r linux-x64 --self-contained true

run image: mcr.microsoft.com/dotnet/core/aspnet:3.0-buster-slim

AWS ECS
CPU available:2048
Memory available(MB)
Agent version: 1.29.0
Docker version:18.06.1-ce

**Comment by danmosemsft** [comment]
This is an ASP.NET project. I also see some Autofac, Microsoft.Extensions.* etc.

@Alan-Lun have you tried reducing the repro case? Ie., removing components and functionality to make your app as simple as possible until the repro stops happening? This will often suggest the issue, or at least make it easier to figure out the issue.

Also, in this repro the community generally works in English language. Is it possible for you to work this way?

**Comment by Alan-Lun** [comment]
OK,Sorry
Next time I will translate it first and then post it.

Can you help me the last time? Thank you.

---------
https://github.com/aspnet/AspNetCore/issues/14932
mkArtakMSFT
Thanks @Alan-Lun.
It seems there's already investigation happening on the corefx repo. Not to duplicate the effort, we're closing this issue. If it turns out that the problem is caused by ASP.NET Core, @danmosemsft will transfer the issue from corefx to here and we'll use the transferred issue instead.
