### ISSUE TITLE
NetCore（2.1） System.Drawing.Common（4.6.0） Bitmap SetResolution invalid

### ISSUE THREAD

**Issue by liu10725** [dotnet/corefx#41979]
Setting the image resolution is good on windows, but it doesn't work on Linux. When you draw text, you don't enlarge the font according to the resolution.

`image.SetResolution(96 * imageDpi, 96 * imageDpi);`

**Comment by gfoidl** [comment]
This is tracked in https://github.com/mono/libgdiplus/issues/524

**Comment by danmosemsft** [comment]
Closing as tracked elsewhere. Thanks for the report.
