### ISSUE TITLE
.NET Core 2.2 SslPolicyErrors: RemoteCertificateChainErrors

### ISSUE THREAD

**Issue by Pilchie** [dotnet/corefx#41996]
_From @rezvanf on Tuesday, October 15, 2019 3:00:55 PM_

### Describe the bug
When making a httpclient call from 1 asp .net Core 2.2 API to another asp .net  2.2  API on 2 different hosts on linux (Red Hat Enterprise Linux Server 7.7 (Maipo)), an error of sslpolicyerrors.: remotecertificatechainerrors occur.

Both asp .net core apis are running under https with a PFX and "pwd".

The PFX has been created from a crt (pem format)

### To Reproduce
Sample httpclient code below
```c#
var handler = new HttpClientHandler();
var cert2 = new X509Certificate2(pfxLocation, "pwd");
handler.ClientCertificates.Add(cert2);
handler.ClientCertificateOptions = ClientCertificateOption.Manual;

var httpClient = new HttpClient(handler);
```
In the ServerCertificateCustomValidationCallback method i get the following

This is the value of sslErrors
sslErrors = RemoteCertificateChainErrors"

This is the value of chain
chainStatus.Status  =PartialChain
chainStatus.StatusInformation = unable to get local issuer certificate

### Expected behavior
call to https end point with no errors

if I do a curl to the api2 endpoint from the host with api1 with the --cacert flag and the file for the crt (pem format) i get a valid response,

If i exclude the --cacert i get the warning the site is insecure which makes sense

### Additional context
Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-rc1-014190
 Commit:    c4d43f672d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-rc1-014190\

Host (useful for support):
  Version: 3.0.0-rc1-19456-20
  Commit:  8f5d7b1ba4

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-rc1.19457.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-rc1-19456-20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-rc1-19456-20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

_Copied from original issue: aspnet/Extensions#2514_

**Comment by Pilchie** [comment]
_From @brandondahler on Thursday, October 17, 2019 7:17:33 PM_

It sounds like you are mistaking `ClientCertificate` as being a way for HttpClient to know which certificate to expect _from_ the server.  This is not the case -- `ClientCertificate` is a way for you to provide your own authentication certificate _to_ the server.  This allows an http client to do [mutual TLS authentication](https://en.wikipedia.org/wiki/Mutual_authentication) when connecting to the server.

Based on your description, it sounds like you have a server which is serving a self-signed or otherwise non-CA signed certificate and you'd like to have your `HttpClient` instance accept that certificate, and only that certificate, as valid.  To do this, you would use `ServerCertificateCustomValidationCallback` and have it validate that the certificate returned by the server is the certificate that your client expected.  It would likely look something like this:

``` C#
// Preferably store/load only the public certificate
var expectedCertificate = new X509Certificate2(pfxLocation, "pwd");


var handler = new HttpClientHandler();

handler.ServerCertificateCustomValidationCallback = 
    (request, serverCertificate, serverChain, sslPolicyErrors) => {
        return serverCertificate.Thumbprint == expectedCertificate.Thumbprint;
    };


var httpClient = new HttpClient(handler);
```

**Comment by Pilchie** [comment]
_From @Pilchie on Tuesday, October 22, 2019 5:03:16 PM_

@anurse thoughts here?

**Comment by Pilchie** [comment]
_From @Pilchie on Tuesday, October 22, 2019 5:03:57 PM_

Putting in `area-httpclientfactory` for now, though I'm not sure this doesn't belong on `aspnet\AspNetCore`

**Comment by Pilchie** [comment]
_From @brandondahler on Tuesday, October 22, 2019 5:25:07 PM_

@Pilchie I'd presume it would belong in `dotnet/corefx`, if anywhere, since they only talk about `HttpClient`.  Its possible that they're talking about the server-side of aspnetcore which would then possibly be in `aspnet/AspNetCore` but there's no direct information in the issue that says so.

**Comment by Pilchie** [comment]
_From @anurse on Tuesday, October 22, 2019 5:35:07 PM_

I agree with @brandondahler 's initial interpretation and it is likely to be a corefx issue since it's dealing with `HttpClient` entirely.

@rezvanf can you provide a runnable sample app that reproduces the problem?

**Comment by davidsh** [comment]
It's possible this is a manifestation of this issue: https://github.com/aspnet/AspNetCore/issues/7246.

Basically using self-signed certificates in Linux is broken because the self-signed certificate requires an X509v3 attribute (Certificate Signing) that Windows self-signed certificates don't require.

Please check out the issue referenced above and see if it applies to your scenario. If so, you can re-generate a self-signed certificate that will work better on Linux.

**Comment by davidsh** [comment]
Looking at the additional information reported:

>if I do a curl to the api2 endpoint from the host with api1 with the --cacert flag and the file for the crt (pem format) i get a valid response,
If i exclude the --cacert i get the warning the site is insecure which makes sense

If you are attempting to use an untrusted self-signed certificate with .NET Core, then you should make that certificate trusted by installing it into the trusted list of certificates.  See example:

```
davidsh@davidsh2:/mnt/d/dotnet/web1$ sudo cp /mnt/d/localhost.crt /usr/local/share/ca-certificates
davidsh@davidsh2:/mnt/d/dotnet/web1$ sudo update-ca-certificates
Updating certificates in /etc/ssl/certs...
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
```

Then verify it works by using 'curl' with the --cacert flag.

By default, you will get an error from HttpClient if you use an untrusted certificate. If you don't want to add the certificate to your machine's trust list, then you will need to use the `HttpClientHandler.ServerCertificateCustomValidationCallback` API as [described](https://github.com/dotnet/corefx/issues/41996#issuecomment-545084368).

**Comment by karelz** [comment]
Duplicate of https://github.com/aspnet/AspNetCore/issues/7246
