### ISSUE TITLE
Make RuntimeInformation available on downlevel platforms

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#4200]
A new API was added to detect the OS, it would be great if we could bring this API back to .NET 4.x as a standalone implementation on top of `Environment.OsVersion`. That way we could remove our ifdef and use the new surface area across the board.

/cc @ericstj @Priya91

**Comment by ericstj** [comment]
Sure, we can bring this to Net 4.5, it doesn't need to be implemented on top of Environment though.  Today it's just a constant that gets cross-compiled to different values.
