### ISSUE TITLE
Tasks.Dataflow TaskScheduler exception duplication

### ISSUE THREAD

**Issue by Illivion** [dotnet/corefx#42032]
I've found strange code in [SourceCore.cs](https://github.com/dotnet/corefx/blob/daadeef2eef255f86b301ded57996dda25618e90/src/System.Threading.Tasks.Dataflow/src/Internal/SourceCore.cs#L791). It adds exception to list twice. 

![image](https://user-images.githubusercontent.com/554661/67391185-d5b07b80-f5a6-11e9-8210-72ab130dfaa3.png)

I tried to check this code and got duplicated exception:

![image](https://user-images.githubusercontent.com/554661/67391522-89197000-f5a7-11e9-877d-3e7a2b8fcd3c.png)

**Comment by stephentoub** [comment]
Thanks.  Looks like that second add can just be deleted.
