### ISSUE TITLE
`HandshakeAsync` benchmark is 70x slower on Linux compared to Windows

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/corefx#42049]
`HandshakeAsync` benchmark is much slower on Linux compared to Windows

| Slower                                                  | diff/base | Windows Median (ns) | Linux Median (ns) | Modality  |
| --------------------------------------------------------| ---------:| -------------------:| -----------------:| ---------- |
| System.Net.Security.Tests.SslStreamTests.HandshakeAsync |     67.42 |           802607.06 |       54112652.00 |           |

The contributor who wants to work on this issue should:

1. Run [this](https://github.com/dotnet/performance/blob/5c164470d7c340db07391f48e9c03dac45527701/src/benchmarks/micro/corefx/System.Net.Security/SslStreamTests.cs#L55-L68) benchmark from dotnet/performance repository and confirm the problem

```cmd
git clone https://github.com/dotnet/performance.git
python3 ./performance/scripts/benchmarks_ci.py -f netcoreapp5.0 --filter System.Net.Security.Tests.SslStreamTests.HandshakeAsync
```

2. Build CoreFX locally: https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-corefx.md#Build
3. Create a small repro app: https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-corefx.md#repro
4. Use PerfCollect to identify issue https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-corefx.md#PerfCollect
5. Solve the issue

This issue is most probably not easy to solve.

/cc @stephentoub

**Comment by stephentoub** [comment]
This issue is generally tracked by https://github.com/dotnet/corefx/issues/32888.
