### ISSUE TITLE
`Directory.GetCurrentDirectory` 7 times slower on Linux

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/corefx#42058]
`Directory.GetCurrentDirectory` 7 times slower on Linux

| Slower                                              | diff/base | Windows Median (ns) | Linux Median (ns) |
| ----------------------------------------------------| ---------:| -------------------:| -----------------:|
| System.IO.Tests.Perf_Directory.GetCurrentDirectory  |      7.11 |               93.43 |            664.02 |

The contributor who wants to work on this issue should:

1. Run [this](https://github.com/dotnet/performance/blob/bbc30fce34506dc613b70b8dc9040aea3ad56426/src/benchmarks/micro/corefx/System.Runtime.Extensions/Perf.Path.cs#L52) simple benchmark from dotnet/performance repository and confirm the problem

```cmd
git clone https://github.com/dotnet/performance.git
python3 ./performance/scripts/benchmarks_ci.py -f netcoreapp5.0 --filter System.IO.Tests.Perf_Directory.GetCurrentDirectory
```

2. Build CoreCLR locally: https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-corefx.md#Build
3. Create a small repro app: https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-corefx.md#repro
4. Use PerfCollect to identify issue https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-corefx.md#PerfCollect
5. Solve the issue

**Comment by stephentoub** [comment]
@adamsitnik, have you measured the cost of P/Invoke'ing to GetCurrentDirectory on Windows and getcwd on Unix?

**Comment by adamsitnik** [comment]
> have you measured the cost of P/Invoke'ing to GetCurrentDirectory on Windows and getcwd on Unix?

@stephentoub I did not. I have thousands of benchmark results and I am currently just creating tasks, without digging deeper.

**Comment by stephentoub** [comment]
I just ran this:
```C#
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Diagnosers;
using BenchmarkDotNet.Running;
using System;
using System.IO;
using System.Runtime.InteropServices;

[MemoryDiagnoser]
public class Program
{
    static void Main(string[] args) => BenchmarkSwitcher.FromAssemblies(new[] { typeof(Program).Assembly }).Run(args);

    [Benchmark]
    public string DirectoryCurrentDirectory() => Directory.GetCurrentDirectory();

    [Benchmark]
    public string EnvironmentCurrentDirectory() => Environment.CurrentDirectory;

    [Benchmark]
    public unsafe string GetCwd()
    {
        byte* stack = stackalloc byte[1024];
        return new string((sbyte*)getcwd(stack, 1024));
    }

    [DllImport("libc")]
    private static extern unsafe byte* getcwd(byte* buf, long size);
}
```
on an Ubuntu 18.04 VM, and got this:

|                      Method |       Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------------------------- |-----------:|---------:|---------:|-------:|------:|------:|----------:|
|   DirectoryCurrentDirectory | 1,011.5 ns | 20.04 ns | 33.49 ns | 0.0076 |     - |     - |     248 B |
| EnvironmentCurrentDirectory | 1,099.9 ns | 21.71 ns | 33.15 ns | 0.0076 |     - |     - |     248 B |
|                      GetCwd |   979.4 ns | 19.51 ns | 26.04 ns | 0.0076 |     - |     - |     248 B |

so 95% of the cost here is in the `getcwd` call itself, with the additional overhead to address the fact that we can't just pass in a stack-allocated buffer all the time and need fallback code for when the current directory is too large for that.

As such, this would seem to simply be an OS difference that we have little control over.

**Comment by adamsitnik** [comment]
I've used VTune to profile following repro:

```cs
static int Main(string[] args)
{
    int result = 0;

    for (int i = 0; i < 10_000_000; i++)
        result ^= Directory.GetCurrentDirectory().Length;

    return result;
}
```

![image](https://user-images.githubusercontent.com/6011991/67766904-cff7e180-fa4f-11e9-90b0-dc1db58fb466.png)

And confirmed what @stephentoub has wrote. Most of the time is spent in `getcwd` and it looks like we don't have any alternative ;(
