### ISSUE TITLE
XmlBinaryWriterSession.TryAdd method always returns one and the same value of 'true' 

### ISSUE THREAD

**Issue by Marusyk** [dotnet/corefx#42065]
[Documentation ](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmlbinarywritersession.tryadd?view=netcore-3.0)says:

> Returns: true if the string could be added; otherwise, false.

but method always returns one and the same value of 'true'
https://github.com/dotnet/corefx/blob/81a551c219041cacdb6c5f77ff1dd588e8bebd01/src/System.Private.DataContractSerialization/src/System/Xml/XmlBinaryWriterSession.cs#L29-L54

Should it be fixed in docs or code?

**Comment by Marusyk** [comment]
a similar code here but not documented, always returns false
https://github.com/dotnet/corefx/blob/81a551c219041cacdb6c5f77ff1dd588e8bebd01/src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/XmlObjectSerializerWriteContext.cs#L415-L426

**Comment by bartonjs** [comment]
It's a virtual method - the base implementation treats duplicates as OK and allows any number of values to be added, but a derived type could return false. (In .NET Framework there is [a derived type that returns false when it's "too full"](https://referencesource.microsoft.com/#System.ServiceModel/System/ServiceModel/Channels/BinaryMessageEncoder.cs,9469f028ad5e7652,references)).

The documentation speaks to the intent of the method.  The fact that no built-in implementation returns false is an implementation detail.

**Comment by Marusyk** [comment]
Thanks for your excellent explanation
