### ISSUE TITLE
[master] `System.Runtime.Serialization.SerializationException : Member 'SerializedString' was not found.`

### ISSUE THREAD

**Issue by RussKie** [dotnet/corefx#42074]
After updating dependencies from https://github.com/dotnet/core-setup build 20191022.6 some of our tests started failing with the following error:
```
Assert.Throws() Failure
Expected: typeof(System.Reflection.TargetInvocationException)
Actual: typeof(System.Runtime.Serialization.SerializationException): Invalid BinaryFormatter stream.
---- System.Runtime.Serialization.SerializationException : Invalid BinaryFormatter stream.
-------- System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
------------ System.Runtime.Serialization.SerializationException : Member 'SerializedString' was not found.
```

Commit: https://github.com/dotnet/winforms/pull/2159
CI: https://dev.azure.com/dnceng/public/_build/results?buildId=398306&view=ms.vss-test-web.build-test-results-tab&runId=12432008&resultId=110198&paneView=debug

In the previous commit that didn't have the update these tests pass.

**Comment by stephentoub** [comment]
What are you deserializing?

Can you share a repro?

**Comment by stephentoub** [comment]
Oh, I see, your test is expecting a TargetInvocationException that wraps this exception.

This is almost certainly https://github.com/dotnet/corefx/pull/40215.

@ViktorHofer

**Comment by danmosemsft** [comment]
This is the kind of result we expected from the change.

**Comment by RussKie** [comment]
This is breaking WinForms serialisation

/cc: @merriemcgaw @Tanya-Solyanik @DustinCampbell

**Comment by RussKie** [comment]
Scratch that, I'm going to investigate it further.
