### ISSUE TITLE
AuthenticateAsClient : The credentials supplied to the package were not recognized at System.Net.SSPIWrapper.AcquireCredentialsHandle

### ISSUE THREAD

**Issue by xav-stargate** [dotnet/corefx#42078]
Hi everybody,

I need your help !
I try to connect to the Apple server to push using a certificate it works locally but not on my server (Windows 2016 IIS)

My code 

```csharp
    var certificate = new X509Certificate2(rawCert, passwordCertificate, X509KeyStorageFlags.DefaultKeySet);
    string server = "gateway.push.apple.com";
    using (TcpClient tcpClient = new TcpClient(server, 2195))
    {
        using (SslStream sslStream = new SslStream(tcpClient.GetStream()))
        {
            X509Certificate2Collection certs = new X509Certificate2Collection();
            certs.Add(certificate);
            sslStream.AuthenticateAsClient(server, certs, SslProtocols.Tls12 | SslProtocols.Tls11 | SslProtocols.Tls, false);
        }
    }

```
Exception

> System.ComponentModel.Win32Exception (0x8009030D): The credentials supplied to the package were not recognized at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface secModule, String package, CredentialUse intent, SCHANNEL_CRED scc) at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCHANNEL_CRED secureCredential) at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer) at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint) at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output) at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count) at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult) at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions) at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)

I'm sure the certificate is good because locally it works!
Strange thing: I installed Visual Studio on the server and executed the code it works too! Why on IIS it would not work?

.NET Standard 2.0
.NET Core 2.2.7
Windows Server 2016

**Comment by davidsh** [comment]
>it works locally

What kind of machine is your local dev machine? What version of Windows?

>Why on IIS it would not work?

Where did you install the PFX file? LocalMachine/MY store? or CurrentUser/MY store? What identity is the IIS server running under? It sounds like the private key is not accessible to the IIS process.

**Comment by xav-stargate** [comment]
> What kind of machine is your local dev machine? What version of Windows?
Windows 10 (last)
VS 16.3.5

> Where did you install the PFX file? LocalMachine/MY store? or CurrentUser/MY store
I don't have a pfx file, all is in the raw (cert + private key)

> What identity is the IIS server running under?
ApplicationPoolIdentity

**Comment by davidsh** [comment]
What server are you using when you run it "locally" and it works?

I think the problem is related to IIS not being able to read the private key. Normally, the private key has to be in the LocalMachine/MY store in order for IIS (which runs as a system process) to read it properly.

How did you create this public/private key in the first place if it is not a PFX file?

**Comment by xav-stargate** [comment]
> What server are you using when you run it "locally" and it works?

A console app

> I think the problem is related to IIS not being able to read the private key. Normally, the private key has to be in the LocalMachine/MY store in order for IIS (which runs as a system process) to read it properly.


Good news, I change idendity from ApplicationPoolIdentity to NetworkService and it's work !

What should I deduce?
It is better to use which identity?

**Comment by SteveSyfuhs** [comment]
I think you're hitting a user profile issue, which is what @davidsh is describing. Internally the private key gets shoved into an in-memory or temporary on-disk certificate store, which lives in the logged on session's user profile. AFAIK the profile isn't loaded by default for ApplicationPoolIdentity whereas Network Service already has one.

**Comment by davidsh** [comment]
>Good news, I change identity from ApplicationPoolIdentity to NetworkService and it's work !

Since you were able to resolve your problem, we can close this issue now.
