### ISSUE TITLE
Issue with access a deeply nested property via dynamic object

### ISSUE THREAD

**Issue by mihail-vladov** [dotnet/corefx#42083]
Hello,

I am experiencing an issue with dynamic objects in .NET Core 3.0. The issue is observed in an attempt to access a deeply nested property. The same code works as expected for 2.2 and .NET Framework. I haven't tested with .NET Core 3.1.

I am implementing IDynamicMetaObjectProvider and I suspect that the parameter of IDynamicMetaObjectProvider.GetMetaObject method has the wrong value in the described use case above.

I have prepared a sample project that illustrates the problem. Here is a [link](https://github.com/mihail-vladov/IssueWithCreatingDynamicObject). For better representing the issue, I am creating a simple tree for which I am creating a dynamic object.
The result is that for .NET Core 2.2 the resulted dynamic object has more nested nodes than the one from .NET Core 3.0. 

If this is not a bug please provide information on what I am doing wrong.

**Comment by cston** [comment]
It looks like the behavior changed as a result of https://github.com/dotnet/corefx/pull/28664 where the dynamic binder is reused in more cases.

In your repro, `BindGetMember()` is returning a `DynamicMetaObject` representing a `ConstantExpression`. Given that, should the `BindingRestrictions` limit the reuse to the specific receiver instance?

For instance, using `BindingRestrictions.GetInstanceRestriction(Expression, Value)` in the value returned from `BindGetMember()` seems to work.

cc @vsadov

**Comment by VSadov** [comment]
Yes, A restriction like `BindingRestrictions.GetExpressionRestriction(Expression.Constant(true))` makes the binding applicable to more cases than you probably want.

**Comment by mihail-vladov** [comment]
Hi @cston the suggestion with BindingRestrictions.GetInstanceRestriction(Expression, Value) has fixed the problem. 
Thank you.

**Comment by cston** [comment]
Thanks @mihail-vladov, and thanks for reporting this change in behavior from 2.2.
