### ISSUE TITLE
System.IO.Compression.GZipStream Flush() documentation is off

### ISSUE THREAD

**Issue by maghis** [dotnet/corefx#42086]
The current documentation for `Flush()` states:
```
The current implementation of this method has no functionality.
```
After testing and reviewing the codebase it looks like it's indeed flushing the buffers of `DeflateStream`.

**Comment by carlossanlop** [comment]
Interesting. Thanks for reporting.

I will transfer this bug to the appropriate repo and assign it to myself to address it soon.

**Comment by carlossanlop** [comment]
This issue was moved to dotnet/dotnet-api-docs#3404
