### ISSUE TITLE
Add warning if generic type passed to OfType cannot possibly match

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/corefx#42093]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/776488/add-warning-if-generic-type-passed-to-oftype-canno.html)._

---
In code like this:

ICollection&lt;TypeA&gt; collection;
collection. OfType&lt;TypeB&gt;()

If TypeA is not assignable from TypeB, then the compiler should show a warning. I know OfType is an extension method and its behavior does not require any such constraint, but surely its purpose is defeated if that's not the case. There is already a precedent for this warning, when, for example &quot;TypeA as TypeB&quot; would be an impossible cast.

---
#### Jane Wu [MSFT] on 10/14/2019, 07:52 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by stephentoub** [comment]
Thank you for the suggestion.  I absorbed this into https://github.com/dotnet/corefx/issues/40739.
