### ISSUE TITLE
Unable to find assembly exception,when perform deserialization using resource manager in Netcore

### ISSUE THREAD

**Issue by mageshsankar** [dotnet/corefx#42091]
I have an custom control in my application, one of its property "LayoutStream" is byte[] type and it is serializable property. Currently I have ported my application from 4.6 framework to NetCore 3.0 project. 

While run ported NetCore 3.0 project, im getting below exception when deserialize the data from resx file.

**Exception::**
`Exception thrown: 'System.Runtime.Serialization.SerializationException' in System.Runtime.Serialization.Formatters.dll
An unhandled exception of type 'System.Runtime.Serialization.SerializationException' occurred in System.Runtime.Serialization.Formatters.dll
Unable to find assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'`

Here I have attached sample application which contain both framework project and NetCore project. While run framework project it works as excepected but it fails with NetCore project.

In the attached project, i have created custom control which has serliazable property called LayoutStream. You can able to reproduce it while run the attached NetCore project.

Sample Link: https://drive.google.com/file/d/1WbRSuxCSQKKT5tVoH-6jY5m9t3luYRgb/view

Here CustomControl added as assembly. Please find code for CustomControl

Custom Control
`[ToolboxItem(true)]
    public class Custom : Control
    {
        public Custom()
        {
            this.Size = new Size(30, 30);
            this.BackColor = Color.Red;
            LayoutStream = new CustomControl.SerializableByteList();
        }
        private CustomControl.SerializableByteList layoutStream;
        
        public CustomControl.SerializableByteList LayoutStream
        {
            get
            {
                return layoutStream;
            }
            set
            {
                layoutStream = value;
            }
        }
    }

[Serializable]
    public class SerializableByteList
    {
        public SerializableByteList()
        {
            Bytes = new List<byte>();
        }

        public List<byte> Bytes { get; set; }
    }`

![image](https://user-images.githubusercontent.com/55440472/66893277-500f5780-f00b-11e9-9913-a7f653164cd5.png)

Please suggest any  solution to resolve this issue.

**Comment by ericstj** [comment]
Fixed in master with https://github.com/dotnet/corefx/pull/42102.  Keeping this open to port to 3.1.

**Comment by ericstj** [comment]
Fixed in https://github.com/dotnet/corefx/pull/42209
