### ISSUE TITLE
Add awaitable API for waiting on Ctrl+C/sigterm

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#42105]
Today to await/wait for Ctrl+C/sigterm looks something like this:

```C#
var tcs = new TaskCompletionSource<object>();
Console.CancelKeyPress += (sender, e) => tcs.TrySetResult(null);
await tcs.Task;
```

It would be great if there was something more first class:

```C#
public partial static Console
{
    public static Task WaitForCancelKeyPress(CancellationToken cancellationToken = default);
}
```

That would let consumers await the task.

```C#
await Console.WaitForCancelKeyPress();
```

Open questions:
- What's the equivalent of:
    ```c#
    Console.CancelKeyPress += (sender, e) =>
    {
        e.Cancel = true;
    };
    ```
- Maybe this would be better as a CancellationToken? But you can't await those either... So maybe if we ever do this https://github.com/dotnet/corefx/issues/23590. You could convert this Task into a `CancellationToken` and use it for cancelling things.

**Comment by jkotas** [comment]
A similar wrapper can be built for any event, but I do not think it is something we would want to do that.

What makes `CancelKeyPress` special to deserve this wrapper?

**Comment by davidfowl** [comment]
It's pretty common for long running tools to wait for exit (e.g. https://github.com/dotnet/diagnostics/blob/a37afe8d86522d03bbdb89ca7afb2d29c4841219/src/Tools/Common/ConsoleCancellation.cs#L33), it's the logical thing to do when we have async main and you don't want to quit the application based on any random key press (people use Console.Read()) today.

> A similar wrapper can be built for any event, but I do not think it is something we would want to do.

I think it's our job to look at how many people are writing these very common wrappers and putting them in the BCL where it makes sense (like this https://github.com/dotnet/corefx/issues/12039).

**Comment by jkotas** [comment]
> https://github.com/dotnet/diagnostics/blob/a37afe8d86522d03bbdb89ca7afb2d29c4841219/src/Tools/Common/ConsoleCancellation.cs#L33

This method is not used anywhere in the repo. It is dead code.

**Comment by khellang** [comment]
I've written this code a ton of times. Just a quick [GitHub search](https://github.com/search?q=CancelKeyPress+TrySetResult&type=Code) shows quite a few others as well.

**Comment by davidfowl** [comment]
@jkotas I know but that's not evidence that it's not useful, there's lots of code on the internet that does the same thing that isn't dead code.

@khellang I was just doing that search!

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/34831
