### ISSUE TITLE
Span<T>.IndexOf - Array?

### ISSUE THREAD

**Issue by Symbai** [dotnet/corefx#42131]
Wouldn't it be nice to have an official API to search within a span for an array? I could imagine it happens quite often that developers use IndexOf and then look ahead if it matches against an array. At least I do a lot of times. 

```
var bla =  new char[] {'a', 'b', 'c', 'd', 'e'};
var index = bla.AsSpan().IndexOf({ 'b', 'c'});

var bla = new byte[] {0x1, 0x2, 0x3, 0x4, 0x5};
var index = bla.AsSpan().IndexOf( { 0x2, 0x3});
```

Or even more advanced with null-able feature to search with wildcard support?

```
var bla =  new char[] {'a', 'b', 'c', 'd', 'e'};
var index = bla.AsSpan().IndexOf({ 'b', null, 'd'});

var bla = new byte[] {0x1, 0x2, 0x3, 0x4, 0x5};
var index = bla.AsSpan().IndexOf( { 0x2, null, 0x4});
```

**Comment by EgorBo** [comment]
I think this API already exists in `MemoryExtensions` e.g. https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/MemoryExtensions.cs#L134

**Comment by stephentoub** [comment]
It does :)

**Comment by Symbai** [comment]
True but it does not have wildcard support
