### ISSUE TITLE
XML Comments Guid.ToString()

### ISSUE THREAD

**Issue by brettrowberry** [dotnet/corefx#42153]
IntelliSense doesn't give any information about the formatting options for the .ToString() method on the Guid type:

> The format parameter can be "N", "D", "B", "P", or "X". If format is null or an empty string (""), "D" is used. https://docs.microsoft.com/en-us/dotnet/api/system.guid.tostring?view=netcore-3.0

# Ideas
1. Update XML comments
2. Add an overload that accepts an enum that has descriptive names and documentation

**Comment by MV10** [comment]
enums are numeric but this is a perfect use-case supporting an ongoing discussion about string-based enums:

https://github.com/dotnet/csharplang/issues/2849

**Comment by brettrowberry** [comment]
@MV10 I hadn’t considered string-based enums. Cool. I’m for anything that provides documentation within the context of a user’s editor.

**Comment by danmosemsft** [comment]
@brettrowberry thanks for reporting. Intellisense text actually comes from https://github.com/dotnet/dotnet-api-docs/ not from this repo. (We do sometimes seed from this repo)

Do you want to open a PR or issue against https://github.com/dotnet/dotnet-api-docs/ ?

**Comment by brettrowberry** [comment]
I was hoping you’d say that. Thanks!

**Comment by brettrowberry** [comment]
Created https://github.com/dotnet/dotnet-api-docs/issues/3426
