### ISSUE TITLE
NetEventSource can throw on the completion port callback thread.

### ISSUE THREAD

**Issue by joshudson** [dotnet/corefx#42161]
This is the first of a class of bugs of the same form that we call the heart of darkness. They're all of the same basic form, doing something dodgy inside of an IO completion callback.

Completion port callbacks must not fail, but must eventually reach `ThreadPool.QueueUserWorkItem` or `ThreadPool.UnsafeQueueUserWorkItem` with the original continuation in application code, or the entire application deadlocks. Simply using `ExecutionContext.Run` to get out of the completion port thread doesn't help.

    src/System.Net.Sockets/src/System/Net/Sockets/BaseOverlappedAsyncResult.Windows.cs: 74:                if (NetEventSource.IsEnabled) NetEventSource.Info(null, $"errorCode:{errorCode} numBytes:{numBytes} nativeOverlapped:{(IntPtr)nativeOverlapped}");

calls `String.Format(string, object[])` directly, which can throw `OutOfMemoryException` before even making the call.

In this particular case, the solution is to wrap the lines in `try { } catch { }`.

**Comment by davidsh** [comment]
I agree we should fix this pattern of code.

Did you discover this because you ran into this failure? Or was this just observed by code inspection?

**Comment by joshudson** [comment]
@davidsh : We've hit the deadlock due to this pattern of code. We don't know if it's this instance or not. There are more of them.

**Comment by joshudson** [comment]
So I've logged both of the ones I currently know about that don't involve legacy APIs. I wouldn't mind putting up pull requests for these two once we agree we like the approach.

**Comment by davidsh** [comment]
>I wouldn't mind putting up pull requests for these two once we agree we like the approach.

It's easier to discuss these things with a real PR example. So, feel free to submit a PR with your approach.

**Comment by karelz** [comment]
Triage:
Looks like we don't have enough evidence or clarity what exactly is wrong and what should happen.
OOM happening during logging is perfectly fine and by design -- we do not optimize for super low memory scenarios.
