### ISSUE TITLE
Graphics.DrawString 中文乱码的问题

### ISSUE THREAD

**Issue by dotnetdot1** [dotnet/corefx#42173]
我发现使用nuget安装的System.Drawing.Common 在源码里面的 api是
[DllImport("libgdiplus", ExactSpelling=true)]
internal static extern int GdipDrawString(IntPtr graphics, string text, int len, IntPtr font, ref RectangleF rc, IntPtr format, IntPtr brush);
没有CharSet标识，导致在centos下 DrawString 中文是乱码，将此代码改成
 [DllImport("gdiplus", CharSet = CharSet.Unicode)]
        static internal extern int GdipDrawString(IntPtr graphics, string text, int len, IntPtr font, ref RectangleF rc, IntPtr format, IntPtr brush); 后中文则可正常，但在源码文件https://github.com/dotnet/corefx/blob/master/src/System.Drawing.Common/src/System/Drawing/GdiplusNative.cs 中又看到是加了CharSet = CharSet.Unicode 的，如果可以请更新下nuget上的包，以便解决此问题

**Comment by ericstj** [comment]
Thank you for raising this issue.

Translation above is that we are missing `CharSet` from GdipDrawString. 

This is a duplicate of https://github.com/dotnet/corefx/issues/41292

Fixed in https://github.com/dotnet/corefx/pull/42015.
