### ISSUE TITLE
System.Net.Security not found on Linux

### ISSUE THREAD

**Issue by saurabh500** [dotnet/corefx#4217]
I installed the runtime version 1.0.0-rc1-16048 on Ubuntu 14.04 and tried to connect to Azure Sql database on Linux 
When I run the test I receive the error 
System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

I checked the runtime folder coreCLR and I dont see System.Net.Security.dll in there.

Is this a packaging issue?

**Comment by davidsh** [comment]
cc: @ericstj

**Comment by GuardRex** [comment]
Maybe similar/same ... certainly the same exception: https://github.com/dotnet/corefx/issues/3927

@saurabh500 Try testing with ...
```
"System.Net.Security": "4.0.0-beta-23405"
```
... or ...
```
"System.Net.Security": "4.0.0-beta-*",
"Microsoft.NETCore.Platforms": "1.0.1-beta-*"
```
... as a workaround until they get a chance to look.

**Comment by ericstj** [comment]
If a direct reference fixes it then it's the known issue where DNX/Nuget won't merge in the platform specific packages when the x-plat package isn't in the compile graph.

**Comment by GuardRex** [comment]
@ericstj Is there an open issue on that one? I can close #3927 and track the known issue.

**Comment by ericstj** [comment]
We actually have a feature request out to Nuget to address this.  Not sure how they are tracking it.  Let me look into that.

**Comment by saurabh500** [comment]
cc: @natemcmaster

**Comment by ericstj** [comment]
I opened this corefx issue: https://github.com/dotnet/corefx/issues/4230
As well as this Nuget feature: https://github.com/NuGet/Home/issues/1660

**Comment by ericstj** [comment]
Closing this out and tracking with #4230.
