### ISSUE TITLE
Default HttpRequestMessage.Version is "1.1" for .Net Core 3.0?

### ISSUE THREAD

**Issue by khteh** [dotnet/corefx#42180]
# Issue Title
Default `HttpRequestMessage.Version` is "1.1" for .Net Core 3.0?

# General
I expect `HttpRequestMessage.Version` to default to 2.0 for .Net Core 3.0 but this is NOT the case. The default value is still 1.1!

**Comment by scalablecory** [comment]
Correct, the default is 1.1.

To default this to 2.0 in a usable way, we would first need to support [h2c upgrade](https://github.com/dotnet/corefx/issues/41621).
