### ISSUE TITLE
File.Move() when the destination does not contain a path the source file gets deleted and no exception is thrown

### ISSUE THREAD

**Issue by jhirschdrg** [dotnet/corefx#42197]
`File.Move(@"C:\abc.txt, "abc.txt");`

If the destination is not a path and not null or empty just a string, the file gets deleted, and no exception is thrown

**Comment by danmosemsft** [comment]
That’s not good! @buyaa-n  can you confirm?

**Comment by buyaa-n** [comment]
Sure I will

**Comment by buyaa-n** [comment]
It is working as expected in .Net core 2.2, 3.0, 3.1. @jhirschdrg i think you are mistaking the output of your app. When you are not set the whole path output will be in `\bin\[Build Mode]\[Target framework` of your current working directory. You can find from there your "abc.txt" file. For example in my case it is in `\ConsoleApp5\bin\Debug\netcoreapp3.0\abc.txt`.

**Comment by jhirschdrg** [comment]
Thanks, @buyaa-n.

It was in production code, I was searching with the windows search in the app directory but I was unable to find it.

I checked now in the user's home directory `c:\users\username` and found it.

Now I see that it's even in the [Microsoft Docs ](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.move)in the remarks section at the bottom

**Comment by buyaa-n** [comment]
Great, then I think we can close the issue, thanks for confirmation
