### ISSUE TITLE
Unexpected behavior in Dictionary methods Remove and Clear (.NET Core)

### ISSUE THREAD

**Issue by dev-masih** [dotnet/corefx#42212]
I am trying to implement a caching mechanism for enumerating collections safely, and I am checking if all modifications of the built-in collections are triggering an `InvalidOperationException` to be thrown by their respective enumerators. I noticed that in the .NET Core platform the [`Dictionary.Remove`][1] and [`Dictionary.Clear`][2] methods are not triggering this exception. Is this a bug or a feature?

Example with `Remove`:

    var dictionary = new Dictionary<int, string>();
    dictionary.Add(1, "Hello");
    dictionary.Add(2, "World");
    foreach (var entry in dictionary)
    {
        var removed = dictionary.Remove(entry.Key);
        Console.WriteLine($"{entry} removed: {removed}");
    }
    Console.WriteLine($"Count: {dictionary.Count}");

Output:

> [1, Hello] removed: True  
> [2, World] removed: True  
> Count: 0  

Example with `Clear`:

    var dictionary = new Dictionary<int, string>();
    dictionary.Add(1, "Hello");
    dictionary.Add(2, "World");
    foreach (var entry in dictionary)
    {
        Console.WriteLine(entry);
        dictionary.Clear();
    }
    Console.WriteLine($"Count: {dictionary.Count}");

Output:

> [1, Hello]  
> Count: 0  

The expected exception is:

> InvalidOperationException: Collection was modified; enumeration operation may not execute.  

...as is thrown by the method `Add`, and by the same methods in .NET Framework.

.NET Core 3.0.0, C# 8, VS 2019 16.3.1, Windows 10

  [1]: https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.remove
  [2]: https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.clear

**Note:** This is a StackOverflow question [here](https://stackoverflow.com/questions/58617273/unexpected-behavior-in-dictionary-methods-remove-and-clear-net-core) and I'm not the original poster of this question.

**Comment by mjwills** [comment]
This does appear to be a bug, since the docs clearly state the old .NET Framework behaviour is the expected behaviour (i.e. it is the **contract**, not just old behaviour):

> An enumerator remains valid as long as the collection remains unchanged. If changes are made to the collection, such as adding, modifying, or deleting elements, the enumerator is irrecoverably invalidated and the next call to MoveNext or IEnumerator.Reset throws an InvalidOperationException.

If this is no longer the case, then **at the very least** the docs need to be updated to be clear what is the specification (contract) and what isn't.

**Comment by dev-masih** [comment]
https://github.com/dotnet/corefx/issues/29979#issuecomment-399806076

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/42123
