### ISSUE TITLE
System.Text.Json DictionaryKeyPolicy is ignored if entry value is null

### ISSUE THREAD

**Issue by uncleyo** [dotnet/corefx#42220]
When setting `DictionaryKeyPolicy = JsonNamingPolicy.CamelCase;`, only non-null value entries have their keys properly converted.

I believe it is because the key is only converted inside the else branch [here](https://github.com/dotnet/corefx/blob/d3c298496e9dbdc35008efcaa6c863286f211170/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.HandleDictionary.cs#L148-L157).

I assume this is a bug, at least I cannot imagine this would be an expected and desired behavior.

**Comment by nickalbrecht** [comment]
I just ran into this as well. Makes for really inconsistent behaviour when trying to use the a Json result from asp.net core app because the Json object might be the expected case in instance and a different casing in another.

**Comment by ericstj** [comment]
Fixed in 3.1. Thanks for the report!

**Comment by uncleyo** [comment]
That was quick! Was considering to make this my own first contribution to the repo, but you've nailed it, people!
