### ISSUE TITLE
Max Array Length Property/Method

### ISSUE THREAD

**Issue by mikernet** [dotnet/corefx#42293]
There are a lot of variables that factor into the max allowed array size (runtime implementation, 32 vs 64 bit, size of the data type, `gcAllowVeryLargeObjects` config, etc). Unless I'm missing something, there doesn't seem to be a particularly easy way to determine this at runtime for the current executing environment (please correct me if I'm wrong).

It would be rather helpful if there was a property or method akin to `Array.GetMaxLength<int>()` which returns the maximum length of an array of the given type in the current runtime environment.

**Comment by jkotas** [comment]
Sounds reasonable to me.

**Comment by Clockwork-Muse** [comment]
...Out of curiosity, are we expecting the answer to be constant for the life of the program, or could the value returned decrease if multiple very large arrays are allocated?

**Comment by mikedn** [comment]
> It would be rather helpful if there was a property or method akin to Array.GetMaxLength<int>()

Doesn't sound very useful to me:

* gcAllowVeryLargeObjects is enabled by default in .NET Core so unless this API makes it to .NET Framework (and it very likely won't) this is not a big selling point for such an API
* On 32 bit platforms the array length is severely constrained by available contiguous memory so it's not clear what value are you going to get from an API that tells you that the max length of an `int` array is 2GB / 4 when the chance of allocating such an array is exactly 0. And the chance of allocating half or even a quarter of that is not much higher than 0.

It may be useful to expose the max array length as a simple constant, mainly because it's intentionally a bit lower than `Int32.MaxValue` and some people may be surprised by that.

**Comment by scalablecory** [comment]
What is the use case for this?

**Comment by jkotas** [comment]
Take a look at how we are using internal version of this in collection classes, etc.:

https://github.com/dotnet/coreclr/search?q=%22Array.MaxArrayLength%22&unscoped_q=%22Array.MaxArrayLength%22
https://github.com/dotnet/coreclr/search?q=%22Array.MaxByteArrayLength%22&unscoped_q=%22Array.MaxByteArrayLength%22

**Comment by mikernet** [comment]
@Clockwork-Muse My expectation is that it would be constant. It would be an "arrays up this size are possible on this runtime" number. 

@mikedn Even if .NET Core has it enabled by default, there could still be differences on various 64 bit runtimes (i.e. mono, iOS/Andriod, some future .NET Standard platform, Raspberry pi, etc) or a user of our library could have very large objects disabled.

You make a good point about there being address space issues on 32 bit that *usually* prevent large arrays from being created, but I'm fine with leaving that up to the user of our library to deal with if needed.

@scalablecory There are a couple use cases. One is similar to `List<T>` where array size is doubled on expand but I don't want to go over the limit. Another is a binary serializer suitable for use on very large objects in some situations. It has object sizing functionality that I would like to throw an exception if you try to measure an object that will never fit into an array.

@jkotas Thanks, I'll have a look at that later when I have a sec to see if it'll help!

**Comment by mikernet** [comment]
Hmmm...how does `Span<byte>` handle large array sizes > 2B elements? The Length is an `Int32` and there is no `LongLength`.

**Comment by mikernet** [comment]
Looks like it just throws `OverflowException` 😢 Looks like half my use case might be a bit of a moot point.

**Comment by mikernet** [comment]
Nevermind the last couple questions, everything makes sense now and all is well. Considering large array support is the default in .NET Core then I'll just keep it simple here and use the constants similarly to the code @jkotas linked to.
