### ISSUE TITLE
NetworkCredentials leaks password copies due to lack of disposable pattern implementation

### ISSUE THREAD

**Issue by daviburg** [dotnet/corefx#42301]
A class which owns a disposable resource needs to implement the disposable pattern itself. This is particularly important for SecureString which upon dispose calls Close on the internal safehandle for security reasons. NetworkCredentials class in .NET Core, and Framework for that matter, forgot to implement IDisposable, creates copies of the SecureString on each get and set call of the password accessor methods.

https://github.com/dotnet/corefx/blob/master/src/System.Net.Primitives/src/System/Net/NetworkCredential.cs
https://referencesource.microsoft.com/#mscorlib/system/security/securestring.cs
https://referencesource.microsoft.com/#mscorlib/system/runtime/interopservices/safehandle.cs,7a33560846dca479

So not only does the internal copy taken by NetworkCredentials never gets dispose, the copy on get implementation is a very bizarre pattern which appear to assume that the caller knows to be responsible for the disposal.

Instead the NetworkCredentials class should:
a) Implement disposable interface and pattern, so that if a securestring password is set or created for its internal member variable, it disposes of it properly;
b) Do not copy on get accessor, rather let the caller decide to copy at all if they are taking a reference (and they might just use the password immediately while NetworkCredentials is inside using scope so won't need to do and track any copy). Get accessors in general should not have hidden side effects. Because this would be a potential breaking change to caller who built an assumption on the old behavior, this means a new property is now required to correct the pattern so folks can migrate to a property that doesn't create leaks.

**Comment by GrabYourPitchforks** [comment]
Related: https://github.com/dotnet/corefx/issues/40393, which discusses why `SecureString` isn't actually a good building block for code which handles credentials.

**Comment by scalablecory** [comment]
I don't know that we could implement `IDisposable` on `NetworkCredential` without it being a possible breaking change for anyone inheriting from the class.

**Comment by karelz** [comment]
Triage: We don't believe in `SecureString` anymore, we don't want to build more APIs to encourage its usage. Closing.
