### ISSUE TITLE
Request toString()

### ISSUE THREAD

**Issue by willmotil** [dotnet/corefx#42310]
**int** **float** **double** types ect.  when you call .ToString() on them in dot net all create garbage that must be collected. It's infuriating noob and been passed on by for how many years now ?.

I got around this with a wrapper that just spit out characters from the value itself by simply doing the decimal to char conversion myself. Using a ugly fat noob wrapper around StringGarbageBuilder. 
That typically outperforms it even though i massively bloated it. 
Because numbers kind of need to be converted to characters in most apps, its kinda Not unheard of for that to happen in just about every single app ever made, a lot.

So.... is it possible.... since you guys are doing this new thing. That while you are at it,,,, 
You can investigate how that conversion takes place internally. 
If it is really, truly, absolutely, necessary to have to generate collectable garbage from all value.ToStrings() calls.
every single time !
on every single number to string!
with no way to stop it from happening or a way to get around it that makes sense ! 

I believe this is the No1 cause of garbage collections in any application by far for anyone who is not actively trying to prevent it or aware of it. Most people aren't even aware that this is a huge source of collections.

It most certainly should not be such a pain in the --- to get around it. c# has been around a long time now. Considering how much converting a number to a string should be considered to occur why has this never been addressed ?. 

Yes i understand the problem of how do you return a string from a number without creating new string but there should be a way to feed a existing string or stringbuilder to ToString() or something so you don't have to create garbage that must be collected.

So file this under improved GC  one that doesn't have to follow behind a pig picking up after it.

Thank you.

**Comment by Random832** [comment]
Have you looked at the TryFormat functions? It won't work with a StringBuilder, but you can write the formatted value into a char array that way.

**Comment by willmotil** [comment]
> Have you looked at the TryFormat functions?
I have not i will, however think of the children.

I have a wrapper class around StringBuilder with the string overloads, I just append values doesn't handle float double exponent characters but its good enough for my needs typically. 
Since i mostly use it for any dynamic values that must be converted to strings.

**Comment by danmosemsft** [comment]
> myString.FromValue( someValue );

Do you mean to modify an existing string? Strings are immutable in.NET.

I agree that you likely are looking for Try Format. It accepts a Span, so it can be over any buffer (just not an existing string)
https://docs.microsoft.com/en-us/dotnet/api/system.double.tryformat?view=netcore-3.0

**Comment by GrabYourPitchforks** [comment]
Related: https://github.com/dotnet/coreclr/issues/20253

That issue tracks the runtime identifying that an object (such as the result of `myInt.ToString()`) is short-lived, allowing the memory to be reclaimed at the end of the frame. The general idea is that things should become more efficient automatically without requiring the developer to modify existing code.

**Comment by jkotas** [comment]
Another related issue: https://github.com/dotnet/csharplang/pull/2293

**Comment by willmotil** [comment]
Related: dotnet/coreclr#20253

Thank you c# jesus who ever pushed for this god bless you.
