### ISSUE TITLE
CurlHandler failing on OS X

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4233]
The SetSslOptions change from https://github.com/dotnet/corefx/pull/4121 causes CurlHandler to fail all requests on OS X, e.g.
```
04:26:47       System.Net.Http.HttpRequestException : An error occurred while sending the request.
04:26:47       ---- System.Net.Http.CurlException : An unknown option was passed in to libcurl
04:26:47       Stack Trace:
04:26:47             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
04:26:47             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
04:26:47             at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
04:26:47             at System.Net.Http.Functional.Tests.PostScenarioTest.<PostUsingAuthHelper>d__32.MoveNext()
04:26:47          --- End of stack trace from previous location where exception was thrown ---
04:26:47             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
04:26:47             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
04:26:47             at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
04:26:47             at System.Net.Http.Functional.Tests.PostScenarioTest.<PostNonRewindableContentUsingAuth_PreAuthenticate_Success>d__26.MoveNext()
04:26:47          --- End of stack trace from previous location where exception was thrown ---
04:26:47             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
04:26:47             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
04:26:47          --- End of stack trace from previous location where exception was thrown ---
04:26:47             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
04:26:47             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
04:26:47          --- End of stack trace from previous location where exception was thrown ---
04:26:47             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
04:26:47             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
04:26:47          ----- Inner Stack Trace -----
04:26:47             at System.Net.Http.CurlHandler.ThrowIfCURLEError(Int32 error)
04:26:47             at System.Net.Http.CurlHandler.SslProvider.SetSslOptions(EasyRequest easy)
04:26:47             at System.Net.Http.CurlHandler.EasyRequest.SetSslOptions()
04:26:47             at System.Net.Http.CurlHandler.EasyRequest.InitializeCurl()
04:26:47             at System.Net.Http.CurlHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
```

**Comment by kapilash** [comment]
Strange. I ran the functional tests multiple times since (my) morning on OSX. I haven't faced this problem so far. 

With the built-in libcurl, I get the one expected failure (for channel binding). Similar for libcurl with openssl.

**Comment by bartonjs** [comment]
Likewise, I'm not seeing this error on my mac.  OSX Yosemite (10.10.5).

Where are we failing?

**Comment by kapilash** [comment]
Seems like an older version of libcurl. The [libcurl documentation](http://curl.haxx.se/libcurl/c/libcurl-errors.html#CURLEUNKNOWNOPTION) says that if the return type is not supported, we will get ```CURLE_UNKNOWN_OPTION```. But [curl code](https://github.com/bagder/curl/blob/master/lib/url.c#L2054) returns ```CURLE_NOT_BUILT_IN```. The latter is what we [ignore in CurlHandler](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.SslProvider.cs#L31).

**Comment by stephentoub** [comment]
On the macs in the lab:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_mac_debug_tst/95/console

cc; @mmitche

**Comment by bartonjs** [comment]
@kapilash thanks, I guess I'll just add `CURLE_UNKNOWN_OPTION` to the list of ignored return codes.

**Comment by kapilash** [comment]
can we please get the version of libcurl on the lab machine?

**Comment by mmitche** [comment]
Mac appears to have libcurl3.dylib and libcurl4.dylib

**Comment by bartonjs** [comment]
@mmitche What's the lab equivalent for:

```
barton@MacbookPro:~/coreclr $ ls -al /usr/lib/libcurl*
lrwxr-xr-x  1 root  wheel      15 Feb 11  2015 /usr/lib/libcurl.3.dylib -> libcurl.4.dylib
-rwxr-xr-x  1 root  wheel  781616 Jul 23 21:14 /usr/lib/libcurl.4.dylib
lrwxr-xr-x  1 root  wheel      15 Feb 11  2015 /usr/lib/libcurl.dylib -> libcurl.4.dylib
```

My system claims to have 3, but just uses 4.

**Comment by stephentoub** [comment]
The mac in the lab shows this:
```
lrwxr-xr-x    1 root  wheel       15 Nov 12  2014 libcurl.3.dylib -> libcurl.4.dylib
-rwxr-xr-x    1 root  wheel   763392 Oct  8  2014 libcurl.4.dylib
lrwxr-xr-x    1 root  wheel       15 Nov 12  2014 libcurl.dylib -> libcurl.4.dylib
```

**Comment by kapilash** [comment]
What does ```curl --version``` print?

On my system, I have

>   Apples-MacBook-Pro:System.Net.Http kapilash$ curl --version
curl 7.43.0 (x86_64-apple-darwin14.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets

**Comment by stephentoub** [comment]
```
curl 7.37.1 (x86_64-apple-darwin14.0) libcurl/7.37.1 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IPv6 Largefile NTLM NTLM_WB SSL libz 
```

**Comment by mmitche** [comment]
7.43.0 libcurl same version

**Comment by stephentoub** [comment]
The machine I posted details for was the mac on which the failing tests ran.  The machine @mmitche posted details for was another mac in the lab.  So they have different versions installed.

The answer seems to be both updating the macs in the lab to be consistent and fixing the code to treat this error as if the functionality isn't available.

**Comment by bartonjs** [comment]
The behavior change seems to have come from curl 7.39, which is why the one mac is failing (7.37).  I've gone ahead and changed it to accept both error codes, PR coming momentarily.
