### ISSUE TITLE
FileSystemWatcher tests on MacOS constantly fail on Outerloop CI run

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#42344]
https://dev.azure.com/dnceng/public/_build/results?buildId=414240&view=ms.vss-test-web.build-test-results-tab

![image](https://user-images.githubusercontent.com/7684835/68095358-a11da900-fe5d-11e9-8e9a-1ae9f4b1ba03.png)

**Comment by davidsh** [comment]
I plan to disable these tests so that we can have GREEN for CI in Outerloop

**Comment by danmosemsft** [comment]
https://github.com/dotnet/corefx/pull/40543

**Comment by davidsh** [comment]
@wfurt 

#40543 didn't fix everything. And these specific tests are always failing Outerloop MacOS CI run making outerloop red and not green. So I will disable these tests against this issue.

**Comment by wfurt** [comment]
#40543  only touched Linux implementation. #41963  may help. I was planning to look at them but I got distracted with 3.1 investigation.

**Comment by aik-jahoda** [comment]
#41963 doesn't fix this outer loop test

**Comment by davidsh** [comment]
>#40543 only touched Linux implementation. #41963 may help. I was planning to look at them but I got distracted with 3.1 investigation.

>#41963 doesn't fix this outer loop test

Thanks! I understand those fixes probably didn't help with this issue. But it's important that we get test failures either fixed or tests disabled so that CI gets to GREEN.

That's why I disabled the tests now. Then later, when someone has the time, they can investigate the failures. But at least CI will be improved for the team since people have to always spend time chasing after RED failures.

**Comment by wfurt** [comment]
yes, I agree. I will setup run in loop and I'll investigate as time permit. One thing we discovered with @aik-jahoda is that you can get events from before you subscribed. I don't know if that is root cause but that behavior is specific to MacOS and we did not find way how to avoid it.

**Comment by danmosemsft** [comment]
I linked #40543 merely because I remembered it touched the same test.

**Comment by wfurt** [comment]
It seems like #41963  made it worse. I get failures now when running tests locally. 
I will take look. 

```
   Starting:    System.IO.FileSystem.Watcher.Tests (parallel test collections = on, max threads = 8)
      System.IO.Tests.File_Move_Tests.File_Move_Multiple_From_Watched_To_Unwatched_Mac(filesCount: 2) [FAIL]
        Expected events (6) count doesn't match triggered events count (2):
        Deleted /var/folders/z6/nnqqzwmd6lz3dttlnjp_vgp00000gn/T/File_Move_Tests_wdzydv2y.l0y/FileMove_Multiple_FromWatchedToUnwatched_192_9a4207af/dir_watched/file0
        Deleted /var/folders/z6/nnqqzwmd6lz3dttlnjp_vgp00000gn/T/File_Move_Tests_wdzydv2y.l0y/FileMove_Multiple_FromWatchedToUnwatched_192_9a4207af/dir_watched/file1
        Expected: True
        Actual:   False
        Stack Trace:
          /Users/furt/github/wfurt-corefx-watcher/src/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs(558,0): at System.IO.Tests.FileSystemWatcherTest.ExpectEvents(FileSystemWatcher watcher, Int32 expectedEvents, Action action)
```

**Comment by aik-jahoda** [comment]
the `File_Move_Multiple_From_Watched_To_Unwatched_Mac` expect FSEventStream receive old event however it seems it somehow behaves randomly as the error indicates FSEventStream received new events only.

I tried to sync the filesystem however it doesn't affect the FSEventStream at all.

`File_Move_Multiple_From_Watched_To_Unwatched_Mac` is not part of the outer loop tests.

**Comment by wfurt** [comment]
It seems like System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Rename_NotAffectEachOther is regression caused by #40611. I did not see Outerloop executed on that PR but the run is old. It fails ever since and it is sad we did not notice for such a long time. 
We now get Rename event instead of getting Create and Delete.
cc: @carlossanlop @JeremyKuhne @mandawah 

As far as File_Move_Multiple_From_Watched_To_Unwatched_Mac it seems like the test assume that we _will_ get events prior to Watcher creation. But in reality we _may_ get them. The coalescing of events depend on timer and perhaps other activities.  So we have race condition with system load and perhaps external activities.

**Comment by JeremyKuhne** [comment]
As far as the change in events I believe it was this discussion: https://github.com/dotnet/corefx/pull/40611#issuecomment-529581203

**Comment by wfurt** [comment]
I think that if fine - what ever we agreed to. But it is easy for external contributors to miss Outerloop @JeremyKuhne and we should notice failing tests IMHO.

**Comment by JeremyKuhne** [comment]
> we should notice failing tests IMHO.

Absolutely, just pointing out that the behavior change was expected. :)

**Comment by stephentoub** [comment]
Failed again here:
https://helix.dot.net/api/2019-06-17/jobs/1b698513-91ff-47b1-84a1-c095c8eeb9b4/workitems/System.IO.FileSystem.Watcher.Tests/files/console.d0c0e6dd.log
```
    System.IO.Tests.File_Move_Tests.File_Move_Multiple_From_Watched_To_Unwatched_Mac(filesCount: 1) [FAIL]
      Expected events (3) count doesn't match triggered events count (1):
      Deleted /var/folders/j1/76_p663903g5g2rg7ckqbv440000gy/T/File_Move_Tests_hepan0n0.4wy/FileMove_Multiple_FromWatchedToUnwatched_192_9877436f/dir_watched/file0 
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs(558,0): at System.IO.Tests.FileSystemWatcherTest.ExpectEvents(FileSystemWatcher watcher, Int32 expectedEvents, Action action)
        /_/src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.File.Move.cs(216,0): at System.IO.Tests.File_Move_Tests.FileMove_Multiple_FromWatchedToUnwatched(Int32 filesCount, Boolean skipOldEvents)
        /_/src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.File.Move.cs(43,0): at System.IO.Tests.File_Move_Tests.File_Move_Multiple_From_Watched_To_Unwatched_Mac(Int32 filesCount)
```
Please disable the test while it's investigated.  Thanks.
