### ISSUE TITLE
System.IO.Path.Combine seems to work differently from .NET framework

### ISSUE THREAD

**Issue by StephenLarkin** [dotnet/corefx#42369]
# General

Tested on .NET Core v2.1, 2.2, 3.0:

```C#
System.IO.Path.Combine("string\nwith", "other");
```

In .NET Framework this throws an Argument Exception as documented:

```C#
        // Exceptions:
        //   T:System.ArgumentException:
        //     One of the strings in the array contains one or more of the invalid characters
        //     defined in System.IO.Path.GetInvalidPathChars.
```

In .NET Core it returns the string with the newline character.

**Comment by scalablecory** [comment]
`Path` was changed to do minimal input checking. Rather, it is assumed that the filesystem will validate the path more correctly than what we were doing in the past.

**Comment by danmosemsft** [comment]
@StephenLarkin is this causing you trouble, or just something you happened to notice (eg broke unit tests)

The reason for the change @scalablecory mentioned is (1) we never could do the path validation exactly as well as the OS (2) it was redundant with the OS checks and actually showing up as a perf hit in customer traces.

**Comment by JeremyKuhne** [comment]
I wrote up a [blog post](https://blogs.msdn.microsoft.com/jeremykuhne/2018/03/08/system-io-in-net-core-2-1-sneak-peek/) that discusses the approach and things that changed.

We're catching up with our backlog on documentation, this one is tracked by https://github.com/dotnet/dotnet-api-docs/issues/1685.

cc: @carlossanlop for the docs issue

**Comment by StephenLarkin** [comment]
Thanks for the responses. @danmosemsft this was indeed something that we caught in our unit testing when migrating them from .NET Framework to .NET Core tests.

The reasoning behind the change makes a lot of sense to me. Thanks for letting me know. Just thought it looked weird as the docs didn't seem to match up with the functionality. Good to know that it's being tracked though.

**Comment by danmosemsft** [comment]
OK, thanks @StephenLarkin for reporting. I'll close this.
