### ISSUE TITLE
Regex.IsMatch too long execution (like 5 minute)

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/corefx#42375]
Regex.IsMatch in the code snippet below executed for too long with one string, but very fast with another very similar string. The problem seems to be in substring "++":

```c#
using System.Diagnostics;
using System.Text.RegularExpressions;

namespace test_app
{
    class Program
    {
        private static readonly Regex testRgx = new Regex(@"^\s*=\s*((\+|\-|)?\s*\d{1,5}([.,]\d{1,2})?\s*)+$", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant | RegexOptions.ExplicitCapture);

        static void Main(string[] args)
        {
            string value = "=145+20-105-145+180-10+22+40+22,5-37,5-160,5++86,5+42,5-64-75,16+53,34-1,53";

            Stopwatch stopwatch = new Stopwatch();
            stopwatch.Start();
            bool res = !testRgx.IsMatch(value);
            stopwatch.Stop();

            Trace.WriteLine($"IsMatch for '{value}' - " + stopwatch.ElapsedMilliseconds);

            Stopwatch stopwatch1 = new Stopwatch();
            stopwatch1.Start();
            bool res1 = !testRgx.IsMatch("=" + value);
            stopwatch1.Stop();

            Trace.WriteLine($"IsMatch for '{"=" + value}' - " + stopwatch1.ElapsedMilliseconds);
        }
    }
}
```

cc: @tarekgh

**Comment by danmosemsft** [comment]
You can simplify using a tool like https://regex101.com (it doesn't support .NET flavor regexes, but this is a valid PCRE one)
eg simplifying down to this still gives "catastrophic backtracking" https://regex101.com/r/m4bNmX/1

On the face of it, `((\+|\-|)?\d{1,5}([.,]\d{1,2})?)+$` against `145+180-10+40+22,160,86,` doesn't seem like it ought to backtrack too painfully. It says "any number of things, each that may start with + or -, followed by 1-5 digits, then possibly followed by a component that begins with , or . then 1-2 digits". There's not a lot of ambiguity there. But the only engine on that web page that seems to work is Javascript.

**Comment by danmosemsft** [comment]
Ah, I see. After a comma or period, the 2nd digit may be the last half of `\d{1,2}` or the first digit of `\d{1,5}`.

**Comment by tarekgh** [comment]
@danmosemsft I believe the original issue is opened in VS community portal https://developercommunity.visualstudio.com/content/problem/790808/regexismatch-too-long-execution-like-5-minute.html and @maryamariyan was logging this issue here to track it for net core as this issue is not meeting full framework bar to fix there.

**Comment by danmosemsft** [comment]
Ah, I see. Nevertheless, we do not plan to do a rearchitecture of our regex engine right now. @eerhardt has done an investigation of other options, which he'll be finishing up soon.

**Comment by danmosemsft** [comment]
I replied on that issue.
