### ISSUE TITLE
IDictionary<TKey, TValue> should not constrain TKey to notnull

### ISSUE THREAD

**Issue by sharwell** [dotnet/corefx#42386]
The `IDictionary<TKey, TValue>` interface is artificially constraining implementations to disallow null from key domains, even in cases where it is valid. This undermines the changes in API shape made for .NET relative to Java.

* Implementations may use `IEqualityComparer<T>` to avoid the need to directly access members of the keys
* Implementations such as `Dictionary<TKey, TValue>` have the option of further constraining the keys, but should not be required to do so

With the current interface definition, implementations must choose between supporting null keys and implementing `IDictionary<TKey, TValue>`.

**Comment by stephentoub** [comment]
I think you're right.  I see this buried deep in the docs:
"Implementations can vary in whether they allow key to be null."
