### ISSUE TITLE
why does *nix don't use iocp when i call  IO methods

### ISSUE THREAD

**Issue by changhengyu** [dotnet/corefx#42380]
why does *nix don't use iocp when i call  IO methods

**Comment by changhengyu** [comment]
does it use epoll ?please help me solve a problem

**Comment by FiniteReality** [comment]
IOCP is a Windows API for performing overlapped, asynchronous I/O: https://docs.microsoft.com/en-us/windows/win32/fileio/i-o-completion-ports

*NIX uses a different approach entirely to overlapped, asynchronous I/O, so using IOCP is like asking a chicken to quack like a duck: sure, they're both birds, but chickens don't quack and ducks don't cluck.

**Comment by changhengyu** [comment]
Yes I can understand your means, thank you . And I hope to know the impl of asynchronous I/O in *nix  by .net core.
