### ISSUE TITLE
support handling Json string to numeric property

### ISSUE THREAD

**Issue by dansiegel** [dotnet/corefx#42396]
# Description

When deserializing a json response that has a property that has been encoded as a string even though it is an int it will result in an exception from the Json Serializer.

## How to reproduce

Given the following Json:

```json
{
  "foos": [
    {
      "id": "123"
    }
  ]
}
```

When setting up the .NET object this will be deserialized to I am likely to realize that the id is a numeric type like:

```cs
public class Foo
{
    [JsonPropertyName("id")]
    public int Id { get; set; }
}
```

However when you use the JsonSerializer like:

```cs
var collection = JsonSerializer.Deserialize<FooCollection>(jsonString)
```

This will result in a JsonException: `The JSON value could not be converted to System.Int32.` with an inner InvalidOperationException `Cannot get the value of a token type 'String' as a number.`

## Expected

There should either be a built in JsonConverter that can handle this, a Serialization option to allow handling this, or it should just be smart enough to try to convert from string to any given numeric type.

**Comment by Tornhoof** [comment]
This looks like #39473

**Comment by ericstj** [comment]
/cc @steveharter 
Closing as duplicate.

**Comment by Going-Gone** [comment]
Trying to migrate from newtonsoft, and this is the biggest issue i'm facing. I'm having to create converters for every type. I'd love to use this, but I can't fathom all this converter middleware for an async deserializer.
