### ISSUE TITLE
X509Certificate: .pfx format unsupported on CoreCLR

### ISSUE THREAD

**Issue by PinpointTownes** [dotnet/corefx#424]
This snippet works on `aspnet50` but an exception is thrown on `aspnetcore50` (tested on Windows 7 and Windows 8.1):

```csharp
public static class Program {
    public static void Main(string[] args) {
        var assembly = typeof(Program).GetTypeInfo().Assembly;

        using (var resource = assembly.GetManifestResourceStream("Certificate.pfx"))
        using (var buffer = new MemoryStream()) {
            resource.CopyTo(buffer);

            var certificate = new X509Certificate2(buffer.ToArray(), "Owin.Security.OpenIdConnect.Server");

            Console.ReadLine();
        }
    }
}
```

![image](https://cloud.githubusercontent.com/assets/6998306/5743652/fdeb3562-9c1a-11e4-93db-1fec2523adcd.png)

```
{System.Security.Cryptography.CryptographicException: Impossible de trouver l’objet requis.

   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at System.Security.Cryptography.X509Certificates.X509Utils._QueryCertBlobType(Byte[] rawData)
   at System.Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromBlob(Byte[] rawData, Object password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password)
   at X509Certificate2.Program.Main(String[] args)}
```

Complete repro: https://github.com/PinpointTownes/X509Certificate-Bug

**Comment by davkean** [comment]
Thanks for filing the issue, we'll look into it when we can.

**Comment by YingP99** [comment]
The reason is the current implementation pass different certificate query flag on CoreClr, which doesn't include 'pfx' format. We have TFS bug for it already. We are going to fix it when porting the X509Certificate classes.

**Comment by PinpointTownes** [comment]
@davkean @YingP99 wonderful, thanks :smile:

**Comment by bartonjs** [comment]
@PinpointTownes Issue housekeeping :smile:.  I think that this has been fixed for quite a while (we even have [tests for it](https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.X509Certificates/tests/PfxTests.cs#L17)!), but wanted to make sure that your scenarios were working before hitting close.

**Comment by PinpointTownes** [comment]
@bartonjs ahhhh, really nice, thanks for the heads-up! :smile: 

First tests are really encouraging and everything works great so far.

On a related note, I just realized you had recently added PFX support for Core CLR on Linux (https://github.com/dotnet/corefx/pull/2574): any idea when the nightly packages including these changes will be uploaded on MyGet? :heart_eyes:

**Comment by bartonjs** [comment]
For Windows, it should be in http://www.nuget.org/packages/System.Security.Cryptography.X509Certificates/4.0.0-beta-23019 or later (and probably won't have any "which build lab built it" problems).

For non-Windows, I'm guessing tomorrow or Monday, based on the myget feed's update dates (being mostly Wednesdays and Mondays :smile:, about every 10ish days).

**Comment by bartonjs** [comment]
@PinpointTownes I'm going to go ahead and close the issue, since things seem to be working in the general case.  Anything else would probably warrant a specific issue.

**Comment by bartonjs** [comment]
@PinpointTownes https://www.myget.org/F/dotnet-core/api/v2/package/System.Security.Cryptography.X509Certificates/4.0.0-beta-23213 has been published, and has support for reading PFX.  Sorry for the delay :smile:.

**Comment by PinpointTownes** [comment]
@bartonjs nice, thanks!

Sadly, I can't test it yet because of this annoying issue: https://github.com/dotnet/roslyn/issues/4512 
(plus a few other ones like the buggy `Uri` class or the embedded resources crash, but they are far easier to work around :sunglasses:)
