### ISSUE TITLE
Non-async FileStream does not use fast path from Stream for Read/WriteAsync

### ISSUE THREAD

**Issue by poizan42** [dotnet/corefx#42419]
Stream.ReadAsync has a fast path (through BeginEndReadSync->BeginReadInternal) when Begin/EndRead isn't overriden in a derived class.

However FileStream does override these so the base implementation won't call them. But the FileStream implementation of ReadAsync delegates to the base implementation when the stream is opened non-async, which then won't use the fast path. It seems that FileStream.ReadAsync should just call BeginReadInternal directly in the case it is non-derived non-async, unless I'm missing something.

**Comment by stephentoub** [comment]
Thanks for the suggestion.  Addressed in https://github.com/dotnet/coreclr/pull/27737.
