### ISSUE TITLE
IronPython.Runtime.Exceptions.ImportExceptions: No module name job

### ISSUE THREAD

**Issue by davideveloper** [dotnet/corefx#42424]
If anyone could help me, I would appreciate it. I am running some Python codes from .NET which sends to call the Software - Autodesk Revit, it happens that when it is starting it sends me the Error 'IronPython.Runtime.Exceptions.ImportExceptions: No module name job'.

I have tried to verify the Python versions installed to see if I am wrong about something but it has the same error, I tried to make a Debug in my .NET code to verify if something I am not sending but I cannot find the cause.

They could support me.

![image](https://user-images.githubusercontent.com/7434352/68349043-5bf9b100-00c1-11ea-8180-8410496b0e4c.png)

**Comment by danmosemsft** [comment]
Hello @davideveloper this is a question for the owners of IronPython. It seems that may be maintained here https://github.com/IronLanguages/ironpython2 

Could you please close and reopen there?

**Comment by wfurt** [comment]
Your environment variables may be different. Try to set PYTHONPATH when creating Process. 
Also simple repro would be useful. Your post does not really have much to look at @davideveloper
