### ISSUE TITLE
Under what circumstances can StackFrame.GetMethod() return null? (netfx has non-null contract)

### ISSUE THREAD

**Issue by jnm2** [dotnet/corefx#42421]
I worked on a PR for Shouldly and a very painful thing that came up frequently was that `StackFrame.GetMethod()` returns `MethodBase?`. I couldn't figure out how to write any test that would make it return null. Furthermore, .NET Framework [has this implementation](https://referencesource.microsoft.com/#mscorlib/system/diagnostics/stackframe.cs,9aa99613c484eb3a):

```cs
        public virtual MethodBase GetMethod ()
        {
            Contract.Ensures(Contract.Result<MethodBase>() != null);
 
            return method;
        }
```

Has something changed in .NET Core that makes nulls possible? If so, what, so that I can document it and possibly write a test for it?

**Comment by stephentoub** [comment]
```C#
using System;
using System.Diagnostics;

class Program
{
    static void Main()
    {
        Console.WriteLine(new StackFrame(10).GetMethod() == null);
    }
}
```

**Comment by danmosemsft** [comment]
It looks like there are other more obscure ways, eg code leading here
https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/src/System/RuntimeType.CoreCLR.cs#L1716

**Comment by danmosemsft** [comment]
Seems resolved.

**Comment by jnm2** [comment]
@danmosemsft Yes, thank you.
