### ISSUE TITLE
Why does StackTrace.GetFrames() return `StackFrame?[]` instead of `StackFrame[]`?

### ISSUE THREAD

**Issue by jnm2** [dotnet/corefx#42422]
Under what circumstances can the array returned by `StackTrace.GetFrames()` contain a null element? I couldn't figure out how to write any test that would trigger this behavior.

**Comment by danmosemsft** [comment]
https://github.com/dotnet/coreclr/pull/23753#discussion_r272610977

**Comment by danmosemsft** [comment]
Oops, that's not what you asked - you're asking about what GetFrames() returns.

**Comment by danmosemsft** [comment]
Nope, I was right the first time. Does that answer your question?

**Comment by jnm2** [comment]
Thank you! That turns this into two more questions.

1. Why is the `StackTrace(StackFrame? frame)` constructor parameter annotated as nullable? Would you consider changing in 5.0?

2. If it must stay nullable, would you consider changing the behavior in 5.0 to:

   ```cs
   public StackTrace(StackFrame frame)
   {
       (_stackFrames, _numOfFrames) = frame is null
           ? (null, 0)
           : (new StackFrame[] { frame }, 1);
   }
   ```

**Comment by danmosemsft** [comment]
Removing the `?` would be a breaking change. We have [acknowledged ](https://github.com/dotnet/corefx/blob/master/Documentation/api-guidelines/nullability.md#breaking-change-guidance) we may need to make such breaking changes, but this may not be enough motivation.

On the face of it your second suggestion sounds reasonable. @stephentoub do you see any reason why it accepts null? Or, conversely, how do you feel about removing the `?`?

**Comment by stephentoub** [comment]
> Why is the `StackTrace(StackFrame? frame)` constructor parameter annotated as nullable?

It's not:
https://github.com/dotnet/coreclr/blob/1b12053ffffc36ad73ad83f7ce111c891c4cf457/src/System.Private.CoreLib/shared/System/Diagnostics/StackTrace.cs#L130
https://github.com/dotnet/corefx/blob/46edc58620f29557e23fea29ed8392a0f2c9e31c/src/System.Diagnostics.StackTrace/ref/System.Diagnostics.StackTrace.cs#L41

> Or, conversely, how do you feel about removing the `?`?

We should remove the `?` from:
https://github.com/dotnet/coreclr/blob/1b12053ffffc36ad73ad83f7ce111c891c4cf457/src/System.Private.CoreLib/shared/System/Diagnostics/StackTrace.cs#L159
https://github.com/dotnet/corefx/blob/46edc58620f29557e23fea29ed8392a0f2c9e31c/src/System.Diagnostics.StackTrace/ref/System.Diagnostics.StackTrace.cs#L50

It can contain null, but as far as I can tell only if you violate the contract of the constructor, and if you're explicitly violating one contract, it's fine for others to be "wrong".

**Comment by danmosemsft** [comment]
@jnm any interest in making the fix mentioned just above? then we can close this.

**Comment by jnm2** [comment]
Yes, PR incoming.
