### ISSUE TITLE
Accept Span<T> as parameter in decimal and Guid constructor 

### ISSUE THREAD

**Issue by ArjunVachhani** [dotnet/corefx#42435]
decimal and Guid are structure types if there is a constructor that accepts `Span<T>` instead of `int[]` / `byte[]` then it can reduce ephemeral garbage and hence improve the performance of many applications doing serialization/deserialization.

**Comment by GrabYourPitchforks** [comment]
[This page](https://apisof.net/catalog/System.Guid..ctor(ReadOnlySpan%3CByte%3E)) shows when the Guid ctor was introduced: .NET Core 2.1.

For Decimal, we're tracking the work at https://github.com/dotnet/corefx/issues/35877.
