### ISSUE TITLE
Proposed size reduction in SortedInt32KeyNode<TValue>

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/corefx#42431]
`SortedInt32KeyNode<TValue>` has two fields that could be merged:

https://github.com/dotnet/corefx/blob/8ebc9bb07f72a3d7807a8b1fc4876cb851ef927f/src/System.Collections.Immutable/src/System/Collections/Immutable/SortedInt32KeyNode.cs#L40-L52

It's my understanding that these will be laid out such that they take 64 bits. If the `_frozen` state was captured in `_height` (e.g. in the MSB) the size of these nodes could be reduced slightly at the expense of some bit twiddling.

If this assumption is correct and the proposed change would be considered, I am happy to make it and benchmark before/after scenarios.

**Comment by stephentoub** [comment]
I'm not following. How will combining these help? Whether together they take 1 byte or 2 bytes, I'm not seeing in what situation that would change the object size due to padding. Can you elaborate?

**Comment by drewnoakes** [comment]
Ah, I was coming the misconception that the `byte` and `bool` fields would each be aligned to 4-byte boundaries, and that merging them would save four bytes.
