### ISSUE TITLE
Use proper reference assemblies for producing partial facades

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#4244]
Right now, we are using a version of mscorlib that we grab from a random CoreCLR NuGet package. Soon, we will need to build .NET Native partial facades as well, which will need to compile against System.Private.CoreLib. We should do the work to produce proper reference assemblies for both System.Private.CoreLib as well as mscorlib, and use those in our partial facade generation process.

**Comment by ellismg** [comment]
Is there a reason we can not use the mscorlib.dll from the runtime nuget package we already produce?   Does it have to be a reference assembly for some reason?

**Comment by mellinoe** [comment]
@ellismg Well, that is basically what we are doing right now. Except, the runtime NuGet package we are using is some old, obsolete one that just happens to have mscorlib in it and that we have to update manually :smile: .

There's not really any functional difference in using a reference assembly for partial facades, other than it would be smaller, more controlled, etc. Actually, the biggest benefit is that it would probably be easier to reference in a NuGet package. We have to use a bit of a workaround to reference the mscorlib we use now, because we have to filter out the rest of the stuff in the package we are using, which would get worse if we used a NuGet package with even more in it.

**Comment by ellismg** [comment]
@mellinoe The upside of just using the runtime package is it's one less package we have to ship and we know that the mscorlib.dll we are facading to can't get out of sync with the runtime we are running on.  I agree that the layout of the package is a hurdle to overcome.

**Comment by ellismg** [comment]
(BTW: 100% percent onboard with killing that random package we are using now, it's a terrible thing).

**Comment by weshaggard** [comment]
I kind of agree that we should just use the Microsoft.NETCore.Runtime.CoreCLR package. I don't think we need a reference assembly for mscorlib or System.Private.CoreLib (and friends). In fact I really don't want to make it easy for folks to consume these implementation assemblies so I don't mind if it is a little work for us to consume them. Whatever we do end up using however I would like to make the production and publishing of those packages automatic as part of our daily builds. We have that for CoreCLR but we don't yet for CoreLIb.

**Comment by mellinoe** [comment]
Just trying to clarify here, as I don't think we are on the same page.

Right now we are using a package called "Microsoft.NETCore.Runtime.CoreCLR", which as far as I know is just a very old package we defined a long time ago before we had our more fleshed-out set of packages right now. It has a few random assemblies in it, one of which happens to be mscorlib.

For running our tests right now, we use the package "runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR", which has roughly the same files as the other package, but are set up in a completely different folder structure. It also has a "ref" folder with a blank placeholder in it, which I imagine would prevent us from referencing the mscorlib.ni.dll contained within it without resorting to some fancy custom targets. Right now we just add a Nuget reference to the old package, and because of its layout, NuGet automatically resolves the mscorlib.dll in it.

@weshaggard Would it help that the "reference assembly" packages would probably only be uploaded to our development feed? If it's a big problem, then we can try the workaround to reference the test runtime package, but I think we do want to move away from the package we are using right now.

**Comment by weshaggard** [comment]
@mellinoe currently we are using "Microsoft.DotNet.CoreCLR" (https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/partialfacades.targets#L29) which is the manually updated one which we should stop using. I'm recommending we use "Microsoft.NETCore.Runtime.CoreCLR" (the particular runtime version of it which is runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR) instead.

I'm starting to think we should have some package like Microsoft.NETCore.Private.References.[NetNative|.CoreCLR] or something along those lines to house these facade seeds. There is definitely more thought to go into this however.

**Comment by mellinoe** [comment]
We're now using the newer "TargetingPack" NuGet package for our CoreCLR partial facades. I'm going to leave this open because there may still be some more work to do in order to get the .NET Native and Desktop facades building using these new NuGet packages as well.

**Comment by mellinoe** [comment]
Now that we have proper filtering (in the latest version of buildtools) there's not really anything else to do here.
