### ISSUE TITLE
problem about Process.Start() in threading timer class 

### ISSUE THREAD

**Issue by bouyeijiang** [dotnet/corefx#42448]
using threading timer class to new Process class start can't return result 
example:

```c#
 var pro= System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo()
                {
                    FileName = "cmd.exe",
                    Arguments = "java -version",
                    RedirectStandardOutput=true,
                    // UseShellExecute=false,
                    //  CreateNoWindow=true,
                });
                pro.WaitForExit();

                var output= pro.StandardOutput;
               string str= output.ReadToEnd();
```

**Comment by danmosemsft** [comment]
There's more info here https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.standardoutput?view=netcore-3.0#remarks
> The example avoids a deadlock condition by calling p.StandardOutput.ReadToEnd before p.WaitForExit. A deadlock condition can result if the parent process calls p.WaitForExit before p.StandardOutput.ReadToEnd and the child process writes enough text to fill the redirected stream. The parent process would wait indefinitely for the child process to exit. The child process would wait indefinitely for the parent to read from the full StandardOutput stream.

**Comment by danmosemsft** [comment]
I'm going to close this @bouyeijiang feel free to reopen if that's not the issue.
