### ISSUE TITLE
How do I use System.Text.Json in a .NetStandardLibrary 2.1?

### ISSUE THREAD

**Issue by aligneddev** [dotnet/corefx#42479]
File new project > .NetStandardLibrary 2.1 (for a .Net Core 3.0 project).

```
 public class Class1
    {
        public void test()
        {
            JsonSerializer
        }
    }
```

I can't add the  System.Text.Json NuGet package and adding the using doesn't work.

Can I use  System.Text.Json in .NetStandardLibrary2.1?

**Comment by huoyaoyuan** [comment]
> I can't add the System.Text.Json NuGet package and adding the using doesn't work.

How can't you add the NuGet package? It's available for every framework that supersets `netstandard2.0`.

**Comment by aligneddev** [comment]
I tried it and the NuGet manager failed. I just tried it again in a brand new 2.1 project and Nuget worked fine. 

I guess I just had something wrong in VS or that project. I'll close this out and it can be ignore.
Thank you.
