### ISSUE TITLE
Issue with vs test run

### ISSUE THREAD

**Issue by MarcoRossignoli** [dotnet/corefx#42476]
If I try to debug test using text explorer in vs test doesn't run, terminate immediatly.
I get this on test output
```
[08/11/2019 3:33:26.392 ] ---------- Discovery started ----------
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' was not found.
  - The following frameworks were found:
      2.2.7 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
      3.0.0 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
      3.1.0-preview2.19525.6 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x86&rid=win10-x86
. Please check the diagnostic logs for more information.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.ThrowOnTestHostExited(Boolean testHostExited)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
[08/11/2019 3:33:26.444 ] ========== Discovery aborted: -1 tests found (0:00:00,051759) ==========
Executing test method: System.Memory.Tests.SequenceReader.ReaderBasicTests.TryPeekOffsetLength
[08/11/2019 3:33:26.502 ] ---------- Run started ----------
[08/11/2019 3:33:26.507 ] ========== Run finished: 0 tests run (0:00:00,0053876) ==========

```

At the moment the workaround is to use `Debug.Launch()` and run with command line.
I'm on fresh master.

cc: @ViktorHofer, @ericstj, @wtgodbe, @safern, @Anipik

**Comment by ericstj** [comment]
@MarcoRossignoli are you launching VS through build -vs as is described here: https://github.com/dotnet/corefx/blob/021463608e504ee53e75689376fede17659f851a/Documentation/building/windows-instructions.md#using-test-explorer-in-visual-studio

**Comment by MarcoRossignoli** [comment]
@ericstj it works as expected thank's...another thing if I want to use vs preview how can I do?I saw that the command open the "non preview" version(I've 2 version installed side-by-side).

**Comment by ericstj** [comment]
It looks like the script just launches the SLN : https://github.com/dotnet/corefx/blob/25154b5cbdc0e08d88f5367493099d4c4bd5a85b/eng/build.ps1#L68-L89

Can you try running that from a developer command prompt for your preview installation?  If that doesn't work then we can probably modify the script to run devenv instead of relying on the shell's .sln extension handling, which would honor your path.

**Comment by MarcoRossignoli** [comment]
No luck for me, I usually work through console with "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\Tools\VsDevCmd.bat" env...if I use that command from here it opens "non preview version".

Btw at the moment I can run and attach using launchsettings.json

**Comment by ericstj** [comment]
Can you modify that PS1 locally from
```
 ."$vs" 
```
to 
```
devenv  ."$vs" 
```

**Comment by ViktorHofer** [comment]
I think changing the default program for the sln extension should suffice. Closing as fixed.

**Comment by MarcoRossignoli** [comment]
Yep guys sorry for the delay! thanks a lot!
