### ISSUE TITLE
Typos in comment

### ISSUE THREAD

**Issue by rob313663** [dotnet/corefx#42481]
src\Common\src\CoreLib\System\Globalization\DateTimeFormat.cs

Therefore, if we are in a regular year, we have to increment the month name if **moth** is greater or **eqaul** to 7.

**Comment by danmosemsft** [comment]
Thanks @rob313663 . Would you like to offer a quick PR?

**Comment by rob313663** [comment]
I'll try.

**Comment by rob313663** [comment]
PR made (https://github.com/dotnet/coreclr/pull/27789).

What happens now? Should I close this or you or the one accepting/rejecting the PR? I have referenced this issue in the desc of the PR.

**Comment by gfoidl** [comment]
> Should I close this or you or the one accepting/rejecting the PR? I have referenced this issue in the desc of the PR.

Leave this issue open (to track the state of this issue). It will get closed when the PR gets merged automatically.
