### ISSUE TITLE
JwtBearerDefaults missing in NetCore 3.0

### ISSUE THREAD

**Issue by ClaudiuSocaci** [dotnet/corefx#42525]
For Authentication I am currently using `services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)..`
I am looking into using 3.0 but JwtBearerDefaults is not available. How can I do it in 3.0?

**Comment by Joe4evr** [comment]
Did you install [Microsoft.AspNetCore.Authentication.JwtBearer](https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.JwtBearer/3.0.0)?

**Comment by davidsh** [comment]
@Tratcher - ASP.NET Core issue.

**Comment by ClaudiuSocaci** [comment]
@Joe4evr You are right. I did not install that package. I use Mac and Rider last version but I did not find that nuget package so by installing it using the terminal worked. 

So maybe the package is not available through search or not sure but now it works.

Thanks!
