### ISSUE TITLE
Time Zone `zzz` formatting/parsing are forcing `:` instead of DateTimeFormatInfo.TimeSeparator

### ISSUE THREAD

**Issue by 2ooom** [dotnet/corefx#42520]
## Formatting
When trying to format timezone offset with custom [`:` delimiter](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings?redirectedfrom=MSDN#timeSeparator) result has `":"` instead of `DateTimeFormatInfo.TimeSeparator` provided.
#### Dot separator
```csharp
var dotSeparatedCulture = new CultureInfo("")
{
    DateTimeFormat = { TimeSeparator = "." },
};
var result = DateTime.UtcNow.ToString("zzz", dotSeparatedCulture);
Assert.AreEqual("+00.00", result);
// Assert.AreEqual failed. Expected:<+00.00>. Actual:<+00:00>.  
```
#### Empty separator
```csharp
var emptySeparatorCulture = new CultureInfo("")
{
    DateTimeFormat = { TimeSeparator = "" },
};
var result = DateTime.UtcNow.ToString("zzz", emptySeparatorCulture);

Assert.AreEqual("+0000", result);
// Assert.AreEqual failed. Expected:<+0000>. Actual:<+00:00>.  
```
Problem is in the function [`System.DateTimeFormat.FormatCustomizedTimeZone`](https://github.com/dotnet/corefx/blob/465da74726664728b690ce4d0086d56f59187a1f/src/Common/src/CoreLib/System/Globalization/DateTimeFormat.cs#L824):
```csharp
// 'zzz*' or longer format e.g "-07:30"
result.AppendFormat(CultureInfo.InvariantCulture, ":{0:00}", offset.Minutes);
```
where `:` is appended instead of `DateTimeFormatInfo.TimeSeparator`

## Parsing
Same issue with parsing. When trying to parse timezone offset with custom `:` delimiter a `System.FormatException` is thrown:
#### Dot separator
```csharp
var offset = TimeZoneInfo.Utc.GetUtcOffset(DateTime.UtcNow);
var customInvariantCulture = new CultureInfo("")
{
    DateTimeFormat = { TimeSeparator = "." },
};
var result = DateTime.ParseExact("+00.00", "zzz", customInvariantCulture);
var resultOffset = TimeZoneInfo.Utc.GetUtcOffset(result.ToUniversalTime());
Assert.AreEqual(offset, resultOffset);
// threw exception:  System.FormatException: String '+00.00' was not recognized as a valid DateTime at System.DateTime.ParseExact(String s, String format, IFormatProvider provider)
```
Problem is in the function [`System.DateTimeParse.ParseTimeZoneOffset`](https://github.com/dotnet/corefx/blob/5bc7c43f61842f19247cef40ba88f7fb395b956d/src/Common/src/CoreLib/System/Globalization/DateTimeParse.cs#L3268):
```csharp
if (str.Match(":"))
{
    // Found ':'
    if (!ParseDigits(ref str, 2, out minuteOffset))
    {
        return false;
    }
}
```
where `":"` is matched instead of `DateTimeFormatInfo.TimeSeparator`
However since it's optional the following code works:
#### Empty separator [Works]
```csharp
var offset = TimeZoneInfo.Utc.GetUtcOffset(DateTime.UtcNow);
var customInvariantCulture = new CultureInfo("")
{
    DateTimeFormat = { TimeSeparator = "" },
};
var result = DateTime.ParseExact("+0000", "zzz", customInvariantCulture);
var resultOffset = TimeZoneInfo.Utc.GetUtcOffset(result.ToUniversalTime());
Assert.AreEqual(offset, resultOffset);
```

**Comment by tarekgh** [comment]
Thanks for your report. The zzz is formatted as a time span and not regular DateTime. It has been decided since day one to use the standard format for the formatting the time zone part in the date/time objects. So, it is intentional always using ```:``` as a separator for the formatting the time span part. I understand you can argue this not the correct decision, but we cannot change this now as the scope of breaking will be very big as many people depend on parsing the dates assuming this format. You can still workaround this issue by replacing ```:``` with the desired separator you want.
