### ISSUE TITLE
System.Text.Json fails to deserialize objects with a Guid

### ISSUE THREAD

**Issue by RasmusWesterlundh** [dotnet/corefx#42535]
### Description
Deserializing an object containing a Guid will result in a null value, even if the json string and Guid is correctly formatted.

Deserializing the same object using Newtonsoft.Json is successful and gives the expected object.

### Example code to reproduce
```
//SystemApplication is an object containing a Guid-property and several string-properties

var response = await httpClient.GetAsync($"v1/some/endpoint");
var content =  await response.Content.ReadAsStringAsync();
var result_SystemText = System.Text.Json.JsonSerializer.Deserialize<SystemApplication>(content); //Will result in null-object
var result_Newtonsoft = Newtonsoft.Json.JsonConvert.DeserializeObject<SystemApplication(content); //Will result in correctly serialized object
```
-------------------------------------------------------------------
 ### dotnet --info
> PS C:\windows\system32> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

>Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

>Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

>.NET Core SDKs installed:
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

>.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by layomia** [comment]
@RasmusWesterlundh can you provide a snippet of your `content` payload (particularly the Guid [format (see remarks section)](https://docs.microsoft.com/en-us/dotnet/api/system.guid.tostring?view=netcore-3.0)), and if possible your `SystemApplication` class schema?

**Comment by RasmusWesterlundh** [comment]
Hi @layomia,

The only content-payload I have at the moment is with sensitive system information from production data, so I cannot share that with you. I hope this should be fairly easy to replicate none-the-less.

In the content-payload the Guid is 32 digits separated with hyphens ("D"-specifier).

In the successful deserialization by Newtonsoft.Json that same value is however noted as 32-digits separated by hyphens, enclosed in bracers ("B"-specifier).

Same payload deserialized in the below image
![untitled](https://user-images.githubusercontent.com/41692047/68614857-158dc300-04c2-11ea-9f14-3ecdbda9ca43.png)

**Comment by ahsonkhan** [comment]
@RasmusWesterlundh - can you provide a simplified/anonymized repro of your issue?

Does your class schema contain public properties with getters and setters? Only those are supported. Is there a property name mismatch in the payload vs your class schema (maybe casing difference)?

Does your JSON payload contain the Guid in the "B" format, i.e. surrounded by braces? The `JsonSerializer` by default uses the "D" format for parsing, and hence would fail for other formats. If you need to support custom formats, you'd need to write your own Guid converter (similar to when you need to support different date time formats: https://docs.microsoft.com/en-us/dotnet/standard/datetime/system-text-json-support

This works as expected:
```C#
[Fact]
public static void GuidDeserializationTest()
{
    Foo f = JsonSerializer.Deserialize<Foo>("{\"MyGuid\":\"090bbc52-bfe3-4fa3-9b36-25d7e624e662\"}");
    Guid expected = new Guid("090bbc52-bfe3-4fa3-9b36-25d7e624e662");
    Assert.Equal(expected, f.MyGuid);
}

public class Foo
{
    public Guid MyGuid { get; set; }
}
```

**Comment by RasmusWesterlundh** [comment]
The Guid is in "D"-format in the json payload. 
No naming mismatches, I doubt I that the Newtonsoft deserializer would have managed to deserialize if that had been the case.

```cs
string content = "{\"data\":{\"Type\":\"Foo\",\"Description\":\"bar \",\"Software\":\"baz\",\"Version\":\"qux\",\"Url\":\"http://example.com\",\"DatabasePortNumber\":1,\"Id\":\"2cdc66f1-0000-0000-39ac-233c00000000\"}}";

var result_SystemText = System.Text.Json.JsonSerializer.Deserialize<SystemApplicationResponse>(content);  //Will result in null-object
var result_Newtonsoft = Newtonsoft.Json.JsonConvert.DeserializeObject<SystemApplicationResponse>(content); //Will result in correctly serialized object
```
```cs
    public class SystemApplicationResponse
    {
        public SystemApplicationDto Data { get; set; }
    }


    public class SystemApplicationDto
    {
        public SystemApplicationDtoType Type { get; set; }

        public string Description { get; set; }

        public string Software { get; set; }

        public string Version { get; set; }
        public string Url { get; set; }

        public int DatabasePortNumber { get; set; }
        public System.Guid Id { get; set; }
    }

    public enum SystemApplicationDtoType
    {
        Foo = 0
    }

**Comment by khellang** [comment]
> No naming mismatches, I doubt I that the Newtonsoft deserializer would have managed to deserialize if that had been the case.

The very first property (`data`) in your JSON doesn't match the property name (`Data`) 🙈

**Comment by RasmusWesterlundh** [comment]
@khellang 
You are correct. Changing it to an uppercase results in System.Text throwing an error on trying to deserialize the SystemApplicationDtoType.

But at this point it is very apparent that this belongs to StackOverflow rather than as a github issue.... 🙃

**Comment by ahsonkhan** [comment]
> Changing it to an uppercase results in System.Text throwing an error on trying to deserialize the SystemApplicationDtoType.

> System.Text.Json.JsonException : The JSON value could not be converted to System.Text.Json.Serialization.Tests.ReadValueTests+SystemApplicationDtoType. Path: $.Data.Type | LineNumber: 0 | BytePositionInLine: 21.

That's likely because you are deserializing an enum with string values. Register the `JsonStringEnumConverter` as part of `JsonSerializerOptions` to get the expected behavior.

```C#
var options = new JsonSerializerOptions();
options.Converters.Add(new JsonStringEnumConverter());

var result_SystemText = JsonSerializer.Deserialize<SystemApplicationResponse>(content, options);
```

> Edit: I'm sorry, my previous testing of this must have been very incomplete. **It is not related** to the Guid at all it seems. Removing the Guid property from the class object and removing it from the content string still results in the System.Text.JsonSerializer to fail the deserialization.

I suspected that.

> But at this point it is very apparent that this belongs to StackOverflow rather than as a github issue.... 

No problem. I am glad the issue got resolved :)
