### ISSUE TITLE
Build failed with failure `Unable to pull image` with Exit Code:-4

### ISSUE THREAD

**Issue by AriNuer** [dotnet/corefx#42552]
**Build:**
[20191111.49](https://dnceng.visualstudio.com/public/_build/results?buildId=423882)(Master)

**Details:**
https://helix.dot.net/api/2019-06-17/jobs/7bdf6cb6-6bed-48be-8035-9a552d26b4f7/workitems/System.Xml.RW.FactoryReader.Tests/console

**OS & Arch:**
Linux x64

**Log:**
```
Executed on b001BSX using docker image mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.9-helix-09ca40b-20190620184719
running $HELIX_CORRELATION_PAYLOAD/scripts/90cca4a137f048c1ba210171f1adcb5c/execute.sh in /datadisks/disk1/work/7bdf6cb6-6bed-48be-8035-9a552d26b4f7/Work/9297b99e-2788-42c0-ba8c-3636ccc4b8d0/Exec max 900 seconds

Output:
Unable to pull image mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.9-helix-09ca40b-20190620184719
Exit Code:-4
```

**Comment by safern** [comment]
Seems like a mcr service issue which seemed to be down at that moment. I don't see it happening anymore.
