### ISSUE TITLE
RuntimeInformation.FrameworkDescription reports 4.0.30319.34209 on .Net Framework 4.5.2

### ISSUE THREAD

**Issue by appel1** [dotnet/corefx#42571]
It would be useful if behaved the same as when targeting newer versions of .NET.

**Comment by bartonjs** [comment]
What do you mean "behaved the same"?

**Comment by appel1** [comment]
> What do you mean "behaved the same"?

I'd expect it to return a string like ".Net Framework 4.5.2".

**Comment by bartonjs** [comment]
The behavior of framework description is $"{FrameworkName} {typeof(object).GetAssemblyFileVersion()}" (GetAssemblyFileVersion being a pseudo-method to get the appropriate attribute out of the assembly).

I don't think there's a way to query the running "branding" version (like 4.5.2).

**Comment by appel1** [comment]
The current workaround we have is to use the method described on https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed when running on Windows.
