### ISSUE TITLE
Add tests for invalid `DuplicatePropertyNameHandling` enum values within JsonNodeOptions

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#42585]
See https://github.com/dotnet/corefx/pull/41030#discussion_r326435731

> We should add tests for invalid `DuplicatePropertyNameHandling` enum values but this can be addressed separately as its test enhancement to improve coverage.
> 
> See [#41030 (comment)](https://github.com/dotnet/corefx/pull/41030#discussion_r323528688)
> 
> > Someone could pass in -1 for this OR an integer value larger than `DuplicatePropertyNameHandlingStrategy.Error`.

**Comment by AntonLandor** [comment]
I have implemented a test case to solve this issue and also get 100% branch coverage on JsonNodeOptions. I will create a pull request as soon as I can when the new dotnet/runtime repository is up.

**Comment by AntonLandor** [comment]
@ahsonkhan I made a [pull request (#436)](https://github.com/dotnet/runtime/pull/436) a couple of days ago for this issue :+1:

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/dotnet/runtime/pull/436
