### ISSUE TITLE
Add support for escaped characters in JsonString (for {Try}GetDateTime{Offset}).

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#42582]
See https://github.com/dotnet/corefx/pull/42574#discussion_r345968116

Escaped characters don't work in the current implementation of `JsonString` (and they should, similar to `JsonElement.GetDateTime` and `Utf8JsonReader.GetDateTime`).

```C#
string testStr = "\"\\u0031997-07-16T19:20:30.4555555+14:00\"";

using var doc = JsonDocument.Parse(testStr);
Assert.True(doc.RootElement.TryGetDateTime(out DateTime dateTimeVal));

var jsonString = new JsonString(testStr);

// This currently fails, returning false.
Assert.True(jsonString.TryGetDateTime(out dateTimeVal));
```

See https://github.com/dotnet/corefx/blob/dc6136f34c7d4ebbc493a7bb6cf1d15bc82250e6/src/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.TryGet.cs#L849-L852

https://github.com/dotnet/corefx/blob/dc6136f34c7d4ebbc493a7bb6cf1d15bc82250e6/src/System.Text.Json/src/System/Text/Json/Document/JsonDocument.cs#L665-L669

cc @khellang

**Comment by eugenesmlv** [comment]
I'm working on this issue.

**Comment by eugenesmlv** [comment]
@ahsonkhan should I open a pull request in [runtime](https://github.com/dotnet/runtime) repo?

**Comment by ahsonkhan** [comment]
@eugenesmlv, yes, please.
