### ISSUE TITLE
Conditionally flow execution context into Task for custom TaskSchedulers

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/corefx#42602]
After some evening perusal of the inner workings of `Task.Run/StartNew` it seems some uses unconditionally capture execution contexts iff there's a custom `TaskScheduler` and don't if `TaskScheduler.Current == TaskScheduler.Default`. 

Besides it being an inconsistency in the implementation it seems problematic for cases where you really don't want any `AsyncLocals` to be rooted by some background task.

My first thought was that the logic to capture or not was deferred to the scheduler (like the threadpool does during normal QUWI) but upon inspection the `Task(Action/Func)` constructors do the capturing unconditionally. I expect that's really just to support the separation of creation and starting yet it seems unfortunate. In any case it would be a decent option to give the scheduler the flexibility to ignore the context by checking a property during Task creation.

Was it a deliberate choice not to have any way to `StartNew/Run` a `Task` without capturing the current context, are we expected to `EC.SuppressFlow()` in this case?

### Example
When there's no scheduler we don't capture when `executionContext == null`
https://github.com/dotnet/coreclr/blob/15daca125fbb15bc3a9b65977957edd936fff752/src/System.Private.CoreLib/shared/System/Threading/Tasks/Sources/ManualResetValueTaskSourceCore.cs#L165-L173

But when there is a `TaskScheduler` it's always:
https://github.com/dotnet/coreclr/blob/15daca125fbb15bc3a9b65977957edd936fff752/src/System.Private.CoreLib/shared/System/Threading/Tasks/Sources/ManualResetValueTaskSourceCore.cs#L184-L186

### Other cases
Potentially problematic cases (just in coreclr) are, searching for StartNew:

- https://github.com/dotnet/coreclr/blob/073ad7ef1b6a7112eefc965aed362c7b5923682a/src/System.Private.CoreLib/shared/System/IO/TextWriter.cs
- https://github.com/dotnet/coreclr/blob/5b1c001bc0fb5bb1ce035c02ec275763f66defc8/src/System.Private.CoreLib/shared/System/IO/TextReader.cs
- https://github.com/dotnet/coreclr/blob/6abc099d4a798dc9a267d04bc025efbcbf148473/src/System.Private.CoreLib/shared/System/IO/Stream.cs

Cases like in `YieldAwaitable` just seem unfortunate as they're doing extra work during `UnsafeOnCompleted`. Async await machinery already maintains the correct context via IAsyncStateMachineBox.

**Comment by tarekgh** [comment]
CC @stephentoub

**Comment by stephentoub** [comment]
I'm not following the examples. Can you please provide a repro where Task.Run doesn't flow EC?

**Comment by NinoFloris** [comment]
It most certainly does flow EC, what I'm seeing is that it might do it a bit too happily in `ManualResetValueTaskSource` or `YieldAwaitable` when custom schedulers are involved. 

This is because there's a choice to either flow execution context or not in these types. That choice eventually influences whether — for the threadpool case — QUWI or its Unsafe version is called. When there's a custom task scheduler `Task.Factory.StartNew` is used, which always  causes the EC to be captured, not honoring `flowContext` or `ValueTaskSourceOnCompletedFlags.FlowExecutionContext` at all.

So I was wondering if there's a reason why there's no UnsafeStartNew, or — probably not the most useful idea — a property on the scheduler that can influence capturing.

**Comment by stephentoub** [comment]
Ah, I misunderstood what you were saying.

In the cases you call out, ExecutionContext is already being flown by the async method infrastructure, so this isn't a case of context being flown when it shouldn't / a functional issue.  But you're correct that there might be additional overhead that's unnecessary due to the context being flowed again when it's already being flowed, basically unecessary duplication.

This could be avoided with APIs like you mention, but it's never really shown up as an impactful cost, and so we haven't bothered.  Both cases you mentioned could also be addressed in the implementation, either by suppressing context around the invocation of the relevant APIs, or by adding additional internal code paths, but again, it just hasn't shown up as impactful enough to be concerned about.

Are you seeing otherwise?

**Comment by tarekgh** [comment]
@NinoFloris could you please answer @stephentoub question? Thanks.

**Comment by tarekgh** [comment]
@NinoFloris I am closing this issue but feel free to reply back if you have more info and we can reactivate the issue again. Thanks.
