### ISSUE TITLE
Build failure on OSX 

### ISSUE THREAD

**Issue by kapilash** [dotnet/corefx#4261]
Building from root fails on OSX with 7 errors related to GenFacades. 

A sample is below

>   /Users/kapilash/src/corefx/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00112/lib/partialfacades.targets(180,5): error MSB3073: The command ""/Users/kapilash/src/corefx/bin/obj/OSX.AnyCPU.Debug/ToolRuntime/corerun" "/Users/kapilash/src/corefx/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00112/lib/GenFacades.exe" -partialFacadeAssemblyPath:"/Users/kapilash/src/corefx/bin/obj/OSX.AnyCPU.Debug/System.Reflection.TypeExtensions.CoreCLR/PreGenFacades/System.Reflection.TypeExtensions.dll" -contracts:"/Users/kapilash/src/corefx/packages/System.Reflection.TypeExtensions/4.1.0-beta-23429/ref/dotnet5.1/System.Reflection.TypeExtensions.dll" -seeds:"/Users/kapilash/src/corefx/packages/Microsoft.DotNet.CoreCLR/1.0.5-prerelease/lib/dnxcore50/mscorlib.dll" -facadePath:"/Users/kapilash/src/corefx/bin/obj/OSX.AnyCPU.Debug/System.Reflection.TypeExtensions.CoreCLR/" -producePdb:false" exited with code 255. [/Users/kapilash/src/corefx/src/System.Reflection.TypeExtensions/src/System.Reflection.TypeExtensions.CoreCLR.csproj]

It seems the problem is the presence of the [file called mscorlib.ni.dll](https://github.com/dotnet/coreclr/issues/1419#issuecomment-134156283).
 Removing that from ```$HOME/bin/obj/OSX.AnyCPU.Debug/ToolRuntime``` fixes the build failure.

**Comment by weshaggard** [comment]
@kapilash I'm not currently setup to test this but I believe this may have been fixed. Can you tell me if this still repro's for you or not?

**Comment by kapilash** [comment]
@weshaggard , it still repro's, for me. The following is an example of failure. And there are many such failures.

      coreclr_initialize failed - status: 0x80131500
      /Users/kapilash/src/corefx/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00141/lib/partialfacades.targets(147,5): error MSB3073: The command ""/Users/kapilash/src/corefx/bin/obj/AnyOS.AnyCPU.Debug/ToolRuntime/corerun" "/Users/kapilash/src/corefx/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00141/lib/GenFacades.exe" -partialFacadeAssemblyPath:"/Users/kapilash/src/corefx/bin/obj/AnyOS.AnyCPU.Debug/Microsoft.Win32.Primitives/net46/PreGenFacades/Microsoft.Win32.Primitives.dll" -contracts:"/Users/kapilash/src/corefx/packages/Microsoft.Win32.Primitives/4.0.1-rc2-23631/ref/net46/Microsoft.Win32.Primitives.dll" -seeds:"/Users/kapilash/src/corefx/packages/Microsoft.TargetingPack.NETFramework.v4.6/1.0.0-rc2-23530/ref/net46/mscorlib.dll;/Users/kapilash/src/corefx/packages/Microsoft.TargetingPack.NETFramework.v4.6/1.0.0-rc2-23530/ref/net46/System.dll" -facadePath:"/Users/kapilash/src/corefx/bin/obj/AnyOS.AnyCPU.Debug/Microsoft.Win32.Primitives/net46/" -producePdb:false" exited with code 255. [/Users/kapilash/src/corefx/src/Microsoft.Win32.Primitives/src/facade/Microsoft.Win32.Primitives.csproj]

Earlier, when I deleted ```mscorlib.ni.dll```, the build would succeed. But there's no such file anymore.
ATM, I know no work around either.

**Comment by weshaggard** [comment]
@stephentoub @ellismg are either of you guys setup to try this out and see if we are restoring the correct ToolRuntime on OSX?

**Comment by ellismg** [comment]
I can take a look.

**Comment by ellismg** [comment]
I tried this today and things were working.
