### ISSUE TITLE
Сould not find Encoding name for such encodings as euc-tw, iso-8859-10, iso-8859-16

### ISSUE THREAD

**Issue by rstm-sf** [dotnet/corefx#42623]
Hello!

Please help find or say why there are no following aliases for `Encoding`:
- [ ] `euc-tw` (maybe `51950` code page identifier and why then there is no name?, [doc/win32](https://docs.microsoft.com/en-us/windows/win32/intl/code-page-identifiers))
- [ ] `iso-8859-10`
- [ ] `iso-8859-16`

_Some explanation_
I looked at the [System/Text/EncodingTable.Data.cs](https://github.com/dotnet/corefx/blob/e99ec129cfd594d53f4390bf97d1d736cff6f860/src/System.Text.Encoding.CodePages/src/System/Text/EncodingTable.Data.cs) (contains aliases for encodings that can be obtained through the method `CodePagesEncodingProvider.Instance.GetEncoding(string)`) and found matches for most encodings of interest. But only for these encodings (`euc-tw`, `iso-8859-10`, `iso-8859-16`) I could not find any similar and could not find an explanation why. They either do not have support (wonder why?), or still there is some kind of alias or some kind of equivalent encoding.

**Comment by Gnbrkm41** [comment]
I'm guessing you were trying to get instances of `Encoding` with `Encoding.GetEncoding(string)`? I'm not entirely sure, but it looks like .NET Framework queries the OS for available encodings, whereas .NET Core does not and support limited number of named code pages. (See also: https://docs.microsoft.com/en-us/dotnet/api/system.text.encodingprovider?view=netframework-4.8#remarks) So, in case of .NET Framework it will fail if the OS does not have information about the encoding, and in case of .NET Core it fails because they are not supported.

Ways to work around this would be to use [RegisterProvider](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.registerprovider?view=netframework-4.8) method to register encoding provider that can resolve those aliases and provide appropriate `Encoding` instances.

**Comment by rstm-sf** [comment]
@Gnbrkm41, thanks for the answer!

Yes, I was mistaken in not writing a better issue. The following I will add to the beginning of the topic:

I looked at the [System/Text/EncodingTable.Data.cs](https://github.com/dotnet/corefx/blob/e99ec129cfd594d53f4390bf97d1d736cff6f860/src/System.Text.Encoding.CodePages/src/System/Text/EncodingTable.Data.cs) (contains aliases for encodings that can be obtained through the method `CodePagesEncodingProvider.Instance.GetEncoding(string)`) and found matches for most encodings of interest. But only for these encodings (`euc-tw`, `iso-8859-10`, `iso-8859-16`) I could not find any similar and could not find an explanation why. They either do not have support (wonder why?), or still there is some kind of alias or some kind of equivalent encoding.

**Comment by Gnbrkm41** [comment]
cc @layomia, @tarekgh

**Comment by ShawnSteele** [comment]
The set and behavior of encodings in the framework are not being changed.

In this particular case, these encodings are not very common.  Applications are really strongly recommended to Use Unicode, either UTF-8 or UTF-16.  If they do need to process legacy data in these rarer encodings, they should probably make that translation at a different layer in their architecture.  There's also an option of overriding the Encoding classes, but that could be tricky for some users.

One problem with the legacy (non-Unicode) encodings is that nearly every platform has their own slight variation on the behavior, making "perfect" conformity a near-impossibility.  Hence an ongoing effort to standardize the behavior of the legacy encodings -- however that has the catch 22 that any new updates to any legacy standardized encoding won't "fix" legacy data sets that used different behavior.  The only way to get that data to conform would be to migrate it from the "wrong" legacy encoding to the "desired" legacy encoding.  Which is a very unlikely exercise as any data migration would best be done by moving to Unicode and avoiding the compatibility problems of Unicode entirely.

Another problem is that data sets are often mis-tagged.  The most common error is probably to incorrectly identify a codepage as an ISO encoding when it's only partially conformant.

The entire set of non-Unicode encodings should be considered deprecated and obsolete.  The only real way to get data portability between applications and systems is to Use Unicode properly.

**Comment by tarekgh** [comment]
Thanks @ShawnSteele 

@rstm-sf I want to emphasize on @ShawnSteele point for using Unicode encoding and try to avoid using legacy encodings. a couple of comments: 

- If you want to see all supported encodings by the framework, you may refer to https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.getencodings?view=netframework-4.8
- You still have the option to support whatever encoding if you implement and register your [EncodingProvider](https://docs.microsoft.com/en-us/dotnet/api/system.text.encodingprovider?view=netframework-4.8)

By that I am closing this issue and please let's know if you have any more questions. Thanks for reporting the issue.

**Comment by rstm-sf** [comment]
@ShawnSteele, @tarekgh thanks!

> In this particular case, these encodings are not very common.

Ok

> By that I am closing this issue and please let's know if you have any more questions.

I'm sorry that I could not get my point across. Therefore, the answer was not fully received (but more and more comes the understanding that yes, they are not supported) 

The question nevertheless was whether there is a possibility on the part of Core, at the moment, to support these encodings.

For example, in the documentation I could not find the encoding `iso-2022-cn`. But after wandering around the Internet, I decided that this is an encoding called `x-cp50227` (or something similar that). 
Thus, could it not be that they are under a different name?

**Comment by tarekgh** [comment]
@rstm-sf 

> could it not be that they are under a different name?

I don't think we have any other codepages that have exact mapping as the mentioned codepages. I am even not sure using x-cp50227 for iso-2022-cn will be good enough either. It is close but not exact I guess.

**Comment by rstm-sf** [comment]
@tarekgh thanks!
