### ISSUE TITLE
System.Security.Cryptography. ECDsaOpenSsl throw NullReferenceException after using construction.

### ISSUE THREAD

**Issue by VladislavMorozov** [dotnet/corefx#42631]
# Issue Title

ECDsaOpenSsl from System.Security.Cryptography throw NullReferenceException after using construction.

# General

I have .NET Core 2.2 and Linux container in docker. When I create JWT token with ES256 algorithm `JwtSecurityTokenHandler.CreateEncodedJwt()` throw exception.

![token](https://user-images.githubusercontent.com/31768904/68990973-a8d04b00-086a-11ea-9802-bde4c34ac303.png)

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.9.5" />
    <PackageReference Include="Portable.BouncyCastle" Version="1.8.5.2" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.6.0" />
  </ItemGroup>

</Project>
```

```
FROM mcr.microsoft.com/dotnet/core/runtime:2.2-stretch-slim AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build
WORKDIR /src
COPY ["AppleMusic/AppleMusic.csproj", "AppleMusic/"]
RUN dotnet restore "AppleMusic/AppleMusic.csproj"
COPY . .
WORKDIR "/src/AppleMusic"
RUN dotnet build "AppleMusic.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "AppleMusic.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AppleMusic.dll"]
```

```
using System;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Security.Cryptography;
using Microsoft.IdentityModel.Tokens;
using Org.BouncyCastle.Crypto.Parameters;
using Org.BouncyCastle.Security;

namespace AppleMusic
{
	class Program
	{
		static void Main(string[] args)
		{
			var key = "";
			
			var iat = (int)DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1)).TotalSeconds;
			var exp = (int)DateTime.UtcNow.AddMonths(5).Subtract(new DateTime(1970, 1, 1)).TotalSeconds;

			var tokenHandler = new JwtSecurityTokenHandler();

			var tokenDescriptor = new SecurityTokenDescriptor
			{
				Subject = new ClaimsIdentity(new Claim[]
				{
					new Claim("iat", iat.ToString()),
					new Claim("exp", exp.ToString()),
				}),
				Issuer = ""
			};

			for (var i = 0; i < 100; i++)
			{
				using (var algorithm = GetEllipticCurveAlgorithm(key)) // this code doesn't work
				{
					tokenDescriptor.SigningCredentials = new SigningCredentials(new ECDsaSecurityKey(algorithm)
					{
						KeyId = ""
					}, SecurityAlgorithms.EcdsaSha256);
					var token = tokenHandler.CreateEncodedJwt(tokenDescriptor);
					Console.WriteLine(token);
				}
			}
		}

		private static ECDsa GetEllipticCurveAlgorithm(string privateKey)
		{
			var keyParams = (ECPrivateKeyParameters)PrivateKeyFactory
				.CreateKey(Convert.FromBase64String(privateKey));

			var q = keyParams.Parameters.G.Multiply(keyParams.D).Normalize();

			return ECDsa.Create(new ECParameters
			{
				Curve = ECCurve.CreateFromValue(keyParams.PublicKeyParamSet.Id),
				D = keyParams.D.ToByteArrayUnsigned(),
				Q =
				{
					X = q.XCoord.GetEncoded(),
					Y = q.YCoord.GetEncoded()
				}
			});
		}
	}
}
```

version 2:

```
using System.IdentityModel.Tokens.Jwt;
using System.Security.Cryptography;
using Microsoft.IdentityModel.Tokens;

namespace AppleMusic
{
	class Program
	{
		static void Main(string[] args)
		{
			var tokenHandler = new JwtSecurityTokenHandler();

			var tokenDescriptor = new SecurityTokenDescriptor
			{
				Issuer = "A"
			};

			for (var i = 0; i < 100; i++)
			{
				using (var algorithm = ECDsa.Create()) // this code doesn't work correct
				{
					tokenDescriptor.SigningCredentials = new SigningCredentials(new ECDsaSecurityKey(algorithm)
					{
						KeyId = "A"
					}, SecurityAlgorithms.EcdsaSha256);
					var token = tokenHandler.CreateEncodedJwt(tokenDescriptor);
				}
			}
		}
	}
}
```

**Comment by wfurt** [comment]
cc: @bartonjs

**Comment by bartonjs** [comment]
@krwq do you have some time to look into this one?

**Comment by krwq** [comment]
@VladislavMorozov I think the problem might be with how you generate the privateKeyInfoData. When I use this instead of the base64:

```csharp
        private static AsymmetricCipherKeyPair GenerateKeyPairEcc()
        {
            var oid = X962NamedCurves.GetOid("prime256v1");
            var generator = new ECKeyPairGenerator();
            var genParam = new ECKeyGenerationParameters(oid, new SecureRandom());
            generator.Init(genParam);
            return generator.GenerateKeyPair();
        }
```

`((ECPrivateKeyParameters)pair.Private to get `ECPrivateKeyParameters` the token gets correctly generated. Is it possible you are hitting issue similar to this: https://stackoverflow.com/questions/9414125/export-ec-private-key-from-bouncycastle-and-import-into-cngkey-or-ecdsacng

**Comment by krwq** [comment]
Ok getting same results on Linux.

On both Windows and Linux ocassionally (< 1% chance) getting this:

```
Unhandled exception. System.Security.Cryptography.CryptographicException: The specified key parameters are not valid. Q.X and Q.Y are required fields. Q.X, Q.Y must be the same length. If D is specified it must be the same length as Q.X and Q.Y for named curves or the same length as Order for explicit curves.
   at System.Security.Cryptography.ECParameters.Validate()
   at System.Security.Cryptography.ECOpenSsl.ImportParameters(ECParameters parameters)
   at System.Security.Cryptography.ECDsa.Create(ECParameters parameters)
   at AppleMusic.Program.GetEllipticCurveAlgorithm(String privateKey) in /home/krwq/mess/corefx-42631/Program.cs:line 73
   at AppleMusic.Program.Main(String[] args) in /home/krwq/mess/corefx-42631/Program.cs:line 47
```

I suspect that is the bouncy castle issue though

**Comment by VladislavMorozov** [comment]
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=System.Security.Cryptography.Algorithms
  StackTrace:
   at System.Security.Cryptography.ECDsaImplementation.ECDsaOpenSsl.SignHash(Byte[] hash)
   at Microsoft.IdentityModel.Tokens.AsymmetricAdapter.SignWithECDsa(Byte[] bytes)
   at Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider.Sign(Byte[] input)
   at Microsoft.IdentityModel.JsonWebTokens.JwtTokenUtilities.CreateEncodedSignature(String input, SigningCredentials signingCredentials)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateJwtSecurityTokenPrivate(String issuer, String audience, ClaimsIdentity subject, Nullable`1 notBefore, Nullable`1 expires, Nullable`1 issuedAt, SigningCredentials signingCredentials, EncryptingCredentials encryptingCredentials)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateJwtSecurityToken(SecurityTokenDescriptor tokenDescriptor)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateEncodedJwt(SecurityTokenDescriptor tokenDescriptor)
   at AppleMusic.Program.Main(String[] args) in C:\Users\Vlad\Desktop\AppleMusic\AppleMusic\Program.cs:line 69

**Comment by VladislavMorozov** [comment]
I have this exception

**Comment by VladislavMorozov** [comment]
Always after the first iteration in the loop throws exception.

**Comment by VladislavMorozov** [comment]
@krwq please use ECDsa.Create in using construction in Linux container

**Comment by krwq** [comment]
@VladislavMorozov can you inspect if hash being passed to SignHash is null or ECDsaOpenSsl variable is set to null? If so then I think the issue will belong to:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues

If this is coming somewhere inside of ECDsaOpenSsl then we can look further

**Comment by bartonjs** [comment]
A null hash looks like it's properly tested for.  The `_key` lazy key loader must be null (as the only thing in that method that gets dereferenced)

**Comment by VladislavMorozov** [comment]
![image](https://user-images.githubusercontent.com/31768904/69281013-8f2b5c80-0bf8-11ea-823f-105fadc5fd2b.png)

**Comment by bartonjs** [comment]
(And _key being null would have been an ObjectDisposedException anyways.)  Huh.

**Comment by VladislavMorozov** [comment]
@bartonjs honestly, I don't understand you) I see that `ECDsa` is `IDisposable` and I want to use the `using` construction. But it's doesn't work correctly on Linux. When I use this code in asp.net core and register class as singleton or per request, this code returns the unpredictable results. For example, 2 requests have an exception and 1 request has token. How I can help you or @krwq to find the problem?

**Comment by VladislavMorozov** [comment]
I guess that `Value` from `_key` from the screenshot can't correct work correctly on Linux, because of the namespace is `Microsoft.Win32`.

**Comment by danmosemsft** [comment]
> can't work correctly on Linux, because of the namespace is Microsoft.Win32.

For historical reasons (originally .NET was Windows specific), there are a number of types in the `Microsoft.Win32` alias that are not actually Windows specific. SafeHandle is one of them.

**Comment by krwq** [comment]
@VladislavMorozov any chance you could try building corefx from sources (Debug build) and try to produce stack trace with line numbers and a bit more details? (at least replace System.Security.Cryptography.Algorithms with the Debug version). I also cannot see anything in SignHash which could produce NRE.

Another thing to try is perhaps try to isolate repro to not use Microsoft.IdentityModel.

Also just a sanity check, can you paste output of `dotnet --info`?

**Comment by wfurt** [comment]
lldb + sos can now get symbols AFAIK. (certainly for 3.0) 
“setsymbolserver -ms” should do the trick. 

https://github.com/dotnet/diagnostics/blob/master/documentation/installing-sos-instructions.md
https://github.com/dotnet/diagnostics/blob/master/documentation/sos-debugging-extension.md

**Comment by VladislavMorozov** [comment]
I found.

```
namespace Microsoft.IdentityModel.Tokens
{
    /// <summary>
    /// Provides signature and verification operations for Asymmetric Algorithms using a <see cref="SecurityKey"/>.
    /// </summary>
    public class AsymmetricSignatureProvider : SignatureProvider
```

![image](https://user-images.githubusercontent.com/31768904/69373120-2c979680-0cb4-11ea-80c6-883061a15072.png)

![image](https://user-images.githubusercontent.com/31768904/69373409-c95a3400-0cb4-11ea-9397-793a245eb724.png)

![image](https://user-images.githubusercontent.com/31768904/69373452-df67f480-0cb4-11ea-9b02-ea2c580e3e81.png)

**Comment by VladislavMorozov** [comment]
![image](https://user-images.githubusercontent.com/31768904/69374086-5c479e00-0cb6-11ea-92cc-d7371dd4b88b.png)


![image](https://user-images.githubusercontent.com/31768904/69374130-797c6c80-0cb6-11ea-92fa-b17dd8825d38.png)


![image](https://user-images.githubusercontent.com/31768904/69374157-88631f00-0cb6-11ea-9724-c436d6319f09.png)

![image](https://user-images.githubusercontent.com/31768904/69374198-a2046680-0cb6-11ea-9463-8c2c35646ecc.png)

**Comment by krwq** [comment]
@VladislavMorozov third screenshot line 307 is where the NRE happens (throw propagates error from the `try` and the stack trace you're seeing is already after it happened). Can you step into that method just before the NRE happens and try to figure out the line where it actually happens?

**Comment by VladislavMorozov** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/31768904/69376081-b5b1cc00-0cba-11ea-87e3-30ee906147ea.gif)

**Comment by VladislavMorozov** [comment]
@krwq I debugged by F10 button.

**Comment by krwq** [comment]
@VladislavMorozov you need to Step-into (if still does the same then in your debugger options unselect "Just My Code")

**Comment by VladislavMorozov** [comment]
Sorry)) That's my fail.

```
/// <summary>
    /// This adapter abstracts the 'RSA' differences between versions of .Net targets.
    /// </summary>
    internal class AsymmetricAdapter
```

![image](https://user-images.githubusercontent.com/31768904/69378154-daa83e00-0cbe-11ea-93e4-ee5f6dd3993f.png)

![image](https://user-images.githubusercontent.com/31768904/69378257-1e9b4300-0cbf-11ea-9458-5ca1892c0084.png)

![image](https://user-images.githubusercontent.com/31768904/69378348-42f71f80-0cbf-11ea-8738-f0a4aac1ab92.png)

I will send a gif

**Comment by VladislavMorozov** [comment]
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/31768904/69378687-f102c980-0cbf-11ea-9307-8a88f752776e.gif)

**Comment by krwq** [comment]
Can you try stepping into SignHash?

You might need to select your debugging options as on the picture (Debug -> Options)
![image](https://user-images.githubusercontent.com/660048/69382646-73619e00-0c6c-11ea-827b-6e489473bce0.png)

and show all local variables? (try to step/step-into as deep as you can before you get moved back to the original try .. catch). I suspect you should be able to figure out what is exactly causing the NRE.

The gif above looks like the lock object is null but looking at the code it doesn't seem possible

**Comment by VladislavMorozov** [comment]
@krwq You can reproduce my exception on Linux just put this code `ECDsa.Create()`

![image](https://user-images.githubusercontent.com/31768904/69429117-e25df600-0d43-11ea-8200-d8c137c06fe0.png)

**Comment by VladislavMorozov** [comment]
```
using System.IdentityModel.Tokens.Jwt;
using System.Security.Cryptography;
using Microsoft.IdentityModel.Tokens;

namespace AppleMusic
{
	class Program
	{
		static void Main(string[] args)
		{
			var tokenHandler = new JwtSecurityTokenHandler();

			var tokenDescriptor = new SecurityTokenDescriptor
			{
				Issuer = "A"
			};

			for (var i = 0; i < 100; i++)
			{
				using (var algorithm = ECDsa.Create()) // this code doesn't work
				{
					tokenDescriptor.SigningCredentials = new SigningCredentials(new ECDsaSecurityKey(algorithm)
					{
						KeyId = "A"
					}, SecurityAlgorithms.EcdsaSha256);
					var token = tokenHandler.CreateEncodedJwt(tokenDescriptor);
				}
			}
		}
	}
}
```

**Comment by VladislavMorozov** [comment]
@krwq I updated code for you. Just add docker support in the visual studio and run on Linux container.

**Comment by VladislavMorozov** [comment]
@krwq I have another exception on Core 3.0)

![image](https://user-images.githubusercontent.com/31768904/69430201-22be7380-0d46-11ea-921d-1661ef1ef021.png)


```
FROM mcr.microsoft.com/dotnet/core/runtime:3.0-buster-slim AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS build
WORKDIR /src
COPY ["AppleMusic/AppleMusic.csproj", "AppleMusic/"]
RUN dotnet restore "AppleMusic/AppleMusic.csproj"
COPY . .
WORKDIR "/src/AppleMusic"
RUN dotnet build "AppleMusic.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "AppleMusic.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AppleMusic.dll"]
```

**Comment by VladislavMorozov** [comment]
@bartonjs I found ObjectDisposedException, but in 3.0 Core :)

**Comment by VladislavMorozov** [comment]
> (And _key being null would have been an ObjectDisposedException anyways.) Huh.

@bartonjs I found ObjectDisposedException, but in 3.0 Core :)

**Comment by VladislavMorozov** [comment]
@krwq 

```
namespace System.Security.Cryptography
{
#if INTERNAL_ASYMMETRIC_IMPLEMENTATIONS
    internal static partial class ECDsaImplementation
    {
#endif
        public sealed partial class ECDsaOpenSsl : ECDsa
```

![image](https://user-images.githubusercontent.com/31768904/69906383-8b0af600-13d3-11ea-9fbe-a3b5b6b1556e.png)

**Comment by bartonjs** [comment]
`_key._key` being null there and an ObjectDisposedException in 3.0 look like the same thing (there's now a `ThrowIfDisposed()` call before the highlighted line).

The only thing that sets `_key` (or `_key._key`) to null is calling Dispose on the ECDsa(OpenSsl) instance.  If you put a breakpoint down at line 169 you might be able to figure out where your key is getting unexpectedly disposed.

**Comment by VladislavMorozov** [comment]
@bartonjs I updated my code. You can reproduce my bug on local machine. You just need linux docker container.

**Comment by VladislavMorozov** [comment]
Hello, somebody will be fixing this issue?

**Comment by krwq** [comment]
@VladislavMorozov it's already fixed in the latest version...

**Comment by brentschmaltz** [comment]
@VladislavMorozov it is the 'using' statement along with caching of SignatureProviders that is causing the issue.
IdentityModel should check if a key has been disposed before using the cached SignatureProvider.
The issue https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1302 captures this.

If we all agree, this issue could be closed.
