### ISSUE TITLE
Docs for LazyInitializer.EnsureInitialize<T>(ref T) are wrong

### ISSUE THREAD

**Issue by heaths** [dotnet/corefx#42643]
In the [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.threading.lazyinitializer.ensureinitialized?view=netstandard-2.0#System_Threading_LazyInitializer_EnsureInitialized__1___0__) for `LazyInitializer.EnsureInitialize<T>(ref T target)`, it states,
> In the event that multiple threads access this method concurrently, multiple instances of T may be created, but only one will be stored into target. In such an occurrence, this method will not dispose of the objects that were not stored. If such objects must be disposed, it is up to the caller to determine if an object was not used and to then dispose of the object appropriately.

The code uses `Activator.CreateInstance` if not already null (guarded by `Interlocked.CompareExchanged`) but `target` is only ever returned. The result of `Activator.CreateInstance` is lost if not placed into `target`, so callers can never dispose of it if not using an overload that takes a `Func<T>` and specifically checking for whether it was initialized.

I'm happy to fix the doc comments, but wanted confirmation first that this was actually the intended behavior and that the docs are wrong and should change.

**Comment by danmosemsft** [comment]
edited for formatting...

**Comment by danmosemsft** [comment]
I think you are correct, @stephentoub do you agree.

**Comment by stephentoub** [comment]
> @stephentoub do you agree

Yes, it's just a copy/paste from the `Func<T>`-based overload where it's correct.  It can be removed from this one without the func.

**Comment by danmosemsft** [comment]
@heaths note that the source of truth for the docs here is not code comments in this repo. It is in https://github.com/dotnet/dotnet-api-docs
A PR would be welcome there..I'll close this.

**Comment by heaths** [comment]
Thanks for the pointer. Didn't realize that.

**Comment by danmosemsft** [comment]
@heaths there's no way you could know -- we're quite anomalous in that respect. It's a legacy of history -- most of the API docs were written independent of the code comments over the years, and we don't plan to attempt to reverse engineer them back into the code. When we write new code, we do comment it and do a one-off ingestion, subsequently they live over there.
