### ISSUE TITLE
System.Net.HttpClient is stripping body for some statuses

### ISSUE THREAD

**Issue by suchoss** [dotnet/corefx#42650]
Hello, 
today I "discovered" a "problem" with HttpClient. I have already described the problem on [StackOverflow](https://stackoverflow.com/questions/58956869/is-there-any-way-how-to-get-httpresponsemessage-content-body-when-response-is-ht/58957661#58957661).

I would like to open a discussion if there is any real reason for stripping of content from response body? I am writing about following .net core code:
https://github.com/dotnet/corefx/blob/0cc22ccba707d7552159363d586262fa9c4e8a2a/src/System.Net.HttpListener/src/System/Net/HttpListenerResponse.cs#L83

Because how I look at it - I do not expect any hidden behavior from libraries. To me - status code is just a number and even if it is marked as **NoContent**, it doesn't have to necessarily mean that there is no additional information in body. Specially for REST communication.

Thanks

**Comment by stephentoub** [comment]
If you are actually asking about HttpClient, then the relevant code is actually here:
https://github.com/dotnet/corefx/blob/e99ec129cfd594d53f4390bf97d1d736cff6f860/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L602-L606

Note that sending a response body with a 204 status code is invalid according to the HTTP specification:
https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.5
"The 204 response MUST NOT include a message-body, and thus is always terminated by the first empty line after the header fields."

If the server does send a response body even though doing so violates the spec, a client can do anything it wants in response to such incorrect behavior.  You can see a discussion of this and the variety of things clients do at:
https://github.com/httpwg/http-core/issues/26

**Comment by suchoss** [comment]
Sorry, I was asking about HttpClient. Thanks for the clarification.

**Comment by suchoss** [comment]
I guess that it is a correct behavior then... When it is called HttpClient it should probably follow Http spec. Thanks for your time @stephentoub .
