### ISSUE TITLE
ConfiguraAwait(false) usability

### ISSUE THREAD

**Issue by bnayae** [dotnet/corefx#42659]
# ConfiguraAwait(false) usability

Using ConfiguraAwait(false) consider as best practice within a class library.
The problem with it is that it very verbose repetitive task.
It would be better experience if instead of repeating this task over and over again we could set a default for the assembly within the .csproj (or alternative via assembly level attribute).
This way the compiler can add it for it generated code under the assembly.

**Comment by tarekgh** [comment]
CC @stephentoub

**Comment by stephentoub** [comment]
This isn't a library issue / request, but rather something for the language compiler. There are already multiple related issues in the csharplang repo, e.g. https://github.com/dotnet/csharplang/issues/2542, https://github.com/dotnet/csharplang/issues/2746, etc.

Thanks.
