### ISSUE TITLE
CryptographicException is not created with the right HResult

### ISSUE THREAD

**Issue by heng-liu** [dotnet/corefx#42661]
We have 2 broken tests because the HResult has been changed for the CryptographicException exception, when using latest SDK(eg. 5.0.100-alpha1-015732).
It looks like the CryptographicException is not initiated with a right HResult on Linux and Mac.

The repro project is as following:
[TestPFX.zip](https://github.com/dotnet/corefx/files/3872903/TestPFX.zip)

Repro steps:
1. Unzip the project and  copy it to a Linux/Mac machine (installed .NET SDK 3.x and 5.0.100-alpha1-015732)
2. Go to ./TestPFX, run "dotnet build"
3. Run "dotnet ./bin/Debug/netcoreapp5.0/TestPFX.dll"
4. Run "dotnet ./bin/Debug/netcoreapp3.0/TestPFX.dll"
5. Compare the HResult of the two.
    The HResult of netcoreapp5.0 is -2146233087(0x80131501)
    The HResult of netcoreapp3.0 is 587686001(0x23076071)

**Comment by bartonjs** [comment]
Yep.  0x80131501 is the "exception, no further info" HResult.  The other came from OpenSSL.  Since we're not using OpenSSL at this step, we don't have an OpenSSL error code.
