### ISSUE TITLE
JsonIgnore

### ISSUE THREAD

**Issue by LeonardoMS01** [dotnet/corefx#42668]
I am confused with "JsonIgnore", which one should I use? NewtonSoft.Json or System.Text.Json.Serialization both do not work fully.

**Comment by Gnbrkm41** [comment]
I expect S.T.Json.Serialization.JsonIgnoreAttribute to work when using System.Text.Json and the Newtonsoft one when using Json.NET.

How are you using it & How does it not work?

**Comment by layomia** [comment]
@LeonardoMS01, can you provide some more context about what you are trying to do? A code snippet showing the scenario would be great.

**Comment by layomia** [comment]
Closing this issue. Please feel free to open another issue if you identify a proble with JsonIgnore.
