### ISSUE TITLE
getaddrinfo() API not working in a specific case

### ISSUE THREAD

**Issue by valakhin** [dotnet/corefx#42675]
We are facing an issue with getaddrinfo() API. 
 
We are trying to resolve IP address of remote host using getaddrinfo() from our server.  My server is enabled only with IPv4 and Remote host(windows server) is enabled with only with IPv6. The getaddrinfo() failed to retrieve remote host IP details.
 
hints.ai_family = AF_UNSPEC;
hints.ai_socktype = SOCK_STREAM;
hints.ai_protocol = IPPROTO_TCP;
dwRetval = getaddrinfo("remotehostname", "port", &hints, &result);
 
Note: If I do nslookup command from my server to remote host, I am able to get IPv6 address of my remote host.
 
If getaddrinfo() API could not provide IP address of remote server in this scenario, Is there any other API to get the IP address of remote server?. Appreciate your help regarding this.

**Comment by scalablecory** [comment]
This repo is for .NET Core, so discussion of these C APIs is off-topic. I would suggest asking for further assistance over in the [MSDN Forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowssdk&filter=alltypes&sort=lastpostdesc). Thanks.
