### ISSUE TITLE
Is NuGet major version upgrade allowed or not? Microsoft.Extensions.Logging.Abstractions

### ISSUE THREAD

**Issue by rlaci999** [dotnet/corefx#42676]
We have `netstandard2.0` projects with `EF Core` `2.2.6`. I tried to upgrade a console application's NuGet `Microsoft.Extensions.Logging.Abstractions` from `2.2` to `3.0.1` but got runtime error:

> Could not load type 'Microsoft.Extensions.Logging.Abstractions.Internal.NullScope' from 
> assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.0.1.0 

The error message seems legit, because `NullScope` was removed: [[Compare link]](https://www.fuget.org/packages/Microsoft.Extensions.Logging.Abstractions/3.0.1/lib/netstandard2.0/diff/2.2.0/?code=true), and Semantic Versioning enables breaking changes at major version change.

**But why is it not written at the NuGet dependencies?** [[NuGet link]](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions/3.0.1)

There are some other `Microsoft.Extensions.*` `3.0.1` packages that seem working well.

**What is the right way to determine on which version can I update? Is it mandatory to stick to always the current major version?**
If so, then at which NuGets? For example `Microsoft.NET.Test.Sdk` `16.4.0` works pretty well.

**Comment by ericstj** [comment]
NuGet questions belong in https://github.com/nuget/home.
aspnet/extensions questions belong in https://github/aspnet/extensions.

Here's the commit that made this breaking change: https://github.com/aspnet/Extensions/commit/678fc58f472cc08e4387d51f1882a48ed7e26f47  @pranavkm
