### ISSUE TITLE
Dictionary allows duplicate keys!

### ISSUE THREAD

**Issue by aqunovus** [dotnet/corefx#42680]
# Issue Title

When I try to add same key to Dictionary, I am always expecting to get "ArgumentException" however after a while Dictionary accepts same key and its count is increased.

# General

Version = .NET Core 3
OS = Win10 Pro
IDE = Visual Studio 2019 Community 2019

Example Code:

I am using Dictionary which is not thread-safe. (System.Collections.Generic)

```C#
private void Run()
        {
            bool isError = true;
            while (isError)
            {
                var dict = new Dictionary<int, int>();
                dict.Add(10, 10);

                try
                {
                    Parallel.Invoke(
                       () =>
                       {
                           // action1
                           Thread.Sleep(500);
                           dict.Add(20, 20);
                       },
                       () =>
                       {
                           // action2
                           Thread.Sleep(500);
                           dict.Add(20, 30);
                       }
                   );
                }
                catch (Exception)
                {
                    isError = true;
                    continue;
                }

                isError = false;
                Console.WriteLine($"It should never be reached: dictCount={dict.Count} dict[10]={dict[10]} dict[20]={dict[20]}");
                // Eg: It should never be reached: dictCount=3 dict[10]=10 dict[20]=30
            }
        }
```

It should never reach to the message but it reaches! Also, It gives 3 for Dictionary item Count with two 20s as key.

Screenshot:
![image](https://user-images.githubusercontent.com/2474419/69447256-36c69d00-0d67-11ea-99c5-b27cec3a1555.png)

**Comment by scalablecory** [comment]
`Dictionary` is not thread-safe, so these sorts of race conditions are to be expected when used this way.

You will need to put a lock around the `Dictionary` operations, or consider using `ConcurrentDictionary`.

**Comment by aqunovus** [comment]
I am aware of `Dictionary` is not thread-safe, I also mention about it in my comment. Also, I know about `ConcurrentDictionary` and `lock` solutions.

I just wanted to share that I was expecting `ArgumentException` or `InvalidOperationException` for these kind of multi-access operation. "**Duplicated Key**" was not expected for me because of nature of Dictionary and its Key controls which handled via HashCode of keys...

**Comment by danmosemsft** [comment]
> I just wanted to share that I was expecting ArgumentException or InvalidOperationException for these kind of multi-access operation. "Duplicated Key" was not expected for me because of nature of Dictionary and its Key controls which handled via HashCode checks.

It is probably impossible to make invalid concurrent access fail deterministically without a performance penalty. The reason it does not make concurrent access actually safe is to avoid a performance penalty.

Historically it would typically cause lookups to enter an infinite loop. In recent versions of .NET Core, Dictionary will instead fail deterministically with "Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.". The idea being that a crash is more helpful than a hang.

**Comment by sharwell** [comment]
> I am aware of Dictionary is not thread-safe

To clarify, this means that parallel access to `Dictionary` is allowed to do _anything_. This includes leaving the dictionary in a _permanently_ invalid state where no further APIs return the correct value. You could have duplicate keys, missing keys/values, incorrect counts, failure to enumerate, exceptions for valid calls, exceptions for invalid calls, or any other behavior.

As soon as parallel access comes into play, if you find yourself saying "I expected _____" then there is already a mistake. There are no expectations to make.

**Comment by aqunovus** [comment]
> It is probably impossible to make invalid concurrent access fail deterministically without a performance penalty. The reason it does not make concurrent access actually safe is to avoid a performance penalty.

> Dictionary will instead fail deterministically with "Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct."

Thanks @danmosemsft for great explanation. I was also reading about this issue and pull request. 
I am using ".NET Core 3" and thinking about `InvalidOperationException` should be thrown. But your clarification about non-deterministic behaviour and performance penalty makes me enlighten about this issue.

https://github.com/dotnet/corefx/issues/28123
https://github.com/dotnet/coreclr/pull/16991

**Comment by danmosemsft** [comment]
Cool - thanks for the issue though, @aqunovus 

BTW, we welcome contributors to our code, if you are interested. Take a look at the README on this repo for pointers on which issues might be interesting and how to get started. It's an interesting time as over the next week we are moving to a new repo, but the code and issues will be the same.
