### ISSUE TITLE
Sara Chipps [.NET Foundation Board Member] Behavior

### ISSUE THREAD

**Issue by TechnikEmpire** [dotnet/corefx#42703]
I'm wondering if the .NET Foundation can respond to the behavior of one its board members, Sara Chipps.

I'll just post links here and let the facts speak for themselves:
https://meta.stackexchange.com/questions/336526/stack-overflow-is-doing-me-ongoing-harm-its-time-to-fix-it

https://meta.stackexchange.com/questions/335173/se-inc-director-of-public-qa-retweets-bad-faith-misrepresentative-tweet

Also I'm wondering why Sara Chipps' .NET Foundation [campaign page](https://election.dotnetfoundation.org/campaign-2019/sara-chipps.html) states that her top priority is to embrace and spread ageism where she directly equates "old coders" with obsoleteness.

> When we think of ColdFusion and Flash we think of closed source platforms and **older coders**. In order to ensure .NET doesn’t fall the way of **forgotten frameworks** we need to encourage the community to work with **student coders** and through mentorship and sponsorship promote them to .NET Contributors.

Thanks.

**Comment by Gnbrkm41** [comment]
I do not think this is an appropriate place for such an issue. This repo focuses on development of the .NET Core BCL and issues related with it, not about .NET Foundation itself and members of the foundation.

**Comment by TechnikEmpire** [comment]
@Gnbrkm41 given that github and the .net foundation have implemented codes of conduct I think its appropriate. If an repo is being run in part by someone who is apparently antisemitic and ageist, discriminatory in way, I'd say that's an issue.

**Comment by Joe4evr** [comment]
@TechnikEmpire You should send an e-mail to `conduct@dotnetfoundation.org`.

**Comment by TechnikEmpire** [comment]
OK thanks. I'm not really down with professional victimhood but since the .net foundation and Microsoft have made it official policy and since a board member is flagrantly trampling all over said policy, I will send an email there.

**Comment by terrajobst** [comment]
As @Gnbrkm41 pointed out, this repo isn't the correct place for CoC violations.

As per the [Code of Conduct](https://www.dotnetfoundation.org/code-of-conduct) please report any concerns to conduct@dotnetfoundation.org. All complaints will be reviewed and investigated in confidence and will result in a response that is deemed necessary and appropriate to the circumstances.

Therefore I am closing this issue but please do get in contact with the Conduct folks if you have concerns.
