### ISSUE TITLE
PropertyNameCaseInsensitive flag doesn't affect

### ISSUE THREAD

**Issue by warrior1305** [dotnet/corefx#42705]
For now, it is unable to use Text.Json as input formatter for CamelCase'd JSON. Setting flag to true did nothing.
``` C#
        .AddJsonOptions(options => {
            options.JsonSerializerOptions.PropertyNameCaseInsensitive = true;
         });
```

Also, this problem is not a very new
https://stackoverflow.com/questions/58476681/asp-net-core-3-0-system-text-json-camel-case-serialization/58476771#58476771

Version: the one that comes with AspNetCore 3.0.0

**Comment by ahsonkhan** [comment]
@warrior1305 - why did you close the issue? What was the issue and was it fixed? From the title/description, it's hard to discern what unexpected behavior you were seeing. Which side was not working - serialization (writing JSON) or deserialization (reading JSON)?
