### ISSUE TITLE
Question: Getting a ReadOnlySpan<byte> from a ref struct

### ISSUE THREAD

**Issue by slang25** [dotnet/corefx#42709]
If I have my own `readonly ref struct` such as this:

```csharp
public readonly ref struct Coords
{
    public readonly int X;
    public readonly int Y;
}
```

It would be constrained to the stack and readonly, so would I be able to get a `ReadOnlySpan<byte>` to it, without any copying on the stack (or elsewhere?).

**Comment by Gnbrkm41** [comment]
`new ReadOnlySpan<byte>(&coords, sizeof(Coords))`?

(As a sidenote, I do not think that this does not really have to be a ref struct)

**Comment by ufcpp** [comment]
ralated to https://github.com/dotnet/csharplang/issues/1792 ?

**Comment by ufcpp** [comment]
FYI

```cs
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

public readonly ref struct Coords
{
    public readonly int X;
    public readonly int Y;
}

public static class CoordsExtensions
{
    public static ReadOnlySpan<int> AsSpan(in this Coords c) => MemoryMarshal.CreateReadOnlySpan(ref Unsafe.AsRef(in c.X), 2);
}
```

**Comment by slang25** [comment]
Thanks @Gnbrkm41 & @ufcpp!

I should have been clearer in the question, but it was the extension method that was most helpful, and dotnet/csharplang#1792 is what I'm really battling against.

It's hard to keep the compiler happy with `ref struct`, when you can't pass the type as a generic argument, making a lot of the `MemoryMarshal` & `Unsafe` APIs unavailable.

Thanks again 😁
