### ISSUE TITLE
DateTime.ToString("MM/dd/yyyy") does not treat "/" as literal character

### ISSUE THREAD

**Issue by mnmr** [dotnet/corefx#42702]
If your current locale specifies a different character than "/" as a date component separator, the following line of code will emit a string using the localized separator (which it should not, at least if backwards compatibility is any concern).

`DateTime.Now.ToString("MM/dd/yyyy")` emits `11-25-2019` with .NET Core 3. However, the same line of code using .NET Framework will emit `11/25/2019`.

This silently breaks existing code that depends on the earlier (and imo correct) behavior.

**Comment by Gnbrkm41** [comment]
https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#dateSeparator

>The `/` custom format specifier represents the date separator, which is used to differentiate years, months, and days. *The appropriate localized date separator is retrieved from the DateTimeFormatInfo.DateSeparator property of the current or specified culture.*

It is supposed to do so per the document. Have you checked if the `CultureInfo.CurrentCulture` is set to a culture that uses a forward slash for the date separator when testing the above code on .NET framework?

**Comment by mnmr** [comment]
You are correct, I don't know why I thought this behaved differently in .NET Framework. Sorry!
