### ISSUE TITLE
Path.GetDirectoryName removes necessary relative paths

### ISSUE THREAD

**Issue by cdmihai** [dotnet/corefx#4274]
`Path.GetDirectoryName(@"..\..\files.txt")` returns an empty string instead of `..\..`

This breaks stories such as "write a new file in the same directory as another specific file"

**Comment by joshfree** [comment]
@Priya91 @ianhays @JeremyKuhne

**Comment by Joe4evr** [comment]
I thought that when you prefix a string with `@`, you don't need to escape backslashes for file paths, so could that have something to do here?

**Comment by cdmihai** [comment]
Sorry, it was late and I misspelled the path. I updated the description.

**Comment by JeremyKuhne** [comment]
I'm digging into this.
