### ISSUE TITLE
Error: GSSAPI operation failed with error - An unsupported mechanism was requested. NTLM authentication requires the GSSAPI plugin 'gss-ntlmssp'

### ISSUE THREAD

**Issue by sulemanb** [dotnet/corefx#42748]
Hi All,

I am facing this error message when my api (dotnet core 3) tries to call another api endpoint.
I am packaging my apis as docker images on the on-prem k8s docker enterprise cluster.

My docker file is as follows:

`
#FROM microsoft/dotnet:2.2-aspnetcore-runtime-alpine AS runtime
FROM ddcdtr.bayer.cnb/microsoft/dotnet-core-aspnet:3.0 AS runtime

WORKDIR /app
# Only Metadata
#EXPOSE 80
ENV PORT=8080
ENV ASPNETCORE_URLS=http://+:${PORT}

ENV HTTP_PROXY=${http_proxy}
ENV HTTPS_PROXY=${https_proxy}

EXPOSE $PORT

#ARG ASPNETCORE_ENVIRONMENT
#ENV ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
# https://rehansaeed.com/securing-asp-net-core-in-docker/
ENV COMPlus_EnableDiagnostics=0

#FROM microsoft/dotnet:2.2-sdk AS build
FROM ddcdtr.bayer.cnb/microsoft/dotnet-core-sdk:3.0 AS build

RUN apt-get update
#RUN apt-get -y install gss-ntlmssp
RUN apt-get update && apt-get install -y --no-install-recommends gss-ntlmssp

WORKDIR /src
#ARG NUGET_CONFIG
#RUN echo $NUGET_CONFIG > NuGet.config

COPY Bardo.Data/Bardo.Data.csproj Bardo.Data/
COPY GBoxApi/GBoxApi.csproj GBoxApi/
COPY GBoxApi.IntegrationTests/GBoxApi.IntegrationTests.csproj GBoxApi.IntegrationTests/
COPY GBoxData/GBoxData.csproj GBoxData/

RUN dotnet restore GBoxApi/GBoxApi.csproj

COPY . .
WORKDIR /src/GBoxApi

RUN dotnet build -c Release -o /app

FROM build AS publish

RUN dotnet publish -c Release -o /app

FROM runtime AS final

###

# Create a group and user
#RUN addgroup -S -g 1000 appgroup \
#&& adduser -S -u 1000 -G appgroup -s /bin/sh appuser

###

WORKDIR /app

RUN mkdir -p /local/

COPY --from=publish /app .

COPY --from=build /src/GBoxApi/GBoxApi.xml .
#COPY --from=build . .

#RUN chown appuser:appgroup /local
#RUN chown appuser:appgroup /app

USER root:root

# Tell docker that all future commands should run as the appuser user
#USER appuser

ENTRYPOINT ["dotnet", "GBoxApi.dll"]

`

build and deployment is all fine, but at runtime, my application throws this error after (log entry 4) at client.SendAsync(request);

`
public async Task<Permission> GetPermissionsAsync(string identity, string context)
        {
            string log = "/n Start: ";
            try
            {
                Permission result = null;
                var permissionUri = $"{ _config["PermissionAPI:BaseUrl"] }?digitalIdentity={identity}&apiContext={context}";
                log += "1 ";
                var request = new HttpRequestMessage(HttpMethod.Get, permissionUri);
                log += "2 ";
                request.Headers.Add("Accept", "application/json");
                log += "3 ";

                var client = _clientFactory.CreateClient();
                log += "4 PermissionUri: " + permissionUri;

                var response = await client.SendAsync(request);

`

i have also tried other base images for (sdk, runtime) like dotnet-core-aspnet:3.0-alpine and dotnet-core-sdk:3.0-alpine, but still same problem.

**Comment by sulemanb** [comment]
problem resolved!
I just noticed that i was not installing:
`RUN apt-get update && apt-get install -y --no-install-recommends gss-ntlmssp`
inside my base dotnet core "runtime" image, but sdk!

**Comment by davidsh** [comment]
>problem resolved!

Glad it's working now.  The 'gss-ntlmssp' is required to be installed in order for NTLM protocol to work. That includes specific NTLM and Negotiate (when it downgrades from Kerberos to NTLM) authentication schemes.
