### ISSUE TITLE
FileNotFoundException with FileInfo.Length on Linux if binary filename contains a 0xDF-Byte 

### ISSUE THREAD

**Issue by mshobohm** [dotnet/corefx#42755]
Special characters in Linux filenames can confuse the FileInfo.Length property, resulting in FileNotFoundException as shown in the attached test case , see also readme.txt.

[SSharpException.zip](https://github.com/dotnet/corefx/files/3921699/SSharpException.zip)

**Comment by mshobohm** [comment]
Registered again at https://github.com/dotnet/runtime/issues/513

**Comment by danmosemsft** [comment]
thanks for porting the issue. closing this one.
