### ISSUE TITLE
Code search broken on the repo?

### ISSUE THREAD

**Issue by los93sol** [dotnet/corefx#42779]
I've noticed for at least the last week that searching the repo for code doesn't seem to work anymore.  Other repos like aspnetcore seem to still be searching fine though.  Not sure where else to report the issue to so figured I'd just open an issue here.

**Comment by stephentoub** [comment]
This repo is now only for servicing.  The current code is in https://github.com/dotnet/runtime.

**Comment by danmosemsft** [comment]
I'll close this since that's the answer. See you in the runtime repo!
