### ISSUE TITLE
How to get RSACryptoServiceProvider from X509Certificate2 .Net Core

### ISSUE THREAD

**Issue by vasicvuk** [dotnet/corefx#42778]
Following code works in .Net 4.7.1 but not in .Net Core 3.1

```csharp
X509Store store = new X509Store(StoreLocation.CurrentUser);
store.Open(OpenFlags.ReadOnly);
X509Certificate2 cert = null;
foreach (X509Certificate2 cert2 in store.Certificates)
{
	if (cert2.HasPrivateKey && cert2.PrivateKey is RSACryptoServiceProvider rsa)
	{
             // .Net Core 3.1 nevers get RSACryptoServiceProvider and .Net Framework returns it
		if (rsa == null) continue; 
		if (rsa.CspKeyContainerInfo.HardwareDevice) // sure - smartcard
		{
			if ((rsa.CspKeyContainerInfo.KeyContainerName == KeyContainerName) && (rsa.CspKeyContainerInfo.ProviderName == ProviderName))
			{
				//we find it
				cert = cert2;
				break;
			}
		}
	}
}
```

I tried working with **RSACng** but i have few issues there. First i cannot get info from **CspKeyContainerInfo** needed for this. And also when i try to sign with this certificate it is always asking me for a PIN even if i defined **RSACryptoServiceProvider** before with **KeyPassword**.

.Net Framework code
```csharp
SecureString pwd = GetSecurePin(PinCode);

CspParameters csp = new CspParameters(1, ProviderName, KeyContainerName,
   new System.Security.AccessControl.CryptoKeySecurity(), pwd);
```

I need this only to work on Windows (ASP.Net Core 3.1).

I read https://github.com/dotnet/corefx/blob/master/Documentation/architecture/cross-platform-cryptography.md but i am not sure how to do migration.

Thanks

**Comment by bartonjs** [comment]
You'd have to P/Invoke into CertGetCertificateContextProperty and read the CERT_KEY_PROV_INFO_PROP_ID property manually (like .NET Framework does: https://referencesource.microsoft.com/#System/security/system/security/cryptography/x509/x509certificate2.cs,0a04b766023855de).

.NET Core has only minimal support for RSACryptoServiceProvider, it's a pretty deprecated type.  (It's the most limited, and hardest to use, of the RSA types)

**Comment by vasicvuk** [comment]
Hi @bartonjs.

Thanks for a link. I managed to this part manually  but now I am stuck with configuring CSP parameters so that i does not ask me for a PIN.

**Comment by bartonjs** [comment]
The CspParameters.KeyPassword property should work the same on Core as on Framework.

**Comment by vasicvuk** [comment]
Didn't work with KeyPassword but i managed to do everything as in .Net Framework. 

Thanks
