### ISSUE TITLE
StringContent doesn't update ContentLength property automatically after creation.

### ISSUE THREAD

**Issue by alexborichevskyidt** [dotnet/corefx#42777]
Working with integration tests, noticed that StringContent doesn't update property ContentLength in Headers after creation, what cause request parsing issues in API application when using a test client with payload.

Calling get for the property helped to resolve the issue.

**Comment by davidsh** [comment]
This is an old bug that we chose not to fix.  I'll find the bug in the CoreFx database.

**Comment by davidsh** [comment]
Duplicate of #5523
