### ISSUE TITLE
bitmap.MakeTransparent works different on linux

### ISSUE THREAD

**Issue by poweralex** [dotnet/corefx#42783]
I'm trying to draw a png image with a block of transparent on it. the same code works fine on local windows environment, but when I deploy it on a Linux server, the block does not go transparent.
the code is simple:
```c#
                    byte[] fileContent = null;
                    using (MemoryStream ms = new MemoryStream())
                    {
                        Bitmap bitmap = new Bitmap(
                            100, 100
                            );
                        using (var g = Graphics.FromImage(bitmap))
                        {
                            // backgrand
                            g.FillRectangle(new SolidBrush(Color.White), 0, 0, bitmap.Width, bitmap.Height);
                            // transparent block
                            g.FillRectangle(new SolidBrush(Color.Red), 10, 10, 80, 80);
                            // blue line
                            g.DrawLine(new Pen(Color.Blue), 10, 10, 90, 90);
                        }
                        bitmap.MakeTransparent(Color.Red);
                        bitmap.Save(ms, ImageFormat.Png);
                        fileContent = ms.ToArray();
                    }
```
the image looks good on windows:
![image](https://user-images.githubusercontent.com/12427030/70973935-a4a18280-20e1-11ea-95a2-d2b8604af9f0.png)
but not on Linux:
![image](https://user-images.githubusercontent.com/12427030/70974041-da466b80-20e1-11ea-9f3b-e329eda130d7.png)

Is this a issue of System.Drawing.Common or is there something I missed?

[danmosemsft fixed formatting]

**Comment by danmosemsft** [comment]
@safern @qmfrederik when a Drawing bug is Unix specific, am I right that it's pretty safe to ask to reopen it in [libgdiplus repo](https://github.com/mono/libgdiplus/issues) without investigation here?

**Comment by danmosemsft** [comment]
@poweralex what version of libgdiplus do you have on this server? Is there a newer one you can try?

**Comment by safern** [comment]
> pretty safe to ask to reopen it in libgdiplus repo without investigation here?

Most of the times yes, but sometimes it could be a wrong PInvoke or something since we have different PInvokes for some pieces depending on the OS, but if the code path is the same it is 100% safe to say it is a libgdiplus bug.

**Comment by danmosemsft** [comment]
OK, @poweralex if this still reproes on the newest libgdiplus you have access to, please close this and reopen there. Thanks for the report.

**Comment by poweralex** [comment]
I'm using libgdiplus 6.0.2 on a docker of alpine linux v3.8.4

**Comment by danmosemsft** [comment]
Closing in favor of libgdiplus issue
