### ISSUE TITLE
captcha در مرورگر موبایل ارور میده

### ISSUE THREAD

**Issue by karimi64bit** [dotnet/corefx#42781]
سلام
ممنون از زحمت هاتون 
وقتی ازش استفاده میکنم درسته فقط وقتی تو موبایل دارم دکمه ریفرش میزنم کار نمیکنه
ممنون میشم راهنمایی کنید

**Comment by Clockwork-Muse** [comment]
Language is detected as Persian by Bing:

>hello
Thanks for your troubles
When I use it, just don't work when you've got a mobile button.
Thanks for your help

Do you have any other details?  Otherwise I'm afraid that it doesn't sound like there's anything actionable for us here.

**Comment by danmosemsft** [comment]
@maryamariyan

**Comment by maryamariyan** [comment]
Slightly improved the bing translation. 

Thank you for your question, but as @Clockwork-Muse mentioned unless you have more information it doesn't sound like there's anything actionable for us here. Translating as follows:

@Clockwork-Muse مرسی از سوال، همانطور که 
 اشاره کردند، اگر اطلاعات بیشتری ندارید به نظر نمیاد کاری از دست ما اینجا بر بیاد
