### ISSUE TITLE
Please provide inline authorization support for HttpClient

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/corefx#4279]
Hi,

The [`HttpClient`](https://github.com/dotnet/corefx/blob/c02d33b18398199f6acc17d375dab154e9a1df66/src/System.Net.Http/src/System/Net/Http/HttpClient.cs) facility is amazing.

However, it lacks OO support for authentication and authorization.

There should be a way to set a few properties (like `ClientId`, `SecretId`, `AuthenticationType`, `UserName` and `Password` etc.), and once the `HttpClient` is initialized with authentication, it should internally keep track of its authentication state, token expiry, refresh tokens, and all that.

**Comment by davidsh** [comment]
cc: @SidharthNabar

**Comment by Kagamine** [comment]
I don't think ClientId, SecretId etc are the infrastructures of HttpClient. It may be based on cookies or headers. The theory of them are proposed by `Identity`, not a standard of HttpRequest or response.

**Comment by weitzhandler** [comment]
Anyway, I'm trying to implement that over the `HttpClient` class, and I can't understand why overriding the `SendAsync` method [does nothing](http://pastebin.com/raw.php?i=QNGz4qWa).

**Comment by Kagamine** [comment]
You should contains your cookies when you create a request.

**Comment by Kagamine** [comment]
What is the cancellationToken?

**Comment by weitzhandler** [comment]
@Kagamine
>I don't think ClientId, SecretId etc are the infrastructures of HttpClient. It may be based on cookies or headers. The theory of them are proposed by Identity, not a standard of HttpRequest or response.

I understand what you're saying, so where do you think that `HttpClient` subclass does belong to?

I believe a substantial percentage of the HTTP requests the `HttpClient` serves, utilize authorization and authentication of some extent. IMHO, it does fit in the official .NET framework, just as Web API does. The thing is that the tools for server side development are all there while client-side tools lack support for this, and everything is done inconsistently and hard-coded.

>You should contains your cookies when you create a request.
You're wrong. I wasn't talking about `WebClient`. The `HttpClient` is especially made to serve RESTful service, and as such, cookies is the second option.

Anyway, I'm trying to implement that over the `HttpClient` class, and I can't understand why overriding the `SendAsync` method [does nothing](http://pastebin.com/raw.php?i=QNGz4qWa), which turns this post into a bug. `cancellationToken` doesn't matter right now. It should have printed `Send async called.`.

**Comment by Kagamine** [comment]
Let me see the source of HttpClient, wait a moment.

**Comment by weitzhandler** [comment]
@Kagamine I've already checked that, they all call `SendAsync` which makes the issue even more weird.

**Comment by Kagamine** [comment]
Oh..

**Comment by weitzhandler** [comment]
Oops, I just checked the [source](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpClient.cs#L334), and looks they call all the methods call the non-overridable `SendAsync`. Makes no sense to me.

**Comment by Kagamine** [comment]
Are you sure you are using corefx? It works on my computer

**Comment by weitzhandler** [comment]
What works on your system? It shouldn't. The `override SendAsync` actually does nothing...

**Comment by Kagamine** [comment]
Hah
`SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)` cannot be overriden

**Comment by Kagamine** [comment]
But you can copy the source of HttpClient into your project and make some changes with SendAsync

**Comment by weitzhandler** [comment]
@Kagamine r u kidn me

**Comment by Kagamine** [comment]
:fearful: What's the meaning QAQ

**Comment by Kagamine** [comment]
Sorry, copy cannot solve the problem. There are some internal properties in it.

**Comment by weitzhandler** [comment]
Talking about minimalism, please avoid repeating duplicated messages. Instead edit your last message to add content.

**Comment by Kagamine** [comment]
Can you try this:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Net.Http;
using System.Diagnostics;
using System.Diagnostics.Contracts;
using System.IO;
using System.Net.Http.Headers;


namespace ConsoleApp5
{
    public class Program
    {
        static void Main(string[] args)
        {
            Task.Run(async () => { await RunAsync(); }).Wait();
            Console.WriteLine("Press any key to finish.");
            Console.Read();
        }

        public static async Task RunAsync()
        {
            Console.WriteLine("RunAsync called.");
            using (var client = new MyHttpClient())
                await client.GetAsync("http://www.google.com");
        }
    }

    public class MyHttpClient : HttpClient
    {
        public MyHttpClient()
        {
            Console.WriteLine("Client instantiated.");
        }

        public new Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption,
            CancellationToken cancellationToken)
        {
            Console.WriteLine("Send async called.");
            return base.SendAsync(request, completionOption, cancellationToken);
        }

        public new Task<HttpResponseMessage> GetAsync(string requestUri)
        {
            return SendAsync(new HttpRequestMessage(HttpMethod.Get, new Uri(requestUri)), HttpCompletionOption.ResponseContentRead, CancellationToken.None);
        }
    }
}

```

**Comment by weitzhandler** [comment]
@Kagamine you're missing the point. I don't want to shadow members, I want to **override** them, so all my calls to `GetAsync` `PutAsync` etc. are caught by it.

**Comment by Kagamine** [comment]
Maybe you have to use ILGenerator...

**Comment by davidsh** [comment]
Hello:

The design of the HttpClient is that if you want to override the 'SendAsync` in order to provide custom request processing or response processing, you need to create a subclass of the HttpMessageHandler class.  That has the virtual SendAsync() method to override.

Then you pass that handler to the constructor of the HttpClient object.  You shouldn't be creating subclasses of HttpClient itself.

The default handler is the HttpClientHandler which is created automatically in the default construtor of the HttpClient object.  You can also create an instance of the HttpClientHandler to pass into the HttpClient object.  That handler has many properties for customizing the request as well.

**Comment by Kagamine** [comment]
:tada:

**Comment by weitzhandler** [comment]
@davidsh 
 Yep. I see, that's what I suspected.
Anyway, I'm hoping to see this feature implemented soon, and wish to see some more love for the client side and consumers of Web API.

**Comment by CIPop** [comment]
The issue is tracking a lot of new APIs that will need to be added to netcoreapp1.2. 
I believe it's a large item that requires following the API process, implementing and testing the APIs on all platforms (cURL, WinHTTP).

**Comment by davidsh** [comment]
Now that we have a new repo specifically for design discussions, please continue the discussion in dotnet/designs#9 or open a new issue in https://github.com/dotnet/designs
