### ISSUE TITLE
System.Net.HttpListener binds port by System process

### ISSUE THREAD

**Issue by peter-volkov** [dotnet/corefx#428]
Reposting from https://github.com/pfn/keepasshttp/issues/195

Code snippet 

        HttpListener listener = new HttpListener();
        listener.Prefixes.Add("http://localhost:18888/");
        MessageBox.Show(Process.GetCurrentProcess().Id.ToString());
        listener.Start();
        MessageBox.Show(Process.GetCurrentProcess().Id.ToString());

at my windows 8.1 pro with latest updates somehow binds port 18888 by System process (PID 4) instead of application process. So other apps can not interact with it.

Both messageboxes show correct PID of application.

What's wrong?

**Comment by justinvp** [comment]
Isn't this by-design? [`HttpListener`](http://msdn.microsoft.com/en-us/library/ms229710(v=vs.110).aspx) is built on top of HTTP.sys, which is the kernel mode listener that handles all HTTP traffic for Windows.

**Comment by peter-volkov** [comment]
Yep, sounds wise.
