### ISSUE TITLE
Path issues when running corefx tests for .NET Core 3.1 tag, what is RunTests.sh?

### ISSUE THREAD

**Issue by assyadh** [dotnet/corefx#42811]
Hi,

I am trying to run the tests for corefx using the v3.1.0 tag.

I have my corefx build output in ```/build/corefx/artifacts/bin```

When I try to run the following: 

``` ./eng/run-test.sh --configurationGroup Release```

I get the following result:
```
Nothing to test in Common.Tests
Nothing to test in Invariant.Tests
Nothing to test in Microsoft.CSharp.Tests
Nothing to test in Microsoft.Bcl.AsyncInterfaces.Tests
Nothing to test in Microsoft.VisualBasic.Core.Tests
Nothing to test in Microsoft.Win32.Primitives.Tests
Nothing to test in System.Buffers.Tests
Nothing to test in System.AppContext.Tests
Nothing to test in Microsoft.XmlSerializer.Generator.Tests
Nothing to test in System.CodeDom.Tests
Nothing to test in System.Collections.Concurrent.Tests
Nothing to test in System.Collections.NonGeneric.Tests
Nothing to test in System.Collections.Specialized.Tests
Nothing to test in System.Collections.Immutable.Tests
Nothing to test in System.Collections.Tests
Nothing to test in System.ComponentModel.Annotations.Tests
Nothing to test in System.ComponentModel.Composition.Registration.Tests
Nothing to test in System.ComponentModel.Composition.Tests
Nothing to test in System.ComponentModel.EventBasedAsync.Tests
Nothing to test in System.ComponentModel.Primitives.Tests
Nothing to test in System.ComponentModel.Tests
...
```

Which leads me to believe there is a path issue.

Effectively, my *.Tests folder contain a ```netcoreapp-Release``` folder with no mention of an OS or Arch as required in the run-test.sh script https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/eng/run-test.sh#L201

```
ls artifacts/bin/System.Data.Common.Tests/
netcoreapp-Release
```

Here is how I am building corefx:

```./build.sh --buildtests --configuration Release --os Linux```

So at this point, after editing the ```run-test.sh#L201``` script above, and removing the OS and Arch properties, I get the following output: ``` dirName="$1/netcoreapp-$ConfigurationGroup"```

I am facing the following issues:

```
Nothing to test in System.Xml.XPath.XDocument.Tests
Cannot find /build/corefx/artifacts/bin/tests/System.Xml.Xsl.XslCompiledTransformApi.Tests/netcoreapp-Release/RunTests.sh
Cannot find /build/corefx/artifacts/bin/tests/System.Xml.XPath.XmlDocument.Tests/netcoreapp-Release/RunTests.sh
Cannot find /build/corefx/artifacts/bin/tests/System.Xml.Xsl.XslTransformApi.Tests/netcoreapp-Release/RunTests.sh
Cannot find /build/corefx/artifacts/bin/tests/XsltCompiler.Tests/netcoreapp-Release/RunTests.sh
```

So my questions: 
**Am I trying to run the tests the correct way?
What is that RunTests.sh script? I can't get a hold of it.**

I am successfully running the corefx test on .NET Core 2.1.13, and trying to adapt my scripts for 3.1, but can't get this part to work.

Thanks for the help

**Comment by assyadh** [comment]
Hey @ViktorHofer Looks like you may be the guy to talk to?

**Comment by assyadh** [comment]
Looks like it is related to this file: https://github.com/dotnet/runtime/blob/master/eng/testing/RunnerTemplate.sh

But it is not there in the v3.1.0 tag: 

https://github.com/dotnet/corefx/tree/v3.1.0/eng

**Comment by ViktorHofer** [comment]
> Am I trying to run the tests the correct way?

On which OS are you trying to run the tests? Note that we migrated this repository to https://github.com/dotnet/runtime. Usually you run tests by doing a `build.cmd/sh -restore -build -buildtests -test`.

**Comment by assyadh** [comment]
Thanks, that works. I was trying to adapt the 2.1 instructions for 3.1, which changed.
