### ISSUE TITLE
System.Text.Json disallows string literals surrounded by single quotes

### ISSUE THREAD

**Issue by lorranpalmeira** [dotnet/corefx#42819]
´´´
var objectExpeted = @"{
              'cep': '01001-000',
              'logradouro': 'Praça da Sé',
              'complemento': 'lado ímpar',
              'bairro': 'Sé',
              'localidade': 'São Paulo',
              'uf': 'SP',
              'unidade': '',
              'ibge': '3550308',
              'gia': '1004'
            }";

 //var expected = JsonSerializer.Deserialize<Cep>(objectExpeted);
    var expected = JsonConvert.DeserializeObject<Cep>(objectExpeted);
´´´

It has an exception when I try Deserialize in JsonSerializer.In NewtonSoft works perfectly.

![image](https://user-images.githubusercontent.com/18705060/72375374-b9763380-36ea-11ea-8aab-f8892c3f9a33.png)

**Comment by khellang** [comment]
You're using single quotes which is invalid JSON. From the migration article:

> System.Text.Json is strict by default and avoids any guessing or interpretation on the caller's behalf, emphasizing deterministic behavior. The library is intentionally designed this way for performance and security. Newtonsoft.Json is flexible by default. This fundamental difference in design is behind many of the following specific differences in default behavior.

This works with Newtonsoft because it's very flexible and allows a ton of non-standard features. This will probably never work with System.Text.Json 😊

**Comment by ahsonkhan** [comment]
This issue is similar to https://github.com/dotnet/corefx/issues/41421 (which talks about having support for no quotes for names, but the same applies to single quotes).

As @khellang mentioned, the bar for such a feature would be quite high and I don't see enough evidence to suggest we should support such flexibility (anything other than double quoted strings), at the cost of perf for the common case and increased code complexity.

**Comment by ahsonkhan** [comment]
Also, just a reminder, please open new issues in https://github.com/dotnet/runtime and not in this repo.

Look at these pinned issues:
https://github.com/dotnet/corefx/issues/42733
https://github.com/dotnet/corefx/issues/42716
