### ISSUE TITLE
[BUG] .Net Core ArrayPool

### ISSUE THREAD

**Issue by faruknane** [dotnet/corefx#42814]
I have tried to use Array Pool many times. Every time I used it to create many arrays with big sizes, I encountered a problem. The problem is after a while my deep learning library runs it throws "System.AccessViolationException HResult=0x80004003 Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.". So, I infer that array pool doesn't work well, because I saw that I couldn't use an array long enough even though I didn't return it. So I implemented two new versions for my performance library. Now it works pretty well. However, I think there is a bug going on with Net core ArrayPool.

**Comment by faruknane** [comment]
I liked the **Dotnet-GitSync-Bot**. Exciting to see...

**Comment by svick** [comment]
If you think there is still a bug, can you share code that reproduces it?

**Comment by stephentoub** [comment]
> The problem is after a while my deep learning library runs it throws "System.AccessViolationException HResult=0x80004003 Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.".

That is almost certainly going to be an issue with the library itself, in how it's accessing the arrays using unsafe code, making assumptions about the state of the array when it's retrieved (e.g. zero'd vs not), etc.  Please share a repro; without that, this isn't actionable.

Also, when you say "big sizes", what's an example size?  Arrays larger than a megabyte or two won't be pooled; the pool will just allocate a new one and won't store it, no different than if you just new'd one up.

**Comment by faruknane** [comment]
It's a big project that I can't update on github now. The code is changed with my arraypool implementation. So I can't create the same case now. Maybe it became pointless to open the issue like that. But I believe that some arrays get unusable after a while. I'll try to create a small test code (other than my project) in a few hours.

**Comment by faruknane** [comment]
Could it be because I don't use the arrays directly? I use pointers instead of arrays in unsafe methods. Because it needs highly optimization. I preferred to use pointers. However, I know that the pointer of an array is fixed until it dies? Or Can they change during run time (like the same array but it needs to be moved to another location in memory for some sort of reasons. and its pointer becomes another adress?)

**Comment by stephentoub** [comment]
> I use pointers instead of arrays in unsafe methods. Because it needs highly optimization. I preferred to use pointers. However, I know that the pointer of an array is fixed until it dies?

If you have an array (regardless of where you got it from), and you get a pointer to it, that pointer is only valid while you're explicitly pinning the array, either with `fixed` or with a GCHandle.  If you try to use that pointer and the array hasn't been pinned the entire time, the GC could have moved it and your pointer may no longer be pointing to what you thought it was pointing to.  That is almost certainly the cause of your AV.  That's not related to the array pool.

**Comment by faruknane** [comment]
I'm coding a deep learning library and I am aware of that. I don't use an array that is returned to the pool. I look up my matrix classes and I see that it throws the error even though the array is not returned yet.

**Comment by stephentoub** [comment]
> I don't use an array that is returned to the pool. I look up my matrix classes and I see that it throws the error even though the array is not returned yet.

I'm saying it sounds like you're getting a pointer to your array but not pinning the array for the lifetime you use that pointer, in which case the GC could move the array and invalidate your pointer.

**Comment by faruknane** [comment]
I remember that I created Living Arrays in my classes to stop GC from deleting the arrays.  Honestly, I don't know. It just works well with my implementation (I create the arrays using Intel MKL not to get GC tired). Do we close the issue?

**Comment by stephentoub** [comment]
> Do we close the issue?

Yes.  Thanks.
