### ISSUE TITLE
Non static System.Text.Json?

### ISSUE THREAD

**Issue by fgfmichael** [dotnet/corefx#42825]
Hi Team

I try to avoid usage of global/static code, however after looking over System.Text.Json it looks like all of the code is written with statics... Is there any way to use DI instead of accessing a global static (i.e. is there some interface I can inject into my services) OR will i need to wrap your serialize up into my own container class?

Really not a fan of globals...

**Comment by Clockwork-Muse** [comment]
... if you're talking about things like [`JsonDocument.Parse(...)`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsondocument.parse?view=netcore-3.1#System_Text_Json_JsonDocument_Parse_System_Buffers_ReadOnlySequence_System_Byte__System_Text_Json_JsonDocumentOptions_), they're factory methods.

This suggests that what you inject should be a reference to the function:

```csharp
using System.Text.Json;
using System.Buffers;

using JSONFactory = Func<ReadOnlySequence<byte>, JsonDocumentOptions, JsonDocument>;

public class SomethingNeedingJSON
{
    public JSONFactory JsonDocumentCreator { get; set; }
    public SomethingNeedingJSON(JSONFactory JsonDocumentCreator)
    {
        this.JsonDocumentCreator = JsonDocumentCreator;
    }
}
```

... which then can be injected like this:
```csharp
public static void Main(string[] args)
{
    var n = new SomethingNeedingJSON(JsonDocument.Parse);
}
```

So make the injected thing [a first-class function](https://en.wikipedia.org/wiki/First-class_function).

**Comment by fgfmichael** [comment]
Cheers
