### ISSUE TITLE
iso-22-cn is not supported encoding

### ISSUE THREAD

**Issue by AutismPatient** [dotnet/corefx#42844]
Response coding error:
![73285829-95116f80-4231-11ea-88de-96e8704d9ddb](https://user-images.githubusercontent.com/37021551/73288008-2b936000-4235-11ea-8e69-667595c62fba.png)

**Comment by stephentoub** [comment]
You're trying to use Chinese Simplified (ISO-2022)? Try using "x-cp50227" rather than "iso-22-cn".  On .NET Core, you'll need to call `Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);` first.

**Comment by AutismPatient** [comment]
@stephentoub Thank you for your answer
