### ISSUE TITLE
Make System.ComponentModel.TypeConverter available on generations < 5.4

### ISSUE THREAD

**Issue by grokys** [dotnet/corefx#4296]
I was just speaking to @davidfowl about the new [.NET Platform Generations](https://github.com/davidfowl/aspnetvnextwebapiapp/blob/master/Generations.md) and he suggested that it may be possible to get System.ComponentModel.TypeConverter on generations lower than 5.4. That would *really* help us over at [Perspex](https://github.com/Perspex/Perspex).

The only platform it's currently unavailable on is win8.

**Comment by davidfowl** [comment]
@joshfree no DNX related :smile:

**Comment by ericstj** [comment]
I'll take a look and see if we can do it.  The hard part for most of these isn't the implementation, but its dependencies.  Everything down the stack needs to be oob-able to net45.

**Comment by joshfree** [comment]
@davidfowl i'll rename the tag to "packaging" it if makes you feel better :-)

**Comment by ericstj** [comment]
Looks do-able.  All dependencies are supported back to Net4.5.  We'll need to produce a new façade for Nett 4.5.  Existing IL implementation can be used for win8/wp8/wpa81 after dialing back dependency versions.

**Comment by Maxwe11** [comment]
fixed by #4419 ?

**Comment by ericstj** [comment]
Yes, though you'll need to wait for the build tomorrow morning.

**Comment by ericstj** [comment]
Fixed.
