### ISSUE TITLE
Expression.Loop doesn't check against reference equal break and continue labels

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#4298]
Fails to compile with non-obvious error. Factory should likely check against this.

**Comment by JonHanna** [comment]
Do you mean the case where the target passed to break and/or continue doesn't match any jumped to within the body?

**Comment by bartdesmet** [comment]
var l = Expression.Label();
var b = Expression.Empty();
var e = Expression.Loop(b, l, l);
var f = Expression.Lambda(e);
f.Compile();

Sent from my Windows Phone
________________________________

**Comment by VSadov** [comment]
There could be some scenarios where a loop node of the described kind is introduced and rewritten later. We would be breaking such scenarios.
Considering that the issue should not be very common and that there are still numerous ways to create  trees that would not compile, I think we do not need to fix this.
