### ISSUE TITLE
BufferedStream should have a leaveOpen constructor

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#4299]
[Migrated issue https://github.com/dotnet/coreclr/issues/1825 on behalf of @redknightlois]

Currently the BufferedStream class doesnt have such a constructor, while there are many others that are intended to be chained like GZipStream do have it.

**Comment by karelz** [comment]
We need API proposal (should be simple).

**Comment by JeremyKuhne** [comment]
Triage: Closing due to low interest.
