### ISSUE TITLE
Registry tests fail from a non-admin build.cmd window

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#430]
Microsoft.Win32.Registry.Tests appear to require admin rights to pass.

This breaks the build.cmd workflow for everyone running non-elevated.  We should fix these tests to not require admin access to the box.

**Comment by Priya91** [comment]
The registry tests which write to the LocalMachine fail with securityexception. The LocalMachine registrykey needs to be changed to CurrentUser. And I dont think this change will introduce a test hole.
