### ISSUE TITLE
NetworkStream doesn't retrieve all the data for the SqlClient

### ISSUE THREAD

**Issue by saurabh500** [dotnet/corefx#4323]
Refer  https://github.com/dotnet/corefx/issues/4273

While using stream.ReadAsync to retrieve data, the stream returns 0 bytes when data is expected from the server. 
This problem occurs on Windows, Linux and OSX while running the entity framework tests at https://github.com/aspnet/EntityFramework

**Comment by davidsh** [comment]
cc: @CIPop @SidharthNabar

**Comment by CIPop** [comment]
As described this would happen by design when the remote endpoint gets shut down (FIN). The local endpoint can still send data but should not be able to receive anymore.
I will help investigate the issue based on the offline discussion.

**Comment by CIPop** [comment]
Given the data (ETW, Network traces) on the offline conversation I am closing this as "by design". 
See http://stackoverflow.com/questions/26740823/should-endreceive-ever-return-zero-if-the-socket-is-still-connected for an in-detail explanation.

**Comment by saurabh500** [comment]
@CIPop  Thanks for the comprehensive investigation.
