### ISSUE TITLE
[Documentation] Improve Tracing documentation

### ISSUE THREAD

**Issue by saurabh500** [dotnet/corefx#4325]
The documentation at https://github.com/dotnet/corefx/blob/master/Documentation/debugging/windows-instructions.md can be improved especially Traces > Using Perfview. 
It would be good to have a few screenshots showing how to configure PerfView for the consumers of CoreFx. 
PerfView may have its own documentation, however it would be nice to show what is needed for event collection in CoreFX.

**Comment by joshfree** [comment]
@brianrob @vancem @ianhays PTAL

**Comment by brianrob** [comment]
@CIPop, it looks like you added this documentation.  Can you help with this?

**Comment by CIPop** [comment]
This is very low on my list. I still think "up for grabs" is the correct marking.
@joshfree I don't understand the tag "performance": this document is about enabling Debug ETW traces.
