### ISSUE TITLE
Generate API docs grouped by .NET Platform Standard version from packages

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#4343]
The same way we generated this list:

https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md#list-of-net-corefx-apis-and-their-associated-net-standard-platform-version-tentative

It would be cool if we could generate an MSDN style API doc experience for the .NET Standard Platform versions.

/cc @ericstj  @richlander @Petermarcu

**Comment by davidfowl** [comment]
Some ideas for visualizations - http://caniuse.com/

**Comment by khellang** [comment]
@davidfowl Do you have the data for the generated list available anywhere? It would be cool if we as a community could try to come up with different ways of visualizing it. Play around with d3.js or something :smile:

**Comment by davidfowl** [comment]
> @davidfowl Do you have the data for the generated list available anywhere? It would be cool if we as a community could try to come up with different ways of visualizing it. Play around with d3.js or something :smile:

The packages are the data. We could go further and index on a per API basis like packagesearch does.

/cc @glennc

**Comment by ericstj** [comment]
I have the entire table encoded in the package source I just need to emit it in a friendly fashion.  I was thinking to do two things: emit to the package description as well as a separate data file.  Separate data file could be used to generate table in docs.

**Comment by blackdwarf** [comment]
@ericstj that would be **really cool**. +100000 to doing it.

**Comment by ericstj** [comment]
I'll make the packages emit a data file with supported platforms and pointers to the assemblies for that platform.   As a start I'll used this to generate the table.  I don't think I can tackle generating the API docs yet, but there will be a good structured input file for doing this.

**Comment by blackdwarf** [comment]
@ericstj is this something we could use docfx for? The API generation I mean?

**Comment by khellang** [comment]
This happened?
