### ISSUE TITLE
".NET Standard Platform" conventions are confusing to developers

### ISSUE THREAD

**Issue by advancedrei** [dotnet/corefx#4345]
Conceptually, the .NET Standard Platform (https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md) is a good idea. However, the devil is in the details, and the implementation parts that are exposed to developers will increase confusion, not decrease it. It was just made public a few minutes ago, and I'm already seeing confusion on Twitter about it: http://twitter.com/khellang/statuses/662310066733711360

This is a new concept, but having the "generation" versions be > currently shipping versions of .NET will just make people think you're working on another .NET framework release. It will exponentially increase confusion over PCLs, when the whole point of this plan is to decrease it.

I think you guys should change it back to .NET "Generations". and change the monikers to "gen1" thru "gen5". **This should bear no resemblance to how you reference specific platform versions today, even at a glance.** That way no aspect of it collides with current understanding of .NET Framework versions.

**Comment by davidfowl** [comment]
This is the feedback that we've heard and will consider. To be honest if naming is the only thing is that is causing confusing then that's a win. Naming is hard :smile: 

This PR is an attempt to explain the relationship between the standard and platforms:

https://github.com/dotnet/corefx/pull/4342

It didn't seem to click with some people immediately.

**Comment by davidfowl** [comment]
@advancedrei Ok we renamed it https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md.

dotnet5.x is now netstandard
