### ISSUE TITLE
SqlClient connection with "instance"

### ISSUE THREAD

**Issue by jamesgibbs100** [dotnet/corefx#4346]
If I establish a connection with SqlClient using the "server\instance" data source syntax this works fine on windows. On Linux it fails with a host resolution error.

If I monitor with Wireshark, I can see the DNS query being executed but it is searching for serverinstance - i.e. it concatenates the both the service and the instance into one host name - which then fails.

Is anyone else seeing this ?

**Comment by joshfree** [comment]
@corivera @saurabh500 @YoungGah

**Comment by saurabh500** [comment]
We don't support the instance name support on Linux yet.
As a work around please use the server name and the port name.

**Comment by joshfree** [comment]
> We don't support the instance name support on Linux yet.
> As a work around please use the server name and the port name. 

@saurabh500 could you get this added to the RC2 release notes (email @leecow)?

**Comment by saurabh500** [comment]
Cc @geleems

**Comment by geleems** [comment]
Fixed the issue: https://github.com/dotnet/corefx/pull/9606
