### ISSUE TITLE
Is new tooling required to support the standard platform TFMs with classic PCL?

### ISSUE THREAD

**Issue by tillig** [dotnet/corefx#4354]
I have a NuGet package targeting `dotnet5.2` that I've built and I'm trying to test that in conjunction with a standard VS 2015 Portable Class Library targeting Profile111.

```xml
<TargetFrameworkProfile>Profile111</TargetFrameworkProfile>
<TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
```

[Per the new documentation](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md), I gather this should work.

However, in trying it, I see the following error:

```
Could not install package 'Autofac 4.0.0-rc1-1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

Am I wrong? Is there a step I'm missing? Or is there an upcoming NuGet update that will make this possible?

**Comment by davidfowl** [comment]
@tillig Updated to doc pointing to the issue which has the remaining work. Mapping portable is one of those things.

**Comment by davidfowl** [comment]
Closing this as it isn't actionable right now. With the RC2 release, netstandard should work across the board
