### ISSUE TITLE
TCPClient.ReceiveTimeout should be in Milliseconds ?

### ISSUE THREAD

**Issue by kkurni** [dotnet/corefx#4357]
Based on MSDN TCPCleint.ReceiveTimeout should be in Millisecond.
https://msdn.microsoft.com/en-us/library/system.net.sockets.tcpclient.receivetimeout(v=vs.110).aspx

But when I read the code it said in second.
https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/TCPClient.cs#L328

Which one is correct ?

**Comment by kkurni** [comment]
CC @corivera @saurabh500

**Comment by davidsh** [comment]
The comment is probably wrong.

**Comment by davidsh** [comment]
@CIPop @pgavlin PTAL

**Comment by CIPop** [comment]
@davidsh +1: SO_RCVTIMEO is in milliseconds.

@kkurni Thanks for noticing this! Feel free to submit a PR to change the comments to say "milliseconds".
