### ISSUE TITLE
Refactor SNIHandle.ReceivePacket to use out instead of ref

### ISSUE THREAD

**Issue by kkurni** [dotnet/corefx#4368]
https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SNITcpHandle.cs#L269

I think we should refactor this to use "out" instead of ref.
As it can lead to confusion whether that Packet is always null or there may have initialized object.
Especially when the decision of releasing that packet.

If it designed to always null, then we should use "out" instead.

**Comment by kkurni** [comment]
CC @corivera @saurabh500

**Comment by saurabh500** [comment]
@corivera can you look at this and make a recommendation?

**Comment by corivera** [comment]
Since we're initializing the packet here every time, "out" would work better. And then there should also be a null check on the packet in "ReportErrorAndReleasePacket".

**Comment by saurabh500** [comment]
What about the MARShandle? Are we initializing the packet there as well?

**Comment by kkurni** [comment]
I have checked on MarsHandle as well, it also called with null packet.
but this packet would be reused using queue, but the caller won't pass any reference packet.

**Comment by saurabh500** [comment]
Sounds good.

**Comment by kkurni** [comment]
I can take this one since I am in codebase now.
