### ISSUE TITLE
Why GetRuntimeFields return non public field vs GetRuntimeField return public only flags ?

### ISSUE THREAD

**Issue by kkurni** [dotnet/corefx#4371]
Why GetRuntimeFields return non public field vs GetRuntimeField return public only flags ?

```
        public static IEnumerable<FieldInfo> GetRuntimeFields(this Type type)
        {
            return type.GetFields(defaultNonPublicFlags).AsNothingButIEnumerable();
        }

        public static FieldInfo GetRuntimeField(this Type type, String name)
        {
            return type.GetField(name, defaultPublicFlags);
        }
```

**Comment by weshaggard** [comment]
Can you provide a pointer to the code you copied in there?

cc @nguerrera

**Comment by kkurni** [comment]
hmm.. apparently the implementation is not exposed yet. 
...\src\System.Reflection.Extensions\System\Reflection\RuntimeReflectionExtensions.cs

which is reference here.
https://github.com/dotnet/corefx/blob/c02d33b18398199f6acc17d375dab154e9a1df66/src/System.Reflection.Extensions/ref/System.Reflection.Extensions.cs#L64

I checked .net46 has differnet implementation as well.
http://referencesource.microsoft.com/#mscorlib/system/reflection/RuntimeReflectionExtensions.cs

**Comment by nguerrera** [comment]
I'm afraid I don't have a good answer as I was not around for the design and implementation of RuntimeReflectionExtensions. I have wondered about this myself, but we can't change the existing behavior. For methods at least, the singular variant being public-only makes ambiguous match less likely, but it is still a very strange api design to have the singular and plural variants search different accessibility. :(

**Comment by AtsushiKan** [comment]
As noted, this is an odd design but we can't change it now.
