### ISSUE TITLE
DtdProcessing.Parse missing

### ISSUE THREAD

**Issue by alhimovich** [dotnet/corefx#4376]
Not sure if I am doing something wrong, but how do I access DtdProcessing.Parse enum value in corefx?
There seems to be a Parse static method as well now, so getting this compilation error:
```
DNXCore,Version=v5.0 error CS0428: Cannot convert method group 'Parse' to non-delegate type 'DtdProcessing'. Did you intend to invoke the method?
```
Any advice?

**Comment by joshfree** [comment]
@krwq @sepidehMS @piotrpMSFT PTAL

**Comment by krwq** [comment]
Hi @alhimovich,

this is currently intentionally not supported scenario. You can workaround this in some places for now by using:
```csharp
(DtdProcessing)2
```
(please see XmlSerializer code to see how they are currently doing that)

This is not guaranteed to work in the future. We are currently not sure if DTD will be supported same way in the future or through some different mechanism (it might be that we will make it public again too).

Please reopen if you have any feedback on this

**Comment by krwq** [comment]
I'm actually gonna reopen and leave it for future

**Comment by danmosemsft** [comment]
This is present now src\System.Private.Xml\src\System\Xml\Core\DtdProcessing.cs but not accessible by reference yet.

**Comment by sepidehMS** [comment]
I'm closing this against https://github.com/dotnet/corefx/issues/11888 as that will bring this back. I'm currently working on https://github.com/dotnet/corefx/issues/11888.
