### ISSUE TITLE
How do I submit a bug/PR against System.Web?

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/corefx#4377]
I see a problem in this source https://github.com/Microsoft/referencesource/blob/master/System.Web/HttpValueCollection.cs That repo is read-only. This repo simply omits that code. How do I submit a bug/PR against that code?

**Comment by davidfowl** [comment]
System.Web is not open source or a part of .NET Core. So you can't submit a PR for it.

**Comment by akoeplinger** [comment]
But you *can* submit a bug report for .NET Framework (which includes System.Web) on https://connect.microsoft.com/VisualStudio
