### ISSUE TITLE
RSA.Create() and ECDsa.Create() don't exist.

### ISSUE THREAD

**Issue by xanather** [dotnet/corefx#4378]
RSA.Create() and ECDsa.Create() don't exist for the System.Security.Cryptography.Algorithms package.

How am I supposed to use those algorithms with .NET Core?

Aes.Create() works fine.

This is for package version 4.0.0-beta-23409.

**Comment by PinpointTownes** [comment]
FYI, there's already a ticket for `RSA.Create()`: https://github.com/dotnet/corefx/issues/2953 :smile:

**Comment by xanather** [comment]
Nice thanks, will close this one then.
