### ISSUE TITLE
Test baseline is wrong

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#4388]
We need to investigate the bits that we use for testing in corefx and for CI.  Today each test decides which dependencies are live (via ProjectReferences) or baseline (via packages).  Additionally the baseline is only updated periodically.

This can lead us to a place where folks commit bits that might work independently by not together.

For TOF, internally, folks are solving this by always using a fixed set of packages after they are produced by the build.  In CoreFx we don't yet build the packages in build, so we have the [TestWithLocalLibraries](https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets#L75) property, but I don't know if this is used in CI or local dev builds.  Also I don't think this will currently work for linux/OS due to the assumed DLL pattern.

Finally it looks to me like our RC builds are still pulling packages from the [master feed](https://github.com/dotnet/corefx/blob/release/1.0.0-rc1/dir.props#L77).

/cc @joshfree @weshaggard

**Comment by davidsh** [comment]
I definitely think that 'msbuild' should be using `/p:TestWithLocalLibraries=true` on the CI machines if it isn't already.

**Comment by weshaggard** [comment]
cc @Chrisboh 

I agree there is some workflows to be figured out but I don't think we should be blindly using TestWithLocalLibraries all the time in CI or local dev workflow. I do believe we should have at least one test run for our repo that is running with the latest, and currently I believe our code coverage runs do this. 

I hope that this is more of a point in time issue as we are still in pre-release mode with a lot of our packages but over time most of our libraries should reference stable packages and they should by default run their tests on those packages.

**Comment by ellismg** [comment]
FWIW, outer-loop runs with `/p:TestWithLocalLibraries=true`.

**Comment by ericstj** [comment]
> should by default run their tests on those packages. 

I don't believe this is happening today due to how the test-runtime copies over everything.

**Comment by weshaggard** [comment]
We now update the package references holistically across the repo and we also are now using a project reference to test-runtime (thanks @mellinoe ) so I think we have covered what we you were looking for here @ericstj. If there is something else missing please feel free to reactivate.
