### ISSUE TITLE
Add version information to FrameworkDescription.

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#4391]
What version string is expected for .NET Framework, .NET Core and .NET Native.

+PM @terrajobst on providing insight with marketing names.

cc @weshaggard 
cc @gkhanna79 To provide insight on runtime side.
@davidfowl Please provide more data on how useful knowing version of framework is, and what you expect for the 3 different framework stacks.

**Comment by weshaggard** [comment]
For this I actually think @mellinoe suggestion in the PR is a good one.

>The AssemblyFileVersion of the core assembly ( typeof(Object).GetTypeInfo().Assembly)) could be an okay indicator of the "runtime version", I think. It doesn't make sense to me to base it off the version of this assembly, it's not in any way tied to any particular runtime.

**Comment by davidfowl** [comment]
+1

**Comment by Priya91** [comment]
Added with #5210
