### ISSUE TITLE
ResourceManager gets incorrect lineending from .resx in Windows 10 Universal App

### ISSUE THREAD

**Issue by Belorus** [dotnet/corefx#4399]
If i create resx with 2-line string and get it via ResourceManager - i get only \n instead of \r\n (Environment.NewLine is \r\n)

.resx file is in PCL that is referenced from UWP project.

Visual Studio 2015 Update 1
Testing on Desktop Windows 10

**Comment by gkhanna79** [comment]
@joshfree Why is this bug marked for RC2? It sounds like a UWP issue.

**Comment by gkhanna79** [comment]
I am asking to understand if you had a good reason to assign it to RC2 that I am unaware of :)

**Comment by Belorus** [comment]
From app perspective this is important. Line breaks are not  rendered correctly in our game. If there is a workaround - please note it here. 

Or should i create this issue in another tracker ?

**Comment by gkhanna79** [comment]
We will use this issue to track the fix for UWP - no need to have another issue :)

**Comment by Belorus** [comment]
Hi!
Any progress on this issue? 

It doesn't seem difficult to fix (i'd do myself if ResourceManager code was in public repo)

**Comment by ramarag** [comment]
Hi belorus, I will try to look into this some time next week.

But you are welcome to contribute a fix, The ResourceManager code live in [src/mscorlib/src/System/Resources/ResourceManager.cs](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Resources/ResourceManager.cs)

**Comment by ramarag** [comment]
@Belorus can you attach a repro and steps so that there are no misunderstanding ?

**Comment by ramarag** [comment]
@Belorus  and can you also share the resx and PCL

**Comment by ramarag** [comment]
Closing this for now as not repro open this back if it becomes actionable
