### ISSUE TITLE
String.IsNullOrX()

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#4409]
Currently we have the function `String.IsNullOrEmpty(string)` as well as `String.IsNullOrWhitespace(string)`

It would be useful to add a public API that lets a user check if a string is null or a single character. Building on this, an API could be added to check if a non-null string is made of a single character.

It could look something like this:

```csharp

public class String 
{
    //...
    public static bool IsNullOrCharacter(string value, char c) { }
    public bool IsOnlyCharacter(char c) { }
}

```

I'm not very happy with the naming of these APIs, but this fleshes out an idea for consideration

**Comment by tpetrina** [comment]
I think this is much better suited to be an extension method as the usage for this is quite low. Besides, you can do it in one if: `if (!string.IsNullOrEmpty(s) && s[0] == 'c')`.

**Comment by hughbe** [comment]
Im not sure that would do the job, as the API I propose would check if the string is *only* made from that character

For example string.IsNullOrCharacter('a') would work as follows

Input -> Output
null -> true
"a" -> true
"aaaaa" -> true
"aaaab"->false

**Comment by Maxwe11** [comment]
>IsNullOrCharacter

For me it sounds like string should be null or have length of one character

**Comment by hughbe** [comment]
@maxwe11 my reasoning behind this is that string.IsNullOrWhitespace doesn't really behave like this - a string with any number of spaces/tabs etc. Would produce a true output

**Comment by NickCraver** [comment]
Whitespace refers to any length of whitespace though - that's not confusing. Character is very specific :)

FWIW, I agree these should remain extension methods - aside from character prompts in console applications (y/n style), I can't think of common use cases across the platform.

Of course, I'm still waiting for the `string.HasValue()` and `string.IsNullOrEmpty()` *extension* methods that so many people copy to each project to be built in :)

**Comment by KrzysztofCwalina** [comment]
Yeah, this seems like too specialized API to be added to String or even BCL in general.
