### ISSUE TITLE
AppContext needs a WinRT (netcore50) specific implementation

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#4432]
BaseDirectory should return AppData.LocaFolder so that EF doesn't have to reflect like so https://github.com/aspnet/Microsoft.Data.Sqlite/commit/db0b8156fd174b5dcd910deccb491cc48fd9151d#diff-a1357e13d2db00bd1204d8f3ca36c59fR132

/cc @ericstj @weshaggard @natemcmaster

**Comment by natemcmaster** [comment]
:+1:

**Comment by natemcmaster** [comment]
Also, we need `AppData.TemporaryFolder` too. 

We currently have to use reflection and the DLR to get LocalFolder.
```c#
var appDataType = Type.GetType("Windows.Storage.ApplicationData, Windows, ContentType=WindowsRuntime", throwOnError: false);
var appData = (dynamic)appDataType?.GetTypeInfo()
                    .GetDeclaredProperty("Current").GetMethod.Invoke(null, null)

var basePath = appData.LocalFolder.Path;
```

**Comment by davidfowl** [comment]
Doesn't Path.GetTempPath()

**Comment by natemcmaster** [comment]
I'm not sure what the guidance is anymore for which TempPath api UWP apps should use. Path.GetTempPath() was not originally available in WinRT. Although it is now supported, it does not return the same path as AppData.TempFolder

![image](https://cloud.githubusercontent.com/assets/2696087/11071344/40f006c4-8795-11e5-9f4c-b8fa8026a64e.png)

**Comment by weshaggard** [comment]
For Temp yes please use Path.GetTempPath() and if for some reason that isn't correct we should fix it there we don't need another API for that.

As for BaseDirectory we already have a netcore50 specific version of System.AppContext.dll (it isn't on GitHub yet) and it currently returns Windows.ApplicationModel.Package.Current.InstalledLocation.Path. Which is the root of the application which is what BaseDirectory is supposed to be about. If there is a need for AppData that is a different request and we should consider.

@AlexGhiondea please have a look and figure out what we need here.

**Comment by ericstj** [comment]
Aside: Also, I'd like to caution the use of assumed root paths in a portable library.  It is very difficult for portable code to get the right assumption that will work everywhere.  Even different app models using the same framework often have a different preference for where data is stored (consider web vs client on desktop).  Usually it is better to expose the root as an API from the portable library.  It also has the nice characteristic of not putting a trust boundary in the framework code.

**Comment by ericstj** [comment]
Removing packaging tag.  This is an implementation discussion around AppContext.

**Comment by AlexGhiondea** [comment]
I remember we decided long ago that we are ok with the current state of AppContext. If I am remembering this wrong, please re-open.
