### ISSUE TITLE
Mars - Intermittently Failed - Causing Timeout

### ISSUE THREAD

**Issue by kkurni** [dotnet/corefx#4438]
Repro 
```
 using (var conn = new SqlConnection("Data Source=***; User ID=***; Password=***;Initial Catalog=***;MultipleActiveResultSets=true;"))
                {
                    conn.Open();
                    var cmdText = "select 1";
                    var cmd1 = new SqlCommand(cmdText, conn);
                    var cmd2 = new SqlCommand(cmdText, conn);

                    Console.WriteLine("{0:hh:mm:ss} - Execute Reader 1", DateTime.Now);
                    using (var reader1 = cmd1.ExecuteReader())
                    {
                        Console.WriteLine("{0:hh:mm:ss} - Execute Reader 2", DateTime.Now);
                        using (var reader2 = cmd2.ExecuteReader())
                        {
                            Console.WriteLine("{0:hh:mm:ss} - Start Read Reader 2", DateTime.Now);
                            reader2.Read();
                            Console.WriteLine("{0:hh:mm:ss} - Finish Read Reader 2", DateTime.Now);

                        }
                        Console.WriteLine("{0:hh:mm:ss} - Start Read Reader 1", DateTime.Now);
                        reader1.Read();
                        Console.WriteLine("{0:hh:mm:ss} - Finish Read Reader 1", DateTime.Now);
                    }
                }
```

results :
01:01:19 - Execute Reader 1
01:01:19 - Execute Reader 2
01:01:49 - ERROR : System.Data.SqlClient.SqlException: Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.

**Comment by kkurni** [comment]
https://gist.github.com/kkurni/35f4309aba1fb55d41b3

**Comment by kkurni** [comment]
CC: @corivera @saurabh500

**Comment by kkurni** [comment]
The timeout only happen in debug mode.
This was caused by Debug.Assert is throwing Exception instead of opening debugger.

We don't exception well which causing this to timeout.
https://github.com/dotnet/corefx/blob/a3050bacc9b716f52f086751bfb4bf0384019f53/src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SNIMarsConnection.cs#L131-L138


Debug Assert was failed because we blindly handle error for every session, even if that session is not error.

We need to indentify the called so that we can call HandleReceiveError to particular session.

**Comment by saurabh500** [comment]
@kkurni has created the following pull request which address the problem

https://github.com/dotnet/corefx/pull/4486

**Comment by saurabh500** [comment]
@kkurni  are you going to fix the Assert for this issue ?

**Comment by kkurni** [comment]
probably, yes 1 only for this assert packet should be allow to be null.
https://github.com/dotnet/corefx/blob/1d9edc6f2da2c9cedf1e1c700fe88d3fe3299d91/src/System.Data.SqlClient/src/System/Data/SqlClient/TdsParserStateObject.cs#L2900

other asserts, I think it is there for a reason.
So I think it is best to handle this error properly by target this per session id if possible

Need to understand a bit more.

**Comment by kkurni** [comment]
I am closing this issue as we already have a fix in https://github.com/dotnet/corefx/pull/4486
This assert does not have any problem anymore. Will raise another issue if that assert become issue in the future.
