### ISSUE TITLE
Add Convert.ToHexString / FromHexString

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/corefx#4441]
This would complement `Convert.ToBase64String` / `Convert.FromBase64String`. You all know you've written this API over and over again in your projects. :)

**Comment by davidfowl** [comment]
+1

**Comment by Maxwe11** [comment]
seems #1647 related

**Comment by CodesInChaos** [comment]
I think we should put each encoding (hex, base64, etc) in its own class. Either as subclass of `System.Text.Encoding` or, since they're a bit different in nature a new `BinaryEncoding` class.

**Comment by AlexGhiondea** [comment]
Let's track this work with issue https://github.com/dotnet/corefx/issues/10013.
