### ISSUE TITLE
LastAccessTime throws on Linux for non-existent files on CoreCLR

### ISSUE THREAD

**Issue by ValMenn** [dotnet/corefx#4442]
LastAccessTime for non-existent file must return 1/1/1601 12:00:00 AM. It does so on Windows. Throws on Linux. Below program assumes file "haha" does not exist.
```
using System;
using System.IO;
namespace nonExistent
{
    public class Program
    {
        public void Main(string[] args)
        {
            FileInfo i = new FileInfo("haha");
            Console.WriteLine(i.LastAccessTimeUtc);
        }
    }
}
```

**Comment by stephentoub** [comment]
Known difference: https://github.com/dotnet/corefx/issues/1728

**Comment by ValMenn** [comment]
Hmm. MSDN specifies the behavior exactly, so the argument "it does not make sense" does not seem relevant. Oh well.

**Comment by stephentoub** [comment]
cc: @ianhays

**Comment by ianhays** [comment]
It was a close decision, @ValMenn. This was an issue that the design discussion team was split on, so I opted for the option with more "votes". 

The primary argument against having it return FromFileTime(0) is that Unix doesn't have the notion of FromFileTime like Windows does; Unix 0 time is in 1970, not 1601. So which do we return for a nonexistent file? Do we return the posix 0 time or do we return the Windows 0 time? The argument was that returning a Windows 0 time "doesn't make sense" for a Unix system and returning the Unix 0 time still breaks cross-compat and is therefore no better than throwing.

I'm not against revisiting the decision in https://github.com/dotnet/corefx/issues/1728. There's certainly a benefit to matching Unix and Windows behaviors when possible. However, I'm wary of porting a Windows-specific number like this and potentially isolating Unix devs.

**Comment by ianhays** [comment]
Closing this as repeat of #1728.
