### ISSUE TITLE
Update System.Text.Encodings.Web to Unicode 8

### ISSUE THREAD

**Issue by Eilon** [dotnet/corefx#4443]
When HttpAbstractions issue https://github.com/aspnet/HttpAbstractions/issues/391 was resolved it switched to using the encoders in the CoreFX repo. The encoders in the aspnet org already had support for Unicode 8.0, which is not yet available in the CoreFX repo.

**Comment by GrabYourPitchforks** [comment]
See in particular the commit https://github.com/aspnet/HttpAbstractions/commit/43d0b0f65bb5abe453d5d54fec6d67c1c93f3fa8, where the support was officially added. That commit also includes a readme file detailing how to update the mapping to support future Unicode versions.

**Comment by tarekgh** [comment]
This is fixed by the inked PR #4549
