### ISSUE TITLE
Consolidate several cross-platform packages

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4446]
System.IO.FileSystem, System.Net.Sockets, and System.Security.Cryptography.Algorithms used to have different builds for OS X and Linux, but now after all the shimming work that was done recently, those were consolidated into a single Unix build, with no differences between Linux and OS X.  However, they still have Linux-specific and OSX-specific packages.  Those can be consolidated now, as well.

**Comment by chcosta** [comment]
A fix for this has been checked in and will be in tomorrow's packages.
