### ISSUE TITLE
Remove Managed Inflator and Deflator code in System.IO.Compression

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefx#4451]
With #4440 we no longer need the managed compression code as we are always using a native compression implementation. The managed code is now dead and can't be hit by a user.

We should remove this code.

**Comment by ianhays** [comment]
What about on Unix systems that don't have libz installed? I'm not sure that there are any (particularly that we support). Think you mentioned this in your PR.

**Comment by eerhardt** [comment]
libz is available on all of our supported Unix platforms - OSX, Ubuntu and CentOS. It also appears to be [available on FreeBSD](http://www.unix.com/man-page/FreeBSD/3/zlib/).

So, we currently have no plans for supporting Unix systems that don't have libz installed. We might as well not be dragging around this dead managed code in case we happen to find one.

Also, we have hard dependencies on other native libraries: libcurl, openSSL, icu, etc. Why should this one be different?

**Comment by ianhays** [comment]
Agreed. I'd like to see the old managed implementation removed as well and I think we're at a good point to move away from them.
