### ISSUE TITLE
_gcHandle usage ?

### ISSUE THREAD

**Issue by kkurni** [dotnet/corefx#4454]
https://github.com/dotnet/corefx/blob/1d9edc6f2da2c9cedf1e1c700fe88d3fe3299d91/src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SNIProxy.cs

It seems there is no one allocated this _gcHandle.

This path will always false
https://github.com/dotnet/corefx/blob/1d9edc6f2da2c9cedf1e1c700fe88d3fe3299d91/src/System.Data.SqlClient/src/System/Data/SqlClient/TdsParserStateObject.cs#L902

Can we remove this ?

**Comment by kkurni** [comment]
CC @corivera @saurabh500

**Comment by saurabh500** [comment]
Looks unused. 
@corivera was it in there only to have parity with Native? Or do we intend to use this?

**Comment by corivera** [comment]
This can be removed. In Native code, GCHandle is used to store a reference to TdsParserStateObject that is passed into native Read/Write callback functions that call back into managed code. Then once we're in managed code we call ReadAsyncCallback/WriteAsyncCallback for TdsParserStateObject.

It's just a native/managed code intercommunication thing, so we can get rid of GCHandle in our managed-only code.

**Comment by corivera** [comment]
Check out ReadDispatcher or WriteDispatcher in TdsParserSafeHandles to see what I'm talking about.
