### ISSUE TITLE
Expose System.Reflection.TargetException

### ISSUE THREAD

**Issue by jonorossi** [dotnet/corefx#4463]
.NET Framework exposed both `TargetException` (fail on an invalid target, e.g, null) and `TargetInvocationException` (fail actually invoking the target). The runtime still throws a `TargetException` in coreclr and there is code in the corefx unit tests that check the exception is thrown using `Type.FullName` or `Assert.ThrowsAny<Exception>`.

Is there a reason this exception hasn't been exposed? I'm porting code checking for this exception.

**Comment by joshfree** [comment]
@terrajobst @weshaggard PTAL

**Comment by weshaggard** [comment]
@pallavit this is something we should consider exposing.

**Comment by pallavit** [comment]
Closing this with #5381
