### ISSUE TITLE
TestUserCredentialsPropertiesOnWindows failed in CI in outer loop

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4466]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_outerloop_windows_win10_debug/88/console
```
03:38:50      System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows [FAIL]
03:38:50         System.InvalidOperationException : No process is associated with this object.
03:38:50         Stack Trace:
03:38:50            d:\j\workspace\dotnet_corefx_outerloop_windows_win10_debug\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs(753,0): at System.Diagnostics.Process.EnsureState(State state)
03:38:50            d:\j\workspace\dotnet_corefx_outerloop_windows_win10_debug\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs(172,0): at System.Diagnostics.Process.get_HasExited()
03:38:50            d:\j\workspace\dotnet_corefx_outerloop_windows_win10_debug\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs(325,0): at System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows()
```

**Comment by pallavit** [comment]
Can't repro the issue, so closing this opportunistically, Please reopen if you see this failing again.

**Comment by stephentoub** [comment]
@pallavit, it failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win10_debug/55/consoleFull
```
07:13:36      System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows [FAIL]
07:13:36         System.InvalidOperationException : No process is associated with this object.
07:13:36         Stack Trace:
07:13:36            d:\j\workspace\dotnet_corefx\outerloop_win10_debug\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs(753,0): at System.Diagnostics.Process.EnsureState(State state)
07:13:36            d:\j\workspace\dotnet_corefx\outerloop_win10_debug\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs(172,0): at System.Diagnostics.Process.get_HasExited()
07:13:36            d:\j\workspace\dotnet_corefx\outerloop_win10_debug\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs(361,0): at System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows()
```

**Comment by pallavit** [comment]
@stephentoub Hmm.. i will take a closer look. Thanks.

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win10_release/146/consoleFull

**Comment by stephentoub** [comment]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win10_release/151/consoleFull

**Comment by bartonjs** [comment]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_release_prtest/1/

**Comment by joshfree** [comment]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_release/lastCompletedBuild/testReport/System.Diagnostics.Tests/ProcessStartInfoTests/TestUserCredentialsPropertiesOnWindows/

Stacktrace
MESSAGE:
System.InvalidOperationException : No process is associated with this object.
+++++++++++++++++++
STACK TRACE:
at System.Diagnostics.Process.EnsureState(State state) in D:\j\workspace\outerloop_win---65ef7d78\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs:line 779 at System.Diagnostics.Process.get_HasExited() in D:\j\workspace\outerloop_win---65ef7d78\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs:line 189 at System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows() in D:\j\workspace\outerloop_win---65ef7d78\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs:line 393

**Comment by stephentoub** [comment]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug/27/

**Comment by Priya91** [comment]
The access denied error from the native call doesn't repro anymore. Could have been because of permissions linked to folders in test, and maybe this changed with netstandard folder structure change. Closing this.
