### ISSUE TITLE
WinHTTP certificate chain build algorithm is potentially not including certificates obtained from the TLS connection

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#4473]
Similarly to how SslStream is including TLS certificates obtained from Schannel, WinHTTP should use the `PCERT_CONTEXT` obtained using `WINHTTP_OPTION_SERVER_CERT_CONTEXT` to extract certificates from the virtual store and use them during chain construction.

See https://github.com/dotnet/corefx/blob/master/src/Common/src/Interop/Windows/SChannel/UnmanagedCertificateContext.cs for reference.

**Comment by CIPop** [comment]
@vijaykota Please verify if this applies to CurlHandler as well.

**Comment by vijaykota** [comment]
Chain validation for CurlHandler was fixed in https://github.com/dotnet/corefx/pull/4121

**Comment by CIPop** [comment]
Closing as a duplicate of #3891.

/cc @davidsh @stephentoub.

**Comment by davidsh** [comment]
This is not a duplicate of #3891.  It requires different code.   This issue is about validation server certificates.

#3891 is about validating client certificates.
