### ISSUE TITLE
Debug.Assert throws System.Diagnostics.Debug+DebugAssertException

### ISSUE THREAD

**Issue by kkurni** [dotnet/corefx#4474]
Is this by designed for corefx ?
because in .net, this should open a debugger instead.

Our code currently depends a lot on Debug.Assert.
Unfortunately Debug.Assert now throws Debug+DebugAssertException which causing inconsistent from the release mode

I remember previously it throws a special uncatchable exception (Environment.FailFast()) which i think can be better instead of causing different behavior.

**Comment by kkurni** [comment]
CC @corivera @saurabh500

**Comment by stephentoub** [comment]
> Is this by designed for corefx ?

It's by design, at least for now.  Environment.FailFast() was incredibly difficult to debug/diagnose when in remote environments, like in CI. This was changed a few weeks ago.
cc: @davidsh, @weshaggard, @ellismg 

> because in .net, this should open a debugger instead.

https://github.com/dotnet/corefx/issues/3708

**Comment by weshaggard** [comment]
Correct this is by design, in CoreCLR it never opened a debugger it simply crashed. If you have a debugger attached it will still break. In general however Debug.Assert should only be used for things that should never fail. 

Given that is by design I'm closing this issue.
