### ISSUE TITLE
Change ZLib Optimal CompressionLevel on Unix

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefx#4475]
We currently have this comment and code in System.IO.Compression:

```C#
  // Note that ZLib currently exactly correspond to the optimal values.
  // However, we have determined the optimal values by intependent measurements across
  // a range of all possible ZLib parameters and over a set of different data.
  // We stress that by using explicitly the values obtained by the measurements rather than
  // ZLib defaults even if they happened to be the same.
  // For ZLib 1.2.3 we have (copied from ZLibNative.cs):
  // ZLibNative.CompressionLevel.DefaultCompression = 6;
  // ZLibNative.Deflate_DefaultWindowBits = -15;
  // ZLibNative.Deflate_DefaultMemLevel = 8;

  case CompressionLevel.Optimal:
      zlibCompressionLevel = (ZLibNative.CompressionLevel)6;
      windowBits = -15;
      memLevel = 8;
      strategy = ZLibNative.CompressionStrategy.DefaultStrategy;
      break;
```

Since we are now using the “current” ZLib version on Unix, and because we are planning on changing which version we use on Windows, I don’t think this is the best approach anymore. It was probably correct when we were hard-coding a version, but since we don’t know which version will actually be used, I think we should be letting the zlib library figure out which is the best compression level to use.

I have 2 separate options on how to address this:
1. On Unix, create a new shim method DeflateInit that only takes in the ZStream. The shim code will use the default values from the ZLib headers. Windows remains unchanged.
https://github.com/eerhardt/corefx/commit/c1be54d6dfaf64098b42c186c041344e4378f083
2. Change both Windows and Unix code to always use the default compression level (-1) and let the zlib version pick.
https://github.com/eerhardt/corefx/commit/38883e3df53153a9434dfc16696667279b18dd82

@ianhays @stephentoub - Do you guys agree this should be fixed? If so, do you have a preferred option - or an even better option than the 2 I've listed?

**Comment by stephentoub** [comment]
I'm probably just missing a step as I've not looking through all that option-setting code in a while.

But zlib exposes a scale from fastest to best compression, with defined constants for the limits:
```C
#define Z_NO_COMPRESSION         0
#define Z_BEST_SPEED             1
#define Z_BEST_COMPRESSION       9
#define Z_DEFAULT_COMPRESSION  (-1)
```
and in System.IO.Compression we have the CompressionLevel enum:
```C#
public enum CompressionLevel
{
    Optimal = 0,
    Fastest = 1,
    NoCompression = 2
}
```

Why wouldn't we just map:
- CompressionLevel.Optimal => Z_BEST_COMPRESSION
- CompressionLevel.Fastest => Z_BEST_SPEED
- CompressionLevel.NoCompression => Z_NO_COMPRESSION
?

Based on the documented meaning of the .NET enum values and the zlib constants, those would appear to be an exact match.

Or am I totally misunderstanding?

**Comment by ianhays** [comment]
@stephentoub looks right to me. Though CompressionLevel.Optimal should be set to Z_DEFAULT_COMPRESSION instead of Z_BEST_COMPRESSION.

**Comment by eerhardt** [comment]
I think you are missing the [other comment on ZLibNative.CompressionLevel](https://github.com/dotnet/corefx/blob/master/src/System.IO.Compression/src/System/IO/Compression/ZLibNative.cs#L42-L85).

Here are the highlights:
```C#
        /// <code>CompressionLevel.DefaultCompression</code> = -1 requests a default compromise between speed and compression
        /// (currently equivalent to level 6).</p>
...
        ///   <li><code>CompressionLevel</code> values over 6 do not significantly improve the compression rate,
        ///       however such values require additional compression time.</li>
        ///   <li>Thus it is not recommended to use a compression level higher than 6, including the
        ///       value <code>CompressionLevel.BestCompression</code>.</li>
        ///   <li>The optimal compression performance (time/rate ratio) tends to occur at compression level 6
        ///       (<code>CompressionLevel.DefaultCompression</code>).</li>

```

What I am proposing is a slightly different map than what you have:
- CompressionLevel.Optimal => **Z_DEFAULT_COMPRESSION**
- CompressionLevel.Fastest => Z_BEST_SPEED
- CompressionLevel.NoCompression => Z_NO_COMPRESSION

**Comment by stephentoub** [comment]
> Though CompressionLevel.Optimal should be set to Z_DEFAULT_COMPRESSION instead of Z_BEST_COMPRESSION

Why?

**Comment by stephentoub** [comment]
> Here are the highlights

Where does that text come from, i.e. is it from zlib docs somewhere or was it written by a dev who worked on System.IO.Compression?  I see no mention of "it is not recommended to use a compression level higher than 6" in the zlib docs... am I just missing it?

**Comment by stephentoub** [comment]
Regardless, I agree we should map the .NET enum values to the corresponding zlib values.  Then it's just a matter of what we choose for "optimal compression".

**Comment by ianhays** [comment]
The msdn docs for Optimal do say ```The compression operation should be optimally compressed, even if the operation takes a longer time to complete.``` which directly conflicts with the comments on CompressionLevel stating that it isn't worth the extra compression time.

The comments for CompressionLevel may be outdated with regards to the usefulness of the higher compression level.

If we do set it to Z_BEST_COMPRESSION then we no longer have a good "middle-ground" compression level: we can only choose between no compression, fast compression, or best compression.

**Comment by eerhardt** [comment]
> Where does that text come from, i.e. is it from zlib docs somewhere or was it written by a dev who worked on System.IO.Compression?

I assume it came from our internal devs, and not from zlib.

The furthest back I could trace it was to @tarekgh in this changeset:
764226	add	Tarek Mahmoud Sayed	9/20/2012 6:00:22 PM	$/DevDiv/OffCycle11/Redhawk/V2/ProjectN/FX/src/System.IO.Compression/System/IO/Compression/ZLibNative.cs	Initial porting for System.IO.Compression This checkin enable DeflateStream class and use the managed library for deflat...

I'm sure it came from earlier, but I don't know where the earlier code was...

**Comment by eerhardt** [comment]
> If we do set it to Z_BEST_COMPRESSION then we no longer have a good "middle-ground" compression level: we can only choose between no compression, fast compression, or best compression.

Does that imply that we need a new enum value?

**Comment by stephentoub** [comment]
> Does that imply that we need a new enum value?

Maybe not.  The docs also state that you get Optimal when you don't specify a level, but the enum value choice isn't to my knowledge actually exposed anywhere, so what this really means is you get the compromise by default between speed/compression.  We could make it so that if you don't specify a level, you get Z_DEFAULT_COMPRESSION, and if you do specify a level, then you're doing so because you want to change it to either best speed, best compression, or no compression, and we honor that.

Just a suggestion.  There may be gotchas I'm not considering.

**Comment by ianhays** [comment]
>Does that imply that we need a new enum value?

That's what I was getting at, yeah. It's a bit odd to me that we don't currently have a "default" compression level that is a middle-ground between speed and best.

>We could make it so that if you don't specify a level, you get Z_DEFAULT_COMPRESSION, and if you do specify a level, then you're doing so because you want to change it to either best speed, best compression, or no compression, and we honor that.

This is good with me, too. Since calling a function with CompressionLevel.Default would be the same as calling a function without a specified CompressionLevel, I can see us leaving out the CompressionLevel.Default definition. My gut reaction is that including Default in the enum is the better choice since it allows Default to be passed around more easily, but I don't have a good example where this would be useful.

**Comment by stephentoub** [comment]
>  My gut reaction is that including Default in the enum is the better choice

Yes, we would want to make it available eventually, I just meant to imply that we wouldn't need to block on it.

**Comment by eerhardt** [comment]
Since the enum is already defined like this:
```C#
 public enum CompressionLevel
 {
     Optimal = 0,
     Fastest = 1,
     NoCompression = 2
 } 
```
It would feel wrong to have either:
Default = -1
or
Default = 3.

I think it is good practice to have the "default" enum value be the same as default(T) would give you.

I think long term it would be better if we added a new value "BestCompression = 3", and changed the MSDN docs. IMO, the docs are and have been incorrect since the code has been using the value "6" since at least 2012.

**Comment by ianhays** [comment]
Instead of adding BestCompression and making it 3, why not just make Optimal=3?

**Comment by tarekgh** [comment]
> Where does that text come from originally, i.e. is it from zlib docs somewhere and copied into our .cs files, or was it written by a dev who worked on System.IO.Compression?

I believe this is originally came from the dev who worked on System.IO.Compression (Greg Paperin).

I think the original proposal of @stephentoub still make sense to me even if the comments on the code contradict

•CompressionLevel.Optimal => Z_BEST_COMPRESSION
•CompressionLevel.Fastest => Z_BEST_SPEED
•CompressionLevel.NoCompression => Z_NO_COMPRESSION

this will match the original intend and will make the doc is right again

**Comment by joshfree** [comment]
@tarekgh is correct.  This comment was from the original System.IO.Compression work on Windows.  Greg spent about a week of machine time trying various combinations and various input data to determine those settings.

**Comment by joshfree** [comment]
To be clear I also agree that we should snap back to the zlib defaults as part of upgrading to the latest version.

**Comment by eerhardt** [comment]
I really don't think our 'Optimal' ('0' - the default) setting should equal Z_BEST_COMPRESSION (i.e. '9').

ZLib's default is -1, which currently translates to '6' according to the zlib.h file. The comments in our code indicate that 6 is the best tradeoff between speed and compression, and that "values over 6 do not significantly improve the compression rate, however such values require additional compression time".

Both of these things indicate to me that our 'Optimal' 0 value should map to Z_DEFAULT_COMPRESSION.  And if we want to expose a value that gives the absolute most compressed data, we should add a new enum value for it.

To answer @ianhays:
> Instead of adding BestCompression and making it 3, why not just make Optimal=3?

This would break compatibility with the desktop framework. In general, changing enum values are a binary breaking change.

**Comment by tarekgh** [comment]
if we ignore what are the values in zlib or in the framework, the way I understand it is CompressionLevel.Optimal really means the best compression. and we chose originally to have this as the default value. if you agree with me, we'll just need to map this value to whatever correspond in zlib

**Comment by ianhays** [comment]
>This would break compatibility with the desktop framework. In general, changing enum values are a binary breaking change.

Gotcha. Seems to me like it would just use the older value (i.e. 0) for Optimal and not actually break but just use a different CompressionLevel than intended.

In that case, I prefer what Steve mentioned earlier about having CompressionLevel.Optimal map to Z_BEST_COMPRESSION. But if no CompressionLevel is specified, use Z_DEFAULT_COMPRESSION.

**Comment by eerhardt** [comment]
My main reasons for preferring to keep CompressionLevel.Optimal to mean "best time/rate ratio" (Z_DEFAULT_COMPRESSION):

1. It follows the [design guidelines](https://msdn.microsoft.com/en-US/library/ms182149(v=vs.80).aspx): "assign zero to the most commonly used member".  I think the Z_DEFAULT_COMPRESSION value should be used in most situations.
2. It is what was currently implemented, and appears to be working just fine for people.
3. According to the comment in the code, values above "6" don't give you significantly better compression for the time taken.
4. We only have 3 public enum values now. If we chose Optimal to be Z_BEST_COMPRESSION, then we wouldn't have an enum value for the most preferred value, which would be unfortunate.
5. Using a value in the overload that isn't available in the enum would be confusing to users.

**Comment by bjjones** [comment]
I’m a little confused by this discussion. It seems like the general agreement is that it should be defaulting to compression level 6, however it doesn’t look like the code reflects this. 

In the Deflater.cs, constructor defaults to CompressionLevel.Optimal
```
internal Deflater() : this(CompressionLevel.Optimal)
{
}
```
In case of CompressionLevel.Optimal, zlibCompressionLevel is set to BestCompression
```
case CompressionLevel.Optimal:
    zlibCompressionLevel = ZLibNative.CompressionLevel.BestCompression;
```

In ZLibNative.cs, BestCompression = 9.
```
public enum CompressionLevel : int
{
    NoCompression = 0,
    BestSpeed = 1,
    BestCompression = 9,    
}
```

So it’s defaulting to 9? Unless I’m missing something, I don’t think that’s what was intended.

**Comment by stephentoub** [comment]
Sorry @bjjones, the folks on this thread (Eric, Ian, Josh, Tarek, and me) had an in-person conversation to try to resolve this more quickly, and it appears we never brought the resulting discussion back to this issue.  The end verdict was to simply map to zlib's defaults.

**Comment by bjjones** [comment]
I see, but by doing that you're mapping to the two extremes (level 1 and 9), and getting rid of the old default value (level 6).

I’m wondering if performance was validated after this change? I’m seeing a pretty significant performance decrease, with no noteworthy increase in compression ratio. 

|  | BestCompression (Current Default) | Level 6 Hardcoded (Old Default)|
| :------------ |:---------------:| :-----:|
| Initial (MB)      | 3.1 | 3.1 |
| Compressed (MB)      | 1.01       |   1.01 |
| Average Time (s) | 319.88 | 202.33 |

So with this change, if a user doesn't specify their own compression level, they could see a pretty significant performance decrease. I understand that this makes sense from a design point of view, but I'm having difficulty thinking that a performance decrease in the default scenario was intended.

**Comment by ianhays** [comment]
Interesting. @eerhardt  performed some perf measurements and got results very different from yours. I'll copy-paste them from the email thread (sorry for the formatting):

Unix results:
```
So I did a simple little perf experiment on my Ubuntu VM running in Hyper-V on my Win 10 box with the zlib library that comes with it.  (version 1.2.8, April 28th, 2013 according to the header file).

I used 2 of the files that we use in our tests in the System.IO.Compression.TestData/1.0.0-prerelease package: 

GZTestDocument.txt which is 22 KB
GZTestDocument.pdf which is 120 KB

And the pure stopwatch time and compressed rate is kind of surprising.  Instead of getting a linear slope as the CompressionLevel goes up, you get this big jump between level 3 & 4, and it is flat otherwise.

For the GZTestDocument.txt, I got the following averages after letting the outer loop run for around 45 iterations (note 1 vs 2 is just another run of Program.exe with the same option):

BEST COMPRESSION 1	BEST COMPRESSION 2	DEFAULT COMPRESSION 1	DEFAULT COMPRESSION 2
1.0072152	1.003678169	1.008132992	1.000857844

For the GZTestDocument.pdf, I got the following averages after letting the outer loop run for around 10 iterations:

BEST COMPRESSION 1	BEST COMPRESSION 2	DEFAULT COMPRESSION 1	DEFAULT COMPRESSION 2
6.38237599	6.38450744	6.387791064	6.40745251


So from a stopwatch perspective, there is very little difference between “BEST” and “DEFAULT”.  This was surprising to me, so I took the .pdf file one step further and tried “BEST SPEED”, and then the levels in between.  Here are my results from that:

BEST SPEED	Level 2	Level 3	Level 4	Level 5	Level 6
3.13459624	3.15157955	3.106727	6.340849	6.380746	6.397237

As you can see, the first 3 levels are pretty flat, then a 2x jump between 3 and 4, and then relatively flat to 6, which is relatively the same as the “DEFAULT” and “BEST” COMPRESSIONs above.

So that led me to see how well the compression was for each level.  The starting .pdf document was 121993 bytes.  Here are the resulting compressed bytes for each level:

BEST SPEED	Level 2	Level 3	Level 4	Level 5	Level 6	BEST COMPRESSION
567	567	567	153	153	153	153

So again, this shows there is a big difference between level 3 and level 4, and no differences outside of that change.

Of course, this is just a single .pdf file on a single machine.
```

Windows results:
```
I used the current CoreFX code built on Windows, and switched each of the levels, running the same program.
NOTE: I had to switch physical machines to run it on Windows, so you can’t compare the numbers across Linux vs Windows at all.

BEST SPEED	Level 2	Level 3	Level 4	Level 5	Level 6	BEST COMPRESSION
Avg Time	3.61840454	3.582261	3.624435	8.784391	8.727766	8.803349	8.73276982
Compressed bytes	567	567	567	153	153	153	153

```

I haven't noticed any substantial changes in the deflateStream perf tests either, but I'll run them again today to be sure.

**Comment by bjjones** [comment]
That's interesting. Thanks for taking a look, I will be very interested in the results. For reference, I used a simple microbenchmark that individually compressed each file included in the Calgary Corpus: https://en.wikipedia.org/wiki/Calgary_corpus

There's some relevant data here: http://www.snellman.net/blog/archive/2015-06-05-updated-zlib-benchmarks/ By looking at the 'baseline' data across compression levels, the author saw some pretty large fluctuations in execution time at different compression levels when you vary the file types. Our different conclusions may be because of our different workloads.

**Comment by bjjones** [comment]
I'm wondering if this has been revisited at all? I was able to reproduce the results posted above from @eerhardt, and I agree that there is no performance issue with the workload mentioned. I do believe however that the "Calgary Corpus" workload I mentioned is a more comprehensive scenario, and I am seeing a very concerning performance decrease. I would appreciate it if someone could take a look.

**Comment by ianhays** [comment]
I ran them again and tweaked some variables but didn't come to any dramatic conclusions that suggested a large difference. 

The perf tests in place right now create random data to compress/decompress and do so with several degrees of sparseness/repeated values. It would be fairly simple to include the calgary/canterbury corpus files in the test data package that we pull from nuget and run the perf tests directly on those in addition to the random data. I'll file an issue for it: https://github.com/dotnet/corefx/issues/5423

**Comment by stephentoub** [comment]
Regardless of additional tests getting harnessed (which I agree we should do), it sounds like we should consider going back to the setting we had before, making optimal 6 rather than 9.

**Comment by stephentoub** [comment]
(I've moved the milestone back to rc2, as if we really have taken a significant perf regression, that's important to fix.)

**Comment by ianhays** [comment]
The differences in timing performance between CompressionLevel 6 and 9 are substantial for some files in the Canterbury corpus and insubstantial for others. I'm going to revert it back to 6 and post some perf results in that PR
