### ISSUE TITLE
new DataAnnotations.EmailAddressAttribute() set customErrorMessageSet=true

### ISSUE THREAD

**Issue by Anderman** [dotnet/corefx#4481]
When create a `new EmailAddressAttribute()` the property Errormessage has the value of DefaultErrormessage and customErrorMessageSet=true.

Now I can't detect if the user set this Errormessage.

Look to CompareAttribute. This is the way it can be implemented. Create an extra overload in DataTypeAttribute.

```c#
public EmailAddressAttribute()
            : base(DataType.EmailAddress) {

            // DevDiv 468241: set DefaultErrorMessage not ErrorMessage, allowing user to set
            // ErrorMessageResourceType and ErrorMessageResourceName to use localized messages.
            DefaultErrorMessage = DataAnnotationsResources.EmailAddressAttribute_Invalid;
        }
```

Should be

```c#
public EmailAddressAttribute()
            : base(DataType.EmailAddress, DataAnnotationsResources.EmailAddressAttribute_Invalid) {
            }
```

This should also be done for all other Attributes that has the basetype `DataTypeAttribute`

**Comment by divega** [comment]
The base constructor call was changed purposely to enable localized messages from resources, and we are not planning to revert that, but @lajones will look into the assertion that `customErrorMessageSet` is set to true and it shouldn't be.

**Comment by karelz** [comment]
@hughbe in future, please ping issues when you grab them, especially if they are assigned -- it helps to avoid duplicated work. Thanks!

**Comment by hughbe** [comment]
Oh sorry my bad!

**Comment by karelz** [comment]
No worries ... we appreciate your help either way ;-)

**Comment by lajones** [comment]
Note: to anyone trying to fix this please see the comment on the PR that tried to fix this https://github.com/dotnet/corefx/pull/17867#issuecomment-293730158

**Comment by hughbe** [comment]
@karelz can you unassign me from this?

**Comment by karelz** [comment]
Done, unassigned also @lajones as it seems to be up-for-grabs ...

**Comment by ajcvickers** [comment]
Closing as this is not something we plan to implement.  We would consider a community PR.
