### ISSUE TITLE
Corefx build fails when Xamarin PCL profiles are installed

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/corefx#449]
1. Install Xamarin tools
2. Build corefx

EXPECTED: Build succeeds
ACTUAL: Build fails with lots of type resolution errors

The ResolveNuGetPackages target is failing to resolve assets out of xunit.core.netcore:

```
C:\git\corefx\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\packageresolve.targets(25,5): warning : Unable to resolve the assets of xunit.core.netcore: Couldn't find a matching group
```

The Xamarin tools add XML files to the SupportedFrameworks folders of some PCL profiles.  This results in the configured frameworks for the project to be:

```
.NETFramework,Version=v4.5;.NETCore,Version=v4.5;WindowsPhoneApp,Version=v8.1;WindowsPhone,Version=v8.0;MonoAndroid,Version=v1.0;MonoTouch,Version=v1.0
```

From the package, the following frameworks are supported:

```
.NETFramework,Version=v4.5;ASP.NetCore,Version=v5.0;.NETCore,Version=v4.5;WindowsPhoneApp,Version=v8.1;WindowsPhone,Version=v8.0
```

So since the package doesn't support MonoTouch and MonoAndroid, the build system isn't resolving any of the assemblies inside it.

**Comment by terrajobst** [comment]
Shouldn't this be closed? It seems https://github.com/dotnet/buildtools/pull/51 fixed this?

**Comment by dsplaisted** [comment]
@terrajobst No, dotnet/buildtools#51 doesn't fix this.  It just allows the workaround of changing the extension of the Xamarin .xml files so that they'll be ignored.

**Comment by trydis** [comment]
I'm experiencing the same, 339 warnings and 1038 errors when building from the command line.

**Comment by AlexSikilinda** [comment]
Is there a workaround for this? I tried changing the extensions of Xamarin xmls but it didn't work as for me. Will uninstalling Xamarin help?

**Comment by dsplaisted** [comment]
@AlexSikilinda Changing the extensions for the Xamarin .xml files in the PCL Profile SupportefFrameworks folders worked for me after dotnet/buildtools#51 was merged.  However, I haven't tested this recently.  It's also possible that you missed renaming some of them.

**Comment by citizenmatt** [comment]
If anyone else hits this, the workaround is to look for any `Xamarin.*.xml` files under `%ProgramFiles%\Reference Assemblies\Microsoft\Framework\.NetPortable`. They'll be in several `ProfileX\SupportedFrameworks` folders, and should be deleted, moved or renamed so that they don't end in `.xml`.

**Comment by xen2** [comment]
Note: this also happens on coreclr:

```
Starting the Managed Tests Build

  Restoring all package dependencies...
C:\DEV\dotnet\coreclr\tests\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\packageresolve.targets(25,5): warning : Unable to resolve the assets of System.Diagnostics.Process: Couldn't find a matching group [C:\DEV\dotnet\coreclr\tests\src\Common\Coreclr.TestWrapper\Coreclr.TestWrapper.csproj]
(some more warning like this)
CSC : error CS0518: Predefined type 'System.Object' is not defined or imported [C:\DEV\dotnet\coreclr\tests\src\Common\Coreclr.TestWrapper\Coreclr.TestWrapper.csproj]
```

**Comment by ghuntley** [comment]
![hmmm](https://cloud.githubusercontent.com/assets/127353/7427453/ffe282f0-f01e-11e4-89f6-7e3db14da583.png)

From Visual Studio 2015 RC developer prompt on a laptop that has Xamarin installed working on clean checkout of @dotnet/coreclr~master

**Comment by bpschoch** [comment]
I had the same thing happen to me after updating to the visual studio 2015 RC version selecting all defaults (which I didn't realize selected Xamarin).  I didn't find the files mentioned in the workaround so I went to add/remove and removed Xamarin and it fixed the problem.

Probably need to update developers instructions (Next to using Visual Studio 2015 RC) to make sure not to install Xamarin when installing this latest version to spare others from this side-trip I made.

**Comment by kzu** [comment]
Guys, I'd love to solve this once and for all. What are we doing wrong that this doesn't "just work"? Installing our .xml files under the SupportedFrameworks for various profiles is the way this has to be done for it to work for installing nuget packages as of NuGet 2.8. 

Is this something that changed *again* on the MS/PCL side? Just to be clear: *anything* that is .NET 4.5 is compatible pretty much as-is with Xamarin.iOS and Xamarin.Android, since we are a full .NET 4.5 profile anyway (plus the platform-specific APIs).

So, how to we tell "the build system" that in a reliable way that works without workarounds that work on one version of VS and break in another? ;) (since removing those XMLs most certainly break the installation of those nuget packages that target net45 or profile78/others onto XA/XI projects... )

**Comment by DickvdBrink** [comment]
Ping, would love to see this issue fixed before the final release, (be it on the Xamarin side or VS side).
I think alot of people will run into this issue. Anything I can do to help diagnose this?

**Comment by kzu** [comment]
We need clear guidance on how to extend PCLs for NuGets in a way that works
for users as well as this project. Disabling all nuget compatibility for
Xamarin should not be the answer ;)

**Comment by kzu** [comment]
Hey @dsplaisted has there been any further investigation on why our PCL XML files would break this scenario? It seems to happen in non-CoreCLR cases too (i.e. just got a report from a MS guy, @victorgarciaaprea can point to, who got the error in a blank PCL Xamarin.Forms app).

**Comment by mellinoe** [comment]
It's been a while since there was last activity on this. Since we've changed our build configuration significantly since this was filed, I'm going to close this. Please file a new issue if there's something similar.
