### ISSUE TITLE
Investigate problematic Sockets assertion

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#4500]
There is an assertion in the Socket constructor which I believe might be faulty. I've tried the same code on the desktop framework and didn't hit any issues. The assertion is on line 112 of Socket.cs:

https://github.com/dotnet/corefx/blob/a22364202c6d6cabeeb662fde346941b7284a8da/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L112

``` CSharp
Debug.Assert(addressFamily != AddressFamily.InterNetworkV6 || !DualMode);
```

I hit this assertion on CoreCLR when instantiating a Socket with the following args:

``` CSharp
new Socket(AddressFamily.InterNetworkV6, SocketType.Raw, ProtocolType.IcmpV6);
```

(NOTE: You have to run as admin or the above will throw some other exception.)

cc: @CIPop , @pgavlin

**Comment by CIPop** [comment]
@joshfree What was the reason for moving this from RTM to RC2?

**Comment by SidharthNabar** [comment]
Postponing to RTM - @mellinoe @joshfree if this is blocking an RC2 scenario.

**Comment by SidharthNabar** [comment]
Moving to future since this is not known to block any partner scenarios or impact any tenets.

**Comment by CIPop** [comment]
@karelz, @davidsh This is a behavior difference between .Net Framework and Core. We should triage for `netstandard2.0`.

**Comment by karelz** [comment]
Looks like we should assess the impact here - @CIPop @davidsh do you have any insights?
