### ISSUE TITLE
Provide better x-plat Console/Terminal features

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#4507]
The current implementation of System.Console doesn't provide good experience on Linux. For example, arrow keys (left/right for caret navigation, up/down for history) don't work. 

It is left to the developer to implement this basic functionality in their app if they want to provide consistent good experience across platforms. CoreFX should provide such implementation either as part of System.Console or as a separate library/nuget. On Linux the implementation can use existing native libraries such as curses or readline. 

Related Roslyn issue: https://github.com/dotnet/roslyn/issues/6751

**Comment by tmat** [comment]
FYI @stephentoub @agocke @genlu

**Comment by stephentoub** [comment]
cc: @pallavit, @ellismg 

@tmat, thanks for the issue.  As you and I discussed offline, I'm not convinced this is something that should be built into Console.ReadLine().  The functionality you're describing on Windows is provided not by Console but by the cmd terminal, and my expectation is that it would be provided either by the terminal elsewhere or by an app that specifically wants the functionality.  This functionality to me seems too specialized to include in a core ReadLine() method from the library, which provides the same basic experience as you get on Linux/OSX from other languages and their core libraries.

That said, I'm happy to hear the opinions of others.  I don't want us to build this functionality ourselves, but if a 3rd party library is available, I could see us potentially using it as an optional light-up thing.  For example, you can play with libreadline today in C# on coreclr, e.g.
```C#
using System;
using System.Runtime.InteropServices;

class Test
{
    static void Main()
    {
        while (true) Console.WriteLine(SpecialReadLine());
    }

    private static string SpecialReadLine()
    {
        try
        {
            string s = readline(null);
            add_history(s);
            return s;
        }
        catch { return Console.ReadLine(); }
    }

    [DllImport("libreadline.so.6")]
    private static extern string readline(string prompt);

    [DllImport("libreadline.so.6")]
    private static extern void add_history(string line);
}
```
Assuming we didn't include such functionality in ReadLine, an app can of course do something like what I've done above.

**Comment by pallavit** [comment]
I agree with both @stephentoub  and @ellismg. This behavior should be outside of  Console.ReadLine() and outside of Console class . As stephen mentioned Console class does not provide this behavior on windows but cmd. And so, wrappers on top of ReadLine() seem like the best option to me too :).

**Comment by mellinoe** [comment]
I'm having a bit trouble following the discussion here, I think maybe there's some context missing. The original post talks about using arrow keys for caret navigation and history completion, but most everyone else is talking about ReadLine(). I haven't really thought about this much, but I would think you would implement something like this by looping over ReadKey(true), right? Maybe there was some offline discussion that isn't captured here.

**Comment by stephentoub** [comment]
> I'm having a bit trouble following the discussion here

@tmat is asking that Console.ReadLine() allow you to use the left/right arrow keys to move around in the line of text that you're writing, and that the up/down array keys allow you to go back through the history of lines that you've typed.  This is the experience for most folks on Windows because cmd intercepts those keys and layers that functionality on top of any console app.

>  I would think you would implement something like this by looping over ReadKey(true), right?

Yes, however I don't think in CoreCLR that we actually expose enough on Console to make this work (we should fix that).  In particular, we don't provide any control over setting cursor position, clearing text, etc. that you'd need to do this right.

You can of course P/Invoke to a library that already implements this functionality, as I did in my example.

**Comment by khellang** [comment]
FYI, Mono has a [`LineEditor`](https://github.com/mono/mono/blob/master/mcs/tools/csharp/getline.cs) class that does exactly this. @migueldeicaza recently PR'd it to scriptcs.

It supports editing, history, reverse-history search, pluggable tab-completion and keyboard shortcuts. It probably uses some of the APIs that @stephentoub mentions, so it would be nice to get those exposed :+1:

**Comment by mellinoe** [comment]
> In particular, we don't provide any control over setting cursor position, clearing text, etc. 

Yeah, agreed. I had brought that up with @pallavit a while back and I think we both thought that we need to at least at [SetCursorPosition](https://msdn.microsoft.com/en-us/library/system.console.setcursorposition(v=vs.110).aspx) back.

**Comment by stephentoub** [comment]
> we both thought that we need to bring at least SetCursorPosition back

Yes, I think we should add back all members that we can reasonably implement (one of which is SetCursorPosition).

**Comment by pallavit** [comment]
> In particular, we don't provide any control over setting cursor position, clearing text, etc. that you'd need to do this right.

+1. I agree, we need to expose the full extend of Console APIs and I am hoping to see it happening in the near future :)

**Comment by cherrydev** [comment]
@khellang I was able to get a basic working command line prompt that was integrated with my (existing) CommandLineApplication program in about 30 minutes using LineEditor.  There's an example of its usage [here](https://github.com/oivoodoo/mono-clish/).  The biggest pain was actually parsing (including quotations) the command string into arguments to pass to CommandLineApplication.  Thanks for the fantastic tip!

**Comment by mellinoe** [comment]
For anyone's curiosity, the Console methods that getline.cs linked above uses that we don't support in .NET Core right now are:

`Console.Clear()` Probably just a generally useful thing to support
`Console.SetCursorPosition(int, int)`
`Console.CursorTop` (`CursorLeft` not used)
`Console.BufferHeight` (`BufferWidth` not used)
`ConsoleKey.Zoom` (What key is that anyways? :smile:)

There's also some other stuff that would have to be changed, like it's use of ThreadAbortException and Thread.ResetAbort, and things like Environment.SpecialFolder.

**Comment by pallavit** [comment]
> ConsoleKey.Zoom (What key is that anyways? :smile:)

My understanding is some earlier keyboards used to have ZOOM key similar to Play and Esc keys.

**Comment by pallavit** [comment]
We already have the missing Console contract surface area tracked. Please let me know if any one disagrees with the conclusion of not adding extra functionality to ReadLine() on Linux otherwise I will go ahead and close this issue.

**Comment by andschwa** [comment]
Sorry for my admittedly late response:

We definitely need at least `Cursor` manipulation for our shell. It's great to have `ReadKey` back, but as we discovered last night, without being able to move the cursor, we can't implement our own handling of the arrow keys (and tab completion) on Linux. It looks like #4639 is all we'll need :smile: 

@stephentoub `libreadline` is really not an option for us as it is GPL (not LGPL) (don't get me wrong, I *love* the FSF, but our company isn't releasing our project as GPL for sure).

#4639 is fantastic, but we need the API exposed ASAP. @pallavit can you PR the updated contract for #4636 so I can build a patched version of `System.Console` and unblock my team? That would be *awesome*.

**Comment by niemyjski** [comment]
Can this get reopened. I've been trying to get our sample console to work on osx as it does on windows and I've been having a heck of a time.

https://github.com/exceptionless/Exceptionless.Net/tree/master/src/Samples/Exceptionless.SampleConsole

SetCursorPosition doesn't seem to work at all and among other things the experience isn't even the same.  

On a side note, I can't even get our app to display anything in VS Code (output stream is directed to I think /dev/null 🎱 )...

**Comment by ejsmith** [comment]
Just tried a very simple test on OSX and setting console position and clearing the console doesn't seem to work.

```
using System;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.Clear();
            Console.WriteLine($"{Console.CursorLeft} - {Console.CursorTop}");
            
            Console.SetCursorPosition(0, 0);
            Console.WriteLine("Hello World!");
            Console.SetCursorPosition(0, 0);
            Console.WriteLine("!");
        }
    }
}
```

**Comment by stephentoub** [comment]
How are you running this? "dotnet run"?

**Comment by ejsmith** [comment]
Yes

**Comment by stephentoub** [comment]
And what happens if you instead use "dotnet publish" and then invoke the published app?

**Comment by ejsmith** [comment]
Yep, that seems to work.

**Comment by ejsmith** [comment]
So I guess there is some sort of bug with the way dotnet run is executing the app, eh?

**Comment by stephentoub** [comment]
Console.Clear(), Console.SetCursorPosition(), etc. on unix work by writing ANSI escape codes to stdout.  If stdout has been redirected, these become nops, e.g.
https://github.com/dotnet/corefx/blob/master/src/System.Console/src/System/ConsolePal.Unix.cs#L217
https://github.com/dotnet/corefx/blob/master/src/System.Console/src/System/ConsolePal.Unix.cs#L204

IIRC, "dotnet run" launches the app as a separate process and redirects input/output, which would cause these to become nops when used with "dotnet run".  @eerhardt or @brthor can probably speak best to what the current state of "dotnet run" here is, whether this behavior has been changed, and any plans around it for the future.

**Comment by brthor** [comment]
@eerhardt Recently changed `dotnet-run` to no longer use explicit Stdout/Stderr redirection and we rely on the default behavior of the process api to forward it appropriately.

```
var psi = new ProcessStartInfo
            {
                FileName = commandSpec.Path,
                Arguments = commandSpec.Args,
                UseShellExecute = false
            };
```

This is the ProcessStartInfo which is used to execute the command, `RedirectStandardOutput` and `RedirectStandardError` are no longer used.

@ejsmith Can you show the output of `dotnet --info` ?

**Comment by niemyjski** [comment]
```
Last login: Tue Jun  7 07:25:28 on console
doblake@:~$ dotnet --info
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
blake@:~$ 
```

**Comment by eerhardt** [comment]
Unfortunately [the change to `dotnet run` to not use Stdout/Stderr redirection](https://github.com/dotnet/cli/pull/3013) didn't make it into `preview1`, but it is available in the latest `preview2` versions.

**Comment by niemyjski** [comment]
Awesome, any idea when that will be available? @dotnetconf???

**Comment by eerhardt** [comment]
> Awesome, any idea when that will be available? @dotnetconf???

`preview1` hasn't officially released yet. If you are interested in taking pre-release versions, you can get the latest here:  https://github.com/dotnet/cli#installers-and-binaries.  Note that the `preview2` version of CLI uses pre-release versions of the .NET Core run time that are post-`RC2` (the packages are currently labeled `RC3`.

If you'd like to wait until it is officially released, see https://blogs.msdn.microsoft.com/dotnet/2016/05/06/net-core-rc2-improvements-schedule-and-roadmap/ for the schedule and roadmap.
