### ISSUE TITLE
Ensure that only API usage exceptions are thrown on the sync path from System.Net TPL APIs

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#4508]
API usage and development-time errors should throw exceptions on the sync path of TPL (async) APIs.
All other errors should be configured within the returned Task object.

/cc: @davidsh @stephentoub

**Comment by CIPop** [comment]
@karelz, @davidsh I've opened this for code ported in .Net Framework (hence the port-consider flag). 
In the light of netstandard and X-plat app-compat, I'm closing this as existing apps (ported to the new platform) could become broken by such a fix.

**Comment by karelz** [comment]
@CIPop can you tell me more about the problem / your original suggestion?
Changing how API handles error is breaking change. However, if we believe it is the right thing to do for an API, we should consider it and discuss.

**Comment by CIPop** [comment]
>  can you tell me more about the problem / your original suggestion?

This is actually [quoting](https://github.com/dotnet/corefx/pull/9258#r66335293) @stephentoub. In brief, the async methods have two stages:

1. Synchronous stage: setup the async operation. 

E.g. An I/O API should verify arguments, prepare all structures, configure the Win32 API to be asynchronous (setting a callback), and finally call the Win32 API. The Win32 API should return immediately with some type of IO pending result (or an error if the arguments were incorrect). In some cases the API may return with the actual result (no async stage).

2. Asynchronous stage: receive the result (usually on a different thread). 

Continuing the example above: the callback is called by the Win32 component. The managed I/O API implementation now needs to perform checks (e.g. success/failure, partial read, etc), marshal the result and eventual exceptions to the caller thread and finally mark the async operation state as done. 

The ideal design would be to throw `Argument*` exceptions in the synchronous path. These are usually development-time issues. 

I don't have examples at hand but we've found that some of the async implementations will perform argument validation in stage 2.
