### ISSUE TITLE
System.Runtime.Tests

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#4535]
The tests contained in System.Runtime.Tests (probably as well as others) do not follow the testing naming and structure guidelines suggested by the corefx team.

A good example for the suggested naming and structure guidelines are tests in the System.Net namespace. Examples include suffixing test classes with `Test` and naming test methods in the format `UnitOfWork_StateUnderTest_ExpectedBehaviour()`.

Edit: I think that this is the book recommended by the corefx team for unit testing standards
http://www.amazon.co.uk/The-Art-Unit-Testing-Examples/dp/1933988274

For example the `String` test class should be renamed to `StringTest`. A method named `TestContains` should be renamed to `Contains_String_MatchesExpected` and `TestContainsInvalid`  to `Contains_InvalidInput_ThrowsException`.

Why this could be good:
- Matches suggested naming standards for .NET unit tests
- Modernises the test suite
- Consistency with other unit tests in the project
- Easier to understand what tests do for debugging, test changes or future test additions
- Reasons of perfectionism

Why this could be undesirable:
- Renaming existing tests or test classes could be a breaking change
- Could break parity with the full .NET Framework
- Could cause merge conflicts and extra hassle for the team

If the good people of GitHub and the corefx team see this as desirable, then I shall submit a pull request to modernize this System.Runtime.Tests suite. Maybe in the future, other test namespaces could be updated too.

**Comment by Priya91** [comment]
@Sridhar-MS you were working on some test naming techniques and principles to apply to dotnet repos. Does this collide with your work?
