### ISSUE TITLE
WinHttpHandlerFunctional.Tests.WinHttpHandlerTest.SendAsync_SlowServerRespondsAfterDefaultReceiveTimeout_ThrowsHttpRequestException (from (empty))

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#4540]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_outerloop_windows_win8_release/lastCompletedBuild/testReport/junit/System.Net.Http.WinHttpHandlerFunctional.Tests/WinHttpHandlerTest/SendAsync_SlowServerRespondsAfterDefaultReceiveTimeout_ThrowsHttpRequestException/

System.Net.Http.WinHttpHandlerFunctional.Tests.WinHttpHandlerTest.SendAsync_SlowServerRespondsAfterDefaultReceiveTimeout_ThrowsHttpRequestException (from (empty))

Failing for the past 1 build (Since Failed#786 )
Took 11 sec.
Stacktrace

MESSAGE:
Assert.Throws() Failure\r\nExpected: typeof(System.AggregateException)\r\nActual: (No exception was thrown)
+++++++++++++++++++
STACK TRACE:
at System.Net.Http.WinHttpHandlerFunctional.Tests.WinHttpHandlerTest.SendAsync_SlowServerRespondsAfterDefaultReceiveTimeout_ThrowsHttpRequestException() in d:\j\workspace\dotnet_corefx_outerloop_windows_win8_release\src\System.Net.Http.WinHttpHandler\tests\FunctionalTests\WinHttpHandlerTest.cs:line 68

**Comment by SidharthNabar** [comment]
@davidsh @ joshfree - Has this been failing again? Or was it just a one-time failure?

**Comment by davidsh** [comment]
This particular test has a > 0% possibility of failing due to race conditions in the test. I don't think it needs to be fixed for RTM nor do I think it is a product issue. I plan to possibly redo this test to a UnitTest where we can precisely control "fake" network timings and still test the code paths.

**Comment by karelz** [comment]
Tracked in #14519.
