### ISSUE TITLE
Some specific meta-programming (metadata access) questions...

### ISSUE THREAD

**Issue by mgravell** [dotnet/corefx#4543]
Blame @davidfowl - he told me to put them here ;p

1. the big one; is there an indirect equivalent to `GetMethodBody()`  / `GetILAsByteArray()` (plus locals, params, exception clauses etc)? Basically, is there an API that exposes the raw underlying IL? If the answer to this one is "nope", then the rest is moot...
2. `[UnverifiableCodeAttribute]` - no longer exists; is there a way to determine if a member is unverifiable?
3. can `volatile` fields be detected? Sigil used to do this via `GetRequiredCustomModifiers()`
4. `TypedReference` - am I right in thinking this simply doesn't exist as a concept?
5. any mechanism to resolve string literal and fields from metadata tokens? (akin to `ResolveString()` / `ResolveField()`)

Context: I'm converting Sigil/Jil; most stuff is working, but some low-level meta-programming  stuff is missing. It would be nice to reinstate the original optimizations to Jil (and an entire chunk of Sigil).

**Comment by nguerrera** [comment]
cc @weshaggard

**Comment by nguerrera** [comment]
1. You can use GetMetadataToken() from System.Reflection.TypeExtensions and then drop down to System.Reflection.Metadata to get the IL. I'll post a gist later tonight. Keep in mind that tokens will not be available on .NET Native if you're also expecting this to work there.

2. I don't believe there's any easy way, but a method could be unverifiable and not have that attribute. Really, the actual verifier succeeding is the only thing you could trust. What do you need it for?

3. Could also be done via metadata token -> S.R.M, but messy. We should add GetRequiredModifiers to .NET Core.

#4 Correct.

#5 Can enumerate each member's token and put them in a dictionary for subsequent lookup.

**Comment by nguerrera** [comment]
Here's that gist for (1). Sorry for not posting sooner. I forgot all about it until now: https://gist.github.com/nguerrera/72444715c7ea0b40addb

Unfortunately, it doesn't quite work on DNX because I'm getting Assembly.Location = String.Empty. I'll  follow up. We either need DNX to override Location somehow, or to add a TryGetRawPEImage alongside TryGetRawMetadata.

**Comment by davidfowl** [comment]
TryGetRawPEImage would be nice

**Comment by pallavit** [comment]
GetRequiredCustomModifiers() will be added to .NET Core as part of #5381. 

@nguerrera , @mgravell Looking at the rest of the thread, the other request is to add a new API TryGetRawPEImage  to System.Reflection.Metadata. Let me know if I missed something here.

**Comment by nguerrera** [comment]
TryGetRawPEImage needs to be implemented in mscorlib, just like TryGetRawMetadata. We used the System.Reflection.Metadata *namespace* for TryGetRawMetadata, but it cannot actually be implemented in System.Reflection.Metadata.dll.

**Comment by Konard** [comment]
```C#
using System.IO;
using System.Reflection;
#if !NET45
using System.Reflection.Metadata;
using System.Reflection.Metadata.Ecma335;
using System.Reflection.PortableExecutable;
#endif

namespace Platform.Helpers.Reflection
{
    public static class MethodInfoExtensions
    {
        /// <remarks>
        /// Based on https://gist.github.com/nguerrera/72444715c7ea0b40addb
        /// </remarks>
        public static byte[] GetILBytes(this MethodInfo methodInfo)
        {
#if NET45
            return methodInfo.GetMethodBody().GetILAsByteArray();
#else
            var metadataToken = methodInfo.GetMetadataToken();
            
            using (var stream = File.OpenRead(methodInfo.DeclaringType.GetTypeInfo().Assembly.Location))
            using (var peReader = new PEReader(stream))
            {
                var metadataReader = peReader.GetMetadataReader();
                var methodHandle = MetadataTokens.MethodDefinitionHandle(metadataToken);
                var methodDef = metadataReader.GetMethodDefinition(methodHandle);
                var methodBody = peReader.GetMethodBody(methodDef.RelativeVirtualAddress);
                return methodBody.GetILBytes();
            }
#endif
        }
    }
}
```

Looks like this working today as expected on .NET Core RC2 (netstandard1.5+) and .NET Framework 4.5+

**Comment by tmat** [comment]
I propose to close this issue and if there is any specific API missing either from System.Reflection or System.Reflection.Metadata let's open new issue for each missing API. Any objections?
