### ISSUE TITLE
Build creates self-referential project.json under artifacts which breaks dnu restore

### ISSUE THREAD

**Issue by mgravell** [dotnet/corefx#4578]
(in case it is contextual to my setup, I'm seeing this from [this commit](https://github.com/StackExchange/dapper-dot-net/commit/00b8a2f59dbd735df3f86381384661f2196a478e))

I have a test project; if I clone it afresh and `dnu restore`, everything is happy. If I build it in Visual Studio (with latest rc1 bits etc) it creates (as desired) the `artifacts` folder. If I now try `dnu restore`, it complains:

> Errors in d:\Dev\dapper-dot-net\artifacts\bin\Dapper.DNX.Tests\Debug\app\project.json
>    Unable to locate Dependency Dapper.DNX.Tests >= 1.0.0

Upon investigation, this project.json contains:

      "dependencies": {
        "Dapper.DNX.Tests": "1.0.0"
      },

This has come from the build tools - this is not present in the original file.

Possible fixes (spit-balling, not my area):

- `dnu restore` should not look at `artifacts`
- build should not create self-referential projects

In my case I can (and have) also fix it by unchecking "Produce outputs on build", but it seems to be doing something undesirable here.

**Comment by mellinoe** [comment]
You may get better visibility in the ASP.NET repos, as this seems to be an issue specific to their project system/tooling, although we can certainly try to help narrow things down and help here.

From what I understand, `dnu restore` restores all of the projects in all subdirectories unless you specify a specific project, so perhaps you need to be more specific with the restore command (i.e. `dnu restore .\project.json`). Again, the ASP.NET folks would know more of the specifics of their tooling, so the above may not be correct :smile:. It does seem reasonable that dnu restore could ignore the generated artifacts folder, though.

@davidfowl

**Comment by mgravell** [comment]
@mellinoe thanks; can you hint at a particular repo I should  be logging this with instead?

re being more specific - when you have 5 or 6 projects under the tree and you're trying to sync everything, that would be very cumbersome

**Comment by mellinoe** [comment]
> when you have 5 or 6 projects under the tree and you're trying to sync everything, that would be very cumbersome

Yeah I can definitely see how that would be annoying.

@anurse Do you have any insight into this issue, or whether it's a new behavior in the latest version or something like that?

**Comment by davidfowl** [comment]
@mgravell This should be gone with the .NET CLI. Today it happens because running `dnu pack` on anything that has a command will create a package with a `project.json` (as it represents an application being packed in a nuget package).

**Comment by mgravell** [comment]
Awesome, thanks.
