### ISSUE TITLE
Add DiffieHellman

### ISSUE THREAD

**Issue by xied75** [dotnet/corefx#4581]
Dear all,

It looks like we got ECDH in corefx now, but what about the old DH? Are these two interchangeable or any specific reason the old DH is not implemented. It is done in mono. I can try to port it here if it is allowed to merge. ( I mean if there is no policy saying we must NOT have DH anymore, things like that.)

Best,

Dong

**Comment by bartonjs** [comment]
Well, ECDiffieHellman isn't quite here yet.  A prototype contract got copied into the git tree by accident, but there's no implementation.  It won't show up until after v1 RTM, because we need to make some changes to the ECDiffieHellman base class first to make it suitable to cross-platform support.

As for regular Diffie-Hellman, .NET has never had support for that algorithm.  If you have a scenario that you want to share, and can't be upgraded to ECDH, I can look into if the omission was intentional, lack of scenario, or just lack of time.

**Comment by xied75** [comment]
@bartonjs Thanks a lot for reply. I was trying to get https://github.com/mono/ngit work under UWP. Now ngit reference nsch, and within nsch they have code calling DH:
https://github.com/mono/ngit/blob/master/NSch/NSch/Sharpen/KeyAgreement.cs

They currently use mono.security to supply this type.

If this is enough to warranty your further investigation, that would be great. I'm not sure if I can replace the DH with ECDH as I haven't done enough learning on this topic. My first step was trying to do a like for like change.

Eventually I might just replace the whole nsch with the new corefx openssl stuff, what do you think?

Best,

Dong

**Comment by xied75** [comment]
@bartonjs Another quick question related to this issue. There is also the RC4/ARC4 missing from corefx, although it is no longer safe to use, I suppose as a library one might still provides that. It can be found in JAVA, Mono, and lots of 3rd party lib's e.g. Bouncy Castle.

Given there are tons of Security protocols, standards, specs, what is the corefx general policy on this? I assume most devs (especially enterprise) would prefer MS to provide those foundation classes so that we don't need to nuget 3rd party lib to potentially having holes in our app. MS has been serious about Security from long time ago, I suppose even corefx is now open source you would still go through very stringent procedures for these things which means it's no going to be fast. So shall we carry on to report what is missing and hope to get it soon or shall we just nuget 3rd party libs for now?

**Comment by bartonjs** [comment]
@xied75 The policy is just "open an issue, preferably explaining a scenario" :smile:.

In the case of RC4, it would be fairly unlikely to make it into CoreFX because of the combination of not having been in .Net Full Framework and it now being considered an insecure algorithm.

**Comment by Steppenwolfe65** [comment]
Rather than ECDH, you might want to think about lattice based ciphers; RingLWE is fast, provably secure, and provides post-quantum security. Large scale quantum computers will soon be a reality, and RSA and ECDH need to be replaced.

**Comment by karelz** [comment]
The algorithm seems to be in decline of usage. If we had the API and implementation, there would be associated cost of maintenance, security review, and security patching ... quite non-trivial cost.
We should rather spend our time implementing newer algorithms.

Please let us know if you think we forgot some arguments ...

Another option is to create a library on top of .NET Core which implements this algorithm. We should not try to pull it into the platform, unless there is really huge benefit justifying the cost mentioned above.
