### ISSUE TITLE
All exceptions in Resources.Reader need to be localizable

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefx#4582]

**Comment by karelz** [comment]
Next step: We need to take messages out from code (we need a list) and move them to resx file.
Should be straightforward.

**Comment by ramarag** [comment]
With https://github.com/dotnet/corefx/pull/12468 implementation has moved to System.private.corelib in coreclr repo and this issue is no longer actionable

**Comment by karelz** [comment]
@ramarag, is the main reason that the code has moved, or that the issue is fixed?

If it is the former, we currently do not have strict policy where to track non-API changes issues. So unless there is a bug in coreclr tracking it, we should keep this one opened.

**Comment by ramarag** [comment]
@karelz all strings used by exceptions in the S.P.Corelib are localizable [ as they are the same as what ships on desktop]

@KrzysztofCwalina What exceptions did you have in mind when you filed this issue ?
