### ISSUE TITLE
CurlHandler empty header values not being sent

### ISSUE THREAD

**Issue by martinbooth** [dotnet/corefx#4597]
You can use the following piece of code to test this:

```
var client = new HttpClient();
client.DefaultRequestHeaders.Add("No-value", "");
client.DefaultRequestHeaders.Add("With-value", "value");

await client.GetAsync("http://www.google.com");
```

Then on linux, the header No-value is not sent. This breaks things such as the AWS SDK on linux due to the request's signature not matching, plus, it is different to the behaviour on windows

**Comment by davidsh** [comment]
@stephentoub @vijaykota PTAL

**Comment by martinbooth** [comment]
Thanks for your quick turnaround on this.

After a little searching, I found this: https://www.myget.org/gallery/aspnetcidev and was able to test it out.

There is still an issue which seems related (although, I'm not personally affected by this one):

The example I gave (http://www.google.com) actually causes a 302 redirect in Australia, and I happened to notice that the header is missing from the subsequent request on linux. This is different behaviour to windows

Linux:
```
GET http://www.google.com/ HTTP/1.1
Host: www.google.com
Accept: */*
Accept-Encoding: gzip,deflate
Connection: Keep-Alive
No-value: 
With-value: value
```
```
GET http://www.google.com.au/?gfe_rd=cr&ei=btBTVp6vCsTu8we45Kv4Dg HTTP/1.1
Host: www.google.com.au
Accept: */*
Accept-Encoding: gzip,deflate
Connection: Keep-Alive
With-value: value
```

Windows:

```
GET http://www.google.com/ HTTP/1.1
Accept-Encoding: gzip, deflate
No-value: 
With-value: value
Connection: Keep-Alive
Host: www.google.com
```
```
GET http://www.google.com.au/?gfe_rd=cr&ei=pdBTVqyuG8Tu8we45Kv4Dg HTTP/1.1
Accept-Encoding: gzip, deflate
No-value: 
With-value: value
Connection: Keep-Alive
Host: www.google.com.au
```
