### ISSUE TITLE
Add IDataObject.GetData(format, index)

### ISSUE THREAD

**Issue by jnm2** [dotnet/corefx#4602]
When receiving dragged attachments from Outlook, `GetData("FileContents")` only returns the first file and there is no way to access the others.

In order to access each file in [FileContents (MSDN)](https://msdn.microsoft.com/en-us/library/windows/desktop/bb776902.aspx?f=255&MSPPError=-2147217396#CFSTR_FILECONTENTS):

> The target treats the data associated with a CFSTR_FILECONTENTS format as if it were a file. When the target calls IDataObject::GetData to extract the data, it specifies a particular file by setting the lindex member of the FORMATETC structure to the zero-based index of the file's FILEDESCRIPTOR structure in the accompanying CFSTR_FILEDESCRIPTOR format. The target then uses the returned interface pointer or global memory handle to extract the data.

The .NET Framework always passes [a hardcoded `lindex` of `-1`](http://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/DataObject.cs,1394). Can we have an overload that allows you to pass any index?

My workaround for now is to use private reflection and mass copy-paste reference source code, adding an index parameter all the way down. I hope the future will not be so ugly.

`SetData` is similarly limited.

**Comment by joshfree** [comment]
Hi @jnm2, this repo is part of [.NET Core](http://docs.asp.net/en/latest/conceptual-overview/dotnetcore.html), and not the full .NET Framework.  For suggestions for the full .NET Framework (such as additions to Windows Forms) you can post to [uservoice](http://visualstudio.uservoice.com/forums/121579-visual-studio-2015/category/31481--net).

Thanks

/cc @Tanya-Solyanik

**Comment by jnm2** [comment]
Ah, I was not aware that Windows Forms was unavailable on .NET Core.
