### ISSUE TITLE
Consistent ToString() implementations

### ISSUE THREAD

**Issue by mattwarren** [dotnet/corefx#4608]
At the moment some classes override `ToString()` and some don't. So it means that if you call `ToString()` on an object for debugging/logging purposes you may get something useful or you may just get the default which is the fully qualified `Type` name.

To see how widespread this is, I wrote a [simple app using Cecil](https://gist.github.com/mattwarren/33edc6d07ea087542ccb) (please let me know if [my logic is wrong](https://gist.github.com/mattwarren/33edc6d07ea087542ccb#file-clrtostringoverrides-cs-L91-L107)).

Here's the lists of types that don't override ToString():
- [Value types](https://gist.github.com/mattwarren/1dc37901be49a18a7204) and a [shorter summary](https://gist.github.com/mattwarren/afba4b325f02e66db419)
- [Reference types](https://gist.github.com/mattwarren/3bcecf5d2b9810c48b41) and a [shorter summary](https://gist.github.com/mattwarren/79cc5669e1e4ebae6a46)

Is there any desire to be more consistent across types or is it not something that people worry about? Is it expected that `[DebuggerDisplayAttribute]` should be used instead?

For instance in Java you can call ToString() on an object and you always gets something meaningful back. This even extends to collections, it calls ToString() on each item in the collection and appends those into a string, which might be going a bit too far.

**Useful links**:
- [Object.ToString Method ()](https://msdn.microsoft.com/en-us/library/system.object.tostring.aspx)
- [Framework Design Guidelines: Overriding Object.ToString()](http://blogs.msdn.com/b/brada/archive/2009/02/02/framework-design-guidelines-overriding-object-tostring.aspx)
- [Why override ToString()? Use DebuggerDisplayAttribute instead](http://blogs.msdn.com/b/soultech/archive/2011/04/05/whyoverridetostring_2d00_use_2d00_debuggerdisplayattribute_2d00_instead.aspx)

**Comment by leppie** [comment]
How about the default `ToString()` detects if the debugger is attached and shows extra info, like say members in order up to 50 chars?

**Comment by mattwarren** [comment]
@leppie that's not a bad idea fro debugging, although I don't know about the cost of adding code to all ToString() methods that detects if the debugger is present?

But it doesn't help for logging which was the other scenario I was highlighting.

**Comment by KrzysztofCwalina** [comment]
@weshaggard, what's the compat bar for ToString? Do we accept changes at leaas for the default ToString implementations? i.e. the ones that return the type name.

**Comment by weshaggard** [comment]
What information would you try to put into all these ToString's? I agree that if an class as something useful then it might be worth overriding it's ToString but there really isn't any consistent way to provide a meaningful value in a programmatic way. For that reason I wouldn't try and do this holistically across all the types in the framework.  

As for the compat bar anything we changed here that also exists on the .NET Framework we should expect that change to go to the .NET Framework and as such the bar would be pretty high. I wouldn't change them unless there is actually some value to changing them.

**Comment by mattwarren** [comment]
@weshaggard, @KrzysztofCwalina 

> What information would you try to put into all these ToString's? I agree that if an class has something useful then it might be worth overriding it's ToString but there really isn't any consistent way to provide a meaningful value in a programmatic way. For that reason I wouldn't try and do this holistically across all the types in the framework.

Yeah I agree, my original intent for this issue was to see if there was any desire to change (one-by-one) all the classes that don't override `ToString()`. So that they individually return something meaningful for that class, not do it in one place for all classes/types.

> As for the compat bar anything we changed here that also exists on the .NET Framework we should expect that change to go to the .NET Framework and as such the bar would be pretty high. I wouldn't change them unless there is actually some value to changing them.

I didn't think about that, I (naively) thought that these changes could just be made in DNX/CoreCLR and not have to be ported back for the .NET Framework, so that changes things.

Based on the lack of response from (almost) anyone else, I guess that not many people are bothered about whether `ToString()` consistently returns something meaningful or not. I admit it's a bit of a niche concern ;-)

So I'm thinking that if I or someone else wants `ToString()` overridden in a specific class, then an issue can be raised for that class and dealt with on a case-by-case basis, rather than in a holistic way, do you agree?

**Comment by stephentoub** [comment]
> So I'm thinking that if I or someone else wants ToString() overridden in a specific class, then an issue can be raised for that class and dealt with on a case-by-case basis, rather than in a holistic way, do you agree?

I think that's the right approach.  Thanks.

**Comment by KrzysztofCwalina** [comment]
I agree that it might be better to do it on case by case basis, but I do think we should do it for cases where it adds value. I really would like our APIs get better over time, and a meaningful ToString is a small by often very nice improvement to the debugging experience.

**Comment by terrajobst** [comment]
We could also make changes to the debugger. For instance, when trying to locate an item in a list I often end up stopping the debugging session in order to override `ToString`. Obviously, this only works if the type is mine.

We could, for example, change the debugger to detect whether ToString is overridden, and if not, fall back to some default presenter that simply returns a string like: `Prop1=Value, Prop2=Value`.

**Comment by KrzysztofCwalina** [comment]
This only works when using the debugger. Does not work for logging, for writing values to console, etc.

**Comment by mattwarren** [comment]
> I really would like our APIs get better over time, and a meaningful ToString is a small by often very nice improvement to the debugging experience.

Let's try a concrete example, [System.Net.Socket](https://msdn.microsoft.com/en-us/library/system.text.asciiencoding(v=vs.110).aspx) doesn't override `ToString()`, but unless I'm mistaken it could be a good candidate. However which of the following properties should be included (maybe this is why it's not been done!!):
- **AddressFamily**
- **Available**
- Blocking	
- **Connected**
- DontFragment	
- DualMode	
- EnableBroadcast	
- ExclusiveAddressUse	
- Handle	
- **IsBound**
- LingerState	
- LocalEndPoint	
- MulticastLoopback	
- NoDelay	
- **ProtocolType**
- ReceiveBufferSize	
- ReceiveTimeout	
- **RemoteEndPoint**
- SendBufferSize	
- SendTimeout	
- **SocketType**	
- Ttl	
- UseOnlyOverlappedIO	

The ones in **bold** seem the most interesting to me, but maybe I'm wrong.

Also I the problem is recursive, i.e. the Type of each property needs to have a meaningful `ToString` implementation otherwise the parent `ToString` implementation gets complicated. However if a single `ToString` implementation can rely on just calling `ToString` on any properties it thinks are interesting, things are easier.

**Comment by stephentoub** [comment]
> This only works when using the debugger.

You could imagine having a ToStringProvider in a corefx assembly that used reflection to provide such a canonical representation, and any code could get the "default" equivalent via ```ToStringProvider.ToString(obj)```, or something like that.

**Comment by KrzysztofCwalina** [comment]
But why make it so complex? why not simply override ToString? 
And BTW, thinking about it more, maybe we can afford behavioral difference here between desktop and CoreFx?

**Comment by stephentoub** [comment]
> But why make it so complex? 

I'm not saying don't override ToString. I'm saying we shouldn't change the base object's behavior, and there will always be types for which we haven't overrides it's ToString, so something like that would address the stated concerns. If there are types for which we want to change the ToString implementation, we can still do so, potentially in some cases using that default.

**Comment by KrzysztofCwalina** [comment]
Oh, I got it. Sounds good.

**Comment by advancedrei** [comment]
I'm not sure how this would work out due to dependencies, but could be really interesting if the ToStringProvider's default output was either JSON, or properties notated in such a way that they could be copy-pasted into Unit Tests. Made-up example output:
```
new System.Net.Socket {
    Property1 = "SomeValue",
    Property2 = Some.Enum,
}
```
The latter would be very useful in using the debugging process to replicate runtime data into Unit Tests to improve code coverage. I have plenty of cases where I have complex object models that I'd like to build tests based on real-world inputs, and being able to dump a current object tree state into a unit test could be quite handy.

**Comment by MgSam** [comment]
I think trying to make ToString better always ends up where this thread has gone- one person wants one representation, another person wants something different. And all solutions are breaking changes.

An alternative is to add method(s) to all objects that give you back the type of strings you're actually interested in. This can possibly done with extension methods if you don't want to touch `Object`  and don't mind the reflection cost. For example, I have an extension method, ToDebugString, that prints out all the properties of an object, or, if its a collection, all the elements of the collection by recursively calling ToDebugString on them. You could easily imagine a ToJsonString or some such as well. 

I imagine that you guys may have had to do something like this for the REPL already, no?

**Comment by JonHanna** [comment]
The best `ToString()` overloads return the most obvious string representation for the culture in question, that can be usefully used in UI. When classes don't have a most obvious string representation for the culture in question that can be usefully used in UI, I'd be less eager to supply one purely for debugging unless it proved particularly useful in that case.

**Comment by MgSam** [comment]
> The best ToString() overloads return the most obvious string representation for the culture in question

What's "most obvious" to you is probably different from what is most obvious to me, and what is most obvious to your friend, and most obvious to Bob your uncle. Trying to encode a defacto representation that is UI-friendly seems impossible; different representations are appropriate for different use cases. 

I think @mattwarren's comment illustrates this really well. How do you decide which properties "matter" for ToString? Maybe the ones you think matter are different from the ones he thinks matter.

**Comment by JonHanna** [comment]
> What's "most obvious" to you is probably different from what is most obvious to me, and what is most obvious to your friend, and most obvious to Bob your uncle.

Exactly.

**Comment by KrzysztofCwalina** [comment]
I think any properties would be better than the default name of the type. If such chosen properties don't work for somebody, an extension method could be used.

**Comment by stephentoub** [comment]
I'm going to close this discussion as it hasn't seen progress in 3.5 years.  As was discussed earlier on the thread, we can consider adding ToString-overrides on a case-by-case basis.  Thanks.
