### ISSUE TITLE
FileNotFoundException issue

### ISSUE THREAD

**Issue by SharpNoiZy** [dotnet/corefx#4609]
I can not compile a new lib I started with new VS 2015 Update 1 RC.
```
The type "FileNotFoundException" is in "System.IO, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Runtime, Version=4.0.21.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" available.
```
It's only underlined in the corefx code view.

Any ideas?

**Comment by mellinoe** [comment]
You need to reference a newer version of System.IO. We moved that exception type down into System.Runtime some version, so if you reference a version of System.IO before that change and a version of System.Runtime after that change, you will get duplicates. If you're using the latest version of System.Runtime (4.0.21.0), then just grab the latest version of System.IO and the problem should go away.

**Comment by mellinoe** [comment]
@SharpNoiZy Did you get a chance to try the above? Let me know if it helped or if you saw any other issues.

**Comment by SharpNoiZy** [comment]
No, unfortunatelly, it doesn't help.
My dependenies are:
"System.Runtime": "4.0.21-beta-23516",
"System.IO.FileSystem": "4.0.1-beta-23516",

My code is:
```
#if DNX451
			catch (System.IO.FileNotFoundException)
			{
				return IOType.DoesNotExist;
			}
#else
			catch (System.Runtime.FileNotFoundException)
			{
				return IOType.DoesNotExist;
			}
#endif
```

And the message is now:
The Type-or Namespacename "FileNotFoundException" is not available in the namespace "System.Runtime".

**Comment by mellinoe** [comment]
`FileNotFoundException` is in the `System.IO` namespace regardless of which framework you are targeting. You shouldn't need any #if blocks at all here.

The names of the NuGet packages don't necessarily imply that all of the types are in that namespace. For example, most of the things in System.Runtime are actually in the `System` namespace, but there's also things in various other low-level namespaces. Same goes for other NuGet packages. In this case, `FileNotFoundException` is in `System.IO`.

**Comment by mellinoe** [comment]
Let me know if the above was not the issue you hit, I'm going to close out the issue for now.

**Comment by SharpNoiZy** [comment]
Yes, this issue is solved, thanks!

**Comment by mellinoe** [comment]
@SharpNoiZy Glad to hear :+1:
