### ISSUE TITLE
BigInteger helper methods like IsProbablePrime(), GenerateRandom(), etc.

### ISSUE THREAD

**Issue by xied75** [dotnet/corefx#4610]
Dear all,

Shall we implement those which exist in JAVA and Mono? If there is no objection from design point of view or other concerns then I will make a PR soon.

(BTW, in general is it ok to copy code from Mono into Corefx? What about reference the JAVA source?)

**Comment by Joe4evr** [comment]
In the case of Mono, you should be careful, as I think it's under some variant of a GPL license, so you can't just straight-up copy it over. There was an issue not too long ago either here or in CoreCLR for a BSD compatibility thing where that was a blocker, and the person who wrote the solution for Mono had to come in and say that since it wasn't more than a man page implementation he offered his PR on Mono up to the public domain.

**Comment by svick** [comment]
The process for proposing changes to the API, like adding new methods, is [detailed here](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md).

In short, you should create an issue with a "speclet" first, then it goes through discussion and API review and if it's accepted, you can post a PR.

**Comment by xied75** [comment]
@mellinoe just to clarify this issue assigned to you means you are going to code it or 'manage' it?

@Joe4evr now due to the license of GPL, we can't just simply move over the mono code, this will complicate the thing, I would need to start from a spec in order to write something 'different' to mono code, not really used to this kind of game yet. :)

**Comment by akoeplinger** [comment]
@xied75 FYI, the Mono class libraries are under MIT license (i.e. code in mcs/class as specified in the [license](https://github.com/mono/mono/blob/master/LICENSE)).

See also here for what the issue assignment means: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#assignee

**Comment by mellinoe** [comment]
>  just to clarify this issue assigned to you means you are going to code it or 'manage' it?

Alex linked our explanation above, but yes, it basically means I will help "manage" the proposal. We still expect that you will come up with a description of what you would like to be added, the rationale for adding it, use cases, API names/shape etc. as well as provide an implementation for it. That includes the source and any tests needed to validate it.  We can obviously help with any of the above, and we have documentation on what we expect in the different stages here: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md.

**Comment by CodesInChaos** [comment]
1. Are they useful outside of cryptography? Because `BigInteger` isn't well suited for crypto (immutability, variable timing).
2. It seems like a good idea to inject the RNG, but what abstraction to use for that? `Action<byte[]>`?

**Comment by xied75** [comment]
@CodesInChaos 1. I can't really answer that question, at least in the Mono case, looks like a No. Not sure about JAVA world, might need to spend some time to find out how much this is used. If you think this is not a good thing in general, do you have better solutions in mind. I don't really fancy copy over whatever is in java, if we can do it differently and better, why not.

2. No idea. :)

**Comment by Steppenwolfe65** [comment]
I think the go-to guy for BigInteger in C# is probably Antonello Provenzano, Deveel Math library: https://github.com/deveel/deveel-math/tree/master/src/Deveel.Math/Deveel.Math
IMO, no matter how well it is written, BigInteger is rather slow, and cryptography based on big number factoring has a limited shelf life.

**Comment by mellinoe** [comment]
@xied75 Were you still interested in bringing forward a proposal for adding this functionality?

**Comment by xied75** [comment]
@mellinoe When I started this issue I was converting a Java derived C# library, and in Java there are lots of methods on BigInteger, later I gave up due to the dislike of Java's idioms. I tried to bring in the real experts like @Steppenwolfe65. Now I think the real question is Do people really think Corefx should have a rich Numerics (which includes BigInteger and many more), or rather nuget third party libs.

**Comment by mellinoe** [comment]
I'd be happy to help push the discussion forward, but we don't have anything concrete enough here. Feel free to re-open or file a new issue with a concrete proposal if you'd like to continue this.

**Comment by karelz** [comment]
Another data point: We started lately forming a line of what belongs into CoreFX and what doesn't. Non-CoreFX repos have advantage of independent shipping schedule, potentially even more open for contributions than CoreFX repo.

Key reasons for being in CoreFX repo: It's code ported from Desktop .NET Framework. Something in CoreFX needs to depend on it.
Insufficient reason: Similar APIs are already in CoreFX (e.g. we do not plan to add gazillion of collections - even `PriorityQueue` is border line and will be in CoreFX mainly, because it will be consumed by other CoreFX libraries as well).
