### ISSUE TITLE
System.Resources.ResourceManager with other project (dll) for the resources

### ISSUE THREAD

**Issue by danicomas** [dotnet/corefx#4611]
Could you add some features to do compatible the resources (text localization) in SiteMapNode? By now we an create a custom provider, or code expression builder but not a expression builder in sitemapnode.

https://msdn.microsoft.com/en-us/library/aa905797.aspx#exaspnet20rpm_topic5

**Comment by karelz** [comment]
Sorry for the XXXL delay in our answer. Could you please explain to us in more details what exactly you mean? Real-world example would be best.

**Comment by jkotas** [comment]
This is ASP.NET specific. ASP.NET Core localization is described in https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.1 . It is best to open issues about that in https://github.com/aspnet/Home/issues
