### ISSUE TITLE
Documentation; Running tests on linux

### ISSUE THREAD

**Issue by saurabh500** [dotnet/corefx#4616]
I am using the document https://github.com/dotnet/corefx/blob/master/Documentation/building/cross-platform-testing.md to run tests on linux. 

One of the steps in the document mentions about mscorlib.dll

>> A coresponding version of mscorlib.dll, built on Windows but targeting Linux. This can be produced by running build.cmd linuxmscorlib Release from a CoreCLR enlistment on Windows. Remember that the runtime and mscorlib are tightly coupled with respect to object sizes and layout so you need to ensure you have either a release coreclr and release mscorlib or debug coreclr and debug mscorlib.

Is this step necessary? When I build coreclr using ./build.sh Release, a Linux specific mscorlib.dll is generated.

**Comment by saurabh500** [comment]
cc @ellismg

**Comment by mellinoe** [comment]
Yeah, that part is a bit out of date. We can build mscorlib on other platforms fine now, since we have a .NET Core-based BclRewriter tool, which was the blocker before.
