### ISSUE TITLE
StringBuilder creates unnecessary strings with Append methods

### ISSUE THREAD

**Issue by JamesNK** [dotnet/corefx#4632]
Append that takes a non-string value like int, double, etc, converts the value to a string then appends that string. StringBuilder should write the value's chars to the buffer without creating unnecessary strings.

**Comment by khellang** [comment]
How do you get "the value's chars" without getting its string representation?

**Comment by stephentoub** [comment]
@JamesNK, yes, I agree this would be a good thing to do.  With the code in coreclr, it'd be relatively complicated to do so, as all of the formatting logic is in coreclr in native code behind FCalls.  That code in .NET Native / corert has been ported to managed, and now that corert is open sourced, that code is available.  @jkotas / @weshaggard may have thoughts on this, but I expect we'd want to achieve this in coreclr by using the managed implementation from corert.

https://github.com/dotnet/coreclr/issues/565
https://github.com/dotnet/corert/blob/84c21c058b04ed734e5001ad603babd3614fa025/src/Common/src/System/Globalization/FormatProvider.Number.cs

**Comment by JamesNK** [comment]
@khellang It's not hard - https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/JsonTextWriter.cs#L760-L781

**Comment by khellang** [comment]
Ah, I see what you mean now :smile:

**Comment by mattwarren** [comment]
> @khellang It's not hard 

It's a *bit* more complicated when you want culture-sensitive formatting, for instance `10,000` instead of `10000`. In that case you can't just write out the individual characters.

**Comment by weshaggard** [comment]
cc @KrzysztofCwalina

**Comment by KrzysztofCwalina** [comment]
Corefxlab formatting library does exactly that: https://github.com/dotnet/corefxlab/tree/master/src/System.Text.Formatting
... and supports globalization
But we don't yet have concrete plans to merge it into corefx or StringBuilder.

**Comment by justinvp** [comment]
Up for grabs? I'd be happy to work on merging the managed number formatting code from corert to coreclr and use it to reduce/avoid unnecessary allocations associated with `StringBuilder.Append*` and `String.Format`. Related: #1514

**Comment by KrzysztofCwalina** [comment]
@justinvp, I think it would be great if you'd like to work on it. But I would not call it "up for grabs". This is a very tricky project given compatibility requirements for something so fundamental as StringBuilder. The new implementation needs to be 100% compatible and result in no performance regressions, and that includes culture-aware formatting.

**Comment by KrzysztofCwalina** [comment]
cc: @vancem, @jkotas

**Comment by AlexGhiondea** [comment]
@KrzysztofCwalina are we still interested in taking this, or do we see the library from CoreFxLabs becoming the way to do this in the future?

**Comment by jkotas** [comment]
Improvements of the existing formatting APIs (with the due-diligence required to maintaining 100% compatibility) should be good to me. It would goodness for existing code. The current formatting APIs are leaving a lot on the table as discussed in #1514.

However, the ultimate performance will be provided by corefxlab APIs. For any new APIs, we should be snapping to corefxlab.

**Comment by jkotas** [comment]
Related issue: #972 . This can be up for grabs. (The usual best practices about small incremental easy to review PRs or good test coverage apply.)

**Comment by stephentoub** [comment]
This was fixed in 2.1.
