### ISSUE TITLE
Wrong encoding when using XmlTextWriter

### ISSUE THREAD

**Issue by SharpNoiZy** [dotnet/corefx#4638]
Hi, does anyone know how to do the following with .NET core?

```
using (XmlTextWriter sw = new XmlTextWriter(this.FilePath, new UTF8Encoding(false)))
            {
                sw.Formatting = Formatting.Indented;
                sw.Indentation = 1;
                sw.IndentChar = '\t';

                this.XmlDocument.WriteTo(sw);
            }
```

Kind regards

**Comment by dVakulen** [comment]
Hi, try this:
```javascript
            var xwSettings = new XmlWriterSettings 
            {
                Encoding = new UTF8Encoding(false),
                Indent = true,
                IndentChars = "\t"
            };
            using (XmlWriter xw = XmlWriter.Create(this.FilePath, xwSettings))
            {
                this.XmlDocument.WriteTo(xw);
            }

**Comment by venknar** [comment]
What should be the package that I need to include for referring XmlTextWriter ? I am getting the error - error CS0246: The type or namespace name 'XmlTextWriter' could not be found (are you missing a using directive or an assembly reference?)
I included the following in my project.json  "System.Xml": "4.0.0.0"

I am trying to build for .Net core

**Comment by krwq** [comment]
Hey @SharpNoiZy, is this question still valid?

**Comment by SharpNoiZy** [comment]
Sorry, the issue can be closed.

**Comment by deepak-khopade-isdr** [comment]
private void InitializeWriter()
        {

            var settings = new XmlWriterSettings();
            settings.Indent = true;
            settings.Encoding = new ASCIIEncoding();
            _stringBuilder = new StringBuilder();
            _writer = XmlWriter.Create(_stringBuilder, settings);
        }

still getting "utf-16"... please help.

**Comment by krwq** [comment]
@sepidehMS could you check if you can repro?

**Comment by deepak-khopade-isdr** [comment]
yes just working on the same now and not getting any results as expected.
running on .NET Core 1.1.0 on Ubuntu 16.04

**Comment by sepidehMS** [comment]
@deepak-khopade-isdr 

Strings are UTF-16, so writing to a StringBuilder you will always get UTF-16. To get the encoding you want, you can do this instead:

```
var settings = new XmlWriterSettings();
settings.Indent = true;
settings.Encoding = new ASCIIEncoding();
using (MemoryStream sw = new MemoryStream())
{
  XmlWriter _writer = XmlWriter.Create(sw, settings);
}
```

**Comment by deepak-khopade-isdr** [comment]
Thanks @sepidehMS. It works.
