### ISSUE TITLE
./build.sh doesn't work on CentOS

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefx#4650]
I set up a CentOS 7.1.1503 machine with the following steps:

1. Install a new VM using "Gen 1" in Hyper-V and using an .iso from http://isoredirect.centos.org/centos/7/isos/x86_64/CentOS-7-x86_64-DVD-1503-01.iso 
	- I had this mounted as a DVD drive
	- When installing the OS, make sure you don't use the default "minimal" because you don't even get networking enabled.  I used the "developer" option, which took a really long time.
2. Run software updates after installing the OS
3. sudo yum install -y libuuid-devel uuid-devel userspace-rcu-de bzip2 libicu-devel unzip openssl-devel libcurl-devel git clang libunwind-devel libxml2-devel python-devel libedit-devel libstdc++-static wget swig gcc cmake
4. Install Mono and Reference Assemblies:
	1. sudo rpm --import "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"
	2. sudo yum-config-manager --add-repo http://download.mono-project.com/repo/centos/ 
	3. sudo yum upgrade -y
	4. sudo yum install -y mono-complete referenceassemblies-pcl
5. add `fs.file-max = 100000` to /etc/sysctl.conf, and then run `sudo sysctl -p`.
6. Git clone corefx
7. `./build.sh`

And during the build, I got errors like the following:
```
  System.Private.Uri.CoreCLR -> /home/eerhardt/git/corefx/bin/Linux.AnyCPU.Debug/System.Private.Uri.CoreCLR/System.Private.Uri.dll
EXEC : dlopen failed to open the libcoreclr.so with error libunwind-x86_64.so.8: cannot open shared object file: No such file or directory [/home/eerhardt/git/corefx/src/System.Runtime/src/System.Runtime.CoreCLR.csproj]
/home/eerhardt/git/corefx/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00121/lib/partialfacades.targets(180,5): error MSB3073: The command ""/home/eerhardt/git/corefx/bin/obj/Linux.AnyCPU.Debug/ToolRuntime/corerun" "/home/eerhardt/git/corefx/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00121/lib/GenFacades.exe" -partialFacadeAssemblyPath:"/home/eerhardt/git/corefx/bin/obj/Linux.AnyCPU.Debug/System.Runtime.CoreCLR/PreGenFacades/System.Runtime.dll" -contracts:"/home/eerhardt/git/corefx/packages/System.Runtime/4.0.21-rc2-23523/ref/dotnet5.4/System.Runtime.dll" -seeds:"/home/eerhardt/git/corefx/packages/Microsoft.DotNet.CoreCLR/1.0.5-prerelease/lib/dnxcore50/mscorlib.dll;/home/eerhardt/git/corefx/bin/Linux.AnyCPU.Debug/System.Private.Uri.CoreCLR/System.Private.Uri.dll" -facadePath:"/home/eerhardt/git/corefx/bin/obj/Linux.AnyCPU.Debug/System.Runtime.CoreCLR/" -producePdb:false" exited with code 255. [/home/eerhardt/git/corefx/src/System.Runtime/src/System.Runtime.CoreCLR.csproj]
EXEC : dlopen failed to open the libcoreclr.so with error libunwind-x86_64.so.8: cannot open shared object file: No such file or directory [/home/eerhardt/git/corefx/src/System.Diagnostics.Debug/src/System.Diagnostics.Debug.csproj]
/home/eerhardt/git/corefx/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00121/lib/partialfacades.targets(180,5): error MSB3073: The command ""/home/eerhardt/git/corefx/bin/obj/Linux.AnyCPU.Debug/ToolRuntime/corerun" "/home/eerhardt/git/corefx/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00121/lib/GenFacades.exe" -partialFacadeAssemblyPath:"/home/eerhardt/git/corefx/bin/obj/Linux.AnyCPU.Debug/System.Diagnostics.Debug/PreGenFacades/System.Diagnostics.Debug.dll" -contracts:"/home/eerhardt/git/corefx/packages/System.Diagnostics.Debug/4.0.11-rc2-23523/ref/dotnet5.4/System.Diagnostics.Debug.dll" -seeds:"/home/eerhardt/git/corefx/packages/Microsoft.DotNet.CoreCLR/1.0.5-prerelease/lib/dnxcore50/mscorlib.dll" -facadePath:"/home/eerhardt/git/corefx/bin/obj/Linux.AnyCPU.Debug/System.Diagnostics.Debug/" -producePdb:false" exited with code 255. [/home/eerhardt/git/corefx/src/System.Diagnostics.Debug/src/System.Diagnostics.Debug.csproj]
  System.ComponentModel.Annotations -> /home/eerhardt/git/corefx/bin/Linux.AnyCPU.Debug/System.ComponentModel.Annotations/System.ComponentModel.Annotations.dll
```

Also, after those build errors, none of the tests pass during the build.  This is because the CoreCLR fails to initialize when running `./corerun xunit.console.netcore.exe` with the same error:

```
[eerhardt@localhost dnxcore50]$ pwd
/home/eerhardt/git/corefx/bin/tests/Linux.AnyCPU.Debug/System.Globalization.Tests/dnxcore50
[eerhardt@localhost dnxcore50]$ ./corerun xunit.console.netcore.exe
dlopen failed to open the libcoreclr.so with error libunwind-x86_64.so.8: cannot open shared object file: No such file or directory
```

**Comment by pgavlin** [comment]
There may not yet be an appropriate runtime package for CentOS. On Fedora I have to use the `BUILDTOOLS_OVERRIDE_RUNTIME` environment variable and point it to a runtime that I've cobbled together out of a complete local build of CoreCLR, a local build of the native components from a CoreFX, and NuGet packages for the CoreFX managed code. My command line currently looks something like `MONO_THREADS_PER_CPU=2000 BUILDTOOLS_OVERRIDE_RUNTIME=path/to/temptoolruntime ./build.sh`.

**Comment by joshfree** [comment]
As part of fixing this, the docs need to be updated @ https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md

**Comment by eerhardt** [comment]
@pgavlin - Thanks for the tip. That does appear to be the problem - we don't have a Runtime.centos.* NuGet package.

I was not able to get the build working using BUILDTOOLS_OVERRIDE_RUNTIME either through setting an environment variable, or by passing `/p:BUILDTOOLS_OVERRIDE_RUNTIME=path/to/temptoolsruntime`.  But I was able to copy my locally built corerun and *.so files into `/corefx/bin/obj/Linux.AnyCPU.Debug/ToolRuntime`, and was able to successfully get through `./build.sh /p:SkipTests=true` with no errors.

@ellismg @ericstj @chcosta - What is the plan for getting a CentOS Runtime package?  Looks like we will need that in order to get ./build.sh to work successfully on CentOS.

**Comment by ellismg** [comment]
We already publish these packages on myget (you can see them in the Gallery http://myget.org/gallery/dotnet-core).

I think what needs to happen here is the following:

1. We need to either add the centos RID to the project.json from the [tool runtime](https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json) from buildtools or move a copy of this into our repo like I did with the test-runtime so we don't need to take a buildtools update to add more RIDs.
2. Update build.sh to explicitly set the ToolNugetRuntimeId property to the correct RID when on CentOS.

Maybe @naamunds can look into this?

**Comment by eerhardt** [comment]
If I get a vote, I vote that we move the .json file into our repo instead of having to change it in buildtools, and then be dependent on a new buildtools version.

**Comment by naamunds** [comment]
I can take it, but I'm on vacation the rest of this week, and then the engineering infrastructure team is having a "double down focus" the following two weeks, so I probably won't have time to look at this until the week of 12/14.

**Comment by ellismg** [comment]
Nate, I assigned the issue to you, but I might end up poaching it if I have some downtime over the long weekend.

**Comment by jasonwilliams200OK** [comment]
> If I get a vote, I vote that we move the .json file into our repo instead of having to change it in buildtools, and then be dependent on a new buildtools version.

+1 :+1: 

Also the default option should be somewhat flexible IMO, like coin the RID at runtime with a warning (preferably emit as warning colored `[0;33m (yellow)`) that `system is not officially supported, RID xxx auto-generated`. This way if someone tries to build on Arch, Gentoo or some other unsupported distro, they get through the build step without overrides. 
*(arch and gentoo are probably not a good example, as they are considered as experienced / power-user distros according to [wikipedia](https://en.wikipedia.org/wiki/Linux_distribution#Installation-free_distributions_.28live_CD.2FUSB.29) and those guys don't usually fancy easy installation experience! :smile:)*

**Comment by naamunds** [comment]
This issue should now be fixed.
