### ISSUE TITLE
Add "Windows Server 2008 R2 Enterprise (Server Core Installation)" CI / Rolling Build

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#4653]
We're currently testing NT 6.1+ versions of full client and server windows.  We need to also add an NT 6.1 Server Core installation to Jenkins outer loop.

https://en.wikipedia.org/wiki/Server_Core
https://msdn.microsoft.com/en-us/library/dd184075.aspx

/cc @Chrisboh @mmitche @markwilkie @leecow

**Comment by ellismg** [comment]
We'll likely run into many of the same issues that we hit in #4779 with respect to getting the worker machines talking to Jenkins.

**Comment by mmitche** [comment]
@ellismg I think we'll take the approach of doing the test runs in Helix (triggered from Jenkins)

**Comment by joshfree** [comment]
moving to rc2 per offline discussions

**Comment by joshfree** [comment]
@Priya91 can you please pick this one up?  This will be similar to https://github.com/dotnet/corefx/issues/4779

**Comment by Priya91** [comment]
Going through the server core installation docs, it is just server with GUI feature turned off. I think we can add this to the Helix graph instead of Jenkins, since the win apis is not changing with respect to .NET Core. @ellismg What do you think?

**Comment by ellismg** [comment]
@Priya91 Sounds like a good idea to me.

**Comment by joshfree** [comment]
I'm also fine with this.  Another approach is to switch one of our existing CI windows runs over to a servercore based installation

**Comment by joshfree** [comment]
Closing this issue as we have since added Server Core coverage to Helix nightly test runs
