### ISSUE TITLE
Add Debian 8.2 (Jessie) CI / Rolling Build

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#4656]
We should have a DebianStable Jenkins outerloop build & test.  The current stable version is 8.2 (Jessie)  https://hub.docker.com/_/debian/.  We'll need to upgrade this about once per year when newer Debian stable releases are available.

https://wiki.debian.org/DebianReleases

/cc @mmitche @leecow @dleeapho @ellismg @chcosta

**Comment by naamunds** [comment]
Debian CI projects have now been added to Jenkins.  Links to them have been added to the READMEs in both CoreCLR and CoreFX.

Debian CI jobs are currently only being run for changes to master and not for PRs.  It would be a fairly easy change to turn on the CI projects for PRs if we decide to do that.
