### ISSUE TITLE
NumberFormatInfoNumberGroupSizes.TestNumberGroupSizesLocale failing on OS X

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4667]
```
20:31:33    System.Globalization.Tests.NumberFormatInfoNumberGroupSizes.TestNumberGroupSizesLocale(locale: "ur-IN") [FAIL]
20:31:33       Assert.Equal() Failure
20:31:33       Expected: Int32[] [3]
20:31:33       Actual:   Int32[] [3, 2]
20:31:33       Stack Trace:
20:31:33             at System.Globalization.Tests.NumberFormatInfoNumberGroupSizes.TestNumberGroupSizesLocale(String locale)
```

**Comment by eerhardt** [comment]
This test passes successfully on my El Capitan machine.  It looks like this culture data differs between Yosemite and El Capitan.  We should be in the process of moving to El Capitan with #4654.

I think we have the following options:
1. just disabling this test until #4654 is fixed (i.e. we move to El Capitan).
2. write some test code to figure out if we are on El Capitan or Yosemite, and change the expected value based on the OS X version.
3. code to Yosemite now, have it fail for anyone running El Capitan locally.  Then switch it later once #4654 is fixed.

I think I'm in favor of the first option.
@stephentoub - do you have any opinion?

**Comment by stephentoub** [comment]
If we're going to upgrade imminently and this issue will simply go away as part of the upgrade, I'm fine with (1).  Thanks.
