### ISSUE TITLE
XML parsing fails in dnx451 but passes in dnxcore50

### ISSUE THREAD

**Issue by acastaner** [dotnet/corefx#4668]
I'm the maintainer of a library that provides C# bindings for the MusicBrainz API in DNX (it's a fork of a previous project). It's open source an available there: https://github.com/ribandelle/MusicBrainz.DNX

While I was porting and using the library I noticed that some of the XML responses would crash when the application was running from the dnx451 profile, but not when using the dnxcore50 profile. An example of an XML response that crashes is this one: http://musicbrainz.org/ws/2/artist/?query=Metallica 

But other responses don't crash at all, like this one: http://musicbrainz.org/ws/2/artist/?query=Lofofora

According to the W3C XML Validator, both responses are valid XML (just a warning that there's no doctype): 
http://validator.w3.org/check?uri=http%3A%2F%2Fmusicbrainz.org%2Fws%2F2%2Fartist%2F%3Fquery%3DMetallica

http://validator.w3.org/check?uri=http%3A%2F%2Fmusicbrainz.org%2Fws%2F2%2Fartist%2F%3Fquery%3DLofofora

The error I get happens here:

```
public static T Find<T>(string query, int limit, int offset, string part)
    {
      var serializer = new XmlSerializer(typeof(T));

      try
      {
        var o = Get("http://musicbrainz.org/ws/2/" + part + "/?query=" + query + LimitOffsetToString(limit, offset));
        {
          return (T)serializer.Deserialize(o.CreateReader());
        }
      }
      catch (Exception ex)
      {
        return default(T);
      }
    }
```
When the Deserialize part of the code is reached, the catch is triggered and the exception says `There is an error in XML document (0, 0)`. The stacktrace is the following:

`   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   at MusicBrainz.Help.Find[T](String query, Int32 limit, Int32 offset, String part) in D:\GitHub\MusicBrainz.DNX\MusicBrainz.DNX\Help.cs:line 111`

I have created a small console program that illustrates that issue. It's available here: https://github.com/acastaner/xmlparsing.git (make sure to use the "debug" branch). I haven't bundled the library in that program, you'll need to also clone the MusicBrainz.DNX repo. Also make sure to clone the debug branch as I have added an "ex" Exception object in the catch so you can see the details of the exception.

If you run that console program with dnx451 it WILL crash when trying to parse the Metallica response, but it will NOT crash if you run it with a dnxcore50 profile. Note that I'm using Windows 10 build 10586 but I've also reproduced the issue on Linux (Ubuntu and CentOS).

It *seems* to me that only responses with a larger body will crash. Metallica triggers the crash, but so does "Queen" for instance. Artists with a shorter content response seem to never crash. Just a thought, maybe it's unrelated.

**Comment by acastaner** [comment]
Just wondering if the fact that you assigned this to the RC2 milestone means you reproduced the issue?

**Comment by khdang** [comment]
@acastaner Thanks for letting us know about this. I'm able to reproduce the issue. So far I see the crash whenever artist data has a 'tag' element with value "-1" in artist's 'tag-list'. We will investigate to understand the cause.

**Comment by khdang** [comment]
@acastaner I understand that in MusicBrainz.DNX library the ArtistData's TagList property is a list of GTag element, whose 'count' is a byte property, therefore it cannot take negative value such as "-1". 

The XmlSerializer in dnxcore50 must have a more tolerating logic that makes it work. In this scenario the type of 'count' property should be changed to a suitable type if you want to use "-1" value with them.

**Comment by acastaner** [comment]
Thanks for the details @khdang. I will see what is the best course of action to fix the MusicBrainz.DNX library. I think it would be interesting to investigate the difference of behavior between dnxcore and .net 4.5.1.

**Comment by khdang** [comment]
@acastaner The difference is at https://github.com/dotnet/corefx/blob/master/src/System.Xml.XmlSerializer/src/System/Xml/Serialization/XmlSerializationReaderILGen.cs#L890. In dnxcore byte is read as Int16 which I think is to be more tolerant to the payload values.
