### ISSUE TITLE
RequireAttribute ignored

### ISSUE THREAD

**Issue by ducalai** [dotnet/corefx#4669]
I have a class with an integer property decorated with [Required] attribute. When I use it within an ASP.NET 5 application MVC controller as a parameter in a Post method accepting json, RequiredAttribute seemed to be ignored when property is not contained in JSON. Model deserialized in controller method contains UserId with default property value 0 for an Int32 and is therefore valid.

If the RequiredAttribute was not ignored, model should not be deserialized and should be null, right?

I am using ASP.NET 5 RC1

Here is my code:

JSON:
```
{
     "Token" : "abcd" 
}
```

Model:
```
[DataContract]
public class MyClass
{
     [Required]
     [DataMember]
     public int UserId { get; set; }
 
     [DataMember]
     public string Token { get; set; }
}
```
MVC Controller:
```
[HttpPost]
public async Task MyMethod([FromBody][Required] MyClass model)
{
     if (!ModelState.IsValid || model == null)
          throw new HttpResponseException(400);
     
     await ...
}
```
Thanks for your help
Alain

**Comment by divega** [comment]
This issue was moved to aspnet/Mvc#3971

**Comment by joshfree** [comment]
Closing corefx issue as this has been migrated to  aspnet/Mvc#3971 per @divega
