### ISSUE TITLE
DLR does not respect InternalsVisibleTo for anonymous types

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/corefx#4672]
In full .NET, anonymous types are accessible via DLR across assembly boundaries if an `InternalsVisibleTo` attribute is present. This behavior is not the same in CoreCLR. Instead, a `RuntimeBinderException` is thrown.

```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'object' does not contain a definition for 'xxxx'
```

Consider the following scenario:

In assembly ConsoleApp:

``` c#
    public class Program
    {
         public static void Main()
         {
            var list = new List<object>();
            list.AddGreeting("Hello world");
            dynamic item = list[0];
            Console.WriteLine(item.Greeting); // throws in CoreCLR. Prints "Hello world" in full .NET
         }
     }
```

In assembly GreetingLibrary:

``` c#
[assembly: InternalsVisibleTo("ConsoleApp")]

public static class ListExtension
{
    public static void AddGreeting(this List<object> source, string greeting)
    {
        source.Add(new { Greeting = greeting });
    }
}
```

In .NET 4.5.1, this console application will print "Hello world" but in CoreCLR this application throws an exception.

Full repro project: 
[test-dlr-bug-master.zip](https://github.com/dotnet/corefx/files/402776/test-dlr-bug-master.zip)

**Comment by Eilon** [comment]
Note: This is blocking some EntityFramework scenarios.

**Comment by natemcmaster** [comment]
Fortunately there simple workaround: just don't use anonymous types if they are potentially used outside the assembly. (See https://github.com/aspnet/EntityFramework/pull/3898)

**Comment by Eilon** [comment]
@natemcmaster I would recommend avoiding using anonymous types entirely within our product codebase (in tests is fine). Anonymous types can produce many surprises.

**Comment by gkhanna79** [comment]
@jaredpar This looks like a Roslyn issue - Can you please route this?

**Comment by karelz** [comment]
The is by design - .NET Core reflection is more restrictive.
