### ISSUE TITLE
Add: BitConverter.SingleToInt32Bits and Int32BitsToSingle

### ISSUE THREAD

**Issue by AlexGhiondea** [dotnet/corefx#4673]
### Migrated from https://github.com/dotnet/coreclr/issues/832

To match the existing `DoubleToInt64Bits` and `Int64BitsToDouble`. This is important for binary serialization tools to get hold of the underlying value without requiring unsafe themselves, which may not be accepted.

Example usage: IO / sockets tools, raw protocol tools, network libraries, serialization tools.

## Existing 64-bit API

    public static long BitConverter.DoubleToInt64Bits(double value);
    public static double BitConverter.Int64BitsToDouble(long value);

However, no 32-bit api exists

## Proposed 32-bit API

To mimic existing API:

    public static int BitConverter.SingleToInt32Bits(float value);
    public static float BitConverter.Int32BitsToSingle(int value);

## Rationale and Usage

Exactly the same as pre-existing 64-bit API:

- caller can populate an `int` (perhaps via shift ops and network access / stream, perhaps via raw memory access), and force it to a `float`, for example during deserialization
- caller can consume a `float` and force it to an `int` (perhaps for use on network access / stream via shift, perhaps via raw memory access), for example during serialization

## Details

To follow same rules and conventions as the existing 64-bit api, which is to say: uses straight unsafe cast - does not explicitly consider machines where integer and floating-point endianness are different (integer big-endian, floating-point little-endian), but is fine on both big-endian and little-endian machines - in reality the endianness matches. To emphasise: there is nothing in here that is different from the expectations of the existing 64-bit api. It would be inconsistent to have the 32-bit API operate with different expectations to the 64-bit api, and it would be a breaking change to alter the expectations of the existing 64-bit api.

## Pull Request

A pull request is available with the proposed implementation (comments etc based on the existing 64-bit API): https://github.com/dotnet/coreclr/pull/833

## Issues

None known; not a breaking change, and no overload resolution issue since uniquely named static non-extension methods.

## Discussion Point

Possible doubt over relevancy of comments and assertion. This is addressed separately in https://github.com/dotnet/coreclr/issues/834

**Comment by CodesInChaos** [comment]
I'd prefer if this method (and its 64 bit equivalent) behaved as if float and integer had the same endianness, even on those machines where this endianness differs.

While this changes the contract for the existing method, that shouldn't break existing code, since the CLR doesn't support such an architecture yet.

**Comment by Petermarcu** [comment]
@AlexGhiondea @weshaggard , Any reason we can't add this API and get the code merged into a version of netcoreapp? Looks like its approved and the PR is sitting in the coreclr repo...

**Comment by jkotas** [comment]
API added in https://github.com/dotnet/coreclr/pull/5492

**Comment by jkotas** [comment]
Covered by https://github.com/dotnet/corefx/issues/1151

**Comment by drauch** [comment]
Please include in netstandard!

**Comment by svick** [comment]
@iq2luc @drauch This API is proposed to be added to .Net Standard 2.1 by https://github.com/dotnet/standard/pull/823.
