### ISSUE TITLE
Proposal: System.Threading.Tasks.Task should provide a static property returning Task.FromResult(0)

### ISSUE THREAD

**Issue by SetTrend** [dotnet/corefx#4689]
Very often I see this kind of code:

```c#
return Task.FromResult<object>(null);
```

It's always used when the interface has been defined for asynchronous operation but the implementation doesn't call any asynchronous member function.

Due to the vast occurance of this kind of code I'd like to propose to add a static, read-only property to the `System.Threading.Tasks.Task` class returning `Task.FromResult(0)`.

I suggest this static member to be called something like `Empty`, `Null`, or (my preferred choice:) `Void`.

This would result in code like this:
```c#
return Task.Void;
```

**Comment by stephentoub** [comment]
How would this differ from https://msdn.microsoft.com/en-us/library/system.threading.tasks.task.completedtask(v=vs.110).aspx ?

**Comment by zabulus** [comment]
I think difference in ```TResult``` type. Though, not proposed ```Void``` type or ```CompletedTask``` don't expose it.

**Comment by stephentoub** [comment]
I thought the request was for a non-generic Task, and the examples were just using the generic FromResult as an example implementation. @SetTrend?

**Comment by SetTrend** [comment]
That's strange. I don't get this property from Intellisense in a .NET 4.5.2 project:

![fromresult](https://cloud.githubusercontent.com/assets/9283914/11430366/b31b283a-9485-11e5-8f65-097d670aaf28.png)

**Comment by stephentoub** [comment]
It was added in .NET 4.6.

**Comment by SetTrend** [comment]
Ah, I see. The MSDN article stated v4.5, too.

OK then, case closed :smiley:

**Comment by stephentoub** [comment]
:smile:
