### ISSUE TITLE
Redundant checks in KeyedCollection<,> classes

### ISSUE THREAD

**Issue by ViIvanov** [dotnet/corefx#4691]
In methods [Contains](https://github.com/dotnet/corefx/blob/49b8925bcf2bd1bd742915fe2f673b153dc74942/src/System.ObjectModel/src/System/Collections/ObjectModel/KeyedCollection.cs#L91) and [Remove](https://github.com/dotnet/corefx/blob/49b8925bcf2bd1bd742915fe2f673b153dc74942/src/System.ObjectModel/src/System/Collections/ObjectModel/KeyedCollection.cs#L131) we have a checks
```cs
            if (key == null)
            {
                throw new ArgumentNullException("key");
            }

            // …

            if (key != null) // <-- this "if" is redundant because we checked key == null above
            {
                // …
            }
```
Should this be fixed?

**Comment by JonHanna** [comment]
It's the
