### ISSUE TITLE
Documentation: request fix the arrows in standard-platform.md

### ISSUE THREAD

**Issue by mgravell** [dotnet/corefx#4702]
Ref: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md

The current unicode character used doesn't render on Chrome on Win 10 (UK English), and possibly a lot of other configurations - making it hard to understand the tables. Fonts are tricky, but there's the handy `&rarr;` that would look almost identical, and would render just about everywhere.

Would be happy to submit a PR if it helps.

**Comment by davidfowl** [comment]
PR welcome

**Comment by mgravell** [comment]
@davidfowl done and done
