### ISSUE TITLE
Public Surface of System.Linq.Expressions.Expression exposing too much?

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#4722]
In the code base, the methods [`DebugView`](https://github.com/dotnet/corefx/blob/master/src/System.Linq.Expressions/src/System/Linq/Expressions/Expression.cs#L222), [`ReturnReadOnly<T>`](https://github.com/dotnet/corefx/blob/master/src/System.Linq.Expressions/src/System/Linq/Expressions/Expression.cs#L245), [`ReturnReadOnly`](https://github.com/dotnet/corefx/blob/master/src/System.Linq.Expressions/src/System/Linq/Expressions/Expression.cs#L263), [`ReturnObject<T>`](https://github.com/dotnet/corefx/blob/master/src/System.Linq.Expressions/src/System/Linq/Expressions/Expression.cs#L276), [`RequiresCanRead`](https://github.com/dotnet/corefx/blob/master/src/System.Linq.Expressions/src/System/Linq/Expressions/Expression.cs#L281), [`RequiresCanRead` (another overload)](https://github.com/dotnet/corefx/blob/master/src/System.Linq.Expressions/src/System/Linq/Expressions/Expression.cs#L286), are all public.

They are not documented, nor public in any of the other .Net versions. I can't see any trace of a decision to make them public here, and the blame record suggests they were imported as such. With the possible exception of `DebugView`, they don't seem particularly useful to outside code or if they are they should perhaps be defined elsewhere. Also, `RequiresCanWrite` remains private and should surely be public if `RequiresCanRead` is.

This looks like it was introduced by accident in a refactoring of some of these methods into `ExpressionUtils` that happened in between the release of .NET 4.6 and the code being brought into dotnet/corefx (or in a different branch, etc.).

If I'm correct in deducing that their access is a mistake, removing the access to them would be a breaking change, but by the same token should perhaps be done as soon as possible before more dependencies on them appear.

**Comment by afscrome** [comment]
On many occasions i'd have found it useful for DebugView to be public.  Mainly this was in automated test scenarios, where it would be beneficial to dump the DebugView upon a test failure for further investigation.

**Comment by JonHanna** [comment]
Yes, as it was the PR to "fix" (still not clear if this is a bug) had to change one test to use reflection.

On the other hand, using reflection isn't a big deal in some debugging scenarios (any where you are peeping in via reflection anyway), so maybe just being accessible that way suffices.

On the gripping hand, if this **is** a bug, and if `DebugView` is considered useful enough to have public anyway, should it be as it currently is?

**Comment by HellBrick** [comment]
I think public `DebugView` would be a nice thing to have. It's quite useful to log the expression pseudo code when something goes wrong in the generated code, so I'd welcome an easier way to do this.

**Comment by JonHanna** [comment]
If I'm correct in this being a bug, I think the best approach is to fix it, and then consider deliberately bringing back `DebugView` as an API change. Of course, it'd be simple to just leave that as part of the fix, but if it is a bug then the API was changed without the change being considered.

**Comment by JonHanna** [comment]
cc @bartdesmet

**Comment by bartdesmet** [comment]
I'd suggest splitting the discussion into one about `DebugView` as a potential API addition and retaining this one to discuss the increased public API surface which seems like an undesirable change. Not sure about the history of that accessibility change; my best guess would be that there could have been some issue with `InternalsVisibleTo` to another assembly that had to use these (maybe DLR stuff). Still seems strange, maybe @VSadov can recollect the history?

**Comment by bartdesmet** [comment]
On the topic of `DebugView`, I think it's useful but it lacks a good extensibility story. I ran across this when prototyping extended expression tree node support in the C# compiler; see https://github.com/bartdesmet/ExpressionFutures/blob/master/CSharpExpressions/Docs/Debugging.MD for some info (disclaimer: work in progress).

In particular, extension nodes are always reduced by `DebugView` which is quite aggressive when trying to inspect such nodes, especially when using `DebugView` for asserts of the shape of a tree. In addition, it lacks detailed information about nodes which is often useful for inspection, so one still has to look at the various internal properties of the nodes in many cases to figure out what's going on.

My proposal would be to invest in an extensible `DebugView` mechanism that can be leveraged by extension nodes, while also adding more detailed info. It may just be quite a bit of work for a feature that has limited use, but having a vibrant community here creates more potential for sure :-).

What I have done right now for the prototyping of the C# expression extensions is not particularly cute given it's using XML as the format (and drags in another fat assembly dependency), but it was merely a pragmatic choice to unblock my debugging needs, and to show what an extensible `DebugView` *could* look like.

Also note that my current approach over there is putting this new `DebugView` capability in a separate assembly, so it becomes pay for play. At runtime it's not needed, but at development time it's useful to have the additional dependency around. It's worth pointing out that the current `DebugView` is really meant to be read from the debugger proxy specified in `DebuggerTypeProxy`, for use by the IDE.

**Comment by JonHanna** [comment]
>  It's worth pointing out that the current DebugView is really meant to be read from the debugger proxy specified in DebuggerTypeProxy, for use by the IDE.

I think that's the most pertinent thing in the short term.

**Comment by VSadov** [comment]
DebugView is used by debug proxies (see  BinaryExpressionProxy). There was similar proxy for DynamicExpression, but then  DynamicExpression was moved to a separate assembly so that forced DebugView to become public.

It appears that DynamicExpressionProxy no longer exists so DebugView no longer needs be public.

**Comment by VSadov** [comment]
I think extensible DebugView is a good idea. 
As I remember at some point there was an expression tree visualizer - a VS extension which would paint tree-like shapes with collapsible children nodes. Not sure if that was a sample or it actually shipped...

ExpressionTrees could get complex enough that specialized visualization could be very helpful at debug time.
