### ISSUE TITLE
[.Net Native] XmlTextAttribute on a primitive type property in struct seems not to be supported

### ISSUE THREAD

**Issue by shanhongyue** [dotnet/corefx#4724]
This problem only occur when the c# code was compiled by .Net Native tool.

If there's a property in a class. This property is a struct. In this struct, there's a primitive type property, such as string. If there's an XmlTextAttribute on this property, the xml serialization and deserialization will go wrong.

Here is the code:
It is a piece of code from a UWP App.

    [XmlRoot("库")]
    public class LibraryPropertyFile
    {
        [XmlElement("库名称")]
        public FieldWithDateTime<string> Name { get; set; }
    }

    public struct FieldWithDateTime<T>//struct, not class.
    {
        //Here:
        [XmlText]
        public T Field { get; set; }

        [XmlAttribute("修改日期")]
        public DateTime DateTime { get; set; }
    }

//Serialize:

                StorageFile libraryFile = ...;
                XmlSerializerNamespaces xmlSerializerNamespaces = new XmlSerializerNamespaces();
                xmlSerializerNamespaces.Add(string.Empty, string.Empty);
                XmlWriterSettings xmlWriterSettings = new XmlWriterSettings
                {
                    Encoding = new UTF8Encoding(false)
                };
                Stream libraryFileStream = await libraryFile.OpenStreamForWriteAsync();
                XmlSerializer serializer = new XmlSerializer(typeof(LibraryPropertyFile));
                XmlWriter xmlWriter = XmlWriter.Create(libraryFileStream, xmlWriterSettings);
                serializer.Serialize(xmlWriter, libraryPropertyFile, xmlSerializerNamespaces);
                xmlWriter.Flush();
                xmlWriter.Dispose();
                libraryFileStream.Flush();
                libraryFileStream.Dispose();

//Deserialize:

            StorageFile libraryFile = ...;
            Stream libraryFileStream = await libraryFile.OpenStreamForReadAsync();
            XmlSerializer libraryXmlSerializer = new XmlSerializer(typeof(LibraryPropertyFile));
            LibraryPropertyFile libraryPropertyFile = libraryXmlSerializer.Deserialize(libraryFileStream) as LibraryPropertyFile;
            libraryFileStream.Dispose();

Pay attention! In the Debug mode, the code is run on CLR, it works perfectly. But in the release mode, the code is compiled into native code. When it is going to Serialize or Deserialize, it crashs. 

But I can modify my code:

    public class FieldWithDateTime<T>//change from struct to class

And then, Compile it, it works perfectly.

So, if FieldWithDateTime is a class, the code can work both in Debug or Release mode, but if  FieldWithDateTime is a struct, the code can only work in Debug mode.

My develop platform: Windows 10 1511, Visual Studio 2015.

**Comment by SGuyGe** [comment]
@shanhongyue, I'm looking into this issue but wasn't able to repro the crash you mentioned. Could you please share out your repro project?

**Comment by shanhongyue** [comment]
I will write an example in several days.

**Comment by shanhongyue** [comment]
I write a demo:
https://github.com/shanhongyue/XmlSerializerBug

In this demo, there is a struct FieldwithDateTime, a class Library. In the class Library, there's a field, on which there's an attribute, XmlText.


If you use .net native tool chains to compile it and run it, it will crash.

**Comment by SGuyGe** [comment]
Thanks. I can repro the crash issue with your repro. We'll look into it.

**Comment by SGuyGe** [comment]
We've confirmed this is a bug in .NET Native compiler. We have fixed it and the fix will be included in a future .NET Native update (post update 2).

**Comment by shanhongyue** [comment]
Well done!
