### ISSUE TITLE
ImmutableList<T> can't be used with T's from collectible assemblies

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4726]
See the discussion at https://github.com/dotnet/corefx/commit/b460c2701270b4c8ff8e6aeebd8a4071b283ceda#commitcomment-14671045.

```C#
using System;
using System.Collections;
using System.Collections.Immutable;
using System.Linq;
using System.Reflection;
using System.Reflection.Emit;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            var assembly = AppDomain.CurrentDomain.DefineDynamicAssembly(new AssemblyName("dynamic_assembly"), AssemblyBuilderAccess.RunAndCollect);
            var module = assembly.DefineDynamicModule("dynamic");
            var typeBuilder = module.DefineType("Dummy");
            typeBuilder.DefineDefaultConstructor(MethodAttributes.Public);
            var dummType = typeBuilder.CreateType();
            var createMethod = typeof(ImmutableList).GetMethods().Where(m => m.Name == nameof(ImmutableList.Create) && m.GetParameters().Length == 0).Single().MakeGenericMethod(dummType);
            var list = (IEnumerable)createMethod.Invoke(null, null);
            var addMethod = list.GetType().GetMethod("Add");
            list = (IEnumerable)addMethod.Invoke(list, new object[] { Activator.CreateInstance(dummType) });
            // Will crash here
            foreach (var item in list)
                Console.WriteLine(item);
        }
    }
}
```
fails with:
```
Unhandled Exception: System.TypeLoadException: Collectible type 'System.Collections.Immutable.AllocFreeConcurrentStack`1[System.Collections.Immutable.SecurePooledObject`1[System.Collections.Generic.Stack`1[System.Collections.Immutable.RefAsValueType`1[System.Collections.Immutable.ImmutableList`1+Node[Dummy]]]]]' may not have Thread or Context static members.
   at System.Collections.Immutable.SecureObjectPool`2.TryTake(TCaller caller, SecurePooledObject`1& item)
   at System.Collections.Immutable.ImmutableList`1.Enumerator..ctor(Node root, Builder builder, Int32 startIndex, Int32 count, Boolean reversed)
   at System.Collections.Immutable.ImmutableList`1.GetEnumerator()
   at System.Collections.Immutable.ImmutableList`1.System.Collections.IEnumerable.GetEnumerator()
   at ConsoleApplication1.Program.Main(String[] args) in C:\Users\stoub\Documents\Visual Studio 2015\Projects\ConsoleApplication26\Program.cs:line 24
```

**Comment by AArnott** [comment]
@stephentoub Should we also file an issue to track alleviating the CLR limitation?

**Comment by stephentoub** [comment]
> Should we also file an issue to track alleviating the CLR limitation?

Good suggestion. Done: https://github.com/dotnet/coreclr/issues/2191

**Comment by ellismg** [comment]
Just so it's clear, is the plan here to move away from `[ThreadStatic]` until dotnet/coreclr#2191 is addressed?

**Comment by AArnott** [comment]
@ellismg If I recall correctly, `[ThreadStatic]` provided a significant perf improvement over what it had before (which I think was locks based). There may be a 3rd option (or a twist on a prior solution) that can keep perf up while avoiding `[ThreadStatic]`, I don't know. I can't promise time (yet) to investigate yet.

**Comment by azeno** [comment]
I'd like to verify that the initial issue I had in my application is indeed fixed, but I don't know whether or not this commit is already included in your daily builds. Or in other words how do the version stamps of the daily built NuGet packages correlate with this repository?

**Comment by stephentoub** [comment]
My expectation is that it'll be in tomorrow's build (http://myget.org/gallery/dotnet-core).

@chcosta, can you share details on how one can correlate the builds to a particular commit or time or whatnot?

**Comment by azeno** [comment]
Using today's build (v1.2.0-rc2-23714) the issue is still present - could it be that only the branch releases/1.0.0-rc2 gets built (which is 4 days behind master)? Would make sense then...

**Comment by stephentoub** [comment]
That's actually yesterday's build and does not include the fix (I double-checked by looking at the IL).

**Comment by stephentoub** [comment]
@azeno, the build at http://www.myget.org/F/dotnet-core/api/v2/package/System.Collections.Immutable/1.2.0-rc2-23715 has the fix in it.

**Comment by chcosta** [comment]
The package description has source info in it...

TFS ID: 1565242, GitHub SHA: https://github.com/dotnet/corefx/tree/9546ca7a50eeb91dd9a168d32a5a4f2fef4e170b

**Comment by azeno** [comment]
@stephentoub Thanks a lot! Works perfectly!
