### ISSUE TITLE
FileVersionInfo.GetVersionInfo(string fileName) fails on Unix with ArgumentException

### ISSUE THREAD

**Issue by mjrousos** [dotnet/corefx#4727]
Calling FileVersionInfo.GetVersionInfo(string) on Unix (passing valid input) results in the following exception:
```
System.ArgumentException: Argument must be between 0 and 3.
Parameter name: fieldCount
   at System.Version.ToString(Int32 fieldCount)
   at System.Diagnostics.FileVersionInfo.LoadManagedAssemblyMetadata(MetadataReader metadataReader)
   at System.Diagnostics.FileVersionInfo.TryLoadManagedAssemblyMetadata()
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
 ```
The error seems to be in [FileVersionInfo.Unix.cs@131](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.FileVersionInfo/src/System/Diagnostics/FileVersionInfo.Unix.cs#L131) which explicitly calls Version.ToString with an argument '4' despite the exception message saying that the argument should fall in the range [0-3].

**Comment by stephentoub** [comment]
The problem is that 4 is only valid when all of the components of the version are available.  If no Revision was supplied and it's set to -1, then ToString(4) is invalid.  I'll fix it.  Thanks.

**Comment by stephentoub** [comment]
@mjrousos, just for the record, how was the assembly created that this failed with?  I'm just wondering how it got a version with fewer than the four parts.

**Comment by mjrousos** [comment]
@stephentoub, the assembly's csproj is [here](https://github.com/mjrousos/dotnet-apiport/blob/ApiPortCore/src/ApiPort/ApiPort.Core.csproj) (the version attribute is actually set by [this targets file](https://github.com/mjrousos/dotnet-apiport/blob/ApiPortCore/dir.targets)). But, it really boils down to just a simple use of the AssemblyFileVersion attribute equivalent to something like this:

```C#
using System;
using System.Reflection;
using System.Diagnostics;

[assembly: AssemblyFileVersion("1.2.3")]
class Program
{
    static void Main(string[] args)
    {
        FileVersionInfo fvi = FileVersionInfo.GetVersionInfo(typeof(Program).Assembly.Location);
        Console.WriteLine(fvi.FileVersion);
    }
}
```

**Comment by stephentoub** [comment]
Interesting, thanks.  Makes complete sense.
