### ISSUE TITLE
Switch Socket.Select to use poll rather than select in the implementation

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4728]

**Comment by ericeil** [comment]
@stephentoub or @pgavlin, can one of you write up a little background info on this issue?

**Comment by stephentoub** [comment]
Basically, ```select``` is limited in scale to the number of file descriptors that can fit in a ```fd_set```, which is basically a bit mask with 1s set for the file descriptor numbers to include; that limits how many file descriptors can be used with it, but it also limits what file descriptors can be used (any file descriptor value than the number of bits in fd_set can't be used)... it should be rare to bump up against this, but it's possible.  In contrast, ```poll``` takes an array of the file descriptor values (```struct pollfd *fds, nfds_t nfds```), so any number of any value file descriptors can be used.

There are other differences, but those are what drove the issue, as a customer hit up against this area with I believe what were some customizations to their standard libraries and maybe kernel.  @pgavlin had looked into it further and may have some more background.

**Comment by ericeil** [comment]
Moving this to the Future milestone; we can reprioritize if there is user demand.

**Comment by stephentoub** [comment]
We should reconsider fixing this now... I just hit it with #6833 (more specifically I hit it with Socket.Poll, which was using select under the covers).
