### ISSUE TITLE
Automated build fails to report syntax errors

### ISSUE THREAD

**Issue by lexware** [dotnet/corefx#473]
As shown by issue #471 the automated build fails to report syntax errors.

**Comment by sgtfrankieboy** [comment]
Might I ask which IDE/Application you used to make these changes?

Because Visual Studio reports the error `A get or set accessor expected` without building. Same error gets thrown when I build the project using `build` from the command line.

**Comment by mikedn** [comment]
Compilation actually failed on the build server as can be seen in the log: http://corefx-ci.cloudapp.net/jenkins/job/dotnet_corefx_windows_prtest/163/console

10:15:55 System\Collections\Specialized\StringDictionary.cs(67,13): error CS1014: A get or set accessor expected [C:\Jenkins\workspace\dotnet_corefx_windows_prtest\src\System.Collections.Specialized\src\System.Collections.Specialized.csproj]

But the build was marked as success:

10:17:26     0 Warning(s)
10:17:26     1 Error(s)
10:17:26 Time Elapsed 00:04:03.01
10:17:27 Finished: SUCCESS

There's a bug somewhere in the build scripts...

**Comment by lexware** [comment]
I may have not used an ide, anyway this is about the automatic build not flagging build failed when there are syntax errors.

—

**Comment by weshaggard** [comment]
@mmitche How does Jenkins detect a successful build? Is it looking at the ErrorLevel coming out of build.cmd? If so perhaps my recent change to call findstr at the end to pull out the warnings/errors is what regressed this.

**Comment by weshaggard** [comment]
Thanks for filing the issue, it has been fixed with PR #477, in the v1.0 branch which will integrate into master later this week.
