### ISSUE TITLE
Update libssl minimum required version for Mac OS X

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#4737]
We're currently using a deprecated and unsupported version of OpenSSL on Mac (0.9.8).  We need to upgrade our minimum required version to a supported version 1.0.1/1.0.2.  This issue is tracking this upgrade; including updating the build server definitions; updating dev instructions; and updating the Mac end-user binary installer (TBD either requiring homebrew again or possibly using another provided libssl installer).

http://lists.apple.com/archives/macnetworkprog/2015/Jun/msg00025.html
>Subject: Re: OpenSSL -> Secure Transport for libevent2
From: "Quinn \"The Eskimo!\"" <email@hidden>
Date: Mon, 15 Jun 2015 12:28:41 -0700
On 15 Jun 2015, at 11:11, John Pannell <email@hidden> wrote:

> Apple stopped shipping OpenSSL with OS X some time ago, citing lack of a stable API from version to version.

>It's a bit more subtle than that:

>o Apple deprecated its OpenSSL shared libraries a while back (with OS X 10.7).  That's because OpenSSL doesn't offer release-to-release binary compatibility, so we can't update the shared libraries to the latest OpenSSL without breaking all the existing clients.

>o At the same time we marked the OpenSSL headers in the OS X SDK as deprecated so you'd get deprecation warnings if you build with a deployment target of 10.7 or later.

>o With the latest OS X SDK we've removed the headers entirely, making it much harder to use the long-since-deprecated shared libraries.

>o We recommend that developers who need OpenSSL build their own copy of it and include that copy in their app.  Alternatively you can use native OS X APIs, like Secure Transport.

>Share and Enjoy

>Quinn "The Eskimo!"                    <http://www.apple.com/developer/>
>Apple Developer Relations, Developer Technical Support, Core OS/Hardware

Related issue https://github.com/dotnet/corefx/issues/3924

**Comment by bartonjs** [comment]
@mmitche This is what we talked about this morning... we'll need to get an OpenSSL 1.0.x on our Mac build machines so that System.Security.Cryptography.Native.dylib targets the right ABI.
```
brew install openssl
brew link --force openssl
```
Should put a good version of OpenSSL on the machine.

**Comment by bartonjs** [comment]
* Build server definitions
  * We did some ahead of time, then removed 0.9.8 support with #5240 and are fixing the failing machines as they surface.
* Dev instructions
  * https://github.com/dotnet/coreclr/pull/2559
* Installer
  * https://github.com/dotnet/cli/issues/674 is the closest that we have to that right now.
  * OpenSSL has no self-produced installer on OS X; Homebrew and MacPorts options both exist.

Closing this out since there's no apparent work remaining.
