### ISSUE TITLE
FileSystemWatcher.Dispose hangs on OSX

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/corefx#4738]
It seems that the FileSystemWatcher doesn't trigger on OSX. This makes [dnx-watch](https://github.com/aspnet/dnx-watch) unusable on CoreCLR. Side note: it works on Mono.

I will provide a simple repro soon but I wanted to open the bug so we can start tracking this because `dnx-watch` will need to become `dotnet-watch` for RC2 and we want it to work on OSX. For now you can repro by running `dnx-watch`

cc @glennc

**Comment by stephentoub** [comment]
Thanks, though this won't be actionable until you can share more details.

**Comment by victorhurdugaci** [comment]
Turns out that the issue is different but it's still the `FileSystemWatcher`. It hangs on `Dispose`.

Here's the simplest repro that I found (update the path in `XTask` when you run):

```
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace FileWatcherBug
{
    public class Program
    {
        public static void Main(string[] args)
        {
            XTask("1").Wait();
	        Console.WriteLine("done");
        }

        private static async Task<string> XTask(string s)
        {
            FileSystemWatcher watcher = new FileSystemWatcher("/Users/victorhurdugaci/dev/x");
            
            var tcs = new TaskCompletionSource<string>();

            FileSystemEventHandler callback = (sender, arg) => {
                Console.WriteLine("File changed: " + arg.FullPath);
                tcs.SetResult(arg.FullPath);  
            };
        
            watcher.Changed += callback;
            watcher.EnableRaisingEvents = true;
        
            Console.WriteLine("Waiting for a file to change...");
            var result =  await tcs.Task;
            
            Console.WriteLine("Disposing the watcher");
            watcher.Dispose();
            Console.WriteLine("Watcher disposed");
            
            System.Console.WriteLine("XTask done");
            return result;
        }
    }
}
```

Run the program using DNX CoreCLR and `touch` a file in the folder being watched.

The output:

```
$ dnx run
Waiting for a file to change...
File changed: /Users/victorhurdugaci/dev/x/x.txt
Disposing the watcher
```

And it hangs...

**Comment by sokket** [comment]
Looks like there's a problem calling CFRunLoopStop(...) from a different thread. I'm looking for a better way to enable graceful cleaning up now

**Comment by sokket** [comment]
Actually...I take that back, it doesn't look like a problem in the FSW. If I change your code to be this, things work as expected:

```C#
using System;
using System.IO.Testing;
using System.Threading;
using System.Threading.Tasks;

public class Program
{
    public static void Main(string[] args)
    {
        Console.WriteLine("Doing Work");
        DoWork().Wait();
        Console.WriteLine("Done");
    }

    public static async Task<string> DoWork()
    {
        var watcher = new FileSystemWatcher("/Test");
        Console.WriteLine("Created FSW");

        var are = new AutoResetEvent(false);

        FileSystemEventHandler callback = (sender, arg) => {
            Console.WriteLine("File changed: " + arg.FullPath);
            are.Set();
        };

        watcher.Changed += callback;
        watcher.EnableRaisingEvents = true;

        Console.WriteLine("Waiting for a file to change...");
        var result =  "foo";//await tcs.Task;
        are.WaitOne();

        Console.WriteLine("Disposing the watcher");
        watcher.Dispose();
        Console.WriteLine("Watcher disposed");

        System.Console.WriteLine("XTask done");
        return result;
    }
}
```


It looks like your problem is with the TaskCompletionSource object causing a deadlock :)

**Comment by stephentoub** [comment]
@sokket, the code worked fine on both Linux and Windows, so there's something different about OS X.

**Comment by stephentoub** [comment]
For example, with the code as written, when the event callback executes, it'll complete the TCS, which will invoke all of the continuations, which will continue to execute the remainder of the async method, which will end up calling watcher.Dispose.... so watcher.Dispose is being called from the same thread that's invoking the callback.  If that's the source of the problem, then the watcher needs to be changed to allow for watcher.Dispose to be called from an event callback, otherwise it's a problem regardless of TCS.

**Comment by sokket** [comment]
Ahh I see, that changes things entirely :) sorry about that! I see the problem now...since the TaskCompletionSource causes the Watcher to be disposed on it's own background thread, the cleanup routine is trying to wait for the Watcher background thread to complete it's self-cleanup by doing a ```Thread.Join(...)``` on...itself. I have a fix ready and will add a unit test to make sure this doesn't regress and then will put out a PR fixing this. Thanks for finding it!

**Comment by sokket** [comment]
Fix is out for PR (#4764)

**Comment by sokket** [comment]
That PR would not have adequately fixed the problem...pulling it and going to make a full-fledged fix that will solve the issue deterministically

**Comment by sokket** [comment]
PR 4781 should fix this issue

**Comment by sokket** [comment]
Fixed
