### ISSUE TITLE
What can/should a non-MS contributor put in a new file's license header?

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#4751]
The comment at https://github.com/dotnet/corefx/pull/3017#discussion_r38267245 which pointed to https://github.com/dotnet/coreclr/pull/1329#discussion_r36218185 led me to believe that the done thing was to put one's own name in copyright headers when creating a new file from scratch.

The comment at https://github.com/dotnet/corefx/pull/2401#issuecomment-159900223 suggests that it is not.

The combination leaves me not knowing what I should do if I want to contribute a PR which would involve new files.

(The discussion on that last comment got side-tracked slightly [my own fault] with the question of what would be the best policy for an open-source .Net to have. I want to know what I should put in a file header right now, if there's some unclear approaches and a clearly-allowed-today approaches, I'm happy to use the clearly-allowed-today one).

**Comment by davidsh** [comment]
cc: @stephentoub @richlander

**Comment by JonHanna** [comment]
I hate "bump" comments, but is there anything I can definitely put as the header if I submit a PR now with new files?

**Comment by JonHanna** [comment]
The recent license change would seem to have answered this, ".NET Foundation and Contributors" is both clearly allowable if it's what is in the license, and clearly appropriate for anyone to use since anyone falls under "and Contributors".
