### ISSUE TITLE
HttpClient doesn't respect HttpRequestMessage.Version

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4754]
e.g. if it's set to 1.0, the request still gets sent with a version 1.1

**Comment by davidsh** [comment]
Most of the underlying Windows stacks ignore the 1.0 version and send it 1.1 anyways.

**Comment by davidsh** [comment]
And Windows (WinHTTP) doesn't support 2.0 anyways right now.

**Comment by SidharthNabar** [comment]
@stephentoub - I agree with David. HTTP 1.0 is a very old version and has minimal usage as compared to 1.1. Even if we passed the version as 1.0 in the .NET layer, the underlying OS (at least in Windows) will send it as 1.1.

When we do enable HTTP 2.0, we should ensure that the 2.0 version gets plumbed down correctly.

**Comment by stephentoub** [comment]
It's up to you guys.  But it is a difference from HttpClient on desktop, and it's strange to me that there's an API for setting the version, 1.0 is a valid version according to the HTTP spec, but when the developer requests 1.0 it's ignored.

**Comment by sblackler** [comment]
Personally, I'd argue that there is a bug there. If we ask for version 1.0 give us 1.0, regardless of levels of usage.

**Comment by davidsh** [comment]
In terms of the HttpClient, yes, it is a bug in the Windows HttpClientHandler/WinHttpHandler in that it doesn't look/honor the `HttpRequestMessage.Version` property when constructing the request to be sent on the wire.

However, servers ARE NOT obligated to echo back a response using that precise version number.

Please note the RFC for HTTP:
http://tools.ietf.org/html/rfc7230

http versions are “<major>.<minor>”.  The model is that increments in minor are backward compatible.  That is, if an http/1.0 recipient sees a http/1.1 response then the response contains extra info that an 1.1 recipient may do something useful with but a 1.0 recipient will just ignore or just perform default actions (e.g. extra headers).

rfc7230:
>The minor version advertises the sender's communication capabilities even when the sender is only using a backwards-compatible subset of the protocol, thereby letting the recipient know that more advanced features can be used in response (by servers) or in future requests (by clients).
When an HTTP/1.1 message is sent to an HTTP/1.0 recipient [RFC1945] or a recipient whose version is unknown, the HTTP/1.1 message is constructed such that it can be interpreted as a valid HTTP/1.0 message if all of the newer features are ignored.
A server SHOULD send a response version equal to the highest version to which the server is conformant that has a major version less than or equal to the one received in the request.  A server MUST NOT send a version to which it is not conformant.
When an HTTP message is received with a major version number that the recipient implements, but a higher minor version number than what the recipient implements, the recipient SHOULD process the message as if it were in the highest minor version within that major version to which the recipient is conformant.

There is similar text in rfc2616 but rfc7230 is easier to read.
