### ISSUE TITLE
Method not found: 'System.Threading.Tasks.Task`1<System.Net.NetworkInformation.PingReply> System.Net.NetworkInformation.Ping.SendPingAsync(System.Net.IPAddress, Int32)'.

### ISSUE THREAD

**Issue by 00101010b** [dotnet/corefx#4760]
I think I found a bug in System.Net.NetworkInformation where PingReply is missing. You can find my source code [here](https://github.com/00101010b/PingTest1/blob/master/Controllers/HomeController.cs) on GitHub.

I get the following errors during build:

```
An unhandled exception has occurred: Method not found: 'System.Threading.Tasks.Task`1<System.Net.NetworkInformation.PingReply> System.Net.NetworkInformation.Ping.SendPingAsync(System.Net.IPAddress, Int32)'.
      System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<System.Net.NetworkInformation.PingReply> System.Net.NetworkInformation.Ping.SendPingAsync(System.Net.IPAddress, Int32)'.
```

**Comment by stephentoub** [comment]
What build are you using?

**Comment by 00101010b** [comment]
Hi Stephen,

Here is my version outputs:

```
 $ dnx --version
Microsoft .NET Execution environment
 Version:      1.0.0-rc1-16231
 Type:         CoreClr
 Architecture: x64
 OS Name:      Darwin
 OS Version:   10.11
 Runtime Id:   osx.10.11-x64
```

Hope this helps.

**Comment by 00101010b** [comment]
Modifying code actually fixed this issue. But another issue cropped up in the form of issue [#4672](https://github.com/dotnet/corefx/issues/4762). 

My [PingTest1](https://github.com/00101010b/PingTest1) source code is updated.

**Comment by mellinoe** [comment]
Hey @00101010b , is this issue now the same as the other one #4762? The title looks different but it sounds like that part was already resolved. Mind if I close this one out and track this with the other issue?

**Comment by 00101010b** [comment]
Hi @mellinoe, definitely not the same issue as #4762. I fixed it on my end by modifying my code (turned out I was calling Task and async wrong). You can go ahead and close this issue if you like.
