### ISSUE TITLE
System.Net.Http nuget package need depend on System.Security.Cryptography.X509Certificates

### ISSUE THREAD

**Issue by loqix** [dotnet/corefx#4767]
dotnet publish System.Net.Http can not work, it need System.Security.Cryptography.X509Certificates.

**Comment by davidsh** [comment]
@ericstj Can you please take a look at this?  This seems like a packaging issue.

**Comment by davidsh** [comment]
And FWIW, System.Net.Http binary does use X509Certificates in its implementation.

**Comment by ericstj** [comment]
>dotnet publish System.Net.Http can not work

@loqix can you please be more specific about what you meant by this?  Perhaps you were trying to publish without using the framework lineup package `Microsoft.NETCore.Platforms`.

**Comment by chcosta** [comment]
Closing issue.  @loqix , please feel free to re-open this issue with additional information if you continue to encounter problems.
