### ISSUE TITLE
PackUriHelper.Create does not work in corefx

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4774]
The original implementation of PackUriHelper had a static constructor that used UriParser.Register to add the part scheme:
http://referencesource.microsoft.com/#WindowsBase/Base/System/IO/Packaging/PackUriHelper.cs,685

That code doesn't exist in corefx, I assume because UriParser isn't public.  As a result, PackUriHelper.Create in corefx in System.IO.Packaging always fails with an exception.  It looks like there's zero test coverage for these Create methods.

cc: @EricWhiteDev, @cipop, @davidsh

**Comment by EricWhiteDev** [comment]
@stephentoub How did you find this?  Was someone actually using this method, and reported the issue, or was this found through getting higher code coverage.

These methods are some crud that was added to System.IO.Packaging (to no good effect I believe, but could be wrong) many, many years ago.  I presume that what happened is that some other internal team at Microsoft requested some functionality, and the System.IO.Packaging team added this stuff to the namespace.  However, these functions are not used by the Open XML SDK, and in my 8 years of doing Open XML stuff, I have never, even once, used this functionality.  I had noticed it there, but never had occasion to use it.

My strategy when creating the new version of System.IO.Packaging was to touch absolutely as little code as possible.  The net result is that we have a new library that is super compatible with the old one.  But I think it would be good to remove this functionality from System.IO.Packaging.  I would take the approach of ifdef it out, then if there happened to be someone who was using it, they could put it back in.  But I highly doubt it.  This will require some analysis and time on my part to determine exactly what to cull.  I am buried right now.  What is the time frame on this?

Or if these functions are actually being used, then need to fix them.

**Comment by stephentoub** [comment]
Thanks, Eric.

> How did you find this?

This code was being changed as part of some cleanup, I noticed there were no tests covering it, and so I went to write some.  They all failed, and so I dug into why.

> these functions are not used by the Open XML SDK

Pack URIs in general aren't used, or just these utility functions for creating them?

> The net result is that we have a new library that is super compatible with the old one.

Obviously there are some gaps :wink:

> But I think it would be good to remove this functionality from System.IO.Packaging. I would take the approach of ifdef it out, then if there happened to be someone who was using it, they could put it back in. But I highly doubt it. This will require some analysis and time on my part to determine exactly what to cull. I am buried right now. What is the time frame on this?

The current state is arguably the worst one: public surface area that's just plain broken.  We should either fix it or remove it (and I'd prefer we not just ifdef it out, but actually delete the code entirely).  If we believe that it's unnecessary/unused/etc., then we should delete it now and then add a fixed version back later if it's deemed important then.

cc: @joshfree

**Comment by stephentoub** [comment]
I believe this applies to more than just Create.  Since you can't create a Uri with the pack format, the GetPackageUri, GetPartUri, etc. are all useless in corefx as well.

**Comment by EricWhiteDev** [comment]
Yes, I agree.  Have been discussing with Tristan / Chris, and plans are to clean up the System.IO.Packaging API.  Should know more in 2-3 days.

**Comment by stephentoub** [comment]
Thanks, @EricWhiteDev.
