### ISSUE TITLE
System.Data.SqlClient not running on IIS  when using DNX Core RC1

### ISSUE THREAD

**Issue by cindro** [dotnet/corefx#4776]
I have been trying to get System.Data.SqlClient (4.0.0-beta-23516) to work on DNX Core RC1.

I have a simple .NET Core app which is loading data from SQL Server, everything works FINE on IIS Express.

As soon as I publish the app on IIS 7.5 (Win7) or IIS 8 (Win 2012), the app is no longer able to load data, everything works fine as soon as I remove System.Data.SqlClient or don't call it.

I have installed Visual C++ Redistributable for Visual Studio 2012 Update 4, it didn't help.

I tried publishing it for both x86 and x64, still didn't help, but System.Data.SqlClient runs totally fine on IIS Express.

**Comment by davidfowl** [comment]
@cindro This was fixed in RC1-Update1, released yesterday. Get a new version from http://get.asp.net

**Comment by joshfree** [comment]
Closing this issue since a fix is available online.  Please feel free to reactivate if there are continued issues.  Thanks.

**Comment by cindro** [comment]
@davidfowl I tried RC1-Update1 without any luck, targeted both x86 and x64. It still only works on IIS Express.

**Comment by cindro** [comment]
I ran RC1-Update1 on 3 different computers (win7,win8 & win2012) and couldn't get IIS to load data from SQL Server, IIS Express was able to do this on all computers. As soon as I remove System.Data.SqlClient package, the app runs fine on IIS again.

> open

**Comment by maxkeller** [comment]
@cindro were you able to solve this yet? I'm facing the same issue

**Comment by cindro** [comment]
@maxkeller No, I was not able to, it looks like we will have to wait for RC2 to be released sometime in February. I am currently using the full .net (dnx46) to get around this issue.

**Comment by maxkeller** [comment]
@cindro wow that was quick, thank you. dnx46 it is, then.

**Comment by mwijnands** [comment]
The fix is to add this to your project.json:

```
  "dependencies": {
    "Microsoft.NETCore.Platforms": "1.0.1-beta-23516",
```

It worked for me. See https://github.com/aspnet/EntityFramework/issues/3637
