### ISSUE TITLE
Add "Windows Server 2016 TP4 (Nano Server Installation)" CI / Rolling Build

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#4779]
Now that Nano Server TP4 is available in the Azure Gallery we should investigate adding it to our non-blocking outer-loop build and test system:

http://blogs.technet.com/b/nanoserver/archive/2015/11/25/nano-server-iaas-image-in-the-azure-gallery.aspx

https://en.wikipedia.org/wiki/Windows_Server_2016#Nano_Server

**Comment by ellismg** [comment]
Moving this to RTM.  We need more investigation to understand how to get the nano server part talking with Jenkins.

**Comment by joshfree** [comment]
moving to rc2 per offline discussions

**Comment by joshfree** [comment]
@Priya91 can you please pick this one up?

**Comment by Priya91** [comment]
@joshfree Yes, will work on this.

**Comment by Priya91** [comment]
This is added to CI.
