### ISSUE TITLE
Immediately accessing properties on Process objects after Start() can throw NullReferenceException

### ISSUE THREAD

**Issue by MattGal** [dotnet/corefx#478]
By calling Process.Start(), then immediately (as in the next line of code) accessing a property on it such as PeakVirtualMemorySize64 can throw a very strange NullReferenceException in the property accessors.  (strange because the text is "error CS0648: '' is a type not supported by the language")
![untitled](https://cloud.githubusercontent.com/assets/7862010/5810953/839237e2-a003-11e4-805f-750d80d1cc31.png)

This is further exacerbated by the lack of (obvious) spin mechanisms on Process class such as the WaitForInputIdle method.  Workarounds are possible but not ideal.  Stepping through in a debugger, the problem will not reproduce.

Noted on : NonpagedSystemMemorySize64
PagedMemorySize64
PagedSystemMemorySize64
PeakPagedMemorySize64
PeakWorkingSet64

**Comment by weshaggard** [comment]
@MattGal Thanks for reporting this issue. Do you know if this works if you run it on the Full .NET Framework?

**Comment by mikedn** [comment]
It appears that some calls to EnsureState have been lost along the way. The desktop version has a EnsureState(State.HaveNtProcessInfo) in this property.

**Comment by stephentoub** [comment]
I'll take a look; assigning to myself.  It's possible I broke this as part of the x-plat refactoring... I'd removed some of these calls when I thought the EnsureState call with particular options was a nop (due, I'd expect, to a previous set of changes to EnsureState), but maybe I overlooked something.

**Comment by stephentoub** [comment]
Yeah, I broke this will #375... will fix.

**Comment by stephentoub** [comment]
Fixed with #481
