### ISSUE TITLE
System.Reflection.Metadata depends on Windows API's

### ISSUE THREAD

**Issue by chcosta** [dotnet/corefx#4784]
@nguerrera , I noticed that System.Reflection.Metadata has a dependency on Windows API's (api-ms-win-core-file-l1-2-0.dll).  I understand that this is light-up code, but is there a reason that we have this requirement instead of using a different method that doesn't include this dependency?

cc @ericstj

**Comment by nguerrera** [comment]
Does this impact packaging given that it's entirely done with light-up? The way to eliminate it would be for the BCL to provide support for reading directly from a FileStream to unmanaged memory, possibly via `Span<byte>` support in Stream. cc @KrzysztofCwalina @tmat

That would make the optimization apply equally on non-Windows platforms, which would certainly be nice.

I think there may be a tracking issue already. I'll look for it and link here if I find it.

**Comment by nguerrera** [comment]
I found slightly related #987 where I argued for the same feature, but no issue for the actual feature. I'll open one.

**Comment by nguerrera** [comment]
Opened #4786.

@chcosta I'm unclear on what the action item here is. Is there anything inherently wrong with a library lighting up on native Windows API? IOW, can I close this?

**Comment by chcosta** [comment]
There's nothing inherently wrong here, the current state causes some confusion in the new package testing infrastructure which is using reflection to find out what pInvokes a library is making and then ensure there is full closure for a packaging lineup.  The result is that when validating the Microsoft.NETCore package against a non-Windows platform, it thinks that it is missing library dependencies, but it's not...

        //        System.Reflection.Metadata is missing native assembly api-ms-win-core-file-l1-2-0.dll
        //        System.Reflection.Metadata is missing native assembly kernel32.dll

This is the only library I've seen using the light-up code methodology, and I can add a hack for this to the testing infrastructure.  When discussing this with @ericstj, there was a desire to understand if there were any unknown factors requiring this method.

**Comment by nguerrera** [comment]
Seems that the test should have some sort of baseline. Alternatively we could invent an attribute like [LightUpOnly] or something and the test could filter those P/Invokes.

**Comment by chcosta** [comment]
Thanks Nick, I'll look into adding a baseline for this.
