### ISSUE TITLE
Mechanism for reading directly from file to unmanaged memory

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#4786]
System.Reflection.Metadata has an optimization where it reads files small enough to not warrant memory mapping directly into the unmanaged heap (without an intermediate copy on the managed heap). This optimization is done by lighting up on Windows to the native `ReadFile` API. For this to work cross-plat there should be a way to pass unmanaged memory to Stream and have FileStream override it to not involve intermediate copies to managed memory. This could possibly be accomplished via `Span<byte>` support in `Stream` overridden by `FileStream`. 

cc @KrzysztofCwalina

**Comment by karelz** [comment]
We need formal API proposal.

**Comment by nguerrera** [comment]
This is done: "This could possibly be accomplished via Span<byte> support in Stream overridden by FileStream." 🎉
