### ISSUE TITLE
Add Path.TryGetExtension 

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#4792]
Today Path.GetExtension throws if the value passed in has invalid chars. See https://github.com/aspnet/StaticFiles/commit/657a5ab26bea3f0b9293a216f28f7b37e004d707#diff-e0272e80448d0ed39c75613bfe35ee62R438. It would be great if there was a way to avoid that exception without reimplementing it.

**Comment by comdiv** [comment]
1) think it will force to add TryGetDictionaryName, TryGetFileName not just TryGetExtension
2) I don't think that it's good design
Semantically:
First: When you write `int.TryParse(mystring, out myint)` it's name doesn't assume that `mystring` is int - you just try to parse it this way.
Second: When you write `Path.TryGetExtension(path)` it assumed that it's `path` but may be not `path`. If it's path - it should be not fail with `GetExtension()` if it's not - no GetExtension no GetFileName and so on should work.

So better is to add guard or analyzer method to Path that determines is given path correct or not.
In my opinion it can be:

simplest one
```
bool Path.IsValid(string pathCandidate){...}

//usage
string extension = "";
stirng filenameNoExt = "";
if (Path.IsValid(mypath)){
     extension = Path.GetExtension(mypath);
     filenameNoExt = Path.GetFileNameWithoutExtension(mypath);
}else{
    ....
}
// it's much more understandable and clear than
string extension = "";
stirng filenameNoExt = "";
bool hasext = Path.TryGetExtension(mypath, out extension); // internally exception or checking validity
bool hasfilename = Path.TryGetFileNameWithoutExtension(mypath, out filenameNoExt); // internally exception or checking validity
// so doubled exceptions or parsing will be applyed
if (hasext && hasfilename) { //broken semantic - is it possible to hasext==true and hasfilename ==false
   ...
}else{
   ...
}
```

So my suggestion add guard `public static bool Path::IsValid(string pathCandidate)` (C++ like for shorter here)

**Comment by karelz** [comment]
@JeremyKuhne @ianhays doesn't it better fit into System.IO area?

**Comment by ianhays** [comment]
@karelz Path lives mostly in runtime extensions so the current tag makes sense, but functionally it makes more sense with a System.IO tag as that is its namespace. Either is correct.

On a meta note, having a runtime extensions label doesn't seem particularly useful as the components of that assembly are spread across several ownership areas and namespaces.

**Comment by karelz** [comment]
@ianhays yes, some areas are more grab bags with exceptions. No system is perfect ...
Are there more things in Runtime.Extentions you think belong to other areas? (e.g. Path into IO)

**Comment by ianhays** [comment]
>Are there more things in Runtime.Extentions you think belong to other areas? (e.g. Path into IO) 

StopWatch => System.Diagnostics
WebUtility => System.Net

I'd argue that organization based on namespace is likely more meaningful than organization based on assembly. In most cases the two are equivalent, but RuntimeExtensions is something of an exception or "grab bag" as you said.

**Comment by karelz** [comment]
If it is per namespace, then there will be lots of exceptions for System namespace ... no system is perfect., we will always have to live with some exceptions.
BTW: The reference assemblies rule was in place before I started making any changes to the rules :) ... I didn't feel "brave" enough to change it.

**Comment by JeremyKuhne** [comment]
@davidfowl We've removed the checks from GetFileExtension and we now have a span version of it as well. I presume this answers your request. If not, please reopen.
