### ISSUE TITLE
Process.Start not working for HTTP links

### ISSUE THREAD

**Issue by xanather** [dotnet/corefx#4794]
On windows (with .NET Core) calling:

System.Diagnostics.Process.Start(SomeWebLinkHere);

Results in:

An exception of type 'System.ComponentModel.Win32Exception' occurred in System.Diagnostics.Process.dll but was not handled in user code.
Additional information: The system cannot find the file specified.

Works fine on the .NET Framework, is this intended?

**Comment by Maxwe11** [comment]
I guess thats because `UseShellExecute` not supported in .NET Core

**Comment by xanather** [comment]
You're probably right, hope it comes in a future version, not sure why the property exists in .net core when its not supported (I tried setting it to true, throws a run-time exception).

**Comment by nguerrera** [comment]
The reason it exists is for portability, you have to explicitly set it to false. On desktop, the default is true IIRC. cc @pallavit

**Comment by pallavit** [comment]
> The reason it exists is for portability.

That is correct. On Desktop default for UseShellExecute = true (which is why the web link works) and for a lot of scenarios you need to explicitly set it to false for example redirecting stream etc. Hence to make desktop code portable on NetCore, this API was added and it only allows setting the property to false.

> hope it comes in a future version, 

Unfortunately, this scenario can't be supported because the necessary windows APIs are not available on Core.

**Comment by xanather** [comment]
Will it eventually be added? I don't see why it shouldn't through some simple Pinvokes. Using the shell can be useful in many scenarios. Its possible that the actual commands executed through the shell may be platform specific but it will stop people from creating the same wrapper methods for each platform.

Linux & Mac:
http://linux.die.net/man/3/system
Windows:
https://msdn.microsoft.com/en-us/library/windows/desktop/bb762153%28v=vs.85%29.aspx

**Comment by pallavit** [comment]
> Will it eventually be added?

Unfortunately as things stand today we can't support it. The windows API for this (the one you shared) is not available on all SKUs of windows and so we can't take dependency on it.

**Comment by nguerrera** [comment]
The best we can do is light up on the platforms that do have ShellExecute. Have we considered that?

**Comment by xanather** [comment]
Sorry I have never had an issue with shell executes, what Windows SKU's aren't supported (it is Windows Server Core?)

**Comment by pallavit** [comment]
@xanather It is not part of windows Onecore. The following link talks about it - https://msdn.microsoft.com/en-us/library/windows/hardware/dn927350(v=vs.85).aspx

**Comment by pallavit** [comment]
Closing this issue, since we can't expose this on Windows as of now (or light-up this scenario in a meaningful way, as discussed in #4861) and Stephen already implemented this on Unix.

**Comment by adamralph** [comment]
Is there any plan to support this on Windows?

Or is there any other way to send an http/https URL to Windows for default handling using .net core?
