### ISSUE TITLE
Evaluate the need to shim native calls on OSX

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefx#4798]
We have a few OSX-specific native calls that don't use shims.  From my understanding this was deemed acceptable because OSX already has a stable Application Binary Interface (ABI).

However, looking through some of these calls, I'm not completely sure this is true.  For example https://github.com/dotnet/corefx/blob/master/src/Common/src/Interop/OSX/Interop.CoreFoundation.cs#L72-L77 has :

``` C#
private static extern SafeCreateHandle CFArrayCreate(
            IntPtr allocator,
            [MarshalAs(UnmanagedType.LPArray)]
            IntPtr[] values,
            ulong numValues,
            IntPtr callbacks); 
```

Which on my Mac appears to be defined as:

``` C++
CFArrayRef CFArrayCreate(
    CFAllocatorRef allocator,
    const void **values,
    CFIndex numValues,
    const CFArrayCallbacks *callbacks);
```

And where `CFIndex` is defined as:

``` C++
#if __LLP64__
typedef signed long long CFIndex;
#else
typedef signed long CFIndex;
#endif
```

Are we guaranteed that CFIndex will always be an 8-byte integer?  What if we were on a 32-bit OSX?

We should analyze all our non-shimmed native calls on OSX and be 100% sure we will always have ABI stability, no matter the OSX system we are running on.

**Comment by mellinoe** [comment]
If it's just a matter of operating system bitness, I think we should just switch to using IntPtr / UIntPtr rather than create more shim functions. Regardless, we don't support running 32-bit outside of Windows, do we? If we do in the future we should take a look at these kinds of issues, but we shouldn't need to create more shims, I don't think.

**Comment by danmosemsft** [comment]
cc @eerhardt @tarekgh this seems it can move to future.

**Comment by tarekgh** [comment]
I am seeing this already fixed to use UIntPtr. we may need just to close it. @eerhardt?

**Comment by tarekgh** [comment]
@eerhardt I am closing this one but feel free to re-open if you think there is anything need to be done here. Thanks.

**Comment by mellinoe** [comment]
We did address it, although shouldn't we be using `IntPtr` here, given that it's defined as a `signed long (long)`, not unsigned? In any case, I still don't think we need shims for this issue, so that could be tracked separately.

**Comment by eerhardt** [comment]
> although shouldn't we be using IntPtr here, given that it's defined as a signed long (long), not unsigned?

This was addressed in the PR https://github.com/dotnet/corefx/pull/15546#issuecomment-275852041.

>if you think there is anything need to be done here. 

It looks like the concern is now addressed.  Thanks for closing it.
