### ISSUE TITLE
Windows 8 support for System.Data.Common

### ISSUE THREAD

**Issue by chinhodado** [dotnet/corefx#4802]
According to [this](https://github.com/aspnet/Microsoft.Data.Sqlite/issues/185#issuecomment-161726607) issue, `System.Data.Common` needs to support Windows 8 before `Microsoft.Data.Sqlite` can. Is it possible to add Windows 8 support to that package?

cc @bricelam

**Comment by ericstj** [comment]
To do this we need to do a couple things:
- [ ] Change the desktop facade to build against Net 4.5 using a partial facade project
- [ ] Dial down all dependencies to `4.0.0`.  I tried this and encountered a few missing methods on Task.  @stephentoub do we have some boilerplate for these methods that will work on the 4.0.0 System.Threading.Tasks?
  - FromException, FromException<t>
  - FromCancelled, FromCancelled<t>
  - CompletedTask
- [ ] Update project to claim implementation as `dotnet5.1` and do the same for the ref assembly.

**Comment by stephentoub** [comment]
>  do we have some boilerplate for these methods that will work on the 4.0.0 System.Threading.Tasks?

Yup:
https://github.com/dotnet/corefx/blob/master/src/Common/src/System/IO/TaskHelpers.cs

**Comment by chcosta** [comment]
This change has been checked in.
