### ISSUE TITLE
Add/Expose String.EndsWith(char)

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#4805]
Moved bug from https://github.com/dotnet/coreclr/issues/1463 to proper repo

> ## davidfowl  commented on Aug 31  
> 
> So we don't have to rewrite it over and over :smile:. Seems like its already there just made internal for > some reason:
> 
> https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/String.cs#L2210
> 
> People end up writing code like this:
> 
> https://github.com/aspnet/dnx/blob/dev/ext/compiler/preprocess/Internalization.cs#L100
> 
> and this
> 
> https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Runtime/NuGet/Utility/PathUtility.cs#L45
> ## bbowyersmyth  commented on Sep 2  
> 
> I had the same thought a while back and discovered it would be a breaking change for an edge case in VB.
> 
> Against the current framework the following is valid VB:
> Dim find As Char = "a"c
> Dim result = "abc".StartsWith(find)
> 
> The compiler wraps  find  with a call to a string conversion and all is good. If  EndsWith(char)  was > made public and the code recompiled it would switch from using the CurrentCulture based  EndsWith(string)  to the Ordinal based  EndsWith(char) .
> 
> Whether any of the offending characters or the above scenario is deemed important I would love to hear. Especially a  StartsWith(char)  with direct access to  String.m_firstChar 
> ## AlexGhiondea  commented on Sep 8  
> 
> It seems like the VB compiler is trying to help by picking an overload that will work.
> 
> @VSadov -- do you know what the VB compile would do if we were to introduce the  bool EndsWith(char value)  overload on string?
> 
> @davidfowl can you create an issue in the CoreFx repo (following the API review process)?

**Comment by AlexGhiondea** [comment]
@VSadov -- any thoughts about how would this impact VB?

**Comment by VSadov** [comment]
in VB char widens to string. The exact match will be preferred, but char can cast to string implicitly if needed.

I am surprised that    StartsWith("A") and StartsWith('A')  could produce different results though. Even in C# it would feel strange that default behavior of these two overloads WRT single char string is different.

**Comment by terrajobst** [comment]
This looks good provided that:

* We add overloads for both, `StartsWith` and `EndsWith`
* We add all three versions (char, char + bool + culture, char + comparison)
* The semantics of the overloads follow the ones that take `string`, for example, `EndsWith('c')` should be identical to calling `EndsWith("c")`. That means the simple one must be culture-aware instead of the current (internal) implementation that is ordinal.
* We suggest renaming the current one to `EndsWithOrdinal` and leaving it internal

**Comment by AlexGhiondea** [comment]
Updating the reference to the code:
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/String.Comparison.cs#L795

**Comment by fujiy** [comment]
I plan to work on it

**Comment by fujiy** [comment]
@karelz could you assign me? Thanks

**Comment by fujiy** [comment]
@brfalcon will fix this issue. Thanks

**Comment by karelz** [comment]
Invite sent ...

**Comment by brfalcon** [comment]
Invite accepted! Thanks @karelz

**Comment by karelz** [comment]
Assigned to you ...

**Comment by brfalcon** [comment]
Thanks @karelz

**Comment by brfalcon** [comment]
Hello guys! I've added the missing parts as suggested however I am being unsuccessful while trying to consume those new public API's. Which documentation could guide me through the appropriate process?

**Comment by AlexGhiondea** [comment]
@brfalcon where did you add those APIs? If they have been added to CoreCLR then we have a 3 step process:
1. Make the changes in CoreCLR
2. Consume the CoreCLR from CoreFX
3. Expose the APIs in CoreFx

**Comment by brfalcon** [comment]
@AlexGhiondea, I've added them to CodeCLR. Would you have any documentation that provides more details on how to perform those steps?

**Comment by karelz** [comment]
I don't think we have great docs on that yet. It's on my todo list.

**Comment by AlexGhiondea** [comment]
@brfalcon we are working on that.

If you want to try locally, you can, more or less, replace system.private.corelib.dll from the CoreCLR build into the Tools folder in your CoreFx build. But the official way is still the one I outlined above.

**Comment by brfalcon** [comment]
I will try to run locally following your suggestion. Thanks @karelz and @AlexGhiondea !

**Comment by fujiy** [comment]
I got it. To be able to consume my CoreClr I had to add a reference to my CoreClr packages path at element DnuRestoreSource in dir.props.

**Comment by AlexGhiondea** [comment]
@fujiy pointing to your package location that you build in CoreCLR is another option!

Glad to see you got it working!

Why did you have to set that envvar?

**Comment by brfalcon** [comment]
@AlexGhiondea, instead of removing the element VerifyDependencies from the VersionTools.targets file, we set that envvar in order to bypass the dependencies verification.

**Comment by justinvp** [comment]
> The semantics of the overloads follow the ones that take string, for example, EndsWith('c') should be identical to calling EndsWith("c"). That means the simple one must be culture-aware instead of the current (internal) implementation that is ordinal.

Note that `IndexOf("c")` and `LastIndexOf("c")` behave differently than `IndexOf('c')` and `LastIndexOf('c')`. **All** of the methods on string that take `char` do an ordinal comparison by default. `IndexOf(char)` and `LastIndexOf(char)` do an ordinal comparison, whereas `IndexOf(string)` and `LastIndexOf(string)` do a culture-sensitive comparison.

How do we reconcile this for `StartsWith(char)` and `EndsWith(char)`? Making them culture sensitive by default makes them match the behavior of the string overloads, but makes them inconsistent with the rest of string's methods that operate on single chars.

Also, I could not find any existing methods on string that operates on a `char` and accepts a `StringComparison` or `CultureInfo`. Do we really need it for `StartsWith(char)` and `EndsWith(char)`?

The following do an ordinal comparison:
 - `IndexOf(char)`
 - `IndexOf(char, int)`
 - `IndexOf(char, int, int)`
 - `IndexOfAny(char[])`
 - `IndexOfAny(char[], int)`
 - `IndexOfAny(char[], int, int)`
 - `LastIndexOf(char)`
 - `LastIndexOf(char, int)`
 - `LastIndexOf(char, int, int)`
 - `LastIndexOfAny(char[])`
 - `LastIndexOfAny(char[], int)`
 - `LastIndexOfAny(char[], int, int)`

The following do a culture-senstive comparison:
 - `IndexOf(string)`
 - `IndexOf(string, int)`
 - `IndexOf(string, int, int)`
 - `LastIndexOf(string)`
 - `LastIndexOf(string, int)`
 - `LastIndexOf(string, int, int)`

The following take a `StringComparison` option (Note: there are no `StringComparison` options for the `char` overloads, only for the `string` overloads):
 - `IndexOf(string, StringComparison)`
 - `IndexOf(string, int, StringComparison)`
 - `IndexOf(string, int, int, StringComparison)`
 - `LastIndexOf(string, StringComparison)`
 - `LastIndexOf(string, int, StringComparison)`
 - `LastIndexOf(string, int, int, StringComparison)`

**Comment by karelz** [comment]
@justinvp that's a very good point. @terrajobst do we want to bring it back for API review?

**Comment by brfalcon** [comment]
If we come to the conclusion that the culture aware implementation of EndsWith(char) and StartsWith(char) isn't needed, I could reuse the implementation from the internal method EndsWithOrdinal to build both EndsWith(char) and StartsWith(char). Does it makes sense?

**Comment by fujiy** [comment]
Hi @terrajobst, did you have a chance to evaluate this item? Thanks!

**Comment by karelz** [comment]
Let's discuss it in next API review.

**Comment by terrajobst** [comment]
That's unfortunate but our goal is to make things consistent with existing APIs, especially overloads. If all `char` based overloads are using ordinal semantics while the `string` ones are culture-sensitive. In that case, I think we should follow that.

So the new plan should be:

- We add overloads for both, `StartsWith` and `EndsWith`
- We add only the `char` version (no other overloads operating on chars take comparisons, cultures, or booleans indicating casing)
- The semantics of the overloads follow the other ones that take `char`, for example, `EndsWith('c')` should be identical to calling `s.LastIndexOf('c') == s.Length - 1`.

**Comment by karelz** [comment]
BTW: This is another example, why we need API proposal in the "formal form" (ideally in the top-most post). It makes it much, much easier to track and understand what we approved and what is the diff in next API proposal revision, etc. I will be insisting it more in future :)

**Comment by fujiy** [comment]
Thanks, we'll take care of it

**Comment by karelz** [comment]
The API needs to be exposed & tests added.

**Comment by danmosemsft** [comment]
Karel that's https://github.com/dotnet/corefx/pull/16198

**Comment by karelz** [comment]
Ooops, I somehow missed that :(
