### ISSUE TITLE
AcceptAsyncV4BoundToAnyV6_Success failed on OSX in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4829]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/21/console
```
09:22:19    System.Net.Sockets.Tests.DualMode.AcceptAsyncV4BoundToAnyV6_Success [FAIL]
09:22:19       Assert.Equal() Failure
09:22:19       Expected: ::ffff:127.0.0.1
09:22:19       Actual:   ::127.0.0.1
09:22:19       Stack Trace:
09:22:19             at System.Net.Sockets.Tests.DualMode.DualModeConnect_AcceptAsync_Helper(IPAddress listenOn, IPAddress connectTo)
09:22:19             at System.Net.Sockets.Tests.DualMode.AcceptAsyncV4BoundToAnyV6_Success()
```

**Comment by ericeil** [comment]
I think the test is just going to have to be a little more forgiving of which form of IPv6 loopback address it receives.

**Comment by ianhays** [comment]
>which form of IPv6 loopback address it receives.

is ```::127:0:0:1``` a valid IPv6 loopback address without the "ffff" prefix?

**Comment by ericeil** [comment]
The "ffff" one is an "IPV4-mapped" address; the other one is an "IPV4-compatible" address.  The "compatible" address scheme is officially deprecated, but still used.

**Comment by stephentoub** [comment]
This just failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/2254/console
```
19:25:24    System.Net.Sockets.Tests.DualMode.AcceptAsyncV4BoundToAnyV6_Success [FAIL]
19:25:24       Assert.Equal() Failure
19:25:24       Expected: ::ffff:127.0.0.1
19:25:24       Actual:   ::127.0.0.1
19:25:24       Stack Trace:
19:25:24             at System.Net.Sockets.Tests.DualMode.DualModeConnect_AcceptAsync_Helper(IPAddress listenOn, IPAddress connectTo)
19:25:24             at System.Net.Sockets.Tests.DualMode.AcceptAsyncV4BoundToAnyV6_Success()
```

**Comment by stephentoub** [comment]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/2257/

**Comment by stephentoub** [comment]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/2265/console
