### ISSUE TITLE
Improve Regex API

### ISSUE THREAD

**Issue by djanosik** [dotnet/corefx#483]
Please, improve Regex API. It feels it wasn't touched since .NET 1.0, it does not support generics (see [CaptureCollection](https://github.com/dotnet/corefx/blob/master/src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexCaptureCollection.cs)), etc.

**Comment by svick** [comment]
There is already a change to add generic interfaces to regex collections under review (#271).

What exactly does your "etc." mean? Because I think that if you don't specify it, it doesn't meant anything.

**Comment by djanosik** [comment]
Eh, I am sorry for that. I've missed #271 somehow. I may add more issues for "etc." later, with more details :)
