### ISSUE TITLE
System.Net.Sockets.APMServer.Tests has a test that hangs, causes build timeout on OSX.

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#4836]
```
System.Net.Sockets.Tests.SendReceive.SendRecvAPM_Single_Stream_TCP_IPv4 [FAIL]
15:49:15       Assert.True() Failure
15:49:15       Expected: True
15:49:15       Actual:   False
15:49:15       Stack Trace:
15:49:16             at System.Net.Sockets.Tests.SendReceive.SendRecvAPM_Stream_TCP(IPAddress listenAt, Boolean useMultipleBuffers)
15:49:16             at System.Net.Sockets.Tests.SendReceive.SendRecvAPM_Single_Stream_TCP_IPv4()
17:34:43 
Build timed out (after 120 minutes). Marking the build as aborted.
17:34:44 ./run-test.sh: line 130:  9296 Terminated: 15          ./corerun xunit.console.netcore.exe $testDllName -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=$xunitOSCategory -notrait Benchmark=true
17:34:44 One or more tests failed while running tests from 'System.Net.Sockets.APMServer.Tests'.  Exit code 143.
```

**Comment by pgavlin** [comment]
When did this start happening?

**Comment by Priya91** [comment]
This happened in my PR yesterday. There's another build failure in ubuntu on the same test project:

```
d:\j\workspace\dotnet_corefx\ubuntu_debug_bld_prtest\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00126\lib\packageresolve.targets(103,5): error MSB4018: The "ValidateProjectDependencyVersions" task failed unexpectedly. [d:\j\workspace\dotnet_corefx\ubuntu_debug_bld_prtest\src\System.Net.Sockets.Legacy\tests\FunctionalTests\System.Net.Sockets.APMServer.Tests.csproj]
```

Build output: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/ubuntu_debug_bld_prtest/33/console

**Comment by SidharthNabar** [comment]
@Priya91 , @pgavlin - Please let me know if this is something that is needed by RC2 or if RTM is okay. Accordingly, let's have the milestone set.

**Comment by Priya91** [comment]
Saw this failing once in my PR, since it's only a test bug and occurred once, i think RTM is fine, unless the owner decides this is an important scenario to debug into.

**Comment by stephentoub** [comment]
How do we know it's a test bug?

**Comment by Priya91** [comment]
Just a logical guess, it's not a functional failure since it doesn't happen on every run, maybe the test code is not entirely free of concurrency bugs, since the product code has been around for sometime. I could be wrong, @pgavlin will know better.

**Comment by stephentoub** [comment]
I'm going to close this one.  There were other lab-related problems happening that day, and I expect this was related to that.  Even if it wasn't, we have a few other open issues on these methods.  If this hangs again, we can reopen.
