### ISSUE TITLE
Building dnxcore libraries that use mono references until a suitable alternative is created (System.Drawing).

### ISSUE THREAD

**Issue by theonlylawislove** [dotnet/corefx#4850]
I have been working on migrating a project I am working on ([Skimur](https://github.com/skimur/skimur/tree/feature/dnx)) and the only feature the app requires that is (currently) missing is ```System.Drawing```.

As described [here](https://github.com/imazen/Graphics-vNext), there are currently no plans to implement some sort of cross-plat ```System.Drawing``` on .NET Core.

Since .NET Core doesn't work on linux yet, we have to use mono. And, since we are using mono, I could reference and use mono's ```System.Drawing```, at least until an alternative gets developed for .NET Core.

With that said, I can't exactly reference mono's ```System.Drawing``` from within my ```project.json```. What are my options, if any?

**Comment by mellinoe** [comment]
This seems to be a question about the project.json format / DNX tool, so you'll probably have better luck asking the ASP.NET folks for help with that tool. From what I remember there is some syntax to reference a "loose" assembly, but I can't recall it off the top of my head. I think you have to create something like a "wrapper" project.json for each assembly you want to reference.

**Comment by davidfowl** [comment]
> As described here, there are currently no plans to implement some sort of cross-plat System.Drawing on .NET Core.

You might want to check out http://imageprocessor.org/. It currently works on .NET Core. Not sure if it has all of the features you need but it's worth a look.

> Since .NET Core doesn't work on linux yet, we have to use mono. 

It does work on linux.

> And, since we are using mono, I could reference and use mono's System.Drawing, at least until an alternative gets developed for .NET Core.

Sure.

> With that said, I can't exactly reference mono's System.Drawing from within my project.json. What are my options, if any?

Sure you can, just put it in the frameworkAssemblies section of dnx451 in your project.json.

**Comment by joshfree** [comment]
It looks like all questions have been answered.  @theonlylawislove feel free to reactivate this issue if needed.
