### ISSUE TITLE
EventSource dictionary events are broken on CoreCLR

### ISSUE THREAD

**Issue by davmason** [dotnet/corefx#4867]
Writing a dictionary to an EventSource like the following is broken.
`EventSource logger = new EventSource();`
`logger.Write("EventWithStringDict_C", new { 
                            myDict = dict, 
                            s = "end" });`

This fails because Activator.CreateInstance fails because it can't find the constructor for one of the types we use in TraceLogging to parse the dictionary. The type is `KeyValuePairTypeInfo<K, V>`.

**Comment by stephentoub** [comment]
@joshfree, @davmason, this is marked as 1.1.0; shouldn't this be 1.0.0-rtm?

**Comment by davmason** [comment]
This has been addressed by one of the other fixes in the last 4 months, now the scenario is working.
