### ISSUE TITLE
Add tests for null/empty array issue in EventSource

### ISSUE THREAD

**Issue by davmason** [dotnet/corefx#4873]
Add tests for https://github.com/dotnet/coreclr/pull/1988.

**Comment by danmosemsft** [comment]
@davmason is this still relevant? if not please close.

**Comment by karelz** [comment]
@davmason the link seems to be not related to EventSource. Can you refer to what you meant?
cc @brianrob

**Comment by davmason** [comment]
It is the right issue number but in coreclr, not corefx. https://github.com/dotnet/coreclr/pull/1988 has the details

**Comment by ViktorHofer** [comment]
@karelz I looked into that issue and @davmason is right there aren't any test cases for that. Unfortunately the tests are pretty hard to read and understand. I failed in my first attempt. Maybe @brianrob or @davmason can support?

**Comment by karelz** [comment]
@davmason doesn't work on EventSource.
@brianrob @vancem if you want help from @ViktorHofer, can you please provide some guidance here?
