### ISSUE TITLE
Address review comments for System.AppContext #4860 

### ISSUE THREAD

**Issue by dsgouda** [dotnet/corefx#4877]
Hi @AlexGhiondea 
Please refactor the code for System/AppContext.cs per comment here
https://github.com/dotnet/corefx/pull/4860#discussion_r46854265

**Comment by AlexGhiondea** [comment]
While the suggestions were good, I don't think they would add enough value to justify the code churn.

**Comment by weshaggard** [comment]
Thanks @AlexGhiondea for following up on the comments.
