### ISSUE TITLE
Issue with  RC1 project

### ISSUE THREAD

**Issue by SharpNoiZy** [dotnet/corefx#4881]
Hi

I developed a library where I try to access an EF7 DbSet<> with Linq Query Syntax.
And I can not compile it, because it keep telling me:
```
Error	CS0012	The Type "IEnumerable<>" is defined in an unreferenced assembly. Add an reference on the Assembly "System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
```

Ideas?
Kind regards

**Comment by Maxwe11** [comment]
@SharpNoiZy could share your project.json?

**Comment by SharpNoiZy** [comment]
Sure:
```
{
	"version": "1.0.0-*",
	"description": "MFT.Integration Class Library",
	"authors": [ "cneuss" ],
	"tags": [ "" ],
	"projectUrl": "",
	"licenseUrl": "",
	"frameworks": {
		"net451": { },
		"dotnet5.4": {
			"dependencies": {
				"Microsoft.CSharp": "4.0.1-beta-23516",
				"System.Collections": "4.0.11-beta-23516",
				"System.Linq": "4.0.1-beta-23516",
				"System.Runtime": "4.0.21-beta-23516",
				"System.Threading": "4.0.11-beta-23516"
			}
		}
	},
	"dependencies": {
		"Common.Cryptography": "1.0.1",
		"MFT.Core": "1.0.0-*"
	}
}
```


Kind regards

**Comment by SharpNoiZy** [comment]
I found the issue, it was a dependent lib "MFT.Core".
And in this one it was the dependency "EntityFramework.Core".
I removed this one, and I can use:
```
List<string> test = new List<string>(); 
test.Where(x => x == "");
```

If I add the dependency "EntityFramework.Core" it's underlined in the normal .NET code view.

So, I think there is an issue with the RC1 version of that nuget pack.

**Comment by chcosta** [comment]
@SharpNoiZy, is there additional follow-up required here or is your issue resolved satisfactorily?

**Comment by bricelam** [comment]
Try adding a reference to the design-time facade on `net451`.
```JSON
{
  "net451": {
    "frameworkAssemblies": {
      "System.Runtime": "4.0.0.0"
    }
  }
}
```

**Comment by SharpNoiZy** [comment]
Yes, the issue is resolved satisfactorily, thanks for your effort!

**Comment by SharpNoiZy** [comment]
Sorry to ping again, but I found a similar issue.
If I use the function ToDictionary I have to add System.Collections to frameworkAssemblies to resolve it.

Just want to mention it.

**Comment by bricelam** [comment]
dotnet/cli#164 would help this...
