### ISSUE TITLE
IntelliSense/coloring/etc. broken in corefx projects

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#4884]
Within the last few weeks, something has changed to break IntelliSense, coloring, etc. within corefx projects.  For example, open a test project: [Fact] attributes aren't colored, no IntelliSense is provided for the Assert class, etc.  And IntelliSense within src assemblies appears to be pulling from the full framework rather than from the actually referenced corefx assemblies.

**Comment by eerhardt** [comment]
@stephentoub - Are you using VS 2015 Update 1?

I'm seeing the same problem with no Intellisense to Linux-only code inside the same project now that I've updated to VS 2015 Update 1.  (Yes, I am selecting "Linux_Debug" in the configuration drop down)

**Comment by stephentoub** [comment]
I'm seeing it on both VS 2015 and VS 2015 Update 1.

**Comment by stephentoub** [comment]
Thanks, @weshaggard.  Your fix worked for me.
