### ISSUE TITLE
Add Linux/Mac build script

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/corefx#49]
A `build.sh` should be added alongside `build.cmd` to build corefx on Linux/Mac.

**Comment by jasonwilliams200OK** [comment]
First, I would like to agree with @ZackCDLVI on this one. Since this is open-source arena, if possible corefx should take advantage of Mono's build system, which is cross platform.

If that is not possible, the options are CMAKE, waf, SCons and gyp etc. I would highly recommend [CMAKE](http://www.cmake.org/), which is universally acceptable cross-platform build machine. Here is the link to the repo: https://github.com/Kitware/CMake.

**Comment by akoeplinger** [comment]
Thought I'd give a little status update on this: with a few recent xbuild fixes that I got into Mono master the corefx repo now builds on Mono, with just two workarounds for xbuild bugs that I didn't have time to investigate yet: https://github.com/dotnet/corefx/compare/master...akoeplinger:xbuild

**Comment by stephentoub** [comment]
Thanks for working on that, @akoeplinger!  That's great to hear.

**Comment by ellismg** [comment]
Now that MSBuild has been open sourced, I think the direction we want to take here is to work with the MSBuild folks to get it working on Linux and OSX and then create a build.sh that mirrors build.cmd, just a lightweight wrapper around MSBuild.

I don't think we should try to adopt a different build system, eg. make, or take a long term dependency on xbuild.

**Comment by jasonwilliams200OK** [comment]
@ellismg, :+1: 
For sake of DRY, IMO it would make sense to collaborate with mono guys: https://github.com/mono/msbuild/commit/fdd90936f1c9b4640ad25be996a9efc6bf01845e and get things moving forward sooner rather than later.
Thanks in advance!

**Comment by akoeplinger** [comment]
@jasonwilliams200OK there's already work going on extending msbuild to linux/mono: https://github.com/Microsoft/msbuild/issues/26

@ellismg sounds good. I'll continue to build corefx with xbuild on my fork and send PRs for xplat issues like the file casing changes I recently sent. This allows us to find problems until msbuild is ready.

**Comment by ellismg** [comment]
@akoeplinger Love to see these PRs.  Thanks so much and keep them coming!

**Comment by akoeplinger** [comment]
Boom, it's done: #1777 :sparkles:

Build instructions are available [here](https://github.com/dotnet/corefx/wiki/Building-On-Unix)

**Comment by jasonwilliams200OK** [comment]
:+1: 
Thanks!

Ugg! everything is so Ubuntu-centric these days. Unfair to Fedora/CentOS, Gentoo, Suse folks.

**Comment by akoeplinger** [comment]
@jasonwilliams200OK Even though the guide uses Ubuntu as an example right now, building should work everywhere where Mono runs. I'm sure that once the process is a little bit more streamlined and doesn't involve a CI build of Mono, there'll be guides for the distros you mentioned.
