### ISSUE TITLE
Group all CoreFX projects under one VS Solution with proper inter-project references.

### ISSUE THREAD

**Issue by clrjunkie** [dotnet/corefx#4901]
Currently it’s virtually impossible to easily navigate and build the entire source tree directly from VS.
This makes it hard to review and debug both implementation code and test code.

**Comment by weshaggard** [comment]
We intentionally do not want to have a single VS solution for all of corefx repo. We want to keep libraries isolated so they can ship independent of each other and in general we want the libraries to depend upon the lowest version of the package that contains the necessary dependencies, and not have project references to the live versions of their dependent libraries. 

For cases were folks have a desire to run tests against the live versions of all the dependencies built in the repo people can pass `/p:TestWithLocalLibraries=true` when building test projects.
