### ISSUE TITLE
statistic distribution generator

### ISSUE THREAD

**Issue by colombod** [dotnet/corefx#492]
I am thinking to add some random generators that obeys specific statistic distribution functions (like normal, binomial, geometric and so on) and also makes the random generator usable as IEnumerable to be easier to use in line or sequence expressions. There is a great paper that covers the ability to obtain sampling functions by composing other sampling functions that is quite nice to express via IEnumerable and IEnumerator. Suck functions can be very useful to obtain numbers that follow a specific law, for example to be used in generating correct weights to initialise untrained neural networks or similar scenarios.

**Comment by cdrnet** [comment]
Do we really want to turn the *core framework* into a general purpose math library?

**Comment by colombod** [comment]
That is a good question, but it applies to some of the stuff in the numeric namespace anyway (like vectors and matrix algebra). And the pseudo random as it is is really basic. The only thing I am suggesting is a framework to implement sampling functions (not full statistics library). What are your toughts?

**Comment by colombod** [comment]
https://www.cs.cmu.edu/~fp/papers/toplas08.pdf this is the paper I was referring to.

**Comment by krwq** [comment]
I think this is a good idea although I'm not convinced it should be part of the core fx. IMO you should create a new repo and once it is ready you can propose to add it here. Your library can always work on top of the framework and you can publish it as a nuget package so people can dogfood it once the first version is ready.

**Comment by colombod** [comment]
Nice suggestion indeed! I can do a first version and then share it. If I get correctly your idea I should build it as a stand alone git repository out of the fork I have of the coreFX, right?

**Comment by cdrnet** [comment]
I agree that this should not be part of the Core FX but implemented as separate package on top of it.  Indeed, this is exactly what all the existing math libraries do, like Math.NET Numerics, Accord.NET, Meta.Numerics to name a few of the open source ones. Most of them currently support the .Net Framework and Mono only, but they can easily add builds for .Net Core as well (at least the first of the mentioned ones already has an experimental branch for that). There's really no need to put the entire NuGet ecosystem directly into the core framework. Have you considered to contribute to one of these projects instead?

**Comment by colombod** [comment]
Actually looking exactly at those ones! I just started this discussion since there was something going on around shuffling functionalities and it could be useful to be able to shuffle according to probability functions and distribution generators. 

Thanks for the directions!!=

**Comment by ikopylov** [comment]
I think that the implementation of a complex statistical library within CoreFx is not a good idea. 
But for me it would be great to see a Random generator with normal distribution as a part of BCL.

**Comment by terrajobst** [comment]
Thanks for filing this suggestion!

We've [reviewed the proposal](https://github.com/dotnet/apireviews/tree/master/2015-09-08-backlog-review) and concluded that we're currently not interested in significant extending the math functionality of the BCL.

However, feel free to start a project under http://github.com/dotnet/corefxlabs. If this generates enough interest, we may pursue this eventually.
