### ISSUE TITLE
coreCLR Assembly.GetExecutingAssembly().CodeBase not working as expected

### ISSUE THREAD

**Issue by Devmates** [dotnet/corefx#4920]
I created a Console Application (Package) under Visual C# - Web - Console Application (Package).
I have got the following .NET Core code :
```csharp
    public class Program
    {
        public static void Main(string[] args)
        {
#if DNX451 //this code is executed
            //but I am getting: C:/Users/currentUser/.dnx/runtimes/dnx-clr-win-x86.1.0.0-rc1-final/bin
            string execDir = Path.GetDirectoryName(Assembly.GetExecutingAssembly().CodeBase);//Assembly.GetExecutingAssembly().Location);
#else
            string execDir = Path.GetDirectoryName(AppContext.BaseDirectory);
#endif
            // ...
        }
    }
```
However, in the old .NET I will get something like ```C:\Users\currentUser\Documents\Visual Studio 2015\Projects\ProjectName\bin\Debug```
Inside this folder there is also the ProjectName.exe and the files which you have marked as "Copy Always" with the "Copy to Output Directory" option. But with the .Net Core these files are missing as well as the Option for copying to output directory.

How can i get the old behaviour or what can I do to get it with .NET Core (e.g. if I have several small programs I would like to execute each in their own location)?

**Comment by weshaggard** [comment]
CodeBase has alwas been a URL (https://msdn.microsoft.com/en-us/library/system.reflection.assemblyname.codebase(v=vs.110).aspx) so I don't think that has changed. 

We have recently added Assembly.Location back which should give you the non-URL path. Depend on your your needs my recommendation however would be to prefer AppContext.BaseDirectory in both .NET Framework and .NET Core.

**Comment by weshaggard** [comment]
@Devmates please let me know if you feel the alternatives don't work for you.
