### ISSUE TITLE
Add PackageTargetRuntime to System.Security.Principal.Windows to name supported OSes

### ISSUE THREAD

**Issue by roncain** [dotnet/corefx#4925]
Update the .csproj in System.Security.Principal.Windows to specify <PackageTargetRuntime> for only the runtimes it supports.  Right now, the package believes a Linux implementation exists but inserts the Windows implementation, causing consumers to break at runtime if they attempt to use it.

**Comment by roncain** [comment]
@ericstj -- be aware we are working to exclude this dependency in https://github.com/dotnet/wcf/issues/604 .  It is okay if your fix goes in ahead of ours, because it should break only the Linux build, which is now done only manually.

**Comment by chcosta** [comment]
This has been fixed and will be in the next package push.

**Comment by ericstj** [comment]
Looks like this broke folks who were depending on this package for x-plat libraries.  We may need to roll it back temporarily.

**Comment by chcosta** [comment]
This was rolled back.  I'll keep the issue open for tracking purposes but move the milestone to rtm (with the possibility that this gets moved to Future).

**Comment by ericstj** [comment]
We fixed this by putting a PlatformNotSupported assembly in place for Unix.
