### ISSUE TITLE
Specifying SSL3.0 throws an exception when trying to authenticate with SslStream

### ISSUE THREAD

**Issue by mconnew** [dotnet/corefx#4927]
In PR #4483 a change was made which causes an exception to be thrown when requesting SSL3.0.
This is the wrong behavior for the following reasons:
* Existing code written for the desktop may fail with an exception
* There's no compile time error when writing code which is guaranteed to fail at runtime
* An exception can be thrown even when SSL3.0 wouldn't be used even though specified
* Inconsistent behavior with other mechanisms to disable SSL3.0

**Existing code written for the desktop may fail with an exception**
Any code written for the desktop which specifies SSL3.0 will now throw an exception, but the developer may not discover this until after code has been released. If a third party library developer is able to port their code to core clr with minimal changes, they may not test every code path in their library on core clr. This is becoming more and more likely now that we support Linux and OSX as many developers won't have the capability to verify their code on those platforms. They should be able to expect that as long as the api surface is available, that their code will behave the same on all platforms that support the api.

**There's no compile time error when writing code which is guaranteed to fail at runtime**
If I create an SslStream and try to authenticate to a remote host specifying SSL3 | TLS | TLS11 | TLS12 in a call to AuthenticateAsClient, this method call is now guaranteed to fail at runtime 100% of the time. That code is deemed invalid and yet there's no compile time warning or error. This is a bad developer experience.

**An exception can be thrown even when SSL3.0 wouldn't be used even though specified**
On desktop and with the prior behavior, if I pass the list SSL3 | TLS | TLS11 | TLS12 to SslStream.AuthenticateAsXXXXX at both ends of a stream I'm attempting to secure, SSL3 won't get negotiated as a higher protocol will attempt to be established. This change causes an application/library which wouldn't have resulted in an insecure connection being negotiated now having a runtime failure despite still being secure.

**Inconsistent behavior with other mechanisms to disable SSL3.0**
Other mechanisms where SSL3.0 can't be used are the protocol being disabled at the OS level (registry change in Windows for example), or the remote end not supporting SSL3.0. In either of these cases, specifying SSL3.0 can't result in SSL3.0 being used as it's been made unavailable, and as long as other protocols have been specified the connection will be negotiated without any problem. If SSL3.0 was the only protocol specified, then an exception would be thrown stating that a secure connection wasn't able to be negotiated. Throwing a different exception because SSL3.0 has been disabled via a different mechanism (hard coded in .NET networking code) is an inconsistent response to the same basic reason (support for the protocol has been disabled for security reasons).

Specifying the protocol to use is a negotiation and there's no guarantee that any one protocol that was specified can or will be used as there are other dependent factors (OS support, remote party protocol support etc). If SSL3.0 (or 2.0) is specified, simply removing it from the list passed down to lower layers (such as SCHANNEL) without any error or exception is compatible with the purpose of specifying which protocols to use in that it's a negotiation and there's no guarantee that everyone agrees to the same list. If only SSL3.0 or SSL2.0 are specified, then there are no alternatives so I could see failing fast and informing by exception that those protocols aren't supported. But in that situation you would be guaranteed a failure regardless of mechanism to disable the protocol and you wouldn't be breaking code which otherwise would continue working had a different mechanism been used to disable these protocols. When other more secure protocols have been specified, there's no need to fail the request, just don't use the insecure protocols.

I would suggest having the following behavior(s):
* Bitwise AND any specified protocols with the compliment of (SSL3 | SSL2) to disable their usage when applying the specified protocols (so as not to break round-tripping of property getter and setter values).
* Optionally throw an exception if only unsupported protocols have been specified.
* Optionally, if SSL3/SSL2 were specified along with other protocols but a secure connection was unable to be negotiated, have a special exception message noting that SSL3/SSL2 are no longer supported to give a hint to a possible cause

**Comment by davidsh** [comment]
cc: @CIPop @SidharthNabar

**Comment by davidsh** [comment]
cc: @stephentoub @ericstj @weshaggard 

Thx for raising this issue.  We are discussing it within our team.

One thing to keep in mind is that the Security Guidelines for new code and new platforms such as CoreFx will sometimes create new behaviors that are different from the legacy.NET Framework (Desktop). So, dropping support for Ssl30 for example is done because of the need to create more secure software.  WinHttpHandler, for instance does not support using Ssl30.

In terms one suggestion you had:

>There's no compile time error when writing code which is guaranteed to fail at runtime

that would require us "obsoleting" an enum value and having the C# compiler detect that in some way. I'm not aware of any compiler architecture that allows for adding 'obsolete' attributes to enum values whereas they can be added to methods.

We plan to get back to you next week with a more substantive response to your proposal.

**Comment by mconnew** [comment]
Just to be clear, I'm not suggesting functionally supporting SSL30, just a change in how it is no longer supported.
