### ISSUE TITLE
Add Marshal.Copy(IntPtr, IntPtr, int) method

### ISSUE THREAD

**Issue by axel-habermaier** [dotnet/corefx#493]
Currently, there is no way in the .NET framework to copy from a pointer to a pointer. All ```System.Runtime.InteropServices.Marshal.Copy``` overloads require a managed array as either the source or the destination. When doing low-level programming (in my case: graphics programming), however, you often need to copy from one pointer to another; for instance, to efficiently copy the contents of a struct to a mapped GPU constant buffer.

Libraries like SharpDX have a similar problem. Their workaround is to add such a method to the compiled assemblies using Mono.Cecil (using the ```cpblk``` instruction to perform the actual copy operation, which is not available from C#). My workaround is to compile an assembly written in IL using ilasm and using ILRepack to merge this tiny helper assembly into the actual one. Alternatively, I could PInvoke the native ```memcpy``` function, but I decided against that as I have the IL helper assembly for other reasons anyway (mostly: the ```calli``` instruction is not exposed by C#, but that's a language issue whereas the missing copy function is a framework issue).

To simplify this, I suggest to add an overload to the ```System.Runtime.InteropServices.Marshal``` class as follows:

```C#
void Copy(IntPtr source, IntPtr destination, int sizeInBytes)
```
This function would copy ```sizeInBytes``` many bytes from  ```source``` to ```destination```. The implementation of the method could either PInvoke the native ```memcpy``` function or use the managed ```cpblk``` instruction. Both seem to have mostly equivalent performance characteristics in the latest version of the runtime.

**Comment by pdelvo** [comment]
This might be relevant: http://frankniemeyer.blogspot.de/2014/07/methods-for-reading-structured-binary.html

**Comment by mikedn** [comment]
@axel-habermaier "there is no way in the .NET framework to copy from a pointer to a pointer"

.NET 4.6 adds [Buffer.MemoryCopy](https://msdn.microsoft.com/en-us/library/dn823273(v=vs.110).aspx)

**Comment by axel-habermaier** [comment]
@mikedn: Thanks! I hadn't noticed that.  Adding a similar method to the ``Marshal`` class might still be worthwhile, as that is where you might expect to find the method considering there are many other copy methods. But either way, I'm happy that there finally is a way to copy from pointer to pointer.

Interestingly, ```System.Buffer.MemoryCopy``` seems to use a custom implementation instead of calling the native ``memcpy`` function or using the ``cpblk`` instruction (and it seems to dynamically switch between a (custom) ``memcpy`` and a QCall ``memmove``). What's the reason for this? Additionally, should there maybe be two methods ```System.Buffer.MemoryMove``` and ```System.Buffer.MemoryCopy```, the former for (potentially) overlapping copies and the latter for non-overlapping ones?

**Comment by mikedn** [comment]
I'd say that this doesn't belong in the Marshal class as it has nothing to do with marshaling.

Regarding `cpblk` take a look at the reference source, there's a [comment](https://github.com/Microsoft/referencesource/blob/master/mscorlib/system/buffer.cs#L266) about it. And calling the native function directly would probably have too much overhead for small blocks so they attempt to avoid that.

**Comment by mburbea** [comment]
`cpblk` is really only slow on x86. On 4.5 or below this was true https://connect.microsoft.com/VisualStudio/feedback/details/766977/il-bytecode-method-cpblk-badly-implemented-by-x86-clr
4.5.1 supposedly improved the performance of this opcode, but its still slow. I don't know if they did anything but there is claim that they did.
x64 old and RyuJit it actually performs fairly well. RyuJit does a better job on pointer copying in general as it actually will use SSE2 instructions when I last looked at it. It might now use AVX on hardware that supports it for ultrafast copying. 

Ideally, I'd like some way to expose cpblk in C#.

**Comment by axel-habermaier** [comment]
Okay, so I guess this issue can be closed since an equivalent method will be introduced with .NET 4.6.

**Comment by sharwell** [comment]
I imagine the `cpblk` opcode was never fully optimized because the C# compiler was never actually emitting it. If the C# language was about to provide access to this opcode, I'm sure the JIT would be updated accordingly.

**Comment by mburbea** [comment]
Eh, in the x64/ryujit the opcode is pretty well written and on more modern hardware its current implementation is pretty good for medium sized structs on x86. It won't beat out native memcpy but it does a pretty good job.
