### ISSUE TITLE
Determine the correct PackageTargetFramework for the System.Buffers namespace

### ISSUE THREAD

**Issue by sokket** [dotnet/corefx#4931]
The PackageTargetFramework is potentially incorrectly set right now; the correct version should be determined per the conversation in #4898

**Comment by ericstj** [comment]
This should be set to `dotnet5.1`.

**Comment by ericstj** [comment]
Actually `dotnet5.2` due to https://github.com/dotnet/corefx/pull/5231.  This is already correct since https://github.com/sokket/corefx/commit/0aaeb54912848eecfb35b6bcaa4f6655b5da78a3
