### ISSUE TITLE
Consider exposing extension methods for System.Array .Net 2 convenience methods

### ISSUE THREAD

**Issue by mburbea** [dotnet/corefx#494]
With .net 2.0, `System.Array` was given a set of convenient LINQ like methods like those present on `List<T>`. Unlike `List<T>`, they were added as static methods. 
While, LINQ does offer some of these methods these variants do offer some differences/benefits as they are
A: Optimized for arrays.
B: Evaluated immediately. 
C: Always produce an array.

These methods are::

``` csharp
AsReadOnly<T>
BinarySearch<T>
ConvertAll<T>
Exists<T>
Find<T>
FindAll<T>
FindIndex<T>
FindLast<T>
FindLastIndex<T>
ForEach<T>
IndexOf<T>
LastIndexOf<T>
Sort<T>
TrueForAll<T>
```

Some of these offer no real benefit over LINQ, but others can be very useful especially in array heavy APIs like Reflection. Primarily `ConvertAll` and `FindAll`. These methods would also make it easier to work with arrays. There would be no clash with existing LINQ methods as they have different names.

**Comment by mikedn** [comment]
I'm not sure why should the core framework should introduce duplication. Such extension methods can be easily created by those who need them.

Also, ForEach<T> shouldn't be on this list, it's a useless method and is not available in some framework profiles.

**Comment by mburbea** [comment]
I agree about `ForEach`. I didn't realize it wasn't available on all profiles but it is somewhat annoying that these methods aren't exposed anywhere. There are other cases where some duplication exists in the core framework and its an unfortunate bit of history that these methods came out before extension methods. I'm sure if extension methods came out first or at the same time they either 
A) Wouldn't exist (Just use LINQ, LINQ has optimizations for Array)
B) Would have been made extension methods.

**Comment by Bhaal22** [comment]
Hi,

I would maybe add ConvertAll with a predicate as a paramer to combine a call to ConvertAll(list.FindAll(predicate)

**Comment by AdamSpeight2008** [comment]
Also consider making some of the exist methods on System.Array generic.

**Comment by terrajobst** [comment]
I don't understand what you're asking for. Are you asking for these methods to be added to `List<T>`? As you said, `Array` already exposes the methods you listed. AFAIK we didn't expose them all in first version of .NET Core (Windows Store) but we added most of them back since then.

**Comment by mburbea** [comment]
No, I'm asking to create a static class that would include them as extensions methods.
I'd like to be able to use `ConvertAll`/`FindAll` and methods like it as if they were instance methods.

e.g.
```csharp
var a = new[]{1,2,3,4,5,6};
a.FindAll(x=> x%2 == 0).ConvertAll(x=>x.ToString());
```
Right now, I have to do the chaining like so:
```csharp
var a = new[]{1,2,3,4,5,6};
Array.ConvertAll(Array.FindAll(a, x=> x%2 == 0)x=>x.ToString());
```

**Comment by joperezr** [comment]
We need a formal Api proposal if we want to go through with this.

Personally, given the methods are already exposed, I don't think there is a big gain with doing this.

**Comment by karelz** [comment]
We do not see huge value in doing this.
Closing as there hasn't been interested recently. If anyone wants to pick it up, provide API proposal, we will be happy to reopen.
