### ISSUE TITLE
Some ValidationAttributes are stateful.

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/corefx#4942]
CompareAttribute has the property OtherPropertyDisplayName, which is set to the otherProperty value you passed in until you call IsValid, at which point it becomes the other properties actual DisplayName.

RangeAttribute has an overload which takes a type and lets you give it string for Min and Max, however those strings aren't converted until you call FormatErrorMessage.

Both of these instances of statefulness make the attributes unpredictable and require gross hacks. If for example you call the Minimum property of RangeAttribute before and after calling FormatErrorMessage you might first get "0" then 0d (which is not a side effect one would expect without examining the source). Now you have to keep track of whether you've called that or not when looking at Minimum and Maximum so you know what to expect.

I understand that throwing in setters and Attribute constructors is bad, but perhaps the work could be done in the getters so that it's never wrong and any exceptions don't break attribute construction.

**Comment by karelz** [comment]
If anyone contributes the PR, we will consider it.

**Comment by divega** [comment]
One possible reason not to do this is compatibility. We are following up trying to figure out a general bar for that. cc @rowanmiller

**Comment by lajones** [comment]
We think the fix for this would probably consist of replicating the offending stateful members and making sure that the new members state was always the same regardless of what had been called before. The old members would have to be left as is for compatibility reasons.

**Comment by ajcvickers** [comment]
This is not something we plan to implement. However, a 100% non-breaking community contribution would be considered.
