### ISSUE TITLE
Redirected request's absolute uri is missing the query string information on CoreClr and Linux

### ISSUE THREAD

**Issue by kichalla** [dotnet/corefx#4945]
I have a http client which tries to communicate to a secure endpoint. This endpoint authorizes the request and redirects if the user is not authenticated.
Some of tests are failing due to different api behavior when on windows and linux platforms.

**CoreClr and Windows**
http://localhost:5000/Account/Login?ReturnUrl=%2Fadmin%2Fstoremanager <--- **this is fine**

---
http://localhost:5000/Admin/StoreManager
StatusCode: 302, ReasonPhrase: 'Found', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Date: Fri, 11 Dec 2015 20:03:29 GMT
  Location: http://localhost:5000/Account/Login?ReturnUrl=%2FAdmin%2FStoreManager
  Server: Kestrel
  Content-Length: 0
}

**CoreClr and Linux**
http://localhost:5000/Admin/StoreManager <--- **note this**

---

http://localhost:5000/Admin/StoreManager
StatusCode: 302, ReasonPhrase: 'Found', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Date: Fri, 11 Dec 2015 20:00:46 GMT
  Location: http://localhost:5000/Account/Login?ReturnUrl=%2FAdmin%2FStoreManager
  Server: Kestrel
  Content-Length: 0
}

**Repro**
```
using System;
using System.Net.Http;

namespace ConsoleApp24
{
    public class Program
    {
        public static void Main(string[] args)
        {
            WithAutoRedirect();
            Console.WriteLine("-------------");
            NoAutoRedirect();
        }

        private static void WithAutoRedirect()
        {
            var client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:5000/");
            var response = client.GetAsync("admin/storemanager").Result;
            Console.WriteLine(response.RequestMessage.RequestUri);
        }

        private static void NoAutoRedirect()
        {
            var clientHandler = new HttpClientHandler()
            {
                AllowAutoRedirect = false
            };
            var client = new HttpClient(clientHandler);
            client.BaseAddress = new Uri("http://localhost:5000/");
            var response = client.GetAsync("Admin/StoreManager").Result;
            Console.WriteLine(response.RequestMessage.RequestUri);
            Console.WriteLine(response);
        }
    }
}
```

cc @Tratcher

**Comment by davidsh** [comment]
cc: @stephentoub
