### ISSUE TITLE
tags don't correspond to nuget releases

### ISSUE THREAD

**Issue by vors** [dotnet/corefx#4950]
I tried to find the source for for
https://www.nuget.org/packages/System.Reflection.Metadata/ v 1.1.0
and
https://www.nuget.org/packages/System.Collections.Immutable/  v 1.1.37

Unfortunately, tags are out-of-sync with nuget releases.

**Comment by weshaggard** [comment]
Unfortunately we aren't at a place yet where we are producing our packages from our git repo, so there aren't any accurate sha's or tags. It is something we working to fix but it will take some time to get everything out in the open.

**Comment by mellinoe** [comment]
We do have tags and commit SHA's in the binaries now.
