### ISSUE TITLE
Increase Code Coverage for System.IO.FileSystem.AccessControl

### ISSUE THREAD

**Issue by dsgouda** [dotnet/corefx#4953]
@GiriSr as the owner of the System.IO.FileSystem.AccessControl library can you please have a look through the code review comments provided in https://github.com/dotnet/corefx/pull/4946 and address them appropriately.

**Comment by weshaggard** [comment]
We should also be sure to add some test coverage for this library.

**Comment by Priya91** [comment]
@dsgouda Can you assign this issue to the right owner of this library. Thanks!

**Comment by weshaggard** [comment]
The library owner is @GiriSr but we cannot assign it to him as he isn't part of the dotnet group yet.

**Comment by pjanotti** [comment]
Closing: current coverage at 84.9%
