### ISSUE TITLE
Visual Studio command Edit.RemoveUnusedUsings not available

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#4956]
For some reason, the command `Edit.RemoveUnusedUsings` is not available on (at least some) corefx projects on VisualStudio Community.  This is a recent development; some of my project history shows it _used_ to be present/working (within about the last two weeks).

**Comment by weshaggard** [comment]
Do you have the changes from PR https://github.com/dotnet/corefx/pull/4886? I'm not sure if that is why would cause this but it is something that broke other things in VS recently.

**Comment by Clockwork-Muse** [comment]
@weshaggard  no I didn't, that fixed it.  Argh, should have tried updating.
