### ISSUE TITLE
Remove non-cancellable overloads from async APIs

### ISSUE THREAD

**Issue by scalablecory** [dotnet/corefx#497]
I'd like to start discussion on removing the convenience overloads that call a cancellable API with `CancellationToken.None`:

````Task DoAsync()
{
    return DoAsync(CancellationToken.None);
}````

I think these overloads bloat the API and if you've got a large number of parameters, can be error-prone to implement.

I also believe they encourage poor design: consider that a great majority of async code either already does or should support cancellation. The use of these APIs should be relatively rare in good code.

**Comment by svick** [comment]
Wouldn't that be a pretty big compatibility break when porting code from "normal" .Net to .Net Core?

**Comment by n8ohu** [comment]
That's probably why they would have to have a good reason to change the behavior.

**Comment by davkean** [comment]
Thanks for the suggestion. Trying to understand the purpose here - by removing, do you mean literally remove? If so, we're not going to be removing any APIs - we care very much about compatibility, and most of .NET Core's surface area has previously shipped in earlier versions of Windows Store and Windows Phone applications.

I can see that there might be a suggestion here that says that we no longer provide these overloads for future versions.

**Comment by scalablecory** [comment]
@davkean It has been suggested elsewhere that .NET Core presents an opportunity to remove some of the older cruft. I'm asking these redundant overloads to be considered for this treatment. Like other APIs under consideration for removal from .NET Core, I'm not suggesting we remove them from the existing monolithic .NET distributions -- only from .NET Core.

**Comment by RichiCoder1** [comment]
My understanding is that .NET Core is less of a divorce from .Net Framework and more of a more Agile version. .Net core changes would eventually filter back into .Net Framework. Correct me if I'm wrong @davkean

**Comment by Alexx999** [comment]
@scalablecory I don't think that this overloads are particularly harmful. And, that's what overloads are for - you either use particular feature (cancellation) or you don't use it. And if you don't - you won't be punished by forcing you to type CancellationToken.None for every API call.
Please don't forget that WinRT API are async-only - developers using it will hate you for this idea :smile:

**Comment by scalablecory** [comment]
@Alexx999 My general opinion -- and I'm of no delusion that a lot of devs will disagree -- is that if you can write cancellable code, you should. It's so painless to pass a token along an invocation stack that there's really not much point in not supporting it. From that standpoint, these overloads are useless clutter.

As I said, I know a lot of people will disagree so I'm not strongly fighting for this -- I just wanted to start the conversation.

**Comment by stephentoub** [comment]
> @davkean It has been suggested elsewhere that .NET Core presents an opportunity to remove some of the older cruft. I'm asking these redundant overloads to be considered for this treatment

That's true, but David's point is that some of .NET Core has previously shipped:

> most of .NET Core's surface area has previously shipped in earlier versions of Windows Store and Windows Phone applications.

If surface area for .NET Core has shipped, those APIs won't be removed. Only for pieces that haven't shipped could they potentially be removed. And most of these async methods, e.g. on Stream, did on fact already ship.

A conversation about the right patterns moving forward for new APIs would be fine to have, though.

**Comment by Alexx999** [comment]
@scalablecory there is possible scenarios when you don't want cancellation.
For example, user clicks a "open file" button - in 99.9% of application you won't be able to cancel.
Or even better - you have an application that just passes data between source and destination - there is *absolutely no way* I'd want to cancel out sending that already started (except if user force-closes app - but it'll cancel in, well, forced way).

**Comment by stephentoub** [comment]
I'm going to close this issue out.  Moving forward when we look at adding new APIs, I agree we should keep this in mind, and we can discuss it on a case-by-case basis.  For existing APIs, however, we're not going to be able to remove them.
