### ISSUE TITLE
An argument for dnx to set the process name

### ISSUE THREAD

**Issue by muratg** [dotnet/corefx#4970]
_From @tuespetre on December 5, 2015 17:36_

Since ASP.NET 5 is aiming to provide a highly scalable, deployable, or otherwise 'cloud-friendly' approach to writing applications, I think it is important to discuss [the 'processes' components of the twelve-factor methodology:](http://12factor.net/processes)

> ... a production deploy of a sophisticated app may use many process types, instantiated into zero or more running processes.

In order to properly identify the running instances of a process, it can be useful for each process to have a distinct name. This allows processes to be easily identified through various user interfaces and command line utilities that provide information on a node's running process, and if set via command-line arguments, allows other utilities like Powershell DSC to distinguish the instances of the running processes that they are supposed to manage.

I realize this can be implemented within each application with very little effort but I hadn't seen a discussion on this yet so I wanted to hear some other opinions.

_Copied from original issue: aspnet/dnx#3235_

**Comment by muratg** [comment]
_From @davidfowl on December 5, 2015 17:38_

We're not adding any features to DNX since it won't be used past RC1. The good news is this will be the default when using the new CLI. Each app with get a unique process name (matching the application name).

**Comment by muratg** [comment]
_From @benaadams on December 5, 2015 17:49_

w00p! :+1:

**Comment by muratg** [comment]
_From @tuespetre on December 5, 2015 18:23_

DNX won't be used anymore? As in, DNX is going away? Also, will the process name account for multiple instances of a running process, or will there be more of a bias to writing an application to use a configurable number of worker threads?

**Comment by muratg** [comment]
_From @benaadams on December 5, 2015 18:30_

@tuespetre is moving to [.NET Command Line Interface](https://github.com/dotnet/cli) it was announced at Connect(); // 2015 and should be the way for RTM (as I understand)

**Comment by muratg** [comment]
_From @davidfowl on December 5, 2015 18:33_

> DNX won't be used anymore? As in, DNX is going away? 

Yes.

> Also, will the process name account for multiple instances of a running process, or will there be more of a bias to writing an application to use a configurable number of worker threads?

What does that mean? You get an executable file in your output folder (like the old days). The hosting model for websites is still a process per site.

**Comment by muratg** [comment]
_From @tuespetre on December 5, 2015 18:37_

Ah, the CLI is something I missed entirely. It looks wonderful!

@davidfowl: I am talking about deployment and scalability, like managing multiple instances of the same process on a server. Think queue processors, etc.

**Comment by muratg** [comment]
_From @davidfowl on December 5, 2015 18:38_

@tuespetre What are you asking about that specifically? You want to set each title of your running app? 

```
mywebapp.exe (1)
mywebapp.exe (2)
...
mywebapp.exe (n)
```

Something like that? I'm not sure what feature you are asking for...

**Comment by muratg** [comment]
_From @tuespetre on December 5, 2015 18:40_

That is correct.

**Comment by muratg** [comment]
_From @davidfowl on December 5, 2015 18:41_

How would you do that if you could do it programmatically?

**Comment by muratg** [comment]
_From @tuespetre on December 5, 2015 19:22_

I would pass the desired process name as a command line argument when instantiating each process.

As I said, this doesn't take much at all to implement within each application that would even need this, so it may just fall under the category of 'other' and not really belong with the 'dnx' or 'dotnet run' commands.

**Comment by ellismg** [comment]
What's the action item here?

**Comment by muratg** [comment]
The ask is being able to name the process instance.

MyApp (1)
MyApp (2)
MyApp (3)

Think of a web farm scenario.

**Comment by stephentoub** [comment]
@muratg, are you requesting a new API in System.Diagnostics.Process.dll, something like:
```
public class ProcessStartInfo
{
    public string DisplayName { get; set; } // defaults to null, which means use the default
    ...
}
```
How would you suggest that be implemented on Windows?  I may be missing some functionality with CreateProcess that would support that, but the only way I'm aware of supporting that on Windows is by creating a copy of the executable (or a link) with the desired name and executing that, and that's not something Process should be in the business of... if the goal here is for dnx / dotnet to support such names, that that copying/linking-then-executing-then-deleting functionality is something that the command line should provide, not the core Process type.

**Comment by benaadams** [comment]
Is a request from @tuespetre

**Comment by stephentoub** [comment]
I don't understand why it was moved to the corefx repo.

**Comment by muratg** [comment]
@davidfowl recommended to move this to this repo. I see your point on Windows though... 

@davidfowl Any thoughts on Windows implementation of this functionality? I agree with @stephentoub that Process should not be in the business of messing with file names etc.

**Comment by pallavit** [comment]
I agree that Process is not the right place for this. May be CLI can provide a functionality for this. @davidfowl Let me know if you disagree? If not, I would go ahead and close this.

**Comment by Maxwe11** [comment]
Definitely :+1: for this feature.

**Comment by pallavit** [comment]
Closing this issue as I don't think System.Diagnostics.Process is the right assembly to have this feature.
