### ISSUE TITLE
project.json PCL framework target meta package

### ISSUE THREAD

**Issue by muratg** [dotnet/corefx#4971]
_From @JamesNK on May 19, 2015 7:42_

Right now when defining a PCL framework target, all the individual assemblies used need to be specified in frameworkAssemblies. This is a pain: https://github.com/JamesNK/Newtonsoft.Json/blob/3cb2518b6c1d0cffb41c2c0b8aacbe0e60c63ec2/Src/Newtonsoft.Json/project.json#L61-L87

A classic PCL project automatically references all the assemblies and groups them together under references in solution explorer as ".NET". This is easy.

Make it easy, not a pain.

:smile_cat: 

_Copied from original issue: aspnet/dnx#1897_

**Comment by Maxwe11** [comment]
+:100:

**Comment by ericstj** [comment]
@cartermp can you have a look at this?

**Comment by ericstj** [comment]
This is really more of a CLI issue since CLI isn't matching the functionality of MSBuild.  I believe @cartermp is looking at this with the targeting pack packages work.

**Comment by cartermp** [comment]
Yup, this issue is called out here: https://github.com/dotnet/core/pull/64

All assemblies in a PCL target would be referenced by default, such that you won't need to specify any additional references.  Example:

```json
".NETPortable,Version=v4.0,Profile=Profile328": {
    "compilationOptions": {
        "define": [ "PORTABLE40" ]
     },
     "dependencies":{
         "Microsoft.TargetingPack.NETPortable.Profile328":"1.0.0"
     }
}
```

**Comment by ericstj** [comment]
Closing this as it is tracked with other feature work.
