### ISSUE TITLE
Add TryRent to ArrayPool Contract

### ISSUE THREAD

**Issue by jonmill** [dotnet/corefx#4979]
Discuss adding a TryRent function to the ArrayPool contract per discussion: https://github.com/dotnet/corefx/pull/4898

**Comment by sokket** [comment]
Pushing back to RTM since this is not necessary for RC2

**Comment by karelz** [comment]
We need formal API proposal.

**Comment by danmosemsft** [comment]
@sokket do you have interest in doing such formal API proposal to keep this moving?

Docs on the [API review process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md) and see [Jon's API request](https://github.com/dotnet/corefx/issues/4547) for a great example of a strong proposal. The more concrete the proposal is (e.g. has examples of usage, real-world scenarios, fleshed out API), the more discussion it will start and the better the chances of us being able to push the addition through the review process.

**Comment by sokket** [comment]
@danmosemsft Unfortunately, I have a full plate of Engineering Infrastructure work going on so I don't have time to draw up an API proposal :(

**Comment by GrabYourPitchforks** [comment]
Closing this issue as it seems to have gone stale. If there's renewed interest in adding this functionality, please reopen the issue.
