### ISSUE TITLE
HashSet<T> constructor performance tuning for ISet<T>

### ISSUE THREAD

**Issue by ChrisEelmaa** [dotnet/corefx#498]
As it is currently, `HashSet<T>` has a constructor that takes `IEnumerable<T>`. 

`var set1 = new HashSet<int>{2,3,4};`
`var set2 = new HashSet<int>(set1); // binds against ctor..(IEnumerable<T>)`

This works nicely, but the fact that we are "copying/cloning" from `ISet<T>` is not being taken advantange of.

 If we have `HashSet<T>` with  ~10000 elements, **there is no efficient way to create a copy of it**. Instead, current implementation will call internally `AddIfNotPresent` for each element in given `IEnumerable<T>`, eg, do an expensive element lookup for each item that is being added (to check if it doesn't exist in our current `HashSet<T>`).

This does not have to be the case. `ISet<T>` already promises us the uniqueness.

Let me know if this is something of interest, I would like to work on that.

**Comment by colombod** [comment]
Sounds quite a good spot you found!

**Comment by davkean** [comment]
One thing to think about, what if the underlying comparer is different between the two sets?

**Comment by mikedn** [comment]
Basically this optimization works only if the `IEnumerable<T>` you pass to the constructor is actually a `HashSet<T>` and uses the default comparer (or the comparer specified by the user if you use the constructor overload which takes a `IEqualityComparer<T>`).

Some hashset operations already do this [optimization](http://referencesource.microsoft.com/#System.Core/System/Collections/Generic/HashSet.cs,430) so maybe it's worth considering.

That said, if you do a lot of hashset copying maybe you should look into using `ImmutableHashSet<T>` instead.

**Comment by ChrisEelmaa** [comment]
Yeah, on second thought, that's true, @mikedn. `ISet<T>` does not expose `IEqualityComparer<T>`, but it probbaly wouldn't make sense to expose it anyways. The above optimization would work only with `HashSet<T>`, and if the comparers are equal.

**Comment by thomaslevesque** [comment]
This would be a useful optimization. See this StackOverflow question:
http://stackoverflow.com/questions/3927789/efficient-way-to-clone-a-hashsett

**Comment by ellismg** [comment]
@ChrisEelmaa I think this is a worthwhile improvement, I'm tagging this as "grabbed by community" under the assumption that you still want to do the work.  If so, go for it, I'll be happy to take a look at the PR once you have one.  If you're no longer willing to work on this, I understand, just let me know.

**Comment by ChrisEelmaa** [comment]
@ellismg, sounds good, I'll start working on it. Though, last I checked, there was no "System.Collections.Generic" in the master branch. Am I missing something?

**Comment by davkean** [comment]
@ChrisEelmaa You are correct, we've not yet ported the generic collections. I'm not sure, but I suspect it will be at least a month away.

**Comment by ellismg** [comment]
Fixed with #4349
