### ISSUE TITLE
SMTP Client does not use correct MediaType for Body when Alternate Views are Specified

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/corefx#4980]
Hi DotNet:
I've found a bug in System.Net.Mail.

First, here's how you replicate the issue:

````
var MessageTest = new System.Net.Mail.MailMessage(FromAddress, ToAddress);
MessageTest.Body = "<b>This is HTML</b>";
MessageTest.IsBodyHtml = true;

MessageTest.AlternateViews.Add(System.Net.Mail.AlternateView.CreateAlternateViewFromString("This is text", Encoding.ASCII, "text/plain"));

Server.Send(MessageTest);
````

You'll notice that I am sending an HTML email that has a plaintext alternate view.

The problem that occurs is that the message gets generated like so:
````
----boundary_0_f09cf3de-0b0f-45cf-960c-47ec45675f7e
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: quoted-printable

<b>This is HTML</b>
----boundary_0_f09cf3de-0b0f-45cf-960c-47ec45675f7e
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: quoted-printable

This is text
----boundary_0_f09cf3de-0b0f-45cf-960c-47ec45675f7e--
````

If you look at that content above, you'll see that the HTML part has its content-type as text/plain.

After digging through the System.Net.Mail.MailMessage class with JustDecompile, I have found the issue:

in the lines following the elseif
````
else if (this.AlternateViews.Count != 0 || this.Attachments.Count <= 0)
````
there is this line:
````
this.bodyView = AlternateView.CreateAlternateViewFromString(this.body, this.bodyEncoding, null);
````

You'll notice that null is passed in as the last parameter.  This is the error.  "text/html" should be passed in if IsBodyHtml is set to true and, otherwise, "text/plain" should be passed in.

Can you please fix this bug?

Thanks!

**Comment by SidharthNabar** [comment]
@TonyValenti - Thanks for reporting this. Question for you - what .NET platform were you using for this repro? I am asking since System.Net.Mail is not yet included in .NET Core. Were you trying this on .NET Framework 4.6 or such?

Note that this repo only tracks the code/issues in .NET Core platform.

Thanks,
Sid

**Comment by TonyValenti** [comment]
I may have reported this in the wrong place.  I was using .NET Framework
4.6.  Can you direct me to the correct place to post?

On Mon, Dec 14, 2015 at 5:12 PM, Sidharth Nabar <notifications@github.com>
wrote:

> @TonyValenti <https://github.com/TonyValenti> - Thanks for reporting
> this. Question for you - what .NET platform were you using for this repro?
> I am asking since System.Net.Mail is not yet included in .NET Core. Were
> you trying this on .NET Framework 4.6 or such?
>
> Note that this repo only tracks the code/issues in .NET Core platform.
>
> Thanks,
> Sid
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dotnet/corefx/issues/4980#issuecomment-164589988>.
>



-- 
Tony Valenti

**Comment by SidharthNabar** [comment]
Please use Microsoft Connect under Visual Studio: https://connect.microsoft.com/VisualStudio/feedback/
That will automatically open a bug in the right database internally. Thanks!
