### ISSUE TITLE
Reduce methods in UnaryExpression and BinaryExpression don't honor mutable struct semantics

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/corefx#4984]
Found while working on extended expression tree support for C#:

``` csharp
// Prints 5
{
    var s = new S();
    s.X += 5;
    Console.WriteLine(s.X);
}

// Prints 0
{
    var s = Expression.Parameter(typeof(S), "s");
    var x = Expression.Field(s, "X");

    var e =
        Expression.Lambda<Action>(
            Expression.Block(
                new[] { s },
                Expression.Assign(s, Expression.New(typeof(S))),
                Expression.AddAssign(x, Expression.Constant(5)),
                Expression.Call(typeof(Console).GetMethod("WriteLine", new[] { typeof(int) }), x)
            )
        );

    var f = e.Compile();
    f();
}
```

where

``` csharp
struct S
{
    public int X;
}
```

The culprit is in `ReduceMember` and `ReduceIndex` in `UnaryExpression` and `BinaryExpression` where the receiver of the LHS is copied to a temporary. Those should really capture a `ref` to the value rather than making a copy of the value.

Unfortunately, blocks don't support `ByRef` variables (if they would escape the stack frame, things would go terribly wrong of course), so options are:
- do nothing and consider this behavior to be expression-specific; extension nodes for languages like C# and VB need to deal with it themselves;
- make the copying behavior for receivers less aggressive; if the target is classified as a variable, the copy can be avoided (also the case of accessing a field with a mutable struct);
- use a write-back approach (not desirable knowing that there are perfectly suited IL instructions to deal with reference indirection for loads and stores);
- support ByRef variables in blocks which would need escape analysis in the lambda compiler to ensure verifiable code gets emitted.

Obviously, any change here would be considered a breaking change. Nonetheless, this is an interesting behavior that can cause issues when layering language-specific extension nodes on top of the existing API.

**Comment by bartdesmet** [comment]
Upon inspecting DLR specs, this may be by design, cf.

```
2.5.3 User-defined Setting Syntax 
Languages that have user-defined setting forms for storable locations should provide language-specific reducible nodes.  These nodes can reduce, for example, to a MethodCallExpression that takes the arguments defining the location and an argument for the value.  We don't provide extensibility for this sort of language feature. 
```

See http://www.codeplex.com/Download?ProjectName=dlr&DownloadId=246540 for details.

**Comment by JonHanna** [comment]
Would a field in a struct really count as a language's user-defined setting form?

**Comment by bartdesmet** [comment]
Very debatable indeed. The definition of a variable in C# is really capturing all the locations for which the runtime has the ability to get a reference with ldelema, ldflda, etc. So it still seems to me the DLR is deviating from this. In fact, it even adds write-back logic for indexers etc. which definitely are custom behavior layered on top of the runtime. All in all, I'm closer to regarding it as a bug. The doc quote about is the closest related info I could find.

@VSadov, what do you think?

Even if it is a bug, the compatibility argument may outweigh its severity...

**Comment by VSadov** [comment]
There are cases where implementing variables as byrefs is not possible (like in async), then compiler uses different approach. - array elements are handled as {array, index1, index2...} tuples for example.

It sounds like ExpressionTrees intentionally do not want to support aliasing nature of variables, possibly to get away with not allowing/requiring byref locals, which in turn makes is easier to deal with lambdas/closures.

I guess at this point we should encode language semantics in terms of what is available. That would be either copy-back (like in async), or by introducing helper methods that take byref arguments just to implement "deep setting".

**Comment by bartdesmet** [comment]
Sounds reasonable given the complexity byref locals would bring. They’re indeed intentionally rejected in Block factories which strengthens this hypothesis.
 
Right now, for named parameters, I’m dealing with ref parameters in a similar approach as async methods. There’s one pending change to ensure that exceptions from accessing by ref variables (null ref, out of bounds) don’t get reordered.
 
For compound assignments, I have specialized nodes already to deal with C#-specifics such a left/final conversion and support for delegates etc. Those reduce to assignment nodes in LINQ but when the variable needs a ref approach, I can follow a similar strategy as for named parameters.
 
Async reuses the stack spiller from LINQ (with minor modifications) and hence rejects by refs that’s have to be spilled. That will need separate treatment.
 
I’ll tackle them on my end in the order listed above.

**Comment by JonHanna** [comment]
@bartdesmet considering your suggestion at https://github.com/dotnet/corefx/issues/4984#issuecomment-165549413 that this may be by design because:

> 2.5.3 User-defined Setting Syntax 
Languages that have user-defined setting forms for storable locations should provide language-specific reducible nodes.  These nodes can reduce, for example, to a MethodCallExpression that takes the arguments defining the location and an argument for the value.  We don't provide extensibility for this sort of language feature.

I don't think this follows, because surely then it should apply to:
```C#
var s = Expression.Parameter(typeof(S), "s");
var x = Expression.Field(s, "X");

var e =
   Expression.Lambda<Action>(
       Expression.Block(
           new[] { s },
           Expression.Assign(s, Expression.New(typeof(S))),
			Expression.Assign(x, Expression.Add(x, Expression.Constant(5))),
           Expression.Call(typeof(Console).GetMethod("WriteLine", new[] { typeof(int) }), x)
       )
   );

var f = e.Compile();
f();
```

But that code prints `5`. If it's not a bug that the expression you opened this issue with prints `0` on the basis of §2.5.3, then it's a bug that this code does.

**Comment by VSadov** [comment]
After rereading this again this seems to be ByDesign from the Expression Trees prospective. The functionality seems intentionally limited and there are compat concerns.

This should be dealt with at the higher level. We can reactivate this issue if it is found to be impossible.
