### ISSUE TITLE
Provide a way for developers to self-instantiate a server for networking API tests

### ISSUE THREAD

**Issue by SidharthNabar** [dotnet/corefx#4989]
Most of the tests for networking APIs (e.g. System.Net.Sockets, System.Net.Http, etc.) depend on a setup where the client machine exchanges data with a remote server (since loopback to same host introduces unsolicited optimizations). In order to allow developers to test their PR locally, it would be great to have a script that sets up a server on their machine with a consistent set of configurations, features and settings. The developer can then run the suite of tests against this server to validate their PR.

Today, tests run the tests against an Azure server. This issue tracks the creation and publishing of a script for setting up a local server.

**Comment by davidsh** [comment]
Closing this as per PR #9715
