### ISSUE TITLE
System.IO.Compression : Consider protection against zip bombs

### ISSUE THREAD

**Issue by blowdart** [dotnet/corefx#4994]
As folks tend to use the built in classes for random zipping and unzipping they are vulnerable to zip bombs. 

Consider adding a way to protect against this. Typically this involves decompressing in a separate process which is time limited, or examining the file entries looking for nested compressed files.

**Comment by JonHanna** [comment]
Are zip bombs possible without nested zips?

Is there automatic recursion on unzipping?

**Comment by blowdart** [comment]
I don't believe it's possible without nested zips. Limiting unzipping to the first layer would also be effective

**Comment by stephentoub** [comment]
@blowdart, can you provide a repro for the problem with the existing System.IO.Compression types? Thanks.

**Comment by ianhays** [comment]
Zip bombs are only an issue when there is automatic recursion on unzipping as @JonHanna mentioned. 

System.IO.Compression.ZipFile.ExtractToDirectory does not recursively unzip. Zips within zips are treated as files, not as directories. 

repro:
```
        [Fact]
        public static void RecursiveZip()
        {
            ZipFile.ExtractToDirectory(bad("recursive_6.zip"), "unzipped");
        }
```
where recursive_6.zip contains six layers of nested zip files. The resulting "unzipped" folder contains the first layer of zip files, still zipped.
