### ISSUE TITLE
Address PR code review feedback for ported System.Threading.AccessControl

### ISSUE THREAD

**Issue by venkat-raman251** [dotnet/corefx#4998]
@GiriSr as the owner of the System.Threading.AccessControl library can you please have a look through the code review comments provided in https://github.com/dotnet/corefx/pull/4996 and address them appropriately.

**Comment by venkat-raman251** [comment]
PR #4996

**Comment by weshaggard** [comment]
@gbaltas is the owner of the ACLs libraries so assign to him.

**Comment by kouvel** [comment]
Looks like the PR has been merged a while back, closing

**Comment by weshaggard** [comment]
@kouvel this issue was supposed to track all the feedback from that merged PR that didn't get addressed with the PR.

**Comment by kouvel** [comment]
Oh I misread that, reopening

**Comment by alexperovich** [comment]
@kouvel are you currently working on this?

**Comment by kouvel** [comment]
Not currently, removed my assignment
