### ISSUE TITLE
Corefx test hang from System.Net.Utilities.Functional.Tests 

### ISSUE THREAD

**Issue by sejongoh** [dotnet/corefx#5002]
Configuration:
 Debug CoreCLR runtime: coreclr.dll, corerun.exe and mscorlib.dll
 CoreFX assemblies and CoreFX tests: release

Linux environment: 
Ubuntu 14.04 LTS on Hyper-V

The following test doesn't finish with **one virtual processor** on Hyper-V.

./corerun  xunit.console.netcore.exe System.Net.Utilities.Functional.Tests.dll -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=nonlinuxtests -notrait Benchmark=true

*** GDB stack traces for all threads ***
[thread_backtrace.txt](https://github.com/dotnet/corefx/files/63367/thread_backtrace.txt)

*** SOS clr stack ***

(lldb) sos ClrStack
OS Thread Id: 0x1762 (1)
        Child SP               IP Call Site
00007FFFFFFFD028 00007FFFF79C4414 [HelperMethodFrame_1OBJ: 00007fffffffd028] System.Threading.WaitHandle.WaitOneNative(System.Runtime.InteropServices.SafeHandle, UInt32, Boolean, Boolean)
00007FFFFFFFD160 00007FFF7C4F9F32 System.Threading.WaitHandle.InternalWaitOne(System.Runtime.InteropServices.SafeHandle, Int64, Boolean, Boolean)
00007FFFFFFFD180 00007FFF7C4F9DDE System.Threading.WaitHandle.WaitOne(Int32, Boolean)
00007FFFFFFFD1B0 00007FFF7C31C45E Xunit.ConsoleClient.Program.ExecuteAssembly(System.Object, System.String, Xunit.XunitProjectAssembly, Boolean, Boolean, Boolean, Boolean, System.Nullable`1<Boolean>, System.Nullable`1<Int32>, Xunit.XunitFilters)
00007FFFFFFFD2B0 00007FFF7C31521F Xunit.ConsoleClient.Program.RunProject(System.String, Xunit.XunitProject, Boolean, Boolean, Boolean, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Int32>)
00007FFFFFFFD420 00007FFF7C2FA889 Xunit.ConsoleClient.Program.Main(System.String[])
00007FFFFFFFD8D0 00007FFFF5FB21DF [GCFrame: 00007fffffffd8d0]
00007FFFFFFFDF80 00007FFFF5FB21DF [GCFrame: 00007fffffffdf80]

*** SOS threads ***

(lldb) sos Threads
ThreadCount:      9
UnstartedThread:  0
BackgroundThread: 4
PendingThread:    0
DeadThread:       4
Hosted Runtime:   no
                                                                                                        Lock
       ID OSID ThreadOBJ           State GC Mode     GC Alloc Context                  Domain           Count Apt Exception
   1    1 1762 00000000006648F0  2020020 Preemptive  00007FFF5C1C03A0:00007FFF5C1C1FD0 0000000000645A80 0     Ukn
   7    2 176b 0000000000688D70    21220 Preemptive  0000000000000000:0000000000000000 0000000000645A80 0     Ukn (Finalizer)
XXXX    3    0 0000000000864760    31820 Preemptive  0000000000000000:0000000000000000 0000000000645A80 0     Ukn
XXXX    4    0 00007FFF5000EFC0    31820 Preemptive  0000000000000000:0000000000000000 0000000000645A80 0     Ukn
  11    5 176f 0000000000890AF0  2021220 Preemptive  00007FFF5C1B5E68:00007FFF5C1B5FD0 0000000000645A80 0     Ukn
  12    6 1770 0000000000943B50  2021220 Preemptive  00007FFF5C210200:00007FFF5C212040 0000000000645A80 0     Ukn
XXXX    7    0 00007FFF5007D840  1031820 Preemptive  0000000000000000:0000000000000000 0000000000645A80 0     Ukn (Threadpool Worker)
XXXX    8    0 00007FFF48015D20  1031820 Preemptive  0000000000000000:0000000000000000 0000000000645A80 0     Ukn (Threadpool Worker)
  16    9 1775 00007FFF3C000F50  1020220 Preemptive  0000000000000000:0000000000000000 0000000000645A80 0     Ukn (Threadpool Worker)

**Comment by davidsh** [comment]
@mellinoe @pgavlin PTAL
cc: @CIPop

**Comment by mellinoe** [comment]
Do you know which individual test is hanging? I suspect it's the one this PR is changing:

https://github.com/dotnet/corefx/pull/4983
(Tests.UnixPingUtilityTests.PacketSizeIsRespected)

**Comment by stephentoub** [comment]
I believe this hanging test was fixed with #4983, so I'm closing.  If this still repros with that fix, please reopen.
