### ISSUE TITLE
WindowsIdentity.Name is missing from the System.Security.Principal.Windows contract

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#5003]
The test code at 
https://github.com/dotnet/corefx/blob/master/src/System.Security.Principal.Windows/tests/WindowsIdentityTests.cs 

References `WindowsIdentity.Name`: `Assert.Throws<ObjectDisposedException>(() => identity.Name);`
which is not present in the contract defined within the respective `ref` folder.

This is currently working because the test code references the `src` project.

It's unclear what the right fix is: add the `Name` property to the contract or remove the test reference.

@AtsushiKan @ericstj @nguerrera @weshaggard @bartonjs PTAL (usernames determined based on GitHub history for src)

**Comment by weshaggard** [comment]
This does seem like an oversight but I will let @bartonjs say for sure one way or the other.

**Comment by bartonjs** [comment]
It's true that the contract doesn't define `public override string Name` on WindowsIdentity; but I think that would just cause a `base.Name` binding error on derived types.

ClaimsIdentity does define the Name property (and WindowsIdentity : ClaimsIdentity), so it feels like things should be compiling... https://github.com/dotnet/corefx/blob/c02d33b18398199f6acc17d375dab154e9a1df66/src/System.Security.Claims/ref/System.Security.Claims.cs#L58

@weshaggard I assume that we should have the override described in the contract anyways, yes?

**Comment by weshaggard** [comment]
It is usually a good idea to include overrides in the contracts as well to make sure base calls don't skip the your particular implementation.
