### ISSUE TITLE
Respond to PR code review comments for ported library System.Security.Crypto.Algorithms

### ISSUE THREAD

**Issue by venkat-raman251** [dotnet/corefx#5008]
@bartonjs as the owner of the System.Security.Crypto.Algorithms library can you please have a look through the code review comments provided in https://github.com/dotnet/corefx/pull/5005 and address them appropriately.

Edit: For clarity, the issues are
- [ ] See if the TFS Desktop-targetting build can succeed when using Array.Empty<byte>().
- [ ] The desktop facade is facading against net46, but 4.6.1 is the minimum compatible version.

**Comment by bartonjs** [comment]
@venkat-raman251 I'm not sure what the objective is here...

**Comment by weshaggard** [comment]
@bartonjs as part of the porting effort we are mainly doing mechanical porting and less changes to the actual code but we are getting code review feedback. So to track responding to the code review feedback we are filing issues for the owner of the library to follow-up on those. If there isn't anything to follow-up on then feel free to close.

**Comment by justinvp** [comment]
@venkat-raman251 maybe the titles of these issues should be something like "Respond to code review feedback from porting X.Y.Z" rather than "Refactoring X.Y.Z" to make it a little more clear to the library owners what needs to be done?

**Comment by weshaggard** [comment]
@venkat-raman251 I agree with @justinvp please add a little more details in these issues explaining their purpose and ideally linking back to the feedback comments themselves.

**Comment by weshaggard** [comment]
I updated the title and the initial comment to reflect the purpose more.

**Comment by karelz** [comment]
@bartonjs can you please double check the work needed here? Please mark it "up for grabs" if appropriate.

**Comment by bartonjs** [comment]
Now that we have the netfx runs running and we have better baselining support, this has effectively resolved itself.  Closing the issue.
