### ISSUE TITLE
Request: Add Interlocked.Exchange/CompareExchange(ref bool)

### ISSUE THREAD

**Issue by tenor** [dotnet/corefx#5011]
`Interlocked.Exchange/CompareExchange` accepts ints, longs and some other types but not bool, which forces me to declare int fields that only behave like bools just so I can use Interlocked methods.

**Comment by stephentoub** [comment]
Thanks, but this would require platform-level support that doesn't exist.  See https://github.com/dotnet/coreclr/issues/1070.
