### ISSUE TITLE
File.GetFileAttributes doesn't get symbolic link data on Unix

### ISSUE THREAD

**Issue by mjrousos** [dotnet/corefx#5015]
Directories which are symbolic links or junctions (made with mklink /d or /j) on Windows have the FileAttributes.ReparsePoint flag set in their attributes.

On *nix platforms, though, symbolic links (made with ln -s) have no special attributes set.

A better user experience would be to use the ReparsePoint flag on such file or, possibly, to add new Unix-specific flags if the ReparsePoint one is inapplicable for some reason.

**Comment by mjrousos** [comment]
I found the problem. When populating file stats on Unix ([FileSystemInfo.Unix@231](https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System/IO/FileSystemInfo.Unix.cs#L231)), stat is called instead of lstat. The result is that in the case of a sym link, attributes for the *target* of the link are retrieved instead of attributes for the sym link itself.

I'll open a PR to change this.

**Comment by Priya91** [comment]
> I'll open a PR to change this.

@mjrousos are you working on this?

**Comment by mjrousos** [comment]
Yep, this is fixed by dotnet/corefx#5020. I just need to fix up the test cases I added and it should be ready to merge. I hope to do that tonight.
