### ISSUE TITLE
Path.GetFullPath doesn't understand ~ on Mac/Linux

### ISSUE THREAD

**Issue by mjrousos** [dotnet/corefx#5016]
Attempting to convert a path beginning with the home symbol (~) to a full path using Path.GetFullPath does not work as expected. Rather, the path (including the ~) is appended onto the current working directory, which is incorrect (and not even a valid path).

**Comment by JeremyKuhne** [comment]
Thanks for the report! I'll look into this after the holiday.

**Comment by stephentoub** [comment]
Isn't ```~``` purely a shell convention on Unix?  For example, in C I can use mkdir to create a directory anywhere named ```~```, and if I use ```open``` to open a file named ```~/tmp.txt```, it doesn't expand ```~``` to mean the ```$HOME``` environment variable but instead looks for that exact file name, with ```~``` as a perfectly valid character in a path name.  Given this, I don't think Path should be updated to provide any special treatment of ```~```, at least not by default.

**Comment by mjrousos** [comment]
Hmm... good point, @stephentoub. Given that ~ is a valid path character, I think you're right that Path probably shouldn't special-case it.

**Comment by mjrousos** [comment]
I'll close this for now; please feel free to re-open if there are other reasons that Path should do something special with ~.
