### ISSUE TITLE
Corefx test hangs but it finishes with sudo

### ISSUE THREAD

**Issue by sejongoh** [dotnet/corefx#5025]
Configuration:
 Debug CoreCLR runtime: coreclr.dll, corerun.exe and mscorlib.dll
 CoreFX assemblies and CoreFX tests: release

Linux environment: 
 Ubuntu 14.04 LTS on Hyper-V

- run-test.sh hangs after most or a lot of test suites are executed.
- From top or ps, there is no coreclr process.
- However, 'sudo run-test.sh ...' doesn't hang.

**Comment by mellinoe** [comment]
Are you able to tell if the process is hanging at any particular test (from the console output maybe)?

**Comment by mellinoe** [comment]
@sejongoh Is this the same issue as https://github.com/dotnet/corefx/issues/5002? I suspect it might be that Ping test I linked in the #5002. Ping uses a different codepath if you have elevated privileges, so that may be why it behaves differently using `sudo`.

**Comment by sejongoh** [comment]
This issue might be different from #5002 since there is no running coreclr process, but run-test.sh hangs. So, I cannot find any particular test. I will provide the console output.

**Comment by sejongoh** [comment]
I cannot reproduce this problem anymore although it consistently hung before trying with sudo. What I did is just to run run-test.sh with sudo. After that, run-test.sh finishes well without sudo.

**Comment by stephentoub** [comment]
I believe this was fixed with #4983, so I'm closing. If this still repros with that fix, please reopen.
