### ISSUE TITLE
String resources need to be configurable on a per-configuration basis

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#5040]
Right now, string resources are included by default in an assembly if there exists a "Strings.resx" file in a "Resources" subdirectory under the csproj. All of the string resources in that file are included in the assembly, even if they are not used at all, or if only a subset are used. You can "opt-out" in a sense by changing the directory that the resource targets look in for the "Strings.resx" file (the `ResourcesSourceOutputDirectory` Property).

This has worked fine for our projects with a single configuration, or with only a few similar configurations. However, this can cause significant bloat in assemblies which don't need those resources. For example, full-facade projects are generally around 5-6 KB in total size. With unnecessary string resources included, they can easily bloat to 25-30 KB each. To a lesser extent, configurations which only need a subset of the resources are also bloated by having extra strings in them.

In our internal build, I recall we used text files that allowed condition inclusion/exclusion of certain strings, based on the project's DefineConstants. We might want to look into something similar to that in order to accomodate this.

**Comment by mellinoe** [comment]
@weshaggard How do you feel about this one right now? I think that many configurations of our libraries are currently shipping with a lot of unnecessary string resources. Most occurrences of this can be fixed by removing all resources (i.e. desktop facades), but some would optimally have more fine-grained control (i.e. use only half of the resources for one configuration, use half for another). Do you think this is something we should try to address for RTM, or are we okay with shipping a few extra "dead resources" until we can clean it up all at once?

**Comment by weshaggard** [comment]
I wonder if we couldn't figure out a way to always just select the resources that are used for the set of code, perhaps using Roslyn or something. cc @tarekgh

**Comment by tarekgh** [comment]
@weshaggard we need to be careful here as I recall seeing some places that constructing the resource keys on the fly so Roslyn analysis can break such cases. 
I have another open issue which is suggesting tagging the resources to exclude them during the compilation. I think if we do this right, we can have a good solution for this issue. but I don't think this is issue I'll address before RTM.

**Comment by tarekgh** [comment]
by the way, we can use Roslyn analysis to know how much extra resources we are shipping so we can know if we need to fix for the RTM or it can wait.

**Comment by mellinoe** [comment]
We discussed this a bit more today. It doesn't seem very important to fix right now, but like @tarekgh said above, it would be good to get better information on how severe the size bloat is because of this.

Another thing that was brought up: with the .NET Standard 2.0 work, we've added a lot of duplicate string resources across assemblies in corefx. Although they may be used in all of the assemblies, they still constitute unnecessary duplication and bloat. A possible solution could be creating a `System.Private.Resources` assembly containing common strings.

**Comment by ViktorHofer** [comment]
I'm not convinced we need to do anything here after we trimmed most of the assemblies and removed dead code / resources. Not sure, but the linker that we now use could also remove additional bloat. Closing for now. Feel free to reopen if you disagree.
