### ISSUE TITLE
System.IO.MemoryMappedFiles.Tests:  Test failures with Assert.Throws() Failure\nExpected: typeof(System.UnauthorizedAccessException)\nActual:   (No exception was thrown

### ISSUE THREAD

**Issue by sejongoh** [dotnet/corefx#5041]
The error message is the same as #5039 but the failures are from a different test set.

**Configuration**

 Debug CoreCLR runtime: coreclr.dll, corerun.exe and mscorlib.dll
 CoreFX assemblies and CoreFX tests: release

**Linux environment**

 Ubuntu 14.04 LTS on Hyper-V

 Run run-test.sh **with sudo** to avoid a hang issue reported in #5025 

**Test names**
```
./bin/tests/Linux.AnyCPU.Release/System.IO.MemoryMappedFiles.Tests/dnxcore50/testResults.xml:      <test name="System.IO.MemoryMappedFiles.Tests.MemoryMappedFileTests_CreateFromFile.ReadOnlyFile(access: ReadWrite)" type="System.IO.MemoryMappedFiles.Tests.MemoryMappedFileTests_CreateFromFile" method="ReadOnlyFile" time="0.5725973" result="Fail">
./bin/tests/Linux.AnyCPU.Release/System.IO.MemoryMappedFiles.Tests/dnxcore50/testResults.xml:      <test name="System.IO.MemoryMappedFiles.Tests.MemoryMappedFileTests_CreateFromFile.ReadOnlyFile(access: CopyOnWrite)" type="System.IO.MemoryMappedFiles.Tests.MemoryMappedFileTests_CreateFromFile" method="ReadOnlyFile" time="0.0054959" result="Fail">
```	  

**Stack trace**

```
<test name="System.IO.MemoryMappedFiles.Tests.MemoryMappedFileTests_CreateFromFile.ReadOnlyFile(access: ReadWrite)" type="System.IO.MemoryMappedFiles.Tests.MemoryMappedFileTests_CreateFromFile" method="ReadOnlyFile" time="0.5725973" result="Fail">
<failure exception-type="Xunit.Sdk.ThrowsException">
  <message><![CDATA[Assert.Throws() Failure\nExpected: typeof(System.UnauthorizedAccessException)\nActual:   (No exception was thrown)]]></message>
  <stack-trace><![CDATA[   at System.IO.MemoryMappedFiles.Tests.MemoryMappedFileTests_CreateFromFile.ReadOnlyFile(MemoryMappedFileAccess access)]]></stack-trace>
</failure>
</test>
```

**Comment by stephentoub** [comment]
@sejongoh, can you determine what's different between your configuration and the one used in CI?  I'm not seeing these failures with a similar set up locally, and the CI set up for Ubuntu looks like what you have as well.

**Comment by sejongoh** [comment]
I think that the difference is sudo. I ran testing with sudo to avoid #5025. The test passes without sudo.

**Comment by ianhays** [comment]
Both this issue and #5039 are results of running the tests as the superuser, I can repro the test failures when running them under sudo, but I'm uncertain how much of an issue that is. 

I assume we want all tests to pass under sudo which means we'll need to add logic to exclude the tests when permissions are elevated such that ReadOnly files may be modified.

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/corefx/pull/5520
