### ISSUE TITLE
TargetingPackReference items show up in VS Solution Explorer

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#5042]
This has no real negative effect, it's just kind of annoying. We should consider putting the `<InProject>false</InProject>` metadata on the includes, which hides them from the solution explorer.

**Comment by mellinoe** [comment]
Actually this is a bit more annoying when a project needs to reference System.dll. If that is in the Solution Explorer, then none of the source files under the "System" folder show up (which is 99% of our source files...)

**Comment by mellinoe** [comment]
For now we should include the TargetingPackReference ItemGroup at the end of the csproj. If we do that, VS will at least show the "System" folder node correctly, although it will still show the annoying reference nodes.

**Comment by ericstj** [comment]
Can you use ItemDefinitionGroup to apply <InProject>false</InProject> to all TargetingPackReference items?

**Comment by mellinoe** [comment]
I can't remember why at this point, but I did look into ItemDefinitionGroup and found that it didn't work for whatever reason. It seemed like VS didn't take that into account when populating the Solution Explorer nodes.

**Comment by karelz** [comment]
Next step: Find out how to make VS to not show them.

**Comment by weshaggard** [comment]
We don't use TargetingPackReference any longer so closing this issue as it isn't relevant any longer.
