### ISSUE TITLE
System.Runtime.Extensions should be 4.1.0.0

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#5050]
There were API changes since the last stable version so we need to update minor version.

**Comment by davidfowl** [comment]
API changes mean a new platform standard version right?

**Comment by ericstj** [comment]
That depends.  If the new API can be completely OOBed to the all the existing frameworks supporting that platform standard version it will not generate a new version.

In this case we can OOB it completely.

Another example was a recent AppContext change.  That required changes to desktop which is why I had to add a new version in https://github.com/NuGet/NuGet.Client/pull/105.
