### ISSUE TITLE
Clean up and Format System.Collections

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#5055]
There's quite a few things in this project that should be cleaned up, not limited to:

* Remove/sort usings
* Use C# alias over type name (`Object` -> `object`, `Int32` -> `int`, etc.)
* Non-compliant field names
  * We need to be careful about renaming these, we've hit issues in the past where Debugger components were relying on the exact names of these fields to not change.
* General block/braces formatting

**Comment by ianhays** [comment]
Oh yeah, and the tests are even worse. I'm working on an overhaul of the tests as a solution to https://github.com/dotnet/corefx/issues/754 and have been finding lots of weird little inconsistencies (and bugs) in the src code as well like the ones you've mentioned. There are some comments that desperately need a re-phrasing as well.

**Comment by bmay2** [comment]
I removed unused usings, replaced type names with C# aliases, and ran the CodeFormatter tool for the solution. Should I open a PR or are there other benchmarks to hit first?

**Comment by ctyar** [comment]
Is it ok to a send PR for this?

**Comment by danmosemsft** [comment]
Any PR that fixes style to match the repo guidelines would be welcome.

**Comment by ctyar** [comment]
@danmosemsft Regarding this, is there somewhere i have to check before changing anything?
> Non-compliant field names
We need to be careful about renaming these, we've hit issues in the past where Debugger components were relying on the exact names of these fields to not change.

**Comment by danmosemsft** [comment]
cc @mellinoe re the question above.
