### ISSUE TITLE
Invalid Server Name Exception will return Name Piped error message in Windows VS TCP in UNIX

### ISSUE THREAD

**Issue by kkurni** [dotnet/corefx#5060]
Repro :

```
 static void Main(string[] args)
        {
            try
            {
                TestConnectionString("Data Source=NotAServer;Initial Catalog=Northwind;User ID=xx;Password=xxx;Connect Timeout=30");
            }
            catch (Exception ex)
            {
                Console.WriteLine("Exception : " + ex.Message);
            }

        }
   public void TestConnectionString(string connstr)
        {
            using (var conn = new SqlConnection(connstr))
            {
                Console.WriteLine("Conn Open..." + connstr);
                conn.Open();

                Console.WriteLine("create command...");
                var cmd = new SqlCommand("select @@Version", conn);

                Console.WriteLine("Execute reader...");
                using (var reader = cmd.ExecuteReader())
                {

                    Console.WriteLine("read...");
                    while (reader.Read())
                    {
                        Console.WriteLine(reader.GetString(0));
                    }
                }
            }
        }
```

***EXCEPTION***
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: **Named Pipes*** Provider, error: 40 - Could not open a connection to SQL Server)

But in unix it will return
**.....TCP Provider ...***, 

***Expected***
We just need to make consistent for this. whether we should return Named Pipes / TCP if there is invalid server name. 

Or ***This can be the expected behavior*** as Unix only support TCP provider at this moment,
but Windows try to connect this with TCP first and Namepipe, and since Name pipe was the last provider than Name pipe was picked up.

**Comment by kkurni** [comment]
CC @saurabh500 @corivera

**Comment by corivera** [comment]
The Named Pipe provider error is from native SNI, and is a pretty old thing. I think it's the default option for the connection error message. I changed it to TCP provider in managed SNI since it IS actually a TCP error. Once we deprecate native SNI for project K, this won't be an issue.

**Comment by kkurni** [comment]
I try to reproed this on my ubuntu machine, and I didn't see any failure. 
Probably this is related with SSL handshake in OSX.

(Still waiting for results in OSX)

```
public void TestConnectionString(string connstr)
        {
            using (var conn = new SqlConnection(connstr))
            {
                conn.Open();
                
                var cmd = new SqlCommand("select @@Version", conn);

                using (var reader = cmd.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        Console.WriteLine(reader.GetString(0));
                    }
                }
                
            }
        }
```

**Comment by kkurni** [comment]
I will close this issue as it won't be issue once we have namepipe provider in manage SNI
