### ISSUE TITLE
SslStream.AuthenticateAsClientAsync method 4-parameter overload missing on rc2

### ISSUE THREAD

**Issue by fsoikin** [dotnet/corefx#5064]
This started happening since rc2-16294, and still happens on yesterday's rc2-16317.

Interestingly, only the [4-parameter overload is missing](https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/ref/System.Net.Security.cs#L102), while [the 1-parameter overload](https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/ref/System.Net.Security.cs#L101) appears to be fine.

Details:
```
C:\i> ls


    Directory: C:\i


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       12/18/2015  10:28 AM            262 Program.cs
-a----       12/18/2015  10:27 AM            258 project.json
-a----       12/18/2015  10:27 AM         105977 project.lock.json


C:\i> cat .\project.json
{
        "compilationOptions": {
                "emitEntryPoint": true
        },

        "dependencies": {
                "System.IO": "4.0.11-beta-23409",
                "System.Runtime": "4.0.20-beta-23409",
                "System.Net.Security":  "4.0.0-beta-23409",
        },

        "frameworks": {
                "dnxcore50": { }
        }
}

C:\i> cat .\Program.cs
public static class Program {
   public static void Main(string[] args) {
      var s = new System.Net.Security.SslStream( new System.IO.MemoryStream() );
      s.AuthenticateAsClientAsync( null, null, System.Security.Authentication.SslProtocols.Ssl2, false );
   }
}

C:\i> dnvm use 1.0.0-rc2-16317 -r coreclr
Adding C:\Users\Fyodor\.dnx\runtimes\dnx-coreclr-win-x64.1.0.0-rc2-16317\bin to process PATH

C:\i> dnx run
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task System.Net.Security.SslStream.AuthenticateAsClientAsync(System.String, System.Security.Cryptography.X509Certificates.X509CertificateCollection, System.Security.Authentication.SslProtocols, Boolean)'.
   at Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

C:\i> dnvm use 1.0.0-rc2-16258 -r coreclr
Adding C:\Users\Fyodor\.dnx\runtimes\dnx-coreclr-win-x64.1.0.0-rc2-16258\bin to process PATH

C:\i> dnx run
System.ArgumentNullException: Value cannot be null.
Parameter name: targetHost
   at System.Net.Security.SslState.ValidateCreateContext(Boolean isServer, String targetHost, SslProtocols enabledSslProtocols, X509Certificate serverCertificate, X509CertificateCollection clientCertificates, Boolean remoteCertRequired, Boolean checkCertRevocationStatus, Boolean checkCertName)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c__DisplayClass26_0.<AuthenticateAsClientAsync>b__0(AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at Program.Main(String[] args) in C:\i\Program.cs:line 4
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

C:\i>
```

**Comment by davidsh** [comment]
My guess is that this is a DNX packaging/cache issue and not a CoreFx issue.  It is possible that the DNX build and/or your package cache has out of sync packages.

Looking at the actual source code in CoreFx for both the ref folder and the src folder shows that the 4-parameter overload for SslStream.AuthenticateAsClientAsync() is present in the code.

Here is the code from:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/src/System/Net/SecureProtocols/SslStream.cs

```c#
        public virtual Task AuthenticateAsClientAsync(string targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, bool checkCertificateRevocation)
        {
            SecurityProtocol.ThrowOnNotAllowed(enabledSslProtocols);

            return Task.Factory.FromAsync((callback, state) => BeginAuthenticateAsClient(targetHost, clientCertificates, enabledSslProtocols, checkCertificateRevocation, callback, state), EndAuthenticateAsClient, null);
        }
```

**Comment by davidsh** [comment]
And looking at the CoreFx Dev feed on MYGET:
https://www.myget.org/gallery/dotnet-core

I see that the System.Net.Security package
https://www.myget.org/feed/dotnet-core/package/nuget/System.Net.Security

and the runtime (Windows, for example) package:
https://www.myget.org/feed/dotnet-core/package/nuget/runtime.win7.System.Net.Security

has the correct refs and implementation methods for `SslStream`.

**Comment by davidsh** [comment]
cc; @davidfowl

**Comment by fsoikin** [comment]
I've only just installed all these runtimes, and immediately ran the test.
How would I verify if anything is "out of sync"?

**Comment by fsoikin** [comment]
The hypothesis that my local packages are somehow corrupted is ruled out by the fact that RC1 works, as does RC2 up to, and excluding, 16294. Therefore, this must be runtime-specific.

The hypothesis that my runtimes got somehow corrupted (is it even possible? I was under impression they never change once installed) is ruled out by the fact they most of them are freshly instated - I literally did `dnvm install ...; dnx run`.

What else could be out of sync?

**Comment by fsoikin** [comment]
Also, here's an interesting bit of trivia: in the package `System.Net.Security` of version 23516 (the latest one on [nuget](https://www.nuget.org/packages/System.Net.Security/4.0.0-beta-23516)) has an empty DLL under `net46`. The DLL is there, but doesn't contain any types. That's why my test project uses previous version 23409.

Could that have something to do with this?

**Comment by davidsh** [comment]
>Also, here's an interesting bit of trivia: in the package System.Net.Security of version 23516 (the latest one on nuget) has an empty DLL under net46. The DLL is there, but doesn't contain any types. That's why my test project uses previous version 23409.
Could that have something to do with this?

No.  The System.Net.Security package doesn't have the actual implementation in it.  That package is a meta-package with a runtime.json in it. The real implementations are in the runtime.* packages where runtime maps to Windows, Linux, etc.

**Comment by fsoikin** [comment]
I know it's a meta package, but there supposed to be ref assemblies in it nevertheless. They contain types with methods, but without bodies.

For example, v23409 does have these assemblies, and that's why the program even compiles. If I put 23516 in project.json, it will stop compiling, complaining that `SslStream` does not exist in namespace `System.Net.Security`.

**Comment by davidsh** [comment]
Since this is a packaging problem with the DNX runtimes, I would suggest you open an issue with the DNX team at:
https://github.com/aspnet/dnx

They will be able to help further investigate this issue with their DNX runtime builds.

**Comment by fsoikin** [comment]
Will do, thank you.
