### ISSUE TITLE
Updating to the recent version of the runtime packages results in some test failures in release only builds

### ISSUE THREAD

**Issue by pallavit** [dotnet/corefx#5067]
#5057 has a little more information. Since, the packages always use release bits, and the tests failures happen only when the tests are built as release, this most likely is a JIT bug which was one major change that happened in the CoreCLR between the update window.

**Comment by weshaggard** [comment]
@CarolEidt Can you suggest someone on the JIT team to have a look at this?

See https://github.com/pallavit/corefx/commit/7a60d36ece69d7aedc9ea4a9a54c78d77b591609 for the tests that repro the issue on Linux Release.

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib. We're pretty short-handed between now and the new year, but hopefully we can find someone to look at these next week.

**Comment by pallavit** [comment]
We are seeing some failures in OpenSUSE Debug builds as well which seems likely to be JIT issues.

**Comment by weshaggard** [comment]
See https://github.com/dotnet/corefx/issues/5082 for the OpenSuse issues.

**Comment by LLITCHEV** [comment]
The System.Linq.Expression failures on Linux were fixed and the tests enabled last week. The Windows System.Collections.Immutable.BinarySearch* failures are the same as the one described in dotnet/coreclr issue #2349 (https://github.com/dotnet/coreclr/issues/2349). The only left failing tests are duplicates of dotnet/coreclr issue # 2349.

**Comment by LLITCHEV** [comment]
@joshfree I am closing this because the remaining failures are dups of dotnet/coreclr #2349. Please reopen if you disagree that it needs to be closed.

**Comment by weshaggard** [comment]
I would like to keep this issue opened until we reactive the tests (i.e. remove the activeissue that is pointing at this issue).

**Comment by LLITCHEV** [comment]
See coreclr issue 2349 - https://github.com/dotnet/coreclr/issues/2349
Assigned to @sivarv.

**Comment by sivarv** [comment]
See coreclr issue 2349 is fixed.  I have verified that failing CoreFX immutable tests pass.
Please verify and re-enable CoreFX tests.  Assigning back to @pallavit

**Comment by pallavit** [comment]
> I have verified that failing CoreFX immutable tests pass.

@sivarv In that case you just needed to remove ActiveIssue from the disabled tests and the let the CI verify the PR :). When was this change checked-in? Would we need to update the packages to consume CoreCLR changes in corefx repo or has that happened?

@ellismg Looks like all the known issues here have been fixed. Do you have any objections with reenabling OpenSUSE builds?

**Comment by ellismg** [comment]
@pallavit: No objections.

**Comment by sivarv** [comment]
I have merged the fix (or pull request) a while ago.

**Comment by pallavit** [comment]
Spoke to sivarv offline, these changes were checked-in today so we will have to wait for today's build to consume them in corefx.

**Comment by pallavit** [comment]
Tests have been enabled as part of #5735
