### ISSUE TITLE
Specification tests for collection interfaces

### ISSUE THREAD

**Issue by eatdrinksleepcode** [dotnet/corefx#507]
In the last [API review](https://github.com/dotnet/apireviews/tree/master/2015-01-14-misc#follow-ups-for-api-review-board), @KrzysztofCwalina mentioned that it would be nice to have a set of tests that can serve as specifications for the expected behavior of the built-in collection interfaces. These tests could be used by people creating types which implement these interfaces to ensure that their implementations match the specification.

I love this idea, and would love to help create the suite. Is this something that the community can engage on?

**Comment by KrzysztofCwalina** [comment]
@eatdrinksleepcode, I marked this as up for grabs. Feel free to take it, if you like to get involved.

**Comment by hughbe** [comment]
@ianhays has this been fixed by your work in the System.Collections.Tests common test helpers? If not, what remains?

**Comment by ianhays** [comment]
Thanks @hughbe, I didn't see this issue but it sounds like I resolved it already with  https://github.com/dotnet/corefx/pull/5764.

@eatdrinksleepcode check out the test files at https://github.com/dotnet/corefx/tree/master/src/Common/tests/System/Collections. Absolutely feel free to add tests if you see gaps in the generic collections tests there :) My goal in adding them was to create a set of interface-level tests that could be used by any class that implemented them whether they be built-in classes or user-made classes.

**Comment by hughbe** [comment]
Ah good to know. Should this be closed then?

**Comment by ianhays** [comment]
Yeah probably. I'll go ahead and close it and @eatdrinksleepcode can comment/re-open if he had something else in mind.
