### ISSUE TITLE
Code cleanup related to System.Diagnostics.Tracing porting

### ISSUE THREAD

**Issue by dsgouda** [dotnet/corefx#5072]
@vancem  @davmason  please clean up, format and address reviews for code  ported as a part of https://github.com/dotnet/corefx/pull/5071

**Comment by weshaggard** [comment]
@davmason please run the codeformatter and update the code to conform to the guidelines of the corefx repo. See:

https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md
https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/project-guidelines.md

Also for information on packaging see:
https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/package-projects.md

**Comment by brianrob** [comment]
Looking at #5071, there are no code review comments present to address.  We're also trying to make sure that we keep EventSource code, which is present in multiple repos, in sync.  Thus, we try to avoid larger code formatting changes.  Based on these, and the fact that we may not even put EventSource in the corefx repo (it must live in both coreclr and corert), I'm closing this issue.

**Comment by weshaggard** [comment]
Looks this was just a preemptive one filed when on one left comments on the PR, and can be closed.
