### ISSUE TITLE
Add instance factory overloads to Enumerable.Repeat

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/corefx#5078]
Hi,

There are `Enumerable.Range` and `Enumerable.Repeat` which are awesome, however, when using `Repeat` with a reference type, it's the reference to the same object being repeated, hence, changing a property of the repeated object will reflect in that property being changed for all indexes.

The solution would be to create another overload of `Enumerable.Repeat` that is either parameterless or ones that accepts `Func<T>` or `Func<int, T>` that uses as a factory of the generated element, where the latter overload (with the `int` argument provides the index of the current element to be generated.

```
//will initialize an array of 40 instantiated StringBuilder objects.
var builders = Enumerable.Repeat<StringBuilder>(40).ToArray(); 

//will initialize an array of 40 instantiated StringBuilder objects using a custom constructor
var builders = Enumerable.Repeat(i => new StringBuilder($"Line {i} says:"));
```

Another overload I'd want to see is for `Enumberable.Range`, is omitting the `start` parameter so that it's set to `0`, and only the `count` is provided. Merely a syntactic sugar.

**Comment by svick** [comment]
So, you're basically asking for a shortcut of `Enumerable.Range(0, 40).Select(_ => new StringBuilder())`?

**Comment by weitzhandler** [comment]
Precisely.

**Comment by JonHanna** [comment]
The construct @svick gives in his comment seems a lot clearer than overloading `Repeat` for something that doesn't repeat the value.

**Comment by JonHanna** [comment]
On second thoughts, it's not just clearer, it's a lot clearer. It's not common to want to actually repeat actions, but it's not impossible either. I've done so in test code, though I don't think I've done so in real code.

**Comment by VSadov** [comment]
This seems to be a subset of the proposal in #13909
