### ISSUE TITLE
OpenSUSE 13.2 test runs flaky

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#5082]
I would appear that recent CLR changes have caused the openSUSE builds to fail often.  [Debug](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/opensuse13.2_debug/120/) fails more often than [Release](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/opensuse13.2_release/122/) but both see failures.

The failures are always the same.  A smattering of failures in globalization tests and a few other assemblies (which may be related to globalization).

The globalization tests that fail aren't "interesting" (e.g specific cultures or special flags).

While we investigate, I am going to remove the openSUSE builds from PR testing in CI.

**Comment by weshaggard** [comment]
cc @dotnet/jit-contrib
