### ISSUE TITLE
System.Linq.Expression rd.xml file leads to spurious warnings

### ISSUE THREAD

**Issue by MattWhilden** [dotnet/corefx#5088]
Start a new UWP and add this to it:
    System.Linq.Expressions.Expression<Func<int>> e = () => 1234;

When building with .NET Native you'll now get two build warnings because the rd.xml file in this assembly has some wonky bits. This keeps folks from being warning clean and is actually pretty distracting for folks as it provides a lovely red herring for their other investigations. :-)

Here's the warnings I get with VS Update 1:
Method 'CreateLambda' within 'System.Linq.Expressions.Expression' could not be found.
Method 'ParameterIsAssignable' within 'System.Linq.Expressions.Expression' could not be found.

@VSadov ?

**Comment by VSadov** [comment]
These methods are not public and do not seem to be used dynamically. There might be some historical reason for them to be listed in rd.xml, but I do not see why these entries would be needed now.

**Comment by mvermef** [comment]
still seeing this on NativeToolChain release builds, RC2

**Comment by MattWhilden** [comment]
That probably has to do with how this flows into the metapackage for UWP apps. I'll make sure nothing crazy is happening. Either way, it's safe to ignore these warnings. 

Thanks for letting us know.

**Comment by martinsuchan** [comment]
Any idea when this fix will be available in VS2015? As of today when doing compiling UWP Anniversary Update project to native code, in Release mode, these warnings are still there, even in VS2015 Update 3.

**Comment by mvermef** [comment]
Yeah saw them too but doesn't seem to be an issue, not sure on WACK yet.

**Comment by martinsuchan** [comment]
It's only issue if you want to have build configuration that returns no errors or warnings when executed, or if you have OCD.

**Comment by MattWhilden** [comment]
I'm running in VS 2015 Update 3 with 5.2.2 of Microsoft.NETCore.UniversalWindowsPlatform. Can you see which versions you're running on? I'm pretty sure this is fixed at this point. If you discover otherwise, we'd love to know.

**Comment by yizhang82** [comment]
Unfortunately I don't think this is fixed with 5.2.2. I'm still reproing this issue with Visual Studio 2015 Update 3 and metapackage 5.2.2 and I'm still seeing the same issue. For whatever reason we just didn't pick up the newer bits.

**Comment by mvermef** [comment]
Its only seen when dealing with "release" toolchain builds.

**Comment by martinsuchan** [comment]
@MattWhilden Just tested in VS2015 U3 + UWP Tools v1.4.1
Create empty UWP project, add this to project.json and rebuild on Release/ARM - you get those two warnings during build:

    "dependencies": {
      "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2",
      "MvvmLightLibs": "5.3.0"
    },

    Resources.System.Linq.Expressions.rd.xml(35): warning : ILTransform_0027: Method 'CreateLambda' within 'System.Linq.Expressions.Expression' could not be found.
    Resources.System.Linq.Expressions.rd.xml(91): warning : ILTransform_0027: Method ParameterIsAssignable' within 'System.Linq.Expressions.Expression' could not be found.

No idea, why adding MvvmLightLibs causes these warnings to appear. If I have only Microsoft.NETCore.UniversalWindowsPlatform dependency, then there is no such issue.

**Comment by MattWhilden** [comment]
A-ha! I have a working theory on this. 

We only trigger this warning if your application has a reference into System.Linq.Expressions (otherwise we ignore that rd.xml file). Previously, the blank template had a reference to ApplicationInsights for UWP and I now presume that was causing the UWP template to need System.Linq.Expressions. One recent change is that HockeyApp is now the preferred telemetry pipeline for UWP so AppInsights was removed from the template.

Presumably, this is why I had erroneously thought it was fixed and why it "reappears" only when various other libraries are pulled in.

Hope that helps.

**Comment by martinsuchan** [comment]
@MattWhilden The question remains, can the build process be fixed so there are no build warnings if there is any reference to System.Linq.Expressions?

**Comment by alex4998** [comment]
Having the same issue looking for the answer. I don't think it is a good practice to just ignore warnings.

**Comment by MattWhilden** [comment]
The infrastructure we have for warning suppression doesn't seem to allow suppression of this one. :-(

One workaround would be to get an updated package of System.Linq.Expressions with the fix in it. If someone from framework could comment on the feasibility of that it would be much appreciated.

**Comment by soroshsabz** [comment]
ITNOA

I have the same problem too.

I have visual studio 2015 U3 and use Microsoft.NETCore.UniversalWindowsPlatform

**Comment by mfe-** [comment]
I'm getting on Configuration Release with enabled .NetNativeToolChain

> 6>  tetris -> C:\Users\mfe\Documents\Visual Studio 2015\Projects\tetris\UWP\tetris\bin\x86\Release\tetris.exe
6>  Processing application code
6>C:\Users\mfe\Documents\Visual Studio 2015\Projects\tetris\UWP\tetris\Resources.System.Linq.Expressions.rd.xml(35): warning : ILTransform : warning ILT0027: Method 'CreateLambda' within 'System.Linq.Expressions.Expression' could not be found.
6>C:\Users\mfe\Documents\Visual Studio 2015\Projects\tetris\UWP\tetris\Resources.System.Linq.Expressions.rd.xml(91): warning : ILTransform : warning ILT0027: Method 'ParameterIsAssignable' within 'System.Linq.Expressions.Expression' could not be found.
6>  Computing application closure and generating interop code
6>    Loading 122 modules...
6>    Generating code...
6>    Interop code generated.
6>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Microsoft.NetNative.targets(640,5): error : MCG0004:InternalAssert Assert Failed: field not found during [UNKNOWN]
========== Rebuild All: 5 succeeded, 1 failed, 0 skipped ==========

There is also a similar post on [SO](http://stackoverflow.com/questions/41366567/error-mcg0004internalassert-assert-failed-when-building-uwp-app-in-release-mode?noredirect=1#comment70046703_41366567)

I'm getting this build error on Windows 10 and on Windows Server 2016.

**Comment by yizhang82** [comment]
@mfe- Are you happening to use the latest 5.3.0-beta2 Microsoft.NetCore.UniversalWindowsPlatform metapackage under VS 2015? If that's the case, you might want to downgrade back to 5.2.2/5.1.0. 5.3.0-beta2 is not compatible with VS 2015.

**Comment by mfe-** [comment]
Thanks @yizhang82 
I changed the project.json dependency from 
"Microsoft.NETCore.UniversalWindowsPlatform": "5.3.0-beta2" to "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2"

This fixed the error. Thanks.

**Comment by MattWhilden** [comment]
This is resolved in version 5.3.0 of Microsoft.NETCore.UniversalWindowsPlaform. You'll need VS 2017 to take advantage of this. More details here: https://blogs.msdn.microsoft.com/dotnet/2017/01/30/announcing-net-core-net-native-and-nuget-updates-in-vs-2017-rc/

**Comment by MarcioAB** [comment]
Indeed. Issue solved with 5.3.3 NetCore.UWP package. Tks.
