### ISSUE TITLE
Equivalent to System.Environment.CurrentDirectory

### ISSUE THREAD

**Issue by travisshepherd-kofax** [dotnet/corefx#5089]
Similar to https://github.com/dotnet/corefx/issues/2413, Environment.CurrentDirectory doesn't appear to be supported.  What is the alternative?

**Comment by weshaggard** [comment]
Directory.GetCurrentDirectory() https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/ref/System.IO.FileSystem.cs#L37
