### ISSUE TITLE
Constant naming guidelines

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#509]
While reviewing some code I realized we have not explicitly listed the guidelines for naming constants in our code so I thought I would get some opinions before updating the [contribution guidelines] (https://github.com/dotnet/corefx/wiki/Contributing). Constants are fields and the framework design guidelines for public [fields](https://msdn.microsoft.com/en-us/library/ms229012(v=vs.110).aspx) states to use pascal casing and I don't see any real reason to do anything different for internal/private constants.

    internal const int MyConstantValue = 42;

Another common case is to use all uppercase chars with underscores separating word.

    internal const uint COPY_FILE_FAIL_IF_EXISTS = 0x00000001;

I think the general case of using all uppercase is from the older C++ days which I don't recommend for general use in more modern C#. However when doing interop with C++ I do think it is valuable to keep the constant names and values exactly matching their C++ counterpart to make it clear that the values are intentionally supposed to match.

So I think the guideline should read something like:

>We do use PascalCasing to name all our constant local variables and fields. The only exception is for interop code where the constant value should exactly match the name and value of the code you are calling via interop.

**Comment by ellismg** [comment]
This sounds good to me.

**Comment by ErikSchierboom** [comment]
Sound very reasonable!

**Comment by stephentoub** [comment]
Agreed. What about constant locals? We similarly have a mix of camel casing, Pascal casing, and all uppercase with underscores. While they're not the same as locals, I'd propose we use the same naming convention: camel casing.

**Comment by weshaggard** [comment]
I updated the guidance to call out local variables as well. 
>We do use PascalCasing to name all our constant local variables and fields.

**Comment by ellismg** [comment]
Even in the case where the local is a Win32 constant?  Is the thinking we never get into this state by never having a local Win32 constant?

**Comment by weshaggard** [comment]
I guess I should have copied the entire guidance line in my last comment :) We will still have the exception for interop constants which applies to all constants both local and fields. I updated the guidance in the original issue comment.

**Comment by ellismg** [comment]
Thanks Wes!

**Comment by weshaggard** [comment]
Added to [coding guidelines](https://github.com/dotnet/corefx/wiki/Contributing).
