### ISSUE TITLE
ReadOnlyDictionary should be located at System.Runtime

### ISSUE THREAD

**Issue by yfakariya** [dotnet/corefx#5104]
I found and confused about location of collection interfaces and their implementations in class library nuget packages.
* Collection interfaces including `IReadOnlyDictionary<TKey, TValue>` are defined in `System.Runtime` assembly, it is perfect.
* (Generic) collection implementations are defined in `System.Collections` assembly, it also OK.
* `INotifyCollectionChanged` and its implementation (`ObservableCollection<T>`) is defined in `System.ObjectModel`, it is no problem.
* `Collection<T>` and `ReadOnlyCollection<T>` are defined in `System.Runtime`, and `ReadOnlyDictionary<TKey, TValue>` is defined in `System.ObjectModel`.

It causes unnecessary dependency from apps to `System.ObjectModel` when apps just want to use read only dictionary. At least, `ReadOnlyDictionary<TKey, TValue>` should be located together with `ReadOnlyCollection<T>`.

**Comment by aevitas** [comment]
I'm not sure I completely follow you here - `ReadOnlyCollection<T>` and `Collection<T>` provide the base types for readonly collections and generic collections respectively. 

Assuming you're not instantiating the base collection types, but instead use `IReadOnlyList<T>` which draws from a backing `List<T>` or similar, you wouldn't need to reference additional assemblies, right? Alternatively, there's `System.Collections.Immutable` as well if you're looking for an isolated immutable collections library.

Correct me if I'm wrong, but I'm not sure this is actually an issue with the code base.

**Comment by yfakariya** [comment]
I want to say there is a packaging issue, especially asymmetry between read-only list and dictionary (I believe `ReadOnlyCollection<T>` and `ReadOnlyDictionary<TKey, TValue>` are even from point of their objectives). As you say, it is OK to expose read only dictionary in API with interface, but we eventually use implementation (that is `ReadOnlyDictionary` class) for it.

**Comment by aevitas** [comment]
> As you say, it is OK to expose read only dictionary in API with interface, but we eventually use implementation (that is ReadOnlyDictionary class) for it.

Not necessarily, `Dictionary<TKey, TValue>` implements `IReadOnlyDictionary<TKey, TValue>` as well (same with `List<T>` and `IReadOnlyList<T>`), therefore, it is perfectly fine to expose a regular dictionary as an immutable dictionary in public API like so:

		private readonly Dictionary<string, int> _dictionary = new Dictionary<string, int>();
		public IReadOnlyDictionary<string, int> Dictionary => _dictionary; 

I'm not sure how common it is to use `ReadOnlyCollection<TKey, TValue>` and `Collection<TKey, TValue>` as actual collections instead of their System.Collections.Generic counterparts. I've personally never used the former in production software - they don't appear to me as types that intended for end-use, but that's something one of the repository contributors should probably comment on.

**Comment by yfakariya** [comment]
>  Not necessarily, Dictionary<TKey, TValue> implements IReadOnlyDictionary<TKey, TValue>

Oh, I forgot it. I still wonder why `ReadOnlyCollection<T>` and `ReadOnlyDictionary<TKey, TValue>` are packaged sparatedly, but I understand I was just misunderstand. Thank you for following @aevitas!
