### ISSUE TITLE
Cannot run tests from console if sln previusly was built with VS 2015 CE (log of error in task)

### ISSUE THREAD

**Issue by comdiv** [dotnet/corefx#5105]
Clone and build coreclr and corefx according to guide, Windows 10, Visual Studio 15 CE.

It succeed.

When I start investigate code in VS

Open System.Collections.sln, build from VS (many many errors in intellisense and so on but Output writes that build succed)

Then go to console:

```
cd .\src\System.Collections\tests
msbuild /t:Test
```

It fails with:

```
"d:\net\corefx\src\System.Collections\tests\System.Collections.Tests.csproj" (target object Build ) (1) ->
"d:\net\corefx\src\System.Collections\src\System.Collections.csproj" (target object Build;DebugSymbolsProjectOutputGroup ) (2) ->
(Целевой объект OpenSourceSign) ->
  d:\net\corefx\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00137\li
b\sign.targets(39,5): error : d:\net\corefx\bin/obj/Windows_NT.AnyCPU.Debug\Sys
tem.Collections\System.Collections.dll: PE file is already strong-name signed.
[d:\net\corefx\src\System.Collections\src\System.Collections.csproj]
```

But if i build sln from cmd:

```
cd .\src\System.Collections
msbuild /t:Clean;Build
cd .\tests
msbuild /t:Test
```

All is well.

What is bad with visual studio and how to match it's behavior with what MSBuild does itself?

**Comment by mellinoe** [comment]
This problem: `PE file is already strong-name signed.` is actually not specific to VS 2015 CE or anything like that. It's just an issue that occasionally occurs if builds are canceled (for some reason) in an intermediate state. It should not persist at all if you just clean and rebuild the project. If you feel that there is actually another distinct issue here, please re-open this or just file a new one.
