### ISSUE TITLE
Add overload for Vector.CopyTo() that supports pointers

### ISSUE THREAD

**Issue by alexandrnikitin** [dotnet/corefx#5106]
At the moment we have only one signature that supports arrays only:
```csharp
public unsafe void CopyTo(T[] destination)
```
But sometimes we have only pointers in code when converting them back to arrays isn't an option. Please add the ability to pass pointers directly to `CopyTo()` method. Something like that would work:
```csharp
public unsafe void CopyTo(void* destination)
```
The issue is related to #3741

**Comment by mellinoe** [comment]
@CarolEidt Do you expect that this functionality would be easy to implement? Unlike https://github.com/dotnet/corefx/issues/3741, we don't already have a (private) implementation for this. I think it is definitely worth adding, though.

**Comment by CarolEidt** [comment]
This would be very straightforward to add, and would basically just be adding the recognition of the signature, and then some minor changes in the importer functions.

**Comment by benaadams** [comment]
:+1: Would like this very much as if you have a pointer you can't easily turn it into an array

**Comment by programmatom** [comment]
How does this reconcile with https://github.com/dotnet/corefx/issues/5474? It looks like that subsumes this, unless I've misunderstood, and https://github.com/dotnet/corefx/issues/5474 is accepted for 1.0.0rtm, whereas this one is just "Future". Is https://github.com/dotnet/corefx/issues/5474 intended to be the preferred mechanism?

**Comment by mellinoe** [comment]
Yes, the current plan is that #5474 will be the generic mechanism to do this, not only with Vector<T> but with any other generic structure as well.

**Comment by alexandrnikitin** [comment]
Ok, I'm happy to close then.
