### ISSUE TITLE
how to use xunit to projects

### ISSUE THREAD

**Issue by ShengboZhang** [dotnet/corefx#511]
sorry to distub everybody,but use xunit to corefx in vs2013,it doesn't work.
when compile the project,it's not generate the bin file,so the Test Explorer can't find the unit test method.
so,except to you help,thanks.

**Comment by mikedn** [comment]
This doesn't currently work, you have to run the tests from the command prompt build. See the [developer guide](https://github.com/dotnet/corefx/wiki/Developer-Guide#running-tests).

**Comment by ShengboZhang** [comment]
yes,I know,thankyou.
this feature with vs test,we can do it by ourself,right?

**Comment by mikedn** [comment]
I'm not sure what you mean by that.

Perhaps it would be useful to point out that there appears to be ongoing work to make tests run in VS: #508

**Comment by krwq** [comment]
Looks like it is already done but only for VS 2015. Not sure if that is satisfying.

**Comment by nguerrera** [comment]
I've added information to https://github.com/dotnet/corefx/wiki/developer-guide#running-tests.

It is possible to debug tests in VS or run the tests for a single project on the command line.
