### ISSUE TITLE
Christmas Analysis of .NET Core Libraries (CoreFX)

### ISSUE THREAD

**Issue by SvyatoslavRazmyslov** [dotnet/corefx#5118]
To demonstrate the capabilities of our analyzer, we regularly perform analysis of open source projects. We had recently checked the CoreFX project.

Here is the link to the article about it: http://www.viva64.com/en/b/0365/
Official page of the analyzer: http://www.viva64.com/en/pvs-studio/

If you have any questions, or if you are interested in the evaluation of our static analyzer or in any other source code quality control services that our company provides, please contact us at support@viva64.com.

**Comment by JonHanna** [comment]
Enumerable.cs 517 was my fault, a remnant on simplifying from code that handled more cases.

It's harmless and of nil effect (it compiles to the same IL as if the more reasonable `if` was used there) but it's worth fixing all the same.
