### ISSUE TITLE
Keeping in sync Localization Resources name when using Event Sources.

### ISSUE THREAD

**Issue by josguil** [dotnet/corefx#5126]
Event Sources can be localized by specifying the name of the resources file. But that name needs to be hard coded in the attribute of the event source. So, if at some point in time, the name of the resources changes, the event source will not be in sync anymore and a message like:

"Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "NameOfMyResources.resources" was correctly embedded or linked into assembly..."

will be the only log that appears in our event source recorder. 

If in the future, a better way to specify LocalizationResources that does not depend on a constant variable is available, changes to the EventSources code in System.Net should be made.

**Comment by josguil** [comment]
Related PR using EventSources and Localization: https://github.com/dotnet/corefx/pull/5101

**Comment by danmosemsft** [comment]
@davmason does not seem needed for 2.0

**Comment by karelz** [comment]
This will likely need new API proposal.
Next step: Think it through and suggest solution. If it needs new API, please we need formal API proposal.

**Comment by brianrob** [comment]
If I understand correctly, this becomes an issue if by chance the resource file name changes.  We could do something to detect this and have a different error message, but that would still be at runtime.  What would be needed is something at compile time.  I suspect that the complexity required is not going to merit such a change.  Closing.
