### ISSUE TITLE
Some DateTime Serialization tests failed in Moscow time zone

### ISSUE THREAD

**Issue by speshuric** [dotnet/corefx#5127]
### Description
Some DateTime Serialization tests failed in Moscow time zone.
Test output [placed](https://gist.github.com/speshuric/49c7e1b5072095cebe7b) in a gist. Here is reduced output:
```
   XmlSerializerTests.Xml_DateTimeAsRoot [FAIL]

      Test failed for input: 02.01.2013 3:04:05
      Expected: <?xml version="1.0"?>
      <dateTime>2013-01-02T03:04:05.006+03:00</dateTime>
      Actual: <?xml version="1.0" encoding="utf-8"?>
      <dateTime>2013-01-02T03:04:05.006+04:00</dateTime>
===================================================================
   DataContractJsonSerializerTests.DCJS_DateTimeAsRoot [FAIL]
[expected]:ate(1357084800000+0300)\/"
[actual  ]:ate(1357081200000+0400)\/"
[Expected (with length=30)]:
"\/Date(1357084800000+0300)\/"
[Actual (with length=30)]:
"\/Date(1357081200000+0400)\/"
===================================================================
   DataContractSerializerTests.DCS_TypeWithDatetimeOffsetTypeProperty [FAIL]

      Expected: <TypeWithDateTimeOffsetTypeProperty xmlns="http://schemas.datacontract.org/2004/07/SerializationTypes" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><ModifiedTime xmlns:a="http://schemas.datacontract.org/2004/07/System"><a:DateTime>2013-01-02T03:04:05.006Z</a:DateTime><a:OffsetMinutes>180</a:OffsetMinutes></ModifiedTime></TypeWithDateTimeOffsetTypeProperty>
      Actual: <TypeWithDateTimeOffsetTypeProperty xmlns="http://schemas.datacontract.org/2004/07/SerializationTypes" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><ModifiedTime xmlns:a="http://schemas.datacontract.org/2004/07/System"><a:DateTime>2013-01-02T02:04:05.006Z</a:DateTime><a:OffsetMinutes>240</a:OffsetMinutes></ModifiedTime></TypeWithDateTimeOffsetTypeProperty>

   DataContractSerializerTests.DCS_DateTimeOffsetAsRoot [FAIL]

      Expected: <DateTimeOffset xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/System"><DateTime>2013-01-02T03:04:05.006Z</DateTime><OffsetMinutes>180</OffsetMinutes></DateTimeOffset>
      Actual: <DateTimeOffset xmlns="http://schemas.datacontract.org/2004/07/System" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><DateTime>2013-01-02T02:04:05.006Z</DateTime><OffsetMinutes>240</OffsetMinutes></DateTimeOffset>
```
### Research
All these tests failed by the similar reasons. In these tests used `TimeZoneInfo.Local.BaseUtcOffset.TotalMinutes` which is not right. Offset *can* change. For example:
```cs
TimeZoneInfo timeZone = TimeZoneInfo.FindSystemTimeZoneById("Russian Standard Time");
DateTime d1Utc = new DateTime(2015, 1, 2, 3, 4, 5, 6, DateTimeKind.Utc);
Console.WriteLine("2015: Offset: {0}", timeZone.GetUtcOffset(d1Utc));
DateTime d2Utc = new DateTime(2013, 1, 2, 3, 4, 5, 6, DateTimeKind.Utc);
Console.WriteLine("2013: Offset: {0}", timeZone.GetUtcOffset(d2Utc));
```
Output is:
```
2015: Offset: 03:00:00
2013: Offset: 04:00:00
```
This issue was fixed in #2496 **Fix serialization test failure in Minsk timezone**, and #2541 **Serialization time zone fixes** but broken again in 3f91ae10 (it was rather big commit and it's no wonder that something was broken).

### Questions to discuss

As @stephentoub mentioned in #2496, it would be better 
>to make this test not depend on the local timezoneinfo and instead have the test run for a variety of specific time zones, e.g. by making it a `[Theory]` and passing in via InlineData or MemberData a few different time zones to test

I think this is right idea and I propose to discuss how to do it better:
1. Make 2 PR (the first - small roll back fix, the second - new tests with `[Theory]` attribute)
2. Make only full PR (but it will take some time for me)

Small rollback PR I can do ASAP

And how can we prevent accidental changes like https://github.com/dotnet/corefx/commit/3f91ae10

**Comment by speshuric** [comment]
IMO that it is better to fix tests now and do extended tests with `[Theory]` in a few days. PR for rollback fixes is here

**Comment by khdang** [comment]
I was thinking of refactoring the related tests to use [Theory] attribute and realized that it may not be possible to do that and still verifying with a string payload. 
DateTime doesn't have an information indicating timezone accept for the Kind property which may take these 3 values: Utc, Unspecified, or Local. When Kind is Unspecified or Local, the serializers will suffix the serialized output with the offset hours. 
I can't think of a way to serialize DateTime objects in a specific timezone except for the current local time zone, so it seems like we still have take into account the offset, which is what we're doing at the moment.

**Comment by khdang** [comment]
I'm closing and will revisit this when there is a way to serialize DateTime instance in a specific time zone.
