### ISSUE TITLE
ArrayIndex Expression fails for Arrays with non zero lower bounds

### ISSUE THREAD

**Issue by afscrome** [dotnet/corefx#5134]
If you have an array with a lower bound other than 0, calls to `Expression.ArrayIndex` for that array fail at execution time with the exception `System.Security.VerificationException: Operation could destabilize the runtime.`

You can reproduce this with the following code.  If you set `lowerBound` to 0, the execution correctly returns `6.5`.  If `lowerBound` is set to anything else, an exception is thrown when evaluating the expression.

```csharp
int lowerBound = 10;

var array = Array.CreateInstance(typeof(float), new int[] { 3 }, new int[] { lowerBound });
array.SetValue(1.2f, lowerBound + 0);
array.SetValue(6.5f, lowerBound + 1);
array.SetValue(9.21f, lowerBound + 2);

var func = Expression.Lambda<Func<float>>(
        Expression.ArrayIndex(
            Expression.Constant(array),
            Expression.Constant(lowerBound + 1)
        )
).Compile();

var result = func(); //Exception thrown here

Assert.That(result, Is.EqualTo(6.5f));
```

**Comment by JonHanna** [comment]
What version of dotnet core are you running this with? I tried the following (to hit both the compiler and the interpreter) with a fresh pull from the repository, and they both worked:

```C#
[Fact]
public static void ArraySingleRankNotSZArrayAccessCompiled()
{
    int lowerBound = 10;

    var array = System.Array.CreateInstance(typeof(float), new int[] { 3 }, new int[] { lowerBound });
    array.SetValue(1.2f, lowerBound + 0);
    array.SetValue(6.5f, lowerBound + 1);
    array.SetValue(9.21f, lowerBound + 2);

    var func = Expression.Lambda<Func<float>>(
            Expression.ArrayIndex(
                Expression.Constant(array),
                Expression.Constant(lowerBound + 1)
            )
    ).Compile(true);

    var result = func();

    Assert.Equal(6.5f, result);
}

[Fact]
public static void ArraySingleRankNotSZArrayAccessInterpretted()
{
    int lowerBound = 10;

    var array = System.Array.CreateInstance(typeof(float), new int[] { 3 }, new int[] { lowerBound });
    array.SetValue(1.2f, lowerBound + 0);
    array.SetValue(6.5f, lowerBound + 1);
    array.SetValue(9.21f, lowerBound + 2);

    var func = Expression.Lambda<Func<float>>(
            Expression.ArrayIndex(
                Expression.Constant(array),
                Expression.Constant(lowerBound + 1)
            )
    ).Compile(false);

    var result = func();

    Assert.Equal(6.5f, result);
}

**Comment by afscrome** [comment]
So I'm able to reproduce this through DNX ( https://github.com/afscrome/NonZeroBasedArrayExample )  , however if I run it through a Universal Windows Test Project, it succeeds.  I'm unable to test against the source directory as Visual Studio is unable to compile the project.

The DNX issue appears to be caused by DNX picking the wrong version of System.Linq.Expressions.
As far as I can tell, I configured the project to use System.Linq.Expressions version "4.0.11-rc2-23629" on .Net Core 1.0.0-rc1-update1 x64, however if I look through procmon, I seems the assembly is actually been loaded from `C:\Users\alex\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-rc1-update1\bin\System.Linq.Expressions.ni.dll`.  However since I understand that DNX is now deprecated, I'm not sure we care about this any more.

**Comment by JonHanna** [comment]
It seems likely it's something already fixed by a previous change (and only hit one of the two compilation paths, with Universal Windows hitting the other). Try  using `msbuild /t:RebuildAndTest` (with whatever path you need to get to `msbuild` from inside the `/test` folder if you can't get it to build in Visual Studio (though that should certainly be possible).

**Comment by afscrome** [comment]
Thanks for your help @JonHanna.  I got the tests to run through msbuild, and both passed for me, so looks like this is no longer an issue.

FYI, the visual studio build error is due to #3150 .
