### ISSUE TITLE
System.Net.CredentialKey and System.Net.CredentialHostKey should implement IEquatable

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#5137]
These classes exist to be used as keys, and hence to be compared for equality. As such the faster path offered to `EqualityComparer<T>.Default` by implementing `IEquatable` is worth obtaining.

Doing so would also remove the logical error identified in #5118, and although the path with this error (throwing on comparison with other instance of another type) is unreachable, that's worth doing.

**Comment by SidharthNabar** [comment]
@JonHanna - Is there a difference between what this issue is tracking and what #5138 is tracking?

**Comment by JonHanna** [comment]
@SidharthNabar, no, #5138 is a PR implementing what this issue suggests.
