### ISSUE TITLE
DriveInfo test has race condition

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#514]
See the following non-deterministic failure:
http://corefx-ci.cloudapp.net/jenkins/job/dotnet_corefx_windows_prtest/211/console

```
11:39:04      System.IO.FileSystem.DriveInfoTests.ctor_str.Test01 [FAIL]
11:39:04         Error, Other properties didn't work. Path: C
11:39:04         Stack Trace:
11:39:04            c:\Jenkins\workspace\dotnet_corefx_windows_prtest\src\System.IO.FileSystem.DriveInfo\tests\CtorStrTests.cs(93,0): at System.IO.FileSystem.DriveInfoTests.ctor_str.Test01()
```

It's not hard to see why this might happen: 
https://github.com/dotnet/corefx/blob/86f6a8ff589cd7f0fbb0237ef7de97bd92046d7b/src/System.IO.FileSystem.DriveInfo/tests/CtorStrTests.cs#L193
```C#
if (checkDrive.AvailableFreeSpace != drive.AvailableFreeSpace)
```

... but the free space can obviously change at any time so there's no way this will always work!

FWIW, the DriveInfo tests are in terrible shape and should be completely rewritten IMHO.

**Comment by stephentoub** [comment]
Fixed by #1109
