### ISSUE TITLE
JIT Failure of method referencing Path.GetDirectoryName, method in PCL, referenced via a full .NET console app

### ISSUE THREAD

**Issue by robpaveza** [dotnet/corefx#5140]
I created a class in a PCL which is failing to JIT on full .NET.  It's throwing a `FileNotFoundException` reporting that `System.IO.FileSystem` could not be loaded.  Looking at the disassembly, it appears to be a factoring of File.Exists:

    IL_005b: call bool [System.IO.FileSystem]System.IO.File::Exists(string)

Details of PCL:
Targets: .NET Framework 4.6, ASP.NET Core 5.0, Windows Universal 10.0
Build: Any CPU, allows unsafe
References: Microsoft.NETCore, Microsoft.NETCore.Portable.Compatibility

Details of console app:
Target framework: .NET Framework 4.6
Build: Any CPU, Prefer 32-bit is off
References: Microsoft.CSharp, PCL, System, System.Core, System.Xml, System.Xml.Linq

In the PCL, I have a static class with a `Lazy<MyApi>` which is initialized to `new Lazy<MyApi>(Load)`.  The `Load` function fails to compile; the FileNotFoundException has this message: 

    An unhandled exception of type 'System.IO.FileNotFoundException' occurred in mscorlib.dll
    Additional information: Could not load file or assembly 'System.IO.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

Here's the FusionLog in the exception:

    === Pre-bind state information ===
    LOG: DisplayName = System.IO.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
     (Fully-specified)
    LOG: Appbase = file:///D:/Projects/jsrt-dotnet/src/ConsoleHost/bin/Debug/
    LOG: Initial PrivatePath = NULL
    Calling assembly : Microsoft.Scripting, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
    ===
    LOG: This bind starts in default load context.
    LOG: Using application configuration file: D:\Projects\jsrt-dotnet\src\ConsoleHost\bin\Debug\ConsoleHost.vshost.exe.Config
    LOG: Using host configuration file: 
    LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
    LOG: Post-policy reference: System.IO.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    LOG: Attempting download of new URL file:///D:/Projects/jsrt-dotnet/src/ConsoleHost/bin/Debug/System.IO.FileSystem.DLL.
    LOG: Attempting download of new URL file:///D:/Projects/jsrt-dotnet/src/ConsoleHost/bin/Debug/System.IO.FileSystem/System.IO.FileSystem.DLL.
    LOG: Attempting download of new URL file:///D:/Projects/jsrt-dotnet/src/ConsoleHost/bin/Debug/System.IO.FileSystem.EXE.
    LOG: Attempting download of new URL file:///D:/Projects/jsrt-dotnet/src/ConsoleHost/bin/Debug/System.IO.FileSystem/System.IO.FileSystem.EXE.

**Comment by robpaveza** [comment]
FWIW, I was able to add System.IO.FileSystem to the packages.config.  I guess the question now is, why didn't that happen when referencing the PCL?

**Comment by ericstj** [comment]
Your PCL was referencing that package but your desktop application was not.  This is happening because the desktop project is still using nuget v2 which doesn't automatically flow package dependencies between projects.  If you add a project.json to the desktop project with the following content does the issue go away?
```
{
  "frameworks": {
    "net46": {}
  },
  "runtimes": {
    "win": {}
  }
}
```
/cc @Pilchie @yishaigalatzer

**Comment by ericstj** [comment]
@robpaveza can you please let me know if using the project.json in the desktop project fixed your issue?  The way to think about this is that portable now brings in some packages by default that aren't part of the default profile.  Those packages are required to bring in the implementation for the added API.  If you are using packages.config you always have to make sure you install the same packages in a referencing project that are in the referenced project.  If you are using project.json this happens automatically.

**Comment by chcosta** [comment]
Closing this issue.  @robpaveza, please feel free to re-open this issue if you continue to have a problem after following Eric's comment.

**Comment by ericstj** [comment]
If you are still seeing this in the desktop project after adding the project.json you may be hitting https://github.com/NuGet/Home/issues/966.
