### ISSUE TITLE
HashSet constructor perf optimization concern

### ISSUE THREAD

**Issue by justinvp** [dotnet/corefx#5141]
#4349 added an optimization to `HashSet<T>`'s constructor when constructing from another `HashSet<T>` with the same comparer, by cloning the other `HashSet<T>`'s fields:

```c#
public HashSet(IEnumerable<T> collection, IEqualityComparer<T> comparer) : this(comparer)
{
    ...

    var otherAsHashSet = collection as HashSet<T>;
    if (otherAsHashSet != null && AreEqualityComparersEqual(this, otherAsHashSet))
    {
        ...

        _buckets = (int[])otherAsHashSet._buckets.Clone();
        _slots = (Slot[])otherAsHashSet._slots.Clone();

        _count = otherAsHashSet._count;
        ...
    }
    ....
}
```

The upside to this optimization is it's fast, but there's a downside that I haven't seen discussed: If the other set had a large number of items at one point, and was subsequently reduced in size, the new set is going to simply clone the `_buckets` and `_slots` arrays, which means the new set could be creating new arrays that are substantially larger than they need to be.

For example:

```c#
var source = new HashSet<int>(Enumerable.Range(1, 8950));
source.Clear();
source.UnionWith(Enumerable.Range(1, 20));

var destination = new HashSet<int>(source);
```

Behavior before the #4349 optimization:
 - `source._buckets` and `source._slots` are of length 17,519.
 - `destination._buckets` and `destination._slots` are of length 23.

Behavior after the #4349 optimization:
 - `source._buckets` and `source._slots` are of length 17,519.
 - `destination._buckets` and `destination._slots` are of length 17,519.

A workaround would be to call `source.TrimExcess()` before using it to construct a new `HashSet<T>`, or calling `destination.TrimExcess()` after constructing, but that won't help existing code and using `TrimExcess()` is going to result in more array allocations.

It'd be nice if the optimized path didn't blindly clone potentially unnecessarily huge arrays for `_buckets` and `_slots` when smaller array sizes would be sufficient for the destination.

Does anyone else share this concern?

An alternative optimization might look something like:

```c#
var otherAsHashSet = collection as HashSet<T>;
if (otherAsHashSet != null && AreEqualityComparersEqual(this, otherAsHashSet))
{
    Initialize(otherAsHashSet.Count);

    int lastIndex = otherAsHashSet._lastIndex;
    Slot[] slots = otherAsHashSet._slots;
    for (int i = 0; i < lastIndex; i++)
    {
        if (slots[i].hashCode >= 0)
        {
            AddIfNotPresent(slots[i].hashCode, slots[i].value)
        }
    }
}
```

Where `AddIfNotPresent` has a new overload that supports taking a pre-calculated hashcode. This entire alternative optimization could also be moved inside `UnionWith`, which would simplify the constructor and optimize `UnionWith`.

cc: @tpetrina @stephentoub @ellismg @ianhays @JonHanna

**Comment by JonHanna** [comment]
> Does anyone else share this concern?

Yes, I've been thinking on exactly this over dinner, having fixed a bug with this constructor I  #5131. I had though thought only to maybe skip the optimised path if it could be determined as perhaps suboptimal.

> Where `AddIfNotPresent` has a new overload that supports taking a pre-calculated hashcode.

And for that matter need not concern itself with the IfNotPresent possibility, or with updating the version, if this is the only place it could be called.

There's a threshold somewhere determining whether this or the current behaviour is preferred, but it's perhaps more complicated than a simple ratio.
