### ISSUE TITLE
 Build failure on master (Windows) - TraceSource.Tests "The UTC time represented when the offset is applied must be between year 0 and 10,000."

### ISSUE THREAD

**Issue by clrjunkie** [dotnet/corefx#5154]
build /t:rebuild /property:Configuration=Debug

 === TEST EXECUTION SUMMARY ===
     System.Diagnostics.Tracing.Tests  Total: 25, Errors: 0, Failed: 1, Skipped: 0, Time: 4.682s
  Discovering: System.Globalization.Calendars.Tests
C:\dev\corefx\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00141\lib\tests.targets(129,5): warning MSB3073: T
he command "C:\dev\corefx\bin/tests/Windows_NT.AnyCPU.Debug\System.Diagnostics.Tracing.Tests\dnxcore50/CoreRun.exe xuni
t.console.netcore.exe System.Diagnostics.Tracing.Tests.dll  -xml testResults.xml -notrait category=nonwindowstests -not
rait Benchmark=true  -notrait category=OuterLoop -notrait category=failing " exited with code 1. [C:\dev\corefx\src\Sys
tem.Diagnostics.Tracing\tests\System.Diagnostics.Tracing.Tests.csproj]
C:\dev\corefx\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00141\lib\tests.targets(136,5): error : One or mor
e tests failed while running tests from 'System.Diagnostics.Tracing.Tests' please check log for details! [C:\dev\corefx
\src\System.Diagnostics.Tracing\tests\System.Diagnostics.Tracing.Tests.csproj]

 === TEST EXECUTION SUMMARY ===
     System.Net.Http.WinHttpHandler.Functional.Tests  Total: 9, Errors: 0, Failed: 1, Skipped: 0, Time: 9.644s
  System.Net.Http.WinHttpHandler.Unit.Tests -> C:\dev\corefx\bin\Windows_NT.AnyCPU.Debug\System.Net.Http.WinHttpHandler
  .Unit.Tests\System.Net.Http.WinHttpHandler.Unit.Tests.dll
C:\dev\corefx\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00141\lib\tests.targets(129,5): warning MSB3073: T
he command "C:\dev\corefx\bin/tests/Windows_NT.AnyCPU.Debug\System.Net.Http.WinHttpHandler.Functional.Tests\dnxcore50/C
oreRun.exe xunit.console.netcore.exe System.Net.Http.WinHttpHandler.Functional.Tests.dll  -xml testResults.xml -notrait
 category=nonwindowstests -notrait Benchmark=true  -notrait category=OuterLoop -notrait category=failing " exited with
code 1. [C:\dev\corefx\src\System.Net.Http.WinHttpHandler\tests\FunctionalTests\System.Net.Http.WinHttpHandler.Function
al.Tests.csproj]
C:\dev\corefx\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00141\lib\tests.targets(136,5): error : One or mor
e tests failed while running tests from 'System.Net.Http.WinHttpHandler.Functional.Tests' please check log for details!
 [C:\dev\corefx\src\System.Net.Http.WinHttpHandler\tests\FunctionalTests\System.Net.Http.WinHttpHandler.Functional.Test
s.csproj]

**Comment by JonHanna** [comment]
Which test failed?

**Comment by clrjunkie** [comment]
Where is it logged ?

**Comment by JonHanna** [comment]
It should have been in the output a bit above where you quoted from. It's possible that the test that failed is one that needed to access the web and just got unlucky in doing so rather than there being any actual bug.

**Comment by clrjunkie** [comment]
I'll try again.

**Comment by clrjunkie** [comment]
Seems so... but now I get a different error (and warning)
 
 Error:
 
 === TEST EXECUTION SUMMARY ===
     System.Diagnostics.Tools.Tests  Total: 6, Errors: 0, Failed: 0, Skipped: 0, Time: 0.475s
  xUnit.net console test runner (64-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.

  Discovering: System.Diagnostics.TraceSource.Tests
  Starting:    System.Diagnostics.Tracing.Tests
  Discovered:  System.Diagnostics.TraceSource.Tests
  Starting:    System.Diagnostics.TraceSource.Tests
  Finished:    System.Diagnostics.TraceSource.Tests

  === TEST EXECUTION SUMMARY ===
     System.Diagnostics.TraceSource.Tests  Total: 246, Errors: 0, Failed: 0, Skipped: 0, Time: 0.951s
     BasicEventSourceTests.FuzzyTests.Test_Write_Fuzzy [FAIL]
        System.ArgumentOutOfRangeException : The UTC time represented when the offset is applied must be between year 0
   and 10,000.
        Parameter name: offset
        Stack Trace:
              at System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
              at System.DateTimeOffset..ctor(Int64 ticks, TimeSpan offset)
           C:\dev\corefx\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\FuzzyTests.cs(2671,0): at BasicEvent
  SourceTests.FuzzyTests.<>c__DisplayClass0_0.<Test_Write_Fuzzy>b__68()
           C:\dev\corefx\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\Harness\EventTestHarness.cs(105,0):
  at BasicEventSourceTests.EventTestHarness.RunTests(List`1 tests, Listener listener, EventSource source, FilteringOpti
  ons options)
           C:\dev\corefx\src\System.Diagnostics.Tracing\tests\BasicEventSourceTest\FuzzyTests.cs(2750,0): at BasicEvent
  SourceTests.FuzzyTests.Test_Write_Fuzzy()
  Finished:    System.Diagnostics.Tracing.Tests
  System.Dynamic.Runtime -> C:\dev\corefx\bin\Windows_NT.AnyCPU.Debug\System.Dynamic.Runtime\System.Dynamic.Runtime.dll

  === TEST EXECUTION SUMMARY ===
     System.Diagnostics.Tracing.Tests  Total: 25, Errors: 0, Failed: 1, Skipped: 0, Time: 2.136s
C:\dev\corefx\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00141\lib\tests.targets(129,5): warning MSB3073: T
he command "C:\dev\corefx\bin/tests/Windows_NT.AnyCPU.Debug\System.Diagnostics.Tracing.Tests\dnxcore50/CoreRun.exe xuni
t.console.netcore.exe System.Diagnostics.Tracing.Tests.dll  -xml testResults.xml -notrait category=nonwindowstests -not
rait Benchmark=true  -notrait category=OuterLoop -notrait category=failing " exited with code 1. [C:\dev\corefx\src\Sys
tem.Diagnostics.Tracing\tests\System.Diagnostics.Tracing.Tests.csproj]
C:\dev\corefx\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00141\lib\tests.targets(136,5): error : One or mor
e tests failed while running tests from 'System.Diagnostics.Tracing.Tests' please check log for details! [C:\dev\corefx
\src\System.Diagnostics.Tracing\tests\System.Diagnostics.Tracing.Tests.csproj]
  Finished:    System.Diagnostics.Process.Tests

  === TEST EXECUTION SUMMARY ===
     System.Diagnostics.Process.Tests  Total: 74, Errors: 0, Failed: 0, Skipped: 0, Time: 10.555s
  System.Globalization.Calendars.Tests -> C:\dev\corefx\bin\Windows_NT.AnyCPU.Debug\System.Globalization.Calendars.Test
  s\System.Globalization.Calendars.Tests.dll
  System.Collections -> C:\dev\corefx\bin\Windows_NT.AnyCPU.Debug\System.Collections\System.Collections.dll
  System.Globalization.Extensions -> C:\dev\corefx\bin\Windows_NT.AnyCPU.Debug\System.Globalization.Extensions\System.G
  lobalization.Extensions.dll
  xUnit.net console test runner (64-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.

  Discovering: System.Globalization.Calendars.Tests
  Discovered:  System.Globalization.Calendars.Tests
  Starting:    System.Globalization.Calendars.Tests
  Finished:    System.Globalization.Calendars.Tests
  
  
  Warning:
  
   === TEST EXECUTION SUMMARY ===
     System.Text.Encoding.Extensions.Tests  Total: 126, Errors: 0, Failed: 0, Skipped: 0, Time: 0.814s
  System.Text.Encodings.Web -> C:\dev\corefx\bin\Windows_NT.AnyCPU.Debug\System.Text.Encodings.Web\System.Text.Encoding
  s.Web.dll
  Discovered:  System.IO.FileSystem.Tests
  System.Text.Encodings.Web.Tests -> C:\dev\corefx\bin\Windows_NT.AnyCPU.Debug\System.Text.Encodings.Web.Tests\System.T
  ext.Encodings.Web.Tests.dll
  System.ServiceProcess.ServiceController.TestNativeService.vcxproj -> C:\dev\corefx\bin/Windows_NT.AnyCPU.Debug\System
  .ServiceProcess.ServiceController.TestNativeService\System.ServiceProcess.ServiceController.TestNativeService.exe
  xUnit.net console test runner (64-bit .NET Core)
  System.ServiceProcess.ServiceController.Tests -> C:\dev\corefx\bin\Windows_NT.AnyCPU.Debug\System.ServiceProcess.Serv
  iceController.Tests\System.ServiceProcess.ServiceController.Tests.dll
  Copyright (C) 2014 Outercurve Foundation.

  Starting:    System.IO.FileSystem.Tests
  Discovering: System.Text.Encodings.Web.Tests
  Discovered:  System.Text.Encodings.Web.Tests
  Starting:    System.Text.Encodings.Web.Tests
  xUnit.net console test runner (64-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.

  Discovering: System.ServiceProcess.ServiceController.Tests
  Discovered:  System.ServiceProcess.ServiceController.Tests
  Starting:    System.ServiceProcess.ServiceController.Tests
EXEC : warning : Failed to stop service (1052). Will still delete, but recreating may fail if the service is still runn
ing. [C:\dev\corefx\src\System.ServiceProcess.ServiceController\tests\System.ServiceProcess.ServiceController.Tests\Sys
tem.ServiceProcess.ServiceController.Tests.csproj]
  Finished:    System.ServiceProcess.ServiceController.Tests

  === TEST EXECUTION SUMMARY ===
     System.ServiceProcess.ServiceController.Tests  Total: 12, Errors: 0, Failed: 0, Skipped: 0, Time: 5.621s
  System.Text.Encoding.Tests -> C:\dev\corefx\bin\Windows_NT.AnyCPU.Debug\System.Text.Encoding.Tests\System.Text.Encodi
  ng.Tests.dll
  Finished:    System.IO.FileSystem.Tests

**Comment by ellismg** [comment]
What timezone are you located in?

**Comment by clrjunkie** [comment]
+02:00

**Comment by ellismg** [comment]
Should be fixed by #5300
