### ISSUE TITLE
Make IImmutableList covariant like IReadOnlyList, IEnumerable etc.

### ISSUE THREAD

**Issue by bluemmc** [dotnet/corefx#5164]
I need  System.Collections.Immutable interfaces such as IImmutableList to be covariant just like IReadOnlyList, IEnumerable in order to be able to write stuff like this:
```
public interface IResources<out T> where T : IDomainEntity
{
        IImmutableList<T> ShouldWorkButCompilerGivesErrorDueToIImmutableListNotCovariant { get; }
        IReadOnlyList<T> Works { get; }
}
```

**Comment by vcsjones** [comment]
I don't think it can reasonably be made covariant since the interface has contravariant methods 
like [`Add<T>`](https://msdn.microsoft.com/en-us/library/dn466930.aspx)

**Comment by bluemmc** [comment]
Maybe it can be done if the covariant methods are moved to a new interface like IImmutableListBase<out T> that  IImmutableList<T> inherits from ?

**Comment by CodesInChaos** [comment]
@bluemmc Almost all covariant methods are already on `IReadOnlyList<T>`. So it sounds like you want is some kind of marker that tells you that this collection is immutable without adding any functionality on top of `IReadOnlyList<T>`.

**Comment by vcsjones** [comment]
`IImmutableList<T>` already implements the `IReadOnlyList<T>` interface, which is pretty much the interface you're asking for.

**Comment by bluemmc** [comment]
Thanks for all the feedback. You are both right. I will have to do with IReadOnlyList<T> when I need it in covariant form (as I do in my example).
