### ISSUE TITLE
TLS Client Handshake seems to violate the protocol in unix

### ISSUE THREAD

**Issue by kkurni** [dotnet/corefx#5178]
I am currently having problem communicating with SQL Server (older version) with TLS 1.0

I do notice that the packet that was sent by SSLStream sent different versions In UNIX

![image](https://cloud.githubusercontent.com/assets/698547/12099774/6aafc6a0-b2df-11e5-8726-9f003ccd0f90.png)

**Comment by kkurni** [comment]
@corivera @saurabh500

**Comment by vijaykota** [comment]
The packet shown is consistent with the client proposing TLS 1.2 and is not a protocol error. The two versions would have matched if the client had proposed TLS 1.0 instead of 1.2

In your case since the server seems to be expecting TLS 1.0, client should force this by explicitly passing SslProtocols.Tls as a parameter to SslStream.AuthenticateAsClient

**Comment by kkurni** [comment]
@vijaykota , why does it behave differently in Windows ?

With the same code, client use TLS 1.2 and proposing TLS 1.2 in windows.
But in Unix client use TLS 1.0 and proposing TLS 1.2.

**Comment by vijaykota** [comment]
Though the packet is diff. in Unix case, the server should still be able to work with it. Can you share the rest of the network capture - maybe there is some failure down the line which is not related to this packet format.

I confirmed that this diff. should not matter by trying the foll.:
On Windows server, started an SSL listener that accepts only TLS 1.0
''''
sslStream.AuthenticateAsServer(cert, false, SslProtocols.Tls, false)
''''

On Unix client, I tried connecting using TLS 1.2
''''
openssl s_client -debug -connect <server>:<port>
'''''
The connection succeeded and the debug output of OpenSsl shows that actually TLS1.0 is being used.

>  client should force this by explicitly passing SslProtocols.Tls
Sorry I was wrong about this and no code change is needed on the client. The server will indicate that it can only support TLS 1.0 and the SSL library is supposed to take care of it (got confirmed by my experiment above)

**Comment by kkurni** [comment]
Unfortunately, the server doesn't use CoreFX.

This server listen to SSL with Windows API. (probably the old version which only accept TLS 1.0).

I also notice that this different version will not matter, as It can success with this different version. So I will close this issue.

But this additional 32 bytes of data still an issue for us, https://github.com/dotnet/corefx/issues/5187
I try to use libssl.so.1.0.0 which does send ssl handshake exactly the same as corefx. But when send application data, it sent without this additional 32 bytes.
