### ISSUE TITLE
System.Buffers configuration and Shared property configuration

### ISSUE THREAD

**Issue by sokket** [dotnet/corefx#5182]
The System.Buffers namespace contains an ArrayPool implementation with the following characteristics:
1) You can create an instance of an ArrayPool<T> with your own configuration
2) You can use the Shared ArrayPool<T> with pre-set configuration options

For option 2 above, there are a couple issues; first, the Shared Pool property cannot be changed to be a user-defined type (currently). This means that if a user has a specific Pool for their scenario that is more efficient (in their scenario) than the default, they must handle sharing themselves...which defeats the purpose of the Shared property. The second problem is that if the default pool characteristics work for the consumer's scenario but they need to tweak the configuration values (max buffer size, max number of buffers, etc), there isn't a way to do this. 

These problems are made more difficult by the fact that the framework itself will be using the Shared pool, meaning before any user code runs, the Shared pool will have already been initialized using the hardcoded configuration values.

We need a solution to 
a) Configure the Shared pool before Framework code has a chance to run, specified by the user
b) allow the Shared pool to be swapped out with a user implementation, preferably before the Framework code has a chance to initialize it

**Comment by terrajobst** [comment]
What is the specific example where the pool needs to use a custom policy? In general, I don't quite like systems with have an open ended policy and yet use centralized sharing. Libraries can never really set the pool, it would be up to the app/app model to initialize it, so general purpose libraries can't really rely on a specific pool pattern.

+ @KrzysztofCwalina

>  they must handle sharing themselves...which defeats the purpose of the Shared property.

Why do you say that? Suppose I'm implementing something like Roslyn, let's call it Froslyn. I need to use buffers for parsing assemblies After some measurement I'm convinced I can provide a better pool than the default. I create a new `static class FroslynMetadataPool`:

```C#
static class FroslynMetadataBufferPool
{
    public static ArrayPool Instance { get; } = new ArrayPool(...);
}
```

Why would that not work?

**Comment by terrajobst** [comment]
@KrzysztofCwalina, I've assigned you and removed the label. Feel free to add it back if you think we've enough information to have a meeting on this.

**Comment by KrzysztofCwalina** [comment]
@terrajobst, this is meant to be used to optimize at the app level. Individual libraries should not be doing it. Ideally, this configuration would be handled by some kind of config system, which we don't really have a general solution for in .net core.

@sokket, could you work with ASP.NET team on a short writeup describing the scenarios. Once we have it, I will flip the lable back to ready for review.

**Comment by benaadams** [comment]
Something in?
```json
"runtimeOptions": {
  "configProperties": {
  }
},
```

**Comment by alexperovich** [comment]
@sokket Are you still working on this?

**Comment by sokket** [comment]
Nope, I am not

**Comment by karelz** [comment]
No strong desire to do this from anyone for 10 months. Let's close it.

Overall it is unclear if it is a good idea, however, if there is a good API proposal thought through from all angles (esp. impact on Framework), we're willing to review it - in such case, please reopen the issue or create a new one.
