### ISSUE TITLE
referencesource repo license incorrect for individual files

### ISSUE THREAD

**Issue by gautamsi** [dotnet/corefx#52]
some of the files I looked up, it has header comment with Apache 2.0 license.
which license should apply for those files? MIT or Apache 2.0

**Comment by joshfree** [comment]
@alokshriram can you follow up on the https://github.com/microsoft/referencesource repo?

**Comment by ellismg** [comment]
@terrajobst Can you handle this?

**Comment by jasonwilliams200OK** [comment]
This belongs to https://github.com/microsoft/referencesource. Should this be closed from this repo and opened in reference source one instead?

**Comment by FiveTimesTheFun** [comment]
Hi, the referencesource repro doesn't have issue tracking turned on, which is why I believe it was opened here.  I'll also ask @richlander to jump in with the definitive answer.

**Comment by richlander** [comment]
Just enabled issue tracking.

**Comment by jasonwilliams200OK** [comment]
Note that Roslyn code is under Apache license
https://github.com/dotnet/roslyn/search?utf8=✓&q=apache&type=Code

**Comment by joshfree** [comment]
@blackdwarf could you help with the http://github.com/microsoft/referencesource individual file license issue?  Also I don't think issue tracking should be enabled for that repo - it's slowly collecting stackoverflow type questions which people won't see.

**Comment by blackdwarf** [comment]
@joshfree sure thing. I can disable issues right now, do we want that?

**Comment by joshfree** [comment]
@blackdwarf yeah, if you could do that and point the 6-7 people who created issues in that repo to the right place (similar to the blurb in the corefx readme) that would be helpful

**Comment by blackdwarf** [comment]
@joshfree not a problem, I assume the right place is corefx?

**Comment by joshfree** [comment]
@blackdwarf no, it's actually not GitHub/corefx for .NET Framework specific asks.

> How to Engage, Contribute and Provide Feedback
>
>Some of the best ways to contribute are to try things out, file bugs, and join in design conversations. If you are having issues with the Full .NET Framework or .NET Runtime, the best way to file a bug is at Connect (http://connect.microsoft.com/VisualStudio) or through Product Support (https://support.microsoft.com/en-us/contactus?ws=support) if you have a contract.

**Comment by blackdwarf** [comment]
@joshfree off I go to solve that particular (easy) thingie.

**Comment by joshfree** [comment]
@blackdwarf @richlander can you give an update on this?

**Comment by richlander** [comment]
The README.md on that repository has been updated to reflect this request.

https://github.com/Microsoft/referencesource/blob/master/README.md

**Comment by gautamsi** [comment]
you still miss the point, this request was to correct individual file header, most file says "Copyright (c) Microsoft Corporation.  All rights reserved" that does override the MIT status as mentioned in README
