### ISSUE TITLE
corefx code coverage runs are consistently failing in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5204]
Some are failing with errors like this in the log:
```
12:13:13   An exception occured: Failed to register(user:True,register:True,is64:False):5 the profiler assembly; you may want to look into permissions or using the -register:user option instead. C:\Windows\system32\regsvr32.exe /s  /n /i:user "d:\j\workspace\dotnet_corefx\code_coverage_windows\packages\OpenCover\4.6.166\tools\x86\OpenCover.Profiler.dll"
12:13:13   stack:    at OpenCover.Framework.ProfilerRegistration.ExecuteRegsvr32(Boolean userRegistration, Boolean register, Boolean is64) in c:\projects\opencover\main\OpenCover.Framework\ProfilerRegistration.cs:line 66
12:13:13      at OpenCover.Console.Program.RunWithContainer(CommandLineParser parser, Bootstrapper container, IPersistance persistance) in c:\projects\opencover\main\OpenCover.Console\Program.cs:line 114
12:13:13      at OpenCover.Console.Program.Main(String[] args) in c:\projects\opencover\main\OpenCover.Console\Program.cs:line 57
12:13:14 d:\j\workspace\dotnet_corefx\code_coverage_windows\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00142\lib\tests.targets(129,5): warning MSB3073: The command "d:\j\workspace\dotnet_corefx\code_coverage_windows\packages/OpenCover\4.6.166\tools\OpenCover.Console.exe -filter:"+[*]* -[*.Tests]*" -excludebyfile:"*\Common\src\System\SR.*" -nodefaultfilters -excludebyattribute:*.ExcludeFromCodeCoverage* -skipautoprops -hideskipped:All -threshold:1 -returntargetcode -register:user -target:d:\j\workspace\dotnet_corefx\code_coverage_windows\bin/tests/Windows_NT.AnyCPU.Debug\System.Net.Primitives.Pal.Tests\dnxcore50/CoreRun.exe -output:d:\j\workspace\dotnet_corefx\code_coverage_windows\bin/tests/coverage\System.Net.Primitives.Pal.Tests.coverage.xml -targetargs:"xunit.console.netcore.exe System.Net.Primitives.Pal.Tests.dll  -xml testResults.xml -notrait category=nonwindowstests -notrait Benchmark=true  -notrait category=OuterLoop -notrait category=failing "" exited with code 1. [d:\j\workspace\dotnet_corefx\code_coverage_windows\src\System.Net.Primitives\tests\PalTests\System.Net.Primitives.Pal.Tests.csproj]
```

Others are failing with errors like this in the log:
```
16:21:59   Unhandled Exception: System.OverflowException: Array dimensions exceeded supported range.
16:21:59      at OpenCover.Framework.Communication.CommunicationManager.HandleMemoryBlock(IManagedMemoryBlock mmb) in c:\projects\opencover\main\OpenCover.Framework\Communication\CommunicationManager.cs:line 82
16:22:00      at OpenCover.Framework.Manager.ProfilerManager.<>c__DisplayClass24.<ProcessBlock>b__22(Object state) in c:\projects\opencover\main\OpenCover.Framework\Manager\ProfilerManager.cs:line 248
16:22:00      at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
16:22:00      at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
16:22:01      at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
16:22:01      at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

We haven't updated to a newer version of OpenCover since July, and these issues only just started happening in the last few days, implying to me this is somehow infrastructure related...?

**Comment by stephentoub** [comment]
@sawilde, have you seen these exceptions from OpenCover before?  Any ideas what might be causing this?

**Comment by stephentoub** [comment]
cc: @weshaggard, @mmitche 

I suspect that this (and also an issue where some libraries are failing to have coverage results as part of a full build, but are successfully handled when built on their own) may be due to ```build.cmd /p:Coverage=true``` now running projects in parallel, whereas previously I believe we tried to force code coverage builds to run serially.

**Comment by sawilde** [comment]
@stephentoub I haven't seen this one before - what version are you running?

**Comment by stephentoub** [comment]
>  I haven't seen this one before - what version are you running?

4.6.166. Though in hopes it might help, we're moving to 4.6.261-rc.

**Comment by sawilde** [comment]
Please use latest [appveyor build](https://ci.appveyor.com/project/sawilde/opencover/history); that RC was shall we say "an embarrassment" and especially on how you use OpenCover.

**Comment by stephentoub** [comment]
> Please use latest appveyor build

We pull this from NuGet so we'll need to wait to upgrade again until there's a new build up there.

**Comment by sawilde** [comment]
> We pull this from NuGet

No worries, I'll see about creating a release candidate - we are due one soon.

**Comment by sawilde** [comment]
please try https://www.nuget.org/packages/OpenCover/4.6.401-rc

**Comment by weshaggard** [comment]
@stephentoub it does look like we have inadvertently started doing parallel builds during coverage again.
Here is where we disable parallel builds:
https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/CodeCoverage.targets#L32
However we are no longer importing CodeCoverage.targets in all the builds that are doing traversals. This was caused by the introduction of all the .builds files as well as the split of dirs.proj into ref.builds/src.builds/tests.builds, see https://github.com/dotnet/corefx/commit/987e4e57c12dbfff29e7a7a597d8db4bc14963dc. 

I'm working a fix, expect a PR shortly.
