### ISSUE TITLE
Consolidate SafeTokenHandle and SafeAccessTokenHandle

### ISSUE THREAD

**Issue by venkat-raman251** [dotnet/corefx#5209]
SafeTokenHandle and SafeAccessTokenHandle in corefx / src / System.Security.Principal.Windows / src / Microsoft / Win32 / SafeHandles / seem to be the same. They must be consolidated into one or needs investigation as to why they both are required.

**Comment by venkat-raman251** [comment]
@weshaggard : Who can look into this? Or is this just a placeholder for us to visit later.

**Comment by weshaggard** [comment]
It is a clean-up work-item that we will visit later. This is a perfect "up-for-grabs" item that someone in the community might be willing to pickup.

**Comment by venkat-raman251** [comment]
@weshaggard Would this item include cleaning up the Common folder? Which is currentlly inconsistent as some use SafeTokenHandle and some use SafeAccessTokenHandle

**Comment by Clockwork-Muse** [comment]
From a cursory look: the static `SafeTokenHandle.InvalidHandle` can be set to a valid handle.  That might result in surprises later.

**Comment by Clockwork-Muse** [comment]
`SafeAccessTokenHandle` has a ref which is annotated with `SecurityCritical`, even though the src one is not.
`SafeTokenHandle` in the `System.Security.Principal.Windows` package appears to be unused.  
There are additional copies in `System.Security.AccessControl` and `System.Diagnostics.Process`, one of which is identical and one which is a copy of `SafeAccessTokenHandle`.

`System.Security.AccessControl` has a reference to `Principal.Windows`, so presumably could use that one if it was made public (but the visibility change would likely be bad).

So should all three be consolidated into one?  (presumably into Common, then)

**Comment by AlexBHarley** [comment]
@Clockwork-Muse started working on this in PR #6101 - however as of your latest comment, it seems like there is more to be done

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/corefx/pull/6282
