### ISSUE TITLE
Update NETStandard.* package versions to match the latest netstandard version they support

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#5216]
Today the NETStandard.* packages are versioned 1.0 but it would be clearer if they were reversion-ed to match the latest supported version of NETStandard.

**Comment by ericstj** [comment]
1.5 is currently the highest netstandard version per: https://github.com/NuGet/Home/issues/1691

**Comment by chcosta** [comment]
This will be part of other work which is in progress.  Moving milestone.

**Comment by weshaggard** [comment]
I've updated the version of NETStandard.Library to 1.5
