### ISSUE TITLE
Add signing support to System.Reflection.Metadata

### ISSUE THREAD

**Issue by terrajobst** [dotnet/corefx#5217]
There is already work in progress to [add the capability](https://github.com/dotnet/cli/issues/720) to the `dotnet` tool

However, compilers usually do strong naming as part of the compilation process. This requires having a library that can be used to perform the signing. It seems `System.Reflection.Metadata` is the right location said functionality, especially when we support writing metadata.

Compiler integration is also most logical way to make these attributes work:

* `AssemblyDelaySignAttribute`
* `AssemblyKeyFileAttribute`
* `AssemblyKeyNameAttribute`

**Comment by tmat** [comment]
Implemented by https://github.com/dotnet/corefx/pull/8316

**Comment by tmat** [comment]
Will do API review as part of overall SRM 1.4 new API review.
