### ISSUE TITLE
VB projects cannot be built on non-Windows platforms

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#5230]
We only have one in the repo here, but I believe there is an issue in the x-plat version of MSBuild that is causing these to fail. I think the problem is that this Task (https://github.com/Microsoft/msbuild/blob/xplat/src/Utilities/ToolTask.cs) has a workaround to normalize all backslashes to forward-slashes, for file paths. Unfortunately it does that on the entire response file we generate to pass to vbc.exe. The define constants have quotation marks in them that need to be escaped, so we initially start with something like

```
-define: "CONFIG=\"Debug\"
```

which gets normalized to

```
-define: "CONFIG=/"Debug/"
```

which is no longer valid, and causes vbc.exe to error out. I've manually invoked vbc.exe with the same command line, but with the backslashes put back in, and it seems to work fine.

@weshaggard

**Comment by weshaggard** [comment]
@mellinoe Could you please file a bug on the msbuild repo to make sure this is tracked?

**Comment by mellinoe** [comment]
Filed this issue there: https://github.com/Microsoft/msbuild/issues/422

**Comment by mellinoe** [comment]
Moving this to RTM.
