### ISSUE TITLE
NuGet packages cannot be built on Ubuntu

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#5233]
(Probably other non-Windows platforms as well)

There seems to be some path issue on Ubuntu when running the package build on Ubuntu. It seems like some paths are not being combined properly, or something of the sort. The inputs to the packaging task seem to be correct, though, so there may be an issue in the NuGet task itself. Here's a representative error:

````
/home/eric/projects/corefx/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00144/lib/Packaging.targets : error : Error when creating nuget package from /home/eric/projects/corefx/bin/pkg/specs/System.Reflection.Metadata.nuspec. System.IO.DirectoryNotFoundException: Directory '/home/eric/projects/corefx/bin/pkg/specs/home/eric/projects/corefx/bin/AnyOS.AnyCPU.Debug/System.Reflection.Metadata' not found. [/home/eric/projects/corefx/src/System.Reflection.Metadata/pkg/System.Reflection.Metadata.pkgproj]
````

Notice the path: **/home/eric/projects/corefx/bin/pkg/specs/home/eric/projects/corefx/bin/AnyOS.AnyCPU.Debug/System.Reflection.Metadata**
is malformed and includes the whole project directory prefix twice.

[Full build output with stacktrace](https://gist.github.com/mellinoe/053405a1187abb91abf3)

@ericstj , @weshaggard

**Comment by ericstj** [comment]
I took a look with Eric and it seem that the issue might be in nuget.core.  The paths in the nuspec are rooted and for some reason nuget.core is combining them with the directory the nuspec is in.

**Comment by mellinoe** [comment]
Should be fixed as of buildtools 151.

**Comment by ericstj** [comment]
Did you undo your SkipBuildPackages workaround?

**Comment by mellinoe** [comment]
I wasn't aware of that property. It looks like it's been in place for a long time, so it doesn't seem to be working as expected since the packages were still being built.

**Comment by ericstj** [comment]
Woops, I noticed it in another change yesterday and thought you had added it.  We should clean that up. /cc @chcosta
