### ISSUE TITLE
Build.sh runs tests that should not be supported

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#5235]
Running build.sh on Ubuntu (for example) will run the Microsoft.Win32.Registry tests, as well as a bunch of other inapplicable test projects. It seems that only runtests.sh is actually detecting which projects should be skipped.

**Comment by Priya91** [comment]
This does not repro now.

**Comment by weshaggard** [comment]
@priya91 any idea why this isn't any issue any longer?

**Comment by Priya91** [comment]
> any idea why this isn't any issue any longer?

Not sure, why it was even failing in the first place. But now, we do this in buildtools
```
<PropertyGroup>
      <TestDisabled Condition="'%(UnsupportedPlatformsItems.Identity)' == '$(TargetOS)'">true</TestDisabled>
    </PropertyGroup>
```
