### ISSUE TITLE
WindowsIdentity ctor doesn't support WindowsAccountType and isAuthenticated

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#5241]
The ctor was used by NegotiateStream to create an authenticated WindowsIdentity (in NegoState.Windows.cs:333).

The lack of the ctor causes a difference in the behavior of NegotiateStream on .Net Desktop vs CoreFX.

**Comment by bartonjs** [comment]
@CIPop Looking at referencesource (http://referencesource.microsoft.com/#mscorlib/system/security/principal/windowsidentity.cs,09a2e5ad8720f935), the acctType parameter is accepted, but not respected; which possibly is why it didn't make it into the contract.

Is the problem that without forcing IsAuthenticated to true that it's coming back as false? (Namely, that the NegotiateStream-created identity can't satisfy the check for the 'authenticated user' SID)?

**Comment by CIPop** [comment]
@bartonjs this is something that got changed from .Net Framework. Apparently everything works fine in .Net Core but we have some issues with UAP (#21282). 
If the UAP bug isn't related, I'll remove the code comment and close this issue.

**Comment by bartonjs** [comment]
Looks like this was fixed by #31689.
