### ISSUE TITLE
Should Expression.TypeIs allow void as a type argument?

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#5244]
Currently any expression will compare with `void` with `TypeIs` as `false`:

```C#
Expression.Lambda<Func<bool>>(
    Expression.TypeIs(Expression.Empty(), typeof(void))
).Compile()() // false
```

This is at odds with `TypeEqual`:

```C#
Expression.Lambda<Func<bool>>(
    Expression.TypeEqual(Expression.Empty(), typeof(void))
).Compile()() // true
```

The decision happens at `AnalyzeTypeIs()` which is commented as saying:

```C#
// Oddly, we allow void operands
// This is LinqV1 behavior of TypeIs
```

Arguably, its not that odd to allow void operands, considering that expressions of void type are allowed, or more reasonaly that dynamic use could mean passing something an expression of type `void` one time and a different type another.

This also makes it a logical exception to the comment saying the result should match the result of `isinst` since there's no way to pass a void expression's value to in CIL (obviously enough as it doesn't have one). The differences between expression trees and CIL (and C#, VB.NET, etc.) are such that what is meaningless in CIL is meaningful, though constant, in trees.

As such it seems to me that the value of `Expression.TypeIs(Expression.Empty(), typeof(void))` should be true, rather than false.

In the other direction, we allow `Expression.TypeIs(Expression.Constant("hello"), typeof(void))` but:

```C#
Expression.Lambda<Func<bool>>(Expression.TypeIs(Expression.Constant("hello"), typeof(void))).Compile()()
```
Throws `InvalidProgramException`. By the same reasoning as above it would make sense for this to return false. This would also make it match `IsInstanceOf()` (but not `isinst` but again that isn't as meaningful in CIL as it is in trees).

**Comment by JonHanna** [comment]
@bartdesmet of relevance to you perhaps:

The last case of `Expression.TypeIs(Expression.Constant("hello"), typeof(void))` does not throw with the interpreter, so this is another place where the behaviours don't match. In the interpreted case the behaviour matches what I suggest here it should be; returning false.

CC: @VSadov

**Comment by VSadov** [comment]
It is a bit unfortunate that reflection models not returning any value as returning a value of type void.

**Comment by JonHanna** [comment]
If there was a good reason to keep `TypeIs` as always returning `false` for void expressions, anyone who does need it as I suggest it should be could certainly work-around it with some `OrElse`, `AndAlso` and `TypeEqual` expressions.

Maybe we just need to fix the error that happens on the other way around.
