### ISSUE TITLE
Consider creating a gitter channel for corefx repo

### ISSUE THREAD

**Issue by jacobcarpenter** [dotnet/corefx#525]
I was checking out the Aurelia docs (new JS framework), and they casually mention "If you have questions, we hope that you will join us on our [gitter channel](https://gitter.im/Aurelia/Discuss)."

Gitter is apparently a free group chat for open source projects hosted on github. Here's the best "About" page I could find: http://blog.gitter.im/about/. It looks like they have really good github integration (an activity feed that shows PRs; issues; commits; etc).

I'd be really interested in trying out a gitter channel for the corefx repo.

**Comment by HoracioFilho** [comment]
Yeah, it would be very nice :smile:

**Comment by davidfowl** [comment]
Orrrr, jabbr :smile:

**Comment by jacobcarpenter** [comment]
Never used that one, but sure!

**Comment by mmitche** [comment]
Closed, committed at #724
