### ISSUE TITLE
Unix SslStream may be reporting ECDH exchanges as ECDSA

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#5251]
There may be no bug here.  I merely saw some code that confused me while fixing another issue, and feel that it warrants investigation.  If it's correct, it probably warrants a comment :smile:.

https://github.com/dotnet/corefx/blob/71544a4ea55406740b1d3a00667b3ef0b816c9a2/src/Native/System.Security.Cryptography.Native/pal_ssl.cpp#L426-L433
```c++
        case SSL_KeyExchangeAlgorithm::SSL_kECDHr:
            return ExchangeAlgorithmType::SSL_ECDH;

        case SSL_KeyExchangeAlgorithm::SSL_kECDHe:
            return ExchangeAlgorithmType::SSL_ECDSA;

        case SSL_KeyExchangeAlgorithm::SSL_kEECDH:
            return ExchangeAlgorithmType::SSL_ECDSA;
```

Note that ECDHr says ECDH, while ECDHe and EECDH say ECDSA.

Based on comparison against what might be a trace helper in OpenSsl (https://github.com/openssl/openssl/blob/bc71f91064a3eec10310fa4cc14fe2a3fd9bc7bb/ssl/t1_trce.c#L909) I can understand why ECDHe and EECDH say ECDSA, but then I'd expect ECDHr to say RSA.

Really these need to be validated against what we say in Windows for the same session types.

**Comment by AtsushiKan** [comment]
You seem to be the owner of this code - please check this out.

**Comment by bartonjs** [comment]
@ericeil Do you have the bandwidth to look at this one?  Or does it need to play pass-the-parcel back to @AtsushiKan? :smile:

**Comment by ericeil** [comment]
I'll take a look.

**Comment by ericeil** [comment]
It looks like if there *was* a bug here, it's since been fixed by #5608.

**Comment by bartonjs** [comment]
https://github.com/dotnet/corefx/blob/master/src/Native/System.Security.Cryptography.Native/pal_ssl.cpp#L219-L224

```C++
    if (strncmp(keyExchange, "ECDH/RSA", keyExchangeLength) == 0)
        return ExchangeAlgorithmType::SSL_ECDH;
    if (strncmp(keyExchange, "ECDH/ECDSA", keyExchangeLength) == 0)
        return ExchangeAlgorithmType::SSL_ECDSA;
    if (strncmp(keyExchange, "ECDH", keyExchangeLength) == 0)
        return ExchangeAlgorithmType::SSL_ECDSA;
```

It has just reshaped.

ECDH/RSA reports ECDH, but ECDH/ECDSA reports ECDSA, and ECDH reports ECDSA.

Maybe that's what Windows does in these cases, I haven't tested.  It probably needs to be forced by doing something like

```
openssl req -x509 -new -newkey rsa:2048 -nodes -keyout server.key -out server.cer
openssl s_server -accept 9025 -cipher ECDHE-RSA-AES256-SHA384 -key server.key -cert server.cer
```

Then connecting to that endpoint (bypassing the cert validation) and seeing what gets printed.

If I misunderstood, and you think we're matching Windows, that's fine :smile:.

**Comment by ericeil** [comment]
Thanks for the help, @bartonjs.  I tried the following client code, hitting the openssl test server configured as you suggested:

```csharp
            using (var tcpClient = new TcpClient())
            {
                await tcpClient.ConnectAsync("eric-linux", 9025);
                using (var ssl = new SslStream(tcpClient.GetStream(), true, delegate { return true; }))
                {
                    await ssl.AuthenticateAsClientAsync("eric-linux");

                    using (var writer = new StreamWriter(ssl))
                    {
                        writer.WriteLine("Hello this is pretty neato");
                    }
                }
            }
```

I tried this on the desktop CLR, CoreFx/CoreCLR on Windows, and CoreFx/CoreCLR on Ubuntu.  In all three cases, openssl reported:

```
CIPHER is ECDHE-RSA-AES256-SHA384
Secure Renegotiation IS supported
Hello this is pretty neato
```

So apparently this works as-is.

**Comment by ericeil** [comment]
Ok, I'd misunderstood the effect of this issue; the problem really is just that `SslStream.KeyExchangeAlgorithm` reports the wrong value.  This does indeed happen, and I'll submit a PR to fix it.
