### ISSUE TITLE
Implement IEquatable interface on System.Drawing structs

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#5255]
This requires changes to the .NET Full Framework code as well, changes to .NET Core to be made after following up with the desktop release cycles to ensure no breaks happen.

Follow up from PR #1563 

# Motivation
These structures all have equality operators, they should also implement the IEquatable interface.

# Proposed API

``` C#
namespace System.Drawing
{
    public struct Color : IEquatable<Color>
    {
        public bool Equals(Color other);
    }
    public struct Point : IEquatable<Point>
    {
        public bool Equals(Point other);
    }
    public struct PointF : IEquatable<PointF>
    {
        public bool Equals(PointF other);
    }
    public struct Rectangle : IEquatable<Rectangle>
    {
        public bool Equals(Rectangle other);
    }
    public struct RectangleF : IEquatable<RectangleF>
    {
        public bool Equals(RectangleF other);
    }
    public struct Size : IEquatable<Size>
    {
        public bool Equals(Size other);
    }
    public struct SizeF : IEquatable<SizeF>
    {
        public bool Equals(SizeF other);
    }
}
```

**Comment by karelz** [comment]
Should be simple. We do not see any reason why not to do it, but if someone grabs it, we would first do quick API review.

**Comment by JonHanna** [comment]
I'll grab this. The API additions would be:
```C#
namespace System.Drawing
{
    public struct Color : IEquatable<Color>
    {
        public bool Equals(Color other);
    }
    public struct Point : IEquatable<Point>
    {
        public bool Equals(Point other);
    }
    public struct PointF : IEquatable<PointF>
    {
        public bool Equals(PointF other);
    }
    public struct Rectangle : IEquatable<Rectangle>
    {
        public bool Equals(Rectangle other);
    }
    public struct RectangleF : IEquatable<RectangleF>
    {
        public bool Equals(RectangleF other);
    }
    public struct Size : IEquatable<Size>
    {
        public bool Equals(Size other);
    }
    public struct SizeF : IEquatable<SizeF>
    {
        public bool Equals(SizeF other);
    }
}

**Comment by JonHanna** [comment]
It's worth noting that it's a compile breaking change to provide some of these due to implicit cast operators. E.g. if we do this to `RectangleF` then calling Equals on it with a Rectangle will cast the argument to RectangleF and then may return true, where currently any rectangle passed would always return false.
This also means that the `Equals(object)` override would return different results, unless changed to match, which would be surprising.

**Comment by karelz** [comment]
@alexperovich can you please check the proposal when you get a chance?

**Comment by alexperovich** [comment]
The api looks good to me. I don't think the breaking change is a big problem.

**Comment by karelz** [comment]
@alexperovich please update the top post with final API proposal - API shape, motivation, examples, etc.

**Comment by karelz** [comment]
API review: We already have operator ==, so it makes sense to add `IEquatable<T>`.
Value: Generic constraints `T : IEquatable<T>`.
Approved

**Comment by akoeplinger** [comment]
@karelz is there already a process for bringing changes like this to a future .NET Standard version?

**Comment by karelz** [comment]
There's no firm process yet. Being in .NET Standard means that the change has to be also in Desktop and Xamarin - I think that .NET Standard will move as fast as the slowest product. @weshaggard can chime in more ...

**Comment by akoeplinger** [comment]
Sure, the Xamarin side is why I'm asking, don't want us to be the slowest platform 😄

**Comment by karelz** [comment]
My guess is that Desktop will be the long-pole - especially given the compat concerns there, etc.
We track all ports to Desktop via netfx-port-consider. We also discussed today that we should do API diff. The behavioral changes are the more interesting ones though.

Xamarin can either do the same - look at our netfx-port-consider, and/or do API diff. Or rely on the fact that you plan to reuse the entire CoreFX :)

**Comment by weshaggard** [comment]
As @karelz mentioned we don't have a good process laid out yet. At some point once the netstandard 2.0 work lands we will likely do a diff of what we added in .NET Core and consider them for a new version of netstandard.
