### ISSUE TITLE
Write alternate implementations for GetHashCode System.Drawing float types.

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#5256]
PR: #5223, [comment](https://github.com/dotnet/corefx/pull/5223#discussion_r49156587)

This also requires changes to .NET Full Framework desktop code.

**Comment by JonHanna** [comment]
I would have thought it possible to change the implementation separately to that of Full.

**Comment by Priya91** [comment]
@JonHanna That will result in getting different values on net46 and someother value on other platforms. Usually for hashcodes this may be fine, but generally we don't allow behavior changes among different platforms.

**Comment by JonHanna** [comment]
Does that include forward/backward compatibility? Are they going to have to remain functionally equivalent?

**Comment by mellinoe** [comment]
@weshaggard Do we have strict compatibility requirements around hash codes? Would we need to quirk this for .NET Framework, or is changing this behavior at all a no-go because of compat?

**Comment by nguerrera** [comment]
We should be fully within our rights to change GetHashCode() in .NET Core as long as we do not violate its invariants (i.e. if two objects are equal than they have the same hash code). We have been warning folks for > 10 years about this. See the 'Warning' sections here: https://msdn.microsoft.com/en-us/library/system.object.gethashcode%28v=vs.110%29.aspx

We have the option of leaving the desktop implementation intact so long as it is being updated in place (to be conservative about the impact on those who misuse GetHashCode()) while still making the hash codes bettern in .NET Core.

**Comment by terrajobst** [comment]
I think we should change the implementation, including the .NET Framework. If we detect a major issue, we can consider quirking it.

**Comment by nguerrera** [comment]
Even better. Just saying that even if we decide to leave the desktop alone, we can still change .NET Core.

**Comment by terrajobst** [comment]
Good point. /cc @weshaggard @ericstj

**Comment by weshaggard** [comment]
I'm OK with fixing the GetHashCode here and considering this for the full framework but I'm not convince it has enough value to bring there, but I would be OK trying to do it if we think we can do it without breaking anyone.
