### ISSUE TITLE
Dictionary<TKey, TValue> class should allow to use a custom load factor

### ISSUE THREAD

**Issue by horaciojcfilho** [dotnet/corefx#526]
Hello guys,

I had seen the ```Dictionary<TKey, TValue>``` class does not allow the use of a custom ```load factor```, this may allow many optimizations, as the case we want to create a dictionary of known initial size and it will be completely filled, but we don't want that resizing operations occurs, for example it would be possible setting the ```load factor``` to ```1.0F```.

The class constructors below may be added:
```csharp
public Dictionary(int capacity, float loadFactor);
public Dictionary(int capacity, float loadFactor, IEqualityComparer<TKey> comparer)
```
Simirlarly to ```Java```'s ```HashMap<K, V>``` class constructor:
```java
public HashMap(int initialCapacity, float loadFactor);
```

When the ```load factor``` is not known, it should take a default value, for example ```0.75F```.

Thanks a lot :smile: and excuse me for any inconvenience.

**Comment by weshaggard** [comment]
The API looks fine; however, looking at our implementation it seems we don't have an internal concept of load factor. So this is less of an API request but mostly a request to change our implementation to support the notion of a load factor.

I think we'd need a fairly common reason to see whether we can support this concept without bloating the instance size or making operations slower. We currently don't see the benefits but we would be happy to see a PR with a proposal to how you would implement this with some performance benchmarks.

**Comment by karelz** [comment]
Seems to be ready for closure, feel free to reopen if you disagree.
