### ISSUE TITLE
System.Net.Http.HttpRequestException does not have a deserialization constructor

### ISSUE THREAD

**Issue by akoshelev** [dotnet/corefx#5266]
Nor it is marked with ```Serializable``` attribute. Is it by design? 
It seems that full .NET Framework has this type marked with ```ISerializable``` but a deserialization constructor is also missing there.

**Comment by davidsh** [comment]
cc: @weshaggard @ericstj @stephentoub 

.NET Core (CoreFx) does not support binary serialization/serialization.

We don't plan to add any other serialization of these Http types.
