### ISSUE TITLE
ResourceManager.GetObject not defined

### ISSUE THREAD

**Issue by Kagamine** [dotnet/corefx#5271]
Where is in ResourceManager.GetObject in dotnet5.4 platform?

**Comment by ramarag** [comment]
It was cut from .net core, please use the [http://dotnetstatus.azurewebsites.net/](http://dotnetstatus.azurewebsites.net/)  to help port your code to .net core

A search on the [site](http://dotnetstatus.azurewebsites.net/fxapi?docId=M%3ASystem.Resources.ResourceManager.GetObject%28System.String%29&__RequestVerificationToken=CfDJ8G2q3eiDRhJNtyri7KT8YkKjYfwyy6t1cbaHXUn9eAl7m1IgmGaxZVORuQkEWW6MnOV8mkcmxlMh0-knCqxyscm-d2F_OCodBSclfPJ0BuUiboIT2pJ3qxB3fQjbpMkLYgPBqJojOCq01HZeIc7SugI) says Recommended changes: Can now only get strings. Use manifest resources for other types of objects

**Comment by lextm** [comment]
See #11532 for an update.
