### ISSUE TITLE
Expression.TypeEquals throws on Nullable<T> parameter.

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#5272]
```C#
Expression value = Expression.Constant(DateTime.MaxValue, typeof(DateTime?));		
var param = Expression.Parameter(value.Type);

Func<bool> func = Expression.Lambda<Func<bool>>(
	Expression.Block(
		new[] { param },
		Expression.Assign(param, value),
		Expression.TypeEqual(param, typeof(object))
	)
).Compile();
```

The above throws `InvalidOperationException` on the `Compile()` with both compilation options. This happens for any type for the `type` parameter except for the actual nullable type of the parameter which correctly returns `false` if the value of `value` is null and `true` otherwise. This includes the related non-nullable type (should return the same as with the nullable type).

**Comment by JonHanna** [comment]
CC: @VSadov @bartdesmet

**Comment by bartdesmet** [comment]
Good find; definitely undesired behavior. Out of curiosity, what's triggering the `InvalidOperationException`? Do you have the stack trace handy?

**Comment by JonHanna** [comment]
@bartdesmet It happens in `ReduceTypeEqual()`.

The logic primarily turns on the type of the `expression` argument. First non-nullable value-types are dealt with. Then constant expressions. Then sealed types (including the remaining nullable value-types) when the type of the expression matches that of the type argument.

This stage introduces the first of two logical errors: The types have to match exactly to be considered here, when with nullable types the logic should be the same as long as the equivalent non-nullable types match (`((int?)3) is int` and `((int?)3) is int?` but we only consider `((int?)3) is int?`).

Then remaining cases are handled by using a `BlockExpression` with a parameter to ensure the expression is implemented only once. The handling of this case includes a null-check by using `ReferenceNotEqual`. Because `ReferenceNotEqual` will throw `InvalidOperationException` value-types are boxed using `Expression.Convert` first.

However, expressions that are already parameters are passed straight to the `ByValParameterTypeEqual` as we don't need to create a parameter-using expression when already using a parameter, but this happens even when the boxing, which is the second logical error.

The result is that a parameter expression with a nullable value type is reduced to an expression that includes `Expression.ReferenceNotEqual` which is not valid for a value type, and hence the validation on that call throws `InvalidOperationException`. (Aside: Should that be an `ArgumentException`?).

#5273 fixes the first error and adds handling at that point to all sealed types that aren't nullable value types. This fixes the second error, and also results in a lighter reduced form for some other cases. I added a check on sealed types for the type compared to after that to optimise those cases since any remaining cases must result in false.

I'm pretty sure this makes the boxing branch completely unnecessary and unreachable, but I'd rather wait until #5279 is in before removing it, as I don't like removing branches as unreachable without good coverage of all the relevant cases unless they're really obvious, and if this was really obvious we wouldn't have this bug.

**Comment by JonHanna** [comment]
This issue is open again, since the fix to it had to be reverted.
