### ISSUE TITLE
Unit test for DriveInfo.Set_VolumeLabel fails in non-elevated process

### ISSUE THREAD

**Issue by eatdrinksleepcode** [dotnet/corefx#528]
If the unit tests are executed in a non-elevated process (i.e. command prompt or VS not "run as administrator"), the Set_VolumeLabel unit test fails. I think that being able to build and test in a non-elevated process is a worthy goal; and since this is the only test that fails in this case, I think that it should be marked as OuterLoop and not included in the default test run.

**Comment by weshaggard** [comment]
We do have a goal of making sure tests as part of the build should not require admin access. @Priya91 I've assigned this to you please have a look.

**Comment by stephentoub** [comment]
Fixed by #1109
