### ISSUE TITLE
Native assert failed in NetworkInformation on Ubuntu in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5281]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/ubuntu_debug_tst/213/console
```
00:04:32 corerun: /mnt/j/workspace/dotnet_corefx/nativecomp_ubuntu_debug/src/Native/System.Native/pal_networkchange.cpp:66: NetworkChangeKind SystemNative_ReadSingleEvent(int32_t): Assertion `(hdr->nlmsg_flags & 2) == 0' failed.
```

**Comment by mellinoe** [comment]
Interesting. This must be an extremely rare case, I'll have to read more into the documentation around what data is supposed to be sent over that socket.

**Comment by mellinoe** [comment]
Since this has not been recurring and because it's potentially a faulty assertion, I'm going to move this to RTM.

**Comment by stephentoub** [comment]
@mellinoe, @joshfree, should this be moved back to 1.0.0-rtm?  I don't love the idea of shipping with asserts we know have failed without investigating why they failed.
