### ISSUE TITLE
NegotiateStream tests: timeout

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5283]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug_prtest/770/consoleFull
```
05:38:51      System.Net.Security.Tests.NegotiateStreamStreamToStreamTest.NegotiateStream_StreamToStream_Successive_ClientWrite_Sync_Success [FAIL]
05:38:51   Starting:    System.ObjectModel.Tests
05:38:51         Handshake completed in the allotted time
05:38:51         Expected: True
05:38:51         Actual:   False
05:38:51         Stack Trace:
05:38:51            d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Security\tests\FunctionalTests\NegotiateStreamStreamToStreamTest.cs(207,0): at System.Net.Security.Tests.NegotiateStreamStreamToStreamTest.NegotiateStream_StreamToStream_Successive_ClientWrite_Sync_Success()
```

**Comment by stephentoub** [comment]
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug_prtest/791/consoleFull

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_release_prtest/806/consoleFull

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_release_prtest/815/consoleFull

**Comment by CIPop** [comment]
This is similar to #4467.

**Comment by SidharthNabar** [comment]
Moving out of RC2 since this is mostly expected to be a test bug

**Comment by ericeil** [comment]
Failed again: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug_prtest/1889/testReport/junit/System.Net.Security.Tests/SslStreamStreamToStreamTest/SslStream_StreamToStream_Successive_ClientWrite_Sync_Success/

**Comment by CIPop** [comment]
See #4467 for details of this investigation and fix.
