### ISSUE TITLE
"Clean" target removes dependencies

### ISSUE THREAD

**Issue by eatdrinksleepcode** [dotnet/corefx#529]
The "Clean" target of the build script intentionally removes the "src\packages" directory, causing the next build to have to restore them again. This is unnecessary, and atypical compared to most build scripts. "Clean" typically removes the outputs of the build process, not the inputs.

If there is a need for an ability to wipe out the packages directory, I propose putting this functionality under a separate target, "CleanDependencies".

**Comment by sharwell** [comment]
> If there is a need for an ability to wipe out the packages directory, I propose putting this functionality under a separate target, "CleanDependencies".

I would agree with this.

However, I'm also curious if the standard configuration for NuGet 3 will include local caching of NuGet packages, which would mean that following the first restore, the `nuget restore` operation would actually just copy the packages over from the cache and restore them for the solution. If so, this may have been a motivating factor for cleaning the directory.

**Comment by weshaggard** [comment]
I'm going to be looking at some of the packaging restoring targets we have over the coming weeks so I will take this issue under consideration. The reason I added the packages directory to the Clean is because from time to time some of the packages get out of sync and nuget doesn't want to update the correctly. So as a big hammer to deal with that I just deleted them as part of Clean.

**Comment by eatdrinksleepcode** [comment]
@sharwell: Even if Nuget does support a machine-level cache (and it should), I would still not remove the packages directory on clean. Copying the packages locally may be usually cheap, but cheap isn't free, and usually isn't always. Particularly on a build server, where drives aren't always local.

**Comment by sharwell** [comment]
@eatdrinksleepcode That's exactly why I changed my working from "a motivating factor" to "a supporting factor". :smile:

**Comment by eatdrinksleepcode** [comment]
@weshaggard: Fair enough. I probably haven't built enough to notice that problem. Is there anything I can do to help track it down?

**Comment by weshaggard** [comment]
Addressed with #759
