### ISSUE TITLE
Build fails with mulitple errors (Windows 10)

### ISSUE THREAD

**Issue by clrjunkie** [dotnet/corefx#5295]
Attached build log from today
[cfxbuild.txt](https://github.com/dotnet/corefx/files/85708/cfxbuild.txt)

**Comment by stephentoub** [comment]
Dup of:
https://github.com/dotnet/corefx/issues/5299
https://github.com/dotnet/corefx/issues/5297
https://github.com/dotnet/corefx/issues/3610
