### ISSUE TITLE
Corefxlab nuget package version scheme is broken

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefx#5320]
Currently, we use <package><version>.dMMDDYY-N versioning scheme for packages.
This does not work as nuget (and VS) use linguistic sort order of the ".d..." part to determine which version order and so: .d010116 is considered to be older than .d123015

**Comment by weshaggard** [comment]
@KrzysztofCwalina should this issue be filed in corefxlab repo?

**Comment by KrzysztofCwalina** [comment]
my bad. it should be in corefxlab Anyway, it's fixed so I am just closing.
