### ISSUE TITLE
Missing System.Threading.ExecutionContext.IsFlowSuppressed()

### ISSUE THREAD

**Issue by lynxx131** [dotnet/corefx#5330]
Hello,

I am currently looking at porting a library to .NET Core and I have noticed there is no ExecutionContext.IsFlowSuppressed() method. Are there are any plans to implement this on .NET Core or are there any alternatives?

**Comment by kouvel** [comment]
CoreCLR seems to always flows the execution context, and the methods to configure that are currently not available. I'm not aware of any plans to implement flow suppression. IsFlowSuppressed() can be assumed to be false.

Is flow suppression important for your scenario? If so, could you please describe the scenario?

**Comment by lynxx131** [comment]
I was looking at getting https://github.com/Bobris/Nowin working under .NET Core and this was the last visible issue. I will see how it behaves if i assume false.

As this is just an attempt to port a library for mostly curiosity this not necessarily important to my particular scenario but I thought this would be the best place to ask the question and provide visibility for anyone else who may be looking for this information.

**Comment by ericeil** [comment]
Flow suppression was deliberately left out of CoreCLR.  On the full CLR, this is mainly used as a performance optimization, but ExecutionContext flow is cheap enough on CoreCLR that this is probably of little value there.  Since this is a fairly dangerous feature (it breaks any code that assumes state will flow), we should not add it unless there is a compelling reason to do so.

**Comment by lynxx131** [comment]
I eventually got the library working under .NET Core and I believe this issue has answered my question so feel free to close.

**Comment by davidfowl** [comment]
One compelling reason to add it would be to avoid ifdefs in class libraries trying to port. Maybe it just returns false all of the time
