### ISSUE TITLE
CI broken?

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#5331]
The web-view at dotnet-ci.cloudapp.net is unreachable, and the trigger phrases don't seem to be triggering new builds. Is CI down?

**Comment by davidsh** [comment]
Yes, CI is down.  It was supposed to be back a few hours ago but ran into issues.  They are actively working on it.

**Comment by mmitche** [comment]
@JonHanna Yeah, the system died last night during update.  I'm working to bring it back up.

**Comment by JonHanna** [comment]
I closed this after @mmitche's comment about it being worked on, but should probably leave this open until it's back.
