### ISSUE TITLE
Building with MSBuild or Visual Studio on Windows failing

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#5332]
Multiple projects, attempt to run MSBuild receive:

> d:\dotnet\corefxTemp\dir.props(67,3): error MSB4019: The imported project "d:\dotnet\corefxTemp\Tools\Build.Common.prop s" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [d:\d otnet\corefxTemp\src\System.Linq.Queryable\tests\System.Linq.Queryable.Tests.csproj]

Attempt to build in Visual Studio receive:

> The imported project "D:\dotnet\corefx\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00144\lib\Build.Common.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

The problem seems to have been introduced with 3cbbca94331bd78f881903a2fd21edf2ebea4e31, particularly https://github.com/dotnet/corefx/commit/3cbbca94331bd78f881903a2fd21edf2ebea4e31#diff-0b192804a6349e8c26d2b027afbd89a2L52

**Comment by stephentoub** [comment]
@JonHanna, I think you need to first ```build.cmd``` from the root of your repo.

**Comment by ellismg** [comment]
You can also run `init-tools.cmd` instead of building with build.cmd.

@joperezr Can you please update the getting started documents?

**Comment by JonHanna** [comment]
Hmm. Was that something I should have realised? In any case, that's done it.

**Comment by ellismg** [comment]
@JonHanna No, we didn't update the documentation like we should have and the commit message for the change should have contained more detail.  Sorry.

**Comment by JonHanna** [comment]
No worries. That's part of the fun of life on the bleeding edge, as long as it wasn't a case where I should have RTFM'd instead of opening an issue.
