### ISSUE TITLE
Add 'skiptestbuild' command line argument to build script

### ISSUE THREAD

**Issue by clrjunkie** [dotnet/corefx#5333]
Similarly to coreclr build script, please add the option to skip tests to reduce the build time.

**Comment by akoeplinger** [comment]
You can pass `/p:SkipTests=true` to build.cmd for this.

**Comment by clrjunkie** [comment]
Thanks a million!!!

**Comment by weshaggard** [comment]
We have also split up the different types of projects under src so you can build just src\src.builds to get the product or src\tests.builds to get the test projects.

**Comment by clrjunkie** [comment]
@weshaggard  Thanks.
