### ISSUE TITLE
Build fails with mulitple errors on Windows 10 (Jan-12)

### ISSUE THREAD

**Issue by clrjunkie** [dotnet/corefx#5335]
build /t:rebuild /property:Configuration=Debug /p:SkipTests=true

 System.Globalization -> C:\clrjunkie\corefx\bin\ref\System.Globalization\4.0.11.0\System.Globalization.dll
C:\clrjunkie\corefx\src\Common\src\System\StringNormalizationExtensions.cs(17,20): error CS1501: No overload for method
 'IsNormalized' takes 2 arguments [C:\clrjunkie\corefx\src\System.Globalization.Extensions\src\System.Globalization.Ext
ensions.csproj]
C:\clrjunkie\corefx\src\Common\src\System\StringNormalizationExtensions.cs(23,20): error CS1501: No overload for method
 'Normalize' takes 2 arguments [C:\clrjunkie\corefx\src\System.Globalization.Extensions\src\System.Globalization.Extens
ions.csproj]

C:\clrjunkie\corefx\src\Common\src\System\IO\PathInternal.cs(24,30): error CS0117: 'PathInternal' does not contain a de
finition for 'HasIllegalCharacters' [C:\clrjunkie\corefx\src\System.IO.Compression\src\System.IO.Compression.csproj]
System\IO\Compression\ZipArchiveEntry.cs(115,38): error CS0103: The name 'CurrentZipPlatform' does not exist in the cur
rent context [C:\clrjunkie\corefx\src\System.IO.Compression\src\System.IO.Compression.csproj]
System\IO\Compression\ZipArchiveEntry.cs(256,24): error CS0103: The name 'ParseFileName' does not exist in the current
context [C:\clrjunkie\corefx\src\System.IO.Compression\src\System.IO.Compression.csproj]
System\IO\Compression\ZipArchiveEntry.cs(571,32): error CS0103: The name 'CurrentZipPlatform' does not exist in the cur
rent context [C:\clrjunkie\corefx\src\System.IO.Compression\src\System.IO.Compression.csproj]

C:\clrjunkie\corefx\src\Common\src\System\Diagnostics\Debug.cs(45,17): error CS0103: The name 's_logger' does not exist
 in the current context [C:\clrjunkie\corefx\src\System.Diagnostics.Debug\src\System.Diagnostics.Debug.csproj]
C:\clrjunkie\corefx\src\Common\src\System\Diagnostics\Debug.cs(86,13): error CS0103: The name 's_logger' does not exist
 in the current context [C:\clrjunkie\corefx\src\System.Diagnostics.Debug\src\System.Diagnostics.Debug.csproj]
 
 
 C:\clrjunkie\corefx\Tools\Packaging.targets(460,5): error : File C:\clrjunkie\corefx\bin\Windows_NT.AnyCPU.Debug\System
.Security.Cryptography.Algorithms\net46\System.Security.Cryptography.Algorithms.dll does not exist, ensure you have bui
lt libraries before building the package. [C:\clrjunkie\corefx\src\System.Security.Cryptography.Algorithms\pkg\System.S
ecurity.Cryptography.Algorithms.pkgproj]
C:\clrjunkie\corefx\Tools\Packaging.targets(460,5): error : File C:\clrjunkie\corefx\bin\Windows_NT.AnyCPU.Debug\System
.Security.Cryptography.Algorithms\net46\System.Security.Cryptography.Algorithms.dll does not exist, ensure you have bui
lt libraries before building the package. [C:\clrjunkie\corefx\src\System.Security.Cryptography.Algorithms\pkg\System.S
ecurity.Cryptography.Algorithms.pkgproj]
C:\clrjunkie\corefx\Tools\Packaging.targets(897,5): error : Error when creating nuget package from C:\clrjunkie\corefx\
bin\pkg\specs\System.Security.Cryptography.Algorithms.nuspec. System.IO.DirectoryNotFoundException: Could not find a pa
rt of the path 'C:\clrjunkie\corefx\bin\Windows_NT.AnyCPU.Debug\System.Security.Cryptography.Algorithms\net46'.\r [C:\c
lrjunkie\corefx\src\System.Security.Cryptography.Algorithms\pkg\System.Security.Cryptography.Algorithms.pkgproj]
C:\clrjunkie\corefx\Tools\Packaging.targets(897,5): error :    at System.IO.__Error.WinIOError(Int32 errorCode, String
maybeFullPath)\r [C:\clrjunkie\corefx\src\System.Security.Cryptography.Algorithms\pkg\System.Security.Cryptography.Algo
rithms.pkgproj]
C:\clrjunkie\corefx\Tools\Packaging.targets(897,5): error :    at System.IO.FileSystemEnumerableIterator`1.CommonInit()
\r [C:\clrjunkie\corefx\src\System.Security.Cryptography.Algorithms\pkg\System.Security.Cryptography.Algorithms.pkgproj
]
C:\clrjunkie\corefx\Tools\Packaging.targets(897,5): error :    at System.IO.FileSystemEnumerableIterator`1..ctor(String
 path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, B
oolean checkHost)\r [C:\clrjunkie\corefx\src\System.Security.Cryptography.Algorithms\pkg\System.Security.Cryptography.A
lgorithms.pkgproj]
C:\clrjunkie\corefx\Tools\Packaging.targets(897,5): error :    at System.IO.Directory.GetFiles(String path, String sear
chPattern, SearchOption searchOption)\r [C:\clrjunkie\corefx\src\System.Security.Cryptography.Algorithms\pkg\System.Sec
urity.Cryptography.Algorithms.pkgproj]
C:\clrjunkie\corefx\Tools\Packaging.targets(897,5): error :    at NuGet.PathResolver.PerformWildcardSearchInternal(Stri
ng basePath, String searchPath, Boolean includeEmptyDirectories, String& normalizedBasePath)\r [C:\clrjunkie\corefx\src
\System.Security.Cryptography.Algorithms\pkg\System.Security.Cryptography.Algorithms.pkgproj]
C:\clrjunkie\corefx\Tools\Packaging.targets(897,5): error :    at NuGet.PathResolver.ResolveSearchPattern(String basePa
th, String searchPath, String targetPath, Boolean includeEmptyDirectories)\r [C:\clrjunkie\corefx\src\System.Security.C
ryptography.Algorithms\pkg\System.Security.Cryptography.Algorithms.pkgproj]
C:\clrjunkie\corefx\Tools\Packaging.targets(897,5): error :    at NuGet.PackageBuilder.AddFiles(String basePath, String
 source, String destination, String exclude)\r [C:\clrjunkie\corefx\src\System.Security.Cryptography.Algorithms\pkg\Sys
tem.Security.Cryptography.Algorithms.pkgproj]
C:\clrjunkie\corefx\Tools\Packaging.targets(897,5): error :    at NuGet.PackageBuilder.PopulateFiles(String basePath, I
Enumerable`1 files)\r [C:\clrjunkie\corefx\src\System.Security.Cryptography.Algorithms\pkg\System.Security.Cryptography
.Algorithms.pkgproj]
C:\clrjunkie\corefx\Tools\Packaging.targets(897,5): error :    at NuGet.PackageBuilder.ReadManifest(Stream stream, Stri
ng basePath, IPropertyProvider propertyProvider)\r [C:\clrjunkie\corefx\src\System.Security.Cryptography.Algorithms\pkg
\System.Security.Cryptography.Algorithms.pkgproj]
C:\clrjunkie\corefx\Tools\Packaging.targets(897,5): error :    at NuGet.PackageBuilder..ctor(String path, String basePa
th, IPropertyProvider propertyProvider, Boolean includeEmptyDirectories)\r [C:\clrjunkie\corefx\src\System.Security.Cry
ptography.Algorithms\pkg\System.Security.Cryptography.Algorithms.pkgproj]
C:\clrjunkie\corefx\Tools\Packaging.targets(897,5): error :    at Microsoft.DotNet.Build.Tasks.Packaging.NuGetPack.Exec
ute() [C:\clrjunkie\corefx\src\System.Security.Cryptography.Algorithms\pkg\System.Security.Cryptography.Algorithms.pkgp
roj]

    6 Warning(s)
    11 Error(s)
Time Elapsed 00:33:47.81
Build Exit Code = 1

**Comment by stephentoub** [comment]
@clrjunkie, you need to do ```/p:ConfigurationGroup=Debug``` rather than ```/p:Configuration=Debug```.  Not all projects have a "Debug" configuration, due to including different files based on which platform is being targeted.  Setting ConfigurationGroup to Debug tells it to use the relevant debug settings for the appropriate platform.

**Comment by clrjunkie** [comment]
Good to know.. but why is it arranged like that? Why doesnt platform sepecific gode placed in an ifdef thats wrapped by a partial class file, named after the platform? As far as I recall VS knows how to turn ifdefs blocks on and off but it doesnt know how to load or unload files based on a build configuration which makes it impossible to go to defenition and navigate the source accross different configurations (e.g platforms)

**Comment by weshaggard** [comment]
@clrjunkie see https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/project-guidelines.md. Hopefully that helps explain some of the reasoning. However in order to give VS the ability to build our projects with many configurations we are encoding OS/Config/Target into our Configuration property. So when you specify Configuration=Debug you are essentially trying to build everything for Conf=Debug, OS=AnyOS, Target=Default, which not all our projects support which is why you get some projects failing to build.

**Comment by clrjunkie** [comment]
@weshaggard

Just looked at this again, I noticed that VS actually *does* "activate" the right files per build configuration.. without needing to #ifdef.. cool :) Is this new? Can you assign files to build configs directly from VS or this can only done by manually editing the csproj file? 

I read the guidelines and looked at a cross platform csproj.  I understand what you mean.

This will actually make it much easier to load multiple corefx projects to navigate the source across different platforms.

**Comment by weshaggard** [comment]
I don't believe VS allows you to put files into particular configurations in the UI, but I've never really tried to see what happens. Even if it did it would put in for the full Configuration which in most cases we want it for only one part of the Configuration (i.e. OS, Target, etc), so we mostly have to do that manually.

**Comment by clrjunkie** [comment]
@weshaggard Yes I figured... Thanks.
