### ISSUE TITLE
TypeConverter lookup does uncached reflection on CoreCLR

### ISSUE THREAD

**Issue by rynowak** [dotnet/corefx#5337]
We're making fairly frequent use of `TypeConverter` in ASP.NET MVC. Traditionally, it's been a point of extensibility in our system for enabling serialization of your types to and from strings in query string and form data. We also rely on the built in converters for commonly used built-in types like `DateTime`.

On CoreCLR the lookup of a `TypeConverter` is doing a bunch of attribute work up and down the inheritance hierarchy before falling back to a lookup table. On Desktop CLR this is cached in the common case. 

The performance effect on MVC of all of this attribute lookup is quite large. This is sampling data from an app doing model binding on 3 fields and then displaying them in an HTML form. Two of these fields use `TypeConverter` as shown here in the profile. Percentages here reflect % of CPU time inside of routing/MVC:
![image](https://cloud.githubusercontent.com/assets/1430011/12270760/8902d09c-b90c-11e5-84f3-749c02cc57a6.png)

**Is this something we could work to address inside CoreFx?**

**Or should we implement our own cache?**

This is caching we've never had a need to do on Desktop.

**Comment by stephentoub** [comment]
@weshaggard. @joshfree, do you you know why this change for corefx?  Without knowing more, it seems much preferable to put back the caching in corefx, given that the full framework provides it and it's apparently quite impactful to ASP.NET.

**Comment by rynowak** [comment]
I recall pretty early on that the decision was made to port `TypeConverter`, but not the rest of `TypeDescriptor`. In fact in `dotnet` TFM the only surface area `TypeDescriptor` has is:

```
public static TypeConverter GetConverter(Type type);
```

I mention this because the caching on desktop appears to be just an implementation detail of the default type descriptor.

**Comment by joshfree** [comment]
@Tanya-Solyanik can you please take a look?

**Comment by joshfree** [comment]
@ianhays is going to help out and load balance here

**Comment by ianhays** [comment]
Added caching of known TypeConverters in #5626 and added perf tests to go along with them. Speedup is around 25x-40x for repeated calls to GetConverter so that should adequately resolve this issue.
