### ISSUE TITLE
Port and commit type-name parsing tests

### ISSUE THREAD

**Issue by davkean** [dotnet/corefx#534]
@nguerrera just committed vnext of the metadata reader (https://github.com/nguerrera/corefx/tree/mdreader-vnext) with the new signature and attribute parsing support. We need to port the Reflection-style type-naming parsing tests to XUnit and check them in.

**Comment by ellismg** [comment]
@davkean My guess is that you're going to do this work and it entails taking existing internal tests and making them open source.  If you're not going to do the work, can you please assign it to someone else?

**Comment by nguerrera** [comment]
Fixed by #3517
