### ISSUE TITLE
Process.Start isn't properly handling escape characters

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5348]
e.g. the string ```"\\" "\\\\"``` is getting parsed as ```\” \\\”``` rather than as ```\ \\```

**Comment by brthor** [comment]
Note I am seeing this issue on Ubuntu.

I wrote some code to compare results (by forwarding args through different processes) on Windows and Linux, and have shared some of the failing test cases below.

I'm not sure what our story for this is, but should the results on Windows/Linux be consistent here? I found the rules Windows seems to follow here: https://msdn.microsoft.com/en-us/library/17w5ykft.aspx

Argument String                                    |        string[] args (Windows)                  |   string[] args (Windows)                          |                                                Different
---------------------------------------------------|        -----------------------------------------|   -------------------------------------------------|                                                ---------------------
a"b c"d                                            |        [<ab cd>]                                |   [<ab cd>]                                        |
"\\" "\\\\" "\\\\\\" "\\\\\\\\" "\\\\\\\\\\" "\\\\\|        [<\>, <\\>, <\\\>, <\\\\>, <\\\\\>, <\\\\|   [<\" \\\">, <\\\\\" \\\\\\\">, <\\\\\\\\\" \\\\\\|                                                X
\" \\"\\\                                          |        [<">, <\\\\>]                            |   [<">, <\"\\\>]                                   |                                                X
"\a\" \\"\\\                                       |        [<\a" \\\\>]                             |   [<\a" \"\\\>]                                    |                                                X
a\\\"b                                             |        [<a\"b>]                                 |   [<a\\"b>]                                        |                                                X
a\\\\"b c                                          |        [<a\\b c>, ]                             |   [<a\\\"b>, <c>]                                  |                                                X
