### ISSUE TITLE
Add Ubuntu 15.10 (Wily Werewolf) CI / Rolling Build

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#5349]
In preparation for Ubuntu 16.04LTS shipping in April, we should start running on Ubuntu 15.10 as a temporary surrogate.

We can then drop 15.10 when we add 16.04LTS later this year.

https://wiki.ubuntu.com/Releases

Related CI work items: https://github.com/dotnet/corefx/issues/4653 (2008 R2 ServerCore), https://github.com/dotnet/corefx/issues/4656 (Debian 8.2), https://github.com/dotnet/corefx/issues/4779 (2016 NanoServer)

**Comment by bartonjs** [comment]
@ellismg I'm sure you're already aware, but 14.04 is libicu52, and 15.10 looks like it's libicu55, so we might need some clever packaging/building for System.Globalization.Native.so

**Comment by ellismg** [comment]
Yeah, we have the same problem between CentOS and Ubuntu.  The RIDs have version numbers in them so we can pivot our runtime packages that way.

**Comment by joshfree** [comment]
@ellismg is there anything left to do here other than update the badges?

**Comment by ellismg** [comment]
@joshfree I looked at the runs and a few of the globalization tests are failing because of data updates on a newer ICU.  I will update the tests and the badges concurrently.

**Comment by ellismg** [comment]
Done.

**Comment by atrauzzi** [comment]
Will there be any updates to install instructions for people who want to run on 15.10 (or future current non-LTS releases)?
