### ISSUE TITLE
"System.Data.SqlClient" tfms not aligned with "runtime.unix.S.D.S"

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/corefx#5359]
System.Data.SqlClient supports `dotnet5.4` but its `runtime.unix.System.Data.SqlClient` requires `dotnet5.5`. This leads to runtime errors due to missing dependencies on Linux/OSX.

Example:
```json
{
	"frameworks": { 
		"dotnet5.4": { 
			"dependencies": {
				"System.Data.SqlClient": "4.0.0-*"
			}
		}
	}
}
```
:white_check_mark: dotnet restore
:x: dotnet run `Could not load file or assembly 'System.Net.Security'`

Change to `dotnet5.5` 
:white_check_mark: dotnet restore
:white_check_mark: dotnet run

**Comment by ericstj** [comment]
/cc @saurabh500 
Looks like this was simply an inconsistency that didn't get cleaned up.  At one point the System.Net contracts that SqlClient dependended on weren't supported on 5.4, now they are.

**Comment by ericstj** [comment]
Also on Windows this is still packaged as 'dnxcore50'.
