### ISSUE TITLE
AggregateException should report better error messages

### ISSUE THREAD

**Issue by yishaigalatzer** [dotnet/corefx#5364]
A common issue when not using await is the print out ex.Message or ex.ToString()

In the case of `AggregateException` and perhaps also `TargetInvocationException` these messages are kinda useless: `One or more errors occurred.` it would be nice to print out a more detailed message by default:
1. Print out how many error where found.
2. Print out the actual inner exceptions

**Comment by stephentoub** [comment]
AggregateException.ToString() does print out all of the inner exceptions:
https://github.com/dotnet/coreclr/blob/bc146608854d1db9cdbcc0b08029a87754e12b49/src/mscorlib/src/System/AggregateException.cs#L438-L451

**Comment by yishaigalatzer** [comment]
But not in the message. I'll strike out the tostring from the suggestion.

**Comment by stephentoub** [comment]
Thanks. Can you provide more details on the behavior you expect from Message? e.g.
- AggregateException has ctors that allow a message to be provided; what are you recommending in that case?  
- What are you recommending the case where no message is provided, concatenate the messages in some form of all of the inner exceptions?  
- What's the value of augmenting Message in this manner when ToString() provides the full set of ToStrings from the inner exceptions.  Why not just call ToString if that's actually what you want?

**Comment by vScottLouvau** [comment]
+1 for at least taking the InnerException.Message when there's actually only one inner exception, or taking it wrapped within a format string ("One aggregated exception occurred: {0}").

I can't say how many times I've written a catch block to unwrap the one exception in an AggregateException when there's only one so that I can see what the issue really was. I prefer Message to ToString in cases because the stacks are usually long - the message is enough to tell me what's happening without bloating any logging too much.

**Comment by yishaigalatzer** [comment]
We ended up having to write something like this (in one of my previous projects @vScottLouvau wink wink) and unify a helper across the whole codebase. Would be much nicer if the message was meaningful

```c#
       public static string GetExceptionMessageForDisplay(this Exception exception)
        {
            if (exception == null)
            {
                throw new ArgumentNullException("exception");
            }

            string message = exception.Message;

            var aggregate = exception as AggregateException;

            if (aggregate != null)
            {
                var flat = aggregate.Flatten();

                if (flat.InnerExceptions.Count == 1)
                {
                    // recalling as we potentially can have a targetinvocationexception
                    message = GetExceptionMessageForDisplay(flat.InnerException);
                }
                else if (flat.InnerExceptions.Count > 0)
                {
                    var bldr = new StringBuilder();

                    bldr.AppendLine(Core.Resources.MultipleErrors);

                    foreach (var innerEx in flat.InnerExceptions)
                    {
                        bldr.AppendLine(GetExceptionMessageForDisplay(innerEx));
                    }

                    message = bldr.ToString();
                }
                else
                {
                    Debug.Fail("Aggregate exception with no internal exceptions");
                }
            }
            else
            {
                var targetInvocationEx = exception as TargetInvocationException;

                if (targetInvocationEx != null && targetInvocationEx.InnerException != null)
                {
                    message = GetExceptionMessageForDisplay(targetInvocationEx.InnerException);
                }
            }

            return message;
        }
```

**Comment by yishaigalatzer** [comment]
@stephentoub to answer your specific questions:

Thanks. Can you provide more details on the behavior you expect from Message? e.g.
> •	AggregateException has ctors that allow a message to be provided; what are you recommending in that case?

Typically I don't throw them, and if the user sets them, I guess he expects them to come out. It is really a question of what the Task family of classes are doing. You could add a virtual method that get the default message

> •	What are you recommending the case where no message is provided, concatenate the messages in some form of all of the inner exceptions?

See what @vScottLouvau is suggesting, we can debate the actual English around it, but that is the idea. See what we did in our code above

> •	What's the value of augmenting Message in this manner when ToString() provides the full set of ToStrings from the inner exceptions. Why not just call ToString if that's actually what you want?

.ToString() is not user friendly enough, even developers don't want to see callstacks pop-up. So it is not appropriate to show in a user message. It is good for debugging, so it will go in logs, traces or for advanced users.

**Comment by stephentoub** [comment]
Ok, that's reasonable.  And from looking at other exception implementations in the framework, it's fairly common for Message to tack on additional information onto whatever message the user supplied, if any.  I'll put a PR together.  I don't want it to be particularly complicated / have lots of policy (e.g. I don't think it should do any special handling for flattening various nested exception types, other than what will recursively happen automatically), but having a basic implementation where the Message includes the messages from the inner exceptions seems reasonable, similar to ToString but without the stacks.
