### ISSUE TITLE
Consider adding TypeDefinition.IsNested { get; }

### ISSUE THREAD

**Issue by vScottLouvau** [dotnet/corefx#5377]
I'm testing https://github.com/dotnet/corefx/pull/4809/files. DisassemblingTypeProvider, the sample implementation used for tests, calls TypeDefinition.Attributes.IsNested in GetTypeFromDefinition, which can't be done outside Roslyn.

I'm guessing we'll want everything the reference implementation does be possible for public consumers to do.

**Comment by vScottLouvau** [comment]
Tagging @nguerrera so he sees this one.

**Comment by tmat** [comment]
Easy to workaround: see https://source.dot.net/#System.Reflection.Metadata/System/Reflection/System.Reflection.cs,227. 
We can consider adding TypeDefinition.IsNested { get; }.

**Comment by karelz** [comment]
This looks very simple. We need someone to implement it. @vScottLouvau do you want to grab it?

cc: @terrajobst @weshaggard we approved the (super-simpler) API with @tmat and @nguerrera, please let us know if you disagree.

**Comment by danmosemsft** [comment]
@MaggieTsang @niustephanie @nchikanov this is up for grabs, if one of you would like to take it, please assign to yourself.

**Comment by karelz** [comment]
Thanks @kassemsandarusi for your contribution! I have sent you collaborator invite - that will allow us to assign this issue to you (GitHub limitation). Assigning the issue to myself temporarily, once you accept, please ping me here and I will reassign it to you.
Pro-tip: GitHub will automatically subscribe you to all repo notifications (500+/day). We recommend people to switch to notifications where you're mentioned.

**Comment by kassemsandarusi** [comment]
@karelz Accepted.
