### ISSUE TITLE
Process.Start() sometimes returns wrong ProcessName

### ISSUE THREAD

**Issue by palladia** [dotnet/corefx#5378]
If executing following code with NETStandard.Library of 1.0.0-rc2-23712:

using System;
using System.Diagnostics;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            for (int i=0; i<100; i++)
            {
                ProcessStartInfo startInfo = new ProcessStartInfo();
                startInfo.FileName = "ping";
                startInfo.Arguments = "localhost -c 1";

                Process process = new Process();
                process.StartInfo = startInfo;
                process.Start();

                Console.WriteLine("processName is: {0}", process.ProcessName);
            }
        }
    }
}

You will see that output ProcessName is usually correct ("ping") the first time, but usually incorrect in subsequent iterations.

If one extends the life of command (change argument to something like "-c 3"), wait a second or so, and then do a "GetProcessById", you would see that the ProcessName has become correct.  This indicates a race condition of some sort.

**Comment by pallavit** [comment]
@palladia When I try to run the repro I always get System.InvalidOperationException : Process has exited, so the requested information is not available. 

My guess is what you are seeing is not a race condition but that the process is already exiting. That is the reason why when you use another option that increases the process running time, you see the expected o/p.

**Comment by palladia** [comment]
No, the initial process.ProcessName is usually wrong.  When I said wait a second, it's kind of like this:

process.Start();
Console.WriteLine(process.ProcessName);       // usually wrong value

Process secondValue = Process.GetProcessById(process.Id);
Console.WriteLine(secondValue.ProcessName);   // still wrong value

// wait one second

Process secondValue = Process.GetProcessById(process.Id);
Console.WriteLine(secondValue.ProcessName);   // now correct value

Not sure why your command is exiting so quickly.  If you want to make sure your command lasts, you can try increase the ping parameter to "-c 4" or something like that.  That will ping 4 times, and your process shouldn't exit quickly.  I set it to "-c 1" so you wouldn't be cluttered with ping messages.

I've also repro'ed this with other long-running commands.  For example, you can try starting "emacs" instead.

**Comment by andschwa** [comment]
@palladia What OS was this on?

**Comment by palladia** [comment]
$ uname -a
Linux george-vm-1 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by andschwa** [comment]
Interestingly, we're seeing that the `Id` is correct (and sequential, as expected), but the `ProcessName` is not correct:

``` c#
using System;
using System.Diagnostics;

namespace Repro
{
    public static class Program
    {
        public static void Main()
        {
            for (int i=0; i<100; i++)
            {
                ProcessStartInfo startInfo = new ProcessStartInfo();
                startInfo.FileName = "ping";
                startInfo.Arguments = "localhost -c 10";

                Process process = Process.Start(startInfo);

                Console.WriteLine($"info: {process.ProcessName} {process.Id}");
            }
        }
    }
}
```

```sh
./bin/console-repro | grep info
info: ping 11836
info: console-repro 11837
info: console-repro 11838
info: console-repro 11839
info: console-repro 11840
info: console-repro 11841
info: console-repro 11842
info: console-repro 11843
info: console-repro 11844
info: console-repro 11845
info: console-repro 11846
info: console-repro 11847
info: console-repro 11848
info: console-repro 11849
info: console-repro 11850
info: console-repro 11851
info: console-repro 11852
info: console-repro 11853
info: console-repro 11855
info: console-repro 11856
info: console-repro 11857
info: console-repro 11858
info: console-repro 11859
info: console-repro 11860
info: console-repro 11861
info: console-repro 11862
info: console-repro 11863
info: console-repro 11864
info: console-repro 11865
info: console-repro 11866
info: console-repro 11867
info: console-repro 11868
info: console-repro 11869
info: console-repro 11870
info: console-repro 11871
info: console-repro 11872
info: console-repro 11873
info: console-repro 11874
info: console-repro 11875
info: console-repro 11876
info: console-repro 11877
info: console-repro 11878
info: console-repro 11879
info: console-repro 11880
info: console-repro 11881
info: console-repro 11882
info: console-repro 11883
info: console-repro 11884
info: console-repro 11885
info: console-repro 11886
info: console-repro 11887
info: console-repro 11888
info: console-repro 11889
info: console-repro 11890
info: console-repro 11891
info: console-repro 11892
info: console-repro 11893
info: console-repro 11894
info: console-repro 11895
info: console-repro 11896
info: console-repro 11897
info: console-repro 11898
info: console-repro 11899
info: console-repro 11900
info: console-repro 11901
info: console-repro 11904
info: console-repro 11905
info: console-repro 11906
info: console-repro 11907
info: console-repro 11908
info: console-repro 11909
info: console-repro 11910
info: console-repro 11911
info: console-repro 11912
info: console-repro 11913
info: console-repro 11914
info: console-repro 11915
info: console-repro 11916
info: console-repro 11917
info: console-repro 11918
info: console-repro 11919
info: console-repro 11920
info: console-repro 11921
info: console-repro 11922
info: console-repro 11923
info: console-repro 11924
info: console-repro 11925
info: console-repro 11926
info: console-repro 11927
info: console-repro 11928
info: console-repro 11929
info: console-repro 11930
info: console-repro 11931
info: console-repro 11932
info: console-repro 11933
info: console-repro 11934
info: console-repro 11935
info: console-repro 11936
info: console-repro 11937
info: console-repro 11938
```

**Comment by stephentoub** [comment]
They're is a race condition, largely inherent to the way processes are spawned on Unix: fork/exec. To create another process, you fork() to create a copy of yourself, and then that copy execs. As such, there is a window of time where the child process has one name (yours) and then it switches. So Process.ProcessName is accurately reflecting reality... it's getting it's data from /proc/pid/stat, which also accurately reports the change on subsequent accesses. I'm not sure there's much to be done about it.

**Comment by stephentoub** [comment]
I may actually have a workaround that would at least work on Linux. I'll try it out today and either submit a PR or close this.

**Comment by palladia** [comment]
If we can get the process Id (of the child process) correct, surely we can get the process name correct as well.  And if that's somehow not possible, we know what the process name should be, can we not force it?

**Comment by stephentoub** [comment]
> If we can get the process Id (of the child process) correct, surely we can get the process name correct as well

It is getting the process name correct, that was my point.  The name of the process actually is "corerun" at that point, so Process.ProcessName is correct even though it's not what you expect it to be.  It doesn't change to "ping" until after the execve call, and there's a race between reading the name and the process getting to the point where it calls execve.  The process ID is handed back by the call to fork(), so that's deterministically always available and correct.  And we don't always know what the process name should be, such as when in your follow-up example you use Process.GetProcessById: we have to ask the system what the name is associated with that process, and we report back what it tells us.

Regardless, my workaround appears to be working fine, so I'll submit a PR for it.

**Comment by palladia** [comment]
Great, thanks!

**Comment by andschwa** [comment]
@stephentoub Would that work-around possibly work on OS X too?

**Comment by stephentoub** [comment]
@andschwa, it was in the general unix implementation, not specific to linux... it should have applied to OS X as well.  You're still seeing this on OS X?  Can you share a repro?

**Comment by andschwa** [comment]
Hmph; yeah one of our tests failed with the exact same thing (of the process name being the host not the launched process itself) on 10.11. I'll have to pull a repro out of the of project though cause NDA. I'm ignoring the failure for now and will put it in our backlog.

**Comment by stephentoub** [comment]
Is it possible the process had already ended by the time you tried to get its name?

**Comment by andschwa** [comment]
It's possible, I will have to take a closer look. I'll let you know when I have more info, thanks @stephentoub.
