### ISSUE TITLE
File.Exist() is case insensitive on Mac

### ISSUE THREAD

**Issue by zhili1208** [dotnet/corefx#5385]
repro step:
1.create a file  "Test.Config".
2.File.exist("test.config") return true on Mac.

here is a test app for this: https://github.com/zhili1208/lzhi-test

**Comment by stephentoub** [comment]
That's correct.  Typically HFS+ is case-insensitive.  While it's possible to configure it to be case-sensitive, that's rare, and we don't currently have any implementation for that.  That's covered by https://github.com/dotnet/corefx/issues/3156.

**Comment by zhili1208** [comment]
I see, thank you
