### ISSUE TITLE
Test fails to verify client.ImpersonationLevel: System.Net.Security.Tests.NegotiateStreamStreamToStreamTest.NegotiateStream_StreamToStream_Authentication_EmptyCredentials_Fails() 

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#5397]
MESSAGE:
Assert.True() Failure\r\nExpected: True\r\nActual: False
+++++++++++++++++++
STACK TRACE:
at System.Net.Security.Tests.NegotiateStreamStreamToStreamTest.NegotiateStream_StreamToStream_Authentication_EmptyCredentials_Fails() in d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Net.Security\tests\FunctionalTests\NegotiateStreamStreamToStreamTest.cs:line 155
This is:
Assert.Equal(TokenImpersonationLevel.Identification, client.ImpersonationLevel);

**Comment by CIPop** [comment]
From #5366 :

> @CIPop Yes we don't run elevated on purpose (sudo isn't the default, it's bad practice, etc.) However we do run outerloop in elevated mode.

@mmitche This is a Windows-only test that started failing recently. Were there any CI changes that could trigger this new behavior? Also I wouldn't expect the behavior to be intermittent unless some CI machines are configured in a different way.

**Comment by mmitche** [comment]
@CIPop the only possibility is that I've spun up some new machines today, and these have Update 1 on them.  There were a couple before, but it's quite possible this test never ran on it.

**Comment by CIPop** [comment]
@mmitche What do you mean by "Update 1"? Visual Studio?
If so, I'm not sure that would be related. I've written the test for .Net Desktop on RS1 + VS Update 1 and ensured that they run the same way on TH2 on a Domain-joined machine logged on as myself without elevation.

Did Windows authentication or the account being used changed somehow? (Maybe was Domain-joined and now it's not?)

**Comment by mmitche** [comment]
@CIPop there is no domain join here, account is the same, etc.  Visual Studio Update 1 is what I am referring to.  We can pull a machine out of rotation to investigate if needed.

**Comment by CIPop** [comment]
> We can pull a machine out of rotation to investigate if needed.

@mmitche Thanks! If we see the test passing on some machines and not others, I'd like to take a look why.

**Comment by CIPop** [comment]
No other reports recorded. Most likely a CI VM config issue.
I wasn't able to repro this issue part of my investigation (#4467 / #7937).
