### ISSUE TITLE
Remove always true "if" and unreachable code in System.Xml.Linq.XObject.SkipNotify method.

### ISSUE THREAD

**Issue by andi9310** [dotnet/corefx#54]
This: if (o.Annotations<XObjectChangeAnnotation>() != null) 
is always true because the above while can finish only in two conditions: when o != null or when o.annotations == null. The first condition will be catched by " if (o == null)" and if the second one is true, "o.Annotations<XObjectChangeAnnotation>() != null" will also always be true i think.

**Comment by IDisposable** [comment]
Carlos's analysis is correct, you cannot write a test to "expose a bug" that can never occur. Rather, this is simple code-path analysis that calls out dead code.

**Comment by davkean** [comment]
Sorry, I should clarify - I agree with the assessment of that the code is dead. However, I do not agree to the removal of said dead code, I would rather see the code changed to follow the spirit of which it was written (which appears to be to raise some Changing/Changed events).

ie My statement is, write some tests that show that these Changing/Changed events do not fire when they are supposed to, and then make the code change to make them fire.

**Comment by sharwell** [comment]
While pull request #55 is a correct interpretation of the original code, I believe the original code did not behave as intended. I believe the original code was meant to read as follows:

```csharp
if (o.Annotations<XObjectChangeAnnotation>().Any()) return false;
```

If the condition was written like this, the meaning of the method would be:

> Skip notify unless the current object or any of its parents includes the `XObjectChangeAnnotation` annotation.

As it was *actually* written, and as #55 preserved, the meaning of the method is:

> Skip notify unless the current object or any of its parents includes any annotation.
