### ISSUE TITLE
Builds files don't handle 'unix' bins correctly

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#5420]
IL libraries in corefx tend to take one of 3 shapes.
1. Single cross-platform library.
2. Windows/Unix library.
3. Windows/Linux/OSX library.

Right now we don't handle 2 correctly in the builds files.  Instead of treating them as OSGroup=Unix and building on both Linux and OSX they use OSGroup=linux and only build on Linux.

/cc @weshaggard @stephentoub

**Comment by weshaggard** [comment]
As part of this I would like to also clean-up unnecessary OSGroup configurations like https://github.com/dotnet/corefx/commit/95efe37475916016a5fc6ee6f0ba584d990c4196#diff-3dbec1fe124acf1d7d5f7d94703c3805R6

**Comment by krytarowski** [comment]
I'm following this ticket.

**Comment by weshaggard** [comment]
We do have support for OSGroup=Unix now but we haven't done a full clean-up of the repo yet, so keeping this item about cleaning up the repo.

**Comment by mellinoe** [comment]
@weshaggard @ericstj What's the status of this one? I think we've cleaned up lots of OS-related stuff, and refactored a bunch on top of that. Is this still a problem?

**Comment by weshaggard** [comment]
There may be some lingering projects that can be optimized but I agree this is pretty much done now.
