### ISSUE TITLE
Ensure error handling is properly checking the last error in Sockets

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5426]
See https://github.com/dotnet/corefx/pull/5419#issuecomment-171752102.

**Comment by CIPop** [comment]
We need to move the Assert checks from Socket.cs to the PAL layer, immediately after the call to Marshal.GetLastWin32Error();  

Example: https://github.com/dotnet/corefx/pull/5419/files#diff-a92dcc50fa7799a1b77b747a99c6222bR3282

**Comment by karelz** [comment]
It is not tracking anything super-useful at this moment. If we have a problem, it is going to surface in test failures or product bugs.

**Comment by stephentoub** [comment]
@karelz, why was this issue closed?  At the very least, there's code that references this issue:
https://github.com/dotnet/corefx/blob/69cd5b28c13c358b1d82c00bf41829d23218e9bf/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L3236
that needs to be deleted if the issue is going to be closed.

**Comment by geoffkizer** [comment]
Should be fixed with #14812.
