### ISSUE TITLE
TcpClient Has some issues on Mac with coreclr

### ISSUE THREAD

**Issue by zhili1208** [dotnet/corefx#5436]
here is a test app: https://github.com/zhili1208/coreclrMacTcpTest

Server side just listens and print incoming string, client side just connect to server and send string.

On Mac, when I start client, it just hang or the string from server is null. only happens with coreclr 1.0.0-rc1-update1, works well on mono.

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by stephentoub** [comment]
@zhili1208, can you try on a newer build, such as one built from the latest source in master?  I just tried your repro on a Linux system using the latest source and it ran fine.  I realize you said this was on a mac, and I'll try that tomorrow.

**Comment by zhili1208** [comment]
@stephentoub it woks well on Linux but for some reason it failed on OSX, I will try a newer build

**Comment by zhili1208** [comment]
latest build works, thank you

**Comment by stephentoub** [comment]
Great!

**Comment by zhili1208** [comment]
Sorry, I just found it passed on mono, when I change the runtime to coreclr, it got same issue again, the coreclr version is 1.0.0-rc1-update1 for darwin-x64

**Comment by stephentoub** [comment]
> the coreclr version is 1.0.0-rc1-update1

But you're using the latest corefx sources?

**Comment by zhili1208** [comment]
Yes, I'm using 4.1.0-rc2-23714

**Comment by stephentoub** [comment]
It looks like the root cause of this is https://github.com/dotnet/corefx/issues/5829.  I'm working on a fix.
