### ISSUE TITLE
Capture the log files in failed CI runs

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#5443]
https://github.com/dotnet/dotnet-ci/blob/8e3c2c86f3b9f6edcd1a1e0aafe8cc8ea5a1cad4/jobs/generation/Utilities.groovy#L379

We currently only capture the log file for jobs when the pass but there are a lot of time we really need to full log for failed jobs. We should see if we can conditionally always archive the log file or find another way to capture the log, even perhaps dumping to the console as part of the CI.

cc @mmitche

**Comment by mmitche** [comment]
I found a way to do this.  Will respond with more details tomorrow.

**Comment by weshaggard** [comment]
@mmitche did you every get this put into place?

**Comment by mmitche** [comment]
@weshaggard nope, but I have limited time.  If you have a resource for this I can teach them how to do it.

**Comment by mellinoe** [comment]
@mmitche Could you share the resource here in case someone would like to invest some time into it? That's assuming this is still a problem and we aren't capturing log files.

**Comment by mmitche** [comment]
We now have a lot more storage available.  I am okay with capturing log files of failed builds.

**Comment by wtgodbe** [comment]
@mmitche is this still actionable?

**Comment by mmitche** [comment]
In corefx, this isn't as applicable any longer since we don't gather logs in the same fashion (pipeline vs. classic jobs).  I don't think we should focus on this.

**Comment by wtgodbe** [comment]
In that case I will close this
