### ISSUE TITLE
Switch to users wide package cache

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#5444]
Today we scope our packages to the repo which gives us isolation but it causes things like CI jobs to always have to download these package every time, which cost time and add extra unnecessary reliability issues. For local devs it also costs in disk space because ever instance of this repo or our sister repo's has their own cache which causes a lot of duplication.

We should find a good user wide cache directory, perhaps just use the default location that nuget/dnu use.

**Comment by ianhays** [comment]
Having the package cache in the same place as other repos would be preferable imo to avoid duplicate packages all over the place. It does complicate the (admittedly narrow) scenario for when you want to manually alter the contents of one of the packages for testing, but that's probably inadvisable anyways.

On my machine, I've got a few package locations:
C:\Users\USERNAME\.nuget\packages
C:\Users\USERNAME\.dnx\packages
D:\git\corefx\packages
D:\git\coreclr\packages
D:\git\buildtools\packages
D:\git\corefxlab\packages

That's a <i>lot</i> of package duplication. :+1: to consolidation where possible.

**Comment by mellinoe** [comment]
> It does complicate the (admittedly narrow) scenario for when you want to manually alter the contents of one of the packages for testing

This is my only concern as well. I guess it's just part of the larger question of "what's the best way to quickly test a change to a nuget package". Doing it could already cause issues if you forget to undo your temporary change, but I usually clean out my packages cache often enough that I've never really hit any weird issues from doing it.

**Comment by mellinoe** [comment]
@weshaggard Do you still believe we should do this? I'm kind of skeptical that it will really be worth it. Download / restore times are still long enough to be annoying, but they aren't really debilitating anymore, at least with a decent connection speed.

**Comment by weshaggard** [comment]
I do still think we should do this to try and help share packages across many repo's. Beyond potential restore performance it also saves a lot of duplicated disk space.

**Comment by karelz** [comment]
@mellinoe we should move it to buildtools - this is cross-repo problem.

**Comment by mellinoe** [comment]
Actually, we're overriding the packages directory in corefx. I suspect most other repos are doing that, too. if we want to use the user cache, we probably just need to remove [this](https://github.com/dotnet/corefx/blob/master/dir.props#L129).

**Comment by weshaggard** [comment]
Correct we would need to remove that in some cases but we also have to decide if we want CI/Official builds to still use an isolated packages folder or use the shared cache folder as well.

**Comment by ViktorHofer** [comment]
+1. Out of Redmond with a "decent" connection speed restoring all the dependencies still takes several minutes. I will assign this to me and tackle it when I have some free cycles.

**Comment by danmosemsft** [comment]
@weshaggard 	is this still active after #31831 and the Arcade work?

**Comment by weshaggard** [comment]
This can be closed now as we use the user wide cache by default but have an option "-ci" to scope it to the repo for our automated builds.
