### ISSUE TITLE
Add third party notices file to packages

### ISSUE THREAD

**Issue by terrajobst** [dotnet/corefx#5446]
The attached file needs to be added to all packages that contain code coming from GitHub (and thus may contained contributions from the .NET Foundation).

[ThirdPartyNotices.txt](https://github.com/dotnet/corefx/files/91263/ThirdPartyNotices.txt)

Please add the file to the root of packages, right next to the `.nuspec` file

**Comment by chcosta** [comment]
Updated notice will appear in the next package push

**Comment by terrajobst** [comment]
Excellent. Thanks!
