### ISSUE TITLE
Add license to NuGet packages

### ISSUE THREAD

**Issue by terrajobst** [dotnet/corefx#5447]
This is related to #5446: we also need to include the EULA. Currently, our packages only have a URL that point to the license. For compliance reasons we also need to include the EULA with the package, so that reading the EULA doesn't require having an internet connection.

I suggest that we add the EULA side by with the .nuspec, as well as the ThirdPartyNotices (#5446).

**Comment by chcosta** [comment]
Do we just want to grab the eula as is and include it in the package?  ie, we would include these two files in every package...

- dotnet_library_license.htm
- ThirdPartyNotices.txt

I'm not certain if we care about having a consistent naming scheme or changing "dotnet_library_license.htm" to "eula.htm" or something else...?

**Comment by chcosta** [comment]
Updated license will appear in the next package push.

**Comment by terrajobst** [comment]
Thanks!
