### ISSUE TITLE
System.Buffers: make sure that arrays are returned

### ISSUE THREAD

**Issue by frblondin** [dotnet/corefx#5451]
After looking at the System.Buffers new package I think that it could become *dangerous* is a code is calling Rent(...) method and doesn't manage properly exception or forgets to call Return(...) in some cases.

So maybe it would be safer to enforce that arrays are being 'released' by using an intermediary class RentedArray<T> (or such) that implements IDisposable.

The code would become
```
using (var rentedArray = XX.Rent(size))
{
      var array = rentedArray.Array; // or rentedArray.Value
      ...
}
```

**Comment by stephentoub** [comment]
Why do you believe it's "dangerous"?  Worst case, the buffer isn't returned, and another one needs to be created by the pool.  There is of course cost to that, but there's also cost to trying to enforce that buffers are always returned, even in the case of exceptions.  Since exceptions in these cases should be relatively rare, it doesn't seem warranted to force such costs upon the common cases.  More related discussion is herE:
https://github.com/dotnet/corefx/pull/5355#discussion_r49539856

You can of course provide your own wrapper around this functionality if you want this for your own code.

**Comment by benaadams** [comment]
All a pattern using the Default/Shared pool that didn't return the buffers would do is be a more expensive way for allocating arrays; they would then get GC'd as normal.

Ofc if you aren't properly returning them then you are loosing out on the benefits; but certainly not in danger. 

Other implementations may vary.

**Comment by frblondin** [comment]
Dangerous was certainly a (too) strong word.

What I meant is that the purpose of this pool is reusing instances. If you aren't returning instances then you will ask the pool to reallocate new arrays until you reach the max size.

The Disposable Using pattern exactly serves the purpose of making sure that when something is started it will be disposed for sure. My feeling is that we exactly need this when we use a pool.

As you said I could easily create my own wrapper but it seems really common that you'll want to make sure that a rented instance is being released. Standard types provided to devs by the .Net Framework should also guide them and make sure that they are doing the proper usage.

Since the package is not made public yet it is probably the right time to do this readjustment if you think it's relevant, as you won't be able to change it in the future (or by adding new methods...).

I'll be more than happy to create a pull request if there would be any chance that it will be merged....?

Side note: in the comment you provided you are talking about internal .Net code written by skilled & expert .Net developers (StringBuilderCache). Remember that the .Net Framework must remain as accessible as possible, even bad programmers :-)

**Comment by stephentoub** [comment]
> I'll be more than happy to create a pull request if there would be any chance that it will be merged....?

The API review process is outlined here:
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md

Personally, as I've stated in other replies, I don't believe we should modify the APIs in that way.  I think doing so is optimizing for cases we in general don't need to optimize for, and in doing so incurring costs for the cases we do.

**Comment by frblondin** [comment]
Closing the request then, as I trust your judgment :-)

**Comment by stephentoub** [comment]
:smile:
