### ISSUE TITLE
Three "unicode" System.IO.Compression.ZipFile tests are failing on Unix

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefx#5459]
We currently have the following tests not running on Unix:

https://github.com/dotnet/corefx/blob/master/src/System.IO.Compression.ZipFile/tests/ZipFileConvenienceMethods.cs#L17
https://github.com/dotnet/corefx/blob/master/src/System.IO.Compression.ZipFile/tests/ZipFileConvenienceMethods.cs#L69
https://github.com/dotnet/corefx/blob/master/src/System.IO.Compression.ZipFile/tests/ZipFileConvenienceMethods.cs#L165

with code like the following:

```C#
if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows)) // [ActiveIssue(846, PlatformID.AnyUnix)] 
{ 
    await TestCreateDirectory(zfolder("unicode"), true); 
} 
```

Since #846 has been closed, we need to investigate these tests and figure out why they aren't passing on Unix.

**Comment by ianhays** [comment]
somewhat a duplicate of #5096
