### ISSUE TITLE
Investigate and fix System.Collections tests marked with ActiveIssue #846

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefx#5460]
Currently there are 6 tests in System.Collections.Tests and System.Collections.NonGeneric.Tests that are marked with ActiveIssue #846, but #846 has been implemented and closed.

We should investigate these tests and find out why they are failing.

https://github.com/dotnet/corefx/blob/c02d33b18398199f6acc17d375dab154e9a1df66/src/System.Collections/tests/Generic/SortedList/Constructor_IDictionary_ComparisonType.cs#L309
https://github.com/dotnet/corefx/blob/c02d33b18398199f6acc17d375dab154e9a1df66/src/System.Collections/tests/Generic/SortedList/Constructor_IDictionary_IKeyComparer.cs#L204
https://github.com/dotnet/corefx/blob/c02d33b18398199f6acc17d375dab154e9a1df66/src/System.Collections/tests/Generic/SortedList/Constructor_IKeyComparer.cs#L178
https://github.com/dotnet/corefx/blob/c02d33b18398199f6acc17d375dab154e9a1df66/src/System.Collections/tests/Generic/SortedList/Constructor_int_ComparisonType.cs#L152
https://github.com/dotnet/corefx/blob/c02d33b18398199f6acc17d375dab154e9a1df66/src/System.Collections/tests/Generic/SortedList/Constructor_int_IKeyComparer.cs#L196
https://github.com/dotnet/corefx/blob/c02d33b18398199f6acc17d375dab154e9a1df66/src/System.Collections.NonGeneric/tests/Comparer/Comparer_CaseInsensitive.cs#L115

**Comment by ianhays** [comment]
Will be resolved alongside #754.

**Comment by ianhays** [comment]
I'm removing these tests. They're not testing collections behavior - they're testing Globalization behavior. We shouldn't try to validate CultureInfo conversions and equality from System.Collections.
