### ISSUE TITLE
Investigate failing System.Globalization.Tests on Unix

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefx#5463]
There are a number of tests under https://github.com/dotnet/corefx/tree/c02d33b18398199f6acc17d375dab154e9a1df66/src/System.Globalization/tests that are disabled against #846.  However, #846 has been implemented and closed.

We should investigate these tests and figure out why they are still failing on Unix.

**Comment by tarekgh** [comment]
@eerhardt I am not seeing test disabled because #846 looks this already fixed. could you confirm if we can close this issue?

**Comment by eerhardt** [comment]
> @eerhardt I am not seeing test disabled against #846 looks this already fixed. could you confirm if we can close this issue?

I removed all references to #846 when I logged these issues.

The tests that need to be investigated are marked with this current issue - #5463.

**Comment by tarekgh** [comment]
cleaned up the test after investigating the cases. all cases are differences between Windows and ICU collation. the linked PR is the test clean up change.
