### ISSUE TITLE
Remove workaround from System.Runtime.Loader package

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#5471]
Related: https://github.com/dotnet/corefx/issues/5406

I updated the generation mapping for DNXCore50 to 5.6 in NuGet.

When our validation task picked up this change it saw that the
minimum generation supported by all platforms is now 5.6.
As a result it produced an error saying that we should update
the reference assembly to 5.6 as well.

The problem is that not everyone consuming this package is
using the latest nuget. 

For now we will workaround this by duplicating the reference
in the dncore50 folder.  This issue is tracking removal of that
workaround.

**Comment by weshaggard** [comment]
Add System.AppContext and System.Diagnostics.Tracing to the list of clean-up.

**Comment by ericstj** [comment]
Fixed with https://github.com/dotnet/corefx/commit/6008326984df7bddff751d0fec678ee29d821a59.
