### ISSUE TITLE
Win7 outer loop builds failing with AVs

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5493]
e.g.
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win7_release/52/console
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win7_release/53/console
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win7_release/51/console
```
22:18:52 Feeds used:
22:18:52     https://www.myget.org/F/dotnet-core/
22:18:52     https://www.myget.org/F/dotnet-buildtools/
22:18:52     https://www.nuget.org/api/v2/
22:18:53 Publishing tool-runtime for DNXCore,Version=v5.0/win7-x64
22:18:55 Compiling tool-runtime for DNXCore,Version=v5.0
22:18:56 
22:18:56 Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
22:18:56    at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
00:18:17 
Build timed out (after 120 minutes). Marking the build as aborted.
00:18:17 
Build was aborted
```

**Comment by weshaggard** [comment]
This looks like it might be an issue with dotnet publish on Win7. @joperezr @piotrpMSFT

**Comment by ellismg** [comment]
The AV is due to https://github.com/dotnet/coreclr/issues/2153.  After that's fixed, there are some errors in init-tools.cmd that also prevent the tools from restoring.  I will submit a PR to fix both.
