### ISSUE TITLE
AssemblyLoadContext broken in build 23714

### ISSUE THREAD

**Issue by andschwa** [dotnet/corefx#5495]
Hello again,

While upgrading to build 23715 from 23712, I encountered this error when building our project that implements the `AssemblyLoadContext`:

```
error CS1069: The type name 'AssemblyLoadContext' could not be found in the namespace 'System.Runtime.Loader'. This type has been forwarded to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' Consider adding a reference to that assembly.
```

23712 and 23713 work, 23714 and 23715 do not.

Relevant `project.json` excerpt:

```json
"dependencies": {
    "NETStandard.Library": "1.0.0-rc2-23715",
    "System.Runtime.Loader": "4.0.0-rc2-23714"
},

"frameworks": { "dnxcore50": { } }
```

The code is implementing the abstract class `AssemblyLoadContext`, but I cannot provide it here due to the usual reasons, though I can give access now to MSFT employees if you ping me.

Ubuntu 14.04 using `dotnet-cli`.

Thanks,

Andy

**Comment by stephentoub** [comment]
@weshaggard, @ericstj, I'm facing similar issues when trying to upgrade all of corefx to use 23715 instead of 23712.  The problem appears to either be or be related to that when the build happens, it's using this:
```
/reference:c:\Users\stoub\Source\repos\corefx\packages/System.Runtime.Loader\4.0.0-rc2-23715\lib\DNXCore50\System.Runtime.Loader.dll
```
Why would it be trying to use that lib implementation as a reference instead of:
```
C:\Users\stoub\Source\repos\corefx\packages\System.Runtime.Loader\4.0.0-rc2-23715\ref\dotnet5.6\System.Runtime.Loader.dll
```
?

**Comment by stephentoub** [comment]
@ericstj, looks like this might be caused by the change you made related to https://github.com/dotnet/corefx/issues/5471...?

**Comment by ericstj** [comment]
I temporarily fixed this.  We took a dependency on a new version of NuGet that understands `dotnet5.6` is supported by `DNXCore50` but most folks don't have this so they are seeing the broken behavior.

**Comment by ericstj** [comment]
When today's build is available (23719) please give it a try.

**Comment by andschwa** [comment]
:+1: Things are working swell on 23729.
