### ISSUE TITLE
System.Data.SqlClient has code with variable name mistyped as "outter"

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/corefx#5498]
`System.Data.SqlClient.SqlConnection.RegisterForConnectionCloseNotification()` has one parameter called `outter`. There're others which can be found with good old text search.

**Comment by ellismg** [comment]
Interested in submitting a PR?

**Comment by Dmitry-Me** [comment]
@ellismg Sure unless you force that "please sign the CLA" thing on me.

**Comment by JonHanna** [comment]
IIRC typos are explicitly mentioned as an exception to the CLA being required.
