### ISSUE TITLE
Where is SqlCommandBuilder class ?

### ISSUE THREAD

**Issue by sady4850** [dotnet/corefx#5501]
Should be in System.Data.SqlClient assembly.

If where no plans implementing it please give a hint how to retrieve stored procedure parameter information (SqlCommandBuilder.DeriveParameters) .

Thanks

**Comment by linl33** [comment]
Any update on this class?

**Comment by mfe-** [comment]
Looking for a SqlCommandBuilder workaround.

**Comment by ViktorHofer** [comment]
@saurabh500 is this planned for 2.0? I tried to add the type but failed as some members and other types are missing.

**Comment by ViktorHofer** [comment]
ping @YoungGah

**Comment by justinvp** [comment]
Note: If/when `SqlCommandBuilder` is added, `SqlClientFactory` should override `CreateCommandBuilder` and return a new instance of `SqlCommandBuilder`.

**Comment by nhathongly** [comment]
Will this one will be in 2.1.0?

**Comment by corivera** [comment]
This was added in https://github.com/dotnet/corefx/pull/20883

It will ship in 2.1.0.

**Comment by bruno-garcia** [comment]
I guess a work around if you can't wait for Q2 2018 (I can't) is to peek at the [reference source](https://github.com/Microsoft/referencesource/blob/master/System.Data/System/Data/SqlClient/SqlCommand.cs#L2696a) and [corefx impl](https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlCommand.cs#L1960) and see if you can bring what you need into your project until 2.1 is released. Or run back to the full framework if you can do that.

**Comment by fdominguezcen** [comment]
I am using the 2.1.0 preview should it be in there?

**Comment by amitgpta** [comment]
@corivera i have downloaded 2.1.0 but still not able to see SqlCommandBuilder class, can you please provide some update?

or is there any alternative to this

**Comment by fdominguezcen** [comment]
I actually got the preview and implemented it on my code and it is working fine. Make sure you add the correct references and are using VS 2017 preview as well

**Comment by amitgpta** [comment]
@fdominguezcen I have Visual Studio Enterprise 2017, looks like some reference issue, can you please provide some detail which .net core Preview version you installed and how you updated the reference from 2.0 to 2.1.x preview version

**Comment by saurabh500** [comment]
@amitgpta what's the version of SqlClient that you are using?

**Comment by fdominguezcen** [comment]
You need to install VS 2017 preview edition, then you can reference the preview assemblies

**Comment by saurabh500** [comment]
@amitgpta SqlClient has support for SqlCommandBuilder stating 4.5.
Try to add a dependency on this package from Nuget https://www.nuget.org/packages/System.Data.SqlClient/4.5.0-preview2-26406-04

**Comment by amitgpta** [comment]
Thanks @saurabh500,@fdominguezcen now its working
