### ISSUE TITLE
System.Data.SqlClient.SqlInternalConnectionTds.Login() unclear timeout manipulations

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/corefx#5503]
`System.Data.SqlClient.SqlInternalConnectionTds.Login()` goes like this:

```
        if (!timeout.IsInfinite)
        {
            long t = timeout.MillisecondsRemaining / 1000;
            if ((long)Int32.MaxValue > t)
            {
                timeoutInSeconds = (int)t;
            }
        }
```

First, a better name could have been invented for `t`. Perhaps `secondsRemaining`?

Second, why does it check `Max > t` instead of `t < Max`? Is that a yet another `5 == a` Yoda condition?

Finally, if the value is "too large" the result is... zero, not "maximum value" and that's not explained. Is that desired behavior? That's not clear. I suspect this is a bug.

**Comment by saurabh500** [comment]
Closing until a defect is proven in this case.

**Comment by Dmitry-Me** [comment]
@saurabh500 How does one prove `t` is not the best variable name in the world?

**Comment by saurabh500** [comment]
We won't be changing a variable name as a part of this issue. I would much rather have them stay what they are as comparison with .Net framework code is easier this way.
 The comment was more on your question to the statement wondering if this is a bug.
