### ISSUE TITLE
Restoring all packages is taking way too long

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#5507]
Restoring all packages is taking a long time even when there is nothing to do when all the packages are in the cache and all the lock files already exist. 

@dagood I know you are looking into this but it is clear to me that we need a solution both internally and externally for this problem because it is currently killing productivity. It is also causing huge lang in our CI system. We are currently almost spawning 300 processes during this restore step.

For reference on my machine this step is taking 20-30 minutes alone where the rest of the build is less then 10 minutes. 

From a recent CI run (http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug_prtest/1117/consoleFull) you can see:
```
12:27:35   Restoring all packages...
12:50:01   Microsoft.CSharp -> 
```
It is took more then 20 minutes.

**Comment by stephentoub** [comment]
I was going to open a similar issue.  It's taking extremely long for me, as well.

**Comment by JonHanna** [comment]
If a switch allowed one to just use the cache without restoring, then while it wouldn't help with CI it could speed up quick tests. I've had cases where I'd been suffering from poor connectivity and just had to give up on trying something.

**Comment by weshaggard** [comment]
See https://github.com/dotnet/corefx/pull/5513/files#diff-3ad318a39efd856540e8cf813f20ec09R33 where I'm adding an extensibility place for folks to be able to disable restoring during the build if they know they have all the packages cached.

**Comment by dagood** [comment]
I think that we can close this now. CI now restores in less than 10 minutes, the 300 processes issue has been resolved by using dotnet restore recursively on the src directory, and for devs sync is independent from build. Are there any more performance gains we want to hit or does closing sound ok?
