### ISSUE TITLE
CurlHandler.EasyRequest.SetProxyOptions() throws ArgException when default credentials used

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#5538]
Issue moved from https://github.com/dotnet/coreclr/issues/2355 on behalf of @rtwede

Data Point 1:
When default credentials are used with the System.Net.Http.CurlHandler.Proxy as is the case in tools such as the DNX tools it results in ArgumentExceptions being thrown due to empty credentials/username.

Data Point 2:
System.Net.CredentialCache.DefaultCredentials is immutably set to a default SystemNetworkCredential (all empty strings for user, password, domain).

Data Point 3:
http://dotnet.github.io/getting-started/
Following the recommended steps to install .net core on Ubuntu Linux includes the step "dotnet restore" and exposes this failure whenever a simple proxy server is configured (e.g http_proxy=http://myserver.domain:8080/)

DNX tools grab the default credendtials and the entire installation fails due to the exception in SetProxyOptions().  It's clear the intention is that the Curl library should detect the lack of credentials and not attempt to use them.  Presently it only succeeds if creds are null, but not when username is an empty string as in the case of the default creds used by DNX tools.

Conclusion:
Fundamentally this is an incompatibility between the three implementations: DNX tools, the CurlHandler.SetproxyOptions() and DefaultCredentials.  One of the three needs to be changed so that the three are compatible with one another.  Arguably the DNX tools or the default credentials could be faulted, but SetProxyOptions seems the friendliest change to the contract between these three components because other clients might similarly use default empty credentials in the case where none are specified or present.

**Comment by davidsh** [comment]
Assuming the "proxyCredentials" are an ICredentials interface, the CurlHandler code should be first checking for something like this "if (proxyCredentials == System.Net.DefaultCredentials)" and then do the 'right thing' for using default credentials.

If not DefaultCredentials, then it can do ICredentials:GetCredentials and then inspect the username/password, etc. for invalid values, i.e. no empty strings for username.

**Comment by davidsh** [comment]
cc: @vijaykota @stephentoub

**Comment by stephentoub** [comment]
The "right thing" is likely to be an exception, though it could be a better exception.  There's no universal "default credentials" concept as there is on Windows, no way to pick up and propagate ambient credentials, etc.

**Comment by vijaykota** [comment]
@joshfree, please see if you can find some folks who can take this investigation forward.
