### ISSUE TITLE
System.Web.Script.Serialization.JavaScriptSerializer incompatible with ES6 (and V8)

### ISSUE THREAD

**Issue by cyberphone** [dotnet/corefx#5545]
A string with a quote (') is serialized as "\'" which departs from JSON.stringify()

Number serialization is not aligned with ES6.

Other reference: https://github.com/Microsoft/ChakraCore/issues/149

**Comment by joshfree** [comment]
@zhenlan please help redirect this to the correct place

**Comment by zhenlan** [comment]
Hi @cyberphone I am closing this issue as _System.Web.Script.Serialization.JavaScriptSerializer_ is not part of .NET Core. For anything related to full .NET Framework, you can open a bug through [Microsoft Connect](http://connect.microsoft.com/). The team actively monitors all incoming Connect bugs and you will also get response or status update there.

**Comment by cyberphone** [comment]
This issue may also apply to:
https://github.com/dotnet/corefx/blob/master/src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/Json/JavaScriptSerializer.cs

**Comment by cyberphone** [comment]
Bug report with code:
https://github.com/cyberphone/jsondotnet
