### ISSUE TITLE
Respond to PR code review comments for ported library System.Reflection.Extensions

### ISSUE THREAD

**Issue by venkat-raman251** [dotnet/corefx#5546]
@weshaggard Who should this be assigned to?

**Comment by venkat-raman251** [comment]
PR #5542

**Comment by joshfree** [comment]
Why are we opening bugs to respond to PR feedback?  Why isn't this just being handled as part of the PR itself?

**Comment by weshaggard** [comment]
@joshfree The primary focus of this effort is to get the code out of our internal TFS branches and onto github and while doing that people have been providing great feedback but for things that aren't simple clean-up my preference is to file an issue and let the owners of the library address the PR feedback.

**Comment by weshaggard** [comment]
@venkat-raman251 @AtsushiKan is the owner of reflection so I've assigned this to him.

**Comment by karelz** [comment]
@AtsushiKan says it was already rewritten, so probably no need for any action.
