### ISSUE TITLE
 EqualityComparerForDouble and EqualityComparerForSingle use the == operator but should use Equals

### ISSUE THREAD

**Issue by AlexGhiondea** [dotnet/corefx#5558]
The class should be calling the Equals(System.Double) method on System.Double because == has the wrong semantic for NaN.

**Comment by AlexGhiondea** [comment]
The fix for this would need to go in the coreclr repo. The PR #5619 was fixing this for CoreRT.

**Comment by stephentoub** [comment]
@AlexGhiondea, is this actually an issue on CoreCLR?  `EqualityComparer<double>.Default` will return a `GenericEqualityComparer<double>`, which uses Equals, since that's what's available via the `IEquatable<T>` interface.

**Comment by AlexGhiondea** [comment]
@stephentoub it is possible that this was only an issue in N and not in Core.
