### ISSUE TITLE
WinHttpResponseStream.ReadAsync may never finish when canceled

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#5560]
This example code pattern can result in the awaited task never moving to a terminal state:

```c#
var tokenSource = new CancellationTokenSource();
CancellationToken token = tokenSource.Token;

var client = new HttpClient();
HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, "some uri");
HttpResponseMessage response = client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead).Result;
Stream stream = response.Content.ReadAsStreamAsync().Result;

byte[] buffer = new byte[1000000];
Task task = stream.ReadAsync(buffer, 0, buffer.Length, token);
tokenSource.Cancel();

task.Wait(); // BUG - the Wait() never returns
```

**Comment by davidsh** [comment]
Added tag "blocking-partner" == Azure Storage libraries team

**Comment by EmmaZhu** [comment]
@davidsh 
I'm just trying with latest GAed .Net Core, seems the hang issue still exists. I tried it with the same sample code as you provided. 
My project.json file is like:
`{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0"
    }
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}
`
Could share any ideas what I can do to resolve it?

**Comment by davidsh** [comment]
cc: @stephentoub @ericstj 

>I'm just trying with latest GAed .Net Core, seems the hang issue still exists

Can you try explicitly adding the System.Net.Http 4.1* package?  It is possible that the meta-package of Microsoft.NETCore.App is not bringing in the System.Net.Http 4.1 package but rather an older 4.0 package. If it is bringing in the older package then the bug wouldn't be fixed.

**Comment by ericstj** [comment]
> It is possible that the meta-package of Microsoft.NETCore.App is not bringing in the System.Net.Http 4.1 package but rather an older 4.0 package. 

@davidsh that is not the case.

**Comment by EmmaZhu** [comment]
@davidsh 
Seems it's already used 4.1.0 version:
`C:\Users\emmazhu\.nuget\packages\System.Net.Http\4.1.0\ref\netstandard1.3\System.Net.Http.dll`
The issue still exists after I add System.Net.Http 4.1.0 to the dependencies:
`{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0"
    },
    "System.Net.Http": "4.1.0"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}`

**Comment by EmmaZhu** [comment]
@davidsh 
The issue still exists. Any update for it?

**Comment by ericstj** [comment]
@EmmaZhu can you share platform information (windows, mac, ubutu, etc) and the sample code if it differs from the original sample.

**Comment by EmmaZhu** [comment]
@ericstj 
The issue is gone now. It updated packages on 25th on my computer, seems from then it works well. Thanks for all of your help!
