### ISSUE TITLE
Add Red Hat Enterprise Linux 7.2 CI / Rolling Build

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#5566]
Add RHEL 7.2 to Jenkins outerloop build & test.

https://access.redhat.com/downloads/content/69/ver=/rhel---7/7.2/x86_64/product-software

Related CI work items: https://github.com/dotnet/corefx/issues/4653 (2008 R2 ServerCore), https://github.com/dotnet/corefx/issues/4656 (Debian 8.2), https://github.com/dotnet/corefx/issues/4779 (2016 NanoServer), https://github.com/dotnet/corefx/issues/5349 (Ubuntu 15.10)

**Comment by ellismg** [comment]
We have Rolling builds now for RHEL 7.2 and a PR has been opened to add badges to our README.md.  These runs can also be triggered on demand for PRs if folks need them (we continue to do CentOS per PR).
