### ISSUE TITLE
Add List constructor size to ConcurrentCollections ToList and other similiar functions

### ISSUE THREAD

**Issue by SunnyWar** [dotnet/corefx#5567]
Many of the ConcurrentCollections create Lists of all the items but do not initialize the list to the size of the number of items in the collection. Most of the time the list will end up containing the exact Count of the number of items in the collection. Rather than continuously resize the List it makes sense to initialize it to the expected size.

**Comment by SunnyWar** [comment]
Dammit, I'm so used to SLM, Source Depot, SVN, those types of things I'm having trouble figuring out how to get my changes up here.  Here they are, maybe someone can just do it.

![concurrentbetter](https://cloud.githubusercontent.com/assets/4521425/12465065/23729610-bf81-11e5-9929-4d7756490419.PNG)

**Comment by mellinoe** [comment]
You should be able to create a Pull Request if you'd like to contribute the changes back. If you push a branch up to your fork of this repository (i.e. https://github.com/SunnyWar/corefx), then a button should automatically appear on the front page of https://github.com/dotnet/corefx that should generate the appropriate PR for you.

**Comment by mburbea** [comment]
In the case of concurrent dictionary and some of these other object isn't the count property expensive? In dictionary I know it does a lock and then has to iterate to come up with a count.  And if your in a scenario where your constantly reading and writing, how can you possibly know how big the list should be?
Could an estimate based be made off your capacity and expected level of concurrency?

**Comment by stephentoub** [comment]
> isn't the count property expensive?

Yes.  These changes likely shouldn't be made exactly as suggested.  There might be some things that could be done, but in general these count operations all have enough cost that the performance benefits of sizing the list appropriately would need to be weighed against the costs of checking the count.  ConcurrentStack's Count needs to walk the linked list of elements to produce the count.  ConcurrentDictionary's needs to sum up the counts from each striped lock.  ConcurrentBag's needs to sum up the count for each thread-local list.  Etc.  Even if it proved valuable via proper perf testing, it's unlikely the Count properties should be used as is shown, e.g. ConcurrentDictionary's Count needs to take all of the locks, but at this point in the relevant code we've already taken all the locks, so it doesn't need to be done again.

**Comment by SunnyWar** [comment]
@stephentoub I assumed that Count did not have to actually count all the elements. I should have checked. I probably would not have made this recommendation had I realized it. However, I think there's a better than even chance it will still be beneficial. Your right we have to check first though.

**Comment by karelz** [comment]
It's unclear if there's any benefit from the proposed change. Closing for now, feel free to reopen when there's more data supporting the proposed change,
