### ISSUE TITLE
System.AppContext cannot be found

### ISSUE THREAD

**Issue by andschwa** [dotnet/corefx#5575]
I don't know if this is CoreFX or CoreCLR or dotnet-cli, but I tried updating to build rc3-23720, and can no longer load `System.AppContext` on Ubuntu 14.04.

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.AppContext, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

I thought perhaps I needed to reference it as a dependency explicitly (though it is depended on by [NETStandard.Platform](https://www.myget.org/feed/dotnet-core/package/nuget/NETStandard.Platform)), but that does not seem to be the case.

I build with `dotnet publish --framework dnxcore50` using the dotnet-nightly package.

Sure enough, `System.AppContext.dll` is not included in the output, but it shouldn't be looking in there anyway, as the type is in `mscorlib.dll`, which exists.

@stephentoub any ideas?

**Comment by AlexGhiondea** [comment]
/cc @ericstj @weshaggard 

@andschwa could you share a repro?

**Comment by andschwa** [comment]
@AlexGhiondea I can try to make a smaller public repro, but for now checkout the `appcontext` branch of the main repo of the team I just invited you too (I hate to speak in generalities).

**Comment by andschwa** [comment]
Simpler [repro](https://github.com/andschwa/console-repro) (reusing an old repo). Note that it works with rc2-23712.

**Comment by ericstj** [comment]
You need the newer nuget that supports dotnet5.6 to use this package.  That should be getting merged into the latest builds of the CLI.

**Comment by andschwa** [comment]
@ericstj Ah! Okay, I'll keep watching `dotnet-nightly`. Thanks :night_with_stars:

**Comment by ericstj** [comment]
I think it should be updated now.

**Comment by GuardRex** [comment]
@ericstj Just hit this ... with a `dotnet cli` install that I performed this morning (before , so it's not surprising.

Point of order: What's the best way to keep `dotnet cli` itself fully updated? There is no `dotnet update-self` ... I'm so spoiled.

**Comment by GuardRex** [comment]
@ericstj Nevermind on that one ... I understand now that the CI system produces this MSI on-the-fly ...
```
https://dotnetcli.blob.core.windows.net/dotnet/dev/Installers/Latest/dotnet-win-x64.latest.msi
```
I'm not sure where to watch for @andschwa commented `dotnet-nightly` to know when the build version has changed so that I know when to hit it for a new MSI.

**Comment by andschwa** [comment]
@GuardRex `dotnet-nightly` is the package on Linux in their Ubuntu feed. Windows doesn't have package repos (well, excluding the whole Chocolately thing...), so I think an `update-self` would still be nice. As would a package in home brew for when on my MacBook, but that's just asking for things :smile:

**Comment by GuardRex** [comment]
@andschwa It's a freak'in nightmare :skull:. I pulled down latest and ran into nothing but package walls ...everything from only VS dnu restore getting proper packages but placing them into .dnx packages and not into .nuget packages, while dotnet restore just continually chokes on 404's in spite of using the same Nuget.Config as dnu was using. Then, it's bad and conflicting dependencies after that. Docs haven't kept up with the rapid changes in design, so there's a half-dozen landminds :boom: to get past, and if you don't have @davidfowl on speed-dial on JabbR, you're behind the :8ball:. Forget about it. Gotta give 'um a few weeks to get it more stable. @anurse PC must have smoke com'in out the back right now! Somebody call 911 for him. :fire_engine: :ambulance: Hang in there @anurse ... I'm pull'in for ya!

**Comment by andschwa** [comment]
HAHA that sounds about right. Things will get better for everyone soon enough!

**Comment by GuardRex** [comment]
They need ... I'd say 2-3 weeks. Docs are a killer, too. The docs team isn't (apparently) even trying to do anything to keep up, and I think even @blackdwarf is reeling from the rapid design and breaking changes.

If anyone is thinking about jumping into `dotnet cli` right now ... word of advice ... DON'T! Wait a few weeks. They need a little time to bust through some design. I'm going to try again 2nd week in Feb.

Until then it's going to be DNX on Nano for me!

### :sparkles: **Nano Server** :sparkles: ... small in size ... BIG IN HEART! :heart:

**Comment by andschwa** [comment]
It's too late for me, DNX isn't an option. We're full-steam ahead with `dotnet-cli` :steam_locomotive:!

**Comment by blackdwarf** [comment]
@GuardRex thanks for the worries. ;) This is good feedback about the docs. When you mention "docs", can you tell me which docs you are referring to? The READMEs on the repo, docs on https://dotnet.github.io/docs/ or all of the above?
