### ISSUE TITLE
System.PlatformNotSupportedException being thrown in SQLClient on Windows machines

### ISSUE THREAD

**Issue by javiercn** [dotnet/corefx#5601]
When running ASP.NET tests on our CI machine (Windows), we are observing a System.PlatformNotSupportedException exception being thrown. The problem looks to be in:

https://github.com/dotnet/corefx/blob/ceae1d38c93e3f53210ad91884dabc1bd6d30a90/src/System.Data.SqlClient/src/Interop/SNINativeMethodWrapper.cs#L420

```
System.PlatformNotSupportedException
The Win32NativeMethods.IsTokenRestrictedWrapper is not supported on non-Windows platform
```

**Comment by saurabh500** [comment]
Based on the information provided, this piece of code should not be built for Windows. 

The MANAGED_SNI flag is only added when SqlClient is built for Windows.

**Comment by saurabh500** [comment]
Looking at the IL, it contains the Managed Bits which are meant for non-Windows systems. 

The way System.Data.SqlClient is being built for Windows has changed causing this problem. 
I checked the IL for the Linux Dlls and they seem fine.

**Comment by divega** [comment]
@saurabh500 @ericstj @corivera When is the change in https://github.com/dotnet/corefx/pull/5604 (assuming it fixes this issue) going to make it into the release branch? Out builds are still blocked by this.

**Comment by corivera** [comment]
This issue was fixed by @ericstj in https://github.com/dotnet/corefx/pull/5604

@divega The change was ported in https://github.com/dotnet/corefx/pull/5629

**Comment by divega** [comment]
Thanks @corivera!
