### ISSUE TITLE
System.Net: Replace existing "catch Exception / throw later" patterns with ExceptionDispatchInfo 

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#5606]
@stephentoub :

> There are a bunch of places in the code where an Exception is caught and then later thrown. This kind of re-throwing ends up clobbering the original call stack and Watson bucket stored in the Exception, making it more difficult for someone looking at the exception to understand where it came from. To address this, ExceptionDispatchInfo was added in .NET 4.5, and is now used in places like Task that have this exact issue. I'd suggest we look at using ExceptionDispatchInfo in all of these places. Basically, instead of just storing an Exception, you'd store the result of ExceptionDispatchInfo.Capture(caughtException), and then instead of using throw _caughtException;, you'd do _caughtExceptionDispatchInfo.Throw();. ExceptionDispatchInfo will preserve the original information and append the new throw location's call stack rather than using it to overwrite the original.

This was discussed in https://github.com/dotnet/corefx/pull/5541#discussion_r50399913.

**Comment by karelz** [comment]
Next step: Scan the code base of System.Networking, replace the pattern as per advise above.
Should be straightforward.
