### ISSUE TITLE
dynamic usage causing live hangs after upgrading packages

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5610]
I'm trying to upgrade our packages to rc3-23721, and on Windows the System.Numerics.Vectors tests are hanging, pegging the CPU at the line doing the dynamic cast here:
```C#
        public static T GenerateSingleValue<T>(int min = 1, int max = 100) where T : struct
        {
            var randomRange = s_random.Next(min, max);
            T value = (T)(dynamic)randomRange;
            return value;
        }
```

**Comment by mellinoe** [comment]
I was able to get a simpler repro with just this code:

````CSharp
[Fact]
public void FakeTest()
{
    int intValue = 5;
    float value = (float)(dynamic)intValue
    Assert.Equal(5.0f, value);
} 
````

Something is wrong with dynamic, I think.

**Comment by stephentoub** [comment]
Yeah.  The System.Dynamic.Runtime.Tests are also hanging, in the very first test that gets run.  It appears to be in an infinite loop accessing CallSite.Binder from within a lightweight function.

@jkotas, I'm trying to upgrade us from the rc2-23712 packages to the rc3-23721 packages, and we're hitting this issue.  Ideas?  Has something changed in this area recently?

**Comment by jkotas** [comment]
These is something wrong with how the expression generated from the callsite is compiled by System.Linq.Expressions.dll.

It is recent regression in System.Linq.Expressions.dll. If I copy old System.Linq.Expressions.dll into current build, it works fine.

**Comment by jkotas** [comment]
cc @JonHanna @VSadov

**Comment by stephentoub** [comment]
This PR appears to be the cause: https://github.com/dotnet/corefx/pull/5273

**Comment by stephentoub** [comment]
I've added a commit to https://github.com/dotnet/corefx/pull/5596 to revert #5273.  We'll see if it addresses the issue, which caused all of the legs to be aborted due to hanging.
cc: @VSadov, @JonHanna

**Comment by JonHanna** [comment]
Thanks for reverting it. Unfortunately I won't have a chance to look at this until the evening, Irish timezone.

**Comment by stephentoub** [comment]
> We'll see if it addresses the issue, which caused all of the legs to be aborted due to hanging.

It did fix it.

**Comment by VSadov** [comment]
Thanks for fixing this!
I do not yet understand how the change could have caused the hangs.

**Comment by VSadov** [comment]
I think it might be because of assumption at
```
// If the type operand is sealed (including value types, void and nullables) then the result
// must be false or it would have been handled by one of the cases above.
if (_typeOperand.GetTypeInfo().IsSealed)
{
       return Expression.Block(Expression, Expression.Constant(false));
}
```

The static type of the LHS can differ from the actual value. 
In particular LHS could be an object expression holding a boxed int. So if the _typeOperand is an int, and the LHS is statically object, the result can still be "true".

The right course of action is still to revert the https://github.com/dotnet/corefx/pull/5273 and when all is working implement a better fix.

**Comment by JonHanna** [comment]
Yes. That attempt to go the extra mile went the extra mile in the wrong direction. Remove that block and there's no regression, while still having the fix the bad PR was intended to fix.
