### ISSUE TITLE
Remove System.Data.Common.DbColumn's _customValues

### ISSUE THREAD

**Issue by NickCraver** [dotnet/corefx#5611]
Per #5609 and @saurabh500, creating an issue here:

I think the Dictionary on `DbColumn` should be protected so that implementers can access the structure more efficiently. Downstream people will want to iterate, bulk create, etc. The indexer being the only point of access internally will be a problem/bottleneck there.

**Comment by justinvp** [comment]
Is the intention for DB implementations to subclass `DbColumn` (e.g. there will be a `SqlColumn` either internal or public)? If so, perhaps the Dictionary should be removed from `DbColumn` altogether to allow subclasses to implement the indexer in the most efficient way possible for the given DB.

Also (sorry if this is unrelated), should `DbColumn` be mutable? Right now the indexer and all the properties have setters. Are there scenarios where a user of the API would want to modify a `DbColumn` or should it only have getters?

**Comment by saurabh500** [comment]
@justinvp The intention is to be able to use the DbColumn as is. At the same time the providers can choose to subclass DbColumn in case they want to add an attribute which is specific to the DB. However the indexer allows adding more attributes and allow them to be consumed without adding dependency to the Db Provider.

More details in the #3423 

Any recommendation / suggestion?

**Comment by NickCraver** [comment]
On further thought, @justinvp is right. The dictionary should just go away. There's no need for the allocation(s) since the actual implementation will very likely be a switch statement here. It's much simpler to just remove it. The default implementation should also implement this same switch for consistency though:

```C#
public virtual object this[string property]
{
	get
	{
		switch (property)
		{
			case nameof(AllowDBNull):
				return AllowDBNull;
			case nameof(BaseCatalogName):
				return BaseCatalogName;
			//...
		}
		return null;
	}
}
```
Inheritors would have a `return base[property];` at the end instead. While the box is still involved to `object`, it's completely lazy here would should be a much rarer case.

**Comment by saurabh500** [comment]
What would be the setter in this case then? How would the default implementation of the DbColumn indexer be used?

**Comment by NickCraver** [comment]
I don't think a setter is needed at all, since each implementation would handle the switch for the properties they support over the base. The default implementation would be the code sample above, just expanded to include all properties. It'd be populated by the properties themselves being set - no need to set things twice. This avoids the duplication, allocations, and enables the weakly typed and referenceless access at all levels, even on the base.

**Comment by saurabh500** [comment]
@NickCraver @justinvp 
I understand what you are saying. 
To add any extra attributes to DbColumn, it will need to be sub-classed.
However to consume the attributes the consumer will not have to take a dependency on the provider.

Any extension to DbColumn would only be possible via creation of a Subclass. 
This way the responsibility of new attribute addition and its implementation lies on the provider.

**Comment by FransBouma** [comment]
The resultset schema will likely be examined only once per query, accessing a structure through a property or through a field won't make much of a difference, performance wise, however protected fields are not great, design wise, so a bad compromise for an irrelevant performance gain. 

Please don't make design choices like this to gain some hypothetical optimization, as that's a slippery slope.

**Comment by NickCraver** [comment]
@FransBouma not sure if you're following the whole thread - nothing is protected, we're saying it should be removed entirely.

**Comment by FransBouma** [comment]
Ah, indeed, as your idea is that every value in that dictionary is actually also exposed as a property anyway? Or at least, it forces a provider developer to do so or keep its own dictionary. 

The switch / case on strings will at compile time be converted to a dictionary lookup which is quite quick anyway and no extra data storage is required indeed. Agreed with the switch design.

**Comment by chadbr** [comment]
I guess it's too late, but for what it's worth...

We have used these dictionaries on DbColumn and DbTable pretty extensively.

This is the only means for a data layer to "attribute" tables coming from the database with meta information that is meaningful to a system without resorting to a custom object structure that parallels the dataset/table/column structure.

As an example, our application(s) have type systems and we use these dictionaries to expose the mapping of a physical model (i.e. Tables / Columns) to types / properties in our type system.

So when someone receives a DataTable, they can use the type system it's to look into our type cache and pull out information useful for reporting, calculations, display, etc. (i.e. What is the precision or preferred formatting of a double? What unit of measure is it stored in? What is the display label for this column? In English? In Spanish?, etc. etc.).

We can certainly live without them, but I don't see how it costs you much to leave them in place?

Thanks, Chad

**Comment by NickCraver** [comment]
@chadbr You can still do all what you want here - just create your own type inheriting  from `DbColumn` and override the `this[string property]` indexer. You can check your dictionary and fall back to `return base[property];` on a miss. There's simply not a good reason for having an unused dictionary *in the base*. You're totally free to have one downstream if that makes sense. 

Any tool looking accessing the indexer doesn't need to reference or specifically know about your new type, the property access will still work even when it's only looked at as a `DbColumn`.

If I missed your point and you're really asking "Why isn't `DataTable` left in place?", that's a much larger discussion. Can you clarify?

**Comment by chadbr** [comment]
@NickCraver 
Maybe I missed something - How would my DbColumn derived class be constructed? Through DI?

If that's the case, no issues then.

As for the DataTable discussion - I've read the other threads (I'm for keeping DataSet/DataTable/DataView by the way...)
