### ISSUE TITLE
Clarify coding styles for on visibility modifier order

### ISSUE THREAD

**Issue by NickCraver** [dotnet/corefx#5620]
I know it's a tiny bit OCD, but the mix of `abstract public` and `public abstract` in the repo slows reading of code a bit since you have to switch. I assume the intent is `public abstract` with the visibility modifier up front since that's by far the more prevalent both here and in the wild.

Can this be made explicit [in the coding style rules](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md)?

I propose simply adding to point 5:

> We always specify the visibility, even if it's the default (i.e. `private string _foo` not `string _foo`).

To be:

> We always specify the visibility, even if it's the default (i.e. `private string _foo` not `string _foo`). Visibility should be the first modifier (i.e. `public abstract` not `abstract public`).

**Comment by stephentoub** [comment]
Sounds good to me.

**Comment by davidsh** [comment]
Can we also clarify the order of the `readonly` and `static` modifiers as well?  I think `readonly` goes before `static`.

Is it:

`private static readonly bool s_foo = false;`

or

`private readonly static bool s_foo = false;`

**Comment by stephentoub** [comment]
Just based on current usage across the codebase, there are only 174 occurrences of ```readonly static``` while there are 2194 occurrences of ```static readonly```, so it seems we've largely voted with our feet for ```static readonly```.
