### ISSUE TITLE
Expose DescriptionAtttribute

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#5625]
Splitting this out from https://github.com/dotnet/corefx/issues/2065 since it has scenarios outside of System.Data.

See https://github.com/aspnet/Home/issues/1251

**Comment by chlowell** [comment]
`DescriptionAttribute` was added with #8093

**Comment by yetanotherchris** [comment]
For those still waiting for RTM, it's very easy to put a temporary fix in :)


    public class DescriptionAttribute : Attribute
    {
        public string Description { get; set; }

        public DescriptionAttribute(string description)
        {
            Description = description;
        }
    }
