### ISSUE TITLE
DirectoryInfo.Exists on a symlink to a directory fails on Unix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5630]
Due to https://github.com/dotnet/corefx/pull/5020, now a DirectoryInfo created for a symlink to a valid directory returns false for Exists.

This is causing any HttpClient request to an https URL to fail on Ubuntu, as X509Certificates uses DirectoryInfo.Exists to determine whether it can enumerate the root store certs directory, and on Ubuntu, the default certs path is a symlink.

cc: @mjrousos, @ianhays

**Comment by ianhays** [comment]
Eek. It looks like Directory.Exists still uses stat so we could modify the x509 code to just call that instead, or we could revert the change for now.

**Comment by mjrousos** [comment]
Yea, this definitely seems no good. I'm taking a look to see how DirectoryInfo.Exists on a symlink works on Windows. Ideally, Linux should match its behavior.

**Comment by stephentoub** [comment]
cc: @ericstj 

Part of the problem here is the goal of having the Unix behavior match the Windows behavior.

On Windows, none of the File, Directory, FileInfo, or DirectoryInfo functions follow symlinks.  This means that Directory.EnumerateFiles on a symlink throws an exception, File.Exists on a symlink that points to a non-existent file returns true, etc.  While that may make some sense on Windows where symlinks aren't as common, on Unix they're extremely prevalent, and not following symlinks in these situations would lead to very bad outcomes IMHO.

Then there are directory junctions.  Those are closer to the desired behavior.  Both Directory and DirectoryInfo let you enumerate a junction, enumerating the target instead, but if you delete the target, Directory.Exists and DirectoryInfo.Exists still return true, even though the target is gone.

My proposal then is to simply do something that seems to make sense for Unix and that meets the spirit of what was originally filed as the issue in #5015: do what we did before the change in #5015, effectively reporting information from following the symlink, except also ensure that attributes include ReparsePoint if the target is a link.  We can do this by first using lstat, and then if it's a symlink, using stat.  I think this is simple and explainable behavior that matches what people would expect.

Thoughts?

**Comment by mjrousos** [comment]
I think that makes sense. We'll need to make sure to document the differences, so that users understand what to expect. For #5015, the concern was just that some users (Azure storage) needed the ability to identify whether a given directory was a link or not; but @stephentoub's proposed solution still unblocks that scenario.

**Comment by stephentoub** [comment]
Ok.  I'll fix it.

**Comment by mjrousos** [comment]
Thanks, @stephentoub!

**Comment by ianhays** [comment]
https://github.com/dotnet/corefx/issues/6556
