### ISSUE TITLE
VS debug System.Collections.Test throws huge number of exceptions

### ISSUE THREAD

**Issue by ankitbko** [dotnet/corefx#5638]
If I start debugging test in System.Collections.Test using VS, large numer of exception gets thrown most(probably all) from mscorlib. It takes more than 15 min to even hit my break point. Am I doing something wrong here?

![image](https://cloud.githubusercontent.com/assets/3169316/12523642/2339136e-c17e-11e5-844f-35037cab7c87.png)

**Comment by mellinoe** [comment]
A lot of the tests do things to verify that certain exceptions are thrown, so this is probably expected. If you look at the call stack of those exceptions you'll probably see they are caught by an `Assert.Throws<Exception>` or something like that.

**Comment by ankitbko** [comment]
Thanks that helped.
