### ISSUE TITLE
System.Runtime broken in VisualStudio

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#5654]
`System.Runtime`'s solution file is broken, preventing builds in VisualStudio.
It's looking for a p2p reference for:

 - System.Private.Uri.CoreCLR
 - System.Runtime.CoreCLR

...the latter got renamed to `System.Runtime`, but I'm not too terribly sure what to do about `System.Private.Uri` - is there a specific package it should be grabbing instead?
The solution file is also ignoring the contents of the `ref` directory, which might be important...

**Comment by ellismg** [comment]
LGTM
