### ISSUE TITLE
Coding guidelines clarifications

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#5668]
I've taken a look at the coding guidelines, and wanted to get some clarifications for the coding style for production code:

- Are regions encouraged or discouraged? If discouraged, should they be removed from existing code? (see https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/HashSet.cs for an example)

- Are extensive comments above functions encouraged or discouraged? If discouraged, should they be removed from existing code? (see https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/BitArray.cs for an example)

- Should classes have a large intro banner at the top? If not, should they be removed from existing code? (see https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/SortedSet.cs for an example)

- Should Contracts be used (e.g. `Contract.EndContractBlock()`)? If not, should they be removed from existing code?
- Follow up: what are the major differences between code formatting styles in coreclr and corefx?

Thanks, I know these are small nitpicks!

**Comment by Maxwe11** [comment]
>Are regions encouraged or discouraged? If discouraged, should they be removed from existing code? 

Most of the code doesn't have regions.

>Are extensive comments above functions encouraged or discouraged? If discouraged, should they be removed from existing code?

Some of the comments are really necessary.

>Should Contracts be used (e.g. Contract.EndContractBlock())? If not, should they be removed from existing code?

https://github.com/dotnet/corefx/issues/682
