### ISSUE TITLE
Will DbConnection be abstracted behind an interface?

### ISSUE THREAD

**Issue by scionwest** [dotnet/corefx#5689]
I've started building out a little ORM project for .Net Core and noticed that the DbConnection did not have any interfaces that I can wrap my providers behind. Is this something in the roadmap? If not, what is the expectation for unit testing, fakes by inheritance and what was the reasoning behind making this change from how .Net worked? Would this mean I have to build an abstraction layer over IDbConnection/DbConnection so I can support a .Net 4.5 implementation & a .Net Core implementation?

I tried looking for some documentation or issues related to this to help understand the direction you are going with DbConnection; came up empty.

**Comment by khellang** [comment]
https://github.com/dotnet/corefx/issues/3480

**Comment by saurabh500** [comment]
With the ADO.Net interfaces coming back in with PR #6359 this issue should be fixed.
