### ISSUE TITLE
System.Security.Principal.Windows missing runtime assembly on Linux

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#5694]
Or incorrectly referenced? Not sure, not directly referenced

It restores fine
`Installing System.Security.Principal.Windows.4.0.0-rc2-23722`
Then errors in use
```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Security.Principal.Windows, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
 ---> System.IO.FileNotFoundException: Could not load the specified file.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   --- End of inner exception stack trace ---
   at System.Net.ContextAwareResult.Cleanup()
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionCallback(Int32 numBytes, SocketError errorCode)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
bash: line 1: 13883 Aborted                 (core dumped) dnx test
fail: Exit code 134 from /usr/bin/env
fail: Stack trace: 
```
No issues on Windows

**Comment by benaadams** [comment]
Related? https://github.com/dotnet/corefx/pull/5576

**Comment by benaadams** [comment]
@stephentoub looks like issue you saw in https://github.com/dotnet/corefx/pull/5596#issuecomment-173966765

**Comment by nagya11** [comment]
Please - is the type that,, how long to "do it: small: medium: large: User
Flies and stop good !! ??? When the drawer !! Thanks Anna!.

2016-01-26 12:47 GMT+01:00 Ben Adams <notifications@github.com>:

**Comment by stephentoub** [comment]
Yes, this should be fixed in newer packages.

**Comment by ericstj** [comment]
That's by design. The contract isn't supported on Linux.  Also, if you use either NuGet or the latest dotnet CLI you should see a restore error.

The dependency from System.Net on System.Security.Principal.Windows was fixed with https://github.com/dotnet/corefx/pull/5576.  You should see that fix in either rc3-23722, or rc2-23726.

**Comment by davidfowl** [comment]
This is going to wreak havoc on upstream packages. Now everyone has to pivot on runtime when they use this dependency.

**Comment by ericstj** [comment]
This is not different than Microsoft.Win32.Registry, System.Security.Cryptography.Cng, System.Net.Http.WinHttpHandler, System.Runtime.WindowsRuntime.UI.Xaml.  All of these are Windows-specific technologies.  We have similar Unix only packages today just not as many of them (OpenSSL comes to mind).

Perhaps you are suggesting the scenario for using WindowsIdentity is a common one and there should be a good cross-platform API that hides platform specific types.  That could be true, though I'd like to hear that from the folks that own the libraries that are using this contract today.

@brentschmaltz does System.Security.Claims have anything like that?

**Comment by andschwa** [comment]
```
error: System.Security.Principal.Windows 4.0.0-rc3-23726 provides a compile-time reference assembly for System.Security.Principal.Windows on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64.
```
@stephentoub This dependency appears to have regressed in 4.0.0-rc3-23726.

**Comment by ericstj** [comment]
@andschwa shared his project file with me and he's using System.IO.FileSystem.AccessControl, Microsoft.Win32.Registry.AccessControl, and System.Security.AccessControl.  All of these are Windows-specific.

**Comment by andschwa** [comment]
@ericstj With `dotnet-cli`'s switch to NuGet, I'm going to have to find another way to provide these types for my project.

**Comment by ericstj** [comment]
@andschwa it's not just the types.  You need to bring down the implementation as well.  One proposal on the table is https://github.com/dotnet/cli/issues/465 which would enable applications to cross-compile by OS.  Another thing that's been discussed in the past is "optional" dependencies, though I don't think there is a solid proposal for that one.

**Comment by andschwa** [comment]
We guard against the use of actual code itself at runtime (shared codebase), so the implementation should never be hit.

**Comment by glennc** [comment]
@davidfowl Doesn't HttpPlatformHandler middleware depend on this? Doesn't this break our ability to move the template apps in VS to Linux or OS X without changes?

**Comment by lodejard** [comment]
@glennc yes, using "implementation missing" at restore time instead of "platform not supported" at run-time means the templates are OS-specific.

**Comment by ericstj** [comment]
That's only if HttpPlatformHandler doesn't build as a fat package.  If you were to build this component as a fat package with separate windows and unix implementations, you wouldn't have OS-specific templates.

This is what we do already for all CoreFx packages that need to use platform specific technology.

**Comment by ericstj** [comment]
This was fixed by adding PlatformNotSupported assemblies.
