### ISSUE TITLE
Unix test: System.Xml.XDocument: "Mismatch : expected: <Root><?badpi text ? >?></Root>"

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#5701]
Failed in #5690

Some Console.WriteLine race condition is hiding the test execution summary for the test that failed:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst_prtest/146/consoleFull#-21371504001f1a4601-6aec-4fd5-b678-78d4389fd5e8

@krwq, @sepidehMS PTAL

```
23:53:19 === TEST EXECUTION SUMMARY ===
23:53:19    System.Xml.XDocument.TreeManipulation.Tests  Total: 2, Errors: 0, Failed: 0, Skipped: 0, Time: 0.988s
23:53:19 Mismatch : expected: <Root><![CDATA[test ]]]]><![CDATA[> test]]></Root>
23:53:19  actual: <Root><![CDATA[test ]]]]><![CDATA[> test]]></Root>
23:53:19 Mismatch : expected: <Root><!--test - - --></Root>
23:53:19  actual: <Root>
23:53:19   <!--test - - -->
23:53:19 </Root>
23:53:19 Mismatch : expected: <Root><?badpi text ? >?></Root>
23:53:19  actual: <Root>
23:53:19   <?badpi text ? >?>
23:53:19 </Root>
23:53:19 Finished:    System.Xml.XDocument.xNodeBuilder.Tests
23:53:19 
23:53:19 === TEST EXECUTION SUMMARY ===
23:53:20    System.Xml.XDocument.xNodeBuilder.Tests  Total: 19, Errors: 0, Failed: 0, Skipped: 0, Time: 1.178s
23:53:20 Finished:    System.Xml.XDocument.SDMSample.Tests
```

**Comment by Priya91** [comment]
This failure is happening quite frequently in many of the Unix runs, failing the builds.. But it doesn't report the test as failed.

Another instance: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/ubuntu_debug_tst_prtest/2019/consoleFull#-21371504001f1a4601-6aec-4fd5-b678-78d4389fd5e8

**Comment by joshfree** [comment]
@krwq @sepidehMS any update?

**Comment by sepidehMS** [comment]
This has been fixed by https://github.com/dotnet/corefx/pull/6360.
