### ISSUE TITLE
Support .NETStandard in CoreFx packages

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#5707]
This covers the last item from https://github.com/dotnet/corefx/issues/4367.

All CoreFx packages need to be updated to use NETStandardX.Y instead of DotNETX.Y.  

Since NETStandardX.Y was made to be separate from DotNETX.Y all dependencies of these packages must also support NETStandardX.Y.

Currently our dependencies are harvested to represent the minimal version required by surface area.  This needs to change since the minimal version required by surface area is no longer sufficient, the package must also support NETStandard.  As such we'll introduce a package baseline concept into the build.  The baseline will be the set of package versions that packages use for a particular contract.  It's still possible for packages to depend on versions newer than this baseline and we'll calculate those normally as we do today, but we'll ensure a minimal baseline.  We'll update this baseline as needed for compatibility.

One wrinkle in this plan is that .NET Native currently has a set of libraries at the bottom of the stack that it doesn't want to update.  We'll make sure that the baseline does not update these implementation assemblies.  In some cases this means we'll need to ship pre-versioned packages that contain the old binaries.  Some packages can be shipped as merely runtime-packages for existing reference packages.  Other cases we'll actually need to produce a lower versioned reference package than we do today.

Since this baseline will be slightly different than latest in a couple cases we may also want to produce a pre-version of NETStandard.Library that can be used for UWP without invalidating shared library.

A downside of this baseline is it means that updating a single package is no longer possible.  Packages will bring with them new versions of all dependencies that are newer in the baseline than the minimum required.  At first we'll just record the minimum dependency for packages and write it out as a metadata (eg: text file) in the package. We could produce special patch packages for these that would permit the "minimum" set if we wanted.  Those patch packages would reference the latest package (with latest dependencies) in addition to the minimum dependency graph of the package.  As such the patch package would downgrade all the latest dependencies to minimum.  Those patch packages would only be install-able in a project that supported the old 'dotnet' TFMs.

Work involved:
- [x] Update buildtools to use NETStandard instead of dotnet.
- [x] Update CoreFx, WCF, and internal projects to use NETStandard instead of dotnet.
- [x] Implement package baseline.
- [x] Produce pre-versioned packages to support NETNative's shared library in our baseline.
 -  [x] Split existing ref packages that are in NETStandard.Platform that need a pre-versioned impl with no version change
  - [x] Produce pre-versioned standalone packages
  - [x] Produce pre-versioned ref packages that need to expose less API for a particular NETStandard version
- [ ] Update CoreFx projects so that they can consume new packages.
  - blocked on getting CoreFx onto latest CLI. Work in progress by @dagood 

Coincidentally this will fix https://github.com/dotnet/corefx/issues/5476

**Comment by muratg** [comment]
@davidfowl @danroth27

**Comment by ericstj** [comment]
I have a private build with this change.  To actually commit it we need to have corefx on the latest dotnet CLI, otherwise it won't understand the new moniker and we won't be able to consume our own packages.  @dagood is working on that.

Also, this only enables NETStandard monikers.  To enable NETStandardApp we still need to update all libraries being packaged as `dnxcore` to use either `netstandard` or `netstandardapp`.  Most can be moved to use `netstandard`.  @chcosta  is working on this as part of the move of package projects to open.

The preversioned packages are being produced and used as the baseline.  I still need to produce some new sets of meta-packages/lineups to enable the UWP targeting scenario and NETStandard lib scenario that doesn't break shared library.  https://github.com/dotnet/corefx/issues/5843 is tracking that.
