### ISSUE TITLE
Clean up build.sh and mono.targets

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#5743]
Once we move to using .Net Core MSBuild for x-plat build, we should clean up build.sh script since it has a lot of code that downloaded msbuild plus it had some checks for prerequisites. We should also stop using mono.targets, since they shouldn't be required anymore.

**Comment by mellinoe** [comment]
:+1:

**Comment by jasonwilliams200OK** [comment]
I am running corefx build with this diff at the moment on OSX and it seems to be building fine without mono installed on my system (cloned fresh corefx > removed some code from `build.sh` > and deleted `mono.targets` then ran `./build.sh`):

```diff
diff --git a/build.sh b/build.sh
index d6fea00..e38c1cc 100755
--- a/build.sh
+++ b/build.sh
@@ -36,27 +36,6 @@ clean()
 
 # Check the system to ensure the right pre-reqs are in place
 
-check_managed_prereqs()
-{
-    __monoversion=$(mono --version | grep "version 4.[1-9]")
-
-    if [ $? -ne 0 ]; then
-        # if built from tarball, mono only identifies itself as 4.0.1
-        __monoversion=$(mono --version | egrep "version 4.0.[1-9]+(.[0-9]+)?")
-        if [ $? -ne 0 ]; then
-            echo "Mono 4.0.1.44 or later is required to build corefx. Please see https://github.com/dotnet/corefx/blob/master/Documentation/building/unix-instructions.md for more details."
-            exit 1
-        else
-            echo "WARNING: Mono 4.0.1.44 or later is required to build corefx. Unable to assess if current version is supported."
-        fi
-    fi
-
-    if [ ! -e "$__referenceassemblyroot/.NETPortable" ]; then
-        echo "PCL reference assemblies not found. Please see https://github.com/dotnet/corefx/blob/master/Documentation/building/unix-instructions.md for more details."
-        exit 1
-    fi
-}
-
 check_native_prereqs()
 {
     echo "Checking pre-requisites..."
@@ -96,16 +75,6 @@ prepare_managed_build()
         fi
     fi
 
-    # Grab the MSBuild package if we don't have it already
-    if [ ! -e "$__msbuildpath" ]; then
-        echo "Restoring MSBuild..."
-        mono "$__nugetpath" install $__msbuildpackageid -Version $__msbuildpackageversion -source "https://www.myget.org/F/dotnet-buildtools/" -OutputDirectory "$__packageroot"
-        if [ $? -ne 0 ]; then
-            echo "Failed to restore MSBuild."
-            exit 1
-        fi
-    fi
-
     # Run Init-Tools to restore BuildTools and ToolRuntime
     chmod a+x $__scriptpath/init-tools.sh
     sh $__scriptpath/init-tools.sh
@@ -339,9 +308,6 @@ setup_dirs
 
 if $__buildmanaged; then
 
-    # Check prereqs.
-
-    check_managed_prereqs
 
     # Prepare the system
 
diff --git a/mono.targets b/mono.targets
deleted file mode 100644
index 0fe780a..0000000
--- a/mono.targets
+++ /dev/null
@@ -1,15 +0,0 @@
-<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
-
-  <!-- Temporary workarounds to allow building on Unix against MSBuild on top of Mono -->
-
-  <!--
-    Normal behavior is to blacklist assemblies that don't meet ResolveAssemblyReference's analysis of what is part of the target
-    framework profile. This causes us to fail on Mono as the framework ref folders don't match up with Windows. Setting the
-    following skips this behavior- should probably do the same in the normal targets (for Windows).
-  -->
-  <PropertyGroup>
-    <IgnoreDefaultInstalledAssemblyTables>true</IgnoreDefaultInstalledAssemblyTables>
-    <IgnoreDefaultInstalledAssemblySubsetTables>true</IgnoreDefaultInstalledAssemblySubsetTables>
-  </PropertyGroup>
-
-</Project>
```

Would be nice to have CI configured to consume msbuild and update build docs removing mono  references.

**Comment by jasonwilliams200OK** [comment]
In case it is not known; you can copy/paste the diff code in a text file on osx/linux and cd into corefx and run `git apply path/to/diff-patch-file`

**Comment by Priya91** [comment]
> Once we move to using .Net Core MSBuild for x-plat build,

When is this coming?

**Comment by jasonwilliams200OK** [comment]
https://github.com/dotnet/corefx/pull/5711

**Comment by mellinoe** [comment]
We should be able to move forward with this. What you have, @jasonwilliams200OK , looks good to me. We should also remove the uses of the PCL reference assemblies in build.sh (__referenceassemblyroot, etc.). I'm running a build from this branch now to see if everything works as expected:

https://github.com/mellinoe/corefx/commit/4eec886811319b26edac88896565536b6e859923

**Comment by jasonwilliams200OK** [comment]
@mellinoe, the build failed for me after couple of minutes and I forgot to update here. If that is building fine. I will give it a try on some VMs and on OSX in couple of hours. This is a great achievement for docker/low-resource Unix environments! Thank you. :tada:

**Comment by mellinoe** [comment]
@jasonwilliams200OK Do you recall where your build failed? Mine hasn't hit any issues, but has only finished about 1/3 of the libraries so far.

**Comment by mellinoe** [comment]
I actually did hit some issues when I didn't use the PCL reference assemblies. A small number of projects are still using the PCL references but can be easily switched off. Another issue also cropped up regarding unused using statements (to namespaces absent from any referenced assembly), which should also be easy to fix but will require going through a bunch of source files and cleaning up the using statements.

**Comment by joperezr** [comment]
Closing since this was fixed already. There is a separate issue for the PCL work #5901
