### ISSUE TITLE
System.Net EventSources conflict, reducing total logging

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#5755]
Given:
```C#
    internal class ConsoleEventListener : EventListener
    {
        private static string[] s_optOut =
        {
            "System.Threading.Tasks.TplEventSource",
            "System.Diagnostics.Eventing.FrameworkEventSource",
        };

        public ConsoleEventListener()
        {
            foreach (EventSource source in EventSource.GetSources())
            {
                if (Array.IndexOf(s_optOut, source.Name) == -1)
                {
                    EnableEvents(source, EventLevel.LogAlways);
                }
            }
        }

        protected override void OnEventSourceCreated(EventSource eventSource)
        {
            base.OnEventSourceCreated(eventSource);

            if (Array.IndexOf(s_optOut, eventSource.Name) == -1)
            {
                EnableEvents(eventSource, EventLevel.LogAlways, EventKeywords.All);
            }
        }

        protected override void OnEventWritten(EventWrittenEventArgs eventData)
        {
            Console.Write("Event ");
            Console.Write(eventData.EventSource.Name);
            Console.Write('-');
            Console.Write(eventData.EventId);
            Console.Write("  (");

            if (eventData.Payload != null)
            {
                bool writeComma = false;

                foreach (object value in eventData.Payload)
                {
                    if (writeComma)
                    {
                        Console.Write(", ");
                    }

                    Console.Write(value);
                    writeComma = true;
                }
            }

            Console.WriteLine(").");
        }
    }
```

Open an instance of the logger, then proceed to open a TcpListener and a (client) SslStream.  Notice that many of the logs appear to be missing, which is likely due to:

```
...
Event Microsoft-System-Net-Debug-1  (Dns.GetHostName).
Event Microsoft-System-Net-Debug-0  (ERROR: Exception in Command Processing for EventSource Microsoft-System-Net-Debug: An instance of EventSource with Guid 99e4576b-9d7e-585f-8b32-0ac3082f2282 already exists.).
...
Event Microsoft-System-Net-1  (System.Net.Sockets.Socket, 55915408, BeginConnect, localhost, 0, 0).
Event Microsoft-System-Net-0  (ERROR: Exception in Command Processing for EventSource Microsoft-System-Net: An instance of EventSource with Guid 501a994a-eb63-5415-9af1-1b031260f16c already exists.).
...
Event Microsoft-System-Net-2  (System.Net.Sockets.TcpClient, 43495525, GetStream, System.Net.Sockets.NetworkStream, 2606490, 0).
Event Microsoft-System-Net-Debug-0  (ERROR: Exception in Command Processing for EventSource Microsoft-System-Net-Debug: An instance of EventSource with Guid 99e4576b-9d7e-585f-8b32-0ac3082f2282 already exists.).
...
```

Each of the event 0 events seems to be a place where the next System.Net library woke up and tried logging something, and then that event source never gets activated due to a duplicate registration.

Looks to be true for both Windows and Linux.

**Comment by stephentoub** [comment]
cc: @josguil 

This is likely due to the System.Net components using the same name and guid for multiple copies of the same EventSource just in different components.  See @vancem's detailed response to that practice here:
https://github.com/dotnet/corefx/pull/5151#issuecomment-169182270

**Comment by CIPop** [comment]
This is known and expected. We won't fix this for RTM given that logman / PerfView collection works as expected.

**Comment by stephentoub** [comment]
I'm not sure it does work as expected (I'm fairly certain I've seen PerfView not get the desired events, though I'd need to double check).  Regardless, though, the Unix tracing also plugs in through the listener mechanism, so if that's broken, so is tracing on Unix.

**Comment by davidsh** [comment]
I have a feeling that we need to fix this especially given @vancem previous comments on the initial design. The problem right now is resource staffing to fix this.

**Comment by CIPop** [comment]
> I'm fairly certain I've seen PerfView not get the desired events, though I'd need to double check

@stephentoub If events are missing then I agree this needs to be fixed for RTM.

**Comment by bartonjs** [comment]
@CIPop Yes, events are missing.  For the shared event sources, only the first library to try logging emits events, the other libraries are silent.

**Comment by stephentoub** [comment]
@joshfree, @cipop, I suggest this be brought back to 1.0.0-rtm.  I'm not sure why/when this got moved to 1.1.0.

**Comment by davidsh** [comment]
It was originally pushed out to Future when there wasn't a 1.1 milestone. Our team's resources are constrained and the triage decisions were made based on the RC1/2/3 and RTM dates at that time.

Some of these dates have moved now. We should discuss offline balancing the importance of this particular work vs. the available resources.

**Comment by CIPop** [comment]
I agree with getting this done by RTM. I've moved it when it wasn't clear that events were missing.

**Comment by CIPop** [comment]
It's unlikely we can get to this in time for RTM.
