### ISSUE TITLE
Sockets logging emits an argument/parameter count mismatch error

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#5757]
Given the ConsoleEventLogger from #5755, lots of errors seem to be emitted from Sockets logging:

```
Event Microsoft-System-Net-2  (System.Net.Sockets.Socket, 55915408, Receive, System.Int32, 5, 0).
Event Microsoft-System-Net-1  (System.Net.Sockets.Socket, 55915408, Receive, , 0, 0).
Event Microsoft-System-Net-Sockets-0  (Event 5 was called with 3 argument(s), but it is defined with 2 parameter(s).).
Event Microsoft-System-Net-Sockets-5  (System.Byte[], Receive).
```

**Comment by bartonjs** [comment]
I see that on both Windows and Linux, by the way.

**Comment by stephentoub** [comment]
cc: @josguil

**Comment by CIPop** [comment]
Thanks @bartonjs. Looked at the code and for the DumpArray eventId (5), it looks like we're passing an extra argument: the pointer value.

**Comment by CIPop** [comment]
@bartonjs I've discussed this with @josguil: he used the pattern from:
https://github.com/dotnet/coreclr/blob/43b39a73cbf832ec13ec29ed356cb75834e7a8d7/src/mscorlib/src/System/Diagnostics/Eventing/EventSource.cs#L983

We've also tested this in PerfView and couldn't find any issues.

**Comment by CIPop** [comment]
@vancem can you please point us to documentation/examples on how to use `WriteEventCore` with an array? 

As an optimization we'd need to pass in the offset and length and adjust the pointer passed to `EventData`. Adding these extra parameters to a method marked with the `EventAttribute` will surface the errors @bartonjs reported as well.

Code in question:
https://github.com/dotnet/corefx/blob/ac67ffac987d0c27236c4a6cf1255c2bcbc7fe7d/src/Common/src/System/Net/Logging/SocketsEventSource.cs#L171

**Comment by stephentoub** [comment]
This looks like https://github.com/dotnet/coreclr/issues/1991

**Comment by CIPop** [comment]
Thanks @stephentoub: it seems the same. 
We either pass the size first then a pointer to the array or we get an error when we decode the data in PerfView.

**Comment by CIPop** [comment]
This appears to have been fixed in dotnet/coreclr#1991.

To ensure that it actually did fix the issue, I'd like to try to create an automated test for this.

**Comment by karelz** [comment]
Next step: Write tests for logging

**Comment by stephentoub** [comment]
> To ensure that it actually did fix the issue, I'd like to try to create an automated test for this.

We already have one:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/tests/FunctionalTests/LoggingTest.cs#L57
