### ISSUE TITLE
ObjectDisposedException on OpenSSL when connecting to SQLAzure on Unix

### ISSUE THREAD

**Issue by kkurni** [dotnet/corefx#5763]
I notice SSLStream (OpenSSL) on Unix throws ObjectDisposedException after finish connecting on SqlAzure on Unix.

(There is no exception on Prem).

This may be related with issue on Mac as well. On Mac, it throws RemoteCertificateNameMismatch.
https://github.com/dotnet/corefx/issues/5173

![image](https://cloud.githubusercontent.com/assets/698547/12663551/fe2abc94-c5dd-11e5-9f22-be1775c8df01.png)

```
Unhandled Exception: System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Ssl.SslShutdown(SafeSslHandle ssl)
   at Interop.OpenSsl.Disconnect(SafeSslHandle context)
   at System.Net.Security.SafeDeleteContext.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
   at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
   at System.Runtime.InteropServices.SafeHandle.Finalize()
[1]    24788 abort (core dumped)  ./corerun xunit.console.netcore.exe System.Data.SqlClient.Tests.dll -class
```

**Comment by kkurni** [comment]
CC @saurabh500 @vijaykota @joshfree @stephentoub

**Comment by joshfree** [comment]
@bartonjs PTAL
/cc @ericeil

**Comment by bartonjs** [comment]
@kkurni The xunit command looks to be a bit cut off... is there a test case already in the suite that I can use for repro, or is it something you were developing locally?

**Comment by kkurni** [comment]
@bartonjs this is just my internal tests. It is very simple tests.
You can copy paste this code with inside any XUnit Tests.

```
 [Fact]
        public void TestSqlAzure()
        {
            TestConnectionString("Server=tcp:xxxxxxx.database.windows.net,1433; Database=xxxx; User ID=xxxx; Password=xxx; Connection Timeout = 30;Encrypt=True;TrustServerCertificate=False;");
        }


        public void TestConnectionString(string connstr)
        {
            using (var conn = new SqlConnection(connstr))
            {
                Console.WriteLine("BEFORE CONN OPEN : {0}.  Press any key to continue.", connstr);
                Console.ReadLine();
                conn.Open();
                Console.WriteLine("AFTER CONN OPEN. Press any key to continue.");
                Console.ReadLine();
                
                Console.WriteLine("create command...");
                var cmd = new SqlCommand("select @@Version", conn);

                Console.WriteLine("Execute reader...");
                using (var reader = cmd.ExecuteReader())
                {

                    Console.WriteLine("read...");
                    while (reader.Read())
                    {
                        Console.WriteLine(reader.GetString(0));
                    }
                }
                
            }
        }
```

Here is my command to run the test as well.
![image](https://cloud.githubusercontent.com/assets/698547/12663854/4c872042-c5e0-11e5-8296-8abfb6224af4.png)


Apparently this error happens after XUnit Finished running the tests after it print 
=== TEST EXECUTION SUMMARY ===
![image](https://cloud.githubusercontent.com/assets/698547/12663875/6e7ea86e-c5e0-11e5-9a4e-58474aaa0efd.png)


If it is connected to sql server box, there is no error.

When connecting to SQL Azure,
In Mac, we get SSL Cert Validation Error during SSLStream RemoteCertificateValidationCallback (Because of Policy Error : RemoteCertificateNameMismatch)
https://github.com/dotnet/corefx/issues/5173

In Unix, we don't get this Cert error and it can connect fine. But after XUnit finished executed, it give me this error exception.

In Windows, the same tests to SQL Azure are fine.

**Comment by bartonjs** [comment]
@kkurni Hmm, what build are you using?  I noticed that the callstack here has `Interop.Ssl.SslShutdown(SafeSslHandle)`, but that changed to `Interop.Ssl.SslShutdown(IntPtr)` back in November... for a strikingly-similar issue: https://github.com/dotnet/corefx/issues/4480.

**Comment by kkurni** [comment]
hmm. it seems similar. Let me rebase my branch and hopefully this won't be appear anymore.

Thanks

**Comment by bartonjs** [comment]
@kkurni Since this seems like it's just #4480, I'm going to go ahead and close the issue.  If you're still seeing weird problems after moving forward, please let us know :smile:.

**Comment by joshfree** [comment]
Testing on a 2 month old build will definitely find bugs that have long since been fixed...  Can you make sure the entire Data team moves forward to the latest builds -- otherwise this would be an easy way to waste time.

**Comment by kkurni** [comment]
Sure. I will make sure to get the latest build before creating issue.
