### ISSUE TITLE
ContinueWhenAll(...).AsyncState not null

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#5769]
This is... at least a little surprising:
```
Action<Task[]> a = _ => { };
Assert.Same(a, new TaskFactory().ContinueWhenAll(new[] { new Task(() => { }) }, a).AsyncState);
// Async state is the continuation action?  Huh?
```
... succeeds (as does `ContinueWhenAny(...)`).

Continuations created via non-state `ContinueWith(...)` have `AsyncState == null`, as do regular tasks and futures.

There's no version of `ContinueWhenAll(...)`/`ContinueWhenAny(...)` that takes a state, so I was expecting it to always be null.  The documentation doesn't mention `AsyncState` in these methods, so I'm not sure what the behavior is supposed to be.

**Comment by JonHanna** [comment]
It would seem to simply be an implementation detail. Does it cause any problems? If not then it would probably be best just to assume that maybe someone somewhere depends on this, and leave it as-is.

**Comment by stephentoub** [comment]
> It would seem to simply be an implementation detail.

Yes, it's an optimization that allows the system to avoid an extra allocation or a larger allocation by simply passing the continuation function as the state.  This is by design.
