### ISSUE TITLE
which version of dotnet spec is supported by current corefx impl. ?

### ISSUE THREAD

**Issue by chunseoklee** [dotnet/corefx#5771]
As in the title, question is that which version of dotnet spec is supported by corefx ?
For example, Mono site(http://www.mono-project.com/docs/about-mono/compatibility/) describes compatibility to dotnet spec. 
I cannot find such material. 
Please help me.

**Comment by Maxwe11** [comment]
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md#mapping-the-net-platform-standard-to-platforms

**Comment by ericstj** [comment]
These docs are here: https://docs.microsoft.com/en-us/dotnet/articles/standard/library
