### ISSUE TITLE
Where is DbProviderFactories???

### ISSUE THREAD

**Issue by giancarloa** [dotnet/corefx#5782]
Hi... in NET451 we have this class called DbProviderFactories that has a method called GetFactory that allows clients to obtain a DbProviderFactory given a connection... I am trying to port to NETCORE50 and I don't see DbProviderFactories although I do see DbProviderFactory... are there plans to include DbProviderFactories in NETCORE50? or is there another generic way in NETCORE50 to obtain a connection's DbProviderFactory? thank you

//
        // Summary:
        //     Returns an instance of a System.Data.Common.DbProviderFactory.
        //
        // Parameters:
        //   connection:
        //     The connection used.
        //
        // Returns:
        //     An instance of a System.Data.Common.DbProviderFactory for a specified connection.
        public static DbProviderFactory GetFactory(DbConnection connection);

**Comment by joshfree** [comment]
@saurabh500 @YoungGah

**Comment by eschneider999** [comment]
I built my own plugin base factory. I have 5 database provider libraries that implement an interface, which is discovered at run time. I have not tested on any other platforms, but works on windows/pcl.
[](https://www.nuget.org/packages?q=symbiotic+data+provider)

I can provide the dynamic discovery code if someone is interested.

**Comment by kkurni** [comment]
Related issue : https://github.com/dotnet/corefx/issues/4571

**Comment by danmosemsft** [comment]
Closing in favor of #4571
