### ISSUE TITLE
Have dotnet-bot automatically submit PRs for package updates

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#5789]
We should have @dotnet-bot automatically do https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/project-nuget-dependencies.md#upgrading-a-package-dependency when new packages are available and submit a PR.

/cc @stephentoub @dagood @markwilkie

**Comment by mellinoe** [comment]
Sounds reasonable, how often would we want the update to happen, though? Every day?

**Comment by ericstj** [comment]
Whenever new packages are available so yeah daily.  We'd want to at least submit the PR.  We would only merge it if the CI was successful.

**Comment by Priya91** [comment]
Yup! +1

**Comment by ellismg** [comment]
@weshaggard Has a script that does this, FWIW.

**Comment by weshaggard** [comment]
Yes I have a script that does this already and I'm planning to hook it up as a post step for publishing our daily packages.

**Comment by weshaggard** [comment]
@eerhardt is working on completing this.

**Comment by eerhardt** [comment]
Closing.  This is now completed.  See:

https://github.com/dotnet/corefx/pull/7502
https://github.com/dotnet/corefx/pull/7510

The script to update the dependencies is located here:  https://github.com/dotnet/corefx/blob/master/UpdateDependencies.ps1
