### ISSUE TITLE
System.Globalization.Extensions.Tests fail on Windows 7

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#579]
On Win7 (7601) the globalization extensions have several failures:

System.Globalization.Extensions.Tests.IdnaConformanceTests.TestAsciiPositive [FAIL]
    System.ArgumentException : Decoded string is not a valid IDN name.
    Parameter name: Unicode

System.Globalization.Extensions.Tests.IdnaConformanceTests.TestUnicodePositive [FAIL]
    Expected: <+á.+É¦ê>. Actual:<xn--0ca.xn--ssa73l>. Error on line number 61

System.Globalization.Extensions.Tests.IdnaConformanceTests.TestAsciiNegative [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   (No exception was thrown)

System.Globalization.Extensions.Tests.NormalizationAll.NormalizeTest [FAIL]
    Assert.False() Failure
        (many lines like "'\x0068' is not matched with the normalized form '\x2095 with Géò normalization")

**Comment by ellismg** [comment]
These are passing now.
