### ISSUE TITLE
MSBuild gives spurious conflict warning when referencing new CoreFX packages in net46 project

### ISSUE THREAD

**Issue by agocke** [dotnet/corefx#5796]
/cc @ericstj 

E.g. when referencing System.Runtime from -23504,

```
 C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190.
```

@davkean Explained that this warning is incorrect as fusion will automatically unify these references at runtime.

In addition, if you actually follow the warning's advice and add the binding redirects, those take precedence over the fusion unification and the exe will fail at runtime.

**Comment by ericstj** [comment]
Thanks for the report @agocke.  I didn't realize you had opened this and opened https://github.com/dotnet/corefx/issues/5842.  Closing this now.
