### ISSUE TITLE
System.Xml.XmlNodeReader is not Available in .Net Core

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#5800]
This API is not available in .Net Core. https://github.com/dotnet/wcf/issues/702 is being blocked by this issue.

**Comment by shmao** [comment]
@sepidehMS Any updates on this? I see the milestone is being set to 1.1.0. Will System.Xml.XmlNodeReader be added in 1.1.0?

**Comment by krwq** [comment]
Hello @shmao, we are currently working on bringing back all System.Xml APIs. For now if possible please simply copy the source code into your project

**Comment by sepidehMS** [comment]
I'm closing this as it is currently being worked on and is tracked by #11888.
