### ISSUE TITLE
TestProcessStartTime failed on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5805]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug/420/
```
22:25:46   Discovering: System.Dynamic.Runtime.Tests
22:25:46      System.Diagnostics.Tests.ProcessTests.TestProcessStartTime [FAIL]
22:25:46         Assert+WrapperXunitException : File path: d:\j\workspace\dotnet_corefx\windows_nt_debug\src\System.Diagnostics.Process\tests\ProcessTests.cs. Line: 404
22:25:46         ---- Assert.InRange() Failure
22:25:46         Range:  (635901169911736243 - 635897320032916240)
22:25:46         Actual: 635897320032696307
22:25:46   System.Globalization.Extensions -> d:\j\workspace\dotnet_corefx\windows_nt_debug\bin\Windows_NT.AnyCPU.Debug\System.Globalization.Extensions\System.Globalization.Extensions.dll
22:25:46         Stack Trace:
22:25:46            d:\j\workspace\dotnet_corefx\windows_nt_debug\src\Common\tests\System\Diagnostics\AssertWithCallerAttributes.cs(583,0): at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber)
22:25:46            d:\j\workspace\dotnet_corefx\windows_nt_debug\src\Common\tests\System\Diagnostics\AssertWithCallerAttributes.cs(226,0): at Assert.InRange[T](T actual, T low, T high, String path, Int32 line)
22:25:46            d:\j\workspace\dotnet_corefx\windows_nt_debug\src\System.Diagnostics.Process\tests\ProcessTests.cs(404,0): at System.Diagnostics.Tests.ProcessTests.TestProcessStartTime()
```

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug_prtest/1606/

**Comment by stephentoub** [comment]
And here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug_prtest/1609/

**Comment by stephentoub** [comment]
The ```TestStartTimeProperty``` test is also now failing on Unix, e.g.
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/ubuntu_release_tst_prtest/1361/
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/opensuse13.2_debug_tst_prtest/784/
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/centos7.1_debug_tst_prtest/1320/

**Comment by Priya91** [comment]
The failures are different, the windows one is on Process start time, and the Unix ones are on ProcessThread start times. The Unix failures could be that the thread started after reading the utcnow values, as the code is taking the afterTicks value before reading the thread starttime.
