### ISSUE TITLE
HttpClient doesnt expose the correct method as virtual

### ISSUE THREAD

**Issue by nishantkagrawal** [dotnet/corefx#5819]
I want to extend HttpClient class to create a wrapper over it. The problem is that it doesnt have the right method exposed as virtual.

The following method should be virtual.

```
public Task<HttpResponseMessage> SendAsync(
		HttpRequestMessage request,
		HttpCompletionOption completionOption,
        CancellationToken cancellationToken)
```

		
Moreover, the following method should be new because it actually hides the implementation of the base method.		
```
public override Task<HttpResponseMessage> SendAsync(
		HttpRequestMessage request,
        CancellationToken cancellationToken)        
```

**Comment by davidsh** [comment]
`HttpClient.SendAsync` method is PUBLIC and NOT virtual by-design.  The design of HttpClient is that "extending" it is done via the HttpMessageHandler class.

The default "handler" for HttpClient is HttpClientHandler.  That handler is derived from HttpMessageHandler which has the virtual protected SendAsync method.  

In general, "extending" HttpClient is done by creating a new message handler, usually derived from HttpMessageHandler. In fact, the best class to look at is the DelegatingHandler class.  That class has built-in support for creating a new handler and then chaining to the base HttpClientHandler class which has the actual HTTP stack for transmitting/receiving on the wire.

Please take a look at the following article.  While it is targeted at Windows UWP developers, it discusses in detail the System.Net.Http API and the use of message handlers:

https://blogs.windows.com/buildingapps/2015/11/23/demystifying-httpclient-apis-in-the-universal-windows-platform/
