### ISSUE TITLE
XmlElementAttributes.Remove doesn't throw on missing element

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#5831]
On Desktop this method is provided by CollectionBase, which throws when it can't find the element to remove: http://referencesource.microsoft.com/#mscorlib/system/collections/collectionbase.cs,147.

The implementation in CoreFx defers to ArrayList, which does not exhibit the same exception pattern on Remove.

**Comment by bartonjs** [comment]
This would also apply to other formerly-CollectionBase collections:
* XmlArrayItemAttributes
* XmlAnyElementAttributes
* SchemaImporterExtensionCollection
* XmlSchemaObjectCollection

**Comment by joshfree** [comment]
@sepidehMS PTAL

**Comment by khdang** [comment]
@bartonjs Are there any scenarios that is impacted because of this behavior difference?

**Comment by bartonjs** [comment]
It could cause compat issues for libraries targeting the generic RID which are used on both core and desktop.  (If they don't guard against the exception because it doesn't happen in core).

Really it's just "a user-visible compatibility change"
