### ISSUE TITLE
System.Net.Sockets.Tests.DualMode.AcceptV6BoundToSpecificV4_CantConnect hangs on Unix

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#5832]
With PR #5472, System.Net.Sockets.Tests.DualMode.AcceptV6BoundToSpecificV4_CantConnect hangs because it expects `Socket.Dispose` to unblock a synchronous call to `Socket.Accept`.  Closing a socket does not cancel a blocking operation on Unix OSs.

**Comment by ericeil** [comment]
Note that calling `shutdown` on the socket prior to closing it seems to unblock the pending `accept` on Linux.  But it causes an error on OSX and Windows.  I haven't found a way to unblock a pending accept on OSX, other than to simply successfully connect to the socket.

**Comment by stephentoub** [comment]
Does a signal cause it to wake up with EINTR?

**Comment by ericeil** [comment]
Fixing this with signals may be an option.  Moving this to "future" for now; I'm not sure this is something we actually need to fix (depends on how much existing code depends on Dispose for cancellation).

**Comment by ericeil** [comment]
See https://github.com/dotnet/corefx/issues/5749#issuecomment-215597396.  Turns out closing a managed Socket while there are pending synchronous operations isn't really supported on Windows either.  Let's not complicate the x-plat implementation to support this.
