### ISSUE TITLE
ParallelEnumerable.Range(...).AsOrdered().Concat(...) ...out of order

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#584]
I'm getting a pretty distressing error:

    int leftSize = 4;
    int rightSize = 4;
    int[] leftData = new int[leftSize];
    for (int i = 0; i < leftSize; i++) leftData[i] = i;
    int[] rightData = new int[rightSize];
    for (int i = 0; i < rightSize; i++) rightData[i] = i;

    ParallelQuery<int> query = ParallelEnumerable.Range(0, leftSize).AsOrdered().Concat(ParallelEnumerable.Range(0, rightSize));

    Assert.True(leftData.Concat(rightData).SequenceEqual(query));

...fails.  The expected sequence is `[0, 1, 2, 3, 0, 1, 2, 3]`, and the actual result of this `Concat(...)` is `[0, 0, 1, 1, 2, 2, 3, 3]`.  Adding `AsOrdered()` to the inner range has no effect.  There is no history of changes for `Concat(...)`, although the actual problem may be elsewhere.  This issue is **NOT** present in the current .NET distribution (ie, creating a brand-new C# project won't reproduce the error, this is something happening in corefx, which is a really good thing)/

Generating the parallel sequence via `Enumerable.Range(...).AsParallel().AsOrdered()` _also_ fails, but seems to be putting the elements in non-deterministic order (the last run was `[0, 1, 1, 2, 2, 3, 0, 3]`).

However, generating the sequence via `leftData.AsParallel().AsOrdered().Concat(leftData.AsParallel())` returns the expected sequence (both of them have to be generated via backing arrays, or you get the re-ordered or non-deterministic results).

`ParallelEnumerable.Range(...).AsOrdered()` _does_ return an ordered sequence.  The following test succeeds:  

    int count = 8;
    ParallelQuery<object> elements = ParallelEnumerable.Range(0, count).AsOrdered().Select(x => (object)x);

    int counter = 0;
    Assert.All(elements.Cast<int>(), x => Assert.Equal(counter++, x));
    Assert.Equal(count, counter);

**Comment by stephentoub** [comment]
@Clockwork-Muse, thank you very much for finding and reporting this.  I believe I found the problem and submitted a PR to fix it (#585).

@weshaggard, @AlfredoMS, I know it's on your radar, but we really need to get back to the more generic implementation as quickly as possible.  Not only are there the performance implications we've previously discussed, but as is demonstrated by this bug, the lack of strong typing in certain areas now allows difficult-to-find bugs like this to creep in.

**Comment by Clockwork-Muse** [comment]
Actually, the current tests _are_ reporting this (`ParallelQuery.cs`), but given the way the error is being reported (because of how the tests are written...), it's difficult to figure out what it's complaining about.  Well, that, and those particular tests are "commented out" (`[KnownIssue(235)]`), so aren't being run as part of the overall build.  Since I'm just compiling and running tests for one project, I wasn't excluding anything...

I'm in these tests anyways to fix the general test setup, so I'm going to add "source" tests (from an array, `Enumerable`, and `ParallelEnumerable`.  Maybe something else?), which should help spot stuff like this in the future.

**Comment by stephentoub** [comment]
Ugh, I didn't know those tests were disabled, and they were disabled apparently exactly because of this bug, as well as another that I just fixed in the same PR in Union.  With both of those fixed, the test passes, so the PR (#585) removes the ActiveIssue from the test to reenable it.

**Comment by stephentoub** [comment]
Fixed with #585.  Thanks, again, for reporting this.

**Comment by Clockwork-Muse** [comment]
@stephentoub - related question -
the documentation for `Concat` states:

    4287         /// <summary> 
    4288         /// Concatenates two parallel sequences. 
    4289         /// </summary> 
    4290         /// <typeparam name="TSource">The type of the elements of the input sequences.</typeparam> 
    4291         /// <param name="first">The first sequence to concatenate.</param> 
    4292         /// <param name="second">The sequence to concatenate to the first sequence.</param> 
    4293         /// <returns>A sequence that contains the concatenated elements of the two input sequences.</returns> 
    4294         /// <exception cref="T:System.ArgumentNullException"> 
    4295         /// <paramref name="first"/> or <paramref name="second"/> is a null reference (Nothing in Visual Basic). 
    4296         /// </exception> 

...which suggests to me that _unordered_ sequences should still exhibit A-then-B behavior (not helped any by the line above it that says: `Appends the second data source to the first, preserving order in the process.`...).  That is, this:

    int leftSize = 4;
    int rightSize = 4;
    int[] leftData = new int[leftSize];
    for (int i = 0; i < leftSize; i++) leftData[i] = i;
    int[] rightData = new int[rightSize];
    for (int i = 0; i < rightSize; i++) rightData[i] = i;

    ParallelQuery<int> query = ParallelEnumerable.Range(0, leftSize).Concat(ParallelEnumerable.Range(0, rightSize));

...should yield `[all-elements-of-leftData, all-elements-of-rightData]` (I'm not expecting the elements on each side to be ordered themselves).

Is my thinking correct, or is the documentation just leading me astray me?  Maybe I'm just hung up on the use of `Concat` for strings...

**Comment by Clockwork-Muse** [comment]
@stephentoub - Unless I've got a broken mental model again, this appears to still be broken (for `Enumerable` and `Partitioner` sourced queries, anyways).
It was my assumption that the output of one of the ordering operators (ie, `OrderBy(...)`) should produce the same results that `AsOrdered()` does, that: 

    int leftSize = 4;
    int rightSize = 4;
    int[] leftData = new int[leftSize];
    for (int i = 0; i < leftSize; i++) leftData[i] = i;
    int[] rightData = new int[rightSize];
    for (int i = 0; i < rightSize; i++) rightData[i] = i;

    ParallelQuery<int> query = ParallelEnumerable.Range(0, leftSize).Concat(Enumerable.Range(0, rightSize).AsParallel().OrderBy(x => x));

    Assert.True(leftData.Concat(rightData).SequenceEqual(query));

...should pass.  That there's effectively an implicit `AsOrdered()` attached to all the ordering operators. And if ordering is applied, that `Concat` treats the not-specifically-ordered section as if `AsOrdered()` was used on it.  Currently, if the _right_ side (not the left one, so far) is ordered via one of the ordering operators, it's failing.

Even if only the specifically ordered section should be returned ordered, I'm still getting something that seems strange to me: items from an ordered right side are occurring out of order.  This behavior is also observable on the current consumer release.  Strangely, the **unordered** side is returned completely ordered; it's only the **ordered** side that has elements in a different order...

**Comment by svick** [comment]
@Clockwork-Muse You're concatenating an unordered sequence (`Range`) and an ordered sequence (`OrderBy`), so I think it makes sense that the result is unordered.

[The documentation](https://msdn.microsoft.com/en-us/library/dd460677) says that the result of `Concat` is ordered when "the source sequence" is ordered and unordered when "the source sequence" is unordered. It's not clear to me what exactly does "the source sequence" mean when `Concat` has *two* source sequences, but requiring both of them to be ordered seems logical to me.

(I think the documentation of PLINQ in general, and its methods in particular, could use a lot of expanding, too bad it's not open source.)

**Comment by Clockwork-Muse** [comment]
@svick - So what would happen in the case that only one sequence is ordered?  Only order that portion of the output sequence (like `Union`), or leave the whole thing unordered?  The way I'm reading the start of the concat operator's implementation makes it seem like output should be ordered if either input is.

**Comment by svick** [comment]
@Clockwork-Muse I don't know. Since I think the documentation doesn't guarantee anything like that, I would expect the whole result to be unordered. But I didn't look at the implementation.

**Comment by Clockwork-Muse** [comment]
Heh.  Well, I need to know, so I can change or comment the appropriate tests.



On Fri, Mar 13, 2015 at 4:08 PM -0700, "Petr Onderka" <notifications@github.com> wrote:
@Clockwork-Muse I don't know. Since I think the documentation doesn't guarantee anything like that, I would expect the whole result to be unordered. But I didn't look at the implementation.

---

**Comment by Clockwork-Muse** [comment]
@svick , the implementation has:

    _outputOrdered = LeftChild.OutputOrdered || RightChild.OutputOrdered;

... which I've been reading as if either source is ordered, the output will be.
Thinking about what I am seeing though, something needs to be changed:

 1. If both would need to be ordered, the current implementation is doing work it doesn't/shouldn't have to.
 2. If only that portion of the results should be ordered, it's clearly not doing that (bug)
 3. If the entire thing should be ordered, it's failing because of the problem with 2.

..am I missing anything here?
@stephentoub  - do you have any direction for me here?
