### ISSUE TITLE
System.Data.ProviderBase.DbConnectionFactory.TryGetConnection() has a misleading comment for use of Sleep()

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/corefx#5840]
`System.Data.ProviderBase.DbConnectionFactory.TryGetConnection()` has these lines:

```
// Yield time slice to allow shut down activities to complete and a new, running pool to be instantiated
//  before retrying.
Threading.Thread.Sleep(timeBetweenRetriesMilliseconds);
timeBetweenRetriesMilliseconds *= 2; // double the wait time for next iteration
```

`timeBetweenRetriesMilliseconds` starts with a value of `1` and is doubled on each iteration. "yield time slice" is the idiom for passing zero into `Sleep()` to mean "I don't want to wait for long, but if there's anyone else wanting CPU time then I'll let them have that time". When any other value is passed that actual wait, not "yielding time slice".

**Comment by JonHanna** [comment]
You need a value of at least `1` to yield to a thread with lower priority than the thread that is yielding, so `1` is also commonly used when one just wants to yield the time slice.

I think the combination of comments is reasonable. First it yields, and then it doubles before subsequent waits.

**Comment by karelz** [comment]
This looks like nit picking - in such case, please just submit PR with changes, we will review them there.
Closing for now as single line comment changes are not worth tracking in issues.
