### ISSUE TITLE
System.Data.SqlClient.SqlConnection.TryOpen() registers an object without finalizer for finalization

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/corefx#5841]
System.Data.SqlClient.SqlConnection.TryOpen() has this code

    if (!tdsInnerConnection.ConnectionOptions.Pooling)
    {
        // For non-pooled connections, we need to make sure that the finalizer does actually run to avoid leaking SNI handles
        GC.ReRegisterForFinalize(this);
    }

but `SqlConnection` has no finalizer and neither does its base class. This code does nothing useful. If some magic must be run then this won't help.

**Comment by JonHanna** [comment]
It's the other way around, the bug is that the derived class doesn't have a finaliser, since this class does indeed make use of that. See #5861.
