### ISSUE TITLE
Implement CustomReflectionContext

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/corefx#5844]
I was just browsing through the source here and I noticed that `System.Reflection.Context.CustomReflectionContext` is not implemented.  One of the projects I work on (RobotDotNet) uses this in our library for some additional nice features.

**Comment by danmosemsft** [comment]
Note to self: on desktop this in in  System.Reflection.Context.dll

**Comment by karelz** [comment]
Next step: Will be likely implementable based on ReferenceSource.
Medium complexity. Key thing: Understand what it was originally design for.
