### ISSUE TITLE
DbEnumerator is included in both System.Data.Common and System.Data.SqlClient

### ISSUE THREAD

**Issue by divega** [dotnet/corefx#5848]
SqlClient shares some code with System.Data.Common by including source files in https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System.Data.SqlClient.csproj#L49-L59. Of all code shared at least `DbEnumerator` is a public type, so when you depend on both libraries the type is duplicated.  

I don't think this has a huge impact but I was wondering if it is just an oversight. 

cc @saurabh500

**Comment by divega** [comment]
(fixed the link to point to master)

**Comment by joshfree** [comment]
moving this to the RTM milestone.
/cc @YoungGah

**Comment by saurabh500** [comment]
We have fixed this as a part of the #4646 fix.
