### ISSUE TITLE
Port changes to Microsoft.Cci.Extensions

### ISSUE THREAD

**Issue by venkat-raman251** [dotnet/corefx#5859]
Update the changes from corefxTools\Microsoft.Cci.Extensions to buildTools\Microsoft.Cci.Extensions

**Comment by mellinoe** [comment]
Did you mean to put this in the buildtools repo?

**Comment by venkat-raman251** [comment]
@mellinoe Oh, yes. Will create one in buildtools and mark this as duplicate

**Comment by venkat-raman251** [comment]
Created in buildTools. Closing this one.
