### ISSUE TITLE
DbConnection and DbCommand should have a finaliser

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#5861]
Originally `DbConnection` and `DbCommand` classes were derived from `System.ComponentModel.Component`. From that they inherited a finaliser that called `Dispose(false)`.

Their descendants sometimes depend on this, in particular `SqlConnection` has finaliser-only code.

They should have finalisers directly added.

~~`DbTransaction` and `DbDataReader` were never derived from `Component` but do both follow the `Dispose(bool)` pattern, as such suggesting that a finaliser exists which would call `Dispose(false)`. While not used within the corefx assemblies a third party derived class could erroneously depend on this.~~

~~As such they should have finalisers added, and then suppressed in the existing derived classes.~~ (Moved this part to #5865)

**Comment by adamsitnik** [comment]
IMHO it is a good fix, but not the best way to solve the problem.

I would rather encourage developers to use SafeHandle class when dealing with native resources. Safe Handle has it's own finalizer, so classes that are using it do not need to have their own finalizers.  Less GC pressure, no "mid-life crysis" and still safe. Even more safe if we take CriticalFinalizerObject (base class of SafeHandle) special treatment  into account. .NET Core has changed some very common APIs that all devs were used to, so the lack of finalizers (which would also remove the need of Dispose(bool) method) should not be a problem.

It is of course only my opinion and I believe that it is great that you found this inconsistency.

**Comment by JonHanna** [comment]
Yeah, I don't like the pattern at all (I'd go so far as to call it an anti-pattern, because while it solves the problem of mixing managed and unmanaged clean-up in one class, I'd rather not get into that position in the first place).

But unless it broke from the pattern and hence forced derived classes to change with the full break (nasty!) it would be very easy to expect the finaliser and not have it, as indeed SqlConnection does. There's nothing to say SafeHandle can't still be used in a derived class after all.
