### ISSUE TITLE
CI jobs failing with WS-CLEANUP errors

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5864]
Lots of legs failing with errors like this,
e.g. http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_bld_prtest/495/console
```
ERROR: [WS-CLEANUP] Cannot delete workspace: remote file operation failed: d:\j\workspace\dotnet_corefx\osx_release_bld_prtest at hudson.remoting.Channel@270f3ae7:dci-win-tbld-6: java.nio.file.AccessDeniedException: d:\j\workspace\dotnet_corefx\osx_release_bld_prtest\Tools\dotnetcli\bin\coreclr.dll
```

**Comment by mmitche** [comment]
@stephentoub Thanks, if you see more of these can you let me know.  I'm unsure of why the process killer didn't work in this case.

**Comment by mmitche** [comment]
I have a hunch that it was a veto killer plugin that was avoiding killing MSBuild (for multi-executor instances of windows), so I uninstalled that.  It's possible it's something else though.  I'll keep watching.
