### ISSUE TITLE
Debugger.NotifyOfCrossThreadDependency missing from System.Diagnostics.Debug contract

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5868]
NotifyOfCrossThreadDependency is used in code any time a debugger accessing that property would potentially cause deadlocks, race conditions, or other behavior changes, e.g. if the debugger has frozen all threads in the process (which it does at a breakpoint), and a property getting evaluated blocks waiting for another thread to perform some operation.

We should expose this in the contract.  If the runtime is built for a platform that doesn't support it, it can simply be a nop.

**Comment by terrajobst** [comment]
Seem very reasonable to me.

@weshaggard @KrzysztofCwalina

**Comment by weshaggard** [comment]
agreed.

**Comment by terrajobst** [comment]
Sounds good. Since there is no push back, I'm marking this API as approved as proposed.

**Comment by terrajobst** [comment]
@stephentoub, are you going to add the API? If not, @weshaggard, who should be taking care of it? I don't think it should be assigned to me :smile:

**Comment by stephentoub** [comment]
Moving to 1.1 to add back along with other members of Debugger.

**Comment by joperezr** [comment]
@stephentoub is this done? if so, can we close?
