### ISSUE TITLE
Untangle FileStream's async implementation

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#587]
In .NET Core, Stream doesn't provide the legacy virtual Begin/EndXx methods, just the XxAsync methods, yet FileStream still implements the Begin/EndXx methods internally with the XxAsync methods wrapping them. This results in what appears to be a non-trivial amount of overhead that's unnecessary. This should be cleaned up to improve both the maintainability and performance of the code.

**Comment by ebickle** [comment]
Fantastic, glad to see this issue listed here!

**Comment by dpaoliello** [comment]
I'm currently looking into this, but I have one question: is USE_OVERLAPPED still relevant?
It seems like it is there for legacy reasons, and as far as I can tell it is always compiled with it set.

**Comment by stephentoub** [comment]
@dpaoliello, it's not set if EnableWinRT is true:
https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System.IO.FileSystem.csproj#L15

**Comment by dpaoliello** [comment]
Thanks @stephentoub, that makes things fun...
Also, feel free to assign this to me - I'm most of the way through the change (I have one race condition between cancellation\starting the IO\receiving the callback to sort out, and putting back in the !USE_OVERLAPPED code path)

**Comment by stephentoub** [comment]
Thanks for working on this, @dpaoliello.

**Comment by stephentoub** [comment]
Closed by #972.
