### ISSUE TITLE
Console support for NETCore

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#5875]
Since Console was added to NETStandard.Library we need to suppoort it on netcore50.

To do this and still pass the WACK we should either:
1. Get the APIs we call added to the modern SDK.
2. Build a version of the contract specific to netcore that only calls supported APIs.  For example, by just using readfile/writefile on the console handles or directing the output to something more appropriate for UWP (EG: debug or etw).

/cc @pallavit @weshaggard

**Comment by pallavit** [comment]
> Since Console was added to NETStandard.Library we need to suppoort it on netcore50.

@ericstj Why does the library need to pass WACK for this? It is not meant to run on UWP at all.

**Comment by ericstj** [comment]
/cc @KrzysztofCwalina 
System.Console is part of the set of libraries that we say every new version of .NET needs to support: the standard library.  As such, libraries may make use of it and those libraries must install in a UWP app without violating WACK.

We need to define what Console should do in this case and implement that behavior.

**Comment by pallavit** [comment]
> As such, libraries may make use of it and those libraries must install in a UWP app without violating WACK.

Console as a concept is not supported on store at all and honestly, I am not sure it makes senses in every UI model either. In the past we worked-around it by using Console only in Developer mode on store and hence removing the WACK compliance limitation.

**Comment by weshaggard** [comment]
Console in this context is StdIn/StdOut which we have agreed to support everywhere, so we should provide the API for UWP, even if it doesn't actually have a console displayed.

**Comment by ericstj** [comment]
Here's the list of unsupported APIs:
```
API GetConsoleCP in api-ms-win-core-console-l1-1-0.dll is not supported for this application type. System.Console.dll calls this API.
API GetConsoleMode in api-ms-win-core-console-l1-1-0.dll is not supported for this application type. System.Console.dll calls this API.
API GetConsoleOutputCP in api-ms-win-core-console-l1-1-0.dll is not supported for this application type. System.Console.dll calls this API.
API ReadConsoleInputW in api-ms-win-core-console-l1-1-0.dll is not supported for this application type. System.Console.dll calls this API.
API ReadConsoleW in api-ms-win-core-console-l1-1-0.dll is not supported for this application type. System.Console.dll calls this API.
API SetConsoleCtrlHandler in api-ms-win-core-console-l1-1-0.dll is not supported for this application type. System.Console.dll calls this API.
API WriteConsoleW in api-ms-win-core-console-l1-1-0.dll is not supported for this application type. System.Console.dll calls this API.
API Beep in api-ms-win-core-util-l1-1-0.dll is not supported for this application type. System.Console.dll calls this API.
API GetStdHandle in api-ms-win-core-processenvironment-l1-1-0.dll is not supported for this application type. System.Console.dll calls this API.
API FillConsoleOutputAttribute in api-ms-win-core-console-l2-1-0.dll is not supported for this application type. System.Console.dll calls this API.
API FillConsoleOutputCharacterW in api-ms-win-core-console-l2-1-0.dll is not supported for this application type. System.Console.dll calls this API.
API GetConsoleCursorInfo in api-ms-win-core-console-l2-1-0.dll is not supported for this application type. System.Console.dll calls this API.
API GetConsoleScreenBufferInfo in api-ms-win-core-console-l2-1-0.dll is not supported for this application type. System.Console.dll calls this API.
API GetConsoleTitleW in api-ms-win-core-console-l2-1-0.dll is not supported for this application type. System.Console.dll calls this API.
API GetLargestConsoleWindowSize in api-ms-win-core-console-l2-1-0.dll is not supported for this application type. System.Console.dll calls this API.
API PeekConsoleInputW in api-ms-win-core-console-l2-1-0.dll is not supported for this application type. System.Console.dll calls this API.
API SetConsoleCursorInfo in api-ms-win-core-console-l2-1-0.dll is not supported for this application type. System.Console.dll calls this API.
API SetConsoleCursorPosition in api-ms-win-core-console-l2-1-0.dll is not supported for this application type. System.Console.dll calls this API.
API SetConsoleScreenBufferSize in api-ms-win-core-console-l2-1-0.dll is not supported for this application type. System.Console.dll calls this API.
API SetConsoleTextAttribute in api-ms-win-core-console-l2-1-0.dll is not supported for this application type. System.Console.dll calls this API.
API SetConsoleTitleW in api-ms-win-core-console-l2-1-0.dll is not supported for this application type. System.Console.dll calls this API.
API SetConsoleWindowInfo in api-ms-win-core-console-l2-1-0.dll is not supported for this application type. System.Console.dll calls this API.
```

**Comment by jasonwilliams200OK** [comment]
Duplicate / Related: https://github.com/dotnet/corefx/issues/4636

**Comment by pallavit** [comment]
As things stand today, we can't support the Console contract as-is and make WACK happy. If we really want to support it on UWP as well, we would need to support a separate contract (w/o encoding and most other features), this would most likely look like the very initial snapshot of Console (possibly further trimmed) version. Also, this will also most likely mean separate implementations for the different versions of the contract as things can't be supported additive. 

Is there a possibility of WACK clearance on this?

**Comment by weshaggard** [comment]
We can inquire about relaxing the WACK checks but even with that we will likely need to do a separate build of this for UWP. I can see some features we we might need to throw PlatformNotSupportedException or no-op but I don't understand why we wouldn't be able to handle the Encoding. We might not be able to get the default Console encoding but we should be able to use a default encoding ourselves for this trimmed down implementation of Console.

**Comment by pallavit** [comment]
> We might not be able to get the default Console encoding but we should be able to use a default encoding ourselves for this trimmed down implementation of Console. 

Yes, we would not be able to support both ANSI and Unicode code pages for Console Read\Write in the WACK compliant set.

**Comment by ianhays** [comment]
Relaxing the WACK check would be quite a bit less work than re-implementing most of Console to work in UWP. Adding the APIs we need to the modern SDK would also be a pretty tall order since we use a **lot** of interop calls that I don't imagine are included in UDP already.

Even then there isn't actually a console, so doing either of the above doesn't make a lot of sense to me. I could see the use case for redirecting stdout to debug, but wouldn't we want people to just directly use Debug in that case to avoid the indirection? And how would we handle stdin?

Implementing `Console` on a platform without a console seems an odd thing to do. Is there evidence that it will be sorely missed if excluded/gutted? Googling doesn't reveal much.

**Comment by weshaggard** [comment]
@danmosemsft this is another set of native dependencies we should ask to get added to the Modern SDK.

**Comment by danmosemsft** [comment]
@weshaggard @ianhays Wes, are you saying that in UWP the console would do nothing by default, but you can wire up Console.SetOut (etc) to get useful behavior? In that case, we don't need most or maybe any of those native API, do we -- just some adjustments to the implementation so it doesn't attempt to initialize itself over the Windows console.

**Comment by weshaggard** [comment]
@danmosemsft that is one option but another option would be to just call the Win32 API's we currently use so we can use the same exact library and not need to have a special build of System.Console just for UWP, but that would require these native dependencies be allowed in UWP. That would make the OS the one responsible for noop'ing these or not.

**Comment by danmosemsft** [comment]
@weshaggard Got it, yes. Because of WACK we can't simply add another codepath, it just won't accept the code. I'll start a thread.

**Comment by joshfree** [comment]
@danmosemsft I'm assuming you're driving this one from here on out
