### ISSUE TITLE
Window chrome ignoring mouse clicks when using TransparencyKey

### ISSUE THREAD

**Issue by Nickesm** [dotnet/corefx#588]
(Not sure if it's the right place to post this kind of issue, but, anyways)

Read this thread: http://stackoverflow.com/questions/20596163/bug-using-transparentkey-and-resizing-form

And perform the steps to get this bug.

**Comment by mikedn** [comment]
I don't think that this belongs here, it's a Windows Form (or DWM) bug. You probably want to post this on [Connect](http://connect.microsoft.com/VisualStudio).

**Comment by patricksadowski** [comment]
Wrong place. Same issue was closed on [roslyn](https://github.com/dotnet/roslyn/issues/185)

**Comment by Nickesm** [comment]
Thanks
