### ISSUE TITLE
Process and Ping should have finaliser

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#5886]
In the wake of #5861 I decided to examine other classes in CoreFX that were originally derived from `Component` to see if there was a risk that classes derived from them in turn could depend upon their having a finaliser.

The following need no action, but I list them in case someone can spot one I missed or a flaw in my reasoning that they are okay as-is:

`ProcessThread`. No longer disposable, functionally sealed (can't be derived as there are no public or protected constructors).

`ProcessModule`. No longer disposable, functionally sealed.

`FileSystemWatcher`. Already has a finaliser.

`PerformanceCounter`. ref only.

This leaves `Process` and `Ping` as two classes that can be derived from, would originally have had a finalizer calling `Dispose(false)` via `Component`, and which do not currently have this. For compatibility with 4.6 and earlier they should have a finalizer.

Further, `ProcessModule` no longer needs one, but still calls `SuppressFinalize` which should be removed as unnecessary.

**Comment by davidsh** [comment]
cc: @CIPop

**Comment by SidharthNabar** [comment]
@JonHanna - thanks for raising this. By `Process`, you mean `System.Diagnostics.Process`, correct? Our team owns `System.Net.Ping`, but not `System.Diagnostics.Process`. Maybe we want to create two separate tracking issues for these two types?  (for easier assignment)

**Comment by JonHanna** [comment]
I do. If you'd prefer to look at one in isolation to the other I'll split the issue and the PR.

**Comment by davidsh** [comment]
@JonHanna There is already a PR for this: #5887.  So, you can leave the issue and PR as-is. It will be reviewed.

**Comment by SidharthNabar** [comment]
Oh - were you planning to submit the PR for both of the types? In that case, it's not needed to split.

**Comment by JonHanna** [comment]
Yes, #5887 covers both. Whether you want to check and (hopefully) okay just part of it, or if you'd rather it was split, I'm happy either way.
