### ISSUE TITLE
WebUtility.UrlDecode to take StringBuilder

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#5888]
`WebUtility.UrlDecode` could take a string builder; `UrlDecoder` could be a struct and use `System.Buffers` for its arrays for reduced allocations.

**Comment by jamesqo** [comment]
@stephentoub Shouldn't this be labeled as an API addition, since it's adding a new public method to a class?

**Comment by davidsh** [comment]
It is labeled ok right now.  Yes, though, in order to move forward with this issue, a properly filed api addition issue must be generated along with design thoughts on how with would align with .NET Framework existing API patterns.

**Comment by davidsh** [comment]
Span<T>, for example, is the new efficient way to pass in these kind of string types instead of StringBuilder. So, closing this issue.  If there are new API proposals that would benefit from using Span<T> in the WebUtility class, then please open a new API proposal issue.
