### ISSUE TITLE
Return more error information for SslStream and NegotiateStream from *Pal.Unix.cs

### ISSUE THREAD

**Issue by vijaykota** [dotnet/corefx#5890]
Please see [PR comment] (https://github.com/dotnet/corefx/pull/5773#commitcomment-15855088). We need to figure a way of passing the extended error information returned by the shim layer to the platform-agnostic code. Currently any exception is translated to SecurityStatusPal.InternalError

**Comment by shrutigarg** [comment]
This got fixed for sslstream in #6750 and the same has been done by @kapilash  for negotiateStream changes in master.

**Comment by stephentoub** [comment]
> and the same has been done by @kapilash for NegotiateStream changes in master

No.  For example, this:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/src/System/Net/NegotiateStreamPal.Unix.cs#L153
hasn't been updated.

**Comment by shrutigarg** [comment]
Will take a look. Thanks

**Comment by shrutigarg** [comment]
Updating this to
_return new Win32Exception(NTE_FAIL, statusCode.Exception.Message); _
will return this win32exception with an appropriate Error message.

**Comment by shrutigarg** [comment]
fix made in commit # 3 of #7647

**Comment by shrutigarg** [comment]
fixed an merged . closing
