### ISSUE TITLE
Plan to create an alternative to xml documentation?

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/corefx#5895]
Hi guys,

I have been following the developments of the .net core initiative on foot for some time now.
As I see a lot of things have been reopened for discussion because of this huge undertaking and refactor.

One thing that I haven't seen in discussions is talk about xml documentation alternatives.
The syntax is just plain verbose and adds a huge amount of noise to what should just be documentation.

In turn an amazing amount of libraries sparingly document around key points of their public api and leave it at that.

The tools have not progressed beyond SandCastle's html generator, and it seems everyone has just taken it as something that is inherent to .Net and we all just have to deal with it no matter how crappy it is.

I propose an alternative syntax just like javadoc, phpdoc, objective-c docs, doxygen etcetera etcetera.
This allows all .net developers to use mostly existing tools (with at most minor adaptations) to create api documentation.  At least this lowers the bar significantly to write docs in the first place. (and keep documentation uncollapsed in editors without burning your eyes out) 

P.S.
I know Visual Studios' integrated intellisense currently relies on this syntax but it should be an easy addition to parse javadoc style comments as this could easily be integrated into roslin, to supply this info to the correct internal structures for intellisense.

**Comment by basdek** [comment]
+1

**Comment by daveaglick** [comment]
Note that there is a pretty lengthy discussion of this over on the Roslyn repo:
https://github.com/dotnet/roslyn/issues/85

**Comment by stephentoub** [comment]
This is better discussed in the Roslyn repo, as it is much more related to the language.  Closing this one.
