### ISSUE TITLE
Expression interpreter can neither catch nor throw non–Exception-derived exceptions

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#5898]
Using the interpreter it is impossible to either throw or catch an exception that isn't derived from `Exception`.

This differs from the compiler, which allows both.

Possibly this should just be documented as a limitation.

Possibly something could be done by manipulating `RuntimeWrappedException`.

Possibly something could be done for catching, but not for throwing, which both seems easier on first blush, and may have more use (throwing such an object is a bad idea after all, catching one might be needed due to someone else's bad idea).

cc: @VSadov @bartdesmet

**Comment by svick** [comment]
Does the behavior of the interpreter depend on whether [`RuntimeCompatibilityAttribute.WrapNonExceptionThrows`](https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.runtimecompatibilityattribute.wrapnonexceptionthrows) is set for the executing assembly?

**Comment by JonHanna** [comment]
It certainly fails when it's set. I imagine it's even worse when it's not, but haven't experimented with that yet. This came up when I was looking at something else, so I'll circle back on experimenting more later.

**Comment by bartdesmet** [comment]
To throw, we may need some helper that does the equivalent of the `throw` instruction without causing any wrapping. I'm not aware of such a helper in the BCL today though. To catch, we'd need a similar helper that has a `catch (T)` (where `T` is not derived from `Exception`) in it.

I don't think `RuntimeWrappedException` is an option here: if the location from where the exception is thrown is subject to wrapping behavior, we can't unwrap it to make it catch the underlying exception object. For throwing ourselves, we'd have to make the assembly that contains `throw` not have the wrapping behavior. Likely dynamically compiled assemblies with the lambda compiler don't have that attribute set, thus making throwing any object without causing the wrapping behavior possible.

**Comment by VSadov** [comment]
I have to admit I've never seen exceptions not derived from System.Exception actually used in practice.   It looks like a feature that did not take off.
For example it does not work with async due to the same limitations of BCL and yet noone finds that limiting.

I think documenting it as a limitation would be completely acceptable.

**Comment by JonHanna** [comment]
It could also do with nicer exceptions (it hits an assertion in debug, and I'd guess an invalid program otherwise, but I have yet to get to checking just what it does through the various permutations), but beyond that even my inner pedant would probably be okay with letting this one go. It's hard to think of even an outlying use-case.

**Comment by bartdesmet** [comment]
Likely sufficient for the compiler behind the interpreter to detect unsupported throw/catch nodes and throw `NotSupportedException` rather than failing mysteriously.

**Comment by bartdesmet** [comment]
@VSadov - Any suggestion where we can document limitations? So far we have the following if I'm not mistaken:

- Passing `Type.Missing` to arguments (in interpreter)
- Non-atomic treatment of `ref`, e.g. relevant for `Interlocked` operations (in interpreter)
- Catch and throw with non-Exception types (in interpreter)
- Filters (not supported in compiler until BCL issue is fixed; implemented using catch in interpreter IIRC)
- Fault (not supported in compiler until BCL issue is fixed; don't recall how it's done in interpreter)

Maybe we can keep this list someone in an MD file?

**Comment by JonHanna** [comment]
Yeah, I'm going to look at throwing exactly that, though I want to checkout all the permutations of current behaviour first in case there's any surprise behaviour that might actually be worth keeping as is.

On limitations, I'd rather we fixed those last two than documented them if possible, but haven't found the coreclr code as easy to dive into as corefx, since it doesn't have the same bite size chunks in its projects.

**Comment by JonHanna** [comment]
Oh, we also have the behaviour in interpreter of mutable value type lhs to op-assignments. That one also seems like it should be fixable.

**Comment by JonHanna** [comment]
Okay, assuming we want to throw `NotSupportedException`, there are three possibilities:

1. Throw on `Compile()`.
2. Throw on the non-Exception throw.
3. Throw on the non-Exception throw, and force it out of the stack, so it can't be caught within the delegate itself.

The first is easy, though could have backward compatibility issues in that someone could e,g, have an lambda expression that attempts to throw non-Exception with certain inputs, but is never used with such inputs in which case we've just broken working code. There is also the question of the throw being typed as `object` in which case the actual running type may or may not be derived from `Exception` and there's a greater backwards-compatibility issue with prohibiting it. For this last case we'd probably want to do one of either 2 or 3 as well.

Between 2 and 3 the "pure" (ignoring backwards compatibility) design difference is between whether we consider the `Compile()` to be faulty, or the throw to be faulty in a way a coder should be able to account for. Backwards compatibility issues are more complex; a `NotSupportedException` could be there to catch a different case, but it's likely to end up doing the right thing overall anyway.

As the case of throwing non-Exceptions is an edge one, and currently fails in a strange way I don't think most of the backwards compatibility issues should be too great a concern, but that of making sure we don't ban `object`-typed throws is as it would break perfectly valid code that isn't affected by this issue.

I'm leaning toward a combination of 1 and 2 where we throw on `Compile(true)` if there is a throw typed to something neither `object` nor derived from `Exception` and throw also on a throw of such a case, but let a `NotSupportedException` handler within the delegate catch it.

**Comment by JonHanna** [comment]
Any changes to how throw works would also have to still throw NRE if one attempts to throw null. Worth noting as the most efficient check would be to do `frame.Pop() as Exception` and throw NSE if that was null, but that would falsely catch this case too.
