### ISSUE TITLE
Documentation Duplication Between .NET Projects

### ISSUE THREAD

**Issue by SamuelEnglard** [dotnet/corefx#5899]
As I'm working on #5877, I started thinking that between CoreCLR and CoreFX there's going to be lots of things that need to be explain in both contexts. The Terms section alone in [glossary](../Documentation/project-docs/glossary.md) would probably be useful for both projects. Would it make sense to move this kind of stuff to the [core-docs](https://github.com/dotnet/core-docs) repo?

/CC: @terrajobst @jasonwilliams200OK

**Comment by terrajobst** [comment]
Tagging a few more folks: @blackdwarf @cartermp 

That's a good questions. Let's see:

* `core-docs` is mostly for consumers of our tech.
* Documentation folder is mostly for documentation of the project and implementation details, such as book of the runtime (i.e. how the type system works, the interaction between GC and JIT etc).

So I think some amount of duplication is unavoidable and most like improves readability. The glossary in the CoreCLR repo is mostly dealing with internals of the runtime, so I think it's in the right spot.

The glossary that we created for CoreFX on the other hand mostly deals with information that is pretty high-level and frankly much broader than CoreFX. I think moving this out wouldn't be a bad idea. Another option would be [core](https://github.com/dotnet/core) repo, but I think `core-docs` is a better location.

Thoughts?

**Comment by cartermp** [comment]
:+1:  on having a glossary of terms on core-docs.  It could fit under the "Understanding the .NET Platform" as a standalone article.

**Comment by blackdwarf** [comment]
+1 on the glossary.

**Comment by SamuelEnglard** [comment]
@cartermp where's "Understanding the .NET Platform"? Can't find it.

**Comment by cartermp** [comment]
@SamuelEnglard, sorry, I was referring to the [table of contents structure](https://github.com/dotnet/core-docs/blob/master/docs/toc.md#understanding-the-net-core-platform).  I think having a glossary as a new article under there would be good, but we're open to other ideas.

**Comment by SamuelEnglard** [comment]
@cartermp ah yes, that does sound like a good idea

**Comment by SamuelEnglard** [comment]
Looking around the docs in code-docs and we have repeating of information in our glossary and the docs. For example see [Overview of .NET Implementations](https://github.com/dotnet/core-docs/blob/master/docs/concepts/editions-overview.md)

**Comment by cartermp** [comment]
Hmmm.  I think it's okay to have the repeating info for now.  We'll be adjusting and improving docs as .NET Core evolves.

**Comment by jasonwilliams200OK** [comment]
@SamuelEnglard, generally a good suggestion. For glossary (list of collective terminologies) and other documents which do not get changed frequently, it would make sense to refactor them out in a common place like https://github.com/dotnet/core-docs.

However, for the rest of the docs around building, testing, coding and contribution guidelines etc., I would like to point out @sindresorhus's brief blog post https://plus.google.com/+sindresorhus/posts/QSS2du26Mg4, which suggests that we should keep such documents in the source tree for version controll and encourage the contributors to submit the related document changes in the same pull request. Also, as I was told on CoreCLR that having a `Documentation` folder in the source tree is Torvalds-grade practice (capital `D` sorts it on top of sorts tree: https://github.com/torvalds/linux and https://github.com/dotnet/Documentation). :smile:

**Comment by SamuelEnglard** [comment]
@jasonwilliams200OK I think you hit it right on the head.

So I'm thinking `glossary.md`'s content (if not the file itself) should be moved to core-docs. Other docs that should be moved I'm not sure of

**Comment by blackdwarf** [comment]
@SamuelEnglard what is the action here? Seems like we have agreement on the glossary.md content's at least becoming a core-docs artifact, correct?

**Comment by terrajobst** [comment]
Here is what I think we should do:

* Move `dotnet/corefx/Documentation/project-docs/glossary.md` to `dotnet/core-docs`
* Follow @cartermp's advice and add new TOC entry "Glossary" under "Understanding the .NET Platform"

It seems either @cartermp or @blackdwarf should own this, given you guys own the docs. Fair?

**Comment by cartermp** [comment]
@terrajobst sounds good.  @blackdwarf sound good to you?  If so I'll move the doc and create the PR on core-docs and corefx.

**Comment by blackdwarf** [comment]
@cartermp go for it, but then reference this issue and then resolve it when merged.

**Comment by SamuelEnglard** [comment]
So is this done?

**Comment by karelz** [comment]
@blackdwarf can you please move the issue to core-docs?

**Comment by danmosemsft** [comment]
Ported to https://github.com/dotnet/docs/issues/1767
