### ISSUE TITLE
NetBSD PCL Reference Assembly redistribution issue

### ISSUE THREAD

**Issue by asiekierka** [dotnet/corefx#5901]
I am helping out in packaging CoreFX for NetBSD, however the build depends on the PCL reference assembly libraries, the license of which doesn't seem entirely clear to me as to whether or not redistribution of the PCL reference assembly as an operating system package (due to pkgsrc's source-based nature) violates its terms.

I would like to ask if the PCL reference assemblies (or the parts of them requires to build CoreFX) could be put under an OSI-approved license, or whether an alternate method of building CoreFX can be made which does not require the PCL reference assemblies.

**Comment by krytarowski** [comment]
This issue blocks pkgsrc port and further porting for NetBSD.

**Comment by mellinoe** [comment]
I don't believe the build uses the PCL reference assemblies any longer. I know the documentation refers to them (https://github.com/dotnet/corefx/blob/master/Documentation/building/unix-instructions.md#known-issues), but I believe they are outdated. We've made lots of build-related changes fairly recently, especially to the x-plat build. All of the references we use are pulled from NuGet at the start of the build, so I can't really think of any reason why we would need the PCL reference assemblies.

**Comment by krytarowski** [comment]
While there - do we need .Net nuget or mono-nuget? Are they both interchangeable?

**Comment by asiekierka** [comment]
That is not true. I still get the following message if the assemblies are
not present:

    PCL reference assemblies not found. Please see
https://github.com/dotnet/corefx/blob/master/Documentation/building/unix-instructions.md
for more details.



2016-02-04 21:08 GMT+01:00 Eric Mellino <notifications@github.com>:

**Comment by mellinoe** [comment]
That's a very good point. See https://github.com/dotnet/corefx/issues/5743, we should be able to remove those out-dated checks in the build script now that we no longer need those components. I'm working on doing that now, and am running a build currently to make sure everything works as expected. In that issue @jasonwilliams200OK posted roughly the changes that you need to make to disable those checks in the meantime.

**Comment by jasonwilliams200OK** [comment]
@mellinoe, sorry I forgot to update on that one. The build failed at later stage. I don't have the log handy (forgot my mac charger somewhere), but it was something to do with missing packages.

@asiekierka, @krytarowski, CoreFx currently uses universal NuGet (from https://NuGet.org) via Mono on Unices. That is the only reason we have Mono dependency. But with #5743 fix, mono dependency to build CoreFX will fade away for good. :) Roslyn will follow the same path most probably and then dotnet will be self dependent on all platforms! :fireworks:

**Comment by krytarowski** [comment]
Is it planned before the release?

**Comment by jasonwilliams200OK** [comment]
Apparently the milestone set for https://github.com/dotnet/corefx/issues/5743 (on right panel) is 1.0.0-rtm. So yup. :)

**Comment by jasonwilliams200OK** [comment]
With the mutual effort, on NetBSD we are able to port CoreRT 100%, CoreCLR 98%, CoreFX 100% System.Native assembly and managed part is yet to arrive. The patches on CoreFx can be found at https://wip.pkgsrc.org/cgi-bin/gitweb.cgi?p=pkgsrc-wip.git;a=tree;f=corefx-git/patches and the mirror repo on github being https://github.com/NetBSD/pkgsrc-wip/commits/master (updates every hour).

I am still very new to this packaging system pkgsrc, but I am learning a lot from @krytarowski and the company on IRC. :)

The upstreaming will follow its course, probably with one change at a time. 

The first in the series in being https://github.com/dotnet/corefx/pull/5983.

Note that pkgsrc is not only a package manager for NetBSD, but it is also available for Solaris, SmartOS and many other targets: http://www.pkgsrc.org/, https://pkgsrc.joyent.com/

Considering pkgsrc workshop as a downstream in this context, next steps are to port managed code and implement those features which require native assembly with through testing. By collaboration with corefx teams, we can achieve this milestone pretty quickly. We however would love to have PCL-independence first. :)

**Comment by mellinoe** [comment]
I have a branch that compiles without PCL reference assemblies here: https://github.com/mellinoe/corefx/commits/eliminate-pcl-warning. 

That branch should build all of the product assemblies, but there are still some issues that I am trying to track down. Namely some test references are not being copied correctly, so a lot of random test projects are failing because files are missing in the output directories. @ericstj gave me a good hint as to why that might be happening, so when I take a look at this again I may be able to fix that remaining issue.

I believe if you just pass /p:SkipTests to the build, though, you should be able to compile all of the product without the PCL reference assemblies.

**Comment by jasonwilliams200OK** [comment]
@mellinoe, thanks! @krytarowski has fixed the linker issue in CoreCLR, so we are most probably 100% there. Once that is done, I will try building your branch. This is a great effort you pulled there!
Kudos! :tada:

**Comment by asiekierka** [comment]
According to NetBSD packagers, this issue has now been solved. Thanks a lot!
