### ISSUE TITLE
echo TTY mode disabled for launched processes

### ISSUE THREAD

**Issue by andschwa** [dotnet/corefx#5902]
Similar to #5109, if `Console.ReadKey()` has been used by a .NET program, the `echo` TTY mode is disabled. To resolve the prior issues, dotnet/coreclr#2561 re-enabled the `echo` mode on program shutdown.

However, we've run into a different scenario: launching a process from the .NET program inherits the TTY modes. So if you launch Bash from the .NET program, you can't type in it until you've explicitly re-enabled `echo`.

**Comment by stephentoub** [comment]
@andschwa, can you share a small C# repro we can use to confirm the problem and verify when it's fixed?  I tried:
```C#
var p = Process.Start("bash");
p.WaitForExit();
```
but I can type fine in the launched process.

**Comment by stephentoub** [comment]
@pallavit, once @andschwa provides a repro, could you take a look at this?  My guess is we need to change how we handle initializing/uninitializing our terminal attributes, and that we need to reset the attributes in response to a variety of signals.  For example, rather than only setting the attributes at start and unsetting them at exit, we could handle signals like SIGTTOU, SIGTTIN, etc., setting the attributes back to the original values, and then the next time I/O is performed, re-call our initialize operation to set the attributes back.  Or something like that.  Related, we don't do a good job today with a console app that's been put into the background, as our read operations trigger EIO errors (see the man page for read for details)... for example, try creating a simple C# app that sits in a Console.ReadLine/Console.WriteLine loop and then launch it as a background process.

**Comment by pallavit** [comment]
@stephentoub Sure, I will take a look. @andschwa Please share a repro.

**Comment by andschwa** [comment]
This repros with the internal project you should both have access to; however, I understand the additional amount of complexity involved with said project. I'll assign one of our contractors to debug this until we can repro outside said project.

@palladia Pulling you into this discussion, I've assigned our linked issue to you. In order to fix this, the CoreFX team needs a repro outside our project.

**Comment by andschwa** [comment]
@pallavit This [gist](https://gist.github.com/andschwa/46eaf35109c93c921e65) reproduces what we're seeing.

If `Console.ReadKey()` or `Readline()` are used, then any subsequent invocation of interactive processes (like Bash) will still have the `ECHO` TTY mode disabled.

So for our project, if you try to launch Bash, you can't actually use it (until you've executed `stty echo` to turn it back on).

Thanks for the repro @palladia.

**Comment by andschwa** [comment]
@stephentoub Any movement on this? It makes self hosting a bit of a pain.

**Comment by stephentoub** [comment]
> @stephentoub Any movement on this?

This is assigned to @pallavit.

**Comment by pallavit** [comment]
@andschwa I have not had a chance to look at this yet as I have been busy with some feature work. I will try to get to this ASAP.

**Comment by andschwa** [comment]
Just checking, thanks guys!

**Comment by andschwa** [comment]
Along a really similar vein, when most interactive apps are run and then closed (say, Vim), `Console.ReadKey()` no longer recognizes the arrow or home/end keys, and instead reports letters: "A, B, C, D, 1~, 4~" for "Up, Down, Right, Left, Home, End".

If this isn't `System.Console`, then it may be our own use of it, and we'd appreciate any pointers to debug it.

I've verified that `TERM` remains `xterm` and `stty -a` emits the following both before and after an interactive application is launched and closed and the problem manifests:

```
speed 38400 baud; rows 59; columns 190; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; flush = ^O;
min = 1; time = 0;
-parenb -parodd cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl -ixon -ixoff -iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig -icanon iexten -echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke
```

**Comment by stephentoub** [comment]
> no longer recognizes the arrow or home/end keys, and instead reports letters: "A, B, C, D, 1~, 4~" for "Up, Down, Right, Left, Home, End"

This is likely very related.  We likely need to handle some of the signals I mentioned, and potentially SIGCONT, to redo some of the initialization previously done, including re-sending KeypadXmit: https://github.com/dotnet/corefx/blob/master/src/System.Console/src/System/ConsolePal.Unix.cs#L618.

**Comment by andschwa** [comment]
Going to add another, related, thing:

> `Key` is a `ConsoleKey`, `^X` is a key code, 'key' is an `stty` special character, and "key" is a physical keyboard key

On OS X, with `TERM=xterm256color` (and all others tested) when the system Terminal is left to its defaults, the "delete" key (used as "backspace") sends `^?`, which according to `stty -a` ought to be interpreted as 'erase' (as in the backspace action, or `Backspace`), but instead gets interpreted by `Console.ReadKey()` as `Delete` (as in the forward delete action). Note that "fn-delete" is interpreted the same way (but _should_ be the only one interpreted this way).

On Linux (over SSH and RDP), with the same tested `TERM` settings, the key code being sent by my MacBook's "delete" key still ends up as `^?`, but it is interpreted correctly as `Backspace`.

`System.Console` is not the only place where I've seen OS X's Terminal defaults cause funny things with the "delete" key. In fact, it seems to be so much an issue that Terminal has a setting to have "delete" send `^H`, which is then interpreted as `Backspace`. However, it would be nice not to have to do this :smile: and I sure would like to know how to fix it.

**Comment by stephentoub** [comment]
> Going to add another, related, thing

This isn't related. Can you please open a separate issue?

**Comment by andschwa** [comment]
Can do.

**Comment by stephentoub** [comment]
I'll take a look at this one, Pallavi.  Thanks.
