### ISSUE TITLE
System.AppContext.BaseDirectory returns location of native executable

### ISSUE THREAD

**Issue by andschwa** [dotnet/corefx#5903]
`System.AppContext.BaseDirectory` returns the location of the native host of .NET, which is not necessarily the same thing as the app's context. If we take "AppContext" to mean the location of the managed libraries that make up the app, these can exist in locations other than the directory that contains the native executable.

In our case, our native host uses the `CORE_ROOT` environment variable to set the "app context" (location of runtime and published app's libraries) to a different folder, but our tests use `AppContext.BaseDirectory` to determine the location of the DLLs, and this discrepancy has lead to a test failure.

What is the intent of `BaseDirectory`, and should it possibly be changed?

**Comment by AlexGhiondea** [comment]
@andschwa have you tried overriding the value in your host? 

Here is how we retrieve the value: https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/AppContext/AppContext.cs#L31

/cc @tarekgh

**Comment by andschwa** [comment]
@alexanderkozlenko Thanks! I will try that.

**Comment by AlexGhiondea** [comment]
@andschwa did that solve it?

**Comment by andschwa** [comment]
@AlexGhiondea Yup! That did it. Thanks a bunch :smile:
