### ISSUE TITLE
Failure in DriveInfoTests.Get_VolumeLabel sporadically in CI builds

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#592]
Discovering: System.IO.FileSystem.DriveInfo.Tests
  Discovered:  System.IO.FileSystem.DriveInfo.Tests
  Starting:    System.IO.FileSystem.DriveInfo.Tests
     System.IO.FileSystem.DriveInfoTests.Get_VolumeLabel.Test01 [FAIL]
        Error, Wrong volume label returned. Expected: BCLTest, Returned: 
        Stack Trace:
c:\j\workspace\dotnet_corefx_windows_prtest\src\System.IO.FileSystem.DriveInfo\tests\GetVolumeLabelTests.cs(106,0): at System.IO.FileSystem.DriveInfoTests.Get_VolumeLabel.Test01()

**Comment by weshaggard** [comment]
I keep hitting this error locally as well.

**Comment by stephentoub** [comment]
Fixed by #1109
