### ISSUE TITLE
Configure ThreadPool

### ISSUE THREAD

**Issue by sadrover** [dotnet/corefx#5920]
Hello,

There is some way to configure the threadPool and the ConnectionLimit in DNX Core 50?
We use this configure in dnx 451:
            ThreadPool.SetMinThreads(50, 50);
            ThreadPool.SetMaxThreads(10000, 10000);
            System.Net.ServicePointManager.DefaultConnectionLimit = int.MaxValue;

How can I put this parameters in core?

Thank you

**Comment by benaadams** [comment]
For threadpool can use environment variables: https://github.com/dotnet/cli/issues/889#issuecomment-172975280

So min+max threads would be setting these environment vars: 
`ComPlus_ThreadPool_ForceMinWorkerThreads=50`
`ComPlus_ThreadPool_ForceMaxWorkerThreads=10000`

**Comment by karelz** [comment]
We are adding APIs back in netstandard2.0 effort.
