### ISSUE TITLE
Add suggestions/samples for dealing with common missing desktop APIs

### ISSUE THREAD

**Issue by mjrousos** [dotnet/corefx#5925]
Customers coming from a .NET desktop background are frequently running into issues with a few common feature areas that are missing/changed in .NET Core (in ways too general to be thoroughly covered by API catalog recommendations).

It would be great to have a page (maybe linked from [here](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/support-dotnet-core-instructions.md) that listed the commonly missed areas and how to deal with them in .NET Core. Some areas that should be covered include:
- Serialization (moving to DCS from binary serialization)
- Xml (some high level changes to which APIs are available, like XmlTextReader vs. XmlReader
- Managed security.(CAS is gone; Transparency still exists, but usually isn't needed)

**Comment by terrajobst** [comment]
I think we need to walk the list of API gaps and make sure we've proposals for all of them.

@blackdwarf, do you want to drive this work?

**Comment by blackdwarf** [comment]
@terrajobst wouldn't you be a better candidate for driving it?

**Comment by karelz** [comment]
Given that we are bringing APIs back in 1.2, I think we can close this one.
