### ISSUE TITLE
MulticastDelegate, BeginInvoke throws NotSupportedException

### ISSUE THREAD

**Issue by christiannagel** [dotnet/corefx#5940]
Invoking the BeginInvoke method of a MulticastDelegate derived delegate compiles fine with .NET Core, but throws a NotSupportedException.
Should this really be the case?
Sample code is here, .NET 4.6 runs ok, but .NET Core fails with the mentioned exception:
https://github.com/ProfessionalCSharp/ProfessionalCSharp6/tree/master/Synchronization/SynchronizationSamples/AsyncDelegate

Thanks,
Christian

**Comment by jkotas** [comment]
Async delegates are not in .NET Core for several reasons:

- Async delegates use the deprecated IAsyncResult-based async pattern. This pattern is generally not supported throughout .NET Core base libraries, e.g. System.IO.Stream does not have IAsyncResult-based overloads for Read/Write methods in .NET Core.
- Async delegates depend on remoting (System.Runtime.Remoting) under the hood. Remoting is not in .NET Core - implementation of async delegates without remoting would be challenging.

**Comment by christiannagel** [comment]
Can't this be solved by compilation errors instead of runtime exceptions?

**Comment by jkotas** [comment]
@jaredpar What do you think?

**Comment by jaredpar** [comment]
Generally the compiler enables / disables features by looking at the types for hints.  Is there anything we can key on here to know to exclude these members?

**Comment by christiannagel** [comment]
just refreshing this thread to see if something can be done for compilation errors instead of runtime exceptions

**Comment by jnm2** [comment]
+1 For compiler safety. How does it make sense to make an API available that is guaranteed to be the wrong thing to use?

**Comment by weltkante** [comment]
Linking back to the official blog post, in case someone comes across the github issue before finding the post. It has some more details and suggestions how to replace `Delegate.BeginInvoke` invocations.

https://devblogs.microsoft.com/dotnet/migrating-delegate-begininvoke-calls-for-net-core/
