### ISSUE TITLE
Using System.IO.Compression cannot resolve System.Buffers with .NET 4.6

### ISSUE THREAD

**Issue by christiannagel** [dotnet/corefx#5941]
Using System.IO.Compression, 4.1.0-rc3-23805 cannot resolve System.Buffers compiling with .NET 4.6. It's ok with .NET Core. Compiling with "dotnet build".
Sample code:
https://github.com/ProfessionalCSharp/ProfessionalCSharp6/tree/master/FilesAndStreams/FilesAndStreamsSamples/CompressFileSample

**Comment by joshfree** [comment]
@sokket

**Comment by sokket** [comment]
Taking a look now

**Comment by sokket** [comment]
Looks like this is a bug with our build tools. The System.Buffers assembly is the first one to have both partial facade assemblies and nuget assemblies references, so there is some work here to make this scenario work (per @ericstj). Assigning to him for now until we can find a permanent owner

@christiannagel - as a workaround to get things building, add a reference to System.Buffers to your project.json and that should unblock you. Thanks for finding this

**Comment by christiannagel** [comment]
thank you @sokket

**Comment by ericstj** [comment]
This is fixed with https://github.com/dotnet/corefx/commit/ba64fda9a0c6bdd205f4d3a99e6c7729821dfada.

**Comment by ericstj** [comment]
Today's package has the fix: 4.1.0-rc3-23811
