### ISSUE TITLE
System.Net.Http.Native.so in package linked to libcurl-gnutls.so.4

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5942]
It should instead be linked to libcurl.so.4 (as is the one that gets built in Jenkins).

cc: @bartonjs, @chcosta

**Comment by ellismg** [comment]
Which distros?

**Comment by stephentoub** [comment]
Ubuntu. Haven't checked others.

**Comment by ellismg** [comment]
I believe this should be fixed in Monday's official build.

**Comment by ellismg** [comment]
Fixed now.

**Comment by ellismg** [comment]
(The fix was to the images of our build agents that produce the packages, so there's not a specific commit I can point to that fixed this).
