### ISSUE TITLE
System.Xml.XDocument.TreeManipulation.Tests failing for OSX Release in CI

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#5950]
Looks like something whitespace or end-of-line related from the error message.

**Comment by mellinoe** [comment]
I was seeing this on my Ubuntu VM on Friday as well, for another data point.

**Comment by sokket** [comment]
Seeing this again in all flavors: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst_prtest/1006/consoleFull#-21371504001f1a4601-6aec-4fd5-b678-78d4389fd5e8

**Comment by sepidehMS** [comment]
This failure doesn't look related to TreeManipulation. All tests in TreeManipulation are passing and the error messages printed were expected. However, those messages have been removed in https://github.com/dotnet/corefx/pull/6360.

**Comment by sepidehMS** [comment]
Closing the issue, since this is not a XML failure.
