### ISSUE TITLE
System.Reflection.Extensions 4.0.0 won't install on Xamarin

### ISSUE THREAD

**Issue by onovotny** [dotnet/corefx#5955]
The existing System.Reflection.Extensions 4.0.0 package seems to be broken on Xamarin. While it has a `\ref\dotnet` directory, there are not `\lib\xamarinios`, `\lib\monotouch` or `\lib\monoandroid` or `\lib\dotnet` directories to match those platforms. 

This differs from System.Reflection 4.0.0 and the other CoreFX libraries that **do** contain the Xamarin folders.

This is causing an issue with packages using `dotnet` or likely `netstandard1.0` in the future when trying to install into Xamarin based projects.

**Comment by onovotny** [comment]
System.Net.Http 4.0.0 is another one. This should be compatible with Xamarin already as it has the facades and is .NET 4.5 compatible. The package just needs the lib entries for it with `_._` in the right places... or a `netstandard1.x` entry as a catch-all.

**Comment by terrajobst** [comment]
@ericstj, do you know what the right fix is? I assume that's not something we can easily do ourselves because it requires Mono/Xamarin to provide these APIs, right?

/cc @weshaggard @pallavit @AtsushiKan

**Comment by onovotny** [comment]
Does this actually require APIs or just a blank TFM entry for nuget? The net45 tfm's don't have an impl and Xamarin should be compat with that.

**Comment by ericstj** [comment]
This is fixed in the latest packages on myget.  https://dotnet.myget.org/gallery/dotnet-core

**Comment by ericstj** [comment]
Looks like HttpClient still needs placeholders.  @mhutch I take it you'd want us to treat this one like the others as it would be inbox for Xamarin?

**Comment by onovotny** [comment]
@ericstj How would the newer 4.0.1 packages play in practice with NuGet? NuGet always uses the lowest version and the current state is that packages relying on the 4.0.0 S.R.E package fail to install on Xamarin. 

Does this mean that any package using PCL 259/the 4.0.0 contract dependencies will need to update themselves to pull in the 4.0.1 package just to prevent install issues on Xamarin? That seems a bit heavy-handed.

I suspect a lot of this boils down to the NuGet issues around highest/lowest versions, etc. It's like we need a way to tell NuGet that a particular package supersedes a prior one and should automatically  choose the higher ver.

**Comment by ericstj** [comment]
The requirement around actually being careful around which version of a package you reference goes away in the latest packages.  Before you had to be careful not to reference a version that was too high or you'd lose support for a platform that didn't support that API.  Now with `netstandard` we encode all API in the latest packages, so choosing the latest is safe.

**Comment by onovotny** [comment]
That's great! So I assume that means that something like System.Net.Sockets would have a `netstandard1.0` `ref` with one surface area and a `netstandard1.4` with a wider surface area?

**Comment by ericstj** [comment]
Yeah, though Sockets in particular wasn't on `netstandard1.0` platforms.  https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#list-of-net-corefx-apis-and-their-associated-net-platform-standard-version-tentative

**Comment by onovotny** [comment]
Fair enough re sockets, I was just using an example but that wasn't accurate in terms of version numbers :)

**Comment by ericstj** [comment]
Since this is already fixed in the latest packages I am closing this issue.  Please reopen if you disagree.

**Comment by onovotny** [comment]
@ericstj Is this resolved for System.Net.Http too or is that still an issue? It wasn't clear from the previous comment.

**Comment by onovotny** [comment]
Can we please re-open this? @terrajobst The System.Net.Http library does not appear to have Xamarin support yet.

I'm looking at the 4.0.1-rc3-23822 from the dotnet-core nuget feed.

**Comment by ericstj** [comment]
I'll fix this.  The list of supported packages was created originally by the file lists from the targeting pack and a list shared by @mhutch.

**Comment by onovotny** [comment]
Thanks Eric! Is there an easy way to check the rest of the BCL packages to ensure the supported packages list is accurate?

**Comment by ericstj** [comment]
Accuracy here is what Xamarin tells us they want to support so it will require a review.  One part that doesn't require review is consistency with the existing FileLists from their targeting packs, so I will make sure we have at least consistency there.

**Comment by onovotny** [comment]
I just checked my reference assms dir and the FrameworkList.xml in those directories is essentially blank :(

**Comment by ericstj** [comment]
They list all the framework assemblies in the redist list for the lowest version of the framework.

**Comment by ericstj** [comment]
Also, the redist list may be empty but we can examine the files in the targeting pack to correct that.

**Comment by ericstj** [comment]
Can you check the latest packages to see that this is resolved and close this issue?

**Comment by onovotny** [comment]
Looking at the package now, will create a test project in a minute. One thing I see that might be missing (could be true of other similar packages): should a framework reference be added on all of the Xamarin platforms?

**Comment by onovotny** [comment]
My assumption is correct. While the package installed correctly, it did not work the same -- It did not add the needed framework assembly.

I would assume that for all of the bcl packages where there's a net45 framework assembly added, those should be added for all the Xamarin platforms too for parity.

**Comment by onovotny** [comment]
This seems to affect https://github.com/dotnet/corefx/issues/6684 as well. The latest package has a blank lib for Xamarin iOS but not the other Xamarin platforms. They have a no-op façade to prevent reflection from breaking.
