### ISSUE TITLE
Dll Hell for System.Diagnostics.Process

### ISSUE THREAD

**Issue by andrew-vandenbrink** [dotnet/corefx#5960]
![image](https://cloud.githubusercontent.com/assets/12871379/12882732/dd604c08-ce53-11e5-86d1-5201bc4e56cf.png)

Add using statement

![image](https://cloud.githubusercontent.com/assets/12871379/12882744/f0fe07b4-ce53-11e5-948c-6e0a6aad3cab.png)

Add nuget package 
System.Diagnostics.Process 4.1.0-beta-23409

![image](https://cloud.githubusercontent.com/assets/12871379/12882812/604c4d74-ce54-11e5-89ad-c592467859eb.png)

![image](https://cloud.githubusercontent.com/assets/12871379/12882884/d5ff5dae-ce54-11e5-9225-b4e0935e41ec.png)

So if I add nuget package I have problem with references in .Net Framework 4.5.1
If I don't use nuget package I have problem with references in .Net Platform 5.4

Hello World Dll Hell

**Comment by adamsitnik** [comment]
Could you post your project.json file?

**Comment by andrew-vandenbrink** [comment]
```
{
  "version": "1.0.0-*",
  "description": "Class Library",
  "authors": [ "" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",
  "frameworks": {
    "net451": { },
    "dotnet5.4": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Linq": "4.0.1-beta-23516",
        "System.Runtime": "4.0.21-beta-23516",
        "System.Threading": "4.0.11-beta-23516",
        "System.Security.Cryptography.Csp": "4.0.0-beta-23516"
      }
    }
  },
  "dependencies": {
    "Microsoft.AspNet.Identity": "3.0.0-rc1-final",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.Core": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.Razor": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.ViewFeatures": "6.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Abstractions": "1.0.0-rc1-final",
    "System.Diagnostics.Process": "4.1.0-beta-23516"
  }
}
```

**Comment by adamsitnik** [comment]
Could you try to move dependency "System.Diagnostics.Process": "4.1.0-beta-23516" from general to framework specific?

```
"frameworks": {
    "net451": { },
    "dotnet5.4": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Linq": "4.0.1-beta-23516",
        "System.Runtime": "4.0.21-beta-23516",
        "System.Threading": "4.0.11-beta-23516",
        "System.Security.Cryptography.Csp": "4.0.0-beta-23516",
		"System.Diagnostics.Process": "4.1.0-beta-23516"
      }
    }
  },
  "dependencies": {
    "Microsoft.AspNet.Identity": "3.0.0-rc1-final",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.Core": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.Razor": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.ViewFeatures": "6.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Abstractions": "1.0.0-rc1-final"
  }
```

**Comment by andrew-vandenbrink** [comment]
Thanks It works!

What is the problem? Nuget?

**Comment by adamsitnik** [comment]
Each nuget package defines now which frameworks it supports. I suspect that Process is a part of net451 framework, where for dotnet5.4 it is a separate package.

VS sometimes shows the dependencies in tooltip when you are editing project.json file.

**Comment by andrew-vandenbrink** [comment]
ok.. thank you will close this one..
