### ISSUE TITLE
Ubuntu 14.04.3 Corefx Build Error 

### ISSUE THREAD

**Issue by hethert** [dotnet/corefx#5969]
Following instructions here https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md 

CoreCLR builds ok. Corefx gets following error 

~/git/corefx$ ./build.sh
Setting up directories for build
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.EntryPointNotFoundException: Unable to find an entry point named 'SetConsoleCtrlHandler' in DLL 'libcoreclr'.
   at Interop.libcoreclr.SetConsoleCtrlHandler(ConsoleCtrlHandlerRoutine handler, Boolean addOrRemove)
   at System.ConsolePal.ControlCHandlerRegistrar.RegisterOrUnregister(Boolean register)
   at System.Console.add_CancelKeyPress(ConsoleCancelEventHandler value)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)

Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'SetConsoleCtrlHandler' in DLL 'libcoreclr'.
   at Interop.libcoreclr.SetConsoleCtrlHandler(ConsoleCtrlHandlerRoutine handler, Boolean addOrRemove)
   at System.ConsolePal.ControlCHandlerRegistrar.RegisterOrUnregister(Boolean register)
   at System.Console.add_CancelKeyPress(ConsoleCancelEventHandler value)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args)
./build.sh: line 132: 31021 Aborted                 (core dumped) ReferenceAssemblyRoot=$__referenceassemblyroot $__scriptpath/Tools/corerun $__scriptpath/Tools/MSBuild.exe "$__buildproj" /nologo /verbosity:minimal "/fileloggerparameters:Verbosity=normal;LogFile=$__buildlog" /t:Build /p:OSGroup=$__BuildOS /p:COMPUTERNAME=$(hostname) /p:USERNAME=$(id -un) /p:TestNugetRuntimeId=$__TestNugetRuntimeId /p:ToolNugetRuntimeId=$__TestNugetRuntimeId $__UnprocessedBuildArgs

tail: cannot open ‘/home/tonyh/git/corefx/msbuild.log’ for reading: No such file or directory
Build Exit Code = 134

**Comment by mellinoe** [comment]
Yes, I'm seeing the same on Ubuntu 15.04. @joperezr, something must have changed recently in the Tools runtime we're using that makes it no longer compatible with the version of MSBuild we are using. Do we know if MSBuild is going to provide a self-contained executable that we can use to avoid issues like that?

**Comment by joperezr** [comment]
That is weird, I just tried a clean build in my ubuntu machine and I'm not seeing that. Could you guys try manually deleting the Tools folder on the root of your enlistment and try again?

**Comment by mellinoe** [comment]
Yeah, like I mentioned offline I actually don't see this anymore if I clean out my Tools directory and re-install it. @hethert Could you try doing the same, cleaning out your Tools directory and re-running build.sh?

**Comment by hethert** [comment]
Clearing out the tools, I got past the original error noted.
I am getting another error further on but it is not clear yet what the other error is.

**Comment by joperezr** [comment]
Ok, I'm closing this issue given that this error doesn't repro anymore, but please feel free to log any more issues you hit.
