### ISSUE TITLE
Failure in Process_EnableRaiseEvents tests in CI build

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#597]
Starting:    System.Diagnostics.Process.Tests
     System.Diagnostics.ProcessTests.ProcessTest.Process_EnableRaiseEvents [FAIL]
        Process_CanRaiseEvents0001: isExited Event not called when EnableRaisingEvent is set to true.
        Stack Trace:
           c:\j\workspace\dotnet_corefx_windows_prtest\src\System.Diagnostics.Process\tests\System.Diagnostics.Process.Tests\ProcessTest.cs(97,0): at System.Diagnostics.ProcessTests.ProcessTest.Process_EnableRaiseEvents()

**Comment by nguerrera** [comment]
Just hit this. Looking to fix it.

**Comment by nguerrera** [comment]
@Priya91 Assigning to you since you are looking at other Process test stability issues. I had a theory about this being due to the timeout added to "infinite" process, but it did not pan out...

**Comment by Priya91** [comment]
Assigning to @pallavit since she is looking at the process tests.

**Comment by pallavit** [comment]
I made some changes to the Process test in the recent past and I am not seeing any new reports of this failure and so closing this for now.
