### ISSUE TITLE
Process start doesn't resolve environment variables in the executable path.

### ISSUE THREAD

**Issue by alsemenn** [dotnet/corefx#5987]
If you use Process.Start(ProcessStartInfo) method on OSX (or any Unix OS) and a path to executable contains environment variables in it (this environment variables are passed to ProcessStartInfo.Environment). This variables will not be resolved and "System.ComponentModel.Win32Exception: No such file or directory" exception will be thrown.

This behavior is inconsistent with the Windows version. 

Note: path looks like "%EnvVar%\test.exe

**Comment by alsemenn** [comment]
If this is expected different behavior could you please update documentation with this difference.

**Comment by pallavit** [comment]
@alsemenn Can you please share a repro here. I seem to be getting win32exception in case of windows as well. Process class does not seem to be doing anything special to handle this. My guess is this might be getting automatically handled by CreateProcess windows function which has some places that it looks by default. So if you share a repro I can check if this happens across the board, for global environment variables, special look up directories, or for any environment variable set specific for the process to be created.
