### ISSUE TITLE
Eliminate CallbackHandle in CurlHandler

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#5998]
For each request, we end up allocating a native CallbackHandle and wrapping it on the managed side with a SafeCallbackHandle.  Then each P/Invoke to register a callback passes a delegate and a GCHandle, stores both in the CallbackHandle, and passes to libcurl a shim function and the CallbackHandle as the user pointer.  The shim when invoked then pulls the relevant function out of the CallbackHandle and invokes it.

But, we always use the same functions, for which delegates are cached in statics, both for perf and to keep them from being collected.  If we instead had a single P/Invoke we called to store pointers to all of these delegates, then we would no longer need to store the delegates in the CallbackHandle, and we'd only have a single piece of state (the GCHandle) to pass for each invocation, which means we could just pass that as the user pointer and get rid of the CallbackHandle altogether.

**Comment by eerhardt** [comment]
An issue is that we use SafeCallbackHandle and Interop.Http.RegisterReadWriteCallback in Crypto.X509Certificates as well:

https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/CertificateAssetDownloader.cs#L82

So we would either need to diverge these two code paths, or figure out a way for Crypto to just use pubilc System.Net.Http APIs instead of diving below straight to the shims.

@bartonjs - would it be possible for this crypto code to use System.Net.Http public APIs here?

**Comment by bartonjs** [comment]
@eerhardt Nope, it'd be a circular reference.  HTTPS needs X509 needs HTTP, and since HTTPS and HTTP are together in the same package there's no injection point... thus X509 needs to talk to libcurl directly.

**Comment by stephentoub** [comment]
We could just add a separate entrypoint to the shim for X509.

**Comment by bartonjs** [comment]
Yeah, I was about to add "but that doesn't mean that X509 can't just benefit from/also-compile-in whatever alternate solution is utilized here"

**Comment by stephentoub** [comment]
> Yeah, I was about to add "but that doesn't mean that X509 can't just benefit from/also-compile-in whatever alternate solution is utilized here"

It's likely that the same native image will be used from both libraries together, so X509 couldn't just use the same mechanism I'm proposing, as it would end up overwriting the callbacks hooked up by Http.  But we can essentially leave the existing mechanism in place for X509 (cleaned up a bit, since X509 needs less of it), and add the new entrypoints for Http to use.

**Comment by eerhardt** [comment]
So just to ensure that I have the idea understood properly:

In MultiAgent's static constructor, we P/Invoke into the shim passing pointers to all the necessary delegates. The shim then holds these pointers in global memory.

Later, when we actually make a request, EasyRequest.SetCurlCallbacks still calls Interop.Http.RegisterXXX as necessary, passing in a GCHandle to the EasyRequest as 'userPointer'. Inside the RegisterXXX method, we pass the pointer to our shim callback and the GCHandle 'userPointer'. When that shim callback is actually invoked, we grab the managed delegate from global memory, and call it passing through the 'userPointer'.

Is that what you had in mind?

**Comment by stephentoub** [comment]
Yup, that's what I had in mind.  Let me know if you think it's unreasonable, doesn't work, etc.

**Comment by stephentoub** [comment]
At this point this doesn't seem worthwhile to track.
