### ISSUE TITLE
HttpClient does not support proxy PAC file with file:// scheme

### ISSUE THREAD

**Issue by hardcodet** [dotnet/corefx#6011]
I have a vanilla ASP.net vnext project, and when switching from `dnx451 `to `dnxcore50`, `HttpClient `stops working assuming an URI with an invalid protocol. The code itself is trivial:

        public IActionResult Get()
        {
            string baseUrl = "http://someserver.com/foo/";
            using (var client = new HttpClient() { BaseAddress = new Uri(baseUrl) })
            {
                var result = client.GetAsync("items").Result;
                ...
            }
        }

I tried importing different versions of `System.Net.Http ` (e.g. _"System.Net.Http": "4.0.1-beta-23409"_), including the latest stable and latest beta, but they are all the same when running under the CoreClr.

I didn't find another implementation of HttpClient for the CoreClr, but then, I have a hard time believing that something as elementary would be missing or broken. Am I missing something or using the wrong library?

Thanks,
Philipp

System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The URL does not use a recognized protocol
   at System.Net.Http.WinInetProxyHelper.GetProxyForUrl(SafeWinHttpHandle sessionHandle, Uri uri, WINHTTP_PROXY_INFO& proxyInfo)
   at System.Net.Http.WinHttpHandler.SetRequestHandleProxyOptions(WinHttpRequestState state)
   at System.Net.Http.WinHttpHandler.SetRequestHandleOptions(WinHttpRequestState state)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__103.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at OrderManager.Controllers.JobsController.Get()
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The URL does not use a recognized protocol
   at System.Net.Http.WinInetProxyHelper.GetProxyForUrl(SafeWinHttpHandle sessionHandle, Uri uri, WINHTTP_PROXY_INFO& proxyInfo)
   at System.Net.Http.WinHttpHandler.SetRequestHandleProxyOptions(WinHttpRequestState state)
   at System.Net.Http.WinHttpHandler.SetRequestHandleOptions(WinHttpRequestState state)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__103.MoveNext()
   --- End of inner exception stack trace --

**Comment by davidsh** [comment]
cc: @CIPop @SidharthNabar 

Can you please submit a small repro Visual Studio solution for this?  Also, what version of Windows OS are you running this on? Thx.

**Comment by hardcodet** [comment]
OS: Win7 x64
Repro: Just start the project, then go to /api/jobs - that yields the exception for me.

[HttpClientIssue.zip](https://github.com/dotnet/corefx/files/125255/HttpClientIssue.zip)

Thanks for the quick reply!
Philipp

**Comment by davidsh** [comment]
I tried to reproduce your problem.  I was not able to.

I installed a Win7 x64 machine and Visual Studio 2015 with all updates.

When I run your project, the browser launches.  I navigate to /api/jobs.  However, I get a different error saying it can not connect.  The problem there is that your source code hardcodes the port of 5000 as the assumed port number for IISExpress when the project runs:

```c#
    [Route("api/[controller]")]
    public class JobsController : Controller
    {
        const string OrderManagerApiUrl = "http://localhost:5000/foo/bar";

        // GET: api/values
        [HttpGet]
        public IActionResult Get()
        {
            using (var client = new HttpClient() { BaseAddress = new Uri(OrderManagerApiUrl) })
            {
                try
                {
                    var result = client.GetAsync("items").Result;
                    return new ObjectResult(result);
                }
                catch (Exception e)
                {
                    return new ObjectResult(e.ToString());
                }
            }
        }

        // GET api/values/5
        [HttpGet("{id}")]
        public string Get(int id)
        {
            return "value";
        }
    }
```

However, my IISExpress server used a different port number:
http://localhost:57599/

After modifying the sample code you sent, I was still unable to repro your error.  The code worked and a JSON file was returned.

**Comment by davidsh** [comment]
Based on the call stack you sent:

```
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The URL does not use a recognized protocol
at System.Net.Http.WinInetProxyHelper.GetProxyForUrl(SafeWinHttpHandle sessionHandle, Uri uri, WINHTTP_PROXY_INFO& proxyInfo)
at System.Net.Http.WinHttpHandler.SetRequestHandleProxyOptions(WinHttpRequestState state)
at System.Net.Http.WinHttpHandler.SetRequestHandleOptions(WinHttpRequestState state)
at System.Net.Http.WinHttpHandler.d__103.MoveNext()
--- End of inner exception stack trace ---
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task1.GetResultCore(Boolean waitCompletionNotification) at System.Threading.Tasks.Task1.get_Result()
at OrderManager.Controllers.JobsController.Get()
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The URL does not use a recognized protocol
at System.Net.Http.WinInetProxyHelper.GetProxyForUrl(SafeWinHttpHandle sessionHandle, Uri uri, WINHTTP_PROXY_INFO& proxyInfo)
at System.Net.Http.WinHttpHandler.SetRequestHandleProxyOptions(WinHttpRequestState state)
at System.Net.Http.WinHttpHandler.SetRequestHandleOptions(WinHttpRequestState state)
at System.Net.Http.WinHttpHandler.d__103.MoveNext()
--- End of inner exception stack trace --
```

I suspect that there is something interesting going on w.r.t. your proxy settings on your machine.

Can you describe the environment of this Win7 machine?  Is it domain joined or standalone?  Does it run behind a proxy server, etc.?

**Comment by hardcodet** [comment]
This is a domain-joined corporate laptop, connected to my employer's environment through VPN.

My real sample actually used an external address (Amazon AWS hosted microservice), but I just removed that in order to make things simpler. The weird thing is that I get the desired results with the regular .net framework. I'll try to repro the issue on a colleague's machine tomorrow and my private workstation and will post back.

**Comment by davidsh** [comment]
It turns out the exception being surfaced is because the proxy detection logic in WinHttpHandler is getting this error from native WInHTTP: ERROR_WINHTTP_UNRECOGNIZED_SCHEME.  That error is not that the destination URL has a problem.  The error is really "The URL of the PAC file specified a scheme other than "http:" or "https:".".

I suspect that in the corporate domain environment, the proxy being specified uses a PAC file and that file is being stored on a fileserver or FTP server.  So, when WPAD (auto-proxy discovery) looks for the PAC file, it discovers that it doesn't have an http nor https scheme.  Due to limitations with WinHttpHandler running on Windows 7, proxy logic will not work if the PAC file is not specified with http/s schemes.  This isn't something that your app can control, per se, since it depends where it is being deployed.

Can you submit a picture of your Internet Explorer settings under the Internet Options/Connections/LAN settings ? That will give us a clue as to how your laptop is currently configured for auto-proxy lookup.

If this is indeed the problem, I'm not sure of the solution since WinHttpHandler (part of HttpClientHandler) in CoreFx doesn't support PAC file processing in that manner on Windows 7.

**Comment by davidsh** [comment]
>The weird thing is that I get the desired results with the regular .net framework.

And regarding the regular .NET Framework, yes, it had the ability to navigate more schemes to find and evaluate the PAC file.  CoreFx doesn't have the same ability on Windows 7.

**Comment by davidsh** [comment]
.And regarding the use of file:// schemes for PAC files, here is some good information on the deprecation plan for that support:

http://blogs.msdn.com/b/ieinternals/archive/2013/10/11/web-proxy-configuration-and-ie11-changes.aspx

```
NOTE: File://-based Proxy Scripts Deprecated
In IE11, the WinINET team has made some changes to attempt to improve interoperability of proxy scripts.

image

Internet Explorer 10 and other WinINET-based clients would use the specified proxy script. However, WindowsUpdate and any other application built on a WinHTTP-based network stack would silently ignore the specified proxy script because WinHTTP has never supported the use of the file:// protocol as the origin of a proxy configuration script. Note: In November 2012, the .NET Framework was changed to use WinHTTP for PAC processing, which means that, by default, .NET Applications will not support file://-based proxy scripts any longer either.

In Internet Explorer 11, the WinINET team has disabled WinINET’s support for file:// based scripts to promote interoperability across network stacks. Corporations are advised to instead host their proxy configuration scripts on a HTTP or HTTPS server.
```

**Comment by hardcodet** [comment]
Screenshot attached - there's no manual proxy configured in the first place...

![lansettings](https://cloud.githubusercontent.com/assets/873009/13002799/9c0f2bae-d171-11e5-943f-2779a3bfd157.png)

Some more findings:
* If I cancel the VPN connection of my laptop to my employer's network, the exception is gone.
* As soon as I reestablish VPN, I'm back to the error.

I'll try how it will behave when I'll be on-site later today and will post back.

**Comment by hardcodet** [comment]
Addendum: When on-site and directly plugged into the company's network, I also don't have the issue, so this seems to be a network quirk related to my VPN. I'm not sure how much of an issue this potentially is: Let me know if I can help you in any way if you want to follow up on this any further!

**Comment by davidsh** [comment]
cc: @stephentoub 
Based on the information provided, it appears that your corporate network is using a proxy and that proxy is discovered via WPAD "Automatically detect settings".  That results in a PAC file being declared.  Retrieving the PAC file is specified with a URL.  And post Windows 7 and also latest versions of .NET Framework as well, PAC file URLs can only be HTTP, HTTPS based.  Support for file:// schemes was deprecated

When you connect to your corporate network via VPN, you are getting those proxy settings. CoreFx HTTP stack doesn't support proxies with PAC files using file:// schemes.

So, this issue itself can not be resolved.

We are still looking into whether we should match .NET Framework behavior by simply ignoring this error and thus determining there is no proxy to use. Currently CoreFx returns this error which is why you see an exception.

**Comment by davidsh** [comment]
We updated the code so that you won't see exceptions generated from proxy discovery issues. This matches the same behavior as Windows 8, 8.1, 10, etc.
