### ISSUE TITLE
Inconsistent results for Math.Cos(double.MaxValue) on Windows and non-Windows platforms

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#6022]
## Problem
- `Math.Cos(double.MaxValue)` has inconsistent results on Windows and non-Windows platforms.
- Windows: returns `double.MaxValue`
- Non-Windows: returns `-0.99998768942656`

## Symptom
Whilst working on #5974, I noticed that I broke the Ubuntu, Mac OSX and CentOS builds by causing test failures. Interesting Windows did not break, and the tests ran as expected.

Consider the following code:
```
var complex = new Complex(double.MaxValue, 0);
Complex result = Complex.Exp(complex);
```

On Windows: `result == new Complex(double.PositiveInfinity, double.NaN)`
On Ubuntu etc: `result == new Complex(double.NegativeInfinity, double.NaN)`

In the [build logs](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/centos7.1_debug_tst_prtest/1595/consoleFull#-21371504001f1a4601-6aec-4fd5-b678-78d4389fd5e8), this test failure occurs at 8:39:16.

The code for Complex.Exp(Complex) is as follows:
```
double expReal = Math.Exp(value._real);
double cosImaginary = expReal * Math.Cos(value._imaginary);
double sinImaginary = expReal * Math.Sin(value._imaginary);
return new Complex(cosImaginary, sinImaginary);
```

This may be a bug, as there are inconsistent implementations of these `System.Math` functions, leading to unexpected/undefined behaviour.
I've added a test for this behaviour marked with ActiveIssue in #5974.

**Comment by hughbe** [comment]
Okay, a test failure on #6176 suggested that the cause of this bug is not actually part of System.Numerics, but rather mscorlib itself - the Math functions.

This brings up questions about breaking changes, as `System.Math.Cos(double.MaxValue)` is different on Windows, and non-Windows.

If the behaviour changes, it may be advisable to check if there are similar inconsistent implementations in the Math library

**Comment by mellinoe** [comment]
I don't think the code in the example above actually computes `Math.Cos(double.MaxValue)`. It computes `Math.Cos(value._imaginary)`, where `value._imaginary` is actually 0, not `double.MaxValue`. So there may be an issue with one of the other computations in the example (not sure which exactly). There is definitely a behavior difference with `Math.Cos(double.MaxValue)`, just not 100% sure it is affecting `Complex.Exp`.

**Comment by mellinoe** [comment]
I filed https://github.com/dotnet/coreclr/issues/4318 to track the issue over there.

**Comment by mellinoe** [comment]
I'm going to close this as it can be tracked over in coreclr. Most likely, we are going to keep this behavior difference and just document it. It is a result of the underlying native functions we are calling for cosine.
