### ISSUE TITLE
HttpWebRequest.UserAgent is not available in corefx?

### ISSUE THREAD

**Issue by feinoujc** [dotnet/corefx#6026]
any particular reason why?

**Comment by davidsh** [comment]
cc: @CIPop @SidharthNabar @stephentoub @terrajobst 

The API surface for System.Net.Requests contract (which includes HttpWebRequest API) was initially created from the Windows 8 Store Profile for .NET app.  In general, this Store Profile was a reduced set of .NET APIs compared with .NET Framework (Desktop).

For the HttpWebRequest API, many methods and properties were removed for simplication reasons.

We recommend devs more to the newer System.Net.Http API surface which is more featured and is the recommended programming model for HTTP in CoreFx.

**Comment by feinoujc** [comment]
Ok, I can live with that. Just seemed a bit odd. 

Thanks for the explanation.

In my case I am using System.Net.Requests so I can target both .net core and .net 4.5 and have synchronous api calls supported in the .net 4.5 target only, since HttpClient is 100% async.

**Comment by SidharthNabar** [comment]
@feinoujc - Just wanted to point out that HttpClient API is supported on .NET 4.5 as well. We would recommend you move to that API since that is where future innovation and improvements will be focused on (e.g. HTTP/2)

**Comment by feinoujc** [comment]
Thanks @SidharthNabar 

Yes, this is true. The only problem with doing that is it would mean I would have to drop support for non-async calls in my 4.5 API client since HttpClient is async only, correct?

Since most of .NET is moving to async all the way, this is just a matter of time i suppose. System.Net.Requests is a useful shim for me at the moment so I'm glad its there, missing UserAgent aside

**Comment by davidsh** [comment]
You can always turn an async all into sync by simply calling .Result. Thus, the async Task will wait until a result is ready.

Internally, it is still async in various ways but you wouldn't have to change a lot of code.  I'm not sure why you want to have sync in the first place, though.

**Comment by feinoujc** [comment]
@davidsh I found that doing that [causes deadlocks](http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html) when there is a SynchronizationContext

I agree, I wouldn't want to call sync unless I have to, but [sometimes](http://particular.net/blog/transactionscope-and-async-await-be-one-with-the-flow), for various legacy reasons you might have to.

**Comment by stephentoub** [comment]
>  I found that doing that causes deadlocks when there is a SynchronizationContext

If you find that with a XxAsync method in corefx, that's a bug we should fix.  The only way that should cause a deadlock is if the operation you're blocked waiting on posts back to the current context, and we should not be doing that in any our XxAsync APIs.  Please file issues if you find any.  Thanks!

**Comment by nbarbettini** [comment]
> You can always turn an async all into sync by simply calling .Result.

This feels 'icky' since it's been drilled into my head from the beginning of async/await that it's a Really Bad Idea(tm) to call .Result to block. I agree that it should be rare to need synchronous calls going forward, but every once in a while it seems to come up.

Ickiness aside, this does work. Thanks guys! :smile:
