### ISSUE TITLE
ServiceController StopAndStart test is failing intermittently

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#6029]
I'm at about 50% over several builds from the last few days, it's usually that the service hasn't finished starting in the allotted time:

```
    System.ServiceProcess.Tests.ServiceControllerTests.StopAndStart [FAIL]
       Assert.Equal() Failure
       Expected: Running
       Actual:   StartPending
       Stack Trace:
          D:\dd\Blue\CoreFx\src\System.ServiceProcess.ServiceController\tests\
 System.ServiceProcess.ServiceController.Tests\ServiceControllerTests.cs(154,0
 ): at System.ServiceProcess.Tests.ServiceControllerTests.StopAndStart()
```

One time it seemed to leave the service process still running, which resulted in me having to hunt down the abandoned service to stop it so I could clear out the bin directory.

**Comment by pallavit** [comment]
@bartonjs Thanks for reporting this. Are you seeing this behavior on windows? I tried repro'ing it on my local machine and things seem to work. I also looked at CI runs and they seem to be passing as well. I will try running the test in a loop or something on my local machine and see if I can repro it.

**Comment by bartonjs** [comment]
@pallavit Windows Server 2012 R2 (8.1 Server, IIRC).  It fails for me about half the time I build clean.  It's probably just my machine thrashing; but it suggests to me that the timeout is really close to the actual time it's taking (when the machine is still under the stress of building everything else).

There are a couple of factors that might be contributing:
* I still have a spinning/magnetic HDD for my code drive.  If you're SSD we might just get to the tests at different times.
* My GAC is possibly almost entirely non-ngenned, due to me doing a Bad Thing, and recovering just enough to continue running the things that I need (pending reformat).  So the parts of the build that use full framework (msbuild, the compiler) likely run a bit slower on my machine than on other ones... again, leading to a state where I might just be hitting this at a different spot than most people.

**Comment by pallavit** [comment]
Hmm.. I guess I will increase the timeout a little. Since, we run these tests only in elevated mode, I don't see any issues with doing it.

**Comment by stephentoub** [comment]
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_win10_debug/7/consoleText

**Comment by bartonjs** [comment]
Hmm.  Odd.  It can't be that the status change is taking too long, because that would throw an exception already: https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs#L849

I wonder if the service is crashing, and we're catching an SCM restart.  ::ponders::

**Comment by bartonjs** [comment]
Actually, I think the failures are in precondition checks.  Each test case creates a service and calls Start before the case runs; and since there's no WaitForStatus(Running) the assert that it's already running is causing the failure.

That does jive with the original reported line number of the failure: https://github.com/dotnet/corefx/blob/7cad8486cbabbce0236bdf530e30db7036335524/src/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.Tests/ServiceControllerTests.cs#L154
