### ISSUE TITLE
deadlocks in Stream ReadAsync/WriteAsync (rc1)

### ISSUE THREAD

**Issue by agnauck** [dotnet/corefx#6036]
ReadAsync and WriteAsync in Stream seem to block each other.
Attached is a test case which blocks with corefx, but works fine with the full .Net Framework 4.6

[ConsoleApplicationTest1.zip](https://github.com/dotnet/corefx/files/126226/ConsoleApplicationTest1.zip)

**Comment by stephentoub** [comment]
Thanks for the issue, @agnauck.  I just tried your repro with recent bits and it ran fine for me.  What build are you using?  

My guess is that it doesn't include https://github.com/dotnet/corefx/pull/3710... without that change back in October, I believe your example would deadlock.  The base Stream class in both the full framework and in CoreCLR serializes all async operations, whether via the Task-based or the APM-based entrypoints.  But in the full framework, NetworkStream overrides the async methods and thus doesn't inherit that behavior from the base class... when NetworkStream was ported to CoreCLR, those overrides were lost, and the aformentioned PR fixes that.

I'm going to close this under the assumption that this is now fixed.  If you're able to repro with the latest bits, please reopen. Thanks!

**Comment by agnauck** [comment]
> Thanks for the issue, @agnauck. I just tried your repro with recent bits and it ran fine for me. What build are you using?

I updated all my references to the latest:
```json
  "dnxcore50": {
      "dependencies": {
       "Microsoft.CSharp": "4.0.1-rc3-23811",
        "System.Collections": "4.0.11-rc3-23811",
        "System.Console": "4.0.0-rc3-23811",
        "System.Linq": "4.0.1-rc3-23811",

        "System.Threading": "4.0.11-rc3-23811",

        "System.Net.Sockets": "4.1.0-rc3-23811",
        "System.Net.NameResolution": "4.0.0-rc3-23811"
      }
```
runtime is dnx-coreclr-win-x86.1.0.0-rc1-update1

any idea what could be wrong with my setup?

**Comment by stephentoub** [comment]
> runtime is dnx-coreclr-win-x86.1.0.0-rc1-update1

DNX locks certain libraries in place, so even if you try to use a newer version of various libraries, you're unlikely to be able to (it'll use the ones that DNX itself is depending on).  You'll need to move to something newer.

**Comment by agnauck** [comment]
> DNX locks certain libraries in place, so even if you try to use a newer version of various libraries, you're unlikely to be able to (it'll use the ones that DNX itself is depending on). You'll need to move to something newer.

How can I do that? I installed the latest from here:
https://dotnet.github.io/getting-started/
