### ISSUE TITLE
Restore the S.S.C.OpenSsl package to Unix-only

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#6046]
PR #5880 made the OpenSsl package claim to be cross-platform to allow consumers of a particular form of lack-of-RSA.Create-workaround to continue having their code function after improved package validation came online.

Now that RSA.Create exists, we should undo that workaround and go back to being honest that the package doesn't work on Windows.

**Comment by bartonjs** [comment]
@ericstj I know we had a chat where you said to hold off on this, because of the new PNSE shims.  Is this a "don't do" now, or a "do differently"?

**Comment by ericstj** [comment]
We don't need to do this anymore.
