### ISSUE TITLE
Remove validation suppression from System.Runtime.Serialization.Primitives

### ISSUE THREAD

**Issue by chcosta** [dotnet/corefx#6059]
We're suppressing validation in System.Runtime.Serialization.Primitives until we can oob it to desktop.

**Comment by SGuyGe** [comment]
@chcosta What's this about? Is there a main issue that we can reference to?

**Comment by chcosta** [comment]
This is a packaging issue.  This issue is just tracking that there is cleanup work for us to be done for this library when we can OOB this package to desktop.  https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Serialization.Primitives/pkg/ValidationSuppression.txt#L2

**Comment by chcosta** [comment]
@ericstj , can we remove this now?

**Comment by ericstj** [comment]
Yep, so long as you don't get any validation errors.  It looks like the need for this was fixed with https://github.com/dotnet/corefx/commit/5fed5907e9d92683a7de98de90457f303315122a.
