### ISSUE TITLE
fixing comment

### ISSUE THREAD

**Issue by shrutigarg** [dotnet/corefx#6063]
check if we need to fix the comment https://github.com/shrutigarg/corefx/commit/f047a7d53ae699e51b8ee631e80d72cde4b6139b#commitcomment-16019127

**Comment by vijaykota** [comment]
@bartonjs, this a "framing" that is required by [MS-NNS data] (https://msdn.microsoft.com/en-us/library/cc236740.aspx) So it has to be at the beginning of the buffer. Note that ```output``` was allocated in the Encrypt call

**Comment by bartonjs** [comment]
@vijaykota Ah, yes, I'd failed to notice that `output` wasn't a user-provided array.  A comment reminding future readers/refactorers that `offset` and `count` apply to reading from `buffer`, and were inputs to the length of `output`, that `output` is a newly created array and thus these absolute indices are correct would be helpful.

Though perhaps significantly less of a run-on sentence than my statement here :).

**Comment by shrutigarg** [comment]
GetSecurityStatusPalFromWin32Int should be renamed to to GetSecurityStatusPalFromNativeInt

**Comment by shrutigarg** [comment]
In securityStatusAdapterPal.Windows. Use the dictionary instead of struct array.

https://github.com/dotnet/corefx/pull/5772#discussion_r52742447

**Comment by shrutigarg** [comment]
is notSet flag check needed?
https://github.com/dotnet/corefx/pull/5772#discussion_r52743232

**Comment by shrutigarg** [comment]
https://github.com/dotnet/corefx/pull/5772#discussion_r52743275 Need to throw more accurate exception in syn with other exception in code.

**Comment by shrutigarg** [comment]
fixed all the issued here and moved one (changing internalException to some other exception) to #5617 as this was present when windows code introduced.. since InternalException is being used at so many other place, we would have to look at other instances too/

**Comment by CIPop** [comment]
Reactivating this issue because this is still referenced from code:
https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.Net.Security/src/System/Net/NegotiateStreamPal.Windows.cs#L315

**Comment by shrutigarg** [comment]
@CIPop we would have to remove the TODO from there as this has already been discussed and fixed. Looks like it remained there by mistake, will incorporate this in one of our next PR.

**Comment by shrutigarg** [comment]
this will be fixed in PR #7647

**Comment by ericeil** [comment]
#7647 has not been merged; reopening this issue until that happens.

**Comment by shrutigarg** [comment]
this got fixed and merged , closing.
