### ISSUE TITLE
Make possible to write NT Services and corresponding Linux infrastructure (easier)

### ISSUE THREAD

**Issue by JiriZidek** [dotnet/corefx#6086]
Using .NET Core as NT Service is essential for any batch jobs and server services not based on http in general. (meant as port-to-core label)

**Comment by pallavit** [comment]
@JiriZidek Can you please elaborate on the functionality ask?

**Comment by pallavit** [comment]
@JiriZidek I believe you are asking for classes like ServiceBase in System.ServiceProcess. Correct me if I am wrong :). These classes are extremely windows centric. My understanding is that a service equivalent on cross-plat is basically a daemon process and nothing more. So, a contract that works cross-plat would not be possible here. Having said that in future we could consider exposing a windows only package (depending on whether the OS supports all the required functionality on the onecore) for these libraries but there is no current plan for the same. 

I will go ahead and close this request for now. Feel free to reopen in case I misunderstood you.

**Comment by JiriZidek** [comment]
Yes, you get it. But it can be some other mechanism. It should be similar approach as moving from IIS to general hosting of web app in ASP.NET Core - you write single code, run everywhere. The same is needed for serverside unattended long running tasks.

**Comment by pantonis** [comment]
+1

**Comment by pantonis** [comment]
@pallavit How would you write a daemon process using .netcore? Any examples?

**Comment by thosoft** [comment]
:+1:

**Comment by jberezanski** [comment]
> in future we could consider exposing a windows only package (depending on whether the OS supports all the required functionality on the onecore) for these libraries

**Comment by jberezanski** [comment]
@pallavit:
> in future we could consider exposing a windows only package (depending on whether the OS supports all the required functionality on the onecore) for these libraries 

Please do! NT services are still one of the best ways of hosting server applications that are not entirely driven by external requests. Providing System.ServiceProcess.ServiceBase as part of .NET Core would enable a lot of such applications to be ported to this platform, making it possible to run them on Nano Server.

The existing, mature implementation from the full .NET Framework could probably be reused (if possible on licensing grounds), perhaps minus the design-time support.

As for it being Windows-centric, you are already providing ServiceController, which is just as Windows-centric (and has, by the look of it, a more complex implementation than ServiceBase).

**Comment by jberezanski** [comment]
The ServiceBase programming model would even be useful on unixes. Many daemons accept control commands via signals - ServiceBase implementation could povide the plumbing for that. And although there is no SCM to report status to, the status could be written to a temporary file (similar to the well-established pidfile paradigm).

**Comment by JessieWadman** [comment]
This should be possible with a generic class and runtime specific implementations under the hood. Windows, Linux and Unix all have service concepts, with start and stop, and abstracting on top of that should be doable, right?

**Comment by JiriZidek** [comment]
I believe simple implementation with start/stop suites 99% of custom development use of NT Services. No extra bells and whistles needed imho (meaning designer support, configurable installer)

**Comment by jberezanski** [comment]
> No extra bells and whistles needed imho (meaning designer support, configurable installer)

I second that. We do not use the designer at all and we have our own custom install logic, so we do not use installutil either.
