### ISSUE TITLE
./build broken for Debian

### ISSUE THREAD

**Issue by kferrio** [dotnet/corefx#6090]
As of 8ca8c48 the `build.sh` script errors out on Debian 8.2:

```
~/projects/dotnet/corefx$ ./build.sh
Setting up directories for build
./build.sh: line 106: /home/projects/dotnet/corefx/Tools/corerun: No such file or directory

tail: cannot open ‘/home/projects/dotnet/corefx/msbuild.log’ for reading: No such file or directory
Build Exit Code = 127
```

I regret that I don't have time to dig into this but mention it because the new and improved build tooling will be very appreciated. BTW, I see that the CI builds are still passing, so I'm guessing that Jenkins is not using the same tooling?

**Comment by kferrio** [comment]
Forgot to mention that I referred to a commit just to put an upper bound on the range of commits to search. I have not isolated the commit(s) which caused the regression.

**Comment by ellismg** [comment]
The CI builds for Linux don't actually build Linux code on Linux.  The reason is that the builds take far too long compared to windows (due to gaps in the .NET Core versions of MSBuild and CSC which are being worked on).  So we compile all the managed code on Windows and then copy it over for testing.

We do have some outer loop runs that validate `build.sh` on Linux but @joperezr is still flushing out some issues with them I believe.  @naamunds has also done some work in this area recently.  I don't think we've actually had someone try to do specific builds on Debian (the team mostly uses CentOS and Ubuntu for daily development) so there could be bugs here yet to be squashed.

**Comment by kferrio** [comment]
@ellismg - Thanks for that insight. It explains a lot, and I appreciate your time. I've had pretty good success building coreclr and corefx on Debian until very recently. I will continue learning about the build process. Cheers!

**Comment by joperezr** [comment]
I believe the issue you are hitting is that the runtime is not being restored for Debian in the tools directory. Oficially, we only restore the correct runtimes for OS X, Ubuntu, and CentOS, but we also have a hook for you to override the runtime that you restore separately. 

The way to do this is by manually generating a folder containing the appropiate runtime for your platform, and then setting the variable 'BUILDTOOLS_OVERRIDE_RUNTIME' to the path to this folder. Once you've done that, simply remove the repo root Tools directory and regenerate it by calling:
```
BUILDTOOLS_OVERRIDE_RUNTIME=<pathToYourRuntimeDir> ./init-tools.sh
./build.sh
```

**Comment by joperezr** [comment]
@kferrio let me know if the fix above works.

**Comment by naamunds** [comment]
I added support for Debian in https://github.com/dotnet/buildtools/commit/78220deef3b1271fcae43cdb62cc1ab79d4613ab. As a first step, I would suggest simply deleting the "Tools" directory and then running `build.sh`. I was hitting the same issue, and that worked for me. If that doesn't work for you, try cleaning your repo and packages cache by running `clean.sh -a` (after ensuring that you don't have any untracked files you want to keep) and then running `build.sh`.

If that still doesn't work, you can try unblocking yourself by using `BUILDTOOLS_OVERRIDE_RUNTIME` as Jose mentioned.

**Comment by kferrio** [comment]
@joperezr and @naamunds : I tried a `clean.sh -a` and also deleting Tools and even cloning a new repo, all to no effect. I have not tried setting `BUILDTOOLS_OVERRIDE_RUNTIME`. I will try that (might be tomorrow) and report results. Thanks!

**Comment by naamunds** [comment]
@kferrio A fix for a different Linux build issue was submitted yesterday, so can you verify that you have the latest CoreFX source, and then try deleting Tools and building again?  If you still hit the issue, can you attach init-tools.log (in the root of your repo) and check what files are in your Tools directory? If everything is working correctly, you should have about 9 folders and 232 files, including the "corerun" file.

**Comment by kferrio** [comment]
Will do. Got called away today but should be back tomorrow.

**Comment by kferrio** [comment]
Finally got back to this.  Happy. I pulled down 56a6daf and it builds
successfully on Debian 8.2.  It appears that some tests may not be running
(chmod does not find corerun). I have not actually used the build yet but
wanted to give this feedback and say "thanks!"

**Comment by joperezr** [comment]
Cool, glad you have this working now. If that's resolved, I will close this issue. Feel free to reopen it if you start seeing this problem or log new ones.
