### ISSUE TITLE
Console.CursorTop is always 0 when TERM is not xterm (Ubuntu 14.04)

### ISSUE THREAD

**Issue by andschwa** [dotnet/corefx#6091]
As far as we can tell, when we're running with `TERM=xterm`, `Console.CursorTop` is set correctly. However, if we use Tmux or Screen, which both use `TERM=screen`, `Console.CursorTop` is always set to 0. This makes our readline implementation always print in the top-left corner, instead of where one would expect with a shell (at the end of the previous output, until the bottom is hit, and then at the bottom).

In fact, we don't even have to be inside Tmux or Screen, but just changing `TERM` causes `CursorTop` to return an incorrect value.

This is on Ubuntu 14.04. I have verified that input and output streams are not redirected, which [could have caused this](https://github.com/dotnet/corefx/blob/f6dc7d4acee451e1047473db0553170c13a505fe/src/System.Console/src/System/ConsolePal.Unix.cs#L310).

**Comment by andschwa** [comment]
See linked private issue for further details. Thanks :smile: 

/cc @pallavit @stephentoub

**Comment by andschwa** [comment]
It reproduced pretty easily with an addition to this [gist](https://gist.github.com/andschwa/46eaf35109c93c921e65).

Add this to the `Main` function:
```c#
Console.WriteLine($"CursorTop is {Console.CursorTop}");
```

Get these results:
```sh
~/src/echo-repro $ dotnet restore && dotnet build
...
~/src/echo-repro $ TERM=screen ./bin/Debug/dnxcore50/repro
CursorTop is 0

~/src/echo-repro $ TERM=vt100 ./bin/Debug/dnxcore50/repro
CursorTop is 0

~/src/echo-repro $ TERM=ansi ./bin/Debug/dnxcore50/repro
CursorTop is 52

~/src/echo-repro $ TERM=xterm ./bin/Debug/dnxcore50/repro
CursorTop is 52
```

**Comment by stephentoub** [comment]
The issue is likely that the terminfo files for those terms doesn't contain an entry for Cursor Position Request, in which case rather than assuming we know the sequence we play it "safe" and avoid writing out what could end up being gibberish to the console:
https://github.com/dotnet/corefx/blob/master/src/System.Console/src/System/ConsolePal.Unix.cs#L701-L703
```C#
CursorPositionRequest = db.GetString(TermInfo.WellKnownStrings.CursorPositionRequest) == KnownCursorPositionRequest ?
                    KnownCursorPositionRequest :
                    string.Empty;
```
My guess is if you try changing those lines to instead be:
```C#
CursorPositionRequest = KnownCursorPositionRequest;
```
that it'll start working...?

**Comment by andschwa** [comment]
Yay! Thank you @stephentoub :smile:
