### ISSUE TITLE
Failure in System.Collections.Concurrent tests in CI build

### ISSUE THREAD

**Issue by nslottow** [dotnet/corefx#610]
Test.BlockingCollectionCancellationTests.ExternalCancel_AddToAny [FAIL]
ExternalCancel_AddToAny:  At this point the cancel should not have occurred.
Stack Trace:       c:\j\workspace\dotnet_corefx_prtest\Config\Debug\OS\Windows_NT\Tests\false\label\windows\src\System.Collections.Concurrent\tests\BlockingCollectionCancellationTests.cs(137,0): at Test.BlockingCollectionCancellationTests.ExternalCancel_AddToAny()

**Comment by stephentoub** [comment]
This was fixed by #586.  It's been merged into v1.0 but not yet into master.

**Comment by nslottow** [comment]
Thanks, Stephen.
