### ISSUE TITLE
How do I determine the OS in which my program is running?

### ISSUE THREAD

**Issue by alexanderuv** [dotnet/corefx#6105]
I found issue #1017 where this is discussed but the solution is not present in the RC1. Is this being covered in the next release?

**Comment by GuardRex** [comment]
`Environment.OSVersion` may be of assistance. https://github.com/dotnet/corefx/issues/4741

**Comment by ellismg** [comment]
Is the information exposed by `System.Runtime.InteropServices.RuntimeInformation` sufficient?  The surface area of the new type can be seen in [the contract](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.InteropServices.RuntimeInformation/ref/System.Runtime.InteropServices.RuntimeInformation.cs).

`RuntimeInformation.IsOSPlatform` will be of use.

**Comment by alexanderuv** [comment]
Yes that seems appropriate. Thanks!
Is this published in any version in myget? Or do I have to compile the sources locally?

**Comment by ellismg** [comment]
It's published to our [dotnet-core](https://dotnet.myget.org/gallery/dotnet-core) MyGet feed.

**Comment by alexanderuv** [comment]
Thanks. I will look for it!
I'm closing this issue.
