### ISSUE TITLE
Remove sealed from Phone and EmailAddress data annotation attributes

### ISSUE THREAD

**Issue by plamenyovchev** [dotnet/corefx#6109]
Can you remove sealed from [Phone], [EmailAddress] and [Url] data annotation attributes(classes).
It would be great if developers can inherit their implementation and add their own improvements to the existing functionality.

> ```
> public class PhoneAttribute : DataTypeAttribute 
> {
>     public PhoneAttribute();
> 
>     public override bool IsValid(object value);
> }
> ```

**And I will use it as follows:**

Example:

>  public class PhoneLocalized : PhoneAttribute
>  {
>       public PhoneLocalized()
>      {
>          base.ErrorMessageResourceType =  typeof(WebPortalResource);
>          base.ErrorMessageResourceName = WebPortalResourceName.PhoneWrong;
>      }
>  }

**How I use Phone attrbute now in my view model:**

> public class RegViewModel 
> {
> [Phone(ErrorMessageResourceType = typeof(WebPortalResource), ErrorMessageResourceName = WebPortalResourceName.PhoneWrong)]
>         public string Phone { get; set; }
> }

**How I would use it if I was able to inherit the [Phone] attribute**

> public class RegViewModel
> {
>     [PhoneLocalized]
>     public string Phone { get; set; }
> }

**Comment by stephentoub** [comment]
cc: @terrajobst, @lajones

**Comment by terrajobst** [comment]
This would require API changes in .NET Framework, so I'm moving it to Future.

**Comment by terrajobst** [comment]
@lajones since you own this API, could you make a proposal?

**Comment by danmosemsft** [comment]
@lajones ?

**Comment by divega** [comment]
Triage: There are comments in #2093 arguing strongly against removing `sealed` for Data Annotations.  Unless are a missing something, the same arguments apply here. It would actually help if frameworks that use Data Annotations for validation are only looking for exact matches.
