### ISSUE TITLE
Suspicious comment on use of GC.KeepAlive() in System.Data.SqlClient.SqlConnection.TryOpen()

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/corefx#6116]
`System.Data.SqlClient.SqlConnection.TryOpen()` has this comment

```
  // does not require GC.KeepAlive(this) because of OnStateChange
```

I don't see an explicit call to `OnStateChange()` anywhere in that method. Even if there's a call chain which leads to `OnStateChange()` from that method it'd be more reliable to put `GC.KeepAlive()` call so that code isn't broken by later changes. It's worth remembering that failing to use `GC.KeepAlive()` can causes the subtlest race conditions.

**Comment by jhudsoncedaron** [comment]
The comment is just outdated. There's a conditional call GC.ReRegisterForFinalize(this); a few lines down that cannot be eliminated by static analysis so this is still rooted.
