### ISSUE TITLE
UmsSecurityTests.ChangePositoViaPointer failing

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#612]
Every other run or so I keep hitting the following test failure in UnmanagedMemoryStreamTests

    UmsSecurityTests.ChangePositioViaPointer [FAIL] (TaskId:528)
        System.IO.IOException : An attempt was made to move the position before the beginning of the stream. (TaskId:528)
            Stack Trace: (TaskId:528)
            d:\git\corefx\src\System.IO.UnmanagedMemoryStream\src\System\IO\UnmanagedMemoryStream.cs(439,0): at System.IO.UnmanagedMemoryStream.set_PositionPointer(Byte* value) (TaskId:528)
            d:\git\corefx\src\System.IO.UnmanagedMemoryStream\tests\UmsSecurityTest.cs(34,0): at UmsSecurityTests.ChangePositioViaPointer() (TaskId:528)
                     Finished:    System.IO.UnmanagedMemoryStream.Tests (TaskId:528)

**Comment by stephentoub** [comment]
This is the same basic problem as in #450: the test is assuming that new byte array allocations will come later in memory, and it fails when the assumption proves incorrect.  I'll fix it.

**Comment by stephentoub** [comment]
Fixed in #613
