### ISSUE TITLE
Cannot locate reference to type IPAddress

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [dotnet/corefx#6122]
Hello,

I've published a .NET Core library to nuget. Here is the project.json of this package:

```
"frameworks": {
        "dnx451": {
            "frameworkAssemblies": {
                "System": "",
                "System.Net": ""
            }
        },
        "dnxcore50": {
            "dependencies": {
                "System.Console": "4.0.0-beta-23516",
                "System.Collections": "4.0.11-beta-23516",
                "System.Linq": "4.0.1-beta-23516",
                "System.Net.Sockets": "4.1.0-beta-23516",
                "System.Runtime": "4.0.21-beta-23516",
                "System.Threading": "4.0.11-beta-23516"
            }
        }
```

I've installed this package from nuget to the DNX451 console app and restored nuget packages.
Unfortunately I have a problem with compiling.

> Reference to type 'IPAddress' claims it is defined in 'System.Net.Primitives', but it could not be found	ConsoleNet451Sample`

What is wrong? In my .NET Core project i have no references to System.Net.Primitives

**Comment by davidsh** [comment]
Can you provide a Visual Studio 2015 solution with your repro?  The IPAddress type is located in the System.Net.Primitives for CoreFx.  So, usually, libraries like System.Net.Sockets that depend on System.Net.Primitives would cause that library to be restored.

It is not clear from you description above exactly what you are trying to do. Are you building a .NET 4.5.1 app or .NET Core app?  You say that "I'm trying to publish to nugget library", but what are you publishing?

**Comment by davidsh** [comment]
@lukasz-pyrzyk Hello, can you provide a solution to repro this issue?  Thx.

**Comment by lukasz-pyrzyk** [comment]
Hi @davidsh. Sorry for insufficient description of issue - programming at night reduces my focus.

When it comes to issue. 
I've tried several time to reproduce that, but without any success. Since this issue I've updated dnvm runtimes. 
Sorry for the confusion

**Comment by davidsh** [comment]
Ok.  For now we'll close this issue.  If you find you have a solid repro...then we can re-visit this. Thx.
