### ISSUE TITLE
System.Threading.ReaderWriterLockSlim.LazyCreateEvent() fails to properly own the just created event

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/corefx#6136]
`System.Threading.ReaderWriterLockSlim.LazyCreateEvent()` goes like this:

            EventWaitHandle newEvent;
            if (makeAutoResetEvent)
                newEvent = new AutoResetEvent(false);
            else
                newEvent = new ManualResetEvent(false);
            EnterMyLock();
            if (waitEvent == null)          // maybe someone snuck in. 
                waitEvent = newEvent;
            else
                newEvent.Dispose();

There's quite a lot of code between a new event is created *and* its ownership is passed to the caller. If there's an exception in between the newly created event gets leaked.

**Comment by stephentoub** [comment]
> If there's an exception in between the newly created event gets leaked

An exception from where?  Worst case is the event gets cleaned up by its finalizer, and it should be extremely rare that even that needs to happen.  Is there a particular case you believe will be common that causes an exception to occur there?  If not, I don't think it's even worth a try/finally here, and there's nothing to be done.

**Comment by Dmitry-Me** [comment]
@stephentoub An exception from anywhere, including `EnterMyLockSpin()`. I dunno how rare that would happen, otherwise I would explain the specific scenario.

**Comment by stephentoub** [comment]
Right.  It'd be extremely unlikely.  It's not worth adding a try/finally here for a case that'll so rarely happen and that won't actually leak, since the finalizer will just pick it up in that extreme case.
