### ISSUE TITLE
Provide cross-platform coding guidelines

### ISSUE THREAD

**Issue by ebickle** [dotnet/corefx#615]
Please consider creating a document or wiki entry for the cross-platform coding guidelines and style. As the corefx and coreclr projects add additional cross-platform logic, a consistent way of organizing the code is going to become more and more important.

Topics could include:
* When should define statements be used rather than including different source files in the build environment? 
* When should partial classes be used to layer in platform-specific functionality?
* How should the platform-specific files be named? (FileStream.Win.cs? Win32FileStream.cs?)
* When should an existing platform-specific .NET API be deprecated or removed in favor of a new approach?
* How should ComVisible and other platform-specific attributes be handled?
* Should assemblies be binary-compatible across platforms? (I.e. exact same System.IO on Win32, Mac, and Linux).

I've seen quite a few other cross-platform .NET projects, and the source seems to quickly degenerate into an unmanagable mess of define statements. Some patterns could help head that off before it occurs, keeping things maintainable over the long term. Something akin to a "single-platform principle" applied at the source file level.

**Comment by stephentoub** [comment]
Thanks, @ebickle.  I agree we should probably have a wiki page outlining such things, but for now let me take a stab at quick answers to your topics:

> Should assemblies be binary-compatible across platforms? (I.e. exact same System.IO on Win32, Mac, and Linux)

Our expectation is that the majority (estimating around 70%) of CoreFX assemblies will have no platform-specific code.  These assemblies should be binary-compatible across platforms.

In some cases, the managed binary will be used across all platforms, but it'll come with its own native library that'll be compiled once per platform.

In a few dozen cases, the managed code itself will have differing implementations based on whether you're building for Windows, Linux, etc.  in such cases, the binary will not work from one platform to the next.  Which binary gets used will be handled by the NuGet package delivering the libraries.

> How should ComVisible and other platform-specific attributes be handled?

I don't believe ComVisible is relevant to .NET Core, and any such attribution that remains in CoreFX is, I believe, being removed, though someone else from the team can correct me if I'm wrong.

> When should an existing platform-specific .NET API be deprecated or removed in favor of a new approach?

Case-by-case basis.  In some cases, entire contracts that are platform-specific just won't be available on other platforms, as they don't make sense by their very nature.  In other cases, a contract will be available, but some members here and there that are platform-specific may throw PlatformNotSupportedException.  In general, though, we want to strive for having any APIs that exist on a platform (i.e. the contract is available) actually working on that platform.

> When should partial classes be used to layer in platform-specific functionality?

Partial classes is the approach we're currently taking when the managed code needs to diverge based on underlying platform.  There are a few cases where we've decided to go a different route, but even in some of those cases we may move back towards partial classes.

> How should the platform-specific files be named? (FileStream.Win.cs? Win32FileStream.cs?)

When the whole type is for a particular platform, we've been using the prefix, e.g. Win32FileStream.  When the file contains a partial class specialized for a particular platform, we've been using the .Platform.cs suffix.

> When should define statements be used rather than including different source files in the build environment?

We're striving to avoid defines whenever possible, instead preferring to include just the source files that are relevant.

**Comment by stephentoub** [comment]
cc: @ellismg

**Comment by ellismg** [comment]
@stephentoub Thanks for tagging me.  This all sounds reasonable to me.

**Comment by stephentoub** [comment]
I've ported this question and response over to a new wiki page at [[Cross Platform Code Guidelines]].  We can evolve it there as needed.  Thanks for the suggestion, @ebickle.
