### ISSUE TITLE
System.IO.Tests.FileStream_Dispose.DisposeVirtualBehavior failed on Ubuntu Release

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#6153]
```
 System.IO.Tests.FileStream_Dispose.DisposeVirtualBehavior [FAIL]
17:42:30       Assert.True() Failure
17:42:30       Expected: True
17:42:30       Actual:   False
17:42:30       Stack Trace:
17:42:31             at System.IO.Tests.FileStream_Dispose.DisposeVirtualBehavior()
```

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/ubuntu_release_tst_prtest/1916/consoleFull#-21371504001f1a4601-6aec-4fd5-b678-78d4389fd5e8

**Comment by Priya91** [comment]
#5818

**Comment by Priya91** [comment]
Failed again here: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst_prtest/872/consoleFull#-21371504001f1a4601-6aec-4fd5-b678-78d4389fd5e8 on OSX

**Comment by Priya91** [comment]
again here: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/ubuntu_release_tst_prtest/1917/consoleFull#-21371504001f1a4601-6aec-4fd5-b678-78d4389fd5e8

**Comment by mellinoe** [comment]
Hit this here: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/ubuntu_release_tst_prtest/1918/

**Comment by ianhays** [comment]
Was this failure intermittent or across all runs? I'm unable to repro it on my local machine.

**Comment by Priya91** [comment]
It was occurring frequently in the CI runs, not across all runs.

**Comment by stephentoub** [comment]
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/ubuntu_release_tst_prtest/2024/console
```
06:02:06    System.IO.Tests.FileStream_Dispose.DisposeVirtualBehavior [FAIL]
06:02:06       Assert.True() Failure
06:02:06       Expected: True
06:02:06       Actual:   False
06:02:06       Stack Trace:
06:02:07             at System.IO.Tests.FileStream_Dispose.DisposeVirtualBehavior()
```
(This was for a PR in the dev/negotiatestream branch, which doesn't have the change to disable the test.)

**Comment by stephentoub** [comment]
Failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst_prtest/1052/console
