### ISSUE TITLE
Add a issue_template.md and pull_request_template.md

### ISSUE THREAD

**Issue by GerjanOnline** [dotnet/corefx#6167]
Please see

https://github.com/dear-github/dear-github/issues/125
and
https://news.ycombinator.com/item?id=11119411

Maybe an idea for this repo?

**Comment by swgillespie** [comment]
Also: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by terrajobst** [comment]
Thanks, that seems like a good idea indeed!

@stephentoub @weshaggard What would like to see in there? In my case, I'd like to point that PRs that add APIs should have a corresponding issue to be filed first.

**Comment by stephentoub** [comment]
> What would like to see in there?

For issues, the normal stuff (description of the problem, minimal repro steps, etc.), but also we often see target platform missing from the description, so it'd be good to highlight that.

For PRs, the body should contain a "Fixes ..." link to the issue (sometimes folks just put the issue number in the title, and that's not as easily followed), plus this way the issue automatically gets closed.  Ideally the PR description also includes a short summary of the problem (in addition to what's in the issue) and a summary of the fix.

> I'd like to point that PRs that add APIs should have a corresponding issue to be filed first

Not only filed, but marked as API approved.

**Comment by terrajobst** [comment]
That makes sense. I'll take a crack at the template and submit a PR.
