### ISSUE TITLE
Debian Jessie RID should be debian.8 not debian.8.2

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#6170]
See the discussion at the end of https://github.com/dotnet/cli/issues/212#issuecomment-184786944.  The CLI is going to compute the debian.8 RID which we produce no assets for.  We should have our debian packages be produced with the debian.8 RID and remove debian.8.2 from the runtime graph.

**Comment by ellismg** [comment]
@chcosta Can you update these packages?  I'm not sure exactly where the source of truth for this stuff is anymore and I don't want to cause a bunch of merge conflicts if it's going to impact your closed to open move for the packages.

**Comment by chcosta** [comment]
@naamunds, @weshaggard, does this require updating buildtools (init-tools.sh and tool-runtime\project.json)?  If yes, is there an ordering requirement between updating buildtools and updating corefx?

**Comment by weshaggard** [comment]
@chcosta once the packages are updated you will likely need to update to RID in the tool-runtime (https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json#L42) in order to get the tools to restore for that new RID. The source of truth for the RID itself is https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/runtime.json. I assume you know where which packages need to be updated with this RID.

**Comment by naamunds** [comment]
The Debian RID should probably be changed from 8.2 to 8 everywhere. It looks like there are four files where it occurs:  src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh and src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json in BuildTools, and build.sh and src/Common/test-runtime/project.json in CoreFX. See https://github.com/dotnet/corefx/commit/ba64fda9a0c6bdd205f4d3a99e6c7729821dfada and https://github.com/dotnet/buildtools/commit/78220deef3b1271fcae43cdb62cc1ab79d4613ab.

I think you should update BuildTools first, although I'm not sure if it's strictly necessary.

**Comment by chcosta** [comment]
@weshaggard , should this issue be pushed to the next milestone?

**Comment by Sridhar-MS** [comment]
@ellismg The CoreCLR packages produced still have the RID `debian.8.2` as seen in https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.debian.8.2-x64.Microsoft.NETCore.Runtime.CoreCLR.

They should also be producing debian packages with `debian.8` RID.

This is blocking CLI from adding support for debian.

**Comment by chcosta** [comment]
A fix for the CoreClr packages has been submitted by @ellismg
