### ISSUE TITLE
Inconsistent ToString() implementations in System.Primitives

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#6177]
The ToString() implementations in System.Drawing.Primitives are as follows:

- Point: `{x,y}`
- PointF: `{x, y}`
- Size: `{width, height}`
- SizeF: `{width, height}`
- Rectangle: `{x,y,width,height}`
- RectangleF: `{x,y,width,height}`

There is some inconsistency here. PointF, Size and SizeF have a space after the comma, and Point, Rectangle and RectangleF do not.

In mathematical notation, `{x,y}` is correct for coordinates, but in English, `{x, y}` is correct.

This inconsistency was addressed by PR #6102, but this require API review, so the PR was not merged.

**Comment by Priya91** [comment]
Thanks for opening this.

**Comment by eadordzhiev** [comment]
Please, don't remove the spaces, it will be totally unreadable then. In some some regional format, such as Russian, the comma is the decimal mark and it would be impossible to distinguish the decimal mark and the member separator. The semicolon and a space after would be the best option, IMHO.

**Comment by Priya91** [comment]
These changes don't cause any functional difference and given that these types are only meant for compatibility to help move desktop apps to .net core. Closing this as won't fix.
