### ISSUE TITLE
Socket_ConnectAsyncDnsEndPoint_HostNotFound test failed with TryAgain error

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#6187]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_release_prtest/2364/consoleFull
```
16:18:38      System.Net.Sockets.Tests.DnsEndPointTest.Socket_ConnectAsyncDnsEndPoint_HostNotFound [FAIL]
16:18:38         SocketError: TryAgain
16:18:38         Expected: True
16:18:38         Actual:   False
16:18:38         Stack Trace:
16:18:38            d:\j\workspace\windows_nt_re---5067c899\src\System.Net.Sockets.Legacy\tests\FunctionalTests\DnsEndPointTest.cs(348,0): at System.Net.Sockets.Tests.DnsEndPointTest.AssertHostNotFoundOrNoData(SocketAsyncEventArgs args)
16:18:38            d:\j\workspace\windows_nt_re---5067c899\src\System.Net.Sockets.Legacy\tests\FunctionalTests\DnsEndPointTest.cs(196,0): at System.Net.Sockets.Tests.DnsEndPointTest.Socket_ConnectAsyncDnsEndPoint_HostNotFound()
```

**Comment by CIPop** [comment]
Thanks for reporting @stephentoub. 

The SocketError is [`WSATRY_AGAIN`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms740668(v=vs.85).aspx):

>Nonauthoritative host not found.
>This is usually a temporary error during host name resolution and means that the local server did not receive a response from an authoritative server. A retry at some time later may be successful.

I believe that the test needs to retry the DNS resolution when this happens. In this case, the expectation was for a HostNotFound error.

**Comment by CIPop** [comment]
Duplicate to #3697.
