### ISSUE TITLE
Failure System.Diagnostics.ProcessTests on Chinese Windows 8.1

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/corefx#619]
Looks like it's because there's localized string for "at" in the exception messages.
-      System.Diagnostics.ProcessTests.ProcessTest.Process_SyncErrorStream [FAIL]
        Assert.Contains() Failure
        Not found: Unhandled Exception: System.Exception: Intentional Exception
   thrown   at ProcessTest_ConsoleApp.Program.Main(String[] args)
        In value:  Unhandled Exception: System.Exception: Intentional Exception
   thrown   ? ProcessTest_ConsoleApp.Program.Main(String[] args) ?? C:\github\j
  eremymeng\corefx\src\System.Diagnostics.Process\tests\ProcessTest_ConsoleApp\
  ProcessTest_ConsoleApp.cs:?? 25
-     System.Diagnostics.ProcessTests.ProcessTest.Process_AsyncErrorStream [FAIL
 ]
       Assert.Contains() Failure
       Not found: Unhandled Exception: System.Exception: Intentional Exception
  thrown   at ProcessTest_ConsoleApp.Program.Main(String[] args)
       In value:  Unhandled Exception: System.Exception: Intentional Exception
  thrown   ? ProcessTest_ConsoleApp.Program.Main(String[] args) ?? C:\github\j
 eremymeng\corefx\src\System.Diagnostics.Process\tests\ProcessTest_ConsoleApp\
 ProcessTest_ConsoleApp.cs:?? 25

**Comment by Alexx999** [comment]
This can be reproduced on any non-English locale in general since test looks for exact error message

**Comment by ellismg** [comment]
It looks like @Alexx999 is fixing this.  Thanks!
