### ISSUE TITLE
(API proposal) Adding a Path.CreateRelativePath method to calculate a relative path between two others

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#6191]
### Background

Currently, there's no built-in way to recalculate a path relative to another directory in .NET. The [most popular SO answer](http://stackoverflow.com/a/340454/4077294) on the topic is over 10 lines, which is less than ideal. Also, it's pretty allocation-heavy since it instantiates 3 `Uri` objects and 3 strings.

### Signature

The method would look like this:

```csharp
public static string CreateRelativePath(string @from, string to)
```

- **from** would be the directory path for which the newly returned path would be relative to. It could be absolute or relative.
- **to** would be the path for which the returned path would point to. It could also be absolute or relative.

If either paths are relative, they are resolved in relation to the process' current directory (e.g. via `Path.GetFullPath`).

### Example inputs/outputs

```csharp
Path.CreateRelativePath(@"C:\Users", @"C:\Users\James"); // returns James
Path.CreateRelativePath("/usr/local/bin", "/usr/bin"); // returns ../../bin
Path.CreateRelativePath("lib", "../test"); // returns ../../test
```

What do you guys think?

**Comment by jasonwilliams200OK** [comment]
:+1: x :100: 

`Resolve()` and `RelativePath()` are very desired API methods in `Path` type. These are available in many many platforms. For example, Node.js has a pretty solid implementation for calculating the relative path, which works brilliantly in cross-platform scenarios: https://nodejs.org/api/path.html#path_path_relative_from_to. IMO, if CoreFX implementation just match node.js one, that would probably satisfy most (if not all) real-world scenarios.

Regarding names, `Path.MakeRelativePath` or just `Path.RelativePath` might be better options to consider.

**Comment by JeremyKuhne** [comment]
Here is an initial implementation if you want to take a look. I need to work out how to add a new API for System.RuntimeExtensions to finish writing the tests / create a PR. (I've tested the code in a separate assembly before integrating it here.)

https://github.com/JeremyKuhne/corefx/commit/f4dcfb31841f2c4d6a64b84df6d6f3f76c637fdb

Everything gets normalized (Path.GetFullPath(), which is already optimized). The API throws for empty/null strings. I've optimized allocations as much as possible.

Only big question is what to do when the exact same path is passed in for both arguments. I currently pass back an empty string. Thoughts?

**Comment by jamesqo** [comment]
@JeremyKuhne Interesting work, thanks for sharing!

> Only big question is what to do when the exact same path is passed in for both arguments. I currently pass back an empty string. Thoughts?

Best option would probably be to return `"."`, so if you `Combine`'d it with the first path you would get the absolute second path.

**Comment by JeremyKuhne** [comment]
Another assumption this makes is that the from path is a directory, not a file. We could check for that but I'm inclined not to as that (1) involves hitting the disk and/or network and (2) would be a guess anyway if the location didn't exist/wasn't reachable. I think it's better to document the behavior clearly. In all my experiences with making relative paths I never had a case where I was trying to make one from a path that might have been a directory- but I have had to make fixes to code where the trailing slash was missing and the directory name got cut off.

Also, if the roots aren't the same the second path is returned as is. This should never happen in a normalized path on Unix as there is only one root. I'll be writing tests for UNCs and device paths on Windows to make sure that we get the desired behavior around roots.

**Comment by jasonwilliams200OK** [comment]
Since `\` is a valid file name character in Linux, the path separator handling in CreateRelativePath should be platform specific.

`CreateRelativePath("/a\\temp/test", "/a/b\\c")` =>
on Windows: `..\\..\\b\\c` (since FS can handle both \ and / in PowerShell for example)
on Unix: `../../a/b\\c`

**Comment by BrennanConroy** [comment]
@JeremyKuhne I think your assumption that the `from` path is a directory is wrong. Look at `Path.GetDirectoryName()` it strips everything after and including the last `DirectorySeparatorChar` i.e. it assumes a path without a trailing `DirectorySeparatorChar` is a File not a Directory. Since these are in the same class the behavior should be consistent.

**Comment by JeremyKuhne** [comment]
@jasonwilliams200OK 

> Since \ is a valid file name character in Linux, the path separator handling in CreateRelativePath should be platform specific.

All of the methods I'm using are platform specific. Did you see a specific place I missed?

**Comment by JeremyKuhne** [comment]
@BrennanConroy Looking at Uri's behavior with trailing slashes I think I agree with you. What matters more to me is that we avoid hitting the disk- we'll do the equivalent of GetDirectoryName() but will not validate the actual disk contents.

**Comment by jasonwilliams200OK** [comment]
@JeremyKuhne, not that I can sport. i was just highlighting another edge case based on your previous assumption. :)

**Comment by BrennanConroy** [comment]
Hitting the disk isn't necessary, if it has a / at the end its a directory, if not its a file :)

**Comment by JeremyKuhne** [comment]
@BrennanConroy: Yes, that's my assertion.

**Comment by JeremyKuhne** [comment]
I'm also going to propose that we add a new assembly for this and all of the other things we have pending. (#9798)  Having a new portable assembly doesn't preclude adding things to the current Path class, but it will enable us to move forward much faster and allow existing deployments to easily pick up new IO related helpers without taking dependencies on newer runtimes (possibly not even existent yet).

**Comment by JeremyKuhne** [comment]
@BrennanConroy Now that I've looked at the behavior a bit more I'm leaning back towards treating the incoming path as a directory. Here's why:

When you get something like `C:\a` to `C:\a\b` you wouldn't want to get back `a\b`. If you then pass in `C:\a` and `C:\b`, getting back `b` would cause differing behavior when you call `Path.Combine()`.

For the record I dislike the name for `GetDirectoryName()`. It's not self-describing and can contradict what is on disk. `TrimToLastSeparator()` would have been much better imho. :)

**Comment by terrajobst** [comment]
@JeremyKuhne and I just talked about this API. Here is what we concluded:

```C#
public string GetRelativePath(string relativeTo, string path)
```

Naming

* Let's use `Get` rather than `Create` because that's what the other APIs on `Path` use.
* Let's make it clear which one is the path the other is made relative to. `from` and `to` as well as `source` and `destination` take too many cycles to think about (in other words, I'm too stupid to get it :smiley:)

Behavior:

* We will not check if `relativeTo` is a directory or file. We'll assume it's a directory.
* We will not enforce that it ends with a `DirectorySeparator`
* Both `relativeTo` and  `path` will be passed to `Path.GetFullPath()` before processing
* We guarantee that:

```C#
casing := Choose(Windows: StringComparison.OrdinalIgnoreCase, Rest: StringComparison.Ordinal)

string.Equals(Path.GetFullPath(Path.Combine(relativeTo, GetRelativePath(relativeTo, path))),
              Path.GetFullPath(path),
              casing)
```

**Comment by jaredpar** [comment]
Overall LGTM

I think casing should be consistent across operating systems.  It's easy to try and categorize Windows as case insenstiive and non-Windows as case sensitive.  That's just not the reality though.  On non-Windows you can actually get paths where part is case sensitive and part is case insensitive (just mount fat32 into a ext3 root).

**Comment by jasonwilliams200OK** [comment]
> I think casing should be consistent across operating systems

Agree, and since this is all canonical paths resolution and we are not hitting the FS to check if either of the paths actually exist, it should just abide by the casing of user input.

**Comment by jamesqo** [comment]
Looks good. As long as we avoid making I/O calls, :+1:

**Comment by JeremyKuhne** [comment]
>>I think casing should be consistent across operating systems

>Agree, and since this is all canonical paths resolution and we are not hitting the FS to check if either of >the paths actually exist, it should just abide by the casing of user input.

If we want it to be consistent then it should be case insensitive. GetFullPath doesn't normalize the casing (and there is no easy, performant way to do so). It is much more likely to run into accidentally ending up with two casings for the same path than two paths with differing casing.

**Comment by jaredpar** [comment]
@JeremyKuhne `GetFullPath` is insensitive on all OS?  If so I can see that being fine for `GetRelativePath`.  This is more of a string operation and can operate on files that don't actually exist on disk.

**Comment by JeremyKuhne** [comment]
@jaredpar Yes, 'GetFullPath' doesn't normalize the casing on any OS, so it's technically insensitive. Fyi- There is another open request to provide an API that gets the canonical cased version of a path.

**Comment by jasonwilliams200OK** [comment]
> There is another open request to provide an API that gets the canonical cased version of a path.

https://github.com/dotnet/corefx/issues/1086, that would be a nice little addition in File/Directory Info types :blush:

**Comment by stephentoub** [comment]
> Here is what we concluded
> public string GetRelativePath(string relativeTo, string path)

Just to clarify, this is still going to be a static method somewhere, right?  Where did we land in terms of what class this lives in... on Path?

**Comment by JeremyKuhne** [comment]
>Just to clarify, this is still going to be a static method somewhere, right? Where did we land in terms of what class this lives in... on Path?

This will be a static method on Path.

**Comment by terrajobst** [comment]
@stephentoub, @JeremyKuhne 

Good points. I've updated the declaration to reflect namespace and type.

**Comment by JeremyKuhne** [comment]
Here is the final proposal (on `System.IO.Path`):

``` c#
/// <summary>
/// Create a relative path from one path to another. Paths will be resolved before calculating the difference.
/// Case will be ignored.
/// </summary>
/// <param name="relativeTo">The source path the output should be relative to.</param>
/// <param name="path">The destination path.</param>
/// <returns>The relative path or <paramref name="path"/> if the paths don't share the same root.</returns>
/// <exception cref="ArgumentNullException">Thrown if <paramref name="relativeTo"/> or <paramref name="path"/> is null or an empty string.</exception>
public static string GetRelativePath(string relativeTo, string path)
{
    return GetRelativePath(relativeTo, path, ignoreCase: true);
}

/// <summary>
/// Create a relative path from one path to another. Paths will be resolved before calculating the difference.
/// </summary>
/// <param name="relativeTo">The source path the output should be relative to.</param>
/// <param name="path">The destination path.</param>
/// <param name="ignoreCase">Ignore casing if true.</param>
/// <returns>The relative path or <paramref name="path"/> if the paths don't share the same root.</returns>
/// <exception cref="ArgumentNullException">Thrown if <paramref name="relativeTo"/> or <paramref name="path"/> is null or an empty string.</exception>
public static string GetRelativePath(string relativeTo, string path, bool ignoreCase)
{
    // IMPL
}
```

**Comment by jamesqo** [comment]
@JeremyKuhne What will happen if `ignoreCase: false` is passed in on Windows? Will the path be canonicalized, e.g. with `GRP(@"C:\", "./tEsT", ignoreCase: true)` and the actual name of the directory being `Test`, will the return value be `@"C:\Wherever\Test"`?

**Comment by JeremyKuhne** [comment]
We decided to start with the following:

``` c#
/// <summary>
/// Create a relative path from one path to another. Paths will be resolved before calculating the difference.
/// Default platform casing will be used to compare paths (OrdinalIgnoreCase on Windows, Ordinal otherwise).
/// </summary>
/// <param name="relativeTo">The source path the output should be relative to. This path is always considered to be a directory.</param>
/// <param name="path">The destination path.</param>
/// <returns>The relative path or <paramref name="path"/> if the paths don't share the same root.</returns>
/// <exception cref="ArgumentNullException">Thrown if <paramref name="relativeTo"/> or <paramref name="path"/> is null or an empty string.</exception>
public static string GetRelativePath(string relativeTo, string path)
{
    // Get the relative path using platform specific comparison
}
```

It was agreed that following typical casing rules for the active platform (OrdinalIgnoreCase for Windows, Ordinal for Unix/Mac) would be the most successful for cross platform use. On Windows, casing variance is very common and there currently isn't a way to canonicalize casing, but there are active pending issues around this functionality (#1086, #3156). While Unix supports FAT and NTFS, it is expected that it is more likely on Unix to have multiple real paths that vary only by case than multiple variants of a path from a mounted FAT volume.

We want to give more thought to and take more input on exposing casing options and consider how it meshes design discussions surrounding path canonicalization.

Behavior:

- Casing handling will be platform specific.
- We avoid hitting the disk.
- We will not check if relativeTo is a directory or file. We'll assume it's a directory.
- We will not enforce that it ends with a DirectorySeparator.
- Both relativeTo and path will be passed to Path.GetFullPath() before processing.

We guarantee that:

```
casing := Choose(Windows: StringComparison.OrdinalIgnoreCase, Rest: StringComparison.Ordinal)

string.Equals(Path.GetFullPath(Path.Combine(relativeTo, GetRelativePath(relativeTo, path))),
              Path.GetFullPath(path),
              casing)
```

**Comment by weltkante** [comment]
Apparently this API made it only to .NET Core and neither into .NET Standard nor Desktop Framework? Any plans on including it in either of them?

**Comment by JeremyKuhne** [comment]
> Apparently this API made it only to .NET Core and neither into .NET Standard nor Desktop Framework? Any plans on including it in either of them?

Thanks for asking. The intent is to get this into Desktop and Standard eventually. I've marked the PR appropriately so that we won't miss it.
