### ISSUE TITLE
Native code does not compile under arm64

### ISSUE THREAD

**Issue by manu-silicon** [dotnet/corefx#6195]
I'm looking into it.

**Comment by stephentoub** [comment]
Is this still an issue after https://github.com/dotnet/corefx/pull/6585?

**Comment by manu-silicon** [comment]
not via cross compilation yet.

**Comment by stephentoub** [comment]
@manu-silicon, are you still working on this?  If yes, we can leave it open.  If not, I'll close it for now.

**Comment by manu-silicon** [comment]
It might be related to #6769 but I should have flagged it a while back. Now I'm not so sure. I would close it.

**Comment by stephentoub** [comment]
Thanks.
