### ISSUE TITLE
Unable to register Trace Listener in CORE CLR 

### ISSUE THREAD

**Issue by jayaranigarg** [dotnet/corefx#6196]
I want to capture logs in Core CLR and want to register a trace listener for same. But I am unable to find a way to do so.
This can be achieved in Full CLR in this way:

```
TextWriterTraceListener writer = new TextWriterTraceListener(System.Console.Out);
Debug.Listeners.Add(writer);
```

I want to achieve same thing in Core CLR but TextWriterTraceListner is not available in core CLR.
How can this be achieved?

**Comment by mellinoe** [comment]
Have you tried the `System.Diagnostics.TextWriterTraceListener` package?

https://www.nuget.org/packages/System.Diagnostics.TextWriterTraceListener/

https://github.com/dotnet/corefx/blob/ac67ffac987d0c27236c4a6cf1255c2bcbc7fe7d/src/System.Diagnostics.TextWriterTraceListener/src/System/Diagnostics/TextWriterTraceListener.cs

**Comment by mellinoe** [comment]
I'm going to close this as adding a reference to the above package should solve your issue. Let me know if you see any other problems with this.

**Comment by mellinoe** [comment]
@stephentoub correctly noted that, while `TextWriterTraceListener` is available, `Debug.Listeners` does not. So you wouldn't be able to register a listener to debug events. @jayaranigarg Is that an important scenario for you, or do you just need `TextWriterTraceListener`?

**Comment by jayaranigarg** [comment]
Hi mellinoe, 
I do need to register a listener to debug events. Just `TextWriterTraceListener`  won't do.
Also the mentioned package requires _.NET 5.1_ but I need it for _.Net 4.5_ or maybe a little lower dotnet version.
