### ISSUE TITLE
Multiple nuget src\ dirs?

### ISSUE THREAD

**Issue by mmitche** [dotnet/corefx#621]
Why are there multiple nuget src dirs.?  There is a .nuget with a single file and a nuget with multiple files.  Was this an oversight?  Can I fix/combine them?

**Comment by weshaggard** [comment]
@mmitche  Can you list the paths to these directories, it is unclear to me from your description. Are you referring to src\.nuget and src\nuget directories?

**Comment by mmitche** [comment]
src\.nuget and src\nuget

It seems unclear to me why we have both if these.

**Comment by mmitche** [comment]
(btw apparently the markup is eliminating the \ before .nuget, it's src \ .nuget

**Comment by weshaggard** [comment]
Yes I will look into fixing this as part of some of the other things I'm looking into.

**Comment by mmitche** [comment]
Awesome, thanks!

**Comment by ellismg** [comment]
Do we still plan to do something here?  I sort of understand the split between the two folders.  Maybe rename the one holding the nuspec's to something else?

**Comment by mmitche** [comment]
@weshaggard We could rename the folder, though I'm not convinced this is a real problem.

**Comment by weshaggard** [comment]
It isn't a real problem, it is just a clean-up item, and if it never happens nothing bad happens :)
I'm going to close this issue as it will likely naturally get fixed when we fully support building our packages on github.
