### ISSUE TITLE
WindowAndCursorProps.Title_Set failed on Windows 10

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#6223]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win10_debug/91/consoleFull
```
10:33:10      WindowAndCursorProps.Title_Set [FAIL]
10:33:10         System.IO.IOException : No process is on the other end of the pipe
10:33:10         Stack Trace:
10:33:10            d:\j\workspace\outerloop_win---0cba2915\src\System.Console\src\System\ConsolePal.Windows.cs(539,0): at System.ConsolePal.set_Title(String value)
10:33:10            d:\j\workspace\outerloop_win---0cba2915\src\System.Console\src\System\Console.cs(265,0): at System.Console.set_Title(String value)
10:33:10            d:\j\workspace\outerloop_win---0cba2915\src\System.Console\tests\WindowAndCursorProps.cs(107,0): at WindowAndCursorProps.Title_Set()
```

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win10_release/89/consoleFull

**Comment by pallavit** [comment]
Interesting. Our code is pretty vanilla. We simply call into windows SetConsoleTitle API here. Looking at the history, this test seems to have started failing recently. Is that correct? I will look into windows code to see when we end up throwing IOException, msdn does not give much details.

**Comment by pallavit** [comment]
I tried to repro this issue locally by running the Title_set test method in isolation in a loop for over 5 mins but could not repro the issue. I also tried running the complete test in the similar fashion with no results. A native app also worked as expected (Os used: win blue and win10). I also looked at the windows code to see when we throw this exception but could not formulate a theory. 

Interestingly, we have only seen this call failing in Title_set test method and not in Title test method both of which call set_Title. For now, I am thinking since we get the same coverage in both the test methods I will remove this but that would only help us unblock. Let me know if you have any other ideas?

**Comment by stephentoub** [comment]
It's very strange that the one is failing and the other is not.  The difference seems simply to be that in one, we access the getter first, whereas in the other, we don't.  I've never seen this fail locally, either.

**Comment by pallavit** [comment]
Yes but I would doubt there will be any dependency between them and even if there was we should still be able to repro this when run in a loop.

**Comment by stephentoub** [comment]
The Title test just failed:
```

**Comment by stephentoub** [comment]
Here, too:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win10_release/121/consoleText

**Comment by stephentoub** [comment]
It's failing pretty consistently, e.g.
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win10_debug/131/consoleFull
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win10_release/124/consoleFull

**Comment by pallavit** [comment]
> System.IO.IOException : No process is on the other end of the pipe

This makes me think as if the call to set_itle was delegated to a background process or something which ran after the current console window died, again could this be the way things get run in our infra?

**Comment by pallavit** [comment]
I tried to repro this issue using the same commands that run in Jenkins for outer loop testing on win10 rtm machine - 

> call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86   && Build.cmd /p:ConfigurationGroup=Debug /p:Outerloop=true /p:TestWithLocalLibraries=true 

But all the System.Console.Tests passed. @Priya91 What is the best way to disable a test only on windows10 and only on outerloop runs? I will keep this bug open under the rtm milestone, however it would be best to disable the test for now to keep the ci clean.

**Comment by Priya91** [comment]
@pallavit Consider using ```ConditionalFact```, you'll have to define a property/method that is true for Windows10, and then pass the property/method name to the ```ConditionalFact``` argument.
