### ISSUE TITLE
Windows 7 outer loop test runs failing finding vcvarsall.bat

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#6224]
```
05:45:09 d:\j\workspace\outerloop_win---627ab81b>call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86   && Build.cmd /p:ConfigurationGroup=Release /p:WithCategories="InnerLoop;OuterLoop" /p:TestWithLocalLibraries=true 
05:45:09 '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"' is not recognized as an internal or external command,
05:45:09 operable program or batch file.
```

**Comment by joshfree** [comment]
how long has this been failing?

**Comment by stephentoub** [comment]
> how long has this been failing?

You can see the history here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win7_debug/

**Comment by Priya91** [comment]
Seems like the win7 machines dont have the C++ toolset. I don't know how to connect to these azure vms. Will sync up with @mmitche

**Comment by Priya91** [comment]
Restarted an Outerloop_win7_debug run [#87](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win7_debug/87/console) 

It finds the vcvarsall.bat. Closing this issue as fixed.
