### ISSUE TITLE
Add Arm64 support in RuntimeInformation

### ISSUE THREAD

**Issue by manu-silicon** [dotnet/corefx#6230]
Currently there is no Arm64 support in CoreFX. I've added support in the native part (see PR #6229), but the managed part needs to go through a review process which I'm opening here.

The simple change requested is to add the Arm64 enum entry to the various enum types listing all the supported platforms. However this is not sufficient, the various platform/OS implementation of RuntimeInformation needs to be updated to take into account this new value.

Here is the list of C# classes that will be most likely need to be updated (list is not exhaustive):

```
src/System.Runtime.InteropServices.RuntimeInformation/ref/System.Runtime.InteropServices.RuntimeInformation.cs
src/System.Runtime.InteropServices.RuntimeInformation/src/System/Runtime/InteropServices/RuntimeInformation/Architecture.cs
src/System.Runtime.InteropServices.RuntimeInformation/src/System/Runtime/InteropServices/RuntimeInformation/RuntimeInformation.Windows.cs
src/System.Runtime.InteropServices.RuntimeInformation/src/System/Runtime/InteropServices/RuntimeInformation/RuntimeInformation.Unix.cs
src/Common/src/Interop/Windows/mincore/Interop.SYSTEM_INFO.cs
src/Common/src/Interop/Unix/System.Native/Interop.GetUnixArchitecture.cs
src/System.Runtime/ref/System.Runtime.cs
```

**Comment by mellinoe** [comment]
We may just want to scope this to adding support in RuntimeInformation. The System.Runtime changes, for example, will be much more difficult to make as it will require us to change mscorlib, port changes to desktop (if we want compatiblity), etc. as that is where the `ProcessorArchitecture` enum is implemented. I assume that is what you were referring to when you said that ref/System.Runtime.cs will need to change. Adding support for this in RuntimeInformation should be very straightforward, as it is a completely new and portable library.

**Comment by manu-silicon** [comment]
@mellinoe That's what I mean. Agreed for System.Runtime, but I would not be surprised if this was added shortly in mscorlib as work on arm64 is progressing in CoreCLR.

**Comment by Priya91** [comment]
The Arm64 arch has been added to RuntimeInformation. Closing this issue, since it's tracking it.
