### ISSUE TITLE
HelloWorld WinRT Dependency?

### ISSUE THREAD

**Issue by ProTip** [dotnet/corefx#625]
Hello,

I'm trying to build the HelloWorld demo based off the Blog post instructions.  It looks like the nuget.org packages aren't quite synced up, so that's a shame and I'm using 22416 instead.  After I build and attempt to run the program I get an error stating that winrt-string is missing.  Should this be working on Windows 7?

-Thanks

**Comment by ProTip** [comment]
I believe this problem is related to this issue in CLR: https://github.com/dotnet/coreclr/issues/65

**Comment by KrzysztofCwalina** [comment]
I just committed a fix to this. To compile the application for Windows 7, you need to get the new bits and follow the instructions described in the CoreFxLab wiki, i.e. uncomment a line in the HelloWorld.csproj file that enables Windows 7 build.
