### ISSUE TITLE
System.Private.Uri lacks a solution file

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#6266]
...I'm not sure if this is deliberate, or what else may be going on here (given the local `pkg` directory).
A quick search didn't appear to have the project/directory included in anything else.

**Comment by JonHanna** [comment]
It is indeed; https://github.com/dotnet/corefx/blob/master/src/System.Runtime/System.Runtime.sln#L16

**Comment by davidsh** [comment]
We don't intend to add a solution for this at this point in time.
