### ISSUE TITLE
Add System.Runtime.InteropServices.Architecture.Arm64

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#6276]
Title says it all. Arm64 is inevitable. There is no reason for dragging our feet to add the enum value for it.

**Comment by benaadams** [comment]
Timing!

I was just looking to see if I could set up ASP.NET Core on a 950 XL which is Arm64 :)

**Comment by stephentoub** [comment]
> There is no reason for dragging our feet to add the enum value for it.

+1

**Comment by benaadams** [comment]
Don't know what mode the O/S is in though...

**Comment by mellinoe** [comment]
See also https://github.com/dotnet/corefx/issues/6230

**Comment by Priya91** [comment]
Also #4384

**Comment by Priya91** [comment]
API approved in email.

cc @terrajobst

**Comment by terrajobst** [comment]
Discussed offline. We don't see a problem with exposing this.

@weshaggard I assume we can't add this enum to .NET Framework at this point.

**Comment by Priya91** [comment]
@terrajobst This assembly is OOB and hasn't shipped a stable version yet. This can be in RTM.

**Comment by terrajobst** [comment]
@Priya91 Thanks for clarifying. In that case, we should indeed do it for RTM.

**Comment by weshaggard** [comment]
Agreed

**Comment by jkotas** [comment]
Fixed by https://github.com/dotnet/corefx/pull/6320

**Comment by manu-silicon** [comment]
:+1: Thanks
