### ISSUE TITLE
Some ArgumentNullExceptions pass the message as the parameter name

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#6283]
Several thrown argument null exceptions pass the message as the parameter name, resulting in some weird behaviour. 

I put a fix for this over at coreclr (most of the ones I found are not included in corefx, e.g. stringBuilder)

**Comment by hughbe** [comment]
https://github.com/dotnet/coreclr/pull/2889 Whoops I forgot the URL

**Comment by Priya91** [comment]
@hughbe Is this pattern observed in corefx? a general search doesn't give any hits.. Most of corefx is using ```nameof``` operator.

**Comment by hughbe** [comment]
Nope just in coreclr I think. Especially not after nameof
I only mentioned this in corefx because I read somewhere that issues about mscorlib should be posted in corefx

**Comment by ctyar** [comment]
I searched the hole reop for usages of ArgumentNullException without `nameof` and some of them have this issue. for example:
https://github.com/dotnet/corefx/blob/master/src/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs#L758
```
                for (i = 0; i < args.Length; i++)
                    {
                        if (args[i] == null)
                            throw new ArgumentNullException(SR.ArgsCantBeNull, nameof(args));

                        argPtrs[i] = Marshal.StringToHGlobalUni(args[i]);
                    }
```
If its ok I can send a PR to fix them all

**Comment by hughbe** [comment]
@ctyar  go for it!
