### ISSUE TITLE
PublicKeyTests.TestKey_RSA failure on Unix in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#6302]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/centos7.1_release_tst_prtest/1959/console

```
17:10:15    System.Security.Cryptography.X509Certificates.Tests.PublicKeyTests.TestKey_RSA [FAIL]
17:10:15       Assert.Equal() Failure
17:10:15       Expected: Byte[] [232, 175, 92, 162, 32, ...]
17:10:15       Actual:   Byte[] [0, 0, 0, 0, 0, ...]
17:10:15       Stack Trace:
17:10:16             at System.Security.Cryptography.X509Certificates.Tests.PublicKeyTests.TestKey_RSA()
```

**Comment by ericeil** [comment]
Another failure, also on CentOS:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/centos7.1_release_tst_prtest/2647/consoleFull#-21371504001f1a4601-6aec-4fd5-b678-78d4389fd5e8

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/centos7.1_release_tst_prtest/2904/console
```
06:49:04    System.Security.Cryptography.X509Certificates.Tests.PublicKeyTests.TestKey_RSA [FAIL]
06:49:04       Assert.Equal() Failure
06:49:04       Expected: Byte[] [232, 175, 92, 162, 32, ...]
06:49:04       Actual:   Byte[] [0, 0, 0, 0, 0, ...]
06:49:04       Stack Trace:
06:49:04             at System.Security.Cryptography.X509Certificates.Tests.PublicKeyTests.TestKey_RSA()
```

**Comment by stephentoub** [comment]
Failed again here, but this time on OSX:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst_prtest/2704/console
```
03:01:51    System.Security.Cryptography.X509Certificates.Tests.PublicKeyTests.TestKey_RSA [FAIL]
03:01:51       Assert.Equal() Failure
03:01:51       Expected: Byte[] [232, 175, 92, 162, 32, ...]
03:01:51       Actual:   Byte[] [0, 0, 0, 0, 0, ...]
03:01:51       Stack Trace:
03:01:51             at System.Security.Cryptography.X509Certificates.Tests.PublicKeyTests.TestKey_RSA()
```

**Comment by stephentoub** [comment]
Failed again:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/ubuntu_release_tst_prtest/4064/console
```
14:40:27    System.Security.Cryptography.X509Certificates.Tests.PublicKeyTests.TestKey_RSA [FAIL]
14:40:27       Assert.Equal() Failure
14:40:27       Expected: Byte[] [1, 0, 1]
14:40:27       Actual:   Byte[] []
14:40:27       Stack Trace:
14:40:28             at System.Security.Cryptography.X509Certificates.Tests.PublicKeyTests.TestKey_RSA()
```

**Comment by stephentoub** [comment]
I think we should investigate this for 1.0.0-rtm... it could potentially be a product bug.

**Comment by stephentoub** [comment]
This is still happening, e.g.
http://ci.dot.net/job/dotnet_corefx/job/master/job/opensuse42.1_release/142/
http://ci.dot.net/job/dotnet_corefx/job/master/job/osx_release/283/
https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu14.04_release/451/
https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu16.04_release/414/
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx_release/483/

**Comment by danmosemsft** [comment]
@steveharter

**Comment by stephentoub** [comment]
Again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx_release_prtest/1146/consoleText

**Comment by danmosemsft** [comment]
@steveharter could you please take a look? this seems like a correctness issue, as well as CI impact.

@bartonjs

**Comment by JeremyKuhne** [comment]
This happens regularly- and I think it may also be causing seg faults sometimes.

**Comment by stephentoub** [comment]
Again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/centos7.1_release_prtest/2055/consoleText

**Comment by danmosemsft** [comment]
According to this it has failed 4 times in Dec/Jan

http://jdash.azurewebsites.net/builds/test?name=System.Security.Cryptography.X509Certificates.Tests.PublicKeyTests.TestKey_RSA&viewName=dotnet_corefx&pr=true&startDate=2016-12-01&limit=20   (check 'include PRs')

**Comment by danmosemsft** [comment]
@bartonjs could you comment? What is the next action? This seems likely to be a real product issue and potentially significant.

**Comment by bartonjs** [comment]
@danmosemsft The proposal I discussed with @steveharter was to make the test do something like

```c#
RSA rsa = cert.GetRSAPublicKey();
RSAParameters rsaParameters = rsa.ExportParameters(false);

if (!expectedModulus.SequenceEqual(rsaParameters.Modulus) ||
    !expectedExponent.SequenceEqual(rsaParameters.Exponent)
{
    rsaParameters = rsa.ExportParameters(false);

    if (!expectedModulus.SequenceEqual(rsaParameters.Modulus) ||
        !expectedExponent.SequenceEqual(rsaParameters.Exponent)
    {
        Assert.False(true, "Second call to ExportParameters produced valid data, but the first did not");
    }

    rsa = rsa.GetRSAPublicKey();
    rsaParameters = rsa.ExportParameters(false);

    if (!expectedModulus.SequenceEqual(rsaParameters.Modulus) ||
        !expectedExponent.SequenceEqual(rsaParameters.Exponent)
    {
        Assert.False(true, "New key handle ExportParameters was successful, original key handle was not");
    }    

    Assert.False(true, "Key's busted");
}
```

(Though ensuring a) it compiles, and b) that the messages are all correct/useful)

**Comment by danmosemsft** [comment]
OK, good that it's not a product bug then. Do either of you have cycles to make this change?

**Comment by bartonjs** [comment]
> OK, good that it's not a product bug then.

Well, we don't know that it is or isn't.  This is just the good old "add logging to figure out what sort of problem we're facing", since it hasn't reproed for me under at least a million runs (not sarcastic; did a `seq 1 1000000` launch loop, and it finished, having never failed).

**Comment by stephentoub** [comment]
Again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/centos7.1_release_prtest/2268/consoleText
```
System.Security.Cryptography.X509Certificates.Tests.PublicKeyTests.TestPublicKey_Key_RSA [FAIL]
        Assert.Equal() Failure
        Expected: Byte[] [232, 175, 92, 162, 32, ...]
        Actual:   Byte[] [0, 0, 0, 0, 0, ...]
        Stack Trace:
           /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_release_prtest/src/System.Security.Cryptography.X509Certificates/tests/PublicKeyTests.cs(212,0): at System.Security.Cryptography.X509Certificates.Tests.PublicKeyTests.VerifyKey_RSA(RSA rsa)
```

**Comment by danmosemsft** [comment]
Alright, I'll add this since nobody is biting. :)

**Comment by steveharter** [comment]
I'll start on this later today.

**Comment by danmosemsft** [comment]
Steve I already added the logging. Thanks!

**Comment by danmosemsft** [comment]
@jiangzeng @Jiayili1 when this test fails again please let me know so we can grab the extra logging that 's now added. thanks.

**Comment by danmosemsft** [comment]
Closing to make sure this gets opened when there's logging.

**Comment by mellinoe** [comment]
I hit this again:

https://ci.dot.net/job/dotnet_corefx/job/release_2.0.0/job/ubuntu14.04_release_prtest/27/consoleText

**Comment by ViktorHofer** [comment]
@mellinoe looks like a different test

**Comment by bartonjs** [comment]
@ViktorHofer Yes, its a different test, but it's the same problem.

**Comment by ianhays** [comment]
@bartonjs think we should add [the extra validation Dan added](https://github.com/dotnet/corefx/pull/15302) to this test as well? It would of course be a bit different since we're loading xml and not using an x509 cert, but the validation would be mostly the same.

**Comment by bartonjs** [comment]
@ianhays I sort of wonder if we want to do something weird and put it as self-debugging code (in \#if DEBUG) in the product code itself.

If it's about to export Exponent == all zeros or Modulus == all zeros, and it's in debug, either do the retry and throw a "it's a miracle, retry worked!" or "totes seems borked, dude..." exception.

Or if it catches it to just crashdump so we can see what happened.... if we have that power.

**Comment by steveharter** [comment]
@bartonjs I think the product-wise DEBUG option would find the issue quicker, and help with a fix especially if we need to add re-try logic to certain OpenSsl calls.

**Comment by bartonjs** [comment]
@ianhays Do you want to take care of moving the retry into a \#if DEBUG section?  Since we don't know what "wrong" means we'll just have to check for all zeros.

There are a couple places that could benefit:
* [ExtractBignum](https://github.com/dotnet/corefx/blob/bfac45af5dddcbd70b6935fcf92b4b8755f3cd1c/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.Bignum.cs#L75-L81) between when the `fixed` block ends and it returns the buffer.  But there the logic would need to ensure that we weren't actually trying to export the number 0.  So `if (compactSize > 1 && buf[offset] == 0) DoSomethingDebuggyLikeCrashdump();
* [ExportRsaParameters](https://github.com/dotnet/corefx/blob/bfac45af5dddcbd70b6935fcf92b4b8755f3cd1c/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.Rsa.cs#L97).  Modulus can't start with a 0, Exponent can't start with a 0. None of the private parameters can be 0 (but they can start with 0.  Except maybe D, I'm having trouble projecting that one in my head).

**Comment by ianhays** [comment]
Yeah, I'll take this one.

**Comment by steveharter** [comment]
FWIW here's Jenkins history since last December including the release branch. I can't say whether each of these failed for the same reason this issue is tracking, since that level of history isn't available.

Pretty much every flavor of Linux + Mac.

```
Test Case: System.Security.Cryptography.X509Certificates.Tests.PublicKeyTests.TestKey_RSA
Failed Jenkins Jobs
Build Number 	Machine Name 	Date 	PR Author 	PR Link
dotnet_corefx/master/ubuntu14.04_release 686 	ubuntu1404-20160211-1-eb1c90 	11/01 07:28 PM 		0
dotnet_corefx/master/fedora24_release 22 	fedora24-20161024-71ea70 	11/03 10:38 PM 		0
dotnet_corefx/master/fedora23_release 608 	fedora23-20160622-f01740 	11/03 06:10 PM 		0
dotnet_corefx/release_1.1.0/rhel7.2_release 26 	rhel72-20160211-c51390 	12/28 10:53 PM 		0
dotnet_corefx/release_1.1.0/outerloop_osx_release 17 	dci-macpro-03 	12/29 08:15 PM 		0
dotnet_corefx/release_1.1.0/debian8.4_release 32 	deb84-20160623-694230 	01/03 01:39 PM 		0
dotnet_corefx/release_1.1.0/outerloop_ubuntu16.04_release 30 	ubuntu1604-20160510-outereb0800 	01/07 05:16 AM 		0
dotnet_corefx/release_1.1.0/outerloop_osx_release 33 	dci-macpro-02 	01/16 08:16 PM 		0
dotnet_corefx/release_1.0.0/opensuse13.2_release 59 	suse132-20160315-323e30 	01/19 02:07 PM 		0
dotnet_corefx/release_1.0.0/osx_release 67 	dci-macpro-02 	01/19 03:04 AM 		0
dotnet_corefx/release_1.0.0/outerloop_osx_release 34 	dci-macpro-02 	01/22 04:29 AM 		0
dotnet_corefx/release_1.1.0/ubuntu14.04_release 133 	ubuntu1404-20160211-1-24f8f1 	03/10 05:19 PM 		0
```

**Comment by karelz** [comment]
All failures are in release builds :(

**Comment by steveharter** [comment]
Good catch @karelz. Also I updated the list to further back - still only release builds

**Comment by bartonjs** [comment]
Yeah, I hadn't noticed that.  Good eye, Karel.  Hmm.

**Comment by karelz** [comment]
Could we add a hack to crash hard when env. var. is set and it happens? (and set the env. var. in Jenkins & Helix)

**Comment by karelz** [comment]
BTW: If chasing down this bug means also updating 1.x, I'd support it

**Comment by ianhays** [comment]
@steveharter does the jdash report accurately show failures from PRs? [I looked to JDash for the failures linked in this issue, but they appear to be missing](http://jdash.azurewebsites.net/builds/test?name=System.Security.Cryptography.X509Certificates.Tests.PublicKeyTests.TestKey_RSA&viewName=dotnet_corefx&pr=True&limit=1000&startDate=2016-1-01). The last non-release branch failure on jdash occurred on 11/03, but Stephen linked failures from January above.

**Comment by steveharter** [comment]
@ianhays I also included PRs in my query, and none showed up, so yes something is amiss in the data.

**Comment by bartonjs** [comment]
I'm like 99% sure I just found the missing GC.KeepAlive and the confusing scenario that bound it all up.

Thanks @karelz  for noticing the release-only, and @steveharter for getting a stable repro with that knowledge.

**Comment by karelz** [comment]
Congrats on chasing down the issue after 1+ year of rare, yet annoying, occurrences! -- Great work! Thanks to everyone helping to catch it.

BTW: @danmosemsft is now tracking down why we didn't run all tests under GCStress=3 on Release mode as we planned. We will finish that off as well.
