### ISSUE TITLE
System.Net.Sockets.APMServer.Tests Hang on OSX in CI

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#6306]
The [test run hung](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/1251/console) and the job was aborted.

> Build timed out (after 120 minutes). Marking the build as aborted.
22:43:45 ./run-test.sh: line 131:   529 Terminated: 15          ./corerun xunit.console.netcore.exe $testDllName -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=$xunitOSCategory -notrait Benchmark=true
22:43:45 error: One or more tests failed while running tests from 'System.Net.Sockets.APMServer.Tests'.  Exit code 143.

**Comment by stephentoub** [comment]
We've been hitting this a fair bit, especially on OS X.  I believe it's the same as https://github.com/dotnet/corefx/issues/6218, just not as frequent.
