### ISSUE TITLE
Cannot build from clone

### ISSUE THREAD

**Issue by citizenmatt** [dotnet/corefx#632]
As per the [developer guide](https://github.com/dotnet/corefx/wiki/Developer-Guide), if I clone the repo, start a VS2013 command prompt and run `build.cmd`, I don't get a clean build. There are lots of warnings shown, as well as several errors regarding to references to `System.Runtime`. The tests for `System.Collections.Immutable` are run, but no others. Loading the solutions in VS2013 doesn't work, as all of the references are empty (there's a comment in the `.csproj` that states all references come from `packages.config`).

Either the docs are out of date, or something's changed, or broken. Any ideas?

**Comment by nguerrera** [comment]
The steps are up to date. Do you have VS 2013 Update 3 or later installed?

**Comment by citizenmatt** [comment]
Yep, running VS2013 Update 4. Here's [a gist with the console output](https://gist.github.com/citizenmatt/1b69b5f4c2bd219e18e4). There's also a 4.5 Mb msbuild.log that doesn't shed any more light - it reports the same warnings about being unable to "find a matching group".

**Comment by akoeplinger** [comment]
@citizenmatt This looks like https://github.com/dotnet/corefx/issues/449

**Comment by citizenmatt** [comment]
Yep. Sounds like it's the same thing. Thanks for pointing it out - I wouldn't have found it otherwise!

**Comment by ellismg** [comment]
Closing this duplicate issues.  If it ends up being something different feel free to reopen.
