### ISSUE TITLE
Failure in ProcessTests, unable to find specified file

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#633]
Every now and then, our CI builds are failing spectacularly with 28 out of 36 ProcessTests failing to run due to a Win32Exception stating that the specified file could not be found.

**Comment by nguerrera** [comment]
@weshaggard I had already changed this locally, see https://github.com/nguerrera/corefx/compare/dotnet:v1.0...nguerrera:process-console-app-build

If this is the fix you had in mind, I can submit it as a PR. If not, I'll hold my changes...

**Comment by weshaggard** [comment]
@nguerrera Yes that is very similar to what I had in mind. Please go ahead and submit the PR for that. Thanks.
