### ISSUE TITLE
Complex.Equals(object) and Complex.Equals(Complex) do not always return the same result

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#6338]
## Context
Complex provides 3 main ways of testing equality of a complex:
- `Complex.Equals(Complex)`
- `Complex.Equals(object)`
- `==(Complex, Complex)`

## Problem
```
public override bool Equals(object obj)
{
    if (!(obj is Complex)) return false;
    return this == ((Complex)obj); // Problem is here.
}

public bool Equals(Complex value)
{
    return _real.Equals(value._real) && _imaginary.Equals(value._imaginary);
}

public static bool operator ==(Complex left, Complex right)
{
    return left._real == right._real && left._imaginary == right._imaginary;
}
```
The problem is that `Equals(object)` calls the `==` operator instead of the `Equals(Complex)` method. Note that the `==` operator and `Equals(Complex)` method have different code, and this causes discrepancies.

The problem mainly occurs with complex numbers containing `double.NaN`, as `double.NaN == double.NaN` returns `false`, but `double.NaN.Equals(double.NaN)` returns `true`.

## Example
As such, we get a strange example where the following code doesn't work as expected:
```
Complex complex1 = new Complex(double.NaN, double.NaN);
Complex complex2 = new Complex(double.NaN, double.NaN);

complex1.Equals(complex2); // True as expected
complex1.Equals((object)complex2); // False as unexpected
complex1 == complex2; // False as expected
```

## Solution
Fix the implementation of `Equals(object)` to the following:
```
public override bool Equals(object obj)
{
    if (!(obj is Complex)) return false;
    return Equals((Complex)obj);
}
```

This may have breaking change implications, but IMO should be fixed. I would be happy to send in a PR fixing this.

**Comment by JonHanna** [comment]
It definitely breaks the contract of `Equals()` and I imagine was just an oversight of not spotting the NaN case. Maybe someone will point out a backwards compatibility case, but I say go for it.

**Comment by mellinoe** [comment]
I think we will be able to do this for CoreCLR/.NET Core without an issue, but we will most likely need to "quirk" the behavior on the desktop framework if we ever want to port the change back there. That part isn't something you'd have to worry about, just pointing it out. There's also the possibility we don't want to bother porting this back to the desktop framework.

**Comment by hughbe** [comment]
Awesome. Would you like me to also port my PR to coreclr as well?

**Comment by mellinoe** [comment]
No, that shouldn't be necessary. If we do end up making that change it will have to be on our side and go through some approval processes as it would ship in an update to the .NET Framework. I was mostly just stating the above for our own consideration in the future.

**Comment by hughbe** [comment]
Understood.
