### ISSUE TITLE
UriBuilder needs some tests

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#6353]
## Problem
UriBuilder currently does not have any tests in corefx.
This means that changes to the class cannot be tested (especially if issues like #6351 and #3646 are fixed). Furthermore, it reduces the coverage report for System.Private.Uri.

## Solution
I have sent a PR with a complete set of tests covering 100% of UriBuilder. This is PR #6354

**Comment by davidsh** [comment]
We also have lots of Uri and UriBuilder tests internally but not yet ported them to CoreFx GitHub.

**Comment by davidsh** [comment]
cc: @CIPop @SidharthNabar

**Comment by hughbe** [comment]
@davidsh good to know.

I've been spending some spare time over Christmas on some Uri tests. Obviously coverage is not a perfect way of measuring, but those tests increase coverage to >70% from 30%.

They're pretty comprehensive IMO. If you have time, you can take a look here: https://github.com/hughbe/corefx/blob/de09b5a315185f13657b74a3b83738ff5b21c989/src/System.Runtime/tests/System/Uri.cs

The file's pretty long but I hope to split the test file up into smaller pieces in the future. 

I quite like the tests, but then again I'm biased ;)

**Comment by hughbe** [comment]
It also seems that the source code for System.Private.Uri is a bit of a mess, and in need of future refactoring. Therefore for my tests above I tried to find both common and corner cases. These may or may not be useful for your internal test suite too.

**Comment by davidsh** [comment]
Please do not do any refactoring of System.Private.Uri.  We know it is not pretty.  But we need to keep it as-is so that we can diff fixes between CoreFx (.NET Core) and .NET Framework.  Over time, we will get the code into a more maintainable state.

Thank you for your contributions and we will schedule the PR for review.

**Comment by hughbe** [comment]
Oh no I don't intend to do any refactoring, don't worry!
