### ISSUE TITLE
NullReferenceException in SmiMetaData.cs when running DataStreamTest

### ISSUE THREAD

**Issue by corivera** [dotnet/corefx#6355]
System.Data.SqlClient.ManualTesting.Tests.DataStreamTest.RunAllTestsForSingleServer_nwnd10SqlClient [FAIL]
	System.NullReferenceException : Object reference not set to an instance of an object.
	Stack Trace:
		D:\CoreFX\src\System.Data.SqlClient\src\Microsoft\SqlServer\Server\SmiMetaData.cs(294,0): at Microsoft.SqlServer.Server.SmiMetaData..ctor(SqlDbType dbType, Int64 maxLength, Byte precision, Byte scale, Int64 localeId, SqlCompareOptions compareOptions, String udtAssemblyQualifiedName, Boolean isMultiValued, IList`1 fieldTypes, SmiMetaDataPropertyCollection extendedProperties)
		D:\CoreFX\src\System.Data.SqlClient\src\Microsoft\SqlServer\Server\SmiMetaData.cs(568,0): at Microsoft.SqlServer.Server.SmiExtendedMetaData..ctor(SqlDbType dbType, Int64 maxLength, Byte precision, Byte scale, Int64 localeId, SqlCompareOptions compareOptions, String udtAssemblyQualifiedName, Boolean isMultiValued, IList`1 fieldMetaData, SmiMetaDataPropertyCollection extendedProperties, String name, String typeSpecificNamePart1, String typeSpecificNamePart2, String typeSpecificNamePart3)
		D:\CoreFX\src\System.Data.SqlClient\src\Microsoft\SqlServer\Server\SmiMetaData.cs(535,0): at Microsoft.SqlServer.Server.SmiExtendedMetaData..ctor(SqlDbType dbType, Int64 maxLength, Byte precision, Byte scale, Int64 localeId, SqlCompareOptions compareOptions, Boolean isMultiValued, IList`1 fieldMetaData, SmiMetaDataPropertyCollection extendedProperties, String name, String typeSpecificNamePart1, String typeSpecificNamePart2, String typeSpecificNamePart3)
		D:\CoreFX\src\System.Data.SqlClient\src\Microsoft\SqlServer\Server\SmiMetaData.cs(743,0): at Microsoft.SqlServer.Server.SmiStorageMetaData..ctor(SqlDbType dbType, Int64 maxLength, Byte precision, Byte scale, Int64 localeId, SqlCompareOptions compareOptions, Boolean isMultiValued, IList`1 fieldMetaData, SmiMetaDataPropertyCollection extendedProperties, String name, String typeSpecificNamePart1, String typeSpecificNamePart2, String typeSpecificNamePart3, SqlBoolean isKey)
		D:\CoreFX\src\System.Data.SqlClient\src\Microsoft\SqlServer\Server\SmiMetaData.cs(793,0): at Microsoft.SqlServer.Server.SmiQueryMetaData..ctor(SqlDbType dbType, Int64 maxLength, Byte precision, Byte scale, Int64 localeId, SqlCompareOptions compareOptions, Boolean isMultiValued, IList`1 fieldMetaData, SmiMetaDataPropertyCollection extendedProperties, String name, String typeSpecificNamePart1, String typeSpecificNamePart2, String typeSpecificNamePart3, SqlBoolean isKey)
		D:\CoreFX\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlDataReader.cs(301,0): at System.Data.SqlClient.SqlDataReader.GetInternalSmiMetaData()
		D:\CoreFX\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlCommand.cs(1259,0): at System.Data.SqlClient.SqlCommand.CompleteXmlReader(SqlDataReader ds, Boolean async)
		D:\CoreFX\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlCommand.cs(1122,0): at System.Data.SqlClient.SqlCommand.ExecuteXmlReader()
		D:\CoreFX\src\System.Data.SqlClient\tests\ManualTests\SQL\DataStreamTest\DataStreamTest.cs(555,0): at System.Data.SqlClient.ManualTesting.Tests.DataStreamTest.ExecuteXmlReaderTest(String connectionString)
		D:\CoreFX\src\System.Data.SqlClient\tests\ManualTests\SQL\DataStreamTest\DataStreamTest.cs(60,0): at System.Data.SqlClient.ManualTesting.Tests.DataStreamTest.RunAllTestsForSingleServer(String connectionString, Boolean usingNamePipes)
		D:\CoreFX\src\System.Data.SqlClient\tests\ManualTests\SQL\DataStreamTest\DataStreamTest.cs(44,0): at System.Data.SqlClient.ManualTesting.Tests.DataStreamTest.RunAllTestsForSingleServer_nwnd10SqlClient()

**Comment by corivera** [comment]
CC @saurabh500

**Comment by saurabh500** [comment]
@corivera Does this happen only for Share Memory ?
