### ISSUE TITLE
Possible typo in FileVersionInfoTest

### ISSUE THREAD

**Issue by mj1856** [dotnet/corefx#636]
This is low priority, but logging here so it doesn't get lost.

In [FileVersionInfoTest.cs line 239](https://github.com/dotnet/corefx/blob/0252409de5d77d4a104903a68d9ee34d54992e54/src/System.Diagnostics.FileVersionInfo/tests/FileVersionInfoTest.cs#L239):

    s_fviSecondNativeLibrary.ProductName = "Unkown_Product_Name";

"Unkown" should be "Unknown", but correcting it fails the test.  It should probably be first corrected wherever it originates from.

Thanks.

**Comment by ghuntley** [comment]
I'm guessing this breaks something that hasn't been publicly released yet as I don't see any references/dependancies within the corefx@master source tree.

    › ack Unkown_Product_Name
    src/System.Diagnostics.FileVersionInfo/tests/FileVersionInfoTest.cs
    256:        _fviSecondNativeLibrary.ProductName = "Unkown_Product_Name";

    › ack Unknown_Product_Name
    <nothing>

**Comment by ghuntley** [comment]
› ack Unkown_Product_Name
    src/System.Diagnostics.FileVersionInfo/tests/FileVersionInfoTest.cs
    256:        _fviSecondNativeLibrary.ProductName = "Unkown_Product_Name";

Digging further yields there is `src/System.Diagnostics.FileVersionInfo/tests/SecondNativeLibrary.dll` which contains the spelling mistake. Thus the actual unit test is "correct" and a source-code PR cannot be done until the source code for is released. Alternatively we could just modify the binary and submit it back as part of the PR.

**Comment by joshfree** [comment]
@ianhays could you track this one down please?
