### ISSUE TITLE
Typo in MetadataReaderTests

### ISSUE THREAD

**Issue by mj1856** [dotnet/corefx#637]
This is low priority, but logging here so it doesn't get lost.

In [MetadataReaderTests.cs lines 60 and 62](https://github.com/dotnet/corefx/blob/53abb169b8f7874db770c083aa52e9c1736aa7b4/src/System.Reflection.Metadata/tests/Metadata/MetadataReaderTests.cs#L60-L62):

            mdtAssemblyProperssor = 0x21000000,
            ...
            mdtAssemblyRefProperssor = 0x24000000,

Is "Properssor" a misspelling? I'm not sure if it should be "Processor" or "Preprocessor" or something else.

Thanks.

**Comment by mellinoe** [comment]
@nguerrera

**Comment by nguerrera** [comment]
Yes, that should be mdtAssemblyProcessor and mdtAssemblyRefProcessor. :)

**Comment by nguerrera** [comment]
Self-assigning to indicate that I'll help check that the right thing happens and merge it, but feel free to fix this and send a PR.

**Comment by mj1856** [comment]
Thanks for the clarification.  I'll update #591 to include this.  Thanks.

**Comment by nguerrera** [comment]
@mj1856 Thanks!

**Comment by nguerrera** [comment]
Fixed by #591
