### ISSUE TITLE
When does core clr throw CultureNotSupported exception?

### ISSUE THREAD

**Issue by cdmihai** [dotnet/corefx#6374]
On windows, `new CultureInfo("zh-CHS")` or `new CultureInfo("Shared")` (bogus name) throw a CultureNotFoundException. On OSX they don't.
However, "zh-CHS" was obtained by calling `CultureInfo.GetCultures(CultureTypes.AllCultures)` on full framework. reading #1669 I get the understanding that any string is now fair game and should be supported.

In light of this, when can one expect CultureNotFoundException and why is zh-CHS not recognized on windows, when the full framework API returns it as supported?

**Comment by tarekgh** [comment]
@cdmihai just wondering, why you are using zh-CHS and not using zh-Hans? zh-Hans is really the right name. zh-CHS is just supported in the desktop because it was kind of legacy and the standard zh-Hans was not introduced yet.

**Comment by cdmihai** [comment]
Long story actually :)
I was trying to make msbuild selfhost on coreclr and got into an issue where the string "Shared" was seen as a valid culture on OSX, but not on Windows (here is how we were checking if it's valid: https://github.com/Microsoft/msbuild/blob/ce30ce4dee76b7d27d9e6e2c7a2e13dfed054841/src/XMakeTasks/CultureInfoCache.cs#L46). The fact that some resource was seen as having the culture "Shared" as opposed to no culture lead msbuild down a weird execution path which ended up with that resource not getting referenced to csc, thus breaking the build.

In the end I fixed the issue by not using CultureInfo at all. It appears the code created those objects just so that it can get the culture names: https://github.com/Microsoft/msbuild/pull/504/files

I opened this issue when I actually wanted to keep using CultureInfo, and my implementation was that for full framework I would use CultureInfo.GetAll and for CoreClr I would manually instantiate CultureInfo objects from known culture name (obtained from the full framework list)

**Comment by tarekgh** [comment]
thanks @cdmihai I'll look at this.

**Comment by cdmihai** [comment]
I am tempted to pinvoke into specific OSes to get a list of supported cultures. I see that unix systems have `locale -a` which returns all the available locales (POSIX command). Unfortunately I'll also have to do some string manipulation to get the output consistent across platforms. Why doesn't corefx use this to populate GetCultures(CultureTypes.AllCultures)?

**Comment by tarekgh** [comment]
@cdmihai why you need to get the list of the locales in the first place? the direction now is culture identifier with right format (lang-region-script) considered valid culture even if the OS doesn't have real data for. for example if you request en-FJ will try to get the English Fiji even the data is not part of the shipped cultures. this is already implemented in Windows 10. by that, the enumeration of the cultures doesn't make sense anymore because returning any list doesn't mean that these are the only supported cultures. 
I would recommend you get rid of enumerating the cultures.

**Comment by tarekgh** [comment]
some quick update, we are working to expose CultureNotSupported exception. actually this is should be fully supported on corefx dev/api branch when running on Windows. will be fully supported on Linux soon too, 
Also I want to mention we are not going to support the names zh-CHS or zh-CHT in coreclr because these are just legacy names and not conforming to the standard/CLDR.

**Comment by iSazonov** [comment]
@tarekgh We catched the issue in POwerShell repo for Get-Culture cmdlet. 
Currently there is the CultureNotSupported exception in .Net Core 2.1 for Windows (for non-existent cultures with names with length > 3) but not for Linux and MacOs. Did your team decide not to add this fix to Linux and MacOs? Could you please share more information?

**Comment by tarekgh** [comment]
@iSazonov we depend on the underlying OS for creating the cultures. If the OS support the culture, then the framework will support it. if the OS doesn't support the culture, then we'll always throw CultureNotFoundException even on Linux/Mac. We are not specializing in Windows by any means here.

https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/src/System/Globalization/CultureInfo.cs#L250

If we are not throwing on Linux, means we were able to create the culture on that OS. On Linux/Mac we use the ICU library for that. 

Some other note, on Windows 10, any BCP-47 wellformed culture name will be supported on Windows 10 even there is no data for such a culture.

Let me know if you have any specific question I can help with.

**Comment by mklement0** [comment]
Thanks, @tarekgh.

> we were able to create the culture on that OS.

I think that's the crux: why would _getting_ a culture implicitly _create_ it?

While using a _constructor_ may look more like an act of creation, conceptually it isn't, and that is even more evident when using `CultureInfo.GetCultureInfo()`.

So while there is _some_ semblance of validation - namely if the specified name isn't _formally_ correct - it's still problematic to get fictitious cultures that aren't _predefined_, because the method doesn't suggest you're _creating them on demand_.

At the very least there should be an overload that either returns a predefined culture available on the system or throws an exception otherwise.

Some examples of problematic behavior (using PowerShell):

```powershell
# OK - bogus name that isn't even formally correct triggers an error.
PS> [cultureinfo]::GetCultureInfo('aintNoSuchThing') 
Exception calling "GetCultureInfo" with "1" argument(s): "Culture is not supported.
...

# PROBLEMATIC: a name that is formally correct, but definitely not a predefined culture,
#                            returns a - presumably useless - definition.
PS> [cultureinfo]::GetCultureInfo('zz-AA') 

LCID             Name             DisplayName
----             ----             -----------
4096             zz-AA            Unknown Locale (zz-AA)
```

Note that while what is formally correct is limited to a BCP-47 on Windows, as you state, on macOS and Linux the only formal constraint appears to be that the name length must not exceed 11 chars. - aside from that, apparently anything goes:

```powershell
# !! SUCCEEDS on macOS and Linux
PSonUnix> [cultureinfo]::GetCultureInfo('01;2.45"78&$')

LCID             Name             DisplayName
----             ----             -----------
4096             01;2             01;2

```

**Comment by iSazonov** [comment]
@tarekgh Thanks! Now I was able to create a test with CultureNotFoundException for `Get-Cuture` cmdlet.

I also agree with @mklement0  that this behavior is somewhat different for different platforms and this can surprise users. At least it's hard to write code with predictable behavior for all platforms that are expected from .Net Core.

**Comment by tarekgh** [comment]
> I also agree with @mklement0 that this behavior is somewhat different for different platforms and this can surprise users. At least it's hard to write code with predictable behavior for all platforms that are expected from .Net Core.

I am not sure why you need to write a code to distinguish the behavior across the platforms. .Net Core (and the full framework) is consistent here. we support whatever the OS support. Why do you think we need to fail a culture that the OS can create? 

if you disagree with the OS behavior (as Windows can create a culture which not having a data for), then feel free to send your complaint to the Windows team. They already spent enough time analyzing that and decided this way.  to summarize, the framework is transparent here and we already decided a long ago to depend on the OS behavior regardless the OS.

**Comment by mklement0** [comment]
@tarekgh:

> we support whatever the OS support.

Fully agreed that it's important not to hide any platform's native capabilities.

However, CoreFx has discretion with respect to how to _surface_ the native capabilities, and that's where my concern lies, which is unrelated to platform differences:

> Why do you think we need to fail a culture that the OS can create?

Why would _getting_ a culture (`CultureInfo.GetCultureInfo()`) from a _known list of predefined cultures_ (`CultureInfo.GetCultures(CultureTypes.AllCultures)`) result in _creating_ a culture if the name doesn't refer to an existing item on that list?

Again: If the underlying OS supports ad-hoc creation of cultures that needs to be surfaced too, _but  arguably not this way_.

If you don't agree that only retrieving _predefined_ cultures should be `CultureInfo.GetCultureInfo()`' s default behavior - or if changing this now is not an option for the sake of backward compatibility, do you see that the behavior described would be a _useful addition_, notably to guard against _typos_?

E.g., to be alerted if you meant to target predefined culture `ar-EG`, but accidentally specified `ar-EF`, which is not predefined.

**Comment by mklement0** [comment]
> You still have a way to filter the fake cultures by getting the EnglishName which will start with text Unknown Locale

That doesn't work on macOS and Linux:

```powershell
PSonUnix> ([cultureinfo] "ff-dd").EnglishName
Fulah (Germany)
```

A robust workaround would have to be:

```powershell
$cultureName = 'ff-DD'
$isPredefined = [bool] [Array]::Find([cultureinfo]::GetCultures('AllCultures'), [Predicate[cultureinfo]] { param($c) $c.Name -eq $cultureName })
```

That is, you need an explicit lookup of the culture name of interest in the list of predefined cultures.

---

That said, the point is not that you can _work around_ the issue, the point is that this functionality should be _directly supported_  and - arguably - be the default behavior.

---

> because people usually don't type the culture manually (except in code which they need to test anyway).

To give one example: In PowerShell I have a function named `Use-Culture` (inspired by a @rkeithhill [blog post](https://rkeithhill.wordpress.com/2009/10/21/windows-powershell-2-0-string-localization/)) which I use for ad-hoc tests of culture-sensitive command behavior.
When I pass a culture name to it, I want to make sure that it matches a _predefined_ culture.

> I think this need to be discussed with the Windows team who decided to have this behavior. as I mentioned, the framework has to follow the OS or otherwise,

I don't think there is a need to discuss this with the Windows team (or maintainers of macOS or Linux, for that matter):

On none of the supported platforms does .NET Core claim or aspire to be a _direct_ representation of the underlying platform functionality - which would be impossible, given the platform differences, but not even on _Windows_ does .NET model the underlying Windows API _directly_.

Therefore, all that is needed is:

* _a_ way to access all capabilities of the underlying platform

* and for that way to be appropriate to .NET Core and internally consistent.

**Comment by tarekgh** [comment]
I see your point but as I mentioned before, if the OS can create any culture then .NET core will. this is what we have decided to stick with. The OS's decided this behavior for some good reason. 

We may in the future try to give an API that can do the filtering you need but for current supported APIs we cannot change this behavior now.

**Comment by mklement0** [comment]
@tarekgh: Please see #32201
