### ISSUE TITLE
CoreFX build stores data within the Users folder

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#6378]
Trying to build CoreFX on a VM with a 25GB System Disk (C:) and 250GB source disk (S:) fails by getting at 0bytes free on the C: drive.
I've tracked this down to a 1GB folder within the Users\username\.nuget folder.

I can't/don't know how to change the System Disk size (it's an internal Windows build VM). 

Is there any way to keep the build contained to the folder where I've cloned dotnet/corefx outside of moving the Users folder to the S: drive?

**Comment by CIPop** [comment]
Just figured out how to expand the disk from HyperV. Still, I think there's a problem that the build system is changing other folders on the box.

**Comment by mellinoe** [comment]
I guess this is an issue with hhow NuGet restore is being done? It might be something we can configure, or it might just be something that NuGet needs to add. The folder that is filling your disk up seems to be the user-wide package cache.

**Comment by akoeplinger** [comment]
You can set the NUGET_PACKAGES env variable to configure the cache location (https://docs.nuget.org/release-notes/nuget-3.2#new-features). The dotnet CLI supports it too.

**Comment by CIPop** [comment]
Thanks @akoeplinger ! I'll give that a try. 

@mellinoe If this works, maybe we can integrate the `NUGET_PACKAGES` env variable in `build.cmd`?

**Comment by ericstj** [comment]
We actually directly use the --packages parameter.  If we're still writing to userprofile that means someone is missing a -packages folder somewhere.  @weshaggard @joperezr I'm guessing this is in the tool staging.

**Comment by weshaggard** [comment]
The tool-runtime does end up getting published to the userprofile. For other purposes we are considering switching everything to use the user cache (see https://github.com/dotnet/corefx/issues/5444) so I think the env variable is a good way to go if you have issues with space in that path. 

@CIPop I don't think we want to set this in build.cmd we want it to be user specific. If a user wants to change it to something else they can do so.

**Comment by CIPop** [comment]
Thanks @weshaggard. Since this is known and expected and it seems to have a simple workaround configuration, I'm closing the issue.
