### ISSUE TITLE
Implement Quicksort as Unsafe Code for better Performance

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/corefx#638]
There are 2 impl. of Quicksort here in Code:

https://github.com/dotnet/corefx/search?utf8=✓&q=quicksort

why are they not programmed using pointers like here: 
http://stackoverflow.com/a/3720041/579623

and maybe we also don't need two implementations

**Comment by AdamSpeight2008** [comment]
It's not swapping the actual elements but the indices of the elements. The result of the QuickSort is where the indices of the elements, will be in the sorted verison

**Comment by stephentoub** [comment]
@jogibear9988, was this just a question or is there an issue here you're concerned about?  If so, can you be more specific?  The two implementations in your search results are operating over different inputs.  Regarding pointers, what would the advantage of using such unsafe code be?  Thanks for your interest.

**Comment by sharwell** [comment]
Neither of these sections of code use a particularly fast implementation of the quick sort algorithm, and changing the code to use `unsafe` blocks would not resolve this. Have you noticed a particular performance problem with it?

**Comment by jogibear9988** [comment]
@stephentoub: I havn't tested, but the author posts with pointers is 10% faster.

@stephentoub: Is there a better Version? maybe we then should replace the existing ones...

**Comment by stephentoub** [comment]
@yogibear9988, you're very welcome to experiment, and if you find a change that makes a measurable difference, open an issue and/or submit a PR. Other than that, this issue doesn't seem particularly actionable right now (there's no demonstrated problem or deficiency) so I'd like to close it. Ok?

**Comment by jogibear9988** [comment]
I'll close! When I've investigated further, I'll vome back...
