### ISSUE TITLE
Reduce the number of feeds we use for restoring our repo

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#6393]
Currently have 4 feeds in our feed source list:

https://github.com/dotnet/corefx/blob/master/dir.props#L101
```
    <DnuSourceList Include="https:%2F%2Fdotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    <DnuSourceList Include="https:%2F%2Fdotnet.myget.org/F/dotnet-corefxtestdata/api/v3/index.json" />
    <DnuSourceList Include="https:%2F%2Fdotnet.myget.org/F/dotnet-buildtools/api/v3/index.json" />
    <DnuSourceList Include="https:%2F%2Fwww.nuget.org/api/v2/" />
```

We should eliminate corefxtestdata and buildtools from our normal source list to reduce the amount of network traffic we are doing when restoring. 

Note we should still keep the build-tools feed in our init-tools.cmd (https://github.com/dotnet/corefx/blob/master/init-tools.cmd#L12) but it shouildn't be needed for anything outside of the tool set initialization.

**Comment by chcosta** [comment]
This has been reduced to two feeds.

     <DnuSourceList Include="https:%2F%2Fdotnet.myget.org/F/dotnet-core/api/v3/index.json" /> 
     <DnuSourceList Include="https:%2F%2Fwww.nuget.org/api/v2/" />
