### ISSUE TITLE
Consider making helper script flag syntax uniform

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#6397]
Just throwing this out there because it's a minor annoyance for me, nothing high priority or workflow-breaking.

This is referring to the difference between `clean.cmd /b` and `clean.sh -b`. I know these were done to match the usual "OS standard" flag syntax, but I think it would be simpler if these were just the same across platforms (i.e. `clean -b` everywhere). I'm often typing the wrong flag after I've been working on one system for a while and then move to another. Additionally, `dotnet` has just made all systems use the "hypen-flag" syntax instead of allowing "slash-syntax" on Windows, and it seems to work fine there.

Anyone else feel the same way? I'm happy to adjust to this if nobody else is having the same troubles :smile: .

**Comment by joshfree** [comment]
maybe just make the windows version work with both /b and -b syntax.

**Comment by jasonwilliams200OK** [comment]
:+1: 

Like many other applications, `node.js`, its package manager `npm` and all the packages follow the same Unix conversion uniformly everywhere (including Windows): double hyphen `--` for full option name and single hyphen `-` for a single letter alias: `node test --watch` == `node test -w`.

On Winodws, the built-in programs on cmd use `/` token for both option names and single letter aliases. In PowerShell, cmdlets use hypen. Although PowerShell has implemented POSIX standard v1 in 2006 and comply with many Unix conventions, it confuses single and double hyphen when it comes to options:
`rm -Force dir1` (should be double hypen `--Force`, if we go by convention) and `rm -f dir1` is an invalid option (which means in PowerShell, we can't use the most famous `rm -rf` grouping.. which is pain++ over lack of `mkdir -p`)! However, `-fo`, `-for`, `-forc` and `-force` are all valid (which is eeeee, painfully ugly).

Certainly not a deal-breaker, but these aspects do carry some weight.

**Comment by mellinoe** [comment]
These are uniform now, since we moved to the run tool.
