### ISSUE TITLE
Usage of "using static" with Interop

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#6408]
Our interop design across corefx has a top-level static class named Interop.  This class has a few helpers on it, but the bulk of its contents is in nested static classes, one per library.  Each of those then has static P/Invoke methods.  For example, from some code in System.IO.FileSystem.dll:
```C#
Interop.CheckIo(Interop.Sys.CopyFile(src.SafeFileHandle, dst.SafeFileHandle));
```
Now that we're using C# 6 in the repo, we could start utilizing "using static" to avoid some of the extra code here, e.g.
```C#
using static Interop;
...
CheckIo(Sys.CopyFile(src.SafeFileHandle, dst.SafeFileHandle)); // potentially with Interop.CheckIo, or moving all methods off of Interop
```
or even:
```C#
using static Interop;
using static Interop.Sys;
...
CheckIo(CopyFile(src.SafeFileHandle, dst.SafeFileHandle));
```

On the one hand, it's nice to avoid unnecessary code cluttering things up, unnecessary typing, etc.

On the other hand, having "Interop" in the name helps to make the code very clear, and having the library name included at the call site can also be helpful.

Thoughts on what our policy should be across the corefx repo?

Personally, I'm ok leaving things the way they are and always specifying the full name: Interop.Sys.CopyFile, Interop.mincore.CloseHandle, Interop.Ssl.GetSslConnectionInfo, etc.  I'm also ok with dropping the Interop.  I don't particularly like just having the raw static method on its own, as it makes it too easy for me to mistake it as a member of the current class.

**Comment by nguerrera** [comment]
Remind me why we went with a static class instead of a namespace. I assumed that we wanted to see `Interop` whererever there was interop.

Also, only slightly related, but we might want to reconsider having anything internal outside of the System or Microsoft namespaces. There are cases where it affects end-users: https://github.com/dotnet/corefx/issues/2278

**Comment by stephentoub** [comment]
> Remind me why we went with a static class instead of a namespace. I assumed that we wanted to see Interop whererever there was interop.

I believe it was so we could define some helpers on it, but over time we moved most (though not all) of those helpers off.  There is also the benefit of seeing "Interop" everywhere, which would be defeated by ```using static``` with it.  If we wanted to move away from it being a class, we probably could, though I'm not sure there's a lot of benefit to such a change.  Maybe the right answer is: leave things the way they are, and don't use ```using static Interop```... I'm fine with that.  I opened this primarily because I was looking at ways C# 6 might impact the code base, and this was one of the potentially more broadly impactful ones (after nameof).

> we might want to reconsider having anything internal outside of the System or Microsoft namespaces

If what we have is problematic, I have no problem putting Interop into the System namespace.

**Comment by mellinoe** [comment]
I thought the issue with internal-types was only problematic if it was in an "otherwise unused" namespace. Our `Interop` type is internal, but it's in the global namespace, so doesn't that mean we are okay? From what I understand of the issue linked above, it was problematic because the namespace itself was being preferred over the type.

**Comment by nguerrera** [comment]
I think you're right and I just hadn't remembered the details.

**Comment by nguerrera** [comment]
So back to the original question, I've personally grown to like Interop at the call site. It's shorter than our previous NativeMethods convention but retains the characteristic of drawing attention to interop boundaries, which I like.

I don't dislike using static generally, though. I've found it nice for Math and Roslyn's SyntaxFactory.

**Comment by ellismg** [comment]
> I've personally grown to like Interop at the call site. It's shorter than our previous NativeMethods convention but retains the characteristic of drawing attention to interop boundaries, which I like.

I feel the same way.

**Comment by stephentoub** [comment]
Great.  I'm going to close this out.  Obviously folks can continue to comment on it and we can choose to re-evaluate in the future, but for now, there doesn't seem to be any good reason to change what we're doing.

**Comment by ianhays** [comment]
I like leaving Interop at the call site of <i>methods</i>, but I don't love it for flags and enums that are defined in Interop files.
