### ISSUE TITLE
Some System.Xml.Linq.XDocument tests are failing

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#641]
Some of the tests used to print error messages but did not fail. I added Asserts assuming that they fail and created this issue. I did not check if this is a test bug, product bug or not a bug at all (we need to check what happens on desktop and if this is something we should fix).

**Comment by krwq** [comment]
This is investigated. Not RC blocking, all issues by design and test issues fixes are in progress.

**Comment by sepidehMS** [comment]
Fixed by https://github.com/dotnet/corefx/pull/5392
