### ISSUE TITLE
IntersectWithEnumerable function SortedSet does unnecessary rotations

### ISSUE THREAD

**Issue by SunnyWar** [dotnet/corefx#6414]
![sortedset](https://cloud.githubusercontent.com/assets/4521425/13342870/d3f94fe8-dbfa-11e5-8402-99d70c58ac06.PNG)

I believe the following change would cause the tree to perform fewer rotations and therefore should be faster. This also handles the case where the set contains all the elements and does not need to be cleared and rebuilt.

**Comment by SunnyWar** [comment]
Such a trivial change...surprised it's not even up for grabs...hint, hint.

**Comment by svick** [comment]
@SunnyWar As long as it's not changing behavior (and there are enough tests to verify that) and it is clearly better (ideally, you should have benchmark results showing that), I think a PR will be reviewed, even if the issue is not marked up for grabs.

**Comment by karelz** [comment]
Feel free to submit PR. "up for grabs" is just a hint for people what might be easy to start with, it is not restriction on what anyone can pick up.

**Comment by karelz** [comment]
@SunnyWar do you plan to take it on?

**Comment by SunnyWar** [comment]
@karelz not at this time.
