### ISSUE TITLE
In SortedSet replace log2 function with Math.Log(x, 2)

### ISSUE THREAD

**Issue by SunnyWar** [dotnet/corefx#6415]
I did a test and 1 + (int) Math.Log(x, 2) was slightly faster than the implementation of the private static int log2(int value) function.

1. Replaces all occurrences of log2 with Math.Log(x,2).
2. Remove the log2 function.

Note: it's odd that to get the same results as log2 I had to use, "1 + (int)Math.Log(value, 2)". So after this change the way log2 is used might want to be looked over.

**Comment by hughbe** [comment]
I'll take a look at this and submit a PR if there is an improvement or no change in performance

@sunnywar do you have any perf data (I know this was opened 2 months ago, sorry)

**Comment by hughbe** [comment]
Also it seems like the current implementation is quite efficient - as Math has a signature of `log(double, double)` and has more branches such as checking for `double.NaN`

**Comment by SunnyWar** [comment]
I'll see if I can dig up the numbers. 

@hughbe My assumption is the corefx functions should be preferred over "roll your own". If you can write an alternative that is significantly faster and just as safe, that indicates a performance bug. So when I see alternative implementations in corefx for functions that also lives in corefx, it makes me wonder. Either the developer didn't know about the Math library, knew about it but decided to ignore it out of hubris, or the developer determined that Math.Log didn't meet the needs of SortedSet. Only in the last case are they justified in making a custom implementation...and then they should have filed a bug against Math.Log.

**Comment by SunnyWar** [comment]
Math.Log: Elapse: 00:01:32.1837385
log2: Elapse: 00:01:58.0396165

I calculated all the integers from 0-int.MaxValue. The difference is times are so close there's no reason to keep a custom function instead of using Math.Log

**Comment by ianhays** [comment]
Closing this as the more detailed results (and looking through the code) indicate the current approach is faster. We can re-open in the future if more detailed results showing Math.Log being faster arise.
