### ISSUE TITLE
[ToFDisable] Port tests for: System.AppContext

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#6416]
As part of moving out of ToF and into the open, I've been going through the "Tree of the future" tests and calculating which of those tests provide coverage that we're missing in the open tests. The goal of this is to get the open tests universally better than the ToF tests so that we can turn the ToF tests off for ProjectK runs and save us all a lot of headache diagnosing test failures from potentially outdated tests.

For System.AppContext, we're missing 11 lines of coverage.

To fulfill the uncovered lines we would need to either create new tests for them or port 1 ToF tests to the open. Those tests are: 

- [ ] System.AppContext\4.0.0.0\BaseDirectory\AppContext.BaseDirectory\AppContextBaseDirectoryTests.DefaultMatchesGetModuleFileName.xml

Coverage reports, coverage xml files, and detailed json lists of each piece of missing coverage and the corresponding ToF test that fills it are available on request.

**Comment by tarekgh** [comment]
I looked at the coverage report and I am seeing the lines not covered are the properties which used when the ArgumentException get thrown in the code. so if we have right coverage for AppContext.SetSwitch & AppContext.TryGetSwitch with the path throw the exception, then we should get the 100% coverage in SR too. right?

**Comment by tarekgh** [comment]
should we have a test exercise the stand alone library and not the one in mscorelib.dll? I don't know how to exclude the SR code from the coverage when running against mscorlib.dll

CC @AlexGhiondea

**Comment by stephentoub** [comment]
> I don't know how to exclude the SR code from the coverage when running against mscorlib.dll

My concern isn't excluding it from coverage.  It's that we're injecting dead code ;) (That said, it's only a small amount of dead code, so it's not a huge concern.)

**Comment by tarekgh** [comment]
if want to exclude the resource generation, can use the property ExcludeResourcesImport=true
Alex may know better when building the stand alone library and when building the Façade which can use this property

**Comment by ianhays** [comment]
closed via #7310
