### ISSUE TITLE
Clean up System.Xml.Linq.XDocument tests

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#642]
- [x] Remove spam messages (there are few left)
- [x] Some of the tests might be failing but not throwing (look at the messages - https://github.com/dotnet/corefx/issues/641)
- [x] Convert tests to use Xunit (right now they are only partially)
- [ ] Replace if (expr) throw new TestException, etc with proper use of Xunit asserts

**Comment by sepidehMS** [comment]
Failing tests and spam messages resolved by https://github.com/dotnet/corefx/pull/5392

**Comment by kasper3** [comment]
> Convert tests to use Xunit (right now they are only partially)

Is this done?

**Comment by krwq** [comment]
@kasper3 I'd call it done as do not think it is worth to do any more work there but this is not 100% accurate:
- we have converted most of the projects to Xunit
- for remaining tests I have added test discoverer so that Xunit can see Xml custom framework - this has achieved the goal of being able to see better errors and making it easier to investigate failures but the custom framework is still there

last point here is to do some clean ups - I think this might not be worth it unless we add some new tests at the same time - closing this issue.
