### ISSUE TITLE
[ToFDisable] Port tests for: System.Console

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#6422]
As part of moving out of ToF and into the open, I've been going through the "Tree of the future" tests and calculating which of those tests provide coverage that we're missing in the open tests. The goal of this is to get the open tests universally better than the ToF tests so that we can turn the ToF tests off for ProjectK runs and save us all a lot of headache diagnosing test failures from potentially outdated tests.

For System.Console, we're missing 15 lines of coverage. Our total line coverage for Open vs. ToF is 98.5%. However, this includes some data points that might not be relevant to the library being tested so the real coverage is likely lower.

To fulfill the uncovered lines we would need to either create new tests for them or port 1 ToF tests to the open. Those tests are: 

- [ ] System.Console\4.0.0.0\ConsoleTests\CancelKeyPress.CanAddAndRemoveHandler.xml

Coverage reports, coverage xml files, and detailed json lists of each piece of missing coverage and the corresponding ToF test that fills it are available on request.

**Comment by stephentoub** [comment]
> To fulfill the uncovered lines we would need to either create new tests for them or port 1 ToF tests to the open. Those tests are: System.Console\4.0.0.0\ConsoleTests\CancelKeyPress.CanAddAndRemoveHandler.xml

@ianhays, that exact test is here:
https://github.com/dotnet/corefx/blob/master/src/System.Console/tests/CancelKeyPress.cs#L12-L23

Can you clarify?

**Comment by ianhays** [comment]
That... is interesting. My per-test results for that test show it having more coverage than it's open equivalent.

Though that test is slightly different in open, I would expect it would provide the same coverage. However, one difference is in the method: ```System.Void System.Console::remove_CancelKeyPress(System.ConsoleCancelEventHandler)``` where in open we're missing lines 327-330 but in that ToF test we're covering them.

I tried running other Console tests to see if there was an issue in the infrastructure providing coverage, but that was not the case.

I also tried modifying the open test to be the old style, but as expected it made no change.

I also tried re-running the test run to check the logs to see if more than just this test got run somehow, but that was not the case either.

I'm going to try to find more instances of this issue and see if any other ones come up elsewhere.

**Comment by stephentoub** [comment]
> where in open we're missing lines 327-330 but in that ToF test we're covering them.

Do the ToF tests run in an environment that's already hooked up a CancelKeyPress handler?  xunit has one (which is why you can ctrl-C to gracefully exit a test run).

**Comment by ianhays** [comment]
I have not delved into the ToF xunit runner so I'm not sure. If I can't find any other instances of this happening then I'm going to blame this one on infrastructure differences. There are a few other differences in how I run the tests e.g. ToF tests are in a batch window, open tests are in a powershell window that could contribute to this weird inconsistency.

**Comment by ianhays** [comment]
Ran the tests again with the latest sources (and Debug) and now it shows us as missing:

- [ ] System.Console\4.0.0.0\ConsoleTests\Console_OpenStandardXXX.OpenStandardXXX_NegativeTesting.xml

with 1 line of coverage: 

      "ModuleName": "System.Console",
      "ClassName": "System.ConsolePal/WindowsConsoleStream",
      "MethodSignature": "System.Int32 System.ConsolePal/WindowsConsoleStream::WriteFileNative(System.IntPtr,System.Byte[],System.Int32,System.Int32,System.Boolean)",
      "LineNumber": 1183
