### ISSUE TITLE
[ToFDisable] Port tests for: System.Globalization

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#6429]
As part of moving out of ToF and into the open, I've been going through the "Tree of the future" tests and calculating which of those tests provide coverage that we're missing in the open tests. The goal of this is to get the open tests universally better than the ToF tests so that we can turn the ToF tests off for ProjectK runs and save us all a lot of headache diagnosing test failures from potentially outdated tests.

For System.Globalization, we're missing 48 lines of coverage.

To fulfill the uncovered lines we would need to either create new tests for them or port 10 ToF tests to the open. Those tests are: 

- [ ] System.Globalization\4.0.0.0\CharNumericCategory\GetNumericValueTests\System.Globalization.Tests.GetNumericValue.InputStringBeginningOfStringWithoutValue.xml
- [ ] System.Globalization\4.0.0.0\CharNumericCategory\GetNumericValueTests\System.Globalization.Tests.GetNumericValue.InputCharWithoutValue.xml
- [ ] System.Globalization\4.0.0.0\CharNumericCategory\GetNumericValueTests\System.Globalization.Tests.GetNumericValue.NullCheck.xml
- [ ] System.Globalization\4.0.0.0\CharNumericCategory\GetNumericValueTests\System.Globalization.Tests.GetNumericValue.VerifyIndexRange.xml
- [ ] System.Globalization\4.0.0.0\CharUnicodeInfo\GetUnicodeCategoryTests\System.Globalization.Tests.GetUnicodeCategory.InputString.xml
- [ ] System.Globalization\4.0.0.0\CharUnicodeInfo\GetUnicodeCategoryTests\System.Globalization.Tests.GetUnicodeCategory.NullCheck.xml
- [ ] System.Globalization\4.0.0.0\CharUnicodeInfo\GetUnicodeCategoryTests\System.Globalization.Tests.GetUnicodeCategory.VerifyIndexRange.xml
- [ ] System.Globalization\4.0.0.0\CompareInfo\CompareInfoCompare2\System.Globalization.Tests.CompareInfoCompare2.RegressionTests.xml
- [ ] System.Globalization\4.0.10.0\CultureInfo\CultureInfoTest_FullRun.XML
- [ ] System.Globalization\4.0.10.0\CultureInfo\CultureInfoTest\System.Globalization.Tests.CultureInfoTest.TestSettingThreadCultures.xml

Coverage reports, coverage xml files, and detailed json lists of each piece of missing coverage and the corresponding ToF test that fills it are available on request.

**Comment by stephentoub** [comment]
@ianhays, I reverted the fix for this, as it was causing issues elsewhere in the globalization tests.

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/corefx/pull/7606
