### ISSUE TITLE
[ToFDisable] Port tests for: System.IO.FileSystem.DriveInfo

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#6434]
As part of moving out of ToF and into the open, I've been going through the "Tree of the future" tests and calculating which of those tests provide coverage that we're missing in the open tests. The goal of this is to get the open tests universally better than the ToF tests so that we can turn the ToF tests off for ProjectK runs and save us all a lot of headache diagnosing test failures from potentially outdated tests.

For System.IO.FileSystem.DriveInfo, we're missing 128 lines of coverage.

To fulfill the uncovered lines we would need to either create new tests for them or port 4 ToF tests to the open. Those tests are: 

- [ ] System.IO.FileSystem.DriveInfo\4.0.0.0\System.IO.FileSystem.DriveInfoTests\System.IO.FileSystem.DriveInfoTests.Get_IsReady.Test01.xml
- [ ] System.IO.FileSystem.DriveInfo\4.0.0.0\System.IO.FileSystem.DriveInfoTests\System.IO.FileSystem.DriveInfoTests.ctor_str.Test01.xml
- [ ] System.IO.FileSystem.DriveInfo\4.0.0.0\System.IO.FileSystem.DriveInfoTests_FullRun.XML
- [ ] System.IO.FileSystem.DriveInfo\4.0.0.0\System.IO.FileSystem.DriveInfoTests\System.IO.FileSystem.DriveInfoTests.Get_VolumeLabel.Test01.xml

Coverage reports, coverage xml files, and detailed json lists of each piece of missing coverage and the corresponding ToF test that fills it are available on request.

**Comment by stephentoub** [comment]
@ianhays, did you run both sets of tests on the same machine with the same drives mounted?

**Comment by ianhays** [comment]
Yes indeed.

**Comment by ianhays** [comment]
Missing lines are mostly testing interop errors and are in:
```
    mscorlib
    "System.IO.Win32Marshal": {
    "System.IO.Error": {
    "Interop/mincore": {
```
The only line in System.IO.FileSystem.DriveInfo directly is:
```
    "System.IO.DriveInfo": {
      "System.Void System.IO.DriveInfo::set_VolumeLabel(System.String)": {
        "234": "System.IO.FileSystem.DriveInfo\\4.0.0.0\\System.IO.FileSystem.DriveInfoTests\\System.IO.FileSystem.DriveInfoTests.Get_VolumeLabel.Test01.xml"
      }
    },
```
Which is only touched when there is a ERROR_ACCESS_DENIED so it can throw an unauthorizedaccessexception.

**Comment by ianhays** [comment]
No real missing coverage. We have tests that test for an UnauthorizedAccessException but they require drives that are ready-able. Closing.
