### ISSUE TITLE
[ToFDisable] Port tests for: System.Runtime.InteropServices.RuntimeInformation

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#6446]
As part of moving out of ToF and into the open, I've been going through the "Tree of the future" tests and calculating which of those tests provide coverage that we're missing in the open tests. The goal of this is to get the open tests universally better than the ToF tests so that we can turn the ToF tests off for ProjectK runs and save us all a lot of headache diagnosing test failures from potentially outdated tests.

For System.Runtime.InteropServices.RuntimeInformation, we're missing 429 lines of coverage. Our total line coverage for Open vs. ToF is 99.4%. However, this includes some data points that might not be relevant to the library being tested so the real coverage is likely lower.

To fulfill the uncovered lines we would need to either create new tests for them or port 3 ToF tests to the open. Those tests are: 

- [ ] System.Runtime.InteropServices.RuntimeInformation\4.0.0.0\System.Runtime.InteropServices.RuntimeInformation.Common.Tests\System.Runtime.InteropServices.RuntimeInformationTests.CheckArchitectureTests.VerifyArchitecture.xml
- [ ] System.Runtime.InteropServices.RuntimeInformation\4.0.0.0\System.Runtime.InteropServices.RuntimeInformation.Common.Tests_FullRun.XML
- [ ] System.Runtime.InteropServices.RuntimeInformation\4.0.0.0\System.Runtime.InteropServices.RuntimeInformation.Common.Tests\System.Runtime.InteropServices.RuntimeInformationTests.CheckPlatformTests.CheckOSPlatform.xml

Coverage reports, coverage xml files, and detailed json lists of each piece of missing coverage and the corresponding ToF test that fills it are available on request.

**Comment by stephentoub** [comment]
> For System.Runtime.InteropServices.RuntimeInformation, we're missing 429 lines of coverage

Some of the code in this library only executes when on a particular platform, when using a particular chip set, etc.  That's not going to be addressed by adding more tests.

That said, I don't understand this number.  According to OpenCover / ReportGenerator when I run ```msbuild /t:rebuildandtest /p:Coverage=true```, there are only 264 total lines of which 14 are uncovered:
![image](https://cloud.githubusercontent.com/assets/2642209/13428684/0fec6ee4-df8a-11e5-80ac-d47448644062.png)
I don't know where the 429 comes from.

> To fulfill the uncovered lines we would need to either create new tests for them or port

All of those tests exist, e.g.
- https://github.com/dotnet/corefx/blob/331690a2293d497e3727f2cb4e99b55e5c2e3da8/src/System.Runtime.InteropServices.RuntimeInformation/tests/CheckArchitectureTests.cs#L13
- https://github.com/dotnet/corefx/blob/331690a2293d497e3727f2cb4e99b55e5c2e3da8/src/System.Runtime.InteropServices.RuntimeInformation/tests/CheckPlatformTests.cs#L56

In looking over the coverage report, I don't see any uncovered lines that could be covered by adding new tests.  There are a couple of branches that could be covered by invoking properties again, but that's it I think.

**Comment by ianhays** [comment]
I re-ran everything and get 0 missing lines. It's possible my results for this library were older from before I made some important fixes to how I was combining results. I'm going through all of the issues and updating them now with the new, outerloop-inclusive results.

Closing this as no missing lines to port.
