### ISSUE TITLE
[ToFDisable] Port tests for: System.Threading.Tasks.Parallel

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#6461]
As part of moving out of ToF and into the open, I've been going through the "Tree of the future" tests and calculating which of those tests provide coverage that we're missing in the open tests. The goal of this is to get the open tests universally better than the ToF tests so that we can turn the ToF tests off for ProjectK runs and save us all a lot of headache diagnosing test failures from potentially outdated tests.

For System.Threading.Tasks.Parallel, we're missing 44 lines of coverage.

To fulfill the uncovered lines we would need to either create new tests for them or port 17 ToF tests to the open. Those tests are: 

- [ ] System.Threading.Tasks.Parallel\4.0.0.0\ParallelForTests_FullRun.XML
- [ ] System.Threading.Tasks.Parallel\4.0.0.0\Parallel\PFB.ParallelForBoundary0\PFB.ParallelForBoundary0.xml
- [ ] System.Threading.Tasks.Parallel\4.0.0.0\Parallel\ParallelStateTest_FullRun.XML
- [ ] System.Threading.Tasks.Parallel\4.0.0.0\Parallel\ParallelStateTest\System.Threading.Tasks.Test.ParallelState.ParallelState0.xml
- [ ] System.Threading.Tasks.Parallel\4.0.0.0\Parallel\ParallelStateTest\System.Threading.Tasks.Test.ParallelState.ParallelState28.xml
- [ ] System.Threading.Tasks.Parallel\4.0.0.0\PLRT.SimultaneousStopBreakTests\PLRT.SimultaneousStopBreakTests.xml
- [ ] System.Threading.Tasks.Parallel\4.0.0.0\Parallel\RPCT.RespectParentCancellation1\RPCT.RespectParentCancellation1.xml
- [ ] System.Threading.Tasks.Parallel\4.0.0.0\Parallel\RespectParentCancellationTest_FullRun.XML
- [ ] System.Threading.Tasks.Parallel\4.0.0.0\Parallel\PFP.ParallelForeachPartitioner1\PFP.ParallelForeachPartitioner1.xml
- [ ] System.Threading.Tasks.Parallel\4.0.0.0\Parallel\PFP.ParallelForeachPartitioner0\PFP.ParallelForeachPartitioner0.xml
- [ ] System.Threading.Tasks.Parallel\4.0.0.0\PFT.TestParallelForPaths\PFT.TestParallelForPaths.xml
- [ ] System.Threading.Tasks.Parallel\4.0.0.0\Parallel\ParallelStateTest\System.Threading.Tasks.Test.ParallelState.ParallelState10.xml
- [ ] System.Threading.Tasks.Parallel\4.0.0.0\Parallel\ParallelStateTest\System.Threading.Tasks.Test.ParallelState.ParallelState37.xml
- [ ] System.Threading.Tasks.Parallel\4.0.0.0\Parallel\PST.ParallelState6\PST.ParallelState6.xml
- [ ] System.Threading.Tasks.Parallel\4.0.0.0\BreakTests_FullRun.XML
- [ ] System.Threading.Tasks.Parallel\4.0.0.0\Parallel\ParallelStateTest\System.Threading.Tasks.Test.ParallelState.ParallelState53.xml
- [ ] System.Threading.Tasks.Parallel\4.0.0.0\Parallel\ParallelStateTest\System.Threading.Tasks.Test.ParallelState.ParallelState1.xml

Coverage reports, coverage xml files, and detailed json lists of each piece of missing coverage and the corresponding ToF test that fills it are available on request.

**Comment by stephentoub** [comment]
@ianhays, thanks for doing this work. Can you help me to understand a few things?
- What tool are you using to measure coverage?  Something other than OpenCover/ReportGenerator? You wrote that we're missing 339 lines of coverage, but when I just ran ```msbuild /t:rebuildandtest /p:Coverage=true``` and looked at the resulting report, it states only 130 of the coverable lines are uncovered, so I'm not sure how to rationalize that difference.  (There could be some small variability due to the concurrent nature of this particular library, but I wouldn't expect such a large swing.)
- What does "Our total line coverage for Open vs. ToF is 96.1%" mean?  Is that saying 96.1% of what's covered by ToF is covered by Open?  Or something else?  What about things covered by Open not covered by ToF?
- As I mentioned offline, I assume this is only reflecting the inner loop open tests as compared to all of the ToF tests?  I see ~80 [OuterLoop] facts and theories for this library, for example.

**Comment by ianhays** [comment]
Original comment updated with fixed coverage that includes outerloop coverage for the open tests.

Let me give you a detailed overview of how I'm getting the coverage. I'll respond to that email thread as well.

The results provided from the early-stages ToF vs. Open coverage contained reports that compared the results of running all the ToF tests vs all the Open tests. The issue with this was that it was somewhat difficult to track down which tests we actually wanted to port to cover those gaps. I took the infrastructure and scripts being used and expanded them to be a pipeline of operations to produce per-test coverage results. That way we can get a nice list of each missing test and what porting that test will gain us in coverage.

The structure of my program is as follows:
- FindTests: Get a list of every ToF test. To do this I iterated the test sources and found every instance of [Fact] or [TestMethod] and added an entry to a JSON list with its location and complete name (i.e. namespace.class.method).
- InvokeTests: For every test in the list above, execute a ToF test run of that exact test wrapped in an instance of OpenCover. 
  - I also run every test project wrapped in opencover as a fallback in case a project has a testing syntax that I didn't parse for. I favor test-specific coverage where it exists.
- MergeCoverageFiles: So now we have an XML test results file for EVERY ToF test. That's a lot of reports to compare with Open and sift through manually. So the next step is to combine each of these ToF test reports into one combined-ToF report, and for each line that is covered we have a "test" property that specifies the test that contributed that piece of coverage.
- GetOpenMscorlibCoverage: Build and test build.cmd with coverage=true and outerloop=true to get a full coverage report for Open that includes mscorlib coverage
- GetLibraryDiff: Take the difference of the combined ToF report and the open coverage report for each library to produce a library.diff.xml file. This is the most complicated part as it required a number of quirky fixes to the coverage. I do a number of different things to filter the results of unnecessary coverage such that the resulting diff.xml file only contains things that we're missing.
  - The logic here can be a bit confusing because of how we filter. For each line:
    - Mark it as uncovered when tof covers it but open does not
    - Mark it as covered when ToF doesn't cover it
    - Mark it as covered when Open covers it

**Comment by ianhays** [comment]
Original comment updated with fixed coverage that includes outerloop coverage for the open tests.

Let me give you a detailed overview of how I'm getting the coverage. I'll respond to that email thread as well.

The results provided from the early-stages ToF vs. Open coverage contained reports that compared the results of running all the ToF tests vs all the Open tests. The issue with this was that it was somewhat difficult to track down which tests we actually wanted to port to cover those gaps. I took the infrastructure and scripts being used and expanded them to be a pipeline of operations to produce per-test coverage results. That way we can get a nice list of each missing test and what porting that test will gain us in coverage.

The structure of my program is as follows:
- FindTests: Get a list of every ToF test. To do this I iterated the test sources and found every instance of [Fact] or [TestMethod] and added an entry to a JSON list with its location and complete name (i.e. namespace.class.method).
- InvokeTests: For every test in the list above, execute a ToF test run of that exact test wrapped in an instance of OpenCover. 
  - I also run every test project wrapped in opencover as a fallback in case a project has a testing syntax that I didn't parse for. I favor test-specific coverage where it exists.
- MergeCoverageFiles: So now we have an XML test results file for EVERY ToF test. That's a lot of reports to compare with Open and sift through manually. So the next step is to combine each of these ToF test reports into one combined-ToF report, and for each line that is covered we have a "test" property that specifies the test that contributed that piece of coverage.
- GetOpenMscorlibCoverage: Build and test build.cmd with coverage=true and outerloop=true to get a full coverage report for Open that includes mscorlib coverage
- GetLibraryDiff: Take the difference of the combined ToF report and the open coverage report for each library to produce a library.diff.xml file. This is the most complicated part as it required a number of quirky fixes to the coverage. I do a number of different things to filter the results of unnecessary coverage such that the resulting diff.xml file only contains things that we're missing.
  - For each line and branch:
    - Mark it as uncovered when tof covers it but open does not
    - Mark it as covered when ToF doesn't cover it
    - Mark it as covered when Open covers it
  - If the coverage is at 100% for a method, class, or module, remove it from the report.
  - If the coverage is for a library that isn't the one being tested, remove it from the report.
- GenerateReports: Call ReportGenerator on the diffed XML file to produce HTML files of the missing coverage as well as a CSV file with stats (e.g. total uncovered lines, total coverage %, etc).
- GenerateMissingTestList: Searches through each diff file to produce two pretty json lists that list every missing test and every line of coverage that test provides. It also produces a txt file containing the body of the github issue for the coverage and the percentage of coverage. This percentage covered in the summary is not our total coverage but rather (the number of lines covered by ToF but not by open) divided by (the total number of lines covered by ToF).

I cache everything that gets pushed through the pipeline such that subsequent re-runs of any portion take significantly less time that re-running the entire program. The only part that takes a long time is collection the ToF test results, but once those are done everything else can be re-run in an hour or two.

So the end result is that we now have a list of every line of coverage that is provided by the ToF tests but not the Open tests. We also have a JSON list that matches each line to a test that will cover that line if we port it.

The total number of lines covered by ToF but not by open is 13730. The total number of tests it would take to port to gain that coverage in open is 441. However, there are a few edge-cases that are making this coverage higher than it should be because of some inconsistencies in the naming of projects.
  - Some libraries like System.XML.ReaderWriter name their test projects in a way that doesn't directly align with the corresponding source, so I need to special-case for that and combine the Open results before comparing them against the ToF results.
  - When I filter out based on library being tested I am overly cautious not to exclude anything that I shouldn't be because of the possibility of naming differences between the tests in ToF and Open. This has the side-effect that in some cases we're comparing coverage for things we don't care about (e.g. including coverage for System.Data when we're testing System.Data.Sqlclient).

I'd estimate at least half of the missing coverage can be attributed to the above two issues. 7486 of the missing lines are from System.Data.SQLClient and there's a bunch of potentially unnecessary results in there. There are 2000 lines for System.Private.URI missing from the open results for the System.Runtime.Tests, but it's possible they were just moved elsewhere. I wouldn't feel comfortable removing these programatically because they could be hiding potential issues in edge-cases so we're stuck with looking through them manually to determine if they're actionable. This is a very small subset of the total tests, though. 

We're missing some edge-cases in Open that were easier to test in ToF (e.g. win32 exceptions) where tests with race-conditions could slumber more soundly, but as a whole we're almost there. There are also some classes that just flat-out don't have enough tests e.g. throwing myself under the bus here and saying System.IO.MemoryStream where we don't test edge cases at all in the open. There are 12 ToF tests for MemoryStream that would have to be ported to get our coverage in open where it needs to be, but nearly every other class in System.IO is 100% what ToF is.

All-in-all though we're looking quite good in our Open coverage.

**Comment by AlfredoMS** [comment]
I am surprised there are differences, since I initially ported 100% of the tests from ToF to here.
Maybe some some cases lost coverage with @Clockwork-Muse upgrade of them as proper xUnit tests.

@ianhays what is the current plan to recover coverage? we should look into integrating those old ToF into the current tests instead of just blindly porting the code.

**Comment by Clockwork-Muse** [comment]
@AlfredoMS - I haven't really touched Tasks.Parallel (changing namespace only).  I did a bunch of stuff for Linq.Parallel (which _probably_ increased coverage, but I haven't checked).  I've been working some on Tasks, but haven't pushed anything.

**Comment by AlfredoMS** [comment]
@Clockwork-Muse oops, sorry I misread the title and was indeed talking about PLINQ. nevermind then

**Comment by ianhays** [comment]
It's possible some of the tests listed aren't really tests that provide new coverage, but maybe their execution differed in ToF or maybe concurrent operations happened in a different order so different lines were touched. There isn't a way to differentiate between "lines this test covers" and "lines that were touched while executing this test". I expect that to be the case for a good number of the above tests. If you're confident that the current coverage is adequate then feel free to close this and I'll disable the ToF tests.

The lines reported as uncovered are:
```
  "System.Threading.Tasks.Parallel": {
    "System.Threading.Tasks.Parallel": {
      "System.Threading.Tasks.ParallelLoopResult System.Threading.Tasks.Parallel::ForEach(System.Collections.Concurrent.Partitioner`1<TSource>,System.Threading.Tasks.ParallelOptions,System.Action`2<TSource,System.Threading.Tasks.ParallelLoopState>)": {
        "2761": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\PFP.ParallelForeachPartitioner1\\PFP.ParallelForeachPartitioner1.xml",
        "2762": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\PFP.ParallelForeachPartitioner1\\PFP.ParallelForeachPartitioner1.xml"
      },
      "System.Threading.Tasks.ParallelLoopResult System.Threading.Tasks.Parallel::ForEach(System.Collections.Concurrent.Partitioner`1<TSource>,System.Threading.Tasks.ParallelOptions,System.Func`1<TLocal>,System.Func`4<TSource,System.Threading.Tasks.ParallelLoopState,TLocal,TLocal>,System.Action`1<TLocal>)": {
        "2947": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\PFP.ParallelForeachPartitioner0\\PFP.ParallelForeachPartitioner0.xml",
        "2948": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\PFP.ParallelForeachPartitioner0\\PFP.ParallelForeachPartitioner0.xml"
      }
    },
    "System.Threading.Tasks.Parallel/<>c__DisplayClass44_0`2": {
      "System.Void System.Threading.Tasks.Parallel/<>c__DisplayClass44_0`2::<PartitionerForEachWorker>b__1(System.Collections.IEnumerator&,System.Int32,System.Boolean&)": {
        "3272": "System.Threading.Tasks.Parallel\\4.0.0.0\\PFT.TestParallelForPaths\\PFT.TestParallelForPaths.xml",
        "3273": "System.Threading.Tasks.Parallel\\4.0.0.0\\PFT.TestParallelForPaths\\PFT.TestParallelForPaths.xml",
        "3274": "System.Threading.Tasks.Parallel\\4.0.0.0\\PFT.TestParallelForPaths\\PFT.TestParallelForPaths.xml"
      }
    },
    "System.Threading.Tasks.ParallelLoopState": {
      "System.Boolean System.Threading.Tasks.ParallelLoopState::get_ShouldExitCurrentIteration()": {
        "65": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState10.xml",
        "66": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState10.xml",
        "67": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState10.xml"
      },
      "System.Boolean System.Threading.Tasks.ParallelLoopState::get_IsStopped()": {
        "76": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest_FullRun.XML",
        "77": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest_FullRun.XML",
        "78": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest_FullRun.XML"
      },
      "System.Boolean System.Threading.Tasks.ParallelLoopState::get_IsExceptional()": {
        "88": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState10.xml",
        "89": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState10.xml",
        "90": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState10.xml"
      },
      "System.Nullable`1<System.Int64> System.Threading.Tasks.ParallelLoopState::get_LowestBreakIteration()": {
        "115": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState0.xml",
        "116": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState0.xml",
        "117": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState0.xml"
      },
      "System.Void System.Threading.Tasks.ParallelLoopState::Break(System.Int32,System.Threading.Tasks.ParallelLoopStateFlags32)": {
        "217": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState37.xml",
        "218": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState37.xml",
        "219": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState37.xml",
        "220": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState37.xml",
        "221": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState37.xml"
      },
      "System.Void System.Threading.Tasks.ParallelLoopState::Break(System.Int64,System.Threading.Tasks.ParallelLoopStateFlags64)": {
        "258": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\PST.ParallelState6\\PST.ParallelState6.xml",
        "259": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\PST.ParallelState6\\PST.ParallelState6.xml",
        "260": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\PST.ParallelState6\\PST.ParallelState6.xml",
        "261": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\PST.ParallelState6\\PST.ParallelState6.xml",
        "262": "System.Threading.Tasks.Parallel\\4.0.0.0\\BreakTests_FullRun.XML"
      }
    },
    "System.Threading.Tasks.ParallelLoopState32": {
      "System.Boolean System.Threading.Tasks.ParallelLoopState32::get_InternalShouldExitCurrentIteration()": {
        "300": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState53.xml"
      },
      "System.Nullable`1<System.Int64> System.Threading.Tasks.ParallelLoopState32::get_InternalLowestBreakIteration()": {
        "309": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState0.xml"
      }
    },
    "System.Threading.Tasks.ParallelLoopState64": {
      "System.Boolean System.Threading.Tasks.ParallelLoopState64::get_InternalShouldExitCurrentIteration()": {
        "365": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState10.xml"
      },
      "System.Nullable`1<System.Int64> System.Threading.Tasks.ParallelLoopState64::get_InternalLowestBreakIteration()": {
        "377": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState1.xml"
      }
    },
    "System.Threading.Tasks.ParallelLoopStateFlags32": {
      "System.Nullable`1<System.Int64> System.Threading.Tasks.ParallelLoopStateFlags32::get_NullableLowestBreakIteration()": {
        "481": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState0.xml",
        "482": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState0.xml",
        "484": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState0.xml",
        "486": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState0.xml",
        "487": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState0.xml",
        "490": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState0.xml"
      }
    },
    "System.Threading.Tasks.ParallelLoopStateFlags64": {
      "System.Nullable`1<System.Int64> System.Threading.Tasks.ParallelLoopStateFlags64::get_NullableLowestBreakIteration()": {
        "551": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState1.xml",
        "552": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState1.xml",
        "554": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState1.xml",
        "555": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState1.xml",
        "558": "System.Threading.Tasks.Parallel\\4.0.0.0\\Parallel\\ParallelStateTest\\System.Threading.Tasks.Test.ParallelState.ParallelState1.xml"
      }
    }
  }
```

**Comment by ianhays** [comment]
All tests are already present in CoreFX. There were just a bunch of false positives. Closing.
