### ISSUE TITLE
[System.Net .Security Tests for NTLM] Allow Unix Implementation to take "Domain\User" format as a user.

### ISSUE THREAD

**Issue by shrutigarg** [dotnet/corefx#6465]
Currently if we pass the credential having user in format Domain/User.. It fails ,, We should fix this to accept this.

**Comment by davidsh** [comment]
FWIW, the format for <domain> plus <user> is usually `Domain\User` i.e. use the backslash and not the forward slash character.

**Comment by shrutigarg** [comment]
Thanks.. it was a typo.

**Comment by shrutigarg** [comment]
it includes fixing user@domain type too

**Comment by shrutigarg** [comment]
This is taken care in the current implementation. Will  send the PR for this soon

**Comment by vijaykota** [comment]
This was just a tracking issue for #5770 and not a bug in checked in code.
