### ISSUE TITLE
Remove Issue and PR templates

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#6471]
I know we just added them, but I'm already finding them to be problematic.  There's a ton of text in them, so much that I end up just ignoring them, deleting everything, and writing my own message.  Plus, for PRs with a single commit, it appears the template text takes precedence over the normal behavior on GitHub of using the commit's description, which means extra work to get the contents of the commit message into the PR description.

My vote is to delete these, at least for now.

**Comment by davidsh** [comment]
+1

**Comment by terrajobst** [comment]
Sounds good to me :-) /cc @weshaggard 

It was good experiment though.

**Comment by weshaggard** [comment]
LOL... I'm fine with that. It is probably still worth having the template as examples in some md file so we can point people at for good examples of how to structure the different type of issues.

**Comment by stephentoub** [comment]
> It was good experiment though.

It was :)  We might still consider doing something for Issues, but with much less text, just a couple of bullet points or something.  For now, though, removal seems best.

> It is probably still worth having the template as examples in some md file so we can point people at for good examples of how to structure the different type of issues

That's a good idea, maybe adding something to the contribution guidelines that highlights what good issues / PRs look like.

**Comment by weitzhandler** [comment]
> It is probably still worth having the template as examples in some md file so we can point people at for good examples of how to structure the different type of issues

It would be best to have a page containing raw markdown templates for various issue types, such as bug reports and API change proposals.

**Comment by danmosemsft** [comment]
@karelz
