### ISSUE TITLE
API for Code based configuration for DBProviderFactories

### ISSUE THREAD

**Issue by kkurni** [dotnet/corefx#6476]
# Problem

DbProviderFactories in .NET Framework provides an API to manage DbProviderFactory which configured in machine.config and load that assembly from GAC via reflection

In Corefx, there is no more GAC and machine.config.

Community are asking to have a standard way to manage DbProviderFactory to write provider agnostic code in libraries.
https://github.com/dotnet/corefx/issues/4571
https://github.com/dotnet/corefx/issues/5782

https://msdn.microsoft.com/en-us/library/ms971499.aspx
# Proposal

We will bring back DbProviderFactories in CoreFx.
But instead of register/read the configuration from machine.config, we will provide a code based configuration.

This will allow application writer to hook this with any configuration mechanism.
## Contract Changes

We will bring back DbProviderFactories.GetFactory functions in V1 contract which will support .Net 4.6.2.
And add "RegisterFactory" functions in V2 contract to support .Net vNext. (version after 4.6.2)

For portability, we will bring "RegisterFactory" into .Net vNext and should work side by side with file config behavior. e.g code based config will override file based config).

Portable library (such as ORM), can start using GetFactory and target it for .Net 4.6.2.
If this library used in .NET 4.6.2 , GetFactory will return factory which defined in machine/app configs. 
Corefx application which used this portable library can register their factory using "RegisterFactory".

Once we release "RegisterFactory" into .Net vNext, The behavior will be work seamless in both frameworks.

``` C#
namespace System.Data.Common
{
    public static class DbProviderFactories
    {
        // V1 -- Supported by .NET Framework 4.6.2 (the upcoming version)
        public static DbProviderFactory GetFactory(string providerInvariantName);
        public static DbProviderFactory GetFactory(DbConnection connection);

        // V2 -- Supported by .NET Core 1.0 and by .NET Framework vNext (version after 4.6.2)
        public static void RegisterFactory(string providerInvariantName, DbProviderFactory factory);
        public static IEnumerable<string> GetFactoryProviderNames();
    }
}
```
## DbProviderFactories

CoreFx Implementation

``` C#
public abstract class DbProviderFactories
    {

        internal static readonly Dictionary<string, Func<DbProviderFactory>> _configs = new Dictionary<string, Func<DbProviderFactory>>();

        public static DbProviderFactory GetFactory(string providerInvariantName)
        {
            ADP.CheckArgumentLength(providerInvariantName, nameof(providerInvariantName));

            if (_configs.ContainsKey(providerInvariantName))
            {
                return _configs[providerInvariantName]();
            }

            throw ADP.ConfigProviderNotFound();
        }

        public static DbProviderFactory GetFactory(DbConnection connection)
        {
            ADP.CheckArgumentNull(connection, nameof(connection));
            return connection.ProviderFactory;
        }

        public static void RegisterFactory(string providerInvariantName, DbProviderFactory factory) {
            ADP.CheckArgumentNull(providerInvariantName, nameof(providerInvariantName));
            ADP.CheckArgumentNull(constructorDelegate, nameof(constructorDelegate));

            _configs[providerInvariantName]  = factory;
        }

        public static IEnumerable<string> GetFactoryProviderNames() {
             return _configs.Keys.toArray();
        }
    }
```
## Usage

For CoreFX application, You need to register your provider factory during startup of your application.

``` C#
public static void Startup()
        {
            //SqlClientFactory is a singleton factory
            DbProviderFactories.Add("System.Data.SqlClient", SqlClientFactory.Instance);

            //You can use other factory which not singleton.
            DbProviderFactories.Add("System.Data.OtherProvider", new OtherProviderFactory());
        }
```
# Progress

I have created initial commit on my branch to inspect what are the changes needed.
https://github.com/kkurni/corefx/commit/68380b3451d3ba0ce9646119101e9b4309f09d68

**Comment by kkurni** [comment]
CC @YoungGah @saurabh500 @corivera @nadiatk

**Comment by davidfowl** [comment]
You should allow overriding the factory. Blocking that seems unnecessarily restrictive.

**Comment by kkurni** [comment]
@davidfowl I assume that your suggestion is about overriding the value of factory registration.

```
  if (Dictionary.ContainsKey(providerInvariantName))
            {
                throw ADP.ConfigProviderKeyAlreadyExists();
            }
```

The reason why we don't allow for duplicate is to make the behavior less unpredictable.
e.g If we allow this, any libraries that you reference can just override your provide without any advanced agreement or notification. This will be hard to debug and find out which libraries override the value.

But the application can decide in advanced which provider they want to use and create their own policy to select which provider they want to use if there is a conflict. e.g File based config override mechanism based on folder hierarchy.

**Comment by davidfowl** [comment]
> The reason why we don't allow for duplicate is to make the behavior less unpredictable.
e.g If we allow this, any libraries that you reference can just override your provide without any advanced agreement or notification. This will be hard to debug and find out which libraries override the value.

Making it impossible though seems a bit restrictive. There's a thin line between trying to protect users from the scenarios "you can think will be confusing" and scenarios "you didn't anticipate would be useful". Blocking it because you can only think of a case that would confusing customers is bad.

Another think I'd like from this API is the ability to new up a `DbProviderFactoriesConfiguration`. The static should be the default but if you want to create a totally separate hive then you should be able to create one, and pass it into `DbProviderFactory.GetFactory`. It'll make it easier to unit test and isolate (multi-tenant scenarios).

**Comment by gafemoyano** [comment]
Does this mean that there ris no way to register a custom provider, say "Oracle.ManagedDataAccess.Client" on .NET 4.6.2?

**Comment by grahamehorner** [comment]
@gafemoyano Oracle.ManagedDataAccess.Client is not a .NET core compatible provider it is a full framework provider

**Comment by karelz** [comment]
@YoungGah plans to port over the old one, not create a new one. Sorry for the confusion and thanks for your effort and help here!

**Comment by KevalPatel** [comment]
What is ADP here ?

**Comment by karelz** [comment]
@KevalPatel please don't comment on old-closed issues. No one is likely monitoring them.

I don't understand your question in this context, so can't answer.
