### ISSUE TITLE
Add parameterless overloads of TrimStart/TrimEnd

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#6485]
I propose we add parameterless overloads of `TrimStart`/`TrimEnd` for the String class.
# Rationale
- We have a parameterless `Trim` [method](https://msdn.microsoft.com/en-us/library/t97s7bs3%28v=vs.110%29.aspx), so it's best to do this for symmetry.
- <s>We can avoid array allocations every time the method is called, e.g. `TrimStart()` would no longer transparently allocate an array. We can avoid this with `TrimStart(Array.Empty<char>())`, but that's besides the point.</s>
- With the [current implmementation](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/String.cs#L1366) in CoreCLR, it would be relatively trivial to implement. Just add this to the class:

``` csharp
public string TrimStart() => TrimHelper(TrimHead);
public string TrimEnd() => TrimHelper(TrimTail);
```
- Perhaps this is just me, but when I first came across the `TrimStart(params char[])` overload (as a beginner to C#), I wasn't even aware that you could leave a `params` method empty. I just assumed that the functionality I was looking for wasn't available, and ended up making my own helper method.
# Proposed API

``` csharp
namespace System
{
    public class String
    {
        // New methods
        public string TrimStart();
        public string TrimEnd();
    }
}
```

**Comment by stephentoub** [comment]
> We can avoid array allocations every time the method is called

When you compile with Roslyn and Array.Empty is available, it'll use Array.Empty for the argument rather than allocating an array.

**Comment by JonHanna** [comment]
> We can avoid this with TrimStart(Array.Empty<char>()), but that's besides the point.

You can also use `TrimStart(null)`, to avoid even that, if you aren't using Roslyn.

**Comment by jamesqo** [comment]
@stephentoub Huh, I didn't know that; props to Roslyn. Even so, Array.Empty still creates more overhead, since it has to lazily initialize an array/introduces another method call.

**Comment by jamesqo** [comment]
@JonHanna Yeah, but most people don't do that. :wink:

**Comment by svick** [comment]
@jamesqo 

> Array.Empty still creates more overhead, since it has to lazily initialize an array/introduces another method call.

I doubt that overhead is going to be measurable under normal circumstances. That lazy initialization is using a static field initializer, which usually doesn't have any overhead beyond the first call. And that method call is very likely going to be inlined. So the total overhead should be just a static field load.

**Comment by jamesqo** [comment]
@svick I suppose you guys are right; I crossed out that bullet point from the list.

**Comment by terrajobst** [comment]
I think having these overloads make sense; however, I've moved it to future because it requires changes to the .NET Framework in order to be compatible at RTM. This change doesn't make the bar for the upcoming version so it has to queued up for the next train.

**Comment by jamesqo** [comment]
@terrajobst Sounds good. Thanks for taking this proposal into consideration :smile:

**Comment by terrajobst** [comment]
Looks good as proposed.

**Comment by AlexGhiondea** [comment]
This should be a simple fix on Core. Anyone interested in taking this over?

**Comment by fujiy** [comment]
I plan to work on it

**Comment by AlexGhiondea** [comment]
@fujiy that is great! Looking forward to the PR! 😄

**Comment by karelz** [comment]
Adding @fujiy to collaborators list, so that it can be assigned to him ... @AlexGhiondea please ping me in future on such assignment requests.

**Comment by karelz** [comment]
@fujiy please don't forget to ping me on issues you want to grab at the time you are ready to start working on them.

**Comment by fujiy** [comment]
@thiagocamargos will fix this issue. Thanks

**Comment by karelz** [comment]
Invite sent ...

**Comment by karelz** [comment]
Assigned to @thiagocamargos

**Comment by thiagocamargos** [comment]
@karelz i'm ready to start working on this

**Comment by thiagocamargos** [comment]
Hi @karelz , I've submited the PR and it is now waiting on https://github.com/dotnet/coreclr/pull/8834

**Comment by jamesqo** [comment]
Don't tests need to be added for this too?

**Comment by fujiy** [comment]
We also need to send a PR to expose those methods at System.Runtime

**Comment by justinvp** [comment]
I went ahead and grabbed this: #15476

**Comment by karelz** [comment]
Thanks @justinvp!
@thiagocamargos hopefully not any duplicated work here ...
