### ISSUE TITLE
Support setting outgoing interface for multicast on Socket

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#6486]
The desktop framework and mono support setting the interface used for outgoing multicast traffic by passing the interface index as a value for the MulticastInterface SocketOption.
```
socket.SetSocketOption(SocketOptionLevel.IP, SocketOptionName.MulticastInterface, IPAddress.HostToNetworkOrder(interfaceIndex))
```
On Windows this is an acceptable value for IP_MULTICAST_IF, see [msdn IPPROTO_IP](https://msdn.microsoft.com/en-us/library/windows/desktop/ms738586%28v=vs.85%29.aspx).
On non-Windows platforms the request should be translated to pass an ip_mreqn as the IP_MULTICAST_IF value, see [man ip](http://man7.org/linux/man-pages/man7/ip.7.html).

The mono implementation for translating the value on non-Windows platforms can be found here:
https://github.com/mono/mono/blob/master/mono/metadata/socket-io.c#L2333-L2345

**Comment by stephentoub** [comment]
cc: @SidharthNabar, @davidsh, @CIPop

**Comment by stephentoub** [comment]
@tmds. it's not clear to me from your description... you say this works on the desktop framework and mono... where does it not work?  Does it work on Windows on coreclr?  Do you have a small repro you can share that fails?

**Comment by tmds** [comment]
Clarifying what the issue is about:
On all platforms it is already possible to set the interface for outgoing multicast by specifying it's network address. This value is passed as an in_addr to the underlying platform.

On Windows something special happens when this address is in the 0.x.x.x block. In that case, the address is treated as an interface index instead. For example: 0.0.0.1 is saying: send outgoing multicast traffic on the interface with index 1.

On non-Windows platform, this isn't the case. So these platforms go looking for an interface with an address 0.x.x.x, which always fails.
These other platforms have support for specifying the multicast interface by index by passing an ip_mreqn instead of an in_addr. This struct has a dedicated field for passing the interface index: imr_ifindex.

\cc @ericeil
