### ISSUE TITLE
Outer loop runs aren't running inner loop tests!

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#6495]
```/p:WithCategories="InnerLoop;OuterLoop"``` is being passed to msbuild, causing ```-trait category=InnerLoop -trait category=OuterLoop``` to be passed to the xunit command line, but "inner loop" tests aren't attributed with an [InnerLoop] attribute, there is no "InnerLoop" trait, etc., and so the only tests that are getting run are the few outer loop ones.

**Comment by Priya91** [comment]
this can be done by using the /p:OuterLoop=true, added by @ianhays [here](https://github.com/dotnet/buildtools/commit/a66d53ee7a3184711d3d0c76ea032cb609373596)
