### ISSUE TITLE
Configuring project to Define conditional compilation symbol and allow unsafe block

### ISSUE THREAD

**Issue by SirusDoma** [dotnet/corefx#6501]
Hello there!
Today, I tried dotnet core, created a new simple hello world project via Visual Studio 2015 (C# -> Web -> Console Application (Package)), it automatically restore the packages, and once finished, I just compile it. It's work like a charm!

However, I would like to add conditional compilation symbol and allow unsafe block.
How can I do that? thanks in advance

**Comment by mellinoe** [comment]
You can add some compilation options to project.json, see here: https://github.com/aspnet/Home/wiki/Project.json-file.

**Comment by SirusDoma** [comment]
Thanks for your response!
