### ISSUE TITLE
Restoring a "dotnet new - Hello World" console app downloads 340 MBs of NuGet packages

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefx#6530]
To repro on a new machine (or delete your `%userprofile%\.nuget\packages` folder):

- Install the latest dotnet cli: https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-win-x64.latest.exe
- In a new cmd prompt:
  - mkdir C:\DotNetTest
  - cd C:\DotNetTest
  - dotnet new
  - dotnet restore
  - dotnet run

# Expected Results
In all actuality, I expected the same .NET assemblies that I installed when I installed the dotnet cli to be used.

# Actual Results
dotnet restore takes a while, and when it is finished my `%userprofile%\.nuget\packages` folder is 340 MB on disk.

Looking into this, a lot of the NuGet packages we download have xml files for every supported language, for multiple versions, and for multiple TFMs. For example:

```
System.Runtime.Extensions
|--- / 4.0.10
        |--- /ref
                |--- /dotnet
                        |--- /de
                                |--- /System.Runtime.Extensions.xml     325 KB
                        |--- /es
                        |--- /.. 7 other languages
                |--- /MonoAndroid10
                |--- /... 4 other TFMs
|--- / 4.1.0-rc2-23811
        |--- /ref
                |--- /dotnet5.1
                        |--- /de
                                |--- /System.Runtime.Extensions.xml     325 KB
                        |--- /es
                        |--- /.. 7 other languages
                |--- /... 11 other TFMs
```

System.Runtime.Extensions alone is 14.2 MB

**Comment by mellinoe** [comment]
What's the action item here, exactly? The CLI has its dependencies bundled in with the product, not in the package cache. That is going off the [raw zip](https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/Latest/dotnet-win-x64.latest.zip) I downloaded earlier today, but I would guess that the MSI is the same.

**Comment by eerhardt** [comment]
I think the biggest/first action item would be to reduce the size of our packages.  The example I show above is repeated for other packages. For example, there are two versions of System.Runtime which account for 84 MB on disk.

18 TFMs X 9 languages is making up for a big problem. Maybe one step we could do is create language specific packages. Each developer only cares about a single language. At most, they care about their native language and maybe English.

**Comment by ericstj** [comment]
So currently intellisense has very strict rules for the layout of xml docs.  @yishaigalatzer has requested feature here but I haven't heard if anything is happening.

NuGet had a feature to split docs out then they'd recompose at restore time, but that doesn't work with NuGet v3/project.json: https://github.com/NuGet/Home/issues/2245.

You should see that the latest packages are closure-complete on the latest set so that will help reduce the number of duplicate packages downloaded.

**Comment by yishaigalatzer** [comment]
Let's revive the thread with core vs on this?

**Comment by weshaggard** [comment]
I don't think there is really anything specifically actionable here so I'm closing. We will try and figure out if there is anything we can do to split out things from the packages but those would be individual separate issues.
