### ISSUE TITLE
HttpClient.GetAsync does not call virtual SendAsync

### ISSUE THREAD

**Issue by maciejw** [dotnet/corefx#6535]
can you confirm that this is NOT by design?

All [Verb]Async methods except GetAsync end up in one particular SendAsync method
```
public override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,
            CancellationToken cancellationToken)
```

I think GetAsync should not be en exception.

**Comment by davidsh** [comment]
This is By-Design.  What are you observing that is wrong with the implementation?

By the way, all of the convenience helper methods of HttpClient (such as GetAsync, PostAsync) eventually call the main handler (HttpClientHandler, usually) and it is the SendAsync virtual method of that class that is actually doing the work.

And if you need to hook into the pipeline chain of handlers, you should look at the DelegatingHandler and chain of handlers architecture with how HttpClient is designed.

**Comment by davidsh** [comment]
See this article for a historical perspective on the architecture of HttpClient and the handler pipeline:

**Comment by maciejw** [comment]
when I derive from HttpClient GetAsync call will not call my overriden SendAsync method. 

I wanted to use decorator with HttpClinet and compose some things this way. I could do it using HttpMessageHandler, but this GetAsync should call this overriden SendAsync I think:) I look into DelegatingHandler, thanks.

**Comment by davidsh** [comment]
You should not be deriving HttpClient in the first place.  It is not meant to be derived from at least in terms of overriding "SendAsync" behavior.

The design pattern is to create a new HttpMessageHandler (or use the DelegatingHandler) class.  That has the virtual SendAsync() method that you can override.  Then you pass in that new HttpHandler chain into the constructor for HttpClient.

**Comment by maciejw** [comment]
OK, thanks for clarification. I look into it.

**Comment by davidsh** [comment]
Ok. We'll close this issue since the question was answered.

**Comment by vanillajonathan** [comment]
This is also issue when inheriting from `HttpMessageHandler` and passing it in the constructor to the `HttpClient`. Then the `SendAsync` method declared in the `HttpMessageHandler` does not get called when calling the `GetAsync` method on the `HttpClient` instance.
