### ISSUE TITLE
Code coverage doesn't work for all assemblies

### ISSUE THREAD

**Issue by mmitche** [dotnet/corefx#655]
Code coverage is broken for a few assemblies (tests or coverage fails when enabled).  Investigate.

All test projects with <CoverageEnabledForProject>false</CoverageEnabledForProject> have had their coverage disabled.

**Comment by mellinoe** [comment]
Do we know why it is broken for some of them? How can we investigate and implement a fix for that, i.e. can we make a pull request and have a "code-coverage run" happen?

**Comment by mmitche** [comment]
It’s not currently run as a PR test, so hmm.  But it can easily be run locally (just use /p:Coverage=true)

Not sure why it is broken for some of them.  It may be altering test timing enough to make some tests fail, there were some permissions issues with the filesystem tests, an assertion popup in xml, etc.

What would be AWESOME..would be if you could request a specific job for a PR.   Like, I set up PR jobs for each job but don’t enable them by default.  Instead you request them in your PR using a comment or such.

Will look into this Monday.

Matt
