### ISSUE TITLE
cannot compile system.net.sockets

### ISSUE THREAD

**Issue by ddobric** [dotnet/corefx#6555]
Hi all,

trying to compile System.Net.Sockets. It fails with errors:

"System.Net.NameResolution 4.0.0-rc3-23829 is not compatible with DNXCore,Version=v5.0.
 System.Security.Principal.Windows 4.0.0-rc3-23829 is not compatible with DNXCore,Version=v5.0."

..build output...

Restoring NuGet packages...
 To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
 Detected package downgrade: System.Collections from 4.0.10 to 4.0.0 
 System.Net.Sockets (≥ 1.0.0) -> System.IO.FileSystem (≥ 4.0.0) -> System.Collections (≥ 4.0.10) 
 System.Net.Sockets (≥ 1.0.0) -> System.Collections (≥ 4.0.0)
 Detected package downgrade: System.Collections from 4.0.10 to 4.0.0 
 System.Net.Sockets (≥ 1.0.0) -> System.Net.Primitives (≥ 4.0.10) -> System.Private.Networking (≥ 4.0.0) -> System.Collections (≥ 4.0.10) 
 System.Net.Sockets (≥ 1.0.0) -> System.Collections (≥ 4.0.0)
 Detected package downgrade: System.Globalization from 4.0.10 to 4.0.0 
 System.Net.Sockets (≥ 1.0.0) -> System.Net.Primitives (≥ 4.0.10) -> System.Private.Networking (≥ 4.0.0) -> System.Globalization (≥ 4.0.10) 
 System.Net.Sockets (≥ 1.0.0) -> System.Globalization (≥ 4.0.0)
 System.Net.NameResolution 4.0.0-rc3-23829 is not compatible with DNXCore,Version=v5.0.
 System.Security.Principal.Windows 4.0.0-rc3-23829 is not compatible with DNXCore,Version=v5.0.
 Some packages are not compatible with DNXCore,Version=v5.0.
 The project 'System.Net.Sockets' does not specify any target frameworks in 'C:\tfs\git\corefx\src\System.Net.Sockets\ref\project.json'.
 NuGet package restore failed.
 1>------ Rebuild All started: Project: System.Net.Sockets (src\System.Net.Sockets), Configuration: Windows_Debug Any CPU ------
 1> System.Net.Sockets -> C:\tfs\git\corefx\bin\Windows_NT.AnyCPU.Debug\System.Net.Sockets\System.Net.Sockets.dll

Thanks
 Damir

**Comment by Clockwork-Muse** [comment]
If you're building via VisualStudio, does this actually keep you from building, or is it just giving the "error"?  It's complaining in System.Threading.Tasks, but doesn't stop builds.  That's what it looks like is happening here, given the output lists a dll.

**Comment by ddobric** [comment]
It is a real error. I get the same one when I try >dnu build

**Comment by ericeil** [comment]
Are you able to build other corefx projects?  Does your repro build successfully using build.cmd?

**Comment by ddobric** [comment]
Yes. I tried for example .Collections solution. It builds fine.

**Comment by ericeil** [comment]
FWIW, I see similar errors when building in VS, for both System.Collections *and* System.Net.Sockets.  As @Clockwork-Muse points out, the project still builds.  If I build the projects from the command line, using MSBuild, I don't see these errors.  

Perhaps @chcosta can shed some light on this.

**Comment by chcosta** [comment]
The version of NuGet that Visual Studio uses does not support the netstandard packages.  To work around this, do a build once from the command line (per @ericeil, and I have confirmed locally), this should build, then in Visual Studio, Options->NuGet Package Manager->General and disable both "Allow NuGet to download missing packages" and "Automatically check for missing packages during build in Visual Studio".  This will prevent NuGet from trying to download the new packages which it doesn't understand but you have already downloaded.

**Comment by chcosta** [comment]
@ddobric, are you still blocked?

**Comment by chcosta** [comment]
Pushing to RTM.  I will close if no repro or receive confirmation that the issue is resolved.  I'll move back to this milestone if I hear more information.

**Comment by ericstj** [comment]
Issue here is that VS/DNU had an older version of the NuGet codebase that had different behavior than the pre-release one we're using in CoreFx.  You can update to the latest NuGet 3.4 and it should address these issues (until we depend on new features in 3.5) and the latest dotnet CLI (instead of DNU) will also work.
