### ISSUE TITLE
FileSystemInfo contains missing/wrong info when symbolic links become broken

### ISSUE THREAD

**Issue by palladia** [dotnet/corefx#6556]
Originally filed in [coreCLR issue #3366](https://github.com/dotnet/coreclr/issues/3366), but perhaps it's  more appropriate here.

Running dotnet 1.0.0-beta-001472 on Ubuntu 14.04.1, System.IO.FileSystem.*:  4.0.0-rc3-23819:

On Linux, a symbolic link has following typical FileSystemInfo
-----------------------
Mode              : --r--l
VersionInfo       : File:             /usr/bin/dotnet
                    InternalName:
                    OriginalFilename:
                    FileVersion:
                    FileDescription:
                    Product:
                    ProductVersion:
                    Debug:            False
                    Patched:          False
                    PreRelease:       False
                    PrivateBuild:     False
                    SpecialBuild:     False
                    Language:

BaseName          : dotnet
Target            :
LinkType          : SymbolicLink
Name              : dotnet
Length            : 31208
DirectoryName     : /usr/bin
Directory         : /usr/bin
IsReadOnly        : True
Exists            : True
FullName          : /usr/bin/dotnet
Extension         :
CreationTime      : 1/1/01 12:00:00 AM
CreationTimeUtc   : 1/1/01 12:00:00 AM
LastAccessTime    : 2/25/16 10:49:00 AM
LastAccessTimeUtc : 2/25/16 6:49:00 PM
LastWriteTime     : 2/18/16 8:29:59 AM
LastWriteTimeUtc  : 2/18/16 4:29:59 PM
Attributes        : ReadOnly, ReparsePoint
-------------------------------
Everything looks reasonable, except that Target is not specified, and Creation Time looks wrong.

But if I delete the target where the symbolic link points to, now my FileSystemInfo looks something like this:
--------------------------------
Mode              :
VersionInfo       :
BaseName          : dotnet-compile-native
Target            :
LinkType          : SymbolicLink
Name              : dotnet-compile-native
Length            :
DirectoryName     : /usr/bin
Directory         : /usr/bin
IsReadOnly        :
Exists            : False
FullName          : /usr/bin/dotnet-compile-native
Extension         :
CreationTime      :
CreationTimeUtc   :
LastAccessTime    :
LastAccessTimeUtc :
LastWriteTime     :
LastWriteTimeUtc  :
Attributes        :
------------------------------------
Notice that many fields are now blank.  Worse yet, the Exists field now says "False".  And if I try to access Attributes field, I get a FileNotFoundException.

Now compare this with a similar set up (i.e. symlink is broken) on a Windows Machine (running full CLR), you get this:
------------------------------------
Mode              : d----l
BaseName          : symlinkfile
Target            : {testfile.txt}
LinkType          : SymbolicLink
Name              : symlinkfile
Parent            : test
Exists            : True
Root              : C:\
FullName          : C:\Users\v-geflem\test\symlinkfile
Extension         :
CreationTime      : 2/25/2016 9:58:44 AM
CreationTimeUtc   : 2/25/2016 5:58:44 PM
LastAccessTime    : 2/25/2016 9:58:44 AM
LastAccessTimeUtc : 2/25/2016 5:58:44 PM
LastWriteTime     : 2/25/2016 9:58:44 AM
LastWriteTimeUtc  : 2/25/2016 5:58:44 PM
Attributes        : Directory, ReparsePoint
----------------------------------------
Notice that on Windows, a broken symbolic link still shows it as having Exist of "True".
This inconsistency is causing me griefs in developing a cross-platform product.

**Comment by stephentoub** [comment]
Thanks for the issue.

We had a discussion about related issues here:
https://github.com/dotnet/corefx/issues/5630

Based on that, what do you propose we do differently?

**Comment by palladia** [comment]
I agree that trying to match Windows behavior of symbolic links makes this a difficult problem.  

On Linux, FileSystemInfo should show the link itself, not what it points to.  In fact, you can create a symbolic link to a non-existent item in Linux.  With that assumption, FileSystemInfo.Exists should always be 'true', and FileSystemInfo.Attributes should never throw exceptions.  

My 2 cents...

**Comment by stephentoub** [comment]
> With that assumption, FileSystemInfo.Exists should always be 'true', and FileSystemInfo.Attributes should never throw exceptions.

So just to make sure I understand, you're saying that you'd want FileSystemInfo to be different from File/FileInfo and Directory/DirectoryInfo in this regard, that FileSystemInfo should never follow a symlink, for any functionality... am I understanding correctly?

**Comment by andschwa** [comment]
After reviewing, I think your current implementation is the best compromise. Python made the same compromise. I would change my mind if we were to add new interfaces for dealing with symlinks explicitly (which is what Boost did), thus leaving this up to the developer. Barring that, the current behavior should remain unchanged.

In @palladia's case, we need to ignore the `File.Exists` attribute if `LinkType == SymbolicLink` (aka it's a "reparse point"). This is as close as we can currently get to having an explicit symlink interface (if it's a symlink, treat the information differently).

**Comment by andschwa** [comment]
This should be safe because, if the symlink itself didn't exist, the `ReparsePoint` property would not be set, is that correct @stephentoub?

**Comment by stephentoub** [comment]
> if the symlink itself didn't exist, the ReparsePoint property would not be set, is that correct @stephentoub?

That's correct.

**Comment by palladia** [comment]
FileSystemInfo is just base class of FileInfo/DirectoryInfo, right?  

On Linux, a symbolic link is just another type of file, like pipes, sockets, etc.  Whether it points to something valid or not, it shouldn't matter.  What I do a Directory.EnumerateFiles(), I shouldn't have to look individually at each file to see if it's a symbolic link on Linux, and then treat it differently.  I have to do that now to avoid a crash when I look at its Attributes.

**Comment by stephentoub** [comment]
> FileSystemInfo is just base class of FileInfo/DirectoryInfo, right

Yes, I was trying to understand if you were somehow asking for different behavior when used via the base reference.

> On Linux, a symbolic link is just another type of file, like pipes, sockets, etc. Whether it points to something valid or not, it shouldn't matter.

But the whole point of a symlink is they're used in place of other ones as a redirection, with the idea that most consumers shouldn't actually care that they're not looking at the real one.  You call Directory.EnumerateFiles for a symlink to a directory, you expect that to successfully enumerate the directory, not throw because it's not a directory.  When you File.Open for a symlink, you expect it to open the target, not read the contents of the symlink file (readlink).  And File/FileInfo and Directory/DirectoryInfo are used interchangeably, so we shouldn't have different behavior for File from FileInfo and Directory from DirectoryInfo for these kinds of things.

**Comment by andschwa** [comment]
@palladia You *always* have to treat symbolic links differently (follow or not follow). What .NET does here does not affect that; they're just choosing a default behavior that's easiest to deal with.

The only real bug is just lack of documentation on the choice :smile: I'm sure that will all come in time!

**Comment by palladia** [comment]
I guess that's why Linux has lstat vs. stat.  It's definitely not clear that you should always follow the link.

**Comment by stephentoub** [comment]
> I guess that's why Linux has lstat vs. stat. It's definitely not clear that you should always follow the link.

And we just have one thing.  We have to pick a single behavior that'll make most things "just work".

**Comment by palladia** [comment]
If I do a "ls", I want to see the link itself.  If I open a file, I expect it to follow the link.  If I "rm" a link, I want to remove the link, not what it points to.

**Comment by andschwa** [comment]
Correct. And in this case, lstat is used; then if it's a symbolic link, that information is noted, and then stat is used.

However, I would like to know what is done for `File.Delete`. @stephentoub does that operation affect the link or its target?

**Comment by palladia** [comment]
I don't know if a single behavior makes sense for Linux.

**Comment by stephentoub** [comment]
> If I do a "ls", I want to see the link itself

That's Directory.EnumerateFiles... you'll see the link.

> If I open a file, I expect it to follow the link.

That's File.Open* / FileStream.ctor... it follows the link.

> If I "rm" a link, I want to remove the link, not what it points to.

That's File.Delete... and it deletes the link.

> @stephentoub does that operation affect the link or its target?

The link.

**Comment by stephentoub** [comment]
> I don't know if a single behavior makes sense for Linux.

I don't understand.  How can we have a single operation do two different things?  Seems we're talking past each other.

**Comment by palladia** [comment]
If I do a "ls", I want to see the link itself
That's Directory.EnumerateFiles... you'll see the link.

Except that if the link becomes broken, your FileSystemInfo becomes totally messed up.

**Comment by andschwa** [comment]
The behaviours you just listed are what I'd expect given the implementation, and are the best defaults.

@palladia Not messed up, just not what we were expecting. It'll say it doesn't exist, but it will also note that it's a symlink. So "symlink existence" is equivalent to `File.Exists || File.IsSymlink` (pseudocode).

**Comment by andschwa** [comment]
I think that's all we needed to know.

**Comment by stephentoub** [comment]
> Except that if the link becomes broken, your FileSystemInfo becomes totally messed up.

If the link becomes broken, the FileSystemInfo's ReparsePoint will still be true.  Yes, you'll get an error if you try to then use it, but you can detect that via the attributes.  If we instead had Exists return true in this case, then you'd try to use the file and blow up, and there' s no API you can check to detect that.

**Comment by stephentoub** [comment]
If by "totally messed up", do you mean you can't use it at all?  I agree you should be able to inspect the attributes so that you can see if it's a reparse point.  If that's not working, I'll fix that.

**Comment by palladia** [comment]
Isn't this what "Target" field is for?  

For current implementation of Get-ChildItem in Powershell, it outputs FileSystemInfo as an object.  So if a sym link gets severed, I can catch the FileNotFound exception, but it will not display anything for Mode, Length, CreationDate, etc.

**Comment by palladia** [comment]
Yes, once a sym link gets severed, FileSystemInfo.Attributes throws FileNotFound Exception, and most other fields become blank.  This exception gives me more headache than the Exists field.

**Comment by stephentoub** [comment]
> Isn't this what "Target" field is for?

Target on what?  FileSystemInfo doesn't have a Target member.

> This exception gives me more headache than the Exists field.

I believe you're in the minority.  I could of course be wrong.

> FileSystemInfo.Attributes throws FileNotFound Exception

I'll take a look.

**Comment by palladia** [comment]
I don't see Target as a property listed, but in PowerShell:

PS /home/george/PowerShell-Linux> $a = Get-ChildItem testlink
PS /home/george/PowerShell-Linux> $a.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    FileInfo                                 System.IO.FileSystemInfo

PS /home/george/PowerShell-Linux> $a | Format-List -Property *


PSPath            : Microsoft.PowerShell.Core\FileSystem::/home/george/PowerShell-Linux/testlink
PSParentPath      : Microsoft.PowerShell.Core\FileSystem::/home/george/PowerShell-Linux
PSChildName       : testlink
PSDrive           : /
PSProvider        : Microsoft.PowerShell.Core\FileSystem
PSIsContainer     : False
Mode              : -----l
VersionInfo       : File:             /home/george/PowerShell-Linux/testlink
                    InternalName:
                    OriginalFilename:
                    FileVersion:
                    FileDescription:
                    Product:
                    ProductVersion:
                    Debug:            False
                    Patched:          False
                    PreRelease:       False
                    PrivateBuild:     False
                    SpecialBuild:     False
                    Language:

BaseName          : testlink
Target            :
LinkType          : SymbolicLink
Name              : testlink
Length            : 10440
DirectoryName     : /home/george/PowerShell-Linux
Directory         : /home/george/PowerShell-Linux
IsReadOnly        : False
Exists            : True
FullName          : /home/george/PowerShell-Linux/testlink
Extension         :
CreationTime      : 1/1/01 12:00:00 AM
CreationTimeUtc   : 1/1/01 12:00:00 AM
LastAccessTime    : 2/29/16 9:58:25 AM
LastAccessTimeUtc : 2/29/16 5:58:25 PM
LastWriteTime     : 2/29/16 9:58:23 AM
LastWriteTimeUtc  : 2/29/16 5:58:23 PM
Attributes        : ReparsePoint

**Comment by palladia** [comment]
On Windows, Target field correctly points to what the symlink points to.

**Comment by andschwa** [comment]
@palladia Sanitize that post...

**Comment by stephentoub** [comment]
> On Windows, Target field correctly points to what the symlink points to.

There is no Target on FileSystemInfo.  That must be something your app is creating.

**Comment by palladia** [comment]
Yeah, I will have to investigate that, I don't know how Target gets added.

**Comment by andschwa** [comment]
@palladia You need to sanitize that post.

**Comment by stephentoub** [comment]
> FileSystemInfo.Attributes throws FileNotFound Exception

So you're right that we're throwing from Attributes; I forgot I added that behavior.  But... I'm not sure it makes sense to change it.  I get that it's causing issues for you, but anything else is going to result in very odd behavior where the FileSystemInfo morphs from being about the target file to the symlink itself.

If Exists is made to return true but the attributes are all about the symlink itself, that's extremely misleading.  I don't think we should do that.

If Exists is made to return false but have the attributes still work, that seems strange as well, as then Exists will be saying "this thing doesn't exist" but some or all of the other properties will be returning "valid" data.

**Comment by palladia** [comment]
As I stated, I think on Linux one should not follow the link by default, but I understand the desire to be consistent, and I have no problem with that.  If you think the current behavior is correct, I can work around these "problems" I have hit.

**Comment by stephentoub** [comment]
I've been discussing this offline with a few folks to get some more opinions.

We're thinking that the best (or least bad option) and most consistent is for these File/Directory/FileInfo/DirectoryInfo APIs to continue doing what they're doing for normal files/directories and valid symlinks... but for a broken symlink, to fallback to being about the symlink.  There are downsides to this, of course, in that you don't know definitively whether you're getting info on the target or the symlink, but broken symlinks should be rare, it avoids the exceptions, and it's closer to the Windows behavior (though not exactly the same, by design).

Would that help your case at all?

**Comment by stephentoub** [comment]
Actually, @ianhays and I have been playing with this more, and experimenting with lots of different use cases with mklink on Windows.  It seems we might actually want to do basically what @palladia suggests, and have all of the file information be about the symlink, but when you enumerate, open, etc., have that follow to the target...

**Comment by stephentoub** [comment]
@palladia, thanks for raising this.  We're going to basically go with your recommendation, with the caveat that we're going to special case a couple things around directories to make the APIs behave more as one would expect, e.g. Directory.Exists(validSymlinkToADirectory) should return true (whereas just doing the "normal" thing would have that return false because the symlink is a file).

**Comment by palladia** [comment]
Thanks for doing the research.  I know there's probably no perfect solution to this, and that's probably why Linux chose to have separate 'lstat' vs 'stat'.

**Comment by andschwa** [comment]
This sounds like a fine compromise. Follow the symlinks only where they make the *most* sense to do so. Cool.
