### ISSUE TITLE
ThreadAfinity support?

### ISSUE THREAD

**Issue by psibernetic** [dotnet/corefx#6562]
Just curious if there is a debate or plan on supporting thread static or if I can safely assume that ThreadAfinity is gone for good.

**Comment by ellismg** [comment]
[TheadStaticAttribute is exposed by System.Runtime](https://github.com/dotnet/corefx/blob/39471b56bd0241e60a33b4179a04187b96481547/src/System.Runtime/ref/System.Runtime.cs#L1639).  Is there something else you are looking for?

**Comment by psibernetic** [comment]
That covers it thanks, I was getting mixed up with Thread.BeginThreadAfinity
