### ISSUE TITLE
[ToFDisable] Port tests for: System.Threading.Tasks

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#6578]
As part of moving out of ToF and into the open, I've been going through the "Tree of the future" tests and calculating which of those tests provide coverage that we're missing in the open tests. The goal of this is to get the open tests universally better than the ToF tests so that we can turn the ToF tests off for ProjectK runs and save us all a lot of headache diagnosing test failures from potentially outdated tests.

For System.Threading.Tasks, we're missing 1 lines of coverage. Our total line coverage for Open vs. ToF is 99.1%. However, this includes some data points that might not be relevant to the library being tested so the real coverage is likely lower.

To fulfill the uncovered lines we would need to either create new tests for them or port 1 ToF tests to the open. Those tests are: 

- [ ] System.Threading.Tasks\4.0.0.0\Task\TCWT.RunUnwrapTests_CancellationTests\TCWT.RunUnwrapTests_CancellationTests.xml

Coverage reports, coverage xml files, and detailed json lists of each piece of missing coverage and the corresponding ToF test that fills it are available on request.

**Comment by stephentoub** [comment]
> we're missing 1 lines of coverage. 

Could you share which 1 line? I'll take care of it ;)

**Comment by ianhays** [comment]
"System.Threading.Tasks\\4.0.0.0\\Task\\TCWT.RunUnwrapTests_CancellationTests\\TCWT.RunUnwrapTests_CancellationTests.xml": [
    {
      "ModuleName": "System.Threading.Tasks",
      "ClassName": "System.Threading.Tasks.TaskExtensions",
      "MethodSignature": "System.Threading.CancellationToken System.Threading.Tasks.TaskExtensions::ExtractCancellationToken(System.Threading.Tasks.Task)",
      "LineNumber": 220
    }
  ]

**Comment by stephentoub** [comment]
@ianhays, thanks, but that line should not be coverable, as it's immediately preceded by a Debug.Fail.
https://github.com/dotnet/corefx/blob/master/src/System.Threading.Tasks/src/System/Threading/Tasks/TaskExtensions.CoreCLR.cs#L219
Did you build the ToF code as release rather than as debug?

**Comment by ianhays** [comment]
Yes, yes I did. I had not anticipated debug failures. Closing.

**Comment by ianhays** [comment]
Re-ran everything with latest sources, Debug, and less aggressive filtering and got:

For System.Threading.Tasks, we're missing 149 lines of coverage.

To fulfill the uncovered lines we would need to either create new tests for them or port 20 ToF tests to the open. Those tests are: 

- [ ] System.Threading.Tasks\4.0.0.0\TaskScheduler\TST.RunSynchronizationContextTaskSchedulerTests\TST.RunSynchronizationContextTaskSchedulerTests.xml
- [ ] System.Threading.Tasks\4.0.0.0\Task\TaskCancelWaitTests_FullRun.XML
- [ ] System.Threading.Tasks\4.0.0.0\Task\TRT.RunDelayTests_NegativeCases\TRT.RunDelayTests_NegativeCases.xml
- [ ] System.Threading.Tasks\4.0.0.0\Task\TCWT.RunContinueWithStressTestsNoState\TCWT.RunContinueWithStressTestsNoState.xml
- [ ] System.Threading.Tasks\4.0.0.0\CESchedulerPairTests_Yeti_FullRun.XML
- [ ] System.Threading.Tasks\4.0.0.0\Task\TaskRunSyncTests.TaskRunSyncTest23\TaskRunSyncTests.TaskRunSyncTest23.xml
- [ ] System.Threading.Tasks\4.0.0.0\System.Runtime.CompilerServices\TAT.AsyncTaskAwaiterTests_CTandOCE\TAT.AsyncTaskAwaiterTests_CTandOCE.xml
- [ ] System.Threading.Tasks\4.0.0.0\Task\TRT_C.RunTaskRecursiveWaitTimeoutTest\TRT_C.RunTaskRecursiveWaitTimeoutTest.xml
- [ ] System.Threading.Tasks\4.0.0.0\Task\TaskRtTests_Core_FullRun.XML
- [ ] System.Threading.Tasks\4.0.0.0\CTT.AddAndRemoveDelegates\CTT.AddAndRemoveDelegates.xml
- [ ] System.Threading.Tasks\4.0.0.0\CTT.TokenSourceDispose_Negative\CTT.TokenSourceDispose_Negative.xml
- [ ] System.Threading.Tasks\4.0.0.0\MC.TaskContinuation\MC.TaskContinuation.xml
- [ ] System.Threading.Tasks\4.0.0.0\Task\TaskContinueWithTests_FullRun.XML
- [ ] System.Threading.Tasks\4.0.0.0\Task\TAPMT.TaskAPMTest0\TAPMT.TaskAPMTest0.xml
- [ ] System.Threading.Tasks\4.0.0.0\Task\TCWT.TaskCancelWait105\TCWT.TaskCancelWait105.xml
- [ ] System.Threading.Tasks\4.0.0.0\Task\TRT_C.RunTaskWaitAllTests\TRT_C.RunTaskWaitAllTests.xml
- [ ] System.Threading.Tasks\4.0.0.0\System.Runtime.CompilerServices\ATMBT.RunAsyncAdditionalBehaviorsTests_NegativeCases2\ATMBT.RunAsyncAdditionalBehaviorsTests_NegativeCases2.xml
- [ ] System.Threading.Tasks\4.0.0.0\Task\TRT.RunRunTests_Cancellation_Negative\TRT.RunRunTests_Cancellation_Negative.xml
- [ ] System.Threading.Tasks\4.0.0.0\Task\TRT_C.RunTaskWaitAnyTests\TRT_C.RunTaskWaitAnyTests.xml
- [ ] System.Threading.Tasks\4.0.0.0\CESchedulerPairTests_Yeti\System.Threading.Tasks.Tests.CESchedulerPairTests.TestConcurrentBlockage.xml

Most of the gaps look to be from concurrency differences in the executions of the tests.

**Comment by ianhays** [comment]
Only gap is that the test ```TokenSourceDispose_Negative``` is missing. The test uses an appcontext switch ```           AppContextSwitches.SetSwitch("Switch.System.Threading.ThrowExceptionIfDisposedCancellationTokenSource", false);``` so I'm guessing that is the reason why it was left out.
