### ISSUE TITLE
System.Composition.* libraries do not produce a NuGet package

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#6598]
On top of this, the assemblies do not list an AssemblyVersion. These were "special" libraries in that they were already previously shipped as a [NuGet package](https://www.nuget.org/packages/Microsoft.Composition/1.0.30) before we moved them into corefx. We should come up with a story for them going forward. The previous version used was 1.0.30, so we should bump up from that at the very least. There is also the question of whether we want to use the old name ("Microsoft.Composition") or switch to matching the assembly names (which might be difficult since there's 5 of them).

**Comment by tmat** [comment]
Once the package is being built it should target netstandard1.X

**Comment by mellinoe** [comment]
> @mellinoe @javiercn has been trying to remove references to all imports from aspnet packages. Some of the Roslyn packages that we transitively depend on reference this package (https://github.com/dotnet/roslyn/blob/2eeb1e3f129aa6429210b20f5a01cb8159b5d3d4/src/Dependencies/Composition/project.json#L4). It would be great if you could let the Roslyn folks know once a netstandard targeting build is available.
@pranavkm

**Comment by mellinoe** [comment]
Pre-release versions of these should now be produced with nightly builds going forward.

**Comment by mellinoe** [comment]
@pranavkm , @javiercn

There are now packages for this on myget:

https://dotnet.myget.org/F/dotnet-core/api/v2/package/System.Composition/1.0.31-beta-24228-03

Still a beta version for now, but they are consumable.

**Comment by pranavkm** [comment]
We pick up this package transitively via Roslyn. Would you know if they plan on updating their dependency soon?

**Comment by Auersberg** [comment]
Any timeframe for the final packages to be published on NuGet?

**Comment by terrajobst** [comment]
@mellinoe 

I assume this can now be closed?

**Comment by mellinoe** [comment]
Yes, these are being produced. They should ship stable with our next release.
