### ISSUE TITLE
Produce package for System.Composition

### ISSUE THREAD

**Issue by terrajobst** [dotnet/corefx#6614]
We currently don't produce packages for System.Composition.*. We should do so that we've a single tree for shipping fixes and features (it's currently only producing packages in our old internal Roxel tree).

It's also worth pointing out that the Roslyn workspace layer has a dependency on the `Microsoft.Composition` package.

**Comment by weshaggard** [comment]
Looks @mellinoe filed this a day before you :) https://github.com/dotnet/corefx/issues/6598 so closing this one.

**Comment by terrajobst** [comment]
*shakesfist*

![](https://media.giphy.com/media/5SyJ1gRqIl8nS/giphy.gif)
