### ISSUE TITLE
Update clean.cmd to kill Roslyn compiler long running task.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/corefx#6615]
@joperezr 
I synced your changes to dir.props for adding the Roslyn compiler to the build process. With that change we get a long running task (VBCSCompiler.exe) after we finish building that prevents us from then running "git clean -xdf" without first manually killing that task. (can't delete the tools dir)

I'd like to request a change perhaps in the clean.cmd script to kill that task if it is still running.

Making this change in the corefx repo would be ideal since we try to keep the scripts in the Wcf repo in sync with corefx.

**Comment by mellinoe** [comment]
:+1: I've noticed this as well.

**Comment by stephentoub** [comment]
cc: @jaredpar

**Comment by jaredpar** [comment]
What version of Roslyn is CoreFx using?  Newer versions of VBCSCompiler have a `-shutdown` argument to politely shutdown the process.  Lacking that though you can safely just kill the process.  It's an optimization tool, and if it's killed any compilations in progress will just fall back to `csc`.

**Comment by joperezr** [comment]
@jaredpar we are using what was the LKG version when we added this support which is **1.2.0-beta1-20160202-02**. Does that include the -shutdown support? Also, does that flag get passed in automatically or does it need to get passed in to the csc task?

**Comment by jaredpar** [comment]
@joperezr that build doesn't have the flag.  

> Also, does that flag get passed in automatically or does it need to get passed in to the csc task?

Not sure what you mean by this.  If you're asking if the MSBuild Csc Task passes this flag then no.  MSBuild doesn't have a concept of build completed.  Hence there is no place for it to pass the flag.  

If MSBuild did have a notion of completed build we'd certainly think hard about hooking into that and using it to shut down the server.
