### ISSUE TITLE
Break X509Certificates dependency on FileSystemWatcher

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#6618]
I'm looking at our dependencies and noticed that the unix implementation of X509Certificates depends on FileSystemWatcher which we should try to break the dependency on. 

https://github.com/dotnet/corefx/commit/0522e19dc6c06bd80c1f80232fd9600862cdb70c#diff-9c28d44206dff30cadeb4ac3e316aabaR32

I don't know the reliability of FileSystemWatcher on unix but it is notoriously bad on windows and we shouldn't have a dependency on it from a low level library.

**Comment by bartonjs** [comment]
On Windows the cert store has a flag to keep open store handles synchronized with external changes; and for some reason .NET uses that flag.  This is about the closest we can come to that behavior, unless we want to do re-read from the filesystem every time someone asks a store instance a question.

Or we could just have a behavioral change between the two.

**Comment by bartonjs** [comment]
Chatted with @weshaggard.  My gut response is that hardly anyone reads the X509Store.Certificates collection more than once on the same instance.  So we're going to just remove the cache and cache invalidation and cold read on every collection walk.

We can always revisit that later.
