### ISSUE TITLE
Should state OS support in developer documentation

### ISSUE THREAD

**Issue by Alexx999** [dotnet/corefx#663]
Should explicitly state which OS should be supported.
This is required so everyone can understand what API can be used.
For example, it's obvious that Windows 7, 8 and 8.1 must be supported, it turns out that XP is not supported (see #303), what about Vista?
I think the same goes for Linux.

**Comment by joshfree** [comment]
Thanks for bringing this issue up.  The current minimum supported OS is Windows 7.  

/cc @richlander

**Comment by ellismg** [comment]
I added some notes to the Wiki about what OS's .NET Core needs to support.
