### ISSUE TITLE
Replace internal ImmutableList in System.Threading.Tasks.Dataflow with System.Collections.Immutable List

### ISSUE THREAD

**Issue by SunnyWar** [dotnet/corefx#6652]
System.Threading.Tasks.Dataflow.Internal contains an ImmutableList<T>. Now that we have System.Collections.Immutable with a ImmutableList<T>, it seems prudent to remove the internal one from Dataflow and replace it's use with the public version.

**Comment by stephentoub** [comment]
I'm not convinced it's worthwhile, actually.  It'd be forcing anyone using Dataflow to also pull in the whole System.Collections.Immutable library, when in reality Dataflow just uses this type for one non-mainstream piece of functionality.  Dataflow's internal ImmutableList is really just a very trimmed down version of System.Collection.Immutable's ImmutableArray, so it wouldn't even be using much of the functionality of that one type, nevermind any of the other types in the library that would come along for the ride.
