### ISSUE TITLE
Make Queue<T> inheret from IProducerConsumerCollection<T>

### ISSUE THREAD

**Issue by SunnyWar** [dotnet/corefx#6653]
Given that: IProducerConsumerCollection<T> : IEnumerable<T>, ICollection, IEnumerable

and:   public class Queue<T> : IEnumerable<T>, ICollection, IEnumerable

It seems reasonable to change Queue to:

public class Queue<T> : IProducerConsumerCollection<T>

Besides simplification, this will enable the IProducerConsumerCollection to replace the IProducerConsumerQueue in the Dataflow classes.

**Comment by stephentoub** [comment]
```IProducerConsumerCollection<T>``` is for thread-safe collections.  ```Queue<T>``` is not one.
