### ISSUE TITLE
SingleProducerSingleConsumerQueue uses IProducerConsumerQueue which is for thread-safe collections but it's not.

### ISSUE THREAD

**Issue by SunnyWar** [dotnet/corefx#6654]
SingleProducerSingleConsumerQueue<T> : IProducerConsumerQueue<T>

nuff said.

**Comment by stephentoub** [comment]
> nuff said

Not really.  Why is this a problem?  It's not the public IProducerConsumerCollection, it's an internal IProducerConsumerQueue interface that merely serves an internal purpose in Dataflow.

I'm not understanding the problem.

**Comment by SunnyWar** [comment]
I'm only re-opening this so that I can get across what I'm hoping to accomplish and this is as good a place as any to discuss it.

I noticed that Dataflow classes make heavy use of two queues: one concurrent and one not. Looking at there interfaces I didn't see anything special that couldn't be accomplished with Queue and ConcurrentQueue. Then I looked at what it would take to replace the internal ones and ran into the IProducerConsumerCollection interface. The Dataflow classes use the interface and then pick which queue to use based on the concurrency count. If it's 1 it used the single threaded queue, otherwise it used it's version of a concurrent queue. Then I noticed that Queue doesn't have a single interface that defines it but it's interfaces to match up perfectly with IProducerConsumerCollection. It seems the problem is solvable, but...as you mentioned, IProducerConsumerCollection is supposed to only be used for thread-safe operations.

So..there's the road I went down. Architecturally it makes sense to me to use Queue and ConcurrentQueue in the Dataflow classes instead of functional equivalences....less code to maintain and test among other things.   But it looks like there are a few things getting in the way. Whether these things _should_ get in the way is another story.

Now I'm wondering if the duel-queues are even needed in Dataflow. The ConcurrentQueue is a lock-free queue so it should be pretty fast in the single consumer/producer scenario. If Dataflow performs comparatively without errors as it did before while using ConcurrentQueue then that seems like the right approach, but it's a bigger change.

Comments please.
.

**Comment by stephentoub** [comment]
> The ConcurrentQueue is a lock-free queue so it should be pretty fast in the single consumer/producer scenario

"lock-free" doesn't mean it's as cheap as possible... SingleProducerSingleConsumerQueue is not only lock-free, it's also interlocked-free, and has better performance for the target cases than does ConcurrentQueue.

> Architecturally it makes sense to me to use Queue and ConcurrentQueue in the Dataflow classes instead of functional equivalences....less code to maintain and test among other things

It's not functionally equivalent.  As noted, Queue provides no thread-safety guarantees, SingleProducerSingleConsumerQueue provides guarantees for a single consumer concurrent with a single producer, and ConcurrentQueue provides guarantees for any number of concurrent consumers and producers.  The code is there for a very specific reason.
