### ISSUE TITLE
SSLv3.0 is not supported on Windows but is supported on Linux

### ISSUE THREAD

**Issue by joelverhagen** [dotnet/corefx#6668]
This very well may be an environment issue (I am vaguely aware that curl is used on non-Windows platforms), but I wanted to report it just in case. I made a test app to demonstrate this: [SslProtocols.zip](https://github.com/dotnet/corefx/files/159292/SslProtocols.zip). Just use `dotnet restore` and `dotnet run` to try it.

My CI test results indicated that Mac does not support SSLv3.0 just like Windows, but I was not able to log in and try my test app there.

#### Windows
```
SSLv2.0: not supported   (exception: A connection with the server could not be established)
SSLv3.0: not supported   (exception: A security error occurred)
TLSv1.0: supported       (response: HTTP/1.1 200 OK)
TLSv1.1: supported       (response: HTTP/1.1 200 OK)
TLSv1.2: supported       (response: HTTP/1.1 200 OK)
```

#### Linux
```
SSLv2.0: not supported   (exception: SSL connect error)
SSLv3.0: supported       (response: HTTP/1.1 200 OK)
TLSv1.0: supported       (response: HTTP/1.1 200 OK)
TLSv1.1: supported       (response: HTTP/1.1 200 OK)
TLSv1.2: supported       (response: HTTP/1.1 200 OK)
```

_(note that the inner exception message is different from Windows and Linux, not sure if that is an issue)_

#### Windows

[Version 1.0.0.001598](https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/1.0.0.001598/dotnet-win-x64.1.0.0.001598.zip)

```
.NET Command Line Tools (1.0.0)
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```

#### Linux
```
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  N/A

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 Runtime Id:  ubuntu.14.04-x64
```

**Comment by joelverhagen** [comment]
Also note that this is different from the default .NET Framework (desktop) functionality where SSLv3.0 and TLSv1.0 are supported by default but TLSv1.1 and TLSv1.2 can be manually turned on using `ServicePointManager.SecurityProtocol`.

**Comment by davidsh** [comment]
cc: @CIPop @stephentoub 

We explicitly chose to not support unsecure protocols like Ssl30 in our .NET Core platform. In fact, the latest .NET Framework will be deprecating them as well.

If Ssl30 is being supported in our *Nix implementation of SslStream of HttpClient (CurlHandler), then that is a bug we need to fix.

**Comment by CIPop** [comment]
@joelverhagen Thanks for reporting this!

> Also note that this is different from the default .NET Framework (desktop) functionality where SSLv3.0 and TLSv1.0 are supported [...]

We've obsoleted the Ssl3 properties from Desktop as well (apps targeting .Net vNext will get compile-time warnings if these are referenced). For app-compat purposes, Ssl3 will still be supported on Desktop. 

>  [...] by default but TLSv1.1 and TLSv1.2 can be manually turned on using ServicePointManager.SecurityProtocol.

The (new) default introduced in .Net 4.6 is `Tls12 | Tls11 |Tls`. My recommendation for app-developers is to avoid specifying the TLS versions in their code. This allows us to add new versions and turn off versions as soon as they are deemed not secure.

**Comment by yishaigalatzer** [comment]
@stephentoub I suggest re-opening for discussion. I've heard the a customer asking to allow TLS 1.2 only (so tighter security than the framework allows), I suggest we discuss this scenario before making a final decision on this

**Comment by stephentoub** [comment]
> I suggest re-opening for discussion. I've heard the a customer asking to allow TLS 1.2 only (so tighter security than the framework allows), I suggest we discuss this scenario before making a final decision on this

A discussion is fine, but that would be a different issue.  This issue, where an older protocol was inadvertently being supported on Linux, has been fixed.  Please feel free to open a new issue if you'd like to discuss further restrictions across all .NET Core platforms.

**Comment by yishaigalatzer** [comment]
> Please feel free to open a new issue if you'd like to discuss further restrictions across all .NET Core platforms.

#6729
