### ISSUE TITLE
Process.Modules tests are hanging in CI on OS X

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#6677]
Locally then run fine, and they made it through a couple of CI runs.  But something about shelling out to vmmap is causing them to hang in CI.

**Comment by stephentoub** [comment]
@joshfree, these tests were disabled.

**Comment by anurse** [comment]
FYI We're hitting this hang in dotnet/cli. I think @pakrym can work around it by not accessing `Process.MainModule`. It only seems to happen in our xunit tests, so it must be related to something in that.

/cc @piotrpMSFT @pakrym

**Comment by stephentoub** [comment]
@anurse, I still don't know what the problem is.  It seems to have something to do with vmmap having special privileges.  Are you hitting this when trying to access MainModule of the current process, or of any process?  I'm contemplating just ripping out the OSX implementation I added and going back to just having MainModule return null and Modules return an empty array.

**Comment by anurse** [comment]
The current process
