### ISSUE TITLE
UWP

### ISSUE THREAD

**Issue by bjarteskogoy** [dotnet/corefx#6682]
I'm reading this one: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/porting.md#prioritization

Does this mean that UWP will be available on OS X and Linux?

**Comment by eadordzhiev** [comment]
No, it doesn't. It means that .NET Core can be used for developing UWP applications.

**Comment by stephentoub** [comment]
Looks like the question was answered.  As such, I'm going to close this.  Please re-open if there's a further action required here.

**Comment by bjarteskogoy** [comment]
Ok. But is there some clear statement anywhere saying that it never will or that it will or anything in between?

**Comment by svick** [comment]
@bjarteskogoy In general, you'll almost never going to get a clear statement that something will never happen, at most you're going to get a "we're not planning to do that anytime soon". And a clear statement that something like this will happen would be a big announcement.

Specifically about this, I think the following facts are relevant:

1. On February 24, it was announced that MS is buying Xamarin. Xamarin is mostly known for making .Net work on iOS and Android, but they also support Mac. And the underlying Mono platform also runs on Linux.
2. On the same day, [UserVoice request asking for a universal cross-platform platform](https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/10027638-create-a-ubiquitous-net-client-application-develo) was marked "Under Review".
3. MS often makes big announcements at Build, which is on March 30 this year.
