### ISSUE TITLE
Bug in System.Runtime.InteropServices.WindowsRuntime packaging

### ISSUE THREAD

**Issue by onovotny** [dotnet/corefx#6684]
I noticed that the System.Runtime.InteropServices.WindowsRuntime package only has a runtime output for `win8`. Unfortunately that breaks code on CoreCLR that uses reflection.

The issue is that a netstandard library can reference types in that assembly even if it’s not used at runtime. It’s part of PCL 259 as well. So if I have an app (or unit test in this case) that runs on CoreCLR and uses reflection against a type in that library, I get a FileNotFoundException and it cannot load the types.

Here's an example from Rx.NET

```
ReactiveTests.Tests.ObservableEventsTest.FromEventPattern_Reflection_Instance_InvalidVariance [FAIL]
      Expected InvalidOperationException threw FileNotFoundException.

      Stack trace:
         at System.Reactive.ReflectionUtils.GetEventMethods[TSender,TEventArgs](Type targetType, Object target, String eventName, MethodInfo& addMethod, MethodInfo& removeMethod, Type& delegateType, Boolean& isWinRT)
         at System.Reactive.Linq.QueryLanguage.FromEventPattern_[TSender,TEventArgs,TResult](Type targetType, Object target, String eventName, Func`3 getResult, IScheduler scheduler)
         at System.Reactive.Linq.QueryLanguage.FromEventPattern_[TEventArgs](Object target, String eventName, IScheduler scheduler)
         at System.Reactive.Linq.QueryLanguage.FromEventPattern[TEventArgs](Object target, String eventName)
         at System.Reactive.Linq.Observable.FromEventPattern[TEventArgs](Object target, String eventName)
         at ReactiveTests.Tests.ObservableEventsTest.<>c.<FromEventPattern_Reflection_Instance_InvalidVariance>b__9_0() in C:\Users\oren\source\git\reactive-extensions-private\Rx.NET\Source\Tests.System.Reactive\Tests\Linq\ObservableEventsTest.cs:line 280
         at Microsoft.Reactive.Testing.ReactiveAssert.Throws[TException](Action action)
      Expected: True
      Actual:   False
```

The unit test is a `netstandardapp1.5` and the library under test is a `netstandard1.0` lib. It just so happens that the code references types in that `System.Runtime.InteropServices.WindowsRuntime` package. This worked (and the tests passed) in dnx.

Note that I don't necessarily expect WinRT functionality to work, but it seems critical that the file exists and is copied to all runtimes. Xamarin had this issue at one point too as they didn't generate this façade assembly. They finally did even if it was mostly no-ops.

**Comment by onovotny** [comment]
I would broaden this to say that any of assembly that can be ref'd by a netstandard needs to be at least in the output directory on all runtimes as a shim to ensure reflection doesn't break. Otherwise random errors like this will happen depending on the platform even if the code would otherwise work.

**Comment by ericstj** [comment]
Ref for this should have been blocked by NuGet's compatibility check.  That's why we created guardrails initially.

Oren, can you clarify if you are taking a static dependency or a light-up dependency on this library?  If it's light-up then I'd expect you to catch the exception.  I wouldn't expect static dependencies since the package isn't supported on all platforms.

I'll let @yizhang82 comment on wether he thinks this file should be dropped/supported on Win7 and Unix.

**Comment by onovotny** [comment]
This was a library, Rx.NET that was ported to netstandard1.0 from a PCL 259. As this was legal in PCL 259, if you can use existing PCL 259's on a netstandardapp then you'll hit that again with other libraries.

**Comment by onovotny** [comment]
Here's where it's using it:
https://github.com/Reactive-Extensions/Rx.NET/blob/859e6159cb07be67fd36b18c2ae2b9a62979cb6d/Rx.NET/Source/System.Reactive.Linq/Reactive/Internal/ReflectionUtils.cs#L73

**Comment by ericstj** [comment]
That's a static reference to EventRegistrationToken.  Instead of a static reference you could use have a static lazy property that did something like this to get the type: https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/src/System/Reflection/Internal/Utilities/LightUpHelper.cs#L20.

**Comment by onovotny** [comment]
Could be a valid workaround but my point still stands -- because this was in PCL 259, there could be many libraries that break on this. So far, on all current platforms that support PCL's, static references have all worked.

I think it'd be confusing to change that now.
