### ISSUE TITLE
System.Resources.ResourceManager has incorrect assembly version in ref

### ISSUE THREAD

**Issue by onovotny** [dotnet/corefx#6688]
The current assembly version of the System.Resources.ResourceManager in `\ref\netstandard1.0` is 4.0.1.

This seems to be incorrect as the in-box version for `net45`-`net461` is 4.0.0.0. In the current packaging, this means that a library built with `netstandard1.x` won't work on desktop because the `\lib\net45` folder contains `_._`. 

Wouldn't the `\ref` version need to either match or an implementation be provided for net45+ to prevent binding issues?

This is accurate as-of rc2-23904. 

/cc @ericstj

**Comment by ericstj** [comment]
Inbox assemblies in the CLR's unification table will unify down so long as the first major.minor matches.  That said, the tooling on desktop isn't doing the right thing.  See https://github.com/dotnet/corefx/issues/5842.

**Comment by onovotny** [comment]
Okay, so when I'm doing the assembly version comparison in the ref generator against the in-box frameworks list, should I only compare major.minor instead of the full assembly version (to determine a match)?

**Comment by ericstj** [comment]
Here's a sample for how we do this: https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks.Packaging/src/Framework.cs#L193

**Comment by onovotny** [comment]
:+1:
