### ISSUE TITLE
Type conflict with BindingFlags

### ISSUE THREAD

**Issue by joshcomley** [dotnet/corefx#6689]
Type/namespace conflict with BindingFlags and `System.Reflection.TypeExtensions` renders code unable to compile.

Same issue discussed here:
https://github.com/dotnet/corefx/pull/6636#issuecomment-192417128

## Steps to reproduce
**program.cs:**

    using System;

    namespace ConsoleApplication
    {
        public class Program
        {
            public static void Main(string[] args)
            {
                var bf = System.Reflection.BindingFlags.CreateInstance;
            }
        }
    }

**project.json:**

    {
        "version": "1.0.0-*",
        "compilationOptions": {
            "emitEntryPoint": true
        },

        "dependencies": {
            "System.Reflection.TypeExtensions": "4.1.0-rc3-23904"
        },

      "frameworks": {
        "netstandardapp1.5": {
          "dependencies": {
            "NETStandard.Library": "1.0.0-rc3-23904"
          },
          "imports": [
            "dnxcore50",
            "portable-net451+win8"
          ]
        }
      }
    }

**Nuget.config:**

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <packageSources>
        <clear />
        <add key="AspNetCI" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
        <add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />
        <add key="nuget.org-v2" value="https://www.nuget.org/api/v2/" />
        <add key="dotnet-core" value="https://www.myget.org/F/dotnet-core/api/v3/index.json" />
        <add key="dotnet-cli" value="https://www.myget.org/F/dotnet-cli/api/v3/index.json" />
      </packageSources>
    </configuration>

Full code to reproduce is also available here:
https://github.com/joshcomley/BugSamples/tree/master/DotNetCore/BindingFlagsBug

## Expected  behavior
It should compile

## Actual behavior
`error CS0433: The type 'BindingFlags' exists in both 'System.Reflection.TypeExtensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Reflection, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'`

## Environment data
`dotnet --version` output:

.NET Command Line Tools (1.0.0-beta-001494)

Product Information:
 Version:     1.0.0-beta-001494
 Commit Sha:  c7a9d1d63a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64

**Comment by weshaggard** [comment]
This should be fixed with the next set of packages coming out tomorrow.

**Comment by weshaggard** [comment]
@joshcomley this should be fixed with build rc3-23907 please let me know if it doesn't work for you.

**Comment by troydai** [comment]
I can hit the same issue on:
__System.Reflection.Extensions 4.0.1-rc2-23910__
__System.Reflection 4.1.0-rc2-23911__

Has this fixed been merged to __rc2__ packages?

**Comment by onovotny** [comment]
I'm seeing this with rc2-23911:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'BindingFlags' exists in both 'System.Reflection.TypeExtensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Reflection, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'	Tests.System.Reactive	C:\Users\oren\Source\Git\reactive-extensions-private\Rx.NET\Source\Tests.System.Reactive\Tests\Linq\QbservableTest.cs	1764	
```

**Comment by weshaggard** [comment]
@onovotny looks like you still have some older versions of System.Reflection.TypeExtensions https://gist.github.com/onovotny/16711b59d567e43a19a0#file-project-lock-json-L3730.

**Comment by troydai** [comment]
@onovotny I used to hit the same issue. And then I realize that some of the other packages pulls in the old `System.Reflection.TypeExtensions` package. You can solve this by explicitly list `"System.Reference.TypeExtensions": "1.0.0-rc3-23907"` (or a later version) to override the issue.

**Comment by onovotny** [comment]
Thanks @troydai, that worked. Guess that was unexpected as I am not explicitly referencing `System.Reflection.TypeExtensions` anywhere else and I was referencing `NetStandard.Library` 1.5 rc2 23911 and assumed it'd bring that in. 

Any particular reason why `System.Reflection.TypeExtensions` isn't included in the NetPlatform.Library? Is it a compatibility package with an explicit opt-in intent?

**Comment by weshaggard** [comment]
System.Reflection.TypeExtensions is a compat library with extensions for a lot of things that we added to the core System.Reflection contract recently. We don't want TypeExtensions in NetStandard.Library because we expect it to fade away over time.

**Comment by onovotny** [comment]
Sorry to bother you again, I'm seeing this now in a `net461` with rc2-23918:

https://gist.github.com/onovotny/44be4c6740b639a73ff9

the project.lock.json is there; the `netstandardapp15` builds fine, the `net461` fails.

**Comment by weshaggard** [comment]
@ericstj looks like we lost the net46 ref folder when a recent update. I'm trying to track it down but if you know what caused it please point me at it.

**Comment by weshaggard** [comment]
@onovotny https://github.com/dotnet/corefx/pull/7113 should take care of that issue.
