### ISSUE TITLE
Adding an Array.Fill<T> method

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#6695]
## Background

At the moment, there's no built-in way to fill an array with a particular value in .NET. You'd have to hand-roll your own extension method, like this:

``` csharp
public static void Fill<T>(this T[] array, T value)
{
    for (int i = 0; i < array.Length; i++)
        array[i] = value;
}
```

While this may be the most obvious way, it is not necessarily the most efficient. For example, we could specialize to `memset` if the array was a byte array, or use an algorithm where we fill the beginning of the array and [double the number of elements copied each time](http://stackoverflow.com/a/13806014/4077294).

To increase the efficiency of code doing this and prevent people from reinventing the wheel, I propose we add a static `Fill` method to the `Array` class that does this.
## Proposed API

``` csharp
public class Array
{
    public static void Fill<T>(T[] array, T value);
    public static void Fill<T>(T[] array, int offset, int count, T value);
}
```

**Comment by mikedn** [comment]
> This isn't the way it should be, since there is an  initblk  IL opcode (relevant SO post) that was designed exactly for this purpose. Therefore, I propose we add a static  Fill  method to the  Array  class that serves as a wrapper for this method.

`initblk` has nothing to do with this. It can be used to fill byte arrays with a specific value but it doesn't work for any other types.

**Comment by SunnyWar** [comment]
@mikedn  isn't any array of any type just a byte array underneath? So, I'm not seeing this as a problem.

**Comment by jamesqo** [comment]
@SunnyWar Nope, he's correct. `initblk` won't work for general types, since the objects themselves within the array may not have all the same bytes (e.g. a char can be represented in memory as `65`, in addition to `66` or `55`).

@mikedn Apologies, I kind of rushed this proposal once I got the idea so pardon my misinformation :smile: I've updated the post accordingly, since I still think this is an API worth pursuing.

**Comment by jamesqo** [comment]
Updated the proposal to remove the `ArraySegment` overload, which doesn't seem too in line with the other overloads of `Array`.

**Comment by bartonjs** [comment]
This seems to be a somewhat popular request on StackOverflow: http://stackoverflow.com/questions/1014005/how-to-populate-instantiate-a-c-sharp-array-with-a-single-value

It gets a lot of bad (performance-wise) answers, too.

**Comment by karelz** [comment]
For context: We don't quite believe that the use case is very common. Doing a for-cycle sounds like a reasonable workaround. However the amount of interest on StackOverflow (100+ votes) convinced us to take it.

**Comment by jamesqo** [comment]
Great! I will submit a PR right away.
