### ISSUE TITLE
NativeTestService.exe binary should be removed from the repo

### ISSUE THREAD

**Issue by nslottow** [dotnet/corefx#670]
I should've caught this in the PR, but it looks like we committed a binary for System.ServiceProcess.ServiceController's NativeTestService to the repo.  This should get built as a dependency of the test project.  There's no need to have the binary committed and referenced directly.  See the System.Diagnostics.Process tests for an example.

Since this is a Win32 specific contract, we shouldn't need to worry about converting the build to cmake.

**Comment by mellinoe** [comment]
Do we build any native binaries in corefx right now? FileVersionInfo also has native test binaries checked in because, at the time I added those, there was no process for building native binaries. System.Diagnostics.Process uses a managed executable, which works fine in our build system.

**Comment by nslottow** [comment]
It makes a little more sense for FileVersionInfo because that's not in a Win32 specific contract, but I think we may want to come up with a process for building native binaries for tests.  That way we can avoid growing the repo by ~100KB (modulo compression) every time we need to update these binaries.

I was about to look into a couple bugs I have on ServiceController, and noticed this because I needed to modify the test service.

**Comment by Priya91** [comment]
The test project is a portable project, portable projects can only reference other protable library projects and assemblies. Since the win32 console application is not portable, the reference doesn't get resolved and the binary is not copied as a dependency to the test drop. Adding it as a content solved this problem.

**Comment by mellinoe** [comment]
> but I think we may want to come up with a process for building native binaries for tests

Yeah, I totally agree, I was just providing some context for why this is probably necessary now.

**Comment by Priya91** [comment]
Instead of copying the binary locally near the csproj, i can change it to pick from the drop of nativetestservice project, so that local copy gets updated automatically on newer build of nativetestservice

**Comment by Priya91** [comment]
closed with #675
