### ISSUE TITLE
IServiceProvider is present in both CoreCLR mscorlib and CoreFX System.ComponentModel

### ISSUE THREAD

**Issue by edmundmk** [dotnet/corefx#6704]
The IServiceProvider interface is declared in CoreCLR's mscorlib.dll, but is also present in the CoreFX System.ComponentModel.dll.  This causes conflicts when trying to compile assemblies that reference System.ComponentModel.dll and use IServiceProvider.

On Mac, using the dotnet command line tools package, something like:

Example.cs:

```
using System;

public class Problem : IServiceProvider
{
    public object GetService( Type type ) { return null; }
}
```

Compile it:

`csc -target:library Example.cs -reference:mscorlib.dll -reference:System.ComponentModel.dll`

Gives:

`Example.cs(3,24): error CS0433: The type 'IServiceProvider' exists in both 'System.ComponentModel, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'`

**Comment by akoeplinger** [comment]
You should never directly compile against mscorlib.dll, it is an implementation detail in .NET Core. Compile against the contracts like System.ComponentModel.dll.
