### ISSUE TITLE
Should DataTable be sealed in the contract and implementation?

### ISSUE THREAD

**Issue by justinvp** [dotnet/corefx#6709]
`DataTable` is currently an empty class in .NET Core, included only to complete the `IDataReader` interface. As such, the constructor is `internal` ([ref](https://github.com/dotnet/corefx/blob/e2f0f429788f611b3d7ac35f0154c975011fd191/src/System.Data.Common/ref/System.Data.Common.cs#L52-L55), [src](https://github.com/dotnet/corefx/blob/e2f0f429788f611b3d7ac35f0154c975011fd191/src/System.Data.Common/src/System/Data/DataTable.cs)), preventing external callers from subclassing or creating an instance.

Any reason why it shouldn't also be `sealed` in both the contract and implementation?

cc: @saurabh500

**Comment by saurabh500** [comment]
We will be keeping the DataTable class the way desktop has it. 
If anyone needs to subclass DataTable for any back compat reasons, they can do so.

**Comment by justinvp** [comment]
Does this mean you'll be changing `DataTable` to have a public constructor in the contract and implementation? Right now, I don't think you can't subclass it from another assembly because the constructor is internal.

**Comment by saurabh500** [comment]
I forgot about that. `DataTable` cannot be sub-classed because of the internal constructor. 
I want to leave it as is. It's there for the completion of interfaces.
