### ISSUE TITLE
Proposal: Adding a Buffer.MemoryFill method equivalent to memset

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#6710]
Separated out from #6695 since I made a false assumption that `initblk` could be used to fill non-byte arrays with a particular value; apparently not.
## Rationale

There's no fast, convenient way at the moment to fill a byte array with a particular value; the fastest method on [StackOverflow](http://stackoverflow.com/a/13806014/4077294) currently involves filling the first few bytes with a for-loop, and then iteratively copying those over to the next few bytes via calls to `BlockCopy`. It would be nice if we could just provide a `MemoryFill` method that was equivalent to memset/the initblk opcode.
## Proposed API

``` csharp
public static class Buffer
{
    public unsafe static void MemoryFill(void* pointer, byte value, long count);
    public unsafe static void MemoryFill(void* pointer, byte value, ulong count);
}
```

(revision: Changed the wording from `MemorySet` to `MemoryFill` since that sounds less awkward)

**Comment by jasonwilliams200OK** [comment]
Nit: methods are missing `unsafe` keyword.

**Comment by jamesqo** [comment]
@jasonwilliams200OK Fixed, thanks.

**Comment by vcsjones** [comment]
Would be super helpful if there were overloads that accepted `IntPtr` as well.

**Comment by jamesqo** [comment]
@joshfree I believe this should be labeled as `System.Runtime` and not `System.Buffers`, since `Buffer` lives in mscorlib.

**Comment by jamesqo** [comment]
@vcsjones I recently asked about this a few months back: https://github.com/dotnet/corefx/pull/7966#issuecomment-213498051

It seems they don't want to add `IntPtr`-based overloads since they only want to support these operations from languages that already support `unsafe`.

**Comment by jamesqo** [comment]
A few months later, I'm reconsidering this-- while a `MemoryFill` method would look nice next to the other overloads we have such as `MemoryCopy`, this seems to be just duplicating the `InitBlock` method we already have in the `Unsafe` class. So I'm closing this issue.
