### ISSUE TITLE
SerialPort cannot receive anything

### ISSUE THREAD

**Issue by derwish-pro** [dotnet/corefx#6712]
I use SerialPort class from the System.IO.Ports in the web server. Everything works fine under Windows. But there is a problem under Linux. SerialPort works only for transmission, but cannot receive anything. DataReceived event is not called.

**Comment by jasonwilliams200OK** [comment]
Are you using Mono or CoreFX? I couldn't find `System.IO.Ports.SerialPort` in the [source tree](https://github.com/dotnet/corefx/tree/e77400c/src) and the feature request is labeled <kbd>up for grabs</kbd> for anyone to take a stab at: #984.

**Comment by derwish-pro** [comment]
I'm using mono.

**Comment by jasonwilliams200OK** [comment]
Then this is a wrong repository. :)

https://github.com/mono/mono for pull request
https://bugzilla.xamarin.com/ to file a bug

**Comment by derwish-pro** [comment]
Sorry, I was referred here from aspnet/Home.
