### ISSUE TITLE
IntPtr / UIntPtr test updates

### ISSUE THREAD

**Issue by vcsjones** [dotnet/corefx#6715]
On the CoreCLR side of things the behavior of `GetHashCode` changed with dotnet/coreclr#3511 for IntPtr and UIntPtr. In the discussion there it was mentioned that while IntPtr and UIntPtr live in CoreCLR, there is unit test coverage for both of them in CoreFx and that the change should be tested here, too.

Am I correct in understanding that the test cases should be repeated here?  If so, then this issue will serve as a place holder until I make a PR with the test updates.

**Comment by stephentoub** [comment]
> Am I correct in understanding that the test cases should be repeated here? If so, then this issue will serve as a place holder until I make a PR with the test updates.

I'm not sure what tests cases were added in coreclr, but a goal here is that the tests in corefx represent the full suite of functional tests for validating the behavior of surface area exposed for .NET Core.  As such, we should ensure that behaviors around IntPtr/UIntPtr.GetHashCode have appropriate coverage:
https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/IntPtr.cs
https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/UIntPtr.cs
