### ISSUE TITLE
System.Net.Http.HttpResponseMessage.ReasonPhrase can return null on core

### ISSUE THREAD

**Issue by Tratcher** [dotnet/corefx#6721]
There was a recent regression with WinHttpHandler where HttpResponseMessage.ReasonPhrase now returns `null` rather than `string.Empty` if no reason phrase was specified in the response message. This diverges from the HttpClientHandler/HttpWebRequest behavior in the full framework that always return `string.Emtpy`. 

@davidsh

**Comment by stephentoub** [comment]
cc: @justinvp

**Comment by davidsh** [comment]
This was caused by @justinvp changes to the WinHttpHandler response parser

**Comment by davidsh** [comment]
PR #3199 caused this regression.

**Comment by davidsh** [comment]
And we should check #6322 as well (CurlHandler) to make sure it has correct behavior.

**Comment by davidsh** [comment]
As part of fixing this, I will be modifying our Azure test server endpoint:
http://corefx-net.cloudapp.net/StatusCode.ashx

to support sending statuscode but no description.
