### ISSUE TITLE
TargetingPackReferences show up in Solution Explorer

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#6722]
Something about the way that we represent these items causes them to show up in solution explorer with a warning icon:
![image](https://cloud.githubusercontent.com/assets/8918108/13580501/6b22a978-e457-11e5-98c7-9a2e63b39fdb.png)

**Comment by weshaggard** [comment]
I think that happens when there is a conflict. @mellinoe looked into some of these in the past. Which project are you looking at?

**Comment by ericstj** [comment]
System.Security.Cryptography.X509Certificates

**Comment by mellinoe** [comment]
https://github.com/dotnet/corefx/issues/5042

This happens with all ItemGroups that you define in the project file, i believe. If VS doesn't understand them, it shows this warning icon, it seems.

**Comment by ericstj** [comment]
Closing since this is a duplicate.
