### ISSUE TITLE
Break dependency on older collections in System.Net.Security

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#6725]
ReadOnlyCollectionBase
https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/src/System/Security/Authentication/ExtendedProtection/ServiceNameCollection.cs#L12

In the contract it is only ICollection and IEnumerable so we should try to make the implementation more closely match.

ArrayList
https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/src/System/Security/Authentication/ExtendedProtection/ServiceNameCollection.cs#L30

Hashtable
https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/src/System/Net/SslSessionsCache.cs#L15

cc @davidsh @CIPop 

@justinvp you broke some similar dependencies in other networking APIs are you interested in tackling this one?

**Comment by justinvp** [comment]
Sure, I'll take a look.

**Comment by justinvp** [comment]
FYI, I'm about 95% complete with this, including new test coverage for `ServiceNameCollection`. I was planning to submit a PR yesterday, but had to react to another issue and probably won't be able to get back to it until Sunday or Monday.
