### ISSUE TITLE
Break dependency on older collections in System.Net.WebHeaderCollection

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#6726]
System.Net.WebHeaderCollection pulls in System.Collections.Specialized which pulls in System.Collections.NonGeneric which we are trying to break dependencies on. We should see if we can break the below dependency in a reasonable way. 

NameValueCollection
https://github.com/dotnet/corefx/blob/master/src/System.Net.WebHeaderCollection/src/System/Net/WebHeaderCollection.cs#L33

cc @davidsh @CIPop

**Comment by justinvp** [comment]
I went ahead and grabbed this. #6952.
