### ISSUE TITLE
HttpClientHandler does not store HttpOnly cookies by default

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/corefx#6728]
In testing for ASP.NET, we found a curious behavior in System.Net.HttpClientHandler. This handler is not storing HttpOnly cookies in the cookie collection it creates. Should it store HttpOnly cookies by default as well?

It appears this issue has a history. The comment in code (see [HttpClientHandler.cs 462-473)](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/netcore50/System/Net/HttpClientHandler.cs#L462-L473) explains the history of this quirk. Before you could turn off lower-level cookie handling in WinRT (before [HttpBaseProtocolFilter.CookieUsageBehavior](https://msdn.microsoft.com/en-us/library/windows/apps/windows.web.http.filters.httpbaseprotocolfilter.cookieusagebehavior.aspx)), storing httponly cookies could cause issues. But this clearly does not apply to all platforms (e.g. Linux).

To play with the issue, see this example app: https://gist.github.com/natemcmaster/e51aa33cf77416772afc This creates a simple server that response with 2 cookies, on HttpOnly and the other not. HttpClientHandler only stores the HttpOnly=false cookie.

**Comment by davidsh** [comment]
@natemcmaster The code you are referencing is for NETCORE50 target (UWP).  This code is not used for ASP.NET scenarios.

So, are you reporting a bug for ASP.NET scenario or UWP scenario?  The code and binaries are different.

**Comment by natemcmaster** [comment]
Investigated further. This was a bug in our app code, not corefx.
