### ISSUE TITLE
Http/WebSocket stacks: Support further limiting of SSL protocols

### ISSUE THREAD

**Issue by yishaigalatzer** [dotnet/corefx#6729]
As noted in https://github.com/dotnet/corefx/issues/6668 & https://github.com/NuGet/Home/issues/390

The framwork is currently limiting SSL protocols, but customers might choose to be more restrictive, there is currently no way to specify it in code, and perhaps alternatively in an external configuration (local or machine level).

**Comment by stephentoub** [comment]
cc: @davidsh, @cipop, @SidharthNabar

**Comment by davidsh** [comment]
There are no plans to change the default protocols from the Tls10 | Tls1 | Tls12 list. That list is the same as .NET Framework.

Devs that need a different set can specify the allowed set of protocols in various SslStream APIs. For HTTP, only the lower level WinHttpHandler (as opposed to HttpClientHandler) has a property for this. Future revisions of the System.Net.Http contract could potentially include this as well.

**Comment by yishaigalatzer** [comment]
The ask is not to change default behaviors, rather allow for something a la ServicePointerManager to override the default behaviors (it is given of course that it shouldn't be ServicePointManager).

Second - I've opened this for discussion, so lets have a discussion before punting...

**Comment by jasonwilliams200OK** [comment]
@yishaigalatzer, just out of curiosity, wouldn't it make sense to rather convince the consumers to avoid SSLv[2/3] due to the security hole:

https://securityblog.redhat.com/2016/03/01/go-home-sslv2-youre-drowning/

As an average consumer, I would take it as a wisest advise. :)

**Comment by yishaigalatzer** [comment]
@jasonwilliams200OK I completely agree with your statement, this is about going to opposite direction (for example a customer requiring TLS 1.2 only)

**Comment by snboisen** [comment]
Instead of making the same mistake as in the ServicePointManager API, it would make a lot of sense, if the new API allowed the developer to specify "use this protocol version or newer".
Right now a lot of code is probably locked down to use Tls12 specifically. When a vulnerability is discovered and a new version emerges, all that code will need to be updated and recompiled instead of at least defaulting to the newest protocol version.

**Comment by CIPop** [comment]
> use this protocol version or newer

+1  @himadrisarkar @davidsh This is an interesting idea and would require new API.

**Comment by karelz** [comment]
Triage: We need formal API proposal

**Comment by davidsh** [comment]
>Instead of making the same mistake as in the ServicePointManager API, it would make a lot of sense, if the new API allowed the developer to specify "use this protocol version or newer".

In the current .NET Core 2.0/2.1 and .NET Framework (4.7+), the default TLS protocol is no longer a fixed set of versions (i.e. it is no longer "Tls10 | Tls11 | Tls12"). Instead, the default is now [SystemDefault](https://docs.microsoft.com/en-us/dotnet/api/system.net.securityprotocoltype?view=netcore-2.0#System_Net_SecurityProtocolType_SystemDefault) which will always use the best set of TLS protocols versions.  This list will change over time as new versions of the OS platforms evolve.  The default list will drop off insecure protocols (such as Ssl30) and add newer, stronger, protocols such as Tls13.

In addition, there is already a property on the Http stack, [HttpClientHandler.SslProtocols](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.sslprotocols?view=netcore-2.0#System_Net_Http_HttpClientHandler_SslProtocols), that can further customize the allowed TLS protocols that might be required.

Based on these updates to .NET Core over the last few years, this issue can be closed now.
