### ISSUE TITLE
ChangedTests.FileSystemWatcher_Changed_PreSeededNestedStructure(includeSubdirectories: False)  fails on windows

### ISSUE THREAD

**Issue by sokket** [dotnet/corefx#6732]
The ChangedTests.FileSystemWatcher_Changed_PreSeededNestedStructure(includeSubdirectories: False) test failed on Windows with System.UnauthorizedAccessException.

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_release_prtest/3194/testReport/junit/(root)/ChangedTests/FileSystemWatcher_Changed_PreSeededNestedStructure_includeSubdirectories__False_/

**Comment by jasonwilliams200OK** [comment]
Should we have something like a `BeforeFilter_EnsureNotExists()` before this line https://github.com/dotnet/corefx/blob/279390c/src/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.Changed.cs#L155, in which we delete-if-exists.

Alternatively, we can add a condition `if(Directory.Exists(path))` which wraps just around this line: https://github.com/dotnet/corefx/blob/ac67ffa/src/System.IO.FileSystem.Watcher/tests/Utility/TemporaryTestDirectory.cs#L12? :)
