### ISSUE TITLE
System.Data.SqlClient reference assembly surface area doesn't match impl

### ISSUE THREAD

**Issue by chcosta** [dotnet/corefx#6734]
When compiling our tests against the System.Data.SqlClient reference assembly, instead of the Windows implementation assembly, there are compilation issues...

                   "E:\gh\chcosta\corefx\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj" (BuildAndTest target) (78) ->
                   (CoreCompile target) -> 
                     SqlBulkCopyColumnMappingCollectionTest.cs(78,62): error CS0021: Cannot apply indexing with [] to an expression of type 'SqlBulkCopyColumnMappingCollection' [E:\gh\chcosta\corefx\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]
                     SqlBulkCopyColumnMappingCollectionTest.cs(79,62): error CS0021: Cannot apply indexing with [] to an expression of type 'SqlBulkCopyColumnMappingCollection' [E:\gh\chcosta\corefx\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]
                     SqlBulkCopyColumnMappingCollectionTest.cs(102,32): error CS0021: Cannot apply indexing with [] to an expression of type 'SqlBulkCopyColumnMappingCollection' [E:\gh\chcosta\corefx\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]
                     SqlBulkCopyColumnMappingCollectionTest.cs(105,32): error CS0021: Cannot apply indexing with [] to an expression of type 'SqlBulkCopyColumnMappingCollection' [E:\gh\chcosta\corefx\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]
                     SqlBulkCopyColumnMappingCollectionTest.cs(232,56): error CS0021: Cannot apply indexing with [] to an expression of type 'SqlBulkCopyColumnMappingCollection' [E:\gh\chcosta\corefx\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]
                     SqlBulkCopyColumnMappingCollectionTest.cs(325,32): error CS0021: Cannot apply indexing with [] to an expression of type 'SqlBulkCopyColumnMappingCollection' [E:\gh\chcosta\corefx\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]
                     SqlBulkCopyColumnMappingCollectionTest.cs(326,32): error CS0021: Cannot apply indexing with [] to an expression of type 'SqlBulkCopyColumnMappingCollection' [E:\gh\chcosta\corefx\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]
                     SqlBulkCopyColumnMappingCollectionTest.cs(327,32): error CS0021: Cannot apply indexing with [] to an expression of type 'SqlBulkCopyColumnMappingCollection' [E:\gh\chcosta\corefx\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]
                     SqlBulkCopyColumnMappingCollectionTest.cs(372,32): error CS0021: Cannot apply indexing with [] to an expression of type 'SqlBulkCopyColumnMappingCollection' [E:\gh\chcosta\corefx\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]
                     SqlBulkCopyColumnMappingCollectionTest.cs(373,32): error CS0021: Cannot apply indexing with [] to an expression of type 'SqlBulkCopyColumnMappingCollection' [E:\gh\chcosta\corefx\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]
                     SqlBulkCopyColumnMappingCollectionTest.cs(374,32): error CS0021: Cannot apply indexing with [] to an expression of type 'SqlBulkCopyColumnMappingCollection' [E:\gh\chcosta\corefx\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]
                     SqlBulkCopyColumnMappingCollectionTest.cs(390,32): error CS0021: Cannot apply indexing with [] to an expression of type 'SqlBulkCopyColumnMappingCollection' [E:\gh\chcosta\corefx\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]
                     SqlBulkCopyColumnMappingCollectionTest.cs(391,32): error CS0021: Cannot apply indexing with [] to an expression of type 'SqlBulkCopyColumnMappingCollection' [E:\gh\chcosta\corefx\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]
                     SqlBulkCopyColumnMappingCollectionTest.cs(392,32): error CS0021: Cannot apply indexing with [] to an expression of type 'SqlBulkCopyColumnMappingCollection' [E:\gh\chcosta\corefx\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]
                     SqlBulkCopyColumnMappingCollectionTest.cs(400,32): error CS0021: Cannot apply indexing with [] to an expression of type 'SqlBulkCopyColumnMappingCollection' [E:\gh\chcosta\corefx\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]
                     SqlBulkCopyColumnMappingCollectionTest.cs(401,32): error CS0021: Cannot apply indexing with [] to an expression of type 'SqlBulkCopyColumnMappingCollection' [E:\gh\chcosta\corefx\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]
                     SqlBulkCopyColumnMappingCollectionTest.cs(405,32): error CS0021: Cannot apply indexing with [] to an expression of type 'SqlBulkCopyColumnMappingCollection' [E:\gh\chcosta\corefx\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]
                     SqlBulkCopyColumnMappingCollectionTest.cs(406,32): error CS0021: Cannot apply indexing with [] to an expression of type 'SqlBulkCopyColumnMappingCollection' [E:\gh\chcosta\corefx\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]
                     SqlBulkCopyColumnMappingCollectionTest.cs(407,32): error CS0021: Cannot apply indexing with [] to an expression of type 'SqlBulkCopyColumnMappingCollection' [E:\gh\chcosta\corefx\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]
                     SqlBulkCopyColumnMappingCollectionTest.cs(450,32): error CS0021: Cannot apply indexing with [] to an expression of type 'SqlBulkCopyColumnMappingCollection' [E:\gh\chcosta\corefx\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]
                     SqlBulkCopyColumnMappingCollectionTest.cs(487,32): error CS0021: Cannot apply indexing with [] to an expression of type 'SqlBulkCopyColumnMappingCollection' [E:\gh\chcosta\corefx\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]
                     SqlBulkCopyColumnMappingCollectionTest.cs(488,32): error CS0021: Cannot apply indexing with [] to an expression of type 'SqlBulkCopyColumnMappingCollection' [E:\gh\chcosta\corefx\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]
                     SqlBulkCopyColumnMappingCollectionTest.cs(492,32): error CS0021: Cannot apply indexing with [] to an expression of type 'SqlBulkCopyColumnMappingCollection' [E:\gh\chcosta\corefx\src\System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj]

You can repro this by compiling System.Data.SqlClient\tests\FunctionalTests\System.Data.SqlClient.Tests.csproj and exchanging the reference to System.Data.SqlClient.dll, with a reference to the reference assembly.

This blocks our ability to compile our tests against current packages.

 /cc @ericstj @karajas

**Comment by saurabh500** [comment]
@chcosta  For a repro, I removed the reference to the SqlClient.csproj from the test project's csproj file and added a dependency on SqlClient using the project.json

The project.json is pointing to 23901 build which may not have the changes made by @justinvp in https://github.com/dotnet/corefx/pull/6527 
The timestamp of the ref dll shows that that it was created on 2/29

I merged the changes to the ref assemblies in the PR  6 days ago on 3/1 

A newer nightly build of .Net core should have the reference and the implementation assemblies in sync.

Let me know if I am missing anything here in terms of the steps for reproducing this issue?

**Comment by chcosta** [comment]
Did you try your repro steps against the 23907 packages?  I'd expect those to have justinvp's changes included.

**Comment by saurabh500** [comment]
@chcosta I tried with 23907 as well.
The references need to be updated with the indexer which was missing. I am submitting a PR to fix this.
