### ISSUE TITLE
ProtectedData usage

### ISSUE THREAD

**Issue by rolfik** [dotnet/corefx#6746]
How can I use ProtectedData from
https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.ProtectedData/ref/System.Security.Cryptography.ProtectedData.cs?
I see no nuget package available or is it?

Thank You

**Comment by lextm** [comment]
http://packagesearch.azurewebsites.net/ gives Microsoft.Dnx.Tooling

**Comment by bartonjs** [comment]
@rolfik It's not currently possible; that got ported to git as a prototype proposal.

Since there are scenarios for it, it will likely appear at some point... but as an FYI those are exposing Windows-specific API, and the use of that future package will restrict your project to Windows-only.

**Comment by rolfik** [comment]
@lextm Yes, thank You. But DNX is going to be dotnet so it should be at the namespace I have posted above.
@bartonjs Maybe there could be multiplatform alternative. Something like Data protection in Asp.net Core. Or something unified across Asp.net and .net Core.

**Comment by bartonjs** [comment]
@rolfik I agree that a multi-platform data protection solution could be built; but since the ProtectedData class is just providing a thin wrapper over Windows DPAPI it would be misleading to have an implementation of that class on other platforms that did not behave the same way DPAPI does.

**Comment by joshfree** [comment]
@chcosta can you review the packaging work for System.Security.Cryptography.ProtectedData in RC3?  This is a windows-only library

**Comment by ericstj** [comment]
We have a package https://dotnet.myget.org/F/dotnet-core/api/v2/package/System.Security.Cryptography.ProtectedData/4.0.0-rc3-24022-00 and it has a dummy impl on Unix that just throws PlatformNotSupported.  You should be able to use this package and get an impl on Windows, on Unix you'll have to catch the PNS exception and gracefully degrade.

**Comment by rrelyea** [comment]
is there an issue tracking providing support for encryption on non-windows platforms? thx -nuget team

**Comment by mountgellert** [comment]
@ericstj, @rrelyea, any update on this item?

**Comment by jnm2** [comment]
@karelz Is there a way for be to check whether platform differences like this are already documented in terrajobst/platform-compat?

**Comment by karelz** [comment]
Only search on GH / of the entries. Some entries are collected also in: https://github.com/dotnet/corefx/wiki/ApiCompat

We will do a proper larger sweep post 5/10 across all repo.

**Comment by karelz** [comment]
But if you know about some incompatibilities, it is better to add them into wiki/tool right now (e.g. as a placeholder with TODOs), rather than risking we could miss them later ...

**Comment by psmulovics** [comment]
Any news on this item? This would be needed for encrypted password storage for the nuget client.

**Comment by SteveL-MSFT** [comment]
We also need this for PowerShell https://github.com/PowerShell/PowerShell/issues/1654
