### ISSUE TITLE
ImmutableArray should come with a Count property

### ISSUE THREAD

**Issue by gregsn** [dotnet/corefx#6752]
When refactoring code it is not uncommon that you need to change types, e.g. ImmutableArray<X> to IReadOnlyList<X> due to its covariance. 

While it is common that certain members are not available in a supertype it certainly feels very strange that a property just get's renamed without any semantic change.

You argued: "We’ve decided to go with having a Length property instead of Count because we see ImmutableArray<T> as a replacement for regular arrays. This makes it easier to port existing code. It also makes the design a bit more self-contained."

But since most other collections besides the array come with a Count property, the chances are very hight that with using the Length property you keep on switching between those properties on every larger refactoring.

It would be nice if you could just add the Count property if possible. By that users that more likely switch between covariant access and direct access to the immutable array (instead of switching between mutable and immutable) can just stick with a property that doesn't break code.

**Comment by gregsn** [comment]
Adding Count to the mutable array aswell would allow users to think in one property, which in the long term might result in making the Length property less used and obsolete at some point.

**Comment by AArnott** [comment]
No strong objection here. But I'll be interested in feedback from others who were involved in the original decision including @terrajobst, @davkean, @nguerrera.

**Comment by nguerrera** [comment]
I've always hated that arrays use a different spelling for the number of items from collections. Nevertheless, I'm still a bit reluctant to have duplicate members.  I'm prepared to accept what the greater API review folks decide here.

**Comment by stephentoub** [comment]
I'd have preferred if it was ```Count``` to begin with, but as it already has a ```Length```, I'd prefer for it to not also have a ```Count```.  Otherwise, I'm forced to assume that there's a meaningful difference between the two, spend time trying to choose between them, etc., when in reality they're identical in meaning.

**Comment by AArnott** [comment]
I'm leaning against having duplicate members as well.
FWIW, if an `ImmutableArray<T>` and `ImmutableList<T>` were ever interchangeable (because folks were using their common interfaces), Count is already available on both.

**Comment by AArnott** [comment]
It sounds like the majority agree this might have been a good idea for the initial public API, but that adding a redundant property to the API at this point risks doing more harm than good.
Closing as Won't Fix.

**Comment by terrajobst** [comment]
On top of the concerns raised, it would also complicate optimization passes that look for certain code patterns in order to remove redundant bounds checking. It's not impossible, but something we should keep in mind when it comes up again.
