### ISSUE TITLE
Enable Ready2Run version of Microsoft.NETCore.App packages

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/corefx#6753]
Packages comprising NEtCore.App meta package must have their assemblies compiled as R2R images prior to packaging.

CC @davidfowl @weshaggard @piotrpMSFT @JohnChen0 @jkotas

**Comment by mellinoe** [comment]
Does this mean we need to crossgen all of the framework assemblies before zipping them into NuGet packages, or is this just referring to the shared framework "installer packaging" ?

**Comment by weshaggard** [comment]
They will not be crossgen'ed before going into the nuget packages (except for mscorlib). This is only going to be happening as a part of the step of building the shared framework. The meta-package is "Microsoft.NETCore.App".

**Comment by mellinoe** [comment]
Okay, thanks for clarifying. That was my initial assumption, but since this was filed in corefx I second-guessed that and thought we wanted to cross-gen the packages in this repo. We may want to move this over to CLI in that case.
