### ISSUE TITLE
Fork project.jsons for windows-only dependencies

### ISSUE THREAD

**Issue by dagood** [dotnet/corefx#6760]
@Priya91 pointed out some restore errors to me on Ubuntu that seem to be because of auto-RID:

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_ubuntu14.04_debug/23/consoleText

	EXEC : error : Microsoft.Win32.Registry 4.0.0-rc3-23908 provides a compile-time reference assembly for Microsoft.Win32.Registry on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/mnt/j/workspace/dotnet_corefx/outerloop_ubuntu14.04_debug/build.proj]
	EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.14.04-x64). [/mnt/j/workspace/dotnet_corefx/outerloop_ubuntu14.04_debug/build.proj]
	EXEC : error : System.Security.AccessControl 4.0.0-rc3-23908 provides a compile-time reference assembly for System.Security.AccessControl on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/mnt/j/workspace/dotnet_corefx/outerloop_ubuntu14.04_debug/build.proj]
	EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.14.04-x64). [/mnt/j/workspace/dotnet_corefx/outerloop_ubuntu14.04_debug/build.proj]
	EXEC : error : System.Threading.Overlapped 4.0.1-rc3-23908 provides a compile-time reference assembly for System.Threading.Overlapped on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/mnt/j/workspace/dotnet_corefx/outerloop_ubuntu14.04_debug/build.proj]
	EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.14.04-x64). [/mnt/j/workspace/dotnet_corefx/outerloop_ubuntu14.04_debug/build.proj]
	...

It looks like these stopped working after upgrading from `23829` because no `dnxcore50` implementation is provided anymore.

It seems to me that the right temporary fix is to fork any `project.json` using these dependencies. I can do this if it sounds right. I'm not sure how to see which configurations a project uses a dependency in except by compiling it.

The long-term fix is to take up a version of CLI/nuget that got rid of auto-RID. (We can get rid of our RID-specific forks then too.)

@ericstj Thoughts? Should this be happening?

/cc @weshaggard

**Comment by dagood** [comment]
Note on the long-term: I looked through the events that happened around auto-RID recently, and it turns out that there isn't a CLI version we can take up to get rid of auto-RID. (It was added back to https://github.com/NuGet/NuGet.Client/blob/abf9390/src/NuGet.Core/NuGet.CommandLine.XPlat/RestoreCommand.cs#L98-L101.)

**Comment by ericstj** [comment]
> It looks like these stopped working after upgrading from 23829 because no dnxcore50 implementation is provided anymore.

We fixed the packages to correctly make the implementations RID-specific.

>right temporary fix is to fork any project.json using these dependencies

Rather than fork can we just make them RID-specific with Windows RID?  Any project that uses these packages should only ever run on Windows.  Also I don't see this as temporary, its just recording that certain projects are RID-specific, which is consistent with how those projects should be packaged.

**Comment by dagood** [comment]
Ok, that makes sense. I see now that I can go into the .builds projects to see where they're supposed to be supported.

> Rather than fork can we just make them RID-specific with Windows RID?

Is that true for `System.IO.FileSystem`? I do see that many of these (especially test projects) are windows-only though, so on those I can simply add the RID.

**Comment by dagood** [comment]
Attaching the list of restore errors (from a verbose restore) for context: [errs.txt](https://github.com/dotnet/corefx/files/164232/errs.txt)

**Comment by leemgs** [comment]
I have also got the same error messages like @dagood.  

### Build environment: 
```
1. Build environment:
- Build PC: Intel i5 CPU (quad core) , MEM 8GiB
- Build OS: Ubuntu 14.04 X86 64bit
- Memory: DDR3 8GiB
- build command: 
  u14.04$> cd ./corefx 
  u14.04$>time  ./build.sh managed debug clean 
```

### Error messages:

```
geunsik@DXL-Workstation:~/dotnet/corefx$ time  ./build.sh managed debug clean
Setting up directories for build
Restoring NuGet.exe...
Installing dotnet cli...
Restoring BuildTools version 1.0.25-prerelease-00193...
Initializing BuildTools...
Done initializing tools.
  [20:16:26.21] Restoring all packages...
EXEC : error : System.Threading.Overlapped 4.0.1-rc3-23908 provides a compile-time reference assembly for System.Threading.Overlapped on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.14.04-x64). [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : System.Threading.Overlapped 4.0.1-rc3-23908 provides a compile-time reference assembly for System.Threading.Overlapped on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.14.04-x64). [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : System.Threading.Overlapped 4.0.1-rc3-23908 provides a compile-time reference assembly for System.Threading.Overlapped on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.14.04-x64). [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : System.Threading.Overlapped 4.0.1-rc3-23908 provides a compile-time reference assembly for System.Threading.Overlapped on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.14.04-x64). [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : System.Threading.Overlapped 4.0.1-rc3-23908 provides a compile-time reference assembly for System.Threading.Overlapped on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.14.04-x64). [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : Microsoft.Win32.Registry 4.0.0-rc3-23908 provides a compile-time reference assembly for Microsoft.Win32.Registry on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.14.04-x64). [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : System.Threading.Overlapped 4.0.1-rc3-23908 provides a compile-time reference assembly for System.Threading.Overlapped on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.14.04-x64). [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : System.Security.AccessControl 4.0.0-rc3-23908 provides a compile-time reference assembly for System.Security.AccessControl on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.14.04-x64). [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : System.Security.AccessControl 4.0.0-rc3-23908 provides a compile-time reference assembly for System.Security.AccessControl on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.14.04-x64). [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : Microsoft.Win32.Registry 4.0.0-rc3-23908 provides a compile-time reference assembly for Microsoft.Win32.Registry on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : System.Security.AccessControl 4.0.0-rc3-23908 provides a compile-time reference assembly for System.Security.AccessControl on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.14.04-x64). [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : Microsoft.Win32.Registry 4.0.0-rc3-23908 provides a compile-time reference assembly for Microsoft.Win32.Registry on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : System.Security.AccessControl 4.0.0-rc3-23908 provides a compile-time reference assembly for System.Security.AccessControl on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.14.04-x64). [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : Microsoft.Win32.Registry 4.0.0-rc3-23908 provides a compile-time reference assembly for Microsoft.Win32.Registry on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.14.04-x64). [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : Microsoft.Win32.Registry 4.0.0-rc3-23908 provides a compile-time reference assembly for Microsoft.Win32.Registry on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.14.04-x64). [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : System.Runtime 4.0.0 provides a compile-time reference assembly for System.Runtime on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : System.Reflection 4.0.0 provides a compile-time reference assembly for System.Reflection on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : System.IO 4.0.0 provides a compile-time reference assembly for System.IO on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : System.Text.Encoding 4.0.0 provides a compile-time reference assembly for System.Text.Encoding on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : System.Threading.Tasks 4.0.0 provides a compile-time reference assembly for System.Threading.Tasks on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/home/geunsik/dotnet/corefx/build.proj]
EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.14.04-x64). [/home/geunsik/dotnet/corefx/build.proj]
/home/geunsik/dotnet/corefx/build.proj(54,5): error MSB3073: The command ""/home/geunsik/dotnet/corefx/Tools/dotnetcli/bin/dotnet" restore --packages "/home/geunsik/dotnet/corefx/packages" --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://www.nuget.org/api/v2/ "/home/geunsik/dotnet/corefx/src" "/home/geunsik/dotnet/corefx/pkg"" exited with code -1.
  [20:17:34.66] Restoring all packages...Done.
                    . . . .  BELOW OMISSION . . . . 
```

**Comment by ericstj** [comment]
Thanks Davis.

I went through the list and made notes.  https://gist.github.com/ericstj/2fcd556831f590c41f7e

I've started making some of the changes but don't have a good way to test them do you think you can help?

**Comment by dagood** [comment]
@ericstj Thanks, yes, I can repro these errors on my OSX machine so I could test them there. I actually made a few changes too yesterday before I had to go: https://github.com/dagood/corefx/tree/add-rid-to-winonly. Let me know where you're making the changes and I can fetch and test them out.

**Comment by dagood** [comment]
@leemgs Auto-RID is a NuGet feature also known as "RID inference". I can't find a better link to explain it than to the source code: https://github.com/NuGet/NuGet.Client/blob/abf9390/src/NuGet.Core/NuGet.CommandLine.XPlat/RestoreCommand.cs#L98-L101. You could try searching "RID inference" in NuGet/Home and dotnet/CLI to see the discussion that has been happening. Basically though, NuGet provides fallback RIDs based on the current OS, but some of our project.jsons don't support all OSes, so we have to specify those RIDs manually in the project.json.

As for why CI didn't catch this on the first occurrence, I don't know. Any number of restore errors should fail the build. I'll look through CI to try to figure out what happened, but right now first priority is fixing it.

**Comment by ericstj** [comment]
Here's my branch: https://github.com/ericstj/corefx/commit/0bc8077c56551e0fb52b5ea771f185496e91f5af

**Comment by dagood** [comment]
Cool, it restores correctly but I get build errors on OpenSourceSign:

> /Users/dagood/git/corefx/Tools/sign.targets(41,5): error : /Users/dagood/git/corefx/bin/obj/ref/System.Diagnostics.StackTrace/4.0.1.0/System.Diagnostics.StackTrace.dll: I/O error reading or writing PE file: Could not find file '/Users/dagood/git/corefx/bin/obj/ref/System.Diagnostics.StackTrace/4.0.1.0/System.Diagnostics.StackTrace.dll'. [/Users/dagood/git/corefx/src/System.Diagnostics.StackTrace/ref/System.Diagnostics.StackTrace.csproj]

I'm not sure yet if I get it without your changes though--it might be an environment error.

**Comment by ericstj** [comment]
Shouldn't be caused by my changes.  Are you still seeing this with a clean build?

**Comment by dagood** [comment]
Yeah, and I cleared the cache and user-level package dirs. It doesn't happen on commits before this problem started happening, but there have been other changes since then. Trying on my ubuntu VM as soon as I can get that online--it should repro this problem and might have a cleaner environment.

**Comment by ericstj** [comment]
I've noticed recent changes that enabled the shared compiler service, at least on windows.  I wonder if that is causing this?  /cc @joperezr @weshaggard

**Comment by dagood** [comment]
Moving back to buildtools `1.0.25-prerelease-00188` makes the issue go away on OSX, still waiting on restore on Ubuntu.

**Comment by dagood** [comment]
Confirmed that the same issue happens on Ubuntu using your commit without changing buildtools.

**Comment by dagood** [comment]
Looks like `00192` doesn't hit that error either. I'm guessing the updateBaseline changes didn't affect this, so it must be the upgrade of `Microsoft.NETCore.Runtime` to a new version (that actually exists). Don't know what to make of that.

**Comment by ericstj** [comment]
Regression in the runtime on Unix?  If you change tool-runtime back to an older version does the problem go away?

**Comment by ericstj** [comment]
I looked at this with @mellinoe the problem has to do with System.Reflection.Metadata.  The version of roslyn we're using depends on surface area that was removed from System.Reflection.Metadata 1.2.  This change https://github.com/dotnet/corefx/commit/7152971f4a940aa897c29fcdbed8934a692a928e moved a bunch of types that were public to private in 1.2.  We need to update the version of SRM we are using in tool-runtime to 1.3.

**Comment by dagood** [comment]
That makes sense @ericstj, thanks! Are you fixing this or should I go ahead and add a root-level dependency to tool-runtime/project.json that upgrades S.R.M?

**Comment by ericstj** [comment]
Yeah, I'm fixing it.

**Comment by ericstj** [comment]
https://github.com/dotnet/buildtools/pull/525

**Comment by leemgs** [comment]
> As for why CI didn't catch this on the first occurrence, I don't know. Any number of restore errors 
> should fail the build. I'll look through CI to try to figure out what happened, 
> but right now first priority is fixing it.

@dagood, @stephentoub , the package restore error still happens on my ubuntu 14.04 x86 64bit pc even though I have moved to latest commit number 3148d50e824ac322838dffa437c7d15ad6d904c3 (Mar-9-2016). Actually, it seems that the error happens when the prerelease specifier (e.g. 4.0.0-rc3-23901) was updated. Who can fix this issue as a urgent task?
