### ISSUE TITLE
[corert] Define and implement Marshal.GetLastWin32Error for Linux systems

### ISSUE THREAD

**Issue by tarekgh** [dotnet/corefx#6778]
System.Private.Uri is using Marshal.GetLastWin32Error, when compiling it as aot (corert netstandard13aot) for Linux it complain about Marshal.GetLastWin32Error is not implemented. Temporary we are providing empty stub to work around the issue but we need a permanent solution either get it implemented in Linux or kill the dependency on that API in Linux code

**Comment by stephentoub** [comment]
@tarekgh, this is specific to corert, correct?  Marshal.GetLastWin32Error() is implemented and is heavily relied upon in all of our corefx components on Linux running with libcoreclr:
https://github.com/dotnet/corefx/blob/master/src/Common/src/Interop/Unix/Interop.Errors.cs#L151-L161

**Comment by tarekgh** [comment]
Yes it is specific for corert case. for coreclr Marshal.GetLastWin32Error is implemented in mscorlib (actually mscorlib just calling the VM for that). in corert we don't have this implementation. also according to Tijoy, the tests of Marshal.GetLastWin32Error are failing when running on Linux (even for coreclr).

**Comment by stephentoub** [comment]
> also according to Tijoy, the tests of Marshal.GetLastWin32Error are failing when running on Linux (even for coreclr)

What are the failures?  It's been working reliably, and it's used extensively throughout corefx via that Interop.Errors.cs file I liked to.  Note that there were some behavior changes made to it a while back (https://github.com/dotnet/coreclr/pull/614), or more specifically to the behavior of SetLastError, which it obviously relates to.  Depending on what the test failures are, maybe that's related.

**Comment by tarekgh** [comment]
the failing test that @tijoytom mentioned to me was CoreMangLib/cti/system/runtime/interopservices/marshal/MarshalGetLastWin32Error_PSC/MarshalGetLastWin32Error_PSC.sh 

I didn't look at the failure but @tijoytom mentioned the failure is Linux only. maybe it is a test issue and not a product issue. anyway @tijoytom can have more info here and should be following up.

**Comment by stephentoub** [comment]
Ok.  Thanks.  I tried to look, but I don't even see that test here:
https://github.com/dotnet/coreclr/tree/master/tests/src/CoreMangLib/cti/system/runtime/interopservices/marshal
even though I see it mentioned here:
https://github.com/dotnet/coreclr/blob/fa7e809b17530818975b7c2212f241c1f91d0fe4/tests/testsFailingOutsideWindows.txt#L3

**Comment by jkotas** [comment]
I think the best way to fix this is to introduce LowLevelMarshal in System.Private.CoreLib.dll and just call it from here.

**Comment by tmds** [comment]
I was trying to figure out what DllImport.SetLastError means on linux when I found this issue. I guess it means Marshal.GetLastWin32Error will return errno?

**Comment by stephentoub** [comment]
> I guess it means Marshal.GetLastWin32Error will return errno?

Yes

**Comment by danmosemsft** [comment]
@yizhang82 @tarekgh does this need to happen for UWP? If so please set milestone 2.1.

**Comment by tarekgh** [comment]
> does this need to happen for UWP? If so please set milestone 2.1

No this is corert specific and not UWP. This functionality already working in UWP.
