### ISSUE TITLE
Support incremental test runs

### ISSUE THREAD

**Issue by eatdrinksleepcode** [dotnet/corefx#678]
(This is really an issue in the Build Tools; however, the lack of activity around that project makes me wonder whether an issue submitted there would be noticed. So I am filing here for now. If it would be better to file it there I would be happy to do that.)

Executing a build twice in a row should ideally be as close to a no-op as possible. In CoreFX, unit tests are always executed during the second run, even when the both the main and test project have not changed. This could be fixed by specifying the correct Inputs and Outputs to the RunTests task. I would be happy to submit a PR with this change to the BuildTools project (although it is not clear whether BuildTools is taking contributions the same way CoreFX is.)

**Comment by weshaggard** [comment]
@eatdrinksleepcode Yes I think this is very annoying as well and I'm doing some looking into some of this. Please do feel free to submit PRs/Issues to the buildtools repo as well. I've been debating whether or not an incremental build should still run the tests. Right I think it should still run the tests but not do all the copying it is doing today. I'd be interested to know your thoughts.

**Comment by ellismg** [comment]
BuildTools is quieter because of its more focused nature, but we are definetly taking contributions there.  I think it makes sense to move this over there,.

**Comment by ellismg** [comment]
Closing in favor of the issue in buildtools.
