### ISSUE TITLE
Unable to find an entry point named 'GetMaxMdSize' on Linux

### ISSUE THREAD

**Issue by ProTip** [dotnet/corefx#6782]
I'm getting this error trying to use the AWS Dotnet SDKv3. This is on Ubuntu 14.04 with openssl 1.0.1f

```sh
$ openssl version
OpenSSL 1.0.1f 6 Jan 2014
```
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (The type initializer for 'Crypto' threw an exception.) ---> System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ---> System.EntryPointNotFoundException: Unable to find an entry point named 'GetMaxMdSize' in DLL 'System.Security.Cryptography.Native'.
   at Interop.Crypto.GetMaxMdSize()
   at Interop.Crypto..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto.EvpSha256()
```

```
   "dependencies": {
        "NETStandard.Library": "1.0.0-rc2-23901",
```

**Comment by stephentoub** [comment]
Where did you get your System.Security.Cryptography.Native.so and System.Security.Cryptography.Algorithms.dll from?  Did you build them yourself?  Or if you got them from packages, what versions?

The fact that it's looking for an entrypoint named ```GetMaxMdSize``` rather than one named ```CryptoNative_GetMaxMdSize``` means that at least the managed .dll is fairly old.  My guess is that there's a mismatch, and that the .dll is relatively old (and is looking for the name without the prefix) whereas the .so is much newer and contains the change to export the name with the CryptoNative_ prefix.

**Comment by ProTip** [comment]
I think the dotnet CLI? I installed it via the "Getting started" instructions for Ubuntu. I would have thought that something in the ```dotnet restore; dotnet run``` process would pull the necessary bits.

**Comment by stephentoub** [comment]
Which version of dotnet cli are you using?  @ellismg, I know there was an issue related to this... do you know the details, if it was fixed, what version one needs to get the fix, etc.?

**Comment by ellismg** [comment]
The fix was in `dotnet restore` itself.  What version of `dotnet` do you have?

**Comment by ProTip** [comment]
I was using ```dotnet=1.0.0.001598-1``` per the instructions. Then tried the latest ```1.0.0.001668-1```.

I also have dnx installed, but I'm not sure if that would be causing an issue? The state off the ecosystem is a bit confusing ATM.

**Comment by ellismg** [comment]
I believe the problem here is that we end up restoring an old version of the managed wrappers around our native shims because they have a more specific RID than the current version and NuGet prefers them.

If you could share out your project.json and project.lock.json either @ericstj or @bartonjs could figure out which Cryptography packages you need to explicitly list in your project.json to work around the issue.

**Comment by ProTip** [comment]
Still seeing this in ```1.0.0.001793-1```

**Comment by bartonjs** [comment]
The AWSSDK.Core library is referencing a 4 month old build of that package, which probably straddles the native target rename.  I'm not sure how we end up in a state where they mismatch, though.

I opened https://github.com/aws/aws-sdk-net/issues/329 to hopefully get the version reference bumped on the AWS package.

Hopefully just adding a dependency of `System.Security.Cryptography.Algorithms-4.1.0-rc2-23901` will solve your problems.

**Comment by ProTip** [comment]
I had a feeling it was targeting on old/wrong dll. Unfortunately my knowledge of how to inspect DLL's outside of VS/Xamarin and on Linux is.. Non-existent. I will try what you recommended and see if it works, thanks!

**Comment by bartonjs** [comment]
@ProTip The quick way is that `dotnet restore` yelled at me:

```
warn : Detected package downgrade: System.Security.Cryptography.Algorithms from 4.0.0-rc3-23720 to 4.0.0-beta-23516
warn :  repro (>= 1.0.0) ->
    AWSSDK.EC2 (>= 3.2.3-beta) ->
    AWSSDK.Core (>= 3.2.3-beta && < 3.3.0-beta) ->
    System.Net.Http (>= 4.0.1-rc3-23720) ->
    runtime.linux.System.Net.Http (>= 4.0.1-rc3-23720) ->
    System.Security.Cryptography.Algorithms (>= 4.0.0-rc3-23720)
warn :  repro (>= 1.0.0) ->
    AWSSDK.EC2 (>= 3.2.3-beta) ->
    AWSSDK.Core (>= 3.2.3-beta && < 3.3.0-beta) ->
    System.Security.Cryptography.Algorithms (>= 4.0.0-beta-23516)
```

In the event that you missed that warning (which is easy to miss if you're not looking for it), the way to find things like this is to open project.lock.json.

```json
{
  "locked": false,
  "version": 2,
  "targets": {
    ".NETStandardApp,Version=v1.5": {
      "AWSSDK.Core/3.2.3-beta": {
        "type": "package",
        "dependencies": {
          "Microsoft.CSharp": "4.0.0",
          "System.Collections": "4.0.10",
          "System.Collections.NonGeneric": "4.0.0",
          "System.Diagnostics.Tools": "4.0.0",
          "System.Linq": "4.0.0",
          "System.Net.Http": "4.0.0",
          "System.Runtime.Extensions": "4.0.10",
          "System.Security.Cryptography.Algorithms": "4.0.0-beta-23516",
          "...": "..."
        },
        "...": "..."
      },
      "...": "..."
    },
    "...": "..."
  },
  "...": "..."
}
```

It'll also tell us which version got bound in the end (library/version):

```
jbarton@jsb-ubuntu2:~/playground/repro$ grep  Algorithms/ project.lock.json
      "System.Security.Cryptography.Algorithms/4.0.0-beta-23516": {
```

But, the runtime.unix.System.Security.Algorithms 4.0.0-beta-23516 project doesn't have a reference to the old Native project (I think it actually predates it), so the native package that got bound is

```
jbarton@jsb-ubuntu2:~/playground/repro$ grep runtime.native.System.Security.Cryptography/ project.lock.json
      "runtime.native.System.Security.Cryptography/4.0.0-rc3-23720": {
```

Hence, old managed code with new native code :(.

**Comment by bartonjs** [comment]
@ProTip Somehow the magic on my test machine has interfered with normal execution.  Can you try adding an explicit dependency on `System.Security.Cryptography.Algorithms-4.1.0-rc2-23901` (where 23901 matches your NETStandard.Library reference version number) and see if that makes things better?  It'd be good to know if the workaround works while the package update is in a holding pattern.

**Comment by ProTip** [comment]
:beers:

**Comment by Inumedia** [comment]
I'm seeing this when trying to use the Aes implementation in Security.Crypto.Algorithms.

### Specs:
- Ubuntu 14.04.4 LTS
- openssl version: OpenSSL 1.0.1f 6 Jan 2014
- dotnet --version:
```
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  N/A

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 Runtime Id:  ubuntu.14.04-x64
```

### Exception:
```
System.EntryPointNotFoundException: Unable to find an entry point named 'GetMaxMdSize' in DLL 'System.Security.Cryptography.Native'.
   at Interop.Crypto.GetMaxMdSize()
   at Interop.Crypto..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto.GetRandomBytes(Byte[] buf, Int32 num)
   at System.Security.Cryptography.RNGCryptoServiceProvider.GetBytes(Byte[] data)
   at Internal.Cryptography.AesImplementation.GenerateIV()
   at System.Security.Cryptography.SymmetricAlgorithm.get_IV()
   at System.Security.Cryptography.SymmetricAlgorithm.CreateEncryptor()
   at (my code at this point)...
```
### Project.JSON:

```
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Newtonsoft.Json": "8.0.3",
    "System.Runtime.Serialization.Primitives" : "1.0.0-rc2-23811",
    "System.Dynamic.Runtime": "1.0.0-rc2-23811",
    "System.Xml.XDocument": "1.0.0-rc2-23811"
  },
  "frameworks": {
    "dnxcore45": {
      "dependencies": {
        "NETStandard.Library": "1.5.0-rc2-23811",
        "System.Security.Cryptography.Algorithms": "4.0.0-beta-23516",
        "System.Threading.Thread": "4.0.0-beta-23516",
        "System.Threading.ThreadPool": "4.0.10-beta-23516",
        "System.Reflection.TypeExtensions": "4.1.0-rc3-24012-00",
        "System.Diagnostics.Process": "4.1.0-rc2-23811"
      }
    },
    "dnxcore50": {
      "dependencies": {
        "NETStandard.Library": "1.5.0-rc2-23811",
        "System.Security.Cryptography.Algorithms": "4.0.0-beta-23516",
        "System.Threading.Thread": "4.0.0-beta-23516",
        "System.Threading.ThreadPool": "4.0.10-beta-23516",
        "System.Reflection.TypeExtensions": "4.1.0-rc3-24012-00",
        "System.Diagnostics.Process": "4.1.0-rc2-23811"
      }
    },
    "net45": {}
  },
  
  "contentFiles": [
    "run.sh",
    "EncryptionKey.txt"
  ]
}
```

The project.lock.json file can be found here: [project.lock.json](http://inumedia.io/project.lock.json)

At the time of execution on the Linux system, it's executing the framework `dnxcore50`

**Comment by Inumedia** [comment]
Never mind, looks like bartonjs's comment fixed my problem, sorry for commenting on an old thread 🙄

**Comment by bartonjs** [comment]
@Inumedia No worries, I was going to ask why you had explicit references to beta packages (RC1) when everything else was rc2 (or rc3).

**Comment by Inumedia** [comment]
Mostly just because they aren't showing up in the auto complete in vscode :P

**Comment by bartonjs** [comment]
@ProTip AWS's 3.2.4-beta build is built on top of RC2 (NETStandard.Library 1.5.0-rc2-24027); so hopefully you can use that combination without needing to use extra references.

Provided everything's happy with RC2, I think we can close the issue.

**Comment by bartonjs** [comment]
Since things seemed generally good at RC2, and we've now hit RTM, I'm going to close this.  If anything is still misbehaving please feel welcome to share.
