### ISSUE TITLE
Refactor build to run tests based on targets and dependencies rather than properties

### ISSUE THREAD

**Issue by eatdrinksleepcode** [dotnet/corefx#679]
The build system currently runs tests by setting the RunTestsForProject to execute after PrepareForRun. Because we don't want to run the tests after a Visual Studio build (because VS has its own mechanisms for running tests), since #508 the BuildingInsideVisualStudio property is used to disable the RunTestsForProject target.

Making the build system aware of the context in which its running in order to skip a target feels odd in a build system with a robust target and dependency mechanism. It seems to me that it would be more idiomatic for the build to expose its targets in such a way so that each context can use the target system to control what targets are run. In other words, do not include the RunTestsForProject in the dependency tree of the default target for the sub-project files (which is what Visual Studio will execute), but do include it in the dependency tree of the default target for the top-level build file.

In practice, I believe this would just mean changing the default target for each sub-project to be Compile instead of Build.

This would also have the positive effect of making the build IDE-agnostic, which is important as .NET Core becomes truly cross-platform. What would the value of the "BuildingInsideVisualStudio" property be from within Xamarin Studio, or SharpDevelop, or Sublime using [OmniSharp](http://www.omnisharp.net/)? Xamarin Studio actually sets BuildingInVisualStudio to true in order to try and increase compatibility, which is obviously not a desirable state of affairs. Let's try to reduce the need for such hacks by keeping the dependencies between the build and the IDE clean (i.e. one-way).

**Comment by weshaggard** [comment]
@eatdrinksleepcode while I somewhat understand your ask here I'm not sure I know how to address it. I want the tests to be able to run via the target where ever you build either the root build.proj or an individual test csproj file. So we there isn't an easy way to detect that you are on the command line or in VS outside of the "BuildingInsideVisualStudio" property. As of now we only have the two options inside and outside VS and that property gives us that pivot. Later if we want to do something unique for another IDE then we would need to have something that represents "BuildingInXamarinStudio" and similarly disable the target and setup whatever they need to run from the IDE. Thus for any IDE we don't have support for they would always get the tests run via the target.

Let me know what you had in mind or submit a PR for review and we can consider our options.

**Comment by eatdrinksleepcode** [comment]
My proposal is to change the default target of all projects to Compile. Since Visual Studio always runs the default target, it would only compile the code, not run tests. From the command line, just running "msbuild" would only compile, but running "msbuild /target:build" would compile and run tests. While this is slightly more verbose, I actually prefer to specify a target when I execute a build, and many build systems (e.g. Maven and Gradle) require it (though there are other systems such as Rake and Grunt which do allow a default).

As a better fix, I would like to see Visual Studio changed to either run a specific named target for Build (like it does for Rebuild and Clean), or even better allow the target to be configured. But in the meantime I think keeping the build system IDE-agnostic is worthwhile.

**Comment by weshaggard** [comment]
@eatdrinksleepcode I think that will likely cause all sorts of other issues. For better or worse there are lots of targets that chain themselves off of build target and so changing the default target to Compile will cause a fair amount inconsistency.

For reference see:
                   CoreBuildDependsOn = 
                         BuildOnlySettings;
                         PrepareForBuild;
                         PreBuildEvent;
                         ResolveReferences;
                         PrepareResources;
                         ResolveKeySource;
                         Compile;
                         ExportWindowsMDFile;
                         UnmanagedUnregistration;
                         GenerateSerializationAssemblies;
                         CreateSatelliteAssemblies;
                         GenerateManifests;
                         GetTargetPath;
                         PrepareForRun;
                         UnmanagedRegistration;
                         IncrementalClean;
                         PostBuildEvent

I'm not saying I know what all those targets do but I know if we stop doing those in VS builds we will likely run into problems and have inconsistent builds. Perhaps we could take a slight different approach is to introduce another target called BuildAndTest which when ran from the command line would run the tests as well as a separate step from the build. We could even set that as the default target in build.proj so that running build.cmd would still do what we want. I will think about this a little more.

@nguerrera what do you think about introducing a BuildAndTest target that would chain in the testing instead chaining in the Test run as part of Build and filtering based on running in VS?

**Comment by eatdrinksleepcode** [comment]
Indeed, the limited ability of declaring dependencies when MSBuild was first released resulted in the "standard" build resembling a Maven-esque linear lifecycle, with targets "hanging off" of particular steps and relying on previous steps having already been executed rather than explicitly declaring their own dependencies. Dependency declaration is much richer now, but the standard build structure has never changed, I presume for compatibility reasons. I have some ideas about possible improvements to that situation, but I am going to refrain from creating an issue about it until I have a more concrete recommendation.

In the meantime, your BuildAndTest solution in #783 achieves the same result, so we can consider that as a fix for this issue.

**Comment by weshaggard** [comment]
Addressed with #783.
