### ISSUE TITLE
What's the recommended alternative for Assembly.Location/CodeBase

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/corefx#6791]
With CoreCLR we lost the ability to have `Assembly.Location` and `Assembly.CodeBase`. What's the recommended alternative?

**Comment by stephentoub** [comment]
Assembly.Location exists:
https://github.com/dotnet/corefx/blob/master/src/System.Reflection/ref/System.Reflection.cs#L38
You may need to reference a newer contract version than you're using to get it.

**Comment by NTaylorMullen** [comment]
Ah, looks like the API was re-added in `System.Reflection 4.1.0-*`. Thanks @stephentoub!
