### ISSUE TITLE
API Proposal: A library solution to generic pointers

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#6795]
If #5474 is approved, we can implement a generic pointer like this independently of any compiler support:

```csharp
public unsafe struct Pointer<T>
{
    private readonly void* pointer;

    public Pointer(void* pointer)
    {
        this.pointer = pointer;
    }

    public T Value
    {
        get { return Unsafe.Read<T>(pointer); }
        set { Unsafe.Write(pointer, value); }
    }
}
```

Since `void*` is implicitly convertible from any pointer type, it would be easy for existing code to transition to the new API without any casting. For example, this:

```csharp
byte* pointer = stackalloc byte[10];
Foo(pointer);

unsafe void Foo(byte* pointer) { /*...*/ }
```

becomes this:

```csharp
byte* pointer = stackalloc byte[10];
var wrapped = new Pointer<byte>(pointer); // no casts needed here
Foo(wrapped);

void Foo(Pointer<byte> pointer) { /*...*/ }
```

This would also allow us to easily supplant `void*` in places where a generic API is needed (e.g. [`Span`](https://github.com/dotnet/corefxlab/blob/ebac409272f2de512967b7c89bb52c33066418ab/src/System.Slices/System/Span.cs#L112)) and allow us to use generic constraints/type inference with pointers.

**Comment by KrzysztofCwalina** [comment]
This is being actively worked on in https://github.com/dotnet/corefxlab/tree/master/src/System.Slices
See Span<T> and ReadOnlySpan<T>
