### ISSUE TITLE
Clean-up: Is "PortableNuGetMode" required in dir.targets

### ISSUE THREAD

**Issue by chcosta** [dotnet/corefx#6798]
https://github.com/dotnet/corefx/blob/master/dir.targets#L30

The question was raised in PR #6785, is PortableNuGetMode still required in dir.targets?  Investigate whether this has been added to buildtools (perhaps add it), and clean up this code.

**Comment by mellinoe** [comment]
This definitely still needs to be there, and it doesn't seem to be in buildtools. We can consider adding it there as long as it still functions the same way.

See Microsoft.Portable.Core.targets (`C:\Program Files (x86)\MSBuild\Microsoft\Portable\Microsoft.Portable.Core.targets`), line 22:
````XML
<Error Condition="'$(TargetFrameworkProfile)' == '' AND '$(PortableNuGetMode)' != 'true'" Text="The TargetFrameworkProfile property is not set for project '$(MSBuildProjectFile)'. Portable projects must specify a profile."/>
````

**Comment by ericstj** [comment]
Changing tags, this has nothing to do with packaging.  It's just a property we set to avoid an error when using the PCL targets.

**Comment by chcosta** [comment]
I don't believe this is a real issue.  We can re-open if I am mistaken.
