### ISSUE TITLE
OSX Outerloop Debug builds failing due to nuget restore error

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#6820]
```
20:26:03   [20:29:43.25] Restoring all packages...
20:26:36 EXEC : error : A local file header is corrupt. [/Users/dotnet-bot/j/workspace/dotnet_corefx/outerloop_osx_debug/build.proj]
20:26:37 
/Users/dotnet-bot/j/workspace/dotnet_corefx/outerloop_osx_debug/build.proj(54,5): error MSB3073: The command ""/Users/dotnet-bot/j/workspace/dotnet_corefx/outerloop_osx_debug/Tools/dotnetcli/bin/dotnet" restore --packages "/Users/dotnet-bot/j/workspace/dotnet_corefx/outerloop_osx_debug/packages" --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://www.nuget.org/api/v2/ "/Users/dotnet-bot/j/workspace/dotnet_corefx/outerloop_osx_debug/src" "/Users/dotnet-bot/j/workspace/dotnet_corefx/outerloop_osx_debug/pkg"" exited with code -1.
20:26:37   [20:30:16.82] Restoring all packages...Done.
20:26:40 
```

Full log [here](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_osx_debug/31/console)

cc @ericstj @dagood

**Comment by dagood** [comment]
Hmm, I'll try to repro on my local OSX. Thanks.

**Comment by dagood** [comment]
I can't repro this exact error, but it seems like for some reason the zip it's trying to extract is corrupted. Maybe clearing the machine's http cache (`~/.local/share/NuGet/v3-cache/`) would get rid of it?

**Comment by dagood** [comment]
Well, I can force a repro by editing a cached zip and making the "relative offset of local header" field invalid. I don't know how the cache would naturally get into that state though. Clearing nuget http cache definitely works around it though.

**Comment by Priya91** [comment]
@dagood Thanks, will try it out.

**Comment by Priya91** [comment]
There is no ```~/.local/share/NuGet/v3-cache/``` on the mac box..

**Comment by dagood** [comment]
Fixed by https://github.com/dotnet/corefx/pull/6839, but there's a additional (unrelated) issue with the OSX outerloop tests being discussed in that PR.
