### ISSUE TITLE
 await Windows.ApplicationModel.Email.EmailManager.ShowComposeNewEmailAsync(emailMessage);  launches Outlook email composer with incomplete content

### ISSUE THREAD

**Issue by 14inc** [dotnet/corefx#6826]
I have been having issues with launching the Windows Phone 10 Outlook email composer with a pre-populated body from a UWP app.

On both emulator and device, I experience inconsistent results with the same piece of code.

The core of the code is provided below:

`public static async Task ComposeEmail()`
`{`
`             `var emailMessage = new Windows.ApplicationModel.Email.EmailMessage();`
``emailMessage.Body = GenerateMessageBody();`
`            ``await Windows.ApplicationModel.Email.EmailManager.ShowComposeNewEmailAsync(emailMessage);`
`}`

`await Windows.ApplicationModel.Email.EmailManager.ShowComposeNewEmailAsync(emailMessage);` **_renders the body with incomplete content_** whose length before truncation is not consistent. I have crosschecked that `emailMessage.Body` contains the full content of the string passed to it.

In the case of a string containing HTML tags, Outlook sometimes renders the body as processed html (just like a web browser should) or plaintext html.

In either of these cases, it stops printing the string passed to the body at different points irrespective of whether it outputs it as processed html or plain text html.

Please be aware that this has been tested with strings with different character length but the issue still persists irrespective. 

**I have attached a complete standalone troubleshooting zip containing:**
• sample app which tries to launch the Outlook email composer whose body is prepopulated at the click of a button on the home screen.

I’ll be pleased if you can look into this.

[EmailComposer.zip](https://github.com/dotnet/corefx/files/168905/EmailComposer.zip)

**Comment by 14inc** [comment]
Any update on this issue, @joshfree ?

**Comment by joshfree** [comment]
I've sent some emails inside Microsoft to a few teams to help find the right place to report this issue for you. It's not the corefx repo, as the code above isn't part of .NET Core itself.

**Comment by tonyPendolino** [comment]
This API was implemented using a mailto protocol launch, so there are some inherent limitations to lengths because of the standard. I'm looking at switching off of that implementation for our Anniversary Update. I'll try to update when we have a firm plan.

**Comment by 14inc** [comment]
@tonyPendolino Thanks. It's always good to have some feedback. I think that will be really useful as the current implementation poses to be an hindrance in some use cases. Once again, thank a lot.

**Comment by tarekgh** [comment]
Closing the issue here as it is not corefx issue. @tonyPendolino please update when you have more news and move this issue to the place you can track. Thanks.
