### ISSUE TITLE
[corert] Dependency-free Marshal.PtrToString needs to use UTF8 encoding on Unix

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#6834]
https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Runtime/InteropServices/Marshal.Unix.cs#L25

**Comment by jkotas** [comment]
Related to https://github.com/dotnet/corefx/issues/6778

**Comment by jkotas** [comment]
I think the best way to fix this is to introduce LowLevelMarshal in System.Private.CoreLib.dll and just call it from here.

**Comment by tarekgh** [comment]
Yes I was going to change that soon. thanks for logging an issue to track it.
