### ISSUE TITLE
Add non-throwing methods to Convert class

### ISSUE THREAD

**Issue by Alexx999** [dotnet/corefx#684]
Convert class is the only method to convert boxed values to needed integer type. However, it throws exceptions, so it is too hard to implement behavior that matches simple explicit cast between integer types.
As a solution - add TryXXX methods to Convert class.

Additionally, it would be nice to have option to make Convert behave like explicit cast.
For example, this is valid:

``` C#
int a = -1;
int b = (int)(uint)a;
```

But this is not:

``` C#
int a = -1;
int b = Convert.ToInt32(Convert.ToUInt32(a));
```

This can be really useful when you process some data as "just some bytes" and you may get either signed or unsigned boxed value at input.
As a possible solution - add overload that accepts second boolean argument and acts like an explicit integer cast.

Example of this problems and required workaround can be seen in Enum class, in particular here:
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Enum.cs#L207

**Comment by terrajobst** [comment]
The static methods on `Convert` are also plumbed through via the `IConvertible` interface, specifically `Convert.ChangeType`. In order to support the `TryXxx` pattern we'd have to make a decision if, and how, this should play with `IConvertible`.

**Comment by danmosemsft** [comment]
Anyone willing to write up a formal [api proposal](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md) ?

**Comment by karelz** [comment]
I think this is assigned to @KrzysztofCwalina by accident (for 2 years), unassigning ...

**Comment by karelz** [comment]
API review: We don't quite see the value yet. There is little interest lately, closing.
We'll be happy to reopen if someone has solid proposal.

**Comment by jnm2** [comment]
Isn't `Convert` technically a legacy VB-compatibility class which was supposed to be replaced by `TypeConverter` even though no easy `TypeConverter.Convert` API was ever provided? 
The `Convert` class is no good for nullable types.
