### ISSUE TITLE
Access violation after task execution

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/corefx#6848]
If you run the code below using `System.Threading.Tasks 4.0.11-rc2-23826` you'll get an AV.

```
Task.Run(() =>
    {
    })
.ContinueWith(t =>
    {
    }, 
    TaskContinuationOptions.OnlyOnFaulted)
.Wait();
```

Exception:

```
Exception thrown at 0x00007FFBFC983CC0 (msvcrt.dll) in Foo.exe: 0xC0000005: Access violation reading location 0x00000000000000F1.

0xC0000005 occurred
  HResult=-2146233088
  Message=One or more errors occurred. (A task was canceled.)
  Source=mscorlib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at System.Threading.Tasks.Task.Wait()
       at Foo.Program.Main(String[] args) in <somepath>\Program.cs:line 40
  InnerException: 
       HResult=-2146233029
       Message=A task was canceled.
       InnerException: 
```

**Comment by janvorli** [comment]
@victorhurdugaci I am unable to repro the problem. Could you please share a minimal repro app with me?  And possibly add native stack dump at the point when the access violation occurs?

**Comment by sergiy-k** [comment]
Hi @victorhurdugaci, I also could not reproduce the problem. Could provide more information that @janvorli has asked for? In addition, it would be nice to know more about the configuration that you are using for your test (i.e. Windows version, etc.). Thank you.

**Comment by victorhurdugaci** [comment]
Sorry for the late reply. I tried it with the latest CoreCLR that we have and I was not able to reproduce it anymore... I was on Windows.

I'll close for now and reopen if I see it again. Thanks!
