### ISSUE TITLE
Unable to use Reflection to get StructLayoutAttribute for a type

### ISSUE THREAD

**Issue by couven92** [dotnet/corefx#6850]
In .NET CoreCLR it is not possible to get the `System.Runtime.InteropServices.StructLayoutAttribute` for a given type via reflection.

In usual .NET CLR the `System.Type` and `System.Reflection.TypeInfo` declare the `StructLayoutAttribute` member as the StructLayout cannot be retrieved by calls to `GetCustomAttribute()` or through the `CustomAttributes` property.

The consequence of this is that it is impossible to use reflection to get the packing size, or the constant size of a StructLayout marked type. Ironically, The `LayoutKind` and `CharSet` values can be infrerred from the `TypeAttributes` of a type info.

**Comment by weshaggard** [comment]
@pallavit was this part of your recent set of APIs you exposed in reflection?

**Comment by pallavit** [comment]
> In .NET CoreCLR it is not possible to get the  System.Runtime.InteropServices.StructLayoutAttribute  for a given type via reflection.

The recent package for System.Reflection expose TypeInfo.StructLayoutAttribute. Do let me know if you see any issues consuming it.

**Comment by pallavit** [comment]
Closing this issue for now. Feel free to reopen in case you hit any consuming the API.
