### ISSUE TITLE
(Proposal) Coding Guidelines. 

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/corefx#686]
The coding guidelines should be alter to permit the following styles. which aids the readability of the code.

* Align on the `:` of named parameters rather than lefthand edge of parmeter name
```c#
public static ImmutableArray<Diagnostic> GetAllMethodBodyDiagnostics(CSharpCompilation compilation, CancellationToken cancellationToken) 
{ 
  DiagnosticBag diagnostics = DiagnosticBag.GetInstance(); 
  CompileMethodBodies( 
                compilation: compilation,  
           moduleBeingBuilt: null,  
          generateDebugInfo: false,  
       hasDeclarationErrors: false,  
                     filter: null,  
                 filterTree: null,  
       filterSpanWithinTree: null, 
                diagnostics: diagnostics,  
          cancellationToken: cancellationToken ); 
  DocumentationCommentCompiler.WriteDocumentationCommentXml(compilation, null, null, diagnostics, cancellationToken); 
  compilation.ReportUnusedImports(diagnostics, cancellationToken); 
  
  return diagnostics.ToReadOnlyAndFree(); 
} 

```
vs
```c#
public static ImmutableArray<Diagnostic> GetAllMethodBodyDiagnostics(CSharpCompilation compilation, CancellationToken cancellationToken) 
{ 
    DiagnosticBag diagnostics = DiagnosticBag.GetInstance(); 
    CompileMethodBodies( 
         compilation: compilation,  
         moduleBeingBuilt: null,  
         generateDebugInfo: false,  
         hasDeclarationErrors: false,  
         filter: null,  
         filterTree: null,  
         filterSpanWithinTree: null, 
         diagnostics: diagnostics,  
         cancellationToken: cancellationToken); 
    DocumentationCommentCompiler.WriteDocumentationCommentXml(compilation, null, null, diagnostics, cancellationToken); 
    compilation.ReportUnusedImports(diagnostics, cancellationToken); *
    return diagnostics.ToReadOnlyAndFree(); 
} 

```

* Simple IF 
If the If statement is small and has no else, and the code block is small enough.
The combined width is less than the 80 character width limit.
```c#
if( arg0 == null ) throw new ArgumentException( nameof( arg0 ) );
if( arg0 == null ) { throw new ArgumentException( nameof( arg0 ) ); };
```
vs
```c#
if( arg0 == null )
{
    throw new ArgumentException( nameof( arg0 ) );
}
```
Consider multiple guards statements you are approaching halve of the length of the screen, ever before you've reached the core of the method.

* Simple case clause
```c#
select ( value )
{
 case 0: return "Zero";
 case 1: return "One";
 case 2: return "Two";
 // ...
 case 9: return "Nine";
 default:
   return "Foo";
}
```
vs
```c#
select ( value )
{
 case 0:
   return "Zero";
 case 1: 
   return "One";
 case 2:
    return "Two";
 // ... 
 case 9:
    return "Nine";
 default:
   return "Foo";
}
```
15 LoC rather than 25 or 35 if you need to include the `break`
```
case 0: output = "Zero"; break; 
```

* 2 space indentation  
Consider the case of pattern-matching, each scope gets indented, 5 levels of indentation and you're already used a quarter of the permitted code width.

* Method Parameter align vertically  
If the method signature is getting "too" wide, then consider vertical alignment.
```c#
internal static MethodSymbol DefineScriptEntryPoint
  (    CSharpCompilation           compilation,
         PEModuleBuilder      moduleBeingBuilt,
              TypeSymbol            returnType,
                    bool  hasDeclarationErrors,
           DiagnosticBag  diagnostics
  ) 
{ 
```
```c#
internal static MethodSymbol DefineScriptEntryPoint(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuilt, TypeSymbol returnType, bool hasDeclarationErrors, DiagnosticBag diagnostics) 
{
```
**NOTE** I not say that the existing code should be altered (it would still be valid according to the guidelines) but allow pull-requests to use some permitted alternatives forms. Yes someone could submit a pull-request that changes the exist to use the alternatives. Whether that pull-request would be accepted is a different question.

**Comment by am11** [comment]
+1 for avoiding [K&R style](http://en.wikipedia.org/wiki/Indent_style#K.26R_style) if-else blocks (note it is mentioned under "Variant 1TBS" that K&R actually says that):

```c#
if(cond)
    doSomething();
else if(otherCond)  doAnything();
else 
{
    doSomethingDifferent();
    redo();
}
```
(for example: [File.cs#L352-L361](https://github.com/dotnet/corefx/blob/12a1df91cec56ea2dbee6e10160909e1a8b775e6/src/System.IO.FileSystem/src/System/IO/File.cs#L352-L361))

in favor of:

```c#
if(cond)
{
    doSomething();   // be it a single statement
}
else if(otherCond)
{
    doAnything();    // be it a single statement
}
else 
{
    doSomethingDifferent();
    redo();
}
```

**Comment by sharwell** [comment]
I disagree with every suggested change in the original post. However, since these aren't part of the existing coding styles I'll reserve further comments (my rationale) for the event where it looks like one or more of these might be included in a future release of the style guide.

**Comment by AdamSpeight2008** [comment]
**2 Spaces**
```nemerle
{
  match( curr ) with
  {
    | '0' - '9' => {
                     var nc = curr;
                     do
                     { 
                       nc = nc.Next();
                       match (nc) with
                       {
                         | '_' when ( match( nc.Next() )
                                      {
                                        | '0'-'9' =>  true;
                                        | _       => false;
                                      }
                                    )  => nc = nc.Next();
                         | '0' - '9'   => nc = nc;
                         | _           => error UnexpectChar;
                       }
                     }
                   }
    | _         => return ;
  }
}
```
**4 Spaces**
```nemerle
{
    match( curr ) with
    {
        | '0' - '9' => {
                           var nc = curr;
                           do
                           { 
                               nc = nc.Next();
                               match (nc) with
                               {
                                   | '_' when ( match( nc.Next() )
                                                { 
                                                    | '0'-'9' =>  true;
                                                    | _       => false;
                                                }
                                              )  => nc = nc.Next();
                                   | '0' - '9'   => nc = nc;
                                   | _           => error UnexpectChar;
                               }
                           }
                       }
        | _         => return ;
    }
}
```

**Comment by ellismg** [comment]
Of the proposed changes, I think the two which might be useful are the "simple case clause" and the "simple if" rules.  I believe we don't have strict guidance on either today (so the proposed code would be fine).  Note that we do allow a similar thing for properties.  Allowing:

```csharp
get { return foo; }
```

over


```csharp
get 
{
    return foo;
}
```

@am11's example first example is disallowed by the style (I believe our rule is if any of the clauses of an if/else if/else statement have curly braces, then they all must have braces).

The two spaces other alignment rules go against the existing guidance we have today and I don't see a compelling reason to switch.

/cc @jaredpar @davkean @stephentoub who are all interested in style discussions.

**Comment by jakesays** [comment]
I'd have to say the suggested changes in the original post are some of my least favorite style rules. They do absolutely nothing to improve readability (especially the compressed if statements) and increase the style maintenance burden on code that uses them.

**Comment by jaredpar** [comment]
I agree with @ellismg here.

Some specific feedback:

- The guidance on `if` was discussed but it looks like we failed to codify it in the guidelines.  I will follow up to get it added but IIRC the rough guideline was: no single line `if` and either all blocks on `if`, `else if` and `else` have braces or none have braces.  
- Very opposed to allowing two space indent.  The main goal of the coding style is to provide consistency across the code base and make it as easy as possible for developers to transition between files.  Allowing two forms of indent goes directly against that goal.  
- I'm also opposed to the parameter and argument alignment for the same reason.

@AdamSpeight2008 

For the most recent code sample I assume you are using the proposed pattern matching feature for C#.  This feature doesn't exist yet and hence neither do the formatting rules and guideline.  For me that doesn't make a particularly compelling example.  I can't imagine changing the guidelines for a scenario that doesn't yet exist.  

But looking the code it seems like it could, and should, be much simpler.  I took that sample and applied what I think are the most likely formatting rules given how this feature relates to existing syntax constructs.  This is what I came up with:

``` csharp
{
    match (curr) with
    {
        | '0' - '9' => 
        {
            var nc = curr;
            do
            { 
                nc = nc.Next();
                match (nc) with
                {
                    | '_' when (match (nc.Next())
                        { 
                            | '0'-'9' =>  true;
                            | _ => false;
                        })  => nc = nc.Next();
                    | '0' - '9' => nc = nc;
                    | _ => error UnexpectChar;
                }
           }
        }
        | _ => return ;
    }
}
```

The biggest difference is the handling of `=>`.  This feature is closest to lambdas and I expect will end up with the same formatting rules (indentation against start of previous line, not against the `=>` token).  

CC'd @terrajobst

**Comment by mikedn** [comment]
* Single line if - tempting in cases like argument validation but no thanks, inconsistency doesn't actually improve readability. It's much easier to read that code when you know that the code guarded by if is always on separate line(s). Besides, I don't think that coding styles should be a LOC competition.
* 2 space indentation - nope, makes indentation useless
* vertical alignment - absolutely no way. Some read from left to write, others from right to left and others from top to bottom. Nobody is reading from the center of the text. Some of the CoreCLR's JIT code pulls the vertical alignment stunt in some files and it reads as if you are travelling in a car on a bad road.

**Comment by weshaggard** [comment]
@jaredpar the single line if statement is in the contribution guidelines:

>We use Allman style braces, where each brace begins on a new line. A single line statement block can go without braces but the block must be properly indented on its own line and it must not be nested in other statement blocks that use braces (See issue 381 for examples).

While if statement isn't called out explicitly it was generalized to all statement blocks. If people feel that should be reworded then we can certainly update it. That guideline also covers the simple case  statements blocks as well and argues they should be on their own line. I don't want to relax this guideline to allow single line if statements and thus for consistency I wouldn't want to allow it for case statements either.

**Comment by jaredpar** [comment]
@weshaggard ah okay.  I was looking for something specific to `if`, nice that we could boil it down to something that simple.

**Comment by am11** [comment]
@ellismg, that is true; I merged various practices into one example. 
The idea is to always have curlies for each if/else block, regardless
of single statement.

**Comment by AdamSpeight2008** [comment]
@jaredpar  Don't like it.

The align of `|` in pattern-matching block, with the ma**t**ch is used as aide memoire, 
Match with **t**his clause to 
```nemerle
match ( foo )
{
  | _ =>
}
```

Aligning the `=>` also aids visual that this clause are part of the same match block.
Snippet from yours'
```nemerle
match (nc) with
{
  | '_' when (match (nc.Next())
              { 
                | '0'-'9' =>  true;
                | _ => false;         /* Potential to think that these clause */
              })  => nc = nc.Next();  /* are part of the same match block     */
  | '0' - '9' => nc = nc;
  | _ => error UnexpectChar;
}
```
whereas using alignment of the `=>` in a match block.
```nemerle
match (nc) with
{
  | '_' when (match (nc.Next())
              { 
                | '0'-'9' =>  true;
                | _       => false;    /* Clearer these clauses are */
              } )  => nc = nc.Next();  /* in separate match blocks  */
  | '0' - '9'      => nc = nc;
  | _              => error UnexpectChar;
}
```

The use of `=>` in a match-clause isn't the same as lambda, so formatting is different.
Example of a match-clause "returning" a lambda.
```nemerle
match ( foo )
{ | bar => ()=> "bar";
  | baz => ()=> "baz";
  | _   => throw exception;
}
```


What's the issue with vertical alignment? "We" already do it for braces.

**Comment by jaredpar** [comment]
@AdamSpeight2008 

> The align of | in pattern-matching block, with the ma**t**ch is used as aide memoire, 

I don't see why `match` would be treated different than any other block level language construct here.  There are no cases today where the indentation is geared towards matching a particular letter in a block construct keyword, if it does happen to line up with 4 space indent it is merely coincidence.  

Further looking at other languages which use `match` expressions none take the stance that `|` should align with ma**t**ch.  The `|` construct is typically either aligned with the `match` keyword start or one indentation in (considered F# and OCaml here).  

Again though allowing for multiple indentation levels already goes directly against our consistency goals.  There would need to be a significant readability argument made for us to take that type of change to the guidelines.  A potential formatting issue on a *proposed* language feature isn't going to meet that bar.  

> What's the issue with vertical alignment? "We" already do it for braces.

We do left alignment for braces, this proposal is calling for center alignment.  That is a new and different format which goes against our desire for consistency.

**Comment by AdamSpeight2008** [comment]
@jaredpar pick two functional language that have significant whitespace indentation.
A better language to compare against would be [Nemerle](https://github.com/rsdn/nemerle), which is close to C# in style.
Nemerle does have `match` expression and does align on the `t` of match.
A majority of match-clause align on `=>` in match blocks. 
As well as vertically aligning of `:` in method parameters.

**Comment by jaredpar** [comment]
@AdamSpeight2008 

F# does have significant white space indentation.  Fairly certain OCaml does as well.

Nemerle's alignment on the `t` seems to just be a product of the standard indent being 2 spaces vs. anything to do with the `t`.  I couldn't find any hard guidelines about indent in Nemerle but every sample I could find used two space indent.  

Again though, this is debating formarting of a proposed language feature.

**Comment by sergiy-k** [comment]
I 100% agree with @mikedn on each of his statements especially with “inconsistency doesn't actually improve readability”. In my opinion, coding guidelines can be very subjective and we can argue about them indefinitely. So as long as coding guidelines are consistent, simple and applicable to majority of the existing codebase, we should just stick with them.

**Comment by AdamSpeight2008** [comment]
Pattern Matching is a much wanted addition to the C# and VB.net languages
So should the "style guide" for feature also be discussed during its development?

The point is you are comparing against the wrong languages, for style guidance (in the match expression aka pattern-matching). Both stated language ain't C-Style in there approach.
So you should be comparing against other C-Style languages and their approaches..
  C C++ Java, JavaScript,. etc

Which why is I chose Nemerle has it a functional language, in the style of C#. Does have match expression. 

Shouldn't the Style Guide change as the Languages Evolve? Shouldn't the (compiler at least) be a showcase for what that language can do?

In some of the languages, the style guide do suggest "compacting" of Trivial conditions.

**Comment by jaredpar** [comment]
@AdamSpeight2008 

> So should the "style guide" for feature also be discussed during its development?

Sure the guidelines should evolve as the language evolves.  In this case though you are trying to evolve the guidelines before the language feature exists.  

> Which why is I chose Nemerle has it a functional language, in the style of C#. Does have match expression.

I still don't agree with the argument that Nemerle style is the best argument here.  As I said in my comment it seems that Nemerle lining up the `|` with `t` is merely an artifact of block constructs in their samples using 2 space indent.  There doesn't seem to be anything special about `t` at least in the code and docs that' I've read.

**Comment by AdamSpeight2008** [comment]
I can't evolve the guidelines to include a potential language?
I can evolve the guidelines for existing language features?

How on earth is this open?

Just follow the style dictated by your Microsoft Overlord.

**Comment by terrajobst** [comment]
> I can't evolve the guidelines to include a potential language?

I've to admit that I'm with @jaredpar: I don't see the point of evolving a document, that is meant to be actionable today, to include speculative language features. It does, however, make sense to me to discuss styling guidelines in the context of the design of the language feature and propose changes [there](http://github.com/dotnet/roslyn).

> I can evolve the guidelines for existing language features?

Yes. And as @ellismg ([link](https://github.com/dotnet/corefx/issues/686#issuecomment-73393520)) @jaredpar ([ink](https://github.com/dotnet/corefx/issues/686#issuecomment-73399605)) said above, we're open to doing exactly that:

> I think the two which might be useful are the "simple case clause" and the "simple if" rules.

In order to make this discussion actionable I think you should split this issue into multiple issues:

1. Simplified if and case clauses
2. Alignment of colon and parameter names
3. Two space indentation

**Comment by AdamSpeight2008** [comment]
@terrajobst I did and @jaredpar told me do it here.

**Comment by AdamSpeight2008** [comment]
@ellismg Where in the style guide are single line properties allowed?

**Comment by jaredpar** [comment]
@AdamSpeight2008 the Roslyn issues thread wasn't discussing new language features hence I asked it to be moved here.

**Comment by MattWhilden** [comment]
Cleanup crew coming through. :-)

It seems to have died here but that's maybe alright. The path forward here is to open individual issues over in the code formatter repo. 

Let me know if you feel otherwise. Thanks!
