### ISSUE TITLE
Nullable types throw TargetException when attempting to retrieve HasValue property within Expression

### ISSUE THREAD

**Issue by JeffScherrer** [dotnet/corefx#6868]
When using expression trees (System.Linq.Expressions) in a Windows 10 UWP app, any references to .HasValue on a nullable type will throw an exception if the object is considered null.

Add the following code to a Windows 10 Universal Windows App function and execute:

`
ParameterExpression inputParameter = Expression.Parameter(typeof(int?));            
            Expression<Func<int?, bool>> lambda1 = Expression.Lambda<Func<int?, bool>>(Expression.Property(inputParameter, "HasValue"), inputParameter);
            Func<int?, bool> compiled1 = lambda1.Compile();

            Expression<Func<int?, bool>> lambda2 = (i) => i.HasValue;
            Func<int?, bool> compiled2 = lambda2.Compile();

            bool? failed1 = null;
            bool? failed2 = null;
            bool? failed3 = null;

            try
            {
                bool result = compiled1(null);
                failed1 = false;
            }
            catch (Exception ex)
            {
                failed1 = true;
            }

            try
            {
                bool result = compiled2(null);
                failed2 = false;
            }
            catch (Exception ex)
            {
                failed2 = true;
            }

            try
            {
                bool result = default(int?).HasValue;
                failed3 = false;
            }
            catch (Exception ex)
            {
                failed3 = true;
            }
            
        }
`

In the above example, the first two scenarios fail, the third scenario succeeds as expected, and as the first two should based on previous versions of the .NET runtime. 

Impact:
All of the code we've written that uses expression trees in .NET and Windows 8/Phone 8 will have to be refactored to support compatibility modifications that will need to modify the expression trees to run on Windows 10 specific runtimes.

**Comment by JonHanna** [comment]
This was fixed in #2753.

In nuget select "Include prerelease" and you'll be able to install System.Linq.Expressions 4.0.11-beta-23516 which is the latest prerelease build. This should run the above fine.

**Comment by JeffScherrer** [comment]
That's great news! I've tested this scenario and it works. Does that mean the fix will make it into the next update to .NET Core? I'm trying to understand the schedule in order to gain perspective on how long my apps will be using "prerelease" code...

**Comment by JonHanna** [comment]
@stephentoub do you know the answer to that last question? (I imagine the answer is "yes").

**Comment by stephentoub** [comment]
Yes.

**Comment by JeffScherrer** [comment]
How frequent are these releases?

**Comment by stephentoub** [comment]
@joshfree can best answer.

**Comment by joshfree** [comment]
Hi @JeffScherrer you can see our roadmap here https://github.com/aspnet/Home/wiki/Roadmap.  You'll notice the TBD / TBD 2016 placeholders right now for RC2 and RTM; this blog post https://blogs.msdn.microsoft.com/webdev/2016/02/01/an-update-on-asp-net-core-and-net-core/ talks to the TBD placeholder in more detail
> We’ll publish dates on the roadmap soon, but not before we – and you – can count on them.
