### ISSUE TITLE
Add way to get generic properties for an application in AppContext

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#6871]
AppDomain used to expose GetData and SetData to enable the hosts to add configuration type data needed by the applications. We need to expose something similar on AppContext to enable some dotnet cli scenarios. See https://github.com/dotnet/cli/issues/1707#issuecomment-196169123 for an example.

**Comment by weshaggard** [comment]
@AlexGhiondea please take a look at this. For now I think the following API.
```
object GetData(string version);
```

cc @terrajobst @KrzysztofCwalina

**Comment by AlexGhiondea** [comment]
@weshaggard - how about this?

```csharp
public static object GetData(string name)
```

**Comment by weshaggard** [comment]
Yes

**Comment by KrzysztofCwalina** [comment]
Why static?

**Comment by AlexGhiondea** [comment]
AppContext is a static class.

**Comment by KrzysztofCwalina** [comment]
Sorry, I confused it with LoadContext.

**Comment by AlexGhiondea** [comment]
This was done in: https://github.com/dotnet/corefx/commit/aaf7890386293b9a5b3983e957275ea135088583
