### ISSUE TITLE
Investigate failures when DiagnosticSource tests are run concurrently 

### ISSUE THREAD

**Issue by vancem** [dotnet/corefx#6872]
Currently there are failures when we run allow the DiagnosticSource tests to run concurrently with one another.  This suggests there may be bugs in the implementation. 

To repro  remove the assembly directive in DiagnosticSourceEventSourceTests.cs 

Also see the TODO in the AllSubscriberStress test case.

**Comment by joperezr** [comment]
@vancem I'll try to get a repro for this since it's been a while since it was logged.

**Comment by karelz** [comment]
@vancem says there is probably real bug.

Next step: Run the tests heavily in parallel and investigate failures, root-cause.
Complexity: Medium (threading, timing issues)
