### ISSUE TITLE
System.Private.Uri is not getting published

### ISSUE THREAD

**Issue by andschwa** [dotnet/corefx#6883]
When upgrading to build 23911 (and now 23914), we had to add an explicit dependency to `System.Private.Uri` (it used to be pulled in transitively by another package).

However, while it restores just fine, it's not getting published. I checked `project.lock.json` and it's referenced just fine, and the app compiles. But the DLL isn't copied to the output folder.

My .NET CLI version, for reference:

```sh
$ dotnet --version
.NET Command Line Tools (1.0.0-beta-001718)

Product Information:
 Version:     1.0.0-beta-001718
 Commit Sha:  N/A

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 Runtime Id:  ubuntu.14.04-x64
```

**Comment by andschwa** [comment]
> Internal implementation package not meant for direct consumption. Please do not reference directly. 

What package is supposed to pull it in then?

**Comment by andschwa** [comment]
From my prior `project.lock.json` at build 23907, it was `System.Runtime` that pulled it in.

**Comment by andschwa** [comment]
However, taking a direct dependency on that still does not get `System.Private.Uri` to restore.

I hate to bug you @stephentoub, but do know maybe know what's going on, or who I should ping?

**Comment by stephentoub** [comment]
@ericstj?

**Comment by andschwa** [comment]
I've somewhat narrowed it down.

When I make this change:

```
-                "NETStandard.Library": "1.0.0-rc3-23914",
+                "NETStandard.Library": "1.5.0-rc3-23914",
```

This reproduces.

If I leave it alone, I get a warning (since there is no 1.0.0-rc3-23914, only 1.0.0-rc3-23909), yet `System.Private.Uri.dll` gets published.

**Comment by andschwa** [comment]
When not changed, it's getting downgraded to `NETStandard.Library 1.5.0-rc2-23911` (for some reason). And that version publishes the assembly no problem.

Why can't I use 1.5.0-rc3-23914? It seems strange to need 1.5.0-rc2-23911, yet be using 23914 packages everywhere else.

**Comment by andschwa** [comment]
Using the odd version is works around for now, but this is very strange.

**Comment by weshaggard** [comment]
@andschwa can you point me at your project.json and your lock file?

**Comment by weshaggard** [comment]
@andschwa I think I tracked down what happened here and submitted a fix #6987. Until then you can workaround it by directly depending on the older version of System.Private.Uri package.

**Comment by andschwa** [comment]
Awesome, thanks @weshaggard. I will get everything updated with 23918 tomorrow, and so should be able to switch back to rc3. Sorry for not getting the logs to you!

**Comment by andschwa** [comment]
FWIW it still repros with NETStandard.Library 1.5.0-rc3-23918.

**Comment by andschwa** [comment]
PEBKAC. My find/replace got replaced.
