### ISSUE TITLE
[ToFDisable] Port tests for: System.Net*

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#6897]
As part of moving out of ToF and into the open, I've been going through the "Tree of the future" tests and calculating which of those tests provide coverage that we're missing in the open tests. The goal of this is to get the open tests universally better than the ToF tests so that we can turn the ToF tests off for ProjectK runs and save us all a lot of headache diagnosing test failures from potentially outdated tests.

For System.Net.Requests, we're missing 0 lines of coverage.
For System.Net.Security, we're missing 0 lines of coverage.
For System.Net.Sockets, we're missing 1246 lines of coverage.
For System.Net.WebHeaderCollection, we're missing 0 lines of coverage.
For System.Net.WebSockets.Client, we're missing 19 lines of coverage.

To fulfill the uncovered lines we would need to either create new tests for them or port 6 ToF tests to the open. Those tests are: 

- [ ] System.Net.Sockets\4.0.10.0\NetSocketsTestAsyncServer_FullRun.XML
- [ ] System.Net.Sockets\4.0.10.0\NetSocketsPerformanceTest_FullRun.XML
- [ ] System.Net.Sockets\4.0.10.0\NetSocketsTest_FullRun.XML
- [ ] System.Net.Sockets\4.0.0.0\NetSocketsTest_FullRun.XML
- [ ] System.Net.Sockets\4.0.0.0\NetSocketsPerformanceTest_FullRun.XML
- [ ] System.Net.WebSockets.Client\4.0.0.0\NetWebSocketsClient_FullRun.XML

Coverage reports, coverage xml files, and detailed json lists of each piece of missing coverage and the corresponding ToF test that fills it are available on request.

**Comment by ianhays** [comment]
This is leaving out a few test libraries where assembly names differ between the tests in ToF and Open. I'll update this with those results later.

Libraries included in that:
System.Net.Http
System.Net.Http.WinHttpHandler
System.Net.Ping
System.Net.Primitives

**Comment by ianhays** [comment]
For all of System.Net.*, we're missing 740 lines of coverage.

Test projects that contain coverage missing in Open:

- [ ] System.Net.Http\4.0.0.0\NetHttpTest_FullRun.XML
- [ ] System.Net.Requests\4.0.10.0\NetRequestsTest_FullRun.XML
- [ ] System.Net.Http.WinHttpHandler\4.0.0.0\NetWinHttpHandlerTest_FullRun.XML
- [ ] System.Net.Primitives\4.0.10.0\NetPrimitivesTest_FullRun.XML
- [ ] System.Net.NameResolution\4.0.0.0\NetNameResolutionTest_FullRun.XML
- [ ] System.Net.NetworkInformation\4.0.10.0\NetNetworkInformationTest_FullRun.XML
- [ ] System.Net.Sockets\4.0.0.0\NetSocketsTest_FullRun.XML
- [ ] System.Net.Sockets\4.0.10.0\NetSocketsTestAsyncServer_FullRun.XML
- [ ] System.Net.Security\4.0.0.0\NetSecurityTest_FullRun.XML
- [ ] System.Net.Sockets\4.0.10.0\NetSocketsTest_FullRun.XML
- [ ] System.Net.Sockets\4.0.10.0\NetSocketsPerformanceTest_FullRun.XML
- [ ] System.Net.WebSockets.Client\4.0.0.0\NetWebSocketsClient_FullRun.XML

This is the result of all ToF System.Net* test project coverage compared against the entire set of Open coverage.This way we don't have missing coverage for tests that were moved to a different test project e.g. *.Functional.Tests.csproj in open vs *.Tests.csproj in ToF.

**Comment by CIPop** [comment]
@ianhays, @pgavlin and I ported everything we had in ToF to CoreFX. New tests were actually added.
I know of a single instance where @ericeil merged the System.Net.Sockets.Legacy within the System.Net.Sockets tests. Also, the Sockets perf tests are not ran part of CI.

@ericeil @stephentoub, did we loose any tests? Any idea why we're not seeing the same coverage here?

**Comment by CIPop** [comment]
Forgot to mention: I've diffed all System.Net ToF and CoreFX tests yesterday and opened the following tracking issues, mostly to get UWP coverage: #9049, #9044

**Comment by ianhays** [comment]
There are a ton of reasons coverage could differ and missing tests is only one of those reasons. It's certainly possible that differences in execution result in touched lines differing between runs. It's also possible that the ToF tests cover exceptions that aren't easily testable from an xunit test and so those were left out in porting to CoreFX. Sometimes the missing lines are from classes or methods that aren't relevant to the tests but I wasn't able to reliably filter them out.

Here's the zip of my results: [System.Net.All.zip](https://github.com/dotnet/corefx/files/296423/System.Net.All.zip). You can view the index.html within the zip as you would any other coverage report. Red lines are lines that were covered in ToF but were not covered in Open.

Ultimately you can close this issue whenever you're confident that all useful ToF tests have been ported to CoreFX. After all, coverage is a good start to finding gaps but it sometime doesn't tell the whole story.

**Comment by CIPop** [comment]
Thanks for sharing @ianhays. I don't remember us leaving any of the tests behind because it wasn't easily testable from xunit. Some of the tests did get converted to OuterLoop but should still cover roughly the same.

**Comment by ericeil** [comment]
I agree with @CIPop that we've already ported all useful tests from ToF, or filed separate issues for old tests that haven't yet been ported.  If we still feel like we're missing important coverage, we should file separate issues for adding new tests (we already have several such issues).

I'm closing this one.
