### ISSUE TITLE
Port EventLog to .NET Core

### ISSUE THREAD

**Issue by terrajobst** [dotnet/corefx#6913]
This includes `System.Diagnostics.EventLog` and friends.

**Comment by danmosemsft** [comment]
This isn't in the Mono mobile subset. Only 
`EventLogEntryType`

**Comment by danmosemsft** [comment]
This is not currently in .NET Standard 2.0. It would be an extension. It probably isn't useful to have an issue for it.

**Comment by danmosemsft** [comment]
Let's use this to track interest in System.Diagnostics.EventLog.

**Comment by danmosemsft** [comment]
Please add a thumbs up to top post if this is relvant to you.

**Comment by alexgwolff** [comment]
https://github.com/PowerShell/PowerShell/tree/master/src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing

**Comment by danmosemsft** [comment]
completed - available in myget, expect on nuget in mid November.

**Comment by DutulescuRemus** [comment]
Any update on when it will be available on nuget?

**Comment by ppman11** [comment]
@danmosemsft Is the nuget package for this available currently?

**Comment by danmosemsft** [comment]
@ppman11 yes it's on nuget here:
https://www.nuget.org/packages/System.Diagnostics.EventLog/4.5.0-preview1-26216-02

If you need compat shims (ie., you want to reuse a binary that was built against .NET Framework) you also need https://www.nuget.org/packages/Microsoft.Windows.Compatibility.Shims/2.0.0-preview1-26216-02

Normally these would be wrapped up in a metapackage but there has been a delay in publishing that due to a name conflict.

**Comment by ppman11** [comment]
@danmosemsft Thanks Dan. That was helpful.

**Comment by MohsenBzm** [comment]
What about linux, or dockerized linux .netcore containers? where does the `EventLog` save the logs?

**Comment by danmosemsft** [comment]
@MohsenBzm this is Windows only and may never have Linux functionality. It is ported to help Windows based code move to Core. In some cases we r have gone further eg for Drawing we ship the Mono version for Linux.
What are you trying to achieve?

**Comment by MohsenBzm** [comment]
It seems to be written to /var/log/message

**Comment by MohsenBzm** [comment]
@danmosemsft : I mean using .netcore https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x

**Comment by theimowski** [comment]
Can you use `System.Diagnostics.EventLog` on .NET Core to query nested event logs from `Applications and Services`, like `Microsoft-Windows-PowerShell/Operational` ?

If not, what's the alternative to query those logs on .NET Core?

**Comment by danmosemsft** [comment]
@theimowski it has the same functionality as on desktop framework so I assume so.
If necessary please open a new issue : it's easy to miss comments on a closed one like this.
