### ISSUE TITLE
unable to locate dependencies on Linux only, on windows all is ok

### ISSUE THREAD

**Issue by joganet** [dotnet/corefx#6917]
Hi
I have a dnxcore50 project where we use some dependencies like Diagnostics, or IO, Reflection.... just to mention a few, in windows the restore works fine (we use VS with a console package project) but we are trying to run the app on Ubuntu without success, when we are doing the dnu restore (or dotnet restore, is the same) we have some depenencies that were not found (see list below)

    Unable to locate Dependency System.Diagnostics.Contracts >= 4.0.1-rc2-23623
    Unable to locate Dependency System.Diagnostics.TextWriterTraceListener >= 4.0.0-rc2-23616
    Unable to locate Dependency System.Diagnostics.Tools >= 4.0.1-rc2-23616
    Unable to locate Dependency System.Globalization >= 4.0.11-rc2-23623
    Unable to locate Dependency System.IO >= 4.0.11-rc2-23616
    Unable to locate Dependency System.Reflection >= 4.1.0-rc2-23623
    Unable to locate Dependency System.Reflection.TypeExtensions >= 4.1.0-rc3-23727
    Unable to locate Dependency System.Resources.ResourceManager >= 4.0.1-rc3-23727
    Unable to locate Dependency System.Runtime >= 4.0.21-rc2-23623
    Unable to locate Dependency System.Runtime.InteropServices >= 4.0.21-rc2-23616
    Unable to locate Dependency System.Threading.Overlapped >= 4.0.1-rc3-23727
    Unable to locate Dependency System.Threading.Tasks >= 4.0.11-rc2-23623
    Unable to locate Dependency System.Threading.Thread >= 4.0.0-rc2-23623
    Unable to locate Dependency System.Threading.ThreadPool >= 4.0.10-rc2-23623
    Unable to locate Dependency System.Threading.Timer >= 4.0.1-rc2-23616

those are necessary and like I said on windows are located and downloaded fine, but not on Linux

when we can expect those files available? we need to be able to run the same app un multi targets for now we are addressing this to windows and Linux just for testing but we will try to on mac osx too in a near future.

Thanks

**Comment by joganet** [comment]
as addition infromation, this is the final output using dotnet.cli

Errors in /home/XXX/YYYYYYYYYYYYYYY/project.json
    Unable to resolve System.Diagnostics.Contracts (>= 4.0.1-rc2-23623) for DNXCore,Version=v5.0.
    Unable to resolve System.Reflection.TypeExtensions (>= 4.1.0-rc3-23727) for DNXCore,Version=v5.0.
    Unable to resolve System.Diagnostics.Tools (>= 4.0.1-rc2-23616) for DNXCore,Version=v5.0.
    Unable to resolve System.IO (>= 4.0.11-rc2-23616) for DNXCore,Version=v5.0.
    Unable to resolve System.Reflection (>= 4.1.0-rc2-23623) for DNXCore,Version=v5.0.
    Unable to resolve System.Threading.Overlapped (>= 4.0.1-rc3-23727) for DNXCore,Version=v5.0.
    Unable to resolve System.Threading.Tasks (>= 4.0.11-rc2-23623) for DNXCore,Version=v5.0.
    Unable to resolve System.Globalization (>= 4.0.11-rc2-23623) for DNXCore,Version=v5.0.
    Unable to resolve System.Threading.Timer (>= 4.0.1-rc2-23616) for DNXCore,Version=v5.0.
    Unable to resolve System.Diagnostics.TextWriterTraceListener (>= 4.0.0-rc2-23616) for DNXCore,Version=v5.0.
    Unable to resolve System.Resources.ResourceManager (>= 4.0.1-rc3-23727) for DNXCore,Version=v5.0.
    Unable to resolve System.Runtime (>= 4.0.21-rc2-23623) for DNXCore,Version=v5.0.
    Unable to resolve System.Runtime.InteropServices (>= 4.0.21-rc2-23616) for DNXCore,Version=v5.0.
    Unable to resolve System.Threading.Thread (>= 4.0.0-rc2-23623) for DNXCore,Version=v5.0.
    Unable to resolve System.Threading.ThreadPool (>= 4.0.10-rc2-23623) for DNXCore,Version=v5.0.

NuGet Config files used:
    /home/gabe/.nuget/NuGet/NuGet.Config

Feeds used:
    https://api.nuget.org/v3/index.json

**Comment by glennc** [comment]
`continuing from Twitter`

Yeah, see how you are only using a single NuGet.Config file. If you look in your app you have a custom one with some custom feeds. But there is a bug in the current version of the CLI (fix checked in yesterday I think) that stops the restore from looking at the one in your app folder. If you copy the NuGet.Config from your app directory to one directory above it then it will work around the bug.

So copy the NuGet.Config that is next to your project.json to `../NuGet.Config`. Does that help?

**Comment by glennc** [comment]
This isn't really an issue for corefx, should be in the CLI repo or on NuGet. But hopefully this will resolve it and we can just close it rather than moving it.

**Comment by joganet** [comment]
Hi Glennc

But I don't have another NuGet.Config, in my console app only have the folowing files

-rw-rw-r-- 1 gabe gabe 160060 mar 15 12:32 project.lock.json
drwxrwxr-x 3 gabe gabe   4096 mar 14 16:26 .
drwxrwxr-x 2 gabe gabe   4096 mar 14 16:26 Properties
drwxrwxr-x 5 gabe gabe   4096 mar 11 17:21 ..
-rw-rw-r-- 1 gabe gabe   2176 mar 10 20:33 Program.cs
-rw-rw-r-- 1 gabe gabe    747 mar 10 20:31 project.json
-rw-rw-r-- 1 gabe gabe   1318 mar  8 16:04 Test.Console.xproj
-rw-rw-r-- 1 gabe gabe    253 mar  8 15:48 Test.Console.xproj.user

one of my dependencies in project.json is a custom library in dotnet core too that is the one that require those missing dependencies, and in that library I don't have either a custom nuget configuration file

**Comment by joganet** [comment]
if this is a cli repo issue how can I move it to the correct forum?

**Comment by glennc** [comment]
Ok, so you created this how? I am assuming you created it using RC1 of the DNX and are starting to change to dotnet cli?

**Comment by glennc** [comment]
There is a CLI repo in the dotnet group here on GitHub

**Comment by joganet** [comment]
yes we created on windows using the RC1 of DNX, I just installed dotnet-cli recently, we still work with dnx, dnu throws a similar error so is not something specific for dotnet-cli, this only happends on Linux, in windows works like a charm

the output from dnu is

Errors in /home/gabe/Test.Console/project.json
    Unable to locate Dependency System.Diagnostics.Contracts >= 4.0.1-rc2-23623
    Unable to locate Dependency System.Diagnostics.TextWriterTraceListener >= 4.0.0-rc2-23616
    Unable to locate Dependency System.Diagnostics.Tools >= 4.0.1-rc2-23616
    Unable to locate Dependency System.Globalization >= 4.0.11-rc2-23623
    Unable to locate Dependency System.IO >= 4.0.11-rc2-23616
    Unable to locate Dependency System.Reflection >= 4.1.0-rc2-23623
    Unable to locate Dependency System.Reflection.TypeExtensions >= 4.1.0-rc3-23727
    Unable to locate Dependency System.Resources.ResourceManager >= 4.0.1-rc3-23727
    Unable to locate Dependency System.Runtime >= 4.0.21-rc2-23623
    Unable to locate Dependency System.Runtime.InteropServices >= 4.0.21-rc2-23616
    Unable to locate Dependency System.Threading.Overlapped >= 4.0.1-rc3-23727
    Unable to locate Dependency System.Threading.Tasks >= 4.0.11-rc2-23623
    Unable to locate Dependency System.Threading.Thread >= 4.0.0-rc2-23623
    Unable to locate Dependency System.Threading.ThreadPool >= 4.0.10-rc2-23623
    Unable to locate Dependency System.Threading.Timer >= 4.0.1-rc2-23616

Feeds used:
    https://api.nuget.org/v3-flatcontainer/


as you can see is the same issue

**Comment by joganet** [comment]
ok, so I will post then in the CLI repo thanks
