### ISSUE TITLE
ArgumentOutOfRangeException when creating named pipes on OSX

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#6918]
When I run `System.IO.NamedPipes.Tests` on my OSX machine, most tests fail with an `ArgumentOutOfRangeException` in `UnixDomainSocketEndPoint(string)`.  It seems the socket path is too long.  I am seeing path strings like this:

```
/var/folders/c7/vc_7ks111wqg4svm2dwq81yw0000gn/T/.dotnet/corefx/pipes/42900fc4-3df4-4a0f-bc93-85b9432ce8b3
```

It looks like this is derived from `Environment.GetTempPath`.  I haven't done anything to customize my temp path, so I assume others with stock configurations will hit this as well.

**Comment by stephentoub** [comment]
There is in fact a length limit for Unix domain sockets: names must be <= 92 characters.  And this path is 106.  I'm not sure why my local tmp folder and the one used in CI are so different from what you've got, but obviously I'll address it.

**Comment by ericeil** [comment]
For anyone who runs across this issue in the future, the workaround is:

```
export TMPDIR=/tmp/
```
