### ISSUE TITLE
[ToFDisable] Port tests for: System.Security.SecureString

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#6923]
As part of moving out of ToF and into the open, I've been going through the "Tree of the future" tests and calculating which of those tests provide coverage that we're missing in the open tests. The goal of this is to get the open tests universally better than the ToF tests so that we can turn the ToF tests off for ProjectK runs and save us all a lot of headache diagnosing test failures from potentially outdated tests.

For System.Security.SecureString, we're missing 388 lines of coverage.

To fulfill the uncovered lines we would need to either create new tests for them or port 1 ToF tests to the open. Those tests are: 

- [ ] System.Security.SecureString\SecureStringTests_FullRun.XML

Coverage reports, coverage xml files, and detailed json lists of each piece of missing coverage and the corresponding ToF test that fills it are available on request.

It looks like I was unable to find any CoreFX tests for SecureString. Did I miss them?

**Comment by stephentoub** [comment]
System.Security.SecureString was removed from corefx.
