### ISSUE TITLE
Remove manual SafeHandle marshaling in Unix Socket interop code

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#6928]
#6345 plumbed SafeHandle usage throughout the Unix Socket interop layer, but had to do manual marshaling from SafeHandles to file descriptors in the native interop layer because most of the Socket-related methods in System.Native take "int"-type file descriptor arguments, rather than IntPtr.  If these are changed to IntPtr, we can remove the manual marshaling code.

**Comment by stephentoub** [comment]
I see that the milestone for this got changed to be 1.1.0?   It's possible that we're not going to be able to remove or change entrypoint signatures in our native shims once we ship.
