### ISSUE TITLE
Fix ApiCompat issues for System.Runtime.Extensions

### ISSUE THREAD

**Issue by venkat-raman251** [dotnet/corefx#6934]
Remove ApiCompatBaseline.netcore50aot.txt once errors mentioned in it are resolved.

**Comment by venkat-raman251** [comment]
MembersMustExist : Member 'System.Environment.Exit(System.Int32)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Environment.GetCommandLineArgs()' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Environment.MachineName.get()' does not exist in the implementation but it does exist in the contract.

The above types do not match between the contracts and the impl.

**Comment by venkat-raman251** [comment]
@weshaggard Who is the owner of system.runtime.extensions that i can assign this bug to?

**Comment by AlexGhiondea** [comment]
@pallavit could you take a look at this?

**Comment by pallavit** [comment]
PR #7533 fixes this.
