### ISSUE TITLE
Fix ApiCompat issues for System.Security.Cryptography.X509Certificates

### ISSUE THREAD

**Issue by venkat-raman251** [dotnet/corefx#6935]
Remove ApiCompatBaseline.net46.txt once errors mentioned in it are resolved.

**Comment by bartonjs** [comment]
@venkat-raman251 How do I run ApiCompat to ensure that I've fixed all the problems?  I tried intentionally breaking it by adding some new enum members in a contract, but it didn't warn that I saw...

**Comment by venkat-raman251** [comment]
With the latest build tools, run msbuild with /p:RunApiCompat=true.

**Comment by venkat-raman251** [comment]
Fixed
