### ISSUE TITLE
Fix ApiCompat issues for System.Data.Common

### ISSUE THREAD

**Issue by venkat-raman251** [dotnet/corefx#6937]
Remove ApiCompatBaseline.net45.txt once errors mentioned in it are resolved.

**Comment by venkat-raman251** [comment]
CannotAddAbstractMembers : Member 'System.Data.Common.DbDataReader.Close()' is abstract in the implementation but is missing in the contract.
CannotAddAbstractMembers : Member 'System.Data.Common.DbDataReader.GetSchemaTable()' is abstract in the implementation but is missing in the contract.
CannotAddAbstractMembers : Member 'System.Data.Common.DbParameter.SourceVersion' is abstract in the implementation but is missing in the contract.
MembersMustExist : Member 'System.Data.Common.DbParameter.Precision.get()' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Data.Common.DbParameter.Precision.set(System.Byte)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Data.Common.DbParameter.Scale.get()' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Data.Common.DbParameter.Scale.set(System.Byte)' does not exist in the implementation but it does exist in the contract.
CannotAddAbstractMembers : Member 'System.Data.Common.DbParameter.SourceVersion.get()' is abstract in the implementation but is missing in the contract.
CannotAddAbstractMembers : Member 'System.Data.Common.DbParameter.SourceVersion.set(System.Data.DataRowVersion)' is abstract in the implementation but is missing in the contract.
CannotAddAbstractMembers : Member 'System.Data.Common.DbParameterCollection.IsFixedSize' is abstract in the implementation but is missing in the contract.
CannotAddAbstractMembers : Member 'System.Data.Common.DbParameterCollection.IsReadOnly' is abstract in the implementation but is missing in the contract.
CannotAddAbstractMembers : Member 'System.Data.Common.DbParameterCollection.IsSynchronized' is abstract in the implementation but is missing in the contract.
CannotAddAbstractMembers : Member 'System.Data.Common.DbParameterCollection.IsFixedSize.get()' is abstract in the implementation but is missing in the contract.
CannotAddAbstractMembers : Member 'System.Data.Common.DbParameterCollection.IsReadOnly.get()' is abstract in the implementation but is missing in the contract.
CannotAddAbstractMembers : Member 'System.Data.Common.DbParameterCollection.IsSynchronized.get()' is abstract in the implementation but is missing in the contract.

The above types do not match between the contracts and the impl.

**Comment by joshfree** [comment]
@saurabh500

**Comment by ericstj** [comment]
@saurabh500 I think this needs to target .NET 4.5.1, not .NET 4.5, right?

**Comment by saurabh500** [comment]
Fixed with https://github.com/dotnet/corefx/pull/7767

**Comment by weshaggard** [comment]
```
MembersMustExist : Member 'System.Data.Common.DbEnumerator..ctor(System.Data.Common.DbDataReader, System.Boolean)' does not exist in the implementation but it does exist in the contract.
```

After trying to enable ApiCompat by default in our builds (https://github.com/dotnet/corefx/pull/8513) we are hitting the below compat issue. @saurabh500 can you please have a look into this?

**Comment by saurabh500** [comment]
cc @corivera

**Comment by saurabh500** [comment]
@weshaggard The Sytem.Data.Common contract and implementation for DbEnumerator are in Sync.

Contract : 
https://github.com/dotnet/corefx/blob/master/src/System.Data.Common/ref/System.Data.Common.cs#L399

Implementation: 
https://github.com/dotnet/corefx/blob/master/src/System.Data.Common/src/System/Data/Common/DbEnumerator.cs#L25

**Comment by weshaggard** [comment]
The compat issue is saying that this member does not exist in .NET 4.5.1 can you please double check that?

**Comment by saurabh500** [comment]
Yes the contract is not in sync with 4.5.1
Fix is to have System.Data.Common create a new version of contract targeting 4.6 to fix this issue.

**Comment by weshaggard** [comment]
I thought the you needed a version that supports .NET 4.5.1? If so what happens if you remove this API from the contract to enable that? If this API is needed and you don't need .NET 4.5.1 support then you can just bump up to .NET 4.6

**Comment by saurabh500** [comment]
We need to have a contract targeting 4.5.1 for System.Data.Common since the work was done to have minimum support for v4.5.1 and there are many libraries which target lower versions of .Net which need a compatible Data.Common library.
`DbEnumerator` should be excluded from the Contract for 4.5.1 and added to a new contract targeting 4.6

**Comment by saurabh500** [comment]
The .Net 4.5.1 supports DbEnumerator with IDataReader in the constructor.
The fix is to change the `DbEnumerator` to use `IDataReader` in the contracts and implementation so that the impl and contracts are in sync with the .Net Framework 4.5.1
This will allow the API in .Net 4.5.1 and there will be no need of a new contract version.
