### ISSUE TITLE
Fix ApiCompat issues for System.Data.SqlClient 

### ISSUE THREAD

**Issue by venkat-raman251** [dotnet/corefx#6938]
Remove ApiCompatBaseline.net45.txt once errors mentioned in it are resolved.

**Comment by venkat-raman251** [comment]
MembersMustExist : Member 'System.Data.SqlClient.SqlConnectionStringBuilder.ConnectRetryCount.get()' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Data.SqlClient.SqlConnectionStringBuilder.ConnectRetryCount.set(System.Int32)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Data.SqlClient.SqlConnectionStringBuilder.ConnectRetryInterval.get()' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Data.SqlClient.SqlConnectionStringBuilder.ConnectRetryInterval.set(System.Int32)' does not exist in the implementation but it does exist in the contract.

The above types do not match between the contracts and the impl.

**Comment by joshfree** [comment]
@saurabh500

**Comment by ericstj** [comment]
@saurabh500 I think this needs to target .NET 4.5.1, not .NET 4.5, right?

**Comment by saurabh500** [comment]
@ericstj that's correct. I opened an issue to track the requirement.
