### ISSUE TITLE
Need to remove Framework-specific assembly attributes from test assemblies

### ISSUE THREAD

**Issue by MattGal** [dotnet/corefx#6945]
The test DLLs for CoreFX are getting created using the values from https://github.com/dotnet/corefx/blob/master/dir.props 

This leads to assembly metadata like this:
[assembly: AssemblyVersion("999.999.999.999")]
[assembly: OptimizeForBenchmarks]
[assembly: AssemblyCompany("Microsoft Corporation")]
[assembly: AssemblyCopyright("© Microsoft Corporation.  All rights reserved.")]
[assembly: AssemblyDefaultAlias("System.Collections.Tests")]
[assembly: AssemblyDescription("System.Collections.Tests")]
[assembly: AssemblyFileVersion("1.0.00001.0")]
[assembly: AssemblyInformationalVersion("1.0.00001.0 built by: NETCORETSTBLD19-CORBVT")]
**[assembly: AssemblyMetadata(".NETFrameworkAssembly", "")]**
**[assembly: AssemblyMetadata("Serviceable", "True")]**
**[assembly: AssemblyProduct("Microsoft® .NET Framework")]**
[assembly: AssemblyTitle("System.Collections.Tests")]
[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]

As well as having the same public key token as the actual product dlls.

This becomes a much bigger deal when trying to compile these tests for .NET Native, as .NET Native considers these DLLs to be part of the platform and doesn't include them as part of the test "application" to be compiled as native.  

Fixing this will entail either signing with a different key (perhaps just using the OpenKey )  or no key, and removing these attributes.

**Comment by joshfree** [comment]
moving this to the RTM milestone

**Comment by mellinoe** [comment]
@MattGal fixed this with some buildtools changes, we no longer emit these for test assemblies.
