### ISSUE TITLE
WebUtility.UrlEncodeToBytes erroneously returns the full array if no encoding is needed

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#6947]
This code prints `1 2 3`, when it should print `2 3`:

```csharp
byte[] input = { 49, 50, 51 };
byte[] output = WebUtility.UrlEncodeToBytes(input, offset: 1, count: 2);
foreach (var item in output)
    Console.WriteLine((char)item);
```

The problem seems to be coming from [this](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/Net/WebUtility.cs#L319) line in the internal `UrlEncode` implementation, which returns the whole byte array disregarding the offset and the count.

Luckily I've found out that I accidentally fixed this with #6698, so this can be closed soon enough when that is merged.

cc @stephentoub @davidsh

**Comment by davidsh** [comment]
>Luckily I've found out that I accidentally fixed this with #6698, so this can be closed soon enough when that is merged.

That PR is now CLOSED and won't be merged as-is. So, we'll need to fix this separately. The code was ported from .NET Framework (Desktop), so it should have worked the same, but I think a bug was introduced during the port.

**Comment by jamesqo** [comment]
@davidsh Nope, this happens in the desktop as well.

**Comment by davidsh** [comment]
On .NET Framework 4.6.1, I see the correct output:  4.6.1 is the latest .NET Framework.

![image](https://cloud.githubusercontent.com/assets/7684835/13905071/4870fbee-ee72-11e5-8698-ade98f45a29f.png)

What version of .NET Framework do you have?

**Comment by davidsh** [comment]
![image](https://cloud.githubusercontent.com/assets/7684835/13905079/afdd24b0-ee72-11e5-8cc3-349a184dc545.png)

![image](https://cloud.githubusercontent.com/assets/7684835/13905081/b7f682a4-ee72-11e5-935a-acd72d3936ed.png)

**Comment by jamesqo** [comment]
@davidsh I have the same version as you, 4.6.1038.0. Just tested locally, it seems to be outputting correctly on my machine (even on .NET < 4.6).

**Comment by jamesqo** [comment]
It seems this code is not even fixed in the [original reference source](https://github.com/Microsoft/referencesource/blob/e458f8df6ded689323d4bd1a2a725ad32668aaec/System/net/System/Net/WebUtility.cs#L395), either, so I'm not sure how it's working.

**Comment by stephentoub** [comment]
@jamesqo, that line is not where the problem comes from.  Note the difference between:
https://github.com/Microsoft/referencesource/blob/e458f8df6ded689323d4bd1a2a725ad32668aaec/System/net/System/Net/WebUtility.cs#L421-L431
and:
https://github.com/dotnet/corefx/blob/e2f0f429788f611b3d7ac35f0154c975011fd191/src/System.Runtime.Extensions/src/System/Net/WebUtility.cs#L318-L319

**Comment by davidsh** [comment]
This is an example of a bug fix made to .NET Framework (Desktop) after the initial port to CoreCLR/CoreFx. Now that we have identified the proper code, I can submit a PR to fix it.

```c#
// nothing to expand?
if (cSpaces == 0 && cUnsafe == 0) {
    // DevDiv 912606: respect "offset" and "count"
    if (0 == offset && bytes.Length == count) {
        return bytes;
    }
    else {
        var subarray = new byte[count];
        Buffer.BlockCopy(bytes, offset, subarray, 0, count);
        return subarray;
    }
}
```
