### ISSUE TITLE
Minor wiki text edit

### ISSUE THREAD

**Issue by kendaleiv** [dotnet/corefx#697]
On https://github.com/dotnet/corefx/wiki/Issues, see error in bold below:

"grabbed by community: Someone outside the CoreFx team **as** called "dibs" on this issue and is working on a fix."

**Comment by akoeplinger** [comment]
Some more typos:

* "It may be **a** simple as a small product or test bug" -> as
* "we'll try to find a better home for the issue and open it **their** on your behalf." -> there
* "This started as User Voice request, " --> as a

Regarding the "has called dibs on this issue" phrase: I'm not sure this particular idiom is well-known enough to people who don't have English as their first language to warrant using it here. I'd suggest rewriting it to a more common term.

**Comment by stephentoub** [comment]
Thanks for noticing these.  I've fixed these issues.
