### ISSUE TITLE
WinHttpHandler needs to better handle proxy url when DefaultProxyCredentials used

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#6997]
See discussion here:
https://github.com/dotnet/corefx/pull/6992/files#r56524599

**Comment by karelz** [comment]
It's edge case bug.
Next step: Review the PR comments and provide a fix.
Complexity: Medium, requires WinHttp stack knowledge.

**Comment by karelz** [comment]
Triage: Edge case, no customer asking for it. Closing.
We can reopen if there is real customer report.
