### ISSUE TITLE
Q: The legacy .NET System.Configuration.Provider namespace & system

### ISSUE THREAD

**Issue by Kaelum** [dotnet/corefx#6998]
I'm not familiar with the new configuration system, but can it be used to perform the same functions that this legacy system does?  I've been heavily using this system for 14 years now, and it works really well, but most people don't even know it exists, or how to use it.

I have created several provider systems, with abstracted interfaces, creating a plug-n-play system for consumers.  I've mostly used it for persistence where one consumer may use SQL Server, another may use Oracle, and another may use web services, etc., but it can be used for anything.  It also works great for versioning support, where you may be required to support clients that require new data using an old data format.

If the new configuration system doesn't support something like this, is there a way to do this in .NET Core?

**Comment by joshfree** [comment]
related https://github.com/dotnet/corefx/issues/1348

**Comment by karelz** [comment]
@Eilon recommended [`Microsoft.Extensions.Configuration`](https://github.com/aspnet/Configuration/) in the issue linked above.
