### ISSUE TITLE
Where is httplistener? Is it renamed?

### ISSUE THREAD

**Issue by xdvarpunen** [dotnet/corefx#6999]
Hi,

I was checking dotnet and didn't find System.net.httplistener. Is it implemented? Is it renamed? Is it going to be implemented? 

-XDVarpunen

**Comment by svick** [comment]
This might be a duplicate of #3872.

**Comment by xdvarpunen** [comment]
@svick yes it, let me write it here clearly so anyone who seeks the answer for the same question can find answer here.

### `System.net.httplistener `== `Microsoft.AspNetCore.Server.Kestrel`

If I understood right the `System.net.httplistener` is not implemented anymore in .NET and separated off into ASP.NET with name KestrelHttpServer in namespaces `Microsoft.AspNetCore.Server.Kestrel` and `Microsoft.AspNetCore.Server.Kestrel.Https`.

**Comment by danmosemsft** [comment]
It is present now (though not shipped)

**Comment by lextm** [comment]
Please go to https://github.com/dotnet/corefx/issues/11793 for more details.
