### ISSUE TITLE
"Hello, World!" sample

### ISSUE THREAD

**Issue by xplicit** [dotnet/corefx#70]
Feature request: please add "Hello, World!" sample, which shows how to use .NET Core with user applications.

**Comment by stephentoub** [comment]
A "Hello, World" sample is now available at https://github.com/dotnet/corefxlab/tree/master/demos/CoreClrConsoleApplications/HelloWorld.  The blog post at http://blogs.msdn.com/b/dotnet/archive/2015/02/03/coreclr-is-now-open-source.aspx has a walkthrough of getting started.
