### ISSUE TITLE
Conditional BuildNative call for WCF support.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/corefx#7001]
WCF leverages the build process scripts from corefx, it aids our regular syncing if we can reduce the diffs between our versions of the same scripts, hence the following request.

In build.cmd would you consider wrapping the ":BuildNative" section with a repo check? Right now it just logs an error in WCF repo since we don't have any Native libraries to build, not a big deal it would just be nice to clean this up.

The check could perhaps be based on "git config remote.upstream.url"?

@zhenlan also suggested...
git remote -v | findstr corefx.git>0
And checking the error level

**Comment by ellismg** [comment]
My preference would be to gate this on the existence of the cmd we would call.  I will submit a PR.

**Comment by StephenBonikowsky** [comment]
Thank you.
