### ISSUE TITLE
WebUtility.UrlDecode fails to make a round-trip for surrogate characters

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#7036]
Discovered this while adding some tests for `WebUtility`. This prints `False`:

```csharp
string value = "\uD800";
string input = WebUtility.UrlEncode(value);
string output = WebUtility.UrlDecode(input);
Console.WriteLine(output == value);
```

Here's a console program on [.NET Fiddle](https://dotnetfiddle.net/DRBu6a) to demonstrate this so you can see it for yourself.

cc @davidsh @stephentoub

**Comment by JonHanna** [comment]
Garbage in, something valid out? Does it roundtrip correctly with valid surrogate pairs?

**Comment by jamesqo** [comment]
@JonHanna Yep, it seems to be working [just fine](https://dotnetfiddle.net/lqxNwq) with valid pairs.

**Comment by davidsh** [comment]
What happens on .NET Framework (Desktop)?  My guess is that the behavior is the same.

As we prep for RTM release, we are primarily focused on stability and app-compat with .NET Framework.  So, if this was a regression, we would prioritize this higher than if this was not a regression.

**Comment by JonHanna** [comment]
That seems correct to me. There's no way to turn a single surrogate into valid UTF-8, so either application-specific exception mechanisms should be used (which would be throwing an exception in .NET) or else U+FFFD encoded instead, as `0xEF, 0xBF,  0xBD`. Since URIs build on UTF-8 the result should hence be `%EF%BF%BD`

**Comment by JonHanna** [comment]
And desktop does the same.

**Comment by jamesqo** [comment]
You seem to be right, they seem to be translating to U+FFFD (which is supposed to represent an unknown/unrepresentable character according to the [Wikipedia page](https://en.wikipedia.org/wiki/Specials_(Unicode_block)) on Unicode). Based on that, it looks like this is intentional behavior, so I'll close this issue.

**Comment by JonHanna** [comment]
Are there tests enforcing this? It would be good to check on it across sole low-surrogates, sole high-surrogates, each of those along with non-surrogates, double-lows, double-highs and low followed by high.

**Comment by jamesqo** [comment]
@JonHanna Great suggestion! I've added tests for all the cases you've mentioned here: a4f7286.
