### ISSUE TITLE
System.IO.FileLoadException: Could not load file or assembly 'System.Collections.Concurrent, Version=4.0.12.0

### ISSUE THREAD

**Issue by onovotny** [dotnet/corefx#7038]
Trying to use the rc2-23918 libraries, when I try to run `dotnet test`, I get the following:

```
C:\users\oren\source\git\reactive-extensions-private\Rx.NET\Source\Tests.System.Reactive [dotnet-cli ≡ +0 ~9 -0 !]> dotnet test
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Collections.Concurrent, Version=4.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Xunit.Runner.DotNet.Program..ctor()
   at Xunit.Runner.DotNet.Program.Main(String[] args)
```

Here's the project.lock.json for it: https://gist.github.com/onovotny/8fe9a08ed4d8d7f7f0fb

**Comment by andschwa** [comment]
The package is bad:

```sh
$ monodis --assembly ~/.nuget/packages/System.Collections.Concurrent/4.0.12-rc3-23918/lib/netcore50/System.Collections.Concurrent.dll
Assembly Table
Name:          System.Collections.Concurrent
Hash Algoritm: 0x00008004
Version:       4.0.10.0
Flags:         0x00000001
PublicKey:     BlobPtr (0x0000105a)
```

**Comment by andschwa** [comment]
@onovotny You can get around this (with warnings) by taking a direct dependency on build 23911; it has 4.0.12.

**Comment by ericstj** [comment]
Package is not bad, we had to downgrade versions for desktop support.  It shouldn't be breaking with any stable packages.  You need to make sure you upgrade the pre-release dependencies in the full stack.

**Comment by andschwa** [comment]
What can I do to fix `dotnet-test-xunit`?

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Collections.Concurrent, Version=4.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Xunit.Runner.DotNet.Program..ctor()
   at Xunit.Runner.DotNet.Program.Main(String[] args)
```

**Comment by ericstj** [comment]
We need a new version of dotnet-test-xunit that is built on these packages.  /cc @livarcocc

**Comment by andschwa** [comment]
I gave it a quick go and didn't have much luck yet. Is there a feed that might have a more recent than three weeks ago build of Microsoft.Platform.Testing.Abstractions?

**Comment by livarcocc** [comment]
For test abstractions, we have a package from Saturday: https://dotnet.myget.org/feed/dotnet-cli/package/nuget/Microsoft.Extensions.Testing.Abstractions/1.0.0-beta-001887.

**Comment by andschwa** [comment]
Build 23922 resolved the problems I was having with this.

**Comment by ericstj** [comment]
This should be fixed now.
