### ISSUE TITLE
Cannot build System.Cryptography.(Cng|Csp).Tests projects

### ISSUE THREAD

**Issue by svick** [dotnet/corefx#7047]
I can't build projects System.Security.Cryptography.Cng.Tests and System.Security.Cryptography.Csp.Tests in msbuild or VS.

In System.Security.Cryptography.Cng.Tests, I get these errors:

>   TestData.cs(35,32): error CS0246: The type or namespace name 'CngKey' could not be found (are you missing a using directive or an assembly reference?)
  TestData.cs(41,32): error CS0246: The type or namespace name 'CngKey' could not be found (are you missing a using directive or an assembly reference?)
  TestData.cs(55,32): error CS0246: The type or namespace name 'CngKey' could not be found (are you missing a using directive or an assembly reference?)

In System.Security.Cryptography.Csp.Tests, the errors are similar:

> RSACryptoServiceProviderTests.cs(275,30): error CS0246: The type or namespace name 'CspParameters' could not be found (are you missing a using directive or an assembly reference?) 
RSACryptoServiceProviderTests.cs(277,37): error CS0246: The type or namespace name 'CspParameters' could not be found (are you missing a using directive or an assembly reference?)

In both cases, it looks like some issue with referencing the tested project.

**Comment by bartonjs** [comment]
I see this locally, too.  But `msbuild /p:OSGroup=Windows_NT` seems to work.  Definitely odd.
