### ISSUE TITLE
Debian 8.2 CI machines are missing libgssapi_krb5

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#7051]
We have a new dependency on `libgssapi_krb5`, we need to get this installed onto the machines running the Debian builds.

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/nativecomp_debian8.2_debug/705/console
````
Cannot find libgssapi_krb5 and System.Net.Security.Native cannot build without it. 
````

@ellismg

**Comment by ellismg** [comment]
Should be fixed now (and the builds I triggered manually got past the nativecomp step).
