### ISSUE TITLE
LoadInDefaultContext failing in CI on Windows outerloop

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7061]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win10_debug/128/consoleFull
```
12:24:22      System.Runtime.Loader.Tests.DefaultLoadContextTests.LoadInDefaultContext [FAIL]
12:24:22         System.IO.FileNotFoundException : Could not load file or assembly 'System.Runtime.Loader.Noop.Assembly, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
12:24:22         Stack Trace:
12:24:22               at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
12:24:22               at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
12:24:22               at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
12:24:22            d:\j\workspace\outerloop_win---0cba2915\src\System.Runtime.Loader\tests\DefaultContext\DefaultLoadContextTest.cs(73,0): at System.Runtime.Loader.Tests.DefaultLoadContextTests.LoadInDefaultContext()
12:24:22   Finished:    System.Runtime.Loader.DefaultContext.Tests
12:24:22   
12:24:22   === TEST EXECUTION SUMMARY ===
12:24:22      System.Runtime.Loader.DefaultContext.Tests  Total: 2, Errors: 0, Failed: 1, Skipped: 0, Time: 0.439s
```

**Comment by stephentoub** [comment]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win10_debug/131/consoleFull

**Comment by stephentoub** [comment]
Also failing on Windows 7:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win7_debug/127/consoleFull
```
14:25:36      System.Runtime.Loader.Tests.DefaultLoadContextTests.LoadInDefaultContext [FAIL]
14:25:36         System.IO.FileNotFoundException : Could not load file or assembly 'System.Runtime.Loader.Noop.Assembly, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
14:25:36         Stack Trace:
14:25:36               at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
14:25:36               at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
14:25:36               at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
14:25:36               at System.Runtime.Loader.Tests.DefaultLoadContextTests.LoadInDefaultContext()
```

**Comment by stephentoub** [comment]
And on Windows 8:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_windows_nt_debug/127/consoleFull

It's basically failing in all Windows outerloop runs.

**Comment by gkhanna79** [comment]
I will take a look at this today. I am not aware of any Loader change that would result in this. @stephentoub Do you happen to know since when this is failing?

**Comment by stephentoub** [comment]
> Do you happen to know since when this is failing?

I quickly looked back through the Jenkins log.  This run from the 18th passes, but it's also not running any loader tests:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_windows_nt_debug/120/consoleFull
```
02:20:29   Discovering: System.Runtime.Loader.DefaultContext.Tests
02:20:29   Discovered:  System.Runtime.Loader.DefaultContext.Tests
02:20:29   Info:        System.Runtime.Loader.DefaultContext.Tests has no tests to run
```
then the next run on the 19th fails:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_windows_nt_debug/121/consoleFull
```
02:23:38   Discovering: System.Runtime.Loader.DefaultContext.Tests
02:23:39   Discovered:  System.Runtime.Loader.DefaultContext.Tests
02:23:39   Starting:    System.Runtime.Loader.DefaultContext.Tests
02:23:39      System.Runtime.Loader.Tests.DefaultLoadContextTests.LoadInDefaultContext [FAIL]
02:23:39         System.IO.FileNotFoundException : Could not load file or assembly 'System.Runtime.Loader.Noop.Assembly, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
02:23:39         Stack Trace:
02:23:39               at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
02:23:39               at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
02:23:39               at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
02:23:39            d:\j\workspace\outerloop_win---069ccc6f\src\System.Runtime.Loader\tests\DefaultContext\DefaultLoadContextTest.cs(73,0): at System.Runtime.Loader.Tests.DefaultLoadContextTests.LoadInDefaultContext()
02:23:39   Finished:    System.Runtime.Loader.DefaultContext.Tests
```

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/commit/68de305a1483795bfe765f64cfa760d6dedaaa5d got checked in between those two runs.  So the reason there were "no tests to run" was because these are innerloop tests and innerloop tests weren't being run as part of the outerloop runs.  So this likely would have been failing well before this, maybe even from when they were originally checked in, but we weren't seeing it in the lab because they weren't actually being run.

**Comment by stephentoub** [comment]
cc: @Priya91

**Comment by gkhanna79** [comment]
@stephentoub Thanks. I am building the CoreFX repo to setup a repro for this. At the time of feature checkin, I did confirm that the tests were passing. Anyhow, I will take a look and update the thread.

**Comment by stephentoub** [comment]
> At the time of feature checkin, I did confirm that the tests were passing.

They're passing in CI for innerloop runs, just not outerloop runs.

**Comment by gkhanna79** [comment]
hmm.. In that case, what is the difference between CI inner loop and outerloop test runs? Don't they run the tests in the same manner?

Is there a way for me to to try to run just these tests as Outerloop on my machine?

**Comment by stephentoub** [comment]
I don't know.  Hence my cc of @Priya91  :smile:

**Comment by gkhanna79** [comment]
@Priya91 Can you please take an initial look at this failure since this does not look like a product issue?

**Comment by Priya91** [comment]
> Is there a way for me to to try to run just these tests as Outerloop on my machine?

@gkhanna79 You can use ```build.cmd /p:Outerloop=true /p:TestWithLocalLibraries=true, the difference in innerloop and outerloop is we use locally built libraries, instead of packages. So this error **may** happen in innerloop runs, once we update to the package version with the local libs..

**Comment by gkhanna79** [comment]
I had a chat with  @Priya91 and she will look into this as it sounds like a test infra issue and not a product issue.

CC @joshfree

**Comment by gkhanna79** [comment]
This will get fixed by Matt's change in https://github.com/dotnet/corefx/pull/7120.

**Comment by gkhanna79** [comment]
@MattGal Please port your PR (https://github.com/dotnet/corefx/pull/7120) to RC2 branch to fix this issue.

**Comment by MattGal** [comment]
Someone already ported my changeset with the fix in it yesterday.
