### ISSUE TITLE
Open-source System.Threading unit tests

### ISSUE THREAD

**Issue by nslottow** [dotnet/corefx#707]
Note: The implementation of this contract lives in mscorlib in the [coreclr](https://github.com/dotnet/coreclr) repository, but we are planning to put tests in this repo and test against the NuGet package produced by the coreclr repo.

**Comment by mellinoe** [comment]
Added with this commit:

https://github.com/dotnet/corefx/commit/464fc4487827d1bcd21efe5d02987484ce57e358#diff-4873cf6fdad06cfc868053a78dfddb87
