### ISSUE TITLE
Add performance tests for all collections

### ISSUE THREAD

**Issue by SunnyWar** [dotnet/corefx#7072]
I see performance tests for only List and SortedDictionary at the moment in the System.Collections solution.. Given that the collections are probably one of the most exercised body of code in the entire .Net Framework I expect that it be treated as a performance critical body of code and therefore have a complete suite of performance tests.

**Comment by joshfree** [comment]
@SunnyWar are you interested in grabbing this work item?

/cc @brianrob

**Comment by SunnyWar** [comment]
@joshfree I would be I don't have the time.

**Comment by kennycoc** [comment]
I can work on this if no one is yet

**Comment by joshfree** [comment]
Thanks @kennycoc.  Tagging this issue as grabbed by community 
/cc @brianrob

**Comment by colejackson** [comment]
@kennycoc, I would love to help out with this! I don't see a branch in you fork yet, Please let me know when you start work.

**Comment by kennycoc** [comment]
Yeah! I'm having a little trouble compiling right now, but I think I
figured out the issue is with my visual studio install, so I'm repairing it.

**Comment by kennycoc** [comment]
@colejackson I've created a branch for this issue in my fork, and am beginning work. 
I plan on just looking at the performance tests that have been done to get an idea of what's expected

**Comment by brianrob** [comment]
Thanks for creating these tests.  Much appreciated.

When you're looking at other tests, one thing to keep in mind is that some do a very small amount of work, while others do more.  Please do the latter - make sure that there is enough code inside the loop iteration to dominate the harness.  I've had good success when each iteration takes around 10 ms.

I'd also recommend testing the noise level of the tests by running them multiple times and comparing the results (xunit.performance.analysis.exe can do this).

**Comment by ianhays** [comment]
@kennycoc are you still working on this?

**Comment by CodeTherapist** [comment]
Is that still open? If so, I would like to add the following perf tests:

- [ ] Stack
- [ ] Queue
- [ ] LinkedList

- [ ] SortedList
- [ ] SortedDictionary
- [ ] SortedSet

**Comment by adamsitnik** [comment]
I have done  that in https://github.com/dotnet/performance/pull/92 

The benchmarks are now available at https://github.com/dotnet/performance/tree/master/src/benchmarks/micro/corefx/System.Collections
