### ISSUE TITLE
Dependency conflict warning from buildtools on clean build

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7079]
```
corefx>git clean -xdf
corefx>build.cmd
Installing dotnet cli...
Restoring BuildTools version 1.0.25-prerelease-00208...
Initializing BuildTools ...
c:\Users\stoub\Source\repos\corefx\packages\Microsoft.DotNet.BuildTools\1.0.25-prerelease-00208\lib\tool-runtime\project.json(37,37): warning NU1012: Dependency conflict. Microsoft.Build 0.1.0-preview-00017 expected System.Diagnostics.Contracts >= 4.0.1-rc2-23712 but got 4.0.0
c:\Users\stoub\Source\repos\corefx\packages\Microsoft.DotNet.BuildTools\1.0.25-prerelease-00208\lib\tool-runtime\project.json(37,37): warning NU1012: Dependency conflict. Microsoft.NETCore.Console 1.0.0-rc2-23907 expected System.Diagnostics.Contracts >= 4.0.1-rc2-23907 but got 4.0.0
```
cc: @weshaggard, @ericstj

**Comment by ericstj** [comment]
This should be a buildtools issue.

**Comment by ericstj** [comment]
Bug is here: https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.json#L37
/cc @joperezr

**Comment by joperezr** [comment]
@ericstj we have a lot of direct dependencies on the tool-runtime project.json today because there were broken dependency trees before so just depending on the Meta package wouldn't pull out the right dependencies for some libraries. Do you know if this has been fixed so that we can clean up the project.json?

**Comment by ericstj** [comment]
This one would have never been helping anything.  Here's what I reccomend:
get tool-runtime restoring as **downgrade-clean** no warnings about downgrades.  Then you can trim any direct references that are already occurring indirectly as can be seen from the project.lock.json.  As you remove direct references you should be able to diff the lock file to make sure you're getting the same graph.
