### ISSUE TITLE
Open-source System.Text.Encoding unit tests

### ISSUE THREAD

**Issue by nslottow** [dotnet/corefx#708]
Note: The implementation of this contract lives in mscorlib in the [coreclr](https://github.com/dotnet/coreclr) repository, but we are planning to put tests in this repo and test against the NuGet package produced by the coreclr repo.

**Comment by tarekgh** [comment]
Venkat already ported the encoding tests so he may close or add any missing item here

**Comment by venkat-raman251** [comment]
Why are there 2 items to track this? isn't this the same as #859 ?

**Comment by tarekgh** [comment]
it looks 2 people opened them in different times

**Comment by venkat-raman251** [comment]
can I close this as duplicate?

**Comment by tarekgh** [comment]
before closing, could you look at the tests under Unit tests and pick whatever not covered from there? if you see we already covered such cases in the unit tests then just close this one as duplicate

**Comment by venkat-raman251** [comment]
Duplicate. #859
