### ISSUE TITLE
Write a test for PROCESS_QUERY_LIMITED functionality

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#709]
Per #303 we have some debt here we need to get tested.  It's not clear the best strategy here.  Should this be an inner loop test?  Does the test need to run elevated somehow or can we run at regular permissions and create a low integrity process?

**Comment by Giorgi** [comment]
@ellismg PROCESS_QUERY_LIMITED_INFORMATION Is used in [GetProcessTimes](https://github.com/dotnet/corefx/blob/7da9e8de780a46459daa8bd4a23a83f12b4f7166/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Windows.cs#L612) too so it's probably also missing a test

**Comment by Priya91** [comment]
This is covered by tests now, through process times tests.
