### ISSUE TITLE
System.IO.UnixFileSystem.MoveFile throwing `Access to the path is denied.` in Docker on Mac

### ISSUE THREAD

**Issue by ctaggart** [dotnet/corefx#7091]
I created a docker image, so this should be easy to create, but the docker host needs to be OS X. When the docker host is Linux, this error does not occur, which leads me to believe it is something wrong with [System.IO.UnixFileSystem.MoveFile](https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System/IO/UnixFileSystem.cs). It is being called from the latest `dotnet` 1.0.0-dev-001806 executable [from here I believe](https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-compile-fsc/Program.cs). cc @enricosada

Steps to reproduce on Mac OS X:
```
git clone https://github.com/ctaggart/visualfsharp-docker.git
cd visualfsharp-docker
docker run --rm -ti -v $PWD/template:/root/template ctaggart/visualfsharp:1.0.0-alpha-160318
cd template
./build.sh
``` 

It will fail with:
```
Unhandled Exception: System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.UnixFileSystem.MoveFile(String sourceFullPath, String destFullPath)
   at Microsoft.DotNet.Tools.Compiler.Fsc.CompileFscCommand.Run(Stringrgs)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(Stringrgs)
   at Microsoft.DotNet.Cli.Program.Main(Stringrgs)
/usr/share/dotnet/bin/dotnet compile-fsc @/root/template/obj/Debug/dnxcore50/dotnet-compile.rsp returned Exit Code 134

Compilation failed.
```

The compilation actually succeeds and then `dotnet` tries to move the files because `fsc` didn't used to support compiling executables with a `dll` extension like `dotnet` wants. That hack can probably be removed, but I think there is still a bug dealing with `MoveFile`.

**Comment by stephentoub** [comment]
> which leads me to believe it is something wrong with System.IO.UnixFileSystem.MoveFile

That implementation is the same on both Linux and OS X, and this failure would simply mean that libc function returned either EACCES or EPERM from the call.  Most likely it's actually a permissions issue with the deployment.  What are the source and destination paths, and have you confirmed that the permissions are amenable to this?

cc: @piotrpMSFT

**Comment by stephentoub** [comment]
Actually, EPERM could mean one other thing: that you're unable to create hard links.  Are you able to successfully use ```ln``` manually to create a hard link?  If that's not working, this could be something we need to deal with in the MoveFile implementation.  Right now we try to link and then we delete the old name; this is much more efficient then copying the file and deleting the old one.  But we do support the latter as a fallback in cases where we know link will fail, such as moving across volumes.  We could potentially add CopyFile as a fallback in the case of EPERM as well, if that's the root of the problem.

**Comment by ctaggart** [comment]
I am not able to successfully use ln manually to create a hard link when I use Docker with the Parallels driver. I logged bug https://github.com/Parallels/docker-machine-parallels/issues/45 . The default VirtualBox drivers supports creating hard links, so I'll switch to it.

**Comment by stephentoub** [comment]
Thanks for confirming.  Given that, my fix #7094 should address this for you, at least making it work, though it'll still be more expensive than if hard links worked, as we'll end up doing the copy rather than the link.

**Comment by ctaggart** [comment]
Thanks @stephentoub. It turns out I was wrong. It is not working with docker volumes on VirtualBox either, so I need this fix for local development the uses docker.

**Comment by stephentoub** [comment]
> so I need this fix for local development the uses docker.

Can you try out the fix and let me know whether it indeed addresses the problem?

**Comment by ctaggart** [comment]
@stephentoub Happy to, but how do you recommend that I do that? Is there a build that contains the fix? I am currently using `dotnet-ubuntu-x64.1.0.1.001806.tar.gz`.
https://github.com/ctaggart/visualfsharp-docker/blob/master/.travis.yml#L18

**Comment by stephentoub** [comment]
Thanks.  Hmm. You can try overwriting your local System.IO.FileSystem.dll with one that contains the fix (saving the current one you have to put back after in case something goes wrong).  You could either build one locally based on the source currently checked in to master in corefx, or you could pick up tonight's build tomorrow from MyGet (https://dotnet.myget.org/gallery/dotnet-core).  It'll be a bit of surgery, but hopefully it'll "just work".  My fear is that build of CLI you're using might be old enough that other things might have changed to make this System.IO.FileSystem.dll incompatible, but it should be easy to try and see.

**Comment by ctaggart** [comment]
OK. I'll try it tomorrow. https://dotnet.myget.org/gallery/dotnet-core reports that the last build 21 hours ago was v4.0.1-rc3-23921. The `System.IO.FileSystem.dll` has this metadata:
[assembly: AssemblyVersion("4.0.1.0")]
[assembly: AssemblyFileVersion("4.6.23901.00")]
So it looks to be 20 builds behind. Possibly 20 days. Hopefully not too incompatible.

**Comment by stephentoub** [comment]
@ctaggart, any luck?  thanks!

**Comment by ctaggart** [comment]
No luck yet. I get this error. Did i download the and unzip the right file?

```
root@ddccdde1db3f:~/template# dotnet restore --configfile $PWD/NuGet.Config -v Minimal
error: Method not found: 'Void System.IO.Directory.Delete(System.String, Boolean)'.
Method not found: 'Boolean System.IO.Directory.Exists(System.String)'.
```

```
docker run --rm -ti -v $DIR/template:/root/template ctaggart/visualfsharp
apt-get -qq -y install unzip
curl -L https://www.myget.org/F/dotnet-core/api/v2/package/System.IO.FileSystem/4.0.1-rc3-23922 -o System.IO.FileSystem.4.0.1-rc3-23922.nupkg
unzip -jo System.IO.FileSystem.4.0.1-rc3-23922.nupkg ref/netstandard1.3/System.IO.FileSystem.dll -d /usr/share/dotnet/bin/
cd template
dotnet restore --configfile $PWD/NuGet.Config -v Minimal
```

fyi, the contents of the nupkg:
```
root@12038f645187:~# unzip -l System.IO.FileSystem.4.0.1-rc3-23922.nupkg 
Archive:  System.IO.FileSystem.4.0.1-rc3-23922.nupkg
  Length      Date    Time    Name
---------  ---------- -----   ----
      518  2016-03-22 00:54   _rels/.rels
     2286  2016-03-22 00:54   System.IO.FileSystem.nuspec
     9323  2016-03-22 00:54   dotnet_library_license.txt
     1617  2016-03-22 00:54   ThirdPartyNotices.txt
        0  2016-03-22 00:54   lib/MonoAndroid10/_._
        0  2016-03-22 00:54   lib/MonoTouch10/_._
    22744  2016-03-22 00:54   lib/net46/System.IO.FileSystem.dll
        0  2016-03-22 00:54   lib/xamarinios10/_._
        0  2016-03-22 00:54   lib/xamarinmac20/_._
        0  2016-03-22 00:54   lib/xamarintvos10/_._
        0  2016-03-22 00:54   lib/xamarinwatchos10/_._
        0  2016-03-22 00:54   ref/MonoAndroid10/_._
        0  2016-03-22 00:54   ref/MonoTouch10/_._
    22744  2016-03-22 00:54   ref/net46/System.IO.FileSystem.dll
    29904  2016-03-22 00:54   ref/netstandard1.3/System.IO.FileSystem.dll
   283171  2016-03-22 00:54   ref/netstandard1.3/System.IO.FileSystem.xml
   317970  2016-03-22 00:54   ref/netstandard1.3/de/System.IO.FileSystem.xml
   313516  2016-03-22 00:54   ref/netstandard1.3/es/System.IO.FileSystem.xml
   313639  2016-03-22 00:54   ref/netstandard1.3/fr/System.IO.FileSystem.xml
   309991  2016-03-22 00:54   ref/netstandard1.3/it/System.IO.FileSystem.xml
   342512  2016-03-22 00:54   ref/netstandard1.3/ja/System.IO.FileSystem.xml
   318403  2016-03-22 00:54   ref/netstandard1.3/ko/System.IO.FileSystem.xml
   411715  2016-03-22 00:54   ref/netstandard1.3/ru/System.IO.FileSystem.xml
   271386  2016-03-22 00:54   ref/netstandard1.3/zh-hans/System.IO.FileSystem.xml
   271826  2016-03-22 00:54   ref/netstandard1.3/zh-hant/System.IO.FileSystem.xml
        0  2016-03-22 00:54   ref/xamarinios10/_._
        0  2016-03-22 00:54   ref/xamarinmac20/_._
        0  2016-03-22 00:54   ref/xamarintvos10/_._
        0  2016-03-22 00:54   ref/xamarinwatchos10/_._
      634  2016-03-22 00:54   [Content_Types].xml
     1027  2016-03-22 00:54   package/services/metadata/core-properties/9e0913036651416fb85a3edf50441751.psmdcp
---------                     -------
  3244926                     31 files
```

**Comment by stephentoub** [comment]
Ah, yeah, you want this one:
https://dotnet.myget.org/F/dotnet-core/api/v2/package/runtime.unix.System.IO.FileSystem/4.0.1-rc3-23922
and specifically the file:
\runtimes\unix\lib\netstandard1.3\System.IO.FileSystem.dll

**Comment by ctaggart** [comment]
That makes more sense. It works! Successfully compiled the Hello World F# console app from a VirtualBox Docker volume and ran it.

```
docker run --rm -it -v $PWD/template:/root/template docker.io/ctaggart/visualfsharp:1.0.0-alpha-160318
apt-get -qq -y install unzip
curl -L https://dotnet.myget.org/F/dotnet-core/api/v2/package/runtime.unix.System.IO.FileSystem/4.0.1-rc3-23922 -o runtime.unix.System.IO.FileSystem.4.0.1-rc3-23922.nupkg
unzip -jo runtime.unix.System.IO.FileSystem.4.0.1-rc3-23922.nupkg runtimes/unix/lib/netstandard1.3/System.IO.FileSystem.dll -d /usr/share/dotnet/bin/
cd template
./build.sh
```

**Comment by stephentoub** [comment]
Excellent!  Thanks, @ctaggart!
