### ISSUE TITLE
Port Tracing

### ISSUE THREAD

**Issue by eschneider999** [dotnet/corefx#7098]
Every system I have worked on uses tracing, the integration with visual studio is very helpful also.

https://msdn.microsoft.com/en-us/library/zs6s4h68(v=vs.110).aspx

**Comment by stephentoub** [comment]
What kind of tracing are you asking for?  EventSource is the recommended way to do tracing, and it is exposed in .NET Core:
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Tracing/ref/System.Diagnostics.Tracing.cs
TraceSource is also exposed:
https://github.com/dotnet/corefx/tree/master/src/System.Diagnostics.TraceSource

**Comment by eschneider999** [comment]
That sounds like what I'm after. I'll give it a try tonight, thanks!

Is there a list of all the .Net Core libraries?

**Comment by stephentoub** [comment]
There's a folder for each of them here:
https://github.com/dotnet/corefx/tree/master/src
@richlander or @terrajobst can probably share if there's an official list somewhere.

**Comment by eschneider999** [comment]
pre-release tough, any idea how stable it is?

**Comment by terrajobst** [comment]
> Is there a list of all the .Net Core libraries?

Unfortunately not. I think the best way would be http://packagesearch.azurewebsites.net and http://dotnet.github.io/api/index.html.

> pre-release tough, any idea how stable it is?

.NET Core all up has a go live license, so pretty stable. We don't churn the code itself much; most churn comes from making it cross-platform and NuGet packaging. The functionality itself is mostly mature as the rest of the .NET stack. That being said, bugs can always manifest themselves in crazy ways.
