### ISSUE TITLE
Behaviour of `Quaternion.CreateFromAxisAngle` when axis is not a unit vector

### ISSUE THREAD

**Issue by CodesInChaos** [dotnet/corefx#71]
The resulting quaternion depends on the length of `axis`. This does not describe a rotation and thus does not match the documentation.

There are a few ways to handle this issue:

1. Normalize `axis`, but this incurs a performance hit
2. Add a precondition that `axis.Length()` ≈ 1.

    But enforcing that pre-condition is about as expensive as 1), so it'd probably need to be a documentation-only precondition. Unfortunately this means that consumers will rely on the current behaviour even if it's undocumented, so I don't think that this is a good solution.
3. Document the current behaviour

----

Just for convenience, the relevant source code:

    /// <summary>
    /// Creates a Quaternion from a vector and an angle to rotate about the vector.
    /// </summary>
    /// <param name="axis">The vector to rotate around.</param>
    /// <param name="angle">The angle, in radians, to rotate around the vector.</param>
    /// <returns>The created Quaternion.</returns>
    public static Quaternion CreateFromAxisAngle(Vector3 axis, float angle)
    {
        Quaternion ans;

        float halfAngle = angle * 0.5f;
        float s = (float)Math.Sin(halfAngle);
        float c = (float)Math.Cos(halfAngle);

        ans.X = axis.X * s;
        ans.Y = axis.Y * s;
        ans.Z = axis.Z * s;
        ans.W = c;

        return ans;
    }

**Comment by jasonwilliams200OK** [comment]
This is fixed by https://github.com/dotnet/corefx/pull/3649.
