### ISSUE TITLE
Outerloop OSX fails with nuget package restore

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#7104]
```
20:27:39   [20:32:06.64] Restoring all packages...
20:27:58 EXEC : error : Could not find file '/Users/dotnet-bot/j/workspace/dotnet_corefx/outerloop_osx_debug/tempHome/.local/share/NuGet/v3-cache/0b99e17097bea891c4215989667b88d90c9f7540$_F_dotnet-core_api_v3_index.json/nupkg_runtime.any.System.IO.4.1.0-rc3-23918.dat'. [/Users/dotnet-bot/j/workspace/dotnet_corefx/outerloop_osx_debug/build.proj]
20:27:58 
/Users/dotnet-bot/j/workspace/dotnet_corefx/outerloop_osx_debug/build.proj(60,5): error MSB3073: The command ""/Users/dotnet-bot/j/workspace/dotnet_corefx/outerloop_osx_debug/Tools/dotnetcli/bin/dotnet" restore --packages "/Users/dotnet-bot/j/workspace/dotnet_corefx/outerloop_osx_debug/packages" --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://www.nuget.org/api/v2/ "/Users/dotnet-bot/j/workspace/dotnet_corefx/outerloop_osx_debug/src" "/Users/dotnet-bot/j/workspace/dotnet_corefx/outerloop_osx_debug/pkg"" exited with code -1.
20:27:58   [20:32:19.04] Restoring all packages...Done.
```

**Comment by joshfree** [comment]
@mellinoe is investigating this one currently

**Comment by mellinoe** [comment]
I'm getting through the build now, but I was having issues where my open files limit was too low, which was causing lots of package restore failures. Any chance this is the same problem in the CI? Jenkins seems to be too slow to open any logs right now, but I don't think this information is in the logs anyways. Is there any way to look at `init-tools.log`, for example, from the outer loop runs?

@mmitche Are we setting the ulimit on our OSX machines to anything particular?

**Comment by mmitche** [comment]
@stephentoub Was talking about this just this morning.

**Comment by stephentoub** [comment]
The default on OS X is ridiculously low, 256 IIRC (ulimit -n).  If this is causing package restore failures from NuGet / cli, potentially those tools should configure the machine and/or encourage users to increase  the limit.  And we could increase the limit on our lab machines.

**Comment by mellinoe** [comment]
I'm 99% sure that is what caused my restore failures locally. After running `ulimit -n 9999`, restore successfully completed on the next try. Init-tools.log also had a few messages about "Too many open files" before changing the limit. It's hard to say whether that's the same problem that's happening in CI (unless we can see the log file), but I wouldn't be surprised if it was.

**Comment by mellinoe** [comment]
@Priya91 and I checked one of the machines and `ulimit -n` printed back `256`, which seems to confirm some suspicions. We were able to run init-tools.sh (which restores a bunch of packages) after setting the limit to 4000. I'll go through the rest of the machines and add a similar configuration.

**Comment by ellismg** [comment]
IIRC, CLI/NuGet was making some changes to do less work in parallel on OSX to prevent running into these issues.

**Comment by mellinoe** [comment]
I upped the open-file limit on our build machines, except for two of them, which I wasn't able to access yet. The runs this morning both failed still, though. One of the runs was on a machine that wasn't updated, but the other SHOULD have had the fix on it. I'm logging on to that machine to see what the deal is.

**Comment by mellinoe** [comment]
I was able to log in and restore all of the packages on the machine that failed, so let's wait and see what happens in the next run...

**Comment by dagood** [comment]
What fix did you apply to the servers for `ulimit`?

**Comment by mellinoe** [comment]
I just increased the limit, roughly following the example from [here](http://unix.stackexchange.com/questions/108174/how-to-persist-ulimit-settings-in-osx-mavericks). Then I restarted the machines.

**Comment by joshfree** [comment]
> The runs this morning both failed still, though. One of the runs was on a machine that wasn't updated, but the other SHOULD have had the fix on it.

Note even after this issue is fixed for OS X, there's still this 2nd set of Mac OS X outerloop test failures: https://github.com/dotnet/corefx/issues/7126.

**Comment by mellinoe** [comment]
The dotnet restore issue should not pop up again, I have finished patching all of the machines. I'll wait to close this issue until we get a couple more runs that get past restore.

**Comment by joshfree** [comment]
@mmitche are you still seeing general dotnet restore hangs?

**Comment by stephentoub** [comment]
@joshfree, yes, many runs are hanging because of this.

**Comment by joshfree** [comment]
Related https://github.com/NuGet/Home/issues/2416

**Comment by mellinoe** [comment]
I don't think I've seen the OSX-specific restore failure since updating the machine configurations. So I think the problem this issue was tracking has been fixed, at the very least. We are still seeing restore hanging in general, but that is across all OS's, not just OSX.

**Comment by joshfree** [comment]
coreclr, corefx, and wcf repos have been updated with CLI-beta-02111 which contains the NuGet 60 second timeout fix @ https://github.com/NuGet/NuGet.Client/pull/390 

/cc @mmitche @dagood
