### ISSUE TITLE
Temporarily revert implementation assembly version change

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#7114]
Revert the change from https://github.com/dotnet/corefx/pull/6902/commits/6ad2e34491d3cd3a078c225f98b2c49268db81e1 as it applies to implementation assemblies to allow folks time to recompile against the newer refs without hitting ref-def mismatches at runtime.

**Comment by ericstj** [comment]
Workaround is in place with https://github.com/dotnet/corefx/commit/0f268ed1079c182d71cdf49cde3f339a01d67863

**Comment by ericstj** [comment]
Moving to RTM.  This is tracking undoing the change above.

**Comment by joshfree** [comment]
What's the timeline for this?

**Comment by ericstj** [comment]
I don't think we're going to do it.  It risks breaking folks that have built against earlier package versions and its really just a cleanup fix.

I'll remove the AssemblyVersionTransition property from the dev branch and add a comment about why the impl doesn't match ref.

**Comment by ericstj** [comment]
We decided not to do this.  I'll use this to track cleaning up the property from projects.
