### ISSUE TITLE
96 System.Text.Encodings.Web.Tests failing in outerloop on OSX and Ubuntu14.04

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7126]
e.g.
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_osx_release/46/consoleText
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_osx_debug/49/consoleText

Mostly due to NullReferenceExceptions, e.g.
```
     Microsoft.Framework.WebEncoders.UnicodeEncoderBaseTests.Encode_NullInput_ReturnsNull [FAIL]
        System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
              at System.Text.Unicode.UnicodeHelpers.CreateDefinedCharacterBitmap()
              at System.Text.Internal.AllowedCharactersBitmap.ForbidUndefinedCharacters()
              at Microsoft.Framework.WebEncoders.UnicodeEncoderBaseTests.Encode_NullInput_ReturnsNull()
```
The pages take a while to load, in part due to one of the tests incurring 65K NullReferenceExceptions, each of which is output in the log.

**Comment by joshfree** [comment]
@KrzysztofCwalina can you get a fix in for this today?

**Comment by KrzysztofCwalina** [comment]
Fixed by https://github.com/dotnet/corefx/commit/fefbfb1b70686234a7e1ae25b32e5027b2be4aa8
