### ISSUE TITLE
Visual Studio occasionally disregards disabled NuGet restore

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#7130]
I haven't been able to completely repro this one, but VisualStudio is occasionally disregarding the unchecked "Allow NuGet to download missing packages" option.  IOW, the option is unchecked, but the build process still attempts to dial out to the server.

This happens consistently when I'm away from "home" (when I have no internet connection), but never when I'm at "home" and try to repro (via things like disconnecting from the wireless internet).  I _thought_ I had managed to with the following steps on my Windows 10 machine, but haven't gotten it to do it a second time:

 1. Make sure both options under "package restore" are checked.
 2. Build the project.  (Should dial out)
 3. Exit VisualStudio
 4. Set the computer to Sleep
 5. Wake computer
 6. Start VisualStudio
 7. Uncheck "Allow NuGet...."
 8. Attempt to build project.

When I'm "away" it still attempts to dial out, which of course results in a failed build (because it can't contact the server).  This is a little bizarre, because in trying to repro this I attempted to do things like give it permission to dial out and turn of my network... and it completed fine.  So no clue what I'm running into here.  My best guess is it may be something in the timing between steps 4 and 5 (ie, travel time).
It's also a little strange, because I can build okay via command line by disabling restore there, but VisualStudio will still refuse to honor the unchecked option (which means I have a terrible time in-editor).

**Comment by Clockwork-Muse** [comment]
...Just hit it again, but still can't repro.  Stuff I've done in VS before first offline build when this happens:

 - _nothing_ (just build/rebuild)
 - Change project file (ie, new test file)
 - Change method signature/attributes/declared variables.

So yeah, still mystified

**Comment by abpiskunov** [comment]
@Clockwork-Muse  what is your project type? Also what is exact VS and Update version?

**Comment by Clockwork-Muse** [comment]
@abpiskunov - This has happened to both PLINQ and Threading.Tasks (so regular .csproj), so I'm assuming it would affect all of the corefx projects.
VS is 10.0.24720.00 Update 1

It can also occur if I build the project, don't shut down VS, sleep the computer, then wake and try to build again.  Trying to rebuild via command line (with `/p:RestorePackages=false`) was complaining about not finding the correct version of System.Runtime.InteropServices.RuntimeInformation (I think - it's behaving now)

**Comment by joshfree** [comment]
@Clockwork-Muse I've moved this issue to https://github.com/NuGet/Home/issues/2414 so the right folks will be able to see this.
