### ISSUE TITLE
Need to copy xunit.runner.utility.desktop.dll in order to run performance tests

### ISSUE THREAD

**Issue by khdang** [dotnet/corefx#7141]
For some reasons, l have to copy xunit.runner.utility.desktop.dll to run the perf test on CoreClr.

I have tried getting a new clone of corefx, do build.cmd and then run serialization performance tests, but I still see the complain that xunit.runner.utility.desktop.dll cannot be loaded.

e.g. I ran: 
```
msbuild src\System.Runtime.Serialization.Xml\tests\System.Runtime.Serialization.Xml.Tests.csproj /t:rebuildandtest /p:Performance=true /p:Configuration=Windows_Release
```

I saw this error:

``` 
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'xunit.runner.utility.desktop, Version=2.1.0.3179, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies. The system cannot f
  ind the file specified.
     at Microsoft.Xunit.Performance.ProgramCore.Run(String[] args)
     at Microsoft.Xunit.Performance.Program.Main(String[] args)
```

If I copy corefx\packages\Microsoft.DotNet.xunit.performance.runner.Windows\1.0.0-alpha-build0029\tools\xunit.runner.utility.desktop.dll to dnxcore50 directory and run the msbuild command again it works fine.
I'm wondering if I'm missing anything here.

**Comment by davmason** [comment]
@dsgouda It looks like all the performance tests are broken from running manually. Do you know if this is related  to #6972

**Comment by MattGal** [comment]
Having extreme network funkiness right now, but can you check whether your execution is in the context of corerun.exe?  The only way this DLL should be necessary is if you're running against desktop Framework.

**Comment by khdang** [comment]
It appears that the the test is run with a xunit.performance.run.exe command, which target is ".NETFramework,Version=v4.6". Any ideas how do can run performance test in CoreClr context?

```
e:\Open\corefx\bin/tests/Windows_NT.AnyCPU.Release/System.Runtime.Serialization.Json.Tests/dnxcore50/xunit.performance.run.exe System.Runtime.Serialization.Json.Tests.dll -trait Benchmark=true -runnerhost e:\Open\corefx\bin/tests/Windows_NT.AnyCPU.Release/System.Runtime.Serialization.Json.Tests/dnxcore50/CoreRun.exe -runner xunit.console.netcore.exe -runid System.Runtime.Serialization.Json.Tests.dll-WindowsCore -verbose
```

**Comment by mellinoe** [comment]
The runner itself is a .NET Framework application, but the program being monitored (and perf information being gathered from) is still be a CoreCLR program:

````
-runnerhost e:\Open\corefx\bin/tests/Windows_NT.AnyCPU.Release/System.Runtime.Serialization.Json.Tests/dnxcore50/CoreRun.exe

-runner xunit.console.netcore.exe
````

**Comment by mellinoe** [comment]
As for why xunit.runner.utility.desktop.dll needs to be copied over, from my memory I think it is because the "outer runner" (i.e. the .NET Framework application) needs to understand which tests are going to be run by the "inner runner" (the CoreCLR xunit runner), and it needs that xunit assembly to do the analysis.

**Comment by khdang** [comment]
So should the xunit.runner.utility.desktop.dll be copied automatically to dnxcore50 folder? or this is only done in the lab machine and running on dev machine would require copying that file manually?

**Comment by mellinoe** [comment]
Yes, it should be. This should have been happening automatically, perhaps something in buildtools has regressed it. It should be part of [this target](https://github.com/dotnet/buildtools/blob/9a879e24e41e6e82930e2f7a09efb7c185caf410/src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets#L25) in buildtools.

**Comment by dsgouda** [comment]
Thanks @mellinoe will take a look

**Comment by dsgouda** [comment]
This should be resolved by a fix submitted here https://github.com/dotnet/buildtools/pull/591
