### ISSUE TITLE
Allow a way to specify native shim dependencies for libs in build targets.

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#7146]
**Repro:**
Using build.sh without `TestWithLocalLibraries=true` will cause builds to fail, if the correct package version with the shim update is not used.

Currently, we are copying all the native shim libs built locally to be used while running tests (when setting `TestWithLocalLibraries=true`). We need a way to just copy over just the required shims, so that, there is no need to keep updating the packages for every shim update.

**Comment by danmosemsft** [comment]
@Priya91 is this one still relevant? if not pls close. if so is it necessary for 2.0 (pls change milestone if not)

**Comment by Priya91** [comment]
We required this in the old test framework, where we were using packages to test against. With the current infra, we should be using the latest source changes for the native bits as well. So this issue doesn't seem to be relevant anymore. @weshaggard Can you confirm?

**Comment by weshaggard** [comment]
Correct this is no longer relevant.
