### ISSUE TITLE
ASCIIEncoding has inconsistent parameter names from base class and other encodings

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#7148]
`ASCIIEncoding` overrides `Encoding`
It has inconsistent parameter names for methods taking a string

### Encoding.cs
```
public virtual int GetByteCount(String s);
public virtual int GetBytes(String s, int charIndex, int charCount, byte[] bytes, int byteIndex);
public override unsafe String GetString(byte[] bytes, int index, int count);
```

### ASCIIEncoding.cs
```
public override int GetByteCount(String chars);
public override int GetBytes(String chars, int charIndex, int charCount, byte[] bytes, int byteIndex);
public override unsafe String GetString(byte[] bytes, int byteIndex, int byteCount);
```

These are pretty insignificant nits, but are currently blocking progress for adding these to `EncodingHelpers.cs` (similar to PR #7145) as the parameter names are different

I'm really not sure if changing the parameter names in `ASCIIEncoding.cs` is a breaking change.
- Other encoding sub classes (e.g. UnicodeEncoding, UTF7Encoding, UTF8Encoding) have `string s` in their function signatures, so there is more reason for consistency

I can submit a PR over at coreclr if this is deemed acceptable to fix. Otherwise I can remove the parameter names for some EncodingHelper tetss

/cc @stephentoub  @tarekgh

**Comment by tarekgh** [comment]
I don't think we can change the names. changing methods parameter names can break compatibility with VB.

**Comment by tarekgh** [comment]
we can workout the tests to make it work.
