### ISSUE TITLE
Implicit windows or UNC uris doesn't parse query or fragment

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#7154]
### Implicit windows file

```
Uri uri = new Uri("C:/path?query#fragment");
uri.AbsolutePath; // "C:/path%3Fquery%23fragment"
uri.Query; // ""
Uri.Fragment; // ""
```
### Explicit windows file

```
Uri uri = new Uri("file:///C:/path?query#fragment");
uri.AbsolutePath; // "C:/path"
uri.Query; // "?query"
Uri.Fragment; // "#fragment"
```
### Implicit UNC file

```
Uri uri = new Uri(@"\\host\path?query#fragment");
uri.AbsolutePath; // "/path%3Fquery%23fragment"
uri.Query; // ""
Uri.Fragment; // ""
```
## Explicit UNC file

```
Uri uri = new Uri(@"file://\\host/path?query#fragment");
uri.AbsolutePath; // "/path"
uri.Query; // "?query"
Uri.Fragment; // "#fragment"
```
## Problem description
- Clearly, there is an inconsistency between parsing of implicit and explicit windows files.
- The query and fragment are escaped in an implicit file, so are not parsed, unlike in explicit files
## Solution
- This may be by design, but I don't see any mention of this in the MSDN docs.
- Furthermore, it seems that this is a bug, as there certainly are many use cases for creating implicit Uris. This may actually deter the impetus for fixing, as this breaking change affects many consumers.
- The solution, a breaking change, would be to correctly the query and fragment of implicit files in the same manner as explicit files.

/cc @davidsh (sorry that I found another breaking change bug!)

**Comment by davidsh** [comment]
We are aware of issues with the System.Uri class especially in the areas of implicit file:// scheme which is not even covered fully in the RFC's.

It is highly unlikely we will make any fixes to this which are breaking changes.

**Comment by hughbe** [comment]
Ach that's disappointing, I'll work around it.

Seems like System.Uri is in a bit of a mess, right? Are there plans for a new replacement to avoid backcompat issues?

**Comment by hughbe** [comment]
This is unlikely to be fixed, too breaking. I'm going to close this to avoid wasting time on discussion
