### ISSUE TITLE
TestCtor_CharPtr failing on Unix sporadically

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7155]
This test has started failing randomly in the past day.  I've seen it now on both CentOS and OpenSUSE.
e.g. http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/centos7.1_debug_tst/999/console
```
12:19:35    StringTests.TestCtor_CharPtr(valueArray: ['a', 'b', 'c', 'd', 'e', ...], expected: "abcdefgh") [FAIL]
12:19:35       Assert.Equal() Failure
12:19:35                         ↓ (pos 8)
12:19:35       Expected: abcdefgh
12:19:35       Actual:   abcdefgh
12:19:35                         ↑ (pos 8)
12:19:35       Stack Trace:
12:19:35             at StringTests.TestCtor_CharPtr(Char[] valueArray, String expected)
```
https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/String.cs#L24

**Comment by stephentoub** [comment]
@wtgodbe, could you recent changes around encoding have caused this?  @janvorli, @ellismg, are you aware of any other recent mscorlib/libcoreclr changes that could impact this?

**Comment by wtgodbe** [comment]
It's certainly possible. Are there any examples of this from before today? My UTF8 change was merged in on March 18 so I'd think we would have some failures from the last few days as well.

**Comment by stephentoub** [comment]
I saw it once yesterday and once today.

**Comment by ellismg** [comment]
I'm pretty sure this is a bad test?

Look at this case:

    [InlineData(new char[] { 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h' }, "abcdefgh")]

We fix the array and then pass it to a .ctor that expects a null terminated chunk of memory.  I don't think there's any reason to assume the array is null terminated (and could explain why this fails intermittently).

Am I missing something?

**Comment by ellismg** [comment]
FWIW, I would be very surprised if @wtgodbe's stuff impacted this at all, we shouldn't be doing any encoding stuff, this should be an allocate a blit.

**Comment by stephentoub** [comment]
> Am I missing something?

No, you're right, bad test.  Maybe there was a recent libcoreclr change related to allocation/GC that made it less likely an array would have a null byte after it.  Regardless, I'll fix the test.

**Comment by stephentoub** [comment]
> Maybe there was a recent libcoreclr change related to allocation/GC

Actually, it looks like these came in as part of @hughbe's test additions a few days ago, so it's probably just as simple as them being new incorrect tests.

**Comment by hughbe** [comment]
Yup, bad test. Sorry about that
