### ISSUE TITLE
Nuget install fails for System.Diagnostics.Tracing 4.0.21-beta-23516

### ISSUE THREAD

**Issue by eschneider999** [dotnet/corefx#7161]
Restoring packages for 'Symbiotic.Core'.
Restoring packages for F:\Dev\FrozenElephant\SymbioticORM\Symbiotic\Symbiotic.Core\project.json...
System.Diagnostics.Tracing 4.0.21-beta-23516 is not compatible with .NETPlatform,Version=v5.0.
Some packages are not compatible with .NETPlatform,Version=v5.0.
All packages are compatible with .NETFramework,Version=v4.6.
All packages are compatible with UAP,Version=v10.0.
All packages are compatible with DNXCore,Version=v5.0.
All packages are compatible with .NETFramework,Version=v4.6 (win-x86).
All packages are compatible with .NETFramework,Version=v4.6 (win-x64).
All packages are compatible with UAP,Version=v10.0 (win10-x86).
All packages are compatible with UAP,Version=v10.0 (win10-x86-aot).
All packages are compatible with UAP,Version=v10.0 (win10-x64).
All packages are compatible with UAP,Version=v10.0 (win10-x64-aot).
All packages are compatible with UAP,Version=v10.0 (win10-arm).
All packages are compatible with UAP,Version=v10.0 (win10-arm-aot).
All packages are compatible with DNXCore,Version=v5.0 (win7-x86).
All packages are compatible with DNXCore,Version=v5.0 (win7-x64).
Package restore failed for 'Symbiotic.Core'.
Package restore failed. Rolling back package changes for 'Symbiotic.Core'.

**Comment by terrajobst** [comment]
@ericstj, could yu have a look? It seems this package is still using the old names. I guess that's just a point in time until we've updated and uploaded new versions to nuget.org?

**Comment by ericstj** [comment]
`.NETPlatform,Version=v5.0` is the `dotnet` moniker which has been replaced with `netstandard`.  To create a PCL using the latest packages you need an updated NuGet client and PCL template /cc @Pilchie.

**Comment by eschneider999** [comment]
@ericstj , are you saying this is an authoring/packaging problem? just trying to understand if I'm doing something wrong...

**Comment by ericstj** [comment]
It's just that you're using the released Portable Class Library project with pre-release packages.  The pre-release packages have changes that require both a new client and an update to the PCL project templates.

If you'd like to try them out you can modify the project, but since this particular package, System.Diagnostics.Tracing, doesn't provide any new API it might not be worth the effort.  Nonetheless let me know if you'd like to try it out and I can provide steps.

@Pilchie may be able to provide details about an update to the PCL projects to use the latest packages.

**Comment by eschneider999** [comment]
So if I use a release build v4.0.20 It's should work fine? 
and your thinking is that there is not much change in the api from v4.0.20 to the latest pre-release?

Curious; what good is the pre-releases is no-one can pull them and test them out?

My main goal is to be able to do simple Trace.Writeline() and see it in VS and/or a file?

Trace does not seem to exist in v4.0.20

**Comment by ericstj** [comment]
There is no change between API in 4.0.20 and 4.0.21.  If there is API change we will bump the minor version (eg: 4.1.x).

The System.Diagnostics.Trace class is contained in https://www.nuget.org/packages/System.Diagnostics.TraceSource, not System.Diagnostics.Tracing.  Currently that package is only pre-release and only won't yet work in UWP which you are targeting.

> Curious; what good is the pre-releases if no-one can pull them and test them out?

Folks can try them out, its just that right now we need some additional PCL template changes and a new NuGet client to try them.  Alternatively you can use the dotnet CLI and also try them.

@weshaggard / @vancem can you recommend a good tracing sample for a PCL targeting NET4.6/UWP/DNXCore?

**Comment by eschneider999** [comment]
ok, my target is core/pcl it's an Micro ORM. Everything works but I pulled-out encryption, configuration, tracing and some dynamics/emit.

Trying to get a feel; if it's possible to re-add the functionality using corefx libs or if I need to exclude it or possibly use a third party pcl.

**Comment by ericstj** [comment]
Dynamic is supported.
Ref.emit is not supported if you are trying to target UWP due to NETNative not supporting it (no JIT).
Tracing is supported using EventSource APIs.  Older tracing technologies are available in pre-release packages (eg: TraceSource).
Encryption is supported but requires pre-release packages/tooling.  Types are in System.Security.Cryptography.*
Configuration APIs are not available.

If your main target is .NET Core then try the following tutorial: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/getting-started-core.md

**Comment by vancem** [comment]
If you just want output in the debugger, you can use System.Diagnostics.Debug.WriteLine (This is only for debug builds).

If you want to do production tracing, you can use EventSource.   You can use https://blogs.msdn.microsoft.com/vancem/2012/07/09/introduction-tutorial-logging-etw-events-in-c-system-diagnostics-tracing-eventsource/.   

Just make an EventSource with a 'Message' event which takes a string.  However typically you will want to make things that are more structured than that.  

Vance

**Comment by eschneider999** [comment]
Does EventSource work on other platforms?

**Comment by vancem** [comment]
EventSource works on all platforms in the sense that things logged with EventSource gets to EventListeners.   Where it goes after that (e.g. VS, or PerfView , or ....), depends on those pieces and is likely platform dependent.

**Comment by eschneider999** [comment]
very nice, I think I will use that for both tracing and the performance tracking part of my orm.

Thanks!

**Comment by ericstj** [comment]
I'll close this out since I think the questions have been addressed.  Let me know if you still have questions.
