### ISSUE TITLE
Capitalization of build folders names in case sensitive OS's

### ISSUE THREAD

**Issue by dmportella** [dotnet/corefx#7173]
HI everyone

Not sure if this is the right place to post this request but I wanted to ask for a change in the build folder setup for dotnet applications, I would like bin/Debug, bin/Release to be by default lower case. I know sounds lazy and all changing this would have no effect on a windows platform but would go be so cool not having to keep reminding yourself that the debug folder name is {caps}Debug and not debug.

![image](https://cloud.githubusercontent.com/assets/676817/13982643/21b3c73e-f0e3-11e5-98eb-9ad067917332.png)

Anyway

peace

**Comment by joshfree** [comment]
Hi @dmportella I moved this issue over to the /dotnet/cli repo.  Thanks

**Comment by dmportella** [comment]
thank you man!
