### ISSUE TITLE
Add NETCore50 support to a number of packages

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#7180]
https://github.com/dotnet/corefx/search?p=3&q=%22NotSupportedOnTargetFramework+Include%3D%5C%22netcore50%5C%22%22&type=Code&utf8=%E2%9C%93

The following packages block install in NetCore50 for poor reasons
- System.Diagnostics.TraceSource
  - GetCurrentProcessId, seems like we could come up with a decent replacement here  
- System.Diagnostics.TextWriterTraceListener
  - likely because of above  
- System.Diagnostics.FileVersionInfo
  - GetFileVersionInfoEx not available can use reflection.metadata implementation here

We should further review this packages to see which ones we can make support all profiles by RTM.

**Comment by ericstj** [comment]
I have fixes for the items listed in the primary description of the issue.

Further analysis of others.
- System.Net.WinHttpHandler
  - WinHTTP not supported in UWP, server networking stack
- *.AccessControl
  - ACL methods like GetSecurityInfoByHandle not supported by UWP
- Microsoft.Win32.Registry
  - Registry not supported in UWP
- System.IO.Pipes
  - CreatePipe and others not supported in UWP
- System.ServiceProcess.ServiceController
  - OpenSCManager and other APIs not supported in UWP.  Admin only tech.
- System.Runtime.CompilerServices.VisualC
  - Support for C++/CLI, not supported by NETNative.
- System.Security.Cryptography.Csp
  - CSP crypto stack not supported by UWP
- System.Diagnostics.Process
  - Creation:CreateProcess not supported by UWP.  
  - Enumeration: EnumProcesses not supported by UWP.
- System.IO.FileSystem.DriveInfo
  - GetLogicalDrive and others not supported by UWP.
- System.IO.MemoryMappedFiles
  - CreateFileMapping not supported but CreateFileMappingFromApp is, along with many other "fromApp" equivalents.  Possible with work.
- System.Net.Ping
  - Iphlpapi methods like IcmpSendEcho2 not supported by UWP.  May be possible to implement on top of sockets.
- System.Threading.Thread
  - tracked by https://github.com/dotnet/corefx/issues/2576
- System.Threading.ThreadPool
  - Represents managed threadpool & interop like BindHandle and RegisterWaitHandle, not supported by NETNative nor needed in cases where managed threadpool doesn't exist.
- System.IO.FileSystem.Watcher
  - ReadDirectoryChangesW not supported by UWP
- System.Net.Security
  - Schannel.dll not supported by UWP

I'll take a crack at MemoryMappedFiles.  The others are either blocked by missing native APIs or tracked with other issues.

**Comment by onovotny** [comment]
One update to the above list - in light of https://blogs.msdn.microsoft.com/dotnet/2016/05/27/making-it-easier-to-port-to-net-core/, `System.Threading.ThreadPool` needs to come back to UWP / .NET Native. Lots of existing code uses it instead of Tasks.
