### ISSUE TITLE
[April 21, 2016] Add Ubuntu 16.04 LTS (Xenial Xerusis) to CI and the RID graph

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#7191]
Ubuntu 16.04 LTS, codenamed Xenial Xerusis is set for release on April 21, 2016.

Add 16.04LTS to the RID graph and replace 15.10 in Jenkins with 16.04LTS.

https://wiki.ubuntu.com/Releases

Related item tracking Fedora 23: https://github.com/dotnet/corefx/issues/5990

**Comment by joshfree** [comment]
https://wiki.ubuntu.com/XenialXerus/ReleaseSchedule
- April 7th - KernelFreeze, NonLanguagePackTranslationDeadline
- April 14th - FinalFreeze, ReleaseCandidate, LanguagePackTranslationDeadline
- April 21st - FinalRelease Ubuntu Ubuntu 16.04

**Comment by joshfree** [comment]
FYI @Chrisboh

**Comment by Priya91** [comment]
This is added now.

**Comment by joshfree** [comment]
reopening issue until we have a clean build with CLI support
