### ISSUE TITLE
Deadlock in ClientWebSocket when CancellationToken is cancelled during a call to ConnectAsync()

### ISSUE THREAD

**Issue by mconnew** [dotnet/corefx#7198]
In WinHttpWebSocket.ConnectAsync, there is a using block around the main implementation of the function which looks like this:

``` csharp
using (CancellationTokenRegistration ctr = ThrowOrRegisterCancellation(cancellationToken))
```

ThrowOrRegisterCancellation registers a callback which calls Abort() on the WinHttpWebSocket. The Abort() method immediately attempts to take a lock on `_operation.Lock`.  
Inside the using block of ConnectAsync, there are two inner blocks which take a lock on `_operation.Lock`. While in the second lock, if the CancellationToken is cancelled, a deadlock occurs. What happens is the callback is fired, which calls Abort() which then blocks waiting to obtain a lock on `_operation.Lock`. This lock can't be taken because ConnectAsync is holding the lock. At the end of the second lock block in ConnectAsync, a call to ctr.Dispose() is made. When calling Dispose() on a CancellationTokenRegistration, if the cancellation callback is currently in progress, it blocks waiting for the callback to complete. The callback won't complete because it's waiting for the lock to be released by ConnectAsync. ConnectAsync won't release the lock until the Dispose() call completes, which won't complete until the callback is complete.  
Here are the two deadlocked call stacks:

```
[HelperMethodFrame: 0000001d84e5e6b8] System.Threading.Thread.SleepInternal(Int32)
System.Threading.Thread.Sleep(Int32) [f:\dd\ndp\clr\src\mscorlib\src\System\Threading\Thread.cs @ 708]
System.Threading.SpinWait.SpinOnce() [f:\dd\ndp\clr\src\mscorlib\src\System\Threading\SpinWait.cs @ 147]
System.Threading.CancellationTokenSource.WaitForCallbackToComplete(System.Threading.CancellationCallbackInfo) [f:\dd\ndp\clr\src\mscorlib\src\System\Threading\CancellationTokenSource.cs @ 890]
System.Net.WebSockets.WinHttpWebSocket+d__18.MoveNext()
```

```
[HelperMethodFrame_1OBJ: 0000001d8384e8d8] System.Threading.Monitor.Enter(System.Object)
System.Net.WebSockets.WinHttpWebSocket.Abort()
System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [f:\dd\ndp\clr\src\mscorlib\src\System\Threading\ExecutionContext.cs @ 93]
System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean) [f:\dd\ndp\clr\src\mscorlib\src\System\Threading\CancellationTokenSource.cs @ 785]
System.Threading.CancellationTokenSource.TimerCallbackLogic(System.Object) [f:\dd\ndp\clr\src\mscorlib\src\System\Threading\CancellationTokenSource.cs @ 513]
```

This will use a lot of CPU as the code for waiting for the callback to complete looks like this:

``` csharp
            SpinWait sw = new SpinWait();
            while (ExecutingCallback == callbackInfo)
            {
                sw.SpinOnce();  //spin as we assume callback execution is fast and that this situation is rare.
            }
```

**Comment by davidsh** [comment]
cc: @CIPop

**Comment by stephentoub** [comment]
> This will use a lot of CPU as the code for waiting for the callback to complete looks like this:

As a complete aside that has nothing to do with the actual issue here, SpinWait doesn't just burn CPU but rather uses a mix of Thread.SpinWait, Thread.Yield, and Thread.Sleep with varying arguments, so if you look at your CPU utilization while it's spinning, it shouldn't actually register as much.

**Comment by stephentoub** [comment]
> At the end of the second lock block in ConnectAsync, a call to ctr.Dispose() is made

It's not clear to me why this is being done.  Why must the CancellationTokenRegistration be disposed of while holding the lock on _operation.Lock?

**Comment by davidsh** [comment]
Without getting into the details here, there is a valid reason we use `_operationLock` to synchronize methods like ConnectAsync() and Abort().  ConnectAsync() calls various WinHTTP APIs.  Abort() calls mostly WinHttpCloseHandle().   It is required that in general, one cannot call a WinHTTP API on one thread while another thread has called a WinHTTP API and has not yet returned from it.  And specifically, it is very bad to call WinHttpCloseHandle() while another thread is still waiting to return from, say, WinHttpSendRequest (part of ConnectAsync).

We will need to look at this particular deadlock issue but there are reasons why we have locks in place to synchronize API calls to WinHTTP functions.

**Comment by mconnew** [comment]
@davidsh, the CancellationTokenRegistration is created in a using statement at the top of the method. There is no need to explicityly dispose it inside the lock. I believe simply removing the `ctr.Dispose()` call from inside the lock will fix this issue.

**Comment by KKhurin** [comment]
This takes less than 10 seconds to repro in WCF stress with short (~1s) Open timeouts. https://github.com/dotnet/wcf/issues/1676

**Comment by CIPop** [comment]
Thanks @KKhurin. According to @mconnew the fix is simple:

> There is no need to explicityly dispose it inside the lock. I believe simply removing the ctr.Dispose() call from inside the lock will fix this issue.

@KKhurin could you please share your test or details on how to repro with the community?

**Comment by mconnew** [comment]
@CIPop, I think @KKhurin provided the details. Call ConnectAsync with a short timeout. Do this with a lot of connections at once (it is a stress test so should be implied) over and over again and eventually (10 seconds but could be a large number of connects) you'll get a connection hit this issue. It's also very easy to reason why this happens and sufficient call stack has been provided to understand it.

**Comment by ayende** [comment]
I just run into this issue, is there any progress in fixing in using 2.0?

**Comment by cjmairair** [comment]
I didn't read everything in detail, but I have a similar problem. I don't know if it's the same. And it boils down to me thinking this:

WaitForCallbackToComplete inside CancellationTokenRegistration is just not right.

You don't just do a wait secretly, without the API user knowing about it. And this is the wrong place to wait.

Just this simple code will cause a deadlock.

```
 var cancelReg = cancelToken.Register(() =>
                    {
                        // maybe dispose stuff...
                        cancelReg.Dispose();
                    });
`
```
Because you are disposing the CancellationTokenRegistration thing inside the callback. But this is a normal thing to do.

This just shouldn't happen. cancelReg.Dispose just needs to detach the callback even if it is running.

**Comment by mconnew** [comment]
@cjmairair, there's a check in CancellationTokenRegistration.Dispose to see if it's being called on the same thread as the registration callback is happening on. If it is, it won't block.

**Comment by davidsh** [comment]
This has been obsoleted since we no longer use WinHTTP for System.Net.WebSockets.Client. Instead we use a managed implementation and use SocketsHttpHandler for the HTTP stack.
