### ISSUE TITLE
How can I add System.Net.Sockets 4.1.0 to my project's reference?

### ISSUE THREAD

**Issue by suzukid** [dotnet/corefx#7204]
Hello,

I'm trying to port my project using System.Net.Sockets.TcpClient class. So I tried to add latest System.Net.Sockets using NuGet. However it fails. Please help.

### PROBLEM
Adding System.Net.Sockets 4.1.0 fails with incompatible errors like this:

```
System.Net.Sockets 4.1.0-rc3-23923 is not compatible with UAP,Version=v10.0.
Some packages are not compatible with UAP,Version=v10.0.
System.Net.Sockets 4.1.0-rc3-23923 is not compatible with UAP,Version=v10.0 (win10-arm).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm).
System.Net.Sockets 4.1.0-rc3-23923 is not compatible with UAP,Version=v10.0 (win10-arm-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).
System.Net.Sockets 4.1.0-rc3-23923 is not compatible with UAP,Version=v10.0 (win10-x86).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86).
System.Net.Sockets 4.1.0-rc3-23923 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).
System.Net.Sockets 4.1.0-rc3-23923 is not compatible with UAP,Version=v10.0 (win10-x64).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64).
System.Net.Sockets 4.1.0-rc3-23923 is not compatible with UAP,Version=v10.0 (win10-x64-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).
```

### NOTES
I could add System.Net.Sockets 4.0.0 successfully. But it doesn't include TcpClient class so I need 4.1.0.
I guess it would be solved by tweaking project.json but I don't know where/how to tweak.
Adding System.Net.Sockets still fails for a newly-created Universal Windows (10) Blank App.

### STEPS

- Create new Blank App (Universal Windows) with Visual Studio 2015 Update 1
- Locate Tools->Options->NuGet Package Manager->Package Sources and add .NET Core package source (*1).
- Right click References in Solution Explorer and select Manage NuGet Packages...
- Select newly-added Package Source and find latest System.Net.Sockets(*2). Don't forget to check "Include prerelease"
- Install latest System.Net.Sockets. It fails. Errors are logged in Output window.
- Double-click project.json in Solution Explorer.

Original project.json is as follows:

```
{
  "dependencies": {
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.0.0"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```

**Tweak a.** Change "dependencies": {"Microsoft.NETCore.UniversalWindowsPlatform": "5.0.0"} -> "5.4.0"
=> Try to add System.Net.Sockets again. Fails.

**Tweak b.** Add "dotnet5.4": {}, into
  "frameworks": {
    "uap10.0": {}
  },
=> Try to add System.Net.Sockets again. Fails.

**Tweak c.** Delete "uap10.0": {} after adding "dotnet5.4": {} into "frameworks".
=> Try to add System.Net.Sockets again. Fails.

### REFERENCE
Can't locate TcpClient and TcpListener from Socket.Net.Sockets #5939
*) This page says you have to switch platform to "dotnet5.4".

(*1) https://dotnet.myget.org/F/dotnet-core/api/v3/index.json

(*2) Currently the latest is 4.1.0-rc3-23923

**Comment by davidsh** [comment]
cc: @ericstj 

You need to wait until we publish RC2 packages to NuGet.org in the next few weeks.

Then the System.Net.Sockets 4.1 contract will work.  Currently the packages on NuGet.org are old and don't support System.Net.Sockets 4.1.  In addition, if you are building a UWP (Windows 10 Store App), you should wait until Visual Studio 2015 Update 2 is released.  This will make sure you have the correct versions of the toolchains.

There have been many changes in the NuGet packaging including the "dotnet" monikers.  For example, things are not called "dotnet5.4" anymore.  Instead, they are called things like "netstandard1.5", etc.

**Comment by ericstj** [comment]
Agree on one count: need a new version of NuGet that's coming with update 2.   Folks don't necessarily need to wait until packages are on nuget.org if all they want to do is try them out, but should wait if they intend to publish the application.

**Comment by davidsh** [comment]
closing this issue since the question was answered.

**Comment by chgray** [comment]
I'm running all the latest,  2015 update 2, and RC2 and I'm also hitting the same problem. -  ideas?

**Comment by ericstj** [comment]
@chgray to pick up the latest packages in UWP reference the following from the .NET Core feed:
```
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.0",
    "System.Net.Sockets": "4.1.0"
```
These require the latest NuGet 3.4.4, available here: https://dist.nuget.org/index.html

**Comment by chgray** [comment]
Thx @ericstj  & @SidharthNabar 

I installed 3.4.4 and 5.2 doesn't appear in the NuGet menu in VS2015 Update2.  is there something I need to do?  (I have the prerelease value checked)
