### ISSUE TITLE
Install fails for Microsoft.Diagnostics.Tracing.EventSource

### ISSUE THREAD

**Issue by eschneider999** [dotnet/corefx#7206]
Trying to use this with my PCL, nit sure what's wrong. It's not a beta version of event source.

Restoring packages for 'Symbiotic.Core'.
Restoring packages for F:\Dev\FrozenElephant\SymbioticORM\Symbiotic\Symbiotic.Core\project.json...
Installing Microsoft.Diagnostics.Tracing.EventSource.Redist 1.1.28.
Installing Microsoft.Diagnostics.Tracing.EventSource 1.1.28.
Installing Microsoft.Diagnostics.Tracing.EventRegister 1.1.28.
Microsoft.Diagnostics.Tracing.EventSource.Redist 1.1.28 is not compatible with .NETPlatform,Version=v5.0.
Some packages are not compatible with .NETPlatform,Version=v5.0.
All packages are compatible with .NETFramework,Version=v4.6.
All packages are compatible with UAP,Version=v10.0.
Microsoft.Diagnostics.Tracing.EventSource 1.1.28 is not compatible with DNXCore,Version=v5.0.
Microsoft.Diagnostics.Tracing.EventSource.Redist 1.1.28 is not compatible with DNXCore,Version=v5.0.
Some packages are not compatible with DNXCore,Version=v5.0.
All packages are compatible with .NETFramework,Version=v4.6 (win-x86).
All packages are compatible with .NETFramework,Version=v4.6 (win-x64).
All packages are compatible with UAP,Version=v10.0 (win10-x86).
All packages are compatible with UAP,Version=v10.0 (win10-x86-aot).
All packages are compatible with UAP,Version=v10.0 (win10-x64).
All packages are compatible with UAP,Version=v10.0 (win10-x64-aot).
All packages are compatible with UAP,Version=v10.0 (win10-arm).
All packages are compatible with UAP,Version=v10.0 (win10-arm-aot).
Microsoft.Diagnostics.Tracing.EventSource 1.1.28 is not compatible with DNXCore,Version=v5.0 (win7-x86).
Microsoft.Diagnostics.Tracing.EventSource.Redist 1.1.28 is not compatible with DNXCore,Version=v5.0 (win7-x86).
Some packages are not compatible with DNXCore,Version=v5.0 (win7-x86).
Microsoft.Diagnostics.Tracing.EventSource 1.1.28 is not compatible with DNXCore,Version=v5.0 (win7-x64).
Microsoft.Diagnostics.Tracing.EventSource.Redist 1.1.28 is not compatible with DNXCore,Version=v5.0 (win7-x64).
Some packages are not compatible with DNXCore,Version=v5.0 (win7-x64).
Package restore failed for 'Symbiotic.Core'.
Package restore failed. Rolling back package changes for 'Symbiotic.Core'.
========== Finished ==========

**Comment by chcosta** [comment]
I'm not familiar with this package or even how/where it gets published from.  I think @vancem was working on this.

**Comment by vancem** [comment]
@davmason  who owns EventSource.

However you should not use Microsoft.Tracing.Tracing.EventSource with CoreCLR.   System.Diagnostics.Tracing.EventSource exists in the CoreFX framework (its references assembly is System.Diagnostics.Tracing.dl).  You should be using that.

**Comment by davmason** [comment]
Do you own SymbioticORM? The issue here is that all the platform/targeting stuff in dotnet core just changed from dnx to dotnet tools and it appears that the nuget package of eventsource doesn't automatically support the new version.

As Vance mentions, there is no reason to use the nuget package on .net core. System.Diagnostics.Tracing.EventSource is as up to date (and sometimes even newer) than the nuget package.

So by far the easiest fix is to drop the nuget package and target System.*.EventSource. I will investigate and see what needs done so the nuget packaged works on .net core, but that may take some time.

**Comment by eschneider999** [comment]
Ok, wasn't sure which to use

-----Original Message-----

**Comment by eschneider999** [comment]
Yes, I own Symbiotic ORM. So do I need to update my package explorer?

 

Curious; what tools do you guys use to create packages?

 

Cool, so I don’t need the lib then…

 

Thanks,

Eric

**Comment by ericstj** [comment]
Removed the packaging tag, this issue is discussing the use of an old package Microsoft.Diagnostics.Tracing.EventSource, which is not part of this repo.  As @vancem mentions that package hasn't been updated to support CoreCLR.  You can use System.Diagnostics.Tracing.EventSource instead.  If System.Diagnostics.Tracing.EventSource needs to be updated to support more platforms/scenarios to be a complete replacement please let us know.

**Comment by karelz** [comment]
Triage: EventSource is part of .NET Standard 2.0. We do not plan to downport the package to Frameworks which do not support EventSource inbox. It is meant to ship bug fixes to Desktop faster.

**Comment by ViktorHofer** [comment]
That nuget package is download more than 1mil times: https://www.nuget.org/packages/Microsoft.Diagnostics.Tracing.EventSource.Redist/

Would it make sense to add a netstandard configuration to the package which just typeforwards to the internal implementation?

I would at least add a description to the nuget package that explains that EventSource is inbox in .NET Core / is part of netstandard2.0.

**Comment by brianrob** [comment]
EventSource.Redist is only targeted at desktop.  The purpose of the package is to provide a mechanism to provide bug fixes outside of framework releases.  Thus, it is expected that it will fail on non-desktop installs, and we don't want to point to internal implementations if the runtime has one.

**Comment by ViktorHofer** [comment]
Thanks for the clarification. I think we should really do this:

> I would at least add a description to the nuget package that explains that EventSource is inbox in .NET Core / is part of netstandard2.0.

**Comment by brianrob** [comment]
@ViktorHofer, it is reasonable to improve the description of the package.  Would you mind filing an issue to track this?
