### ISSUE TITLE
Registered I/O Extensions

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#721]
Expose Winsock's RIO Extensions to .NET. [Registered I/O is available](https://msdn.microsoft.com/en-gb/library/windows/desktop/ms740642%28v=vs.85%29.aspx) for desktop from Windows 8, Windows Server 2012, Windows Store apps from Server 2012 R2 and 8.1, and phone from Windows Phone 8

User code would want to pre-register a buffer, which would need to be pinned and go via [RIORegisterBuffer](https://msdn.microsoft.com/en-us/library/windows/desktop/hh437199%28v=vs.85%29.aspx) probably by passing through an internal buffer as per the [Websocket](http://referencesource.microsoft.com/#System/net/System/Net/WebSockets/WebSocket.cs,7dd0b6c7a0033d04)s to reduce data copies. Async sends and receives driven via ArraySegment over provided internal buffer.

(Related [SO question](http://stackoverflow.com/questions/18419117/rio-registered-i-o-sockets-in-net))

**Comment by ericstj** [comment]
I think this is a request for System.Net.Sockets.  Ben, is that correct?

**Comment by benaadams** [comment]
Yes, would be in System.Net and Sockets for raw exposure; but could always be used in other areas TcpClient, HttpListener etc though don't know how the underlying implementations work at this time

**Comment by benaadams** [comment]
Also depends where NetworkStream lives

**Comment by benaadams** [comment]
Created [an example](https://github.com/aspnet/benchmarks/pull/10) which uses Registered I/O from managed code which @DamianEdwards and the ASP.NET team took for a spin on their community stand up: https://youtu.be/7O81CAjmOXk?t=5m38s 7.6 million requests per second and 8GBps on Windows

**Comment by CIPop** [comment]
@benaadams This is a very interesting idea: we were also thinking of adding RIO support.
From a design perspective, it's unclear if RIO would fit the current System.Net.Sockets contract and associated usage patterns.

For now, it may be interesting to note that we've been updating both the ThreadPool and the Sockets implementation in corefx. We have removed the managed ThreadPool implementation and removed all older async modes used by Sockets, allowinging only Overlaped with IOCP. The work for open-sourcing this is tracked by #896.

I'm curious: could you share some of the scenarios for managed code where you would use RIO instead of Sockets?

**Comment by benaadams** [comment]
Hi @CIPop we've done some further testing using RIO which may be of interest: http://www.ageofascent.com/azure-cloud-high-speed-networking/ which is all in managed code (other than the RIO interop). For memory reservation we allocate several chunks in the LoH which we pin after a GC Compact/FInalizers/GC Compact round and then split into RIO buffer segments (much like ArraySegments) and pool - its almost a zero allocation system with very few GC pointers.

For us ideally we'd want a webserver around it so we wouldn't have to handle encryption and websocket protocols, but I think very many people would be interested as the results are quite astounding. At the moment we use websockets on httplistener in v4.6 and again create a large pinned buffer in the LoH which we then chunk and pass as internal buffers into each websocket initialise for similar reasons. 

For server based scenarios; especially cloud, where you may have one app per machine; I'd probably want to use RIO as the underlying sockets rather than standard Winsock as you generally have plenty of free RAM but throughput and latency are the premiums. There is an argument that for these scenarios C/C++ is more fitting - but managed code is so much nicer, so if you can get the same throughput and latency in the managed world for me it would be the clear choice, especially now SIMD is with us.

Will come up with some examples...

**Comment by benaadams** [comment]
> allowinging only Overlaped with IOCP

RIO is mostly the same; though with a couple other methods. It uses IOCP to signal edge changes, so you only get 1 IOCP kernel event each time you call RIONotify; to signal more data. Then you read from the user mode RIO queue (see: https://github.com/benaadams/benchmarks/blob/managed-rio-experimental/experimental/ManagedRIOHttpServer/RegisteredIO/RIOThreadPool.cs#L159 )

You can skip IOCP completely for lowest latency and just spin reading the user mode queues; but that burns a lot of CPU and I imagine would be quite an edge case.

**Comment by stas-sultanov** [comment]
@CIPop a good example where i'm going to use RIO socket with managed code is my ecomrce project which requires to handle 100000 HTTP requests per second on the USA.

@benaadams by creating a new socket implementation i would like to suggest that it should implement try-do pattern for performance sensetive methods like `send`, because IOPS of the server will dramaticly degraded if `send` method will start to throw exceptions.

**Comment by CIPop** [comment]
Thank you all for your feedback! 

The following benchmark (open source) is useful to compare perf differences between classic IOCP and RIO: http://ctstraffic.codeplex.com/

**Comment by aL3891** [comment]
Hey there, i took a stab at a .net version of the Rio apis over at https://github.com/aL3891/RioSharp, it's very early still but perhaps it can be useful

**Comment by CIPop** [comment]
Really cool @aL3891! Thanks for sharing with us!

Please keep us updated. I'm really curious on how it performs vs [ctstraffic](http://ctstraffic.codeplex.com/) and vs the current implementation for Sockets.

**Comment by aL3891** [comment]
Yeah i am as well :) my plan was to create a cts compatible server and client so i can test both ends of that. Hopefully i'll be able to spend some time on that this week, i'll be sure to keep you posted

**Comment by aL3891** [comment]
Hello, i'm pretty close to a 1.0 of riosharp and i've done some preliminary testing with a rio sharp based version of cts traffic.
 
Right now on my reference machine i max out the 10 gbit virtual network at about 10% less cpu than ctstraffic when pulling from the server (regular ctstraffic acting as the client in both cases) i'm not sure i do everything that ctstraffic is doing though (but i did at least turn of data verification and used the same buffer size)

Riosharp is pretty low level with access to data pointers and things like that (as well as support for streams) so maybe its not a great fit for the corefx in the current state (there are no tests for example), i'd love for some feedback as to how it could be more corefx friendly though

**Comment by aL3891** [comment]
hm, now i'm actually getting some erratic performance, i may have broken something when trying to fix some other issues with the cts implementation :) but in my profiling the managed parts have been pretty lean. i'd love to have a second pair of eyes on it though!

**Comment by karelz** [comment]
Triage: We believe that reimplementing sockets is too hard. Adding new API sounds like a good idea.
Maybe trying it out in corefxlab first, or building it on top of pipeline APIs.

This looks like a non-trivial large work.

**Comment by benaadams** [comment]
I have already added to pipelines (pre-corefxlab); now [System.IO.Pipelines.Networking.Windows.RIO](https://github.com/dotnet/corefxlab/tree/master/src/System.IO.Pipelines.Networking.Windows.RIO) still needs work - is good fit and works as good transport agnostic test subject for it.

**Comment by karelz** [comment]
Do we need to keep it opened here? (if there's value in tracking in corefx, I am fine with it ...)

**Comment by benaadams** [comment]
Would be nice to have in the corefx apis; but I think it would require significant design as it is a whole different set of apis. 

I think for now Pipelines provides a good intermediary to enable support - without requiring an different api shape; so happy to close this and maybe revisit in future.
