### ISSUE TITLE
Suspicious code in SortedList

### ISSUE THREAD

**Issue by GSPP** [dotnet/corefx#7230]
Reading the commit logs I find [this code](https://github.com/dotnet/corefx/blob/39a8b7dc241d536653b20066ffe69698e04f82ab/src/System.Collections/src/System/Collections/Generic/SortedList.cs#L164) suspicious:

                    Array.Sort<TKey, TValue>(keys, _values, comparer);
                    comparer = Comparer; // obtain default if this is null.

Either the assignment does nothing (which I think is the case) or the sorting and the following usage of `comparer` are using different comparer which would be a bug.

**Comment by stephentoub** [comment]
cc: @JonHanna 

Those lines should probably be swapped, but I'm not sure it technically matters.  If comparer is provided as null to the constructor, then Comparer will be ```Comparer<T>.Default```, comparer will be null, and Array.Sort will use ```Comparer<T>.Default```, so everyone will be using ```Comparer<T>.Default```.  If comparer comes in non-null, then Comparer will equal comparer, and everyone will be using the provided comparer.

If that ```comparer = Comparer;``` didn't exist, and comparer came in as null, then the subsequent use of ```comparer.Compare``` would null ref.

**Comment by JonHanna** [comment]
Yeah, sort does the same null-becomes-default logic that the constructor had previously done, so passing null to it is fine. It's only the added check that can't work with null, hence the pulling it back into the argument.
Its fine as is, but I'll add a more extensive comment if wanted.

**Comment by stephentoub** [comment]
> Its fine as is, but I'll add a more extensive comment if wanted.

I'd say just swap the lines.

**Comment by JonHanna** [comment]
Cool. Will do that when next at my computer. Will probably add a little bit to the comment that's there since assigning a field to a parameter in a ctor is a bit unusual.

**Comment by GSPP** [comment]
So if the assignment actually does something, is this not a bug? The duplicate checking would use a different comparer than the sorting. This should be demonstrable with a test.

**Comment by stephentoub** [comment]
> So if the assignment actually does something, is this not a bug? The duplicate checking would use a different comparer than the sorting.

No.  The assignment does something because when comparer comes in to the ctor, it's passed to the base, and the base will check for null and make ```Comparer``` be ```Comparer<T>.Default```, but that doesn't affect the value of ```comparer``` in the ctor.  So, if null is passed in to the ctor, the null is passed in to Array.Sort, and Array.Sort will use ```Comparer<T>.Default```, then ```comparer``` (which is null) will be set to ```Comparer``` (which is ```Comparer<T>.Default```), and both the sort and the comparison will be done with ```Comparer<T>.Default```.  If ```comparer``` comes in non-null, then the assignment is a nop, because ```Comparer``` and ```comparer``` will be identical.

**Comment by GSPP** [comment]
I see. The assignment does not change sort order under any circumstances but it makes `comparer.Compare(...)` work. So sad, I thought I had found a bug :)

**Comment by stephentoub** [comment]
> So sad, I thought I had found a bug :)

That it's not intuitive, though, is enough of a reason to swap the order of the lines, just so that it's clear the same comparer is in fact being used.

**Comment by GSPP** [comment]
Solace.

**Comment by JonHanna** [comment]
Yep. It's not a bug, but you've certainly found scope for improvement. If you want to take the task of flipping the lines, please do, as I won't be able to submit a PR until at least tomorrow.

**Comment by GSPP** [comment]
Uh, I don't have anything set up. I actually planned to submit some spelling corrections as my first pull request some time. But right now this is not on my mind/agenda so I'll pass on the opportunity. Thanks!
