### ISSUE TITLE
System.Buffers.ArrayPool.Rent does not accept capacity == 0

### ISSUE THREAD

**Issue by iskandersierra** [dotnet/corefx#7250]
I'm writing a "new" implementation of MemoryStream based on ArrayPool<byte>. 
The problem is that current implementation of System.IO.MemoryStream allows capacity zero, and current implementation of System.Buffers.ArrayPool.Rent rejects capacity zero. But I do not see any impediment on Rent accepting zero as argument.  After all you can do new byte[0].
Two possible implementations:
* Return a singleton byte[0] array
* Return a minimum length array
```CSharp
    public override T[] Rent(int minimumLength)
    {
        if (minimumLength <= 0)
            throw new ArgumentOutOfRangeException(nameof(minimumLength));
        ...
```
Would become:
```CSharp
    public override T[] Rent(int minimumLength)
    {
        if (minimumLength < 0)
            throw new ArgumentOutOfRangeException(nameof(minimumLength));
        if (minimumLength == 0) // otherwise Utilities.SelectBucketIndex could break
            minimumLength = 1;
        ...
```

Otherwise client code most remember this case and Return or not the buffer. It is not a huge burden but its not as clean as just returning the empty buffer.

**Comment by benaadams** [comment]
@iskandersierra if this was supported, you'd probably want to something more like

```csharp
if (minimumLength == 0)
    return Array.Empty<T>(); // or equv
```

**Comment by JonHanna** [comment]
Returning it could just be a nop, too.

**Comment by sokket** [comment]
@iskandersierra Could you please elaborate on the scenario where you're renting a 0-length array? The code right now doesn't explicitly disallow this, but I'm curious on what meaningful operations could be done on a zero-length-pooled-array (I'm not saying that there aren't any, I just can't think of one off the top of my head :) ).

**Comment by sokket** [comment]
Sorry I take that back, it is explicitly disallowed and throws an Exception. My other question still pertains of if you can elaborate on your scenario :)

**Comment by iskandersierra** [comment]
Hi @sokket its all about completeness. The zero-length case could be handled by the client code as I did in an implementation of ArrayPoolMemoryStream (a MemoryStream using ArrayPool for buffer management). A response for a zero-length buffer request could be a singleton zero-length array or a minimum size array (I prefer this last option). After all, when creating a MemoryStream for writing, usually you are going to need some bytes anyway, so there would be no concern about giving some of the minimum length buffers away.
