### ISSUE TITLE
ServiceControllerTests.PauseAndContinue test failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7264]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win10_debug/142/consoleFull
```
18:55:59      System.ServiceProcess.Tests.ServiceControllerTests.PauseAndContinue [FAIL]
18:55:59         Assert.Equal() Failure
18:55:59         Expected: Running
18:55:59         Actual:   StartPending
18:55:59         Stack Trace:
18:55:59            d:\j\workspace\outerloop_win---0cba2915\src\System.ServiceProcess.ServiceController\tests\System.ServiceProcess.ServiceController.Tests\ServiceControllerTests.cs(172,0): at System.ServiceProcess.Tests.ServiceControllerTests.PauseAndContinue()
```

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win7_debug/139/consoleFull

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win10_release/137/consoleFull

**Comment by ianhays** [comment]
@bartonjs resolved this in https://github.com/dotnet/corefx/pull/8010. 

I tested it locally to be sure (ran it in a loop ~100 times) and saw no failures.
