### ISSUE TITLE
Regression happened when run cross-build for Linux/ARM32

### ISSUE THREAD

**Issue by leemgs** [dotnet/corefx#7267]
Yesterday, We changed the commit number of coreCLR with the  latest commit number that is merged on 25-Mar-2016. Oops. We have again been getting the build-break of CoreCLR with cross-build since 2016.06.18. Actually,  the existing CI system (e.g. http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/arm_cross_release_ubuntu/) does not handle completely the build errors  of CoreCLR with release mode for Linux/ARM 

### Build Command: 
invain@u1404:/work/dotnet/arm-32/coreclr$ time ROOTFS_DIR=/work/dotnet/rootfs-coreclr/arm ./build.sh arm release clean cross skiptests

### Build  errors:

```
invain@u1404:/work/dotnet/arm-32/coreclr$ time ROOTFS_DIR=/work/dotnet/rootfs-coreclr/arm ./build.sh arm release clean cross skiptests 
                   . . . .  OMISSION  . . . . .
[ 16%] Building CXX object src/jit/crossgen/CMakeFiles/jit_crossgen.dir/__/targetarm.cpp.o
[ 16%] Building CXX object src/jit/crossgen/CMakeFiles/jit_crossgen.dir/__/lowerarm.cpp.o
[ 16%] Building CXX object src/jit/crossgen/CMakeFiles/jit_crossgen.dir/__/codegenarm.cpp.o
[ 16%] Building CXX object src/jit/crossgen/CMakeFiles/jit_crossgen.dir/__/unwindarm.cpp.o
[ 16%] Building CXX object src/jit/crossgen/CMakeFiles/jit_crossgen.dir/__/codegenlegacy.cpp.o
[ 16%] Building CXX object src/jit/crossgen/CMakeFiles/jit_crossgen.dir/__/registerfp.cpp.o
Linking CXX static library libjit_crossgen.a
[ 16%] Built target jit_crossgen
make: *** [all] Error 2
Failed to build coreclr components.

real	1m5.735s
user	3m0.388s
sys	0m12.956s
invain@u1404:/work/dotnet/arm-32/coreclr$ 
```

**Comment by leemgs** [comment]
Actually, the above issue is always reproduced if the not-stripped native files are in the different format that  build machine (running objcopy command) uses.

**Comment by leemgs** [comment]
Moved to github.com/dotnet/coreclr/

**Comment by stephentoub** [comment]
> Moved to github.com/dotnet/coreclr/

Closing here then.
