### ISSUE TITLE
Socket.SendAsync NetEventSource calls Enter twice instead of Exit.

### ISSUE THREAD

**Issue by jlennox** [dotnet/corefx#7276]
`public bool SendAsync(SocketAsyncEventArgs e)
        {
            bool retval;

            if (s_loggingEnabled)
            {
                NetEventSource.Enter(NetEventSource.ComponentType.Socket, this, "SendAsync", "");
            }

            // ...

            if (s_loggingEnabled)
            {
                NetEventSource.Enter(NetEventSource.ComponentType.Socket, this, "SendAsync", retval);
            }

            return retval;
        }
`

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/corefx/pull/7277
