### ISSUE TITLE
Open-source EncodingData tool

### ISSUE THREAD

**Issue by nslottow** [dotnet/corefx#728]
This tool is used to generate [System.Text.Encoding.CodePages\src\System\Text\EncodingTable.Data.cs](https://github.com/dotnet/corefx/blob/master/src/System.Text.Encoding.CodePages/src/System/Text/EncodingTable.Data.cs).

**Comment by nslottow** [comment]
@tarekgh @weshaggard, as we discussed, this may not be worth open-sourcing at this time: It is just a one-off tool that was used to generate EncodingTable.Data.cs once, a file which we do not expect to change frequently, if at all.

@tarekgh I'm reassigning this to you to close since you own the tool.

**Comment by krwq** [comment]
If the tool is not too big it might be worth to converting it to t4 template

**Comment by tarekgh** [comment]
This issue already done in the BuildTools:

```
https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/GenerateEncodingTable.cs
https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/encoding.targets
```
