### ISSUE TITLE
`nameof` still could be used in a lot of places

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#7290]
Ran this `grep` query on the source code to search for places we're still using magic strings:

```bash
grep -r 'throw new .*Exception(.*"[^ ]*".*)' .
```

Surprisingly, I found a lot of them. [Here's](https://gist.github.com/anonymous/5b9e96733edd62e52631) the full output from my terminal. I'm going to try tackling some of the ones in `Common`, but as it looks like there are quite a few, I don't think I'll be able to sort through all of them. Other people are welcome to join in.

For easier reading, [here's](https://gist.github.com/anonymous/5b9e96733edd62e52631) the full file list with just the names.

cc: @justinvp

---

**edit:** I'll update this post more as I come along more use cases for `nameof` in the CoreFX source.

- [DynamicObject](https://github.com/dotnet/corefx/blob/master/src/System.Dynamic.Runtime/src/System/Dynamic/DynamicObject.cs#L239)

**Comment by JonHanna** [comment]
I think it's pretty much consensus (and the best way to prove a consensus is to claim one and wait for someone to argue otherwise) that if you can find some cases where `nameof` can be introduced, that you'll have made an improvement, so go for it :smile:

**Comment by stephentoub** [comment]
> Surprisingly, I found a lot of them. Here's the full output from my terminal.

There are some real ones in there that can be fixed, but lots of them aren't valid.

> if you can find some cases where nameof can be introduced, that you'll have made an improvement

In the product source, yes.  In tests, not worth the churn.

**Comment by jamesqo** [comment]
@stephentoub 

> There are some real ones in there that can be fixed, but lots of them aren't valid.

You seem to be right. I ran `grep -v test` on the results which cut out most of the invalid cases and reduced it to ~450 lines:

https://gist.github.com/anonymous/ae4352e1d7ce2901e4ef

**Comment by eadordzhiev** [comment]
@stephentoub Sorry to bother you, I need your advice. The `OpenCore` function in `S.I.MMF\MemoryMappedFile.Windows.cs` references the `access` parameter, which is absent there. 

        private static SafeMemoryMappedFileHandle OpenCore(
            string mapName, HandleInheritability inheritability, int desiredAccessRights, bool createOrOpen)
        {
            // ...
            throw new ArgumentException(SR.Argument_NewMMFWriteAccessNotAllowed, "access");
            // ...
        }

Visual Studio shows me that the function is being used here:

        private static SafeMemoryMappedFileHandle OpenCore(
            string mapName, HandleInheritability inheritability, MemoryMappedFileAccess access, bool createOrOpen)
        {
            return OpenCore(mapName, inheritability, GetFileMapAccess(access), createOrOpen);
        }

And here:

        private static SafeMemoryMappedFileHandle OpenCore(
            string mapName, HandleInheritability inheritability, MemoryMappedFileRights rights, bool createOrOpen)
        {
            return OpenCore(mapName, inheritability, GetFileMapAccess(rights), createOrOpen);
        }

The latter doesn't have the `access` parameter, but the `rights` instead, which makes the `paramName` misleading. How should I resolve this? I would add an `accessParameterName` argument and pass the `nameof` to it, but I'm not sure if this is the best solution. Or mb just leave the code as it is? Thanks!

**Comment by jamesqo** [comment]
Another place I found in `SqlClient` that looks like it could use `nameof`:

https://github.com/dotnet/corefx/blob/7cad848/src/System.Data.SqlClient/src/System/Data/Locale/Locale.cs#L33

I've fixed that in #7467, but I'm sure there are other calls to that method throughout the assembly.

**Comment by stephentoub** [comment]
I'm going to close this.  A bunch have been addressed and the list is out of date.  Folks are welcome to submit PRs to address other ones found when they're found; an issue tracking it isn't needed. Thanks.
