### ISSUE TITLE
System.Globalization.Tests.CompareInfoTests.GetHashCode_EmptyString failed on Ubuntu 14.04 outerloop

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#7299]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_ubuntu14.04_debug/58/consoleFull
````
02:40:21   Discovering: System.Globalization.Tests
02:40:21   Discovered:  System.Globalization.Tests
02:40:21   Starting:    System.Globalization.Tests
02:40:21      System.Globalization.Tests.CompareInfoTests.GetHashCode_EmptyString [FAIL]
02:40:22         Assert.Equal() Failure
02:40:22         Expected: 0
02:40:22         Actual:   -482897332
02:40:22         Stack Trace:
02:40:22               at System.Globalization.Tests.CompareInfoTests.GetHashCode_EmptyString()
02:40:22   Finished:    System.Globalization.Tests
02:40:22   
````

**Comment by stephentoub** [comment]
This looks like an infrastructure issue, using an out-of-date mscorlib.

**Comment by tarekgh** [comment]
@stephentoub 
I am seeing you have fixed Unix code with the commit fb223894cc95c4269829dde874cc9ec7f65d3bce and you are right the version used on build is rc3-23925 but also the latest built package from myget which is https://dotnet.myget.org/F/dotnet-core/api/v2/package/runtime.ubuntu.14.04-x64.Microsoft.NETCore.Runtime.CoreCLR/1.0.2-rc3-23929-00 looks still not including your fix, 

do you know what is wrong? do you know who is familiar with this area who may help fixing it in the infrastructure?

**Comment by stephentoub** [comment]
@joshfree, is this the issue you mentioned offline where the coreclr package hasn't been including updated Unix mscorlib/libcoreclr bits?

**Comment by joshfree** [comment]
it could be.  @chcosta is looking into this now.

**Comment by tarekgh** [comment]
@chcosta please let me know if you think I can help with anything here. Thanks.

**Comment by joshfree** [comment]
Happened again http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_ubuntu14.04_debug/lastCompletedBuild/testReport/System.Globalization.Tests/CompareInfoTests/GetHashCode_EmptyString/

do we need to update packages in corefx from coreclr?

**Comment by stephentoub** [comment]
@joshfree, I merged the latest packages earlier today, but the build you highlighted is from last night.

**Comment by joshfree** [comment]
ok.  I kicked off a number of manual runs.  let's see how it goes

**Comment by stephentoub** [comment]
I believe this is now fixed.  Please re-open if I'm incorrect.
