### ISSUE TITLE
Calling EventSource.WriteEvent(int eventId, string arg1, string arg2) throws an ArgumentNullException

### ISSUE THREAD

**Issue by sleimanzublidi** [dotnet/corefx#7335]
I'm calling the method EventSource.WriteEvent(int eventId, string arg1, string arg2) and arg2 is a string with 90947 characters. It throws the following exception:

Exception thrown: 'System.ArgumentNullException' in mscorlib.ni.dll
Additional information: Value cannot be null.

{"Value cannot be null.\r\nParameter name: format"}

```
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at System.Environment.GetResourceString(String key, Object[] values)
   at System.Diagnostics.Tracing.EventSource.ThrowEventSourceException(String eventName, Exception innerEx)
   at System.Diagnostics.Tracing.EventSource.WriteEventWithRelatedActivityIdCore(Int32 eventId, Guid* relatedActivityId, Int32 eventDataCount, EventData* data)
   at System.Diagnostics.Tracing.EventSource.WriteEvent(Int32 eventId, String arg1, String arg2)
```

**Comment by davmason** [comment]
@sleimanzublidi  - I assume this only happens when you are collecting via ETW. I haven't had a chance to debug this yet, but it is almost certainly because you're exceeding the capacities of ETW - you are limited to 64 KB of data in an event and your string is too big. It shouldn't matter if you are using EventListeners, there isn't a limitation on size there.

This is clearly an issue with how we handle this failure - I need to investigate why EventSource is failing and not providing a useful error message, but in the meantime you can unblock yourself by making sure that your strings don't exceed the capacity of ETW.

**Comment by lt72** [comment]
This does not make the bar for RTM as it is mostly a cosmetic issue about how error is presented, given that ETW would not be able to handle such amount of data anyway.

**Comment by karelz** [comment]
Next step: Debug the failure, propose a fix.

**Comment by brianrob** [comment]
I put together a quick test for this and it did not throw.  Instead, it wrote an EventSourceMessage into the trace that writing the event failed.  Here is the test case:

```
using System;
using System.Diagnostics.Tracing;
using System.Text;

namespace eventsource_hugeevent
{
    [EventSource]
    class MySource : EventSource
    {
        public static MySource Log = new MySource();

        private MySource()
            : base()
        {
        }

        [Event(1)]
        public void SendEvent(string s1, string s2)
        {
            WriteEvent(1, s1, s2);
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Building a very large string.");
            int stringSize = 90947;
            StringBuilder builder = new StringBuilder(stringSize);
            for(int i=0; i<stringSize; i++)
            {
                builder.Append('A');
            }
            Console.WriteLine("Writing an event with a very large string.");
            MySource.Log.SendEvent("Foo", builder.ToString());
        }
    }
}
```

Closing this since this no longer repros.
