### ISSUE TITLE
Compiler Warning using IQueryable

### ISSUE THREAD

**Issue by HermannCalculationWorks** [dotnet/corefx#7347]
Adding a line like
`string.Empty.AsQueryable().Any(char.IsDigit);`
to a Windows Universal App will cause compiler warnings in release build:
Method 'CreateLambda' within 'System.Linq.Expressions.Expression' could not not be found.
Method 'ParameterIsAssignable' within 'System.Linq.Expressions.Expression' could not not be found.

Referenced Microsoft.NETCore.UniversalWindowsPlatform 5.0.0
Settings in Default.rd.xml have no influence.

**Comment by JonHanna** [comment]
Do you have an explicit reference to System.Linq.Expressions in you build? (if not does adding one change this?) what version is it (if not the latests pre-release, does changing to that change this?)

**Comment by HermannCalculationWorks** [comment]
There are no explicit references. It happens also in blank new VS 2015 Universal Windows app.
Adding a explicit reference to System.Linq has solved the issue.
 - thanks a lot
