### ISSUE TITLE
CharUnicodeInfo has incorrect results on Unix

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#7351]
CharUnicodeInfo is expected to return consistent (identical) results across platforms, according to the latest Unicode Standard - 8.0.0

In PR #7279 I added tests for CharUnicodeInfo: the test data comes from the [publicly available Unicode dataset](http://www.unicode.org/Public/UNIDATA/UnicodeData.txt).

The Windows tests pass, but Unix builds don't. Unfortunately, owing to a bug in xunit, we can't use [MemberData], so the first assertion failure stops all the tests from running. I presume there are more failures that therefore aren't being reported

Here are some examples of the failures. These are not the only ones - there are many more
- CodeValue: 00A7; Expected `GetUnicodeCategory`: OtherPunctuation; actual: OtherSymbol
- CodeValue: 09F4; Expected `GetNumericValue`: 0.0625; actual: 1

/cc @tarekgh

**Comment by JonHanna** [comment]
I might suspect something sourced from a different version of Unicode, but U+00A7 has been in there since forever, so it can't be that.

**Comment by JonHanna** [comment]
For that matter, so has U+09F4

**Comment by hughbe** [comment]
@JonHanna yeah I noticed that -  and taking a look at the UnicodeData.txt files for the past several versions of unicode, the categories or numeric values of these two chars haven't changed.

I presume its something to do with Unix code being in coreclr/src/mscorlib/corefx/system/globalization, and Windows code being in coreclr/src/mscorlib/system/globalization so there are different implementations

**Comment by tarekgh** [comment]
@JonHanna it is not the data only but the implementation is different too. so this issue tracking to look deeply into that and make sure we have consistent behavior between Windows and other platforms.

**Comment by tarekgh** [comment]
@joshfree I moved this to RTM milestone and I am going to send the request to the shiproom very soon.

**Comment by tarekgh** [comment]
This is fixed by the linked PR's
