### ISSUE TITLE
Help with using System.Runtime.InteropServices.RuntimeInformation with .NET 4.6

### ISSUE THREAD

**Issue by hal-ler** [dotnet/corefx#7352]
More of a question than an issues. Based on the information I found within dotnet repositories, System.Runtime.InteropServices.RuntimeInformation should also be available for .NET 4.6 (to avoid having to use #if), however if I add the dependency
`"System.Runtime.InteropServices.RuntimeInformation": "4.0.0-*"`

`dotnet restore` returns:

`System.Runtime.InteropServices.RuntimeInformation 4.0.0-rc3-23930-00 provides a compile-time reference assembly for System.Runtime.InteropServices.RuntimeInformation on .NETFramework,Version=v4.5.1, but there is no run-time assembly compatible with win7-x64.`

The runtime for this package is at `runtime.win.System.Runtime.InteropServices.RuntimeInformation`, but I cannot make a connection between the two using project.json. I tried adding `NetStandard.Library` as a dependency, but it results in weird build errors.

Any ideas about getting around this problem?

**Comment by mellinoe** [comment]
Can you try adding a reference to `Microsoft.NETCore.Platforms`?

**Comment by hal-ler** [comment]
I went back to adding `NetStandard.Library` as a dependency and found the problem on my end. I assume that is the way forward with integrating the new APIs as part of netstandard into desktop CLR builds. The problem was due to missing reference assemblies for .NET 4.6. Sorry for taking up your time.

**Comment by hal-ler** [comment]
This solution did result in `"The type 'AppContext' exists in both 'System.AppContext, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'`. I was able to get around using AppContext personally, but it might be worth to keep this in mind.
