### ISSUE TITLE
System.Collections.Concurrent.Tests.BlockingCollectionTests.TestBugFix914998 failed in Windows outerloop

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#7360]
See http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_windows_nt_debug/141/consoleFull

````
08:57:28      System.Collections.Concurrent.Tests.BlockingCollectionTests.TestBugFix914998 [FAIL]
08:57:28         Assert.Equal() Failure
08:57:28         Expected: 1
08:57:28         Actual:   -1
08:57:28         Stack Trace:
08:57:28            d:\j\workspace\outerloop_win---069ccc6f\src\System.Collections.Concurrent\tests\BlockingCollectionTests.cs(169,0): at System.Collections.Concurrent.Tests.BlockingCollectionTests.TestBugFix914998()
```

**Comment by stephentoub** [comment]
@mellinoe, you added the "blocking-clean-ci" tag.  Are you seeing this failure consistently, or did this just happen once?

**Comment by stephentoub** [comment]
My assumption, btw, is that the lab was just swamped, and this happened to run when the machine was so loaded that the 5 second timeout was exceeded, causing the test to fail:
https://github.com/dotnet/corefx/blob/master/src/System.Collections.Concurrent/tests/BlockingCollectionTests.cs#L169

**Comment by mellinoe** [comment]
Yes, I've only seen this once, I will remove the tag.
