### ISSUE TITLE
DateTimeFormatInfoGetInstance.GetInstance failed on Unix in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7367]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/debian8.2_debug_tst/764/console
```
15:21:57    System.Globalization.Tests.DateTimeFormatInfoGetInstance.GetInstance(provider: TestIFormatProviderClass { }, expected: DateTimeFormatInfo { AbbreviatedDayNames = ["Sun", "Mon", "Tue", "Wed", "Thu", ...], AbbreviatedMonthGenitiveNames = ["Jan", "Feb", "Mar", "Apr", "May", ...], AbbreviatedMonthNames = ["Jan", "Feb", "Mar", "Apr", "May", ...], AMDesignator = "AM", Calendar = GregorianCalendar { CalendarType = Localized, Eras = [...], IsReadOnly = True, MaxSupportedDateTime = 9999-12-31T23:59:59.9999999, MinSupportedDateTime = 0001-01-01T00:00:00.0000000, ... }, ... }) [FAIL]
15:21:57       Assert.Equal() Failure
15:21:57       Expected: DateTimeFormatInfo { AbbreviatedDayNames = ["Sun", "Mon", "Tue", "Wed", "Thu", ...], AbbreviatedMonthGenitiveNames = ["Jan", "Feb", "Mar", "Apr", "May", ...], AbbreviatedMonthNames = ["Jan", "Feb", "Mar", "Apr", "May", ...], AMDesignator = "AM", Calendar = GregorianCalendar { CalendarType = Localized, Eras = [...], IsReadOnly = True, MaxSupportedDateTime = 9999-12-31T23:59:59.9999999, MinSupportedDateTime = 0001-01-01T00:00:00.0000000, ... }, ... }
15:21:57       Actual:   DateTimeFormatInfo { AbbreviatedDayNames = ["���", "���", "���", "���", "���", ...], AbbreviatedMonthGenitiveNames = ["1���", "2���", "3���", "4���", "5���", ...], AbbreviatedMonthNames = ["1���", "2���", "3���", "4���", "5���", ...], AMDesignator = "������", Calendar = GregorianCalendar { CalendarType = Localized, Eras = [...], IsReadOnly = False, MaxSupportedDateTime = 9999-12-31T23:59:59.9999999, MinSupportedDateTime = 0001-01-01T00:00:00.0000000, ... }, ... }
15:21:57       Stack Trace:
15:21:57             at System.Globalization.Tests.DateTimeFormatInfoGetInstance.GetInstance(IFormatProvider provider, DateTimeFormatInfo expected)
```
cc: @tarekgh, @hughbe

**Comment by tarekgh** [comment]
looks the recent test changes has some problems. I already fixing some other issue with the current culture because the CI run machine looks using Japanese culture as default culture :-)

**Comment by JonHanna** [comment]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst_prtest/2472/consoleFull

**Comment by stephentoub** [comment]
@tarekgh, this test doesn't appear to have been updated in almost a month.  Do we know why it's only failing now?  Did something recently change in a product binary, maybe mscorlib, that would affect this?

**Comment by tarekgh** [comment]
we didn't touch such area in the code but I am noticing the other failure I got because the current culture was set to Japanese culture. so either running machine configuration is changed or the recent tests which maybe setting current culture and somehow affect other running tasks. anyway this need some investigation.

**Comment by tarekgh** [comment]
I confirm the test is wrong, looks we were just lucky before because we were running on English system. 

the test is comparing ```new DateTimeFormatInfo()``` with ```DateTimeFormatInfo.CurrentInfo``` 

CurrentInfo will use the current culture data and new DateTimeFormatInfo() will use invariant. so now running with non-English culture as current culture will cause such failure. also I don't think this is Linux specific issue.

**Comment by tarekgh** [comment]
interesting, this one I cannot repro it so far even with changing the current culture. will try to play more with it and figure out what could be wrong.

**Comment by stephentoub** [comment]
Seems like this is being caused by https://github.com/dotnet/corefx/pull/7323 (cc: @ianhays).  Specifically due to the usage of the DefaultThreadCurrentCulture properties.
