### ISSUE TITLE
Unordered `System.Linq.Parallel.Concat(...)` confusion.

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#737]
The documentation for `Concat` states:

    4287         /// <summary> 
    4288         /// Concatenates two parallel sequences. 
    4289         /// </summary> 
    4290         /// <typeparam name="TSource">The type of the elements of the input sequences.</typeparam> 
    4291         /// <param name="first">The first sequence to concatenate.</param> 
    4292         /// <param name="second">The sequence to concatenate to the first sequence.</param> 
    4293         /// <returns>A sequence that contains the concatenated elements of the two input sequences.</returns> 
    4294         /// <exception cref="T:System.ArgumentNullException"> 
    4295         /// <paramref name="first"/> or <paramref name="second"/> is a null reference (Nothing in Visual Basic). 
    4296         /// </exception> 

...which suggests to me that _unordered_ sequences should still exhibit A-then-B behavior (not helped any by the line above the previous that says: `Appends the second data source to the first, preserving order in the process.`...).  That is, this:

    int leftSize = 4;
    int rightSize = 4;

    foreach(int i in ParallelEnumerable.Range(0, leftSize).Concat(ParallelEnumerable.Range(4, rightSize)))
    {
        Console.Write("" + i);
    }

...should yield something like `02314657` (I'm not expecting the elements on each side to be ordered themselves).

Is my thinking correct, or is the documentation just leading me astray me?  Maybe I'm just hung up on the use of `Concat` for strings...

Related to (but distinct from) #584

**Comment by stephentoub** [comment]
@Clockwork-Muse, I believe the comments are just leading you astray, as you say.  To my knowledge, it was never the intention that Concat would guarantee such ordering if order preservation was disabled, and it's certainly not guaranteed by the current implementation.

**Comment by stephentoub** [comment]
@Clockwork-Muse, I'm going to close this issue, as it doesn't look like there's actually a problem here.  If you disagree and there's an additional issue I'm not aware of, please feel free to reopen or to open a new issue.  Thanks.
