### ISSUE TITLE
Consider adding PureAttribute to IntrospectionExtensions.GetTypeInfo

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/corefx#7377]
Porting some code to .NET Core, I encountered the following code:

```C#
public static Type FindImplementationType(Type type, ObjectLiteral objLit, Func<string> getResolverKind)
{
    Contract.Requires(type.IsInterface);
    // ...
}
```

So I added the call to GetTypeInfo():

```C#
Contract.Requires(type.GetTypeInfo().IsInterface);
````

However, when code contracts actually runs, I get the following error:

> error CC1036: Detected call to method 'System.Reflection.IntrospectionExtensions.GetTypeInfo(System.Type)' without [Pure] in contracts of method 'Util.ConfigurationConverter.FindImplementationType(System.Type,ObjectLiteral,System.Func`1<System.String>)'

Is it possible to add a PureAttribute to the GetTypeInfo() method?  That seems like it might be a dependency we don't want to add to the contract, is there another way of specifying that a method is pure for code contracts?  Should the attribute at least be added to the .NET Framework version of this method?

**Comment by hughbe** [comment]
I don't think corex uses code contracts: perhaps its a good idea to replace this with a Debug.Assert?

**Comment by joshfree** [comment]
@weshaggard @pallavit

**Comment by weshaggard** [comment]
I wouldn't consider GetTypeInfo as pure there are definitely potential side-effect that might occur in that extension method. Today on desktop it might be pure but I would still not fill comfortable adding it there either because it may not always be pure. 

Thanks for the suggestion @dsplaisted but think I'm going to close this.
