### ISSUE TITLE
Add more tests around Enum.TryParse

### ISSUE THREAD

**Issue by AlexGhiondea** [dotnet/corefx#738]

**Comment by AlexGhiondea** [comment]
@Alex999 I know you did some work around this -- would you be interested in picking this up?

**Comment by Alexx999** [comment]
@AlexGhiondea yeah, sure, I can do it.
This tests must cover all the edge cases I found?

**Comment by AlexGhiondea** [comment]
Thank you @Alexx999 

Ideally yes, we should cover all of them. 

We might have some issues with the ones that can't be expressed in C# as we don't have any other tests (in CoreFx) like that :).

**Comment by Alexx999** [comment]
Actually there is something - System.Reflection.Metadata has at lest 2 tests with IL files (and pre-compiled assemblies).
Probably here we can go same way - add pre-compiled binaries plus IL sources.

**Comment by hughbe** [comment]
This has been fixed by #5810 and #7620 so I reckon it can be closed?

**Comment by stephentoub** [comment]
Yup.  Thanks, @hughbe.
