### ISSUE TITLE
Unix builds fail when trying to sign a project

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#7383]
Calling `./build.sh /p:ConfigurationGroup=Release` throws the following error:

```
CSC : error CS7027: Error signing output with public key from file '/mnt/j/workspace/dotnet_corefx/outerloop_ubuntu14.04_release/Tools/Test.snk' -- Cannot marshal 'return value': Unknown error. [/mnt/j/workspace/dotnet_corefx/outerloop_ubuntu14.04_release/src/System.Globalization/tests/System.Globalization.Tests.csproj]
```

[Here is a sample](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_ubuntu14.04_release/58/consoleFull) of a build that is running into the issue.

**Comment by joperezr** [comment]
@tarekgh Looks like your change #7354 broke the build in non-Windows. The reason is that portable roslyn compilers don't support signing yet. Do you mind taking a look?

**Comment by joperezr** [comment]
I suppose [this add](https://github.com/dotnet/corefx/pull/7354/files#diff-d73f3353526d9613993ed9f955c987afR156) is what broke it, but I'm not sure. If so, maybe we should condition on OS being Windows for this?

**Comment by stephentoub** [comment]
It's not just Ubuntu:
e.g.
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_ubuntu14.04_release/58/consoleFull
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_ubuntu14.04_debug/64/consoleFull
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_osx_release/61/consoleFull
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_centos7.1_release_bld/42/consoleFull

**Comment by joperezr** [comment]
Related: dotnet/roslyn#8210

**Comment by tarekgh** [comment]
sorry about that. really my changes pass the CI checks so I am not sure why it didn't complain about it. I'll try to submit a fix soon.

**Comment by stephentoub** [comment]
> really my changes pass the CI checks so I am not sure why it didn't complain about it.

None of the PR CI legs using msbuild/csc.exe on Unix.

**Comment by joperezr** [comment]
> None of the PR CI legs use msbuild/csc.exe on Unix

Now that we have /m in .Net Core MSBuild, we are really close to enabling CI to use build.sh :smile:

**Comment by tarekgh** [comment]
I submitted the PR 
https://github.com/dotnet/corefx/pull/7393
