### ISSUE TITLE
System.Resources.WindowsRuntimeResourceManager not available in System.Runtime.WindowsRuntime for netcore50

### ISSUE THREAD

**Issue by drieseng** [dotnet/corefx#7387]
I'm trying to use CoreFX in a vanilla UWP 10.0 project targeting Windows Mobile 10 ARM.
However when I run the app on my device, I get the following exception:

Could not load type 'System.Resources.WindowsRuntimeResourceManager' from assembly 'System.Runtime.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

Now, apparrently this class is only included when **FEATURE_APPX** is defined which is not for the **netcore50** TFM.

I have a few questions with this:
* Why is this class not included for **netcore50** (it's only included in the **netstandard1.3** assembly)?
 See [here](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.WindowsRuntime/src/System.Runtime.WindowsRuntime.csproj) and [here] (https://github.com/dotnet/corefx/blob/master/src/System.Runtime.WindowsRuntime/src/System/Resources/WindowsRuntimeResourceManager.cs). 

* Is it correct that nuget uses **netcore50** assemblies for UWP 10.0 ?
  See [build log](https://github.com/dotnet/corefx/files/197491/BuildLog.txt).

* Is it correct that nuget uses the **win8** runtime (with the **netcore50** TFM) of **System.Runtime.WindowsRuntime** for UWP 10.0 apps targeting Windows 10 Mobile ARM ?
  See [build log](https://github.com/dotnet/corefx/files/197491/BuildLog.txt).

* Perhaps the most important question: is it all too soon to attempt to use the CoreFX libraries in UWP projects ?

**Comment by weshaggard** [comment]
We don't publicly expose WindowsRuntimeResourceManager on any platform, how are you calling it on anywhere? 

>Is it correct that nuget uses netcore50 assemblies for UWP 10.0 ?

Yes the nuget TFM we use for most of our libraries targeting UWP is netcore50. 

>Is it correct that nuget uses the win8 runtime (with the netcore50 TFM)

Yes that is the one that gets selected for this library. The runtime ides form a hierarchy so we find the one that is the most specific, and for this there isn't anything needed beyond win8 to support it so the asset goes into the win8 folder. 

>Perhaps the most important question: is it all too soon to attempt to use the CoreFX libraries in UWP projects ?

The ones that actually support UWP should be usable in UWP today, note that not all libraries are supported there. Our current nuget packages have been changes to add support for netstandard which is exposing some bugs when consuming in UWP so some might be broken currently but if you see any issues please file them.

**Comment by drieseng** [comment]
I'm not creating a **WindowsRuntimeResourceManager** instance myself, it's being created by [System.Resources.ResourceManager] (https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Resources/ResourceManager.cs):

```cs
// Since we can't directly reference System.Runtime.WindowsRuntime from mscorlib, we have to get the type via reflection. 
// It would be better if we could just implement WindowsRuntimeResourceManager in mscorlib, but we can't, because 
// we can do very little with WinRT in mscorlib. 
[SecurityCritical] 
internal static WindowsRuntimeResourceManagerBase GetWinRTResourceManager() 
{ 
	Type WinRTResourceManagerType = Type.GetType("System.Resources.WindowsRuntimeResourceManager, " + AssemblyRef.SystemRuntimeWindowsRuntime, true); 
	return (WindowsRuntimeResourceManagerBase)Activator.CreateInstance(WinRTResourceManagerType, true); 
} 
```
If I look at the build log of Visual Studio, I can see that it's correctly deploying the version of the CoreFX assemblies that I specified in my project.json (rc3-23931-00):

```
Copying file "<profile dir>\.nuget\packages\runtime.any.System.Threading.Tasks\4.0.11-rc3-23931-00\lib\netcore50\System.Threading.Tasks.dll" to layout "System.Threading.Tasks.dll"...
Copying file "<profile dir>\.nuget\packages\runtime.any.System.Threading.Timer\4.0.1-rc3-23931-00\lib\netcore50\System.Threading.Timer.dll" to layout "System.Threading.Timer.dll"...
Copying file ""<profile dir>\.nuget\packages\System.ComponentModel\4.0.1-rc3-23931-00\lib\netcore50\System.ComponentModel.dll" to layout "System.ComponentModel.dll"...
Copying file ""<profile dir>\.nuget\packages\System.ComponentModel.Annotations\4.1.0-rc3-23931-00\lib\netstandard1.4\System.ComponentModel.Annotations.dll" to layout "System.ComponentModel.Annotations.dll"...
```
However, it's not deploying the CoreCLR runtime for ARM:

```
Checking whether required frameworks are installed...
Framework: Microsoft.NET.CoreRuntime.1.0/ARM, app package version 1.0.23430.0 is installed.
Framework: Microsoft.VCLibs.140.00.Debug/ARM, app package version 14.0.23824.1 is installed.
```

Now, the questions I have with this are:
* should it be possible to use the CoreFX libraries with this runtime ?
* or is it in fact the CoreCLR runtime that's trying to create a **WindowsRuntimeResourceManager** instance ? In which case, it means that **FEATURE_APPX** is defined for the CoreCLR runtime but not for the corresponding **System.Runtime.WindowsRuntime**.

**Comment by weshaggard** [comment]
@ericstj looks like another potential issue with our prerelease packages being consume in UWP.

**Comment by ericstj** [comment]
We have two builds of this contract.  One for NETNative and one for CoreCLR.  Only the CoreCLR version should be getting WindowsRuntimeResourceManager.

The cause of this bug is an incorrect RID
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.WindowsRuntime/src/System.Runtime.WindowsRuntime.csproj#L16

This is using the `win8` RID even for NETNative configuration.  Instead it should be using an AOT rid for NETNative.  /cc @chcosta

**Comment by anders9ustafsson** [comment]
@ericstj I get this exact error message when I am trying out .NET Core 1.0 RC2.

I have created a simple .NET Core class library, *netstandard* 1.4, which I am consuming from a *UWP* application. After some struggle I have found the correct *Microsoft.NETCore.UniversalWindowsPlatform* dependency, namely 5.2.0-rc2-24027.

When I start my UWP application (Debug mode, x86), I get the `TypeLoadException` with the message

> Could not load type 'System.Resources.WindowsRuntimeResourceManager' from assembly 'System.Runtime.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.":"System.Resources.WindowsRuntimeResourceManager

This happens immediately in the `MainPage` constructor when calling `InitializeComponent()`.

**Comment by ericstj** [comment]
We specifically didn't release the UWP meta-package at RC2.  There are a number of known issues with the RC2 packages when consumed by UWP applications.  We fixed all of those in RC3.  If you'd like to test out consuming `netstandard` libraries in a UWP app please use the RC3 package from https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
