### ISSUE TITLE
Boolean System.Console.get_KeyAvailable()

### ISSUE THREAD

**Issue by bruno-garcia** [dotnet/corefx#7391]
Following issue: #2936 I made a small project referencing the dev nuget feed.
When using `SystemConsole.KeyAvailable`, I'm getting an error:

System.MissingMethodException: Method not found: 'Boolean System.Console.get_Key
Available()'.
   at SharpSyslogServer.Console.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly,
 String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b_
_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

The version I'm using is: "System.Console": "4.0.0-rc2-23826",
And the branch with the code to reproduce it: https://github.com/bruno-garcia/SharpSyslogServer/tree/system-console-issue

**Comment by pallavit** [comment]
@bruno-garcia Would you mind using the most recent package from nuget? We consume this method in our tests everyday w/o issue.

**Comment by bruno-garcia** [comment]
I'm using the dev nuget feed as I mentioned: https://www.myget.org/F/aspnetvnext/api/v2/
![image](https://cloud.githubusercontent.com/assets/1633368/14225316/e980b5dc-f8be-11e5-81d9-ea17be0e33f0.png)

I see no updates.

Is it not version rc2-23826?
![image](https://cloud.githubusercontent.com/assets/1633368/14225326/565292b6-f8bf-11e5-87a5-347c80939cb3.png)

**Comment by ianhays** [comment]
>KeyAvailable wasn't there yet

It is available in the most recent package in the [.net core feed](https://www.myget.org/F/dotnet-core/).
