### ISSUE TITLE
Regression in StringBuilder.AppendLine and Console.Write and Console.WriteLine

### ISSUE THREAD

**Issue by ljw1004** [dotnet/corefx#7409]
This code:
```csharp
static void Main()
{
    var sb = new StringBuilder();
    sb.Append("hello");
    sb.AppendLine();
    sb.AppendLine();
    sb.Append("world");
    sb.AppendLine();
    var s = sb.ToString();
    Console.WriteLine(s);
}
```

In .NET Framework 4.6, it prints this output (with a completely empty line between the two words):
```
hello

world
```

But when I write it in a dotnet-cli console app (generated using "dotnet new", and targeting 
`"frameworks": {"netstandard1.5"}` and dependency `"Microsoft.NETCore.App": { "version": "1.0.0-rc2-23930"}`, then it omits the blank line:
```
hello
world
```

**Comment by joshfree** [comment]
@steveharter PTAL

**Comment by ljw1004** [comment]
I've changed the title to indicate further repros. Here's some code:
```cs
Console.Write("hello" + Environment.NewLine);
Console.Write(Environment.NewLine);
Console.WriteLine();
Console.Write("world" + Environment.NewLine);
```

What I expect: two empty lines
```
hello

world
```

What I get: no empty lines
```
hello
world
```

**Comment by svick** [comment]
I get the wrong output with `dotnet run`, but not with `dotnet exec`. I think that means this is a bug in `dotnet run`.

**Comment by svick** [comment]
dotnet/cli#2235 should fix this.

**Comment by ljw1004** [comment]
@svick is there any documentation on "dotnet exec"? How do you use it? (when I do "dotnet -h" it doesn't suggest 'exec' as an option, and when I do "dotnet exec -h" it complains that this is invalid).

**Comment by svick** [comment]
@ljw1004 I don't think there is. When I run `dotnet exec -h`, it says "dotnet exec needs a dll to execute" and that's how I used it.

In my case, I could either use `dotnet run` or `dotnet exec bin\Debug\netstandard1.5\myapp.dll`.

**Comment by stephentoub** [comment]
As this isn't actually a bug in corefx, I'm closing this out.  Thanks.
