### ISSUE TITLE
Feature: Need to create a solution for building localized binaries

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#743]
We need to come up with a solution to enable building localized binaries as well as taking contributions to localized content.

**Comment by tarekgh** [comment]
@joshfree, I thought the localization support was going to be added by @naamunds. am I wrong? you may look at #2713 which has the initial support I guess. 

CC @weshaggard

**Comment by joshfree** [comment]
@tarekgh I hadn't heard that - feel free to update / reassign

**Comment by naamunds** [comment]
In September, we decided to postpone the localization work.  We will tentatively resume it around the beginning of December.

**Comment by mellinoe** [comment]
@naamunds What's the current thinking around this? Should we close this issue and open something more specific?

**Comment by naamunds** [comment]
@mellinoe I'm not sure what the current plan is for localization. I think it's more of a product roadmap question, and @Petermarcu and @richlander would be better able to address it.

**Comment by mellinoe** [comment]
We discussed this briefly today. The main problem discussed was that NuGet and Visual Studio do not support this at all anymore. Even past that, there was some discussion on whether we should even ship localized strings for our exception messages, or whether having English-only exception messages is acceptable.

**Comment by weshaggard** [comment]
Closing this as we don't really have a loc story for our nuget packages at this time with no real plans to fully add that at this point in time.

**Comment by krwq** [comment]
One scenario where exceptions would be valuable are validators. One example would be XmlSchema. It is pretty useful to give developer a localized error - XmlSchema error will quite often resurface to the end user. XML is one of those file formats which is used not only by developers.

**Comment by weltkante** [comment]
Just for the record, this breaks the validation story of UI frameworks like WPF and WinForms, which rely on the exception messages to be readable to the end user.
