### ISSUE TITLE
GetFullPath_Windows_83Paths  failed on Windows Nano

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#7433]
```
19:42:53 Discovering: System.Runtime.Extensions.Tests
19:42:53 Discovered:  System.Runtime.Extensions.Tests
19:42:54 Starting:    System.Runtime.Extensions.Tests
19:42:54    System.IO.Tests.PathTests.GetFullPath_Windows_83Paths [FAIL]
19:42:54       Assert+WrapperXunitException : File path: d:\j\workspace\outerloop_win---ce410c48\src\System.Runtime.Extensions\tests\System\IO\PathTests.cs. Line: 650
19:42:54       ---- Assert.Equal() Failure
19:42:54                             â†“ (pos 12)
19:42:54       Expected: C:\Windows\TEMP\2516432d47634334a66fb171ea9af088.txt
19:42:54       Actual:   C:\Windows\Temp\2516432d47634334a66fb171ea9af088.txt
19:42:54                             â†‘ (pos 12)
19:42:54       Stack Trace:
19:42:54             at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber)
19:42:54             at Assert.Equal(String expected, String actual, String path, Int32 line)
19:42:54             at System.IO.Tests.PathTests.GetFullPath_Windows_83Paths()
19:42:54          ----- Inner Stack Trace -----
19:42:54             at Assert.Equal(String expected, String actual, String path, Int32 line)
19:42:55 Finished:    System.Runtime.Extensions.Tests
```

`GetTempPath` and `GetFullPath` returning temp path with different casing?

cc @JeremyKuhne

**Comment by ianhays** [comment]
When we get a full temporary path we call Path.GetfullPath on it, so subsequent GetFullPath calls likely won't change the case further. It is the shortening of the path that is causing issue. I'd guess this is a bug in WinNano's implementation of GetShortPathName or GetLongPathNameW, but I'll have to set up a WinNano machine to figure out for sure.

**Comment by JeremyKuhne** [comment]
It is also possible/likely that this has to do with how the TEMP environment variable is set. If it isn't canonical that could impact what we get back- the expansion of 8.3 has to actually get the "real" file name, the [GetTempPath ](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364992(v=vs.85).aspx)() function is simply an environment variable getter.

GetFullPathName() does not canonicalize casing.

**Comment by AlexGhiondea** [comment]
@ianhays @JeremyKuhne can this be closed?

**Comment by Jiayili1** [comment]
This issue is repro, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170508.01/workItem/System.Runtime.Extensions.Tests/analysis/xunit/System.IO.Tests.PathTests~2FGetFullPath_Windows_83Paths

**Comment by Jiayili1** [comment]
This issue is repro on Core Tests in build 20170510.01, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170510.01/workItem/System.Runtime.Extensions.Tests/analysis/xunit/System.IO.Tests.PathTests~2FGetFullPath_Windows_83Paths
