### ISSUE TITLE
ASP.NET Core 1.0 - FTP upload files

### ISSUE THREAD

**Issue by ge6a93** [dotnet/corefx#7439]
Hi, I'm trying to upload files to a FTP server. I've tried using old piece of code I've used ASP.NET MVC 5 but DNX Core does not see to provide FtpWebRequest class for FTP manipulation. One workaround has come to my mind to use HttpClient with external Web service (WebAPI 2) which will upload my files, but I would have to maintain two applications and I don't like this approach... So is there any other approach I could use and I'm apparently missing? Thanks!

![ftp](https://cloud.githubusercontent.com/assets/5251112/14212399/56cff172-f83b-11e5-9eb9-36905de58c6f.png)

**Comment by svick** [comment]
I believe `FtpWebRequest` is not available on .Net Core. `WebRequest` on .Net Core is just a wrapper around `HttpCLient` and it does not support FTP. I also didn't find any Core-compatible packages for FTP after a cursory search of NuGet.

The confusing thing is that if you remove the cast to `FtpWebRequest`, and don't set `FtpWebRequest`-specific properties, then `WebRequest.Create()` succeeds (I think it's because of [this line](https://github.com/dotnet/corefx/blob/d1a3d8dff8836dea02d460e2f6f8a69e738de603/src/System.Net.Requests/src/System/Net/WebRequest.cs#L361)), but then fails when you actually try to retrieve the request. Is there any reason to pretend FTP is supported like this?

**Comment by davidsh** [comment]
These lines in `WebRequest.cs` should have never been ported to CoreFx:

```c#
prefixList.Add(new WebRequestPrefixElement("file:", new HttpRequestCreator())); 
prefixList.Add(new WebRequestPrefixElement("ftp:", new HttpRequestCreator())); 
```

CoreFx doesn't support file: or ftp: schemes for WebRequest classes.  Only the HttpWebRequest is supported on CoreFx.

We will submit a PR to fix this.

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by MaximRouiller** [comment]
@davidsh Any plan to support it by RTM?

**Comment by davidsh** [comment]
>Any plan to support it by RTM?

What do you mean by "it"?  If you mean "we will support FtpWebRequest class in CoreFx", the answer is no.  We have no plans to do that. There are better architectures and coding patterns for Ftp than the 'FtpWebRequest' pattern.  There are several 3rd party libraries (FtpClient) out there.

**Comment by MaximRouiller** [comment]
Not `FtpWebRequest` per se. Just 'FTP'. Is it something the team want to spend time on or is it a scenario where the decision has been made to rely on 3rd party libraries?

**Comment by davidsh** [comment]
Currently Ftp is not a priority.  And there are many 3rd party libraries to fill the gap right now.

**Comment by svick** [comment]
@davidsh Are you aware of any third party FTP libraries that support .Net Core?

**Comment by davidsh** [comment]
I am not aware of any specific libraries that target .NET Core.  But we haven't really been looking lately. As I mentioned, Ftp is not a priority for the team right now.

**Comment by MaximRouiller** [comment]
Thanks for the clarification @davidsh

**Comment by maliu1970** [comment]
Does anyone know which ftp utility can be used with .NETCore RC2?

**Comment by stephendrew** [comment]
> there are many 3rd party libraries to fill the gap right now.

> I am not aware of any specific libraries that target .NET Core.

Eh? :)

Here is one potential: [CoreFTP](https://github.com/sparkeh9/CoreFTP), although i have yet to use it.

**Comment by sharpcoder28** [comment]
What are these better architectures and patterns you spreak of?

**Comment by davidsh** [comment]
FtpWebRequest is supported now as part of .NET Core 2.0 (NETStandard2.0).

You can try it out in the previews releases or use the daily code in master branch.
