### ISSUE TITLE
HttpClient not stripping Content-Length header after redirect on non-Windows systems

### ISSUE THREAD

**Issue by cesarbs** [dotnet/corefx#7440]
Scenario:

1) Client sends POST to server with some content.
2) Server sends 302 response.
3) Client sends GET to redirect location **with Content-Length from original POST request but no content**.

Example:

Client:

    POST / HTTP/1.1
    Host: 10.135.34.146:5000
    Accept: */*
    Accept-Encoding: gzip,deflate
    Content-Type: text/plain; charset=utf-8
    Content-Length: 7
    Expect: 100-continue

    content

Server:

    HTTP/1.1 302 Found
    Date: Fri, 01 Apr 2016 17:48:58 GMT
    Content-Length: 0
    Location: /Somewhere
    Server: Kestrel

Client:

    GET /Somewhere HTTP/1.1
    Host: 10.135.34.146:5000
    Accept: */*
    Accept-Encoding: gzip,deflate
    Content-Type: text/plain; charset=utf-8
    Content-Length: 7     <----------------------- wrong

    <no content>

This is breaking one of our functional tests: https://github.com/aspnet/MusicStore/blob/dev/test/E2ETests/OpenIdConnectTests.cs

Reproes on Linux and Mac.

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by muratg** [comment]
:eyes:
