### ISSUE TITLE
Many solutions fail to build in VS without a full build.cmd first

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#745]
The culprit in most cases is a missing project reference to XunitTraitsDiscoverers. VS needs the targets of project references to be in the scope of the current solution. While we could go and add this project everywhere, I think it will clutter the solutions. A better approach might be to use shared source files that we pull in the test targets/props.

**Comment by nguerrera** [comment]
cc @weshaggard @krwq

**Comment by ellismg** [comment]
@nguerrera was this fixed by #796?

**Comment by weshaggard** [comment]
@ellismg no this isn't fixed by that change. I've got a change where I'm creating this library as a nuget package and we will reference it via packages as opposed to a project reference which will take care of this. I hope to finish that sometime this week.

**Comment by ellismg** [comment]
Thanks!

**Comment by weshaggard** [comment]
This issue has been fixed by #1668.
