### ISSUE TITLE
Outerloop OSX/Ubuntu CI is running tests using the wrong platform's binaries

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#7455]
See this Ubuntu run: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_ubuntu14.04_debug/69/consoleFull

Windows binary on Ubuntu14.04:
````
15:51:41      System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetUnicode_Invalid [FAIL]
15:51:41         System.TypeInitializationException : The type initializer for 'System.PlatformDetection' threw an exception.
15:51:41         ---- System.DllNotFoundException : Unable to load DLL 'ntdll.dll': The specified module could not be found.
15:51:41          (Exception from HRESULT: 0x8007007E)
15:51:41         Stack Trace:
15:51:41               at System.PlatformDetection.get_IsWindows7()
15:51:41               at System.Globalization.Tests.Factory.GetIdnaTestTxt()
````

OSX binary on Ubuntu14.04:
````
15:59:26      ChangedTests.FileSystemWatcher_Changed_SymLinkFileDoesntFireEvent [FAIL]
15:59:26         System.DllNotFoundException : Unable to load DLL '/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation': The specified module could not be found.
15:59:26          (Exception from HRESULT: 0x8007007E)
15:59:26         Stack Trace:
15:59:26               at Interop.CoreFoundation.CFStringCreateWithCString(IntPtr allocator, String str, CFStringBuiltInEncodings encoding)
15:59:26               at Interop.CoreFoundation.CFStringCreateWithCString(String str)
15:59:26               at System.IO.FileSystemWatcher.RunningInstance.Start()
````

This does not repro if you build the test projects individually, so I suspect something has regressed in the full traversal build very recently. I think it may have something to do with the new test.builds files.

@sokket @Priya91

**Comment by sokket** [comment]
It looks like the build script isn't being passed an OSGroup like the inner loop CI, so there must have been a regression in the platform detection that is used to determine the runtime identifier.

**Comment by sokket** [comment]
I'll assign this to me and start taking a look

**Comment by mellinoe** [comment]
I also see this in my local testing on OS X when running

````
sudo ./build.sh /p:ConfigurationGroup=Debug /p:Outerloop=true /p:TestWithLocalLibraries=true
````

which should be equivalent to what the outer loop CI job does. It doesn't look like the outer loop job from this morning hit these errors though (other errors instead).

**Comment by sokket** [comment]
Hmm maybe it's something else then...my change went in yesterday so it should have been reflected in this mornings build. Weird though since none of the new PRs from today immediately jump out as affecting this build path

**Comment by sokket** [comment]
@mellinoe Do the Windows bits have the right runtime?

**Comment by mellinoe** [comment]
I don't see any failures like this in the latest outerloop Windows runs. I just started a new Win7 Outerloop run since the newest was from this morning.

**Comment by sokket** [comment]
Trying to get a repro locally now

**Comment by sokket** [comment]
I worked with Eric and it looks like this could be due to a lack of filtering in OuterLoop; we build all the tests and it looks like we then try to run all of them, including tests built for other platforms. I'm going to try re-enabling filtering for OuterLoop and see if my theory is correct

**Comment by sokket** [comment]
@mellinoe and I were debugging this separately and he found that this can repro when trying to build a single csproj file...looks like there is different, underlying issue here

**Comment by mellinoe** [comment]
This should be fixed now. Hopefully we can prevent future regressions with #7709.
