### ISSUE TITLE
IdnMapping unnecessarily allocates substrings

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#7457]
Discovered this while going through the code in #7291. It looks like `IdnMapping` is allocating a substring where it shouldn't need to, specifically [here](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Globalization/IdnMapping.cs#L85) and [here](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Globalization/IdnMapping.cs#L132). I'm going to open up a PR in a couple of days for this when I have time, but I'm raising an issue here first as a self-reminder.

**Comment by steveharter** [comment]
The code in question allocates a substring like:
    unicode = unicode.Substring(index, count);
If index !=0 and count != unicode.Length then the allocation isn't necessary, otherwise it is. I assume the intended optimization is:
if (index != 0 || count != unicode.Length)
    unicode = unicode.Substring(index, count);

**Comment by svick** [comment]
@steveharter [`string.Substring()` is optimized for that](https://github.com/dotnet/coreclr/blob/ebb839f3218a9410f76f4595574155304c5e101e/src/mscorlib/src/System/String.cs#L1331-L1333) and already doesn't allocate a new string in that case.
