### ISSUE TITLE
Cookie class does not abide by the MSDN docs

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#7459]
## Cookie Constructor (String, String)

A `CookieException` is thrown in the following circumstances, according to MSDN:
- The `name` parameter is null.
- The `name` parameter is of zero length.
- The `name` parameter contains an invalid character.
- **The `value` parameter is null.**
- **The `value` parameter contains a string not enclosed in quotes that contains an invalid character.**

The circumstances in bold are currently not followed by the Cookie class - no exception is thrown, but MSDN tells us one should be.
## Cookie.Value Property

This field has the following remark:
**The Value of a Cookie must not be null. The following characters are reserved and cannot be used for this property: semicolon, comma.**
- MSDN does not make it clear if an exception is thrown or not in the above circumstances.
- However, in corefx, the second condition is not checked. If a value is null, it is converted to an empty string.
## Solutions
- Fix the documentation according to the current behaviour
- Adapt the documentation for Cookie.Value Property and change some current behaviour
- Change all the behaviours to that described in the MSDN docs
## Notes
- Corefx currently aligns with the behaviour of .NET desktop (no exceptions are thrown there)
- I reckon its quite important to ensure that Cookie.Value can never be null, as this is documented in MSDN and therefore can lead to NREs. The solutions to this are throwing an exception or setting Cookie.Value to string.Empty

/cc @davidsh

**Comment by karelz** [comment]
Looks like we need to change the docs.
@hughbe do you have links to MSDN which need to be changed? Do you have proposed wording change?

**Comment by ViktorHofer** [comment]
@karelz it's this one: https://msdn.microsoft.com/en-us/library/kesbe27x(v=vs.110).aspx

**Comment by karelz** [comment]
Thanks @ViktorHofer can you please suggest the exact wording change? It will much easier for our docs team to 'fix' the language, when they have technical details laid out.
I can then move it to docs repo ... thanks!

**Comment by ViktorHofer** [comment]
As agreed offline I will directly edit it in the new open docs site https://docs.microsoft.com/en-us/dotnet/api/system.net.cookie.-ctor?view=netcore-1.1.0 and will then link the PR here

**Comment by karelz** [comment]
Great, thanks! Once you create the PR (please add me on CC), please close this issue. We do not have to block on docs change completion in CoreFX ... supplying the right info into docs is enough for us to close here.
