### ISSUE TITLE
The top-level src/ folder is cluttered with all of those .slns

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#746]
IMHO, each library should have its sln file within its own folder. 

Instead of
```
src\
    System.Xyz\
    System.Xyz.sln
```

We should have

```
src\
    System.Xyz\
          System.Xyz.sln
```

I believe the reasons why we had the former originally are obsolete now.

1) We liked the idea of grouping related libraries together in a solution. Today, only System.Xml.* does this. However, it will not really work long-term because we shouldn't have library-to-library project-to-project references as it messes with our package versioning story post-V1.

2) We had problems with redundant packages/ folders. I believe this was solved by the NuGet.config change that moved packages to a folder at the root outside of src

**Comment by nguerrera** [comment]
cc @weshaggard @davkean

**Comment by davkean** [comment]
+1

**Comment by ilmax** [comment]
+1

**Comment by weshaggard** [comment]
Fixed by @Maxwe11 with PR #777

**Comment by nguerrera** [comment]
Thanks @Maxwe11!

**Comment by davkean** [comment]
@Maxwe11 awesome!
