### ISSUE TITLE
Two CNG tests failing on Win8 outerloop

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7465]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_windows_nt_debug/146/consoleFull
```
14:10:20      System.Security.Cryptography.Cng.Tests.TripleDESCngTests.VerifyMachineKey [FAIL]
14:10:20         Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Access denied
14:10:20         Stack Trace:
14:10:20            D:\j\workspace\outerloop_win---069ccc6f\src\System.Security.Cryptography.Cng\src\System\Security\Cryptography\CngKey.Create.cs(53,0): at System.Security.Cryptography.CngKey.Create(CngAlgorithm algorithm, String keyName, CngKeyCreationParameters creationParameters)
14:10:20            D:\j\workspace\outerloop_win---069ccc6f\src\System.Security.Cryptography.Cng\tests\SymmetricCngTestHelpers.cs(240,0): at System.Security.Cryptography.Cng.Tests.SymmetricCngTestHelpers.VerifyMachineKey(CngAlgorithm algorithm, Int32 plainBytesCount, Func`2 persistedFunc, Func`1 ephemeralFunc)
14:10:20            D:\j\workspace\outerloop_win---069ccc6f\src\System.Security.Cryptography.Cng\tests\TripleDESCngTests.cs(79,0): at System.Security.Cryptography.Cng.Tests.TripleDESCngTests.VerifyMachineKey()
14:10:20      System.Security.Cryptography.Cng.Tests.AesCngTests.VerifyMachineKey [FAIL]
14:10:20         Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Access denied
14:10:20         Stack Trace:
14:10:20            D:\j\workspace\outerloop_win---069ccc6f\src\System.Security.Cryptography.Cng\src\System\Security\Cryptography\CngKey.Create.cs(53,0): at System.Security.Cryptography.CngKey.Create(CngAlgorithm algorithm, String keyName, CngKeyCreationParameters creationParameters)
14:10:20            D:\j\workspace\outerloop_win---069ccc6f\src\System.Security.Cryptography.Cng\tests\SymmetricCngTestHelpers.cs(240,0): at System.Security.Cryptography.Cng.Tests.SymmetricCngTestHelpers.VerifyMachineKey(CngAlgorithm algorithm, Int32 plainBytesCount, Func`2 persistedFunc, Func`1 ephemeralFunc)
14:10:20            D:\j\workspace\outerloop_win---069ccc6f\src\System.Security.Cryptography.Cng\tests\AesCngTests.cs(82,0): at System.Security.Cryptography.Cng.Tests.AesCngTests.VerifyMachineKey()
```

**Comment by bartonjs** [comment]
@Priya91 Do we have a standard runtime test for "am I an administrator?" on Windows?  It seems that CNG machine key creation is restricted to administrators (by default):

```
  NT AUTHORITY\SYSTEM:(OI)(CI)(F)
  BUILTIN\Administrators:(OI)(CI)(F)
  Everyone:(OI)(CI)(R)
```

**Comment by Priya91** [comment]
@bartonjs Are you asking if there's a way you can query to see if the test is run as admin? We dont have that. Although all windows tests are run elevated, as the jenkins slave is run as admin.

**Comment by bartonjs** [comment]
@Priya91 I hate to ask this question, but "are you sure?".  The console logs show a lot of messages like
```
You do not have sufficient privilege to perform this operation.
```

It rather feels like on this machine the test agent was running as a low rights user.  I can start seeking a local mitigation, but want to make sure that the infrastructure is doing what we think it is, first.

**Comment by Priya91** [comment]
As far as i read from the netci.groovy files, we are using the same OS label ```auto-win2012-20160325``` for innerloop and outerloop ```Windows_NT```, with similar init script for both runs. By that, innerloop and outerloop should both be running tests elevated, maybe we do further configuration for this. @mmitche Any insights here?

**Comment by bartonjs** [comment]
@Priya91 The ServiceController tests had a ConditionalFact for administrator rights, and it fails (aka skips the tests) on outerloop_windows_nt_debug:

> 10:59:57   Starting:    System.ServiceProcess.ServiceController.Tests
10:59:57      System.ServiceProcess.Tests.ServiceControllerTests.ConstructWithServiceName [SKIP]
10:59:57         Condition(s) not met: "RunningWithElevatedPrivileges"
10:59:57      System.ServiceProcess.Tests.ServiceControllerTests.ConstructWithDisplayName [SKIP]
10:59:57         Condition(s) not met: "RunningWithElevatedPrivileges"
10:59:57      System.ServiceProcess.Tests.ServiceControllerTests.StopAndStart [SKIP]
10:59:57         Condition(s) not met: "RunningWithElevatedPrivileges"
10:59:57      System.ServiceProcess.Tests.ServiceControllerTests.ConstructWithMachineName [SKIP]
10:59:57         Condition(s) not met: "RunningWithElevatedPrivileges"
10:59:57      System.ServiceProcess.Tests.ServiceControllerTests.ControlCapabilities [SKIP]
10:59:57         Condition(s) not met: "RunningWithElevatedPrivileges"
10:59:57      System.ServiceProcess.Tests.ServiceControllerTests.ServicesStartMode [SKIP]
10:59:57         Condition(s) not met: "RunningWithElevatedPrivileges"
10:59:57      System.ServiceProcess.Tests.ServiceControllerTests.PauseAndContinue [SKIP]
10:59:57         Condition(s) not met: "RunningWithElevatedPrivileges"
10:59:57      System.ServiceProcess.Tests.ServiceControllerTests.GetServices [SKIP]
10:59:59         Condition(s) not met: "RunningWithElevatedPrivileges"
10:59:59      System.ServiceProcess.Tests.ServiceControllerTests.StartWithArguments [SKIP]
10:59:59         Condition(s) not met: "RunningWithElevatedPrivileges"
10:59:59      System.ServiceProcess.Tests.ServiceControllerTests.Dependencies [SKIP]
10:59:59         Condition(s) not met: "RunningWithElevatedPrivileges"
10:59:59      System.ServiceProcess.Tests.ServiceControllerTests.GetDevices [SKIP]
10:59:59         Condition(s) not met: "RunningWithElevatedPrivileges"
10:59:59      System.ServiceProcess.Tests.ServiceControllerTests.WaitForStatusTimeout [SKIP]
10:59:59         Condition(s) not met: "RunningWithElevatedPrivileges"
10:59:59   Finished:    System.ServiceProcess.ServiceController.Tests

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug/7/consoleFull

I'm going to guard my two admin-requiring tests the same way, which is a good citizen thing to do anyways.

**Comment by Priya91** [comment]
@bartonjs the outerloop windows runs are not run elevated, that is a bug.. Will look into this.
