### ISSUE TITLE
Fix 5.2 UWP meta-package so that it can be consumed in VS. 

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#7466]
There are various folks(example: https://github.com/dotnet/coreclr/issues/3520)  trying to consume the prerelease 5.2 meta-package for UWP but it currently doesn't work. We should fix this meta-package and ensure the closure of the prerelease packages work on UWP.

**Comment by ericstj** [comment]
There were various causes of regression here: moving packages to open, fat package conversion, UWP rolling back to NETStandard1.4.  I'll take a holistic look at the scenario to make sure we get it back up and running on latest packages.

**Comment by markmnl** [comment]
Is there anyway someone like I outside of MS help out on this one?

**Comment by ericstj** [comment]
I'm actively working on it.  It should be done by end of week (hopefully even end of day).  Right now the changes span internal and external so its hard for external folks to work on this.  One thing you can do to help is test with your app as soon as I get changes published.

**Comment by markmnl** [comment]
Seems to have got further today but no cigar, attmpted to use Microsoft.NETCore.UniversalWindowsPlatform Latest prerelease v5.2.0-rc3-24007-00, the end of the output looks like:

```
System.Runtime.InteropServices.PInvoke 4.0.0-rc3-24007-00 is not compatible with UAP,Version=v10.0.
Some packages are not compatible with UAP,Version=v10.0.
System.Runtime.InteropServices.PInvoke 4.0.0-rc3-24007-00 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).
Package restore failed for 'FalconUDP.WindowsUniversal'.
Package restore failed. Rolling back package changes for 'FalconUDP.WindowsUniversal'.
========== Finished ==========
```

**Comment by markmnl** [comment]
Out of interest which is the correct terminology: "UAP", "UWP" or "Universal Windows"?

**Comment by ericstj** [comment]
The fix for that went into yesterday morning.  Please try 24008 build.  

UWP= universal windows platform is the correct terminology.  Originally it was uap and folks decided to change the name but did so too late to update the value of the target platform value in folks projects.  Thus you still see uap in a few places.

**Comment by markmnl** [comment]
Building OK now

**Comment by markmnl** [comment]
I am afraid I have been unable to use the new (old) `Socket` API yet.. I am not sure if the problem is still related to this issue or if I should create a new one?

I have created some trivial tests to bind a `Socket`: [https://github.com/markmnl/SocketTests.UWP](https://github.com/markmnl/SocketTests.UWP). Problem is when running the tests in Debug or Release they never complete. After about 10 minutes of loading symbols the following appear in the Output Window but VS still shows the Tests as running:

```
The thread 0x3018 has exited with code 0 (0x0).
'SocketTests.UWP.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\rmclient.dll'
The thread 0xd30 has exited with code 0 (0x0).
The thread 0x32e0 has exited with code 0 (0x0).
Exception thrown at 0x73CCDAD8 in SocketTests.UWP.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x09DBC894.
Exception thrown at 0x73CCDAD8 in SocketTests.UWP.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
The thread 0x3118 has exited with code 0 (0x0).
Exception thrown at 0x73CCDAD8 in SocketTests.UWP.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown at 0x73CCDAD8 in SocketTests.UWP.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown: 'System.IO.FileNotFoundException' in Microsoft.VisualStudio.TestPlatform.TestExecutor.Core.dll
The thread 0x5f8 has exited with code 0 (0x0).
The thread 0x24b8 has exited with code 0 (0x0).
The thread 0x1bf0 has exited with code 0 (0x0).
The thread 0x1298 has exited with code 0 (0x0).
The thread 0x1a08 has exited with code 0 (0x0).
The thread 0xdac has exited with code 0 (0x0).
The thread 0x3094 has exited with code 0 (0x0).
The thread 0x2d74 has exited with code 0 (0x0).
The thread 0x18f4 has exited with code 0 (0x0).
'SocketTests.UWP.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\Windows.Globalization.dll'
```

**Comment by ericstj** [comment]
This issue has been verified fixed using VS Update 2 and the latest packages.  Please open a seperate issue if you are having trouble using sockets.
