### ISSUE TITLE
Outerloop Ubuntu and OSX getting packaging errors for VB project.

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#7472]
There are a bunch of errors on the packaging.targets for the VisualBasic project which doesn't get built in non-Windows builds. Here is a sample of a couple of errors:
```
/Users/dotnet-bot/j/workspace/dotnet_corefx/outerloop_osx_debug/Tools/Packaging.targets(881,5): error : Microsoft.VisualBasic should be supported on .NETStandardApp,Version=v1.5/win7-x86 but has no runtime assets. [/Users/dotnet-bot/j/workspace/dotnet_corefx/outerloop_osx_debug/src/Microsoft.VisualBasic/pkg/Microsoft.VisualBasic.pkgproj]
/Users/dotnet-bot/j/workspace/dotnet_corefx/outerloop_osx_debug/Tools/Packaging.targets(881,5): error : Microsoft.VisualBasic should be supported on .NETStandardApp,Version=v1.5/win7-x64 but has no runtime assets. [/Users/dotnet-bot/j/workspace/dotnet_corefx/outerloop_osx_debug/src/Microsoft.VisualBasic/pkg/Microsoft.VisualBasic.pkgproj]
```

[Here](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_osx_debug/78/consoleFull) is a full build log. We should fix this since the build in non-Windows is currently broken.

**Comment by joperezr** [comment]
@ericstj do you know why do we started seeing this now even though VB project has never been built for non-Windows platforms?

**Comment by joshfree** [comment]
@sokket is this related to your recent changes?

**Comment by ericstj** [comment]
Yeah, this was caused by https://github.com/dotnet/corefx/issues/7410.

**Comment by ericstj** [comment]
@joperezr this worked before due to a different workaround.  See https://github.com/sokket/corefx/commit/752599494fce80b5d0059a9090fdc010d8c7f45b#diff-05664100383e2fd6ff44bb13fdfab202L6

**Comment by sokket** [comment]
PR #7491 out to fix this

**Comment by sokket** [comment]
Fixed
