### ISSUE TITLE
A de-facto Option type.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/corefx#748]
Consider having an `Option(Of T)` that is common across the .net languages.
```
type Option
  | None
  | .Value : T
```
If it's traits were allowed to be inherited..
```
type Iter<T> extends Option|.Value
  .Next : ()-> Iter<T>
```
Would be the basis of an iterator / sequence.

**Comment by ellismg** [comment]
I think this is the same as #538?

**Comment by AdamSpeight2008** [comment]
Nope. This is about having a Option / MayBe that is common across .net languages. F#. C#, VB.net.
If you end up doing anything functional in style, having a Option type is useful, as the T can be a Struct or a Class. Unlike Nullable(Of T) which constricts T to a Struct and for a class type Null could also be a valid valid of that type.

**Comment by ellismg** [comment]
How is this different than 538 which also wants to add an option type?  It also is not constrained to just a struct.

**Comment by AdamSpeight2008** [comment]
I thought in #538 that they wanted to change Null to Option.

**Comment by ellismg** [comment]
From the issue:

> So in this issue I want to propose the addition of a Option type to the .NET Framework.

The discussion is focused more on adding the Option type than changing existing APIs which use null to consume/produce Option.
