### ISSUE TITLE
System.Diagnostics.TraceSource should not be RID specific

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#7480]
I don't know the reasoning behind why we chose to compile this thing twice but AFAIK there's a dependency on getting the PID? I'm guess we didn't want to use Process since we're hoping for a more xplat friendly process API. Whatever the reason, runtime light up would be a much better solution here since all of the IL is duplicated in the output of a portable application and the need to cross compile is a very small part of the code.

https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.TraceSource/src/System/Diagnostics/TraceEventCache.Unix.cs

https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.TraceSource/src/System/Diagnostics/TraceEventCache.Windows.cs

/cc @stephentoub @ericstj @weshaggard

**Comment by stephentoub** [comment]
> runtime light up would be a much better solution here 

Last I checked that doesn't play well with store verification or with .NET Native compilation.

**Comment by weshaggard** [comment]
I agree we should try to make this a single IL library. I would actually like to see if we could eliminate the PID as a dependency without too much of an issue. If we cannot we should consider taking a dependency on Process.

@davidfowl out of curiosity why are you using this library it exist primarily as a compat library.

cc @vancem @lt72

**Comment by stephentoub** [comment]
> I would actually like to see if we could eliminate the PID as a dependency without too much of an issue.

FYI, the PID dependency comes from public surface area:
https://github.com/dotnet/corefx/blob/ac67ffac987d0c27236c4a6cf1255c2bcbc7fe7d/src/System.Diagnostics.TraceSource/ref/System.Diagnostics.TraceSource.cs#L141
https://github.com/dotnet/corefx/blob/ac67ffac987d0c27236c4a6cf1255c2bcbc7fe7d/src/System.Diagnostics.TraceSource/ref/System.Diagnostics.TraceSource.cs#L232

**Comment by ericstj** [comment]
This is covering the same work already described here: https://github.com/dotnet/corefx/issues/7180

**Comment by davidfowl** [comment]
> @davidfowl out of curiosity why are you using this library it exist primarily as a compat library.

Seems like we pull it in in Kestrel. I'm going to remove it now 😄

**Comment by weshaggard** [comment]
Closing this as it is tracked by #7180.
