### ISSUE TITLE
Add libuv to the Microsoft.NETCore.App redist

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#7481]
Reasoning behind this is because it's a purely native component with 0 managed surface area. We now have 6 native libuv assets in the kestrel package:

![image](https://cloud.githubusercontent.com/assets/95136/14239035/7f65cfc8-f9ec-11e5-91c7-24d89626b552.png)

Today, every ASP.NET application depends on this and removing it would reduce the output size by 2MB. We'd make a libuv package and make kestrel depend on it so that it would be possible to use a newer version that what was shipped in the redist (like we do for every other component).

**Comment by joshfree** [comment]
@stephentoub

**Comment by joshfree** [comment]
Moved issue to https://github.com/dotnet/cli/issues/2277
