### ISSUE TITLE
Add Sockets performance tests

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#7499]
We currently have no formal performance testing of Sockets.  We have a couple of tests checked in, but they are disabled, haven't been adapted to the xunit.performance infrastructure, and test only a couple of particular end-to-end scenarios.  We should add new tests to cover individual operations, as well as a couple of larger scenarios.

**Comment by davidsh** [comment]
We have performance tests in TFS that have not been ported.  So, you should consider looking at those

**Comment by ericeil** [comment]
This is covered by other ongoing work.
