### ISSUE TITLE
How to use Reflection over .net core libraries?

### ISSUE THREAD

**Issue by rposener** [dotnet/corefx#7520]
It is not clear how to properly use reflection over .net core libraries.  When trying to use T4 template to reflect over a class library (we do this to generate Typescript definition files of our Dto's.  The  way we have always done this and expected it to work is the following a simple template:
````
<#@ template debug="false" language="C#" #>
<#@ assembly name="System.Core" #>
<#@ assembly name="System.Collections" #>
<#@ assembly name="System.Linq" #>
<#@ assembly name="$(SolutionDir)\srcCore\CM.Dtos\bin\Debug\dnx451\CM.Dtos.dll" #>
<#@ import namespace="System" #>
<#@ import namespace="System.Linq" #>
<#@ import namespace="System.Reflection" #>
<#@ import namespace="System.Collections.Generic" #>
<#@ output extension=".d.ts" #>
<#

	var assembly = Assembly.GetAssembly(typeof(CM.Dtos.PagedRequest));
	var allTypes = assembly.GetTypes().ToList();

`````

this does not seem to work with dnx/core libraries as we expected.  How would one crack open library the correct way to reflect over it's classes?

**Comment by mellinoe** [comment]
> this does not seem to work with dnx/core libraries as we expected

Could you give a bit more detail? Does it work in a different way than you expect, or does it not work at all?

Here's a few things that might help you in the right direction:

* Most reflection-related members on `System.Type` are now on `System.Reflection.TypeInfo`. Call `GetTypeInfo` to get a `TypeInfo` from a `Type`.
* `Assembly.GetAssembly` doesn't exist anymore. Use `typeof(...).GetTypeInfo().Assembly`
* You likely need to reference some additional NuGet packages, depending on what you are doing. `Assembly.GetTypes()` is in [System.Reflection.TypeExtensions](https://dotnet.myget.org/F/dotnet-core/api/v2/package/runtime.any.System.Reflection.TypeExtensions/4.1.0-rc3-23918), for example.

**Comment by rposener** [comment]
So, when running from VS, when you choose "Run Custom Tool" - what is really happening?  Is it using .net core app?  I would have believed it to be the old T4 execution.  If so, is there any way the old tool can reflect over the new core packages?  Is there a way to execute a .net core console app or something in the Task Runner as part of our build process instead so these suggestions will work?

**Comment by rposener** [comment]
Just a follow-on comment - I can see that despite the 
`<#@ assembly name="$(SolutionDir)\srcCore\CM.Dtos\bin\Debug\dnx451\CM.Dtos.dll" #>`
line, if I output Assembly.Location, it is pulling from, which seems to point at an older version of the file.

%userprofile%\AppData\Local\assembly\dl3\DO2HVQV3.BT8\L5ZE9129.P2B\217c4995\628efb06_318dd101\CM.Dtos.dll

Cleaing the project nor deleting that temp assembly and rebuilding does not fix this.  My project is targeting dnx451 and dnxcore50.  Do I need to target net451 as well, to be able to use reflection from a T4 template?

**Comment by AtsushiKan** [comment]
This seems to have morphed into a series of questions about VS rather than about the framework. This isn't the right place for that sort of question.
