### ISSUE TITLE
HttpResponseMessage.Dispose does not cancel an ongoing call to ReadAsync

### ISSUE THREAD

**Issue by halter73** [dotnet/corefx#7522]
The "netcore50" but not the "dnxcore50" version of System.Net.Http 4.0.1-beta-23516 has a bug where calling HttpResponseMessage.Dispose() does not cancel an ongoing call to responseStream.ReadAsync(). This breaks the SignalR client in Universal Windows Platform apps.

Here is an example of code that will hang indefinitely if HttpResponseMessage.Dispose() is called before the response body is completed.

```c#
using (var client = new HttpClient())
{
    var request = new HttpRequestMessage(HttpMethod.Get, "http://localhost:5000/");
    HttpResponseMessage response = null;
    var ignore = Task.Delay(5000).ContinueWith(_ =>
    {
        mLogger.WriteLine("Canceling request");
        response.Dispose();
    });

    mLogger.WriteLine("Making request");
    response = await client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, CancellationToken.None);
    mLogger.WriteLine("Got headers");
    var buffer = new byte[1024];
    int count = -1;
    var responseStream = await response.Content.ReadAsStreamAsync();
    while (count != 0)
    {
        mLogger.WriteLine("ReadAsync");
        count = await responseStream.ReadAsync(buffer, 0, 1024);
        mLogger.WriteLine("Finished ReadAsync");
    }
    mLogger.WriteLine("Request complete");
}
```

__Expected behavior (which happens with the dnxcore50 assembly):__ When HttpResponseMessage.Dispose() is called, the ongoing call to responseStream.ReadAsync throws a TaskedCanceledException.

__Actual behavior (which happens only with dotnetcore50 assembly):__ stream.ReadAsync never completes after HttpResponseMessage.Dispose() is called. To make matters even worse, when/if the response body actually does complete, responseStream.ReadAsync *still* never finishes.

__Note:__ If the CancellationToken that is passed to Send is canceled before client.SendAsync completes, SendAsync will throw a TaskedCanceledException with both the dnxcore50 and netcore50 versions of System.Net.Http. That is not what this bug is about.

**Comment by micbil** [comment]
This is an active problem we're seeing affect our Bingo Game.

**Comment by davidsh** [comment]
I tried repro'ing this with the System.Net.Http 4.0.0 package. That is the stable (not pre-release) and is automatically brought in when you build a new UWP app in Visual Studio.

project.json
```c#
{
  "dependencies": {
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.0.0"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```

btnClick handler:
```c#
        private async void btnTest_Click(object sender, RoutedEventArgs e)
        {
            using (var client = new HttpClient())
            {
                var uri = new Uri("http://httpbin.org/bytes/1000000");
                var request = new HttpRequestMessage(HttpMethod.Get, uri);
                HttpResponseMessage response = null;
                var ignore = Task.Delay(1000).ContinueWith(_ =>
                {
                    WriteLine("Canceling request");
                    response.Dispose();
                });

                WriteLine("Making request");
                response = await client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, CancellationToken.None);
                WriteLine("Got headers");
                var buffer = new byte[1024];
                int count = -1;
                var responseStream = await response.Content.ReadAsStreamAsync();
                while (count != 0)
                {
                    WriteLine("ReadAsync");
                    count = await responseStream.ReadAsync(buffer, 0, 1024);
                    WriteLine("Finished ReadAsync");
                }
                WriteLine("Request complete");
            }
        }

        private async void WriteLine(string message)
        {
            if (txtOut.Dispatcher.HasThreadAccess)
            {
                txtOut.Text += message + "\r\n";
            }
            else
            {
                await Dispatcher.RunAsync(CoreDispatcherPriority.Normal, () =>
                {
                    txtOut.Text += message + "\r\n";
                });
            }
        }
```

I'm also not sure why you expect the behavior to throw a `TaskCanceledException` from the stream you doing the ReadAsync on when you dispose the `HttpResponseMessage`. In my example, the `stream.ReadAsync` throws an `ObjectDisposedException`.

Can you provide a repro where the server-side of this is determinstic?  Feel free to use the httpbin.org server like I did. Your current repro example uses localhost and it isn't clear what that server does. So, I am unable to repro this right now.

**Comment by davidsh** [comment]
Also, when I upgraded the System.Net.Http package from 4.0.0 to the same as you tried, I still didn't repro the "hang":

```c#
  "dependencies": {
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.0.0",
    "System.Net.Http":  "4.0.1-beta-23516"
  },
```

**Comment by halter73** [comment]
@davidsh It's important that you have a long-lasting call to ReadAsync ongoing when you dispose the HttpResponseMessage.

Long-lasting ReadAsync calls are typical for the SignalR client. Normally there is 10 seconds between each keep-alive message the SignalR server sends to each client. Many connection issues can only be detected by tracking each call to ReadAsync and determining if any last much longer than 10 seconds. When such a timeout is triggered, we need to cancel the ongoing ReadAsync call and attempt to reestablish a new connection.

If you make a call to ReadAsync after you dispose HttpResponseMessage, you will get an ODE as expected.

The easiest way I found to repro was to take the [Kestrel sample app](https://github.com/aspnet/KestrelHttpServer/blob/5a8cba878d84614794ea16a624080db501e47eea/samples/SampleApp/Startup.cs#L37) and set `ContentLength` to 12 instead of 11 so the last call to ReadAsync will never complete normally

> I'm also not sure why you expect the behavior to throw a TaskCanceledException from the stream you doing the ReadAsync on when you dispose the HttpResponseMessage. In my example, the stream.ReadAsync throws an ObjectDisposedException.

Mainly because that's the behavior on desktop, and this was the only we we could find to reliably kill an ongoing ReadAsync call so we could then continue with our reconnect logic in SignalR.

**Comment by davidsh** [comment]
We have determined that this is a Windows OS level bug that we plan to fix in the next release of Windows 10.

In the meantime, using a `CancellationTokenSource` pattern will allow the `Stream.ReadAsync` to be cancelled correctly.

```c#
    CancellationTokenSource cts;

    cts = new CancellationTokenSource();

    // other code

    var client = new HttpClient();

    var request = new HttpRequestMessage(HttpMethod.Get, uri);
    var ignore = Task.Delay(2000).ContinueWith(_ =>
    {
        // _responseStream.Dispose();  // currently doesn’t work due to bug  
        cts.Cancel();
    });

    _response = await client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead);

    var buffer = new byte[1024];
    _responseStream = await _response.Content.ReadAsStreamAsync();

    int count = -1;
    count = await _responseStream.ReadAsync(buffer, 0, 1024, cts.Token);
```

**Comment by davidsh** [comment]
The Windows 10 OS bug has been fixed and the fix will roll out as part of the next release of Windows later this year.  Closing out this issue.

**Comment by micbil** [comment]
Thank you David for the update and for the assistance.



Michael


-------- Original message --------
