### ISSUE TITLE
Dynamic type resolution goes into infinite recursion

### ISSUE THREAD

**Issue by ScramblerUSA** [dotnet/corefx#7527]
Under certain circumstances dynamic type resolution goes into infinite recursion (causing program to terminate with StackOverflowException) alternating between these methods:

```
Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.Semantics.TypeManager.SubstTypeCore(Microsoft.CSharp.RuntimeBinder.Semantics.CType type, Microsoft.CSharp.RuntimeBinder.Semantics.SubstContext pctx)
Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.Semantics.TypeManager.SubstTypeArray(Microsoft.CSharp.RuntimeBinder.Semantics.TypeArray taSrc, Microsoft.CSharp.RuntimeBinder.Semantics.SubstContext pctx)
```

This happens only when an argument of type "dynamic" is passed, of course. Static typing works fine.

Repro:
```c#
using System;
class Program
{
    static void Main(string[] args)
    {
        // vvv--- changing "dynamic" to "var" or "string" here fixes the issue
        dynamic parsedDocument = "";
        var mystery = new FailingClass<string>();
        Console.WriteLine("Entering...");
        mystery.FailingMethod(parsedDocument);
        Console.WriteLine("... and we are back!");
        Console.ReadLine();
    }
}
public abstract class CommonBase<T> {}

// Technically, this class does nothing and deriving from it should be identical to deriving from CommonBase
public abstract class FailingClassBase<T> : CommonBase<T> {}

// However, deriving from CommonBase instead of FailingClassBase here also fixes the issue
// ----------------------------vvvvvvvvvvvvvvvv
public class FailingClass<T> : FailingClassBase<FailingClass<T>>
{
    public void FailingMethod(T src) {}
}
```

[EDIT] Fixed callstack formatting by @karelz
[EDIT] Inlined source code from original attachment [repro.txt](https://github.com/dotnet/corefx/files/205290/repro.txt), with minor formatting changes by @karelz

**Comment by ContentsMayVary** [comment]
Here's another repro:

class First<T> where T : First<T> { }
class Second<T> : First<T> where T : First<T> { }
class Third<T> : Second<Third<T>> { }

class Program
{
    static void Main()
    {
        dynamic x = new Third<int>();
        Print(x);
    }

    static void Print(object obj) { }
}

**Comment by karelz** [comment]
We need someone to get it under debugger and find out what is wrong in .NET Core code.

**Comment by JonHanna** [comment]
The loop is straight-forward enough. In the last of the examples produced, for example, it trys to substitute the types in `Third<T>` to get `Third<int>` then work out the base when is a type of `Second<T>` typed with `Third<T>` which has a base of `Second<T>` typed with `Third<T>` which has a base…

Breaking the loop does not seem to be easy though.

**Comment by karelz** [comment]
There is duplicate report in #23706 with variant of the same bug: `Second<T>`=`BuilderBaseEx<T>`, but the constraint is slightly (and likely insignificantly) different:
* `Second<T> : First<T> where T : Second<T>` in #23706 
* `Second<T> : First<T> where T : First<T>` in this bug

**Comment by JonHanna** [comment]
The great thing about not having time to contribute to corefx for a month, is getting a fresher look at some things. I'd tried a variant of the fix in #25196 before but must have slipped up, since it went quite smoothly this time.

**Comment by JonHanna** [comment]
It might be worth making this netfx-port-consider, since there are several stackoverflow questions about it with netfx, suggesting it affects a fair number of people.

**Comment by karelz** [comment]
@JonHanna did you see more than the 2 StackOverflow links above? If there are any highly upvoted, that would be worth linking from here. It will be useful at the point we do the port to assess need vs. risk. Thanks!

**Comment by JonHanna** [comment]
There was also https://stackoverflow.com/q/19612325/400547 that gave me the idea of testing it in cases where it should throw RBE.

https://stackoverflow.com/q/16064085/400547 seemed to be a variant too, but it turns out to be something else, so that's my homework for this week 😉

**Comment by JonHanna** [comment]
(Actually no, that last one was just the querent doing something wrong, so that's off the list).

**Comment by karelz** [comment]
Which last one? Can you please edit your reply to keep just the relevant links? Thanks!

**Comment by JonHanna** [comment]
NP
