### ISSUE TITLE
Add not supported assemblies for more packages

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#7528]
Some packages are only supported starting with a particular RID (EG: System.Runtime.WinRT packages)  For these we should add a dummy impl so that folks can compile, JIT, then light up on win8.

**Comment by ericstj** [comment]
We also need to make sure that any package shipping in 2.0 with a net standard ref has a net standard implementation, even if that is a platform not supported assembly.

**Comment by tarekgh** [comment]
@ericstj just want to make sure you are tracking this issue to fix it for v2.0.

**Comment by ericstj** [comment]
Yeah I'm reviewing this.  I actually think I'll roll this into another issue.
