### ISSUE TITLE
`System.Linq.Parallel.Cast<TCastTo>()` doesn't.

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#753]
The following throws `InvalidCastException`:

    foreach(double d in ParallelEnumerable.Range(0, 10).Cast<double>()) {}

This is because `ParallelQuery.Cast<TCastTo>()` looks like this (ParallelQuery.cs, starting at line 98):

    internal sealed override ParallelQuery<TCastTo> Cast<TCastTo>()
    {
        return ParallelEnumerable.Select<TSource, TCastTo>(this, elem => (TCastTo)(object)elem);
    }

...which means that what happens for primitives is that they're getting autoboxed, so of course it throws the error when it tries to convert it later.  
This _is_ currently shipping behavior (effectively, cannot use `Cast<TCastTo>()` to change primitive types), which is rather counterintuitive.

Attempting to remove the cast to `object` results in compile errors, because there's no way the compiler can determine if there's any valid cast.  I believe doing a cast to `dynamic` first instead should solve the problem (testing via other means indicates it should), but the required assembly/something doesn't appear to be part of corefx as of yet, given the following compile error appears:

    error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.Binder.Convert'

(I was trying to fix this myself, but I got stuck with that last compiler error)

**Comment by mikedn** [comment]
This isn't specific to ParallelEnumerable, Enumerable's Cast behaves identically.

In general, you can't to numeric conversions in generic methods since the conversion code depends on the involved types. You can use `dynamic` but it's pretty inefficient to do so.

You can use Select instead of Cast in such cases:

```C#
foreach (double d in ParallelEnumerable.Range(0, 10).Select<int, double>(x => x)) { }
```

And of course, in your particular example you could eliminate the cast completely since `foreach` will cast anyway.

**Comment by mburbea** [comment]
This has been the case since .net 3.5 sp1.

**Comment by Clockwork-Muse** [comment]
@mikedn - Well, yeah, I'm aware you can use `Select(...)` instead, and that explicitly listing the cast when enumerating isn't necessary.  I just thought it was liable to throw people off, since the exception thrown is `InvalidCast`, when the destination type was obviously auto-assignable from the source...

**Comment by stephentoub** [comment]
@Clockwork-Muse, while it may be counter-intuitive, as @mikedn stated, this is the behavior of both Enumerable.Cast and ParallelEnumerable.Cast.  What outcome are you hoping for here?  Is it that you're just interested in seeing this made more clear in the documentation for Cast?

**Comment by Clockwork-Muse** [comment]
@stephentoub - maybe, or possibly changed so it works "as expected" (I'm aware that this is possibly only as -I- expect it to...)

After all, the documentation states you can change between types, and you can generally cast single primitives to each other.. "why can't I cast between types?" seems like a natural question consumers might raise.

**Comment by stephentoub** [comment]
@Clockwork-Muse, as @mikedn alluded to, there's no good/efficient way to change the implementation to provide the behavior you're hoping for.  This is the behavior that's existed in LINQ for a long time; I think it's going to remain as-is.  But thank you for the suggestion.
