### ISSUE TITLE
Building is slow on Linux

### ISSUE THREAD

**Issue by manu-silicon** [dotnet/corefx#7538]
On Linux, it takes quite a bit of time to build CoreFX from scratch even if skipping tests (about 52 minutes). However, I was surprised to see that if you just do a change in one of the C# file, the recompilation time (it should really be just recompiling an assembly) is quite long (about 31 minutes). This is on a relatively fast machine with a SSD drive.

Is this expected? If not, what am I doing wrong? If so, should we have a fast mode that only compiles the assemblies for which their C# code has changed?

Note that on Windows, the behavior is the same but it doesn't take the same amount of time (5 minutes for a rebuild with no changes).

**Comment by mellinoe** [comment]
This is probably related to https://github.com/dotnet/corefx/issues/6220 based on what you described. However, even apart from that issue, the x-plat build does seem quite a bit slower in general. We should try to determine where the slowest parts are and see what can be done about it. A diagnostic log could potentially reveal if anything in particular stands out as taking an unreasonable amount of time compared with the Windows build.

We've also talked about pre-compiling the tool runtime (crossgen), but I'm not sure what improvement (if any) we will see to the full product build with that.

@weshaggard , @joperezr

**Comment by joperezr** [comment]
> but I'm not sure what improvement (if any) we will see to the full product build with that.

I have tried locally and noticed that there is definitely an improvement in perf but it is not super high. Something around 10-20%. I think the major issue in here is what @mellinoe points out where there seems to be a bug where rebuild will always clean and build no matter if there were no changes in those assemblies.

**Comment by joperezr** [comment]
build time in non-Windows has improved now since @mellinoe fixed which tests where being excecuted plus the change that added /m option to msbuild. If there is nothing else to this issue, I would like to close it as a dupe to #6220 which is about the msbuild /t:rebuild always rebuilding. Would that be ok with you guys? @mellinoe @manu-silicon

**Comment by manu-silicon** [comment]
@joperezr  Sorry I missed your comment last week. I'll try again later this week.

**Comment by manu-silicon** [comment]
I checked this and here is the results. To compile from scratch it took 19 minutes (almost 3 times faster), an incremental compilation without changes took 12min30s (including 2 minutes to restore all packages).

So there have been some improvements :+1: but looks like there are still a few issues during the build. First it still compile the Tests assemblies, is this expected? Second when it tries to compile them I get this on the console:

```
Common.Tests -> /home/local/Microsoft/corefx/bin/Unix.AnyCPU.Debug/Common.Tests/Common.Tests.dll
chmod: cannot access ‘/home/local/Microsoft/corefx/bin/tests/Unix.AnyCPU.Debug/Common.Tests/dnxcore50/corerun’: No such file or directory
```

Should I open an issue for those?

**Comment by mellinoe** [comment]
> First it still compile the Tests assemblies, is this expected?

It depends on how you ran the build, but yeah, it is expected. You can do some filtering so that some subsets are built and everything else is skipped, but by default (i.e. `build.sh` or `msbuild build.proj`), everything will get built including test assemblies. Test assemblies should get skipped if they aren't applicable to your platform, but that's a small minority of them.

> Should I open an issue for those?

Please do, it looks like something we missed when switching to a new process for deploying tests.

**Comment by joperezr** [comment]
Thanks for checking Manu, so then does it make sense to close this issue and open one for the chmod error?

**Comment by manu-silicon** [comment]
I've posted issues #8385 and #8386

**Comment by manu-silicon** [comment]
@joperezr I'd like to keep this open as it is still slower than Windows. I'm going to redo the benchmarks using the a machine that has dual boot so that timing are accurate.

**Comment by karelz** [comment]
@manu-silicon are you still working on the issue?

**Comment by manu-silicon** [comment]
@karelz Not at the moment, it has been a while since I build myself CoreFX and I'm unable at this point to perform a fair benchmark between the Linux and Windows build. I'm closing the issue for now.
