### ISSUE TITLE
ConvertStringSidToSid() result compared against TRUE

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/corefx#7545]
`System.Security.Principal.CreateSidFromString()` has this code:

     if (TRUE != Interop.mincore.ConvertStringSidToSid(stringSid, out ByteArray))

It looks like this causes `ConvertStringSidToSid()` WinAPI function call and `ConvertStringSidToSid()` is documented to return either "zero" or "non-zero". So this check should compare the result against `FALSE`, not `TRUE`.

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/corefx/pull/7771
