### ISSUE TITLE
Remove Pinvoke exceptions in System.Security.Cryptography.Csp

### ISSUE THREAD

**Issue by pallavit** [dotnet/corefx#7550]
PinvokeAnalyzerExceptionList.analyzerdata in System.Security.Cryptography.Csp implementation contains non api-set pinvokes. Corefx repro is following apiset model and so these Pinvokes should be changed to use the APISet counter parts. If you remove exception list. Pinvoke analyzer will suggest in its error message the correct Apiset to use for this.

Advapi32.dll!CryptAcquireContextW
Advapi32.dll!CryptGetProvParam
Advapi32.dll!CryptGetUserKey
Advapi32.dll!CryptGetKeyParam
Advapi32.dll!CryptGenKey
Advapi32.dll!CryptReleaseContext
Advapi32.dll!CryptDecrypt
Advapi32.dll!CryptEncrypt
Advapi32.dll!CryptExportKey
Advapi32.dll!CryptImportKey
Advapi32.dll!CryptCreateHash
Advapi32.dll!CryptGetHashParam
Advapi32.dll!CryptSetHashParam
Advapi32.dll!CryptSignHashW
Advapi32.dll!CryptVerifySignatureW
Advapi32.dll!CryptDestroyKey
Advapi32.dll!CryptDestroyHash

**Comment by pallavit** [comment]
@bartonjs I believe you own this library, please feel free to reroute in case I am mistaken.

**Comment by bartonjs** [comment]
@pallavit Is this for UWP? Or a different API-set restricted surface?  The CSP package is all the legacy crypto stuff not allowed for UWP, so shouldn't be scanned by any UWP-only tools.

**Comment by pallavit** [comment]
> @pallavit Is this for UWP

The package is supported on .NetStandard1.3 (so technically should work both on UWP and OneCore. However, for now this is getting flagged for OneCore only.

**Comment by mellinoe** [comment]
Do we need to add an explicit "Not Supported" assembly for UWP?
