### ISSUE TITLE
System.Runtime.InteropServices.PInvoke only supports .NETStandard1.5 / Breaks UAP

### ISSUE THREAD

**Issue by drieseng** [dotnet/corefx#7554]
As part of commit [398d38059d05a768ca6b58f6e6c5e4417954830f](https://github.com/dotnet/corefx/commit/398d38059d05a768ca6b58f6e6c5e4417954830f), the **System.Runtime.InteropServices.PInvoke** package was modified to remove netcore50 as supported target framework, and "upgrade" from .NETStandard 1.3 to 1.5.

The **System.Runtime.InteropServices.PInvoke** package is a dependency of **Microsoft.NETCore** - which in turn is a dependency of **Microsoft.NETCore.UniversalWindowsPlatform**.

Due to the commit mentioned above, the following error is reported when restoring or building a UAP 10.0 app that references any of the nuget packages mentioned:

```text
One or more packages are incompatible with UAP,Version=v10.0 (win10-x64-aot)

Package System.Runtime.InteropServices.PInvoke 4.0.0-rc3-24006-00 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x86. Package System.Runtime.InteropServices.PInvoke 4.0.0-rc3-24006-00 supports:
      - monoandroid10 (MonoAndroid,Version=v1.0)
      - monotouch10 (MonoTouch,Version=v1.0)
      - net462 (.NETFramework,Version=v4.6.2)
      - netstandard1.5 (.NETStandard,Version=v1.5)
      - xamarinios10 (Xamarin.iOS,Version=v1.0)
      - xamarinmac20 (Xamarin.Mac,Version=v2.0)
```

This makes CoreFX unusable for building UWP/UAP apps.

**Comment by drieseng** [comment]
Just found this meta-issue for UWP/UAP: #7466.
@ericstj Feel free to close the current issue, if it does not hold new information for you.

**Comment by ericstj** [comment]
Yep, I am fixing this now.
