### ISSUE TITLE
Enable pinvoke analyzer in System.Reflection.Metadata.

### ISSUE THREAD

**Issue by pallavit** [dotnet/corefx#7556]
PR #7553 disabled these warnings to unblock the build and enable the analyzers.

**Comment by pallavit** [comment]
/cc: @nguerrera please reroute as you see fit :).

**Comment by nguerrera** [comment]
I'm not convinced there's a real product issue being detected by these warnings in this specific case. Here is an experiment that I've just done with using ReadFile via kernel32.dll in a UWP and passing WACK.

* File New Project -> C# -> Universal Windows -> Blank App
* Drop a text box onto MainPage.Xaml
* Update MainPage.xaml.cs to the following:

``` C#
using System;
using System.IO;
using System.Runtime.InteropServices;
using Windows.UI.Xaml.Controls;

namespace App1 {
    public sealed partial class MainPage : Page {
        public MainPage(){
            this.InitializeComponent();

            using (var stream = new FileStream(
                Directory.GetFiles(AppContext.BaseDirectory)[0], 
                FileMode.Open, 
                FileAccess.Read,
                FileShare.ReadWrite,
                4096,
                FileOptions.None))
            {
                int _;
                this.textBox.Text += ReadFile(stream.SafeFileHandle, new byte[10], 10, out _, IntPtr.Zero);
                this.textBox.Text += Environment.NewLine;
            }

            try
            {
                IntPtr _;
                CryptAcquireContext(out _, IntPtr.Zero, IntPtr.Zero, 0, 0);
            }
            catch (Exception ex)
            {
                this.textBox.Text += Environment.NewLine;
                this.textBox.Text += ex;
            }
        }

        
        [DllImport(@"kernel32.dll", SetLastError = true)]
        [return: MarshalAs(UnmanagedType.Bool)]
        internal static extern bool ReadFile(
           SafeHandle fileHandle,
           byte[] buffer,
           int byteCount,
           out int bytesRead,
           IntPtr overlapped
        );

        [DllImport("advapi32.dll", SetLastError = true, CharSet = CharSet.Unicode, EntryPoint = "CryptAcquireContextW")]
        [return: MarshalAs(UnmanagedType.Bool)]
        public static extern unsafe bool CryptAcquireContext(
            out IntPtr psafeProvHandle,
            IntPtr pszContainer,
            IntPtr pszProvider,
            int dwProvType,
            int dwFlags);
    }
}

```

* Set configuration to release
* F5
* Note toolchain complaining about CryptAcquireContext, but not ReadFile:
```
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\IlcInternals.targets(887,5): warning :           Unresolved P/Invoke method 'CryptAcquireContext!advapi32.dll' in assembly 'App1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
```

* Observe the following output in the text box -> ReadFile succeeds, CryptAcquireContext fails.
```
True

System.TypeLoadException: Unresolved P/Invoke method 'CryptAcquireContext!advapi32.dll' in assembly 'App1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
   at SharedLibrary!<BaseAddress>+0x133a56
   at SharedLibrary!<BaseAddress>+0x133a0f
   at App1.MainPage..ctor()
```

* Project -> Store -> Create App Package
* 'No' do not upload to store
* Check x86, release -> Create
* Launch Windows App Certification Kit
* Select only 'Supported API test' -> *PASSED*

* Change both P/Invokes to ExactSpelling=true (to bypass toolchain warning as indicated by exception)
* F5 again -> this time, both calls work
* Run through app creation + WACK again -> FAILED but the only error is about CryptAcquireContextW:
```
API CryptAcquireContextW in advapi32.dll is not supported for this application type. App1.dll calls this API.
```

This is all consistent with the investigation that was done at the time the light-up P/Invoke in question was authored and I discovered by reviewing internal lists with @ericstj that it was permitted for store apps (Win8 at the time) to consume ReadFile via kernel32.dll. This appears to continue to be allowed for UWP apps.

This suggests to me that S.R.Metadata will pass WACK just fine as-is. We should therefore either make the analysis that flagged it smarter or make the suppression permanent with an appropriate comment.

cc @weshaggard @tmat @jkotas

**Comment by nguerrera** [comment]
Assigning back to you, @pallavit based on my conclusion above.

**Comment by pallavit** [comment]
> This suggests to me that S.R.Metadata will pass WACK just fine as-is

Pinvoke analyzer is not flagging it because of WACK, it is doing so because we have explicitly set the policy in corefx that AnyOS binaries should be purely managed. (I thought I mentioned this in the earlier discussion as well). If you want the library to continue to have OS calls and guard against them using EntryPointNotFoundException, there is no action here. I created the bug to make sure we looked at it and explicitly chose it.

**Comment by nguerrera** [comment]
> Pinvoke analyzer is not flagging it because of WACK, it is doing so because we have explicitly set the policy in corefx that AnyOS binaries should be purely managed.

Great. I misread. Sorry. We can close this. The library is working fine on UNIX and guarding against EntryPointNotFoundException. 

FWIW, my thinking that this might have been related to WACK was due to @weshaggard explicitly commenting on the PR that it wouldn't pass WACK on UWP as-is: https://github.com/dotnet/corefx/pull/7532/files/df35c1146cde41cbb605a344fbf085fa8eba5d61#r58738024

**Comment by pallavit** [comment]
I believe @weshaggard said that since guarding against incorrect Pinvoke calls using EntryPointNotFoundException does not always work, due to WACK (this was one of the motivation for the purely managed policy for AnyOS :))

The use of api-ms-win-core-file-l1-2-0!ReadFile however is still incorrect. It is not the lowest api-set and would not have the necessary forwarder deployed on win7, and so the library won't work. I can address it as part of PR #7553 if you are ok with it.

**Comment by nguerrera** [comment]
> The use of api-ms-win-core-file-l1-2-0!ReadFile however is still incorrect. It is not the lowest api-set and would not have the necessary forwarder deployed on win7, and so the library won't work. I can address it as part of PR #7553 if you are ok with it.

I'm OK with that as general goodness/clean-up, but note that the fallback to kernel32.dll would kick in on Win7 as the code was before any of these changes.  I maintain that there is no bug in the library only a situation too subtle for the analysis to understand.

**Comment by nguerrera** [comment]
> I believe @weshaggard said that since guarding against incorrect Pinvoke calls using EntryPointNotFoundException does not always work, due to WACK 

That is for the case of unapproved API, yes? You can't call them and catch because WACK will fail, but you can do what we're doing, call approved API and catch on non-Windows. Right?

**Comment by weshaggard** [comment]
Yes. Sorry if I caused some confusion here. I thought this was a banned API.

**Comment by pallavit** [comment]
> I'm OK with that as general goodness/clean-up, but note that the fallback to kernel32.dll would kick in on Win7 as the code was before any of these changes. I maintain that there is no bug in the library, only a situation too subtle for the analysis to understand.

In that case I will let the Apiset be as-is. It might be something to consider in case you remove the fallback in future.
