### ISSUE TITLE
NETCore SDK doesn't include live built packages

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#7557]
We have a single MSI that contains our NuGet packages to enable offline project creation for UWP and NETCore.  In the process of getting ready to ship UWP for update 2, folks removed all the NETCore-only packages from this MSI, because at the time those packages were huge because cross-plat native bits included full symbols.  We need to re-enable the NETCore-only packages.

This is a TFS-only change.

/cc @joshfree @weshaggard @Petermarcu

**Comment by weshaggard** [comment]
The other reason we disabled it was because we didn't want to ship this SDK with a random prerelease build of .NET Core packages when we shipped UWP update.

**Comment by ericstj** [comment]
ASP.NET msi includes our packages for RC2.  I've made a fix in the Dev branch but we need to coordinate the correct layout between us and ASP.NET and ensure shared components are getting the proper GUIDs. /cc @joeloff

**Comment by joeloff** [comment]
The ones where the casing is exactly the same (I could only find a few packages that currently match between both installers) have the correct GUIDs, keypaths, etc.

**Comment by ericstj** [comment]
I double checked components in our MSI old and new and even those that differ in case still get the same component GUID, so it looks like we are safe.

**Comment by joshfree** [comment]
@ericstj how's this tracking?

**Comment by ericstj** [comment]
I believe @jhendrixMSFT is working on getting the existing package building in the core-setup repo.

/cc @MichaelSimons 
We've actually changed the plan a bit since it's likely for NETCore SDK (UWP) to be out of sync with the latest CoreFx/CLI packages.

At RTM time we will make the NET Core SDK reference the 5.1.0 stable package and its closure.  This MSI will be responsible for satisfying the UWP templates and hybrid/designer scenarios.  As such it will carry whatever packages the templates use and the expanded layout of those to enable hybrid/designer.

The live package cache will be a separate installer.

@jhendrixMSFT @MichaelSimons does that sound like a good summary of the plans?  Do either of you want this issue to track the work you're doing?

**Comment by ericstj** [comment]
Closing this and opening an issue in core-setup: https://github.com/dotnet/core-setup/issues/189
