### ISSUE TITLE
BuildPackages target fails because GetPackageVersion needs a version number

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#758]
BuildPackages target is broken currently because GetPackageVersion requires more than we are currently setting in corefx repo right now. Luckily (:)) we had another bug that prevented this target from running on clean builds so not many people have hit it yet including our CI system. I'm fixing the other bug however I'm going to disable BuildPackages for now until we get this fixed.

Task "GetPackageVersion" (TaskId:2)
  Task Parameter:NuSpecFile=D:\git\corefx\src\nuget\Microsoft.Bcl.Immutable.nuspec (TaskId:2)
D:\git\corefx\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-4\lib\packages.targets(62,5): error MSB4044: The "GetPackageVersion" task was not given a value for the required parameter "DailyBuildNumber".

**Comment by jhendrixMSFT** [comment]
This has been resolved in https://github.com/dotnet/corefx/pull/765.

**Comment by stephentoub** [comment]
@jhendrixMSFT, @weshaggard, the Windows 10 outer loop debug run is still deterministically failing with a GetPackageVersion error, e.g.
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win10_debug/111/console
```
d:\j\workspace\outerloop_win---0cba2915\Tools\Packaging.targets(531,5): error MSB4018: The "GetPackageVersion" task failed unexpectedly. [d:\j\workspace\outerloop_win---0cba2915\src\Microsoft.Win32.Primitives\pkg\win\Microsoft.Win32.Primitives.pkgproj]
06:49:26 d:\j\workspace\outerloop_win---0cba2915\Tools\Packaging.targets(531,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [d:\j\workspace\outerloop_win---0cba2915\src\Microsoft.Win32.Primitives\pkg\win\Microsoft.Win32.Primitives.pkgproj]
06:49:26 d:\j\workspace\outerloop_win---0cba2915\Tools\Packaging.targets(531,5): error MSB4018:    at Microsoft.DotNet.Build.Tasks.Packaging.GetPackageVersion.Execute() [d:\j\workspace\outerloop_win---0cba2915\src\Microsoft.Win32.Primitives\pkg\win\Microsoft.Win32.Primitives.pkgproj]
06:49:26 d:\j\workspace\outerloop_win---0cba2915\Tools\Packaging.targets(531,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [d:\j\workspace\outerloop_win---0cba2915\src\Microsoft.Win32.Primitives\pkg\win\Microsoft.Win32.Primitives.pkgproj]
06:49:26 d:\j\workspace\outerloop_win---0cba2915\Tools\Packaging.targets(531,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [d:\j\workspace\outerloop_win---0cba2915\src\Microsoft.Win32.Primitives\pkg\win\Microsoft.Win32.Primitives.pkgproj]
```
Is this the same or a different issue?
