### ISSUE TITLE
Microsoft.NETCore.UWP rc2 crashes at runtime on UWP

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/corefx#7582]
## Steps to reproduce
File > New UWP blank project.
```
Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Pre
```
(using aspnetcidev as the source of truth, this gets Ms.NetCore.UWP version `5.2.0-rc2-23931`

## Expected behavior
Debug > Start (with or without) debugging
Launches empty app

## Actual
Application crashes on launch.
> Could not load type 'System.Resources.WindowsRuntimeResourceManager`
![image](https://cloud.githubusercontent.com/assets/2696087/14365170/24fbfa08-fcc1-11e5-9473-b3ed180e940c.png)

## Environment
VS2015 U2
VS Tools for UWP 14.0.25123.00
[project.lock.json](https://github.com/dotnet/corefx/files/209113/project.lock.json.txt)

**Comment by natemcmaster** [comment]
cc @ericstj

**Comment by ericstj** [comment]
This is a known issue and fixed in the RC3 branch.  /cc @weshaggard

**Comment by natemcmaster** [comment]
Which package is causing the issue? Is there a way to downgrade select packages to workaround this?

**Comment by andriysavin** [comment]
Any information when that RC3 is going to be available as a package?

**Comment by ericstj** [comment]
RC3 packages are already available here: https://dotnet.myget.org/F/dotnet-core/api/v3/index.json.

@natemcmaster there were issues across a large number of packages that we needed to fixup for UWP.  We're not recommending that folks take the new UWP meta-package from RC2.

**Comment by andriysavin** [comment]
@ericstj Thanks! I didn't know that URL, was taking all from "aspnet unstable", I guess...
