### ISSUE TITLE
Perf test failures in corefx / src / System.Xml.XmlSerializer / tests / System.Xml.XmlSerializer.Tests.csproj 

### ISSUE THREAD

**Issue by dsgouda** [dotnet/corefx#7584]
@khdang there seem to be some failures in tests related to  corefx / src / System.Xml.XmlSerializer / tests / System.Xml.XmlSerializer.Tests.csproj 
(Can be repro-ed by >msbuild src\System.Xml.XmlSerializer\tests\System.Xml.XmlSerializer.Tests.csproj /t:BuildAndTest /p:Performance=true /p:Configuration=Release) 
Please take a look and fix these

**Comment by khdang** [comment]
I think I know the reason of these failures. We ran the same perf scenarios for all 3 serializers and one of the scenario is not supported in XmlSerialzier. Let me disable this scenario.
