### ISSUE TITLE
TaiwanCalendarDaysAndMonths test failing in CI with FileLoadException

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7592]
e.g. 
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win7_debug/153/consoleFull
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win10_debug/160/consoleFull
```
04:01:25       System.Globalization.Tests.TaiwanCalendarDaysAndMonths.DayNames_MonthNames [FAIL]
04:01:25         System.IO.FileLoadException : Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)
04:01:25         Stack Trace:
04:01:25              at System.Globalization.Tests.TaiwanCalendarDaysAndMonths.GetExpectedMonthNames()
04:01:25           d:\j\workspace\outerloop_win---0cba2915\src\System.Globalization.Calendars\tests\TaiwanCalendar\TaiwanCalendarDaysAndMonths.cs(30,0): at System.Globalization.Tests.TaiwanCalendarDaysAndMonths.DayNames_MonthNames()
```
cc: @tarekgh, @Priya91

**Comment by tarekgh** [comment]
CC @weshaggard @joperezr 

@stephentoub how we can repro this issue?

**Comment by stephentoub** [comment]
> @stephentoub how we can repro this issue?

It's failing consistently in the outerloop runs.  I haven't tried reproing locally.

**Comment by stephentoub** [comment]
FYI, @tarekgh, I kicked off another Win10 outerloop run, and it failed in that one, too:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win10_debug/162/

**Comment by tarekgh** [comment]
yes looks failing in same tests but the logs not having much information. 

```
-0cba2915\src\System.Globalization.Calendars\tests\System.Globalization.Calendars.Tests.csproj]
09:11:09 d:\j\workspace\outerloop_win---0cba2915\Tools\tests.targets(154,5): error : One or more tests failed while running tests from 'System.Globalization.Tests' please check log for details! [d:\j\workspace\outerloop_win---0cba2915\src\System.Globalization\tests\System.Globalization.Tests.csproj]
09:11:09 d:\j\workspace\outerloop_win---0cba2915\Tools\tests.targets(154,5): error : One or more tests failed while running tests from 'System.Globalization.Calendars.Tests' please check log for details! [d:\j\workspace\outerloop_win---0cba2915\src\System.Globalization.Calendars\tests\System.Globalization.Calendars.Tests.csproj]
```

looks the issue related to assembly signing when running against the desktop. I'll try to repro it so we can know how to fix it.

**Comment by tarekgh** [comment]
Now I am able to repro it locally.

**Comment by tarekgh** [comment]
I am seeing at least one of the problems which is using ```/p:TestWithLocalLibraries=true ``` on the run. this will cause getting the test assembly link against the local assemblies. when the test run against to the desktop (as net46) it will fail because we cannot load such assemblies because we already filter the assemblies list in the desktop. 

@weshaggard mentioned to me there is a direction to have runs with filters, so we can run the desktop separately. and the non-desktop tests in other runs

**Comment by stephentoub** [comment]
FYI, 52 tests are failing in the Windows 8 outerloop run with this error, e.g.
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_windows_nt_debug/155/#showFailuresLink

**Comment by tarekgh** [comment]
I think this is related to the same problem 
```
System.TypeInitializationException : The type initializer for 'System.Globalization.Tests.CompareInfoCompareTests' threw an exception.\r\n---- System.TypeInitializationException : The type initializer for 'System.PlatformDetection' threw an exception.\r\n-------- System.IO.FileLoadException : Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name signature could not be verified. The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045
```

I believe we have 2 problems need more thoughts, the first is using ```/p:TestWithLocalLibraries=true``` with the desktop test runs. looks we need to disable this property when compiling and running  against desktop. the second problem could be signing issue as ```System.Runtime.InteropServices.RuntimeInformation``` looks not signed

**Comment by tarekgh** [comment]
@AlexGhiondea

**Comment by tarekgh** [comment]
https://github.com/dotnet/corefx/pull/7659

**Comment by tarekgh** [comment]
@stephentoub could you please try re-run it again and let's know if you see any other problem? Alex's fix already got a successful outerloop run.
