### ISSUE TITLE
BitConverter: Write bytes to exisiting array

### ISSUE THREAD

**Issue by Toxantron** [dotnet/corefx#7594]
I moved this here from dotnet/coreclr#4142 because I was told this is the right place.

Hello,

are there any ambitions to provide an API to BitConverter that takes an exisiting `byte[]` and position to include the bytes of a primitive? 

Right now I have an additional converter based on BitConverter that has methods like this:

``` c#
    /// <summary>
    /// Includes an int into an array of bytes
    /// </summary>
    public unsafe static void InsertBytes(int value, byte[] bytes, int index)
    {
        // Error handling and parameter validation
        if (bytes == null)
            throw new ArgumentNullException(nameof(bytes));
        if (index + 4 > bytes.Length)
            throw new ArgumentOutOfRangeException(nameof(index));
        fixed (byte* b = bytes)
            *((int*)(b + index)) = value;
    }

    /// <summary>
    /// Includes a long into an array of bytes
    /// </summary>
    [System.Security.SecuritySafeCritical]  // auto-generated
    public unsafe static void InsertBytes(long value, byte[] bytes, int index)
    {
        // Error handling and parameter validation
        if (bytes == null)
            throw new ArgumentNullException("bytes");
        if (index + 8 > bytes.Length)
            throw new ArgumentOutOfRangeException("index");
        fixed (byte* b = bytes)
            *((long*)(b + index)) = value;
    }
```

I think it would be great to have those methods as well whenever we try to serialize values into an array without having to use `Array.Copy` all the time. To avoid redundant code the `GetBytes` methods should then just call the new methods.

``` c#
        // Converts an int into an array of bytes with length 
        // four.
        [System.Security.SecuritySafeCritical]  // auto-generated
        public unsafe static byte[] GetBytes(int value)
        {
            Contract.Ensures(Contract.Result<byte[]>() != null);
            Contract.Ensures(Contract.Result<byte[]>().Length == 4);

            byte[] bytes = new byte[4];
            InsertBytes(value, bytes, 0);
            return bytes;
        }

        // Converts a long into an array of bytes with length 
        // eight.
        [System.Security.SecuritySafeCritical]  // auto-generated
        public unsafe static byte[] GetBytes(long value)
        {
            Contract.Ensures(Contract.Result<byte[]>() != null);
            Contract.Ensures(Contract.Result<byte[]>().Length == 8);

            byte[] bytes = new byte[8];
            InsertBytes(value, bytes, 0);
            return bytes;
        }
```

I would be happy to submit a PR once this was reviewed and approved.

**Comment by svick** [comment]
Can't you use `BinaryWriter` over `MemoryStream` for this?

**Comment by Toxantron** [comment]
Well I could, I just thought it would make a nice addition to the API. Doesn't MemoryStream and writer create unnecessary overhead when I already have array and position?

**Comment by Toxantron** [comment]
I came to think that `InsertBytes` might be a better name.

**Comment by Toxantron** [comment]
@KrzysztofCwalina I am aware of the usual workflow and that API suggestions need approval. Are there any comments on this? Otherwise I would prepare a PR against the `future` branch in the next days.

**Comment by KrzysztofCwalina** [comment]
@Toxantron, Yes, we definitely need APIs like this (non-allocating binary writer and reader). I am just not sure if this should be on BitConverter or some other type. The problem with BitConverter is that it's distributed with .NET Framework and so can evolve very slowly. A totally separate nuget package would be immediately available. I have been experimenting with similar APIs (non-allocating data transformation APIs) in corfxlab. See https://github.com/dotnet/corefxlab/tree/master/src/System.Binary/System/Binary for an example (non allocating reader).

@svick, BinaryWriter and MemryStream cause heap allocations that are often unacceptable.

**Comment by Toxantron** [comment]
@KrzysztofCwalina thanks for getting back to me. This looks pretty neat. Did you do any tests whether bit shift is faster than pointer cast?

Right now I just created my [own converter](https://github.com/Toxantron/CGbR/blob/master/CGbR.Lib/Tools/GeneratorByteConverter.cs) inspired by the BitConverter. Because it is used only be generated code the index check is skipped to achieve better performance. I plan on extending it with overloads for var int as used by googles protobuf. 

If you are interested I would love to get on board for binary conversions.

**Comment by KrzysztofCwalina** [comment]
@Toxantron, for now this is just to get the shape of non-allocating APIs. I have not done much measurements or optimizations other than memory (in the whole cofxlab). I did some optimizations of the formatting library to ensure that once we have optimized span<T>, such non allocating formatters will be able to beat the current APIs in raw execution speed too.

**Comment by Toxantron** [comment]
@KrzysztofCwalina, so I will leave this open and we see where it fits best.

**Comment by KrzysztofCwalina** [comment]
If you want to submit a PR to add it to https://github.com/dotnet/corefxlab/tree/master/src/System.Binary, it would be great. If we decide to add it to BitConverter later, the move should be very simple.

**Comment by Toxantron** [comment]
I'd be happy to. Should it use span and bit shift as well or the original proposal?

**Comment by KrzysztofCwalina** [comment]
I think it would be good to have overloads for both span and (byte[], int, int).

As to the implementation, feel free to change it if you think it will be better perf wise, as long as it does not allocate on the GC heap.

**Comment by AlexGhiondea** [comment]
@Toxantron thanks for working on this. It sounds like the best place for this to move forward is in the CoreFxLab repo.

I am going to close this issue in this repo and look forward to your contribution to the CoreFxLab repo!
