### ISSUE TITLE
.NET Core test coverage for Bash on Windows

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#7597]
https://blogs.windows.com/buildingapps/2016/03/30/run-bash-on-ubuntu-on-windows/

We should add a .NET Core test run for Bash on Windows.  @Chrisboh could you add this to Helix initially?

**Comment by mellinoe** [comment]
Is this going to be a supported scenario for RTM? We already know of things that prevent it from working right now (i.e. https://github.com/dotnet/coreclr/issues/4048 and https://github.com/dotnet/coreclr/issues/4132).

**Comment by joshfree** [comment]
It'll be runnable for dev-time scenarios, similar to OS X.

**Comment by CIPop** [comment]
Looks like there's a tracking item here #11057 stating that build/test isn't working yet.

**Comment by mellinoe** [comment]
We did disable some of the tests that were known to fail here https://github.com/dotnet/corefx/pull/11574.

It would be interesting to see how a full outerloop run fares.

**Comment by CIPop** [comment]
I'm working with the Bash on Ubuntu team offline. I was able to run build + inner on the 14967 insider build but saw some of the tests failing intermittently.
I will shortly have a few changes to the docs since they seem to point to the wrong prerequisite lib.

**Comment by Petermarcu** [comment]
On 14986 I'm seeing 5 categories of test fail on build and test from the root. This is down from 9 failing on the Anniversary build of Win10 from the same corefx SHA.

**Comment by Petermarcu** [comment]
Meant to list the 5 areas. These fail 100% of the time on my runs:

System.IO.FileSystem.Tests
System.Linq.Expressions.Tests
System.Net.NetworkInformation.Functional.Tests
System.Net.WebProxy.Tests
System.Net.Sockets.Tests

**Comment by weshaggard** [comment]
It looks like a number of similar failures are occurring when running Ubuntu in docker for windows, see https://github.com/dotnet/corefx/issues/15513.

**Comment by CIPop** [comment]
> It looks like a number of similar failures are occurring when running Ubuntu in docker for windows, see #15513.

That may prove that the failures are not particular to the Linux subsystem for Windows. Docker Linux containers on Windows uses an actual Linux VM where the Docker server is hosted.

**Comment by ViktorHofer** [comment]
I am going to check if we now have a clean run in RS5 when I have some free cycles.

**Comment by ViktorHofer** [comment]
```
/home/vihofer/corefx/Tools/tests.targets(588,5): warning :    System.IO.FileSystem.Tests  Total: 4027, Errors: 0, Failed: 11, Skipped: 15, Time: 146.386s [/home/vihofer/corefx/src/System.IO.FileSystem/tests/System.IO.FileSystem.Tests.csproj]
/home/vihofer/corefx/Tools/tests.targets(588,5): warning MSB3073: The command "/home/vihofer/corefx/bin/tests/System.IO.FileSystem.Tests/netcoreapp-Linux-Debug-x64/RunTests.sh /home/vihofer/corefx/bin/testhost/netcoreapp-Linux-Debug-x64/" exited with code 1. [/home/vihofer/corefx/src/System.IO.FileSystem/tests/System.IO.FileSystem.Tests.csproj]
/home/vihofer/corefx/Tools/tests.targets(588,5): warning :    System.IO.Pipes.Tests  Total: 507, Errors: 0, Failed: 6, Skipped: 0, Time: 13.152s [/home/vihofer/corefx/src/System.IO.Pipes/tests/System.IO.Pipes.Tests.csproj]
/home/vihofer/corefx/Tools/tests.targets(588,5): warning MSB3073: The command "/home/vihofer/corefx/bin/tests/System.IO.Pipes.Tests/netcoreapp-Linux-Debug-x64/RunTests.sh /home/vihofer/corefx/bin/testhost/netcoreapp-Linux-Debug-x64/" exited with code 1. [/home/vihofer/corefx/src/System.IO.Pipes/tests/System.IO.Pipes.Tests.csproj]
/home/vihofer/corefx/Tools/tests.targets(588,5): warning :    System.Net.Http.Unit.Tests  Total: 1626, Errors: 0, Failed: 17, Skipped: 0, Time: 114.423s [/home/vihofer/corefx/src/System.Net.Http/tests/UnitTests/System.Net.Http.Unit.Tests.csproj]
/home/vihofer/corefx/Tools/tests.targets(588,5): warning MSB3073: The command "/home/vihofer/corefx/bin/tests/System.Net.Http.Unit.Tests/netcoreapp-Linux-Debug-x64/RunTests.sh /home/vihofer/corefx/bin/testhost/netcoreapp-Linux-Debug-x64/" exited with code 1. [/home/vihofer/corefx/src/System.Net.Http/tests/UnitTests/System.Net.Http.Unit.Tests.csproj]
/home/vihofer/corefx/Tools/tests.targets(588,5): warning :    System.Net.Sockets.Tests  Total: 798, Errors: 0, Failed: 17, Skipped: 8, Time: 29.163s [/home/vihofer/corefx/src/System.Net.Sockets/tests/FunctionalTests/System.Net.Sockets.Tests.csproj]
/home/vihofer/corefx/Tools/tests.targets(588,5): warning MSB3073: The command "/home/vihofer/corefx/bin/tests/System.Net.Sockets.Tests/netcoreapp-Linux-Debug-x64/RunTests.sh /home/vihofer/corefx/bin/testhost/netcoreapp-Linux-Debug-x64/" exited with code 1. [/home/vihofer/corefx/src/System.Net.Sockets/tests/FunctionalTests/System.Net.Sockets.Tests.csproj]
/home/vihofer/corefx/Tools/tests.targets(596,5): error : One or more tests failed while running tests from 'System.IO.FileSystem.Tests' please check /home/vihofer/corefx/bin/tests/System.IO.FileSystem.Tests/netcoreapp-Linux-Debug-x64/testResults.xml for details! [/home/vihofer/corefx/src/System.IO.FileSystem/tests/System.IO.FileSystem.Tests.csproj]
/home/vihofer/corefx/Tools/tests.targets(596,5): error : One or more tests failed while running tests from 'System.IO.Pipes.Tests' please check /home/vihofer/corefx/bin/tests/System.IO.Pipes.Tests/netcoreapp-Linux-Debug-x64/testResults.xml for details! [/home/vihofer/corefx/src/System.IO.Pipes/tests/System.IO.Pipes.Tests.csproj]
/home/vihofer/corefx/Tools/tests.targets(596,5): error : One or more tests failed while running tests from 'System.Net.Http.Unit.Tests' please check /home/vihofer/corefx/bin/tests/System.Net.Http.Unit.Tests/netcoreapp-Linux-Debug-x64/testResults.xml for details! [/home/vihofer/corefx/src/System.Net.Http/tests/UnitTests/System.Net.Http.Unit.Tests.csproj]
/home/vihofer/corefx/Tools/tests.targets(596,5): error : One or more tests failed while running tests from 'System.Net.Sockets.Tests' please check /home/vihofer/corefx/bin/tests/System.Net.Sockets.Tests/netcoreapp-Linux-Debug-x64/testResults.xml for details! [/home/vihofer/corefx/src/System.Net.Sockets/tests/FunctionalTests/System.Net.Sockets.Tests.csproj]
/home/vihofer/corefx/dir.traversal.targets(77,5): error : (No message specified) [/home/vihofer/corefx/src/tests.builds]    8 Warning(s)
```

[System.Net.Http.Unit.Tests.txt](https://github.com/dotnet/corefx/files/2402273/System.Net.Http.Unit.Tests.txt)
[System.Net.Sockets.Tests.txt](https://github.com/dotnet/corefx/files/2402274/System.Net.Sockets.Tests.txt)
[System.IO.FileSystem.Tests.txt](https://github.com/dotnet/corefx/files/2402275/System.IO.FileSystem.Tests.txt)
[System.IO.Pipes.Tests.txt](https://github.com/dotnet/corefx/files/2402276/System.IO.Pipes.Tests.txt)

**Comment by ViktorHofer** [comment]
cc @safern as you recently made a change. This already includes your fix.

**Comment by danmosemsft** [comment]
Some of the IO ones are trivial @anipik
```
System.NullReferenceException: Object reference not set to an instance of an object.\n        at System.IO.Tests.BaseGetSetTimes`1.get_isHFS() in /home/vihofer/corefx/src/System.IO.FileSystem/tests/Base/BaseGetSetTimes.cs:line 19\n        at 
```

**Comment by ViktorHofer** [comment]
Closing in favor of https://github.com/dotnet/corefx/issues/11057 which has more details and tracks external WSL issues.
