### ISSUE TITLE
Weird console problem on Mac OS X

### ISSUE THREAD

**Issue by cnblogs-dudu** [dotnet/corefx#761]
It happens when I run [CoreClrHelloWorld](https://github.com/dotnet/corefxlab/blob/master/demos/CoreClrConsoleApplications/HelloWorld/HelloWorld.cs) console app to draw Linux logo on Mac OS X.
When I type `runtime_mac/corerun app/HelloWorld.exe linux` to run it, the console draw an incomplete penguin. See the below screen shot.

![screen shot 2015-02-13 at 23 30 28](https://cloud.githubusercontent.com/assets/3196961/6189881/145f5460-b3d9-11e4-8eff-b5c656d269c7.png)
After that, the console is out of control. I can move cursor and type text in console. But the console does not respond any command. The console's background color and foreground color become gray. "Press ENTER to exit ..." does not appear.

![screen shot 2015-02-13 at 23 33 00](https://cloud.githubusercontent.com/assets/3196961/6189854/d75567b2-b3d8-11e4-9c69-501957d1192a.png)
Then I comment the following two line code in HelloWorld.cs.
```csharp
ConsoleColor cc =
    c == '*' ? ConsoleColor.Blue :
    c == '@' ? ConsoleColor.Black :
    c == '-' ? ConsoleColor.Yellow :
    ConsoleColor.White;
//Console.BackgroundColor = cc;
//Console.ForegroundColor = cc;
Console.Write(" ");
```
Compile and run it. The weird console problem disappear.
Afterwards,  I try to run HelloWorld.exe by mono.
```
mono app/HelloWorld.exe linux
```
The entire enguin is been showing.
```
Hello, Linux...
[Penguin]
Press ENTER to exit ...
```
The problem can be reproduced by following below command on Mac OS X.
```
git clone https://github.com/cnblogs-dudu/CoreClrHelloWorld.git
cd CoreClrHelloWorld
runtime_mac/corerun app/HelloWorld.exe linux
```

**Comment by stephentoub** [comment]
My guess is that this is due to lack of GC at the moment.  Changing colors generates some allocations due to needing to evaluate the parameter strings in the terminfo file, and this sample is changing colors a lot.  But that's just a guess.

**Comment by pgavlin** [comment]
I have also seen this locally--it does appear that the runtime ends up hung while performing a GC in these cases.

@cnblogs-dudu, you should be able to kill the program (press CTRL-C or otherwise send SIGKILL) and run the "reset" command (even though you won't be able to see what you're typing) to get your terminal back to normal.
