### ISSUE TITLE
How to reference netstandard1.1 assemblies from PCL projects

### ISSUE THREAD

**Issue by lewischeng-ms** [dotnet/corefx#7612]
Hi guys, I am from OData team. We now have some traditional PCL projects (Profile111) and for some reason about our build system, currently we cannot upgrade them to use xproj and target a new .NET standard TFM. But we would like to reference `Microsoft.Extensions.DependencyInjection` which targets `netstandard1.1` from these PCL projects. AFAIK, the API set of Profile111 should be fully compatible with `netstandard1.1` (https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md) however I cannot install the packages using even the latest VS2015 Update 2. It said:

```
Could not install package 'Microsoft.Extensions.DependencyInjection 1.0.0-rc1-final'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

Is this error expected? If not, is there any solution here? Thanks very much for your help!

**Comment by ericstj** [comment]
You should open this issue in the repo that builds Microsoft.Extensions.DependencyInjection.

https://github.com/aspnet/DependencyInjection

I suspect the rc1-final version does not support `netstandard` monikers since those were added post RC1.

/cc @pranavkm

**Comment by pranavkm** [comment]
Like @ericstj said, the rc2 version targets `netstandard`. If you point to our release feeds (`https://www.myget.org/f/aspnetrelease`), you could grab some of our more recent builds.

**Comment by lewischeng-ms** [comment]
@ericstj @pranavkm Got it. I will have a try. Thank you very much for the instructions!
