### ISSUE TITLE
WinHttpResponseStream: Cannot access a disposed object.

### ISSUE THREAD

**Issue by GuardRex** [dotnet/corefx#7622]
@davidsh Looks like this might be for you based on other issues.

This just started cropping up with my use of both `WindowsAzure.Storage` versions `6.2.2-preview` and `7.0.1-preview` when calling `.ExecuteQuerySegmentedAsync(...)`. The resolved version of the `System.Net.Http` package is `4.0.1-rc3-24008-00`. If you would like a repro of the issue, let me know, and I'll put one up. If this is just due to current churn, no prob, I can wait (a few days anyway).

``` xml
<RequestResult>
  <HTTPStatusCode>501</HTTPStatusCode>
  <HttpStatusMessage>NotImplemented</HttpStatusMessage>
  <TargetLocation>Primary</TargetLocation>
  <ServiceRequestID>128c10da-0002-001a-0982-920393000000</ServiceRequestID>
  <ContentMd5 />
  <Etag />
  <RequestDate>Sat, 09 Apr 2016 17:07:40 GMT</RequestDate>
  <StartTime>Sat, 09 Apr 2016 17:07:38 GMT</StartTime>
  <EndTime>Sat, 09 Apr 2016 17:07:41 GMT</EndTime>
  <Error>
    <Code>NotImplemented</Code>
    <Message>The requested operation is not implemented on the specified resource.
RequestId:128c10da-0002-001a-0982-920393000000
Time:2016-04-09T17:07:40.7566462Z</Message>
  </Error>
  <ExceptionInfo>
    <Type>StorageException</Type>
    <HResult>-2146233088</HResult>
    <Message>Cannot access a disposed object.
Object name: 'System.Net.Http.WinHttpResponseStream'.</Message>
    <Source />
    <StackTrace />
    <InnerExceptionInfo>
      <ExceptionInfo>
        <Type>ObjectDisposedException</Type>
        <HResult>-2146232798</HResult>
        <Message>Cannot access a disposed object.
Object name: 'System.Net.Http.WinHttpResponseStream'.</Message>
        <Source>System.Net.Http</Source>
        <StackTrace>   at System.Net.Http.WinHttpResponseStream.CheckDisposed()
   at System.Net.Http.WinHttpResponseStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token)
   at System.Net.Http.DelegatingStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.WindowsAzure.Storage.Core.Util.StreamExtensions.&lt;WriteToAsync&gt;d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.&lt;ExecuteAsyncInternal&gt;d__4`1.MoveNext()</StackTrace>
      </ExceptionInfo>
    </InnerExceptionInfo>
  </ExceptionInfo>
</RequestResult>
```

**Comment by davidsh** [comment]
Yes, please provide a full repro.  The exception "Cannot access a disposed object" is by-design if trying call ReadAsync when the response and/or responsestream has already been disposed. But we need to find out when and by whom the stream is getting disposed.

**Comment by GuardRex** [comment]
@davidsh sure thing ... I realize it's the weekend and this might take a while (next week), but I'll have the repro up in an hour or two.

**Comment by GuardRex** [comment]
@davidsh

https://github.com/GuardRex/repro2

It's kind'a hacked together quickly. Cut-and-paste was my friend here! This should demo it. Turns out that the difference between working and failing is in the specification of a string query to the Azure Storage library.
#### Works
```
var query = new TableQuery<Data>().Where("Active eq true");
```
#### Breaks
```
var query = new TableQuery<Data>().Where("Active eq True");
```
#### Steps to Repro
1. Establish an Azure Storage Account (keep the account name and key handy)
2. Create an Azure Table named "Data"
3. Put three entities in the table (shown below)
4. Get repro ... Open the `HomeController` and provide `storage_account` and `storage_account_key`
5. `dotnet restore` and `dotnet publish`
6. Run locally in Kestrel or put on an IIS server

#### Data Table Entities

| PartitionKey  | RowKey | Active (boolean) |
| ------------- | ------------- | ------------- |
| AAA | 0001 | True |
| AAA  | 0002  | True |
| AAA  | 0003  | False |

#### Result
Queries that specify a capital boolean condition in the string query fail with the exception, while queries that specify a lowercase boolean condition return results properly. The exception is shown in the OP. IMO the exception is way off anything easy to interpret as a problem with a string query.

#### `dotnet --info`
```
.NET Command Line Tools (1.0.0-rc2-002296)

Product Information:
 Version:     1.0.0-rc2-002296
 Commit Sha:  b9d6a0c911

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by davidsh** [comment]
Closing this issue since is using very old code.  If this happens again with .NET Core 1.1 RTM, please open up a new issue. Thx.
