### ISSUE TITLE
System.Net.Http 4.1 Contract Revisions

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#7623]
## Background

To support important customer scenarios for CoreFx RTM, we want to update the System.Net.Http contract from 4.0 to 4.1.

The System.Net.Http API surface consists of several classes. All of the implementation also lives in the .NET Framework as mostly a standalone implementation DLL (System.Net.Http.dll). Some functionality depends on low level APIs (such as HttpWebRequest) that lives in System.dll

As part of updating the contract to 4.1, we are also OOB'ing the Desktop (net46 Windows) implementation so that the package won't be a facade over Desktop but rather a full implementation. As part of this, we are changing the implementation used for Desktop from the legacy HttpWebRequest sockets stack to the WinHttpHandler stack based on native WinHTTP. This will give us a good path forward as WinHttpHandler stack will be getting HTTP/2.0 support with newer versions of Windows 10. Since we are OOB'ing the DLL, we are able to add surface area as regular properties and not be forced to use extension methods (which wouldn't work in this case anyways).

.NET Framework (Desktop) developers will only get this new implementation and expanded API set when they consume the NuGet package. Otherwise .NET Framework (Desktop) developers will get the existing inbox implementation.
## Proposed API

``` c#
namespace System.Net.Http
{
    // Other classes already part of System.Net.Http 4.0 contract ...

    public partial class HttpClientHandler : System.Net.Http.HttpMessageHandler
    {
        //
        // Existing methods and properties.
        //
        public HttpClientHandler() { }
        public bool AllowAutoRedirect { get; set; }
        public System.Net.DecompressionMethods AutomaticDecompression { get; set; }
        public System.Net.Http.ClientCertificateOption ClientCertificateOptions { get; set; }
        public System.Net.CookieContainer CookieContainer { get; set; }
        public System.Net.ICredentials Credentials { get; set; }
        public int MaxAutomaticRedirections { get; set; }
        public long MaxRequestContentBufferSize { get; set; }
        public bool PreAuthenticate { get; set; }
        public System.Net.IWebProxy Proxy { get; set; }
        public virtual bool SupportsAutomaticDecompression { get; }
        public virtual bool SupportsProxy { get; }
        public virtual bool SupportsRedirectConfiguration { get; }
        public bool UseCookies { get; set; }
        public bool UseDefaultCredentials { get; set; }
        public bool UseProxy { get; set; }
        protected override void Dispose(bool disposing);
        protected internal override System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> SendAsync(System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken);

        //
        // New properties.
        //

        public bool CheckCertificateRevocationList { get; set; }

        // Wanted to have this property be on type 'X509Certificate2Collection' but conflicts
        // with derived class WebRequestHandler in .NET Framework of the same property name.
        public System.Security.Cryptography.X509Certificates.X509CertificateCollection ClientCertificates { get; set; }

        // Wanted to have this property be called 'ServerCertificateValidationCallback` but
        // that name would conflict the derived class WebRequestHandler in .NET Framework
        // where the property is of a different type.
        public System.Func<System.Net.Http.HttpRequestMessage, System.Security.Cryptography.X509Certificates.X509Certificate2, System.Security.Cryptography.X509Certificates.X509Chain, System.Net.Security.SslPolicyErrors, bool> ServerCertificateCustomValidationCallback { get; set; }

        public System.Net.ICredentials DefaultProxyCredentials { get; set; }
        public int MaxConnectionsPerServer { get; set; }
        public int MaxResponseHeadersLength { get; set; }
        public System.Security.Authentication.SslProtocols SslProtocols { get; set; }

        // Generic property bag to that would allow for additional properties to be set and recognized by particular implementations (i.e. Windows vs. Unix, Unix-only connection socket options, etc.)
        public System.Collections.Generic.IDictionary<string, object> Properties { get; }
    }
}
```
## Open Questions / Issues
- There is an existing .NET Framework type, `System.Net.Http.WebRequestHandler` that lives in `System.Net.Http.WebRequest.dll`. `WebRequestHandler` derives from `HttpClientHandler`. And `WebRequestHandler` already has these properties on the type:

``` c#
        public System.Security.Cryptography.X509Certificates.X509CertificateCollection ClientCertificates { get; set; }
        public RemoteCertificateValidationCallback ServerCertificateValidationCallback { get; set; }
```
## Usage

The new HttpClientHandler properties  being considered are currently already in the System.Net.Http.WinHttpHandler contract, as properties of the WinHttpHandler class. That contract is only implemented on Windows.

For reference, all the System.Net.\* APIs were previously reviewed including WinHttpHandler:
https://github.com/dotnet/apireviews/pull/21

Pending the 4.1 System.Net.Http review, the WinHttpHandler contract is being considered for removal from CoreFx final RTM contracts since it will be duplicative to the revised System.Net.Http 4.1 contract.

**Comment by stephentoub** [comment]
@davidsh, as part of this, did you want to expose a property bag that would allow for additional properties to be set and recognized by particular implementations?

**Comment by davidsh** [comment]
@stephentoub Yes.  I added the property to the proposed API.  This property is similar to HttpRequestMessage.Properties.

**Comment by markvincze** [comment]
Just to double-check: will this - particularly the support for `ClientCertificateOptions` - be part of the RTM release, and will it support Linux?

**Comment by stephentoub** [comment]
> will this - particularly the support for  ClientCertificateOptions  - be part of the RTM release, and will it support Linux?

Yes and yes.

**Comment by CIPop** [comment]
Reopening: still referenced in code: https://github.com/dotnet/corefx/blob/a6fc5237f0db5dc7aecf128bbb5dd7bbe570d495/src/System.Net.Http/src/netcore50/System/Net/HttpClientHandler.cs#L345

**Comment by CIPop** [comment]
@davidsh @himadrisarkar PTAL

**Comment by stephentoub** [comment]
@davidsh, this can be closed now, right?

**Comment by davidsh** [comment]
Cristian re-opened it due to this: 
https://github.com/dotnet/corefx/blob/a6fc5237f0db5dc7aecf128bbb5dd7bbe570d495/src/System.Net.Http/src/netcore50/System/Net/HttpClientHandler.cs#L345

And the fact the contract is not fully enabled for netcore50.

**Comment by chlowell** [comment]
Just to clarify: what remains to be implemented for client certificates? Does basic code like the below (no custom validation) work on all platforms?
```cs
var handler = new HttpClientHandler
{
    ClientCertificateOptions = ClientCertificateOption.Manual
};
handler.ClientCertificates.Add(someCert);
var client = new HttpClient(handler);
var response = await client.GetAsync(url);
```

**Comment by davidsh** [comment]
>Just to clarify: what remains to be implemented for client certificates?

What type of application are you building?  If it is an ASP.NET app (Windows or Linux), then client certificate work today in the latest stable System.Net.Http NuGet package.

If you are building a Window UWP Store App, then that functionality is NOT yet working.

**Comment by chlowell** [comment]
Thanks, that's good to know. It's an ASP.NET app targeting Linux.

**Comment by justin-lavelle** [comment]
Does HttpClient work with a client certificate? 
Using dotnet 1.1 with System.Net.Http 4.3.0 in a console app and asp.net site.

```c#
var handler = new HttpClientHandler() { ClientCertificateOptions = ClientCertificateOption.Manual };
handler.ClientCertificates.Add(settings.ClientCertificate);
var httpClient = new HttpClient(handler);
var responseMsg = await httpClient.SendAsync(requestMsg);
```
It works fine on Windows 8.1/10 but fails on CentOS 7 with the following error...

_Exception: System.PlatformNotSupportedException: The libcurl library in use (7.29.0) and its SSL backend ("NSS/3.19.1 Basic ECC") do not support custom handling of certificates. A libcurl built with OpenSSL is required._

I tried using libcurl-openssl and exporting LD_LIBRARY_PATH as well and get the following error

_Exception: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: SSL peer certificate or SSH remote key was not OK_

**Comment by davidsh** [comment]
>Does HttpClient work with a client certificate on linux (CentOS) at this point in time?

In general, the answer is yes.  However, if you are having a problem, I recommend you open a new issue for this problem.  This issue itself is tracking a different task (regarding Windows UWP).

Thx,

**Comment by karelz** [comment]
It's part of our UWP .NET Standard 2.0 work (in planning).

**Comment by davidsh** [comment]
Tracking this as part of #20010
