### ISSUE TITLE
C# 6: `when` could be used in a couple of places

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#7632]
C# 6 introduces exception filters via `when`, which can transform code of this form

```cs
try
{
    Foo();
}
catch (Exception e)
{
    if (e is BarException) throw;

    DoSomeWork();
}
```

to this:

```cs
try
{
    Foo();
}
catch (Exception e) when (!(e is BarException))
{
    DoSomeWork();
}
```

I believe this is supposed to be faster than the previous version as well, since in the case of `e` being a `BarException` you don't have to actually catch the exception and just let it propogate up the tree.

Anyway, this is a tracking issue I'm opening because it looks like there's a bunch of places in the repo that could use this feature. See: https://gist.github.com/anonymous/d4a45e9996abf589a561ee251b341d7a I'll be opening a couple of PRs to use exception filters in these places within the next few days.

**Comment by stephentoub** [comment]
> I believe this is supposed to be faster than the previous version as well, since in the case of e being a BarException you don't have to actually catch the exception and just let it propogate up the tree.

The difference s minor when compared to the costs involved in throwing an exception relative to anything else happening.  Further, while it's likely to be a bit faster for the case where the filter doesn't match, it's likely to be a bit slower for the case where the filter does match, so this isn't something where every replacement is actually a win.

> Anyway, this is a tracking issue I'm opening because it looks like there's a bunch of places in the repo that could use this feature.

Thanks, but we don't need an issue tracking this.  If there are particular cases where switching to using exception filters makes an impactful difference, for readability, maintainability, or performance, we can consider PRs for such things on a case-by-case basis, but we do not want to go through and blindly replace all such cases with exception filters.  Additionally, your gist includes cases that aren't relevant, e.g. the "if (castedAsyncResult.Result is Exception)" example in Socket.cs isn't in a catch block.

Any PRs need to include justification for why the change is impactful.

Thanks.
