### ISSUE TITLE
NamedPipeClientStream poorly handles the case where the pipe does not exist

### ISSUE THREAD

**Issue by jstarks** [dotnet/corefx#7635]
NamedPipeClientStream waits when the pipe does not exist, and it waits by spinning:

                // Some platforms may return immediately from TryConnect if the connection could not be made, 
                // e.g. WaitNamedPipe on Win32 will return immediately if the pipe hasn't yet been created,
                // and open on Unix will fail if the file isn't yet available.  Rather than just immediately
                // looping around again, do slightly smarter busy waiting.
                sw.SpinOnce();

This is problematic for two reasons.

1. I typically do not want to wait if the pipe does not exist; I only want to wait if the pipe is busy. This is because if the pipe doesn't exist, the server is probably not running, so waiting is unlikely to resolve anything.

2. Spinning on file not found consumes an entire CPU waiting for a service to start. Not a good choice.

This combination of problems basically makes timeouts larger than a few milliseconds useless if there is any risk that the pipe will not exist.

To fix this, I would propose two things:

1. Stop spinning. Sleep for a short time if you must poll.

2. Provide an option to fail if the pipe does not yet exist. Frankly I think this should be the default, but there are probably compatibility implications of this.

**Comment by stephentoub** [comment]
> Stop spinning. Sleep for a short time if you must poll.

SpinOnce does that.  It uses a mixture of Thread.SpinWait, Thread.Yield, and Thread.Sleep, including Thread.Sleep(1), which in most circumstances is indistinguishable from Thread.Sleep(10) or so.

> Provide an option to fail if the pipe does not yet exist.

This exists: pass a timeout of 0.

**Comment by jstarks** [comment]
@stephentoub You're right, my mistake on the spinning. It turns out that I am observing spinning only when running on the .NET Framework 4.6.1, where System.IO.Pipes is backed by System.Core. According to the reference source for 4.6.1, there is no delay, just a tight loop. I don't quite understand the relationship between the .NET Framework releases and corefx -- will the corefx improvements make it into a future version of the framework?

Regarding the timeout, perhaps I wasn't clear. I can pass a timeout of 0, but this will fail in the case where the pipe exists but is not currently available (because the server is busy). I would like to wait up to, say, 5 seconds for the server to free up, but I want to give instant feedback to the user if the pipe doesn't exist at all, which would indicate that the server is not running or that they got the pipe address wrong. I don't believe there is a straightforward way to achieve this today.

**Comment by ianhays** [comment]
>I don't quite understand the relationship between the .NET Framework releases and corefx -- will the corefx improvements make it into a future version of the framework?

Not all of the changes, but some of them. CoreFX is a part of the "Core" .NET that is a distinct product from the full .NET framework (e.g. 4.6.2). Some changes to the core are incompatible with the full framework, so we cherry-pick high-priority, highly-compatible improvements in CoreFX to bring back to the full framework for the next release there.

**Comment by ianhays** [comment]
> I want to give instant feedback to the user if the pipe doesn't exist at all, which would indicate that the server is not running or that they got the pipe address wrong. I don't believe there is a straightforward way to achieve this today.

I can't think of a non-hacky solution. I agree that any modification would have to be parallel to the existing default behavior as we would run into back-compat nightmares. Plus the existing behavior isn't <i>wrong</i>; what if you wanted to connect to a server in the next 10 seconds and you didn't care when that server was created as long as the operation succeeds before the timeout?

**Comment by jstarks** [comment]
You're right that the existing behavior isn't wrong, but I would argue that it's rarely useful. The caller easily could have added a retry loop if he wanted the behavior you're describing. But there's no way to remove the retry loop without also losing the WaitNamedPipe functionality.

Based on your retargeting of the milestone, it sounds like I'm just going to have to live with a short timeout for now, or I'm going to have to fork this code.

**Comment by ianhays** [comment]
>Based on your retargeting of the milestone, it sounds like I'm just going to have to live with a short timeout for now, or I'm going to have to fork this code.

**Comment by karelz** [comment]
No response for a long time, closing. If you have proposal for the API, feel free to reopen.
