### ISSUE TITLE
System.Data.SqlClient still uses the non-generic collections

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#7637]
A quick [GitHub search](https://github.com/dotnet/corefx/search?l=json&q=NonGeneric&utf8=%E2%9C%93) shows that `System.Collections.Specialized` and `System.Data.SqlClient` are the only non-test assemblies still dependent on the non-generic collections. While it's kind of inevitable for the specialized collections since it contains a lot of legacy code, it appears from [this](https://github.com/dotnet/corefx/pull/6527) PR that we can remove `System.Collections.NonGeneric` from the `SqlClient` implementation, since it's not exposed to callers.

This is a tracking issue I'm opening up to remove the dependency from `SqlClient`.

**Comment by justinvp** [comment]
I have a PR that's almost ready that removes the dependency.
