### ISSUE TITLE
Command files (*.cmd) can't use directories with spaces

### ISSUE THREAD

**Issue by McNeight** [dotnet/corefx#7640]
When creating or evaluating an environment variable, quotes are not required:

``` batchfile
set INIT_TOOLS_LOG=%~dp0init-tools.log
if [%PACKAGES_DIR%]==[] set PACKAGES_DIR=%~dp0packages\
```

However, when turning that environment variable into a file to be used, quotes are required. Instead of:

``` batchfile
set /P BUILDTOOLS_VERSION=< %~dp0BuildToolsVersion.txt
echo %PROJECT_JSON_CONTENTS% > %PROJECT_JSON_FILE%
echo Running %0 > %INIT_TOOLS_LOG%
```

The correct syntax is:

``` batchfile
set /P BUILDTOOLS_VERSION=< "%~dp0BuildToolsVersion.txt"
echo %PROJECT_JSON_CONTENTS% > "%PROJECT_JSON_FILE%"
echo Running %0 > "%INIT_TOOLS_LOG%"
```

Because of the lack of quotes, any attempt to use these command files in a directory with spaces will fail.

-Neil

**Comment by weshaggard** [comment]
cc @joperezr @maririos

**Comment by McNeight** [comment]
Two further notes:
To be clear, the spaces can be anywhere in the path and not just the current working directory. For example, any subfolder of  "C:\Users\Neil\Documents\Visual Studio 2015\" is not going to work.

Also, I discovered that putting quotes around the --packages path for `dotnet restore` will cause the command to fail. I've written this up as dotnet/cli/issues/2395

-Neil

**Comment by weshaggard** [comment]
Thanks @McNeight. Please feel free to submit some PR's to fix up the scripts to correctly handle spaces in the paths. This is something that always bugs me too and I try to fix them when I find them but I've not had enough cycles to dig in recently.

**Comment by brfalcon** [comment]
Is this issue still open? I've that the scripts already have been fixed.

**Comment by karelz** [comment]
If you know which PR fixed it, please link it. Closing as per info above.
cc: @mellinoe
