### ISSUE TITLE
System.* contract packages don't work on netstandard compatible portable profiles with packages.config

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#7649]
According to this https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#portable-profiles I should be able to install packages that target netstandard into certain compatible PCL profiles. When using nuget 3.4 in VS update 2, the support is there to make this work, but the BCL contract packages aren't authored to support it. It means that it's not possible to author a single netstandard folder and have it work in all the places netstandard is supposed to work.

**Comment by ericstj** [comment]
We need placeholders for the PCL profiles that support these contracts.

**Comment by joshfree** [comment]
consider for rc2 depending on risk / work involved

**Comment by ericstj** [comment]
Fix for CoreFx: https://github.com/dotnet/corefx/issues/7665
Fix for WCF: https://github.com/dotnet/wcf/pull/1008
