### ISSUE TITLE
System.Data needs .Net 4.5.1 targeting pack 

### ISSUE THREAD

**Issue by saurabh500** [dotnet/corefx#7662]
System.Data was created with the requirement of being compatible with .Net 4.5.1 
However the System.Data.Common and SqlClient assembly facades are referencing 4.5 

This is causing incompatibility in ApiCompat

Can the .Net targeting packs for .Net 4.5.1 be added so that System.Data can target them?

**Comment by saurabh500** [comment]
Blocks #6937 and #6938

**Comment by saurabh500** [comment]
cc @AlexGhiondea

**Comment by weshaggard** [comment]
This should exist on the dotnet-core feed now.

**Comment by saurabh500** [comment]
Yes. This is available now. Closing issue.
