### ISSUE TITLE
FileSystemWatcher double / on OSX

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/corefx#7680]
While on OSX El Capitan, using System.IO.FileSystem.Watcher 4.0.0-rc2-23931 and the code below

```
FileSystemWatcher f = new FileSystemWatcher("/Users/victorhurdugaci/dev/temp/x");
f.Created += (s, e) => {
    Console.WriteLine(e.FullPath);
};
f.EnableRaisingEvents = true;
```

`FullPath` returns a double `/` before the file name:

```
/Users/victorhurdugaci/dev/temp/x//foo.txt
```

**Comment by victorhurdugaci** [comment]
Marking as blocking partner because we a lot of code where we compare paths and the comparisons fail

**Comment by sokket** [comment]
Investigating now...

**Comment by sokket** [comment]
Found the issue and have a fix ready. Sending out the PR with description of the issue and fix now

**Comment by sokket** [comment]
Fixed! Thanks for finding this!

**Comment by victorhurdugaci** [comment]
Was this backported to rc2?

**Comment by sokket** [comment]
The PR is out to port now. I added you as FYI
