### ISSUE TITLE
Path.Combine on Unix thinks the filename /foo is rooted

### ISSUE THREAD

**Issue by sokket** [dotnet/corefx#7685]
Uncovered via #7680, calling ```Path.Combine``` with the following parameters yields unexpected results:
```
string fullDirectory = "/foo/bar.txt";
string dirName = "/foo/";
string fileName = "/bar.txt";
string result = Path.Combine(dirName, fileName);
Assert.Equal(fullDirectory, result);
```

This fails because ```fileName``` is thought to be rooted since it begins with a '/' character.

**Comment by gucluoz** [comment]
I think there should be *nix specific versions of Combine since cross platform CombineNoChecks() returns Path2 (or Path3) by checking if it's rooted. While it seems legit in Windows, it may yield unexpexted results as above.

This is due to the assumption of VolumeSeperatorChar and DirectorySeperator being same in Unix. "/bar.txt" would denote a rooted file when used individually but one might think it in a non-rooted manner while using in the Combine() scope.

**Comment by stephentoub** [comment]
Pulling back to 1.0.0-rtm; if we're going to consider a behavior change for the API, it should be prior to that milestone ending.  Otherwise, if a new API will be considered, it can be pushed out.

**Comment by ianhays** [comment]
>This fails because fileName is thought to be rooted since it begins with a '/' character.

That's makes sense though, right? From Path's perspective, ```/bar.txt``` <i>is</i> a rooted path just like ```/foo/``` or ```/``` are. It's functioning as the docs define the behavior.

>This is due to the assumption of VolumeSeperatorChar and DirectorySeperator being same in Unix. 

This is also how Windows does it and ```/```  is barely a root prefix there (cc: @JeremyKuhne ). The example in the OP fails on .NET 4.6.2 as well as Windows core.

**Comment by JeremyKuhne** [comment]
One way to look at the current logic is a coalescing of `cd` commands. From that perspective it _kind of_ makes sense. That said I've never been fond of the root checking- particularly in the case of the starting separator. It ends up being a gotcha- I don't think most people intuit that Combine will do anything other than make sure there is a single separator between them. It isn't called `.Navigate()` or `.Resolve()` after all.

This simple combining behavior is what appears to happen with Java's `File` class. Python's `os.path.join` doesn't have the same behavior as `Path.Combine` with the directory separator, but does with drive letters for Windows.

If we do change it I'd like to see the checks for invalid characters go away. It doesn't make much sense as some "useless" paths will still come out of it (such as `*\*`).

**Comment by ianhays** [comment]
When I was first starting out with C# I was constantly annoyed with Path functions doing validation I didn't want them to (e.g. throwing PathTooLongExceptions on paths I made that had lots of ```../../```). I eventually just starting doing ```str1 + "/" + str2 + "/"```, ignoring Path.Combine entirely. I"m not crazy about the behavior but it is technically correct so I'm going to to relabel the issue.

I think that ideally Path.Combine should do a rooted check on Windows but only treat drive letter paths and maybe ```\\``` as rooted. Treating paths that begin with ```/``` as rooted isn't useful on Unix and it's odd on Windows. Unix would then not root check at all to match Windows' directory separator behavior. It sounds like this is what Python does.

I don't have a strong opinion on invalid character checking... though I do think we should keep our checks for the null character.

**Comment by ianhays** [comment]
I've got a closed-out PR up (https://github.com/dotnet/corefx/pull/8319) with this implementation if we decide to change it in the future, but for RTM at least we should leave it as is.
