### ISSUE TITLE
Update System.Linq.Expressions and System.Text.RegularExpressions package versions

### ISSUE THREAD

**Issue by chcosta** [dotnet/corefx#7695]
https://github.com/dotnet/corefx/commit/051ef074c324e123d21ede9ff9c00e49438ec1b7 updated the assembly version for some libraries but did not update the package versions.  This will cause a problem when we are building tests against packages if we do not provide an explicit package drop source then it will attempt to determine the package version by looking at the assembly version (from the csproj) and then will fail to resolve the packages from anywhere.

https://github.com/dotnet/corefx/blob/051ef074c324e123d21ede9ff9c00e49438ec1b7/src/System.Linq.Expressions/pkg/System.Linq.Expressions.pkgproj#L4

https://github.com/dotnet/corefx/blob/051ef074c324e123d21ede9ff9c00e49438ec1b7/src/System.Text.RegularExpressions/pkg/System.Text.RegularExpressions.pkgproj#L4

**Comment by ericstj** [comment]
Please make sure to update the baseline list in buildtools as well.
