### ISSUE TITLE
Test dlls and pdbs containing large tables

### ISSUE THREAD

**Issue by tmat** [dotnet/corefx#7697]
We don't have much test coverage of PE files (and Portable PDBs) with large numbers of rows.
The correctness of size calculation of cross table reference (2B vs 4B) is thus not validated. 

The problem with testing is that it requires somewhat large files. Having them checked into the repo is not ideal. Instead they should be generated in-memory using the metadata writer once it's ready.

See bug https://github.com/dotnet/roslyn/issues/10401 for an example of an issue encountered recently.

**Comment by joshfree** [comment]
Test binaries could also go into https://github.com/dotnet/corefx-testdata and then uploaded to nuget.org

**Comment by tmat** [comment]
Fixed by #8387
