### ISSUE TITLE
System.Xml.XmlSerializer uses non-generic shim collections

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#7699]
It appears from [here](https://github.com/dotnet/corefx/tree/master/src/System.Xml.XmlSerializer/src/System/Collections) that, although it doesn't depend on `System.Collections.NonGeneric`, the `XmlSerializer` assembly has a few shim non-generic collection classes since it hasn't been refactored yet from its port to .NET Core. Indeed, hitting Shift + F12 in Visual Studio shows that `InternalHashtable` is being used in at least 32 different places, and `ArrayList` at least 20. It would be better to eliminate usages of these classes, so less code + avoiding things like boxing/casting.

**Comment by joshfree** [comment]
Thanks @jamesqo for creating this issue. /cc @khdang @zhenlan
