### ISSUE TITLE
Some Xml encoding tests lost their encoding

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#77]
Some of Xml tests were testing problematic characters in different Encoding (like Russian characters). At some point few years back the encoding was lost while moving between different repos. Tests pass because .cs files lost their encoding too. Tests need to be rewritten since there is no trace of original copy

**Comment by IDisposable** [comment]
+1 for UTF8

**Comment by danmosemsft** [comment]
I updated the contribution guidelines.

@krwq do you have a pointer to what tests these actually are?

**Comment by krwq** [comment]
@danmosemsft
I think the issue was about this particular file and to re-validate rest of them https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/Xml/XPath/TestData/Russian_problem_chars.xml
Likely some of those are affected: (there are only few tests to check)
https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/Xml/XPath/TestsWithEncoding/MiscWithEncodings.cs

**Comment by Petermarcu** [comment]
@krwq @danmosemsft Is this issue tracking anything useful at this point? It's 3 years old.

**Comment by danmosemsft** [comment]
I'm going to guess nobody's going to do this at this point...
