### ISSUE TITLE
Win7 Outer Loop Test Failures in System.Globalization.Tests.TextInfoToLower.ToLower (and TextInfoToUpper.ToUpper)

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#7700]
https://github.com/dotnet/corefx/blob/d725f9f6a7232118f9179dc74f56af8ae54dc269/src/System.Globalization/tests/TextInfo/TextInfoToLower.cs#L78

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win7_release/lastCompletedBuild/testReport/System.Globalization.Tests/TextInfoToLower/ToLower_name___en_US___str___34__34____34______34________34__________34____________34______________34___________________expected___34__34____34______34________34__________34____________34______________34________________34____________________/

MESSAGE:
Assert.Equal() Failure\r\n ↓ (pos 1)\r\nExpected: 𐐀\r\nActual: 𐐨\r\n ↑ (pos 1)
+++++++++++++++++++
STACK TRACE:
at System.Globalization.Tests.TextInfoToLower.ToLower(String name, String str, String expected) in d:\j\workspace\outerloop_win---627ab81b\src\System.Globalization\tests\TextInfo\TextInfoToLower.cs:line 81

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win7_release/lastCompletedBuild/testReport/System.Globalization.Tests/TextInfoToLower/ToLower_name___fr___str___34__34____34______34________34__________34____________34______________34________________34__________________34____________________34______________________34___________________________expected___34__34____34______34________34__________34____________34______________34________________34__________________34____________________34______________________34________________________34____________________________/

MESSAGE:
Assert.Equal() Failure\r\n ↓ (pos 1)\r\nExpected: 𐐀\r\nActual: 𐐨\r\n ↑ (pos 1)
+++++++++++++++++++
STACK TRACE:
at System.Globalization.Tests.TextInfoToLower.ToLower(String name, String str, String expected) in d:\j\workspace\outerloop_win---627ab81b\src\System.Globalization\tests\TextInfo\TextInfoToLower.cs:line 81

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win7_release/lastCompletedBuild/testReport/System.Globalization.Tests/TextInfoToLower/ToLower_name___fr_FR___str___34__34____34______34________34__________34____________34______________34________________34__________________34____________________34______________________34________________________34__________________________34____________________________34______________________________34___________________________________expected___34__34____34______34________34__________34____________34______________34________________34__________________34____________________34______________________34________________________34__________________________34____________________________34______________________________34________________________________34____________________________________/

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win7_release/lastCompletedBuild/testReport/System.Globalization.Tests/TextInfoToUpper/ToUpper_name___en_US___str___34__34____34______34________34__________34____________34______________34________________34__________________34____________________34______________________34________________________34__________________________34____________________________34______________________________34________________________________34__________________________________34____________________________________34______________________________________34________________________________________34__________________________________________34____________________________________________34______________________________________________34___________________________________________________expected___34__34____34______34________34__________34____________34______________34________________34__________________34____________________34______________________34________________________34__________________________34____________________________34______________________________34________________________________34__________________________________34____________________________________34______________________________________34________________________________________34__________________________________________34____________________________________________34______________________________________________34________________________________________________34____________________________________________________/

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win7_release/lastCompletedBuild/testReport/System.Globalization.Tests/TextInfoToUpper/ToUpper_name___fr___str___34__34____34______34________34__________34____________34______________34________________34__________________34____________________34______________________34________________________34__________________________34____________________________34______________________________34________________________________34__________________________________34____________________________________34______________________________________34________________________________________34__________________________________________34____________________________________________34______________________________________________34________________________________________________34__________________________________________________34____________________________________________________34______________________________________________________34___________________________________________________________expected___34__34____34______34________34__________34____________34______________34________________34__________________34____________________34______________________34________________________34__________________________34____________________________34______________________________34________________________________34__________________________________34____________________________________34______________________________________34________________________________________34__________________________________________34____________________________________________34______________________________________________34________________________________________________34__________________________________________________34____________________________________________________34______________________________________________________34________________________________________________________34____________________________________________________________/

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win7_release/lastCompletedBuild/testReport/System.Globalization.Tests/TextInfoToUpper/ToUpper_name___fr_FR___str___34__34____34______34________34__________34____________34______________34________________34__________________34____________________34______________________34________________________34__________________________34____________________________34______________________________34________________________________34__________________________________34____________________________________34______________________________________34________________________________________34__________________________________________34____________________________________________34______________________________________________34________________________________________________34__________________________________________________34____________________________________________________34______________________________________________________34________________________________________________________34__________________________________________________________34____________________________________________________________34______________________________________________________________34___________________________________________________________________expected___34__34____34______34________34__________34____________34______________34________________34__________________34____________________34______________________34________________________34__________________________34____________________________34______________________________34________________________________34__________________________________34____________________________________34______________________________________34________________________________________34__________________________________________34____________________________________________34______________________________________________34________________________________________________34__________________________________________________34____________________________________________________34______________________________________________________34________________________________________________________34__________________________________________________________34____________________________________________________________34______________________________________________________________34________________________________________________________________34____________________________________________________________________/

**Comment by tarekgh** [comment]
this issue should be fixed now by the linked PR #7708

**Comment by joshfree** [comment]
I kicked off manual re-runs of the win7 outerloop just now

**Comment by tarekgh** [comment]
@joshfree thanks.
