### ISSUE TITLE
InputOSGroup not correctly set when building individual test projects for x-plat

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#7705]
`c:\Users\stoub\Source\repos\corefx\src\System.Diagnostics.Process\tests>msbuild /t:rebuild /p:OSGroup=Linux /v:m`

With that command line it ends up building the Linux version of the tests but the Windows version of the product libraries:

```
System.Diagnostics.Process -> c:\Users\stoub\Source\repos\corefx\bin\Windows_NT.AnyCPU.Debug\System.Diagnostics.Process\System.Diagnostics.Process.dll
RemoteExecutorConsoleApp -> c:\Users\stoub\Source\repos\corefx\bin\Windows_NT.AnyCPU.Debug\RemoteExecutorConsoleApp\RemoteExecutorConsoleApp.exe
System.Diagnostics.Process.Tests -> c:\Users\stoub\Source\repos\corefx\bin\Linux.AnyCPU.Debug\System.Diagnostics.Process.Tests\System.Diagnostics.Process.Tests.dll 
```

That is because the InputOSGroup isn't set correctly and defaults to OSEnvironment windows is Windows_NT when building this on Windows. 

As a temporary workaround you can do:
`c:\Users\stoub\Source\repos\corefx\src\System.Diagnostics.Process\tests>msbuild /t:rebuild /p:OSGroup=Linux /p:InputOSGroup=Linux /v:m`

We should do some more testing of the test infrastructure to make sure basic scenarios like this work, in our dev workflow.

cc @maririos @stephentoub @sokket

**Comment by mellinoe** [comment]
The described issue no longer repros, so I'm going to close this. Technically it's only fixed because we build every configuration now (because of the test's pkgproj references), but it's fixed nonetheless.
