### ISSUE TITLE
System.Net.Security.Tests.KerberosTest.NegotiateStream_StreamToStream_AuthToHttpTarget_Success [FAIL]

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#7713]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_rhel7.2_release_tst/47/consoleFull#-21371504001f1a4601-6aec-4fd5-b678-78d4389fd5e8

08:18:33 === TEST EXECUTION SUMMARY ===
08:18:33    System.Net.Primitives.Functional.Tests  Total: 260, Errors: 0, Failed: 0, Skipped: 0, Time: 5.249s
08:18:40    System.Net.Security.Tests.KerberosTest.NegotiateStream_StreamToStream_AuthToHttpTarget_Success [FAIL]
08:18:40       System.AggregateException : One or more errors occurred. (A call to SSPI failed, see inner exception.)
08:18:40       ---- System.Security.Authentication.AuthenticationException : A call to SSPI failed, see inner exception.
08:18:40       -------- System.ComponentModel.Win32Exception : ErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - An invalid status code was supplied (Server not found in Kerberos database).
08:18:40          at Interop.GssApi.EstablishSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags)
08:18:40          at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, Boolean isNtlm, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)
08:18:40       Stack Trace:
08:18:40             at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
08:18:40             at System.Net.Security.Tests.KerberosTest.NegotiateStream_StreamToStream_AuthToHttpTarget_Success()
08:18:40          ----- Inner Stack Trace -----
08:18:40             at System.Net.Security.NegoState.EndProcessAuthentication(IAsyncResult result)
08:18:40             at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
08:18:40          ----- Inner Stack Trace -----
08:18:40          
08:18:40 Finished:    System.Net.Security.Tests
08:18:40 
08:18:40 === TEST EXECUTION SUMMARY ===
08:18:40    System.Net.Security.Tests  Total: 106, Errors: 0, Failed: 1, Skipped: 0, Time: 11.159s
08:18:40 error: One or more tests failed while running tests from ''.  Exit code 1.

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/7707
