### ISSUE TITLE
LINQ: Append/Prepend/Cast could probably be optimized

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#7719]
Currently, the implementation for `Append` looks like this:

``` cs
public static IEnumerable<T> Append<T>(this IEnumerable<T> source, T value)
{
    foreach (var item in source)
        yield return item;

    yield return value;
}
```

This looks like it's missing out on chances for optimization. For example, this code could probably be optimized if `items` was an array/list:

``` cs
items.Append(foo).ToArray();
```

since we'd know that the result would have a length of exactly `items.Length + 1`. Same for this:

``` cs
items.Append(foo).Count();
```

cc @JonHanna 

---

**edit:** Also `Cast` too, since the number of elements in the resulting enumerable is guaranteed to have the same number of items as the source. Today we still naively use an iterator block like this:

``` cs
public static IEnumerable<T> Cast<T>(this IEnumerable source)
{
    foreach (object obj in source)
        yield return (T)obj;
}
```

**Comment by JonHanna** [comment]
See #6864

**Comment by stephentoub** [comment]
This has been addressed.
