### ISSUE TITLE
Should ArrayPool do less work with the lock taken?

### ISSUE THREAD

**Issue by rynowak** [dotnet/corefx#7727]
We're starting to get to the point with ASP.NET perf where we're starting to see the ArrayPool show up in profiles. This is good because we're making more use of it, and making enough improvements in other places that the ArrayPool is now visible.

Example sampling data:
![image](https://cloud.githubusercontent.com/assets/1430011/14512502/7045eff0-0194-11e6-8b1e-f3c6d07d450e.png)

Roughly 00.59% of the time spent to execute a basic Razor/MVC view is spent checking out the buffers that we'll use for encoding text and writing output.

==============================

The question in my mind is, should we move more of the work done outside of the 'lock'?

https://github.com/dotnet/corefx/blob/master/src/System.Buffers/src/System/Buffers/DefaultArrayPoolBucket.cs#L58

IIRC `new` can be a blocking operation if the thread's memory chunk can't satisfy the allocation, which is likely when we're talking about buffers.

==============================

Also, is `SpinLock` the right construct for this? I'm a little perturbed seeing `Thread.Sleep` show up in the trace. 

Our usage in ASP.NET uses buffers of predictable sizes, so we're not really benefiting from striping locks across sizes. 

@sokket @KrzysztofCwalina @stephentoub

**Comment by benaadams** [comment]
if all the buffers are allocated at lower levels `Rent(int)` will be calling `Rent()+lock` in a loop as it chases up the buckets looking for an empty one so the call ratio of `Rent(int)` -> `Rent()` will be much higher than expected. 

Depending on the concurrency you may also have threads contending for the locks at each level; which may trigger the `SpinLock` to spin more and therefore hit sleep backoffs.

**Comment by rynowak** [comment]
Ben's change did improve this, we're going to take a look at more scenarios and collect more data to see if other changes would be an improvement.

(Note that the timings are not comparable, but the percentages are)

**Baseline**
![image](https://cloud.githubusercontent.com/assets/1430011/14536730/b8bc2a3a-0228-11e6-87ca-58ecba4d0b43.png)


**Allocation moved outside of lock**
![image](https://cloud.githubusercontent.com/assets/1430011/14536755/e127850a-0228-11e6-8302-97d3c8be3a75.png)

**Comment by stephentoub** [comment]
As of https://github.com/dotnet/corefx/pull/7738 it's no longer allocating while holding the lock.
