### ISSUE TITLE
Support OS X 10.9

### ISSUE THREAD

**Issue by andschwa** [dotnet/corefx#7731]
The widely popular [Travis CI](https://travis-ci.com/)'s OS X build machines run [10.9.5](https://docs.travis-ci.com/user/osx-ci-environment/#CI-environment-OS). While NuGet (in .NET CLI) recognizes the platform with the "osx.10.9-x64" moniker, unfortunately, .NET Core does not (yet) build packages for 10.9, thus resulting in errors from NuGet and a failed build.

Please consider supporting 10.9 (at least on a best-effort basis, provide runtime packages) so that we can officially expand our internal project's support matrix to OS X by continuing to use Travis CI.

**Comment by joshfree** [comment]
@andschwa 10.11 is our current minimum supported version of OS X.  Older releases 10.9.x and 10.10.x are in limited "Security updates and printer drivers only" support from Apple.

**Comment by joshfree** [comment]
@akoeplinger I see your name in the travis-ci docs (https://docs.travis-ci.com/user/languages/csharp/) :smile: - do you know when travis-ci will upgrade their build machines to os x 10.11?

**Comment by MariadeAnton** [comment]
Sorry for the confusion!

Currently these versions are supported:

- Xcode 7.3 (OS X 10.11) – `osx_image: xcode7.3`
- Xcode 7.2 (OS X 10.11) – `osx_image: xcode7.2`
- Xcode 7.1 (OS X 10.10) – `osx_image: xcode7.1`
- Xcode 7 (OS X 10.10) – `osx_image: xcode7`
- Xcode 6.4 (OS X 10.10) – `osx_image: xcode6.4`
- Xcode 6.3 (OS X 10.10) – `osx_image: beta-xcode6.3`
- Xcode 6.2 (OS X 10.9) – `osx_image: beta-xcode6.2`
- Xcode 6.1 (OS X 10.9) – `osx_image: beta-xcode6.1` – Default when no other osx_image: is specified

from: https://docs.travis-ci.com/user/languages/objective-c#Supported-OS-X-iOS-SDK-versions

**Comment by akoeplinger** [comment]
@joshfree I'm a co-maintainer of the community C# support in Travis, so I don't really have control over when they upgrade :)

According to the list María provided above it should be possible to switch your builds to an OSX supported by .NET Core (something I need to keep in mind for my plans of adding support for .NET Core along Mono on Travis, so thanks for the issue!).

**Comment by jasonwilliams200OK** [comment]
@andschwa, you can add a key:

```yml
osx_image: xcode7.3
```

in your `.travis.yml` file, to use OS X 10.11.

Reference: https://github.com/search?q=extension%3Ayml+osx_image&ref=searchresults&type=Code&utf8=%E2%9C%93

**Comment by andschwa** [comment]
Ah I was one Google away from finding this last night! Thank you very much @MariadeAnton and @joshfree; setting said key enabled OS X 10.11, and now I just have to deal with `dotnet restore` and `too many open files`, but that was too be expected.

**Comment by andschwa** [comment]
And we're golden; matrix expanded to OS X :smile:
