### ISSUE TITLE
ARM64: Tests failing due to missing native components

### ISSUE THREAD

**Issue by ramarag** [dotnet/corefx#7737]
Need to investigate failures, most of them might be fixed when the native dependency is built for arm64.
But do verify they pass after that 

System.Data.SqlClient.Tests  Total: 25, Errors: 0, Failed: 2, Skipped: 0, Time: 12.869s
System.IO.Compression.Tests  Total: 143, Errors: 0, Failed: 113, Skipped: 0, Time: 61.830s
System.IO.Compression.ZipFile.Tests  Total: 24, Errors: 0, Failed: 12, Skipped: 0, Time: 19.632s
System.IO.FileSystem.DriveInfo.Tests  Total: 9, Errors: 0, Failed: 1, Skipped: 0, Time: 9.713s
System.IO.FileSystem.Tests  Total: 2227, Errors: 0, Failed: 18, Skipped: 25, Time: 4181.445s
System.IO.Packaging.Tests  Total: 131, Errors: 0, Failed: 112, Skipped: 0, Time: 67.804s

**Comment by joshfree** [comment]
@ramarag depending on the error, you may want to split the sqlclient failure into a separate bug for saurabh500.

**Comment by kyulee1** [comment]
Some of failures are not relevant anymore. I'm closing this while creating new ones for each test.
