### ISSUE TITLE
XUnit classes included code coverage

### ISSUE THREAD

**Issue by JonHanna** [dotnet/corefx#7744]
See for example http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/code_coverage_windows_local/Code_Coverage_Report/xunit.execution.dotnet_ReflectionAbstractionExtensions.htm which summarises `ReflectionAbstractionExtensions` in xunit.execution.desktop and attempts to give more detail, but fails due to the source file not being available.

**Comment by stephentoub** [comment]
Thanks. Dup of https://github.com/dotnet/buildtools/issues/637
