### ISSUE TITLE
Static link libvcruntime.lib to eliminate dependency on VCRuntime140.dll

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/corefx#7748]
CC @weshaggard @ericstj

**Comment by ianhays** [comment]
I think I've got an abandoned PR up somewhere with this already done. I created it with the intent of making our internal build use CMake but gave up on it after learning we were going to abandon that shortly anyways.

iirc passing link arguments/libraries to cmake is relatively simple, though in the previous case I was also manually specifying the compiler and linker being used. I'm not sure if that will be a problem.
