### ISSUE TITLE
Remove System.Runtime.InteropServices.PInvoke contract

### ISSUE THREAD

**Issue by yizhang82** [dotnet/corefx#7754]
We should remove S.R.InteropServices.PInvoke contract since it is no longer aligned with our direction for .NET Core APIs.

**Comment by ericstj** [comment]
@botaberg is working on this now.  We're changing the way the reference and facades are built for these so that we can OOB them back to NETStandard1.1.

**Comment by botaberg** [comment]
System.Runtime.InteropServices.PInvoke contract removed as of #8626.
