### ISSUE TITLE
TimeZoneInfo should expose FromSerializedString and ToSerializedString

### ISSUE THREAD

**Issue by mjrousos** [dotnet/corefx#7757]
`TimeZoneInfo` cannot be serialized with the data contract serializer (which is a recommended serialization API for .NET Core) - serializing it results in an `InvalidDataContractException`.

An easy workaround would be to use `ToSerializedString` and `FromSerializedString` to convert the TimeZoneInfo into a string, but those APIs are also not available in .NET Core.

This combination makes attempting to serialize a type containing a `TimeZoneInfo` a poor experience (the user needs to add a lot of `[KnownType]` attributes as per [this guidance](https://social.msdn.microsoft.com/Forums/en-US/f164f185-ae18-4775-a2ff-a814813d262d/unable-to-serialze-member-of-type-timezoneinfo?forum=wcf)) which results in messy code.

**Comment by tarekgh** [comment]
just wondering, from the TZI you can get the TZ ID. in .Net Core we don't have any customized TZ so serialization will only need the TZI ID.

**Comment by mjrousos** [comment]
That could work. I didn't realize we didn't have customized timezones. Do you think using the ID for serialization would work cross-platform (serialize on Windows, de-serialize on Linux or vice-versa)?

**Comment by tarekgh** [comment]
No serialization cross platforms will not work because the IDs on Windows is different than the IDs on Linux/OSX. we have a tracked future work to introduce a provider concept to TZI so we can handle IANA (and Linux) IDs on Windows and handle Windows IDs on Linux.

**Comment by tarekgh** [comment]
@mjrousos do you still want to keep this issue open? or we can close it?

**Comment by mjrousos** [comment]
We can close it for now, I guess since ID works. 

As far as cross-plat serialization goes, though, would storing the TZI offset work better for that? If I remembered that on Windows I serialized something that was UTC -5 and then found a TZ on Linux when deserializing that matched that would that work? Or is there more data (daylight saving time??) that would be needed?

**Comment by tarekgh** [comment]
> As far as cross-plat serialization goes, though, would storing the TZI offset work better for that? If I remembered that on Windows I serialized something that was UTC -5 and then found a TZ on Linux when deserializing that matched, would that work? Or is there more data (daylight saving time??) that would be needed?

I think this will not work perfectly because you may end up using a TZ which has daylight saving rules different than the original one. either you need to wait the work to be done for supporting the providers or you will need to do your own mapping of the Windows Ids to IANA IDs and vice versa. this is not straight forward but it is possible. anyway the interop across platform for TZ is not supported yet so I think you can live with that till we support it.
