### ISSUE TITLE
XmlSerializer internal cache could have issue with concurrent reading and writing operations

### ISSUE THREAD

**Issue by khdang** [dotnet/corefx#7778]
https://github.com/dotnet/corefx/pull/7765#discussion_r59859405

**Comment by shmao** [comment]
I reviewed the use of the [Dictionary](https://github.com/khdang/corefx/blob/e477b9cd98a4855cf5820dc3bf9483e321aa25e1/src/System.Xml.XmlSerializer/src/System/Xml/Serialization/Compilation.cs#L306) in question. It doesn't seem like we would have issue with concurrent reading and writing. Although we have lock on write operation only, we make a clone of the dictionary every time we add an element. The code may not be efficient, but it should be thread-safe. I'm closing the issue as no action is required at this point.

/cc: @khdang @SGuyGe @zhenlan
