### ISSUE TITLE
Localized resources from net46 dependency are not working

### ISSUE THREAD

**Issue by joplaal** [dotnet/corefx#7783]
When a .net "legacy" library is referenced from an application targeting net46, the localized resources are not working properly, and neutral culture resources are being used.

Steps to reproduce: https://gist.github.com/joplaal/5e7399d126f2bd79336a65569932fbd1

(A console app using FluentValidator, that has resources in spanish)

Targeting dnx46, with dnx run, works properly. But targeting net46 and using dotnet run, it doesn't.

**Comment by ramarag** [comment]
This is a CLI issue, the CLI is not placing the resources of all the locales from the FluentValidation nuget package into the execution directory. Thus ResourceManager defaults to the default locale embedded with in FluentValidation.dll 

@schellap  can you link the appropriate tracking bug from dotnet/cli and close this issue ?

**Comment by ramarag** [comment]
closing it here and tracking in dotnet/cli https://github.com/dotnet/cli/issues/2983
