### ISSUE TITLE
[perf] System.Data.SqlClient allocates lots of closures with ContinueWith

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#7787]
Ran this grep query:

``` bash
grep --include='*.cs' --exclude-dir=tests --exclude-dir=ref -r 'ContinueWith[^(]*(([^,]*)' .
```

It printed out the following results: https://gist.github.com/anonymous/7afb47c97f2f632c7ddf963111ad3136

The closure in `WinHttpHandler` is fixed by #7785, but there appear to be a bunch of them in `System.Data.SqlClient` that could be removed. Opening up a tracking issue to remove them (which I'll do myself).

---

**edit:** Just realized I wasn't picking up on some of them, because most are written in the form:

``` cs
task.ContinueWith(t => ...)
```

rather than

``` cs
task.ContinueWith((t) => ...)
```

so I ran a new query, which seems to pick up more matches. See: https://gist.github.com/anonymous/14aa1dea4fe3a26e42e338c5b30b09b4

**Comment by jamesqo** [comment]
Related: as **justinvp** pointed out [here](https://github.com/dotnet/corefx/pull/7788#issuecomment-210750555), it's also possible to use subclassing in some cases (e.g. `TaskCompletionSource<T>`) to avoid tuple allocations. Here's a list of all the places that could use this optimization: https://gist.github.com/jamesqo/5c24959b7c15a154831901166ae32fbe

**Comment by jamesqo** [comment]
@joshfree Could you add a 'grabbed by community' tag to this issue? The associated PR for this (#7789) was recently closed, but I'm still working on it locally.

**Comment by karelz** [comment]
@jamesqo are still working on the issue? (I don't think so, so changing the labels ... I'll be happy to revert it back if I am wrong)

**Comment by Wraith2** [comment]
@karelz I think this can be closed now after https://github.com/dotnet/corefx/pull/34134 was merged everything that I can prevent allocating closures does.

**Comment by Wraith2** [comment]
No problem, they're all alerted now so that's fine. 😁
