### ISSUE TITLE
[xml] Code duplication of some XML decoder types

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#7793]
The following types look like they have 2-3 different files, one in `Common` and one in the `System.Xml` assemblies.

- `Base64Decoder` and `Base64Encoder`: present in both `Common` and `ReaderWriter`
- `BinHexDecoder` and `BinHexEncoder`: present in `Common`, `ReaderWriter`, and `XmlSerializer`
- `IncrementalReadDecoder`: present in both `Common` and `ReaderWriter`

cc @khdang @zhenlan

**Comment by sepidehMS** [comment]
Done by https://github.com/dotnet/xml/pull/63 and merged into master. Closing.
