### ISSUE TITLE
[API Proposal] Task.Default<T> for returning a cached Task with a result of default(T)

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#7798]
Basically as the title says. It's a common scenario to want to return a cached `Task<T>` if there's no async work that needs to be done in a method; .NET 4.6 offers `Task.CompletedTask` which helps with this, but for methods that actually return a result through the task there is no such alternative.

Examples of where this would be useful:

- `Stream.ReadAsync`: Classes that override `ReadAsync` can return `Task.Default<int>()` instead of `Task.FromResult(0)` when there's no more work to do.

- For any method returning `Task<T>` where T is a reference type, if the return value is null then they can use `Task.Default<T>()`.

- Any method returning `Task.FromResult(false)` can use `Task.Default<bool>()` instead, which is likely a common scenario since there's only two boolean values.

## Proposed API

```cs
namespace System.Threading.Tasks
{
    public class Task : IAsyncResult
    {
        public static Task<TResult> Default<TResult>();
    }

    public class Task<TResult> : Task
    {
        public static Task<TResult> Default { get; }
    }
}
```

**Comment by svick** [comment]
Wouldn't it be better to modify `Task.FromResult()` to cache common results?

**Comment by jamesqo** [comment]
@svick That might hurt performance in the case where a result of `default(T)` isn't common, e.g. calling it on the result of a method that's supposed to never return null. It should be up the developer to explicitly spell out when he/she wants to return a cached task with a certain result.

**Comment by alexperovich** [comment]
The possible performance gains from this API addition don't outweigh the cost of maintaining a new API. The case where the default value is returned from a function is the exception, not the rule. If a specific application has performance issues that caching tasks can solve then it is easy to make a cache.

**Comment by jamesqo** [comment]
@alexperovich Yep. Also it looks like this API has been supplanted by `ValueTask<T>` for the most part, except for existing methods that need to return a Task.
