### ISSUE TITLE
Unused PLATFORM_UNIX defines in CoreFX

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#7799]
`PLATFORM_UNIX` is defined in CoreCLR, however there are still 2 files where it is still being used (one of them being `TextWriter`): https://github.com/dotnet/corefx/search?utf8=%E2%9C%93&q=PLATFORM_UNIX

**Comment by steveharter** [comment]
I assume the description should be "PLATFORM_UNIX is *not* defined in *CoreFX*..."

Is the intent of the issue to add the define, or remove the uses of? It appears from looking at the TextWriter case, that PLATFORM_UNIX should be defined to get unix behavior or what the linefeed characters should be.

CoreCLR does define PLATFORM_UNIX in the clr.defines.targets file at the root of the enlistment.
