### ISSUE TITLE
Immutable collections test failure in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#780]
An immutable collections test failed in a CI run:

```
System.Collections.Immutable -> d:\j\workspace\dotnet_corefx_windows_debug_prtest\bin\Windows_NT\Debug\System.Collections.Immutable\System.Collections.Immutable.dll
  System.Collections.Immutable.Tests -> d:\j\workspace\dotnet_corefx_windows_debug_prtest\bin\Windows_NT\Debug\System.Collections.Immutable.Tests\System.Collections.Immutable.Tests.dll
  xUnit.net console test runner (32-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.
  
  Discovering: System.Collections.Immutable.Tests
  Discovered:  System.Collections.Immutable.Tests
  Starting:    System.Collections.Immutable.Tests
     System.Collections.Immutable.Test.ImmutableSortedSetTest.EmptyTest [FAIL]
        Assert.Same() Failure
        Expected: ImmutableSortedSet<Int32> []
        Actual:   ImmutableSortedSet<Int32> []
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Collections.Immutable\tests\ImmutableSortedSetTest.cs(354,0): at System.Collections.Immutable.Test.ImmutableSortedSetTest.EmptyTestHelper[T](IImmutableSet`1 emptySet, T value, IComparer`1 comparer)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Collections.Immutable\tests\ImmutableSortedSetTest.cs(82,0): at System.Collections.Immutable.Test.ImmutableSortedSetTest.EmptyTest()
  Finished:    System.Collections.Immutable.Tests
  
  === TEST EXECUTION SUMMARY ===
     System.Collections.Immutable.Tests  Total: 591, Errors: 0, Failed: 1, Skipped: 0, Time: 1.839s
```

**Comment by stephentoub** [comment]
@AArnott, my theory here is that this is due to a very subtle and rare race.  If two immutable collections tests ran concurrently, it's possible they could both access ```Comparer<T>.Default``` for the first time concurrently.  ```Comparer<T>.Default``` doesn't guarantee it'll return the same object every time... it usually does, as it caches a result in a static, but it doesn't use any synchronization when doing that, so it's possible two concurrent calls could get two different objects.  If test 1 was the immutable sorted set test and constructed the object used for ```ImmutableSortedSet<T>.Empty``` using a ```Comparer<T>``` that loses the race and isn't actually stored into the static, then when a subsequent test verifies that ```ImmutableSortedSet<T>.Empty.WithComparer(null)``` is the same object, it won't be, because the ```Comparer<T>.Default``` that's retrieved in place of the null comparer will be a different object than the one that's stored in ```ImmutableSortedSet<T>.Empty```, and thus ```WithComparer``` will manufacture a new ```ImmutableSortedSet<T>``` instance.

**Comment by AArnott** [comment]
Thanks, @stephentoub. 
I guess it would be *very* unfortunate for an immutable collection's Empty instance to accidentally capture an unusual instance of `Comparer<T>.Default` as that would mean this would happen for the whole life of the process, causing more allocations than designed for.
Perhaps the library should defend by calling `Comparer<T>.Default` _twice_ and always using the result of the second call. Do you know any better way?

**Comment by stephentoub** [comment]
If it's something important to defend against, you could maintain your own:
```
private static readonly Comparer<T> s_defaultComparer = Comparer<T>.Default;
```
and then the library would use that s_defaultComparer everywhere instead of using Comparer<T>.Default.  This wouldn't defend against external code passing in Comparer<T>.Default (which could possibly differ from s_defaultComparer), but it would ensure that every internal code path consuming s_defaultComparer would get the same instance.

**Comment by AArnott** [comment]
I was more concerned about external code passing one in. I'm thinking about modifying the constructor from this:

    _comparer = comparer ?? Comparer<T>.Default;

to this:

    if (comparer != null)
    {
        _comparer = comparer;
    }
    else
    {
        var dummy = Comparer<T>.Default; // ensure we get the right singleton on the second call.
        _comparer = Comparer<T>.Default;
    }

**Comment by stephentoub** [comment]
I don't understand how this defends against external code calling WithComparer(Comparer<T>.Default).  Can you elaborate?

**Comment by AArnott** [comment]
By the time they call WithComparer, they already have an instance of the collection. And that instance is based on Empty. And the Empty constructor has already run and called Comparer.Default. Therefore there is no race.

In fact we could instead move this double-call into the Empty initializer's constructor call so that we only do the double-call for Empty and not any other instance.

**Comment by stephentoub** [comment]
Ah, I see.  This wouldn't be 100%, but it would address the common case.  It wouldn't, for example, address the corner case where the user themselves cached ```Comparer<T>.Default``` concurrently with ```Empty``` being initialized rather than accessing Default as part of the call to ```WithComparer```.

I think doing it instead as part of Empty's construction would address it, since the field that backs ```Comparer<T>.Default``` is volatile, though I need to mull it over a bit more.

**Comment by AArnott** [comment]
Right. I don't think we can deal with the case of the caller using a cached odd instance. I'll start a pull request so you can review what I'm thinking. I'm nearly done with it.

**Comment by stephentoub** [comment]
Actually, no, that still wouldn't address the issue, at least not with how ```Default``` is currently implemented.  It's logic is basically:
```
Comparer<T> default = s_default;
if (default == null)
{
    default = CreateComparer<T>();
    s_default = default;
}
return default;
```
So if thread 1 calls:
```
var dummy = Comparer<T>.Default;
return Comparer<T>.Default;
```
concurrently with thread 2 doing:
```
return Comparer<T>.Default;
```
thread 2 could get to the point of being inside of the null check, then thread 1 could execute, and then thread 2 would continue to create its own copy and overwrite what's in s_default.   Subsequent calls to Comparer<T>.Default would return the value created by thread 2, not the one accessed by thread 1.

**Comment by stephentoub** [comment]
Actually, no, that still wouldn't address the issue, at least not with how ```Default``` is currently implemented.  It's logic is basically:
```
Comparer<T> default = s_default;
if (default == null)
{
    default = CreateComparer<T>();
    s_default = default;
}
return default;
```
So if thread 1 calls:
```
var dummy = Comparer<T>.Default;
return Comparer<T>.Default;
```
concurrently with thread 2 doing:
```
return Comparer<T>.Default;
```
thread 2 could get to the point of being inside of the null check, then thread 1 could execute, and then thread 2 would continue to create its own copy and overwrite what's in s_default.   Subsequent calls to Comparer<T>.Default would return the value created by thread 2, not the one accessed by thread 1.

**Comment by AArnott** [comment]
Hmmm... I see. Too bad there's no `Interlocked.CompareExchange` there. Surely that wasn't due to a perf concern with an interlocked call as this is just in lazy init.

**Comment by stephentoub** [comment]
I didn't write that code, so I can't speak to the reasoning, but there are lots of places where a CompareExchange isn't used in places where object identity isn't expected to be needed.  For example, a CompareExchange isn't used when the C# compiler caches delegate instances.

**Comment by AArnott** [comment]
The pull request might be a step toward the solution. But perhaps the solution is to switch to using interlocked in the Comparer initializer then. Assuming that's in corefx we could fix it here, and then file a bug against .NET 4.6 too.

**Comment by stephentoub** [comment]
I think it'd be a reasonable change to ```Comparer<T>.Default``` and ```EqualityComparer<T>.Default```.  Since this is about performance rather than correctness, it'd be ok for the fix not to show up everywhere, especially since the negative perf consequences would only likely happen once in a blue moon.

**Comment by AArnott** [comment]
OK. I'll see if I can find the Comparer implementation in Corefx and update the pull request.
Do you think the existing pull request commit is not worth keeping any form of at this point? If it doesn't really solve the problem, IMO it's not worth the complexity.

**Comment by stephentoub** [comment]
I believe the source is in the System.Collections library, for which tests but not yet source are up on GitHub.  Hopefully it'll be up soon.

And, yeah, IMHO the PR isn't worth it.

**Comment by AArnott** [comment]
Sounds good. I'll cancel it. And I noticed the src for the lib is missing too. I'll hold off on fixing this till it's available.

**Comment by weshaggard** [comment]
This test is still failing in random test runs. see http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/509/console as an example of a recent one. We should see if there is something that we can do within the test to avoid this identity comparison perhaps.
