### ISSUE TITLE
LoadInDefaultContext failed in CI with permissions error

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7805]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu15.10_release_tst/15/console
```
04:16:23    System.Runtime.Loader.Tests.DefaultLoadContextTests.LoadInDefaultContext [FAIL]
04:16:23       System.UnauthorizedAccessException : Access to the path '/tmp/System.Runtime.Loader.Noop.Assembly.dll' is denied.
04:16:23       ---- System.IO.IOException : Operation not permitted
04:16:23       Stack Trace:
04:16:23 Starting:    System.Runtime.Loader.Tests
04:16:23             at System.IO.UnixFileSystem.DeleteFile(String fullPath)
04:16:23             at System.Runtime.Loader.Tests.DefaultLoadContextTests.Init()
04:16:23             at System.Runtime.Loader.Tests.DefaultLoadContextTests.LoadInDefaultContext()
```

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu15.10_debug_tst/17/console

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu15.10_debug_tst/22/console

This seems to be happening regularly on at least the Ubuntu 15.10 runs.

**Comment by mellinoe** [comment]
Occurred here in a CentOS run:

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_debug_tst_prtest/323/testReport/junit/System.Runtime.Loader.Tests/DefaultLoadContextTests/LoadInDefaultContext/

**Comment by mellinoe** [comment]
Hm, this just happened again in my PR on CentOS, and seems to be happening pretty regularly in the other runs:

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_debug_tst_prtest/335/console
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_debug_tst_prtest/337/console

**Comment by stephentoub** [comment]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_release_prtest/478/consoleText

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_debug_tst_prtest/608/consoleText

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_release_tst_prtest/636/consoleText

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_debug_tst_prtest/638/

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_release_tst_prtest/643/consoleText
