### ISSUE TITLE
TestProcessStartTime failing on certain machines in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7818]
This just started acting up again.  I've seen it fail several times today.
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_tst_prtest/68/console
```
14:50:03    System.Diagnostics.Tests.ProcessTests.TestProcessStartTime [FAIL]
14:50:03       Assert+WrapperXunitException : File path: D:\j\workspace\osx_debug_bld---9c844ccb\src\System.Diagnostics.Process\tests\ProcessTests.cs. Line: 411
14:50:03       ---- Assert.InRange() Failure
14:50:03       Range:  (4/17/16 9:56:53 PM - 4/17/16 9:56:59 PM)
14:50:03       Actual: 6/6/16 2:59:43 PM
14:50:03       Stack Trace:
14:50:03             at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber)
14:50:03             at Assert.InRange[T](T actual, T low, T high, String path, Int32 line)
14:50:03             at System.Diagnostics.Tests.ProcessTests.TestProcessStartTime()
14:50:03          ----- Inner Stack Trace -----
14:50:03             at Assert.InRange[T](T actual, T low, T high, String path, Int32 line)
```

**Comment by stephentoub** [comment]
@Priya91, I think this is a product bug.  The implementation uses Environment.TickCount to determine boot time in order to calculate process start time, but TickCount can overflow, will do so after ~24.8 days, and the machine on which this is failing has been has now been up for 25 days, which explains why when tests run on that machine today, they're failing.

**Comment by Priya91** [comment]
:dancer: happy to see the process times get fixed!
