### ISSUE TITLE
[Help] How to get current assembly name?

### ISSUE THREAD

**Issue by Kagamine** [dotnet/corefx#7821]

**Comment by mellinoe** [comment]
The question is a bit ambiguous, but I'm assuming you are asking about `Assembly.GetExecutingAssembly`. We don't support it in the new .NET Core surface area, so you will need to look at different approaches to solving your problem. If you give some more information, we could try to point you in the right direction for some workarounds and/or alternate designs. In general, stack-crawling and stack-inspection functionality is not present in .NET Core.

**Comment by mellinoe** [comment]
@Kagamine Did the above answer your question, or was it about something else?

**Comment by Kagamine** [comment]
I saw the asp.net team made a package which named IAssemblyLoader, Is there any document to introduce how to use that? I am making a nuget package and I just want to know who called my package, and load the caller assembly, execute the caller classes and functions dynamicly.

**Comment by mellinoe** [comment]
> I saw the asp.net team made a package which named IAssemblyLoader, Is there any document to introduce how to use that?

I'm not familiar with the component. The folks over at https://github.com/aspnet/Home may know more specifics about it.

> I am making a nuget package and I just want to know who called my package, and load the caller assembly, execute the caller classes and functions dynamicly.

We do expose `Environment.StackTrace`, which will give you some sort of "caller history". But keep in mind that this is dependent on things like JIT inlining, which aren't predictable. It's not a great idea to use it for a scenario like you are mentioning.

Is this for some sort of "plugin" system? Could you just have the caller pass in their assembly, or have them pass in some other type of registration object that your library could understand? That would be a more stable contract between the two than relying on a stack trace.

**Comment by Kagamine** [comment]
The things which I want to do is similar to ASP.Net Core MVC controllers detector. I have to detect the specific classes, and get all of the methods in the class by using reflection. So I think I have to find the assembly which called my package.

**Comment by mellinoe** [comment]
Have you considered what I suggested about having the caller pass in the necessary information? Unfortunately, I'm not familiar with how the ASP.NET component works, so I can't really speak to what they are doing there.
