### ISSUE TITLE
Kerberos to ntlm fallback is not happening with the ntlmssp plugin when passed valid ntlm creds.

### ISSUE THREAD

**Issue by shrutigarg** [dotnet/corefx#7825]
There is a bug in ntlmssp package .If we try spnego with valid ntlm creds, it first tries Kerberos and since the creds are not present in Kerberos database it should fallback to ntlm. Which is not happening in the current verison. 
The issue is discussed with ntlmssp plugin developer (simo sorce) .He will look into this.

**Comment by shrutigarg** [comment]
Assigned to @rahulkotecha to follow up on the fix for this issue,

**Comment by joshfree** [comment]
Moving to 1.1.  We can reconsider for 1.0 if a fix is available in time.
