### ISSUE TITLE
Culture is not preserved after EF 6 async operation, targeting net46

### ISSUE THREAD

**Issue by joplaal** [dotnet/corefx#7827]
After an async operation in EntityFramework 6.1.3, as AnyAsync(), or ToListAsync(), Thread.CurrentThread.CurrentCulture is not preserved.

Steps to reproduce: https://gist.github.com/joplaal/d9462f25baca8b3083d0c62b0d050e3c

It did not happen in a similar setup targeting dnx46.

Since EFCore is not yet mature for certain scenarios, it's important that we could get a EntityFramework 6 setup fully working.

**Comment by stephentoub** [comment]
What build are you using?  I'd have expected this to be fixed with https://github.com/dotnet/coreclr/pull/4119.

**Comment by joplaal** [comment]
I'm using dotnet restore from https://www.myget.org/F/aspnetcidev/, so latest ones.  (.net46 -  windows). You can see the details at the gist dotnet-run-tests.bat file

**Comment by stephentoub** [comment]
Oh, wait, this is when targeting .NET 4.6?  That shouldn't depend on the fix I mentioned.

**Comment by joplaal** [comment]
Yes, I can reproduce this bug targeting net46

**Comment by tarekgh** [comment]
I'll take a look. I have suspect that the run is not really targeting 4.6 and maybe it is running as 4.5.x

**Comment by tarekgh** [comment]
I am seeing xunit.console.exe has 

[assembly: TargetFramework(".NETFramework,Version=v4.5", FrameworkDisplayName = ".NET Framework 4.5")]

so it is running as 4.5 and not 4.6. 

something you may try to workaround this is calling 

```
AppContext.SetSwitch(@"Switch.System.Globalization.NoAsyncCurrentCulture", false);

```

I'll try to look if there is any way to force the xunit.console.exe to target different version of the framework

**Comment by joplaal** [comment]
Ok, understood. That issue will not happen on production code, which was our main concern,

We are using xunit.console.exe only until dotnet test runner targets net46, (https://github.com/dotnet/cli/issues/2380)

**Comment by tarekgh** [comment]
meanwhile you can use the workaround I mentioned in your tests 

```
AppContext.SetSwitch(@"Switch.System.Globalization.NoAsyncCurrentCulture", false);
```

or you can also work around it by creating xunit.console.exe.config file with the following contents 

``` Xml
<?xml version ="1.0"?>
<configuration>
  <runtime>
   <AppContextSwitchOverrides value="Switch.System.Globalization.NoAsyncCurrentCulture=false" /> 
  </runtime> 
</configuration>
```

I am closing this issue but feel free to reply or reopen if you have any follow up questions.
