### ISSUE TITLE
Receive bytes on accepted socket if requested

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#7836]
See TODO here: https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/AcceptOverlappedAsyncResult.Unix.cs#L31

and here: https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Unix.cs#L55

**Comment by ericeil** [comment]
#7941 addresses the most immediate concern, which is that this code behaves incorrectly if passed a receive buffer.  We should consider implementing this on Unix, but maybe that can wait until after RTM.

**Comment by ericeil** [comment]
Emulating the exact Windows behavior on Unix may be difficult.  The particulars of this feature on Windows are pretty specific to the behavior of the underlying AcceptEx API.  From [the MSDN docs](https://msdn.microsoft.com/en-us/library/system.net.sockets.socket.acceptasync(v=vs.110).aspx):

> Part of the buffer passed in will be consumed internally for use by the the underlying Winsock AcceptEx call. This means that the amount of data returned will always be less than the value of the SocketAsyncEventArgs.Count property on the System.Net.Sockets.SocketAsyncEventArgs instance provided. The amount of the buffer used internally varies based on the address family of the socket. The minimum buffer size required is 288 bytes. If a larger buffer size is specified, then the Socket will expect some extra data other than the address data received by the Winsock AcceptEx call and will wait until this extra data is received. If a timeout occurs, the connection is reset. So if extra data is expected of a specific amount, then the buffer size should be set to the minimum buffer size plus this amount.
 
I'm not sure it's even *possible* to exactly replicate the "connection is reset" part of this, and the rest of the behavior feels hard to replicate enough to make all existing users happy.  This feels to me like it *might* be best to leave this as a Windows-only feature of `AcceptAsync`, and possibly add a new method that offers similar performance benefits but behaves reasonably on all platforms.

OTOH, we may be able to make this "good enough" without introducing a new API.

**Comment by davidsh** [comment]
We believe this difference has been gracefully handled on *Nix.  We will re-visit this issue again if it is impacting customers.
