### ISSUE TITLE
Add logging to calls to WinHttp based code

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#7856]
Tracking EventSource logging for all WinHttp code. This applies to both WinHttpHandler as well as the WinHttp WebSockets implementation.

One example from Interop.SafeWinHttpHandle.cs:

```
                // TODO(Issue 2500): Add logging so we know when the handle gets closed.
                return Interop.WinHttp.WinHttpCloseHandle(handle);
```
#2500 was already closed; this issue will cover the specific potential log usage.

**Comment by CIPop** [comment]
Thanks @ericeil for noticing this!
Re-purposed this issue to track adding logging to all WinHttp new code.

**Comment by davidsh** [comment]
We need to convert the existing "OutputDebugString" low-level tracing in WinHttpHandler and make that align with the other EventSource based tracing we use. We also need to update the documentation as well.
