### ISSUE TITLE
Console.WindowWidth fails with IOException

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/corefx#7858]
Try the following:

Program.cs:
``` csharp
using System;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine($"Width: {Console.WindowWidth}");
        }
    }
}
```

project.json:

```json
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002424"
    }
  },
  "frameworks": {
    "netcoreapp1.0": {}
  }
}
```

The fails with the following exception:

```
Unhandled Exception: System.IO.IOException: The handle is invalid
   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.ConsolePal.get_WindowWidth()
   at System.Console.get_WindowWidth()
   at ConsoleApplication.Program.Main(String[] args)
```

**Comment by mellinoe** [comment]
Hm, I'm not able to reproduce this one either, using version `4.0.0-rc3-24015-00`. I'm assuming this is also a CLI program; is Console output redirected?

**Comment by twsouthwick** [comment]
I just ran `dotnet run` from the commandline - I don't think there's any redirection, unless the CLI runner does some of that.

**Comment by stephentoub** [comment]
> I don't think there's any redirection, unless the CLI runner does some of that.

It does.

**Comment by twsouthwick** [comment]
If it's due to the CLI redirection of stdout, should I open an issue there instead?

**Comment by stephentoub** [comment]
> If it's due to the CLI redirection of stdout, should I open an issue there instead?

There's little we can do about this from a System.Console perspective: we're trying to get the screen buffer from the OS, and it's failing:
https://github.com/dotnet/corefx/blob/master/src/System.Console/src/System/ConsolePal.Windows.cs#L1097

I believe "dotnet run" is just shelling out to "dotnet-run", so that would likely need to change in order to address this.  But, yeah, following up in the CLI repo is probably the best option.

**Comment by ianhays** [comment]
@twsouthwick did you have a chance to open an issue in the CLI repo for this?

**Comment by joshfree** [comment]
Moved to https://github.com/dotnet/cli/issues/2780

**Comment by eiriktsarpalis** [comment]
FWIW I'm getting this exception on windows nanoserver containers.
