### ISSUE TITLE
Empty Console.WriteLine call does not write blank line

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/corefx#7859]
`Console.WriteLine()` should output an empty line:

```csharp
using System;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
			Console.WriteLine("Should have empty line below");
			Console.WriteLine();
			Console.WriteLine("Should have empty line above");
        }
    }
}
```

**Expected**
```
Should have empty line below

Should have empty line above
```

**Observed (1.0.0-rc2-3002424)**
```
Should have empty line below
Should have empty line above
```

**Comment by akoeplinger** [comment]
Are you using dotnet run? this sounds like https://github.com/dotnet/cli/issues/2234

**Comment by mellinoe** [comment]
Yes, this is most likely a CLI issue. This does not repro for me in a regular program.

>1.0.0-rc2-3002424

Not sure which version this is. I tested version `4.0.0-rc3-24015-00`.

**Comment by twsouthwick** [comment]
Yup - that looks like the issue. Didn't think to look at those issues.
