### ISSUE TITLE
CoreFX types are not browsable in Visual Studio 2015 Update 2

### ISSUE THREAD

**Issue by richlander** [dotnet/corefx#7860]
Repro steps:

- Create netstandard PCL
- Build
- Double click on NETStandard.Library

---------------------------
Microsoft Visual Studio
---------------------------
This project cannot be viewed in the object browser because it is unavailable or not yet built. Please ensure that the project is available and built.
---------------------------
OK   
---------------------------

**Comment by davidfowl** [comment]
That's not a corefx bug, it's a project system issue.

/cc @jasonmalinowski @Pilchie

**Comment by mellinoe** [comment]
Yeah, this actually happens with any/every NuGet package.

**Comment by jasonmalinowski** [comment]
Going to dupe this one against dotnet/roslyn#10685 since that's a repository that we'll see better.

**Comment by mellinoe** [comment]
Thanks @jasonmalinowski , I'll close this one and we can track it there.
