### ISSUE TITLE
IEnumerable<DateTime> Select with formatting does not work (anymore)

### ISSUE THREAD

**Issue by rmja** [dotnet/corefx#7861]
Running on the latest bits in the `aspnetcirelease` feed.

Steps to reproduce:
```
var times = new List<DateTime>() { DateTime.Now };
string.Join(",", times.Select(x => x.ToString("yyyy")))
```

Expected result: `2016`
http://csharppad.com/gist/f08e21c1f701482902517b23e4117abc

Actual result: `19-04-2016 09:45:29`

**Comment by rmja** [comment]
Note that the following works:

```
var times = new List<DateTime>() { DateTime.Now };
times.First().ToString("yyyy")
```

**Comment by mellinoe** [comment]
I'm not able to reproduce this, `2016` is returned as expected. Could you give more information about your setup and how you are reproducing this? Could you list the versions of System.Linq.dll and mscorlib.dll that you are using, and preferably the Nuget package version they came from? Also, i'm not sure what packages get put on the `aspnetcirelease` feed, but you will have better luck using the "dotnet-core" feed on dotnet.myget.org: [gallery](https://dotnet.myget.org/gallery/dotnet-core), [feed](https://dotnet.myget.org/F/dotnet-core/api/v3/index.json). That is where the latest builds from this repro and from coreclr go to.

**Comment by rmja** [comment]
@mellinoe so it seems that the problem does not exist in the actual run code, but in the Immediate Window:

![image](https://cloud.githubusercontent.com/assets/2112306/14632327/523034fc-0618-11e6-8f23-4f542c2b1050.png)

The variable `s` is resolved correctly, where the result in the immediate window is not. I was prototyping in that window while investigating the behavior.

**Comment by jasonwilliams200OK** [comment]
It seems like in interactive mode, the correct `DateTime.ToString(string format)` overload is not being in `Select` predicate (instead `DateTime.ToString()` gets called). 
This seems to be related to https://github.com/dotnet/roslyn/issues/5119 (note the `Interactive-*` issue labels in Roslyn repo).
cc @gafter, @cston

**Comment by karelz** [comment]
@gafter should we move the issue to Roslyn repo?

**Comment by cston** [comment]
@karelz, yes this looks like an EE bug. Please feel free to move to dotnet/roslyn.

**Comment by karelz** [comment]
Moved to dotnet/roslyn#13714
