### ISSUE TITLE
Convert System.Runtime.InteropServices.RuntimeInformation to a fat package

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#7863]
This enables us to package it such that it works on desktop without a lineup.  Desktop shouldn't need a lineup and this is one package that was causing it to be required.  Let's double check all packages as part of this work to ensure they don't need a lineup for desktop.

**Comment by ericstj** [comment]
Another thing I'm noticing while looking at this is some packages have a specific desktop asset and RID specific assets but don't always put the desktop asset in the RID folder.  As a result we could get different implementation (wrong) when resolving for desktop and providing a rid like "win7" or "win8".  I think we should try and make all the desktop assets behave the same.

If the package is fat, duplicate the desktop asset in the RID and RID-less folder.

**Comment by davidfowl** [comment]
/cc @emgarten 

This is interesting because it means you can end up with different nuget selection on `packages.config`

**Comment by ericstj** [comment]
Yeah, that's expected.  I'm making changes to our packages to ensure that any packages that do support project-types that are still on packages.config get the same asset (by copying that asset into lib, so long as it doesn't require RID specific selection on those projects)

**Comment by pranavkm** [comment]
@ericstj - is this not going to be fixed for RTM?

**Comment by ericstj** [comment]
It's already fixed in the RC3 packages.

**Comment by pranavkm** [comment]
Ok. I was confused by the 1.1.0 milestone attached to this work item.

**Comment by ericstj** [comment]
That's odd, it was set to 1.0.0-rtm on 28 days ago, and I don't see anything that changed it to 1.1.0.  I have changed it back.
