### ISSUE TITLE
The type initializer for 'Crypto' threw an exception - Unix

### ISSUE THREAD

**Issue by jacksontbryan** [dotnet/corefx#7870]
When starting my coreclr web application on a docker image, I receive the following exception:
The type initializer for 'Crypto' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.

Full stack trace:
http://textuploader.com/5yccn

I think this is the line throwing the exception:
https://github.com/dotnet/corefx/blob/release/1.0.0-rc1/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.EVP.cs#L50

I have tried both update1 and update2 of coreclr.

I am utilizing the docker image:
microsoft/aspnet:1.0.0-rc1-update1-coreclr

I can find the library here and openssl dev is installed:
root@475b687:/# find -name "libcrypto.so"
./usr/lib/x86_64-linux-gnu/libcrypto.so

My project.json looks like:

"dependencies": {
"Microsoft.AspNet.Authentication.JwtBearer": "1.0.0-rc1-final",
"Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
"Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
"Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
"Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
"Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
"Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
"Microsoft.Extensions.Logging": "1.0.0-rc1-final",
"Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
"Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
"System.IdentityModel.Tokens.Jwt": "5.0.0-rc1-211161024"
},

**Comment by bartonjs** [comment]
@jacksontbryan We've come a long way since RC1.  It'd be great if you could try again with the final release build.

**Comment by bartonjs** [comment]
Since it's been a long time since there was any discussion on this, and there haven't been similar complaints, this is presumed as having been fixed between RC1 and 1.0 RTM.
