### ISSUE TITLE
Behavior difference from NETFX when unknown HttpRequestMessage.Version is used

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#7878]
From HttpHandlerToFilter.cs:

``` csharp
                else
                {
                    // TODO: We need to throw an exception here similar to .NET Desktop
                    // throw new ArgumentException(SR.GetString(SR.net_wrongversion), "value");
                    //
                    // But we need to do that checking in the HttpClientHandler object itself.
                    // and we have that bug as well for the WinHttpHandler version also.
                    maxVersion = RTHttpVersion.Http11;
                }
```

...but maybe this would be a breaking change at this point?

**Comment by davidsh** [comment]
The comment is out of date now. We don't want to throw but instead need to use Version(0,0) which is what we do in non-UWP CoreFx HttpClient.

**Comment by davidsh** [comment]
>The comment is out of date now. We don't want to throw but instead need to use Version(0,0) which is what we do in non-UWP CoreFx HttpClient.

My comment here is incorrect.  This TODO is about handling a request.Version.  My comment (about using Version(0,0) was about handling unknown response.Version.
