### ISSUE TITLE
Add exception message explaining the PlatformNotSupportedException on MaxRequestContentBufferSize

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#7879]
From HttpClientHandler.Windows.cs:

``` csharp
        public long MaxRequestContentBufferSize
        {
            // This property has been deprecated. In the .NET Desktop it was only used when the handler needed to 
            // automatically buffer the request content. That only happened if neither 'Content-Length' nor 
            // 'Transfer-Encoding: chunked' request headers were specified. So, the handler thus needed to buffer
            // in the request content to determine its length and then would choose 'Content-Length' semantics when
            // POST'ing. In CoreCLR and .NETNative, the handler will resolve the ambiguity by always choosing
            // 'Transfer-Encoding: chunked'. The handler will never automatically buffer in the request content.
            get { return 0; }

            // TODO: Add message/link to exception explaining the deprecation. 
            // Update corresponding exception in HttpClientHandler.Unix.cs if/when this is updated.
            set { throw new PlatformNotSupportedException(); }
        }
```

**Comment by danmosemsft** [comment]
@davidsh can you specify a string and I'll do it. I trip over it when going through our PNSE's without reasons.

**Comment by davidsh** [comment]
I can summarize the reason (already in the comments) and give you a string:

"The handler will no longer automatically buffer the request content. Instead 'Transfer-Encoding: chunked' behavior will be used if needed."

But in light of #17691 and making our .NET Core behavior more like .NET Framework, we might re-consider the whole idea that this property is "deprecated" and instead make it work more like .NET Framework.

**Comment by danmosemsft** [comment]
Your call, do you want me to transumte this issue to 'implement it' ?

**Comment by davidsh** [comment]
>Your call, do you want me to transumte this issue to 'implement it' ?

No.  Add the string for now and close out this issue.  If we decide later to change behavior, that will be based on the analysis for #17691.
