### ISSUE TITLE
Refactor similar test into simpler helpers for ParallelFor tests

### ISSUE THREAD

**Issue by AlfredoMS** [dotnet/corefx#790]
There's a lot of repetition in these tests that could easily be refactored into helpers.

see https://github.com/dotnet/corefx/blob/master/src/System.Threading.Tasks.Parallel/tests/ParallelFor.cs

**Comment by Maxwe11** [comment]
>could easily be refactored into helpers.

I see that it could be easily refactored with `Theory` attribute. If yes I can do that.
