### ISSUE TITLE
Building System.Xml.XmlSerializer.Tests against packages fails

### ISSUE THREAD

**Issue by venkat-raman251** [dotnet/corefx#7912]
Building the Tests with /p:BuildTestsAgainstPackages=true throws errors. Currently true has been added to keep the project reference.
We should be able to remove this project reference (just reference the nupkg) and build the test project without errors.  @weshaggard

**Comment by khdang** [comment]
@venkat-raman251 how to repro this issue? I updated in System.Xml.XmlSerializer.Tests.csproj to ``` <KeepProjectReference>false</KeepProjectReference>``` and run ```msbuild System.Xml.XmlSerializer\tests\System.Xml.XmlSerializer.Tests.csproj /t:rebuildandtest /p:BuildTestsAgainstPackages=true``` but there are no errors.

**Comment by khdang** [comment]
I can see this error now when doing a clean build.

After I add the fix, the packages references seem to be right but there are still errors.

Here's packages resolution from project references:
```
GatherProjectReferenceForProjectJson:
  Derived version number from project reference evaluation.
  Converting project reference (System.Private.DataContractSerialization) to package dependency - System.Private.DataContractSerialization: 4.1.1.0
GatherProjectReferenceForProjectJson:
  Derived version number from project reference evaluation.
  Converting project reference (System.Runtime.Serialization.Primitives) to package dependency - System.Runtime.Serialization.Primitives: 4.1.1.0
GatherProjectReferenceForProjectJson:
  Derived version number from project reference evaluation.
  Converting project reference (System.Xml.XmlSerializer) to package dependency - System.Xml.XmlSerializer: 4.0.11.0
AddDependenciesToProjectJson:
  Determined buildnumber using existing package dependencies as 'rc3-24026-00'
  Generated project.json file - 'e:\Open\corefx\bin/obj/generated\System.Xml.XmlSerializer.Tests\AnyOS\project.json'
```

I looked at ```e:\Open\corefx\bin/obj/generated\System.Xml.XmlSerializer.Tests\AnyOS\project.json``` and it has all required contracts but then the CoreCompile doesn't include those contracts.

```
CoreCompile:
  C:\Program Files (x86)\MSBuild\14.0\bin\csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /warn:4 /define:DEBUG;TRACE;DEBUGRESOURCES;SIGNED /reference:e:\Open\corefx\packages/System.Collections\4.0.11-rc3-24022-00\ref\netstandard1.3\Syst
  em.Collections.dll /reference:e:\Open\corefx\packages/System.Diagnostics.Debug\4.0.11-rc3-24022-00\ref\netstandard1.3\System.Diagnostics.Debug.dll /reference:e:\Open\corefx\packages/System.Diagnostics.Tools\4.0.1-rc3-24022-00\ref\nets
  tandard1.0\System.Diagnostics.Tools.dll /reference:e:\Open\corefx\packages/System.Diagnostics.Tracing\4.1.0-rc3-24022-00\ref\netstandard1.5\System.Diagnostics.Tracing.dll /reference:e:\Open\corefx\packages/System.Globalization\4.0.11-
  rc3-24022-00\ref\netstandard1.3\System.Globalization.dll /reference:e:\Open\corefx\packages/System.IO\4.1.0-rc3-24022-00\ref\netstandard1.5\System.IO.dll /reference:e:\Open\corefx\packages/System.IO.FileSystem\4.0.1-rc3-24022-00\ref\n
  etstandard1.3\System.IO.FileSystem.dll /reference:e:\Open\corefx\packages/System.IO.FileSystem.Primitives\4.0.1-rc3-24022-00\ref\netstandard1.3\System.IO.FileSystem.Primitives.dll /reference:e:\Open\corefx\packages/System.Linq\4.1.0-r
  c3-24022-00\ref\netstandard1.5\System.Linq.dll /reference:e:\Open\corefx\packages/System.Linq.Expressions\4.1.0-rc3-24022-00\ref\netstandard1.5\System.Linq.Expressions.dll /reference:e:\Open\corefx\packages/System.ObjectModel\4.0.12-r
  c3-24022-00\ref\netstandard1.3\System.ObjectModel.dll /reference:e:\Open\corefx\packages/System.Reflection\4.1.0-rc3-24022-00\ref\netstandard1.5\System.Reflection.dll /reference:e:\Open\corefx\packages/System.Reflection.Extensions\4.0
  .1-rc3-24022-00\ref\netstandard1.0\System.Reflection.Extensions.dll /reference:e:\Open\corefx\packages/System.Reflection.Primitives\4.0.1-rc3-24022-00\ref\netstandard1.0\System.Reflection.Primitives.dll /reference:e:\Open\corefx\packa
  ges/System.Runtime\4.1.0-rc3-24022-00\ref\netstandard1.5\System.Runtime.dll /reference:e:\Open\corefx\packages/System.Runtime.Extensions\4.1.0-rc3-24022-00\ref\netstandard1.5\System.Runtime.Extensions.dll /reference:e:\Open\corefx\pac
  kages/System.Runtime.Handles\4.0.1-rc3-24022-00\ref\netstandard1.3\System.Runtime.Handles.dll /reference:e:\Open\corefx\packages/System.Runtime.InteropServices\4.1.0-rc3-24022-00\ref\netstandard1.5\System.Runtime.InteropServices.dll /
  reference:e:\Open\corefx\packages/System.Runtime.InteropServices.PInvoke\4.0.0-rc3-24022-00\ref\netstandard1.5\System.Runtime.InteropServices.PInvoke.dll /reference:e:\Open\corefx\packages/System.Runtime.InteropServices.RuntimeInforma
  tion\4.0.0-rc3-24022-00\ref\netstandard1.1\System.Runtime.InteropServices.RuntimeInformation.dll /reference:e:\Open\corefx\packages/System.Text.Encoding\4.0.11-rc3-24022-00\ref\netstandard1.3\System.Text.Encoding.dll /reference:e:\Ope
  n\corefx\packages/System.Text.RegularExpressions\4.1.0-rc3-24022-00\ref\netstandard1.5\System.Text.RegularExpressions.dll /reference:e:\Open\corefx\packages/System.Threading\4.0.11-rc3-24022-00\ref\netstandard1.3\System.Threading.dll
  /reference:e:\Open\corefx\packages/System.Threading.Tasks\4.0.11-rc3-24022-00\ref\netstandard1.3\System.Threading.Tasks.dll /reference:e:\Open\corefx\packages/System.Xml.ReaderWriter\4.0.11-rc3-24022-00\ref\netstandard1.3\System.Xml.R
  eaderWriter.dll /reference:e:\Open\corefx\packages/System.Xml.XDocument\4.0.11-rc3-24022-00\ref\netstandard1.3\System.Xml.XDocument.dll /reference:e:\Open\corefx\packages/System.Xml.XmlDocument\4.0.1-rc3-24022-00\ref\netstandard1.3\Sy
  stem.Xml.XmlDocument.dll /reference:e:\Open\corefx\packages/xunit.abstractions\2.0.0\lib\portable-net45+win+wpa81+wp80+monotouch+monoandroid+Xamarin.iOS\xunit.abstractions.dll /reference:e:\Open\corefx\packages/xunit.assert\2.1.0\lib\
  dotnet\xunit.assert.dll /reference:e:\Open\corefx\packages/xunit.extensibility.core\2.1.0\lib\dotnet\xunit.core.dll /reference:e:\Open\corefx\packages/xunit.extensibility.execution\2.1.0\lib\dotnet\xunit.execution.dotnet.dll /referenc
  e:e:\Open\corefx\packages/xunit.netcore.extensions\1.0.0-prerelease-00312-04\lib\dotnet\Xunit.NetCore.Extensions.dll /reference:e:\Open\corefx\packages/Microsoft.DotNet.xunit.performance\1.0.0-alpha-build0029\lib\dotnet\xunit.performa
  nce.core.dll /reference:e:\Open\corefx\packages/Microsoft.DotNet.xunit.performance\1.0.0-alpha-build0029\lib\dotnet\xunit.performance.execution.dotnet.dll /debug+ /debug:full /delaysign- /keyfile:e:\Open\corefx\Tools/Test.snk /optimiz
  e- /out:e:\Open\corefx\bin/obj/AnyOS.AnyCPU.Debug/System.Xml.XmlSerializer.Tests/System.Xml.XmlSerializer.Tests.dll /ruleset:e:\Open\corefx\Tools\Microsoft.DotNet.CodeAnalysis.ruleset /target:library /warnaserror+ /utf8output /analyze
  r:e:\Open\corefx\Tools/net45/analyzers/Microsoft.DotNet.CodeAnalysis.dll /additionalfile:e:\Open\corefx\bin/obj/AnyOS.AnyCPU.Debug/System.Xml.XmlSerializer.Tests//disabledAnalyzers.config ..\..\System.Runtime.Serialization.Xml\tests\U
  tils.cs ..\..\System.Runtime.Serialization.Xml\tests\SerializationTypes.cs ..\..\System.Runtime.Serialization.Xml\tests\Performance\PerformanceTestsCommon.cs XmlSerializerTests.cs Performance\XsPerformanceTest.cs e:\Open\corefx\bin/ob
  j/AnyOS.AnyCPU.Debug/System.Xml.XmlSerializer.Tests/_AssemblyInfo.cs
```
Any ideas?

**Comment by chcosta** [comment]
It does appear that your project references are missing from the CoreCompile.  @venkat-raman251 , do you have a local repro which produces the same CoreCompile output that @khdang is seeing?  

@khdang , can you provide the contents of your project.json?

**Comment by chcosta** [comment]
I'm not able to repro this locally.  If I delete the entry for "KeepProjectReference" from the System.Xml.XmlSerializer Project Reference or I change the value to false, then I get a compile which includes the project references as packages.

  C:\Program Files (x86)\MSBuild\14.0\bin\csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /warn:4 /define:DEBUG;TRACE;DEBUGRESOURCES;SIGNED /reference:e:\gh\chcosta\corefx\packages/System.Collections\4.0.11-rc3-24026-00\ref\netstandard1.3\System.Collections.dll /reference:e:\gh\chcosta\corefx\packages/System.Diagnostics.Debug\4.0.11-rc3-24026-00\ref\netstandard1.3\System.Diagnostics.Debug.dll /reference:e:\gh\chcosta\corefx\packages/System.Diagnostics.Tools\4.0.1-rc3-24026-00\ref\netstandard1.0\System.Diagnostics.Tools.dll /reference:e:\gh\chcosta\corefx\packages/System.Diagnostics.Tracing\4.1.0-rc3-24026-00\ref\netstandard1.5\System.Diagnostics.Tracing.dll /reference:e:\gh\chcosta\corefx\packages/System.Globalization\4.0.11-rc3-24026-00\ref\netstandard1.3\System.Globalization.dll /reference:e:\gh\chcosta\corefx\packages/System.IO\4.1.0-rc3-24026-00\ref\netstandard1.5\System.IO.dll /reference:e:\gh\chcosta\corefx\packages/System.IO.FileSystem\4.0.1-rc3-24026-00\ref\netstandard1.3\System.IO.FileSystem.dll /reference:e:\gh\chcosta\corefx\packages/System.IO.FileSystem.Primitives\4.0.1-rc3-24026-00\ref\netstandard1.3\System.IO.FileSystem.Primitives.dll /reference:e:\gh\chcosta\corefx\packages/System.Linq\4.1.0-rc3-24026-00\ref\netstandard1.5\System.Linq.dll /reference:e:\gh\chcosta\corefx\packages/System.Linq.Expressions\4.1.0-rc3-24026-00\ref\netstandard1.5\System.Linq.Expressions.dll /reference:e:\gh\chcosta\corefx\packages/System.ObjectModel\4.0.12-rc3-24026-00\ref\netstandard1.3\System.ObjectModel.dll /reference:e:\gh\chcosta\corefx\bin\AnyOS.AnyCPU.Debug\System.Private.DataContractSerialization\System.Private.DataContractSerialization.dll /reference:e:\gh\chcosta\corefx\packages/System.Reflection\4.1.0-rc3-24026-00\ref\netstandard1.5\System.Reflection.dll /reference:e:\gh\chcosta\corefx\packages/System.Reflection.Extensions\4.0.1-rc3-24026-00\ref\netstandard1.0\System.Reflection.Extensions.dll /reference:e:\gh\chcosta\corefx\packages/System.Reflection.Primitives\4.0.1-rc3-24026-00\ref\netstandard1.0\System.Reflection.Primitives.dll /reference:e:\gh\chcosta\corefx\packages/System.Runtime\4.1.0-rc3-24026-00\ref\netstandard1.5\System.Runtime.dll /reference:e:\gh\chcosta\corefx\packages/System.Runtime.Extensions\4.1.0-rc3-24026-00\ref\netstandard1.5\System.Runtime.Extensions.dll /reference:e:\gh\chcosta\corefx\packages/System.Runtime.Handles\4.0.1-rc3-24026-00\ref\netstandard1.3\System.Runtime.Handles.dll /reference:e:\gh\chcosta\corefx\packages/System.Runtime.InteropServices\4.1.0-rc3-24026-00\ref\netstandard1.5\System.Runtime.InteropServices.dll /reference:e:\gh\chcosta\corefx\packages/System.Runtime.InteropServices.PInvoke\4.0.0-rc3-24026-00\ref\netstandard1.5\System.Runtime.InteropServices.PInvoke.dll /reference:e:\gh\chcosta\corefx\packages/System.Runtime.InteropServices.RuntimeInformation\4.0.0-rc3-24026-00\ref\netstandard1.1\System.Runtime.InteropServices.RuntimeInformation.dll /reference:e:\gh\chcosta\corefx\packages/System.Runtime.Serialization.Primitives\4.1.1-rc3-24026-00\ref\netstandard1.3\System.Runtime.Serialization.Primitives.dll /reference:e:\gh\chcosta\corefx\packages/System.Text.Encoding\4.0.11-rc3-24026-00\ref\netstandard1.3\System.Text.Encoding.dll /reference:e:\gh\chcosta\corefx\packages/System.Text.RegularExpressions\4.1.0-rc3-24026-00\ref\netstandard1.5\System.Text.RegularExpressions.dll /reference:e:\gh\chcosta\corefx\packages/System.Threading\4.0.11-rc3-24026-00\ref\netstandard1.3\System.Threading.dll /reference:e:\gh\chcosta\corefx\packages/System.Threading.Tasks\4.0.11-rc3-24026-00\ref\netstandard1.3\System.Threading.Tasks.dll /reference:e:\gh\chcosta\corefx\packages/System.Xml.ReaderWriter\4.0.11-rc3-24026-00\ref\netstandard1.3\System.Xml.ReaderWriter.dll /reference:e:\gh\chcosta\corefx\packages/System.Xml.XDocument\4.0.11-rc3-24026-00\ref\netstandard1.3\System.Xml.XDocument.dll /reference:e:\gh\chcosta\corefx\packages/System.Xml.XmlDocument\4.0.1-rc3-24026-00\ref\netstandard1.3\System.Xml.XmlDocument.dll /reference:e:\gh\chcosta\corefx\packages/System.Xml.XmlSerializer\4.0.11-rc3-24026-00\ref\netstandard1.3\System.Xml.XmlSerializer.dll /reference:e:\gh\chcosta\corefx\packages/xunit.abstractions\2.0.0\lib\portable-net45+win+wpa81+wp80+monotouch+monoandroid+Xamarin.iOS\xunit.abstractions.dll /reference:e:\gh\chcosta\corefx\packages/xunit.assert\2.1.0\lib\dotnet\xunit.assert.dll /reference:e:\gh\chcosta\corefx\packages/xunit.extensibility.core\2.1.0\lib\dotnet\xunit.core.dll /reference:e:\gh\chcosta\corefx\packages/xunit.extensibility.execution\2.1.0\lib\dotnet\xunit.execution.dotnet.dll /reference:e:\gh\chcosta\corefx\packages/xunit.netcore.extensions\1.0.0-prerelease-00312-04\lib\dotnet\Xunit.NetCore.Extensions.dll /reference:e:\gh\chcosta\corefx\packages/Microsoft.DotNet.xunit.performance\1.0.0-alpha-build0030\lib\dotnet\xunit.performance.core.dll /reference:e:\gh\chcosta\corefx\packages/Microsoft.DotNet.xunit.performance\1.0.0-alpha-build0030\lib\dotnet\xunit.performance.execution.dotnet.dll /debug+ /debug:full /delaysign- /keyfile:e:\gh\chcosta\corefx\Tools/Test.snk /optimize- /out:e:\gh\chcosta\corefx\bin/obj/AnyOS.AnyCPU.Debug/System.Xml.XmlSerializer.Tests/System.Xml.XmlSerializer.Tests.dll /ruleset:e:\gh\chcosta\corefx\Tools\Microsoft.DotNet.CodeAnalysis.ruleset /target:library /warnaserror+ /utf8output /analyzer:e:\gh\chcosta\corefx\Tools/net45/analyzers/Microsoft.DotNet.CodeAnalysis.dll /additionalfile:e:\gh\chcosta\corefx\bin/obj/AnyOS.AnyCPU.Debug/System.Xml.XmlSerializer.Tests//disabledAnalyzers.config ..\..\System.Runtime.Serialization.Xml\tests\Utils.cs ..\..\System.Runtime.Serialization.Xml\tests\SerializationTypes.cs ..\..\System.Runtime.Serialization.Xml\tests\Performance\PerformanceTestsCommon.cs XmlSerializerTests.Internal.cs XmlSerializerTests.cs Performance\XsPerformanceTest.cs e:\gh\chcosta\corefx\bin/obj/AnyOS.AnyCPU.Debug/System.Xml.XmlSerializer.Tests/_AssemblyInfo.cs (TaskId:128)

**Comment by khdang** [comment]
@chcosta I added these packages in ```src/System.Xml.XmlSerializer/tests/project.json``` 
```
    "System.Runtime.Serialization.Primitives": "4.1.1-rc3-24026-00",
    "System.Runtime.Serialization.Json": "4.0.2-rc3-24026-00",
    "System.Runtime.Serialization.Xml": "4.1.1-rc3-24026-00",
    "System.Xml.XmlSerializer": "4.0.10"
```

**Comment by chcosta** [comment]
If you directly added the packages to your project.json (I assume you just did that for the purposes of validation), then remove the projectreference from your csproj and do not pass the "BuildTestsAgainstPackages=true" property.

Note that when you generate a project.json, it's setting a different version that what you have listed above for System.Xml.XmlSerializer...

> "System.Xml.XmlSerializer": "4.0.11-rc3-24026-00"

Also, I don't see entries for System.Runtime.Serialization.Json or System.Runtime.Serialization.Xml.

**Comment by khdang** [comment]
The only reason that can be the reason for the failure is that we have some tests for internal method in ```XmlSerializerTests.Internal.cs```. I believe adding a condition in csproj file will fix this:
```
<Compile Include="XmlSerializerTests.Internal.cs" Condition="'$(UseContractReferences)' == '' And '$(BuildTestsAgainstPackages)' == ''" />
```
@venkat-raman251 Could you please help to look at this?

**Comment by zhenlan** [comment]
@venkat-raman251, any updates on this item?

**Comment by venkat-raman251** [comment]
I will have a look.

**Comment by shmao** [comment]
@venkat-raman251, any updates?

**Comment by karelz** [comment]
Unclear what is needed or what is wrong. Please provide more info and reopen.
