### ISSUE TITLE
Building System.Xml.XDocument.TreeManipulation.Tests against packages fails

### ISSUE THREAD

**Issue by venkat-raman251** [dotnet/corefx#7913]
Building the Tests with /p:BuildTestsAgainstPackages=true throws errors. Currently true has been added to keep the project reference.
We should be able to remove this project reference (just reference the nupkg) and build the test project without errors. @weshaggard

**Comment by karelz** [comment]
@sepidehMS wasn't able reproduce it in the past. If it still repros, please reopen.

**Comment by weshaggard** [comment]
Please see https://github.com/dotnet/corefx/blob/master/Documentation/building/build-tests-against-packages.md. We really do need to fix try and fix these as this is how our official build runs the tests, if we don't fix them then we are essentially not running these as part of our official test runs.

**Comment by karelz** [comment]
@sepidehMS can you please confirm you understand what is needed here?

**Comment by sepidehMS** [comment]
@karelz Yes, I'm investigating this right now.

**Comment by sepidehMS** [comment]
Done by https://github.com/dotnet/corefx/pull/12874
