### ISSUE TITLE
TypeExtensions does not contain GetConstructor, GetMethod which accepts both BindingFlags and a Type[]

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#7920]
For example: in the full framework you could obtain a protected constructor with a specific signature by using the "Type.GetConstructor(BindingFlags, Binder, Type[], ParameterModifier[])" method.

TypeExtensions provides a method which accepts BindingFlags and one that accepts a Type[]. But there is no method that accepts both.

**Comment by AtsushiKan** [comment]
Now that we're backtracking on the .NetCore api reduction and restoring the full api set direclty on System.Type, it no longer makes sense to add to TypeExtensions.
