### ISSUE TITLE
Uri GetComponents test fails with invalid punycode on Unix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7921]
```
     System.Tests.UriMethodTests.GetComponents(uri: http://xn--ሴpck.com/, components: NormalizedHost, expected: "xn--ሴpck.com") [FAIL]
        Assert.Equal() Failure
                  ↓ (pos 0)
        Expected: xn--ሴpck.com
        Actual:   ఽూ.com
                  ↑ (pos 0)
        Stack Trace:
              at System.Tests.UriMethodTests.GetComponents(Uri uri, UriComponents components, UriFormat format, String expected)
              at System.Tests.UriMethodTests.GetComponents(Uri uri, UriComponents components, String expected)
```

**Comment by hughbe** [comment]
Okay, I've done a bit of digging.
The bug isn't actually in the code for `Uri.GetComponents`. It is found in IdnMapping.

Since there is no managed implementation of GetUnicode, we delegate IdnToUnicode conversions to native functions on the platform.

**Comment by ericeil** [comment]
@hughbe, thank you for taking the time to look into this!  

@tarekgh, is this something you already knew about?

**Comment by tarekgh** [comment]
@ericeil I think @ellismg can know better here as I think he is the one ported Idn support to Linux.

**Comment by hughbe** [comment]
Before there is a discussion here, i suggest closing this in favour of #8242 as this is not a problem with Uri.GetComponents and I've found more inconsistencies in IdnMapping documented there

**Comment by ericeil** [comment]
>  suggest closing this in favour of #8242

I agree.  I've updated the comment in the test code to refer to #8242, and closed this issue.  Thanks for the help with this!
