### ISSUE TITLE
ProjectReference -> Package Dependency: No packages available for System.Composition.* project references

### ISSUE THREAD

**Issue by chcosta** [dotnet/corefx#7927]
In our test builds, we'd like to be able to compile our libraries with project references converted to packages.  

System.Composition and System.Composition.Convention have project references to these libraries which we do not publish packaging for...

> "System.Composition.AttributedModel"
> "System.Composition.Convention"
> "System.Composition.Hosting"
> "System.Composition.Runtime"
> "System.Composition.TypedParts"
> "TestLibrary" 
> "Microsoft.Composition.Demos.ExtendedCollectionImports" 

The System.Composition.Convention test library was opted out of the project reference to package dependency conversion with https://github.com/dotnet/corefx/commit/c1ec94b74183f598513199cde0d799a514c0a0fb

You can repro the issue by removing the "KeepAllProjectReferences" property from System.Composition.Convention.Tests.csproj and running "sync /p /t".

**Comment by chcosta** [comment]
@weshaggard , do we intend to move the System.Composition.* packaging into corefx?

**Comment by weshaggard** [comment]
I don't know of any plans to remove the packaging for it.

**Comment by chcosta** [comment]
We don't have packages for these projects, only source.  If / when we create packages for these in the future, then we will need to update this.  Moving the milestone for this issue to Future.

**Comment by weshaggard** [comment]
No longer applicable.
