### ISSUE TITLE
ProjectReference -> Package Dependency: System.Reflection.Context does not restore against packages

### ISSUE THREAD

**Issue by chcosta** [dotnet/corefx#7930]
In our test builds, we'd like to be able to compile our libraries with project references converted to packages. 

System.Reflection.Context test project does not build when its project references are converted to package dependencies.

EXEC : error : System.Reflection.Context 4.0.1-rc3-24018-00 provides a compile-time reference assembly for System.Reflection.Context on DNXCore,Version=v5.0, but there is no run-time assembly compatible with centos.7-x64. [E:\gh\chcosta\corefx\build.proj]
EXEC : error : One or more packages are incompatible with DNXCore,Version=v5.0 (centos.7-x64). [E:\gh\chcosta\corefx\build.proj]
EXEC : error : System.Reflection.Context 4.0.1-rc3-24018-00 provides a compile-time reference assembly for System.Reflection.Context on DNXCore,Version=v5.0, but there is no run-time assembly compatible with debian.8.2-x64. [E:\gh\chcosta\corefx\build.proj]
EXEC : error : One or more packages are incompatible with DNXCore,Version=v5.0 (debian.8.2-x64). [E:\gh\chcosta\corefx\build.proj]

Perhaps the right thing to do here is to remove the System.Reflection.Context test build as I hear it provides very little value...

Alternatively, we could switch the target framework to netcore50, but then we'd need to create a netcore50 test-runtime.

**Comment by ericstj** [comment]
All this assembly does is throw platformnotsupported.  Currently we don't have an implementation for NETStandard.  Any objection to me just making the one implementation used everywhere?

**Comment by ericstj** [comment]
FYI: configuration only for netcore50 https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Context/src/System.Reflection.Context.builds#L7

Implementation throwing PNS:
https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Context/src/System/Reflection/Context/CustomReflectionContext.cs

**Comment by ericstj** [comment]
@weshaggard let me know if you want me to make the suggested change.

**Comment by weshaggard** [comment]
If it makes life easier lets just use the same one everywhere, as I don't care at all about this assembly and I wish we could just delete it.
