### ISSUE TITLE
HttpResponseMessage dispose doesn't close when the body is not read

### ISSUE THREAD

**Issue by joelverhagen** [dotnet/corefx#7932]
When using `HttpClient.SendAsync` with `HttpCompletionOption.ResponseHeadersRead`, `HttpResponseMessage.Dispose` on the resulting response does not close the connection if none of the content has been read. If you even read a single byte of the content, `Dispose` works just fine. `HttpCompletionOption.ResponseContentRead` is the default so this is perhaps a less common scenario.

I have tested Mac OS X and Linux, which have the same results. Windows acts differently.

```
> dotnet --version
1.0.0-rc2-002345
```

### Use Case

This is important because sometimes it's not necessary for a client application to read the response body (e.g. if the status code is `500 Internal Server Error` then perhaps the client does not care to download the response).

### Workaround

The client can just read a single byte from the response. However this seems like a hack and could break in the future for all I know.

### Test procedure

1. Extract the following .NET CLI test app: [closehttp.zip](https://github.com/dotnet/corefx/files/228633/closehttp.zip)
1. Open a connection but don't read any content (`dotnet run` on the test app).
1. Use some other tool to see open TCP connections on the test app process and verify one exists.
    - `lsof` on OS X and Linux.
    - [Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx) on Windows.
1. Dispose the connection by following the tool's prompts. (`HttpResponseMessage.Dispose`)
1. Expect the connection to be closed in the tool and verify in the tool used in step 3.
1. Repeat steps 2-5 with `dotnet run read` (or any command line argument) to read a byte of the content body.

### Mac OS X and Linux results

Checking a process's TCP connections:

```
> lsof -p PID | grep TCP
dotnet  49733 <REDACTED>   46u    IPv4 <REDACTED>        0t0      TCP <REDACTED>:50657->ec2-54-175-222-246.compute-1.amazonaws.com:http (ESTABLISHED)
```

`HttpResponseMessage.Dispose` only closes the connection if an attempt has been made to read from the content stream. Calling `Dispose` on the network stream (from `HttpResponseMessage.Content.ReadAsStreamAsync`) does not help. `HttpClient.Dispose` *does* close the connections.

### Windows results

Checking a process's TCP connections:

Screenshot for Process Explorer.

![capture](https://cloud.githubusercontent.com/assets/94054/14687430/572239e4-06f2-11e6-8bfb-5b20dcf13d4d.PNG)

`HttpResponseMessage.Dispose` never seems to close the connection. Calling `Dispose` on the network stream (from `HttpResponseMessage.Content.ReadAsStreamAsync`) does not help. `HttpClient.Dispose` *does* close the connections. I am thinking this may be due to the fact that the underlying layer is doing some connection pooling or `Keep-Alive` stuff. Not sure.

**Comment by joelverhagen** [comment]
Spoke to @stephentoub offline. To clarify, my scenario is handle exhaustion on OS X since my application sometimes does not read the response body.

Here's another little app to demonstrate the exhaustion: [lotsofreads.zip](https://github.com/dotnet/corefx/files/228789/lotsofreads.zip)

Note that although I am running this on OS X with a low handle limit, my app is restricting concurrency using a semaphore (16, in the example below).

<pre>
> ulimit -n
256

>  dotnet run 60 5 16 https://api.nuget.org/v3/index.json false
TASK_COUNT:      60
ITERATION_COUNT: 5
SEMAPHORE_COUNT: 16
URL:             https://api.nuget.org/v3/index.json
SHOULD_READ:     False
PID:             50855
Ready? Press any key to continue...
    0     0 GET https://api.nuget.org/v3/index.json
    1     0 GET https://api.nuget.org/v3/index.json
    2     0 GET https://api.nuget.org/v3/index.json
    3     0 GET https://api.nuget.org/v3/index.json
    4     0 GET https://api.nuget.org/v3/index.json
    5     0 GET https://api.nuget.org/v3/index.json
    6     0 GET https://api.nuget.org/v3/index.json
    7     0 GET https://api.nuget.org/v3/index.json
    8     0 GET https://api.nuget.org/v3/index.json
    9     0 GET https://api.nuget.org/v3/index.json
   10     0 GET https://api.nuget.org/v3/index.json
   11     0 GET https://api.nuget.org/v3/index.json
   12     0 GET https://api.nuget.org/v3/index.json
   13     0 GET https://api.nuget.org/v3/index.json
   14     0 GET https://api.nuget.org/v3/index.json
   15     0 GET https://api.nuget.org/v3/index.json
    6     0 200 (0 byte(s) read)
    2     0 200 (0 byte(s) read)
    8     0 200 (0 byte(s) read)
    3     0 200 (0 byte(s) read)
   16     0 GET https://api.nuget.org/v3/index.json
   19     0 GET https://api.nuget.org/v3/index.json
<i><b>- truncated -</b></i>
   36     4 GET https://api.nuget.org/v3/index.json
   36     5 ERROR An error occurred while sending the request.
    1     3 200 (0 byte(s) read)
    1     4 GET https://api.nuget.org/v3/index.json
    1     5 ERROR An error occurred while sending the request.
SUCCESSES: 204
ERRORS   : 96
RATE     : 68%
Done. Press any key to end the process...
</pre>

**Comment by stephentoub** [comment]
Thanks for the repro, @joelverhagen. I'll take a look.

**Comment by yishaigalatzer** [comment]
I would like us to consider this fix for RC2, this has some major side effects on nuget restore on mac that keeps blocking users. It also have potential major stress effect on a service calling a backend (if it repros on unix and not just mac).

CC @Petermarcu @davidfowl

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/corefx/pull/7946
