### ISSUE TITLE
Publish a package list with each build

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#7933]
We change the set of packages / versions produced quite often.  It would be good to produce a build artifact dropped to a public server that lists what packages make up a particular build.

**Comment by ericstj** [comment]
Actually @weshaggard let me know that @eerhardt was working on this.

**Comment by eerhardt** [comment]
We already write this list to my private repo:  https://github.com/eerhardt/versions/tree/master/dotnet/corefx

We drop a list of all packages Ids with their full version for both branches: master and release/1.0.0-rc2.

I'm working on moving this to a real repo (probably named `dotnet/versions`) but RC2 keeps getting in the way.  It should be moved in a week or two once RC2 slows down.

The ASP.NET team is already reading from `eerhardt/versions`, so anyone else who needs this now can read from there until it is moved.
