### ISSUE TITLE
CanCatchExceptionAsObject failed in CI on unix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7948]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_release_prtest/138/consoleText
```
     System.Linq.Expressions.Tests.ExceptionHandlingExpressions.CanCatchExceptionAsObject(useInterpreter: True) [FAIL]
        System.Exception : Exception of type 'System.Exception' was thrown.
        Stack Trace:
              at System.Linq.Expressions.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
              at System.Linq.Expressions.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
              at System.Linq.Expressions.Interpreter.Interpreter.Run(InterpretedFrame frame)
              at System.Linq.Expressions.Interpreter.LightLambda.Run(Object[] arguments)
              at Thunk(Func`2 )
              at System.Linq.Expressions.Tests.ExceptionHandlingExpressions.CanCatchExceptionAsObject(Boolean useInterpreter)
```

**Comment by stephentoub** [comment]
cc: @JonHanna, @VSadov

**Comment by JonHanna** [comment]
IIRC, (on phone right now, will double check soon), calling that with true should only happen via an active-issue decorated call.

**Comment by JonHanna** [comment]
@stephentoub is this from #7945 and subsequently passed? I thought at first you meant it was from master.

Curious as this should be pretty deterministic, and either always fail or always pass.

**Comment by stephentoub** [comment]
> @stephentoub is this from #7945 and subsequently passed? I thought at first you meant it was from master.

Yes

**Comment by JonHanna** [comment]
Right. I'm flummoxed. Any ideas @VSadov?

**Comment by VSadov** [comment]
My first guess would be that something went wrong with exception handling on Unix.

Interpreted uses real exception handling (filters, in particular) to implement exception handling. In this case it looks like Catch did not catch the exception.

The test should be completely deterministic.
in this case the catch has a filter that would basically just check if the exception is at least of type "object", which it is, since it is a System.Exception.

Since this is Unix only, I'd think something is wrong with exception filters.

**Comment by VSadov** [comment]
There was also a recent bug about JIT sometimes losing sideeffects happening in filters. 
https://github.com/dotnet/coreclr/issues/4044

However that would have impact on x64 as well, so I am not sure if that is the case here

**Comment by JonHanna** [comment]
Since we only just moved to using filters that would explain why nothing similar was seen before.

**Comment by stephentoub** [comment]
Since this happened only once and since it sounds like there was a known related bug at the time, I'm going to close this optimistically.  We can re-open if we see it again.
