### ISSUE TITLE
Collection modified during package restore

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#7959]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/72/consoleFull#205152537279494335-f7bd-47d0-8771-8661e00c2db2

> 08:47:54   [08:53:09.86] Restoring all packages...
> 08:51:58 EXEC : error : Collection was modified; enumeration operation may not execute. [/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/build.proj]
>
> 08:51:58 
/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/build.proj(80,5): error MSB3073: The command ""/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/Tools/dotnetcli/dotnet" restore --packages "/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/packages" --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://www.nuget.org/api/v2/ --infer-runtimes "/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src" "/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/pkg"" exited with code -1.

**Comment by bartonjs** [comment]
@dagood Would you expect this to also be solved with the other OSX restore errors?

**Comment by dagood** [comment]
I wouldn't be surprised if it's solved (it seems like those and this error could all be explained as a threading issue), but I never saw this error myself.

**Comment by bartonjs** [comment]
Okay, since it only happened on OSX, and it happened amongst a lot of other errors at the same time; I'm going to call this closed until proven otherwise.
