### ISSUE TITLE
Add UriTemplate from WCF to .NET Core?

### ISSUE THREAD

**Issue by martincostello** [dotnet/corefx#7983]
The [UriTemplate](https://msdn.microsoft.com/en-us/library/system.uritemplate%28v=vs.110%29.aspx) class looks useful for scenarios with calling HTTP clients, however it is part of System.ServiceModel.dll.

Could this type (or a similar one) be moved into the core framework along the `Uri` class to allow it to be used more widely and in .NET Core scenarios?

**Comment by khellang** [comment]
Just curious. Does this class implement any level of RFC 6570? Or is this some weird MS implementation, like NuGet's `SemanticVersion`? :stuck_out_tongue: If that's the case, I'd rather see a new implementation of the former, than bringing the latter over to .NET Core.

// @darrelmiller

**Comment by martincostello** [comment]
I don't know actually, I just stumbled across it while reading about some other stuff. Based on the examples in the documentation to looks like it would remove the need to manually build up URIs for API calls that I've written in the past, so it looks like something that does a similar job, regardless of implementation, would be a most welcome addition.

**Comment by darrelmiller** [comment]
That UriTemplate class is an old one back from the days of WCF REST.  It is pre-6570.   It does simple {x} style parameters and it has a wildcard character.  

@martincostello My [UriTemplates](https://www.nuget.org/packages/Tavis.UriTemplates/) is a portable library that can be used by .Net core, if you are looking for something.

**Comment by martincostello** [comment]
Sold!

**Comment by martincostello** [comment]
Alas [Tavis.UriTemplates](https://www.nuget.org/packages/Tavis.UriTemplates/) is not strong-named, so isn't suitable for use in all the things I'd like to use it in.

**Comment by khellang** [comment]
@martincostello Use [Strong Namer](https://github.com/dsplaisted/strongnamer)?

**Comment by davidsh** [comment]
Thank you for the suggestion.  It is a good idea in general about having templates, but we think it belongs where it is in WCF and is not generally applicable to .NET Core.
