### ISSUE TITLE
Created file permisssion

### ISSUE THREAD

**Issue by akusmin** [dotnet/corefx#7986]
Greetings,
Within CoreClr application under Linux i'm saving log files but permissions are only for owner (rwx------) even if parent folder has another owner.
I've tried to use FileSystem.AccessControl to modify created file permissions but it looks not supported under Linux (got error: Unable to load DLL 'api-ms-win-security-provider-l1-1-0': The specified module could not be found.)

Please give an advice is there any way to customize output file set of permissions.

Thanks.

**Comment by stephentoub** [comment]
What version are you using?  This was already fixed:
https://github.com/dotnet/corefx/pull/6797

There aren't any APIs currently change to change file permissions.  You can P/Invoke to chmod, though.

**Comment by akusmin** [comment]
Just updated to 1.0.0-rc2-20221.
System.IO.FileSystem - 4.0.1-beta-23516

test code:
'''
var file = new FileStream(filename, FileMode.OpenOrCreate,
FileAccess.ReadWrite, FileShare.ReadWrite);
file.Dispose();
'''
permission for a created file is 700.

2016-04-22 15:53 GMT+03:00 Stephen Toub <notifications@github.com>:

**Comment by stephentoub** [comment]
That's a very old build.  The current rc2 build is 4.0.1-rc2-24022.

**Comment by stephentoub** [comment]
I believe this issue has been fixed.  If you find with a recent build that it's not, please re-open. Thanks!

**Comment by akusmin** [comment]
I'm confused.
I've upgraded version of SDK to 1.0.0-rc2-20222 and version of System.IO.FileSystem  to 4.0.1-rc3-24025.

And no any changes. File is creating with permission 700.

SDK in Global.json:
```
  "sdk": {
    "version": "1.0.0-rc2-20222"
  }
```
Dependencies from project.json:
```
  "dependencies": {
    "Microsoft.CSharp": "4.0.1-rc3-24025-00",
    "System.Collections": "4.0.11-rc3-24025-00",
    "System.Console": "4.0.0-rc3-24025-00",
    "System.IO.FileSystem": "4.0.1-rc3-24025-00",
    "System.Linq": "4.1.0-rc3-24025-00",
    "System.Threading": "4.0.11-rc3-24025-00"
  }
```

What have I done wrong?

**Comment by stephentoub** [comment]
@akusmin, what do you see at the terminal when you type:
```
umask
```
?

**Comment by akusmin** [comment]
@stephentoub, output is 
```
~$ umask
0002
```

**Comment by stephentoub** [comment]
Are you using the old DNU tool or the new dotnet tool?

**Comment by akusmin** [comment]
I'm using old one (dnu).

**Comment by stephentoub** [comment]
Ah, that's likely the issue then.  dnu/dnx would lock versions of assemblies it relied on, meaning even though you're specifying a newer version of System.IO.FileSystem, you're not getting one.  This is one of the issues addressed with the dotnet tool that replaces it.  You're going to need to upgrade to dotnet.  Note that dnu/dnx don't exist anymore as of rc2.

**Comment by akusmin** [comment]
@stephentoub, no result...
Used dotnet and same 700

dotnet --version:
```
.NET Command Line Tools (1.0.0-dev-001698)

Product Information:
 Version:     1.0.0-dev-001698
 Commit Sha:  N/A

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 Runtime Id:  ubuntu.14.04-x64
```

Should I use newer version?

**Comment by stephentoub** [comment]
That's very old.  Can you just use the latest as shown on the home page at https://github.com/dotnet/cli/?

**Comment by akusmin** [comment]
@stephentoub, thanks! It was a challenge... Now it's working great!

**Comment by stephentoub** [comment]
Excellent.  Glad you got it working; sorry it was a hassle.
