### ISSUE TITLE
Support for System.Double in System.Numerics namespace 

### ISSUE THREAD

**Issue by ratishphilip** [dotnet/corefx#8007]
It would be great if the classes in** System.Numerics** namespace such as **Vector2**, **Vector3**, **Vector4**, **Matrix3x2**, **Matrix4x4**, **Plane** & **Quaternion** accept **System.Double** too wherever they are accepting **System.Single** or **float**.

I agree that it is not a good idea to silently reduce precision in the methods. But in windows application development, most of the values that we calculate or derive from other properties of UIElement are of type System.Double and each time while providing values to the classes in the System.Numerics namespace we have to cast them to float.

It would be great if they could accept **System.Double** and convert them to **float** **_internally_**. _This would save us lot of time_.

**Comment by mellinoe** [comment]
I can understand that there is a bit of friction when trying to inter-operate between a system like WPF which uses `double`s and System.Numerics.Vectors which uses floats, but I'm not sure that this would be the best way of reducing that friction. All it saves you is the effort of explicitly casting the values to (float) when passing them in, but, as a general rule of thumb, it is not good form to "silently" reduce precision, especially in a simple constructor call. It should be an explicit action from the developer to cast from one type to the other. I'm not sure we have a specific or strict guideline regarding this, but I get the feeling that this is how we've designed most other things like this in the framework. We would also not be able to do anything special here for direct field assignments. You would still always have to cast there.

We have considered, as a separate solution, providing real double-based vector types, i.e. `Vector3d`, `Vector4d`, etc., which would not require you to lose any precision. But that is not something we are likely to do soon, and I think there's also some design problems related to interoperability with that anyways. It would not be a lot of effort to create such a library (pretty much find-replace `float` -> `double`...), but it would be a significant investment to create SIMD support for such types up to par with what we already have.

**Comment by ratishphilip** [comment]
Thanks for your reply.

I agree with the fact the it should be the developer's responsibility to cast it from one type to another.

Thinking of a long term solution, now I think it would be better to provide an extension method to System.Double (say _.Single()_ or _.ToFloat()_) which would convert the **double** to **float**.

**Comment by svick** [comment]
@ratishphilip What makes `value.Single()` or `value.ToFloat()` better than `(float)value`?

**Comment by ratishphilip** [comment]
In my opinion, `(float)value` breaks the flow of typing the code. When we type, we type from left to right. Often when we pass a double value to a method or variable requiring float, most of the time we are made aware of the mistake by the red squiggly line which appears underneath the value. To solve this issue we have to go back and add the `(float)` cast manually. This breaks the flow. Moreover, there is no IntelliSense support to add the cast automatically.

Using an extension method `value.Single()` does not break the flow. All you need to do is press the `.` and IntelliSense provides you with the option of adding `Single()` from the dropdown list of methods.

I believe it is better aesthetically. Well, not everyone might agree.

It's more of a personal choice and may vary from developer to developer.

**Comment by JonHanna** [comment]
Would you negate by using a `value.Negate()` extension method instead of `-value`, by the same logic?

**Comment by ratishphilip** [comment]
@JonHanna :)

No, I would not. Providing `value

**Comment by mellinoe** [comment]
I think you may be able to come up with a Roslyn analyzer that lets you "auto-complete" that scenario, but I'm not super familiar with those or how exactly you would write it. That way, if you tried to pass a `double` into a `float`-parameter method, you would automatically get a recommended change to add the cast.

**Comment by ratishphilip** [comment]
@mellinoe 
Sounds interesting. Might look into it.
Thank you.
