### ISSUE TITLE
Two MoveFileTests failing on Windows OuterLoop

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#8024]
> System.IO.Tests.MoveFileTests.Windows_File_Move_To_Different_Directory_Triggers_Event(eventType: Deleted, moveRaisesEvent: False)
System.IO.Tests.MoveFileTests.Windows_File_Move_To_Different_Directory_Triggers_Event(eventType: Renamed, moveRaisesEvent: True)

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_release_prtest/1/
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug_prtest/3/

**Comment by stephentoub** [comment]
It's not just on Windows... all outerloop runs appear to be failing due to FSW tests, e.g.
```
System.IO.Tests.MoveFileTests.Unix_File_Move_To_Different_Directory_Triggers_Event(eventType: Created, moveRaisesEvent: True) [FAIL]
      Didn't observe a Created event within 30000ms
      Expected: True
      Actual:   False
      Stack Trace:
            at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(WaitHandle eventOccurred, String eventName, Int32 timeout)
            at System.IO.Tests.MoveFileTests.MoveAndCheck_DifferentDirectory(WatcherChangeTypes eventType, Boolean moveRaisesEvent)
            at System.IO.Tests.MoveFileTests.Unix_File_Move_To_Different_Directory_Triggers_Event(WatcherChangeTypes eventType, Boolean moveRaisesEvent)
```

**Comment by ianhays** [comment]
The outerloop tests have the wrong bool values for their expected types. I'm fixing it in #7992 so I'll just ActiveIssue hotfix them now.

**Comment by ianhays** [comment]
Pushed a PR to disable them until I permanently fixed.
