### ISSUE TITLE
[perf] BitConverter's Throw* methods could be tagged with MethodImplOptions.NoInlining

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#8039]
Helper methods that throw exceptions usually shouldn't be inlined, since 1) they aren't a branch taken often and 2) they reduce the chance of the JIT inlining the caller, which is typically more important. For example, a GitHub search for [`NoInlining`](https://github.com/dotnet/corefx/search?utf8=%E2%9C%93&q=NoInlining) in this repo shows that most of the use cases are for these kinds of methods/`SR.GetString`.

`BitConverter` already has a bunch of these types of methods: https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/BitConverter.cs#L456

We could probably tag them with this attribute to increase the chances of the public methods being inlined (e.g. [this](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/BitConverter.cs#L403)). I'm opening up an issue for this since I'm currently on vacation, but I'll submit a PR (along with benchmarks) once I return.

**Comment by mikedn** [comment]
Not inlining those helpers is something that the JIT compiler should figure out on its own. It should also figure out that those helpers never return and that's something that `NoInlining` doesn't help with, quite the contrary.

**Comment by stephentoub** [comment]
@jamesqo, did you open this issue because you're speculating that they are getting inlined, or have you confirmed that they actually are getting inlined?

**Comment by mikedn** [comment]
@stephentoub Yes, such throw helpers are unfortunately inlined by the current JIT. See https://github.com/dotnet/coreclr/issues/1270.

That said, this has nothing to do with perf, it's just that inlining bloats the caller unnecessarily. Adding `NoInlining` deals with the code bloat but it does so at the cost of decreased code quality of the main execution path.

**Comment by stephentoub** [comment]
> but it does so at the cost of decreased code quality of the main execution path.

Thanks.  Can you elaborate on this part?  I'd expect that at the call sites to these NoInlining methods, which we expect to only be used rarely and in exceptional situations, would just contain a method call site; is that not the case?

**Comment by mikedn** [comment]
> I'd expect that at the call sites to these NoInlining methods, which we expect to only be used rarely and in exceptional situations, would just contain a method call site; is that not the case?

Yes, it contains a call site and that's good for code size. But the JIT doesn't know that those helper never return, it assumes that they do and that the main code always executes. The `value` and `startIndex` parameters are initially in the `rcx` and `rdx` registers but these are killed by calls so the JIT has to move them to call preserved registers such as `rsi` and `rdi`. And these call preserved registers need to be saved/restored to/from the stack. You end up with 6 additional instructions and 4 memory load/stores that weren't there before.

It's quite easy to teach the JIT to stop inlining throw helpers but it's a bit more complicated for the JIT to also understand that these helpers never return. In any case, it's something that I think it's worth considering before adding `NoInlining` all other the place (there are a lot more places in the framework where such throw helprs are used).

**Comment by stephentoub** [comment]
> And these call preserved registers need to be saved/restored to/from the stack. You end up with 6 additional instructions and 4 memory load/stores that weren't there before.

Ah!  I understand now.  Thanks for the explanation.

**Comment by JonHanna** [comment]
@mikedn (and anyone else that knows) what's the effect of the pattern where instead of:

```C#
private static void ThrowValueArgumentNull()
{
    throw new ArgumentNullException("value");
}

/*…*/
if (value == null) ThrowValueArgumentNull();
```

One has:

```C#
private static void ValueArgumentNull()
{
    return new ArgumentNullException("value");
}

/*…*/
if (value == null) throw ValueArgumentNull();
```

Since that pattern is also found in the project. Would this benefit more directly from `NoInlining`?

I'm not about to submit a PR full of 1500 `NoInlining` attributes, but I'm curious.

**Comment by mikedn** [comment]
@JonHanna This pattern (seen in LINQ AFAIR :smile:) is a compromise. It avoids problems associated with the lack of "no return" information (because the throw statement is kept inside the caller) but at the same the code is still larger than it needs to be since there are 2 calls instead of 1 (1 call to helper and 1 call to throw instead of just one call to helper).
