### ISSUE TITLE
dotnet restore failing on OS X

### ISSUE THREAD

**Issue by San7hos** [dotnet/corefx#8041]
Hi,

I have an asp.net project on my OS X and while with dnx and dnu everything works, I cannot make it work with dotnet cli. I have also started an SO question:

http://stackoverflow.com/questions/36787311/dotnet-cli-unable-to-restore-packages

My project.json file:

```
{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true
    },
    "dependencies": {
        "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
        "Microsoft.AspNet.Hosting": "1.0.0-rc1-final"
    },
    "frameworks": {
        "dnx451": {},
        "dnxcore50": {}
    },
    "commands": {
        "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.Kestrel --server.urls http://localhost:5000"
    },
    "exclude": [
        "wwwroot",
        "node_modules"
    ]
}
```

The command line output:

> Arrakis:AndaronWebApp Santhos$ dotnet restore
> log  : Restoring packages for /Users/Santhos/Projects/andaron/src/AndaronWebApp/project.json...
> error: System.Diagnostics.Debug 4.0.11-beta-23516 provides a compile-time reference assembly for System.Diagnostics.Debug on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
> error: System.Diagnostics.TraceSource 4.0.0-beta-23516 provides a compile-time reference assembly for System.Diagnostics.TraceSource on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
> error: System.Net.Primitives 4.0.11-beta-23516 provides a compile-time reference assembly for System.Net.Primitives on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
> error: System.Runtime.Extensions 4.0.11-beta-23516 provides a compile-time reference assembly for System.Runtime.Extensions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
> error: System.Threading 4.0.11-beta-23516 provides a compile-time reference assembly for System.Threading on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
> error: System.Console 4.0.0-beta-23516 provides a compile-time reference assembly for System.Console on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
> error: System.IO.FileSystem.Watcher 4.0.0-beta-23516 provides a compile-time reference assembly for System.IO.FileSystem.Watcher on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
> error: System.IO.FileSystem 4.0.1-beta-23516 provides a compile-time reference assembly for System.IO.FileSystem on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
> error: System.Globalization.Extensions 4.0.1-beta-23516 provides a compile-time reference assembly for System.Globalization.Extensions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
> error: System.Linq.Expressions 4.0.11-beta-23516 provides a compile-time reference assembly for System.Linq.Expressions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
> error: System.Security.Cryptography.X509Certificates 4.0.0-beta-23516 provides a compile-time reference assembly for System.Security.Cryptography.X509Certificates on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
> error: System.Security.Cryptography.Algorithms 4.0.0-beta-23516 provides a compile-time reference assembly for System.Security.Cryptography.Algorithms on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
> error: System.Security.Cryptography.Encoding 4.0.0-beta-23516 provides a compile-time reference assembly for System.Security.Cryptography.Encoding on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
> error: Some packages are not compatible with DNXCore,Version=v5.0 (osx.10.11-x64).
> info : Committing restore...
> log  : Restore failed in 1083ms.
> 
> Errors in /Users/Santhos/Projects/andaron/src/AndaronWebApp/project.json
>     System.Diagnostics.Debug 4.0.11-beta-23516 provides a compile-time reference assembly for System.Diagnostics.Debug on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
>     System.Diagnostics.TraceSource 4.0.0-beta-23516 provides a compile-time reference assembly for System.Diagnostics.TraceSource on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
>     System.Net.Primitives 4.0.11-beta-23516 provides a compile-time reference assembly for System.Net.Primitives on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
>     System.Runtime.Extensions 4.0.11-beta-23516 provides a compile-time reference assembly for System.Runtime.Extensions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
>     System.Threading 4.0.11-beta-23516 provides a compile-time reference assembly for System.Threading on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
>     System.Console 4.0.0-beta-23516 provides a compile-time reference assembly for System.Console on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
>     System.IO.FileSystem.Watcher 4.0.0-beta-23516 provides a compile-time reference assembly for System.IO.FileSystem.Watcher on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
>     System.IO.FileSystem 4.0.1-beta-23516 provides a compile-time reference assembly for System.IO.FileSystem on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
>     System.Globalization.Extensions 4.0.1-beta-23516 provides a compile-time reference assembly for System.Globalization.Extensions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
>     System.Linq.Expressions 4.0.11-beta-23516 provides a compile-time reference assembly for System.Linq.Expressions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
>     System.Security.Cryptography.X509Certificates 4.0.0-beta-23516 provides a compile-time reference assembly for System.Security.Cryptography.X509Certificates on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
>     System.Security.Cryptography.Algorithms 4.0.0-beta-23516 provides a compile-time reference assembly for System.Security.Cryptography.Algorithms on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
>     System.Security.Cryptography.Encoding 4.0.0-beta-23516 provides a compile-time reference assembly for System.Security.Cryptography.Encoding on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
>     Some packages are not compatible with DNXCore,Version=v5.0 (osx.10.11-x64).
> 
> NuGet Config files used:
>     /Users/Santhos/.nuget/NuGet/NuGet.Config
> 
> Feeds used:
>     https://api.nuget.org/v3/index.json
> Arrakis:AndaronWebApp Santhos$ dotnet --version
> .NET Command Line Tools (1.0.0-beta-001598)
> 
> Product Information:
>  Version:     1.0.0-beta-001598
>  Commit Sha:  7582649f88
> 
> Runtime Environment:
>  OS Name:     Mac OS X
>  OS Version:  10.11
>  OS Platform: Darwin
>  Runtime Id:  osx.10.11-x64

**Comment by ericstj** [comment]
You are using rather old dependencies and framework monikers.
```
    "dependencies": {
        "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
        "Microsoft.AspNet.Hosting": "1.0.0-rc1-final"
    },
    "frameworks": {
        "dnx451": {},
        "dnxcore50": {}
    },
```
This project worked with DNX because DNX didn't actually check for implementations for many of the packages and relied on its own internal copy of the packages.  You could make this work with the CLI and those old packages/monikers but its probably better just to update your project.json to match the new templates.

You can see samples of ASP.NET projects here: https://github.com/aspnet/cli-samples

**Comment by San7hos** [comment]
@ericstj I have realised that after seeing the new samples to which I had already been pointed, thanks. I forgot to close the issue, sorry about that.
