### ISSUE TITLE
Documenting the support for Negotiate Stream

### ISSUE THREAD

**Issue by kapilash** [dotnet/corefx#8042]
The behavior of ```System.Net.NegotiateStream``` for unix needs to be documented so as to allow the developers/administrators to install the required libraries.

```NegotiateStream``` relies on the gssapi implementation available on the platform.
* On Linux flavors, the default gssapi implementation provided is [MIT's krb5 library](http://web.mit.edu/kerberos/) which is available on all the linux platforms
* On OSX, the default implementation is heimdal-based GSS.framework 

On both Linux and OSX, NegotiateStream uses SPNEGO and relies on the underlying implementation for supporting Kerberos or NTLM as the underlying security protocol.

* On OSX, Gss.framework supports SPNEGO mechanism with Kerberos and NTLM as the security protocols.
* On Linux, mit krb5 library supports SPENGO mechanism and Kerberos as the out of the box security protocol. The implenentation can be made to support NTLM too by installing [GSS-NTLMSSP plugin](https://fedorahosted.org/gss-ntlmssp/) or another plugin with similar functionality. The fallback to NTLM is thus dependent on runtime availability of such a plugin.

On RHEL and CENTOS, the plugin GSS-NTLMSSP is available from the package managers. The same is also available on Ubuntu 16. It can be installed on the other flavors of linux.
There's no compile time dependency on this plugin.

**Comment by joshfree** [comment]
@leecow can you help @kapilash get this into the RTM release notes?

**Comment by leecow** [comment]
Captured in rel notes working doc
