### ISSUE TITLE
The default debug action for *.Tests projects should disable xunit parallelism.

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefx#8048]
I see no advantage to having multiple tests running in multiple threads firing off breakpoints when I'm trying to debug a test. 

tools\test.targets already nicely adds the "-wait" argument by default so the console doesn't disappear on you.

``  <StartArguments Condition="'$(StartArguments)'==''">$(TestArguments) -wait</StartArguments>
``

The argument "-parallel none" would be a great companion to the "-wait" argument.

xunit.console.netcore.exe doesn't care if you specify "-parallel" multiple times so this should be safe.

**Comment by joperezr** [comment]
This change will make it to corefx as soon as buildtools is updated.
