### ISSUE TITLE
Remove explicit reference to System.ComponentModel.Primitives project when dev/typedescriptor is merged to master

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/corefx#8050]
The updated System.ComponentModel.TypeConverter utilizes new attributes in the S.CM.Primitives assembly, but the reference assembly has not been updated with that surface area. For now, there is an explicit reference. Once the branch gets merged and built, the reference assembly will be available and can be referenced instead of explicitly referencing the project file.

**Comment by joshfree** [comment]
@twsouthwick can this issue be closed now?

**Comment by twsouthwick** [comment]
Not yet - dev/typedescriptor has yet to be merged.
