### ISSUE TITLE
Build fails on Ubuntu with missing corerun error

### ISSUE THREAD

**Issue by tstringer** [dotnet/corefx#8053]
I was successfully able to do a native build on Ubuntu Linux, but when attempting to do a `./build.sh managed` I received the following error:

> `./build.sh: line 129: /var/lib/corefx/Tools/corerun: No such file or directory`

And looking at the Tools dir, I don't see `corerun` there.  Below are the contents of this directory:

```
drwxr-x---  4 root root 4096 Apr 25 11:48 .
drwxr-xr-x 10 root root 4096 Apr 25 12:05 ..
drwxr-xr-x  2 root root 4096 Apr 25 11:48 1.0.25-prerelease-00321-01
drwxr-xr-x  4 1001 sudo 4096 Apr 21 13:47 dotnetcli
```

Here is my build of Ubuntu:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
```

Is there something I'm missing or should have done?  I have followed the *nix build instructions line by line!

Thank you in advance!

**Comment by mellinoe** [comment]
It looks like init-tools.sh failed at some point. Is there an init-tools.log file next to init-tools.sh? If so, could you point out any errors appearing in it, or just paste the whole thing somewhere?

**Comment by tstringer** [comment]
@mellinoe thanks for the quick reply!  Here is the log output:

```
Running: /var/lib/corefx/init-tools.sh
Installing 'https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/1.0.0-rc2-002468/dotnet-dev-ubuntu-x64.1.0.0-rc2-002468.tar.gz' to '/var/lib/corefx/Tools/dotnetcli/dotnet.tar'
Running: /var/lib/corefx/Tools/dotnetcli/dotnet restore "/var/lib/corefx/Tools/1.0.25-prerelease-00321-01/project.json" --packages /var/lib/corefx/packages --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json
Running: /var/lib/corefx/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00321-01/lib/init-tools.sh /var/lib/corefx /var/lib/corefx/Tools/dotnetcli/dotnet /var/lib/corefx/Tools
```

It's worth noting that this wasn't the first time I ran the build script, so this instance of running the build script explain that build tools have already been initialized:

```
tstringer@tahr:/var/lib/corefx$ sudo ./build.sh managed
Setting up directories for build
Tools are already initialized
```

With that being said, maybe init-tools issues were overwritten on subsequent runs?

**Comment by mellinoe** [comment]
That is possible. Could you delete your Tools directory entirely and then run `init-tools.sh` by itself and post the log?

**Comment by tstringer** [comment]
@mellinoe Done!  Here is the output of not only re-running `init-tools.sh`, but also dumping `init-tools.log`:

```
root@tahr:/var/lib/corefx# ./init-tools.sh 
Installing dotnet cli...
Restoring BuildTools version 1.0.25-prerelease-00321-01...
Failed to load /var/lib/corefx/Tools/dotnetcli/shared/Microsoft.NETCore.App/1.0.0-rc2-3002468/libcoreclr.so, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to coreclr
ERROR: Could not restore build tools correctly. See '/var/lib/corefx/init-tools.log' for more details.
Initializing BuildTools...
./init-tools.sh: line 84: /var/lib/corefx/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00321-01/lib/init-tools.sh: No such file or directory
Done initializing tools.


root@tahr:/var/lib/corefx# cat init-tools.log
Running: /var/lib/corefx/init-tools.sh
Installing 'https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/1.0.0-rc2-002468/dotnet-dev-ubuntu-x64.1.0.0-rc2-002468.tar.gz' to '/var/lib/corefx/Tools/dotnetcli/dotnet.tar'
Running: /var/lib/corefx/Tools/dotnetcli/dotnet restore "/var/lib/corefx/Tools/1.0.25-prerelease-00321-01/project.json" --packages /var/lib/corefx/packages --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json
Running: /var/lib/corefx/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00321-01/lib/init-tools.sh /var/lib/corefx /var/lib/corefx/Tools/dotnetcli/dotnet /var/lib/corefx/Tools
```

**Comment by mellinoe** [comment]
It looks like you are missing libunwind from your machine. Could you try installing it using apt-get?

`sudo apt-get install libunwind8-dev`

**Comment by tstringer** [comment]
@mellinoe that looks like that fixed it!  Still building and running tests, but it's safe to say that I'm way further than I was originally :smile: 

Thanks so much!  And I have to apologize, as I preemptively opened this issue, if only I would've just read the appropriate logging.

But now that this is out there, do you think it would be a good idea to put `libunwind8-dev` as a prerequisite in the build doc for *nix?

**Comment by mellinoe** [comment]
> But now that this is out there, do you think it would be a good idea to put libunwind8-dev as a prerequisite in the build doc for *nix?

Yeah, we need to be better about documenting what is required. We list some things in https://github.com/dotnet/corefx/blob/master/Documentation/building/unix-instructions.md, but it is not exhaustive, and libunwind is not included there.

**Comment by tstringer** [comment]
@mellinoe I started this with a fresh trusty tahr (14.04) installation because I could get my daily installation of Ubuntu working. So I could document the steps and requirements and create a pull request for this doc, unless you have any qualms with that! I'll verify my steps/prereqs are reproducible to a successful build.

Let me know your thoughts!

**Comment by mellinoe** [comment]
> So I could document the steps and requirements and create a pull request for this doc, 

If you don't mind doing that, we would really appreciate it! If you know all of the things that are missing from a clean installation of Ubuntu 14.04, please add them to that document. At this point, I've had my machine set up for a while so I've long since forgotten what was needed from a clean install :smile: . Thanks!

**Comment by joperezr** [comment]
Hey @tstringer thanks so much for your help and for reporting the lack of documentation. Would it be ok to close this issue since you figured out what was wrong?

**Comment by tstringer** [comment]
@joperezr absolutely!  And likewise, @mellinoe, I have created pull request #8109 to add this documentation.  Let me know your thoughts!

**Comment by pedoc** [comment]
@mellinoe thanks,it's work for me, system: deepin 15.5
