### ISSUE TITLE
`System.Linq.Parallel` - `Average` vs. `Sum` on empty sets.

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#806]
For parallel collections, the `Average` operator throws `InvalidOperationException` if there are no elements (empty).  In contrast, `Sum` returns 0.
I'm not really seeing a good reason for there to be a difference here - it's not like a 0 result is any more or less valid for `Sum` than it would be for `Average` (for what it's worth, SQL returns null for both operations).

(This looks to be a simple change in either direction.  Since I'm working on updating the tests for this namespace I'd like the opportunity to make the change, if it occurs)

**Comment by ellismg** [comment]
FWIW, I believe the behavior matches the standard LINQ operations.

I think it's a little odd that sum is defined over the empty set, but I worry about changing that behavior.

Whatever we do, we should make sure LINQ and PLINQ behave the same way.

**Comment by Clockwork-Muse** [comment]
@ellismg  - it does, but that brings up another problem - I don't think the `System.Collections.Generic` namespace has been open-sourced yet (looks like we have tests, but no implementation source).

**Comment by ellismg** [comment]
That's correct.  We are working on getting it up here.

What's the rationale for changing either of these?

**Comment by mikedn** [comment]
The fact that Average throws an exception for empty collections is a natural consequence of Sum returning 0 for empty collections:
```
average({}) = sum({}) / 0 = 0 / 0 = nonsense
```

And Sum returns 0 for empty collections because that's the [convention](http://en.wikipedia.org/wiki/Empty_sum) in mathematics. If you make `sum(empty)` null then you end up with weird situations such as:
```
sum(c,c...c) = c * n = 0 for n = 0
sum() = null
0 = null !?!
```
SQL kind of screwed up when it decided that SUM(empty) is null. The result of a mathematical operation should not be null unless at least one of the input variable is null.

**Comment by Clockwork-Muse** [comment]
@mikedn - Okay, I can get returning 0 for an empty sum like that.  SQL really only returns null when you've got a null source column (usually from a `LEFT JOIN` that's not fulfilled) - otherwise you usually end up with an empty set, so get no rows returned (no value returned).  
...Hmm, looks like SO [already had a question on this](http://math.stackexchange.com/questions/909395/what-is-the-average-of-no-numbers).  
@ellismg  - It just suddenly felt strange to me.  Didn't mean I was right, but it was something I felt like I had to ask.
