### ISSUE TITLE
OSX System.Net.NetworkInformation.Functional.Tests timeout in CI

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#8066]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/263/console

> 08:53:21   Discovering: System.Net.NetworkInformation.Functional.Tests
08:53:21   Discovered:  System.Net.NetworkInformation.Functional.Tests
08:53:21   Starting:    System.Net.NetworkInformation.Functional.Tests
08:53:21   System.Xml.XDocument.xNodeBuilder.Tests -> /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/bin/AnyOS.AnyCPU.Debug/System.Xml.XDocument.xNodeBuilder.Tests/System.Xml.XDocument.xNodeBuilder.Tests.dll
10:22:33 
Build timed out (after 120 minutes). Marking the build as aborted.
10:22:39 
Build was aborted
10:22:39 [xUnit] [INFO] - Starting to record.
10:22:39 [xUnit] [INFO] - Processing xUnit.Net-v2 (default)
10:22:39 
MSBUILD : error MSB4166: Child node "3" exited prematurely. Shutting down. Diagnostic information may be found in files in the temporary files directory named MSBuild_*.failure.txt.
10:22:39 /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/Tools/tests.targets(145,5): warning MSB5021: "sh" and its child processes are being terminated in order to cancel the build. [/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Net.NetworkInformation/tests/FunctionalTests/System.Net.NetworkInformation.Functional.Tests.csproj]

**Comment by stephentoub** [comment]
cc: @ericeil, is it possible your recent change to NetworkInformation causes this?  We've been seeing these hangs that we never used to see.

**Comment by ericeil** [comment]
> is it possible your recent change to NetworkInformation causes this?

That change was Linux-only.

**Comment by joshfree** [comment]
marking as `blocking-clean-ci` and moving up to RC3

**Comment by mellinoe** [comment]
Do we know which test is hanging? Can we please mention this issue if a PR has hit this issue? It would be nice to be able to take a machine offline if we have a live instance of this happening. I can disable the test on OSX, but it would be nice to know which test specifically is hanging. If I had to blindly guess, I would imagine it's the NetworkChange tests, because the OSX implementation is complicated and involves multiple threads.
