### ISSUE TITLE
ProjectReference -> Package Dependency: Disabled System.Linq.Expressions from package dependency build

### ISSUE THREAD

**Issue by chcosta** [dotnet/corefx#8067]
System.Linq.Expressions does not build when project references are converted to package dependencies due to 

> Catalog\ExpressionCatalog.RuntimeVariables.cs(34,39): error CS0246: The type or namespace name 'IRuntimeVariables' could not be found (are you missing a using directive or an assembly reference?) [D:\A_work\8\s\src\System.Linq.Expressions\tests

See PR #7998

**Comment by chcosta** [comment]
@JonHanna

**Comment by JonHanna** [comment]
@chcosta I must admit I'm not entirely clear on how the package references work, but if I'm not completely off the mark then this public type should be visible, that not being so is a bug, and the change in #8339 will make it so.
But as I say, this is something where I don't even know basics that I probably should know, so maybe I'm barking up the wrong tree.

**Comment by chcosta** [comment]
Your assessment sounds correct to me.

**Comment by JonHanna** [comment]
Great. I don't know how to confirm that it fixes your issue though.

**Comment by VSadov** [comment]
@chcosta - is the bug still actionable?

**Comment by karelz** [comment]
@chcosta ping? Are you working on it? If not, we should unassign you :)

**Comment by chcosta** [comment]
We no longer build with package references.  This is not an issue anymore.
