### ISSUE TITLE
UDP Datagram do not receive fragmented packets

### ISSUE THREAD

**Issue by DiegoVil** [dotnet/corefx#8068]
With [this ](http://stackoverflow.com/questions/36832880/problems-with-udp-in-windows-10-uwp)configuration I was able to see that when are sent fragmented packets Universal App do not receive any messagereceived event. When there is a single packet yes.

**Comment by CIPop** [comment]
@DiegoVil the sample contains references to unsupported APIs in CoreFX (`UdpClient.Connect`) so I presume it's not a .Net Core project. For .Net Desktop please open a new issue at http://connect.microsoft.com/. 

If you can repro this in .Net CoreFX:
1. In your current environment, use .Net Core in both the client and the server to exclude the possibility of an issue within the WinRT DatagramSocket.
2. Attach a Wireshark trace from all experiments: `UdpClient/UdpClient` as well as `UdpClient/DatagramSocket` for comparison.
3. Please submit a PR adding the failing test to the `src\System.Net.Sockets\tests\FunctionalTests` project.

**Comment by DiegoVil** [comment]
Dear @CIPop ,
Being honest I am not a great developer.Maybe some of the things that I say are not coherent at all.Please excuse me about that. As you say it is a mix of both frameworks. I am running this in 2 different computers. In the first computer I am running an application based on 4.5 framework that do not use .netCore ( uses framework 4.5). In the second one I am running a code taken from [here](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/DatagramSocket) that this is based on .netCore framework. If I run with 2 4.5 frameworks this problem do not appears. 
I will do point 2.
Regarding opening a issue I will also do it. Thanks

**Comment by CIPop** [comment]
Thanks for the clarification @DiegoVil. I think I understand the issue: the only incorrect part is that [DatagramSocket](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/DatagramSocket) is actually a UWP API (native COM) not a .Net (Desktop or Core) component.

To continue the investigation, please open a http://connect.microsoft.com bug. It would help a lot if you could attach to the connect issue the Wireshark trace as well as a sample SLN that contains both client and server along with instructions on how to repro the problem.

Closing this issue as it's not a .Net problem.
