### ISSUE TITLE
`System.Linq.Parallel` - `Any` vs `All` on empty sets.

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#807]
On an empty set, `Any(delegate)` returns false.
On an empty set, `All(delegate)` returns true.  
(This appears to be an artifact of the implementation as direct opposites of each other)

This seems nonsensical for two reasons:
 1. The documentation of the return value is identical in wording, save for `'any'`/`'all'`.
 2. Conceptually, the result of asking the delegate 'question' would be the same for both (which one it gets - true or false - would depend on wording).

Which one is correct?  Or should they both throw `InvalidOperationException` in that case?  Or just update the documentation to  reflect this particular quirk?  Given I'm working on the tests, I'd like the chance to make any changes myself.
(The existing tests were no help, as they didn't test empty sets at all)
(Yes, I'm aware `Any()` - which solely checks for existence of elements - returns false in the case of an empty set.  That choice of name feels somewhat unfortunate in relation to the delegate version...)

**Comment by ellismg** [comment]
In my opinion, the behavior here is sensible and correct.  The documentation on MSDN calls out the specific case that All returns true for an empty enumerable.

We should just add test coverage.
