### ISSUE TITLE
Can't open VS project due to missing files

### ISSUE THREAD

**Issue by bdenison99** [dotnet/corefx#8070]
corefx-master\corefx-master\src\System.IO.FileSystem.DriveInfo\src\System.IO.FileSystem.DriveInfo.csproj : error  : The imported project "\corefx-master\corefx-master\Tools\BuildVersion.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  \corefx-master\corefx-master\dir.props

Where are these files?

**Comment by mellinoe** [comment]
@bdenison99 Have you run `init-tools.cmd` before opening the solution?

**Comment by bdenison99** [comment]
That did it.  I didn't see any reference to this step in the readme.md.  Can we get this added somewhere?

**Comment by bdenison99** [comment]
So - next up is these two errors when trying to build:
NuGet Package restore failed for project System.IO.FileSystem.DriveInfo.Tests for 'test-runtime '.
Unable to resolve test-runtime  for DNXCore,Version=v5.0.

**Comment by maririos** [comment]
@joperezr could you please handle this? We need to show the "run init-tools" message again?

**Comment by maririos** [comment]
@bdenison99 I can't repro your error. Could you please share the steps you are executing in order to build?

**Comment by joperezr** [comment]
Thanks for reporting the issue @bdenison99, I have linked the PR that will give you a better error message if you haven't run init-tools before building individual projects.

**Comment by bdenison99** [comment]
I downloaded the zip file from here, stripped the alternate data streams that marked the files as coming from the internet, ran init-tools.cmd, then build.cmd.

**Comment by joperezr** [comment]
> stripped the alternate data streams that marked the files as coming from the internet

What do you mean by alternate data streams?

Can you try cleaning out your repo by running `clean.cmd /all` and then building the whole tree by running `build.sh`? You shouldn't see any issues after doing those two steps.

**Comment by bdenison99** [comment]
https://blogs.technet.microsoft.com/askcore/2013/03/24/alternate-data-streams-in-ntfs/

This is the mechanism by which Windows determines that a file came from the internet, an e-mail attachment, etc.  I saw an error early in the build process that said that the powershell script was unsigned and couldn't be run because the powershell execution policy was set to not allow it.  Removing the ADS from the source files makes Windows think they were all created locally and not downloaded from the internet.

I ran clean.cmd, and then build.cmd.  I'm now getting these kinds of errors:
C:\Users\bdenison\Desktop\corefx-master\corefx-master\Tools\tests.targets(188,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiated
Task>d__26.MoveNext() [C:\Users\bdenison\Desktop\corefx-master\corefx-master\src\System.Xml.ReaderWriter\tests\Readers\CharCheckingReader\System.Xml.RW.CharChe
ckingReader.Tests.csproj]

**Comment by maririos** [comment]
@bdenison99 are you still having problems when building?

**Comment by bdenison99** [comment]
Yes.  I've stopped trying to build since it's not working.

**Comment by maririos** [comment]
I haven't been able to repro it and I don't see more people reporting an issue. Could you try cloning the repo again and do build.cmd?
@mellinoe do you have an idea of what may be happening?

**Comment by bdenison99** [comment]
I'll give it a try once I get a dedicated development / build system.  I'm beginning to suspect that the corporate IT imaged laptop has an issue.

**Comment by bdenison99** [comment]
Could this be caused by my running a build on Windows 7?
I see the following in the output, and not long after I get lots of errors:

C:\Users\bdenison\git_workspace\net_core\Tools\packageresolve.targets(78,5): warning : Your project.json doesn't have a runtimes section. You should add '"runtimes": { "win7-x64":
 { } }' to your project.json and then re-run NuGet restore. [C:\Users\bdenison\git_workspace\net_core\src\System.AppContext\src\redist\System.AppContext.depproj]
C:\Users\bdenison\git_workspace\net_core\Tools\packageresolve.targets(78,5): warning : Your project.json doesn't have a runtimes section. You should add '"runtimes": { "win7-x64":
 { } }' to your project.json and then re-run NuGet restore. [C:\Users\bdenison\git_workspace\net_core\src\System.AppContext\src\redist\System.AppContext.depproj]

...

C:\Users\bdenison\git_workspace\net_core\Tools\packageresolve.targets(78,5): warning : Your project is not referencing the "DNXCore,Version=v5.0" framework. Add a reference to "DN
XCore,Version=v5.0" in the "frameworks" section of your project.json, and then re-run NuGet restore. [C:\Users\bdenison\git_workspace\net_core\src\System.Data.SqlClient\src\System
.Data.SqlClient.csproj]
C:\Users\bdenison\git_workspace\net_core\Tools\packageresolve.targets(78,5): warning : Your project is not referencing the "DNXCore,Version=v5.0" framework. Add a reference to "DN
XCore,Version=v5.0" in the "frameworks" section of your project.json, and then re-run NuGet restore. [C:\Users\bdenison\git_workspace\net_core\src\System.Data.SqlClient\src\System
.Data.SqlClient.csproj]
C:\Users\bdenison\git_workspace\net_core\Tools\packageresolve.targets(78,5): warning : Your project is not referencing the "DNXCore,Version=v5.0" framework. Add a reference to "DN
XCore,Version=v5.0" in the "frameworks" section of your project.json, and then re-run NuGet restore. [C:\Users\bdenison\git_workspace\net_core\src\System.Data.SqlClient\src\System
.Data.SqlClient.csproj]
C:\Users\bdenison\git_workspace\net_core\Tools\packageresolve.targets(78,5): warning : Your project is not referencing the "DNXCore,Version=v5.0" framework. Add a reference to "DN
XCore,Version=v5.0" in the "frameworks" section of your project.json, and then re-run NuGet restore. [C:\Users\bdenison\git_workspace\net_core\src\System.Data.SqlClient\src\System
.Data.SqlClient.csproj]

...

C:\Users\bdenison\git_workspace\net_core\Tools\tests.targets(190,5): error MSB4018: The "GetTargetMachineInfo" task failed unexpectedly.\r [C:\Users\bdenison\git_workspace\net_cor
e\src\Common\tests\Common.Tests.csproj]
C:\Users\bdenison\git_workspace\net_core\Tools\tests.targets(190,5): error MSB4018: System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-sysinfo-l1-2-0.dll': The speci
fied module could not be found. (Exception from HRESULT: 0x8007007E)\r [C:\Users\bdenison\git_workspace\net_core\src\Common\tests\Common.Tests.csproj]
(about 150 more errors follow)

**Comment by maririos** [comment]
@bdenison99 I repro it in a win7 machine. I don't know why it is failing in this configuration though. Could you open a different issue with this error information?
Thanks!

**Comment by bdenison99** [comment]
Done!
