### ISSUE TITLE
How do i get an spesified encoding like this.

### ISSUE THREAD

**Issue by 18583690825** [dotnet/corefx#8077]
Encoding enc = Encoding.GetEncoding("gbk");
↓↓↓↓↓↓↓↓↓↓
Exception: 'gbk' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name

can anyone give a solution,please.

**Comment by tarekgh** [comment]
try Encoding.GetEncoding("gb2312") or Encoding.GetEncoding(936)

**Comment by tarekgh** [comment]
one more point, you can look at the page https://msdn.microsoft.com/en-us/library/system.text.encoding(v=vs.110).aspx for the list of all encodings with the supported names and codepage numbers.

I am going to close this issue but feel free to reply back or re-open if you have any following questions. 
Thanks

**Comment by 18583690825** [comment]
@tarekgh 
Thanks very much!
only two lines of code solved my question.
`Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);`
`Encoding enc = Encoding.GetEncoding(54936);`

im using `dnxcore50` and `coreclr update1` so does this work on linux?

**Comment by tarekgh** [comment]
> im using  dnxcore50  and  coreclr update1  so does this work on linux?
Yes it should work on Linux exactly as it works on Windows. Enjoy!
