### ISSUE TITLE
OSPlatform.FreeBSD

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#8079]
While looking at OSPlatform, there seems to be some strangeness regarding FreeBSD.

FreeBSD is on the release/1.0.0-rc1 branch, but not on master or release/v1.0.0-rc2.
The 1.0.0-rc1 version doesn't have a property for FreeBSD but the private backing field is there.

cc @jasonwilliams200OK

**Comment by stephentoub** [comment]
> doesn't have a property for FreeBSD but the private backing field is there.

We're not exposing additional public properties until we're confident in the implementation, tests are passing across the board, etc.  FreeBSD is not in a sufficiently working state yet to do that.

**Comment by tmds** [comment]
@stephentoub ok, what about the differences between rc1, rc2 and master?

**Comment by stephentoub** [comment]
> what about the differences between rc1, rc2 and master?

Can you paste links?  What differences are you referring to?

**Comment by tmds** [comment]
FreeBSD is here on rc1:
https://github.com/dotnet/corefx/blob/release/1.0.0-rc1/src/System.Runtime.InteropServices.RuntimeInformation/src/OSPlatform.cs

But not on master: https://github.com/dotnet/corefx/blob/master/src/System.Runtime.InteropServices.RuntimeInformation/src/System/Runtime/InteropServices/RuntimeInformation/OSPlatform.cs

Nor on rc2:
https://github.com/dotnet/corefx/blob/release/1.0.0-rc2/src/System.Runtime.InteropServices.RuntimeInformation/src/System/Runtime/InteropServices/RuntimeInformation/OSPlatform.cs

**Comment by stephentoub** [comment]
The implementation changed as part of https://github.com/dotnet/corefx/commit/dbb7a3f2d3938b9b888b876ba4b2fd45fdc10985 to move the name detection into the native shim.  At that point the const and field you reference became dead code and were removed.

**Comment by tmds** [comment]
Thanks for clarifying.
