### ISSUE TITLE
System.ServiceProcess.ServiceController Throws InvalidOperationException for Valid Service

### ISSUE THREAD

**Issue by mirichmo** [dotnet/corefx#8090]
There is a behavioral difference in the ServiceController constructor when handling a kernel mode driver between .Net 4.5 and CoreCLR. The ServiceController works as expected in .Net 4.5, but fails to properly construct a ServiceController object in CoreCLR; throwing an InvalidOperationException during subsequent use.

I verified that the process is present and running on the system:

sc.exe query tcpip

SERVICE_NAME: tcpip
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

The following code triggers the exception. In this case, nameOfService == "tcpip" and computerName == ".". The exception is thrown when executing "sc.Status."

`            try
            {
                ServiceController sc = new ServiceController(nameOfService, computerName);
                ServiceControllerStatus tmp = sc.Status; // this will throw if the service doesn't exist

                // no exceptions = this is an existing, valid service = add
                listOfValidServices.Add(sc);
            }
            catch (InvalidOperationException)
            {
            }
            catch (ArgumentException)
            {
            }
`
Exception:
System.InvalidOperationException {"Service TCPIP was not found on computer '.'."}

**Comment by Priya91** [comment]
Investigated the desktop and .netcore implementations, we are using different win32 calls, on .netcore, we are querying only services of type ```SERVICE_WIN32```, whereas tcpip service that's queried is of type ```SERVICE_KERNEL_DRIVER```. Will fix the .NET core implmentation.
