### ISSUE TITLE
OSInformation not querying the underlying OS runtime is simply not good enough.

### ISSUE THREAD

**Issue by redknightlois** [dotnet/corefx#8099]
Here is a real example of use why build time OS Information without the real runtime is not a good idea. 

See discussions here:

- https://github.com/dotnet/corefx/issues/3032
- https://github.com/dotnet/corefx/issues/6105
- https://github.com/dotnet/corefx/issues/1017

I code for a managed NoSQL database and for us performance is a must; therefore in some cases we have to do some platform specific stuff like calling PrefetchVirtualMemory. The problem is that the function is not supported on any OS, it is only supported in Windows 8+. 

While this may look like an isolated example, not even in windows (which is very stable) the runtime is changing and underlying APIs are not set in stone. Knowing that, think about newer platforms like Android where versions numbers would mean something is viable or not. 

Not having a cross-platform way to query the runtime is a no-no for performance and support OS that are not mature enough to absolutely not require having specific dedicated codepath depending on the runtime.  

EDIT: I know I can still get it with a Win32 call now I know that I am on windows, but that is not the point.

**Comment by Priya91** [comment]
@redknightlois Have you looked at ```RuntimeInformation.OSDescription``` API, it basically gives output from uname on Unix and RtlGetVersion on Windows.

**Comment by redknightlois** [comment]
Now I get why I couldnt find it. It is not in the RC1-update2 build. Closed.
