### ISSUE TITLE
ProjectReference -> Package Dependency: Disable SqlClient tests from package dependency build

### ISSUE THREAD

**Issue by chcosta** [dotnet/corefx#8104]
System.Data.SqlClient.Tests.csproj and System.Data.SqlClient.ManualTesting.Tests.csproj have a dependency on sni.dll which we do not currently build in the open.  

If we build packages in the open (producing new package versions), and then we attempt to restore packages against the new versions, we hit an error because the sni packages were not produced...

Errors in E:\gh\chcosta\corefx\bin/obj/generated\System.Data.SqlClient.ManualTesting.Tests\AnyOS\project.json
      Unable to resolve 'runtime.win7-x86.runtime.native.System.Data.SqlClient.sni (>= 4.0.1-rc3-24026-01)' for 'DNXCore,Version=v5.0'.
      Unable to resolve 'runtime.win7-x64.runtime.native.System.Data.SqlClient.sni (>= 4.0.1-rc3-24026-01)' for 'DNXCore,Version=v5.0'.

  Errors in E:\gh\chcosta\corefx\bin/obj/generated\System.Data.SqlClient.Tests\AnyOS\project.json
      Unable to resolve 'runtime.win7-x64.runtime.native.System.Data.SqlClient.sni (>= 4.0.1-rc3-24026-01)' for 'DNXCore,Version=v5.0'.
      Unable to resolve 'runtime.win7-x86.runtime.native.System.Data.SqlClient.sni (>= 4.0.1-rc3-24026-01)' for 'DNXCore,Version=v5.0'.

I'm going to submit a PR to disable these projects from the Project Reference to package dependency conversion for test builds so that I can unblock some build pipeline work while investigating how we want to resolve this problem.  

This issue is tracking disabling the System.Data.SqlClient test projects from the project reference to package dependency conversion process so that we can re-enable it once the underlying problem is resolved.

**Comment by joshfree** [comment]
@saurabh500

**Comment by chcosta** [comment]
We don't build sni in the corefx repo, which leads to the problem mentioned in this issue.  We are working to enable a solution.  In the meantime, @saurabh500 , if you believe there is a gap in test coverage here for RTM, please let me know.  Otherwise, I'll change the Milestone assigned for this issue.

**Comment by saurabh500** [comment]
@chcosta as long as the Sql Client tests in the Functional folder are being executed, I am good with the triage to a later milestone.

**Comment by ViktorHofer** [comment]
@chcosta @saurabh500 @karelz Is the issue still present? I don't see any dependency on sni.dll

**Comment by karelz** [comment]
cc @corivera

**Comment by saurabh500** [comment]
This issue doesn't seem to be present any more. The tests build and run fine.
@ViktorHofer There is a dependency on sni.dll for SqlClient on Windows.
