### ISSUE TITLE
Implement File enumeration over WinRT

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#8108]
We are missing an implementation of FileSystem.EnumeratePaths and FileSystem.EnumerateFileSystemInfos on WinRTFileSystem.
https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System/IO/WinRTFileSystem.cs#L231

This should be implemented by grabbing a StorageFolder for the path, then constructing a query and calling CreateFileQueryWithOptions.  

- Translate SearchOption into [FolderDepth](https://msdn.microsoft.com/en-us/library/windows/apps/windows.storage.search.queryoptions.folderdepth).
- Split the searchPattern into `name` and `extension`
- Set [ApplicationSearchFilter](https://msdn.microsoft.com/en-us/library/windows/apps/windows.storage.search.queryoptions.applicationsearchfilter.aspx) as `$"System.FileName:~\"{name}\""` using [AQS](https://msdn.microsoft.com/en-us/library/windows/apps/bb266512.aspx)
- Set [FileTypeFilter](https://msdn.microsoft.com/en-us/library/windows/apps/windows.storage.search.queryoptions.filetypefilter.aspx) as `extension`, if it exists.

**Comment by ianhays** [comment]
I've got a prototype for this but am unsure how to test the thing. It looks like I could test it out of UWP fairly well through ```msbuild /t:buildandtest /p:TargetGroup=netcore50 /p:PackageTargetFramework=netcore50``` but the multiplexing always chooses the Win32 functions.

Any tips on how to test WinRT functionality before I submit my PR?

**Comment by ericstj** [comment]
Internally we would run the tests using either the pictures or documents folder as the root and from an appx process.  Not sure corefx has the test infra to set up appx.  You can use tof and enable the enumeration tests for WinRT.

**Comment by joshfree** [comment]
@ianhays @bartonjs has been living in the UWP world for the last few days and can probably assist with setting up an environment for manual testing.

**Comment by bartonjs** [comment]
@ianhays What I did:

* Get a machine with Win10 (it's sort of required)
* VS2015 Update 2, if you're doing new setup install the Universal Windows App Development Tools (including the Windows 10 SDK)
* Create a new project: Blank App (Universal Windows)
* Optional: Learn XAML
* Write your code
* Run it on the local computer (Debug|X86)
* Decide it's happy
* Borrow a Win10 phone from the hardware checkout
* Change to Retail|ARM|Device
* F5 or Ctrl+F5.
* Play with it on the phone
* Ship it.
