### ISSUE TITLE
System.Text.Encoding and System.Text.Encoding.Extensions test duplication

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#8114]
Currently, the System.Text.Encoding and System.Text.Encoding.Extensions test projects test the same things for the same classes - I.e. ASCIIEncoding, UT7Encoding, UTF32Encoding, UTD8Encoding and UnicodeEncoding. For Latin1Encoding, System.Text.Encoding.Extensions is the only one testing this class 

This means that there is lots of duplication between the test projects. Ideally, this should be fixed.

There are some solutions:
- Remove/combine the tests in System.Text.Encoding.Extensions to the new more modern System.Text.Encoding.Tests
- Extract the current tests in System.Text.Encoding.Tests and System.Text.Encoding.Extensions to src/common/tests and reference the files in both projects
- keep as is, and duplicate tests (not an ideal solution IMO)

My preferred solution is to migrate the existing non-duplicated tests to System.Text.Encoding.Tests as that project is more modern. In terms of coverage loss, there wouldn't really be any, as the code is in mscorlib anyway. In fact, this could consolidate coverage even more by having he tests in one place. 

@tarekgh let me know what approach you think is the best and I'll work on it

**Comment by tarekgh** [comment]
I would recommend to do:

- remove any duplication first. 
- all basic encoding testing should be kept under System.Text.Encoding.Tests 
- the extra functionality provided by System.Text.Encoding.Extensions should be tested by System.Text.Encoding.Extensions without doing any duplication with System.Text.Encoding.Tests
- for common helper test classes it can got to common/tests folders
- we should consider looking at System.Text.Encoding.CodePages too before starting this refactoring to know if there is more duplication we can get rid of it. 

please let me know if this make sense to you and thanks for looking at that.

**Comment by hughbe** [comment]
Thanks - by extra functionality do you mean APIs exposed by the contract - I.e in the ref folder

**Comment by tarekgh** [comment]
> by extra functionality do you mean APIs exposed by the contract - I.e in the ref folder

exactly. thanks :-)

**Comment by joshfree** [comment]
tagging this with `grabbed by community`; @hughbe let me know if you weren't intending to pick this one up 😄

**Comment by hughbe** [comment]
yeah I was, thanks for doing that @joshfree

**Comment by hughbe** [comment]
Just while we're at it - @tarekgh do you have any areas of System.Text.Encoding that I can work on after the cleanup? I wouldn't mind having some direct suggestions :)

**Comment by tarekgh** [comment]
@hughbe, first I would to thank you for your effort and willing to help more. 
I would suggest if you can start moving to other areas. one area that I am feeling is important and may need adding/cleaning tests is System.Console and in same time it is related to System.Text.Encoding too. I can suggest more if you are not interested in such area.

**Comment by hughbe** [comment]
brill, I'll take a look!

**Comment by hughbe** [comment]
Also, @joshfree I notice you're in charge of issues in the repo. May I suggest that we take greater advantage of the *up-for-grabs* tag, as this could encourage contributions and help me and others target work that is somewhat menial, letting the Microsoft folks make more impactful changes.

Perhaps suggesting that Microsoft devs create an issue and mark it as up-for-grabs whenever they think something like "oh, this could be improved, maybe someday I'll get round to it" (hopefully this won't lead to too many issues being created though)

**Comment by hughbe** [comment]
> we should consider looking at System.Text.Encoding.CodePages too before starting this refactoring to know if there is more duplication we can get rid of it.

I took a look, but unfortunately it seems that most of the tests there perform roundtrips to test GetChars and GetBytes.
Although I do think it would be a good idea to plug in NegativeEncodingTests into that project at some point

**Comment by tarekgh** [comment]
@hughbe it will be good if we add same coverage of testing as we did for other encodings. Also we may need to add a test for custom encoding provider too. I mean create your own encoding for example, encoding which convert sequence of bytes to emoji symbols and roundtrip it.

**Comment by joshfree** [comment]
> May I suggest that we take greater advantage of the up-for-grabs tag,

Thank you for your contributions and also thanks for the suggestion on issue labeling; we'll use the `up for grabs` label as much as possible.  @hughbe in addition to the existing ~120 `up for grabs` issues in corefx, there is also ~560 `Future` bugs that you can check out.  Some of them may be of interest.  Is there a particular area of corefx that you're interested in contributing to?

**Comment by hughbe** [comment]
Thanks @joshfree. My slight confusion with the up-for-grabs tag is the number of API-proposals that are tagged as up-for-grabs - is this deliberate?
I'll take a look and get back to you if necessary!

**Comment by joshfree** [comment]
@hughbe See this doc https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md for more details on the API review process and the `api-needs-work` label; for the issues you're seeing it means they've been assigned to an owner (Step-2) but probably no design discussion (Step-3) has happened yet.  If you see an issue where a design discussion (Step-3) has happened but there's been no update then feel free to ping the assignee for next steps.
