### ISSUE TITLE
Refactor  SafeFreeCredentials class

### ISSUE THREAD

**Issue by kapilash** [dotnet/corefx#8115]
Tracking issue to fix the following code smells [``SafeFreeCredentials`](https://github.com/dotnet/corefx/blob/master/src/Common/src/Interop/Unix/libssl/SecuritySafeHandles.cs#L62) class:

~~\* As pointed out in [the PR comments of #6469](https://github.com/dotnet/corefx/pull/6469#discussion_r56659315),  this class needs to be split up into two separate classes~~ (via #8452)
- Rework PAL to remove non- SafeHandle SafeHandles. (Source of this observation was [the PR Comments of #6469](https://github.com/dotnet/corefx/pull/6469#discussion_r56658414) )

**Comment by kapilash** [comment]
First part is done via #8452.  ```libssl``` has also been cleaned.

The second part , namely, reworking PAL to eliminate non-safe handle, safe handles is an involved change and considering the impact,  is a riskier change to get into RTM at this point.
So moving the milestone of the bug to 1.1.0

**Comment by Priya91** [comment]
It's unclear what remaining work is left here. @kapilash Can you elaborate on the next steps. Thanks!

**Comment by Priya91** [comment]
Closing due to lack of response.
