### ISSUE TITLE
NegotiateStreamTest For Unix relies on ManualSkip

### ISSUE THREAD

**Issue by kapilash** [dotnet/corefx#8117]
The current situation with running functional tests on Linux for `NegotiateStream` is suboptimal. Instead of using a `ConditionalFlag`, each test [checks if the installation is successful or not](https://github.com/dotnet/corefx/blob/master/src/System.Net.Security/tests/FunctionalTests/NegotiateStreamTestForUnix.cs#L155) and bails out if it wasn't. This means that we cannot rely on the output of xunit to know if the test was successful or if it was skipped.

This was written this way due to following orthogonal constraints:
1. Unlike other tests, the NegotiateStreamTests were expected to download and install the prereqs (This constraint is related to the infra team).
2. When the tests are run on a dev machine, the installation should be done only if the developer chooses to do so.
3. If the developer does not choose to download, install and configure KDC (presumably because he/she is not testing negotiatestream) the outerloop should not fail. 
4. If the tests install anything, we need to uninstall them as well.

In order to achieve 1 and 4, we need to use the XUnit's disposable fixture mechanism. 
 But XUnit can only guarantee that the fixture instance is created before the any of the test is run. There are no documented relative ordering of 
- fixture instance creation
- filtering of test cases

Thus making it really tricky to achieve all the four requirements.

**Comment by davidsh** [comment]
Tracking this with #24707
