### ISSUE TITLE
Implement async I/O support in System.IO.FileSystem/Pipes on Unix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#812]
System.IO.FileSystem has an initial implementation on Unix, but it doesn't yet have special support for async I/O (right now the async operations just rely on the base Stream type's implementation, which will schedule a work item to invoke the synchronous implementations).

**Comment by stephentoub** [comment]
After further investigation, there doesn't seem to be much more we can do here for FileStream.  io_submit would require restrictions on the FileStream (e.g. requiring O_DIRECT) and is only available on Linux.  epoll doesn't work with files.  And aio would essentially provide the same solution we already employ, offloading the synchronous call to another thread.

**Comment by sokket** [comment]
Okay cool, if this isn't actionable anymore then I'll close the issue. Thanks Stephen!
