### ISSUE TITLE
Missing DebuggingFlags on DebuggableAttribute

### ISSUE THREAD

**Issue by manu-silicon** [dotnet/corefx#8141]
Are there plan to add `DebuggingFlags` to System.Diagnostics.DebuggableAttribute? Especially since the constructor takes them as arguments, it seems natural that one could query it?

**Comment by AtsushiKan** [comment]
To summarize, the desktop CLR **DebuggableAttribute** class has a **DebuggingFlags** property that retrieves the debugging mode passed to the **DebuggableAttribute** constructor.

```
    public sealed class DebuggableAttribute : Attribute {
        public DebuggableAttribute(DebuggableAttribute.DebuggingModes modes);
        public DebuggableAttribute.DebuggingModes DebuggingFlags { get; }
    }
```
In Core, the **DebuggingFlags** property has been taken out.

The ask is to add it back (or to have an explanation - any specific reason not to have this?)

Use case: Reflection code browsing over metadata can more conveniently retrieve the debugging flags of these attributes.

**Comment by nguerrera** [comment]
API LGTM

**Comment by weshaggard** [comment]
@KrzysztofCwalina @terrajobst @danmosemsft 

I no issues with exposing this. However given our current direction can you please extend this to include all the APIs on DebuggableAttribute and DebuggingModes.

**Comment by terrajobst** [comment]
Agreed with @weshaggard. Also, I bet the API is already included in our TODO.

**Comment by manu-silicon** [comment]
Thanks for fixing this!
