### ISSUE TITLE
System.IO.Tests.CreatedTests.FileSystemWatcher_Created_Negative is failing on OSX

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#8154]
This has been failing periodically in some runs that I have looked at. For example:

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/463/consoleFull
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/457/testReport/junit/System.IO.Tests/CreatedTests/FileSystemWatcher_Created_Negative/
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/455/testReport/junit/System.IO.Tests/CreatedTests/FileSystemWatcher_Created_Negative/

**Comment by joshfree** [comment]
cc: @sokket

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/570/

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/579/

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/581/

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/589/

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_release_prtest/566/

**Comment by JonHanna** [comment]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/597/

**Comment by JonHanna** [comment]
Had it happen again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_release_prtest/669/

**Comment by ianhays** [comment]
This is resolved in #8231
