### ISSUE TITLE
Cookies should use the Value property as opposed to field in constructor

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#8171]
This behavior seems somewhat unintuitive:

```cs
public static void Main()
{
	var cookie = new Cookie("name", null);
	Console.WriteLine(cookie.Value == null); // -> True
	cookie.Value = null;
	Console.WriteLine(cookie.Value.Length == 0); // -> True
}
```

The fix would be to change [this](https://github.com/dotnet/corefx/blob/master/src/System.Net.Primitives/src/System/Net/Cookie.cs#L106) line of `Cookie` to use the value property instead of field to set the value, since the property defaults to `string.Empty` if the parameter is null.

cc @davidsh

**Comment by hughbe** [comment]
Dupe/similar to #7459

**Comment by davidsh** [comment]
I've researched this issue.  We've never thrown an exception if the `value` is null.  We always have converted it to `string.Empty`.  The default is actually `string.Empty` if you call this constructor overload:

```c#
    var cookie = new Cookie("name");
    Console.WriteLine(cookie.Value.Length == 0); // -> True
```

I also agree with #7459 that we need to fix the documentation.

In the case of this issue, doing the change as you suggest is the correct fix for this edge case.

**Comment by jamesqo** [comment]
@davidsh Okay then, I'll open a pull request in a few hours. Will cc you and @hughbe.

**Comment by CIPop** [comment]
LGTM (with one request to have a comment added that clearly marks the CoreFX/Desktop behavior difference).

regarding the netfx-port-consider:

>  Fixing this would cause breaking changes - something the system.net team dislike - though

I agree with @davidsh: it's less likely for an application to have taken a dependency on setting a certain value to null. Still, this requires app-compat council approval before getting ported back to Desktop.

**Comment by CIPop** [comment]
Added the LGTM to the wrong conversation...

**Comment by davidsh** [comment]
FWIW, applications that might have passed in null to the constructor will end up with a Cookie object in an inconsistent state and it will fail later on.

We will evaluate this bug for porting to Desktop via the 'netfx-port-consider' process.

**Comment by hughbe** [comment]
Could the community at some point have some clarification as to the 'netfx-port-consider' process (not immensely important but good stuff to know)

**Comment by davidsh** [comment]
Basically, the label:
![image](https://cloud.githubusercontent.com/assets/7684835/15000982/a64d2d2a-1148-11e6-97c0-f7fc8511f163.png)

just helps with our internal process by opening up a related bug in our internal database for .NET Framework.  Then we study the potential source changes with a large review team and decide if it carries app-compat risk before accepting the change into .NET Framework.
