### ISSUE TITLE
Ubuntu build instructions are incorrect

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#8174]
I'm following the instructions [here](https://github.com/dotnet/corefx/blob/master/Documentation/building/unix-instructions.md) on a fresh Ubuntu 15.10 machine.

However, I've had a bit of a 'mare trying to get it working
I'll list the problems I'm having in chronological order
### Getting prerequisite packages
- Can't find `libicu52`: fixed by using `libicu55`

### Running build.sh
- CMake error: `Could not find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)`:
 fixed by `sudo apt-get install zlib1g-dev`

### Rerunning build.sh
```CMake Error at System.Net.Security.Native/CMakeLists.txt:15 (message):
  Cannot find libgssapi_krb5 and System.Net.Security.Native cannot build
  without it.  Try installing libkrb5-dev (or the appropriate package for
  your platform)```: fixed by `sudo apt-get install libkrb5-dev`

### Rerunning build.sh
```Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
  OPENSSL_INCLUDE_DIR)```: fixed by `sudo apt-get install libssl-dev`

## Rerunning build.sh
```CMake Error at System.IO.Compression.Native/CMakeLists.txt:9 (add_library):
  Cannot find source file:

    /home/hugh/corefx/bin/obj/version.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error at System.Native/CMakeLists.txt:30 (add_library):
  Cannot find source file:

    /home/hugh/corefx/bin/obj/version.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error at System.Net.Http.Native/CMakeLists.txt:18 (add_library):
  Cannot find source file:

    /home/hugh/corefx/bin/obj/version.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error at System.Net.Security.Native/CMakeLists.txt:23 (add_library):
  Cannot find source file:

    /home/hugh/corefx/bin/obj/version.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error at System.Security.Cryptography.Native/CMakeLists.txt:41 (add_library):
  Cannot find source file:

    /home/hugh/corefx/bin/obj/version.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: System.IO.Compression.Native
CMake Error: Cannot determine link language for target "System.IO.Compression.Native".
CMake Error: CMake can not determine linker language for target: System.Native
CMake Error: Cannot determine link language for target "System.Native".
CMake Error: Cannot determine link language for target "System.Native-Static".
CMake Error: CMake can not determine linker language for target: System.Native-Static
CMake Error: CMake can not determine linker language for target: System.Net.Http.Native
CMake Error: Cannot determine link language for target "System.Net.Http.Native".
CMake Error: CMake can not determine linker language for target: System.Net.Security.Native
CMake Error: Cannot determine link language for target "System.Net.Security.Native".
CMake Error: CMake can not determine linker language for target: System.Security.Cryptography.Native
CMake Error: Cannot determine link language for target "System.Security.Cryptography.Native".
-- Generating done
```
Fixed by running `./build.sh native`

### Final rerun of build.sh
```
Setting up directories for build
Checking pre-requisites...
Tools are already initialized
./build.sh: line 91: /home/hugh/corefx/Tools/corerun: No such file or directory
Commencing build of corefx native components for Linux.x64.Debug
Invoking cmake with arguments: "/home/hugh/corefx/src/Native" DEBUG 
No CMake extra Args specified
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hugh/corefx/bin/obj/Linux.x64.Debug/Native
Executing make install -j 5
[  8%] Built target System.Net.Http.Native
[ 11%] [ 37%] Built target System.Net.Security.Native
Built target System.Native
[ 40%] Built target System.IO.Compression.Native
[ 66%] Built target System.Native-Static
[100%] Built target System.Security.Cryptography.Native
Install the project...
-- Install configuration: "DEBUG"
-- Up-to-date: /home/hugh/corefx/bin/Linux.x64.Debug/Native/./System.IO.Compression.Native.so
-- Up-to-date: /home/hugh/corefx/bin/Linux.x64.Debug/Native/./System.Native.so
-- Up-to-date: /home/hugh/corefx/bin/Linux.x64.Debug/Native/./System.Native.a
-- Up-to-date: /home/hugh/corefx/bin/Linux.x64.Debug/Native/./System.Net.Http.Native.so
-- Up-to-date: /home/hugh/corefx/bin/Linux.x64.Debug/Native/./System.Net.Security.Native.so
-- Up-to-date: /home/hugh/corefx/bin/Linux.x64.Debug/Native/./System.Security.Cryptography.Native.so
CoreFX native components successfully built.
Product binaries are available at /home/hugh/corefx/bin/Linux.x64.Debug/Native
Tools are already initialized
./build.sh: line 105: /home/hugh/corefx/Tools/corerun: No such file or directory

tail: cannot open ‘/home/hugh/corefx/msbuild.log’ for reading: No such file or directory
Build Exit Code = 127
```

### Question
Gah! I give up! Seems like corefx is harder to build on Ubuntu than the documentation suggests.
From the get go the packages were incorrect and prerequisites aren't mentioned. And then it all goes wrong with a file not found error!
Surely I must be doing something wrong? Or maybe not.

I've tried this on a new Ubuntu 16 LTS VM too and had the same errors - any ideas would be appreciated. Sorry for dumping logs!

**Comment by joshfree** [comment]
Related https://github.com/dotnet/corefx/issues/8136

**Comment by hughbe** [comment]
These are following the (I thought new) instructions in #8109

**Comment by ellismg** [comment]
The documents were written with Ubuntu 14.04 in mind, which is the only version can build CoreFX (both managed and native).  The copy/paste-able instructions in #8109 were written for that distro specifically and some of the package name changes are due to packages being updated.

I expect in a few weeks we will also support building everything on Ubuntu 16.04. It's less clear we will support building on Ubuntu 15.10 in a reasonable timeframe.

If you want to get managed and native builds working on Linux now, I recommend that you use Ubuntu 14.04.

**Comment by hughbe** [comment]
Thanks @ellismj good to know.
Just one question: is there a way to build and test an individual project on Linux? I know you can with `msbuild /T:BuildAndTest` on Windows

**Comment by ellismg** [comment]
@hughbe Once you are on Ubuntu 14.04, you should be able to run `init-tools.sh` in the root without an error.  Once that's complete, you can invoke msbuild with `<path-to-repo-root>/Tools/corerun <path-to-repo-root>/Tools/MSBuild.exe`.

I usually alias the above to just `msbuild` in my shell and then you can go to any project and `msbuild /t:BuildAndTest` like you would on Windows.

**Comment by mellinoe** [comment]
> I usually alias the above to just msbuild in my shell and then you can go to any project and msbuild /t:BuildAndTest like you would on Windows.

:+1:

**Comment by hughbe** [comment]
@mellinoe that works for me, but I get some build errors: all of them say `SR does not contain a definition for ...`

**Comment by mellinoe** [comment]
@hughbe Could you clarify if you are building on 14.04, or 15.10? Also, do you see those same kinds of errors when running `build.sh`, or is it just when using msbuild directly?

**Comment by hughbe** [comment]
Sorry, 14.04 - they were only with msbuild. However, I ran `clean.sh` and used `msbuild` again and it all worked. If there are any future problems I'll diagnose further!

**Comment by ellismg** [comment]
Looks like everything is working as expected (and other folks have also reported success building on Ubuntu 14.04) so I'm going to close this up.
