### ISSUE TITLE
System.Diagnostics.Tracing package version 4.1.0 contains version 4.0.20 reference assembly

### ISSUE THREAD

**Issue by ericeil** [dotnet/corefx#8182]
I am trying to reference System.Diagnostics.Tracing version 4.1.0 from System.Net.Sockets, so I can use the new EventCounter type.  I changed the project.json in src\System.Net.Sockets\src\win to include:

```
        "System.Diagnostics.Tracing": "4.1.0-rc3-24026-00",
```

However, the build complains that EventCounter doesn't exist in any referenced assembly.

If I open up the reference assembly:

```
packages/System.Diagnostics.Tracing\4.1.0-rc3-24026-00\ref\netstandard1.3\System.Diagnostics.Tracing.dll
```

...in ILSpy, I see that the assembly version is *4.0.20.00," and that indeed it does not contain the EventCounter type.

Why does the 4.1.0 package contain the 4.0.20 reference assembly?

@ericstj, @vancem

**Comment by joshfree** [comment]
@chcosta can you take a look at this one?

**Comment by ericeil** [comment]
cc: @cshung

**Comment by chcosta** [comment]
The 4.0.20 reference assembly is used for netstandard1.3.  NetStandard 1.5 contains the 4.1.0 reference assembly.

'''
packages/System.Diagnostics.Tracing\4.1.0-rc3-24026-00\ref\netstandard1.5\System.Diagnostics.Tracing.dll
'''

**Comment by ericeil** [comment]
Ok, so this is because System.Net.Sockets specifies the dependency under the "netstandard1.3" framework?

https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/win/project.json

What change do I need to make to get the 4.1.0 reference assembly?

**Comment by vancem** [comment]
See https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md on the NetStandard docs.    NetStandard 1.3 corresponds to V4.6   

Note that in this case, it seems like it would be useful to take a direct reference to the necessary DLL (that is directly reference System.Diagnostics.Tracing. V4.1  because that is the only piece that you need that needs to be super-new.

**Comment by vancem** [comment]
My expectations is that you would add the following

    "dependencies": { 
         "System.Diagnostics.Tracing": "4.1.0",        
    },

As a sibling to the 'frameworks' property specifying netstanard 1.3.   My expectation is that this would 'promote' the need for a newer version of this particular DLL. 

As an aside, perhaps Eric St John can tell you more about what it means for a framework to have a 'dependencies' field as is the case for https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/win/project.json
I don't really know what that means...

**Comment by ericeil** [comment]
Moving the dependency out of the "frameworks" property does not appear to have any effect; the build still references the netstandard1.3 reference assembly.

**Comment by mellinoe** [comment]
If netstandard1.3 doesn't support the type, and you still want to use it, then you need to raise the target to netstandard1.5. Otherwise, the library would not actually be usable by platforms supporting netstandard1.3 (since it doesn't support the type...).

**Comment by ericeil** [comment]
Thanks, I think I'm starting to wrap my head around this now. :). Closing this while I work out what to do...
