### ISSUE TITLE
Console.Write() doesn't show output until a newline

### ISSUE THREAD

**Issue by omajid** [dotnet/corefx#8183]
On RHEL 7, `Console.Write()`'s output does not get displayed until a newline is used (or the program exits).

If you run the following application, you don't see anything as the output until 10 seconds have passed. Then all of "HelloWorld!" appears at once.

     public static void Main(string[] args)
     {
         Console.Write("Hello World");
         Console.Out.Flush();
         Task.Delay(10000).Wait();
         Console.WriteLine("!");
     }

Console applications that do input/output may use a style like the following:

    public static void Main(string[] args)
    {
        Console.Write("Name: ");
        var name = Console.ReadLine();
        Console.WriteLine("Your name is '" + name + "'.");
    }

This doesn't work for me. You get no output at all at first. If you type in something (say "Foo") and hit ENTER, then you see all of the output at once:

    Name: Foo
    Your name is 'Foo'.

If you don't hit enter, then it seems like the application has hung. A `Console.Out.Flush()` doesn't fix this, as in the following:

    public static void Main(string[] args)
    {
        Console.Write("Name: ");
        Console.Out.Flush();
        var name = Console.ReadLine();
        Console.WriteLine("Your name is '" + name + "'.");
    }

I ran all the test cases while ssh'ed into the RHEL 7 VM.

    $ dotnet --version
    1.0.0-rc2-002538

**Comment by stephentoub** [comment]
I believe this is an issue with the dotnet run command rather than with corefx and System.Console. Do you see the same issue if you compile and then separately execute the compiled app?

**Comment by omajid** [comment]
I have the same issue if I do `dotnet build` followed by `dotnet run`. Is there some other way to separately execute the compiled app?

**Comment by stephentoub** [comment]
> Is there some other way to separately execute the compiled app?

Yes, dotnet build creates an executable you can just execute (not with dotnet run). See overview at https://github.com/dotnet/cli/blob/rel/1.0.0/README.md .

**Comment by omajid** [comment]
The README says:

> This will drop a binary in ./bin/[configuration]/[framework]/[rid]/[binary name] that you can just run.

I can't find a native binary. Is my build broken somehow?

    $ dotnet build
    Project console-application (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
    Compiling console-application for .NETCoreApp,Version=v1.0
    /home/omajid/dotnet-tests/console-application/project.json(3,26): warning DOTNET1015: The 'compilationOptions' option is deprecated. Use 'buildOptions' instead.
    /home/omajid/dotnet-tests/console-application/project.json(7,31): warning NU1007: Dependency specified was Microsoft.NETCore.App >= 1.0.0-rc2-002538 but ended up with Microsoft.NETCore.App 1.0.0-rc2-23929.
    
    Compilation succeeded.
        2 Warning(s)
        0 Error(s)
    
    Time elapsed 00:00:05.0513219
    
    $ dotnet build --native
    Specify --help for a list of available options and commands.
    Unrecognized option '--native'
    $ find
    .
    ./project.json
    ./Program.cs
    ./project.lock.json
    ./bin
    ./bin/Debug
    ./bin/Debug/netcoreapp1.0
    ./bin/Debug/netcoreapp1.0/console-application.pdb
    ./bin/Debug/netcoreapp1.0/console-application.dll
    ./bin/Debug/netcoreapp1.0/console-application.deps.json
    ./bin/Debug/netcoreapp1.0/console-application.runtimeconfig.json
    ./bin/Debug/netcoreapp1.0/console-application.runtimeconfig.dev.json
    ./obj
    ./obj/Debug
    ./obj/Debug/netcoreapp1.0
    ./obj/Debug/netcoreapp1.0/dotnet-compile.rsp
    ./obj/Debug/netcoreapp1.0/dotnet-compile.assemblyinfo.cs
    ./obj/Debug/netcoreapp1.0/dotnet-compile-csc.rsp
    ./obj/Debug/netcoreapp1.0/.SDKVersion
    ./obj/Debug/netcoreapp1.0/.IncrementalCache
    $ ./bin/Debug/netcoreapp1.0/console-application.pdb
    bash: ./bin/Debug/netcoreapp1.0/console-application.pdb: cannot execute binary file
    $ ./bin/Debug/netcoreapp1.0/console-application.dll
    bash: ./bin/Debug/netcoreapp1.0/console-application.dll: cannot execute binary file

**Comment by omajid** [comment]
@ellismg suggested `dotnet <your-app-name>.dll` and that doesn't show the problem.

**Comment by ellismg** [comment]
Moved this one as well

**Comment by eerhardt** [comment]
@omajid - `dotnet <your-app-name>.dll` is the right way to run it outside of `dotnet run`.  If you `dotnet publish` your app there will be an executable created `<your-app-name>` in the output directory, which you can run as well without using `dotnet`.

I commented on the CLI issue why this happens.  This is a CLI issue, as @ellismg pointed out.

**Comment by omajid** [comment]
Thanks for the clarification and moving the bug!
