### ISSUE TITLE
Console.ReadLine() doesn't display input

### ISSUE THREAD

**Issue by omajid** [dotnet/corefx#8184]
On RHEL 7, when I run the following program (using `dotnet run`) and type some input, I don't see what I am typing until I hit ENTER. Then everything I have typed appears at once:

    public static void Main(string[] args)
    {
        Console.WriteLine("Name: ");
        var name = Console.ReadLine();
    }

    $ dotnet --version
    1.0.0-rc2-002538

**Comment by stephentoub** [comment]
I believe this is an issue with the dotnet run command rather than with corefx and System.Console. Do you see the same issue if you compile and then separately execute the compiled app?

**Comment by ellismg** [comment]
You can do this by moving into the `bin` directory that is produced by `dotnet build` and invoking `dotnet <your-app-name>.dll`

**Comment by omajid** [comment]
Aha. Yes, running via `dotnet <your-app-name>.dll` doesn't show the problem!

**Comment by ellismg** [comment]
(Opened a tracking issue in CLI since this is specific to `dotnet run`).
