### ISSUE TITLE
Are Query Notifications on the roadmap?

### ISSUE THREAD

**Issue by rposener** [dotnet/corefx#8188]
It seems the System.Data.SqlClient does not include any of the query notification (SqlNotification or SqlDependency) classes.  is this on the roadmap to be added?

**Comment by alikalfaoglu** [comment]
We have implemented missing pieces (notification & dependency) locally in our project, shall we contribute?

**Comment by ViktorHofer** [comment]
@saurabh500 @YoungGah It seems we still haven't ported them to corefx. Any reason why? I see them supported in Xamarin and Desktop: https://apisof.net/catalog/System.Data.SqlClient.SqlDependency

**Comment by karelz** [comment]
@corivera any insight here?
@stephentoub @weshaggard @danmosemsft?

**Comment by akoeplinger** [comment]
@ViktorHofer FYI it's just a stub in Mono/Xamarin at the moment: [SqlDependency.cs](https://github.com/mono/mono/blob/462834e6ea925fbc69711fb4ffc6f8b22ab92de8/mcs/class/System.Data/System.Data.SqlClient/SqlDependency.cs)

**Comment by ViktorHofer** [comment]
@karelz Moving this to future as we reached feature freeze...

**Comment by karelz** [comment]
I'd like area experts & owners to make the decision. While we are past feature complete, there are options like DCRs, etc. I would prefer to focus on doing the right thing for the customers rather than process.

That said, given they are stubbed out in Xamarin, it feels more like Future to me as well, but I don't have enough background in the space to make the call ...

**Comment by corivera** [comment]
We currently don't have any plans for working on query notifications.

**Comment by grahamehorner** [comment]
Is there any mileage in possibility providing a work around until officially supported, this is a blocker for us moving to asp.net core as we aren't able to invalidate cached items as notifications was used as the trigger this

**Comment by saurabh500** [comment]
Query notifications via SqlDependency and related APIs is a feature we have on the backlog. However we couldn't get it into 2.0 because we didn't have the bandwidth. 
We will be looking to port this feature in Future iterations.

**Comment by saurabh500** [comment]
Related issue https://github.com/dotnet/corefx/issues/17833

**Comment by maike9** [comment]
This is a roadblock to moving to .net core for me too.

**Comment by saurabh500** [comment]
What is your scenario fire query notification?

**Comment by corivera** [comment]
Query notification support was added in https://github.com/dotnet/corefx/pull/20708

**Comment by ViktorHofer** [comment]
... and will be available with the .NET Core 2.1 and the next version of UWP. Right @corivera ?

**Comment by corivera** [comment]
Yep

**Comment by ChristopherRobinSuperStar** [comment]
@corivera Is it possible to use it with action attribute in asp net core 2.1?
Before in asp net mvc it was:
```
[OutputCache(Duration = Int32.MaxValue, SqlDependency = "DBNAME:DEPENDENCY_TABLE_NAME", Location = System.Web.UI.OutputCacheLocation.Server)]
public ActionResult Index()
{
}
```

**Comment by karelz** [comment]
cc @keeratsingh @David-Engel @AfsanehR
