### ISSUE TITLE
Should ValueTuple's hashing functions could be separated into a new file?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#8193]
Right now, `ValueTuple` has a [bunch of code](https://github.com/dotnet/corefx/blob/master/src/System.ValueTuple/src/System/ValueTuple/ValueTuple.cs#L245-L279) dedicated to combining hash codes. Maybe this could be separated out into a new file in `Common` (similarly to what was proposed in #8034) to help reduce the LOC in the file? I'm sure a hash helper class would also be useful in certain other scenarios, e.g. #8163.

cc @jcouv

**Comment by jcouv** [comment]
On a related note, the hashing and hash combining functions of `System.Tuple` and `System.ValueTuple` seem rather weak. If that code is going to be moved in common, it should probably be stronger.

**Comment by jamesqo** [comment]
@jcouv How so? It uses the same algorithm as [here](http://stackoverflow.com/a/263416), which is continually multiplying the hash by a prime (in this case `33`, since `(i << 5) + i` is equivalent to that in unchecked mode) and then XORing it with another hash, right?

**Comment by jcouv** [comment]
Adding @VSadov and @dsyme for feedback on the hash function. For context, this came up in the compiler [review of ValueTuple](https://github.com/dotnet/roslyn/pull/9809#discussion_r56749491).

**Comment by VSadov** [comment]
We are talking about a hash combiner like
```C#
internal static int CombineHashCodes(int h1, int h2)
{
          return (((h1 << 5) + h1) ^ h2);
}
```

If you notice, if  h1 and h2 are sufficiently large,   ```h1 << 5```  becomes 0, and the whole deal becomes just  ```h1 ^ h2```

That is 1) symmetrical and 2) will result in 0 if  h1 == h2.

Being a variant of DJB, there are easily discoverable funnels - for example (0x00, 0x21) will collide with (0x01, 0x00)


I think we can find a combiner that is more robust.

**Comment by jamesqo** [comment]
@VSadov Ah good point, I hadn't noticed that. Perhaps we should also add the upper 5 bits of `h1` beforing XORing it, like so:

```cs
return ((h1 << 5) + h1 + (h1 >> 27)) ^ h2;
```

This is what `String` [does for its (non-randomized) hash code](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/String.cs#L866-L867) on 32-bit platforms.

**Comment by jamesqo** [comment]
Closing, the other PR was merged.
