### ISSUE TITLE
Should we make the native shims 1:1 with the managed assemblies consuming them?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#8211]
Today we only have a few shims, e.g. System.Native.so, and some of these shims are shared by multiple managed assemblies.  In some cases such sharing is important because the native shim does initialization that should only be done once, e.g. supplying to OpenSSL the locks to be used.  But most cases don't require such sharing, and using the same shim for multiple managed assemblies makes it harder to independently version and ship the managed assemblies.  Prior to 1.0.0-rtm, we should consider breaking these native shims apart such that they're 1:1 with the assemblies that use them, e.g. System.Diagnostics.Process.Native.so used by System.Diagnostics.Process.dll, and creating shared shims only for the minimal logic that does in fact need to be used as a single shared instance by multiple assemblies, e.g. library initialization.

**Comment by stephentoub** [comment]
cc: @ellismg, @nguerrera, @sokket, @eerhardt, @bartonjs

**Comment by eerhardt** [comment]
What do we do about functions that are shared by multiple managed assemblies?  Do we put them in both native shim assemblies?  ex. SystemNative_Open.  Or do we continue having that function exposed from just one native shim assembly?

**Comment by stephentoub** [comment]
I'm suggesting they'd share source but be compiled into each binary that needs them exported.

**Comment by eerhardt** [comment]
If they were in different assemblies, would they have different prefixes in their names?

ex. SystemNative_Open is in "SystemNative.so".

Or would we treat the prefix more like a namespace?

I think I like the idea, I am just trying to work through it fully so I understand it.

**Comment by stephentoub** [comment]
> would they have different prefixes in their names?

Yes, for the AOT scenarios in particular, we'd need to still make all names unique, so when compiling Open into System.Diagnostics.Process.Native.so, it'd be something like SystemDiagnosticsProcess_Open, and when compiling it into System.IO.FileSystem.Native.so, it'd be something like SystemIOFileSystem_Open, at least in my mind.

**Comment by stephentoub** [comment]
cc: @jkotas, @janvorli for their opinions as well

**Comment by jkotas** [comment]
I do not think that having the shims per managed .dll is good idea. I think that the logical grouping as it exists today is the right tradeoff.

**Comment by stephentoub** [comment]
> I do not think that having the shims per managed .dll is good idea. I think that the logical grouping as it exists today is the right tradeoff.

Thanks, Jan.  Can you elaborate a bit on why?

**Comment by janvorli** [comment]
@stephentoub it seem that besides the System.Native.so, the other shims already correspond 1:1 to managed assemblies, am I right? 
As for the System.Native.so, I can see that about 18 managed assemblies are using that, so these would need to be versioned together. Now splitting the System.Native.so into 18 smaller shared libraries look like too much to me - it would mean longer loading time and larger memory footprint.
So if we opted for splitting that shim, I would suggest using some larger granularity. For example, System.IO.Native.so, System.Diagnostics.Native.so, System.Net.Native.so and then System.Native.so with the rest.

**Comment by jkotas** [comment]
> Can you elaborate a bit on why?

- I feel that we are trying to be too much componentized at the lowest levels of the stack and there is not enough value in it.
- We would still need some shims that are shared across .dlls as you have mentioned for various reasons.
- Having many little .so is not free.

I understand that there is a price we will pay for sharing the shim - we need to maintain backward compatibility for it. I do not think it should be a problem. The churn should be pretty minimal. In worst case, we can bump the version number on System.Native.so.

If there is stuff in System.Native.so today that we think should better be separate, I would be fine with splitting System.Native.so into 2 or 3 smaller ones; but not into 18 - I think it is too much.

> it seem that besides the System.Native.so, the other shims already correspond 1:1 to managed assemblies

I do not think it is the case.

**Comment by nguerrera** [comment]
I agree with @jkotas and @janvorli. 

It is not really the case that the ~18 assemblies that use System.Native.so must absolutely version together. The only requirement is that increasing stable versions of System.Native.so are compatible with earlier stable versions. 

Since these functions are small and mostly correspond 1:1 to Unix low-level API, I don't think they will change very much. Generally, evolving C-style native API in a backwards-compatible way is easier than managed/OOP API. We can always have SystemNative_Open2(..), etc. There is no concern here about aesthetics, developer confusion, exchange types, etc. etc. Plus, if our hands were ever really tied, we could put a version in the file name so that they can live SxS in the same deployment if absolutely necessary.

**Comment by stephentoub** [comment]
Ok, thanks for the discussion.
