### ISSUE TITLE
Some csproj files still use DNXCore,Version=5.0 as the moniker

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#8214]
The document for .NET Platform Standard says that `dnxcore` is deprecated, however it's still being used in a couple of `.csproj` files: https://github.com/dotnet/corefx/search?l=xml&q=DNXCore&utf8=%E2%9C%93 Not sure if this is intentional or not.

cc @ericstj

**Comment by ericstj** [comment]
Yeah, we should clean this up.  It isn't a functional defect nor does it impact packaging, thus I've removed the tag.  Many more projects still use this (tests) and that needs to be cleaned up in buildtools and CoreFx.
