### ISSUE TITLE
Array.LongLength property missing

### ISSUE THREAD

**Issue by AArnott** [dotnet/corefx#8216]
I'm [porting libgit2sharp to portable](https://github.com/libgit2/libgit2sharp/issues/1293) and the lack of `LongLength` on arrays forces me to resort to `Length`, which will break the library in writing objects larger than 2GB in size. The wisdom of 2GB objects in git aside, this seems like a sad limitation if CoreCLR itself supports 64-bit processes.

**Comment by ellismg** [comment]
FWIW, Presently, the runtime does not allow an array to contain more than `int.MaxValue` elements (and the [actual limit is slightly smaller](https://msdn.microsoft.com/en-us/library/hh285054(v=vs.110).aspx).)

So even if this was exposed, you could write the code you'd want, but you wouldn't get the behavior you desire.

**Comment by AArnott** [comment]
Oh, interesting. Then in that case, removing a pointless API sounds good. 
But is that limitation only in CoreCLR, or does .NET Framework share it?
