### ISSUE TITLE
Attribute.GetCustomAttributes does not resepct 'inherit' flag for non-RuntimeTypes.

### ISSUE THREAD

**Issue by alphaleonis** [dotnet/corefx#8220]
The method `GetCustomAttributes` on `PropertyInfo` and `EventInfo` ignores the `inherit` parameter, which is mentioned in the documentation. Instead one is supposed to use the `Attribute.GetCustomAttributes` method to get attributes in the inheritance chain.  The problem is that this method only walks the inheritance chain if the type of the `PropertyInfo` (or rather the `MethodInfo` returned from `GetAccessors()` in the case of a property) is an instance of `RuntimePropertyInfo` (or `RuntimeMethodInfo`).

This means that for any custom implementation of a `MemberInfo`, such as those provided from `CustomReflectionContext`, there is no way to get the attributes in the inheritance chain in a transparent way, regardless of the implementation of the `MemberInfo` in question.

Suggest that the implementation of `Attribute.GetCustomAttributes()` is changed so that it works regardless of the underlying implementation of the `MemberInfo` provided.

A sample program illustrating the issue:

```c#
   [AttributeUsage(AttributeTargets.All, Inherited = true)]
   public sealed class TestAttribute : Attribute
   {
   }

   class A
   {
      [Test]
      public virtual object MyProp { get; set; }
   }

   class B : A 
   {
      public override object MyProp { get; set; }
   }

   class MyReflectionContext : CustomReflectionContext
   {      
   }

   class Program
   {
      static void Main(string[] args)
      {
         PropertyInfo propertyInfo = typeof(B).GetProperty("MyProp");

         var attrs1 = propertyInfo.GetCustomAttributes(true);
         var attrs2 = Attribute.GetCustomAttributes(propertyInfo, true);

         MyReflectionContext ctx = new MyReflectionContext();

         propertyInfo = ctx.MapType(typeof(B).GetTypeInfo()).GetProperty("MyProp");
         var attrs3 = propertyInfo.GetCustomAttributes(true);
         var attrs4 = Attribute.GetCustomAttributes(propertyInfo, true);

         Console.WriteLine(attrs1.Length); // Returns 0 - As expected
         Console.WriteLine(attrs2.Length); // Returns 1 - As expected
         Console.WriteLine(attrs3.Length); // Returns 0 - As epected
         Console.WriteLine(attrs4.Length); // Returns 0 - We want 1 here!
      }
   }
```

**Comment by karelz** [comment]
@AtsushiKan plans to work on it next week.

**Comment by AtsushiKan** [comment]
I mistook this for a different issue I was working on.

**Comment by karelz** [comment]
OK, any guess on complexity?

**Comment by AtsushiKan** [comment]
Main complexity is that it's a breaking change. 

If we decide to take the change, we'll probably port the "GetParent" logic from corert so light to medium complexity.

**Comment by karelz** [comment]
Can we decide on the breaking change now (or at least provide high-confidence evaluation), or do we have to wait for the change to be coded up?

**Comment by AtsushiKan** [comment]
It makes little sense to code it up before we’ve decided whether the breaking change is worth it (especially since personally leaning against…)

**Comment by karelz** [comment]
OK, then as area owner can you please provide recommendation? Or pull in more people and drive the AppCompat decision?
It also means it is not ready for "up for grabs" yet, as we might want to reject it ...

**Comment by AtsushiKan** [comment]
Recommend we not take breaking change.

**Comment by alphaleonis** [comment]
Couldn't it be implemented without a breaking change as a new method or a new overload that provides this (proper) functionality?

**Comment by AtsushiKan** [comment]
Why isn't it sufficient for the third party types to implement the `ICustomAttributeProvider` apis on their PropertyInfo implementations? The static apis on `Attribute` are CLR-1.0-era apis. We don't want to pile on yet more overloads of this functionality when there already so many of them.
