### ISSUE TITLE
StringBuilder.AppendFormat additional pre-checks.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/corefx#8226]
Split from #1514 

[AppendFormatHelper](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Text/StringBuilder.cs/#L1285)

It maybe beneficial to do extra checks before actually generating the output.

[Approximation Routine](https://gist.github.com/AdamSpeight2008/ef6834483148afcac59234eef36ef36f) _Note: this is rough coding._

This gets us
- the number of argholes (`{0}`)  
  -  If this is zero, we could just return the original format string.
- the approximate length of the output.
  - we can pre-size the output, reducing the number of resizes and copying
- Is the format string structurally sound. (Excluding `IFormatable` errors)
  - If it is likely to throw an error. Don't generate the output.

**Comment by joshfree** [comment]
cc: @KrzysztofCwalina since this is a split off of https://github.com/dotnet/corefx/issues/1514

**Comment by danmosemsft** [comment]
@AlexGhiondea thoughts? is this ready for review (in which case please change hte label) or do you have feedback.

**Comment by AlexGhiondea** [comment]
I believe this is just a perf improvement.

@AdamSpeight2008 is this something you are interested in tackling?

**Comment by AdamSpeight2008** [comment]
@AlexGhiondea
Honestly I've not look at this for a while,Initially posted to that they maybe *(ie untested)* benefits. I think the premise needs a some more bake time. Since it basically replicates the code that does the parse and build, they may be a way shared code and get both.

**Comment by AlexGhiondea** [comment]
@AdamSpeight2008 thanks for adding more context! I am going to leave this as up for grabs in case someone is interested in a fun little optimization challenge 😄

**Comment by stephentoub** [comment]
> If this is zero, we could just return the original format string.

This is super rare and not something we really need to optimize for.  If you're using AppendFormat with zero holes, you've likely made a mistake, and in the rare case you haven't, we shouldn't spend any cycles to detect it and that penalize the 99% case.

> the approximate length of the output

There's potential benefit here, but in many situations it'd be very difficult to get a good estimate, or alternatively getting a good estimate would be expensive.

> Is the format string structurally sound. (Excluding IFormatable errors) If it is likely to throw an error. Don't generate the output.

We also don't want to spend any additional cycles proactively detecting incorrect input that'll be discovered later anyway; we should optimize for valid inputs, not invalid ones.

Given that, and that we're thinking about alternate approaches to addressing the larger problem space, e.g. https://github.com/dotnet/corefx/issues/35986, and that this issue has been open for over two years, I'm going to close this.  If you feel I've done so in error, please feel free to re-open.
