### ISSUE TITLE
Update CI to Debian 8.4

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#8228]
1. We should update CI infra to Debian 8.4 (https://www.debian.org/News/2016/20160402)
2. Also please review the RID graph entries for Debian 8.2+ (8.3, 8.4) so there are no issues for users on newer Debian 8 patch levels

**Comment by ellismg** [comment]
> Also please review the RID graph entries for Debian 8.2+ (8.3, 8.4) so there are no issues for users on newer Debian 8 patch levels

Debian does not bump the `VERSION_ID` field of `/etc/os-release` on minor version updates, so we should not need to add anything to the rid graph.  CLI will always generate the rid of `debian.8-x64` for all debian 8.X versions.

**Comment by Priya91** [comment]
Keeping it open till runs are added to readme.
