### ISSUE TITLE
CoreRun of Xunit.Console.Netcore causes terminal to stop responding to certain inputs on OSX

### ISSUE THREAD

**Issue by MattGal** [dotnet/corefx#8230]
When running individual CoreFX test cases on OSX (using vanilla corefx fetched this morning), every time I run Xunit.Console.Netcore.exe using corerun my terminal is never the same after.  

Observations:
- You have to actually run tests to get the repro (just running ./corerun xunit.console.netcore.exe doesn't repro) 
- Running "reset" solves this temporarily.

Some keys this takes away (not exhaustive list)
- Period
- Num keys
- dash and + (but not _ and =)

**Comment by mellinoe** [comment]
This is any test project? Or is it specific to, say, System.Console?

**Comment by MattGal** [comment]
It's definitely more than one.  I hit it with various System.Collections tests... but I can't say which all cause it.

**Comment by mellinoe** [comment]
I think this is a problem with the VNC viewer. I don't get a repro of this when I'm running things locally but I was able to see the problem on the machine that you shared with me (through VNC Viewer). I see some reports on google of people complaining of similar issues, I wonder if this is a bug in the viewer somehow? Anyone more familiar with this tool than I am?

**Comment by mellinoe** [comment]
I'm not sure this is actionable right now, so I'm moving it to future.

**Comment by mellinoe** [comment]
Hey @MattGal have you been experiencing this still? I wonder if it has resolved itself in a newer version of the VNC Viewer or something like that.

**Comment by MattGal** [comment]
I've stopped using VNC entirely, and it certainly does seem to have various weird effects on inputs when using it, not just for corerun.  I'd be OK closing this since it doesn't seem to come up often.
