### ISSUE TITLE
Ubuntu support needs to be better

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/corefx#8234]
I'm sure this seems like a nuisance ticket, but it's hard to gauge the level of interest in solving concerns I've seen brought up by others over the .NET experience on Ubuntu.

There are a few top-level issues at the moment, immediately apparent by the current install instructions:

![image](https://cloud.githubusercontent.com/assets/115199/14971129/198149e8-1095-11e6-913f-3d58e3e6011a.png)
1. The current instructions to install .NET on Ubuntu are second-rate.
    The big issue here is that you are requiring additional steps when they could be avoided.  If you examine Chrome and other debian packages, they are able to provide a PPA configuration without making you drop to the command line.  You can consider this on par with an MSI installer:
   
    ![image](https://cloud.githubusercontent.com/assets/115199/14971157/597c511e-1095-11e6-819f-f40a604cf269.png)
   
    This entry, as viewed in the "Software Sources" app in Ubuntu did not require me to do anything except add the `.deb` found [here](https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb).  It's also worth noting that using a PPA also avoids the need to make people do things with keys.
2. Only supporting 14.04.
    We're coming up to a month with 16.04. If the current build system cannot even support getting 14.10, 15.04 and 15.10 over the last 2 years, something has been seriously overlooked.  At the very least, this is a problem you shouldn't be carrying into a 1.0 release.
3. "Feeds".  Really, you can just package all the versions you want in a single feed and have a metapackage that points to the most current version.

As you can see, there are a few things that can be done to reduce the number of touchpoints for an Ubuntu developer as well as increasing the likelihood that they can run this wonderful new platform with confidence.
Having a first-rate install experience on Windows is great, but always allowing Linux to lag risks sending a message of what to expect in the future.

**Comment by joshfree** [comment]
Hi @atrauzzi thanks for all the great suggestions on making the getting started guide and acquisition process less painful.  Just a note that the instructions are based on the latest public preview (RC1) and that page will get a refresh once RC2 is published to nuget.org.

Also Ubuntu 16.04 support is in the works for 1.0-RTM

cc: @richlander @blackdwarf @ellismg

**Comment by ellismg** [comment]
As @joshfree says, we plan to add an Ubuntu 16.04 for 1.0.0 RTM (which will come around the end of June).

We currently don't have plans to produce pre-built packages of 15.10 for RTM.  It would be good to hear from folks who are presently on Ubuntu 15.10, how long they plan to stay on it.  Canonical stops supporting it shortly after we RTM.  Have folks on 15.10 already started to move to 16.04 or do you all plan to stay on 15.10 for a while?

Tagging @svick  and @GalaxiaGuy explicitly, since the they +1's the issue.

**Comment by atrauzzi** [comment]
I've moved to 16.04, I always keep pace.  But if this policy means 16.10 won't be supported, I'll definitely be frustrated (as will others most likely).
Generally, it's tough to say.  Every release is going to have different influences.  This current one for example, I'm hearing some rumblings about shifts in AMD's proprietary driver support.  Wouldn't be surprised if some people hang back due to that.

Since starting to use Ubuntu in 2005, I'd say the convention is you support back to the previous LTS release inclusive.

**Comment by ellismg** [comment]
> Since starting to use Ubuntu in 2005, I'd say the convention is you support back to the previous LTS release inclusive.

Thanks that's helpful.

**Comment by ellismg** [comment]
@atrauzzi Quick question about the above, as I'm afraid I'm missing something. Typically, I think of a PPA as something hosted by Ubuntu (i.e. [here](https://launchpad.net/ubuntu/+ppas)).  For the example you gave, Chrome, they appear to just give out a raw deb that you can install.  The deb does contain some cron scripts which seem concerned about ensuring that you have their apt repository in your sources list, but [other places on the internet](http://www.ubuntuupdates.org/ppa/google_chrome) describe dropping to the command line to add the source explicitly and then apt-get installing it.

We already publish .deb files that folks can install manually, they just don't attempt to add additional sources.  Were you proposing buying into the Ubuntu/Launchpad ecosystem or something else?

**Comment by atrauzzi** [comment]
Either a PPA or a "meta" package works fine at the end of the day.
You can either do as Chrome does which is publish a package that configures their own repositories and then triggers an installation.
*or*
You can host packages at Launchpad as a PPA.

From my point of view, so long as the installation does not require me to drop to a terminal, either approach is fine.

What's important is to ensure you:
 - Don't require people to set up a key
 - Don't require people to manually manage sources

:)

**Comment by tarekgh** [comment]
@ellismg what need to be done here? are you tracking to get any fixes soon? I am asking because this is marked as v2.0. Thanks.

**Comment by ellismg** [comment]
The portable linux work ensures that we support Ubuntu 14.04 and higher (assuming the necessary prereqs are installed) and we are no longer as strict about versions of native components (e.g. we require ICU be installed, but any recent version is fine).

We don't have any plans to adopt the PPA workflow or to simplify the gestures to add the Microsoft package source to your sources.list for 2.0.

**Comment by richlander** [comment]
Was just talking about this on Twitter: https://twitter.com/runfaster2000/status/854039105423818753

Feel free to reply to it / like it. The Ubuntu folks are watching.
