### ISSUE TITLE
Reduce number of package references for runtime specific packages

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#8239]
Today when you reference a fat package that uses RIDs you also have to reference Microsoft.NETCore.Platforms to bring in the RID graph.

When you reference a split package you need both Microsoft.NETCore.Platforms for the RID graph and Microsoft.NETCore.Targets for the lineup.

When referencing NETStandard.Library we include both of these, but not when referencing individual packages.

Adding these references to the packages themselves is a simpler story and makes it so folks don't need to understand the RID-graph/lineup concepts (or think that it is somehow magic).

**Comment by mellinoe** [comment]
> Adding these references to the packages themselves is a simpler story and makes it so folks don't need to understand the RID-graph/lineup concepts (or think that it is somehow magic).

:+1:

**Comment by davidfowl** [comment]
This work should include splitting the dependency between Platforms and Targets.
