### ISSUE TITLE
How to access values from project.json in code

### ISSUE THREAD

**Issue by SamuelEnglard** [dotnet/corefx#8258]
I don't want to be writing the values multiple times. Is there a way to access them? It can be something that's compile time.

**Comment by davidfowl** [comment]
What are you looking for? You can use JSON.NET if you want a JSON reader and writer.

**Comment by SamuelEnglard** [comment]
Looking for a "framework" way to it. If JSON.NET is answer I'll go way

**Comment by ericstj** [comment]
This should be asked in the NuGet repo: https://github.com/nuget/home.

I believe https://github.com/NuGet/NuGet.Client/tree/dev/src/NuGet.Core/NuGet.ProjectModel is the model that NuGet uses (which uses JSON.NET)
