### ISSUE TITLE
TypeDescriptor APIs

### ISSUE THREAD

**Issue by henkmollema** [dotnet/corefx#8262]
Hi there,

I was wondering what the status of the `TypeDescriptor` API is. Currently I am using `TypeDescriptor.AddAttributes()` but unfortunately this is not available on .NET Core. Is there any equivalent available or a timeline when this API will be ported?

Thanks in advance.

**Comment by svick** [comment]
I think this is duplicate of #6573.

**Comment by henkmollema** [comment]
Ah yes, thanks.

It also seems that the APIs are already ported according to this open PR: https://github.com/dotnet/corefx/pull/8093.

**Comment by stephentoub** [comment]
Dup of #6573, which has been fixed by https://github.com/dotnet/corefx/issues/8093.

**Comment by henkmollema** [comment]
Great. Thanks @stephentoub

**Comment by bgever** [comment]
@stephentoub This issue should be reopened, as the problem which @henkmollema pointed out is still the case when you target .NET Standard 1.0.

`System.ComponentModel.TypeConverter` package v4.3.0 (latest) when targeting .NET Standard contains this file: [`TypeDescriptor.NetStandard10.cs`](https://github.com/dotnet/corefx/blob/release/1.1.0/src/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.NetStandard10.cs), and not [`TypeDescriptor.cs`](https://github.com/dotnet/corefx/blob/release/1.1.0/src/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs), resulting in the issue as mentioned in the opening post.

**Comment by stephentoub** [comment]
These APIs were added back for 2.0; there are currently no plans to make them available earlier.
