### ISSUE TITLE
LinuxNetworkInterface Id and Description implementation

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#8297]
Currently NetworkInterface Id and Description throw PlatformNotSupportedException on Linux.
I'd like to propose the following:
Id returns _name
Description returns _name

The linux kernel does not grantee a network interface will have the same name after reboot but it can be done by using [udev](http://www.debianhelp.co.uk/udev.htm) or [systemd](https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/).

**Comment by mellinoe** [comment]
This seems like an okay compromise to me. @CIPop What are the "ID" and "Description" properties usually used for on Windows? Is it just things like display, diagnostics, statistics, etc.? It would be unfortunate that we can't guarantee the same network interface will return the same Name all the time, though.

Is there any way to get better information for "Description"? Windows returns fairly useful information here, i.e. `Intel(R) 82579LM Gigabit Network Connection` on my machine.

**Comment by tmds** [comment]
On Windows, the Id is a GUID which remains the same after each reboot. So it can be used as a persistent identifier. The Description is a useful one. The Name can be changed by the user in the Network Settings.

Looking at one real example: Wireshark has in it's capture interfaces dialog two columns: Device and Description where it puts the Name and Description respectively. On Linux the name is left blan. Screenshots here: https://www.wireshark.org/docs/wsug_html/#ChCapInterfaceSection.

Returning string.Empty on description could also be an option or something like $"Interface '_name'" or $"'_name' interface".

**Comment by tmds** [comment]
My personal preference is not to do string.Empty on Description, since Description will likely end up in a GUI and it isn't of much use if it shows nothing.

**Comment by tmds** [comment]
@mellinoe can we conclude on the proper values to return from Id and Description. Do we need feedback from some other people?

So proposal:
Id returns `_name`
Description returns `$"'{_name}' interface"`

@joshfree It should not be much work to implement. Would it be possible to get this in rc2? I need this feature for a library and it would be great if I could use the rc2 release.

**Comment by joshfree** [comment]
@tmds sorry; it's not possible to get new changes into the corefx /release/1.0.0-rc2 branch at this point.

**Comment by mellinoe** [comment]
I'd like to get the opinions of some of the guys on our networking team. @CIPop , @davidsh Any opinions here? My impression is that `Description` does not necessarily need to return any particular string, so the proposed value would be fine. It seems like the fact that `ID` does not return a consistent value across reboots could be problematic.

**Comment by tmds** [comment]
@mellinoe Indeed the ID should be consistent across reboots. This grantee could be provided by an external manager like udev or systemd. If the implementation is done in corefx, the systemd way may be a good one, see [PredictableNetworkInterfaceNames](https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/). (Note: systemd has a LGPL license.)

**Comment by davidsh** [comment]
> Description  does not necessarily need to return any particular string

I agree that this can vary between implementations but it would nice to get the strings as close as possible across the implementations.

The ID should be consistent.

**Comment by tmds** [comment]
@mellinoe @davidfowl @CIPop I think we all agree that the ID should be consistent. The real question is: who is responsible for making it consistent across reboots?

In my opinion the network interface name is good enough, rationale:
* It is a common practice to use the name in configuration files which are expected to remain the same across reboots. (e.g. firewall rules, routing, ...)
* On most systems the names are always the same after reboots.
* Systems with a recent version of systemd have unique names.
* It is a common practice to fix the names using udev in case the names are changing.

**Comment by mellinoe** [comment]
Thanks, that is good information. If there is precedent for persisting the ID, then that alleviates some of my concern. When using it from a .NET Application, though, there may be an extra expectation that the value always be consistent, but I'm not familiar enough with how people are using this property in practice. The fact that most systems (and newer ones) all have consistent names is reassuring as well.

Regarding `Description`: is there a way we can get a "real" description? For example, I can run `lshw` to find out that my `wlan0` interface is a "Wireless 7260" product by Intel Corporation. That information would probably line up better with what the Windows implementation exposes. I can't find anything on how to actually get that information, though.

**Comment by tmds** [comment]
The info you get from `lshw `comes from matching pci ids to descriptions stored on the filesystem typically at `/usr/share/misc/pci.ids`, `/usr/share/hwdata/pci.ids`, ...

**Comment by mellinoe** [comment]
Based on the above info, I'd be fine with the original proposal, i.e.

````
public static string ID => _name;
public static string Description => _name;
````

We can further improve the description in the future if we would like. @tmds Is this something you'd like to contribute? If so, I can hold off on making the changes and can help review the changes. If not, I can do this sometime today or tomorrow. We should be able to get this in for the RTM release.

**Comment by mellinoe** [comment]
@tmds I went ahead and implemented the above proposal. Check out the PR here: https://github.com/dotnet/corefx/pull/8586

**Comment by tmds** [comment]
Thanks @mellinoe
