### ISSUE TITLE
Cross building much slower with new universal runner infrastructure.

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#8307]
As part of adopting the universal runners, we need to copy the entire packages folder from the builder machines to the test executor machines when we have to build managed code on Linux but test it on windows.

Previously, the amount of data we needed to copy was on the order of 130 MB (this was the entire "bin" folder, de-duplicated in a zip file, via Packer).

After the changes to also include the packages folder, we've grown to about 630 MB.

We should figure out how to shrink this amount of data.  I expect there is low-hanging fruit here (e.g. we are archiving all the nupkg's we downloaded, which we don't need?  This removes about 300 MB from the compressed archive if we stop that).

**Comment by ellismg** [comment]
/cc @MattGal @weshaggard 

I noticed this because today the CI system was taking a very long time to archive the artifacts.  The time spent copying this to and from machines slows down CI time.

**Comment by weshaggard** [comment]
I think anything we can do to improve the size here is goodness all around. 

What does the size look like if you filter it to just .dll/.exe files in the packages folder?

**Comment by ellismg** [comment]
> What does the size look like if you filter it to just .dll/.exe files in the packages folder?

The pre-compressed size ends up dropping from 1.7GB to 417 MB.  I do not expect we would realize much gain from compression, but who knows.

The above filtering is too aggressive however, since it also takes away test assets we have in NuGet packages and filters out all of the Linux and OSX run-times, which we will need in some cases (including .so's and files with no extension brings the count up to around 550 MB).

**Comment by ellismg** [comment]
If you're interested (and also a good place for me to store this interesting power-shell snippet)

```
PS> Get-ChildItem -File -Recurse .\Packages | Group Extension | %{ New-Object psobject -Property @{Extension = $_.Name ; Sum = ($_.Group | Measure-Object Length -Sum).Sum } } | Sort -Descending Sum

      Sum Extension
      --- ---------
820323279 .xml
406976784 .dll
334906137 .nupkg
 60563882 .so
 32055926 .zip
 27612267
 27037880 .wmv
 22056960 .pdb
 13063100 .dylib
  9303072 .exe
  4678678 .txt
  4179456 .winmd
  2443778 .json
  1029744 .xls
  1001516 .gz
   874021 .nuspec
   730089 .rtf
   532783 .msu
   358294 .a
   317407 .docx
   313684 .targets
   243986 .pdf
    91136 .doc
    82454 .pptx
    41551 .rsp
    37881 .py
    33352 .sha512
    31245 .xslt
    29505 .xaml
    25314 .pfx
    24603 .html
    19888 .xlsx
    13683 .props
    11581 .c
     9356 .xap
     8868 .cer
     8709 .p7b
     6082 .cs
     5898 .p7c
     5100 .csproj
     4651 .config
     4227 .1
     4188 .ps1
     3991 .sh
     3721 .lsp
     2723 .cmd
     1798 .pem
     1585 .sln
     1510 .rc
     1368 .snk
     1291 .nuproj
     1114 .package
      459 .ruleset
      402 .tdnet
      340 .bat
      251 .vb
      142 .SDKVersion
        0 .file
        0 ._
```

Obviously, the XML will compress well.

**Comment by weshaggard** [comment]
The XML will compress well but it is probably the set of files that isn't needed for our testing purposes as it is mostly intellisense files. So it might be worth filtering those and nupkg files out.

**Comment by xoofx** [comment]
The inefficiency of zip dealing with almost duplicate data (doesn't span compression across archive entries) and poor compression model (deflate/inflate) has been hurting a lot NuGet packaging... and we can see that it is getting worse with its broader adoption into the build...

Compressing a package folders with all packages with 7Z (with LZMA) will go down to 10% compression ratio, while with zip you will only achieve 30-40%

Also NuGet bandwidth would benefit a lot to switch to 7Z like format , in my experiments, around 50% would be saved... though LZMA is not a panacea in decompression speed (until we get an OSS equivalent of [Kraken](http://cbloomrants.blogspot.jp/2016/04/release-kraken.html) some days!)

**Comment by mellinoe** [comment]
@ellismg Is this still a problem? Assuming that you meant this in your first post:

> when we have to build managed code on *windows* but test it on *linux*.

Then I think this is not a problem any longer, since we don't build/run our tests that way anymore.

**Comment by ellismg** [comment]
Yeah, this is not a problem anymore.
