### ISSUE TITLE
Any plans to include NetworkAvailabilityChanged

### ISSUE THREAD

**Issue by jchannon** [dotnet/corefx#8311]
We use this event off `NetworkChange`, Portability Analyzer says NetworkChange is available but not that event. Any plans to bring this in for 1.0.0?

**Comment by davidsh** [comment]
cc: @CIPop @himadrisarkar

**Comment by CIPop** [comment]
Thanks for noticing and reporting this @jchannon!

@SidharthNabar @himadrisarkar @davidsh Do you have any background on why we didn't add this to the contract surface initially?

Looking at the code I see that we might have the code already: the entry point is in [this file for Windows ](https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.Net.NetworkInformation/src/System/Net/NetworkInformation/NetworkAddressChange.Windows.cs#L15).

This might be a simple omission from the [contract surface](https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.Net.NetworkInformation/ref/System.Net.NetworkInformation.cs).

**Comment by davidsh** [comment]
>Do you have any background on why we didn't add this to the contract surface initially?

It wasn't added to the original .NET Store Profile contract.  And that is because it wasn't possible to implement it on UWP (netcore50) which  uses the WinRT networking APis.  I will forward you info offline.

**Comment by jchannon** [comment]
So is that confirmation that it's not making it into 1.0.0?

**Comment by davidsh** [comment]
>So is that confirmation that it's not making it into 1.0.0?

Yes. However, we will consider it post RTM for a future contract if we determine that it can be implemented in a reliable manner.

**Comment by jchannon** [comment]
Hmmm. This might be problem for our systems. Thanks for the info.

**Comment by davidsh** [comment]
Moving to post-RTM

**Comment by karelz** [comment]
Covered by #11789 in netstandard2.0 effort.
/cc: @mellinoe
