### ISSUE TITLE
Consider adding System.Linq.Expressions into Standard Library

### ISSUE THREAD

**Issue by onovotny** [dotnet/corefx#8315]
Currently System.Linq.Expressions is not included in the .NETStandard.Library.

While it's true that some cases might fallback to interpretation, there does seem to be an implementation that works everywhere. Even Xamarin.iOS had a solution to this (might be interpretation as well).

**Comment by svick** [comment]
Why do you think it's a problem that it's not included? When you need it, you can just specify it in `project.json`. And since I believe it's relatively rare to need it directly, not including it makes sense to me, since it means people who don't need it don't need to download it.
