### ISSUE TITLE
Two PLINQ tests consistently fail on 6 core HT Xeon machine

### ISSUE THREAD

**Issue by MattGal** [dotnet/corefx#8324]
I have a particular machine with a 6 core (Hyperthreaded to 12) CPU Xeon processor.   On this machine both in Windows and an ubuntu VM, I see the following two tests always fail in System.Linq.Parallel tests:

      <test name="System.Linq.Parallel.Tests.SelectSelectManyTests.Select_OrderablePartitionerWithOutOfOrderInputs_AsOrdered_CorrectOrder(keysOrderedInEachPartition: False, keysNormalized: True)" type="System.Linq.Parallel.Tests.SelectSelectManyTests" method="Select_OrderablePartitionerWithOutOfOrderInputs_AsOrdered_CorrectOrder" time="0.0100057" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 0\r\nActual:   4]]></message>
          <stack-trace><![CDATA[   at System.Linq.Parallel.Tests.SelectSelectManyTests.Select_OrderablePartitionerWithOutOfOrderInputs_AsOrdered_CorrectOrder(Boolean keysOrderedInEachPartition, Boolean keysNormalized) in C:\GIT\corefx\src\System.Linq.Parallel\tests\QueryOperators\SelectSelectManyTests.cs:line 217]]></stack-trace>
        </failure>
      </test>
      <test name="System.Linq.Parallel.Tests.SelectSelectManyTests.Select_OrderablePartitionerWithOutOfOrderInputs_AsOrdered_CorrectOrder(keysOrderedInEachPartition: False, keysNormalized: False)" type="System.Linq.Parallel.Tests.SelectSelectManyTests" method="Select_OrderablePartitionerWithOutOfOrderInputs_AsOrdered_CorrectOrder" time="0.0033736" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\r\nExpected: 0\r\nActual:   4]]></message>
          <stack-trace><![CDATA[   at System.Linq.Parallel.Tests.SelectSelectManyTests.Select_OrderablePartitionerWithOutOfOrderInputs_AsOrdered_CorrectOrder(Boolean keysOrderedInEachPartition, Boolean keysNormalized) in C:\GIT\corefx\src\System.Linq.Parallel\tests\QueryOperators\SelectSelectManyTests.cs:line 217]]></stack-trace>
        </failure>
      </test>

As this is the only machine like this I have like this, internal folks can stop by my office to investigate if needed.

**Comment by joshfree** [comment]
@AlfredoMS can you please look into this PLINQ issue?

**Comment by AlfredoMS** [comment]
I'll stop by your office tomorrow morning

**Comment by stephentoub** [comment]
I know what the problem is.  It's a test bug.  I'll fix it.
