### ISSUE TITLE
netcore .nupkgs have minclientversion=3.4 -- which will never be able to work in VS2013

### ISSUE THREAD

**Issue by rrelyea** [dotnet/corefx#8336]
checked a few .nuspec files in yesterday's (i think) build of rc2
packages\System.Runtime\4.1.0-rc2-24027\System.Runtime.nuspec
uses a minClientVersion:
`  <metadata minClientVersion="3.4">`

NuGet is working on a v2.12 version of NuGet to work in VS 2013, which will not be able to support these packages unless minClientVersion is removed.

/cc: @ericstj @yishaigalatzer

**Comment by ericstj** [comment]
We can make them work in nuget 2 once we have a version that supports all new monikers.

**Comment by yishaigalatzer** [comment]
We have one in flight, shouldn't the packages going live support it? How would we validate in the wild with this block in place at RC2 time?

**Comment by ericstj** [comment]
Share bits and I'll try it out and lower the minClientVersion.  I don't suppose there's a chance that you'll support minClientVersion="2.12,3.4"?  Otherwise we'll get folks asking why these packages don't work with NuGet 3.3.

**Comment by yishaigalatzer** [comment]
There is no way to go back in time and make old versions understand it

**Comment by yishaigalatzer** [comment]
Bits will be ready in a couple of days. But note that this will be similar to a packages.config scenario in 3.4.4 we don't plan on porting PJ down

**Comment by ericstj** [comment]
Yeah, we've done some work to support packages.config in 3.4 so we should work in packages.config on 2.12..  I was hoping there was some syntax, like 2.12,3.4 that both 2.11 and 3.3 would reject but 3.4 and 2.12 would accept (suppose the old clients would treat parsing error as not supported).

**Comment by yishaigalatzer** [comment]
We weren't that smart when the feature was first developed.

**Comment by ericstj** [comment]
What about us producing a package with minClientVersion=2.12 and minClientVersion3=3.4 and then the v2 feeds serve up the package unmodified, but the v3 feeds rewrite the package to use the higher minClientVersion?

**Comment by yishaigalatzer** [comment]
And then it breaks on all the public servers AND fails after you put it in the local folder. Agree we need to find something creative but I don't have a clean way to do it

**Comment by ericstj** [comment]
Id really like you to think about how to represent the comstaint better.  We already get a ton of folks reporting issues where nuget isn't checkin min version; I suspect many more once we have to lie and say 2.12...

**Comment by cdrnet** [comment]
Seems the issue here is that the constraint is scoped at the client, while it should really be scoped at the NuGet package format.

**Comment by yishaigalatzer** [comment]
The constraint is just a dumb "big hammer". It's very unfortunate, we will have to build something more intelligent like browser feature detection but then will have to retrofit all the old clients which isn't possible.

We could think of something else going forward beyond 3.5 and 2.12. Something like: requires: [" feature1", "feature2"]  that wouldnt say what client supports, unless we build a small service that can map that, or a help page that helps a customer do the mapping.

Of course this will turn into something more elaborate like
[
{"Capability": " feature1", "required": "false" },
{"Capability": " feature2", "required": " true" }
]

This pattern can also be used for packages that work only in PJ scenarios vs. Packages.config scenarios, and anything else that will be built into the client.

We also need to consider how it interacts with package type feature.

Cc @robrelyea @davidfowl @emgarten

**Comment by ericstj** [comment]
So for the short term we'll set it at 2.12 and add some note to the package description that we need 3.4 for folks on NuGet 3.

**Comment by ericstj** [comment]
This has been fixed as of https://github.com/dotnet/corefx/commit/eae5aa4063bf5990292d0b753415f127ebe97755
