### ISSUE TITLE
Unable to build under Windows 10 x64

### ISSUE THREAD

**Issue by TorbenJ** [dotnet/corefx#8341]
Today I tried to build this repository but unfortunately it didn't succeed.
I got several "Permission denied" errors while running the tests so I tried running them in an elevated cmd. I also noticed several test failures so I copied every line from the build log that indicates a warning or an error into a gist.
Apart from that the build process gets stuck after the test summary of System.Net.Sockets.Tests (last line in the gist)

[https://gist.github.com/TorbenJ/701697b7448f0fbfdf9e3cc0a501c58e](url)

Used software:
Windows 10 Education N 64-bit (10.0, Build 10240)

**Comment by ellismg** [comment]
Is it possible to attach the full msbuild.log file to this issue?

A bunch of folks on the team use Windows 10 x64.  I'm not sure if there's something specific about this SKU however.  A complete log could be helpful.

**Comment by TorbenJ** [comment]
[msbuild.log](https://github.com/dotnet/corefx/files/252021/msbuild.log.txt)

**Comment by mellinoe** [comment]
It looks like almost everything succeeded except one test project, which is most likely just due to flaky tests, but may be due to a real issue. Could you try doing the following and let us know what happens?

````
<go to corefx root>
cd src\System.Net.Sockets\tests\FunctionalTests
msbuild /t:RebuildAndTest /p:OSGroup=Windows_NT
````

That will re-run only the System.Net.Sockets tests that failed.

**Comment by TorbenJ** [comment]
I ran this but nothing special happened and msbuild succeeds without any errors or warnings.

The full output:
[https://gist.github.com/TorbenJ/b677929f4689a61548be402e3396d0e6](url)

**Comment by mellinoe** [comment]
My assumption is that you just hit a few flaky tests, and they succeeded after re-trying them. Unfortunately, we have a few flaky tests that will fail every so often, even with a clean build. If you hit consistent issues, please re-open this. In the meantime, I'm going to close this out.
