### ISSUE TITLE
Expose Stream.Begin/EndRead/Write in System.IO contract

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#8358]
We really want devs to use Stream.Read/WriteAsync, but not having these Begin/End methods exposed breaks portability scenarios, e.g. where a stream in the full framework wraps another stream (e.g. SslStream) and the wrapper's async implementation wraps the Begin/End methods on the underlying Stream.  Without these Begin/End members in the contract, it's impossible for a portable Stream implementation to plug in to that wrapper correctly.

The core work here (for RTM) is to:
- Expose the Begin/EndRead/Write virtual methods in the contract
- Fix all of our Stream implementations in corefx to override these.  In some cases, the methods already exist and we just need to change them from internal methods to public overrides.  In other cases, we need to implement them and can do so easily on top of the Read/WriteAsync implementations.

After that, we can optionally consider:
- Changing the base Stream.Begin/EndRead/Write implementation to check if ReadAsync/WriteAsync are overridden, and if they are, delegating to those instead of queueing a work item that invokes the synchronous Read/Write.  There are potential issues here, though, e.g. if a Stream overrides ReadAsync/WriteAsync to delegate to Begin/End which it doesn't override, at which point they'll end up in an infinite redirection loop.  There may be ways to mitigate that.  If we added that, we need a similar change (under a quirk) in the full framework.

cc: @weshaggard, @terrajobst, @KrzysztofCwalina, @davidfowl, @benaadams

**Comment by benaadams** [comment]
Related full framework blocked stack trace

![](http://aoa.blob.core.windows.net/aspnet/sslstream-async-issue.png)

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/pull/8486
