### ISSUE TITLE
System.Net.Http.Functional.Tests RevokedCertificate 2 tests fail

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#8366]
Failures on Ubuntu:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_release_prtest/854/
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_release_prtest/854/

Failures on Centos:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_release_tst_prtest/861/consoleFull#6262143651f1a4601-6aec-4fd5-b678-78d4389fd5e8

```
MESSAGE:
Assert.Throws() Failure
Expected: typeof(System.Net.Http.HttpRequestException)
Actual: typeof(System.Threading.Tasks.TaskCanceledException): A task was canceled.
+++++++++++++++++++
STACK TRACE:
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

```
MESSAGE:
System.Threading.Tasks.TaskCanceledException : A task was canceled.
+++++++++++++++++++
STACK TRACE:
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test.<NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds>d__7.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
--- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by stephentoub** [comment]
Failures on Windows:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/979/consoleText

This wasn't specific to any particular OS.  I think the site this was talking to was just down briefly.  It'd be great to find a way to test this instead with a local loopback server.

**Comment by davidsh** [comment]
> It'd be great to find a way to test this instead with a local loopback server.

This is really hard to test with a loopback server because revocation checking requires that the certificate be trusted in the first place and that is hard to do with fake servers.

I was thinking, though, of moving these tests to our own Azure test endpoint which would be more stable than a 3rd party server.

**Comment by bartonjs** [comment]
Either way, since they require an off-box connection OuterLoop might be prudent.

**Comment by davidsh** [comment]
>Either way, since they require an off-box connection OuterLoop might be prudent.

Most of our HTTP tests are end-to-end and require "off-box" connections.  I don't think we want to move all of those HTTP tests to [OuterLoop] as we will miss important regressions in our code.

I do think we need to stop using 3rd party servers whose reliability is questionable.

**Comment by davidsh** [comment]
This is probably due to timeouts due to network congestion accessing the Azure test server.

We need to change more of the tests to use Loopback server or possibly an alternate test server that would be in CI's system LAN network (to reduce latency, etc.).

**Comment by davidsh** [comment]
Mitigated with PR #11341 and future work part of issue #11345
