### ISSUE TITLE
Building CoreFx on Windows requires both MsBuild 12.0 and 14.0 tools installed

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#8369]
The instructions for setting up a machine to build CoreFx are not precise and can lead to problems building.  The instructions right now say:
https://github.com/dotnet/corefx/blob/master/Documentation/building/windows-instructions.md

“Visual Studio 2015 is required.”

However, that is not sufficient using the default settings of Visual Studio 2015 install.

The default settings will only install MsBuild 14.0.  But the CoreFx CSPROJ and other scripts seem to want MsBuild 12.0 (you will see warning messages when doing “build” from the CoreFx root directory). In addition, it ends up using the C# 5 compiler:

![image](https://cloud.githubusercontent.com/assets/7684835/15089388/f19df56e-13b6-11e6-8b32-1ca1c936e675.png)

This will cause compilation errors in System.Net.Http/src for example due to C# 6 features being used in the source files.

The fix is to install these additional things from Visual Studio 2015.   This will install MsBuild 12.0 tools.

![image](https://cloud.githubusercontent.com/assets/7684835/15089391/f85c2a2e-13b6-11e6-89b7-bb5cd0faf2fb.png)

Which then results in the C# 6 compiler being used:

![image](https://cloud.githubusercontent.com/assets/7684835/15089394/ff56d630-13b6-11e6-9f7a-43d438f5ca89.png)

Why does our build system require both MsBuild 12.0 and MsBuild 14.0 tools?

**Comment by davidsh** [comment]
cc: @ellismg @weshaggard @stephentoub @CIPop

**Comment by CIPop** [comment]
This doesn't work with VS Community 2015, at least on Win7.

**Comment by CIPop** [comment]
@davidsh and I talked offline and he recommended as alternative installing 
https://www.microsoft.com/en-us/download/details.aspx?id=40760 

I've verified this works on Win7.

**Comment by weshaggard** [comment]
I can build successfully with just VS2015 and msbuild 14. I do believe we do require at least VS 2015 Update 1 now however. I don't know of any reason why you would need msbuild 12.

**Comment by davidsh** [comment]
>I can build successfully with just VS2015 and msbuild 14

That is only true if you build everything from the root with "build".

However, if you go into a specific project, say `\CoreFx\src\System.Net.Http\src` and then do:

`msbuild /t:rebuild`

it will use the wrong compiler.  You will also see warning messages about "Can't find MsBuild 12.0".

**Comment by joperezr** [comment]
@davidsh did you run init-tools.cmd before trying to build individual projects? I don't have msbuild 12 and I can't repro this.

**Comment by CIPop** [comment]
@joperezr Please contact me offline for a very simple repro on either an Azure or a vanilla deployment of Win7/Win10.

Repro steps: 

1. Install Visual Studio Community
- Install CMake
- Install GitHub's Desktop client
- Restart
- Start the GitHub client (installs Git tools)
- Start PoshGit using the desktop icon that GitHub's client installed
- git clone https://github.com/dotnet/corefx.git
- .\build : This runs without any issues.
- cd src\system.net.http\tests\FunctionalTests
- msbuild /t:rebuild,test

The last command fails to build. 

Workaround: install https://www.microsoft.com/en-us/download/details.aspx?id=40760 
If you retry the last command, it will build and run the tests.

#8435 is also related but has a different cause: .\build runs the tests as expected but msbuild /t:rebuild,tests fails to build the project even after msbuild 12 is installed.

**Comment by joperezr** [comment]
It did repro on my box. I guess we need to add the requirement of msbuild 12.0 to be installed to the md file.

**Comment by joperezr** [comment]
So I noticed in the instructions that there is a small note that does indicate that the Tools need to be installed in order to build C++ projects succesfully. The line reads:
>Note: In order to build our C++ projects be sure to select "Programming Languages | Visual C++ | Common Tools for Visual C++ 2015" while installing VS 2015 (or modify your install to include it).

@davidsh do you think that is not very explanatory? would it help if we add a screenshot like the one you provided in this issue?

**Comment by davidsh** [comment]
>@davidsh do you think that is not very explanatory? would it help if we add a screenshot like the one you provided in this issue?

The current docs are not very helpful.  Yes, it would help to clarify them and add a screenshot.

**Comment by joperezr** [comment]
ok, thanks! I'll send out a PR soon.

**Comment by CIPop** [comment]
> So I noticed in the instructions that there is a small note [...]

@joperezr I've followed all instructions. The note is clear but will not help. You need to install the v12 msbuild. That checkbox will install v14 msbuild.

**Comment by mellinoe** [comment]
I'm not sure I understand where this requirement is coming from. Can't we just fix whichever project is configured in such a way that it needs MSBuild 12?

**Comment by weshaggard** [comment]
I agree with @mellinoe we should eliminate the dependency on msbuild 12.

**Comment by mellinoe** [comment]
I haven't had MSBuild 12 installed on a variety of machines and I haven't hit this, so I'm going to assume it is fixed by now.

**Comment by CIPop** [comment]
Trying now with a fresh install of Win7 and without installing MSBuild 12.
(Note for others: Win7 needs to be up-to-date before installing VS Community, otherwise the VS setup will hang.)

**Comment by CIPop** [comment]
I can confirm that the build works as expected after installing just VS Community!
Thanks @weshaggard @mellinoe !
