### ISSUE TITLE
Skipping build of test assemblies when "skiptests" is specified

### ISSUE THREAD

**Issue by manu-silicon** [dotnet/corefx#8385]
On Unix, one can specify the `skiptests` command line option to `build.sh`. However, it still compiles all the test assemblies and increases the overall compile time. Shouldn't the build of test assemblies be actually skipped too?

**Comment by ellismg** [comment]
This is similar to how we do things on windows (passing `/p:SkipTests=true` still causes the tests to be built, it just doesn't execute them).

**Comment by manu-silicon** [comment]
I assumed this was not available on windows because the batch script does not provide this has an option like you have for CoreCLR.

In any case, I would change this issue to not build the tests if `skiptests` is set. It feels like it would be a huge saving in compile time. As I mentioned in #7538 a rebuild when you do not change anything is taking quite a bit of time when it should be close to just a few seconds.

**Comment by joperezr** [comment]
@manu-silicon There are some new changes coming in from the new dev workflow which I'm not 100% sure but I believe that they will basically separate the product and test build. @maririos has been working on those changes, so she might have a bit more info to share about them.

**Comment by maririos** [comment]
@manu-silicon if you want to avoid building the tests you could pass `/p:BuildTests=false` in both build.cmd and build.sh.
There are some scenarios where we want to build but not execute the tests so for now we have both properties for the different behaviors.
As @joperezr mentioned, I'm working on a change that involves the exposure of the properties we have and when to use them, so in the future custom a build could be easier.

**Comment by manu-silicon** [comment]
@maririos Thanks. I'll try this.

**Comment by joperezr** [comment]
@manu-silicon If that works for you, can you let us know so we can close the issue? Thanks!
