### ISSUE TITLE
chmod errors when building on Linux

### ISSUE THREAD

**Issue by manu-silicon** [dotnet/corefx#8386]
When building on Linux, I'm getting a lot of those messages. Luckily they do not cause the build to break. It would be nice however to not have those:

```
Common.Tests -> /home/local/Microsoft/corefx/bin/Unix.AnyCPU.Debug/Common.Tests/Common.Tests.dll
chmod: cannot access ‘/home/local/Microsoft/corefx/bin/tests/Unix.AnyCPU.Debug/Common.Tests/dnxcore50/corerun’: No such file or directory
```

**Comment by manu-silicon** [comment]
Forgot to say that I used `skiptests` in the argument of `build.sh`. I haven't checked if those messages disappear if `skiptests` is dropped.

**Comment by manu-silicon** [comment]
Just remembered that on CoreRT, I reported a similar issue dotnet/corert#1194. I'm not sure if they are related but it is worth checking.

**Comment by joperezr** [comment]
Thanks for fixing this @ellismg :smile:

**Comment by manu-silicon** [comment]
Confirming that I'm not seeing those errors anymore.
