### ISSUE TITLE
Clean.cmd and .sh should offer an option to prevent user prompt on failures

### ISSUE THREAD

**Issue by roncain** [dotnet/corefx#8392]
When Clean.cmd or .sh fail to unlink a file during the 'git clean -xdf' phase, they prompt "Should I try again?"  This is fatal for an automated environment like CI and will require manual intervention.

Clean should offer an option that prevents prompts.  Possible solution is:
- Optionally 'set GIT_ASK_YESNO=false' in clean.cmd

I would prefer this prompt suppression should be the default.  Interactive users can see the failures and try again, but lab machines cannot.

Any netci.groovy scripts using clean.cmd/sh or doing manual 'git clean -xdf' should also be aware of whichever option is chosen and use it.

**Comment by weshaggard** [comment]
While I generally like the idea I don't think it will be easy to guarantee we stay clean in all the commands our scripts call. Given it hasn't gotten any interest for a long time I'm going to close, if someone is interested in trying to improve our scripts by all means give it a go.
