### ISSUE TITLE
Nullref while deserializing on many threads with DataContractJsonSerializer

### ISSUE THREAD

**Issue by billwert** [dotnet/corefx#8422]
Updating the packages used for serialization seems to have introduced a crash.

Repro:
1) dotnet new
2) replace program.cs with [this](https://gist.github.com/billwert/183050efed9a3ff9856dda9cd58be86c#file-program-cs)
3) Add these to your project.json:
    "System.Runtime.Serialization.Json": "4.0.2-rc3-24109-00",
    "System.Runtime.Serialization.Primitives": "4.1.1-rc3-24109-00"
4) dotnet restore
5) dotnet build
6) dotnet run

It should crash with something like this at the top of the stack:
Unhandled Exception: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Runtime.Serialization.XmlFormatReaderGenerator.UnsafeGetUninitializedObject(Type type)
   at ReadPersonFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )

Rolling the packages back to these will make the bug go away.
    "System.Runtime.Serialization.Json": "4.0.2-rc3-23924",
    "System.Runtime.Serialization.Primitives": "4.1.1-rc3-23924"

**Comment by stephentoub** [comment]
This code is not thread-safe:
https://github.com/dotnet/corefx/blob/master/src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/XmlFormatReaderGenerator.cs#L875-L879
yet it appears to be accessible from multiple threads concurrently.

**Comment by khdang** [comment]
Something is wrong with my machines. When I ran ```dotnet run``` I see this: 
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Private.DataContractSerialization, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at SerializerRepro.Program.Main(String[] args)
```

**Comment by khdang** [comment]
Somehow I ran the repro code as a unit test in corefx multiple times and it didn't repro.

**Comment by khdang** [comment]
I still cannot repro the issue. 
The callstack suggests ```s_typeHasDefaultConstructorMap``` is null at the index operation. However it should be accessed before this index operation without any issue by the same thread. In addition, it is a private readonly and should be initialized before the below code is executed. So I'm not sure how this could happen.
```
if (!s_typeHasDefaultConstructorMap.TryGetValue(type, out hasDefaultConstructor))
            {
                hasDefaultConstructor = type.GetConstructor(BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance, Array.Empty<Type>()) != null;
                s_typeHasDefaultConstructorMap[type] = hasDefaultConstructor;
            }
```

**Comment by khdang** [comment]
@shmao @SGuyGe can you help give it a try to see if it's repro?

**Comment by stephentoub** [comment]
@khdang, I believe the issue is a race condition.  It's not that s_typeHasDefaultConstructorMap is null, it's that inside of the dictionary it's hitting a null reference exception.  If the code I highlighted can be invoked from multiple threads concurrently, it's possible for two threads to be trying to modify the dictionary concurrently, or one reading from it as another is modifying it, and Dictionary is not thread-safe for such concurrent operations.

**Comment by billwert** [comment]
Debugging this on my machine, the crash happens here: https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/Dictionary.cs#L345

Looking up the function a bit, you can see that the first time someone calls Insert it will call initialize: https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/Dictionary.cs#L310

Initialize https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/Dictionary.cs#L294 first initializes buckets, then entries.

What is likely happening is that thread A gets as far as initializing buckets, and thread B proceeds through Insert, until it hits the null entries pointer.

Amusingly, when I debug this in VS, entries actually gets initialized by the other thread before the debugger can stop, so it looks like a mystery bug. I'm pretty sure this is what's happening, though.

**Comment by khdang** [comment]
That makes sense. I didn't realize the exception was from dictionary. I'll fix this by using ConcurentDictionary instead.

**Comment by shmao** [comment]
The Dictionary was used as a perf optimization. It may be worth to compare the performance of using ConcurentDictionary v.s. not using dictionary at all. We can then decide whether we need this optimization.
