### ISSUE TITLE
PublicKeyTests.TestKey_RSA failed in CI on Ubuntu 14.04

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#8423]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_release/254/consoleText

```
     System.Security.Cryptography.X509Certificates.Tests.PublicKeyTests.TestKey_RSA [FAIL]
        Assert.Equal() Failure
        Expected: Byte[] [1, 0, 1]
        Actual:   Byte[] []
```

**Comment by bartonjs** [comment]
I really wish we could get heapdumps on things like this.  I've tried ~1 million reruns of this test locally and can't get it to fail.  Maybe I can beef it up with some things like bouncing between threads, and an occasional block on Finalization.

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/rhel7.2_release_tst/497/consoleText

Sorry, Jeremy :)

**Comment by bartonjs** [comment]
@stephentoub Well, that really looks more like the version reported in #6302; but the sympathy is still appreciated :).

I've had this suite running for over 24 hours and not seen a failure locally.

Dear computers, plz be deterministic. Kthx.

**Comment by bartonjs** [comment]
#6302 has an instance of getting back Array.Empty already, so closing this as duplicate.
