### ISSUE TITLE
System.Security.SecureString.Tests fails using Ubuntu 14.04.3 LTS

### ISSUE THREAD

**Issue by TorbenJ** [dotnet/corefx#8425]
I noticed one error when building the corefx repository.
The repository was freshly cloned to ensure it wasn't fixed in the meantime.

An extract of the `msbuild.log` file (hopefully) indicating the issue.
[https://gist.github.com/TorbenJ/40e4fe407d18976bb0d881a606f4a048](url)

I tried to build using `./build.sh` and another time using `./build.sh Linux` with the same results.

**Comment by stephentoub** [comment]
Thanks, @TorbenJ.  The log shows that for some reason it's using the Windows build of SecureString on Linux rather than using the Unix build on Linux.

**Comment by stephentoub** [comment]
@TorbenJ, are you still hitting this?  I know you just opened this a day ago, but that was also just after we added the source for this project, and a few things have changed since, so I'm wondering if the issue might be gone.  I've been unable to reproduce it locally, and it's not reproducing in our CI system.

**Comment by TorbenJ** [comment]
@stephentoub I tried to build it using a fresh Ubuntu 14.04 VM (and a fresh clone of the repo) following the [Steps to Build on Ubuntu](https://github.com/dotnet/corefx/blob/master/Documentation/building/unix-instructions.md#steps-to-build-on-ubuntu).
Still the same issue that it tries to load `oleaut32.dll`.

**Comment by TorbenJ** [comment]
So I rebuilt the project using the desktop version of 16.04 LTS and there are no more errors reported. Only ~100 warnings stating one should add `win7-x64` or `ubuntu.16.04-x64` to project.json and re-run NuGet restore. So I guess it's somehow related to the server image I used.

**Comment by stephentoub** [comment]
Interesting.  @ellismg, @eerhardt, @ericstj, could this be related to RID detection, such that we're incorrectly determining what system we're on when using the "server" edition?

**Comment by ellismg** [comment]
Server shouldn't matter, but I'll take a look @TorbenJ, did you just use the ISO from Ubuntu's site or spin up and Azure VM or something else?

**Comment by TorbenJ** [comment]
@ellismg I used an Amazon AWS VM. Haven't tried Azure so far.

**Comment by ellismg** [comment]
>  I've been unable to reproduce it locally, and it's not reproducing in our CI system.

Interestingly enough, it looks like we are hitting this in CI, but it is not causing jobs to fail?!

See failures in [Ubuntu 14.04](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug_prtest/1067/consoleFull) and [OSX](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/1079/consoleFull).  You'll want to search for "api".

```
22:56:14   Commands:
22:56:14   ./corerun xunit.console.netcore.exe System.Security.SecureString.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonosxtests
22:56:14   
22:56:14   Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-processenvironment-l1-1-0.dll': The specified module could not be found.
22:56:14    (Exception from HRESULT: 0x8007007E)
22:56:14      at Interop.mincore.GetStdHandle(Int32 nStdHandle)
22:56:14      at System.ConsolePal.get_OutputHandle()
22:56:14      at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
22:56:14      at System.ConsolePal.set_ForegroundColor(ConsoleColor value)
22:56:14      at System.Console.set_ForegroundColor(ConsoleColor value)
22:56:14      at Xunit.ConsoleClient.Program.Main(String[] args)
22:56:15   /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/bin/tests/Windows_NT.AnyCPU.Debug/System.Security.SecureString.Tests/dnxcore50/RunTests.sh: line 311: 44815 Abort trap: 6           ./corerun xunit.console.netcore.exe System.Security.SecureString.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonosxtests
22:56:15   Finished running tests. End time=23:02:13. Return value was 134
```

**Comment by ellismg** [comment]
I believe that #8494 will address this issue.  It is very troubling to me that we were not seeing things fail the same way in CI as @TorbenJ was.
