### ISSUE TITLE
Addition ConditionalWeakTable.AddOrUpdate

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#8429]
From https://github.com/dotnet/coreclr/issues/4545

Or indexer setter?

At the moment you need to do 

``` csharp
lock (cwt) {
    cwt.Remove(key);
    cwt.Add(key, newValue);
}
```

Would be nicer if you could just do

``` csharp
cwt[key] = newValue;
```

or

``` csharp
cwt.AddOrUpdate(key, newValue);
```

**Comment by SamuelEnglard** [comment]
I vote for `AddOrUpdate`, it's more inline with the idea behind `ConditionalWeakTable`

**Comment by mellinoe** [comment]
Indeed, `AddOrUpdate` seems to fit well with the current interface. There are no indexers or the like currently, so a method seems appropriate.

**Comment by danmosemsft** [comment]
@mellinoe good to add api-readyforreview?

**Comment by mellinoe** [comment]
@danmosemsft sure

**Comment by terrajobst** [comment]
The API looks good.

**Comment by karelz** [comment]
Anyone wants to pick it up? Should be fairly simple (the API addition will be a bit tricky) ...

**Comment by safern** [comment]
Do we want this for netcoreapp only or do we want to expose it in standard? @mellinoe @terrajobst

**Comment by weshaggard** [comment]
All new APIs have to start out as netcoreapp specific.

**Comment by karelz** [comment]
That's what the 'netfx-port-consider' tracks. When we invest into porting APIs and bug fixes into .NET Framework, we will review all those.

**Comment by danmosemsft** [comment]
Putting those two comments together for @safern -- Standard = .NET Standard, currently 2.0, defined by what's already in Desktop, Mono etc so we cannot add new API to it.
After we ship .NET Standard 2.0 we can consider more API for .NET Standard 2.1 or whatever but it would probably have to be ported to Desktop by then to make it reasonable to have in a standard.

**Comment by safern** [comment]
Ok -- thanks :)
