### ISSUE TITLE
FileSystemWatcher Test failure: File_NotifyFilter_Security, File_NotifyFilter_Size

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#8436]
```
System.IO.Tests.File_NotifyFilter_Tests.FileSystemWatcher_File_NotifyFilter_Security(filter: Attributes) [FAIL]
12:29:55         Changed event did not occur as expected
12:29:55         Expected: True
12:29:55         Actual:   False
12:29:55         Stack Trace:
12:29:55               at System.IO.Tests.FileSystemWatcherTest.ExecuteAndVerifyEvents(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Boolean assertExpected, String[] expectedPaths)
12:29:55               at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String[] expectedPaths, Int32 attempts)
12:29:55               at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String expectedPath, Int32 attempts)
12:29:55               at System.IO.Tests.File_NotifyFilter_Tests.FileSystemWatcher_File_NotifyFilter_Security(NotifyFilters filter)
12:29:55   System.IO.FileSystem.Tests -> d:\j\workspace\outerloop_win---b280fd23\bin\Windows_NT.AnyCPU.Debug\System.IO.FileSystem.Tests\System.IO.FileSystem.Tests.dll
```
```
Discovering: System.IO.FileSystem.Tests
12:29:57   Discovered:  System.IO.FileSystem.Tests
12:29:58   Starting:    System.IO.FileSystem.Tests
12:29:58      System.IO.Tests.File_NotifyFilter_Tests.FileSystemWatcher_File_NotifyFilter_Size(filter: Attributes) [FAIL]
12:29:58         Changed event did not occur as expected
12:29:59         Expected: True
12:29:59         Actual:   False
12:29:59         Stack Trace:
12:29:59               at System.IO.Tests.FileSystemWatcherTest.ExecuteAndVerifyEvents(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Boolean assertExpected, String[] expectedPaths)
12:29:59               at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String[] expectedPaths, Int32 attempts)
12:29:59               at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String expectedPath, Int32 attempts)
12:29:59               at System.IO.Tests.File_NotifyFilter_Tests.FileSystemWatcher_File_NotifyFilter_Size(NotifyFilters filter)
```

**Comment by Priya91** [comment]
@ianhays Can you take a look?

**Comment by ianhays** [comment]
Sure, thanks for the heads up! I haven't seen these failures before. Are they from the same run?

**Comment by Priya91** [comment]
Yeah these are from Windows 7..

**Comment by ianhays** [comment]
Did they fail in the same test pass on the same machine? Do you have a link to the job by any chance?

And do we run tests on win7 only in Outerloop?

I'm trying to determine if the failure is consistent or intermittent.

**Comment by Priya91** [comment]
> Did they fail in the same test pass on the same machine? Do you have a link to the job by any chance?
yeah.. from same test pass on same machine, the test link is [here]
(http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_win7_debug/30/)

> And do we run tests on win7 only in Outerloop?
Yes, Win7 tests are only run in Outerloop , run once daily.

**Comment by ianhays** [comment]
These tests are failing consistently on win7; it is not an intermittent failure but rather a test failure due to platform differences that I was unaware of. Apparently, modifying the size or Security of file passes the "Attribute" filter on Win7.

I don't think we have a way to restrict a test to run on a certain machine configuration. The only thing I can think of making a ConditionalTheory that checks the Environment.OSVersion but [we can't do that just yet](https://github.com/dotnet/corefx/issues/4741).

**Comment by Priya91** [comment]
@ianhays Consider using [PlatformDetection](https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/PlatformDetection.cs). You can add a property ```IsNotWindows7``` to skip on windows 7

**Comment by ianhays** [comment]
That's exactly what I need. Thanks Priya! I'll have this fixed in a little bit.
