### ISSUE TITLE
X509Certificate2.GetECDsaPublicKey fails on UWP

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#8450]
https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Windows/X509Pal.PublicKey.cs

``` C#
        private static ECDsa DecodeECDsaPublicKey(CertificatePal certificatePal)
        {
            using (SafeBCryptKeyHandle bCryptKeyHandle = ImportPublicKeyInfo(certificatePal.CertContext))
            {
                ...
            }
        }

        private static SafeBCryptKeyHandle ImportPublicKeyInfo(SafeCertContextHandle certContext)
        {
#if NETNATIVE
            // CryptImportPublicKeyInfoEx2() not in the UWP api list.
            throw new PlatformNotSupportedException();
#else
            ...
#endif
        }
```

**Comment by bartonjs** [comment]
This is dependent upon CryptImportPublicKeyInfoEx2 being added to https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.CodeAnalysis/PackageFiles/PinvokeAnalyzer_UWPApis.txt. (Which is dependent upon it being added to the actual WACK list)

**Comment by bartonjs** [comment]
@safern I was looking to see if this was fixed in master given the recent UWP work (and new WACK list).  But it doesn't look like X509Certificates tests are running in UWP at all.  Is that something you're aware of?

**Comment by danmosemsft** [comment]
@joperezr for that q

**Comment by joperezr** [comment]
That is a very good point, no we were not aware of it. Usually if we do this, we would log a tracking issue to re-enable those tests back, but we didn't seem to do it this time. Looks like the PR that did it was a maestro update PR, specifically looks like it was a commit made by @jkotas  https://github.com/dotnet/corefx/pull/17755/commits/4197fb68b69c1248e6be79aa8e4b08d2c92777c1

**Comment by jkotas** [comment]
> We didn't seem to do it this time

The issue opened on this was: https://github.com/dotnet/corefx/issues/17764

**Comment by joperezr** [comment]
Thanks for pointing it out. Looks like we have caught this once and logged that issue, but the issue was for both Cng and X509Certificates and we only fixed Cng configurations. I just reopened the issue and will fix the configurations.
