### ISSUE TITLE
API difference between ref assembly and actuall assembly

### ISSUE THREAD

**Issue by SamuelEnglard** [dotnet/corefx#8454]
`System.Reflection.ParameterInfo` defines a protected constructor in mscorlib, but in the ref assembly `System.Reflection` it does not. This prevents me from inheriting from it. While I suspect this is the very reason this is done...

1. Why change the API contract?
2. Why block me from inheriting (even more so only by ref assembly)?

**Comment by AtsushiKan** [comment]
This is already being tracked by this issue.

https://github.com/dotnet/corefx/issues/4997

The TLDR version is "We'd like to enable user-inheritance of Reflection types some day but it's a lot more complicated than exposing a constructor."
