### ISSUE TITLE
RSACertificateExtensions.GetRSAPrivateKey() fails on UWP

### ISSUE THREAD

**Issue by awcullen** [dotnet/corefx#8455]
Since 4.2.0-rc3-24105-00, in UWP, calling RSACertificateExtensions.GetRSAPrivateKey() results in:

System.TypeLoadException occurred
  Message=Could not load type 'System.Security.Cryptography.ECDsa' from assembly 'System.Security.Cryptography.Algorithms, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
  Source=System.Security.Cryptography.X509Certificates

I see in the package that the runtime changed from netstandard1.4 to 1.6. 

4.1.0-rc3-24104 works fine.

**Comment by bartonjs** [comment]
Could you share your whole project.json so I can try to get into the same state?

**Comment by awcullen** [comment]
My library that is calling GetRSAPrivateKey has
```
{
  "supports": {},
  "dependencies": {
    "MetroLog": "1.0.1",
    "NETStandard.Library": "1.5.0-rc3-24104-00", // last release that works
    "StyleCop.Analyzers": "1.0.0",
    "System.Threading.Tasks.Dataflow": "4.6.0-rc3-24104-00"
  },
  "frameworks": {
    "netstandard1.4": {
      "imports": ".NETPlatform5.0" // to support metrolog
    }
  }
}
```

**Comment by awcullen** [comment]
I found in ".nuget\packages\System.Security.Cryptography.Algorithms\4.2.0-rc3-24111-00\ref\netstandard1.4\" 
"System.Security.Cryptography.Algorithms.dll" has the ECDsa type.
So it compiles.
But there is no "\lib\netstandard1.4\" or "\runtimes\win\lib\netstandard1.4\" so it fails at runtime. 

Thanks

**Comment by ericstj** [comment]
So `netstandard1.4` isn't a *runnable* TFM.  It's an abstract/portable TFM that represents the surface area of many app models / concrete TFMs.  The concrete TFM here you'd be using would be from the UWP application referencing this, which should use 
```
  "frameworks": {
    "uap10.0": {}
  },
```

Here is an examples of a project that works fine for me with UWP and the latest Algorithms:
```
{
  "dependencies": {
    "Microsoft.ApplicationInsights": "1.0.0",
    "Microsoft.ApplicationInsights.PersistenceChannel": "1.0.0",
    "Microsoft.ApplicationInsights.WindowsApps": "1.0.0",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.0-rc3-24112-00",
    "System.Security.Cryptography.Algorithms": "4.2.0-rc3-24112-00"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```

**Comment by bartonjs** [comment]
Okay, after chatting with Eric some more we figured it out.  The ECDsa class got excluded from the netcore50 library during a recent change; and so that's causing this error.  I've reproed it locally with Eric's project.json and my test app.

**Comment by awcullen** [comment]
Awesome. Thanks guys.

**Comment by bartonjs** [comment]
@awcullen It looks happy to me with the 24113 packages, mind giving it a go?

**Comment by awcullen** [comment]
Good to go. Thanks again.
