### ISSUE TITLE
System.Collections.Generic.List problem

### ISSUE THREAD

**Issue by m4nd1cm4rk0** [dotnet/corefx#8457]
I have a problem with Contains method in List.cs
Contains will return true even if object that i'am searching for doesn't exist in the List.
I don't know is this something that should work in that way or it is a bug.

       `static void Main(string[] args)
        {
            List<object> Array = new List<object>();
            Employee e1 = new Employee();
            Employee e2 = null;

            Array.Add(5);
            Array.Add(4);
            Array.Add(null);
            Array.Add(e1);
            Array.Add(5);
            Array.Add("banana");

            // returns True, even if e2 is not in the List
            Console.WriteLine(Array.Contains(e2)); 
        }`

**Comment by svick** [comment]
The value of `e2` is `null` and your list does indeed contain `null`. So this looks like the correct behavior to me.

**Comment by m4nd1cm4rk0** [comment]
Yeah, but i want to find e2 object that doesn't exist in the List.

**Comment by m4nd1cm4rk0** [comment]
`public bool Contains(T item)
        {
            if ((Object)item == null)
            {
                for (int i = 0; i < _size; i++)
                    if ((Object)_items[i] == null)
                        return true;
                return false;
            }
            else
            {
                EqualityComparer<T> c = EqualityComparer<T>.Default;
                for (int i = 0; i < _size; i++)
                {
                    if (c.Equals(_items[i], item)) return true;
                }
                return false;
            }
        }`

**Comment by m4nd1cm4rk0** [comment]
I want to find specific object, but instead Contains returns True even if specific object doesn't found in the List.

**Comment by svick** [comment]
There is no `e2` object, `e2` is a variable whose value is `null`.

**Comment by m4nd1cm4rk0** [comment]
Ok, but than it should return false? Right?
I know that Contains method search for null object in the List. but seems wrong to search null object and return true even if that specific object doesn't exist in that List.

**Comment by mellinoe** [comment]
It shouldn't return false. It isn't very common, but you might want to store a `null` value in your List, and `Contains()` should return whether or not `null` is in the list. Are you suggesting that it should always return "false" if you pass in `null`?

**Comment by m4nd1cm4rk0** [comment]
Maybe
