### ISSUE TITLE
Issues with Socket.GetSocketOption for errors on Linux

### ISSUE THREAD

**Issue by roji** [dotnet/corefx#8464]
It seems I've stumbled on some behavior issues with Socket.GetSocketOption. In Npgsql I use a pretty standard pattern for non-blocking socket connect:

```c#
var ep = new IPEndPoint(IPAddress.Parse("127.0.0.1"), 44444);
var socket = new Socket(ep.AddressFamily, SocketType.Stream, ProtocolType.Tcp)
{
    Blocking = false
};
try
{
    socket.Connect(ep);
}
catch (SocketException e)
{
    if (e.SocketErrorCode != SocketError.WouldBlock)
        throw;
}
var write = new List<Socket> { socket };
var error = new List<Socket> { socket };
Socket.Select(null, write, error, -1);
var errorCode = (int)socket.GetSocketOption(SocketOptionLevel.Socket, SocketOptionName.Error);
Console.WriteLine("First getsockopt: " + (SocketError)errorCode);
if (errorCode != 0) {
    var second = (int)socket.GetSocketOption(SocketOptionLevel.Socket, SocketOptionName.Error);
    Console.WriteLine("Second getsockopt: " + (SocketError)second);
    throw new SocketException(errorCode);
}
```

The code above is supposed to fail with a ConnectionRefused since nobody's listening at 44444.

On Linux/mono, as well as on Windows/coreclr and Windows/net451 the output of this code is ConnectionRefused from both GetSocketOption invocations.

However, on Linux/coreclr I curiously get 111 from the first GetSocketOption, and Success from the second.

**Comment by davidsh** [comment]
cc: @ericeil

**Comment by stephentoub** [comment]
It looks like we're missing a translation between error value spaces.  111 is the value of ECONNREFUSED on Linux.

**Comment by roji** [comment]
The error also seems to be cleared when GetSocketOption is called, resulting in the second GetSocketOption reporting success...

**Comment by stephentoub** [comment]
> The error also seems to be cleared when GetSocketOption is called, resulting in the second GetSocketOption reporting success.

That seems to match the docs, which state:
```
Get the error status and clear.
```
That also matches the defined behavior for SO_ERROR:
```
SO_ERROR
              Get and clear the pending socket error.  This socket option is
              read-only.
```
Given the MSDN state it should clear, if it's not doing so on Windows, that would seem like a bug on Windows. @davidsh?

**Comment by roji** [comment]
@stephentoub you're right, the Linux [man page](http://linux.die.net/man/7/socket) states this as well (see SO_ERROR). Curious that both mono on Linux and .NET Framework don't do this.

**Comment by davidsh** [comment]
cc: @CIPop 
>Given that MSDN states it should clear the error, if it's not doing so on Windows, that would seem like a bug on Windows. @davidsh?

Could be a bug in Windows implementation for System.Net.Sockets.  Curious if the bug occurs in .NET Framework Desktop.  Sounds like we need a specific test for this.

**Comment by CIPop** [comment]
> Could be a bug in Windows implementation for System.Net.Sockets. Curious if the bug occurs in .NET Framework Desktop. Sounds like we need a specific test for this.

Ran the test on .Net 4.6.1 and 3.5 on TH2:

```
First getsockopt: ConnectionRefused
Second getsockopt: ConnectionRefused

Unhandled Exception: System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it
   at console_pg.GetSockOptBehavior.RunTest() in S:\Prj\console_pg\console_pg\GetSockOptBehavior.cs:line 38
   at console_pg.Program.Main(String[] args) in S:\Prj\console_pg\console_pg\Program.cs:line 15
```

Since the behavior has already been shipped on so many platforms, we may only be able to change the documentation at this point.

**Comment by stephentoub** [comment]
> Since the behavior has already been shipped on so many platforms, we may only be able to change the documentation at this point.

I'm about to post a fix for the Unix portion of this (the error translation), but we would have to go out of our way to explicitly store the last error and ensure we're using the "right" last one in order to appropriately not clear it.  It's not obvious to me that we could get that "right".  So I think we should have the implementation on Unix match getsockopt and the current documentation, and have it clear. @ericeil?

**Comment by ericeil** [comment]
> It's not obvious to me that we could always get that "right". 

I agree; this would require maintaining the "pending socket error" value across all native socket calls, exactly the way Windows does, whatever that is.  This may not be possible, and even if it *is*, it's going to be very fragile.

I think implementing this as documented, and mentioning it in the "platform differences" notes, sounds like a fine solution.
