### ISSUE TITLE
Boolean expressions evaluated wrong within async method

### ISSUE THREAD

**Issue by hardcodet** [dotnet/corefx#8475]
Have a look at this method that has two identical if statements:

        public async Task Foo()
        {
            int x = 199 + 1;
            if (x == 500)
            {
                throw new AggregateException("WTF");
            }

            await Task.FromResult(1);

            int y = 199 + 1;
            if (y == 500)
            {
                throw new AggregateException("WTF");
            }

            //await Task.FromResult(1);
        }

The second if statement here evaluates to true for now obvious reason and the exception is thrown - there seems to be a compiler issue. In order for the exception not to be thrown (the statement evaluating to false), the second await can be uncommented, or the throw within the if replaced by something else.

Repro attached.

[WebApplication1.zip](https://github.com/dotnet/corefx/files/261183/WebApplication1.zip)

**Comment by svick** [comment]
I don't see any exception being actually thrown in your repro project. But when I step through the method in VS debugger in Debug mode, the second `throw` line looks like it's active. That would mean it's just a debugging issue, not actually incorrect code being executed. Is that what you see?

To me this looks like it might be a bug in the PDB file: there is code to execute after the skipped `throw`, but no source lines to associate with that code, so the previous line is shown instead.

Machine code:

![](http://i.imgur.com/VehFuBp.png)

IL:

```cil
    IL_00b9:  ldloc.s    V_4
    IL_00bb:  brfalse.s  IL_00c9
//000049:             {
    IL_00bd:  nop
//000050:                 throw new AggregateException("WTF");
    IL_00be:  ldstr      "WTF"
    IL_00c3:  newobj     instance void [mscorlib]System.AggregateException::.ctor(string)
    IL_00c8:  throw
    IL_00c9:  leave.s    IL_00e5 // this is the problematic line
```

In any case, this is not about CoreFX, I think [the Roslyn repo](https://github.com/dotnet/roslyn) is the appropriate place to report this.

**Comment by hardcodet** [comment]
Not sure this is just a PDB issue - I discovered it because my unit tests were failing. I assume the error doesn't surface at runtime because it's just thrown on another thread (with await messing up).
Anyway, I'll post it into Roslyn - thanks for the pointer!

**Comment by hardcodet** [comment]
Issue opened on Rosly board:
https://github.com/dotnet/roslyn/issues/11267

Feel free to close here if you don't want to follow.

**Comment by stephentoub** [comment]
Closing as this was moved to the Roslyn repo.
