### ISSUE TITLE
Enable checksumalgorithm:SHA256 for managed code.

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#8479]
see https://github.com/dotnet/roslyn/issues/10451

We will need to generate an rsp file for this for now because it isn't exposed in the csc build task.

**Comment by gkhanna79** [comment]
CoreCLR native binary issue is https://github.com/dotnet/coreclr/issues/4938

**Comment by gkhanna79** [comment]
@weshaggard @joperezr Native binary support for Sha256 checksum has been committed. Can you please add support for mscorlib (aka core lib) when you get to managed binary support for the same?

**Comment by weshaggard** [comment]
@joperezr we also need to enable it for the native binaries that we are building in corefx.

**Comment by joperezr** [comment]
@gkhanna79 
> Can you please add support for mscorlib (aka core lib) when you get to managed binary support for the same?

Will do.

**Comment by weshaggard** [comment]
@joperezr where is the corefx change that enables this option for the managed components?

**Comment by joperezr** [comment]
@weshaggard My change in BuildTools dotnet/buildtools#719 enabled this by default, and since you had already updated to a version of buildtools that contained those changes then managed components was a no-op.
