### ISSUE TITLE
Implement Create methods for better cross-plat Crypto

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#8487]
During the API review of #7688 it was decided that to enable better cross-plat authoring we should have Create() methods on the following crypto base classes:
 ECDsa: Create(), Create(ECCurve), Create(ECParameters)
 RSA: Create(), Create(int), Create(RSAParameters)

This enables creation of the classes without having to special-case for Cng or OpenSsl platforms.

Implementation includes refactoring and cross-compiling to get the logic into algorithms.dll.

This will also eventually apply to .net 4.6.3 but also including:
 ECDiffieHellman: Create(), Create(ECCurve), Create(ECParameters)
 DSA: Create(), Create(int), Create(DSAParameters)

**Comment by steveharter** [comment]
@bartonjs

**Comment by bartonjs** [comment]
(I say "consider", but I mean "we're making a contract change, we need to do this in net463, too" :smile:)

**Comment by steveharter** [comment]
Since only ECDSA added the Create to the contract, this issue will be doing only:
ECDsa: Create(), Create(ECCurve), Create(ECParameters)
and not RSA

**Comment by joshfree** [comment]
This is in release/1.0.0 with https://github.com/dotnet/corefx/pull/8885
