### ISSUE TITLE
Test crashes cross plat don't trigger CI failures in MSBuild

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#8495]
While investigating https://github.com/dotnet/corefx/issues/8425, I noticed a case where a test project was failing in CI, but the build was not being marked as an error.  The best way to reproduce it may be to just revert the change I'm going to merge to fix this issue and run a CI job or local build.

I'm not yet sure where the problems lies.  Is the universal runner not flowing the correct exit code back in this case or is MSBuild just dropping it for some reason?

**Comment by stephentoub** [comment]
I don't think we ported https://github.com/dotnet/corefx/pull/7676 to RC2, and the issue was reported by MSBuild in https://github.com/dotnet/corefx/issues/7658.  If this has to do with an exit code not being reported correctly, maybe that's the cause?

**Comment by ellismg** [comment]
I should be able to test your hunch today with a custom tool runtime build.

**Comment by joperezr** [comment]
Even if we haven't ported that change, I added a condition in dotnet/buildtools#628 that should workaround this issue, so I'm not sure as to why this would fail. I'm not sure where to find the log you are investigating, but are we not longer using [tests.targets](https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets) to run the tests?

**Comment by ellismg** [comment]
Take a look at the log here:

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug_prtest/1067/consoleFull

I think the problem is since the runtime ends up crashing (probably also not the best thing in the world) xUnit never gets to prints the failed line.

**Comment by joperezr** [comment]
I see, yeah if xunit crashes then it would make sense why the target is succeeding. Do you guys suggest perhaps adding "Unhandled Exception" to the regex, or perhaps wait till MSBuild gets @stephentoub fix?

**Comment by ellismg** [comment]
My understanding is we plan to rev the tool runtime to an RC3 in the next few days (after RC2 ships, correct)?  If that's the case, I figure we should just wait.

**Comment by joperezr** [comment]
Moved to 1.1.0 given that we'll wait for the new tool-runtime to get this fixed.
