### ISSUE TITLE
Seg fault in System.Linq.Expressions tests on CentOS in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#8501]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_release_tst_prtest/1042/consoleText
```
Starting:    System.Linq.Expressions.Tests
   System.Linq.Expressions.Tests.Compiler_Tests.NewExpressionwithMemberAssignInit [SKIP]
      870811
   System.Linq.Expressions.Tests.Compiler_Tests.ArrayInitializedWithCapturedInstance [SKIP]
      870811
   System.Linq.Expressions.Tests.Compiler_Tests.TestAndAlso [SKIP]
      870811
   System.Linq.Expressions.Tests.Compiler_Tests.CallOnCapturedInstance [SKIP]
      870811
./RunTests.sh: line 197: 29395 Segmentation fault      ./corerun xunit.console.netcore.exe System.Linq.Expressions.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests
Finished running tests. End time=16:08:44. Return value was 139
error: One or more tests failed while running tests from ''.  Exit code 139.
```
cc: @sergiy-k, @janvorli... I have no idea if this stemmed from CoreCLR or CoreFx, but System.Linq.Expressions is itself pure IL.

**Comment by joshfree** [comment]
@stephentoub have we seen this more than once so far?

**Comment by stephentoub** [comment]
I haven't, no.

**Comment by janvorli** [comment]
@joshfree I am working on it. I can reliably repro it on my Ubuntu if I run the test in a loop. In 1..30 iterations I can hit it.

**Comment by janvorli** [comment]
This 100% repro's the issue in single run:

`COMPlus_HeapVerify=255 ./corerun xunit.console.netcore.exe System.Linq.Expressions.Tests.dll -parallel none -showprogress -xml testResults.xml -notrait Benchmark=true  -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests -method System.Linq.Expressions.Tests.LambdaAddNullableTests.LambdaAddNullableUIntTest`

**Comment by janvorli** [comment]
Hmm, that was some local issue, the small repro doesn't actually repro anything after a rebuild.

**Comment by stephentoub** [comment]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_ubuntu16.04_release_tst/22/consoleText

**Comment by janvorli** [comment]
Fixed by https://github.com/dotnet/coreclr/issues/5183
