### ISSUE TITLE
ReflectionBasedDCS: refactor to avoid concrete adapters in ReflectionXmlFormatReader/Writer

### ISSUE THREAD

**Issue by khdang** [dotnet/corefx#8507]
https://github.com/dotnet/corefx/pull/8418#discussion_r62722072

**Comment by shmao** [comment]
It might be nicer to refactor the code to avoid referencing concrete adapter types in ReflectionXmlFormatReader/Writer. But this seems to be the existing pattern we have for CodeGen based serialization as well. We decided that we wouldn't refactor this particular place.
