### ISSUE TITLE
System.Net.IPAddress and IPv6 zone indices

### ISSUE THREAD

**Issue by lemonmojo** [dotnet/corefx#8509]
I already reported this issue on mono's bugzilla but since it's mainly a .NET issue, I was redirected here.
Here's my original bug entry: https://bugzilla.xamarin.com/show_bug.cgi?id=37724

As per this article (https://en.wikipedia.org/wiki/IPv6_address#Link-local_addresses_and_zone_indices) the syntax of specifying IPv6 zone indices and link-local addresses depends on the platform.
On MS Windows the index is determined by the interface number while on Unix-like OS's (including OS X) the interface name (ie. en0) is used.

System.Net.IPAddress only has support for specifying the interface the MS Windows way in the form of it's "ScopeId" property which is a "long". So this causes issues on non-Windows systems and in some cases, specifically where the MS Windows notation is not supported as an alternate way of specifying the interface it renders this class completely useless.
Even worse, IPAddress.Parse succeeds in parsing an IP Address with a zone index specified as name (ie. %en0") but totally ignores/scraps the zone index resulting in a false positive.

At least on OS X (can't speak for other Unix or BSD based platforms) one can alternatively specify the zone index using the index of the interface. This is not well known or widely used though and requires finding an interface's index instead of just using it's name.

So on platforms where the number-based notation is available but not the default, IPAddress.Parse could be extended to look up the interface index using the System.Net.NetworkInformation.NetworkInterface class. On systems where this "fallback" isn't available this wouldn't work though and apart from introducing a new property and adjusting the parsing code I have no suggestion for this scenario.

**Comment by davidsh** [comment]
cc: @CIPop @stephentoub

**Comment by CIPop** [comment]
Thanks for raising the issue @lemonmojo! Interesting coincidence: we just had the conversation about ZoneIDs the last two weeks internally regading Uri parsing.

Would it be possible to add more details about your scenario? Asking because the RFC specifies that ZoneIDs should be used only in debugging scenarios and for link-local addresses.

One thing that we could do is support a `string ZoneId` property that will return the correct zone and that can be interpreted any way the application needs. I'm not sure if it would be easy to map Unix interface names to interface numbers and even if we would do that, would it be useful?

Furthermore, Uri appears to be interpreting ZoneId from a browser perspective, removing the ZoneId.

From our discussion (which may or not be relevant to your case):

> According to the RFC, the Zone ID are something to be used only on link-local addresses:
```
   The URI syntax specification [RFC3986] states that URIs have a global
   scope, but that in some cases their interpretation depends on the
   end-user's context.  URIs including a ZoneID are to be interpreted
   only in the context of the host at which they originate, since the
   ZoneID is of local significance only.
   It would therefore be highly desirable for a browser to remove the
   ZoneID from a URI before including that URI in an HTTP request.
```

>The Security section of the RFC further clarifies this:
```
   To limit this risk, implementations MUST NOT allow use of this format
   except for well-defined usages, such as sending to link-local
   addresses under prefix fe80::/10.  At the time of writing, this is
   the only well-defined usage known.
```

References:
* RFC: https://tools.ietf.org/html/rfc6874
* Browser discussion: http://comments.gmane.org/gmane.ietf.ipv6/31528

**Comment by lemonmojo** [comment]
Thanks for getting back to me @CIPop!

Let me start by saying that I'm by no means an IPv6 expert. I stumbled upon this issue because in my application, [Royal TSX](https://www.royalapplications.com/ts/osx) I'm using a third party library ([SecureBlackbox](https://www.eldos.com/sbb/) by ELDOS) to establish SSH tunnels. Now, since my app is being used by thousands of customers in all kinds of network environments, I have no control over what kind of destination host type my customers use. It could be a hostname, IPv4 address, IPv6 address or even an IPv6 link-local address. So basically I just pass the destination host string the user enters to the third party library which then parses it, and in the case of an IP address, wraps it into an System.Net.IPAddress object for further use.

Since the library isn't open source I don't know what exactly happens with this IPAddress object down the line. What I do know however, is that by passing a Unix style IPv6 link-local address (ie. %en0) to the IPAddress.Parse method the zone index gets lost which obviously can lead to getting a completely different address than was being passed in.

IMHO, if the IPAddress object doesn't support zone indexes specified as string, the Parse and TryParse methods should either just throw an exception (or return false) when such an address is passed in or be able to translate the zone index to the corresponding numeral ScopeId.

Obviously the best solution would be to have full support for these string based Unix style zone indexes just like you suggested.

Regarding mapping interface names to zone indexes, this is actually what I did as a workaround to the issue in my app in conjunction with the 3rd party library. I'll include the code I'm using for reference.
Basically it remaps an IPv6 link-local address's interface name to the corresponding interface number and returns an IPv6 link-local address string that can safely passed to the IPAddress.Parse method.

```cs
public static class BSDStyleIPv6LinkLocalAddress
{
	public static bool TryParse(string ipAddressString, out string windowsStyleLinkLocalIPv6Address)
	{
		windowsStyleLinkLocalIPv6Address = null;

		try {
			IPAddress ipAddr;
			bool parseSuccess = IPAddress.TryParse(ipAddressString, out ipAddr);

			if (!parseSuccess ||
				!ipAddr.IsIPv6LinkLocal) {
				return false;
			}

			const string RE_ZONE_STRING = "%.*$";
			Regex RE_ZONE = new Regex(RE_ZONE_STRING);

			string zoneIndexStr = string.Empty;

			Match zoneIndexMatch = RE_ZONE.Match(ipAddressString);

			if (zoneIndexMatch == null ||
				!zoneIndexMatch.Success) {
				return false;
			}

			zoneIndexStr = zoneIndexMatch.Value;

			if (string.IsNullOrWhiteSpace(zoneIndexStr) ||
				zoneIndexStr.Length <= 1) {
				return false;
			}

			zoneIndexStr = zoneIndexStr.Substring(1);

			int zoneIndex;

			if (int.TryParse(zoneIndexStr, out zoneIndex)) { // Is already a Windows-style numeric zone index
				return false;
			}

			zoneIndex = -1;
			NetworkInterface[] ifaces = NetworkInterface.GetAllNetworkInterfaces();

			for (int i = 0; i < ifaces.Length; i++) {
				NetworkInterface iface = ifaces[i];

				if (iface == null ||
					string.IsNullOrEmpty(iface.Id) ||
					!iface.Id.Equals(zoneIndexStr, StringComparison.InvariantCultureIgnoreCase)) {
					continue;
				}

				zoneIndex = i + 1;
				break;
			}

			if (zoneIndex < 0) {
				return false;
			}

			windowsStyleLinkLocalIPv6Address = RE_ZONE.Replace(ipAddressString, "%" + zoneIndex);

			return true;
		} catch (Exception) { }

		return false;
	}
}
```

**Comment by CIPop** [comment]
Thanks @lemonmojo for explaining the scenario and for providing the workaround code!

@ericeil @stephentoub Please review the request and the Milestone marking.

**Comment by ericeil** [comment]
It sounds like we should definitely address this in IPAddress.Parse, which should be able to parse address strings that conform to the convention on the host OS.  

As for providing an alternative to IPAddress.ZoneId, I'd like to understand the use cases better.  @lemonmojo, do I understand correctly that your interest in that property was primarily aimed at finding a better workaround for the IPAddress.Parse problem?  If Parse could handle ZoneIDs expressed as interface names, would you still have a need for a string-valued ZoneId property?

**Comment by lemonmojo** [comment]
@ericeil My case is that my users can enter arbitrary string based data as a destination host which I then pass to a 3rd party library which parses it and ultimately opens an SSH tunnel. If the 3rd party library detects an IP address, it calls IPAddress.Parse which results in the problem I'm having since the string based interface name is lost in the process.

Since the library isn't open source, I don't know how exactly they use the IPAddress object after IPAddress.Parse. I'm sure though that they access the ZoneId property since some of my connections won't work without the workaround code I previously attached.

I guess both properties make sense. The integer based ZoneId to not break any existing code and a new string based (ie. InterfaceName) property to be future- and x-plat-proof.
The IPAddress.Parse method should then be able to set both properties to the correct values.

Examples:
* If an integer based zone index is provided, set the ZoneId to that value and try to map the interface index to the interface name if available. If the interface cannot be found, set InterfaceName to string.Empty.
* If a string-based interface name is provided, set the InterfaceName property to that value and find the interface index corresponding to the name and if successful set the ZoneId property to the interface index.

I'm not sure if this would work on all platforms though. I'm mainly an OS X guy so I can only speak for that platform and it certainly works in my scenario.

Hope that helps!

**Comment by ericeil** [comment]
I just tried a test on the current CoreFx running on Ubuntu 14.04; the following address strings were correctly parsed:

```
fe80::1%lo
fe80::1%eth0
```

The resulting IPAddress objects had `ZoneId`s of 1 and 2, respectively, on my machine.  Note that the underlying native sockets API on Linux *and* OSX does deal directly in numeric IDs for these; the difference from Windows is just in how address strings are parsed, by APIs such as `getaddrinfo`.

`IPAddress.ToString` appears to also do the "right thing" with these, as I end up with the original address strings (with names, rather than numeric indexes).

So, I suspect this has already been fixed.  @lemonmojo, can you check whether your scenario is working on the most recent (RC2) CoreFx release?

I will work on adding some new test cases to ensure this doesn't regress.

**Comment by lemonmojo** [comment]
@ericeil Awesome news! Looks like this is implemented in [pal_networking.cpp](https://github.com/dotnet/corefx/blob/6eed3985aa246946ff66016a4972d55525098f9e/src/Native/System.Native/pal_networking.cpp#L253).
Unfortunately, I can't test it since I'm not using CoreFx for my app but mono. Do you know if this is something that will make it to mono in the near future?

**Comment by ericeil** [comment]
> Do you know if this is something that will make it to mono in the near future?

I don't know; you'll want to follow up with them.

**Comment by lemonmojo** [comment]
Will do, thx for your help!
