### ISSUE TITLE
Cleanup dependencies on System.Diagnostics.Contracts

### ISSUE THREAD

**Issue by justinvp** [dotnet/corefx#8510]
Code Contracts are not being maintained in .NET Core and `Debug.Assert` is being used in favor of `Contract.Assert`, yet many CoreFX components still depend on `System.Diagnostics.Contracts` in their implementation.

https://github.com/dotnet/corefx/search?l=json&p=1&q=%22System.Diagnostics.Contracts%22&type=Code

Could we start removing dependencies on `System.Diagnostics.Contracts` (similar to how most dependencies on `System.Collections.NonGeneric` have been removed) or is there a reason to keep the dependencies the way they are?

cc: @weshaggard

**Comment by weshaggard** [comment]
cc @KrzysztofCwalina @stephentoub 

See some of the conversations at https://github.com/dotnet/corefx/issues/503, while it might be nice to clean-up these things I kind of would like to keep them at least until we understand more of the future code contract support in the language. Some of them might be useful if we try to automate converting to a new model .

**Comment by justinvp** [comment]
What if we added an internal DEBUG-only version of the code contract API surface under src/Common, that could be included in DEBUG builds of packages currently using contracts? Then we could remove the package dependencies while keeping the existing annotations in the source code.

**Comment by weshaggard** [comment]
I'm not sure this extra complexity is worth it for just this dependency as it exists everywhere and there isn't much value in breaking it.

**Comment by justinvp** [comment]
It just seems odd to me that in the new "lean" world of .NET Core, where dependencies have been carefully considered and cleanly factored, there are a bunch of packages depending on a package that's effectively "legacy".

**Comment by justinvp** [comment]
BTW, we're not talking about a huge surface area here... The vast majority of existing uses are `Contract.EndContractBlock`, with small number of `Contract.Requires`, `Contract.Ensures` attributes in some packages.

**Comment by weshaggard** [comment]
Yes I realize it is a little odd, but in the end it doesn't actually eliminate much beyond a facade dependency because this contract is implemented in the core assembly.

That said I'm interested in seeing what one of these PR's looks like. Don't spend a ton of time but pick out one representative library and submit a PR for review.

**Comment by justinvp** [comment]
Actually, maybe this isn't as much of as wart as I think it is...

I see that the project.json for `System.Net.Http` has a dependency on `System.Diagnostics.Contracts`: https://github.com/dotnet/corefx/blob/0953751fb947b5a826b2fc5f3a1350c73c9f92cd/src/System.Net.Http/src/project.json#L14

But I don't see that dependency listed in `System.Net.Http`'s nuget package at: https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Net.Http

Is this because `System.Diagnostics.Contracts` is a facade, or something else?

**Comment by weshaggard** [comment]
I don't think it is because it is a facade but instead it is because the methods are conditioned on CONTRACTS_FULL which we don't define. https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Contracts/ref/System.Diagnostics.Contracts.cs#L26. So from a release/package prospective it doesn't actually show up in the dependency list.

**Comment by justinvp** [comment]
> So from a release/package prospective it doesn't actually show up in the dependency list.

That makes sense, thanks. Glad the packager is smart enough not to include it as a dependency in the released packages.

I do see that [`System.Reflection.TypeExtensions`](https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Reflection.TypeExtensions) is the only package in CoreFX that has a release dependency on `System.Diagnostics.Contracts`, I assume because of [it's use of `Contract.ForAll`](https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/Common/src/Internal/Reflection/Execution/Binder/DefaultBinder.cs#L720), which is not conditional.

In any case, since all released packages other than that don't actually have the dependency, I agree it's not really worth cleaning up (at least not yet), so I'm going to go ahead and close the bug.

**Comment by weshaggard** [comment]
Thanks @justinvp. I would be fine if you wanted to clean-up TypeExtensions to remove its dependency.
