### ISSUE TITLE
Add the notion of metadata to DiagnosticsSource

### ISSUE THREAD

**Issue by avanderhoorn** [dotnet/corefx#8511]
DiagnosticsSource has been around for a while now and as more sites are instrumented and more listeners come online, it is becoming evident that there is a need for metadata to be provided as part of the system - specifically, the notion of collecting `timestamps`, `duration`, `correlationid` and possibly `stack`, `processid` and `threadid`. 

These concerns are currently being tracked in an inconsistent manner across the publisher and subscriber code bases and has lead to several problems (i.e. different listeners coming up with different durations or timestamps, correlations not being determined correctly, listening to more events than are needed just to calculate duration, etc). Hence, after seeing issues like #8498 arise, it has been determined that the correct place isn't in the publisher or the subscriber, but most likely in the underlying subsystem - DiagnosticsSource.  

This issue is to track this discussion and determine the best way to start including this data into the system. Considerations that need to be had are as follows:
- Can we get these updates in place before RTM/RTW lockdowns?
- Can we make these changes in a non breaking way, given the fact that people are already taking a dependency on DS today?
  - A possible solution here is to have two subscription methods which listeners can use, listen without metadata (what they would be using today) and listening with metadata. Other solutions are also possible.
- Is there the need for the subscribers to dictate which metadata they would like collected (i.e. if no listeners want the stack, then the stack wouldn't be collected)?
- Can the system be optimized so that to calculate durations, listener don't have to listen to both the `begin`/`end` events?
- To do this work, do we need to take any extra dependencies, and if so does it matter?
- Can correlations between `begin`/`end` events be provided in a deterministic way?

Obviously given where things are at timing wise with release schedules, we need to see what we think is the right solution and what we can get done in the time we have. Assuming this work is done, we can also go through and cleanup some of the publishers code and simply things greatly.

// @vancem @stephentoub (note this should be assigned to @vancem for the time being).

**Comment by danmosemsft** [comment]
@brianrob @valenis is this in plan for 2.0? if not please change to future

**Comment by brianrob** [comment]
@danmosemsft, FYI, we will be triaging all of the System.Diagnostics.Tracing bugs on Thursday, so will take care of this one at the same time.

**Comment by karelz** [comment]
@avanderhoorn from triage discussion: @vancem thinks this is addressed by `System.Diagnostics.Activity`.
Closing for now, feel free to reopen if you think it does not fully address your request.
