### ISSUE TITLE
ApiCompat issues with System.Runtime.Extensions

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#8516]
While enabling ApiCompat by default in our builds https://github.com/dotnet/corefx/pull/8513 we discovered the following compat errors:

netstandard15aot

```
MembersMustExist : Member 'System.Environment.Exit(System.Int32)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Environment.GetCommandLineArgs()' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Environment.MachineName.get()' does not exist in the implementation but it does exist in the contract.
```

@tarekgh you added that configuration what are the plans for getting correct support for these APIs?

**Comment by tarekgh** [comment]
netstandard15aot is mainly for corert and all these APIs are exist in System.Private.Corelib.dll which built for corert. so we need to update the targeting Pack but as no-one is going to consume netstandard15aot for now so I have moved the issue to the future milestone after talking to @weshaggard
