### ISSUE TITLE
Tests should not be built if /p:SkipTests=true is passed

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#8524]
Noticed during a local build of the repo on my Windows machine, with the following flags:

```cs
build /p:ConfigurationGroup=Release /p:SkipTests=true
```

that the tests are still being built, although not run. Would it be possible to add some logic to forego building the tests if `SkipTests` is passed?

cc @mellinoe

**Comment by mellinoe** [comment]
Could you look at the discussion [here](https://github.com/dotnet/corefx/issues/8385) and see if it addresses this? You should be able to pass `/p:buildtests=false to avoid building those projects.

**Comment by jamesqo** [comment]
@mellinoe Sounds awesome, I did not know about that property (maybe we should consider adding this to the documentation). Thank you!

**Comment by maririos** [comment]
Thanks @jamesqo for the suggestion. 
I'm currently working in a change that involves the exposure of the properties we have and when to use them (it would include documentation) :)
