### ISSUE TITLE
WinHttpHandler not updating response state with error from server when client supports multiple TLS protocols 

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#8538]
Might be a test bug. Noticed this while adding HttpClientHandler.SslProtocols property to Windows.

System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test.GetAsync_DisallowTls10_AllowTls11_AllowTls12

```
   Assert.Throws() Failure
    Expected: typeof(System.Net.Http.HttpRequestException)
    Actual:   typeof(System.Threading.Tasks.TaskCanceledException): A task was canceled.
    Stack Trace:
          at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
       s:\GitHub\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs(392,0): at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
       --- End of stack trace from previous location where exception was thrown ---
          at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by stephentoub** [comment]
This fails every time I run it locally, and it's failing in CI now that it's been re-enabled.

**Comment by Priya91** [comment]
@davidsh @CIPop Debugged through this, and the test is waiting for state to be updated by the WinHttpSendRequest native winhttp API [here](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs#L851). I'm not sure how to debug further to identify the problem, can you take a look..

cc @karelz @steveharter @ianhays

**Comment by davidsh** [comment]
This looks like a WinHTTP bug.  It is not giving us back any errors from the Tls connection failure.  So, it basically "hangs" since we get notifications that the async call for WinHttpSendRequest is done.

I got traces and I'm contacting the WinHTTP team for analysis.

**Comment by davidsh** [comment]
I discussed this with the WinHTTP team. It seems this is a bug in our loopback test server that is doing the TLS/SSL handshake. 

From the WinHTTP team:

The client does TLS fallback to TLS1.1 because it gets SEC_E_ALGORITHM_MISMATCH during the TLS1.2 negotiation, and the server never responds to the TLS1.1 client hello. It’s waiting on a response from the server, and the receive timeout is infinite.  So it will wait until the connection is terminated or the server responds. 
The root of the issue is the loopback server is not responding correctly to TLS/SSL handshakes.  It should be responding to both client hellos in the same way by sending a TLS 1.0 server hello since it allows that protocol.

So, this is really a test bug.

**Comment by stephentoub** [comment]
> So, this is really a test bug with the loopback server.

The loopback server is using SslStream for the handshake.  Do you mean it's a bug in how the loopback server is using SslStream (which would be a test bug), or a bug in SslStream (which would be a product bug)?

**Comment by davidsh** [comment]
>The loopback server is using SslStream for the handshake. Do you mean it's a bug in how the loopback server is using SslStream (which would be a test bug), or a bug in SslStream (which would be a product bug)?

Hmm...that actually is a good question.  Maybe then it is a bug in SslStream itself that we have uncovered via this HTTP test.  I'll put back 'bug' until we figure this out.

cc: @CIPop

**Comment by danmosemsft** [comment]
1 week estimate

**Comment by danmosemsft** [comment]
Expect this issue would uncover itself during customer development phase: workaround potentially to change TLS protocol. We are moving this out to Future on this basis however @davidsh can you please open a doc bug for 2.0 to make sure the workaround is discoverable as it's not something folks will likely stumble on.

**Comment by davidsh** [comment]
>Expect this issue would uncover itself during customer development phase: workaround potentially to change TLS protocol. We are moving this out to Future on this basis however @davidsh can you please open a doc bug for 2.0 to make sure the workaround is discoverable as it's not something folks will likely stumble on.

@dan Where do doc bugs get opened?  This repo?  Or the new one based on docs.microsoft.com?

**Comment by danmosemsft** [comment]
@davidsh they go in https://github.com/dotnet/docs and @mairaw then takes them.

**Comment by karelz** [comment]
FYI: We should not open bugs in docs repo, until we have clear guidance written form engineering team.
It is ok to create documentation bug in CoreFX to track the "we need to write the guidance", I can mark it Post-ZBB. Just tag me on it @davidsh.

**Comment by CIPop** [comment]
I've verified this is not related to #16516: I can repro locally.
