### ISSUE TITLE
S.R.CS.Unsafe: Adding a Copy(ref T, ref U) overload

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#8540]
Right now we support copying from a pointer to a reference, and a reference to a pointer via `Unsafe.Copy`, but not between two references. We should add an overload with the following signature:

```cs
public static class Unsafe
{
    public static void Copy<T, U>(ref U destination, ref T source);
}
```

that copies `sizeof(T)` bytes from `source` to `destination`. Example usages:

```cs
// Reinterpret binary data
byte[] array = { 0x01, 0x02, 0x03, 0x04 };
int asInt = 0;
Unsafe.Copy(ref asInt, ref array[0]);
Assert.Equal(0x04030201, asInt);

// Object-to-pointer
public unsafe static void* GetCurrentAddress(this object obj)
{
    var result = default(IntPtr);
    Unsafe.Copy(ref result, ref obj);
    return result.ToPointer();
}

// As-style functionality extended to structs
public static ImmutableArray<T> FakeAsImmutable<T>(this T[] array)
{
    var result = default(ImmutableArray<T>);
    Unsafe.Copy(ref result, ref array);
    return result;
}
```

cc @mellinoe @nietras @jkotas

**Comment by jkotas** [comment]
What would the implementation look like? What would be allowed combinations of T and U?

This overload feels too dangerous to me because of it does number of it does multiple unsafe operations, without them being visible.

**Comment by jamesqo** [comment]
> What would the implementation look like?

Basically the same thing we have for the existing `Copy` overloads, e.g.

```
.method public hidebysig static void Copy<T, U>(!!U& destination, !!T& source)
    cil managed aggressiveinlining
{
    .maxstack 2
    ldarg.0
    ldarg.1
    ldobj !!T
    stobj !!T
    ret
}
```

> What would be allowed combinations of T and U?

There wouldn't be any constraints on T or U (I realize this could lead to mishaps in the case where `sizeof(T) > sizeof(U)`, but if this is the Unsafe class then why not?)

> This overload feels too dangerous to me because of it does number of it does multiple unsafe operations, without them being visible.

The exact same effect can be achieved with `Unsafe.Copy(Unsafe.AsPointer(ref dest), ref src)`; this overload just shortens the syntax (although you have to declare an unsafe block). To be fair, though, you can call `Unsafe.As` without any errors from perfectly "safe" C# code.

**Comment by jkotas** [comment]
> mishaps in the case where `sizeof(T) > sizeof(U)`

There are number of other cases where mishaps can happen - alignment is off and the platform requires aligned writes, or the GC layout of T and U is different.

> though, you can call  `Unsafe.As` without any errors from perfectly "safe" C# code

The difference is that you see the unsafe cast in the code - you do not see it with the `Unsafe.Copy`.

**Comment by GSPP** [comment]
This is the most unsafe class in the whole framework. I don't think preventing usage errors is a priority here. There priority should be exposing raw capability.
