### ISSUE TITLE
Impossible to create UdpClient on shared port

### ISSUE THREAD

**Issue by onovotny** [dotnet/corefx#8552]
As per the discussion here: https://github.com/dotnet/corefx/pull/5953#issuecomment-219304032

With the removal of `Client` from `UdpClient`, it's now impossible to create a `UdpClient` instance that can listen on a shared port if the port is already in use. The core issue is that the ctor of `UdpClient` creates the socket. The `ExclusiveAddressUse` is a property that evaluates after the ctor, so it's too late.

Today, this is accomplished by using the default `UdpClient` ctor, then setting a bunch of options on the socket/client and then calling `udpClient.Client.Bind(localEndpoint)`. This allows for the socket to be setup as a shared socket before binding.

We need a way to create a `UdpClient` while specifying exclusive address use is false.

One suggestion could be to add another ctor parameter with that flag. Another might be to add a collection of socket options.

**Comment by davidsh** [comment]
cc: @stephentoub @CIPop @himadrisarkar

**Comment by onovotny** [comment]
Can we please get this into 1.0? It really shouldn't be that complicated and blocks use of multicast without nasty hacks.

Here's the gross workaround to use UdpClient and get at the Socket:

```csharp
static Socket GetSocketFromUdpClient(UdpClient client)
        {
            var mi = GetSocketMember.Value as MethodInfo;
            if (mi != null)
            {
                return (Socket)mi.Invoke(client, null);
            }
            var fi = GetSocketMember.Value as FieldInfo;
            if (fi != null)
            {
                return (Socket)fi.GetValue(client);
            }

            throw new NotSupportedException("Could not locate Socket");
        }

        static readonly Lazy<MemberInfo> GetSocketMember = new Lazy<MemberInfo>(GetSocketMemberImpl);

        static MemberInfo GetSocketMemberImpl()
        {
            // See if there's a client prop
            var pi = typeof(UdpClient).GetRuntimeProperties().FirstOrDefault(p => p.PropertyType == typeof(Socket));
            if (pi != null)
                return pi.GetMethod;

            var mi = typeof(UdpClient).GetRuntimeFields().First(fi => fi.FieldType == typeof(Socket));
            return mi;
        }
    }
```

**Comment by onovotny** [comment]
Appears that this will be fixed in https://github.com/dotnet/corefx/pull/8603

**Comment by stephentoub** [comment]
Thanks. Client was added back. Closing.

**Comment by christianhuening** [comment]
Hm does using the Client property of UdpClient actually work for you to use a shared port? 
I am testing on Windows 10 and macOS using the latest version of everything.

On Windows 10 I have to use: 
`            udpClient.Client.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, true);`
for it to work.
Using only
`            udpClient.Client.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ExclusiveAddressUse, false);`
doesn't do a thing on windows and I receive an error.

On macOS I receive an error as follows, when using:
`            udpClient.Client.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ExclusiveAddressUse, false);` 
Error:

> System.Net.Sockets.SocketException : Operation not supported
  at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
  at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
  at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Boolean optionValue)

While using:
`            udpClient.Client.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, true);`
on macOS does not throw and exception, but does not work for me either. 

The property udpClient.ExclusiveAddressUse behaves accordingly on Windows 10 and macOS.

Is there anything I am missing or doing wrong here?

**Comment by onovotny** [comment]
@christianhuening Here's the code I'm using to do this:
https://github.com/onovotny/Zeroconf/blob/master/Zeroconf.DotNetCore/NetworkInterface.cs#L84-L113

**Comment by christianhuening** [comment]
@onovotny Thanks! You did a zeroconf/bonjour thing for .net core? Awesome! Might switch to your solution alltogether ;-)

**Comment by onovotny** [comment]
@christianhuening for now, it only supports service discovery, but I'd welcome any PR's for advertisement/publishing

**Comment by christianhuening** [comment]
@onovotny What exactly is the purpose of https://github.com/onovotny/Zeroconf/blob/master/Zeroconf.DotNetCore/NetworkInterface.cs#L92-L99
? 
You're setting ExclusiveAddressUse = false two times.
Does that not throw on macOS / Linux for you?

**Comment by onovotny** [comment]
Can't say I'm 100% certain of why anymore, but I thought I recalled some issue where it had to be set twice for some strange reason.

As to macOS/Linux, I haven't done much/any testing there, but it does work with Xamarin Android and iOS along with .NET Desktop and UWP.
