### ISSUE TITLE
missing System.Threading.Thread VolatileRead/VolatileWrite/MemoryBarrier methods or porting documentation

### ISSUE THREAD

**Issue by zpodlovics** [dotnet/corefx#8560]
Recently I started porting some concurrent data structure to coreclr and I ran into this issue. Maybe I missed some api / documentation / deprecation notices, but the VolatileRead(*), VolatileWrite(*), MemoryBarrier() methods seems missing from System.Threading.Thread class [1]. However the coreclr repo has an implementation [2], and also has some documentation reference [3]. Please note, I am perfectly fine to left out these methods from the api in order to simplify it (in this case could somebody please give me a pointer about these decisions?).

[1] https://github.com/dotnet/corefx/blob/master/src/System.Threading.Thread/ref/System.Threading.Thread.cs#L13
[2] https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/Thread.cs#L1477
[3] https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/Volatile.cs#L20

**Comment by stephentoub** [comment]
The ```Volatile``` class (which has methods like ```Read``` and ```Write```) is recommended in general instead of using ```Thread.Volatile*```.

**Comment by zpodlovics** [comment]
Yes, I know that. But I still had to check every possible implementation and do the measurements if the VolatileRead(*)/VolatileRead(*) implementation should exists. There could be significant differences between the clr implementations, and these implementations could change later. For example the mono jit engine had significantly better (and faster) code for the VolatileRead/VolatileWrite methods (they improved it significantly in the 4.x series). I know that the coreclr jit engine will replace these Read/Write methods with inlined native instructions. Also corert and llilc will probably have their own volatile related codegen implementation.

**Comment by joshfree** [comment]
@sergiy-k

**Comment by kouvel** [comment]
These will be added back as part of #11632
