### ISSUE TITLE
LoadFromAssemblyName_ValidTrustedPlatformAssembly test failing on Unix builds pulling latest coreclr

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#8563]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_debug_tst_prtest/1118/consoleText
```
System.Runtime.Loader.Tests.AssemblyLoadContextTest.LoadFromAssemblyName_ValidTrustedPlatformAssembly [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.IO.FileLoadException)
      Actual:   (No exception was thrown)
      Stack Trace:
            at System.Runtime.Loader.Tests.AssemblyLoadContextTest.LoadFromAssemblyName_ValidTrustedPlatformAssembly()
```

**Comment by gkhanna79** [comment]
This is expected outcome of https://github.com/dotnet/coreclr/pull/4969 and I was waiting for CoreCLR change to come through to push CoreFX side of changes.

**Comment by stephentoub** [comment]
> I was waiting for CoreCLR change to come through to push CoreFX side of changes

Ok. Note that not all of our CoreFx legs pull CoreCLR from packages; some pull the latest successful build from the CoreCLR repo.  So in the future if you know that a CoreFx test is going to be broken by a CoreCLR change, it's a good idea to first disable that test in CoreFx.

**Comment by gkhanna79** [comment]
Closing this since the change was undone and corresponding test fix is being tracked by https://github.com/dotnet/corefx/issues/8643
