### ISSUE TITLE
Restore the use of reflection methods with binding flags in Microsoft.CSharp

### ISSUE THREAD

**Issue by VSadov** [dotnet/corefx#8577]
Reflection used to expose APIs like

``` C#
// allocates nothing in steady state
return type.GetMethod(name, BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, ...);
```

In CoreFX the surface was reduced to minimum "GetMethods() forcing the following solution:

``` C#
       // allocates array with all methods each time
       MethodInfo[] methods = type.GetMethods();
       foreach (var method in methods)
       {
            if (method.IsStatic && method.Name == name)
          return methods;
       }
```

The second is worse performance-wise and we should be getting the original API with binding flags back.
Make sure that Microsoft.CSharp is switched back to using that API

**Comment by joshfree** [comment]
Moving to 1.1

**Comment by karelz** [comment]
Next step: Identify call sites and fix them in batches (don't need to fix all at once).
