### ISSUE TITLE
System.Net.WebSockets.Client.Tests.ClientWebSocketTest.SendAsync__MultipleOutstandingSendOperations_Throws failed in CI

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#8581]
On Windows NT Release:

System.Net.WebSockets.WebSocketException : Unable to connect to the remote server\r\n---- System.Net.WebSockets.WebSocketException : Unable to connect to the remote server\r\n-------- System.Net.Http.WinHttpException : The operation has been canceled

[Details](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/1316/testReport/junit/System.Net.WebSockets.Client.Tests/ClientWebSocketTest/SendAsync__MultipleOutstandingSendOperations_Throws_server__wss___corefx_net_cloudapp_net_WebSocket_EchoWebSocket_ashx_/)

**Comment by davidsh** [comment]
Probably due to network congestion contacting the Azure test server.

**Comment by davidsh** [comment]
@danmosemsft Did this in CI?  Can you provide a link to the CI build?  Or did this just happen on your dev box while running tests?

**Comment by davidsh** [comment]
closing this for now since this is an external Azure issue that only happens occasionally
