### ISSUE TITLE
IntPtr and UIntPtr should implement the IEquatable<T> interface

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#8592]
Both are structs, overload ==, and even have [specialized implementations](https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/EqualityComparer.cs#L64-L67) for the default `EqualityComparer`, yet they don't implement `IEquatable<T>` (or override `Equals`). Should we consider making them implement the interface?

If there's no particular reason why they shouldn't, then here is the API proposal:

```cs
public struct IntPtr : IEquatable<IntPtr>
{
    public bool Equals(IntPtr other);
}

public struct UIntPtr : IEquatable<UIntPtr>
{
    public bool Equals(UIntPtr other);
}
```

**Comment by omariom** [comment]
Yes! 
To avoid allocation I had to pass an `IEqualityComparer`  to dictionaries having `IntPtr`s as `TKey`.

**Comment by jkotas** [comment]
It has been done in CoreRT/.NET Native a while ago. We should just do this in CoreCLR as well. Not much to think about/design here.

**Comment by jamesqo** [comment]
@jkotas Awesome that this got accepted! I will submit a PR for it later.

**Comment by tannergooding** [comment]
I think this is in a similar vein to https://github.com/dotnet/corefx/issues/10457.

**Comment by jkotas** [comment]
#10457 needs careful thought about the design. This one does not.
