### ISSUE TITLE
DataTable future?

### ISSUE THREAD

**Issue by kenticomartinh** [dotnet/corefx#8597]
Hi, there is a newly introduced (empty) type System.Data.DataTable in RC2, is this some sort of workaround that will be removed in final, or do you plan to extend it and keep DataTable and related classes as part of the core framework? I am asking because our code similarly to lot of others relies on DataSet / DataTable structures and we need to outline some strategy how to address this or wait.

**Comment by saurabh500** [comment]
@kenticomartinh The empty `DataTable` class was added to complete the interfaces. 
We are looking at options for `DataSet` and `DataTable` for .Net Core. However the `DataTable` and `DataSet` API (or their replacement) will make it in only after version 1.0

**Comment by saurabh500** [comment]
The effort will be a part of the issue at https://github.com/dotnet/corefx/issues/8597

**Comment by kenticomartinh** [comment]
Thank you for a quick response. We thought it may be something like that. Note that you linked #8597 which is this issue, not another one, I guess you meant #8622, right?

**Comment by saurabh500** [comment]
Yes. I meant #8622 

Thanks for the correction
