### ISSUE TITLE
Set KeySizeValue directly, rather than doing gymnastics

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#8601]
In the RSA and ECDSA types we do gymnastics to ensure that we can make get_KeySize return "the correct answer", even if it isn't "a legal answer" per LegalKeySizes.

In full .NET Framework this is easily solvable by setting the protected field instead of the property.  Since #8571 brought the fields back, we can simplify the code now (once the new packages are introduced... so, tomorrow-ish).

**Comment by krwq** [comment]
Not sure if intentionally or not intentionally but fix for this is also solving threading issues around LegalKeySizes. See #18746 for some more info

**Comment by bartonjs** [comment]
@krwq Well, this one is for asymmetric, not symmetric.  And the problem now isn't really "threading" so much as "a test tried to prove that we didn't corrupt state, and when it failed, state was corrupted"
