### ISSUE TITLE
System.ComponentModel.Tests.MemberDescriptorTests.CopiedMemberDescriptorEqualsItsSource test failure

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#8606]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug_prtest/1257/testReport/junit/System.ComponentModel.Tests/MemberDescriptorTests/CopiedMemberDescriptorEqualsItsSource/

> Stacktrace
> 
> MESSAGE:
Assert.True() Failure
Expected: True
Actual: False
+++++++++++++++++++
STACK TRACE:
at System.ComponentModel.Tests.MemberDescriptorTests.CopiedMemberDescriptorEqualsItsSource()

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_debug_tst_prtest/1186/consoleText
```
System.ComponentModel.Tests.MemberDescriptorTests.CopiedMemberDescriptorEqualsItsSource [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
   System.Composition.Convention.Tests  Total: 84, Errors: 0, Failed: 0, Skipped: 0, Time: 1.046s
            at System.ComponentModel.Tests.MemberDescriptorTests.CopiedMemberDescriptorEqualsItsSource()
```

**Comment by stephentoub** [comment]
Failed on Windows, too:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/1462/

**Comment by chlowell** [comment]
Strange, I don't see any obvious nondeterminism in the test. I've opened another PR to skip the test on all platforms while I investigate.

**Comment by stephentoub** [comment]
> Strange, I don't see any obvious nondeterminism in the test. I've opened another PR to skip the test on all platforms while I investigate.

I have a guess, though I've not looked deeply into it:
It looks like the equality is in part based on a collection that wraps a Hashtable, and that Hashtable is being indexed in some cases by strings.  With randomized string hashing, different executions could result in different enumeration orders of that Hashtable.  The test is comparing two member descriptors, one of which is created around an array of two attributes, and the other which is created around the first.  If in the process of creating the second, we end up going through that Hashtable and the ordering ends up being different than expected based on that randomization, the test could fail.

**Comment by chlowell** [comment]
Yes, `Hashtable` is the culprit. The ordering of a MemberDescriptor's `_attributes` member is unspecified because it comes from `Hashtable.Values`. `Equals` returns false when these members don't have identical elements at each index. I think this is mistaken because I don't find this ordering explicitly relevant anywhere else (though it is implicitly so when the `Hashtable` is populated).

What do you think of changing the comparison to search rather than enumerate? I expect the arrays are typically short.

**Comment by stephentoub** [comment]
Is the Hashtable just being used to filter out duplicates?  If so, instead of:
```C#
Hashtable hash = new Hashtable(list.Count);

foreach (Attribute attr in list)
{
    hash[attr.GetTypeId()] = attr;
}

Attribute[] newAttributes = new Attribute[hash.Values.Count];
hash.Values.CopyTo(newAttributes, 0);
```
how about something like (pseudo-code):
```C#
HashSet<object> hash = new HashSet<object>();

for (int i = 0; i < list.Count; )
{
    if (hash.TryAdd(list[i].GetTypeId()))
    {
        i++;
    }
    else
    {
        list.RemoveAt(i);
    }
}

Attribute[] newAttributes = list.ToArray();
```
