### ISSUE TITLE
System.Collections.Immutable should not use ` and + in its file names so source lookup works.

### ISSUE THREAD

**Issue by vancem** [dotnet/corefx#8608]
Currently in System.Collections.Immutable\src\System\Collections\Immutable there are a number of files that have names like

     ImmutableHashSet`1+MutationResult.cs

which have unusal characters like ` and +.     It turns out that these characters cause problem with the Nuget Symbol packages we generate in that they need to be escaped.   

See the package  bin\symbolpkg\System.Collections.*.symbols.nupkg

You will see that the special characters are escaped, in the nuget package archive.   This in turn confuses the nuget source server.   (basically source lookup for these files simply fail).  

While we could try to push nuget and all downstream components to support ` and + as normal characters, this seems like more trouble than it is worth.  

System.Collections.Immutable is the only assembly in CoreFX that does this.   Thus my recommendation is to simply avoid the problem and reaname the source files to avoid ` and + (very easy).    This will have no effect on the assembly, but it will make source code lookup work properly.

Thus low cost, useful value.

**Comment by AArnott** [comment]
Personally, I'd rather see the source server bugs fixed. These are valid filenames and whenever you have escaping bugs as evidently exist here, that can be compounded with security vulnerabilities.

**Comment by justinvp** [comment]
Note that @terrajobst adopted the same file naming convention in [`System.CommandLine`](https://github.com/dotnet/corefxlab/tree/master/src/System.CommandLine/System/CommandLine) over on corefxlab. It might be good to update `System.CommandLine` as well, preferably using the same convention.

**Comment by AArnott** [comment]
Good point, @justinvp. And to be fair, anyone with StyleCop.Analyzers installed might be following this rule.

**Comment by rrelyea** [comment]
we can address the issue, but I don't see it happening quickly. so you might want to do the workaround if this is important. happy to discuss over on https://github.com/NuGet/Home/issues/2811

**Comment by AArnott** [comment]
Thanks for considering, @rrelyea. We have indeed gone ahead with the workaround for now.
