### ISSUE TITLE
ZipArchive doesn't verify checksums when decompressing.

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#8610]
The Zip specification includes a crc32 for each individual file entry header.

When writing a ZipArchive, we calculate this crc32 and include it for each file.

When reading/decompressing a ZipArchive, we read this crc32 from the file header but don't ever validate it. We pass the data block to the underlying DeflateStream to decompress then return that deflatestream to the caller. The end result of this is that you can successfully unzip an archive that has potentially invalid data. 

Changing this behavior would introduce a large number of new errors and breaking changes. This issue is copied from an internal bug report.

**Comment by ianhays** [comment]
@stephentoub any thoughts on this?

**Comment by stephentoub** [comment]
Do all other zip implementations include a proper checksum in the generated zip files?  If not, seems like we'd be failing in valid cases.

What does Windows do when decompressing a file with an invalid checksum?

What does the zip utility do on Linux when decompressing a file with an invalid checksum?

Etc.

**Comment by ianhays** [comment]
>Do all other zip implementations include a proper checksum in the generated zip files? If not, seems like we'd be failing in valid cases.

Yes. It is required of the format:
``` 4.1.5 Data integrity MUST be provided for each file using CRC32. ```

> What does the Windows shell do when decompressing a file with an invalid checksum (e.g. when double-clicking a .zip to open it)?

Just opening the zip in explorer works fine. Extraction fails.

>>What does the zip utility do on Linux when decompressing a file with an invalid checksum?
>Etc.

Explorer when attempting to extract the file within the zip with the incorrect crc32:
![windowsexplorer error](https://cloud.githubusercontent.com/assets/2606879/16501777/f470e5f6-3ebf-11e6-99c6-17a419b4778f.png)

7zip:
![capture](https://cloud.githubusercontent.com/assets/2606879/16501805/1712f07c-3ec0-11e6-9d4f-1bbcc0ea6bb4.PNG)

Unix unzip:
```
ianha@ianhaU:~/test$ ls
MalformedData.zip
ianha@ianhaU:~/test$ unzip MalformedData.zip
Archive:  MalformedData.zip
  inflating: update.version4          bad CRC b0f0b09c  (should be 142320ca)
  inflating: update.version4.md5
ianha@ianhaU:~/test$ ls
MalformedData.zip  update.version4  update.version4.md5
```

**Comment by stephentoub** [comment]
So the Windows Explorer unzip prevents opening it, while the Unix unzip utility puts out a warning message but still expands it?

Seems like we shouldn't prevent such unzipping, as it would both be a breaking change and would prevent potentially valid usage, and ideally come up with a way to warn about the bad checksum while still not preventing the usage of it.  Unfortunately with the current APIs, there doesn't appear to be a way to give back such a warning.  Maybe we leave the current functionality as is, but add an additional property to ZipArchiveEntry to convey validity information, or add another overload of Open that takes a Boolean indicating whether to throw on an invalid checksum (with the default being false for compatibility), or something like that.

**Comment by ianhays** [comment]
>So the Windows Explorer unzip prevents opening it, while the Unix unzip utility puts out a warning message but still expands it?

That is correct. 

>Seems like we shouldn't prevent such unzipping, as it would both be a breaking change and would prevent potentially valid usage,

Agreed. We can't safely change the default behavior to throw on invalid checksum zips (because I'm sure it would cause a compat nightmare), and even if we could I'm not 100% convinced we would want to.

>add another overload of Open that takes a Boolean indicating whether to throw on an invalid checksum (with the default being false for compatibility), or something like that.

This is along the lines of what I had in mind, though I'd first want to make sure there's demand for it. It would essentially be a "verify zip" functionality and I don't recall seeing any requests for that anywhere. Maybe that's because it's assumed that verification is baked-in already, but it's difficult to say for sure.
