### ISSUE TITLE
System.Resources.ResourceWriterTests.ResourceReaderTests.ReadV1Resources failing after mscorlib rename.

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#8633]
This test started to fail when we renamed mscorlib.dll to System.Private.Corelib.dll.  The serialized resource payload does include the string "mscorlib".  Not clear if this is a test issue or product issue, but it's killing CI, so we are disabling it.

**Comment by ellismg** [comment]
You can't run this easily on windows yet, but after packages are updated tonight, you will be able to.  I'll add instructions then.

**Comment by gkhanna79** [comment]
I setup a repro on Windows as follows: 

1) Do a CoreFX build to produce the test folder that contains the ResourceReader tests
2) Copy the ResourceReader test folder to a temp location and overwrite CoreCLR binaries in it from the latest from CoreCLR master branch build.

Running the tests again (using modified runtests.cmd in the folder to simply invoke the test) I observe that they pass.

Is this (https://github.com/dotnet/corefx/pull/8620)  an issue on only CentOS or other platforms too?

CC @stephentoub

**Comment by ellismg** [comment]
Did you remove the ActiveIssue tag from the test?

**Comment by ellismg** [comment]
We saw it on other Linux platforms.  I suspect the only reason we didn't see it everywhere is because we were not pulling live bits for CoreCLR for some platforms.

**Comment by gkhanna79** [comment]
> Did you remove the ActiveIssue tag from the test?

The syncpoint I used for CoreFX didnt have ActiveIssue tag even though the CoreCLR had the change in it.

**Comment by gkhanna79** [comment]
@ellismg Can you point me to other CI failures for this?
