### ISSUE TITLE
IsKey is always null in SqlDataReader.GetColumnSchema()

### ISSUE THREAD

**Issue by roji** [dotnet/corefx#8641]
```c#
using (var cmd = new SqlCommand("CREATE TABLE data (id INTEGER PRIMARY KEY)", conn))
	cmd.ExecuteNonQuery();

using (var cmd = new SqlCommand("SELECT id FROM data", conn))
using (var reader = cmd.ExecuteReader(CommandBehavior.SchemaOnly))
{
	var columns = reader.GetColumnSchema();
	Console.WriteLine(columns[0].IsKey);
}

```

**Comment by saurabh500** [comment]
@roji, I can repro this on my end.
I also tested the SqlDataReader.GetSchemaTable() API on .Net framework the repro code. It turns out that IsKey column of the DataTable doesn't contain any information. Since the new API uses the same code that `SqlDataReader.GetSchemaTable()` uses, on desktop, we see the same behavior.

I am investigating more into why such a behavior exists.

**Comment by roji** [comment]
OK, great. FYI I have a full implementation of the new schema API that will probably be released tomorrow.

On a side note, the MSDN docs for the DataReader schema API seem to say that IsKey should be true even for columns with unique constraints - it's not just for primary keys. That would make it identical to IsUnique which exists as well. I wasn't sure what exactly what to implement so at least for now IsKey returns true only for primary keys. If you can clarify this that would be great too.

**Comment by saurabh500** [comment]
> FYI I have a full implementation of the new schema API that will probably be released tomorrow.
 
Is this for ngpsql ?

**Comment by roji** [comment]
@saurabh500 yes it's for Npgsql

**Comment by saurabh500** [comment]
After debugging further and going through the code, the TDS protocol sends a few column schema related items only when a query is executed in Browse Mode 
Refer: https://msdn.microsoft.com/en-us/library/dd358065.aspx
https://msdn.microsoft.com/en-us/library/aa936959(SQL.80).aspx

To get the IsKey attribute for a column the query can be executed as 
`new SqlCommand("SELECT id FROM data FOR BROWSE", connection)`

This feature is working as designed on .Net framework for `GetSchemaTable` API and for the new API in .Net Core.

**Comment by roji** [comment]
Apologies, you're right.

FYI, after digging into this it seems you can also get key information by specifying `CommandBehavior.KeyInfo` on your reader, obviating the need to modify the SQL query.
