### ISSUE TITLE
Require resgen.exe which can generate CoreCLR compliant code

### ISSUE THREAD

**Issue by hrushib** [dotnet/corefx#8648]
We use ResGen.exe to generate .resources file and C# class for given resx file. At present there is no ResGen.exe tool which generates CoreCLR compliant code and hence code generation can not be fully automated as part of the build at the moment. 

Please let us know plan/timelines around availability of the same.

**Comment by ramarag** [comment]
Already brought up in https://github.com/dotnet/coreclr/issues/2007 and has been moved to https://github.com/dotnet/cli/issues/819
