### ISSUE TITLE
Cannot use NETStandard.Library with a Wpa81 library

### ISSUE THREAD

**Issue by onovotny** [dotnet/corefx#8649]
Is NETStandard.Library supposed to be installable into a Wpa81 project? NET Standard 1.0 is compatible with Wpa81 but the following error is reported when it's attempted.

I would not expect many/any of the types outside of netstandard1.0 to be available, but referencing the package should succeed.

Could not install package 'Microsoft.NETCore.Runtime.Native 1.0.2-rc2-24027'. You are trying to install this package into a project that targets 'WindowsPhoneApp,Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author. 

/cc @ericstj

**Comment by grahamehorner** [comment]
I think we really should target netcoreapp1.0 which is the framework supported cross platforms and will run inside the clr & coreclr on all supported oses

**Comment by ericstj** [comment]
No repro in RC3.  Removed the runtime reference from NETStandard.Library.

@grahamehorner : not for this package.  It's specifically meant to represent all the different iterations of NETStandard and needs to be installable in all frameworks that support NETStandard.

**Comment by onovotny** [comment]
Thanks!
