### ISSUE TITLE
System.Security.Cryptography.X509Certificates RC2 is no longer compatible with UWP projects

### ISSUE THREAD

**Issue by martinsuchan** [dotnet/corefx#8651]
We're using in our Windows 10 UWP app the [System.Security.Cryptography.X509Certificates](https://www.nuget.org/packages/System.Security.Cryptography.X509Certificates/) .NET Core NuGet package for processing domain certificates.

Up until now we used the version **4.0.0-beta-23516** that compiled and ran just fine.
We tried to update the library to the **RC2** version today and the NuGet package failed to update with this error message: http://pastebin.com/zExtFk1T

Sample from the error message:
> System.Threading.Tasks 4.0.11-rc2-24027 provides a compile-time reference assembly for System.Threading.Tasks on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm.

Should these .NET Core packages work in UWP projects and this is just a temporary bug in the RC2 version or current NuGet package manager?
Is there any workaround we could use in our project, or we should just use the older version for now?

**Comment by bartonjs** [comment]
https://github.com/dotnet/core/blob/master/release-notes/1.0/Known-Issues-RC2.md

> .NET Core RC2 Packages and UWP Projects
>
> .NET Core 1.0 RC2 will not work in UWP projects. It is recommended that RC2 packages not be referenced.

For stable feeds, the RC1 build (beta-23516) is the only option.  But on the dotnet.myget.org dotnet-core feed the current "-rc3-" packages should have the UWP issue fixed.

(FYI: @ericstj @terrajobst)

**Comment by martinsuchan** [comment]
Thanks for the Known Issues link.
Wondering, if there is a way how to use EF Core RC2 together with the X509Certificates package in a single project since the X509Certificates RC2 is not compatible right now.

**Comment by bartonjs** [comment]
It's not that X509Certificates doesn't work on UWP, it's much lower than that.  The RC2 release note about UWP not working is all-inclusive.

Microsoft.EntityFrameworkCore.Relational 1.0.0-rc2-final depends on
System.Text.RegularExpressions 4.0.12-rc2-24027 depends on
System.Collections 4.0.11-rc2-24027 which is in your list of packages that complained there was no UWP-capable asset.

I don't think there's any way around it using only the nuget.org packages, unfortunately.

You might have success using the dotnet.myget.org dotnet-core feed and referencing a recent Microsoft.NETCore.UniversalWindowsPlatform 5.2.0-rc3-* build with the rc2-final EntityFramework packages; but that's entirely speculation.

@ericstj or @chcosta, any thoughts?

**Comment by bartonjs** [comment]
I've been able to successfully deploy to a phone using the RTM packages:

```
{
  "dependencies": {
    "Microsoft.ApplicationInsights": "1.0.0",
    "Microsoft.ApplicationInsights.PersistenceChannel": "1.0.0",
    "Microsoft.ApplicationInsights.WindowsApps": "1.0.0",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.0",
    "NETStandard.Library": "1.6.0",
    "System.Security.Cryptography.Algorithms": "4.2.0",
    "System.Security.Cryptography.Cng": "4.2.0",
    "System.Security.Cryptography.X509Certificates": "4.1.0"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```

Since everything is happy with things from the NuGet.org feed I'm going to call this closed.  if you are still having problems, please let us know.

**Comment by martinsuchan** [comment]
The build still fails for me but with a different problem now. Not sure, if this is a NuGet Package Manager or corefx issue, see:  

```
{
  "dependencies": {
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.1.0",
    "System.Security.Cryptography.X509Certificates": "4.1.0"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}

```

Detected package downgrade errors:
```
Detected package downgrade: Microsoft.Win32.Primitives from 4.0.1 to 4.0.0 
 Temp1 (>= 1.0.0) -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.1.0) -> Microsoft.NETCore (>= 5.0.0) -> System.Net.Primitives (>= 4.0.10) -> runtime.win.System.Net.Primitives (>= 4.0.11) -> Microsoft.Win32.Primitives (>= 4.0.1) 
 Temp1 (>= 1.0.0) -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.1.0) -> Microsoft.Win32.Primitives (>= 4.0.0)
```

Payload contains two or more files with the same destination path errors: 
```
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1692,5): error APPX1101: Payload contains two or more files with the same destination path 'Microsoft.Win32.Primitives.dll'. Source files: 
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1692,5): error APPX1101: C:\Users\martin.suchan\.nuget\packages\Microsoft.Win32.Primitives\4.0.0\lib\dotnet\Microsoft.Win32.Primitives.dll
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1692,5): error APPX1101: C:\Users\martin.suchan\.nuget\packages\runtime.win.Microsoft.Win32.Primitives\4.0.1\runtimes\win\lib\netstandard1.3\Microsoft.Win32.Primitives.dll
```
Detailed log: http://pastebin.com/fQyQ1Qcb

It looks like NuGet(?) tries to use both v4.0.0 and 4.0.1 of some dependencies.
This happens on VS2015 Update 3, UWP Tools 1.4.0 and NuGet 3.5.0.1484

**Comment by martinsuchan** [comment]
@bartonjs I've noticed you use **"Microsoft.NETCore.UniversalWindowsPlatform": "5.2.0"** and     **"NETStandard.Library": "1.6.0"** in the project.json.
The 5.2.0 version is not available in public stable NuGet feed and I never had to use "NETStandard.Library": "1.6.0" in my UWP projects, maybe that's the problem here?

**Comment by bartonjs** [comment]
@martinsuchan Sigh, I thought I'd cleared out my cache to be using only nuget.org packages; apparently not.

@ericstj Was Microsoft.NETCore.UniversalWindowsPlatform 5.2.0 supposed to have been published to nuget.org?  Or is it waiting for some other thing?

**Comment by onovotny** [comment]
It is on NuGet.org but was delisted due to a few issues. There are workarounds though:
https://github.com/dotnet/cli/issues/3189

**Comment by martinsuchan** [comment]
**Microsoft.NETCore.UniversalWindowsPlatform 5.2.1** NuGet was just released in public NuGet feed and **System.Security.Cryptography.X509Certificates 4.1.0** NuGet works fine with it, so I guess this issue is fixed now.
