### ISSUE TITLE
Seg fault in System.Security.Cryptography.X509Certificates.Tests.dll on CentOS in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#8657]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_release_tst_prtest/1252/consoleText

```
./RunTests.sh: line 208: 41177 Segmentation fault      ./corerun xunit.console.netcore.exe System.Security.Cryptography.X509Certificates.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests
Finished running tests. End time=18:46:58. Return value was 139
error: One or more tests failed while running tests from ''.  Exit code 139.
```

I don't know if this is the same issue @janvorli is already chasing down...

**Comment by bartonjs** [comment]
This may be related to #8501, waiting for Jan's investigation

**Comment by janvorli** [comment]
@bartonjs I have fixed #8501 and this issue still occurs. 
I have tried to run the test in a loop locally and it is reliably reproducible about every 80 test runs. In all cases, the Interop.Crypto.ExtractBignum is on the stack, the SafeBignumHandle is valid, but pointing to memory that doesn't seem right.
In fact, looking at the failure place, it looks as if the memory it points to was modified in the background by another thread.

This is the disass of the failing function:
```asm
(lldb) disass -F intel
   0x7ffc54cb4bb0 <BN_num_bits>:    mov    eax, dword ptr [rdi + 0x8]
   0x7ffc54cb4bb3 <BN_num_bits+3>:  test   eax, eax
   0x7ffc54cb4bb5 <BN_num_bits+5>:  jne    0x7ffc54cb4bc0            ; BN_num_bits + 16
   0x7ffc54cb4bb7 <BN_num_bits+7>:  ret
   0x7ffc54cb4bb8 <BN_num_bits+8>:  nop    dword ptr [rax + rax]
   0x7ffc54cb4bc0 <BN_num_bits+16>: push   rbx
   0x7ffc54cb4bc1 <BN_num_bits+17>: lea    ebx, [rax - 0x1]
   0x7ffc54cb4bc4 <BN_num_bits+20>: mov    rax, qword ptr [rdi]
   0x7ffc54cb4bc7 <BN_num_bits+23>: movsxd rdx, ebx
   0x7ffc54cb4bca <BN_num_bits+26>: shl    ebx, 0x6
-> 0x7ffc54cb4bcd <BN_num_bits+29>: mov    rdi, qword ptr [rax + 8*rdx]
   0x7ffc54cb4bd1 <BN_num_bits+33>: call   0x7ffc54cb4a80            ; BN_num_bits_word
   0x7ffc54cb4bd6 <BN_num_bits+38>: add    eax, ebx
   0x7ffc54cb4bd8 <BN_num_bits+40>: pop    rbx
   0x7ffc54cb4bd9 <BN_num_bits+41>: ret
```
Now the register values are:
```
RAX = 0x0000000000000000
RDX = 0x000000004c01710f
```
But, the RAX doesn't correspond to what I can see in memory at the address in RDI (where the RAX is loaded from few lines before by `mov    rax, qword ptr [rdi]`):
```
(lldb) x/gx $rdi
0x7ffc4c0155a0: 0x00007ffc4c016e70
```

**Comment by bartonjs** [comment]
Drat.  Well, thanks for looking, @janvorli.

I don't suppose you have any tips for getting the repro under a debugger?  Right now I'm just telling lldb "run" over and over again, haven't caught it yet.

**Comment by janvorli** [comment]
This is what I do to repro it (it also includes enabling stress log that can be used to trouble shoot GC related issues and disables concurrent and server GC to make investigations of possible GC issues easier).
First, `cd` to the test folder: 
`cd bin/tests/Unix.AnyCPU.Release/System.Security.Cryptography.X509Certificates.Tests/dnxcore50`
I would also recommend building coreclr for x64 checked and copying *.so, *.dll and corerun from the target folder of the build to the current folder. That makes it run slower, but debugging of native code if necessary is much easier. 
Before running the script below, please enable core dump using `ulimit -c unlimited` and make sure the crashdump contains code data of shared libraries using `echo 0x3f > /proc/self/coredump_filter`
Run the script below. The script keeps running until the test fails. Then you just open the core.
Also note that if you didn't explicitly configure Linux to put core dumps to a specific folder or use a specific format of a name, it would put the core right to the current folder and it will never overwrite existing one, so if you had old one, you need to delete it first.
```bash
for i in `seq 1 1000`; do echo $i;  COMPlus_StressLog=1 COMPlus_LogLevel=7 COMPlus_LogFacility=80103 COMPlus_StressLogSize=2000000 COMPlus_TotalStressLogSize=40000000 CORECLR_CONCURRENT_GC=0 CORECLR_SERVER_GC=0 ./corerun xunit.console.netcore.exe System.Security.Cryptography.X509Certificates.Tests.dll -xml testResults.xml -notrait Benchmark=true  -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests; rc=$?; if [[ $rc != 0 ]]; then break; fi; done
```

**Comment by bartonjs** [comment]
Thanks, Jan.  I forgot about just grabbing a coredump, and was only thinking about live capture.

**Comment by bartonjs** [comment]
Hmm, I've now had 2000 runs succeed without crashing on my machine.  I do have a single-core VM, so maybe there's some sort of parallel processing that isn't happening for me.

The second 1000 were with -maxthreads 4 on xunit to try to coerce some sort of parallel load into the equation.

**Comment by janvorli** [comment]
I was running it on my 16 processor native box with Ubuntu and with release version of the runtime, it reproduces in several hundreds of runs. So I guess the parallelism plays a role here.

**Comment by bartonjs** [comment]
Hmm, I've bumped the VM up to 4, and then 8 processors and still have had several thousand successful runs with 0 failures.

```
jbarton@jsb-centos:~$ uname -a
Linux jsb-centos 3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
jbarton@jsb-centos:~$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
```

@janvorli, if you still have a coredump and the associated collateral, can you pack it up and give me access so I can try from my end to see what's happening?  (I'm currently using a debug build off of 5cb2d1f8596ffeabe3c77a561b216dbd7c17f138, from the release/1.0.0 branch)

**Comment by bartonjs** [comment]
8-proc overnight 10,000 runs, no errors.

**Comment by janvorli** [comment]
I'll try to sync to the latest sources and re-test on Monday.

**Comment by janvorli** [comment]
I was able to repro it with the latest corefx in 300 iterations in debug. I'll share the dump with you.

**Comment by bartonjs** [comment]
I haven't been able to reproduce it, which has significantly hindered my ability to assess what a fix might be.  There's clearly some bad here, but I don't think we're going to make much progress on this for RTM without a fast-acting test case.

Moving to 1.1.

**Comment by adityamandaleeka** [comment]
@bartonjs This occurred today while we were trying to reproduce a different issue. I have a dump if it would be helpful to you.

```
0000000000098970 <BN_num_bits>:
   98970:       8b 47 08                mov    0x8(%rdi),%eax
   98973:       85 c0                   test   %eax,%eax
   98975:       75 09                   jne    98980 <BN_num_bits+0x10>
   98977:       c3                      retq
   98978:       0f 1f 84 00 00 00 00    nopl   0x0(%rax,%rax,1)
   9897f:       00
   98980:       53                      push   %rbx
   98981:       8d 58 ff                lea    -0x1(%rax),%ebx
   98984:       48 8b 07                mov    (%rdi),%rax
   98987:       48 63 d3                movslq %ebx,%rdx
   9898a:       c1 e3 06                shl    $0x6,%ebx
   9898d:       48 8b 3c d0             mov    (%rax,%rdx,8),%rdi     <-------------------
   98991:       e8 aa fe ff ff          callq  98840 <BN_num_bits_word>
   98996:       01 d8                   add    %ebx,%eax
   98998:       5b                      pop    %rbx
   98999:       c3                      retq
   9899a:       66 0f 1f 44 00 00       nopw   0x0(%rax,%rax,1)


 $1 = {si_signo = 0xb, si_errno = 0x0, si_code = 0x1, _sifields = {_pad = {0xa0df9a78, 0x2, 0x0, 0x0, 0x5e7d78, 0xffff8801, 0x817aa327, 0xffffffff, 
      0x0 <repeats 20 times>}, _kill = {si_pid = 0xa0df9a78, si_uid = 0x2}, _timer = {si_tid = 0xa0df9a78, si_overrun = 0x2, si_sigval = {sival_int = 0x0, 
        sival_ptr = 0x0}}, _rt = {si_pid = 0xa0df9a78, si_uid = 0x2, si_sigval = {sival_int = 0x0, sival_ptr = 0x0}}, _sigchld = {si_pid = 0xa0df9a78, si_uid = 0x2, 
      si_status = 0x0, si_utime = 0x5e7d7800000000, si_stime = 0x817aa327ffff8801}, _sigfault = {si_addr = 0x2a0df9a78}, _sigpoll = {si_band = 0x2a0df9a78, 
      si_fd = 0x0}}}
```

**Comment by bartonjs** [comment]
Since we don't have a plethora of crashes, and this issue hasn't been touched in months, I'm going to close this.  If we get new crashes we'll get a new bug opened, and hopefully we'll have some useful diagnostics now that the auto-callstack stuff is working.
