### ISSUE TITLE
Change dnxcore50 to netcoreapp10

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#8665]
Most existing projects assume dnxcore50 in various ways including the json and csproj.  These should all be changed to netcoreapp10 per @ericstj 

Note that the test scripts for unix (including runtest.sh) assume dnxcore50 being the last folder in the test's bin directory.

An attempt was made to use netcoreapp10 for the folder test name for System.Security.Cryptography.OpenSll and .Cng but resulted in various hacks in its respective .csproj.

**Comment by mellinoe** [comment]
We no longer use dnxcore50 except in places like legacy documentation, etc.
