### ISSUE TITLE
System.Reflection.TargetException.ctor() has different message between Core and Framework

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/corefx#8668]
While refactoring tests for System.Reflection.TargetException, I found that the [.NET documentation](https://msdn.microsoft.com/en-us/library/system.reflection.targetexception(v=vs.110).aspx) states that the default constructor: 

> Initializes a new instance of the TargetException class with an empty message and the root cause of the exception.

However I'm getting different messages in the exception on the [.NET framework](http://referencesource.microsoft.com/#mscorlib/system/reflection/targetexception.cs,8aea524b98ba77d4) where I get:

> Error in the application.

and .NET Core, where I get:

> Exception of type 'System.Reflection.TargetException' was thrown.

What should be the behavior I should test for?

**Comment by mellinoe** [comment]
You generally shouldn't need to test for any particular exception message unless there's a good reason to. It is too fragile and also doesn't play well with things like localization, etc. In .NET Native, we don't even preserve exception messages, anyways, so the tests would fail there if we required the strings to match. For our tests, we will usually just validate that exceptions thrown are of the correct type/subtype.

**Comment by bartonjs** [comment]
@mellinoe In this case, he was boosting the tests to match what we said on MSDN (specifically, the "empty message" part).  The mismatch is, I think, because we got rid of ApplicationException (where the Full Framework string comes from)... so it's probably something on our "eh, don't care" list; but filing the issue was good practice :)

**Comment by AtsushiKan** [comment]
The documentation is inaccurate for either framework but the existing .NETCore version is a lot more useful (and as stated above, the text of the exception message isn't part of the contract.)

Doesn't seem to need any further action.
