### ISSUE TITLE
Enabling ARM based builds in corefx CI

### ISSUE THREAD

**Issue by prajwal-aithal** [dotnet/corefx#8675]
The current CI code in corefx does not build (cross/native) for ARM architecture. Some commits could break the native part of corefx for Linux ARM (as can be seen here #8557 ). I want to add the code to cross build the native part of corefx for Ubuntu-ARM to prevent such build breaks. I would like to do the same in 2 steps.

1. Add code to enable cross build for Ubuntu ARM to the CI (supporting manual trigger of the CI check).
2. Once this is confirmed to work correctly, change the code to make this check automatically triggered for every PR.

I saw the CI script, and have a question regarding where in the script could this change be best accommodated.
1. Adding code to build native corefx (no testing) under the outerloop testing part of the script (lines 319 to 375).
2. Adding code to build native corefx (again, no testing) under the innerloop part of the script (lines 467 to 590).

What is the best choice for this change?

@mmitche @Priya91

**Comment by prajwal-aithal** [comment]
@leemgs

**Comment by prajwal-aithal** [comment]
@jashook @Priya91 ARM Emulator CI checks have now been enabled in the coreclr project (PRs dotnet/coreclr#5933, dotnet/coreclr#5961, dotnet/coreclr#5983). 

I believe we can implement the ARM Emulator CI checks for the native part of corefx in the same manner as implemented in coreclr. This would help us prevent build regressions in the native part of corefx.

There has been a lot of learning involved in this task and I believe that the effort in implementing the same in corefx would be a lot lesser than what it took to do the same in coreclr. The cross build script would roughly be the same, but I still need some insight into the organization of the groovy script in corefx.

Specifically, could you please let me know what the outerloop and innerloop sections of the groovy script correspond to and where I can add the code for the ARM Emulator CI check job?

**Comment by mkborg** [comment]
@prajwal-aithal Let me propose a patch for CoreFX arm-softfp cross build with emulator's rootfs: [emulator-corefx-cross-build.patch.txt](https://github.com/dotnet/corefx/files/331427/emulator-corefx-cross-build.patch.txt) (it is similar to patch for CoreCLR: [emulator-coreclr-cross-build.patch.txt](https://github.com/dotnet/corefx/files/331429/emulator-coreclr-cross-build.patch.txt))

**Comment by Priya91** [comment]
> Specifically, could you please let me know what the outerloop and innerloop sections of the groovy script correspond to and where I can add the code for the ARM Emulator CI check job?

The outerloop and innerloop are differing only in a build switch /p:OuterLoop=true, in outerloop more tests are run, and it is a nightly build, run daily once. Innerloop runs have a subset of post-checkin tests that are required to be run for every checkin. Outerloop runs are run elevated, innerloop is not. 

The native build of corefx is done as a part of the build process itself, we don't have a separate section in netci.groovy that does this. Check out the [build.sh](https://github.com/dotnet/corefx/blob/master/build.sh) and [src\Native\Windows\build-native.cmd](https://github.com/dotnet/corefx/blob/master/src/Native/Windows/build-native.cmd)

**Comment by prajwal-aithal** [comment]
This has been implemented by PRs #9718 , #9906 , and #9909 . This can be closed now.
