### ISSUE TITLE
Custom Type Converters in Core

### ISSUE THREAD

**Issue by AbhitejJohn** [dotnet/corefx#8679]
Custom Type converters as detailed here: https://msdn.microsoft.com/en-us/library/ayybcxe5.aspx are not working in core. The ConvertFrom() and ConvertTo() methods never get hit but they do work when targetting full CLR. This is how my project.json looks like:

`"dependencies": {
    "Newtonsoft.Json": "8.0.3",
    "System.ComponentModel.TypeConverter": "4.0.1-rc2-24027"
  },

  "runtimes": {
    "win7-x64": { },
    "win7-x86": { }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50",
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0-rc2-3002702"
        },
        "System.Dynamic.Runtime": "4.0.11-rc2-24027",
        "System.Runtime.Serialization.Primitives": "4.1.1-rc2-24027"
      }
    }
  }`

**Comment by ianhays** [comment]
Could you post a code snippet or example showing what exactly you're doing?

Also, there have been a pretty big number of ports/enchacements to ComponentModel since rc2. It's possible that what you're trying was missing in RC2 but is now included in the most recent builds.

**Comment by AbhitejJohn** [comment]
I'm trying this on the latest rc2 bits pulled from here: https://myget.org/gallery/aspnetrc2. 
Below is a simple code snippet. The CanConvertFrom/ConvertFrom/ConvertTo APIs do not get hit while serializing/deserializing when targeting core. These work on net461 though. 

`public class Program
    {
        public static void Main(string[] args)
        {
            var properties = new Dictionary<string, TestProperty>();
            properties.Add("FullyQualifiedName", new TestProperty("AssemblyFullName", typeof(string), typeof(Program).GetTypeInfo().Assembly.FullName));
            var tpl = new TestPropertyList(properties);
            var serializedPayload = JsonConvert.SerializeObject(tpl);
        }
    }
    
    public class TestPropertyList
    {
        public Dictionary<string, TestProperty> properties;

        public TestPropertyList(Dictionary<string,TestProperty> p)
        {
            this.properties = p;
        }
    }

    [TypeConverter(typeof(TestPropertyConverter))]
    public class TestProperty
    {
        public string Name;
        public Type ValueType;
        public object Value;

        public TestProperty(string name, Type type, object fullName)
        {
            this.Name = name;
            this.ValueType = type;
            this.Value = fullName;
        }
    }

    public class TestPropertyConverter : TypeConverter
    {
        public override bool CanConvertFrom(ITypeDescriptorContext context, Type sourceType)
        {
            return base.CanConvertFrom(context, sourceType);
        }

        public override object ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value)
        {
            return base.ConvertFrom(context, culture, value);
        }

        public override object ConvertTo(ITypeDescriptorContext context, CultureInfo culture, object value, Type destinationType)
        {
            return base.ConvertTo(context, culture, value, destinationType);
        }
    }`

**Comment by ianhays** [comment]
That API was pretty much a stub in RC2. There have been a pretty big number of ports/enhancements since then. Take a look at [TypeConverter in RC2](https://github.com/dotnet/corefx/blob/release/1.0.0-rc2/src/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs) compared to [TypeConverter now](https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs).

The latest dotnet core packages are on https://www.myget.org/F/dotnet-core/.

**Comment by ianhays** [comment]
It's also possible there's a difference in the JSON.net core version vs the full framework version that modifies this behavior.

I just took your example app and ran it on the RC2 bits with some added validation, namely `TypeDescriptor.GetConverter(typeof(TestProperty));` which returns `TestPropertyConverter` as expected. I don't know what JSON.NET is doing on its side, but the TypeConverter **does** work as expected at least in that regard. Calling ConvertTo/ConvertFrom/CanConvertFrom on the TypeConverter returned by GetConveter correctly calls the overrides in TestPropertyConverter.
