### ISSUE TITLE
Improve crypto error handling for ECDSA

### ISSUE THREAD

**Issue by steveharter** [dotnet/corefx#8684]
Misc low-priority issues found post code review (elliptic curve support):
- Clear native errors in cases where validating oid, and other failure cases where a native crypto exception will not occur (ERR_clear_error) to avoid false exception information
- Add [DebuggerDisplay] ECCurve to return the curve oid so we get useful debugger information instead of the default type name semantics (via ToString)
- Remove any unused resource strings (one known: Cryptography_UnsupportedEcKeyAlgorithm)

**Comment by danmosemsft** [comment]
Dead strings should be removed now

**Comment by ViktorHofer** [comment]
@steveharter: As Dan said, dead resources are already gone. I added the DebuggerDisplay for oid. I can't find any native errors while validating oid, maybe already fixed? https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/ECCurve.cs#L191

This PR would be a one liner ;)

**Comment by steveharter** [comment]
The native errors would have to be emulated. However, this is low-pri so closing. Thanks

**Comment by karelz** [comment]
We should not close bugs if they are low-pri. If it is something valuable for the code base, we should move it to Future. Thanks @ViktorHofer for fixing it!
