### ISSUE TITLE
Enhance RSA.Create

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#8688]
During the API review of #7688 it was decided that to enable better cross-plat authoring we should have Create() methods on the following crypto base classes:
ECDsa: Create(), Create(ECCurve), Create(ECParameters)
_RSA: Create(), Create(int), Create(RSAParameters)_
ECDiffieHellman: Create(), Create(ECCurve), Create(ECParameters)
DSA: Create(), Create(int), Create(DSAParameters)

Hopefully all of these make it for net463, and we should have them in .NET Core as well.

This specific issue tracks adding the int and RSAParameters create overloads for RSA, and is an offshoot of #8487.

**Comment by bartonjs** [comment]
(Marked as api-approved since this is an action item which came out of the EC import/export design discussion)

**Comment by danmosemsft** [comment]
Removing NS2.0 label as this isn't in desktop yet

**Comment by karelz** [comment]
Should be fairly simple to implement (10 mins + adding new API) - up for grabs.

**Comment by leastprivilege** [comment]
So the x-plat problem still exists in netstandard 2.0

RSA.Create will create a 1k key on .NET Framework 4.6.1 and a 2k key on .NET Core 2.

Is there a workaround for that that doesn't involve multi-targeting our library (because of 1 API)? Am I missing something?

**Comment by bartonjs** [comment]
@leastprivilege 

```c#
private static RSA CreateRSA(int keySize)
{
    RSA rsa = RSA.Create();

    if (rsa is RSACryptoServiceProvider)
    {
        rsa.Dispose();
        return new RSACng(keySize);
    }

    rsa.KeySize = keySize;
    return rsa;
}
```

Or

```C#
static YourClass()
{
    using (RSA rsa = RSA.Create())
    {
        if (rsa is RSACryptoServiceProvider)
        {
            CryptoConfig.AddAlgorithm(typeof(RSACng), "System.Security.Cryptography.RSA");
        }
    }
}
```

Though the latter is harmful to code that does blind casting.

**Comment by leastprivilege** [comment]
Thanks - but where do I find `RSACng` ?

According to this 
https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsacng?view=netstandard-2.0

It is not supported by netstandard2 libs.

**Comment by leastprivilege** [comment]
nevermind - I think I found it.

**Comment by leastprivilege** [comment]
Thanks! It is working!

**Comment by rosdi** [comment]
For those like me, `RSACng` is available as nuget package. There seems some issue in Visual Studio not able to install this package properly in my project. I had to remove the package, delete bin and obj folder, rebuild and it finally works.
