### ISSUE TITLE
Async methods for Concurrent Queue and Stack

### ISSUE THREAD

**Issue by SamuelEnglard** [dotnet/corefx#8694]
The concurrent Queue and Stack could use *Async methods, something like

```csharp
Task<T> ConcurrentQueue<T>.DequeueAsync();
Task<T> ConcurrentQueue<T>.PeekAsync();
Task ConcurrentQueue<T>.EnqueueAsync(T item);
```

For `DequeueAsync()` and `PeekAsync()` the advantage of having async methods is if you "must" have a result you don't block while waiting. For `Enqueue(T item)` the advantage is that you don't have to be blocked till the item is successfully enqueued.

**Comment by stephentoub** [comment]
ConcurrentQueue/Stack don't do any blocking not in general any signaling between producers and consumers. If you need support like this, you can either layer it on top with SemaphoreSlim or use a collection that does build in such signaling, e.g. BufferBlock in the dataflow library.

**Comment by SamuelEnglard** [comment]
Admittedly I didn't know about BufferBlock and the like, which do solve the exact use case that made me think of these. While I still think the first two would be useful since many developers put `TryDequeue` in a loop I'll close the issue since they should use the DataFlow Library

**Comment by svick** [comment]
Some other options apart from Dataflow are:

* [`AsyncCollection`](https://github.com/StephenCleary/AsyncEx/wiki/AsyncCollection) from Nito.AsyncEx. It's very similar to `BlockingCollection`, except that it's async.
* [Channels](https://github.com/dotnet/corefxlab/blob/master/src/System.Threading.Tasks.Channels/README.md) from corefxlab.
