### ISSUE TITLE
Potential issue with System.Runtime.CompilerServices.Unsafe.

### ISSUE THREAD

**Issue by MarkPflug** [dotnet/corefx#8699]
I was reviewing the code in the Unsafe class that was added recently, and I think the methods on this class should have a struct constraint added to the type parameters. Some of the IL opcodes that these methods use are documented to only operate on value types (ldobj and stobj, for example). I think if they are called with non-struct types it might result in an exception being thrown by the JIT compiler.

https://github.com/dotnet/corefx/blob/master/src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.il

**Comment by mikedn** [comment]
> Some of the IL opcodes that these methods use are documented to only operate on value types (ldobj and stobj, for example).

`ldobj` and `stobj` do not have such a restriction.

**Comment by MarkPflug** [comment]
It doesn't?
https://msdn.microsoft.com/en-us/library/system.reflection.emit.opcodes.ldobj(v=vs.110).aspx

> The ldobj instruction is used to pass a value type as a parameter.

**Comment by mikedn** [comment]
The MSDN documentation is wrong, ECMA-335 doesn't say "value type", it only says "value". 

Anyway, ldobj/stobj must work with reference types, otherwise it wouldn't be possible to write a method like the following:

```C#
T get<T>(ref T x) => x;
```

`ldind.ref` cannot be used because `T` may be a value type. So `ldobj !T` is used instead because it works with both value and reference types.

**Comment by MarkPflug** [comment]
Okay, you are correct. The reference itself, not the referenced object, is what will be operated on.

**Comment by mattwarren** [comment]
> The MSDN documentation is wrong, ECMA-335 doesn't say "value type", it only says "value".

I got caught out by this as well!

Those MSDN docs are a bit misleading, it's really confusing that they say "value type"
