### ISSUE TITLE
SqlClient: async command to fetch sequence values hangs connection on Linux

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/corefx#8701]
Executing a DbCommand asynchronously with SqlClient can cause the connection to hang on Linux. 
### Setup

Minimal repro here: [Archive.zip](https://github.com/dotnet/corefx/files/402773/Archive.zip)

What this test app does:
Create 50 tasks.
Each task tries to select a value from a sequence using ExecuteScalarAsync.

The important part of this repro:

``` c#
using (var conn = new SqlConnection(connStr))
{
    var command = conn.CreateCommand();
    command.CommandText = "SELECT NEXT VALUE FOR TestSequence";
    conn.Open();
    await command.ExecuteScalarAsync();
}       
```
### Expected behavior

Can retrieve 50 values in parallel for all platforms. It works on Windows 10-x64.
### Actual behavior

On Linux, command execution hangs on executescalarasync. Subsequent attempts to open a connection will overwhelm the server until to refuses more connections. A few of the first calls to ExecuteScalarAsync may pass, but with in a few seconds, this simple app crashes as subsequent connections are rejected:

```
System.Data.SqlClient.SqlException : A network-related or instance-specific error occurred while
 establishing a connection to SQL Server. The server was not found or was not accessible. Verify
 that the instance name is correct and that SQL Server is configured to allow remote connections. 
(provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
```
### Setup

SQL 2014 and SQL 2016
Ubuntu 14.04-x64
System.Data.SqlClient/4.1.0-rc2-24027
Exact same app works on Windows against the exact same database using an identical connection string: `Server=mymachine.com;User ID=user;Password=password;Connect Timeout=30`

**Comment by natemcmaster** [comment]
cc @corivera @saurabh500

**Comment by YoungGah** [comment]
@natemcmaster, so far our investigation revealed that we have decreased scalability going through connection pool on Linux. We will continue to investigate, but meantime, I recommend you to use OpenAsync rather than trying to do sync open on 50 tasks. OpenAsync will give the best scalability.

**Comment by saurabh500** [comment]
This involves ConnectionPool along with Managed SNI. 
With Managed SNI running on Windows, I can get this issue to reproduce. 
I agree with @YoungGah 's recommendation of using OpenAsync while working with about 50 tasks. That would provide better scalability

I have had successful executions with about 22 parallel tasks.

**Comment by saurabh500** [comment]
@natemcmaster Is this still an issue? 
I see this working quite well on Ubuntu. I am using .Net Core 1.1 tooling 
I have tried the execution with SqlClient 4.1.0 and 4.3.0.
The execution is very quick.

**Comment by natemcmaster** [comment]
cc @ajcvickers have you seen this since RC2? This might have been mitigated by a Entity Framework Core change: https://github.com/aspnet/EntityFramework/pull/6023

**Comment by saurabh500** [comment]
The repro in archive.zip has nothing to do with  EF

**Comment by natemcmaster** [comment]
Right. We discovered the issue from EF Core testing. The EF team would know better if this continues to be an issue, but I haven't worked on EF for 6 months.

**Comment by saurabh500** [comment]
Thanks @natemcmaster 

I am closing this issue based on the results that we have today.
