### ISSUE TITLE
System.Data.SqlClient: System.OverflowException during Prelogin Handshake

### ISSUE THREAD

**Issue by aleksbol** [dotnet/corefx#8703]
During the Sql Client prelogin handshake, it appears the Sql Client does not respect the stream nature of TCP and will fail with _System.OverflowException: Arithmetic operation resulted in an overflow_ if the underlying socket read call returns less bytes than expected. 

Sample app that repro's the issue:

``` csharp
class Program
{
    static void Main(string[] args)
    {
        string sqlHost = "[YourDBHost]";
        Task.Factory.StartNew(() => { SetupProxy(sqlHost); });

        // Using sleeps to avoid any races...
        Thread.Sleep(1000);

        using (SqlConnection conn = new SqlConnection("Server=localhost,9999;Database=[YourDBName];User ID=sa;Password=[password];Encrypt=False"))
        {
            conn.Open();
            Console.WriteLine("Open succeeds");
        }
    }

    static void SetupProxy(string actualHost)
    {
        // Create listener, wait for client
        TcpListener listener = new TcpListener(9999);

        listener.Start();
        var client = listener.AcceptTcpClient();

        var sqlClient = new TcpClient(actualHost, 1433);

        // Setup reading and writing proxy
        Task.Factory.StartNew(() => { ForwardToSql(client, sqlClient); });
        Task.Factory.StartNew(() => { ForwardToClient(client, sqlClient); });
    }

    static void ForwardToSql(TcpClient ourClient, TcpClient sqlClient)
    {
        while(true)
        {
            byte[] buffer = new byte[1024];
            int bytesRead = ourClient.GetStream().Read(buffer, 0, 1024);

            sqlClient.GetStream().Write(buffer, 0, bytesRead);
        }
    }

    static void ForwardToClient(TcpClient ourClient, TcpClient sqlClient)
    {
        byte[] buffer;
        int bytesRead;
        // Read one byte first to show the issue.
        // Comment this out to see things work as expected.

        buffer = new byte[1];
        bytesRead = sqlClient.GetStream().Read(buffer, 0, 1);
        if(bytesRead != 1)
        {
            Console.WriteLine("Failed reading a single byte...");
            return;
        }

        ourClient.GetStream().Write(buffer, 0, bytesRead);
        
        // Now proxy normally. We will sleep for 500ms to make sure that nagling doesn't cause further data to be bundled with this.
        Thread.Sleep(500);
        while (true)
        {
            buffer = new byte[1024];
            bytesRead = sqlClient.GetStream().Read(buffer, 0, 1024);

            ourClient.GetStream().Write(buffer, 0, bytesRead);
        }
    }
}
```

**Comment by saurabh500** [comment]
@aleksbol Is the above repro a minimum repro of the code from SqlClient ? 

What is the usecase? What server are you using?

**Comment by aleksbol** [comment]
@saurabh500 I'm not sure what you mean by a minimum repro. In general, this issue happens if any number of bytes less than what SQL expects, is returned by the underlying socket read call - not just the 1 byte scenario I made in the repro.

The problem above was reported by a number of users of Azure App Service, when using the Hybrid Connectivity feature to access on-premise SQL databases. More info here:

https://blogs.msdn.microsoft.com/waws/2016/05/17/hybrid-connection-error-with-sql-server-system-overflowexception-arithmetic-operation-resulted-in-an-overflow/

The Hybrid Connectivity feature makes a proxy between an Azure App Service App and an endpoint that may not be internet accessible. Due to a recent change in .NET this proxy has started to split the first packet into two, which consistently causes the above problem.

**Comment by saurabh500** [comment]
@aleksbol Is this issue with the .Net Framework for Desktop or is it for .Net Core? 

I see that this issue is reproducible on .Net Full Framework. 
The blog points towards a work around for the full framework and hints at modifying registry keys for SCHANNEL . Also a fix is expected in the Hybrid connection manager.

cc @davidsh @cipop Are you aware of the issue mentioned in the listed blog

**Comment by aleksbol** [comment]
This is a .Net full framework issue, I have filed an issue on the appropriate teams. Closing this for now, though the issue may be relevant to .NET core still.

**Comment by CIPop** [comment]
/cc @himadrisarkar 

@saurabh500 @aleksbol This is by design, part of https://support.microsoft.com/en-us/kb/3155464. It is relevant to all .Net releases including CoreFX.
