### ISSUE TITLE
dotnet restore high cpu usage

### ISSUE THREAD

**Issue by xyting** [dotnet/corefx#8711]
<img width="313" alt="2016-05-20 14 43 09" src="https://cloud.githubusercontent.com/assets/14950276/15419548/44396168-1e99-11e6-97c3-1bfda94c6a8b.png">

**Comment by svick** [comment]
Why exactly is that a problem? I can understand complaining about `dotnet restore` taking too long, but that's not what you're saying. Why does it matter that it uses too much CPU?

**Comment by joshfree** [comment]
This issue has been moved to the CLI repo https://github.com/dotnet/cli/issues/3162
