### ISSUE TITLE
HttpMessageContent - Is this a part of .NET Core?

### ISSUE THREAD

**Issue by BadriL** [dotnet/corefx#8713]
Can I use `HttpMessageContent` with .NET Core. I can't seem to find this class here or anywhere else. Any pointer will be appreciated.

**Comment by davidsh** [comment]
`HttpMessageContent` is not part of the main .NET Framework nor part of .NET Core.  It is part of the ASP.NET WebAPI extensions for Http.
https://msdn.microsoft.com/en-us/library/system.net.http.httpmessagecontent(v=vs.118).aspx

It is currently part of the System.Net.Formatting.dll.

@danroth27 What are the plans for `HttpMessageContent` ?

**Comment by BadriL** [comment]
Looks like there is a DNX package available `Microsoft.AspNet.WebApi.Client` and it seems to be working okay in a .NET Core console app (dnxcore50, to be exact, since we are still on RC1-Update). Is it okay to use this package going forward with RC2, RTM, etc?

**Comment by danroth27** [comment]
@Eilon Yes, we plan to continue to support using this package on .NET Core.

**Comment by davidsh** [comment]
Closing this issue since the question was answered and HttpMessageContent is not part of CoreFx but part of ASP.NET. Please follow up directly in the ASP.NET repo for future inquiries about HttpMessageContent.
