### ISSUE TITLE
MailMessage and SmtpClient libraries in CoreFx

### ISSUE THREAD

**Issue by kjanshair** [dotnet/corefx#8714]
Greetings,

I'm using RC1 in production for my web application and it uses .NET Mail Service assemblies for sending mails using MailMessage and SmtpClient. These are only available on .NET Framework, when I'll get these libraries as a part of CoreFx so that I can port my application on .NET Core and avoid using 3rd party libraries.

Regards,

**Comment by Maxwe11** [comment]
#1006

**Comment by davidsh** [comment]
We'll use #1006 to track this.
