### ISSUE TITLE
HttpRequestHeaders Date header

### ISSUE THREAD

**Issue by adontz** [dotnet/corefx#8715]
Hello,

Proposal:

I think Date header in HttpRequestHeaders  (and maybe other headers of DateTimeOffset type) must be of new DateTimeHeaderValue type which will be convertible to/from DateTimeOffset and string.

Rationale:

Many token based authentication schemes require client to send some hash/HMAC of request data. Value of Date header is almost always part of data to be hashed/HMACed. While values of other types of headers (like StringWithQualityHeaderValue) can be get by simply calling ToString() this is not the case for Date. So you'll have to read documentation on how dates are represented in HTTP headers and convert value exactly the same way. Or probably dig into source code of CoreFX to see how it's done. Abstraction leaked the bad way.

As a side note, maybe it's good idea to provide type conversion operators for header value types, which will call ToString/Parse internally and ease one's life.

**Comment by karelz** [comment]
Next step: We need formal API proposal (exact API shape - see https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md)

Please assess impact on compatibility of existing code and existing binaries.

**Comment by karelz** [comment]
Triage: 3 years old, 1 upvote + we think it already exists. Closing.

**Comment by adontz** [comment]
I look at source code and see

    public DateTimeOffset? Date
        {
            get { return GeneralHeaders.Date; }
            set { GeneralHeaders.Date = value; }
        }

So situation did not change a bit and "we think it already exists" comment confuses me.

**Comment by stephentoub** [comment]
> So situation did not change a bit and "we think it already exists" comment confuses me.

There is already a `Date` property, as you highlight.  Changing its type would be a breaking change.

**Comment by karelz** [comment]
Yeah, sorry - I misunderstood what was said in the triage meeting and made wrong comment. The API already exists and returns DateTimeOffset, we believe it is sufficient / not worth to do anything else here.
