### ISSUE TITLE
Help me BREAK this app!

### ISSUE THREAD

**Issue by GuardRex** [dotnet/corefx#8717]
@ericstj ... you might enjoy this one for a change.

Coming off of an installer problem in https://github.com/aspnet/IISIntegration/issues/179, we realized that the [Publishing to IIS documentation](https://docs.asp.net/en/latest/publishing/iis.html) requires some information added back with regard to the VC++ redist requirement on 2008R2 machines.

Normally, the hosting bundle will install the redist, but it can go MIA on an app if any of the following happens:
  1. The installer fails to install it,
  2. Someone uninstalls it after the hosting bundle is installed, or
  3. Someone plans to only run self-contained apps on their 2008R2 server, thus they never run the hosting bundle installer in the first place (in the future when the ANCM is available separately).

It's simple enough in the doc to mention that the 2008R2 server requires the redist and that it is normally installed by the hosting bundle installer. What I need to do is repro what happens when it isn't there for the troubleshooting section.

What's a good way to break an app if the vc++ redist is missing? Does anyone have a code snippet that I can place in a controller so I can simulate an app needing vc++ redist? ... perhaps looking for the compiler (cl.exe) or requiring some class/method where the redist would be needed?

cc/ @Rick-Anderson @shirhatti

**Comment by ericstj** [comment]
/cc @gkhanna79 
Check for VCRuntime.dll and ucrtbase.dll in the system32 directory?  CL.exe isn't part of the redist.  FWIW folks are trying to eliminate the dependency on the VCRedist and just require the UCRT which is pushed out as an OS update to those old 2008R2 machines.

**Comment by gkhanna79** [comment]
For RTM, we dont require VCRuntime (since we statically link that piece). The only dependency is on uCRT and there is a Windows update required to push down the same (see https://www.microsoft.com/en-us/download/details.aspx?id=48234 and https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/).

**Comment by GuardRex** [comment]
I'm looking for something that might be lazily loaded at runtime ... like something that would compile but :boom: at runtime ... something that I could place in a controller that would break when a request is made to the app.

If the whole concept of reverse-engineering an exception for an MIA VC++ install is too problematic, then perhaps the doc should just mention that 2008R2 machines should have it installed and we should leave it out of the troubleshooting section. I get the impression this scenario is going to be rare anyway, as it hasn't shown up in the issues all that much and 2008R2 is kind'a on its way out ... Welcome to 2016! :smile:

**Comment by gkhanna79** [comment]
@blackdwarf should document the dependency

**Comment by blackdwarf** [comment]
@GuardRex is this about ASP.NET tools?

**Comment by GuardRex** [comment]
Not really ... just in the general sense. Can apps break if the app needs VC++ redist at runtime and it's not there? 

If the scenario is highly unlikely, then it's probably not worth mentioning in the Publishing to IIS doc. My goal there was to provide a somewhat comprehensive coverage of common faults, but this prob might be so rare or limited to devs who play with custom tools that it might not be worth mentioning.

**Comment by blackdwarf** [comment]
@GuardRex ah, so you landed in this position by *using* publish to IIS tools?

**Comment by GuardRex** [comment]
It seems that back in DNX days (ancient history :smile: ) it was absolutely required on 2008R2. @Rick-Anderson may recall more about it than I do.

Currently, I'm not sure if anything is required from VC++ redist on 2008R2 that a dev might be able to lazily ref in their code that would cause it to choke on deployment. Generally speaking, yes, I'm asking regarding published output that the dev moves to the server and their code fails because the redist isn't present.

**Comment by GuardRex** [comment]
Looks like there is no obvious way to repro the scenario. By the looks of the low issue count dealing with a missing VC++ redist, I'll let this one go and just reference it over on the next Publishing to IIS discussion.
