### ISSUE TITLE
NuGet packages for releases should have more memorable versions

### ISSUE THREAD

**Issue by svick** [dotnet/corefx#8718]
Currently, the package versions for the RC2 release look something like this:

| Package | Version |
| --- | --- |
| Microsoft.NETCore.App | 1.0.0-rc2-3002702 |
| NETStandard.Library | 1.5.0-rc2-24027 |
| System.Collections | 4.0.11-rc2-24027 |
| Microsoft.AspNetCore.Server.Kestrel | 1.0.0-rc2-final |

There seem to be three groups:
- Microsoft.NETCore.App: rc2-3002702
- CoreFX: rc2-24027
- ASP.NET Core: rc2-final

I like the ASP.NET Core approach of marking the release version by "-final", while CoreFX and NETCore.App just use a seemingly meaningless number.

Would it be possible to use the "-final" approach for future releases of CoreFX, NETCore.App and any other .Net Core packages? I think this is especially important since hand-editing project.json seems to be a relatively common practice.

**Comment by mellinoe** [comment]
At RTM, these packages won't have any pre-release identifier all (by definition :smile:). I agree that it's a bit confusing now to match the different versions right now. This is mostly a consequence of different layers of the stack being built in different places with different naming schemes. The corefx versions ("24027") are based on the build date, the cli versions ("3002702") are based on the number of commits in their git repository.

**Comment by svick** [comment]
@mellinoe Right, 1.0 RTM won't have this problem, but 1.0 RC3 or 2.0 beta1 or whatever comes next will.

**Comment by SamuelEnglard** [comment]
@svick RTM is next, short of something major happening

**Comment by danmosemsft** [comment]
@leecow is this still in plan? if so is it 2.0 (if not please change to future for us)

**Comment by mellinoe** [comment]
Given that we won't have many "individual packages" anymore, I would think that this is much less confusing than before. Additionally, the version numbers we do have correspond with the "marketed" versions of the products. For example, version 2.0.0 of Microsoft.NETCore.App and NETStandard.Library will represent .NET Core 2.0 and .NET Standard 2.0. I can't speak for the external components like ASP.NET, but the lower-level packages look reasonable to  me.

**Comment by leecow** [comment]
Currently, RTM level .NET Core packages are just the version number with no suffix. eg NETCore.APP is 1.0.4. We are having discussions around 2.0 versioning so additional refinement is certainly possible.

**Comment by mellinoe** [comment]
I'm going to say that, unless there's concrete improvements to be made, we can close this. When originally filed, we had tons of different packges with weird and confusing version numbers. Nowadays, it is vastly simplified, and all of the version numbers make more sense, especially the stable versions.
