### ISSUE TITLE
UnixDomainSocketEndPoint should set length instead of null-terminating

### ISSUE THREAD

**Issue by tmds** [dotnet/corefx#8727]
I've used (a copy of) UnixDomainSocketEndPoint to connect to a unix socket with an abstract address (path starts with a zero-byte). The connect call failed with ECONNREFUSED. When I changed the implementation to pass `2 + _encodedPath.Length` instead of `s_nativeAddressSize` in Serialize the connect works.

\cc @stephentoub

**Comment by tmds** [comment]
This class is internal, so there is no hurry to fix this.

**Comment by ericeil** [comment]
From the Linux ["unix (7)" man page](http://man7.org/linux/man-pages/man7/unix.7.html):

>        *  abstract: an abstract socket address is distinguished (from a
          pathname socket) by the fact that sun_path[0] is a null byte
          ('\0').  The socket's address in this namespace is given by the
          additional bytes in sun_path that are covered by the specified
          length of the address structure.  (Null bytes in the name have no
          special significance.)  The name has no connection with filesystem
          pathnames.  When the address of an abstract socket is returned,
          the returned addrlen is greater than sizeof(sa_family_t) (i.e.,
          greater than 2), and the name of the socket is contained in the
          first (addrlen - sizeof(sa_family_t)) bytes of sun_path.  The
          abstract socket namespace is a nonportable Linux extension.

So, this is a Linux-specific, and special-purpose, usage of UNIX-domain sockets.  I think this is outside of the scope of the (internal) `UnixDomainSocketEndPoint` type.

**Comment by tmds** [comment]
@ericeil the null terminating is idependent of the socket being abstract. Please also have a look at the BUGS section in the man page you referenced.
