### ISSUE TITLE
Question: How to get RegionInfo from CultureInfo

### ISSUE THREAD

**Issue by Tasteful** [dotnet/corefx#8735]
In net45 I was using the following code to get the correct region info.
```
var ci = new System.Globalization.CultureInfo("sv-SE");
var ri = new System.Globalization.RegionInfo(ci.LCID);
```
Is there any way that I can do more or less the same in dotnet-core?

The reason is that the Swedish region info (if created from `SE`) is returned the following; that not is the main region information, and need to find correct main region.
```
PS> New-Object system.globalization.regioninfo("SE")

Name                         : SE
EnglishName                  : Sweden
DisplayName                  : Sweden
NativeName                   : Ruoŧŧa
TwoLetterISORegionName       : SE
ThreeLetterISORegionName     : SWE
ThreeLetterWindowsRegionName : SWE
IsMetric                     : True
GeoId                        : 221
CurrencyEnglishName          : Swedish Krona
CurrencyNativeName           : ruvdnu
CurrencySymbol               : kr
ISOCurrencySymbol            : SEK
```

If I go with the LCID instead from `CultureInfo("sv-SE")` I got the correct main region out.
```
PS> New-Object system.globalization.regioninfo((New-Object system.globalization.cultureinfo("sv-se")).LCID)


Name                         : SE
EnglishName                  : Sweden
DisplayName                  : Sweden
NativeName                   : Sverige
TwoLetterISORegionName       : SE
ThreeLetterISORegionName     : SWE
ThreeLetterWindowsRegionName : SWE
IsMetric                     : True
GeoId                        : 221
CurrencyEnglishName          : Swedish Krona
CurrencyNativeName           : Svensk krona
CurrencySymbol               : kr
ISOCurrencySymbol            : SEK
```

**Comment by svick** [comment]
To me, this looks like a bug when searching which culture is the main culture for a region.

`RegionInfo` uses `CultureData` for that and [`CultureData` has a hard-coded table with the right value](https://github.com/dotnet/coreclr/blob/3e537a4/src/mscorlib/src/System/Globalization/CultureData.cs#L306), but [it's not used on CoreCLR](https://github.com/dotnet/coreclr/blob/3e537a4/src/mscorlib/src/System/Globalization/CultureData.cs#L802-L812) (notice the `#endif`).

**Comment by tarekgh** [comment]
@Tasteful did you try to do the following?: 

```
new RegionInfo(new CultureInfo("sv-SE").Name);
```

this should give you the region match the specified culture.

**Comment by Tasteful** [comment]
@tarekgh Yes, it was returning correct, thanks!

I didn't try to use `sv-SE` for the name of the RegionInfo, reason when we fetched the RegionInfo from LCID in previous versions the RegionInfo.Name was `SE` and not `sv-SE`.

**Comment by svick** [comment]
@tarekgh So, ignoring `RegionNames` is expected on CoreCLR? Why?

**Comment by tarekgh** [comment]
@svick we don't ignore the region names in coreclr. you can try it yourself by instantiating RegionInfo("US") for instance. the mechanism used in the desktop of using the hardcoded mapping table is not really needed as we have a different way to do that without hardcoding such table. 

thanks all for bringing this discussion

**Comment by svick** [comment]
@tarekgh If I understand [the code correctly](https://github.com/dotnet/coreclr/blob/3e537a4/src/mscorlib/src/System/Globalization/CultureData.cs#L802-L829), the hardcoded table is needed to find the right "primary" culture for a region. And in the absence of looking up the table, the code uses the first culture from the given region it can find. And I don't think that's correct.

This is what was reported originally in this issue: `new RegionInfo("SE")` returns `se-SE`, when it should return `sv-SE`. But it happens for other cases too, for example:

Region | Correct "primary" culture | .Net Core culture
--- | --- | ---
SE | sv-SE | se-SE
GB | en-GB | cy-GB
IL | he-IL | ar-IL
RU | ru-RU | ba-RU
PK | ur-PK | en-PK
FR | fr-FR | br-FR

You can test this by checking the `NativeName`. For example, [this code](https://gist.github.com/svick/7979f3d13822942095cb414d0dcb53c5):

The output for `dotnet run -f net461`:

```
Sverige
United Kingdom
ישראל
Россия
پاکستان
France
```

For `dotnet run -f netcoreapp1.0`:

```
Ruoŧŧa
Y Deyrnas Unedig
إسرائيل
Рәсәй
Pakistan
Frañs
```
