### ISSUE TITLE
DCS/DCJS: CultureInfo is not serializable

### ISSUE THREAD

**Issue by SGuyGe** [dotnet/corefx#8736]
Today, if you try to serialize CultureInfo, you'll get the following error:

System.Runtime.Serialization.InvalidDataContractException : Type 'System.Globalization.CompareInfo' cannot be serialized. Consider marking it with the DataContractAttribute attribute, and marking all of its members you want serialized with the DataMemberAttribute attribute. Alternatively, you can ensure that the type is public and has a parameterless constructor - all public members of the type will then be serialized, and no attributes will be required.

**Comment by shmao** [comment]
We think PR #9014 would be the right fix. The issue with it is that the payloads on CoreCLR and Desktop are not compatible. Opened #10513 for that issue.

**Comment by karelz** [comment]
No customer asks so far, closing for now.
