### ISSUE TITLE
failure in System.Threading.Tests.MutexTests.AbandonExisting

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#8745]
@kouvel It seems these tests should not be enabled for Ubuntu?

System.PlatformNotSupportedException : Named synchronization primitives are not supported on this platform.

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug_prtest/1439/

**Comment by danmosemsft** [comment]
From https://github.com/dotnet/corefx/pull/8741

**Comment by kouvel** [comment]
Hmm this is bizarre, PR #8625 showed me green when I merged. I guess CoreFX tests are not yet using the latest CoreCLR bits. Should I revert #8625?
