### ISSUE TITLE
OS-independent libraries should be built to an OS-independent folder

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#875]
Once #818 gets merged, we should refactor how our binaries are built to output paths.  Libraries that have no direct OS-dependencies and do not have an OS-specific build should go into a neutral folder, and libraries that have OS-specific builds should go into an OS-specific folder.

**Comment by weshaggard** [comment]
I'm was thinking about this more and I want to figure out the high level build scenarios we support. I believe we have:

1. Building via configuration in VS:
    * {Flavor}
    * {OS_Flavor}
2. Building via command line (either from root or local project)
    * /p:Configuration={Flavor} /p:OS={OS}
    * /p:Configuration={OS}_{Flavor}

While we can control the VS configurations by only including the relevent ones in VS we don't have a good way to block or skip the invalid configurations at the command line. This makes it difficult to consistently create an AnyOS default drop location for libraries that aren't OS specific. We could add some more properties in the projects that would allow people to sepcify the OS configurations and use that information but that seems like a lot of duplication. We would need something like.

    <ItemGroup>
      <SupportedOS Include="Windows_NT;Unix" /> // Excluding this on projects that are AnyOS
    </ItemGroup>
    <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), dir.props))\dir.props" />
    <PropertyGroup>
      <Configuration Condition="'$(Configuration)' == ''">Windows_Debug</Configuration>
      <Platform Condition="'$(Platform)' == ''">AnyCPU</Platform>
      <ProjectGuid>{879C23DC-D828-4DFB-8E92-ABBC11B71035}</ProjectGuid>
      <OutputType>Library</OutputType>
      <AssemblyName>System.IO.FileSystem</AssemblyName>
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    ...
    
    <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Windows_Debug|AnyCPU'" />
    <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Windows_Release|AnyCPU'" />
    <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Unix_Debug|AnyCPU'" />
    <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Unix_Release|AnyCPU'" />

With the list of Supported OS's we could then do some exclusion, eroring, or simply overriding properties for libraries based on the given config. 
Another option would be to have some way of filtering the projects when you do a root build but it would really be nice if the project itself could keep this information in its project.

Thoughts @stephentoub @mmitche?

**Comment by mmitche** [comment]
That sounds reasonable.  We actually had something similar to this in the old Phoenix days.

We had builds like this:

msbuild /p:Arch=*;Host=x86

Arch would be evaluated to the set of Architectures for which Host=x86 was valid.  We did it using some form of Supported* properties.

**Comment by weshaggard** [comment]
@stephentoub I feel this issue is now address with our recent build changes. Do you agree? If so feel free to close this issue.
