### ISSUE TITLE
String formatting tests fail when run on some cultures

### ISSUE THREAD

**Issue by svick** [dotnet/corefx#8753]
When I run `msbuild /t:BuildAndTest System.Runtime.Tests.csproj`, I get many failures in string formatting tests (including `StringBuilder` and `.Parse()`). The cause seems to be culture: the tests appear to run in my system culture, which uses `,` as decimal separator, while the tests expect `.`. 

[Tests output](https://gist.github.com/svick/383824511c8778d57e959355082e35fd)

I expect the fix is to force the thread to invariant culture for those tests.

**Comment by hughbe** [comment]
That'll be my fault I think while doing adding some tests - I'll investigate this

**Comment by hughbe** [comment]
Also, these aren't just StringBuilder, but also other System.Runtime tests

**Comment by svick** [comment]
@hughbe You're right. I have updated the initial issue.

**Comment by hughbe** [comment]
@svick which culture are you using - the Parse and ToString ones should be easy to fix, but I might need a bit more info about the culture to check out the DateTime failures

**Comment by svick** [comment]
@hughbe Yeah, I'm using `cs-CZ`.

**Comment by hughbe** [comment]
@svick I've fixed System.Runtime.Tests - are any other tests failing with reasons related to cultures so that I could fix them too?

**Comment by svick** [comment]
@hughbe No, no other tests are failing on my machine.

**Comment by tarekgh** [comment]
thanks @hughbe for fixing this issue.
