### ISSUE TITLE
Resources only work when placed in the default namespace

### ISSUE THREAD

**Issue by srollinet** [dotnet/corefx#8754]
Using RC2 version, if a resource is placed outside the default namespace, its ResourceManager throws a _MissingManifestResourceException_ when it tries to get the ResourceSet

**Scenario:**

- Project Name: `TestResx`
- Default Namespace: `TestResx`
- Resource file: Resources/Res.resx (namespace: `TestResx.Resources`)

**Expected behavior:**

- The resource is embedded as TestResx.Resources.Res.resources
- At runtime, it is possible to get a value from this resource

**Actual behavior:**

- The resource is embedded as TestResx.Resources.Res.resources -> OK
- At runtime, a _MissingManifestResourceException_ is thrown

**Workaround:**

Add a namedResource in Project.json to force the resource to be embedded as TestResx.Res.resources
```
  "namedResource": {
    "TestResx.Res": "Resources\\Res.resx"
  }
```

Demo project: [TestResx.zip](https://github.com/dotnet/corefx/files/275965/TestResx.zip)

I have seen that a quite similar issue have been closed as resolved in RC2. (https://github.com/aspnet/Tooling/issues/311 , https://github.com/dotnet/cli/issues/548) But it seems that it is not resolved. Note, it is not exactly the same case, so maybe the other case is really resolved.

**Comment by ramarag** [comment]
This is a CLI issue closing this and opening as https://github.com/dotnet/cli/issues/3247
