### ISSUE TITLE
Update NetCoreApp metapackage to carry updated Roslyn package

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/corefx#8755]
This is required to enable TPA overriding in AssemblyLoadContext(https://github.com/dotnet/coreclr/pull/5144) committed. Supporting Roslyn and CoreFX changes are already committed.

CC @jkotas @weshaggard @jaredpar @eerhardt

**Comment by eerhardt** [comment]
The latest version of `Microsoft.NETCore.App` is on Roslyn as of https://github.com/dotnet/core-setup/pull/12.

CLI is almost on it.  See https://github.com/dotnet/cli/pull/3260.

Once #3260 is merged, I'll close this issue.

**Comment by eerhardt** [comment]
https://github.com/dotnet/cli/pull/3260 is now merged.  This issue can be closed.

**Comment by eerhardt** [comment]
CLI is now on Roslyn `1.3.0-beta1-20160525-03`
