### ISSUE TITLE
link to the release notes github tag from the nuspec files

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#8758]
New bug copied from conversation @ https://github.com/dotnet/corefx/issues/1706

from @akoeplinger --

> The only other suggestion I'd have is adding the link to the releaseNotes tag into the nuspec for the packages as well, so they show up on nuget.org.

**Comment by ericstj** [comment]
@joshfree @leecow can you provide a FWLink for this?  Do we want the same link for every package or a unique link per package.  We might be able to pass package ID as a query param if that's helpful.

**Comment by leecow** [comment]
@ericstj For the Release Notes (https://github.com/dotnet/core/blob/master/release-notes/1.0/Release-Notes-RC2.md), API diff (https://github.com/dotnet/core/blob/master/release-notes/1.0/RC1-RC2_API_diff.md) or both?

**Comment by joshfree** [comment]
@leecow this is for the _next_ round of releases like 1.0.0 or 1.1.0-beta. :smile: 

See how https://www.nuget.org/packages/Microsoft.Bcl/ has a Project Site link where as https://www.nuget.org/packages/System.Net.Http/4.0.1-rc2-24027 does not.

How about we create a FWLink that points to https://github.com/dotnet/core/blob/master/release-notes/Release-Notes-1.0.0.md and @ericstj can add the fwlink to the nuspec files?

**Comment by ericstj** [comment]
Yeah, and we just need to make sure to update that with every release.

**Comment by leecow** [comment]
Sounds good. FWIW, we'll used versioned dirs under release-notes to enable better capturing of the various assets. eg https://github.com/dotnet/core/blob/master/release-notes/1.0

**Comment by joshfree** [comment]
@leecow could you create an FWLink for 1.0.0-rtm and another for 1.1.0-beta* and share them back?

**Comment by leecow** [comment]
When the time comes, the fwlink will be https://go.microsoft.com/fwlink/?LinkID=799417

**Comment by leecow** [comment]
Release-Notes-1.1.0-beta.md will be https://go.microsoft.com/fwlink/?LinkID=799421

**Comment by ericstj** [comment]
What would you guys like the "Project Site" to point to:  http://dotnet.github.io/ or http://dot.net?
/cc @richlander

**Comment by ericstj** [comment]
Ping.  Please let me know.

**Comment by joshfree** [comment]
Point it to https://dot.net/
