### ISSUE TITLE
Pipes tests failing on CentOS innerloop - UnauthorizedAccessException : Access to the path '/tmp/.dotnet/corefx' is denied

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#8761]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/release_1.0.0/job/centos7.1_release_tst_prtest/4/testReport/

MESSAGE:
System.UnauthorizedAccessException : Access to the path '/tmp/.dotnet/corefx' is denied.\n---- System.IO.IOException : Permission denied
+++++++++++++++++++
STACK TRACE:
at System.IO.Pipes.PipeStream.CreateDirectory(String directoryPath) at System.IO.Pipes.PipeStream.EnsurePipeDirectoryPath() at System.IO.Pipes.PipeStream.GetPipePath(String serverName, String pipeName) at System.IO.Pipes.NamedPipeServerStream.Create(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, HandleInheritability inheritability) at System.IO.Pipes.Tests.NamedPipeTest_CreateServer.Unix_GetHandleOfNewServerStream_Throws_InvalidOperationException() ----- Inner Stack Trace -----

**Comment by stephentoub** [comment]
I have a theory:

@mmitche, do any runs happen under sudo? I think if the first run to happen on the machine is elevated, the temp corefx directories will be created with root as owner and without write permissions for other. Then when subsequent runs try to run non elevated and modify these directories, they fail with permissions errors. That's just a guess. Should be easy enough to test.

**Comment by ellismg** [comment]
@stephentoub Yes.  All outerloop runs happen under sudo.  I think that https://github.com/dotnet/corefx/pull/8364 should have addressed this, but if we do a run with are CoreFX that doesn't have the fix, then the machine is poisoned.

I tried to to look at the history of runs on the machine that failed but Jenkins just spun forever.  I did connect to the machine and confirm it had the same problem as when I saw this previously.

**Comment by stephentoub** [comment]
> I think that #8364 should have addressed this, but if we do a run with are CoreFX that doesn't have the fix, then the machine is poisoned.

I was actually referring to the fact that typically normal users and root have different default umasks, so I'm hypothesizing that even with that change we may have an issue if the temp dirs are created by root. You might be entirely right, of course, and my hypothesis may be way off.

**Comment by ellismg** [comment]
> I was actually referring to the fact that typically normal users and root have different default umasks, so I'm hypothesizing that even with that change we may have an issue if the temp dirs are created by root. 

Ahh, I see.  I don't think that's the case here (this is on the machine that failed):

```
[dotnet-bot@Azure0521064929 tmp]$ umask -S
u=rwx,g=rwx,o=rx
[root@Azure0521064929 tmp]# umask -S
u=rwx,g=rx,o=rx
```

I was able to pull up the history of the above machine and the first job it ran was an outerloop run for RC2, which didn't have your fix.  Everything failed since then.  I think it would be best to add `sudo rm -rf /tmp/.dotnet` to the end of the RC2 runs as a tactical fix.

**Comment by stephentoub** [comment]
> I was able to pull up the history of the above machine and the first job it ran was an outerloop run for RC2, which didn't have your fix. Everything failed since then. I think it would be best to add  sudo rm -rf /tmp/.dotnet  to the end of the RC2 runs as a tactical fix.

Great. Thanks, Matt!

**Comment by ellismg** [comment]
@stephentoub Actually, thinking about this more, in both cases the default umask restricts world access from the folder we create, which will prevent the sharing we want.

I think that we need to enforce we set the permissions to world writable after creating it.

**Comment by ellismg** [comment]
I am going to fix this.
