### ISSUE TITLE
ReadLinesReader.CreateIterator might not dispose a stream

### ISSUE THREAD

**Issue by pdelvo** [dotnet/corefx#8773]
I just discovered [this](https://github.com/dotnet/corefx/blob/538a35ee2e7fe09ea5024ad464cb99331fec0b05/src/System.IO.FileSystem/src/System/IO/ReadLinesIterator.cs#L100) dubious line in the ReadLineIterator. If the StreamReader reader is not null the method still opens a stream but never disposes it or returns it in any way to the caller. This looks wrong to me.
This might happen if Clone() is called.

I think this should be fixed or a comment should be added explaining why this is the correct behavior.

**Comment by stephentoub** [comment]
Fixed by #8789
