### ISSUE TITLE
Server.MapPath("~/App_Data/test.xml")

### ISSUE THREAD

**Issue by 29795113** [dotnet/corefx#8774]
In MVC Controller,can i use "Server.MapPath"? The "Server.MapPath" does not exists.

**Comment by danroth27** [comment]
You can get access to the file providers for both the web root and the content root using the `IHostingEnvironment` service, which is available to your controllers through DI.

If you would like to discuss this further please open an issue in the ASP.NET Core [Hosting](https://github.com/aspnet/hosting) repo.
