### ISSUE TITLE
Interop.mincore.IdnToAscii/IdnToUnicode fails on UWP

### ISSUE THREAD

**Issue by luqunl** [dotnet/corefx#8783]
there are two pinvoke definitions in Interop.Idna.cs which isn't compatible with UWP app. 
https://github.com/dotnet/corefx/blob/d7d2f7a83269b9540cd9a966338149dcc014171b/src/Common/src/Interop/Windows/mincore/Interop.Idna.cs

1>  Compiling interop code
1>c:\users\namc\documents\visual studio 2015\Projects\App2\App2\obj\x86\Release\ilc\intermediate\App2.McgInterop\PInvoke.g.cs(2132,21): error : The best overloaded method match for 'McgInterop.api_ms_win_core_localization_l1_2_0_dll_PInvokes.IdnToUnicode(uint, ushort_, int, ushort_, int)' has some invalid arguments
1>c:\users\namc\documents\visual studio 2015\Projects\App2\App2\obj\x86\Release\ilc\intermediate\App2.McgInterop\PInvoke.g.cs(2136,9): error : Argument 4: cannot convert from 'char_' to 'ushort_'
1>c:\users\namc\documents\visual studio 2015\Projects\App2\App2\obj\x86\Release\ilc\intermediate\App2.McgInterop\PInvoke.g.cs(2231,21): error : The best overloaded method match for 'McgInterop.api_ms_win_core_localization_l1_2_0_dll_PInvokes.IdnToAscii(uint, ushort_, int, ushort_, int)' has some invalid arguments
1>c:\users\namc\documents\visual studio 2015\Projects\App2\App2\obj\x86\Release\ilc\intermediate\App2.McgInterop\PInvoke.g.cs(2235,9): error : Argument 4: cannot convert from 'char_' to 'ushort_'
1>c:\users\namc\documents\visual studio 2015\Projects\App2\App2\obj\x86\Release\ilc\intermediate\App2.McgInterop\PInvoke.g.cs(2289,21): error : The best overloaded method match for 'McgInterop.api_ms_win_core_localization_l1_2_0_dll_PInvokes.IdnToAscii__0(uint, ushort_, int, ushort_, int)' has some invalid arguments
1>c:\users\namc\documents\visual studio 2015\Projects\App2\App2\obj\x86\Release\ilc\intermediate\App2.McgInterop\PInvoke.g.cs(2293,9): error : Argument 4: cannot convert from 'char_' to 'ushort_'
1>c:\users\namc\documents\visual studio 2015\Projects\App2\App2\obj\x86\Release\ilc\intermediate\App2.McgInterop\PInvoke.g.cs(2317,21): error : The best overloaded method match for 'McgInterop.api_ms_win_core_localization_l1_2_0_dll_PInvokes.IdnToUnicode__0(uint, ushort_, int, ushort_, int)' has some invalid arguments
1>c:\users\namc\documents\visual studio 2015\Projects\App2\App2\obj\x86\Release\ilc\intermediate\App2.McgInterop\PInvoke.g.cs(2321,9): error : Argument 4: cannot convert from 'char_' to 'ushort_'

**Comment by tarekgh** [comment]
It is MCG issue as the version used in this compilation doesn't understand

[System.Runtime.InteropServices.OutAttribute()]
char* lpUnicodeCharStr

@luqunl already have a fix to convert the parameters to [out] IntPtr

**Comment by luqunl** [comment]
Fixed in #8793

**Comment by luqunl** [comment]
@joshfree @stephentoub @weshaggard We already did internal code review and if you still have comments, please let me know.

**Comment by stephentoub** [comment]
> if you still have comments, please let me know.

I left a comment on the PR:
https://github.com/dotnet/corefx/pull/8793#discussion_r64319395

**Comment by bartonjs** [comment]
I think we've solved this for RTM (#8865), which even included Stephen's comment about the other char\*.  So I'm changing the milestone to 1.1.0, assuming this is still open to track that the fix was different in master (one char\*, one IntPtr) and RTM (two IntPtr).

**Comment by karelz** [comment]
@luqunl this is already done, isn't it? If yes, can you please close it?
cc: @tijoytom @yizhang82

**Comment by luqunl** [comment]
Yes, the issue has been solved long time ago and close this issue
