### ISSUE TITLE
FileStream to fully support externally open files

### ISSUE THREAD

**Issue by adontz** [dotnet/corefx#8797]
# Proposal

Add

    FileStream(string path, SafeFileHandle handle, FileAccess fileAccess, int bufferSize, bool isAsync)

platform independent constructor for externally opened files, when both handle and path are known.

# Rationale

My case is good support for Transactioned NTFS file stream

https://bitbucket.org/triflesoft/nabu/src/c52a39909bab429e4a7ce61fa1432e1d48b09ca9/Sources/Modules/Nabu.Platform.Vista/FileSystem/Streams/TxFileStream.cs

where I open file by calling CreateFileTransactedW native API function and know both path and handle, but cannot supply both to constructor and forced to use dirty hack.

Maybe there are other similar cases I do not know about. Anyway this is just a few lines of code which will break nothing. So effort is small and risk is absent.

**Comment by ianhays** [comment]
The path given to the FileStream constructors is only used to create the underlying stream and the only other thing it would affect is calling the `Name` property. Is it worth adding another set of constructors just to allow setting a property that isn't functionally used anywhere? If so, would it not make more sense to just allow setting the Name? 

Further, the `Name` property is only there to  `Get the name of the FileStream that was passed to the constructor`([docs](https://msdn.microsoft.com/en-us/library/system.io.filestream.name(v=vs.110).aspx)), so adding a constructor to allow setting a property that is defined only as the value set in the constructor is imo adding unnecessary bloat.
