### ISSUE TITLE
[UWP] Latest RC3 failed on Update 2

### ISSUE THREAD

**Issue by shmao** [dotnet/corefx#8798]
I was trying the latest RC3 packages with VS Update 2 in my UWP test app, but I got the following errors when building the app,

```
error : The best overloaded method match for 'McgInterop.api_ms_win_core_localization_l1_2_0_dll_PInvokes.IdnToAscii(uint, ushort*, int, ushort*, int)' has some invalid arguments
```
We need to port #8793 to the release branch of RC3.

**Comment by joshfree** [comment]
@yizhang82 @sergiy-k can you get this through the system.  This has been sitting here for 9 days

**Comment by joshfree** [comment]
per offline thread @shmao is unable to repro on a newer build with the fix
