### ISSUE TITLE
System.Numerics.Vectors package does not include XML documentation for "ref" assembly

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#8803]
(This has been a problem for a while, but I'm just filing the issue to track it more officially)

Despite being produced by the library source code, the XML documentation for System.Numerics.Vectors isn't in the `netstandard1.0` ref folder in the nuget package, so you do not get Intellisense when you use the library (except on .NET Framework). Other libraries that have "ref" folders get their documentation files from part of an internal build process. We should do one of the following:

* Allow XML docs to come from the source library if they do not otherwise exist
* Copy the XML comments over to the ref library (unnecessary duplication and maintenance nightmare)

We should do the first, probably in some step in buildtools.

NOTE: This may affect other libraries than just System.Numerics.Vectors. It could theoretically affect any library with split ref-lib components. Like I mentioned above, most of the split ref-lib components get their XML docs from an internal source, but there may be some that don't.

**Comment by ianhays** [comment]
>Other libraries that have "ref" folders get their documentation files from part of an internal build process.

Weren't there a bunch of PRs recently to move those to CoreFX?
