### ISSUE TITLE
Provide API to enumerate assemblies that constitute the application

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/corefx#8806]
This has shown up a couple times as a limitation in the Win8-aot .NET profile - .NET Core doesn't provide a way to enumerate assemblies that constitute the "running application".

Frameworks such as Xamarin Forms need to use [workarounds](https://developer.xamarin.com/guides/xamarin-forms/platform-features/windows/installation/universal/#troubleshooting) to build such lists.

It can be up to a debate whether:
* We define a new API, or reuse an existing one (`AppDomain.GetAssemblies` with a well defined behavior)
* The API returns Assemblies, or string names.
* We treat System.Private assemblies specially or not.
* Etc.

**Comment by joshfree** [comment]
setting this to 1.1.0.

**Comment by danmosemsft** [comment]
AppDomain.GetAssemblies is tracked by https://github.com/dotnet/corefx/issues/9327
