### ISSUE TITLE
Desktop Microsoft.VisualBasic.dll: please consider releasing as Reference Source

### ISSUE THREAD

**Issue by iainnicol** [dotnet/corefx#8808]
It's the 25th anniversary of Visual Basic.  To celebrate, others have suggested that Microsoft open source VB6.  However, I presume that's incredibly impracticable, and moreover VB6 is long obsolete.

My alternative (still pie-in-the-sky) request is that the .NET assembly Microsoft.VisualBasic is released under an open source license at the [referencesource](https://github.com/microsoft/referencesource) repository.  I'm not going _quite_ as far as suggesting bringing all that source into corefx:  Microsoft.VisualBasic of course already exists in .NET Core, but its API footprint seems deliberately small.

The Reference Source would still be useful.  In time, the community might contribute improvements to Mono's Microsoft.VisualBasic assembly.  Mono's implementation is stagnant, and probably not of the same high quality as the rest of Mono.

CC: @dotnet-bot, @mellinoe @AlekseyTs

**Comment by OmarTawfik** [comment]
cc @VSadov @AnthonyDGreen

**Comment by iainnicol** [comment]
Closing as a dupe of the previously linked issue.
Please this is happening.
