### ISSUE TITLE
Huge performance issue with HttpClient.PostAsync after upgrade from RC1 to RC2

### ISSUE THREAD

**Issue by laskoviymishka** [dotnet/corefx#8809]
This issue related to (_https://github.com/aspnet/JavaScriptServices/issues/92_)

We faced some strange issue with `await client.PostAsync`

I created sample repository to show what we have here, you can find it [here](https://github.com/laskoviymishka/HttpIssue)

To run sample do following steps:

1. Clone repository
2. Run `cd src\WebApplication1 & dotnet restore & dotnet run`
3. Run `cd ..\ConsoleApp1\ & dotnet restore & dotnet run`
4. Check how long it takes to make 20 post api requests

To see how it works in classic .net open solution 
There is 2 console project with really same code, but .netcore version take significant longer.
Please notice that stop watch show incorrect amount of time, or may be i log it incorect.

Please notice that in RC1 version of _https://github.com/aspnet/JavaScriptServices_ the really same code perform usually for ~50-60 ms. Right not it executed ~1.2-1.5 second. 

Here is version of dotnet which i use:
`.NET Command Line Tools (1.0.0-preview1-002702)`

ConsoleApp run for following framework:
```
  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
```

JavaScriptServices for following:
```
"frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  },
```

This is major issue IMHO.

Can anyone advise? May be i miss something?

**Comment by laskoviymishka** [comment]
Guys, any information what happens here?

**Comment by pauldotknopf** [comment]
Seriously? 1.1.0? There are HUGE performance issues here.

**Comment by pauldotknopf** [comment]
Update, there was a bug in @laskoviymishka's demo repository. Replace ```Milliseconds``` with ```TotalMilliseconds```. Otherwise, you only see the milliseconds within the current second.

Here is the new output, which _clearly_ illustrates a **HUGE** issue with .NET Core.

```ConsoleApp1``` output:

```
Elapsed=1246.4032 ms
Elapsed=1032.1824 ms
Elapsed=1031.5464 ms
Elapsed=1032.7355 ms
Elapsed=1013.7454 ms
Elapsed=1010.2167 ms
Elapsed=1012.8409 ms
Elapsed=1007.1485 ms
Elapsed=1011.054 ms
Elapsed=1011.5348 ms
Elapsed=1005.3291 ms
Elapsed=1003.5637 ms
Elapsed=1021.1278 ms
Elapsed=1006.7902 ms
Elapsed=1005.657 ms
Elapsed=1010.9605 ms
Elapsed=1012.1959 ms
Elapsed=1012.4846 ms
Elapsed=1011.1206 ms
Elapsed=1009.1076 ms
Total Elapsed=20558.7293 ms
```

```ConsoleApplication1``` output:

```
Elapsed=1152.2902 ms
Elapsed=8.5079 ms
Elapsed=9.1006 ms
Elapsed=7.3624 ms
Elapsed=10.3489 ms
Elapsed=8.9677 ms
Elapsed=9.6616 ms
Elapsed=9.1713 ms
Elapsed=7.9744 ms
Elapsed=5.5812 ms
Elapsed=6.3373 ms
Elapsed=5.522 ms
Elapsed=4.5986 ms
Elapsed=3.1634 ms
Elapsed=7.9505 ms
Elapsed=2.7354 ms
Elapsed=2.2976 ms
Elapsed=2.4869 ms
Elapsed=3.334 ms
Elapsed=2.0512 ms
Total Elapsed=1276.8956 ms
```

**THIS IS A HUGE ISSUE** - 20 seconds vs 1 second.

**Comment by laskoviymishka** [comment]
@pauldotknopf good catch, I'll fix it

**Comment by laskoviymishka** [comment]
I think root issue with incorrect refactored HTTP Client for async/await.
_https://github.com/dotnet/corefx/commit/3860eab0d26527b0e5b931ef4084d40f2886ccc7_ this check-in, but i don't know what exact goes wrong. So may be @stephentoub can clarify what goes wrong?

**Comment by stephentoub** [comment]
> I think root issue with incorrect refactored HTTP Client for async/await

Why? What do you believe is incorrect?

**Comment by pauldotknopf** [comment]
@laskoviymishka, I updated the ```ConsoleApp1``` .NET Core app to use ```HttpWebRequest```, and I am getting similar numbers.

```
var request = (HttpWebRequest)WebRequest.Create("http://localhost:5000/api/values");
var postData = test;
var data = Encoding.ASCII.GetBytes(postData);
request.Method = "POST";
request.ContentType = "application/json";
using (var stream = await request.GetRequestStreamAsync())
    stream.Write(data, 0, data.Length);
var response = (HttpWebResponse)await request.GetResponseAsync();
var responseString = new StreamReader(response.GetResponseStream()).ReadToEnd();
```
Here is the new output from ```ConsoleApp1```.

```
Elapsed=1208.6815 ms
Elapsed=1022.4424 ms
Elapsed=1004.315 ms
Elapsed=1011.8565 ms
Elapsed=1024.8138 ms
Elapsed=1037.4788 ms
Elapsed=1034.5559 ms
Elapsed=1016.2428 ms
Elapsed=1044.4701 ms
Elapsed=1008.4721 ms
Elapsed=1010.0438 ms
Elapsed=1018.9544 ms
Elapsed=1014.1132 ms
Elapsed=1016.1196 ms
Elapsed=1018.499 ms
Elapsed=1014.0996 ms
Elapsed=1015.9352 ms
Elapsed=1017.0223 ms
Elapsed=1011.5338 ms
Elapsed=1012.8163 ms
Total Elapsed=20622.7174 ms
```

I think the issue is deeper.

**Comment by laskoviymishka** [comment]
@stephentoub i just tried to check what changed between rc1 and rc2 version of http client, and this one was biggest change. I not really understand what exactly goes wrong :cry:, but this issue is really annoying.

**Comment by laskoviymishka** [comment]
@pauldotknopf can you trace each line? What exact line take this 1000 ms?

**Comment by pauldotknopf** [comment]
```GetResponseAsync``` is the culprit.

**Comment by laskoviymishka** [comment]
@pauldotknopf well this method made `Task.Run` for `WebRequest.BeginGetResponse`. It will be difficult to check what goes wrong here

**Comment by stephentoub** [comment]
Have you tried changing the sample to reuse the same HttpClient instance across all requests, rather than creating and destroying a new one for each use?

**Comment by stephentoub** [comment]
All of the time is being spent in HttpClient.Dispose.  If you change the repro to use the same HttpClient instance for all calls, it's super fast again, and if you change your repro to be like this:
```C#
			Stopwatch sw = new Stopwatch();

			sw.Start();
                        var client = new HttpClient();
			
			var payload = new StringContent(test, Encoding.UTF8, "application/json");
			var response = await client.PostAsync("http://localhost:5000/api/values", payload);
			
			sw.Stop();

                        var disposeTime = Stopwatch.StartNew();
                        client.Dispose();
                        Console.WriteLine($"Dispose time: {sw.Elapsed.TotalMilliseconds}");

			Console.WriteLine("Elapsed={0} ms", sw.Elapsed.TotalMilliseconds);
```
you can see that basically all of the time is spent in HttpClient.Dispose:
```
Dispose time: 1234.8827
Elapsed=1234.8827 ms
Dispose time: 1014.9668
Elapsed=1014.9668 ms
Dispose time: 1018.3572
Elapsed=1018.3572 ms
Dispose time: 1023.7303
Elapsed=1023.7303 ms
Dispose time: 1025.7101
Elapsed=1025.7101 ms
Dispose time: 1022.8705
Elapsed=1022.8705 ms
Dispose time: 1017.0113
Elapsed=1017.0113 ms
Dispose time: 1021.0546
Elapsed=1021.0546 ms
Dispose time: 1014.9857
Elapsed=1014.9857 ms
Dispose time: 1024.3941
Elapsed=1024.3941 ms
Dispose time: 1031.5426
Elapsed=1031.5426 ms
Dispose time: 1026.4339
Elapsed=1026.4339 ms
Dispose time: 1019.1961
Elapsed=1019.1961 ms
Dispose time: 1015.6744
Elapsed=1015.6744 ms
Dispose time: 1013.9754
Elapsed=1013.9754 ms
Dispose time: 1013.8171
Elapsed=1013.8171 ms
Dispose time: 1018.8816
Elapsed=1018.8816 ms
Dispose time: 1012.507
Elapsed=1012.507 ms
Dispose time: 1015.4828
Elapsed=1015.4828 ms
Dispose time: 1013.9117
Elapsed=1013.9117 ms
Total Elapsed=20698.0268 ms
```

**Comment by laskoviymishka** [comment]
@stephentoub great, thank you! 
But why this behaivior changed from rc1? Does this change documented anywhere?

**Comment by stephentoub** [comment]
> But why this behaivior changed from rc1? Does this change documented anywhere?

I don't know.  I was simply narrowing down where the cost was coming from (and highlighting that it wasn't my change :wink:).  @davidsh would need to comment.

**Comment by laskoviymishka** [comment]
@stephentoub sorry for this dirty trick to get you involved :sweat:, i just saw that you was last who made major change into probably root cause. Thx for really fast reply!

**Comment by stephentoub** [comment]
> sorry for this dirty trick to get you involved

I had a feeling I was being baited :wink:

**Comment by stephentoub** [comment]
@davidsh just pointed out to me that my example above had a silly typo in it (fixed) where I was outputting the wrong time; it would have potentially incorrectly pointed the finger at Dispose when in reality the problem could have been elsewhere.  However, after fixing my mistake, I just tried the repro again, and I'm no longer able to repro any perf problem, with either the release/1.0.0 bits or with what's currently in master.

**Comment by CIPop** [comment]
@laskoviymishka Can you still repro this issue? 

Investigating performance I've found a few potential causes: #12217, #11979, #11978, #11910.
Except #1910, none of my attempts to repro showed the same behavior.

**Comment by laskoviymishka** [comment]
@CIPop i update my initial repro repository. Looks like it still reproducing (see ConsoleApp2 for latest .net core).

**Comment by CIPop** [comment]
I'm not able to build the server from your repo because it references rc2 which is no longer under support.
```
The specified framework 'Microsoft.NETCore.App', version '1.0.0-rc2-3002702' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\shared\Microsoft.NETCore.App
  - The following versions are installed:
      1.0.0
  - Alternatively, install the framework version '1.0.0-rc2-3002702'.
```

I've changed the file this way: https://gist.github.com/CIPop/1bc8b2851c0bc066f59b80d9815ab2e2 to be able to run it.

I ran two tests:

## Baseline run against IIS + ASHX:

I was able to build the client and test against an IIS + a [very simple Echo.ashx ](https://gist.github.com/CIPop/ba74bf3563b51b2faff9500129d58c6d) getting the following results:

```
S:\temp\HttpIssue\src\ConsoleApp2>dotnet run
Project ConsoleApp2 (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Elapsed=73.9708 ms
Elapsed=5.6147 ms
Elapsed=4.7124 ms
Elapsed=4.2649 ms
Elapsed=4.2473 ms
Elapsed=4.5315 ms
Elapsed=3.9881 ms
Elapsed=3.8771 ms
Elapsed=4.9626 ms
Elapsed=4.0792 ms
Elapsed=4.0895 ms
Elapsed=3.8502 ms
Elapsed=4.7903 ms
Elapsed=3.8739 ms
Elapsed=3.9397 ms
Elapsed=3.8357 ms
Elapsed=4.1212 ms
Elapsed=4.3198 ms
Elapsed=4.4654 ms
Elapsed=4.0474 ms
Total Elapsed=166.7154 ms
```

## Running the test as described:
```
S:\temp\HttpIssue\src\ConsoleApp2>dotnet run
Project ConsoleApp2 (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Elapsed=76.9277 ms
Elapsed=9.5269 ms
Elapsed=9.3799 ms
Elapsed=9.6991 ms
Elapsed=9.8749 ms
Elapsed=9.5429 ms
Elapsed=9.0771 ms
Elapsed=9.0159 ms
Elapsed=10.1735 ms
Elapsed=10.92 ms
Elapsed=10.1424 ms
Elapsed=9.7261 ms
Elapsed=10.6611 ms
Elapsed=10.2534 ms
Elapsed=9.4916 ms
Elapsed=9.446 ms
Elapsed=9.6565 ms
Elapsed=9.8974 ms
Elapsed=9.5057 ms
Elapsed=9.3944 ms
Total Elapsed=274.8266 ms


S:\temp\HttpIssue\src\ConsoleApp2>dotnet run
Project ConsoleApp2 (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Elapsed=81.6058 ms
Elapsed=9.7386 ms
Elapsed=9.6141 ms
Elapsed=10.4029 ms
Elapsed=10.3095 ms
Elapsed=11.0124 ms
Elapsed=10.2919 ms
Elapsed=11.1487 ms
Elapsed=10.3455 ms
Elapsed=10.0767 ms
Elapsed=8.826 ms
Elapsed=10.1492 ms
Elapsed=9.6616 ms
Elapsed=9.5121 ms
Elapsed=9.5256 ms
Elapsed=9.2937 ms
Elapsed=10.1219 ms
Elapsed=11.4916 ms
Elapsed=10.6974 ms
Elapsed=10.7503 ms
Total Elapsed=287.0246 ms
```

@davidfowl @Tratcher PTAL There is a substantial drop in performance (>35%) when running against the ASP.Net core server using dotnet run.

@laskoviymishka I can't see the ~1 second/request times. Please confirm that running the latest version (1.0.1) you can see the same behavior.

**Comment by laskoviymishka** [comment]
@CIPop well it does. At least for me
![image](https://cloud.githubusercontent.com/assets/2754361/19003911/ae9c2dda-875b-11e6-85ed-a5a62f393ebd.png)

I just tried on fresh machine with fresh installed latest visual studio .

**Comment by CIPop** [comment]
@laskoviymishka Since you can repro we need to collect more information:

  * What OS version are you using? What machine configuration (CPU: number of sockets, cores, logical processors; RAM)?
  * Please confirm that you're using .Net Core 1.0.0 (or 1.0.1). 
  * In the example above, is there a difference between the top left and top right apps ? (Is it that one uses HttpClient and the other HttpWebRequest?)
  * In the example above, please confirm that ConsoleApplication1.exe is making the query towards the same localhost server.
  * Try building (client and server) and running Release: does this still repro?
`dotnet build -c Release`
From the server folder:  `dotnet .\bin\Release\netcoreapp1.0\WebApplication1.dll`
From the client folder: `dotnet .\bin\Release\netcoreapp1.0\ConsoleApp2.dll`

  * Please capture performance traces for both the .Net Desktop exe (baseline) as well as the ConsoleApp2 using .Net Core 1.0.1:

    Install the latest Perfview https://www.microsoft.com/en-us/download/details.aspx?id=28567.
    Run `perfview /logFile:ConsoleApp2Perf.log /dataFile:ConsoleApp2Perf.data /ThreadTime /zip:true /KernelEvents:Default+VirtualAlloc run dotnet .\bin\Release\netcoreapp1.0\ConsoleApp2.dll` 
    This should create a ConsoleApp2Perf.log and .zip files. Please share these two files with us (can be hundreds of MB).

**Comment by laskoviymishka** [comment]
@CIPop 

- I use win 10, 16gb ram i7. It pretty powerfull
- Could you please point me how i can ensure version of .net core? dotnet --version or something different?
- yes
- yes

**Comment by CIPop** [comment]
Thanks @laskoviymishka!

> Could you please point me how i can ensure version of .net core? dotnet --version or something different

First take a look at what SDKs you have installed. 
![image](https://cloud.githubusercontent.com/assets/8635911/19006702/d01bb8e0-8715-11e6-8b02-5f802ea974fd.png)

You should uninstall non-RTM versions at this time.

Second, change the project.json to use either 1.0.0 or 1.0.1. For the server, use https://gist.github.com/CIPop/1bc8b2851c0bc066f59b80d9815ab2e2 

You already have done this for ConsoleApp2 in your GH repo. You may want to change ConsoleApp1 to 1.0.1 as well:
```
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },
```
or 
```
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.1"
    }
  },
```

> I use win 10, 16gb ram i7. It pretty powerfull

How many CPU cores / logical cores does it have? (See Task Manager.) This could be relevant for #12217.

**Comment by laskoviymishka** [comment]
@CIPop looks like there was 2 conflicted version (one preview 2), after removing old one it become blazing fast.
![image](https://cloud.githubusercontent.com/assets/2754361/19007317/0861500a-876d-11e6-917f-96dd3d30b5c2.png)
Even so i don't see any performance degradation in compare to classic .net.
So i believe it closed. 
Just from curiosity could you please point me to changeset that closed it?

**Comment by CIPop** [comment]
Thanks @laskoviymishka! 

> Just from curiosity could you please point me to changeset that closed it?

@davidsh or @stephentoub might be able to answer although a lot of changes were made to the implementation since RC2.

**Comment by laskoviymishka** [comment]
@CIPop may be class / classes 🎯. Anyway thanks to you too. This issue was quite noisy for me.

**Comment by CIPop** [comment]
Glad I was able to help!

The most likely component to cause the issue would be `System.Net.Http.WinHttpHandler` although, based on other discoveries made during my perf investigations, it might have been a configuration issue, a runtime issue (the incorrect version of System.Net.Http implementation might have been selected), or even a Task/ThreadPool problem (see other issues I've referenced).

**Comment by CIPop** [comment]
> @davidfowl @Tratcher PTAL There is a substantial drop in performance (>35%) when running against the ASP.Net core server using dotnet run

This is being investigated in https://github.com/aspnet/Performance/issues/182

**Comment by Ponant** [comment]
@stephentoub , is there any objection if we configure the HttpClient as AddSingleton in Startup instead of a static in a controller? Cheers

**Comment by stephentoub** [comment]
> is there any objection if we configure the HttpClient as AddSingleton in Startup instead of a static in a controller? Cheers

That's effectively the same thing, is it not?  You end up with a single instance that'll be used for all requests?  Unless I'm missing something, sounds fine.

**Comment by Ponant** [comment]
It should be the same indeed, but I had a doubt owing to the docs which made some unclear statements (to me at least) about recommendation in DI, here https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection#recommendations .
Besides this, although not mandatory, you would use an interface for the DI, e.g. `AddSingleton(IMyInterface, MyClass)`; what would be the interface for HttpClient? cheers

**Comment by Tratcher** [comment]
The use of interfaces is just a recommended pattern, not a functional requirement. You can just specify the type as HttpClient.
