### ISSUE TITLE
Lots of "CoreRun.exe" not found issues during CI

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#8815]
I noticed when looking at a test results lots of errors like
```
14:16:22   System.AppContext -> /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/bin/ref/System.AppContext/4.1.0.0/System.AppContext.dll
14:16:25   /bin/sh: 3: /tmp/tmpe981cd0cc1d24e4dbb12e5d80b2be7eb.exec.cmd: /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/Tools/CoreRun.exe: not found
```

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug_prtest/1490/consoleFull
This one, for example, has 319 of these messages.  I can't quite tell if this means that the tests aren't running or if it is innocuous.

@MattGal is this related to your test runner work?
I'm guessing this is coming from https://github.com/dotnet/buildtools/commit/6a824644b18126db086065175226f3f5dd6b4ed8

/cc @weshaggard @joperezr in case they have any ideas.  I see Joe previously made a change to tool-runtime to copy corerun to corerun.exe.

**Comment by joperezr** [comment]
the reason why I copied corerun to corerun.exe in the tool-runtime was because the csc msbuild task didn't have the support for changing the host of csc, so it always tried to use CoreRun.exe even when running in non-Windows. To work around it, I simply copied the file and renamed it to corerun.exe which worked, but I wonder how come this wasn't needed on the tests before and it is now.

**Comment by joperezr** [comment]
@MattGal [these lines](https://github.com/dotnet/buildtools/commit/6a824644b18126db086065175226f3f5dd6b4ed8#diff-425cb0dcf83ca9680e4a736c021dabe8L35) in particular look suspicious to me. I'm not sure we took into account the OS when we did this change.

**Comment by ellismg** [comment]
This is not due to Matt's change, it's due to the API Compat stuff. From the build log:

```
    28>ValidateApiCompatForSrc:
         "/home/matell/git/corefx/Tools/CoreRun.exe" "/home/matell/git/corefx/Tools/ApiCompat.exe" "/home/matell/git/corefx/bin/ref/System.Collections.Concurrent/4.0.10.0/\
System.Collections.Concurrent.dll"  -contractDepends:"/home/matell/git/corefx/packages/System.Runtime/4.0.0/ref/dotnet/;/home/matell/git/corefx/packages/System.Threading.T\
asks/4.0.0/ref/dotnet/;" -implDirs:"/home/matell/git/corefx/bin/obj/AnyOS.AnyCPU.Debug/System.Collections.Concurrent/;/home/matell/git/corefx/packages/System.Collections/4\
.0.10/ref/dotnet/;/home/matell/git/corefx/packages/System.Diagnostics.Contracts/4.0.0/ref/dotnet/;/home/matell/git/corefx/packages/System.Diagnostics.Debug/4.0.10/ref/dotn\
et/;/home/matell/git/corefx/packages/System.Diagnostics.Tools/4.0.0/ref/dotnet/;/home/matell/git/corefx/packages/System.Diagnostics.Tracing/4.0.20/ref/dotnet/;/home/matell\
/git/corefx/packages/System.Globalization/4.0.10/ref/dotnet/;/home/matell/git/corefx/packages/System.IO/4.0.0/ref/dotnet/;/home/matell/git/corefx/packages/System.Reflectio\
n/4.0.10/ref/dotnet/;/home/matell/git/corefx/packages/System.Reflection.Primitives/4.0.0/ref/dotnet/;/home/matell/git/corefx/packages/System.Resources.ResourceManager/4.0.\
0/ref/dotnet/;/home/matell/git/corefx/packages/System.Runtime/4.0.20/ref/dotnet/;/home/matell/git/corefx/packages/System.Runtime.Extensions/4.0.10/ref/dotnet/;/home/matell\
/git/corefx/packages/System.Text.Encoding/4.0.0/ref/dotnet/;/home/matell/git/corefx/packages/System.Threading/4.0.10/ref/dotnet/;/home/matell/git/corefx/packages/System.Th\
reading.Tasks/4.0.10/ref/dotnet/;"
         /bin/sh: 3: /tmp/tmpaa2445e5c493435896a968005c3ea597.exec.cmd: /home/matell/git/corefx/Tools/CoreRun.exe: not found
```

[This line](https://github.com/dotnet/buildtools/blob/79338bcec4db7e2e86f81c5c5e5505212cbee62f/src/Microsoft.DotNet.Build.Tasks/PackageFiles/ApiCompat.targets#L47) needs to be conditioned to be "corerun" on Unix, I think (or we just need to fix the casing to be in all lowercase, but I'd rather not keep this corerun.exe hack around long term if we don't need it).

@weshaggard

**Comment by ericstj** [comment]
Apologies for calling out @MattGal here.  Wes, can you fix this up?  I think this means folks aren't running APICompat on Unix, right?

**Comment by ellismg** [comment]
I am working on validating a fix.

**Comment by weshaggard** [comment]
Thanks for fixing @ellismg, sorry I didn't fix this earlier. In https://github.com/dotnet/buildtools/pull/721 I even saw this error but I never got back around to digging in to repro it and understand (I really want to setup an ubunto docker image so I can repro these things).

**Comment by ellismg** [comment]
The fix has landed in BuildTools.  I will update the tools we use tomorrow to pick it up.
