### ISSUE TITLE
WinHttpRequestState memory leak when cancelling requests

### ISSUE THREAD

**Issue by davidsh** [dotnet/corefx#8819]
(reported by ASP.NET team).
cc: @DavidObando 

There is a memory leak of WinHttpRequestState (and related objects) when the outstanding http request is canceled prior to it completing with an HttpResponseMessage.

**Comment by davidsh** [comment]
After analyzing this, the size of the WinHttpRequestState memory leaks are orders of magnitude smaller than the memory fragmentation caused by issues in the Kestrel server.

Moving to post RTM.

**Comment by DavidObando** [comment]
@davidsh that's true as long as the cancellation token is freed.

**Comment by davidsh** [comment]
>that's true as long as the cancellation token is freed.

I will submit a PR for RTM to fix just that. This issue, though, will cover the overall problem which still isn't 100% fixed.

**Comment by davidsh** [comment]
Switching this issue to RTM for now until #8896 gets merged. Then the issue will move to post RTM to fix the remaining leaks.

**Comment by karelz** [comment]
Check out more details in closed dupe #11674.

**Comment by karelz** [comment]
Next step:
* Run again the repro to see if there is anything left (it was at least partially mitigated by other changes

**Comment by karelz** [comment]
Triage: The impact on 2.0 is expected to be low if any. The cost is high, moving to Future.

**Comment by karelz** [comment]
Should be addressed in 2.1 with new default handler: SocketsHttpHandler, closing.
