### ISSUE TITLE
RC2 issues: Unit Test Project with Target Framework 4.6.1

### ISSUE THREAD

**Issue by gimlichael** [dotnet/corefx#8822]
I have setup a range of `Unit Test` projects that has the target framework set to `.NET Framework 4.6.1`.

Before the release of .NET Core RC2, I was able to fully test my .NET Core assemblies that targeted the `.NETPlatform 5.4`; no problems at all (except some NuGet reference complains now and then, but manageable).

After the release of RC2, my assemblies went from `.NETPlatform 5.4` to `.NETStandard 1.4` that, according to this link, [https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md](url), is supported by `.NET Framework 4.6.1`.

However, when trying to add assemblies through NuGet, I get this error:

`Severity	Code	Description	Project	File	Line
Error		Could not install package 'Microsoft.NETCore.Targets 1.0.1-rc2-24027'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0
`

Am I doing something wrong? Again, it works perfectly with my NuGet packages targeting the `.NETPlatform 5.4`, but not `.NETStandard 1.4`. I am getting a little despaired.

**Comment by ericstj** [comment]
Looks like NuGet+packages.config isn't happy about seeing a package with only a runtime.json.  I suspect if you switched your net461 project to use project.json it would fix this.

We'll need to add a dummy directory to the package to make NuGet+packages.config happy with this.

**Comment by gimlichael** [comment]
I am still a rookie here on GitHub; I can understand the bug has been located and I am guessing fixed with #8929. When will the fix be published for the public hence making it available for me to test? Keep up the great work, guys!

**Comment by ericstj** [comment]
You can find updated packages using https://myget.org/gallery/dotnet-core
The RC4 version of the packages was fixed with this commit.  RC3 will be updated shortly.
