### ISSUE TITLE
Updating versions of externalpackages in pkg\ExternalPackages\versions.props

### ISSUE THREAD

**Issue by chcosta** [dotnet/corefx#8835]
This PR, https://github.com/dotnet/corefx/pull/8824, is introducing pkg\ExternalPackages\versions.props which we are using to determine version numbers for external packages (System.IO.Compression for example).  

We need some method (similar to UpdatePackageDependencyVersion), so that we can keep this file up to date w.r.t. the latest stable package version for these packages (perhaps making use of the versions repo).  Until that is done, we'll have to be diligent about manually updating this file. :(

/cc @jhendrixMSFT @weshaggard 

@jhendrixMSFT , assigning to you for tracking at the moment...

**Comment by weshaggard** [comment]
Fixed by https://github.com/dotnet/corefx/commit/329de5ea298885637d01ae85186a42436a375b8b which now uses the properties we use for validation and get updated when we do our updates.
