### ISSUE TITLE
System.Diagnostics.StackTrace depends on 1.3.0 version of System.Reflection.Metadata

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#8836]
When @nguerrera downversioned the System.Reflection.Metadata in the release branch, we did not update System.Diagnostics.StackTrace's project.json to compile against the old version.

Doing this is not straight forward as we depend on some surface area that was made internal, but we need to come up with a fix here before RTM.

**Comment by nguerrera** [comment]
Working on this. The MetadataReaderProvider API is really handy and scoped. I'll work to get it approved by FXDC and bump the version back to 1.3. This will also unblock some logistic problems with the change in version from 1.3 to 1.2.1. 

cc @eerhardt

**Comment by nguerrera** [comment]
Fixed by #8850

**Comment by ellismg** [comment]
Thanks for the quick turn around, Nick.
