### ISSUE TITLE
Stop pulling live CoreCLR

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#8841]
We've been hitting issues left and right recently because some of our jobs pull live CoreCLR bits and that breaks us.  We've hit issues due to the mscorlib rename, changes that expose test issues, and the inability to get a consistent mscorlib/coreclr pair because of how we pull from jobs.

Windows, OSX and Ubuntu 14.04 consume CoreCLR from packages.  It's time that we do the same for the other distros.

If we are concerned about trying to get an early read on if CoreCLR changes are going to break CoreFX, there should be tests in CoreCLR that use a LKG test drop and run with a live CoreCLR.

**Comment by ellismg** [comment]
@stephentoub I know in the past you've been wary of this.  It feels like I've fixed multiple issues over the past few days that are root caused to us picking up live CoreCLRs.  It's even worse because this impacts every PR.

Thoughts?

**Comment by stephentoub** [comment]
> If we are concerned about trying to get an early read on if CoreCLR changes are going to break CoreFx

This is my primary concern here.  While it's frustrating when we've had legs broken, many of those breaks have actually been real product issues, and it's much easier to root-cause them when you can narrow down the window to one or just a few commits within a particular and small time window.  If such breaks occurred at a time (like now) when we've not updated which coreclr package we use for a week, determining the cause of such a failure would be a much bigger challenge.

If we wanted to instead have a set of corefx legs run in coreclr on every coreclr merge to master, I'd be fine with that.

**Comment by gkhanna79** [comment]
> If we wanted to instead have a set of corefx legs run in coreclr on every coreclr merge to master, I'd be fine with that.

I concur with this.

**Comment by gkhanna79** [comment]
We should also have a way to make a CoreFX build target a private CoreCLR build on a dev box (assumption is that dev can build the master of CoreFX and point it to their private CoreCLR binaries). This will help identify issues even before CI is hit.

**Comment by ellismg** [comment]
> We should also have a way to make a CoreFX build target a private CoreCLR build on a dev box (assumption is that dev can build the master of CoreFX and point it to their private CoreCLR binaries). This will help identify issues even before CI is hit.

Once https://github.com/dotnet/buildtools/pull/753 is merged and we update our builds tools we will support this again.

**Comment by mellinoe** [comment]
Unless I'm misunderstanding the topic, we are already doing this for all distros that we run tests on. CoreCLR is pulled from packages.
