### ISSUE TITLE
ECDsaCng doesn't work on Red Hat

### ISSUE THREAD

**Issue by erikzhang** [dotnet/corefx#8843]
When I use ECDsaCng on Red Hat, it throws a PlatformNotSupportedException.

**Comment by vcsjones** [comment]
That's expected. *Cng classes only work on Windows. You likely want to use ECDsaOpenSsl depending on what you're trying to do.

**Comment by erikzhang** [comment]
Is there anything such as ECDsa.Create() to create ECDsa in any platforms?
Otherwise I have to use conditional compilation, which is uncomfortable.

**Comment by vcsjones** [comment]
It looks like there will be eventually: https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/ECDsa.cs#L13

But currently it throws a NotImplementedException and is marked "todo". /cc @bartonjs

**Comment by erikzhang** [comment]
Great!
Another question, is there any way to import/export keys to/from ECDsaOpenSsl?

**Comment by bartonjs** [comment]
If you're looking at RC2, ECDSA is effectively only supported via X509Certificate2.GetECDsaPublicKey() and GetECDsaPrivateKey().

For RTM, ECC Import/Export was added last week; and the ECDsa.Create methods should be getting implementations today.

But, like @vcsjones said, the \*Cng types are Windows-only; so I'm going to close the issue (though feel free to keep asking questions on it).

**Comment by erikzhang** [comment]
So the only thing I need to do is wait for RTM.
Thank you very much!

**Comment by vcsjones** [comment]
You could *probably* grab nightlies from the MyGet feeds once this is implemented if you're eager to try things out. That's my plan, at least.
