### ISSUE TITLE
EqualityComparer<T>.Default, IEquatable<T>  and boxing

### ISSUE THREAD

**Issue by omariom** [dotnet/corefx#8844]
The implementation of [EqualityComparer<T>.Default](https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/EqualityComparer.cs#L31) makes me think that calling innocent `ContainsKey` of `Dictionary` will produce garbage even for value types that designed to be good keys (override `GetHashCode`, `Equals` and implement `IEquatable<T>`),   because the default comparer for all types (except `sbyte, byte, short, ushort, int, uint, long, ulong, IntPtr, UIntPtr, float, double, decimal` - quite narrow list by itself!) doesn't take advantage of `IEquatable<T>`.

Is it unavoidable?

**Comment by benaadams** [comment]
Looks like the comment relates to a non-jit environment? https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/EqualityComparer.cs#L116-L119

> ProjectN compatibility notes:
>
> Unlike the full desktop, we make no attempt to use the IEquatable<T> interface on T. Because we can't generate code at runtime, we derive no performance benefit from using the type-specific Equals(). We can't even perform the check for IEquatable<> at the time the type-specific constructor is created (due to the removable of Type.IsAssignableFrom). We would thus be incurring an interface cast check on each call to Equals() for no performance gain.

**Comment by omariom** [comment]
Yes, but it will influence non AOT environments.

**Comment by stephentoub** [comment]
> Yes, but it influences non AOT environments, isn't?

The code you linked to is only used with .NET Native.  The ```EqualityComparer<T>``` implementation used with coreclr is in mscorlib in the coreclr repo.

**Comment by omariom** [comment]
Aha! 

But does it mean to avoid boxing in   .NET Native we have to provide a type specific implementation of 'IEqialityComparer' to dictionaries?

**Comment by stephentoub** [comment]
With the current implementation, it would appear that way. @jkotas may know if any special tricks are played to avoid that.

**Comment by jkotas** [comment]
The C# code that you see here is not what actually runs in UWP apps. .NET Native for UWP toolchain inserts a different implementation using intrinsics. https://github.com/dotnet/corert/issues/763 tracks implementing this optimization in the CoreRT toolchain as well.
