### ISSUE TITLE
LinQ GroupBy fails with TResult

### ISSUE THREAD

**Issue by glatzert** [dotnet/corefx#8848]
I have the following Linq Expression (after loading elements from the database):

```C#
var result = memberships.GroupBy(
    m => m.Role,
    (role, ms) => new RoleUsage
    {
        Role = role,
        MemberCount = ms.Count(m => m.StructuralUnitId == query.StructuralUnitId),
        InheritedMemberCount = ms.Count(m => m.StructuralUnitId != query.StructuralUnitId)
    }).ToList();
```
Where `memberships` is a `List<Membership>` of *non null* `Membership` instances.
`Role` and `Membership` are simple classes.

Running that Linq will fail with a NullReferenceException in the inner `Count(m => m..)` Expression, since `m` is `null`.

We first thought, it would have to do with EF, which loads the `Memberships`, but it's not the case.
Appearantly somewhere in Linqs GroupBy something goes wrong, since pointing with the Debugger on `ms` states Powers of 2 in elemt Count, with lots of empty entries.

Further Investigation leads to `corefx / src / System.Linq / src / System / Linq / Lookup.cs ` and especially `ApplyResultSelector` (Line 240), which applies the result selector to the Elemtents of a Grouping. Unfortunately that `_elements` (Line 253) appearantly contains null entries, which should not be present.

**Comment by glatzert** [comment]
Here is the full Repro

```C#
sing System.Collections.Generic;
using System.Linq;
using Xunit;

namespace LinqError
{
    public class LinqGroupByTest
    {
        [Fact]
        public void RunTest()
        {
            //Create test data
            var roles = new List<Role>()
            {
                new Role { Id = 1 },
                new Role { Id = 2 },
                new Role { Id = 3 },
            };

            var memberships = Enumerable.Range(0, 5000).Select(i => new Membership
            {
                Id = i,
                Role = roles[i % 3],
                CountMe = i % 3 == 0
            }).ToList();

            //Run actual test
            var result = memberships.GroupBy(
                m => m.Role,
                (role, mems) => new RoleMetadata
                {
                    Role = role,
                    CountA = mems.Count(m => m.CountMe),
                    CountrB = mems.Count(m => !m.CountMe)
                }).ToList();
        }
    }

    public class Membership
    {
        public int Id { get; set; }
        public Role Role { get; set; }

        public bool CountMe { get; set; }
    }

    public class Role
    {
        public int Id { get; set; }
    }

    public class RoleMetadata
    {
        public Role Role { get; set; }
        public int CountA { get; set; }
        public int CountrB { get; set; }
    }
}

```

**Comment by JonHanna** [comment]
It's actually that `ApplyResultSelector()` was bypassed and the optimised `ToList()` that bypassed it didn't trim extraneous elements as `ApplyResultSelector()` does.

If you need a workaround before the fix is applied, use:

```C#
var result = new List<RoleMetadata>(memberships.GroupBy(
    m => m.Role,
    (role, mems) => new RoleMetadata
    {
        Role = role,
        CountA = mems.Count(m => m.CountMe),
        CountrB = mems.Count(m => !m.CountMe)
    }));
```

That of course won't work with anonymous types, though a helper method that provides an the same effect can be used.

**Comment by JonHanna** [comment]
@joshfree strictly this should be under System.Linq rather than System.Linq.Expressions.

**Comment by jamesqo** [comment]
Just came across this. I wonder if it wouldn't be better to invoke the result selector with `g` instead of its array-- would prevent someone from casting to `TElement[]` within the selector and violating Grouping's immutability-after-creation. Plus, we wouldn't need to have these expensive resizes.
