### ISSUE TITLE
Remove explicit version number requirement for project references

### ISSUE THREAD

**Issue by girish-a** [dotnet/corefx#8849]
Prior to rc2, we could refer to another project without specifying a version number. But now, it looks like the version number requirement is enforced. See the following StackOverflow link:

http://stackoverflow.com/questions/37438833/net-core-rc2-package-dependencies-are-not-resolved/37439188?noredirect=1#comment62381252_37439188

Wouldn't it be simpler to remove the version number requirement for project references?

**Comment by mellinoe** [comment]
You don't need to specify version. Just use:

````json
"dependencies": {
  "project-name": { "target": "project" }
}
````

**Comment by ericstj** [comment]
Closing this.  If you have further questions please re-open the issue in the dotnet/CLI repo.
