### ISSUE TITLE
Regression  threading.NamedMutex.test1 (from (empty))

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#8857]
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/release_1.0.0/job/debug_centos7.1_prtest/11/testReport/junit/threading/NamedMutex/test1/

Stacktrace

MESSAGE:
'paltest_namedmutex_test1' failed at line 355. Expression: m != nullptr 'paltest_namedmutex_test1' failed at line 421. Expression: WriteHeaderInfo(BuildGlobalShmFilePath(name, NamePrefix), -1, 0, &fd) 'paltest_namedmutex_test1' failed at line 502. Expression: m != nullptr 'paltest_namedmutex_test1' failed at line 607. Expression: m != nullptr 'paltest_namedmutex_test1' failed at line 248. Expression: parentEvents[i] != nullptr 'paltest_namedmutex_test1' failed at line 629. Expression: InitializeParent(parentEvents, childEvents) 'paltest_namedmutex_test1' failed at line 761. Expression: AbandonTests_Parent() 'paltest_namedmutex_test1' failed at line 234. Expression: WaitForSingleObject(childRunningEvent, FailTimeoutMilliseconds) == WAIT_OBJECT_0 'paltest_namedmutex_test1' failed at line 280. Expression: AcquireChildRunningEvent(childRunningEvent) 'paltest_namedmutex_test1' failed at line 675. Expression: InitializeChild(childRunningEvent, parentEvents, childEvents)
+++++++++++++++++++
STACK TRACE:

**Comment by joshfree** [comment]
cc: @sergiy-k

**Comment by kouvel** [comment]
The permissions on /tmp/.dotnet folder are incorrect. Probably it was created before the permissions issue was fixed in CoreFX. I have fixed it manually on this machine, but try to look at the image as well and see if there's an inherent issue there.

**Comment by joshfree** [comment]
Note that this is from the /coreclr/release/1.0.0 branch.

**Comment by kouvel** [comment]
This is a machine config issue with leftover invalid state from before. It should be fixed now, at least on that machine. Shouldn't matter which branch.

**Comment by kouvel** [comment]
Looks like the image is fine, so it must have just been that the machine hadn't gotten reset yet. Please let me know if this happens again on other jobs, it's possible that there are more CI machines with this invalid state, I can fix them manually.
