### ISSUE TITLE
Update CI to use dotnet cli to build Ubuntu16.04

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#8860]
This is a tracking bug, to ensure using dotnet cli packages once available. dotnet/cli#2957

cc @joshfree

**Comment by joshfree** [comment]
I believe this should now be unblocked. @livarcocc which build should @Priya91 pick up?

**Comment by ellismg** [comment]
init-tools.sh and build.sh in the root should work on all supported distros (I manually published builds and once @livarcocc's changes land we will get real builds going forward) so this should be unblocked now.

We should be able to cut over to building everything on Linux for Ubuntu 16.04 based on what's in master today.
