### ISSUE TITLE
Environment.StackTrace throws BadImageFormatException 

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#8866]
From: https://github.com/dotnet/corefx/pull/8842

This appears to be a regression from the recent StackTrace/symbol work.

To repro clone the branch mentioned in above PR, and build the System.Net.Http.WinHttpHandler\tests\unittests directory with /t:BuildAndTest.

For now I'm disabling the code that is triggering this failure during test.  Please re-enable after StackTrace is fixed and the fixed packages are being consumed by the tests.

**Comment by mikem8361** [comment]
The PR for this fix is in coreclr: https://github.com/dotnet/coreclr/pull/5265
