### ISSUE TITLE
Regression - 10 CharTests failures in CI

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#8869]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_release_tst/490/consoleFull#-21371504001f1a4601-6aec-4fd5-b678-78d4389fd5e8

16:33:59    System.Tests.CharTests.IsNumber_String_Int [FAIL]
16:33:59       Assert.False() Failure
16:33:59       Expected: False
16:33:59       Actual:   True
16:33:59       Stack Trace:
16:34:00             at System.Tests.CharTests.IsNumber_String_Int()
16:34:00    System.Tests.CharTests.IsLower_String_Int [FAIL]
16:34:00       Assert.False() Failure
16:34:00       Expected: False
16:34:00       Actual:   True
16:34:00       Stack Trace:
16:34:00             at System.Tests.CharTests.IsLower_String_Int()
16:34:00    System.Tests.CharTests.IsLower_Char [FAIL]
16:34:00       Assert.False() Failure
16:34:00       Expected: False
16:34:00       Actual:   True
16:34:00       Stack Trace:
16:34:00             at System.Tests.CharTests.IsLower_Char()
16:34:00    System.Tests.CharTests.IsNumber_Char [FAIL]
16:34:00       Assert.False() Failure
16:34:00       Expected: False
16:34:00       Actual:   True
16:34:00       Stack Trace:
16:34:00             at System.Tests.CharTests.IsNumber_Char()
16:34:00    System.Tests.CharTests.IsDigit_Char [FAIL]
16:34:00       Assert.False() Failure
16:34:00       Expected: False
16:34:00       Actual:   True
16:34:00       Stack Trace:
16:34:00             at System.Tests.CharTests.IsDigit_Char()
16:34:00    System.Tests.CharTests.IsLetter_String_Int [FAIL]
16:34:00       Assert.False() Failure
16:34:00       Expected: False
16:34:00       Actual:   True
16:34:00       Stack Trace:
16:34:00             at System.Tests.CharTests.IsLetter_String_Int()
16:34:00    System.Tests.CharTests.IsLetterOrDigit_Char [FAIL]
16:34:00       Assert.False() Failure
16:34:00       Expected: False
16:34:00       Actual:   True
16:34:00       Stack Trace:
16:34:00             at System.Tests.CharTests.IsLetterOrDigit_Char()
16:34:00    System.Tests.CharTests.IsLetterOrDigit_String_Int [FAIL]
16:34:00       Assert.False() Failure
16:34:00       Expected: False
16:34:00       Actual:   True
16:34:00       Stack Trace:
16:34:00             at System.Tests.CharTests.IsLetterOrDigit_String_Int()
16:34:00    System.Tests.CharTests.IsDigit_String_Int [FAIL]
16:34:00       Assert.False() Failure
16:34:00       Expected: False
16:34:00       Actual:   True
16:34:00       Stack Trace:
16:34:00             at System.Tests.CharTests.IsDigit_String_Int()
16:34:00    System.Tests.CharTests.IsLetter_Char [FAIL]
16:34:00       Assert.False() Failure
16:34:00       Expected: False
16:34:00       Actual:   True
16:34:00       Stack Trace:
16:34:00             at System.Tests.CharTests.IsLetter_Char()
16:34:01 Finished:    System.Runtime.Tests
16:34:01 
16:34:01 === TEST EXECUTION SUMMARY ===
16:34:01    System.Runtime.Tests  Total: 5757, Errors: 0, Failed: 10, Skipped: 0, Time: 2.846s
16:34:01 Finished running tests. End time=23:34:38. Return value was 10

**Comment by joshfree** [comment]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/debian8.2_debug_tst/482/consoleFull#-21371504001f1a4601-6aec-4fd5-b678-78d4389fd5e8

Appears to be all distros.

**Comment by tarekgh** [comment]
this should be fixed by https://github.com/dotnet/corefx/pull/8873
