### ISSUE TITLE
Code coverage broken recently

### ISSUE THREAD

**Issue by hughbe** [dotnet/corefx#8880]
Code coverage doesn't seem to be working anymore (I think after dnxcore50 -> netcoreapp1.0).

## Steps to reproduce
- Clone the repo
- Initialize build tools
- Navigate to a test project (e.g. System.Collections.NonGeneric)
- Run `msbuild /T:BuildAndTest /P:Coverage=true`

## Expected
- ~100% code coverage

## Actual
- 0% code coverage reported
![untitled](https://cloud.githubusercontent.com/assets/1275900/15567682/8c1a36a8-231f-11e6-836f-fc9f79f85cfd.png)

/cc @ericstj

**Comment by stephentoub** [comment]
Note that this isn't just when building locally or when building an individual project.  Our code coverage reports are all showing as 0% coverage. 😦

**Comment by stephentoub** [comment]
@sawilde, does OpenCover have a hard dependency on mscorlib.dll being named "mscorlib"?  The core library has been renamed for .NET Core from "mscorlib" to "System.Private.Corelib", and I'm wondering if that change explains why OpenCover is reporting 0 hits on everything.

**Comment by joshfree** [comment]
Moving this to 1.1.0.  We can fix this in master and then look to port the changes back to 1.0.0, possibly during a servicing event or other related branch maintenance.

**Comment by sawilde** [comment]
@stephentoub - Alas yes - the cuckoos attach to `System.CannotUnloadAppDomainException` which it looks for when mscorlib is loaded. 

I suspect the change is easy - see https://github.com/OpenCover/opencover/blob/0f406744660456ec67e4aa3a6d77d2e28a8788ee/main/OpenCover.Profiler/CodeCoverage_Cuckoo.cpp#L221 - but it depends where you keep that class in your new scheme.

You could try the `-oldstyle` switch - see [Usage](https://github.com/OpenCover/opencover/wiki/Usage) but you may have other issues especially around partial trust scenarios.

**Comment by stephentoub** [comment]
Thanks, @sawilde. I'll give that a try.

**Comment by stephentoub** [comment]
Thanks, @sawilde. The ```-oldStyle``` workaround appears to have unblocked us.

**Comment by sawilde** [comment]
I am so glad I didn't delete that code 3 years ago :)

**Comment by stephentoub** [comment]
> I am so glad I didn't delete that code 3 years ago :)

Hah :) Me, too.
