### ISSUE TITLE
Enable ApiCompat on Linux

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#8899]
I am disabling this because it is broken presently and the breaks will cause problems when MSBuild actually starts to catch them.

We need to fix up the problems (there are some file casing issues that need to be tracked down).

**Comment by mellinoe** [comment]
I'm fixing this. It looks like two files have the wrong casing:

https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Cng/src/ApiCompatBaseLine.net463.txt

https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Algorithms/src/ApiCompatBaseLine.net463.txt

Base**Line**.txt vs. Baseline.txt

**Comment by karelz** [comment]
Fixed by #13600.
