### ISSUE TITLE
Question: Is there any way to get all types from all loaded assemblies?

### ISSUE THREAD

**Issue by Tasteful** [dotnet/corefx#8910]
Hi.

In our solution we are during startup scanning all loaded assemblies (AppDomain.CurrentDomain.GetAssemblies()) and fetching all types and depend on custom attributes register the classes in different factories and/or ServiceProvider. When I tried to use netstandard as TFM I didn't find a way to get the assembly. I was trying with the DependencyContext that I found in some other issue that was possible to use to find all dependencies. Does it exists any simplier way to get the loaded assemblies then check all dependencies from DependencyContext and manually load them?

**Comment by svick** [comment]
Related: #8806

**Comment by danmosemsft** [comment]
AppDomain.GetAssemblies is tracked by https://github.com/dotnet/corefx/issues/9327
