### ISSUE TITLE
FileExtensionsAttribute always says invalid

### ISSUE THREAD

**Issue by Angelixion** [dotnet/corefx#8913]
Hello, i have a property that the model always says is invalid, i have tried to not put any extensions only with `[FileExtensions]` but doesnt work,  only works if i dont put the attribute, what i have is this.

```
[FileExtensions(Extensions = "png")]
public IFormFile Property { get; set; }
```

**Comment by hughbe** [comment]
Your issue is that FileExtensionAttribute considers any non-string value as invalid. 
An IFormFile cannot be a string, so is always invalid.
See the implementation (here)[https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/FileExtensionsAttribute.cs#L57] for more

**Comment by Angelixion** [comment]
The how i can use the FileExtensionAttribute to check an IFormFile?, and why it says FileExtensionAttribute if it doesnt check files but strings?

**Comment by hughbe** [comment]
@Angelixion 
The way that you use FileExtensionsAttribute only works on **file names** as demonstrated:
```
FileExtensionsAttrbibute attribute = new FileExtensionsAttribute() { Extensions = "png" };
attribute.IsValid("file.png"); // true
attribute.IsValid("file.anyotherextensions"); // false
```

I have no idea what IFormFile is/looks like - I suggest asking on stackoverflow.com for that

**Comment by divega** [comment]
Data Annotations Triage: At first glance this looks like an interesting request, but making it work would require more work on ASP.NET Core (maintained in http://www.github.com/aspnet/home/) than in the data annotation itself. Data annotations cannot take a dependency on Microsoft.AspNetCore.Http to make it work so the "protocol" between the attribute and `IFormFile` would need to use some other convention. 

Our recommendation is to create a new issue in ASP.NET Core.

cc @danroth27 @DamianEdwards
