### ISSUE TITLE
Add mono detection to RuntimeInformation

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/corefx#8920]
Currently the RuntimeInformation class has a FrameworkDescription which will display `.NET Framework 4.0.0.0` on Mono. There should be a different value for Mono so that is easier to tell if you are running on Mono

**Comment by AlexGhiondea** [comment]
@Priya91 is this something we still want to do in 1.2?

**Comment by Priya91** [comment]
@BrennanConroy This is implemented in Mono, executing ```RuntimeInformation.FrameworkDescription``` on Mono runtime gives this output:

```
FrameworkDescription=4.6.2 (Visual Studio built mono)
```

**Comment by Priya91** [comment]
Closing the issue, please reopen if there are additional requirements.
