### ISSUE TITLE
HttpClient not overwriting RequestURI after server redirect on non-Windows

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/corefx#8941]
Scenario:

1) Client sends GET to server, server sends 302 response.
2) Client sends GET to redirect location and completes the request but the RequestURI is not updated

Example:
```
1):
Request URL:http://localhost:5000/
Request Method:GET
Status Code:302 Found
Remote Address:127.0.0.1:5000
2):
Request URL:http://localhost:5000/hello
Request Method:GET
Status Code:200 OK
Remote Address:127.0.0.1:5000
```

The expected content of the `HttpResponseMessage` is: 
```
Response.RequestMessage:
Method: GET, RequestUri: 'http://localhost:5000/hello', Version: 1.1, Content: <null>, Headers:
{
}
Response:
Hello world
StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Date: Sat, 28 May 2016 02:18:13 GMT
  Transfer-Encoding: chunked
  Server: Kestrel
}
```
This is correct and what I see on Windows. But on Mac, (and most likely Linux too) I'm seeing:
```
Response.RequestMessage:
Method: GET, RequestUri: 'http://localhost:5000/', Version: 1.1, Content: <null>, Headers:
{
}
Response:
Hello world
StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Date: Sat, 28 May 2016 01:48:35 GMT
  Transfer-Encoding: chunked
  Server: Kestrel
}
```

I have a simple repro on https://github.com/JunTaoLuo/ServerRedirect. You can repro by running `dotnet restore` at the solution root, then running `dotnet run` in the ServerRedirect project followed by `dotnet run` in the Client project.

This is breaking one of some of our functional tests when I re-enabled them while trying to verify the fix for https://github.com/dotnet/corefx/issues/7440: 
https://github.com/aspnet/MusicStore/blob/dev/test/E2ETests/SmokeTests.cs#L103
https://github.com/aspnet/MusicStore/blob/dev/test/E2ETests/OpenIdConnectTests.cs#L41

I have been able to repro this on Mac and I suspect this will also affect Linux (I'll follow up when I try that on a Ubuntu machine).

cc @Tratcher @muratg @Eilon

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by stephentoub** [comment]
@JunTaoLuo, if you change your repro to use an absolute uri for the redirect rather than a relative one, do you still see this?

**Comment by JunTaoLuo** [comment]
@stephentoub How do I test out your fix in the linked PR? Will you build a package for me to test?

**Comment by JunTaoLuo** [comment]
@stephentoub The repro only works for relative redirects. Absolute redirects seems to work fine. Also, sorry for the spam on this issue, the previous comment was meant for the issue filed on our MusicStore repo.
