### ISSUE TITLE
WinHttpHandler off-by-1 in MaxAutomaticRedirections

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#8945]
It appears that WinHttpHandler has an off-by-1 error in its handling of MaxAutomaticRedirections.  When MaxAutomaticRedirections is set to N, it successfully follows N-1 redirects, but fails on the Nth, rather than successfully following N redirects and failing on the N+1th.

**Comment by davidsh** [comment]
This is a bug in native WinHTTP. I opened up a bug with the WinHTTP team. Bug number 7814885

**Comment by davidsh** [comment]
This has been fixed in Windows 10.  But the fix won't be available until the next public release of Windows 10 after the Anniversary Update.

**Comment by stephentoub** [comment]
I'm reopening this, as the test still needs to be re-enabled, and done so in a way that it'll either not run or pass on OSes without the fix.

**Comment by karelz** [comment]
Next step: We need scope the test to just Win10 Aniversary+
