### ISSUE TITLE
MaxAutomaticRedirections behavior difference between .NET Framework and .NET Core

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#8947]
Repro:

``` C#
using System;
using System.Net.Http;

class Program
{
    static void Main()
    {
        var c = new HttpClient(new HttpClientHandler { MaxAutomaticRedirections = 3 });
        Console.WriteLine(c.GetAsync("http://corefx-net.cloudapp.net/Redirect.ashx?statuscode=302&uri=%2FEcho.ashx&hops=4").GetAwaiter().GetResult().StatusCode);
    }
}
```

With the .NET Framework, this prints out "Redirect".

With .NET Core (both on Windows and on Unix), this throws an HttpRequestException due to exceeding the number of allowed redirects.

Is this behavioral change by design?

cc: @davidsh, @cipop

**Comment by davidsh** [comment]
This is due to the underlying stack differences.On Desktop, going beyond the max limit simply results in not following the final redirect.  So, the 3xx response is left.

On native Windows stack like WinHTTP, it generates an error.

**Comment by stephentoub** [comment]
So... the difference is by design and this should be closed?

**Comment by davidsh** [comment]
>So... the difference is by design and this should be closed?

This is not something we explicitly test. We didn't interntionally make it different.  It just happens to be different. I would need to research the native HTTP stack documentation to see what is the design behavior.

We also should consider the netcore50 (UWP) version which uses WinINet (and not WinHTTP).  It's possible it is different as well.

**Comment by davidsh** [comment]
I opened up a bug with the Windows native WinHTTP team about this.
Ref: 7814885

**Comment by karelz** [comment]
Next step:
* Add test (specific to Windows OS version - probably RS2)

**Comment by davidsh** [comment]
>I opened up a bug with the Windows native WinHTTP team about this.
Ref: 7814885

Turns out that this is not a WinHTTP bug.  That comment dealt with a different issue #8945.

This issue is a behavior difference between .NET Framework and .NET Core:

> This is due to the underlying stack differences.On Desktop, going beyond the max limit simply results in not following the final redirect. So, the 3xx response is left. On native Windows stack like WinHTTP, it generates an error.

**Comment by karelz** [comment]
Is it interesting for 2.0? If not why?

**Comment by davidsh** [comment]
>Is it interesting for 2.0? If not why?

I don't think this is critical for 2.0.  And it is not easily solvable since we can't change the behavior of the OS platform APIs (WinHTTP) that cause this behavior. We would have to write code to track redirection counts manually after disabling any OS redirection limits (assuming that can be done at all).

**Comment by Jiayili1** [comment]
@danmosemsft @safern which test need to be disabled for this issue?

**Comment by safern** [comment]
@davidsh @stephentoub do you know of any test running against Desktop hitting this issue so that we can disable them?

**Comment by davidsh** [comment]
>@davidsh @stephentoub do you know of any test running against Desktop hitting this issue so that we can disable them?

We might have tests for this already...but we're probably already skipping them on Desktop.

**Comment by stephentoub** [comment]
> do you know of any test running against Desktop

https://github.com/dotnet/corefx/blob/e9318bc16cffe22dbc5b384222ffc0445aff0240/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs#L523

**Comment by davidsh** [comment]
And we are already "skipping" the test on Full Framework:

```c#
            else if (PlatformDetection.IsFullFramework) 
            { 
                // Skip this test if running on .NET Framework. Exceeding max redirections will not throw 
                // exception. Instead, it simply returns the 3xx response. 
                _output.WriteLine("Skipping test on .NET Framework due to behavior difference."); 
                return; 
            } 
```

**Comment by safern** [comment]
So then there is no test that needs to be skipped related to this issue? Thanks for pointing out.

**Comment by davidsh** [comment]
PR #22702 changed the way that auto redirection is done on UWP.  So now the behavior on UWP matches .NET Framework which doesn't throw an exception when exceeding the max redirects. It simply doesn't follow the redirect and thus returns a 3xx response status code.

At this point, the current behavior is by-design.  I will update the AppCompat wiki https://github.com/dotnet/corefx/wiki/ApiCompat to document that .NET Core is different from .NET Framework and UWP.
