### ISSUE TITLE
Add an announcements repo for dotnet

### ISSUE THREAD

**Issue by aL3891** [dotnet/corefx#8948]
Hey there, 
The aspnet GitHub org has a special repo for announcements, it would be really useful to have that for the dotnet org as well, especially with the changes coming to the api surface and the fact that there is a very large amount of activity in the corefx repo, so its easy for announcements/calls for feedback to get lost. 

An announcement repo where you link to issues for discussion would be a great way to alleviate that

**Comment by karelz** [comment]
@leecow any update on this? cc @terrajobst

**Comment by terrajobst** [comment]
@aL3891 

I'm in complete agreement that we've provide more details on the API additions. Personally, I'm not convinced that an announcment repo is the most effective way to communicate these broad aspects. I'd rather use our blog and encourage team members to blog more. Issues in particular are fairly terrible for communication.

**Comment by aL3891** [comment]
@terrajobst  But they do provide a better platform for discussion, the asp.net repos typically have a discussion issue as well, but it gets lost in the sea of other issues. an announcement repo would also be a good way to collect feedback around issues as well by linking to another issue.

now you could ofcourse do that with blog posts as well, however there are a lot of Microsoft blogs, so in my view that would be less visible, atleast for people that spend a lot of time on GitHub. Asp.net does have both blogs and an announcement repo :) 

I don't mind blogs though as long as they happen, but sadly that doesn't seem to be the case, especially for more technical topics (details around the new build system for one, netstandard2 plans for another)

**Comment by danmosemsft** [comment]
@tarekgh I changed this to future

**Comment by tarekgh** [comment]
@leecow @terrajobst do we have any updates or plans to do it?

**Comment by leecow** [comment]
Yes, talking with a few folks on whether to spin up a new repo or utilize /core.

**Comment by karelz** [comment]
Should we move this bug to /core then?

**Comment by leecow** [comment]
@karelz - sounds fine.
