### ISSUE TITLE
Sync-blocking on threadpool threads

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#8949]
If there is a sync block on a threadpool thread `task.Wait()` etc; could it increment the threadpool min thread count by one? Then decrement by one on complete?

May or may not help with threadpool starvation in async-over-sync situations which seem to keep popping up.

**Comment by GSPP** [comment]
All kinds of built-in waits could be instrumented like this.

[The thread pool thread injection heuristics are sometimes very slow to inject threads.](https://github.com/dotnet/coreclr/issues/1754)

**Comment by kouvel** [comment]
Closing in favor of dotnet/coreclr#1754, will track this issue there
