### ISSUE TITLE
Console not echoing input on Mac OS X until enter is pressed

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#8950]
There appears to be a difference in behaviour with respect to echoing console input on at least .NET Core RC 2 on Mac OS X vs. .NET 4.6 on Windows. 

### Environment
* OS X El Capitan 10.11.4
* Bash config and inputrc (in case they matter): https://github.com/nguerrera/.dot
* .NET Core RC 2 installed following https://www.microsoft.com/net/core#macosx

### Repro steps

* Create project
```
$ mkdir repro
$ cd repro
$ dotnet new
$ dotnet restore
```

* Edit Program.cs to match:
``` C#
class Program {
    static void Main(string[] args) {
        System.Console.ReadLine();
    }
}
```

* Run:
```
$ dotnet run
```

* Wait for compilation to succeed and app to start up
* Start typing

### Expected result
Characters I type are echoed back to me as I type.

### Actual result
Characters are not shown to me until I hit enter.

@stephentoub @pallavit

**Comment by svick** [comment]
I think this is duplicate of dotnet/cli#2775, which should be already fixed (but it was fixed after RC2).

**Comment by nguerrera** [comment]
@svick. Yes. That's it. Thanks. Closing.
