### ISSUE TITLE
Microsoft.NETCore.Platforms doesn't install on packages.config based projects

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefx#8952]
PS: Feel free to close if by design, this is just an FYI

Packages that depend on Microsoft.NETCore.Platforms won't work on packages.config based projects. Here's the error:

Could not install package 'Microsoft.NETCore.Platforms 1.0.1-rc3-24127-00'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

/cc @ericstj

**Comment by ericstj** [comment]
This was already fixed.  https://github.com/dotnet/corefx/pull/8929
