### ISSUE TITLE
1.Nuget package restore failed for project tests\System.Data/Sqlclient.Manualtesting.Tests for 'test-runtime' 2.Unable to resolve test-runtime for .NETCoreApp, Version=v1.0

### ISSUE THREAD

**Issue by sravan1022** [dotnet/corefx#8963]
I am trying to build sqlclient (System.Data.SqlClient) from the source available from github. But i get these issues when i trying to build it. I tried uninstalled and re-installed nuget packet manager, still it doesn't solve the issue. What else i am missing ?

**Comment by ellismg** [comment]
How are you trying to build it?  from Visual Studio or from build.cmd or something else?

**Comment by sravan1022** [comment]
I am trying to build it from visual studio 2015

**Comment by sravan1022** [comment]
Here is how my error list looks like 
Severity	Code	Description	Project	File	Line	Suppression State
Error		NuGet Package restore failed for project  tests\System.Data.SqlClient.ManualTesting.Tests for 'test-runtime '.			0	
Error		Unable to resolve test-runtime  for .NETCoreApp,Version=v1.0.			0	
Error		Unable to resolve test-runtime  for .NETCoreApp,Version=v1.0.			0	
Error		NuGet Package restore failed for project tests\System.Data.SqlClient.Tests for 'test-runtime '.			0

**Comment by joperezr** [comment]
@sravan1022 some questions for you:

1. Did you run init-tools.cmd from the repo root before trying to open the project in VS?
2. Which version of Visual Studio are you running? VS 2015 Update 1 or higher?
3. I can see those errors on VS myself as well, but when I look in the Output window for Build, I see that the build actually succeeded despite of those "errors". Do you see this as well?

**Comment by joperezr** [comment]
I have a repro for this, and it is not corefx related. The Issue seems to be nugget extension in VS related. You can still build in VS and even though you see those errors in the error list, you'll see how the build output says that the build succeeded. I suggest we should open an issue in nuget's repo instead so that they can triage it.

**Comment by joperezr** [comment]
Closing this issue since I have copied the issue to NuGet/Home repo. @sravan1022 feel free to reopen or add more info to this issue if needed.
