### ISSUE TITLE
System.Runtime.Loader not working in webapp targeting 4.6.2 ?

### ISSUE THREAD

**Issue by leo9223** [dotnet/corefx#8965]
I am using System.Runtime.Loader in .NET Core app (net462) it doesn't give error at compile time but gives exception at run time "Could not load assembly System.Runtime.Loader".

I want to know System.Runtime.Loader is not working in 4.6.2 webapp?

**Comment by svick** [comment]
[System.Runtime.Loader is not supported on net462.](https://github.com/dotnet/corefx/issues/8526) If I understand it correctly, [it being able to be restored on net462 is a bug](https://github.com/dotnet/corefx/issues/8453).

**Comment by AlexGhiondea** [comment]
Closing this as S.R.Loader is not supposed to work on 4.6.2. See https://github.com/dotnet/corefx/issues/8526 for more information.

**Comment by raffaeler** [comment]
Sorry but how the assembly loading is supposed to work in netstandard1.5?
My app *must* either call the Assembly.LoadFrom or AssemblyLoadContext.Default.Loadxxx
The Assembly.Load cannot be used in my scenario.

I am not interested in calls specific to either netcore or netdesktop. The netstandard dll is "neutral" and should be able to do its job, right?

**Comment by jnevins-gcm** [comment]
Your nuget package SAYS it supports .NET 4.6.2. Additionally .NET 4.6.2 is supposed to be a superset of .NET Standard 1.5...in other words, something that targets.NET Standard 1.5 should be supported by 4.6.2. 

So, is your documentation on the package screwed up, is the package definition itself screwed up, or is there just more misinformation/bugs around the basic functioning of .NET Standard?

**Comment by evandixon** [comment]
The [latest NuGet package](https://www.nuget.org/api/v2/package/System.Runtime.Loader/4.3.0) only contains binaries for netstandard1.5 despite having entries for several other frameworks like net462 and variants of Xamarin

**Comment by ericstj** [comment]
Yeah, Loader isn't supported anywhere but coreclr.  It has a netstandard ref because that's the only way to represent surface area shared between more than one platform.  The package intentionally puts lib placeholders where it isn't supported to trigger NuGet's ref/lib compatibility check.

**Comment by SeanSnyders** [comment]
I'm also impacted by this.
I would like the 462 version of the `System.Runtime.Loader` package/library be an abstraction to the supported (existing, old-skool) 462 functionality such that I do not have to have two code paths to support a .Net 462 application and a .Net Core application.
