### ISSUE TITLE
All corefx tests failed on CentOS with "Infinite recursion during resource lookup" failure

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#8985]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_release_tst/523/consoleText
e.g.
```
Description: Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: NotSupported_WrongResourceReader_TypeCLR: Managed code called FailFast, saying "Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: NotSupported_WrongResourceReader_Type"
./RunTests.sh: line 208: 14383 Aborted                 ./corerun xunit.console.netcore.exe System.Composition.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests
Finished running tests. End time=15:05:07. Return value was 134
```
cc: @tarekgh, @gkhanna79

**Comment by gkhanna79** [comment]
@stephentoub Is this unique to CentOS?

**Comment by gkhanna79** [comment]
I am not aware of any ResourceManager changes to result in this.

**Comment by gkhanna79** [comment]
@stephentoub Which PR is failing? I see that https://github.com/dotnet/corefx/pull/8978 was clean.

**Comment by gkhanna79** [comment]
@tarekgh Can you please take an initial stab at this if this is unique to the PR or CoreFX infrastructure? Looking at http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_release_tst/, I see that all previous jobs were clean.

**Comment by stephentoub** [comment]
> Which PR is failing?

It wasn't a PR.  It was the main build.

> Is this unique to CentOS?

I only saw it on CentOS, but typically when that's happened it's that CentOS is serving as an early warning indicator because it's picking up the latest successful build from the coreclr repo.

**Comment by gkhanna79** [comment]
> it's that CentOS is serving as an early warning indicator because it's picking up the latest successful build from the coreclr repo.

Doesn't CoreFX CentOS build pickup daily build from CoreCLR?

**Comment by tarekgh** [comment]
CC @AlexGhiondea and @weshaggard this may be a side effect of introducing System.Private.Corelib.dll out of mscorlib.dll but I am not sure yet.

**Comment by gkhanna79** [comment]
System.Private.CoreLib.dll was introduced over 1.5 weeks ago and I believe CoreFX did consume that build.

**Comment by stephentoub** [comment]
> Doesn't CoreFX CentOS build pickup daily build from CoreCLR?

As I said, it currently picks up the *latest* successful build from coreclr.

This particular run could have been some kind of fluke, though that in and of itself would be a bit disconcerting.  I kicked off some more runs.  We can see if we see it again.

**Comment by gkhanna79** [comment]
> As I said, it currently picks up the latest successful build from coreclr.

Is there a way to figure out which CoreCLR build did CoreFX CentOS run consume?

**Comment by stephentoub** [comment]
> Is there a way to figure out which CoreCLR build did CoreFX CentOS run consume?

Yes.  When you look at the run in Jenkins:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_release_tst/523/consoleText
it shows at the top which it pulled in:
```
Copied 132 artifacts from "dotnet_coreclr » master » release_centos7.1" build number 913
```
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/release_centos7.1/913/

**Comment by tarekgh** [comment]
@stephentoub I am seeing the next build is succeeded

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_release_tst/524/

so it looks there was something wrong with the failed build

**Comment by bartonjs** [comment]
523 and 524 both used the same coreclr assets:

```
Copied 132 artifacts from "dotnet_coreclr » master » release_centos7.1" build number 913
```

In fact, they seem to think that they ran the exact same code (the followup build having been manually launched)... so something interesting must be going on.

**Comment by tarekgh** [comment]
ok, I am going to close this issue and if we hit it again we can dive more. I want to note that this is the second time I am seeing some random failure on Centos and then it just automatically disappear.
