### ISSUE TITLE
Multi-trageting basic class library with VS2015

### ISSUE THREAD

**Issue by gzak** [dotnet/corefx#8991]
I have a very barebones class library, and here's its project.json file (it's just a data model with very basic types and so doesn't need any other dependencies):
```
{
  "version": "1.1.0-beta2",
  "description": "My.Models",
  "authors": [ "asdf" ],

  "dependencies": {
    "NETStandard.Library": "1.5.0-rc2-24027"
  },

  "frameworks": {
    "netstandard1.2": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  }
}
```
I also have a separate solution with a traditional csproj project inside targeting .net 451 (framework assemblies), and when I add a dependency on the `My.Models` package in the csproj I get the following error (after the dependency list resolves and I accept the license terms):
```
Attempting to resolve dependency 'NETStandard.Library (≥ 1.5.0-rc2-24027)'.
'NETStandard.Library' already has a dependency defined for 'Microsoft.NETCore.Platforms'.
```
I'm using the following versions of software:
VS2015: 14.0.25123.00 Update 2
NuGet Package Manager (VS Extension): 3.4.3
dotnet (to create the package): 1.0.0-preview1-002702

cc https://github.com/dotnet/cli/issues/3206

**Comment by gzak** [comment]
https://github.com/dotnet/cli/issues/3206

**Comment by ericstj** [comment]
This is what I'd expect to see if your NuGet version was too old.  Looking at the linked issue that isn't actually the problem you are hitting now.  You're hitting 
```
Could not install package 'Microsoft.NETCore.Targets 1.0.1-rc2-24027'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

Which has been fixed with https://github.com/dotnet/corefx/pull/8929.  That fix is currently available in the RC4 packages, will be integrated to the RC3 packages tonight.

Duplicate issue of https://github.com/dotnet/corefx/issues/8822

**Comment by gzak** [comment]
@ericstj Totally right about the error message, and I thought I was careful and pasted the right one :)

Anyway, what exactly do I need to install (the RC3 packages of what?)? And do I need any kind of software update (VS, NuGet, dotnet, etc) to install it?
