### ISSUE TITLE
Socket.Handle isn't public *and* no access to SIO_KEEPALIVE_VALS / SIOCKEEPALIVE via Socket

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/corefx#9008]
Got here looking for how to call ioctl(SIOCKEEPALVIE) / WSAIOCTL(SIO_KEEPALIVE_VALS). No access via public Socket API layer and no access to the handle either.

I could P/Invoke it if I had the handle, but I don't oops.

**Comment by svick** [comment]
See #6807 for `Socket.Handle`.

**Comment by jhudsoncedaron** [comment]
Minor update it's not SIOCKEEPALIVE but TCP_KEEPIDLE. This doesn't make a practical difference.

**Comment by stephentoub** [comment]
Socket.Handle is now exposed for 1.2.
