### ISSUE TITLE
Filesystem tests for symlinks failing in Helix for OSX

### ISSUE THREAD

**Issue by brthor** [dotnet/corefx#9009]
These tests are all failing with a similar error and there don't seem to be any recent changes to the tests themselves.

System.IO.Tests.FileInfo_Exists.SymLinksMayExistIndependentlyOfTarget
System.IO.Tests.Directory_GetDirectories_str.EnumerateWithSymLinkToDirectory
System.IO.Tests.Directory_Delete_str_bool.DeletingSymLinkDoesntDeleteTarget	
System.IO.Tests.Directory_Delete_Tests.FileSystemWatcher_Directory_Delete_SymLink
System.IO.Tests.Directory_Create_Tests.FileSystemWatcher_Directory_Create_SymLink

Log:
```
System.ComponentModel.Win32Exception : No such file or directory
```

@dsgouda can you please take a look, you had the most recent changes to this directory (https://github.com/dotnet/corefx/tree/master/src/System.IO.FileSystem/tests)

@weshaggard @ericstj Any ideas on the cause?

**Comment by ellismg** [comment]
I think this is OSX specific (and may fail more reliability in Helix then on Jenkins, since the outerloop results have been more or less clean there).

I wonder if the logic around figuring out if we can run the test or not is not working correctly on Helix.

/cc @sokket

**Comment by ianhays** [comment]
>I wonder if the logic around figuring out if we can run the test or not is not working correctly on Helix.

This is almost certainly the case. These tests are Innerloop ConditionalFacts that are only run if the `CanCreateSymlinks` helper method succeeds. `CanCreateSymlinks` creates a symlink to a test file by starting a subprocess to `cmd /c mklink`. To verify if it succeeded, it checks that cmd returns 0 and then for FileSystemWatcher it calls File.Exists on the symlink to verify it exists. 

Are all of those tests throwing that same exception?

**Comment by brthor** [comment]
> Are all of those tests throwing that same exception?

 Yes

**Comment by ianhays** [comment]
These errors are caused by Helix not running the tests with elevated privileges. Matt Ellis is adding a trait to declare that a test requires elevated privileges in #9080. I'll push a quick PR adding that trait to these tests whenever he merges his PR.

**Comment by ellismg** [comment]
Ian, I thought that these tests were conditional on `CanCreateSymbolicLinks`?  Do you know why the tests would even run in this case?

**Comment by ianhays** [comment]
Weird, huh? `CanCreateSymbolicLinks` only checks that we can make a symlink to a file and the test failures above all make directory symlinks. If a system allowed File symlinks but not directory symlinks, we would see those failures.

That'd be my first guess. Second guess would be we can create a symlink - to a directory or file - without issue, but then when we try to *do* something to it (e.g. delete, enumerateentries) we can't find it and it fails. This would require that File.Exists passes on the created symlink which seems dubious.

**Comment by ericstj** [comment]
You can create file symlinks unelevated but directory symlinks require elevation.

**Comment by ericstj** [comment]
N/m, I misspoke all symlinks require elevation.  File hardlinks do not.

**Comment by ianhays** [comment]
I'm seeing some new failures in Helix on OSX around proc_pidpath that are causing the symlink creation to fail:

The tests themselves don't seem to matter that much and vary run by run, though generally these fail:
```
SymLinksAreReparsePoints
SymLinksReflectSymLinkAttributes
```

trace from helix:

```
System.ComponentModel.Win32Exception : No such file or directory
Stack Trace:
   at Interop.libproc.proc_pidpath(Int32 pid)
   at System.Diagnostics.Process.ResolvePath(String filename)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at MountHelper.CreateSymbolicLink(String linkPath, String targetPath, Boolean isDirectory)
   at System.IO.Tests.File_GetSetAttributes.SymLinksAreReparsePoints()
```
