### ISSUE TITLE
Consider exposing more APIs via RuntimeInformation

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#9011]
The CLI and AspNet Core have a bunch of APIs that p/invoke to read runtime information that's not readily available via `RuntimeInformation`. This includes operating system version and Unix distro name. Scanning through the code, there're internal APIs to read both these pieces of information, but they aren't surfaced in a way that can be consumed.

Could the API surface for `RuntimeInformation` be enhanced to include this information?

**Comment by joshfree** [comment]
@weshaggard giving this to you since you have strong feelings about this space

**Comment by weshaggard** [comment]
A more general issue is at https://github.com/dotnet/corefx/issues/12737 so closing this one in favor of that issue.
