### ISSUE TITLE
Strategy for targetting safe subsets of mscorlib

### ISSUE THREAD

**Issue by gulbanana** [dotnet/corefx#9039]
This blog post describes plans to support more API on .NET core:
https://blogs.msdn.microsoft.com/dotnet/2016/05/27/making-it-easier-to-port-to-net-core/

Good news, but it does raise some questions. Let's say that in six months it's possible to link against the BCL reference assemblies; you compile a dll, which can now be used on the various platforms and appmodels of the core CLR. So: what happens to code which calls System.DoesntWorkOnLinux? Or in the case of UWP, System.IO?

As a library author, I won't have the capability to test every current and future platform. How should I go about building packages which do not throw PlatformNotSupportedException in an unexpected new environment?

Can netstandard help here? It's not yet clear how it will relate to mscorlib - and some problems would still exist, like the one with System.IO in Store apps.

**Comment by danmosemsft** [comment]
Great question. First, our goal will be to remove PlatformNoSupportedException in the BCL as far as possible - even for example for use of ACL's on Unix we could emulate them to some extent or possibly no-op in some scenarios. There will still be API's that are truly platform specific and we're discussing how we could best help you detect that you're hitting these. Roslyn analyzers are one possibility. @terrajobst any other thoughts here?

**Comment by gulbanana** [comment]
At dotnetconf Miguel de Icaza talked about a 'nugeterizer' project type which would wrap multiple other platform-specific projects and create packages which have the intersection of their exposed APIs. Some mechanism like this would help, as long as it was available in-solution rather than only when building nugets.

**Comment by gulbanana** [comment]
More APIs are being added to netstandard which are not truly cross-platform. For example, these fail at runtime on Xamarin:
System.Runtime.InteropServices
System.Net.Http

And these fail at runtime on UWP:
System.Runtime.Loader
System.Security.Cryptography.Csp
System.Net.NetworkInformation

There are many others, and it's not just the 'obscure' platforms. System.Runtime.Loader even fails at runtime on .NET Framework 4.6.2. This is becoming a major issue for developing portable software.

**Comment by davidfowl** [comment]
Unfortunately there's no silver bullet for this. The best we can do is try to make it more predictable. Some of the things tou mention just sound like bugs

**Comment by gulbanana** [comment]
Is it accurate to say that netstandard will be more for consuming than authoring (outside of Microsoft), and many libraries should be built for multi-TFM instead? (e.g. supporting and testing specific platforms)

**Comment by davidfowl** [comment]
Nope. The libraries we write will strive to be netstandard. When we need platform specific API then we'll consider cross compiling. All of ASP.NET will most likely be .NET Standard 2.0 without hacks.

**Comment by gulbanana** [comment]
yeah, netstandard 2.0 changes the game. quoting two sections of the blog post in particular:

Optional APIs aren’t part of .NET Standard but are available as separate NuGet packages. We try to build these as libraries targeting .NET Standard so that their implementation can be consumed from any platform, but that might not always be feasible for platform specific APIs (e.g. Windows registry).

[..]

Our general strategy for dealing with technologies that are only available on some .NET platforms is to make them NuGet packages that sit above the .NET Standard. So if you create a .NET Standard-based library, it’ll not reference these APIs by default. You’ll have to add a NuGet package that brings them in.

This strategy works well for APIs that are self-contained and thus can be moved into a separate package. For cases where individual members on types cannot be implemented everywhere, we’ll use the second and third approach: platforms have to have these members but they can decide to throw or emulate them.

so, summary: reference netstandard.library 2.0 and *most* apis will just work. the bulk of optionally-supported types will be in packages which are hopefully tfm-limited. there will be the occasional exception like AppDomain.Create which will throw outside desktop.

finally, i see that my nemesis System.Runtime.Loader is gone. that counts as a fix, IMO.
