### ISSUE TITLE
Remove -rc3 prerelease moniker

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#9040]
We'll need to drop the -rc3 prerelease moniker from /release/1.0.0 branches (CoreCLR, CoreFX, WCF)  mid next week

**Comment by ericstj** [comment]
@joshfree @weshaggard @gkhanna79 can we get a consolidated list of which packages and versions we want to mark as stable?

**Comment by gkhanna79** [comment]
CoreCLR: Microsoft.NETCore.Runtime.CoreCLR version 1.0.2

JIT: Microsoft.NETCore.Jit 1.0.2 
ILAsm: Microsoft.NETCore.ILAsm 1.0.2
ILDasm: Microsoft.NETCore.ILDasm 1.0.2

@russellhadley @RussKeldorph Please chime in and confirm the names and versions of the JIT/ILAsm/ILDasm packages.

**Comment by gkhanna79** [comment]
CC @sergiy-k

**Comment by gkhanna79** [comment]
@schellap Can you please add the host packages to this list as well?

**Comment by gkhanna79** [comment]
@ericstj @weshaggard Do the repos need to be on specific Buildtools version to support this?

**Comment by russellhadley** [comment]
The JIT/ILAsm/ILDasm names look fine to me.  (I don't think we need to solve having one jit package that plugs  into different runtime contexts yet.  I.e. is NETCore to specific)

**Comment by ericstj** [comment]
No, I've had support in buildtools for this since I added packaging.  We just add entries to the StablePackages item in the repo.

**Comment by schellap** [comment]
Updated the above list with host packages and the stable version that we'd rev to for RTM.

**Comment by joshfree** [comment]
Here's the list from RC2.  You'll need to add the runtime packages for openSUSE 13.2, Fedora 23, and Ubuntu 16.04 to the list as well


runtime.debian.8-x64.Microsoft.NETCore.ConsoleHost.1.0.0
runtime.debian.8-x64.Microsoft.NETCore.ILAsm.1.0.2
runtime.debian.8-x64.Microsoft.NETCore.ILDAsm.1.0.2
runtime.debian.8-x64.Microsoft.NETCore.Runtime.CoreCLR.1.0.2
runtime.debian.8-x64.Microsoft.NETCore.TestHost.1.0.0
runtime.debian.8-x64.runtime.native.System.1.0.1
runtime.debian.8-x64.runtime.native.System.IO.Compression.1.0.1
runtime.debian.8-x64.runtime.native.System.Net.Http.1.0.1
runtime.debian.8-x64.runtime.native.System.Net.Security.1.0.1
runtime.debian.8-x64.runtime.native.System.Security.Cryptography.1.0.1
runtime.osx.10.10-x64.Microsoft.NETCore.ConsoleHost.1.0.0
runtime.osx.10.10-x64.Microsoft.NETCore.ILAsm.1.0.2
runtime.osx.10.10-x64.Microsoft.NETCore.ILDAsm.1.0.2
runtime.osx.10.10-x64.Microsoft.NETCore.Runtime.CoreCLR.1.0.2
runtime.osx.10.10-x64.Microsoft.NETCore.TestHost.1.0.0
runtime.osx.10.10-x64.runtime.native.System.1.0.1
runtime.osx.10.10-x64.runtime.native.System.IO.Compression.1.0.1
runtime.osx.10.10-x64.runtime.native.System.Net.Http.1.0.1
runtime.osx.10.10-x64.runtime.native.System.Net.Security.1.0.1
runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.1.0.1
runtime.rhel.7-x64.Microsoft.NETCore.ConsoleHost.1.0.0
runtime.rhel.7-x64.Microsoft.NETCore.ILAsm.1.0.2
runtime.rhel.7-x64.Microsoft.NETCore.ILDAsm.1.0.2
runtime.rhel.7-x64.Microsoft.NETCore.Runtime.CoreCLR.1.0.2
runtime.rhel.7-x64.Microsoft.NETCore.TestHost.1.0.0
runtime.rhel.7-x64.runtime.native.System.1.0.1
runtime.rhel.7-x64.runtime.native.System.IO.Compression.1.0.1
runtime.rhel.7-x64.runtime.native.System.Net.Http.1.0.1
runtime.rhel.7-x64.runtime.native.System.Net.Security.1.0.1
runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.1.0.1
runtime.ubuntu.14.04-x64.Microsoft.NETCore.ConsoleHost.1.0.0
runtime.ubuntu.14.04-x64.Microsoft.NETCore.ILAsm.1.0.2
runtime.ubuntu.14.04-x64.Microsoft.NETCore.ILDAsm.1.0.2
runtime.ubuntu.14.04-x64.Microsoft.NETCore.Runtime.CoreCLR.1.0.2
runtime.ubuntu.14.04-x64.Microsoft.NETCore.TestHost.1.0.0
runtime.ubuntu.14.04-x64.runtime.native.System.1.0.1
runtime.ubuntu.14.04-x64.runtime.native.System.IO.Compression.1.0.1
runtime.ubuntu.14.04-x64.runtime.native.System.Net.Http.1.0.1
runtime.ubuntu.14.04-x64.runtime.native.System.Net.Security.1.0.1
runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.1.0.1
runtime.win10-x64.runtime.native.System.IO.Compression.4.0.1
runtime.win7-x64.Microsoft.NETCore.ConsoleHost.1.0.0
runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR.1.0.2
runtime.win7-x64.Microsoft.NETCore.TestHost.1.0.0
runtime.win7-x64.Microsoft.NETCore.Windows.ApiSets.1.0.1
runtime.win7-x64.runtime.native.System.Data.SqlClient.sni.4.0.1
runtime.win7-x64.runtime.native.System.IO.Compression.4.0.1
runtime.win8-x64.Microsoft.NETCore.Windows.ApiSets.1.0.1
runtime.win81-x64.Microsoft.NETCore.Windows.ApiSets.1.0.1
runtime.win10-arm.runtime.native.System.IO.Compression.4.0.1
runtime.win7-arm.Microsoft.NETCore.ConsoleHost.1.0.0
runtime.win7-arm.Microsoft.NETCore.TestHost.1.0.0
runtime.win7-arm.runtime.native.System.IO.Compression.4.0.1
runtime.win8-arm.Microsoft.NETCore.Runtime.CoreCLR.1.0.2
Microsoft.CSharp.4.0.1
Microsoft.NETCore.5.0.1
Microsoft.NETCore.Console.1.0.0
Microsoft.NETCore.ConsoleHost.1.0.0
Microsoft.NETCore.ILAsm.1.0.2
Microsoft.NETCore.ILDAsm.1.0.2
Microsoft.NETCore.Platforms.1.0.1
Microsoft.NETCore.Portable.Compatibility.1.0.1
Microsoft.NETCore.Runtime.1.0.2
Microsoft.NETCore.Runtime.CoreCLR.1.0.2
Microsoft.NETCore.Runtime.Native.1.0.2
Microsoft.NETCore.Targets.1.0.1
Microsoft.NETCore.TestHost.1.0.0
Microsoft.NETCore.UniversalWindowsPlatform.5.2.0
Microsoft.NETCore.Windows.ApiSets.1.0.1
Microsoft.TargetingPack.Private.CoreCLR.1.0.0
Microsoft.TargetingPack.Private.NETNative.1.0.0
Microsoft.VisualBasic.10.0.1
Microsoft.Win32.Primitives.4.0.1
Microsoft.Win32.Registry.4.0.0
Microsoft.Win32.Registry.AccessControl.4.0.0
NETStandard.Library.1.5.0
runtime.any.System.AppContext.4.1.0
runtime.any.System.Collections.4.0.11
runtime.any.System.Diagnostics.Tools.4.0.1
runtime.any.System.Diagnostics.Tracing.4.1.0
runtime.any.System.Globalization.4.0.11
runtime.any.System.Globalization.Calendars.4.0.1
runtime.any.System.IO.4.1.0
runtime.any.System.Reflection.4.1.0
runtime.any.System.Reflection.Extensions.4.0.1
runtime.any.System.Reflection.Primitives.4.0.1
runtime.any.System.Resources.ResourceManager.4.0.1
runtime.any.System.runtime.4.1.0
runtime.any.System.Runtime.Handles.4.0.1
runtime.any.System.Runtime.InteropServices.4.1.0
runtime.any.System.Text.Encoding.4.0.11
runtime.any.System.Text.Encoding.Extensions.4.0.11
runtime.any.System.Threading.Tasks.4.0.11
runtime.any.System.Threading.Timer.4.0.1
runtime.aot.System.Collections.4.0.10
runtime.aot.System.Diagnostics.Tools.4.0.1
runtime.aot.System.Diagnostics.Tracing.4.0.20
runtime.aot.System.Globalization.4.0.11
runtime.aot.System.Globalization.Calendars.4.0.1
runtime.aot.System.IO.4.1.0
runtime.aot.System.Reflection.4.0.10
runtime.aot.System.Reflection.Extensions.4.0.0
runtime.aot.System.Reflection.Primitives.4.0.0
runtime.aot.System.Resources.ResourceManager.4.0.0
runtime.aot.System.Runtime.4.0.20
runtime.aot.System.Runtime.Handles.4.0.1
runtime.aot.System.Runtime.InteropServices.4.0.20
runtime.aot.System.Text.Encoding.4.0.11
runtime.aot.System.Text.Encoding.Extensions.4.0.11
runtime.aot.System.Threading.Tasks.4.0.11
runtime.aot.System.Threading.Timer.4.0.1
runtime.native.System.4.0.0
runtime.native.System.Data.SqlClient.sni.4.0.0
runtime.native.System.IO.Compression.4.1.0
runtime.native.System.Net.Http.4.0.1
runtime.native.System.Net.Security.4.0.1
runtime.native.System.Security.Cryptography.4.0.0
runtime.unix.Microsoft.Win32.Primitives.4.0.1
runtime.unix.System.Console.4.0.0
runtime.unix.System.Diagnostics.Debug.4.0.11
runtime.unix.System.IO.FileSystem.4.0.1
runtime.unix.System.Net.Primitives.4.0.11
runtime.unix.System.Net.Sockets.4.1.0
runtime.unix.System.Private.Uri.4.0.1
runtime.unix.System.Runtime.Extensions.4.1.0
runtime.unix.System.Runtime.InteropServices.RuntimeInformation.4.0.0
runtime.win.System.Runtime.InteropServices.RuntimeInformation.4.0.0
runtime.win10-x86.runtime.native.System.IO.Compression.4.0.1
runtime.win7-x86.Microsoft.NETCore.ConsoleHost.1.0.0
runtime.win7-x86.Microsoft.NETCore.Runtime.CoreCLR.1.0.2
runtime.win7-x86.Microsoft.NETCore.TestHost.1.0.0
runtime.win7-x86.Microsoft.NETCore.Windows.ApiSets.1.0.1
runtime.win7-x86.runtime.native.System.Data.SqlClient.sni.4.0.1
runtime.win7-x86.runtime.native.System.IO.Compression.4.0.1
runtime.win7.Microsoft.Win32.Primitives.4.0.1
runtime.win7.System.Console.4.0.0
runtime.win7.System.Diagnostics.Debug.4.0.11
runtime.win7.System.IO.FileSystem.4.0.1
runtime.win7.System.Net.Primitives.4.0.11
runtime.win7.System.Net.Sockets.4.1.0
runtime.win7.System.Private.Uri.4.0.1
runtime.win7.System.Runtime.Extensions.4.1.0
runtime.win8-x86.Microsoft.NETCore.Windows.ApiSets.1.0.1
runtime.win81-x86.Microsoft.NETCore.Windows.ApiSets.1.0.1
System.AppContext.4.1.0
System.Buffers.4.0.0
System.Collections.4.0.11
System.Collections.Concurrent.4.0.12
System.Collections.Immutable.1.2.0
System.Collections.NonGeneric.4.0.1
System.Collections.Specialized.4.0.1
System.ComponentModel.4.0.1
System.ComponentModel.Annotations.4.1.0
System.ComponentModel.EventBasedAsync.4.0.11
System.ComponentModel.Primitives.4.0.1
System.ComponentModel.TypeConverter.4.0.1
System.Console.4.0.0
System.Data.Common.4.0.1
System.Data.SqlClient.4.1.0
System.Diagnostics.Contracts.4.0.1
System.Diagnostics.Debug.4.0.11
System.Diagnostics.DiagnosticSource.4.0.0
System.Diagnostics.FileVersionInfo.4.0.0
System.Diagnostics.Process.4.1.0
System.Diagnostics.StackTrace.4.0.1
System.Diagnostics.TextWriterTraceListener.4.0.0
System.Diagnostics.Tools.4.0.1
System.Diagnostics.TraceSource.4.0.0
System.Diagnostics.Tracing.4.1.0
System.Drawing.Primitives.4.0.0
System.Dynamic.Runtime.4.0.11
System.Globalization.4.0.11
System.Globalization.Calendars.4.0.1
System.Globalization.Extensions.4.0.1
System.IO.4.1.0
System.IO.Compression.4.1.0
System.IO.Compression.ZipFile.4.0.1
System.IO.FileSystem.4.0.1
System.IO.FileSystem.AccessControl.4.0.0
System.IO.FileSystem.DriveInfo.4.0.0
System.IO.FileSystem.Primitives.4.0.1
System.IO.FileSystem.Watcher.4.0.0
System.IO.IsolatedStorage.4.0.1
System.IO.MemoryMappedFiles.4.0.0
System.IO.Packaging.4.0.0
System.IO.Pipes.4.0.0
System.IO.UnmanagedMemoryStream.4.0.1
System.Linq.4.1.0
System.Linq.Expressions.4.0.11
System.Linq.Parallel.4.0.1
System.Linq.Queryable.4.0.1
System.Net.Http.4.0.1
System.Net.Http.Rtc.4.0.1
System.Net.Http.WinHttpHandler.4.0.0
System.Net.NameResolution.4.0.0
System.Net.NetworkInformation.4.1.0
System.Net.Ping.4.0.0
System.Net.Primitives.4.0.11
System.Net.Requests.4.0.11
System.Net.Security.4.0.0
System.Net.Sockets.4.1.0
System.Net.WebHeaderCollection.4.0.1
System.Net.WebSockets.4.0.0
System.Net.WebSockets.Client.4.0.0
System.Numerics.Vectors.4.1.1
System.Numerics.Vectors.WindowsRuntime.4.0.1
System.ObjectModel.4.0.12
System.Private.DataContractSerialization.4.1.1
System.Private.ServiceModel.4.1.0
System.Private.Uri.4.0.1
System.Reflection.4.1.0
System.Reflection.Context.4.0.1
System.Reflection.DispatchProxy.4.0.1
System.Reflection.Emit.4.0.1
System.Reflection.Emit.ILGeneration.4.0.1
System.Reflection.Emit.Lightweight.4.0.1
System.Reflection.Extensions.4.0.1
System.Reflection.Metadata.1.3.0
System.Reflection.Primitives.4.0.1
System.Reflection.TypeExtensions.4.1.0
System.Resources.Reader.4.0.0
System.Resources.ReaderWriter.4.0.0
System.Resources.ResourceManager.4.0.1
System.Resources.Writer.4.0.0
System.Runtime.4.1.0
System.Runtime.CompilerServices.VisualC.4.0.0
System.Runtime.Extensions.4.1.0
System.Runtime.Handles.4.0.1
System.Runtime.InteropServices.4.1.0
System.Runtime.InteropServices.PInvoke.4.0.0
System.Runtime.InteropServices.RuntimeInformation.4.0.0
System.Runtime.InteropServices.WindowsRuntime.4.0.1
System.Runtime.Loader.4.0.0
System.Runtime.Numerics.4.0.1
System.Runtime.Serialization.Json.4.0.2
System.Runtime.Serialization.Primitives.4.1.1
System.Runtime.Serialization.Xml.4.1.1
System.Runtime.WindowsRuntime.4.0.11
System.Runtime.WindowsRuntime.UI.Xaml.4.0.1
System.Security.AccessControl.4.0.0
System.Security.Claims.4.0.1
System.Security.Cryptography.Algorithms.4.1.0
System.Security.Cryptography.Cng.4.1.0
System.Security.Cryptography.Csp.4.0.0
System.Security.Cryptography.Encoding.4.0.0
System.Security.Cryptography.OpenSsl.4.0.0
System.Security.Cryptography.Primitives.4.0.0
System.Security.Cryptography.X509Certificates.4.1.0
System.Security.Principal.4.0.1
System.Security.Principal.Windows.4.0.0
System.ServiceModel.Duplex.4.0.1
System.ServiceModel.Http.4.1.0
System.ServiceModel.NetTcp.4.1.0
System.ServiceModel.Primitives.4.1.0
System.ServiceModel.Security.4.0.1
System.ServiceProcess.ServiceController.4.1.0
System.Text.Encoding.4.0.11
System.Text.Encoding.CodePages.4.0.1
System.Text.Encoding.Extensions.4.0.11
System.Text.Encodings.Web.4.0.0
System.Text.RegularExpressions.4.0.12
System.Threading.4.0.11
System.Threading.AccessControl.4.0.0
System.Threading.Overlapped.4.0.1
System.Threading.Tasks.4.0.11
System.Threading.Tasks.Dataflow.4.6.0
System.Threading.Tasks.Extensions.4.0.0
System.Threading.Tasks.Parallel.4.0.1
System.Threading.Thread.4.0.0
System.Threading.ThreadPool.4.0.10
System.Threading.Timer.4.0.1
System.Xml.ReaderWriter.4.0.11
System.Xml.XDocument.4.0.11
System.Xml.XmlDocument.4.0.1
System.Xml.XmlSerializer.4.0.11
System.Xml.XPath.4.0.1
System.Xml.XPath.XDocument.4.0.1
System.Xml.XPath.XmlDocument.4.0.1

**Comment by RussKeldorph** [comment]
@gkhanna79 I'm fine with the JIT/ILAsm/ILDasm package names as well.  I'm not familiar with the versions.  Are those not obviously the correct ones?

/cc @pgavlin

**Comment by gkhanna79** [comment]
@RussKeldorph The versions look correct and correspond to the ones in the package that is produced. This is merely to ensure you are in the loop.

**Comment by ellismg** [comment]
> NETStandard.Library.1.5.0

That should be 1.6.0, right?

Regarding TestHost and ConsoleHost, I am surprised we are marking them as stable/shipping them at all.  I thought we only use the CLI host for now?

**Comment by joshfree** [comment]
>  That should be 1.6.0, right?
@ellismg yes.  That's the RC2 list as a starting point.

**Comment by weshaggard** [comment]
I agree about TestHost/ConsoleHost we don't need to ship them stable. Can we get a diff of this an all our packages so we can see the delta? Another one I didn't see in the list is System.Security.SecureString which we are plan to ship now.

**Comment by ericstj** [comment]
Ok, creating that here https://gist.github.com/ericstj/7eb848890c19e992c928fe26486235bf  will ping when I have it filled in to the best of my ability.  Should we have specific leads sign off on which packages are in there as well as that they have all of their packages listed?

**Comment by ericstj** [comment]
Ok, PR's for CoreCLR, CoreFx, and WCF are up:
https://github.com/dotnet/corefx/pull/9292
https://github.com/dotnet/wcf/pull/1276
https://github.com/dotnet/coreclr/pull/5654

Still need to do core-setup.  I'm leaving cli alone for now since that's black magic to me. @piotrpMSFT / @eerhardt is this something you're tracking to do (mark CLI packages stable).

**Comment by eerhardt** [comment]
> @piotrpMSFT / @eerhardt is this something you're tracking to do (mark CLI packages stable).

We are now:

https://github.com/dotnet/cli/issues/3465

But we are nowhere near getting to that point yet.

**Comment by ericstj** [comment]
@schellap  and I have a PR for core-setup: https://github.com/dotnet/core-setup/pull/128

/cc @tmat @danroth27 looks like we'll need to coordinate for LibUV and Roslyn packages.

**Comment by danroth27** [comment]
Adding @Eilon @muratg to help coordinate.

**Comment by muratg** [comment]
@moozzyk will be providing the libuv "RTM" package. I believe he's working with @ellismg to ensure the current set of binaries work with the newly supported distros.

**Comment by moozzyk** [comment]
status: stuck @ LCA

**Comment by joshfree** [comment]
latest libuv with proper MIT licensing is already in core-setup (as of earlier today)

**Comment by joshfree** [comment]
> looks like we'll need to coordinate for LibUV and Roslyn packages.

@cston is taking care of Roslyn

**Comment by ericstj** [comment]
This has been done for corefx, coreclr, and WCF.
