### ISSUE TITLE
Enable System.Net tests to run against NetFX

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#9045]
/cc @tarekgh @davidsh

An example is already available in `System.Globalization.Calendars`. 
To run the tests against .Net 4.6 Desktop: `msbuild /t:rebuild,test /property:Configuration=net46`.

**Comment by tarekgh** [comment]
please hold on that till we finish the infrastructure. in general we'll have a property called TestTFM which can be set to the platform we need to run the test against. will let you know when it is ready.

**Comment by CIPop** [comment]
> please hold on that till we finish the infrastructure

@tarekgh Can you please back-reference the issue# or VSO bug# so that we know when this work was completed?

**Comment by karelz** [comment]
@tarekgh is driving global CoreFX tests running on NetFX.
