### ISSUE TITLE
Port ProtectedMemory

### ISSUE THREAD

**Issue by erikzhang** [dotnet/corefx#9058]
I found the class ProtectedData in System.Security.Cryptography, but did not find the class ProtectedMemory.

**Comment by AtsushiKan** [comment]
Is there a specific scenario that you need this for? 

ProtectedData/Memory is very Windows-specific and normally not the sort of thing we'd add but we had very specific reasons for adding ProtectedData. ProtectedMemory requires apis that aren't in the UWP api list so adding them alongside ProtectedData would require forking the package.

So it would be good to know if the lack of this api is actually blocking something or if this was opened for "completeness."

**Comment by erikzhang** [comment]
It is useful to protect in-memory data, such as key, password and so on.

**Comment by AtsushiKan** [comment]
Yes, but any number of crypto algorithms already in the stack can do that. What I'm looking for is is there an existing scenario that needs this particular encryption scheme. This api's encryption uses key material that's only good for the current logon session so it's unlikely there would be long-term persisted data that needs to be decrypted here. I'm looking for something like "Important server X that we don't have control over encrypts data using this api and passes it cross-process to client Y that we want to migrate to Core."

**Comment by weshaggard** [comment]
We will expose this just like ProtectedData and implement it on windows and have it throw on X-plat.

**Comment by erikzhang** [comment]
Is it possible that implement it on linux too?

**Comment by stephentoub** [comment]
> Is it possible that implement it on linux too?

We're not aware of any good way to do so.

**Comment by erikzhang** [comment]
> We're not aware of any good way to do so.

This is a bad news...

**Comment by danmosemsft** [comment]
@erikzhang are you interested in making a PR (with some tests)?

**Comment by erikzhang** [comment]
Well I know ProtectedMemory is a wrapper around CryptProtectMemory and CryptUnprotectMemory. I can make a RP to implement it.
By the way, is that a windows-only functionality? I can't find any equivalent functions in linux or osx.

**Comment by ligengatms** [comment]
hi, is this work still ongoing? do you have any plan when it will be supported?

**Comment by danmosemsft** [comment]
Curious what you need it for? Is this new code or porting existing code? What behavior would you expect in Linux if there is no OS support, throw or no option?

**Comment by danmosemsft** [comment]
@ligengatms no it needs an owner. Any interest?

**Comment by GrabYourPitchforks** [comment]
Closing this issue. See https://github.com/dotnet/corefx/issues/32309#issuecomment-536064487 for reasoning.
