### ISSUE TITLE
ApiCompat issue with System.Diagnostics.Tracing

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#9060]
@vancem I was looking at the ApiCompat errors with System.Diagnostics.Tracing library in the release branch and we are still seeing:

```
CannotMakeMoreVisible : Visibility of member 'System.Diagnostics.Tracing.EventListener.EventSourceIndex(System.Diagnostics.Tracing.EventSource)' is 'Family' in the implementation but 'Public' in the contract.
```

So while you made this an internal helper it is still public in the contract.  See https://github.com/dotnet/corefx/pull/7442/files#diff-4e6fc7375b9eeb2cbb687c1513ccdc14R124

So that means anyone using that method and trying to run on .NET 4.6.2 they will fail because that public member doesn't exist. We should try and address this for RTM.

**Comment by joshfree** [comment]
@vancem can you try to get this fixed in /rel today?

**Comment by vancem** [comment]
I will take a look now.

**Comment by vancem** [comment]
Pull request is available.  Mail has ben sent to .NetShiproom.

**Comment by joshfree** [comment]
Closing as this has been ported to release
