### ISSUE TITLE
ApiCompat issues with System.Text.RegularExpressions

### ISSUE THREAD

**Issue by weshaggard** [dotnet/corefx#9061]
@Priya91 as part of PR https://github.com/dotnet/corefx/pull/7456 you baselined the following APIs which need to be fixed before we ship this package stable. 

```
MembersMustExist : Member 'System.Text.RegularExpressions.Regex.Caps.get()' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Text.RegularExpressions.Regex.Caps.set(System.Collections.IDictionary)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Text.RegularExpressions.Regex.CapNames.get()' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Text.RegularExpressions.Regex.CapNames.set(System.Collections.IDictionary)' does not exist in the implementation but it does exist in the contract.
```

Currently with these baselined it means people that use these APIs and try to run on .NET 4.6.2 they will fail because those APIs do not exist. Since these APIs did not ship in .NET 4.6.2 you need to update the contract to be netstandard1.6 and net463 and these APIs need to be added in .NET 4.6.3.

**Comment by Priya91** [comment]
working on this

**Comment by Priya91** [comment]
this is merged.
