### ISSUE TITLE
Thread.IsThreadPoolThread not exposed in coreclr

### ISSUE THREAD

**Issue by benaadams** [dotnet/corefx#9063]
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/Thread.cs#L645-L649

Some times we want to queue things on the threadpool; but if we are already on the threadpool continue executing rather than queue - however the thread can't be checked if is threadpool thread currently.

Coreclr issue https://github.com/dotnet/coreclr/issues/5407

**Comment by kouvel** [comment]
This will be added as part of #11632
