### ISSUE TITLE
CI tests pass, but plugin fails to report results, failing leg

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#9066]
```
[xUnit] [ERROR] - The plugin hasn't been performed correctly: Problem on deletion
```

e.g.
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_release_prtest/1749/consoleText
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/1790/consoleText

**Comment by joshfree** [comment]
Moving to 1.1 as this isn't blocking shipping from the /release/1.0.0 branch

**Comment by karelz** [comment]
Probably not happening anymore. If it does, let's file an issue and look into it right away.

**Comment by mmitche** [comment]
I haven't seen this in a while, but the good news is there is new logging in there so we should be able to see some more diagnostics
