### ISSUE TITLE
Two outerloop Process tests failing on OSX with "Permission denied"

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#9068]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_osx_debug/55/consoleText
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_osx_release/58/consoleText
```
System.Diagnostics.Tests.ProcessTests.TestBasePriorityOnUnix [FAIL]
        System.ComponentModel.Win32Exception : Permission denied
        Stack Trace:
              at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass value)
              at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value)
              at System.Diagnostics.Tests.ProcessTests.SetAndCheckBasePriority(ProcessPriorityClass exPriorityClass, Int32 priority)
              at System.Diagnostics.Tests.ProcessTests.TestBasePriorityOnUnix()
```
and
```
System.Diagnostics.Tests.ProcessTests.TestPriorityClassUnix [FAIL]
        System.ComponentModel.Win32Exception : Permission denied
        Stack Trace:
              at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass value)
              at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value)
              at System.Diagnostics.Tests.ProcessTests.TestPriorityClassUnix()
```
Both of these tests have a comment next to them "// This test requires admin elevation on Unix
"... maybe the runs where these fail isn't being done elevated?

**Comment by ellismg** [comment]
We are also seeing these failures (across all Unixes) in Helix which runs exclusively non elevated, but all outerloop tests.

@mmitche Did something change which the macs?  Do we now need to explicitly sudo our test runs?

**Comment by mmitche** [comment]
@ellismg Yes, it's not launching as non-elevated.  We'll need to disable sudo psswd for the commands we need.  We don't have the same flexibility as we did with the other Ubuntu machines (which have separate startup scripts and VMs).  We changed from using JNLP remoting, which was launching as root to launching VIA SSH from Jenkins itself, which is launching as non-root.  This is to avoid the disconnect failures we've been seeing.

We could disable password root for commands we need.

**Comment by mmitche** [comment]
Alternatively, we could dedicate some computers to root access only, but we have limited mac resources

**Comment by ellismg** [comment]
> Alternatively, we could dedicate some computers to root access only, but we have limited mac resources

I am going to adding metadata to our tests that describe which ones require elevation.  It sounds like we should just start passing that in Jenkins for OSX and maybe try to get elevated coverage internally in Helix.

**Comment by mmitche** [comment]
@ellismg What about cases where we want coverage in PR builds?

**Comment by mmitche** [comment]
I am thinking that we can easily do both on the Jenkins side by setting up the right permissions on the machine and then running them as a developer would (with sudo)

**Comment by Priya91** [comment]
Fixed with #9308

**Comment by stephentoub** [comment]
These are failing again, e.g.
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_osx_debug/84/
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_osx_debug/82/
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_osx_debug/81

**Comment by Priya91** [comment]
This happned because the tests were run on mac machine, that was not configured for running elevated tests. This machine was wrongly tagged with the mac-elevated jenkins label. Fixed it.

**Comment by stephentoub** [comment]
Thanks, @Priya91.
