### ISSUE TITLE
Add NuGet serviceable attribute to all packages

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#9072]
Tracking bug on the CoreFX/CoreCLR/WCF side for https://github.com/NuGet/Home/issues/2870

@ericstj @gkhanna79 @rohit21agrawal

**Comment by ericstj** [comment]
I already have a prototype: https://github.com/ericstj/buildtools/commit/86343cb6efe41e3235e6816f2b97bb1f90c2e932

Right now we're blocked on getting real nuget bits that implement the feature.

**Comment by joshfree** [comment]
> Right now we're blocked on getting real nuget bits that implement the feature.

@yishaigalatzer how soon can we get an updated nuget.exe?

**Comment by ericstj** [comment]
We just need the nuget DLL nupkgs, not exe.

**Comment by yishaigalatzer** [comment]
You can grab bits off the nugetbuild feed as soon as rohit checks in

**Comment by joshfree** [comment]
https://github.com/NuGet/NuGet.Client/pull/639

**Comment by joshfree** [comment]
@ericstj can this be verified and closed now on rc3-24208-04?

**Comment by ericstj** [comment]
Yep, looks good.  I've checked packages produced from CoreFx and TFS and they have this attribute.
