### ISSUE TITLE
[CurlHandler] HttpClientHandler.SendAsync on Unix completes at start-of-body, not end-of-headers

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#9075]
The implementation currently looks for the first byte of the body (or no more processing to be done) as an indication that the response message should be published, but it should really be when the last byte of the headers are received.  Ideally we'd find some mechanism to be notified by libcurl of end-of-headers (including end-of-headers for the final request when doing automatic redirection) so we can publish then, in case there's a delay between the last byte of the headers and the first byte of the body.

We may need to switch to not using libcurl's automatic redirection mechanism and instead handle automatic redirections manually, using https://curl.haxx.se/libcurl/c/CURLOPT_FOLLOWLOCATION.html.

**Comment by ericeil** [comment]
Moving to "future" as there doesn't seem to be much urgency to making this change.

**Comment by Priya91** [comment]
From @stephentoub 
"The impact here is really only if the server has a delay between sending the last byte of the headers and the first byte of the body, and that delay is meaningful to the consumer of the data… typically the server won’t and typically there’s nothing different a consumer would do if it did.  So that’s relatively niche I think."

This would be low pri for 2.0, hence moving to Future.

**Comment by davidsh** [comment]
@karelz Given that SocketsHttpHandler is the default for .NET Core 2.1 and the future plan is to deprecate CurlHandler, perhaps we can close this issue?

**Comment by karelz** [comment]
Agreed, closing.

**Comment by karelz** [comment]
Actually, it has disabled tests against it. We need to disable them permanently without linking this bug.

**Comment by stephentoub** [comment]
@karelz, I searched the repo for 9075, and I don't see this issue referred to anywhere.

**Comment by davidsh** [comment]
>@karelz, I searched the repo for 9075, and I don't see this issue referred to anywhere.

In that case, I will close this issue.
