### ISSUE TITLE
Enumerable Append and Prepend should be ported to the netfx

### ISSUE THREAD

**Issue by VSadov** [dotnet/corefx#9085]
Enumerable.Append and Enumerable.Prepend are new public API added in CoreFX

**Comment by VSadov** [comment]
related to https://github.com/dotnet/corefx/pull/9079

**Comment by karelz** [comment]
@vsadov @OmarTawfik I assume that this tracks full .NET Framework port. If that's the case, we do not need to keep the issue opened - the 'netfx-port-consider' tag will track it even if the issue is closed.
We don't use GitHub to track full .NET Framework bugs.
