### ISSUE TITLE
NETFX: Port Compile(System.Boolean) overloads in Linq.Expressions to netfx

### ISSUE THREAD

**Issue by VSadov** [dotnet/corefx#9087]
Preferrable with full interpreter support.

It would be acceptable just to port the API and fallback to compiling since API does not strictly require interpretation.

**Comment by VSadov** [comment]
related to https://github.com/dotnet/corefx/pull/9079

**Comment by karelz** [comment]
We don't need to keep NETFX bugs opened - netfx-port-consider is sufficient.
