### ISSUE TITLE
The build.cmd script should accept more common options

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#9088]
Currently to build the repo as release you have to do this:

```cmd
build /p:ConfigurationGroup=Release
```

This is very error-prone to typos, since you can write something like `/p:ConfigurationGrouo=Release` and go away from your computer for 40 minutes only to realize you built on Debug configuration. We should provide `--debug` and `--release` shortcuts like is done in [the `build.sh` script](https://github.com/dotnet/corefx/blob/master/build.sh#L10), as well as update the documentation/`--help` output. Then, we could call the script like this:

```cmd
build --release
```

Other things we might want to consider: `--skiptests[ bool]` (default false), `--buildtests[ bool]` (default true), `--buildpackages[ bool]` (default true)

cc: @mellinoe 

Note: I have knowledge of batch/shell scripting, so I can submit a PR to fix this myself if this is OK.

**edit:** Additionally we should echo the arguments that are being passed to MSBuild to the user, so they know right away if they made a typo.

**Comment by mellinoe** [comment]
I think if we add some options, we should try to match what is available in `build.sh`. TBH I'd prefer if both scripts took exactly the same arguments, minus platform-specific ones (cross, clang version, etc.). @maririos Any thoughts here?

**Comment by maririos** [comment]
Yes I agree that the cmd/sh scripts should be as similar as possible. The other dev workflow scripts (build-packages, build-tests, clean) are as similar as they can. We didn't wanted to change build.cmd too much by adding parsing commands logic but we could do that and have parity in build.cmd too.

**Comment by joperezr** [comment]
After some discussions, I think we'll hold off this change for @maririos work on her new dev workflow since she will touch all of this code eventually.

**Comment by wpostma** [comment]
Is build --help going to be among the options supported? That would be nice.

**Comment by maririos** [comment]
@jamesqo Thanks for your suggestions! With the implementation of the [Run Command Tool](https://github.com/dotnet/buildtools/blob/master/Documentation/RunCommand.md) in the dev workflow scripts we addressed your suggestions and more!

- [x] We should provide --debug and --release shortcuts like is done in the build.sh script
      =>Now we have `-debug` and `-release` for both build.cmd and build.sh

- [x] update the documentation/--help output
    => `-help` works in every dev workflow script and it is updated

- [x] We should echo the arguments that are being passed to MSBuild to the user 
     => We do it now

- [x] --skiptests, --buildtests, --buildpackages
     => `-skiptests`, `-buildtests` and `-buildpackages` are now available settings that you could pass to the build command. Also, we added the option `binaries` so if you do `build-managed.cmd -binaries` you would be able to build the product binaries without restoring packages, building/running tests and without building the packages. All in one :)

For more information about the changes we introduced with the Run Command Tool, please take a look at the [documentation](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md).

Thanks!
