### ISSUE TITLE
Sometimes Socket.Dispose() doesn’t trigger ws2_32!closesocket() in NanoServer

### ISSUE THREAD

**Issue by victorgu2001** [dotnet/corefx#9091]
I have a full SKU physical machine on which I created a Nanoserver virtual machine (i.e., VM). If I run below PowerShell command on physical machine twice, the second command sometimes will either hang or fail. This is due to the fact that Socket.Dispose() sometimes doesn’t trigger ws2_32!closesocket() in Nanoserver. Statistically the repro rate is about 50%, but for the same physical machine-VM pair, the repro rate seems to be either 0 or 100%.

New-PSSession -vmname <vm name> -credential <vm credential>

**Comment by CIPop** [comment]
@victorgu2001 It's unclear how your code is using CoreFX. 

The call to Socket.Dispose() is not guaranteed to call closesocket() in certain cases. See the complicated implementation at https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L5143.

To better understand this please provide the following:
1. An isolated repro of the Sockets pattern you are using. You could add a test to the System.Net.Sockets FunctionalTests within the repository.
2. [System.Net ETW ](https://github.com/dotnet/corefx/blob/master/Documentation/debugging/windows-instructions.md) traces in both the failing and passing modes.
3. Wireshark network capture traces in both the failing and passing modes.

**Comment by victorgu2001** [comment]
I no longer see this issue since 6/8/2016. Let's close this for now. I can re-activate it if I see it again.
