### ISSUE TITLE
System.IO.Compression ZipArchive improvements

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#9108]
I've been spending some time with zips and found our APIs lacking in a few places:
1. Cannot rename an entry, have to remove it and re-add-it
2. Cannot open multiple entries at once since they seem share the same underlying stream.
3. Cannot control the order/re-order entries in the zip

**Comment by danmosemsft** [comment]
This needs someone to write up a formal API proposal then we can review and if approved, offer up for implementation. Anyone?

Docs on the [API review process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md) and see [Jon's API request](https://github.com/dotnet/corefx/issues/4547) for a great example of a strong proposal. The more concrete the proposal is (e.g. has examples of usage, real-world scenarios, fleshed out API), the more discussion it will start and the better the chances of us being able to push the addition through the review process.

**Comment by carlossanlop** [comment]
Triage:
3.5 years old, only 1 external upvote. We don't think this is super needed and would be complicated.
