### ISSUE TITLE
VerifyCrlCache test failed in release branch: "Chain should not build validly"

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#9114]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_ubuntu14.04_debug_prtest/1/consoleText
```
     System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.VerifyCrlCache [FAIL]
        Chain should not build validly
        Expected: False
        Actual:   True
        Stack Trace:
           /mnt/j/workspace/dotnet_corefx/release_1.0.0/outerloop_ubuntu14.04_debug_prtest/src/System.Security.Cryptography.X509Certificates/tests/X509FilesystemTests.Unix.cs(58,0): at System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.VerifyCrlCache()
```

**Comment by bartonjs** [comment]
This very, very strongly suggests that it was a parallel execution problem on CI.

**Comment by stephentoub** [comment]
> This very, very strongly suggests that it was a parallel execution problem on CI.

As in a bug in the test, or as in an issue that multiple apps might hit when running on the same machine?

**Comment by bartonjs** [comment]
A requirement that the test has of operating by itself.  It first deletes the cache entry, and makes sure that everything is behaving "as expected" with no cache, then causes the cache to fill.  If anything else in/out-of-proc populates the cache between clean and test, it'll fail a precondition.

So, either test (it should be using resources unique to that test so no parallelism gets in the way) or infrastructure (no other build can have the same library running at the same time) bug; but not product.

**Comment by bartonjs** [comment]
Having not heard about this failing again I'm going to close it as an intermittent infrastructure issue.
