### ISSUE TITLE
System.IO.Compression perf tests failing on linux machines

### ISSUE THREAD

**Issue by dsgouda** [dotnet/corefx#9116]
When running the System.IO.Compression perf tests locally on a linux machine, a bunch for FileNotFoundExceptions show up

Eg.: System.IO.Compression.Tests/netcoreapp1.0/GZTestData/Canterbury/GZCompressed/grammar.lsp.gz not found

To repro the error:
On a linux machine, build the CoreFX repro and run the following command
```
Tools/corerun Tools/MSBuild.exe src/System.IO.Compression/tests/System.IO.Compression.tests.csproj /t:BuildAndTest /p:Performance=true /p:OSGroup=Linux
```

**Comment by ianhays** [comment]
Just the perf tests?

**Comment by stephentoub** [comment]
Can you add /p:XunitOptions="-parallel none -showProgress", and if it hangs, see which test started but didn't finish?

**Comment by ianhays** [comment]
@stephentoub did you mean to comment on https://github.com/dotnet/corefx/issues/9118?

**Comment by dsgouda** [comment]
@ianhays yes, it's just the perf tests
