### ISSUE TITLE
System.IO.Pipes perf tests never finish exection on linux machine

### ISSUE THREAD

**Issue by dsgouda** [dotnet/corefx#9118]
When running System.IO.Pipes perf tests on a linux machine, the tests seem to run infinitely and need to be killed/timed out 

To repro the error:
On a linux machine, build the CoreFX repo and run the following command

`Tools/corerun Tools/MSBuild.exe src/System.IO.Pipes/tests/System.IO.Pipes.tests.csproj /t:BuildAndTest /p:Performance=true /p:OSGroup=Linux`

**Comment by stephentoub** [comment]
Can you add  /p:XunitOptions="-parallel none -showProgress" , and if it hangs, see which test started but didn't finish?

**Comment by ianhays** [comment]
>Can you add /p:XunitOptions="-parallel none -showProgress"

Doesn't look like that works with the perf runner now. I don't see a way to pass args to the perf runner's invocation of the regular test runner:

```
Error: missing filename for -showProgress
   at Microsoft.Xunit.Performance.ProgramCore.ParseCommandLine(String[] args)
   at Microsoft.Xunit.Performance.ProgramCore.Run(String[] args)
```

**Comment by stephentoub** [comment]
I didn't realize a separate runner was used :(

**Comment by dsgouda** [comment]
@stephentoub yes we use a separate runner to execute the microbenchmark tests, I doubt if it is possible to repro the same issue without using the xunit performance runner
@brianrob Can you confirm this

**Comment by brianrob** [comment]
It is possible to run the benchmarks using xunit as opposed to xunit-performance.  The main differences are that (a) no performance metrics will be collected and (b) the test will only run 1 iteration.

**Comment by ianhays** [comment]
Do these still run? I'm getting an error:

  D:\git\corefx\Tools\PerfTesting.targets(41,5): error : Xunit performance package was not found [D:\git\corefx\src\System.IO.Pipes\t
ests\Performance\System.IO.Pipes.Performance.Tests.csproj]

**Comment by dsgouda** [comment]
@brianrob can you ask someone from perf to take a look

**Comment by brianrob** [comment]
To my knowledge, these still run.  This sounds like more of a build issue.

**Comment by dsgouda** [comment]
We used to be able to run perf tests locally using the build targets under CoreFX, I am not sure if this is true today, someone from perf may have to take a look

**Comment by stephentoub** [comment]
Performance tests have been moved to dotnet/performance and rewritten, and I'm not aware of any hangs (cc: @adamsitnik).  As such, I'm closing this.  We can re-open if it's still detected as an issue.

**Comment by adamsitnik** [comment]
System.IO.Pipes.PerformanceTests benchmarks were ported in https://github.com/dotnet/performance/pull/108 and now are available at https://github.com/dotnet/performance/tree/master/src/benchmarks/micro/corefx/System.IO.Pipes

They work fine on every OS and every architecture and we have a CI that verifies that https://github.com/dotnet/performance/#micro-benchmarks
