### ISSUE TITLE
HttpClient.GetAsync throws an exception, if server response has more than one"WWW-Authenticate: Basic" header with different realm

### ISSUE THREAD

**Issue by stiliev** [dotnet/corefx#9124]
HttpClient.GetAsync throws an exception, if server response has more than one "WWW-Authenticate: Basic" header with different realms. The sample client code is:
`

                var handler = new HttpClientHandler();                                
                handler.UseDefaultCredentials = false;
                handler.Credentials = System.Net.CredentialCache.DefaultCredentials;

                handler.AllowAutoRedirect = true;

                using (var client = new HttpClient(handler))
                {
                        client.BaseAddress = new Uri("type you server URI here");
                        HttpResponseMessage response = await client.GetAsync("api/values");
                }
`
Same code works fine under desktop .Net framework.
The exception call stack is:

System.Net.Http.HttpRequestException:

 An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The operation identifier is not valid
   at System.Net.Http.WinHttpAuthHelper.CheckResponseForAuthentication(WinHttpRequestState state, UInt32& proxyAuthScheme, UInt32& serverAuthScheme)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__101.MoveNext()
  --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApplication.Program.<doGet>d__1.MoveNext() in D:\prj\repro_ntlm_integrated\Client\Program.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ConsoleApplication.Program.<doTest>d__0.MoveNext() in D:\prj\repro_ntlm_integrated\Client\Program.cs:line 28

Below is fiddler trace:

> 
GET http://stiliev-dev/WebApplication2/api/values HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate, peerdist
Connection: Keep-Alive
X-P2P-PeerDist: Version=1.1
X-P2P-PeerDistEx: MinContentInformation=1.0, MaxContentInformation=2.0
Host: stiliev-dev

> 
HTTP/1.1 401 Unauthorized
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
Server: Microsoft-IIS/10.0
X-AspNet-Version: 4.0.30319
WWW-Authenticate: Basic realm="http://stiliev-dev:8080/tfs"
WWW-Authenticate: Basic realm="http://stiliev-dev:8080"
WWW-Authenticate: Negotiate
WWW-Authenticate: NTLM
X-Powered-By: ASP.NET
Date: Fri, 03 Jun 2016 14:50:44 GMT
Content-Length: 61
{"Message":"Authorization has been denied for this request."}

**Comment by joshfree** [comment]
A few questions -- 

@davidsh @CIPop @stephentoub  what is the risk of this fix?  Given it's a regression in behavior from .NET 4.x I think we'd still consider it during this week of escrow.  We still have a few other changes we need to take such as https://github.com/dotnet/corefx/issues/9040 and https://github.com/dotnet/corefx/issues/9072.

@stiliev are you able to workaround this if the fix does not make it into 1.0?

**Comment by joshfree** [comment]
marking this as 1.0.0-rtm while the issue is being investigated

**Comment by davidsh** [comment]
@joshfree I have no idea of the risk.  I have not investigated it.  And I won't be able to for a few days since I have other high priority work.

**Comment by stiliev** [comment]
@joshfree We have not found any workaround. We have this use case in our TFS build automation agent that is part of the DevDiv Dev15.
@bryanmacfarlane

**Comment by joshfree** [comment]
@ericeil can you please investigate today and report back?

**Comment by ericeil** [comment]
It looks like the error comes from the underlying native WinHttp implementation.  I get the same `ERROR_INVALID_OPERATION` code when I use the sample native code from the [WinHttpQueryAuthSchemes docs](https://msdn.microsoft.com/en-us/library/windows/desktop/aa384100(v=vs.85).aspx).

**Comment by bryanmacfarlane** [comment]
it works with our previous windows agent using .net desktop.  So at a minimum, a compat, porting blocker

**Comment by ericeil** [comment]
> it works with our previous windows agent using .net desktop. So at a minimum, a compat, porting blocker

Agreed; I also verified that this works on the full CLR.  I don't think the full CLR uses WinHttp, which would explain the difference.

I experimented a bit with the native `WinHttpQueryAuthSchemes` sample, but I was unable to find anything I could do at the native level to make this work.  @davidsh may have some ideas here, but to me this looks like it's just a limitation of WinHttp, which is going to make it very unlikely that we can fix this quickly.

**Comment by davidsh** [comment]
@ericeil Please send me the C++ WinHTTP repro you have.  I can open up a bug with the WinHTTP team.

**Comment by joshfree** [comment]
Tagging this as `release notes` as we should at a minimum include information on this scenario in the 1.0 Known Issues.

**Comment by bryanmacfarlane** [comment]
In parallel, we're figuring out what we can do from the server side

**Comment by davidsh** [comment]
Ref: Internal tracking number; 7841095

**Comment by ericeil** [comment]
Added this to the release notes for 1.0 RTM.  Moving this tracking issue to 1.1.

**Comment by ericeil** [comment]
See also: https://github.com/Microsoft/vsts-agent/issues/326#issuecomment-228010379

Doesn't appear to be anything CoreFx can do here.  Closing this issue.
