### ISSUE TITLE
Add greater validation to HttpClient SSL cerificate validation

### ISSUE THREAD

**Issue by blowdart** [dotnet/corefx#9127]
Add more checks in addition to the host name, validity periods and chaining to trusted roots.

**Comment by davidsh** [comment]
We should also consider if SslStream should be enhanced as well.

And in terms of HttpClient, those enhancements would have to be at the native OS level (WinHTTP for Windows, Curl for *Nix).

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by karelz** [comment]
@davidsh can you please share your offline discussion with the v-team.

**Comment by CIPop** [comment]
Fixed by #19622.
