### ISSUE TITLE
Remove uses of Console.WriteLine in the Unit Tests?

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#915]
A bunch of our unit tests do `Console.WriteLine` either on regular paths or on error cases.  By my count there's bout 1600 hits for `Console.Write*` in our tests.  This is a bit of an over-count because some of these are the Console tests themselves.

I don't really like this very much.  It feels like something we inherited when porting our legacy test assets.  Is it worthwhile to go clean this up?  I don't mind doing the work, just don't want to put in a bunch of effort if it doesn't stand a chance of getting merged.

I'm sure @nguerrera will be interested in this and my understanding was @davkean had some guidance on how to author and port tests and I'd be interested in understanding how this aligns with his thinking.

**Comment by davkean** [comment]
Agreed with this. A good example of this was what we did with the File IO tests. We ripped all logging that was non-essential and just noise, and moved logging that added value only to the failure case.

**Comment by nguerrera** [comment]
Strongly agree too. I got them down to zero at [one point], but folks keep adding them back with each new library. :(

[one point]: https://github.com/dotnet/corefx/pull/456

**Comment by ellismg** [comment]
The real issue here really is that all of our tests were not written with xUnit in mind.  As we do this, we should make sure that if the output of the test was useful then it's captured in some other way (e.g an assert with a good message).

**Comment by gregoryyoung** [comment]
I was getting ready to send a PR in this area but want to make sure this is what is being refered to:

https://github.com/dotnet/corefx/blob/master/src/System.IO.MemoryMappedFiles/tests/MemoryMappedFile/CreateViewAccessor.cs#L501

If so I'll get together the PR

Cheers,

Greg

**Comment by ellismg** [comment]
@gregoryyoung, Yes.  I would expect in cases like what you had here we would just let the unexpected exception go unhandled, and xUnit would catch it and give a nice message.

**Comment by gregoryyoung** [comment]
OK just wanted to check..

Cheers,

Greg

**Comment by gregoryyoung** [comment]
In looking through some are simple some are less so.

As an example here https://github.com/gregoryyoung/corefx/blob/master/src/System.IO.MemoryMappedFiles/tests/MemoryMappedViewStream/ReadWrite.cs

It appears the reason why they are printing is that basically all the tests are being done in a single method (I guess its expected that you would go read the output).

If you just mechanically change this you will also get some pretty annoying behaviour in trying to run this if its broken (first exception stops all tests).

Is the idea to just remove the writelines here or to refactor the entire fixure to remove such issues?

**Comment by tarekgh** [comment]
@tarekgh

**Comment by stephentoub** [comment]
Very few WriteLines appear in test output at this point.  We can close this and fix any we see reactively.
