### ISSUE TITLE
HttpClient and PreAuthenticate

### ISSUE THREAD

**Issue by jmurphzyo** [dotnet/corefx#9155]
I am just curious why PreAuthenticate has never worked as expected. On several occasions when I am using Server to Server auth the nounce needs to stay the same on consecutive request  but with the way HttpClient behaves I cannot implement that.

**Comment by davidsh** [comment]
Can you please provide more details? What sort of project?  Is this is a Windows UWP app or ASP.NET app or Linux etc.?  Can you provide a small repro solution?  Thx.

**Comment by jmurphzyo** [comment]
@davidsh David I solved the issue by writing a helper class. It was more ignorance on my part of how to setup credential cache.
