### ISSUE TITLE
 'Cyrillic' is not a supported encoding name.

### ISSUE THREAD

**Issue by tugberkugurlu** [dotnet/corefx#9158]
When I run this:

```
Encoding.GetEncoding("Cyrillic");
```

I am now getting this:

```
Unhandled Exception: System.ArgumentException: 'Cyrillic' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at System.Globalization.EncodingTable.GetCodePageFromName(String name)
   at System.Text.Encoding.GetEncoding(String name)
   at ConsoleApplication.Program.Main(String[] args)
```

which wasn't the case before, it started happening in RC2.

dotnet CLI:

```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
```

project.json

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },
  "dependencies": {
    "Microsoft.Extensions.DependencyModel": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final",
    "Microsoft.Extensions.Options": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.Binder": "1.0.0-rc2-final",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0-rc2-final",
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002702"
    }
  },
  "frameworks": {
    "netcoreapp1.0": { 
      "imports": "portable-net45+wp80+win8+wpa81+dnxcore50"
    }
  }
}

```

**Comment by tarekgh** [comment]
Please have a look at Remarks section in the following doc:

```
https://msdn.microsoft.com/en-us/library/mt643901(v=vs.110).aspx

```

and apply the suggested steps:

```
- Add a reference to the System.Text.Encoding.CodePages.dll assembly to your project.
- Retrieve a CodePagesEncodingProvider object from the static CodePagesEncodingProvider.Instance property.
- Pass the CodePagesEncodingProvider object to the Encoding.RegisterProvider method.

```

This should make everything work. 

I am going to close the issue, please feel free to respond back or re-open it if you have any follow up question of anything didn't work. 

Thanks.

**Comment by akoeplinger** [comment]
@tarekgh seems the [docs for the Instance property](https://msdn.microsoft.com/en-us/library/system.text.codepagesencodingprovider.instance(v=vs.110).aspx) of the CodePagesEncodingProvider in .NET Framework were copied from the UWP version, but references to UWP incorrectly replaced. This leads to gems such as:

> makes encodings available to .NET Framework 4.6 apps that otherwise are available only in the .NET Framework on the Windows desktop.

or 

> an encoding that is present in the .NET Framework on the Windows desktop but not in .NET Framework 4.6

... which seems a bit inaccurate 😄 

Where's the best place to file those MSDN doc bugs?

**Comment by tarekgh** [comment]
@akoeplinger thanks for pointing at that. I'll forward this issue to the doc team.

**Comment by tarekgh** [comment]
CC @rpetrusha from the doc team

**Comment by tarekgh** [comment]
@akoeplinger just FYI, https://github.com/dotnet/core-docs is the repro for the doc issue. I'll let @rpetrusha handle this issue if he want to create a new issue on the core-docs repo

**Comment by rpetrusha** [comment]
@akoeplinger Thanks for pointing this out. I'm investigating how we can address this issue. In the meantime, this is stale content that is no longer being maintained. The current version of the CodePagesEncodingProvider class is found at https://msdn.microsoft.com/en-us/library/mt643901(v=vs.111).aspx and (for the Instance property) https://msdn.microsoft.com/en-us/library/mt643899(v=vs.111).aspx.

**Comment by akoeplinger** [comment]
Thanks! As long as we get if fixed/redirected to the proper page I'm fine :)

**Comment by miikkaa** [comment]
Had the same issue. Had to provide the explicit `4.3.0` version for `System.Text` in `project.json`:

```
"System.Text.Encoding": "4.3.0",
"System.Text.Encoding.CodePages": "4.3.0",
"System.Text.Encoding.Extensions": "4.3.0"
```

And then registered the provider in `Startup.cs` ([as suggested on StackOverflow](http://stackoverflow.com/a/33579717/186787)):

`Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);`
