### ISSUE TITLE
[release/1.0.0] LoadFromAssemblyName failed - could not load System.Runtime

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#9166]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/release_1.0.0/job/opensuse13.2_debug_tst/75/consoleFull#-21371504001f1a4601-6aec-4fd5-b678-78d4389fd5e8

> 07:44:46    System.Runtime.Loader.Tests.AssemblyLoadContextTest.LoadFromAssemblyName_ValidTrustedPlatformAssembly [FAIL]
07:44:46       System.IO.FileLoadException : Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
07:44:46       Stack Trace:
07:44:46 Finished:    System.Runtime.Serialization.Formatters.Tests
07:44:46 
07:44:46 === TEST EXECUTION SUMMARY ===
07:44:46    System.Runtime.Serialization.Formatters.Tests  Total: 4, Errors: 0, Failed: 0, Skipped: 0, Time: 0.638s
07:44:47             at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
07:44:47             at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
07:44:47             at System.Runtime.Loader.Tests.CustomTPALoadContext.Load(AssemblyName assemblyName)
07:44:47             at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
07:44:47             at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
07:44:47             at System.Runtime.Loader.Tests.AssemblyLoadContextTest.LoadFromAssemblyName_ValidTrustedPlatformAssembly()
07:44:47 Finished:    System.Runtime.Loader.Tests
07:44:47 Finished running tests. End time=14:45:53. Return value was 0

**Comment by gkhanna79** [comment]
@joshfree This should not be unique to open-suse. It seems like the CoreCLR package used for Open-Suse does not have https://github.com/dotnet/coreclr/commit/58a45de30d6ee7d61510968f34569832c0a40dbe#diff-8bc86ef9cf95adfc911933f21b5530cc change but is using CoreFX build that has https://github.com/dotnet/corefx/commit/6c8088a07034e979619bfc6db80fa21930ce73d4#diff-f83ac88aa51d019559710c3404c9322c change.

@ellismg Can you please look into this? It sounds like a configuration issue since the RTM port PR (https://github.com/dotnet/corefx/pull/9038) was clean.

**Comment by gkhanna79** [comment]
From failing job above, the details of the commit that triggered it are at http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/release_1.0.0/job/opensuse13.2_debug_tst/75/. Per this link, the commit in question (which triggered the job) is https://github.com/dotnet/corefx/commit/1caac18fd7e1c7f122d7807bfbe5202f616ff3d1and associated PR is https://github.com/dotnet/corefx/pull/9146. 

The PR is clean for Windows/OSX/Ubuntu - a product failure would have failed them as well. @ellismg I will assign this to you to look into further. Please let me know if you find this to be product issue.

**Comment by ellismg** [comment]
Now that we are consuming stuff from packages instead of copying stale live bits, this is resolved.
