### ISSUE TITLE
[release/1.0.0] investigate Nano Server 2016 CI failures

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#9168]
Nano Server has been failing pretty regularly in outerloop runs.  Please investigate.

**Comment by Priya91** [comment]
The serviceprocess failures have been fixed. The SecureString tests are failing because winapi, ```RtlZeroMemory``` is not found in kernel32.dll.

**Comment by joshfree** [comment]
This should now be fixed with https://github.com/dotnet/coreclr/pull/5580

**Comment by Priya91** [comment]
builds are passing, closing.
