### ISSUE TITLE
VS2015 cannot debug after changing project.json to be selfcontained. 

### ISSUE THREAD

**Issue by emailtowalter** [dotnet/corefx#9182]
followed the guide on this link "http://dotnet.github.io/docs/core-concepts/app-types.html", and publish the windows and ubuntu images. They both work fine. 

But in the VS2015, when I try to debug the app using kestrel, it gaves me a error "unable to attach to coreclr. a debug component is not installed". Never seen it before I change to self-contained app.

**Comment by joshfree** [comment]
@mikem8361 @tzwlai @sergiy-k

**Comment by mikem8361** [comment]
@gregg-miskelly, @caslan do you guys think this is the runtime or the VS support?

**Comment by gregg-miskelly** [comment]
This error message is coming from the CLR:

    <HRESULT NumericValue="0x80131c3c">
      <SymbolicName>CORDBG_E_DEBUG_COMPONENT_MISSING</SymbolicName>
      <Message>"A debug component is not installed."</Message>
      <Comment>A debug component is not installed</Comment>
    </HRESULT>

**Comment by gregg-miskelly** [comment]
@emailtowalter Two questions:

1. What are you doing to debug them? (ex: Hit F5 on a project.json-based project, Manually try and launch the exe, attach to the process. etc).
2. If you look at the files next to the app, do you see a mscordaccore.dll and a mscordbi.dll?

**Comment by emailtowalter** [comment]
Cannot do it now. Later today. Thanks, guys for for quick action .

**Comment by emailtowalter** [comment]
@gregg-miskelly : 1) it is normal debug. you are right. F5 on project.json based project. I do not have other ones. 2) Assuming you meant the debug folder. There is no system DLL like, system. or microsoft. there at all. It is different if I publish to the app to a publish folder. 

Does it help?

**Comment by joshfree** [comment]
> It is different if I publish to the app to a publish folder.

Can you clarify this statement?  how is it different?  does it succeed or is there a different error?

**Comment by emailtowalter** [comment]
Publishing works. There are many more system DLL in the publish folder.
