### ISSUE TITLE
Allow CookieContainer to be Serialized/Deserialized

### ISSUE THREAD

**Issue by himadrisarkar** [dotnet/corefx#9184]
Currently, serialization and deserialization of the CookieContainer doesn't work. The documentation says to use the CookieContainer if one needs to save off HttpOnly cookies. It seems that saving the CookieContainer isn't possible.
"If the server sends HTTPOnly cookies, you should create a System.Net.CookieContainer on the request to hold the cookies, although you will not see or be able to access the cookies that are stored in the container."
We should look at providing support for CookieContainer class to have XML serialization.

**Comment by stil** [comment]
Are there any temporary workarounds? This issue and lack of BinaryFormatter stops me from migrating my project to .NET Core

**Comment by swimtver** [comment]
This workaround is work for me. 
Json.net is very helpfull.
``` csharp
public class CookieContainerSerializer
    {
        private readonly JsonSerializerSettings _settings = new JsonSerializerSettings
        {
            ContractResolver = new PrivateFieldsContractResolver(),
            Converters = new List<JsonConverter> {new CookieCollectionConverter()},
            DateFormatHandling = DateFormatHandling.IsoDateFormat,
        };
        public string Serialize(CookieContainer container) => Json.Serialize(container, Formatting.None, _settings);
        public CookieContainer Deserialize(string value) => Json.Deserialize<CookieContainer>(value, _settings);
        private object GetCookiesTable(CookieContainer container)
        {
            const BindingFlags bindFlags = BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic
                                           | BindingFlags.Static;
            var field = container.GetType().GetField("_domainTable", bindFlags);
            return field?.GetValue(container);
        }
        class CookieCollectionConverter : JsonConverter
        {
            public override bool CanWrite => false;
            public override bool CanConvert(Type objectType) => objectType == typeof(CookieCollection);
            public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
            {
                throw new NotImplementedException("this implementation isn't necessary.");
            }
            public override object ReadJson(JsonReader reader, Type oType, object value, JsonSerializer serializer)
            {
                var list = serializer.Deserialize<Cookie[]>(reader);
                var collection = new CookieCollection();
                for (var i = 0; i < list.Length; i++)
                    collection.Add(list[i]);
                return collection;
            }
        }
        class PrivateFieldsContractResolver : DefaultContractResolver
        {
            protected override IList<JsonProperty> CreateProperties(Type type, MemberSerialization memberSerialization)
            {
                if (type == typeof(Cookie) || type == typeof(CookieCollection) ||
                    type == typeof(SortedList<string, CookieCollection>))
                    return base.CreateProperties(type, memberSerialization);
                var fields = type.GetFields(BindingFlags.NonPublic | BindingFlags.Instance)
                    .Select(f => CreateProperty(f, memberSerialization)).ToList();
                fields.ForEach(p =>
                {
                    p.Writable = true;
                    p.Readable = true;
                });
                return fields;
            }
        }
    }
```

**Comment by CIPop** [comment]
@karelz, @danmosemsft @weshaggard I noticed that the `[Serializable]` attributes have not been ported to Standard. 

What is the current recommendation for serialization in .Net Core? What changes would be needed to allow serialization of `CookieContainer` (Serializable in .Net Framework)?

**Comment by danmosemsft** [comment]
Current recommendation is: where something was binary serializable in full framework, we want it to be binary serializable in Core. There are a few cases where we didn't eg it was too expensive and couldn't be simply ported from full framework.

**Comment by danmosemsft** [comment]
> [Serializable] attributes have not been ported to Standard.

We don't put those on the ref assemblies (except by accident) as they're not part of the API signature. I see CookieCollection implementation has [Serializable]: https://github.com/dotnet/corefx/blob/master/src/System.Net.Primitives/src/System/Net/CookieCollection.cs#L16 but perhaps it doesn't work. If that's the case we're missing a test for it and really should fix that.

**Comment by CIPop** [comment]
> We don't put those on the ref assemblies (except by accident)

Wasn't aware of this and I see that the impl has the attribute so it may already work.

> If that's the case we're missing a test for it and really should fix that.

I agree. @karelz, @davidsh we may want to consider this test gap for 2.0.

(Removed HTTP: The type is in S.N.Primitives.)

The work required here is to add a serialization/deserialization test for `CookieContainer` in `SerializationTest.cs`.

**Comment by karelz** [comment]
We do not use the netstandard2.0 label anymore. If we believe it is must-have for 2.0, let's use milestone. Otherwise Future.

**Comment by CIPop** [comment]
> We do not use the netstandard2.0 label anymore.

Having the label as an option is confusing. Do you have permissions to remove the label (and ensure that all 11 remaining issues labeled this way are moved to milestone:2.0)?

**Comment by davidsh** [comment]
I added a new test for validating serialization roundtrip for CookieContainer (a very simple test):

And it failed.

>     System.Net.Primitives.Functional.Tests.SerializationTest.SerializeDeserialize_Roundtrip(obj: CookieContainer { Capacity = 300, Count = 0, MaxCookieSize =
  4096, PerDomainCapacity = 20 }) [FAIL]
        Assert.Equal() Failure
        Expected: CookieContainer { Capacity = 300, Count = 0, MaxCookieSize = 4096, PerDomainCapacity = 20 }
        Actual:   CookieContainer { Capacity = 300, Count = 0, MaxCookieSize = 4096, PerDomainCapacity = 20 }
        Stack Trace:
           s:\GitHub\corefx\src\System.Net.Primitives\tests\FunctionalTests\SerializationTest.cs(26,0): at System.Net.Primitives.Functional.Tests.Serialization


So, there is something missing in the product code regarding supporting serialization for `CookieContainer`.

**Comment by karelz** [comment]
Flipping to 'bug' in that case ...

**Comment by davidsh** [comment]
More interesting...running this new test against NETFX (Desktop) fails also:

>Msbuild /t:rebuildandtest /p:TargetGroup=netfx

**Comment by stephentoub** [comment]
Does CookieContainer override Equals or implement IEquatable?  Assuming not, Assert.Equal will fail as it's comparing two distinct references.

**Comment by davidsh** [comment]
`CookieContainer` does NOT implement `Equals` nor `IEquatable`.  In addition, it doesn't implement those things on .NET Framework either.

And yet, it is marked as `[Serializable]`.

So, what does it mean to mark it that way but not provide the proper equality overrides?

**Comment by davidsh** [comment]
The same can be said for `CookieCollection`.  And yet, it seems to pass some of these tests on .NET Core.  Yet, writing the same "test" on .NET Framework fails the equality test.

**Comment by stephentoub** [comment]
> what does it mean to mark it that way but not provide the proper equality overrides?

I don't understand. Serialization and equality are two completely different things. The type is serializable, but you obviously get back different instances. Whether the type then implements equality checks to show you to compare two instances is unrelated. This is at the very least a test bug: if you want to compare the instances, you'll need to write your own equality check for whatever you define as equality of two containers.

**Comment by stephentoub** [comment]
> The same can be said for CookieCollection

Assert.Equal special-cases enumerables.

**Comment by davidsh** [comment]
>I don't understand. Serialization and equality are two completely different things. ...This is at the very least a test bug:

Good point.

It means that the current `SerializationTest` we have:

```c#
        [Theory]
        [MemberData(nameof(SerializeDeserialize_Roundtrip_MemberData))]
        public static void SerializeDeserialize_Roundtrip(object obj)
        {
            Assert.Equal(obj, BinaryFormatterHelpers.Clone(obj));
        }
```

is bad.  It is not testing serialization.  But really round-trip equality.  For which the types are set up for that.  So, this test needs to be re-written.

**Comment by stephentoub** [comment]
> is bad

How is it bad? Yes, it only works for types that supply their own definition of equality. A separate test is needed for other types that don't.

**Comment by davidsh** [comment]
At the very least, the current test is confusing and not well documented as to the real purpose (I was confused). :)
