### ISSUE TITLE
Introduce Gentoo Linux RID and a job in CI matrix

### ISSUE THREAD

**Issue by ghost** [dotnet/corefx#9187]
The current master branches of CoreCLR and CoreFX native builds on Gentoo Linux. I have compiled the steps to create a Gentoo LXC container on Ubuntu 14 with list of dependencies required for the said repos: https://gist.github.com/jasonwilliams200OK/1a2e2c0e904ffa95faf6333fcd88d9b8.

Please assign an RID for Gentoo Linux and add CI job to continuously monitor its build status.

Thanks! :)

**Comment by karelz** [comment]
Our plan for build-from-source should mitigate it.
It is still unlikely we will add a lot of distros (especially those moving super-fast) - we will likely rely on distros owners/maintainers to build for it.
