### ISSUE TITLE
Improve code coverage for Microsoft.Win32.Registry

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#919]
According to the current code coverage report, this library is only at 77%.  Our general goal is closer to 90%, though this will depend on the library.  We should investigate to see whether the current coverage level is appropriate, and if not, improve our test suites to provide better coverage.

**Comment by danmosemsft** [comment]
It's at 83% now and the missing coverage is in relatively little used parts. I think we can focus elsewhere.
