### ISSUE TITLE
Marshal.ZeroFreeGlobalAllocUnicode fails with entrypoint not found

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#9198]
The ```Marshal.ZeroFreeGlobalAllocUnicode``` calls in ```RtlZeroMemory``` in ```kernel32.dll```, and this throws entry point not found error in Windows Nano Server 2016. ```kernel32.dll``` is not available in onecore profile except as a forwarder.

```
 System.Security.Tests.SecureStringTests.Clear(initialValue: "test") [FAIL]
    System.EntryPointNotFoundException : Unable to find an entry point named 'RtlZeroMemory' in DLL 'kernel32.dll'.
    Stack Trace:
          at Microsoft.Win32.Win32Native.ZeroMemory(IntPtr address, UIntPtr length)
          at System.Runtime.InteropServices.Marshal.ZeroFreeGlobalAllocUnicode(IntPtr s)
          at System.Security.Tests.SecureStringTests.CreateString(SecureString value)
          at System.Security.Tests.SecureStringTests.AssertEquals(String expected, SecureString actual)
          at System.Security.Tests.SecureStringTests.Clear(String initialValue)
```

**Comment by joshfree** [comment]
@botaberg @sergiy-k

**Comment by joshfree** [comment]
@Priya91 even though this is technically owned by another team, feel free to start looking into a potential fix.

**Comment by yizhang82** [comment]
This is the failing CI: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_winnano16_debug_tst/14/#showFailuresLink

**Comment by yizhang82** [comment]
It looks like x64 version of System.Private.CoreLib.dll is coming from dlab-DDVSOWINAGE002 and it is not built correctly. ProjectKRel versions are correct. Some post-processing is needed to rewrite kernel32!RtlZeroMemory to ntdll!RtlZeroMemory, and for whatever reason dlab-DDVSOWINAGE002 is skipping that.
