### ISSUE TITLE
HttpClient PostAsync - The server returned an invalid or unrecognized response

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/corefx#9201]
EDITED:

If I run this application on a Windows computer everything works out fine. When I run this application on a Linux (CentOS) computer I get the following exception:

> System.Net.Http.HttpRequestException: The server returned an invalid or unrecognized response. at System.Net.Http.CurlResponseHeaderReader.ReadHeader(String& headerName, String& headerValue) at System.Net.Http.CurlHandler.MultiAgent.CurlReceiveHeadersCallback(IntPtr buffer, UInt64 size, UInt64 nitems, IntPtr context) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 

I've tried this code on a Windows machine and it is working perfectly. I've also tried to make a SOAP call on CentOS console trough curl and it also works fine (I get the response). In the web application I keep getting the exception saying that the server returned an invalid or unrecognized response.

This is the code - Exception thrown right on the hc.PostAsync().

            Uri uri = new Uri(ServiceConfiguration.SERVICE_URL);

            string sSOAPResponse = String.Empty;

            HttpClient hc = new HttpClient();

            hc.DefaultRequestHeaders.Add("SOAPAction", oRequest.Action);
            
            var content = new StringContent(oRequest.RequestMessage, Encoding.UTF8, "text/xml");

            try
            {
                using (HttpResponseMessage response = await hc.PostAsync(uri, content))
                {

                    sSOAPResponse = await response.Content.ReadAsStringAsync();
                    (...)
                 }
`

## Steps to reproduce
Call post async method with HttpClient on a Linux Server (CentOS 7.1 My case)

## Expected  behavior
Get the SOAP response (Works perfectly on Windows).

## Actual behavior
The server returned an invalid or unrecognized response thrown.

## Environment data

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64

Moved from https://github.com/dotnet/cli/issues/3344 on behalf of @RicardoRazz as this seems to be an HttpClient issue in the RC2 release of Shared Framework.

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by stephentoub** [comment]
@RicardoRazz, do you have a standalone repro I can try? Or at least a url I can try hitting with your snippet? We have a bunch of tests passing on CentOS using PostAsync, so I suspect this is something specific to the response the server is sending back, and in particular it may be sending a header we're having trouble parsing. Alternatively, can you share the full response, including headers, you get back when using curl?

**Comment by RicardoRazz** [comment]
Hi @stephentoub. First of all thank you very much for your reply. At the moment I do not have an avaliable URL but here's my curl example:

This is the command I sent in:

> [root@su soaptest]# curl --header "Content-Type: text/xml;charset=UTF-8" --header "SOAPAction:ping" --data @request.xml http://application.com/api/service.php

Response sucessfully received (hello there):

`
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/">
	<SOAP-ENV:Body>
		<ns1:pingResponse xmlns:ns1="http://schemas.xmlsoap.org/soap/envelope/"><return xsi:type="xsd:string">hello there</return>
		</ns1:pingResponse>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>`

Then I've sent this command to get the headers:

> [root@su soaptest]# curl -I http://application.com/api/service.php

And this is the response I get:

> HTTP/1.1 200 OK
> Date: Tue, 07 Jun 2016 01:21:20 GMT
> Server: Apache/2.4.6 (CentOS)
> X-Powered-By: PHP/5.4.16
> Access-Control-Allow-Headers: SOAPAction,Content-Type
> Access-Control-Allow-Origin: *
> Access-Control-Allow-Methods : POST,GET,OPTIONS
> Connection: close
> Content-Type: text/html; charset=utf-8

Just if you need, this is my request.xml:

`<soapenv:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/X$
   <soapenv:Header/>
   <soapenv:Body>
      <ping soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
      </ping>
   </soapenv:Body>
</soapenv:Envelope>
`

**Comment by stephentoub** [comment]
I believe the problem is here:
```
Access-Control-Allow-Methods : POST,GET,OPTIONS
```
Our unix implementation is throwing at the extra space between the header name and the colon.

**Comment by stephentoub** [comment]
@RicardoRazz, what's generating these headers?  Is it your code or is it from some common server?

I may be interpreting it incorrectly, but the RFC at https://tools.ietf.org/html/rfc7230 states:
```
Each header field consists of a case-insensitive field name followed
   by a colon (":"), optional leading whitespace, the field value, and
   optional trailing whitespace.
```
which suggests that whitespace between the field name and the colon is not allowed, since it calls out optional space both before and after the value but not after the field name.

@davidsh, it seems we're being more strict here than is WinHttp in parsing the headers.  Am I misinterpreting the spec?  Would you recommend we make it more lenient?

**Comment by stephentoub** [comment]
cc: @justinvp

**Comment by davidsh** [comment]
@stephentoub 
>it seems we're being more strict here than is WinHttp in parsing the headers. Am I misinterpreting the spec? Would you recommend we make it more lenient?

Yes, you should be more lenient.  The RFC is useful.  And in general, the guiding principle in networking is "be liberal in what you read...be strict in what you write".

Both WinHTTP and Wininet more so, have to work with many web servers that have "issues".  So, over time, a lenient policy was developed for some things like certain whitespace between end of header name and colon.

The best rule of thumb is that if it works in WinHTTP and Wininet, then it is probably a good rule to follow in terms of parsing behavior.

**Comment by RicardoRazz** [comment]
@stephentoub you were right it was the space on

> Access-Control-Allow-Methods : POST,GET,OPTIONS

This was defined on my API PHP main page (service.php). 

Thank you very much for this. I was able to run my MVC project on CentOS as so far it is working great.
