### ISSUE TITLE
string.IndexOf not giving correct index

### ISSUE THREAD

**Issue by conniey** [dotnet/corefx#9202]
## Repro Steps
1. Copy code below
2. Run code

``` csharp
namespace TestApp
{
    class Program
    {
        static void Main(string[] args)
        {
            var sentence = "\uDAD1²\uDF8F 㽜|";
            var index = sentence.IndexOf(sentence);
            Console.WriteLine("index: {0}", index);

            if (index == 0)
            {
                 Console.WriteLine("It works!");
            }
            else
            {
                 throw new InvalidOperationException("Expected that it is 0");
            }
        }
    }
}
```
## Expected

`index` is equal to 0.
## Actual

An InvalidOperationException is thrown because `index` is equal to 1.

**Comment by ellismg** [comment]
Two questions:

1) What Platform are you hitting this on?
2) Is it possible for you to replace the characters in sentence with their Unicode codes `\uXXXX` so it's clear exactly what's going into that string?

**Comment by conniey** [comment]
1. I tried it on .NET Frameworks: 4.0, 4.5.2 and 4.6
2. I updated the example.

**Comment by jasonwilliams200OK** [comment]
I have reduced this issue to:

These work:

```c#
var sentence = "²\uDAD1";
var sentence = "²";
var sentence = "\uDAD1";
```

But this doesn't:

```c#
 var sentence = "\uDAD1²";
```

Using dotnet-cli NetCoreApp1.0.

Also tested with online Mono:

Passes: https://ideone.com/8sI3ka
Fails: https://ideone.com/PUSkSv

Also checked that the Roslyn decompiles the same IL for both codes (select IL from top-right dropdown):

Passes: http://tryroslyn.azurewebsites.net/#b:future/f:%3Eil/K4Zwlgdg5gBAygTxAFwKYFsDcAobECG6qIADvgMaowAqxyAgiSdgN7YwczkA2+IIMAAoAnAPZRhhdpzac5MFPmRhyMAG6iwAExgBZfJAAUKYZCgBtALox8wqCACU0+TFkv5a2wtQQ0ESjAAvDAARABNADrAACL00QCMITjuHl6QWqgAHkHevj6UAHQAkhAZmQDyAGbGPn6UDskpnADCohAgotyoBQDqpmgAMpCohiHpWQBcrgAMAL4hADQw45kNuE2cYJUwhitBwdNOGxxux3Kt7Z3dfWCDw6NFyDAA7qLCANYgAIQha2ezziaqG4IFQgJSpzOHGQAAsxM8YBBUAiSp5uNpyiRUJJlG0AKKZSgkXEQUYErHkNA6WFKZZPMACaa/RobAEpNmcAGzIA===

Fails: http://tryroslyn.azurewebsites.net/#b:future/f:%3Eil/K4Zwlgdg5gBAygTxAFwKYFsDcAobECG6qIADvgMaowAqxyAgiSdgN7YwczkA2+IIMAAoAnAPZRhhdpzac5MFPmRhyMAG6iwAExgBZfJAAUKYZCgBtALox8wqCACU0+TFkv5a2wtQQ0ESjAAvDAARAA6wAAi9JEAjABNITjuHl6QWqgAHkHevj6UAHQAkhAZmQDyAGbGPn6UDskpnADCohAgotyoBQDqpmgAMpCohiHpWQBcrgAMAL4hADQw45kNuE2cYJUwhitBwdNOGxxux3Kt7Z3dfWCDw6NFyDAA7qLCANYgAIQha2ezziaqG4IFQgJSpzOHGQAAsxM8YBBUAiSp5uNpyiRUJJlG0AKKZSgkXEQUYErHkNA6WFKZZPMACaa/RobAEpNmcAGzIA===

**Comment by ellismg** [comment]
Where did this test case come from?  I'm not surprised that doing a linguistic IndexOf with an unpaired surrogate causes weirdness.  If I had to guess, the underlying collation algorithm is just ignoring the unpaired surrogate in both the pattern and the target.  I would expect this behavior could also differ between Windows and Unix as we use different collation implementations on these platforms (Win32 vs ICU).

**Comment by conniey** [comment]
@ellismg I found this while migrating Lucene.NET libraries to .NET Core. One of their libraries uses icu4c. I migrated that dependency to .NET Core but the BreakIterator outputs a string rather than a start and end index that it did before, so I was trying to get the start and end index of that token using string.IndexOf.

[Test case](https://github.com/conniey/lucenenet/blob/conniey/updateIcu/src/Lucene.Net.Tests.Analysis.Common/Analysis/Util/TestSegmentingTokenizerBase.cs#L117)

[Code in local branch (that fails)](https://github.com/conniey/lucenenet/blob/conniey/updateIcu/src/Lucene.Net.Analysis.Common/Analysis/Util/SegmentingTokenizerBase.cs#L241)
[Code in master branch (that works)](https://github.com/conniey/lucenenet/blob/master/src/Lucene.Net.Analysis.Common/Analysis/Util/SegmentingTokenizerBase.cs#L218)

**Comment by krwq** [comment]
I do not believe we should be investing in fixing IndexOf for invalid strings (unpaired surrogate) as IMO this is undefined behavior. I advise to use direct byte comparison in such cases. Please reopen if you really think this should be fixed.
