### ISSUE TITLE
CentOS 7 outerloop runs failing [cmake is not found]

### ISSUE THREAD

**Issue by ellismg** [dotnet/corefx#9204]
After upgrading to build everything on the target machines the CentOS outerloop runs are failing with an error saying cmake is not found.

Looking at how the labels are set up in Jenkins, it looks like the outerloop runs use a different base image id than the inner loop ones. I suppose CMake is not present on this newer image?

**Comment by ellismg** [comment]
@Priya91 Do you know why these images are split out the way they are?  Also why don't the images patch the label names?

**Comment by Priya91** [comment]
@ellismg Missed this, yeah it's weird the images shouldn't be different, only the label is different for enabling sudo on outerloop runs. Not sure, what you mean by "images patch the label names"..

**Comment by ellismg** [comment]
> Not sure, what you mean by "images patch the label names".

Typo, sorry.  I mean the image names don't /match/ the label names.  I would have expected the label name (sans the "outer" tag) to match what image id we use when spinning up workers.

**Comment by Priya91** [comment]
@ellismg Yeah, that's correct. Changing the label name for every image name update will require changing the values in the utilities.groovy in dotnet-ci, and also we cant delete old labels, since other repo netci.groovy may be using them. Then we'll have duplicate labels mapped to same image..

**Comment by Priya91** [comment]
Found why this is happening in outerloop runs, hash command is not found with sudo. 
```
[dotnet-bot@Azure0609182303 outerloop_centos7.1_debug]$ sudo hash
sudo: hash: command not found
```

**Comment by Priya91** [comment]
This is fixed.
