### ISSUE TITLE
[release/1.0.0] Perf test execution failing in release branch

### ISSUE THREAD

**Issue by dsgouda** [dotnet/corefx#9207]
The release branch is now pointing to buildtools version 00503-04 which in turn references xunit-performance package version "v1.0.0-alpha-build0035" while individual project.jsons under release branch all point to "v1.0.0-alpha-build0033".
This results in an error here https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/PerfTesting.targets#L58 , that is failure to find the 0035 package number and hence failure to copy the xunit performance runner
This impacts execution of perf tests under CoreFx (both locally and via helix)

Tagging @jhendrixMSFT @lt72

**Comment by joshfree** [comment]
Fixed by https://github.com/dotnet/corefx/commit/a25e2df6e4c945e6bb502d049f5f4441b9c119c1
