### ISSUE TITLE
Improve code coverage for System.ComponentModel.Annotations

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#921]
According to the current code coverage report, this library is only at 75%.  Our general goal is closer to 90%, though this will depend on the library.  We should investigate to see whether the current coverage level is appropriate, and if not, improve our test suites to provide better coverage.

**Comment by ghuntley** [comment]
This looks like a nice and easy/simple starting point for contribution - Bagsies. Would a pull-request per annotation linked to this issue be acceptable?

**Comment by MattWhilden** [comment]
@ghuntley is going to go ham on this thing.

**Comment by karelz** [comment]
@ghuntley are you still working on it?

**Comment by danmosemsft** [comment]
It's now at an awesome 95%! Closing
https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/Code_Coverage_Report/
