### ISSUE TITLE
DispatchProxy should emit interface properties and events metadata

### ISSUE THREAD

**Issue by yfakariya** [dotnet/corefx#9220]
Currently, `DispatchProxyGenerator` only emits accessor methods of the interface type, does not emit any properties and/or events. Thus, getting properties and/or events via reflection fails as following:
```csharp
interface IFoo { string Bar { get; set; } };

IFoo proxy = DispatchProxy.Create<IFoo, SomeProxy>();
PropertyInfo[] props = proxy.GetType().GetProperties();
```
In this point, it is natural to think that `props` has 1 property (string Bar), but it is actually an empty array even though `var bar = proxy.Bar` and `proxy.Bar = "something"` can be compiled.

It looks unnatural. In addition, it limits effectiveness of `DispatchProxy`. For example, when we generate a wrapper which implements `INotifyPropertyChanged` around underlying model object using `DispatchProxy`, we cannot do that because the data binding engine fails to retrieve `PropertyInfo` and then fails to bind object. Other AOP scenario may also be restricted by this issue.

So, `DispatchProxyGenerator` should also emit properties and events of specified interface type as well as their accessor methods.

**Comment by yfakariya** [comment]
@AtsushiKan Do you have any questions? I have a patch with unit tests for this, but I'm waiting for further discussion about it :)

**Comment by AtsushiKan** [comment]
I’ll probably have lots of questions once I get to it (starting with questions like “What’s DispatchProxy…”) but given that it’s Milestoned for “Future” and not “1.1.0”, I wasn’t anticipating getting to it anytime soon.

If you feel it needs to be in 1.1.0, please change the Milestone.

**Comment by AtsushiKan** [comment]
It sounds like you have a fix ready to PR – if so, don’t wait on me. Issues that sounds “Reflection-y” just tend to get auto-assigned to me.

**Comment by yfakariya** [comment]
Thank you for reply! Yes, I had a fix as you thought, so I've just sent the PR.

**Comment by yfakariya** [comment]
Should I close this issue? I'm realizing that this issue was solved but a work to split the test project is remaining.

**Comment by AtsushiKan** [comment]
Go ahead and close. The test work can be tracked separately if and when it becomes important.

**Comment by yfakariya** [comment]
I got it.
