### ISSUE TITLE
Consider File.WriteAll(Stream) method

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#9222]
I frequently find myself wanting to dump all of the data from a stream to a new file. Currently, the best way to do that is:

```
using (var fs = new FileStream(pathForNewFile, FileMode.Create))
{
    streamIWantToDump.CopyTo(fs);
}
// OR
using (var fs = File.OpenWrite(pathForNewFile))
{
    streamIWantToDump.CopyTo(fs);
}
// or async CopyTo equivalents.
```

while these are fine, I'd really like to be able to do:
```
File.WriteAllFromStream(pathForNewFile, streamIWantToDump);
```

where `WriteAllFromStream` reads from `streamIWantToDump` until its end is reached.

**Comment by svick** [comment]
Did you mean this?

```c#
File.WriteAllFromStream(pathForNewFile, streamIWantToDump);
```

**Comment by ianhays** [comment]
>Did you mean this?

Yes, yes I did. Thanks, edited.

**Comment by karelz** [comment]
@ianhays says close it
