### ISSUE TITLE
Improve code coverage for System.Console

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#923]
According to the current code coverage report, this library is only at 58%.  Our general goal is closer to 90%, though this will depend on the library.  We should investigate to see whether the current coverage level is appropriate, and if not, improve our test suites to provide better coverage.

**Comment by patriksvensson** [comment]
I'm not sure if I'm reading the code coverage report wrong, but it says 97,3%.
Perhaps someone already fixed this?

**Comment by patriksvensson** [comment]
I was reading the report wrong. Disregard my previous comment.
I could take a look at this if you need some extra hand.

**Comment by stephentoub** [comment]
@patriksvensson, yes, if you have the time to try to boost the coverage of this library, that'd be terrific.  Thanks!  I can change the label to "grabbed by community" if you'd like to give it a go?

**Comment by patriksvensson** [comment]
Sure, I can give it a go :+1:

**Comment by stephentoub** [comment]
Great!  All yours :smile: Thanks, again, for taking a look.  If you decide not to address it, that's fine, just let us know so we can return it to being "up for grabs".

**Comment by patriksvensson** [comment]
Yes, of course. I keep you updated on this.

**Comment by patriksvensson** [comment]
I've done about 45 minutes of work after reading all the contribution documents, and got the test coverage up from 58% to 62.5%, so by extrapolation I get a feeling that this will take a while :wink: 

Some thoughts:

1. Some code that affects code coverage is shared code, such as code in the namespaces `Interop` and `System.SR`, which is linked into the System.Console solution. I don't think this functionality (if testable) should be covered by tests in System.Console, but I'm not sure of how you guys prefer it. Since they're linked into the solution, tests for this probably belong somewhere else?

2. Some code is not covered due to coverage by code contracts. An example is the `SyncTextReader` which I wrote tests for, that have a 66.67% coverage for the methods `ReadBlockAsync` and `ReadAsync`. I could easily add some tests to make them 100%, but I got a feeling that this will be enforced by the contracts? Unless you want to have tests that ensure that the contracts are there...

These two issues makes it look like `System.Console` has a 58% code coverage, when it in reality probably is closer to 80%.

**Comment by stephentoub** [comment]
Thanks, @patriksvensson.

> Some code that affects code coverage is shared code, such as code in the namespaces Interop and System.SR, which is linked into the System.Console solution

For SR, some of the code will definitely not be testable, e.g. calls to Format that just aren't used by this project but that are in the shared SR type.  But other code in SR that's not currently being exercised probably should be.  I've not looked in depth, but for example there are ~20 resource strings that aren't being accessed, which suggests that there are some error paths not being exercised.  We would likely want tests exercising those paths, to make sure they behave as we expect; the goal here isn't really to exercise the functionality in SR, but the fact that the SR paths aren't being covered is a warning sign that there may be missing tests elsewhere.

As for the Interop namespace, working to improve code coverage helps with two key things:
- Finding areas that aren't appropriately covered by tests
- Finding dead code that can be removed
In the case of the Interop namespace, it's very possible that System.Console is including a file that it doesn't use at all, in which case the fix would be to simply remove it from being compiled into System.Console.dll.  I would not be surprised if that's both the issue and the right fix here.

> Some code is not covered due to coverage by code contracts. An example is the SyncTextReader which I wrote tests for, that have a 66.67% coverage for the methods ReadBlockAsync and ReadAsync. I could easily add some tests to make them 100%, but I got a feeling that this will be enforced by the contracts?

If a type like SyncTextReader is defined in the System.Console assembly and is produced by calls to some methods on Console, it's unlikely that functionality will be exercised anywhere else in the system.  For base types like TextReader, it would probably be very useful to have some shared testing routines that verify correct handling of incorrect inputs, and that outputs abide by the stated contracts of methods; such shared test utilities could then be used by the Console tests as part of verifying the behavior of its custom SyncTextReader.  Unfortunately I don't think we have any such shared routines, at least not currently on GitHub; if you wanted to author those as part of writing these Console tests, that'd be very welcome.  Then other libraries could benefit from them as well.

> got the test coverage up from 58% to 62.5%, so by extrapolation I get a feeling that this will take a while

Please feel free to submit incremental PRs for the improvements you've made and then decide whether you want to continue or not... this in no way needs to be all or nothing. :smile:  We'll likely just keep the Issue open if it looks like there's value in increasing the code coverage number further.  Again, the goal here isn't to get to a specific number; rather, it's to use the code coverage number as an indication of whether there may be more work to do... it's very possible we get to a certain point with a lower-than-normal code coverage number and decide that it's perfectly acceptable.  It's also possible a high code coverage number isn't high enough. :smile:  It's all very dependent on the library and tests in question.

**Comment by stephentoub** [comment]
@patriksvensson, are you still working on this?  Just wondering if we should move it back to being up-for-grabs.

**Comment by patriksvensson** [comment]
@stephentoub Yes, I've been doing some minor stuff, but haven't had any time last month to finish it. You can add it back to up-for-grabs and I'll give you a shout when I have more time (unless someone else grabbed it by then).

**Comment by stephentoub** [comment]
Sounds good, thanks.
