### ISSUE TITLE
Version mismatch in System.Data.SqlClient.sni packages

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#9231]
```
runtime.native.System.Data.SqlClient.sni.4.0.0-rc3-24206-00 depends on runtime.win7-x64.runtime.native.System.Data.SqlClient.sni v[4.0.1-rc3-24203-02, ) (Any,Version=v0.0) when the latest build is v4.0.1-rc3-24206-00.
runtime.native.System.Data.SqlClient.sni.4.0.0-rc3-24206-00 depends on runtime.win7-x86.runtime.native.System.Data.SqlClient.sni v[4.0.1-rc3-24203-02, ) (Any,Version=v0.0) when the latest build is v4.0.1-rc3-24206-00.
```

cc @joshfree

**Comment by joshfree** [comment]
@jhendrixMSFT @weshaggard PTAL

**Comment by weshaggard** [comment]
@pranavkm these packages versions don't match by design as we build them from diffeent repo's (one in corefx and the other RID specific ones in TFS). Is this version mismatch causing some issue for you?

**Comment by joshfree** [comment]
@weshaggard I think this is an FYI that these components don't have expected matching versions.  They should after the -rc3 version is dropped. 

Is there any additional work required here?

**Comment by pranavkm** [comment]
It doesn't affect our builds. We saw something similar yesterday - https://github.com/dotnet/wcf/issues/1258 - and @ericstj fixed it. I wasn't sure if this was something similar.

**Comment by ericstj** [comment]
WCF was different.  It depended on non-existent packages.

**Comment by pranavkm** [comment]
Fair enough. Sorry for the false alarm.
