### ISSUE TITLE
Add sample code to release notes for a static Socket.ConnectAsync(string host, int port)

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#9235]

**Comment by stephentoub** [comment]
cc: @ericeil, @cipop, @davidsh 

Sample code:
```C#
public static class SocketUtilities
{
    public static async Task<Socket> ConnectAsync(string host, int port)
    {
        IPAddress[] addresses = await Dns.GetHostAddressesAsync(host).ConfigureAwait(false);
        return await ConnectAsync(addresses, port).ConfigureAwait(false);
    }

    public static async Task<Socket> ConnectAsync(IPAddress[] addresses, int port)
    {
        ExceptionDispatchInfo lastException = null;
        foreach (IPAddress address in addresses)
        {
            var socket = new Socket(address.AddressFamily, SocketType.Stream, ProtocolType.Tcp);
            try
            {
                await socket.ConnectAsync(address, port).ConfigureAwait(false);
                return socket;
            }
            catch (Exception exc)
            {
                socket.Dispose();
                lastException = ExceptionDispatchInfo.Capture(exc);
            }
        }

        if (lastException != null) lastException.Throw();
        throw new ArgumentOutOfRangeException(nameof(addresses));
    }
}
```

**Comment by ericeil** [comment]
I assume the ArgumentOutOfRangeException at the end is to cover the case where `addresses` is empty?  I think if we're going to put argument validation in the sample, we should do it in a more clear way (up top, with explicit checks).

Otherwise, this looks great!

**Comment by stephentoub** [comment]
>  I think if we're going to put argument validation in the sample, we should do it in a more clear way (up top, with explicit checks).

We could.  But then we would still need an exception throw at the end, as the compiler can't tell it's unreachable.

**Comment by CIPop** [comment]
This is needed only for *NIX systems. Windows will still work without them.

For API consistency, is there any reason not to add this to a future version of the contract and obsolete the other Connect methods? We could implement them differently on Windows (using direct calls to Winsock) and, as above, for any OS that doesn't have native support for multiple address connect.

**Comment by stephentoub** [comment]
> This is needed only for *NIX systems. Windows will still work without them.

Yes, we'll want to call out that this is only necessary for running on Unix, though for libraries trying to be cross-platform, it'll likely be common to use a solution like this rather than special-casing by platform.

> For API consistency, is there any reason not to add this to a future version of the contract and obsolete the other Connect methods?

Adding such methods would be a good thing to do.  Whether to obsolete the existing instance methods is debatable.

**Comment by CIPop** [comment]
> for libraries trying to be cross-platform, it'll likely be common to use a solution like this rather than special-casing by platform.

I agree that the APIs above should be the ones called by the application. For Windows, the implementation should call `WSAConnectByName` instead.

**Comment by stephentoub** [comment]
> For Windows, the implementation should call  WSAConnectByName  instead.

Sure, though I assume you mean via the existing instance methods rather than via P/Invoke, e.g.
```C#
public static class SocketUtilities
{
    public static async Task<Socket> ConnectAsync(string host, int port)
    {
        IPAddress[] addresses = await Dns.GetHostAddressesAsync(host).ConfigureAwait(false);
        return await ConnectAsync(addresses, port).ConfigureAwait(false);
    }

    public static async Task<Socket> ConnectAsync(IPAddress[] addresses, int port)
    {
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
        {
            var socket = new Socket(AddressFamily.Internetwork, SocketType.Stream, ProtocolType.Tcp);
            try
            {
                await socket.ConnectAsync(addresses, port).ConfigureAwait(false);
                return socket;
            }
            catch
            {
                socket.Dispose();
                throw;
            }
        }

        ExceptionDispatchInfo lastException = null;
        foreach (IPAddress address in addresses)
        {
            var socket = new Socket(address.AddressFamily, SocketType.Stream, ProtocolType.Tcp);
            try
            {
                await socket.ConnectAsync(address, port).ConfigureAwait(false);
                return socket;
            }
            catch (Exception exc)
            {
                socket.Dispose();
                lastException = ExceptionDispatchInfo.Capture(exc);
            }
        }

        lastException?.Throw();
        throw new ArgumentOutOfRangeException(nameof(addresses));
    }
}
```

**Comment by CIPop** [comment]
Thanks @stephentoub !

> Sure, though I assume you mean via the existing instance methods rather than via P/Invoke, e.g.

For now, yes.  After we get perf tests in place, we can take another look at the implementation and see if it can change to use more of the OS-level optimizations (such as `WSAConnectByName`).

**Comment by stephentoub** [comment]
> For now, yes. After we get perf tests in place, we can take another look at the implementation and see if it can change to use more of the OS-level optimizations (such as  WSAConnectByName ).

Yeah, I was referring to this for sample code purposes.  We can do whatever it takes in internal implementations to make things perform as we'd like.  I'd just like to keep samples as concise as possible.

**Comment by stephentoub** [comment]
Release note contents:

### Socket.Connect and ConnectAsync instance methods support only one IPAddress

The Socket class provides instance and extension Connect and ConnectAsync methods, each with multiple overloads.  Some of these overloads take an IPAddress, some take an array of IPAddresses, some take a string host name, and others take an EndPoint.  On Linux and on OSX, only some of these methods are functional in this release, due to the capabilities of the underlying platform.  Specifically, any of these overloads that may need to work with multiple addresses will throw a PlatformNotSupportedException; that includes not only the overloads that take an array of IPAddress instances, but also the overloads that take a string host, as well as the overloads that take an EndPoint if a DnsEndPoint is supplied (when the DNS lookup is performed, the host name may end up mapping to multiple addresses).

As a workaround, a new Socket instance may be created for each address to be tried, e.g.
```C#
public static class SocketUtilities
{
    public static async Task<Socket> ConnectAsync(string host, int port)
    {
        IPAddress[] addresses = await Dns.GetHostAddressesAsync(host).ConfigureAwait(false);
        return await ConnectAsync(addresses, port).ConfigureAwait(false);
    }

    public static async Task<Socket> ConnectAsync(IPAddress[] addresses, int port)
    {
        ExceptionDispatchInfo lastException = null;
        foreach (IPAddress address in addresses)
        {
            var socket = new Socket(address.AddressFamily, SocketType.Stream, ProtocolType.Tcp);
            try
            {
                await socket.ConnectAsync(address, port).ConfigureAwait(false);
                return socket;
            }
            catch (Exception exc)
            {
                socket.Dispose();
                lastException = ExceptionDispatchInfo.Capture(exc);
            }
        }

        lastException?.Throw();
        throw new ArgumentOutOfRangeException(nameof(addresses));
    }
}
```
