### ISSUE TITLE
Discuss adding System.IO.Compression static shortcuts

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#9237]
# Problem

I'd like to see some better support for compressing data in different forms quickly. Say you have a string right now - to compress it you have to do something like this:

```
string iWantToCompress = "thisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokaythisisalongstringokay?";
byte[] bytesToCompress = Encoding.UTF8.GetBytes(iWantToCompress);
using (var streamWithCompressed = new MemoryStream())
{
    using (var compressor = new DeflateStream(streamWithCompressed, CompressionMode.Compress, true))
    {
        compressor.Write(bytesToCompress, 0, bytesToCompress.Length);
    }
    byte[] compressed = streamWithCompressed.ToArray();
}
```
# Proposal

It would be nice if we could compress or decompress a string more intuitively, like so:
```
byte[] compressed = Deflate.Compress(iWantToCompress);
```

This would be somewhat similar to what we did in FileSystem by having`File.WriteAll*` operations to circumvent the need for a `FileStream`.

# Design

### Deflate / Zlib / GZIP

Deflate, Zlib, and GZip are all variants of the DEFLATE algorithm. The difference between them is that Deflate does not have a header, while ZLib and GZip have their own distinct headers. We currently support Deflate and GZip via DeflateStream and GZipStream, though there is [an issue for adding Zlib header support](https://github.com/dotnet/corefx/issues/7570).

Do we add string support for all three types? If so, how? Some options:
- Have one `Compression` static class with methods `Compress` and `Decompress` that take in an optional `HeaderType` enum with values `None`, `ZLib`, and `GZip`. The default would be None.
```
string compressed, decompressed;
compressed = Compression.Compress("stringToCompress", HeaderType.GZip);
compressed = Compression.Compress("stringToCompress"); // uses Deflate i.e. no header is written 
decompressed = Compression.Decompress(compressed); // decompression can detect and interpret the header for any of the three DEFLATE types, so specifying it explicitly would override that behavior and force the header to conform to the given type
```
- Have 2-3 static classes `Deflate`, `GZip`, and `ZLib` that contain their own `Compress` and `Decompress` methods.
```
string compressed, decompressed;
compressed = GZip.Compress("stringToCompress");
compressed = Deflate.Compress("stringToCompress");
decompressed = Deflate.Decompress(compressed);
```
- Add static `Compress` and `Decompress` methods to the existing `DeflateStream` and `GZipStream` classes:
```
string compressed, decompressed;
compressed = GZipStream.Compress("stringToCompress");
compressed = DeflateStream.Compress("stringToCompress");
decompressed = DeflateStream.Decompress(compressed);
```

### Parameters

There should be three versions of Compress + three versions of Decompress:
```
Compress(string stringToCompress);
Compress(string stringToCompress, Encoding encoding);
Compress(byte[] bytesToCompress);
Decompress(string stringToDecompress);
Decompress(string stringToDecompress, Encoding encoding);
Decompress(byte[] bytesToDecompress);
```

though I could see the value for `stream` equivalents (similar to https://github.com/dotnet/corefx/issues/9222) as well:
```
Compress(Stream streamToCompress);
Decompress(Stream streamToCompress);
```

### Return value

Three sensible options:
- Return a string with the results of the operation. :-1:
- Return a byte[] with the results of the operation
- Return a stream that can be read for the results of the operation. 
- The return type varies based on the parameter type e.g. `Compress(string)` returns a string, `Compress(byte[])` returns a byte[], etc.  :-1:

# Perf

Using these shortcuts would circumvent the need for:
- an Underlying stream (e.g. a MemoryStream) to hold the results of the (de)compression.
- a DeflateStream/GZipStream object
- A Deflater/Inflater object

since we would be able to directly hit the ZLibStream SetInput/GetOutput methods because we know the entirety of the item being compressed/decompressed. The downside to this is that the thing being (de)compressed would have to first be entirely in memory, but for a string or byte[] array that isn't an issue. There would be a net memory savings of an object already in memory since we wouldn't need to allocate the internal arrays of a DeflateStream object. 

# Downsides

- Every compress/decompress opens its own ZLibStreamHandle. For a lot of repeated operations this would be a performance hit.
- Adding fine-grained Compression support (e.g. CompressionLevel) would be too clunky to be worthwhile
- Adds a potentially large amount of new API

**Comment by svick** [comment]
I think that representing DEFLATE-compressed data as a `string` is a terrible idea (and the same applies to pretty much any other compression). It's just binary data, not characters, treating it as characters is wrong and leads to all kinds of problems.

A good example of such problems is the original code you showed: you're converting `byte[]` to `string` using `Encoding.UTF8.GetString()`. The problem with that is that invalid UTF8 input bytes (and there will be lots of them in DEFLATE-compressed data) are converted to U+FFFD REPLACEMENT CHARACTER. This means that `Encoding.UTF8.GetString()` is lossy and it won't be possible to decompress the original input string from the "compressed string". In other words, `Encoding.UTF8.GetBytes(Encoding.UTF8.GetString(b)) != b`.

Sure, it's possible to have a non-lossy encoding, but it's still a bad idea to treat data as something it's not.

**Comment by ianhays** [comment]
A byte[] would likely be better and more inline with similar methods, but I included string as a return value since there [certainly](https://social.msdn.microsoft.com/Forums/en-US/08567b82-f3a3-4887-b6a7-92ae553e9e3f/compress-string-with-gzipstream?forum=winappswithcsharp) [are](http://stackoverflow.com/questions/7343465/compression-decompression-string-with-c-sharp) [people](http://madskristensen.net/post/compress-and-decompress-strings-in-c) [compressing](http://dotnet-snippets.com/snippet/compress-and-decompress-strings/612) [strings](http://mitchvanhelden.blogspot.com/2011/01/compress-and-decompress-strings-with-c.html). It's probably not the best option, but it's good to consider nonetheless :) I'll update the OP with byte[] as the return value for the first example.

**Comment by Tornhoof** [comment]
>  This would be somewhat similar to what we did in FileSystem by having File.WriteAll* operations to circumvent the need for a FileStream.
Did you actually look how File.WriteAll* are implemented at the moment?
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/File.cs
- WriteAllLines/Text: Streamwriter
- WriteAllBytes: **FileStream**

The example you mentioned from SO, according to the OP he is compressing/decompressing an xml, his approach itself is probably flawed, because why convert the xml first to string and then compress/decompress, why not simply using the stream based api to the appropriate xml classes.

I'm not sure that your suggestion actually improves the API.

**Comment by ianhays** [comment]
>Did you actually look how File.WriteAll* are implemented at the moment?

They're abstractions around the more complicated underlying implementation; their purpose is to make quick-and-dirty file operations easy and succinct. The important aspect is that they circumvent the need for the **programmer** to use a FileStream.

>I'm not sure that your suggestion actually improves the API.

Then we'll iterate on it until it does, or close it if we decide it won't :). My goal is to make Compression easier and more intuitive to use so that people like the one [in the post you mentioned](http://stackoverflow.com/questions/7343465/compression-decompression-string-with-c-sharp) - self-proclaimed "newbie to .NET" programmers - can use it without writing paragraphs of bad code to work around our interface. Google "c# compress string" and there are a ton of results; I want to provide a better answer to those questions.

**Comment by Tornhoof** [comment]
Yes, your effort to improve it is great :)
> Decompress(byte[] bytesToDecompress);

The main problem I see with those byte array based overloads, is simply the amount of memory allocation. If that overload is "more visible" than the stream based api, maybe because intellisense will first suggest the byte[] one (afaik its lexicographically sorted, e.g. byte[] will be the first), programmers will start using the byte[] one. This means one possible code snippet would be:
```csharp
var bytes = File.ReadAllBytes("myfile");
var decompressed = Deflate.Decompress(bytes);
```
The above example is a recipie for disaster regarding memory and especially LOH allocations, but this is a general problem with all those byte[] apis. 
One solution to solve the order is actually going the way from File.*, e.g.
```csharp
DecompressString(string input)
DecompressBytes(byte[] input)
```
If you want to do it allocation friendly we need to talk about:
```csharp
int Compress(string input, byte[] output, int offset, int count) (similar to Write in Stream)
string Decompress(byte[] input, int offset, int count)
```
And I imagine no beginner will ever use those overloads, because they are complicated.

Or it is necessary to go directly the route of #6740

So yes, improving the ease of usage for an API is great, but we need a good way to point the beginner programmer to the right api at the right time, the experienced user will probably simply use the stream based api or write his own extension methods on strings to solve this problem. If the beginner selects the wrong one, like in SO post or in my example above, he will not improve his skills.

**Comment by svick** [comment]
@Tornhoof I think having both a simple and inefficient interface and also a complicated and efficient interface is better than having just the complicated and efficient interface. More often than not, efficiency is not that important.

Having a simple and efficient interface would be obviously best, but that may not be possible.

**Comment by ianhays** [comment]
closing this until we actually need it i.e. when we have more compression algorithms in Sys.IO.Compression.
