### ISSUE TITLE
Improve code coverage for System.Diagnostics.TextWriterTraceListener

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#924]
According to the current code coverage report, this library is only at 73%.  Our general goal is closer to 90%, though this will depend on the library.  We should investigate to see whether the current coverage level is appropriate, and if not, improve our test suites to provide better coverage.

**Comment by pallavit** [comment]
This needs to go to @Karelz who owns tracing support now. I am not sure how this can be assigned to him(I don't see him in the assignee list), can someone please help me here.
