### ISSUE TITLE
Ping doesn't work out-of-the-box on OS X

### ISSUE THREAD

**Issue by jpsingleton** [dotnet/corefx#9246]
I've been doing some cross platform testing on RC2, and Ping doesn't work out-of-the-box on OS X.

This seems to be fixed in https://github.com/dotnet/corefx/issues/4762 but there is still an [old package on NuGet](https://www.nuget.org/packages/System.Net.Utilities). So with the default feeds you get `System.Net.Utilities` version `4.0.0-beta-23516` from November and `project.json` contains this:

```javascript
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002702"
    },
    "System.Net.Utilities": "4.0.0-beta-23516"
  },
```

So you get the `Unable to load DLL 'ntdll.dll'` error shown in the issue, when not on Windows.

I think all that's needed is to push the latest version of the package to NuGet.

**Comment by mellinoe** [comment]
@jpsingleton We've renamed this package to [System.Net.Ping](https://www.nuget.org/packages/System.Net.Ping/). Could you try to use that package instead, and see if it works for you?

**Comment by jpsingleton** [comment]
That seems to still work on Windows, I'll test on Mac.

BTW https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Net.Utilities gave me an exception at runtime on Windows. `Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Utilities`.

**Comment by jpsingleton** [comment]
Yes that works on OS X. Thanks.

Visual Studio still prompts to install the old package when you try to use `Ping` though. No indication of the new version. Might be worth updating the docs on NuGet for `System.Net.Utilities`?

The problem is that the legacy package works fine on Windows and the issue only occurs when deploying to Unix. It would be nice if this broke earlier. Perhaps if the old package was removed?
