### ISSUE TITLE
X509Certificates.Tests.X509FilesystemTests.X509Store_AddAfterDispose

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#9248]
This appears to be a test issue.  Please investigate and confirm.

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/release_1.0.0/job/fedora23_release/lastCompletedBuild/testReport/System.Security.Cryptography.X509Certificates.Tests/X509FilesystemTests/X509Store_AddAfterDispose/

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/release_1.0.0/job/fedora23_debug/lastCompletedBuild/testReport/System.Security.Cryptography.X509Certificates.Tests/X509FilesystemTests/X509Store_AddAfterDispose/

```
MESSAGE:
System.Security.Cryptography.CryptographicException : The owner of '/mnt/resource/j/workspace/dotnet_corefx/release_1.0.0/fedora23_release/tempHome/.dotnet/corefx/cryptography/x509stores/teststorea5d8b5c4bda94ae2bdb99f5cc6afdcdd' is not the current user.
+++++++++++++++++++
STACK TRACE:
at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.EnsureDirectoryPermissions(String path, UInt32 userId) at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.Add(ICertificatePal certPal) at System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.<>c.<X509Store_AddAfterDispose>b__7_0(X509Store store, String storeDirectory) at System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.RunX509StoreTest(Action`2 testAction)
```

```
MESSAGE:
System.Security.Cryptography.CryptographicException : The owner of '/mnt/resource/j/workspace/dotnet_corefx/release_1.0.0/fedora23_debug/tempHome/.dotnet/corefx/cryptography/x509stores/teststore99ac8254ea77466ebf1bf59151bb561d' is not the current user.
+++++++++++++++++++
STACK TRACE:
at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.EnsureDirectoryPermissions(String path, UInt32 userId) at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.Add(ICertificatePal certPal) at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate) at System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.<>c.<X509Store_AddAfterDispose>b__7_0(X509Store store, String storeDirectory) at System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.RunX509StoreTest(Action`2 testAction) at System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_AddAfterDispose()
```

**Comment by bartonjs** [comment]
@ellismg This seems to have been the first run of Fedora 23... did we do anything different on this configuration?  This directory was created fresh by the test, and its uid is not the value of GetEUid().

https://github.com/dotnet/corefx/blob/release/1.0.0/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/DirectoryBasedStoreProvider.cs#L125-L129

**Comment by joshfree** [comment]
just a clarification it's the first run since the jenkins server rebooted

**Comment by bartonjs** [comment]
Although.. only ONE X509FilesystemTests test failing seems weird.  Every one of them uses a helper which does
* Guid.NewGuid() to pick a directory
* Delete that directory if it exists, though it's a GUID, so it shouldn't
* Run the test (which will likely create the directory)
* Delete that directory if it exists, to leave the machine in the same state we found it.

So I'd really expect all of them to fail.

**Comment by joshfree** [comment]
@bartonjs can you give me an update by EOD?

**Comment by ellismg** [comment]
FWIW, we are not seeing this test failure in Helix.

This seems to be related to the fact that we are now running the tests via `build.sh` instead of using the cross built artifacts plus a live CoreCLR.  I would have assumed if there was a problem specific to consuming CoreCLR from packages we would also see it in Helix, which also consumes the runtime that way.

**Comment by bartonjs** [comment]
I understand why only one of the test cases in this class is failing... this is the only one which causes the directory to be created which is not marked OuterLoop.

Fedora 23 1.0.0 (RTM)
* InnerLoop Debug: Fail
* InnerLoop Release: Fail
* OuterLoop Debug: Fail
* OuterLoop Release: __Pass__

Fedora 23 Master:
* InnerLoop Debug: Fail
* InnerLoop Release: Fail
* OuterLoop Debug: Fail
* OuterLoop Release: __Pass__

And, like Matt said, when we checked earlier it was showing as passing in Helix.  I don't really know what's going on, but this seems more infrastructure than product or test bug.

**Comment by bartonjs** [comment]
Manual investigation concurs on something being odd about our test rig:

```
[dotnet-bot@jbarton-fedora23 netcoreapp1.0]$ uname -a
Linux jbarton-fedora23 4.4.9-300.fc23.x86_64 #1 SMP Wed May 4 23:56:27 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Master (because I forgot to change branches):
```
=== TEST EXECUTION SUMMARY ===
   System.Security.Cryptography.X509Certificates.Tests  Total: 17, Errors: 0, Failed: 0, Skipped: 0, Time: 0.769s
[dotnet-bot@jbarton-fedora23 netcoreapp1.0]$ ./corerun xunit.console.netcore.exe System.Security.Cryptography.X509Certificates.Tests.dll -class System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests -showprogress
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Security.Cryptography.X509Certificates.Tests
Discovered:  System.Security.Cryptography.X509Certificates.Tests
Starting:    System.Security.Cryptography.X509Certificates.Tests
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_MultipleObjects(matchCase: False) [STARTING]
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_MultipleObjects(matchCase: False) [FINISHED] Time: 0.1549574s
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_MultipleObjects(matchCase: True) [STARTING]
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_MultipleObjects(matchCase: True) [FINISHED] Time: 0.0287467s
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_AddTwo [STARTING]
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_AddTwo [FINISHED] Time: 0.01292s
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_DistinctCollections [STARTING]
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_DistinctCollections [FINISHED] Time: 0.0116826s
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_AddOne [STARTING]
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_AddOne [FINISHED] Time: 0.0044739s
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_AddAfterDispose [STARTING]
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_AddAfterDispose [FINISHED] Time: 0.0046231s
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_DowngradePermissions [STARTING]
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_DowngradePermissions [FINISHED] Time: 0.0028717s
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.VerifyCrlCache [STARTING]
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.VerifyCrlCache [FINISHED] Time: 0.1778821s
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_AddAndClear [STARTING]
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_AddAndClear [FINISHED] Time: 0.0047743s
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_AddOneAfterUpgrade [STARTING]
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_AddOneAfterUpgrade [FINISHED] Time: 0.0045832s
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_Add4_Remove1 [STARTING]
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_Add4_Remove1 [FINISHED] Time: 0.0193128s
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_AddReadOnly [STARTING]
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_AddReadOnly [FINISHED] Time: 0.0011845s
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_AddClosed [STARTING]
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_AddClosed [FINISHED] Time: 0.0011015s
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_AddTwo_UpgradePrivateKey [STARTING]
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_AddTwo_UpgradePrivateKey [FINISHED] Time: 0.0215885s
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_OpenExisting_Fails [STARTING]
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_OpenExisting_Fails [FINISHED] Time: 0.0008997s
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_AddDuplicate [STARTING]
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_AddDuplicate [FINISHED] Time: 0.0038972s
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_AddTwo_UpgradePrivateKey_NoDowngrade [STARTING]
   System.Security.Cryptography.X509Certificates.Tests.X509FilesystemTests.X509Store_AddTwo_UpgradePrivateKey_NoDowngrade [FINISHED] Time: 0.020404s
Finished:    System.Security.Cryptography.X509Certificates.Tests

=== TEST EXECUTION SUMMARY ===
   System.Security.Cryptography.X509Certificates.Tests  Total: 17, Errors: 0, Failed: 0, Skipped: 0, Time: 0.749s
```

Double-checking now with the release/1.0.0 branch.

**Comment by bartonjs** [comment]
Yep, release/1.0.0 just came back clean; too.

@ellismg: Thanks for hooking me up with a test machine.  Fortunately (for the product) the tests passed, unfortunately (for the badge) that doesn't tell us why CI isn't happy
@joshfree: I'm not sure what metadata changes you'd want to make here, so I haven't pre-applied any.  The `infrastructure` label mostly seems to be about changes to/for infrastructure, not so much "this is broken by infrastructure"

**Comment by joshfree** [comment]
Should the failing test be disabled for that specific flavor with a tracking bug?

**Comment by bartonjs** [comment]
I can make the tests all be [Conditional(NotFedora)]; but I don't think Fedora is really the problem, just coincident with some odd machine configuration.

But, if the goal is just to make the build badges be green so we guard against regressions, I can make that change.

**Comment by joshfree** [comment]
Let's do the test-only change and have a tracking bug to resolve in 1.1

**Comment by bartonjs** [comment]
Okay... @ellismg got in the same room for 5 minutes, and solved the mystery.

On our Fedora23 machines, /mnt/resource is of type fuseblk (which really means NTFS), when we expect a Unix-mode-based system.

* InnerLoop Debug: Runs as a standard user, fails because the directory UID (0, because it's NTFS mounted as root) is not the current UID.
* InnerLoop Release: Same
* OuterLoop Debug: Runs as root, the UID check passes, but an assert that after chmod the permissions do not include g+rw or o+rw fails.
* OuterLoop Release: Runs as root, the UID check passes, asserts are compiled out, thinks everything is happy.

So the infrastructure problem is that the resource mount is NTFS instead of the ext4 it claims in config.

**Comment by bartonjs** [comment]
Further investigation in #9293 has shown this to be an Azure-sourced infrastructure problem.  We put in the release notes that $HOME is required to be on a chmod-supported filesystem.

9293 should be the only thing tracking this problem, now.
