### ISSUE TITLE
VSO build should fail if package upload also fails

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefx#9249]
Currently all the new build pipeline results are "green" even though all builds have failed to publish since MyGet.org is returning HTTP 500.

The pipeline should actually catch this and not report success.

**Comment by dagood** [comment]
I see green in dotnetmissioncontrol but on the VSTS dashboard the builds show failed. To confirm, it's just dotnetmissioncontrol that needs to change, and maybe some linkage? It doesn't show the publish builds at all right now, so I guess those should be added.

**Comment by jhendrixMSFT** [comment]
Correct this is not an issue with the build pipeline, it's mission control.  @ChadNedzlek can you please take a look.

**Comment by ChadNedzlek** [comment]
As far as I can tell, this was fixed long ago.  If someone is still seeing this, feel free to reopen.
