### ISSUE TITLE
Improve code coverage for System.Diagnostics.TraceSource

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#925]
According to the current code coverage report, this library is only at 24%.  Our general goal is closer to 90%, though this will depend on the library.  We should investigate to see whether the current coverage level is appropriate, and if not, improve our test suites to provide better coverage.

**Comment by MarkPflug** [comment]
@stephentoub I've started working on this. My efforts currently put it at 85% coverage. I have a few more classes to go then I'll open a PR. It might be a while until I get around to finishing it up though. 

Just wanted to put a note on this so that no one else starts duplicating effort.

**Comment by stephentoub** [comment]
That's awesome, @MarkPflug.  Thanks!  Looking forward to seeing the PR.

**Comment by stephentoub** [comment]
Thanks to @MarkPflug, the coverage for this library is now at 98%!
