### ISSUE TITLE
[dev/cms_unix] EnvelopedCms Decode different behavior between Framework and Core

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/corefx#9252]
Decode on Framework returns a CryptographicAttributeObjectCollection for unprotected attributes that has a CryptographicAttributeObject for every Oid listed in the encoding, even if it holds no attributes (if it's given an empty set for that oid). However Core won't create an object for the oid if the set is empty. Thus EnvelopedCms.UnprotectedAttributes.Count will return different things on framework and core.

**Comment by AtsushiKan** [comment]
This issue has been unassigned since it was opened - were you planning on fixing it yourself or were you planning on assigning it to me to fix?

**Comment by hoyosjs** [comment]
This has been fixed on dev/cms_unix

**Comment by bartonjs** [comment]
Since this affects the existing Windows implementation we may want to cherry pick this into master for 1.2.0

**Comment by karelz** [comment]
We need to cherry pick the commit (likely #9659). Should be easy and is needed for 1.2.

**Comment by ViktorHofer** [comment]
@bartonjs @karelz If still an issue, I could do it later today

**Comment by karelz** [comment]
I think it is still needed (or rather I don't see a reason why it would be suddenly not needed). Assigned to you. Thanks!

**Comment by ViktorHofer** [comment]
@bartonjs 
> Cherry picking seems not possible because the changed files of the linked commit aren't even yet existing in master here. Merge the whole branch or picking multiple commits?

**Comment by bartonjs** [comment]
@ViktorHofer The test and the Windows change from that PR.  The Unix change doesn't make sense since we don't have Unix CMS in master.  And we absolutely can't merge the branch (it won't build, it won't work on macOS, and it has a data corruption bug)
