### ISSUE TITLE
Instructions to run perf tests need to be updated

### ISSUE THREAD

**Issue by dsgouda** [dotnet/corefx#9257]
The instructions provided to run perf tests here https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/performance-tests.md need to be modified now that we have enabled execution of perf tests using dotnet cli.
We also need to remove dependencies mentioned there that are no longer applicable.

**Comment by danmosemsft** [comment]
@DrewScoggins @brianrob is this still relevant? please switch to milestone future if it's not planned.

**Comment by brianrob** [comment]
@DrewScoggins @valenis, I think we should do this.  The instructions are likely quite old.

**Comment by Clockwork-Muse** [comment]
I can get performance tests to run locally!

From `corefxRoot/src/<System.Whatever>/tests/Performance` call: 
`msbuild /t:clean,build,test /p:ConfigurationGroup=Release /p:TargetOS=Windows_NT /p:Performance=true`
(from an admin VS2017 dev command prompt, at least)

It ends by claiming the tests failed with `corefx\Tools/Microsoft.BenchView.JSONFormat\tools\
  measurement.py': [Errno 2] No such file or directory` (nope, doesn't exist)... however, Python isn't listed as an official requirement for building corefx (it is for coreclr, though).  I don't know why the python file is gone, but I suspect it's related to the requirement...

Is something like this the expected end state, or are there more changes anticipated?

**Comment by DrewScoggins** [comment]
This is a bug on our side. Those Python scripts are used to take the raw data and massage it into a format that our visualization and tracking tools you. Those calls should be hidden behind flags that we set when we do runs that submit that data I will file an issue for this on Monday.

**Comment by danmosemsft** [comment]
@tarekgh who was also trying this.

**Comment by tarekgh** [comment]
@DrewScoggins when you think we can finish and close this one?

**Comment by tarekgh** [comment]
@DrewScoggins @valenis @brianrob when you think will get this issue done?

**Comment by brianrob** [comment]
@DrewScoggins is out of the office, but should be able to give you a better idea on this next week.

**Comment by danmosemsft** [comment]
@DrewScoggins ...?

**Comment by DrewScoggins** [comment]
I believe that the performance instructions have already been updated to be current by this [PR](https://github.com/dotnet/corefx/pull/17319).

I also made a change in buildtools that fixed the issue where we were exposing the call to python when you were not uploading to Benchview with this [PR](https://github.com/dotnet/buildtools/pull/1448).

So I think we can close this issue.

**Comment by tarekgh** [comment]
Closing the issue per @DrewScoggins comment

**Comment by karelz** [comment]
@DrewScoggins it info is missing how to target Desktop - can you please add it as "TODO section" and file a documentation bug to fill the info later? Thanks!
