### ISSUE TITLE
Query: options for connecting to Oracle databases

### ISSUE THREAD

**Issue by dibyendumajumdar** [dotnet/corefx#9268]
Hi
I am considering using the cross platform dot net framework for building a major new application. But I have hit an issue - I am unsure whether the current corefx supports connecting to Oracle databases or not. I need to be able to support multiple database backends, including Oracle and SQL Server.
Thanks

**Comment by saurabh500** [comment]
@dibyendumajumdar CoreFx doesn't support connecting to Oracle. The database provider in CoreFx is only SqlClient which can connect to Microsoft Sql Server. 
For Oracle, you will need a ADO.Net provider for CoreFx.

**Comment by dibyendumajumdar** [comment]
@saurabh500 thanks. I forgot to mention that my backend service must be able to run on Linux or Windows. I assume that I can get an ADO.Net provider for Oracle on Windows but what options are there on Linux? Has any provider been tested/certified? Any plans to do so?

**Comment by Giorgi** [comment]
@dibyendumajumdar Check [http://forums.devart.com/viewtopic.php?f=19&t=33592](url)

**Comment by saurabh500** [comment]
@dibyendumajumdar We don't have any recommendations for the Oracle ADO.Net Provider for CoreFx. It is up to you to select one for your project.

**Comment by dibyendumajumdar** [comment]
So essentially there is no free Oracle ADO.Net provider on Linux? As far as I can tell the official Oracle one is for Windows only. And the others are commercial products. This is a show stopper for me as far as using dot net on Linux is concerned.

**Comment by saurabh500** [comment]
@dibyendumajumdar You are right, the Oracle provider is ODP.Net which support .Net Framework on Desktop. 
ODP.Net will need to build the DB library on top of .Net core (CoreFx) so that it can be consumed by users building on top of CoreFx.

**Comment by chadbr** [comment]
Anyone interested in helping me port the mono provider to .net core?

http://www.mono-project.com/docs/database-access/providers/oracle/

**Comment by wklm** [comment]
hey @chadbr did u manage to port the library?

**Comment by chadbr** [comment]
@wklm never did - sorry... requirements changed, we dropped oracle.
