### ISSUE TITLE
[Release/1.0.0]System.Net.Security.Tests failing on Opensuse

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#9272]
```
15:50:21   Copyright (C) 2014 Outercurve Foundation.
15:50:21   
15:50:21   Discovering: System.Net.Security.Unit.Tests
15:50:21   Discovered:  System.Net.Security.Unit.Tests
15:50:21   Starting:    System.Net.Security.Unit.Tests
15:50:22   Finished:    System.Net.Security.Tests
15:50:22   
15:50:22   === TEST EXECUTION SUMMARY ===
15:50:22      System.Net.Security.Tests  Total: 97, Errors: 0, Failed: 0, Skipped: 3, Time: 3.204s
15:50:22   Finished running tests. End time=22:51:38. Return value was 0
15:50:22 /mnt/resource/j/workspace/dotnet_corefx/release_1.0.0/opensuse13.2_debug/Tools/tests.targets(202,5): warning MSB3073: The command "/mnt/resource/j/workspace/dotnet_corefx/release_1.0.0/opensuse13.2_debug/bin/tests/Linux.AnyCPU.Debug/System.Net.Security.Tests/netcoreapp1.0/RunTests.sh /mnt/resource/j/workspace/dotnet_corefx/release_1.0.0/opensuse13.2_debug/packages/" exited with code -1. [/mnt/resource/j/workspace/dotnet_corefx/release_1.0.0/opensuse13.2_debug/src/System.Net.Security/tests/FunctionalTests/System.Net.Security.Tests.csproj]
15:50:22 /mnt/resource/j/workspace/dotnet_corefx/release_1.0.0/opensuse13.2_debug/Tools/tests.targets(211,5): error : One or more tests failed while running tests from 'System.Net.Security.Tests' please check log for details! 
```

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by ellismg** [comment]
Note that a little earlier in the log I see this text:

```
140526372357776 : warning : 1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:ssl_lib.c:1294: 
```

I assume that's something printed to stderr.  All the tests passed however.  It's also unclear why MSBuild thinks the return value is -1 and the execution scripts think the return value is 0.

**Comment by ellismg** [comment]
I looked into this a little more.  When run outside of MSBuild, the test writes the following text to stderr:

```
Error in cipher list
140623300417168:error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:ssl_lib.c:1294:
   System.Net.Security.Tests.ServerNoEncryptionTest.ServerNoEncryption_ClientAllowNoEncryption_ConnectWithNoEncryption [SKIP]
      Condition(s) not met: "SupportsNullEncryption"
   System.Net.Security.Tests.ServerRequireEncryptionTest.ServerRequireEncryption_ClientNoEncryption_NoConnect [SKIP]
      Condition(s) not met: "SupportsNullEncryption"
   System.Net.Security.Tests.ServerAllowNoEncryptionTest.ServerAllowNoEncryption_ClientNoEncryption_ConnectWithNoEncryption [SKIP]
      Condition(s) not met: "SupportsNullEncryption"
```

The first two lines look like they debugging output from OpenSSL.  My understanding is that we probe to see if ciphers are supported by calling Open SSL functions and then checking return values.  I could imagine that OpenSUSE builds with an OpenSSL that prints an error in this case (it looks like the behavior is toggle-able via a define at compile time).

In this case I believe the `:error:` text is triggering MSBuild to think that the task reported an error and that gets turned into a failure.  If I explicitly set `IgnoreStandardErrorWarningFormat` to false on the Exec task in tests.targets that runs the tests, then then I still see the error in the log, but MSBuild does not fail.

I'm not sure if there's some way we can detect what we need to detect without triggering this error (being good citizens and all would be nice) but I don't think there's a product bug here.

The reason it shows up now is previously we ran tests on opneSUSE via run-test.sh (outside of msbuild) which did not look at stderr or stdout to figure out if things failed, it just used return codes.

**Comment by stephentoub** [comment]
@ellismg, I believe you're right about the root cause.  In which case we could also change this code:
https://github.com/dotnet/corefx/blob/dbdae6947381db563b081fe7dbcf116ff9df36bc/src/System.Net.Security/tests/FunctionalTests/TestConfiguration.cs#L43-L46
to redirect and consume stderr.

**Comment by ellismg** [comment]
@stephentoub Yes, I was just about to post the above after seeing how this was implemented.  I will give it a shot locally, since I have a machine handy.

**Comment by ellismg** [comment]
@joshfree after investigation this is not a product issue.  Moving to 1.1.  I have also opened a PR to fix the test issue.  If we want to take it at some point into release to clean up the numbers in Jenkins, we can do that.
