### ISSUE TITLE
"OS X" is now branded as "macOS"

### ISSUE THREAD

**Issue by justinvp** [dotnet/corefx#9274]
**Update (6/13):** Apple has officially announced that "OS X" is now "macOS".

---

It appears highly likely that "OS X" will be rebranded as "macOS" next week at WWDC.
- http://9to5mac.com/2016/06/08/latest-hint-at-macos-rebranding-of-os-x-appears-in-new-app-store-guidelines/
- https://daringfireball.net/linked/2016/03/30/macos

Is it too late to tweak the naming of new .NET Core APIs with `OSX`, or will the first version of .NET Core RTM with obsolete naming?

e.g. [`RuntimeInformation.IsOSPlatform(OSPlatform.OSX)`](https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.Runtime.InteropServices.RuntimeInformation/src/System/Runtime/InteropServices/RuntimeInformation/OSPlatform.cs#L13) -> `OSPlatform.Mac` or `OSPlatform.MacOS` or `OSPlatform.Darwin` or ?

**Comment by mellinoe** [comment]
I think it is already too late to make breaking changes like this, even moreso if the rename won't be official until next week. We should not break compatibility with our current RC2 interface.

**Comment by am11** [comment]
Switching to MacOS or preferably Darwin at some point would be nice.

SmartOS, then MacOS and next could be WindOS. :)

**Comment by AlexGhiondea** [comment]
This would be a breaking change that will probably not add a lot of value. 

I am closing this for now. Feel free to reactivate if you have more data to justify taking this breaking change.
