### ISSUE TITLE
Rewrite System.IO.MemoryMappedFiles tests

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#928]
According to the current code coverage report, this library is only at 77%.  Our general goal is closer to 90%, though this will depend on the library.  We should investigate to see whether the current coverage level is appropriate, and if not, improve our test suites to provide better coverage.

**Comment by Maxwe11** [comment]
I think these test should be refactored with xunit in mind. One `Fact` which catch all exceptions it's not good point to start working on this issue.

**Comment by stephentoub** [comment]
I've started to rewrite these tests.  They're still causing sporadic failures in our CI and in local runs and it's difficult to augment them well given their legacy style.

**Comment by Maxwe11** [comment]
@stephentoub they also leave temporary files after themselves

**Comment by stephentoub** [comment]
Yup, and they're not testing everything we want them to test, and... lots of things to fix ;)

**Comment by mellinoe** [comment]
Did you mean to say "Tests" in the title?

**Comment by stephentoub** [comment]
Oops, yes, fixed.
