### ISSUE TITLE
Fedora /mnt/resource is an NTFS mount, making permissions checks fail

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#9293]
```
$ mount | grep resource
/dev/sdb1 on /mnt/resource type fuseblk (rw,relatime,user_id=0,group_id=0,allow_other,blksize=4096)
```

fuseblk is NTFS, which doesn't support Unix mode-based permissions; and leads to things like the X509Store permissions set/checks failing.

**Comment by bartonjs** [comment]
This is the cause of #9248.

**Comment by Priya91** [comment]
Upon investigation, the problem seems to be with Azure Linux agent, filed issue here Azure/WALinuxAgent#392

**Comment by karelz** [comment]
@mmitche the https://github.com/Azure/WALinuxAgent/issues/392 was closed. Do we have an issue tracking in engineering to work around the problem?

**Comment by mmitche** [comment]
@karelz We've already worked around it.  We run the initial startup script as root now, which makes the drive writable.

**Comment by bartonjs** [comment]
@mmitche "writable" or "ext4"?  The X509Certificates tests fail when HOME is bound to an NTFS volume, so it needs to be a filesystem supporting chmod.

**Comment by mmitche** [comment]
Oh that's right.  It's made writeable.  I haven't done anything else with it.  Have you seen this recently?

**Comment by bartonjs** [comment]
We have a fair number of tests that are disabled because of this problem.  I don't know that we've specifically tried re-enabling them, but if the mount type is still NTFS they'll still fail.

**Comment by mmitche** [comment]
@bartonjs still looks like fuseblk

Filesystem     Type      Size  Used Avail Use% Mounted on
devtmpfs       devtmpfs  6.9G     0  6.9G   0% /dev
tmpfs          tmpfs     6.9G  8.0K  6.9G   1% /dev/shm
tmpfs          tmpfs     6.9G  380K  6.9G   1% /run
tmpfs          tmpfs     6.9G     0  6.9G   0% /sys/fs/cgroup
/dev/sda2      xfs        30G  4.8G   25G  17% /
tmpfs          tmpfs     6.9G   71M  6.8G   2% /tmp
/dev/sda1      ext4      477M   95M  353M  22% /boot
/dev/sdb1      fuseblk   200G  6.5G  194G   4% /mnt/resource
tmpfs          tmpfs     1.4G     0  1.4G   0% /run/user/1000

**Comment by mmitche** [comment]
@dotnet/dnceng FYI

**Comment by danmosemsft** [comment]
@mmitche @bartonjs who owns the next action here? so we can get the linked tests fixed.

**Comment by mmitche** [comment]
Since Azure doesn't support Fedora, then we either just wait or somehow figure out and fix it ourselves? The client is OSS.

**Comment by Priya91** [comment]
> somehow figure out and fix it ourselves?

On the linked issue from Azure, they had suggested that we configure the cloud images using cloud init settings ourselves. I guess for unknown VM images, azure calls into the cloud init APIs, and we may need to specific the settings using the config keys fs_type. Microsoft Azure docs [here](https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-linux-using-cloud-init) and cloud-init docs [here](https://cloudinit.readthedocs.io/en/latest/topics/modules.html#disk-setup)

**Comment by danmosemsft** [comment]
Milestone=2.0 since we aren't getting x509 coverage on Fedora.

**Comment by RheaAyase** [comment]
Did someone check F24 or 25 by any chance? F23 is EOL so if this is not a problem on newer versions, this issue is kinda irrelevant now.

**Comment by bartonjs** [comment]
@RheaAyase Yes, it's all our Fedora VMs and our Ubuntu 16.xx VMs.  When the issue was opened Fedora23 was the only version of any distro we were testing on which had this problem (because, apparently, it was the only version of any distro that we were testing on which didn't have a base image provided by Azure).

**Comment by karelz** [comment]
This is difficult and obscure. @bartonjs can we push it to Future? To compensate we could do one off manual sign off test ... thoughts?

**Comment by bartonjs** [comment]
We've pushed it off since before 1.0 RTM, so clearly we "can" live without it.  As long as we have one distro which still runs the tests that are disabled because of this problem we can safely say that the code works.

If the number of distros which run these tests has fallen to 0 (it's Linux-only) then we've definitely lost coverage and this becomes more important.

**Comment by karelz** [comment]
Alright, future it is. Sad, but the right cost/benefit trade off at this moment.

**Comment by ViktorHofer** [comment]
Can someone summarize what the action item here is?

**Comment by MattGal** [comment]
@ViktorHofer given that the VMs described with the problem are the ancient Jenkins type, and given that we do all our build and test work in a properly created and mounted * (to my knowledge) folder in Helix, I think the remaining work is to see if that test can pass now (or is already enabled and passing), and enable it.  

Virtually everything about how we build and run tests has changed since this was opened, so just finding out if this is still an issue makes the most sense.

**Comment by bartonjs** [comment]
For X509, change https://github.com/dotnet/corefx/commit/73d4a319ab5f32409f6001c929462fea86bd0441#diff-d1dec5099a08dcd1ee7f06b8d172dcdd to always report `true`.  If that successfully runs on all configurations, we can rip out the conditions

**Comment by MattGal** [comment]
... and if it does fail, send me the link to the mc.dot.net or other test result page and I'll see if we can fix our machines.
