### ISSUE TITLE
Microsoft.Composition does not target netstandard

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#9300]
The most recent build of the package on NuGet.org targets PCL but not netstandard.

**Comment by pranavkm** [comment]
cc @joshfree

**Comment by mellinoe** [comment]
We aren't producing the packages for this out of corefx yet, because we haven't made any functional changes. You should be able to consume it with an imports statement for now. We're planning on publishing new packages by 1.1.0. https://github.com/dotnet/corefx/issues/6598

**Comment by pranavkm** [comment]
@mellinoe @javiercn has been trying to remove references to all imports from aspnet packages. Some of the Roslyn packages that we transitively depend on reference this package (https://github.com/dotnet/roslyn/blob/2eeb1e3f129aa6429210b20f5a01cb8159b5d3d4/src/Dependencies/Composition/project.json#L4). It would be great if you could let the Roslyn folks know once a netstandard targeting build is available. Feel free to close this as a dup pf #6598.

**Comment by mellinoe** [comment]
> It would be great if you could let the Roslyn folks know once a netstandard targeting build is available. Feel free to close this as a dup of #6598.

Thanks, I'm going to do that. I'll leave a note in the other issue to notify you guys when the work is done.
