### ISSUE TITLE
Improve code coverage for System.Reflection.Metadata (71.6%)

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#931]
According to the current code coverage report, this library is only at 51%.  Our general goal is closer to 90%, though this will depend on the library.  We should investigate to see whether the current coverage level is appropriate, and if not, improve our test suites to provide better coverage.

**Comment by tmat** [comment]
@stephentoub Where do I find the current coverage numbers? Is there a table online listing the current coverage for each CoreFX assembly?

**Comment by stephentoub** [comment]
Here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/code_coverage_windows/Code_Coverage_Report/

You can also generate this locally just for the individual assembly by doing:
msbuild /t:rebuildandtest /p:Coverage:true
from the project's tests directory. The result will be available in bin\tests\coverage\index.htm.

**Comment by danmosemsft** [comment]
It's apparently now at 70% which is improved

https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/Code_Coverage_Report/
