### ISSUE TITLE
Improve code coverage for System.Resources.ResourceWriter

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#932]
According to the current code coverage report, this library is only at 56%.  Our general goal is closer to 90%, though this will depend on the library.  We should investigate to see whether the current coverage level is appropriate, and if not, improve our test suites to provide better coverage.

**Comment by ramarag** [comment]
With the change 67da6227c3 System.Resources.ResourceWriter has become System.Resources.ReaderWriter and has the following coverage details with aggregate to 80 %, the product coverage is 86% and 95%. To improve upon net coverage is only possible by a thorough testing of the spec line by line

@stephentoub :I am closing this issue for now. Do reopen it if you think higher coverage is needed !!

Name | Covered  | Uncovered | Coverable | Total         | Coverage
---------| -------------| --------------- | -------------- | ------------- | -------------
System.Resources.ReaderWriter | 357 | 89 | 446 | 1016 | 80%
**Core Product** :|
System.Resources.ResourceReader | 223 | 36 | 259 |487 |86.1%
System.Resources.ResourceWriter |103 | 5 | 108 | 272 | 95.3% 
**Helper Code** :|
System.Resources.FastResourceComparer | 10 |  6 | 16 | 49 | 62.5% 
System.SR | 21 | 42 | 63 | 208 | 33.3%
