### ISSUE TITLE
Fill out AppDomain

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#9327]
There are several buckets here, which likely should be broken out.

We know .UnhandledException, .CurrentDomain, .GetAssemblies, .GetCurrentThreadId are heavily used in Xamarin/Unity and should be straightforward to add.

DefineDynamicAssembly is in the next bucket.

True AppDomain support would be a larger challenge. We may distinguish design time support (eg for Unity IDE) vs. bulletproof runtime level support.

**Comment by leppie** [comment]
`AssemblyResolve` is a must have too

**Comment by mellinoe** [comment]
> True AppDomain support would be a larger challenge. We may distinguish design time support (eg for Unity IDE) vs. bulletproof runtime level support.

Could you expand on this a bit? From what I understand of Unity, we would need to support full runtime-level support for their use cases to work.

**Comment by justinvp** [comment]
Related: #6398

**Comment by tenor** [comment]
Please consider https://github.com/dotnet/coreclr/issues/5563.

**Comment by danmosemsft** [comment]
Specifically, using the specific mobile corpus I have these are the subset that dominate usage. None of them appear to require that there's more than the primary app domain, so they're clearly the place to start.

```
P:System.AppDomain.CurrentDomain
M:System.AppDomain.get_CurrentDomain
M:System.AppDomain.GetAssemblies
E:System.AppDomain.UnhandledException
M:System.AppDomain.add_UnhandledException(System.UnhandledExceptionEventHandler)
M:System.UnhandledExceptionEventHandler.#ctor(System.Object,System.IntPtr)
P:System.UnhandledExceptionEventArgs.ExceptionObject
M:System.UnhandledExceptionEventArgs.get_ExceptionObject
P:System.AppDomain.BaseDirectory
M:System.AppDomain.get_BaseDirectory
P:System.AppDomain.RelativeSearchPath
M:System.AppDomain.get_RelativeSearchPath
M:System.AppDomain.remove_UnhandledException(System.UnhandledExceptionEventHandler)
```

**Comment by danmosemsft** [comment]
@joshfree This needs breaking out for CoreRT (albeit in this db). It would be great to start work on that.

**Comment by morganbr** [comment]
CreateInstanceAndUnwrap does require true AppDomain support (and possibly remoting), so I'd suggest throwing from that. SetupInformation looks very problematic as well on .NET Native (it pulls in AppDomainManagers, ApplicationTrust, and possibly other things that aren't really meaningful without multiple AppDomains and/or partial trust).

Evidence is very problematic to do correctly and can't entirely be done cross-platform. I believe @JeremyKuhne was thinking about what to do about that.

**Comment by JeremyKuhne** [comment]
> Evidence is very problematic to do correctly and can't entirely be done cross-platform. I believe @JeremyKuhne was thinking about what to do about that.

I've looked into Evidence as IsolatedStorage uses it for placing folders in a "known" spot. I've emulated the usage for now (getting the CodeBase (Url) and StrongName).

**Comment by danmosemsft** [comment]
Here is what I believe is the final list ofr .NET Standard 2.0:

```
T:System.AppDomain
M:System.AppDomain.get_BaseDirectory
M:System.AppDomain.get_CurrentDomain
M:System.AppDomain.get_DynamicDirectory
M:System.AppDomain.get_FriendlyName
M:System.AppDomain.get_Id
M:System.AppDomain.get_IsFullyTrusted
M:System.AppDomain.get_IsHomogenous
M:System.AppDomain.get_MonitoringIsEnabled
M:System.AppDomain.set_MonitoringIsEnabled(System.Boolean)
M:System.AppDomain.get_MonitoringSurvivedMemorySize
M:System.AppDomain.get_MonitoringSurvivedProcessMemorySize
M:System.AppDomain.get_MonitoringTotalAllocatedMemorySize
M:System.AppDomain.get_MonitoringTotalProcessorTime
M:System.AppDomain.get_RelativeSearchPath
M:System.AppDomain.get_ShadowCopyFiles
M:System.AppDomain.AppendPrivatePath(System.String)
M:System.AppDomain.ApplyPolicy(System.String)
M:System.AppDomain.ClearPrivatePath
M:System.AppDomain.ClearShadowCopyPath
M:System.AppDomain.CreateDomain(System.String)
M:System.AppDomain.ExecuteAssembly(System.String)
M:System.AppDomain.ExecuteAssembly(System.String,System.String[])
M:System.AppDomain.ExecuteAssembly(System.String,System.String[],System.Byte[],System.Configuration.Assemblies.AssemblyHashAlgorithm)
M:System.AppDomain.ExecuteAssemblyByName(System.Reflection.AssemblyName,System.String[])
M:System.AppDomain.ExecuteAssemblyByName(System.String)
M:System.AppDomain.ExecuteAssemblyByName(System.String,System.String[])
M:System.AppDomain.GetAssemblies
M:System.AppDomain.GetCurrentThreadId
M:System.AppDomain.GetData(System.String)
M:System.AppDomain.GetType
M:System.AppDomain.IsCompatibilitySwitchSet(System.String)
M:System.AppDomain.IsDefaultAppDomain
M:System.AppDomain.IsFinalizingForUnload
M:System.AppDomain.Load(System.Reflection.AssemblyName)
M:System.AppDomain.Load(System.Byte[])
M:System.AppDomain.Load(System.Byte[],System.Byte[])
M:System.AppDomain.Load(System.String)
M:System.AppDomain.ReflectionOnlyGetAssemblies
M:System.AppDomain.SetCachePath(System.String)
M:System.AppDomain.SetData(System.String,System.Object)
M:System.AppDomain.SetPrincipalPolicy(System.Security.Principal.PrincipalPolicy)
M:System.AppDomain.SetShadowCopyFiles
M:System.AppDomain.SetShadowCopyPath(System.String)
M:System.AppDomain.SetThreadPrincipal(System.Security.Principal.IPrincipal)
M:System.AppDomain.Unload(System.AppDomain)
M:System.AppDomain.add_AssemblyLoad(System.AssemblyLoadEventHandler)
M:System.AppDomain.remove_AssemblyLoad(System.AssemblyLoadEventHandler)
M:System.AppDomain.add_AssemblyResolve(System.ResolveEventHandler)
M:System.AppDomain.remove_AssemblyResolve(System.ResolveEventHandler)
M:System.AppDomain.add_DomainUnload(System.EventHandler)
M:System.AppDomain.remove_DomainUnload(System.EventHandler)
M:System.AppDomain.add_FirstChanceException(System.EventHandler{System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs})
M:System.AppDomain.remove_FirstChanceException(System.EventHandler{System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs})
M:System.AppDomain.add_ProcessExit(System.EventHandler)
M:System.AppDomain.remove_ProcessExit(System.EventHandler)
M:System.AppDomain.add_ResourceResolve(System.ResolveEventHandler)
M:System.AppDomain.remove_ResourceResolve(System.ResolveEventHandler)
M:System.AppDomain.add_TypeResolve(System.ResolveEventHandler)
M:System.AppDomain.remove_TypeResolve(System.ResolveEventHandler)
M:System.AppDomain.add_UnhandledException(System.UnhandledExceptionEventHandler)
M:System.AppDomain.remove_UnhandledException(System.UnhandledExceptionEventHandler)
T:System.AppDomainUnloadedException
M:System.AppDomainUnloadedException.#ctor
M:System.AppDomainUnloadedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
M:System.AppDomainUnloadedException.#ctor(System.String)
M:System.AppDomainUnloadedException.#ctor(System.String,System.Exception)
```

**Comment by gkhanna79** [comment]
CC @kouvel

**Comment by rahku** [comment]
These need to be added too
T:System.CannotUnloadAppDomainException
M:System.CannotUnloadAppDomainException.#ctor
M:System.CannotUnloadAppDomainException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
M:System.CannotUnloadAppDomainException.#ctor(System.String)
M:System.CannotUnloadAppDomainException.#ctor(System.String,System.Exception)

**Comment by ramarag** [comment]
These need to be added here too:
T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs
M:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.#ctor(System.Exception)
P:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception
M:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.get_Exception

**Comment by danmosemsft** [comment]
I see a dependency on `T:System.Security.Principal.PrincipalPolicy`. That's just an enum you'll want to add.

**Comment by rahku** [comment]
I have implemented and exposed most of the apis.
Apis remaining are
        public Assembly[] GetAssemblies() { throw null; }
        public event AssemblyLoadEventHandler AssemblyLoad { add { } remove { } }
        public event ResolveEventHandler AssemblyResolve { add { } remove { } }
        public event ResolveEventHandler TypeResolve { add { } remove { } }
        public event ResolveEventHandler ResourceResolve { add { } remove { } }
        public void SetPrincipalPolicy(System.Security.Principal.PrincipalPolicy policy) { }
        public void SetThreadPrincipal(System.Security.Principal.IPrincipal principal) 
testing for ExecuteAssembly is blocked as Assembly.LoadFrom is not exposed yet
Testing for ExecuteAssemblyByName is blocked due to Assembly.Load(AssemblyName assemblyRef) is not yet supported in VM

**Comment by gkhanna79** [comment]
> Testing for ExecuteAssemblyByName is blocked due to Assembly.Load(AssemblyName assemblyRef) is not yet supported in VM

This works today as we use it across the board. See https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Loader/tests/DefaultContext/DefaultLoadContextTest.cs#L129 as an example.

**Comment by rahku** [comment]
check why unhandledException test causes xunit to crash on OSX

**Comment by rahku** [comment]
>This works today as we use it across the board

Donno how it works. I hit this exception. 
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Reflection/Assembly.cs#L324
https://github.com/dotnet/coreclr/blob/master/clr.coreclr.props#L67

**Comment by gkhanna79** [comment]
That is because the AssemblyRef has a codebase associated with it. This was not supported in Phone but if we want to support it for .NET Core, it can be done via ALC.LoadFromAssemblyPath

**Comment by danmosemsft** [comment]
This is what still remains from `AppDomain`
```
    public sealed class AppDomain : MarshalByRefObject {
        public event ResolveEventHandler ReflectionOnlyAssemblyResolve;
        public new Type GetType();
        public override object InitializeLifetimeService();
        public void SetDynamicBase(string path);
    }
```

**Comment by rahku** [comment]
These overrides will be excluded for net core
public new Type GetType();
public override object InitializeLifetimeService();
