### ISSUE TITLE
Fill out Convert

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#9328]
We removed much of the members for cleanup reasons - many times because they are useless, eg., Convert.ToBoolean(DateTime) always throws InvalidCastException. There was also a layering issue with DBNull. We should bring these back.

    public static class Convert {
        public static readonly object DBNull;
        public static object ChangeType(object value, TypeCode typeCode);
        public static bool IsDBNull(object value);
        public static int ToBase64CharArray(byte[] inArray, int offsetIn, int length, char[] outArray, int offsetOut, Base64FormattingOptions options);
        public static string ToBase64String(byte[] inArray, Base64FormattingOptions options);
        public static string ToBase64String(byte[] inArray, int offset, int length, Base64FormattingOptions options);
        public static bool ToBoolean(char value);
        public static bool ToBoolean(DateTime value);
        public static byte ToByte(DateTime value);
        public static char ToChar(bool value);
        public static char ToChar(char value);
        public static char ToChar(DateTime value);
        public static char ToChar(decimal value);
        public static char ToChar(double value);
        public static char ToChar(float value);
        public static DateTime ToDateTime(bool value);
        public static DateTime ToDateTime(byte value);
        public static DateTime ToDateTime(char value);
        public static DateTime ToDateTime(DateTime value);
        public static DateTime ToDateTime(decimal value);
        public static DateTime ToDateTime(double value);
        public static DateTime ToDateTime(short value);
        public static DateTime ToDateTime(int value);
        public static DateTime ToDateTime(long value);
        public static DateTime ToDateTime(sbyte value);
        public static DateTime ToDateTime(float value);
        public static DateTime ToDateTime(ushort value);
        public static DateTime ToDateTime(uint value);
        public static DateTime ToDateTime(ulong value);
        public static decimal ToDecimal(char value);
        public static decimal ToDecimal(DateTime value);
        public static double ToDouble(char value);
        public static double ToDouble(DateTime value);
        public static short ToInt16(DateTime value);
        public static int ToInt32(DateTime value);
        public static long ToInt64(DateTime value);
        public static sbyte ToSByte(DateTime value);
        public static float ToSingle(char value);
        public static float ToSingle(DateTime value);
        public static string ToString(string value);
        public static string ToString(string value, IFormatProvider provider);
        public static ushort ToUInt16(DateTime value);
        public static uint ToUInt32(DateTime value);
        public static ulong ToUInt64(DateTime value);
    }

**Comment by danmosemsft** [comment]
We've decided to track missing API in less granular issues, tracking each major area/issue, and break down as needed. Closing.

**Comment by danmosemsft** [comment]
Go ahead and do this one. Note you'll need to start by editing model.xml for many of them.

**Comment by Lixire** [comment]
Gotcha. I'll start as soon as I submit a PR for the BitArray issue (I'm currently rebuilding corefx due to some problems)

**Comment by danmosemsft** [comment]
I did the model.xml edits, see  https://github.com/dotnet/coreclr/commit/4a13a029ef492ce167cf2ec0e46ae5e5cd08dda2
You can do the corefx work.

**Comment by Lixire** [comment]
@danmosemsft I rebased my changes on top of dev/api but the new members don't seem to show up even though I'm using the latest coreclr package (eg. 'Convert' does not contain a definition for 'IsDBNull'). Your changes do show up in model.xml and mscorlib.cs and the members are also implemented in coreclr so I'm a little confused.

**Comment by Lixire** [comment]
Merged
