### ISSUE TITLE
Fill out GC class

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#9329]
Below is what's in Xamarin Android but not in Core. If these are all still in the implementation, we should expose them.

    public static class GC {
        public static void CancelFullGCNotification();
        public static int GetGeneration(WeakReference wo);
        public static void RegisterForFullGCNotification(int maxGenerationThreshold, int largeObjectHeapThreshold);
        public static GCNotificationStatus WaitForFullGCApproach();
        public static GCNotificationStatus WaitForFullGCApproach(int millisecondsTimeout);
        public static GCNotificationStatus WaitForFullGCComplete();
        public static GCNotificationStatus WaitForFullGCComplete(int millisecondsTimeout);
    }
    public enum GCNotificationStatus {
        Canceled = 2,
        Failed = 1,
        NotApplicable = 4,
        Succeeded = 0,
        Timeout = 3,
    }

**Comment by mellinoe** [comment]
Most of them don't seem to be implemented in .NET Native: https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/System/GC.cs.

**Comment by jkotas** [comment]
Right, it is work to implement them...

**Comment by Maoni0** [comment]
this is all implemented on coreclr so it's a matter of exposing the APIs.

**Comment by Maoni0** [comment]
I will let .net native folks decide if/how they wanna do this work. @sergiy-k

**Comment by danmosemsft** [comment]
Incidentally I didn’t list members that aren’t in Xamarin either (eg TryStartNoGCRegion) as desktop parity is not a current goal.

**Comment by danmosemsft** [comment]
Transmuting this issue to track adding the missing members to project N. The subset of the ones above that aren't on Project N seems to be those listed below

```
public static class GC {
    public static void CancelFullGCNotification();
    public static void RegisterForFullGCNotification(int maxGenerationThreshold, int largeObjectHeapThreshold);
    public static GCNotificationStatus WaitForFullGCApproach();
    public static GCNotificationStatus WaitForFullGCApproach(int millisecondsTimeout);
    public static GCNotificationStatus WaitForFullGCComplete();
    public static GCNotificationStatus WaitForFullGCComplete(int millisecondsTimeout);
}
public enum GCNotificationStatus {
    Canceled = 2,
    Failed = 1,
    NotApplicable = 4,
    Succeeded = 0,
    Timeout = 3,
}
```

ie `GetGeneration` is implemented there already.

**Comment by danmosemsft** [comment]
Not sure whether this should move to the CoreRT repo now.

**Comment by jkotas** [comment]
@danmosemsft  There is work to even on CoreCLR: The members are in the source code, but not in the build / public surface. And there are no tests - at least some basic tests have to be added together with exposing it in the public surface.

**Comment by jkotas** [comment]
> The subset of the ones above that aren't on Project N seems to be those listed below

Note that there are two overloads of `GetGeneration`: one that takes `Object` and other that takes `WeakReference`. The one that takes `WeakReference` is missing.

**Comment by akoeplinger** [comment]
> Below is what's in Xamarin Android ...

Apart from GetGeneration() none of those methods are actually implemented in Mono/Xamarin, they throw NotImplementedException.

**Comment by danmosemsft** [comment]
@akoeplinger Correct, we need to expose the same surface area (for binary compat) even if it throws NIE.

Clearly, we're still figuring out how to track this kind of work most efficiently...

**Comment by gkhanna79** [comment]
I have assigned this to @kouvel and @sergiy-k to drive the exposure of the APIs in .NET Core, add tests, validate them on CoreCLR and have a plan for .NET Native.

CC @Maoni0

**Comment by danmosemsft** [comment]
@kouvel is this now covered sufficiently by #11866?

**Comment by kouvel** [comment]
Yes this is fully covered by #11866, closing this one
