### ISSUE TITLE
Improve code coverage for System.Text.Encoding.CodePages (74.8%)

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#933]
According to the current code coverage report, this library is only at 66%.  Our general goal is closer to 90%, though this will depend on the library.  We should investigate to see whether the current coverage level is appropriate, and if not, improve our test suites to provide better coverage.

**Comment by joshfree** [comment]
@eerhardt could you take a quick look while Matt is out?

**Comment by allan-silva** [comment]
@danmosemsft 
Hi, I'm looking for first contribution opportunity. So like the guide says, I made query by 'up-for-grabs' and 'easy'. This issue seems a good start. 
So should I just fork the repo and start work, or I missed any step?

Thanks!

**Comment by tarekgh** [comment]
@allan-silva yes, you can pick this one. You can fork the repo and create your changes and then submit a PR against the master branch of the repo. Please use the following 2 links to familiarize yourself with the build and the code coverage. let me know if you need any help.

https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/contributing.md
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md

**Comment by allan-silva** [comment]
Thanks @tarekgh, I'll take a look.

**Comment by allan-silva** [comment]
@tarekgh, I started work on this (ISCIIEncoding), just to know, can this issue be assigned to me? Or it is assigne to who open the first PR?

**Comment by tarekgh** [comment]
@allan-silva don't worry about assigning this issue. Just go ahead and open a PR for your changes. Thanks.

**Comment by allan-silva** [comment]
@tarekgh, Should I cover unsafe code like bellow and, consequently, mark project to allow unsafe code ?

https://github.com/dotnet/corefx/blob/95b21631b4f72e5ecbb6338a3fc7ae9345b5144e/src/Common/src/CoreLib/System/Text/EncoderNLS.cs#L123

**Comment by stephentoub** [comment]
I'm closing this due to age and the numbers here are very stale.  We should revisit where code coverage is most impactful to improve.
