### ISSUE TITLE
Improve code coverage for System.Xml.XPath.XDocument

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#935]
According to the current code coverage report, this library is only at 54.5%.  Our general goal is closer to 90%, though this will depend on the library.  We should investigate to see whether the current coverage level is appropriate, and if not, improve our test suites to provide better coverage.

**Comment by danmosemsft** [comment]
This code was moved into System.Private.Xml. It's probably more useful to have new issue for that.
