### ISSUE TITLE
[Ping] Unix - System.Net.Ping ignores PingOptions

### ISSUE THREAD

**Issue by irwiss** [dotnet/corefx#9350]
[Relevant code](https://github.com/dotnet/corefx/blob/master/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.Unix.cs#L59)

Ignoring DontFragment or TTL produces different behaviour between linux and windows builds when implementing a simple ICMP trace.

Is this the intended/by-design behaviour? Wouldn't a NotImplementedException if PingOptions are given/non default be a nicer signal to the developer?

**Comment by davidsh** [comment]
cc: @stephentoub @CIPop

**Comment by stephentoub** [comment]
@irwiss, can you try running undo sudo and see if you get different results?

**Comment by irwiss** [comment]
Can you give more details on 'undo sudo'? I'm not sure what you mean, the process wasn't run as super user.

I can construct a console project to demonstrate the difference but it's just making Ping send a packet with options to specify low TTL (around 2) to a remote site with icmp enabled thats >2 hops away.

On windows you'll get the node at the hop you chose (or whatever hop you choose) reply with TtlExpired.
On unix you'll get Success since the PingOptions aren't passed anywhere except to fake the response back to user code.

**Comment by stephentoub** [comment]
> Can you give more details on 'undo sudo'? I'm not sure what you mean, the process wasn't run as super user.

That's what I mean, try running as root / a super user, e.g. instead of:
```
./yourprogram
```
doing
```
sudo yourprogram
```

**Comment by irwiss** [comment]
Running as root doesn't make a difference, I'm not sure what difference it should make as `options` argument is ignored in the unix implementation in both raw sockets and via ping utility. Here's the relevant code and output:

project.json reference
`System.Net.Ping": "4.0.0-*"`

code in Main()

```
            using (Ping pinger = new Ping())
            {
                PingReply reply = pinger.SendPingAsync("google.com", 5000, new byte[] { 0xff }, new PingOptions(1, true)).Result;
                Console.WriteLine($"status: {reply.Status} address: {reply.Address}");
                Console.ReadLine();
            }
```

As normal user on unix (172.217.16.206 is the final hop ip, not the intended first hop):
```
appdev@hostname:~/pingtest$ dotnet run
Project pingtest (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
status: Success address: 172.217.16.206
```

As root on unix:
```
root@hostname:/home/appdev/pingtest# dotnet run
Project pingtest (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
status: Success address: 172.217.16.206
```

Same code on windows in a .NET Core application (10.0.0.254 is local gateway):

`status: TtlExpired address: 10.0.0.254`


Trace output on the unix host (just to show that 172.217.16.206 is definitely NOT the first hop)
```
root@hostname:/home/appdev/pingtest# mtr google.com -n --report -c 2
Start: Sat Jun 11 17:17:29 2016
HOST: hostname.com               Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- ???                       100.0     2    0.0   0.0   0.0   0.0   0.0
  2.|-- 104.207.130.1              0.0%     2    5.4   2.9   0.3   5.4   3.5
  3.|-- 46.33.81.29                0.0%     2    0.3   0.4   0.3   0.5   0.0
  4.|-- 89.149.183.78              0.0%     2    0.7   0.6   0.5   0.7   0.0
  5.|-- 72.14.221.74               0.0%     2    1.4   0.9   0.5   1.4   0.0
  6.|-- 216.239.58.239             0.0%     2    0.7   0.7   0.7   0.7   0.0
  7.|-- 216.239.40.235             0.0%     2    1.0   0.9   0.8   1.0   0.0
  8.|-- 172.217.16.206             0.0%     2    0.7   0.7   0.7   0.8   0.0

```

**Comment by stephentoub** [comment]
> as  options  argument is ignored in the unix implementation in both raw sockets and via ping utility

Hmm, you're right, I was misremembering.  I thought we used it in the raw sockets implementation, hence my question.

@mellinoe?

**Comment by mellinoe** [comment]
Are those properties supported now? If so, then we can just start using them and this should work. They must have thrown some exception at the time I was implementing this.

**Comment by irwiss** [comment]
I don't know if they're supported and I'm cool with stuff that's not supported, after all .net core is fairly new product and I expect some APIs to be left out.

My point is that TTL and DontFragment in PingOptions change the purpose of the call from a generic ping to icmp trace or mtu discovery, which are fairly orthogonal to the purpose of a regular ping request.

As I understand it, even if the socket options are supported in raw sockets it will still silently swallow PingOptions if it decides it can't use raw sockets and calls ping cli instead bringing back the same issue of doing something other than what the original code specified.

Having it raise an exception would save me a lot of time as I'd figure out it's not supported without poking through framework source and I'd parse some CLI tool output instead myself.

**Comment by mellinoe** [comment]
@stephentoub @davidsh How do we feel about the raw-sockets ping and the "non-elevated" ping behaving differently here? The proposed change here would be:

* Support `PingOption` in the Unix raw sockets implementation. Unix sockets support these options now.
* Throw a `NotSupportedException` if `PingOptions` are used without raw socket permissions, instead of ignoring the parameter.

**Comment by stephentoub** [comment]
> Throw a  NotSupportedException  if  PingOptions  are used without raw socket permissions

This means that code written against 1.0 would start throwing NotSupportedException when upgraded?

**Comment by mellinoe** [comment]
> This means that code written against 1.0 would start throwing NotSupportedException when upgraded?

Yes, that would happen. Instead of ignoring the parameter, we'd throw.

**Comment by davidsh** [comment]
>Yes, that would happen. Instead of ignoring the parameter, we'd throw. 

That would be a breaking change.  You can't add new exceptions being thrown from one release to the next.

**Comment by mellinoe** [comment]
Yes, I'm aware it would be a breaking change. Shouldn't we have a bit more flexibilty to make breaking changes like this in our .NET Core libraries, especially on new platforms?

**Comment by davidsh** [comment]
@ericstj can comment on the rules for breaking changes.  But I don't think doing a breaking change like that from 1.0 to 1.1 is a good idea.

**Comment by irwiss** [comment]
I'd argue that majority of the code that currently enjoys being error free is also currently completly broken, you don't specify PingOptions out of the blue, you only need it for a specific purpose and ignoring it is already a silent breaking change vs running on windows

**Comment by mellinoe** [comment]
Right now, `Socket.DontFragment` is not supported in our Unix sockets implementation. I'm looking into getting that implemented, then we would be able to fully support `PingOptions`. I'm still curious to hear others' feelings about breaking compat in the case where the options are silently ignored.

**Comment by iSazonov** [comment]
In PowerShell Core repo we plan to migrate `Test-Connection` cmdlet from WMI to .Net. It would be good to fix the Issue - I still see it [here](https://github.com/dotnet/corefx/blob/7ce4889d1de78d251d7e536ee174ff8640fa8583/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.Unix.cs#L71).

**Comment by iSazonov** [comment]
It seems to me that this breaking change is a fiction - I implemented Test-Connection cmdlet in PowerShell Core, it works on Windows well, but really does not work on Unix in some cases, so there is absolutely no difference whether it doesn't work silently or occurs throw. I would even say that it is better to get an throw that would not mislead users.
