### ISSUE TITLE
Improve code coverage for System.Xml.XPath.XmlDocument

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#936]
According to the current code coverage report, this library is only at 15%! Our general goal is closer to 90%, though this will depend on the library.  We should investigate to see whether the current coverage level is appropriate, and if not, improve our test suites to provide better coverage.

**Comment by VanJanssen** [comment]
When I inspected this code I noticed the following.

Of all the classes that are tested (and listed below), only the bold ones are contained in the corefx\src\System.Xml.XPath.XmlDocument\src folder. The rest of those classes are contained in corefx\src\Common\src.
1. Resources.Strings
1. System.ArrayT
1. System.NotImplemented
1. System.SR
1. System.Xml.Base64Encoder
1. System.Xml.Bits
1. **System.Xml.DocumentXmlWriter**
1. **System.Xml.DocumentXPathNavigator**
1. **System.Xml.DocumentXPathNodeIterator_AllElemChildren**
1. **System.Xml.DocumentXPathNodeIterator_AllElemChildren_AndSelf**
1. **System.Xml.DocumentXPathNodeIterator_ElemChildren**
1. **System.Xml.DocumentXPathNodeIterator_ElemChildren_AndSelf**
1. **System.Xml.DocumentXPathNodeIterator_ElemChildren_AndSelf_NoLocalName**
1. **System.Xml.DocumentXPathNodeIterator_ElemChildren_NoLocalName**
1. **System.Xml.DocumentXPathNodeIterator_ElemDescendants**
1. **System.Xml.DocumentXPathNodeIterator_Empty**
1. System.Xml.Ref
1. System.Xml.Schema.XmlUntypedConverter
1. System.Xml.Schema.XsdDateTime
1. System.Xml.SecureStringHasher
1. System.Xml.ValidateNames
1. System.Xml.XmlAttributeCollectionEx
1. **System.Xml.XmlAttributeEx**
1. System.Xml.XmlCharType
1. System.Xml.XmlConvertEx
1. **System.Xml.XmlDocumentEx**
1. System.Xml.XmlExceptionHelper
1. **System.Xml.XmlNodeEx**
1. System.Xml.XmlNodeListEnumerator
1. System.Xml.XmlParsingHelper
1. System.Xml.XmlRawWriter
1. System.Xml.XmlRawWriterBase64Encoder
1. **System.Xml.XmlWellFormedWriter**
1. **System.Xml.XPath.XmlDocumentExtensions**
1. System.Xml.XPath.XPathNavigatorE
1. **System.Xml.XPathNodeList**

Other assemblies provide some coverage for the classes in corefx\src\Common\src. Is it possible to test everything in common in one place, or should this be done separately for every assembly?

Also, is there a naming convention for namespaces in test files? I can't find a pattern in the existing tests.

**Comment by stephentoub** [comment]
@krwq?

**Comment by krwq** [comment]
Yes, the coverage sounds pretty terrible. I don't believe it is appropriate. Also the question is if we should test behavior according to Xml/XPath spec or the old Desktop behavior. We must aim either for compat or for the spec. I personally think that spec should be the guideline although making breaking changes is not nice either. @ericstj, any thoughts?

> Is it possible to test everything in common in one place, or should this be done separately for every assembly?
Our goal is to have a good product and not good number on the coverage report so we can test it either in one of the products or create separate solution. Whatever we choose we will get to the goal. IMO it is more important to test it properly than thinking about how to solve meaningless engineering problem.

> Also, is there a naming convention for namespaces in test files? I can't find a pattern in the existing tests.
I don't think we have any convention especially not in Xml (this is mostly really old code). For new code I would just use any convention and just be consistent with it - it doesn't really matter as long as we test the product - it is just a name, right?

**Comment by danmosemsft** [comment]
This code was moved into System.Private.Xml. It's probably more useful to have new issue for that.
