### ISSUE TITLE
System.Diagnostics.PerformanceCounter is missing in .Net Core

### ISSUE THREAD

**Issue by srinigithub2016** [dotnet/corefx#9376]
missing  Performance counter in .Net Core

**Comment by danmosemsft** [comment]
This is not currently available in Xamarin on mobile, so it would be motivated by Desktop compat. Marking Future for now.

**Comment by danmosemsft** [comment]
Not in NS 2.0

**Comment by joperezr** [comment]
related: #10633

**Comment by karelz** [comment]
Dupe of #3906.
