### ISSUE TITLE
Improve test coverage for Comparer/EqualityComparer of enums

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#9379]
The runtime has special logic to create Comparer/EqualityComparer of enums, but we do not seem to have any tests to exercise these special paths.

**Comment by jkotas** [comment]
cc @jamesqo

**Comment by GSPP** [comment]
Copying over my comments to here:

> I looked at all test files of the pattern comparer*.cs and I did not find tests for negative integers and negative enums yet. I advocate that we create test cases for each primitive type and for each primitive wrapped in an enum.

<hr>

Quote:

The comparer tests also seem quite ad-hoc. I'd do it like that:

```
var testCases = new object[] {
 new { Type = typeof(int), A = (object)1, B = (object)-1, ExpectedResult = -1 }, 
 ... //tons more
}
```

And then:

```
foreach (dynamic x in testCases) {
  var actual = Comparer<x.Type /*pseudocode, need reflection here*/>.Default.Compare(x.A, x.B);
  Assert.AreEqual(x.Expected, actual);

  //reverse
  var actual = Comparer<...>.Default.Compare(x.B, x.A);
  Assert.AreEqual(-x.Expected, actual);
}
```

That makes it easy to add cases, cleans up the very verbose tests and reduces the number of cases by half.

Can be extended for other cases as well such as `x.A.CompareTo(x.B)`.

And to be clear, the code shown above is a rough sketch. If this approach is being liked it must be done properly, the `dynamic` must go away, etc.

**Comment by GSPP** [comment]
I think there should be tests for nullable enums. Right now there are none.

**Comment by WinCPP** [comment]
Hi all,

Is this something that I can take up? Please note this will be my first attempt / contribution, so I might be slow to start.

Thanks,
Mandar

**Comment by jamesqo** [comment]
@WinCPP Whoops, I have actually fixed this previously and forgot to update this issue; sorry about that.

@jkotas Can you close this to avoid further confusion? (https://github.com/dotnet/corefx/pull/11074, https://github.com/dotnet/corefx/pull/12059)
