### ISSUE TITLE
Code coverage reported as zero for some debugger proxy classes

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/corefx#938]
E.g. [ImmutableHashSet`1DebuggerProxy.cs](https://github.com/dotnet/corefx/blob/6cc61f2c1c976fc1e392c415d9f592ca509d747f/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableHashSet%601%2BDebuggerProxy.cs)  is listed with zero coverage on the [last coverage report](http://dotnet-ci.cloudapp.net/job/dotnet_corefx_coverage_windows/37/Code_Coverage_Report/)

It should be excluded from the code coverage. Note that it already has an `[ExcludeFromCodeCoverage]`, but it looks like that applies to the VS Code Coverage tool and not to OpenCover which is used on Jenkins.

**Comment by stephentoub** [comment]
Thanks, @akoeplinger. Maybe this should be filed as an issue over at https://github.com/opencover/opencover?

**Comment by stephentoub** [comment]
That said, I actually think we should have unit tests for debugger-related types like this.  It's really easy to break these when refactoring and not realize it until someone actually tries to use that particular proxy or visualizer or display while debugging, only to find that VS doesn't provide the right details.  Testing these often involves some kind of reflection.

**Comment by stephentoub** [comment]
Actually, looking more at OpenCover, it looks like we may be able to do these exclusions by augmenting what we pass to at as command-line arguments.  I'll follow-up.
