### ISSUE TITLE
Hello. Is it possible to install CoreFX to a custom folder?

### ISSUE THREAD

**Issue by zenitfan219** [dotnet/corefx#9383]
Is it possible to install CoreFX to a custom folder after the building from sources?

Command to build:
`./build.sh x64 debug`

But in this case CoreFX installs to a current folder. What command I must enter to onfigure sources and instal to a custom folder?
PS: OS Ubuntu 16.04 LTS. Problem with building are missing.

**Comment by joperezr** [comment]
Hi @zenitfan219 thanks for posting your question. There is no easy way of selecting the drop folder of the build output. However, corefx itself doesn't install in that directory, only the output is dropped there. If you want to use the corefx that you just built in a different project, you can do this by referencing the packages that get produced in `<corefxRepoPath>/bin/packages` from your project.

Please let me know if this answers your question.

**Comment by zenitfan219** [comment]
Okay, thank You for yor answer. Then next question.

Can I use built packages in <corefxRepoPath>/bin/packages without source code? I want to delete source code without <corefxRepoPath>/bin directory. Does it work?

**Comment by joperezr** [comment]
I'm not 100% sure I get your question, but if what you want to know is if the built packages are self-contained meaning that they don't depend on source code being in your machine, then that is correct. You only need the source code to build the packages, but once they are built, you can delete all of the repo code entirely from your machine, and just reference the packages that were produced.

**Comment by zenitfan219** [comment]
Thank you, @joperezr.

And the last question. Can I build CoreFX not in repo folder?

**Comment by mellinoe** [comment]
Do you mean if you do no have corefx in a git repository? Right now, it does not work, but that's something we should fix, in my opinion. We have some build steps that add assembly metadata based on  some git information. We should be able to skip that step if there is no git repository.

For now, you'll need to be in a git repo to build.

**Comment by zenitfan219** [comment]
No.
I mean if I clonned CoreFX repo to my PC to folder `/home/<username>/MS_GIT/corefx` and produce building in folder `/home/<username>/MS_BINARIES/corefx/bin`. Is it possible?

**Comment by joperezr** [comment]
No. There is no easy way to have the output of the build be a folder different than the `<repoRoot>/bin`. That said, you could easily just wait for the build to finish and then either manually or by a script copy the outputs (all of the bin directory) to a different folder in your machine, and then use that. The reason why there is no easy way to do this is because every time you run build.sh, we basically build two phases of the repo, first the native assets and then the managed ones so it's not super straight forward to change outputs from both phases into a different folder.

**Comment by zenitfan219** [comment]
Thank you for your answers!

**Comment by joperezr** [comment]
sure no problem! happy to help :smile:
