### ISSUE TITLE
Release notes for the uCRT dependency on Windows

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/corefx#9389]
With 1.0 of .NET Core, all applications that target .NET Core and run on Windows have a [Universal CRT (UCRT)](https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/) dependency. This dependency is needed on all non-Windows 10 editions. This especially impacts the [self-contained](https://dotnet.github.io/docs/core-concepts/app-types.html) applications, as it means that the machine that they are to be run on needs to have UCRT installed. 

If the dependency is not present, applications will fail to run and errors will be thrown. The error will be:

> The program can't start because api-ms-win-crt-runtime-1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem. 

The UCRT dependency can be installed via Windows Update (name: "Update for Universal C Runtime in Windows" as according to https://support.microsoft.com/en-us/kb/2999226) and as a recommended update it will be installed automatically if the user left the default settings for Windows Update operational. It can also be downloaded from [Microsoft Download Center](https://www.microsoft.com/en-us/download/details.aspx?id=48234). 

Related issues: #9083 

/cc @joshfree @leecow @gkhanna79

**Comment by joshfree** [comment]
> If the dependency is not present, applications will fail to run and errors will be thrown.

How will it fail.  What is the exact message?  This will help with search results

> The UCRT dependency can be installed via Windows Update

Please include the exact update name.  Also include links to the correct download center page.

**Comment by blackdwarf** [comment]
The links and name is in there, waiting for the exact error message.

**Comment by ianhays** [comment]
This isn't true of the clrcompression shipped stable as 4.0.1. https://github.com/dotnet/corefx/issues/9083 had to do with the clrcompression that we were building in the open. Because of the packaging mishap and subsequent fallback to the clrcompression built from TFS, the clrcompression we shipped does not have a UCRT dependency. It is the older version (identical to the one from RC2) that links against msvcrt.dll.

**Comment by ianhays** [comment]
cc: @ericstj

**Comment by blackdwarf** [comment]
@ianhays I'm sorry, I'm unsure that I understand. What is the effect of what you said on this issue? Makes the release notes invalid/not needed?

**Comment by ianhays** [comment]
That is correct. The problem from #9083 is not present in the clrcompression that we shipped, so the release note addition of ucrt notes is not necessary.

**Comment by blackdwarf** [comment]
So...do I just close this down and remove this from the RTM known issues? What versions then does this dependency impact? RC2?

**Comment by gkhanna79** [comment]
@ianhays is simply saying that clrcompression does not have that dependency since they reverted. The rest of the product does have dependency on uCRT.

**Comment by ianhays** [comment]
>So...do I just close this down and remove this from the RTM known issues?

Yes.

>What versions then does this dependency impact? RC2?

The UCRT dependency impacts any future forks from master and all builds from master. The reversion to the TFS clrcompression occurred only in the release branch. This will need to be something we fix for 1.1.0, but #9083 is tracking that. The clrcompression shipped in RTM was the same one we shipped in RC2 - neither of which use the UCRT.

**Comment by ericstj** [comment]
Here's what I see on a machine without uCRT.
![image](https://cloud.githubusercontent.com/assets/8918108/16025465/5e2a8d04-317c-11e6-9943-3c25d2271cc2.png)

**Comment by blackdwarf** [comment]
Thanks @ericstj so it seems that we still need this. With the error I think we're good to go.

**Comment by joshfree** [comment]
Thanks all.  @blackdwarf can you post something here that can be copy and pasted by @leecow for the rel notes (and then also put it in the OneNote).  After that, feel free to close this issue.

**Comment by blackdwarf** [comment]
@joshfree here is the text:

With 1.0 of .NET Core, all applications that target .NET Core and run on Windows have a [Universal CRT (UCRT)](https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/) dependency. This dependency is needed on all non-Windows 10 editions. This especially impacts the [self-contained](https://dotnet.github.io/docs/core-concepts/app-types.html) applications, as it means that the machine that they are to be run on needs to have UCRT installed. 

If the dependency is not present, applications will fail to run and errors will be thrown. The error will be:

> The program can't start because api-ms-win-crt-runtime-1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem. 

The UCRT dependency can be installed via Windows Update (name: "Update for Universal C Runtime in Windows" as according to https://support.microsoft.com/en-us/kb/2999226) and as a recommended update it will be installed automatically if the user left the default settings for Windows Update operational. It can also be downloaded from [Microsoft Download Center](https://www.microsoft.com/en-us/download/details.aspx?id=48234).
