### ISSUE TITLE
Necessary bits for Mono.Posix

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/corefx#94]
I tried to build [Mono.Posix] (https://github.com/mono/mono/tree/master/mcs/class/Mono.Posix) against aspnetcore50 and found a lot of API that mono uses to be missing from .NET Core most prominently in the Interop-domain (like CustomMarshaler).

Please add Mono.Posix to your list of scenarios that can benefit from the API surface of .NET Core.

**Comment by ellismg** [comment]
Moving this to Immo, since I feel this is more about the set of types we expose in .NET Core than cross platform specific stuff.

**Comment by ellismg** [comment]
@Tragetaschen We've listed the APIs we plan to expose in .NET Core in the [corefx-progress](https://github.com/dotnet/corefx-progress) repo.  Can you take a look at what is exposed and help us understand if this is sufficient for Mono.Posix?

**Comment by jasonwilliams200OK** [comment]
@Tragetaschen, all the required assemblies (https://github.com/dotnet/corefx/issues/94#issuecomment-63211643) can be tracked from CoreFX-Progress repo: https://github.com/dotnet/corefx-progress/blob/master/src-diff/README.md. Most of them are already "Done" and few are pending with "Coming" status. IMO, this (broader) issue can be closed as there are specific issues opened for porting remaining assemblies by @dotnet-bot (like https://github.com/dotnet/corefx/issues/858 etc.). What do you think?

**Comment by Tragetaschen** [comment]
You are right. I'm already seeing a lot of progress and a lot of much more specific promises in focused issues (like the already referenced ones). Thanks!
