### ISSUE TITLE
build.sh script hammering proxy

### ISSUE THREAD

**Issue by darkstar** [dotnet/corefx#9410]
When trying to build corefx via the build.sh script, at some point it fetches some data from https://dotnetmyget.blob.core.windows.net

This is hammering our proxy with 5-10 requests per second, which in turn causes the proxy to rate-limit and  stall/disconnect the client, which in turn leads to failures during the build stage:

```
darkstar@kubuntu:/usr/src/corefx$ ./build.sh managed x64 debug
Setting up directories for build
Installing dotnet cli...
Restoring BuildTools version 1.0.25-prerelease-00512-01...
Initializing BuildTools...
ERROR: An error occured when trying to initialize the tools. Please check '/usr/src/corefx/init-tools.log' for more details.
./build.sh: line 107: /usr/src/corefx/Tools/corerun: No such file or directory

tail: cannot open '/usr/src/corefx/msbuild.log' for reading: No such file or directory
Build Exit Code = 127
darkstar@kubuntu:/usr/src/corefx$
```

the problem is that there is no way of recovering from such a failed build as subsequent builds will fail quite early in the process:

```
darkstar@kubuntu:/usr/src/corefx$ ./build.sh managed x64 debug
Setting up directories for build
Tools are already initialized
./build.sh: line 107: /usr/src/corefx/Tools/corerun: No such file or directory

tail: cannot open '/usr/src/corefx/msbuild.log' for reading: No such file or directory
Build Exit Code = 127
darkstar@kubuntu:/usr/src/corefx$
```

There should be an option for build.sh to not hammer the proxy with hundreds of parallel requests, or instead of requesting each and every file individually maybe something like a ZIP archive could be downloaded instead? another idea could be that the `build.sh` script checks which files are downloaded already and only downloads those that are missing/incomplete, instead of nothing (if re-running `build.sh` without cleaning) or everything (if running `clean.sh` before retrying `build.sh`)

right now I'm unable to build corefx and coreclr because of this issue. Any ideas for workarounds will be appreciated :)

**Comment by ellismg** [comment]
The hammering is likely coming from dotnet restore's parallel restore behavior.  Could you try editing init-tools.sh to add `--disable-parallel` [here](https://github.com/dotnet/corefx/blob/master/init-tools.sh#L70)?  A similar edit may be necessary in [dir.props](https://github.com/dotnet/corefx/blob/master/dir.props#L162) since we also build a dotnet restore command there.

**Comment by joperezr** [comment]
I can do that, and make it to be parallel by default and just provide a way to disable it.

**Comment by darkstar** [comment]
Okay, disabling the parallel downloads improved it somewhat, but I still get occasional timeouts from the proxy:
```
info : An error was encountered when fetching 'GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-buildtools/nuget/v3/flatcontainer/microsoft.codeanalysis.common/index.json'. The request will now be retried.
info : The HTTP request to 'GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-buildtools/nuget/v3/flatcontainer/microsoft.codeanalysis.common/index.json' has timed out after 100000ms.
info : An error was encountered when fetching 'GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.codeanalysis.common/index.json'. The request will now be retried.
info : The HTTP request to 'GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.codeanalysis.common/index.json' has timed out after 100000ms.
info :   GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.codeanalysis.common/index.json
info :   GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-buildtools/nuget/v3/flatcontainer/microsoft.codeanalysis.common/index.json
info : An error was encountered when fetching 'GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-buildtools/nuget/v3/flatcontainer/microsoft.codeanalysis.analyzers/index.json'. The request will now be retried.
info : The HTTP request to 'GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-buildtools/nuget/v3/flatcontainer/microsoft.codeanalysis.analyzers/index.json' has timed out after 100000ms.
info : An error was encountered when fetching 'GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.codeanalysis.analyzers/index.json'. The request will now be retried.
info : The HTTP request to 'GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.codeanalysis.analyzers/index.json' has timed out after 100000ms.
info :   GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.codeanalysis.analyzers/index.json
info :   GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-buildtools/nuget/v3/flatcontainer/microsoft.codeanalysis.analyzers/index.json
info :   NotFound https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.net.compilers.targets.netcore/index.json 57650ms
info :   NotFound https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/nuget.client/index.json 57579ms
info :   NotFound https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/nuget.versioning/index.json 57563ms
info :   OK https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/system.diagnostics.debug/index.json 57904ms
info :   OK https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/system.threading/index.json 57710ms
info :   OK https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/system.globalization/index.json 57888ms
info :   OK https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/system.runtime/index.json 57796ms
info :   OK https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.net.compilers.netcore/index.json 58245ms
```

But I think this might be due to out company policies, and it works fine when you're having a direct connection to the internet.

I still think it would be a good idea (long-term) to check all downloads and only download those packages that have not been fully downloaded, that way one could resume an interrupted build process without running clean.sh inbetween. Right now, after having an incomplete download like above, all I'm getting is something like this:
```
darkstar@kubuntu:/usr/src/corefx$ ./build.sh managed x64 debug
Setting up directories for build
Tools are already initialized
./build.sh: line 107: /usr/src/corefx/Tools/corerun: No such file or directory

tail: cannot open '/usr/src/corefx/msbuild.log' for reading: No such file or directory
Build Exit Code = 127
darkstar@kubuntu:/usr/src/corefx$
```

I think the "--disable-parallel" switch needs to also go into the Tools/init-tools.sh file but this file is re-fetched on every build.sh so there's no easy way to fix that. I tried patching the file after the first (unsuccessful) build.sh run and manually re-run the exact command from the /init-tools.sh file but that also seems to hit some problems. I'm still investigating though ... ;-)

**Comment by akoeplinger** [comment]
> Right now, after having an incomplete download like above, all I'm getting is something like this:

That part should be fixed with https://github.com/dotnet/corefx/pull/8621

**Comment by joperezr** [comment]
Looks like this has been fixed for some time. I'll close it now, but feel free to reopen if needed.
