### ISSUE TITLE
System.IO.FileSystem.DriveInfo is missing from .Net Core

### ISSUE THREAD

**Issue by HenryGarle** [dotnet/corefx#9413]
System.IO.FileSystem.DriveInfo is missing

https://github.com/dotnet/corefx/tree/master/src/System.IO.FileSystem/src/System/IO

https://dotnet.github.io/api/System.IO.DriveInfo.html

**Comment by ianhays** [comment]
It's still included in .NET core; it's just in its own assembly: https://github.com/dotnet/corefx/tree/master/src/System.IO.FileSystem.DriveInfo

**Comment by HenryGarle** [comment]
My mistake, you are absolutely right. Visual studio and nuget were fighting against it but its installed and functional. Sorry for the waste of time!

**Comment by ianhays** [comment]
No worries at all :) Happy coding!
