### ISSUE TITLE
[PostRTM] Introduce .depproj references for newly stable packages

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#9417]
The stable versions of contracts are embedded via a .depproj; rather than continuing to rebuild them (and potentially rewriting history).

As part of our Post-RTM tasks we should change .csproj to .depproj as appropriate, holistically.

**Comment by bartonjs** [comment]
Per a chat with EricStJ, this should only be done for subdirectories of the ref directory, but not ref itself.

Therefore System.Security.Cryptography.Algorithms\ref\{4.0,4.1}, but not System.Security.Cryptography.Algorithms\ref.  That way the (root) ref directory is always viewable in history as the changes of the contract over time.

And ApiCompat keeps us honest about bumping that version when the contents change.

**Comment by joperezr** [comment]
@bartonjs Looks like this won't be necessary anymore thanks to the package harvesting work that @ericstj made. So if you don't think otherwise, I'll just close this one.

**Comment by bartonjs** [comment]
There are times where it might still be required, but I agree they're the minority now.
