### ISSUE TITLE
[PostRTM] Change project.json references to stable packages

### ISSUE THREAD

**Issue by bartonjs** [dotnet/corefx#9418]
Part of the problem with the build frequency (#9156) is that the project.json updates frequently end up with merge conflicts (not only between the bots, but between the bots and humans).

If all of the existing references are snapped to the stable versions the updates won't be editing any files, and will continue to not need to edit any files until live dependencies on new contract API starts to creep in; making for significantly less noise than we have today.

**Comment by ericstj** [comment]
Yeah, we do this as part of our normal versioning process.  I've done so with https://github.com/dotnet/corefx/pull/9455 and mopped up with https://github.com/dotnet/corefx/pull/9524.
