### ISSUE TITLE
Failed CI build reported it completed successfully

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#942]
PR #917 had a bad P/Invoke declaration that caused a TypeLoadException and a huge number of tests to fail.  But even though the build lists a large number of test failures:

http://dotnet-ci.cloudapp.net/job/dotnet_corefx_prtest/138/#showFailuresLink

the build still shows as green / successful, and GitHub reports "all is well".

**Comment by mmitche** [comment]
@stephentoub Looks like somehow build.cmd got messed up again.  MSBuild is reporting errors but build.cmd returns 0.  This might be related to recent changes in the way we run tests.  I'll check.

**Comment by stephentoub** [comment]
Thanks for investigating, @mmitche.

**Comment by weshaggard** [comment]
I suspect this may be my recent change to dir.tarversals.target where I added ContinueOnError="ErrorAndContinue" in an attempt to make sure we continue to run all the tests and not fail fast on the first test failure. I will take care of this issue.

**Comment by mmitche** [comment]
@weshaggard Actually, that part is okay.  It's the AfterTargets + ContinueOnError that causes this problem.  There is a bug in msbuild that causes it to not keep track of the error state for tasks that are ContinueOnError in AfterTargets.

I fixed this bug a while back (when we ran tests after bujlding) by gathering up an itemgroup of the exit codes and making that an output to the test task.  Then you have to add one more level of indirection to the test running which checks the state of this item group once it's complete for any failure codes and errors if so.

**Comment by weshaggard** [comment]
Yes I remember your other change I will try to apply in to the new way we are running the tests.

**Comment by mmitche** [comment]
@weshaggard I think it might be slightly different now...before it looked like we were running all of the assemblies on the same xunit command line, now we're running multiple xunit instances.  I think it might be more challenging.

The other way to fix this is to avoid using AfterTargets.  Instead use DependsOnTargets in some fashion.

**Comment by weshaggard** [comment]
Turns out it was the ContinueOnError thing I introduced and not an AfterTargets issue this time. I've submitted PR #945 which should fix this.

**Comment by weshaggard** [comment]
Fix merged.
