### ISSUE TITLE
System.Runtime.Serialization.Formatters takes dependency on xunit.performance but has no perf tests

### ISSUE THREAD

**Issue by dsgouda** [dotnet/corefx#9420]
The perf tests are currently detected by figuring out which tests take a dependency on xunit.performance and running those test dlls with xunit performance runner.
System.Runtime.Serialization.Formatters seems to take a dependency on xunit.performance but does not have a perf test to execute
To repro: ``` msbuild .\src\System.Runtime.Serialization.Formatters\tests\System.Runtime.Serialization.Formatters.Tests.csproj /t:buildAndtest /p:performance=true /p:OSGroup=Windows_NT ```
Is this intended?

**Comment by mellinoe** [comment]
Probably just an accident or a copy-paste error. Feel free to remove it if it's causing issues.

**Comment by dsgouda** [comment]
If I remove the reference to xunit performance here the build seems to fail,
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Serialization.Formatters/tests/project.json#L18
Could you take a look

**Comment by dsgouda** [comment]
This has been resolved with commit b39944b8bad5d859ff1a5d9e64ec4cc23cfee142
