### ISSUE TITLE
TcpClient.Dispose used concurrently with ConnectAsync may not Dispose of the Socket

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#9423]
TcpClient is not documented to have thread-safe members, and in general Dispose implementations should not be used concurrently with other members on the containing types.  However, as TcpClient is a thin wrapper for a Socket, code may end up calling Dispose on the TcpClient in order to cancel in-progress async operations, such as ConnectAsync.  However, on Unix, ConnectAsync is implemented by creating a new Socket for each address it attempts to connect to, and that Socket isn't stored into the TcpClient until after a connection has been successfully established.  As a result, Dispose can't be used to cancel the connect operation, as the Socket won't have been stored yet, and in such cases the Socket won't get disposed of.

**Comment by i3arnon** [comment]
I Just yesterday published a post pretty much saying this shouldn't happen: [Not All Beginnings Must Have An End](http://blog.i3arnon.com/2016/06/13/idisposable-trumps-apm/) 

I should have checked the x-plat implementation first...

**Comment by GSPP** [comment]
Also, see https://github.com/dotnet/corefx/issues/5749 to add clean cancellation in the first place.
