### ISSUE TITLE
What is the story for Distributed Systems in .NET

### ISSUE THREAD

**Issue by SamuelCox** [dotnet/corefx#9426]
Hi,
This is a very general question about .NET so I'm not sure it really goes here, but I have no idea what repo I would put it in at all so best guess is here.
 My questions quite simple, Distributed Systems have become a massive trend in the past couple of years, what is the story for them in .NET ? It doesn't really feel like they're a first class scenario, and the only great .NET librarys I can think of for Distributed Systems is Akka.NET and Orleans. Is this something the .NET team are looking more to in the future? Or am I missing some great ways of building Distributed Systems? 

I guess just in general, as a very young developer who is a big fan of the .NET ecosystem, it seems there are a lot of doubts about c# and .NET at the moment for building, and one of those biggest doubts I see is distributed systems, and while I'm mostly inclined to disagree with them, so many are saying it now that I can't just ignore it.

If you feel this isn't an appropriate question to be asked in github, regardless of what repo, then feel free to close this issue.

**Comment by SamuelCox** [comment]
To give some context, this post was brought on at least partly by this blog:
http://byterot.blogspot.co.uk/2016/06/after-all-it-might-not-matter-commentary-status-of-dotnet-dotnetcore-csharp-oss-fsharp-dnx.html

**Comment by omariom** [comment]
Two servers communicating via ASP.NET Web API or WCF  is a distributed system.

Buy if you are interested in actors and autoscaling and resilience look at  Service Fabric.
https://channel9.msdn.com/Events/Build/2016/B874

**Comment by wangyanjun** [comment]
I have the same question. do we have any equivalent systems(for examples: Hadoop, spark, hive and so on), or at least some interactive methods. such systems are very important for today's development. Cloud services may be not suitable sometimes. So I think the new .NET ecosystem should consider distributed systems serious. 
Thanks!

**Comment by sergeybykov** [comment]
Dryad (https://en.wikipedia.org/wiki/Dryad_(programming) https://github.com/MicrosoftResearch/Dryad) was considered superior to Hadoop back in the days. It was used as a base for building of Cosmos, Microsoft internal high scale compute system used by Bing.

[Naiad](https://github.com/MicrosoftResearch/Naiad) is another system that was built by Microsoft Research SVC lab.

[Akka.Net](https://github.com/akkadotnet/akka.net), as was already mentioned, is a partial port of JVM's Akka.

[Orleans](https://github.com/dotnet/orleans/) is the distribute actor model project that my team works on.

There are .NET adapters for systems like Spark, Kafka, Storm (/cc @jthelin) as well as open-sourced libraries like WCF.

**Comment by jthelin** [comment]
You can run Apache Spark for distributed batch / data science analytics processing using C# language bindings for Spark with Project Mobius available through GitHub. 
https://github.com/Microsoft/Mobius

Mobius provides the same RDD / DStream / DataFrame based API for C# developers that are provided for Java / Scala / Python / R languages elsewhere.

Apache Spark is running on some of the biggest machine clusters in the world, and there are various teams in Microsoft already running large-scale production jobs using Spark + Mobius + C# every day. 

HTH.
