### ISSUE TITLE
Move TestSuite package to dotnet-core feed

### ISSUE THREAD

**Issue by karajas** [dotnet/corefx#9428]
To improve perf of restore and avoiding hitting multiple feeds, move the new sets of packages to the dotnet-core feed and not the dotnet-buildtools feed.

**Comment by weshaggard** [comment]
Any idea on how much this extra feed costs us in restore time?

**Comment by karajas** [comment]
Is there a way to measure the time to restore?

**Comment by weshaggard** [comment]
I would just do a restore with and without it, cleaning our package cache between the tries and measure the difference.
