### ISSUE TITLE
Centos: One or more tests failed while running tests from 'System.Collections.Tests'

### ISSUE THREAD

**Issue by CIPop** [dotnet/corefx#9444]
Can't find much in the logs:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_release_prtest/206/consoleFull#-85362248767b4762c-faac-47f0-8268-9f6835e4535e

```
11:34:53 /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_release_prtest/Tools/tests.targets(202,5): warning MSB3073: The command "/mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_release_prtest/bin/tests/AnyOS.AnyCPU.Release/System.Collections.Tests/netcoreapp1.0/RunTests.sh /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_release_prtest/packages/" exited with code 139. [/mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_release_prtest/src/System.Collections/tests/System.Collections.Tests.csproj]
11:34:53 /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_release_prtest/Tools/tests.targets(211,5): error : One or more tests failed while running tests from 'System.Collections.Tests' please check log for details! [/mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_release_prtest/src/System.Collections/tests/System.Collections.Tests.csproj]
11:34:57   System.Net.Security.Tests -> 
```

**Comment by CIPop** [comment]
/cc: @weshaggard @ericstj 

Tentatively assigned to @stephentoub: from the history, it's not obvious who owns System.Collections.

**Comment by stephentoub** [comment]
This is a seg fault:
```
/mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_release_prtest/bin/tests/AnyOS.AnyCPU.Release/System.Collections.Tests/netcoreapp1.0/RunTests.sh: line 253: 37248 Segmentation fault      (core dumped) ./corerun xunit.console.netcore.exe System.Collections.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests
```
cc: @sergiy-k, @janvorli, @gkhanna79, @joshfree

**Comment by CIPop** [comment]
@stephentoub @joshfree Where should I open an enhancement issue for the CI system to search and mark in red the text "Segmentation fault". It would also be good if the initial report would clearly mark it as "Seg fault / Crash".

**Comment by stephentoub** [comment]
> Where should I open an enhancement issue for the CI system to search and mark in red the text "Segmentation fault". 

I believe I've now correctly added it to the failure management so that it should be called out on the main leg's page.

**Comment by CIPop** [comment]
> I believe I've now correctly added it to the failure management so that it should be called out on the main leg's page

Nice, Thanks! Is there documentation for how to do this?

**Comment by stephentoub** [comment]
https://wiki.jenkins-ci.org/display/JENKINS/Build+Failure+Analyzer

**Comment by gkhanna79** [comment]
@janvorli Can you PTAL?
CC @sergiy-k

**Comment by stephentoub** [comment]
This is very likely a dup of https://github.com/dotnet/coreclr/issues/5687.  Closing this one so we have one issue tracking.
