### ISSUE TITLE
Issue, Proposal: Decimal, Double (Negative 0) ToString

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/corefx#9451]
I am having a hard time believing I never caught this before but none the less;

I must be missing something and if I am not then this should probably be corrected...

`System.BitConverter.ToDouble(System.BitConverter.GetBytes(-0.0), 0)`

Evaluates to : '0.0'

`System.BitConverter.Int64BitsToDouble(System.BitConverter.ToInt64(System.BitConverter.GetBytes(-0.0), 0))`

Evaluates to : '0.0'

But ...

`System.BitConverter.DoubleToInt64Bits(-0.0)`

Evaluates to 

'-9223372036854775808', e.g. long.MaxValue + 1.

I guess my issue / question is how to round trip negative zero in the CLR using the BitConverter..

It gets the Bytes correctly as can be seen here:

`System.BitConverter.GetBytes(-0.0)`

> {byte[8]}
>     [0]: 0
>     [1]: 0
>     [2]: 0
>     [3]: 0
>     [4]: 0
>     [5]: 0
>     [6]: 0
>     [7]: 128

`System.BitConverter.GetBytes(0.0)`

> {byte[8]}
>     [0]: 0
>     [1]: 0
>     [2]: 0
>     [3]: 0
>     [4]: 0
>     [5]: 0
>     [6]: 0
>     [7]: 0

And I believe that it actually does parse to `-0.0`.

However as can be seen by the following statement(s):

`-unchecked(-System.BitConverter.Int64BitsToDouble(long.MaxValue + 1))`

`unchecked(-System.BitConverter.Int64BitsToDouble(long.MaxValue + 1))`

`unchecked(-0.0)`

`(0.0 + -0.0)`

`System.BitConverter.GetBytes((-1.0 * 0.0))`

> {byte[8]}
>     [0]: 0
>     [1]: 0
>     [2]: 0
>     [3]: 0
>     [4]: 0
>     [5]: 0
>     [6]: 0
>     [7]: 128

`System.BitConverter.ToDouble(System.BitConverter.GetBytes((-1.0 * 0.0)), 0)`,  Evaluates to 0 but as can be seen using the following code:

`System.BitConverter.GetBytes(System.BitConverter.ToDouble(System.BitConverter.GetBytes((-1.0 * 0.0)), 0))`

You get the same bytes...

Yes I am aware there is IEEE 754, which also says that both are equal except in terms of divisions with negative numbers...

It also says

`−1.0*0.0` == `-0.0` [Wikipedia Signed Zero](https://en.wikipedia.org/wiki/Signed_zero)

You cannot evaluate an expression to negative zero because the interpreter always replaces it with absolute 0, however in memory the bytes are actually as they are given by the BitConverter or otherwise which can also be verified as follows:

`double d = -0.0;`

`*((byte*)(&d) + 7)` Evaluates to `0x80` e.g. `128`.

The following code can detect the anomaly:

```
[System.CLSCompliant(false)]
        public unsafe static bool IsNegativeZero(double* d)
        {
            //Check for -0.0
            return (*((long*)(d))).Equals(Common.Binary.NegativeZeroBits);
        }

        public unsafe static bool IsNegativeZero(ref double d)
        {
            //Make a pointer to the pointer, which when dereferenced can access the result.
            System.IntPtr value = Unsafe.AddressOf(ref d);

            //Check for -0.0
            return (*((long*)((int*)&value))).Equals(Common.Binary.NegativeZeroBits);
        }
```

This gets even more confusing with Decimals as 

`new Decimal(0, 0, 0, true, 0).Equals(-0.0m)` evaluates to true.

However 

> System.Decimal.GetBits(new Decimal(0, 0, 0, true, 0))
> {int[4]}
>     [0]: 0
>     [1]: 0
>     [2]: 0
>     [3]: -2147483648
> 
> System.Decimal.GetBits(-0.0m)
> {int[4]}
>     [0]: 0
>     [1]: 0
>     [2]: 0
>     [3]: -2147418112

Since the Decimal type itself is documented this way I find it less intrusive to deal with, however the issue still remains that the value I pass is interpreted as a different but equal value in the cases of Double and Decimal where I do not believe they should be, neither mathematically typing nor obviously with respect to their binary representation.

I guess I will go as far as to even propose that '-0.0' Should not be equal to `0.0`, furthermore that the same should also apply to Decimal with respect to the variations of Zero which are possible although I am sure that proposal can be taken elsewhere besides the corefx issues.

For instance...

`(1 / -0.0) + Double.PositiveInfinity` == `NaN`

This indicates the value is actually preserved and calculated as expected to the standard but there is no way to indicate the display of such a value without testing specifically for such and augmenting the results thereof.

The only source of information I can find in relation to this topic was from the BCL Team Blog back in 2006: [Here](https://blogs.msdn.microsoft.com/bclteam/2006/10/12/decimal-negative-zero-representation-lakshan-fernando/).

It obviates the differences between the decimal representations of negative zero but doesn't touch on the subject for the double type; although I am fairly sure after seeing this the same obviously applies there as well.

A more reasonable approach or proposal which would still be compliant to the IEEE standard would be to allow the 'sign' to be given as '+'  or '-' via the ToString and not omit it; and also to return the value parsed and not an equivalent representation.

Finally, here is a good example of a 'buggy' or weird case in my humble opinion:

`System.BitConverter.GetBytes(double.Parse("-0.0"))`

> {byte[8]}
>     [0]: 0
>     [1]: 0
>     [2]: 0
>     [3]: 0
>     [4]: 0
>     [5]: 0
>     [6]: 0
>     [7]: 0

Thanks in advance!

**Comment by tannergooding** [comment]
@juliusfriedman, this looks like an issue with the formatting logic around `-0.0`. Up until recently, it would always normalize `-0.0` to `0.0` when generating the string.

This was fixed fairly recently and should be resolved in the latest nightlies. If you could double-check that your issue is resolved, it would be greatly appreciated.

**Comment by tannergooding** [comment]
Based on your response, this looks resolved. Feel free to reopen if you feel otherwise.
