### ISSUE TITLE
Compat work for IO category

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#9465]
Break out as needed, tagging with the dev/api-xxx tags.

**Comment by danmosemsft** [comment]
Misc - broken out Close, APM, and Access Control
```
M:System.IO.Path.Combine(System.String,System.String,System.String,System.String)
F:System.IO.Path.InvalidPathChars

M:System.IO.Directory.GetLogicalDrives

M:System.IO.File.Decrypt(System.String)
M:System.IO.File.Encrypt(System.String)
M:System.IO.File.Replace(System.String,System.String,System.String)
M:System.IO.File.Replace(System.String,System.String,System.String,System.Boolean)
M:System.IO.File.WriteAllLines(System.String,System.String[])
M:System.IO.File.WriteAllLines(System.String,System.String[],System.Text.Encoding)

M:System.IO.FileInfo.Decrypt
M:System.IO.FileInfo.Encrypt

M:System.IO.FileLoadException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
M:System.IO.FileLoadException.get_FusionLog

M:System.IO.FileNotFoundException.get_FusionLog

M:System.IO.FileStream.Lock(System.Int64,System.Int64)
M:System.IO.FileStream.Unlock(System.Int64,System.Int64)
M:System.IO.FileStream.get_Handle

M:System.IO.InternalBufferOverflowException.#ctor
M:System.IO.InternalBufferOverflowException.#ctor(System.String)
M:System.IO.InternalBufferOverflowException.#ctor(System.String,System.Exception)

M:System.IO.MemoryStream.GetBuffer

M:System.IO.Stream.CreateWaitHandle
M:System.IO.Stream.ObjectInvariant
M:System.IO.Stream.Synchronized(System.IO.Stream)

M:System.IO.StreamReader.#ctor(System.String)
M:System.IO.StreamReader.#ctor(System.String,System.Boolean)
M:System.IO.StreamReader.#ctor(System.String,System.Text.Encoding)
M:System.IO.StreamReader.#ctor(System.String,System.Text.Encoding,System.Boolean)
M:System.IO.StreamReader.#ctor(System.String,System.Text.Encoding,System.Boolean,System.Int32)
M:System.IO.StreamWriter.#ctor(System.String)
M:System.IO.StreamWriter.#ctor(System.String,System.Boolean)
M:System.IO.StreamWriter.#ctor(System.String,System.Boolean,System.Text.Encoding)
M:System.IO.StreamWriter.#ctor(System.String,System.Boolean,System.Text.Encoding,System.Int32)

M:System.IO.TextReader.Synchronized(System.IO.TextReader)
M:System.IO.TextWriter.Synchronized(System.IO.TextWriter)

M:System.IO.UnmanagedMemoryAccessor.ReadArray``1(System.Int64,``0[],System.Int32,System.Int32)
M:System.IO.UnmanagedMemoryAccessor.Read``1(System.Int64,``0@)
M:System.IO.UnmanagedMemoryAccessor.WriteArray``1(System.Int64,``0[],System.Int32,System.Int32)
M:System.IO.UnmanagedMemoryAccessor.Write``1(System.Int64,``0@)

P:System.IO.FileNotFoundException.FusionLog
P:System.IO.FileStream.Handle
T:System.IO.InternalBufferOverflowException
```

**Comment by ianhays** [comment]
Remaining:

	• M:System.IO.Directory.GetLogicalDrives
	
	• M:System.IO.FileLoadException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
	• M:System.IO.FileLoadException.get_FusionLog
	
	• M:System.IO.FileNotFoundException.get_FusionLog
	
	• M:System.IO.Stream.CreateWaitHandle
	• M:System.IO.Stream.ObjectInvariant
	• M:System.IO.Stream.Synchronized(System.IO.Stream)
	
	• M:System.IO.TextReader.Synchronized(System.IO.TextReader)
	• M:System.IO.TextWriter.Synchronized(System.IO.TextWriter)
	
	• M:System.IO.UnmanagedMemoryAccessor.ReadArray``1(System.Int64,``0[],System.Int32,System.Int32)
	• M:System.IO.UnmanagedMemoryAccessor.Read``1(System.Int64,``0@)
	• M:System.IO.UnmanagedMemoryAccessor.WriteArray``1(System.Int64,``0[],System.Int32,System.Int32)
	• M:System.IO.UnmanagedMemoryAccessor.Write``1(System.Int64,``0@)
	P:System.IO.FileNotFoundException.FusionLog

**Comment by ianhays** [comment]
All of the remaining IO API's are in PR (https://github.com/dotnet/coreclr/pull/7385) to be exposed in CoreCLR. The final work item is to add/port tests and submit a CoreFX PR to add them the API's to the ref files.

I split StreamReader/StreamWriter ctors to their own issue.

**Comment by ianhays** [comment]
Hey @hughbe, do you know if we have any basic tests for FileNotFoundException? I don't see any in System.Runtime.Tests, but oddly enough we do have DirectoryNotFoundException tests.

**Comment by hughbe** [comment]
@ianhays I don't see any either in System.Runtime, System.IO or common. Following a quick git grep and github search, I'd assume there aren't any
