### ISSUE TITLE
Support retrieving the full set of resource strings for a given culture

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/corefx#948]
On .NET Framework, the `ResourceManager` allows you to get the full set of strings for a given culture by loading its `ResourceSet`. We'd like this to be possible in .NET Core (although the requirement to expose it via `ResourceSet` is not necessary, a simple `IDictionary<string, string>` or similar would suffice).

This is required in web scenarios to enable sending back the full set of resource strings to the client so that they can be utilized when performing client-side rendering via JavaScript.

**Comment by joshfree** [comment]
Linking #947 as these are both API requests for ResourceManager.  @DamianEdwards when do you need this by?

/cc @tarekgh

**Comment by DamianEdwards** [comment]
@joshfree we're starting our work on this now and we'd like these features for 1.0 so within the next month.

**Comment by ramarag** [comment]
With the 67da6227c39c5eca7fa5ce98fc2cdb91c27e40e4 you can implement the Resource Manger for example like [here] (https://gist.github.com/ramarag/6e6f58a210dd00745582)
