### ISSUE TITLE
Compat work for CAS (stub it)

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#9482]
Likely plan: bring it back so the types resolve, but do nothing.

Caveat: as desktop was written originally, sometimes the XXPermission's ctor or Demand throws some of the non-security exceptions expected of the API - for example, in the case of invalid file paths. In those situations it is not possible to simply remove the body of the permission type. Either it needs to be partially removed, or (in the ideal case - given sufficiently good tests) moved out of the type.

**Comment by morganbr** [comment]
Since partial trust is no longer supported as a security boundary, I think it's pretty important that if we bring this back, it is only stub support. That avoids the illusion of security (but there'd be even less illusion if we don't bring this back).

**Comment by danmosemsft** [comment]
We decided it's okay to have stubs because for almost all code that will run on core, they did little or nothing anyway -- Desktop and Xamarin do not enforce the boundary generally -- and we do not plan to invest more in this feature.

**Comment by danmosemsft** [comment]
This includes everything deriving from CodeAccessPermission, but not System.Security.Permissions.PrincipalPermission (which does not)

**Comment by danmosemsft** [comment]
Talked to @JeremyKuhne and this needs no context, you can go ahead and just add the stubs.

**Comment by ioanacrant** [comment]
Resolved in #10977
