### ISSUE TITLE
System.IO.Compression.ZipFile tests leak folders into temp directory

### ISSUE THREAD

**Issue by MattGal** [dotnet/corefx#9484]
The ZipFile tests create paths like this in the /tmp  or %TEMP% folders:

./ZipTestsRoot_ef3dc45b504d4ff58e009af435fb4ccc
./ZipTestsRoot_ef3dc45b504d4ff58e009af435fb4ccc/ZipTests1

On a long-running test VM, these random folders build up, and on Linux can eventually fill /tmp so hard that execution of pretty much anything is blocked.  

I'm working to prevent this from mattering in infrastructure, but if the tests could either use their current directory (which gets automatic cleanup on .NET Helix) or be more aggressive in cleaning up leaked ZipTest folders that would prevent this in the future.

**Comment by ianhays** [comment]
>I'm working to prevent this from mattering in infrastructure, but if the tests could either use their current directory (which gets automatic cleanup on .NET Helix)

Creating files in the current directory muddles up the test directory so we moved the test files all into temp.

>or be more aggressive in cleaning up leaked ZipTest folders that would prevent this in the future.

We do this (create files in TMP) in all IO tests, though I mostly tried to remove the temp files/directories when the test concluded. I haven't looked at ZipFile though - we should be able to clean that up a bit and use the TempDirectory cleanup helper we use in FileSystem.
