### ISSUE TITLE
Compat work for Collections

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#9486]

**Comment by Clockwork-Muse** [comment]
...Is this meant to cover things like the fact that `BitArray.CopyTo` throws `ArgumentException` with different parameter names in mscorlib and the version here on corefx, or should I open a new issue?

**Comment by danmosemsft** [comment]
@Clockwork-Muse that's specific enough to be another issue please -- this one tracks filling in System.Collections.* as far as it makes sense to.

**Comment by danmosemsft** [comment]
#11728 has the specific remnants.
