### ISSUE TITLE
System.Reflection.Metadata fails to build in VS

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/corefx#950]
This is related to https://github.com/dotnet/corefx/issues/745, but in this case it's not because of Xunit but because of the project reference to System.Collections.Immutable.

I tried to fix this by moving the reference to NuGet in https://github.com/dotnet/corefx/pull/946 but apparently the System.Collections.Immutable.dll is not copied to the test directory so the tests fail.

I'm a bit at a loss currently as to what to do. Can anyone shed a light why this would occur?

**Comment by nguerrera** [comment]
@akoeplinger It should definitely be a nuget dependency. There's an assumption deep in the test buildtools infrastructure at the moment that nuget packages support aspnetcore50 by name and not just an older portable profile.

/cc @FiveTimesTheFun @weshaggard who worked on the CoreCLR test running and the project reference came in as a result of that AFAICT.
