### ISSUE TITLE
Compat work for Console

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#9516]
Not much here to match Xamarin mobile, as much of it isn't there. We do miss these:

```
        public static Stream OpenStandardError(int bufferSize);
        public static Stream OpenStandardInput(int bufferSize);
        public static Stream OpenStandardOutput(int bufferSize);
        public static void Write(string format, object arg0, object arg1, object arg2, object arg3, __arglist);
        public static void WriteLine(string format, object arg0, object arg1, object arg2, object arg3, __arglist);
```

also `enum ConsoleKey`

**Comment by joperezr** [comment]
Looks like all of these were done already by @stephentoub via #9741

**Comment by joperezr** [comment]
I guess I'll leave this open so that when ArgIterator is available, I'll go and uncomment the last api that was added but commented out.

**Comment by joperezr** [comment]
After some investigation, ArgIterator might be a bit tricky to port given that it actually has internal calls to the CLR which today don't exist in CoreCLR. Also, ArgIterator is not a type that people can call, so we will revisit this in the future.

**Comment by stephentoub** [comment]
@jkotas, @danmosemsft, is ArgIterator something we're going to re-enable in CoreCLR, CoreRT?

**Comment by danmosemsft** [comment]
It's available in mobile Xamarin apps, so yes. @jkotas Does this need work on the runtime team? If so Jose can open a new issue.

**Comment by jkotas** [comment]
> ArgIterator something we're going to re-enable in CoreCLR, CoreRT?

P3. If we get to it, it will be towards the end - expensive to support, limited value. I think it is fine to not add the ArgIterator overloads to Console, at least for now. 

> ArgIterator might be a bit tricky to port given that it actually has internal calls to the CLR 

Right, it would need to live in System.Private.CoreLib. It is runtime type.

> ArgIterator is not a type that people can call

Not sure what you mean ... it has number of methods that people can call.

**Comment by danmosemsft** [comment]
The ArgIterator overloads show negligible usage, i'm going to close this as it isn't a priority.
