### ISSUE TITLE
System.Console implementations with limitations such as Color should not throw

### ISSUE THREAD

**Issue by MattGal** [dotnet/corefx#9521]
All NetCore50 implementations of System.Console I've found so far throw if any color settings are used (i.e. ForegroundColor) due to limitations of where they run.  This means that I can't use Xunit.Console.NetCore.exe against these versions because the first thing XUnit DOES is to set the console color.  

I favor turning these NotSupportedExceptions into noops... ideally with some kind of debug output that indicates to the user this happened, in case the behavior is desired so much that they're checking it out under a debugger.  Either way, I need some way to run executables that expect to set these colors on such a runtime.

**Comment by ianhays** [comment]
related: https://github.com/dotnet/corefx/pull/8853

**Comment by danmosemsft** [comment]
Matt's argument makes sense to me, as color is "just presentational". If we do this, probably getting Fore/BackgroundColor should return the value that was supposedly set, although I doubt there's much code that would notice if it didn't, because that would make it real close to a non-breaking change.

**Comment by ianhays** [comment]
There is some precedent for ignoring certain Console operations on platforms where they’re not relevant. The majority of those unsupported functions throw PlatformNotSupportedExceptions, but some (e.g. WriteLine) are no-ops.

I'm fine with expanding that to include *groundColor. i imagine that for a lot of cases missing out on setting the Color isn't going to be a terribly breaking change, so throwing a PlatformNotSupportedException is a bit harsh.

While we're talking about Console on UWP, we should look at the other functions we throw for and decide if we'd rather no-op for them: https://github.com/dotnet/corefx/blob/master/src/System.Console/src/System/ConsolePal.WinRT.cs

**Comment by weshaggard** [comment]
I"m also fine with making these noop.

**Comment by morganbr** [comment]
Some similar cases to UWP (such as Xamarin and I believe XNA or WPF) have made Console.WriteLine get output back to the debugger, which might dictate how other operations work (e.g. *groundColor can safely be a no-op while ReadLine should probably throw).

**Comment by danmosemsft** [comment]
Morgan has a good point, there's already precedent for making them no-op.
