### ISSUE TITLE
Why System.Runtime.Loader isn't available on UWP?

### ISSUE THREAD

**Issue by sunnycase** [dotnet/corefx#9539]
Load assembly at runtime is very useful for app extension purpose.
UWP apps can have the codeGeneration capability. And there is VirtualProtectFromApp function.
Why System.Runtime.Loader isn't available on UWP?

**Comment by gkhanna79** [comment]
@sunnycase Our current UWP story, for production scenarios, is based upon .NET Native static compilation which does not support dynamic loading of assemblies (at runtime). And that is not subject to just having support of VirtualProtectFromApp but more fundamental toolchain changes.

We intend to spend sometime thinking about this scenario in the near future and will update this thread as we form concrete ideas.

CC @sergiy-k @jkotas

**Comment by gulbanana** [comment]
if UWP is not able to support this API, does that mean it will not support the rest of netstandard1.5 as a consequence?

**Comment by joperezr** [comment]
> if UWP is not able to support this API, does that mean it will not support the rest of netstandard1.5 as a consequence?

AssemblyLoadContext and AssemblyExtensions are not part of netstandard so UWP still supports netstandard.

**Comment by joperezr** [comment]
Closing for now since the original question has been answered. Feel free to reopen if you have any follow ups and we will update it if this ever changes.
