### ISSUE TITLE
[dev/xml] Port XslCompiledTransform tests

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/corefx#9550]
This needs to be done as a part of dev/xml branch work.
Workload size: large

**Comment by danmosemsft** [comment]
done

**Comment by jasonwilliams200OK** [comment]
> done

Could you link a PR or commit that goes along with it? I couldn't locate `XslCompiledTransform` or `Xsl` related APIs in the code.

**Comment by weshaggard** [comment]
The xml work was done in the dev/xml branch which just merged into the dev/api branch https://github.com/dotnet/corefx/pull/10672 recently.

**Comment by jasonwilliams200OK** [comment]
Thanks @weshaggard! I was actually trying to port xunit.runners.msbuild to .NET Standard, which does Xsl parsing and requires `XslCompiledTransform` and friends. I will try to take another stab with nightly package (which is ultimately used by NuGet.Client, which in turn -- hopefully -- will fix one of the CoreCLR CI issue: dotnet/coreclr#6716) :)
