### ISSUE TITLE
Dashboard: Hook up official build results.

### ISSUE THREAD

**Issue by alexperovich** [dotnet/corefx#957]

**Comment by akoeplinger** [comment]
As I was curious what this dashboard is I asked in gitter, here's the answer from @ellismg (so it's more visible for other curious folks):

> The dashboard is a project internally that gives us a view into both our open source and closed source systems. I think there is a desire to have parts of be public at some point, but we aren't there yet. This issue was created when we took all our internal tracking sticky notes from our Kanban board and turned them into GitHub issues so we could stop using a whiteboard in the hallway and start using something publicly visible. Unfortunately, that does include issues that track internalish work that are related to Open Source.
