### ISSUE TITLE
Proposal: support for local variables in SymbolReader for Portable PDB, Linux

### ISSUE THREAD

**Issue by Dmitri-Botcharnikov** [dotnet/corefx#9570]
To support getting names of local variables from Portable PDB (see dotnet/coreclr#5809) the following method should be added to System.Diagnostics.Debug.SymbolReader (#8981):
```c#
public static bool GetLocalVariableName(string assemblyFileName, int methodToken, int localIndex, out IntPtr localVarName)
{
}
```
The output parameter `localVarName` is supposed to be marshaled as BSTR to native code.
@lucenticus @mikem8361 @seanshpark @chunseoklee

**Comment by mikem8361** [comment]
Are you going to make the change?

**Comment by Dmitri-Botcharnikov** [comment]
@mikem8361 I've prepared PR #9571 for this change
