### ISSUE TITLE
System.Collections.BitArray tests fail for netcore50aot

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/corefx#9581]
There's a slight difference in the implementations of `System.Collections.BitArray` in mscorlib and for netcore50aot (which is in the corefx repository):  netcore50aot includes a parameter name for an exception, while mscorlib does not.

[coreclr/mscorlib](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/BitArray.cs#L390):
```
if (array is int[]) {  // .... }
else if (array is byte[]) { // .... } 
else if (array is bool[]) { // .... }
else
    throw new ArgumentException(Environment.GetResourceString("Arg_BitArrayTypeUnsupported")); 
                                       // No  argument name in this message.
```
[corefx/netcore50aot](https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/BitArray.cs#L422)
```
if (array is int[]) { // ..... }
else if (array is byte[]) { // .... }
else if (array is bool[]) { // .... }
else
    throw new ArgumentException(SR.Arg_BitArrayTypeUnsupported, nameof(array));   
                               // Uses name of argument 
```
...this is causing tests to fail, because the tests verify the non-existence of the parameter name.

What should be done in this case?  Remove the parameter name from the version in corefx?  Add them to mscorlib (perhaps in future)?

(more classes' tests may fail, these are just the one I've been investigating)

**Comment by hughbe** [comment]
I'd say just add the params to coreclr - I've done it before, it's pretty easy and quick :)

**Comment by Clockwork-Muse** [comment]
@hughbe - I probably would too, I just don't know if that would be considered a company issue.
Granted, nobody should be depending on the parameter name, but still...

**Comment by tarekgh** [comment]
@Clockwork-Muse it is ok to add the parameter name in coreclr. feel free to submit a PR for it or I can take care of it in the near future. Thanks.

**Comment by Clockwork-Muse** [comment]
@tarekgh - Oh, I can take care of it, I just wanted to make sure it wouldn't be a problem.

**Comment by tarekgh** [comment]
thanks a lot @Clockwork-Muse

**Comment by tarekgh** [comment]
This is fixed with the linked PR. thanks @Clockwork-Muse for taking care with it.
