### ISSUE TITLE
  Uri.TryCreate creates wrong Uri

### ISSUE THREAD

**Issue by krk** [dotnet/corefx#9596]
Uri class duplicates everytrhing after the colon when scheme is unknown and there are unicode characters in the uri.

`Uri.TryCreate("scheme:Ç", System.UriKind.RelativeOrAbsolute, out url);`

creates `"scheme:ÇÇ"`,

`Uri.TryCreate("scheme:Ç/Ğ/İ?a=b", System.UriKind.RelativeOrAbsolute, out url);`

creates `"scheme:Ç/Ğ/İ?a=bÇ/Ğ/İ?a=b"`. 

https://connect.microsoft.com/VisualStudio/feedback/details/2844324

**Comment by davidsh** [comment]
cc: @CIPop @stephentoub @himadrisarkar

**Comment by danmosemsft** [comment]
tool added tag.

**Comment by CIPop** [comment]
@krk Thanks for reporting!

Assigning to @himadrisarkar  for triage/prioritization.
