### ISSUE TITLE
Old reference of Framework Design Guidlines

### ISSUE THREAD

**Issue by tmori3y2** [dotnet/corefx#9620]
https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/framework-design-guidelines-digest.md#fxcop

Newer reference is here:
https://msdn.microsoft.com/en-us/library/ms229042(v=vs.110).aspx

**Comment by stephentoub** [comment]
Thanks. I'm not sure which old reference you're referring to, as all of the links appear to be valid and referencing the latest available page for that topic (e.g. the FxCop link is from .NET 2.0 but I've not seen a newer version of that content on MSDN).  But I've added the link you mention in https://github.com/dotnet/corefx/commit/935018d4c6089871c82d66c43482b24cafd3b58a.
