### ISSUE TITLE
Cant instal System.Net.Security 4.0.0-rc2-24027

### ISSUE THREAD

**Issue by Lisaj** [dotnet/corefx#9621]
Hello,
i instalig nuget System.Net.Security 4.0.0-rc2-24027 to new csproj project, but take this error:
Could not install package 'runtime.native.System 4.0.0-rc2-24027'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by svick** [comment]
Could you share your project.json and the full output of running the restore?

**Comment by Lisaj** [comment]
I dont have project.json. It is csproj and i instal nuget.

Package manager output:

Attempting to gather dependency information for package 'System.Net.Security.4.0.0-rc2-24027' with respect to project 'WebApplication1', targeting '.NETFramework,Version=v4.6.1'
Attempting to resolve dependencies for package 'System.Net.Security.4.0.0-rc2-24027' with DependencyBehavior 'Lowest'
Resolving actions to install package 'System.Net.Security.4.0.0-rc2-24027'
Resolved actions to install package 'System.Net.Security.4.0.0-rc2-24027'
Install failed. Rolling back...
Package 'runtime.native.System.4.0.0-rc2-24027' does not exist in project 'WebApplication1'
Package 'runtime.native.System.4.0.0-rc2-24027' does not exist in folder 'C:\Users\prouz\onedrive\dokumenty\visual studio 2015\Projects\WebApplication4\packages'
Could not install package 'runtime.native.System 4.0.0-rc2-24027'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
========== Finished ==========

**Comment by bartonjs** [comment]
Walking through the daily builds feed, the net46 dependency graph gained runtime.native.System.Net.Security in rc2-23921 (and rc3-23921).

While the rc2 line never lost this dependency, it did clear out of the rc3 dependency subgraph in rc3-24018-00, and it does not appear to have been reintroduced since then.

So, there's probably no easy workaround for this; but if everything goes according to plan the stable version goes out on Monday, and the problem should be fixed.

**Comment by bartonjs** [comment]
I've tried with the stable version of the package (System.Net.Security 4.0.0), and that worked fine; so I'm going to go ahead and close out the issue.

Thanks for reporting the problem, please let us know if any more crop up.

**Comment by Lisaj** [comment]
Thank you for your work
