### ISSUE TITLE
[dev/xml] Merge current xml libraries on corefx into System.Xml

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/corefx#9635]
Merge the source code with current corefx xml libraries and reuse as much as possible of the work done on corefx

This needs to be done as a part of dev/xml branch work.
 Workload size: large

System.Xml.ReaderWriter
System.Xml.XmlDocument
System.Xml.XPath
System.Xml.XPath.XmlDocument
System.Xml.XmlSerializer

**Comment by danmosemsft** [comment]
Complete except for serializer which is tracked separately.
