### ISSUE TITLE
Consider options for supporting Socket.DontFragment on Unix sockets

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#9652]
Right now, setting `Socket.DontFragment` outside of windows results in an exception being thrown. We do not have a mapping for this option in `Interop.Sys.SetSockOpt`. It would be nice for this to work, especially if we can get the same behavior as Windows.

It looks like there are a couple of options. Supposedly, there exists `IP_DONTFRAG` on some systems (https://www.ibm.com/support/knowledgecenter/ssw_i5_54/apis/ssocko.htm). I'm not sure if any of the systems we support actually have this. Ubuntu/CentOS don't seem to.

There is another option, `IP_MTU_DISCOVER` (http://man7.org/linux/man-pages/man7/ip.7.html), which seems to control what we want:

```
Set or receive the Path MTU Discovery setting for a socket.
When enabled, Linux will perform Path MTU Discovery as defined
in RFC 1191 on SOCK_STREAM sockets.  For non-SOCK_STREAM
sockets, IP_PMTUDISC_DO forces the don't-fragment flag to be
set on all outgoing packets.
```

I'm not familiar with the difference between SOCK_STREAM and non-SOCK_STREAM sockets is, or which we use in our implementation. If we use non-SOCK_STREAM sockets, this seems like a good option.

For reference, it looks like [mono](https://github.com/mono/mono/blob/91734968b83a0971c041254286cdc903b26564e2/mono/metadata/socket-io.c#L445) uses `IP_DONTFRAGMENT` or `IP_MTU_DISCOVER`, based on which is available. Presumably, `IP_DONTFRAGMENT` is only available on Windows.

If we use `IP_MTU_DISCOVER`, we need to set the value to `IP_PMTUDISC_DO`, according to the above manpage.

@ericeil , @pgavlin

**Comment by mellinoe** [comment]
This is part of #9350

**Comment by stephentoub** [comment]
> I'm not familiar with the difference between SOCK_STREAM and non-SOCK_STREAM sockets is, or which we use in our implementation. If we use non-SOCK_STREAM sockets, this seems like a good option.

This is based on the option passed in when constructing the Socket.  In Ping you're doing:
```C#
using (Socket socket = new Socket(address.AddressFamily, SocketType.Raw, protocolType))
```
and it's that SocketType that's relevant here.  You're using Raw, which is SOCK_RAW, as opposed to using SocketType.Stream which is SOCK_STREAM, or SocketType.Dgram which is SOCK_DGRAM, etc.
