### ISSUE TITLE
Hashtable not in mscorlib

### ISSUE THREAD

**Issue by andschwa** [dotnet/corefx#9658]
I'm thoroughly confused and don't know what I'm doing wrong here. I have a C# project that uses a `Hashtable` (and indeed, this C# project builds just fine under netstandard1.5 when it's part of another application, but I'm trying to pull it out). Here's my project.json:

```json
{
    "name": "Still Can't Say",
    "version": "1.0.0-*",

    "buildOptions": {
        "warningsAsErrors": true
    },

    "dependencies": {
        "Some old-school .NET 4.5 ReferenceAssemblies": "1.0.0-*"
    },

    "frameworks": {
        "netstandard1.5": {
            "buildOptions": {
                "define": [ "CORECLR" ]
            },
            "imports": [ "net40" ],
            "dependencies": {
                "Microsoft.NETCore": "5.0.1",
                "System.Console": "4.0.0",
                "System.Collections.NonGeneric": "4.0.1",
                "System.Threading.Thread": "4.0.0",
                "Microsoft.Win32.Primitives": "4.0.1",
                "Microsoft.NETCore.Portable.Compatibility": "1.0.1"
            }
        },
        "net451": {
            "frameworkAssemblies": {
                "System.Windows.Forms": {
                    "type": "build"
                }
            }
        }
    }
}
```

My NuGet.config provides the dotnet-core MyGet feed and the NuGet feed.

The `net451` is happy to compile. But here's the error I get when trying to use the `Hashtable` type (and I can't remove, it's part of a public API):

**error CS7069: Reference to type 'Hashtable' claims it is defined in 'mscorlib', but it could not be found**

I *have* `System.Collections.NonGeneric`, and it's not a `using` problem as the type is found, but its forwarded to `mscorlib`, and that (supposedly) doesn't have it.

This particular example uses the RTM escrow bits from (what RC3 turned into), but I've also tried `rc2-24027` (where the project was known to work when part of a larger set of projects), as well as `rc3-24013-00` from the `NonGeneric` [test projects](https://github.com/dotnet/corefx/blob/e88bf5f29be03434bb7b6385c93534deef4a5731/src/System.Collections.NonGeneric/tests/project.json). I've also cleared out my NuGet packages and re-installed `dotnet`.

`dotnet --info` says:

```
.NET Command Line Tools (1.0.0-preview3-003161)

Product Information:
 Version:            1.0.0-preview3-003161
 Commit SHA-1 hash:  63846c5751

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
```

@piotrpMSFT pinging you because you always figure out what I've done wrong :smile:

**Comment by mellinoe** [comment]
> and I can't remove, it's part of a public API

How is this other project compiled? If it's compiled against `[mscorlib]Hashtable`, then I don't think this is going to work. Microsoft.NETCore.Portable.Compatibility has a "ref mscorlib" assembly which can help resolve some of these old references to mscorlib, but `Hashtable` is not one of the types that is forwarded. That would explain the `it could not be found` message. This is most likely because `Hashtable` was not available in the portable subset that the compat package is for.

@weshaggard

**Comment by weshaggard** [comment]
@andschwa why are you doing `"imports": [ "net40" ]` for netstandard1.5? that is going to mix full .NET framework libraries with netstandard ones and is not a valid configuration. I'm not entirely sure if that is what is happening for you but I can definitely imagining that causing issue here.

**Comment by andschwa** [comment]
The reference assembly I'm compiling against is `net4`.

**Comment by andschwa** [comment]
It *should* just be a reference assembly, but for some reason I think I'm seeing it provide a runtime package. This is probably the root of my problem.

**Comment by weshaggard** [comment]
The reason I think it is related to your problem is because the System.Collections.NonGeneric library that is used for netfx does have a type-forward for Hashtable but it should have a type-forward for .NET Core/.NET Standard version so I think that import might be causing the wrong version to be picked up.

**Comment by andschwa** [comment]
Synced offline, conclusion is I need to get the corresponding team to create a new reference assembly that's compatible. Thanks @weshaggard!

**Comment by andschwa** [comment]
Hey by the way, this was for PSReadLine 😄 (I can say that now!)
