### ISSUE TITLE
Open source System.Collections.Generic.dll

### ISSUE THREAD

**Issue by ebickle** [dotnet/corefx#966]
The System.Collection set of projects is missing System.Collections.Generic, which is part of both mscorlib and System.dll in the standard .NET Framework.

Please open source and port that namespace to a proper System.Collections.Generic.dll assembly as part of corefx.

**Comment by shahid-pk** [comment]
generic collections are in System.Collections in corefx but they are not yet on github, but they will soon appear here.

**Comment by davkean** [comment]
We should already have an issue on this, but I can't find it. I'll make this one it. It's on our backlog and will be ported soon.

**Comment by IdahoSixString** [comment]
When will all the backlog items for porting be completed?

**Comment by davkean** [comment]
We don't have a timeline, but we you can see our progress on https://huboard.com/dotnet/corefx.

**Comment by davkean** [comment]
We just published a better view here: https://github.com/dotnet/corefx-progress/blob/master/src-diff/README.md.

**Comment by stephentoub** [comment]
System.Collections source was added in #1532
