### ISSUE TITLE
Trace uses the string DEFAULT_APPNAME unconditionally in logged messages

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#9669]
This looks like a temporary workaround that was never fully resolved, and got lost in an old bug tracker.

https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.Diagnostics.TraceSource/src/System/Diagnostics/TraceInternal.cs#L52

``` CSharp
// This needs to be updated once we have the correct property implemented in the Environment class.
// Bug:895000 is tracking this.
s_appName = "DEFAULT_APPNAME";
```

Desktop uses the code below, which may not be a good idea in today's world where the first command-line arg is often the CLR host.

``` CSharp
appName = Path.GetFileName(Environment.GetCommandLineArgs()[0]);
```

I propose we use `Assembly.GetEntryAssembly()`, but it would require us to bump the support up to `netstandard1.5`:

``` CSharp
s_appName = Assembly.GetEntryAssembly().GetName().Name;
```

**Comment by stephentoub** [comment]
> I propose we use  Assembly.GetEntryAssembly() 

Sounds reasonable.

> but it would require us to bump the support up to  netstandard1.5 

We could play some tricks if we wanted to, e.g. using reflection to get it and invoking it if it can be found, otherwise falling back to something else.

**Comment by mellinoe** [comment]
I am hoping we don't need to use any "tricks", so to speak. We should be able to ship a second binary in the nuget package (under lib/netstandard1.5) which supports the same surface area but takes more/newer dependencies. We can also ship a new version of the netstandard1.3 binary with some better fallback behavior (not sure what that is without `GetEntryAssembly`). I don't think this would be terribly hard to accomplish considering how our build projects are set up.

**Comment by stephentoub** [comment]
> not sure what that is without  GetEntryAssembly 

Given that apps published by CLI rename the host as the app's name, seems reasonable to just use argv[0].
