### ISSUE TITLE
System.IO.Compression should support *tar files

### ISSUE THREAD

**Issue by ericstj** [dotnet/corefx#9673]
Now that we have x-plat implementation it'd be great to be able to work with .tar & .tar.gz.

**Comment by jasonwilliams200OK** [comment]
Also .bz2 if possible (http://www.bzip.org/1.0.3/html/zlib-compat.html). :)

**Comment by ianhays** [comment]
closing as duplicate of https://github.com/dotnet/corefx/issues/3253.
