### ISSUE TITLE
Move Process related classes out of System.Diagnostics

### ISSUE THREAD

**Issue by ebickle** [dotnet/corefx#968]
This is likely a contentious issue and a bit of a non-starter, but I wanted to open it up for discussion now before the first release of corefx.

Going back to the first release of .NET, all of the process-related functionality (e.g. Process, ProcessModule) is located inside of System.Diagnostics while all of the thread-related functionality is located inside of System.Threading.

To this day, it's confusing and unintuitive. The Process management functionality has nothing to do with diagnostics at all - it's core functionality with interacting with the host operating system.

**Comment by davkean** [comment]
Thanks for bug. While we do consider a mistake that Process lives in Diagnostics, it's too late to change it. For APIs that it shares with the other .NET stacks, it remains API compatible (changing namespace is a breaking change), developers can compile against .NET Core and run on other platforms, such as .NET Framework and Mono.
