### ISSUE TITLE
Socket.SendFile leaks FileStream in case of error

### ISSUE THREAD

**Issue by GSPP** [dotnet/corefx#9706]
Here's a sketch of the method:

```c#
public void SendFile(string fileName, byte[] preBuffer, byte[] postBuffer, TransmitFileOptions flags)
{
    ...    FileStream fileStream = null;
    ...        fileStream = new FileStream(fileName, FileMode.Open, FileAccess.Read, FileShare.Read);
    ...    if (fileStream != null)
    {
        ExceptionHelper.UnmanagedPermission.Assert();
    ...
    }
    ...
}
```
1. The `fileStream` can leak if there's an exception. Actually, I can't find the place where the stream is ever closed but this might be an oversight on my part. This is a resource leak and therefore a bug. 
2. `new TransmitFileOverlappedAsyncResult(this)` can leak in case anything throws. This class has a finalizer. Probably a minor issue.
3. Another issue is that if `ReuseSocket` is set but not `Disconnect` we in fact disconnect. Is this really intended? The whole design of the enum stinks as well but we're stuck with that. Also, the enum is not validated and directly passed into unmanaged code. Hope this is alright.

Disclaimer: I have not tested this. This is from code review only.

**Comment by davidsh** [comment]
cc: @CIPop

**Comment by CIPop** [comment]
Thanks @GSPP. I believe you are referring to the .Net _Desktop_ code you've found on referencesource and not the code in CoreFX?
SendFile is not an API available through .Net Core: we recommend using `SendAsync` with `SendPacketsElement(string filepath)` instead.

> The fileStream can leak if there's an exception.

I see how the `fileStream` is not disposed. I wouldn't say it's not leaking: it's going to be GCed at a later time. 
The situation is exceptional given that the app will not be able to communicate. @himadrisarkar: For completeness it would be good to fix.

> new TransmitFileOverlappedAsyncResult(this) can leak in case anything throws

As you point out, the finalizer is there to handle that case. Again, this is not leaking. 

> Another issue is that if ReuseSocket is set but not Disconnect we in fact disconnect. Is this really intended?

These map directly to the Windows OS. According to the [documentation](https://msdn.microsoft.com/en-us/library/system.net.sockets.transmitfileoptions(v=vs.110).aspx):

_ReuseSocket	
The socket handle may be reused when the request completes. This flag is valid only if Disconnect is also specified. When used with Disconnect, these flags return the socket to a disconnected, reusable state after the file has been transmitted._

**Comment by GSPP** [comment]
Yes, this is Desktop code. I forgot to check CoreClr.

**Comment by CIPop** [comment]
Thanks for confirming @GSPP.

@himadrisarkar I've assigned this to you for triage/tracking of the .Net Desktop bug.

**Comment by GSPP** [comment]
I pointed out the finalization issues because generally finalization is avoided. In the FileStream case the file is locked for an unspecified time which clearly must be fixed (as you said). In the other cases it's merely an inefficiency because the object will run through the finalization queue and is guaranteed to reach Gen2. My understanding is that this is unwanted but it's not a correctness issue.

**Comment by karelz** [comment]
@geoffkizer can you please investigate and triage?

**Comment by geoffkizer** [comment]
@GSPP can you point to the specific code you're referring to?

I'm looking at this:https://github.com/dotnet/corefx/blob/684af05e70b345eecd503e23d0d6d4efd67f9130/src/System.Net.Sockets/src/System/Net/Sockets/Socket.Windows.cs#L215
and there's clearly a using() around the FileStream.

Similarly for Unix: https://github.com/dotnet/corefx/blob/684af05e70b345eecd503e23d0d6d4efd67f9130/src/System.Net.Sockets/src/System/Net/Sockets/Socket.Unix.cs#L44

**Comment by stephentoub** [comment]
I believe this was about desktop code:
https://referencesource.microsoft.com/#System/net/System/Net/Sockets/Socket.cs,1435

**Comment by karelz** [comment]
Desktop bugs are not tracked on GitHub - we should close the issue if it is that case.

**Comment by geoffkizer** [comment]
Sorry, missed that above.  Yes, this appears to be a desktop-only issue.

**Comment by karelz** [comment]
Closing per info above.
