### ISSUE TITLE
Investigate high-level CompressionStream with header detection

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#9709]
## Problem

There have been a number of requests coming up lately to add new compression algorithms to System.IO.Compression. This is a great way to expand the usefulness of the library and be more friendly to other platforms that frequently use compression algorithms other than Deflate/GZip/Zip.

However, adding those algorithms will likely introduce lots of new, in-depth API that may add too much complexity to the scenarios where the user just wants to compress/decompress something using the defaults.

## Suggestion

We should consider whether we want to provide a high-level way of compression without the need for fine-grained construction and setup, possibly by adding API that allow easy choosing of a Compression algorithm . A **major** part of this would be to add header detection to the default decompression stream. This way we can add detailed compression algorithms in their individual classes (e.g. LZMAStream, BZ2Stream, GZipStream) while still providing a simple Compression/Decompression vehicle with plenty of Algorithm choices.

## API 1 - CompressionStream type

```
    public enum Compressiontype
    {
        Deflate = 0,
        GZip = 1,
        ZLib = 2,
        LZMA = 3
        ...
    }
    public partial class CompressionStream : System.IO.Stream
    {
        public CompressionStream(System.IO.Stream stream, System.IO.Compression.CompressionMode mode) { } // default Deflate for CompressionMode.Compress. CompressionMode.Decompress attempts to detect type from header and defaults to Deflate if it can not be determined.
        public CompressionStream(System.IO.Stream stream, System.IO.Compression.CompressionMode mode, System.IO.Compression.CompressionType type) { } // no auto-header detection for Decompression.
        public CompressionStream(System.IO.Stream stream, System.IO.Compression.CompressionMode mode, bool leaveOpen) { }
        public CompressionStream(System.IO.Stream stream, System.IO.Compression.CompressionMode mode, System.IO.Compression.CompressionType type, bool leaveOpen) { }
        ...
    }
```

### Examples

```
using (FileStream fs = File.OpenRead("existinggzipfile.gz"))
using (CompressionStream compStream = new CompressionStream(fs, CompressionMode.Decompress))
{
    // compStream defers entirely to GZipStream
}

using (FileStream fs = File.OpenWrite("newgzipfile.gz"))
using (CompressionStream compStream = new CompressionStream(fs, CompressionMode.Compress, CompressionType.GZip))
{
    // compStream defers entirely to GZipStream
}
```

## API 2 - Compression static class

```
    public enum Compressiontype
    {
        Deflate = 0,
        GZip = 1,
        ZLib = 2,
        LZMA = 3
        ...
    }
    public partial static class Compression
    {
        public static Stream CreateStream(System.IO.Stream stream, System.IO.Compression.CompressionMode mode) { } // default Deflate for CompressionMode.Compress. CompressionMode.Decompress attempts to detect type from header and defaults to Deflate if it can not be determined.
        public static Stream CreateStream(System.IO.Stream stream, System.IO.Compression.CompressionMode mode, System.IO.Compression.CompressionType type) { } // no auto-header detection for Decompression.
        public static Stream CreateStream(System.IO.Stream stream, System.IO.Compression.CompressionMode mode, bool leaveOpen) { }
        public static Stream CreateStream(System.IO.Stream stream, System.IO.Compression.CompressionMode mode, System.IO.Compression.CompressionType type, bool leaveOpen) { }
        ...
    }
```

### Examples

```
using (FileStream fs = File.OpenRead("existinggzipfile.gz"))
using (Stream compStream = Compression.CreateStream(fs, CompressionMode.Decompress)) // stream is a GZipStream
{
    ...
}

using (FileStream fs = File.OpenWrite("newgzipfile.gz"))
using (Stream compStream = Compression.CreateStream(fs, CompressionMode.Compress, CompressionType.GZip)) // stream is a GZipStream
{
    ...
}
```

Somewhat related to https://github.com/dotnet/corefx/issues/9237.
Discussion forked from https://github.com/dotnet/corefx/issues/9657.
Issues for adding new compression algorithms:
- ZLib https://github.com/dotnet/corefx/issues/7570
- 7z/LZMA1/LZMA2 https://github.com/dotnet/corefx/issues/9657
- LZ4 https://github.com/dotnet/corefx/issues/9704 
- Bz2 https://github.com/dotnet/corefx/issues/3253

**Comment by ericstj** [comment]
I'm not sure if a derived type is the right pattern here.  Consider a factory instead.

**Comment by ianhays** [comment]
Agreed. Updated OP with static factory class API (though couldn't think of a good name).

Overlaps with #9237.

**Comment by svick** [comment]
Since some of these compression formats are almost always used together with tar and since adding tar is proposed in #3253, would it make sense to also add a high-level `Archive` type (similar to `ZipArchive`), which would be able to handle at least .zip, .tar.gz and .tar.bz2?

**Comment by GSPP** [comment]
I'm duplicating a comment that I made [elsewhere](https://github.com/dotnet/corefx/issues/9657#issuecomment-229042376) because it applies to the API design for this issue:

> I think the enum approach suffers from non-extensibility. Wouldn't it be better to use one derived type for each algorithm? Algorithms have different parameters and sometimes different capabilities. For example, Zip has the capability to add named entries (files). Many compression libraries offer a ZipStream that behaves like a normal stream plus the ability to define files.

>Proposal: Make CompressionStream an abstract base class that anyone including user code can derive from. That way there is a standardized infrastructure for the compression mode and leaving the stream open. Also, maybe we can have standardized compression levels 1-9 that each derived algorithm interprets and uses to set it's settings.

>Also, I do not see in what way a class-based approach (as opposed to an enum-based approach) would be inferior(?). Seems equal or better in every regard (apart from format detection).

>I advise against format detection when decompressing. The format should be statically known and usually is. Some formats are headerless which breaks the scheme.

**Comment by GSPP** [comment]
Also note, that algorithms have their own specific settings. For example, LZMA(2) can make use of up to 15GB of memory. This is mostly independent from the CPU time it spends finding good matches. It's not possible to express both in a generic 1-9 scale. The amount of memory *must* be configurable. This strongly suggests a design in which all algorithms are represented by a specialized API (probably a derived class or one factory static class for each algorithm).

**Comment by ianhays** [comment]
>This strongly suggests a design in which all algorithms are represented by a specialized API (probably a derived class or one factory static class for each algorithm).

Each algorithm will definitely need its own class to allow fine-grained tuning like you mentioned. My tentative plan is to add algorithms in their own classes (ZlibStream, Deflate64Stream, LzmaStream, etc.) with APIs similar to DeflateStream but with added parameters and control over algorithm-specific settings that can't be easily abstracted to any compression stream.

This issue (#9709) will be on the backburner until we get to a point where we have a large number of compression classes.

>I advise against format detection when decompressing. The format should be statically known and usually is. Some formats are headerless which breaks the scheme.

If it's statically known then that's great and we'll assert the header/lack of header of the given stream adheres to the type. But for the parent stream style (e.g. CompressionStream) I think it'd be nice to provide *some* sort of detection for well-known headers. That is of course under the assumption that we decide to go that route.

**Comment by ianhays** [comment]
Closing this until we need it i.e. when we have more compression classes to differentiate between.
