### ISSUE TITLE
System.Runtime.InteropServices.RuntimeInformation.OsDescription Improvements...

### ISSUE THREAD

**Issue by niemyjski** [dotnet/corefx#9729]
The RuntimeInformation could be improved greatly and go back to the previous model that rc2 had for getting os info. I'd love to get a friendly os name and os version.. It's currently not possible (unless you want to build some kind of parser for os description user agents 👎 .

`Darwin 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64`

**Comment by ejsmith** [comment]
Yeah, this sucks. Surely there has to be a way to get a friendly name for the OS and version.

**Comment by Priya91** [comment]
This api implementation was designed keeping in mind that we want to see as much information as possible for debug purposes. Moreover, this is the output from the OS native call, ```uname -srv```. For a more pretty string, the user code has to parse the output of this string, following the syntax specifications of the OS.

**Comment by Priya91** [comment]
@niemyjski You can use the Environment.OSVersion that is now exposed in corefx for an exact Unix version object, #9851
