### ISSUE TITLE
F# with RC2/3 on Mac OS X 10.11 and CentOS 7: downgrade warnings on "dotnet restore", dependency failure during build

### ISSUE THREAD

**Issue by wyoung** [dotnet/corefx#9730]
The current binary releases downloaded from microsoft.com give errors of the following form when trying to `dotnet restore` after generating the default "Hello, World" F# app:

<pre>warn : Detected package downgrade: System.Runtime.InteropServices.PInvoke from 4.0.0-rc2-24027 to 4.0.0-rc2-23911 
warn :  dotnet-compile-fsc (>= 1.0.0-preview2) -> Microsoft.FSharp.Compiler.netcore (>= 1.0.0-alpha-160318) -> System.Runtime.InteropServices (>= 4.1.0-rc2-23911) -> System.Runtime.InteropServices.PInvoke (>= 4.0.0-rc2-24027) 
warn :  dotnet-compile-fsc (>= 1.0.0-preview2) -> Microsoft.FSharp.Compiler.netcore (>= 1.0.0-alpha-160318) -> System.Runtime.InteropServices.PInvoke (>= 4.0.0-rc2-23911)
warn : Detected package downgrade: System.Dynamic.Runtime from 4.0.11 to 4.0.11-rc3-24210-10 
</pre>

That goes on for dozens of lines.

Then on trying to build it:

<pre>The specified framework 'Microsoft.NETCore.App', version '1.0.0-rc3-004459-00' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/local/share/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.0.0
      1.0.0-rc2-3002702
  - Alternatively, install the framework version '1.0.0-rc3-004459-00'.
/usr/local/share/dotnet/dotnet compile-fsc @/Users/tangent/tmp/x/obj/Debug/netcoreapp1.0/dotnet-compile.rsp returned Exit Code 131
</pre>

I assume this is a late-beta thing that will shake out quickly as the non-Windows platforms get 1.0.0 final. If so, please disregard this. Otherwise, I'd be sad to see this in the final 1.0.0 binaries.

I say "RC2/3" because `dotnet --version` says `1.0.0-preview2-003121` on both test platforms, but I see a lot of `rc3` in the messages above. I assume this is related to the core problem; some kind of version mismatch, yes?

**Comment by ericstj** [comment]
@wyoung this is an issue with FSharp, that I believe is being fixed with https://github.com/Microsoft/visualfsharp/pull/1290.

**Comment by enricosada** [comment]
yes already fixed but not yet published.
anyway ref https://github.com/dotnet/netcorecli-fsc/issues/12 for f# and preview2.

thx @ericstj
