### ISSUE TITLE
Assemblies in NETFramework TargetingPack do not compile on non-Windows platforms

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/corefx#9735]
The targeting packs for full desktop .NET on dotnet.myget.org/F/dotnet-core do not currently work when attempting to compile on OSX or Linux.

**Repro**

``` json
{
  "dependencies": {
    "Microsoft.TargetingPack.NETFramework.v4.5.1": {
      "type": "build",
      "version": "1.0.1"
    }
  },
  "frameworks": {
    "net451": {}
  }
}
```

`dotnet build`

> /private/tmp/targeting/error CS1509: The referenced file '/Users/namc/.nuget/packages/Microsoft.TargetingPack.NETFramework.v4.5.1/1.0.1/lib/net451/System.EnterpriseServices.Wrapper.dll' is not an assembly
> /private/tmp/targeting/error CS0009: Metadata file '/Users/namc/.nuget/packages/Microsoft.TargetingPack.NETFramework.v4.5.1/1.0.1/lib/net451/System.EnterpriseServices.Thunk.dll' could not be opened -- PE image doesn't contain managed metadata.

**Comment by mellinoe** [comment]
I'm not sure that package is necessarily intended to be referenced outside of our uses here. We have MSBuild targets that filter the references. It was my understanding that the `dotnet` project system has a different mechanism for referencing framework libraries.

@weshaggard

**Comment by natemcmaster** [comment]
Yes, dotnet-cli [does some magic](https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.Extensions.DependencyModel/Resolution/DotNetReferenceAssembliesPathResolver.cs) to find references assemblies. For x-plat builds, this requires having Mono installed or providing the reference assemblies through [some other method](https://github.com/aspnet/KoreBuild/pull/94). 

Ideally we'd like to just use a targeting pack from nuget instead. We are investigating using these targeting packs for aspnet builds and came across this issue.

**Comment by mellinoe** [comment]
I think it sounds reasonable. @weshaggard It sounds like all we'd need to do would be to trim out non-referencable assemblies from the package.

**Comment by weshaggard** [comment]
As @mellinoe pointed out these packages are currently only for our build consumption and we consume them in a filtered way from our targets. We can consider doing some tweaking like you suggest to enable referencing all of them but I'm not sure that is going to get you all the way you want to be, as these are also in the lib directory instead of the ref because of other nuget issues. 

I know there are plans to provide nuget packages for the targeting packages at some point @cartermp has some issues https://github.com/dotnet/corefx/issues/3934 assigned to him to spec out that experience. 

@cartermp any updates on that front?

**Comment by cartermp** [comment]
I had spec'd this out here prior to a lot of big movements (Xamarin, project.json --> msbuild): https://github.com/dotnet/core/pull/64

I closed the proposal, but intended on opening it back up and revising once we had a stable story in place for things.  Looks like that might be now.  It's going to need a re-think, but the gist of it is:

1. Targeting packs are NuGet packages

    a. They contain metadata containing information about the default set of references and the NuGet folder name packaging purposes
    b. These packages can have additional assemblies references from within the package, thus eliminating the need for `frameworkAssemblies`

2. Each .NET Framework version and PCL profile gets its own package
3. The build system will treat the targeting pack as the directory for looking for assemblies

    a. This used to be a simple convention the CLI would understand

This will probably need a bit of a re-think now that we're going to msbuild and csproj/fsproj/vbproj.

**Comment by mellinoe** [comment]
I think it's fair to say that right now, the "TargetingPack" nuget packages aren't intended to be used outside of our build system. Delivering a separate package for public consumption would probably be a separate effort.

**Comment by karelz** [comment]
Given that these packages are not supposed to be used outside, we should close the issue.

**Comment by Thealexbarney** [comment]
Is there any plan to publish .NET Framework reference assemblies to NuGet so that the .NET Core CLI could be used to target .NET Framework versions without having the relevant targeting pack installed?
