### ISSUE TITLE
mscorlib reference assembly shouldn't need to expose internal types with FriendAccessAllowed Attribute.

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#9756]
per @jkotas:

> The desired state should be:
> - System.Private.CoreLib exposes two kinds of types/methods: types/methods for public consumption, and types/methods for internal consumption by other framework libraries.
> - mscorlib facade has forwarders for the types for public consumption only.

Today framework libraries still reference mscorlib, so our mscorlib reference assembly still needs to add type forwards for internal types to S.P.Corelib. We should figure out a plan to remove this without breaking backward compat with developing a framework library that we need to run in UWP against an older version of coreclr which doesn't contain S.P.CoreLib

Related: #9712

**Comment by mellinoe** [comment]
@joperezr It doesn't look like we have any `FriendAccessAllowed` attributes in mscorlib here. Is that correct?

**Comment by karelz** [comment]
@joperezr did it already happen by a chance?

**Comment by joperezr** [comment]
The thing is that now the libraries in corefx compile against S.P.C.dll so I believe that this is not required anymore. I'll close it for now.
