### ISSUE TITLE
Console.CancelKeyPress not fireing in git bash.

### ISSUE THREAD

**Issue by Mohammed-El-Nabulsi** [dotnet/corefx#9757]
I wanted to shutdown a running console application gracefully on Ctrl+C, so I went on using the `Console.CancelKeyPress` event. For some reason it does not seem to fire on git bash (everything works fine when I use the cmd though.); the following code is used:

````
using System;
using System.Threading.Tasks;

namespace ConsoleApplication {
    public class Program {
        private static bool isRunning = true;

        public static void Main(string[] args)
        {
          Console.CancelKeyPress += (s, e) => {
              Console.WriteLine("Exiting...");

              isRunning = false;

              e.Cancel = true;

              Console.WriteLine("Done...");
          };

          while(isRunning) {
              Task.Delay(100).ContinueWith((t) => {
                  Console.WriteLine("Hello World!");
              }).Wait();
          };
        }
    }
}
````

Reproduction steps: 

```
$ mkdir test
$ cd test
$ dotnet new
$ dotnet restore
$ paste in the code above
$ dotnet run  
```

The WriteLines inside the handler aren't printed and the program quits abruptly on Ctrl+C.

Dotnet version: `1.0.0-preview2-003121`  
OS: `Windows 10 Pro v. 1511, build 10586.420`   
Git version: `2.9.0.windows.1`

**Comment by mellinoe** [comment]
This doesn't repro for me. Can you use the latest tooling preview and see if it helps?

https://www.microsoft.com/net/core#windows

**Comment by Mohammed-El-Nabulsi** [comment]
Thanks for the swift answer. I noticed the version I pointed out above was in fact wrong. I am using `1.0.0-preview2-003121`, which matches the version I just downloaded. I'll edit the issue accordingly. Sorry for the inconvenience.

I've digged some further into this and found out that it works on the `Git/bin/bash.exe` but does not on `Git/git-bash.exe`. Can you reproduce this?

This indicates that it's less of a dotnet and more of a git problem.

I've attached a screenshot that shows this - the right one is git-bash.exe

![image](https://cloud.githubusercontent.com/assets/13213483/16465881/4051d798-3e41-11e6-89e0-7a116276f5ac.png)

**Comment by innix** [comment]
Does it work when you prefix with `winpty`? e.g. `winpty dotnet run`

**Comment by Mohammed-El-Nabulsi** [comment]
Yes, it does work then. Nice!

**Comment by innix** [comment]
It's a known issue with Git Bash for Windows:
https://github.com/git-for-windows/build-extra/blob/43d672f/installer/ReleaseNotes.md#known-issues

**Comment by Mohammed-El-Nabulsi** [comment]
I see.  Thanks for resolving my problem! Well then I guess this issue can be closed.
