### ISSUE TITLE
XPathTests failing in CI system.

### ISSUE THREAD

**Issue by AlexGhiondea** [dotnet/corefx#976]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_prtest/159/

**Comment by krwq** [comment]
It looks the same as the bug I fixed yesterday: https://github.com/dotnet/corefx/issues/949 https://github.com/dotnet/corefx/pull/954. Looking at the date of log that would also fit. Could you attach the error message? It says "not found" when clicking on the test:

**Comment by krwq** [comment]
I don't see any failures since my fix. Closing.
