### ISSUE TITLE
TcpClient.Connected throws NullReferenceException on Windows when there is no Socket

### ISSUE THREAD

**Issue by svick** [dotnet/corefx#9762]
The following code throws `NullReferenceException` on .Net Core on Windows and on .Net Framework:

```c#
var client = new TcpClient();
client.Dispose();
Console.WriteLine(client.Connected);
```

On Unix, it writes `False`, as expected.

This is because `Connected` on Windows [just returns `Connected` of the underlying socket](https://github.com/dotnet/corefx/blob/v1.0.0/src/System.Net.Sockets/src/System/Net/Sockets/TCPClient.Windows.cs#L25), while [on Unix it checks for `null`](https://github.com/dotnet/corefx/blob/v1.0.0/src/System.Net.Sockets/src/System/Net/Sockets/TCPClient.Unix.cs#L164-L172).

This happens when accessing `Connected` while the underlying socket is `null`. That can happen after calling `Dispose()` and also after explicitly assigning `null` to `Client` (the underlying socket).

This also affects `Available` and `ExclusiveAddressUse`.

**Comment by davidsh** [comment]
cc: @CIPop

**Comment by CIPop** [comment]
Thanks for reporting @svick!

**Comment by CIPop** [comment]
Thanks @svick for the fix!

Assigning to @himadrisarkar to track the port and scheduling for .Net Desktop.
