### ISSUE TITLE
Dns.GetHostAddressesAsync Unexpected Result on Ubuntu 14.04

### ISSUE THREAD

**Issue by allevyMS** [dotnet/corefx#9764]
running the following in Ubuntu 14.04:

Dns.GetHostAddressesAsync(Dns.GetHostName()).Result

returns:
Three entries where the AddressFamily is InterNetwork and the ip is 127.0.1.1

using the following package:     "Microsoft.NETCore.App": "1.0.0-rc3-004432-00"

Thanks,

Alon

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by stephentoub** [comment]
GetHostAddressesAsync is essentially just passing along the results it gets from getaddrinfo.  Here's a little C program to demonstrate:
```C
#include <stdio.h>
#include <stdlib.h>
#include <netdb.h>

int main(int argc, char** argv)
{
    if (argc < 2) return 1;
    char* hostname = argv[1];
    printf ("Host: %s\n", hostname);

    struct addrinfo hints = { .ai_family = PF_UNSPEC, .ai_flags = AI_CANONNAME }, *result;
    if (getaddrinfo (hostname, NULL, &hints, &result) != 0) return 1;

    for (; result != NULL; result = result->ai_next)
    {
      void *addr;
      if (result->ai_family == AF_INET)
          addr = &((struct sockaddr_in *) result->ai_addr)->sin_addr;
      else if (result->ai_family == AF_INET6)
          addr = &((struct sockaddr_in6 *) result->ai_addr)->sin6_addr;
      else
          continue;

      char addrstr[100];
      inet_ntop (result->ai_family, addr, addrstr, 100);
      printf ("IPv%d address: %s (socktype: %d)\n", result->ai_family == PF_INET6 ? 6 : 4, addrstr, result->ai_socktype);
    }

    return 0;
}
```
You can try compiling this with ```gcc -o test test.c``` and then running it.  When I do ```./test localhost```, on my Ubuntu 14.04 install I get:
```
Host: localhost
IPv4 address: 127.0.0.1 (socktype: 1)
IPv4 address: 127.0.0.1 (socktype: 2)
IPv4 address: 127.0.0.1 (socktype: 3)
```
so you can see I'm getting three different results, one for SOCK_STREAM (1), SOCK_DGRAM (2), and SOCK_RAW (3).

We could potentially coalesce results when they're the same other than socktype... not sure if that's the right answer or not.
cc: @ericeil
