### ISSUE TITLE
Need a GetResourceSet API on ResourceManager

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/corefx#9766]
As we found in aspnet/Localization#257 currently there's no way to get a complete list of the resources for a specific culture from a [ResourceManager](https://github.com/dotnet/corefx/blob/master/src/System.Resources.ResourceManager/src/System/Resources/ResourceManager.cs). We need to be able to do that for Localization in [ResourceManagerStringLocalizer](https://github.com/aspnet/Localization/blob/dev/src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizer.cs) in order to enable client-side localization.

My suggestion would be to add a function much like what existed before with a signature like:
```
public virtual ResourceSet GetResourceSet(CultureInfo culture, bool createIfNotExists, bool tryParents);
```
which would take care of doing any groveling through embedded resources and satellite assemblies and return us a `ResourceSet` full of all the resources for that culture.

CC @DamianEdwards

**Comment by gkhanna79** [comment]
@ramarag owns this and is the right person to look into this.

**Comment by ramarag** [comment]
https://github.com/dotnet/corefx/issues/11769 will bring back the old resources APIs in netstandard2.0
