### ISSUE TITLE
UrlAttribute.IsValid too naive ?

### ISSUE THREAD

**Issue by Bartmax** [dotnet/corefx#9769]
When looking at https://github.com/dotnet/corefx/blob/6df5eb18807fa42e27a20e41257dcd8cc83d96d9/src/System.Private.Uri/src/System/UriExt.cs

and https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/UrlAttribute.cs

I think the `UrlAttribute` is way too naive to be any useful for url validation.

Is this missing implementation or is the idea to only check if string starts with http(s) or ftp ?

**Comment by jasonwilliams200OK** [comment]
RFC 2396 defines (valid) URL: http://tools.ietf.org/html/rfc2396

Here is one implementation of the said RFC https://commons.apache.org/proper/commons-validator/apidocs/src-html/org/apache/commons/validator/routines/UrlValidator.html (in Java)

**Comment by davidsh** [comment]
cc: @CIPop

**Comment by lajones** [comment]
@Eilon would you like to respond to this?

**Comment by Eilon** [comment]
This is by design as far as the validation attribute is concerned. The goal is not to use a huge expensive complicated unreadable regex to ensure that a human exactly followed an RFC to the letter when typing in a URL. Rather, the goal is to validate that the human did a reasonable job typing something that at least *looks like* a URL.

Ultimately the "killer feature" that most people seem to want is to validate that a URL *works*, and of course this attribute will never do that. So we decided to draw the line at "here's a super easy, quick, and reliable check that will validate that 99.99% scenario."

**Comment by Bartmax** [comment]
>  Rather, the goal is to validate that the human did a reasonable job typing something that at least looks like a URL.

i don't agree, typing http as a start of the string is not a reasonable job in my opinion.

>super easy, quick, and reliable check that will validate that 99.99% scenario."

@Eilon do you are aware that this only validates if the string starts with http, https or ftp? This won't pick nearly the 1% of the scenarios.

I don't care about a strict RFC to the letter, but this accomplishes nothing. From my point of view, this is more like not implemented and it's better to have it removed than to have it like it is now which is misleading.

This is just my point of view. Thanks for answering.

**Comment by lajones** [comment]
Note: just to be precise, the attribute checks that the text starts with `http://` or `https://` or `ftp://`.

**Comment by Bartmax** [comment]
yeah, that what should said the summary documentation at least.

        // Summary:
        //     Validates the format of the specified URL.

**Comment by jasonwilliams200OK** [comment]
> I don't care about a strict RFC 

There is only one way to "validate" a URL by definition; following the rules set by RFC that defines it .. of course IMHO.

**Comment by Eilon** [comment]
@Bartmax I think the question is what could we do that is *more* than the current check, but *less* than the RFC? And then for whatever that is, how straightforward is it to implement and to describe to someone using this feature?

**Comment by Bartmax** [comment]
for a start, validating dots `.` always has a next char that is a number/letter and it's not the first char after `://`

or you can use `Uri.TryCreate` ? 

I cannot be sure because I don't know based in which data a proper validator would be "huge expensive complicated unreadable regex" and why should we do really care.

Since I don't agree/understand any of those (that's why I closed the issue), can't help, I'm not aligned with your design decision at all.

**Comment by Eilon** [comment]
@Bartmax I think my point is that even though we could certainly add logic to check for:

> validating dots `.` always has a next char that is a number/letter and it's not the first char after `://`

That that wouldn't help in any real-world scenario.

That would at most prevent someone from typing in `http://foo.` and `ftp://.`, neither of which is likely to be "user error." User error is more likely something like this:

* `htttp://example.com/`
* `example.com/`
* `http:///example.com/`

And other *common* typos that happen when someone is typing (or sometimes copy/pasting) something.

So while I'm not trying to suggest that one way is right and another way is wrong, I'm rather saying that we felt that the cost/benefit had the best overall balance with the simple `string.StartsWith()` logic that we ended up with. It's trivial to explain, catches what we believe are the most common errors, and is very unlikely to have any bugs in it.

**Comment by Bartmax** [comment]
With the dot example, I was thinking of this common (in my few small samples dataset) user error `www.example..com` but again, this dataset is very small to be useful for any real source of trust.

My point is: From a framework perspective, if I ask an email address, it's because I would normally want to send them an email, so if I use the framework MailAddress, then it will throw if the input is not valid.
Same for Uri, I ask the user for an url, to then create an uri for consumption. Those two things (validation and consuming) being different renders (in my opinion) the validation useless.

**Comment by Eilon** [comment]
@Bartmax you're right, those scenarios become a bit more challenging. If those are the requirements of the application then I recommend writing a custom validator.

BTW see also related discussion about email validation: https://github.com/dotnet/corefx/issues/4923

**Comment by Bartmax** [comment]
@Eilon That's what I'm doing, using custom validators (which I need to write client and server side validation).

I think ideally those common concerns baked in the framework and used for input validation is great! at least that makes a lot of sense to me, specially when that code is already in the framework. 

Take it as an enhancement suggestion.

For the current status of the validators, my feedback is: for me (aka my use cases) both are useless and misleading.
