### ISSUE TITLE
System.Data.SqlClient.SqlException: A connection was successfully established with the server, but then an error occurred during the login process.

### ISSUE THREAD

**Issue by scott-martin** [dotnet/corefx#9795]
`System.Data.SqlClient.SqlException: A connection was successfully established with the server, but then an error occurred during the login process. (provider: TCP Provider, error: 0 - Unable to write data to the transport connection: Unknown error 10054.)
`

I'm getting this error when trying to run our .net core dockerized app against our production sql server. 

`select @@VERSION`:
`Microsoft SQL Server 2008 R2 (SP3) - 10.50.6000.34 (X64)   Aug 19 2014 12:21:34   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (Hypervisor)`

Here is the connection string we are using:

```
Server=172.x.x.x;Database=xxx;User Id=xxx;Password=abcd;
```

I saw one issue that seemed similar that referred to some TLS settings, but those all seem good for us. Any help is appreciated.

**Comment by saurabh500** [comment]
@scott-martin Is this happening on Linux ?

**Comment by saurabh500** [comment]
@scott-martin Any updates on this?

**Comment by scott-martin** [comment]
It was happening on linux, but we were able to fix the issue. It's been so long I don't remember exactly what the problem ended up being. I'll go ahead and close the issue.

**Comment by saurabh500** [comment]
Thanks @scott-martin 
In case you recall what was done to fix this issue, please do update this thread. It will be very helpful.
