### ISSUE TITLE
CallingConvention gap in ILGenerator.EmitCalli

### ISSUE THREAD

**Issue by mellinoe** [dotnet/corefx#9800]
Based on [this stackoverflow submission](http://stackoverflow.com/questions/38129594/emitcalli-net-core-alternative/38134706#38134706).

It seems like there is a bit of a feature gap in the current interface for `ILGenerator`. .NET Core has a `EmitCalli` method, but the calling conventions it supports do not line up exactly with the ones exposed from the .NET Framework: https://msdn.microsoft.com/en-us/library/d81ee808(v=vs.110).aspx

We should understand if this is a meaningful gap, or if the use cases for the .NET Framework version can still be covered by the new version.

We may already be considering adding this functionality back as part of our bigger API compat push.

cc: @AtsushiKan

**Comment by AtsushiKan** [comment]
For future clarification:

    ILGenerator on Core is missing the overload of EmitCalli that takes a System.Runtime.InteropServices.CallingConvention enum (the unmanaged calling convention enum that includes CDecl.)

**Comment by karelz** [comment]
@AtsushiKan @DnlHarvey please update top post with proposal if it is ready.

**Comment by AtsushiKan** [comment]
Does not need an api review as this proposal is simply about restoring an overload that already exists on the full framework:

public virtual void EmitCalli(
	OpCode opcode,
	CallingConvention unmanagedCallConv,
	Type returnType,
	Type[] parameterTypes
)

**Comment by karelz** [comment]
@AtsushiKan is it just matter of exposing existing functionality, or what is involved in the work? (the "next step & complexity" comment ;-))

**Comment by karelz** [comment]
Also, unassigning you as you don't plan to work on it ...

**Comment by AtsushiKan** [comment]
The overload and its underlying support was physically removed from CoreClr so it'll have to be exhumed from the desktop source. Estimate: light to medium complexity.

**Comment by Cronan** [comment]
I'm interested in having a go at this, it's a major blocking issue for
https://github.com/pythonnet/pythonnet/issues/96

Any advice other than "read the contrib dox"?

**Comment by jkotas** [comment]
Needs to be exposed from the contracts: https://github.com/dotnet/corefx/tree/master/src/System.Reflection.Emit.ILGeneration

**Comment by Cronan** [comment]
I noticed this - I can do it as well, if you like, I’ve got the code open as it is

**Comment by jkotas** [comment]
@Cronan Yes, that would be great. Thanks!

**Comment by Cronan** [comment]
I'm slightly confused about where exactly the change should be made.
The screen grab below is from my corefx checkout of master

![emicalli_grab](https://user-images.githubusercontent.com/777435/32882165-5f1e742c-caab-11e7-8acb-d99ba1a37aae.png)

**Comment by jkotas** [comment]
1. Wait for https://github.com/dotnet/corefx/pull/25282 to get merged. This PR will propagate your change to CoreFX repo. (Alternatively, if you do not want to wait - you can use CoreCLROverridePath option for build.cmd to point it to your private CoreCLR build https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md.)
2. Add the method to https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Emit.ILGeneration/ref/System.Reflection.Emit.ILGeneration.cs
3. Find a some good spot to add a test for the new API under https://github.com/dotnet/corefx/tree/master/src/System.Reflection.Emit.ILGeneration/tests/ILGenerator . 

Also, I have noticed that the fix in CoreCLR is incomplete - the method needs to be overriden in System\Reflection\Emit\DynamicILGenerator.cs with specialized implementation for dynamic methods. Could you please fix that one too (it is probably best to do it before above)?

**Comment by Cronan** [comment]
Accepted.

**Comment by Cronan** [comment]
I’m AFK until Monday, hope that’s not a problem

**Comment by jkotas** [comment]
No problem

**Comment by karelz** [comment]
@Cronan GH shows your invite as "not accepted". Can you please double check?

**Comment by Cronan** [comment]
Sorry, I didn’t have 2-factor enabled, and the mobile GUI wasn’t very clear. Should be accepted now.
