### ISSUE TITLE
StringComparison.InvariantCulture/InvariantCultureIgnoreCase are missing from System.Runtime Reference Assembly

### ISSUE THREAD

**Issue by xyziemba** [dotnet/corefx#9801]
InvariantCulture and InvairantCultureIgnoreCase aren't present on System.StringComparison, but appear to be implemented and used in tests. I would expect them to be present, but perhaps this is an intentional omission for some reason I don't understand?

StringComparison def: https://github.com/dotnet/corefx/blob/72f546c30e61b485546d7c5c0397b8ccc406efa4/src/System.Runtime/ref/System.Runtime.cs#L1626

Code using InvariantCulture/InvariantCultureIgnoreCase by casting an int:
https://github.com/dotnet/corefx/blob/72f546c30e61b485546d7c5c0397b8ccc406efa4/src/System.Runtime/tests/System/StringTests.cs#L433

**Comment by danmosemsft** [comment]
These were not included in Core because of the following reason

> It is almost always incorrect to using InvariantCulture for string equality, see http://msdn.microsoft.com/en-us/library/dd465121(v=vs.110).aspx. The most common replacement is StringComparison.OrdinalIgnoreCase, otherwise, if you need InvariantCulture, use CultureInfo.InvariantCulture.ComparerInfo.GetStringComparer(CompareOptions).

However, we will bring these back for compatibility with existing code.

**Comment by hann013** [comment]
Completed - #10019 merged.
