### ISSUE TITLE
#System.Data.SqlClient UWP reference, FileNotFound Exception

### ISSUE THREAD

**Issue by pozzzima123** [dotnet/corefx#9802]
Hey i want to share with you my experience about system.data.sqlclient.
I created new UWP project and from myget i added reference to package.
Then i got exception while i was trying to connect to my database.
In .Net Core console project i don't have this issuse.

Debug Log:

```
Exception thrown: 'System.IO.FileNotFoundException' in System.Data.SqlClient.dll
Exception thrown: 'System.IO.FileNotFoundException' in System.Data.SqlClient.dll
Exception thrown: 'System.IO.FileNotFoundException' in System.Data.SqlClient.dll
Exception thrown: 'System.IO.FileNotFoundException' in App16.exe
```

Exception:
`"Could not load file or assembly 'System.Threading.Thread, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Nie można odnaleźć określonego pliku."`

My project.json:
```
{
  "dependencies": {
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.1.0",
    "System.Data.SqlClient": "4.1.1-beta-24230-04"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```

My code in ctr:
```
SqlConnection conn = new SqlConnection("Data source=exampleSource\\sqlexpress;user id=exampleUser;pwd=ExamplePwd;database=ExampleDB");
            conn.Open();
```

What package i must install to solve this problem? I tried to install Systema.Threading.Thread from MyGet but it isn't compatible with my runtimes.

**Comment by saurabh500** [comment]
@pozzzima123  `System.Data.SqlClient` is not supported on UWP
