### ISSUE TITLE
Restore Reflection API (.NET Native)

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#9805]

**Comment by danmosemsft** [comment]
For UWP, this is distinct work to CoreCLR (where the work is mostly just exposing already existing implementation and adding tests). Tracking the latter separately.

**Comment by danmosemsft** [comment]
Removing NS2.0 label as we're not currently targeting NS2.0 for UWP

**Comment by karelz** [comment]
This is just tracking issue for NS 2.0 in UWP which is already tracked.
