### ISSUE TITLE
Assigning VectorX right to VectorX left

### ISSUE THREAD

**Issue by lampuiho** [dotnet/corefx#9807]
CopyTo allows copying of value to arrays but not another Vector of the same length.

**Comment by benaadams** [comment]
Vector is a value type so you just need to use assignment to do a copy.

e.g. `var vectorB = vectorA;`

**Comment by mellinoe** [comment]
Yep, @benaadams pretty much covered it. Anything else for clarification, @lampuiho ?

**Comment by lampuiho** [comment]
No, that's all. Thank you. I do have a question about Vector<T> though. How do I assign values directly to it? I am actually trying to do matrix multiplication here. Currently I am using a locally allocated "fixed size" array with unrolled dot product to do the multiplication with a vector. But the extra code to initialise the array and wrapping it into a vector is quite costly (and I have to wrap it each time the multiplication is done with values allocated to the array). Is there any faster way to do it without initialising the array at all and directly perform the multiplication on the locally initialised vector.

**Comment by mellinoe** [comment]
`Vector<T>` is designed to be immutable once created, so the individual elements of a vector cannot be modified after it is constructed. There's a few main ways to initialize a `Vector<T>`:

* Store all of your data upfront in a large array, create vectors from it, using different contiguous parts of the array
* Store your data in a small, local array, perhaps re-using the array for several constructions, and modifying the values in-between. This sounds like what you're doing already.
* Store your data on the stack (using `float* ptr = stackalloc float[Vector<float>.Count]`) and then using `Unsafe.Read<Vector<float>>(ptr)`. You can avoid the temporary allocation here, but you have to be careful about the unsafe code and boundary checks.

> Vector4 only supports float*

Is this related to the above question? I'm not sure what you're referring to.

**Comment by karelz** [comment]
Original question seems to be answered. Feel free to open a new issue if needed ...
