### ISSUE TITLE
Exception occur when Registraing a new User in .NetCoreApp

### ISSUE THREAD

**Issue by HassanSiddique** [dotnet/corefx#9809]
### The issue

Exception occur while Registring a new user in .NetCoreApp v1.0.0-rc2-3002702
### STACK

**OverflowException: Arithmetic operation resulted in an overflow.**

System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
AggregateException: One or more errors occurred. (Arithmetic operation resulted in an overflow.)

System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
AggregateException: One or more errors occurred. (Arithmetic operation resulted in an overflow.)

```
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Identity.UserValidator`1.<ValidateUserName>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Identity.UserValidator`1.<ValidateAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Identity.UserManager`1.<ValidateUserInternal>d__157.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Identity.UserManager`1.<CreateAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Identity.UserManager`1.<CreateAsync>d__73.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
SoundBoard.Controllers.AccountController.<Register>d__9.MoveNext() in AccountController.cs
                    var result = await _userManager.CreateAsync(user, model.Password);
--- End of stack trace from previous location where exception was thrown ---
```

```


EF Core version: EF 7 / EF Core
Operating system: Windows 8.1
Visual Studio version: VS 2015 
```

**Comment by Clockwork-Muse** [comment]
...you got lines numbers and the rest of the trace?

**Comment by HassanSiddique** [comment]
1. `
2. OverflowException: Arithmetic operation resulted in an overflow.
3. 
4.     System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
5.     System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
6.     System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
7.     System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
8.     System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
9.     System.Data.SqlClient.SqlConnection.Open()
10.     Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open()
11.     Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.Exists(Boolean retryOnNotExists)
12.     Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
13. 
14. 
15. Show raw exception details
16. AggregateException: One or more errors occurred. (Arithmetic operation resulted in an overflow.)
17. 
18.     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
19.     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
20.     Microsoft.AspNetCore.Identity.UserValidator`1.<ValidateUserName>d__6.MoveNext()
21.     --- End of stack trace from previous location where exception was thrown ---
22.     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
23.     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
24.     Microsoft.AspNetCore.Identity.UserValidator`1.<ValidateAsync>d__5.MoveNext()
25.     --- End of stack trace from previous location where exception was thrown ---
26.     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
27.     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
28.     Microsoft.AspNetCore.Identity.UserManager`1.<ValidateUserInternal>d__157.MoveNext()
29.     --- End of stack trace from previous location where exception was thrown ---
30.     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
31.     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
32.     Microsoft.AspNetCore.Identity.UserManager`1.<CreateAsync>d__68.MoveNext()
33.     --- End of stack trace from previous location where exception was thrown ---
34.     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
35.     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
36.     Microsoft.AspNetCore.Identity.UserManager`1.<CreateAsync>d__73.MoveNext()
37.     --- End of stack trace from previous location where exception was thrown ---
38.     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
39.     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
40.     System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
41.     SoundBoard.Controllers.AccountController.<Register>d__9.MoveNext() in AccountController.cs
42.                         var result = await _userManager.CreateAsync(user, model.Password);
43.     --- End of stack trace from previous location where exception was thrown ---
44.     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
45.     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
46.     Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.<CastToObject>d__24`1.MoveNext()
47.     --- End of stack trace from previous location where exception was thrown ---
48.     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
49.     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
50.     Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionAsync>d__6.MoveNext()
51.     --- End of stack trace from previous location where exception was thrown ---
52.     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
53.     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
54.     Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeActionFilterAsync>d__41.MoveNext()
55.     --- End of stack trace from previous location where exception was thrown ---
56.     Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeAsync>d__32.MoveNext()
57.     --- End of stack trace from previous location where exception was thrown ---
58.     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
59.     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
60.     Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler.<InvokeActionAsync>d__8.MoveNext()
61.     --- End of stack trace from previous location where exception was thrown ---
62.     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
63.     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
64.     Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
65.     --- End of stack trace from previous location where exception was thrown ---
66.     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
67.     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
68.     Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
69.     --- End of stack trace from previous location where exception was thrown ---
70.     Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
71.     --- End of stack trace from previous location where exception was thrown ---
72.     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
73.     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
74.     Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
75.     --- End of stack trace from previous location where exception was thrown ---
76.     Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
77.     --- End of stack trace from previous location where exception was thrown ---
78.     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
79.     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
80.     Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
81.     --- End of stack trace from previous location where exception was thrown ---
82.     Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
83.     --- End of stack trace from previous location where exception was thrown ---
84.     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
85.     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
86.     Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
87.     --- End of stack trace from previous location where exception was thrown ---
88.     Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
89.     --- End of stack trace from previous location where exception was thrown ---
90.     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
91.     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
92.     Microsoft.VisualStudio.Web.BrowserLink.Runtime.BrowserLinkMiddleware.<ExecuteWithFilter>d__5.MoveNext()
93.     --- End of stack trace from previous location where exception was thrown ---
94.     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
95.     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
96.     Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__5.MoveNext()
97.     --- End of stack trace from previous location where exception was thrown ---
98.     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
99.     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
100.     Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
101.     --- End of stack trace from previous location where exception was thrown ---
102.     Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
103.     --- End of stack trace from previous location where exception was thrown ---
104.     System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
105.     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
106.     Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
107. 
108. 

@Clockwork-Muse 

`

**Comment by Clockwork-Muse** [comment]
When I asked for line numbers, I meant from source code, but it's understandable if you don't have pdbs on a server.

I'm not [seeing anything immediately interesting].

One level up (in the other [TryGetConnection](https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionPool.cs#L696)) there's this:

 > `waitForMultipleObjectsTimeout = (uint)CreationTimeout;`

could we get your connections string, just to rule this out (the username, password, and possibly server name anonymized, of course).

A better possibility is in [WaitForPendingOpen](https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionPool.cs#L642)

> `delay = (uint)Math.Max(ADP.TimerRemainingMilliseconds(next.DueTime), 0);`

...since the return type is a long (would be thrown as a ['cloned' exception](https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionPool.cs#L776), but haven't investigated enough).  This would imply that the retry timer was set to go off in ~25 days, though, or possibly the value is getting set some other way.  The system clock didn't change around the time this happened, did it?

**Comment by saurabh500** [comment]
@HassanSiddique Is it possible to provide a standalone repro of this issue? What is the use case that is causing this error?

**Comment by HassanSiddique** [comment]
@saurabh500  Here is a standalone repro of this issue
[Repor Link](https://github.com/HassanSiddique/SoundBoard)

I just Want to register a new user in this app but this error occur..

**Comment by saurabh500** [comment]
@HassanSiddique Thanks. Is this any OS specific?

**Comment by saurabh500** [comment]
@HassanSiddique The `project.json` is referencing the RC2 bits. 
Can you update the sample to use .Net Core 1.0 and try the application again?

**Comment by HassanSiddique** [comment]
@saurabh500  It as on 
OS --Windows 8.1 Enterprise
VS -- Visual Studio 2015 update 3

Here is a Link of update .Net Core 1.0 RTM release
[Repor Link](https://github.com/HassanSiddique/SoundBoardRTM)

Unfortunately Same Error Occurred  Again

**Comment by saurabh500** [comment]
@HassanSiddique Can you walk me through the exact steps I need to repro this? 
I restored the packages for .Net Core using `dotnet restore` in `SoundBoardRTM\src\RTM` 
Then I applied the EF migrations using `dotnet ef database update`
I started the app using `dotnet run` 

In the browser I navigated to `http://localhost:5000` and clicked on the ***Register*** link. 
I could add a user with email Id and valid password. 

I have tried this on Windows Server 2012 so far. I will setup a Win 8.1 VM to test this out. If my steps of repro are different from the ones you are using, let me know.

**Comment by saurabh500** [comment]
I tried running the App on Windows 8.1 without Visual Studio, using .Net CLI and all worked well.

**Comment by HassanSiddique** [comment]
@saurabh500  Yes, you perform exact steps, I also Perform these same steps on .Net CLI without Visual Studio but When I perform `dotnet ef database update`  Same error show on cmd 

**Arithmetic operation resulted in an overflow.**

I think its machine specific error due to OS ...

**Comment by saurabh500** [comment]
@HassanSiddique Can you write a sample App which connects to a Sql Database using .Net Core and let us know if that succeeds. That would help us further isolate the problem. 

Right now I am not sure about what is happening. What is the Sql Server version that you are using? 
You can use `SELECT @@VERSION; ` query to get the version either from Visual Studio or SSMS after connecting to the database.

**Comment by saurabh500** [comment]
@HassanSiddique Is this fixed for you?

**Comment by karelz** [comment]
Looks like we don't have enough data to move forward. Closing for now.
Please reopen when more data is available.
