### ISSUE TITLE
Project with .NET Standard won't compile on Xamarin.iOS - missing type in facade

### ISSUE THREAD

**Issue by onovotny** [dotnet/corefx#9817]
When trying to compile the ZeroconfTest.Xam.iOS test project from here:
https://github.com/onovotny/Zeroconf/tree/netstandard

I get a compile time error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to resolve "System.Runtime.CompilerServices.ConditionalWeakTable`2" reference from "System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"	ZeroconfTest.Xam.iOS	C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	681	
```
Digging into it, the facades that Xamarin ships do not have a type forwarder for ```System.Runtime.CompilerServices.ConditionalWeakTable`2```.

I suspect the fix has to come from Xamarin, but it's these packages that's causing the compiler error.

/cc @mhutch @ericstj

**Comment by ericstj** [comment]
I believe Xamarin has fixed this in the latest beta of their SDK.  Can you give it a try.

https://releases.xamarin.com/beta-release-cycle-7-service-release-1-updated/

**Comment by onovotny** [comment]
Confirmed fixed for me using the beta SDK on VS and the Mac.
