### ISSUE TITLE
Running tests for a single project needs /t:Test

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/corefx#982]
The wiki shows for [running tests on the command line](https://github.com/dotnet/corefx/wiki/Developer-Guide#running-tests-on-the-command-line):
> You can also run the test for an individual project by building just one test project, e.g.:
> cd src\System.Collections.Immutable\tests
> msbuild

... this doesn't work (it only builds the project), I need to append `/t:Test` for the tests to run.

The guidance is also misleading for projects that have nested folders under \tests, like [System.Diagnostics.Process](https://github.com/dotnet/corefx/tree/master/src/System.Diagnostics.Process/tests) cause running msbuild in the tests dir won't work.

**Comment by weshaggard** [comment]
Thanks for pointing out the out dated instructions. I updated the wiki for with the following:

>cd src\System.Collections.Immutable\tests
msbuild /t:BuildAndTest (or /t:Test to just re-run the tests)

>In some test directories there may be multiple test projects or directories so you may need to specify the specific test project to get it to build and run the tests.

Does that cover what you are after @akoeplinger?

**Comment by akoeplinger** [comment]
Sounds good, thanks!
