### ISSUE TITLE
Investigate using buffer pooling for StringContent

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#9833]
Currently `StringContent` calls `Encoding.GetBytes` to get the underlying bytes of the string, so it can pass it in to the base constructor: https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/StringContent.cs#L51 This method always allocates a new byte array.

Since `StringContent` is an `IDisposable`, we should investigate renting a buffer from `ArrayPool<byte>.Shared` when initializing the content, and returning it when we dispose. I've made a prototype here: https://github.com/anonpenguin/PooledStringContent/blob/master/src/Pooling.Net.Http/PooledStringContent.cs

(Note however, we may want to come up with a scheme for existing code that assumes `StringContent`'s `Dispose` doesn't do any important work and neglects to dispose it, e.g.

``` cs
var content = new StringContent("..."); // no using
return await _httpClient.PutAsync(_uri, content).ConfigureAwait(false);
```

In those cases we may want to stop after renting a certain amount of ArrayPools without disposing, and fallback to allocating like we originally did.)

cc @benaadams @davidsh

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by karelz** [comment]
Next step: Investigate @jamesqo's prototype, carefully measure impact and propose solution with measured data
Complexity: Medium-Difficult

**Comment by jamesqo** [comment]
@karelz I don't think this is worth it.

**Comment by karelz** [comment]
OK, thanks for the proposal and for following up!
