### ISSUE TITLE
Can't use Path.GetFullPath in netstandard1.2

### ISSUE THREAD

**Issue by sebok** [dotnet/corefx#9839]
Hi,

_Same issue/question as https://github.com/aspnet/Home/issues/1551 by @Sebosek_

How to get the full path of a given relative path in _netstandard1.2_? `Path.GetFullPath` seems to be available only for _netstandard1.3_ and above. Out of curiosity, why is that?

Thanks

**Comment by ianhays** [comment]
According to the [netstandard1.3 vs netstandard1.2 diff](https://github.com/dotnet/standard/blob/master/docs/versions/netstandard1.3_diff.md), Path.GetFullPath isn't available on netstandards before 1.3. 

I'm not sure why that is the case, as it was available on the full framework .NET 1.1. Other Path APIs like [GetFileName](https://github.com/dotnet/standard/blob/4419038e6c8eaed28609d3103b814b0fe6d1ef60/docs/versions/netstandard1.2_ref.md) from .NET 1.1 are available on netstandard1.2, so GetFullPath ostensibly should be as well. Maybe it isn't supported as a part of another platform that implements netstandard<1.3? I don't know which one that would be though if not desktop.

@terrajobst @weshaggard

**Comment by JeremyKuhne** [comment]
It wasn't available on Windows 8/8.1 Universal.

**Comment by ianhays** [comment]
Ah, there ya go. Thanks @JeremyKuhne.
