### ISSUE TITLE
MoveNext and Current for Stack/Queue.Enumerator aren't being inlined

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#9843]
Currently the `MoveNext`/`get_Current` methods for the `Stack/Queue.Enumerator` structs aren't being inlined, which means two method calls for every iteration of a foreach. We should look at making their method sizes smaller (e.g. moving [the exception throwing code](https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/Queue.cs#L419-L422) into a new method and marking with `NoInlining`) to facilitate inlining of the normal code path by the JIT.

**Comment by omariom** [comment]
`List<T>.Enumerator::MoveNext` is not inlined as well. And it is iterated more often than stacks/queues. Would be interesting to see how  forcing inline would change iterating call sites and speed.
