### ISSUE TITLE
[ARM/Linux] Workaround for running unit-test on Linux ARM32

### ISSUE THREAD

**Issue by lemmaa** [dotnet/corefx#9865]
In default, runtimes environments for CoreFX unit-test uses `*.ni.dll`s (mscorlib.ni.dll, System.Private.CoreLib.ni.dll) which extracted from NuGet packages. It's good for performance, but as of now, we don't have proper packages for Linux/ARM32. 

I want to work around this situation by using `*.dll`s instead of `*.ni.dll`s, with `--ignore-native-dlls` option, in spite of performance degradation in test. #9862 is patch for this.

In addition, to improve the readability of test log, add `--sequential` option to run tests one by one. #9863 is patch for this.

**Comment by lemmaa** [comment]
I do alternative approach followed by @jkotas's comment. 

Now 'run-test.sh' checks the validity of using `*ni.dll`s while preparing a test directory and remove mismatching dlls and patch the `RunTests.sh` script to prevent unintended overlaying of dlls from NuGet package.  Updated PR #9862 .

**Comment by jkotas** [comment]
The modification of the auto-generated script on the fly is not pretty. It would be better to generate the script in the right form in the first place. The script generator is in https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets.

I have found that the script generator has a property to skip copying of the native images already: https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets#L194. It seems to be doing exactly what you are looking: just pass  `/p:TestWithoutNativeImages=true` on the msbuild command line. Could you please give it a try?

**Comment by lemmaa** [comment]
@jkotas Thank you, it works well. I can get what I want just passing `/p:TestWithoutNativeImages=true` on the `./build.sh` command line as following. 
```
sjlee@js1-desktop:~/git/corefx$ ./build.sh clean verbose /p:TestWithoutNativeImages=true
```

**Comment by lemmaa** [comment]
@jkotas Thank you, it works well. I can get what I want just passing `/p:TestWithoutNativeImages=true` on the `./build.sh` command line as following. 
```
sjlee@js1-desktop:~/git/corefx$ ./build.sh clean verbose /p:TestWithoutNativeImages=true
```
