### ISSUE TITLE
why would XmlTextWriter be in corefx internal and in .net framework public?

### ISSUE THREAD

**Issue by xrkolovos** [dotnet/corefx#9868]
[core fx implementation](https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/Common/src/System/Xml/XmlTextWriter.cs)
[dotnet Framework 4.6.1 implementation](http://referencesource.microsoft.com/#System.Xml/System/Xml/Core/XmlTextWriter.cs,deba79d6386a7da8)

This project inherits from this class https://github.com/EricWhiteDev/Open-XML-SDK and is a problem porting it to dotnet core.

**Comment by danmosemsft** [comment]
We are adding the surface area of the Desktop version of System.Xml.dll. I believe issue #9635 is the closest tracking issue

**Comment by matt-richardson** [comment]
Please re-open. Issue #9635 has been closed and doesn't resolve this issue.

**Comment by xrkolovos** [comment]
So, Should this be open?

**Comment by matt-richardson** [comment]
@xrkolovos: I've logged another issue https://github.com/dotnet/corefx/issues/11196 which is still open and they've said it should happen with `1.2.0`.
