### ISSUE TITLE
Consistency of partial class filenames

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#9875]
There are multiple different axes along which we customize the implementation via partial classes. From https://github.com/dotnet/corefx/pull/9851/files/282ad11461c480a282a529c38d8fc353bc03663b#r69807075:

1. Classic win32 vs. UWP apps (vs. non-Windows OSes). The two Windows appmodels are very much like different OSes because of there are different APIs available and things have to be generally done differently in number of places. I believe that the most common pattern has been to use `.Win32.cs` vs. `.WinRT.cs` to provide different implementations. `System.IO.FileSystem` or  `System.Console` are good examples.

2. JIT vs. full AOT. I do not actually see any good examples. `System.Linq.Expressions` or data contract serialization where this difference is most prelevant are configured via ifdefs, not via alternative file includes.

3. Different surface of System.Private.CoreLib between CoreCLR and CoreRT/.NET Native. The common pattern for this is `.CoreCLR.cs` vs. `.netcore50.cs` or `.netcore50aot.cs`. Hopefully, most of these will go away over time as we work on filling in the missing APIs and converging the implementations.

**Comment by jkotas** [comment]
Proposed cleanup to make this consistent and more intuitive:

- [ ] `.WinRT.cs` for UWP Apps-specific implementation is confusing , e.g. (`ConsolePal.WinRT.cs`)[https://github.com/dotnet/corefx/blob/master/src/System.Console/src/System/ConsolePal.WinRT.cs] has no WinRT whatsoever. We should rename it to `.UWPApp.cs`.

- [ ] Very few people understand what netcore50 means. We should rename `.netcore50.cs` and `.netcore50aot.cs` to `.CoreRT.cs` instead.

- [ ] `.NetNative.cs` in ` System.Net.NetworkInformation` should be renamed to `.UWPApp.cs`.

- [ ] ` SafeProvOrNCryptKeyHandleUwp.cs` should be renamed to `SafeProvOrNCryptKeyHandle.UWPApp.cs`

**Comment by jkotas** [comment]
cc @stephentoub

**Comment by mellinoe** [comment]
I agree in general with the proposed guidelines. Regarding `netcore50`, `netcore50aot`, etc. We wanted to come up with a naming convention that roughly corresponded to the NuGet framework that the code would eventually end up in. So some things get mixed up in that bucket. I.e. things that go into the `netcore50` group might be due to WinRT, or they might be due to CoreRT differences. With all of the different configurations we have, though, it seemed like a decent way to identify which files would be included in which configurations just by the file names.

**Comment by weshaggard** [comment]
I agree we have some room to improve consistency. We the guidelines posted at https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/project-guidelines.md#code-file-naming-conventions but I'm good with updating them to more clearly identify when to use CoreCLR and to add CoreRT as an option as well. I do think the TargetGroup will still be a common one we use as well but I agree for the runtime specific forks we can use CoreCLR/CoreRT.

All I ask is that we update the guideline docs with the convention.
