### ISSUE TITLE
Re-enable and fix failing 60-70 Xsl checksum based tests

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/corefx#9877]
These tests are marked with ActiveIssue

This needs to be done as a part of dev/xml branch work

**Comment by danmosemsft** [comment]
The problem with the checksum approach is it's flaky and opaque when they fail. There are 60-70 tests disabled with this ID.

**Comment by AlexGhiondea** [comment]
@sepidehMS is this still something we need to do?

**Comment by sepidehMS** [comment]
@AlexGhiondea yes, these tests need to be re-written so that they no longer use checksum for verification.
