### ISSUE TITLE
Running tests for a single project on Linux

### ISSUE THREAD

**Issue by svick** [dotnet/corefx#9892]
I am trying to run tests for a single project on Ubuntu 16.04. I figured out that the command I need to run (assuming corefx is in `~/corefx`) is:

`~/corefx/Tools/dotnetcli/dotnet ~/corefx/Tools/MSBuild.exe /t:BuildAndTest /p:TestNugetRuntimeId=ubuntu.16.04-x64 /p:OSGroup=Linux /p:TargetOS=Linux`

As far as I can tell, this is not documented anywhere and I think it should be, probably in [unix-instructions.md](https://github.com/dotnet/corefx/blob/master/Documentation/building/unix-instructions.md).

Also, I think it's confusing that [the default for `TestNugetRuntimeId` is `win7-x64`](https://github.com/dotnet/buildtools/blob/acf2600/src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets#L18), even on Linux. Should it be changed to detect the OS? The same applies to `OSGroup` and `TargetOS`.

**Comment by mellinoe** [comment]
Yeah, this stuff is a bit confusing right now. I think some of the parameters you pass there are unnecessary. It looks like `TestNugetRuntimeId` is overridden in [dir.props](https://github.com/dotnet/corefx/blob/master/dir.props#L330), but it always seems to use ubuntu14.04-x64, which isn't right in your case. I also believe `TargetOS` is auto-detected [in a buildtools task](https://github.com/dotnet/buildtools/blob/7943606a52f3e1de51770cbd97f4f5a302249bf7/src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets#L295), ([source](https://github.com/dotnet/buildtools/blob/3afdd3e6319beaa0a59d7f6b3f1538e5b46e8055/src/Microsoft.DotNet.Build.Tasks/GetTargetMachineInfo.cs)) assuming you don't specify it.

I've always been able to do this by just specifying `OSGroup=Linux` (or OSX). I'm not sure about the hard-coding of ubuntu14.04-x64 in dir.props, though; seems wrong to me. There may be some other targets somewhere that I am forgetting about.

@joperezr Anything else I'm forgetting?

**Comment by mellinoe** [comment]
To close this out, the way to run a single project's tests right now is to run:

```
msbuild /t:rebuildandtest /p:OSGroup=Linux /p:testnugetruntimeidentifier=ubuntu.16.04-x64
```
