### ISSUE TITLE
Enable CoreFX test runs on OneCoreUAP images for x86 and x64

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/corefx#9917]
CC @weshaggard @joshfree

**Comment by gkhanna79** [comment]
@JohnChen0 Now that you have been able to do a CoreFX run on Nano, can you also look into running CoreFX tests on OneCoreUAP once we are done with Reverse Forwarders work?

**Comment by mellinoe** [comment]
@gkhanna79 @JohnChen0 Are we still actively looking at this for 1.2.0?

**Comment by gkhanna79** [comment]
Yes, @JohnChen0 will look into enabling this for 1.2.0.

**Comment by karelz** [comment]
@gkhanna79 who can look at it for 2.0?

**Comment by gkhanna79** [comment]
@wtgodbe should be able to look into this.

**Comment by mellinoe** [comment]
@gkhanna79 @wtgodbe Could you give a rough estimate of the work remaining for this? (Just trying to get a sense of the time needed for current "area-Infrastructure" issues).

**Comment by gkhanna79** [comment]
I would say a sprint.

**Comment by karelz** [comment]
I assume OneCoreUAP has nothing to do with UWP=2.1, right?

**Comment by gkhanna79** [comment]
We will need to bring it up for that.



Thanks,
Gaurav


-------- Original message --------

**Comment by karelz** [comment]
Would it make more sense track it as 2.1 issue then?

**Comment by gkhanna79** [comment]
Sounds good to me.


Thanks,
Gaurav

**Comment by karelz** [comment]
Done, BTW: @mellinoe OneNote with costing updated.

**Comment by wtgodbe** [comment]
@gkhanna79 I'm unclear what this entails, what does resolving this issue look like?

**Comment by danmosemsft** [comment]
@gkhanna79 same question - is this different to what we've already done recently?

**Comment by gkhanna79** [comment]
This is about running tests on OneCoreUAP images, similar to how we do it for Nano. Doing this will enable us to get coverage for any OS SKU built over OneCoreUAP (e.g. Holo*, Phone, IoTCore, etc).

**Comment by danmosemsft** [comment]
@wtgodbe I'm assuming this isn't required to ship UWP. Correct me if I'm wrong.

**Comment by gkhanna79** [comment]
This is not required for shipping UWP. However, we should get to it since it allows us to enable testing on fundamental Windows SKUs (e.g. OneCoreUAP) that will allow us to test once for all other SKUs that maybe built over it. Not doing so will force us to figure out how to test .NET Core for XBox if that ever happens.

**Comment by wtgodbe** [comment]
Looks like we haven't had any traction on this a while, closing.
