### ISSUE TITLE
Expose XmlTextReaderImpl.DetectEncoding as more general API (also for text files)

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#9920]
Seems pretty useful.
cc: @tarekgh

**Comment by tarekgh** [comment]
This is not a generic method that can detect any supported encoding. this is useful only for Unicode encoding detection (UTF8, UTF16,...etc.) I am not sure how useful this will be and which scenario will really need it

**Comment by krwq** [comment]
@tarekgh, true, I understand it needs improvement. Here is an example scenario:
- replace a single string in all files under specified directory
simplest algorithm for single file would be:
- File.WriteAllText(..., File.ReadAllText(...).Replace(...)) - that messes up encoding - when you think about it there is no really clean way to do it without messing with detection of encoding (or at least I don't know any obvious one)

**Comment by tarekgh** [comment]
@krwq when calling File.ReadAllText, either you not passing encoding and at that time will assume he encoding is UTF8, or explicitly you pass the encoding. in both cases you already knows the encoding of the file. so there is no detection is really needed. am I missing something?

**Comment by krwq** [comment]
@tarekgh, When you are calling ReadAllText decoding is automatically detected when calling WriteAllText some random encoding is being picked or you need to know what the automatically detected encoding was - that part is completely missing

**Comment by tarekgh** [comment]
> When you are calling ReadAllText decoding is automatically detected but never given to user. 

I don;t think so. look at the implementation
https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.IO.FileSystem/src/System/IO/File.cs#L354 

and you'll find it will just use UTF8

**Comment by krwq** [comment]
sounds to me like both would be useful :) that is pretty common scenario to automate changing files. Perhaps couple of helper APIs:
```csharp
Encoding File.DetectEncoding(string filePath); // perhaps also/alternatively: Encoding.DetectFromFile(string filePath)
string File.ReadAllText(string filePath, out Encoding detectedEncoding);
```

**Comment by tarekgh** [comment]
@krwq I suggest you close this one as I don't think it is really useful. and if we want to do teh detection to all encoding this is not easy to do and never proven to work correctly.

**Comment by krwq** [comment]
@tarekgh I do not agree this is not useful. Writing simple tool like:
- read text from a file
- modify text
- saves with the same encoding
is currently not reliable and we make users implement encoding detection by themselves which is even worse than if we figure out some mostly working implementation.

I think it is better to provide algorithm which works 90% of the cases and supports adding new encodings so that if someone does something not standard it will still be possible to implement their thing.

We could do something like this for encoding detection (+ couple of options to be able to reconfigure heuristics), the default implementation would be something like:
```
API: Encoding Encoding.DetectEncoding(Stream stream)
- iterate on encoding preambles for all known encodings and if any matches the stream beginning then return this encoding (we could generate directed graph or check most common options first to speed this up)
- iterate on user added encodings (apis for adding those need to be available) - same logic as above
- [assume utf8 no bom] check if stream contains any invalid utf8 characters (127, incomplete surrogates, forbidden unicode ranges etc)
- return default value
```

**Comment by tarekgh** [comment]
You are thinking on just one encoding and not all encodings. thinking about Unicode only is not that useful.

just to mention Encoding detection is really very complex issue and never worked fine. I am telling from my experience with that before. 

having 
```
Encoding Encoding.DetectEncoding(Stream stream)
```

do you know how it can detect shift_jis encoding for instance?

if you want to go ahead and try it be ready for that and also should have enough justification of doing it.

**Comment by krwq** [comment]
@tarekgh, the point is not to make perfect solution but something which works most of the time and works as well as most of the text editors. I believe this will make C# more useful for scripting than it is right now. Currently IMO the most interesting scenario of find & replace is broken as you cannot reliably save files.

Perhaps some find&replace APIs which would work on bytes would make this problem be reduced to minimum

**Comment by tarekgh** [comment]
I am not seeing any value when having BOM in the file because first most of the time (the main stream scenarios) the files don't include BOMs. second it is easy for the users to check that.

**Comment by stephentoub** [comment]
@tarekgh, what is the recommended code I should write if I want to read all of the lines from a file, modify one of them, and write them all back, preserving the original file's encoding?

**Comment by tarekgh** [comment]
> what is the recommended code I should write if I want to read all of the lines from a file, modify one of them, and write them all back, preserving the original file's encoding?

Today when you do File.ReadAllLines will open the file as UTF8 even if it is ansi encoded which is fine in 99% of the cases because when writing back after inserting a few text in the middle the bytes will be exactly preserved (because we convert the bytes from UTF8 to UTF16 when reading and we do the opposite when writing which should produce the exact original byte stream).

we have to be aware the inserted new text in the file will be encoded by UTF8 bytes and not the encoding of the file. also I mentioned 99% of the cases work because there is a chance to get some bytes that can cause some conversion issue like not well formed surrogate bytes.

Also StreamReader has a constructor which tell if need teh stream auto-detect the streams which has BOM on it.

**Comment by stephentoub** [comment]
> which is fine in 99% of the cases

This is not my experience.  I'm frequently writing tools to process all of the files in corefx, for example, and the moment I hit one that wasn't UTF8 encoded, characters get messed up, VS warns me about a change in the file's encoding, etc.  Whereas I initially do something simple like:
```C#
string contents = File.ReadAllText(path);
contents = Manipulate(contents);
File.WriteAllText(path, contents);
```
I end up doing something more complicated like:
```C#
string contents;
Encoding enc;
using (var reader = new StreamReader(path))
{
    contents = reader.ReadToEnd();
    enc = reader.CurrentEncoding;
}
contents  = Manipulate(contents);
File.WriteAllText(path, contents, enc);
```
and even then I'm not sure that's actually correct.  So... is that the recommended approach?

Your position appears to be that we don't want/need new APIs here, which may be correct... in which case, when someone needs to manipulate the contents of a file while preserving its original encoding, what is the pattern they should follow?  What sample should be in MSDN for that? Etc.

**Comment by tarekgh** [comment]
the way you are doing is really reading the file as UTF8 and writing it as UTF8. I may misspelled something in my last reply but this is what I really meant. when reading the stream and get it as strings it will be converted (from UTF8) to Unicode 16 but when writing you'll need to convert the contents back to UTF8 and that what you have done. if you write the file without specifying the encoding will be written as UTF16 which will be different.

> what is the pattern they should follow? What sample should be in MSDN for that? Etc.

- if you know the file encoding, specify the encoding when reading/Writing to the stream.
- if the encoding is not known, open the stream with public 
StreamReader(	string path, Encoding encoding, bool detectEncodingFromByteOrderMarks, int ufferSize)

and pass true for detectEncodingFromByteOrderMarks and pass Encoding.Default for the encoding parameter. note if you are using net core, you need to use S.T.E.Codepages provider to get the actual default encoding on Windows and not UTF8. 

I am not sure if System.IO docs has any sample doing exactly your scenario, but it has a lot of samples how to open files with different encodings.

**Comment by tarekgh** [comment]
forgot to say in my second bullet, you still need to get the encoding value from the stream and then use it  while writing to the file.

**Comment by krwq** [comment]
I talked with @tarekgh about this couple of times. I do believe the solution @stephentoub provided is slightly inconvenient and possibly incorrect if there is no BOM in the file but giving a user heuristically detected encoding in the corefx would probably be even worse from maintenance point of view - fuzzy logic is simply problematic.

I think this would be useful addition but corefx is probably not a right place for this.
