### ISSUE TITLE
build.sh fails on Arch Linux because Blob missing

### ISSUE THREAD

**Issue by paulcbetts** [dotnet/corefx#9928]
init-tools.log:

```
Running: /home/paul/code/paulcbetts/corefx/init-tools.sh
Installing 'https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview2-002733/dotnet-dev-arch.-x64.1.0.0-preview2-002733.tar.gz' to '/home/paul/code/paulcbetts/corefx/Tools/dotnetcli/dotnet.tar'
Running: /home/paul/code/paulcbetts/corefx/Tools/dotnetcli/dotnet restore "/home/paul/code/paulcbetts/corefx/Tools/1.0.25-prerelease-00517-05/project.json" --packages /home/paul/code/paulcbetts/corefx/packages --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json
Running: /home/paul/code/paulcbetts/corefx/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00517-05/lib/init-tools.sh /home/paul/code/paulcbetts/corefx /home/paul/code/paulcbetts/corefx/Tools/dotnetcli/dotnet /home/paul/code/paulcbetts/corefx/Tools
```

```
paul@io:~/code/paulcbetts/corefx/Tools/dotnetcli% cat dotnet.tar 
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:ccf4fbc2-0001-0128-1f9c-d9576f000000
Time:2016-07-09T04:47:08.2585465Z</Message></Error>
```

**Comment by svick** [comment]
It seems you're using Arch Linux, which is not currently supported.

**Comment by paulcbetts** [comment]
@svick I can build coreclr successfully, it'd be cool if I could point corefx to a from-source built repo on my local machine

**Comment by svick** [comment]
@paulcbetts You might be interested in the process outlined here: https://github.com/dotnet/coreclr/issues/917#issuecomment-231723500 by @jasonwilliams200OK. Though it's fairly byzantine and not complete yet.

**Comment by paulcbetts** [comment]
This would be really great to get working, the build process for Mono is very straightforward to build all of the runtime + BCL + compiler, whereas coreclr seems to be extremely difficult. While I understand why you don't want the monorepo thing, it'd be great to have a top level "fake" repo that just has submodules and build scripts that wire everything together.

**Comment by jasonwilliams200OK** [comment]
+10000 for:

> have a top level "fake" repo that just has submodules and build scripts that wire everything together.

**Comment by mellinoe** [comment]
This is part of the general "how to I build on an unsupported distro" discussion. Unfortunately, we don't have a good story for this right now, but we are working on it.

**Comment by jaen** [comment]
@mellinoe Is there any issue to track progress on this? I'd be happy to help with it if somehow possible, as it would let me run the backend server we develop at work in C# core (I use Arch Linux and while I can get 1.0.0-preview2-003131 to run, no such luck for 1.1).
