### ISSUE TITLE
Inconsistent default access mode for Package.Open(Stream) between .Net Core and .Net Framework

### ISSUE THREAD

**Issue by svick** [dotnet/corefx#9932]
The default access mode for `Package.Open(Stream)` is `ReadWrite` on .Net Core, while it's `Read` on .Net Framework. This means that a program that runs on one can fail on the other, in both directions.

In my case, I have code like:

```c#
Package.Open(File.OpenRead(path));
```

[This code](https://gist.github.com/svick/0dfbcef372c72127df791de8f4d1b471) runs successfully with `dotnet run -f net46`, but throws with `dotnet run -f netcoreap1.0`:

```
Unhandled Exception: System.ArgumentException: Update mode requires a stream with read, write, and seek capabilities.
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode packageFileMode, FileAccess packageFileAccess)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess)
   at System.IO.Packaging.Package.Open(Stream stream)
   at ConsoleApplication.Program.Main(String[] args)
```

The cause seems to be that on .Net Framework [`Package.Open(Stream)` calls ` Open(stream, _defaultStreamMode, _defaultStreamAccess)`](http://referencesource.microsoft.com/#WindowsBase/Base/System/IO/Packaging/Package.cs,226), where `_defaultStreamAccess` is `FileAccess.Read`, while on .Net Core, [`Package.Open(Stream)` calls `Open(stream, s_defaultStreamMode)`](https://github.com/dotnet/corefx/blob/83432af/src/System.IO.Packaging/src/System/IO/Packaging/Package.cs#L149), which in turn calls `Open(stream, packageMode, s_defaultFileAccess)`, where `s_defaultFileAccess` is `FileAccess.ReadWrite`.

I'm not sure how could this be fixed without breaking compatibility on .Net Core or .Net Framework.

**Comment by stephentoub** [comment]
cc: @EricWhiteDev

**Comment by ianhays** [comment]
It's worth noting that the [first porting commit](https://github.com/dotnet/corefx/commit/f77d4bb33670c504a8ed5e5e0dfc4d7663e279c1#diff-afdf1dce8e2e9738035ae8906efd9cc0R239) brought this function over correctly, then it looks like @EricWhiteDev may have mistakenly modified the behavior in [his cleanup commit](https://github.com/dotnet/corefx/commit/c22894be815a3b6419c05849828cad47f6c19e8b#diff-afdf1dce8e2e9738035ae8906efd9cc0R174).

Either way, we should fix it to be in line with desktop.
