### ISSUE TITLE
Change System.Json version number to match Mono?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#9938]
From @ericstj here: https://github.com/dotnet/corefx/pull/9897/files/391dae1d0f3789e0c11190f357e02fbcc03570db#r70150707

> I think this version needs to match the version xamarin has inbox (2.0.5.0). We should test that.

**Comment by ericstj** [comment]
Test here would be to create a PCL that references System.Json, then try and use it in any Xamarin project.   Find out if it gets a ref/def exception or a build error or if it just works.

You may need to consider this for all "classic" assemblies being added. I see System/System.Core/mscorlib all have lower versions.

**Comment by danmosemsft** [comment]
@joperezr sounds like a global pass may be needed.

**Comment by weshaggard** [comment]
@marek-safar @akoeplinger can correct me if I'm wrong but my understand is they always unify references for anything in their unification table (https://github.com/mono/mono/blob/master/mono/metadata/assembly.c#L88) to 4.0.0.0. However I don't see System.Json in that list so I guess we would need to match assembly versioning if we wanted the .NET Core implementation/references to work on mono/Xamarin.
