### ISSUE TITLE
UWP-EF-SQlite (Not compatible with Prism Framework)

### ISSUE THREAD

**Issue by mikemarango** [dotnet/corefx#9949]
For some strange reason on a Blank App(UWP) with suggested (temporary)fixes solved the issues in 5.2. with SQLite on closely following the docs. However the fixes break the xaml designer when the Prism framework i.e. prism 6.1.0, unity 4.0.1 and on VS update 3 is applied. "GridView, Stackpanel ... Etc cannot be children of the Grid" is the error message. It's not just the grid but most layout controls seems to broken. And this might not be just prism but it seems also on Template 10 according to this..https://github.com/Windows-XAML/Template10/issues/1109

**Comment by saurabh500** [comment]
@mikemarango Is this an issue with SQLite or XAML? 

cc @divega for SqlLite.

**Comment by mikemarango** [comment]
@saurabh500 It's an issue with Xaml. The Grid doesn't accept child elements. However everything else works as per the document guidelines. I suspect it's an issue with the compression. 
When I apply the same backend code to a blank app UWP, The xaml designer works just fine. I can add child elements like the gridview, stackpanel, etc as usual without a problem. My hunch .... Is Either the app.config or the addition of the following lines of code in project.json
"dependencies": {

    "runtime.native.System.IO.Compression": "4.1.0",
    "runtime.win7.System.Private.Uri": {
      "version": "4.0.1",
      "exclude": "runtime"
    },
    "System.Private.Uri": "4.0.0"
}

does not play nice with Prism/Unity code.

**Comment by saurabh500** [comment]
@joshfree  @stephentoub This is not a System.Data related issue. Can you help direct this to the right team?

**Comment by timheuer** [comment]
@mikemarango can you point me to a VS project that has this error with the markup?  Or help me understand the clear repro steps?  This made it my way and I want to help, but it is unclear to me what the setup here is.  "Blank project with fixes applied" is foreign to me.  If you could provide a VS project that has the issue I can take a look.

**Comment by danmosemsft** [comment]
Closing as no repro.
