### ISSUE TITLE
450+ warnings on a build!

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#9952]
They're all currently of the form:
```
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
```
or:
```
D:\j\workspace\windows_nt_debug88592b53\Tools\packageresolve.targets(74,5): warning : Your project is not referencing the ".NETCoreApp,Version=v1.0" framework. Add a reference to ".NETCoreApp,Version=v1.0" in the "frameworks" section of your project.json, and then re-run NuGet restore.
```
but it makes it really hard to spot important warnings.

Replaces https://github.com/dotnet/corefx/issues/9464

cc: @weshaggard, @ericstj, @joperezr, @karajas

**Comment by ericstj** [comment]
@stephentoub do you have VS Update 3 installed?

**Comment by stephentoub** [comment]
> do you have VS Update 3 installed?

Yes.

And I'm seeing the warnings both locally and in CI.

**Comment by stephentoub** [comment]
e.g. you can see them in the latest Win8 run here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug/835/consoleText
456 warnings

**Comment by ericstj** [comment]
Yeah, I suspect most of these are from @karajas's test work.  Just wanted to confirm you had the updated VS because using old targets can also cause these warnings.

**Comment by karajas** [comment]
Working on resolving this, updating the TestSuite package to use the RTM version should resolve most of the resolution issues.

**Comment by RussKeldorph** [comment]
@karajas Do you have a status update or ETA?  Is your work likely to help with dotnet/coreclr#6022 as well?  If there's another issue tracking this work more closely, please link it.

**Comment by weshaggard** [comment]
@karajas I'm also curious of the status of this issue as having this many warnings in the build is not a good place to be as it hides other new warnings from users.

**Comment by RussKeldorph** [comment]
@karajas Could we just suppress these somehow for now while we look for a proper fix (assuming suppression isn't the proper fix)?  Presumably a local-to-coreclr/corefx suppression would be desirable as opposed to removing the warning from whatever tool is issuing it, but at this point any solution would be   an improvement over the situation we are in now.

**Comment by karajas** [comment]
This requires a update to the xunit.netcore.extensions package so that it restores for netstandard1.1 (the minimum version it supports) instead of netstandard1.3. This is what was causing a large list of warnings of all the projects that depended on this package to build. Currently testing the fix, but I also need to verify that it gets rid of some of the non-related warnings.

**Comment by weshaggard** [comment]
@karajas re-opened this until you can get this into corefx and we see CI with no-warnings.

**Comment by karajas** [comment]
Sorry I didn't realize merging would close this issue.

**Comment by karajas** [comment]
More clean up: https://github.com/dotnet/corefx/pull/10605

**Comment by karajas** [comment]
After getting #10605 merged, the remaining warnings from CI for all OSes were 

`EXEC : warning : Test connection strings not defined! Tests cannot be run. [/mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_debug_prtest/src/System.Data.SqlClient/tests/ManualTests/System.Data.SqlClient.ManualTesting.Tests.csproj]`

**Comment by weshaggard** [comment]
@saurabh500 can you speak to that warning?

**Comment by saurabh500** [comment]
cc @corivera who made the change.
We have tests which depend on an environment variable being defined. When the environment variable is not defined the test is skipped.
The Attribute defined for this behavior is https://github.com/dotnet/corefx/blob/0532442d684e62fa26f4dc849da7f9f2acd1ea38/src/System.Data.SqlClient/tests/ManualTests/DataCommon/CheckConnStrSetupFactAttribute.cs 

The PR for the behavior is https://github.com/dotnet/corefx/pull/9523
