### ISSUE TITLE
Support to run selected tests in run-test.sh

### ISSUE THREAD

**Issue by jyoungyun** [dotnet/corefx#9958]
Add --test-dir option to run selected tests only.
To run given tests only, add '--test-dir' option to run-test.sh.

The existing '--restrict-proj' option compares all test list to jugde if it runs or not.
And it runs only matched tests with regex.
If there is no matched rule among tests, this option will be useful.

I will post PR soon.

**Comment by jyoungyun** [comment]
Leave a comment

**Comment by mellinoe** [comment]
@jyoungyun Were you still planning on adding this filtering feature? I believe we aren't using `run-test.sh` anywhere in our main test runs.

**Comment by mellinoe** [comment]
I'm going to close this for now. The official CI and official runs on our side are not using `run-tests.sh` at all, and we've been moving away from it for a while.
