### ISSUE TITLE
Port System.Security.Cryptography.DSA 

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#9982]
```
T:System.Security.Cryptography.DSA	
```
Contract is System.Security.Cryptography.Algorithms.
Windows: Port DSACng. 
Unix: All new code.  
Tests: Some tests exist in RedZone Desktop suite, needs a whole lot of tests.

**Comment by bartonjs** [comment]
Duplicate of #4813.  Updated metadata on that issue.
