### ISSUE TITLE
Port System.Security.Cryptography.HashAlgorithm

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#9983]
```
T:System.Security.Cryptography.HashAlgorithm (ICryptoTransform / incremental hashing)
F:System.Security.Cryptography.HashAlgorithm.HashValue
F:System.Security.Cryptography.HashAlgorithm.State
```

The incremental hashing methods and ComputeHash together can produce unexpected data and break the incremental hash state machine.  In .NET Core 1.0 the incremental part was moved to a new type and the ICryptoTransform declaration was removed.  Presumably requires bug-for-bug compat with Framework, and lots of bug-verifying tests.

The other two are required for incremental hash mainly.  Or derived types as a secondary thing.

**Comment by steveharter** [comment]
FYI the list of new members
public abstract partial class HashAlgorithm : System.IDisposable, System.Security.Cryptography.ICryptoTransform
     {
+        protected internal byte[] HashValue;
+        protected int State;
+        public virtual bool CanReuseTransform { get { return default(bool); } }
+        public virtual bool CanTransformMultipleBlocks { get { return default(bool); } }
+        public virtual byte[] Hash { get { return default(byte[]); } }
+        public virtual int InputBlockSize { get { return default(int); } }
+        public virtual int OutputBlockSize { get { return default(int); } }
+        public int TransformBlock(byte[] inputBuffer, int inputOffset, int inputCount, byte[] outputBuffer, int outputOffset) { return default(int); }
+        public byte[] TransformFinalBlock(byte[] inputBuffer, int inputOffset, int inputCount) { return default(byte[]); }
     }
