### ISSUE TITLE
Lots of code duplication/type unsafety/messiness in System.Collections tests

### ISSUE THREAD

**Issue by jamesqo** [dotnet/corefx#9989]
At the moment there appears to be a lot of messiness in the `System.Collections.*` tests. For example the tests [for each collection type](https://github.com/dotnet/corefx/blob/master/src/System.Collections/tests/Generic/HashSet/HashSet.Generic.cs) contains code related to generating the seed/explicitly saying what kinds of type parameters to test. This makes it very hard to add tests for new kinds of types.

<s>There is also a lot of `protected abstract` / `override` which makes the code hard to read without jumping back and forth between files, and things like [this](https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/Collections/IGenericSharedAPI.Tests.cs#L50-L55) are not typesafe and reduce readability, since the collection is passed as an argument to the method instead of the method being called on it (e.g. `Count(collection)` vs `collection.Count()`).</s>

I'm going to attempt to clean a lot of this code up, as part of #9379 and #9947.

**Comment by joshfree** [comment]
The collections tests are super old and can use a good scrubbing.  Many of those tests were written before .NET Framework 1.0, back when C# was still named Cool.  Thanks for taking a look at this space @jamesqo

**Comment by jamesqo** [comment]
@joshfree Really? I thought generics were only introduced in .NET 2.0...

**Comment by stephentoub** [comment]
> I thought generics were only introduced in .NET 2.0

I believe when you said System.Collections.*, I believe @joshfree took that to mean all collections... note that the generic collections are in the System.Collections.Generic namespace, whereas the collections actually in System.Collections are typically non-generic.  The assembly naming makes this a bit confusing.

> At the moment there appears to be a lot of messiness in the  System.Collections.*  tests. For example the tests for each collection type contains code related to generating the seed/explicitly saying what kinds of type parameters to test. This makes it very hard to add tests for new kinds of types.

Eye of the beholder I guess.  The tests you refer to were actually recently added by @hughbe and @ianhays.  I would like to avoid continually redoing such tests for stylistic reasons.

**Comment by ianhays** [comment]
>The tests you refer to were actually recently added by @hughbe and @ianhays. I would like to avoid continually redoing such tests for stylistic reasons.

Yeah, @hughbe and I added those this year. Coverage in the previous tests was lower and tests were copy/pasted between multiple files, making it difficult to change the expected behavior of *anything* without first hunting down ten tests. There were a few issues tracking a standardized Collections testing suite that all classes implementing an interface should adhere to, and that's what these tests do. Doing that means some potential uncleanliness (e.g. jumping between files to find the test source), but I'd far rather have that then have the same IList test duplicated a hundred times for every class that implements IList.

>For example the tests for each collection type contains code related to generating the seed/explicitly saying what kinds of type parameters to test. This makes it very hard to add tests for new kinds of types.

I think you want [HashSet.Generic.Tests.cs](https://github.com/dotnet/corefx/blob/master/src/System.Collections/tests/Generic/HashSet/HashSet.Generic.Tests.cs). That's where you would add tests that are independent of the generic type. The file you linked is so that we can test the HashSet with different generic parameters e.g. int/string that may have different behavior.

>things like this are not typesafe and reduce readability, since the collection is passed as an argument to the method instead of the method being called on it (e.g. Count(collection) vs collection.Count()).

There's a comment above that code describing why it's that way: 
```
        // There are a number of methods shared between Queue, and Stack for which there is no
        // common interface. To enable high code reuse, delegates are used to defer to those methods for 
        // checking validity.
```

again, it's so we minimize duplicate test assets for shared collections interfaces.

**Comment by hughbe** [comment]
@joshfree the tests have now been updated and are no longer the mess they were before. 

@jamesqo I agree that it is annoying having so many files and tests. One thing that we could do is consolidate the `CreateT` methods into a helper and call that for various types.

**Comment by jamesqo** [comment]
@ianhays 

> The file you linked is so that we can test the HashSet with different generic parameters e.g. int/string that may have different behavior.

Yeah, but IMO it's counterintuitive to have the same string/int generation logic copy-and-pasted between all the different collection files. I was thinking instead of having a generic test class we have to instantiate with specific types, we should make all of the *methods* in `IGenericSharedAPI_Tests` et al. generic instead, something like this:

```cs
public interface ICollectionCreator
{
    IEnumerable<T> Create<T>();
}

public abstract class IGenericSharedAPITestDriver
{
    protected static ICollectionCreator Creator { get; set; }

    [Theory]
    [MemberData(nameof(GenericTestData))]
    public void InitialSizeShouldBeZero<T>(T[] values)
    {
        var collection = CreateCollectionFromValues(values);
    }

    public static IEnumerable<object[]> GenericTestData()
    {
        yield return new object[] { new int[] { 1, 2, 3 } };
        yield return new object[] { new string[] { "Hello", "world" } };
    }

    private static IEnumerable<T> CreateCollectionFromValues<T>(T{] values)
    {
        var result = Creator.Create();
        foreach (var value in values) Add(result, value);
        return result;
    }
}

public class QueueCollectionCreator : ICollectionCreator
{
    public IEnumerable<T> Create<T>() => new Queue<T>();
}

public class QueueTestDriver : IGenericSharedAPITestDriver
{
    static QueueTestDriver()
    {
        Creator = new QueueCollectionCreator();
    }
}
```

That way we'd only have to be aware of specific types in the `iGenericSharedAPI` tests themselves, and we could get rid of all of the `*.Generic.cs` files.

> again, it's so we minimize duplicate test assets for shared collections interfaces.

What if we made an `ISharedApi<T>` interface wrapper around each collection?

```cs
protected abstract ISharedApi<T> SharedApiFactory(int count);

[Theory]
[MemberData(nameof(ValidCollectionSizes))]
public void Foo(int count)
{
    ISharedApi<T> enumerable = SharedApiFactory(count);
    Assert.Equal(count, enumerable.Count); // note: not Count(enumerable)
}

public class QueueSharedApi<T> : ISharedApi<T>
{
    private readonly Queue<T> _queue;

    public QueueSharedApi(Queue<T> queue) { _queue = queue; }

    public int Count => _queue.Count;
    public void Add(T value) => _queue.Add(value);
    // All the other virtual methods from IGenericSharedAPI.Tests...
}

public class QueueTestDriver : IGenericSharedAPITestDriver
{
    protected override ISharedApi<T> SharedApiFactory<T>(int count) => new QueueSharedApi<T>(new Queue<T>(count)):
}
```

**Comment by ianhays** [comment]
>Yeah, but IMO it's counterintuitive to have the same string/int generation logic copy-and-pasted between all the different collection files. 

I agree. I wasn't happy with the end design on that part and don't love the CreateT methods being duplicated. At the very least I think consolidating those would be an improvement.

>I was thinking instead of having a generic test class we have to instantiate with specific types, we should make all of the methods in IGenericSharedAPI_Tests et al. generic instead, something like this:

That would require a huge amount of changes. As Steve said, I'd really rather we not reinvent the wheel here unless it's going to bring a noticeable functional improvement or irrefutable stylistic improvement.

>What if we made an ISharedApi<T> interface wrapper around each collection?

The GenericSharedAPI tests are a bit unusual in their current state; I think there's room for clear improvement there. I rather like the idea of forcing the inheritance, so instead of having:
```
    public abstract class IGenericSharedAPI_Tests<T> : IEnumerable_Generic_Tests<T>
    {
...
        protected abstract int Count(IEnumerable<T> enumerable);
        protected abstract void Add(IEnumerable<T> enumerable, T value);
        protected abstract void Clear(IEnumerable<T> enumerable);
        protected abstract bool Contains(IEnumerable<T> enumerable, T value);
        protected abstract void CopyTo(IEnumerable<T> enumerable, T[] array, int index);
        protected abstract bool Remove(IEnumerable<T> enumerable);
...
        [Theory]
        [MemberData(nameof(ValidCollectionSizes))]
        public void IGenericSharedAPI_Count_Validity(int count)
        {
            IEnumerable<T> collection = GenericIEnumerableFactory(count);
            Assert.Equal(count, Count(collection));
        }
...
    }
```

we would have:
```
    public class ISharedApi<T> : IEnumerable<T>
    {
        public abstract int Count { get; }
        public abstract void Add(T value);
        public abstract void Clear();
        public abstract bool Contains(T value);
        public abstract void CopyTo(T[] array, int index);
        public abstract bool Remove();
    }
...
    public abstract class IGenericSharedAPI_Tests<T> : IEnumerable_Generic_Tests<T>
    {
...
        protected abstract ISharedApi<T> GenericISharedApiFactory(int count);
...
        [Theory]
        [MemberData(nameof(ValidCollectionSizes))]
        public void IGenericSharedAPI_Count_Validity(int count)
        {
            ISharedApi<T> collection = GenericISharedApiFactory(count);
            Assert.Equal(count, collection.Count);
        }
...
    }
```

**Comment by jamesqo** [comment]
I had two ideas I had since I last posted this issue to avoid the duplication.

## Idea 1

We could make use of partial classes instead of using inheritance, such that all of the specific type parameters are contained in the `Common` file. It would look something like this:

```cs
// IGenericSharedAPI.Tests.cs

public abstract partial class IGenericSharedAPI_Tests<T>
{
    private static List<Func<int, IEnumerable<T>> _generators = new List();

    public void EnumerateGenerators(Action<Func<int, IEnumerable<T>>> action)
    {
        _generators.ForEach(action);
    }

    [Theory]
    [MemberData(nameof(ValidCollectionSizes))]
    public void IGenericSharedAPI_Count_Validity(int count)
    {
        EnumerateGenerators(generator => // generator == GenericIEnumerableFactory
        {
            IEnumerable<T> collection = generator(count);
            Assert.Equal(count, Count(collection));
        });
    }
}

// All the type parameters are instantiated in the same Common file
public class IGenericSharedAPIStringTests : IGenericSharedAPI_Tests<string>
{
    protected override string CreateT(int seed) => ...
}

// Registry.cs (one for each test assembly)

public abstract partial class IGenericSharedAPI_Tests<T>
{
    static IGenericSharedAPI_Tests()
    {
        _generators.Add(count => new Queue<T>(count));
        _generators.Add(count => new Stack<T>(count));
        // ...
    }
}

// Queue.Generic.Tests.cs

public abstract partial class IGenericSharedAPI_Tests<T>
{
    // Queue specific tests...
}
```

It would be kinda complex, though, and you would not be able to inherit from the class w/o duplicating all the type params.

## Idea 2

Do the same as [the Vector tests](https://github.com/dotnet/corefx/blob/master/src/System.Numerics.Vectors/tests/GenericVectorTests.tt) and use a `.tt` file.

@ianhays @stephentoub do those sound like good ideas to any of you?

**Comment by ianhays** [comment]
We should be looking at making these tests *less* complex, not *more* complex, and I think either the Common file or the tt files would be going in the wrong direction in that regard. The purpose behind the Common collections tests is to provide an easy to use base set of tests that any collection implementing an interface should adhere to and an Inheritance test structure best aligns with that goal, imo.

The two best improvements here look to be:
- Add an ISharedAPI that implements IEnumerable and make the IGenericSharedAPI tests have a GenericISharedApiFactory instead of individual abstract methods for count, add, etc.
- Pull out the CreateT methods into a common file.

**Comment by jamesqo** [comment]
@ianhays 

> We should be looking at making these tests less complex, not more complex, and I think either the Common file or the tt files would be going in the wrong direction in that regard.

I think you'll change your mind when you see how much code duplication this would result in. [EqualityComparer.Default](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/EqualityComparer.cs#L36), which is used extensively by the standard collections, can return at least 7 different specialized comparers based on the type of T. Therefore, to have complete coverage with the current scheme, we'd need a minimum of 7 type instantiations per collection. That number can grow quickly when new type parameters/collections are added, and to add just one more type parameter you would have to edit the tests for *every* collection in CoreFX. Whereas if we put all the generic instantiations in Common, we'd only need to edit 1 file.

**Comment by karelz** [comment]
@jamesqo do you still plan to tackle it?

**Comment by jamesqo** [comment]
@karelz Yes, although I may not be able to get around to it for a while. If that's an issue you can remove the 'grabbed by community' tag.

**Comment by karelz** [comment]
Done. Whoever gets to it first, please ping us, so that we can mark/assign it properly. Thanks!

**Comment by stephentoub** [comment]
I'm not seeing much to actually do here.  If someone wants to improve the tests, great, but we don't need an issue tracking the potential.
