### ISSUE TITLE
Fill out BitArray

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#9994]
The following are in Xamarin but not Core

```
P:System.Collections.BitArray.Count
M:System.Collections.BitArray.get_Count
P:System.Collections.BitArray.IsReadOnly
M:System.Collections.BitArray.get_IsReadOnly
P:System.Collections.BitArray.IsSynchronized
M:System.Collections.BitArray.get_IsSynchronized
P:System.Collections.BitArray.SyncRoot
M:System.Collections.BitArray.get_SyncRoot
M:System.Collections.BitArray.Clone
M:System.Collections.BitArray.CopyTo(System.Array,System.Int32)
```

**Comment by Lixire** [comment]
Do I also need to implement these in src since they don't exist or do you just want these to do nothing when called?

**Comment by danmosemsft** [comment]
They should do whatever they do in Xamarin and Desktop. Get ILSPY (search internet) and open "c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\mscorlib.dll" then look for BitArray. You'll see what they do. You'll also note they're not explicit interface implmentations, they're implicit (you see "public ...")

**Comment by stephentoub** [comment]
> Get ILSPY

Decompiling isn't necessary.  The source is here:
http://referencesource.microsoft.com/#mscorlib/system/collections/bitarray.cs,19ad3f494f0dc7f6

**Comment by Lixire** [comment]
Done.
