### ISSUE TITLE
[dev/xml] Re-enable test when System.Globalization.SortKey is back

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/corefx#9997]
XmlStringSortKey class is missing from XmlSortKey right now. Bring this back if System.Globalization.SortKey is available.

The test (marked with ActiveIssue) should be re-enabled as well.

This needs to be done as part of dev/xml branch work.

**Comment by joshfree** [comment]
cc: @tarekgh

**Comment by tarekgh** [comment]
@danmosemsft is currently figuring out the schedule (when the work will be done and who will do it).

**Comment by danmosemsft** [comment]
@sokket has this one.

**Comment by danmosemsft** [comment]
@tarekgh Please enable when you have SortKey.

**Comment by tarekgh** [comment]
@sepidehMS SortKey should be exposed now on Windows platform but test cannot get compiled. please have a look to fix the compilation and mark the disabled test as 
        [PlatformSpecific(Xunit.PlatformID.Windows)] // Non Windows is not supported yet

and then you may assign this issue back to me so I can remove the platform specific attribute when I support SortKey on Linux based platforms

**Comment by sepidehMS** [comment]
@tarekgh  Test re-enabled for Windows via https://github.com/dotnet/corefx/pull/13222. Please enable the test for other platforms when available. (look for ActiveIssue9997)
Cases where `UpperFirst=true` should also be tested

**Comment by sepidehMS** [comment]
Tracking: Cases where `UpperFirst=true` should also be tested

**Comment by tarekgh** [comment]
@sepidehMS 

> Test re-enabled for Windows via #13222. Please enable the test for other platforms when available. (look for ActiveIssue9997)

I am not sure I understand the ask here. this is Xml test and should be enabled by you. what exactly you want me to do here?

**Comment by sepidehMS** [comment]
@tarekgh IIRC you told me before that SortKey is not yet available on Linux and the test should be only enabled in Windows right now. If that's the case, please just notify me when SortKey is available in Linux as well. Thanks.

**Comment by tarekgh** [comment]
@sepidehMS SortKey is already available on Linux.
